# Imports

In [1]:
import optuna
import pickle

import numpy as np
import pandas as pd

from tqdm import tqdm

from sklearn.metrics import balanced_accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold, cross_val_predict

/home/junior/Documentos/GitHub/kaggle-competition-predicting-student-health/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Utils

In [2]:
def load_pickle(file_path):
    with open(file_path, 'rb') as file:
        return pickle.load(file)

# Loading Datasets

In [3]:
X_train = pd.read_parquet('../data/processed/X_train_stacking_layer_one_model_90_trials.parquet')
y_train = pd.read_parquet('../data/interim/y_train.parquet')

X_test = pd.read_parquet('../data/processed/X_test_stacking_layer_one_model_90_trials.parquet')

In [4]:
X_train.head()

     lgbm_0    lgbm_1    lgbm_2     xgb_0     xgb_1     xgb_2
0  0.004927  0.001350  0.993723  0.003345  0.002030  0.994625
1  0.996682  0.000414  0.002905  0.996100  0.000521  0.003379
2  0.003205  0.000699  0.996095  0.002819  0.000623  0.996558
3  0.004065  0.003263  0.992672  0.003906  0.002117  0.993978
4  0.996028  0.000021  0.003951  0.995773  0.000024  0.004204

In [5]:
X_test.head()

     lgbm_0    lgbm_1    lgbm_2     xgb_0     xgb_1     xgb_2
0  0.010078  0.003001  0.986921  0.009916  0.003474  0.986609
1  0.457102  0.002879  0.540019  0.505986  0.002978  0.491037
2  0.998144  0.001284  0.000572  0.996786  0.002227  0.000987
3  0.988863  0.000017  0.011120  0.989342  0.000024  0.010634
4  0.006397  0.002261  0.991343  0.006481  0.001816  0.991703

# Machine Learning

In [6]:
label_encoder = load_pickle('../artifacts/label_encoder.pkl')

In [7]:
def objective(trial, X, y):

    w0 = trial.suggest_float('weight_class_0', 0.001, 10.0, log=True)
    w1 = trial.suggest_float('weight_class_1', 0.001, 10.0, log=True)
    w2 = trial.suggest_float('weight_class_2', 0.001, 10.0, log=True)
    weights = np.array([w0, w1, w2])

    proba = X.loc[:, ['xgb_0', 'xgb_1', 'xgb_2']].to_numpy()
    
    weighted_probas = proba * weights
    pred = np.argmax(weighted_probas, axis=1)
    
    score = balanced_accuracy_score(y, pred)

    return score


study = optuna.create_study(
    direction="maximize", 
    sampler=optuna.samplers.TPESampler(seed=42), 
    pruner=optuna.pruners.MedianPruner(n_warmup_steps=2)
)

study.optimize(
    lambda trial: objective(trial, X_train, y_train.health_condition), 
    n_trials=3000, 
    n_jobs=-1, 
    show_progress_bar=True
)

print("\nBest trial score:")
print(study.best_trial.value)

print("\nBest params:")
print(study.best_trial.params)

[I 2026-07-05 15:25:14,573] A new study created in memory with name: no-name-022348d8-1959-4af8-b4f2-deaf2f416eba

[I 2026-07-05 15:25:14,751] Trial 9 finished with value: 0.8359954623317479 and parameters: {'weight_class_0': 1.0262250085934133, 'weight_class_1': 0.022692496322119775, 'weight_class_2': 1.2534272435067007}. Best is trial 9 with value: 0.8359954623317479.
[I 2026-07-05 15:25:14,752] Trial 0 finished with value: 0.9042902733663016 and parameters: {'weight_class_0': 0.005020549289867377, 'weight_class_1': 0.008812353068512116, 'weight_class_2': 0.7476651336456264}. Best is trial 0 with value: 0.9042902733663016.
[I 2026-07-05 15:25:14,755] Trial 8 finished with value: 0.6748710997601813 and parameters: {'weight_class_0': 0.0014659705345561474, 'weight_class_1': 3.173629663963162, 'weight_class_2': 0.4028570326792345}. Best is trial 0 with value: 0.9042902733663016.
[I 2026-07-05 15:25:14,756] Trial 7 finished with value: 0.873672663936965 and parameters: {'weight_class_0': 1.897607694264434, 'weight_class_1': 4.781876988587423, 'weight_class_2': 0.049401410073672894}. Best is trial 0 with value: 0.9042902733663016.
[I 2026-07-05 15:25:14,758] Trial 11 finished with value: 0.9223172089397537 and parameters: {'weight_class_0': 0.012079054161114428, 'weight_class_1': 0.014688590501046586, 'weight_class_2': 0.09328557575943272}. Best is trial 11 with value: 0.9223172089397537.
[I 2026-07-05 15:25:14,760] Trial 1 finished with value: 0.5188222439846418 and parameters: {'weight_class_0': 5.394776874252505, 'weight_class_1': 0.027807988764081103, 'weight_class_2': 0.024065528243619207}. Best is trial 11 with value: 0.9223172089397537.
[I 2026-07-05 15:25:14,762] Trial 3 finished with value: 0.4377893353519999 and parameters: {'weight_class_0': 1.8650190363556063, 'weight_class_1': 0.0013860234779493577, 'weight_class_2': 0.006798639989285453}. Best is trial 11 with value: 0.9223172089397537.
[I 2026-07-05 15:25:14,765] Trial 2 finished with value: 0.8934412163685316 and parameters: {'weight_class_0': 0.019493713095515015, 'weight_class_1': 4.251562977147961, 'weight_class_2': 0.9046271657418715}. Best is trial 11 with value: 0.9223172089397537.
[I 2026-07-05 15:25:14,766] Trial 5 finished with value: 0.8620709152237783 and parameters: {'weight_class_0': 0.024709111072620086, 'weight_class_1': 0.005421732303674085, 'weight_class_2': 0.03764719197015035}. Best is trial 11 with value: 0.9223172089397537.
[I 2026-07-05 15:25:14,767] Trial 4 finished with value: 0.9478484421405583 and parameters: {'weight_class_0': 0.01306008960980352, 'weight_class_1': 0.5861634618754269, 'weight_class_2': 0.2863628943527067}. Best is trial 4 with value: 0.9478484421405583.
[I 2026-07-05 15:25:14,768] Trial 6 finished with value: 0.9491025903697642 and parameters: {'weight_class_0': 0.0031747213518500627, 'weight_class_1': 0.043826829259573506, 'weight_class_2': 0.056164232812141536}. Best is trial 6 with value: 0.9491025903697642.
[I 2026-07-05 15:25:14,769] Trial 10 finished with value: 0.5738753452837075 and parameters: {'weight_class_0': 5.991183636392007, 'weight_class_1': 0.0011972326375752945, 'weight_class_2': 0.1563642066320892}. Best is trial 6 with value: 0.9491025903697642.
[I 2026-07-05 15:25:14,921] Trial 13 finished with value: 0.9297989782835662 and parameters: {'weight_class_0': 0.11783247370201645, 'weight_class_1': 0.21619373671984274, 'weight_class_2': 7.922189890141396}. Best is trial 6 with value: 0.9491025903697642.

Best trial: 6. Best value: 0.949103:   1%|█▏                                                                                                                                     | 25/3000 [00:00<00:58, 51.13it/s]

[I 2026-07-05 15:25:14,937] Trial 12 finished with value: 0.8666488901783099 and parameters: {'weight_class_0': 0.12319742883265099, 'weight_class_1': 0.27707773646052486, 'weight_class_2': 0.0018023796172947418}. Best is trial 6 with value: 0.9491025903697642.
[I 2026-07-05 15:25:14,944] Trial 16 finished with value: 0.9326818870819559 and parameters: {'weight_class_0': 0.13617121120002784, 'weight_class_1': 0.2830288436029976, 'weight_class_2': 9.252355719307543}. Best is trial 6 with value: 0.9491025903697642.
[I 2026-07-05 15:25:14,950] Trial 15 finished with value: 0.9298280958903412 and parameters: {'weight_class_0': 0.0930291584857552, 'weight_class_1': 0.1897637018353295, 'weight_class_2': 7.768764192494065}. Best is trial 6 with value: 0.9491025903697642.
[I 2026-07-05 15:25:14,958] Trial 14 finished with value: 0.9324039667169447 and parameters: {'weight_class_0': 0.11605241414152075, 'weight_class_1': 0.2533253940696394, 'weight_class_2': 9.014989313721887}. Best is trial 6 with value: 0.9491025903697642.
[I 2026-07-05 15:25:14,973] Trial 17 finished with value: 0.9225953103607799 and parameters: {'weight_class_0': 0.16259701837272425, 'weight_class_1': 0.21052722273507699, 'weight_class_2': 6.196263010212849}. Best is trial 6 with value: 0.9491025903697642.
[I 2026-07-05 15:25:14,987] Trial 19 finished with value: 0.9359384994248146 and parameters: {'weight_class_0': 0.1401795648927767, 'weight_class_1': 0.3035481564713588, 'weight_class_2': 5.922437230797409}. Best is trial 6 with value: 0.9491025903697642.
[I 2026-07-05 15:25:14,991] Trial 18 finished with value: 0.934047653765381 and parameters: {'weight_class_0': 0.1459344182733356, 'weight_class_1': 0.2888980193487958, 'weight_class_2': 6.663753728287769}. Best is trial 6 with value: 0.9491025903697642.
[I 2026-07-05 15:25:15,013] Trial 20 finished with value: 0.9357416251414326 and parameters: {'weight_class_0': 0.11381874435785526, 'weight_class_1': 0.2449617009703477, 'weight_class_2': 5.014596368801215}. Best is trial 6 with value: 0.9491025903697642.
[I 2026-07-05 15:25:15,018] Trial 21 finished with value: 0.9287244428810079 and parameters: {'weight_class_0': 0.133843883698562, 'weight_class_1': 0.2267392331252893, 'weight_class_2': 7.6048503441458255}. Best is trial 6 with value: 0.9491025903697642.
[I 2026-07-05 15:25:15,055] Trial 23 finished with value: 0.8519914497283824 and parameters: {'weight_class_0': 0.11142315106018814, 'weight_class_1': 0.26951145492340195, 'weight_class_2': 0.0011575266799547014}. Best is trial 6 with value: 0.9491025903697642.
[I 2026-07-05 15:25:15,067] Trial 22 finished with value: 0.9337007020355373 and parameters: {'weight_class_0': 0.09836301885429849, 'weight_class_1': 0.28112083833236867, 'weight_class_2': 9.900294215033}. Best is trial 6 with value: 0.9491025903697642.
[I 2026-07-05 15:25:15,095] Trial 24 finished with value: 0.7640764097580774 and parameters: {'weight_class_0': 0.0016722784336073518, 'weight_class_1': 0.7893512008654628, 'weight_class_2': 0.011955830635824734}. Best is trial 6 with value: 0.9491025903697642.
[I 2026-07-05 15:25:15,107] Trial 25 finished with value: 0.7280988367597104 and parameters: {'weight_class_0': 0.0025799149952844772, 'weight_class_1': 1.3335106860176478, 'weight_class_2': 0.00956829306472125}. Best is trial 6 with value: 0.9491025903697642.

[I 2026-07-05 15:25:15,129] Trial 27 finished with value: 0.6646629892096141 and parameters: {'weight_class_0': 0.001129210428206735, 'weight_class_1': 1.308547626800867, 'weight_class_2': 0.013367084370190263}. Best is trial 6 with value: 0.9491025903697642.
[I 2026-07-05 15:25:15,147] Trial 26 finished with value: 0.7009190544190372 and parameters: {'weight_class_0': 0.001484594453220546, 'weight_class_1': 1.1046768529742093, 'weight_class_2': 0.013880036216438792}. Best is trial 6 with value: 0.9491025903697642.
[I 2026-07-05 15:25:15,157] Trial 28 finished with value: 0.6637456224557635 and parameters: {'weight_class_0': 0.001090148816953155, 'weight_class_1': 1.1550289227316919, 'weight_class_2': 0.010056180724328363}. Best is trial 6 with value: 0.9491025903697642.
[I 2026-07-05 15:25:15,174] Trial 29 finished with value: 0.7148843895071536 and parameters: {'weight_class_0': 0.0011113257949376145, 'weight_class_1': 0.8038632626694467, 'weight_class_2': 0.2565193859970058}. Best is trial 6 with value: 0.9491025903697642.
[I 2026-07-05 15:25:15,183] Trial 30 finished with value: 0.6655752981167543 and parameters: {'weight_class_0': 0.0011766020450672784, 'weight_class_1': 1.298258071988425, 'weight_class_2': 0.012770443673450529}. Best is trial 6 with value: 0.9491025903697642.
[I 2026-07-05 15:25:15,212] Trial 31 finished with value: 0.6633286351621464 and parameters: {'weight_class_0': 0.0010288593869167873, 'weight_class_1': 1.3000986659123508, 'weight_class_2': 0.014135639188463972}. Best is trial 6 with value: 0.9491025903697642.
[I 2026-07-05 15:25:15,220] Trial 32 finished with value: 0.6564073478840058 and parameters: {'weight_class_0': 0.0010205886150561271, 'weight_class_1': 1.1557599060251682, 'weight_class_2': 2.0688006596915627}. Best is trial 6 with value: 0.9491025903697642.
[I 2026-07-05 15:25:15,255] Trial 33 finished with value: 0.8316122824442163 and parameters: {'weight_class_0': 0.005749836650699285, 'weight_class_1': 0.06074377725079494, 'weight_class_2': 2.268321290000282}. Best is trial 6 with value: 0.9491025903697642.
[I 2026-07-05 15:25:15,266] Trial 35 finished with value: 0.846223708043207 and parameters: {'weight_class_0': 0.0072834645917118895, 'weight_class_1': 0.06261842837413266, 'weight_class_2': 2.5738039155591776}. Best is trial 6 with value: 0.9491025903697642.
[I 2026-07-05 15:25:15,274] Trial 34 finished with value: 0.848885489017964 and parameters: {'weight_class_0': 0.0065967071946543155, 'weight_class_1': 0.04997399691042702, 'weight_class_2': 2.2607458630864428}. Best is trial 6 with value: 0.9491025903697642.
[I 2026-07-05 15:25:15,288] Trial 36 finished with value: 0.7976787155320585 and parameters: {'weight_class_0': 0.005814597559477834, 'weight_class_1': 0.05598317197913604, 'weight_class_2': 2.748130358857467}. Best is trial 6 with value: 0.9491025903697642.

[I 2026-07-05 15:25:15,318] Trial 37 finished with value: 0.9467885834741393 and parameters: {'weight_class_0': 0.0065896810248238305, 'weight_class_1': 0.09809276697736391, 'weight_class_2': 0.2994126363784779}. Best is trial 6 with value: 0.9491025903697642.
[I 2026-07-05 15:25:15,335] Trial 38 finished with value: 0.8618500615874543 and parameters: {'weight_class_0': 0.00804827120223005, 'weight_class_1': 0.07352183344372198, 'weight_class_2': 2.5856379013556845}. Best is trial 6 with value: 0.9491025903697642.
[I 2026-07-05 15:25:15,354] Trial 39 finished with value: 0.7739354610244974 and parameters: {'weight_class_0': 0.0043725335934437885, 'weight_class_1': 0.05242204902844321, 'weight_class_2': 2.3963877341654594}. Best is trial 6 with value: 0.9491025903697642.
[I 2026-07-05 15:25:15,390] Trial 41 finished with value: 0.7910953223177152 and parameters: {'weight_class_0': 0.006139444823243132, 'weight_class_1': 0.08994240808894484, 'weight_class_2': 3.1240823760401537}. Best is trial 6 with value: 0.9491025903697642.
[I 2026-07-05 15:25:15,395] Trial 40 finished with value: 0.8227367593520901 and parameters: {'weight_class_0': 0.006109948024054546, 'weight_class_1': 0.07651813861850265, 'weight_class_2': 2.57430629707452}. Best is trial 6 with value: 0.9491025903697642.
[I 2026-07-05 15:25:15,415] Trial 42 finished with value: 0.9283794554489404 and parameters: {'weight_class_0': 0.03732328554179785, 'weight_class_1': 0.06891152888584598, 'weight_class_2': 2.8567230085832205}. Best is trial 6 with value: 0.9491025903697642.
[I 2026-07-05 15:25:15,435] Trial 44 finished with value: 0.9435265758007759 and parameters: {'weight_class_0': 0.034961352847485166, 'weight_class_1': 0.1066052920931046, 'weight_class_2': 0.495777654166199}. Best is trial 6 with value: 0.9491025903697642.
[I 2026-07-05 15:25:15,438] Trial 43 finished with value: 0.9435093178768875 and parameters: {'weight_class_0': 0.04168141497458081, 'weight_class_1': 0.12336611083460353, 'weight_class_2': 0.49663406226360984}. Best is trial 6 with value: 0.9491025903697642.
[I 2026-07-05 15:25:15,465] Trial 46 finished with value: 0.8827595833242768 and parameters: {'weight_class_0': 0.032470437408783505, 'weight_class_1': 0.0062045504820838916, 'weight_class_2': 0.5436668660077844}. Best is trial 6 with value: 0.9491025903697642.
[I 2026-07-05 15:25:15,480] Trial 45 finished with value: 0.942363465729574 and parameters: {'weight_class_0': 0.04014025057703668, 'weight_class_1': 0.11041037818164431, 'weight_class_2': 0.5084599765526714}. Best is trial 6 with value: 0.9491025903697642.
[I 2026-07-05 15:25:15,503] Trial 47 finished with value: 0.9450656091481026 and parameters: {'weight_class_0': 0.03400096767916639, 'weight_class_1': 0.12337346397775413, 'weight_class_2': 0.6141846155546686}. Best is trial 6 with value: 0.9491025903697642.
[I 2026-07-05 15:25:15,521] Trial 48 finished with value: 0.9457654003565293 and parameters: {'weight_class_0': 0.024866485739817486, 'weight_class_1': 0.10676925161333287, 'weight_class_2': 0.5711211537007818}. Best is trial 6 with value: 0.9491025903697642.

Best trial: 50. Best value: 0.949216:   2%|██▋                                                                                                                                   | 60/3000 [00:01<00:55, 53.25it/s]

[I 2026-07-05 15:25:15,532] Trial 49 finished with value: 0.9492074382487489 and parameters: {'weight_class_0': 0.03996246204149154, 'weight_class_1': 0.5135497916323853, 'weight_class_2': 0.6471103888272304}. Best is trial 49 with value: 0.9492074382487489.
[I 2026-07-05 15:25:15,557] Trial 50 finished with value: 0.9492158270674023 and parameters: {'weight_class_0': 0.04203559020585128, 'weight_class_1': 0.4731416249507893, 'weight_class_2': 0.6218243661322937}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:15,585] Trial 52 finished with value: 0.9444844982799062 and parameters: {'weight_class_0': 0.03759965995832841, 'weight_class_1': 0.12326204724244963, 'weight_class_2': 0.542866831612802}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:15,606] Trial 51 finished with value: 0.8765010891501918 and parameters: {'weight_class_0': 0.03858661104820507, 'weight_class_1': 0.004861294832419773, 'weight_class_2': 0.6644918170390034}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:15,613] Trial 53 finished with value: 0.9312655684275035 and parameters: {'weight_class_0': 0.015592401763461569, 'weight_class_1': 0.02637404502819412, 'weight_class_2': 0.0848522185794955}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:15,621] Trial 54 finished with value: 0.9339212337399055 and parameters: {'weight_class_0': 0.014771085295366434, 'weight_class_1': 0.027985069218365844, 'weight_class_2': 0.07240522370429667}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:15,642] Trial 55 finished with value: 0.9344301975137425 and parameters: {'weight_class_0': 0.014901132005962405, 'weight_class_1': 0.02848249912721865, 'weight_class_2': 0.07861213604017786}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:15,671] Trial 56 finished with value: 0.9221029946295703 and parameters: {'weight_class_0': 0.015869589332159803, 'weight_class_1': 0.019926423863911292, 'weight_class_2': 0.07849744218346821}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:15,689] Trial 57 finished with value: 0.948125692606777 and parameters: {'weight_class_0': 0.01136577315137458, 'weight_class_1': 0.4909445530103558, 'weight_class_2': 0.08430921459061096}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:15,704] Trial 58 finished with value: 0.9460851040225432 and parameters: {'weight_class_0': 0.016352283676750155, 'weight_class_1': 0.5238751930839256, 'weight_class_2': 1.0306650704618268}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:15,719] Trial 59 finished with value: 0.9295624351513404 and parameters: {'weight_class_0': 0.015017218785058257, 'weight_class_1': 0.028600709668882795, 'weight_class_2': 1.1305922316544583}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:15,741] Trial 60 finished with value: 0.9363436375623563 and parameters: {'weight_class_0': 0.015935007916000374, 'weight_class_1': 0.032088002422123896, 'weight_class_2': 0.10330441188576765}. Best is trial 50 with value: 0.9492158270674023.

[I 2026-07-05 15:25:15,761] Trial 61 finished with value: 0.9466424019276501 and parameters: {'weight_class_0': 0.06561510009994691, 'weight_class_1': 0.4577252430911696, 'weight_class_2': 0.26546545107338104}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:15,773] Trial 62 finished with value: 0.8715438212149375 and parameters: {'weight_class_0': 0.010550984082067932, 'weight_class_1': 2.7732181646356824, 'weight_class_2': 0.2822037465905952}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:15,812] Trial 63 finished with value: 0.9477534479027566 and parameters: {'weight_class_0': 0.05811362261205812, 'weight_class_1': 2.9138732386403587, 'weight_class_2': 1.0628384211753323}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:15,822] Trial 64 finished with value: 0.9330322458498356 and parameters: {'weight_class_0': 0.25327127605301747, 'weight_class_1': 0.48017528317939007, 'weight_class_2': 1.0531114351862647}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:15,834] Trial 65 finished with value: 0.9481355909244664 and parameters: {'weight_class_0': 0.06698205304227042, 'weight_class_1': 0.42290869260232056, 'weight_class_2': 1.06478281082459}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:15,854] Trial 66 finished with value: 0.8392862009934744 and parameters: {'weight_class_0': 0.010235669680502695, 'weight_class_1': 3.3400159239132323, 'weight_class_2': 0.17474326255156147}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:15,867] Trial 67 finished with value: 0.9462771520021301 and parameters: {'weight_class_0': 0.06453052881141048, 'weight_class_1': 2.2097917638311992, 'weight_class_2': 0.2574063181293271}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:15,879] Trial 68 finished with value: 0.9454986236603576 and parameters: {'weight_class_0': 0.067440619641267, 'weight_class_1': 0.4131035895893774, 'weight_class_2': 0.2537475246707946}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:15,917] Trial 70 finished with value: 0.9051307050504348 and parameters: {'weight_class_0': 0.002174639133782808, 'weight_class_1': 0.41399684564162276, 'weight_class_2': 0.18046665260748762}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:15,922] Trial 69 finished with value: 0.8684176764673408 and parameters: {'weight_class_0': 0.40588427796268195, 'weight_class_1': 0.41447015701269296, 'weight_class_2': 0.28133117833814525}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:15,941] Trial 71 finished with value: 0.8701679382215728 and parameters: {'weight_class_0': 0.3494865617762414, 'weight_class_1': 0.4353508223585346, 'weight_class_2': 0.15194265877477678}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:15,954] Trial 72 finished with value: 0.9192906137000346 and parameters: {'weight_class_0': 0.0030618304304688318, 'weight_class_1': 0.49400360369872065, 'weight_class_2': 0.03387765225707918}. Best is trial 50 with value: 0.9492158270674023.

Best trial: 50. Best value: 0.949216:   3%|███▊                                                                                                                                  | 84/3000 [00:01<00:50, 57.86it/s]

[I 2026-07-05 15:25:15,980] Trial 73 finished with value: 0.8940809466059415 and parameters: {'weight_class_0': 0.06347080094571489, 'weight_class_1': 2.0084772353862874, 'weight_class_2': 0.025084158419416067}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:16,003] Trial 74 finished with value: 0.8468563775454072 and parameters: {'weight_class_0': 0.06439028336212468, 'weight_class_1': 9.991115841938102, 'weight_class_2': 0.03820676636871568}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:16,018] Trial 75 finished with value: 0.8981427070469415 and parameters: {'weight_class_0': 0.24255789878535006, 'weight_class_1': 7.130996227852973, 'weight_class_2': 0.14228336171517914}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:16,036] Trial 76 finished with value: 0.8854710177317896 and parameters: {'weight_class_0': 0.20333566103835782, 'weight_class_1': 0.6970258276891433, 'weight_class_2': 0.025422702512719223}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:16,041] Trial 77 finished with value: 0.8844647966064835 and parameters: {'weight_class_0': 0.25746028239113145, 'weight_class_1': 5.670724318772607, 'weight_class_2': 0.03203602334967715}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:16,059] Trial 78 finished with value: 0.9488430619518059 and parameters: {'weight_class_0': 0.23856378195200895, 'weight_class_1': 5.248556874203131, 'weight_class_2': 1.5339063046900405}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:16,090] Trial 80 finished with value: 0.6692894200361823 and parameters: {'weight_class_0': 0.004295825019987599, 'weight_class_1': 8.980713205522498, 'weight_class_2': 1.6472879749407305}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:16,106] Trial 79 finished with value: 0.8997348666772558 and parameters: {'weight_class_0': 0.0036713195328209386, 'weight_class_1': 0.7374836113866234, 'weight_class_2': 0.03832743199958133}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:16,121] Trial 81 finished with value: 0.667791280820515 and parameters: {'weight_class_0': 0.0033177375001016527, 'weight_class_1': 6.740531924366777, 'weight_class_2': 1.3971639483873572}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:16,153] Trial 82 finished with value: 0.8155232002296834 and parameters: {'weight_class_0': 0.003918651329450783, 'weight_class_1': 0.7281653041926482, 'weight_class_2': 1.4896296389022912}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:16,157] Trial 83 finished with value: 0.8510089966484529 and parameters: {'weight_class_0': 0.004085790722865648, 'weight_class_1': 0.17159827261525004, 'weight_class_2': 1.4728715980822684}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:16,180] Trial 84 finished with value: 0.8227526071189605 and parameters: {'weight_class_0': 0.003462574375214909, 'weight_class_1': 0.164223667531336, 'weight_class_2': 1.501488973110182}. Best is trial 50 with value: 0.9492158270674023.

[I 2026-07-05 15:25:16,206] Trial 86 finished with value: 0.9382827581626261 and parameters: {'weight_class_0': 0.08290073120548137, 'weight_class_1': 0.18476610985475617, 'weight_class_2': 1.5478111576032347}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:16,208] Trial 85 finished with value: 0.808828179708386 and parameters: {'weight_class_0': 0.0038171725467537262, 'weight_class_1': 0.6841437007551611, 'weight_class_2': 1.548838184331392}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:16,245] Trial 87 finished with value: 0.8365136632170098 and parameters: {'weight_class_0': 1.0601961884415212, 'weight_class_1': 0.18575282319751954, 'weight_class_2': 0.8194605237303662}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:16,258] Trial 88 finished with value: 0.8336107054915773 and parameters: {'weight_class_0': 1.1836044638093335, 'weight_class_1': 0.17099025437619292, 'weight_class_2': 0.8598731980673622}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:16,267] Trial 89 finished with value: 0.9484167275104793 and parameters: {'weight_class_0': 0.023627983488788015, 'weight_class_1': 0.17188684207017962, 'weight_class_2': 0.372963807956036}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:16,289] Trial 90 finished with value: 0.9447906795366015 and parameters: {'weight_class_0': 0.02454930608031449, 'weight_class_1': 1.771346506431714, 'weight_class_2': 0.8984943236305154}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:16,313] Trial 91 finished with value: 0.9449085331893382 and parameters: {'weight_class_0': 0.02294024235922228, 'weight_class_1': 1.6573587625211674, 'weight_class_2': 0.7655940649772047}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:16,323] Trial 92 finished with value: 0.9464004249415883 and parameters: {'weight_class_0': 0.022969910665869554, 'weight_class_1': 0.16132740881900057, 'weight_class_2': 0.8246532259618125}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:16,337] Trial 93 finished with value: 0.8449752584082928 and parameters: {'weight_class_0': 0.7993711389557403, 'weight_class_1': 0.3294156831599798, 'weight_class_2': 0.41369405743632853}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:16,358] Trial 94 finished with value: 0.9061912529216644 and parameters: {'weight_class_0': 0.008779575144107985, 'weight_class_1': 1.681525695400357, 'weight_class_2': 0.38428769023878584}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:16,377] Trial 95 finished with value: 0.9447849694257741 and parameters: {'weight_class_0': 0.025221294321761036, 'weight_class_1': 1.8634073724007119, 'weight_class_2': 0.7826612189068514}. Best is trial 50 with value: 0.9492158270674023.
[I 2026-07-05 15:25:16,411] Trial 96 finished with value: 0.9447607175444223 and parameters: {'weight_class_0': 0.021721571107367055, 'weight_class_1': 1.7358728073966514, 'weight_class_2': 0.36359363784666}. Best is trial 50 with value: 0.9492158270674023.

[I 2026-07-05 15:25:16,424] Trial 97 finished with value: 0.9493896339152014 and parameters: {'weight_class_0': 0.023584446491276518, 'weight_class_1': 0.3168864236872407, 'weight_class_2': 0.36379589934123735}. Best is trial 97 with value: 0.9493896339152014.
[I 2026-07-05 15:25:16,452] Trial 98 finished with value: 0.9493200517560224 and parameters: {'weight_class_0': 0.02141039789654249, 'weight_class_1': 0.32076297414343513, 'weight_class_2': 0.36215180509125444}. Best is trial 97 with value: 0.9493896339152014.
[I 2026-07-05 15:25:16,461] Trial 99 finished with value: 0.9487750433846864 and parameters: {'weight_class_0': 0.04905704112808612, 'weight_class_1': 0.33337708825781737, 'weight_class_2': 0.366351024289841}. Best is trial 97 with value: 0.9493896339152014.
[I 2026-07-05 15:25:16,481] Trial 100 finished with value: 0.8161076299912172 and parameters: {'weight_class_0': 7.5838520331855, 'weight_class_1': 0.9958895581185321, 'weight_class_2': 0.3572559438653598}. Best is trial 97 with value: 0.9493896339152014.
[I 2026-07-05 15:25:16,500] Trial 101 finished with value: 0.9439028474016798 and parameters: {'weight_class_0': 0.04676245792310803, 'weight_class_1': 0.9466389327215906, 'weight_class_2': 4.151669116022873}. Best is trial 97 with value: 0.9493896339152014.
[I 2026-07-05 15:25:16,518] Trial 102 finished with value: 0.9423474242239154 and parameters: {'weight_class_0': 0.047383491081856285, 'weight_class_1': 0.3260294972226571, 'weight_class_2': 4.348530735420404}. Best is trial 97 with value: 0.9493896339152014.
[I 2026-07-05 15:25:16,534] Trial 103 finished with value: 0.6152309234891589 and parameters: {'weight_class_0': 8.891051040197352, 'weight_class_1': 0.040188357403111614, 'weight_class_2': 0.39561167230972505}. Best is trial 97 with value: 0.9493896339152014.
[I 2026-07-05 15:25:16,557] Trial 104 finished with value: 0.6235099003129585 and parameters: {'weight_class_0': 9.851487274913765, 'weight_class_1': 0.04318235873628527, 'weight_class_2': 4.1324297716457545}. Best is trial 97 with value: 0.9493896339152014.
[I 2026-07-05 15:25:16,573] Trial 105 finished with value: 0.7622418671443739 and parameters: {'weight_class_0': 7.567997899374507, 'weight_class_1': 0.32097129909991307, 'weight_class_2': 0.05522568092499949}. Best is trial 97 with value: 0.9493896339152014.
[I 2026-07-05 15:25:16,597] Trial 106 finished with value: 0.8812826956840468 and parameters: {'weight_class_0': 0.04721078020535548, 'weight_class_1': 0.5740697412018271, 'weight_class_2': 0.0031045021255708036}. Best is trial 97 with value: 0.9493896339152014.
[I 2026-07-05 15:25:16,611] Trial 107 finished with value: 0.9160106536175027 and parameters: {'weight_class_0': 0.048253566099976414, 'weight_class_1': 0.9544994377080976, 'weight_class_2': 0.05663378345397765}. Best is trial 97 with value: 0.9493896339152014.

Best trial: 116. Best value: 0.949662:   4%|█████▏                                                                                                                              | 118/3000 [00:02<00:54, 52.54it/s]

[I 2026-07-05 15:25:16,641] Trial 108 finished with value: 0.912962484303563 and parameters: {'weight_class_0': 0.0501618617529874, 'weight_class_1': 0.31668187502699485, 'weight_class_2': 0.055155052362874324}. Best is trial 97 with value: 0.9493896339152014.
[I 2026-07-05 15:25:16,655] Trial 109 finished with value: 0.9466759173643197 and parameters: {'weight_class_0': 0.049597213703248835, 'weight_class_1': 0.33884529475415803, 'weight_class_2': 0.20418884986216917}. Best is trial 97 with value: 0.9493896339152014.
[I 2026-07-05 15:25:16,674] Trial 110 finished with value: 0.9492653536635727 and parameters: {'weight_class_0': 0.029563112218402427, 'weight_class_1': 0.33582437424713535, 'weight_class_2': 0.2209289204144024}. Best is trial 97 with value: 0.9493896339152014.
[I 2026-07-05 15:25:16,683] Trial 111 finished with value: 0.9346847327498065 and parameters: {'weight_class_0': 0.030412183439958496, 'weight_class_1': 0.2324399005681097, 'weight_class_2': 0.061121336426834524}. Best is trial 97 with value: 0.9493896339152014.
[I 2026-07-05 15:25:16,711] Trial 112 finished with value: 0.9489397318546383 and parameters: {'weight_class_0': 0.030638936188668125, 'weight_class_1': 0.5722255606214394, 'weight_class_2': 0.20115151861900735}. Best is trial 97 with value: 0.9493896339152014.
[I 2026-07-05 15:25:16,728] Trial 113 finished with value: 0.9489510441273495 and parameters: {'weight_class_0': 0.03165386064109262, 'weight_class_1': 0.6073780108223344, 'weight_class_2': 0.20579760508328376}. Best is trial 97 with value: 0.9493896339152014.
[I 2026-07-05 15:25:16,746] Trial 114 finished with value: 0.9490751308990637 and parameters: {'weight_class_0': 0.029879287134173413, 'weight_class_1': 0.6038606802004057, 'weight_class_2': 0.20762435535625007}. Best is trial 97 with value: 0.9493896339152014.
[I 2026-07-05 15:25:16,766] Trial 115 finished with value: 0.9488254207889198 and parameters: {'weight_class_0': 0.08607267130532852, 'weight_class_1': 0.5877403942453651, 'weight_class_2': 0.6631643348708557}. Best is trial 97 with value: 0.9493896339152014.
[I 2026-07-05 15:25:16,782] Trial 116 finished with value: 0.9496618942354548 and parameters: {'weight_class_0': 0.011497214200171184, 'weight_class_1': 0.23341439036435124, 'weight_class_2': 0.11613409977018767}. Best is trial 116 with value: 0.9496618942354548.
[I 2026-07-05 15:25:16,806] Trial 117 finished with value: 0.9490368422938827 and parameters: {'weight_class_0': 0.02823062022897012, 'weight_class_1': 0.23366511529938913, 'weight_class_2': 0.207518817714016}. Best is trial 116 with value: 0.9496618942354548.
[I 2026-07-05 15:25:16,822] Trial 118 finished with value: 0.9483198066531838 and parameters: {'weight_class_0': 0.01881076896001569, 'weight_class_1': 0.568084819249147, 'weight_class_2': 0.11038308989999887}. Best is trial 116 with value: 0.9496618942354548.

Best trial: 129. Best value: 0.949725:   4%|█████▋                                                                                                                              | 128/3000 [00:02<00:53, 53.51it/s]

[I 2026-07-05 15:25:16,832] Trial 119 finished with value: 0.8973020805590212 and parameters: {'weight_class_0': 0.028979860731514553, 'weight_class_1': 0.012403101460321203, 'weight_class_2': 0.21459505727975595}. Best is trial 116 with value: 0.9496618942354548.
[I 2026-07-05 15:25:16,849] Trial 120 finished with value: 0.9473549764097536 and parameters: {'weight_class_0': 0.02890149871203628, 'weight_class_1': 0.6013776747918078, 'weight_class_2': 0.12573698653629362}. Best is trial 116 with value: 0.9496618942354548.
[I 2026-07-05 15:25:16,866] Trial 121 finished with value: 0.9494351599031488 and parameters: {'weight_class_0': 0.029250101123842197, 'weight_class_1': 0.5898994972481707, 'weight_class_2': 0.469822207363277}. Best is trial 116 with value: 0.9496618942354548.
[I 2026-07-05 15:25:16,887] Trial 122 finished with value: 0.945701769435039 and parameters: {'weight_class_0': 0.02957276827853204, 'weight_class_1': 0.6212269411875168, 'weight_class_2': 0.10363719952467373}. Best is trial 116 with value: 0.9496618942354548.
[I 2026-07-05 15:25:16,907] Trial 123 finished with value: 0.9457395509950035 and parameters: {'weight_class_0': 0.029098206420035435, 'weight_class_1': 0.5871019062143655, 'weight_class_2': 0.10162760258350775}. Best is trial 116 with value: 0.9496618942354548.
[I 2026-07-05 15:25:16,937] Trial 124 finished with value: 0.9461078830527181 and parameters: {'weight_class_0': 0.029553047132146276, 'weight_class_1': 0.6283370777302008, 'weight_class_2': 0.10948222384359967}. Best is trial 116 with value: 0.9496618942354548.
[I 2026-07-05 15:25:16,966] Trial 125 finished with value: 0.9472257587701624 and parameters: {'weight_class_0': 0.02897305095040083, 'weight_class_1': 0.6308135799128132, 'weight_class_2': 0.1246794751999238}. Best is trial 116 with value: 0.9496618942354548.
[I 2026-07-05 15:25:16,984] Trial 126 finished with value: 0.9011198280658727 and parameters: {'weight_class_0': 0.018533618074397424, 'weight_class_1': 0.009723607682177976, 'weight_class_2': 0.12867806966508988}. Best is trial 116 with value: 0.9496618942354548.
[I 2026-07-05 15:25:16,995] Trial 127 finished with value: 0.8802474325700119 and parameters: {'weight_class_0': 0.012597155029923798, 'weight_class_1': 0.0016743405593739166, 'weight_class_2': 0.13625595948302138}. Best is trial 116 with value: 0.9496618942354548.
[I 2026-07-05 15:25:17,023] Trial 129 finished with value: 0.9497247427428631 and parameters: {'weight_class_0': 0.019018882702938684, 'weight_class_1': 0.23773265895683401, 'weight_class_2': 0.2137716125966884}. Best is trial 129 with value: 0.9497247427428631.

Best trial: 136. Best value: 0.949786:   5%|██████                                                                                                                              | 139/3000 [00:02<00:57, 50.03it/s]

[I 2026-07-05 15:25:17,035] Trial 128 finished with value: 0.8767030418546989 and parameters: {'weight_class_0': 0.01874932226184236, 'weight_class_1': 0.0018239224110878371, 'weight_class_2': 0.19393102567354048}. Best is trial 129 with value: 0.9497247427428631.
[I 2026-07-05 15:25:17,075] Trial 130 finished with value: 0.874566348130224 and parameters: {'weight_class_0': 0.018464048746714156, 'weight_class_1': 0.0015679776748778384, 'weight_class_2': 0.19137718681593874}. Best is trial 129 with value: 0.9497247427428631.
[I 2026-07-05 15:25:17,082] Trial 131 finished with value: 0.9496965914683216 and parameters: {'weight_class_0': 0.01852670912364306, 'weight_class_1': 0.26896086848491524, 'weight_class_2': 0.22883761599962316}. Best is trial 129 with value: 0.9497247427428631.
[I 2026-07-05 15:25:17,101] Trial 132 finished with value: 0.9496449584185672 and parameters: {'weight_class_0': 0.01709812403063304, 'weight_class_1': 0.22925162223667117, 'weight_class_2': 0.2135068373098228}. Best is trial 129 with value: 0.9497247427428631.
[I 2026-07-05 15:25:17,117] Trial 133 finished with value: 0.9491433659305856 and parameters: {'weight_class_0': 0.01232353254778168, 'weight_class_1': 0.37895083802854623, 'weight_class_2': 0.19856414951181253}. Best is trial 129 with value: 0.9497247427428631.
[I 2026-07-05 15:25:17,134] Trial 134 finished with value: 0.94975898588506 and parameters: {'weight_class_0': 0.019366025488721194, 'weight_class_1': 0.2522953787228133, 'weight_class_2': 0.21778171147868733}. Best is trial 134 with value: 0.94975898588506.
[I 2026-07-05 15:25:17,157] Trial 135 finished with value: 0.9482372586512883 and parameters: {'weight_class_0': 0.037833062413079724, 'weight_class_1': 0.26538072363135756, 'weight_class_2': 0.21751323413517767}. Best is trial 134 with value: 0.94975898588506.
[I 2026-07-05 15:25:17,170] Trial 136 finished with value: 0.9497863292588861 and parameters: {'weight_class_0': 0.0187307665341539, 'weight_class_1': 0.25984199424819326, 'weight_class_2': 0.2156938915160565}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:17,209] Trial 138 finished with value: 0.9475017633319368 and parameters: {'weight_class_0': 0.03649209498306388, 'weight_class_1': 0.810979713211891, 'weight_class_2': 0.16481211350552216}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:17,217] Trial 137 finished with value: 0.9485220355949968 and parameters: {'weight_class_0': 0.039460956673688465, 'weight_class_1': 0.3900503819826118, 'weight_class_2': 0.21948538394672268}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:17,238] Trial 139 finished with value: 0.9485730903486477 and parameters: {'weight_class_0': 0.009118102566977157, 'weight_class_1': 0.2105854953063449, 'weight_class_2': 0.22712251417585133}. Best is trial 136 with value: 0.9497863292588861.

Best trial: 136. Best value: 0.949786:   5%|██████▋                                                                                                                             | 151/3000 [00:02<00:56, 50.15it/s]

[I 2026-07-05 15:25:17,261] Trial 140 finished with value: 0.9481867230703965 and parameters: {'weight_class_0': 0.009729216111441728, 'weight_class_1': 0.2393481082423092, 'weight_class_2': 0.2957300061921343}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:17,268] Trial 141 finished with value: 0.9481526587274797 and parameters: {'weight_class_0': 0.009711930647057703, 'weight_class_1': 0.25177173889307924, 'weight_class_2': 0.3039988223461457}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:17,312] Trial 143 finished with value: 0.9466079864715344 and parameters: {'weight_class_0': 0.009018065395228437, 'weight_class_1': 0.37563897571077753, 'weight_class_2': 0.46742979567278276}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:17,331] Trial 142 finished with value: 0.9479180930665517 and parameters: {'weight_class_0': 0.014861419703978529, 'weight_class_1': 0.2696519331508121, 'weight_class_2': 0.46711959977557554}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:17,339] Trial 144 finished with value: 0.9474547799787391 and parameters: {'weight_class_0': 0.008440482274999207, 'weight_class_1': 0.1323580982175314, 'weight_class_2': 0.2970374776941869}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:17,347] Trial 145 finished with value: 0.9464849308722542 and parameters: {'weight_class_0': 0.008943305966496024, 'weight_class_1': 0.13274294520700256, 'weight_class_2': 0.4578637780176133}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:17,363] Trial 146 finished with value: 0.9479403322490841 and parameters: {'weight_class_0': 0.009038218070978496, 'weight_class_1': 0.27087878943913424, 'weight_class_2': 0.30947728209070574}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:17,394] Trial 147 finished with value: 0.947960848203809 and parameters: {'weight_class_0': 0.012300773149683137, 'weight_class_1': 0.1408315009418257, 'weight_class_2': 0.3041250642940374}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:17,419] Trial 148 finished with value: 0.9479373990113985 and parameters: {'weight_class_0': 0.013199403668402688, 'weight_class_1': 0.13836979058093363, 'weight_class_2': 0.3204750214641824}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:17,429] Trial 149 finished with value: 0.9470079113886171 and parameters: {'weight_class_0': 0.012953881440355754, 'weight_class_1': 0.13569110830390907, 'weight_class_2': 0.4577384054601134}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:17,441] Trial 150 finished with value: 0.947796097928817 and parameters: {'weight_class_0': 0.013603588711701687, 'weight_class_1': 0.37682982728646186, 'weight_class_2': 0.4799083896703856}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:17,464] Trial 151 finished with value: 0.9477576418422199 and parameters: {'weight_class_0': 0.012292654416932747, 'weight_class_1': 0.35930083143552694, 'weight_class_2': 0.4523649525147651}. Best is trial 136 with value: 0.9497863292588861.

[I 2026-07-05 15:25:17,483] Trial 152 finished with value: 0.9489646690698303 and parameters: {'weight_class_0': 0.012569979542703934, 'weight_class_1': 0.4617445993049179, 'weight_class_2': 0.16219826508921265}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:17,507] Trial 153 finished with value: 0.9488291383501258 and parameters: {'weight_class_0': 0.01244808245907361, 'weight_class_1': 0.48753383350058205, 'weight_class_2': 0.16244082504774185}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:17,514] Trial 154 finished with value: 0.9490421412928631 and parameters: {'weight_class_0': 0.012934690121985214, 'weight_class_1': 0.47585215645132833, 'weight_class_2': 0.1581538206612176}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:17,555] Trial 156 finished with value: 0.9488449090330463 and parameters: {'weight_class_0': 0.012697560749062966, 'weight_class_1': 0.47890570662186693, 'weight_class_2': 0.17093771523869639}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:17,556] Trial 155 finished with value: 0.9486694107255823 and parameters: {'weight_class_0': 0.01357128707415963, 'weight_class_1': 0.0866911540854043, 'weight_class_2': 0.15956655168205847}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:17,575] Trial 157 finished with value: 0.9484562679731324 and parameters: {'weight_class_0': 0.023244689433651548, 'weight_class_1': 0.45738220134363494, 'weight_class_2': 0.6042972966698431}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:17,593] Trial 158 finished with value: 0.9489561652343355 and parameters: {'weight_class_0': 0.02081589993375835, 'weight_class_1': 0.48922409391816774, 'weight_class_2': 0.1486391282770148}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:17,623] Trial 159 finished with value: 0.9492963585620887 and parameters: {'weight_class_0': 0.020187552080867706, 'weight_class_1': 0.19593249433793422, 'weight_class_2': 0.1528544823016333}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:17,644] Trial 160 finished with value: 0.949500217091248 and parameters: {'weight_class_0': 0.02075549806908008, 'weight_class_1': 0.20006531941993608, 'weight_class_2': 0.2536167204678273}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:17,661] Trial 161 finished with value: 0.9474414330187114 and parameters: {'weight_class_0': 0.021049904962935274, 'weight_class_1': 0.20529378783797797, 'weight_class_2': 0.6059717808543161}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:17,682] Trial 162 finished with value: 0.9474133594592066 and parameters: {'weight_class_0': 0.020830676523947985, 'weight_class_1': 0.19970770591884993, 'weight_class_2': 0.6039114590815468}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:17,704] Trial 163 finished with value: 0.9497611543861054 and parameters: {'weight_class_0': 0.0216920671953615, 'weight_class_1': 0.2918097612933381, 'weight_class_2': 0.2457888389370667}. Best is trial 136 with value: 0.9497863292588861.

Best trial: 136. Best value: 0.949786:   6%|███████▋                                                                                                                            | 174/3000 [00:03<00:54, 52.01it/s]

[I 2026-07-05 15:25:17,724] Trial 164 finished with value: 0.9495155141028064 and parameters: {'weight_class_0': 0.021058236316647973, 'weight_class_1': 0.19691859525235036, 'weight_class_2': 0.24861249000561544}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:17,736] Trial 165 finished with value: 0.9493875919597117 and parameters: {'weight_class_0': 0.019458414832736453, 'weight_class_1': 0.19586680193726275, 'weight_class_2': 0.25053842870771376}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:17,760] Trial 166 finished with value: 0.9494637019786939 and parameters: {'weight_class_0': 0.019371101961012865, 'weight_class_1': 0.20254332189081994, 'weight_class_2': 0.2480163411628592}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:17,783] Trial 167 finished with value: 0.9496109667893586 and parameters: {'weight_class_0': 0.017532870793077915, 'weight_class_1': 0.30218099662092623, 'weight_class_2': 0.23917745432550205}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:17,813] Trial 168 finished with value: 0.9495927863880245 and parameters: {'weight_class_0': 0.01938417908780536, 'weight_class_1': 0.20369863861939833, 'weight_class_2': 0.23396102682092085}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:17,819] Trial 169 finished with value: 0.9495772296701345 and parameters: {'weight_class_0': 0.018324333951381885, 'weight_class_1': 0.21033788060200978, 'weight_class_2': 0.23811775141752278}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:17,835] Trial 170 finished with value: 0.949539272569528 and parameters: {'weight_class_0': 0.01744814538793682, 'weight_class_1': 0.2933348398308558, 'weight_class_2': 0.2516810826327307}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:17,858] Trial 171 finished with value: 0.9495210979402953 and parameters: {'weight_class_0': 0.0169469259042585, 'weight_class_1': 0.29744628313155475, 'weight_class_2': 0.24929234626619814}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:17,869] Trial 172 finished with value: 0.949542074109198 and parameters: {'weight_class_0': 0.017479376361120798, 'weight_class_1': 0.3153289292235199, 'weight_class_2': 0.24670874141754406}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:17,879] Trial 173 finished with value: 0.9493723021106684 and parameters: {'weight_class_0': 0.015367802815885177, 'weight_class_1': 0.2884450153981267, 'weight_class_2': 0.2592396315827324}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:17,907] Trial 175 finished with value: 0.94949014584566 and parameters: {'weight_class_0': 0.01719812530925665, 'weight_class_1': 0.27894886999627694, 'weight_class_2': 0.24516125721559912}. Best is trial 136 with value: 0.9497863292588861.

Best trial: 136. Best value: 0.949786:   6%|████████▏                                                                                                                           | 186/3000 [00:03<00:53, 53.00it/s]

[I 2026-07-05 15:25:17,920] Trial 176 finished with value: 0.9493302793747382 and parameters: {'weight_class_0': 0.01726099694735472, 'weight_class_1': 0.20753766645833913, 'weight_class_2': 0.2548226577894196}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:17,924] Trial 174 finished with value: 0.9494919026156218 and parameters: {'weight_class_0': 0.01742555956227816, 'weight_class_1': 0.29314926366494143, 'weight_class_2': 0.26483397085063104}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:17,974] Trial 178 finished with value: 0.949464619113109 and parameters: {'weight_class_0': 0.01680165876973823, 'weight_class_1': 0.2845292366752529, 'weight_class_2': 0.2534207883263884}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:17,976] Trial 177 finished with value: 0.9494877109820377 and parameters: {'weight_class_0': 0.01871728133729774, 'weight_class_1': 0.20541577129470712, 'weight_class_2': 0.24375237379892556}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:17,995] Trial 179 finished with value: 0.9494817665412789 and parameters: {'weight_class_0': 0.01642035749840303, 'weight_class_1': 0.2799603762153711, 'weight_class_2': 0.255442162079481}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:18,015] Trial 181 finished with value: 0.9491781421482225 and parameters: {'weight_class_0': 0.01793523793411536, 'weight_class_1': 0.1595023217235961, 'weight_class_2': 0.24179437008107119}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:18,038] Trial 180 finished with value: 0.9489305797804547 and parameters: {'weight_class_0': 0.016908819851299956, 'weight_class_1': 0.1556965922135773, 'weight_class_2': 0.2599155276303444}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:18,051] Trial 182 finished with value: 0.9493525311969337 and parameters: {'weight_class_0': 0.01715620709441105, 'weight_class_1': 0.23007654416376536, 'weight_class_2': 0.267682198396769}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:18,065] Trial 183 finished with value: 0.9494044180419484 and parameters: {'weight_class_0': 0.017737473319356954, 'weight_class_1': 0.22930749560168437, 'weight_class_2': 0.25347515503649454}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:18,104] Trial 184 finished with value: 0.9494183387117303 and parameters: {'weight_class_0': 0.016082359616819454, 'weight_class_1': 0.2438276386382559, 'weight_class_2': 0.24595452740855142}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:18,116] Trial 185 finished with value: 0.9490299314108458 and parameters: {'weight_class_0': 0.016531980455406336, 'weight_class_1': 0.15866952324091704, 'weight_class_2': 0.25493238001461516}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:18,154] Trial 186 finished with value: 0.9486598841585469 and parameters: {'weight_class_0': 0.0163396436846736, 'weight_class_1': 0.24534652247432395, 'weight_class_2': 0.3462291030277453}. Best is trial 136 with value: 0.9497863292588861.

Best trial: 136. Best value: 0.949786:   7%|████████▋                                                                                                                           | 197/3000 [00:03<00:51, 54.13it/s]

[I 2026-07-05 15:25:18,161] Trial 187 finished with value: 0.9483489386489671 and parameters: {'weight_class_0': 0.01651653200399145, 'weight_class_1': 0.15375384936243078, 'weight_class_2': 0.3233600227790129}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:18,188] Trial 188 finished with value: 0.9487618662419997 and parameters: {'weight_class_0': 0.0160925402619115, 'weight_class_1': 0.2383619061582128, 'weight_class_2': 0.32880975387817335}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:18,206] Trial 189 finished with value: 0.9489263117165896 and parameters: {'weight_class_0': 0.015936475630483393, 'weight_class_1': 0.23894206682697722, 'weight_class_2': 0.3075156354031558}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:18,209] Trial 190 finished with value: 0.9487801909915876 and parameters: {'weight_class_0': 0.01621693232114449, 'weight_class_1': 0.2560503458270275, 'weight_class_2': 0.3379615820397674}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:18,242] Trial 191 finished with value: 0.9494187634574907 and parameters: {'weight_class_0': 0.02350378248581113, 'weight_class_1': 0.29535728038749426, 'weight_class_2': 0.33218847173949745}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:18,243] Trial 192 finished with value: 0.9481176560088164 and parameters: {'weight_class_0': 0.011206965448674083, 'weight_class_1': 0.26521312028939703, 'weight_class_2': 0.3424402011172279}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:18,270] Trial 193 finished with value: 0.949370341740781 and parameters: {'weight_class_0': 0.02525767982762065, 'weight_class_1': 0.26969428896735465, 'weight_class_2': 0.33930181152618344}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:18,303] Trial 194 finished with value: 0.9493810133649926 and parameters: {'weight_class_0': 0.025007459960074908, 'weight_class_1': 0.2623582650268936, 'weight_class_2': 0.33131305573752273}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:18,313] Trial 195 finished with value: 0.9495458303702753 and parameters: {'weight_class_0': 0.024588221842946137, 'weight_class_1': 0.30023999158859976, 'weight_class_2': 0.3251289326026383}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:18,340] Trial 196 finished with value: 0.9491128713773543 and parameters: {'weight_class_0': 0.024927167564009613, 'weight_class_1': 0.28918404366699935, 'weight_class_2': 0.17517778665453612}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:18,355] Trial 198 finished with value: 0.9494098390190179 and parameters: {'weight_class_0': 0.02308773258528729, 'weight_class_1': 0.29552682543962294, 'weight_class_2': 0.18560375083564665}. Best is trial 136 with value: 0.9497863292588861.

Best trial: 207. Best value: 0.949824:   7%|█████████▏                                                                                                                          | 208/3000 [00:04<00:54, 51.51it/s]

[I 2026-07-05 15:25:18,357] Trial 197 finished with value: 0.9477735133135594 and parameters: {'weight_class_0': 0.007131541307522889, 'weight_class_1': 0.2938521570036157, 'weight_class_2': 0.187293913390459}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:18,417] Trial 199 finished with value: 0.9491193952304836 and parameters: {'weight_class_0': 0.024861506295702416, 'weight_class_1': 0.3042173412301637, 'weight_class_2': 0.1736190479774701}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:18,419] Trial 200 finished with value: 0.9492969740653797 and parameters: {'weight_class_0': 0.024501775931388012, 'weight_class_1': 0.30466752297574323, 'weight_class_2': 0.18915653604989124}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:18,427] Trial 201 finished with value: 0.9493802178665603 and parameters: {'weight_class_0': 0.02302749681117619, 'weight_class_1': 0.2945421663705889, 'weight_class_2': 0.1808521000445998}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:18,460] Trial 202 finished with value: 0.9492734653433575 and parameters: {'weight_class_0': 0.024977405002933523, 'weight_class_1': 0.30880403737628204, 'weight_class_2': 0.18434568121461306}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:18,477] Trial 203 finished with value: 0.9474518694023789 and parameters: {'weight_class_0': 0.006995175182998085, 'weight_class_1': 0.318622442079955, 'weight_class_2': 0.19264590730756037}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:18,486] Trial 204 finished with value: 0.9492821477339093 and parameters: {'weight_class_0': 0.02179131496012528, 'weight_class_1': 0.18354084087896916, 'weight_class_2': 0.1784532743811651}. Best is trial 136 with value: 0.9497863292588861.
[I 2026-07-05 15:25:18,530] Trial 206 finished with value: 0.9498031181348668 and parameters: {'weight_class_0': 0.011051842006339406, 'weight_class_1': 0.18374735637850784, 'weight_class_2': 0.13447659591859987}. Best is trial 206 with value: 0.9498031181348668.
[I 2026-07-05 15:25:18,534] Trial 205 finished with value: 0.9483862809219722 and parameters: {'weight_class_0': 0.011141220747665163, 'weight_class_1': 0.10787670678537446, 'weight_class_2': 0.21926856705000813}. Best is trial 206 with value: 0.9498031181348668.
[I 2026-07-05 15:25:18,560] Trial 207 finished with value: 0.949824397435818 and parameters: {'weight_class_0': 0.010891452527756041, 'weight_class_1': 0.1864258394971161, 'weight_class_2': 0.12497015374764163}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:18,565] Trial 208 finished with value: 0.949756784012151 and parameters: {'weight_class_0': 0.010544219350920227, 'weight_class_1': 0.1784371412291123, 'weight_class_2': 0.13112927787109988}. Best is trial 207 with value: 0.949824397435818.

Best trial: 207. Best value: 0.949824:   7%|█████████▋                                                                                                                          | 219/3000 [00:04<00:54, 51.36it/s]

[I 2026-07-05 15:25:18,581] Trial 209 finished with value: 0.9489019092626704 and parameters: {'weight_class_0': 0.010688887944486485, 'weight_class_1': 0.18284731104737506, 'weight_class_2': 0.2263126745827569}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:18,612] Trial 210 finished with value: 0.949448797780185 and parameters: {'weight_class_0': 0.020951793681479244, 'weight_class_1': 0.18239835812604968, 'weight_class_2': 0.22223940851918125}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:18,630] Trial 212 finished with value: 0.9496066057679701 and parameters: {'weight_class_0': 0.01980926435465943, 'weight_class_1': 0.1911727409447097, 'weight_class_2': 0.23404878318876643}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:18,651] Trial 211 finished with value: 0.9489730155683974 and parameters: {'weight_class_0': 0.011139990537621637, 'weight_class_1': 0.19178377188010629, 'weight_class_2': 0.22758599788293243}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:18,659] Trial 213 finished with value: 0.9489434821684712 and parameters: {'weight_class_0': 0.019469878328051273, 'weight_class_1': 0.3883621470600909, 'weight_class_2': 0.12528339108453362}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:18,678] Trial 214 finished with value: 0.9497866167933097 and parameters: {'weight_class_0': 0.019609181389558035, 'weight_class_1': 0.37720111311964205, 'weight_class_2': 0.22747252614082825}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:18,712] Trial 215 finished with value: 0.9488148022335577 and parameters: {'weight_class_0': 0.01075822650961912, 'weight_class_1': 0.1743119130633524, 'weight_class_2': 0.22210447015816115}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:18,723] Trial 216 finished with value: 0.9497985618657405 and parameters: {'weight_class_0': 0.010432789850300217, 'weight_class_1': 0.1776115908639649, 'weight_class_2': 0.11953656833780224}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:18,748] Trial 218 finished with value: 0.949675549735194 and parameters: {'weight_class_0': 0.013384676140029356, 'weight_class_1': 0.17039367574706213, 'weight_class_2': 0.12511181792051776}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:18,775] Trial 217 finished with value: 0.9494112443659937 and parameters: {'weight_class_0': 0.01409289972441005, 'weight_class_1': 0.3905024202052443, 'weight_class_2': 0.1305977796040398}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:18,790] Trial 220 finished with value: 0.9493941543984702 and parameters: {'weight_class_0': 0.014095408245541579, 'weight_class_1': 0.3780891589146364, 'weight_class_2': 0.12450766314897703}. Best is trial 207 with value: 0.949824397435818.

Best trial: 207. Best value: 0.949824:   8%|██████████                                                                                                                          | 230/3000 [00:04<00:52, 52.27it/s]

[I 2026-07-05 15:25:18,792] Trial 219 finished with value: 0.9479041437198358 and parameters: {'weight_class_0': 0.005195249383649634, 'weight_class_1': 0.21388790515525546, 'weight_class_2': 0.12484821078655158}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:18,819] Trial 221 finished with value: 0.9493464508730155 and parameters: {'weight_class_0': 0.014296685575747434, 'weight_class_1': 0.372968748645787, 'weight_class_2': 0.12045916580841813}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:18,847] Trial 222 finished with value: 0.8063660139494471 and parameters: {'weight_class_0': 3.415950550788425, 'weight_class_1': 0.12453684835948865, 'weight_class_2': 0.13144570485689164}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:18,864] Trial 223 finished with value: 0.9494464703974007 and parameters: {'weight_class_0': 0.014111848445991476, 'weight_class_1': 0.12005508298730672, 'weight_class_2': 0.13232771580131408}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:18,875] Trial 224 finished with value: 0.9492625428721427 and parameters: {'weight_class_0': 0.013887350642483996, 'weight_class_1': 0.11358951831397968, 'weight_class_2': 0.12043153294672043}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:18,898] Trial 225 finished with value: 0.9486874789700924 and parameters: {'weight_class_0': 0.013844666162607558, 'weight_class_1': 0.1098702625707875, 'weight_class_2': 0.08569769298165009}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:18,918] Trial 226 finished with value: 0.948890889167651 and parameters: {'weight_class_0': 0.013901335503824778, 'weight_class_1': 0.1534894736529604, 'weight_class_2': 0.0868325106191301}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:18,930] Trial 227 finished with value: 0.9488450122508869 and parameters: {'weight_class_0': 0.005490506593462347, 'weight_class_1': 0.12001884054605837, 'weight_class_2': 0.11895381358021431}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:18,953] Trial 228 finished with value: 0.8000799767346018 and parameters: {'weight_class_0': 4.583625140372323, 'weight_class_1': 0.11258426565401894, 'weight_class_2': 0.07552422306897273}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:18,988] Trial 229 finished with value: 0.9496400509807877 and parameters: {'weight_class_0': 0.008152655932752667, 'weight_class_1': 0.11941929046401294, 'weight_class_2': 0.08141690758661348}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,007] Trial 230 finished with value: 0.9492681087790041 and parameters: {'weight_class_0': 0.008127628565413814, 'weight_class_1': 0.1259542829337535, 'weight_class_2': 0.1440742377374409}. Best is trial 207 with value: 0.949824397435818.

Best trial: 207. Best value: 0.949824:   8%|██████████▌                                                                                                                         | 241/3000 [00:04<00:53, 51.60it/s]

[I 2026-07-05 15:25:19,024] Trial 231 finished with value: 0.9495342308604896 and parameters: {'weight_class_0': 0.009857708203058804, 'weight_class_1': 0.15821558646015937, 'weight_class_2': 0.08172258300180871}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,051] Trial 233 finished with value: 0.9494934621663597 and parameters: {'weight_class_0': 0.010212353708078785, 'weight_class_1': 0.15257499670409344, 'weight_class_2': 0.08493137037885785}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,053] Trial 232 finished with value: 0.9497402996301734 and parameters: {'weight_class_0': 0.008199299360085273, 'weight_class_1': 0.1437758010618035, 'weight_class_2': 0.08966440027596655}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,082] Trial 234 finished with value: 0.9496754130378405 and parameters: {'weight_class_0': 0.008207073014291145, 'weight_class_1': 0.1585403771982385, 'weight_class_2': 0.07426900889044953}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,122] Trial 235 finished with value: 0.9495169824561911 and parameters: {'weight_class_0': 0.0077528119368366, 'weight_class_1': 0.2131388590985315, 'weight_class_2': 0.09525631411946417}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,125] Trial 236 finished with value: 0.9493510216833405 and parameters: {'weight_class_0': 0.007744815200960362, 'weight_class_1': 0.22428832939179968, 'weight_class_2': 0.07085319969228375}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,137] Trial 237 finished with value: 0.9495511248558466 and parameters: {'weight_class_0': 0.008521098729121131, 'weight_class_1': 0.21893116828462406, 'weight_class_2': 0.09219495278666935}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,148] Trial 238 finished with value: 0.9496653232318139 and parameters: {'weight_class_0': 0.008508084568036652, 'weight_class_1': 0.21255777977153684, 'weight_class_2': 0.09652575912917942}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,170] Trial 239 finished with value: 0.9495449382392379 and parameters: {'weight_class_0': 0.007253950863145709, 'weight_class_1': 0.1598724221139554, 'weight_class_2': 0.09917711226878526}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,185] Trial 240 finished with value: 0.9496450897492831 and parameters: {'weight_class_0': 0.007448563110645733, 'weight_class_1': 0.1579820546840962, 'weight_class_2': 0.09446993913886315}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,237] Trial 242 finished with value: 0.9493457174653376 and parameters: {'weight_class_0': 0.006471187291128657, 'weight_class_1': 0.08728251323113889, 'weight_class_2': 0.10133213482180056}. Best is trial 207 with value: 0.949824397435818.

[I 2026-07-05 15:25:19,239] Trial 241 finished with value: 0.9496381005619573 and parameters: {'weight_class_0': 0.007192006562299244, 'weight_class_1': 0.08584320502578334, 'weight_class_2': 0.06815994586285958}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,252] Trial 243 finished with value: 0.9496137709814617 and parameters: {'weight_class_0': 0.0074629351993162965, 'weight_class_1': 0.0920379866035568, 'weight_class_2': 0.0927240325240654}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,262] Trial 244 finished with value: 0.9494310568864263 and parameters: {'weight_class_0': 0.006547759651398979, 'weight_class_1': 0.14968886126239667, 'weight_class_2': 0.09635555069324139}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,283] Trial 245 finished with value: 0.9496666762299824 and parameters: {'weight_class_0': 0.006719706670019474, 'weight_class_1': 0.1504056040126257, 'weight_class_2': 0.0713680280915222}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,295] Trial 246 finished with value: 0.9495087258060545 and parameters: {'weight_class_0': 0.007459680835758962, 'weight_class_1': 0.15673282230586166, 'weight_class_2': 0.06432081865224307}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,352] Trial 249 finished with value: 0.9493805441037776 and parameters: {'weight_class_0': 0.0063801380775475106, 'weight_class_1': 0.09118346602060802, 'weight_class_2': 0.0978937046873598}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,356] Trial 247 finished with value: 0.94939063947146 and parameters: {'weight_class_0': 0.006553293917041077, 'weight_class_1': 0.09160466359574178, 'weight_class_2': 0.09627416655884774}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,364] Trial 248 finished with value: 0.9496859275408883 and parameters: {'weight_class_0': 0.007223947825394015, 'weight_class_1': 0.14306860325128648, 'weight_class_2': 0.06474124421280011}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,390] Trial 250 finished with value: 0.9492944630498815 and parameters: {'weight_class_0': 0.006380953392071529, 'weight_class_1': 0.07789214588555456, 'weight_class_2': 0.09787676014231284}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,418] Trial 251 finished with value: 0.9495595525669936 and parameters: {'weight_class_0': 0.007108523178226343, 'weight_class_1': 0.14061983799179917, 'weight_class_2': 0.09970298260409867}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,419] Trial 252 finished with value: 0.9497497501655484 and parameters: {'weight_class_0': 0.005894367584611026, 'weight_class_1': 0.07648610359898546, 'weight_class_2': 0.06624430757128583}. Best is trial 207 with value: 0.949824397435818.

[I 2026-07-05 15:25:19,449] Trial 253 finished with value: 0.9496339194064451 and parameters: {'weight_class_0': 0.004911930401858497, 'weight_class_1': 0.07941762919586826, 'weight_class_2': 0.06577938401752637}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,466] Trial 254 finished with value: 0.9493857500627176 and parameters: {'weight_class_0': 0.004476914840851406, 'weight_class_1': 0.06535934666968181, 'weight_class_2': 0.06945153346213333}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,497] Trial 256 finished with value: 0.9496765731148963 and parameters: {'weight_class_0': 0.0054886000964550555, 'weight_class_1': 0.07327705211992536, 'weight_class_2': 0.06630388685255577}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,500] Trial 255 finished with value: 0.9496538258119669 and parameters: {'weight_class_0': 0.00479679072456723, 'weight_class_1': 0.05819015850263379, 'weight_class_2': 0.048349143239430355}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,526] Trial 257 finished with value: 0.9495186849855145 and parameters: {'weight_class_0': 0.005133315223323702, 'weight_class_1': 0.08369434709085743, 'weight_class_2': 0.04218298608392307}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,563] Trial 259 finished with value: 0.9478221599888191 and parameters: {'weight_class_0': 0.009186307698908653, 'weight_class_1': 0.13822893412339232, 'weight_class_2': 0.043328537321839014}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,566] Trial 258 finished with value: 0.9492804692571957 and parameters: {'weight_class_0': 0.004608542512766524, 'weight_class_1': 0.1382631772725923, 'weight_class_2': 0.06527625588143789}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,578] Trial 260 finished with value: 0.9496139937614677 and parameters: {'weight_class_0': 0.004501560452186425, 'weight_class_1': 0.051579436436201866, 'weight_class_2': 0.045421924869089796}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,595] Trial 261 finished with value: 0.9496939388072674 and parameters: {'weight_class_0': 0.004985367346917712, 'weight_class_1': 0.09897603393330169, 'weight_class_2': 0.047660939081165865}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,634] Trial 264 finished with value: 0.9495302545823497 and parameters: {'weight_class_0': 0.00528260080507163, 'weight_class_1': 0.058181619326023774, 'weight_class_2': 0.04456073633640316}. Best is trial 207 with value: 0.949824397435818.

Best trial: 207. Best value: 0.949824:   9%|███████████▉                                                                                                                        | 272/3000 [00:05<00:54, 49.63it/s]

[I 2026-07-05 15:25:19,641] Trial 263 finished with value: 0.9494090652276267 and parameters: {'weight_class_0': 0.004871344387733692, 'weight_class_1': 0.1338121783582239, 'weight_class_2': 0.04655041100593082}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,652] Trial 262 finished with value: 0.9496709296831637 and parameters: {'weight_class_0': 0.004729853418164495, 'weight_class_1': 0.06866683802832359, 'weight_class_2': 0.04488550758770037}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,679] Trial 265 finished with value: 0.9496466850984445 and parameters: {'weight_class_0': 0.005142001553711656, 'weight_class_1': 0.0587014004914487, 'weight_class_2': 0.04917093544345174}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,706] Trial 266 finished with value: 0.9496105930328468 and parameters: {'weight_class_0': 0.005324975267781946, 'weight_class_1': 0.05782869576281685, 'weight_class_2': 0.04968078022988861}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,720] Trial 267 finished with value: 0.9495591466721781 and parameters: {'weight_class_0': 0.0055151954191915865, 'weight_class_1': 0.06734905586101833, 'weight_class_2': 0.047447223213389456}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,739] Trial 268 finished with value: 0.9495752893254373 and parameters: {'weight_class_0': 0.0052790929468731745, 'weight_class_1': 0.05683598948816722, 'weight_class_2': 0.0477170083850555}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,757] Trial 269 finished with value: 0.9497426098221871 and parameters: {'weight_class_0': 0.005079691531823832, 'weight_class_1': 0.06049087446379801, 'weight_class_2': 0.05826791021924264}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,759] Trial 270 finished with value: 0.9496130850438734 and parameters: {'weight_class_0': 0.005755461766549081, 'weight_class_1': 0.06312545459785418, 'weight_class_2': 0.06311805756812314}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,799] Trial 271 finished with value: 0.9496322912635703 and parameters: {'weight_class_0': 0.005585359629710898, 'weight_class_1': 0.06625966271415439, 'weight_class_2': 0.05267044922235934}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,804] Trial 272 finished with value: 0.9497204678297253 and parameters: {'weight_class_0': 0.005970430390621204, 'weight_class_1': 0.09787492025886876, 'weight_class_2': 0.05764569082971343}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,829] Trial 273 finished with value: 0.9497848815986675 and parameters: {'weight_class_0': 0.0029012407668757676, 'weight_class_1': 0.06451580553002291, 'weight_class_2': 0.03306093373193545}. Best is trial 207 with value: 0.949824397435818.

Best trial: 207. Best value: 0.949824:   9%|████████████▍                                                                                                                       | 283/3000 [00:05<00:52, 51.58it/s]

[I 2026-07-05 15:25:19,861] Trial 274 finished with value: 0.9495402031862592 and parameters: {'weight_class_0': 0.005930912080238516, 'weight_class_1': 0.060976973160256735, 'weight_class_2': 0.05396984233287434}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,884] Trial 275 finished with value: 0.949663765387128 and parameters: {'weight_class_0': 0.0033607957468847387, 'weight_class_1': 0.04125756828159702, 'weight_class_2': 0.030885646280117276}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,897] Trial 276 finished with value: 0.9496402957347336 and parameters: {'weight_class_0': 0.0033760702495011573, 'weight_class_1': 0.04565503054176517, 'weight_class_2': 0.03369420122582699}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,918] Trial 277 finished with value: 0.9491722382872547 and parameters: {'weight_class_0': 0.0041769190184288135, 'weight_class_1': 0.07089123674140799, 'weight_class_2': 0.02965171569353148}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,942] Trial 278 finished with value: 0.9489405087105807 and parameters: {'weight_class_0': 0.003121249020948761, 'weight_class_1': 0.03989557423869674, 'weight_class_2': 0.05670472760177723}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,966] Trial 280 finished with value: 0.9496564524972596 and parameters: {'weight_class_0': 0.003485850517915687, 'weight_class_1': 0.04268803038792972, 'weight_class_2': 0.032097325950353826}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:19,982] Trial 279 finished with value: 0.9495937961739688 and parameters: {'weight_class_0': 0.0033242891871387995, 'weight_class_1': 0.06629226289356717, 'weight_class_2': 0.029013508685087813}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,001] Trial 281 finished with value: 0.9495717093993816 and parameters: {'weight_class_0': 0.002353940872196048, 'weight_class_1': 0.03834663227313731, 'weight_class_2': 0.03233572072542537}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,002] Trial 282 finished with value: 0.9492661555093953 and parameters: {'weight_class_0': 0.0041065036373353, 'weight_class_1': 0.03958668026142594, 'weight_class_2': 0.03138911574237955}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,038] Trial 283 finished with value: 0.9492888328920105 and parameters: {'weight_class_0': 0.003979979460806593, 'weight_class_1': 0.03997428972055078, 'weight_class_2': 0.03061820346487631}. Best is trial 207 with value: 0.949824397435818.

Best trial: 207. Best value: 0.949824:  10%|████████████▉                                                                                                                       | 294/3000 [00:05<00:52, 51.27it/s]

[I 2026-07-05 15:25:20,090] Trial 286 finished with value: 0.9493967180411809 and parameters: {'weight_class_0': 0.0033651106978931484, 'weight_class_1': 0.09598830787526616, 'weight_class_2': 0.03305297684012332}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,095] Trial 284 finished with value: 0.9493872263700748 and parameters: {'weight_class_0': 0.0026482271128384963, 'weight_class_1': 0.0413520837668458, 'weight_class_2': 0.020321567292313977}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,109] Trial 285 finished with value: 0.9494677385929252 and parameters: {'weight_class_0': 0.002743840640127844, 'weight_class_1': 0.03743448991818502, 'weight_class_2': 0.022666173131880685}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,111] Trial 287 finished with value: 0.9496936940200098 and parameters: {'weight_class_0': 0.0029154735734980798, 'weight_class_1': 0.0479374802402597, 'weight_class_2': 0.027600653603611157}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,144] Trial 288 finished with value: 0.9495652853790513 and parameters: {'weight_class_0': 0.002947423344288069, 'weight_class_1': 0.03385291781210831, 'weight_class_2': 0.03893081211250693}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,158] Trial 289 finished with value: 0.9485704817223768 and parameters: {'weight_class_0': 0.0024877635055915626, 'weight_class_1': 0.10124719394088867, 'weight_class_2': 0.036854369030508836}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,174] Trial 290 finished with value: 0.9481463193342899 and parameters: {'weight_class_0': 0.002529372602418007, 'weight_class_1': 0.10076833776725012, 'weight_class_2': 0.017651412629169614}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,180] Trial 291 finished with value: 0.9480497680181883 and parameters: {'weight_class_0': 0.002009574961789547, 'weight_class_1': 0.1009043298650471, 'weight_class_2': 0.025824127517661336}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,218] Trial 292 finished with value: 0.9485270930069133 and parameters: {'weight_class_0': 0.0024647047967579112, 'weight_class_1': 0.1016444903098351, 'weight_class_2': 0.037520468502832624}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,250] Trial 293 finished with value: 0.9364634515705864 and parameters: {'weight_class_0': 0.009875325736588286, 'weight_class_1': 0.08995866745642424, 'weight_class_2': 0.020986040042081596}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,251] Trial 294 finished with value: 0.9467520086616833 and parameters: {'weight_class_0': 0.002037316038759368, 'weight_class_1': 0.09988475325770556, 'weight_class_2': 0.07735675705466019}. Best is trial 207 with value: 0.949824397435818.

[I 2026-07-05 15:25:20,313] Trial 296 finished with value: 0.9463848201090245 and parameters: {'weight_class_0': 0.0018282303896859748, 'weight_class_1': 0.10369261291212123, 'weight_class_2': 0.06280080754299006}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,317] Trial 295 finished with value: 0.9498030629898041 and parameters: {'weight_class_0': 0.002050083861713323, 'weight_class_1': 0.02962601211845902, 'weight_class_2': 0.02306309630119966}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,329] Trial 297 finished with value: 0.9491511721989112 and parameters: {'weight_class_0': 0.0020211704329067257, 'weight_class_1': 0.04881144510431386, 'weight_class_2': 0.03734505943419322}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,351] Trial 298 finished with value: 0.9486503513431254 and parameters: {'weight_class_0': 0.0018096071563989023, 'weight_class_1': 0.07534781739289406, 'weight_class_2': 0.01955714513747538}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,360] Trial 299 finished with value: 0.9370725973160763 and parameters: {'weight_class_0': 0.00984915273395556, 'weight_class_1': 0.02045591153450808, 'weight_class_2': 0.07103100426464873}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,373] Trial 300 finished with value: 0.9490036691283743 and parameters: {'weight_class_0': 0.009849048251763682, 'weight_class_1': 0.07377302288311378, 'weight_class_2': 0.07532627889349645}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,411] Trial 301 finished with value: 0.9491128356855202 and parameters: {'weight_class_0': 0.003890163915457416, 'weight_class_1': 0.07555195816552615, 'weight_class_2': 0.07537087771157926}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,426] Trial 302 finished with value: 0.9401182116807295 and parameters: {'weight_class_0': 0.009885752216951437, 'weight_class_1': 0.024644141510330474, 'weight_class_2': 0.05997041249845852}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,430] Trial 304 finished with value: 0.94857010811541 and parameters: {'weight_class_0': 0.00803793740403567, 'weight_class_1': 0.04984747272977066, 'weight_class_2': 0.06439542347616883}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,455] Trial 303 finished with value: 0.9425572539219566 and parameters: {'weight_class_0': 0.009135810830122817, 'weight_class_1': 0.025686423518328123, 'weight_class_2': 0.07257296107220391}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,471] Trial 305 finished with value: 0.9475775088996308 and parameters: {'weight_class_0': 0.001636578993520273, 'weight_class_1': 0.04836981664542559, 'weight_class_2': 0.06425907398310557}. Best is trial 207 with value: 0.949824397435818.

[I 2026-07-05 15:25:20,502] Trial 306 finished with value: 0.9487896629908402 and parameters: {'weight_class_0': 0.008890516929413898, 'weight_class_1': 0.0741465987645529, 'weight_class_2': 0.05648451588881162}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,512] Trial 307 finished with value: 0.948311837546116 and parameters: {'weight_class_0': 0.00154831171661675, 'weight_class_1': 0.0734430527938582, 'weight_class_2': 0.016944293015604243}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,515] Trial 308 finished with value: 0.9449789952470353 and parameters: {'weight_class_0': 0.008743445241449353, 'weight_class_1': 0.030951360135697475, 'weight_class_2': 0.05615492470746825}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,546] Trial 309 finished with value: 0.9308408742965688 and parameters: {'weight_class_0': 0.0013436205828101621, 'weight_class_1': 0.17669699542723785, 'weight_class_2': 0.05704615609906055}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,557] Trial 310 finished with value: 0.9306616520900045 and parameters: {'weight_class_0': 0.00880625742322458, 'weight_class_1': 0.1726953249631238, 'weight_class_2': 0.015489570276162158}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,591] Trial 311 finished with value: 0.9490203466959679 and parameters: {'weight_class_0': 0.008682418636329127, 'weight_class_1': 0.1857364859404335, 'weight_class_2': 0.06093983274334777}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,608] Trial 312 finished with value: 0.94938805399577 and parameters: {'weight_class_0': 0.006363485179736144, 'weight_class_1': 0.17386573529235544, 'weight_class_2': 0.058437097455249054}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,649] Trial 313 finished with value: 0.9361269829782155 and parameters: {'weight_class_0': 0.005982417957354893, 'weight_class_1': 0.01778629804692818, 'weight_class_2': 0.01605667408495122}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,664] Trial 314 finished with value: 0.9421540647664877 and parameters: {'weight_class_0': 0.006100033229873828, 'weight_class_1': 0.01795971789106483, 'weight_class_2': 0.13871107774863317}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,683] Trial 315 finished with value: 0.9395185602934267 and parameters: {'weight_class_0': 0.00646123093700819, 'weight_class_1': 0.18235021446910527, 'weight_class_2': 0.01547497938000002}. Best is trial 207 with value: 0.949824397435818.

[I 2026-07-05 15:25:20,687] Trial 316 finished with value: 0.9468967442411023 and parameters: {'weight_class_0': 0.006179939482372463, 'weight_class_1': 0.16892517938536356, 'weight_class_2': 0.02575792524025684}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,693] Trial 317 finished with value: 0.9484380963351732 and parameters: {'weight_class_0': 0.0058604435812976705, 'weight_class_1': 0.1768475722834242, 'weight_class_2': 0.14796684076354366}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,715] Trial 318 finished with value: 0.9487786030954473 and parameters: {'weight_class_0': 0.006513056245995862, 'weight_class_1': 0.125199601247313, 'weight_class_2': 0.1485526039495524}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,753] Trial 320 finished with value: 0.9486720600166177 and parameters: {'weight_class_0': 0.00637754115186551, 'weight_class_1': 0.130021754562523, 'weight_class_2': 0.15403120861135317}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,769] Trial 321 finished with value: 0.9471346501864449 and parameters: {'weight_class_0': 0.0063343650941303465, 'weight_class_1': 0.12400221806110201, 'weight_class_2': 0.0263297351123567}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,781] Trial 319 finished with value: 0.9494096476528867 and parameters: {'weight_class_0': 0.011274338257497567, 'weight_class_1': 0.1239412947035464, 'weight_class_2': 0.15208392302855472}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,796] Trial 322 finished with value: 0.9495270579091938 and parameters: {'weight_class_0': 0.0117081848735356, 'weight_class_1': 0.12615993679506574, 'weight_class_2': 0.14640701591955577}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,828] Trial 323 finished with value: 0.9375339739568543 and parameters: {'weight_class_0': 0.011639548384243907, 'weight_class_1': 0.132770209250115, 'weight_class_2': 0.025570325898798558}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,853] Trial 324 finished with value: 0.9496284578993835 and parameters: {'weight_class_0': 0.010566410047320677, 'weight_class_1': 0.12831311689868338, 'weight_class_2': 0.10974000594788999}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,857] Trial 325 finished with value: 0.9495983905286428 and parameters: {'weight_class_0': 0.01106549400250152, 'weight_class_1': 0.1317459827836772, 'weight_class_2': 0.11180821567282721}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,869] Trial 326 finished with value: 0.9495819315592384 and parameters: {'weight_class_0': 0.01151667781590728, 'weight_class_1': 0.12036824531909325, 'weight_class_2': 0.11036289321479766}. Best is trial 207 with value: 0.949824397435818.

Best trial: 207. Best value: 0.949824:  11%|██████████████▊                                                                                                                     | 337/3000 [00:06<00:51, 51.50it/s]

[I 2026-07-05 15:25:20,892] Trial 327 finished with value: 0.9490435448150362 and parameters: {'weight_class_0': 0.01137936796991635, 'weight_class_1': 0.12694092496533085, 'weight_class_2': 0.07941698301528893}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,921] Trial 328 finished with value: 0.9496727796191035 and parameters: {'weight_class_0': 0.010533197217043596, 'weight_class_1': 0.2399389896686982, 'weight_class_2': 0.1153853600166587}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,935] Trial 329 finished with value: 0.9491365652209142 and parameters: {'weight_class_0': 0.01130139137510804, 'weight_class_1': 0.140705290223791, 'weight_class_2': 0.0809735195724929}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,954] Trial 330 finished with value: 0.946884509402112 and parameters: {'weight_class_0': 0.004180022023410258, 'weight_class_1': 0.22860230600360557, 'weight_class_2': 0.11230690808773748}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,984] Trial 332 finished with value: 0.9468681326606879 and parameters: {'weight_class_0': 0.004318220706974088, 'weight_class_1': 0.2378781166128979, 'weight_class_2': 0.11588492783232562}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:20,990] Trial 331 finished with value: 0.9472532466423136 and parameters: {'weight_class_0': 0.004210853786555383, 'weight_class_1': 0.23460096714472797, 'weight_class_2': 0.0823474777000785}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,017] Trial 333 finished with value: 0.9341918931914618 and parameters: {'weight_class_0': 0.004273034854988593, 'weight_class_1': 0.21175282040514914, 'weight_class_2': 0.00893391296347553}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,041] Trial 334 finished with value: 0.9476861448508521 and parameters: {'weight_class_0': 0.004442531855034733, 'weight_class_1': 0.2258202961205521, 'weight_class_2': 0.08138955868084373}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,053] Trial 335 finished with value: 0.9474446050061798 and parameters: {'weight_class_0': 0.004336583303359204, 'weight_class_1': 0.23414689790983342, 'weight_class_2': 0.08153495895086134}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,069] Trial 336 finished with value: 0.9480704005327644 and parameters: {'weight_class_0': 0.007203980081890946, 'weight_class_1': 0.2320342021603422, 'weight_class_2': 0.04065442810053641}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,106] Trial 337 finished with value: 0.9476312433693881 and parameters: {'weight_class_0': 0.003792985129735524, 'weight_class_1': 0.2137400522923926, 'weight_class_2': 0.040271771357192565}. Best is trial 207 with value: 0.949824397435818.

Best trial: 207. Best value: 0.949824:  12%|███████████████▎                                                                                                                    | 348/3000 [00:06<00:52, 50.78it/s]

[I 2026-07-05 15:25:21,136] Trial 339 finished with value: 0.8931730431405617 and parameters: {'weight_class_0': 0.004496544318791067, 'weight_class_1': 0.23111130154402496, 'weight_class_2': 0.002222532545549589}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,144] Trial 338 finished with value: 0.9496903678066976 and parameters: {'weight_class_0': 0.004669600663446519, 'weight_class_1': 0.08677412080390358, 'weight_class_2': 0.04223290060368965}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,166] Trial 340 finished with value: 0.9478753303904295 and parameters: {'weight_class_0': 0.0047996754431439545, 'weight_class_1': 0.2475032660121243, 'weight_class_2': 0.043235230693687066}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,168] Trial 341 finished with value: 0.948210574725306 and parameters: {'weight_class_0': 0.008073285222009712, 'weight_class_1': 0.07827529364110412, 'weight_class_2': 0.040475707453898606}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,199] Trial 342 finished with value: 0.9495168265478414 and parameters: {'weight_class_0': 0.004958749970546062, 'weight_class_1': 0.08543744659051229, 'weight_class_2': 0.04006669818133987}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,235] Trial 344 finished with value: 0.9486146576261693 and parameters: {'weight_class_0': 0.0071777106822302735, 'weight_class_1': 0.0829877370582182, 'weight_class_2': 0.04052351872149586}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,240] Trial 343 finished with value: 0.9489186161693901 and parameters: {'weight_class_0': 0.007584564527381911, 'weight_class_1': 0.08262063378331391, 'weight_class_2': 0.048251841072722707}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,261] Trial 345 finished with value: 0.9489382149429518 and parameters: {'weight_class_0': 0.007499933429909041, 'weight_class_1': 0.07468238955103414, 'weight_class_2': 0.049775901143069845}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,270] Trial 346 finished with value: 0.9486007156817441 and parameters: {'weight_class_0': 0.007709094378391186, 'weight_class_1': 0.08284122030718977, 'weight_class_2': 0.04439938293583974}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,291] Trial 348 finished with value: 0.9487454089217285 and parameters: {'weight_class_0': 0.007582703731710619, 'weight_class_1': 0.0617352031254206, 'weight_class_2': 0.04792722066933207}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,295] Trial 347 finished with value: 0.8449005355239269 and parameters: {'weight_class_0': 0.007921493440344787, 'weight_class_1': 0.0038083382872133526, 'weight_class_2': 0.002533411245218878}. Best is trial 207 with value: 0.949824397435818.

Best trial: 207. Best value: 0.949824:  12%|███████████████▊                                                                                                                    | 359/3000 [00:07<00:51, 51.69it/s]

[I 2026-07-05 15:25:21,353] Trial 349 finished with value: 0.9453858418188442 and parameters: {'weight_class_0': 0.012654382260429291, 'weight_class_1': 0.07578360057143596, 'weight_class_2': 0.047103081818842645}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,372] Trial 351 finished with value: 0.9494210131995753 and parameters: {'weight_class_0': 0.0032230775147620056, 'weight_class_1': 0.057092805122478885, 'weight_class_2': 0.05179017335872692}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,375] Trial 350 finished with value: 0.9490055448572189 and parameters: {'weight_class_0': 0.002737503365900036, 'weight_class_1': 0.0837137083963583, 'weight_class_2': 0.04930284877620707}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,406] Trial 353 finished with value: 0.9176740208124011 and parameters: {'weight_class_0': 0.003134379069696377, 'weight_class_1': 0.003774447276233261, 'weight_class_2': 0.18200144144617497}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,412] Trial 352 finished with value: 0.9433539388905823 and parameters: {'weight_class_0': 0.013844570841083705, 'weight_class_1': 0.05691533996764081, 'weight_class_2': 0.04976419974858976}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,435] Trial 354 finished with value: 0.9463084578554866 and parameters: {'weight_class_0': 0.00283897989900238, 'weight_class_1': 0.0663506039798495, 'weight_class_2': 0.17123817419485257}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,460] Trial 355 finished with value: 0.9471229590809619 and parameters: {'weight_class_0': 0.0030806433957225464, 'weight_class_1': 0.058627304721826035, 'weight_class_2': 0.13622600806532323}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,466] Trial 356 finished with value: 0.9462307323178649 and parameters: {'weight_class_0': 0.0027528306094927366, 'weight_class_1': 0.052719938839366765, 'weight_class_2': 0.16282730637250298}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,492] Trial 357 finished with value: 0.9459235214550085 and parameters: {'weight_class_0': 0.002907433892629707, 'weight_class_1': 0.05887561013807012, 'weight_class_2': 0.1870353801557711}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,526] Trial 359 finished with value: 0.9469860005938523 and parameters: {'weight_class_0': 0.010070536907829282, 'weight_class_1': 0.04899373904369599, 'weight_class_2': 0.17779679156367445}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,528] Trial 358 finished with value: 0.9461323841292941 and parameters: {'weight_class_0': 0.013030810495436893, 'weight_class_1': 0.05041058887294395, 'weight_class_2': 0.17427422979822943}. Best is trial 207 with value: 0.949824397435818.

[I 2026-07-05 15:25:21,543] Trial 360 finished with value: 0.8207164325800068 and parameters: {'weight_class_0': 0.6666777916767922, 'weight_class_1': 0.054777747283009486, 'weight_class_2': 0.16855132438481318}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,602] Trial 362 finished with value: 0.9496944785283779 and parameters: {'weight_class_0': 0.015138865698275352, 'weight_class_1': 0.35323571854146746, 'weight_class_2': 0.16904768798232736}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,611] Trial 361 finished with value: 0.9496357733075677 and parameters: {'weight_class_0': 0.0022624163017103483, 'weight_class_1': 0.04901648526587313, 'weight_class_2': 0.021859197562170418}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,624] Trial 363 finished with value: 0.9490911406081813 and parameters: {'weight_class_0': 0.01432299889295623, 'weight_class_1': 0.10285976649900931, 'weight_class_2': 0.1349415137673297}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,633] Trial 364 finished with value: 0.9292607887090738 and parameters: {'weight_class_0': 0.0012822724696053495, 'weight_class_1': 0.1617662350389292, 'weight_class_2': 0.12736935637547775}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,677] Trial 365 finished with value: 0.9276637916837096 and parameters: {'weight_class_0': 0.014583006979439827, 'weight_class_1': 0.10376894682130189, 'weight_class_2': 0.02371130132286501}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,678] Trial 366 finished with value: 0.9318397733636137 and parameters: {'weight_class_0': 0.013382470960262502, 'weight_class_1': 0.10306970795238307, 'weight_class_2': 0.024500754018409454}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,698] Trial 368 finished with value: 0.9282148534949854 and parameters: {'weight_class_0': 0.014488747556157698, 'weight_class_1': 0.3490577363352766, 'weight_class_2': 0.023850463188654844}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,714] Trial 367 finished with value: 0.9488567540573801 and parameters: {'weight_class_0': 0.005484151386318583, 'weight_class_1': 0.10307749759487142, 'weight_class_2': 0.11946794812735159}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,715] Trial 369 finished with value: 0.926592525521332 and parameters: {'weight_class_0': 0.014194855060656219, 'weight_class_1': 0.10511239416281022, 'weight_class_2': 0.022281771578322215}. Best is trial 207 with value: 0.949824397435818.

[I 2026-07-05 15:25:21,754] Trial 370 finished with value: 0.9461301223581988 and parameters: {'weight_class_0': 0.0022544042039690437, 'weight_class_1': 0.10298848454727468, 'weight_class_2': 0.12920330761576332}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,771] Trial 371 finished with value: 0.9496026041231351 and parameters: {'weight_class_0': 0.014453567307781358, 'weight_class_1': 0.16206592047310003, 'weight_class_2': 0.13195694252405885}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,785] Trial 372 finished with value: 0.9492747862495658 and parameters: {'weight_class_0': 0.01464027871414015, 'weight_class_1': 0.40697958096456816, 'weight_class_2': 0.12768987371443216}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,833] Trial 374 finished with value: 0.9489090665415385 and parameters: {'weight_class_0': 0.014076978923520162, 'weight_class_1': 0.32673375077110967, 'weight_class_2': 0.09869270944684928}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,836] Trial 373 finished with value: 0.9487462156603601 and parameters: {'weight_class_0': 0.015072701048192817, 'weight_class_1': 0.39410771720476656, 'weight_class_2': 0.09648821575575531}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,866] Trial 375 finished with value: 0.9478537397867622 and parameters: {'weight_class_0': 0.020957002241635745, 'weight_class_1': 0.3291998524957012, 'weight_class_2': 0.09918539128203824}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,877] Trial 376 finished with value: 0.9484184106397612 and parameters: {'weight_class_0': 0.02068747792270621, 'weight_class_1': 0.4112352991611735, 'weight_class_2': 0.11377832036448565}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,914] Trial 378 finished with value: 0.8712986900095788 and parameters: {'weight_class_0': 0.01986263977494987, 'weight_class_1': 0.269546666932071, 'weight_class_2': 0.0010483981807371645}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,918] Trial 377 finished with value: 0.9489965838089901 and parameters: {'weight_class_0': 0.00953133539030649, 'weight_class_1': 0.35336781318098875, 'weight_class_2': 0.10781817470867561}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,939] Trial 379 finished with value: 0.9476893780743887 and parameters: {'weight_class_0': 0.021257321728974012, 'weight_class_1': 0.3602770975200081, 'weight_class_2': 0.0983034945370168}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,956] Trial 380 finished with value: 0.9496943221267906 and parameters: {'weight_class_0': 0.00982408767602343, 'weight_class_1': 0.19100376216047127, 'weight_class_2': 0.09941321019415832}. Best is trial 207 with value: 0.949824397435818.

Best trial: 207. Best value: 0.949824:  13%|█████████████████▏                                                                                                                  | 391/3000 [00:07<00:52, 49.54it/s]

[I 2026-07-05 15:25:21,969] Trial 381 finished with value: 0.8684822286125473 and parameters: {'weight_class_0': 0.019993165259184927, 'weight_class_1': 0.34869000402786443, 'weight_class_2': 0.0012562977485058406}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:21,984] Trial 382 finished with value: 0.947545074710238 and parameters: {'weight_class_0': 0.021196602951696144, 'weight_class_1': 0.3601971229762014, 'weight_class_2': 0.09543686739454543}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,011] Trial 383 finished with value: 0.949598906366564 and parameters: {'weight_class_0': 0.019379016691337694, 'weight_class_1': 0.18616712150368628, 'weight_class_2': 0.2092757490926696}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,038] Trial 384 finished with value: 0.9496932460285855 and parameters: {'weight_class_0': 0.019459123931556153, 'weight_class_1': 0.26654365571384925, 'weight_class_2': 0.2057973948601155}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,054] Trial 386 finished with value: 0.9490427797188709 and parameters: {'weight_class_0': 0.010310289412685738, 'weight_class_1': 0.1782208444818296, 'weight_class_2': 0.20586745570465415}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,066] Trial 385 finished with value: 0.9488355160103842 and parameters: {'weight_class_0': 0.009045086320477952, 'weight_class_1': 0.18957223341239565, 'weight_class_2': 0.19708221704609566}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,079] Trial 387 finished with value: 0.9490377072127377 and parameters: {'weight_class_0': 0.009885272783532139, 'weight_class_1': 0.1837211722268194, 'weight_class_2': 0.06713473646485607}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,128] Trial 388 finished with value: 0.9492203351937999 and parameters: {'weight_class_0': 0.009860841718917475, 'weight_class_1': 0.17855496185421446, 'weight_class_2': 0.07202092985887663}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,136] Trial 389 finished with value: 0.9491076029974646 and parameters: {'weight_class_0': 0.010166910019468857, 'weight_class_1': 0.17979919213274248, 'weight_class_2': 0.07160981223931594}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,140] Trial 390 finished with value: 0.9492363212731902 and parameters: {'weight_class_0': 0.00922184460197367, 'weight_class_1': 0.16741973993174533, 'weight_class_2': 0.06737417558537359}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,166] Trial 391 finished with value: 0.9493111841739825 and parameters: {'weight_class_0': 0.00946435820723187, 'weight_class_1': 0.1891064286955584, 'weight_class_2': 0.07300806258457894}. Best is trial 207 with value: 0.949824397435818.

Best trial: 207. Best value: 0.949824:  13%|█████████████████▋                                                                                                                  | 402/3000 [00:07<00:52, 49.58it/s]

[I 2026-07-05 15:25:22,194] Trial 393 finished with value: 0.9491321391261426 and parameters: {'weight_class_0': 0.009896366489125953, 'weight_class_1': 0.15377789490555788, 'weight_class_2': 0.06833247382167405}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,216] Trial 392 finished with value: 0.9489540287480517 and parameters: {'weight_class_0': 0.009334308601443731, 'weight_class_1': 0.17638229170016212, 'weight_class_2': 0.05984766022429322}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,229] Trial 394 finished with value: 0.922470769639761 and parameters: {'weight_class_0': 0.026160383589197915, 'weight_class_1': 0.032023905676708105, 'weight_class_2': 0.19240667339014356}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,250] Trial 395 finished with value: 0.9496532242456611 and parameters: {'weight_class_0': 0.01785482091378294, 'weight_class_1': 0.25416540593646714, 'weight_class_2': 0.16111301321734886}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,252] Trial 396 finished with value: 0.9484144538013523 and parameters: {'weight_class_0': 0.03054594128947154, 'weight_class_1': 0.2874850432139352, 'weight_class_2': 0.16456457356715368}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,298] Trial 397 finished with value: 0.9480319149631579 and parameters: {'weight_class_0': 0.032213507792940334, 'weight_class_1': 0.2637753208118226, 'weight_class_2': 0.16192062612706726}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,316] Trial 399 finished with value: 0.8051051756812421 and parameters: {'weight_class_0': 1.6788897835012861, 'weight_class_1': 0.033297418997733766, 'weight_class_2': 0.15976259812528484}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,335] Trial 398 finished with value: 0.9485678025642686 and parameters: {'weight_class_0': 0.026602836125176034, 'weight_class_1': 0.27303792381006065, 'weight_class_2': 0.1516494158346004}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,353] Trial 401 finished with value: 0.9492742733058445 and parameters: {'weight_class_0': 0.027227979843540955, 'weight_class_1': 0.2785575580666335, 'weight_class_2': 0.20391298447731396}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,370] Trial 400 finished with value: 0.9341880803907628 and parameters: {'weight_class_0': 0.0161299574564817, 'weight_class_1': 0.028978617179791225, 'weight_class_2': 0.1434834363244826}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,380] Trial 402 finished with value: 0.9132110183451477 and parameters: {'weight_class_0': 0.03379114764480032, 'weight_class_1': 0.031922288357008076, 'weight_class_2': 0.15574278994841945}. Best is trial 207 with value: 0.949824397435818.

Best trial: 207. Best value: 0.949824:  14%|██████████████████▏                                                                                                                 | 413/3000 [00:08<00:51, 50.69it/s]

[I 2026-07-05 15:25:22,391] Trial 403 finished with value: 0.9485498866211145 and parameters: {'weight_class_0': 0.02754700466023277, 'weight_class_1': 0.2575678038202289, 'weight_class_2': 0.15768275555135491}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,426] Trial 404 finished with value: 0.9498189093110826 and parameters: {'weight_class_0': 0.02576635735082592, 'weight_class_1': 0.44628392739114847, 'weight_class_2': 0.29497035340562155}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,436] Trial 405 finished with value: 0.9155600312541686 and parameters: {'weight_class_0': 0.027900143454834162, 'weight_class_1': 0.2562942636134118, 'weight_class_2': 0.0323424332120883}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,455] Trial 406 finished with value: 0.8976537006667306 and parameters: {'weight_class_0': 0.035036328724342564, 'weight_class_1': 0.015109991924909614, 'weight_class_2': 0.2891564702012466}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,485] Trial 407 finished with value: 0.9497377631321514 and parameters: {'weight_class_0': 0.026493008409373065, 'weight_class_1': 0.44957929114595524, 'weight_class_2': 0.28501776246433524}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,508] Trial 408 finished with value: 0.8925528936605728 and parameters: {'weight_class_0': 0.016903572016761747, 'weight_class_1': 0.44046366902100176, 'weight_class_2': 0.004823674589205321}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,540] Trial 409 finished with value: 0.9416875050282568 and parameters: {'weight_class_0': 0.012353859504866853, 'weight_class_1': 0.14730233833721962, 'weight_class_2': 0.03218270237500998}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,576] Trial 410 finished with value: 0.8407045030591599 and parameters: {'weight_class_0': 0.0016620394975790567, 'weight_class_1': 0.5009541102200175, 'weight_class_2': 0.27231336968694114}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,582] Trial 411 finished with value: 0.9486157028031433 and parameters: {'weight_class_0': 0.012155069649580167, 'weight_class_1': 0.2078257755826339, 'weight_class_2': 0.2875233408236191}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,587] Trial 412 finished with value: 0.9482164669624766 and parameters: {'weight_class_0': 0.012231319831874423, 'weight_class_1': 0.14314704947552195, 'weight_class_2': 0.2794579184562218}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,604] Trial 413 finished with value: 0.9484108270036983 and parameters: {'weight_class_0': 0.012627877100826718, 'weight_class_1': 0.43532108724508867, 'weight_class_2': 0.28247858844766677}. Best is trial 207 with value: 0.949824397435818.

Best trial: 207. Best value: 0.949824:  14%|██████████████████▌                                                                                                                 | 423/3000 [00:08<00:51, 49.64it/s]

[I 2026-07-05 15:25:22,630] Trial 414 finished with value: 0.9299289733194316 and parameters: {'weight_class_0': 0.003634086179213753, 'weight_class_1': 0.47331174527566766, 'weight_class_2': 0.27425660538991925}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,643] Trial 415 finished with value: 0.9449345832668886 and parameters: {'weight_class_0': 0.005327956758857315, 'weight_class_1': 0.34974355420769154, 'weight_class_2': 0.28310221237512356}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,658] Trial 416 finished with value: 0.9494845896229567 and parameters: {'weight_class_0': 0.02567155179853339, 'weight_class_1': 0.44611863884821545, 'weight_class_2': 0.39881154481926434}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,684] Trial 417 finished with value: 0.949628638726603 and parameters: {'weight_class_0': 0.025075955340024603, 'weight_class_1': 0.35996112171877404, 'weight_class_2': 0.32990668025204745}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,713] Trial 418 finished with value: 0.9497509130408502 and parameters: {'weight_class_0': 0.023410279156082292, 'weight_class_1': 0.38712030360544786, 'weight_class_2': 0.2906472690761836}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,731] Trial 420 finished with value: 0.9497687155969476 and parameters: {'weight_class_0': 0.02351008181426845, 'weight_class_1': 0.4405673086880545, 'weight_class_2': 0.27567033404612024}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,747] Trial 419 finished with value: 0.9497232806032171 and parameters: {'weight_class_0': 0.02253891147216308, 'weight_class_1': 0.41593088019642566, 'weight_class_2': 0.2771167907235661}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,765] Trial 421 finished with value: 0.9496462434881877 and parameters: {'weight_class_0': 0.023487897793153953, 'weight_class_1': 0.494353034723372, 'weight_class_2': 0.2961440720735866}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,791] Trial 422 finished with value: 0.9493879235906898 and parameters: {'weight_class_0': 0.023681460251651625, 'weight_class_1': 0.41938691477879575, 'weight_class_2': 0.39581441841644627}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,795] Trial 423 finished with value: 0.9496981696571627 and parameters: {'weight_class_0': 0.03959177464047749, 'weight_class_1': 0.5559392854012144, 'weight_class_2': 0.38210462887682023}. Best is trial 207 with value: 0.949824397435818.

Best trial: 433. Best value: 0.94983:  14%|███████████████████▏                                                                                                                 | 434/3000 [00:08<00:51, 49.68it/s]

[I 2026-07-05 15:25:22,840] Trial 424 finished with value: 0.949563987789983 and parameters: {'weight_class_0': 0.023349562623573322, 'weight_class_1': 0.5307141865942896, 'weight_class_2': 0.21436859549858417}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,850] Trial 425 finished with value: 0.9497227658960591 and parameters: {'weight_class_0': 0.041147946952690015, 'weight_class_1': 0.6899954225394928, 'weight_class_2': 0.38900006340131077}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,859] Trial 426 finished with value: 0.9490294216457024 and parameters: {'weight_class_0': 0.020699523811780515, 'weight_class_1': 0.5032977504238977, 'weight_class_2': 0.4017477361493684}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,877] Trial 427 finished with value: 0.9485047926490916 and parameters: {'weight_class_0': 0.03869139927755563, 'weight_class_1': 0.5960676713553003, 'weight_class_2': 0.21522902006860875}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,910] Trial 428 finished with value: 0.9492381847667147 and parameters: {'weight_class_0': 0.02296795320589324, 'weight_class_1': 0.5574432020623049, 'weight_class_2': 0.4031219713646802}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,934] Trial 429 finished with value: 0.9496941598759033 and parameters: {'weight_class_0': 0.04090236883334081, 'weight_class_1': 0.6991773666501093, 'weight_class_2': 0.40757014190322866}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,946] Trial 430 finished with value: 0.9497566235344049 and parameters: {'weight_class_0': 0.03465720563287074, 'weight_class_1': 0.5991963932793919, 'weight_class_2': 0.3722216300574054}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,966] Trial 431 finished with value: 0.9497009140368625 and parameters: {'weight_class_0': 0.03339440581416212, 'weight_class_1': 0.6967450452166033, 'weight_class_2': 0.3591078440790149}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:22,970] Trial 432 finished with value: 0.949694380731232 and parameters: {'weight_class_0': 0.03424378335351122, 'weight_class_1': 0.7850593870753273, 'weight_class_2': 0.4187202112676679}. Best is trial 207 with value: 0.949824397435818.
[I 2026-07-05 15:25:23,008] Trial 433 finished with value: 0.9498304662349432 and parameters: {'weight_class_0': 0.045014089697177594, 'weight_class_1': 0.7549312132010155, 'weight_class_2': 0.5241378674737277}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,025] Trial 435 finished with value: 0.9495231120392332 and parameters: {'weight_class_0': 0.036521881899287845, 'weight_class_1': 0.7061936531406305, 'weight_class_2': 0.5370039674962219}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  15%|███████████████████▋                                                                                                                 | 445/3000 [00:08<00:51, 49.51it/s]

[I 2026-07-05 15:25:23,037] Trial 434 finished with value: 0.9484553509710332 and parameters: {'weight_class_0': 0.04199273827740425, 'weight_class_1': 0.5538293036937381, 'weight_class_2': 0.22728578115768577}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,060] Trial 436 finished with value: 0.9498246725674927 and parameters: {'weight_class_0': 0.0450209658876737, 'weight_class_1': 0.6876178223828033, 'weight_class_2': 0.5152019040572768}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,075] Trial 437 finished with value: 0.9498032003010759 and parameters: {'weight_class_0': 0.04772838698034679, 'weight_class_1': 0.8724423575509594, 'weight_class_2': 0.5377700451470422}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,093] Trial 438 finished with value: 0.9495563027733874 and parameters: {'weight_class_0': 0.03856558687267545, 'weight_class_1': 0.9612158269037246, 'weight_class_2': 0.5049880559047792}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,159] Trial 439 finished with value: 0.9496267612396401 and parameters: {'weight_class_0': 0.05122136605650292, 'weight_class_1': 0.7772215402693253, 'weight_class_2': 0.5114659693610019}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,165] Trial 440 finished with value: 0.9496855177142018 and parameters: {'weight_class_0': 0.05105746779382927, 'weight_class_1': 0.9377823322798496, 'weight_class_2': 0.46288538172667554}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,177] Trial 441 finished with value: 0.9488419693795453 and parameters: {'weight_class_0': 0.05752688721478814, 'weight_class_1': 1.0152987768857615, 'weight_class_2': 0.3520386545981453}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,178] Trial 442 finished with value: 0.94960595504201 and parameters: {'weight_class_0': 0.05876732210139052, 'weight_class_1': 0.6668116358856903, 'weight_class_2': 0.5346026495926265}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,195] Trial 443 finished with value: 0.9496981258945962 and parameters: {'weight_class_0': 0.051512790979196664, 'weight_class_1': 0.9070967133515195, 'weight_class_2': 0.4747065751019268}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,216] Trial 444 finished with value: 0.9487779824432127 and parameters: {'weight_class_0': 0.038671566148252984, 'weight_class_1': 1.1193740618319596, 'weight_class_2': 0.2648738560216604}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,249] Trial 445 finished with value: 0.8921655500599966 and parameters: {'weight_class_0': 0.05374630379106323, 'weight_class_1': 0.9471561141106254, 'weight_class_2': 0.012044563803046129}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  15%|████████████████████▏                                                                                                                | 456/3000 [00:08<00:50, 50.19it/s]

[I 2026-07-05 15:25:23,258] Trial 446 finished with value: 0.9497041834063081 and parameters: {'weight_class_0': 0.05159014554583266, 'weight_class_1': 0.8436146838950906, 'weight_class_2': 0.5427210402044859}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,294] Trial 447 finished with value: 0.9496252542838627 and parameters: {'weight_class_0': 0.05923743187949198, 'weight_class_1': 1.24751146484185, 'weight_class_2': 0.5980738341043287}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,305] Trial 448 finished with value: 0.9496836106800629 and parameters: {'weight_class_0': 0.055687881442132006, 'weight_class_1': 0.9403522571023235, 'weight_class_2': 0.5558999509809862}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,319] Trial 449 finished with value: 0.949559099977248 and parameters: {'weight_class_0': 0.05692074291242686, 'weight_class_1': 1.3534225187106261, 'weight_class_2': 0.5516035265635135}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,334] Trial 450 finished with value: 0.9496509418102637 and parameters: {'weight_class_0': 0.05980491494506997, 'weight_class_1': 0.732049777945186, 'weight_class_2': 0.5491968931680886}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,379] Trial 451 finished with value: 0.949821558928797 and parameters: {'weight_class_0': 0.06657273324338625, 'weight_class_1': 1.156094399100214, 'weight_class_2': 0.7459080096491387}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,388] Trial 452 finished with value: 0.9494744657819427 and parameters: {'weight_class_0': 0.04495904816354479, 'weight_class_1': 0.7636317745140033, 'weight_class_2': 0.702064749288066}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,396] Trial 453 finished with value: 0.9492871150893455 and parameters: {'weight_class_0': 0.04784835630726826, 'weight_class_1': 0.8134291620226876, 'weight_class_2': 0.8376045360254031}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,425] Trial 454 finished with value: 0.9494633688029047 and parameters: {'weight_class_0': 0.047105752535732744, 'weight_class_1': 0.8371844145600439, 'weight_class_2': 0.7434174104813278}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,429] Trial 455 finished with value: 0.9496165659932808 and parameters: {'weight_class_0': 0.0445793263015498, 'weight_class_1': 0.6719153251693633, 'weight_class_2': 0.5947937554223688}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,481] Trial 456 finished with value: 0.9495602371706212 and parameters: {'weight_class_0': 0.06755497936704298, 'weight_class_1': 0.6869284541505809, 'weight_class_2': 0.618684229373552}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  16%|████████████████████▌                                                                                                                | 465/3000 [00:09<00:53, 47.43it/s]

[I 2026-07-05 15:25:23,485] Trial 457 finished with value: 0.9486180265591195 and parameters: {'weight_class_0': 0.04169470158447622, 'weight_class_1': 1.3536136782409747, 'weight_class_2': 0.869717444595492}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,491] Trial 458 finished with value: 0.9493318408347257 and parameters: {'weight_class_0': 0.04579412538031033, 'weight_class_1': 0.6699664644016758, 'weight_class_2': 0.34039947567720535}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,532] Trial 459 finished with value: 0.9491493732242263 and parameters: {'weight_class_0': 0.04416913887231129, 'weight_class_1': 0.6623993411846727, 'weight_class_2': 0.7997953904112562}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,546] Trial 460 finished with value: 0.9494971492112717 and parameters: {'weight_class_0': 0.042208146225297304, 'weight_class_1': 0.6532600524346178, 'weight_class_2': 0.3424616443022452}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,562] Trial 461 finished with value: 0.9490855289320254 and parameters: {'weight_class_0': 0.08488230057351953, 'weight_class_1': 0.6153359147635381, 'weight_class_2': 0.8325839513804254}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,579] Trial 462 finished with value: 0.9492244052686 and parameters: {'weight_class_0': 0.07864436952395859, 'weight_class_1': 0.5996250875191366, 'weight_class_2': 0.7702192374497101}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,637] Trial 463 finished with value: 0.8774459740995275 and parameters: {'weight_class_0': 0.10981784273797936, 'weight_class_1': 0.010633349447442778, 'weight_class_2': 0.741608853351577}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,643] Trial 464 finished with value: 0.9495196952351774 and parameters: {'weight_class_0': 0.07040815000695308, 'weight_class_1': 1.254027721061988, 'weight_class_2': 1.0057862426704436}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,656] Trial 465 finished with value: 0.9497056580515001 and parameters: {'weight_class_0': 0.07572009854722586, 'weight_class_1': 1.2490081798853645, 'weight_class_2': 0.7283831056802269}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  16%|█████████████████████                                                                                                                | 476/3000 [00:09<00:52, 47.63it/s]

[I 2026-07-05 15:25:23,676] Trial 466 finished with value: 0.9484521102538547 and parameters: {'weight_class_0': 0.07090925501887806, 'weight_class_1': 0.5744494621464088, 'weight_class_2': 1.205786510187555}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,696] Trial 467 finished with value: 0.9495027640181369 and parameters: {'weight_class_0': 0.06874295700005505, 'weight_class_1': 1.4355595733456128, 'weight_class_2': 0.9579156298896707}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,720] Trial 468 finished with value: 0.9484886694973346 and parameters: {'weight_class_0': 0.07953569348921602, 'weight_class_1': 1.1612577611103265, 'weight_class_2': 0.43605598109231913}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,729] Trial 469 finished with value: 0.9490356759896524 and parameters: {'weight_class_0': 0.06698092427740014, 'weight_class_1': 1.1635417359792442, 'weight_class_2': 0.4467997236658218}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,745] Trial 471 finished with value: 0.9421552919745739 and parameters: {'weight_class_0': 0.12376310287302268, 'weight_class_1': 0.45450158653451306, 'weight_class_2': 0.43849398022684266}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,747] Trial 470 finished with value: 0.9483548510398507 and parameters: {'weight_class_0': 0.08101251984368711, 'weight_class_1': 1.0875749301653297, 'weight_class_2': 0.4305402412418398}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,790] Trial 472 finished with value: 0.943364300335715 and parameters: {'weight_class_0': 0.027991155002692746, 'weight_class_1': 2.4587343800134653, 'weight_class_2': 0.4592151647096012}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,808] Trial 473 finished with value: 0.9473217172556155 and parameters: {'weight_class_0': 0.030353800376468287, 'weight_class_1': 0.45962886902987976, 'weight_class_2': 1.1124116252902512}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,826] Trial 474 finished with value: 0.9495190797318864 and parameters: {'weight_class_0': 0.031758545505793094, 'weight_class_1': 0.45719331332578517, 'weight_class_2': 0.4414908471197084}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,878] Trial 475 finished with value: 0.9495614206912203 and parameters: {'weight_class_0': 0.03182169712964475, 'weight_class_1': 0.4224905776850812, 'weight_class_2': 0.4219173940496383}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,893] Trial 477 finished with value: 0.9498009272771543 and parameters: {'weight_class_0': 0.027738910517454817, 'weight_class_1': 0.42098904434815365, 'weight_class_2': 0.32310625442568497}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  16%|█████████████████████▌                                                                                                               | 486/3000 [00:09<00:53, 47.01it/s]

[I 2026-07-05 15:25:23,900] Trial 476 finished with value: 0.9496631330811119 and parameters: {'weight_class_0': 0.03104721037700755, 'weight_class_1': 0.5013512552865977, 'weight_class_2': 0.39507810232924245}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,930] Trial 478 finished with value: 0.9496955793350071 and parameters: {'weight_class_0': 0.030443665972823032, 'weight_class_1': 0.4982948964498829, 'weight_class_2': 0.29544781965818045}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,939] Trial 480 finished with value: 0.9497040763415089 and parameters: {'weight_class_0': 0.032536325310631845, 'weight_class_1': 0.5045152478811118, 'weight_class_2': 0.31271084802537097}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,945] Trial 479 finished with value: 0.9496157568252278 and parameters: {'weight_class_0': 0.031778925019779296, 'weight_class_1': 0.4338194793215662, 'weight_class_2': 0.29205539099057604}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,981] Trial 481 finished with value: 0.9351097732074658 and parameters: {'weight_class_0': 0.03288704690679839, 'weight_class_1': 3.9343414030021826, 'weight_class_2': 0.318621107717477}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:23,988] Trial 482 finished with value: 0.9496933023661825 and parameters: {'weight_class_0': 0.0316156325125611, 'weight_class_1': 0.4014832222536048, 'weight_class_2': 0.3342176392085293}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:24,000] Trial 483 finished with value: 0.8896154752570952 and parameters: {'weight_class_0': 0.028656036386720936, 'weight_class_1': 0.007948730918106144, 'weight_class_2': 0.30399586869588685}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:24,028] Trial 484 finished with value: 0.9496778621038217 and parameters: {'weight_class_0': 0.03379848332618639, 'weight_class_1': 0.4139317334463033, 'weight_class_2': 0.32513281637124347}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:24,077] Trial 485 finished with value: 0.9496240178391675 and parameters: {'weight_class_0': 0.03231394089399144, 'weight_class_1': 0.3898153006908848, 'weight_class_2': 0.32391676418078125}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:24,087] Trial 486 finished with value: 0.949711676658152 and parameters: {'weight_class_0': 0.02846693902576019, 'weight_class_1': 0.3991438895835455, 'weight_class_2': 0.3029350377932792}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  17%|█████████████████████▉                                                                                                               | 496/3000 [00:09<00:52, 47.63it/s]

[I 2026-07-05 15:25:24,131] Trial 487 finished with value: 0.9496850410438528 and parameters: {'weight_class_0': 0.025922866015796502, 'weight_class_1': 0.4022486478022679, 'weight_class_2': 0.2653042038633805}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:24,142] Trial 488 finished with value: 0.9495209688556782 and parameters: {'weight_class_0': 0.025634683221019076, 'weight_class_1': 0.32058108863636514, 'weight_class_2': 0.3372849649380944}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:24,150] Trial 489 finished with value: 0.9496811140614758 and parameters: {'weight_class_0': 0.02623220380587546, 'weight_class_1': 0.35384819410226287, 'weight_class_2': 0.3217825924298345}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:24,160] Trial 490 finished with value: 0.949667941014762 and parameters: {'weight_class_0': 0.0237468155136219, 'weight_class_1': 0.33210896285270103, 'weight_class_2': 0.24717846038421717}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:24,193] Trial 491 finished with value: 0.9496662317799881 and parameters: {'weight_class_0': 0.024204153758422154, 'weight_class_1': 0.37649315609219447, 'weight_class_2': 0.2521327921856748}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:24,243] Trial 492 finished with value: 0.949669346850123 and parameters: {'weight_class_0': 0.025243182858268803, 'weight_class_1': 0.3276286037638099, 'weight_class_2': 0.24684534859154336}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:24,248] Trial 493 finished with value: 0.9479181131848337 and parameters: {'weight_class_0': 0.024431121467293412, 'weight_class_1': 0.3284852930973487, 'weight_class_2': 0.654241454372087}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:24,262] Trial 494 finished with value: 0.9495715969500608 and parameters: {'weight_class_0': 0.025918129904299307, 'weight_class_1': 0.3695752954292334, 'weight_class_2': 0.22661569803790224}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:24,290] Trial 495 finished with value: 0.9496649218040639 and parameters: {'weight_class_0': 0.02279692991374344, 'weight_class_1': 0.3162526759680718, 'weight_class_2': 0.23569727463357473}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:24,296] Trial 496 finished with value: 0.8006267542830816 and parameters: {'weight_class_0': 0.0010059109131709619, 'weight_class_1': 0.3506499562051661, 'weight_class_2': 0.2405894185856474}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  17%|██████████████████████▍                                                                                                              | 506/3000 [00:10<00:57, 43.57it/s]

[I 2026-07-05 15:25:24,351] Trial 497 finished with value: 0.9495399960676402 and parameters: {'weight_class_0': 0.01975253634541538, 'weight_class_1': 0.5676324761216467, 'weight_class_2': 0.23257546743327476}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:24,358] Trial 498 finished with value: 0.9494884877333817 and parameters: {'weight_class_0': 0.021191073976350273, 'weight_class_1': 0.5520854274904573, 'weight_class_2': 0.20554544698565497}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:24,382] Trial 499 finished with value: 0.9495332296115812 and parameters: {'weight_class_0': 0.022462229568866347, 'weight_class_1': 0.5450168854848944, 'weight_class_2': 0.22035747360021798}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:24,392] Trial 501 finished with value: 0.9494428007459912 and parameters: {'weight_class_0': 0.020055233461343264, 'weight_class_1': 0.5412105796584911, 'weight_class_2': 0.21065655550851725}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:24,401] Trial 500 finished with value: 0.949523364448932 and parameters: {'weight_class_0': 0.019147176424422978, 'weight_class_1': 0.5478187143569987, 'weight_class_2': 0.21349246385328885}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:24,432] Trial 502 finished with value: 0.9495345818491475 and parameters: {'weight_class_0': 0.01926685294115952, 'weight_class_1': 0.5591268487090455, 'weight_class_2': 0.22162209087616513}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:24,476] Trial 504 finished with value: 0.944230857225969 and parameters: {'weight_class_0': 0.01878023014288182, 'weight_class_1': 1.5699159543671526, 'weight_class_2': 0.20426174608362724}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:24,479] Trial 503 finished with value: 0.9433518819413379 and parameters: {'weight_class_0': 0.017630196832217573, 'weight_class_1': 1.5673024356687801, 'weight_class_2': 0.20604477009843497}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:24,493] Trial 505 finished with value: 0.949464342431305 and parameters: {'weight_class_0': 0.018949300231931532, 'weight_class_1': 0.5458211880147693, 'weight_class_2': 0.20593144652999099}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:24,533] Trial 506 finished with value: 0.9493053904167671 and parameters: {'weight_class_0': 0.01821244489511245, 'weight_class_1': 0.5775919872797307, 'weight_class_2': 0.1982846884038843}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  17%|██████████████████████▉                                                                                                              | 517/3000 [00:10<00:54, 45.79it/s]

[I 2026-07-05 15:25:24,567] Trial 507 finished with value: 0.9493896316580618 and parameters: {'weight_class_0': 0.019692107560758128, 'weight_class_1': 0.5423419022347222, 'weight_class_2': 0.19575097171084024}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:24,571] Trial 508 finished with value: 0.9475111031515037 and parameters: {'weight_class_0': 0.017670307322023963, 'weight_class_1': 0.8885528452737371, 'weight_class_2': 0.36972968830966907}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:24,601] Trial 509 finished with value: 0.9468769058475766 and parameters: {'weight_class_0': 0.01754446017052777, 'weight_class_1': 0.8133066127678205, 'weight_class_2': 0.6857559286722691}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:24,622] Trial 510 finished with value: 0.7264471366621911 and parameters: {'weight_class_0': 0.001435952997831474, 'weight_class_1': 0.8577237859262612, 'weight_class_2': 0.394530848274077}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:24,650] Trial 511 finished with value: 0.9492123975030023 and parameters: {'weight_class_0': 0.03685935198539313, 'weight_class_1': 0.28986449230954037, 'weight_class_2': 0.3728031916545004}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:24,655] Trial 512 finished with value: 0.9045033031434403 and parameters: {'weight_class_0': 0.03910882107467557, 'weight_class_1': 0.0233073143174408, 'weight_class_2': 0.3698671569286624}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:24,702] Trial 513 finished with value: 0.9493662064675306 and parameters: {'weight_class_0': 0.039212231628666286, 'weight_class_1': 0.8794676030371252, 'weight_class_2': 0.6568890382679813}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:24,721] Trial 514 finished with value: 0.9492620948396929 and parameters: {'weight_class_0': 0.036073068840271325, 'weight_class_1': 0.2908924167538952, 'weight_class_2': 0.3949760234021191}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:24,733] Trial 515 finished with value: 0.9487492451603005 and parameters: {'weight_class_0': 0.03943836164919049, 'weight_class_1': 0.2826007898373111, 'weight_class_2': 0.5186954339856956}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:24,749] Trial 516 finished with value: 0.9483994876204802 and parameters: {'weight_class_0': 0.03596671417488215, 'weight_class_1': 0.28441368007138623, 'weight_class_2': 0.6156054840886136}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:24,769] Trial 517 finished with value: 0.9457643976391378 and parameters: {'weight_class_0': 0.028003289949395736, 'weight_class_1': 0.8752132783056745, 'weight_class_2': 1.8944323152732017}. Best is trial 433 with value: 0.9498304662349432.

[I 2026-07-05 15:25:24,792] Trial 518 finished with value: 0.949181517615806 and parameters: {'weight_class_0': 0.03661612294277893, 'weight_class_1': 0.27161693475777404, 'weight_class_2': 0.3534715072390318}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:24,829] Trial 520 finished with value: 0.8233996440971662 and parameters: {'weight_class_0': 0.03562295703599457, 'weight_class_1': 0.0011470340795652432, 'weight_class_2': 0.5289822391048525}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:24,852] Trial 519 finished with value: 0.9060890327896184 and parameters: {'weight_class_0': 0.03540153670216672, 'weight_class_1': 0.023040791768630664, 'weight_class_2': 0.49044176842282305}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:24,864] Trial 521 finished with value: 0.9495849090637689 and parameters: {'weight_class_0': 0.04060688944955247, 'weight_class_1': 0.4620561647490758, 'weight_class_2': 0.5118318931092145}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:24,896] Trial 522 finished with value: 0.9494797966571195 and parameters: {'weight_class_0': 0.042225133839102695, 'weight_class_1': 0.4394304674872037, 'weight_class_2': 0.5323371705260106}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:24,897] Trial 523 finished with value: 0.9493506633806313 and parameters: {'weight_class_0': 0.03648436048161449, 'weight_class_1': 0.45115596755359105, 'weight_class_2': 0.285201584862203}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:24,935] Trial 524 finished with value: 0.9492107063561753 and parameters: {'weight_class_0': 0.027181898615986983, 'weight_class_1': 0.4494110990576292, 'weight_class_2': 0.4984573343979123}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:24,960] Trial 525 finished with value: 0.9488301002543281 and parameters: {'weight_class_0': 0.027414849594138153, 'weight_class_1': 1.0360147218002416, 'weight_class_2': 0.27042478016974714}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:24,976] Trial 526 finished with value: 0.9399474193418292 and parameters: {'weight_class_0': 0.10344208916482694, 'weight_class_1': 0.4529354989522532, 'weight_class_2': 0.27611178634050904}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:24,985] Trial 528 finished with value: 0.8327264353989047 and parameters: {'weight_class_0': 0.05015435292901399, 'weight_class_1': 0.01423728841150319, 'weight_class_2': 5.643450003017723}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:24,987] Trial 527 finished with value: 0.9222484664035573 and parameters: {'weight_class_0': 0.001907709392517951, 'weight_class_1': 0.22782809352826874, 'weight_class_2': 0.2879261370870551}. Best is trial 433 with value: 0.9498304662349432.

[I 2026-07-05 15:25:25,007] Trial 529 finished with value: 0.9486158760938936 and parameters: {'weight_class_0': 0.0466015701653764, 'weight_class_1': 0.4331845126670355, 'weight_class_2': 0.27087191883026734}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:25,074] Trial 531 finished with value: 0.92273675038635 and parameters: {'weight_class_0': 0.0018315562613138887, 'weight_class_1': 0.2251565721329903, 'weight_class_2': 0.2659498015466875}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:25,094] Trial 530 finished with value: 0.9313240203566183 and parameters: {'weight_class_0': 0.015412354574176985, 'weight_class_1': 2.04092518079299, 'weight_class_2': 0.2840019787747526}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:25,099] Trial 532 finished with value: 0.9184395253127567 and parameters: {'weight_class_0': 0.0017904111280697395, 'weight_class_1': 0.22289233657051766, 'weight_class_2': 0.28671759927554585}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:25,116] Trial 533 finished with value: 0.9497740715401344 and parameters: {'weight_class_0': 0.023352149468260686, 'weight_class_1': 0.39375990214318557, 'weight_class_2': 0.2827405563828358}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:25,147] Trial 534 finished with value: 0.9314438819834819 and parameters: {'weight_class_0': 0.10013385303687031, 'weight_class_1': 0.21819592771742385, 'weight_class_2': 0.2763698539588691}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:25,170] Trial 535 finished with value: 0.8553794900063633 and parameters: {'weight_class_0': 0.3771747975874391, 'weight_class_1': 0.22468233481594463, 'weight_class_2': 0.25561171159658574}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:25,187] Trial 536 finished with value: 0.9288686419335109 and parameters: {'weight_class_0': 0.10340243836201875, 'weight_class_1': 0.2090617585082454, 'weight_class_2': 0.2660979240164759}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:25,223] Trial 537 finished with value: 0.796942027429368 and parameters: {'weight_class_0': 0.015417173501624552, 'weight_class_1': 0.2225437980577643, 'weight_class_2': 7.585864362221498}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  18%|████████████████████████▎                                                                                                            | 547/3000 [00:10<00:52, 46.42it/s]

[I 2026-07-05 15:25:25,251] Trial 538 finished with value: 0.9492828621573954 and parameters: {'weight_class_0': 0.02212359736323182, 'weight_class_1': 0.22488129372385174, 'weight_class_2': 0.16899747227654738}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:25,254] Trial 540 finished with value: 0.9493620647460234 and parameters: {'weight_class_0': 0.0223981440343075, 'weight_class_1': 0.215945933111001, 'weight_class_2': 0.17737801598351255}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:25,269] Trial 539 finished with value: 0.9488315632033161 and parameters: {'weight_class_0': 0.022869577997530442, 'weight_class_1': 0.2261416473503186, 'weight_class_2': 0.14072749238761248}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:25,303] Trial 541 finished with value: 0.94833324087098 and parameters: {'weight_class_0': 0.022463848606485703, 'weight_class_1': 0.7470871962126433, 'weight_class_2': 0.1385746840926497}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:25,323] Trial 542 finished with value: 0.9489213761182552 and parameters: {'weight_class_0': 0.023184033813016206, 'weight_class_1': 0.32885713633836433, 'weight_class_2': 0.1447602073967664}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:25,332] Trial 543 finished with value: 0.9482180684395325 and parameters: {'weight_class_0': 0.02327521048971255, 'weight_class_1': 0.7704915085686362, 'weight_class_2': 0.13851828471090774}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:25,361] Trial 544 finished with value: 0.9489800204190401 and parameters: {'weight_class_0': 0.02204483761654656, 'weight_class_1': 0.3655021493914455, 'weight_class_2': 0.14443292095675284}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:25,401] Trial 545 finished with value: 0.9490433293746793 and parameters: {'weight_class_0': 0.02204519308355121, 'weight_class_1': 0.6711471068213599, 'weight_class_2': 0.1764531831103931}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:25,414] Trial 546 finished with value: 0.9481837541101498 and parameters: {'weight_class_0': 0.02295002838133242, 'weight_class_1': 0.7683829476393345, 'weight_class_2': 0.13692775424199516}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:25,458] Trial 548 finished with value: 0.9054879009096751 and parameters: {'weight_class_0': 0.021894266094185308, 'weight_class_1': 0.33393711124469017, 'weight_class_2': 0.01894847459881607}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  19%|████████████████████████▋                                                                                                            | 557/3000 [00:11<00:54, 44.63it/s]

[I 2026-07-05 15:25:25,473] Trial 547 finished with value: 0.9390364933411446 and parameters: {'weight_class_0': 0.06273283471751391, 'weight_class_1': 0.7365407355514845, 'weight_class_2': 0.14576839854515447}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:25,479] Trial 549 finished with value: 0.8975059147248086 and parameters: {'weight_class_0': 0.1977184480513345, 'weight_class_1': 0.7128314934328815, 'weight_class_2': 0.14045789299122496}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:25,497] Trial 550 finished with value: 0.939298363568783 and parameters: {'weight_class_0': 0.05680271496735926, 'weight_class_1': 0.7415975008176607, 'weight_class_2': 0.1337868710021462}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:25,508] Trial 551 finished with value: 0.9470048740235377 and parameters: {'weight_class_0': 0.028627515666307276, 'weight_class_1': 0.7114254634612167, 'weight_class_2': 0.1205488378540168}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:25,567] Trial 552 finished with value: 0.9143250188672806 and parameters: {'weight_class_0': 0.016577513392057944, 'weight_class_1': 0.6572116763137698, 'weight_class_2': 0.019200003024769912}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:25,587] Trial 553 finished with value: 0.9497450988849566 and parameters: {'weight_class_0': 0.02933033582598135, 'weight_class_1': 0.659078545565207, 'weight_class_2': 0.34751637418950776}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:25,593] Trial 554 finished with value: 0.9308463910519009 and parameters: {'weight_class_0': 0.18425416497168162, 'weight_class_1': 0.6840430247122911, 'weight_class_2': 0.3646634971466024}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:25,623] Trial 556 finished with value: 0.9478348562603961 and parameters: {'weight_class_0': 0.05745724774986289, 'weight_class_1': 0.3169822714815445, 'weight_class_2': 0.3509408921178761}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:25,629] Trial 555 finished with value: 0.8944484077415088 and parameters: {'weight_class_0': 0.054669821009642974, 'weight_class_1': 0.3134470845442203, 'weight_class_2': 0.01977765339582539}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:25,649] Trial 558 finished with value: 0.8907622652992916 and parameters: {'weight_class_0': 0.06276235620555377, 'weight_class_1': 0.28490609419076224, 'weight_class_2': 0.013364975007889742}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  19%|█████████████████████████▏                                                                                                           | 567/3000 [00:11<00:51, 46.87it/s]

[I 2026-07-05 15:25:25,672] Trial 559 finished with value: 0.94853281296401 and parameters: {'weight_class_0': 0.015871916165610064, 'weight_class_1': 0.295512332194407, 'weight_class_2': 0.3887576964774936}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:25,673] Trial 557 finished with value: 0.9494621349126984 and parameters: {'weight_class_0': 0.028937995043266135, 'weight_class_1': 0.31307133369323387, 'weight_class_2': 0.379969456364336}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:25,710] Trial 560 finished with value: 0.9486111697386557 and parameters: {'weight_class_0': 0.015018649036498681, 'weight_class_1': 0.37744652984874705, 'weight_class_2': 0.36506727971533814}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:25,725] Trial 561 finished with value: 0.9486882216004769 and parameters: {'weight_class_0': 0.015872901924781104, 'weight_class_1': 0.3739832403022229, 'weight_class_2': 0.37467628656020546}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:25,765] Trial 562 finished with value: 0.949612609702167 and parameters: {'weight_class_0': 0.02904626853928663, 'weight_class_1': 0.2749017681052037, 'weight_class_2': 0.3340711041985836}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:25,802] Trial 563 finished with value: 0.6970544118103069 and parameters: {'weight_class_0': 3.330004568698381, 'weight_class_1': 1.0491889549336646, 'weight_class_2': 0.01302678840588826}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:25,819] Trial 564 finished with value: 0.8878165810310451 and parameters: {'weight_class_0': 0.5193320161218506, 'weight_class_1': 0.9439554470732635, 'weight_class_2': 0.40494734020070267}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:25,829] Trial 565 finished with value: 0.9492236230831246 and parameters: {'weight_class_0': 0.03135924644420422, 'weight_class_1': 1.045926326151839, 'weight_class_2': 0.39033561306554126}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:25,854] Trial 566 finished with value: 0.9488966560456119 and parameters: {'weight_class_0': 0.02978707711849539, 'weight_class_1': 1.0657140441312483, 'weight_class_2': 0.4522972724808566}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:25,900] Trial 568 finished with value: 0.9481985222729037 and parameters: {'weight_class_0': 0.028649135137746834, 'weight_class_1': 1.065768694146068, 'weight_class_2': 0.6578290330485792}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  19%|█████████████████████████▌                                                                                                           | 577/3000 [00:11<00:52, 46.03it/s]

[I 2026-07-05 15:25:25,912] Trial 567 finished with value: 0.8345734174939032 and parameters: {'weight_class_0': 2.8943735880921584, 'weight_class_1': 0.9611550702878334, 'weight_class_2': 0.4920182041352346}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:25,924] Trial 569 finished with value: 0.9486586739792485 and parameters: {'weight_class_0': 0.02968226340009701, 'weight_class_1': 0.4883363818910566, 'weight_class_2': 0.659588941955988}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:25,963] Trial 571 finished with value: 0.9485957704551721 and parameters: {'weight_class_0': 0.02793822150646149, 'weight_class_1': 1.055304522253816, 'weight_class_2': 0.509622520292598}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:25,969] Trial 570 finished with value: 0.8736787235088102 and parameters: {'weight_class_0': 0.02784103365263319, 'weight_class_1': 0.002350494340695701, 'weight_class_2': 0.3226672309197826}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:25,997] Trial 572 finished with value: 0.9397245329850485 and parameters: {'weight_class_0': 0.045036388916799286, 'weight_class_1': 1.0457230242308446, 'weight_class_2': 0.10800762805165467}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:26,004] Trial 573 finished with value: 0.9487562179783585 and parameters: {'weight_class_0': 0.02971225503443339, 'weight_class_1': 1.1214525608645896, 'weight_class_2': 0.4563951275808726}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:26,034] Trial 574 finished with value: 0.933443351269026 and parameters: {'weight_class_0': 0.046911029497023624, 'weight_class_1': 0.5177922774020289, 'weight_class_2': 0.08994373680075096}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:26,075] Trial 575 finished with value: 0.8945198294479159 and parameters: {'weight_class_0': 0.029212969997818597, 'weight_class_1': 0.48421425781591015, 'weight_class_2': 0.009553296950682678}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:26,088] Trial 577 finished with value: 0.9495430927163061 and parameters: {'weight_class_0': 0.0501303228812947, 'weight_class_1': 0.4916888828381198, 'weight_class_2': 0.6071855660938204}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:26,093] Trial 576 finished with value: 0.935579636946144 and parameters: {'weight_class_0': 0.044019111841154965, 'weight_class_1': 0.5068588419471047, 'weight_class_2': 0.09073673655225119}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  20%|██████████████████████████                                                                                                           | 587/3000 [00:11<00:51, 46.95it/s]

[I 2026-07-05 15:25:26,127] Trial 578 finished with value: 0.9490735279506026 and parameters: {'weight_class_0': 0.04640619122745572, 'weight_class_1': 0.5104933184813392, 'weight_class_2': 0.3333616543269765}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:26,159] Trial 579 finished with value: 0.9483960765885256 and parameters: {'weight_class_0': 0.0451713542743961, 'weight_class_1': 0.5137780047732772, 'weight_class_2': 0.9420415861969981}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:26,179] Trial 581 finished with value: 0.9476508686703928 and parameters: {'weight_class_0': 0.011961293339426655, 'weight_class_1': 0.595566408780479, 'weight_class_2': 0.08888544489503028}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:26,181] Trial 580 finished with value: 0.9496693756318447 and parameters: {'weight_class_0': 0.0474907895958872, 'weight_class_1': 0.5941219019478854, 'weight_class_2': 0.4543408718430148}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:26,230] Trial 583 finished with value: 0.9474520154132634 and parameters: {'weight_class_0': 0.012097087172946054, 'weight_class_1': 0.5671557492926953, 'weight_class_2': 0.3096620106336186}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:26,245] Trial 582 finished with value: 0.9474249893546242 and parameters: {'weight_class_0': 0.012150530165737883, 'weight_class_1': 0.6062526921115258, 'weight_class_2': 0.08291575694692745}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:26,252] Trial 584 finished with value: 0.9028035999895706 and parameters: {'weight_class_0': 0.011594634672245587, 'weight_class_1': 0.596154215208218, 'weight_class_2': 0.010121858530664118}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:26,282] Trial 585 finished with value: 0.900011761580365 and parameters: {'weight_class_0': 0.012546950858266404, 'weight_class_1': 0.5707841962122848, 'weight_class_2': 0.00948451703646372}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:26,287] Trial 586 finished with value: 0.9444901595971039 and parameters: {'weight_class_0': 0.011960882066925124, 'weight_class_1': 0.6142106711368569, 'weight_class_2': 0.9193894756351428}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:26,332] Trial 587 finished with value: 0.8680615604500649 and parameters: {'weight_class_0': 0.0024128017283488296, 'weight_class_1': 0.6253310964919212, 'weight_class_2': 0.2978277862122431}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  20%|██████████████████████████▍                                                                                                          | 597/3000 [00:11<00:52, 46.17it/s]

[I 2026-07-05 15:25:26,372] Trial 588 finished with value: 0.9475437226512028 and parameters: {'weight_class_0': 0.013217425226359937, 'weight_class_1': 0.6357963808986752, 'weight_class_2': 0.3104384366227251}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:26,379] Trial 589 finished with value: 0.8887922332610327 and parameters: {'weight_class_0': 0.011959458537871743, 'weight_class_1': 0.6111241448952599, 'weight_class_2': 0.004219283691921451}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:26,386] Trial 590 finished with value: 0.9476183398188218 and parameters: {'weight_class_0': 0.011462760367472359, 'weight_class_1': 0.5684636699380891, 'weight_class_2': 0.23001740518599542}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:26,407] Trial 591 finished with value: 0.9482702860095756 and parameters: {'weight_class_0': 0.011601909817702618, 'weight_class_1': 0.3654342009868494, 'weight_class_2': 0.3159976287206786}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:26,433] Trial 592 finished with value: 0.9485208807388265 and parameters: {'weight_class_0': 0.01137334850466894, 'weight_class_1': 0.3839648004683326, 'weight_class_2': 0.24062818909748523}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:26,460] Trial 593 finished with value: 0.9085489518481235 and parameters: {'weight_class_0': 0.002247455985193272, 'weight_class_1': 0.3987633856421906, 'weight_class_2': 0.24250783960145003}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:26,465] Trial 594 finished with value: 0.9491162751334219 and parameters: {'weight_class_0': 0.03343455368137869, 'weight_class_1': 0.4036323775875028, 'weight_class_2': 0.23758171029757724}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:26,513] Trial 596 finished with value: 0.9491157198431459 and parameters: {'weight_class_0': 0.03394414961438234, 'weight_class_1': 0.41604678722674787, 'weight_class_2': 0.23166849634146486}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:26,515] Trial 595 finished with value: 0.9481842139342914 and parameters: {'weight_class_0': 0.036796144618221074, 'weight_class_1': 0.39373951101671445, 'weight_class_2': 0.1850256473378651}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:26,536] Trial 597 finished with value: 0.9103221280979362 and parameters: {'weight_class_0': 0.002307786810987683, 'weight_class_1': 0.4028725098013839, 'weight_class_2': 0.2376610386917124}. Best is trial 433 with value: 0.9498304662349432.

[I 2026-07-05 15:25:26,562] Trial 599 finished with value: 0.948967486687331 and parameters: {'weight_class_0': 0.03536747179134618, 'weight_class_1': 0.402751737250135, 'weight_class_2': 0.22965432477926354}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:26,575] Trial 598 finished with value: 0.9495989709202407 and parameters: {'weight_class_0': 0.018441076085113153, 'weight_class_1': 0.4249691333665228, 'weight_class_2': 0.23760220923885314}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:26,616] Trial 600 finished with value: 0.9489070267244987 and parameters: {'weight_class_0': 0.037326278359930166, 'weight_class_1': 0.3905902248473874, 'weight_class_2': 0.24681835577214867}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:26,633] Trial 601 finished with value: 0.9474408383640434 and parameters: {'weight_class_0': 0.039386568873185014, 'weight_class_1': 0.42556091538082663, 'weight_class_2': 0.17374229288868376}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:26,647] Trial 602 finished with value: 0.9482623585739667 and parameters: {'weight_class_0': 0.03540350962178072, 'weight_class_1': 0.39701711109431803, 'weight_class_2': 0.1811044610063465}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:26,676] Trial 603 finished with value: 0.9488545734258026 and parameters: {'weight_class_0': 0.008254258181587107, 'weight_class_1': 0.15086411407460545, 'weight_class_2': 0.17796036275329097}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:26,702] Trial 604 finished with value: 0.9483428319916923 and parameters: {'weight_class_0': 0.03604814837619296, 'weight_class_1': 0.8477249952324238, 'weight_class_2': 0.19668349071083419}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:26,707] Trial 605 finished with value: 0.9392649162917852 and parameters: {'weight_class_0': 0.008175593759820186, 'weight_class_1': 0.8613888469556085, 'weight_class_2': 0.17963111413000568}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:26,714] Trial 606 finished with value: 0.9467622842392786 and parameters: {'weight_class_0': 0.035948182542279314, 'weight_class_1': 0.18520000564762992, 'weight_class_2': 0.17494337786386385}. Best is trial 433 with value: 0.9498304662349432.

[I 2026-07-05 15:25:26,772] Trial 607 finished with value: 0.8380638482531956 and parameters: {'weight_class_0': 0.0012077212319271204, 'weight_class_1': 0.1617981412736957, 'weight_class_2': 0.43811561574171304}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:26,783] Trial 609 finished with value: 0.9392468985742957 and parameters: {'weight_class_0': 0.007512993079024678, 'weight_class_1': 0.018229136234436526, 'weight_class_2': 0.17384769720099}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:26,791] Trial 608 finished with value: 0.8259070882087792 and parameters: {'weight_class_0': 0.007873265019465477, 'weight_class_1': 0.8677921529335993, 'weight_class_2': 3.22418607624026}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:26,807] Trial 610 finished with value: 0.9401653355606922 and parameters: {'weight_class_0': 0.007856166697919395, 'weight_class_1': 0.02024592552900631, 'weight_class_2': 0.17844037459311876}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:26,827] Trial 611 finished with value: 0.9496785243483864 and parameters: {'weight_class_0': 0.008190952535311382, 'weight_class_1': 0.14683582922203278, 'weight_class_2': 0.10842303278801498}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:26,838] Trial 612 finished with value: 0.9381067578799848 and parameters: {'weight_class_0': 0.007618932015680293, 'weight_class_1': 0.8458512239664336, 'weight_class_2': 0.10612430565307042}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:26,868] Trial 613 finished with value: 0.9272462767596007 and parameters: {'weight_class_0': 0.024975549650219177, 'weight_class_1': 0.03781457525429715, 'weight_class_2': 0.11320221798372455}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:26,882] Trial 614 finished with value: 0.9159550153766309 and parameters: {'weight_class_0': 0.08915433293316351, 'weight_class_1': 1.3861923347458251, 'weight_class_2': 0.10423409368391422}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:26,936] Trial 616 finished with value: 0.9473390073332354 and parameters: {'weight_class_0': 0.024883877313706785, 'weight_class_1': 0.25330872180903036, 'weight_class_2': 0.7590997309438559}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:26,956] Trial 615 finished with value: 0.9438058010726733 and parameters: {'weight_class_0': 0.01846092216219998, 'weight_class_1': 1.4671387407440482, 'weight_class_2': 0.11336471606611118}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  21%|███████████████████████████▊                                                                                                         | 626/3000 [00:12<00:51, 46.46it/s]

[I 2026-07-05 15:25:26,974] Trial 617 finished with value: 0.9488450875388982 and parameters: {'weight_class_0': 0.01817599287840998, 'weight_class_1': 0.26985163620788527, 'weight_class_2': 0.11127659727644425}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:26,991] Trial 618 finished with value: 0.9421954483746567 and parameters: {'weight_class_0': 0.0895937366431862, 'weight_class_1': 0.25268053941009905, 'weight_class_2': 0.5863761063632595}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:27,013] Trial 620 finished with value: 0.9452766309257057 and parameters: {'weight_class_0': 0.0014695572785913744, 'weight_class_1': 0.036066098981807224, 'weight_class_2': 0.10934565760726106}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:27,032] Trial 619 finished with value: 0.9260060047463039 and parameters: {'weight_class_0': 0.025926298476998386, 'weight_class_1': 0.03643197067416629, 'weight_class_2': 0.6385585442217028}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:27,070] Trial 621 finished with value: 0.8888108178660342 and parameters: {'weight_class_0': 0.02524041950294069, 'weight_class_1': 0.0070166913674919945, 'weight_class_2': 0.4520035015731828}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:27,084] Trial 622 finished with value: 0.9259688619304418 and parameters: {'weight_class_0': 0.025578867615998098, 'weight_class_1': 0.036306890389366464, 'weight_class_2': 0.7260353250075481}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:27,101] Trial 623 finished with value: 0.9477220226694977 and parameters: {'weight_class_0': 0.016693813436385548, 'weight_class_1': 0.291414423188891, 'weight_class_2': 0.548281570995803}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:27,129] Trial 624 finished with value: 0.9477895845102774 and parameters: {'weight_class_0': 0.017954674882854696, 'weight_class_1': 0.26780433595503866, 'weight_class_2': 0.5323567977560911}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:27,136] Trial 625 finished with value: 0.9473667118393377 and parameters: {'weight_class_0': 0.01680807311894321, 'weight_class_1': 0.26036648135198576, 'weight_class_2': 0.6191056649365314}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:27,175] Trial 626 finished with value: 0.9391019927804404 and parameters: {'weight_class_0': 0.017847340293620007, 'weight_class_1': 0.045260665953812965, 'weight_class_2': 0.6279543977280342}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  21%|████████████████████████████▏                                                                                                        | 636/3000 [00:12<00:50, 46.67it/s]

[I 2026-07-05 15:25:27,205] Trial 627 finished with value: 0.9475822060860911 and parameters: {'weight_class_0': 0.01715733968317754, 'weight_class_1': 0.31177425420279564, 'weight_class_2': 0.60577471978486}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:27,213] Trial 628 finished with value: 0.9163443799036912 and parameters: {'weight_class_0': 0.02632726158604185, 'weight_class_1': 0.02601916874031061, 'weight_class_2': 0.33461238019321116}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:27,227] Trial 629 finished with value: 0.9332637965889373 and parameters: {'weight_class_0': 0.014993142970100548, 'weight_class_1': 0.027442848512173487, 'weight_class_2': 0.4167508110715925}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:27,253] Trial 630 finished with value: 0.9477072120433011 and parameters: {'weight_class_0': 0.015224585695769198, 'weight_class_1': 0.19123182869124855, 'weight_class_2': 0.435439602477161}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:27,285] Trial 631 finished with value: 0.9483168206154101 and parameters: {'weight_class_0': 0.016503383058581785, 'weight_class_1': 0.18141581827193998, 'weight_class_2': 0.3434538503007147}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:27,301] Trial 632 finished with value: 0.9403764246828485 and parameters: {'weight_class_0': 0.06948611543905138, 'weight_class_1': 0.1838514475720599, 'weight_class_2': 0.345172209874341}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:27,325] Trial 633 finished with value: 0.9091319428441723 and parameters: {'weight_class_0': 0.01642552173671813, 'weight_class_1': 0.012542360520220647, 'weight_class_2': 0.3417218923527588}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:27,338] Trial 634 finished with value: 0.9482670383239687 and parameters: {'weight_class_0': 0.015051875375164035, 'weight_class_1': 0.18748741858107887, 'weight_class_2': 0.33889370424863297}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:27,375] Trial 636 finished with value: 0.8269517206669516 and parameters: {'weight_class_0': 0.021906260177892437, 'weight_class_1': 7.711198738981727, 'weight_class_2': 0.33745476732580415}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:27,378] Trial 635 finished with value: 0.9488622860218805 and parameters: {'weight_class_0': 0.020312610321884996, 'weight_class_1': 0.18932347964159418, 'weight_class_2': 0.3272010938042479}. Best is trial 433 with value: 0.9498304662349432.

[I 2026-07-05 15:25:27,411] Trial 637 finished with value: 0.9486971101198453 and parameters: {'weight_class_0': 0.020993743773525413, 'weight_class_1': 0.3331445412414369, 'weight_class_2': 0.45287091778739036}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:27,417] Trial 638 finished with value: 0.940562817770414 and parameters: {'weight_class_0': 0.07019958621122939, 'weight_class_1': 0.19442282915939246, 'weight_class_2': 0.3176441782349585}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:27,465] Trial 639 finished with value: 0.9423131481899998 and parameters: {'weight_class_0': 0.06452727545911528, 'weight_class_1': 0.1988436003879504, 'weight_class_2': 0.30648536982692876}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:27,470] Trial 640 finished with value: 0.9391391300434201 and parameters: {'weight_class_0': 0.06938621831364937, 'weight_class_1': 0.17586883219448968, 'weight_class_2': 0.31105767197702927}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:27,481] Trial 641 finished with value: 0.9493917282064667 and parameters: {'weight_class_0': 0.020725757649664035, 'weight_class_1': 0.478567945146796, 'weight_class_2': 0.3169411623440373}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:27,512] Trial 642 finished with value: 0.940561936785829 and parameters: {'weight_class_0': 0.06983587027365665, 'weight_class_1': 0.19408485392324804, 'weight_class_2': 0.31165428063145606}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:27,525] Trial 643 finished with value: 0.8833770413448692 and parameters: {'weight_class_0': 0.05570661622444881, 'weight_class_1': 0.010814013035984308, 'weight_class_2': 0.305565551360593}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:27,567] Trial 644 finished with value: 0.917786388905327 and parameters: {'weight_class_0': 0.021583894468109346, 'weight_class_1': 0.1445274040394191, 'weight_class_2': 0.026930641967348925}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:27,576] Trial 645 finished with value: 0.9470961048377468 and parameters: {'weight_class_0': 0.020176956980111873, 'weight_class_1': 0.33081913523770295, 'weight_class_2': 0.08331013114261014}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:27,579] Trial 646 finished with value: 0.9480860661342833 and parameters: {'weight_class_0': 0.020645973999671316, 'weight_class_1': 0.12215707867791674, 'weight_class_2': 0.299308367673032}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  22%|█████████████████████████████                                                                                                        | 656/3000 [00:13<00:51, 45.71it/s]

[I 2026-07-05 15:25:27,602] Trial 647 finished with value: 0.9480773359219592 and parameters: {'weight_class_0': 0.05519790908914403, 'weight_class_1': 0.48001655992312037, 'weight_class_2': 0.275168425750345}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:27,646] Trial 648 finished with value: 0.9496204309533286 and parameters: {'weight_class_0': 0.0064272875378457335, 'weight_class_1': 0.12647411503718825, 'weight_class_2': 0.08676093253240387}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:27,659] Trial 650 finished with value: 0.9452373629921539 and parameters: {'weight_class_0': 0.006149749934566516, 'weight_class_1': 0.47725273273090013, 'weight_class_2': 0.07895228382387454}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:27,683] Trial 649 finished with value: 0.9495494361915667 and parameters: {'weight_class_0': 0.03156410184707472, 'weight_class_1': 0.47803346320506496, 'weight_class_2': 0.27284899877897806}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:27,722] Trial 651 finished with value: 0.9482034948945762 and parameters: {'weight_class_0': 0.05495248656806694, 'weight_class_1': 0.7161492773846057, 'weight_class_2': 1.3121620094583317}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:27,739] Trial 652 finished with value: 0.9231171920533866 and parameters: {'weight_class_0': 0.006577033103725751, 'weight_class_1': 0.1435359079048297, 'weight_class_2': 1.2105977379764}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:27,752] Trial 653 finished with value: 0.9441178016572253 and parameters: {'weight_class_0': 0.029811023082756925, 'weight_class_1': 0.724551447352207, 'weight_class_2': 0.09129897338861032}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:27,782] Trial 654 finished with value: 0.8557317923956348 and parameters: {'weight_class_0': 0.006463757708306438, 'weight_class_1': 1.9123940872404415, 'weight_class_2': 0.26723214522352867}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:27,798] Trial 655 finished with value: 0.9449995801537335 and parameters: {'weight_class_0': 0.0063210911468918884, 'weight_class_1': 0.4988730063845436, 'weight_class_2': 0.08488009094179279}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:27,816] Trial 656 finished with value: 0.8974842216432181 and parameters: {'weight_class_0': 0.1493768731366058, 'weight_class_1': 0.7429583614190216, 'weight_class_2': 0.08721956658760051}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  22%|█████████████████████████████▌                                                                                                       | 667/3000 [00:13<00:50, 46.60it/s]

[I 2026-07-05 15:25:27,829] Trial 657 finished with value: 0.8970298076181331 and parameters: {'weight_class_0': 0.031546313819803905, 'weight_class_1': 0.7202097268310118, 'weight_class_2': 0.01572032867967261}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:27,858] Trial 658 finished with value: 0.9427906527558102 and parameters: {'weight_class_0': 0.031636585218524506, 'weight_class_1': 0.7311627791328298, 'weight_class_2': 0.08823484146901726}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:27,877] Trial 660 finished with value: 0.9437198894436861 and parameters: {'weight_class_0': 0.00963812208504989, 'weight_class_1': 0.7412666594747422, 'weight_class_2': 0.4728534917165219}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:27,915] Trial 659 finished with value: 0.9442253716639019 and parameters: {'weight_class_0': 0.009476476275271692, 'weight_class_1': 0.7626246074720999, 'weight_class_2': 0.2095192181257069}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:27,931] Trial 661 finished with value: 0.8970788518056309 and parameters: {'weight_class_0': 0.031145321444493054, 'weight_class_1': 0.7195734308713541, 'weight_class_2': 0.01573263664198106}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:27,952] Trial 663 finished with value: 0.9471917139045466 and parameters: {'weight_class_0': 0.00929593016197925, 'weight_class_1': 0.32029021725426365, 'weight_class_2': 0.41241112588051476}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:27,965] Trial 662 finished with value: 0.9494887892186926 and parameters: {'weight_class_0': 0.03145584327261749, 'weight_class_1': 0.34724518674549937, 'weight_class_2': 0.40674655424408546}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,003] Trial 665 finished with value: 0.9480411806873758 and parameters: {'weight_class_0': 0.04282059130163057, 'weight_class_1': 0.8152379078541815, 'weight_class_2': 0.21258414540501594}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,004] Trial 664 finished with value: 0.9475342608264236 and parameters: {'weight_class_0': 0.01028857917036074, 'weight_class_1': 0.2509956207091565, 'weight_class_2': 0.3991257145525478}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,021] Trial 666 finished with value: 0.9472677256707828 and parameters: {'weight_class_0': 0.04373980149112563, 'weight_class_1': 0.2427788320669988, 'weight_class_2': 0.21944487979475644}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,056] Trial 667 finished with value: 0.9472682681707911 and parameters: {'weight_class_0': 0.00892326968209653, 'weight_class_1': 0.24813678911666862, 'weight_class_2': 0.39733677008219154}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  23%|█████████████████████████████▉                                                                                                       | 676/3000 [00:13<00:52, 44.11it/s]

[I 2026-07-05 15:25:28,067] Trial 668 finished with value: 0.9483665061652612 and parameters: {'weight_class_0': 0.009657954896386049, 'weight_class_1': 0.34330857978681634, 'weight_class_2': 0.20956123200763552}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,108] Trial 669 finished with value: 0.9489961751935926 and parameters: {'weight_class_0': 0.025523721085211986, 'weight_class_1': 0.2464268837833235, 'weight_class_2': 0.4006638884871502}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,141] Trial 670 finished with value: 0.9493774399094036 and parameters: {'weight_class_0': 0.02647236487736935, 'weight_class_1': 0.3377106103688357, 'weight_class_2': 0.2090344956713374}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,145] Trial 671 finished with value: 0.9492968033160863 and parameters: {'weight_class_0': 0.025626389769421262, 'weight_class_1': 0.3355504596173194, 'weight_class_2': 0.40666809920212904}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,180] Trial 672 finished with value: 0.9441139341170905 and parameters: {'weight_class_0': 0.044211053825288414, 'weight_class_1': 0.35822351641528766, 'weight_class_2': 0.1361800651793314}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,195] Trial 673 finished with value: 0.9461985661508187 and parameters: {'weight_class_0': 0.02492674238288773, 'weight_class_1': 1.2909606773521132, 'weight_class_2': 0.12217627755885636}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,206] Trial 674 finished with value: 0.8670612225663815 and parameters: {'weight_class_0': 0.2784966181510104, 'weight_class_1': 0.26122618060039676, 'weight_class_2': 0.20513811487392697}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,226] Trial 676 finished with value: 0.9472619173714981 and parameters: {'weight_class_0': 0.025768107501080745, 'weight_class_1': 1.2617294071222394, 'weight_class_2': 0.15754527683257658}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,232] Trial 675 finished with value: 0.8240887386045602 and parameters: {'weight_class_0': 1.2883571118066697, 'weight_class_1': 0.062292363690353285, 'weight_class_2': 0.8783468295144453}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  23%|██████████████████████████████▍                                                                                                      | 687/3000 [00:13<00:47, 48.45it/s]

[I 2026-07-05 15:25:28,273] Trial 677 finished with value: 0.9489710747835886 and parameters: {'weight_class_0': 0.023874898204910604, 'weight_class_1': 0.34403478863644066, 'weight_class_2': 0.15146976331401155}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,286] Trial 678 finished with value: 0.8156908572380591 and parameters: {'weight_class_0': 0.0020466918422505963, 'weight_class_1': 0.3384065087515328, 'weight_class_2': 0.8161119880218755}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,297] Trial 679 finished with value: 0.8880466072118405 and parameters: {'weight_class_0': 0.0019765349729209533, 'weight_class_1': 0.45090391040657885, 'weight_class_2': 0.1260929258739799}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,319] Trial 680 finished with value: 0.903363360231635 and parameters: {'weight_class_0': 0.026025115438253907, 'weight_class_1': 0.01544184032453512, 'weight_class_2': 0.1470402661625126}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,329] Trial 681 finished with value: 0.9375510643181721 and parameters: {'weight_class_0': 0.02594548659570825, 'weight_class_1': 0.058492840073244325, 'weight_class_2': 0.12669301808859704}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,357] Trial 682 finished with value: 0.7155611261581001 and parameters: {'weight_class_0': 0.0015746653873907608, 'weight_class_1': 1.3334425021921243, 'weight_class_2': 0.1257328262500806}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,375] Trial 683 finished with value: 0.8954427662248808 and parameters: {'weight_class_0': 0.0037287634457429087, 'weight_class_1': 0.06548443689159504, 'weight_class_2': 0.0014189347780514622}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,414] Trial 684 finished with value: 0.7958377052032161 and parameters: {'weight_class_0': 0.0015644020122502981, 'weight_class_1': 0.4594574413616235, 'weight_class_2': 0.5007431801371117}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,416] Trial 685 finished with value: 0.9476884360427807 and parameters: {'weight_class_0': 0.014461731611635312, 'weight_class_1': 0.48705094481417516, 'weight_class_2': 0.5094861431072982}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,469] Trial 686 finished with value: 0.9325331049026421 and parameters: {'weight_class_0': 0.013219065994558488, 'weight_class_1': 0.046331221767681785, 'weight_class_2': 0.028190832321429854}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,482] Trial 687 finished with value: 0.9488768339857748 and parameters: {'weight_class_0': 0.014231220054083468, 'weight_class_1': 0.45137721602988773, 'weight_class_2': 0.2630200329732005}. Best is trial 433 with value: 0.9498304662349432.

[I 2026-07-05 15:25:28,510] Trial 688 finished with value: 0.920934009041278 and parameters: {'weight_class_0': 0.03921372798046606, 'weight_class_1': 0.04609696523850014, 'weight_class_2': 0.26186306003693377}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,567] Trial 691 finished with value: 0.9206922180403443 and parameters: {'weight_class_0': 0.003802662963389432, 'weight_class_1': 0.5936623772320154, 'weight_class_2': 0.263021453132185}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,572] Trial 689 finished with value: 0.7942733721008391 and parameters: {'weight_class_0': 0.003815983367267563, 'weight_class_1': 1.703711206780287, 'weight_class_2': 0.2568465273938899}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,576] Trial 690 finished with value: 0.8600411408975264 and parameters: {'weight_class_0': 0.00160850256421863, 'weight_class_1': 0.048076266992420735, 'weight_class_2': 0.5450129716441564}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,592] Trial 692 finished with value: 0.9481368284170034 and parameters: {'weight_class_0': 0.01382558538930728, 'weight_class_1': 0.6020162372112802, 'weight_class_2': 0.2659381426283067}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,611] Trial 693 finished with value: 0.9414191714640417 and parameters: {'weight_class_0': 0.0135453057536798, 'weight_class_1': 0.11158619091555096, 'weight_class_2': 0.03502488993823731}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,652] Trial 694 finished with value: 0.933684479297702 and parameters: {'weight_class_0': 0.013824310670968993, 'weight_class_1': 0.5575766045620528, 'weight_class_2': 0.02768865724585042}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,661] Trial 695 finished with value: 0.9482297169497228 and parameters: {'weight_class_0': 0.013751630865381545, 'weight_class_1': 0.5745568858756793, 'weight_class_2': 0.2703190186011336}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,671] Trial 696 finished with value: 0.8952847716294063 and parameters: {'weight_class_0': 0.04007284778071897, 'weight_class_1': 0.15261372747180835, 'weight_class_2': 0.02255581915855617}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  24%|███████████████████████████████▎                                                                                                     | 706/3000 [00:14<00:50, 45.77it/s]

[I 2026-07-05 15:25:28,703] Trial 697 finished with value: 0.9422349820367764 and parameters: {'weight_class_0': 0.05162499519997523, 'weight_class_1': 0.15586759238015466, 'weight_class_2': 0.25618949301560084}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,711] Trial 698 finished with value: 0.9488149540773833 and parameters: {'weight_class_0': 0.043233179365084924, 'weight_class_1': 0.5860881992621735, 'weight_class_2': 0.26158122886419116}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,732] Trial 699 finished with value: 0.9136099736988693 and parameters: {'weight_class_0': 0.04895581276153472, 'weight_class_1': 0.20890193131967733, 'weight_class_2': 0.05734584044832164}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,794] Trial 700 finished with value: 0.8137390170981377 and parameters: {'weight_class_0': 5.661790272578305, 'weight_class_1': 0.5714002331546949, 'weight_class_2': 0.25174090618082784}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,812] Trial 701 finished with value: 0.8895386153530526 and parameters: {'weight_class_0': 0.020366386022130863, 'weight_class_1': 0.005609299335095514, 'weight_class_2': 0.18902844039968505}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,834] Trial 702 finished with value: 0.8955774166956857 and parameters: {'weight_class_0': 0.04845277116179615, 'weight_class_1': 0.1455716377814209, 'weight_class_2': 0.035010733676954967}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,845] Trial 703 finished with value: 0.918190690836527 and parameters: {'weight_class_0': 0.0494034782166965, 'weight_class_1': 0.1567600819525587, 'weight_class_2': 0.07080718550863214}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,866] Trial 704 finished with value: 0.939321251254999 and parameters: {'weight_class_0': 0.05321772487692818, 'weight_class_1': 0.1579444818606526, 'weight_class_2': 0.18086767528015632}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,891] Trial 705 finished with value: 0.9495046622450141 and parameters: {'weight_class_0': 0.05087478130729592, 'weight_class_1': 0.915029564565472, 'weight_class_2': 0.7418213003237731}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,898] Trial 706 finished with value: 0.9496774505295918 and parameters: {'weight_class_0': 0.05190460461585211, 'weight_class_1': 0.9373248974435381, 'weight_class_2': 0.6837616624084433}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  24%|███████████████████████████████▋                                                                                                     | 716/3000 [00:14<00:48, 47.47it/s]

[I 2026-07-05 15:25:28,937] Trial 707 finished with value: 0.8300333425660149 and parameters: {'weight_class_0': 0.0026457828699783044, 'weight_class_1': 0.9317524828936122, 'weight_class_2': 0.18340028462141494}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,939] Trial 708 finished with value: 0.9470877967638445 and parameters: {'weight_class_0': 0.020778496956375094, 'weight_class_1': 0.21020133886968503, 'weight_class_2': 0.7008451843031618}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,969] Trial 709 finished with value: 0.9473386756583705 and parameters: {'weight_class_0': 0.0213058088577412, 'weight_class_1': 0.27149865234993736, 'weight_class_2': 0.722616106570837}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,970] Trial 710 finished with value: 0.9486389579045823 and parameters: {'weight_class_0': 0.02054261277348997, 'weight_class_1': 0.12402652552471138, 'weight_class_2': 0.18615518164978284}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:28,999] Trial 711 finished with value: 0.949529339616835 and parameters: {'weight_class_0': 0.020757465517082165, 'weight_class_1': 0.28002121132074775, 'weight_class_2': 0.17813012933194225}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:29,032] Trial 712 finished with value: 0.9496990542782605 and parameters: {'weight_class_0': 0.018880102889007298, 'weight_class_1': 0.2946641057584701, 'weight_class_2': 0.18455691613236486}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:29,048] Trial 713 finished with value: 0.9182055606333304 and parameters: {'weight_class_0': 0.005510975464302761, 'weight_class_1': 0.9092037394277821, 'weight_class_2': 0.16300165394606703}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:29,072] Trial 714 finished with value: 0.9495820654985004 and parameters: {'weight_class_0': 0.033458282784986866, 'weight_class_1': 0.8864416126697026, 'weight_class_2': 0.3718258945592709}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:29,074] Trial 715 finished with value: 0.9491908681127885 and parameters: {'weight_class_0': 0.03512805824364137, 'weight_class_1': 0.26814879094247035, 'weight_class_2': 0.3761339346272264}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  24%|████████████████████████████████▏                                                                                                    | 727/3000 [00:14<00:46, 48.40it/s]

[I 2026-07-05 15:25:29,137] Trial 716 finished with value: 0.9291712064055019 and parameters: {'weight_class_0': 0.0026879158142456886, 'weight_class_1': 0.2830163661734687, 'weight_class_2': 0.36845763670585197}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:29,139] Trial 717 finished with value: 0.9493285453803443 and parameters: {'weight_class_0': 0.033321006259432094, 'weight_class_1': 0.2811597625317508, 'weight_class_2': 0.3672527291135044}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:29,158] Trial 718 finished with value: 0.9493932031295982 and parameters: {'weight_class_0': 0.033654621803415136, 'weight_class_1': 0.286630727601443, 'weight_class_2': 0.38058925389439197}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:29,172] Trial 719 finished with value: 0.949357794870853 and parameters: {'weight_class_0': 0.034729148508525515, 'weight_class_1': 0.2922913012213315, 'weight_class_2': 0.35848151756917906}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:29,198] Trial 720 finished with value: 0.9497017754817811 and parameters: {'weight_class_0': 0.033795024848514287, 'weight_class_1': 0.42165476545110947, 'weight_class_2': 0.37500098428161016}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:29,206] Trial 721 finished with value: 0.9494627875966474 and parameters: {'weight_class_0': 0.033418521569721596, 'weight_class_1': 0.2928564115843292, 'weight_class_2': 0.3758505088626521}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:29,229] Trial 723 finished with value: 0.9430265429057393 and parameters: {'weight_class_0': 0.005428382726270162, 'weight_class_1': 0.41014665856778343, 'weight_class_2': 0.37329881930787}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:29,238] Trial 722 finished with value: 0.9497634062048688 and parameters: {'weight_class_0': 0.03173414291685544, 'weight_class_1': 0.4158010811598323, 'weight_class_2': 0.3597702010113676}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:29,261] Trial 724 finished with value: 0.9497159840638617 and parameters: {'weight_class_0': 0.03263457395012402, 'weight_class_1': 0.4498052274576927, 'weight_class_2': 0.35094962051082507}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:29,295] Trial 725 finished with value: 0.9490415888431952 and parameters: {'weight_class_0': 0.03129322641844988, 'weight_class_1': 0.4064632964556924, 'weight_class_2': 0.5488624650091879}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:29,297] Trial 726 finished with value: 0.9406271122942259 and parameters: {'weight_class_0': 0.030885772335295353, 'weight_class_1': 0.08623064250022329, 'weight_class_2': 1.0133266775697485}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:29,331] Trial 727 finished with value: 0.9493221275973592 and parameters: {'weight_class_0': 0.03146530391126623, 'weight_class_1': 0.41433933734445444, 'weight_class_2': 0.49808109150657137}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  25%|████████████████████████████████▋                                                                                                    | 737/3000 [00:15<00:48, 46.79it/s]

[I 2026-07-05 15:25:29,367] Trial 728 finished with value: 0.9493766289561089 and parameters: {'weight_class_0': 0.028449985966818112, 'weight_class_1': 0.4125994841347033, 'weight_class_2': 0.4385763600828842}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:29,378] Trial 729 finished with value: 0.9469965784856313 and parameters: {'weight_class_0': 0.010247954518142685, 'weight_class_1': 0.4022562390854672, 'weight_class_2': 0.47627446442581184}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:29,389] Trial 730 finished with value: 0.9469558636489469 and parameters: {'weight_class_0': 0.01052937709172713, 'weight_class_1': 0.41900219401446254, 'weight_class_2': 0.4889757244711504}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:29,440] Trial 731 finished with value: 0.9454690917901525 and parameters: {'weight_class_0': 0.007382575316005921, 'weight_class_1': 0.08511930488060526, 'weight_class_2': 0.47331015907888163}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:29,467] Trial 732 finished with value: 0.9455794383312591 and parameters: {'weight_class_0': 0.011288651469391226, 'weight_class_1': 0.06933159005905644, 'weight_class_2': 0.48531536381830287}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:29,482] Trial 733 finished with value: 0.9453505976611977 and parameters: {'weight_class_0': 0.01028183473428313, 'weight_class_1': 0.0896225720269734, 'weight_class_2': 0.6190186400259913}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:29,496] Trial 734 finished with value: 0.9452265684452127 and parameters: {'weight_class_0': 0.008107935743294513, 'weight_class_1': 0.08592292224040396, 'weight_class_2': 0.5261533770747239}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:29,520] Trial 736 finished with value: 0.9471266034120198 and parameters: {'weight_class_0': 0.01059677755470643, 'weight_class_1': 0.22803395572113613, 'weight_class_2': 0.4726984870035876}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:29,523] Trial 735 finished with value: 0.9458414816860113 and parameters: {'weight_class_0': 0.010057327687200994, 'weight_class_1': 0.07601865931414097, 'weight_class_2': 0.47748915272472314}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:29,534] Trial 737 finished with value: 0.9463992258668467 and parameters: {'weight_class_0': 0.00827127122304298, 'weight_class_1': 0.22767043062745757, 'weight_class_2': 0.4821448411802797}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  25%|█████████████████████████████████                                                                                                    | 747/3000 [00:15<00:48, 46.58it/s]

[I 2026-07-05 15:25:29,578] Trial 739 finished with value: 0.9006291428587702 and parameters: {'weight_class_0': 0.010636395515828354, 'weight_class_1': 0.21318148924685817, 'weight_class_2': 0.007273831449015817}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:29,580] Trial 738 finished with value: 0.9471438387813618 and parameters: {'weight_class_0': 0.011190293336063188, 'weight_class_1': 0.21861739321201554, 'weight_class_2': 0.475575146862504}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:29,625] Trial 740 finished with value: 0.9428756815357809 and parameters: {'weight_class_0': 0.007175993427027526, 'weight_class_1': 0.06742064659448534, 'weight_class_2': 0.020056841668547473}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:29,639] Trial 742 finished with value: 0.9266996065044855 and parameters: {'weight_class_0': 0.03964448154786319, 'weight_class_1': 0.06901672340277239, 'weight_class_2': 0.11314006443343579}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:29,660] Trial 741 finished with value: 0.9494224943364452 and parameters: {'weight_class_0': 0.007821506182634518, 'weight_class_1': 0.20923638520849788, 'weight_class_2': 0.10564024678687013}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:29,675] Trial 743 finished with value: 0.9193276100046001 and parameters: {'weight_class_0': 0.04311008720779425, 'weight_class_1': 0.2026081355115288, 'weight_class_2': 0.058121204452313405}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:29,707] Trial 744 finished with value: 0.9254543616777116 and parameters: {'weight_class_0': 0.03919989629905297, 'weight_class_1': 0.23202156418650588, 'weight_class_2': 0.06035048066731001}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:29,744] Trial 745 finished with value: 0.9473061440183862 and parameters: {'weight_class_0': 0.02316952347713292, 'weight_class_1': 0.21415050307690703, 'weight_class_2': 0.09928371966740965}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:29,749] Trial 746 finished with value: 0.9426903709333109 and parameters: {'weight_class_0': 0.03934106043493, 'weight_class_1': 0.23027324194921314, 'weight_class_2': 0.1146550075252654}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:29,765] Trial 747 finished with value: 0.9418602330559329 and parameters: {'weight_class_0': 0.040426655443334694, 'weight_class_1': 1.165291576088644, 'weight_class_2': 0.10783513576077632}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  25%|█████████████████████████████████▌                                                                                                   | 757/3000 [00:15<00:49, 44.98it/s]

[I 2026-07-05 15:25:29,812] Trial 748 finished with value: 0.9346848973815912 and parameters: {'weight_class_0': 0.040519211460073416, 'weight_class_1': 0.11216769371315322, 'weight_class_2': 0.10622231252901612}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:29,821] Trial 749 finished with value: 0.9197613609006554 and parameters: {'weight_class_0': 0.04236588218854315, 'weight_class_1': 0.5159474471265062, 'weight_class_2': 0.05479710832772375}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:29,846] Trial 750 finished with value: 0.9482483924273867 and parameters: {'weight_class_0': 0.017136441704091985, 'weight_class_1': 0.5226519331779462, 'weight_class_2': 0.09889885432875822}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:29,852] Trial 751 finished with value: 0.9162732701375754 and parameters: {'weight_class_0': 0.08530705029194378, 'weight_class_1': 0.6354446128167477, 'weight_class_2': 0.10149861791698628}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:29,872] Trial 752 finished with value: 0.9100061870320685 and parameters: {'weight_class_0': 0.0617361149415171, 'weight_class_1': 0.6636095124965397, 'weight_class_2': 0.061771767094388086}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:29,904] Trial 753 finished with value: 0.8958197630677782 and parameters: {'weight_class_0': 0.06336680488944367, 'weight_class_1': 0.030310200441075283, 'weight_class_2': 0.22012276111333456}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:29,922] Trial 754 finished with value: 0.9472930227114137 and parameters: {'weight_class_0': 0.016794362558340402, 'weight_class_1': 0.34558828073469716, 'weight_class_2': 0.07251785995779372}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:29,929] Trial 755 finished with value: 0.948397627912143 and parameters: {'weight_class_0': 0.016805033221353106, 'weight_class_1': 0.11973429565442785, 'weight_class_2': 0.1002337189396303}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:29,960] Trial 756 finished with value: 0.9465661455560817 and parameters: {'weight_class_0': 0.017565808869848494, 'weight_class_1': 0.11146317805718989, 'weight_class_2': 0.07391954492425412}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:29,972] Trial 757 finished with value: 0.9491241879143991 and parameters: {'weight_class_0': 0.01691943353715922, 'weight_class_1': 0.1194573755781848, 'weight_class_2': 0.1508195235770077}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  26%|██████████████████████████████████                                                                                                   | 767/3000 [00:15<00:49, 45.41it/s]

[I 2026-07-05 15:25:29,995] Trial 758 finished with value: 0.9314228855365555 and parameters: {'weight_class_0': 0.08318758324338585, 'weight_class_1': 0.6484047635922997, 'weight_class_2': 0.15042087842133228}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:30,004] Trial 759 finished with value: 0.9467023617757196 and parameters: {'weight_class_0': 0.01793857804921986, 'weight_class_1': 0.532616147005631, 'weight_class_2': 0.07330403747201147}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:30,048] Trial 760 finished with value: 0.9066416122222868 and parameters: {'weight_class_0': 0.08238007414791639, 'weight_class_1': 0.6211179903359088, 'weight_class_2': 0.07501370472468431}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:30,079] Trial 761 finished with value: 0.8450529236922965 and parameters: {'weight_class_0': 0.001232512038149892, 'weight_class_1': 0.3506635327489627, 'weight_class_2': 0.21879966569993267}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:30,100] Trial 762 finished with value: 0.9383723270031368 and parameters: {'weight_class_0': 0.003213972002419536, 'weight_class_1': 0.3498947574989087, 'weight_class_2': 0.07225576259195302}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:30,117] Trial 763 finished with value: 0.9470630102352464 and parameters: {'weight_class_0': 0.01820651149910921, 'weight_class_1': 0.32157682839933427, 'weight_class_2': 0.07508091846773275}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:30,142] Trial 764 finished with value: 0.9371937969341348 and parameters: {'weight_class_0': 0.003192939848259409, 'weight_class_1': 0.3523894243415657, 'weight_class_2': 0.14887862090738732}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:30,181] Trial 765 finished with value: 0.935656493427845 and parameters: {'weight_class_0': 0.0032970413486092965, 'weight_class_1': 0.3499243264080838, 'weight_class_2': 0.30421260657729515}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:30,191] Trial 766 finished with value: 0.9484975917558662 and parameters: {'weight_class_0': 0.024762855009301234, 'weight_class_1': 0.3491228290435669, 'weight_class_2': 0.13692345746528697}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:30,204] Trial 767 finished with value: 0.9497620954475968 and parameters: {'weight_class_0': 0.026281746908206623, 'weight_class_1': 0.3518407851261414, 'weight_class_2': 0.2960502185926323}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  26%|██████████████████████████████████▍                                                                                                  | 777/3000 [00:15<00:49, 45.11it/s]

[I 2026-07-05 15:25:30,234] Trial 768 finished with value: 0.9448385359709528 and parameters: {'weight_class_0': 0.0050305006032779105, 'weight_class_1': 0.3492101801233259, 'weight_class_2': 0.22107893058502712}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:30,251] Trial 769 finished with value: 0.9497233595725593 and parameters: {'weight_class_0': 0.025098249563709863, 'weight_class_1': 0.33586310435053507, 'weight_class_2': 0.2960129388671072}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:30,284] Trial 770 finished with value: 0.9464443455285118 and parameters: {'weight_class_0': 0.0048903001573049705, 'weight_class_1': 0.16360865519856474, 'weight_class_2': 0.28310301247002917}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:30,294] Trial 771 finished with value: 0.9488224607251058 and parameters: {'weight_class_0': 0.025119301142973758, 'weight_class_1': 0.16402324684221026, 'weight_class_2': 0.2288827055993314}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:30,332] Trial 772 finished with value: 0.9485521276238971 and parameters: {'weight_class_0': 0.025610285519698815, 'weight_class_1': 0.15719291122318216, 'weight_class_2': 0.2973899312957527}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:30,365] Trial 773 finished with value: 0.9484613441997598 and parameters: {'weight_class_0': 0.025841955811863455, 'weight_class_1': 0.14838603915457793, 'weight_class_2': 0.23623128312278074}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:30,381] Trial 774 finished with value: 0.9497783220324928 and parameters: {'weight_class_0': 0.02523219825760254, 'weight_class_1': 0.4946445358735611, 'weight_class_2': 0.29572893159593794}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:30,382] Trial 775 finished with value: 0.9483929701423298 and parameters: {'weight_class_0': 0.023627212603943064, 'weight_class_1': 1.0606370963177625, 'weight_class_2': 0.23577533821963434}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:30,424] Trial 776 finished with value: 0.948962166011166 and parameters: {'weight_class_0': 0.025912976470858582, 'weight_class_1': 0.1819602827386559, 'weight_class_2': 0.3013243036319383}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:30,443] Trial 777 finished with value: 0.9496899149452007 and parameters: {'weight_class_0': 0.02316857364991231, 'weight_class_1': 0.42850970359378876, 'weight_class_2': 0.29542079503589364}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  26%|██████████████████████████████████▉                                                                                                  | 787/3000 [00:16<00:49, 44.92it/s]

[I 2026-07-05 15:25:30,465] Trial 778 finished with value: 0.9497942459660115 and parameters: {'weight_class_0': 0.025172951371330313, 'weight_class_1': 0.5053371833618474, 'weight_class_2': 0.2798972293060271}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:30,477] Trial 779 finished with value: 0.9496701245015046 and parameters: {'weight_class_0': 0.025386258684776942, 'weight_class_1': 0.4854894492031886, 'weight_class_2': 0.2628666453211417}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:30,514] Trial 780 finished with value: 0.9139234426469267 and parameters: {'weight_class_0': 0.0241178508077111, 'weight_class_1': 0.021821279611003806, 'weight_class_2': 0.31272401331516386}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:30,518] Trial 781 finished with value: 0.9162300461131355 and parameters: {'weight_class_0': 0.021907479079598845, 'weight_class_1': 0.021653630697914907, 'weight_class_2': 0.30564974739169865}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:30,540] Trial 782 finished with value: 0.8913626182620721 and parameters: {'weight_class_0': 0.002291950739461386, 'weight_class_1': 0.471906516493191, 'weight_class_2': 0.31040966883152965}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:30,565] Trial 784 finished with value: 0.9336923678612455 and parameters: {'weight_class_0': 0.0021303579960498084, 'weight_class_1': 0.02217055942281255, 'weight_class_2': 0.311673618136792}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:30,604] Trial 783 finished with value: 0.9495701217088345 and parameters: {'weight_class_0': 0.022144588496597443, 'weight_class_1': 0.42336091067095216, 'weight_class_2': 0.30861081315186994}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:30,624] Trial 786 finished with value: 0.9498042142485571 and parameters: {'weight_class_0': 0.02852881652217717, 'weight_class_1': 0.48150247636060517, 'weight_class_2': 0.31910287579962937}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:30,641] Trial 785 finished with value: 0.9498180905751658 and parameters: {'weight_class_0': 0.028348624110018802, 'weight_class_1': 0.47961664612363203, 'weight_class_2': 0.3302936398974133}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:30,656] Trial 787 finished with value: 0.9493993452486363 and parameters: {'weight_class_0': 0.020503791640633286, 'weight_class_1': 0.5007355555840814, 'weight_class_2': 0.2954781269436867}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  27%|███████████████████████████████████▍                                                                                                 | 798/3000 [00:16<00:47, 46.37it/s]

[I 2026-07-05 15:25:30,711] Trial 788 finished with value: 0.9496659313592826 and parameters: {'weight_class_0': 0.020620397280511262, 'weight_class_1': 0.4892068845521677, 'weight_class_2': 0.25034314765979915}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:30,716] Trial 789 finished with value: 0.9496604509472188 and parameters: {'weight_class_0': 0.020824968151809647, 'weight_class_1': 0.4862149320014075, 'weight_class_2': 0.2571856069425472}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:30,722] Trial 790 finished with value: 0.9495246951932299 and parameters: {'weight_class_0': 0.020861400130929447, 'weight_class_1': 0.49790769348357417, 'weight_class_2': 0.20943505681215221}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:30,739] Trial 791 finished with value: 0.9496249193836716 and parameters: {'weight_class_0': 0.021229327874519085, 'weight_class_1': 0.4554090905419569, 'weight_class_2': 0.20747608989459726}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:30,765] Trial 792 finished with value: 0.9495971056743203 and parameters: {'weight_class_0': 0.029311095166354904, 'weight_class_1': 0.4898758872521244, 'weight_class_2': 0.24507898117827326}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:30,798] Trial 794 finished with value: 0.9495838665165527 and parameters: {'weight_class_0': 0.01984144541877104, 'weight_class_1': 0.46374377343872347, 'weight_class_2': 0.20444072152038031}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:30,806] Trial 793 finished with value: 0.9494367591325803 and parameters: {'weight_class_0': 0.020788760440900535, 'weight_class_1': 0.5481606207931516, 'weight_class_2': 0.20778240142441265}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:30,832] Trial 795 finished with value: 0.9494090546931018 and parameters: {'weight_class_0': 0.02026913979580357, 'weight_class_1': 0.557051511834512, 'weight_class_2': 0.19733876778453563}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:30,860] Trial 796 finished with value: 0.9494519195239843 and parameters: {'weight_class_0': 0.02806249305421161, 'weight_class_1': 0.5340121157387604, 'weight_class_2': 0.2260828711943906}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:30,863] Trial 797 finished with value: 0.8871385484798878 and parameters: {'weight_class_0': 0.029907142202841207, 'weight_class_1': 0.525610288607581, 'weight_class_2': 0.0036911575616933724}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:30,899] Trial 798 finished with value: 0.9496344403456302 and parameters: {'weight_class_0': 0.030753188616452175, 'weight_class_1': 0.5579974574606551, 'weight_class_2': 0.4147911947085239}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  27%|███████████████████████████████████▊                                                                                                 | 808/3000 [00:16<00:48, 45.44it/s]

[I 2026-07-05 15:25:30,933] Trial 799 finished with value: 0.9497258543769798 and parameters: {'weight_class_0': 0.03255514238420589, 'weight_class_1': 0.5172180536291274, 'weight_class_2': 0.405527705168853}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:30,953] Trial 800 finished with value: 0.8884770138045104 and parameters: {'weight_class_0': 0.02927202912708286, 'weight_class_1': 0.5793463091892618, 'weight_class_2': 0.004354245286313786}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:30,986] Trial 801 finished with value: 0.9495217043405005 and parameters: {'weight_class_0': 0.02989510993385595, 'weight_class_1': 0.6421039455403664, 'weight_class_2': 0.40965091105454277}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:30,993] Trial 802 finished with value: 0.9497537222931919 and parameters: {'weight_class_0': 0.0321316900034593, 'weight_class_1': 0.5692107528192067, 'weight_class_2': 0.39412515913259905}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:31,032] Trial 804 finished with value: 0.8889389596898049 and parameters: {'weight_class_0': 0.03128886403376323, 'weight_class_1': 0.60644760180164, 'weight_class_2': 0.004776721468396346}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:31,043] Trial 803 finished with value: 0.9497949826385158 and parameters: {'weight_class_0': 0.035280264862730754, 'weight_class_1': 0.644513412415397, 'weight_class_2': 0.4106452387905737}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:31,050] Trial 805 finished with value: 0.9496889402111695 and parameters: {'weight_class_0': 0.031938103264490605, 'weight_class_1': 0.6353067702838049, 'weight_class_2': 0.3999273968163485}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:31,068] Trial 806 finished with value: 0.9494916091054945 and parameters: {'weight_class_0': 0.029080874236400513, 'weight_class_1': 0.7028324341660936, 'weight_class_2': 0.39297951472547377}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:31,078] Trial 807 finished with value: 0.9495790912351895 and parameters: {'weight_class_0': 0.030100143103036704, 'weight_class_1': 0.6583108332619657, 'weight_class_2': 0.3992602299835532}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:31,112] Trial 808 finished with value: 0.9497755659590453 and parameters: {'weight_class_0': 0.03498525982611791, 'weight_class_1': 0.7787115136101725, 'weight_class_2': 0.40102404168861516}. Best is trial 433 with value: 0.9498304662349432.

[I 2026-07-05 15:25:31,165] Trial 809 finished with value: 0.9491996780841715 and parameters: {'weight_class_0': 0.0354281066533043, 'weight_class_1': 0.664371555824507, 'weight_class_2': 0.6538311287006544}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:31,167] Trial 810 finished with value: 0.9496622048745816 and parameters: {'weight_class_0': 0.03634225402869457, 'weight_class_1': 0.7614787659223102, 'weight_class_2': 0.37282946578589576}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:31,181] Trial 811 finished with value: 0.9490832972778875 and parameters: {'weight_class_0': 0.0394528090300682, 'weight_class_1': 0.3945047378311227, 'weight_class_2': 0.5950582475767079}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:31,198] Trial 812 finished with value: 0.9496837871714728 and parameters: {'weight_class_0': 0.04166467185249544, 'weight_class_1': 0.6883561560134289, 'weight_class_2': 0.3986446352973606}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:31,232] Trial 813 finished with value: 0.9491111971678355 and parameters: {'weight_class_0': 0.037724192227674286, 'weight_class_1': 0.4055732350715226, 'weight_class_2': 0.5757579687275586}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:31,246] Trial 814 finished with value: 0.9495798496552946 and parameters: {'weight_class_0': 0.04517568915727254, 'weight_class_1': 0.7914041025246408, 'weight_class_2': 0.621910735038156}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:31,276] Trial 815 finished with value: 0.9495731362497352 and parameters: {'weight_class_0': 0.038249902753720796, 'weight_class_1': 0.3775364815163299, 'weight_class_2': 0.35245110594094325}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:31,282] Trial 816 finished with value: 0.9495458859931482 and parameters: {'weight_class_0': 0.03867784488087603, 'weight_class_1': 0.7647427250533285, 'weight_class_2': 0.5477046478574371}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:31,290] Trial 817 finished with value: 0.9489078066411993 and parameters: {'weight_class_0': 0.03843584011728978, 'weight_class_1': 0.38959867433597867, 'weight_class_2': 0.6275344942256359}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:31,307] Trial 818 finished with value: 0.9495014294645788 and parameters: {'weight_class_0': 0.04036885451518068, 'weight_class_1': 0.8686410119855391, 'weight_class_2': 0.34438716774349226}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:31,354] Trial 820 finished with value: 0.9493485967167175 and parameters: {'weight_class_0': 0.04454231866238722, 'weight_class_1': 0.7960032928806623, 'weight_class_2': 0.3438648429509044}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  28%|████████████████████████████████████▋                                                                                                | 828/3000 [00:17<00:47, 45.94it/s]

[I 2026-07-05 15:25:31,362] Trial 819 finished with value: 0.9495959395992902 and parameters: {'weight_class_0': 0.03919513633030532, 'weight_class_1': 0.7164841238178961, 'weight_class_2': 0.3378591908139061}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:31,418] Trial 822 finished with value: 0.9492234081591467 and parameters: {'weight_class_0': 0.04617881878840099, 'weight_class_1': 0.964450344818687, 'weight_class_2': 0.3413900940429749}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:31,423] Trial 821 finished with value: 0.9495021606786898 and parameters: {'weight_class_0': 0.041154985654318015, 'weight_class_1': 0.8738410646158455, 'weight_class_2': 0.5751925351364123}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:31,435] Trial 823 finished with value: 0.9491040012079792 and parameters: {'weight_class_0': 0.04710675062513046, 'weight_class_1': 0.9080351864439997, 'weight_class_2': 0.3336282042794579}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:31,488] Trial 824 finished with value: 0.9492600170211473 and parameters: {'weight_class_0': 0.04720204906370386, 'weight_class_1': 0.8114177145807753, 'weight_class_2': 0.3437470496842461}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:31,491] Trial 825 finished with value: 0.9481643167823316 and parameters: {'weight_class_0': 0.04637095335461247, 'weight_class_1': 0.39101963109614973, 'weight_class_2': 0.9136306484277431}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:31,511] Trial 826 finished with value: 0.9487642267177766 and parameters: {'weight_class_0': 0.05813467937226892, 'weight_class_1': 0.7974102864573387, 'weight_class_2': 0.3467663969210311}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:31,537] Trial 828 finished with value: 0.9494936066511874 and parameters: {'weight_class_0': 0.057045072427166346, 'weight_class_1': 0.988286755247756, 'weight_class_2': 0.8767061676756108}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:31,549] Trial 827 finished with value: 0.8819766227441344 and parameters: {'weight_class_0': 0.05485233035653273, 'weight_class_1': 0.008942781389151786, 'weight_class_2': 0.33388463813091185}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  28%|█████████████████████████████████████▏                                                                                               | 838/3000 [00:17<00:48, 44.74it/s]

[I 2026-07-05 15:25:31,570] Trial 829 finished with value: 0.949664356834948 and parameters: {'weight_class_0': 0.05324064281195848, 'weight_class_1': 0.8108902110870734, 'weight_class_2': 0.4790913174558876}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:31,602] Trial 830 finished with value: 0.949371736051349 and parameters: {'weight_class_0': 0.05877298904008579, 'weight_class_1': 0.9884384262774241, 'weight_class_2': 0.4485379587824661}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:31,615] Trial 831 finished with value: 0.949467759189483 and parameters: {'weight_class_0': 0.05749900775826324, 'weight_class_1': 1.1710118325098318, 'weight_class_2': 0.8677563992001508}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:31,645] Trial 832 finished with value: 0.9494467869573034 and parameters: {'weight_class_0': 0.05316276661264119, 'weight_class_1': 1.1698005875449897, 'weight_class_2': 0.44657467784683375}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:31,662] Trial 833 finished with value: 0.9487054577617419 and parameters: {'weight_class_0': 0.05460012351943669, 'weight_class_1': 0.428372817957956, 'weight_class_2': 0.7874725104635446}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:31,678] Trial 834 finished with value: 0.8385389408972791 and parameters: {'weight_class_0': 0.061309439160797945, 'weight_class_1': 0.0022949647991868556, 'weight_class_2': 0.7910814513789861}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:31,704] Trial 835 finished with value: 0.948474100267442 and parameters: {'weight_class_0': 0.056973541831678874, 'weight_class_1': 0.44860052666905326, 'weight_class_2': 0.9352889040621918}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:31,741] Trial 836 finished with value: 0.9488419081313157 and parameters: {'weight_class_0': 0.02852990652462163, 'weight_class_1': 1.0405917693235862, 'weight_class_2': 0.45508503569546693}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:31,751] Trial 837 finished with value: 0.9475494124376892 and parameters: {'weight_class_0': 0.026720114806266043, 'weight_class_1': 1.5160246946063785, 'weight_class_2': 0.2560548838153362}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:31,775] Trial 838 finished with value: 0.948426372089146 and parameters: {'weight_class_0': 0.02656077872682889, 'weight_class_1': 1.1745199298085705, 'weight_class_2': 0.26611141086982265}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  28%|█████████████████████████████████████▌                                                                                               | 847/3000 [00:17<00:48, 44.11it/s]

[I 2026-07-05 15:25:31,798] Trial 839 finished with value: 0.9458566423584666 and parameters: {'weight_class_0': 0.023534600696194258, 'weight_class_1': 1.7329259545620308, 'weight_class_2': 0.263918433201576}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:31,825] Trial 840 finished with value: 0.8786159256887695 and parameters: {'weight_class_0': 0.026876705223311297, 'weight_class_1': 1.2695760134597724, 'weight_class_2': 0.0055941211141980855}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:31,833] Trial 841 finished with value: 0.8927352680596817 and parameters: {'weight_class_0': 0.025990837164390854, 'weight_class_1': 0.4354902048691906, 'weight_class_2': 0.006236341569385465}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:31,888] Trial 842 finished with value: 0.8755343562238593 and parameters: {'weight_class_0': 0.02693007835554815, 'weight_class_1': 0.0024317483813624916, 'weight_class_2': 0.28160895267388997}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:31,901] Trial 843 finished with value: 0.8583457960986255 and parameters: {'weight_class_0': 0.02876577971070503, 'weight_class_1': 1.4683022587283696, 'weight_class_2': 9.840162223496655}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:31,917] Trial 844 finished with value: 0.8884096842451122 and parameters: {'weight_class_0': 0.02527277743345654, 'weight_class_1': 5.618622024594621, 'weight_class_2': 0.25706890176013114}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:31,951] Trial 845 finished with value: 0.9471544241285574 and parameters: {'weight_class_0': 0.02692193351502784, 'weight_class_1': 1.6369300438290044, 'weight_class_2': 0.2709921582228047}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:31,980] Trial 847 finished with value: 0.9496527722065373 and parameters: {'weight_class_0': 0.026018296649230478, 'weight_class_1': 0.311097276865422, 'weight_class_2': 0.2813530498127086}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:31,986] Trial 846 finished with value: 0.9496576483332385 and parameters: {'weight_class_0': 0.02793344547631589, 'weight_class_1': 0.3622980508819159, 'weight_class_2': 0.272876527904482}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  29%|█████████████████████████████████████▉                                                                                               | 856/3000 [00:17<00:48, 44.08it/s]

[I 2026-07-05 15:25:31,987] Trial 848 finished with value: 0.8931659396564368 and parameters: {'weight_class_0': 0.0250181187671233, 'weight_class_1': 0.32494927210220814, 'weight_class_2': 0.006124941831937435}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:32,053] Trial 849 finished with value: 0.949666135751131 and parameters: {'weight_class_0': 0.02689874368935812, 'weight_class_1': 0.3133796829643884, 'weight_class_2': 0.290992826589443}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:32,055] Trial 850 finished with value: 0.9496429376682358 and parameters: {'weight_class_0': 0.02646085902033987, 'weight_class_1': 0.31337411367910567, 'weight_class_2': 0.27925688463487836}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:32,069] Trial 851 finished with value: 0.8065560852746629 and parameters: {'weight_class_0': 7.825609753673267, 'weight_class_1': 0.32365176216530994, 'weight_class_2': 0.27800721413400453}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:32,112] Trial 853 finished with value: 0.9494714039601869 and parameters: {'weight_class_0': 0.017635531057227812, 'weight_class_1': 0.31816886456308685, 'weight_class_2': 0.2782751112143925}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:32,123] Trial 852 finished with value: 0.9497009564374744 and parameters: {'weight_class_0': 0.023817678018304738, 'weight_class_1': 0.3164073455708871, 'weight_class_2': 0.2830617688146303}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:32,154] Trial 854 finished with value: 0.9006862178884862 and parameters: {'weight_class_0': 0.016843237115387644, 'weight_class_1': 0.32957085224336236, 'weight_class_2': 0.01156455015441861}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:32,192] Trial 856 finished with value: 0.9479340036436922 and parameters: {'weight_class_0': 0.01756283944863997, 'weight_class_1': 0.3211690403626127, 'weight_class_2': 0.5527744645052075}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:32,208] Trial 855 finished with value: 0.948406444941719 and parameters: {'weight_class_0': 0.0169581202024365, 'weight_class_1': 0.30270078462824274, 'weight_class_2': 0.4401483511550068}. Best is trial 433 with value: 0.9498304662349432.

[I 2026-07-05 15:25:32,212] Trial 857 finished with value: 0.9484507245643647 and parameters: {'weight_class_0': 0.018306416104284653, 'weight_class_1': 0.5099793418995511, 'weight_class_2': 0.46206130159159964}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:32,232] Trial 858 finished with value: 0.9481342107681727 and parameters: {'weight_class_0': 0.017917046827686658, 'weight_class_1': 0.5034236308347029, 'weight_class_2': 0.5523976739784392}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:32,251] Trial 859 finished with value: 0.9482291021534425 and parameters: {'weight_class_0': 0.01909215578923227, 'weight_class_1': 0.5029142975230098, 'weight_class_2': 0.5666089252898121}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:32,273] Trial 860 finished with value: 0.9485436090209255 and parameters: {'weight_class_0': 0.018393176094297952, 'weight_class_1': 0.5535253823025488, 'weight_class_2': 0.43584329319882154}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:32,286] Trial 861 finished with value: 0.9481280846111977 and parameters: {'weight_class_0': 0.01787086038205918, 'weight_class_1': 0.5121201215769594, 'weight_class_2': 0.5468662447649619}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:32,292] Trial 862 finished with value: 0.7041838266757193 and parameters: {'weight_class_0': 0.0010262286025882561, 'weight_class_1': 0.5027709682036025, 'weight_class_2': 0.5371890142364493}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:32,351] Trial 863 finished with value: 0.9493752112986056 and parameters: {'weight_class_0': 0.03511023411463205, 'weight_class_1': 0.5139152901770292, 'weight_class_2': 0.547007645335043}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:32,368] Trial 864 finished with value: 0.9484892101445465 and parameters: {'weight_class_0': 0.017423302689249194, 'weight_class_1': 0.49487119252600226, 'weight_class_2': 0.4340398149483416}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:32,398] Trial 866 finished with value: 0.9497584343958646 and parameters: {'weight_class_0': 0.034702430974443345, 'weight_class_1': 0.5362764496604063, 'weight_class_2': 0.4174087159783473}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:32,435] Trial 867 finished with value: 0.9489385842323981 and parameters: {'weight_class_0': 0.03412815826871088, 'weight_class_1': 0.6282992004261099, 'weight_class_2': 0.2234468572273841}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  29%|██████████████████████████████████████▊                                                                                              | 875/3000 [00:18<00:48, 43.79it/s]

[I 2026-07-05 15:25:32,437] Trial 865 finished with value: 0.9497216727972492 and parameters: {'weight_class_0': 0.03627331023314844, 'weight_class_1': 0.5382210564631569, 'weight_class_2': 0.43941449615776473}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:32,446] Trial 868 finished with value: 0.945335707305246 and parameters: {'weight_class_0': 0.032090910592862724, 'weight_class_1': 2.267278936063101, 'weight_class_2': 0.21356361090121853}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:32,502] Trial 869 finished with value: 0.8798840727165947 and parameters: {'weight_class_0': 0.03391041426336228, 'weight_class_1': 0.004270607734418477, 'weight_class_2': 0.23007394400694217}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:32,508] Trial 871 finished with value: 0.9487709380003136 and parameters: {'weight_class_0': 0.03537804016928961, 'weight_class_1': 0.6610304164056269, 'weight_class_2': 0.2127259060092175}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:32,519] Trial 870 finished with value: 0.9489584490678604 and parameters: {'weight_class_0': 0.03540469148072852, 'weight_class_1': 0.6674040132536675, 'weight_class_2': 0.2291749514675653}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:32,559] Trial 872 finished with value: 0.8553469837110536 and parameters: {'weight_class_0': 0.8391466139857707, 'weight_class_1': 0.6757508383122341, 'weight_class_2': 0.22944847153641604}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:32,573] Trial 873 finished with value: 0.9489371060250305 and parameters: {'weight_class_0': 0.03392537270675211, 'weight_class_1': 0.646601622161689, 'weight_class_2': 0.21604824758255503}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:32,605] Trial 874 finished with value: 0.9488011834584715 and parameters: {'weight_class_0': 0.035973438645352004, 'weight_class_1': 0.6606622749397452, 'weight_class_2': 0.2182708902815074}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:32,651] Trial 875 finished with value: 0.9489596088206329 and parameters: {'weight_class_0': 0.03431244856656684, 'weight_class_1': 0.6481936850068315, 'weight_class_2': 0.22298120791353335}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  30%|███████████████████████████████████████▏                                                                                             | 885/3000 [00:18<00:47, 44.64it/s]

[I 2026-07-05 15:25:32,657] Trial 876 finished with value: 0.948851272374652 and parameters: {'weight_class_0': 0.03227802238781591, 'weight_class_1': 0.6894500220447445, 'weight_class_2': 0.20992318294534887}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:32,668] Trial 877 finished with value: 0.9493861589024633 and parameters: {'weight_class_0': 0.02163978090618897, 'weight_class_1': 0.3909301860120847, 'weight_class_2': 0.3507419641085739}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:32,692] Trial 878 finished with value: 0.9465099784862193 and parameters: {'weight_class_0': 0.07526832961618773, 'weight_class_1': 0.4030551543273912, 'weight_class_2': 0.33639368749162957}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:32,707] Trial 879 finished with value: 0.8441984672028534 and parameters: {'weight_class_0': 0.910314968097271, 'weight_class_1': 0.3992636373141311, 'weight_class_2': 0.3469107252257801}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:32,738] Trial 880 finished with value: 0.9071225723078941 and parameters: {'weight_class_0': 0.023165936575312556, 'weight_class_1': 0.015873116937258614, 'weight_class_2': 0.3878258076039867}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:32,743] Trial 881 finished with value: 0.9464062656211324 and parameters: {'weight_class_0': 0.07721711675539111, 'weight_class_1': 0.37997456536956814, 'weight_class_2': 0.3647682622181532}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:32,778] Trial 882 finished with value: 0.9494264163077887 and parameters: {'weight_class_0': 0.021052797266675295, 'weight_class_1': 0.3999380002788768, 'weight_class_2': 0.3392102773291833}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:32,810] Trial 883 finished with value: 0.9029956110861249 and parameters: {'weight_class_0': 0.022886098613206157, 'weight_class_1': 0.41581007904069445, 'weight_class_2': 0.017837845043779416}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:32,831] Trial 884 finished with value: 0.9494041624783994 and parameters: {'weight_class_0': 0.02071031959761043, 'weight_class_1': 0.39623058761794466, 'weight_class_2': 0.336339013491804}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:32,844] Trial 885 finished with value: 0.8837582834468773 and parameters: {'weight_class_0': 0.021334673554084367, 'weight_class_1': 0.40275947154553454, 'weight_class_2': 0.0022576458383234558}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  30%|███████████████████████████████████████▋                                                                                             | 894/3000 [00:18<00:51, 40.82it/s]

[I 2026-07-05 15:25:32,888] Trial 886 finished with value: 0.9495130524540812 and parameters: {'weight_class_0': 0.023384363448441227, 'weight_class_1': 0.3886059322951998, 'weight_class_2': 0.3348724899351615}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:32,903] Trial 887 finished with value: 0.9494718458634059 and parameters: {'weight_class_0': 0.02202962113402078, 'weight_class_1': 0.3939411787397211, 'weight_class_2': 0.3456368976584943}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:32,951] Trial 888 finished with value: 0.9479281682826403 and parameters: {'weight_class_0': 0.022280770696502996, 'weight_class_1': 0.4328081015853951, 'weight_class_2': 0.7117439302358487}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:32,975] Trial 889 finished with value: 0.9270233710259483 and parameters: {'weight_class_0': 0.02153213728960786, 'weight_class_1': 3.053581633203715, 'weight_class_2': 1.0916234550251358}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:32,993] Trial 890 finished with value: 0.9492831209795823 and parameters: {'weight_class_0': 0.022263357260346173, 'weight_class_1': 0.2520253715832514, 'weight_class_2': 0.16858489272836905}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:33,009] Trial 892 finished with value: 0.9475649604239907 and parameters: {'weight_class_0': 0.022537267203175674, 'weight_class_1': 0.27043886242275267, 'weight_class_2': 0.680715499644009}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:33,013] Trial 891 finished with value: 0.8798874512886665 and parameters: {'weight_class_0': 0.022507706698940137, 'weight_class_1': 0.4518424135310695, 'weight_class_2': 0.0021478397308619676}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:33,066] Trial 893 finished with value: 0.9468137246048952 and parameters: {'weight_class_0': 0.02197959983656639, 'weight_class_1': 0.4434249655983897, 'weight_class_2': 1.0980012067093352}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:33,083] Trial 894 finished with value: 0.946327234128224 and parameters: {'weight_class_0': 0.022927407327907223, 'weight_class_1': 0.2727298385550615, 'weight_class_2': 1.117692680392639}. Best is trial 433 with value: 0.9498304662349432.

[I 2026-07-05 15:25:33,111] Trial 895 finished with value: 0.946821617126164 and parameters: {'weight_class_0': 0.04335941851727929, 'weight_class_1': 0.2693669349413846, 'weight_class_2': 1.0954458281643813}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:33,129] Trial 897 finished with value: 0.9455179330858555 and parameters: {'weight_class_0': 0.01406912515130184, 'weight_class_1': 0.8619252715826226, 'weight_class_2': 0.6806834191399458}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:33,154] Trial 896 finished with value: 0.8156461519176249 and parameters: {'weight_class_0': 4.563054925989197, 'weight_class_1': 0.264819546232004, 'weight_class_2': 0.7055935881249225}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:33,211] Trial 898 finished with value: 0.9465632977141899 and parameters: {'weight_class_0': 0.042737765622683055, 'weight_class_1': 0.248404314520207, 'weight_class_2': 1.1425499726963197}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:33,237] Trial 899 finished with value: 0.9458046098644881 and parameters: {'weight_class_0': 0.045528177486264865, 'weight_class_1': 0.2799377070199106, 'weight_class_2': 0.1764484929215148}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:33,245] Trial 900 finished with value: 0.9275138177923425 and parameters: {'weight_class_0': 0.11456692281314702, 'weight_class_1': 0.8156451085528471, 'weight_class_2': 0.18542011206268}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:33,252] Trial 901 finished with value: 0.9123745098886568 and parameters: {'weight_class_0': 0.014237105870414392, 'weight_class_1': 0.012011753558895425, 'weight_class_2': 0.16896956382775488}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:33,300] Trial 902 finished with value: 0.7092087272751947 and parameters: {'weight_class_0': 0.0013205171768452633, 'weight_class_1': 0.8644134381288122, 'weight_class_2': 0.43550308871773585}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  30%|████████████████████████████████████████▍                                                                                            | 911/3000 [00:18<00:53, 39.00it/s]

[I 2026-07-05 15:25:33,326] Trial 903 finished with value: 0.9489410350020352 and parameters: {'weight_class_0': 0.04560801379322941, 'weight_class_1': 0.8241064937998044, 'weight_class_2': 0.29219411128020134}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:33,375] Trial 904 finished with value: 0.9248736693735738 and parameters: {'weight_class_0': 0.014542193540542855, 'weight_class_1': 0.8232083385121837, 'weight_class_2': 0.02344768914697142}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:33,405] Trial 906 finished with value: 0.6356640488751031 and parameters: {'weight_class_0': 2.499409433812395, 'weight_class_1': 0.013051302563517797, 'weight_class_2': 0.16825411812965155}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:33,407] Trial 905 finished with value: 0.9485088786700616 and parameters: {'weight_class_0': 0.028593688354726643, 'weight_class_1': 0.8628457363469497, 'weight_class_2': 0.1773749337543329}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:33,445] Trial 908 finished with value: 0.9042514648258182 and parameters: {'weight_class_0': 0.028124197428947638, 'weight_class_1': 0.812829790436066, 'weight_class_2': 0.023682190796429803}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:33,446] Trial 907 finished with value: 0.9484933450284155 and parameters: {'weight_class_0': 0.028592385982523914, 'weight_class_1': 0.8460787813389342, 'weight_class_2': 0.17403067649446544}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:33,476] Trial 909 finished with value: 0.9478076877202627 and parameters: {'weight_class_0': 0.015556700750594276, 'weight_class_1': 0.7579258084504223, 'weight_class_2': 0.2896062502937589}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:33,516] Trial 911 finished with value: 0.9019549781192889 and parameters: {'weight_class_0': 0.029161569454762924, 'weight_class_1': 0.588664149759837, 'weight_class_2': 0.02164424436914144}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:33,546] Trial 910 finished with value: 0.9494771538317592 and parameters: {'weight_class_0': 0.03027670873321225, 'weight_class_1': 0.5681647106628597, 'weight_class_2': 0.447268691063232}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  31%|████████████████████████████████████████▋                                                                                            | 919/3000 [00:19<00:52, 39.28it/s]

[I 2026-07-05 15:25:33,547] Trial 912 finished with value: 0.891744735255414 and parameters: {'weight_class_0': 0.028773688335228184, 'weight_class_1': 0.7993653464843181, 'weight_class_2': 0.0076511201628881725}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:33,565] Trial 913 finished with value: 0.9490192840622558 and parameters: {'weight_class_0': 0.028053933299702943, 'weight_class_1': 1.0097764274762908, 'weight_class_2': 0.307040307952876}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:33,584] Trial 914 finished with value: 0.9496968769748056 and parameters: {'weight_class_0': 0.028849236953228174, 'weight_class_1': 0.547916069105092, 'weight_class_2': 0.2912786527258611}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:33,645] Trial 915 finished with value: 0.9485699073292192 and parameters: {'weight_class_0': 0.014760107197045262, 'weight_class_1': 0.5895940853180054, 'weight_class_2': 0.2496858392689143}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:33,648] Trial 916 finished with value: 0.9496866898648709 and parameters: {'weight_class_0': 0.029826076646512895, 'weight_class_1': 0.5426759124045235, 'weight_class_2': 0.2968526091186571}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:33,692] Trial 917 finished with value: 0.9495419618987823 and parameters: {'weight_class_0': 0.028803200974777458, 'weight_class_1': 0.5892488356754617, 'weight_class_2': 0.24947223400119306}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:33,722] Trial 918 finished with value: 0.896581159495048 and parameters: {'weight_class_0': 0.030840634807907715, 'weight_class_1': 0.5860775249405898, 'weight_class_2': 0.014082709805272129}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:33,753] Trial 919 finished with value: 0.9495073385344596 and parameters: {'weight_class_0': 0.03043449397206906, 'weight_class_1': 0.5962240148695094, 'weight_class_2': 0.4576507966884042}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  31%|█████████████████████████████████████████                                                                                            | 927/3000 [00:19<00:54, 38.17it/s]

[I 2026-07-05 15:25:33,761] Trial 920 finished with value: 0.6861826637247845 and parameters: {'weight_class_0': 0.0018267683783845196, 'weight_class_1': 0.6145520874839286, 'weight_class_2': 1.6147994750534538}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:33,799] Trial 921 finished with value: 0.9487167809995743 and parameters: {'weight_class_0': 0.02961144882682478, 'weight_class_1': 1.1346089006610285, 'weight_class_2': 0.2543602382769395}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:33,811] Trial 922 finished with value: 0.9460039924829414 and parameters: {'weight_class_0': 0.06882133497761941, 'weight_class_1': 1.1189312380141994, 'weight_class_2': 0.2484744813734431}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:33,815] Trial 923 finished with value: 0.9489297953430968 and parameters: {'weight_class_0': 0.03828836623978972, 'weight_class_1': 0.35793980570418593, 'weight_class_2': 0.2487349012296143}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:33,895] Trial 925 finished with value: 0.9484786194264547 and parameters: {'weight_class_0': 0.045567061793955546, 'weight_class_1': 0.48456736602715145, 'weight_class_2': 0.24754252450112266}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:33,911] Trial 924 finished with value: 0.94591748681255 and parameters: {'weight_class_0': 0.062884619994374, 'weight_class_1': 0.35418752377442003, 'weight_class_2': 0.2508817215500589}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:33,915] Trial 926 finished with value: 0.9457096210622148 and parameters: {'weight_class_0': 0.07081905480895682, 'weight_class_1': 0.3317085373419269, 'weight_class_2': 1.9849166239615668}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:33,944] Trial 927 finished with value: 0.8759555324009988 and parameters: {'weight_class_0': 0.0018572526506346867, 'weight_class_1': 0.3497123043982244, 'weight_class_2': 0.40266627556516355}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  31%|█████████████████████████████████████████▌                                                                                           | 937/3000 [00:19<00:51, 39.80it/s]

[I 2026-07-05 15:25:33,971] Trial 928 finished with value: 0.948001462716387 and parameters: {'weight_class_0': 0.0669176681493217, 'weight_class_1': 0.36097414235146846, 'weight_class_2': 0.4751250352784503}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:33,995] Trial 929 finished with value: 0.8435042980504782 and parameters: {'weight_class_0': 0.0017144886769405864, 'weight_class_1': 0.3473122283651269, 'weight_class_2': 0.4900518282994773}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:34,027] Trial 930 finished with value: 0.9495616452395149 and parameters: {'weight_class_0': 0.03801775881749635, 'weight_class_1': 0.35431610413898745, 'weight_class_2': 0.38739484032860505}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:34,068] Trial 931 finished with value: 0.9449117640782863 and parameters: {'weight_class_0': 0.09751090265917135, 'weight_class_1': 0.36643532979393606, 'weight_class_2': 0.4939817950461063}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:34,077] Trial 933 finished with value: 0.9490018212536856 and parameters: {'weight_class_0': 0.06486770211402454, 'weight_class_1': 0.45152563648871435, 'weight_class_2': 0.519745423627224}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:34,084] Trial 932 finished with value: 0.9493431261224635 and parameters: {'weight_class_0': 0.04917826363320098, 'weight_class_1': 0.4598614389164683, 'weight_class_2': 0.3929781412848986}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:34,116] Trial 934 finished with value: 0.9495934951470583 and parameters: {'weight_class_0': 0.04310369963685308, 'weight_class_1': 0.474090708349435, 'weight_class_2': 0.39187853722911237}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:34,130] Trial 935 finished with value: 0.8535204831775055 and parameters: {'weight_class_0': 0.577759446063155, 'weight_class_1': 0.3279487417778958, 'weight_class_2': 0.3705583918822799}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:34,172] Trial 936 finished with value: 0.9464792855047427 and parameters: {'weight_class_0': 0.09816437709370963, 'weight_class_1': 0.4456617269575109, 'weight_class_2': 0.5211696459816806}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:34,198] Trial 937 finished with value: 0.9493814125543576 and parameters: {'weight_class_0': 0.03795072712473267, 'weight_class_1': 0.42244245448119366, 'weight_class_2': 0.5233093003350299}. Best is trial 433 with value: 0.9498304662349432.

[I 2026-07-05 15:25:34,214] Trial 938 finished with value: 0.9496122802116299 and parameters: {'weight_class_0': 0.03794037769228067, 'weight_class_1': 0.455018919332592, 'weight_class_2': 0.38158457953576874}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:34,258] Trial 939 finished with value: 0.9496616298800715 and parameters: {'weight_class_0': 0.03812191353700348, 'weight_class_1': 0.4626089164968178, 'weight_class_2': 0.3497938555635153}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:34,279] Trial 940 finished with value: 0.9496033046998665 and parameters: {'weight_class_0': 0.04953666113769493, 'weight_class_1': 0.4528674724807419, 'weight_class_2': 0.5539391607961089}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:34,295] Trial 941 finished with value: 0.9443139932687156 and parameters: {'weight_class_0': 0.10020121058966794, 'weight_class_1': 0.43429240095072963, 'weight_class_2': 0.3834723334175915}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:34,321] Trial 942 finished with value: 0.9487385654711403 and parameters: {'weight_class_0': 0.015389774150411607, 'weight_class_1': 0.23890076964790488, 'weight_class_2': 0.32568198985010866}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:34,349] Trial 943 finished with value: 0.9492412323841212 and parameters: {'weight_class_0': 0.01759198569320129, 'weight_class_1': 0.28487579948631436, 'weight_class_2': 0.31053814835682814}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:34,377] Trial 944 finished with value: 0.949241435616747 and parameters: {'weight_class_0': 0.018639194664378852, 'weight_class_1': 0.2479840437481868, 'weight_class_2': 0.3094947187368928}. Best is trial 433 with value: 0.9498304662349432.

[I 2026-07-05 15:25:34,400] Trial 945 finished with value: 0.8328668493724156 and parameters: {'weight_class_0': 0.01952118319972419, 'weight_class_1': 1.3515265134726588, 'weight_class_2': 0.003083765811885208}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:34,427] Trial 946 finished with value: 0.9491836545596201 and parameters: {'weight_class_0': 0.0185936134928317, 'weight_class_1': 0.268428685223337, 'weight_class_2': 0.33153977497449744}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:34,447] Trial 947 finished with value: 0.9490942358404307 and parameters: {'weight_class_0': 0.018786619026073363, 'weight_class_1': 0.24159102078263986, 'weight_class_2': 0.3205453244670817}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:34,469] Trial 948 finished with value: 0.9492147396171514 and parameters: {'weight_class_0': 0.01878434280888706, 'weight_class_1': 0.284481782603759, 'weight_class_2': 0.33179303090464757}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:34,489] Trial 949 finished with value: 0.9491745248228836 and parameters: {'weight_class_0': 0.018354722022721127, 'weight_class_1': 0.24981699398271617, 'weight_class_2': 0.3149491555638971}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:34,524] Trial 952 finished with value: 0.949260651885445 and parameters: {'weight_class_0': 0.018404698645385718, 'weight_class_1': 0.253606064337923, 'weight_class_2': 0.30944943328602165}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:34,528] Trial 951 finished with value: 0.9490768711113936 and parameters: {'weight_class_0': 0.017956395390171985, 'weight_class_1': 0.2419510473893034, 'weight_class_2': 0.3151801386327599}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:34,555] Trial 950 finished with value: 0.9495222353412528 and parameters: {'weight_class_0': 0.025746014069629647, 'weight_class_1': 0.6987509827762172, 'weight_class_2': 0.3157939735458757}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:34,603] Trial 953 finished with value: 0.9493993982865699 and parameters: {'weight_class_0': 0.01881184605959158, 'weight_class_1': 0.287706269584502, 'weight_class_2': 0.2981207769405701}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:34,610] Trial 955 finished with value: 0.9490795171969171 and parameters: {'weight_class_0': 0.02432329425985309, 'weight_class_1': 0.6785116184667638, 'weight_class_2': 0.19179721822362605}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  32%|██████████████████████████████████████████▋                                                                                          | 962/3000 [00:20<00:52, 38.60it/s]

[I 2026-07-05 15:25:34,623] Trial 954 finished with value: 0.8702179374055324 and parameters: {'weight_class_0': 0.024033560296849492, 'weight_class_1': 0.0014063943719614814, 'weight_class_2': 0.20339404942912978}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:34,666] Trial 956 finished with value: 0.9483074850361654 and parameters: {'weight_class_0': 0.024700019811602966, 'weight_class_1': 1.014830855905916, 'weight_class_2': 0.18913304370179573}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:34,674] Trial 957 finished with value: 0.9491414676622171 and parameters: {'weight_class_0': 0.022824328766913062, 'weight_class_1': 0.6905379276825395, 'weight_class_2': 0.197324548058428}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:34,746] Trial 958 finished with value: 0.9484878541599567 and parameters: {'weight_class_0': 0.023909174158398133, 'weight_class_1': 0.6897459041426883, 'weight_class_2': 0.6013545501527282}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:34,770] Trial 959 finished with value: 0.9483168500366483 and parameters: {'weight_class_0': 0.02425776716852811, 'weight_class_1': 0.6893638789224386, 'weight_class_2': 0.675837418611982}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:34,803] Trial 961 finished with value: 0.9388504113872124 and parameters: {'weight_class_0': 0.024351622422572904, 'weight_class_1': 0.7257973480070437, 'weight_class_2': 3.0866183526264077}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:34,809] Trial 960 finished with value: 0.9490540992689945 and parameters: {'weight_class_0': 0.024496392804216203, 'weight_class_1': 0.6834733640921035, 'weight_class_2': 0.19135385336158045}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:34,839] Trial 962 finished with value: 0.9483145686592023 and parameters: {'weight_class_0': 0.023625653854557734, 'weight_class_1': 1.049225698077051, 'weight_class_2': 0.20068292231933163}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  32%|███████████████████████████████████████████                                                                                          | 971/3000 [00:20<00:51, 39.62it/s]

[I 2026-07-05 15:25:34,847] Trial 963 finished with value: 0.948434932915191 and parameters: {'weight_class_0': 0.024086496728421863, 'weight_class_1': 0.6775242353864426, 'weight_class_2': 0.615583069149442}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:34,896] Trial 964 finished with value: 0.9488654529032327 and parameters: {'weight_class_0': 0.035940491751907305, 'weight_class_1': 1.0264589549667555, 'weight_class_2': 0.722239525882559}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:34,909] Trial 965 finished with value: 0.9486264270971185 and parameters: {'weight_class_0': 0.033721845235921, 'weight_class_1': 1.0628995511858392, 'weight_class_2': 0.719709364410933}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:34,953] Trial 966 finished with value: 0.9492664947295025 and parameters: {'weight_class_0': 0.03341782195758786, 'weight_class_1': 0.5507823340794041, 'weight_class_2': 0.24417253472279232}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:34,981] Trial 967 finished with value: 0.9491298382953399 and parameters: {'weight_class_0': 0.034717768922103036, 'weight_class_1': 0.534240449270669, 'weight_class_2': 0.6436092790840786}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:34,994] Trial 968 finished with value: 0.9492150833530637 and parameters: {'weight_class_0': 0.035090753659306195, 'weight_class_1': 0.5422013444057423, 'weight_class_2': 0.6279187977031975}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:35,015] Trial 970 finished with value: 0.9124590021618024 and parameters: {'weight_class_0': 0.03372676360438274, 'weight_class_1': 0.029171093625581145, 'weight_class_2': 0.2434867802331869}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:35,017] Trial 969 finished with value: 0.9339078412069374 and parameters: {'weight_class_0': 0.01435792011824834, 'weight_class_1': 0.02596079496334238, 'weight_class_2': 0.2503617228158413}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:35,082] Trial 971 finished with value: 0.9104993660372146 and parameters: {'weight_class_0': 0.03346763217846507, 'weight_class_1': 0.026824679898707675, 'weight_class_2': 0.23003892346594543}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  33%|███████████████████████████████████████████▍                                                                                         | 980/3000 [00:20<00:50, 39.85it/s]

[I 2026-07-05 15:25:35,096] Trial 972 finished with value: 0.9491557415976111 and parameters: {'weight_class_0': 0.03335677700204148, 'weight_class_1': 0.5083333965287269, 'weight_class_2': 0.24024607111424753}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:35,138] Trial 973 finished with value: 0.921002251945513 and parameters: {'weight_class_0': 0.013350764946381924, 'weight_class_1': 0.5008908818495282, 'weight_class_2': 0.01836046513978209}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:35,170] Trial 974 finished with value: 0.9483812894078637 and parameters: {'weight_class_0': 0.012926466397905855, 'weight_class_1': 0.5244216548071737, 'weight_class_2': 0.240658423791291}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:35,174] Trial 976 finished with value: 0.947550317822774 and parameters: {'weight_class_0': 0.01433827245896203, 'weight_class_1': 0.573178654224497, 'weight_class_2': 0.4655262215839102}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:35,182] Trial 975 finished with value: 0.9224023491666767 and parameters: {'weight_class_0': 0.014590528828354895, 'weight_class_1': 0.017809150838698055, 'weight_class_2': 0.23650956514539428}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:35,228] Trial 978 finished with value: 0.9485968354719617 and parameters: {'weight_class_0': 0.04950520351975984, 'weight_class_1': 0.3082141321900482, 'weight_class_2': 0.4270442027236485}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:35,251] Trial 977 finished with value: 0.9478785892933098 and parameters: {'weight_class_0': 0.014068278182338297, 'weight_class_1': 0.2068152781636849, 'weight_class_2': 0.40318852422614826}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:35,256] Trial 979 finished with value: 0.8942495375747909 and parameters: {'weight_class_0': 0.051259944878400715, 'weight_class_1': 0.01839221211543959, 'weight_class_2': 0.46160252740286245}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:35,300] Trial 980 finished with value: 0.9467315369307258 and parameters: {'weight_class_0': 0.049455759105896564, 'weight_class_1': 0.20249250862970622, 'weight_class_2': 0.4385693476694735}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  33%|███████████████████████████████████████████▊                                                                                         | 989/3000 [00:20<00:49, 40.90it/s]

[I 2026-07-05 15:25:35,338] Trial 981 finished with value: 0.8756804381838963 and parameters: {'weight_class_0': 0.0013989968454140146, 'weight_class_1': 0.018022688540794855, 'weight_class_2': 0.41562684768326175}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:35,362] Trial 982 finished with value: 0.8416762716975978 and parameters: {'weight_class_0': 0.04569695100794407, 'weight_class_1': 0.017934829886725335, 'weight_class_2': 0.01637827419558305}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:35,385] Trial 983 finished with value: 0.9488656934424545 and parameters: {'weight_class_0': 0.04653023190490854, 'weight_class_1': 0.3108613956525921, 'weight_class_2': 0.406105924391003}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:35,410] Trial 985 finished with value: 0.9492345548021176 and parameters: {'weight_class_0': 0.046253504204334814, 'weight_class_1': 0.34172519446788274, 'weight_class_2': 0.41853872794116276}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:35,420] Trial 984 finished with value: 0.9468472261918879 and parameters: {'weight_class_0': 0.04771274165064587, 'weight_class_1': 0.19632710748033375, 'weight_class_2': 0.4253349966244259}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:35,442] Trial 986 finished with value: 0.9488894044101616 and parameters: {'weight_class_0': 0.046713944570245976, 'weight_class_1': 0.31114971419524806, 'weight_class_2': 0.4256437543625824}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:35,481] Trial 987 finished with value: 0.9491721625981663 and parameters: {'weight_class_0': 0.04407362630792738, 'weight_class_1': 0.3172780051335705, 'weight_class_2': 0.3970454344810632}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:35,483] Trial 988 finished with value: 0.9438514733590884 and parameters: {'weight_class_0': 0.05181184380028512, 'weight_class_1': 0.3776830781507098, 'weight_class_2': 0.1577334569793972}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:35,506] Trial 989 finished with value: 0.9453163242336218 and parameters: {'weight_class_0': 0.043636704885407, 'weight_class_1': 0.3797890922346998, 'weight_class_2': 0.14735819100036152}. Best is trial 433 with value: 0.9498304662349432.

[I 2026-07-05 15:25:35,519] Trial 990 finished with value: 0.9494680409672328 and parameters: {'weight_class_0': 0.043121642964709106, 'weight_class_1': 0.37088313392108363, 'weight_class_2': 0.4061593326108863}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:35,560] Trial 991 finished with value: 0.9447715869848907 and parameters: {'weight_class_0': 0.04440729444182294, 'weight_class_1': 0.38334079667730936, 'weight_class_2': 0.14387866711999373}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:35,598] Trial 993 finished with value: 0.9189091056873152 and parameters: {'weight_class_0': 0.002487610106337785, 'weight_class_1': 0.40059953841030005, 'weight_class_2': 0.16279875789336076}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:35,602] Trial 992 finished with value: 0.9172656325088266 and parameters: {'weight_class_0': 0.002294976986990355, 'weight_class_1': 0.37682533337472834, 'weight_class_2': 0.16575654067391815}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:35,639] Trial 994 finished with value: 0.9134036000325673 and parameters: {'weight_class_0': 0.002339711821225176, 'weight_class_1': 0.3799645799386458, 'weight_class_2': 0.279733894663457}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:35,662] Trial 995 finished with value: 0.9496362434119016 and parameters: {'weight_class_0': 0.028764551645321327, 'weight_class_1': 0.38715843927990357, 'weight_class_2': 0.2887183726188673}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:35,677] Trial 996 finished with value: 0.9497511724798172 and parameters: {'weight_class_0': 0.027148811730369423, 'weight_class_1': 0.4175891723620128, 'weight_class_2': 0.29838190657931957}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:35,693] Trial 997 finished with value: 0.9107286716603812 and parameters: {'weight_class_0': 0.02733636521695226, 'weight_class_1': 0.41011302439908537, 'weight_class_2': 0.027771461947847357}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:35,728] Trial 998 finished with value: 0.9136062749842085 and parameters: {'weight_class_0': 0.002468772156918607, 'weight_class_1': 0.4028751291154795, 'weight_class_2': 0.28691752470486465}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  34%|████████████████████████████████████████████▎                                                                                       | 1008/3000 [00:21<00:45, 43.78it/s]

[I 2026-07-05 15:25:35,731] Trial 999 finished with value: 0.9496332702431806 and parameters: {'weight_class_0': 0.028003792249784727, 'weight_class_1': 0.4273241192294211, 'weight_class_2': 0.2812913327213763}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:35,763] Trial 1000 finished with value: 0.9496812044258806 and parameters: {'weight_class_0': 0.028719795854134974, 'weight_class_1': 0.43167275657544857, 'weight_class_2': 0.2764754959293686}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:35,814] Trial 1001 finished with value: 0.8953579302305826 and parameters: {'weight_class_0': 0.0022875756067974105, 'weight_class_1': 0.4461678314095731, 'weight_class_2': 0.011709014446589562}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:35,821] Trial 1002 finished with value: 0.904222354410888 and parameters: {'weight_class_0': 0.3068191304606786, 'weight_class_1': 1.4313366238750933, 'weight_class_2': 0.27058519644694334}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:35,824] Trial 1003 finished with value: 0.9483831642829533 and parameters: {'weight_class_0': 0.02776712353959636, 'weight_class_1': 1.2582764569475047, 'weight_class_2': 0.26600566426742267}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:35,867] Trial 1004 finished with value: 0.9496812721126621 and parameters: {'weight_class_0': 0.029657922224900782, 'weight_class_1': 0.4556591050612407, 'weight_class_2': 0.2883762067285407}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:35,872] Trial 1005 finished with value: 0.9496818980143694 and parameters: {'weight_class_0': 0.02900859806124291, 'weight_class_1': 0.44425887815092846, 'weight_class_2': 0.2816656685679074}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:35,897] Trial 1006 finished with value: 0.9187750266803811 and parameters: {'weight_class_0': 0.028236844101709287, 'weight_class_1': 4.621567456297085, 'weight_class_2': 0.8641928357715281}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:35,942] Trial 1008 finished with value: 0.9483262782660863 and parameters: {'weight_class_0': 0.020927788687670694, 'weight_class_1': 0.9584881875085914, 'weight_class_2': 0.2775026481684976}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:35,946] Trial 1009 finished with value: 0.8892859779873653 and parameters: {'weight_class_0': 0.020412123249854235, 'weight_class_1': 0.006370289130038507, 'weight_class_2': 0.5393517320717806}. Best is trial 433 with value: 0.9498304662349432.

[I 2026-07-05 15:25:35,949] Trial 1007 finished with value: 0.9474811798442339 and parameters: {'weight_class_0': 0.019980705212768374, 'weight_class_1': 0.46498797498719574, 'weight_class_2': 0.7842286247641203}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:35,992] Trial 1010 finished with value: 0.9430477100295866 and parameters: {'weight_class_0': 0.016195606944800666, 'weight_class_1': 1.464597393564562, 'weight_class_2': 0.2007423811752035}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:36,013] Trial 1011 finished with value: 0.9482660749947046 and parameters: {'weight_class_0': 0.01999228652977717, 'weight_class_1': 0.949086425659896, 'weight_class_2': 0.2101419360007999}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:36,038] Trial 1012 finished with value: 0.8551980644647782 and parameters: {'weight_class_0': 1.40878773216866, 'weight_class_1': 1.296065660547455, 'weight_class_2': 0.2018242678658114}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:36,071] Trial 1013 finished with value: 0.909293974097828 and parameters: {'weight_class_0': 0.0207267307221969, 'weight_class_1': 0.9649688190946647, 'weight_class_2': 4.580088377631591}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:36,091] Trial 1014 finished with value: 0.9471637058933734 and parameters: {'weight_class_0': 0.02158219891999555, 'weight_class_1': 0.9297046907986318, 'weight_class_2': 0.7930360127065269}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:36,114] Trial 1015 finished with value: 0.94761573488113 and parameters: {'weight_class_0': 0.020509109636595635, 'weight_class_1': 0.8753553048923978, 'weight_class_2': 0.55972907969681}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:36,135] Trial 1016 finished with value: 0.9488004216412241 and parameters: {'weight_class_0': 0.02032460471963259, 'weight_class_1': 0.7950611190894628, 'weight_class_2': 0.198603572601758}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:36,159] Trial 1018 finished with value: 0.9486680580474997 and parameters: {'weight_class_0': 0.021573669266822398, 'weight_class_1': 0.8810715931401082, 'weight_class_2': 0.20411330944103953}. Best is trial 433 with value: 0.9498304662349432.

[I 2026-07-05 15:25:36,164] Trial 1017 finished with value: 0.9462377975359809 and parameters: {'weight_class_0': 0.01593176128321371, 'weight_class_1': 0.930870101971795, 'weight_class_2': 0.5461550706405877}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:36,178] Trial 1019 finished with value: 0.9489335277774987 and parameters: {'weight_class_0': 0.016127526602852334, 'weight_class_1': 0.6042821432125142, 'weight_class_2': 0.20306870128428722}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:36,215] Trial 1020 finished with value: 0.948261467190965 and parameters: {'weight_class_0': 0.03853310568215591, 'weight_class_1': 0.6000829142779073, 'weight_class_2': 0.1956247013060062}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:36,243] Trial 1021 finished with value: 0.9478317610557357 and parameters: {'weight_class_0': 0.07490514409792721, 'weight_class_1': 0.7588810022259744, 'weight_class_2': 0.35394965761271635}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:36,283] Trial 1023 finished with value: 0.9482846484532508 and parameters: {'weight_class_0': 0.06692143150232152, 'weight_class_1': 0.6080772963954719, 'weight_class_2': 0.3545737596921087}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:36,299] Trial 1022 finished with value: 0.9496757824947162 and parameters: {'weight_class_0': 0.039100327506668864, 'weight_class_1': 0.5966696756194653, 'weight_class_2': 0.36622440186371885}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:36,318] Trial 1024 finished with value: 0.9474398192819865 and parameters: {'weight_class_0': 0.07784370053306582, 'weight_class_1': 0.5600970438231249, 'weight_class_2': 0.3629608529877248}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:36,337] Trial 1025 finished with value: 0.9487706063616219 and parameters: {'weight_class_0': 0.059937659248346827, 'weight_class_1': 0.7735773912980791, 'weight_class_2': 0.35804103602536486}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:36,352] Trial 1026 finished with value: 0.9497236770527796 and parameters: {'weight_class_0': 0.035227875820043233, 'weight_class_1': 0.5865242168341065, 'weight_class_2': 0.3487677113618771}. Best is trial 433 with value: 0.9498304662349432.

[I 2026-07-05 15:25:36,364] Trial 1027 finished with value: 0.9472731827156314 and parameters: {'weight_class_0': 0.07958904969907696, 'weight_class_1': 0.6020871425863316, 'weight_class_2': 0.34880931712557}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:36,402] Trial 1029 finished with value: 0.9469160283161419 and parameters: {'weight_class_0': 0.0607776362052382, 'weight_class_1': 0.2986514581090311, 'weight_class_2': 0.32487347553068974}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:36,410] Trial 1028 finished with value: 0.9485186863749258 and parameters: {'weight_class_0': 0.06314491867059696, 'weight_class_1': 0.5949386051927353, 'weight_class_2': 0.35491369727510985}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:36,439] Trial 1030 finished with value: 0.949346685966876 and parameters: {'weight_class_0': 0.03514946930457632, 'weight_class_1': 0.29450626696078064, 'weight_class_2': 0.3543232284100903}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:36,454] Trial 1031 finished with value: 0.9441794810692157 and parameters: {'weight_class_0': 0.07731101322383642, 'weight_class_1': 0.2896374863494994, 'weight_class_2': 0.34432084582327577}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:36,485] Trial 1032 finished with value: 0.9282909979228738 and parameters: {'weight_class_0': 0.13896274066016182, 'weight_class_1': 0.2845034547214036, 'weight_class_2': 0.3448348399866442}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:36,527] Trial 1034 finished with value: 0.9470128379360604 and parameters: {'weight_class_0': 0.059269168718070746, 'weight_class_1': 0.27607922634269816, 'weight_class_2': 0.3503618885989391}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:36,529] Trial 1033 finished with value: 0.9467736887223478 and parameters: {'weight_class_0': 0.06037329183106783, 'weight_class_1': 0.2809265420016691, 'weight_class_2': 0.3351754219052186}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:36,572] Trial 1035 finished with value: 0.897243065056298 and parameters: {'weight_class_0': 0.05779260715124001, 'weight_class_1': 0.2887866227598517, 'weight_class_2': 0.03288938311714884}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  35%|█████████████████████████████████████████████▉                                                                                      | 1045/3000 [00:22<00:44, 44.31it/s]

[I 2026-07-05 15:25:36,595] Trial 1036 finished with value: 0.9487859349549502 and parameters: {'weight_class_0': 0.03386012969556444, 'weight_class_1': 0.2905544167403321, 'weight_class_2': 0.5148359871333447}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:36,608] Trial 1037 finished with value: 0.9487589577765002 and parameters: {'weight_class_0': 0.032063390464016274, 'weight_class_1': 0.2744750234580361, 'weight_class_2': 0.4916963069183926}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:36,626] Trial 1038 finished with value: 0.9483527051772048 and parameters: {'weight_class_0': 0.03243571023629642, 'weight_class_1': 0.2213242401160427, 'weight_class_2': 0.49231471767700186}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:36,631] Trial 1039 finished with value: 0.9483536506565567 and parameters: {'weight_class_0': 0.033730978035944825, 'weight_class_1': 0.2306503123163357, 'weight_class_2': 0.5022801524945164}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:36,665] Trial 1040 finished with value: 0.9482493648012924 and parameters: {'weight_class_0': 0.03332745955467034, 'weight_class_1': 0.21206221621076038, 'weight_class_2': 0.47956485225661155}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:36,691] Trial 1041 finished with value: 0.9314806832934481 and parameters: {'weight_class_0': 0.12755496330134103, 'weight_class_1': 0.2366248770288967, 'weight_class_2': 0.4796170333223714}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:36,724] Trial 1042 finished with value: 0.9494627776504428 and parameters: {'weight_class_0': 0.025265453882424394, 'weight_class_1': 0.21666764051351894, 'weight_class_2': 0.23867514896269082}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:36,756] Trial 1043 finished with value: 0.9491070888413945 and parameters: {'weight_class_0': 0.012382249055188152, 'weight_class_1': 0.22431946722831858, 'weight_class_2': 0.23505023936367356}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:36,780] Trial 1044 finished with value: 0.9479768727514747 and parameters: {'weight_class_0': 0.025643142146525136, 'weight_class_1': 0.20894066347150844, 'weight_class_2': 0.5179458350658394}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:36,784] Trial 1045 finished with value: 0.9159498116256256 and parameters: {'weight_class_0': 0.02603715817291416, 'weight_class_1': 0.2103322641266585, 'weight_class_2': 0.030650991853224757}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  35%|██████████████████████████████████████████████▍                                                                                     | 1054/3000 [00:22<00:46, 42.08it/s]

[I 2026-07-05 15:25:36,818] Trial 1046 finished with value: 0.9450521797393238 and parameters: {'weight_class_0': 0.025167592369259938, 'weight_class_1': 1.890546266387022, 'weight_class_2': 0.5242769962647371}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:36,828] Trial 1047 finished with value: 0.8857803054279726 and parameters: {'weight_class_0': 0.0011467992968323105, 'weight_class_1': 0.19634645844391432, 'weight_class_2': 0.23956165703331211}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:36,840] Trial 1048 finished with value: 0.8934184186404125 and parameters: {'weight_class_0': 0.0012175020669042097, 'weight_class_1': 0.1947718397913816, 'weight_class_2': 0.24370680408010706}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:36,876] Trial 1049 finished with value: 0.9490099179685187 and parameters: {'weight_class_0': 0.0248854067989623, 'weight_class_1': 0.1792406589889129, 'weight_class_2': 0.25100094378706417}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:36,881] Trial 1050 finished with value: 0.8632039925436846 and parameters: {'weight_class_0': 0.02468882344358425, 'weight_class_1': 0.49949170714965485, 'weight_class_2': 0.0016312060117797112}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:36,927] Trial 1051 finished with value: 0.9492266009683914 and parameters: {'weight_class_0': 0.015538543426556556, 'weight_class_1': 0.17979853730303663, 'weight_class_2': 0.2355544321035395}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:36,949] Trial 1052 finished with value: 0.9497129518100276 and parameters: {'weight_class_0': 0.025004586715317946, 'weight_class_1': 0.4911621671433101, 'weight_class_2': 0.24431378353579636}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:36,965] Trial 1053 finished with value: 0.9496363092637706 and parameters: {'weight_class_0': 0.015950691430172404, 'weight_class_1': 0.18435645925708044, 'weight_class_2': 0.1593798924313113}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:36,975] Trial 1054 finished with value: 0.9492213376516014 and parameters: {'weight_class_0': 0.015775853327955523, 'weight_class_1': 0.18172700413859502, 'weight_class_2': 0.2403355128571649}. Best is trial 433 with value: 0.9498304662349432.

[I 2026-07-05 15:25:37,018] Trial 1055 finished with value: 0.9492559223058824 and parameters: {'weight_class_0': 0.015401715879253418, 'weight_class_1': 0.48504810833887163, 'weight_class_2': 0.152966967632241}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:37,038] Trial 1056 finished with value: 0.9490085514644271 and parameters: {'weight_class_0': 0.015280498656960271, 'weight_class_1': 0.508176585925292, 'weight_class_2': 0.2473723890426834}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:37,056] Trial 1058 finished with value: 0.9493570300971692 and parameters: {'weight_class_0': 0.015857593412000826, 'weight_class_1': 0.4697433390461452, 'weight_class_2': 0.15797358790277874}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:37,101] Trial 1057 finished with value: 0.9471456219847433 and parameters: {'weight_class_0': 0.038488377871630564, 'weight_class_1': 0.521752040631014, 'weight_class_2': 0.16180314129449777}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:37,106] Trial 1059 finished with value: 0.8645381478315824 and parameters: {'weight_class_0': 0.4412847315268903, 'weight_class_1': 0.4884311231638834, 'weight_class_2': 0.1389365786499755}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:37,125] Trial 1060 finished with value: 0.9485511150167544 and parameters: {'weight_class_0': 0.017294669049171926, 'weight_class_1': 0.7045079351391248, 'weight_class_2': 0.14963684621625173}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:37,179] Trial 1061 finished with value: 0.8460707612216541 and parameters: {'weight_class_0': 0.001574161391294687, 'weight_class_1': 0.49131226415668594, 'weight_class_2': 0.1510330803860298}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:37,209] Trial 1063 finished with value: 0.9454993139371436 and parameters: {'weight_class_0': 0.012434143851395877, 'weight_class_1': 0.7591668883328566, 'weight_class_2': 0.6240050807688409}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  36%|███████████████████████████████████████████████                                                                                     | 1071/3000 [00:22<00:46, 41.40it/s]

[I 2026-07-05 15:25:37,210] Trial 1062 finished with value: 0.949345232084335 and parameters: {'weight_class_0': 0.01573319312584768, 'weight_class_1': 0.4823909847713104, 'weight_class_2': 0.1684547822732577}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:37,229] Trial 1064 finished with value: 0.9494597930760843 and parameters: {'weight_class_0': 0.041965822628792344, 'weight_class_1': 0.7325229635186322, 'weight_class_2': 0.6662311586697038}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:37,281] Trial 1065 finished with value: 0.9487811211512543 and parameters: {'weight_class_0': 0.04066186757156014, 'weight_class_1': 0.35124626713100815, 'weight_class_2': 0.6389050357817179}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:37,287] Trial 1066 finished with value: 0.9486631303233541 and parameters: {'weight_class_0': 0.039636337059693647, 'weight_class_1': 0.3480208097800372, 'weight_class_2': 0.6517231518260448}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:37,310] Trial 1067 finished with value: 0.9351471592682373 and parameters: {'weight_class_0': 0.012240108719330726, 'weight_class_1': 0.36175983876434026, 'weight_class_2': 0.02511280024314656}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:37,360] Trial 1068 finished with value: 0.9487427258201145 and parameters: {'weight_class_0': 0.0382625177539133, 'weight_class_1': 0.3354802537591273, 'weight_class_2': 0.6128210455334187}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:37,362] Trial 1069 finished with value: 0.9485043708013238 and parameters: {'weight_class_0': 0.04062087413497617, 'weight_class_1': 0.3440285589968412, 'weight_class_2': 0.7040734062083086}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:37,389] Trial 1070 finished with value: 0.9486448653422827 and parameters: {'weight_class_0': 0.039120736024514234, 'weight_class_1': 0.3499679248834866, 'weight_class_2': 0.6677807319374758}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:37,428] Trial 1071 finished with value: 0.9486802764639068 and parameters: {'weight_class_0': 0.04029397495502458, 'weight_class_1': 0.3320152713862343, 'weight_class_2': 0.6198324888874192}. Best is trial 433 with value: 0.9498304662349432.

[I 2026-07-05 15:25:37,436] Trial 1072 finished with value: 0.9487493665216707 and parameters: {'weight_class_0': 0.029725378580106855, 'weight_class_1': 0.7358963392164003, 'weight_class_2': 0.6590480824672934}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:37,465] Trial 1073 finished with value: 0.9492880776306079 and parameters: {'weight_class_0': 0.03826768854107229, 'weight_class_1': 0.36747981800259344, 'weight_class_2': 0.2933986090981732}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:37,487] Trial 1074 finished with value: 0.9489945234543021 and parameters: {'weight_class_0': 0.03933415865313215, 'weight_class_1': 1.1592929273764605, 'weight_class_2': 0.2980347744245229}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:37,500] Trial 1075 finished with value: 0.9496139127467673 and parameters: {'weight_class_0': 0.03720270570933042, 'weight_class_1': 0.3498784197779364, 'weight_class_2': 0.4258185681934105}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:37,520] Trial 1076 finished with value: 0.948571225955551 and parameters: {'weight_class_0': 0.028657394356731085, 'weight_class_1': 1.2227709406290437, 'weight_class_2': 0.2933633829812097}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:37,584] Trial 1077 finished with value: 0.8991568155814619 and parameters: {'weight_class_0': 0.029721137049223828, 'weight_class_1': 0.6569546276758135, 'weight_class_2': 0.018217607994605898}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:37,589] Trial 1078 finished with value: 0.9495954078123378 and parameters: {'weight_class_0': 0.030497570536156756, 'weight_class_1': 0.34151488216560305, 'weight_class_2': 0.3010072552871605}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:37,609] Trial 1079 finished with value: 0.9496296911520643 and parameters: {'weight_class_0': 0.028672132542944918, 'weight_class_1': 0.6070978476459601, 'weight_class_2': 0.28924752262870346}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:37,658] Trial 1081 finished with value: 0.9359755271987984 and parameters: {'weight_class_0': 0.03099279811422513, 'weight_class_1': 3.653631006303394, 'weight_class_2': 0.42674807191084607}. Best is trial 433 with value: 0.9498304662349432.

[I 2026-07-05 15:25:37,663] Trial 1080 finished with value: 0.8993597969112234 and parameters: {'weight_class_0': 0.028676991196476747, 'weight_class_1': 1.1652515788517752, 'weight_class_2': 0.020241219180596612}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:37,705] Trial 1082 finished with value: 0.9488750880177026 and parameters: {'weight_class_0': 0.02065010601344661, 'weight_class_1': 0.618075225366939, 'weight_class_2': 0.4035954413181949}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:37,709] Trial 1083 finished with value: 0.9488676649327917 and parameters: {'weight_class_0': 0.020927717331084703, 'weight_class_1': 0.6354831695190009, 'weight_class_2': 0.4055360283172981}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:37,722] Trial 1084 finished with value: 0.929098988409919 and parameters: {'weight_class_0': 0.021061338237649732, 'weight_class_1': 0.03252030443155329, 'weight_class_2': 0.42537880582383825}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:37,754] Trial 1085 finished with value: 0.9031187054856774 and parameters: {'weight_class_0': 0.021710165361910113, 'weight_class_1': 0.6491892870607537, 'weight_class_2': 0.017491322634708484}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:37,772] Trial 1086 finished with value: 0.9492363935964573 and parameters: {'weight_class_0': 0.020885917996239543, 'weight_class_1': 0.6583227385873388, 'weight_class_2': 0.20452782196912278}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:37,808] Trial 1088 finished with value: 0.9486898238370755 and parameters: {'weight_class_0': 0.02057778705564896, 'weight_class_1': 0.6603261288729845, 'weight_class_2': 0.4132909754733694}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:37,811] Trial 1087 finished with value: 0.9488822533006793 and parameters: {'weight_class_0': 0.02150052673648199, 'weight_class_1': 0.6256311340365242, 'weight_class_2': 0.4252077666245201}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  37%|████████████████████████████████████████████████▎                                                                                   | 1097/3000 [00:23<00:45, 41.81it/s]

[I 2026-07-05 15:25:37,851] Trial 1089 finished with value: 0.8966631986006478 and parameters: {'weight_class_0': 0.02011764054215492, 'weight_class_1': 0.008158311327575794, 'weight_class_2': 0.19513942723876856}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:37,852] Trial 1090 finished with value: 0.9471155021179177 and parameters: {'weight_class_0': 0.02005674702603399, 'weight_class_1': 0.4340783023374518, 'weight_class_2': 0.8997899144364505}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:37,872] Trial 1091 finished with value: 0.8272655227209055 and parameters: {'weight_class_0': 2.159596605700366, 'weight_class_1': 0.4224921544470754, 'weight_class_2': 0.4233959438595567}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:37,918] Trial 1093 finished with value: 0.9496536563595298 and parameters: {'weight_class_0': 0.020651176627923682, 'weight_class_1': 0.45518376758671625, 'weight_class_2': 0.1958970703081765}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:37,929] Trial 1092 finished with value: 0.8903196079241029 and parameters: {'weight_class_0': 0.020111457263890773, 'weight_class_1': 0.007810049858272652, 'weight_class_2': 0.8993911438363261}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:37,930] Trial 1094 finished with value: 0.9496908790955021 and parameters: {'weight_class_0': 0.023683967974317335, 'weight_class_1': 0.4338166532771007, 'weight_class_2': 0.2151717213427132}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:37,990] Trial 1095 finished with value: 0.9401779172309075 and parameters: {'weight_class_0': 0.0018863361861035726, 'weight_class_1': 0.13947383199388275, 'weight_class_2': 0.193704850234937}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:38,027] Trial 1096 finished with value: 0.5796739330041648 and parameters: {'weight_class_0': 9.753470391493181, 'weight_class_1': 0.00820353877925124, 'weight_class_2': 0.9684743856082099}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:38,039] Trial 1098 finished with value: 0.8936625048536376 and parameters: {'weight_class_0': 0.0020185657369669726, 'weight_class_1': 0.4279683739874465, 'weight_class_2': 0.19581435802888367}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 433. Best value: 0.94983:  37%|████████████████████████████████████████████████▋                                                                                   | 1106/3000 [00:23<00:45, 41.32it/s]

[I 2026-07-05 15:25:38,051] Trial 1097 finished with value: 0.8062709111384091 and parameters: {'weight_class_0': 0.0018155115665394854, 'weight_class_1': 0.13455863177309282, 'weight_class_2': 0.8642086980369581}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:38,088] Trial 1099 finished with value: 0.9454176065230268 and parameters: {'weight_class_0': 0.05324105049059434, 'weight_class_1': 0.2556929290442955, 'weight_class_2': 0.21612974653959724}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:38,097] Trial 1100 finished with value: 0.9496180804117839 and parameters: {'weight_class_0': 0.024840903508250946, 'weight_class_1': 0.452966432380686, 'weight_class_2': 0.21726326023349543}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:38,135] Trial 1101 finished with value: 0.8891254451364055 and parameters: {'weight_class_0': 0.025336504613454262, 'weight_class_1': 0.010365605597992399, 'weight_class_2': 1.3559869528263344}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:38,182] Trial 1103 finished with value: 0.9485586555311034 and parameters: {'weight_class_0': 0.05300243574596254, 'weight_class_1': 0.791525899072152, 'weight_class_2': 0.30126812295210076}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:38,208] Trial 1102 finished with value: 0.9188434523593277 and parameters: {'weight_class_0': 0.0019197631734798118, 'weight_class_1': 0.24716792955438746, 'weight_class_2': 0.295201357017884}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:38,214] Trial 1104 finished with value: 0.9117297160794227 and parameters: {'weight_class_0': 0.0018069459222931133, 'weight_class_1': 0.25402849676788963, 'weight_class_2': 0.29939295677787453}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:38,241] Trial 1106 finished with value: 0.949339893429863 and parameters: {'weight_class_0': 0.025160489915628966, 'weight_class_1': 0.8054941911912801, 'weight_class_2': 0.2963889855490105}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:38,241] Trial 1105 finished with value: 0.9465469989590881 and parameters: {'weight_class_0': 0.055539748329923574, 'weight_class_1': 0.2506563844058339, 'weight_class_2': 0.2998728997581124}. Best is trial 433 with value: 0.9498304662349432.

[I 2026-07-05 15:25:38,289] Trial 1107 finished with value: 0.8837998803022437 and parameters: {'weight_class_0': 0.05315010756045604, 'weight_class_1': 0.010587422258908434, 'weight_class_2': 0.3039052587520644}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:38,292] Trial 1108 finished with value: 0.8922220752258543 and parameters: {'weight_class_0': 0.05184239087132322, 'weight_class_1': 0.2553062303638714, 'weight_class_2': 0.013598027390569025}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:38,318] Trial 1109 finished with value: 0.9478797947522697 and parameters: {'weight_class_0': 0.02486223452793042, 'weight_class_1': 0.7871692158296502, 'weight_class_2': 0.13003139721701146}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:38,351] Trial 1110 finished with value: 0.9422641285351023 and parameters: {'weight_class_0': 0.04891745516321818, 'weight_class_1': 0.8259232290612248, 'weight_class_2': 0.13115459249972378}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:38,379] Trial 1111 finished with value: 0.9483634253835146 and parameters: {'weight_class_0': 0.0523809195299656, 'weight_class_1': 0.8243430207221611, 'weight_class_2': 0.2776237046982121}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:38,414] Trial 1112 finished with value: 0.949706890723574 and parameters: {'weight_class_0': 0.012919321855534191, 'weight_class_1': 0.25208791207079695, 'weight_class_2': 0.1262107738944871}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:38,430] Trial 1113 finished with value: 0.9487875593682205 and parameters: {'weight_class_0': 0.011976905948879712, 'weight_class_1': 0.24575563233790146, 'weight_class_2': 0.2706030326916048}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:38,468] Trial 1114 finished with value: 0.923070516953098 and parameters: {'weight_class_0': 0.03249871005198677, 'weight_class_1': 0.040296630284018475, 'weight_class_2': 0.2593974693746861}. Best is trial 433 with value: 0.9498304662349432.

Best trial: 1121. Best value: 0.949833:  37%|████████████████████████████████████████████████▋                                                                                 | 1123/3000 [00:24<00:46, 40.16it/s]

[I 2026-07-05 15:25:38,494] Trial 1115 finished with value: 0.9484243648187353 and parameters: {'weight_class_0': 0.012497545631199461, 'weight_class_1': 0.5536332645429644, 'weight_class_2': 0.12946772646347923}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:38,504] Trial 1116 finished with value: 0.9463502827448376 and parameters: {'weight_class_0': 0.012151591268437739, 'weight_class_1': 0.7829383587997254, 'weight_class_2': 0.24848579255506537}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:38,545] Trial 1117 finished with value: 0.9485411674205314 and parameters: {'weight_class_0': 0.012328330397582504, 'weight_class_1': 0.5344593492549449, 'weight_class_2': 0.119017404947691}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:38,552] Trial 1118 finished with value: 0.9497069680558837 and parameters: {'weight_class_0': 0.033456221362883794, 'weight_class_1': 0.49970873966989987, 'weight_class_2': 0.3583243991017891}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:38,557] Trial 1119 finished with value: 0.9473928946810345 and parameters: {'weight_class_0': 0.011644515262127867, 'weight_class_1': 0.514057728444758, 'weight_class_2': 0.3551572489063425}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:38,605] Trial 1120 finished with value: 0.9170518743777877 and parameters: {'weight_class_0': 0.22948774572225542, 'weight_class_1': 0.5298357945030732, 'weight_class_2': 0.36463297657106614}. Best is trial 433 with value: 0.9498304662349432.
[I 2026-07-05 15:25:38,642] Trial 1121 finished with value: 0.94983269980651 and parameters: {'weight_class_0': 0.03196866600351773, 'weight_class_1': 0.532014214601177, 'weight_class_2': 0.37592965629852965}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:38,673] Trial 1123 finished with value: 0.9497848408586953 and parameters: {'weight_class_0': 0.033292968708622306, 'weight_class_1': 0.5656404492262862, 'weight_class_2': 0.37101064729520733}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:38,676] Trial 1124 finished with value: 0.9498210525308108 and parameters: {'weight_class_0': 0.03189688579304501, 'weight_class_1': 0.5352028489407827, 'weight_class_2': 0.3731271883124181}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  38%|█████████████████████████████████████████████████                                                                                 | 1132/3000 [00:24<00:45, 40.87it/s]

[I 2026-07-05 15:25:38,690] Trial 1122 finished with value: 0.9497997761545095 and parameters: {'weight_class_0': 0.03196842676703937, 'weight_class_1': 0.5256763285645109, 'weight_class_2': 0.3770084345238058}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:38,711] Trial 1125 finished with value: 0.9496992280095883 and parameters: {'weight_class_0': 0.03263723726517439, 'weight_class_1': 0.5279178220845762, 'weight_class_2': 0.3542280067705106}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:38,738] Trial 1126 finished with value: 0.9493699260286214 and parameters: {'weight_class_0': 0.031956102608517264, 'weight_class_1': 0.5348324841890219, 'weight_class_2': 0.5423245521560925}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:38,798] Trial 1127 finished with value: 0.9488021359168272 and parameters: {'weight_class_0': 0.032025687041748456, 'weight_class_1': 0.3134742996855968, 'weight_class_2': 0.5465582600931816}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:38,799] Trial 1128 finished with value: 0.9487829525393213 and parameters: {'weight_class_0': 0.03088791697571363, 'weight_class_1': 0.3093127022757645, 'weight_class_2': 0.536956188050815}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:38,816] Trial 1129 finished with value: 0.8690493797444397 and parameters: {'weight_class_0': 0.031590321720133485, 'weight_class_1': 0.0028861121664764157, 'weight_class_2': 0.5252233797920103}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:38,867] Trial 1130 finished with value: 0.9480178155490845 and parameters: {'weight_class_0': 0.0167547298622969, 'weight_class_1': 0.3893452842082609, 'weight_class_2': 0.5355074369206282}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:38,885] Trial 1131 finished with value: 0.9496132714453146 and parameters: {'weight_class_0': 0.03298460576648952, 'weight_class_1': 0.5531111512637535, 'weight_class_2': 0.46034749988785695}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:38,926] Trial 1132 finished with value: 0.9495408249220431 and parameters: {'weight_class_0': 0.03497851976050723, 'weight_class_1': 0.6737629749875137, 'weight_class_2': 0.4973514684426634}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  38%|█████████████████████████████████████████████████▍                                                                                | 1141/3000 [00:24<00:46, 40.37it/s]

[I 2026-07-05 15:25:38,928] Trial 1133 finished with value: 0.9497886844774763 and parameters: {'weight_class_0': 0.0438595608121011, 'weight_class_1': 0.6522895017629772, 'weight_class_2': 0.5064850111031648}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:38,961] Trial 1135 finished with value: 0.9497001221039327 and parameters: {'weight_class_0': 0.038628235157713624, 'weight_class_1': 0.6878623655656846, 'weight_class_2': 0.48910727083930405}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:38,971] Trial 1134 finished with value: 0.9498022450685467 and parameters: {'weight_class_0': 0.042383208409745764, 'weight_class_1': 0.6810322674099272, 'weight_class_2': 0.4962094847029413}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:38,990] Trial 1136 finished with value: 0.9497676709300359 and parameters: {'weight_class_0': 0.03907191706500111, 'weight_class_1': 0.6781211968403361, 'weight_class_2': 0.48239853795237636}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:39,079] Trial 1138 finished with value: 0.9496690829648363 and parameters: {'weight_class_0': 0.041377842774860785, 'weight_class_1': 0.6997792967152734, 'weight_class_2': 0.41602688896168283}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:39,098] Trial 1137 finished with value: 0.9498099002011168 and parameters: {'weight_class_0': 0.04329338538722665, 'weight_class_1': 0.6995421638285149, 'weight_class_2': 0.4895344675654922}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:39,105] Trial 1139 finished with value: 0.9497384391519949 and parameters: {'weight_class_0': 0.042766031594260075, 'weight_class_1': 0.7035628044908012, 'weight_class_2': 0.4728311325058727}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:39,122] Trial 1140 finished with value: 0.9496824951343553 and parameters: {'weight_class_0': 0.04240035264898082, 'weight_class_1': 0.6623209486329847, 'weight_class_2': 0.4219216147392167}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:39,127] Trial 1141 finished with value: 0.9496979747129628 and parameters: {'weight_class_0': 0.04342867337604764, 'weight_class_1': 0.6812706572506912, 'weight_class_2': 0.4563159024814711}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  38%|█████████████████████████████████████████████████▉                                                                                | 1151/3000 [00:24<00:45, 40.95it/s]

[I 2026-07-05 15:25:39,186] Trial 1143 finished with value: 0.9496474899688522 and parameters: {'weight_class_0': 0.04534598870503191, 'weight_class_1': 0.9645503881244839, 'weight_class_2': 0.4465864570502141}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:39,192] Trial 1142 finished with value: 0.9497541509838549 and parameters: {'weight_class_0': 0.04051504180158485, 'weight_class_1': 0.6268663194246954, 'weight_class_2': 0.44220964263963874}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:39,207] Trial 1144 finished with value: 0.9497181529066089 and parameters: {'weight_class_0': 0.042904369575538885, 'weight_class_1': 0.7271897142718641, 'weight_class_2': 0.45145879357471935}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:39,228] Trial 1145 finished with value: 0.9491983621276914 and parameters: {'weight_class_0': 0.04304277923299606, 'weight_class_1': 0.9315254912597538, 'weight_class_2': 0.7882583295591443}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:39,247] Trial 1146 finished with value: 0.949651047176259 and parameters: {'weight_class_0': 0.06689662215434992, 'weight_class_1': 0.8992457127118139, 'weight_class_2': 0.6657291458538233}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:39,275] Trial 1148 finished with value: 0.9496144123877022 and parameters: {'weight_class_0': 0.04510111074329116, 'weight_class_1': 0.9717357855953734, 'weight_class_2': 0.4666484243754242}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:39,281] Trial 1147 finished with value: 0.9493316160890171 and parameters: {'weight_class_0': 0.04528166784552448, 'weight_class_1': 1.0472021444504245, 'weight_class_2': 0.7602815687839559}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:39,349] Trial 1149 finished with value: 0.9497659347846259 and parameters: {'weight_class_0': 0.06586792884637507, 'weight_class_1': 0.9477095119640622, 'weight_class_2': 0.7823870184991528}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:39,353] Trial 1150 finished with value: 0.9493328215826247 and parameters: {'weight_class_0': 0.06183439132311011, 'weight_class_1': 0.8401970541838238, 'weight_class_2': 0.47087566628114097}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:39,392] Trial 1151 finished with value: 0.9496477743141227 and parameters: {'weight_class_0': 0.06502326368388778, 'weight_class_1': 0.866743036681033, 'weight_class_2': 0.5813873665421199}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:25:39,412] Trial 1152 finished with value: 0.9496762540227756 and parameters: {'weight_class_0': 0.07156315040956905, 'weight_class_1': 0.9597753947761888, 'weight_class_2': 0.733147336412961}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:39,450] Trial 1154 finished with value: 0.9496784794087131 and parameters: {'weight_class_0': 0.061557079672834934, 'weight_class_1': 0.8968492435847987, 'weight_class_2': 0.5951426994711725}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:39,453] Trial 1153 finished with value: 0.9494708965134886 and parameters: {'weight_class_0': 0.05193138998795764, 'weight_class_1': 0.9900399366920127, 'weight_class_2': 0.7757948541861444}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:39,468] Trial 1155 finished with value: 0.9495249903814155 and parameters: {'weight_class_0': 0.0716840115387087, 'weight_class_1': 0.9423284355628393, 'weight_class_2': 0.6166224604721895}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:39,512] Trial 1156 finished with value: 0.9497634379778638 and parameters: {'weight_class_0': 0.05206077863157744, 'weight_class_1': 1.0494823874560568, 'weight_class_2': 0.574963741111909}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:39,579] Trial 1157 finished with value: 0.9494927635258117 and parameters: {'weight_class_0': 0.060617370903843705, 'weight_class_1': 0.6241708767801674, 'weight_class_2': 0.7587476084201346}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:39,580] Trial 1158 finished with value: 0.949557618922429 and parameters: {'weight_class_0': 0.06565938402954408, 'weight_class_1': 0.8047193927774527, 'weight_class_2': 0.5552016332292109}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  39%|██████████████████████████████████████████████████▌                                                                               | 1167/3000 [00:25<00:44, 40.78it/s]

[I 2026-07-05 15:25:39,593] Trial 1159 finished with value: 0.9497047085244485 and parameters: {'weight_class_0': 0.0522610393984026, 'weight_class_1': 0.815779895278964, 'weight_class_2': 0.5532275609524131}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:39,628] Trial 1160 finished with value: 0.949673888195323 and parameters: {'weight_class_0': 0.05330420854871366, 'weight_class_1': 0.5979243489693736, 'weight_class_2': 0.6173620966204246}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:39,640] Trial 1161 finished with value: 0.9496551155286482 and parameters: {'weight_class_0': 0.05764328893041065, 'weight_class_1': 0.6022014079564546, 'weight_class_2': 0.6576168142354424}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:39,662] Trial 1162 finished with value: 0.9495712343453198 and parameters: {'weight_class_0': 0.05399114653367301, 'weight_class_1': 0.5937868778844825, 'weight_class_2': 0.5571873784593081}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:39,668] Trial 1163 finished with value: 0.9496446972885102 and parameters: {'weight_class_0': 0.05528169437927741, 'weight_class_1': 0.5972441032471337, 'weight_class_2': 0.6492120219044029}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:39,715] Trial 1164 finished with value: 0.9497367538032718 and parameters: {'weight_class_0': 0.05090151886983797, 'weight_class_1': 0.5846828376083295, 'weight_class_2': 0.568137985873568}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:39,740] Trial 1165 finished with value: 0.9496861779211224 and parameters: {'weight_class_0': 0.05284543852363537, 'weight_class_1': 0.5871958864631253, 'weight_class_2': 0.6096773264186275}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:39,749] Trial 1166 finished with value: 0.9125395882666704 and parameters: {'weight_class_0': 0.051100136446886484, 'weight_class_1': 8.998474942684023, 'weight_class_2': 0.5762976940757067}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:39,823] Trial 1167 finished with value: 0.9481801684302819 and parameters: {'weight_class_0': 0.08972447615950696, 'weight_class_1': 0.5866191306514201, 'weight_class_2': 0.5302358261734499}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:25:39,830] Trial 1168 finished with value: 0.9497323001810841 and parameters: {'weight_class_0': 0.05092882864922865, 'weight_class_1': 0.6210680690909299, 'weight_class_2': 0.5935785562298432}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:39,841] Trial 1169 finished with value: 0.9484434461510595 and parameters: {'weight_class_0': 0.08887806918100256, 'weight_class_1': 0.5919741627585235, 'weight_class_2': 0.5906714028753465}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:39,879] Trial 1170 finished with value: 0.9496152326814621 and parameters: {'weight_class_0': 0.052191139116601074, 'weight_class_1': 0.5709124090959755, 'weight_class_2': 0.5749872310263909}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:39,928] Trial 1171 finished with value: 0.9498207287408991 and parameters: {'weight_class_0': 0.044958519556622736, 'weight_class_1': 0.6970517376864955, 'weight_class_2': 0.5194120000109177}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:39,947] Trial 1172 finished with value: 0.9498243164954548 and parameters: {'weight_class_0': 0.04714379890645568, 'weight_class_1': 0.7412571897237447, 'weight_class_2': 0.5556706567497792}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:39,969] Trial 1173 finished with value: 0.9497600915053089 and parameters: {'weight_class_0': 0.04461574701636814, 'weight_class_1': 0.7343208663722413, 'weight_class_2': 0.5494702966572176}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:39,981] Trial 1174 finished with value: 0.9498074478354722 and parameters: {'weight_class_0': 0.044184583936117294, 'weight_class_1': 0.7339043756739676, 'weight_class_2': 0.49920236454789374}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:40,031] Trial 1175 finished with value: 0.9483836598765935 and parameters: {'weight_class_0': 0.08640402867582146, 'weight_class_1': 0.670080979261485, 'weight_class_2': 0.49091503681935983}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  39%|███████████████████████████████████████████████████▎                                                                              | 1184/3000 [00:25<00:46, 38.74it/s]

[I 2026-07-05 15:25:40,040] Trial 1176 finished with value: 0.9496810532365333 and parameters: {'weight_class_0': 0.03959135370417996, 'weight_class_1': 0.7296349592548018, 'weight_class_2': 0.5155092168971342}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:40,051] Trial 1177 finished with value: 0.9497312645193139 and parameters: {'weight_class_0': 0.03952834392167414, 'weight_class_1': 0.7427943054415758, 'weight_class_2': 0.4871654445590053}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:40,077] Trial 1178 finished with value: 0.9497084841195989 and parameters: {'weight_class_0': 0.04396295881673586, 'weight_class_1': 0.7534320463611012, 'weight_class_2': 0.45669820329633365}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:40,120] Trial 1179 finished with value: 0.949813327436901 and parameters: {'weight_class_0': 0.03987121959966249, 'weight_class_1': 0.7265537438922949, 'weight_class_2': 0.45761481271640053}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:40,134] Trial 1180 finished with value: 0.9497643025168528 and parameters: {'weight_class_0': 0.040904127990890285, 'weight_class_1': 0.7824627482461114, 'weight_class_2': 0.4562292483095928}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:40,173] Trial 1182 finished with value: 0.9496972197932619 and parameters: {'weight_class_0': 0.04095008314071428, 'weight_class_1': 0.7250681361333892, 'weight_class_2': 0.4154147656409606}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:40,183] Trial 1181 finished with value: 0.949748844542024 and parameters: {'weight_class_0': 0.03731720521883353, 'weight_class_1': 0.7108201264477967, 'weight_class_2': 0.4526311704251257}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:40,207] Trial 1183 finished with value: 0.9490668296344685 and parameters: {'weight_class_0': 0.04314626339379861, 'weight_class_1': 0.764068626477167, 'weight_class_2': 0.8498815691824727}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:40,254] Trial 1184 finished with value: 0.9495837955378215 and parameters: {'weight_class_0': 0.07909734662708572, 'weight_class_1': 0.8208177509205214, 'weight_class_2': 0.740813944523385}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:25:40,263] Trial 1185 finished with value: 0.9497889295731238 and parameters: {'weight_class_0': 0.07472293569676787, 'weight_class_1': 1.2389288443593276, 'weight_class_2': 0.8357665394222239}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:40,279] Trial 1186 finished with value: 0.7798404749000452 and parameters: {'weight_class_0': 0.07817669375343136, 'weight_class_1': 0.0010001391999801502, 'weight_class_2': 0.7702694592419962}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:40,335] Trial 1188 finished with value: 0.9496299714008961 and parameters: {'weight_class_0': 0.07056715371584617, 'weight_class_1': 1.3725151197375889, 'weight_class_2': 0.947987829909354}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:40,337] Trial 1187 finished with value: 0.949449332669387 and parameters: {'weight_class_0': 0.047711694970102365, 'weight_class_1': 1.0494894274262134, 'weight_class_2': 0.7502109289573407}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:40,357] Trial 1189 finished with value: 0.9498326503669251 and parameters: {'weight_class_0': 0.0718738882993592, 'weight_class_1': 1.1281829016651705, 'weight_class_2': 0.832822989273923}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:40,382] Trial 1190 finished with value: 0.9494432469517081 and parameters: {'weight_class_0': 0.047546544596552574, 'weight_class_1': 1.099601165178753, 'weight_class_2': 0.6717451871877539}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:40,438] Trial 1192 finished with value: 0.9496390369020506 and parameters: {'weight_class_0': 0.0645177410314548, 'weight_class_1': 1.3125881521306524, 'weight_class_2': 0.5923963071412607}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:40,455] Trial 1193 finished with value: 0.9496743682348207 and parameters: {'weight_class_0': 0.07328044342071606, 'weight_class_1': 1.0604942739697023, 'weight_class_2': 0.694249881123167}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  40%|████████████████████████████████████████████████████                                                                              | 1200/3000 [00:26<00:44, 40.86it/s]

[I 2026-07-05 15:25:40,456] Trial 1191 finished with value: 0.9496227853775393 and parameters: {'weight_class_0': 0.07719627659054415, 'weight_class_1': 1.1659694143165653, 'weight_class_2': 0.6790097242766181}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:40,468] Trial 1194 finished with value: 0.9494495210857359 and parameters: {'weight_class_0': 0.0477873757169211, 'weight_class_1': 1.063406682903717, 'weight_class_2': 0.7479107186249122}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:40,503] Trial 1195 finished with value: 0.9496743836809095 and parameters: {'weight_class_0': 0.0711439270681673, 'weight_class_1': 1.1472425712452463, 'weight_class_2': 0.9025989643117736}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:40,520] Trial 1196 finished with value: 0.9492147577152078 and parameters: {'weight_class_0': 0.12440588873177012, 'weight_class_1': 0.9909149313302739, 'weight_class_2': 1.2861487767984703}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:40,542] Trial 1198 finished with value: 0.9497211459928709 and parameters: {'weight_class_0': 0.11063374608526635, 'weight_class_1': 1.9412630798006651, 'weight_class_2': 1.0479276941283282}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:40,563] Trial 1197 finished with value: 0.9488883183469974 and parameters: {'weight_class_0': 0.11314329020645775, 'weight_class_1': 1.196480849851677, 'weight_class_2': 0.7421704386359128}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:40,625] Trial 1199 finished with value: 0.9496687320586951 and parameters: {'weight_class_0': 0.10093788817474697, 'weight_class_1': 1.2237904871516838, 'weight_class_2': 1.0039864182533824}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:40,642] Trial 1200 finished with value: 0.9488741783406951 and parameters: {'weight_class_0': 0.11945999875227614, 'weight_class_1': 1.5418440795829014, 'weight_class_2': 0.7419860415207357}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  40%|████████████████████████████████████████████████████▍                                                                             | 1210/3000 [00:26<00:44, 39.85it/s]

[I 2026-07-05 15:25:40,695] Trial 1202 finished with value: 0.9480008520547702 and parameters: {'weight_class_0': 0.05692562909919315, 'weight_class_1': 2.332075411549968, 'weight_class_2': 1.3093607920695138}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:40,714] Trial 1201 finished with value: 0.9494454779350084 and parameters: {'weight_class_0': 0.0990562326321756, 'weight_class_1': 1.167156442353224, 'weight_class_2': 0.8036028441835567}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:40,722] Trial 1203 finished with value: 0.9498199016137594 and parameters: {'weight_class_0': 0.07691439298887333, 'weight_class_1': 1.3303962913057414, 'weight_class_2': 0.8738616682001609}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:40,775] Trial 1204 finished with value: 0.949614728233751 and parameters: {'weight_class_0': 0.10948410037290646, 'weight_class_1': 1.4967640591952032, 'weight_class_2': 0.9905335720851173}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:40,783] Trial 1205 finished with value: 0.9495799762877537 and parameters: {'weight_class_0': 0.10096357761183004, 'weight_class_1': 1.7370325211549253, 'weight_class_2': 0.846329371230815}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:40,785] Trial 1206 finished with value: 0.9495769821527794 and parameters: {'weight_class_0': 0.09533449955422489, 'weight_class_1': 1.8486358009867974, 'weight_class_2': 0.8044563861386791}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:40,809] Trial 1208 finished with value: 0.9493112648421286 and parameters: {'weight_class_0': 0.09336666019729052, 'weight_class_1': 1.1876987866402882, 'weight_class_2': 0.7134183947668118}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:40,812] Trial 1207 finished with value: 0.949484208232963 and parameters: {'weight_class_0': 0.09375555696319625, 'weight_class_1': 1.9382387811141764, 'weight_class_2': 0.7848915904417318}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:40,850] Trial 1209 finished with value: 0.9495073452268783 and parameters: {'weight_class_0': 0.08244562816420162, 'weight_class_1': 1.5233143560239737, 'weight_class_2': 1.2769712883126454}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:40,890] Trial 1210 finished with value: 0.9496740443421121 and parameters: {'weight_class_0': 0.0957962080531044, 'weight_class_1': 1.307247837579273, 'weight_class_2': 0.9126364719231345}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:25:40,894] Trial 1211 finished with value: 0.9497010614666204 and parameters: {'weight_class_0': 0.09892334222028897, 'weight_class_1': 1.8263859355925611, 'weight_class_2': 1.2386310757235441}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:40,975] Trial 1212 finished with value: 0.9495424186313103 and parameters: {'weight_class_0': 0.07022183310713671, 'weight_class_1': 1.863893570965452, 'weight_class_2': 0.8756817509571617}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:40,978] Trial 1214 finished with value: 0.9497152539399539 and parameters: {'weight_class_0': 0.08722646252199484, 'weight_class_1': 1.3584137074604081, 'weight_class_2': 1.0924945696532404}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:40,984] Trial 1213 finished with value: 0.949361022050598 and parameters: {'weight_class_0': 0.0917116359575014, 'weight_class_1': 1.9408337973748488, 'weight_class_2': 1.558534183308417}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:41,037] Trial 1215 finished with value: 0.9489100515924008 and parameters: {'weight_class_0': 0.05940060935783329, 'weight_class_1': 1.5717682549251988, 'weight_class_2': 1.1963819863305092}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:41,053] Trial 1216 finished with value: 0.9483100353875958 and parameters: {'weight_class_0': 0.056820070815780235, 'weight_class_1': 1.5300888717125247, 'weight_class_2': 1.5797592588380263}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:41,095] Trial 1217 finished with value: 0.9487884598591599 and parameters: {'weight_class_0': 0.06428525138156922, 'weight_class_1': 1.6209799772857518, 'weight_class_2': 1.3786098246479417}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:41,112] Trial 1218 finished with value: 0.9492352453733304 and parameters: {'weight_class_0': 0.0627155492844441, 'weight_class_1': 1.5301247204149202, 'weight_class_2': 1.1031991182265883}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  41%|█████████████████████████████████████████████████████▏                                                                            | 1226/3000 [00:26<00:45, 38.67it/s]

[I 2026-07-05 15:25:41,127] Trial 1219 finished with value: 0.9495550844190349 and parameters: {'weight_class_0': 0.1481285607435481, 'weight_class_1': 1.4389685701744999, 'weight_class_2': 1.462338858387692}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:41,153] Trial 1221 finished with value: 0.9476668183107835 and parameters: {'weight_class_0': 0.055911378737208146, 'weight_class_1': 0.9266402616836665, 'weight_class_2': 1.8427670142042667}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:41,160] Trial 1220 finished with value: 0.9482080576220685 and parameters: {'weight_class_0': 0.06325608516118567, 'weight_class_1': 0.926577731290678, 'weight_class_2': 1.5966619786380605}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:41,191] Trial 1222 finished with value: 0.9484390915876325 and parameters: {'weight_class_0': 0.0646758347489179, 'weight_class_1': 2.874868873034533, 'weight_class_2': 0.6354031321781479}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:41,245] Trial 1223 finished with value: 0.949723643408699 and parameters: {'weight_class_0': 0.06090263670729344, 'weight_class_1': 0.8953095331181727, 'weight_class_2': 0.6521929534876132}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:41,250] Trial 1224 finished with value: 0.9493604980555069 and parameters: {'weight_class_0': 0.058970747142484195, 'weight_class_1': 1.3792721474625997, 'weight_class_2': 0.939782075543123}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:41,281] Trial 1226 finished with value: 0.9494409877238107 and parameters: {'weight_class_0': 0.06785676229683439, 'weight_class_1': 0.9864174338846348, 'weight_class_2': 0.9875884390922082}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:41,302] Trial 1225 finished with value: 0.8173251891217584 and parameters: {'weight_class_0': 0.15303198751318275, 'weight_class_1': 0.0017993811459738034, 'weight_class_2': 0.6566912477453203}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  41%|█████████████████████████████████████████████████████▌                                                                            | 1235/3000 [00:26<00:43, 40.48it/s]

[I 2026-07-05 15:25:41,329] Trial 1227 finished with value: 0.9494421675253802 and parameters: {'weight_class_0': 0.06431113805587226, 'weight_class_1': 0.8797147104669263, 'weight_class_2': 0.9084423028016382}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:41,343] Trial 1228 finished with value: 0.9496121684080142 and parameters: {'weight_class_0': 0.07513034930149359, 'weight_class_1': 0.8497245348868386, 'weight_class_2': 0.9267135957031892}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:41,358] Trial 1229 finished with value: 0.9497201959928617 and parameters: {'weight_class_0': 0.06297505496692721, 'weight_class_1': 1.1077834386518022, 'weight_class_2': 0.622534351914052}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:41,438] Trial 1231 finished with value: 0.9493347982653267 and parameters: {'weight_class_0': 0.062135989804856975, 'weight_class_1': 0.9018223415711579, 'weight_class_2': 1.03287011934166}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:41,445] Trial 1230 finished with value: 0.9478075734726685 and parameters: {'weight_class_0': 0.07310857932925371, 'weight_class_1': 2.3293279957361026, 'weight_class_2': 2.516837119394728}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:41,449] Trial 1232 finished with value: 0.943367675638076 and parameters: {'weight_class_0': 0.07356079798954322, 'weight_class_1': 0.8782270655909739, 'weight_class_2': 6.558754853253954}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:41,462] Trial 1233 finished with value: 0.9489451755497625 and parameters: {'weight_class_0': 0.05109684376855219, 'weight_class_1': 0.9034008313029255, 'weight_class_2': 1.047872936893141}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:41,489] Trial 1234 finished with value: 0.9495039517712831 and parameters: {'weight_class_0': 0.04739241144248078, 'weight_class_1': 1.096918142939701, 'weight_class_2': 0.6408575885631634}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:41,534] Trial 1236 finished with value: 0.8448854962640143 and parameters: {'weight_class_0': 0.04936285202323925, 'weight_class_1': 0.0033245052930329123, 'weight_class_2': 1.0469051046919666}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  41%|█████████████████████████████████████████████████████▉                                                                            | 1244/3000 [00:27<00:43, 40.04it/s]

[I 2026-07-05 15:25:41,536] Trial 1235 finished with value: 0.8667291327188581 and parameters: {'weight_class_0': 0.05033521526533809, 'weight_class_1': 0.0032273410029204515, 'weight_class_2': 0.5871025364435929}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:41,560] Trial 1237 finished with value: 0.9496799902939657 and parameters: {'weight_class_0': 0.04860685876030361, 'weight_class_1': 1.0886831690719692, 'weight_class_2': 0.5880842049507745}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:41,608] Trial 1238 finished with value: 0.8758753362081354 and parameters: {'weight_class_0': 0.048740089954507744, 'weight_class_1': 0.004648519979644542, 'weight_class_2': 0.5662123871696122}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:41,633] Trial 1239 finished with value: 0.7764174092311741 and parameters: {'weight_class_0': 0.051206359675931595, 'weight_class_1': 0.004414558242604934, 'weight_class_2': 3.5942508863000873}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:41,660] Trial 1240 finished with value: 0.868021235218233 and parameters: {'weight_class_0': 0.04555134125514293, 'weight_class_1': 0.0031296789855872476, 'weight_class_2': 0.5479949940798006}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:41,679] Trial 1241 finished with value: 0.94969479688789 and parameters: {'weight_class_0': 0.053683973350025914, 'weight_class_1': 0.8428176345461842, 'weight_class_2': 0.5433558125179214}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:41,693] Trial 1242 finished with value: 0.9497435453809326 and parameters: {'weight_class_0': 0.048735720512817035, 'weight_class_1': 1.0903128799299513, 'weight_class_2': 0.542838165392039}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:41,739] Trial 1243 finished with value: 0.9497617891901576 and parameters: {'weight_class_0': 0.04875348349841332, 'weight_class_1': 1.1031045834845685, 'weight_class_2': 0.5585466488852315}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:41,758] Trial 1244 finished with value: 0.8203590375680179 and parameters: {'weight_class_0': 0.04889436169618525, 'weight_class_1': 0.0046960952947417865, 'weight_class_2': 0.008575856059781532}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  42%|██████████████████████████████████████████████████████▎                                                                           | 1252/3000 [00:27<00:45, 38.75it/s]

[I 2026-07-05 15:25:41,814] Trial 1246 finished with value: 0.9495831680990164 and parameters: {'weight_class_0': 0.047068932925199, 'weight_class_1': 1.193835432423005, 'weight_class_2': 0.5150640430099315}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:41,821] Trial 1245 finished with value: 0.8786857979436723 and parameters: {'weight_class_0': 0.046333219419873346, 'weight_class_1': 0.005356758703160384, 'weight_class_2': 0.5124446243676861}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:41,832] Trial 1247 finished with value: 0.9497528368289753 and parameters: {'weight_class_0': 0.045714436593537376, 'weight_class_1': 0.7665372588645674, 'weight_class_2': 0.49370542817942104}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:41,853] Trial 1248 finished with value: 0.9496898862662757 and parameters: {'weight_class_0': 0.0433609497161978, 'weight_class_1': 0.8076310721182846, 'weight_class_2': 0.5555488026342026}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:41,894] Trial 1249 finished with value: 0.9497144077842702 and parameters: {'weight_class_0': 0.03920641794667511, 'weight_class_1': 0.7860249264563729, 'weight_class_2': 0.48225923810308374}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:41,921] Trial 1251 finished with value: 0.9496948371423385 and parameters: {'weight_class_0': 0.03921536383777728, 'weight_class_1': 0.7609187442608832, 'weight_class_2': 0.4958377798622539}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:41,932] Trial 1250 finished with value: 0.8911711259656517 and parameters: {'weight_class_0': 0.040223145312552416, 'weight_class_1': 0.8009958325091862, 'weight_class_2': 0.008011883857155004}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:41,954] Trial 1253 finished with value: 0.9485427004746811 and parameters: {'weight_class_0': 0.08431369220256364, 'weight_class_1': 0.780838959977735, 'weight_class_2': 0.48349274388706054}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:25:41,960] Trial 1252 finished with value: 0.9491484947864164 and parameters: {'weight_class_0': 0.03815807905712155, 'weight_class_1': 0.8040748577666116, 'weight_class_2': 0.719613823560032}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:42,014] Trial 1254 finished with value: 0.9498051412751192 and parameters: {'weight_class_0': 0.03963622333754826, 'weight_class_1': 0.7322133384623571, 'weight_class_2': 0.45287712690352927}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:42,042] Trial 1256 finished with value: 0.9490408587241399 and parameters: {'weight_class_0': 0.03818946131038674, 'weight_class_1': 0.784078496560887, 'weight_class_2': 0.7627114260758376}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:42,048] Trial 1255 finished with value: 0.9491161066842847 and parameters: {'weight_class_0': 0.03876903615330178, 'weight_class_1': 0.7668922107713838, 'weight_class_2': 0.7541840801886442}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:42,108] Trial 1257 finished with value: 0.9492717098204534 and parameters: {'weight_class_0': 0.03733726015201036, 'weight_class_1': 0.7734465901724872, 'weight_class_2': 0.6674218046034248}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:42,109] Trial 1258 finished with value: 0.9489107700871934 and parameters: {'weight_class_0': 0.03791638628137792, 'weight_class_1': 0.7453262499069978, 'weight_class_2': 0.7964165401160214}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:42,116] Trial 1259 finished with value: 0.9495716768653187 and parameters: {'weight_class_0': 0.07996186732706916, 'weight_class_1': 0.7390676626627747, 'weight_class_2': 0.7409806380616512}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:42,176] Trial 1260 finished with value: 0.9492101516749655 and parameters: {'weight_class_0': 0.03691826897102452, 'weight_class_1': 0.7264665730154694, 'weight_class_2': 0.6943359684981437}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:42,190] Trial 1262 finished with value: 0.9485707255178409 and parameters: {'weight_class_0': 0.037819604324129584, 'weight_class_1': 1.2963416744901228, 'weight_class_2': 0.7626449950069673}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  42%|███████████████████████████████████████████████████████                                                                           | 1270/3000 [00:27<00:42, 40.81it/s]

[I 2026-07-05 15:25:42,192] Trial 1261 finished with value: 0.8533370460137893 and parameters: {'weight_class_0': 0.08386995330996992, 'weight_class_1': 1.2653492639925437, 'weight_class_2': 0.0036428727508916064}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:42,239] Trial 1263 finished with value: 0.8319114442464688 and parameters: {'weight_class_0': 0.08384062525142699, 'weight_class_1': 1.3246113316762973, 'weight_class_2': 0.0029675997762931778}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:42,269] Trial 1264 finished with value: 0.9495628823883592 and parameters: {'weight_class_0': 0.05323055677061118, 'weight_class_1': 1.39052794214898, 'weight_class_2': 0.6652154041815621}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:42,289] Trial 1265 finished with value: 0.9494801445276346 and parameters: {'weight_class_0': 0.07844288601729722, 'weight_class_1': 1.0650472507431585, 'weight_class_2': 0.6549490621896275}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:42,306] Trial 1266 finished with value: 0.9497647528446064 and parameters: {'weight_class_0': 0.05763719504276934, 'weight_class_1': 1.2600253413504325, 'weight_class_2': 0.6662386174229977}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:42,329] Trial 1268 finished with value: 0.9490383414361828 and parameters: {'weight_class_0': 0.05694523254149689, 'weight_class_1': 1.2787847621676414, 'weight_class_2': 0.40669495765900326}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:42,338] Trial 1267 finished with value: 0.9497794498115292 and parameters: {'weight_class_0': 0.059618353090951474, 'weight_class_1': 1.2240993764090613, 'weight_class_2': 0.686582181755909}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:42,398] Trial 1270 finished with value: 0.9489609625924352 and parameters: {'weight_class_0': 0.059928674554677985, 'weight_class_1': 1.3400684277943917, 'weight_class_2': 0.4150120465245081}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:42,419] Trial 1269 finished with value: 0.9493398405178675 and parameters: {'weight_class_0': 0.05852962177851263, 'weight_class_1': 1.0136409980553995, 'weight_class_2': 0.43164301442452824}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:25:42,465] Trial 1272 finished with value: 0.9493595633491193 and parameters: {'weight_class_0': 0.057141309432905706, 'weight_class_1': 1.126833970214804, 'weight_class_2': 0.4462449759508799}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:42,475] Trial 1271 finished with value: 0.9490832798545895 and parameters: {'weight_class_0': 0.06036140244485319, 'weight_class_1': 1.0824974648215173, 'weight_class_2': 0.4128829313572404}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:42,487] Trial 1273 finished with value: 0.9494967619801575 and parameters: {'weight_class_0': 0.053299334397694326, 'weight_class_1': 1.0429760362036709, 'weight_class_2': 0.4390910114632915}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:42,537] Trial 1274 finished with value: 0.9491144219282689 and parameters: {'weight_class_0': 0.06250864688452862, 'weight_class_1': 0.9534311509776348, 'weight_class_2': 0.43791084013930626}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:42,567] Trial 1275 finished with value: 0.9493174087038576 and parameters: {'weight_class_0': 0.05943512653594202, 'weight_class_1': 1.0435163717689282, 'weight_class_2': 0.4427212450512175}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:42,570] Trial 1276 finished with value: 0.949165752524526 and parameters: {'weight_class_0': 0.05861045352653584, 'weight_class_1': 0.8830119571938769, 'weight_class_2': 0.4240152462733498}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:42,603] Trial 1277 finished with value: 0.9492366129532576 and parameters: {'weight_class_0': 0.058682043584185266, 'weight_class_1': 0.9370702670273804, 'weight_class_2': 0.428438651748889}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:42,642] Trial 1278 finished with value: 0.9490896013259255 and parameters: {'weight_class_0': 0.06612836917221966, 'weight_class_1': 0.9842345842873363, 'weight_class_2': 0.45141818098921616}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  43%|███████████████████████████████████████████████████████▊                                                                          | 1287/3000 [00:28<00:44, 38.55it/s]

[I 2026-07-05 15:25:42,650] Trial 1279 finished with value: 0.9496451326402714 and parameters: {'weight_class_0': 0.04280781085723563, 'weight_class_1': 0.965170528389519, 'weight_class_2': 0.4494677543337196}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:42,654] Trial 1280 finished with value: 0.9496740690399611 and parameters: {'weight_class_0': 0.042731500298514184, 'weight_class_1': 0.9434749257873876, 'weight_class_2': 0.451018157306252}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:42,712] Trial 1281 finished with value: 0.9496917627581182 and parameters: {'weight_class_0': 0.04498101555103723, 'weight_class_1': 0.8985385283562456, 'weight_class_2': 0.468926813587292}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:42,715] Trial 1282 finished with value: 0.9497696951933379 and parameters: {'weight_class_0': 0.043717891189645315, 'weight_class_1': 0.8931988340290841, 'weight_class_2': 0.4858298159170817}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:42,771] Trial 1283 finished with value: 0.9496407745281051 and parameters: {'weight_class_0': 0.041795041792188604, 'weight_class_1': 0.9711608913304273, 'weight_class_2': 0.5194482308208876}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:42,797] Trial 1286 finished with value: 0.949732209965354 and parameters: {'weight_class_0': 0.044124275859589085, 'weight_class_1': 0.6589678056848818, 'weight_class_2': 0.5231585583324836}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:42,810] Trial 1284 finished with value: 0.9497505071923783 and parameters: {'weight_class_0': 0.04336416031826595, 'weight_class_1': 0.9463394966826093, 'weight_class_2': 0.5098525743328471}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:42,814] Trial 1285 finished with value: 0.9497263509189922 and parameters: {'weight_class_0': 0.04322617598259597, 'weight_class_1': 0.6525608978733117, 'weight_class_2': 0.5318295259889667}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:42,838] Trial 1287 finished with value: 0.9496117038730496 and parameters: {'weight_class_0': 0.0440123485630087, 'weight_class_1': 0.6529508125578106, 'weight_class_2': 0.5730226115137356}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  43%|████████████████████████████████████████████████████████▏                                                                         | 1296/3000 [00:28<00:42, 39.84it/s]

[I 2026-07-05 15:25:42,872] Trial 1288 finished with value: 0.9496884122378638 and parameters: {'weight_class_0': 0.04417289332306378, 'weight_class_1': 0.7068716626285848, 'weight_class_2': 0.5569637588227458}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:42,885] Trial 1289 finished with value: 0.949634174694916 and parameters: {'weight_class_0': 0.0435996273883062, 'weight_class_1': 0.664305404189298, 'weight_class_2': 0.5687286140876828}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:42,913] Trial 1290 finished with value: 0.9494487060558168 and parameters: {'weight_class_0': 0.03551292997517038, 'weight_class_1': 0.677381766990793, 'weight_class_2': 0.5364222128934301}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:42,966] Trial 1291 finished with value: 0.9495051905551689 and parameters: {'weight_class_0': 0.037294462079457455, 'weight_class_1': 0.6474092782754455, 'weight_class_2': 0.576438307421188}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:42,985] Trial 1292 finished with value: 0.9494394273835457 and parameters: {'weight_class_0': 0.03714839329698754, 'weight_class_1': 0.655522299945121, 'weight_class_2': 0.5946447056512196}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:42,999] Trial 1293 finished with value: 0.9493870050914587 and parameters: {'weight_class_0': 0.03605370187800641, 'weight_class_1': 0.6474680535532354, 'weight_class_2': 0.6098674892038922}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:43,040] Trial 1294 finished with value: 0.9405275318456119 and parameters: {'weight_class_0': 0.18699312639519872, 'weight_class_1': 0.7002720867095087, 'weight_class_2': 0.5618793182617676}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:43,076] Trial 1295 finished with value: 0.9492658244797695 and parameters: {'weight_class_0': 0.07442803695976613, 'weight_class_1': 0.6705804028916584, 'weight_class_2': 0.5801128522525092}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:43,079] Trial 1296 finished with value: 0.9483048682670923 and parameters: {'weight_class_0': 0.034903725763964076, 'weight_class_1': 0.643314202640111, 'weight_class_2': 0.9573747229711295}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  44%|████████████████████████████████████████████████████████▌                                                                         | 1305/3000 [00:28<00:43, 38.57it/s]

[I 2026-07-05 15:25:43,099] Trial 1297 finished with value: 0.9493631070978169 and parameters: {'weight_class_0': 0.03488387554747101, 'weight_class_1': 0.6575188164355694, 'weight_class_2': 0.6000569645138747}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:43,147] Trial 1298 finished with value: 0.9484295009586324 and parameters: {'weight_class_0': 0.03684098248924044, 'weight_class_1': 0.6610308805083898, 'weight_class_2': 0.9309120646773764}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:43,190] Trial 1299 finished with value: 0.9481055181383491 and parameters: {'weight_class_0': 0.03472541511905808, 'weight_class_1': 0.5865876686933624, 'weight_class_2': 0.9824985739605998}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:43,222] Trial 1300 finished with value: 0.948425753363856 and parameters: {'weight_class_0': 0.03542309986657229, 'weight_class_1': 0.631294260725033, 'weight_class_2': 0.8899917368413475}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:43,228] Trial 1301 finished with value: 0.9497467391453318 and parameters: {'weight_class_0': 0.03511794597340617, 'weight_class_1': 0.639520431700787, 'weight_class_2': 0.38768536253408453}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:43,242] Trial 1302 finished with value: 0.9472550802716272 and parameters: {'weight_class_0': 0.035195681741506696, 'weight_class_1': 1.6823084094833083, 'weight_class_2': 0.9853745926772017}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:43,251] Trial 1303 finished with value: 0.9483136026556388 and parameters: {'weight_class_0': 0.06929602035854693, 'weight_class_1': 0.5567195192655201, 'weight_class_2': 0.3807483383169974}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:43,278] Trial 1305 finished with value: 0.8142587021657457 and parameters: {'weight_class_0': 0.07503437675020487, 'weight_class_1': 0.5695217082079543, 'weight_class_2': 0.0010837865415020181}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:43,304] Trial 1304 finished with value: 0.9483508286685988 and parameters: {'weight_class_0': 0.034064134647736485, 'weight_class_1': 1.6145971844298834, 'weight_class_2': 0.4051267982049964}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:25:43,316] Trial 1306 finished with value: 0.9472296468155648 and parameters: {'weight_class_0': 0.03409772515394797, 'weight_class_1': 1.7241664493893973, 'weight_class_2': 0.8690129635749184}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:43,362] Trial 1307 finished with value: 0.9497858408045587 and parameters: {'weight_class_0': 0.07492392325421389, 'weight_class_1': 1.6600301853402706, 'weight_class_2': 0.8592149374328034}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:43,400] Trial 1308 finished with value: 0.9481908915061245 and parameters: {'weight_class_0': 0.07319285808785782, 'weight_class_1': 0.5619341276819381, 'weight_class_2': 0.393150964059412}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:43,427] Trial 1309 finished with value: 0.9491425205412266 and parameters: {'weight_class_0': 0.07970134398966856, 'weight_class_1': 0.5987642836752253, 'weight_class_2': 0.8031924231714288}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:43,430] Trial 1310 finished with value: 0.9496946881165734 and parameters: {'weight_class_0': 0.07238349032426439, 'weight_class_1': 1.5974236396132189, 'weight_class_2': 0.7703186201849727}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:43,509] Trial 1311 finished with value: 0.949729384477862 and parameters: {'weight_class_0': 0.08047249988080209, 'weight_class_1': 1.5909867783225644, 'weight_class_2': 0.844222244706544}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:43,520] Trial 1312 finished with value: 0.9483410239139217 and parameters: {'weight_class_0': 0.07336709230701832, 'weight_class_1': 0.8206705089798991, 'weight_class_2': 0.38833677289163243}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  44%|█████████████████████████████████████████████████████████▏                                                                        | 1320/3000 [00:29<00:45, 37.21it/s]

[I 2026-07-05 15:25:43,527] Trial 1314 finished with value: 0.9493486922677642 and parameters: {'weight_class_0': 0.050837757099489296, 'weight_class_1': 0.8175780318857265, 'weight_class_2': 0.3879990342145223}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:43,531] Trial 1313 finished with value: 0.9494963022775673 and parameters: {'weight_class_0': 0.052142205172249045, 'weight_class_1': 0.8009567792953491, 'weight_class_2': 0.764288548851063}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:43,560] Trial 1315 finished with value: 0.9493844782105056 and parameters: {'weight_class_0': 0.05188370406575003, 'weight_class_1': 0.8140883091078168, 'weight_class_2': 0.8334261376811959}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:43,579] Trial 1316 finished with value: 0.9481837169868762 and parameters: {'weight_class_0': 0.04916551271782602, 'weight_class_1': 2.3002467256871446, 'weight_class_2': 0.7674425270625365}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:43,620] Trial 1318 finished with value: 0.9485460270248427 and parameters: {'weight_class_0': 0.12130888874788069, 'weight_class_1': 0.8863785230127015, 'weight_class_2': 0.7419682276658897}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:43,664] Trial 1317 finished with value: 0.9492860478027888 and parameters: {'weight_class_0': 0.05281763902103304, 'weight_class_1': 0.8204932156625442, 'weight_class_2': 0.3869123530242661}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:43,671] Trial 1319 finished with value: 0.9495498192519051 and parameters: {'weight_class_0': 0.05249250219204569, 'weight_class_1': 0.8230368701386366, 'weight_class_2': 0.7314028183417433}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:43,738] Trial 1320 finished with value: 0.943908000942456 and parameters: {'weight_class_0': 0.12393445790540987, 'weight_class_1': 0.8195676924021231, 'weight_class_2': 0.3874085267886097}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  44%|█████████████████████████████████████████████████████████▌                                                                        | 1328/3000 [00:29<00:48, 34.69it/s]

[I 2026-07-05 15:25:43,771] Trial 1321 finished with value: 0.9496698165355566 and parameters: {'weight_class_0': 0.05481042882343953, 'weight_class_1': 0.764133298378641, 'weight_class_2': 0.6841246864707998}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:43,781] Trial 1322 finished with value: 0.8859997028747731 and parameters: {'weight_class_0': 0.050779342222600686, 'weight_class_1': 0.8108544790586641, 'weight_class_2': 0.005425479604041189}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:43,829] Trial 1323 finished with value: 0.9479240475973371 and parameters: {'weight_class_0': 0.04932443956395097, 'weight_class_1': 0.5208866796968026, 'weight_class_2': 1.2041270629733647}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:43,838] Trial 1324 finished with value: 0.9469557050394247 and parameters: {'weight_class_0': 0.04439109513661577, 'weight_class_1': 2.384347539494315, 'weight_class_2': 1.188698430864892}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:43,879] Trial 1325 finished with value: 0.9462306039534186 and parameters: {'weight_class_0': 0.1177705938325786, 'weight_class_1': 0.8381219702518303, 'weight_class_2': 0.4547301846794276}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:43,904] Trial 1327 finished with value: 0.9496051462933229 and parameters: {'weight_class_0': 0.05253434877309726, 'weight_class_1': 0.5223840147706549, 'weight_class_2': 0.5041393105503507}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:43,924] Trial 1326 finished with value: 0.9492665226588661 and parameters: {'weight_class_0': 0.04801946265127209, 'weight_class_1': 0.524946081967857, 'weight_class_2': 0.6769515603539978}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:43,928] Trial 1328 finished with value: 0.9477818115394783 and parameters: {'weight_class_0': 0.04457628827633359, 'weight_class_1': 0.5272561767676313, 'weight_class_2': 1.226975095361278}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  45%|█████████████████████████████████████████████████████████▉                                                                        | 1336/3000 [00:29<00:47, 34.89it/s]

[I 2026-07-05 15:25:43,979] Trial 1329 finished with value: 0.9494268321198835 and parameters: {'weight_class_0': 0.04502972732189902, 'weight_class_1': 1.1133947036666056, 'weight_class_2': 0.6267504128614346}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:44,029] Trial 1330 finished with value: 0.949678769110046 and parameters: {'weight_class_0': 0.04416747861338572, 'weight_class_1': 0.5468641498835858, 'weight_class_2': 0.48642423635503007}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:44,063] Trial 1331 finished with value: 0.949745801003638 and parameters: {'weight_class_0': 0.04425281848752865, 'weight_class_1': 0.5233416347151736, 'weight_class_2': 0.5043902498913831}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:44,090] Trial 1332 finished with value: 0.9497515392176359 and parameters: {'weight_class_0': 0.04241859734291117, 'weight_class_1': 0.520730470731248, 'weight_class_2': 0.4809719705821064}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:44,092] Trial 1333 finished with value: 0.9497532978919948 and parameters: {'weight_class_0': 0.04254660006801847, 'weight_class_1': 0.5008209949753287, 'weight_class_2': 0.48813381258158045}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:44,115] Trial 1334 finished with value: 0.9495108293190951 and parameters: {'weight_class_0': 0.03967384516982031, 'weight_class_1': 1.0929517388425234, 'weight_class_2': 0.49103750411110586}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:44,130] Trial 1335 finished with value: 0.948687110271889 and parameters: {'weight_class_0': 0.031348336980850836, 'weight_class_1': 1.092003160829028, 'weight_class_2': 0.5974639518756588}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:44,177] Trial 1336 finished with value: 0.9490619361162556 and parameters: {'weight_class_0': 0.03167116251719477, 'weight_class_1': 0.5324386981263616, 'weight_class_2': 0.6241671224744453}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  45%|██████████████████████████████████████████████████████████▏                                                                       | 1344/3000 [00:29<00:47, 35.10it/s]

[I 2026-07-05 15:25:44,235] Trial 1337 finished with value: 0.9485122553928823 and parameters: {'weight_class_0': 0.03186146875443116, 'weight_class_1': 1.1474572727483239, 'weight_class_2': 0.6404438916941401}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:44,237] Trial 1338 finished with value: 0.948852777110394 and parameters: {'weight_class_0': 0.03171141381184385, 'weight_class_1': 1.1540163049692476, 'weight_class_2': 0.46998000465338763}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:44,254] Trial 1339 finished with value: 0.9491213122779162 and parameters: {'weight_class_0': 0.03360979433878447, 'weight_class_1': 1.0829770958864875, 'weight_class_2': 0.48903694223605915}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:44,296] Trial 1340 finished with value: 0.9490743780077681 and parameters: {'weight_class_0': 0.03136838165438511, 'weight_class_1': 1.033495044954251, 'weight_class_2': 0.49137673194205345}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:44,342] Trial 1342 finished with value: 0.9492825213847631 and parameters: {'weight_class_0': 0.031310779659966745, 'weight_class_1': 1.012636737324617, 'weight_class_2': 0.3754425758625427}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:44,373] Trial 1343 finished with value: 0.9492063894536121 and parameters: {'weight_class_0': 0.03368269838353123, 'weight_class_1': 1.13233612780041, 'weight_class_2': 0.36902907270950114}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:44,377] Trial 1341 finished with value: 0.9483387531008572 and parameters: {'weight_class_0': 0.03048140652004431, 'weight_class_1': 1.1752628344417688, 'weight_class_2': 0.6222698004329683}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:44,390] Trial 1344 finished with value: 0.948957257049321 and parameters: {'weight_class_0': 0.03158609979339118, 'weight_class_1': 0.6968474711071007, 'weight_class_2': 0.6525491296114712}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  45%|██████████████████████████████████████████████████████████▌                                                                       | 1352/3000 [00:30<00:45, 36.48it/s]

[I 2026-07-05 15:25:44,454] Trial 1345 finished with value: 0.9489137776316722 and parameters: {'weight_class_0': 0.06267482436698182, 'weight_class_1': 0.7199509611787405, 'weight_class_2': 0.3883303041793893}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:44,479] Trial 1347 finished with value: 0.9497794932372464 and parameters: {'weight_class_0': 0.03286767573437232, 'weight_class_1': 0.7184281989335424, 'weight_class_2': 0.3768338656632833}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:44,484] Trial 1346 finished with value: 0.9497768255779286 and parameters: {'weight_class_0': 0.03334935927210683, 'weight_class_1': 0.6996935570238745, 'weight_class_2': 0.38156607807927706}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:44,542] Trial 1348 finished with value: 0.8907920289406133 and parameters: {'weight_class_0': 0.06660767611018711, 'weight_class_1': 0.7019781074599302, 'weight_class_2': 0.01055502072735412}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:44,572] Trial 1350 finished with value: 0.9484891338267057 and parameters: {'weight_class_0': 0.06635328212019122, 'weight_class_1': 0.7283328946700108, 'weight_class_2': 0.36443727822828087}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:44,577] Trial 1349 finished with value: 0.9496970021222338 and parameters: {'weight_class_0': 0.037935949739455715, 'weight_class_1': 0.7229210029383408, 'weight_class_2': 0.37352727452017453}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:44,590] Trial 1351 finished with value: 0.948649569754089 and parameters: {'weight_class_0': 0.0620645375962996, 'weight_class_1': 0.6707345140068662, 'weight_class_2': 0.3611492093823386}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:44,618] Trial 1352 finished with value: 0.9488734196816848 and parameters: {'weight_class_0': 0.05749870933413235, 'weight_class_1': 0.7560331864476177, 'weight_class_2': 0.3538516526545055}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:25:44,667] Trial 1354 finished with value: 0.9490159214187172 and parameters: {'weight_class_0': 0.06180513476869099, 'weight_class_1': 0.7272310644593843, 'weight_class_2': 0.40933009820909744}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:44,686] Trial 1353 finished with value: 0.9468066294228219 and parameters: {'weight_class_0': 0.09347711603268984, 'weight_class_1': 0.7213073194903064, 'weight_class_2': 0.3784606779262777}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:44,744] Trial 1356 finished with value: 0.946774130105395 and parameters: {'weight_class_0': 0.0923976848025375, 'weight_class_1': 0.6670084363256671, 'weight_class_2': 0.37978429709182226}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:44,771] Trial 1355 finished with value: 0.9488854975114186 and parameters: {'weight_class_0': 0.06572876410464512, 'weight_class_1': 0.7372630838558407, 'weight_class_2': 0.40489013725936635}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:44,811] Trial 1358 finished with value: 0.9486511330807751 and parameters: {'weight_class_0': 0.0654175610914805, 'weight_class_1': 0.6049336109341131, 'weight_class_2': 0.3832751354580985}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:44,820] Trial 1357 finished with value: 0.8927945799890874 and parameters: {'weight_class_0': 0.038876720921502295, 'weight_class_1': 0.8711729567147511, 'weight_class_2': 0.010578073611829338}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:44,839] Trial 1359 finished with value: 0.9489490953045262 and parameters: {'weight_class_0': 0.06323456850408384, 'weight_class_1': 0.9479902676834476, 'weight_class_2': 0.4025565454465868}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:25:44,860] Trial 1360 finished with value: 0.9480373366602696 and parameters: {'weight_class_0': 0.09214779296990758, 'weight_class_1': 0.8754889556630698, 'weight_class_2': 0.4512990385142137}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:44,874] Trial 1362 finished with value: 0.9478762703105218 and parameters: {'weight_class_0': 0.09444076430408391, 'weight_class_1': 0.9469589111265709, 'weight_class_2': 0.44762614091989306}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:44,908] Trial 1361 finished with value: 0.9475059607148856 and parameters: {'weight_class_0': 0.09754788310830109, 'weight_class_1': 1.429705302801705, 'weight_class_2': 0.43506377895880727}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:44,936] Trial 1363 finished with value: 0.9487252419460109 and parameters: {'weight_class_0': 0.09181124948802996, 'weight_class_1': 0.892487095776417, 'weight_class_2': 0.5433374277541659}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:44,945] Trial 1364 finished with value: 0.949123942429836 and parameters: {'weight_class_0': 0.08472135307513222, 'weight_class_1': 1.3622111042400638, 'weight_class_2': 0.5926093156353662}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:44,998] Trial 1366 finished with value: 0.9494325740350268 and parameters: {'weight_class_0': 0.039517218036743275, 'weight_class_1': 0.5692236002499592, 'weight_class_2': 0.5792097308621581}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:45,017] Trial 1365 finished with value: 0.9082370367642203 and parameters: {'weight_class_0': 0.0380593130886415, 'weight_class_1': 7.111935036891348, 'weight_class_2': 0.5675199765405454}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:45,065] Trial 1368 finished with value: 0.949498406288698 and parameters: {'weight_class_0': 0.03971392773822052, 'weight_class_1': 0.9432699402406406, 'weight_class_2': 0.5424294441607661}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  46%|███████████████████████████████████████████████████████████▌                                                                      | 1375/3000 [00:30<00:45, 35.91it/s]

[I 2026-07-05 15:25:45,080] Trial 1367 finished with value: 0.6653862119511903 and parameters: {'weight_class_0': 0.0010118579079005556, 'weight_class_1': 1.3411910772875901, 'weight_class_2': 0.5776261128308888}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:45,100] Trial 1369 finished with value: 0.9493475489610536 and parameters: {'weight_class_0': 0.03877395323167502, 'weight_class_1': 0.9345414164438813, 'weight_class_2': 0.5774520283882871}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:45,124] Trial 1370 finished with value: 0.9487367557298686 and parameters: {'weight_class_0': 0.037178674913113864, 'weight_class_1': 1.388143837278937, 'weight_class_2': 0.6094088730834204}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:45,157] Trial 1371 finished with value: 0.9494157658221117 and parameters: {'weight_class_0': 0.03916445857693859, 'weight_class_1': 0.5846965184854422, 'weight_class_2': 0.5812916467759495}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:45,207] Trial 1372 finished with value: 0.949303069161688 and parameters: {'weight_class_0': 0.040369787572366145, 'weight_class_1': 0.5624449913481171, 'weight_class_2': 0.6644054481106876}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:45,231] Trial 1374 finished with value: 0.9493438500891469 and parameters: {'weight_class_0': 0.04050333140764685, 'weight_class_1': 0.5730235656196101, 'weight_class_2': 0.65271330881231}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:45,237] Trial 1373 finished with value: 0.9493848123988341 and parameters: {'weight_class_0': 0.04180294712868058, 'weight_class_1': 0.5719986039583889, 'weight_class_2': 0.6571357295816941}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:45,265] Trial 1375 finished with value: 0.9493530269957624 and parameters: {'weight_class_0': 0.05057310853945736, 'weight_class_1': 1.406770406456234, 'weight_class_2': 0.7044259302740645}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  46%|███████████████████████████████████████████████████████████▉                                                                      | 1383/3000 [00:30<00:43, 37.40it/s]

[I 2026-07-05 15:25:45,296] Trial 1376 finished with value: 0.948326700483826 and parameters: {'weight_class_0': 0.05180386973025967, 'weight_class_1': 0.5570154049990487, 'weight_class_2': 1.067350591533679}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:45,326] Trial 1378 finished with value: 0.9494040350925862 and parameters: {'weight_class_0': 0.045688335990785554, 'weight_class_1': 0.5836326734267991, 'weight_class_2': 0.6687710798334275}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:45,368] Trial 1377 finished with value: 0.9494969813943421 and parameters: {'weight_class_0': 0.05192967299258927, 'weight_class_1': 0.5735283360031102, 'weight_class_2': 0.6814093868805661}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:45,371] Trial 1379 finished with value: 0.8575887988376407 and parameters: {'weight_class_0': 1.1009401047823608, 'weight_class_1': 0.535215535015374, 'weight_class_2': 1.0139149777165242}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:45,384] Trial 1380 finished with value: 0.9491141962269399 and parameters: {'weight_class_0': 0.04953187758745966, 'weight_class_1': 0.5876202804712042, 'weight_class_2': 0.8103699486894592}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:45,442] Trial 1382 finished with value: 0.9491895506838434 and parameters: {'weight_class_0': 0.05231956562988908, 'weight_class_1': 0.4860387551976211, 'weight_class_2': 0.7217953271929246}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:45,464] Trial 1381 finished with value: 0.9491999738481115 and parameters: {'weight_class_0': 0.04901341507412047, 'weight_class_1': 0.5366417807981071, 'weight_class_2': 0.7139168699005176}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:45,474] Trial 1383 finished with value: 0.9481685817130922 and parameters: {'weight_class_0': 0.04909178735340652, 'weight_class_1': 0.518256131817586, 'weight_class_2': 1.0671199606712927}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  46%|████████████████████████████████████████████████████████████▎                                                                     | 1391/3000 [00:31<00:43, 36.85it/s]

[I 2026-07-05 15:25:45,521] Trial 1384 finished with value: 0.9484273482274935 and parameters: {'weight_class_0': 0.05111446662448106, 'weight_class_1': 0.5252692346749733, 'weight_class_2': 1.0076833724423928}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:45,569] Trial 1386 finished with value: 0.9485801855370376 and parameters: {'weight_class_0': 0.046591588264125634, 'weight_class_1': 0.4877960515031114, 'weight_class_2': 0.8675256807584513}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:45,571] Trial 1385 finished with value: 0.9484358625970476 and parameters: {'weight_class_0': 0.05123978886813245, 'weight_class_1': 0.559770565652843, 'weight_class_2': 1.030071914090901}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:45,588] Trial 1387 finished with value: 0.860463554111469 and parameters: {'weight_class_0': 0.05088702410768806, 'weight_class_1': 0.5083026687569707, 'weight_class_2': 0.0016481575930770275}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:45,633] Trial 1388 finished with value: 0.9494123903337827 and parameters: {'weight_class_0': 0.052051439004105436, 'weight_class_1': 0.8458823941236477, 'weight_class_2': 0.8293428560615249}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:45,675] Trial 1390 finished with value: 0.9494046496784211 and parameters: {'weight_class_0': 0.03136629977165317, 'weight_class_1': 0.4572145138457197, 'weight_class_2': 0.4715123235513456}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:45,678] Trial 1389 finished with value: 0.8377270667455701 and parameters: {'weight_class_0': 1.6888165432453666, 'weight_class_1': 0.4718856259317229, 'weight_class_2': 0.8668800980791983}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:45,721] Trial 1392 finished with value: 0.9492369542712549 and parameters: {'weight_class_0': 0.029706751709886195, 'weight_class_1': 0.8637109276980625, 'weight_class_2': 0.4733538999739168}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  47%|████████████████████████████████████████████████████████████▌                                                                     | 1399/3000 [00:31<00:42, 37.85it/s]

[I 2026-07-05 15:25:45,722] Trial 1391 finished with value: 0.9492819446427099 and parameters: {'weight_class_0': 0.03016645268834654, 'weight_class_1': 0.8617678175315693, 'weight_class_2': 0.46500074206533065}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:45,766] Trial 1393 finished with value: 0.8867683338301607 and parameters: {'weight_class_0': 0.0039417378943594, 'weight_class_1': 0.8721025320300987, 'weight_class_2': 0.47222626647872085}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:45,777] Trial 1394 finished with value: 0.9491221875159978 and parameters: {'weight_class_0': 0.02886811892520694, 'weight_class_1': 0.8766838776954996, 'weight_class_2': 0.4897570264900259}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:45,786] Trial 1395 finished with value: 0.8349566697804841 and parameters: {'weight_class_0': 0.029675011173956965, 'weight_class_1': 0.8126019419566534, 'weight_class_2': 0.0018615691637607823}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:45,822] Trial 1396 finished with value: 0.9492750798755217 and parameters: {'weight_class_0': 0.031167152105797364, 'weight_class_1': 0.8577106347445276, 'weight_class_2': 0.4635325185406323}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:45,858] Trial 1397 finished with value: 0.9491987099446147 and parameters: {'weight_class_0': 0.029797716690190955, 'weight_class_1': 0.851922847849952, 'weight_class_2': 0.4873279913492946}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:45,886] Trial 1398 finished with value: 0.9491950751611408 and parameters: {'weight_class_0': 0.02880664875135233, 'weight_class_1': 0.8516486748734067, 'weight_class_2': 0.47533406711520276}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:45,937] Trial 1399 finished with value: 0.8460611795439705 and parameters: {'weight_class_0': 1.628168780299439, 'weight_class_1': 0.8503859489061574, 'weight_class_2': 0.4735129396477124}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  47%|█████████████████████████████████████████████████████████████                                                                     | 1408/3000 [00:31<00:42, 37.59it/s]

[I 2026-07-05 15:25:45,957] Trial 1400 finished with value: 0.9491780985806741 and parameters: {'weight_class_0': 0.029910248656410416, 'weight_class_1': 0.8438513345379008, 'weight_class_2': 0.49239747871652645}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:46,019] Trial 1401 finished with value: 0.9496941333402807 and parameters: {'weight_class_0': 0.03649191487835027, 'weight_class_1': 0.7230892142271431, 'weight_class_2': 0.34510109957131724}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:46,021] Trial 1402 finished with value: 0.9089132261859181 and parameters: {'weight_class_0': 0.004170104689347338, 'weight_class_1': 0.7251391468118841, 'weight_class_2': 0.48746782524926546}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:46,029] Trial 1403 finished with value: 0.9149579007438753 and parameters: {'weight_class_0': 0.004110425481778248, 'weight_class_1': 0.6878800092515776, 'weight_class_2': 0.3536512240188719}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:46,043] Trial 1404 finished with value: 0.9496217868887132 and parameters: {'weight_class_0': 0.036640817691850056, 'weight_class_1': 0.7710689449743591, 'weight_class_2': 0.33438649993699676}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:46,079] Trial 1405 finished with value: 0.9482058288139851 and parameters: {'weight_class_0': 0.07022072790829582, 'weight_class_1': 0.663176351771274, 'weight_class_2': 0.35173867769624545}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:46,106] Trial 1406 finished with value: 0.9491663925075061 and parameters: {'weight_class_0': 0.0367070332560358, 'weight_class_1': 1.183889073052239, 'weight_class_2': 0.3586792434392786}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:46,136] Trial 1407 finished with value: 0.9484612616982265 and parameters: {'weight_class_0': 0.06992988009050426, 'weight_class_1': 0.6419064037341999, 'weight_class_2': 0.3799096154857944}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:46,171] Trial 1408 finished with value: 0.9475535819790482 and parameters: {'weight_class_0': 0.07312386594300328, 'weight_class_1': 0.6675585678394356, 'weight_class_2': 0.3270222851247364}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  47%|█████████████████████████████████████████████████████████████▎                                                                    | 1416/3000 [00:31<00:43, 36.41it/s]

[I 2026-07-05 15:25:46,182] Trial 1409 finished with value: 0.9497317103056645 and parameters: {'weight_class_0': 0.03566078270792469, 'weight_class_1': 0.6645571747463758, 'weight_class_2': 0.36237504715193986}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:46,217] Trial 1410 finished with value: 0.9478122287097978 and parameters: {'weight_class_0': 0.07582105647498141, 'weight_class_1': 0.6673650819294745, 'weight_class_2': 0.3582430430340093}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:46,236] Trial 1411 finished with value: 0.9497300166400561 and parameters: {'weight_class_0': 0.03801623221671003, 'weight_class_1': 0.659285636684606, 'weight_class_2': 0.340773255207471}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:46,259] Trial 1412 finished with value: 0.9474344119301851 and parameters: {'weight_class_0': 0.07807313994937706, 'weight_class_1': 1.254897385260451, 'weight_class_2': 0.344082617083807}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:46,294] Trial 1413 finished with value: 0.9481393628118173 and parameters: {'weight_class_0': 0.06994683205601519, 'weight_class_1': 1.2696984131749878, 'weight_class_2': 0.3508422964941015}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:46,346] Trial 1414 finished with value: 0.9474010421626983 and parameters: {'weight_class_0': 0.07698704626377047, 'weight_class_1': 1.0927804157933487, 'weight_class_2': 0.3368696071964275}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:46,376] Trial 1415 finished with value: 0.9483342345794984 and parameters: {'weight_class_0': 0.0775747927187759, 'weight_class_1': 1.1339210473159709, 'weight_class_2': 0.4109300684945542}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:46,394] Trial 1416 finished with value: 0.9491868744987201 and parameters: {'weight_class_0': 0.059101334269479784, 'weight_class_1': 1.014604909495846, 'weight_class_2': 0.41897985607280425}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  48%|█████████████████████████████████████████████████████████████▊                                                                    | 1425/3000 [00:32<00:41, 38.01it/s]

[I 2026-07-05 15:25:46,420] Trial 1418 finished with value: 0.9497278373988923 and parameters: {'weight_class_0': 0.059683229732273295, 'weight_class_1': 1.0684357902152508, 'weight_class_2': 0.5585865304335651}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:46,423] Trial 1417 finished with value: 0.9357319152679922 and parameters: {'weight_class_0': 0.008966392739172976, 'weight_class_1': 1.0367325533090472, 'weight_class_2': 0.39226407283191794}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:46,470] Trial 1419 finished with value: 0.9453122425866255 and parameters: {'weight_class_0': 0.164511374116701, 'weight_class_1': 2.158563108769114, 'weight_class_2': 0.552038239766282}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:46,492] Trial 1420 finished with value: 0.9490939343676859 and parameters: {'weight_class_0': 0.06061950005128803, 'weight_class_1': 2.0561768222589536, 'weight_class_2': 0.5425954546128678}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:46,497] Trial 1421 finished with value: 0.9404588222138267 and parameters: {'weight_class_0': 0.16631563516434666, 'weight_class_1': 1.2010613094701095, 'weight_class_2': 0.4142518999176482}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:46,545] Trial 1422 finished with value: 0.9365398427895668 and parameters: {'weight_class_0': 0.008833346897195176, 'weight_class_1': 0.9952923332000638, 'weight_class_2': 0.41851188387960186}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:46,563] Trial 1423 finished with value: 0.8137751991877745 and parameters: {'weight_class_0': 6.479518442721379, 'weight_class_1': 0.46307376881002066, 'weight_class_2': 0.556973922140256}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:46,579] Trial 1424 finished with value: 0.9496820628815167 and parameters: {'weight_class_0': 0.059646007719898794, 'weight_class_1': 1.0879817711898907, 'weight_class_2': 0.5956446054040911}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:46,615] Trial 1425 finished with value: 0.9493101083049776 and parameters: {'weight_class_0': 0.06099959333734392, 'weight_class_1': 0.46478287661345524, 'weight_class_2': 0.5542641902609132}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  48%|██████████████████████████████████████████████████████████████                                                                    | 1433/3000 [00:32<00:41, 37.43it/s]

[I 2026-07-05 15:25:46,638] Trial 1426 finished with value: 0.9493944224245482 and parameters: {'weight_class_0': 0.0593853178604448, 'weight_class_1': 0.4893740744806814, 'weight_class_2': 0.5605730293301019}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:46,676] Trial 1427 finished with value: 0.9493483049038688 and parameters: {'weight_class_0': 0.04170012275302943, 'weight_class_1': 0.4559126344881219, 'weight_class_2': 0.5731421672884551}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:46,703] Trial 1428 finished with value: 0.949502989643603 and parameters: {'weight_class_0': 0.04135600185816824, 'weight_class_1': 0.4585030851214643, 'weight_class_2': 0.5328027852712036}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:46,734] Trial 1429 finished with value: 0.8907544594128227 and parameters: {'weight_class_0': 0.038265397798037004, 'weight_class_1': 0.624019511068874, 'weight_class_2': 0.006614311507320852}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:46,740] Trial 1430 finished with value: 0.9487308151320865 and parameters: {'weight_class_0': 0.043688636497252124, 'weight_class_1': 0.45335014184063244, 'weight_class_2': 0.786286634948106}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:46,784] Trial 1432 finished with value: 0.9486698595446978 and parameters: {'weight_class_0': 0.04324119599564448, 'weight_class_1': 0.4745064675555229, 'weight_class_2': 0.8145247700966401}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:46,801] Trial 1433 finished with value: 0.9487432793421019 and parameters: {'weight_class_0': 0.04289082555906321, 'weight_class_1': 0.47051022813390836, 'weight_class_2': 0.7835791576745084}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:46,809] Trial 1431 finished with value: 0.9484799656616598 and parameters: {'weight_class_0': 0.03882588802881312, 'weight_class_1': 0.4496932899240243, 'weight_class_2': 0.7885591283586765}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  48%|██████████████████████████████████████████████████████████████▍                                                                   | 1441/3000 [00:32<00:41, 37.23it/s]

[I 2026-07-05 15:25:46,865] Trial 1435 finished with value: 0.9488610323140684 and parameters: {'weight_class_0': 0.045266719383491374, 'weight_class_1': 0.4631281421788611, 'weight_class_2': 0.7669180271775781}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:46,875] Trial 1434 finished with value: 0.9487521487634409 and parameters: {'weight_class_0': 0.0453203500219922, 'weight_class_1': 0.48836438993169273, 'weight_class_2': 0.8146383956358455}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:46,933] Trial 1436 finished with value: 0.9490418248975283 and parameters: {'weight_class_0': 0.04414694938396253, 'weight_class_1': 0.6407018963837506, 'weight_class_2': 0.8138511854620823}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:46,947] Trial 1437 finished with value: 0.9485425289189079 and parameters: {'weight_class_0': 0.04090468618215361, 'weight_class_1': 0.4512338169654786, 'weight_class_2': 0.7965529294074378}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:46,967] Trial 1438 finished with value: 0.9489717143948826 and parameters: {'weight_class_0': 0.045592816994280166, 'weight_class_1': 0.6095237563136165, 'weight_class_2': 0.8318582548463176}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:47,015] Trial 1439 finished with value: 0.8394389395954951 and parameters: {'weight_class_0': 0.03599014707127047, 'weight_class_1': 0.0021446907678787162, 'weight_class_2': 0.7460744877531607}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:47,016] Trial 1440 finished with value: 0.9491872790141626 and parameters: {'weight_class_0': 0.04546630072628392, 'weight_class_1': 0.612139996330017, 'weight_class_2': 0.7717190126666975}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:47,038] Trial 1441 finished with value: 0.9492125276903889 and parameters: {'weight_class_0': 0.04382949062443583, 'weight_class_1': 0.611915049534528, 'weight_class_2': 0.7620372959694206}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:25:47,093] Trial 1443 finished with value: 0.8513090003139775 and parameters: {'weight_class_0': 3.6568551185280587, 'weight_class_1': 2.67728193901905, 'weight_class_2': 0.6853789643402335}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:47,102] Trial 1442 finished with value: 0.9478805334328991 and parameters: {'weight_class_0': 0.03412875464708639, 'weight_class_1': 1.5471354560436357, 'weight_class_2': 0.7005855904567726}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:47,164] Trial 1444 finished with value: 0.9438288814593859 and parameters: {'weight_class_0': 0.03411307287011307, 'weight_class_1': 0.1043184227302768, 'weight_class_2': 0.4331899863479459}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:47,173] Trial 1445 finished with value: 0.9199404651495176 and parameters: {'weight_class_0': 0.028722680297703886, 'weight_class_1': 0.5947050199574837, 'weight_class_2': 5.543266501311623}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:47,185] Trial 1446 finished with value: 0.9497182029837191 and parameters: {'weight_class_0': 0.03485316631953449, 'weight_class_1': 0.6185359563679833, 'weight_class_2': 0.4359262855524586}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:47,213] Trial 1447 finished with value: 0.943880391834866 and parameters: {'weight_class_0': 0.028188939078485773, 'weight_class_1': 1.5571757819189416, 'weight_class_2': 2.2951776039144476}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:47,272] Trial 1448 finished with value: 0.8397682361668081 and parameters: {'weight_class_0': 0.03398896285326388, 'weight_class_1': 0.0013764358799826305, 'weight_class_2': 0.4637352101563145}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:47,273] Trial 1450 finished with value: 0.9494640137380088 and parameters: {'weight_class_0': 0.03195340573604328, 'weight_class_1': 0.7379608472482062, 'weight_class_2': 0.4465169543028344}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  49%|███████████████████████████████████████████████████████████████▏                                                                  | 1458/3000 [00:32<00:40, 38.34it/s]

[I 2026-07-05 15:25:47,276] Trial 1449 finished with value: 0.9410266200995306 and parameters: {'weight_class_0': 0.03313454161731827, 'weight_class_1': 3.307116376295178, 'weight_class_2': 0.4564233748692163}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:47,313] Trial 1451 finished with value: 0.9419977238264314 and parameters: {'weight_class_0': 0.031096910087426623, 'weight_class_1': 2.9693813489792364, 'weight_class_2': 0.43691690479387135}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:47,357] Trial 1452 finished with value: 0.9335311276795534 and parameters: {'weight_class_0': 0.0063644591540020605, 'weight_class_1': 0.7552803478741874, 'weight_class_2': 0.04005546100664302}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:47,369] Trial 1453 finished with value: 0.9493311709937834 and parameters: {'weight_class_0': 0.02952445871905574, 'weight_class_1': 0.70702274490182, 'weight_class_2': 0.4711787745380511}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:47,376] Trial 1454 finished with value: 0.9460859528184988 and parameters: {'weight_class_0': 0.02769806692594313, 'weight_class_1': 0.11283592488031335, 'weight_class_2': 0.4587947852957281}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:47,402] Trial 1455 finished with value: 0.9435492728027128 and parameters: {'weight_class_0': 0.029487824314076292, 'weight_class_1': 0.11540217843722991, 'weight_class_2': 1.3328542689755456}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:47,457] Trial 1456 finished with value: 0.948522538239582 and parameters: {'weight_class_0': 0.11480630685416254, 'weight_class_1': 0.7119997460513804, 'weight_class_2': 1.3658696600756117}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:47,473] Trial 1457 finished with value: 0.9320627910279624 and parameters: {'weight_class_0': 0.006155042210114439, 'weight_class_1': 0.7592966732112465, 'weight_class_2': 0.46737474320277295}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:47,504] Trial 1458 finished with value: 0.9467496080116463 and parameters: {'weight_class_0': 0.107814087263009, 'weight_class_1': 0.7785406176623695, 'weight_class_2': 0.4415882504494325}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:25:47,538] Trial 1459 finished with value: 0.9494687033397264 and parameters: {'weight_class_0': 0.054859206170599834, 'weight_class_1': 0.7849396724781752, 'weight_class_2': 0.439710072825722}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:47,560] Trial 1460 finished with value: 0.9300277001663125 and parameters: {'weight_class_0': 0.00639064675531326, 'weight_class_1': 0.7857565565684633, 'weight_class_2': 0.6498211468020775}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:47,571] Trial 1461 finished with value: 0.9484747300368538 and parameters: {'weight_class_0': 0.056104877871773776, 'weight_class_1': 0.7553426227632661, 'weight_class_2': 1.2255327714667834}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:47,580] Trial 1463 finished with value: 0.948403849625017 and parameters: {'weight_class_0': 0.11352035508552599, 'weight_class_1': 0.97047952130347, 'weight_class_2': 0.6272430489640072}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:47,608] Trial 1462 finished with value: 0.9250180856334999 and parameters: {'weight_class_0': 0.3222477551179426, 'weight_class_1': 0.7730553112252869, 'weight_class_2': 0.6398800878254068}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:47,648] Trial 1464 finished with value: 0.9489067416389058 and parameters: {'weight_class_0': 0.05288664035679308, 'weight_class_1': 0.9782917494571827, 'weight_class_2': 0.3334373164520013}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:47,692] Trial 1465 finished with value: 0.9485092365514137 and parameters: {'weight_class_0': 0.05700582627093971, 'weight_class_1': 0.9660879032617101, 'weight_class_2': 0.31473715331064084}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:47,713] Trial 1466 finished with value: 0.9434027144985183 and parameters: {'weight_class_0': 0.11299400821533997, 'weight_class_1': 0.9489882791908842, 'weight_class_2': 0.329057123862533}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  49%|███████████████████████████████████████████████████████████████▊                                                                  | 1474/3000 [00:33<00:39, 38.53it/s]

[I 2026-07-05 15:25:47,720] Trial 1467 finished with value: 0.9488156165067957 and parameters: {'weight_class_0': 0.05379235413507426, 'weight_class_1': 0.9183499529123904, 'weight_class_2': 0.32678850297759393}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:47,775] Trial 1468 finished with value: 0.7873609959386646 and parameters: {'weight_class_0': 0.05174269791034851, 'weight_class_1': 0.9388135406102862, 'weight_class_2': 0.0013393020436748798}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:47,799] Trial 1470 finished with value: 0.8878585441124619 and parameters: {'weight_class_0': 0.05379384715890549, 'weight_class_1': 0.01351774602582926, 'weight_class_2': 0.6292265509944284}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:47,803] Trial 1469 finished with value: 0.887594593489518 and parameters: {'weight_class_0': 0.05507366020234884, 'weight_class_1': 0.013603851773849467, 'weight_class_2': 0.6320777764600168}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:47,841] Trial 1471 finished with value: 0.949729002207051 and parameters: {'weight_class_0': 0.05460699974634512, 'weight_class_1': 0.9735550398016833, 'weight_class_2': 0.5931280280048861}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:47,863] Trial 1472 finished with value: 0.9486718986383683 and parameters: {'weight_class_0': 0.05244122900443638, 'weight_class_1': 1.2838896539837013, 'weight_class_2': 0.3257425443106012}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:47,921] Trial 1475 finished with value: 0.9484990658870749 and parameters: {'weight_class_0': 0.059913105064898275, 'weight_class_1': 0.995202727247556, 'weight_class_2': 0.33007709455377676}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:47,923] Trial 1473 finished with value: 0.9487491216485693 and parameters: {'weight_class_0': 0.04859608854986489, 'weight_class_1': 1.3709800852808607, 'weight_class_2': 0.32850293697133187}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  49%|████████████████████████████████████████████████████████████████▎                                                                 | 1483/3000 [00:33<00:40, 37.07it/s]

[I 2026-07-05 15:25:47,955] Trial 1474 finished with value: 0.9486089507406682 and parameters: {'weight_class_0': 0.05709005580325915, 'weight_class_1': 0.9587225873534324, 'weight_class_2': 0.3263690208689029}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:47,959] Trial 1476 finished with value: 0.9430594606496583 and parameters: {'weight_class_0': 0.02744489014228379, 'weight_class_1': 1.3293434274534432, 'weight_class_2': 0.08742000869402486}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:48,009] Trial 1477 finished with value: 0.8897484871091944 and parameters: {'weight_class_0': 0.0488081171507073, 'weight_class_1': 0.013601399766492309, 'weight_class_2': 0.5438246696685933}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:48,020] Trial 1478 finished with value: 0.9489652470324117 and parameters: {'weight_class_0': 0.08447976760889771, 'weight_class_1': 1.3695698751731893, 'weight_class_2': 0.5555273113814446}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:48,033] Trial 1479 finished with value: 0.637107388938852 and parameters: {'weight_class_0': 0.7111549356568229, 'weight_class_1': 0.5947542633738074, 'weight_class_2': 0.001303266638444717}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:48,065] Trial 1480 finished with value: 0.9476989865721164 and parameters: {'weight_class_0': 0.026953956136439774, 'weight_class_1': 1.3536442243762092, 'weight_class_2': 0.5121290487478498}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:48,107] Trial 1481 finished with value: 0.9487655607008983 and parameters: {'weight_class_0': 0.03696454932080038, 'weight_class_1': 1.407743563325042, 'weight_class_2': 0.5412806839695714}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:48,112] Trial 1482 finished with value: 0.9478737010076171 and parameters: {'weight_class_0': 0.03644782190218918, 'weight_class_1': 0.5753669414643278, 'weight_class_2': 1.076332091802726}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:48,145] Trial 1483 finished with value: 0.948375337822413 and parameters: {'weight_class_0': 0.08551844355735495, 'weight_class_1': 0.5645679980864117, 'weight_class_2': 0.542694244347518}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  50%|████████████████████████████████████████████████████████████████▌                                                                 | 1490/3000 [00:33<00:39, 38.40it/s]

[I 2026-07-05 15:25:48,200] Trial 1484 finished with value: 0.9489364978911842 and parameters: {'weight_class_0': 0.08402324618318166, 'weight_class_1': 0.5852743812708667, 'weight_class_2': 0.990146021452489}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:48,206] Trial 1485 finished with value: 0.9490987993130974 and parameters: {'weight_class_0': 0.027176227321498107, 'weight_class_1': 0.5549229381289104, 'weight_class_2': 0.5329493896976856}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:48,239] Trial 1487 finished with value: 0.8822150690973182 and parameters: {'weight_class_0': 0.03907216034590858, 'weight_class_1': 0.006210489116128086, 'weight_class_2': 0.39967519800676404}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:48,265] Trial 1486 finished with value: 0.9492082085397358 and parameters: {'weight_class_0': 0.08444996461261657, 'weight_class_1': 0.6893761940486324, 'weight_class_2': 1.0118100868817137}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:48,292] Trial 1489 finished with value: 0.9480335108687251 and parameters: {'weight_class_0': 0.03703574793308852, 'weight_class_1': 0.5509130614110797, 'weight_class_2': 0.9937631433812714}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:48,312] Trial 1488 finished with value: 0.9482440395954203 and parameters: {'weight_class_0': 0.037129183795234964, 'weight_class_1': 0.568202315716024, 'weight_class_2': 0.9373056065334288}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:48,363] Trial 1490 finished with value: 0.9466156934273612 and parameters: {'weight_class_0': 0.24460531883933903, 'weight_class_1': 1.8692233909852027, 'weight_class_2': 0.970958053445288}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  50%|████████████████████████████████████████████████████████████████▉                                                                 | 1499/3000 [00:34<00:39, 37.77it/s]

[I 2026-07-05 15:25:48,410] Trial 1491 finished with value: 0.949829729220737 and parameters: {'weight_class_0': 0.0358922331422853, 'weight_class_1': 0.555920432803405, 'weight_class_2': 0.4142774254157031}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:48,416] Trial 1492 finished with value: 0.9497263761385382 and parameters: {'weight_class_0': 0.03733640915493724, 'weight_class_1': 0.5522676911968283, 'weight_class_2': 0.40234801524997155}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:48,427] Trial 1493 finished with value: 0.9454668540720715 and parameters: {'weight_class_0': 0.008854167381086672, 'weight_class_1': 0.5582244955854895, 'weight_class_2': 0.40215651777536}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:48,452] Trial 1494 finished with value: 0.9454963679541368 and parameters: {'weight_class_0': 0.009254545610468085, 'weight_class_1': 0.5830725341181153, 'weight_class_2': 0.39343741294275825}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:48,470] Trial 1495 finished with value: 0.8754381699231657 and parameters: {'weight_class_0': 0.03771474760069928, 'weight_class_1': 0.005913427213720354, 'weight_class_2': 0.9343286433191442}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:48,523] Trial 1498 finished with value: 0.9482863165368659 and parameters: {'weight_class_0': 0.06839056168071368, 'weight_class_1': 0.5262231044702798, 'weight_class_2': 0.37179055486814394}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:48,526] Trial 1496 finished with value: 0.9487956638691312 and parameters: {'weight_class_0': 0.06630547530891276, 'weight_class_1': 0.6394313912121187, 'weight_class_2': 0.4018461273136418}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:48,545] Trial 1497 finished with value: 0.8886465414560295 and parameters: {'weight_class_0': 0.008831474112477523, 'weight_class_1': 2.013214914180278, 'weight_class_2': 0.42125849142235505}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:48,562] Trial 1499 finished with value: 0.754599894045473 and parameters: {'weight_class_0': 0.0032195070821424395, 'weight_class_1': 1.8647988010314613, 'weight_class_2': 0.3776235757704498}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  50%|█████████████████████████████████████████████████████████████████▎                                                                | 1506/3000 [00:34<00:42, 35.12it/s]

[I 2026-07-05 15:25:48,601] Trial 1500 finished with value: 0.9487283679541437 and parameters: {'weight_class_0': 0.06477275424080986, 'weight_class_1': 0.6862208865170584, 'weight_class_2': 0.38561512175694035}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:48,620] Trial 1501 finished with value: 0.9486487875125654 and parameters: {'weight_class_0': 0.06772991137520225, 'weight_class_1': 0.6776032221532224, 'weight_class_2': 0.3961542805307267}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:48,680] Trial 1502 finished with value: 0.9446728953722466 and parameters: {'weight_class_0': 0.009506144748961607, 'weight_class_1': 0.6801144844650967, 'weight_class_2': 0.38838972704345115}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:48,691] Trial 1503 finished with value: 0.9481659685811258 and parameters: {'weight_class_0': 0.06516302262899525, 'weight_class_1': 0.41340865478292926, 'weight_class_2': 0.3967493312052575}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:48,755] Trial 1504 finished with value: 0.9486014465444487 and parameters: {'weight_class_0': 0.06799229753697283, 'weight_class_1': 0.42505055246141726, 'weight_class_2': 0.6799854189910953}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:48,762] Trial 1505 finished with value: 0.9490511248034171 and parameters: {'weight_class_0': 0.02642117780738523, 'weight_class_1': 0.4184667019124187, 'weight_class_2': 0.5110354731273284}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:48,786] Trial 1507 finished with value: 0.9490933493482475 and parameters: {'weight_class_0': 0.027008407871065784, 'weight_class_1': 0.41737668148868634, 'weight_class_2': 0.5045341570046997}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  50%|█████████████████████████████████████████████████████████████████▋                                                                | 1515/3000 [00:34<00:40, 36.71it/s]

[I 2026-07-05 15:25:48,803] Trial 1506 finished with value: 0.9486012174214394 and parameters: {'weight_class_0': 0.06870028425976232, 'weight_class_1': 0.42467234279989907, 'weight_class_2': 0.6781906638925496}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:48,814] Trial 1508 finished with value: 0.948536945070844 and parameters: {'weight_class_0': 0.027937032933547958, 'weight_class_1': 0.43134861104273364, 'weight_class_2': 0.6530210719552908}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:48,884] Trial 1510 finished with value: 0.949067611611489 and parameters: {'weight_class_0': 0.0450557500847417, 'weight_class_1': 0.42795578731138767, 'weight_class_2': 0.6657704336029415}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:48,893] Trial 1512 finished with value: 0.948977982625553 and parameters: {'weight_class_0': 0.04396085717295008, 'weight_class_1': 0.4169781941803379, 'weight_class_2': 0.662277699730035}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:48,898] Trial 1511 finished with value: 0.8898009150917945 and parameters: {'weight_class_0': 0.02669585585289778, 'weight_class_1': 0.42891188402288194, 'weight_class_2': 0.004009920109833234}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:48,916] Trial 1509 finished with value: 0.9485773700290617 and parameters: {'weight_class_0': 0.0271888047163647, 'weight_class_1': 0.4298187072792216, 'weight_class_2': 0.62760770613031}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:48,960] Trial 1513 finished with value: 0.7090075903294223 and parameters: {'weight_class_0': 0.00496994860694911, 'weight_class_1': 4.441213605188116, 'weight_class_2': 0.6559170695270573}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:48,982] Trial 1514 finished with value: 0.9490755666430677 and parameters: {'weight_class_0': 0.04331904804061711, 'weight_class_1': 0.44807443153156706, 'weight_class_2': 0.6781803035370448}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:48,983] Trial 1515 finished with value: 0.9489928212882965 and parameters: {'weight_class_0': 0.04635231570696528, 'weight_class_1': 0.4189090622636514, 'weight_class_2': 0.6622001959408618}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:25:49,047] Trial 1516 finished with value: 0.934669966928039 and parameters: {'weight_class_0': 0.004990029295774319, 'weight_class_1': 0.4655995217104913, 'weight_class_2': 0.6039871039869639}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:49,081] Trial 1517 finished with value: 0.9432700101800563 and parameters: {'weight_class_0': 0.04517843854410854, 'weight_class_1': 0.13063865872119304, 'weight_class_2': 0.5183947738814262}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:49,097] Trial 1518 finished with value: 0.9295824473019484 and parameters: {'weight_class_0': 0.04430571278173936, 'weight_class_1': 6.058811820595406, 'weight_class_2': 0.5000350974113721}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:49,141] Trial 1519 finished with value: 0.695615452265593 and parameters: {'weight_class_0': 0.004921019668395994, 'weight_class_1': 4.6831912098153685, 'weight_class_2': 0.10745624091702294}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:49,164] Trial 1520 finished with value: 0.9261727805692948 and parameters: {'weight_class_0': 0.005266241544667043, 'weight_class_1': 0.7705149476279177, 'weight_class_2': 0.09633080412394417}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:49,212] Trial 1522 finished with value: 0.9497476819056271 and parameters: {'weight_class_0': 0.046244011924176515, 'weight_class_1': 0.8169827800357726, 'weight_class_2': 0.5096911093036985}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:49,216] Trial 1521 finished with value: 0.9497644627272345 and parameters: {'weight_class_0': 0.04368315180655165, 'weight_class_1': 0.8196634970624949, 'weight_class_2': 0.5148688176364954}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:49,238] Trial 1523 finished with value: 0.9497951826096425 and parameters: {'weight_class_0': 0.044512230183112456, 'weight_class_1': 0.878628713523384, 'weight_class_2': 0.49855046598349617}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  51%|██████████████████████████████████████████████████████████████████▎                                                               | 1531/3000 [00:34<00:41, 35.62it/s]

[I 2026-07-05 15:25:49,260] Trial 1524 finished with value: 0.8837501605687891 and parameters: {'weight_class_0': 0.036369357687027745, 'weight_class_1': 0.13845365445173102, 'weight_class_2': 0.0028276457351294713}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:49,300] Trial 1525 finished with value: 0.9449662749832838 and parameters: {'weight_class_0': 0.1409094476537585, 'weight_class_1': 0.8130291643279518, 'weight_class_2': 0.5031181670046734}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:49,341] Trial 1526 finished with value: 0.9439345344180773 and parameters: {'weight_class_0': 0.03474121377649633, 'weight_class_1': 0.8475939022395661, 'weight_class_2': 0.10489807280358276}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:49,370] Trial 1528 finished with value: 0.9491037478369374 and parameters: {'weight_class_0': 0.033482075651787985, 'weight_class_1': 1.1292317770726474, 'weight_class_2': 0.31969337920918}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:49,381] Trial 1527 finished with value: 0.9495627481171001 and parameters: {'weight_class_0': 0.03464956175415598, 'weight_class_1': 0.7926308924621587, 'weight_class_2': 0.3189577157372522}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:49,429] Trial 1529 finished with value: 0.9494988805276346 and parameters: {'weight_class_0': 0.03571792861617007, 'weight_class_1': 0.8143383215360369, 'weight_class_2': 0.31287182413073433}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:49,455] Trial 1531 finished with value: 0.9494971053666542 and parameters: {'weight_class_0': 0.03238966432718373, 'weight_class_1': 0.8172249304875104, 'weight_class_2': 0.31352018847129803}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:49,471] Trial 1532 finished with value: 0.9190717318235135 and parameters: {'weight_class_0': 0.03769955262171768, 'weight_class_1': 1.1024734976345945, 'weight_class_2': 0.04843282761551622}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  51%|██████████████████████████████████████████████████████████████████▋                                                               | 1539/3000 [00:35<00:40, 36.23it/s]

[I 2026-07-05 15:25:49,494] Trial 1530 finished with value: 0.9464105407891298 and parameters: {'weight_class_0': 0.03212464725743195, 'weight_class_1': 1.1037529323882516, 'weight_class_2': 1.86385284561259}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:49,507] Trial 1533 finished with value: 0.9488962795748958 and parameters: {'weight_class_0': 0.03322671466078853, 'weight_class_1': 1.224518839084084, 'weight_class_2': 0.30719847609261286}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:49,560] Trial 1535 finished with value: 0.9496794848621749 and parameters: {'weight_class_0': 0.033185753338385034, 'weight_class_1': 0.5137957750486462, 'weight_class_2': 0.31546464098278504}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:49,578] Trial 1536 finished with value: 0.9496977209587282 and parameters: {'weight_class_0': 0.03278871226925073, 'weight_class_1': 0.5307591017174376, 'weight_class_2': 0.3160877057715783}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:49,584] Trial 1534 finished with value: 0.9427838017094649 and parameters: {'weight_class_0': 0.034605038950095944, 'weight_class_1': 0.09699645934488114, 'weight_class_2': 0.32889343513032376}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:49,607] Trial 1537 finished with value: 0.9496953683563977 and parameters: {'weight_class_0': 0.03252786742381052, 'weight_class_1': 0.5114052406540581, 'weight_class_2': 0.3167578823042405}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:49,662] Trial 1538 finished with value: 0.9265674136472465 and parameters: {'weight_class_0': 0.033001900848870364, 'weight_class_1': 0.5187847419559466, 'weight_class_2': 0.05117662403724048}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:49,690] Trial 1539 finished with value: 0.949699827684063 and parameters: {'weight_class_0': 0.03169378508628035, 'weight_class_1': 0.5248505623863536, 'weight_class_2': 0.31460789016688906}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:25:49,702] Trial 1540 finished with value: 0.9495675042704494 and parameters: {'weight_class_0': 0.03021964243627323, 'weight_class_1': 0.5252334746451962, 'weight_class_2': 0.4247906791830027}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:49,723] Trial 1541 finished with value: 0.9495526161681211 and parameters: {'weight_class_0': 0.030979613301778803, 'weight_class_1': 0.5367900072408837, 'weight_class_2': 0.44926981546560124}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:49,766] Trial 1543 finished with value: 0.9493454875605148 and parameters: {'weight_class_0': 0.05530575442917232, 'weight_class_1': 0.5232388014054177, 'weight_class_2': 0.432692920825339}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:49,796] Trial 1542 finished with value: 0.9493348981309717 and parameters: {'weight_class_0': 0.05546755606186208, 'weight_class_1': 0.5048888833042199, 'weight_class_2': 0.4475722330882036}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:49,838] Trial 1544 finished with value: 0.9441597639715574 and parameters: {'weight_class_0': 0.007437874621911856, 'weight_class_1': 0.5124570953896788, 'weight_class_2': 0.4592886112898239}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:49,849] Trial 1545 finished with value: 0.9494887369823868 and parameters: {'weight_class_0': 0.0560628941178898, 'weight_class_1': 0.659286363321857, 'weight_class_2': 0.46483497524971723}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:49,899] Trial 1546 finished with value: 0.8938626108605633 and parameters: {'weight_class_0': 0.0074577726716108786, 'weight_class_1': 1.610762321440895, 'weight_class_2': 0.46991624439448926}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  52%|███████████████████████████████████████████████████████████████████▍                                                              | 1555/3000 [00:35<00:39, 36.19it/s]

[I 2026-07-05 15:25:49,942] Trial 1548 finished with value: 0.9411784644721993 and parameters: {'weight_class_0': 0.007314075441305065, 'weight_class_1': 0.6400437041336652, 'weight_class_2': 0.5009111638510437}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:49,945] Trial 1547 finished with value: 0.9494509225312301 and parameters: {'weight_class_0': 0.054308407552700576, 'weight_class_1': 0.6132063451905284, 'weight_class_2': 0.44645727091114323}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:50,000] Trial 1550 finished with value: 0.9496362223838771 and parameters: {'weight_class_0': 0.05459081450266317, 'weight_class_1': 0.6858725787952409, 'weight_class_2': 0.494179930834651}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:50,004] Trial 1549 finished with value: 0.9495482971661425 and parameters: {'weight_class_0': 0.05235169544780407, 'weight_class_1': 0.6525291950551743, 'weight_class_2': 0.44859244794895925}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:50,020] Trial 1551 finished with value: 0.9483885735835046 and parameters: {'weight_class_0': 0.056834749063274924, 'weight_class_1': 0.6613459123828066, 'weight_class_2': 1.1905602035920833}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:50,041] Trial 1552 finished with value: 0.9494176406354303 and parameters: {'weight_class_0': 0.05380083424014102, 'weight_class_1': 0.6724803322863111, 'weight_class_2': 0.4331150080694973}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:50,064] Trial 1553 finished with value: 0.9497449590269097 and parameters: {'weight_class_0': 0.049937006163549034, 'weight_class_1': 0.6404594930397692, 'weight_class_2': 0.5663558748959862}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:50,101] Trial 1554 finished with value: 0.9489848441616924 and parameters: {'weight_class_0': 0.04981658537754898, 'weight_class_1': 1.5695964586571132, 'weight_class_2': 0.8831069367884261}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:50,125] Trial 1555 finished with value: 0.9471070537696531 and parameters: {'weight_class_0': 0.025934562909563714, 'weight_class_1': 0.6678181255109235, 'weight_class_2': 1.2132598545404645}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  52%|███████████████████████████████████████████████████████████████████▋                                                              | 1563/3000 [00:35<00:39, 36.62it/s]

[I 2026-07-05 15:25:50,172] Trial 1556 finished with value: 0.9489783296298081 and parameters: {'weight_class_0': 0.0433375453340526, 'weight_class_1': 1.5989641726631212, 'weight_class_2': 0.5459894979843726}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:50,195] Trial 1557 finished with value: 0.9478889483739975 and parameters: {'weight_class_0': 0.04281423438276831, 'weight_class_1': 0.6467221817078747, 'weight_class_2': 1.2332106131943303}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:50,227] Trial 1558 finished with value: 0.8897843766390644 and parameters: {'weight_class_0': 0.02573647557368773, 'weight_class_1': 0.6636373466107559, 'weight_class_2': 0.005192860396188268}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:50,270] Trial 1560 finished with value: 0.9494964318095439 and parameters: {'weight_class_0': 0.08400686425023758, 'weight_class_1': 1.0307658035579603, 'weight_class_2': 1.1388267373990355}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:50,274] Trial 1559 finished with value: 0.9477987161485499 and parameters: {'weight_class_0': 0.025300331655111443, 'weight_class_1': 0.6895634942497729, 'weight_class_2': 0.8827155237397544}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:50,283] Trial 1561 finished with value: 0.9481406928992411 and parameters: {'weight_class_0': 0.025677797795712567, 'weight_class_1': 1.0049850679308807, 'weight_class_2': 0.5759199111255402}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:50,341] Trial 1563 finished with value: 0.9475961760280288 and parameters: {'weight_class_0': 0.026504619710515803, 'weight_class_1': 0.9735168876088864, 'weight_class_2': 0.9140070456709852}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:50,347] Trial 1562 finished with value: 0.9253823962775675 and parameters: {'weight_class_0': 0.04141241558926233, 'weight_class_1': 1.103208943371815, 'weight_class_2': 7.366943621925394}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  52%|████████████████████████████████████████████████████████████████████                                                              | 1572/3000 [00:36<00:37, 38.23it/s]

[I 2026-07-05 15:25:50,368] Trial 1564 finished with value: 0.949050575641906 and parameters: {'weight_class_0': 0.08579766472508547, 'weight_class_1': 0.9481938364668752, 'weight_class_2': 0.5923194416808997}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:50,384] Trial 1565 finished with value: 0.9495610190883274 and parameters: {'weight_class_0': 0.04260462752661703, 'weight_class_1': 0.9856545628163844, 'weight_class_2': 0.5682635567738833}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:50,454] Trial 1566 finished with value: 0.9492825820321059 and parameters: {'weight_class_0': 0.07980587152852475, 'weight_class_1': 0.9746520041226622, 'weight_class_2': 0.5988475666918628}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:50,477] Trial 1567 finished with value: 0.9483426212881612 and parameters: {'weight_class_0': 0.07072134051377608, 'weight_class_1': 1.0267235631091518, 'weight_class_2': 0.37496311221109296}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:50,491] Trial 1568 finished with value: 0.9278916044018107 and parameters: {'weight_class_0': 0.0733106259608054, 'weight_class_1': 0.9820411649813482, 'weight_class_2': 0.11862105621175444}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:50,512] Trial 1569 finished with value: 0.9464442047196969 and parameters: {'weight_class_0': 0.07005154421610947, 'weight_class_1': 1.179603437353994, 'weight_class_2': 3.7908400643767415}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:50,523] Trial 1570 finished with value: 0.9156251826758544 and parameters: {'weight_class_0': 0.040999700300978735, 'weight_class_1': 0.9325596978237809, 'weight_class_2': 8.403675233248157}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:50,576] Trial 1571 finished with value: 0.9495072007343367 and parameters: {'weight_class_0': 0.03833784162561262, 'weight_class_1': 0.9469475171511503, 'weight_class_2': 0.3609412014072878}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:50,589] Trial 1572 finished with value: 0.949508129665296 and parameters: {'weight_class_0': 0.0397497885874487, 'weight_class_1': 0.9952164522414692, 'weight_class_2': 0.3699572747843365}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:25:50,594] Trial 1573 finished with value: 0.9179685492033233 and parameters: {'weight_class_0': 0.41851976591805684, 'weight_class_1': 0.9075329664307695, 'weight_class_2': 0.7078296855397636}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:50,669] Trial 1575 finished with value: 0.9482725483334734 and parameters: {'weight_class_0': 0.07160626850597387, 'weight_class_1': 1.2869436583911076, 'weight_class_2': 0.37363976132752624}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:50,671] Trial 1574 finished with value: 0.9487901712705478 and parameters: {'weight_class_0': 0.039914970329848434, 'weight_class_1': 1.2712101833859273, 'weight_class_2': 0.7701648663696975}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:50,687] Trial 1576 finished with value: 0.9387181745394733 and parameters: {'weight_class_0': 0.06937412977451769, 'weight_class_1': 0.1521211358936159, 'weight_class_2': 0.738973705590431}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:50,703] Trial 1577 finished with value: 0.930273671066255 and parameters: {'weight_class_0': 0.06860039839257757, 'weight_class_1': 1.2398366827451093, 'weight_class_2': 0.11960097854734819}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:50,752] Trial 1578 finished with value: 0.9492870899441367 and parameters: {'weight_class_0': 0.0401448801896629, 'weight_class_1': 0.7919237691313762, 'weight_class_2': 0.7185524645720746}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:50,753] Trial 1580 finished with value: 0.9492956728846167 and parameters: {'weight_class_0': 0.04092649584406211, 'weight_class_1': 0.7766528043252966, 'weight_class_2': 0.7260925549122098}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:50,775] Trial 1579 finished with value: 0.9247539802105965 and parameters: {'weight_class_0': 0.039709623197319015, 'weight_class_1': 0.052312966323771214, 'weight_class_2': 0.709640651677656}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  53%|████████████████████████████████████████████████████████████████████▊                                                             | 1588/3000 [00:36<00:37, 38.16it/s]

[I 2026-07-05 15:25:50,808] Trial 1581 finished with value: 0.9491386715196349 and parameters: {'weight_class_0': 0.03956021165322826, 'weight_class_1': 1.3075013558161388, 'weight_class_2': 0.3801271587774586}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:50,837] Trial 1582 finished with value: 0.9455400627306852 and parameters: {'weight_class_0': 0.010310100302019115, 'weight_class_1': 0.7507149512789965, 'weight_class_2': 0.08424420863466}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:50,900] Trial 1584 finished with value: 0.9484958111987293 and parameters: {'weight_class_0': 0.027461463480477184, 'weight_class_1': 0.777785447363815, 'weight_class_2': 0.682114192155676}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:50,907] Trial 1583 finished with value: 0.9447450391051714 and parameters: {'weight_class_0': 0.010747526142344005, 'weight_class_1': 0.7829135977371013, 'weight_class_2': 0.3861350057772846}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:50,909] Trial 1585 finished with value: 0.949314406543435 and parameters: {'weight_class_0': 0.04049775092528483, 'weight_class_1': 0.7992406461303202, 'weight_class_2': 0.7127665828237352}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:50,955] Trial 1586 finished with value: 0.9495092656507073 and parameters: {'weight_class_0': 0.02856431528832866, 'weight_class_1': 0.7484131852064654, 'weight_class_2': 0.36947673897827843}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:50,996] Trial 1587 finished with value: 0.9447430046471835 and parameters: {'weight_class_0': 0.02735999015916723, 'weight_class_1': 0.7187572506299674, 'weight_class_2': 0.08897942422143748}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:51,023] Trial 1588 finished with value: 0.949430378489228 and parameters: {'weight_class_0': 0.028646435973993883, 'weight_class_1': 0.8072030102156906, 'weight_class_2': 0.38268368617930143}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  53%|█████████████████████████████████████████████████████████████████████▏                                                            | 1597/3000 [00:36<00:36, 38.11it/s]

[I 2026-07-05 15:25:51,030] Trial 1589 finished with value: 0.9495691999147923 and parameters: {'weight_class_0': 0.028628480973141968, 'weight_class_1': 0.5795078348965059, 'weight_class_2': 0.38992231764589613}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:51,071] Trial 1590 finished with value: 0.9496482302653031 and parameters: {'weight_class_0': 0.03028855117445057, 'weight_class_1': 0.5860340117553089, 'weight_class_2': 0.3996037403943967}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:51,095] Trial 1591 finished with value: 0.9469905861147963 and parameters: {'weight_class_0': 0.0013863467016732925, 'weight_class_1': 0.009401949871598179, 'weight_class_2': 0.03682862735242952}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:51,122] Trial 1592 finished with value: 0.914659798766865 and parameters: {'weight_class_0': 0.002912015189288929, 'weight_class_1': 0.5042185158873902, 'weight_class_2': 0.0837645026988381}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:51,124] Trial 1593 finished with value: 0.9478303069225938 and parameters: {'weight_class_0': 0.09846244208371041, 'weight_class_1': 0.5708707989796071, 'weight_class_2': 0.5794264875248566}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:51,164] Trial 1594 finished with value: 0.9476689525987764 and parameters: {'weight_class_0': 0.09993542857236101, 'weight_class_1': 0.5732449616969343, 'weight_class_2': 0.5544250733503048}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:51,200] Trial 1595 finished with value: 0.9496232926471038 and parameters: {'weight_class_0': 0.04853086283372077, 'weight_class_1': 0.5871872520603499, 'weight_class_2': 0.5069815296369243}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:51,204] Trial 1597 finished with value: 0.9496653679146978 and parameters: {'weight_class_0': 0.04896481400302582, 'weight_class_1': 0.4777673622335594, 'weight_class_2': 0.5494038153048956}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:51,233] Trial 1596 finished with value: 0.9480037622715445 and parameters: {'weight_class_0': 0.10439096928641352, 'weight_class_1': 0.6053049974245411, 'weight_class_2': 1.5024088347121087}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  54%|█████████████████████████████████████████████████████████████████████▌                                                            | 1605/3000 [00:36<00:36, 37.93it/s]

[I 2026-07-05 15:25:51,250] Trial 1598 finished with value: 0.9497072866417348 and parameters: {'weight_class_0': 0.046731146478099894, 'weight_class_1': 0.5582604363976098, 'weight_class_2': 0.5488612400546877}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:51,297] Trial 1600 finished with value: 0.9039337245181036 and parameters: {'weight_class_0': 0.04937718051720735, 'weight_class_1': 0.3836102029074398, 'weight_class_2': 0.04044001587626534}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:51,330] Trial 1599 finished with value: 0.9496252154024099 and parameters: {'weight_class_0': 0.04719847708905532, 'weight_class_1': 0.5075363012927941, 'weight_class_2': 0.5501578018046929}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:51,337] Trial 1601 finished with value: 0.8759370641000824 and parameters: {'weight_class_0': 0.10407084104968399, 'weight_class_1': 0.009163729370419219, 'weight_class_2': 0.5313869929436889}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:51,376] Trial 1602 finished with value: 0.949680155027866 and parameters: {'weight_class_0': 0.04856892792239916, 'weight_class_1': 0.4873557544830212, 'weight_class_2': 0.5540404181328439}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:51,416] Trial 1603 finished with value: 0.9492068029509935 and parameters: {'weight_class_0': 0.049276489023515994, 'weight_class_1': 0.37730393141383894, 'weight_class_2': 0.5286188143515487}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:51,420] Trial 1605 finished with value: 0.947117792338333 and parameters: {'weight_class_0': 0.04821426359663123, 'weight_class_1': 0.44259885084169315, 'weight_class_2': 1.5470927906034435}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:51,429] Trial 1604 finished with value: 0.947501553844547 and parameters: {'weight_class_0': 0.05861867632448262, 'weight_class_1': 0.3954156664875243, 'weight_class_2': 0.283013046981386}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  54%|█████████████████████████████████████████████████████████████████████▉                                                            | 1614/3000 [00:37<00:35, 38.81it/s]

[I 2026-07-05 15:25:51,472] Trial 1606 finished with value: 0.9468692276353746 and parameters: {'weight_class_0': 0.06320185762508594, 'weight_class_1': 0.3930983249819344, 'weight_class_2': 0.28463616033591094}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:51,512] Trial 1607 finished with value: 0.9474050286934412 and parameters: {'weight_class_0': 0.06248770209116999, 'weight_class_1': 0.40100382069747553, 'weight_class_2': 0.3022570308618641}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:51,556] Trial 1608 finished with value: 0.9480061528548246 and parameters: {'weight_class_0': 0.057324862707657555, 'weight_class_1': 0.4205873871346414, 'weight_class_2': 0.2961568839459428}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:51,561] Trial 1609 finished with value: 0.9468579103690483 and parameters: {'weight_class_0': 0.06184136966405715, 'weight_class_1': 0.38944762525695364, 'weight_class_2': 0.27471221683082525}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:51,570] Trial 1610 finished with value: 0.9407763696068323 and parameters: {'weight_class_0': 0.05803945270460921, 'weight_class_1': 0.1573660254655135, 'weight_class_2': 0.28797407590214863}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:51,603] Trial 1611 finished with value: 0.9495745146653293 and parameters: {'weight_class_0': 0.033932031488981926, 'weight_class_1': 0.3918574407371229, 'weight_class_2': 0.29124498246046154}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:51,655] Trial 1612 finished with value: 0.9466282606906494 and parameters: {'weight_class_0': 0.0622083693950833, 'weight_class_1': 0.3933592080049707, 'weight_class_2': 0.26497957768441943}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:51,666] Trial 1613 finished with value: 0.946567594167068 and parameters: {'weight_class_0': 0.06543978677106953, 'weight_class_1': 0.39159851030826925, 'weight_class_2': 0.2801315158607451}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:51,671] Trial 1614 finished with value: 0.9299809832813214 and parameters: {'weight_class_0': 0.05884345537083499, 'weight_class_1': 0.09701126717141985, 'weight_class_2': 0.28259433702613396}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  54%|██████████████████████████████████████████████████████████████████████▎                                                           | 1622/3000 [00:37<00:36, 37.84it/s]

[I 2026-07-05 15:25:51,739] Trial 1615 finished with value: 0.938484151214114 and parameters: {'weight_class_0': 0.061058158380862204, 'weight_class_1': 0.14774511152406883, 'weight_class_2': 0.2815257565055005}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:51,750] Trial 1616 finished with value: 0.9472525496956562 and parameters: {'weight_class_0': 0.03489663759506838, 'weight_class_1': 0.1539000241328835, 'weight_class_2': 0.2883627762889263}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:51,784] Trial 1617 finished with value: 0.9444237775466026 and parameters: {'weight_class_0': 0.03608417455817312, 'weight_class_1': 0.1349582017469664, 'weight_class_2': 0.9233523575799696}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:51,803] Trial 1618 finished with value: 0.946985391659438 and parameters: {'weight_class_0': 0.03442429811168245, 'weight_class_1': 0.14605968627113364, 'weight_class_2': 0.43496347383268025}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:51,815] Trial 1619 finished with value: 0.9497339920291991 and parameters: {'weight_class_0': 0.03495364847897358, 'weight_class_1': 0.6365346666204659, 'weight_class_2': 0.3369122092569578}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:51,849] Trial 1620 finished with value: 0.9426293107088298 and parameters: {'weight_class_0': 0.03547930321081526, 'weight_class_1': 0.09899486793567225, 'weight_class_2': 0.4390034220007678}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:51,874] Trial 1621 finished with value: 0.9478829133473474 and parameters: {'weight_class_0': 0.025687664426569133, 'weight_class_1': 0.6714127943678309, 'weight_class_2': 0.8748562902654557}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:51,889] Trial 1623 finished with value: 0.7723632149230792 and parameters: {'weight_class_0': 0.0035024523001344118, 'weight_class_1': 1.7687148611590156, 'weight_class_2': 0.441539966140156}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  54%|██████████████████████████████████████████████████████████████████████▋                                                           | 1630/3000 [00:37<00:38, 35.37it/s]

[I 2026-07-05 15:25:51,900] Trial 1622 finished with value: 0.9459049331069077 and parameters: {'weight_class_0': 0.024470401316542573, 'weight_class_1': 1.7460458383258437, 'weight_class_2': 0.4040634846834657}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:51,943] Trial 1624 finished with value: 0.9477837977712894 and parameters: {'weight_class_0': 0.024691517414086296, 'weight_class_1': 0.6793691946793865, 'weight_class_2': 0.8766527124441059}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:51,970] Trial 1625 finished with value: 0.9497215218260614 and parameters: {'weight_class_0': 0.03546605846987842, 'weight_class_1': 0.6850798451469159, 'weight_class_2': 0.4394541153384096}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:51,990] Trial 1626 finished with value: 0.9496601338497258 and parameters: {'weight_class_0': 0.03659279155382737, 'weight_class_1': 0.703434162142265, 'weight_class_2': 0.4687853777285095}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:51,995] Trial 1627 finished with value: 0.9497066425594541 and parameters: {'weight_class_0': 0.03574761246662029, 'weight_class_1': 0.7096405213774791, 'weight_class_2': 0.44459806449422656}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:52,056] Trial 1628 finished with value: 0.9490847079650324 and parameters: {'weight_class_0': 0.02438975979936361, 'weight_class_1': 0.7104408688131653, 'weight_class_2': 0.43000994945985777}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:52,105] Trial 1630 finished with value: 0.9478482404657754 and parameters: {'weight_class_0': 0.024302615026289928, 'weight_class_1': 0.7248322497627832, 'weight_class_2': 0.8635125095485068}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:52,123] Trial 1629 finished with value: 0.9452265298714077 and parameters: {'weight_class_0': 0.1338596812060611, 'weight_class_1': 1.7446555224878824, 'weight_class_2': 0.4455501180162121}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  55%|██████████████████████████████████████████████████████████████████████▉                                                           | 1637/3000 [00:37<00:40, 33.87it/s]

[I 2026-07-05 15:25:52,147] Trial 1631 finished with value: 0.9455645992584496 and parameters: {'weight_class_0': 0.023909469760260912, 'weight_class_1': 1.5641889743710296, 'weight_class_2': 0.8635270751544597}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:52,179] Trial 1632 finished with value: 0.9485065063026575 and parameters: {'weight_class_0': 0.024706172489527112, 'weight_class_1': 0.7384922534505556, 'weight_class_2': 0.5984836587996538}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:52,211] Trial 1633 finished with value: 0.9492565160798613 and parameters: {'weight_class_0': 0.08141308018343688, 'weight_class_1': 0.7399205141125026, 'weight_class_2': 0.6180551992176876}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:52,215] Trial 1634 finished with value: 0.9036120562479142 and parameters: {'weight_class_0': 0.08159911049211876, 'weight_class_1': 1.139107140425355, 'weight_class_2': 0.06538705975713328}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:52,263] Trial 1635 finished with value: 0.9492692007827582 and parameters: {'weight_class_0': 0.08579755966135891, 'weight_class_1': 0.7882257853386495, 'weight_class_2': 0.6525795303114349}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:52,281] Trial 1636 finished with value: 0.9495785249658901 and parameters: {'weight_class_0': 0.04514485977722312, 'weight_class_1': 0.8604187099622702, 'weight_class_2': 0.6250387493606004}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:52,340] Trial 1637 finished with value: 0.8880058337604084 and parameters: {'weight_class_0': 0.08121641219292644, 'weight_class_1': 0.4839422173926776, 'weight_class_2': 0.00869690948862615}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  55%|███████████████████████████████████████████████████████████████████████▏                                                          | 1644/3000 [00:38<00:40, 33.47it/s]

[I 2026-07-05 15:25:52,350] Trial 1638 finished with value: 0.9493896609281686 and parameters: {'weight_class_0': 0.04502276516078226, 'weight_class_1': 0.5087716466369405, 'weight_class_2': 0.35694914368084807}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:52,395] Trial 1639 finished with value: 0.9493742029248805 and parameters: {'weight_class_0': 0.08173045159772101, 'weight_class_1': 1.1345203607087533, 'weight_class_2': 0.6367109897889895}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:52,404] Trial 1640 finished with value: 0.9169459130076166 and parameters: {'weight_class_0': 0.04155002168865128, 'weight_class_1': 0.042298134796540404, 'weight_class_2': 0.6157665181627215}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:52,454] Trial 1642 finished with value: 0.9495055891687794 and parameters: {'weight_class_0': 0.043587128396198334, 'weight_class_1': 0.8645654762330511, 'weight_class_2': 0.6724783323953778}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:52,475] Trial 1641 finished with value: 0.9493697671797285 and parameters: {'weight_class_0': 0.0839178532850224, 'weight_class_1': 1.2241876817539261, 'weight_class_2': 0.6348069040830171}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:52,482] Trial 1643 finished with value: 0.9494614056362961 and parameters: {'weight_class_0': 0.04226840430472549, 'weight_class_1': 0.4728933855369505, 'weight_class_2': 0.3500375306836944}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:52,506] Trial 1644 finished with value: 0.9431337686945026 and parameters: {'weight_class_0': 0.04277676082747993, 'weight_class_1': 0.4936381675709466, 'weight_class_2': 0.12107547056615052}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  55%|███████████████████████████████████████████████████████████████████████▋                                                          | 1653/3000 [00:38<00:37, 35.78it/s]

[I 2026-07-05 15:25:52,580] Trial 1645 finished with value: 0.9497490832821023 and parameters: {'weight_class_0': 0.029915612523777047, 'weight_class_1': 0.5257020634608615, 'weight_class_2': 0.36017943775551464}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:52,613] Trial 1646 finished with value: 0.8940284028801382 and parameters: {'weight_class_0': 0.02969924319567051, 'weight_class_1': 0.4877241751832539, 'weight_class_2': 0.00892846420971481}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:52,621] Trial 1647 finished with value: 0.9497449231131232 and parameters: {'weight_class_0': 0.030422788159987425, 'weight_class_1': 0.5775736593573662, 'weight_class_2': 0.3355530920689038}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:52,657] Trial 1648 finished with value: 0.949526831576717 and parameters: {'weight_class_0': 0.03127836271278208, 'weight_class_1': 0.909207637942743, 'weight_class_2': 0.3517796023674322}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:52,697] Trial 1650 finished with value: 0.9106513181455197 and parameters: {'weight_class_0': 0.030476998241889663, 'weight_class_1': 0.02388974281313915, 'weight_class_2': 0.3684396289046355}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:52,698] Trial 1649 finished with value: 0.9497820615728959 and parameters: {'weight_class_0': 0.029900179214031746, 'weight_class_1': 0.5024585925740073, 'weight_class_2': 0.36040109099709317}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:52,731] Trial 1651 finished with value: 0.9483614429349606 and parameters: {'weight_class_0': 0.010622589600700642, 'weight_class_1': 0.4991381415594075, 'weight_class_2': 0.12659631882541794}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:52,752] Trial 1652 finished with value: 0.9497961885360621 and parameters: {'weight_class_0': 0.03007752352581975, 'weight_class_1': 0.6016430795067504, 'weight_class_2': 0.34747957402139235}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:52,820] Trial 1654 finished with value: 0.9498072793984358 and parameters: {'weight_class_0': 0.03065961463343742, 'weight_class_1': 0.6025093681476148, 'weight_class_2': 0.3535134398991708}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:25:52,845] Trial 1653 finished with value: 0.9096825877226995 and parameters: {'weight_class_0': 0.032499828984425966, 'weight_class_1': 0.02441077527470768, 'weight_class_2': 0.3464003375258753}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:52,866] Trial 1655 finished with value: 0.9364899583593517 and parameters: {'weight_class_0': 0.010531577425745592, 'weight_class_1': 0.023684175665569043, 'weight_class_2': 0.4933594306144352}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:52,872] Trial 1656 finished with value: 0.9491050885071598 and parameters: {'weight_class_0': 0.02969947337529007, 'weight_class_1': 0.8896463385092469, 'weight_class_2': 0.5069650441509964}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:52,951] Trial 1657 finished with value: 0.8995589750058328 and parameters: {'weight_class_0': 0.04653403458138356, 'weight_class_1': 0.021793934928184756, 'weight_class_2': 0.5227707840509608}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:52,974] Trial 1658 finished with value: 0.9494050022674729 and parameters: {'weight_class_0': 0.05053755215608482, 'weight_class_1': 1.419456353417104, 'weight_class_2': 0.5021223956010706}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:52,993] Trial 1659 finished with value: 0.9496555981100684 and parameters: {'weight_class_0': 0.048848809325841, 'weight_class_1': 0.6016972492777432, 'weight_class_2': 0.5140622193505986}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:53,016] Trial 1661 finished with value: 0.9496528619826217 and parameters: {'weight_class_0': 0.048798760529610435, 'weight_class_1': 0.6194388373922998, 'weight_class_2': 0.5088231931277183}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:25:53,021] Trial 1660 finished with value: 0.907449793831784 and parameters: {'weight_class_0': 0.04986770416672354, 'weight_class_1': 0.03416788444956393, 'weight_class_2': 0.5056083036922656}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:53,058] Trial 1662 finished with value: 0.9492627325862792 and parameters: {'weight_class_0': 0.04959765372925499, 'weight_class_1': 1.4461378521295136, 'weight_class_2': 0.7804943348059921}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:53,090] Trial 1663 finished with value: 0.9494216502700062 and parameters: {'weight_class_0': 0.05151166362614791, 'weight_class_1': 1.453736139613639, 'weight_class_2': 0.4790509947131514}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:53,109] Trial 1665 finished with value: 0.9488868385571202 and parameters: {'weight_class_0': 0.023482331596708816, 'weight_class_1': 0.6250497673184369, 'weight_class_2': 0.47402286615241035}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:53,115] Trial 1664 finished with value: 0.9497316336185943 and parameters: {'weight_class_0': 0.052065901801909585, 'weight_class_1': 0.8796004417285948, 'weight_class_2': 0.48638146817941114}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:53,168] Trial 1667 finished with value: 0.9492888153904541 and parameters: {'weight_class_0': 0.024733840804543834, 'weight_class_1': 0.5952346480171635, 'weight_class_2': 0.40100727652231116}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:53,180] Trial 1666 finished with value: 0.949202980617026 and parameters: {'weight_class_0': 0.02441792968875394, 'weight_class_1': 0.5985447989673826, 'weight_class_2': 0.4339187767942612}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:53,206] Trial 1668 finished with value: 0.9491741752758355 and parameters: {'weight_class_0': 0.023340614870559325, 'weight_class_1': 0.5896312666402375, 'weight_class_2': 0.415685317450717}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:25:53,251] Trial 1669 finished with value: 0.9498062908017566 and parameters: {'weight_class_0': 0.037454253321330705, 'weight_class_1': 0.6396106843140199, 'weight_class_2': 0.4160639060705988}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:53,293] Trial 1670 finished with value: 0.9496063851153732 and parameters: {'weight_class_0': 0.03785747511267841, 'weight_class_1': 0.5674047560862165, 'weight_class_2': 0.38040643454996675}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:53,313] Trial 1671 finished with value: 0.949198215882754 and parameters: {'weight_class_0': 0.023820495694287583, 'weight_class_1': 0.6328005089356984, 'weight_class_2': 0.3978601605865243}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:53,353] Trial 1672 finished with value: 0.9493320849723572 and parameters: {'weight_class_0': 0.02376029560954881, 'weight_class_1': 0.5633708988424306, 'weight_class_2': 0.3890359427876853}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:53,373] Trial 1673 finished with value: 0.9492621741324481 and parameters: {'weight_class_0': 0.023272956631170814, 'weight_class_1': 0.5902775564758229, 'weight_class_2': 0.38395704503269257}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:53,396] Trial 1674 finished with value: 0.9498115123916334 and parameters: {'weight_class_0': 0.03553936625340993, 'weight_class_1': 0.5547436092620277, 'weight_class_2': 0.39478731969785513}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:53,423] Trial 1675 finished with value: 0.8676167281043708 and parameters: {'weight_class_0': 0.5612694414619502, 'weight_class_1': 0.590421297188362, 'weight_class_2': 0.3387600600638768}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  56%|████████████████████████████████████████████████████████████████████████▉                                                         | 1683/3000 [00:39<00:36, 35.84it/s]

[I 2026-07-05 15:25:53,458] Trial 1676 finished with value: 0.9496634923987557 and parameters: {'weight_class_0': 0.037656706209636306, 'weight_class_1': 0.58419012001618, 'weight_class_2': 0.33179024164943494}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:53,464] Trial 1677 finished with value: 0.9495842388696185 and parameters: {'weight_class_0': 0.03852398147457164, 'weight_class_1': 0.870447244587447, 'weight_class_2': 0.3526963784796151}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:53,511] Trial 1679 finished with value: 0.9496577675334222 and parameters: {'weight_class_0': 0.036807433397508825, 'weight_class_1': 0.8221547548738328, 'weight_class_2': 0.35542935966201306}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:53,518] Trial 1678 finished with value: 0.8947015860947737 and parameters: {'weight_class_0': 0.03764139537180469, 'weight_class_1': 0.8150670518611497, 'weight_class_2': 0.013799747503453547}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:53,579] Trial 1680 finished with value: 0.9494428494529675 and parameters: {'weight_class_0': 0.03958738546394193, 'weight_class_1': 0.8098746611246651, 'weight_class_2': 0.32433249579568063}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:53,598] Trial 1681 finished with value: 0.949566592385973 and parameters: {'weight_class_0': 0.03765373486095973, 'weight_class_1': 0.8249384273564778, 'weight_class_2': 0.33153093525298777}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:53,621] Trial 1682 finished with value: 0.9494586817060052 and parameters: {'weight_class_0': 0.03993236046912688, 'weight_class_1': 0.8435700076037848, 'weight_class_2': 0.3341509586581393}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:53,670] Trial 1683 finished with value: 0.9495174789156867 and parameters: {'weight_class_0': 0.03844640138964741, 'weight_class_1': 0.8170966664328849, 'weight_class_2': 0.3287757698607874}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:25:53,680] Trial 1684 finished with value: 0.9494434646227362 and parameters: {'weight_class_0': 0.04040646409820708, 'weight_class_1': 0.8717750962118224, 'weight_class_2': 0.594797182427734}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:53,692] Trial 1685 finished with value: 0.9453367938398424 and parameters: {'weight_class_0': 0.038280274081484975, 'weight_class_1': 0.8160016287137841, 'weight_class_2': 2.8031157062101464}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:53,721] Trial 1686 finished with value: 0.9494589607497365 and parameters: {'weight_class_0': 0.03828847529131919, 'weight_class_1': 0.8179956948888583, 'weight_class_2': 0.6026255428645351}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:53,769] Trial 1687 finished with value: 0.9494848340400531 and parameters: {'weight_class_0': 0.040077933146527606, 'weight_class_1': 0.8244692473041368, 'weight_class_2': 0.5845220760840605}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:53,810] Trial 1688 finished with value: 0.9492514796042743 and parameters: {'weight_class_0': 0.035207430100066495, 'weight_class_1': 0.7607384667523406, 'weight_class_2': 0.631801624736701}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:53,836] Trial 1690 finished with value: 0.9493415451296533 and parameters: {'weight_class_0': 0.04003050240212271, 'weight_class_1': 0.9646949374206295, 'weight_class_2': 0.6018001466527408}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:53,849] Trial 1689 finished with value: 0.826761672294169 and parameters: {'weight_class_0': 4.87044459994596, 'weight_class_1': 1.143857182661745, 'weight_class_2': 0.592376159324888}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  57%|█████████████████████████████████████████████████████████████████████████▌                                                        | 1697/3000 [00:39<00:37, 34.72it/s]

[I 2026-07-05 15:25:53,863] Trial 1691 finished with value: 0.949332361568783 and parameters: {'weight_class_0': 0.04233688944619708, 'weight_class_1': 1.1090007027046849, 'weight_class_2': 0.6291904604569729}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:53,927] Trial 1693 finished with value: 0.9493395857028202 and parameters: {'weight_class_0': 0.0435684672007262, 'weight_class_1': 1.1264175074160176, 'weight_class_2': 0.6712243225632085}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:53,946] Trial 1692 finished with value: 0.9494564769576511 and parameters: {'weight_class_0': 0.04312355296270806, 'weight_class_1': 1.1181107333770572, 'weight_class_2': 0.5945340960749133}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:53,949] Trial 1694 finished with value: 0.9494606759699189 and parameters: {'weight_class_0': 0.04285887557332947, 'weight_class_1': 1.0467208843347084, 'weight_class_2': 0.5894653070082291}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:53,971] Trial 1695 finished with value: 0.9470839152858543 and parameters: {'weight_class_0': 0.060095705365506506, 'weight_class_1': 1.1568032950556164, 'weight_class_2': 2.7347175862085553}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:54,016] Trial 1696 finished with value: 0.9497298893700714 and parameters: {'weight_class_0': 0.06103494935726517, 'weight_class_1': 1.0921853789573153, 'weight_class_2': 0.7626342853130564}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:54,032] Trial 1697 finished with value: 0.949741850312344 and parameters: {'weight_class_0': 0.06116572519177914, 'weight_class_1': 1.089390216987752, 'weight_class_2': 0.7291373281166577}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  57%|█████████████████████████████████████████████████████████████████████████▉                                                        | 1705/3000 [00:39<00:37, 34.09it/s]

[I 2026-07-05 15:25:54,075] Trial 1698 finished with value: 0.9497208577388706 and parameters: {'weight_class_0': 0.06811404802719856, 'weight_class_1': 1.0297988732000498, 'weight_class_2': 0.7240708577684903}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:54,126] Trial 1699 finished with value: 0.9495907408882435 and parameters: {'weight_class_0': 0.05820030090285551, 'weight_class_1': 1.0891279591066796, 'weight_class_2': 0.8024623688412517}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:54,141] Trial 1701 finished with value: 0.9492627917408772 and parameters: {'weight_class_0': 0.060643852984920574, 'weight_class_1': 1.0838268071803139, 'weight_class_2': 1.0831547345025758}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:54,170] Trial 1700 finished with value: 0.9168279959288915 and parameters: {'weight_class_0': 0.0589314323937212, 'weight_class_1': 9.880578084902837, 'weight_class_2': 0.7890573324018771}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:54,197] Trial 1702 finished with value: 0.9493169343490923 and parameters: {'weight_class_0': 0.05806293970737885, 'weight_class_1': 0.6802834116299994, 'weight_class_2': 0.444406756110599}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:54,227] Trial 1703 finished with value: 0.9494449584972134 and parameters: {'weight_class_0': 0.05780920791396893, 'weight_class_1': 0.6641941016438418, 'weight_class_2': 0.7953319127520604}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:54,283] Trial 1705 finished with value: 0.9491355190607917 and parameters: {'weight_class_0': 0.0606726939198608, 'weight_class_1': 0.6967616261005267, 'weight_class_2': 0.4380017448322415}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:54,296] Trial 1704 finished with value: 0.8479153851966715 and parameters: {'weight_class_0': 0.05560163907302036, 'weight_class_1': 0.003763248240139047, 'weight_class_2': 1.1146808351820356}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  57%|██████████████████████████████████████████████████████████████████████████▏                                                       | 1713/3000 [00:39<00:39, 32.55it/s]

[I 2026-07-05 15:25:54,312] Trial 1706 finished with value: 0.9494823998468025 and parameters: {'weight_class_0': 0.05731787108488371, 'weight_class_1': 0.6801176241799523, 'weight_class_2': 0.4742843360901812}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:54,341] Trial 1707 finished with value: 0.9495506539807401 and parameters: {'weight_class_0': 0.0521086308679239, 'weight_class_1': 0.7014460102044958, 'weight_class_2': 0.4545602824996331}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:54,408] Trial 1709 finished with value: 0.9494685430270137 and parameters: {'weight_class_0': 0.03094717298094544, 'weight_class_1': 0.6825057799220065, 'weight_class_2': 0.4730607461093209}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:54,421] Trial 1708 finished with value: 0.9495747116090092 and parameters: {'weight_class_0': 0.051145458709640906, 'weight_class_1': 0.6902920369848868, 'weight_class_2': 0.4489305580157476}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:54,459] Trial 1710 finished with value: 0.9486715574969109 and parameters: {'weight_class_0': 0.05025559153602803, 'weight_class_1': 0.6940513699392419, 'weight_class_2': 1.0483568477852185}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:54,464] Trial 1711 finished with value: 0.9494422867255637 and parameters: {'weight_class_0': 0.0322629792259374, 'weight_class_1': 0.6978666428449617, 'weight_class_2': 0.46206043025359234}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:54,501] Trial 1713 finished with value: 0.9496908054233121 and parameters: {'weight_class_0': 0.047397890081514384, 'weight_class_1': 0.6821970436070132, 'weight_class_2': 0.46828394342460355}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:54,506] Trial 1712 finished with value: 0.9496550399694796 and parameters: {'weight_class_0': 0.04784790980271678, 'weight_class_1': 0.7178932500979076, 'weight_class_2': 0.45395117018884296}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  57%|██████████████████████████████████████████████████████████████████████████▌                                                       | 1720/3000 [00:40<00:37, 34.05it/s]

[I 2026-07-05 15:25:54,552] Trial 1714 finished with value: 0.949482419086258 and parameters: {'weight_class_0': 0.03175303875874172, 'weight_class_1': 0.7010420620665372, 'weight_class_2': 0.4546378007136189}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:54,553] Trial 1715 finished with value: 0.9493371598727983 and parameters: {'weight_class_0': 0.029883105421415278, 'weight_class_1': 0.6997463956005054, 'weight_class_2': 0.49119750640569576}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:54,611] Trial 1716 finished with value: 0.8859617866645567 and parameters: {'weight_class_0': 0.031404602334452816, 'weight_class_1': 0.007260365461260076, 'weight_class_2': 0.4529353034690411}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:54,625] Trial 1717 finished with value: 0.7040497567120906 and parameters: {'weight_class_0': 0.0011103730964089115, 'weight_class_1': 0.6904379547125449, 'weight_class_2': 0.43890393637872743}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:54,640] Trial 1718 finished with value: 0.9493749761255555 and parameters: {'weight_class_0': 0.030728085050123144, 'weight_class_1': 0.6943088778166072, 'weight_class_2': 0.503309235668514}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:54,686] Trial 1719 finished with value: 0.9493045900134249 and parameters: {'weight_class_0': 0.03056553371064873, 'weight_class_1': 0.5001419669915507, 'weight_class_2': 0.5246248120720293}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:54,754] Trial 1722 finished with value: 0.949312295264131 and parameters: {'weight_class_0': 0.030333290736712173, 'weight_class_1': 0.4694327947035749, 'weight_class_2': 0.5186810115389948}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  58%|██████████████████████████████████████████████████████████████████████████▉                                                       | 1728/3000 [00:40<00:36, 34.57it/s]

[I 2026-07-05 15:25:54,757] Trial 1720 finished with value: 0.9492462873385618 and parameters: {'weight_class_0': 0.028608284836768316, 'weight_class_1': 0.4798056350966915, 'weight_class_2': 0.5106579957145657}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:54,766] Trial 1721 finished with value: 0.94596293866359 and parameters: {'weight_class_0': 0.02996355827170059, 'weight_class_1': 2.1127238691909747, 'weight_class_2': 0.5163959324727628}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:54,808] Trial 1723 finished with value: 0.9493328207968902 and parameters: {'weight_class_0': 0.031233168593984773, 'weight_class_1': 0.4814552500582973, 'weight_class_2': 0.5148143444815165}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:54,816] Trial 1724 finished with value: 0.7465686194871696 and parameters: {'weight_class_0': 0.03467169171544858, 'weight_class_1': 2.2258100357363633, 'weight_class_2': 0.0021145891957686557}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:54,865] Trial 1725 finished with value: 0.9486325555054494 and parameters: {'weight_class_0': 0.07191542949243482, 'weight_class_1': 0.4600914450671098, 'weight_class_2': 0.5513903228187668}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:54,875] Trial 1726 finished with value: 0.94786361713201 and parameters: {'weight_class_0': 0.0743113856834126, 'weight_class_1': 0.49578033313908115, 'weight_class_2': 0.3960779868620489}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:54,946] Trial 1727 finished with value: 0.9494137923270376 and parameters: {'weight_class_0': 0.03440705562364295, 'weight_class_1': 0.47645625193428365, 'weight_class_2': 0.531001378026151}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:54,971] Trial 1728 finished with value: 0.9488450988547709 and parameters: {'weight_class_0': 0.043808357274413935, 'weight_class_1': 0.5380991196863177, 'weight_class_2': 0.26616151190393683}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  58%|███████████████████████████████████████████████████████████████████████████▎                                                      | 1737/3000 [00:40<00:34, 36.50it/s]

[I 2026-07-05 15:25:54,984] Trial 1729 finished with value: 0.9494969618103234 and parameters: {'weight_class_0': 0.0452345605130374, 'weight_class_1': 0.47417011392700353, 'weight_class_2': 0.38963989968547236}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:54,989] Trial 1730 finished with value: 0.9480157429760295 and parameters: {'weight_class_0': 0.07300666123014324, 'weight_class_1': 0.4908794943089556, 'weight_class_2': 0.39961219049556607}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:55,017] Trial 1731 finished with value: 0.9458627692523757 and parameters: {'weight_class_0': 0.07183188303162803, 'weight_class_1': 0.5218649450903373, 'weight_class_2': 0.2640168406894751}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:55,046] Trial 1732 finished with value: 0.9488088539917183 and parameters: {'weight_class_0': 0.0421442331739314, 'weight_class_1': 0.8814528513805543, 'weight_class_2': 0.9214554345724731}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:55,084] Trial 1733 finished with value: 0.9495777917445851 and parameters: {'weight_class_0': 0.04463925057389564, 'weight_class_1': 0.9751973863294345, 'weight_class_2': 0.3935418807243996}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:55,128] Trial 1734 finished with value: 0.9496077748801516 and parameters: {'weight_class_0': 0.04351301262006009, 'weight_class_1': 0.926497276851443, 'weight_class_2': 0.39628025815889273}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:55,143] Trial 1735 finished with value: 0.8874538225621716 and parameters: {'weight_class_0': 0.04512672960304807, 'weight_class_1': 0.9579574636919548, 'weight_class_2': 0.006535533206446851}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:55,184] Trial 1736 finished with value: 0.9488784628226284 and parameters: {'weight_class_0': 0.04456432981015749, 'weight_class_1': 0.9179116459917855, 'weight_class_2': 0.9433879640659834}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:55,206] Trial 1737 finished with value: 0.9486328205616547 and parameters: {'weight_class_0': 0.04483703000714212, 'weight_class_1': 0.9478771467009198, 'weight_class_2': 0.26757628986688387}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:25:55,243] Trial 1738 finished with value: 0.9485965879232858 and parameters: {'weight_class_0': 0.045440370678303296, 'weight_class_1': 0.9252935153359824, 'weight_class_2': 0.2659030670072837}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:55,266] Trial 1739 finished with value: 0.9489760826226733 and parameters: {'weight_class_0': 0.047415107969244225, 'weight_class_1': 0.8823902200488565, 'weight_class_2': 0.9637066906598114}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:55,300] Trial 1740 finished with value: 0.8423393544770409 and parameters: {'weight_class_0': 0.03980298555141264, 'weight_class_1': 0.0026164852564094154, 'weight_class_2': 0.8623319270847233}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:55,347] Trial 1741 finished with value: 0.9479794098957957 and parameters: {'weight_class_0': 0.13489289158937273, 'weight_class_1': 0.9415239735612712, 'weight_class_2': 0.7134144720218528}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:55,379] Trial 1742 finished with value: 0.9493835580457826 and parameters: {'weight_class_0': 0.045996536758194456, 'weight_class_1': 0.9423592538052491, 'weight_class_2': 0.7649887452028719}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:55,402] Trial 1744 finished with value: 0.9307014220130344 and parameters: {'weight_class_0': 0.04752280725387627, 'weight_class_1': 0.07604456753392227, 'weight_class_2': 0.6800477142230467}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:55,413] Trial 1745 finished with value: 0.9484718253382528 and parameters: {'weight_class_0': 0.036093597000846765, 'weight_class_1': 1.3812234027255108, 'weight_class_2': 0.7011941953278246}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:25:55,414] Trial 1743 finished with value: 0.9490048375856116 and parameters: {'weight_class_0': 0.1028456291902135, 'weight_class_1': 0.9013601305425466, 'weight_class_2': 0.7293043353291062}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:55,455] Trial 1746 finished with value: 0.948388448574176 and parameters: {'weight_class_0': 0.03659537555440978, 'weight_class_1': 1.4663653617669432, 'weight_class_2': 0.6947137388545805}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:55,497] Trial 1747 finished with value: 0.949096978015057 and parameters: {'weight_class_0': 0.03839342442555881, 'weight_class_1': 0.5805470880006063, 'weight_class_2': 0.7136480295684537}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:55,504] Trial 1748 finished with value: 0.9486870270569677 and parameters: {'weight_class_0': 0.0372224918546622, 'weight_class_1': 1.3629688647675855, 'weight_class_2': 0.6773394092509873}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:55,526] Trial 1749 finished with value: 0.9489496731734216 and parameters: {'weight_class_0': 0.03580656206615316, 'weight_class_1': 0.5950711541310566, 'weight_class_2': 0.7252639946614748}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:55,599] Trial 1751 finished with value: 0.948265204861214 and parameters: {'weight_class_0': 0.035398549320153606, 'weight_class_1': 1.3954341804804615, 'weight_class_2': 0.742291079698658}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:55,601] Trial 1750 finished with value: 0.9492737345972729 and parameters: {'weight_class_0': 0.09666146205664192, 'weight_class_1': 1.3298796540150966, 'weight_class_2': 0.7081691105653507}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:55,642] Trial 1752 finished with value: 0.9485599916449612 and parameters: {'weight_class_0': 0.036252853262446975, 'weight_class_1': 1.3967129045932627, 'weight_class_2': 0.6611390712473552}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  59%|████████████████████████████████████████████████████████████████████████████▎                                                     | 1760/3000 [00:41<00:35, 34.85it/s]

[I 2026-07-05 15:25:55,657] Trial 1753 finished with value: 0.94883287352626 and parameters: {'weight_class_0': 0.03560928906566498, 'weight_class_1': 1.332371418532877, 'weight_class_2': 0.32414833691566053}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:55,707] Trial 1754 finished with value: 0.9496924597031894 and parameters: {'weight_class_0': 0.027366289923848743, 'weight_class_1': 0.5862039112216181, 'weight_class_2': 0.33059819404786117}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:55,723] Trial 1755 finished with value: 0.918483923176523 and parameters: {'weight_class_0': 0.21785070940385923, 'weight_class_1': 0.61465245400748, 'weight_class_2': 0.3285461140889358}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:55,740] Trial 1756 finished with value: 0.9497557643925038 and parameters: {'weight_class_0': 0.02769259499265505, 'weight_class_1': 0.6111838881075317, 'weight_class_2': 0.32736999817322526}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:55,774] Trial 1757 finished with value: 0.9478694397916277 and parameters: {'weight_class_0': 0.0684763457737704, 'weight_class_1': 0.5785493162759267, 'weight_class_2': 0.33206219836410333}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:55,838] Trial 1758 finished with value: 0.9497502068821831 and parameters: {'weight_class_0': 0.027130844854688283, 'weight_class_1': 0.6055894150903249, 'weight_class_2': 0.31741111760374435}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:55,881] Trial 1759 finished with value: 0.9497333911621899 and parameters: {'weight_class_0': 0.026678813250058955, 'weight_class_1': 0.6052591529705175, 'weight_class_2': 0.2986789689953889}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:55,883] Trial 1760 finished with value: 0.9363711299985861 and parameters: {'weight_class_0': 0.027147076158683944, 'weight_class_1': 0.053271221900445344, 'weight_class_2': 0.34303819031608723}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  59%|████████████████████████████████████████████████████████████████████████████▌                                                     | 1768/3000 [00:41<00:35, 35.12it/s]

[I 2026-07-05 15:25:55,894] Trial 1761 finished with value: 0.9494549775451252 and parameters: {'weight_class_0': 0.027048464991498277, 'weight_class_1': 0.5850078297825801, 'weight_class_2': 0.3844084881103748}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:55,935] Trial 1762 finished with value: 0.9496578118640294 and parameters: {'weight_class_0': 0.026620652460577505, 'weight_class_1': 0.5981867070596671, 'weight_class_2': 0.33404227435752976}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:55,971] Trial 1763 finished with value: 0.949789492033629 and parameters: {'weight_class_0': 0.027783641500088153, 'weight_class_1': 0.6106252730151865, 'weight_class_2': 0.31876438578536664}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:55,978] Trial 1764 finished with value: 0.9497346912821402 and parameters: {'weight_class_0': 0.02648472877989326, 'weight_class_1': 0.6007173800753461, 'weight_class_2': 0.31033044784083846}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:56,025] Trial 1765 finished with value: 0.8675660166450326 and parameters: {'weight_class_0': 0.02699929378186005, 'weight_class_1': 0.0020815284967667757, 'weight_class_2': 0.38288384173734513}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:56,034] Trial 1766 finished with value: 0.8631585972720087 and parameters: {'weight_class_0': 0.0029742531024828673, 'weight_class_1': 0.7810880619834435, 'weight_class_2': 0.42334871926604334}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:56,100] Trial 1768 finished with value: 0.9493801460008232 and parameters: {'weight_class_0': 0.05291955760396772, 'weight_class_1': 0.8037046894205566, 'weight_class_2': 0.4110653219432867}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:56,104] Trial 1767 finished with value: 0.9101287747564548 and parameters: {'weight_class_0': 0.07071373484288752, 'weight_class_1': 0.05655454420147946, 'weight_class_2': 0.4222650746048244}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:25:56,118] Trial 1769 finished with value: 0.9491582287588448 and parameters: {'weight_class_0': 0.05562931415519381, 'weight_class_1': 0.785580607351357, 'weight_class_2': 0.3969700775513477}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:56,136] Trial 1770 finished with value: 0.8527031007436948 and parameters: {'weight_class_0': 0.054081216544929055, 'weight_class_1': 0.053362865672353293, 'weight_class_2': 0.003341723192377921}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:56,207] Trial 1771 finished with value: 0.8594095439636703 and parameters: {'weight_class_0': 0.0028668985837618922, 'weight_class_1': 0.7689597017667924, 'weight_class_2': 0.42500823423231815}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:56,209] Trial 1772 finished with value: 0.949679580474993 and parameters: {'weight_class_0': 0.05384963674893767, 'weight_class_1': 0.805559381537811, 'weight_class_2': 0.5650718316961769}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:56,246] Trial 1773 finished with value: 0.9493182333175337 and parameters: {'weight_class_0': 0.05593298087317564, 'weight_class_1': 0.7756950745509549, 'weight_class_2': 0.4161923124669295}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:56,262] Trial 1774 finished with value: 0.8416601102273437 and parameters: {'weight_class_0': 0.0037766889419422085, 'weight_class_1': 0.43695539363833463, 'weight_class_2': 1.3777607052300096}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:56,323] Trial 1775 finished with value: 0.9475847621295022 and parameters: {'weight_class_0': 0.05735998942301707, 'weight_class_1': 0.43147680252282944, 'weight_class_2': 1.3131477198105634}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  59%|█████████████████████████████████████████████████████████████████████████████▎                                                    | 1783/3000 [00:41<00:34, 35.28it/s]

[I 2026-07-05 15:25:56,324] Trial 1776 finished with value: 0.9496358645102388 and parameters: {'weight_class_0': 0.0541815729269942, 'weight_class_1': 0.7570825209224914, 'weight_class_2': 0.5095688358381356}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:56,346] Trial 1777 finished with value: 0.948091576502314 and parameters: {'weight_class_0': 0.05217673643371861, 'weight_class_1': 0.7755236894250526, 'weight_class_2': 1.3710004243234042}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:56,392] Trial 1778 finished with value: 0.949668402391024 and parameters: {'weight_class_0': 0.055356774230831296, 'weight_class_1': 0.768720486239613, 'weight_class_2': 0.5424894952894411}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:56,402] Trial 1780 finished with value: 0.9489568127837087 and parameters: {'weight_class_0': 0.08803228788894664, 'weight_class_1': 0.7627448315470052, 'weight_class_2': 0.5997956579627168}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:56,433] Trial 1779 finished with value: 0.9496620660700991 and parameters: {'weight_class_0': 0.04937245316219823, 'weight_class_1': 0.7822366892545782, 'weight_class_2': 0.4949780315853229}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:56,481] Trial 1782 finished with value: 0.948794262709756 and parameters: {'weight_class_0': 0.08576073240767827, 'weight_class_1': 0.7372594361290652, 'weight_class_2': 1.2955264846295713}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:56,508] Trial 1781 finished with value: 0.9485949244031552 and parameters: {'weight_class_0': 0.08774100298767906, 'weight_class_1': 0.7362351604668436, 'weight_class_2': 1.4416581880555446}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:56,529] Trial 1784 finished with value: 0.9473043892902662 and parameters: {'weight_class_0': 0.08916803204413165, 'weight_class_1': 0.4277770625705961, 'weight_class_2': 0.5607839935467935}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  60%|█████████████████████████████████████████████████████████████████████████████▌                                                    | 1790/3000 [00:42<00:35, 34.57it/s]

[I 2026-07-05 15:25:56,554] Trial 1783 finished with value: 0.9486797731436317 and parameters: {'weight_class_0': 0.0880213193432757, 'weight_class_1': 0.7533959150778171, 'weight_class_2': 0.5303565966125754}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:56,562] Trial 1785 finished with value: 0.9472927568641558 and parameters: {'weight_class_0': 0.08964219977066037, 'weight_class_1': 0.4349805847469032, 'weight_class_2': 0.5582952604569705}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:56,622] Trial 1786 finished with value: 0.9493501274890607 and parameters: {'weight_class_0': 0.07042836736999783, 'weight_class_1': 0.7428908190618828, 'weight_class_2': 0.5627994334104863}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:56,669] Trial 1788 finished with value: 0.9486841167401971 and parameters: {'weight_class_0': 0.08279895129075711, 'weight_class_1': 1.1276066937484612, 'weight_class_2': 0.4844672291643606}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:56,672] Trial 1787 finished with value: 0.8311378441099792 and parameters: {'weight_class_0': 0.0909763332023549, 'weight_class_1': 1.1712201390279624, 'weight_class_2': 0.002619433171964693}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:56,693] Trial 1789 finished with value: 0.9488386975796187 and parameters: {'weight_class_0': 0.033615833905527685, 'weight_class_1': 1.1806143892504133, 'weight_class_2': 0.580697292496229}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:56,736] Trial 1790 finished with value: 0.949139966489582 and parameters: {'weight_class_0': 0.03430537686770333, 'weight_class_1': 1.0812381093595913, 'weight_class_2': 0.5455709824543314}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  60%|█████████████████████████████████████████████████████████████████████████████▉                                                    | 1798/3000 [00:42<00:34, 35.01it/s]

[I 2026-07-05 15:25:56,765] Trial 1793 finished with value: 0.9468190759352032 and parameters: {'weight_class_0': 0.06982870535635505, 'weight_class_1': 0.519237510611656, 'weight_class_2': 2.122239215699297}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:56,777] Trial 1792 finished with value: 0.8800249645732192 and parameters: {'weight_class_0': 0.03326247044219697, 'weight_class_1': 0.5204745592089366, 'weight_class_2': 0.0025635470359473473}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:56,792] Trial 1791 finished with value: 0.9495733411165325 and parameters: {'weight_class_0': 0.06910503807228369, 'weight_class_1': 1.1184604486896867, 'weight_class_2': 0.5975401771087974}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:56,822] Trial 1794 finished with value: 0.9493123120225038 and parameters: {'weight_class_0': 0.03482249473222092, 'weight_class_1': 0.529535367467323, 'weight_class_2': 0.25962436598374783}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:56,869] Trial 1796 finished with value: 0.9493014807636649 and parameters: {'weight_class_0': 0.03536823984990987, 'weight_class_1': 0.5278569963236701, 'weight_class_2': 0.2616493183980936}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:56,875] Trial 1795 finished with value: 0.948059035696879 and parameters: {'weight_class_0': 0.034292184068944395, 'weight_class_1': 0.5159837201459616, 'weight_class_2': 0.9137628548809793}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:56,908] Trial 1797 finished with value: 0.9487498481900215 and parameters: {'weight_class_0': 0.03515941874786933, 'weight_class_1': 1.1745235510205114, 'weight_class_2': 0.2633063792140461}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:56,960] Trial 1798 finished with value: 0.9494570796465407 and parameters: {'weight_class_0': 0.032791746518277425, 'weight_class_1': 0.5218500446517756, 'weight_class_2': 0.2582589784001529}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  60%|██████████████████████████████████████████████████████████████████████████████▎                                                   | 1806/3000 [00:42<00:33, 35.40it/s]

[I 2026-07-05 15:25:56,986] Trial 1799 finished with value: 0.9490384642424291 and parameters: {'weight_class_0': 0.03969251269519968, 'weight_class_1': 0.5308284281834538, 'weight_class_2': 0.2650264077501863}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:57,010] Trial 1800 finished with value: 0.9489680363054411 and parameters: {'weight_class_0': 0.03835738656135399, 'weight_class_1': 0.5215178148023183, 'weight_class_2': 0.24679709073712622}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:57,037] Trial 1802 finished with value: 0.9484076596083627 and parameters: {'weight_class_0': 0.040782163139464714, 'weight_class_1': 0.5318472479292407, 'weight_class_2': 0.8948505580277866}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:57,051] Trial 1801 finished with value: 0.9489893992942714 and parameters: {'weight_class_0': 0.04067216324719505, 'weight_class_1': 0.5041954581490217, 'weight_class_2': 0.2657236862753286}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:57,111] Trial 1803 finished with value: 0.9481485363453634 and parameters: {'weight_class_0': 0.04107256627870701, 'weight_class_1': 1.6880285522910972, 'weight_class_2': 0.854556766769019}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:57,121] Trial 1804 finished with value: 0.7994931737550989 and parameters: {'weight_class_0': 0.04222425616069974, 'weight_class_1': 0.001679540374061972, 'weight_class_2': 1.0796809607240385}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:57,173] Trial 1805 finished with value: 0.9496189032161458 and parameters: {'weight_class_0': 0.04031765989371141, 'weight_class_1': 0.9189830163410099, 'weight_class_2': 0.4084357358243637}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:57,188] Trial 1807 finished with value: 0.9494940827896691 and parameters: {'weight_class_0': 0.04027570582317964, 'weight_class_1': 0.37596225157547064, 'weight_class_2': 0.40456142145225293}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  60%|██████████████████████████████████████████████████████████████████████████████▌                                                   | 1814/3000 [00:42<00:33, 34.97it/s]

[I 2026-07-05 15:25:57,191] Trial 1806 finished with value: 0.8803904538421606 and parameters: {'weight_class_0': 0.041844941253547895, 'weight_class_1': 0.981815451449142, 'weight_class_2': 0.004673263021566172}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:57,263] Trial 1809 finished with value: 0.9496107715285893 and parameters: {'weight_class_0': 0.04414529952853606, 'weight_class_1': 0.9453131833956074, 'weight_class_2': 0.4038004141486104}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:57,275] Trial 1808 finished with value: 0.9497364184634346 and parameters: {'weight_class_0': 0.0406946234788301, 'weight_class_1': 0.6228125538421367, 'weight_class_2': 0.4324902935607607}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:57,298] Trial 1810 finished with value: 0.9496401104124551 and parameters: {'weight_class_0': 0.04215743196950748, 'weight_class_1': 0.9429911377586591, 'weight_class_2': 0.40408137106550696}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:57,325] Trial 1811 finished with value: 0.948770390291919 and parameters: {'weight_class_0': 0.04599688683000551, 'weight_class_1': 1.7963798625640373, 'weight_class_2': 0.4096286258599147}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:57,362] Trial 1813 finished with value: 0.9496506825817425 and parameters: {'weight_class_0': 0.04638686326930419, 'weight_class_1': 0.9500425249148439, 'weight_class_2': 0.4190556644211044}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:57,379] Trial 1812 finished with value: 0.9485845561770203 and parameters: {'weight_class_0': 0.04771553998061713, 'weight_class_1': 1.920608421038348, 'weight_class_2': 0.4023181335941685}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:57,434] Trial 1814 finished with value: 0.9487956813682917 and parameters: {'weight_class_0': 0.06394336827399237, 'weight_class_1': 0.9580355969091912, 'weight_class_2': 0.388239584241848}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  61%|██████████████████████████████████████████████████████████████████████████████▉                                                   | 1821/3000 [00:43<00:34, 34.61it/s]

[I 2026-07-05 15:25:57,446] Trial 1815 finished with value: 0.8263212719453442 and parameters: {'weight_class_0': 2.0781117061800067, 'weight_class_1': 0.3745802618830796, 'weight_class_2': 0.4062211325319335}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:57,462] Trial 1817 finished with value: 0.8520174447669335 and parameters: {'weight_class_0': 0.0012363014387212642, 'weight_class_1': 0.015962885716851245, 'weight_class_2': 0.43454519591577445}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:57,483] Trial 1816 finished with value: 0.8931301773946188 and parameters: {'weight_class_0': 0.04842032551565357, 'weight_class_1': 0.6422780377585712, 'weight_class_2': 0.011828756032966984}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:57,527] Trial 1818 finished with value: 0.9490275085692362 and parameters: {'weight_class_0': 0.023388395822403995, 'weight_class_1': 0.6340196026655407, 'weight_class_2': 0.43161560220755535}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:57,550] Trial 1819 finished with value: 0.9496175424797076 and parameters: {'weight_class_0': 0.04918822349456002, 'weight_class_1': 0.6643559868016231, 'weight_class_2': 0.454093825228879}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:57,587] Trial 1820 finished with value: 0.8926911585347125 and parameters: {'weight_class_0': 0.11273231455699126, 'weight_class_1': 0.650532711585527, 'weight_class_2': 0.02882867054263295}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:57,631] Trial 1821 finished with value: 0.9041049141664228 and parameters: {'weight_class_0': 0.06449623367023687, 'weight_class_1': 0.6582854413562363, 'weight_class_2': 0.05286326419924262}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  61%|███████████████████████████████████████████████████████████████████████████████▎                                                  | 1829/3000 [00:43<00:33, 34.96it/s]

[I 2026-07-05 15:25:57,643] Trial 1822 finished with value: 0.897567377209394 and parameters: {'weight_class_0': 0.06122083328912887, 'weight_class_1': 0.6487458887175788, 'weight_class_2': 0.03141690471093852}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:57,682] Trial 1823 finished with value: 0.7450260352177455 and parameters: {'weight_class_0': 0.004349367182291328, 'weight_class_1': 2.6740884717035494, 'weight_class_2': 0.6024212608145864}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:57,715] Trial 1824 finished with value: 0.9384300717763837 and parameters: {'weight_class_0': 0.02244762983999274, 'weight_class_1': 0.6628490107961555, 'weight_class_2': 0.051596039524995044}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:57,722] Trial 1825 finished with value: 0.9060378476872355 and parameters: {'weight_class_0': 0.06298722830335153, 'weight_class_1': 0.6456235785778657, 'weight_class_2': 0.05576944012267168}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:57,753] Trial 1826 finished with value: 0.9418298789987399 and parameters: {'weight_class_0': 0.022125979832210405, 'weight_class_1': 0.6540072304775517, 'weight_class_2': 0.05904988048344816}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:57,778] Trial 1827 finished with value: 0.9111808803532305 and parameters: {'weight_class_0': 0.022780495925830983, 'weight_class_1': 0.03114079371921664, 'weight_class_2': 0.04546980144290598}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:57,819] Trial 1829 finished with value: 0.9481880911522064 and parameters: {'weight_class_0': 0.02217765398892189, 'weight_class_1': 0.42811161550155824, 'weight_class_2': 0.6448481185998518}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:57,849] Trial 1828 finished with value: 0.9495669184122789 and parameters: {'weight_class_0': 0.06320744126666514, 'weight_class_1': 0.6411716088556035, 'weight_class_2': 0.6232651457880465}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:25:57,882] Trial 1831 finished with value: 0.948700355263934 and parameters: {'weight_class_0': 0.0644142636412973, 'weight_class_1': 0.411316934523137, 'weight_class_2': 0.5301529119918875}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:57,888] Trial 1830 finished with value: 0.9488348589471437 and parameters: {'weight_class_0': 0.06476563430306731, 'weight_class_1': 0.4247375157649285, 'weight_class_2': 0.5907437976940613}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:57,949] Trial 1832 finished with value: 0.948293289562319 and parameters: {'weight_class_0': 0.022999832874576836, 'weight_class_1': 0.3887382834465058, 'weight_class_2': 0.6090396862094607}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:57,981] Trial 1833 finished with value: 0.9482078734512985 and parameters: {'weight_class_0': 0.022252555696442078, 'weight_class_1': 0.4172417540540976, 'weight_class_2': 0.6348422626384144}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:58,006] Trial 1834 finished with value: 0.94906960766111 and parameters: {'weight_class_0': 0.031422760082123365, 'weight_class_1': 0.44398335933467614, 'weight_class_2': 0.5683137928777977}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:58,029] Trial 1835 finished with value: 0.9491586429246678 and parameters: {'weight_class_0': 0.030390213071103258, 'weight_class_1': 0.4063825261389288, 'weight_class_2': 0.5169312690769892}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:58,039] Trial 1836 finished with value: 0.9486098797115933 and parameters: {'weight_class_0': 0.03112257542365604, 'weight_class_1': 0.36077451009696915, 'weight_class_2': 0.6131059143432497}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  61%|███████████████████████████████████████████████████████████████████████████████▉                                                  | 1844/3000 [00:43<00:32, 35.07it/s]

[I 2026-07-05 15:25:58,101] Trial 1837 finished with value: 0.7015186868313811 and parameters: {'weight_class_0': 0.0010110211064500044, 'weight_class_1': 0.41763144346878595, 'weight_class_2': 0.6357623027505522}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:58,129] Trial 1838 finished with value: 0.9492121135819503 and parameters: {'weight_class_0': 0.027284566765795545, 'weight_class_1': 0.4403633510622192, 'weight_class_2': 0.4943523802468212}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:58,179] Trial 1839 finished with value: 0.9493532064354294 and parameters: {'weight_class_0': 0.030644036497390476, 'weight_class_1': 0.4382967015930461, 'weight_class_2': 0.4992756041166152}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:58,185] Trial 1841 finished with value: 0.9494889191020758 and parameters: {'weight_class_0': 0.03244056708894371, 'weight_class_1': 0.8416327865825799, 'weight_class_2': 0.31861081996146207}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:58,204] Trial 1840 finished with value: 0.9244142514052416 and parameters: {'weight_class_0': 0.03114324074021152, 'weight_class_1': 0.0415771029978081, 'weight_class_2': 0.8369766880824485}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:58,231] Trial 1843 finished with value: 0.9494847748931688 and parameters: {'weight_class_0': 0.030600418305873085, 'weight_class_1': 0.8340600758327054, 'weight_class_2': 0.3340646915889371}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:58,240] Trial 1844 finished with value: 0.9483277204061403 and parameters: {'weight_class_0': 0.030266285357567178, 'weight_class_1': 0.8741178011589654, 'weight_class_2': 0.848464687914986}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:58,243] Trial 1842 finished with value: 0.9263240475103771 and parameters: {'weight_class_0': 0.028942038643664153, 'weight_class_1': 0.04171936846137395, 'weight_class_2': 0.8352205636843929}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:25:58,320] Trial 1846 finished with value: 0.9482701826097486 and parameters: {'weight_class_0': 0.029406169107635747, 'weight_class_1': 0.8429777806708072, 'weight_class_2': 0.8380370246466471}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:58,345] Trial 1845 finished with value: 0.9482421420442327 and parameters: {'weight_class_0': 0.02959211641862382, 'weight_class_1': 0.8598193922412584, 'weight_class_2': 0.8512501277746386}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:58,364] Trial 1847 finished with value: 0.6112799864171495 and parameters: {'weight_class_0': 2.7533696035350266, 'weight_class_1': 0.011358878311542135, 'weight_class_2': 0.3187626339412771}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:58,394] Trial 1848 finished with value: 0.9483705196114928 and parameters: {'weight_class_0': 0.03037885187942585, 'weight_class_1': 0.8501246979307554, 'weight_class_2': 0.8240889733724682}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:58,426] Trial 1850 finished with value: 0.9492888634347727 and parameters: {'weight_class_0': 0.05366483648842428, 'weight_class_1': 0.8523517276648933, 'weight_class_2': 0.9323853396572294}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:58,440] Trial 1849 finished with value: 0.9490426815352051 and parameters: {'weight_class_0': 0.05219162065676206, 'weight_class_1': 0.8571564711807135, 'weight_class_2': 0.3489729766845498}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:58,470] Trial 1851 finished with value: 0.9277659145595424 and parameters: {'weight_class_0': 0.04625082106892996, 'weight_class_1': 0.06893839291683942, 'weight_class_2': 1.0620271034187059}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  62%|████████████████████████████████████████████████████████████████████████████████▌                                                 | 1858/3000 [00:44<00:34, 33.28it/s]

[I 2026-07-05 15:25:58,522] Trial 1852 finished with value: 0.9488041037822863 and parameters: {'weight_class_0': 0.05030246797109777, 'weight_class_1': 1.273528432985892, 'weight_class_2': 0.33844236192790683}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:58,584] Trial 1854 finished with value: 0.7392182886428773 and parameters: {'weight_class_0': 0.001492489193184814, 'weight_class_1': 0.0793588674817526, 'weight_class_2': 1.0700303056338485}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:58,594] Trial 1853 finished with value: 0.948820146070879 and parameters: {'weight_class_0': 0.050508871460742, 'weight_class_1': 0.554908218080285, 'weight_class_2': 0.3073232904185013}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:58,597] Trial 1855 finished with value: 0.9490221997862237 and parameters: {'weight_class_0': 0.05576023584686513, 'weight_class_1': 1.2371385724525576, 'weight_class_2': 1.113085173784893}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:58,605] Trial 1856 finished with value: 0.9488387349702568 and parameters: {'weight_class_0': 0.05057120814390005, 'weight_class_1': 1.2317822117133705, 'weight_class_2': 0.3402738897856293}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:58,657] Trial 1858 finished with value: 0.9491682542602703 and parameters: {'weight_class_0': 0.048642703284264836, 'weight_class_1': 1.0909716723799663, 'weight_class_2': 0.3576035307472317}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:58,665] Trial 1857 finished with value: 0.9491584142172318 and parameters: {'weight_class_0': 0.050226155938682265, 'weight_class_1': 0.5578711464324988, 'weight_class_2': 0.36611611679224426}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  62%|████████████████████████████████████████████████████████████████████████████████▊                                                 | 1866/3000 [00:44<00:33, 33.86it/s]

[I 2026-07-05 15:25:58,713] Trial 1859 finished with value: 0.9489146918414373 and parameters: {'weight_class_0': 0.05145485776035035, 'weight_class_1': 1.192849532494177, 'weight_class_2': 0.36052915798063473}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:58,733] Trial 1860 finished with value: 0.948867114956621 and parameters: {'weight_class_0': 0.05300546023325331, 'weight_class_1': 1.235352191873408, 'weight_class_2': 0.3565750480828153}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:58,813] Trial 1862 finished with value: 0.7020391990024025 and parameters: {'weight_class_0': 0.0015253584106121093, 'weight_class_1': 1.1271673015075931, 'weight_class_2': 0.4771541806015996}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:58,818] Trial 1861 finished with value: 0.9491212551236686 and parameters: {'weight_class_0': 0.12183199725530884, 'weight_class_1': 1.2152858473475179, 'weight_class_2': 1.798084091648792}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:58,822] Trial 1863 finished with value: 0.9496252801978531 and parameters: {'weight_class_0': 0.03793194376441839, 'weight_class_1': 0.5309648327128104, 'weight_class_2': 0.4857386618191698}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:58,840] Trial 1864 finished with value: 0.9467893508660742 and parameters: {'weight_class_0': 0.038635013826452944, 'weight_class_1': 0.5919105893657107, 'weight_class_2': 1.796846842414296}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:58,887] Trial 1865 finished with value: 0.9496265015207426 and parameters: {'weight_class_0': 0.036972928133562316, 'weight_class_1': 0.5511677732246255, 'weight_class_2': 0.4824962272833857}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:58,915] Trial 1866 finished with value: 0.9495366579529962 and parameters: {'weight_class_0': 0.03620939644979146, 'weight_class_1': 0.5640693368625465, 'weight_class_2': 0.5048879913645153}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:25:58,921] Trial 1867 finished with value: 0.9452083138090944 and parameters: {'weight_class_0': 0.12939703469133404, 'weight_class_1': 0.6866415547100505, 'weight_class_2': 0.4885029941171947}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:58,967] Trial 1868 finished with value: 0.8672004053312022 and parameters: {'weight_class_0': 0.005750072688741874, 'weight_class_1': 1.5481146683209122, 'weight_class_2': 0.47354632055924556}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:59,018] Trial 1869 finished with value: 0.9496265075679222 and parameters: {'weight_class_0': 0.038169901563496395, 'weight_class_1': 0.7032994996518803, 'weight_class_2': 0.5210421624574474}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:59,049] Trial 1871 finished with value: 0.9487188248468951 and parameters: {'weight_class_0': 0.037694675281031466, 'weight_class_1': 1.5593203253487384, 'weight_class_2': 0.44716059012773507}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:59,057] Trial 1870 finished with value: 0.9489276294583114 and parameters: {'weight_class_0': 0.0729409555924918, 'weight_class_1': 0.7042269230312519, 'weight_class_2': 0.473951500637913}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:59,106] Trial 1872 finished with value: 0.9496405433645903 and parameters: {'weight_class_0': 0.03712085145092059, 'weight_class_1': 0.7148019685243835, 'weight_class_2': 0.47762792509009455}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:59,131] Trial 1873 finished with value: 0.9488993398237858 and parameters: {'weight_class_0': 0.07489508058713475, 'weight_class_1': 0.7684944717526682, 'weight_class_2': 0.48433643121270914}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:59,167] Trial 1874 finished with value: 0.9497268711796262 and parameters: {'weight_class_0': 0.03760461913363974, 'weight_class_1': 0.7171822416159416, 'weight_class_2': 0.4555411956346703}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  63%|█████████████████████████████████████████████████████████████████████████████████▌                                                | 1881/3000 [00:44<00:32, 34.90it/s]

[I 2026-07-05 15:25:59,169] Trial 1875 finished with value: 0.9466979835968722 and parameters: {'weight_class_0': 0.07233718924452345, 'weight_class_1': 0.7227791317389872, 'weight_class_2': 0.2854205173507973}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:59,223] Trial 1876 finished with value: 0.949636126187591 and parameters: {'weight_class_0': 0.07449032193276152, 'weight_class_1': 1.533182913446905, 'weight_class_2': 0.6802373666682114}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:59,265] Trial 1878 finished with value: 0.9459446473206419 and parameters: {'weight_class_0': 0.07429420243656353, 'weight_class_1': 0.6962832585351981, 'weight_class_2': 0.26648523166443266}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:59,276] Trial 1877 finished with value: 0.9461456984241923 and parameters: {'weight_class_0': 0.0761567719795357, 'weight_class_1': 0.696627952656454, 'weight_class_2': 0.279951967274081}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:59,296] Trial 1879 finished with value: 0.9470182395087017 and parameters: {'weight_class_0': 0.06770719053254899, 'weight_class_1': 0.7288411274098644, 'weight_class_2': 0.2792599897227031}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:59,355] Trial 1880 finished with value: 0.9490596510815511 and parameters: {'weight_class_0': 0.042050884352928176, 'weight_class_1': 0.68325704058074, 'weight_class_2': 0.2835900640449289}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:59,388] Trial 1881 finished with value: 0.9468941239885776 and parameters: {'weight_class_0': 0.07091650562720908, 'weight_class_1': 0.9968661114811863, 'weight_class_2': 0.2846102517777334}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  63%|█████████████████████████████████████████████████████████████████████████████████▊                                                | 1889/3000 [00:45<00:32, 34.10it/s]

[I 2026-07-05 15:25:59,395] Trial 1882 finished with value: 0.9228144941485662 and parameters: {'weight_class_0': 0.17964056021027897, 'weight_class_1': 0.7478999089454006, 'weight_class_2': 0.27080973641272227}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:59,438] Trial 1883 finished with value: 0.9467744954214793 and parameters: {'weight_class_0': 0.07334833738652528, 'weight_class_1': 0.9585205057771908, 'weight_class_2': 0.2914649169723142}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:59,438] Trial 1884 finished with value: 0.9488845797911397 and parameters: {'weight_class_0': 0.026152982952336888, 'weight_class_1': 1.000011388258158, 'weight_class_2': 0.28927302018793155}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:59,478] Trial 1885 finished with value: 0.9494444479868953 and parameters: {'weight_class_0': 0.046016487729550776, 'weight_class_1': 0.9850038738704935, 'weight_class_2': 0.7047679196942603}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:59,502] Trial 1886 finished with value: 0.9480906751292212 and parameters: {'weight_class_0': 0.02691543705409424, 'weight_class_1': 0.9858733158100813, 'weight_class_2': 0.6966030818254522}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:59,524] Trial 1887 finished with value: 0.9498032757005289 and parameters: {'weight_class_0': 0.025159251883628733, 'weight_class_1': 0.46824879614072085, 'weight_class_2': 0.2889008393531104}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:59,534] Trial 1888 finished with value: 0.9487560509930413 and parameters: {'weight_class_0': 0.025660142249915485, 'weight_class_1': 1.0137616980881101, 'weight_class_2': 0.2281569066098034}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:59,587] Trial 1889 finished with value: 0.9494659490683454 and parameters: {'weight_class_0': 0.043891002495944256, 'weight_class_1': 0.9770535448086338, 'weight_class_2': 0.6793953931462458}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  63%|██████████████████████████████████████████████████████████████████████████████████▏                                               | 1896/3000 [00:45<00:32, 34.50it/s]

[I 2026-07-05 15:25:59,608] Trial 1890 finished with value: 0.9481463276106155 and parameters: {'weight_class_0': 0.025787487939245058, 'weight_class_1': 0.9736519205094667, 'weight_class_2': 0.6043381969999115}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:59,644] Trial 1891 finished with value: 0.8149478322007928 and parameters: {'weight_class_0': 0.02620724058423812, 'weight_class_1': 0.0013210075938456974, 'weight_class_2': 0.7006238808207488}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:59,686] Trial 1892 finished with value: 0.9485906676189896 and parameters: {'weight_class_0': 0.026818484092653992, 'weight_class_1': 0.49206661188859646, 'weight_class_2': 0.6394438773839178}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:59,723] Trial 1893 finished with value: 0.8499555826916261 and parameters: {'weight_class_0': 1.0029220872985865, 'weight_class_1': 0.47094035844269133, 'weight_class_2': 0.6579655652744061}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:59,757] Trial 1894 finished with value: 0.9264529813214838 and parameters: {'weight_class_0': 0.026676152398609543, 'weight_class_1': 3.868850326356758, 'weight_class_2': 0.7092742268528024}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:59,760] Trial 1895 finished with value: 0.948640929019906 and parameters: {'weight_class_0': 0.02693429320960495, 'weight_class_1': 0.4728836750330428, 'weight_class_2': 0.6241780277925374}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:59,827] Trial 1896 finished with value: 0.9497207271533293 and parameters: {'weight_class_0': 0.034069706090027456, 'weight_class_1': 0.4786822673080203, 'weight_class_2': 0.37757478910727305}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  63%|██████████████████████████████████████████████████████████████████████████████████▌                                               | 1904/3000 [00:45<00:31, 34.95it/s]

[I 2026-07-05 15:25:59,831] Trial 1897 finished with value: 0.9497083002239073 and parameters: {'weight_class_0': 0.02620608485133841, 'weight_class_1': 0.4426034281951586, 'weight_class_2': 0.2658014894851268}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:59,856] Trial 1899 finished with value: 0.9490506538149388 and parameters: {'weight_class_0': 0.0173209445876491, 'weight_class_1': 0.45702775023903064, 'weight_class_2': 0.32759612137712435}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:59,879] Trial 1898 finished with value: 0.9496857662359166 and parameters: {'weight_class_0': 0.023066558513008185, 'weight_class_1': 0.3602640873007812, 'weight_class_2': 0.2258885263240121}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:59,924] Trial 1900 finished with value: 0.9496228293790109 and parameters: {'weight_class_0': 0.02383046263152911, 'weight_class_1': 0.35234658891360654, 'weight_class_2': 0.21699332538468427}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:59,943] Trial 1901 finished with value: 0.9496919323056381 and parameters: {'weight_class_0': 0.02010476243411275, 'weight_class_1': 0.31674560973674776, 'weight_class_2': 0.25645066940249495}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:25:59,981] Trial 1902 finished with value: 0.9497738691298818 and parameters: {'weight_class_0': 0.020308996944907377, 'weight_class_1': 0.3413552182475662, 'weight_class_2': 0.2208023591310493}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:00,011] Trial 1903 finished with value: 0.9494932885382941 and parameters: {'weight_class_0': 0.01704583636527559, 'weight_class_1': 0.3543377698158052, 'weight_class_2': 0.24427102735024817}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:00,026] Trial 1904 finished with value: 0.949732683875621 and parameters: {'weight_class_0': 0.019143099920642136, 'weight_class_1': 0.34620758532926665, 'weight_class_2': 0.2346353577026507}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  64%|██████████████████████████████████████████████████████████████████████████████████▊                                               | 1912/3000 [00:45<00:33, 32.68it/s]

[I 2026-07-05 15:26:00,080] Trial 1905 finished with value: 0.9497231131941469 and parameters: {'weight_class_0': 0.019116304616932252, 'weight_class_1': 0.3207495631559552, 'weight_class_2': 0.2023778074643839}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:00,090] Trial 1906 finished with value: 0.9496553861368042 and parameters: {'weight_class_0': 0.019370485831370025, 'weight_class_1': 0.3814774732144657, 'weight_class_2': 0.25130811814312803}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:00,135] Trial 1907 finished with value: 0.8549436555355102 and parameters: {'weight_class_0': 0.01984456980984233, 'weight_class_1': 0.34618335004641704, 'weight_class_2': 0.0010132023658917836}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:00,159] Trial 1908 finished with value: 0.9496079084346954 and parameters: {'weight_class_0': 0.024792034083174007, 'weight_class_1': 0.3346616298030674, 'weight_class_2': 0.32520372898318295}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:00,221] Trial 1909 finished with value: 0.9496562732173081 and parameters: {'weight_class_0': 0.03208043590096737, 'weight_class_1': 0.5260569647696359, 'weight_class_2': 0.3235493715626284}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:00,243] Trial 1910 finished with value: 0.8936853555179797 and parameters: {'weight_class_0': 0.01933789844977774, 'weight_class_1': 0.3851452077772003, 'weight_class_2': 4.992870425685782}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:00,247] Trial 1911 finished with value: 0.9496033396571623 and parameters: {'weight_class_0': 0.017508761868930422, 'weight_class_1': 0.3309463711343821, 'weight_class_2': 0.2412635413786425}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:00,255] Trial 1912 finished with value: 0.9493364145701663 and parameters: {'weight_class_0': 0.02112602112153684, 'weight_class_1': 0.5113310024313585, 'weight_class_2': 0.32172294843239224}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  64%|███████████████████████████████████████████████████████████████████████████████████▏                                              | 1920/3000 [00:45<00:31, 34.68it/s]

[I 2026-07-05 15:26:00,318] Trial 1913 finished with value: 0.9491699508461421 and parameters: {'weight_class_0': 0.018033725121469498, 'weight_class_1': 0.3775217626696418, 'weight_class_2': 0.3342278619965912}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:00,328] Trial 1914 finished with value: 0.9496577262128433 and parameters: {'weight_class_0': 0.031884634678178994, 'weight_class_1': 0.36528842405058287, 'weight_class_2': 0.31587734338393364}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:00,355] Trial 1915 finished with value: 0.9491950969087418 and parameters: {'weight_class_0': 0.01920682200513822, 'weight_class_1': 0.5220024739942836, 'weight_class_2': 0.3122040006801747}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:00,399] Trial 1916 finished with value: 0.9493258741072502 and parameters: {'weight_class_0': 0.022218857598859786, 'weight_class_1': 0.5524649692874076, 'weight_class_2': 0.33709757976808963}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:00,442] Trial 1918 finished with value: 0.949470091372855 and parameters: {'weight_class_0': 0.022395654895835056, 'weight_class_1': 0.5252948358554382, 'weight_class_2': 0.30987058638057435}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:00,444] Trial 1917 finished with value: 0.9493697317060539 and parameters: {'weight_class_0': 0.021400808495915847, 'weight_class_1': 0.5284067631600645, 'weight_class_2': 0.3088237287033658}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:00,465] Trial 1919 finished with value: 0.9492898031724737 and parameters: {'weight_class_0': 0.02167388406738537, 'weight_class_1': 0.527822589458503, 'weight_class_2': 0.3600883633827763}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:00,508] Trial 1920 finished with value: 0.9498272421623001 and parameters: {'weight_class_0': 0.0340074092685913, 'weight_class_1': 0.5457097719705201, 'weight_class_2': 0.39030884195687526}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  64%|███████████████████████████████████████████████████████████████████████████████████▌                                              | 1927/3000 [00:46<00:32, 33.49it/s]

[I 2026-07-05 15:26:00,544] Trial 1921 finished with value: 0.9498021403116175 and parameters: {'weight_class_0': 0.031557167832449606, 'weight_class_1': 0.563683392157642, 'weight_class_2': 0.3560626606836591}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:00,579] Trial 1922 finished with value: 0.9492479345968845 and parameters: {'weight_class_0': 0.022924240463646342, 'weight_class_1': 0.568667047029063, 'weight_class_2': 0.38511880243116375}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:00,596] Trial 1923 finished with value: 0.949321428300531 and parameters: {'weight_class_0': 0.02279655921167993, 'weight_class_1': 0.5628753842413186, 'weight_class_2': 0.36430571286538616}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:00,648] Trial 1924 finished with value: 0.9492458910376738 and parameters: {'weight_class_0': 0.022712604701577006, 'weight_class_1': 0.5690564459697982, 'weight_class_2': 0.38609708361408673}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:00,671] Trial 1925 finished with value: 0.9450248835377115 and parameters: {'weight_class_0': 0.10578424658686936, 'weight_class_1': 0.5677160983341649, 'weight_class_2': 0.3859841012077106}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:00,684] Trial 1926 finished with value: 0.9171139700356964 and parameters: {'weight_class_0': 0.0035851855476506066, 'weight_class_1': 0.5638432577665814, 'weight_class_2': 0.3837787820455767}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:00,725] Trial 1927 finished with value: 0.9496750823658099 and parameters: {'weight_class_0': 0.030081586004677228, 'weight_class_1': 0.45921218244328604, 'weight_class_2': 0.38584217212887245}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  64%|███████████████████████████████████████████████████████████████████████████████████▊                                              | 1934/3000 [00:46<00:32, 33.14it/s]

[I 2026-07-05 15:26:00,771] Trial 1928 finished with value: 0.9431753917056839 and parameters: {'weight_class_0': 0.10784672574402561, 'weight_class_1': 0.44711341245724084, 'weight_class_2': 0.3771125442586201}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:00,800] Trial 1930 finished with value: 0.9444625670712249 and parameters: {'weight_class_0': 0.10229870814392983, 'weight_class_1': 0.4494513722274792, 'weight_class_2': 0.39243091242867956}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:00,815] Trial 1929 finished with value: 0.949655973778691 and parameters: {'weight_class_0': 0.032170840844874135, 'weight_class_1': 0.4264309214413587, 'weight_class_2': 0.39958306618388895}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:00,830] Trial 1931 finished with value: 0.949072755891327 and parameters: {'weight_class_0': 0.01396758974584374, 'weight_class_1': 0.43837634867294345, 'weight_class_2': 0.11684670613114369}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:00,879] Trial 1932 finished with value: 0.9486963490724393 and parameters: {'weight_class_0': 0.011861351107540294, 'weight_class_1': 0.4773806315790626, 'weight_class_2': 0.11992688480865248}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:00,901] Trial 1933 finished with value: 0.9480406302546065 and parameters: {'weight_class_0': 0.03493008483125001, 'weight_class_1': 0.4790457730956882, 'weight_class_2': 0.17301510983888235}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:00,942] Trial 1934 finished with value: 0.9485536066933271 and parameters: {'weight_class_0': 0.032044593381405084, 'weight_class_1': 0.4339985326913211, 'weight_class_2': 0.18094816108552855}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  65%|████████████████████████████████████████████████████████████████████████████████████▏                                             | 1942/3000 [00:46<00:31, 33.12it/s]

[I 2026-07-05 15:26:00,966] Trial 1935 finished with value: 0.947001803949529 and parameters: {'weight_class_0': 0.03243239882787767, 'weight_class_1': 0.46656764922996685, 'weight_class_2': 0.1326581727370425}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:00,998] Trial 1936 finished with value: 0.949188375034761 and parameters: {'weight_class_0': 0.01300277507950379, 'weight_class_1': 0.4500510310541986, 'weight_class_2': 0.15215364242345822}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:01,000] Trial 1937 finished with value: 0.9487569456631402 and parameters: {'weight_class_0': 0.011594965339464662, 'weight_class_1': 0.46229788188324217, 'weight_class_2': 0.12318363090777289}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:01,032] Trial 1938 finished with value: 0.9487670545102773 and parameters: {'weight_class_0': 0.01388917156492515, 'weight_class_1': 0.41895557157562824, 'weight_class_2': 0.09880186204238889}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:01,059] Trial 1939 finished with value: 0.948993684328352 and parameters: {'weight_class_0': 0.013854260275883247, 'weight_class_1': 0.4672527566638348, 'weight_class_2': 0.2254989175639074}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:01,101] Trial 1940 finished with value: 0.9487145387158287 and parameters: {'weight_class_0': 0.011285259112161675, 'weight_class_1': 0.4596753658902089, 'weight_class_2': 0.12288584354882186}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:01,125] Trial 1941 finished with value: 0.947714816865768 and parameters: {'weight_class_0': 0.033876985036702806, 'weight_class_1': 0.6085753339118557, 'weight_class_2': 0.15730955711018763}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:01,138] Trial 1942 finished with value: 0.9481983380061195 and parameters: {'weight_class_0': 0.03451830491248207, 'weight_class_1': 0.627606014517799, 'weight_class_2': 0.1757642054471022}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  65%|████████████████████████████████████████████████████████████████████████████████████▌                                             | 1950/3000 [00:46<00:31, 33.26it/s]

[I 2026-07-05 15:26:01,190] Trial 1943 finished with value: 0.9472046875641958 and parameters: {'weight_class_0': 0.03271217815779508, 'weight_class_1': 0.6275950130270498, 'weight_class_2': 0.13826947950318252}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:01,244] Trial 1944 finished with value: 0.9478949110678648 and parameters: {'weight_class_0': 0.0345413887438138, 'weight_class_1': 0.6238452781304381, 'weight_class_2': 0.16625548035889953}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:01,261] Trial 1945 finished with value: 0.9489468728765506 and parameters: {'weight_class_0': 0.035436784905077, 'weight_class_1': 0.6503148028681732, 'weight_class_2': 0.23119110955642094}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:01,283] Trial 1946 finished with value: 0.9494969781579751 and parameters: {'weight_class_0': 0.0350677889666643, 'weight_class_1': 0.6207600740708399, 'weight_class_2': 0.28730573709955826}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:01,311] Trial 1947 finished with value: 0.949309606573462 and parameters: {'weight_class_0': 0.02830405395579076, 'weight_class_1': 0.6120253480375889, 'weight_class_2': 0.2244057678323555}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:01,330] Trial 1948 finished with value: 0.949377659962639 and parameters: {'weight_class_0': 0.03664650735219844, 'weight_class_1': 0.6156017083274474, 'weight_class_2': 0.28005040776794304}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:01,391] Trial 1949 finished with value: 0.9450487327221069 and parameters: {'weight_class_0': 0.00851937655875281, 'weight_class_1': 0.6164832564908478, 'weight_class_2': 0.246384430766457}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:01,412] Trial 1950 finished with value: 0.9488811510283676 and parameters: {'weight_class_0': 0.03748110984744224, 'weight_class_1': 0.5822004597983411, 'weight_class_2': 0.2315784025939057}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  65%|████████████████████████████████████████████████████████████████████████████████████▊                                             | 1958/3000 [00:47<00:29, 34.76it/s]

[I 2026-07-05 15:26:01,433] Trial 1951 finished with value: 0.9442755353704692 and parameters: {'weight_class_0': 0.008622795459758591, 'weight_class_1': 0.6760157522113601, 'weight_class_2': 0.23760918700294226}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:01,450] Trial 1952 finished with value: 0.9495332326390278 and parameters: {'weight_class_0': 0.026491806957483485, 'weight_class_1': 0.6164894837746173, 'weight_class_2': 0.24479483392173423}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:01,502] Trial 1953 finished with value: 0.9495749503129142 and parameters: {'weight_class_0': 0.02725831197833711, 'weight_class_1': 0.6228726069398678, 'weight_class_2': 0.24427751617097557}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:01,517] Trial 1955 finished with value: 0.9492850842412737 and parameters: {'weight_class_0': 0.02670565874396998, 'weight_class_1': 0.649985533686903, 'weight_class_2': 0.4366241653041075}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:01,518] Trial 1954 finished with value: 0.9491655702175933 and parameters: {'weight_class_0': 0.02691436434409558, 'weight_class_1': 0.8025798444902229, 'weight_class_2': 0.43499248036354954}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:01,566] Trial 1956 finished with value: 0.9492171181147174 and parameters: {'weight_class_0': 0.027794035310045134, 'weight_class_1': 0.7858301109533291, 'weight_class_2': 0.4476825903386418}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:01,635] Trial 1957 finished with value: 0.9467023366327783 and parameters: {'weight_class_0': 0.00859487394925871, 'weight_class_1': 0.16739245134412825, 'weight_class_2': 0.4458905145063626}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  66%|█████████████████████████████████████████████████████████████████████████████████████▏                                            | 1965/3000 [00:47<00:31, 32.55it/s]

[I 2026-07-05 15:26:01,686] Trial 1959 finished with value: 0.9463319589424403 and parameters: {'weight_class_0': 0.041918143029359825, 'weight_class_1': 0.1636489034847693, 'weight_class_2': 0.43280599770012196}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:01,688] Trial 1958 finished with value: 0.9412583363597924 and parameters: {'weight_class_0': 0.008642885310966332, 'weight_class_1': 0.7944305522549006, 'weight_class_2': 0.43719508736787355}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:01,701] Trial 1960 finished with value: 0.9483068735075726 and parameters: {'weight_class_0': 0.027079991366303638, 'weight_class_1': 0.1831831456799643, 'weight_class_2': 0.43253452142368193}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:01,759] Trial 1962 finished with value: 0.9464933926106137 and parameters: {'weight_class_0': 0.04136098922551443, 'weight_class_1': 0.16332554991897502, 'weight_class_2': 0.43991037921623805}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:01,764] Trial 1961 finished with value: 0.9497417287806833 and parameters: {'weight_class_0': 0.04461572345906647, 'weight_class_1': 0.7850484675233698, 'weight_class_2': 0.4157996840790971}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:01,798] Trial 1963 finished with value: 0.9497046682622866 and parameters: {'weight_class_0': 0.042975987702859236, 'weight_class_1': 0.7731472723149329, 'weight_class_2': 0.4255437138776013}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:01,838] Trial 1964 finished with value: 0.9497277286970606 and parameters: {'weight_class_0': 0.04285979100079154, 'weight_class_1': 0.8007909904416142, 'weight_class_2': 0.41228860044625004}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:01,868] Trial 1965 finished with value: 0.9493188950050987 and parameters: {'weight_class_0': 0.042965299547284036, 'weight_class_1': 0.37101628015028865, 'weight_class_2': 0.5177339800945208}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:01,893] Trial 1966 finished with value: 0.9497224020085531 and parameters: {'weight_class_0': 0.043702215417165166, 'weight_class_1': 0.8180296168585133, 'weight_class_2': 0.42148899680116286}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:01,920] Trial 1968 finished with value: 0.9492223637373286 and parameters: {'weight_class_0': 0.04504369123721061, 'weight_class_1': 0.36860461564801694, 'weight_class_2': 0.5454153056717375}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:01,944] Trial 1967 finished with value: 0.9492048572096743 and parameters: {'weight_class_0': 0.04215470600793682, 'weight_class_1': 0.3648169210283692, 'weight_class_2': 0.5516996284754235}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:01,977] Trial 1969 finished with value: 0.949719644914853 and parameters: {'weight_class_0': 0.04235222716350277, 'weight_class_1': 0.8257834774631627, 'weight_class_2': 0.409730213546506}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:02,025] Trial 1970 finished with value: 0.9491493822033039 and parameters: {'weight_class_0': 0.041535956473470706, 'weight_class_1': 0.365397565328784, 'weight_class_2': 0.3050647513025258}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:02,045] Trial 1971 finished with value: 0.9496691525767605 and parameters: {'weight_class_0': 0.04358756545791822, 'weight_class_1': 0.8166831391100496, 'weight_class_2': 0.5553199590568592}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:02,056] Trial 1972 finished with value: 0.949354594607062 and parameters: {'weight_class_0': 0.04277518692169763, 'weight_class_1': 0.40460373092866403, 'weight_class_2': 0.5449429190923741}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:02,123] Trial 1974 finished with value: 0.9485405596307825 and parameters: {'weight_class_0': 0.05510533180969489, 'weight_class_1': 0.3289780193815844, 'weight_class_2': 0.5472596511243333}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  66%|█████████████████████████████████████████████████████████████████████████████████████▊                                            | 1980/3000 [00:47<00:31, 32.61it/s]

[I 2026-07-05 15:26:02,134] Trial 1973 finished with value: 0.9486193419325364 and parameters: {'weight_class_0': 0.058809116279404404, 'weight_class_1': 0.35966644003343595, 'weight_class_2': 0.5580028352871319}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:02,150] Trial 1975 finished with value: 0.9488131225232231 and parameters: {'weight_class_0': 0.05799915449007038, 'weight_class_1': 0.37715991357136774, 'weight_class_2': 0.5301751895501734}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:02,204] Trial 1976 finished with value: 0.9484452866263188 and parameters: {'weight_class_0': 0.055248171444920856, 'weight_class_1': 0.48763016595018965, 'weight_class_2': 0.3099256607081047}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:02,249] Trial 1977 finished with value: 0.9481632326356652 and parameters: {'weight_class_0': 0.059280851071489414, 'weight_class_1': 0.5198706207050261, 'weight_class_2': 0.3007649622521101}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:02,278] Trial 1979 finished with value: 0.9484643772746311 and parameters: {'weight_class_0': 0.055852442560958525, 'weight_class_1': 0.5266183416126026, 'weight_class_2': 0.3064334560379644}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:02,279] Trial 1978 finished with value: 0.9483560373977307 and parameters: {'weight_class_0': 0.056749471674002114, 'weight_class_1': 0.4973706404396314, 'weight_class_2': 0.3071816434659841}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:02,290] Trial 1980 finished with value: 0.9484369765429553 and parameters: {'weight_class_0': 0.05592068700424516, 'weight_class_1': 0.5087351259779447, 'weight_class_2': 0.3037203234136205}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  66%|██████████████████████████████████████████████████████████████████████████████████████                                            | 1987/3000 [00:47<00:30, 33.08it/s]

[I 2026-07-05 15:26:02,360] Trial 1983 finished with value: 0.9484013548539084 and parameters: {'weight_class_0': 0.05719702497680146, 'weight_class_1': 0.509887502216854, 'weight_class_2': 0.31127659331217433}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:02,365] Trial 1982 finished with value: 0.9483962772344107 and parameters: {'weight_class_0': 0.05813316033326951, 'weight_class_1': 0.5007224714036204, 'weight_class_2': 0.3198526013727976}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:02,391] Trial 1981 finished with value: 0.8192979066847329 and parameters: {'weight_class_0': 3.6473150706615245, 'weight_class_1': 0.5153008606548096, 'weight_class_2': 0.31068870383266767}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:02,437] Trial 1984 finished with value: 0.9486610300733381 and parameters: {'weight_class_0': 0.05962605907285626, 'weight_class_1': 0.5174611982116809, 'weight_class_2': 0.35525341974495606}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:02,490] Trial 1986 finished with value: 0.9497049195030579 and parameters: {'weight_class_0': 0.03162342334685111, 'weight_class_1': 0.5132658335910452, 'weight_class_2': 0.3333410384058238}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:02,491] Trial 1985 finished with value: 0.9496937573917273 and parameters: {'weight_class_0': 0.031672969067971984, 'weight_class_1': 0.5179812202071978, 'weight_class_2': 0.29989065491570827}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:02,499] Trial 1987 finished with value: 0.9497241858898917 and parameters: {'weight_class_0': 0.03217683879987143, 'weight_class_1': 0.5248229496716491, 'weight_class_2': 0.3508952589171558}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:02,543] Trial 1988 finished with value: 0.9497613895562943 and parameters: {'weight_class_0': 0.029553878873052896, 'weight_class_1': 0.5191377197930206, 'weight_class_2': 0.35149468171583187}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:02,601] Trial 1989 finished with value: 0.8186842089475085 and parameters: {'weight_class_0': 7.65185969028005, 'weight_class_1': 1.3331632063567702, 'weight_class_2': 0.3745132292631537}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:02,626] Trial 1990 finished with value: 0.9486876397586852 and parameters: {'weight_class_0': 0.03324611281296288, 'weight_class_1': 1.3694397088457408, 'weight_class_2': 0.3601478592486872}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:02,627] Trial 1991 finished with value: 0.9485871669721915 and parameters: {'weight_class_0': 0.030609986523498185, 'weight_class_1': 1.3428777743414848, 'weight_class_2': 0.3507896573602883}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:02,647] Trial 1992 finished with value: 0.9486974109252692 and parameters: {'weight_class_0': 0.03190478618605881, 'weight_class_1': 1.321735472561571, 'weight_class_2': 0.35407705542027246}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:02,697] Trial 1993 finished with value: 0.9480748841427052 and parameters: {'weight_class_0': 0.031487993013755294, 'weight_class_1': 1.6125278148423157, 'weight_class_2': 0.3829993886595613}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:02,717] Trial 1994 finished with value: 0.9489240278720238 and parameters: {'weight_class_0': 0.03221091422050538, 'weight_class_1': 1.2332658568601143, 'weight_class_2': 0.3644582385802562}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:02,750] Trial 1995 finished with value: 0.9465308185714982 and parameters: {'weight_class_0': 0.03219274597705527, 'weight_class_1': 0.12633851762236206, 'weight_class_2': 0.363758762296587}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:02,783] Trial 1996 finished with value: 0.9485141348093746 and parameters: {'weight_class_0': 0.029437375963005018, 'weight_class_1': 1.271497241551134, 'weight_class_2': 0.37548121109990484}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:02,860] Trial 1997 finished with value: 0.9488127399180195 and parameters: {'weight_class_0': 0.036829317794528096, 'weight_class_1': 1.0026585490096087, 'weight_class_2': 0.773887664062134}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:02,874] Trial 1998 finished with value: 0.9484456179290927 and parameters: {'weight_class_0': 0.036485833642915674, 'weight_class_1': 1.2365488827627855, 'weight_class_2': 0.8102525332026579}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:02,896] Trial 2000 finished with value: 0.9428680173919682 and parameters: {'weight_class_0': 0.03585913780027571, 'weight_class_1': 0.11716675515464006, 'weight_class_2': 1.0477574106119167}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:02,903] Trial 1999 finished with value: 0.946692918175927 and parameters: {'weight_class_0': 0.023767953797540032, 'weight_class_1': 1.2516614344422663, 'weight_class_2': 0.7699394356700959}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:02,929] Trial 2001 finished with value: 0.9472148888542793 and parameters: {'weight_class_0': 0.036904810361937546, 'weight_class_1': 1.7625267535096034, 'weight_class_2': 1.056026941518062}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  67%|███████████████████████████████████████████████████████████████████████████████████████                                           | 2008/3000 [00:48<00:29, 33.98it/s]

[I 2026-07-05 15:26:02,962] Trial 2002 finished with value: 0.9472967825486297 and parameters: {'weight_class_0': 0.02394237994059424, 'weight_class_1': 1.0108536468493778, 'weight_class_2': 0.8298064993399159}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:02,977] Trial 2003 finished with value: 0.94750275014384 and parameters: {'weight_class_0': 0.024431910428239022, 'weight_class_1': 0.9822454465110078, 'weight_class_2': 0.8114384787533675}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:03,023] Trial 2004 finished with value: 0.9477637689166509 and parameters: {'weight_class_0': 0.02319611187326415, 'weight_class_1': 0.7097333484401598, 'weight_class_2': 0.8541254674036096}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:03,064] Trial 2005 finished with value: 0.9474353082179681 and parameters: {'weight_class_0': 0.023474369640182305, 'weight_class_1': 0.9691388243712569, 'weight_class_2': 0.777619322104146}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:03,076] Trial 2006 finished with value: 0.9475277175384157 and parameters: {'weight_class_0': 0.024380533519870243, 'weight_class_1': 0.939227385011328, 'weight_class_2': 0.8327061634053484}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:03,114] Trial 2007 finished with value: 0.9489228097237303 and parameters: {'weight_class_0': 0.037931298644195546, 'weight_class_1': 0.7104148975401905, 'weight_class_2': 0.8046646492305831}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:03,124] Trial 2008 finished with value: 0.947307259840569 and parameters: {'weight_class_0': 0.023095191547427278, 'weight_class_1': 0.6922107914002198, 'weight_class_2': 1.0450867294373216}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:03,220] Trial 2011 finished with value: 0.9487658668478272 and parameters: {'weight_class_0': 0.023473691488422353, 'weight_class_1': 0.6975534596860233, 'weight_class_2': 0.48555042609005716}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:03,240] Trial 2010 finished with value: 0.9486749148712906 and parameters: {'weight_class_0': 0.02309301709221606, 'weight_class_1': 0.7063537203601666, 'weight_class_2': 0.49923732066889687}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:03,258] Trial 2009 finished with value: 0.9496456490949723 and parameters: {'weight_class_0': 0.04919579788176035, 'weight_class_1': 0.7488848076637699, 'weight_class_2': 0.5108843254288952}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:03,281] Trial 2012 finished with value: 0.9496596081635448 and parameters: {'weight_class_0': 0.04842255630306223, 'weight_class_1': 0.7453861470687566, 'weight_class_2': 0.5042321160045312}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:03,302] Trial 2013 finished with value: 0.949649425574267 and parameters: {'weight_class_0': 0.04995874836968579, 'weight_class_1': 0.7163285127066554, 'weight_class_2': 0.5009403201339724}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:03,373] Trial 2014 finished with value: 0.9497181868875386 and parameters: {'weight_class_0': 0.05024255120890547, 'weight_class_1': 0.736431210499517, 'weight_class_2': 0.5100538158403135}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:03,374] Trial 2015 finished with value: 0.9496551654870687 and parameters: {'weight_class_0': 0.05047014879956141, 'weight_class_1': 0.7223340654045133, 'weight_class_2': 0.5037050086939222}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:03,405] Trial 2016 finished with value: 0.9497968249389827 and parameters: {'weight_class_0': 0.04611753936807671, 'weight_class_1': 0.711711850800429, 'weight_class_2': 0.5138787175966631}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:03,447] Trial 2017 finished with value: 0.9485363501867865 and parameters: {'weight_class_0': 0.049318419779677165, 'weight_class_1': 0.30394919033961787, 'weight_class_2': 0.49514529124100487}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:03,486] Trial 2019 finished with value: 0.9496883072830551 and parameters: {'weight_class_0': 0.04736973999741162, 'weight_class_1': 0.6276159527042473, 'weight_class_2': 0.5045056475877203}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:03,490] Trial 2018 finished with value: 0.9496346939145516 and parameters: {'weight_class_0': 0.04883344749741786, 'weight_class_1': 0.7473023462344092, 'weight_class_2': 0.49155773144525794}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:03,511] Trial 2020 finished with value: 0.9496319081086148 and parameters: {'weight_class_0': 0.05082733363294058, 'weight_class_1': 0.6333541433381723, 'weight_class_2': 0.5033484041847397}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:03,538] Trial 2021 finished with value: 0.9496882577329598 and parameters: {'weight_class_0': 0.04703825089399571, 'weight_class_1': 0.8351880009029715, 'weight_class_2': 0.5994215499903544}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:03,574] Trial 2022 finished with value: 0.9496977452405381 and parameters: {'weight_class_0': 0.04750888037319405, 'weight_class_1': 0.8572214486106604, 'weight_class_2': 0.6017061514769707}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:03,594] Trial 2023 finished with value: 0.9481355468647402 and parameters: {'weight_class_0': 0.016165019813938034, 'weight_class_1': 0.6101958993211037, 'weight_class_2': 0.10341867444564082}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:03,621] Trial 2024 finished with value: 0.9486824489793398 and parameters: {'weight_class_0': 0.04021156725811836, 'weight_class_1': 0.2897879469000085, 'weight_class_2': 0.5409574893449886}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:03,637] Trial 2025 finished with value: 0.9483098809560979 and parameters: {'weight_class_0': 0.03805201053782963, 'weight_class_1': 0.6104150606757692, 'weight_class_2': 0.20020217094343373}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:03,704] Trial 2027 finished with value: 0.9493129828387522 and parameters: {'weight_class_0': 0.037929786234684355, 'weight_class_1': 0.601661270305503, 'weight_class_2': 0.6464388432445932}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:03,749] Trial 2026 finished with value: 0.9482790409560501 and parameters: {'weight_class_0': 0.03691902187753289, 'weight_class_1': 0.30071909158960325, 'weight_class_2': 0.20254722829061808}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:03,758] Trial 2028 finished with value: 0.9493633780172243 and parameters: {'weight_class_0': 0.03766320960558195, 'weight_class_1': 0.6083653002103065, 'weight_class_2': 0.6210345974090286}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:03,762] Trial 2029 finished with value: 0.9478176380876085 and parameters: {'weight_class_0': 0.01729255827247088, 'weight_class_1': 0.41407241059383076, 'weight_class_2': 0.6011557760925086}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:03,824] Trial 2030 finished with value: 0.9337796820502531 and parameters: {'weight_class_0': 0.016717266303282158, 'weight_class_1': 2.092406857037756, 'weight_class_2': 0.27010805577363955}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:03,865] Trial 2031 finished with value: 0.9490481213959371 and parameters: {'weight_class_0': 0.03693093837916423, 'weight_class_1': 0.41386468331878357, 'weight_class_2': 0.6160639679189107}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:03,898] Trial 2032 finished with value: 0.9496241516451827 and parameters: {'weight_class_0': 0.03807845981453034, 'weight_class_1': 0.41462163705753163, 'weight_class_2': 0.4148612943477262}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:03,921] Trial 2033 finished with value: 0.9464859872282503 and parameters: {'weight_class_0': 0.03872951638305729, 'weight_class_1': 2.1165245894807927, 'weight_class_2': 0.21613253181489261}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:03,950] Trial 2034 finished with value: 0.9496531865254217 and parameters: {'weight_class_0': 0.02745128062025032, 'weight_class_1': 0.4095648862361889, 'weight_class_2': 0.26214401906079304}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:03,970] Trial 2035 finished with value: 0.9493206368193478 and parameters: {'weight_class_0': 0.036359886003610245, 'weight_class_1': 0.42050402627438044, 'weight_class_2': 0.277581933109409}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:04,007] Trial 2036 finished with value: 0.9477514403649813 and parameters: {'weight_class_0': 0.03958507059988697, 'weight_class_1': 2.0415729356271672, 'weight_class_2': 0.6448555082632671}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:04,022] Trial 2037 finished with value: 0.9237294531739675 and parameters: {'weight_class_0': 0.0638715078315727, 'weight_class_1': 0.40667502849341575, 'weight_class_2': 0.09390387537127823}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  68%|████████████████████████████████████████████████████████████████████████████████████████▌                                         | 2045/3000 [00:49<00:29, 32.84it/s]

[I 2026-07-05 15:26:04,095] Trial 2038 finished with value: 0.9496503876020118 and parameters: {'weight_class_0': 0.028777879272395772, 'weight_class_1': 0.42260407439660036, 'weight_class_2': 0.28111814150182235}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:04,114] Trial 2039 finished with value: 0.9496339819142983 and parameters: {'weight_class_0': 0.029116540351228303, 'weight_class_1': 0.4342311375821558, 'weight_class_2': 0.26350934804027193}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:04,166] Trial 2040 finished with value: 0.9494423885245311 and parameters: {'weight_class_0': 0.027775793466828857, 'weight_class_1': 0.4327901651620231, 'weight_class_2': 0.43488317859161324}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:04,174] Trial 2041 finished with value: 0.9494447532573936 and parameters: {'weight_class_0': 0.026833128384370804, 'weight_class_1': 0.41776239867044623, 'weight_class_2': 0.41740020403296973}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:04,179] Trial 2042 finished with value: 0.94904349009951 and parameters: {'weight_class_0': 0.027201482047947232, 'weight_class_1': 0.9089366397180595, 'weight_class_2': 0.424885812331259}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:04,229] Trial 2043 finished with value: 0.9447069008135011 and parameters: {'weight_class_0': 0.027155662804460773, 'weight_class_1': 1.0569946819458969, 'weight_class_2': 0.09346647648982233}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:04,236] Trial 2044 finished with value: 0.9491098542535052 and parameters: {'weight_class_0': 0.027806146385901804, 'weight_class_1': 0.9289024850868975, 'weight_class_2': 0.2577606153136897}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:04,284] Trial 2045 finished with value: 0.9493372093867204 and parameters: {'weight_class_0': 0.02961418793184939, 'weight_class_1': 0.8763773942595865, 'weight_class_2': 0.40687296670844614}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  68%|████████████████████████████████████████████████████████████████████████████████████████▉                                         | 2052/3000 [00:49<00:28, 33.56it/s]

[I 2026-07-05 15:26:04,321] Trial 2046 finished with value: 0.9487622300846873 and parameters: {'weight_class_0': 0.06677597914881661, 'weight_class_1': 0.8853027259217291, 'weight_class_2': 0.39825226588274365}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:04,340] Trial 2047 finished with value: 0.9488921610531748 and parameters: {'weight_class_0': 0.06806594701291378, 'weight_class_1': 0.9064797244066088, 'weight_class_2': 0.42309615534656086}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:04,355] Trial 2048 finished with value: 0.9490239387250275 and parameters: {'weight_class_0': 0.028496571910471134, 'weight_class_1': 0.9644989556489411, 'weight_class_2': 0.44425003051538825}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:04,407] Trial 2049 finished with value: 0.9491236168310756 and parameters: {'weight_class_0': 0.028647755403530425, 'weight_class_1': 0.9134591219711437, 'weight_class_2': 0.4396027692077327}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:04,440] Trial 2050 finished with value: 0.94890640830141 and parameters: {'weight_class_0': 0.06612111742767013, 'weight_class_1': 0.8840400193863981, 'weight_class_2': 0.41233795695597475}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:04,441] Trial 2051 finished with value: 0.9490007844862843 and parameters: {'weight_class_0': 0.06683066305226498, 'weight_class_1': 1.0466285157946593, 'weight_class_2': 0.4402272456077014}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:04,523] Trial 2052 finished with value: 0.9380220010222554 and parameters: {'weight_class_0': 0.010141980023639453, 'weight_class_1': 1.0926520690473716, 'weight_class_2': 0.411061902801023}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:04,553] Trial 2053 finished with value: 0.9479236573190901 and parameters: {'weight_class_0': 0.08150621053440514, 'weight_class_1': 1.0659410631559512, 'weight_class_2': 0.3920530840860005}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:04,580] Trial 2054 finished with value: 0.9373243485429518 and parameters: {'weight_class_0': 0.06690072841492256, 'weight_class_1': 0.8990011111805883, 'weight_class_2': 0.14610163305328092}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:04,595] Trial 2055 finished with value: 0.9486036855889659 and parameters: {'weight_class_0': 0.06679737596654499, 'weight_class_1': 0.8751590684886331, 'weight_class_2': 0.38308985847929483}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:04,608] Trial 2056 finished with value: 0.9398442993517367 and parameters: {'weight_class_0': 0.010644764089889095, 'weight_class_1': 1.1131460876358505, 'weight_class_2': 0.1754399284694644}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:04,636] Trial 2057 finished with value: 0.9301846207170646 and parameters: {'weight_class_0': 0.08480770819603692, 'weight_class_1': 0.5944276804234107, 'weight_class_2': 0.14889863991289673}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:04,687] Trial 2059 finished with value: 0.9486899907166736 and parameters: {'weight_class_0': 0.08918781675661003, 'weight_class_1': 0.5780227208551423, 'weight_class_2': 0.6933537048756284}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:04,706] Trial 2058 finished with value: 0.9488459659207207 and parameters: {'weight_class_0': 0.018682850051965096, 'weight_class_1': 0.5821739863007955, 'weight_class_2': 0.35606393337061454}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:04,727] Trial 2060 finished with value: 0.9359648489130903 and parameters: {'weight_class_0': 0.08224888679416302, 'weight_class_1': 0.5772085634057327, 'weight_class_2': 0.1736020106118187}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:04,731] Trial 2061 finished with value: 0.9452772009647651 and parameters: {'weight_class_0': 0.01107750756566729, 'weight_class_1': 0.5971105194034596, 'weight_class_2': 0.7120788628988322}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:04,801] Trial 2063 finished with value: 0.9482720230236416 and parameters: {'weight_class_0': 0.09678130171816832, 'weight_class_1': 0.5687725308595392, 'weight_class_2': 0.6994596657600484}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:04,804] Trial 2062 finished with value: 0.9307936626704588 and parameters: {'weight_class_0': 0.08365374697886083, 'weight_class_1': 0.6006831038490313, 'weight_class_2': 0.14901994475928443}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:04,856] Trial 2064 finished with value: 0.9309762359794161 and parameters: {'weight_class_0': 0.08620052642475966, 'weight_class_1': 0.5700603690967795, 'weight_class_2': 0.15551431931806736}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:04,892] Trial 2065 finished with value: 0.9485090123379774 and parameters: {'weight_class_0': 0.0930465855819634, 'weight_class_1': 0.6152808181104239, 'weight_class_2': 0.6661511210924544}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:04,933] Trial 2067 finished with value: 0.9478080934943973 and parameters: {'weight_class_0': 0.018823174628651677, 'weight_class_1': 0.6202264428907713, 'weight_class_2': 0.6401104152401025}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  69%|█████████████████████████████████████████████████████████████████████████████████████████▊                                        | 2073/3000 [00:50<00:28, 32.81it/s]

[I 2026-07-05 15:26:04,951] Trial 2066 finished with value: 0.9478466388097838 and parameters: {'weight_class_0': 0.019475276910589846, 'weight_class_1': 0.5832061428156881, 'weight_class_2': 0.6947475793343781}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:04,978] Trial 2068 finished with value: 0.948085162060018 and parameters: {'weight_class_0': 0.020579043760900643, 'weight_class_1': 0.5841354546124432, 'weight_class_2': 0.6675389129368902}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:05,026] Trial 2070 finished with value: 0.9472467078149327 and parameters: {'weight_class_0': 0.04124128001805645, 'weight_class_1': 0.19765195849396489, 'weight_class_2': 0.6198569749344714}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:05,027] Trial 2069 finished with value: 0.9483910397090001 and parameters: {'weight_class_0': 0.04230289593706913, 'weight_class_1': 0.5893266912490615, 'weight_class_2': 0.9773074958139698}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:05,081] Trial 2071 finished with value: 0.9488878937300975 and parameters: {'weight_class_0': 0.042711731269789076, 'weight_class_1': 1.5554400094888865, 'weight_class_2': 0.6047401858437632}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:05,091] Trial 2072 finished with value: 0.9470225309671818 and parameters: {'weight_class_0': 0.04202830867097279, 'weight_class_1': 0.1921416733010312, 'weight_class_2': 0.6269624860148144}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:05,154] Trial 2073 finished with value: 0.9486599709071845 and parameters: {'weight_class_0': 0.04402591763092417, 'weight_class_1': 0.7291368099179205, 'weight_class_2': 0.9852301481391783}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  69%|██████████████████████████████████████████████████████████████████████████████████████████▏                                       | 2080/3000 [00:50<00:28, 32.20it/s]

[I 2026-07-05 15:26:05,184] Trial 2074 finished with value: 0.9481442728914548 and parameters: {'weight_class_0': 0.044650654219457596, 'weight_class_1': 1.6876776667136468, 'weight_class_2': 0.2915484114797713}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:05,210] Trial 2075 finished with value: 0.9496373771227548 and parameters: {'weight_class_0': 0.04349341098306707, 'weight_class_1': 0.7389395065602776, 'weight_class_2': 0.5819242993179627}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:05,243] Trial 2077 finished with value: 0.9483063269204256 and parameters: {'weight_class_0': 0.04264136460619526, 'weight_class_1': 1.597643836324903, 'weight_class_2': 0.299747997175828}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:05,252] Trial 2076 finished with value: 0.9497005854463629 and parameters: {'weight_class_0': 0.04247273705148419, 'weight_class_1': 0.7174866504782494, 'weight_class_2': 0.5555044125869688}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:05,273] Trial 2079 finished with value: 0.949457228507738 and parameters: {'weight_class_0': 0.03517334989131703, 'weight_class_1': 0.47781606241440555, 'weight_class_2': 0.2896478197144745}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:05,307] Trial 2078 finished with value: 0.9487899162523029 and parameters: {'weight_class_0': 0.0436341071046159, 'weight_class_1': 0.7547409734363498, 'weight_class_2': 0.9523405204207122}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:05,344] Trial 2080 finished with value: 0.9496116128267666 and parameters: {'weight_class_0': 0.03431162652859249, 'weight_class_1': 0.760403087792986, 'weight_class_2': 0.3089251595404347}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:05,407] Trial 2082 finished with value: 0.9495838370876007 and parameters: {'weight_class_0': 0.0323588939592909, 'weight_class_1': 0.3199001107457176, 'weight_class_2': 0.34500051607008103}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:05,418] Trial 2083 finished with value: 0.9496154558316291 and parameters: {'weight_class_0': 0.031972592881586055, 'weight_class_1': 0.3165354615518228, 'weight_class_2': 0.3081402243053975}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:05,424] Trial 2081 finished with value: 0.9479568007704592 and parameters: {'weight_class_0': 0.033917339484129116, 'weight_class_1': 1.7206283690761148, 'weight_class_2': 0.3107643957498675}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:05,440] Trial 2084 finished with value: 0.9495849221291759 and parameters: {'weight_class_0': 0.03360495542703923, 'weight_class_1': 0.7389678423329157, 'weight_class_2': 0.30556257796125535}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:05,514] Trial 2085 finished with value: 0.9496821631511003 and parameters: {'weight_class_0': 0.03144981896292374, 'weight_class_1': 0.6973610952498345, 'weight_class_2': 0.33470897931366844}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:05,540] Trial 2086 finished with value: 0.9495715081483516 and parameters: {'weight_class_0': 0.032745371207942124, 'weight_class_1': 0.3344903343670696, 'weight_class_2': 0.35759355389687975}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:05,575] Trial 2087 finished with value: 0.9496442151974662 and parameters: {'weight_class_0': 0.03451707856202893, 'weight_class_1': 0.4776783823434551, 'weight_class_2': 0.34684354173669424}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:05,583] Trial 2088 finished with value: 0.9495182914224376 and parameters: {'weight_class_0': 0.03316921893856999, 'weight_class_1': 0.3012386822613364, 'weight_class_2': 0.33612685220994803}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:05,636] Trial 2089 finished with value: 0.9496199528385083 and parameters: {'weight_class_0': 0.032734171729580465, 'weight_class_1': 0.36110524563997415, 'weight_class_2': 0.34773010890699174}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:05,660] Trial 2090 finished with value: 0.9467514653667015 and parameters: {'weight_class_0': 0.033310905864820516, 'weight_class_1': 0.3053746924766685, 'weight_class_2': 1.220889836639907}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:05,668] Trial 2091 finished with value: 0.9467158378274841 and parameters: {'weight_class_0': 0.007199909415134623, 'weight_class_1': 0.3121497209218106, 'weight_class_2': 0.3453221260395783}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:05,727] Trial 2092 finished with value: 0.9463406036491152 and parameters: {'weight_class_0': 0.05569673491891801, 'weight_class_1': 0.30693842845850877, 'weight_class_2': 0.24027539779892368}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:05,731] Trial 2093 finished with value: 0.947311555620619 and parameters: {'weight_class_0': 0.056003778046767975, 'weight_class_1': 0.4933646011095754, 'weight_class_2': 0.24225773272478093}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  70%|███████████████████████████████████████████████████████████████████████████████████████████                                       | 2101/3000 [00:51<00:28, 31.76it/s]

[I 2026-07-05 15:26:05,820] Trial 2096 finished with value: 0.9469648469699291 and parameters: {'weight_class_0': 0.05622387979196451, 'weight_class_1': 0.4950538373224891, 'weight_class_2': 0.22993048140872624}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:05,824] Trial 2095 finished with value: 0.9493532946435 and parameters: {'weight_class_0': 0.058164686504473165, 'weight_class_1': 0.5113149295470679, 'weight_class_2': 0.4829718824193318}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:05,826] Trial 2094 finished with value: 0.9472592057415641 and parameters: {'weight_class_0': 0.05525800840535002, 'weight_class_1': 0.47481138487716623, 'weight_class_2': 0.2365095959691659}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:05,883] Trial 2097 finished with value: 0.9467870635404525 and parameters: {'weight_class_0': 0.05597367714023537, 'weight_class_1': 0.4777894662921829, 'weight_class_2': 0.22376752934952868}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:05,939] Trial 2098 finished with value: 0.9465767018936916 and parameters: {'weight_class_0': 0.05901902158520233, 'weight_class_1': 0.481356968264821, 'weight_class_2': 0.23296566296817003}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:05,953] Trial 2099 finished with value: 0.9470668851853855 and parameters: {'weight_class_0': 0.05597498471470626, 'weight_class_1': 0.4865757394756529, 'weight_class_2': 0.23197763395662768}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:05,959] Trial 2100 finished with value: 0.9493810805990962 and parameters: {'weight_class_0': 0.056319103497465405, 'weight_class_1': 0.4830940037943617, 'weight_class_2': 0.479842884262603}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:05,987] Trial 2101 finished with value: 0.9494357301404922 and parameters: {'weight_class_0': 0.058193718046036784, 'weight_class_1': 0.5197970316753606, 'weight_class_2': 0.501622533737963}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  70%|███████████████████████████████████████████████████████████████████████████████████████████▍                                      | 2109/3000 [00:51<00:25, 34.38it/s]

[I 2026-07-05 15:26:06,037] Trial 2102 finished with value: 0.9462249843305383 and parameters: {'weight_class_0': 0.05619459534851538, 'weight_class_1': 0.47390554708076404, 'weight_class_2': 0.21253744100400332}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:06,059] Trial 2103 finished with value: 0.9474098141647663 and parameters: {'weight_class_0': 0.05302076968875383, 'weight_class_1': 0.4823161683036301, 'weight_class_2': 0.2322888270030992}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:06,079] Trial 2104 finished with value: 0.9496262177430469 and parameters: {'weight_class_0': 0.05450254583058279, 'weight_class_1': 1.14526099435008, 'weight_class_2': 0.49262268322814695}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:06,105] Trial 2105 finished with value: 0.9494806861893155 and parameters: {'weight_class_0': 0.053202664691995964, 'weight_class_1': 0.4685369720135217, 'weight_class_2': 0.4738729854925407}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:06,155] Trial 2106 finished with value: 0.9476413991305463 and parameters: {'weight_class_0': 0.023066246121228446, 'weight_class_1': 1.1161107474838359, 'weight_class_2': 0.48300015132343027}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:06,169] Trial 2107 finished with value: 0.943451629173786 and parameters: {'weight_class_0': 0.01392106874735998, 'weight_class_1': 1.1481914788517018, 'weight_class_2': 0.4708984284313034}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:06,186] Trial 2108 finished with value: 0.9421692513478653 and parameters: {'weight_class_0': 0.013068751861956175, 'weight_class_1': 1.1463584048113133, 'weight_class_2': 0.07995854917234503}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:06,220] Trial 2109 finished with value: 0.9472795081429718 and parameters: {'weight_class_0': 0.021770520683828364, 'weight_class_1': 1.1326623236848756, 'weight_class_2': 0.501332427982707}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:06,313] Trial 2110 finished with value: 0.9450676758441814 and parameters: {'weight_class_0': 0.02320863335743186, 'weight_class_1': 0.8255389156352578, 'weight_class_2': 0.080787879344808}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:06,320] Trial 2111 finished with value: 0.9460523779329937 and parameters: {'weight_class_0': 0.013752483547392702, 'weight_class_1': 0.8401305143833552, 'weight_class_2': 0.4727497832737117}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:06,325] Trial 2112 finished with value: 0.948208278664236 and parameters: {'weight_class_0': 0.025560348410941847, 'weight_class_1': 1.1457308198512297, 'weight_class_2': 0.44132904576955784}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:06,405] Trial 2113 finished with value: 0.9456392792504912 and parameters: {'weight_class_0': 0.013276666896922713, 'weight_class_1': 0.8252458755617176, 'weight_class_2': 0.5473159178145787}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:06,414] Trial 2115 finished with value: 0.9484559457145955 and parameters: {'weight_class_0': 0.02496736448218258, 'weight_class_1': 0.8307096653034164, 'weight_class_2': 0.5557671577677021}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:06,446] Trial 2116 finished with value: 0.9463162085744062 and parameters: {'weight_class_0': 0.014461759640334595, 'weight_class_1': 0.7986105273417504, 'weight_class_2': 0.5589139156542788}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:06,449] Trial 2114 finished with value: 0.947997477553382 and parameters: {'weight_class_0': 0.021970254715926795, 'weight_class_1': 0.8315593424761905, 'weight_class_2': 0.5527846658475914}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:06,475] Trial 2117 finished with value: 0.9466630989900517 and parameters: {'weight_class_0': 0.014367472261205083, 'weight_class_1': 0.7956473552854249, 'weight_class_2': 0.43278768501245074}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:06,488] Trial 2118 finished with value: 0.9491134912912577 and parameters: {'weight_class_0': 0.02583137305974583, 'weight_class_1': 0.8264827836772127, 'weight_class_2': 0.3966162989341152}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:06,560] Trial 2120 finished with value: 0.9496294845913155 and parameters: {'weight_class_0': 0.037840760999142624, 'weight_class_1': 0.7888630185431613, 'weight_class_2': 0.37881345561416196}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:06,565] Trial 2119 finished with value: 0.9483361041616939 and parameters: {'weight_class_0': 0.02454851263946377, 'weight_class_1': 0.8489335000096386, 'weight_class_2': 0.5743299654471999}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:06,576] Trial 2121 finished with value: 0.9484995244424148 and parameters: {'weight_class_0': 0.025938627230930184, 'weight_class_1': 0.8507209739693435, 'weight_class_2': 0.5725635402276938}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:06,608] Trial 2122 finished with value: 0.9494838674583396 and parameters: {'weight_class_0': 0.038707331465231504, 'weight_class_1': 0.6433663805896224, 'weight_class_2': 0.5876948306161782}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:06,700] Trial 2124 finished with value: 0.9489226545402754 and parameters: {'weight_class_0': 0.027944892894408165, 'weight_class_1': 0.6504836547128472, 'weight_class_2': 0.5720344455473475}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  71%|████████████████████████████████████████████████████████████████████████████████████████████▎                                     | 2131/3000 [00:52<00:25, 33.65it/s]

[I 2026-07-05 15:26:06,712] Trial 2123 finished with value: 0.9496782700594227 and parameters: {'weight_class_0': 0.03830209287107922, 'weight_class_1': 0.693646162875778, 'weight_class_2': 0.38726057340214964}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:06,737] Trial 2125 finished with value: 0.9495761104435615 and parameters: {'weight_class_0': 0.04597130294270607, 'weight_class_1': 0.6781396325314235, 'weight_class_2': 0.3900084871396773}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:06,750] Trial 2126 finished with value: 0.9496979752602579 and parameters: {'weight_class_0': 0.038689348811067184, 'weight_class_1': 0.6868821219727995, 'weight_class_2': 0.379781751110617}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:06,779] Trial 2127 finished with value: 0.9491123433224633 and parameters: {'weight_class_0': 0.038136879772931044, 'weight_class_1': 0.6561457497188646, 'weight_class_2': 0.7505436178875482}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:06,809] Trial 2128 finished with value: 0.9489875423661679 and parameters: {'weight_class_0': 0.03995887773861621, 'weight_class_1': 0.643304636990939, 'weight_class_2': 0.7939288315245862}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:06,832] Trial 2129 finished with value: 0.9490455733069642 and parameters: {'weight_class_0': 0.04098049632107927, 'weight_class_1': 0.6624300057014657, 'weight_class_2': 0.79282313976168}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:06,861] Trial 2130 finished with value: 0.9488152952751655 and parameters: {'weight_class_0': 0.03872923770209239, 'weight_class_1': 0.6407727539633304, 'weight_class_2': 0.8141758213117906}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:06,913] Trial 2132 finished with value: 0.9486612218959398 and parameters: {'weight_class_0': 0.04460187491075599, 'weight_class_1': 0.6612794358730959, 'weight_class_2': 0.9489709359779648}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  71%|████████████████████████████████████████████████████████████████████████████████████████████▌                                     | 2137/3000 [00:52<00:27, 31.42it/s]

[I 2026-07-05 15:26:06,929] Trial 2131 finished with value: 0.9492179074216823 and parameters: {'weight_class_0': 0.04813080630955466, 'weight_class_1': 0.6449966649815638, 'weight_class_2': 0.8067619878590059}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:06,970] Trial 2133 finished with value: 0.9492276881740144 and parameters: {'weight_class_0': 0.04780748699220619, 'weight_class_1': 1.436635297022436, 'weight_class_2': 0.7550410065561641}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:07,006] Trial 2134 finished with value: 0.949371455328034 and parameters: {'weight_class_0': 0.07446750801795167, 'weight_class_1': 0.6339329942182239, 'weight_class_2': 0.769818260700242}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:07,078] Trial 2135 finished with value: 0.9497311387961315 and parameters: {'weight_class_0': 0.07127535928014275, 'weight_class_1': 1.4352716400281906, 'weight_class_2': 0.8635903575188666}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:07,091] Trial 2136 finished with value: 0.9317795224587478 and parameters: {'weight_class_0': 0.07459101528267836, 'weight_class_1': 0.12347657863375756, 'weight_class_2': 0.7384106465450899}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:07,149] Trial 2137 finished with value: 0.9496265807956136 and parameters: {'weight_class_0': 0.06883444339081064, 'weight_class_1': 1.4115019664677637, 'weight_class_2': 0.8952575559631629}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:07,163] Trial 2138 finished with value: 0.9497365756796814 and parameters: {'weight_class_0': 0.07372618179471495, 'weight_class_1': 1.4702363701820078, 'weight_class_2': 0.8955181030326498}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:07,188] Trial 2139 finished with value: 0.9454450229932881 and parameters: {'weight_class_0': 0.07218591183980583, 'weight_class_1': 0.3802435509211813, 'weight_class_2': 0.27821122054596603}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:07,197] Trial 2140 finished with value: 0.9306923933505598 and parameters: {'weight_class_0': 0.07405533726702722, 'weight_class_1': 0.13144257142846244, 'weight_class_2': 0.2846925661018585}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:07,204] Trial 2141 finished with value: 0.9322312092992643 and parameters: {'weight_class_0': 0.07211984533012232, 'weight_class_1': 0.17636039624284264, 'weight_class_2': 0.18464896991630708}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:07,225] Trial 2142 finished with value: 0.9492448107966863 and parameters: {'weight_class_0': 0.07435004324257803, 'weight_class_1': 0.9886817123687212, 'weight_class_2': 1.233559061714443}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:07,275] Trial 2143 finished with value: 0.9474194499022047 and parameters: {'weight_class_0': 0.07418781036591844, 'weight_class_1': 0.3769407581471433, 'weight_class_2': 0.4379753506767463}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:07,285] Trial 2144 finished with value: 0.9477189289207542 and parameters: {'weight_class_0': 0.07025300566783507, 'weight_class_1': 0.3862155470870905, 'weight_class_2': 1.1170393737612718}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:07,290] Trial 2145 finished with value: 0.9263783866785613 and parameters: {'weight_class_0': 0.0699012038120678, 'weight_class_1': 0.40420220374321153, 'weight_class_2': 0.11126222153544724}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  72%|█████████████████████████████████████████████████████████████████████████████████████████████▎                                    | 2153/3000 [00:53<00:24, 33.99it/s]

[I 2026-07-05 15:26:07,328] Trial 2146 finished with value: 0.8793116116773828 and parameters: {'weight_class_0': 0.6790200008558744, 'weight_class_1': 1.047505555271818, 'weight_class_2': 0.40664276300395896}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:07,405] Trial 2147 finished with value: 0.9456829348023597 and parameters: {'weight_class_0': 0.018155060051065756, 'weight_class_1': 0.39699612709941834, 'weight_class_2': 1.2406453587340425}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:07,409] Trial 2148 finished with value: 0.9496639580157441 and parameters: {'weight_class_0': 0.029338689069310763, 'weight_class_1': 0.3986630614103174, 'weight_class_2': 0.27366949004840657}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:07,479] Trial 2149 finished with value: 0.9493732330155096 and parameters: {'weight_class_0': 0.028308272819262913, 'weight_class_1': 0.3767273151529753, 'weight_class_2': 0.4264931651712419}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:07,506] Trial 2150 finished with value: 0.8279993761088561 and parameters: {'weight_class_0': 1.3107364609356988, 'weight_class_1': 0.3851260104265287, 'weight_class_2': 0.1023027737769044}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:07,540] Trial 2151 finished with value: 0.9493936618741726 and parameters: {'weight_class_0': 0.02803772449909059, 'weight_class_1': 0.3907004619363064, 'weight_class_2': 0.4395271382558132}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:07,572] Trial 2153 finished with value: 0.9496083200629825 and parameters: {'weight_class_0': 0.029813679573261087, 'weight_class_1': 0.4069625836626562, 'weight_class_2': 0.3823361491075568}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:07,576] Trial 2152 finished with value: 0.9488677331620158 and parameters: {'weight_class_0': 0.017672317474976256, 'weight_class_1': 0.42160666557586673, 'weight_class_2': 0.37227725777133985}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  72%|█████████████████████████████████████████████████████████████████████████████████████████████▌                                    | 2160/3000 [00:53<00:26, 31.89it/s]

[I 2026-07-05 15:26:07,635] Trial 2154 finished with value: 0.9496663399268112 and parameters: {'weight_class_0': 0.0293981761654774, 'weight_class_1': 0.5511441356477792, 'weight_class_2': 0.3749544500290911}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:07,693] Trial 2155 finished with value: 0.9497297245362359 and parameters: {'weight_class_0': 0.02964196636531763, 'weight_class_1': 0.5688810097069126, 'weight_class_2': 0.3650970228352904}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:07,697] Trial 2156 finished with value: 0.9488095948813422 and parameters: {'weight_class_0': 0.01841121529999088, 'weight_class_1': 0.5439804997097327, 'weight_class_2': 0.3768842855103854}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:07,721] Trial 2157 finished with value: 0.9497287956463021 and parameters: {'weight_class_0': 0.031637546920054736, 'weight_class_1': 0.5502550581145337, 'weight_class_2': 0.34187658717694397}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:07,760] Trial 2158 finished with value: 0.9498129003832707 and parameters: {'weight_class_0': 0.029910818802930773, 'weight_class_1': 0.5686345149908006, 'weight_class_2': 0.34163379599368493}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:07,788] Trial 2159 finished with value: 0.9497792743070601 and parameters: {'weight_class_0': 0.029381775606569568, 'weight_class_1': 0.5193891033715877, 'weight_class_2': 0.34290190476703447}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:07,825] Trial 2160 finished with value: 0.9497465839903363 and parameters: {'weight_class_0': 0.02913998109261457, 'weight_class_1': 0.5448556881452921, 'weight_class_2': 0.3537464932747997}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  72%|█████████████████████████████████████████████████████████████████████████████████████████████▊                                    | 2166/3000 [00:53<00:24, 33.96it/s]

[I 2026-07-05 15:26:07,838] Trial 2161 finished with value: 0.9497315456030851 and parameters: {'weight_class_0': 0.03330367762890517, 'weight_class_1': 0.5366847314588019, 'weight_class_2': 0.3654155589756215}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:07,839] Trial 2162 finished with value: 0.9496905165650982 and parameters: {'weight_class_0': 0.03357673203633469, 'weight_class_1': 0.5494001157714842, 'weight_class_2': 0.32631498976256207}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:07,885] Trial 2163 finished with value: 0.9430686827206998 and parameters: {'weight_class_0': 0.11169147922947081, 'weight_class_1': 0.5562619881267341, 'weight_class_2': 0.35072047485680086}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:07,920] Trial 2165 finished with value: 0.9495223700675854 and parameters: {'weight_class_0': 0.047182407732617435, 'weight_class_1': 0.5685418136758605, 'weight_class_2': 0.6078520724276453}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:07,941] Trial 2164 finished with value: 0.9496069033924203 and parameters: {'weight_class_0': 0.04815409876182529, 'weight_class_1': 0.558697748491858, 'weight_class_2': 0.5950781914585256}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:07,962] Trial 2166 finished with value: 0.9495588591174746 and parameters: {'weight_class_0': 0.04726576377586144, 'weight_class_1': 0.5575286466896106, 'weight_class_2': 0.5943529525327993}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:08,060] Trial 2167 finished with value: 0.9496490770015938 and parameters: {'weight_class_0': 0.04852570377616309, 'weight_class_1': 1.0589202870507022, 'weight_class_2': 0.6110658984818986}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:08,075] Trial 2168 finished with value: 0.9497314148452621 and parameters: {'weight_class_0': 0.04817187859932638, 'weight_class_1': 0.9613134897586932, 'weight_class_2': 0.5837613907602659}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:08,111] Trial 2170 finished with value: 0.9497761615858207 and parameters: {'weight_class_0': 0.02386859707086645, 'weight_class_1': 0.5350376555806979, 'weight_class_2': 0.26920132625779036}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:08,114] Trial 2169 finished with value: 0.9494671347525268 and parameters: {'weight_class_0': 0.0213990338464571, 'weight_class_1': 0.5697448508471173, 'weight_class_2': 0.28690371848064683}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:08,169] Trial 2171 finished with value: 0.9492050175581553 and parameters: {'weight_class_0': 0.021691712799044985, 'weight_class_1': 0.6980654160233858, 'weight_class_2': 0.2926176031251751}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:08,183] Trial 2172 finished with value: 0.9495283429836667 and parameters: {'weight_class_0': 0.024416471957906097, 'weight_class_1': 0.6797298818388267, 'weight_class_2': 0.2732668269293042}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:08,191] Trial 2173 finished with value: 0.9494095762698124 and parameters: {'weight_class_0': 0.02362452063049074, 'weight_class_1': 0.7285726731352218, 'weight_class_2': 0.26482007313410577}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:08,216] Trial 2174 finished with value: 0.9492330549316569 and parameters: {'weight_class_0': 0.021631977303824705, 'weight_class_1': 0.7100000581694684, 'weight_class_2': 0.27409162025358064}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:08,243] Trial 2175 finished with value: 0.9493253265011865 and parameters: {'weight_class_0': 0.02264787375031596, 'weight_class_1': 0.724722597865623, 'weight_class_2': 0.2751035132879637}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:08,309] Trial 2176 finished with value: 0.9490756441134768 and parameters: {'weight_class_0': 0.02522871573668335, 'weight_class_1': 0.7385675204482751, 'weight_class_2': 0.44656490364531554}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:08,312] Trial 2177 finished with value: 0.9494104691793361 and parameters: {'weight_class_0': 0.023827979467396274, 'weight_class_1': 0.7365048025169283, 'weight_class_2': 0.28262596778427}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:08,331] Trial 2178 finished with value: 0.9492566873078961 and parameters: {'weight_class_0': 0.02260483824620727, 'weight_class_1': 0.7311324386049083, 'weight_class_2': 0.2841133729044116}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:08,408] Trial 2179 finished with value: 0.9492598889210755 and parameters: {'weight_class_0': 0.022047228216634872, 'weight_class_1': 0.7266724472401749, 'weight_class_2': 0.27277075872523093}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:08,466] Trial 2180 finished with value: 0.9493530255638573 and parameters: {'weight_class_0': 0.034858879312662204, 'weight_class_1': 0.7132925661533959, 'weight_class_2': 0.2757369079683802}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  73%|██████████████████████████████████████████████████████████████████████████████████████████████▊                                   | 2188/3000 [00:54<00:25, 32.41it/s]

[I 2026-07-05 15:26:08,491] Trial 2181 finished with value: 0.9496529426068809 and parameters: {'weight_class_0': 0.03523456969116349, 'weight_class_1': 0.7371223808797506, 'weight_class_2': 0.44522850761530347}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:08,494] Trial 2182 finished with value: 0.9493553270277989 and parameters: {'weight_class_0': 0.03750808135025329, 'weight_class_1': 0.7418636788301317, 'weight_class_2': 0.2923273394034075}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:08,519] Trial 2183 finished with value: 0.9495935873830142 and parameters: {'weight_class_0': 0.035083010638811654, 'weight_class_1': 0.46738829630303164, 'weight_class_2': 0.45835996577454563}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:08,553] Trial 2185 finished with value: 0.949545376169095 and parameters: {'weight_class_0': 0.03611779403023586, 'weight_class_1': 0.9314968820548661, 'weight_class_2': 0.46007235990458545}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:08,554] Trial 2186 finished with value: 0.9495042447751407 and parameters: {'weight_class_0': 0.03442836586956522, 'weight_class_1': 0.4651455665551172, 'weight_class_2': 0.4690704672485074}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:08,581] Trial 2184 finished with value: 0.9496305574467758 and parameters: {'weight_class_0': 0.03551875820058892, 'weight_class_1': 0.46921692826520855, 'weight_class_2': 0.4463289230283188}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:08,614] Trial 2188 finished with value: 0.9495672680153754 and parameters: {'weight_class_0': 0.03653182902851258, 'weight_class_1': 0.9509640820547248, 'weight_class_2': 0.45896323948135814}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:08,632] Trial 2187 finished with value: 0.949578990384999 and parameters: {'weight_class_0': 0.03503130578656706, 'weight_class_1': 0.45302152442199145, 'weight_class_2': 0.44807110839673514}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  73%|███████████████████████████████████████████████████████████████████████████████████████████████                                   | 2195/3000 [00:54<00:25, 31.69it/s]

[I 2026-07-05 15:26:08,705] Trial 2189 finished with value: 0.9494720433905542 and parameters: {'weight_class_0': 0.0339029124615691, 'weight_class_1': 0.4558905313746286, 'weight_class_2': 0.4650483909986464}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:08,728] Trial 2190 finished with value: 0.9496213337549996 and parameters: {'weight_class_0': 0.035639019030435926, 'weight_class_1': 0.4771525967440987, 'weight_class_2': 0.4567844546811114}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:08,734] Trial 2191 finished with value: 0.949661238794285 and parameters: {'weight_class_0': 0.03623002183557517, 'weight_class_1': 0.4670937710241834, 'weight_class_2': 0.4497940511509769}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:08,803] Trial 2192 finished with value: 0.949699722881256 and parameters: {'weight_class_0': 0.034552859891758346, 'weight_class_1': 0.45406512743616007, 'weight_class_2': 0.4087812289587916}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:08,860] Trial 2194 finished with value: 0.9495896819552111 and parameters: {'weight_class_0': 0.037413541011546425, 'weight_class_1': 0.4520284458937428, 'weight_class_2': 0.4694066346820154}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:08,873] Trial 2193 finished with value: 0.9495856218169108 and parameters: {'weight_class_0': 0.03609099767702234, 'weight_class_1': 0.4534634823679016, 'weight_class_2': 0.4582519286332342}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:08,885] Trial 2195 finished with value: 0.9492168033376607 and parameters: {'weight_class_0': 0.028258311900417717, 'weight_class_1': 0.9459501361759445, 'weight_class_2': 0.34728366153973256}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  73%|███████████████████████████████████████████████████████████████████████████████████████████████▍                                  | 2202/3000 [00:54<00:24, 32.47it/s]

[I 2026-07-05 15:26:08,905] Trial 2196 finished with value: 0.9494635867587157 and parameters: {'weight_class_0': 0.02871045950812637, 'weight_class_1': 0.8758127303323757, 'weight_class_2': 0.33069133347392166}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:08,932] Trial 2197 finished with value: 0.949332965085364 and parameters: {'weight_class_0': 0.027871024960970714, 'weight_class_1': 0.8970249657907959, 'weight_class_2': 0.32996659834134484}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:08,965] Trial 2198 finished with value: 0.9493509600311724 and parameters: {'weight_class_0': 0.028808757731829088, 'weight_class_1': 0.9167002149954255, 'weight_class_2': 0.3375074516154968}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:08,966] Trial 2199 finished with value: 0.9492592570055002 and parameters: {'weight_class_0': 0.027559633484184564, 'weight_class_1': 0.9139050975176723, 'weight_class_2': 0.33588335031756655}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:09,042] Trial 2200 finished with value: 0.9496037880187477 and parameters: {'weight_class_0': 0.02756882723785995, 'weight_class_1': 0.6118327686070149, 'weight_class_2': 0.35559219237878636}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:09,103] Trial 2201 finished with value: 0.9493307988173857 and parameters: {'weight_class_0': 0.04223409979172207, 'weight_class_1': 0.8593415572034184, 'weight_class_2': 0.32915634662115634}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  74%|███████████████████████████████████████████████████████████████████████████████████████████████▊                                  | 2210/3000 [00:54<00:24, 32.84it/s]

[I 2026-07-05 15:26:09,134] Trial 2202 finished with value: 0.9493558238502074 and parameters: {'weight_class_0': 0.02802872821860998, 'weight_class_1': 0.8747622461935037, 'weight_class_2': 0.3374779876200019}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:09,141] Trial 2203 finished with value: 0.9493766269253081 and parameters: {'weight_class_0': 0.028088339786898245, 'weight_class_1': 0.8712154989112583, 'weight_class_2': 0.34458919175898867}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:09,163] Trial 2204 finished with value: 0.9491815613031648 and parameters: {'weight_class_0': 0.028353658553293016, 'weight_class_1': 0.987752080300542, 'weight_class_2': 0.33166947827888416}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:09,203] Trial 2205 finished with value: 0.9497358362881204 and parameters: {'weight_class_0': 0.02774951682258954, 'weight_class_1': 0.5970480543418366, 'weight_class_2': 0.32558767072655}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:09,210] Trial 2206 finished with value: 0.9491634816439064 and parameters: {'weight_class_0': 0.04529670186341331, 'weight_class_1': 0.6240680452084439, 'weight_class_2': 0.3229860328904931}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:09,252] Trial 2207 finished with value: 0.9493157930824215 and parameters: {'weight_class_0': 0.04507401100327455, 'weight_class_1': 0.6365758153636086, 'weight_class_2': 0.3362895662513559}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:09,265] Trial 2208 finished with value: 0.9497321377579153 and parameters: {'weight_class_0': 0.044800399938415475, 'weight_class_1': 0.6492858442730044, 'weight_class_2': 0.5417574794371621}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:09,332] Trial 2209 finished with value: 0.9493738164089561 and parameters: {'weight_class_0': 0.0453071890544264, 'weight_class_1': 0.6313588431267695, 'weight_class_2': 0.6834661383254453}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  74%|████████████████████████████████████████████████████████████████████████████████████████████████                                  | 2216/3000 [00:54<00:23, 33.33it/s]

[I 2026-07-05 15:26:09,337] Trial 2210 finished with value: 0.9496655263978163 and parameters: {'weight_class_0': 0.050863183787680954, 'weight_class_1': 0.6062055542865008, 'weight_class_2': 0.5456447942787831}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:09,380] Trial 2211 finished with value: 0.9495758113722443 and parameters: {'weight_class_0': 0.04576728747670491, 'weight_class_1': 1.2295545349287584, 'weight_class_2': 0.5344474160384952}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:09,427] Trial 2212 finished with value: 0.9493860896891594 and parameters: {'weight_class_0': 0.04562916430868732, 'weight_class_1': 0.6151248466958783, 'weight_class_2': 0.6742983728940052}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:09,438] Trial 2213 finished with value: 0.9497063708615604 and parameters: {'weight_class_0': 0.046536799783286224, 'weight_class_1': 0.5872603230700839, 'weight_class_2': 0.5444561016744781}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:09,497] Trial 2215 finished with value: 0.9496707158701349 and parameters: {'weight_class_0': 0.046500774286346136, 'weight_class_1': 0.5928476626070862, 'weight_class_2': 0.5757432185706384}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:09,505] Trial 2214 finished with value: 0.9494353919869812 and parameters: {'weight_class_0': 0.0475854944151523, 'weight_class_1': 0.5972730723075245, 'weight_class_2': 0.6662021823252496}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:09,532] Trial 2216 finished with value: 0.9495934369924334 and parameters: {'weight_class_0': 0.04815287922609121, 'weight_class_1': 1.2466064181119698, 'weight_class_2': 0.5961159542336157}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  74%|████████████████████████████████████████████████████████████████████████████████████████████████▎                                 | 2223/3000 [00:55<00:24, 31.18it/s]

[I 2026-07-05 15:26:09,574] Trial 2217 finished with value: 0.9495611970729478 and parameters: {'weight_class_0': 0.05044766540433009, 'weight_class_1': 1.1574522586332103, 'weight_class_2': 0.6703445031558106}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:09,577] Trial 2218 finished with value: 0.9493946289336964 and parameters: {'weight_class_0': 0.047357636110668455, 'weight_class_1': 1.2235498093601076, 'weight_class_2': 0.673189688757128}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:09,632] Trial 2219 finished with value: 0.949550622567331 and parameters: {'weight_class_0': 0.04673683420897758, 'weight_class_1': 1.28478461890562, 'weight_class_2': 0.5439557103610188}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:09,673] Trial 2220 finished with value: 0.9497848024599049 and parameters: {'weight_class_0': 0.05959390220349299, 'weight_class_1': 1.1588764012936412, 'weight_class_2': 0.6921245959879585}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:09,697] Trial 2221 finished with value: 0.9470037450596807 and parameters: {'weight_class_0': 0.13819271615213352, 'weight_class_1': 2.6783764275270303, 'weight_class_2': 0.5633521986790467}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:09,718] Trial 2222 finished with value: 0.9494448699156545 and parameters: {'weight_class_0': 0.04050643248107916, 'weight_class_1': 1.146341598144993, 'weight_class_2': 0.5211097817800996}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:09,731] Trial 2223 finished with value: 0.9496714616013721 and parameters: {'weight_class_0': 0.061612235420474094, 'weight_class_1': 1.213108697544518, 'weight_class_2': 0.5464236932768118}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:09,788] Trial 2224 finished with value: 0.948901982877476 and parameters: {'weight_class_0': 0.05845908922182355, 'weight_class_1': 1.3642853170883842, 'weight_class_2': 0.4060146821318056}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:09,805] Trial 2225 finished with value: 0.9490870814308193 and parameters: {'weight_class_0': 0.04019786510705947, 'weight_class_1': 1.2221184338238518, 'weight_class_2': 0.6958946286301733}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:09,853] Trial 2226 finished with value: 0.9493876304015186 and parameters: {'weight_class_0': 0.040965964142832795, 'weight_class_1': 1.1389568104056644, 'weight_class_2': 0.42495825325709574}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:09,861] Trial 2227 finished with value: 0.9480571591707934 and parameters: {'weight_class_0': 0.060399342657023285, 'weight_class_1': 0.3479991733557539, 'weight_class_2': 0.39490565485163337}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:09,878] Trial 2228 finished with value: 0.9479653871707227 and parameters: {'weight_class_0': 0.0635876824214797, 'weight_class_1': 0.357360595955187, 'weight_class_2': 0.4013207789564869}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:09,911] Trial 2229 finished with value: 0.9315404668461854 and parameters: {'weight_class_0': 0.14944704677964965, 'weight_class_1': 0.3426591657828668, 'weight_class_2': 0.3920255157559428}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:09,957] Trial 2230 finished with value: 0.9482136435589115 and parameters: {'weight_class_0': 0.061191773779214004, 'weight_class_1': 0.35757131429799427, 'weight_class_2': 0.4207391675795529}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  75%|████████████████████████████████████████████████████████████████████████████████████████████████▉                                 | 2237/3000 [00:55<00:24, 30.92it/s]

[I 2026-07-05 15:26:10,012] Trial 2231 finished with value: 0.948258938897327 and parameters: {'weight_class_0': 0.06160382109426004, 'weight_class_1': 0.38657396788968684, 'weight_class_2': 0.4094655537981268}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:10,062] Trial 2232 finished with value: 0.949617785802214 and parameters: {'weight_class_0': 0.04055332628283056, 'weight_class_1': 0.5224434553677484, 'weight_class_2': 0.40728957994190845}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:10,105] Trial 2233 finished with value: 0.9496909019125609 and parameters: {'weight_class_0': 0.031887698337639644, 'weight_class_1': 0.5266544822374416, 'weight_class_2': 0.40765748709857397}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:10,111] Trial 2235 finished with value: 0.9496673301889823 and parameters: {'weight_class_0': 0.03206709997404006, 'weight_class_1': 0.5245796191982607, 'weight_class_2': 0.4180151646639274}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:10,123] Trial 2234 finished with value: 0.9489882432609943 and parameters: {'weight_class_0': 0.020202296877377544, 'weight_class_1': 0.5258902446213329, 'weight_class_2': 0.4000526275073637}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:10,172] Trial 2236 finished with value: 0.9490229852892466 and parameters: {'weight_class_0': 0.02004453464663078, 'weight_class_1': 0.36650329674741355, 'weight_class_2': 0.4021721012841049}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:10,204] Trial 2237 finished with value: 0.9482073049407527 and parameters: {'weight_class_0': 0.03373773107094375, 'weight_class_1': 0.7660703218220447, 'weight_class_2': 0.9870719825059864}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  75%|█████████████████████████████████████████████████████████████████████████████████████████████████▏                                | 2244/3000 [00:55<00:23, 32.18it/s]

[I 2026-07-05 15:26:10,242] Trial 2238 finished with value: 0.9492626109165191 and parameters: {'weight_class_0': 0.09504326217560674, 'weight_class_1': 0.7712934835157546, 'weight_class_2': 1.1059142701926385}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:10,248] Trial 2239 finished with value: 0.9482663323964929 and parameters: {'weight_class_0': 0.03267938869358643, 'weight_class_1': 0.7784036585440118, 'weight_class_2': 0.9591656690449913}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:10,291] Trial 2240 finished with value: 0.9483106370330914 and parameters: {'weight_class_0': 0.019877439585303868, 'weight_class_1': 0.7857533328532077, 'weight_class_2': 0.4014323940861827}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:10,315] Trial 2242 finished with value: 0.9487525667280772 and parameters: {'weight_class_0': 0.03224804235538709, 'weight_class_1': 0.7864435971651877, 'weight_class_2': 0.2058466315909916}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:10,338] Trial 2243 finished with value: 0.9467245358566863 and parameters: {'weight_class_0': 0.02046501600722662, 'weight_class_1': 0.5115130319805044, 'weight_class_2': 1.0710638690858083}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:10,363] Trial 2241 finished with value: 0.9477189626135739 and parameters: {'weight_class_0': 0.10542530970296089, 'weight_class_1': 0.5082622817242377, 'weight_class_2': 1.0819579416589444}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:10,434] Trial 2244 finished with value: 0.949101588712065 and parameters: {'weight_class_0': 0.10287587934080407, 'weight_class_1': 0.7611477013654383, 'weight_class_2': 1.0326106815634686}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  75%|█████████████████████████████████████████████████████████████████████████████████████████████████▌                                | 2252/3000 [00:56<00:23, 32.12it/s]

[I 2026-07-05 15:26:10,460] Trial 2246 finished with value: 0.9492945763211097 and parameters: {'weight_class_0': 0.0980079713768725, 'weight_class_1': 0.7889815385060995, 'weight_class_2': 0.9934674566404277}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:10,471] Trial 2247 finished with value: 0.9493789604860622 and parameters: {'weight_class_0': 0.03260139232978155, 'weight_class_1': 0.7553904928248879, 'weight_class_2': 0.272797885127809}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:10,487] Trial 2245 finished with value: 0.9489818219495504 and parameters: {'weight_class_0': 0.11283479229610978, 'weight_class_1': 0.7822910752115155, 'weight_class_2': 1.114187311709335}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:10,519] Trial 2248 finished with value: 0.9491774197982918 and parameters: {'weight_class_0': 0.11020813119617622, 'weight_class_1': 0.8023930981970531, 'weight_class_2': 1.0000477315603444}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:10,588] Trial 2250 finished with value: 0.9406116393717769 and parameters: {'weight_class_0': 0.10635139187152699, 'weight_class_1': 0.8372182992049693, 'weight_class_2': 0.26513326233007156}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:10,594] Trial 2251 finished with value: 0.9456042982761019 and parameters: {'weight_class_0': 0.02500536110448932, 'weight_class_1': 1.8648777138046264, 'weight_class_2': 0.24515453055372544}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:10,596] Trial 2249 finished with value: 0.9492645952434674 and parameters: {'weight_class_0': 0.031707276744453186, 'weight_class_1': 0.4497496023552827, 'weight_class_2': 0.23195954410290195}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:10,665] Trial 2252 finished with value: 0.948826836353851 and parameters: {'weight_class_0': 0.03942879320885688, 'weight_class_1': 0.42485663728273715, 'weight_class_2': 0.2448004307736345}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  75%|█████████████████████████████████████████████████████████████████████████████████████████████████▊                                | 2258/3000 [00:56<00:24, 30.72it/s]

[I 2026-07-05 15:26:10,688] Trial 2253 finished with value: 0.9461435313656882 and parameters: {'weight_class_0': 0.024929879184189326, 'weight_class_1': 1.7558246697897448, 'weight_class_2': 0.262792908122251}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:10,700] Trial 2254 finished with value: 0.949423409252755 and parameters: {'weight_class_0': 0.02542634660620992, 'weight_class_1': 0.6486180310443432, 'weight_class_2': 0.23043235456031247}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:10,760] Trial 2255 finished with value: 0.9465061657925231 and parameters: {'weight_class_0': 0.02536962227786483, 'weight_class_1': 1.7100512080198864, 'weight_class_2': 0.24501230952738365}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:10,791] Trial 2256 finished with value: 0.9459157470973115 and parameters: {'weight_class_0': 0.026407394974563604, 'weight_class_1': 1.8741900005397354, 'weight_class_2': 0.2312579733454097}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:10,857] Trial 2257 finished with value: 0.9458764302805198 and parameters: {'weight_class_0': 0.026393688696373454, 'weight_class_1': 1.8620505002565737, 'weight_class_2': 0.22011142610426512}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:10,859] Trial 2258 finished with value: 0.9486963143796464 and parameters: {'weight_class_0': 0.024275071054914586, 'weight_class_1': 0.9753402472545961, 'weight_class_2': 0.24459657979816152}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  76%|██████████████████████████████████████████████████████████████████████████████████████████████████▏                               | 2266/3000 [00:56<00:22, 33.02it/s]

[I 2026-07-05 15:26:10,877] Trial 2259 finished with value: 0.9490337037367831 and parameters: {'weight_class_0': 0.024606286303458527, 'weight_class_1': 0.43494875340305916, 'weight_class_2': 0.4896440612657539}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:10,891] Trial 2260 finished with value: 0.9496772612985837 and parameters: {'weight_class_0': 0.03923845441172713, 'weight_class_1': 0.6221367381165368, 'weight_class_2': 0.5071671234536101}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:10,959] Trial 2261 finished with value: 0.9496708623872889 and parameters: {'weight_class_0': 0.0394828351138517, 'weight_class_1': 0.630434834971812, 'weight_class_2': 0.5234076147408949}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:10,976] Trial 2263 finished with value: 0.9485829771532398 and parameters: {'weight_class_0': 0.02689404068542175, 'weight_class_1': 1.0000184973317214, 'weight_class_2': 0.5052437514644806}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:10,983] Trial 2262 finished with value: 0.9489983045116385 and parameters: {'weight_class_0': 0.025297078320984403, 'weight_class_1': 0.6212526063216263, 'weight_class_2': 0.49647736189623765}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:11,034] Trial 2264 finished with value: 0.9494912376081134 and parameters: {'weight_class_0': 0.03914636753950686, 'weight_class_1': 1.0280028256968299, 'weight_class_2': 0.5234394866923843}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:11,064] Trial 2265 finished with value: 0.8995343473820364 and parameters: {'weight_class_0': 0.4784920317873462, 'weight_class_1': 0.9624144143712287, 'weight_class_2': 0.5058115523966854}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:11,093] Trial 2266 finished with value: 0.8200558223855227 and parameters: {'weight_class_0': 6.395057312096457, 'weight_class_1': 0.99950764094601, 'weight_class_2': 0.5197983611598422}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  76%|██████████████████████████████████████████████████████████████████████████████████████████████████▍                               | 2273/3000 [00:56<00:24, 30.25it/s]

[I 2026-07-05 15:26:11,139] Trial 2267 finished with value: 0.9496755816268788 and parameters: {'weight_class_0': 0.04028388818136912, 'weight_class_1': 0.6043073079594035, 'weight_class_2': 0.5063836710536167}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:11,168] Trial 2268 finished with value: 0.949629086442949 and parameters: {'weight_class_0': 0.040545587676888706, 'weight_class_1': 0.9756808827329174, 'weight_class_2': 0.5001730315151591}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:11,245] Trial 2269 finished with value: 0.9496649698739804 and parameters: {'weight_class_0': 0.03941421149575024, 'weight_class_1': 0.6506484102490147, 'weight_class_2': 0.5103354805938638}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:11,249] Trial 2270 finished with value: 0.9495375371408331 and parameters: {'weight_class_0': 0.0402519079535006, 'weight_class_1': 1.0209068176819913, 'weight_class_2': 0.5163973837698577}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:11,258] Trial 2271 finished with value: 0.9491284036831097 and parameters: {'weight_class_0': 0.04007749526982714, 'weight_class_1': 1.0281167500564519, 'weight_class_2': 0.733260074515366}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:11,270] Trial 2272 finished with value: 0.9487680452608339 and parameters: {'weight_class_0': 0.05200888507679459, 'weight_class_1': 0.5473727587398757, 'weight_class_2': 0.3141875265486645}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:11,364] Trial 2273 finished with value: 0.9475061899555252 and parameters: {'weight_class_0': 0.05293619998201759, 'weight_class_1': 0.5411916407244458, 'weight_class_2': 1.5095867110225278}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  76%|██████████████████████████████████████████████████████████████████████████████████████████████████▊                               | 2280/3000 [00:57<00:22, 32.08it/s]

[I 2026-07-05 15:26:11,372] Trial 2274 finished with value: 0.9485737915460802 and parameters: {'weight_class_0': 0.053101022813814514, 'weight_class_1': 0.5177194761466689, 'weight_class_2': 0.30484563965810585}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:11,381] Trial 2275 finished with value: 0.9486314984913714 and parameters: {'weight_class_0': 0.05470608770391078, 'weight_class_1': 0.5247234539112774, 'weight_class_2': 0.3165766451433217}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:11,394] Trial 2276 finished with value: 0.9491917424590121 and parameters: {'weight_class_0': 0.05098780728001332, 'weight_class_1': 0.5695476228279878, 'weight_class_2': 0.7524515857112088}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:11,450] Trial 2277 finished with value: 0.949102024922838 and parameters: {'weight_class_0': 0.05167670896267711, 'weight_class_1': 0.5291903877576514, 'weight_class_2': 0.7693075372434494}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:11,461] Trial 2278 finished with value: 0.947387200913877 and parameters: {'weight_class_0': 0.05352587039242511, 'weight_class_1': 0.5339881549546414, 'weight_class_2': 1.5902301189746582}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:11,496] Trial 2279 finished with value: 0.9491830789893557 and parameters: {'weight_class_0': 0.05338359362997106, 'weight_class_1': 0.5238564111264138, 'weight_class_2': 0.7431546075461896}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:11,514] Trial 2280 finished with value: 0.9491887042892545 and parameters: {'weight_class_0': 0.05441739273304273, 'weight_class_1': 0.5313574476236016, 'weight_class_2': 0.7573246827672179}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  76%|███████████████████████████████████████████████████████████████████████████████████████████████████                               | 2287/3000 [00:57<00:21, 32.54it/s]

[I 2026-07-05 15:26:11,573] Trial 2281 finished with value: 0.9490538038558061 and parameters: {'weight_class_0': 0.052486026029326546, 'weight_class_1': 0.45748636525498837, 'weight_class_2': 0.7198939704595768}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:11,614] Trial 2282 finished with value: 0.9490470615169891 and parameters: {'weight_class_0': 0.05291993210001779, 'weight_class_1': 0.43460544679594015, 'weight_class_2': 0.6867273594785097}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:11,622] Trial 2283 finished with value: 0.949184182474016 and parameters: {'weight_class_0': 0.05458338030881605, 'weight_class_1': 0.4678323526218995, 'weight_class_2': 0.7162599336790889}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:11,662] Trial 2284 finished with value: 0.9484103912808446 and parameters: {'weight_class_0': 0.0542895668422322, 'weight_class_1': 0.4256449191875466, 'weight_class_2': 0.3102551559282992}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:11,718] Trial 2286 finished with value: 0.9486283729315296 and parameters: {'weight_class_0': 0.031782081896903104, 'weight_class_1': 0.4126457031259188, 'weight_class_2': 0.6443793367951756}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:11,724] Trial 2285 finished with value: 0.9485375086905715 and parameters: {'weight_class_0': 0.03260028921513429, 'weight_class_1': 0.42495049223894127, 'weight_class_2': 0.6752350884025828}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:11,745] Trial 2287 finished with value: 0.948530151388045 and parameters: {'weight_class_0': 0.031195481935608838, 'weight_class_1': 0.45119899995758456, 'weight_class_2': 0.698745795821861}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  76%|███████████████████████████████████████████████████████████████████████████████████████████████████▍                              | 2294/3000 [00:57<00:23, 30.64it/s]

[I 2026-07-05 15:26:11,809] Trial 2288 finished with value: 0.9487221383726752 and parameters: {'weight_class_0': 0.031817884570737066, 'weight_class_1': 0.43686250958437445, 'weight_class_2': 0.6460873488109564}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:11,850] Trial 2289 finished with value: 0.9496802441871702 and parameters: {'weight_class_0': 0.03105556066411731, 'weight_class_1': 0.3981789270140659, 'weight_class_2': 0.3804672273355595}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:11,859] Trial 2290 finished with value: 0.9497047776711289 and parameters: {'weight_class_0': 0.033415024091028145, 'weight_class_1': 0.4329602346168836, 'weight_class_2': 0.35896130129661546}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:11,893] Trial 2291 finished with value: 0.9496776773114194 and parameters: {'weight_class_0': 0.0314588651318106, 'weight_class_1': 0.40125318972315066, 'weight_class_2': 0.37988266228017076}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:11,940] Trial 2292 finished with value: 0.9497149007592545 and parameters: {'weight_class_0': 0.032573887753710486, 'weight_class_1': 0.4139332358315595, 'weight_class_2': 0.3851306740850696}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:11,983] Trial 2293 finished with value: 0.9496120823476324 and parameters: {'weight_class_0': 0.03187405935183076, 'weight_class_1': 0.6894382820025926, 'weight_class_2': 0.3319617500541038}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:11,997] Trial 2294 finished with value: 0.9497388085726971 and parameters: {'weight_class_0': 0.03248076423342681, 'weight_class_1': 0.7195758395579519, 'weight_class_2': 0.38769535485961915}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:12,003] Trial 2295 finished with value: 0.9497129366110232 and parameters: {'weight_class_0': 0.031244943856718697, 'weight_class_1': 0.7161100770027886, 'weight_class_2': 0.36920837798372586}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:12,059] Trial 2296 finished with value: 0.9497153471469577 and parameters: {'weight_class_0': 0.03138996230898182, 'weight_class_1': 0.6493415495121744, 'weight_class_2': 0.3812840486649608}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:12,093] Trial 2297 finished with value: 0.9497727864058815 and parameters: {'weight_class_0': 0.031731725679745734, 'weight_class_1': 0.714072033421933, 'weight_class_2': 0.35787374177027587}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:12,123] Trial 2298 finished with value: 0.9497491607220608 and parameters: {'weight_class_0': 0.03218322103927986, 'weight_class_1': 0.6635473355834574, 'weight_class_2': 0.3810378785641945}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:12,147] Trial 2299 finished with value: 0.947182403832897 and parameters: {'weight_class_0': 0.08457499705301047, 'weight_class_1': 0.6762373810066618, 'weight_class_2': 0.363835455978589}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:12,162] Trial 2300 finished with value: 0.9496796252626645 and parameters: {'weight_class_0': 0.03474150994795256, 'weight_class_1': 0.6938040986858013, 'weight_class_2': 0.3474712564775753}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:12,237] Trial 2302 finished with value: 0.948731141334656 and parameters: {'weight_class_0': 0.019946207101487867, 'weight_class_1': 0.7044283054496847, 'weight_class_2': 0.3669295988492727}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:12,255] Trial 2301 finished with value: 0.9487677057839982 and parameters: {'weight_class_0': 0.019919181297724412, 'weight_class_1': 0.6966227941596211, 'weight_class_2': 0.3652116586169788}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:12,296] Trial 2304 finished with value: 0.948902569422377 and parameters: {'weight_class_0': 0.01949764503311913, 'weight_class_1': 0.6941076723022737, 'weight_class_2': 0.3053211668934276}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:12,306] Trial 2303 finished with value: 0.9475452906158389 and parameters: {'weight_class_0': 0.0807172279727019, 'weight_class_1': 0.7234525973394629, 'weight_class_2': 0.36552810849626555}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:12,375] Trial 2306 finished with value: 0.9493567275278433 and parameters: {'weight_class_0': 0.04073232161047409, 'weight_class_1': 0.6405982209849929, 'weight_class_2': 0.30594600508748765}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:12,388] Trial 2305 finished with value: 0.9475136475461134 and parameters: {'weight_class_0': 0.06552883944653529, 'weight_class_1': 1.4285220922566222, 'weight_class_2': 0.298892389139135}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:12,390] Trial 2307 finished with value: 0.9458890282762703 and parameters: {'weight_class_0': 0.020345062209888895, 'weight_class_1': 1.467695788724239, 'weight_class_2': 0.2929531283219787}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:12,446] Trial 2308 finished with value: 0.945626169417244 and parameters: {'weight_class_0': 0.08614695513803082, 'weight_class_1': 1.442366487904841, 'weight_class_2': 0.29657441356035913}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  77%|████████████████████████████████████████████████████████████████████████████████████████████████████▎                             | 2315/3000 [00:58<00:20, 32.74it/s]

[I 2026-07-05 15:26:12,470] Trial 2311 finished with value: 0.9440082592460759 and parameters: {'weight_class_0': 0.01898943934000205, 'weight_class_1': 1.5383069585747846, 'weight_class_2': 0.4605002693117155}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:12,479] Trial 2309 finished with value: 0.9483863954389221 and parameters: {'weight_class_0': 0.020075599785475497, 'weight_class_1': 0.873422147389027, 'weight_class_2': 0.3043945179653544}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:12,490] Trial 2310 finished with value: 0.945571583171764 and parameters: {'weight_class_0': 0.01969901795338366, 'weight_class_1': 1.471165043115492, 'weight_class_2': 0.3005148331827464}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:12,526] Trial 2312 finished with value: 0.9451127748368141 and parameters: {'weight_class_0': 0.020264136150341908, 'weight_class_1': 1.4967470817888238, 'weight_class_2': 0.4553777586344075}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:12,592] Trial 2314 finished with value: 0.9495891661631678 and parameters: {'weight_class_0': 0.06488487693614892, 'weight_class_1': 1.4060333284314372, 'weight_class_2': 0.5986882403071286}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:12,619] Trial 2313 finished with value: 0.9496127517160824 and parameters: {'weight_class_0': 0.06665549113889128, 'weight_class_1': 1.3995317189229424, 'weight_class_2': 0.6064245501067619}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:12,665] Trial 2315 finished with value: 0.948946061277551 and parameters: {'weight_class_0': 0.04525578335442946, 'weight_class_1': 0.8670964198399226, 'weight_class_2': 0.29191226772061}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  77%|████████████████████████████████████████████████████████████████████████████████████████████████████▋                             | 2323/3000 [00:58<00:21, 31.53it/s]

[I 2026-07-05 15:26:12,688] Trial 2316 finished with value: 0.9491175939450671 and parameters: {'weight_class_0': 0.06363495390688081, 'weight_class_1': 0.8742125896156028, 'weight_class_2': 0.4457616865002555}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:12,729] Trial 2317 finished with value: 0.9497272323196162 and parameters: {'weight_class_0': 0.04289619022365269, 'weight_class_1': 0.870683867061963, 'weight_class_2': 0.4589531558214281}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:12,750] Trial 2318 finished with value: 0.9491471942340682 and parameters: {'weight_class_0': 0.06420152887965898, 'weight_class_1': 0.8387025792412462, 'weight_class_2': 0.4620557606195402}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:12,777] Trial 2319 finished with value: 0.9496605041415407 and parameters: {'weight_class_0': 0.06382795755073895, 'weight_class_1': 0.877533503103756, 'weight_class_2': 0.5737868881002324}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:12,790] Trial 2320 finished with value: 0.9496133031849979 and parameters: {'weight_class_0': 0.04180503657160852, 'weight_class_1': 0.8764008360207014, 'weight_class_2': 0.544385614364444}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:12,829] Trial 2321 finished with value: 0.949368408168158 and parameters: {'weight_class_0': 0.0368100657948018, 'weight_class_1': 0.855708248734566, 'weight_class_2': 0.5895560626345147}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:12,908] Trial 2323 finished with value: 0.9493751674665543 and parameters: {'weight_class_0': 0.03793213153885629, 'weight_class_1': 0.8812691444907956, 'weight_class_2': 0.5781333377512675}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  78%|████████████████████████████████████████████████████████████████████████████████████████████████████▉                             | 2329/3000 [00:58<00:21, 30.63it/s]

[I 2026-07-05 15:26:12,924] Trial 2322 finished with value: 0.9495243462325115 and parameters: {'weight_class_0': 0.06560925229330573, 'weight_class_1': 0.8874010417444735, 'weight_class_2': 0.5684089099176481}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:12,974] Trial 2326 finished with value: 0.9497868243743112 and parameters: {'weight_class_0': 0.040387172372703124, 'weight_class_1': 0.8567694644116961, 'weight_class_2': 0.4613166117674859}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:12,975] Trial 2324 finished with value: 0.9496328865332163 and parameters: {'weight_class_0': 0.04518976461751053, 'weight_class_1': 0.8924962879185924, 'weight_class_2': 0.6025319178197616}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:12,986] Trial 2325 finished with value: 0.9488356740490044 and parameters: {'weight_class_0': 0.040193034471681925, 'weight_class_1': 0.8742884903772156, 'weight_class_2': 0.8754983536342541}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:13,047] Trial 2327 finished with value: 0.9477768809872908 and parameters: {'weight_class_0': 0.04085041842979883, 'weight_class_1': 0.3335416741968092, 'weight_class_2': 0.900755416308139}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:13,071] Trial 2328 finished with value: 0.9057969548854649 and parameters: {'weight_class_0': 0.041335446903678075, 'weight_class_1': 7.959348869132813, 'weight_class_2': 0.8407213840170927}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:13,102] Trial 2329 finished with value: 0.9488190672004913 and parameters: {'weight_class_0': 0.04553525792352548, 'weight_class_1': 0.5915080660480844, 'weight_class_2': 0.8774205803020432}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  78%|█████████████████████████████████████████████████████████████████████████████████████████████████████▏                            | 2336/3000 [00:58<00:20, 32.56it/s]

[I 2026-07-05 15:26:13,153] Trial 2331 finished with value: 0.9478829074753108 and parameters: {'weight_class_0': 0.039718549054909354, 'weight_class_1': 0.3370895741736225, 'weight_class_2': 0.8824523321332398}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:13,170] Trial 2330 finished with value: 0.9477698172692288 and parameters: {'weight_class_0': 0.039731824083628166, 'weight_class_1': 0.3094046772000603, 'weight_class_2': 0.8604490587358682}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:13,179] Trial 2332 finished with value: 0.9480557658240252 and parameters: {'weight_class_0': 0.04322203234168809, 'weight_class_1': 0.34054886166937703, 'weight_class_2': 0.854020277813375}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:13,199] Trial 2333 finished with value: 0.948646967613584 and parameters: {'weight_class_0': 0.03990831259670723, 'weight_class_1': 0.5533912086888697, 'weight_class_2': 0.8417321284448553}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:13,249] Trial 2334 finished with value: 0.9480463824976217 and parameters: {'weight_class_0': 0.04253508343328127, 'weight_class_1': 0.3242347999701843, 'weight_class_2': 0.8383732419000556}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:13,298] Trial 2335 finished with value: 0.9479102072482769 and parameters: {'weight_class_0': 0.026305885237888058, 'weight_class_1': 0.5723154043646406, 'weight_class_2': 0.8769122274954452}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:13,346] Trial 2336 finished with value: 0.9492725606734626 and parameters: {'weight_class_0': 0.027684772981396804, 'weight_class_1': 0.3341022544753624, 'weight_class_2': 0.20697473876327735}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:13,363] Trial 2337 finished with value: 0.9481349658601551 and parameters: {'weight_class_0': 0.028152443583007822, 'weight_class_1': 0.5659357594690266, 'weight_class_2': 0.8529457125231897}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:13,395] Trial 2339 finished with value: 0.9494531900142418 and parameters: {'weight_class_0': 0.024981398845465422, 'weight_class_1': 0.32798725464540457, 'weight_class_2': 0.20722828766538468}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:13,422] Trial 2338 finished with value: 0.8474671828512986 and parameters: {'weight_class_0': 0.02665580860728179, 'weight_class_1': 2.4659226102059604, 'weight_class_2': 9.620956125322458}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:13,435] Trial 2340 finished with value: 0.9493530225035647 and parameters: {'weight_class_0': 0.02469690952867705, 'weight_class_1': 0.5526306547816909, 'weight_class_2': 0.42522884352343665}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:13,484] Trial 2341 finished with value: 0.9494541574805656 and parameters: {'weight_class_0': 0.027056207379703993, 'weight_class_1': 0.5633985476528872, 'weight_class_2': 0.4323576451257046}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:13,513] Trial 2342 finished with value: 0.949342956867906 and parameters: {'weight_class_0': 0.02365836367268492, 'weight_class_1': 0.5769629189583726, 'weight_class_2': 0.19731853745036523}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:13,531] Trial 2343 finished with value: 0.8273292105621013 and parameters: {'weight_class_0': 0.02621997327873739, 'weight_class_1': 0.0010249389584495398, 'weight_class_2': 0.44485065307705673}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  78%|█████████████████████████████████████████████████████████████████████████████████████████████████████▊                            | 2350/3000 [00:59<00:21, 30.34it/s]

[I 2026-07-05 15:26:13,569] Trial 2344 finished with value: 0.9492416597099682 and parameters: {'weight_class_0': 0.024864203067352493, 'weight_class_1': 0.5746324715203187, 'weight_class_2': 0.4447500648353914}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:13,599] Trial 2345 finished with value: 0.9492399670974586 and parameters: {'weight_class_0': 0.02602047834413031, 'weight_class_1': 0.5745599701786401, 'weight_class_2': 0.19496914472465454}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:13,670] Trial 2346 finished with value: 0.948309149517045 and parameters: {'weight_class_0': 0.02545923082983086, 'weight_class_1': 1.1125283526503877, 'weight_class_2': 0.43358163627530544}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:13,694] Trial 2347 finished with value: 0.9492345153643198 and parameters: {'weight_class_0': 0.026667336953633006, 'weight_class_1': 0.5819436766138724, 'weight_class_2': 0.20123037069303829}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:13,722] Trial 2348 finished with value: 0.9482569598194468 and parameters: {'weight_class_0': 0.025892116696316077, 'weight_class_1': 1.0784018406882285, 'weight_class_2': 0.19731566267569903}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:13,741] Trial 2349 finished with value: 0.9485735079203863 and parameters: {'weight_class_0': 0.08090805540611051, 'weight_class_1': 1.0773876439879546, 'weight_class_2': 0.4564477770905141}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:13,793] Trial 2350 finished with value: 0.9496062363902843 and parameters: {'weight_class_0': 0.04845635341791668, 'weight_class_1': 1.0979179470923324, 'weight_class_2': 0.4538860323706471}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:13,813] Trial 2352 finished with value: 0.9489011675468806 and parameters: {'weight_class_0': 0.0782996330421759, 'weight_class_1': 1.061517468399857, 'weight_class_2': 0.4898417758495052}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:13,847] Trial 2351 finished with value: 0.9485465064808721 and parameters: {'weight_class_0': 0.08010365801333241, 'weight_class_1': 1.0763988570048924, 'weight_class_2': 0.4531113617286075}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:13,871] Trial 2353 finished with value: 0.9496365270757597 and parameters: {'weight_class_0': 0.050914534501148384, 'weight_class_1': 1.1312374881970177, 'weight_class_2': 0.47591072047051464}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:13,895] Trial 2354 finished with value: 0.9489033317328621 and parameters: {'weight_class_0': 0.08495755154110239, 'weight_class_1': 1.1413870952793597, 'weight_class_2': 0.5305602351953163}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:13,907] Trial 2355 finished with value: 0.9496559519741714 and parameters: {'weight_class_0': 0.04951315843652306, 'weight_class_1': 1.0857470791175554, 'weight_class_2': 0.505372807966549}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:13,959] Trial 2356 finished with value: 0.9493087172338274 and parameters: {'weight_class_0': 0.07972877078379798, 'weight_class_1': 1.05816330314658, 'weight_class_2': 0.5891656831339469}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:13,987] Trial 2357 finished with value: 0.9480946056249735 and parameters: {'weight_class_0': 0.08057135882555408, 'weight_class_1': 0.47077547473034065, 'weight_class_2': 0.5258396354553165}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  79%|██████████████████████████████████████████████████████████████████████████████████████████████████████▍                           | 2363/3000 [00:59<00:21, 29.31it/s]

[I 2026-07-05 15:26:14,019] Trial 2358 finished with value: 0.9492891328653562 and parameters: {'weight_class_0': 0.08288220635949163, 'weight_class_1': 1.0897137334334361, 'weight_class_2': 0.6111167623331388}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:14,067] Trial 2359 finished with value: 0.9489373387179291 and parameters: {'weight_class_0': 0.08550660884394032, 'weight_class_1': 1.0651305297465536, 'weight_class_2': 0.5335584125427575}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:14,087] Trial 2360 finished with value: 0.949653261809512 and parameters: {'weight_class_0': 0.0494132830601096, 'weight_class_1': 0.6999182741690713, 'weight_class_2': 0.6220430902315952}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:14,180] Trial 2362 finished with value: 0.9492757872551825 and parameters: {'weight_class_0': 0.03505466202751856, 'weight_class_1': 0.489826434169275, 'weight_class_2': 0.5890520088763176}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:14,184] Trial 2361 finished with value: 0.9493499205914625 and parameters: {'weight_class_0': 0.03438815437212673, 'weight_class_1': 0.47221309205138073, 'weight_class_2': 0.2616109765822371}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:14,205] Trial 2363 finished with value: 0.9491256107764289 and parameters: {'weight_class_0': 0.03547707825740716, 'weight_class_1': 0.4575075972336544, 'weight_class_2': 0.6029780113470395}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:14,271] Trial 2364 finished with value: 0.9491639581704333 and parameters: {'weight_class_0': 0.035876509517416715, 'weight_class_1': 0.6941101016469592, 'weight_class_2': 0.2606275891782468}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:14,297] Trial 2365 finished with value: 0.9492756904542169 and parameters: {'weight_class_0': 0.03473562100267853, 'weight_class_1': 0.6833155720073004, 'weight_class_2': 0.25603772921273804}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:14,303] Trial 2366 finished with value: 0.9491796264404678 and parameters: {'weight_class_0': 0.036564458620174434, 'weight_class_1': 0.47637064505181204, 'weight_class_2': 0.2648613646188059}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:14,338] Trial 2367 finished with value: 0.949301749778675 and parameters: {'weight_class_0': 0.034997693818539066, 'weight_class_1': 0.46321844106222587, 'weight_class_2': 0.26125606232402915}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:14,347] Trial 2369 finished with value: 0.9492582493749587 and parameters: {'weight_class_0': 0.03690124008256716, 'weight_class_1': 0.4907210081800605, 'weight_class_2': 0.27084107891948705}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:14,350] Trial 2368 finished with value: 0.949109846897963 and parameters: {'weight_class_0': 0.03595010882899538, 'weight_class_1': 0.6717084368739239, 'weight_class_2': 0.2584249156560929}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:14,414] Trial 2370 finished with value: 0.9493009624407397 and parameters: {'weight_class_0': 0.03556098351377706, 'weight_class_1': 0.4834447425298454, 'weight_class_2': 0.26385717689538124}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:14,417] Trial 2371 finished with value: 0.9478625833128654 and parameters: {'weight_class_0': 0.06179016231509918, 'weight_class_1': 0.47098469275210786, 'weight_class_2': 0.30451623407886874}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  79%|██████████████████████████████████████████████████████████████████████████████████████████████████████▉                           | 2376/3000 [01:00<00:19, 31.24it/s]

[I 2026-07-05 15:26:14,455] Trial 2372 finished with value: 0.9491379055745671 and parameters: {'weight_class_0': 0.03502569120109077, 'weight_class_1': 0.4697847783918111, 'weight_class_2': 0.2515975572282582}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:14,506] Trial 2373 finished with value: 0.9491261906453983 and parameters: {'weight_class_0': 0.037353008927001, 'weight_class_1': 0.6627544133469075, 'weight_class_2': 0.26811603743791035}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:14,566] Trial 2374 finished with value: 0.949150645867025 and parameters: {'weight_class_0': 0.03611068788894212, 'weight_class_1': 0.7101837302220755, 'weight_class_2': 0.26176153700541566}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:14,579] Trial 2375 finished with value: 0.9485058420411944 and parameters: {'weight_class_0': 0.06213437289703722, 'weight_class_1': 0.7142338113048008, 'weight_class_2': 1.2526486028725494}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:14,623] Trial 2376 finished with value: 0.9483003639538756 and parameters: {'weight_class_0': 0.06091899514352959, 'weight_class_1': 0.6773976695922745, 'weight_class_2': 1.2987624836647302}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████████▎                          | 2385/3000 [01:00<00:18, 32.90it/s]

[I 2026-07-05 15:26:14,694] Trial 2378 finished with value: 0.9489038838311236 and parameters: {'weight_class_0': 0.057822196229019754, 'weight_class_1': 0.7557151677594067, 'weight_class_2': 0.3615906607996268}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:14,698] Trial 2377 finished with value: 0.948308300911599 and parameters: {'weight_class_0': 0.06306814665979878, 'weight_class_1': 0.6705539863807736, 'weight_class_2': 0.3289115982682498}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:14,714] Trial 2380 finished with value: 0.9489178568318287 and parameters: {'weight_class_0': 0.0597201645260414, 'weight_class_1': 0.732371580983149, 'weight_class_2': 0.37125383735564577}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:14,741] Trial 2379 finished with value: 0.9486329143472741 and parameters: {'weight_class_0': 0.06173498726123243, 'weight_class_1': 0.6352086969422621, 'weight_class_2': 0.35801337074705786}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:14,764] Trial 2381 finished with value: 0.9488462403603467 and parameters: {'weight_class_0': 0.06246350620898661, 'weight_class_1': 0.7983833125990971, 'weight_class_2': 0.3817416293058009}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:14,801] Trial 2384 finished with value: 0.9487378510438614 and parameters: {'weight_class_0': 0.06143981313719205, 'weight_class_1': 0.6493517656878678, 'weight_class_2': 0.36842426986833293}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:14,803] Trial 2383 finished with value: 0.9036619946224086 and parameters: {'weight_class_0': 0.3339166584641521, 'weight_class_1': 0.7420723414669218, 'weight_class_2': 0.37554716167331076}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:14,810] Trial 2382 finished with value: 0.9487819055863449 and parameters: {'weight_class_0': 0.061045963527439656, 'weight_class_1': 0.7258861690241613, 'weight_class_2': 0.36221070624524504}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:14,859] Trial 2385 finished with value: 0.9486644916650656 and parameters: {'weight_class_0': 0.06021902850571631, 'weight_class_1': 0.7818465271386404, 'weight_class_2': 0.34794297273962}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████████▌                          | 2391/3000 [01:00<00:19, 31.44it/s]

[I 2026-07-05 15:26:14,934] Trial 2387 finished with value: 0.9494086969709995 and parameters: {'weight_class_0': 0.04689126147773642, 'weight_class_1': 0.8379265815649848, 'weight_class_2': 0.36722302058573036}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:14,940] Trial 2386 finished with value: 0.9492016504919039 and parameters: {'weight_class_0': 0.04643076742438885, 'weight_class_1': 0.3796444495480913, 'weight_class_2': 0.3757133110737479}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:14,943] Trial 2388 finished with value: 0.9488388245387567 and parameters: {'weight_class_0': 0.049159517961667606, 'weight_class_1': 0.37874430346550797, 'weight_class_2': 0.3392870556242135}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:15,037] Trial 2389 finished with value: 0.9491449893650333 and parameters: {'weight_class_0': 0.04684638709205425, 'weight_class_1': 0.3654729178565929, 'weight_class_2': 0.38296341877712087}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:15,113] Trial 2390 finished with value: 0.949300589946713 and parameters: {'weight_class_0': 0.047098794669946806, 'weight_class_1': 0.3778894620425914, 'weight_class_2': 0.4103034780507707}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:15,126] Trial 2391 finished with value: 0.9492667241845089 and parameters: {'weight_class_0': 0.047856236336112586, 'weight_class_1': 0.4027101668929588, 'weight_class_2': 0.3915841612569341}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████████▉                          | 2399/3000 [01:00<00:18, 31.81it/s]

[I 2026-07-05 15:26:15,158] Trial 2392 finished with value: 0.9494099843879903 and parameters: {'weight_class_0': 0.04471659639232098, 'weight_class_1': 0.5946872938816979, 'weight_class_2': 0.6314390831511393}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:15,170] Trial 2393 finished with value: 0.9473598573649079 and parameters: {'weight_class_0': 0.016509710747335694, 'weight_class_1': 0.3993493457243095, 'weight_class_2': 0.6792222917459154}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:15,177] Trial 2394 finished with value: 0.9486409586268622 and parameters: {'weight_class_0': 0.04841371311722026, 'weight_class_1': 0.3729473593148917, 'weight_class_2': 0.7061211653588129}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:15,229] Trial 2395 finished with value: 0.9486117960905843 and parameters: {'weight_class_0': 0.043928694888274916, 'weight_class_1': 0.35245334879117085, 'weight_class_2': 0.6932946157525804}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:15,238] Trial 2396 finished with value: 0.9489257831419317 and parameters: {'weight_class_0': 0.04643290729980021, 'weight_class_1': 0.37964174239103204, 'weight_class_2': 0.6293797706907743}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:15,263] Trial 2397 finished with value: 0.9487313671352652 and parameters: {'weight_class_0': 0.04504519706186353, 'weight_class_1': 0.3608089237341471, 'weight_class_2': 0.6481570466690301}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:15,298] Trial 2398 finished with value: 0.9487983055772257 and parameters: {'weight_class_0': 0.031200759697742882, 'weight_class_1': 0.5645173952644581, 'weight_class_2': 0.691628984534048}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:15,355] Trial 2400 finished with value: 0.948722687715707 and parameters: {'weight_class_0': 0.02836245558680503, 'weight_class_1': 0.5734798719374834, 'weight_class_2': 0.6728710543411989}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  80%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                         | 2405/3000 [01:01<00:20, 29.57it/s]

[I 2026-07-05 15:26:15,360] Trial 2399 finished with value: 0.9489763578904563 and parameters: {'weight_class_0': 0.02990879614972746, 'weight_class_1': 0.6130133538896563, 'weight_class_2': 0.6084413587130721}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:15,400] Trial 2401 finished with value: 0.9487067337128493 and parameters: {'weight_class_0': 0.02931581324551952, 'weight_class_1': 0.5588537811270375, 'weight_class_2': 0.6955943450705278}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:15,465] Trial 2402 finished with value: 0.9487980051642338 and parameters: {'weight_class_0': 0.029845778111971515, 'weight_class_1': 0.564209930683132, 'weight_class_2': 0.6794798043556391}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:15,530] Trial 2404 finished with value: 0.94938470203151 and parameters: {'weight_class_0': 0.028371867361487797, 'weight_class_1': 0.5217870482197468, 'weight_class_2': 0.48010786793020244}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:15,538] Trial 2403 finished with value: 0.9493882821761908 and parameters: {'weight_class_0': 0.030222295430339958, 'weight_class_1': 0.5637319585841486, 'weight_class_2': 0.5025921265653089}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:15,546] Trial 2405 finished with value: 0.9493922633118371 and parameters: {'weight_class_0': 0.029591206690290233, 'weight_class_1': 0.5732767413141057, 'weight_class_2': 0.4937032926947368}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  80%|████████████████████████████████████████████████████████████████████████████████████████████████████████▌                         | 2413/3000 [01:01<00:18, 32.37it/s]

[I 2026-07-05 15:26:15,573] Trial 2406 finished with value: 0.9493987862475102 and parameters: {'weight_class_0': 0.0309179913247611, 'weight_class_1': 0.574730887926, 'weight_class_2': 0.5079198902037172}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:15,617] Trial 2407 finished with value: 0.949439640978415 and parameters: {'weight_class_0': 0.028908010371181937, 'weight_class_1': 0.5524829328167692, 'weight_class_2': 0.46433598678786453}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:15,652] Trial 2408 finished with value: 0.9493964996331575 and parameters: {'weight_class_0': 0.02957065920870997, 'weight_class_1': 0.5744103889458649, 'weight_class_2': 0.49423655758242824}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:15,685] Trial 2409 finished with value: 0.9486905117485459 and parameters: {'weight_class_0': 0.021900635356289184, 'weight_class_1': 0.5718478589501335, 'weight_class_2': 0.5047827450837339}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:15,689] Trial 2410 finished with value: 0.9487662953613563 and parameters: {'weight_class_0': 0.02143900856673055, 'weight_class_1': 0.5190205274226617, 'weight_class_2': 0.47479933597338225}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:15,704] Trial 2411 finished with value: 0.9493715936725905 and parameters: {'weight_class_0': 0.029513312101830773, 'weight_class_1': 0.524110553947441, 'weight_class_2': 0.5008128140584283}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:15,773] Trial 2413 finished with value: 0.9480693479562329 and parameters: {'weight_class_0': 0.02258939145882968, 'weight_class_1': 0.9183506949639706, 'weight_class_2': 0.5028231205198936}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:15,778] Trial 2412 finished with value: 0.9470214219634777 and parameters: {'weight_class_0': 0.016546703458973678, 'weight_class_1': 0.8402124429713723, 'weight_class_2': 0.4792282785328787}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  81%|████████████████████████████████████████████████████████████████████████████████████████████████████████▊                         | 2419/3000 [01:01<00:19, 29.30it/s]

[I 2026-07-05 15:26:15,812] Trial 2414 finished with value: 0.9477908546989884 and parameters: {'weight_class_0': 0.020920397108495813, 'weight_class_1': 0.9173561935917328, 'weight_class_2': 0.4968503415100757}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:15,880] Trial 2415 finished with value: 0.9497355342791215 and parameters: {'weight_class_0': 0.03894597938767803, 'weight_class_1': 0.8913752695752436, 'weight_class_2': 0.45087864059648286}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:15,938] Trial 2417 finished with value: 0.9480969598721112 and parameters: {'weight_class_0': 0.0221950548874781, 'weight_class_1': 0.9433069565826583, 'weight_class_2': 0.44731370779521795}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:15,942] Trial 2416 finished with value: 0.9484815542021692 and parameters: {'weight_class_0': 0.022922030632607695, 'weight_class_1': 0.8813466071865802, 'weight_class_2': 0.4387325376937021}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:15,952] Trial 2418 finished with value: 0.948516945747954 and parameters: {'weight_class_0': 0.022175832478576213, 'weight_class_1': 0.7862344166767611, 'weight_class_2': 0.44633834419028834}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:15,961] Trial 2419 finished with value: 0.9404334521294816 and parameters: {'weight_class_0': 0.1250076745878592, 'weight_class_1': 0.9261308006451779, 'weight_class_2': 0.309357692154879}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▏                        | 2427/3000 [01:01<00:18, 31.20it/s]

[I 2026-07-05 15:26:16,073] Trial 2421 finished with value: 0.9492232423050583 and parameters: {'weight_class_0': 0.04099396724343367, 'weight_class_1': 0.8517502531274641, 'weight_class_2': 0.3050251542441447}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:16,076] Trial 2420 finished with value: 0.9479494211194449 and parameters: {'weight_class_0': 0.017420685280747264, 'weight_class_1': 0.8386465372421623, 'weight_class_2': 0.3038608341683573}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:16,098] Trial 2422 finished with value: 0.9497021823886701 and parameters: {'weight_class_0': 0.040523670800829636, 'weight_class_1': 0.8329805857743745, 'weight_class_2': 0.4331814765285979}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:16,126] Trial 2423 finished with value: 0.9492581041092487 and parameters: {'weight_class_0': 0.03931552941386524, 'weight_class_1': 0.8355492501377976, 'weight_class_2': 0.3032162584927259}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:16,150] Trial 2424 finished with value: 0.9377292722024113 and parameters: {'weight_class_0': 0.1326120177484244, 'weight_class_1': 1.2803066262132765, 'weight_class_2': 0.293555679092421}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:16,154] Trial 2425 finished with value: 0.9377048686567635 and parameters: {'weight_class_0': 0.13437044989322638, 'weight_class_1': 0.8332519667163671, 'weight_class_2': 0.30540932167550155}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:16,211] Trial 2426 finished with value: 0.9493018563010315 and parameters: {'weight_class_0': 0.039181982095148365, 'weight_class_1': 0.8312148590145804, 'weight_class_2': 0.30602457721009774}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:16,267] Trial 2427 finished with value: 0.918929317738233 and parameters: {'weight_class_0': 0.26860079463052833, 'weight_class_1': 0.7859433710653072, 'weight_class_2': 0.4033651357767423}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▍                        | 2434/3000 [01:01<00:17, 31.78it/s]

[I 2026-07-05 15:26:16,292] Trial 2429 finished with value: 0.9495418020947349 and parameters: {'weight_class_0': 0.03955839759182317, 'weight_class_1': 0.4507817737333638, 'weight_class_2': 0.33358126102785796}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:16,296] Trial 2430 finished with value: 0.9494459548032372 and parameters: {'weight_class_0': 0.03939569211262745, 'weight_class_1': 0.7695795709777603, 'weight_class_2': 0.3167073984843021}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:16,327] Trial 2428 finished with value: 0.9496301042117907 and parameters: {'weight_class_0': 0.036142962009130246, 'weight_class_1': 0.7497585436008869, 'weight_class_2': 0.32801136313020307}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:16,395] Trial 2431 finished with value: 0.9487972200483248 and parameters: {'weight_class_0': 0.042790543182347957, 'weight_class_1': 1.2822975544284514, 'weight_class_2': 0.30893751515098417}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:16,418] Trial 2433 finished with value: 0.9492769976400742 and parameters: {'weight_class_0': 0.037395465522479646, 'weight_class_1': 0.45625725835916897, 'weight_class_2': 0.5786390537507492}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:16,444] Trial 2432 finished with value: 0.9486802099475781 and parameters: {'weight_class_0': 0.05186807427367016, 'weight_class_1': 1.2412955693263867, 'weight_class_2': 0.31803494677005745}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:16,472] Trial 2434 finished with value: 0.9483288868976142 and parameters: {'weight_class_0': 0.049666269084042244, 'weight_class_1': 0.27596622985142216, 'weight_class_2': 0.3979996192692315}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▋                        | 2440/3000 [01:02<00:17, 32.52it/s]

[I 2026-07-05 15:26:16,502] Trial 2435 finished with value: 0.9486649847327372 and parameters: {'weight_class_0': 0.05270577714674985, 'weight_class_1': 2.204983937074685, 'weight_class_2': 0.5846083573875}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:16,540] Trial 2436 finished with value: 0.9483670578401747 and parameters: {'weight_class_0': 0.05094162534877339, 'weight_class_1': 0.29083590584265484, 'weight_class_2': 0.592588425652236}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:16,597] Trial 2437 finished with value: 0.9494207302963192 and parameters: {'weight_class_0': 0.04906439188266703, 'weight_class_1': 0.45702720236461974, 'weight_class_2': 0.5932619936619725}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:16,602] Trial 2438 finished with value: 0.9491854029760575 and parameters: {'weight_class_0': 0.051851846049822625, 'weight_class_1': 1.3022268719655745, 'weight_class_2': 0.41074227560857973}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:16,669] Trial 2439 finished with value: 0.9496088274860739 and parameters: {'weight_class_0': 0.05181100039227443, 'weight_class_1': 1.2588560286018884, 'weight_class_2': 0.5647766043904136}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:16,709] Trial 2440 finished with value: 0.947756735132224 and parameters: {'weight_class_0': 0.05450895853797913, 'weight_class_1': 0.26590569005626413, 'weight_class_2': 0.5819827800550741}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████                        | 2447/3000 [01:02<00:18, 30.62it/s]

[I 2026-07-05 15:26:16,725] Trial 2441 finished with value: 0.9485368257539614 and parameters: {'weight_class_0': 0.050317422516314186, 'weight_class_1': 2.2506188469781487, 'weight_class_2': 0.5758794657898517}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:16,792] Trial 2443 finished with value: 0.949172032166152 and parameters: {'weight_class_0': 0.05425798749738516, 'weight_class_1': 0.6447736376165786, 'weight_class_2': 0.39609485551888274}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:16,793] Trial 2442 finished with value: 0.9480319919112149 and parameters: {'weight_class_0': 0.052647258279940164, 'weight_class_1': 0.2731601525873289, 'weight_class_2': 0.5695090189038813}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:16,843] Trial 2444 finished with value: 0.9497174585319197 and parameters: {'weight_class_0': 0.0520227543992292, 'weight_class_1': 0.6481345659795573, 'weight_class_2': 0.5816501623078972}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:16,857] Trial 2445 finished with value: 0.949728663801603 and parameters: {'weight_class_0': 0.05166862635895866, 'weight_class_1': 0.6624885427136475, 'weight_class_2': 0.5952387358711057}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:16,862] Trial 2446 finished with value: 0.9494864976310048 and parameters: {'weight_class_0': 0.06869614893540664, 'weight_class_1': 0.6462128824823069, 'weight_class_2': 0.5911542761006107}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:16,887] Trial 2447 finished with value: 0.9496401538284673 and parameters: {'weight_class_0': 0.06747916542970436, 'weight_class_1': 0.6471734486282218, 'weight_class_2': 0.7634719062826357}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▎                       | 2454/3000 [01:02<00:17, 31.48it/s]

[I 2026-07-05 15:26:16,899] Trial 2448 finished with value: 0.9489346411007143 and parameters: {'weight_class_0': 0.0349512457004591, 'weight_class_1': 0.6346593387115479, 'weight_class_2': 0.7320634447108416}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:16,966] Trial 2449 finished with value: 0.9495086276290428 and parameters: {'weight_class_0': 0.07362739613243655, 'weight_class_1': 0.6509210033893659, 'weight_class_2': 0.7509129372887005}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:16,987] Trial 2450 finished with value: 0.9475444418891789 and parameters: {'weight_class_0': 0.03162038495836363, 'weight_class_1': 0.6465361697706421, 'weight_class_2': 1.1870333035633516}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:17,036] Trial 2451 finished with value: 0.9495502098883408 and parameters: {'weight_class_0': 0.06995437032032423, 'weight_class_1': 0.6347863755639984, 'weight_class_2': 0.7796506009572225}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:17,070] Trial 2452 finished with value: 0.9487211063169672 and parameters: {'weight_class_0': 0.06821124309829309, 'weight_class_1': 0.6558120311154746, 'weight_class_2': 1.1942749332007145}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:17,101] Trial 2453 finished with value: 0.8268661830928323 and parameters: {'weight_class_0': 4.131315754087648, 'weight_class_1': 0.6478765532009166, 'weight_class_2': 1.1730337585986843}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:17,142] Trial 2454 finished with value: 0.9487508550246582 and parameters: {'weight_class_0': 0.03238697199383054, 'weight_class_1': 0.640965787661283, 'weight_class_2': 0.7613373286243598}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                       | 2461/3000 [01:02<00:17, 31.01it/s]

[I 2026-07-05 15:26:17,166] Trial 2455 finished with value: 0.944516096816138 and parameters: {'weight_class_0': 0.06930133386074935, 'weight_class_1': 5.643800236567424, 'weight_class_2': 1.1779648314076157}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:17,217] Trial 2456 finished with value: 0.9496257342316045 and parameters: {'weight_class_0': 0.0333553297312999, 'weight_class_1': 0.46206999577504476, 'weight_class_2': 0.42492096527553774}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:17,222] Trial 2457 finished with value: 0.937080766933826 and parameters: {'weight_class_0': 0.09521395866860445, 'weight_class_1': 0.48922128099148193, 'weight_class_2': 0.21595546759042183}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:17,258] Trial 2458 finished with value: 0.9474523658062918 and parameters: {'weight_class_0': 0.031603293661390246, 'weight_class_1': 0.47008998893076814, 'weight_class_2': 1.0872741744609344}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:17,282] Trial 2459 finished with value: 0.9475884739315777 and parameters: {'weight_class_0': 0.09946107198961482, 'weight_class_1': 0.454978999431057, 'weight_class_2': 1.121514802073856}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:17,345] Trial 2461 finished with value: 0.9490923020820285 and parameters: {'weight_class_0': 0.03184029724405406, 'weight_class_1': 0.4893068241574616, 'weight_class_2': 0.2159416229130155}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:17,354] Trial 2460 finished with value: 0.949175213051983 and parameters: {'weight_class_0': 0.032258847663114834, 'weight_class_1': 0.48500234774822243, 'weight_class_2': 0.2338103561953585}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▉                       | 2469/3000 [01:03<00:16, 31.35it/s]

[I 2026-07-05 15:26:17,396] Trial 2462 finished with value: 0.9494223188604356 and parameters: {'weight_class_0': 0.024356915383860173, 'weight_class_1': 0.45531518403739346, 'weight_class_2': 0.3920955892023887}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:17,417] Trial 2463 finished with value: 0.9491636986363835 and parameters: {'weight_class_0': 0.03287834416368654, 'weight_class_1': 0.47048456411126705, 'weight_class_2': 0.23619361414613324}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:17,462] Trial 2464 finished with value: 0.9375927487619998 and parameters: {'weight_class_0': 0.09865761472079866, 'weight_class_1': 0.48749379567106776, 'weight_class_2': 0.22991065527411514}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:17,464] Trial 2465 finished with value: 0.934164664606552 and parameters: {'weight_class_0': 0.1012361233925789, 'weight_class_1': 0.4459511938710761, 'weight_class_2': 0.21324624656426108}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:17,494] Trial 2466 finished with value: 0.9494122990977996 and parameters: {'weight_class_0': 0.024822477901237743, 'weight_class_1': 0.45253167178556986, 'weight_class_2': 0.40866290156904045}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:17,519] Trial 2467 finished with value: 0.93521948624278 and parameters: {'weight_class_0': 0.09882856257782878, 'weight_class_1': 0.4724885750094806, 'weight_class_2': 0.21272451686605431}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:17,599] Trial 2468 finished with value: 0.9483745115949063 and parameters: {'weight_class_0': 0.023371395140616643, 'weight_class_1': 1.0071094243850878, 'weight_class_2': 0.387055098588934}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▎                      | 2475/3000 [01:03<00:16, 31.41it/s]

[I 2026-07-05 15:26:17,616] Trial 2470 finished with value: 0.9467373673253471 and parameters: {'weight_class_0': 0.017026445947604486, 'weight_class_1': 1.0101856902219557, 'weight_class_2': 0.38828488797134464}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:17,631] Trial 2469 finished with value: 0.9493764881082596 and parameters: {'weight_class_0': 0.024261373180517604, 'weight_class_1': 0.49158011793765916, 'weight_class_2': 0.413245154758113}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:17,650] Trial 2471 finished with value: 0.9467146022071532 and parameters: {'weight_class_0': 0.017467008068957793, 'weight_class_1': 1.0387002205554332, 'weight_class_2': 0.4008994229651901}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:17,731] Trial 2473 finished with value: 0.9485285424325594 and parameters: {'weight_class_0': 0.02498135758696408, 'weight_class_1': 1.0177236409494983, 'weight_class_2': 0.4068046814795934}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:17,736] Trial 2472 finished with value: 0.9487379333596766 and parameters: {'weight_class_0': 0.025996954984614788, 'weight_class_1': 0.9984999715805108, 'weight_class_2': 0.3813624799464085}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:17,781] Trial 2474 finished with value: 0.9486278689872267 and parameters: {'weight_class_0': 0.024696250346003718, 'weight_class_1': 0.981720598699784, 'weight_class_2': 0.392510536240701}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:17,805] Trial 2475 finished with value: 0.948469877877384 and parameters: {'weight_class_0': 0.02507727398149155, 'weight_class_1': 1.0421811737603812, 'weight_class_2': 0.4066662095322865}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  83%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▌                      | 2482/3000 [01:03<00:17, 29.78it/s]

[I 2026-07-05 15:26:17,829] Trial 2477 finished with value: 0.9486127717614813 and parameters: {'weight_class_0': 0.040264452365724734, 'weight_class_1': 1.6753677678514631, 'weight_class_2': 0.4033283310254372}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:17,883] Trial 2478 finished with value: 0.9487424461949061 and parameters: {'weight_class_0': 0.04072367843790415, 'weight_class_1': 1.5959488672312445, 'weight_class_2': 0.3585068915025627}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:17,888] Trial 2476 finished with value: 0.9494976920549117 and parameters: {'weight_class_0': 0.040609734169770116, 'weight_class_1': 1.0148109063262185, 'weight_class_2': 0.40474128475715665}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:17,927] Trial 2479 finished with value: 0.9486836324368317 and parameters: {'weight_class_0': 0.04124748653065583, 'weight_class_1': 1.6094127885336367, 'weight_class_2': 0.35835655853387277}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:18,007] Trial 2481 finished with value: 0.948277270457619 and parameters: {'weight_class_0': 0.0422979296637699, 'weight_class_1': 1.5420802227874693, 'weight_class_2': 0.9472079473201198}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:18,013] Trial 2482 finished with value: 0.9494677233036902 and parameters: {'weight_class_0': 0.0409682588892217, 'weight_class_1': 0.7568086872417338, 'weight_class_2': 0.32932655008176087}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:18,015] Trial 2480 finished with value: 0.9487859326698168 and parameters: {'weight_class_0': 0.041781672383972686, 'weight_class_1': 0.9920512901736472, 'weight_class_2': 0.9307728020227762}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:18,037] Trial 2483 finished with value: 0.9488329906226416 and parameters: {'weight_class_0': 0.04164440055644983, 'weight_class_1': 0.7804965564769247, 'weight_class_2': 0.9130065549457339}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:18,112] Trial 2484 finished with value: 0.9484337361994544 and parameters: {'weight_class_0': 0.04070144132695257, 'weight_class_1': 1.6311235894851677, 'weight_class_2': 0.32474846022035964}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:18,129] Trial 2485 finished with value: 0.883191223608562 and parameters: {'weight_class_0': 0.8599739944331469, 'weight_class_1': 1.7665818506718816, 'weight_class_2': 0.3189341276070165}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:18,147] Trial 2486 finished with value: 0.9012953227728574 and parameters: {'weight_class_0': 0.8715393394223998, 'weight_class_1': 1.7318627489877878, 'weight_class_2': 0.9763351562673825}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:18,188] Trial 2487 finished with value: 0.9486924448404973 and parameters: {'weight_class_0': 0.041896109261224126, 'weight_class_1': 0.7393377373356208, 'weight_class_2': 0.948776851423312}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:18,235] Trial 2488 finished with value: 0.949806530829452 and parameters: {'weight_class_0': 0.04276174568466636, 'weight_class_1': 0.7229010211549319, 'weight_class_2': 0.5076352095116653}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:18,253] Trial 2489 finished with value: 0.9497745595881275 and parameters: {'weight_class_0': 0.041985555408874525, 'weight_class_1': 0.7895172309309363, 'weight_class_2': 0.49694293381465615}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████                      | 2495/3000 [01:03<00:16, 29.97it/s]

[I 2026-07-05 15:26:18,278] Trial 2490 finished with value: 0.9483517432749933 and parameters: {'weight_class_0': 0.03645955104168453, 'weight_class_1': 0.7021984228910769, 'weight_class_2': 0.9741488090733009}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:18,337] Trial 2491 finished with value: 0.949788977684066 and parameters: {'weight_class_0': 0.04243344992990237, 'weight_class_1': 0.7342298313455095, 'weight_class_2': 0.5155974540385335}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:18,393] Trial 2493 finished with value: 0.9490869473144232 and parameters: {'weight_class_0': 0.030764700152445753, 'weight_class_1': 0.38099745965435267, 'weight_class_2': 0.5148017602219498}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:18,402] Trial 2492 finished with value: 0.9493257942899366 and parameters: {'weight_class_0': 0.0307773356760472, 'weight_class_1': 0.7448983921264828, 'weight_class_2': 0.46444167653204416}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:18,453] Trial 2495 finished with value: 0.9491497451299326 and parameters: {'weight_class_0': 0.02921817834896138, 'weight_class_1': 0.7490377333005276, 'weight_class_2': 0.5269566992734478}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:18,457] Trial 2494 finished with value: 0.9488743783566401 and parameters: {'weight_class_0': 0.028204068995314375, 'weight_class_1': 0.40194588770662193, 'weight_class_2': 0.5490386387016711}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                     | 2503/3000 [01:04<00:15, 32.51it/s]

[I 2026-07-05 15:26:18,520] Trial 2498 finished with value: 0.9493752883273777 and parameters: {'weight_class_0': 0.02988964750376306, 'weight_class_1': 0.5510241629206765, 'weight_class_2': 0.5077458728843776}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:18,525] Trial 2497 finished with value: 0.9491296917781858 and parameters: {'weight_class_0': 0.030187076684048485, 'weight_class_1': 0.3879300329079038, 'weight_class_2': 0.5045786093355219}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:18,528] Trial 2496 finished with value: 0.9490245862000636 and parameters: {'weight_class_0': 0.02878408884893365, 'weight_class_1': 0.37799876253943376, 'weight_class_2': 0.5089717163943501}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:18,531] Trial 2499 finished with value: 0.9492961642274206 and parameters: {'weight_class_0': 0.02895459962230073, 'weight_class_1': 0.5796961100171906, 'weight_class_2': 0.5153128732246608}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:18,604] Trial 2501 finished with value: 0.9493265057172969 and parameters: {'weight_class_0': 0.031929097812523254, 'weight_class_1': 0.4044231326908877, 'weight_class_2': 0.4772918495977719}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:18,622] Trial 2502 finished with value: 0.9491231887885133 and parameters: {'weight_class_0': 0.030514003862539607, 'weight_class_1': 0.38897576114134463, 'weight_class_2': 0.5159717947695897}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:18,624] Trial 2500 finished with value: 0.8080599026766269 and parameters: {'weight_class_0': 9.627756416623226, 'weight_class_1': 0.3728589375443579, 'weight_class_2': 0.523006786505709}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:18,660] Trial 2503 finished with value: 0.9492965003896311 and parameters: {'weight_class_0': 0.03181687240762474, 'weight_class_1': 0.40055059771232493, 'weight_class_2': 0.4987994116860193}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:18,746] Trial 2505 finished with value: 0.9497113774015215 and parameters: {'weight_class_0': 0.027416584130884956, 'weight_class_1': 0.555699846124912, 'weight_class_2': 0.2897336501816892}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:18,765] Trial 2504 finished with value: 0.823649759960912 and parameters: {'weight_class_0': 2.295729958282833, 'weight_class_1': 0.388948346111086, 'weight_class_2': 0.3150342630351892}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:18,787] Trial 2506 finished with value: 0.949592192004514 and parameters: {'weight_class_0': 0.03140303193701161, 'weight_class_1': 0.5701118914928708, 'weight_class_2': 0.26997556026332153}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:18,839] Trial 2507 finished with value: 0.9496843073987952 and parameters: {'weight_class_0': 0.03425766502604742, 'weight_class_1': 0.5648889977863475, 'weight_class_2': 0.3170845852993257}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:18,897] Trial 2508 finished with value: 0.9234802888383568 and parameters: {'weight_class_0': 0.020984659275915238, 'weight_class_1': 3.2007335964857484, 'weight_class_2': 0.27450741732123685}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:18,908] Trial 2509 finished with value: 0.9494612212729648 and parameters: {'weight_class_0': 0.020648056895629034, 'weight_class_1': 0.5652057350468392, 'weight_class_2': 0.2750576538793266}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  84%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████                     | 2516/3000 [01:04<00:15, 31.42it/s]

[I 2026-07-05 15:26:18,940] Trial 2510 finished with value: 0.9494556791879875 and parameters: {'weight_class_0': 0.021291125058286255, 'weight_class_1': 0.5490899570030251, 'weight_class_2': 0.2925726664318879}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:18,978] Trial 2511 finished with value: 0.9493840911898371 and parameters: {'weight_class_0': 0.019715589449639862, 'weight_class_1': 0.5542956642303081, 'weight_class_2': 0.27126814432196217}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:19,017] Trial 2513 finished with value: 0.9493468243162848 and parameters: {'weight_class_0': 0.019745710993385655, 'weight_class_1': 0.5314599118021422, 'weight_class_2': 0.28009203424305085}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:19,034] Trial 2512 finished with value: 0.9493806661253489 and parameters: {'weight_class_0': 0.03563184849753242, 'weight_class_1': 0.5472075960124546, 'weight_class_2': 0.2733021426040433}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:19,074] Trial 2514 finished with value: 0.9493659136021768 and parameters: {'weight_class_0': 0.03728736341158756, 'weight_class_1': 0.5802761113284394, 'weight_class_2': 0.28675508954459356}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:19,075] Trial 2515 finished with value: 0.9495766140327263 and parameters: {'weight_class_0': 0.022204687769179488, 'weight_class_1': 0.5645802975579515, 'weight_class_2': 0.2754226137832135}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:19,157] Trial 2517 finished with value: 0.9478102957374676 and parameters: {'weight_class_0': 0.02037528526299653, 'weight_class_1': 0.5391837348571162, 'weight_class_2': 0.7112442044538227}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  84%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                    | 2523/3000 [01:04<00:16, 29.79it/s]

[I 2026-07-05 15:26:19,170] Trial 2516 finished with value: 0.9477833906636596 and parameters: {'weight_class_0': 0.02019168317298051, 'weight_class_1': 0.550331846720763, 'weight_class_2': 0.7082531117161573}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:19,193] Trial 2519 finished with value: 0.9479390196568999 and parameters: {'weight_class_0': 0.020693951561705646, 'weight_class_1': 0.5573996013748305, 'weight_class_2': 0.6976049353420222}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:19,201] Trial 2518 finished with value: 0.9477189817778221 and parameters: {'weight_class_0': 0.01967021235012576, 'weight_class_1': 0.5402956544173779, 'weight_class_2': 0.7183398129807564}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:19,270] Trial 2521 finished with value: 0.9462841972392192 and parameters: {'weight_class_0': 0.03539098666047873, 'weight_class_1': 0.30059630511424085, 'weight_class_2': 1.5143212862479452}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:19,297] Trial 2520 finished with value: 0.9482616718824302 and parameters: {'weight_class_0': 0.03630702648373333, 'weight_class_1': 0.31310775064331064, 'weight_class_2': 0.6941364484922208}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:19,300] Trial 2522 finished with value: 0.9492204473506239 and parameters: {'weight_class_0': 0.03758895743441933, 'weight_class_1': 0.6169612016645415, 'weight_class_2': 0.6842155073416981}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:19,322] Trial 2523 finished with value: 0.9470573123933269 and parameters: {'weight_class_0': 0.03620287423360884, 'weight_class_1': 0.5270789279284851, 'weight_class_2': 1.458901667170964}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:19,421] Trial 2525 finished with value: 0.9481807742585255 and parameters: {'weight_class_0': 0.03613755863531424, 'weight_class_1': 0.3309085203502874, 'weight_class_2': 0.7409353872659165}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:19,432] Trial 2524 finished with value: 0.9492029889749372 and parameters: {'weight_class_0': 0.03658761246837101, 'weight_class_1': 0.6343790231694258, 'weight_class_2': 0.67021599513449}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:19,435] Trial 2527 finished with value: 0.9481401213852604 and parameters: {'weight_class_0': 0.05980206715099392, 'weight_class_1': 0.3122058347909072, 'weight_class_2': 0.6778444437460047}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:19,449] Trial 2526 finished with value: 0.948186255451937 and parameters: {'weight_class_0': 0.035943689259111185, 'weight_class_1': 0.301605595618499, 'weight_class_2': 0.7039497212149138}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:19,524] Trial 2528 finished with value: 0.9476613345705971 and parameters: {'weight_class_0': 0.0487379772061321, 'weight_class_1': 0.6606480652990643, 'weight_class_2': 1.4552804211180566}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:19,525] Trial 2529 finished with value: 0.9497080566958075 and parameters: {'weight_class_0': 0.035966158849443715, 'weight_class_1': 0.6747242038748094, 'weight_class_2': 0.34464471132962515}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:19,562] Trial 2530 finished with value: 0.9493240183548566 and parameters: {'weight_class_0': 0.04699160034488837, 'weight_class_1': 0.6676516770221652, 'weight_class_2': 0.3495451372199225}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                    | 2537/3000 [01:05<00:15, 29.66it/s]

[I 2026-07-05 15:26:19,625] Trial 2531 finished with value: 0.9487623350472099 and parameters: {'weight_class_0': 0.05923235971013656, 'weight_class_1': 0.661286594073622, 'weight_class_2': 0.3531250545966977}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:19,646] Trial 2533 finished with value: 0.9491754726555178 and parameters: {'weight_class_0': 0.04757222676522245, 'weight_class_1': 0.6689702744421627, 'weight_class_2': 0.3426010573057662}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:19,651] Trial 2532 finished with value: 0.9486500412536892 and parameters: {'weight_class_0': 0.05911856261472504, 'weight_class_1': 0.6969710841426915, 'weight_class_2': 0.34106881267927786}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:19,709] Trial 2534 finished with value: 0.9493692288080063 and parameters: {'weight_class_0': 0.046236287651018414, 'weight_class_1': 0.6756236660303808, 'weight_class_2': 0.3572274325070736}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:19,739] Trial 2535 finished with value: 0.9488851382473665 and parameters: {'weight_class_0': 0.057696341110800874, 'weight_class_1': 0.6651305346461016, 'weight_class_2': 0.35129058851263306}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:19,822] Trial 2538 finished with value: 0.9492838236426975 and parameters: {'weight_class_0': 0.04736433220176175, 'weight_class_1': 0.7052631840668874, 'weight_class_2': 0.348423847922643}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:19,823] Trial 2536 finished with value: 0.949634008997216 and parameters: {'weight_class_0': 0.04919353625407364, 'weight_class_1': 0.7293565836094259, 'weight_class_2': 0.4350377240881355}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:19,824] Trial 2537 finished with value: 0.9493769576412255 and parameters: {'weight_class_0': 0.0447961790134053, 'weight_class_1': 0.686732106914521, 'weight_class_2': 0.34160462846160533}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:19,886] Trial 2539 finished with value: 0.9493155369792913 and parameters: {'weight_class_0': 0.057755978874860725, 'weight_class_1': 0.767659930953992, 'weight_class_2': 0.43014331627958535}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:19,915] Trial 2540 finished with value: 0.949323033867648 and parameters: {'weight_class_0': 0.05796839719693642, 'weight_class_1': 0.7758644366311196, 'weight_class_2': 0.4337114195853479}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:19,970] Trial 2541 finished with value: 0.9489383640382018 and parameters: {'weight_class_0': 0.05751572628827057, 'weight_class_1': 0.4327310556284119, 'weight_class_2': 0.41965056507978993}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:19,974] Trial 2542 finished with value: 0.949576983134868 and parameters: {'weight_class_0': 0.0465493830951438, 'weight_class_1': 0.4752321102609896, 'weight_class_2': 0.41067552139815233}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:19,992] Trial 2543 finished with value: 0.9494189834697006 and parameters: {'weight_class_0': 0.026709940702661493, 'weight_class_1': 0.4555816712925609, 'weight_class_2': 0.43786107600665036}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:20,050] Trial 2544 finished with value: 0.9494132964968879 and parameters: {'weight_class_0': 0.025884779830524365, 'weight_class_1': 0.4324780169628553, 'weight_class_2': 0.4274961655806542}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:20,059] Trial 2545 finished with value: 0.9492962371134105 and parameters: {'weight_class_0': 0.024618637994423546, 'weight_class_1': 0.4564476250868458, 'weight_class_2': 0.4374287358990621}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:20,082] Trial 2546 finished with value: 0.9493645186386558 and parameters: {'weight_class_0': 0.0253787491569353, 'weight_class_1': 0.48060505204229553, 'weight_class_2': 0.4370041732264523}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:20,097] Trial 2547 finished with value: 0.9494905499258434 and parameters: {'weight_class_0': 0.026820642992248803, 'weight_class_1': 0.45085818722447263, 'weight_class_2': 0.42279261888365266}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:20,193] Trial 2549 finished with value: 0.9494748442106475 and parameters: {'weight_class_0': 0.02744560861737551, 'weight_class_1': 0.47050075855011486, 'weight_class_2': 0.4367737497942887}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:20,229] Trial 2550 finished with value: 0.94794803964017 and parameters: {'weight_class_0': 0.07365499982606792, 'weight_class_1': 0.4356907121051273, 'weight_class_2': 0.4401696223663341}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:20,238] Trial 2548 finished with value: 0.9493782470576965 and parameters: {'weight_class_0': 0.02776535576762855, 'weight_class_1': 0.4151370020514358, 'weight_class_2': 0.43225495137525316}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:20,239] Trial 2551 finished with value: 0.9479545706302166 and parameters: {'weight_class_0': 0.07532493288492935, 'weight_class_1': 0.4675175211441448, 'weight_class_2': 0.4395182763315453}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:20,270] Trial 2552 finished with value: 0.9493786030269376 and parameters: {'weight_class_0': 0.027420115620847358, 'weight_class_1': 0.40364706755133123, 'weight_class_2': 0.4218645736378012}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:20,383] Trial 2554 finished with value: 0.9487379395694329 and parameters: {'weight_class_0': 0.02678726154681647, 'weight_class_1': 0.41794617868592354, 'weight_class_2': 0.5681568703265041}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:20,388] Trial 2553 finished with value: 0.9492981499268988 and parameters: {'weight_class_0': 0.026555104365756164, 'weight_class_1': 0.4734952879900595, 'weight_class_2': 0.19633609870625204}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:20,395] Trial 2555 finished with value: 0.9485245306855363 and parameters: {'weight_class_0': 0.07824892105026016, 'weight_class_1': 0.48519617045562563, 'weight_class_2': 0.5963223805240616}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:20,413] Trial 2556 finished with value: 0.9405476094952511 and parameters: {'weight_class_0': 0.07591930107106735, 'weight_class_1': 0.8567814654853614, 'weight_class_2': 0.18679639118445077}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:20,478] Trial 2557 finished with value: 0.9366495983651175 and parameters: {'weight_class_0': 0.08414195103131891, 'weight_class_1': 0.9163541979230825, 'weight_class_2': 0.18003167072318083}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:20,484] Trial 2558 finished with value: 0.9479140954380952 and parameters: {'weight_class_0': 0.01571241947012146, 'weight_class_1': 0.8369454412941115, 'weight_class_2': 0.18341112242075694}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:20,522] Trial 2559 finished with value: 0.9494805733828654 and parameters: {'weight_class_0': 0.0733552773593336, 'weight_class_1': 0.8915023634093651, 'weight_class_2': 0.6069591914788063}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:20,585] Trial 2560 finished with value: 0.9491036325203511 and parameters: {'weight_class_0': 0.033221091536270515, 'weight_class_1': 0.8962748909736974, 'weight_class_2': 0.5879169288478634}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:20,603] Trial 2561 finished with value: 0.9464977885319744 and parameters: {'weight_class_0': 0.01586181036091626, 'weight_class_1': 0.8317725613049651, 'weight_class_2': 0.6124713815731806}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:20,610] Trial 2562 finished with value: 0.9487593516779517 and parameters: {'weight_class_0': 0.03441334564268641, 'weight_class_1': 0.8568136281856042, 'weight_class_2': 0.2244171590871944}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:20,612] Trial 2563 finished with value: 0.9467595369480216 and parameters: {'weight_class_0': 0.01623980874867455, 'weight_class_1': 0.813493270389717, 'weight_class_2': 0.5853610124882013}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:20,657] Trial 2564 finished with value: 0.9483185918581455 and parameters: {'weight_class_0': 0.03436132312917012, 'weight_class_1': 0.8442342926969202, 'weight_class_2': 0.19055131658259886}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:20,765] Trial 2566 finished with value: 0.9493023854957965 and parameters: {'weight_class_0': 0.036443562438204104, 'weight_class_1': 0.8756185209756383, 'weight_class_2': 0.5958769841902222}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:20,774] Trial 2565 finished with value: 0.9492257457352199 and parameters: {'weight_class_0': 0.0339732099567203, 'weight_class_1': 0.8270539055829214, 'weight_class_2': 0.5987041436618333}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:20,801] Trial 2567 finished with value: 0.9464434593828828 and parameters: {'weight_class_0': 0.015935867389076548, 'weight_class_1': 0.8728607698601308, 'weight_class_2': 0.5736277541216985}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:20,838] Trial 2568 finished with value: 0.948379553821849 and parameters: {'weight_class_0': 0.03696692758578459, 'weight_class_1': 1.254288671034775, 'weight_class_2': 0.23467879142846665}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:20,904] Trial 2570 finished with value: 0.946918091900138 and parameters: {'weight_class_0': 0.03538687465256648, 'weight_class_1': 1.9830688151815818, 'weight_class_2': 0.23621387595805018}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                  | 2576/3000 [01:06<00:13, 30.33it/s]

[I 2026-07-05 15:26:20,906] Trial 2569 finished with value: 0.9488541091828692 and parameters: {'weight_class_0': 0.035889685936058, 'weight_class_1': 0.7788393752681064, 'weight_class_2': 0.2385133902974606}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:20,923] Trial 2571 finished with value: 0.9473209800340144 and parameters: {'weight_class_0': 0.04311002940614079, 'weight_class_1': 1.9897574532173972, 'weight_class_2': 0.2512891156652012}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:20,977] Trial 2572 finished with value: 0.9489699781799876 and parameters: {'weight_class_0': 0.04255147540637047, 'weight_class_1': 0.6008701539221809, 'weight_class_2': 0.7905951533475494}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:21,017] Trial 2574 finished with value: 0.9486100479030708 and parameters: {'weight_class_0': 0.04238060128647178, 'weight_class_1': 0.6220930709884805, 'weight_class_2': 0.24378636405951407}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:21,037] Trial 2573 finished with value: 0.9462976344513395 and parameters: {'weight_class_0': 0.04210583720421807, 'weight_class_1': 2.395036785682716, 'weight_class_2': 0.23144229753059026}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:21,051] Trial 2575 finished with value: 0.9488257489894439 and parameters: {'weight_class_0': 0.04205173839943746, 'weight_class_1': 0.6011967629048448, 'weight_class_2': 0.834168618354737}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:21,126] Trial 2576 finished with value: 0.9478685043308873 and parameters: {'weight_class_0': 0.042907280288918034, 'weight_class_1': 2.057266293680423, 'weight_class_2': 0.7975664679983758}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                  | 2582/3000 [01:06<00:14, 28.08it/s]

[I 2026-07-05 15:26:21,161] Trial 2577 finished with value: 0.9483444963770236 and parameters: {'weight_class_0': 0.04677888708855171, 'weight_class_1': 0.6051893362407685, 'weight_class_2': 0.24759583162794857}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:21,172] Trial 2578 finished with value: 0.948982194102341 and parameters: {'weight_class_0': 0.04406954957237116, 'weight_class_1': 0.6098669438350709, 'weight_class_2': 0.8137433269370321}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:21,199] Trial 2579 finished with value: 0.9477577358475241 and parameters: {'weight_class_0': 0.045603554421354296, 'weight_class_1': 2.1294182783302515, 'weight_class_2': 0.3294931884568717}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:21,246] Trial 2580 finished with value: 0.9485403333644639 and parameters: {'weight_class_0': 0.05592888311629094, 'weight_class_1': 0.5969801059194924, 'weight_class_2': 0.3149363038317676}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:21,320] Trial 2582 finished with value: 0.9491407800002268 and parameters: {'weight_class_0': 0.04379492349818898, 'weight_class_1': 0.5816549483313237, 'weight_class_2': 0.30868998691962435}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:21,329] Trial 2581 finished with value: 0.9493108874336765 and parameters: {'weight_class_0': 0.04385520869902792, 'weight_class_1': 0.5869058709389385, 'weight_class_2': 0.3260924409743654}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:21,332] Trial 2583 finished with value: 0.9491260838146518 and parameters: {'weight_class_0': 0.04792181611984115, 'weight_class_1': 0.5903645620994953, 'weight_class_2': 0.34126216659849606}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:21,357] Trial 2584 finished with value: 0.9491417079109333 and parameters: {'weight_class_0': 0.04558501542965737, 'weight_class_1': 0.5659998985096109, 'weight_class_2': 0.3239558645068081}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:21,396] Trial 2585 finished with value: 0.9313138973073706 and parameters: {'weight_class_0': 0.0522832380329379, 'weight_class_1': 0.0877888154079621, 'weight_class_2': 0.31290796468847937}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:21,424] Trial 2587 finished with value: 0.9487863320484161 and parameters: {'weight_class_0': 0.04959159405631818, 'weight_class_1': 1.2595824866114131, 'weight_class_2': 0.3321643083015495}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:21,442] Trial 2586 finished with value: 0.9486185652923577 and parameters: {'weight_class_0': 0.050861065383751916, 'weight_class_1': 1.2503932143936167, 'weight_class_2': 0.3080778300864887}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:21,471] Trial 2588 finished with value: 0.9285633046751668 and parameters: {'weight_class_0': 0.056770089309949257, 'weight_class_1': 0.0870982410453506, 'weight_class_2': 0.30858096579795635}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:21,538] Trial 2590 finished with value: 0.947940457838088 and parameters: {'weight_class_0': 0.059820889658194154, 'weight_class_1': 0.3659155237169435, 'weight_class_2': 0.35038912829997804}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:21,546] Trial 2589 finished with value: 0.9477807718367908 and parameters: {'weight_class_0': 0.058706795593434405, 'weight_class_1': 0.3480776132514054, 'weight_class_2': 0.32998838678889514}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:21,580] Trial 2591 finished with value: 0.9490585698820823 and parameters: {'weight_class_0': 0.06672470499210655, 'weight_class_1': 0.5516442494239255, 'weight_class_2': 0.49766931565573735}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:21,622] Trial 2592 finished with value: 0.9493889536797638 and parameters: {'weight_class_0': 0.06293237515364068, 'weight_class_1': 1.2408449459898483, 'weight_class_2': 0.49826632199618615}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:21,729] Trial 2593 finished with value: 0.9478429401612937 and parameters: {'weight_class_0': 0.06399011862240865, 'weight_class_1': 0.3188158728171051, 'weight_class_2': 0.5041348272146415}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:21,745] Trial 2594 finished with value: 0.9493097137820832 and parameters: {'weight_class_0': 0.06439622230491225, 'weight_class_1': 1.2641305062737453, 'weight_class_2': 0.48553556624586625}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  87%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                 | 2602/3000 [01:07<00:12, 30.96it/s]

[I 2026-07-05 15:26:21,785] Trial 2595 finished with value: 0.949348795153608 and parameters: {'weight_class_0': 0.06311226592531555, 'weight_class_1': 1.374423707798765, 'weight_class_2': 0.5072874992899491}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:21,805] Trial 2596 finished with value: 0.9483531688869348 and parameters: {'weight_class_0': 0.023109673455450473, 'weight_class_1': 0.2729983795822553, 'weight_class_2': 0.4932340473771492}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:21,832] Trial 2598 finished with value: 0.9490542032430506 and parameters: {'weight_class_0': 0.029917161935621286, 'weight_class_1': 0.36251159590284154, 'weight_class_2': 0.514583837636381}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:21,846] Trial 2597 finished with value: 0.9491195819721012 and parameters: {'weight_class_0': 0.029242820462094414, 'weight_class_1': 0.3340365346965723, 'weight_class_2': 0.4701826936888185}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:21,879] Trial 2599 finished with value: 0.9489238012450594 and parameters: {'weight_class_0': 0.024008043817131404, 'weight_class_1': 0.5042170020272446, 'weight_class_2': 0.49882486773461915}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:21,919] Trial 2601 finished with value: 0.9494274755158992 and parameters: {'weight_class_0': 0.03208953381616677, 'weight_class_1': 0.7047448976705044, 'weight_class_2': 0.5141071755900307}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:21,928] Trial 2600 finished with value: 0.949324451348483 and parameters: {'weight_class_0': 0.02958589400483565, 'weight_class_1': 0.5170251710379882, 'weight_class_2': 0.513463858628572}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:21,952] Trial 2602 finished with value: 0.9491822677909675 and parameters: {'weight_class_0': 0.02941662009136448, 'weight_class_1': 0.7544967621397037, 'weight_class_2': 0.5130025567698833}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████                 | 2608/3000 [01:07<00:13, 30.12it/s]

[I 2026-07-05 15:26:21,986] Trial 2604 finished with value: 0.949154310440373 and parameters: {'weight_class_0': 0.029135169893368607, 'weight_class_1': 0.7223084664694852, 'weight_class_2': 0.5299077518589854}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:21,987] Trial 2603 finished with value: 0.9492498739749206 and parameters: {'weight_class_0': 0.029748688437528006, 'weight_class_1': 0.7407010473623034, 'weight_class_2': 0.4961276420866812}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:22,105] Trial 2605 finished with value: 0.9496719775961472 and parameters: {'weight_class_0': 0.031728510964898975, 'weight_class_1': 0.7283372064799921, 'weight_class_2': 0.39165526336573503}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:22,108] Trial 2606 finished with value: 0.9489545005362277 and parameters: {'weight_class_0': 0.022460389758646407, 'weight_class_1': 0.7369412755327394, 'weight_class_2': 0.3938421803926413}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:22,168] Trial 2607 finished with value: 0.9496130793973053 and parameters: {'weight_class_0': 0.03176081858609917, 'weight_class_1': 0.7330123936983992, 'weight_class_2': 0.4032899782306071}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:22,184] Trial 2608 finished with value: 0.9497022589729438 and parameters: {'weight_class_0': 0.031618802590716, 'weight_class_1': 0.7486929642293608, 'weight_class_2': 0.37287207410368084}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                | 2615/3000 [01:07<00:12, 31.63it/s]

[I 2026-07-05 15:26:22,215] Trial 2609 finished with value: 0.9363101119078943 and parameters: {'weight_class_0': 0.031280260904246376, 'weight_class_1': 0.7742748694338175, 'weight_class_2': 0.0662598584290457}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:22,257] Trial 2610 finished with value: 0.9496303806518283 and parameters: {'weight_class_0': 0.030321704209679473, 'weight_class_1': 0.6796487691507228, 'weight_class_2': 0.3864038692614526}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:22,268] Trial 2611 finished with value: 0.9497681794713243 and parameters: {'weight_class_0': 0.035423139654981645, 'weight_class_1': 0.7329937713834482, 'weight_class_2': 0.3948667300067234}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:22,278] Trial 2612 finished with value: 0.9497696543838808 and parameters: {'weight_class_0': 0.034486457537989255, 'weight_class_1': 0.7195999090159704, 'weight_class_2': 0.3835223717596531}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:22,335] Trial 2614 finished with value: 0.9281065790270073 and parameters: {'weight_class_0': 0.19034517999624842, 'weight_class_1': 0.4969021805339087, 'weight_class_2': 0.3995273514114197}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:22,378] Trial 2613 finished with value: 0.939260882926089 and parameters: {'weight_class_0': 0.16327096589146792, 'weight_class_1': 1.0155029934523419, 'weight_class_2': 0.3945916709695283}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:22,398] Trial 2615 finished with value: 0.9496894516104843 and parameters: {'weight_class_0': 0.0368931245756165, 'weight_class_1': 0.5010813610861408, 'weight_class_2': 0.3867526169685156}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                | 2621/3000 [01:08<00:13, 27.89it/s]

[I 2026-07-05 15:26:22,411] Trial 2616 finished with value: 0.9490770472944137 and parameters: {'weight_class_0': 0.03522918504637636, 'weight_class_1': 0.4926437805291271, 'weight_class_2': 0.6333451825322604}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:22,544] Trial 2619 finished with value: 0.9493033171458126 and parameters: {'weight_class_0': 0.04048288766554889, 'weight_class_1': 1.019119299769572, 'weight_class_2': 0.6405120529726749}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:22,548] Trial 2617 finished with value: 0.949044464864862 and parameters: {'weight_class_0': 0.03719291815186019, 'weight_class_1': 0.47973604566292644, 'weight_class_2': 0.6519197678751335}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:22,573] Trial 2618 finished with value: 0.9492394167341741 and parameters: {'weight_class_0': 0.08888147354087989, 'weight_class_1': 1.0215299735095467, 'weight_class_2': 0.6513667575049393}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:22,605] Trial 2620 finished with value: 0.9493048060595207 and parameters: {'weight_class_0': 0.08860972083194021, 'weight_class_1': 1.0349363459046634, 'weight_class_2': 0.6820690107798827}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:22,645] Trial 2621 finished with value: 0.9490942324882351 and parameters: {'weight_class_0': 0.08849823286015497, 'weight_class_1': 1.0179166699972568, 'weight_class_2': 0.6119248366327392}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                | 2628/3000 [01:08<00:12, 29.75it/s]

[I 2026-07-05 15:26:22,647] Trial 2622 finished with value: 0.9473090584450929 and parameters: {'weight_class_0': 0.02368527874718212, 'weight_class_1': 1.0194476948713707, 'weight_class_2': 0.7978802171138719}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:22,657] Trial 2623 finished with value: 0.9466019979592927 and parameters: {'weight_class_0': 0.19509271975042786, 'weight_class_1': 1.0592376647893758, 'weight_class_2': 0.8893346094854467}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:22,709] Trial 2625 finished with value: 0.9491385185884673 and parameters: {'weight_class_0': 0.036907891320187514, 'weight_class_1': 0.48949084638757584, 'weight_class_2': 0.629549285259876}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:22,713] Trial 2624 finished with value: 0.9492554599614342 and parameters: {'weight_class_0': 0.0406107210435741, 'weight_class_1': 0.5114409304284216, 'weight_class_2': 0.6430936982375288}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:22,800] Trial 2626 finished with value: 0.9473354193369131 and parameters: {'weight_class_0': 0.024221404060866487, 'weight_class_1': 0.4050186392885933, 'weight_class_2': 0.9402050843319311}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:22,805] Trial 2628 finished with value: 0.9474053403464432 and parameters: {'weight_class_0': 0.08767245090913667, 'weight_class_1': 0.3956966221046875, 'weight_class_2': 0.7665198330800375}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:22,810] Trial 2627 finished with value: 0.9474253164557059 and parameters: {'weight_class_0': 0.024466122503797323, 'weight_class_1': 1.049146516393914, 'weight_class_2': 0.7828950062824044}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏               | 2635/3000 [01:08<00:12, 28.86it/s]

[I 2026-07-05 15:26:22,888] Trial 2629 finished with value: 0.8932445273202747 and parameters: {'weight_class_0': 0.02309869962321349, 'weight_class_1': 0.4049113748490751, 'weight_class_2': 5.983198952283867}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:22,949] Trial 2631 finished with value: 0.9498041176772575 and parameters: {'weight_class_0': 0.023155654513192115, 'weight_class_1': 0.4006538928349434, 'weight_class_2': 0.26785319168136235}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:22,968] Trial 2630 finished with value: 0.9464466929316337 and parameters: {'weight_class_0': 0.01718416571147563, 'weight_class_1': 0.6271496067563743, 'weight_class_2': 0.9795712528965186}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:22,992] Trial 2632 finished with value: 0.9392241276017949 and parameters: {'weight_class_0': 0.01783221659873391, 'weight_class_1': 0.39687594751604893, 'weight_class_2': 2.2173104452131884}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:23,029] Trial 2633 finished with value: 0.9486353780402977 and parameters: {'weight_class_0': 0.050084920179228554, 'weight_class_1': 0.42471178813232824, 'weight_class_2': 0.8112854184561784}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:23,031] Trial 2634 finished with value: 0.9484978127693852 and parameters: {'weight_class_0': 0.05283784005768202, 'weight_class_1': 0.39106609140498694, 'weight_class_2': 0.8049171605062436}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:23,066] Trial 2635 finished with value: 0.9190716679412206 and parameters: {'weight_class_0': 0.02261440865346195, 'weight_class_1': 0.39608824654878166, 'weight_class_2': 4.414960226020915}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:23,121] Trial 2636 finished with value: 0.9479394576630241 and parameters: {'weight_class_0': 0.053132167718189356, 'weight_class_1': 0.3858628427059563, 'weight_class_2': 0.2680211682727215}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:23,137] Trial 2637 finished with value: 0.9482769678053108 and parameters: {'weight_class_0': 0.054636732526466406, 'weight_class_1': 0.6106481946999185, 'weight_class_2': 0.28083519337225055}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:23,208] Trial 2638 finished with value: 0.9477800258653124 and parameters: {'weight_class_0': 0.0563228965701197, 'weight_class_1': 0.6136178036071054, 'weight_class_2': 0.26302213689840115}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:23,220] Trial 2639 finished with value: 0.9483743425430199 and parameters: {'weight_class_0': 0.051103759074709, 'weight_class_1': 0.5942170524718007, 'weight_class_2': 0.2707917978663488}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:23,227] Trial 2640 finished with value: 0.9488714583021808 and parameters: {'weight_class_0': 0.017127238717854047, 'weight_class_1': 0.6163438595411027, 'weight_class_2': 0.2742006128062641}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:23,302] Trial 2642 finished with value: 0.9494227462919408 and parameters: {'weight_class_0': 0.018647757411843314, 'weight_class_1': 0.23779234136519692, 'weight_class_2': 0.26504989577022686}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋               | 2648/3000 [01:08<00:11, 29.67it/s]

[I 2026-07-05 15:26:23,304] Trial 2641 finished with value: 0.9486672808352984 and parameters: {'weight_class_0': 0.05111328876239931, 'weight_class_1': 0.5799009595416195, 'weight_class_2': 0.29513770680928536}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:23,381] Trial 2643 finished with value: 0.9483292586277119 and parameters: {'weight_class_0': 0.051193818157477505, 'weight_class_1': 0.6146597357208226, 'weight_class_2': 0.2694996546839922}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:23,404] Trial 2644 finished with value: 0.9491217904771833 and parameters: {'weight_class_0': 0.03990617735102002, 'weight_class_1': 0.6124368164211139, 'weight_class_2': 0.2758275390348321}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:23,443] Trial 2646 finished with value: 0.9476565879464817 and parameters: {'weight_class_0': 0.04918323333001637, 'weight_class_1': 0.2778356161575896, 'weight_class_2': 0.28115242192634193}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:23,462] Trial 2645 finished with value: 0.9491197965631507 and parameters: {'weight_class_0': 0.038993799410313876, 'weight_class_1': 0.6122645524501678, 'weight_class_2': 0.2651810335714766}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:23,501] Trial 2647 finished with value: 0.9488258169634042 and parameters: {'weight_class_0': 0.03972080303121941, 'weight_class_1': 0.30651690762367756, 'weight_class_2': 0.271669510128718}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:23,504] Trial 2648 finished with value: 0.9485712394440556 and parameters: {'weight_class_0': 0.04000055667519407, 'weight_class_1': 0.2486179367214792, 'weight_class_2': 0.4326389317746554}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 2655/3000 [01:09<00:11, 29.11it/s]

[I 2026-07-05 15:26:23,506] Trial 2649 finished with value: 0.9492318737453962 and parameters: {'weight_class_0': 0.03980868922469708, 'weight_class_1': 0.31147697866738483, 'weight_class_2': 0.42763348835026527}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:23,595] Trial 2651 finished with value: 0.949111029013591 and parameters: {'weight_class_0': 0.0402853983776352, 'weight_class_1': 0.2983293951615336, 'weight_class_2': 0.4677900025958426}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:23,647] Trial 2650 finished with value: 0.9492746141614593 and parameters: {'weight_class_0': 0.038440806638582015, 'weight_class_1': 0.30819449521723385, 'weight_class_2': 0.4454094029564645}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:23,670] Trial 2652 finished with value: 0.9491795728614276 and parameters: {'weight_class_0': 0.040092495980765926, 'weight_class_1': 0.2966446871083189, 'weight_class_2': 0.4469773351997436}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:23,697] Trial 2653 finished with value: 0.9494692663252556 and parameters: {'weight_class_0': 0.03888850869704367, 'weight_class_1': 0.3437515336422734, 'weight_class_2': 0.4337173217478186}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:23,720] Trial 2654 finished with value: 0.9491098011010793 and parameters: {'weight_class_0': 0.04123023529397573, 'weight_class_1': 0.30274792889242347, 'weight_class_2': 0.4500673005914777}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:23,768] Trial 2655 finished with value: 0.9494504688835331 and parameters: {'weight_class_0': 0.036505262060845756, 'weight_class_1': 0.3403707888386814, 'weight_class_2': 0.43968441420221016}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:23,774] Trial 2656 finished with value: 0.9486360767739376 and parameters: {'weight_class_0': 0.03972027440945978, 'weight_class_1': 0.25001452485440107, 'weight_class_2': 0.4462328503521134}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:23,851] Trial 2657 finished with value: 0.9492374887781345 and parameters: {'weight_class_0': 0.037366485833739964, 'weight_class_1': 0.30115480978815307, 'weight_class_2': 0.44364658614908087}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:23,857] Trial 2659 finished with value: 0.9495582166673744 and parameters: {'weight_class_0': 0.027763788824759716, 'weight_class_1': 0.3280674959429457, 'weight_class_2': 0.35218064344685945}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:23,864] Trial 2658 finished with value: 0.9496693320545916 and parameters: {'weight_class_0': 0.027141098863587988, 'weight_class_1': 0.5108161126763329, 'weight_class_2': 0.3594815300959976}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:23,891] Trial 2660 finished with value: 0.9411210018377592 and parameters: {'weight_class_0': 0.12171370864594631, 'weight_class_1': 0.516567572608242, 'weight_class_2': 0.35360894633565954}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  89%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌              | 2668/3000 [01:09<00:11, 29.89it/s]

[I 2026-07-05 15:26:23,934] Trial 2661 finished with value: 0.8224381085636212 and parameters: {'weight_class_0': 3.0376871028760317, 'weight_class_1': 0.4778823130187593, 'weight_class_2': 0.37356684511294186}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:23,977] Trial 2662 finished with value: 0.9497003737892026 and parameters: {'weight_class_0': 0.027463087346902684, 'weight_class_1': 0.5043400686450206, 'weight_class_2': 0.35213568667175865}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:24,035] Trial 2663 finished with value: 0.9495955154784893 and parameters: {'weight_class_0': 0.02653015484182259, 'weight_class_1': 0.505010493623853, 'weight_class_2': 0.36420909136310103}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:24,082] Trial 2664 finished with value: 0.9490366455244755 and parameters: {'weight_class_0': 0.02699097285763905, 'weight_class_1': 0.4994266634951347, 'weight_class_2': 0.1831950460660223}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:24,084] Trial 2665 finished with value: 0.9496433140820332 and parameters: {'weight_class_0': 0.02712922689511809, 'weight_class_1': 0.4978613242401501, 'weight_class_2': 0.3650829710888661}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:24,120] Trial 2667 finished with value: 0.9496024030135315 and parameters: {'weight_class_0': 0.026607734755387854, 'weight_class_1': 0.5101615160985653, 'weight_class_2': 0.3640144547265811}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:24,141] Trial 2668 finished with value: 0.9415381616377893 and parameters: {'weight_class_0': 0.1194358683117347, 'weight_class_1': 0.5149722841008092, 'weight_class_2': 0.35282226711901626}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:24,153] Trial 2666 finished with value: 0.9496758124820038 and parameters: {'weight_class_0': 0.027293587911795904, 'weight_class_1': 0.5090162687644124, 'weight_class_2': 0.35694160326684854}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:24,224] Trial 2669 finished with value: 0.9495241865978841 and parameters: {'weight_class_0': 0.06625372643486824, 'weight_class_1': 0.8545459423700418, 'weight_class_2': 0.5636234042886181}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:24,259] Trial 2671 finished with value: 0.9495162659507081 and parameters: {'weight_class_0': 0.06703228237692029, 'weight_class_1': 0.8742340338472145, 'weight_class_2': 0.5776328648615383}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:24,264] Trial 2670 finished with value: 0.9495546117394663 and parameters: {'weight_class_0': 0.06841097196026297, 'weight_class_1': 0.8361118025961591, 'weight_class_2': 0.5865740670520314}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:24,349] Trial 2672 finished with value: 0.9408176069308141 and parameters: {'weight_class_0': 0.06924679281168253, 'weight_class_1': 0.8667430292103037, 'weight_class_2': 0.17271371328977347}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:24,423] Trial 2673 finished with value: 0.9495874856434919 and parameters: {'weight_class_0': 0.06601825316793868, 'weight_class_1': 0.868278392979754, 'weight_class_2': 0.5825436814034002}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  89%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏             | 2680/3000 [01:10<00:10, 29.71it/s]

[I 2026-07-05 15:26:24,425] Trial 2674 finished with value: 0.9494571103611188 and parameters: {'weight_class_0': 0.0713300949462769, 'weight_class_1': 0.804929859977203, 'weight_class_2': 0.5856647058008905}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:24,434] Trial 2675 finished with value: 0.949464084747595 and parameters: {'weight_class_0': 0.06917602915718338, 'weight_class_1': 0.8794007743138086, 'weight_class_2': 0.5691576373465271}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:24,498] Trial 2676 finished with value: 0.9477580296872525 and parameters: {'weight_class_0': 0.021514148870048516, 'weight_class_1': 0.865813399617979, 'weight_class_2': 0.6001437064785059}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:24,533] Trial 2677 finished with value: 0.9494364696397022 and parameters: {'weight_class_0': 0.06717877096568632, 'weight_class_1': 0.8406852592010641, 'weight_class_2': 0.5469435752960353}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:24,567] Trial 2678 finished with value: 0.949438606742766 and parameters: {'weight_class_0': 0.06923548067380357, 'weight_class_1': 0.8697860226831514, 'weight_class_2': 0.5751304365371532}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:24,596] Trial 2679 finished with value: 0.949369881348133 and parameters: {'weight_class_0': 0.06961528909263649, 'weight_class_1': 0.8717302577417828, 'weight_class_2': 0.5484781264798082}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:24,610] Trial 2680 finished with value: 0.9492363148843089 and parameters: {'weight_class_0': 0.07309813981528014, 'weight_class_1': 0.8078987313072458, 'weight_class_2': 0.5388523807355952}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍             | 2686/3000 [01:10<00:11, 27.10it/s]

[I 2026-07-05 15:26:24,615] Trial 2681 finished with value: 0.948405770926208 and parameters: {'weight_class_0': 0.02210726825927697, 'weight_class_1': 0.6946374687047385, 'weight_class_2': 0.5458738158719998}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:24,624] Trial 2682 finished with value: 0.9469298718100635 and parameters: {'weight_class_0': 0.0217333429999287, 'weight_class_1': 1.3723162973344594, 'weight_class_2': 0.2018031429858188}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:24,672] Trial 2683 finished with value: 0.9481539612296372 and parameters: {'weight_class_0': 0.021226873860120003, 'weight_class_1': 0.7020081695425734, 'weight_class_2': 0.5917757551395197}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:24,701] Trial 2684 finished with value: 0.9459117658260224 and parameters: {'weight_class_0': 0.021056019778553918, 'weight_class_1': 1.3908414391130297, 'weight_class_2': 0.5485905043568274}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:24,841] Trial 2687 finished with value: 0.9490610329565241 and parameters: {'weight_class_0': 0.0323869912311491, 'weight_class_1': 0.6520986329470145, 'weight_class_2': 0.2246970829330816}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:24,847] Trial 2685 finished with value: 0.9471500746257736 and parameters: {'weight_class_0': 0.022456312317304813, 'weight_class_1': 1.3616388456449655, 'weight_class_2': 0.20642140401961556}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:24,853] Trial 2686 finished with value: 0.9474272679276354 and parameters: {'weight_class_0': 0.022136349273948384, 'weight_class_1': 1.286163826484942, 'weight_class_2': 0.21102459111809344}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:24,867] Trial 2688 finished with value: 0.9480763015941495 and parameters: {'weight_class_0': 0.031223693365546618, 'weight_class_1': 1.2941070640978258, 'weight_class_2': 0.22103933379515406}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:24,937] Trial 2689 finished with value: 0.9481698305889955 and parameters: {'weight_class_0': 0.03360350883254258, 'weight_class_1': 0.6715790975621572, 'weight_class_2': 1.0045751600137656}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:24,964] Trial 2690 finished with value: 0.9480696733952777 and parameters: {'weight_class_0': 0.03233846244774607, 'weight_class_1': 1.2703896501309304, 'weight_class_2': 0.21303005611289336}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:24,987] Trial 2691 finished with value: 0.9487763147822905 and parameters: {'weight_class_0': 0.03288464519598831, 'weight_class_1': 0.6804893832649088, 'weight_class_2': 0.7614240085161407}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:25,003] Trial 2692 finished with value: 0.9490343648211939 and parameters: {'weight_class_0': 0.03161248840463633, 'weight_class_1': 0.6504487460320955, 'weight_class_2': 0.2213523773461}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:25,036] Trial 2693 finished with value: 0.9481126260967878 and parameters: {'weight_class_0': 0.03259308073243716, 'weight_class_1': 0.6567562139551221, 'weight_class_2': 0.9994481986398648}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉             | 2698/3000 [01:10<00:10, 27.74it/s]

[I 2026-07-05 15:26:25,088] Trial 2696 finished with value: 0.8468672617987479 and parameters: {'weight_class_0': 1.5330800831954217, 'weight_class_1': 0.6288324895377114, 'weight_class_2': 0.9664277034166074}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:25,090] Trial 2694 finished with value: 0.9491009125088992 and parameters: {'weight_class_0': 0.03238232802245334, 'weight_class_1': 0.6331238752559241, 'weight_class_2': 0.22942288548981912}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:25,101] Trial 2695 finished with value: 0.9490187271011695 and parameters: {'weight_class_0': 0.03207340848189216, 'weight_class_1': 0.6387938524271911, 'weight_class_2': 0.2162875788391563}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:25,241] Trial 2698 finished with value: 0.949394271330284 and parameters: {'weight_class_0': 0.04775595124827336, 'weight_class_1': 0.6454377515866319, 'weight_class_2': 0.7358074779097816}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:25,245] Trial 2697 finished with value: 0.9486996929710957 and parameters: {'weight_class_0': 0.046198259251212404, 'weight_class_1': 0.41643431760131666, 'weight_class_2': 0.7756326782581044}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:25,264] Trial 2700 finished with value: 0.9487263267220234 and parameters: {'weight_class_0': 0.04712427132459575, 'weight_class_1': 0.3960724043168194, 'weight_class_2': 0.7174586307998067}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:25,276] Trial 2699 finished with value: 0.9482690245253297 and parameters: {'weight_class_0': 0.03307809000221295, 'weight_class_1': 0.41082031926568957, 'weight_class_2': 0.7475532204425028}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:25,330] Trial 2701 finished with value: 0.9444039178570071 and parameters: {'weight_class_0': 0.005876683016659825, 'weight_class_1': 0.4119532772129508, 'weight_class_2': 0.31903374432817677}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:25,357] Trial 2702 finished with value: 0.949082110076423 and parameters: {'weight_class_0': 0.0448266612777202, 'weight_class_1': 0.40984803081976623, 'weight_class_2': 0.3145006626488409}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:25,386] Trial 2704 finished with value: 0.9446139195278529 and parameters: {'weight_class_0': 0.005953374096654425, 'weight_class_1': 0.41009468934834803, 'weight_class_2': 0.3148799765566119}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:25,391] Trial 2703 finished with value: 0.9495061085968698 and parameters: {'weight_class_0': 0.04494716136612262, 'weight_class_1': 0.4159035767303855, 'weight_class_2': 0.4512083558924418}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:25,442] Trial 2705 finished with value: 0.9495075854138233 and parameters: {'weight_class_0': 0.04710131059471525, 'weight_class_1': 0.4141207998615157, 'weight_class_2': 0.4541373848418642}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  90%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 2713/3000 [01:11<00:08, 32.29it/s]

[I 2026-07-05 15:26:25,459] Trial 2706 finished with value: 0.949515919182497 and parameters: {'weight_class_0': 0.04732708622516701, 'weight_class_1': 0.42094815211616693, 'weight_class_2': 0.45834471837184276}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:25,486] Trial 2707 finished with value: 0.9495094657352058 and parameters: {'weight_class_0': 0.04582439099378294, 'weight_class_1': 0.4182729092955833, 'weight_class_2': 0.4447732481396126}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:25,571] Trial 2708 finished with value: 0.9492989657284608 and parameters: {'weight_class_0': 0.052664999264227894, 'weight_class_1': 0.4191034061170393, 'weight_class_2': 0.45945248093698804}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:25,600] Trial 2709 finished with value: 0.9495431756735679 and parameters: {'weight_class_0': 0.04688809583844962, 'weight_class_1': 1.1198294500621253, 'weight_class_2': 0.4448799300745552}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:25,626] Trial 2710 finished with value: 0.9496218941952789 and parameters: {'weight_class_0': 0.04732389517258228, 'weight_class_1': 0.5526648864134791, 'weight_class_2': 0.43670621588248826}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:25,632] Trial 2711 finished with value: 0.9494274831586202 and parameters: {'weight_class_0': 0.053482616134678834, 'weight_class_1': 1.1114790403135004, 'weight_class_2': 0.439745132422961}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:25,679] Trial 2712 finished with value: 0.9496731143957525 and parameters: {'weight_class_0': 0.05262756894496439, 'weight_class_1': 1.0764793607881495, 'weight_class_2': 0.46980871421303716}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:25,752] Trial 2714 finished with value: 0.9494964119219874 and parameters: {'weight_class_0': 0.05036493188906042, 'weight_class_1': 1.0752267186675328, 'weight_class_2': 0.42444676689961247}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:25,762] Trial 2713 finished with value: 0.9494444445839695 and parameters: {'weight_class_0': 0.05555233639807402, 'weight_class_1': 0.5474140986692763, 'weight_class_2': 0.45812410042482643}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:25,786] Trial 2715 finished with value: 0.9490311757497333 and parameters: {'weight_class_0': 0.05789398181240955, 'weight_class_1': 1.008424140595496, 'weight_class_2': 0.3862813696619698}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:25,860] Trial 2717 finished with value: 0.9468762880745798 and parameters: {'weight_class_0': 0.017539617179267775, 'weight_class_1': 1.0217888076976582, 'weight_class_2': 0.3776246322056454}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:25,861] Trial 2718 finished with value: 0.9471087292721071 and parameters: {'weight_class_0': 0.01783688755431651, 'weight_class_1': 0.9987245751832625, 'weight_class_2': 0.3773732891721919}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:25,891] Trial 2716 finished with value: 0.9487080694479008 and parameters: {'weight_class_0': 0.017926621566781372, 'weight_class_1': 0.5461237573394577, 'weight_class_2': 0.38117927187810435}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████            | 2725/3000 [01:11<00:08, 30.78it/s]

[I 2026-07-05 15:26:25,952] Trial 2719 finished with value: 0.948902579630162 and parameters: {'weight_class_0': 0.05730320898075399, 'weight_class_1': 0.5415638283480886, 'weight_class_2': 0.36556932899618255}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:26,002] Trial 2720 finished with value: 0.949656566390586 and parameters: {'weight_class_0': 0.03648626321644409, 'weight_class_1': 0.5527164874545472, 'weight_class_2': 0.37538677049200914}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:26,006] Trial 2721 finished with value: 0.9487622442976821 and parameters: {'weight_class_0': 0.01812583643410511, 'weight_class_1': 0.5443772825200855, 'weight_class_2': 0.36924395719107783}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:26,057] Trial 2722 finished with value: 0.9496763135239278 and parameters: {'weight_class_0': 0.035574798612379444, 'weight_class_1': 0.5412325158549229, 'weight_class_2': 0.3438614078121971}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:26,059] Trial 2723 finished with value: 0.9488632644561869 and parameters: {'weight_class_0': 0.018350865731570947, 'weight_class_1': 0.5417572890946761, 'weight_class_2': 0.3623600058224198}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:26,073] Trial 2724 finished with value: 0.9485635757630041 and parameters: {'weight_class_0': 0.016857734224484885, 'weight_class_1': 0.5566496483800575, 'weight_class_2': 0.3500015146711326}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:26,112] Trial 2725 finished with value: 0.9483283316687047 and parameters: {'weight_class_0': 0.017776648775211967, 'weight_class_1': 0.7299822556062933, 'weight_class_2': 0.3375466580731226}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍           | 2732/3000 [01:11<00:09, 29.74it/s]

[I 2026-07-05 15:26:26,160] Trial 2726 finished with value: 0.9490120616762275 and parameters: {'weight_class_0': 0.01808361048122901, 'weight_class_1': 0.5350143917010274, 'weight_class_2': 0.32854535218110437}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:26,205] Trial 2727 finished with value: 0.949539568486995 and parameters: {'weight_class_0': 0.03655925172659038, 'weight_class_1': 0.7664958099169421, 'weight_class_2': 0.3185271417687444}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:26,261] Trial 2728 finished with value: 0.9492424929537723 and parameters: {'weight_class_0': 0.036776806386329235, 'weight_class_1': 0.7695581682118426, 'weight_class_2': 0.6666858014855614}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:26,274] Trial 2729 finished with value: 0.9498076683616657 and parameters: {'weight_class_0': 0.02740036485153085, 'weight_class_1': 0.546845830511275, 'weight_class_2': 0.3133696874390371}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:26,286] Trial 2730 finished with value: 0.9476387099890012 and parameters: {'weight_class_0': 0.036128710883992395, 'weight_class_1': 0.7370427452519313, 'weight_class_2': 1.2976850535250106}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:26,365] Trial 2732 finished with value: 0.9493880796679939 and parameters: {'weight_class_0': 0.024984699963909084, 'weight_class_1': 0.7601090316042514, 'weight_class_2': 0.3160584496669903}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:26,370] Trial 2731 finished with value: 0.9470254105347263 and parameters: {'weight_class_0': 0.02531039676510756, 'weight_class_1': 0.7408431535511917, 'weight_class_2': 1.2361273929168934}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋           | 2738/3000 [01:12<00:09, 27.55it/s]

[I 2026-07-05 15:26:26,422] Trial 2733 finished with value: 0.9495570501575505 and parameters: {'weight_class_0': 0.026730822742026518, 'weight_class_1': 0.7353662975343285, 'weight_class_2': 0.3025059627672253}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:26,449] Trial 2734 finished with value: 0.9487509022697447 and parameters: {'weight_class_0': 0.09208257876086513, 'weight_class_1': 0.6843909833105131, 'weight_class_2': 1.2458509870992922}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:26,463] Trial 2735 finished with value: 0.9483715762033434 and parameters: {'weight_class_0': 0.02487779418808024, 'weight_class_1': 0.7554082716739422, 'weight_class_2': 0.6512469320246413}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:26,517] Trial 2736 finished with value: 0.9382001813577042 and parameters: {'weight_class_0': 0.02707531364825479, 'weight_class_1': 0.7888896700880155, 'weight_class_2': 3.5185518189302156}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:26,537] Trial 2737 finished with value: 0.9491750725699081 and parameters: {'weight_class_0': 0.03654236301580778, 'weight_class_1': 0.7423923546056915, 'weight_class_2': 0.6903350643033668}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:26,582] Trial 2738 finished with value: 0.9485230965028425 and parameters: {'weight_class_0': 0.027709946139313078, 'weight_class_1': 0.7528987363575463, 'weight_class_2': 0.6783742961838334}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉           | 2745/3000 [01:12<00:08, 31.17it/s]

[I 2026-07-05 15:26:26,584] Trial 2739 finished with value: 0.9485292973807197 and parameters: {'weight_class_0': 0.026282534257282223, 'weight_class_1': 0.754692619868691, 'weight_class_2': 0.6452095904964185}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:26,644] Trial 2741 finished with value: 0.9485125829496314 and parameters: {'weight_class_0': 0.09273666263258673, 'weight_class_1': 1.6554931247106872, 'weight_class_2': 0.521453482000178}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:26,654] Trial 2740 finished with value: 0.9489060309165649 and parameters: {'weight_class_0': 0.095221095787362, 'weight_class_1': 0.7526037892077514, 'weight_class_2': 0.685769592504699}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:26,703] Trial 2742 finished with value: 0.9465506606788572 and parameters: {'weight_class_0': 0.028897430164218942, 'weight_class_1': 1.64315498280852, 'weight_class_2': 0.8907380188953304}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:26,709] Trial 2743 finished with value: 0.9488341505115224 and parameters: {'weight_class_0': 0.029300210656901794, 'weight_class_1': 0.6662482295722242, 'weight_class_2': 0.6480743270960413}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:26,778] Trial 2744 finished with value: 0.8283096896598443 and parameters: {'weight_class_0': 5.480662673885334, 'weight_class_1': 1.5262923598574707, 'weight_class_2': 0.5301532498097811}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:26,820] Trial 2746 finished with value: 0.9485718461541763 and parameters: {'weight_class_0': 0.09434246829747595, 'weight_class_1': 0.9046955061139691, 'weight_class_2': 0.539252188039209}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏          | 2751/3000 [01:12<00:08, 28.64it/s]

[I 2026-07-05 15:26:26,842] Trial 2745 finished with value: 0.9494417428457779 and parameters: {'weight_class_0': 0.08255295016828951, 'weight_class_1': 1.5088849989208133, 'weight_class_2': 0.6596693221753688}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:26,883] Trial 2747 finished with value: 0.9489109528511905 and parameters: {'weight_class_0': 0.08156610799593587, 'weight_class_1': 0.9416836335424954, 'weight_class_2': 0.5047305724048627}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:26,951] Trial 2749 finished with value: 0.9487446691933181 and parameters: {'weight_class_0': 0.08696912109895591, 'weight_class_1': 0.9244203323634678, 'weight_class_2': 0.5150899198039708}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:26,960] Trial 2748 finished with value: 0.9497140969757232 and parameters: {'weight_class_0': 0.07786974868204602, 'weight_class_1': 0.981824527869842, 'weight_class_2': 0.908041640645878}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:27,023] Trial 2750 finished with value: 0.9497703369600347 and parameters: {'weight_class_0': 0.04326585302892285, 'weight_class_1': 0.6263173728913237, 'weight_class_2': 0.5112615414962588}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:27,058] Trial 2751 finished with value: 0.9489159041803967 and parameters: {'weight_class_0': 0.042621557632500355, 'weight_class_1': 0.9924356858734725, 'weight_class_2': 0.874544933769749}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌          | 2758/3000 [01:12<00:08, 27.50it/s]

[I 2026-07-05 15:26:27,092] Trial 2754 finished with value: 0.949677735381132 and parameters: {'weight_class_0': 0.042188006692275966, 'weight_class_1': 0.6149427828416114, 'weight_class_2': 0.5293395591140609}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:27,093] Trial 2752 finished with value: 0.9497287080419796 and parameters: {'weight_class_0': 0.04234706244599142, 'weight_class_1': 0.6363171126349692, 'weight_class_2': 0.5030299470028042}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:27,121] Trial 2753 finished with value: 0.9496597303786088 and parameters: {'weight_class_0': 0.041744149111664575, 'weight_class_1': 0.9102337912038241, 'weight_class_2': 0.5217761691834885}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:27,166] Trial 2755 finished with value: 0.9496809417871853 and parameters: {'weight_class_0': 0.04146461402377583, 'weight_class_1': 0.9555591303951625, 'weight_class_2': 0.4968044432404806}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:27,183] Trial 2756 finished with value: 0.9497419177602203 and parameters: {'weight_class_0': 0.04077268786437937, 'weight_class_1': 0.6141540117009869, 'weight_class_2': 0.49640002397560085}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:27,233] Trial 2757 finished with value: 0.9497813647229075 and parameters: {'weight_class_0': 0.042899146868396354, 'weight_class_1': 0.9510777866998222, 'weight_class_2': 0.5049290193653037}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:27,271] Trial 2758 finished with value: 0.9469925684017048 and parameters: {'weight_class_0': 0.04007693454675897, 'weight_class_1': 0.62261208809139, 'weight_class_2': 1.7266263923672875}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊          | 2765/3000 [01:12<00:08, 29.01it/s]

[I 2026-07-05 15:26:27,314] Trial 2759 finished with value: 0.8538404900106205 and parameters: {'weight_class_0': 1.1342031740976972, 'weight_class_1': 0.603269547056689, 'weight_class_2': 0.8201790141132729}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:27,368] Trial 2760 finished with value: 0.949666196642697 and parameters: {'weight_class_0': 0.04364792798420018, 'weight_class_1': 0.5929211828889319, 'weight_class_2': 0.47232533731251425}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:27,397] Trial 2761 finished with value: 0.9497583508107822 and parameters: {'weight_class_0': 0.037838181180342004, 'weight_class_1': 0.627272254999325, 'weight_class_2': 0.4173870053600928}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:27,436] Trial 2762 finished with value: 0.949700697216667 and parameters: {'weight_class_0': 0.041594977095736264, 'weight_class_1': 0.6025486080666065, 'weight_class_2': 0.42513464408888957}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:27,466] Trial 2763 finished with value: 0.9490899564447997 and parameters: {'weight_class_0': 0.034610688044630966, 'weight_class_1': 1.232787870946191, 'weight_class_2': 0.41625481114443225}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:27,499] Trial 2764 finished with value: 0.9490344331199029 and parameters: {'weight_class_0': 0.05705752630113997, 'weight_class_1': 0.6069434958711413, 'weight_class_2': 0.40117760551488374}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:27,543] Trial 2765 finished with value: 0.9490545359807192 and parameters: {'weight_class_0': 0.05942523225375221, 'weight_class_1': 1.222527267692699, 'weight_class_2': 0.4179450302602856}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 2770/3000 [01:13<00:08, 27.69it/s]

[I 2026-07-05 15:26:27,584] Trial 2766 finished with value: 0.9490139589311256 and parameters: {'weight_class_0': 0.05916483603319175, 'weight_class_1': 0.6244958893225965, 'weight_class_2': 0.4173836563513253}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:27,646] Trial 2768 finished with value: 0.9490895184478535 and parameters: {'weight_class_0': 0.05579797399528945, 'weight_class_1': 0.625663393678884, 'weight_class_2': 0.3975742767096465}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:27,664] Trial 2767 finished with value: 0.9492702491528063 and parameters: {'weight_class_0': 0.05902886643017957, 'weight_class_1': 1.1689739091759759, 'weight_class_2': 0.4371823664779488}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:27,708] Trial 2770 finished with value: 0.9497152539399539 and parameters: {'weight_class_0': 0.03242752729638773, 'weight_class_1': 0.5043198649009536, 'weight_class_2': 0.4061740090870273}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:27,709] Trial 2769 finished with value: 0.9488577658813733 and parameters: {'weight_class_0': 0.059993740460674204, 'weight_class_1': 0.4914075482297341, 'weight_class_2': 0.4049909434300776}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:27,805] Trial 2771 finished with value: 0.9489715030553513 and parameters: {'weight_class_0': 0.0587191862005665, 'weight_class_1': 1.2772353503899077, 'weight_class_2': 0.4068367129159292}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:27,834] Trial 2772 finished with value: 0.9488707100850083 and parameters: {'weight_class_0': 0.05944397853243121, 'weight_class_1': 0.4907082306183641, 'weight_class_2': 0.4041385372812399}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:27,842] Trial 2773 finished with value: 0.9482091099027761 and parameters: {'weight_class_0': 0.05789087468552113, 'weight_class_1': 0.4993019983348181, 'weight_class_2': 0.2991719275229613}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:27,857] Trial 2774 finished with value: 0.9484596417950383 and parameters: {'weight_class_0': 0.05595623991721566, 'weight_class_1': 0.5259164046877728, 'weight_class_2': 0.3063012649733677}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:27,889] Trial 2775 finished with value: 0.9481363397951862 and parameters: {'weight_class_0': 0.057063747447606755, 'weight_class_1': 0.49533908089533707, 'weight_class_2': 0.2871109862060671}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:27,920] Trial 2776 finished with value: 0.9496642379069811 and parameters: {'weight_class_0': 0.033886787678438654, 'weight_class_1': 0.4946010048773152, 'weight_class_2': 0.30391171374454484}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:27,924] Trial 2777 finished with value: 0.9496893192976797 and parameters: {'weight_class_0': 0.030896183200270412, 'weight_class_1': 0.4969794197793307, 'weight_class_2': 0.30656064518838994}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  93%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋         | 2784/3000 [01:13<00:07, 29.42it/s]

[I 2026-07-05 15:26:27,961] Trial 2778 finished with value: 0.847133851715327 and parameters: {'weight_class_0': 1.8437857662168613, 'weight_class_1': 0.7992831493171925, 'weight_class_2': 1.0801340400359951}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:28,034] Trial 2779 finished with value: 0.9494913896121201 and parameters: {'weight_class_0': 0.030325480158062725, 'weight_class_1': 0.7558786734531276, 'weight_class_2': 0.30398138792588975}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:28,070] Trial 2781 finished with value: 0.9494647484569109 and parameters: {'weight_class_0': 0.03080238019229563, 'weight_class_1': 0.7955992670153488, 'weight_class_2': 0.30816591994456194}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:28,085] Trial 2780 finished with value: 0.9477805528351898 and parameters: {'weight_class_0': 0.030827445440440936, 'weight_class_1': 0.7894342681161927, 'weight_class_2': 1.0757665729081451}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:28,116] Trial 2782 finished with value: 0.9494404450954687 and parameters: {'weight_class_0': 0.03171694819544881, 'weight_class_1': 0.7791594105936375, 'weight_class_2': 0.2791490548803182}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:28,198] Trial 2785 finished with value: 0.9490296343231156 and parameters: {'weight_class_0': 0.032277464229276784, 'weight_class_1': 0.7792038599106548, 'weight_class_2': 0.6285942029130268}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:28,229] Trial 2784 finished with value: 0.9495365970788487 and parameters: {'weight_class_0': 0.031476155647277536, 'weight_class_1': 0.7844600363629808, 'weight_class_2': 0.30273498493966117}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:28,231] Trial 2783 finished with value: 0.9486138330829094 and parameters: {'weight_class_0': 0.03212386934261892, 'weight_class_1': 0.8081669777854195, 'weight_class_2': 0.7770704612959092}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:28,289] Trial 2786 finished with value: 0.9491276187225294 and parameters: {'weight_class_0': 0.03239575817373159, 'weight_class_1': 0.7438358798845013, 'weight_class_2': 0.6177020114978995}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:28,323] Trial 2788 finished with value: 0.9485629066923079 and parameters: {'weight_class_0': 0.11635501024676452, 'weight_class_1': 0.8153133419412446, 'weight_class_2': 0.7583131524923669}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:28,377] Trial 2787 finished with value: 0.9484853790959434 and parameters: {'weight_class_0': 0.030663754914636812, 'weight_class_1': 0.7559795269866003, 'weight_class_2': 0.7813407096722066}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:28,388] Trial 2789 finished with value: 0.9485209937508698 and parameters: {'weight_class_0': 0.03147941727368897, 'weight_class_1': 0.7382600812155593, 'weight_class_2': 0.8129432423741231}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:28,408] Trial 2790 finished with value: 0.9495583475535918 and parameters: {'weight_class_0': 0.047387026295754454, 'weight_class_1': 0.7653276210684651, 'weight_class_2': 0.6517977482915326}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏        | 2796/3000 [01:14<00:06, 29.47it/s]

[I 2026-07-05 15:26:28,436] Trial 2792 finished with value: 0.9492973196651292 and parameters: {'weight_class_0': 0.0354196434755494, 'weight_class_1': 0.6841317136302266, 'weight_class_2': 0.6287446787345927}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:28,454] Trial 2791 finished with value: 0.9493935682941462 and parameters: {'weight_class_0': 0.03496503401833444, 'weight_class_1': 0.7807438547590181, 'weight_class_2': 0.5677821952343343}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:28,528] Trial 2793 finished with value: 0.949077739592424 and parameters: {'weight_class_0': 0.03477456137139947, 'weight_class_1': 0.9436642552563976, 'weight_class_2': 0.6255416800577922}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:28,559] Trial 2795 finished with value: 0.9493560337342267 and parameters: {'weight_class_0': 0.0484316817062394, 'weight_class_1': 1.1540124987446965, 'weight_class_2': 0.7270754809150748}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:28,566] Trial 2794 finished with value: 0.9442754953139004 and parameters: {'weight_class_0': 0.03466584061874383, 'weight_class_1': 2.85477931861141, 'weight_class_2': 0.6276310861641896}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:28,613] Trial 2796 finished with value: 0.949578927079905 and parameters: {'weight_class_0': 0.04551416892393656, 'weight_class_1': 0.9614920818164979, 'weight_class_2': 0.6101176635373959}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍        | 2803/3000 [01:14<00:06, 29.54it/s]

[I 2026-07-05 15:26:28,692] Trial 2797 finished with value: 0.949673732975695 and parameters: {'weight_class_0': 0.04823945179326471, 'weight_class_1': 1.123421177883723, 'weight_class_2': 0.5857756637595904}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:28,732] Trial 2798 finished with value: 0.9497086716107779 and parameters: {'weight_class_0': 0.04841754468623682, 'weight_class_1': 1.1208614473917087, 'weight_class_2': 0.5737722137118081}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:28,762] Trial 2799 finished with value: 0.9497099112836606 and parameters: {'weight_class_0': 0.047840577040170584, 'weight_class_1': 1.1141982069132303, 'weight_class_2': 0.5634785545294241}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:28,781] Trial 2801 finished with value: 0.9093908762027646 and parameters: {'weight_class_0': 0.03977525742818346, 'weight_class_1': 1.111051152533054, 'weight_class_2': 0.03943108168052187}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:28,785] Trial 2800 finished with value: 0.9496874497704729 and parameters: {'weight_class_0': 0.04625118246583773, 'weight_class_1': 0.9911914106954886, 'weight_class_2': 0.5698580201393371}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:28,829] Trial 2802 finished with value: 0.9496531889283747 and parameters: {'weight_class_0': 0.04723143185932803, 'weight_class_1': 1.1723401254179469, 'weight_class_2': 0.5344344603101083}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:28,859] Trial 2803 finished with value: 0.949748036682334 and parameters: {'weight_class_0': 0.04857683766570413, 'weight_class_1': 1.0919454236454311, 'weight_class_2': 0.5620398093959926}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  94%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋        | 2809/3000 [01:14<00:06, 27.75it/s]

[I 2026-07-05 15:26:28,882] Trial 2804 finished with value: 0.9390686823678268 and parameters: {'weight_class_0': 0.04567067293997262, 'weight_class_1': 0.10153865484302654, 'weight_class_2': 0.5120021055628814}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:28,931] Trial 2806 finished with value: 0.8979849151659122 and parameters: {'weight_class_0': 0.0765376838674298, 'weight_class_1': 0.6196670011178497, 'weight_class_2': 0.04165879144398677}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:28,949] Trial 2805 finished with value: 0.9491789830729115 and parameters: {'weight_class_0': 0.0483095731153685, 'weight_class_1': 0.5776986189594434, 'weight_class_2': 0.35171675094281385}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:28,966] Trial 2807 finished with value: 0.9454748731380258 and parameters: {'weight_class_0': 0.023904087621135908, 'weight_class_1': 1.802414679722831, 'weight_class_2': 0.3667401241355665}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:29,000] Trial 2808 finished with value: 0.9476387682141709 and parameters: {'weight_class_0': 0.07485524220514161, 'weight_class_1': 0.5991290128131577, 'weight_class_2': 0.3501669449811385}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:29,105] Trial 2809 finished with value: 0.9258032133223089 and parameters: {'weight_class_0': 0.0727444829659929, 'weight_class_1': 0.10298288460943698, 'weight_class_2': 0.362468427780073}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:29,138] Trial 2810 finished with value: 0.9477143857672995 and parameters: {'weight_class_0': 0.0787317154076523, 'weight_class_1': 0.6141117231739341, 'weight_class_2': 0.37283398645003524}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:29,165] Trial 2811 finished with value: 0.9473629901591455 and parameters: {'weight_class_0': 0.07790067983484959, 'weight_class_1': 0.5872403156155631, 'weight_class_2': 0.34914751691421836}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:29,173] Trial 2812 finished with value: 0.9478286972934096 and parameters: {'weight_class_0': 0.07629781362041156, 'weight_class_1': 1.8857016612341464, 'weight_class_2': 0.3732770552477441}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:29,189] Trial 2813 finished with value: 0.9493219362945244 and parameters: {'weight_class_0': 0.023887856053634776, 'weight_class_1': 0.610226842117084, 'weight_class_2': 0.3691725725581799}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:29,228] Trial 2815 finished with value: 0.9495280016868805 and parameters: {'weight_class_0': 0.02573366424874961, 'weight_class_1': 0.6071812623644335, 'weight_class_2': 0.34546628076630365}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:29,257] Trial 2814 finished with value: 0.9427635245728608 and parameters: {'weight_class_0': 0.024384890298880517, 'weight_class_1': 0.5836800710250761, 'weight_class_2': 0.06800199302431023}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:29,305] Trial 2816 finished with value: 0.9494922073769891 and parameters: {'weight_class_0': 0.023057653239312317, 'weight_class_1': 0.4763108848032304, 'weight_class_2': 0.3570175522145478}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  94%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏       | 2821/3000 [01:14<00:05, 30.48it/s]

[I 2026-07-05 15:26:29,333] Trial 2817 finished with value: 0.9497161180185513 and parameters: {'weight_class_0': 0.026680659572574785, 'weight_class_1': 0.4545625227357488, 'weight_class_2': 0.25015493675179934}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:29,340] Trial 2818 finished with value: 0.9473195496025415 and parameters: {'weight_class_0': 0.02283461217471748, 'weight_class_1': 0.4614684766803348, 'weight_class_2': 0.9242515577102969}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:29,431] Trial 2819 finished with value: 0.8566415841589944 and parameters: {'weight_class_0': 0.6058704402718618, 'weight_class_1': 0.465112769203525, 'weight_class_2': 0.2566550981832855}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:29,486] Trial 2820 finished with value: 0.9475386568518562 and parameters: {'weight_class_0': 0.025004724198147178, 'weight_class_1': 0.5036691798618235, 'weight_class_2': 0.937510484035389}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:29,516] Trial 2821 finished with value: 0.9474406194791415 and parameters: {'weight_class_0': 0.025864919317640404, 'weight_class_1': 0.4548686453232529, 'weight_class_2': 0.955604396463709}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  94%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 2828/3000 [01:15<00:06, 28.43it/s]

[I 2026-07-05 15:26:29,577] Trial 2823 finished with value: 0.9493559183351237 and parameters: {'weight_class_0': 0.02693279822720611, 'weight_class_1': 0.46808723383825895, 'weight_class_2': 0.461128671332672}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:29,581] Trial 2822 finished with value: 0.9493184370853543 and parameters: {'weight_class_0': 0.026610347116138855, 'weight_class_1': 0.4592944746994294, 'weight_class_2': 0.46565684142721686}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:29,647] Trial 2827 finished with value: 0.9480516898825065 and parameters: {'weight_class_0': 0.04031071335993886, 'weight_class_1': 0.45870486871477023, 'weight_class_2': 0.9642865155627613}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:29,648] Trial 2825 finished with value: 0.9489976185528386 and parameters: {'weight_class_0': 0.038043570900458054, 'weight_class_1': 0.46937218881535114, 'weight_class_2': 0.24546640206497813}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:29,649] Trial 2824 finished with value: 0.9284966460549059 and parameters: {'weight_class_0': 0.038665895788354096, 'weight_class_1': 0.4658852638692479, 'weight_class_2': 0.06391299155228022}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:29,682] Trial 2826 finished with value: 0.9491147770828506 and parameters: {'weight_class_0': 0.036614282746352776, 'weight_class_1': 0.46466188909496464, 'weight_class_2': 0.25015457072286823}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:29,721] Trial 2828 finished with value: 0.9496670299482721 and parameters: {'weight_class_0': 0.037734128201386434, 'weight_class_1': 0.49009288198474416, 'weight_class_2': 0.46339255609629754}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  94%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊       | 2833/3000 [01:15<00:05, 30.32it/s]

[I 2026-07-05 15:26:29,758] Trial 2830 finished with value: 0.9485831662607058 and parameters: {'weight_class_0': 0.036306553787241486, 'weight_class_1': 1.5232059095251476, 'weight_class_2': 0.4632046448358505}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:29,768] Trial 2829 finished with value: 0.9489470208873808 and parameters: {'weight_class_0': 0.03794457709365654, 'weight_class_1': 1.4329011740871551, 'weight_class_2': 0.45722986571982777}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:29,802] Trial 2831 finished with value: 0.9496485788635743 and parameters: {'weight_class_0': 0.03866951707728874, 'weight_class_1': 0.9365093325590216, 'weight_class_2': 0.4697372500078943}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:29,905] Trial 2833 finished with value: 0.9489871461111578 and parameters: {'weight_class_0': 0.03807901690525657, 'weight_class_1': 1.4062361684995666, 'weight_class_2': 0.4754562786839958}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:29,909] Trial 2832 finished with value: 0.9496029670082725 and parameters: {'weight_class_0': 0.0368241693869055, 'weight_class_1': 0.9219653773430551, 'weight_class_2': 0.45487694296155934}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████       | 2840/3000 [01:15<00:05, 28.57it/s]

[I 2026-07-05 15:26:29,996] Trial 2835 finished with value: 0.9489193677918841 and parameters: {'weight_class_0': 0.038630138300429454, 'weight_class_1': 1.485018184446373, 'weight_class_2': 0.44502385291319646}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:29,999] Trial 2834 finished with value: 0.9488769382823122 and parameters: {'weight_class_0': 0.03903274401673125, 'weight_class_1': 1.5116812173356857, 'weight_class_2': 0.46358330484781696}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:30,033] Trial 2837 finished with value: 0.9486472586581168 and parameters: {'weight_class_0': 0.0357011345527161, 'weight_class_1': 1.446252424642574, 'weight_class_2': 0.4940693432134765}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:30,040] Trial 2836 finished with value: 0.9495842497950503 and parameters: {'weight_class_0': 0.036984510392200964, 'weight_class_1': 0.9143364893977982, 'weight_class_2': 0.4653458860282453}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:30,108] Trial 2838 finished with value: 0.9464440078070613 and parameters: {'weight_class_0': 0.11223954463400213, 'weight_class_1': 3.804096729048061, 'weight_class_2': 0.4556619262351246}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:30,111] Trial 2839 finished with value: 0.9475266770413486 and parameters: {'weight_class_0': 0.11380592014587618, 'weight_class_1': 1.4124770204557724, 'weight_class_2': 0.5071263615760392}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:30,140] Trial 2841 finished with value: 0.947076588716384 and parameters: {'weight_class_0': 0.06243087869125089, 'weight_class_1': 2.468434808003076, 'weight_class_2': 0.30296189702191345}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎      | 2846/3000 [01:15<00:05, 27.27it/s]

[I 2026-07-05 15:26:30,156] Trial 2840 finished with value: 0.9492310633539538 and parameters: {'weight_class_0': 0.030006412432660404, 'weight_class_1': 0.9000256080821903, 'weight_class_2': 0.4738542262728948}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:30,190] Trial 2843 finished with value: 0.9483149752739991 and parameters: {'weight_class_0': 0.11137530615753032, 'weight_class_1': 0.6769109432232239, 'weight_class_2': 0.7745335089518143}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:30,221] Trial 2842 finished with value: 0.9479410139937539 and parameters: {'weight_class_0': 0.06530769975961898, 'weight_class_1': 0.6793171321863543, 'weight_class_2': 0.31548677278514353}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:30,296] Trial 2844 finished with value: 0.9494907712077861 and parameters: {'weight_class_0': 0.061477896786276964, 'weight_class_1': 0.6414180482631465, 'weight_class_2': 0.7744761902007267}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:30,322] Trial 2845 finished with value: 0.9482794828699054 and parameters: {'weight_class_0': 0.05502387831717506, 'weight_class_1': 2.501918872343669, 'weight_class_2': 0.7892856183966825}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:30,393] Trial 2846 finished with value: 0.9482990679111438 and parameters: {'weight_class_0': 0.059375136664389476, 'weight_class_1': 0.6481465101552667, 'weight_class_2': 0.30591401797250384}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋      | 2853/3000 [01:16<00:05, 27.63it/s]

[I 2026-07-05 15:26:30,442] Trial 2848 finished with value: 0.9495285266022891 and parameters: {'weight_class_0': 0.0599820202846038, 'weight_class_1': 0.6697949517608419, 'weight_class_2': 0.7718903158335967}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:30,451] Trial 2847 finished with value: 0.9484855058393786 and parameters: {'weight_class_0': 0.02984113393192367, 'weight_class_1': 0.7306835281320243, 'weight_class_2': 0.7591011960190913}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:30,455] Trial 2849 finished with value: 0.9493703319181188 and parameters: {'weight_class_0': 0.05506880626352011, 'weight_class_1': 0.6711516076865192, 'weight_class_2': 0.8013833741392078}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:30,495] Trial 2850 finished with value: 0.948591819692402 and parameters: {'weight_class_0': 0.029114326130150702, 'weight_class_1': 0.6768841008173893, 'weight_class_2': 0.7088649150255916}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:30,559] Trial 2851 finished with value: 0.9226340930079462 and parameters: {'weight_class_0': 0.05324544986222012, 'weight_class_1': 0.06509449656315153, 'weight_class_2': 0.7470924376949931}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:30,587] Trial 2852 finished with value: 0.9469861266843344 and parameters: {'weight_class_0': 0.054448422250500776, 'weight_class_1': 0.3658548720015272, 'weight_class_2': 1.4384283082407598}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:30,591] Trial 2853 finished with value: 0.948501165695454 and parameters: {'weight_class_0': 0.05317441572594198, 'weight_class_1': 0.36961683034299175, 'weight_class_2': 0.7486467616801037}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉      | 2859/3000 [01:16<00:04, 28.59it/s]

[I 2026-07-05 15:26:30,667] Trial 2855 finished with value: 0.9485205418830963 and parameters: {'weight_class_0': 0.050471874149250584, 'weight_class_1': 0.35280804918153835, 'weight_class_2': 0.31703331405204577}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:30,722] Trial 2856 finished with value: 0.9482588628936602 and parameters: {'weight_class_0': 0.05137359559369189, 'weight_class_1': 0.3541825402562109, 'weight_class_2': 0.30046669960487715}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:30,732] Trial 2854 finished with value: 0.9474848028446002 and parameters: {'weight_class_0': 0.05117629777590831, 'weight_class_1': 0.36284315472349277, 'weight_class_2': 1.1513452232296375}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:30,754] Trial 2857 finished with value: 0.9391291717677905 and parameters: {'weight_class_0': 0.027986425216216824, 'weight_class_1': 0.06760748872767228, 'weight_class_2': 0.6679235587421446}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:30,815] Trial 2858 finished with value: 0.9492484744690654 and parameters: {'weight_class_0': 0.046835648698821716, 'weight_class_1': 0.5472480517150149, 'weight_class_2': 0.34436895931044664}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:30,843] Trial 2859 finished with value: 0.9394199922317027 and parameters: {'weight_class_0': 0.02930302806868353, 'weight_class_1': 0.06748954824255554, 'weight_class_2': 0.2538665730923259}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:30,912] Trial 2860 finished with value: 0.9480362170335507 and parameters: {'weight_class_0': 0.049274650689980035, 'weight_class_1': 0.3657351747392606, 'weight_class_2': 0.25218473118220835}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:30,921] Trial 2861 finished with value: 0.9482828927320012 and parameters: {'weight_class_0': 0.045887003222721344, 'weight_class_1': 0.3715026526276335, 'weight_class_2': 0.25129778416363885}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:30,959] Trial 2862 finished with value: 0.949243901263967 and parameters: {'weight_class_0': 0.04522311077497648, 'weight_class_1': 0.35400081266720895, 'weight_class_2': 0.3902678940802634}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:30,966] Trial 2863 finished with value: 0.9234378891106663 and parameters: {'weight_class_0': 0.36575325590971736, 'weight_class_1': 0.5393656990591834, 'weight_class_2': 1.1688997505216818}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:31,001] Trial 2864 finished with value: 0.9317225089062138 and parameters: {'weight_class_0': 0.004562873514903595, 'weight_class_1': 0.5615287179275061, 'weight_class_2': 0.37365797404014156}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:31,007] Trial 2865 finished with value: 0.9485172777920488 and parameters: {'weight_class_0': 0.0455734519630831, 'weight_class_1': 0.5598294164411028, 'weight_class_2': 0.2482245676126436}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:31,041] Trial 2866 finished with value: 0.9495769892694166 and parameters: {'weight_class_0': 0.02107577659584877, 'weight_class_1': 0.5617000059793759, 'weight_class_2': 0.2508888635676544}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍     | 2872/3000 [01:16<00:04, 29.37it/s]

[I 2026-07-05 15:26:31,105] Trial 2867 finished with value: 0.9496341892563948 and parameters: {'weight_class_0': 0.042777490678653066, 'weight_class_1': 0.5570773482923913, 'weight_class_2': 0.3901133441510354}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:31,162] Trial 2869 finished with value: 0.9492076059015764 and parameters: {'weight_class_0': 0.022194124949106473, 'weight_class_1': 0.5492782162292028, 'weight_class_2': 0.3913301735215733}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:31,166] Trial 2868 finished with value: 0.9495593670622631 and parameters: {'weight_class_0': 0.04472485441462342, 'weight_class_1': 0.5357268465449746, 'weight_class_2': 0.38916430479003405}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:31,219] Trial 2871 finished with value: 0.9490470780881185 and parameters: {'weight_class_0': 0.02067425122193541, 'weight_class_1': 0.5435759213269679, 'weight_class_2': 0.3927605569215525}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:31,255] Trial 2870 finished with value: 0.9493941981122972 and parameters: {'weight_class_0': 0.03008230665122618, 'weight_class_1': 0.9170222233951314, 'weight_class_2': 0.375617745300728}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:31,297] Trial 2872 finished with value: 0.9491056793743731 and parameters: {'weight_class_0': 0.021319566307018412, 'weight_class_1': 0.5453334229432923, 'weight_class_2': 0.3906427796300839}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋     | 2878/3000 [01:17<00:04, 26.51it/s]

[I 2026-07-05 15:26:31,338] Trial 2873 finished with value: 0.9477373725202399 and parameters: {'weight_class_0': 0.0220171940312447, 'weight_class_1': 0.9259427622984424, 'weight_class_2': 0.5728574553642889}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:31,370] Trial 2874 finished with value: 0.9493521854871393 and parameters: {'weight_class_0': 0.031639902551023724, 'weight_class_1': 0.5738722354786716, 'weight_class_2': 0.5458986152764416}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:31,449] Trial 2875 finished with value: 0.9486520516885865 and parameters: {'weight_class_0': 0.029132522620495843, 'weight_class_1': 0.8985727416659179, 'weight_class_2': 0.6282930065672657}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:31,465] Trial 2876 finished with value: 0.9495208676990888 and parameters: {'weight_class_0': 0.029774007307900335, 'weight_class_1': 0.7753862750831837, 'weight_class_2': 0.39459053682859835}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:31,519] Trial 2878 finished with value: 0.9489788713865718 and parameters: {'weight_class_0': 0.030091158468166512, 'weight_class_1': 0.8485131023871355, 'weight_class_2': 0.5668985443938438}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:31,544] Trial 2881 finished with value: 0.9485384095203514 and parameters: {'weight_class_0': 0.028751080666310675, 'weight_class_1': 0.9873211638306524, 'weight_class_2': 0.5914246366507505}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:31,546] Trial 2877 finished with value: 0.9490584651845285 and parameters: {'weight_class_0': 0.030838950042789706, 'weight_class_1': 0.8950954259081408, 'weight_class_2': 0.5564988547654047}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:31,548] Trial 2879 finished with value: 0.9489520020258095 and parameters: {'weight_class_0': 0.029296814006373136, 'weight_class_1': 0.8927738274496093, 'weight_class_2': 0.5412494136310999}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:31,560] Trial 2880 finished with value: 0.9490852166375768 and parameters: {'weight_class_0': 0.030519174394011604, 'weight_class_1': 0.8432243189050403, 'weight_class_2': 0.5404018716263314}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:31,658] Trial 2882 finished with value: 0.9491957679349702 and parameters: {'weight_class_0': 0.03379725599763866, 'weight_class_1': 0.9289499598149408, 'weight_class_2': 0.5515323223613338}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:31,697] Trial 2883 finished with value: 0.9490904215762641 and parameters: {'weight_class_0': 0.03181836515486941, 'weight_class_1': 0.8243103526240546, 'weight_class_2': 0.5949110948973481}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏    | 2890/3000 [01:17<00:04, 27.32it/s]

[I 2026-07-05 15:26:31,802] Trial 2884 finished with value: 0.9482650418280477 and parameters: {'weight_class_0': 0.034696256611403145, 'weight_class_1': 0.7053997680444012, 'weight_class_2': 0.18175127357830678}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:31,813] Trial 2885 finished with value: 0.949124042317158 and parameters: {'weight_class_0': 0.033289801144863976, 'weight_class_1': 0.8402810044195048, 'weight_class_2': 0.6113866814409586}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:31,874] Trial 2886 finished with value: 0.9474369884563164 and parameters: {'weight_class_0': 0.03670629110240111, 'weight_class_1': 0.7028143460966431, 'weight_class_2': 0.1618764941311906}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:31,880] Trial 2887 finished with value: 0.9494674620713023 and parameters: {'weight_class_0': 0.034792399206994756, 'weight_class_1': 0.73292689202608, 'weight_class_2': 0.5475206504817784}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:31,901] Trial 2888 finished with value: 0.9495162045500113 and parameters: {'weight_class_0': 0.036122054081194156, 'weight_class_1': 0.7707526458882061, 'weight_class_2': 0.30822196948618985}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:31,931] Trial 2889 finished with value: 0.9497260213666839 and parameters: {'weight_class_0': 0.0367359342712286, 'weight_class_1': 0.6908976488630788, 'weight_class_2': 0.3428032015112743}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:31,990] Trial 2891 finished with value: 0.9471081722024405 and parameters: {'weight_class_0': 0.07143263922977887, 'weight_class_1': 0.6905340852067554, 'weight_class_2': 0.29491363043619767}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  97%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌    | 2897/3000 [01:17<00:03, 27.36it/s]

[I 2026-07-05 15:26:32,010] Trial 2890 finished with value: 0.949666522753045 and parameters: {'weight_class_0': 0.0353105468681522, 'weight_class_1': 0.6760500487422004, 'weight_class_2': 0.32194219724717155}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:32,019] Trial 2892 finished with value: 0.9474876931870391 and parameters: {'weight_class_0': 0.06963109983196496, 'weight_class_1': 0.6806938248043098, 'weight_class_2': 0.3093181079377089}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:32,085] Trial 2893 finished with value: 0.9475324194343019 and parameters: {'weight_class_0': 0.06859162922998607, 'weight_class_1': 0.70180739852123, 'weight_class_2': 0.30665176002124966}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:32,120] Trial 2894 finished with value: 0.9471879854368527 and parameters: {'weight_class_0': 0.04107779089281921, 'weight_class_1': 0.7090333755933177, 'weight_class_2': 0.17175483614107506}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:32,130] Trial 2895 finished with value: 0.9474289757946711 and parameters: {'weight_class_0': 0.0695220150712273, 'weight_class_1': 0.6925124017919739, 'weight_class_2': 0.3052681443279459}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:32,219] Trial 2896 finished with value: 0.9448330298340721 and parameters: {'weight_class_0': 0.0961563518174485, 'weight_class_1': 0.6966999822375676, 'weight_class_2': 0.31791943555555774}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:32,263] Trial 2897 finished with value: 0.9343563933780615 and parameters: {'weight_class_0': 0.1416050959992595, 'weight_class_1': 0.6370398797914736, 'weight_class_2': 0.29932047105935033}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:32,333] Trial 2898 finished with value: 0.9473139475030227 and parameters: {'weight_class_0': 0.07438910059360625, 'weight_class_1': 1.1763066428013327, 'weight_class_2': 0.3198195776035141}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:32,341] Trial 2900 finished with value: 0.9474968655348333 and parameters: {'weight_class_0': 0.06683260031913775, 'weight_class_1': 0.6642580400541294, 'weight_class_2': 0.29705928206331966}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:32,345] Trial 2899 finished with value: 0.9475357060640032 and parameters: {'weight_class_0': 0.0707255886582776, 'weight_class_1': 0.661850945720764, 'weight_class_2': 0.315478678969028}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:32,405] Trial 2902 finished with value: 0.9485539402040358 and parameters: {'weight_class_0': 0.04044132079273682, 'weight_class_1': 1.1430633904364602, 'weight_class_2': 0.9824033551822007}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:32,413] Trial 2903 finished with value: 0.949651017950039 and parameters: {'weight_class_0': 0.09235749021031815, 'weight_class_1': 1.1412573446599237, 'weight_class_2': 0.9805993020206796}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:32,417] Trial 2901 finished with value: 0.9478882059019922 and parameters: {'weight_class_0': 0.09122836761821201, 'weight_class_1': 1.1595849392187645, 'weight_class_2': 0.43381053871246916}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:32,419] Trial 2904 finished with value: 0.9486559092395003 and parameters: {'weight_class_0': 0.04417101533000237, 'weight_class_1': 1.1801240350906945, 'weight_class_2': 1.018157409108248}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:32,512] Trial 2906 finished with value: 0.9494313660449086 and parameters: {'weight_class_0': 0.041982433680223, 'weight_class_1': 1.1659653522001328, 'weight_class_2': 0.44541951340835184}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:32,523] Trial 2907 finished with value: 0.949375642108964 and parameters: {'weight_class_0': 0.04227153201376217, 'weight_class_1': 1.2007604740800268, 'weight_class_2': 0.42740772283207495}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:32,525] Trial 2905 finished with value: 0.9473303244904717 and parameters: {'weight_class_0': 0.024195243270528455, 'weight_class_1': 0.4353032552610017, 'weight_class_2': 0.937398501877672}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:32,631] Trial 2908 finished with value: 0.9479558349429699 and parameters: {'weight_class_0': 0.04402287557395228, 'weight_class_1': 0.41399431747954485, 'weight_class_2': 1.0116137723142682}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:32,635] Trial 2909 finished with value: 0.9495394635147677 and parameters: {'weight_class_0': 0.04378795407791935, 'weight_class_1': 0.4286375446084098, 'weight_class_2': 0.4480129781997272}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:32,711] Trial 2910 finished with value: 0.9488444168630167 and parameters: {'weight_class_0': 0.042906835866675395, 'weight_class_1': 1.1146704789536959, 'weight_class_2': 0.9157071357373068}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍   | 2917/3000 [01:18<00:03, 26.86it/s]

[I 2026-07-05 15:26:32,717] Trial 2911 finished with value: 0.9487018658509672 and parameters: {'weight_class_0': 0.042181836778959786, 'weight_class_1': 1.16366485454196, 'weight_class_2': 0.9258949117788053}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:32,760] Trial 2913 finished with value: 0.9493133578698494 and parameters: {'weight_class_0': 0.025594796122414828, 'weight_class_1': 0.4328394752455403, 'weight_class_2': 0.4427411180783487}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:32,792] Trial 2914 finished with value: 0.9490847871684274 and parameters: {'weight_class_0': 0.024634702622812178, 'weight_class_1': 0.4142379154742508, 'weight_class_2': 0.48191913730002106}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:32,799] Trial 2912 finished with value: 0.9492745345676231 and parameters: {'weight_class_0': 0.026002900329035072, 'weight_class_1': 0.43056385739509656, 'weight_class_2': 0.4521092359873536}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:32,869] Trial 2917 finished with value: 0.9483035609074281 and parameters: {'weight_class_0': 0.024188082635875255, 'weight_class_1': 0.43558383893262126, 'weight_class_2': 0.6566550232237274}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:32,871] Trial 2915 finished with value: 0.9443924003806491 and parameters: {'weight_class_0': 0.0068346387079135035, 'weight_class_1': 0.4381906638052896, 'weight_class_2': 0.4514871601140744}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:32,910] Trial 2916 finished with value: 0.949198461754897 and parameters: {'weight_class_0': 0.024955739378898802, 'weight_class_1': 0.41806465104084695, 'weight_class_2': 0.4660662113243317}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋   | 2923/3000 [01:18<00:02, 28.46it/s]

[I 2026-07-05 15:26:32,932] Trial 2918 finished with value: 0.9483851687015261 and parameters: {'weight_class_0': 0.0249770308507092, 'weight_class_1': 0.5225244760312624, 'weight_class_2': 0.6674408140816618}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:32,957] Trial 2919 finished with value: 0.9491178542483643 and parameters: {'weight_class_0': 0.025036429272012405, 'weight_class_1': 0.5293160721659751, 'weight_class_2': 0.47817204882954073}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:33,005] Trial 2920 finished with value: 0.9485317789677316 and parameters: {'weight_class_0': 0.02553567416104851, 'weight_class_1': 0.5417177274991968, 'weight_class_2': 0.6647681212248787}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:33,065] Trial 2921 finished with value: 0.949130367083305 and parameters: {'weight_class_0': 0.025269214600799478, 'weight_class_1': 0.5434486596666628, 'weight_class_2': 0.4786970829959424}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:33,091] Trial 2922 finished with value: 0.949561574587058 and parameters: {'weight_class_0': 0.0540909010935696, 'weight_class_1': 0.5491462903857101, 'weight_class_2': 0.6570502042227049}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:33,121] Trial 2923 finished with value: 0.947099859195824 and parameters: {'weight_class_0': 0.01506398480751285, 'weight_class_1': 0.5860761596429682, 'weight_class_2': 0.6716845171046979}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  98%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉   | 2929/3000 [01:18<00:02, 27.77it/s]

[I 2026-07-05 15:26:33,167] Trial 2924 finished with value: 0.9475650939144961 and parameters: {'weight_class_0': 0.05049277613764015, 'weight_class_1': 0.5694855823751015, 'weight_class_2': 0.22653309078328893}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:33,260] Trial 2927 finished with value: 0.9472442093819025 and parameters: {'weight_class_0': 0.052907103226589806, 'weight_class_1': 0.5538398304294817, 'weight_class_2': 0.2262820754351432}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:33,276] Trial 2925 finished with value: 0.9494094489076063 and parameters: {'weight_class_0': 0.04871734526134734, 'weight_class_1': 0.5138806188624825, 'weight_class_2': 0.6453616911897146}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:33,278] Trial 2926 finished with value: 0.9494990184334156 and parameters: {'weight_class_0': 0.057689954346598654, 'weight_class_1': 0.5286259907896286, 'weight_class_2': 0.6801531189132479}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:33,353] Trial 2928 finished with value: 0.9488889372739598 and parameters: {'weight_class_0': 0.014728345276106962, 'weight_class_1': 0.540196115811006, 'weight_class_2': 0.20505883658168353}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:33,390] Trial 2929 finished with value: 0.9488940983757433 and parameters: {'weight_class_0': 0.014743800861653646, 'weight_class_1': 0.5182129376865506, 'weight_class_2': 0.23681228551717445}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏  | 2936/3000 [01:19<00:02, 29.21it/s]

[I 2026-07-05 15:26:33,413] Trial 2930 finished with value: 0.9490083623101517 and parameters: {'weight_class_0': 0.05463680328287259, 'weight_class_1': 0.5708285952027582, 'weight_class_2': 0.3834069940563759}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:33,460] Trial 2931 finished with value: 0.9464960834824728 and parameters: {'weight_class_0': 0.055903538777100255, 'weight_class_1': 0.5650735552332882, 'weight_class_2': 0.21494423550002675}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:33,462] Trial 2932 finished with value: 0.9473252327956129 and parameters: {'weight_class_0': 0.054219953380073925, 'weight_class_1': 0.8554516877049902, 'weight_class_2': 0.23356760441201851}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:33,490] Trial 2933 finished with value: 0.9491162807076438 and parameters: {'weight_class_0': 0.0541034268279484, 'weight_class_1': 0.9401507200508913, 'weight_class_2': 0.37111088254651026}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:33,553] Trial 2934 finished with value: 0.9487365161616336 and parameters: {'weight_class_0': 0.06138971623641487, 'weight_class_1': 0.8971017051004163, 'weight_class_2': 0.3614990771866289}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:33,565] Trial 2935 finished with value: 0.9495455915037936 and parameters: {'weight_class_0': 0.03639661981182725, 'weight_class_1': 0.9581021507675157, 'weight_class_2': 0.39640497348971115}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:33,593] Trial 2936 finished with value: 0.9481637744561912 and parameters: {'weight_class_0': 0.05621604303539505, 'weight_class_1': 2.004963622519945, 'weight_class_2': 0.3443331569169564}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:33,683] Trial 2937 finished with value: 0.947768643925155 and parameters: {'weight_class_0': 0.019729382338702358, 'weight_class_1': 0.9680535493313862, 'weight_class_2': 0.3734824708650762}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:33,693] Trial 2938 finished with value: 0.9494453041472277 and parameters: {'weight_class_0': 0.03476994515747629, 'weight_class_1': 0.9665735613359279, 'weight_class_2': 0.37567797945606346}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:33,737] Trial 2940 finished with value: 0.949683054464617 and parameters: {'weight_class_0': 0.035692133142145636, 'weight_class_1': 0.8101348301848232, 'weight_class_2': 0.3910043678918992}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:33,762] Trial 2939 finished with value: 0.9494386338102561 and parameters: {'weight_class_0': 0.03529318636570411, 'weight_class_1': 0.9549170943834345, 'weight_class_2': 0.3736539332253605}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:33,789] Trial 2941 finished with value: 0.9481275668404202 and parameters: {'weight_class_0': 0.01958449855669723, 'weight_class_1': 0.8972561379221835, 'weight_class_2': 0.34400543555864416}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:33,790] Trial 2942 finished with value: 0.9476707964335401 and parameters: {'weight_class_0': 0.034019466873904, 'weight_class_1': 1.7847391077594195, 'weight_class_2': 0.5423410336349268}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:33,864] Trial 2943 finished with value: 0.949682617082055 and parameters: {'weight_class_0': 0.03537749586037383, 'weight_class_1': 0.7999044150273168, 'weight_class_2': 0.37976554708377197}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊  | 2949/3000 [01:19<00:01, 26.97it/s]

[I 2026-07-05 15:26:33,871] Trial 2944 finished with value: 0.9482221388044336 and parameters: {'weight_class_0': 0.03659962516644501, 'weight_class_1': 1.7601507696799255, 'weight_class_2': 0.37226260844519443}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:33,878] Trial 2945 finished with value: 0.9495033444377284 and parameters: {'weight_class_0': 0.03720912727366936, 'weight_class_1': 0.9418495639180089, 'weight_class_2': 0.3586292023893294}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:33,950] Trial 2946 finished with value: 0.8787052457923897 and parameters: {'weight_class_0': 0.020329248755914867, 'weight_class_1': 0.0038383682933643185, 'weight_class_2': 0.5406670475426847}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:33,953] Trial 2947 finished with value: 0.9478314387571046 and parameters: {'weight_class_0': 0.03473281068989656, 'weight_class_1': 1.7684246131023462, 'weight_class_2': 0.539833326488753}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:33,958] Trial 2948 finished with value: 0.9493834395623142 and parameters: {'weight_class_0': 0.03484860993455343, 'weight_class_1': 0.8057488619361037, 'weight_class_2': 0.5345795612631321}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:34,123] Trial 2951 finished with value: 0.9496768169152129 and parameters: {'weight_class_0': 0.041009876386259386, 'weight_class_1': 0.7540755365143764, 'weight_class_2': 0.5331724981704733}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:34,134] Trial 2949 finished with value: 0.9470722723252191 and parameters: {'weight_class_0': 0.03754113940383659, 'weight_class_1': 0.7568100975605904, 'weight_class_2': 1.7104247862844}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:34,139] Trial 2950 finished with value: 0.9479809932457416 and parameters: {'weight_class_0': 0.03573655053891594, 'weight_class_1': 1.7786787726253275, 'weight_class_2': 0.49067587475575}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:34,155] Trial 2952 finished with value: 0.9287018374674876 and parameters: {'weight_class_0': 0.041604802003751024, 'weight_class_1': 0.6622440769669173, 'weight_class_2': 6.928440678114069}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:34,212] Trial 2954 finished with value: 0.9497594163696098 and parameters: {'weight_class_0': 0.0438393822192559, 'weight_class_1': 0.6577301844325738, 'weight_class_2': 0.512173183272754}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:34,236] Trial 2953 finished with value: 0.9497535764879007 and parameters: {'weight_class_0': 0.04235147747696082, 'weight_class_1': 0.6852018000849587, 'weight_class_2': 0.5131065008457655}. Best is trial 1121 with value: 0.94983269980651.

[I 2026-07-05 15:26:34,248] Trial 2955 finished with value: 0.94854018270832 and parameters: {'weight_class_0': 0.08047923980720649, 'weight_class_1': 0.6714025677458739, 'weight_class_2': 1.3483999714405792}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:34,358] Trial 2956 finished with value: 0.9484498379905352 and parameters: {'weight_class_0': 0.043091353327954926, 'weight_class_1': 0.2638734842469869, 'weight_class_2': 0.5293614504028762}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:34,373] Trial 2957 finished with value: 0.9496030904361509 and parameters: {'weight_class_0': 0.02907624262085428, 'weight_class_1': 0.6594654523763642, 'weight_class_2': 0.27058086022135713}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:34,397] Trial 2958 finished with value: 0.9480780758100847 and parameters: {'weight_class_0': 0.043888479998469496, 'weight_class_1': 0.2671602801356904, 'weight_class_2': 0.2686709856261867}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:34,432] Trial 2959 finished with value: 0.9386913095676811 and parameters: {'weight_class_0': 0.08048146603911976, 'weight_class_1': 6.56987170587833, 'weight_class_2': 0.2696747145858698}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:34,469] Trial 2960 finished with value: 0.9478621717424286 and parameters: {'weight_class_0': 0.04428867146740553, 'weight_class_1': 0.6665908594367786, 'weight_class_2': 1.290749877222705}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  99%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌ | 2966/3000 [01:20<00:01, 27.04it/s]

[I 2026-07-05 15:26:34,504] Trial 2961 finished with value: 0.9495522335112558 and parameters: {'weight_class_0': 0.02857050310397246, 'weight_class_1': 0.6669985803544949, 'weight_class_2': 0.2684745229993618}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:34,576] Trial 2962 finished with value: 0.9494622255521813 and parameters: {'weight_class_0': 0.02999598583056575, 'weight_class_1': 0.2639810893253152, 'weight_class_2': 0.2836337164018218}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:34,619] Trial 2964 finished with value: 0.9496271615930799 and parameters: {'weight_class_0': 0.02864059110063103, 'weight_class_1': 0.4485539232344881, 'weight_class_2': 0.24966034513289792}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:34,628] Trial 2963 finished with value: 0.9495637439563546 and parameters: {'weight_class_0': 0.02964685827512455, 'weight_class_1': 0.33362010188427454, 'weight_class_2': 0.25929873592205993}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:34,686] Trial 2965 finished with value: 0.9496881563528928 and parameters: {'weight_class_0': 0.02857920402365726, 'weight_class_1': 0.46045973354137976, 'weight_class_2': 0.27152493026042174}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:34,747] Trial 2966 finished with value: 0.9496197891687478 and parameters: {'weight_class_0': 0.028728944190213546, 'weight_class_1': 0.32125490763013187, 'weight_class_2': 0.2574996291916323}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  99%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊ | 2973/3000 [01:20<00:00, 29.35it/s]

[I 2026-07-05 15:26:34,773] Trial 2967 finished with value: 0.9492304918549958 and parameters: {'weight_class_0': 0.02879858519473776, 'weight_class_1': 0.33381701000729413, 'weight_class_2': 0.43236742795081884}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:34,780] Trial 2968 finished with value: 0.9490379152728855 and parameters: {'weight_class_0': 0.06354181616473738, 'weight_class_1': 0.4562743542087769, 'weight_class_2': 0.6984992920749454}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:34,824] Trial 2970 finished with value: 0.9477802758714642 and parameters: {'weight_class_0': 0.02912677583398625, 'weight_class_1': 0.37177331100189936, 'weight_class_2': 0.8129313391433339}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:34,857] Trial 2971 finished with value: 0.9482716396046488 and parameters: {'weight_class_0': 0.06377953548244024, 'weight_class_1': 0.347321625445983, 'weight_class_2': 0.7322336962456849}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:34,869] Trial 2969 finished with value: 0.8570121197760274 and parameters: {'weight_class_0': 0.02888453438609373, 'weight_class_1': 0.4863049200040816, 'weight_class_2': 0.0014635704450199649}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:34,884] Trial 2972 finished with value: 0.9477224854723465 and parameters: {'weight_class_0': 0.031126583992705348, 'weight_class_1': 0.3480657757738361, 'weight_class_2': 0.8438890497705248}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:34,936] Trial 2974 finished with value: 0.9481225408485668 and parameters: {'weight_class_0': 0.06484983213231162, 'weight_class_1': 0.3514549951374456, 'weight_class_2': 0.8262654762937333}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833:  99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ | 2979/3000 [01:20<00:00, 28.55it/s]

[I 2026-07-05 15:26:34,945] Trial 2973 finished with value: 0.9481931914217384 and parameters: {'weight_class_0': 0.06519449786143107, 'weight_class_1': 0.3663110297803673, 'weight_class_2': 0.815810452400657}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:35,007] Trial 2975 finished with value: 0.8277344502085704 and parameters: {'weight_class_0': 0.06252819062615889, 'weight_class_1': 0.0019277124577060066, 'weight_class_2': 0.8218037761739452}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:35,075] Trial 2977 finished with value: 0.9489518844322081 and parameters: {'weight_class_0': 0.0633699719079472, 'weight_class_1': 0.501017070907452, 'weight_class_2': 0.8419461541246804}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:35,080] Trial 2976 finished with value: 0.9488470445742849 and parameters: {'weight_class_0': 0.06060405963281511, 'weight_class_1': 0.46997376472280855, 'weight_class_2': 0.8186679246689951}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:35,152] Trial 2978 finished with value: 0.8347478389760637 and parameters: {'weight_class_0': 0.0669844072279492, 'weight_class_1': 0.0019523931851219388, 'weight_class_2': 0.7231139812709424}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍| 2986/3000 [01:20<00:00, 28.41it/s]

[I 2026-07-05 15:26:35,221] Trial 2980 finished with value: 0.9494320466008368 and parameters: {'weight_class_0': 0.05075335968027407, 'weight_class_1': 0.6070176843165295, 'weight_class_2': 0.4155856844630468}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:35,231] Trial 2979 finished with value: 0.9489701759552799 and parameters: {'weight_class_0': 0.0643382658005128, 'weight_class_1': 1.3373757675264426, 'weight_class_2': 0.4324419696282983}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:35,267] Trial 2982 finished with value: 0.9487337965217396 and parameters: {'weight_class_0': 0.020497981314839805, 'weight_class_1': 0.6244687246777603, 'weight_class_2': 0.43107352324946857}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:35,268] Trial 2981 finished with value: 0.9463794015470084 and parameters: {'weight_class_0': 0.02186688287663638, 'weight_class_1': 1.4119063927936748, 'weight_class_2': 0.4325556243185375}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:35,302] Trial 2984 finished with value: 0.9467287425850809 and parameters: {'weight_class_0': 0.1065767180303495, 'weight_class_1': 0.7991716294883672, 'weight_class_2': 0.4282842149151972}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:35,330] Trial 2983 finished with value: 0.9464534745881616 and parameters: {'weight_class_0': 0.10308526226255361, 'weight_class_1': 0.6081878787037359, 'weight_class_2': 0.43427770484229916}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:35,337] Trial 2985 finished with value: 0.9472272763632613 and parameters: {'weight_class_0': 0.10576858323137513, 'weight_class_1': 1.4093780715424016, 'weight_class_2': 0.4480759663110966}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:35,412] Trial 2988 finished with value: 0.9470499105759395 and parameters: {'weight_class_0': 0.10366843564021364, 'weight_class_1': 1.3251791027930797, 'weight_class_2': 0.4257901607438805}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊| 2995/3000 [01:21<00:00, 30.05it/s]

[I 2026-07-05 15:26:35,416] Trial 2986 finished with value: 0.9463850902186248 and parameters: {'weight_class_0': 0.02156685203646661, 'weight_class_1': 1.3882067987002398, 'weight_class_2': 0.42733800805750993}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:35,422] Trial 2987 finished with value: 0.9487155724529219 and parameters: {'weight_class_0': 0.021418889917313437, 'weight_class_1': 0.6396374233874943, 'weight_class_2': 0.45596657533108376}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:35,545] Trial 2990 finished with value: 0.9469335366551016 and parameters: {'weight_class_0': 0.0960085158445066, 'weight_class_1': 0.6082587872582177, 'weight_class_2': 0.4311309383851576}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:35,551] Trial 2989 finished with value: 0.9464498279907859 and parameters: {'weight_class_0': 0.021492236937033237, 'weight_class_1': 1.3656393684761718, 'weight_class_2': 0.4340433641393805}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:35,573] Trial 2991 finished with value: 0.9479852726385114 and parameters: {'weight_class_0': 0.021393806510123, 'weight_class_1': 0.7751878868898643, 'weight_class_2': 0.6021669172536147}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:35,638] Trial 2992 finished with value: 0.9496928289544715 and parameters: {'weight_class_0': 0.04522568507238481, 'weight_class_1': 0.797659452305016, 'weight_class_2': 0.5938769356148558}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:35,645] Trial 2994 finished with value: 0.9496468693898953 and parameters: {'weight_class_0': 0.04868903309802747, 'weight_class_1': 1.018931468313837, 'weight_class_2': 0.6135930151484809}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:35,651] Trial 2993 finished with value: 0.9496776406447447 and parameters: {'weight_class_0': 0.04669012212396923, 'weight_class_1': 0.8285902913003957, 'weight_class_2': 0.6141676239094606}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:35,677] Trial 2995 finished with value: 0.9495845086123849 and parameters: {'weight_class_0': 0.045382737344014254, 'weight_class_1': 0.756278233647971, 'weight_class_2': 0.6367162663276539}. Best is trial 1121 with value: 0.94983269980651.

Best trial: 1121. Best value: 0.949833: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3000/3000 [01:21<00:00, 36.97it/s]

[I 2026-07-05 15:26:35,687] Trial 2996 finished with value: 0.9496470799240061 and parameters: {'weight_class_0': 0.04581544802148492, 'weight_class_1': 0.8322979390618235, 'weight_class_2': 0.614038286656948}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:35,703] Trial 2997 finished with value: 0.9497240156797141 and parameters: {'weight_class_0': 0.04813969599366262, 'weight_class_1': 0.7996590221237957, 'weight_class_2': 0.6106022103929949}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:35,718] Trial 2999 finished with value: 0.9497334988722282 and parameters: {'weight_class_0': 0.048702452159894306, 'weight_class_1': 0.793501204992805, 'weight_class_2': 0.6106078563186682}. Best is trial 1121 with value: 0.94983269980651.
[I 2026-07-05 15:26:35,722] Trial 2998 finished with value: 0.9495680998972248 and parameters: {'weight_class_0': 0.04581112284330318, 'weight_class_1': 0.7983860802755921, 'weight_class_2': 0.6319808519356177}. Best is trial 1121 with value: 0.94983269980651.

Best trial score:
0.94983269980651

Best params:
{'weight_class_0': 0.03196866600351773, 'weight_class_1': 0.532014214601177, 'weight_class_2': 0.37592965629852965}

In [8]:
weights = np.array([study.best_params['weight_class_0'], study.best_params['weight_class_1'], study.best_params['weight_class_2']])
weighted_probas = X_test.loc[:, ['xgb_0', 'xgb_1', 'xgb_2']].to_numpy() * weights

pred = np.argmax(weighted_probas, axis=1)

In [9]:
sub_labels = label_encoder.inverse_transform(pred)

# Submission

In [10]:
submission = pd.read_csv('../data/submission/sample_submission.csv')
submission['health_condition'] = sub_labels

submission.to_csv('../data/submission/submission_from_5.0.2_xgboost_submission.csv', index=False)

In [11]:
submission.head()

       id health_condition
0  690088        unhealthy
1  690089        unhealthy
2  690090          at-risk
3  690091          at-risk
4  690092        unhealthy