# Imports

In [25]:
import optuna
import pickle

import numpy as np
import pandas as pd

from tqdm import tqdm

from sklearn.metrics import balanced_accuracy_score
from sklearn.model_selection import StratifiedKFold, cross_val_predict

## Utils

In [26]:
def load_pickle(file_path):
    with open(file_path, 'rb') as file:
        return pickle.load(file)

# Loading Datasets

In [27]:
X_train = pd.read_parquet('../data/processed/X_train_stacking_layer_one.parquet')
y_train = pd.read_parquet('../data/interim/y_train.parquet')

X_test = pd.read_parquet('../data/processed/X_test_stacking_layer_one.parquet')

In [28]:
X_train.head()

     lgbm_0    lgbm_1    lgbm_2     xgb_0     xgb_1     xgb_2
0  0.004922  0.001773  0.993304  0.004134  0.002593  0.993273
1  0.997228  0.000463  0.002309  0.995591  0.000405  0.004004
2  0.002369  0.000604  0.997026  0.001958  0.000503  0.997538
3  0.004656  0.003362  0.991982  0.002466  0.002391  0.995142
4  0.995353  0.000016  0.004632  0.994178  0.000003  0.005819

In [29]:
X_test.head()

     lgbm_0    lgbm_1    lgbm_2     xgb_0     xgb_1     xgb_2
0  0.012452  0.003199  0.984349  0.011048  0.004491  0.984461
1  0.472116  0.002331  0.525553  0.499186  0.001896  0.498918
2  0.998690  0.001012  0.000298  0.997826  0.001594  0.000579
3  0.980854  0.000018  0.019128  0.987434  0.000009  0.012557
4  0.006765  0.001847  0.991388  0.006876  0.001972  0.991152

# Machine Learning

In [30]:
label_encoder = load_pickle('../artifacts/label_encoder.pkl')

In [31]:
def objective(trial, X, y):

    w0 = trial.suggest_float('weight_class_0', 0.001, 10.0, log=True)
    w1 = trial.suggest_float('weight_class_1', 0.001, 10.0, log=True)
    w2 = trial.suggest_float('weight_class_2', 0.001, 10.0, log=True)
    weights = np.array([w0, w1, w2])

    proba = X.loc[:, ['xgb_0', 'xgb_1', 'xgb_2']].to_numpy()
    
    weighted_probas = proba * weights
    pred = np.argmax(weighted_probas, axis=1)
    
    score = balanced_accuracy_score(y, pred)

    return score


study = optuna.create_study(
    direction="maximize", 
    sampler=optuna.samplers.TPESampler(seed=42), 
    pruner=optuna.pruners.MedianPruner(n_warmup_steps=2)
)

study.optimize(
    lambda trial: objective(trial, X_train, y_train.health_condition), 
    n_trials=3000, 
    n_jobs=-1, 
    show_progress_bar=True
)

print("\nBest trial score:")
print(study.best_trial.value)

print("\nBest params:")
print(study.best_trial.params)

[I 2026-07-03 10:56:23,851] A new study created in memory with name: no-name-d9b36f9c-5c10-4462-b0b8-cb76e6fa4e20
Best trial: 4. Best value: 0.948606:   0%|▍                                                                                                                                      | 11/3000 [00:00<01:30, 33.04it/s]

[I 2026-07-03 10:56:23,989] Trial 2 finished with value: 0.6653171354734482 and parameters: {'weight_class_0': 3.4734616757219596, 'weight_class_1': 3.805816637382215, 'weight_class_2': 0.006173677388354917}. Best is trial 2 with value: 0.6653171354734482.
[I 2026-07-03 10:56:23,990] Trial 0 finished with value: 0.9484115427310996 and parameters: {'weight_class_0': 0.007850442713920384, 'weight_class_1': 0.04462153966419699, 'weight_class_2': 0.091764862578854}. Best is trial 0 with value: 0.9484115427310996.
[I 2026-07-03 10:56:24,012] Trial 6 finished with value: 0.8273813024977928 and parameters: {'weight_class_0': 0.8593937614935693, 'weight_class_1': 0.2919638274421619, 'weight_class_2': 0.037978709952975344}. Best is trial 0 with value: 0.9484115427310996.
[I 2026-07-03 10:56:24,013] Trial 7 finished with value: 0.9202340536455934 and parameters: {'weight_class_0': 0.0015290766017109277, 'weight_class_1': 0.024051289610042364, 'weight_class_2': 0.27459538655705307}. Best is trial 0 with value: 0.9484115427310996.
[I 2026-07-03 10:56:24,014] Trial 5 finished with value: 0.7141100184173891 and parameters: {'weight_class_0': 0.001797133772109571, 'weight_class_1': 0.052914754133989265, 'weight_class_2': 1.8379596916035115}. Best is trial 0 with value: 0.9484115427310996.
[I 2026-07-03 10:56:24,023] Trial 4 finished with value: 0.948605793512619 and parameters: {'weight_class_0': 0.0018240713825550682, 'weight_class_1': 0.062261970738105694, 'weight_class_2': 0.031109392274745996}. Best is trial 4 with value: 0.948605793512619.
[I 2026-07-03 10:56:24,037] Trial 3 finished with value: 0.7146859398040033 and parameters: {'weight_class_0': 1.3488285597014735, 'weight_class_1': 0.012537222059720469, 'weight_class_2': 0.4092118050837507}. Best is trial 4 with value: 0.948605793512619.
[I 2026-07-03 10:56:24,040] Trial 8 finished with value: 0.7334911037346837 and parameters: {'weight_class_0': 1.283773497849909, 'weight_class_1': 9.717797342842385, 'weight_class_2': 0.008861637557973116}. Best is trial 4 with value: 0.948605793512619.
[I 2026-07-03 10:56:24,053] Trial 1 finished with value: 0.6972740112189362 and parameters: {'weight_class_0': 0.0742679106109334, 'weight_class_1': 0.0011134643266220011, 'weight_class_2': 4.0595409545842}. Best is trial 4 with value: 0.948605793512619.
[I 2026-07-03 10:56:24,060] Trial 10 finished with value: 0.9270521413423211 and parameters: {'weight_class_0': 0.0015070618104916303, 'weight_class_1': 0.002885707964473838, 'weight_class_2': 0.003830479615989315}. Best is trial 4 with value: 0.948605793512619.
[I 2026-07-03 10:56:24,068] Trial 11 finished with value: 0.7820524230410374 and parameters: {'weight_class_0': 1.6932956434768627, 'weight_class_1': 0.03167375236358593, 'weight_class_2': 0.08601386096251631}. Best is trial 4 with value: 0.948605793512619.
[I 2026-07-03 10:56:24,084] Trial 9 finished with value: 0.7534723181553312 and parameters: {'weight_class_0': 7.123632314480265, 'weight_class_1': 0.09571601824416216, 'weight_class_2': 0.3934525734129021}. Best is trial 4 with value: 0.948605793512619.

[I 2026-07-03 10:56:24,128] Trial 12 finished with value: 0.5896562075934612 and parameters: {'weight_class_0': 4.699477916065641, 'weight_class_1': 0.0020871173027371677, 'weight_class_2': 2.4344377438591183}. Best is trial 4 with value: 0.948605793512619.
[I 2026-07-03 10:56:24,141] Trial 13 finished with value: 0.7928631331878759 and parameters: {'weight_class_0': 0.09438511067175223, 'weight_class_1': 8.742955064996934, 'weight_class_2': 0.016677974448334534}. Best is trial 4 with value: 0.948605793512619.
[I 2026-07-03 10:56:24,159] Trial 15 finished with value: 0.9277510167373487 and parameters: {'weight_class_0': 0.21650747929846784, 'weight_class_1': 0.3182147368967358, 'weight_class_2': 5.495229189107336}. Best is trial 4 with value: 0.948605793512619.
[I 2026-07-03 10:56:24,162] Trial 14 finished with value: 0.6277953319656032 and parameters: {'weight_class_0': 4.534451800751583, 'weight_class_1': 7.762586509773331, 'weight_class_2': 0.0011783082208558933}. Best is trial 4 with value: 0.948605793512619.
[I 2026-07-03 10:56:24,196] Trial 16 finished with value: 0.9388437036728913 and parameters: {'weight_class_0': 0.012003348252836409, 'weight_class_1': 0.5368445983391653, 'weight_class_2': 0.030491074678642767}. Best is trial 4 with value: 0.948605793512619.
[I 2026-07-03 10:56:24,214] Trial 17 finished with value: 0.941602088223258 and parameters: {'weight_class_0': 0.01354851900939132, 'weight_class_1': 0.5038662280047472, 'weight_class_2': 0.038405355232202044}. Best is trial 4 with value: 0.948605793512619.
[I 2026-07-03 10:56:24,232] Trial 18 finished with value: 0.9386043801187846 and parameters: {'weight_class_0': 0.013880039399076421, 'weight_class_1': 0.492679720969267, 'weight_class_2': 0.0336008452527317}. Best is trial 4 with value: 0.948605793512619.
[I 2026-07-03 10:56:24,252] Trial 19 finished with value: 0.9418902355955229 and parameters: {'weight_class_0': 0.010200083678527747, 'weight_class_1': 0.5349200283592811, 'weight_class_2': 0.03286583721187211}. Best is trial 4 with value: 0.948605793512619.
[I 2026-07-03 10:56:24,259] Trial 20 finished with value: 0.7785645995676078 and parameters: {'weight_class_0': 0.008158989235957497, 'weight_class_1': 0.6640194335775038, 'weight_class_2': 0.0010369698065123836}. Best is trial 4 with value: 0.948605793512619.
[I 2026-07-03 10:56:24,286] Trial 21 finished with value: 0.9409953987225209 and parameters: {'weight_class_0': 0.008515656381267483, 'weight_class_1': 0.7294102334527865, 'weight_class_2': 0.09565384208716739}. Best is trial 4 with value: 0.948605793512619.
[I 2026-07-03 10:56:24,298] Trial 22 finished with value: 0.9493049080535063 and parameters: {'weight_class_0': 0.009645791583662276, 'weight_class_1': 0.25256814662042615, 'weight_class_2': 0.08432489407510645}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:24,329] Trial 23 finished with value: 0.9132318700518279 and parameters: {'weight_class_0': 0.008387648631694748, 'weight_class_1': 0.007112571857122457, 'weight_class_2': 0.09520220461802634}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:24,344] Trial 24 finished with value: 0.9243921345198244 and parameters: {'weight_class_0': 0.006337414766352911, 'weight_class_1': 0.00805827203149778, 'weight_class_2': 0.11188916150143108}. Best is trial 22 with value: 0.9493049080535063.

Best trial: 22. Best value: 0.949305:   1%|█▌                                                                                                                                    | 36/3000 [00:00<00:54, 54.30it/s]

[I 2026-07-03 10:56:24,361] Trial 25 finished with value: 0.929242109998618 and parameters: {'weight_class_0': 0.0053803626124146655, 'weight_class_1': 0.008338980610354476, 'weight_class_2': 0.1442990775691607}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:24,381] Trial 26 finished with value: 0.9226699941616158 and parameters: {'weight_class_0': 0.005516668896020284, 'weight_class_1': 0.006849160641645899, 'weight_class_2': 0.15690555380894392}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:24,388] Trial 27 finished with value: 0.9481293916340127 and parameters: {'weight_class_0': 0.004192771774970207, 'weight_class_1': 0.14301856917801253, 'weight_class_2': 0.09210607087451052}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:24,418] Trial 29 finished with value: 0.9469339013968282 and parameters: {'weight_class_0': 0.0034578573439702567, 'weight_class_1': 0.11598514946017069, 'weight_class_2': 0.15144311569541186}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:24,428] Trial 28 finished with value: 0.9468433437188382 and parameters: {'weight_class_0': 0.0034466929814084206, 'weight_class_1': 0.12897177103442, 'weight_class_2': 0.1445897252586804}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:24,442] Trial 30 finished with value: 0.9470686716559218 and parameters: {'weight_class_0': 0.003567744175982108, 'weight_class_1': 0.11874244539640492, 'weight_class_2': 0.14883642698642172}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:24,453] Trial 31 finished with value: 0.946089646804035 and parameters: {'weight_class_0': 0.0034153365120483574, 'weight_class_1': 0.10640895476172854, 'weight_class_2': 0.19650746388991572}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:24,477] Trial 33 finished with value: 0.945733179429415 and parameters: {'weight_class_0': 0.027987521640604463, 'weight_class_1': 0.12758737545389182, 'weight_class_2': 0.7943440884949335}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:24,497] Trial 32 finished with value: 0.8773559396445852 and parameters: {'weight_class_0': 0.0029144886047673298, 'weight_class_1': 0.1207788199675185, 'weight_class_2': 0.8365206452237941}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:24,501] Trial 34 finished with value: 0.942682772746155 and parameters: {'weight_class_0': 0.03516080455338775, 'weight_class_1': 0.11513657636971321, 'weight_class_2': 1.2564992232891794}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:24,522] Trial 35 finished with value: 0.9468742576946134 and parameters: {'weight_class_0': 0.03528288174846462, 'weight_class_1': 1.6600311369274254, 'weight_class_2': 0.9432293074334033}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:24,533] Trial 36 finished with value: 0.9466096309823412 and parameters: {'weight_class_0': 0.03031385019485832, 'weight_class_1': 1.5728544935704099, 'weight_class_2': 0.6980650711773743}. Best is trial 22 with value: 0.9493049080535063.

[I 2026-07-03 10:56:24,554] Trial 37 finished with value: 0.8869950418265445 and parameters: {'weight_class_0': 0.027080771006717453, 'weight_class_1': 0.06052740078327204, 'weight_class_2': 0.012533024312720827}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:24,565] Trial 38 finished with value: 0.9467873981718148 and parameters: {'weight_class_0': 0.028895645565780906, 'weight_class_1': 1.449827567730395, 'weight_class_2': 0.6937312752995306}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:24,605] Trial 40 finished with value: 0.9310659685582671 and parameters: {'weight_class_0': 0.027042764215241457, 'weight_class_1': 1.9504083785389323, 'weight_class_2': 0.06057844378627791}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:24,605] Trial 39 finished with value: 0.8899571146954616 and parameters: {'weight_class_0': 0.029546156975651734, 'weight_class_1': 1.6796688248599325, 'weight_class_2': 0.01490765861182391}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:24,621] Trial 41 finished with value: 0.9324302961116661 and parameters: {'weight_class_0': 0.02649407802317727, 'weight_class_1': 1.695169398223029, 'weight_class_2': 0.05828734298745495}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:24,642] Trial 42 finished with value: 0.9456091585932072 and parameters: {'weight_class_0': 0.0010011272674720006, 'weight_class_1': 0.03955026958404656, 'weight_class_2': 0.05996891723584015}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:24,656] Trial 43 finished with value: 0.9479907176743789 and parameters: {'weight_class_0': 0.0019645919740295206, 'weight_class_1': 0.050738318180212474, 'weight_class_2': 0.058285226699945666}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:24,679] Trial 44 finished with value: 0.9477667149720039 and parameters: {'weight_class_0': 0.002085331579646917, 'weight_class_1': 0.023531645450051424, 'weight_class_2': 0.06020150377119146}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:24,686] Trial 46 finished with value: 0.9464069978868781 and parameters: {'weight_class_0': 0.0010774813514160062, 'weight_class_1': 0.02304926580964873, 'weight_class_2': 0.057529276465094335}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:24,698] Trial 45 finished with value: 0.9478579281813942 and parameters: {'weight_class_0': 0.0020774783261240477, 'weight_class_1': 0.026708041944796975, 'weight_class_2': 0.06134983492911087}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:24,732] Trial 47 finished with value: 0.8166270373175651 and parameters: {'weight_class_0': 0.0010250053919990303, 'weight_class_1': 0.21176587788054238, 'weight_class_2': 0.35893032352203325}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:24,756] Trial 48 finished with value: 0.9354926643395696 and parameters: {'weight_class_0': 0.002311937437821161, 'weight_class_1': 0.029952627765999985, 'weight_class_2': 0.29826700972037534}. Best is trial 22 with value: 0.9493049080535063.

Best trial: 22. Best value: 0.949305:   2%|██▊                                                                                                                                   | 62/3000 [00:01<00:50, 57.63it/s]

[I 2026-07-03 10:56:24,772] Trial 50 finished with value: 0.9270387503964931 and parameters: {'weight_class_0': 0.0023450127571642567, 'weight_class_1': 0.017942818849671322, 'weight_class_2': 0.36417779953086954}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:24,777] Trial 49 finished with value: 0.8993541675113831 and parameters: {'weight_class_0': 0.0012422008250819736, 'weight_class_1': 0.025380083563001695, 'weight_class_2': 0.289799934925565}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:24,815] Trial 51 finished with value: 0.9348468842624243 and parameters: {'weight_class_0': 0.0021826887251083556, 'weight_class_1': 0.020614327242720307, 'weight_class_2': 0.28335187326812183}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:24,817] Trial 52 finished with value: 0.8923817633990486 and parameters: {'weight_class_0': 0.0020407119083103438, 'weight_class_1': 0.2998833343299495, 'weight_class_2': 0.3868862455613046}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:24,840] Trial 53 finished with value: 0.9049487045809895 and parameters: {'weight_class_0': 0.0015642202826448913, 'weight_class_1': 0.1974585567605097, 'weight_class_2': 0.27166887975725973}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:24,859] Trial 54 finished with value: 0.9103513039695335 and parameters: {'weight_class_0': 0.06994709786865141, 'weight_class_1': 0.058548136802147446, 'weight_class_2': 0.2992199185119691}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:24,861] Trial 55 finished with value: 0.8792561736308806 and parameters: {'weight_class_0': 0.0015433115079120296, 'weight_class_1': 0.21567424046020847, 'weight_class_2': 0.35906350016114136}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:24,861] Trial 56 finished with value: 0.9443593775363648 and parameters: {'weight_class_0': 0.0016479446489973259, 'weight_class_1': 0.060886177216534734, 'weight_class_2': 0.005692259248801888}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:24,916] Trial 57 finished with value: 0.9490162259672431 and parameters: {'weight_class_0': 0.0017961391840748448, 'weight_class_1': 0.05914619289648956, 'weight_class_2': 0.02391331919955367}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:24,917] Trial 58 finished with value: 0.9488878390913044 and parameters: {'weight_class_0': 0.0016807723519144026, 'weight_class_1': 0.05927797104494037, 'weight_class_2': 0.021740416944894973}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:24,932] Trial 59 finished with value: 0.9483862431057797 and parameters: {'weight_class_0': 0.0016809986582771185, 'weight_class_1': 0.06693668841139361, 'weight_class_2': 0.025887656780516678}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:25,004] Trial 63 finished with value: 0.9489197403785372 and parameters: {'weight_class_0': 0.00440472872308965, 'weight_class_1': 0.07327151751194609, 'weight_class_2': 0.027720998514285076}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:24,982] Trial 61 finished with value: 0.9115710737620907 and parameters: {'weight_class_0': 0.016312003504959836, 'weight_class_1': 0.06463523085404237, 'weight_class_2': 0.017956815734191}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:24,987] Trial 62 finished with value: 0.9114053146786062 and parameters: {'weight_class_0': 0.018600573772831832, 'weight_class_1': 0.04049395534405944, 'weight_class_2': 0.02551228598284827}. Best is trial 22 with value: 0.9493049080535063.

Best trial: 22. Best value: 0.949305:   2%|███▎                                                                                                                                  | 74/3000 [00:01<00:47, 61.24it/s]

[I 2026-07-03 10:56:24,951] Trial 60 finished with value: 0.948004232782402 and parameters: {'weight_class_0': 0.004625030462622704, 'weight_class_1': 0.06486299307127019, 'weight_class_2': 0.02222118104996224}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:25,031] Trial 65 finished with value: 0.8787874855592469 and parameters: {'weight_class_0': 0.018124416027095847, 'weight_class_1': 0.0138977969897844, 'weight_class_2': 0.02188461301656153}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:25,051] Trial 66 finished with value: 0.9092842875114598 and parameters: {'weight_class_0': 0.016678634442838562, 'weight_class_1': 0.036434544697734904, 'weight_class_2': 0.021457706440594058}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:25,053] Trial 64 finished with value: 0.9177860257360876 and parameters: {'weight_class_0': 0.01585227378778112, 'weight_class_1': 0.04032861253186315, 'weight_class_2': 0.024071502415009664}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:25,078] Trial 67 finished with value: 0.8865918601896517 and parameters: {'weight_class_0': 0.017141624080211422, 'weight_class_1': 0.013522804115287305, 'weight_class_2': 0.025361372546684257}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:25,099] Trial 68 finished with value: 0.9415276829706744 and parameters: {'weight_class_0': 0.004659077048822017, 'weight_class_1': 0.01383427625489379, 'weight_class_2': 0.020752395088728358}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:25,104] Trial 69 finished with value: 0.9440847936520417 and parameters: {'weight_class_0': 0.004386204247166603, 'weight_class_1': 0.0150076131731492, 'weight_class_2': 0.022820669477781573}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:25,142] Trial 70 finished with value: 0.9109683385652424 and parameters: {'weight_class_0': 0.006348263249186665, 'weight_class_1': 0.01359470141106134, 'weight_class_2': 0.008651758324639554}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:25,152] Trial 71 finished with value: 0.9146213999488572 and parameters: {'weight_class_0': 0.0066554943308881655, 'weight_class_1': 0.012019711315734264, 'weight_class_2': 0.011313510899654041}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:25,187] Trial 72 finished with value: 0.9278096167447071 and parameters: {'weight_class_0': 0.005832995292955151, 'weight_class_1': 0.1673245648758483, 'weight_class_2': 0.0095297446812881}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:25,188] Trial 73 finished with value: 0.9316139737595005 and parameters: {'weight_class_0': 0.005198245684389407, 'weight_class_1': 0.09045749145829751, 'weight_class_2': 0.009439873560764216}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:25,191] Trial 74 finished with value: 0.9123875874993314 and parameters: {'weight_class_0': 0.007063127372886656, 'weight_class_1': 0.0830269045917109, 'weight_class_2': 0.007281199974473139}. Best is trial 22 with value: 0.9493049080535063.

Best trial: 22. Best value: 0.949305:   3%|███▉                                                                                                                                  | 87/3000 [00:01<00:50, 57.33it/s]

[I 2026-07-03 10:56:25,218] Trial 75 finished with value: 0.9307479812621425 and parameters: {'weight_class_0': 0.00614123713492686, 'weight_class_1': 0.08872628798451826, 'weight_class_2': 0.0107700181908375}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:25,241] Trial 76 finished with value: 0.8130004164792469 and parameters: {'weight_class_0': 0.4881953602042178, 'weight_class_1': 0.0822163963737565, 'weight_class_2': 0.009762800729406631}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:25,256] Trial 78 finished with value: 0.9192431143783885 and parameters: {'weight_class_0': 0.006959063633824883, 'weight_class_1': 0.07587726258594711, 'weight_class_2': 0.008738778233787312}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:25,260] Trial 77 finished with value: 0.9270000575132297 and parameters: {'weight_class_0': 0.006827171253147182, 'weight_class_1': 0.0847282160309576, 'weight_class_2': 0.010710518527333375}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:25,282] Trial 79 finished with value: 0.947844320577893 and parameters: {'weight_class_0': 0.009178425251942098, 'weight_class_1': 0.07979972069493865, 'weight_class_2': 0.044042173586953684}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:25,285] Trial 80 finished with value: 0.9489677326521612 and parameters: {'weight_class_0': 0.0028084434044388174, 'weight_class_1': 0.0881157434155716, 'weight_class_2': 0.04026428342698362}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:25,315] Trial 82 finished with value: 0.9462950354049048 and parameters: {'weight_class_0': 0.0028729777174736283, 'weight_class_1': 0.16836867859070082, 'weight_class_2': 0.0440286618879408}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:25,317] Trial 81 finished with value: 0.9456726651436167 and parameters: {'weight_class_0': 0.010521538596580948, 'weight_class_1': 0.08524773141087541, 'weight_class_2': 0.03822703970341711}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:25,337] Trial 83 finished with value: 0.946406358434368 and parameters: {'weight_class_0': 0.009985686703975346, 'weight_class_1': 0.07094042933901508, 'weight_class_2': 0.040716689353581796}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:25,357] Trial 84 finished with value: 0.9463165004031483 and parameters: {'weight_class_0': 0.002928082962106579, 'weight_class_1': 0.17225801598687304, 'weight_class_2': 0.041421497667377793}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:25,393] Trial 85 finished with value: 0.9221030057321381 and parameters: {'weight_class_0': 0.002810828934003905, 'weight_class_1': 0.3953402047343471, 'weight_class_2': 0.03755919971622997}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:25,393] Trial 86 finished with value: 0.9314909488829715 and parameters: {'weight_class_0': 0.0030206539674644153, 'weight_class_1': 0.3504239035004261, 'weight_class_2': 0.04712517222901402}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:25,403] Trial 87 finished with value: 0.9238140537583694 and parameters: {'weight_class_0': 0.0028090224204503815, 'weight_class_1': 0.3836385800903051, 'weight_class_2': 0.04328579311856521}. Best is trial 22 with value: 0.9493049080535063.

Best trial: 22. Best value: 0.949305:   3%|████▍                                                                                                                                | 100/3000 [00:01<00:48, 60.00it/s]

[I 2026-07-03 10:56:25,440] Trial 88 finished with value: 0.9301188393300248 and parameters: {'weight_class_0': 0.0034013148183974266, 'weight_class_1': 0.40787937111854417, 'weight_class_2': 0.043169697876306944}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:25,447] Trial 89 finished with value: 0.9479412567796013 and parameters: {'weight_class_0': 0.0034149583806601215, 'weight_class_1': 0.16035861088486178, 'weight_class_2': 0.04274740903407303}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:25,469] Trial 91 finished with value: 0.9472301066575904 and parameters: {'weight_class_0': 0.003297537301449718, 'weight_class_1': 0.15110895214749273, 'weight_class_2': 0.07924130157481622}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:25,473] Trial 90 finished with value: 0.947976754935982 and parameters: {'weight_class_0': 0.002711328692988551, 'weight_class_1': 0.049909005127185734, 'weight_class_2': 0.08310665782802408}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:25,480] Trial 92 finished with value: 0.9436412909328364 and parameters: {'weight_class_0': 0.0013593619156854668, 'weight_class_1': 0.0489103166326099, 'weight_class_2': 0.11307303620841129}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:25,510] Trial 93 finished with value: 0.9360605888545338 and parameters: {'weight_class_0': 0.003652965221770299, 'weight_class_1': 0.3730392435639719, 'weight_class_2': 0.08019542409911906}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:25,540] Trial 94 finished with value: 0.9448855494729553 and parameters: {'weight_class_0': 0.0012321375628523434, 'weight_class_1': 0.0496660036142004, 'weight_class_2': 0.08532205845248549}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:25,541] Trial 95 finished with value: 0.9476601146381215 and parameters: {'weight_class_0': 0.003924882640298353, 'weight_class_1': 0.04625317153353223, 'weight_class_2': 0.11904677109738092}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:25,556] Trial 96 finished with value: 0.9455196667824347 and parameters: {'weight_class_0': 0.0013142550721616548, 'weight_class_1': 0.05095924146959113, 'weight_class_2': 0.08141477421152246}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:25,592] Trial 97 finished with value: 0.9454238127936659 and parameters: {'weight_class_0': 0.0012580989482650006, 'weight_class_1': 0.05287262464936461, 'weight_class_2': 0.07624355061351121}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:25,596] Trial 98 finished with value: 0.9456074091942154 and parameters: {'weight_class_0': 0.001273195533767762, 'weight_class_1': 0.04262392943826787, 'weight_class_2': 0.08132666416479249}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:25,628] Trial 100 finished with value: 0.9487780659645328 and parameters: {'weight_class_0': 0.004324184580244837, 'weight_class_1': 0.03252577688872728, 'weight_class_2': 0.02960386663669415}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:25,632] Trial 99 finished with value: 0.9448049124946434 and parameters: {'weight_class_0': 0.004011733127298169, 'weight_class_1': 0.261857156780023, 'weight_class_2': 0.028505773886260355}. Best is trial 22 with value: 0.9493049080535063.

Best trial: 109. Best value: 0.949641:   4%|████▉                                                                                                                               | 111/3000 [00:02<00:49, 57.85it/s]

[I 2026-07-03 10:56:25,652] Trial 101 finished with value: 0.9452747113813579 and parameters: {'weight_class_0': 0.004402827025290707, 'weight_class_1': 0.2706963292053895, 'weight_class_2': 0.030085611949187577}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:25,668] Trial 102 finished with value: 0.8948371381993016 and parameters: {'weight_class_0': 0.0012120886681266179, 'weight_class_1': 0.24899675375004104, 'weight_class_2': 0.02981721029373377}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:25,675] Trial 103 finished with value: 0.9464967535198302 and parameters: {'weight_class_0': 0.001842210108005462, 'weight_class_1': 0.10635540164148732, 'weight_class_2': 0.015682732981186363}. Best is trial 22 with value: 0.9493049080535063.
[I 2026-07-03 10:56:25,692] Trial 104 finished with value: 0.9495861755285979 and parameters: {'weight_class_0': 0.0016856382914038361, 'weight_class_1': 0.03358930293707314, 'weight_class_2': 0.01487179112413961}. Best is trial 104 with value: 0.9495861755285979.
[I 2026-07-03 10:56:25,703] Trial 105 finished with value: 0.9495822302087937 and parameters: {'weight_class_0': 0.0016735557527058772, 'weight_class_1': 0.03377934338240654, 'weight_class_2': 0.01430879946673124}. Best is trial 104 with value: 0.9495861755285979.
[I 2026-07-03 10:56:25,732] Trial 106 finished with value: 0.9490897277488702 and parameters: {'weight_class_0': 0.0016807293653869045, 'weight_class_1': 0.032515407980570545, 'weight_class_2': 0.0300833940741249}. Best is trial 104 with value: 0.9495861755285979.
[I 2026-07-03 10:56:25,760] Trial 107 finished with value: 0.4689047866427991 and parameters: {'weight_class_0': 9.994195830503932, 'weight_class_1': 0.03427938865270586, 'weight_class_2': 0.029020496285191832}. Best is trial 104 with value: 0.9495861755285979.
[I 2026-07-03 10:56:25,766] Trial 109 finished with value: 0.9496405873168569 and parameters: {'weight_class_0': 0.0017247421783998958, 'weight_class_1': 0.032534212051250753, 'weight_class_2': 0.015047363806991202}. Best is trial 109 with value: 0.9496405873168569.
[I 2026-07-03 10:56:25,778] Trial 108 finished with value: 0.949577472742695 and parameters: {'weight_class_0': 0.0018076129665150888, 'weight_class_1': 0.03249074788793503, 'weight_class_2': 0.016112044787591408}. Best is trial 109 with value: 0.9496405873168569.
[I 2026-07-03 10:56:25,807] Trial 110 finished with value: 0.949241506265877 and parameters: {'weight_class_0': 0.0018420116998282277, 'weight_class_1': 0.03142409017728296, 'weight_class_2': 0.01317476148869227}. Best is trial 109 with value: 0.9496405873168569.
[I 2026-07-03 10:56:25,812] Trial 111 finished with value: 0.9487120349801385 and parameters: {'weight_class_0': 0.002442720491876349, 'weight_class_1': 0.032141167973813764, 'weight_class_2': 0.013917574073092995}. Best is trial 109 with value: 0.9496405873168569.

Best trial: 127. Best value: 0.949653:   4%|█████▌                                                                                                                              | 125/3000 [00:02<00:47, 60.10it/s]

[I 2026-07-03 10:56:25,831] Trial 112 finished with value: 0.9402279645747265 and parameters: {'weight_class_0': 0.012408935010952351, 'weight_class_1': 0.029526130041859267, 'weight_class_2': 0.1971028070213998}. Best is trial 109 with value: 0.9496405873168569.
[I 2026-07-03 10:56:25,847] Trial 113 finished with value: 0.40499497871641044 and parameters: {'weight_class_0': 9.873664393235586, 'weight_class_1': 0.03053537541143526, 'weight_class_2': 0.013632158865060744}. Best is trial 109 with value: 0.9496405873168569.
[I 2026-07-03 10:56:25,863] Trial 114 finished with value: 0.9495559021936085 and parameters: {'weight_class_0': 0.0015868995340969786, 'weight_class_1': 0.032404267680491095, 'weight_class_2': 0.01813005919206066}. Best is trial 109 with value: 0.9496405873168569.
[I 2026-07-03 10:56:25,893] Trial 116 finished with value: 0.9487660341198575 and parameters: {'weight_class_0': 0.002477916285930978, 'weight_class_1': 0.02860907081631257, 'weight_class_2': 0.014424074108828821}. Best is trial 109 with value: 0.9496405873168569.
[I 2026-07-03 10:56:25,898] Trial 115 finished with value: 0.9485527979161809 and parameters: {'weight_class_0': 0.0023922849022830514, 'weight_class_1': 0.032779538985571295, 'weight_class_2': 0.012891404056524952}. Best is trial 109 with value: 0.9496405873168569.
[I 2026-07-03 10:56:25,922] Trial 117 finished with value: 0.936387348043282 and parameters: {'weight_class_0': 0.0022699987057295135, 'weight_class_1': 0.030641967649350985, 'weight_class_2': 0.004859857906124076}. Best is trial 109 with value: 0.9496405873168569.
[I 2026-07-03 10:56:25,935] Trial 118 finished with value: 0.9461894069478364 and parameters: {'weight_class_0': 0.002340421776196237, 'weight_class_1': 0.009657956406387681, 'weight_class_2': 0.013711159051623166}. Best is trial 109 with value: 0.9496405873168569.
[I 2026-07-03 10:56:25,944] Trial 119 finished with value: 0.9439456889967316 and parameters: {'weight_class_0': 0.0018009795770675928, 'weight_class_1': 0.018627655832878, 'weight_class_2': 0.005513815394728931}. Best is trial 109 with value: 0.9496405873168569.
[I 2026-07-03 10:56:25,967] Trial 120 finished with value: 0.9495199232221054 and parameters: {'weight_class_0': 0.0018578169205450293, 'weight_class_1': 0.01998733941537628, 'weight_class_2': 0.017011862034610133}. Best is trial 109 with value: 0.9496405873168569.
[I 2026-07-03 10:56:25,980] Trial 121 finished with value: 0.9495396438482838 and parameters: {'weight_class_0': 0.00188063768431124, 'weight_class_1': 0.018841017061846054, 'weight_class_2': 0.017183136617487743}. Best is trial 109 with value: 0.9496405873168569.
[I 2026-07-03 10:56:26,004] Trial 122 finished with value: 0.940483020214126 and parameters: {'weight_class_0': 0.0018296423427868436, 'weight_class_1': 0.018429952249680918, 'weight_class_2': 0.004624054419439045}. Best is trial 109 with value: 0.9496405873168569.
[I 2026-07-03 10:56:26,022] Trial 123 finished with value: 0.9377944884054964 and parameters: {'weight_class_0': 0.0015463306131160315, 'weight_class_1': 0.01822766246141264, 'weight_class_2': 0.0034773336680585707}. Best is trial 109 with value: 0.9496405873168569.
[I 2026-07-03 10:56:26,062] Trial 124 finished with value: 0.949595848181321 and parameters: {'weight_class_0': 0.0016541631801783936, 'weight_class_1': 0.0184939906830922, 'weight_class_2': 0.01741844491328833}. Best is trial 109 with value: 0.9496405873168569.
[I 2026-07-03 10:56:26,066] Trial 125 finished with value: 0.9496167498682269 and parameters: {'weight_class_0': 0.0016999803187040456, 'weight_class_1': 0.020878122776306834, 'weight_class_2': 0.017083152262917164}. Best is trial 109 with value: 0.9496405873168569.

[I 2026-07-03 10:56:26,074] Trial 127 finished with value: 0.9496530219463843 and parameters: {'weight_class_0': 0.001546089301005013, 'weight_class_1': 0.021221569467489806, 'weight_class_2': 0.019609932381662153}. Best is trial 127 with value: 0.9496530219463843.
[I 2026-07-03 10:56:26,083] Trial 126 finished with value: 0.9496241509666317 and parameters: {'weight_class_0': 0.0017524560295606503, 'weight_class_1': 0.019782710741388574, 'weight_class_2': 0.018283123560054692}. Best is trial 127 with value: 0.9496530219463843.
[I 2026-07-03 10:56:26,109] Trial 128 finished with value: 0.9496621698685465 and parameters: {'weight_class_0': 0.0015672744324595708, 'weight_class_1': 0.021660754466517367, 'weight_class_2': 0.017692515654532275}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,131] Trial 129 finished with value: 0.9496354381559052 and parameters: {'weight_class_0': 0.0015127577730465757, 'weight_class_1': 0.022564379731150528, 'weight_class_2': 0.01784226562069474}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,139] Trial 130 finished with value: 0.9495659833159159 and parameters: {'weight_class_0': 0.0015033827963873102, 'weight_class_1': 0.02277788187076321, 'weight_class_2': 0.01969469830202801}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,155] Trial 131 finished with value: 0.9449264679214159 and parameters: {'weight_class_0': 0.0014854409197690506, 'weight_class_1': 0.004855864329936885, 'weight_class_2': 0.017979741484737587}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,176] Trial 132 finished with value: 0.9489107686272947 and parameters: {'weight_class_0': 0.0010106439324659546, 'weight_class_1': 0.023162146021377714, 'weight_class_2': 0.018256662714834854}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,181] Trial 133 finished with value: 0.9490680974438334 and parameters: {'weight_class_0': 0.0010351432542100854, 'weight_class_1': 0.023444825289634087, 'weight_class_2': 0.017649535246141955}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,214] Trial 134 finished with value: 0.9489995381706534 and parameters: {'weight_class_0': 0.001009324465362639, 'weight_class_1': 0.023134792890302278, 'weight_class_2': 0.01770537866787516}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,215] Trial 135 finished with value: 0.946518774887262 and parameters: {'weight_class_0': 0.0014394926294881369, 'weight_class_1': 0.0055670561153816755, 'weight_class_2': 0.017619613040519008}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,233] Trial 136 finished with value: 0.9488280089292043 and parameters: {'weight_class_0': 0.0010010991460279457, 'weight_class_1': 0.023304771304512653, 'weight_class_2': 0.018571985262407536}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,268] Trial 137 finished with value: 0.9496280071527295 and parameters: {'weight_class_0': 0.0014168475709657262, 'weight_class_1': 0.022664364790199676, 'weight_class_2': 0.01701289368048414}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,275] Trial 138 finished with value: 0.9487004323959685 and parameters: {'weight_class_0': 0.0010321358009534542, 'weight_class_1': 0.010062915507556107, 'weight_class_2': 0.018329305403154545}. Best is trial 128 with value: 0.9496621698685465.

Best trial: 128. Best value: 0.949662:   5%|██████▌                                                                                                                             | 150/3000 [00:02<00:46, 61.06it/s]

[I 2026-07-03 10:56:26,279] Trial 139 finished with value: 0.9491255163122583 and parameters: {'weight_class_0': 0.0010478054688743633, 'weight_class_1': 0.02302821049255448, 'weight_class_2': 0.01765646085887364}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,292] Trial 140 finished with value: 0.9490888389488169 and parameters: {'weight_class_0': 0.0010466198575207618, 'weight_class_1': 0.022566267071012343, 'weight_class_2': 0.01802516026910852}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,311] Trial 141 finished with value: 0.948150924657817 and parameters: {'weight_class_0': 0.0014563493972884999, 'weight_class_1': 0.010494828017419465, 'weight_class_2': 0.007930903085633077}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,335] Trial 142 finished with value: 0.9479226553563279 and parameters: {'weight_class_0': 0.00142904674285223, 'weight_class_1': 0.009345005078328483, 'weight_class_2': 0.007908818232141632}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,349] Trial 143 finished with value: 0.9442357141493266 and parameters: {'weight_class_0': 0.002053229757162891, 'weight_class_1': 0.010666854269731449, 'weight_class_2': 0.007241379976931845}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,363] Trial 144 finished with value: 0.9449403444046022 and parameters: {'weight_class_0': 0.002039952670204048, 'weight_class_1': 0.011375630927034624, 'weight_class_2': 0.007606059537213852}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,381] Trial 145 finished with value: 0.9464860030338643 and parameters: {'weight_class_0': 0.001936582114690889, 'weight_class_1': 0.01684483718734397, 'weight_class_2': 0.00757488966580562}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,403] Trial 146 finished with value: 0.9443604837076404 and parameters: {'weight_class_0': 0.0020896716513505893, 'weight_class_1': 0.01115463964389752, 'weight_class_2': 0.007422529073359972}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,421] Trial 147 finished with value: 0.9471981196381191 and parameters: {'weight_class_0': 0.0014539604799772416, 'weight_class_1': 0.011187299254962776, 'weight_class_2': 0.006476257120548946}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,421] Trial 148 finished with value: 0.9483362217678003 and parameters: {'weight_class_0': 0.0014464072140204357, 'weight_class_1': 0.01639917225927327, 'weight_class_2': 0.007462943957718181}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,440] Trial 149 finished with value: 0.9466457059204035 and parameters: {'weight_class_0': 0.0020449938524967153, 'weight_class_1': 0.01570224222179397, 'weight_class_2': 0.008539737849022313}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,459] Trial 150 finished with value: 0.945151745289866 and parameters: {'weight_class_0': 0.0019400474766330528, 'weight_class_1': 0.016133467954377978, 'weight_class_2': 0.006677915576083604}. Best is trial 128 with value: 0.9496621698685465.

[I 2026-07-03 10:56:26,475] Trial 151 finished with value: 0.9484810649920313 and parameters: {'weight_class_0': 0.001969806240846487, 'weight_class_1': 0.016510411826269368, 'weight_class_2': 0.011301911426458963}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,514] Trial 153 finished with value: 0.9492385416606602 and parameters: {'weight_class_0': 0.0016003980822483779, 'weight_class_1': 0.019240551550992267, 'weight_class_2': 0.011422558952499547}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,516] Trial 152 finished with value: 0.9482738865751448 and parameters: {'weight_class_0': 0.0020125141307016465, 'weight_class_1': 0.014500062330296543, 'weight_class_2': 0.011304277658045066}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,534] Trial 154 finished with value: 0.9493637175404036 and parameters: {'weight_class_0': 0.0015179764295205024, 'weight_class_1': 0.015503777569154513, 'weight_class_2': 0.011713477183315897}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,548] Trial 155 finished with value: 0.9490221822658516 and parameters: {'weight_class_0': 0.0016044168157229746, 'weight_class_1': 0.015004085412021934, 'weight_class_2': 0.011073017060986765}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,566] Trial 156 finished with value: 0.5139437753039431 and parameters: {'weight_class_0': 2.2432841325157304, 'weight_class_1': 0.0011874185259415477, 'weight_class_2': 0.012637559347967339}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,573] Trial 157 finished with value: 0.9496111951513001 and parameters: {'weight_class_0': 0.0012591752482423607, 'weight_class_1': 0.019700783337284866, 'weight_class_2': 0.010911535400891237}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,585] Trial 158 finished with value: 0.5570085500344032 and parameters: {'weight_class_0': 0.0016739427866535805, 'weight_class_1': 5.38139921932774, 'weight_class_2': 0.011462230955730625}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,605] Trial 159 finished with value: 0.9495635310038631 and parameters: {'weight_class_0': 0.001264996915052961, 'weight_class_1': 0.019818312985696498, 'weight_class_2': 0.011269734826471041}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,632] Trial 160 finished with value: 0.7304213885143973 and parameters: {'weight_class_0': 0.0017099800017510904, 'weight_class_1': 1.1545558323791223, 'weight_class_2': 0.012043517488542823}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,663] Trial 161 finished with value: 0.9495947401885697 and parameters: {'weight_class_0': 0.0012920392086321036, 'weight_class_1': 0.019951213529331185, 'weight_class_2': 0.011340829819659969}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,668] Trial 162 finished with value: 0.6162893851793214 and parameters: {'weight_class_0': 0.001254254409508085, 'weight_class_1': 0.026475508327332493, 'weight_class_2': 8.512600984886143}. Best is trial 128 with value: 0.9496621698685465.

[I 2026-07-03 10:56:26,676] Trial 163 finished with value: 0.6181888162593864 and parameters: {'weight_class_0': 0.0012473950250214902, 'weight_class_1': 0.025673613235392495, 'weight_class_2': 7.932490413712683}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,708] Trial 164 finished with value: 0.614045955747401 and parameters: {'weight_class_0': 0.0012499676683782623, 'weight_class_1': 0.02615051072756416, 'weight_class_2': 8.791961867048226}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,729] Trial 165 finished with value: 0.9484914060702111 and parameters: {'weight_class_0': 0.0012163390319695068, 'weight_class_1': 0.038504400953347125, 'weight_class_2': 0.02292054998944779}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,736] Trial 166 finished with value: 0.9491591403146513 and parameters: {'weight_class_0': 0.001287406587567237, 'weight_class_1': 0.02069285297502615, 'weight_class_2': 0.022136764896666872}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,756] Trial 167 finished with value: 0.9488221274233783 and parameters: {'weight_class_0': 0.0011947982576248405, 'weight_class_1': 0.027071391958488553, 'weight_class_2': 0.02294271883292597}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,768] Trial 168 finished with value: 0.9489667368442275 and parameters: {'weight_class_0': 0.0012204244515400234, 'weight_class_1': 0.026441298135950007, 'weight_class_2': 0.022127182245689835}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,793] Trial 170 finished with value: 0.9485468144762107 and parameters: {'weight_class_0': 0.0012652426062227465, 'weight_class_1': 0.039802962416802874, 'weight_class_2': 0.023209468207636218}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,796] Trial 169 finished with value: 0.9485661184804872 and parameters: {'weight_class_0': 0.0012636771811072763, 'weight_class_1': 0.039682766427520486, 'weight_class_2': 0.022912838682118155}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,822] Trial 171 finished with value: 0.9485891761962044 and parameters: {'weight_class_0': 0.001247223642492927, 'weight_class_1': 0.038916933844658094, 'weight_class_2': 0.022222301590127894}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,847] Trial 172 finished with value: 0.9495735868497057 and parameters: {'weight_class_0': 0.0024517638505548505, 'weight_class_1': 0.04085015232993623, 'weight_class_2': 0.02263264038433144}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,867] Trial 173 finished with value: 0.9495689009124945 and parameters: {'weight_class_0': 0.0025056281639199195, 'weight_class_1': 0.04319644668810952, 'weight_class_2': 0.02292795416153775}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,870] Trial 174 finished with value: 0.9486612868550196 and parameters: {'weight_class_0': 0.002387999351642793, 'weight_class_1': 0.020844698397788398, 'weight_class_2': 0.014262032716185863}. Best is trial 128 with value: 0.9496621698685465.

Best trial: 128. Best value: 0.949662:   6%|████████▏                                                                                                                           | 186/3000 [00:03<00:46, 60.51it/s]

[I 2026-07-03 10:56:26,895] Trial 175 finished with value: 0.9486608031602546 and parameters: {'weight_class_0': 0.002654910361893896, 'weight_class_1': 0.04184756643548746, 'weight_class_2': 0.01507707846498771}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,913] Trial 176 finished with value: 0.9488946272814669 and parameters: {'weight_class_0': 0.0025483089503369567, 'weight_class_1': 0.04055152992413565, 'weight_class_2': 0.015661179695898007}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,922] Trial 177 finished with value: 0.9485895400417537 and parameters: {'weight_class_0': 0.0026352094744015874, 'weight_class_1': 0.039825789468427526, 'weight_class_2': 0.01460865568546245}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,949] Trial 178 finished with value: 0.94854230743044 and parameters: {'weight_class_0': 0.002543575890933314, 'weight_class_1': 0.02046504634935159, 'weight_class_2': 0.015123908302708515}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,960] Trial 179 finished with value: 0.9487291864796149 and parameters: {'weight_class_0': 0.002433239059418821, 'weight_class_1': 0.02002441842059021, 'weight_class_2': 0.015566897993682778}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,971] Trial 180 finished with value: 0.9486500820582938 and parameters: {'weight_class_0': 0.002496773904772209, 'weight_class_1': 0.020891232482593492, 'weight_class_2': 0.015204526524013133}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:26,989] Trial 181 finished with value: 0.94840237766557 and parameters: {'weight_class_0': 0.0025326902570502073, 'weight_class_1': 0.020267071411519632, 'weight_class_2': 0.014502302995514542}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,004] Trial 182 finished with value: 0.9488169161156241 and parameters: {'weight_class_0': 0.0023468822191516844, 'weight_class_1': 0.020816758877769192, 'weight_class_2': 0.014839360535117694}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,026] Trial 183 finished with value: 0.9487427492188399 and parameters: {'weight_class_0': 0.002574785381947371, 'weight_class_1': 0.03533118151111931, 'weight_class_2': 0.014763462982207608}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,058] Trial 184 finished with value: 0.9487189779686331 and parameters: {'weight_class_0': 0.0024782142774397893, 'weight_class_1': 0.036301825336551144, 'weight_class_2': 0.014247662050288788}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,058] Trial 185 finished with value: 0.9479725426533081 and parameters: {'weight_class_0': 0.0029535385870792493, 'weight_class_1': 0.031718313920497135, 'weight_class_2': 0.014211142316433263}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,073] Trial 186 finished with value: 0.9495472327462576 and parameters: {'weight_class_0': 0.0030733803955535688, 'weight_class_1': 0.032918394350983184, 'weight_class_2': 0.0321607269238476}. Best is trial 128 with value: 0.9496621698685465.

Best trial: 128. Best value: 0.949662:   7%|████████▊                                                                                                                           | 199/3000 [00:03<00:49, 56.41it/s]

[I 2026-07-03 10:56:27,120] Trial 187 finished with value: 0.9488144684067453 and parameters: {'weight_class_0': 0.003179167007320702, 'weight_class_1': 0.03406287544239291, 'weight_class_2': 0.019568846026962072}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,125] Trial 189 finished with value: 0.9495569137921942 and parameters: {'weight_class_0': 0.0016022581813558531, 'weight_class_1': 0.02864448391666213, 'weight_class_2': 0.01994785990768746}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,132] Trial 188 finished with value: 0.9486419384800419 and parameters: {'weight_class_0': 0.0015592641462453523, 'weight_class_1': 0.029019327193988163, 'weight_class_2': 0.035282888778461474}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,141] Trial 190 finished with value: 0.9488667337224218 and parameters: {'weight_class_0': 0.001641445781851476, 'weight_class_1': 0.03383794886553132, 'weight_class_2': 0.03334894022659218}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,149] Trial 191 finished with value: 0.9489168648461869 and parameters: {'weight_class_0': 0.0016926995769208477, 'weight_class_1': 0.029461310840742105, 'weight_class_2': 0.03341120415111513}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,174] Trial 192 finished with value: 0.948234289089561 and parameters: {'weight_class_0': 0.0016476785025994571, 'weight_class_1': 0.013192868550502123, 'weight_class_2': 0.03249807843173846}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,192] Trial 193 finished with value: 0.9495662355484807 and parameters: {'weight_class_0': 0.0016165576117959434, 'weight_class_1': 0.028448218334724846, 'weight_class_2': 0.01985640525496987}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,208] Trial 194 finished with value: 0.948861360074481 and parameters: {'weight_class_0': 0.0016050162756256622, 'weight_class_1': 0.027484174079198693, 'weight_class_2': 0.03257662517067111}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,216] Trial 195 finished with value: 0.9486255460705766 and parameters: {'weight_class_0': 0.0016162589180610987, 'weight_class_1': 0.026737851898244444, 'weight_class_2': 0.009189835836160693}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,242] Trial 196 finished with value: 0.9488879342794383 and parameters: {'weight_class_0': 0.0016206960242896372, 'weight_class_1': 0.025395069654339235, 'weight_class_2': 0.009889890891426159}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,278] Trial 197 finished with value: 0.948246815071494 and parameters: {'weight_class_0': 0.0016765927589188511, 'weight_class_1': 0.012917263263442598, 'weight_class_2': 0.009242672144682123}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,288] Trial 198 finished with value: 0.9491826633105078 and parameters: {'weight_class_0': 0.0014593333689510884, 'weight_class_1': 0.02586048881073621, 'weight_class_2': 0.02509119587251467}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,303] Trial 199 finished with value: 0.9489349467298673 and parameters: {'weight_class_0': 0.0014820275786593898, 'weight_class_1': 0.02554156897820946, 'weight_class_2': 0.009546324778344255}. Best is trial 128 with value: 0.9496621698685465.

[I 2026-07-03 10:56:27,324] Trial 200 finished with value: 0.9476966000033524 and parameters: {'weight_class_0': 0.0020272984046780895, 'weight_class_1': 0.025322372960813147, 'weight_class_2': 0.00915031065504615}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,332] Trial 202 finished with value: 0.9490599626381342 and parameters: {'weight_class_0': 0.0014757831013454549, 'weight_class_1': 0.02546787844171077, 'weight_class_2': 0.009740493732862619}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,340] Trial 201 finished with value: 0.9490724302457574 and parameters: {'weight_class_0': 0.001442530020433102, 'weight_class_1': 0.025338585966530224, 'weight_class_2': 0.009583432700231778}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,433] Trial 206 finished with value: 0.9494362407068587 and parameters: {'weight_class_0': 0.002078349975467998, 'weight_class_1': 0.04766549103729638, 'weight_class_2': 0.02018121427136243}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,401] Trial 205 finished with value: 0.9493943436786835 and parameters: {'weight_class_0': 0.002094141746089165, 'weight_class_1': 0.05259953038012955, 'weight_class_2': 0.025952180011916907}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,401] Trial 204 finished with value: 0.9493849882291113 and parameters: {'weight_class_0': 0.002088487451308768, 'weight_class_1': 0.05174501572408936, 'weight_class_2': 0.019511898808559806}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,392] Trial 203 finished with value: 0.9475879373823909 and parameters: {'weight_class_0': 0.002062864003089062, 'weight_class_1': 0.04848396602942954, 'weight_class_2': 0.009817043078979562}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,448] Trial 207 finished with value: 0.9493603199188847 and parameters: {'weight_class_0': 0.002110130950021045, 'weight_class_1': 0.053366420214288064, 'weight_class_2': 0.020713827763521993}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,469] Trial 208 finished with value: 0.9494253851869554 and parameters: {'weight_class_0': 0.0020973555961606863, 'weight_class_1': 0.04827253077398317, 'weight_class_2': 0.020116205049415803}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,471] Trial 209 finished with value: 0.9494659944520514 and parameters: {'weight_class_0': 0.002054684100569895, 'weight_class_1': 0.045512687780885706, 'weight_class_2': 0.018725906736188}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,484] Trial 210 finished with value: 0.9494010034603845 and parameters: {'weight_class_0': 0.002043163746362051, 'weight_class_1': 0.047105614588793115, 'weight_class_2': 0.020323761820334418}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,507] Trial 211 finished with value: 0.9493576958908775 and parameters: {'weight_class_0': 0.002030757998686824, 'weight_class_1': 0.04969684211951497, 'weight_class_2': 0.019243076181625365}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,539] Trial 212 finished with value: 0.9492502884202084 and parameters: {'weight_class_0': 0.0011416194030700478, 'weight_class_1': 0.017732116218173524, 'weight_class_2': 0.019052382737621557}. Best is trial 128 with value: 0.9496621698685465.

Best trial: 128. Best value: 0.949662:   8%|█████████▉                                                                                                                          | 225/3000 [00:03<00:46, 59.63it/s]

[I 2026-07-03 10:56:27,551] Trial 213 finished with value: 0.9491555428069183 and parameters: {'weight_class_0': 0.001138943213020419, 'weight_class_1': 0.01611809737553929, 'weight_class_2': 0.01971393765424426}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,562] Trial 214 finished with value: 0.9492868815484757 and parameters: {'weight_class_0': 0.0011214507752997094, 'weight_class_1': 0.01716593010364694, 'weight_class_2': 0.018512089988865568}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,591] Trial 215 finished with value: 0.817755975705583 and parameters: {'weight_class_0': 0.18906370164646422, 'weight_class_1': 0.01724126021896594, 'weight_class_2': 0.026398813789532124}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,622] Trial 217 finished with value: 0.8124793299574297 and parameters: {'weight_class_0': 0.2682348793028017, 'weight_class_1': 0.01758759646925895, 'weight_class_2': 0.02499255662671478}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,640] Trial 216 finished with value: 0.9484528917729405 and parameters: {'weight_class_0': 0.001150325482408119, 'weight_class_1': 0.01937342475935599, 'weight_class_2': 0.0277299212833916}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,651] Trial 218 finished with value: 0.9485970141660492 and parameters: {'weight_class_0': 0.0011978016076911585, 'weight_class_1': 0.019041005203881706, 'weight_class_2': 0.02691178099924443}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,652] Trial 219 finished with value: 0.9485758150935983 and parameters: {'weight_class_0': 0.0011466575093247347, 'weight_class_1': 0.016937698159993735, 'weight_class_2': 0.025609663693886953}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,674] Trial 220 finished with value: 0.9485302388485454 and parameters: {'weight_class_0': 0.0011172297823260821, 'weight_class_1': 0.01844657516184032, 'weight_class_2': 0.025992347720544113}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,682] Trial 221 finished with value: 0.9495765582785974 and parameters: {'weight_class_0': 0.0011623572245353468, 'weight_class_1': 0.01953549012752395, 'weight_class_2': 0.012327974350593976}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,707] Trial 222 finished with value: 0.94849308424911 and parameters: {'weight_class_0': 0.0032792313399990208, 'weight_class_1': 0.018294282338843167, 'weight_class_2': 0.02735555557781045}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,730] Trial 224 finished with value: 0.9495844605140089 and parameters: {'weight_class_0': 0.0013443064839999852, 'weight_class_1': 0.022532816740355417, 'weight_class_2': 0.0126915695168473}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,731] Trial 223 finished with value: 0.684299396272159 and parameters: {'weight_class_0': 0.0032635814981094966, 'weight_class_1': 0.019007020490319878, 'weight_class_2': 3.1678763988411367}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,755] Trial 225 finished with value: 0.94957259815023 and parameters: {'weight_class_0': 0.0013649390481739179, 'weight_class_1': 0.02068519552132813, 'weight_class_2': 0.012399362601029383}. Best is trial 128 with value: 0.9496621698685465.

Best trial: 128. Best value: 0.949662:   8%|██████████▍                                                                                                                         | 238/3000 [00:04<00:49, 55.74it/s]

[I 2026-07-03 10:56:27,772] Trial 226 finished with value: 0.9496265519805802 and parameters: {'weight_class_0': 0.0013328347155848773, 'weight_class_1': 0.021252398147577335, 'weight_class_2': 0.016569556297975328}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,805] Trial 227 finished with value: 0.9480109645200705 and parameters: {'weight_class_0': 0.0034160553832305674, 'weight_class_1': 0.032866139689844295, 'weight_class_2': 0.016880223847675787}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,812] Trial 228 finished with value: 0.9460253259448757 and parameters: {'weight_class_0': 0.0034492589333809318, 'weight_class_1': 0.03373723883285356, 'weight_class_2': 0.012767789848623215}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,837] Trial 229 finished with value: 0.9495752052596833 and parameters: {'weight_class_0': 0.001419301309574616, 'weight_class_1': 0.022563738248594395, 'weight_class_2': 0.012617530478316721}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,862] Trial 230 finished with value: 0.9494404269510687 and parameters: {'weight_class_0': 0.0014314187510586587, 'weight_class_1': 0.0325320023065541, 'weight_class_2': 0.011762385522786823}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,872] Trial 231 finished with value: 0.9493797642285681 and parameters: {'weight_class_0': 0.0013977547322438007, 'weight_class_1': 0.03342995802019187, 'weight_class_2': 0.012616498371223151}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,890] Trial 232 finished with value: 0.9494866992980739 and parameters: {'weight_class_0': 0.0014489923523889746, 'weight_class_1': 0.031710850659470595, 'weight_class_2': 0.012089720659225528}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,902] Trial 233 finished with value: 0.9494072136879659 and parameters: {'weight_class_0': 0.001370211644052131, 'weight_class_1': 0.031640778372055874, 'weight_class_2': 0.0122545620120878}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,918] Trial 234 finished with value: 0.9496117905724821 and parameters: {'weight_class_0': 0.0013919327433343693, 'weight_class_1': 0.022789416890956198, 'weight_class_2': 0.012295108863355761}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,933] Trial 235 finished with value: 0.9495854530584523 and parameters: {'weight_class_0': 0.0013957973389977349, 'weight_class_1': 0.013760084115404126, 'weight_class_2': 0.01206774493411772}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,936] Trial 237 finished with value: 0.9496428139570997 and parameters: {'weight_class_0': 0.001378579543281989, 'weight_class_1': 0.023050089126935274, 'weight_class_2': 0.0120987227045308}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,937] Trial 236 finished with value: 0.9495280252515096 and parameters: {'weight_class_0': 0.0013680161630748753, 'weight_class_1': 0.013727509979662865, 'weight_class_2': 0.012375977951872034}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:27,977] Trial 238 finished with value: 0.9495987089880904 and parameters: {'weight_class_0': 0.0013403880957228733, 'weight_class_1': 0.02263641148648105, 'weight_class_2': 0.012117254641190648}. Best is trial 128 with value: 0.9496621698685465.

Best trial: 246. Best value: 0.949689:   8%|███████████                                                                                                                         | 250/3000 [00:04<00:50, 54.25it/s]

[I 2026-07-03 10:56:27,993] Trial 239 finished with value: 0.9495752173902154 and parameters: {'weight_class_0': 0.0013904690564334108, 'weight_class_1': 0.02194839060265251, 'weight_class_2': 0.012377467412347963}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:28,018] Trial 240 finished with value: 0.9495919092914237 and parameters: {'weight_class_0': 0.0014179806993265855, 'weight_class_1': 0.02226297696334626, 'weight_class_2': 0.012532891034448714}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:28,055] Trial 241 finished with value: 0.9496139605334263 and parameters: {'weight_class_0': 0.0017485115215850997, 'weight_class_1': 0.023815680127327193, 'weight_class_2': 0.015881874504633377}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:28,077] Trial 243 finished with value: 0.9493220984093034 and parameters: {'weight_class_0': 0.001020332705537792, 'weight_class_1': 0.02224286611181696, 'weight_class_2': 0.015163866972684646}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:28,086] Trial 242 finished with value: 0.9495889224453681 and parameters: {'weight_class_0': 0.0013072012009468768, 'weight_class_1': 0.02232990997067805, 'weight_class_2': 0.016125601693884536}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:28,099] Trial 244 finished with value: 0.9493167807572579 and parameters: {'weight_class_0': 0.0010000042360320618, 'weight_class_1': 0.013597396486243895, 'weight_class_2': 0.016057425378262265}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:28,100] Trial 245 finished with value: 0.9496400303229245 and parameters: {'weight_class_0': 0.0017417159834578933, 'weight_class_1': 0.022393166940672712, 'weight_class_2': 0.016055524993451007}. Best is trial 128 with value: 0.9496621698685465.
[I 2026-07-03 10:56:28,113] Trial 246 finished with value: 0.9496886974103601 and parameters: {'weight_class_0': 0.001758327217060223, 'weight_class_1': 0.02155787646453763, 'weight_class_2': 0.015178828504293048}. Best is trial 246 with value: 0.9496886974103601.
[I 2026-07-03 10:56:28,123] Trial 247 finished with value: 0.9496260045878234 and parameters: {'weight_class_0': 0.0017775377734210796, 'weight_class_1': 0.023327552626573357, 'weight_class_2': 0.016028452036883044}. Best is trial 246 with value: 0.9496886974103601.
[I 2026-07-03 10:56:28,156] Trial 248 finished with value: 0.9496003807574233 and parameters: {'weight_class_0': 0.0010027603151367469, 'weight_class_1': 0.014773942454980092, 'weight_class_2': 0.01362945361428916}. Best is trial 246 with value: 0.9496886974103601.
[I 2026-07-03 10:56:28,190] Trial 249 finished with value: 0.9491305108196313 and parameters: {'weight_class_0': 0.0010007430564496587, 'weight_class_1': 0.023378739721702537, 'weight_class_2': 0.015694718162240967}. Best is trial 246 with value: 0.9496886974103601.
[I 2026-07-03 10:56:28,190] Trial 251 finished with value: 0.9491885555897636 and parameters: {'weight_class_0': 0.0010070561231247145, 'weight_class_1': 0.022686335960857014, 'weight_class_2': 0.015625772399563316}. Best is trial 246 with value: 0.9496886974103601.

Best trial: 253. Best value: 0.949691:   9%|███████████▌                                                                                                                        | 263/3000 [00:04<00:48, 56.10it/s]

[I 2026-07-03 10:56:28,215] Trial 252 finished with value: 0.9492074976109312 and parameters: {'weight_class_0': 0.0010185642761748855, 'weight_class_1': 0.0227988956519571, 'weight_class_2': 0.015656649283471984}. Best is trial 246 with value: 0.9496886974103601.
[I 2026-07-03 10:56:28,216] Trial 250 finished with value: 0.9496368992183801 and parameters: {'weight_class_0': 0.0017357912371999277, 'weight_class_1': 0.02309572206799529, 'weight_class_2': 0.01575862787699258}. Best is trial 246 with value: 0.9496886974103601.
[I 2026-07-03 10:56:28,249] Trial 253 finished with value: 0.9496914284413952 and parameters: {'weight_class_0': 0.001826916564356039, 'weight_class_1': 0.023346533579235596, 'weight_class_2': 0.015845817468989908}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:28,272] Trial 254 finished with value: 0.9496156994673779 and parameters: {'weight_class_0': 0.001724135293010769, 'weight_class_1': 0.022790001475404303, 'weight_class_2': 0.015376013011022177}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:28,278] Trial 255 finished with value: 0.9496113151690047 and parameters: {'weight_class_0': 0.0017914136668440298, 'weight_class_1': 0.023333298074614022, 'weight_class_2': 0.014997419340184864}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:28,284] Trial 256 finished with value: 0.949402867716907 and parameters: {'weight_class_0': 0.0017666753012352144, 'weight_class_1': 0.014664066654109341, 'weight_class_2': 0.01539078606374897}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:28,305] Trial 257 finished with value: 0.9496120479709435 and parameters: {'weight_class_0': 0.0017632681877894827, 'weight_class_1': 0.02366499250573806, 'weight_class_2': 0.014491845662181601}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:28,331] Trial 258 finished with value: 0.9493814237877135 and parameters: {'weight_class_0': 0.001727277949376943, 'weight_class_1': 0.014149186442504532, 'weight_class_2': 0.015274085558947926}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:28,352] Trial 259 finished with value: 0.9486604445365895 and parameters: {'weight_class_0': 0.0017568903535837084, 'weight_class_1': 0.014556067483256822, 'weight_class_2': 0.010716823525785906}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:28,365] Trial 261 finished with value: 0.9484184028556136 and parameters: {'weight_class_0': 0.0017945085279675648, 'weight_class_1': 0.014461551489969861, 'weight_class_2': 0.010248559288340637}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:28,368] Trial 260 finished with value: 0.9491410501618934 and parameters: {'weight_class_0': 0.0018086250199221498, 'weight_class_1': 0.014067071794310802, 'weight_class_2': 0.013986171199970572}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:28,404] Trial 263 finished with value: 0.9485447382540769 and parameters: {'weight_class_0': 0.0018059775675229978, 'weight_class_1': 0.014820758438817768, 'weight_class_2': 0.010594136248235278}. Best is trial 253 with value: 0.9496914284413952.

[I 2026-07-03 10:56:28,418] Trial 262 finished with value: 0.9482957941884701 and parameters: {'weight_class_0': 0.0018179440216307284, 'weight_class_1': 0.014256608142788937, 'weight_class_2': 0.01007971624058992}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:28,442] Trial 264 finished with value: 0.9486273919693922 and parameters: {'weight_class_0': 0.0018002489136271372, 'weight_class_1': 0.015276501101811994, 'weight_class_2': 0.010544597315977726}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:28,458] Trial 265 finished with value: 0.9486636012641526 and parameters: {'weight_class_0': 0.0017364176454334724, 'weight_class_1': 0.016151431266768494, 'weight_class_2': 0.010396732451793459}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:28,459] Trial 266 finished with value: 0.9485507127280012 and parameters: {'weight_class_0': 0.0018074420192149717, 'weight_class_1': 0.01568178322009148, 'weight_class_2': 0.010474151876543202}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:28,471] Trial 267 finished with value: 0.948408277081743 and parameters: {'weight_class_0': 0.001832031479051123, 'weight_class_1': 0.017277134059640768, 'weight_class_2': 0.009918886325860589}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:28,517] Trial 268 finished with value: 0.9488622151238643 and parameters: {'weight_class_0': 0.0017898820315884406, 'weight_class_1': 0.026176928072521657, 'weight_class_2': 0.010811721270167728}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:28,527] Trial 269 finished with value: 0.9496107421662611 and parameters: {'weight_class_0': 0.0018066556702046673, 'weight_class_1': 0.02556855792850334, 'weight_class_2': 0.017164887485328188}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:28,537] Trial 271 finished with value: 0.9496294395362793 and parameters: {'weight_class_0': 0.0018190099322278502, 'weight_class_1': 0.026473155165059537, 'weight_class_2': 0.016839856537857273}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:28,538] Trial 270 finished with value: 0.949646558388321 and parameters: {'weight_class_0': 0.0018183926081667696, 'weight_class_1': 0.02595866962412489, 'weight_class_2': 0.01705884355888583}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:28,547] Trial 272 finished with value: 0.9496352750001279 and parameters: {'weight_class_0': 0.00179794633450772, 'weight_class_1': 0.023726181460001865, 'weight_class_2': 0.016308757651134924}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:28,587] Trial 273 finished with value: 0.9496354299085047 and parameters: {'weight_class_0': 0.0017869174852386766, 'weight_class_1': 0.02657257096378082, 'weight_class_2': 0.017483474752018197}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:28,606] Trial 274 finished with value: 0.9496043232679402 and parameters: {'weight_class_0': 0.001542316254291686, 'weight_class_1': 0.025319336975375743, 'weight_class_2': 0.017060722286578105}. Best is trial 253 with value: 0.9496914284413952.

[I 2026-07-03 10:56:28,618] Trial 275 finished with value: 0.9495713894848877 and parameters: {'weight_class_0': 0.0013699039797743576, 'weight_class_1': 0.026848137827746695, 'weight_class_2': 0.016988088399374067}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:28,655] Trial 276 finished with value: 0.949569287958761 and parameters: {'weight_class_0': 0.0013337130641990695, 'weight_class_1': 0.023205371607590414, 'weight_class_2': 0.015935428805715333}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:28,661] Trial 277 finished with value: 0.9495557416004995 and parameters: {'weight_class_0': 0.0013324907941281757, 'weight_class_1': 0.025385838967529134, 'weight_class_2': 0.017385605367790446}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:28,670] Trial 278 finished with value: 0.9495368188467813 and parameters: {'weight_class_0': 0.001300940395716919, 'weight_class_1': 0.02600436735401048, 'weight_class_2': 0.016727738652192885}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:28,696] Trial 279 finished with value: 0.9495256454480373 and parameters: {'weight_class_0': 0.0013307924955562045, 'weight_class_1': 0.0256191244758648, 'weight_class_2': 0.0172770397454612}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:28,697] Trial 280 finished with value: 0.9492366744900628 and parameters: {'weight_class_0': 0.00223202784853684, 'weight_class_1': 0.02710442637182853, 'weight_class_2': 0.015733762994462903}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:28,745] Trial 281 finished with value: 0.9496497921190586 and parameters: {'weight_class_0': 0.0021812814544204568, 'weight_class_1': 0.026998399048619778, 'weight_class_2': 0.017907761097959447}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:28,747] Trial 282 finished with value: 0.9496079671747797 and parameters: {'weight_class_0': 0.0021722306339415185, 'weight_class_1': 0.027098243529247133, 'weight_class_2': 0.01751258923642275}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:28,755] Trial 283 finished with value: 0.9495494504320895 and parameters: {'weight_class_0': 0.002206540396750043, 'weight_class_1': 0.02729335943736364, 'weight_class_2': 0.017331761149810738}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:28,769] Trial 284 finished with value: 0.9495965766807619 and parameters: {'weight_class_0': 0.002227717084695894, 'weight_class_1': 0.026999044595094335, 'weight_class_2': 0.0181460384240942}. Best is trial 253 with value: 0.9496914284413952.

Best trial: 253. Best value: 0.949691:  10%|████████████▉                                                                                                                       | 295/3000 [00:05<00:50, 53.59it/s]

[I 2026-07-03 10:56:28,787] Trial 285 finished with value: 0.9496319918708312 and parameters: {'weight_class_0': 0.002156211131894738, 'weight_class_1': 0.028024348906696944, 'weight_class_2': 0.01947222580580972}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:28,825] Trial 287 finished with value: 0.94968169994764 and parameters: {'weight_class_0': 0.002277774593757967, 'weight_class_1': 0.02798925141759619, 'weight_class_2': 0.02126943586418727}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:28,837] Trial 286 finished with value: 0.9496376007251338 and parameters: {'weight_class_0': 0.0022799817465248566, 'weight_class_1': 0.02854668750030423, 'weight_class_2': 0.020420579986208345}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:28,839] Trial 288 finished with value: 0.9051804266422033 and parameters: {'weight_class_0': 0.0021029960420991685, 'weight_class_1': 0.02732591873801231, 'weight_class_2': 0.0016898666339107639}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:28,867] Trial 289 finished with value: 0.9496084773405347 and parameters: {'weight_class_0': 0.0023841085998442414, 'weight_class_1': 0.028889548682938738, 'weight_class_2': 0.01979114577364716}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:28,887] Trial 290 finished with value: 0.9495309453774446 and parameters: {'weight_class_0': 0.0021000635561066266, 'weight_class_1': 0.020039519316716947, 'weight_class_2': 0.019357314359200566}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:28,898] Trial 291 finished with value: 0.9494732181444513 and parameters: {'weight_class_0': 0.002323886958257817, 'weight_class_1': 0.02068253867386953, 'weight_class_2': 0.02193214564100712}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:28,919] Trial 292 finished with value: 0.949443982010321 and parameters: {'weight_class_0': 0.0023096117486490412, 'weight_class_1': 0.019991993990693156, 'weight_class_2': 0.022381644508820263}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:28,946] Trial 293 finished with value: 0.9489386092651054 and parameters: {'weight_class_0': 0.0027945966532398805, 'weight_class_1': 0.020545148872316156, 'weight_class_2': 0.020672477898410688}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:28,961] Trial 294 finished with value: 0.9490975311692789 and parameters: {'weight_class_0': 0.002777651890305931, 'weight_class_1': 0.019865488820014914, 'weight_class_2': 0.021775796321127912}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:28,989] Trial 295 finished with value: 0.9493164466428011 and parameters: {'weight_class_0': 0.0029544611796072317, 'weight_class_1': 0.03642847155100441, 'weight_class_2': 0.021518145896668187}. Best is trial 253 with value: 0.9496914284413952.

Best trial: 253. Best value: 0.949691:  10%|█████████████▌                                                                                                                      | 307/3000 [00:05<00:50, 53.40it/s]

[I 2026-07-03 10:56:29,007] Trial 296 finished with value: 0.9491218785732182 and parameters: {'weight_class_0': 0.002767089557470725, 'weight_class_1': 0.019489942451920823, 'weight_class_2': 0.02221680630090092}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,046] Trial 297 finished with value: 0.9495747276844441 and parameters: {'weight_class_0': 0.0028462317224902563, 'weight_class_1': 0.03874724745154117, 'weight_class_2': 0.02275032079869834}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,052] Trial 298 finished with value: 0.9495338367675363 and parameters: {'weight_class_0': 0.002867206599499421, 'weight_class_1': 0.03598129573900561, 'weight_class_2': 0.022537708346079263}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,090] Trial 300 finished with value: 0.949670748712122 and parameters: {'weight_class_0': 0.0027608064784360067, 'weight_class_1': 0.03691535221871074, 'weight_class_2': 0.0234906604283597}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,104] Trial 299 finished with value: 0.949167174697834 and parameters: {'weight_class_0': 0.00306652337039517, 'weight_class_1': 0.02965689659843467, 'weight_class_2': 0.022256383946950162}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,113] Trial 301 finished with value: 0.9496566099601252 and parameters: {'weight_class_0': 0.002765244420855645, 'weight_class_1': 0.03766512685460898, 'weight_class_2': 0.023537059859415625}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,120] Trial 302 finished with value: 0.949668991736567 and parameters: {'weight_class_0': 0.002844319492847734, 'weight_class_1': 0.03766223049206384, 'weight_class_2': 0.02404203443172465}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,155] Trial 303 finished with value: 0.949619017700654 and parameters: {'weight_class_0': 0.002918293560911837, 'weight_class_1': 0.03535332068328814, 'weight_class_2': 0.02456532636270625}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,176] Trial 304 finished with value: 0.7470753390554444 and parameters: {'weight_class_0': 0.002042615690642654, 'weight_class_1': 0.030437559097732488, 'weight_class_2': 1.4594985887437286}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,180] Trial 305 finished with value: 0.9496255285883118 and parameters: {'weight_class_0': 0.0020749276721184215, 'weight_class_1': 0.02961893859616853, 'weight_class_2': 0.025245437323306943}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,185] Trial 306 finished with value: 0.8014375127518313 and parameters: {'weight_class_0': 0.8332835263986742, 'weight_class_1': 0.03026011615999619, 'weight_class_2': 0.026081709915991468}. Best is trial 253 with value: 0.9496914284413952.

Best trial: 253. Best value: 0.949691:  11%|██████████████                                                                                                                      | 319/3000 [00:05<00:47, 56.22it/s]

[I 2026-07-03 10:56:29,226] Trial 307 finished with value: 0.9496640130864695 and parameters: {'weight_class_0': 0.002418470756689015, 'weight_class_1': 0.03061773625855591, 'weight_class_2': 0.026265665905078856}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,231] Trial 308 finished with value: 0.9496559673536367 and parameters: {'weight_class_0': 0.0021900515664429036, 'weight_class_1': 0.029762062523646653, 'weight_class_2': 0.02802199461840477}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,266] Trial 309 finished with value: 0.9496215615209066 and parameters: {'weight_class_0': 0.00246417555657513, 'weight_class_1': 0.039091337508393484, 'weight_class_2': 0.02940735574097306}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,289] Trial 310 finished with value: 0.9494361394942209 and parameters: {'weight_class_0': 0.0037813254315692915, 'weight_class_1': 0.03756880857064488, 'weight_class_2': 0.029960397182354145}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,305] Trial 311 finished with value: 0.9480365327690891 and parameters: {'weight_class_0': 0.0050745871368989845, 'weight_class_1': 0.039005074182977266, 'weight_class_2': 0.02665246084658815}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,312] Trial 312 finished with value: 0.9485805946355024 and parameters: {'weight_class_0': 0.0047553239523684095, 'weight_class_1': 0.037191585611988695, 'weight_class_2': 0.029478860927135572}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,329] Trial 313 finished with value: 0.949653822352588 and parameters: {'weight_class_0': 0.0035553350180952755, 'weight_class_1': 0.04226498911669204, 'weight_class_2': 0.030325330584193386}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,352] Trial 314 finished with value: 0.949597207527345 and parameters: {'weight_class_0': 0.002481994815357286, 'weight_class_1': 0.04273993878874422, 'weight_class_2': 0.02731716414574328}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,368] Trial 315 finished with value: 0.9494399339123222 and parameters: {'weight_class_0': 0.003747535822009064, 'weight_class_1': 0.037595813859256484, 'weight_class_2': 0.02986901243049823}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,381] Trial 316 finished with value: 0.9494769884786223 and parameters: {'weight_class_0': 0.003748611033901563, 'weight_class_1': 0.03873601901001602, 'weight_class_2': 0.031223427053032996}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,399] Trial 317 finished with value: 0.949255406445225 and parameters: {'weight_class_0': 0.004119676713702528, 'weight_class_1': 0.03739337426281484, 'weight_class_2': 0.030891146827316408}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,415] Trial 318 finished with value: 0.9496076187951337 and parameters: {'weight_class_0': 0.0024978931681515944, 'weight_class_1': 0.041461291235978796, 'weight_class_2': 0.030484296498969655}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,446] Trial 319 finished with value: 0.9495683341166457 and parameters: {'weight_class_0': 0.0025410618472481604, 'weight_class_1': 0.040443842606223405, 'weight_class_2': 0.033651510127715}. Best is trial 253 with value: 0.9496914284413952.

Best trial: 253. Best value: 0.949691:  11%|██████████████▌                                                                                                                     | 331/3000 [00:05<00:47, 56.54it/s]

[I 2026-07-03 10:56:29,463] Trial 320 finished with value: 0.9494271215485339 and parameters: {'weight_class_0': 0.0033143618259238858, 'weight_class_1': 0.030341045909137426, 'weight_class_2': 0.026413385907330757}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,474] Trial 321 finished with value: 0.9493714386150734 and parameters: {'weight_class_0': 0.003604073710118607, 'weight_class_1': 0.02961632030507383, 'weight_class_2': 0.03304724769957058}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,486] Trial 322 finished with value: 0.9496613047948288 and parameters: {'weight_class_0': 0.003980578528939716, 'weight_class_1': 0.057073893483562434, 'weight_class_2': 0.037509706771404305}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,525] Trial 323 finished with value: 0.9495874083319279 and parameters: {'weight_class_0': 0.003379751793523912, 'weight_class_1': 0.06259790339966609, 'weight_class_2': 0.0334691334517606}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,541] Trial 324 finished with value: 0.949616012558197 and parameters: {'weight_class_0': 0.00435259792931577, 'weight_class_1': 0.061143281935831316, 'weight_class_2': 0.03609879892445477}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,548] Trial 325 finished with value: 0.9494126763778571 and parameters: {'weight_class_0': 0.0029738435043062624, 'weight_class_1': 0.029849309912593984, 'weight_class_2': 0.03884747637699703}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,562] Trial 326 finished with value: 0.9492388786993012 and parameters: {'weight_class_0': 0.003347186204792509, 'weight_class_1': 0.03172705992180159, 'weight_class_2': 0.025047630000330324}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,573] Trial 327 finished with value: 0.9489007609647405 and parameters: {'weight_class_0': 0.0033550085892173984, 'weight_class_1': 0.03104146823385566, 'weight_class_2': 0.05479269739579858}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,582] Trial 328 finished with value: 0.9495532295025119 and parameters: {'weight_class_0': 0.0030454748216898007, 'weight_class_1': 0.03308505947876567, 'weight_class_2': 0.036677046079977946}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,615] Trial 329 finished with value: 0.9494710661507733 and parameters: {'weight_class_0': 0.0033773196313159177, 'weight_class_1': 0.03154808674635956, 'weight_class_2': 0.036107010504922994}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,624] Trial 330 finished with value: 0.949025261508044 and parameters: {'weight_class_0': 0.0030089721784778253, 'weight_class_1': 0.03130648181050342, 'weight_class_2': 0.04980489429191817}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,644] Trial 331 finished with value: 0.948671975744339 and parameters: {'weight_class_0': 0.004356884027605514, 'weight_class_1': 0.06390056913518434, 'weight_class_2': 0.02425356029301201}. Best is trial 253 with value: 0.9496914284413952.

Best trial: 253. Best value: 0.949691:  11%|███████████████                                                                                                                     | 343/3000 [00:06<00:46, 57.65it/s]

[I 2026-07-03 10:56:29,667] Trial 332 finished with value: 0.9495602142637977 and parameters: {'weight_class_0': 0.004090783420568622, 'weight_class_1': 0.07164112757462687, 'weight_class_2': 0.03975288809378863}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,681] Trial 333 finished with value: 0.9496097772138663 and parameters: {'weight_class_0': 0.004293580432457025, 'weight_class_1': 0.06089593269035679, 'weight_class_2': 0.04378843633769365}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,703] Trial 334 finished with value: 0.9496340332505665 and parameters: {'weight_class_0': 0.0024241736035103528, 'weight_class_1': 0.045780656792806414, 'weight_class_2': 0.02371488935660741}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,704] Trial 335 finished with value: 0.9495701145255736 and parameters: {'weight_class_0': 0.00530964151807104, 'weight_class_1': 0.047771325930417045, 'weight_class_2': 0.04597853883773888}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,745] Trial 336 finished with value: 0.9493097454836024 and parameters: {'weight_class_0': 0.005402709659783735, 'weight_class_1': 0.060362600840208475, 'weight_class_2': 0.04016554264968621}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,751] Trial 337 finished with value: 0.948708486509449 and parameters: {'weight_class_0': 0.0022998764816035988, 'weight_class_1': 0.047996833804106714, 'weight_class_2': 0.049273361766934795}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,771] Trial 338 finished with value: 0.946771657456901 and parameters: {'weight_class_0': 0.004978673847800195, 'weight_class_1': 0.04802848975059362, 'weight_class_2': 0.020254656896912266}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,801] Trial 339 finished with value: 0.9452108782838833 and parameters: {'weight_class_0': 0.005837678719529872, 'weight_class_1': 0.044762252556481606, 'weight_class_2': 0.020409111063091987}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,806] Trial 340 finished with value: 0.9495438364736613 and parameters: {'weight_class_0': 0.002333128865538107, 'weight_class_1': 0.04723766925439897, 'weight_class_2': 0.020626287867530187}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,842] Trial 341 finished with value: 0.9494964946229256 and parameters: {'weight_class_0': 0.00231702763971581, 'weight_class_1': 0.05174276032174903, 'weight_class_2': 0.020138657164834633}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,872] Trial 343 finished with value: 0.9495728618347758 and parameters: {'weight_class_0': 0.002392758826554573, 'weight_class_1': 0.04575926620750971, 'weight_class_2': 0.020091810920171684}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,883] Trial 342 finished with value: 0.949499785464894 and parameters: {'weight_class_0': 0.0022730302719631773, 'weight_class_1': 0.048974458270292454, 'weight_class_2': 0.02031095059066139}. Best is trial 253 with value: 0.9496914284413952.

Best trial: 253. Best value: 0.949691:  12%|███████████████▋                                                                                                                    | 357/3000 [00:06<00:43, 60.71it/s]

[I 2026-07-03 10:56:29,888] Trial 344 finished with value: 0.9496281135925693 and parameters: {'weight_class_0': 0.0023411489326126854, 'weight_class_1': 0.04461017790204359, 'weight_class_2': 0.02036408500877148}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,904] Trial 345 finished with value: 0.9091596074488212 and parameters: {'weight_class_0': 0.002489441332438542, 'weight_class_1': 0.052176541036527586, 'weight_class_2': 0.5210002258469556}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,918] Trial 347 finished with value: 0.9495718271266346 and parameters: {'weight_class_0': 0.0023651572761490295, 'weight_class_1': 0.04692429565843679, 'weight_class_2': 0.01959832525226986}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,918] Trial 346 finished with value: 0.6774190125033117 and parameters: {'weight_class_0': 0.0021796151436265817, 'weight_class_1': 2.529254659054595, 'weight_class_2': 0.020004437948965864}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,948] Trial 348 finished with value: 0.9495721927129446 and parameters: {'weight_class_0': 0.00250356971462082, 'weight_class_1': 0.044169534417853366, 'weight_class_2': 0.020386536664279337}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,962] Trial 349 finished with value: 0.8108889618042512 and parameters: {'weight_class_0': 0.07849340736219518, 'weight_class_1': 0.0024285152960950747, 'weight_class_2': 0.024611813432314385}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:29,973] Trial 350 finished with value: 0.9495269077985435 and parameters: {'weight_class_0': 0.002515298427395698, 'weight_class_1': 0.05402569431584504, 'weight_class_2': 0.024558587048373548}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,002] Trial 351 finished with value: 0.9496512339966007 and parameters: {'weight_class_0': 0.0026905249296368143, 'weight_class_1': 0.03584278627661155, 'weight_class_2': 0.02501654287474397}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,025] Trial 352 finished with value: 0.5989982735895625 and parameters: {'weight_class_0': 4.821225139088883, 'weight_class_1': 0.03543465545875468, 'weight_class_2': 0.024744124744088904}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,046] Trial 353 finished with value: 0.9496486520038966 and parameters: {'weight_class_0': 0.002788614083759706, 'weight_class_1': 0.035750751798496384, 'weight_class_2': 0.0238454741475091}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,059] Trial 354 finished with value: 0.9496435666307016 and parameters: {'weight_class_0': 0.002611767101243739, 'weight_class_1': 0.036193395770226615, 'weight_class_2': 0.025416365297202554}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,076] Trial 355 finished with value: 0.9496646491935664 and parameters: {'weight_class_0': 0.0028863817008961683, 'weight_class_1': 0.034317346286357416, 'weight_class_2': 0.02503907530552161}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,089] Trial 356 finished with value: 0.949671099140453 and parameters: {'weight_class_0': 0.0027831667182823265, 'weight_class_1': 0.03455466372927824, 'weight_class_2': 0.024468991983419296}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,107] Trial 357 finished with value: 0.9496364287390326 and parameters: {'weight_class_0': 0.002811862293806293, 'weight_class_1': 0.036763327638931434, 'weight_class_2': 0.02539035146455386}. Best is trial 253 with value: 0.9496914284413952.

Best trial: 253. Best value: 0.949691:  12%|████████████████▎                                                                                                                   | 371/3000 [00:06<00:43, 60.87it/s]

[I 2026-07-03 10:56:30,117] Trial 358 finished with value: 0.949634589329904 and parameters: {'weight_class_0': 0.0028107352398780857, 'weight_class_1': 0.03346810016440388, 'weight_class_2': 0.02483882105253138}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,128] Trial 359 finished with value: 0.9495398090368531 and parameters: {'weight_class_0': 0.002001666168387673, 'weight_class_1': 0.0348722775855412, 'weight_class_2': 0.02725808750951083}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,136] Trial 360 finished with value: 0.9495337403405245 and parameters: {'weight_class_0': 0.0020270121534545155, 'weight_class_1': 0.03486061266559908, 'weight_class_2': 0.02666204186326563}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,146] Trial 361 finished with value: 0.9495650153230427 and parameters: {'weight_class_0': 0.002733683441211134, 'weight_class_1': 0.02720732859899201, 'weight_class_2': 0.026801968047916458}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,176] Trial 362 finished with value: 0.9496106030533885 and parameters: {'weight_class_0': 0.0028974174006259046, 'weight_class_1': 0.033976667309908226, 'weight_class_2': 0.027954297489984382}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,184] Trial 363 finished with value: 0.9496765900870417 and parameters: {'weight_class_0': 0.00290721681258809, 'weight_class_1': 0.036452297164182995, 'weight_class_2': 0.024836389329628297}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,194] Trial 364 finished with value: 0.9496087132177341 and parameters: {'weight_class_0': 0.0029428897686161817, 'weight_class_1': 0.03541671877075247, 'weight_class_2': 0.028350173655731704}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,221] Trial 365 finished with value: 0.9495973983287627 and parameters: {'weight_class_0': 0.002975315372622381, 'weight_class_1': 0.03329726268103352, 'weight_class_2': 0.028656396385931607}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,237] Trial 366 finished with value: 0.9494758216917293 and parameters: {'weight_class_0': 0.0037820305442375886, 'weight_class_1': 0.03655845683345148, 'weight_class_2': 0.03153134255610858}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,274] Trial 368 finished with value: 0.9492841012829832 and parameters: {'weight_class_0': 0.003798207451680486, 'weight_class_1': 0.03709358280729598, 'weight_class_2': 0.02936687924654272}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,276] Trial 367 finished with value: 0.9492958814187819 and parameters: {'weight_class_0': 0.003832182993882216, 'weight_class_1': 0.035878808617207776, 'weight_class_2': 0.029633625108292875}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,278] Trial 369 finished with value: 0.9495716643617641 and parameters: {'weight_class_0': 0.0037847454820970276, 'weight_class_1': 0.0763420482363331, 'weight_class_2': 0.03323834657518154}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,306] Trial 370 finished with value: 0.9495555538496699 and parameters: {'weight_class_0': 0.003807425844642094, 'weight_class_1': 0.04184803756440409, 'weight_class_2': 0.033647208452875804}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,320] Trial 371 finished with value: 0.9495407522570742 and parameters: {'weight_class_0': 0.003881167510678923, 'weight_class_1': 0.04008723908826072, 'weight_class_2': 0.03619690407797609}. Best is trial 253 with value: 0.9496914284413952.

Best trial: 253. Best value: 0.949691:  13%|████████████████▊                                                                                                                   | 383/3000 [00:06<00:42, 61.73it/s]

[I 2026-07-03 10:56:30,326] Trial 372 finished with value: 0.9496341039599422 and parameters: {'weight_class_0': 0.0033120180080361684, 'weight_class_1': 0.0404925781921502, 'weight_class_2': 0.033750254860369235}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,332] Trial 373 finished with value: 0.9495026221731758 and parameters: {'weight_class_0': 0.0038247202450169666, 'weight_class_1': 0.03977175306800801, 'weight_class_2': 0.033914220924731536}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,340] Trial 374 finished with value: 0.9488257220788078 and parameters: {'weight_class_0': 0.003835470939619372, 'weight_class_1': 0.03958176393819076, 'weight_class_2': 0.06762702242537402}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,356] Trial 375 finished with value: 0.9495712330577023 and parameters: {'weight_class_0': 0.00395846408088974, 'weight_class_1': 0.039480614664391914, 'weight_class_2': 0.036759444461460726}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,389] Trial 376 finished with value: 0.9495030917350671 and parameters: {'weight_class_0': 0.0040397597656369405, 'weight_class_1': 0.03882488772398318, 'weight_class_2': 0.036002326770843585}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,418] Trial 378 finished with value: 0.9495441903613712 and parameters: {'weight_class_0': 0.003833940652128822, 'weight_class_1': 0.0711040443750463, 'weight_class_2': 0.04020884921578644}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,419] Trial 377 finished with value: 0.8874798639509263 and parameters: {'weight_class_0': 0.044203802316635885, 'weight_class_1': 0.07206057842912374, 'weight_class_2': 0.035432320890623065}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,445] Trial 379 finished with value: 0.9495689197972167 and parameters: {'weight_class_0': 0.0034274762182344757, 'weight_class_1': 0.05672331594957764, 'weight_class_2': 0.03655653857893945}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,465] Trial 380 finished with value: 0.9495707063691526 and parameters: {'weight_class_0': 0.0032837333662221226, 'weight_class_1': 0.05954584921788465, 'weight_class_2': 0.035118426485218}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,472] Trial 382 finished with value: 0.9495936065192075 and parameters: {'weight_class_0': 0.003393162378030887, 'weight_class_1': 0.05620559707905994, 'weight_class_2': 0.03771017732523037}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,476] Trial 381 finished with value: 0.9492643464118374 and parameters: {'weight_class_0': 0.0033659940141858376, 'weight_class_1': 0.02869827192088664, 'weight_class_2': 0.043487337446614066}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,505] Trial 383 finished with value: 0.9495097678648857 and parameters: {'weight_class_0': 0.0031029537804334877, 'weight_class_1': 0.06043676511063593, 'weight_class_2': 0.0403895965223251}. Best is trial 253 with value: 0.9496914284413952.

Best trial: 253. Best value: 0.949691:  13%|█████████████████▍                                                                                                                  | 396/3000 [00:06<00:42, 60.81it/s]

[I 2026-07-03 10:56:30,519] Trial 384 finished with value: 0.9494106983003544 and parameters: {'weight_class_0': 0.003086043930703372, 'weight_class_1': 0.02796272227606835, 'weight_class_2': 0.03783165671182476}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,531] Trial 385 finished with value: 0.9492974295956685 and parameters: {'weight_class_0': 0.0032112082362551466, 'weight_class_1': 0.02959759606302788, 'weight_class_2': 0.043080943626673175}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,532] Trial 386 finished with value: 0.9493291277758087 and parameters: {'weight_class_0': 0.0031155967504253148, 'weight_class_1': 0.05845333441995221, 'weight_class_2': 0.02307209422798437}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,537] Trial 387 finished with value: 0.8930791185271629 and parameters: {'weight_class_0': 0.04101676553069398, 'weight_class_1': 0.05815798543067997, 'weight_class_2': 0.04567292136350837}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,558] Trial 388 finished with value: 0.8695417052274529 and parameters: {'weight_class_0': 0.04849983437713832, 'weight_class_1': 0.05542340707129051, 'weight_class_2': 0.023589184921167055}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,588] Trial 389 finished with value: 0.9494251814919467 and parameters: {'weight_class_0': 0.0029597923550430225, 'weight_class_1': 0.029354033063123074, 'weight_class_2': 0.023322523226208956}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,598] Trial 390 finished with value: 0.9495053102924773 and parameters: {'weight_class_0': 0.002953608069246899, 'weight_class_1': 0.02701344495820951, 'weight_class_2': 0.024277220259004847}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,619] Trial 391 finished with value: 0.9492450664263933 and parameters: {'weight_class_0': 0.0030493326344201836, 'weight_class_1': 0.029620143332908088, 'weight_class_2': 0.02312065608877664}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,640] Trial 392 finished with value: 0.9494586857155404 and parameters: {'weight_class_0': 0.0027863003369756616, 'weight_class_1': 0.0288757888286505, 'weight_class_2': 0.022371240759281357}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,684] Trial 394 finished with value: 0.9496723812395457 and parameters: {'weight_class_0': 0.0020697455405724865, 'weight_class_1': 0.0296761540894088, 'weight_class_2': 0.023694806718209536}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,705] Trial 393 finished with value: 0.9495942869028542 and parameters: {'weight_class_0': 0.0027463425480152496, 'weight_class_1': 0.0302464970097264, 'weight_class_2': 0.02385590233349046}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,721] Trial 395 finished with value: 0.9496111792481466 and parameters: {'weight_class_0': 0.0026544687524693873, 'weight_class_1': 0.029658659174441493, 'weight_class_2': 0.023230921754833194}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,742] Trial 396 finished with value: 0.9495864387304813 and parameters: {'weight_class_0': 0.002641586167686527, 'weight_class_1': 0.029419249680875302, 'weight_class_2': 0.024788473672082346}. Best is trial 253 with value: 0.9496914284413952.

Best trial: 253. Best value: 0.949691:  14%|██████████████████                                                                                                                  | 410/3000 [00:07<00:41, 62.83it/s]

[I 2026-07-03 10:56:30,774] Trial 397 finished with value: 0.9495920247551591 and parameters: {'weight_class_0': 0.002739504713737195, 'weight_class_1': 0.029799441185268775, 'weight_class_2': 0.02334593525962493}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,777] Trial 399 finished with value: 0.9463409484004277 and parameters: {'weight_class_0': 0.004778365545267964, 'weight_class_1': 0.024504094683364428, 'weight_class_2': 0.022041736912454705}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,777] Trial 398 finished with value: 0.9495553653305245 and parameters: {'weight_class_0': 0.0026456446024127568, 'weight_class_1': 0.029233613004065344, 'weight_class_2': 0.02384214596762998}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,792] Trial 400 finished with value: 0.9496403757166152 and parameters: {'weight_class_0': 0.002176458870540524, 'weight_class_1': 0.030359462707639295, 'weight_class_2': 0.02329881340060846}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,802] Trial 401 finished with value: 0.9441808334728753 and parameters: {'weight_class_0': 0.004916577056560787, 'weight_class_1': 0.02292524702657643, 'weight_class_2': 0.01832514843349095}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,823] Trial 402 finished with value: 0.9492371241059536 and parameters: {'weight_class_0': 0.0020222227349922886, 'weight_class_1': 0.02382830248830811, 'weight_class_2': 0.01434094750858058}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,839] Trial 403 finished with value: 0.9491643765606241 and parameters: {'weight_class_0': 0.0020401704921464226, 'weight_class_1': 0.024601512753341277, 'weight_class_2': 0.014150661895066622}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,860] Trial 404 finished with value: 0.9495276798298254 and parameters: {'weight_class_0': 0.002066871690437142, 'weight_class_1': 0.03251960571992848, 'weight_class_2': 0.02863535219045409}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,862] Trial 406 finished with value: 0.9494386382155504 and parameters: {'weight_class_0': 0.002047521149780282, 'weight_class_1': 0.04420135026670429, 'weight_class_2': 0.026937151338361557}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,866] Trial 405 finished with value: 0.9494949914174985 and parameters: {'weight_class_0': 0.002055477142075283, 'weight_class_1': 0.03166780662947988, 'weight_class_2': 0.028740865896470156}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,898] Trial 407 finished with value: 0.9486883256035865 and parameters: {'weight_class_0': 0.0048803341797581425, 'weight_class_1': 0.044214693083962024, 'weight_class_2': 0.029379999376789895}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,914] Trial 408 finished with value: 0.5929893493692682 and parameters: {'weight_class_0': 0.0020362906375454835, 'weight_class_1': 9.254868623190214, 'weight_class_2': 0.02911536722048542}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,930] Trial 409 finished with value: 0.949348553970017 and parameters: {'weight_class_0': 0.0020232989074789273, 'weight_class_1': 0.04272508482101358, 'weight_class_2': 0.029097568121382283}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,953] Trial 410 finished with value: 0.9493250362066806 and parameters: {'weight_class_0': 0.002026826609537834, 'weight_class_1': 0.043563725061509906, 'weight_class_2': 0.02943146705440125}. Best is trial 253 with value: 0.9496914284413952.

Best trial: 253. Best value: 0.949691:  14%|██████████████████▋                                                                                                                 | 424/3000 [00:07<00:41, 62.18it/s]

[I 2026-07-03 10:56:30,964] Trial 411 finished with value: 0.9493989057227722 and parameters: {'weight_class_0': 0.002152590687865016, 'weight_class_1': 0.04407454715356959, 'weight_class_2': 0.030184124624280745}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:30,982] Trial 412 finished with value: 0.9494436590529528 and parameters: {'weight_class_0': 0.002055116883818933, 'weight_class_1': 0.04289904934168339, 'weight_class_2': 0.028305624757003624}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,017] Trial 413 finished with value: 0.9492691236487939 and parameters: {'weight_class_0': 0.002045707632386128, 'weight_class_1': 0.04682355098609972, 'weight_class_2': 0.02917328898324398}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,033] Trial 414 finished with value: 0.9493506531882737 and parameters: {'weight_class_0': 0.0020945743328603618, 'weight_class_1': 0.04407710367111635, 'weight_class_2': 0.0294015461352986}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,040] Trial 416 finished with value: 0.9495732340932247 and parameters: {'weight_class_0': 0.0023204299416041217, 'weight_class_1': 0.0446846875611624, 'weight_class_2': 0.02921686889789671}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,040] Trial 415 finished with value: 0.9495888478605744 and parameters: {'weight_class_0': 0.002310377829993914, 'weight_class_1': 0.043241351778150264, 'weight_class_2': 0.02851321615673133}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,072] Trial 417 finished with value: 0.5550349787341373 and parameters: {'weight_class_0': 0.0023984299686985334, 'weight_class_1': 8.80111837142956, 'weight_class_2': 0.01846497872780293}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,083] Trial 418 finished with value: 0.8973688920625285 and parameters: {'weight_class_0': 0.002431530613711862, 'weight_class_1': 0.0010333817392246816, 'weight_class_2': 0.018165749968308692}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,092] Trial 420 finished with value: 0.9494957486909475 and parameters: {'weight_class_0': 0.001600784999561195, 'weight_class_1': 0.036588122451605753, 'weight_class_2': 0.018688596100951617}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,101] Trial 419 finished with value: 0.938291808561763 and parameters: {'weight_class_0': 0.008034424347628386, 'weight_class_1': 0.042693513931846935, 'weight_class_2': 0.019590921078269374}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,121] Trial 421 finished with value: 0.6790316466730283 and parameters: {'weight_class_0': 0.006260143233991825, 'weight_class_1': 0.018225865299828954, 'weight_class_2': 5.184882101966383}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,134] Trial 422 finished with value: 0.9259347451176406 and parameters: {'weight_class_0': 0.007240918559369842, 'weight_class_1': 0.72527519718074, 'weight_class_2': 0.018635631076067263}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,162] Trial 423 finished with value: 0.9495624967228018 and parameters: {'weight_class_0': 0.0016280888854904249, 'weight_class_1': 0.017986720733876724, 'weight_class_2': 0.01881311241785369}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,183] Trial 424 finished with value: 0.9495667932238255 and parameters: {'weight_class_0': 0.001627020633653009, 'weight_class_1': 0.017974007514253758, 'weight_class_2': 0.018124726965342543}. Best is trial 253 with value: 0.9496914284413952.

Best trial: 253. Best value: 0.949691:  15%|███████████████████▏                                                                                                                | 437/3000 [00:07<00:41, 61.39it/s]

[I 2026-07-03 10:56:31,189] Trial 425 finished with value: 0.9496047013216318 and parameters: {'weight_class_0': 0.0015804472202866052, 'weight_class_1': 0.017644649528588453, 'weight_class_2': 0.018051215019734827}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,199] Trial 426 finished with value: 0.9491475884201132 and parameters: {'weight_class_0': 0.002573703347157274, 'weight_class_1': 0.019418149082612614, 'weight_class_2': 0.02042681902474838}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,232] Trial 427 finished with value: 0.8194585022321862 and parameters: {'weight_class_0': 0.14376808936685073, 'weight_class_1': 0.017280468843690673, 'weight_class_2': 0.017985284204825175}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,255] Trial 428 finished with value: 0.9495519867404113 and parameters: {'weight_class_0': 0.0016297843432207147, 'weight_class_1': 0.017490265133699837, 'weight_class_2': 0.018496955913373223}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,274] Trial 429 finished with value: 0.9495842095767751 and parameters: {'weight_class_0': 0.0015792833799549177, 'weight_class_1': 0.017715442129677895, 'weight_class_2': 0.014591850590141975}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,275] Trial 430 finished with value: 0.9495728955434889 and parameters: {'weight_class_0': 0.0016696005179919074, 'weight_class_1': 0.01811918462901344, 'weight_class_2': 0.013793355249831517}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,301] Trial 431 finished with value: 0.9473983653046183 and parameters: {'weight_class_0': 0.0015650229680299584, 'weight_class_1': 0.01834234563762194, 'weight_class_2': 0.053070065350319294}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,308] Trial 432 finished with value: 0.949501039990227 and parameters: {'weight_class_0': 0.0016854328084563988, 'weight_class_1': 0.017801069785319736, 'weight_class_2': 0.014188100750061224}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,340] Trial 435 finished with value: 0.9485836301653929 and parameters: {'weight_class_0': 0.00260784379828826, 'weight_class_1': 0.034938586513436454, 'weight_class_2': 0.014200904243727787}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,345] Trial 433 finished with value: 0.945234038185149 and parameters: {'weight_class_0': 0.0016408197261806381, 'weight_class_1': 0.09717295671490418, 'weight_class_2': 0.04979828601417553}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,355] Trial 434 finished with value: 0.9486981080946881 and parameters: {'weight_class_0': 0.002682464280890585, 'weight_class_1': 0.03351118127361444, 'weight_class_2': 0.05651469239846102}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,375] Trial 436 finished with value: 0.9482154510097925 and parameters: {'weight_class_0': 0.002742594143512709, 'weight_class_1': 0.09422249703183772, 'weight_class_2': 0.05721439946308696}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,386] Trial 437 finished with value: 0.9484056428942244 and parameters: {'weight_class_0': 0.00263968658978631, 'weight_class_1': 0.03467080398422605, 'weight_class_2': 0.013763348312497703}. Best is trial 253 with value: 0.9496914284413952.

[I 2026-07-03 10:56:31,392] Trial 438 finished with value: 0.9439984512805687 and parameters: {'weight_class_0': 0.00450767061405361, 'weight_class_1': 0.033052443365016185, 'weight_class_2': 0.014409042829451615}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,416] Trial 439 finished with value: 0.948365278012913 and parameters: {'weight_class_0': 0.002631434943909484, 'weight_class_1': 0.03388699446262283, 'weight_class_2': 0.013591327174893407}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,434] Trial 440 finished with value: 0.9489056463924069 and parameters: {'weight_class_0': 0.002645775963528861, 'weight_class_1': 0.03350737326806252, 'weight_class_2': 0.04990866672171628}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,454] Trial 442 finished with value: 0.9109469590916444 and parameters: {'weight_class_0': 0.0043805708808912994, 'weight_class_1': 0.0036176996385268788, 'weight_class_2': 0.022274944727143624}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,455] Trial 441 finished with value: 0.9496619776636832 and parameters: {'weight_class_0': 0.0027182118674289285, 'weight_class_1': 0.0339860925266586, 'weight_class_2': 0.022314199625912842}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,481] Trial 443 finished with value: 0.9477473322156132 and parameters: {'weight_class_0': 0.004553356142739445, 'weight_class_1': 0.03419552316516615, 'weight_class_2': 0.022798946040079968}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,497] Trial 444 finished with value: 0.9481709441342918 and parameters: {'weight_class_0': 0.0044007720674363315, 'weight_class_1': 0.0344053332389137, 'weight_class_2': 0.023694358952159118}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,522] Trial 445 finished with value: 0.9485456016984757 and parameters: {'weight_class_0': 0.003368613846645531, 'weight_class_1': 0.023486537864055083, 'weight_class_2': 0.022142611174672696}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,541] Trial 446 finished with value: 0.9488288775593139 and parameters: {'weight_class_0': 0.0032486418849047402, 'weight_class_1': 0.024797535132550765, 'weight_class_2': 0.022597070662536075}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,572] Trial 448 finished with value: 0.9485047723516847 and parameters: {'weight_class_0': 0.003536027492429444, 'weight_class_1': 0.024490862266184073, 'weight_class_2': 0.023041818993177903}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,574] Trial 447 finished with value: 0.9482918125339882 and parameters: {'weight_class_0': 0.003381384043568951, 'weight_class_1': 0.02220803855285086, 'weight_class_2': 0.021365502645610806}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,595] Trial 449 finished with value: 0.9487946189917738 and parameters: {'weight_class_0': 0.0033271892801849078, 'weight_class_1': 0.02524874094994171, 'weight_class_2': 0.0225718473932937}. Best is trial 253 with value: 0.9496914284413952.

[I 2026-07-03 10:56:31,628] Trial 451 finished with value: 0.9488462515970298 and parameters: {'weight_class_0': 0.003312356867688643, 'weight_class_1': 0.024095396534856015, 'weight_class_2': 0.02326215500752825}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,636] Trial 450 finished with value: 0.9486241997961476 and parameters: {'weight_class_0': 0.003408881651851048, 'weight_class_1': 0.024734174442536564, 'weight_class_2': 0.022091530715690495}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,638] Trial 452 finished with value: 0.6263673423489227 and parameters: {'weight_class_0': 0.0033064235747927826, 'weight_class_1': 5.947999536375573, 'weight_class_2': 0.025253867563034927}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,656] Trial 454 finished with value: 0.9490997921654651 and parameters: {'weight_class_0': 0.0032131342111853026, 'weight_class_1': 0.025308886943800075, 'weight_class_2': 0.024210352014031426}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,658] Trial 453 finished with value: 0.9486934652613067 and parameters: {'weight_class_0': 0.0035548977921861366, 'weight_class_1': 0.025327146662617855, 'weight_class_2': 0.023807984607869585}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,660] Trial 455 finished with value: 0.9038723391247162 and parameters: {'weight_class_0': 0.003419911992649982, 'weight_class_1': 0.0257662261190847, 'weight_class_2': 0.002655790023574154}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,684] Trial 456 finished with value: 0.8960020672415947 and parameters: {'weight_class_0': 0.003354729066093199, 'weight_class_1': 0.025409411141186607, 'weight_class_2': 0.001363677160333593}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,702] Trial 457 finished with value: 0.9495650197047301 and parameters: {'weight_class_0': 0.0032450510087415002, 'weight_class_1': 0.05265945674852581, 'weight_class_2': 0.0333024513392937}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,723] Trial 458 finished with value: 0.44400171446780745 and parameters: {'weight_class_0': 0.0033042066050073355, 'weight_class_1': 5.804304983125561, 'weight_class_2': 0.001935243637919469}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,727] Trial 459 finished with value: 0.7285557438670153 and parameters: {'weight_class_0': 0.6086461547492708, 'weight_class_1': 0.05070365633492703, 'weight_class_2': 0.0028924567346087088}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,748] Trial 460 finished with value: 0.8188812978796536 and parameters: {'weight_class_0': 0.002365342434062609, 'weight_class_1': 0.9190995466586307, 'weight_class_2': 0.033124082836194065}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,778] Trial 461 finished with value: 0.9493931189866456 and parameters: {'weight_class_0': 0.0024333666946562845, 'weight_class_1': 0.05048657825588022, 'weight_class_2': 0.033952371560095396}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,789] Trial 462 finished with value: 0.7925006156070925 and parameters: {'weight_class_0': 0.002287234748573856, 'weight_class_1': 1.077647621409213, 'weight_class_2': 0.03275638769166249}. Best is trial 253 with value: 0.9496914284413952.

Best trial: 253. Best value: 0.949691:  16%|████████████████████▊                                                                                                               | 474/3000 [00:08<00:43, 58.28it/s]

[I 2026-07-03 10:56:31,829] Trial 464 finished with value: 0.9494447477213361 and parameters: {'weight_class_0': 0.0023622269248427512, 'weight_class_1': 0.05112310183032696, 'weight_class_2': 0.0320399889853065}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,841] Trial 463 finished with value: 0.9494900882822169 and parameters: {'weight_class_0': 0.0023446171815020723, 'weight_class_1': 0.037611765313873134, 'weight_class_2': 0.03360099773842955}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,849] Trial 465 finished with value: 0.786040168534987 and parameters: {'weight_class_0': 1.7226510097520702, 'weight_class_1': 0.03805813989350973, 'weight_class_2': 0.034133527412577636}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,867] Trial 466 finished with value: 0.9070822700864376 and parameters: {'weight_class_0': 0.0022830225267512277, 'weight_class_1': 0.0015051600561841309, 'weight_class_2': 0.034436966612204946}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,883] Trial 467 finished with value: 0.9491378898002739 and parameters: {'weight_class_0': 0.0021423996502910607, 'weight_class_1': 0.05119703152936402, 'weight_class_2': 0.03289529007636723}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,887] Trial 468 finished with value: 0.7979391632345659 and parameters: {'weight_class_0': 1.5876509024326764, 'weight_class_1': 0.05257781401683893, 'weight_class_2': 0.03297679683232226}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,907] Trial 469 finished with value: 0.9494820348777381 and parameters: {'weight_class_0': 0.002301013851540073, 'weight_class_1': 0.037150515258680405, 'weight_class_2': 0.03313677279772216}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,914] Trial 470 finished with value: 0.9494301327101767 and parameters: {'weight_class_0': 0.0022384448260489628, 'weight_class_1': 0.038106064012333025, 'weight_class_2': 0.03289632914284569}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,950] Trial 473 finished with value: 0.9487526041847447 and parameters: {'weight_class_0': 0.0019427890765184067, 'weight_class_1': 0.03681667068157724, 'weight_class_2': 0.042331358479400845}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,967] Trial 472 finished with value: 0.9487750524443507 and parameters: {'weight_class_0': 0.0018981708578835062, 'weight_class_1': 0.03668025248885206, 'weight_class_2': 0.04111434311644163}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,973] Trial 471 finished with value: 0.9487982230741672 and parameters: {'weight_class_0': 0.0019384704097189038, 'weight_class_1': 0.03825993977178091, 'weight_class_2': 0.04031819502685283}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:31,999] Trial 474 finished with value: 0.9487943921616727 and parameters: {'weight_class_0': 0.0018924485129634017, 'weight_class_1': 0.03925179479617974, 'weight_class_2': 0.03928305066049102}. Best is trial 253 with value: 0.9496914284413952.

Best trial: 253. Best value: 0.949691:  16%|█████████████████████▍                                                                                                              | 486/3000 [00:08<00:43, 58.07it/s]

[I 2026-07-03 10:56:32,019] Trial 475 finished with value: 0.9486997237161242 and parameters: {'weight_class_0': 0.002029097508641923, 'weight_class_1': 0.030350286814984837, 'weight_class_2': 0.04306059384706603}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,022] Trial 476 finished with value: 0.9495792019234695 and parameters: {'weight_class_0': 0.0019338036295476575, 'weight_class_1': 0.03031633412080174, 'weight_class_2': 0.01731389575703891}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,057] Trial 477 finished with value: 0.9495776739681272 and parameters: {'weight_class_0': 0.0018540960976189565, 'weight_class_1': 0.030379182124467812, 'weight_class_2': 0.016866994434442596}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,098] Trial 478 finished with value: 0.941481335653476 and parameters: {'weight_class_0': 0.005781611381801632, 'weight_class_1': 0.029831047542469465, 'weight_class_2': 0.01664061721515433}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,100] Trial 479 finished with value: 0.9496502190004072 and parameters: {'weight_class_0': 0.001919862618352763, 'weight_class_1': 0.031149398466623835, 'weight_class_2': 0.016482577226654214}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,119] Trial 481 finished with value: 0.949573071348634 and parameters: {'weight_class_0': 0.0018877553884858707, 'weight_class_1': 0.03004204142809689, 'weight_class_2': 0.017008710179179154}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,119] Trial 480 finished with value: 0.9495993167453979 and parameters: {'weight_class_0': 0.0018872480699159153, 'weight_class_1': 0.03153102308622436, 'weight_class_2': 0.016887061496779945}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,127] Trial 482 finished with value: 0.9489251058026845 and parameters: {'weight_class_0': 0.002734843241970619, 'weight_class_1': 0.029817403284434812, 'weight_class_2': 0.017704167318271326}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,156] Trial 483 finished with value: 0.9487117411234571 and parameters: {'weight_class_0': 0.0028515470680545805, 'weight_class_1': 0.029798448093371406, 'weight_class_2': 0.01681477144029908}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,184] Trial 484 finished with value: 0.9487290180141189 and parameters: {'weight_class_0': 0.002803946687946717, 'weight_class_1': 0.03003429038916164, 'weight_class_2': 0.016723483912300913}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,211] Trial 486 finished with value: 0.9493309763087686 and parameters: {'weight_class_0': 0.0026543852284311776, 'weight_class_1': 0.06798724341908247, 'weight_class_2': 0.026304853392285634}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,213] Trial 485 finished with value: 0.9493482338702098 and parameters: {'weight_class_0': 0.0029029342259659454, 'weight_class_1': 0.07092440188243448, 'weight_class_2': 0.026369481328856106}. Best is trial 253 with value: 0.9496914284413952.

Best trial: 253. Best value: 0.949691:  17%|█████████████████████▉                                                                                                              | 498/3000 [00:08<00:43, 56.98it/s]

[I 2026-07-03 10:56:32,228] Trial 487 finished with value: 0.9493807866005836 and parameters: {'weight_class_0': 0.00287655442862278, 'weight_class_1': 0.07123274424868922, 'weight_class_2': 0.0269457111286936}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,254] Trial 488 finished with value: 0.949597789093593 and parameters: {'weight_class_0': 0.002819748133634805, 'weight_class_1': 0.030692096110782975, 'weight_class_2': 0.026510325068733312}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,270] Trial 489 finished with value: 0.9475236802129157 and parameters: {'weight_class_0': 0.002784996709727843, 'weight_class_1': 0.07714042319893737, 'weight_class_2': 0.013610857154064876}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,299] Trial 490 finished with value: 0.9472837108728722 and parameters: {'weight_class_0': 0.0027778993809060297, 'weight_class_1': 0.06872664031657587, 'weight_class_2': 0.012596240793954112}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,311] Trial 491 finished with value: 0.9493346831968846 and parameters: {'weight_class_0': 0.0027403171945534766, 'weight_class_1': 0.07089621718166567, 'weight_class_2': 0.026698280860403444}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,334] Trial 492 finished with value: 0.9477106292644558 and parameters: {'weight_class_0': 0.002652520639196433, 'weight_class_1': 0.06436623030248896, 'weight_class_2': 0.01304471696752464}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,339] Trial 493 finished with value: 0.9439411141025341 and parameters: {'weight_class_0': 0.0044584139723346464, 'weight_class_1': 0.07090656626751146, 'weight_class_2': 0.013674348728069791}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,361] Trial 494 finished with value: 0.9488805404825186 and parameters: {'weight_class_0': 0.004213548949123089, 'weight_class_1': 0.07968834530631029, 'weight_class_2': 0.026330736557107937}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,382] Trial 495 finished with value: 0.947671991186564 and parameters: {'weight_class_0': 0.0028239590381388324, 'weight_class_1': 0.06575389671803968, 'weight_class_2': 0.013600853437452506}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,400] Trial 497 finished with value: 0.9429514479070904 and parameters: {'weight_class_0': 0.004091235057948009, 'weight_class_1': 0.021959880388573688, 'weight_class_2': 0.01291576085234916}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,419] Trial 496 finished with value: 0.9409899746007183 and parameters: {'weight_class_0': 0.004147879004025797, 'weight_class_1': 0.022191146506695278, 'weight_class_2': 0.011531595350469733}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,436] Trial 498 finished with value: 0.9423542165700205 and parameters: {'weight_class_0': 0.00429987822875924, 'weight_class_1': 0.022214874030058247, 'weight_class_2': 0.012979347724773122}. Best is trial 253 with value: 0.9496914284413952.

Best trial: 253. Best value: 0.949691:  17%|██████████████████████▍                                                                                                             | 510/3000 [00:08<00:42, 58.18it/s]

[I 2026-07-03 10:56:32,450] Trial 500 finished with value: 0.9496167064140503 and parameters: {'weight_class_0': 0.0014396268192851188, 'weight_class_1': 0.020620656210404525, 'weight_class_2': 0.013029833166179717}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,464] Trial 499 finished with value: 0.9429402440423783 and parameters: {'weight_class_0': 0.004253833959296144, 'weight_class_1': 0.04284008819426003, 'weight_class_2': 0.012255383794793274}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,481] Trial 501 finished with value: 0.9486502132577538 and parameters: {'weight_class_0': 0.001476361485208723, 'weight_class_1': 0.0227609387107733, 'weight_class_2': 0.00829129968389507}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,505] Trial 502 finished with value: 0.9495293752352634 and parameters: {'weight_class_0': 0.0014488436883853442, 'weight_class_1': 0.0219065351816185, 'weight_class_2': 0.019919890957670043}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,541] Trial 503 finished with value: 0.9496283911508038 and parameters: {'weight_class_0': 0.0015038995981007947, 'weight_class_1': 0.0214009527190483, 'weight_class_2': 0.0196236736052705}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,552] Trial 504 finished with value: 0.9495522384179673 and parameters: {'weight_class_0': 0.001486574377575218, 'weight_class_1': 0.022002748330213394, 'weight_class_2': 0.020529233685614923}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,559] Trial 505 finished with value: 0.692210868019235 and parameters: {'weight_class_0': 0.0015026772157596933, 'weight_class_1': 0.04328718818414255, 'weight_class_2': 2.0633631196755498}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,583] Trial 506 finished with value: 0.9496626528485872 and parameters: {'weight_class_0': 0.0015908653927704899, 'weight_class_1': 0.021312353225108244, 'weight_class_2': 0.01959046379066404}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,593] Trial 507 finished with value: 0.9492091337256628 and parameters: {'weight_class_0': 0.0014991565671398479, 'weight_class_1': 0.04267065363697668, 'weight_class_2': 0.02025079550129048}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,613] Trial 508 finished with value: 0.9486223708009242 and parameters: {'weight_class_0': 0.0012640639468927066, 'weight_class_1': 0.04361694657211725, 'weight_class_2': 0.02112969788350979}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,616] Trial 509 finished with value: 0.9480714593991731 and parameters: {'weight_class_0': 0.0015023140389122092, 'weight_class_1': 0.04401033821385984, 'weight_class_2': 0.008529874443108447}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,640] Trial 510 finished with value: 0.949125672623615 and parameters: {'weight_class_0': 0.0014899885013588334, 'weight_class_1': 0.04363726594095504, 'weight_class_2': 0.020518123736546948}. Best is trial 253 with value: 0.9496914284413952.

Best trial: 253. Best value: 0.949691:  17%|██████████████████████▉                                                                                                             | 520/3000 [00:09<00:44, 55.22it/s]

[I 2026-07-03 10:56:32,678] Trial 511 finished with value: 0.9490723600382646 and parameters: {'weight_class_0': 0.001447989934808862, 'weight_class_1': 0.045418499949385426, 'weight_class_2': 0.019294922333363867}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,689] Trial 512 finished with value: 0.948571340309269 and parameters: {'weight_class_0': 0.0011737505535140869, 'weight_class_1': 0.041680909199926196, 'weight_class_2': 0.019596555916279536}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,708] Trial 513 finished with value: 0.9490996061289279 and parameters: {'weight_class_0': 0.0014461839528424358, 'weight_class_1': 0.04316947164527644, 'weight_class_2': 0.020010324596126713}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,743] Trial 515 finished with value: 0.8144119023466212 and parameters: {'weight_class_0': 0.34913340942011556, 'weight_class_1': 0.038683314413872044, 'weight_class_2': 0.020038528857914933}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,744] Trial 514 finished with value: 0.9451088815564349 and parameters: {'weight_class_0': 0.00568337377845277, 'weight_class_1': 0.04085513859614166, 'weight_class_2': 0.019838063810546588}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,754] Trial 516 finished with value: 0.9485643155990635 and parameters: {'weight_class_0': 0.0011811987790780727, 'weight_class_1': 0.04059717927985305, 'weight_class_2': 0.020259323189880846}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,775] Trial 517 finished with value: 0.9487572835351953 and parameters: {'weight_class_0': 0.00115934134195145, 'weight_class_1': 0.011986126347667604, 'weight_class_2': 0.02068111341608849}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,801] Trial 518 finished with value: 0.8858921966281881 and parameters: {'weight_class_0': 0.020723537308978555, 'weight_class_1': 0.02643132213146616, 'weight_class_2': 0.020363212543997703}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,833] Trial 519 finished with value: 0.9483044871555038 and parameters: {'weight_class_0': 0.0011827277568286349, 'weight_class_1': 0.012199676188466638, 'weight_class_2': 0.025766684207845014}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,836] Trial 520 finished with value: 0.9484860170253864 and parameters: {'weight_class_0': 0.0011410606559426116, 'weight_class_1': 0.026092150914529905, 'weight_class_2': 0.026618844437008436}. Best is trial 253 with value: 0.9496914284413952.

Best trial: 253. Best value: 0.949691:  18%|███████████████████████▍                                                                                                            | 532/3000 [00:09<00:44, 55.12it/s]

[I 2026-07-03 10:56:32,848] Trial 521 finished with value: 0.9147301860432858 and parameters: {'weight_class_0': 0.0011990741120717293, 'weight_class_1': 0.025400969222166992, 'weight_class_2': 0.23390958261051348}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,865] Trial 522 finished with value: 0.9481270426328923 and parameters: {'weight_class_0': 0.0011440387719640363, 'weight_class_1': 0.012777952341790879, 'weight_class_2': 0.027828087957332052}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,888] Trial 523 finished with value: 0.9496208712967137 and parameters: {'weight_class_0': 0.002285879754569118, 'weight_class_1': 0.02616272311529613, 'weight_class_2': 0.026814701433349204}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,904] Trial 525 finished with value: 0.9496805456204148 and parameters: {'weight_class_0': 0.0023034750635164795, 'weight_class_1': 0.027743304505558116, 'weight_class_2': 0.02650072192670792}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,904] Trial 524 finished with value: 0.9496197054272768 and parameters: {'weight_class_0': 0.002229582337118221, 'weight_class_1': 0.025958954827984347, 'weight_class_2': 0.026244670996439776}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,935] Trial 526 finished with value: 0.6610736725032162 and parameters: {'weight_class_0': 3.2240852576924532, 'weight_class_1': 0.027221592774691907, 'weight_class_2': 0.026002859512282688}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,987] Trial 528 finished with value: 0.9496084459917582 and parameters: {'weight_class_0': 0.0023202950498132416, 'weight_class_1': 0.026211684417724312, 'weight_class_2': 0.028058780375774414}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,996] Trial 529 finished with value: 0.9415058033399605 and parameters: {'weight_class_0': 0.0022877218398229624, 'weight_class_1': 0.026257262718171366, 'weight_class_2': 0.22426298590256052}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:32,998] Trial 527 finished with value: 0.9496415973763539 and parameters: {'weight_class_0': 0.0023261569999599415, 'weight_class_1': 0.026391496995121336, 'weight_class_2': 0.02660601289124441}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,015] Trial 530 finished with value: 0.9493856485311148 and parameters: {'weight_class_0': 0.001876205980201053, 'weight_class_1': 0.03502603005182534, 'weight_class_2': 0.02836491645523977}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,028] Trial 531 finished with value: 0.9495807346383741 and parameters: {'weight_class_0': 0.0018707878862389555, 'weight_class_1': 0.03382820221091021, 'weight_class_2': 0.015670693655798644}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,067] Trial 532 finished with value: 0.6824602382225661 and parameters: {'weight_class_0': 0.002018206574121112, 'weight_class_1': 2.4968926203234276, 'weight_class_2': 0.02540130338204637}. Best is trial 253 with value: 0.9496914284413952.

Best trial: 253. Best value: 0.949691:  18%|███████████████████████▉                                                                                                            | 544/3000 [00:09<00:47, 51.99it/s]

[I 2026-07-03 10:56:33,101] Trial 534 finished with value: 0.9494261150801373 and parameters: {'weight_class_0': 0.001945675596057765, 'weight_class_1': 0.03283570868265356, 'weight_class_2': 0.02905963609509629}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,113] Trial 533 finished with value: 0.9496294029265234 and parameters: {'weight_class_0': 0.002434238343806031, 'weight_class_1': 0.034846950035214264, 'weight_class_2': 0.02963868903963158}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,128] Trial 535 finished with value: 0.9493154033667691 and parameters: {'weight_class_0': 0.0018567414845558534, 'weight_class_1': 0.03425913330096276, 'weight_class_2': 0.028998558698228306}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,171] Trial 537 finished with value: 0.949428232442794 and parameters: {'weight_class_0': 0.002003628435544308, 'weight_class_1': 0.034279565522381455, 'weight_class_2': 0.02944612697501665}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,171] Trial 536 finished with value: 0.9493268935213042 and parameters: {'weight_class_0': 0.0018453389651467897, 'weight_class_1': 0.03485859655500559, 'weight_class_2': 0.029142869453688134}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,203] Trial 538 finished with value: 0.9496147870437858 and parameters: {'weight_class_0': 0.0023366034920292516, 'weight_class_1': 0.033811876647842944, 'weight_class_2': 0.02382642657471795}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,219] Trial 539 finished with value: 0.9496316380782042 and parameters: {'weight_class_0': 0.0018160700578785573, 'weight_class_1': 0.03446780983099411, 'weight_class_2': 0.015817467981081284}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,245] Trial 542 finished with value: 0.9494575488826235 and parameters: {'weight_class_0': 0.0037182019211290493, 'weight_class_1': 0.03479104294715622, 'weight_class_2': 0.040098310924650785}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,249] Trial 540 finished with value: 0.949614560804401 and parameters: {'weight_class_0': 0.003745592321709825, 'weight_class_1': 0.0574621808771312, 'weight_class_2': 0.04115574331258796}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,251] Trial 541 finished with value: 0.9489374601593593 and parameters: {'weight_class_0': 0.0037376515837194667, 'weight_class_1': 0.052311638598371527, 'weight_class_2': 0.02327365993524247}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,289] Trial 543 finished with value: 0.9487805896250124 and parameters: {'weight_class_0': 0.003703505201802807, 'weight_class_1': 0.034537524419962426, 'weight_class_2': 0.02324202413582715}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,300] Trial 546 finished with value: 0.94832915745504 and parameters: {'weight_class_0': 0.0036528429098191986, 'weight_class_1': 0.02000879261843298, 'weight_class_2': 0.041459237363941026}. Best is trial 253 with value: 0.9496914284413952.

Best trial: 253. Best value: 0.949691:  19%|████████████████████████▍                                                                                                           | 556/3000 [00:09<00:45, 53.25it/s]

[I 2026-07-03 10:56:33,308] Trial 544 finished with value: 0.9488235397320676 and parameters: {'weight_class_0': 0.003779567808032386, 'weight_class_1': 0.03373011030997025, 'weight_class_2': 0.023901495558941378}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,319] Trial 545 finished with value: 0.8849044120184965 and parameters: {'weight_class_0': 0.003587936405931487, 'weight_class_1': 0.05504193761374505, 'weight_class_2': 0.9586079200631186}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,337] Trial 547 finished with value: 0.9475327104691301 and parameters: {'weight_class_0': 0.0038500690021573323, 'weight_class_1': 0.05129796925045495, 'weight_class_2': 0.017174006050690527}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,370] Trial 548 finished with value: 0.9473583092537133 and parameters: {'weight_class_0': 0.0037721699126502185, 'weight_class_1': 0.052354703327266106, 'weight_class_2': 0.016318497042283338}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,380] Trial 549 finished with value: 0.9495860816922481 and parameters: {'weight_class_0': 0.003482069910029148, 'weight_class_1': 0.05476579265998196, 'weight_class_2': 0.045310259022407165}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,421] Trial 550 finished with value: 0.9496313262291244 and parameters: {'weight_class_0': 0.003763465915811299, 'weight_class_1': 0.05094990760285816, 'weight_class_2': 0.048698024939806496}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,437] Trial 551 finished with value: 0.9478054559140623 and parameters: {'weight_class_0': 0.003024727836301163, 'weight_class_1': 0.019898554469487573, 'weight_class_2': 0.016216095272091075}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,461] Trial 552 finished with value: 0.941562762079248 and parameters: {'weight_class_0': 0.005259876607789014, 'weight_class_1': 0.020640867837618895, 'weight_class_2': 0.017100225668902545}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,466] Trial 553 finished with value: 0.9478854606902143 and parameters: {'weight_class_0': 0.0030683327880030417, 'weight_class_1': 0.019806147856663216, 'weight_class_2': 0.016919971288205174}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,482] Trial 554 finished with value: 0.948545257386809 and parameters: {'weight_class_0': 0.0028794719139821003, 'weight_class_1': 0.020306760108481394, 'weight_class_2': 0.018326849111113482}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,502] Trial 555 finished with value: 0.9479613856161183 and parameters: {'weight_class_0': 0.002781450778501468, 'weight_class_1': 0.016524742230335752, 'weight_class_2': 0.01680777554105031}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,516] Trial 556 finished with value: 0.9478613643957904 and parameters: {'weight_class_0': 0.0029222853676136628, 'weight_class_1': 0.0200043041781181, 'weight_class_2': 0.015511097365267644}. Best is trial 253 with value: 0.9496914284413952.

Best trial: 253. Best value: 0.949691:  19%|████████████████████████▉                                                                                                           | 567/3000 [00:09<00:45, 53.51it/s]

[I 2026-07-03 10:56:33,534] Trial 557 finished with value: 0.9472916138369102 and parameters: {'weight_class_0': 0.0029601469206341443, 'weight_class_1': 0.015314193112718682, 'weight_class_2': 0.016433962017402562}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,550] Trial 558 finished with value: 0.9488029151463317 and parameters: {'weight_class_0': 0.002986408411134423, 'weight_class_1': 0.019464434111572056, 'weight_class_2': 0.03512214326044831}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,567] Trial 559 finished with value: 0.9492563135209341 and parameters: {'weight_class_0': 0.002620160446849328, 'weight_class_1': 0.019871150991238748, 'weight_class_2': 0.021397499084993655}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,583] Trial 560 finished with value: 0.9482724658476439 and parameters: {'weight_class_0': 0.002947411936521229, 'weight_class_1': 0.016078914264222515, 'weight_class_2': 0.034699930622140836}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,606] Trial 561 finished with value: 0.9436805550711588 and parameters: {'weight_class_0': 0.005293389277207159, 'weight_class_1': 0.02026947584356897, 'weight_class_2': 0.02181934625493671}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,626] Trial 562 finished with value: 0.9436419151916665 and parameters: {'weight_class_0': 0.005267754849867138, 'weight_class_1': 0.020296759330679294, 'weight_class_2': 0.02142125496715007}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,637] Trial 563 finished with value: 0.9438459662890066 and parameters: {'weight_class_0': 0.0026187649994355183, 'weight_class_1': 0.007830881701918157, 'weight_class_2': 0.02105506642277102}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,692] Trial 565 finished with value: 0.9496483975995703 and parameters: {'weight_class_0': 0.002529929743477935, 'weight_class_1': 0.03017356606045158, 'weight_class_2': 0.021547345806616814}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,693] Trial 564 finished with value: 0.9494213154836525 and parameters: {'weight_class_0': 0.002485398453558107, 'weight_class_1': 0.028850867555126322, 'weight_class_2': 0.03476933969979895}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,719] Trial 566 finished with value: 0.9496539943851118 and parameters: {'weight_class_0': 0.0023992047678714915, 'weight_class_1': 0.02919135587939403, 'weight_class_2': 0.022733444197149243}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,723] Trial 568 finished with value: 0.9493920472729894 and parameters: {'weight_class_0': 0.0023964960256078116, 'weight_class_1': 0.02813824283234363, 'weight_class_2': 0.034868792686268336}. Best is trial 253 with value: 0.9496914284413952.

[I 2026-07-03 10:56:33,725] Trial 567 finished with value: 0.9493980286449258 and parameters: {'weight_class_0': 0.0024974369343866228, 'weight_class_1': 0.028618043002998472, 'weight_class_2': 0.03510183887071133}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,768] Trial 569 finished with value: 0.9496249121801309 and parameters: {'weight_class_0': 0.0024773195060342986, 'weight_class_1': 0.028606682663837514, 'weight_class_2': 0.023087916894373263}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,780] Trial 571 finished with value: 0.9496243510405549 and parameters: {'weight_class_0': 0.0024012601479516255, 'weight_class_1': 0.028542362081005468, 'weight_class_2': 0.02367098533555162}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,789] Trial 570 finished with value: 0.9496411315947976 and parameters: {'weight_class_0': 0.002351755367628485, 'weight_class_1': 0.028902038194602866, 'weight_class_2': 0.02274373751014275}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,809] Trial 572 finished with value: 0.9496154710229198 and parameters: {'weight_class_0': 0.00251541277521083, 'weight_class_1': 0.029479273551042868, 'weight_class_2': 0.022549221500192715}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,839] Trial 573 finished with value: 0.9496129102228079 and parameters: {'weight_class_0': 0.0022803494574697037, 'weight_class_1': 0.027854655252762282, 'weight_class_2': 0.023047441483858826}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,854] Trial 575 finished with value: 0.9496124941766603 and parameters: {'weight_class_0': 0.0023236523565102916, 'weight_class_1': 0.02828458401591986, 'weight_class_2': 0.024154891592679594}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,859] Trial 574 finished with value: 0.9496581239707688 and parameters: {'weight_class_0': 0.002252958357327698, 'weight_class_1': 0.02748063737334003, 'weight_class_2': 0.024173792659899582}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,903] Trial 576 finished with value: 0.9496457977505762 and parameters: {'weight_class_0': 0.002166025905199733, 'weight_class_1': 0.028492519268829945, 'weight_class_2': 0.023508006943897437}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,909] Trial 577 finished with value: 0.9496626754518731 and parameters: {'weight_class_0': 0.002242499668727284, 'weight_class_1': 0.027613453353587225, 'weight_class_2': 0.023938622181536872}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,914] Trial 578 finished with value: 0.9496417966689296 and parameters: {'weight_class_0': 0.002194660177496809, 'weight_class_1': 0.029321324139234647, 'weight_class_2': 0.023832123540120518}. Best is trial 253 with value: 0.9496914284413952.
[I 2026-07-03 10:56:33,934] Trial 580 finished with value: 0.9496577135273023 and parameters: {'weight_class_0': 0.0020348666170248975, 'weight_class_1': 0.02833435270348156, 'weight_class_2': 0.024350002766225662}. Best is trial 253 with value: 0.9496914284413952.

Best trial: 579. Best value: 0.949714:  20%|█████████████████████████▉                                                                                                          | 590/3000 [00:10<00:45, 53.16it/s]

[I 2026-07-03 10:56:33,941] Trial 579 finished with value: 0.9497138399884486 and parameters: {'weight_class_0': 0.002115345249391801, 'weight_class_1': 0.027388701457004984, 'weight_class_2': 0.024221842679932364}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:33,979] Trial 582 finished with value: 0.9494455841571545 and parameters: {'weight_class_0': 0.0020409273171297076, 'weight_class_1': 0.03833966605925568, 'weight_class_2': 0.029803991975209727}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:33,986] Trial 581 finished with value: 0.9494512928442562 and parameters: {'weight_class_0': 0.0017769523185475733, 'weight_class_1': 0.02440167164914389, 'weight_class_2': 0.02503614428856415}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,033] Trial 584 finished with value: 0.949176536372185 and parameters: {'weight_class_0': 0.001849521492526164, 'weight_class_1': 0.03888514045870414, 'weight_class_2': 0.03090969427453505}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,041] Trial 583 finished with value: 0.9429941650012833 and parameters: {'weight_class_0': 0.0017672393084429388, 'weight_class_1': 0.12451904238571483, 'weight_class_2': 0.07042493549522003}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,066] Trial 585 finished with value: 0.9435973375301788 and parameters: {'weight_class_0': 0.0017663302515045563, 'weight_class_1': 0.12999044195636045, 'weight_class_2': 0.02962821187198297}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,075] Trial 586 finished with value: 0.9490937611459547 and parameters: {'weight_class_0': 0.0017250165733699804, 'weight_class_1': 0.03941660336538624, 'weight_class_2': 0.028987932944441314}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,096] Trial 587 finished with value: 0.9488749385758984 and parameters: {'weight_class_0': 0.0016867018895383426, 'weight_class_1': 0.039566864968693986, 'weight_class_2': 0.03059507165666286}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,113] Trial 588 finished with value: 0.9490964919047732 and parameters: {'weight_class_0': 0.0016716057963954486, 'weight_class_1': 0.025368797696058997, 'weight_class_2': 0.029408775890993746}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,143] Trial 590 finished with value: 0.9489910885994038 and parameters: {'weight_class_0': 0.0017136468047328772, 'weight_class_1': 0.022888291337662955, 'weight_class_2': 0.031118615250197733}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,161] Trial 589 finished with value: 0.9489492929098043 and parameters: {'weight_class_0': 0.001764812871810691, 'weight_class_1': 0.022003583335113333, 'weight_class_2': 0.03240448389049671}. Best is trial 579 with value: 0.9497138399884486.

[I 2026-07-03 10:56:34,173] Trial 591 finished with value: 0.9492681566920668 and parameters: {'weight_class_0': 0.0019078080730911334, 'weight_class_1': 0.022751095487542283, 'weight_class_2': 0.029944156706066604}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,182] Trial 592 finished with value: 0.9488936249002701 and parameters: {'weight_class_0': 0.0016889560310263745, 'weight_class_1': 0.022547687013563095, 'weight_class_2': 0.03223770809146024}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,183] Trial 594 finished with value: 0.948954063999646 and parameters: {'weight_class_0': 0.0016637402148127927, 'weight_class_1': 0.023064093812930637, 'weight_class_2': 0.030990320417917414}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,200] Trial 593 finished with value: 0.9492668925525263 and parameters: {'weight_class_0': 0.0018200098375131645, 'weight_class_1': 0.02312897047186453, 'weight_class_2': 0.030036474691631974}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,263] Trial 595 finished with value: 0.9489228669454718 and parameters: {'weight_class_0': 0.0016055551560986711, 'weight_class_1': 0.022637689694716703, 'weight_class_2': 0.030680217258955787}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,271] Trial 596 finished with value: 0.9491217289055408 and parameters: {'weight_class_0': 0.0031258648945909034, 'weight_class_1': 0.02320360662424861, 'weight_class_2': 0.03788571582849404}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,271] Trial 597 finished with value: 0.9491326686606184 and parameters: {'weight_class_0': 0.0030941679623365964, 'weight_class_1': 0.023514799008364572, 'weight_class_2': 0.038031683648387285}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,307] Trial 598 finished with value: 0.9492293390079491 and parameters: {'weight_class_0': 0.0031616790925779016, 'weight_class_1': 0.024369485000290916, 'weight_class_2': 0.03680811612618612}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,325] Trial 599 finished with value: 0.948948841561798 and parameters: {'weight_class_0': 0.002014314215141472, 'weight_class_1': 0.022274597345212973, 'weight_class_2': 0.03492842622789916}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,330] Trial 600 finished with value: 0.9487824437383822 and parameters: {'weight_class_0': 0.0032182916964193153, 'weight_class_1': 0.02189725495570396, 'weight_class_2': 0.04295992034288511}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,352] Trial 601 finished with value: 0.9479694386001714 and parameters: {'weight_class_0': 0.003060827336681816, 'weight_class_1': 0.01587506014571961, 'weight_class_2': 0.04040299563109351}. Best is trial 579 with value: 0.9497138399884486.

[I 2026-07-03 10:56:34,378] Trial 603 finished with value: 0.9474499718654984 and parameters: {'weight_class_0': 0.0031638408324317405, 'weight_class_1': 0.015582671059898115, 'weight_class_2': 0.04905651872784638}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,386] Trial 602 finished with value: 0.9475655111501272 and parameters: {'weight_class_0': 0.00322733308440429, 'weight_class_1': 0.014953289262572278, 'weight_class_2': 0.040244392171065145}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,403] Trial 604 finished with value: 0.9480118558764143 and parameters: {'weight_class_0': 0.0030458538885574666, 'weight_class_1': 0.0158846347003444, 'weight_class_2': 0.03966801032359869}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,407] Trial 605 finished with value: 0.9480921451672571 and parameters: {'weight_class_0': 0.003160840861178742, 'weight_class_1': 0.01641167732993379, 'weight_class_2': 0.03901035739473648}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,447] Trial 606 finished with value: 0.9495795910387009 and parameters: {'weight_class_0': 0.003189401332307732, 'weight_class_1': 0.048093737094295, 'weight_class_2': 0.040241305155622395}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,471] Trial 607 finished with value: 0.9440514931865639 and parameters: {'weight_class_0': 0.004798722248386668, 'weight_class_1': 0.014550149457621748, 'weight_class_2': 0.05246456203209491}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,485] Trial 608 finished with value: 0.9492134340745153 and parameters: {'weight_class_0': 0.00445045140757676, 'weight_class_1': 0.03442341537414474, 'weight_class_2': 0.04899488037014121}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,494] Trial 609 finished with value: 0.9493855591198738 and parameters: {'weight_class_0': 0.002163872068188197, 'weight_class_1': 0.01797475341631648, 'weight_class_2': 0.019915403032257778}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,535] Trial 612 finished with value: 0.9494550244533625 and parameters: {'weight_class_0': 0.0020796619451141536, 'weight_class_1': 0.017914870274669367, 'weight_class_2': 0.01955812123590079}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,536] Trial 611 finished with value: 0.9486152574328314 and parameters: {'weight_class_0': 0.0021672075721945517, 'weight_class_1': 0.04561187160738986, 'weight_class_2': 0.049194726600974584}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,539] Trial 610 finished with value: 0.9440847812305382 and parameters: {'weight_class_0': 0.004625248437945054, 'weight_class_1': 0.01747444156864434, 'weight_class_2': 0.02029199489467142}. Best is trial 579 with value: 0.9497138399884486.

[I 2026-07-03 10:56:34,555] Trial 613 finished with value: 0.9439766809083755 and parameters: {'weight_class_0': 0.00466132911204961, 'weight_class_1': 0.017365117826835478, 'weight_class_2': 0.020353769327618742}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,602] Trial 615 finished with value: 0.9470000442216056 and parameters: {'weight_class_0': 0.0046794644163740485, 'weight_class_1': 0.047126216738259945, 'weight_class_2': 0.019593825277031754}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,607] Trial 614 finished with value: 0.949558145937253 and parameters: {'weight_class_0': 0.0022247459713672963, 'weight_class_1': 0.033248682108304714, 'weight_class_2': 0.02039675181333384}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,618] Trial 616 finished with value: 0.9476795069750704 and parameters: {'weight_class_0': 0.004574168531537845, 'weight_class_1': 0.045595447225930015, 'weight_class_2': 0.02070387891856439}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,633] Trial 618 finished with value: 0.9462403149069877 and parameters: {'weight_class_0': 0.004904493676410823, 'weight_class_1': 0.03336959787030596, 'weight_class_2': 0.01994149679381422}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,648] Trial 617 finished with value: 0.9471121942454882 and parameters: {'weight_class_0': 0.004464508337504126, 'weight_class_1': 0.034590569739711946, 'weight_class_2': 0.019629821463073665}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,656] Trial 619 finished with value: 0.9495737607248557 and parameters: {'weight_class_0': 0.002180290581393226, 'weight_class_1': 0.03359231206258762, 'weight_class_2': 0.01933099499193023}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,700] Trial 620 finished with value: 0.9496469075497807 and parameters: {'weight_class_0': 0.002192681434127268, 'weight_class_1': 0.0320083089740549, 'weight_class_2': 0.025606955073871725}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,712] Trial 621 finished with value: 0.9496198499087777 and parameters: {'weight_class_0': 0.002287931879782594, 'weight_class_1': 0.04398157144056986, 'weight_class_2': 0.026442471997858364}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,757] Trial 622 finished with value: 0.9496395556930811 and parameters: {'weight_class_0': 0.0025140837551750235, 'weight_class_1': 0.031194406769685705, 'weight_class_2': 0.025514185547648807}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  21%|███████████████████████████▉                                                                                                        | 635/3000 [00:11<00:41, 56.59it/s]

[I 2026-07-03 10:56:34,781] Trial 624 finished with value: 0.9496335952873979 and parameters: {'weight_class_0': 0.0025325186120246216, 'weight_class_1': 0.033651375085930246, 'weight_class_2': 0.02584345090746553}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,783] Trial 625 finished with value: 0.9496163305272681 and parameters: {'weight_class_0': 0.002562708248997909, 'weight_class_1': 0.03233770835387019, 'weight_class_2': 0.025976274968871744}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,787] Trial 623 finished with value: 0.9496327629277382 and parameters: {'weight_class_0': 0.0026108099084118626, 'weight_class_1': 0.0332136764944731, 'weight_class_2': 0.02601280973272712}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,834] Trial 626 finished with value: 0.9495923265508511 and parameters: {'weight_class_0': 0.0025244069775385977, 'weight_class_1': 0.037171473647907835, 'weight_class_2': 0.026165664114957007}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,841] Trial 629 finished with value: 0.9495855858775263 and parameters: {'weight_class_0': 0.0026187589155778034, 'weight_class_1': 0.02663278350042043, 'weight_class_2': 0.025696214245603678}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,842] Trial 627 finished with value: 0.9495956409420211 and parameters: {'weight_class_0': 0.0026446743790931645, 'weight_class_1': 0.03198938673832718, 'weight_class_2': 0.02711612133796741}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,860] Trial 628 finished with value: 0.9495609108053958 and parameters: {'weight_class_0': 0.002577137013218843, 'weight_class_1': 0.03857830930262082, 'weight_class_2': 0.026818012518382044}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,874] Trial 630 finished with value: 0.9495105312245485 and parameters: {'weight_class_0': 0.0025542777551518054, 'weight_class_1': 0.02682005806321691, 'weight_class_2': 0.026393830157802976}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,897] Trial 631 finished with value: 0.9495347211371629 and parameters: {'weight_class_0': 0.0025511618442773587, 'weight_class_1': 0.027394103232972925, 'weight_class_2': 0.025552632108220813}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,918] Trial 632 finished with value: 0.949544447384819 and parameters: {'weight_class_0': 0.0025719203267979144, 'weight_class_1': 0.026074296435156092, 'weight_class_2': 0.025375540386720706}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,918] Trial 633 finished with value: 0.9495544733669162 and parameters: {'weight_class_0': 0.0027146667991909817, 'weight_class_1': 0.02700500850330247, 'weight_class_2': 0.025725281621710602}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,934] Trial 634 finished with value: 0.9495301960271133 and parameters: {'weight_class_0': 0.0026997337136999825, 'weight_class_1': 0.02570426313817924, 'weight_class_2': 0.025384555956070552}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:34,981] Trial 635 finished with value: 0.9430950929700538 and parameters: {'weight_class_0': 0.0068715507749809385, 'weight_class_1': 0.027929465713097595, 'weight_class_2': 0.024931070488813163}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  22%|████████████████████████████▍                                                                                                       | 647/3000 [00:11<00:46, 50.87it/s]

[I 2026-07-03 10:56:34,997] Trial 636 finished with value: 0.949090490825741 and parameters: {'weight_class_0': 0.001381567472124923, 'weight_class_1': 0.02677118007349893, 'weight_class_2': 0.02468505800727521}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,024] Trial 637 finished with value: 0.9482550026058666 and parameters: {'weight_class_0': 0.0013561106755301596, 'weight_class_1': 0.05876364292622173, 'weight_class_2': 0.017187698767781912}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,065] Trial 638 finished with value: 0.8238556394469189 and parameters: {'weight_class_0': 0.001346859670691914, 'weight_class_1': 0.49978840776943145, 'weight_class_2': 0.015677005243180338}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,071] Trial 640 finished with value: 0.43264134630940276 and parameters: {'weight_class_0': 8.040282332679602, 'weight_class_1': 0.025912433065159595, 'weight_class_2': 0.015543871899672943}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,072] Trial 639 finished with value: 0.9496086821537403 and parameters: {'weight_class_0': 0.0014318152736443272, 'weight_class_1': 0.027254854931490418, 'weight_class_2': 0.015683295085104933}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,080] Trial 641 finished with value: 0.9495713167427201 and parameters: {'weight_class_0': 0.0013685658111975592, 'weight_class_1': 0.02595948612279233, 'weight_class_2': 0.01451315580462257}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,100] Trial 642 finished with value: 0.9492709950442246 and parameters: {'weight_class_0': 0.0014385697749465809, 'weight_class_1': 0.04052765181169503, 'weight_class_2': 0.015687453118508998}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,112] Trial 643 finished with value: 0.9482557580110913 and parameters: {'weight_class_0': 0.001371478519202795, 'weight_class_1': 0.05886683056156299, 'weight_class_2': 0.014695622605885496}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,147] Trial 644 finished with value: 0.948595422416762 and parameters: {'weight_class_0': 0.0013507752072864571, 'weight_class_1': 0.053304582471827476, 'weight_class_2': 0.0152588193434662}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,160] Trial 646 finished with value: 0.6630002002151124 and parameters: {'weight_class_0': 0.0013533693411992619, 'weight_class_1': 0.5978831675369974, 'weight_class_2': 3.406189226298796}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,166] Trial 645 finished with value: 0.9493268077360008 and parameters: {'weight_class_0': 0.0014774301956959372, 'weight_class_1': 0.04091856926498023, 'weight_class_2': 0.016474408935014024}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,192] Trial 648 finished with value: 0.948365721394381 and parameters: {'weight_class_0': 0.0014054677080570755, 'weight_class_1': 0.05864107195570301, 'weight_class_2': 0.014883963953981205}. Best is trial 579 with value: 0.9497138399884486.

[I 2026-07-03 10:56:35,204] Trial 647 finished with value: 0.9486374191672259 and parameters: {'weight_class_0': 0.0015203848785083187, 'weight_class_1': 0.05744792500995472, 'weight_class_2': 0.015794888465976112}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,231] Trial 649 finished with value: 0.9488323499639716 and parameters: {'weight_class_0': 0.0015336633839776403, 'weight_class_1': 0.010044475206588426, 'weight_class_2': 0.015838321593752903}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,260] Trial 650 finished with value: 0.9492294368562909 and parameters: {'weight_class_0': 0.0019959657499855434, 'weight_class_1': 0.040879762604799835, 'weight_class_2': 0.03250315449030417}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,295] Trial 651 finished with value: 0.9492605208935694 and parameters: {'weight_class_0': 0.002003465092617089, 'weight_class_1': 0.039947639868495456, 'weight_class_2': 0.03315580831850999}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,314] Trial 652 finished with value: 0.9411619789185875 and parameters: {'weight_class_0': 0.0037131246711168656, 'weight_class_1': 0.011162409423733245, 'weight_class_2': 0.15722059368641303}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,325] Trial 653 finished with value: 0.9491010427406382 and parameters: {'weight_class_0': 0.0019463675681681205, 'weight_class_1': 0.04085897665208079, 'weight_class_2': 0.033445988790041535}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,350] Trial 654 finished with value: 0.9495941069776633 and parameters: {'weight_class_0': 0.0020885912482772953, 'weight_class_1': 0.04104382175166308, 'weight_class_2': 0.01944796000941585}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,362] Trial 655 finished with value: 0.9489804876532473 and parameters: {'weight_class_0': 0.0018913697457690515, 'weight_class_1': 0.04282949979901203, 'weight_class_2': 0.033448599255196436}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,388] Trial 657 finished with value: 0.9489973635529436 and parameters: {'weight_class_0': 0.0018607357685416104, 'weight_class_1': 0.04199171027678091, 'weight_class_2': 0.03283246213500451}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,402] Trial 656 finished with value: 0.9489832939504885 and parameters: {'weight_class_0': 0.001995686980825857, 'weight_class_1': 0.019622541536261695, 'weight_class_2': 0.033091502459204836}. Best is trial 579 with value: 0.9497138399884486.

[I 2026-07-03 10:56:35,408] Trial 658 finished with value: 0.9489254844200299 and parameters: {'weight_class_0': 0.0019598262227790374, 'weight_class_1': 0.019736459851744142, 'weight_class_2': 0.03330790136281896}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,446] Trial 659 finished with value: 0.9477765732061906 and parameters: {'weight_class_0': 0.002054737915171201, 'weight_class_1': 0.01163437816442301, 'weight_class_2': 0.034665744043690376}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,457] Trial 660 finished with value: 0.948854200232479 and parameters: {'weight_class_0': 0.001982815439921828, 'weight_class_1': 0.019632170263735038, 'weight_class_2': 0.0339424175249641}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,477] Trial 661 finished with value: 0.9439057477205842 and parameters: {'weight_class_0': 0.0019238093068949913, 'weight_class_1': 0.019649596389777757, 'weight_class_2': 0.14956738693371505}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,488] Trial 662 finished with value: 0.9495495935342172 and parameters: {'weight_class_0': 0.0019188980531501681, 'weight_class_1': 0.019568986576438078, 'weight_class_2': 0.021233253419269318}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,530] Trial 665 finished with value: 0.949494501719441 and parameters: {'weight_class_0': 0.0020543779017716856, 'weight_class_1': 0.020410225654575325, 'weight_class_2': 0.021230915170488883}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,535] Trial 663 finished with value: 0.9494878163272874 and parameters: {'weight_class_0': 0.002004021401588783, 'weight_class_1': 0.019830276575737556, 'weight_class_2': 0.02112721272655969}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,538] Trial 664 finished with value: 0.8239632025759391 and parameters: {'weight_class_0': 0.1210607182514791, 'weight_class_1': 0.01982786238727344, 'weight_class_2': 0.020465059432268416}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,576] Trial 666 finished with value: 0.9474538133010112 and parameters: {'weight_class_0': 0.0037028554827932512, 'weight_class_1': 0.019899217356780862, 'weight_class_2': 0.020864897510917538}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,590] Trial 667 finished with value: 0.9480950596587249 and parameters: {'weight_class_0': 0.003401740580499435, 'weight_class_1': 0.020422372973385044, 'weight_class_2': 0.021961942460545177}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,622] Trial 668 finished with value: 0.9488018285894643 and parameters: {'weight_class_0': 0.00347526864936806, 'weight_class_1': 0.03190290165173049, 'weight_class_2': 0.021806599070683313}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  23%|█████████████████████████████▉                                                                                                      | 679/3000 [00:12<00:47, 48.42it/s]

[I 2026-07-03 10:56:35,644] Trial 669 finished with value: 0.9478372176984475 and parameters: {'weight_class_0': 0.0035862669792725804, 'weight_class_1': 0.02087173927669806, 'weight_class_2': 0.02134940253785223}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,680] Trial 670 finished with value: 0.947676862814224 and parameters: {'weight_class_0': 0.003588886861714844, 'weight_class_1': 0.021305804542627302, 'weight_class_2': 0.019695829691869178}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,690] Trial 671 finished with value: 0.9256178428954914 and parameters: {'weight_class_0': 0.0034875858671212317, 'weight_class_1': 0.03135292822845807, 'weight_class_2': 0.562069618909104}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,711] Trial 673 finished with value: 0.9487280184384165 and parameters: {'weight_class_0': 0.003578618347384773, 'weight_class_1': 0.031020972727479647, 'weight_class_2': 0.021939409951329283}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,721] Trial 672 finished with value: 0.9362004375036476 and parameters: {'weight_class_0': 0.0036780733008059847, 'weight_class_1': 0.03181706981088759, 'weight_class_2': 0.4549583750100566}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,764] Trial 675 finished with value: 0.9485878978798427 and parameters: {'weight_class_0': 0.003643716296322208, 'weight_class_1': 0.034253258478725505, 'weight_class_2': 0.021175814996477714}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,773] Trial 674 finished with value: 0.9487124500011809 and parameters: {'weight_class_0': 0.003701618541710644, 'weight_class_1': 0.03225809911184658, 'weight_class_2': 0.02243223738003972}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,778] Trial 676 finished with value: 0.9488735028130298 and parameters: {'weight_class_0': 0.0039378156351593694, 'weight_class_1': 0.03129633021616933, 'weight_class_2': 0.05915022352085718}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,810] Trial 677 finished with value: 0.9488035242338073 and parameters: {'weight_class_0': 0.003100460909069239, 'weight_class_1': 0.03165952891100141, 'weight_class_2': 0.01912021728197127}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,828] Trial 678 finished with value: 0.9487777910433041 and parameters: {'weight_class_0': 0.0029854017573034733, 'weight_class_1': 0.0317198245900884, 'weight_class_2': 0.018552960107807624}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,837] Trial 679 finished with value: 0.9487201927998447 and parameters: {'weight_class_0': 0.0030542861909918545, 'weight_class_1': 0.031459382428343126, 'weight_class_2': 0.018381185717149476}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  23%|██████████████████████████████▎                                                                                                     | 689/3000 [00:12<00:47, 49.03it/s]

[I 2026-07-03 10:56:35,840] Trial 680 finished with value: 0.9487953877258488 and parameters: {'weight_class_0': 0.0031378400949655066, 'weight_class_1': 0.050335802164515664, 'weight_class_2': 0.06576010723646111}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,878] Trial 681 finished with value: 0.9495146905504086 and parameters: {'weight_class_0': 0.0029899049092937794, 'weight_class_1': 0.03083146063010318, 'weight_class_2': 0.02981658215531028}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,919] Trial 682 finished with value: 0.9486397022255915 and parameters: {'weight_class_0': 0.0031079130751302526, 'weight_class_1': 0.03598219557444573, 'weight_class_2': 0.06402475697740556}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,924] Trial 684 finished with value: 0.9496313062623783 and parameters: {'weight_class_0': 0.002962553213795036, 'weight_class_1': 0.036696136207059846, 'weight_class_2': 0.029358939879304526}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,929] Trial 683 finished with value: 0.94959672427994 and parameters: {'weight_class_0': 0.003037777412179581, 'weight_class_1': 0.05254360912773879, 'weight_class_2': 0.02836322945360836}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,955] Trial 685 finished with value: 0.9496058515032132 and parameters: {'weight_class_0': 0.0029436401205709304, 'weight_class_1': 0.05037903846848807, 'weight_class_2': 0.02741958466298838}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:35,986] Trial 686 finished with value: 0.949557241979221 and parameters: {'weight_class_0': 0.002994069498774013, 'weight_class_1': 0.04999459182260266, 'weight_class_2': 0.028658865134499653}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,035] Trial 687 finished with value: 0.8040407724233359 and parameters: {'weight_class_0': 1.0474206809473934, 'weight_class_1': 0.05255472982448011, 'weight_class_2': 0.027233535253286378}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,038] Trial 689 finished with value: 0.9489416201439562 and parameters: {'weight_class_0': 0.0016264277420821008, 'weight_class_1': 0.03839000500863744, 'weight_class_2': 0.028694739452056004}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,049] Trial 688 finished with value: 0.9491254266056589 and parameters: {'weight_class_0': 0.00163820785404359, 'weight_class_1': 0.025152048560982705, 'weight_class_2': 0.028823064508630328}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  23%|██████████████████████████████▊                                                                                                     | 700/3000 [00:12<00:44, 51.32it/s]

[I 2026-07-03 10:56:36,066] Trial 690 finished with value: 0.9495603556102027 and parameters: {'weight_class_0': 0.0024236370051114826, 'weight_class_1': 0.049704152924013985, 'weight_class_2': 0.02748197759909567}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,100] Trial 691 finished with value: 0.9446117728129164 and parameters: {'weight_class_0': 0.006117739849438009, 'weight_class_1': 0.024688216382865783, 'weight_class_2': 0.026945955122976567}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,109] Trial 692 finished with value: 0.9487272920388564 and parameters: {'weight_class_0': 0.0016462427548797512, 'weight_class_1': 0.046907610753965094, 'weight_class_2': 0.029305193178897983}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,120] Trial 693 finished with value: 0.8052714584681913 and parameters: {'weight_class_0': 0.906220603812432, 'weight_class_1': 0.0475632609116073, 'weight_class_2': 0.02768302217668295}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,160] Trial 694 finished with value: 0.9494602525146373 and parameters: {'weight_class_0': 0.0016953628884509681, 'weight_class_1': 0.023655531374005015, 'weight_class_2': 0.02390619480348503}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,161] Trial 695 finished with value: 0.9495674159335183 and parameters: {'weight_class_0': 0.002310085736866482, 'weight_class_1': 0.025083110422141758, 'weight_class_2': 0.024827034948206084}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,167] Trial 696 finished with value: 0.949466293449497 and parameters: {'weight_class_0': 0.0016495422363494564, 'weight_class_1': 0.025493001580549606, 'weight_class_2': 0.024323578978657046}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,184] Trial 697 finished with value: 0.948232112461796 and parameters: {'weight_class_0': 0.0016292293849943559, 'weight_class_1': 0.02573700406915498, 'weight_class_2': 0.04332947429943698}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,193] Trial 698 finished with value: 0.9486599674429531 and parameters: {'weight_class_0': 0.0023886846863275706, 'weight_class_1': 0.02513304990878541, 'weight_class_2': 0.04475912026582169}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,240] Trial 699 finished with value: 0.9400925117378666 and parameters: {'weight_class_0': 0.00614539749985363, 'weight_class_1': 0.0250931384915686, 'weight_class_2': 0.017641563390017354}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,290] Trial 700 finished with value: 0.9489177322432023 and parameters: {'weight_class_0': 0.00232489833481132, 'weight_class_1': 0.024833041876620075, 'weight_class_2': 0.04051711291435202}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  24%|███████████████████████████████▎                                                                                                    | 711/3000 [00:12<00:44, 51.81it/s]

[I 2026-07-03 10:56:36,310] Trial 701 finished with value: 0.9485073713869506 and parameters: {'weight_class_0': 0.0022878915474644195, 'weight_class_1': 0.02420200991311042, 'weight_class_2': 0.046594378113748794}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,331] Trial 703 finished with value: 0.9489146270985259 and parameters: {'weight_class_0': 0.002299604168705907, 'weight_class_1': 0.02433963022047364, 'weight_class_2': 0.03939073408382206}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,337] Trial 702 finished with value: 0.9489787754633728 and parameters: {'weight_class_0': 0.0024640595742918226, 'weight_class_1': 0.024721293992199002, 'weight_class_2': 0.04116883912739771}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,350] Trial 704 finished with value: 0.9486066285855514 and parameters: {'weight_class_0': 0.0022808785323980936, 'weight_class_1': 0.025563480333364023, 'weight_class_2': 0.01264187442568516}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,359] Trial 705 finished with value: 0.9477210448852832 and parameters: {'weight_class_0': 0.0022526785695189686, 'weight_class_1': 0.013643523724209532, 'weight_class_2': 0.04163631229101831}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,375] Trial 706 finished with value: 0.9482395449687576 and parameters: {'weight_class_0': 0.002417748622732029, 'weight_class_1': 0.016061226527658942, 'weight_class_2': 0.04068636394375222}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,397] Trial 707 finished with value: 0.9483636036408175 and parameters: {'weight_class_0': 0.0023166631818603333, 'weight_class_1': 0.09156801552697151, 'weight_class_2': 0.01823807603053411}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,416] Trial 708 finished with value: 0.948168581171709 and parameters: {'weight_class_0': 0.0022140011451888997, 'weight_class_1': 0.03833408338113959, 'weight_class_2': 0.011273008697662325}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,458] Trial 709 finished with value: 0.9488217399634685 and parameters: {'weight_class_0': 0.0023700166253679752, 'weight_class_1': 0.015990904532369867, 'weight_class_2': 0.017918062781069406}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,470] Trial 710 finished with value: 0.9481278030661034 and parameters: {'weight_class_0': 0.0022487873064605812, 'weight_class_1': 0.038586056986683104, 'weight_class_2': 0.011353744414617674}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,494] Trial 711 finished with value: 0.9485674179966285 and parameters: {'weight_class_0': 0.0022750389268757654, 'weight_class_1': 0.013682322137450206, 'weight_class_2': 0.017572705425760202}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  24%|███████████████████████████████▊                                                                                                    | 722/3000 [00:12<00:46, 49.52it/s]

[I 2026-07-03 10:56:36,518] Trial 712 finished with value: 0.9115152660639296 and parameters: {'weight_class_0': 0.01010357711992517, 'weight_class_1': 0.039598935894663345, 'weight_class_2': 0.011129553600234744}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,530] Trial 713 finished with value: 0.9493153727545218 and parameters: {'weight_class_0': 0.00229983711148173, 'weight_class_1': 0.03870219402926707, 'weight_class_2': 0.016941492745879035}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,549] Trial 714 finished with value: 0.9495697316143756 and parameters: {'weight_class_0': 0.0021678361168280115, 'weight_class_1': 0.03732014247990281, 'weight_class_2': 0.01770911850143211}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,565] Trial 715 finished with value: 0.948688723585455 and parameters: {'weight_class_0': 0.0011510049739383527, 'weight_class_1': 0.03972733521007156, 'weight_class_2': 0.017869256496022327}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,600] Trial 716 finished with value: 0.9488204052482652 and parameters: {'weight_class_0': 0.0011647877735965376, 'weight_class_1': 0.039919468062467225, 'weight_class_2': 0.01709155070703674}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,620] Trial 718 finished with value: 0.9473641469588087 and parameters: {'weight_class_0': 0.0041432096562752435, 'weight_class_1': 0.03747395385312582, 'weight_class_2': 0.01815537512207188}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,627] Trial 717 finished with value: 0.9494958028567829 and parameters: {'weight_class_0': 0.0017218011706463293, 'weight_class_1': 0.03929707682806653, 'weight_class_2': 0.019064266783638283}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,649] Trial 720 finished with value: 0.6404269733760383 and parameters: {'weight_class_0': 0.001127047166161954, 'weight_class_1': 0.040293737053772316, 'weight_class_2': 6.926195877980027}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,662] Trial 721 finished with value: 0.9484279673301929 and parameters: {'weight_class_0': 0.004158552168139965, 'weight_class_1': 0.03761931296854464, 'weight_class_2': 0.022589045990135}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,687] Trial 719 finished with value: 0.948987888859301 and parameters: {'weight_class_0': 0.0011522457757981834, 'weight_class_1': 0.03524041635364339, 'weight_class_2': 0.01747411983382553}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,688] Trial 722 finished with value: 0.9484042771907006 and parameters: {'weight_class_0': 0.0011714763756388374, 'weight_class_1': 0.03856289592221377, 'weight_class_2': 0.02281813274363919}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  24%|████████████████████████████████▎                                                                                                   | 734/3000 [00:13<00:44, 50.83it/s]

[I 2026-07-03 10:56:36,720] Trial 723 finished with value: 0.948532000280125 and parameters: {'weight_class_0': 0.0011575053281733378, 'weight_class_1': 0.03581103298455806, 'weight_class_2': 0.021645865218492225}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,769] Trial 726 finished with value: 0.9495455489496547 and parameters: {'weight_class_0': 0.0016820701897160284, 'weight_class_1': 0.02931715803860128, 'weight_class_2': 0.022790325307786862}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,776] Trial 724 finished with value: 0.8488967225528524 and parameters: {'weight_class_0': 0.05578442866949819, 'weight_class_1': 0.02943017739506838, 'weight_class_2': 0.022796440296643974}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,793] Trial 725 finished with value: 0.9495770431089778 and parameters: {'weight_class_0': 0.0027503102426593667, 'weight_class_1': 0.0296677083933583, 'weight_class_2': 0.023277570052627365}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,812] Trial 727 finished with value: 0.9480201579605216 and parameters: {'weight_class_0': 0.004268000211808755, 'weight_class_1': 0.02884364436278975, 'weight_class_2': 0.023606434728704967}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,840] Trial 728 finished with value: 0.9486543376987253 and parameters: {'weight_class_0': 0.0016988995162180167, 'weight_class_1': 0.06481680618111574, 'weight_class_2': 0.023044835349204415}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,853] Trial 729 finished with value: 0.9494838772115167 and parameters: {'weight_class_0': 0.0016521391024170015, 'weight_class_1': 0.02952635248537464, 'weight_class_2': 0.022869686605079247}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,867] Trial 730 finished with value: 0.9495771736945192 and parameters: {'weight_class_0': 0.002799908062785345, 'weight_class_1': 0.031835509259598625, 'weight_class_2': 0.02279608184732966}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,889] Trial 732 finished with value: 0.949582089330494 and parameters: {'weight_class_0': 0.0027678156531011524, 'weight_class_1': 0.029755509073958603, 'weight_class_2': 0.023545005277720816}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,894] Trial 731 finished with value: 0.9318757646704244 and parameters: {'weight_class_0': 0.0027997158810651574, 'weight_class_1': 0.004520895274403666, 'weight_class_2': 0.02390181766840032}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,899] Trial 733 finished with value: 0.9480084498029613 and parameters: {'weight_class_0': 0.002806170221824285, 'weight_class_1': 0.02916463926061648, 'weight_class_2': 0.013655592214082945}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:36,936] Trial 735 finished with value: 0.9495004004647769 and parameters: {'weight_class_0': 0.002874713974727002, 'weight_class_1': 0.02973240218917702, 'weight_class_2': 0.02339763488981763}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  25%|████████████████████████████████▋                                                                                                   | 744/3000 [00:13<00:43, 51.32it/s]

[I 2026-07-03 10:56:36,937] Trial 734 finished with value: 0.9495281501315732 and parameters: {'weight_class_0': 0.0028453785198421736, 'weight_class_1': 0.028411904718821036, 'weight_class_2': 0.02331458794696247}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,006] Trial 737 finished with value: 0.9471056527160643 and parameters: {'weight_class_0': 0.0027984801384238604, 'weight_class_1': 0.01714839360610409, 'weight_class_2': 0.013381293176124458}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,013] Trial 738 finished with value: 0.9471471537676347 and parameters: {'weight_class_0': 0.0027515068439408043, 'weight_class_1': 0.01639019044148942, 'weight_class_2': 0.013431737265456916}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,026] Trial 736 finished with value: 0.9486476287659543 and parameters: {'weight_class_0': 0.0027012131442428616, 'weight_class_1': 0.017280898747517374, 'weight_class_2': 0.03384125517212073}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,057] Trial 739 finished with value: 0.894462812789459 and parameters: {'weight_class_0': 0.0029827469360269123, 'weight_class_1': 0.017136955509159633, 'weight_class_2': 0.0010482762284327596}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,082] Trial 740 finished with value: 0.9487139014247816 and parameters: {'weight_class_0': 0.002757334127516247, 'weight_class_1': 0.018017633575574607, 'weight_class_2': 0.03436034430161566}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,107] Trial 741 finished with value: 0.949158487990693 and parameters: {'weight_class_0': 0.0028499324929805578, 'weight_class_1': 0.020661774058092944, 'weight_class_2': 0.03312355460979622}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,123] Trial 742 finished with value: 0.9346737690810829 and parameters: {'weight_class_0': 0.0020093825045304327, 'weight_class_1': 0.2147748419259801, 'weight_class_2': 0.03487577115266236}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,124] Trial 743 finished with value: 0.9486000519685073 and parameters: {'weight_class_0': 0.0018859374977541388, 'weight_class_1': 0.017969219325100837, 'weight_class_2': 0.03464581169187529}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,143] Trial 744 finished with value: 0.9484722230685892 and parameters: {'weight_class_0': 0.001878979828895109, 'weight_class_1': 0.016081896805107663, 'weight_class_2': 0.034240715954115465}. Best is trial 579 with value: 0.9497138399884486.

[I 2026-07-03 10:56:37,168] Trial 745 finished with value: 0.948791948973451 and parameters: {'weight_class_0': 0.0019143513463474426, 'weight_class_1': 0.049507806155650806, 'weight_class_2': 0.03478983436459896}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,172] Trial 746 finished with value: 0.9487228780393143 and parameters: {'weight_class_0': 0.0018410449065639656, 'weight_class_1': 0.017298191574390397, 'weight_class_2': 0.03231077723183791}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,200] Trial 747 finished with value: 0.9487445484752572 and parameters: {'weight_class_0': 0.001929900074538914, 'weight_class_1': 0.017389263816462986, 'weight_class_2': 0.03353018922785798}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,229] Trial 748 finished with value: 0.9488793488056807 and parameters: {'weight_class_0': 0.001865342969148064, 'weight_class_1': 0.050116902893200525, 'weight_class_2': 0.03190011655506352}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,246] Trial 749 finished with value: 0.9490444847080659 and parameters: {'weight_class_0': 0.0019430224955152607, 'weight_class_1': 0.022272152516258557, 'weight_class_2': 0.03352273682280274}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,265] Trial 750 finished with value: 0.9491634287279899 and parameters: {'weight_class_0': 0.0019234114647729427, 'weight_class_1': 0.021975979925939228, 'weight_class_2': 0.031172055074087834}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,301] Trial 751 finished with value: 0.9487555894888504 and parameters: {'weight_class_0': 0.0017509203192206282, 'weight_class_1': 0.046582860810170316, 'weight_class_2': 0.03124730209668109}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,320] Trial 752 finished with value: 0.9156648711574542 and parameters: {'weight_class_0': 0.0019102447135423601, 'weight_class_1': 0.0018018340677647853, 'weight_class_2': 0.03127883150701623}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  25%|█████████████████████████████████▌                                                                                                  | 764/3000 [00:13<00:48, 46.14it/s]

[I 2026-07-03 10:56:37,343] Trial 753 finished with value: 0.9491368419413478 and parameters: {'weight_class_0': 0.001971261082454242, 'weight_class_1': 0.045622113484308044, 'weight_class_2': 0.03052856817415478}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,356] Trial 754 finished with value: 0.9485164915723104 and parameters: {'weight_class_0': 0.005452534924495351, 'weight_class_1': 0.04803812644616086, 'weight_class_2': 0.03084948438020353}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,381] Trial 755 finished with value: 0.948632312000552 and parameters: {'weight_class_0': 0.001568986641509717, 'weight_class_1': 0.04527076658306557, 'weight_class_2': 0.02938318971853883}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,404] Trial 756 finished with value: 0.947956183926364 and parameters: {'weight_class_0': 0.004136164365454302, 'weight_class_1': 0.021680266573688465, 'weight_class_2': 0.029678369762947663}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,423] Trial 758 finished with value: 0.9486810056844498 and parameters: {'weight_class_0': 0.005038665569247463, 'weight_class_1': 0.061139875628470564, 'weight_class_2': 0.02827827905263254}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,430] Trial 757 finished with value: 0.9481954851363698 and parameters: {'weight_class_0': 0.004036005190942134, 'weight_class_1': 0.023131793812741667, 'weight_class_2': 0.028324120313056894}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,460] Trial 760 finished with value: 0.9491587530956376 and parameters: {'weight_class_0': 0.004110472423309793, 'weight_class_1': 0.06218522465790743, 'weight_class_2': 0.028274822174992456}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,461] Trial 759 finished with value: 0.6619268016741608 and parameters: {'weight_class_0': 0.001517963345201668, 'weight_class_1': 3.2420070702385417, 'weight_class_2': 0.02847277231082906}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,462] Trial 761 finished with value: 0.9485027087176743 and parameters: {'weight_class_0': 0.0015264085233068951, 'weight_class_1': 0.06064795758030005, 'weight_class_2': 0.014145402094323217}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,494] Trial 762 finished with value: 0.9418620171909492 and parameters: {'weight_class_0': 0.005640989699828857, 'weight_class_1': 0.02235463173493958, 'weight_class_2': 0.018637404371655217}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,517] Trial 763 finished with value: 0.9460756403190932 and parameters: {'weight_class_0': 0.005177188521184414, 'weight_class_1': 0.05877496012054483, 'weight_class_2': 0.0191359530075235}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,539] Trial 764 finished with value: 0.949571939151737 and parameters: {'weight_class_0': 0.0015028642830135347, 'weight_class_1': 0.022734296433259644, 'weight_class_2': 0.013858501611803445}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  26%|██████████████████████████████████                                                                                                  | 774/3000 [00:13<00:46, 47.51it/s]

[I 2026-07-03 10:56:37,613] Trial 765 finished with value: 0.9481715431273541 and parameters: {'weight_class_0': 0.003696231023372577, 'weight_class_1': 0.06399327331188398, 'weight_class_2': 0.01882968680562289}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,624] Trial 766 finished with value: 0.949437603931162 and parameters: {'weight_class_0': 0.0015041776348635456, 'weight_class_1': 0.03463842071863876, 'weight_class_2': 0.013919577111773067}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,636] Trial 767 finished with value: 0.946697551575225 and parameters: {'weight_class_0': 0.003408559706592955, 'weight_class_1': 0.07991982113037802, 'weight_class_2': 0.014362717029472727}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,636] Trial 768 finished with value: 0.9485959143169705 and parameters: {'weight_class_0': 0.0034055460330086156, 'weight_class_1': 0.03383679302253236, 'weight_class_2': 0.01907692871864524}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,683] Trial 769 finished with value: 0.9482547485326057 and parameters: {'weight_class_0': 0.0036086740192704265, 'weight_class_1': 0.03351460289646396, 'weight_class_2': 0.01881851490281196}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,699] Trial 770 finished with value: 0.9482638844888034 and parameters: {'weight_class_0': 0.003480785902778028, 'weight_class_1': 0.03332457149374154, 'weight_class_2': 0.018037475741114615}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,728] Trial 771 finished with value: 0.8140211854343299 and parameters: {'weight_class_0': 0.2865126012993598, 'weight_class_1': 0.03314897839836282, 'weight_class_2': 0.014291162850583877}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,768] Trial 773 finished with value: 0.9485350388552855 and parameters: {'weight_class_0': 0.003497916195543914, 'weight_class_1': 0.03479567544290291, 'weight_class_2': 0.019295555070874746}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,776] Trial 772 finished with value: 0.9496289898586174 and parameters: {'weight_class_0': 0.002394148735060371, 'weight_class_1': 0.03405173007975182, 'weight_class_2': 0.019682684706941553}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,785] Trial 774 finished with value: 0.8473204924318005 and parameters: {'weight_class_0': 0.0034494014702211944, 'weight_class_1': 0.0813938784485169, 'weight_class_2': 1.2522891345111382}. Best is trial 579 with value: 0.9497138399884486.

[I 2026-07-03 10:56:37,798] Trial 775 finished with value: 0.94872096199338 and parameters: {'weight_class_0': 0.003317447044471827, 'weight_class_1': 0.033700354010779386, 'weight_class_2': 0.019828758618951683}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,812] Trial 776 finished with value: 0.8288754953948301 and parameters: {'weight_class_0': 0.38949172061316606, 'weight_class_1': 0.08341963543582168, 'weight_class_2': 0.09970958287031591}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,867] Trial 777 finished with value: 0.9496654756421549 and parameters: {'weight_class_0': 0.002314720464727192, 'weight_class_1': 0.027570168692931704, 'weight_class_2': 0.020017186841621345}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,897] Trial 778 finished with value: 0.9496560449784431 and parameters: {'weight_class_0': 0.0020998063565508996, 'weight_class_1': 0.027654964170438653, 'weight_class_2': 0.01958538264942605}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,898] Trial 779 finished with value: 0.9496017296871466 and parameters: {'weight_class_0': 0.0023819880606012916, 'weight_class_1': 0.027086155099791398, 'weight_class_2': 0.024698499385758903}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,918] Trial 780 finished with value: 0.9496983731161276 and parameters: {'weight_class_0': 0.0023089007479393502, 'weight_class_1': 0.027569047968453917, 'weight_class_2': 0.02589000324877494}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,920] Trial 781 finished with value: 0.9495893812130838 and parameters: {'weight_class_0': 0.002473551536057782, 'weight_class_1': 0.027581268861287655, 'weight_class_2': 0.024576376767240303}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,958] Trial 783 finished with value: 0.9496128821196375 and parameters: {'weight_class_0': 0.002325136288131253, 'weight_class_1': 0.027201575720434017, 'weight_class_2': 0.02434617675808818}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:37,968] Trial 782 finished with value: 0.9496291338164302 and parameters: {'weight_class_0': 0.002384288687023764, 'weight_class_1': 0.02709805385049029, 'weight_class_2': 0.02502568037322756}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  26%|██████████████████████████████████▉                                                                                                 | 793/3000 [00:14<00:46, 47.02it/s]

[I 2026-07-03 10:56:38,023] Trial 785 finished with value: 0.9485119583755072 and parameters: {'weight_class_0': 0.0023359631979069343, 'weight_class_1': 0.027146093731596876, 'weight_class_2': 0.05015220410689337}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:38,043] Trial 784 finished with value: 0.9496557069764681 and parameters: {'weight_class_0': 0.0023254707223444634, 'weight_class_1': 0.026911045271886657, 'weight_class_2': 0.02541180751927526}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:38,051] Trial 786 finished with value: 0.9496424503321057 and parameters: {'weight_class_0': 0.0022937826206686487, 'weight_class_1': 0.027099963980268895, 'weight_class_2': 0.0247195179386973}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:38,058] Trial 787 finished with value: 0.9107915229175646 and parameters: {'weight_class_0': 0.022374861554263735, 'weight_class_1': 0.026189977075070363, 'weight_class_2': 0.05144717061337754}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:38,111] Trial 788 finished with value: 0.6405373035473145 and parameters: {'weight_class_0': 2.8862850322352913, 'weight_class_1': 0.026579419561475255, 'weight_class_2': 0.016194112089254357}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:38,122] Trial 789 finished with value: 0.9492610973962519 and parameters: {'weight_class_0': 0.002213267440281276, 'weight_class_1': 0.025986096350818208, 'weight_class_2': 0.01601558614294728}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:38,136] Trial 790 finished with value: 0.9491018742644269 and parameters: {'weight_class_0': 0.0022754076498033233, 'weight_class_1': 0.025646497329901756, 'weight_class_2': 0.015490100551049647}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:38,144] Trial 791 finished with value: 0.9495955507957757 and parameters: {'weight_class_0': 0.002201174362345045, 'weight_class_1': 0.025033196364498862, 'weight_class_2': 0.02200179830350423}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:38,185] Trial 792 finished with value: 0.9490674768229196 and parameters: {'weight_class_0': 0.0022173471160520167, 'weight_class_1': 0.02550205506656814, 'weight_class_2': 0.014694906857942844}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:38,217] Trial 794 finished with value: 0.9493530382035203 and parameters: {'weight_class_0': 0.002122493861328287, 'weight_class_1': 0.02285730748755065, 'weight_class_2': 0.016353658985279743}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  27%|███████████████████████████████████▎                                                                                                | 803/3000 [00:14<00:48, 45.11it/s]

[I 2026-07-03 10:56:38,234] Trial 793 finished with value: 0.9492989748774243 and parameters: {'weight_class_0': 0.0021369976183735844, 'weight_class_1': 0.022798263658458447, 'weight_class_2': 0.01591898962899604}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:38,251] Trial 795 finished with value: 0.9495073308497816 and parameters: {'weight_class_0': 0.0019795713693987324, 'weight_class_1': 0.022670979294276656, 'weight_class_2': 0.015692247845372948}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:38,271] Trial 796 finished with value: 0.9479043047593732 and parameters: {'weight_class_0': 0.002113314114515257, 'weight_class_1': 0.022019656521825987, 'weight_class_2': 0.010087567210061868}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:38,298] Trial 797 finished with value: 0.9480409213589193 and parameters: {'weight_class_0': 0.00203814157382975, 'weight_class_1': 0.02524815236576949, 'weight_class_2': 0.009782123603735676}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:38,324] Trial 798 finished with value: 0.9493900835639383 and parameters: {'weight_class_0': 0.002020759936638584, 'weight_class_1': 0.022082840650364782, 'weight_class_2': 0.015596850530637665}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:38,331] Trial 799 finished with value: 0.9480882038112997 and parameters: {'weight_class_0': 0.002075821778431192, 'weight_class_1': 0.02212638224403297, 'weight_class_2': 0.010331157864036116}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:38,360] Trial 800 finished with value: 0.9024218461777008 and parameters: {'weight_class_0': 0.014448641332818306, 'weight_class_1': 0.022185938936117332, 'weight_class_2': 0.019589570113375254}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:38,378] Trial 801 finished with value: 0.9496138842039509 and parameters: {'weight_class_0': 0.0018859878295841334, 'weight_class_1': 0.02107799521298917, 'weight_class_2': 0.021219681990865154}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:38,385] Trial 802 finished with value: 0.9444534349799308 and parameters: {'weight_class_0': 0.0015156662525283996, 'weight_class_1': 0.10518400712907473, 'weight_class_2': 0.012331244574670303}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:38,424] Trial 803 finished with value: 0.9488069312798335 and parameters: {'weight_class_0': 0.001751278550324166, 'weight_class_1': 0.013289528175313956, 'weight_class_2': 0.011871247822410997}. Best is trial 579 with value: 0.9497138399884486.

[I 2026-07-03 10:56:38,430] Trial 804 finished with value: 0.9489124827727012 and parameters: {'weight_class_0': 0.0018161075906884389, 'weight_class_1': 0.019919767659509657, 'weight_class_2': 0.011719471890437318}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:38,458] Trial 805 finished with value: 0.9489105725180885 and parameters: {'weight_class_0': 0.0016675292894649798, 'weight_class_1': 0.020057603404143174, 'weight_class_2': 0.010264369458077889}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:38,490] Trial 806 finished with value: 0.8975598781403002 and parameters: {'weight_class_0': 0.0016233747825469417, 'weight_class_1': 0.321129736321235, 'weight_class_2': 0.02072615680092585}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:38,512] Trial 807 finished with value: 0.9496612880282765 and parameters: {'weight_class_0': 0.0015585638974515805, 'weight_class_1': 0.021048707864629104, 'weight_class_2': 0.019689027182425527}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:38,540] Trial 808 finished with value: 0.9492544897224621 and parameters: {'weight_class_0': 0.0016907638652721776, 'weight_class_1': 0.013302817790932684, 'weight_class_2': 0.019485891918003064}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:38,542] Trial 809 finished with value: 0.9495816148241928 and parameters: {'weight_class_0': 0.001701446452018817, 'weight_class_1': 0.01964476332040422, 'weight_class_2': 0.020281470179847896}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:38,554] Trial 810 finished with value: 0.9450901808462543 and parameters: {'weight_class_0': 0.0015560649517471952, 'weight_class_1': 0.10405158525482833, 'weight_class_2': 0.021408999070261545}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:38,591] Trial 811 finished with value: 0.7120131954644434 and parameters: {'weight_class_0': 0.0016510923688428175, 'weight_class_1': 1.5373542429000553, 'weight_class_2': 0.026159831810935803}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:38,616] Trial 812 finished with value: 0.9394348459824483 and parameters: {'weight_class_0': 0.001650594415564857, 'weight_class_1': 0.013759712339404815, 'weight_class_2': 0.004026676423254301}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  27%|████████████████████████████████████▏                                                                                               | 822/3000 [00:15<00:46, 46.44it/s]

[I 2026-07-03 10:56:38,631] Trial 813 finished with value: 0.9495363786577937 and parameters: {'weight_class_0': 0.002743451423037892, 'weight_class_1': 0.028627531388239393, 'weight_class_2': 0.02605254544379873}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:38,662] Trial 814 finished with value: 0.9495742035406786 and parameters: {'weight_class_0': 0.0026990902985622985, 'weight_class_1': 0.029662799152291974, 'weight_class_2': 0.025904478960018597}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:38,687] Trial 815 finished with value: 0.9495933476019379 and parameters: {'weight_class_0': 0.002627094844552179, 'weight_class_1': 0.02916418199206359, 'weight_class_2': 0.025915864097369703}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:38,703] Trial 816 finished with value: 0.9495901005558475 and parameters: {'weight_class_0': 0.00264191652753028, 'weight_class_1': 0.030276403138825052, 'weight_class_2': 0.027594434234214777}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:38,742] Trial 817 finished with value: 0.49668751900008346 and parameters: {'weight_class_0': 4.519086094723531, 'weight_class_1': 0.012595266006994383, 'weight_class_2': 0.018893284938686722}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:38,754] Trial 819 finished with value: 0.9496613635305263 and parameters: {'weight_class_0': 0.00139992044282234, 'weight_class_1': 0.01844030331339587, 'weight_class_2': 0.017734128275344343}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:38,759] Trial 818 finished with value: 0.94914572631022 and parameters: {'weight_class_0': 0.001232630823326288, 'weight_class_1': 0.01790019798542304, 'weight_class_2': 0.02143508615797703}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:38,793] Trial 820 finished with value: 0.948262078984742 and parameters: {'weight_class_0': 0.002750709068707149, 'weight_class_1': 0.014449911808174508, 'weight_class_2': 0.025344186412166715}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:38,795] Trial 821 finished with value: 0.9495738751480585 and parameters: {'weight_class_0': 0.001273779930205047, 'weight_class_1': 0.015134295425748444, 'weight_class_2': 0.016614704246124393}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:38,815] Trial 822 finished with value: 0.9496012002746879 and parameters: {'weight_class_0': 0.0013803668118978207, 'weight_class_1': 0.01834846298750467, 'weight_class_2': 0.018476211226408832}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  28%|████████████████████████████████████▋                                                                                               | 833/3000 [00:15<00:45, 47.74it/s]

[I 2026-07-03 10:56:38,880] Trial 825 finished with value: 0.949469476782168 and parameters: {'weight_class_0': 0.0012881995815523257, 'weight_class_1': 0.0162275961956208, 'weight_class_2': 0.018624532780936075}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:38,882] Trial 823 finished with value: 0.9496161152543405 and parameters: {'weight_class_0': 0.001332059484474554, 'weight_class_1': 0.01830886113542153, 'weight_class_2': 0.017562067960166038}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:38,888] Trial 824 finished with value: 0.9494796607000883 and parameters: {'weight_class_0': 0.0013228301081729657, 'weight_class_1': 0.017906788625176872, 'weight_class_2': 0.018458437383961166}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:38,923] Trial 826 finished with value: 0.9495879183490082 and parameters: {'weight_class_0': 0.0013525774303054733, 'weight_class_1': 0.017480251807707382, 'weight_class_2': 0.01800869934851814}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:38,933] Trial 827 finished with value: 0.9490366710277448 and parameters: {'weight_class_0': 0.0010203376608581, 'weight_class_1': 0.018550785260076707, 'weight_class_2': 0.0185161058168885}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:38,979] Trial 828 finished with value: 0.949593409377648 and parameters: {'weight_class_0': 0.0014281168587142853, 'weight_class_1': 0.015941310568638966, 'weight_class_2': 0.01378895274999835}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:38,982] Trial 829 finished with value: 0.9495734863286508 and parameters: {'weight_class_0': 0.0012861597401554094, 'weight_class_1': 0.013974328262783949, 'weight_class_2': 0.014231859359196514}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:39,025] Trial 830 finished with value: 0.9495695021293847 and parameters: {'weight_class_0': 0.0010561108745211233, 'weight_class_1': 0.0186278339513718, 'weight_class_2': 0.013165319755485492}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:39,039] Trial 831 finished with value: 0.9492121161803261 and parameters: {'weight_class_0': 0.001276370663383434, 'weight_class_1': 0.009680958028377928, 'weight_class_2': 0.014233806522897742}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:39,059] Trial 832 finished with value: 0.9496113084640196 and parameters: {'weight_class_0': 0.0012683475837350865, 'weight_class_1': 0.016334703332535, 'weight_class_2': 0.013018743861002406}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  28%|█████████████████████████████████████                                                                                               | 843/3000 [00:15<00:47, 45.39it/s]

[I 2026-07-03 10:56:39,107] Trial 834 finished with value: 0.9494532383876959 and parameters: {'weight_class_0': 0.0012632782001497772, 'weight_class_1': 0.011781389455713305, 'weight_class_2': 0.012744212804162424}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:39,113] Trial 833 finished with value: 0.949638425063732 and parameters: {'weight_class_0': 0.0012828721699637666, 'weight_class_1': 0.018557183979422697, 'weight_class_2': 0.012204122614832238}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:39,122] Trial 835 finished with value: 0.9495459957152329 and parameters: {'weight_class_0': 0.0010193300554481868, 'weight_class_1': 0.02025227965132293, 'weight_class_2': 0.01278836119895886}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:39,125] Trial 836 finished with value: 0.9495734108881723 and parameters: {'weight_class_0': 0.0010285538538565289, 'weight_class_1': 0.011789672637516896, 'weight_class_2': 0.012972884267677141}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:39,172] Trial 837 finished with value: 0.9491875621668986 and parameters: {'weight_class_0': 0.001041615262030763, 'weight_class_1': 0.011107959125973245, 'weight_class_2': 0.015802477180816912}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:39,208] Trial 839 finished with value: 0.9493961971512007 and parameters: {'weight_class_0': 0.001072842849304175, 'weight_class_1': 0.022033022327008177, 'weight_class_2': 0.01532066809877127}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:39,211] Trial 838 finished with value: 0.949426206023158 and parameters: {'weight_class_0': 0.0011844124956387385, 'weight_class_1': 0.010452254606067916, 'weight_class_2': 0.012825115219465257}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:39,223] Trial 840 finished with value: 0.9495792630413744 and parameters: {'weight_class_0': 0.0010957112061173978, 'weight_class_1': 0.02155769097012165, 'weight_class_2': 0.012087879081698135}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:39,245] Trial 841 finished with value: 0.9495511613989791 and parameters: {'weight_class_0': 0.00155118234977298, 'weight_class_1': 0.022444546577030735, 'weight_class_2': 0.012363138944693135}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:39,246] Trial 842 finished with value: 0.9495659387671495 and parameters: {'weight_class_0': 0.001576465054445202, 'weight_class_1': 0.02149302018347309, 'weight_class_2': 0.02156739888380565}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:39,281] Trial 843 finished with value: 0.9492309189057645 and parameters: {'weight_class_0': 0.0010003543070964927, 'weight_class_1': 0.021899885130146454, 'weight_class_2': 0.01562848495331627}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  28%|█████████████████████████████████████▌                                                                                              | 853/3000 [00:15<00:45, 46.89it/s]

[I 2026-07-03 10:56:39,325] Trial 844 finished with value: 0.9496890120435945 and parameters: {'weight_class_0': 0.0017696439913191797, 'weight_class_1': 0.022007134901241152, 'weight_class_2': 0.02112671130279632}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:39,334] Trial 846 finished with value: 0.9496375106614053 and parameters: {'weight_class_0': 0.0016483163884762635, 'weight_class_1': 0.02370471307147022, 'weight_class_2': 0.02113563673498399}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:39,336] Trial 845 finished with value: 0.94962922009211 and parameters: {'weight_class_0': 0.0016344708533882887, 'weight_class_1': 0.022482805710038894, 'weight_class_2': 0.01659370249267764}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:39,367] Trial 847 finished with value: 0.9495657443369326 and parameters: {'weight_class_0': 0.0015929366127640995, 'weight_class_1': 0.02140366840688579, 'weight_class_2': 0.021619179274825265}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:39,399] Trial 848 finished with value: 0.9495228618138624 and parameters: {'weight_class_0': 0.0016181747922327057, 'weight_class_1': 0.023660235315646712, 'weight_class_2': 0.022580917318457554}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:39,444] Trial 849 finished with value: 0.9495720666277806 and parameters: {'weight_class_0': 0.0017280140604810513, 'weight_class_1': 0.033867540370944235, 'weight_class_2': 0.021342068751015648}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:39,466] Trial 850 finished with value: 0.9494209798687371 and parameters: {'weight_class_0': 0.0016035712271121637, 'weight_class_1': 0.033874066328763525, 'weight_class_2': 0.022241711651206288}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:39,466] Trial 852 finished with value: 0.9495133434889093 and parameters: {'weight_class_0': 0.0017333290107155118, 'weight_class_1': 0.03465909505331935, 'weight_class_2': 0.022885246077618347}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:39,469] Trial 853 finished with value: 0.9495801383822527 and parameters: {'weight_class_0': 0.0018477319254926632, 'weight_class_1': 0.03432729371037782, 'weight_class_2': 0.022234651542432145}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:39,472] Trial 851 finished with value: 0.9495496348137706 and parameters: {'weight_class_0': 0.0017309710403771322, 'weight_class_1': 0.03409170450402512, 'weight_class_2': 0.021658810435484874}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  29%|█████████████████████████████████████▉                                                                                              | 863/3000 [00:15<00:44, 48.01it/s]

[I 2026-07-03 10:56:39,542] Trial 854 finished with value: 0.9495776815987477 and parameters: {'weight_class_0': 0.0018071573499933, 'weight_class_1': 0.0338598886362215, 'weight_class_2': 0.021973008223881114}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:39,552] Trial 856 finished with value: 0.9495741723328628 and parameters: {'weight_class_0': 0.0017358100735206424, 'weight_class_1': 0.033017828751772144, 'weight_class_2': 0.022376377710555964}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:39,553] Trial 855 finished with value: 0.9495681973859806 and parameters: {'weight_class_0': 0.0017907420888168117, 'weight_class_1': 0.03275851545018957, 'weight_class_2': 0.022317464978305245}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:39,587] Trial 857 finished with value: 0.9496124683118751 and parameters: {'weight_class_0': 0.0019101738371412019, 'weight_class_1': 0.033744167878589824, 'weight_class_2': 0.022423427797249474}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:39,625] Trial 859 finished with value: 0.9495508554247972 and parameters: {'weight_class_0': 0.001861295329480195, 'weight_class_1': 0.03416953209717958, 'weight_class_2': 0.02288186389121946}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:39,634] Trial 858 finished with value: 0.9495786033927898 and parameters: {'weight_class_0': 0.001894160313756146, 'weight_class_1': 0.03455264247167173, 'weight_class_2': 0.023341911439902937}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:39,656] Trial 860 finished with value: 0.9477957810498884 and parameters: {'weight_class_0': 0.0030642025807889176, 'weight_class_1': 0.014624592368547063, 'weight_class_2': 0.02432388177647994}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:39,680] Trial 861 finished with value: 0.9480767560022594 and parameters: {'weight_class_0': 0.002847681712430014, 'weight_class_1': 0.015280768731765116, 'weight_class_2': 0.03737299350905518}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:39,702] Trial 862 finished with value: 0.9496324424041781 and parameters: {'weight_class_0': 0.003089123969836257, 'weight_class_1': 0.04299755555785446, 'weight_class_2': 0.028166249863617914}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:39,721] Trial 863 finished with value: 0.9492973194006261 and parameters: {'weight_class_0': 0.0030655800558840765, 'weight_class_1': 0.02869937410985513, 'weight_class_2': 0.04072053238855554}. Best is trial 579 with value: 0.9497138399884486.

[I 2026-07-03 10:56:39,762] Trial 864 finished with value: 0.9496248621445117 and parameters: {'weight_class_0': 0.002986950333529365, 'weight_class_1': 0.04295926510170245, 'weight_class_2': 0.04025385547476327}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:39,778] Trial 865 finished with value: 0.9475093831132538 and parameters: {'weight_class_0': 0.0031860776743932967, 'weight_class_1': 0.01417532254553359, 'weight_class_2': 0.027328650732830244}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:39,790] Trial 867 finished with value: 0.9478052487224421 and parameters: {'weight_class_0': 0.0031218159597088927, 'weight_class_1': 0.01527828711266085, 'weight_class_2': 0.0391171014878456}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:39,804] Trial 866 finished with value: 0.9477833175599152 and parameters: {'weight_class_0': 0.0030721570189487725, 'weight_class_1': 0.015247359678635605, 'weight_class_2': 0.040528953100373626}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:39,838] Trial 868 finished with value: 0.9495810509988719 and parameters: {'weight_class_0': 0.002962933561196215, 'weight_class_1': 0.04427808890235806, 'weight_class_2': 0.0385752596629065}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:39,851] Trial 869 finished with value: 0.9475264585192985 and parameters: {'weight_class_0': 0.0030815652269961893, 'weight_class_1': 0.014188746556558253, 'weight_class_2': 0.03963304979234863}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:39,858] Trial 870 finished with value: 0.9409152361756462 and parameters: {'weight_class_0': 0.0031797350803320955, 'weight_class_1': 0.04385130485839638, 'weight_class_2': 0.008162221566068264}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:39,903] Trial 872 finished with value: 0.9406120102905421 and parameters: {'weight_class_0': 0.0024384517206547307, 'weight_class_1': 0.04275110537074489, 'weight_class_2': 0.006216369079950071}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:39,914] Trial 871 finished with value: 0.9494323283969365 and parameters: {'weight_class_0': 0.002728334453139066, 'weight_class_1': 0.046021774446394645, 'weight_class_2': 0.038438322413992254}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  29%|██████████████████████████████████████▊                                                                                             | 883/3000 [00:16<00:45, 46.84it/s]

[I 2026-07-03 10:56:39,954] Trial 873 finished with value: 0.9490929978089674 and parameters: {'weight_class_0': 0.002454093368022195, 'weight_class_1': 0.02701784355940991, 'weight_class_2': 0.016853778307853524}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:39,958] Trial 874 finished with value: 0.9489812002157575 and parameters: {'weight_class_0': 0.002539391411932529, 'weight_class_1': 0.024646390672047328, 'weight_class_2': 0.017255527790143648}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:40,002] Trial 875 finished with value: 0.9395343470184704 and parameters: {'weight_class_0': 0.002379349530436895, 'weight_class_1': 0.04366739671576907, 'weight_class_2': 0.005800198342228742}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:40,004] Trial 876 finished with value: 0.6153058083314474 and parameters: {'weight_class_0': 0.002558485475115449, 'weight_class_1': 4.645393563161912, 'weight_class_2': 0.017251889826246702}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:40,019] Trial 877 finished with value: 0.9490647001200684 and parameters: {'weight_class_0': 0.0024654977425614417, 'weight_class_1': 0.02498669591459109, 'weight_class_2': 0.017206104562010084}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:40,048] Trial 878 finished with value: 0.9489894506667129 and parameters: {'weight_class_0': 0.0024546525999120535, 'weight_class_1': 0.02522558976964037, 'weight_class_2': 0.016778072887394236}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:40,081] Trial 879 finished with value: 0.9491395406641935 and parameters: {'weight_class_0': 0.0024683916586012962, 'weight_class_1': 0.025677262125794652, 'weight_class_2': 0.017586295260451065}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:40,106] Trial 880 finished with value: 0.9489905740278889 and parameters: {'weight_class_0': 0.002428367900638973, 'weight_class_1': 0.025692648404900615, 'weight_class_2': 0.016567803973692535}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:40,109] Trial 881 finished with value: 0.9496780545678699 and parameters: {'weight_class_0': 0.0021223862552872553, 'weight_class_1': 0.026201268566689705, 'weight_class_2': 0.018114445893668098}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:40,126] Trial 882 finished with value: 0.9495829736972592 and parameters: {'weight_class_0': 0.0013853227865139892, 'weight_class_1': 0.025412042362855373, 'weight_class_2': 0.01639557083784729}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:40,133] Trial 883 finished with value: 0.9491077728944001 and parameters: {'weight_class_0': 0.0024985347038001446, 'weight_class_1': 0.027376234119894698, 'weight_class_2': 0.0171542397467068}. Best is trial 579 with value: 0.9497138399884486.

[I 2026-07-03 10:56:40,192] Trial 884 finished with value: 0.9496174144486552 and parameters: {'weight_class_0': 0.002140907772347903, 'weight_class_1': 0.026011481925265, 'weight_class_2': 0.01776454178513564}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:40,198] Trial 885 finished with value: 0.9488615501563219 and parameters: {'weight_class_0': 0.0013961059506786037, 'weight_class_1': 0.01904400770864378, 'weight_class_2': 0.027570419755184206}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:40,254] Trial 886 finished with value: 0.948836804850635 and parameters: {'weight_class_0': 0.0014381402805649247, 'weight_class_1': 0.019811865570065312, 'weight_class_2': 0.029029575089700208}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:40,255] Trial 887 finished with value: 0.9487469693039502 and parameters: {'weight_class_0': 0.0013658585912572376, 'weight_class_1': 0.01834809657154178, 'weight_class_2': 0.028128186645727523}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:40,285] Trial 888 finished with value: 0.94873619179976 and parameters: {'weight_class_0': 0.0013459891628174938, 'weight_class_1': 0.01925871690913917, 'weight_class_2': 0.0284003207801781}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:40,291] Trial 889 finished with value: 0.8076637208804117 and parameters: {'weight_class_0': 0.5559228950545264, 'weight_class_1': 0.02943335860340278, 'weight_class_2': 0.027474794958382613}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:40,321] Trial 891 finished with value: 0.9489210647425991 and parameters: {'weight_class_0': 0.0014060429238846185, 'weight_class_1': 0.019959055245057214, 'weight_class_2': 0.027015300331665874}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:40,322] Trial 890 finished with value: 0.948922451171541 and parameters: {'weight_class_0': 0.0013974200269323304, 'weight_class_1': 0.029004249117346077, 'weight_class_2': 0.027689114720267204}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:40,366] Trial 893 finished with value: 0.9488949460892703 and parameters: {'weight_class_0': 0.0014700848534828909, 'weight_class_1': 0.01940166319741917, 'weight_class_2': 0.0284824450746741}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  30%|███████████████████████████████████████▋                                                                                            | 902/3000 [00:16<00:45, 46.01it/s]

[I 2026-07-03 10:56:40,372] Trial 892 finished with value: 0.9487239628294185 and parameters: {'weight_class_0': 0.0013473590215003464, 'weight_class_1': 0.018310129248282285, 'weight_class_2': 0.028229704786177263}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:40,384] Trial 894 finished with value: 0.9488344236721765 and parameters: {'weight_class_0': 0.0014106133286948424, 'weight_class_1': 0.01904184101006028, 'weight_class_2': 0.028220155945057574}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:40,426] Trial 896 finished with value: 0.9459380086159809 and parameters: {'weight_class_0': 0.001442465719190058, 'weight_class_1': 0.0058702920073794695, 'weight_class_2': 0.02863176164284953}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:40,432] Trial 895 finished with value: 0.9492483808875138 and parameters: {'weight_class_0': 0.0020285090631680545, 'weight_class_1': 0.01902114152490816, 'weight_class_2': 0.027871384443960957}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:40,464] Trial 897 finished with value: 0.9489015003201283 and parameters: {'weight_class_0': 0.0014611701149560112, 'weight_class_1': 0.019426906153975913, 'weight_class_2': 0.027851296947522402}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:40,490] Trial 899 finished with value: 0.9491591786512049 and parameters: {'weight_class_0': 0.0020821551704958683, 'weight_class_1': 0.020014234165195124, 'weight_class_2': 0.015050241128504062}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:40,510] Trial 900 finished with value: 0.9491176825932494 and parameters: {'weight_class_0': 0.0020297097297274232, 'weight_class_1': 0.019792481665188075, 'weight_class_2': 0.014571109323003352}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:40,521] Trial 898 finished with value: 0.949116936167568 and parameters: {'weight_class_0': 0.002015759938506854, 'weight_class_1': 0.018943926443023007, 'weight_class_2': 0.014269926080908083}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:40,571] Trial 901 finished with value: 0.9495306536973773 and parameters: {'weight_class_0': 0.00208433854855311, 'weight_class_1': 0.022161949974310226, 'weight_class_2': 0.01929079889759934}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:40,579] Trial 902 finished with value: 0.9481371127613428 and parameters: {'weight_class_0': 0.0018925605088107832, 'weight_class_1': 0.022773095414499595, 'weight_class_2': 0.009348751012122007}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  30%|████████████████████████████████████████▏                                                                                           | 913/3000 [00:16<00:44, 47.21it/s]

[I 2026-07-03 10:56:40,596] Trial 903 finished with value: 0.9495957816301551 and parameters: {'weight_class_0': 0.0017703232777259586, 'weight_class_1': 0.02181712106120369, 'weight_class_2': 0.014264119102427569}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:40,638] Trial 904 finished with value: 0.9490437426428605 and parameters: {'weight_class_0': 0.0020954462490627795, 'weight_class_1': 0.022572082858131684, 'weight_class_2': 0.01432950630275922}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:40,650] Trial 905 finished with value: 0.9480311811458186 and parameters: {'weight_class_0': 0.002018415568812062, 'weight_class_1': 0.02245186831683884, 'weight_class_2': 0.009766554198429766}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:40,685] Trial 906 finished with value: 0.9491021370599763 and parameters: {'weight_class_0': 0.0019995845012759457, 'weight_class_1': 0.022064777470378445, 'weight_class_2': 0.013973938453712432}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:40,701] Trial 907 finished with value: 0.9492053950023149 and parameters: {'weight_class_0': 0.0019970934730151662, 'weight_class_1': 0.02277893573015053, 'weight_class_2': 0.014136325474891685}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:40,709] Trial 908 finished with value: 0.9492829665774751 and parameters: {'weight_class_0': 0.0019708521491568526, 'weight_class_1': 0.023417550014446814, 'weight_class_2': 0.01432275236064727}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:40,738] Trial 910 finished with value: 0.9495779644918333 and parameters: {'weight_class_0': 0.002074217945978631, 'weight_class_1': 0.02315322452890192, 'weight_class_2': 0.019040789371669344}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:40,740] Trial 909 finished with value: 0.948526130664995 and parameters: {'weight_class_0': 0.0020013783130392857, 'weight_class_1': 0.023353650094696938, 'weight_class_2': 0.010797887829784495}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:40,776] Trial 911 finished with value: 0.9495949051536612 and parameters: {'weight_class_0': 0.002018853918786048, 'weight_class_1': 0.02332516854102657, 'weight_class_2': 0.019517446019838767}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:40,779] Trial 912 finished with value: 0.8355294012638437 and parameters: {'weight_class_0': 0.08888878128840785, 'weight_class_1': 0.029414560565601662, 'weight_class_2': 0.019536814558255358}. Best is trial 579 with value: 0.9497138399884486.

[I 2026-07-03 10:56:40,838] Trial 913 finished with value: 0.9496556091918884 and parameters: {'weight_class_0': 0.002132102888919347, 'weight_class_1': 0.027815672799548184, 'weight_class_2': 0.019870294392534196}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:40,842] Trial 914 finished with value: 0.9086456230232368 and parameters: {'weight_class_0': 0.004136272516689975, 'weight_class_1': 0.0031378581407815534, 'weight_class_2': 0.019542599639755905}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:40,871] Trial 915 finished with value: 0.7471214235953215 and parameters: {'weight_class_0': 0.003943210056766828, 'weight_class_1': 0.029712665167019113, 'weight_class_2': 2.5716829333943863}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:40,871] Trial 916 finished with value: 0.9496388869129516 and parameters: {'weight_class_0': 0.002110111127818379, 'weight_class_1': 0.029009908620246803, 'weight_class_2': 0.01983472574185861}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:40,918] Trial 917 finished with value: 0.9496188228592507 and parameters: {'weight_class_0': 0.002175780558231657, 'weight_class_1': 0.028613062403325472, 'weight_class_2': 0.0194580743003193}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:40,926] Trial 919 finished with value: 0.947581643637221 and parameters: {'weight_class_0': 0.003982742450522342, 'weight_class_1': 0.026982508480039583, 'weight_class_2': 0.019963406688904017}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:40,950] Trial 918 finished with value: 0.9470008302955306 and parameters: {'weight_class_0': 0.0044020461834424676, 'weight_class_1': 0.029945735353054493, 'weight_class_2': 0.019772085555490086}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:40,992] Trial 920 finished with value: 0.9495616942935112 and parameters: {'weight_class_0': 0.0016097457793600124, 'weight_class_1': 0.030102846911070145, 'weight_class_2': 0.020499308021762405}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:41,001] Trial 921 finished with value: 0.949587874825347 and parameters: {'weight_class_0': 0.0016179516631415157, 'weight_class_1': 0.03126301662490513, 'weight_class_2': 0.019753053726365273}. Best is trial 579 with value: 0.9497138399884486.

[I 2026-07-03 10:56:41,023] Trial 922 finished with value: 0.9482427159253372 and parameters: {'weight_class_0': 0.003872351397164632, 'weight_class_1': 0.029970671822673385, 'weight_class_2': 0.021273797932626248}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:41,040] Trial 923 finished with value: 0.93595966688458 and parameters: {'weight_class_0': 0.004241166343260041, 'weight_class_1': 0.008682851297475223, 'weight_class_2': 0.019822122890254822}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:41,066] Trial 924 finished with value: 0.9473828657631856 and parameters: {'weight_class_0': 0.00412810611588838, 'weight_class_1': 0.029524025771226974, 'weight_class_2': 0.01923799238070201}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:41,078] Trial 925 finished with value: 0.9484033304130953 and parameters: {'weight_class_0': 0.003919798962973837, 'weight_class_1': 0.028584702445125485, 'weight_class_2': 0.023210680771048795}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:41,113] Trial 926 finished with value: 0.9492409172291896 and parameters: {'weight_class_0': 0.0016622504225383401, 'weight_class_1': 0.03842802738867466, 'weight_class_2': 0.024042850726505458}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:41,136] Trial 927 finished with value: 0.9490864278371279 and parameters: {'weight_class_0': 0.0015421200842068, 'weight_class_1': 0.038803671394950466, 'weight_class_2': 0.023981238440893594}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:41,187] Trial 928 finished with value: 0.9477081405813627 and parameters: {'weight_class_0': 0.001691909134553739, 'weight_class_1': 0.008530710985093455, 'weight_class_2': 0.02366186933923567}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:41,189] Trial 929 finished with value: 0.949166532006433 and parameters: {'weight_class_0': 0.0016070608780809816, 'weight_class_1': 0.03880318009379876, 'weight_class_2': 0.02419567410356515}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:41,191] Trial 930 finished with value: 0.9493248990315172 and parameters: {'weight_class_0': 0.0016477905996710705, 'weight_class_1': 0.035108854682984234, 'weight_class_2': 0.02394845899481854}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:41,198] Trial 931 finished with value: 0.940991021668592 and parameters: {'weight_class_0': 0.008184236981228377, 'weight_class_1': 0.03648858434841725, 'weight_class_2': 0.024021799435557406}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  31%|█████████████████████████████████████████▎                                                                                          | 940/3000 [00:17<00:45, 45.23it/s]

[I 2026-07-03 10:56:41,244] Trial 932 finished with value: 0.9495897547842821 and parameters: {'weight_class_0': 0.002507629431385056, 'weight_class_1': 0.038111686634281786, 'weight_class_2': 0.024498731399799103}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:41,257] Trial 933 finished with value: 0.9496513310616037 and parameters: {'weight_class_0': 0.002691731418777833, 'weight_class_1': 0.0387729184244066, 'weight_class_2': 0.033230916300691665}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:41,317] Trial 934 finished with value: 0.9495991250626973 and parameters: {'weight_class_0': 0.0025871784381395068, 'weight_class_1': 0.03760240627807354, 'weight_class_2': 0.025214576718661185}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:41,319] Trial 935 finished with value: 0.949563452728965 and parameters: {'weight_class_0': 0.0025433123780607375, 'weight_class_1': 0.03828895418877207, 'weight_class_2': 0.03374550484870674}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:41,345] Trial 936 finished with value: 0.9485493239742363 and parameters: {'weight_class_0': 0.0026004169646907, 'weight_class_1': 0.01593601831163348, 'weight_class_2': 0.03275258138486084}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:41,369] Trial 937 finished with value: 0.9484435895697567 and parameters: {'weight_class_0': 0.0025736387009199398, 'weight_class_1': 0.01613589297279321, 'weight_class_2': 0.03575036864281356}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:41,396] Trial 938 finished with value: 0.9485741582413482 and parameters: {'weight_class_0': 0.0028125914890928766, 'weight_class_1': 0.016773531804205467, 'weight_class_2': 0.032520237352114935}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:41,421] Trial 940 finished with value: 0.6316357996304427 and parameters: {'weight_class_0': 0.0025290550616677587, 'weight_class_1': 0.016258666990221295, 'weight_class_2': 4.595136021464902}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:41,432] Trial 939 finished with value: 0.947754877599441 and parameters: {'weight_class_0': 0.002653256048994428, 'weight_class_1': 0.013080659909611764, 'weight_class_2': 0.035416723367660136}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  32%|█████████████████████████████████████████▊                                                                                          | 951/3000 [00:17<00:45, 45.11it/s]

[I 2026-07-03 10:56:41,471] Trial 941 finished with value: 0.9484274319308001 and parameters: {'weight_class_0': 0.0026812162361742565, 'weight_class_1': 0.016098144944097434, 'weight_class_2': 0.03460264721450649}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:41,481] Trial 942 finished with value: 0.9484333436087614 and parameters: {'weight_class_0': 0.002566646428496893, 'weight_class_1': 0.015651967800257724, 'weight_class_2': 0.03379375625332003}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:41,514] Trial 944 finished with value: 0.9485821147661374 and parameters: {'weight_class_0': 0.0025637605977212267, 'weight_class_1': 0.01603958080904523, 'weight_class_2': 0.03257207252439905}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:41,522] Trial 943 finished with value: 0.9484210553761727 and parameters: {'weight_class_0': 0.0024892965304383363, 'weight_class_1': 0.015349981810507424, 'weight_class_2': 0.03459674675275205}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:41,546] Trial 945 finished with value: 0.9483063140127431 and parameters: {'weight_class_0': 0.002904732311666237, 'weight_class_1': 0.015999018007999025, 'weight_class_2': 0.0341006751587301}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:41,583] Trial 947 finished with value: 0.9467069196986421 and parameters: {'weight_class_0': 0.003177300147072863, 'weight_class_1': 0.015749427730950824, 'weight_class_2': 0.016206679114765046}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:41,585] Trial 946 finished with value: 0.9457943897049818 and parameters: {'weight_class_0': 0.003267684441785822, 'weight_class_1': 0.014190961778345413, 'weight_class_2': 0.016141637155434155}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:41,598] Trial 948 finished with value: 0.9463545116713309 and parameters: {'weight_class_0': 0.0032157434231910205, 'weight_class_1': 0.01264056889974495, 'weight_class_2': 0.04813128393170403}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:41,621] Trial 949 finished with value: 0.9480982920058917 and parameters: {'weight_class_0': 0.003165724888303848, 'weight_class_1': 0.055340561182292775, 'weight_class_2': 0.015909765571451812}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:41,641] Trial 950 finished with value: 0.9495419890434711 and parameters: {'weight_class_0': 0.0012389278128880931, 'weight_class_1': 0.02522714956830059, 'weight_class_2': 0.011119653365241539}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:41,661] Trial 951 finished with value: 0.9486742081377395 and parameters: {'weight_class_0': 0.0031314851870181877, 'weight_class_1': 0.023695328281248738, 'weight_class_2': 0.049530183169397085}. Best is trial 579 with value: 0.9497138399884486.

[I 2026-07-03 10:56:41,677] Trial 952 finished with value: 0.9484855919151879 and parameters: {'weight_class_0': 0.003295640798620448, 'weight_class_1': 0.025285183538531597, 'weight_class_2': 0.057056450778661796}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:41,731] Trial 953 finished with value: 0.9495591740890837 and parameters: {'weight_class_0': 0.0012700568160114206, 'weight_class_1': 0.025470517444341388, 'weight_class_2': 0.01124236649771257}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:41,754] Trial 954 finished with value: 0.8912834216744955 and parameters: {'weight_class_0': 0.0012017179552973136, 'weight_class_1': 0.02582853571163455, 'weight_class_2': 0.30403650670231486}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:41,770] Trial 956 finished with value: 0.8596954294126659 and parameters: {'weight_class_0': 0.0321046787698098, 'weight_class_1': 0.025391306014773615, 'weight_class_2': 0.016121597215070792}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:41,794] Trial 955 finished with value: 0.9494582137483004 and parameters: {'weight_class_0': 0.001208537592022285, 'weight_class_1': 0.025921191166481974, 'weight_class_2': 0.01629980431309277}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:41,830] Trial 957 finished with value: 0.6495260942883475 and parameters: {'weight_class_0': 0.0012556220968625667, 'weight_class_1': 1.889582466947196, 'weight_class_2': 0.010566199976239702}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:41,849] Trial 959 finished with value: 0.9496162883322495 and parameters: {'weight_class_0': 0.0012521834490564936, 'weight_class_1': 0.02432255661732221, 'weight_class_2': 0.010847688400517086}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:41,859] Trial 958 finished with value: 0.9495887393151309 and parameters: {'weight_class_0': 0.0013029206807781326, 'weight_class_1': 0.025844488031368584, 'weight_class_2': 0.01099767685954111}. Best is trial 579 with value: 0.9497138399884486.

[I 2026-07-03 10:56:41,877] Trial 960 finished with value: 0.949629479222687 and parameters: {'weight_class_0': 0.0018280271874714625, 'weight_class_1': 0.025281833688443087, 'weight_class_2': 0.017429036911629572}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:41,907] Trial 961 finished with value: 0.9496293386499156 and parameters: {'weight_class_0': 0.0018061233035947773, 'weight_class_1': 0.02606694188718707, 'weight_class_2': 0.01716799360066779}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:41,909] Trial 962 finished with value: 0.7639905602777212 and parameters: {'weight_class_0': 0.0012145087326769785, 'weight_class_1': 0.0473715104448258, 'weight_class_2': 0.7976967521583377}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:41,922] Trial 964 finished with value: 0.9492557011011383 and parameters: {'weight_class_0': 0.001778081664834801, 'weight_class_1': 0.046979683184635336, 'weight_class_2': 0.01637294986482343}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:41,928] Trial 963 finished with value: 0.9491670349040149 and parameters: {'weight_class_0': 0.0011796200303909293, 'weight_class_1': 0.03137752358835035, 'weight_class_2': 0.016902310565976193}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:41,986] Trial 966 finished with value: 0.9492761844957975 and parameters: {'weight_class_0': 0.0017969799911650324, 'weight_class_1': 0.04776029611488153, 'weight_class_2': 0.017351166044141927}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:42,010] Trial 967 finished with value: 0.6039030236660187 and parameters: {'weight_class_0': 0.0018146719037382003, 'weight_class_1': 7.205153197063656, 'weight_class_2': 0.025608325872335455}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:42,012] Trial 965 finished with value: 0.9493106338777871 and parameters: {'weight_class_0': 0.001862238671764622, 'weight_class_1': 0.04805970357912046, 'weight_class_2': 0.02524021230039902}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:42,062] Trial 968 finished with value: 0.9493409593588519 and parameters: {'weight_class_0': 0.0018186677601383463, 'weight_class_1': 0.04552040239565274, 'weight_class_2': 0.024236697869510635}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  33%|███████████████████████████████████████████                                                                                         | 979/3000 [00:18<00:44, 45.87it/s]

[I 2026-07-03 10:56:42,100] Trial 969 finished with value: 0.9493449912419801 and parameters: {'weight_class_0': 0.001877994668589862, 'weight_class_1': 0.047780781789750676, 'weight_class_2': 0.01772415515502539}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:42,102] Trial 970 finished with value: 0.9496844599867357 and parameters: {'weight_class_0': 0.002193565722976607, 'weight_class_1': 0.03022027015330877, 'weight_class_2': 0.025145643801992298}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:42,143] Trial 971 finished with value: 0.9495577963443269 and parameters: {'weight_class_0': 0.002203673648994784, 'weight_class_1': 0.045503199319013525, 'weight_class_2': 0.025303381235746027}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:42,157] Trial 972 finished with value: 0.949625167522659 and parameters: {'weight_class_0': 0.00207054921181228, 'weight_class_1': 0.03265873026172898, 'weight_class_2': 0.025071696607401363}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:42,162] Trial 973 finished with value: 0.9496098134616405 and parameters: {'weight_class_0': 0.002130388258057068, 'weight_class_1': 0.03274612757894233, 'weight_class_2': 0.025576769575279393}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:42,181] Trial 974 finished with value: 0.8237380480458999 and parameters: {'weight_class_0': 0.1790332937652419, 'weight_class_1': 0.031896115521237764, 'weight_class_2': 0.024646291234743517}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:42,208] Trial 975 finished with value: 0.9496627183636072 and parameters: {'weight_class_0': 0.0021500472356793085, 'weight_class_1': 0.032800343687113175, 'weight_class_2': 0.02477615026440862}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:42,231] Trial 976 finished with value: 0.9496779415717197 and parameters: {'weight_class_0': 0.002229880008694429, 'weight_class_1': 0.032371289843848565, 'weight_class_2': 0.024981946210469008}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:42,237] Trial 977 finished with value: 0.9495938346629896 and parameters: {'weight_class_0': 0.0022164566663452055, 'weight_class_1': 0.03184435630150997, 'weight_class_2': 0.02227117364889186}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:42,245] Trial 978 finished with value: 0.9496073773152535 and parameters: {'weight_class_0': 0.0022060574222039007, 'weight_class_1': 0.0324955712622439, 'weight_class_2': 0.021327075827925555}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:42,280] Trial 979 finished with value: 0.9496159799961404 and parameters: {'weight_class_0': 0.002274129351245595, 'weight_class_1': 0.03224177214246877, 'weight_class_2': 0.022560479049474114}. Best is trial 579 with value: 0.9497138399884486.

[I 2026-07-03 10:56:42,346] Trial 980 finished with value: 0.9496264220243851 and parameters: {'weight_class_0': 0.00231390635740842, 'weight_class_1': 0.03239968848849002, 'weight_class_2': 0.021337101577839565}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:42,365] Trial 981 finished with value: 0.9496008380367807 and parameters: {'weight_class_0': 0.0022431883433986473, 'weight_class_1': 0.03306765330708049, 'weight_class_2': 0.021311936071664875}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:42,369] Trial 982 finished with value: 0.9495834766025548 and parameters: {'weight_class_0': 0.0021877006690226557, 'weight_class_1': 0.03275884820220749, 'weight_class_2': 0.02158637302736359}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:42,389] Trial 983 finished with value: 0.9496077441607212 and parameters: {'weight_class_0': 0.0022504421805264806, 'weight_class_1': 0.037865704693700666, 'weight_class_2': 0.02042608686452586}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:42,405] Trial 984 finished with value: 0.9496287724549538 and parameters: {'weight_class_0': 0.0024331285840425254, 'weight_class_1': 0.03734034518722049, 'weight_class_2': 0.021075781276422324}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:42,423] Trial 985 finished with value: 0.9495617631853932 and parameters: {'weight_class_0': 0.0022541329110609865, 'weight_class_1': 0.038251447357697504, 'weight_class_2': 0.021145923003479197}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:42,440] Trial 986 finished with value: 0.9484914253270245 and parameters: {'weight_class_0': 0.005014736749960115, 'weight_class_1': 0.03862071279514357, 'weight_class_2': 0.029966355628833315}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:42,473] Trial 988 finished with value: 0.6295361449631328 and parameters: {'weight_class_0': 0.003493959124865232, 'weight_class_1': 0.03817570456209232, 'weight_class_2': 9.664928663236772}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:42,480] Trial 987 finished with value: 0.9496068388484482 and parameters: {'weight_class_0': 0.003503708397776525, 'weight_class_1': 0.038953863714993826, 'weight_class_2': 0.030228095783513435}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:42,499] Trial 989 finished with value: 0.9496288980420277 and parameters: {'weight_class_0': 0.0034551262959961397, 'weight_class_1': 0.03918367309062449, 'weight_class_2': 0.030449263466467476}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  33%|███████████████████████████████████████████▋                                                                                       | 1000/3000 [00:18<00:44, 45.42it/s]

[I 2026-07-03 10:56:42,537] Trial 990 finished with value: 0.9496255332938167 and parameters: {'weight_class_0': 0.003459430403564203, 'weight_class_1': 0.03981605431854619, 'weight_class_2': 0.030547745905981877}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:42,548] Trial 991 finished with value: 0.9495389734185554 and parameters: {'weight_class_0': 0.0036209329021722305, 'weight_class_1': 0.038709759422645144, 'weight_class_2': 0.04431193990124631}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:42,603] Trial 992 finished with value: 0.9495600493015673 and parameters: {'weight_class_0': 0.0035849088527006847, 'weight_class_1': 0.039476295042826876, 'weight_class_2': 0.02999016433921669}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:42,615] Trial 993 finished with value: 0.9496838170429321 and parameters: {'weight_class_0': 0.0034672963613702097, 'weight_class_1': 0.04314179077778778, 'weight_class_2': 0.029521477788627164}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:42,619] Trial 994 finished with value: 0.9488584310013829 and parameters: {'weight_class_0': 0.0050773324727791305, 'weight_class_1': 0.05817423669585111, 'weight_class_2': 0.030713003770516795}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:42,645] Trial 995 finished with value: 0.949602547037502 and parameters: {'weight_class_0': 0.0035087090664346204, 'weight_class_1': 0.06034559350311494, 'weight_class_2': 0.03090181233452333}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:42,666] Trial 996 finished with value: 0.9495625133378182 and parameters: {'weight_class_0': 0.003568482776302202, 'weight_class_1': 0.06327028700280043, 'weight_class_2': 0.04248236126977728}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:42,679] Trial 997 finished with value: 0.9496256485568114 and parameters: {'weight_class_0': 0.0036577783076935056, 'weight_class_1': 0.04497542493361531, 'weight_class_2': 0.02980733006943129}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:42,723] Trial 999 finished with value: 0.9492762422397018 and parameters: {'weight_class_0': 0.002960665601275568, 'weight_class_1': 0.05296033591826281, 'weight_class_2': 0.04805097282674676}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:42,748] Trial 998 finished with value: 0.9494335986990192 and parameters: {'weight_class_0': 0.0029404217198613692, 'weight_class_1': 0.06629420386724554, 'weight_class_2': 0.030289624820300246}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:42,755] Trial 1000 finished with value: 0.9461571174928739 and parameters: {'weight_class_0': 0.0028925662323075452, 'weight_class_1': 0.17254886784631143, 'weight_class_2': 0.043549890429988754}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  34%|████████████████████████████████████████████                                                                                       | 1009/3000 [00:19<00:43, 45.45it/s]

[I 2026-07-03 10:56:42,767] Trial 1001 finished with value: 0.9493763311926888 and parameters: {'weight_class_0': 0.002703958264092569, 'weight_class_1': 0.051674719490339645, 'weight_class_2': 0.0410244065823347}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:42,807] Trial 1002 finished with value: 0.9494571895746843 and parameters: {'weight_class_0': 0.002955083416261089, 'weight_class_1': 0.0643738624646022, 'weight_class_2': 0.03860690758066112}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:42,858] Trial 1004 finished with value: 0.949565758047579 and parameters: {'weight_class_0': 0.0028699416587425522, 'weight_class_1': 0.05030101787749171, 'weight_class_2': 0.027605131328297484}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:42,862] Trial 1003 finished with value: 0.949604646415474 and parameters: {'weight_class_0': 0.0027100835468088693, 'weight_class_1': 0.03102171277849994, 'weight_class_2': 0.028478883243661577}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:42,887] Trial 1005 finished with value: 0.9496092968833972 and parameters: {'weight_class_0': 0.00284189195679744, 'weight_class_1': 0.054367593258162955, 'weight_class_2': 0.02710643626678009}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:42,892] Trial 1007 finished with value: 0.9496052177860376 and parameters: {'weight_class_0': 0.00284316854915983, 'weight_class_1': 0.05130563874867982, 'weight_class_2': 0.026569818864937016}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:42,900] Trial 1006 finished with value: 0.949570211464173 and parameters: {'weight_class_0': 0.0028696045128217182, 'weight_class_1': 0.05048473528991945, 'weight_class_2': 0.027393481036863995}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:42,953] Trial 1008 finished with value: 0.9496042828363581 and parameters: {'weight_class_0': 0.002624465575073169, 'weight_class_1': 0.030189139145222227, 'weight_class_2': 0.02698509799773224}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:42,970] Trial 1010 finished with value: 0.9480102337586374 and parameters: {'weight_class_0': 0.0028221985283924636, 'weight_class_1': 0.03008105416597341, 'weight_class_2': 0.013746225511662838}. Best is trial 579 with value: 0.9497138399884486.

[I 2026-07-03 10:56:42,975] Trial 1009 finished with value: 0.9495812569298089 and parameters: {'weight_class_0': 0.0027950185065319312, 'weight_class_1': 0.03103133813818302, 'weight_class_2': 0.026575368169052736}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:42,998] Trial 1011 finished with value: 0.9100413277080396 and parameters: {'weight_class_0': 0.0026794163868690203, 'weight_class_1': 0.42690301170375006, 'weight_class_2': 0.013830393197019746}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:43,029] Trial 1012 finished with value: 0.9482446380812818 and parameters: {'weight_class_0': 0.0026798857112792555, 'weight_class_1': 0.02990850532300203, 'weight_class_2': 0.013642814840713944}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:43,059] Trial 1013 finished with value: 0.9496184305268726 and parameters: {'weight_class_0': 0.0026680017800714416, 'weight_class_1': 0.030126511554053652, 'weight_class_2': 0.02642809894743166}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:43,085] Trial 1014 finished with value: 0.9485754916082838 and parameters: {'weight_class_0': 0.002623992559848111, 'weight_class_1': 0.030658439857745103, 'weight_class_2': 0.014403492925124967}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:43,109] Trial 1015 finished with value: 0.9495793756263379 and parameters: {'weight_class_0': 0.001544409976579385, 'weight_class_1': 0.029446249961314296, 'weight_class_2': 0.013779073922441246}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:43,122] Trial 1016 finished with value: 0.7266219421242727 and parameters: {'weight_class_0': 2.2116090208523, 'weight_class_1': 0.029689548806579626, 'weight_class_2': 0.019008225449268595}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:43,161] Trial 1018 finished with value: 0.9496238303325611 and parameters: {'weight_class_0': 0.0016467850008683245, 'weight_class_1': 0.029129914454693637, 'weight_class_2': 0.018433139154629546}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:43,172] Trial 1017 finished with value: 0.9496439156734713 and parameters: {'weight_class_0': 0.0015921883098975456, 'weight_class_1': 0.030330622787512158, 'weight_class_2': 0.013772127198602697}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:43,179] Trial 1019 finished with value: 0.9496200592706342 and parameters: {'weight_class_0': 0.0016562940615236093, 'weight_class_1': 0.02869488083526365, 'weight_class_2': 0.014542021286917763}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  34%|████████████████████████████████████████████▊                                                                                      | 1027/3000 [00:19<00:45, 43.44it/s]

[I 2026-07-03 10:56:43,210] Trial 1020 finished with value: 0.9495005031498795 and parameters: {'weight_class_0': 0.0016803035054258244, 'weight_class_1': 0.036103293853853705, 'weight_class_2': 0.01368046291564736}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:43,220] Trial 1021 finished with value: 0.9494115074906784 and parameters: {'weight_class_0': 0.0017006316332224838, 'weight_class_1': 0.04246029989735877, 'weight_class_2': 0.019099020860519893}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:43,287] Trial 1022 finished with value: 0.9493178347092415 and parameters: {'weight_class_0': 0.0015914590406662528, 'weight_class_1': 0.04294057382850397, 'weight_class_2': 0.018732712420960924}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:43,298] Trial 1023 finished with value: 0.9494096524506132 and parameters: {'weight_class_0': 0.0016695906234829104, 'weight_class_1': 0.04164420916776673, 'weight_class_2': 0.0185147879382269}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:43,340] Trial 1025 finished with value: 0.9494961135369352 and parameters: {'weight_class_0': 0.0018254370313604386, 'weight_class_1': 0.038940066681706735, 'weight_class_2': 0.018125336901063143}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:43,343] Trial 1024 finished with value: 0.9494284093502429 and parameters: {'weight_class_0': 0.0017235460434926208, 'weight_class_1': 0.040616053093657664, 'weight_class_2': 0.01964168567044075}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:43,360] Trial 1026 finished with value: 0.9494103916776063 and parameters: {'weight_class_0': 0.0018226251007116491, 'weight_class_1': 0.041601477880060904, 'weight_class_2': 0.018994637683422178}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:43,381] Trial 1027 finished with value: 0.9494257547799392 and parameters: {'weight_class_0': 0.0018085863664124412, 'weight_class_1': 0.04154787174283225, 'weight_class_2': 0.017939007732930036}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  35%|█████████████████████████████████████████████▎                                                                                     | 1037/3000 [00:19<00:43, 45.28it/s]

[I 2026-07-03 10:56:43,399] Trial 1028 finished with value: 0.9495144806302163 and parameters: {'weight_class_0': 0.00201469920643069, 'weight_class_1': 0.04320141875807815, 'weight_class_2': 0.01812450594636159}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:43,423] Trial 1029 finished with value: 0.9495830810830145 and parameters: {'weight_class_0': 0.0019564751623222963, 'weight_class_1': 0.03895923937832657, 'weight_class_2': 0.01862521739521735}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:43,451] Trial 1031 finished with value: 0.5882467702877529 and parameters: {'weight_class_0': 5.169218805629082, 'weight_class_1': 0.040597232690691, 'weight_class_2': 0.022405557736220473}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:43,456] Trial 1030 finished with value: 0.949535157167475 and parameters: {'weight_class_0': 0.002085829083545405, 'weight_class_1': 0.04276432335456409, 'weight_class_2': 0.01853987081018532}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:43,468] Trial 1032 finished with value: 0.9494891936482913 and parameters: {'weight_class_0': 0.0021102751848293628, 'weight_class_1': 0.020537002718477686, 'weight_class_2': 0.02319106553865091}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:43,508] Trial 1034 finished with value: 0.946510627067541 and parameters: {'weight_class_0': 0.0021027613025312894, 'weight_class_1': 0.023615847074228365, 'weight_class_2': 0.008076476835729061}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:43,513] Trial 1033 finished with value: 0.949553788981448 and parameters: {'weight_class_0': 0.002065703386191611, 'weight_class_1': 0.04169080380710557, 'weight_class_2': 0.02166993148816781}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:43,557] Trial 1035 finished with value: 0.9496164692241016 and parameters: {'weight_class_0': 0.0019765505674084914, 'weight_class_1': 0.022084698263619022, 'weight_class_2': 0.022784049141550324}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:43,567] Trial 1036 finished with value: 0.9495311403423902 and parameters: {'weight_class_0': 0.0021438340015372532, 'weight_class_1': 0.021210696333349776, 'weight_class_2': 0.02354433254617061}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:43,608] Trial 1037 finished with value: 0.949482328202552 and parameters: {'weight_class_0': 0.0021869853283106007, 'weight_class_1': 0.021829306289739375, 'weight_class_2': 0.023047095785297615}. Best is trial 579 with value: 0.9497138399884486.

[I 2026-07-03 10:56:43,659] Trial 1038 finished with value: 0.9494343475049171 and parameters: {'weight_class_0': 0.002162990715054784, 'weight_class_1': 0.0209768049376968, 'weight_class_2': 0.022243782575910184}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:43,672] Trial 1039 finished with value: 0.9494572906077314 and parameters: {'weight_class_0': 0.002267681382519368, 'weight_class_1': 0.021815027368072566, 'weight_class_2': 0.02309817755359637}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:43,705] Trial 1041 finished with value: 0.9494541357150803 and parameters: {'weight_class_0': 0.002277670924267976, 'weight_class_1': 0.02192821633355351, 'weight_class_2': 0.023917991033661483}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:43,711] Trial 1040 finished with value: 0.949072289424842 and parameters: {'weight_class_0': 0.002263522656237806, 'weight_class_1': 0.022462763361587212, 'weight_class_2': 0.03527584440835014}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:43,729] Trial 1042 finished with value: 0.9490584508802438 and parameters: {'weight_class_0': 0.0022669134049784854, 'weight_class_1': 0.022655688031080118, 'weight_class_2': 0.036436579772805636}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:43,747] Trial 1043 finished with value: 0.9491640739666316 and parameters: {'weight_class_0': 0.002349260620203875, 'weight_class_1': 0.02246651303042069, 'weight_class_2': 0.03474318788873073}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:43,753] Trial 1044 finished with value: 0.9489656422343229 and parameters: {'weight_class_0': 0.0023288439696832453, 'weight_class_1': 0.020067916783411507, 'weight_class_2': 0.03575159342105567}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:43,777] Trial 1045 finished with value: 0.9489324961850437 and parameters: {'weight_class_0': 0.0022464446436336835, 'weight_class_1': 0.021222815168912376, 'weight_class_2': 0.0365870196775043}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:43,819] Trial 1047 finished with value: 0.948337494674913 and parameters: {'weight_class_0': 0.004440275484421034, 'weight_class_1': 0.024067233654906116, 'weight_class_2': 0.03570724952391708}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  35%|██████████████████████████████████████████████                                                                                     | 1055/3000 [00:20<00:47, 41.17it/s]

[I 2026-07-03 10:56:43,850] Trial 1046 finished with value: 0.9484063374015056 and parameters: {'weight_class_0': 0.004466722739882238, 'weight_class_1': 0.02455814235984453, 'weight_class_2': 0.03745403704090983}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:43,870] Trial 1048 finished with value: 0.9492256771338438 and parameters: {'weight_class_0': 0.0024684306932599965, 'weight_class_1': 0.025150790230466517, 'weight_class_2': 0.036392059319960986}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:43,878] Trial 1049 finished with value: 0.9491104685781641 and parameters: {'weight_class_0': 0.0023057294985861293, 'weight_class_1': 0.02446878958326202, 'weight_class_2': 0.03586751107961599}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:43,925] Trial 1050 finished with value: 0.9488335881846691 and parameters: {'weight_class_0': 0.004135775426840281, 'weight_class_1': 0.02566303057915351, 'weight_class_2': 0.03585852286067134}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:43,963] Trial 1052 finished with value: 0.9489540823568873 and parameters: {'weight_class_0': 0.004550770626889118, 'weight_class_1': 0.03414663325904071, 'weight_class_2': 0.03356090998623836}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:43,964] Trial 1051 finished with value: 0.9488117581140991 and parameters: {'weight_class_0': 0.004185178685536521, 'weight_class_1': 0.025811868644289124, 'weight_class_2': 0.036019474456097}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:44,005] Trial 1054 finished with value: 0.9489966241020072 and parameters: {'weight_class_0': 0.004191938897277871, 'weight_class_1': 0.03356460233648987, 'weight_class_2': 0.0297626823244034}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:44,009] Trial 1053 finished with value: 0.9495188042787901 and parameters: {'weight_class_0': 0.00323418723752578, 'weight_class_1': 0.034416429400337005, 'weight_class_2': 0.02934739891604812}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:44,017] Trial 1055 finished with value: 0.9489912929956391 and parameters: {'weight_class_0': 0.004275252587728629, 'weight_class_1': 0.03406265110259799, 'weight_class_2': 0.030620933719284833}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  36%|██████████████████████████████████████████████▌                                                                                    | 1065/3000 [00:20<00:45, 42.17it/s]

[I 2026-07-03 10:56:44,057] Trial 1057 finished with value: 0.9487025992286603 and parameters: {'weight_class_0': 0.0014326414575566936, 'weight_class_1': 0.035453184004065864, 'weight_class_2': 0.028996920533627235}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:44,064] Trial 1056 finished with value: 0.7908736118400878 and parameters: {'weight_class_0': 0.003272781858289023, 'weight_class_1': 0.03446840335497863, 'weight_class_2': 1.6820553990516744}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:44,090] Trial 1058 finished with value: 0.9487964664403138 and parameters: {'weight_class_0': 0.0014702272847874915, 'weight_class_1': 0.03479536570290812, 'weight_class_2': 0.02752367902056239}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:44,103] Trial 1059 finished with value: 0.9487239606214836 and parameters: {'weight_class_0': 0.0014304925654803561, 'weight_class_1': 0.0338262078415132, 'weight_class_2': 0.028576832813195337}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:44,137] Trial 1060 finished with value: 0.9025747689341213 and parameters: {'weight_class_0': 0.0033806012515863633, 'weight_class_1': 0.03354250526005567, 'weight_class_2': 0.0024335312527427604}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:44,176] Trial 1061 finished with value: 0.9489073058145735 and parameters: {'weight_class_0': 0.0014681960516775073, 'weight_class_1': 0.034557023022337575, 'weight_class_2': 0.026166260942876208}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:44,195] Trial 1062 finished with value: 0.9487883583970419 and parameters: {'weight_class_0': 0.0014473225805976405, 'weight_class_1': 0.03616303537382987, 'weight_class_2': 0.026986186422599014}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:44,213] Trial 1063 finished with value: 0.9487220812175573 and parameters: {'weight_class_0': 0.0013667946771118847, 'weight_class_1': 0.03357850112682926, 'weight_class_2': 0.027095679615175724}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:44,229] Trial 1064 finished with value: 0.9490098642573522 and parameters: {'weight_class_0': 0.0014821855613929198, 'weight_class_1': 0.0339162430326464, 'weight_class_2': 0.02590797300670218}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:44,257] Trial 1065 finished with value: 0.9488177428166152 and parameters: {'weight_class_0': 0.0014162847025109963, 'weight_class_1': 0.03451314228650009, 'weight_class_2': 0.025945345521610246}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  36%|██████████████████████████████████████████████▉                                                                                    | 1074/3000 [00:20<00:44, 43.19it/s]

[I 2026-07-03 10:56:44,285] Trial 1067 finished with value: 0.9496024398240284 and parameters: {'weight_class_0': 0.0015164567921750805, 'weight_class_1': 0.017744836448084177, 'weight_class_2': 0.01568588678514785}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:44,307] Trial 1066 finished with value: 0.9481913425867664 and parameters: {'weight_class_0': 0.0030698235170148976, 'weight_class_1': 0.02773644938941992, 'weight_class_2': 0.01569891145542}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:44,346] Trial 1068 finished with value: 0.898699123247293 and parameters: {'weight_class_0': 0.003267632674525841, 'weight_class_1': 0.02792775759695806, 'weight_class_2': 0.0018178355767551678}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:44,368] Trial 1069 finished with value: 0.9473466741731791 and parameters: {'weight_class_0': 0.0034068872830937636, 'weight_class_1': 0.026716263442449276, 'weight_class_2': 0.015366035067776371}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:44,376] Trial 1070 finished with value: 0.9479290184281736 and parameters: {'weight_class_0': 0.0032265533570730786, 'weight_class_1': 0.027782540311464494, 'weight_class_2': 0.01575549036268891}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:44,444] Trial 1072 finished with value: 0.9467757055862204 and parameters: {'weight_class_0': 0.0031423947346992873, 'weight_class_1': 0.01748811433892301, 'weight_class_2': 0.014841984974367482}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:44,448] Trial 1071 finished with value: 0.9479654483186121 and parameters: {'weight_class_0': 0.0032238069603667103, 'weight_class_1': 0.028707521407008454, 'weight_class_2': 0.015761858944351774}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:44,454] Trial 1073 finished with value: 0.9478609821013723 and parameters: {'weight_class_0': 0.0031451213195838115, 'weight_class_1': 0.027740041102684108, 'weight_class_2': 0.015040821125452757}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:44,476] Trial 1074 finished with value: 0.9468178379776115 and parameters: {'weight_class_0': 0.003283238039405729, 'weight_class_1': 0.018358559200138447, 'weight_class_2': 0.015569136749614717}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  36%|███████████████████████████████████████████████▎                                                                                   | 1083/3000 [00:20<00:46, 41.59it/s]

[I 2026-07-03 10:56:44,504] Trial 1075 finished with value: 0.9482255819896538 and parameters: {'weight_class_0': 0.0031734570514795877, 'weight_class_1': 0.02754900599820894, 'weight_class_2': 0.01663043805166267}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:44,540] Trial 1077 finished with value: 0.9483084944479664 and parameters: {'weight_class_0': 0.0026464167678387747, 'weight_class_1': 0.01830318686726276, 'weight_class_2': 0.015952168828909326}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:44,556] Trial 1076 finished with value: 0.9490980827014908 and parameters: {'weight_class_0': 0.0018500076208893559, 'weight_class_1': 0.02758504283204165, 'weight_class_2': 0.012223353063173632}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:44,575] Trial 1078 finished with value: 0.9495993672747204 and parameters: {'weight_class_0': 0.001842597691844989, 'weight_class_1': 0.02763010765585728, 'weight_class_2': 0.015893981746439516}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:44,626] Trial 1080 finished with value: 0.7799090317624474 and parameters: {'weight_class_0': 0.0018573086697889526, 'weight_class_1': 0.049524752854834216, 'weight_class_2': 1.0772370426705866}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:44,627] Trial 1079 finished with value: 0.9487134266729211 and parameters: {'weight_class_0': 0.0018777409112860366, 'weight_class_1': 0.01761904177881609, 'weight_class_2': 0.01140145869760669}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:44,644] Trial 1081 finished with value: 0.9474712869471782 and parameters: {'weight_class_0': 0.0025637095449671282, 'weight_class_1': 0.018479587131007922, 'weight_class_2': 0.012143981018044819}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:44,666] Trial 1082 finished with value: 0.9488647309591706 and parameters: {'weight_class_0': 0.0018910846332001053, 'weight_class_1': 0.01743863986822787, 'weight_class_2': 0.012241640147307643}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:44,686] Trial 1083 finished with value: 0.9483722672002389 and parameters: {'weight_class_0': 0.001931756438340415, 'weight_class_1': 0.052420939950036716, 'weight_class_2': 0.01176853674911233}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  36%|███████████████████████████████████████████████▋                                                                                   | 1092/3000 [00:21<00:44, 42.61it/s]

[I 2026-07-03 10:56:44,696] Trial 1084 finished with value: 0.9495617649585344 and parameters: {'weight_class_0': 0.0025563813456548254, 'weight_class_1': 0.05027568998184786, 'weight_class_2': 0.021216574280418482}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:44,761] Trial 1085 finished with value: 0.9484737715646304 and parameters: {'weight_class_0': 0.0018753764387196574, 'weight_class_1': 0.04912251896705418, 'weight_class_2': 0.011585222769211229}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:44,774] Trial 1087 finished with value: 0.949303517972624 and parameters: {'weight_class_0': 0.0018221477209994328, 'weight_class_1': 0.05027749247049282, 'weight_class_2': 0.021506216461967327}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:44,792] Trial 1086 finished with value: 0.9493113270343437 and parameters: {'weight_class_0': 0.001867808407595869, 'weight_class_1': 0.04977917203441866, 'weight_class_2': 0.020375101124741956}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:44,827] Trial 1088 finished with value: 0.949543314485764 and parameters: {'weight_class_0': 0.002559471266484884, 'weight_class_1': 0.05118628111668375, 'weight_class_2': 0.02076423622400065}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:44,842] Trial 1089 finished with value: 0.949532080537156 and parameters: {'weight_class_0': 0.0024543540282101818, 'weight_class_1': 0.047309979517269986, 'weight_class_2': 0.019599739244231345}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:44,843] Trial 1090 finished with value: 0.949518492246388 and parameters: {'weight_class_0': 0.00240584711651372, 'weight_class_1': 0.05133052412465872, 'weight_class_2': 0.02125517699432679}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:44,903] Trial 1091 finished with value: 0.9496387428113167 and parameters: {'weight_class_0': 0.002461782127696798, 'weight_class_1': 0.04633496537049379, 'weight_class_2': 0.020845877582593535}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:44,907] Trial 1092 finished with value: 0.9495839276831967 and parameters: {'weight_class_0': 0.002493764470275337, 'weight_class_1': 0.044042971581014, 'weight_class_2': 0.023064140256381743}. Best is trial 579 with value: 0.9497138399884486.

[I 2026-07-03 10:56:44,962] Trial 1094 finished with value: 0.8562973970539409 and parameters: {'weight_class_0': 0.0579136069278624, 'weight_class_1': 0.0432164422925758, 'weight_class_2': 0.021830618775710343}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:44,962] Trial 1093 finished with value: 0.8366675101776995 and parameters: {'weight_class_0': 0.1220485377136002, 'weight_class_1': 0.04501149764735612, 'weight_class_2': 0.021565380388052717}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:44,965] Trial 1095 finished with value: 0.948234537988685 and parameters: {'weight_class_0': 0.002393199511635773, 'weight_class_1': 0.012250798477586282, 'weight_class_2': 0.02074012829474302}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:45,005] Trial 1096 finished with value: 0.9495969924108058 and parameters: {'weight_class_0': 0.0023191313777037, 'weight_class_1': 0.04232653770920121, 'weight_class_2': 0.022142851491526987}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:45,035] Trial 1097 finished with value: 0.9482359917293947 and parameters: {'weight_class_0': 0.0024050996716613385, 'weight_class_1': 0.012407876619886458, 'weight_class_2': 0.021897173849996975}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:45,043] Trial 1098 finished with value: 0.9495379034211217 and parameters: {'weight_class_0': 0.0024444964333479964, 'weight_class_1': 0.02455697077498287, 'weight_class_2': 0.021990066491390518}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:45,078] Trial 1099 finished with value: 0.9494580266016848 and parameters: {'weight_class_0': 0.002433458547557276, 'weight_class_1': 0.02345537735906887, 'weight_class_2': 0.02538267139281571}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:45,105] Trial 1100 finished with value: 0.9496476822509141 and parameters: {'weight_class_0': 0.0022131683917742564, 'weight_class_1': 0.02566384729796417, 'weight_class_2': 0.024170919809223132}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:45,129] Trial 1101 finished with value: 0.9482651273062972 and parameters: {'weight_class_0': 0.0022225149483313935, 'weight_class_1': 0.01194446726467074, 'weight_class_2': 0.02461147015917238}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  37%|████████████████████████████████████████████████▍                                                                                  | 1110/3000 [00:21<00:46, 40.56it/s]

[I 2026-07-03 10:56:45,155] Trial 1102 finished with value: 0.8277048136830487 and parameters: {'weight_class_0': 0.11793254860495793, 'weight_class_1': 0.024787504840653164, 'weight_class_2': 0.024554503055657463}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:45,167] Trial 1103 finished with value: 0.9483442806942454 and parameters: {'weight_class_0': 0.002192316350955586, 'weight_class_1': 0.012165583677040208, 'weight_class_2': 0.024835124557187938}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:45,202] Trial 1104 finished with value: 0.9494862998779835 and parameters: {'weight_class_0': 0.0015702545840559422, 'weight_class_1': 0.025241529803622768, 'weight_class_2': 0.022548484161252054}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:45,237] Trial 1105 finished with value: 0.9485813728761358 and parameters: {'weight_class_0': 0.0011393874917783305, 'weight_class_1': 0.024411539593999245, 'weight_class_2': 0.02557832672498934}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:45,268] Trial 1107 finished with value: 0.948656572075247 and parameters: {'weight_class_0': 0.0011403819886763, 'weight_class_1': 0.0202731185521292, 'weight_class_2': 0.025523285123453802}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:45,270] Trial 1106 finished with value: 0.9492849657529528 and parameters: {'weight_class_0': 0.001506558418179641, 'weight_class_1': 0.02479598159403329, 'weight_class_2': 0.02443406085390412}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:45,283] Trial 1108 finished with value: 0.9417210648243303 and parameters: {'weight_class_0': 0.0012126852476780146, 'weight_class_1': 0.028444846722882017, 'weight_class_2': 0.12030980899996879}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:45,307] Trial 1109 finished with value: 0.9484916867712552 and parameters: {'weight_class_0': 0.0011540121610954172, 'weight_class_1': 0.02932484675041162, 'weight_class_2': 0.025657232095380476}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:45,334] Trial 1110 finished with value: 0.9492694024454407 and parameters: {'weight_class_0': 0.001567804612603401, 'weight_class_1': 0.03006512531606395, 'weight_class_2': 0.025803889262019493}. Best is trial 579 with value: 0.9497138399884486.

[I 2026-07-03 10:56:45,363] Trial 1111 finished with value: 0.9481655681022136 and parameters: {'weight_class_0': 0.0010169536983924451, 'weight_class_1': 0.019934224711397334, 'weight_class_2': 0.02880299789361731}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:45,377] Trial 1112 finished with value: 0.9481941208406784 and parameters: {'weight_class_0': 0.001126832503443087, 'weight_class_1': 0.01930141715565886, 'weight_class_2': 0.03077035752566592}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:45,395] Trial 1113 finished with value: 0.9487027011961165 and parameters: {'weight_class_0': 0.0015594733277601027, 'weight_class_1': 0.020430628327810892, 'weight_class_2': 0.008852786336066945}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:45,440] Trial 1115 finished with value: 0.9488484437017997 and parameters: {'weight_class_0': 0.0016569903524443162, 'weight_class_1': 0.01999985154504967, 'weight_class_2': 0.03099899760861004}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:45,448] Trial 1114 finished with value: 0.9494738614884007 and parameters: {'weight_class_0': 0.001120528668387138, 'weight_class_1': 0.01961782135316254, 'weight_class_2': 0.008746795963297676}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:45,473] Trial 1116 finished with value: 0.9488490755145782 and parameters: {'weight_class_0': 0.0015820226845176062, 'weight_class_1': 0.019618682494830595, 'weight_class_2': 0.030986139028640412}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:45,484] Trial 1117 finished with value: 0.9493885540077364 and parameters: {'weight_class_0': 0.0037839002199826473, 'weight_class_1': 0.03106126355421538, 'weight_class_2': 0.031167935696215322}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:45,515] Trial 1118 finished with value: 0.9494360056138685 and parameters: {'weight_class_0': 0.0037340773628267245, 'weight_class_1': 0.036223953352893835, 'weight_class_2': 0.03010749501346208}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:45,555] Trial 1119 finished with value: 0.949497032080053 and parameters: {'weight_class_0': 0.0038062031521737517, 'weight_class_1': 0.03573467444291778, 'weight_class_2': 0.03129774917926382}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:45,589] Trial 1120 finished with value: 0.8974081407545026 and parameters: {'weight_class_0': 0.002902854829779251, 'weight_class_1': 0.03677382152343735, 'weight_class_2': 0.001369905932520344}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  38%|█████████████████████████████████████████████████▎                                                                                 | 1129/3000 [00:21<00:43, 42.86it/s]

[I 2026-07-03 10:56:45,601] Trial 1121 finished with value: 0.9481173077638817 and parameters: {'weight_class_0': 0.0035925804537580144, 'weight_class_1': 0.03668956679965033, 'weight_class_2': 0.01789432798027529}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:45,620] Trial 1122 finished with value: 0.9496542479337533 and parameters: {'weight_class_0': 0.002895558134667682, 'weight_class_1': 0.03660032413636192, 'weight_class_2': 0.03096436406059049}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:45,649] Trial 1123 finished with value: 0.8185132216278483 and parameters: {'weight_class_0': 0.00290150820549363, 'weight_class_1': 1.0465173686704108, 'weight_class_2': 0.016907473740156373}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:45,680] Trial 1124 finished with value: 0.8429648637057925 and parameters: {'weight_class_0': 0.0028835527247734554, 'weight_class_1': 0.8782464436046324, 'weight_class_2': 0.017393690942161873}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:45,690] Trial 1125 finished with value: 0.9488367782368824 and parameters: {'weight_class_0': 0.0029249328630938628, 'weight_class_1': 0.036173538140140134, 'weight_class_2': 0.017177390944399625}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:45,723] Trial 1126 finished with value: 0.9488494585219187 and parameters: {'weight_class_0': 0.0029587664281807437, 'weight_class_1': 0.03677318455935396, 'weight_class_2': 0.01755288343598679}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:45,736] Trial 1128 finished with value: 0.9491237437873522 and parameters: {'weight_class_0': 0.0027532173519255582, 'weight_class_1': 0.03761295138973298, 'weight_class_2': 0.01817629613499375}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:45,740] Trial 1127 finished with value: 0.9487780200350574 and parameters: {'weight_class_0': 0.0028716108607973953, 'weight_class_1': 0.03711069598698733, 'weight_class_2': 0.01670097701497267}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:45,775] Trial 1129 finished with value: 0.9490044739085514 and parameters: {'weight_class_0': 0.0028812026370560466, 'weight_class_1': 0.03843521639523669, 'weight_class_2': 0.01834756200000053}. Best is trial 579 with value: 0.9497138399884486.

[I 2026-07-03 10:56:45,816] Trial 1130 finished with value: 0.7936479407689228 and parameters: {'weight_class_0': 1.1917231581576644, 'weight_class_1': 0.036198748084038626, 'weight_class_2': 0.018412667044269224}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:45,830] Trial 1131 finished with value: 0.948780269813315 and parameters: {'weight_class_0': 0.0030066275849308967, 'weight_class_1': 0.03301937916117692, 'weight_class_2': 0.018097240355081614}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:45,871] Trial 1132 finished with value: 0.9496327014319584 and parameters: {'weight_class_0': 0.0020394301872755823, 'weight_class_1': 0.029890697404973823, 'weight_class_2': 0.017765781735024366}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:45,879] Trial 1133 finished with value: 0.9496014137175557 and parameters: {'weight_class_0': 0.0019465049134569628, 'weight_class_1': 0.030384371517267653, 'weight_class_2': 0.01816821059001054}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:45,899] Trial 1134 finished with value: 0.9495893231071979 and parameters: {'weight_class_0': 0.0017972419797968341, 'weight_class_1': 0.028972057229359117, 'weight_class_2': 0.018332971282453245}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:45,921] Trial 1135 finished with value: 0.9495604665658474 and parameters: {'weight_class_0': 0.0019348647823364277, 'weight_class_1': 0.03027791338222861, 'weight_class_2': 0.01729990258635144}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:45,937] Trial 1136 finished with value: 0.94959615359278 and parameters: {'weight_class_0': 0.00193500195150669, 'weight_class_1': 0.02978884530594323, 'weight_class_2': 0.01886887585670571}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:45,978] Trial 1137 finished with value: 0.9495998622824966 and parameters: {'weight_class_0': 0.0019550544426759882, 'weight_class_1': 0.028861928592017826, 'weight_class_2': 0.01858553493017998}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:46,022] Trial 1138 finished with value: 0.9486851578077005 and parameters: {'weight_class_0': 0.0019027719463322588, 'weight_class_1': 0.029935478044104933, 'weight_class_2': 0.041587617261503514}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  38%|██████████████████████████████████████████████████                                                                                 | 1147/3000 [00:22<00:46, 39.85it/s]

[I 2026-07-03 10:56:46,031] Trial 1139 finished with value: 0.9423386529159542 and parameters: {'weight_class_0': 0.00623183227143091, 'weight_class_1': 0.028776577558697145, 'weight_class_2': 0.01987362416191151}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:46,032] Trial 1140 finished with value: 0.9485113341031187 and parameters: {'weight_class_0': 0.001981839009252609, 'weight_class_1': 0.028266155889507007, 'weight_class_2': 0.04623580261785605}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:46,055] Trial 1141 finished with value: 0.9484644461833375 and parameters: {'weight_class_0': 0.001893892568436116, 'weight_class_1': 0.029005880260530026, 'weight_class_2': 0.045062273059762986}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:46,131] Trial 1143 finished with value: 0.9490992607014599 and parameters: {'weight_class_0': 0.001954360791427027, 'weight_class_1': 0.028575547155440223, 'weight_class_2': 0.012917224040275227}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:46,140] Trial 1142 finished with value: 0.9492962920649802 and parameters: {'weight_class_0': 0.0018480975464564005, 'weight_class_1': 0.030315895439346145, 'weight_class_2': 0.013323168751558982}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:46,153] Trial 1144 finished with value: 0.9484539178176421 and parameters: {'weight_class_0': 0.001949208109247984, 'weight_class_1': 0.024187767307842743, 'weight_class_2': 0.04487313529980834}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:46,164] Trial 1145 finished with value: 0.9488893336564331 and parameters: {'weight_class_0': 0.002078036728550596, 'weight_class_1': 0.024663005575148625, 'weight_class_2': 0.01264423954248312}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:46,202] Trial 1146 finished with value: 0.9483890341373931 and parameters: {'weight_class_0': 0.00209070103604034, 'weight_class_1': 0.02532668462074273, 'weight_class_2': 0.04843192805068478}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:46,237] Trial 1148 finished with value: 0.9488117796783776 and parameters: {'weight_class_0': 0.002195235384379423, 'weight_class_1': 0.023327004170622497, 'weight_class_2': 0.013842315947384533}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  39%|██████████████████████████████████████████████████▍                                                                                | 1156/3000 [00:22<00:43, 41.95it/s]

[I 2026-07-03 10:56:46,276] Trial 1147 finished with value: 0.9382517199587829 and parameters: {'weight_class_0': 0.005249233081856909, 'weight_class_1': 0.02331269745822464, 'weight_class_2': 0.013264451988683767}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:46,295] Trial 1149 finished with value: 0.8856083897803936 and parameters: {'weight_class_0': 0.002257013883867989, 'weight_class_1': 0.022338522053452645, 'weight_class_2': 0.5904881183041678}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:46,312] Trial 1150 finished with value: 0.9491744223738245 and parameters: {'weight_class_0': 0.0014886348139266082, 'weight_class_1': 0.023078223420522345, 'weight_class_2': 0.025391843852945337}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:46,328] Trial 1151 finished with value: 0.9404128057164894 and parameters: {'weight_class_0': 0.005043653273633664, 'weight_class_1': 0.023403631874776103, 'weight_class_2': 0.014083213512307492}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:46,355] Trial 1152 finished with value: 0.9495402552295381 and parameters: {'weight_class_0': 0.0022412272407566092, 'weight_class_1': 0.023338892549729692, 'weight_class_2': 0.025289741547613855}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:46,363] Trial 1153 finished with value: 0.9466375623140967 and parameters: {'weight_class_0': 0.004862156771976551, 'weight_class_1': 0.023141973926428586, 'weight_class_2': 0.025583554667078588}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:46,431] Trial 1155 finished with value: 0.6385641813864663 and parameters: {'weight_class_0': 0.004965036564941079, 'weight_class_1': 0.021683964411543428, 'weight_class_2': 6.698920350205934}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:46,431] Trial 1154 finished with value: 0.6677015036545851 and parameters: {'weight_class_0': 0.0013670459371710965, 'weight_class_1': 2.595955913331882, 'weight_class_2': 0.025639039296927846}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:46,461] Trial 1156 finished with value: 0.9490130627996027 and parameters: {'weight_class_0': 0.0024802477310178106, 'weight_class_1': 0.017187582022107576, 'weight_class_2': 0.02541907100066309}. Best is trial 579 with value: 0.9497138399884486.

[I 2026-07-03 10:56:46,479] Trial 1157 finished with value: 0.9490231260009875 and parameters: {'weight_class_0': 0.0015799189292263988, 'weight_class_1': 0.01637357038421268, 'weight_class_2': 0.026033853408555525}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:46,511] Trial 1158 finished with value: 0.9428343120163486 and parameters: {'weight_class_0': 0.00488698757885936, 'weight_class_1': 0.01491267781533934, 'weight_class_2': 0.025614070112318966}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:46,532] Trial 1159 finished with value: 0.9489353339107169 and parameters: {'weight_class_0': 0.0015664924284796665, 'weight_class_1': 0.015893777071259024, 'weight_class_2': 0.02655575310806916}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:46,541] Trial 1160 finished with value: 0.9488843267959818 and parameters: {'weight_class_0': 0.001415410009072135, 'weight_class_1': 0.016300459145499213, 'weight_class_2': 0.025453550703253655}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:46,579] Trial 1161 finished with value: 0.9487964141484252 and parameters: {'weight_class_0': 0.0015054416109743268, 'weight_class_1': 0.013823149070119929, 'weight_class_2': 0.025586405768744207}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:46,610] Trial 1162 finished with value: 0.9484735351801019 and parameters: {'weight_class_0': 0.0013513543082097066, 'weight_class_1': 0.01754819868684424, 'weight_class_2': 0.031341217248811115}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:46,619] Trial 1163 finished with value: 0.8999687263758709 and parameters: {'weight_class_0': 0.0014120451814092876, 'weight_class_1': 0.273476814573157, 'weight_class_2': 0.029481481342765452}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:46,639] Trial 1164 finished with value: 0.9484769876638915 and parameters: {'weight_class_0': 0.0013743477976609752, 'weight_class_1': 0.01673734868788918, 'weight_class_2': 0.030942378599878407}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:46,648] Trial 1165 finished with value: 0.9486740410216319 and parameters: {'weight_class_0': 0.0015420925477248326, 'weight_class_1': 0.016863964517296326, 'weight_class_2': 0.029764012336187626}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  39%|███████████████████████████████████████████████████▎                                                                               | 1174/3000 [00:23<00:45, 40.25it/s]

[I 2026-07-03 10:56:46,680] Trial 1166 finished with value: 0.9482148103283858 and parameters: {'weight_class_0': 0.0036539997111112396, 'weight_class_1': 0.018668060092454815, 'weight_class_2': 0.03185698098293884}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:46,711] Trial 1167 finished with value: 0.9467062919194715 and parameters: {'weight_class_0': 0.0034691071966967716, 'weight_class_1': 0.013741458861643258, 'weight_class_2': 0.03255506123778261}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:46,739] Trial 1168 finished with value: 0.9495378426656641 and parameters: {'weight_class_0': 0.0037140681381275754, 'weight_class_1': 0.04002424404917679, 'weight_class_2': 0.03354226843261817}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:46,790] Trial 1170 finished with value: 0.9044558324059672 and parameters: {'weight_class_0': 0.0035845550303993568, 'weight_class_1': 0.0020652997001156803, 'weight_class_2': 0.03488741760570643}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:46,799] Trial 1169 finished with value: 0.9496383506512198 and parameters: {'weight_class_0': 0.0036049417151600796, 'weight_class_1': 0.04265466443277477, 'weight_class_2': 0.03259458979168648}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:46,848] Trial 1173 finished with value: 0.9489611124815992 and parameters: {'weight_class_0': 0.0034563800040039593, 'weight_class_1': 0.04308568681859273, 'weight_class_2': 0.021416250389911552}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:46,852] Trial 1172 finished with value: 0.9496466422200225 and parameters: {'weight_class_0': 0.0035948250717181955, 'weight_class_1': 0.042564685685382735, 'weight_class_2': 0.030973910528800264}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:46,853] Trial 1171 finished with value: 0.9495507342376998 and parameters: {'weight_class_0': 0.0037456470814958044, 'weight_class_1': 0.0389822824285204, 'weight_class_2': 0.03241560234268363}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:46,891] Trial 1174 finished with value: 0.9486865693114348 and parameters: {'weight_class_0': 0.0037557885419546135, 'weight_class_1': 0.04452108517740124, 'weight_class_2': 0.02110786873995316}. Best is trial 579 with value: 0.9497138399884486.

[I 2026-07-03 10:56:46,897] Trial 1175 finished with value: 0.9496317548010976 and parameters: {'weight_class_0': 0.002569788151864069, 'weight_class_1': 0.042726962247744, 'weight_class_2': 0.021081987064071547}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:46,929] Trial 1176 finished with value: 0.9496017583091528 and parameters: {'weight_class_0': 0.002585323959345902, 'weight_class_1': 0.042693476629168545, 'weight_class_2': 0.02166416172226308}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:46,969] Trial 1178 finished with value: 0.9494787211979653 and parameters: {'weight_class_0': 0.002800739539184672, 'weight_class_1': 0.043372421072727325, 'weight_class_2': 0.021691389838873254}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:46,980] Trial 1177 finished with value: 0.9496250904779937 and parameters: {'weight_class_0': 0.0026213309394029338, 'weight_class_1': 0.042287402207755405, 'weight_class_2': 0.021324054717603954}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:47,021] Trial 1179 finished with value: 0.9011394710339329 and parameters: {'weight_class_0': 0.0024904993359936983, 'weight_class_1': 0.0012390444247698078, 'weight_class_2': 0.020962087226893116}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:47,023] Trial 1180 finished with value: 0.9494303297894996 and parameters: {'weight_class_0': 0.002631707439785675, 'weight_class_1': 0.043025697212599884, 'weight_class_2': 0.02034432904448033}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:47,069] Trial 1181 finished with value: 0.9493993063971682 and parameters: {'weight_class_0': 0.0025500239558548694, 'weight_class_1': 0.06124220958449599, 'weight_class_2': 0.021861259427069502}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:47,083] Trial 1182 finished with value: 0.9496202871755112 and parameters: {'weight_class_0': 0.0025725303903479215, 'weight_class_1': 0.03175832001440297, 'weight_class_2': 0.020913879627837605}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:47,089] Trial 1183 finished with value: 0.9495482558837277 and parameters: {'weight_class_0': 0.0026407759374489563, 'weight_class_1': 0.03361394269893634, 'weight_class_2': 0.020882403439843437}. Best is trial 579 with value: 0.9497138399884486.

[I 2026-07-03 10:56:47,126] Trial 1184 finished with value: 0.9494440329528211 and parameters: {'weight_class_0': 0.002628544811446198, 'weight_class_1': 0.05864909360943213, 'weight_class_2': 0.021986231978095162}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:47,162] Trial 1186 finished with value: 0.9496110150644027 and parameters: {'weight_class_0': 0.002606459822313008, 'weight_class_1': 0.032851388175333444, 'weight_class_2': 0.021052211925536326}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:47,183] Trial 1185 finished with value: 0.9493717786546928 and parameters: {'weight_class_0': 0.0025485269593849102, 'weight_class_1': 0.05680513051656197, 'weight_class_2': 0.020305088500667035}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:47,201] Trial 1187 finished with value: 0.9483711304209136 and parameters: {'weight_class_0': 0.0025152463873723504, 'weight_class_1': 0.06079403212417821, 'weight_class_2': 0.014621108433711607}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:47,222] Trial 1188 finished with value: 0.9489869357155509 and parameters: {'weight_class_0': 0.00241811262840207, 'weight_class_1': 0.033600438282026225, 'weight_class_2': 0.01533226844006003}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:47,256] Trial 1189 finished with value: 0.9489255567805298 and parameters: {'weight_class_0': 0.002412020598665415, 'weight_class_1': 0.032237814981036665, 'weight_class_2': 0.014948204224678024}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:47,265] Trial 1190 finished with value: 0.9496026822054716 and parameters: {'weight_class_0': 0.0017166652025433033, 'weight_class_1': 0.032694270744464585, 'weight_class_2': 0.015755565344827777}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:47,293] Trial 1191 finished with value: 0.9487450837187271 and parameters: {'weight_class_0': 0.0022240045999418084, 'weight_class_1': 0.060508250100327704, 'weight_class_2': 0.04006643518999856}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:47,331] Trial 1192 finished with value: 0.9496212981288575 and parameters: {'weight_class_0': 0.0017205785700716153, 'weight_class_1': 0.026660499832131104, 'weight_class_2': 0.014865573539769224}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  40%|████████████████████████████████████████████████████▍                                                                              | 1201/3000 [00:23<00:42, 42.18it/s]

[I 2026-07-03 10:56:47,336] Trial 1193 finished with value: 0.9496002145867655 and parameters: {'weight_class_0': 0.0017302804116149685, 'weight_class_1': 0.02666494440771232, 'weight_class_2': 0.01489875997400863}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:47,362] Trial 1194 finished with value: 0.949641843368712 and parameters: {'weight_class_0': 0.0017295311789224845, 'weight_class_1': 0.020493539618664024, 'weight_class_2': 0.014875575664394918}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:47,379] Trial 1195 finished with value: 0.9495841830744641 and parameters: {'weight_class_0': 0.0016786212469227981, 'weight_class_1': 0.026928990613482102, 'weight_class_2': 0.015109304698456484}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:47,421] Trial 1196 finished with value: 0.9486321040473982 and parameters: {'weight_class_0': 0.0021572159531841025, 'weight_class_1': 0.020710251394865264, 'weight_class_2': 0.039160309343756854}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:47,463] Trial 1197 finished with value: 0.9084288164769329 and parameters: {'weight_class_0': 0.012271370626928945, 'weight_class_1': 0.026322525575876377, 'weight_class_2': 0.015581755374854499}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:47,470] Trial 1198 finished with value: 0.9483117235561814 and parameters: {'weight_class_0': 0.001706253787366926, 'weight_class_1': 0.02018374895374806, 'weight_class_2': 0.04019771669231199}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:47,496] Trial 1199 finished with value: 0.9486817087872108 and parameters: {'weight_class_0': 0.0016869844844808496, 'weight_class_1': 0.01970498781540542, 'weight_class_2': 0.009500910140206965}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:47,513] Trial 1200 finished with value: 0.9483049098245853 and parameters: {'weight_class_0': 0.0016878031887086404, 'weight_class_1': 0.020086207368008126, 'weight_class_2': 0.0398610547305114}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:47,516] Trial 1201 finished with value: 0.9484176207873029 and parameters: {'weight_class_0': 0.0017511564318236572, 'weight_class_1': 0.020550123019901004, 'weight_class_2': 0.039321585515236734}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  40%|████████████████████████████████████████████████████▊                                                                              | 1210/3000 [00:23<00:42, 42.41it/s]

[I 2026-07-03 10:56:47,583] Trial 1202 finished with value: 0.9479799023665013 and parameters: {'weight_class_0': 0.0019602163295257867, 'weight_class_1': 0.020878929453119515, 'weight_class_2': 0.009481880094896073}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:47,592] Trial 1203 finished with value: 0.49961006046199485 and parameters: {'weight_class_0': 8.558730724159107, 'weight_class_1': 0.019516700920850772, 'weight_class_2': 0.038480391041886185}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:47,606] Trial 1204 finished with value: 0.9478573961817288 and parameters: {'weight_class_0': 0.0020007908553491, 'weight_class_1': 0.02027174175976184, 'weight_class_2': 0.009403817568309368}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:47,614] Trial 1205 finished with value: 0.9483086201475418 and parameters: {'weight_class_0': 0.002079934230980211, 'weight_class_1': 0.019801519013286806, 'weight_class_2': 0.011006892841446984}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:47,674] Trial 1206 finished with value: 0.948660735821829 and parameters: {'weight_class_0': 0.0021616540869153324, 'weight_class_1': 0.020449619446695485, 'weight_class_2': 0.038699344712035066}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:47,675] Trial 1207 finished with value: 0.9480979516009637 and parameters: {'weight_class_0': 0.001997594895578466, 'weight_class_1': 0.01916617172025664, 'weight_class_2': 0.01002812229687391}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:47,690] Trial 1208 finished with value: 0.9482473050620484 and parameters: {'weight_class_0': 0.0020706276594240364, 'weight_class_1': 0.025965749522359347, 'weight_class_2': 0.010412240270211027}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:47,733] Trial 1209 finished with value: 0.948914030993475 and parameters: {'weight_class_0': 0.0031477433548420695, 'weight_class_1': 0.019931813802461788, 'weight_class_2': 0.0267301432387569}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:47,748] Trial 1210 finished with value: 0.8214992154300506 and parameters: {'weight_class_0': 0.22204027897808765, 'weight_class_1': 0.03446644167243969, 'weight_class_2': 0.0268020921265787}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  41%|█████████████████████████████████████████████████████▏                                                                             | 1219/3000 [00:24<00:44, 39.66it/s]

[I 2026-07-03 10:56:47,778] Trial 1211 finished with value: 0.9494684903157591 and parameters: {'weight_class_0': 0.0031257798175969563, 'weight_class_1': 0.026339495221417247, 'weight_class_2': 0.02653351241245239}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:47,821] Trial 1212 finished with value: 0.9496521707304622 and parameters: {'weight_class_0': 0.002212778774799525, 'weight_class_1': 0.02575048565846858, 'weight_class_2': 0.025778495298188157}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:47,822] Trial 1213 finished with value: 0.9496184329785647 and parameters: {'weight_class_0': 0.003000907241232564, 'weight_class_1': 0.035157136653689795, 'weight_class_2': 0.026929068801460444}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:47,862] Trial 1214 finished with value: 0.9495607385749923 and parameters: {'weight_class_0': 0.003061905810599996, 'weight_class_1': 0.03338054926183133, 'weight_class_2': 0.02560832080652187}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:47,877] Trial 1215 finished with value: 0.9393422322778658 and parameters: {'weight_class_0': 0.0029723844378679275, 'weight_class_1': 0.03439936217993483, 'weight_class_2': 0.00712282811759348}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:47,908] Trial 1216 finished with value: 0.9496395514190427 and parameters: {'weight_class_0': 0.003095411178783074, 'weight_class_1': 0.035029895355355334, 'weight_class_2': 0.027102311039557084}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:47,932] Trial 1217 finished with value: 0.9494783925408422 and parameters: {'weight_class_0': 0.0031223428526336076, 'weight_class_1': 0.026948462537276268, 'weight_class_2': 0.027330196276448056}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:47,939] Trial 1218 finished with value: 0.9496213044178035 and parameters: {'weight_class_0': 0.003185545309307452, 'weight_class_1': 0.03596465196591042, 'weight_class_2': 0.026145649391767067}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:47,979] Trial 1219 finished with value: 0.9494211015104425 and parameters: {'weight_class_0': 0.0032565889527225427, 'weight_class_1': 0.03463616675695707, 'weight_class_2': 0.025459149638800038}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  41%|█████████████████████████████████████████████████████▌                                                                             | 1228/3000 [00:24<00:43, 40.55it/s]

[I 2026-07-03 10:56:47,991] Trial 1220 finished with value: 0.9494079565210214 and parameters: {'weight_class_0': 0.003055780778954967, 'weight_class_1': 0.02696684379149621, 'weight_class_2': 0.024186124906473424}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:48,018] Trial 1221 finished with value: 0.9469220542194874 and parameters: {'weight_class_0': 0.0012435875215601887, 'weight_class_1': 0.03287171908905527, 'weight_class_2': 0.057352600713207504}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:48,074] Trial 1223 finished with value: 0.9491049306741332 and parameters: {'weight_class_0': 0.0012280986328002835, 'weight_class_1': 0.03249733169051449, 'weight_class_2': 0.018422587057160246}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:48,084] Trial 1222 finished with value: 0.9493142467775516 and parameters: {'weight_class_0': 0.0012920282072437495, 'weight_class_1': 0.028683855720378657, 'weight_class_2': 0.01812568847569375}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:48,124] Trial 1224 finished with value: 0.9492156981493441 and parameters: {'weight_class_0': 0.0012637354251645839, 'weight_class_1': 0.030587533056128807, 'weight_class_2': 0.017705905660955867}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:48,124] Trial 1225 finished with value: 0.9492078606142927 and parameters: {'weight_class_0': 0.0012184855738042607, 'weight_class_1': 0.028992349424296494, 'weight_class_2': 0.018212865058644653}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:48,163] Trial 1226 finished with value: 0.9494957464448485 and parameters: {'weight_class_0': 0.0013873574160379446, 'weight_class_1': 0.02878932743899102, 'weight_class_2': 0.017649423425461174}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:48,180] Trial 1227 finished with value: 0.9493924384461451 and parameters: {'weight_class_0': 0.0013272900040452048, 'weight_class_1': 0.028994798852559407, 'weight_class_2': 0.018457333267557025}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:48,210] Trial 1228 finished with value: 0.9463162181547752 and parameters: {'weight_class_0': 0.004279946651875012, 'weight_class_1': 0.025572847577554087, 'weight_class_2': 0.01838488386326978}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  41%|█████████████████████████████████████████████████████▉                                                                             | 1236/3000 [00:24<00:43, 40.44it/s]

[I 2026-07-03 10:56:48,232] Trial 1229 finished with value: 0.7994067359801305 and parameters: {'weight_class_0': 0.786100632141033, 'weight_class_1': 0.028122744105080456, 'weight_class_2': 0.016771390514908266}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:48,254] Trial 1230 finished with value: 0.9493126010172919 and parameters: {'weight_class_0': 0.0012613936314523906, 'weight_class_1': 0.030266179839892597, 'weight_class_2': 0.016999415065375303}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:48,272] Trial 1231 finished with value: 0.9487224800367611 and parameters: {'weight_class_0': 0.0010188691633387008, 'weight_class_1': 0.027780019960297952, 'weight_class_2': 0.01852717996968412}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:48,299] Trial 1233 finished with value: 0.9494810754377941 and parameters: {'weight_class_0': 0.0014019376060115496, 'weight_class_1': 0.029042081506044388, 'weight_class_2': 0.018165552683604654}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:48,317] Trial 1232 finished with value: 0.9464907474755817 and parameters: {'weight_class_0': 0.004224726438391873, 'weight_class_1': 0.02734729882062368, 'weight_class_2': 0.018103834322737933}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:48,326] Trial 1234 finished with value: 0.9493092226400202 and parameters: {'weight_class_0': 0.0022589699007074778, 'weight_class_1': 0.024249462751933955, 'weight_class_2': 0.017243489340067957}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:48,363] Trial 1235 finished with value: 0.9464240872106267 and parameters: {'weight_class_0': 0.004200133646111492, 'weight_class_1': 0.024376536715750814, 'weight_class_2': 0.018536233405561344}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:48,390] Trial 1236 finished with value: 0.9486411948067287 and parameters: {'weight_class_0': 0.001016201392996341, 'weight_class_1': 0.024349634874219005, 'weight_class_2': 0.021427964381125833}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  42%|██████████████████████████████████████████████████████▍                                                                            | 1246/3000 [00:24<00:42, 40.98it/s]

[I 2026-07-03 10:56:48,443] Trial 1238 finished with value: 0.918704661279921 and parameters: {'weight_class_0': 0.002135974913311644, 'weight_class_1': 0.023940442276103185, 'weight_class_2': 0.38993223502747093}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:48,462] Trial 1239 finished with value: 0.8064931142076271 and parameters: {'weight_class_0': 0.7754286001292457, 'weight_class_1': 0.049832346080534586, 'weight_class_2': 0.022300968460469753}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:48,465] Trial 1237 finished with value: 0.94717921640951 and parameters: {'weight_class_0': 0.0042985979539292936, 'weight_class_1': 0.023761305531436447, 'weight_class_2': 0.022171508553208034}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:48,503] Trial 1240 finished with value: 0.9474823667831253 and parameters: {'weight_class_0': 0.0022312513182554043, 'weight_class_1': 0.010030036125675398, 'weight_class_2': 0.022072318356854387}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:48,514] Trial 1241 finished with value: 0.9486222907722334 and parameters: {'weight_class_0': 0.0021596926127470726, 'weight_class_1': 0.023320305828632693, 'weight_class_2': 0.012054822191231546}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:48,518] Trial 1242 finished with value: 0.9493907148883315 and parameters: {'weight_class_0': 0.0022461750962442565, 'weight_class_1': 0.053241492108004204, 'weight_class_2': 0.021675219425429087}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:48,549] Trial 1243 finished with value: 0.948342822950378 and parameters: {'weight_class_0': 0.002217613510652786, 'weight_class_1': 0.05061626712590545, 'weight_class_2': 0.012306490161487446}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:48,597] Trial 1244 finished with value: 0.9474563004940313 and parameters: {'weight_class_0': 0.002293127115622267, 'weight_class_1': 0.010237489758711363, 'weight_class_2': 0.02202078794227336}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:48,600] Trial 1245 finished with value: 0.9493576146010989 and parameters: {'weight_class_0': 0.001910495195238332, 'weight_class_1': 0.05003778674823934, 'weight_class_2': 0.022422202775245287}. Best is trial 579 with value: 0.9497138399884486.

[I 2026-07-03 10:56:48,648] Trial 1246 finished with value: 0.9493379502507464 and parameters: {'weight_class_0': 0.0021222284028185163, 'weight_class_1': 0.05195403170848717, 'weight_class_2': 0.022361298944711776}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:48,658] Trial 1247 finished with value: 0.9481929947692193 and parameters: {'weight_class_0': 0.002373196114096415, 'weight_class_1': 0.040084105753080856, 'weight_class_2': 0.012104520123887193}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:48,691] Trial 1248 finished with value: 0.9483201904866903 and parameters: {'weight_class_0': 0.0022598323142658697, 'weight_class_1': 0.05362811440973082, 'weight_class_2': 0.012818893313357073}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:48,726] Trial 1250 finished with value: 0.948333997683848 and parameters: {'weight_class_0': 0.00224373641221364, 'weight_class_1': 0.01374860094374728, 'weight_class_2': 0.03191558284317874}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:48,727] Trial 1249 finished with value: 0.9484831665563221 and parameters: {'weight_class_0': 0.002247544675054683, 'weight_class_1': 0.040788628196696826, 'weight_class_2': 0.012234958118100655}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:48,774] Trial 1251 finished with value: 0.9488645386857538 and parameters: {'weight_class_0': 0.0017475565083420075, 'weight_class_1': 0.03983289707706568, 'weight_class_2': 0.03219069071233659}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:48,820] Trial 1253 finished with value: 0.9487528512181013 and parameters: {'weight_class_0': 0.0016121652307950253, 'weight_class_1': 0.040261204342507226, 'weight_class_2': 0.030901869671203223}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:48,839] Trial 1252 finished with value: 0.9488701986784452 and parameters: {'weight_class_0': 0.0017148027664044023, 'weight_class_1': 0.03910652833573441, 'weight_class_2': 0.0317622647207975}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:48,842] Trial 1255 finished with value: 0.9487479323157747 and parameters: {'weight_class_0': 0.0016605363986209503, 'weight_class_1': 0.038196163274918093, 'weight_class_2': 0.03388076942453767}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  42%|███████████████████████████████████████████████████████▏                                                                           | 1263/3000 [00:25<00:42, 40.82it/s]

[I 2026-07-03 10:56:48,856] Trial 1254 finished with value: 0.9489316334781056 and parameters: {'weight_class_0': 0.0017133404395244772, 'weight_class_1': 0.03922576032266034, 'weight_class_2': 0.030693010559330876}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:48,873] Trial 1256 finished with value: 0.9489930655587094 and parameters: {'weight_class_0': 0.0017727723191560474, 'weight_class_1': 0.038546110417299786, 'weight_class_2': 0.031728597550147015}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:48,902] Trial 1257 finished with value: 0.9487463984493613 and parameters: {'weight_class_0': 0.0016688356741063354, 'weight_class_1': 0.03948639239412978, 'weight_class_2': 0.033163261687321}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:48,939] Trial 1258 finished with value: 0.9487559233687888 and parameters: {'weight_class_0': 0.0016671777733512074, 'weight_class_1': 0.041236181245154525, 'weight_class_2': 0.03238289233323618}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:48,943] Trial 1259 finished with value: 0.9484683436006544 and parameters: {'weight_class_0': 0.0017836528977198014, 'weight_class_1': 0.013637971869338622, 'weight_class_2': 0.03084422902778534}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:48,982] Trial 1260 finished with value: 0.9490573085904588 and parameters: {'weight_class_0': 0.0017786172152541252, 'weight_class_1': 0.038604585731717066, 'weight_class_2': 0.031151790054632613}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:49,015] Trial 1261 finished with value: 0.9480668299443126 and parameters: {'weight_class_0': 0.0017732895210518056, 'weight_class_1': 0.07585601903670504, 'weight_class_2': 0.029820150220161965}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:49,020] Trial 1262 finished with value: 0.9488661843432169 and parameters: {'weight_class_0': 0.0016869228831436624, 'weight_class_1': 0.03720353680284689, 'weight_class_2': 0.03313969881906407}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:49,032] Trial 1263 finished with value: 0.9489048073041553 and parameters: {'weight_class_0': 0.001745789152075718, 'weight_class_1': 0.03814377634475161, 'weight_class_2': 0.03218354253758692}. Best is trial 579 with value: 0.9497138399884486.

[I 2026-07-03 10:56:49,092] Trial 1264 finished with value: 0.9496997587998948 and parameters: {'weight_class_0': 0.0028022330916614617, 'weight_class_1': 0.03421403954248035, 'weight_class_2': 0.03070098402119908}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:49,113] Trial 1265 finished with value: 0.9486329078873826 and parameters: {'weight_class_0': 0.002843043059933982, 'weight_class_1': 0.017179653460234055, 'weight_class_2': 0.029365245600843748}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:49,125] Trial 1266 finished with value: 0.9492672681893626 and parameters: {'weight_class_0': 0.0027712984077519374, 'weight_class_1': 0.07498737477166431, 'weight_class_2': 0.023607521672310696}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:49,153] Trial 1268 finished with value: 0.949328008174688 and parameters: {'weight_class_0': 0.0027899592847100375, 'weight_class_1': 0.07056111100152797, 'weight_class_2': 0.024622741742512794}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:49,177] Trial 1267 finished with value: 0.9484342485663008 and parameters: {'weight_class_0': 0.0026899408635274753, 'weight_class_1': 0.01482094950163248, 'weight_class_2': 0.02534382255089836}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:49,192] Trial 1269 finished with value: 0.9486578747472295 and parameters: {'weight_class_0': 0.0027726114144491507, 'weight_class_1': 0.016188350189104396, 'weight_class_2': 0.024272542972761803}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:49,217] Trial 1270 finished with value: 0.9492455045179566 and parameters: {'weight_class_0': 0.0029680766415192705, 'weight_class_1': 0.07542629041201157, 'weight_class_2': 0.023842835390839597}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:49,248] Trial 1271 finished with value: 0.9409221118605785 and parameters: {'weight_class_0': 0.002772380917773622, 'weight_class_1': 0.006741773973769875, 'weight_class_2': 0.024398214126891107}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 579. Best value: 0.949714:  43%|███████████████████████████████████████████████████████▉                                                                           | 1280/3000 [00:25<00:45, 37.84it/s]

[I 2026-07-03 10:56:49,296] Trial 1274 finished with value: 0.9488452922424638 and parameters: {'weight_class_0': 0.0027381607481382552, 'weight_class_1': 0.017315867132851184, 'weight_class_2': 0.022999252110628896}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:49,297] Trial 1273 finished with value: 0.9488972834332209 and parameters: {'weight_class_0': 0.0027375135555788538, 'weight_class_1': 0.017312798375264074, 'weight_class_2': 0.0236768153860962}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:49,313] Trial 1272 finished with value: 0.9488120583214976 and parameters: {'weight_class_0': 0.0027070854557420844, 'weight_class_1': 0.01669418330535902, 'weight_class_2': 0.023744354934200712}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:49,326] Trial 1275 finished with value: 0.9488915204852009 and parameters: {'weight_class_0': 0.002751927016792857, 'weight_class_1': 0.017691736700017537, 'weight_class_2': 0.022843724113344115}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:49,380] Trial 1276 finished with value: 0.9491828808198295 and parameters: {'weight_class_0': 0.003810757587005105, 'weight_class_1': 0.03250523952894504, 'weight_class_2': 0.05259948422430869}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:49,405] Trial 1279 finished with value: 0.9493078149446145 and parameters: {'weight_class_0': 0.0038792807846371727, 'weight_class_1': 0.03289869698069901, 'weight_class_2': 0.0494039894536669}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:49,408] Trial 1278 finished with value: 0.9490062078681084 and parameters: {'weight_class_0': 0.003878943859527035, 'weight_class_1': 0.032556803727799434, 'weight_class_2': 0.057584761595106046}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:49,414] Trial 1277 finished with value: 0.9473621474767427 and parameters: {'weight_class_0': 0.006581445847721194, 'weight_class_1': 0.031997817943207496, 'weight_class_2': 0.041742289039803336}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:49,479] Trial 1281 finished with value: 0.9491938875498257 and parameters: {'weight_class_0': 0.003985789716640511, 'weight_class_1': 0.03250164433034803, 'weight_class_2': 0.053321009382674096}. Best is trial 579 with value: 0.9497138399884486.

Best trial: 1287. Best value: 0.949717:  43%|███████████████████████████████████████████████████████▉                                                                          | 1290/3000 [00:25<00:40, 42.08it/s]

[I 2026-07-03 10:56:49,486] Trial 1280 finished with value: 0.9060006866674613 and parameters: {'weight_class_0': 0.025909076471632982, 'weight_class_1': 0.03099580691245039, 'weight_class_2': 0.04852402461153238}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:49,548] Trial 1282 finished with value: 0.9491782948515257 and parameters: {'weight_class_0': 0.0037996520223272903, 'weight_class_1': 0.03154365038895428, 'weight_class_2': 0.04995547791986882}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:49,559] Trial 1283 finished with value: 0.9494787128177834 and parameters: {'weight_class_0': 0.003697903934388318, 'weight_class_1': 0.0331986827514697, 'weight_class_2': 0.04182587952477667}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:49,564] Trial 1285 finished with value: 0.949295742314089 and parameters: {'weight_class_0': 0.003834065845869967, 'weight_class_1': 0.032941429497401704, 'weight_class_2': 0.048563309574921464}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:49,567] Trial 1284 finished with value: 0.9492854056928651 and parameters: {'weight_class_0': 0.0038536783077885006, 'weight_class_1': 0.033307629927886336, 'weight_class_2': 0.04985013518517541}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:49,600] Trial 1286 finished with value: 0.9070391293432896 and parameters: {'weight_class_0': 0.02463261174688967, 'weight_class_1': 0.03244188507788594, 'weight_class_2': 0.0436456192817543}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:49,641] Trial 1288 finished with value: 0.9496702231702288 and parameters: {'weight_class_0': 0.003443784931097101, 'weight_class_1': 0.04869086033472014, 'weight_class_2': 0.03929708236404507}. Best is trial 579 with value: 0.9497138399884486.
[I 2026-07-03 10:56:49,665] Trial 1287 finished with value: 0.9497172498611803 and parameters: {'weight_class_0': 0.0034307367940855835, 'weight_class_1': 0.04429746038045652, 'weight_class_2': 0.0394738247623214}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:49,683] Trial 1289 finished with value: 0.949634765430873 and parameters: {'weight_class_0': 0.003255250068417559, 'weight_class_1': 0.049427398052880614, 'weight_class_2': 0.03793827706157478}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:49,719] Trial 1290 finished with value: 0.9235469378700903 and parameters: {'weight_class_0': 0.0033016586910988603, 'weight_class_1': 0.04522200888284144, 'weight_class_2': 0.004677565669303679}. Best is trial 1287 with value: 0.9497172498611803.

[I 2026-07-03 10:56:49,765] Trial 1292 finished with value: 0.9496573426592674 and parameters: {'weight_class_0': 0.003546586110248563, 'weight_class_1': 0.05056794168539961, 'weight_class_2': 0.030138776562460765}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:49,788] Trial 1291 finished with value: 0.9496796506009004 and parameters: {'weight_class_0': 0.0033233559628922786, 'weight_class_1': 0.04634413619886721, 'weight_class_2': 0.03868041542591867}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:49,796] Trial 1293 finished with value: 0.9496557024891227 and parameters: {'weight_class_0': 0.003354395339583487, 'weight_class_1': 0.051595426126723576, 'weight_class_2': 0.038050363616714565}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:49,833] Trial 1294 finished with value: 0.9496090044581553 and parameters: {'weight_class_0': 0.0031080520826630054, 'weight_class_1': 0.045349623310532536, 'weight_class_2': 0.028714307732302553}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:49,870] Trial 1295 finished with value: 0.9097781693179049 and parameters: {'weight_class_0': 0.0034470957599104317, 'weight_class_1': 0.04714440194838863, 'weight_class_2': 0.003275704887222891}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:49,890] Trial 1297 finished with value: 0.9493666979821503 and parameters: {'weight_class_0': 0.00512153036290228, 'weight_class_1': 0.05960518448223398, 'weight_class_2': 0.039107828637582435}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:49,918] Trial 1296 finished with value: 0.9493936761808531 and parameters: {'weight_class_0': 0.005187031608300361, 'weight_class_1': 0.06412442995352223, 'weight_class_2': 0.03875569443453303}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:49,932] Trial 1298 finished with value: 0.949320185603063 and parameters: {'weight_class_0': 0.0044845284519680825, 'weight_class_1': 0.051826509271315824, 'weight_class_2': 0.06794204996967838}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:49,939] Trial 1299 finished with value: 0.9494943299668478 and parameters: {'weight_class_0': 0.005350158944716647, 'weight_class_1': 0.05702546705368237, 'weight_class_2': 0.04301036044816655}. Best is trial 1287 with value: 0.9497172498611803.

Best trial: 1287. Best value: 0.949717:  44%|████████████████████████████████████████████████████████▋                                                                         | 1308/3000 [00:26<00:41, 40.90it/s]

[I 2026-07-03 10:56:49,956] Trial 1300 finished with value: 0.9495386771609121 and parameters: {'weight_class_0': 0.0035243183813491986, 'weight_class_1': 0.05920817539824326, 'weight_class_2': 0.03622970096291066}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:50,014] Trial 1302 finished with value: 0.9494744744892691 and parameters: {'weight_class_0': 0.005635361628947153, 'weight_class_1': 0.05555147448913841, 'weight_class_2': 0.06715971705299083}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:50,017] Trial 1301 finished with value: 0.9494738392378572 and parameters: {'weight_class_0': 0.005110108348759606, 'weight_class_1': 0.056225498082897576, 'weight_class_2': 0.06840784198266975}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:50,035] Trial 1303 finished with value: 0.9496955701165587 and parameters: {'weight_class_0': 0.0047359209220298685, 'weight_class_1': 0.0670486316560337, 'weight_class_2': 0.052950125386600704}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:50,041] Trial 1304 finished with value: 0.9495377783764903 and parameters: {'weight_class_0': 0.005338933576891721, 'weight_class_1': 0.052597756204862414, 'weight_class_2': 0.048193449047140166}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:50,097] Trial 1305 finished with value: 0.9492019445541785 and parameters: {'weight_class_0': 0.006668043730185324, 'weight_class_1': 0.06456692635192163, 'weight_class_2': 0.04951250841034705}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:50,100] Trial 1306 finished with value: 0.949695635968428 and parameters: {'weight_class_0': 0.0050108568083797565, 'weight_class_1': 0.05886354932241622, 'weight_class_2': 0.056416820599885}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:50,153] Trial 1308 finished with value: 0.9495380938446644 and parameters: {'weight_class_0': 0.006463592186969964, 'weight_class_1': 0.06054087437856118, 'weight_class_2': 0.055294133484373266}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:50,156] Trial 1307 finished with value: 0.9492733790966029 and parameters: {'weight_class_0': 0.0050577029850848235, 'weight_class_1': 0.06228260979515347, 'weight_class_2': 0.08146389986752803}. Best is trial 1287 with value: 0.9497172498611803.

[I 2026-07-03 10:56:50,199] Trial 1310 finished with value: 0.94951470065014 and parameters: {'weight_class_0': 0.004065449307679145, 'weight_class_1': 0.08956958181097124, 'weight_class_2': 0.03431122424108612}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:50,202] Trial 1309 finished with value: 0.9495020816581515 and parameters: {'weight_class_0': 0.0062672473724985685, 'weight_class_1': 0.059447551205184544, 'weight_class_2': 0.05941001390157978}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:50,231] Trial 1311 finished with value: 0.9495043166326983 and parameters: {'weight_class_0': 0.006724512030346503, 'weight_class_1': 0.07285376961279515, 'weight_class_2': 0.0539770207584218}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:50,278] Trial 1313 finished with value: 0.9494261689091235 and parameters: {'weight_class_0': 0.004731921161962959, 'weight_class_1': 0.1057493940536961, 'weight_class_2': 0.06077988426528114}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:50,283] Trial 1312 finished with value: 0.9489272047622218 and parameters: {'weight_class_0': 0.004388405815719312, 'weight_class_1': 0.0733889533602268, 'weight_class_2': 0.08720765129583717}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:50,310] Trial 1314 finished with value: 0.9495458959673462 and parameters: {'weight_class_0': 0.0058330786849245956, 'weight_class_1': 0.06375337159533634, 'weight_class_2': 0.05332295018413636}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:50,357] Trial 1315 finished with value: 0.9496541660885002 and parameters: {'weight_class_0': 0.006736051481468863, 'weight_class_1': 0.08149843832223798, 'weight_class_2': 0.05788065143045236}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:50,371] Trial 1316 finished with value: 0.949568726819185 and parameters: {'weight_class_0': 0.006681902994554652, 'weight_class_1': 0.12097207320676372, 'weight_class_2': 0.08473753946176393}. Best is trial 1287 with value: 0.9497172498611803.

[I 2026-07-03 10:56:50,422] Trial 1317 finished with value: 0.94891597925311 and parameters: {'weight_class_0': 0.009084412340702406, 'weight_class_1': 0.06886805981910758, 'weight_class_2': 0.06387174107578868}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:50,433] Trial 1318 finished with value: 0.949631561036866 and parameters: {'weight_class_0': 0.0067215381854492185, 'weight_class_1': 0.08827814133917869, 'weight_class_2': 0.07139253094962936}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:50,441] Trial 1319 finished with value: 0.9495739461214717 and parameters: {'weight_class_0': 0.006359891205644035, 'weight_class_1': 0.07439281205667202, 'weight_class_2': 0.0516696726129199}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:50,494] Trial 1320 finished with value: 0.9488498898326346 and parameters: {'weight_class_0': 0.005522771935409692, 'weight_class_1': 0.06896681088882221, 'weight_class_2': 0.10741065268176843}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:50,503] Trial 1321 finished with value: 0.9496221145491904 and parameters: {'weight_class_0': 0.004890552224972418, 'weight_class_1': 0.09134019805137218, 'weight_class_2': 0.045487532593383936}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:50,527] Trial 1322 finished with value: 0.949249075010266 and parameters: {'weight_class_0': 0.009542444863957633, 'weight_class_1': 0.06887896871031492, 'weight_class_2': 0.08044134029175544}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:50,538] Trial 1323 finished with value: 0.9493168313198922 and parameters: {'weight_class_0': 0.005706018047541499, 'weight_class_1': 0.08674727027330303, 'weight_class_2': 0.088588999382334}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:50,574] Trial 1324 finished with value: 0.9492724321906639 and parameters: {'weight_class_0': 0.005095195149903126, 'weight_class_1': 0.09820547526484208, 'weight_class_2': 0.08268841201468495}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:50,610] Trial 1326 finished with value: 0.9496539455830525 and parameters: {'weight_class_0': 0.00690448062472832, 'weight_class_1': 0.07890777156317061, 'weight_class_2': 0.07550447153440559}. Best is trial 1287 with value: 0.9497172498611803.

[I 2026-07-03 10:56:50,611] Trial 1325 finished with value: 0.9494450310053284 and parameters: {'weight_class_0': 0.005148283407482538, 'weight_class_1': 0.07336597872878677, 'weight_class_2': 0.07592047803007268}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:50,639] Trial 1327 finished with value: 0.9495739803827977 and parameters: {'weight_class_0': 0.005998572535039966, 'weight_class_1': 0.09706373673350367, 'weight_class_2': 0.07761907590913791}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:50,659] Trial 1328 finished with value: 0.9496413564234887 and parameters: {'weight_class_0': 0.005796217419167461, 'weight_class_1': 0.08228107142431018, 'weight_class_2': 0.0734471235524056}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:50,673] Trial 1329 finished with value: 0.9496162385717085 and parameters: {'weight_class_0': 0.004258891377794562, 'weight_class_1': 0.07527077331682658, 'weight_class_2': 0.04908834509766034}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:50,704] Trial 1330 finished with value: 0.9495023518169567 and parameters: {'weight_class_0': 0.00945867271909749, 'weight_class_1': 0.09699283728230704, 'weight_class_2': 0.11353118123470242}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:50,736] Trial 1331 finished with value: 0.9493852617111872 and parameters: {'weight_class_0': 0.0051515970108172516, 'weight_class_1': 0.10657364035237508, 'weight_class_2': 0.07297914412009944}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:50,773] Trial 1332 finished with value: 0.9495413969663051 and parameters: {'weight_class_0': 0.004731292227860103, 'weight_class_1': 0.08319017704273193, 'weight_class_2': 0.06253564307273005}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:50,790] Trial 1333 finished with value: 0.949576965324456 and parameters: {'weight_class_0': 0.00438035294673569, 'weight_class_1': 0.07189748795607767, 'weight_class_2': 0.041234944789504006}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:50,826] Trial 1334 finished with value: 0.9493716539497722 and parameters: {'weight_class_0': 0.007285382127681336, 'weight_class_1': 0.059305010668101794, 'weight_class_2': 0.05901109961452921}. Best is trial 1287 with value: 0.9497172498611803.

Best trial: 1341. Best value: 0.94972:  45%|██████████████████████████████████████████████████████████▌                                                                        | 1342/3000 [00:27<00:41, 39.71it/s]

[I 2026-07-03 10:56:50,846] Trial 1335 finished with value: 0.9493327696918131 and parameters: {'weight_class_0': 0.004491027235896742, 'weight_class_1': 0.07888138831286132, 'weight_class_2': 0.07038155784761814}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:50,862] Trial 1336 finished with value: 0.9487385103073231 and parameters: {'weight_class_0': 0.0037717222950447602, 'weight_class_1': 0.13850659946858104, 'weight_class_2': 0.040224458594374436}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:50,924] Trial 1337 finished with value: 0.9496104442541663 and parameters: {'weight_class_0': 0.004539849188107115, 'weight_class_1': 0.0673990221786555, 'weight_class_2': 0.057034547012964176}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:50,926] Trial 1338 finished with value: 0.9489899045928153 and parameters: {'weight_class_0': 0.00812742818109131, 'weight_class_1': 0.06210916855151791, 'weight_class_2': 0.0597834121869089}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:50,935] Trial 1339 finished with value: 0.9494778671273435 and parameters: {'weight_class_0': 0.004305498675107272, 'weight_class_1': 0.06257735061638851, 'weight_class_2': 0.061288973478755275}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:50,969] Trial 1340 finished with value: 0.9492482505737238 and parameters: {'weight_class_0': 0.007596837970757727, 'weight_class_1': 0.06809183085427709, 'weight_class_2': 0.05777498123662626}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:51,016] Trial 1342 finished with value: 0.9495983753914098 and parameters: {'weight_class_0': 0.004847137837045784, 'weight_class_1': 0.06636831210322414, 'weight_class_2': 0.06614180734003576}. Best is trial 1287 with value: 0.9497172498611803.
[I 2026-07-03 10:56:51,017] Trial 1341 finished with value: 0.9497202830040115 and parameters: {'weight_class_0': 0.004658888390844541, 'weight_class_1': 0.056675838107244025, 'weight_class_2': 0.05338619733921493}. Best is trial 1341 with value: 0.9497202830040115.

[I 2026-07-03 10:56:51,054] Trial 1344 finished with value: 0.9493921521660269 and parameters: {'weight_class_0': 0.004451299957628149, 'weight_class_1': 0.05967604684229676, 'weight_class_2': 0.06771909853223211}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:51,055] Trial 1343 finished with value: 0.9496070392722528 and parameters: {'weight_class_0': 0.004240730802116315, 'weight_class_1': 0.05927847187092124, 'weight_class_2': 0.05583405283972009}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:51,067] Trial 1345 finished with value: 0.9485556572591305 and parameters: {'weight_class_0': 0.003925150796519476, 'weight_class_1': 0.14096023244168926, 'weight_class_2': 0.06445569248777475}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:51,089] Trial 1346 finished with value: 0.9497054939864461 and parameters: {'weight_class_0': 0.00421237513924786, 'weight_class_1': 0.05632341493975894, 'weight_class_2': 0.048680366608283065}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:51,145] Trial 1348 finished with value: 0.9492185233308419 and parameters: {'weight_class_0': 0.007600795758192432, 'weight_class_1': 0.05528414625856788, 'weight_class_2': 0.06178894267344153}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:51,153] Trial 1347 finished with value: 0.9495915470158179 and parameters: {'weight_class_0': 0.004608292073282201, 'weight_class_1': 0.05781453456850773, 'weight_class_2': 0.061283066301884355}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:51,192] Trial 1349 finished with value: 0.9496875070616994 and parameters: {'weight_class_0': 0.004045083516879707, 'weight_class_1': 0.04840377798933091, 'weight_class_2': 0.04568810782009934}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:51,236] Trial 1350 finished with value: 0.9496246969482288 and parameters: {'weight_class_0': 0.004601715626619076, 'weight_class_1': 0.05188073353416034, 'weight_class_2': 0.04837559290642875}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:51,236] Trial 1351 finished with value: 0.9496470932880983 and parameters: {'weight_class_0': 0.003999959668929476, 'weight_class_1': 0.04999648325699069, 'weight_class_2': 0.041335928211014235}. Best is trial 1341 with value: 0.9497202830040115.

Best trial: 1341. Best value: 0.94972:  45%|███████████████████████████████████████████████████████████▎                                                                       | 1359/3000 [00:27<00:40, 40.38it/s]

[I 2026-07-03 10:56:51,260] Trial 1352 finished with value: 0.9496267464185107 and parameters: {'weight_class_0': 0.004707065089019982, 'weight_class_1': 0.05460847746894224, 'weight_class_2': 0.050351038380944964}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:51,261] Trial 1353 finished with value: 0.9494888283086002 and parameters: {'weight_class_0': 0.005766631089030904, 'weight_class_1': 0.05478851406726247, 'weight_class_2': 0.05501009355808834}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:51,310] Trial 1354 finished with value: 0.9494045082779584 and parameters: {'weight_class_0': 0.0059420337437337675, 'weight_class_1': 0.050822531481572224, 'weight_class_2': 0.053215245287225196}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:51,347] Trial 1355 finished with value: 0.9495017267501886 and parameters: {'weight_class_0': 0.005697310190462155, 'weight_class_1': 0.0543980949285653, 'weight_class_2': 0.047135360591330625}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:51,378] Trial 1356 finished with value: 0.9495836519376035 and parameters: {'weight_class_0': 0.004908023418036445, 'weight_class_1': 0.053943850260252446, 'weight_class_2': 0.04721273790298803}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:51,397] Trial 1357 finished with value: 0.9495866657150408 and parameters: {'weight_class_0': 0.005337956717123799, 'weight_class_1': 0.08332648875553526, 'weight_class_2': 0.048677124801931475}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:51,436] Trial 1358 finished with value: 0.9496040726849744 and parameters: {'weight_class_0': 0.005781759672850886, 'weight_class_1': 0.08193802301297913, 'weight_class_2': 0.048107800292338875}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:51,465] Trial 1359 finished with value: 0.9495473355780438 and parameters: {'weight_class_0': 0.005534884295811955, 'weight_class_1': 0.0524686404469822, 'weight_class_2': 0.04782650426988514}. Best is trial 1341 with value: 0.9497202830040115.

Best trial: 1341. Best value: 0.94972:  46%|███████████████████████████████████████████████████████████▋                                                                       | 1367/3000 [00:27<00:43, 37.90it/s]

[I 2026-07-03 10:56:51,477] Trial 1360 finished with value: 0.9495714912964212 and parameters: {'weight_class_0': 0.0052797497362707104, 'weight_class_1': 0.08365521508301298, 'weight_class_2': 0.054820672269888494}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:51,516] Trial 1361 finished with value: 0.9496505444558112 and parameters: {'weight_class_0': 0.006098647651446304, 'weight_class_1': 0.08163623555739252, 'weight_class_2': 0.05242209255930621}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:51,547] Trial 1362 finished with value: 0.9495437000875594 and parameters: {'weight_class_0': 0.005775742660615089, 'weight_class_1': 0.0703599049856419, 'weight_class_2': 0.04552820683780679}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:51,570] Trial 1363 finished with value: 0.9496083210340304 and parameters: {'weight_class_0': 0.005631084585505641, 'weight_class_1': 0.08271970740993718, 'weight_class_2': 0.047498508247334564}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:51,579] Trial 1364 finished with value: 0.9491296985039165 and parameters: {'weight_class_0': 0.005754908707725158, 'weight_class_1': 0.0771912704537958, 'weight_class_2': 0.10018330612169701}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:51,612] Trial 1366 finished with value: 0.9496010596937373 and parameters: {'weight_class_0': 0.005586900497081616, 'weight_class_1': 0.07392982838750345, 'weight_class_2': 0.045189030832666385}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:51,615] Trial 1365 finished with value: 0.9496102379733481 and parameters: {'weight_class_0': 0.0042204783552898814, 'weight_class_1': 0.0674700252954441, 'weight_class_2': 0.0448146690458809}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:51,633] Trial 1367 finished with value: 0.9496467855118503 and parameters: {'weight_class_0': 0.005917087582469982, 'weight_class_1': 0.06970338600501574, 'weight_class_2': 0.05057540994952792}. Best is trial 1341 with value: 0.9497202830040115.

Best trial: 1341. Best value: 0.94972:  46%|████████████████████████████████████████████████████████████                                                                       | 1376/3000 [00:28<00:43, 37.30it/s]

[I 2026-07-03 10:56:51,643] Trial 1368 finished with value: 0.9494408109235449 and parameters: {'weight_class_0': 0.006183235354415501, 'weight_class_1': 0.0673293847816447, 'weight_class_2': 0.0483591652030246}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:51,714] Trial 1369 finished with value: 0.9495629383586565 and parameters: {'weight_class_0': 0.005371095834982743, 'weight_class_1': 0.057925381371069735, 'weight_class_2': 0.0568222911639527}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:51,720] Trial 1370 finished with value: 0.9494110538502295 and parameters: {'weight_class_0': 0.007374697627409124, 'weight_class_1': 0.06948797257546757, 'weight_class_2': 0.05897007755572384}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:51,725] Trial 1371 finished with value: 0.949273447873122 and parameters: {'weight_class_0': 0.004507153979103814, 'weight_class_1': 0.049429442647236775, 'weight_class_2': 0.06763530335702635}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:51,801] Trial 1373 finished with value: 0.9493192080804902 and parameters: {'weight_class_0': 0.004167851119471491, 'weight_class_1': 0.06387236704124426, 'weight_class_2': 0.06614157352454386}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:51,817] Trial 1372 finished with value: 0.9495597425586041 and parameters: {'weight_class_0': 0.004190109634345826, 'weight_class_1': 0.07087818826811584, 'weight_class_2': 0.04274374042913047}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:51,828] Trial 1374 finished with value: 0.9485492907554341 and parameters: {'weight_class_0': 0.0073409775233436335, 'weight_class_1': 0.06242193004617412, 'weight_class_2': 0.04251782226490299}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:51,874] Trial 1375 finished with value: 0.9496159267351949 and parameters: {'weight_class_0': 0.00474050952766328, 'weight_class_1': 0.06622732197063039, 'weight_class_2': 0.06413901167119722}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:51,878] Trial 1376 finished with value: 0.9491233537251453 and parameters: {'weight_class_0': 0.004457559934862911, 'weight_class_1': 0.04882649856140399, 'weight_class_2': 0.07122348759460562}. Best is trial 1341 with value: 0.9497202830040115.

Best trial: 1341. Best value: 0.94972:  46%|████████████████████████████████████████████████████████████▍                                                                      | 1384/3000 [00:28<00:39, 40.61it/s]

[I 2026-07-03 10:56:51,901] Trial 1377 finished with value: 0.9495844271450067 and parameters: {'weight_class_0': 0.00432129275333241, 'weight_class_1': 0.04715751635496491, 'weight_class_2': 0.04160369019358739}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:51,933] Trial 1378 finished with value: 0.9496082026074806 and parameters: {'weight_class_0': 0.0043843107598080695, 'weight_class_1': 0.04869871927213676, 'weight_class_2': 0.0428250483115472}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:51,973] Trial 1379 finished with value: 0.9490991205229223 and parameters: {'weight_class_0': 0.003980998298980278, 'weight_class_1': 0.04763533961168025, 'weight_class_2': 0.06745709904420373}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:52,006] Trial 1381 finished with value: 0.9495617315151949 and parameters: {'weight_class_0': 0.004371432292646598, 'weight_class_1': 0.046971922962589736, 'weight_class_2': 0.04191487643808114}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:52,007] Trial 1380 finished with value: 0.9489948032696764 and parameters: {'weight_class_0': 0.004228521209399745, 'weight_class_1': 0.04562317803860282, 'weight_class_2': 0.07091970312622481}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:52,024] Trial 1382 finished with value: 0.9488370862017708 and parameters: {'weight_class_0': 0.004171204395890254, 'weight_class_1': 0.04942093519171993, 'weight_class_2': 0.08045223496651371}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:52,062] Trial 1383 finished with value: 0.9484825835730026 and parameters: {'weight_class_0': 0.004387676116905058, 'weight_class_1': 0.04846297952905484, 'weight_class_2': 0.09221024880916787}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:52,136] Trial 1385 finished with value: 0.949552503405558 and parameters: {'weight_class_0': 0.004374277478980756, 'weight_class_1': 0.047027844142223954, 'weight_class_2': 0.04314182422129027}. Best is trial 1341 with value: 0.9497202830040115.

Best trial: 1341. Best value: 0.94972:  46%|████████████████████████████████████████████████████████████▊                                                                      | 1393/3000 [00:28<00:40, 39.23it/s]

[I 2026-07-03 10:56:52,150] Trial 1387 finished with value: 0.9485971425749766 and parameters: {'weight_class_0': 0.003741194934769027, 'weight_class_1': 0.04616174595772519, 'weight_class_2': 0.08113633631917018}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:52,150] Trial 1386 finished with value: 0.9485150374575185 and parameters: {'weight_class_0': 0.003925460682816201, 'weight_class_1': 0.048282310508022994, 'weight_class_2': 0.08761417082499781}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:52,155] Trial 1384 finished with value: 0.949705786789563 and parameters: {'weight_class_0': 0.003781967680983513, 'weight_class_1': 0.0464238224852916, 'weight_class_2': 0.042111764868904035}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:52,189] Trial 1388 finished with value: 0.9485917713608437 and parameters: {'weight_class_0': 0.007998555820599966, 'weight_class_1': 0.04811972062975494, 'weight_class_2': 0.09030297993189881}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:52,246] Trial 1389 finished with value: 0.9481383361131032 and parameters: {'weight_class_0': 0.003626070759761536, 'weight_class_1': 0.10526549325863392, 'weight_class_2': 0.09369488318029068}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:52,252] Trial 1390 finished with value: 0.9482429663523804 and parameters: {'weight_class_0': 0.003645581040405156, 'weight_class_1': 0.04612226807206479, 'weight_class_2': 0.09104955910932298}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:52,275] Trial 1391 finished with value: 0.9494670608414317 and parameters: {'weight_class_0': 0.003677614524225033, 'weight_class_1': 0.05903332381218469, 'weight_class_2': 0.05453561005494504}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:52,302] Trial 1392 finished with value: 0.9483134119941222 and parameters: {'weight_class_0': 0.0036729775704029497, 'weight_class_1': 0.059674770237659866, 'weight_class_2': 0.09475467068533304}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:52,318] Trial 1393 finished with value: 0.9493525779507737 and parameters: {'weight_class_0': 0.0035551359832534683, 'weight_class_1': 0.05700717973485156, 'weight_class_2': 0.05612141109331364}. Best is trial 1341 with value: 0.9497202830040115.

[I 2026-07-03 10:56:52,343] Trial 1395 finished with value: 0.9494660276959861 and parameters: {'weight_class_0': 0.0036226093090820513, 'weight_class_1': 0.046174262909090866, 'weight_class_2': 0.053624683644187016}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:52,343] Trial 1394 finished with value: 0.9496335239563898 and parameters: {'weight_class_0': 0.0036544185828038395, 'weight_class_1': 0.05748707676743106, 'weight_class_2': 0.0436630913439495}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:52,425] Trial 1396 finished with value: 0.9477507403103514 and parameters: {'weight_class_0': 0.00903648955765737, 'weight_class_1': 0.05249528813378285, 'weight_class_2': 0.05233665098432062}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:52,433] Trial 1397 finished with value: 0.9490466229028584 and parameters: {'weight_class_0': 0.003548720002770647, 'weight_class_1': 0.10478282150696727, 'weight_class_2': 0.053387500288119887}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:52,442] Trial 1398 finished with value: 0.9493374357858207 and parameters: {'weight_class_0': 0.0035358992687739735, 'weight_class_1': 0.062407596866020654, 'weight_class_2': 0.05479079362282498}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:52,475] Trial 1399 finished with value: 0.949419635672978 and parameters: {'weight_class_0': 0.0035592806562931272, 'weight_class_1': 0.06539633052556693, 'weight_class_2': 0.05242521297035037}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:52,521] Trial 1400 finished with value: 0.9496898280604548 and parameters: {'weight_class_0': 0.004921662229003364, 'weight_class_1': 0.06000867364476893, 'weight_class_2': 0.058491692613977166}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:52,527] Trial 1401 finished with value: 0.949553389869282 and parameters: {'weight_class_0': 0.005042445590121016, 'weight_class_1': 0.053694404643628145, 'weight_class_2': 0.04310771877849968}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:52,538] Trial 1402 finished with value: 0.9142315172451294 and parameters: {'weight_class_0': 0.008292174525557704, 'weight_class_1': 1.2741834943020718, 'weight_class_2': 0.05339486699021716}. Best is trial 1341 with value: 0.9497202830040115.

Best trial: 1341. Best value: 0.94972:  47%|█████████████████████████████████████████████████████████████▌                                                                     | 1411/3000 [00:28<00:40, 39.06it/s]

[I 2026-07-03 10:56:52,547] Trial 1403 finished with value: 0.9497004406280127 and parameters: {'weight_class_0': 0.004902738033069781, 'weight_class_1': 0.06047867861008394, 'weight_class_2': 0.05814461736896847}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:52,623] Trial 1405 finished with value: 0.9495775116554687 and parameters: {'weight_class_0': 0.004914028777488667, 'weight_class_1': 0.06781779349093654, 'weight_class_2': 0.03940230953977995}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:52,623] Trial 1404 finished with value: 0.9495448527700381 and parameters: {'weight_class_0': 0.004891803606335332, 'weight_class_1': 0.0975970917991017, 'weight_class_2': 0.0396541338594394}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:52,667] Trial 1406 finished with value: 0.9483163290299084 and parameters: {'weight_class_0': 0.007377421487000827, 'weight_class_1': 0.05670155681149304, 'weight_class_2': 0.04123024787612682}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:52,685] Trial 1407 finished with value: 0.9496381046096567 and parameters: {'weight_class_0': 0.005121784795318126, 'weight_class_1': 0.06093283833795601, 'weight_class_2': 0.04320079755515483}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:52,725] Trial 1408 finished with value: 0.9494719612905028 and parameters: {'weight_class_0': 0.005017807156744258, 'weight_class_1': 0.06409026226543846, 'weight_class_2': 0.03873390695229664}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:52,742] Trial 1410 finished with value: 0.9495165561375649 and parameters: {'weight_class_0': 0.005200991348369505, 'weight_class_1': 0.0584642843171845, 'weight_class_2': 0.041314458813716}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:52,779] Trial 1409 finished with value: 0.949687003703726 and parameters: {'weight_class_0': 0.004779447191886571, 'weight_class_1': 0.060269757359391475, 'weight_class_2': 0.04154384149639299}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:52,780] Trial 1411 finished with value: 0.9494682260887707 and parameters: {'weight_class_0': 0.008157635794661826, 'weight_class_1': 0.07251960282841667, 'weight_class_2': 0.07299089908294353}. Best is trial 1341 with value: 0.9497202830040115.

Best trial: 1341. Best value: 0.94972:  47%|██████████████████████████████████████████████████████████████                                                                     | 1420/3000 [00:29<00:40, 38.99it/s]

[I 2026-07-03 10:56:52,806] Trial 1413 finished with value: 0.9494237435515936 and parameters: {'weight_class_0': 0.0072956457309213294, 'weight_class_1': 0.09308673970033997, 'weight_class_2': 0.055977730817724246}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:52,807] Trial 1412 finished with value: 0.9495693606878968 and parameters: {'weight_class_0': 0.007925422598664196, 'weight_class_1': 0.08819386741306486, 'weight_class_2': 0.0732378928882221}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:52,869] Trial 1415 finished with value: 0.9495764377956487 and parameters: {'weight_class_0': 0.006113339064425276, 'weight_class_1': 0.09293285248976735, 'weight_class_2': 0.055246482630952984}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:52,908] Trial 1414 finished with value: 0.9496227932832383 and parameters: {'weight_class_0': 0.006244265185444847, 'weight_class_1': 0.07481767710515169, 'weight_class_2': 0.06509343457083533}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:52,917] Trial 1416 finished with value: 0.949636202561419 and parameters: {'weight_class_0': 0.006254063868708493, 'weight_class_1': 0.09331269522891453, 'weight_class_2': 0.06849181653578067}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:52,939] Trial 1417 finished with value: 0.9496313407085522 and parameters: {'weight_class_0': 0.005954587717087428, 'weight_class_1': 0.08638583397501917, 'weight_class_2': 0.0705295701208268}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:52,982] Trial 1418 finished with value: 0.9482023602214488 and parameters: {'weight_class_0': 0.010857542209879664, 'weight_class_1': 0.0918550669623261, 'weight_class_2': 0.05709784657466376}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:52,997] Trial 1419 finished with value: 0.949620024976462 and parameters: {'weight_class_0': 0.006838005474847511, 'weight_class_1': 0.09700518775337527, 'weight_class_2': 0.07143747535652394}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:53,006] Trial 1420 finished with value: 0.9490838794214153 and parameters: {'weight_class_0': 0.008264317338554835, 'weight_class_1': 0.09244744664882011, 'weight_class_2': 0.05593951075499629}. Best is trial 1341 with value: 0.9497202830040115.

Best trial: 1341. Best value: 0.94972:  48%|██████████████████████████████████████████████████████████████▎                                                                    | 1428/3000 [00:29<00:40, 39.23it/s]

[I 2026-07-03 10:56:53,054] Trial 1421 finished with value: 0.9496781225220158 and parameters: {'weight_class_0': 0.006924870762423889, 'weight_class_1': 0.08870552721028394, 'weight_class_2': 0.06455129263863313}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:53,078] Trial 1423 finished with value: 0.9496443775796095 and parameters: {'weight_class_0': 0.006551211490498526, 'weight_class_1': 0.07881373637986416, 'weight_class_2': 0.07004769733132665}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:53,135] Trial 1424 finished with value: 0.9495068636652452 and parameters: {'weight_class_0': 0.0071799667874079985, 'weight_class_1': 0.07956378452910036, 'weight_class_2': 0.05763693489592616}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:53,135] Trial 1422 finished with value: 0.9487329589941925 and parameters: {'weight_class_0': 0.0062039115837232185, 'weight_class_1': 0.0810605587570622, 'weight_class_2': 0.1279498968138813}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:53,144] Trial 1425 finished with value: 0.9496977794270611 and parameters: {'weight_class_0': 0.00581250193589083, 'weight_class_1': 0.08392454403556689, 'weight_class_2': 0.06502758831859559}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:53,186] Trial 1426 finished with value: 0.9484160839258231 and parameters: {'weight_class_0': 0.010419884631588931, 'weight_class_1': 0.08031185897887941, 'weight_class_2': 0.06059898401971064}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:53,215] Trial 1427 finished with value: 0.9496601142198292 and parameters: {'weight_class_0': 0.006517706402085057, 'weight_class_1': 0.08305848684389394, 'weight_class_2': 0.06464743220084708}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:53,228] Trial 1428 finished with value: 0.9477907140566714 and parameters: {'weight_class_0': 0.011081764594066628, 'weight_class_1': 0.06608498609946858, 'weight_class_2': 0.06255223693071851}. Best is trial 1341 with value: 0.9497202830040115.

[I 2026-07-03 10:56:53,260] Trial 1429 finished with value: 0.9487847561297466 and parameters: {'weight_class_0': 0.006543196663491478, 'weight_class_1': 0.11899007379259209, 'weight_class_2': 0.13857201315530338}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:53,268] Trial 1430 finished with value: 0.9496478653034869 and parameters: {'weight_class_0': 0.006321603077210134, 'weight_class_1': 0.08010856680435759, 'weight_class_2': 0.06271107697382727}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:53,320] Trial 1431 finished with value: 0.9483961095738694 and parameters: {'weight_class_0': 0.010791625299537321, 'weight_class_1': 0.07774883242161218, 'weight_class_2': 0.06367331654203}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:53,326] Trial 1432 finished with value: 0.9495575924408638 and parameters: {'weight_class_0': 0.006562569011319486, 'weight_class_1': 0.1282967812167318, 'weight_class_2': 0.06593554918762491}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:53,332] Trial 1433 finished with value: 0.9490157858347086 and parameters: {'weight_class_0': 0.00905787077146107, 'weight_class_1': 0.07577889432034196, 'weight_class_2': 0.06376166004932987}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:53,371] Trial 1434 finished with value: 0.9488188341905576 and parameters: {'weight_class_0': 0.010147841103101863, 'weight_class_1': 0.11103698626154454, 'weight_class_2': 0.06206091009311121}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:53,388] Trial 1435 finished with value: 0.9496357081704226 and parameters: {'weight_class_0': 0.009332733249164966, 'weight_class_1': 0.11542409093088582, 'weight_class_2': 0.08447676507822435}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:53,439] Trial 1437 finished with value: 0.9494863100988004 and parameters: {'weight_class_0': 0.01082970411820059, 'weight_class_1': 0.09126418369563383, 'weight_class_2': 0.08890714449598623}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:53,454] Trial 1436 finished with value: 0.948992060038624 and parameters: {'weight_class_0': 0.006433354872899169, 'weight_class_1': 0.08272923582325165, 'weight_class_2': 0.11548212711407582}. Best is trial 1341 with value: 0.9497202830040115.

[I 2026-07-03 10:56:53,494] Trial 1438 finished with value: 0.9496280158031372 and parameters: {'weight_class_0': 0.009349479729835592, 'weight_class_1': 0.12770369567268477, 'weight_class_2': 0.07750200324458542}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:53,506] Trial 1439 finished with value: 0.9494082896992674 and parameters: {'weight_class_0': 0.00658149292664969, 'weight_class_1': 0.15385230307837333, 'weight_class_2': 0.08226095858780595}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:53,525] Trial 1440 finished with value: 0.9495007870380855 and parameters: {'weight_class_0': 0.008656703759891927, 'weight_class_1': 0.09153062540409966, 'weight_class_2': 0.08670555614699361}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:53,557] Trial 1441 finished with value: 0.9494044465847647 and parameters: {'weight_class_0': 0.008590072316280907, 'weight_class_1': 0.08743635424201457, 'weight_class_2': 0.11591562687699561}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:53,575] Trial 1442 finished with value: 0.9495656699625847 and parameters: {'weight_class_0': 0.008204409997830727, 'weight_class_1': 0.1787191411855037, 'weight_class_2': 0.09509202205379592}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:53,582] Trial 1443 finished with value: 0.9494561430728604 and parameters: {'weight_class_0': 0.007886333030824899, 'weight_class_1': 0.13464732073432092, 'weight_class_2': 0.1100006536838483}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:53,629] Trial 1444 finished with value: 0.9489304637665628 and parameters: {'weight_class_0': 0.005680440583964379, 'weight_class_1': 0.11873211157279093, 'weight_class_2': 0.11196509083844891}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:53,667] Trial 1445 finished with value: 0.9493492142228156 and parameters: {'weight_class_0': 0.005333400707300483, 'weight_class_1': 0.09402592460093595, 'weight_class_2': 0.08193179720054124}. Best is trial 1341 with value: 0.9497202830040115.

Best trial: 1341. Best value: 0.94972:  48%|███████████████████████████████████████████████████████████████▍                                                                   | 1454/3000 [00:30<00:38, 40.35it/s]

[I 2026-07-03 10:56:53,688] Trial 1446 finished with value: 0.9496123167600805 and parameters: {'weight_class_0': 0.007559966794687459, 'weight_class_1': 0.12238356449201776, 'weight_class_2': 0.09540098669097447}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:53,697] Trial 1447 finished with value: 0.9482475395116009 and parameters: {'weight_class_0': 0.007040187937504153, 'weight_class_1': 0.10447556692531852, 'weight_class_2': 0.18220290206327805}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:53,716] Trial 1448 finished with value: 0.9495411205421608 and parameters: {'weight_class_0': 0.008047175709716118, 'weight_class_1': 0.09430180918533643, 'weight_class_2': 0.10937645484409096}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:53,733] Trial 1449 finished with value: 0.9492487966962816 and parameters: {'weight_class_0': 0.0073423955593962, 'weight_class_1': 0.11963068125526896, 'weight_class_2': 0.05193548202409362}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:53,787] Trial 1450 finished with value: 0.9494668298294529 and parameters: {'weight_class_0': 0.007509155677848823, 'weight_class_1': 0.06997980147739448, 'weight_class_2': 0.0801601586431851}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:53,830] Trial 1451 finished with value: 0.9494750026937661 and parameters: {'weight_class_0': 0.005358364157505388, 'weight_class_1': 0.1067983645568297, 'weight_class_2': 0.07360473143835712}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:53,833] Trial 1452 finished with value: 0.9493633818926422 and parameters: {'weight_class_0': 0.005546488898040668, 'weight_class_1': 0.11647728237284936, 'weight_class_2': 0.08138774521375003}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:53,847] Trial 1453 finished with value: 0.9494262889885992 and parameters: {'weight_class_0': 0.005193991043115617, 'weight_class_1': 0.10148108737973487, 'weight_class_2': 0.07429943854835226}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:53,905] Trial 1455 finished with value: 0.9496380380666704 and parameters: {'weight_class_0': 0.0050590476657126505, 'weight_class_1': 0.07033095147739724, 'weight_class_2': 0.052923879465054884}. Best is trial 1341 with value: 0.9497202830040115.

Best trial: 1341. Best value: 0.94972:  49%|███████████████████████████████████████████████████████████████▊                                                                   | 1462/3000 [00:30<00:41, 37.51it/s]

[I 2026-07-03 10:56:53,935] Trial 1454 finished with value: 0.9495456560270199 and parameters: {'weight_class_0': 0.00501754770891933, 'weight_class_1': 0.10224201591120805, 'weight_class_2': 0.05700576260998322}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:53,944] Trial 1456 finished with value: 0.9472154695696338 and parameters: {'weight_class_0': 0.013858321296643938, 'weight_class_1': 0.07383146685387904, 'weight_class_2': 0.07446529870845488}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:53,974] Trial 1457 finished with value: 0.9496257668964576 and parameters: {'weight_class_0': 0.005202994990059376, 'weight_class_1': 0.06463403064150954, 'weight_class_2': 0.05174444566865723}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:53,996] Trial 1458 finished with value: 0.9496409938438798 and parameters: {'weight_class_0': 0.005114357649222743, 'weight_class_1': 0.06877407384728432, 'weight_class_2': 0.04776794528043022}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:54,024] Trial 1459 finished with value: 0.94963951903412 and parameters: {'weight_class_0': 0.005348302294728567, 'weight_class_1': 0.06878629722162155, 'weight_class_2': 0.04919063072033952}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:54,067] Trial 1460 finished with value: 0.9447800380709669 and parameters: {'weight_class_0': 0.012995952526176208, 'weight_class_1': 0.06828341886925603, 'weight_class_2': 0.048550240839990565}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:54,106] Trial 1462 finished with value: 0.9495916615384904 and parameters: {'weight_class_0': 0.004614031331866774, 'weight_class_1': 0.06765118373884946, 'weight_class_2': 0.048104190329959315}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:54,132] Trial 1461 finished with value: 0.949622763555601 and parameters: {'weight_class_0': 0.005109624457989136, 'weight_class_1': 0.07079878588175727, 'weight_class_2': 0.049016286966035626}. Best is trial 1341 with value: 0.9497202830040115.

Best trial: 1341. Best value: 0.94972:  49%|████████████████████████████████████████████████████████████████▏                                                                  | 1470/3000 [00:30<00:41, 37.31it/s]

[I 2026-07-03 10:56:54,152] Trial 1464 finished with value: 0.9496477794723055 and parameters: {'weight_class_0': 0.005214938179917258, 'weight_class_1': 0.06389676380882041, 'weight_class_2': 0.05062820227056681}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:54,169] Trial 1463 finished with value: 0.9495913174324171 and parameters: {'weight_class_0': 0.00520828888085327, 'weight_class_1': 0.07568583278243486, 'weight_class_2': 0.05034496520497197}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:54,199] Trial 1465 finished with value: 0.9496253426646807 and parameters: {'weight_class_0': 0.004878928703285512, 'weight_class_1': 0.06515266924524174, 'weight_class_2': 0.04677681595940841}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:54,220] Trial 1466 finished with value: 0.9496765927525068 and parameters: {'weight_class_0': 0.004961768510100586, 'weight_class_1': 0.06285409618469394, 'weight_class_2': 0.06131457410757803}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:54,237] Trial 1467 finished with value: 0.9496336401445543 and parameters: {'weight_class_0': 0.0050456159178916896, 'weight_class_1': 0.06892292568902506, 'weight_class_2': 0.04725018911734229}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:54,280] Trial 1468 finished with value: 0.9496142126916537 and parameters: {'weight_class_0': 0.0047363177840428145, 'weight_class_1': 0.06403609943273503, 'weight_class_2': 0.045756159321131716}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:54,300] Trial 1469 finished with value: 0.9496399447591076 and parameters: {'weight_class_0': 0.004799178611528066, 'weight_class_1': 0.05954591062234298, 'weight_class_2': 0.04741979140336235}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:54,337] Trial 1470 finished with value: 0.949620576486403 and parameters: {'weight_class_0': 0.004700620002685096, 'weight_class_1': 0.062096066515975115, 'weight_class_2': 0.06116083660180153}. Best is trial 1341 with value: 0.9497202830040115.

[I 2026-07-03 10:56:54,341] Trial 1471 finished with value: 0.9495547423250077 and parameters: {'weight_class_0': 0.0059192672125786975, 'weight_class_1': 0.075285749934697, 'weight_class_2': 0.046876428142557575}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:54,386] Trial 1472 finished with value: 0.9494672305530538 and parameters: {'weight_class_0': 0.006279662257929733, 'weight_class_1': 0.06024226661014022, 'weight_class_2': 0.06232079157615388}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:54,397] Trial 1473 finished with value: 0.949561546393657 and parameters: {'weight_class_0': 0.006304820222676753, 'weight_class_1': 0.0645266303022531, 'weight_class_2': 0.06210229789382429}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:54,462] Trial 1474 finished with value: 0.9494850102051888 and parameters: {'weight_class_0': 0.006408119501026473, 'weight_class_1': 0.057330518486079264, 'weight_class_2': 0.06252411768016815}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:54,473] Trial 1475 finished with value: 0.949455001274322 and parameters: {'weight_class_0': 0.006142147340410167, 'weight_class_1': 0.059472077794042046, 'weight_class_2': 0.06406409373950955}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:54,481] Trial 1476 finished with value: 0.9494289740958813 and parameters: {'weight_class_0': 0.0063870517230302055, 'weight_class_1': 0.060647125008056364, 'weight_class_2': 0.06457231624464872}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:54,517] Trial 1477 finished with value: 0.9493992167552014 and parameters: {'weight_class_0': 0.006930234058534253, 'weight_class_1': 0.05757254508326792, 'weight_class_2': 0.06561911751156851}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:54,583] Trial 1479 finished with value: 0.9494159055261662 and parameters: {'weight_class_0': 0.0062267425934453054, 'weight_class_1': 0.05362578485925224, 'weight_class_2': 0.0635222303763167}. Best is trial 1341 with value: 0.9497202830040115.

Best trial: 1341. Best value: 0.94972:  50%|████████████████████████████████████████████████████████████████▉                                                                  | 1487/3000 [00:30<00:39, 37.83it/s]

[I 2026-07-03 10:56:54,591] Trial 1478 finished with value: 0.9496152262279484 and parameters: {'weight_class_0': 0.00590394254674546, 'weight_class_1': 0.08123862505078917, 'weight_class_2': 0.06062226438668068}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:54,592] Trial 1480 finished with value: 0.9494565713677643 and parameters: {'weight_class_0': 0.0065515838761058525, 'weight_class_1': 0.05963312836906776, 'weight_class_2': 0.06261068582735112}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:54,622] Trial 1481 finished with value: 0.9493896325735268 and parameters: {'weight_class_0': 0.006589389960399495, 'weight_class_1': 0.055753347624547, 'weight_class_2': 0.06600127205003316}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:54,651] Trial 1482 finished with value: 0.9399638911814331 and parameters: {'weight_class_0': 0.018761317331962592, 'weight_class_1': 0.05566637994370165, 'weight_class_2': 0.06914879157458026}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:54,670] Trial 1483 finished with value: 0.9496538901421662 and parameters: {'weight_class_0': 0.007203837860565796, 'weight_class_1': 0.08575755657996491, 'weight_class_2': 0.06090483408714712}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:54,712] Trial 1484 finished with value: 0.9493681764288886 and parameters: {'weight_class_0': 0.004274360150693211, 'weight_class_1': 0.08684302240291783, 'weight_class_2': 0.06253637225259763}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:54,728] Trial 1485 finished with value: 0.9491990096742032 and parameters: {'weight_class_0': 0.00446304420301896, 'weight_class_1': 0.08073466640080583, 'weight_class_2': 0.0766895276974314}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:54,772] Trial 1486 finished with value: 0.949067500899602 and parameters: {'weight_class_0': 0.004253727856374409, 'weight_class_1': 0.08477511887404834, 'weight_class_2': 0.07590355774554922}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:54,773] Trial 1487 finished with value: 0.9492038085255134 and parameters: {'weight_class_0': 0.004426499119615775, 'weight_class_1': 0.08011778044129841, 'weight_class_2': 0.07625503449166963}. Best is trial 1341 with value: 0.9497202830040115.

Best trial: 1341. Best value: 0.94972:  50%|█████████████████████████████████████████████████████████████████▎                                                                 | 1495/3000 [00:31<00:38, 38.94it/s]

[I 2026-07-03 10:56:54,816] Trial 1489 finished with value: 0.7393413672833938 and parameters: {'weight_class_0': 6.488102131751209, 'weight_class_1': 0.08569336855503605, 'weight_class_2': 0.07816082082573506}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:54,816] Trial 1488 finished with value: 0.9494919752801249 and parameters: {'weight_class_0': 0.007440683505563239, 'weight_class_1': 0.15684995640445018, 'weight_class_2': 0.0742332473936732}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:54,871] Trial 1490 finished with value: 0.9494946777350318 and parameters: {'weight_class_0': 0.00416200561702057, 'weight_class_1': 0.08966985763274911, 'weight_class_2': 0.041130390485717205}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:54,888] Trial 1491 finished with value: 0.9495901587332093 and parameters: {'weight_class_0': 0.004380301616437886, 'weight_class_1': 0.08568152560849336, 'weight_class_2': 0.041633850670366464}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:54,906] Trial 1493 finished with value: 0.9487896870154561 and parameters: {'weight_class_0': 0.004047660249683101, 'weight_class_1': 0.14332442226492842, 'weight_class_2': 0.041027690636188496}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:54,918] Trial 1492 finished with value: 0.9495363028109809 and parameters: {'weight_class_0': 0.004045177927987728, 'weight_class_1': 0.07547117647629022, 'weight_class_2': 0.04236413958701613}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:54,985] Trial 1494 finished with value: 0.9496035298210543 and parameters: {'weight_class_0': 0.0042676202833003786, 'weight_class_1': 0.05093256581739908, 'weight_class_2': 0.04090293570737954}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:55,004] Trial 1496 finished with value: 0.949643536931524 and parameters: {'weight_class_0': 0.0041057556088321435, 'weight_class_1': 0.05234182621674727, 'weight_class_2': 0.04093782124769004}. Best is trial 1341 with value: 0.9497202830040115.

Best trial: 1341. Best value: 0.94972:  50%|█████████████████████████████████████████████████████████████████▋                                                                 | 1503/3000 [00:31<00:38, 38.55it/s]

[I 2026-07-03 10:56:55,010] Trial 1495 finished with value: 0.9493603200834526 and parameters: {'weight_class_0': 0.0038488729645706544, 'weight_class_1': 0.09856425856023052, 'weight_class_2': 0.04204340529664722}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:55,040] Trial 1497 finished with value: 0.9486244402707982 and parameters: {'weight_class_0': 0.0040589308724966015, 'weight_class_1': 0.15314219897448153, 'weight_class_2': 0.041643750444483194}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:55,056] Trial 1499 finished with value: 0.9171351022121662 and parameters: {'weight_class_0': 0.004670818280462363, 'weight_class_1': 0.004593347629307839, 'weight_class_2': 0.04227491462238353}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:55,066] Trial 1498 finished with value: 0.9494228017628119 and parameters: {'weight_class_0': 0.004398263941197439, 'weight_class_1': 0.10179471823692779, 'weight_class_2': 0.041807859942700656}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:55,125] Trial 1500 finished with value: 0.9496597644700491 and parameters: {'weight_class_0': 0.0042677682883237415, 'weight_class_1': 0.05273454977958311, 'weight_class_2': 0.041575676768948425}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:55,163] Trial 1502 finished with value: 0.949707667213742 and parameters: {'weight_class_0': 0.004376287101919926, 'weight_class_1': 0.05561551327458124, 'weight_class_2': 0.0479783973232236}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:55,179] Trial 1501 finished with value: 0.9496169324763012 and parameters: {'weight_class_0': 0.004300301237133227, 'weight_class_1': 0.0516546431297259, 'weight_class_2': 0.040918523888067555}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:55,194] Trial 1503 finished with value: 0.9495491498086519 and parameters: {'weight_class_0': 0.005352469098768132, 'weight_class_1': 0.0510077224022107, 'weight_class_2': 0.047023715900651505}. Best is trial 1341 with value: 0.9497202830040115.

Best trial: 1341. Best value: 0.94972:  50%|██████████████████████████████████████████████████████████████████                                                                 | 1512/3000 [00:31<00:37, 39.68it/s]

[I 2026-07-03 10:56:55,231] Trial 1504 finished with value: 0.9496232263507363 and parameters: {'weight_class_0': 0.004355231774834974, 'weight_class_1': 0.05104289121675464, 'weight_class_2': 0.04601533229382052}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:55,235] Trial 1505 finished with value: 0.9496144459936186 and parameters: {'weight_class_0': 0.004606773746572242, 'weight_class_1': 0.05297454735707804, 'weight_class_2': 0.04524435112353331}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:55,260] Trial 1507 finished with value: 0.9494465384847937 and parameters: {'weight_class_0': 0.004717075042054128, 'weight_class_1': 0.10526286129934019, 'weight_class_2': 0.049611850417697445}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:55,280] Trial 1506 finished with value: 0.9495367091782884 and parameters: {'weight_class_0': 0.005452969728512832, 'weight_class_1': 0.11021776997649163, 'weight_class_2': 0.04943112403501943}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:55,324] Trial 1508 finished with value: 0.9495494228274747 and parameters: {'weight_class_0': 0.005515201143291655, 'weight_class_1': 0.11234517044922895, 'weight_class_2': 0.05432283873296682}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:55,328] Trial 1509 finished with value: 0.949437508411436 and parameters: {'weight_class_0': 0.005477817226981937, 'weight_class_1': 0.053480231533082345, 'weight_class_2': 0.05528773104033887}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:55,355] Trial 1510 finished with value: 0.9475476095928433 and parameters: {'weight_class_0': 0.008867834676396872, 'weight_class_1': 0.04771937967031344, 'weight_class_2': 0.051696534257922526}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:55,375] Trial 1511 finished with value: 0.9494449454284796 and parameters: {'weight_class_0': 0.005214647864673198, 'weight_class_1': 0.04687832841673415, 'weight_class_2': 0.0523490702073635}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:55,421] Trial 1512 finished with value: 0.9487993510144443 and parameters: {'weight_class_0': 0.005871599254037038, 'weight_class_1': 0.2086832229696333, 'weight_class_2': 0.056447375263302804}. Best is trial 1341 with value: 0.9497202830040115.

[I 2026-07-03 10:56:55,468] Trial 1513 finished with value: 0.9496802446726941 and parameters: {'weight_class_0': 0.005487556109702214, 'weight_class_1': 0.0691565612350937, 'weight_class_2': 0.0538659488641234}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:55,472] Trial 1514 finished with value: 0.9496314565883268 and parameters: {'weight_class_0': 0.0052039306199739965, 'weight_class_1': 0.07061849706409472, 'weight_class_2': 0.05069442669826675}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:55,495] Trial 1515 finished with value: 0.9496318008999934 and parameters: {'weight_class_0': 0.0055132568811136805, 'weight_class_1': 0.06883871223328308, 'weight_class_2': 0.0563656974132635}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:55,524] Trial 1516 finished with value: 0.9496659221278024 and parameters: {'weight_class_0': 0.005742022856871355, 'weight_class_1': 0.06993058059861325, 'weight_class_2': 0.05399795543080276}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:55,576] Trial 1517 finished with value: 0.9496736359058394 and parameters: {'weight_class_0': 0.005560614600553645, 'weight_class_1': 0.07196330230001136, 'weight_class_2': 0.05393477263325439}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:55,582] Trial 1518 finished with value: 0.9492289163973119 and parameters: {'weight_class_0': 0.00775683222614922, 'weight_class_1': 0.06890638449144461, 'weight_class_2': 0.05768862891356308}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:55,599] Trial 1519 finished with value: 0.9495755412780715 and parameters: {'weight_class_0': 0.005680010779610595, 'weight_class_1': 0.06195853906690248, 'weight_class_2': 0.05458534974212569}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:55,601] Trial 1520 finished with value: 0.8208041020967479 and parameters: {'weight_class_0': 0.4095195502598088, 'weight_class_1': 0.05505988668303004, 'weight_class_2': 0.05377944538211332}. Best is trial 1341 with value: 0.9497202830040115.

Best trial: 1341. Best value: 0.94972:  51%|██████████████████████████████████████████████████████████████████▊                                                                | 1529/3000 [00:32<00:39, 37.62it/s]

[I 2026-07-03 10:56:55,671] Trial 1521 finished with value: 0.9490127234250978 and parameters: {'weight_class_0': 0.005601690483887783, 'weight_class_1': 0.0662217077876082, 'weight_class_2': 0.09884677341727384}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:55,692] Trial 1522 finished with value: 0.9494240017931738 and parameters: {'weight_class_0': 0.007048058675612458, 'weight_class_1': 0.07268419225281658, 'weight_class_2': 0.05540683594792568}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:55,709] Trial 1524 finished with value: 0.948976559164162 and parameters: {'weight_class_0': 0.007597685550112633, 'weight_class_1': 0.06547580151676333, 'weight_class_2': 0.052343922982849705}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:55,709] Trial 1523 finished with value: 0.949085733885726 and parameters: {'weight_class_0': 0.005720973614807882, 'weight_class_1': 0.06757549026515383, 'weight_class_2': 0.03793211796790303}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:55,795] Trial 1525 finished with value: 0.9493358458723159 and parameters: {'weight_class_0': 0.007353883719461349, 'weight_class_1': 0.059413775419994534, 'weight_class_2': 0.07298196483368957}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:55,804] Trial 1526 finished with value: 0.9494728677778914 and parameters: {'weight_class_0': 0.007412176390330804, 'weight_class_1': 0.07316912453487115, 'weight_class_2': 0.07631554351818534}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:55,817] Trial 1527 finished with value: 0.9494674861706601 and parameters: {'weight_class_0': 0.007663424445806979, 'weight_class_1': 0.07310877325646957, 'weight_class_2': 0.09227964150333864}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:55,845] Trial 1528 finished with value: 0.9493578624755834 and parameters: {'weight_class_0': 0.007253741790378171, 'weight_class_1': 0.071537503577005, 'weight_class_2': 0.09846462581441517}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:55,849] Trial 1529 finished with value: 0.9493430655397531 and parameters: {'weight_class_0': 0.006369179294569367, 'weight_class_1': 0.07035625618064528, 'weight_class_2': 0.09092434396424465}. Best is trial 1341 with value: 0.9497202830040115.

[I 2026-07-03 10:56:55,908] Trial 1531 finished with value: 0.9495200434251233 and parameters: {'weight_class_0': 0.0067707164567286275, 'weight_class_1': 0.07355512593305609, 'weight_class_2': 0.08547078924939189}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:55,921] Trial 1530 finished with value: 0.9495129246363359 and parameters: {'weight_class_0': 0.007561473475494289, 'weight_class_1': 0.07824742148846563, 'weight_class_2': 0.07751180179941128}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:55,942] Trial 1532 finished with value: 0.9494280739673893 and parameters: {'weight_class_0': 0.0069598136324225835, 'weight_class_1': 0.07334917227437125, 'weight_class_2': 0.09024920733752965}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:55,993] Trial 1533 finished with value: 0.9496064535091651 and parameters: {'weight_class_0': 0.00822670448223035, 'weight_class_1': 0.09171593311309413, 'weight_class_2': 0.08952943369212625}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:56,010] Trial 1535 finished with value: 0.9496596709879673 and parameters: {'weight_class_0': 0.007265745585398324, 'weight_class_1': 0.09395439327728916, 'weight_class_2': 0.07758348342291413}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:56,027] Trial 1534 finished with value: 0.9495297435483437 and parameters: {'weight_class_0': 0.0073063483137630674, 'weight_class_1': 0.07563106418302462, 'weight_class_2': 0.08073026349607453}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:56,066] Trial 1536 finished with value: 0.949564554329508 and parameters: {'weight_class_0': 0.008925040234498782, 'weight_class_1': 0.09825590657178923, 'weight_class_2': 0.078654909917279}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:56,068] Trial 1537 finished with value: 0.9494780816676628 and parameters: {'weight_class_0': 0.009057225117859379, 'weight_class_1': 0.09425781228120406, 'weight_class_2': 0.07297159059855003}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:56,106] Trial 1539 finished with value: 0.947083850552776 and parameters: {'weight_class_0': 0.009075032760330313, 'weight_class_1': 0.09481238734081138, 'weight_class_2': 0.03845168109181084}. Best is trial 1341 with value: 0.9497202830040115.

Best trial: 1341. Best value: 0.94972:  52%|███████████████████████████████████████████████████████████████████▌                                                               | 1546/3000 [00:32<00:39, 37.22it/s]

[I 2026-07-03 10:56:56,128] Trial 1538 finished with value: 0.94943301226556 and parameters: {'weight_class_0': 0.004884610858387266, 'weight_class_1': 0.09521173259613411, 'weight_class_2': 0.07211032028396956}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:56,162] Trial 1540 finished with value: 0.9494492319832988 and parameters: {'weight_class_0': 0.008849106764855709, 'weight_class_1': 0.08407618117119275, 'weight_class_2': 0.07152354279184528}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:56,211] Trial 1541 finished with value: 0.9494157908611968 and parameters: {'weight_class_0': 0.004869536417384743, 'weight_class_1': 0.08890854346455791, 'weight_class_2': 0.03756563536577862}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:56,249] Trial 1542 finished with value: 0.9494250125457793 and parameters: {'weight_class_0': 0.004874249141085205, 'weight_class_1': 0.1008299854925114, 'weight_class_2': 0.03813183083830842}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:56,250] Trial 1543 finished with value: 0.9495169055456433 and parameters: {'weight_class_0': 0.0045236947152520616, 'weight_class_1': 0.04551663002920826, 'weight_class_2': 0.037503220900470265}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:56,277] Trial 1544 finished with value: 0.9493247748961626 and parameters: {'weight_class_0': 0.004512669356523581, 'weight_class_1': 0.10905655910794271, 'weight_class_2': 0.03769548572918075}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:56,304] Trial 1545 finished with value: 0.9495788882727894 and parameters: {'weight_class_0': 0.004794728229097096, 'weight_class_1': 0.056788919689184154, 'weight_class_2': 0.06409760402694512}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:56,323] Trial 1546 finished with value: 0.9495216580181273 and parameters: {'weight_class_0': 0.004685802161565671, 'weight_class_1': 0.053145179372979176, 'weight_class_2': 0.03704065404640014}. Best is trial 1341 with value: 0.9497202830040115.

[I 2026-07-03 10:56:56,380] Trial 1547 finished with value: 0.9496192126655995 and parameters: {'weight_class_0': 0.004599429202036018, 'weight_class_1': 0.05620020619207469, 'weight_class_2': 0.04621185013542323}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:56,385] Trial 1549 finished with value: 0.949608265786171 and parameters: {'weight_class_0': 0.004561187740261245, 'weight_class_1': 0.05710403316826894, 'weight_class_2': 0.036856711398010576}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:56,388] Trial 1548 finished with value: 0.9496295740334117 and parameters: {'weight_class_0': 0.004495017252387726, 'weight_class_1': 0.05748833408151985, 'weight_class_2': 0.037172530577464835}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:56,399] Trial 1550 finished with value: 0.9496070694646681 and parameters: {'weight_class_0': 0.0040257639868056805, 'weight_class_1': 0.04634574972261805, 'weight_class_2': 0.03635830300404551}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:56,440] Trial 1551 finished with value: 0.9496259148117394 and parameters: {'weight_class_0': 0.004696041716846198, 'weight_class_1': 0.05601265187174464, 'weight_class_2': 0.04409734053144641}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:56,454] Trial 1552 finished with value: 0.9496767332760729 and parameters: {'weight_class_0': 0.0044326406242579585, 'weight_class_1': 0.0564584943679872, 'weight_class_2': 0.038214863071986106}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:56,474] Trial 1553 finished with value: 0.9496213765021655 and parameters: {'weight_class_0': 0.003882882326505644, 'weight_class_1': 0.05751787848094914, 'weight_class_2': 0.04704330518495905}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:56,507] Trial 1554 finished with value: 0.9496449215950385 and parameters: {'weight_class_0': 0.00465435406782328, 'weight_class_1': 0.057608399056968934, 'weight_class_2': 0.04583126136162333}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:56,541] Trial 1555 finished with value: 0.9495725464852917 and parameters: {'weight_class_0': 0.003814253680621043, 'weight_class_1': 0.05792623863832943, 'weight_class_2': 0.04758520881968786}. Best is trial 1341 with value: 0.9497202830040115.

Best trial: 1341. Best value: 0.94972:  52%|████████████████████████████████████████████████████████████████████▎                                                              | 1563/3000 [00:32<00:38, 37.25it/s]

[I 2026-07-03 10:56:56,561] Trial 1556 finished with value: 0.9496665763590192 and parameters: {'weight_class_0': 0.0040054262859154505, 'weight_class_1': 0.058389762239737616, 'weight_class_2': 0.045149344699456376}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:56,616] Trial 1557 finished with value: 0.9496735721847065 and parameters: {'weight_class_0': 0.003739404011715578, 'weight_class_1': 0.058598436858836804, 'weight_class_2': 0.04351009952581797}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:56,654] Trial 1558 finished with value: 0.9495922561039875 and parameters: {'weight_class_0': 0.0038581055972514225, 'weight_class_1': 0.0582208825819434, 'weight_class_2': 0.04612940747529289}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:56,664] Trial 1559 finished with value: 0.9495732540753982 and parameters: {'weight_class_0': 0.003906426303493204, 'weight_class_1': 0.043564065051830976, 'weight_class_2': 0.04675105480848812}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:56,709] Trial 1560 finished with value: 0.9496199056657679 and parameters: {'weight_class_0': 0.003689692357491261, 'weight_class_1': 0.04551357953511558, 'weight_class_2': 0.04601656416190418}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:56,721] Trial 1561 finished with value: 0.9495272958679242 and parameters: {'weight_class_0': 0.00405974995366879, 'weight_class_1': 0.04377940328660471, 'weight_class_2': 0.04869944174097681}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:56,766] Trial 1564 finished with value: 0.9491983776920044 and parameters: {'weight_class_0': 0.003680653323498108, 'weight_class_1': 0.04287420116854913, 'weight_class_2': 0.059197923202391825}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:56,768] Trial 1563 finished with value: 0.9492716933082338 and parameters: {'weight_class_0': 0.0038002268472983568, 'weight_class_1': 0.044890591312085, 'weight_class_2': 0.05989527100111697}. Best is trial 1341 with value: 0.9497202830040115.

Best trial: 1341. Best value: 0.94972:  52%|████████████████████████████████████████████████████████████████████▌                                                              | 1571/3000 [00:33<00:38, 37.17it/s]

[I 2026-07-03 10:56:56,783] Trial 1562 finished with value: 0.949356343759435 and parameters: {'weight_class_0': 0.0037728971847986923, 'weight_class_1': 0.0462389794113002, 'weight_class_2': 0.05819905164843643}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:56,802] Trial 1565 finished with value: 0.9493363609134619 and parameters: {'weight_class_0': 0.0036193571418994953, 'weight_class_1': 0.04687250072098613, 'weight_class_2': 0.05632839824807307}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:56,819] Trial 1566 finished with value: 0.7522566595268181 and parameters: {'weight_class_0': 0.005893321128623278, 'weight_class_1': 3.5946137333187616, 'weight_class_2': 0.057781559241983554}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:56,857] Trial 1567 finished with value: 0.9491640402400344 and parameters: {'weight_class_0': 0.006024266916054167, 'weight_class_1': 0.044724630175880735, 'weight_class_2': 0.06365149230301105}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:56,882] Trial 1568 finished with value: 0.9492828092463313 and parameters: {'weight_class_0': 0.00354416554333299, 'weight_class_1': 0.04474105678880987, 'weight_class_2': 0.057735229224458194}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:56,918] Trial 1569 finished with value: 0.9494102264305931 and parameters: {'weight_class_0': 0.005531138200125153, 'weight_class_1': 0.048055523829308375, 'weight_class_2': 0.06328672297686667}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:56,933] Trial 1570 finished with value: 0.949209529194007 and parameters: {'weight_class_0': 0.005993562878733892, 'weight_class_1': 0.045617767431102976, 'weight_class_2': 0.06001311302365107}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:56,975] Trial 1571 finished with value: 0.9493317352331524 and parameters: {'weight_class_0': 0.005385102831436139, 'weight_class_1': 0.04407771694658962, 'weight_class_2': 0.0618109552405426}. Best is trial 1341 with value: 0.9497202830040115.

Best trial: 1341. Best value: 0.94972:  53%|████████████████████████████████████████████████████████████████████▉                                                              | 1579/3000 [00:33<00:37, 37.68it/s]

[I 2026-07-03 10:56:56,991] Trial 1572 finished with value: 0.949292579729046 and parameters: {'weight_class_0': 0.006306171088702238, 'weight_class_1': 0.04664123603191478, 'weight_class_2': 0.05448458858096419}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:57,019] Trial 1573 finished with value: 0.9494197150916711 and parameters: {'weight_class_0': 0.005722121781066721, 'weight_class_1': 0.13496969391133276, 'weight_class_2': 0.06780977229804519}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:57,081] Trial 1574 finished with value: 0.9496299577848671 and parameters: {'weight_class_0': 0.006000762997313016, 'weight_class_1': 0.07936969115358959, 'weight_class_2': 0.0626523691886088}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:57,108] Trial 1576 finished with value: 0.949671934918466 and parameters: {'weight_class_0': 0.005542513517134612, 'weight_class_1': 0.07852355722779088, 'weight_class_2': 0.06473392781843992}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:57,119] Trial 1575 finished with value: 0.8010031857192579 and parameters: {'weight_class_0': 0.006035932134314015, 'weight_class_1': 0.12899596567285465, 'weight_class_2': 3.010642799418693}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:57,129] Trial 1577 finished with value: 0.9496261180984226 and parameters: {'weight_class_0': 0.005649320397789862, 'weight_class_1': 0.08286384741589331, 'weight_class_2': 0.06805131740148165}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:57,157] Trial 1578 finished with value: 0.9496655330207502 and parameters: {'weight_class_0': 0.005964577357604422, 'weight_class_1': 0.080914065807105, 'weight_class_2': 0.06599717509491054}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:57,201] Trial 1579 finished with value: 0.9496525481104549 and parameters: {'weight_class_0': 0.006197702799948787, 'weight_class_1': 0.08146155728971093, 'weight_class_2': 0.06719159077248874}. Best is trial 1341 with value: 0.9497202830040115.

Best trial: 1341. Best value: 0.94972:  53%|█████████████████████████████████████████████████████████████████████▎                                                             | 1587/3000 [00:33<00:37, 37.32it/s]

[I 2026-07-03 10:56:57,236] Trial 1580 finished with value: 0.949011817073352 and parameters: {'weight_class_0': 0.005911302032309184, 'weight_class_1': 0.07720395486809217, 'weight_class_2': 0.0382116434831503}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:57,251] Trial 1582 finished with value: 0.9494613108101441 and parameters: {'weight_class_0': 0.0057209186324386355, 'weight_class_1': 0.13096141682897638, 'weight_class_2': 0.07051619480004337}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:57,256] Trial 1581 finished with value: 0.9490395511092117 and parameters: {'weight_class_0': 0.0056693664666798765, 'weight_class_1': 0.08034326173237571, 'weight_class_2': 0.036941162112021135}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:57,282] Trial 1583 finished with value: 0.897628143404449 and parameters: {'weight_class_0': 0.005775054459968467, 'weight_class_1': 0.0025193754861689305, 'weight_class_2': 0.037707487318145876}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:57,357] Trial 1584 finished with value: 0.949261166712818 and parameters: {'weight_class_0': 0.003447773968064693, 'weight_class_1': 0.07944586428704084, 'weight_class_2': 0.04843628570319515}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:57,366] Trial 1585 finished with value: 0.9495668831693297 and parameters: {'weight_class_0': 0.0033833787671113075, 'weight_class_1': 0.06310006559329764, 'weight_class_2': 0.036615343067867914}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:57,374] Trial 1586 finished with value: 0.9487946517826259 and parameters: {'weight_class_0': 0.0032509798563862095, 'weight_class_1': 0.1189709431933537, 'weight_class_2': 0.03671486747454876}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:57,384] Trial 1587 finished with value: 0.9495962340809311 and parameters: {'weight_class_0': 0.0033601675345216763, 'weight_class_1': 0.06705365076816072, 'weight_class_2': 0.03875059775476909}. Best is trial 1341 with value: 0.9497202830040115.

Best trial: 1341. Best value: 0.94972:  53%|█████████████████████████████████████████████████████████████████████▋                                                             | 1595/3000 [00:33<00:38, 36.92it/s]

[I 2026-07-03 10:56:57,462] Trial 1588 finished with value: 0.9495541005047192 and parameters: {'weight_class_0': 0.003593821888393434, 'weight_class_1': 0.0646187249134725, 'weight_class_2': 0.03810556848055278}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:57,480] Trial 1589 finished with value: 0.9495755214604656 and parameters: {'weight_class_0': 0.0033255070224863974, 'weight_class_1': 0.06516052681701046, 'weight_class_2': 0.03699479647281377}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:57,484] Trial 1590 finished with value: 0.9495375059769042 and parameters: {'weight_class_0': 0.003325990361542686, 'weight_class_1': 0.059615317934813485, 'weight_class_2': 0.04525153318585684}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:57,553] Trial 1592 finished with value: 0.9493793235260627 and parameters: {'weight_class_0': 0.0033609128083659737, 'weight_class_1': 0.06191450085724488, 'weight_class_2': 0.05117953187016871}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:57,568] Trial 1593 finished with value: 0.949634608926489 and parameters: {'weight_class_0': 0.004701990448456013, 'weight_class_1': 0.06296715885265769, 'weight_class_2': 0.049995126069173806}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:57,570] Trial 1591 finished with value: 0.9495901383093986 and parameters: {'weight_class_0': 0.004524182630323498, 'weight_class_1': 0.06430010913265304, 'weight_class_2': 0.04530503742330058}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:57,612] Trial 1594 finished with value: 0.9494072489029213 and parameters: {'weight_class_0': 0.0033262452105280267, 'weight_class_1': 0.06592501646496515, 'weight_class_2': 0.0478128059181097}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:57,631] Trial 1595 finished with value: 0.9494477996871179 and parameters: {'weight_class_0': 0.0033110326293585113, 'weight_class_1': 0.06108348287907859, 'weight_class_2': 0.04701862267248822}. Best is trial 1341 with value: 0.9497202830040115.

Best trial: 1341. Best value: 0.94972:  53%|██████████████████████████████████████████████████████████████████████                                                             | 1604/3000 [00:34<00:36, 37.77it/s]

[I 2026-07-03 10:56:57,634] Trial 1596 finished with value: 0.9496422821006624 and parameters: {'weight_class_0': 0.004602103563231848, 'weight_class_1': 0.06277735676135046, 'weight_class_2': 0.048857332499058465}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:57,679] Trial 1597 finished with value: 0.9399458626978573 and parameters: {'weight_class_0': 0.016361148273246008, 'weight_class_1': 0.06286441312847872, 'weight_class_2': 0.04801332119888328}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:57,727] Trial 1599 finished with value: 0.9496349027498586 and parameters: {'weight_class_0': 0.004682432955716827, 'weight_class_1': 0.061854984328410974, 'weight_class_2': 0.047237783634358654}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:57,727] Trial 1598 finished with value: 0.9496586888086287 and parameters: {'weight_class_0': 0.004464102139385726, 'weight_class_1': 0.06557789470359209, 'weight_class_2': 0.0502860234153831}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:57,752] Trial 1600 finished with value: 0.9137946452324384 and parameters: {'weight_class_0': 0.004159751504912442, 'weight_class_1': 0.0036053196073443177, 'weight_class_2': 0.050852700261247524}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:57,787] Trial 1601 finished with value: 0.9484646936230283 and parameters: {'weight_class_0': 0.004600020411176542, 'weight_class_1': 0.05490182013099177, 'weight_class_2': 0.10250113908557497}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:57,815] Trial 1602 finished with value: 0.9496300522128646 and parameters: {'weight_class_0': 0.004807872600666829, 'weight_class_1': 0.055496760922675255, 'weight_class_2': 0.05096353712399648}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:57,857] Trial 1603 finished with value: 0.9460652222935982 and parameters: {'weight_class_0': 0.011131820335743836, 'weight_class_1': 0.051893243154876, 'weight_class_2': 0.05312665531791612}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:57,873] Trial 1605 finished with value: 0.8736871479999202 and parameters: {'weight_class_0': 1.7289753561130037, 'weight_class_1': 7.792327681926763, 'weight_class_2': 0.05443231751432448}. Best is trial 1341 with value: 0.9497202830040115.

[I 2026-07-03 10:56:57,887] Trial 1604 finished with value: 0.9495030512547457 and parameters: {'weight_class_0': 0.004813280319249267, 'weight_class_1': 0.05011447039320198, 'weight_class_2': 0.05251292721594367}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:57,919] Trial 1606 finished with value: 0.9495461400301748 and parameters: {'weight_class_0': 0.0047557865960844055, 'weight_class_1': 0.04840576013715985, 'weight_class_2': 0.05420266067577018}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:57,930] Trial 1607 finished with value: 0.9481661420537342 and parameters: {'weight_class_0': 0.004808340704858731, 'weight_class_1': 0.044811597595258934, 'weight_class_2': 0.10518493474313854}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:57,985] Trial 1608 finished with value: 0.9481192048613317 and parameters: {'weight_class_0': 0.010119753374213475, 'weight_class_1': 0.0512417375041039, 'weight_class_2': 0.09517080858383509}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:58,015] Trial 1609 finished with value: 0.9496435264380244 and parameters: {'weight_class_0': 0.004061515970847532, 'weight_class_1': 0.04870337342154981, 'weight_class_2': 0.03580046741283881}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:58,026] Trial 1610 finished with value: 0.9480255086001782 and parameters: {'weight_class_0': 0.010022687179906078, 'weight_class_1': 0.05020542670255523, 'weight_class_2': 0.09888090246713876}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:58,043] Trial 1611 finished with value: 0.9492536985960124 and parameters: {'weight_class_0': 0.006801041163538142, 'weight_class_1': 0.05090273161081149, 'weight_class_2': 0.05704608071275805}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:58,082] Trial 1612 finished with value: 0.9486321637131182 and parameters: {'weight_class_0': 0.00402054958630595, 'weight_class_1': 0.04323578565718322, 'weight_class_2': 0.07880474728304218}. Best is trial 1341 with value: 0.9497202830040115.

Best trial: 1341. Best value: 0.94972:  54%|██████████████████████████████████████████████████████████████████████▋                                                            | 1620/3000 [00:34<00:36, 37.72it/s]

[I 2026-07-03 10:56:58,101] Trial 1613 finished with value: 0.9454792346819207 and parameters: {'weight_class_0': 0.011162523824196982, 'weight_class_1': 0.045624646181008054, 'weight_class_2': 0.05624201555805366}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:58,117] Trial 1614 finished with value: 0.9496010805856532 and parameters: {'weight_class_0': 0.004036783318797974, 'weight_class_1': 0.046803506309416223, 'weight_class_2': 0.03580434025174729}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:58,139] Trial 1615 finished with value: 0.876600702806064 and parameters: {'weight_class_0': 0.040188623451558984, 'weight_class_1': 0.04299855779281313, 'weight_class_2': 0.03490282054043814}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:58,151] Trial 1616 finished with value: 0.7900820861318306 and parameters: {'weight_class_0': 4.0349121600477655, 'weight_class_1': 0.6866208405126846, 'weight_class_2': 0.03405079527157311}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:58,222] Trial 1617 finished with value: 0.9475998088834375 and parameters: {'weight_class_0': 0.006751224705009793, 'weight_class_1': 0.04235503622765636, 'weight_class_2': 0.035603988596599224}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:58,234] Trial 1618 finished with value: 0.9486179539616447 and parameters: {'weight_class_0': 0.0068115390778965895, 'weight_class_1': 0.041056742797585775, 'weight_class_2': 0.0788330196285788}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:58,260] Trial 1619 finished with value: 0.7051868403396834 and parameters: {'weight_class_0': 4.1114146443332675, 'weight_class_1': 0.04592728896435122, 'weight_class_2': 0.03600687032009882}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:58,281] Trial 1620 finished with value: 0.949525353988991 and parameters: {'weight_class_0': 0.003897456708559837, 'weight_class_1': 0.042156318646833404, 'weight_class_2': 0.03600528850152161}. Best is trial 1341 with value: 0.9497202830040115.

Best trial: 1341. Best value: 0.94972:  54%|███████████████████████████████████████████████████████████████████████▏                                                           | 1629/3000 [00:34<00:35, 38.46it/s]

[I 2026-07-03 10:56:58,351] Trial 1621 finished with value: 0.9486212581055292 and parameters: {'weight_class_0': 0.0038439182258022428, 'weight_class_1': 0.1049731854361338, 'weight_class_2': 0.07794896359286838}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:58,386] Trial 1622 finished with value: 0.9485451211388064 and parameters: {'weight_class_0': 0.006807528716330387, 'weight_class_1': 0.10481864425081837, 'weight_class_2': 0.03730938921382244}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:58,404] Trial 1624 finished with value: 0.9472365381308808 and parameters: {'weight_class_0': 0.007112271135594974, 'weight_class_1': 0.04050275891498376, 'weight_class_2': 0.03637741728238465}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:58,407] Trial 1623 finished with value: 0.9482734884775086 and parameters: {'weight_class_0': 0.007054783464213365, 'weight_class_1': 0.10660663291722086, 'weight_class_2': 0.03633066827222836}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:58,426] Trial 1625 finished with value: 0.9496252167976761 and parameters: {'weight_class_0': 0.006670317713565721, 'weight_class_1': 0.10808121414802603, 'weight_class_2': 0.07302235697304045}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:58,475] Trial 1626 finished with value: 0.949569067506905 and parameters: {'weight_class_0': 0.007029962667406553, 'weight_class_1': 0.11622130017458329, 'weight_class_2': 0.07359610982797377}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:58,503] Trial 1627 finished with value: 0.9492294014564878 and parameters: {'weight_class_0': 0.0033576888232788008, 'weight_class_1': 0.0943677712948617, 'weight_class_2': 0.043894395592480366}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:58,514] Trial 1628 finished with value: 0.9490477955390513 and parameters: {'weight_class_0': 0.0033486853958038182, 'weight_class_1': 0.10868029328137467, 'weight_class_2': 0.04303102429946261}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:58,520] Trial 1629 finished with value: 0.9491227509016728 and parameters: {'weight_class_0': 0.0032864309741289094, 'weight_class_1': 0.10175671424728179, 'weight_class_2': 0.04252725946162361}. Best is trial 1341 with value: 0.9497202830040115.

[I 2026-07-03 10:56:58,566] Trial 1631 finished with value: 0.9492628849194215 and parameters: {'weight_class_0': 0.0032295538059580343, 'weight_class_1': 0.08821329572862352, 'weight_class_2': 0.04289819005299311}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:58,590] Trial 1630 finished with value: 0.9492230550122246 and parameters: {'weight_class_0': 0.003380177438206041, 'weight_class_1': 0.09729952109561861, 'weight_class_2': 0.042460678970760606}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:58,622] Trial 1632 finished with value: 0.9486321681604976 and parameters: {'weight_class_0': 0.007896852586726288, 'weight_class_1': 0.09448875164312497, 'weight_class_2': 0.043662877140405155}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:58,677] Trial 1633 finished with value: 0.9492556474290063 and parameters: {'weight_class_0': 0.0032651767416142174, 'weight_class_1': 0.09026809871674386, 'weight_class_2': 0.04437148290665274}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:58,695] Trial 1635 finished with value: 0.9493404697148516 and parameters: {'weight_class_0': 0.003237271664677398, 'weight_class_1': 0.07603366396467544, 'weight_class_2': 0.04327700689721315}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:58,722] Trial 1634 finished with value: 0.9493490553743884 and parameters: {'weight_class_0': 0.0032387565567593988, 'weight_class_1': 0.07581304038542529, 'weight_class_2': 0.042393047292558876}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:58,742] Trial 1636 finished with value: 0.949300420807984 and parameters: {'weight_class_0': 0.003282792406141986, 'weight_class_1': 0.08517319007621084, 'weight_class_2': 0.04331365625769386}. Best is trial 1341 with value: 0.9497202830040115.

Best trial: 1341. Best value: 0.94972:  55%|███████████████████████████████████████████████████████████████████████▊                                                           | 1644/3000 [00:35<00:35, 38.61it/s]

[I 2026-07-03 10:56:58,761] Trial 1637 finished with value: 0.9493497357092956 and parameters: {'weight_class_0': 0.0031560809551344463, 'weight_class_1': 0.07333486280039433, 'weight_class_2': 0.043126544265377126}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:58,767] Trial 1638 finished with value: 0.9493438700733116 and parameters: {'weight_class_0': 0.0032230846174864857, 'weight_class_1': 0.08016259018731019, 'weight_class_2': 0.04328022819123877}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:58,811] Trial 1640 finished with value: 0.9496573713381923 and parameters: {'weight_class_0': 0.005219068136816594, 'weight_class_1': 0.07358251789296145, 'weight_class_2': 0.044200471088055235}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:58,828] Trial 1639 finished with value: 0.9496672373236804 and parameters: {'weight_class_0': 0.005171824087972992, 'weight_class_1': 0.07275495921174976, 'weight_class_2': 0.06334587578983729}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:58,846] Trial 1641 finished with value: 0.8828942697261208 and parameters: {'weight_class_0': 0.06669542751010052, 'weight_class_1': 0.07594610262844888, 'weight_class_2': 0.06630400316970825}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:58,910] Trial 1642 finished with value: 0.9495988883915842 and parameters: {'weight_class_0': 0.005215108793727554, 'weight_class_1': 0.07796869888850987, 'weight_class_2': 0.055024974591332806}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:58,925] Trial 1643 finished with value: 0.9495855028194589 and parameters: {'weight_class_0': 0.004995329018688593, 'weight_class_1': 0.07585597228552135, 'weight_class_2': 0.06293377141365582}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:58,942] Trial 1644 finished with value: 0.9496360519270804 and parameters: {'weight_class_0': 0.005142832529020409, 'weight_class_1': 0.07724864432298054, 'weight_class_2': 0.06023944480681128}. Best is trial 1341 with value: 0.9497202830040115.

Best trial: 1341. Best value: 0.94972:  55%|████████████████████████████████████████████████████████████████████████▏                                                          | 1652/3000 [00:35<00:38, 35.23it/s]

[I 2026-07-03 10:56:58,963] Trial 1645 finished with value: 0.9495244186614366 and parameters: {'weight_class_0': 0.005610256335152563, 'weight_class_1': 0.055357258515533976, 'weight_class_2': 0.0612690790589385}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:58,984] Trial 1646 finished with value: 0.9494292684129544 and parameters: {'weight_class_0': 0.0051243175578895295, 'weight_class_1': 0.05416953787340056, 'weight_class_2': 0.06713466988895492}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:59,051] Trial 1648 finished with value: 0.9495426909439931 and parameters: {'weight_class_0': 0.0052176185745055215, 'weight_class_1': 0.05450354829481726, 'weight_class_2': 0.06022262475443741}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:59,065] Trial 1647 finished with value: 0.9492870724449761 and parameters: {'weight_class_0': 0.0041063208998655815, 'weight_class_1': 0.05455798724226865, 'weight_class_2': 0.06808756057124228}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:59,070] Trial 1649 finished with value: 0.9495221097521878 and parameters: {'weight_class_0': 0.005140532301614681, 'weight_class_1': 0.05280556583297856, 'weight_class_2': 0.062041613499582614}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:59,111] Trial 1651 finished with value: 0.7360056570058989 and parameters: {'weight_class_0': 0.0051360019546296985, 'weight_class_1': 0.05475942142152325, 'weight_class_2': 3.8145397115353696}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:59,120] Trial 1650 finished with value: 0.9492019483996117 and parameters: {'weight_class_0': 0.005119689819044293, 'weight_class_1': 0.040741633396213936, 'weight_class_2': 0.06280748269368115}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:59,185] Trial 1652 finished with value: 0.8259052325769876 and parameters: {'weight_class_0': 0.3052544127754933, 'weight_class_1': 0.05419303219908, 'weight_class_2': 0.06346090206615035}. Best is trial 1341 with value: 0.9497202830040115.

[I 2026-07-03 10:56:59,190] Trial 1653 finished with value: 0.9472294837764862 and parameters: {'weight_class_0': 0.00418757468120378, 'weight_class_1': 0.05453430475197077, 'weight_class_2': 0.1591939567629106}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:59,205] Trial 1654 finished with value: 0.9494330962285172 and parameters: {'weight_class_0': 0.004005445965208748, 'weight_class_1': 0.052605173150441845, 'weight_class_2': 0.05987925904702297}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:59,255] Trial 1655 finished with value: 0.9475778080896379 and parameters: {'weight_class_0': 0.0042711394022901675, 'weight_class_1': 0.05882322052334429, 'weight_class_2': 0.14152120915294425}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:59,304] Trial 1656 finished with value: 0.9494949244705736 and parameters: {'weight_class_0': 0.004158686154666822, 'weight_class_1': 0.043141083509954645, 'weight_class_2': 0.033902306622585816}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:59,306] Trial 1657 finished with value: 0.7739418226350008 and parameters: {'weight_class_0': 2.764066699366223, 'weight_class_1': 0.05479667056328471, 'weight_class_2': 0.03420158064476868}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:59,339] Trial 1658 finished with value: 0.9484705707804785 and parameters: {'weight_class_0': 0.0041495937225366104, 'weight_class_1': 0.0408396348262523, 'weight_class_2': 0.08378734092222595}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:59,367] Trial 1659 finished with value: 0.9482158661031813 and parameters: {'weight_class_0': 0.004110773417276359, 'weight_class_1': 0.03916569435270701, 'weight_class_2': 0.08896679974070074}. Best is trial 1341 with value: 0.9497202830040115.

Best trial: 1341. Best value: 0.94972:  56%|████████████████████████████████████████████████████████████████████████▉                                                          | 1669/3000 [00:35<00:36, 36.72it/s]

[I 2026-07-03 10:56:59,414] Trial 1660 finished with value: 0.7043613060264896 and parameters: {'weight_class_0': 0.0040458192562383664, 'weight_class_1': 4.675618006422628, 'weight_class_2': 0.12458766472904526}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:59,447] Trial 1661 finished with value: 0.9484960731491686 and parameters: {'weight_class_0': 0.004273324142800751, 'weight_class_1': 0.04146231678784228, 'weight_class_2': 0.08284009796461379}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:59,454] Trial 1662 finished with value: 0.9484641294637196 and parameters: {'weight_class_0': 0.004034589626615596, 'weight_class_1': 0.0402269621721943, 'weight_class_2': 0.08233930726326942}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:59,488] Trial 1664 finished with value: 0.9452384108741604 and parameters: {'weight_class_0': 0.008431235358606471, 'weight_class_1': 0.04229554945156717, 'weight_class_2': 0.034200225797447616}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:59,491] Trial 1663 finished with value: 0.9483745986450905 and parameters: {'weight_class_0': 0.003987451098427797, 'weight_class_1': 0.03871634347739002, 'weight_class_2': 0.08142716696509524}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:59,529] Trial 1666 finished with value: 0.9494922705377954 and parameters: {'weight_class_0': 0.004064805960503456, 'weight_class_1': 0.04007734583483328, 'weight_class_2': 0.03377757823820717}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:59,539] Trial 1665 finished with value: 0.9474940287438454 and parameters: {'weight_class_0': 0.008974622214315397, 'weight_class_1': 0.04052721144702486, 'weight_class_2': 0.08022148141914166}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:59,557] Trial 1667 finished with value: 0.9495128397636362 and parameters: {'weight_class_0': 0.004061625473042722, 'weight_class_1': 0.041807754112676405, 'weight_class_2': 0.035745060320335184}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:59,606] Trial 1668 finished with value: 0.9476180341606829 and parameters: {'weight_class_0': 0.008137695738894078, 'weight_class_1': 0.04178224675537851, 'weight_class_2': 0.05275543137106559}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:59,624] Trial 1670 finished with value: 0.7874748341840488 and parameters: {'weight_class_0': 0.0038579600770284133, 'weight_class_1': 0.04033620292980142, 'weight_class_2': 2.0255402578901727}. Best is trial 1341 with value: 0.9497202830040115.

Best trial: 1341. Best value: 0.94972:  56%|█████████████████████████████████████████████████████████████████████████▏                                                         | 1676/3000 [00:35<00:36, 36.20it/s]

[I 2026-07-03 10:56:59,647] Trial 1669 finished with value: 0.9470127333103875 and parameters: {'weight_class_0': 0.008567370784554827, 'weight_class_1': 0.03960481646428893, 'weight_class_2': 0.05267560855351154}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:59,709] Trial 1671 finished with value: 0.9472930020910596 and parameters: {'weight_class_0': 0.008614867366116956, 'weight_class_1': 0.04124048201874822, 'weight_class_2': 0.055877983966292157}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:59,733] Trial 1672 finished with value: 0.9495686305432436 and parameters: {'weight_class_0': 0.006107162612023185, 'weight_class_1': 0.06676651546935725, 'weight_class_2': 0.050638334688638376}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:59,759] Trial 1673 finished with value: 0.8885674736414094 and parameters: {'weight_class_0': 0.005970433253339023, 'weight_class_1': 0.001601781392723045, 'weight_class_2': 0.05238782402500967}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:59,775] Trial 1674 finished with value: 0.9494566459984358 and parameters: {'weight_class_0': 0.006003687749410216, 'weight_class_1': 0.06670401239545376, 'weight_class_2': 0.04682180512197693}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:59,834] Trial 1675 finished with value: 0.9495629934829736 and parameters: {'weight_class_0': 0.006420895575634098, 'weight_class_1': 0.06976306160978994, 'weight_class_2': 0.056627157965192604}. Best is trial 1341 with value: 0.9497202830040115.

[I 2026-07-03 10:56:59,876] Trial 1676 finished with value: 0.8417448002561998 and parameters: {'weight_class_0': 0.1711387594805306, 'weight_class_1': 0.06961775491255366, 'weight_class_2': 0.05332786116718104}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:59,912] Trial 1677 finished with value: 0.9495776525240638 and parameters: {'weight_class_0': 0.005760405713575148, 'weight_class_1': 0.06401450829238886, 'weight_class_2': 0.055199009411212634}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:59,914] Trial 1678 finished with value: 0.8346305794966047 and parameters: {'weight_class_0': 0.21750264221158733, 'weight_class_1': 0.06743940088333779, 'weight_class_2': 0.05154715233134421}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:59,930] Trial 1680 finished with value: 0.9495611627039727 and parameters: {'weight_class_0': 0.0062614778439324765, 'weight_class_1': 0.06743991351256481, 'weight_class_2': 0.054703100145420056}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:59,941] Trial 1679 finished with value: 0.949643872078334 and parameters: {'weight_class_0': 0.0059543921087963, 'weight_class_1': 0.06785828240718524, 'weight_class_2': 0.05137515360497168}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:59,963] Trial 1682 finished with value: 0.8399564118163321 and parameters: {'weight_class_0': 0.17472519938932016, 'weight_class_1': 0.06611290591242328, 'weight_class_2': 0.05262629398063936}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:59,975] Trial 1681 finished with value: 0.9491487465744828 and parameters: {'weight_class_0': 0.0030273879580717112, 'weight_class_1': 0.05902386235344418, 'weight_class_2': 0.05276858751303483}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:56:59,993] Trial 1683 finished with value: 0.946802114356982 and parameters: {'weight_class_0': 0.003118810034204067, 'weight_class_1': 0.17579205830842237, 'weight_class_2': 0.03455921865697604}. Best is trial 1341 with value: 0.9497202830040115.

Best trial: 1341. Best value: 0.94972:  56%|█████████████████████████████████████████████████████████████████████████▊                                                         | 1691/3000 [00:36<00:34, 37.53it/s]

[I 2026-07-03 10:57:00,040] Trial 1684 finished with value: 0.9494745437691964 and parameters: {'weight_class_0': 0.0031809994441270835, 'weight_class_1': 0.06615204692723171, 'weight_class_2': 0.041701697089610267}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:57:00,062] Trial 1685 finished with value: 0.949541414917678 and parameters: {'weight_class_0': 0.0032493414364262647, 'weight_class_1': 0.06567261538932213, 'weight_class_2': 0.03486881513678983}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:57:00,075] Trial 1686 finished with value: 0.9495590206946631 and parameters: {'weight_class_0': 0.0031803510438060617, 'weight_class_1': 0.06618853678334548, 'weight_class_2': 0.03492410370368941}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:57:00,118] Trial 1688 finished with value: 0.949570922341377 and parameters: {'weight_class_0': 0.0032423135960039377, 'weight_class_1': 0.05694872091178409, 'weight_class_2': 0.0354409652915773}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:57:00,139] Trial 1687 finished with value: 0.9495960382603005 and parameters: {'weight_class_0': 0.0032457794071714344, 'weight_class_1': 0.060196644023916605, 'weight_class_2': 0.035514620434120396}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:57:00,179] Trial 1689 finished with value: 0.9495972501384027 and parameters: {'weight_class_0': 0.0032134848813068287, 'weight_class_1': 0.051768292279380984, 'weight_class_2': 0.03484801350941369}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:57:00,215] Trial 1690 finished with value: 0.9496334439334828 and parameters: {'weight_class_0': 0.003070808344945382, 'weight_class_1': 0.04995116216315731, 'weight_class_2': 0.037635547366753744}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:57:00,263] Trial 1692 finished with value: 0.9496926809441067 and parameters: {'weight_class_0': 0.003413658994904586, 'weight_class_1': 0.045164880462157095, 'weight_class_2': 0.03881938376162367}. Best is trial 1341 with value: 0.9497202830040115.

Best trial: 1341. Best value: 0.94972:  57%|██████████████████████████████████████████████████████████████████████████▏                                                        | 1699/3000 [00:36<00:35, 36.79it/s]

[I 2026-07-03 10:57:00,274] Trial 1691 finished with value: 0.9496296861535969 and parameters: {'weight_class_0': 0.0033542537395189645, 'weight_class_1': 0.04548675499318272, 'weight_class_2': 0.034637103084980775}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:57:00,303] Trial 1693 finished with value: 0.9495948180271488 and parameters: {'weight_class_0': 0.003422671916393197, 'weight_class_1': 0.04969454850822876, 'weight_class_2': 0.0353199863718894}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:57:00,328] Trial 1694 finished with value: 0.9492688638753733 and parameters: {'weight_class_0': 0.004781663672436802, 'weight_class_1': 0.05074853316759257, 'weight_class_2': 0.03563946042716052}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:57:00,350] Trial 1695 finished with value: 0.9494991139685692 and parameters: {'weight_class_0': 0.004977251113527486, 'weight_class_1': 0.05207331864454449, 'weight_class_2': 0.040349066621062885}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:57:00,394] Trial 1696 finished with value: 0.9493989123452403 and parameters: {'weight_class_0': 0.005071589647898937, 'weight_class_1': 0.08734474473151352, 'weight_class_2': 0.03912697180038085}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:57:00,407] Trial 1697 finished with value: 0.9495394419109889 and parameters: {'weight_class_0': 0.004827364684234073, 'weight_class_1': 0.04716390322776996, 'weight_class_2': 0.04186359454333698}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:57:00,454] Trial 1699 finished with value: 0.9494189110228911 and parameters: {'weight_class_0': 0.00507156514628948, 'weight_class_1': 0.04895590989456526, 'weight_class_2': 0.040671112114116684}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:57:00,455] Trial 1698 finished with value: 0.9495497375171623 and parameters: {'weight_class_0': 0.0048900521729358225, 'weight_class_1': 0.04977190615333124, 'weight_class_2': 0.043204156428071266}. Best is trial 1341 with value: 0.9497202830040115.

Best trial: 1707. Best value: 0.949732:  57%|█████████████████████████████████████████████████████████████████████████▉                                                        | 1707/3000 [00:36<00:34, 37.16it/s]

[I 2026-07-03 10:57:00,464] Trial 1700 finished with value: 0.949124782801318 and parameters: {'weight_class_0': 0.004921766974293122, 'weight_class_1': 0.04785645213872631, 'weight_class_2': 0.07331661192365349}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:57:00,500] Trial 1702 finished with value: 0.9319765738032625 and parameters: {'weight_class_0': 0.004867857774572625, 'weight_class_1': 0.5582999265657446, 'weight_class_2': 0.07428655580618301}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:57:00,548] Trial 1701 finished with value: 0.9278921587120091 and parameters: {'weight_class_0': 0.004698069384978956, 'weight_class_1': 0.04847846944051118, 'weight_class_2': 0.728748635140461}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:57:00,558] Trial 1703 finished with value: 0.9496838342906214 and parameters: {'weight_class_0': 0.003795961250179761, 'weight_class_1': 0.04955447490066378, 'weight_class_2': 0.04208505091650081}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:57:00,606] Trial 1704 finished with value: 0.9497092523213407 and parameters: {'weight_class_0': 0.0037623042102876447, 'weight_class_1': 0.047131324941259115, 'weight_class_2': 0.041525808442455125}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:57:00,624] Trial 1706 finished with value: 0.9497104603906487 and parameters: {'weight_class_0': 0.0036035096929238784, 'weight_class_1': 0.046349704291690365, 'weight_class_2': 0.041617610094471374}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:57:00,644] Trial 1705 finished with value: 0.9211732955190509 and parameters: {'weight_class_0': 0.0037389441351931506, 'weight_class_1': 0.5331798922750064, 'weight_class_2': 0.04326668213302976}. Best is trial 1341 with value: 0.9497202830040115.
[I 2026-07-03 10:57:00,672] Trial 1707 finished with value: 0.9497320734687417 and parameters: {'weight_class_0': 0.003767539416890682, 'weight_class_1': 0.04648112158370834, 'weight_class_2': 0.04375789898174255}. Best is trial 1707 with value: 0.9497320734687417.

Best trial: 1707. Best value: 0.949732:  57%|██████████████████████████████████████████████████████████████████████████▎                                                       | 1714/3000 [00:37<00:35, 36.28it/s]

[I 2026-07-03 10:57:00,714] Trial 1708 finished with value: 0.9496488202353399 and parameters: {'weight_class_0': 0.0038057292675444288, 'weight_class_1': 0.04351790087042233, 'weight_class_2': 0.03288405170967513}. Best is trial 1707 with value: 0.9497320734687417.
[I 2026-07-03 10:57:00,720] Trial 1709 finished with value: 0.9495884731866067 and parameters: {'weight_class_0': 0.0035695321749601443, 'weight_class_1': 0.03884955806567747, 'weight_class_2': 0.031157619312492193}. Best is trial 1707 with value: 0.9497320734687417.
[I 2026-07-03 10:57:00,734] Trial 1710 finished with value: 0.9495277352702461 and parameters: {'weight_class_0': 0.0035563099506253433, 'weight_class_1': 0.03842951287791079, 'weight_class_2': 0.0325383729534231}. Best is trial 1707 with value: 0.9497320734687417.
[I 2026-07-03 10:57:00,794] Trial 1711 finished with value: 0.9495328192120015 and parameters: {'weight_class_0': 0.0036417874335378485, 'weight_class_1': 0.03867562984180359, 'weight_class_2': 0.03161541804475177}. Best is trial 1707 with value: 0.9497320734687417.
[I 2026-07-03 10:57:00,804] Trial 1712 finished with value: 0.6616044843344976 and parameters: {'weight_class_0': 0.0035198530872363673, 'weight_class_1': 0.0392437487816055, 'weight_class_2': 5.48865830716231}. Best is trial 1707 with value: 0.9497320734687417.
[I 2026-07-03 10:57:00,889] Trial 1713 finished with value: 0.9495420610481778 and parameters: {'weight_class_0': 0.003627969778522208, 'weight_class_1': 0.03765872731533979, 'weight_class_2': 0.031346813618504527}. Best is trial 1707 with value: 0.9497320734687417.
[I 2026-07-03 10:57:00,892] Trial 1714 finished with value: 0.9495440857308459 and parameters: {'weight_class_0': 0.0037465399427373852, 'weight_class_1': 0.04090159961851511, 'weight_class_2': 0.045704326362826155}. Best is trial 1707 with value: 0.9497320734687417.

Best trial: 1707. Best value: 0.949732:  57%|██████████████████████████████████████████████████████████████████████████▌                                                       | 1721/3000 [00:37<00:36, 34.60it/s]

[I 2026-07-03 10:57:00,906] Trial 1715 finished with value: 0.9495363808913263 and parameters: {'weight_class_0': 0.0038357829696590144, 'weight_class_1': 0.03968183403441641, 'weight_class_2': 0.043312021126057906}. Best is trial 1707 with value: 0.9497320734687417.
[I 2026-07-03 10:57:00,939] Trial 1716 finished with value: 0.9006412207579889 and parameters: {'weight_class_0': 0.0037059623852826523, 'weight_class_1': 0.04249566958019015, 'weight_class_2': 0.002364413384535952}. Best is trial 1707 with value: 0.9497320734687417.
[I 2026-07-03 10:57:00,986] Trial 1717 finished with value: 0.9494935352738357 and parameters: {'weight_class_0': 0.003922695176643429, 'weight_class_1': 0.03851895247096632, 'weight_class_2': 0.0418316323654847}. Best is trial 1707 with value: 0.9497320734687417.
[I 2026-07-03 10:57:00,996] Trial 1718 finished with value: 0.9496671854734289 and parameters: {'weight_class_0': 0.0037949384387705527, 'weight_class_1': 0.04445588196677593, 'weight_class_2': 0.043759804184690956}. Best is trial 1707 with value: 0.9497320734687417.
[I 2026-07-03 10:57:01,017] Trial 1719 finished with value: 0.9495771736409274 and parameters: {'weight_class_0': 0.0038153547715625963, 'weight_class_1': 0.04276281294094476, 'weight_class_2': 0.04499908056316497}. Best is trial 1707 with value: 0.9497320734687417.
[I 2026-07-03 10:57:01,041] Trial 1720 finished with value: 0.9497002247585851 and parameters: {'weight_class_0': 0.003919410340696165, 'weight_class_1': 0.049446272213789895, 'weight_class_2': 0.04441515454621109}. Best is trial 1707 with value: 0.9497320734687417.
[I 2026-07-03 10:57:01,067] Trial 1721 finished with value: 0.9496713869991599 and parameters: {'weight_class_0': 0.0037794038436869625, 'weight_class_1': 0.04479103613805073, 'weight_class_2': 0.0444990168515543}. Best is trial 1707 with value: 0.9497320734687417.

[I 2026-07-03 10:57:01,143] Trial 1724 finished with value: 0.9496097875094861 and parameters: {'weight_class_0': 0.004134285022141284, 'weight_class_1': 0.0472359961922713, 'weight_class_2': 0.042216820765801896}. Best is trial 1707 with value: 0.9497320734687417.
[I 2026-07-03 10:57:01,156] Trial 1723 finished with value: 0.9496311799919009 and parameters: {'weight_class_0': 0.004087571650571109, 'weight_class_1': 0.04855123703516562, 'weight_class_2': 0.04270969452827165}. Best is trial 1707 with value: 0.9497320734687417.
[I 2026-07-03 10:57:01,160] Trial 1722 finished with value: 0.9496767753605811 and parameters: {'weight_class_0': 0.003939223406030537, 'weight_class_1': 0.047398514472029606, 'weight_class_2': 0.04603425470520851}. Best is trial 1707 with value: 0.9497320734687417.
[I 2026-07-03 10:57:01,216] Trial 1725 finished with value: 0.8125308453147682 and parameters: {'weight_class_0': 0.6493968893423471, 'weight_class_1': 0.052547411751661006, 'weight_class_2': 0.043976883402297925}. Best is trial 1707 with value: 0.9497320734687417.
[I 2026-07-03 10:57:01,225] Trial 1727 finished with value: 0.9442057298592617 and parameters: {'weight_class_0': 0.004030428672354725, 'weight_class_1': 0.04942421785939798, 'weight_class_2': 0.3114598690544446}. Best is trial 1707 with value: 0.9497320734687417.
[I 2026-07-03 10:57:01,231] Trial 1726 finished with value: 0.9496417290849447 and parameters: {'weight_class_0': 0.004236000016268731, 'weight_class_1': 0.05264369167619544, 'weight_class_2': 0.04498454393678602}. Best is trial 1707 with value: 0.9497320734687417.
[I 2026-07-03 10:57:01,271] Trial 1728 finished with value: 0.9496825825900034 and parameters: {'weight_class_0': 0.004183035369218109, 'weight_class_1': 0.05336548058681385, 'weight_class_2': 0.04568067504707501}. Best is trial 1707 with value: 0.9497320734687417.
[I 2026-07-03 10:57:01,279] Trial 1729 finished with value: 0.9449504892909308 and parameters: {'weight_class_0': 0.0045711660191092955, 'weight_class_1': 0.05463543973633741, 'weight_class_2': 0.3163866036033118}. Best is trial 1707 with value: 0.9497320734687417.

Best trial: 1707. Best value: 0.949732:  58%|███████████████████████████████████████████████████████████████████████████▎                                                      | 1737/3000 [00:37<00:36, 35.03it/s]

[I 2026-07-03 10:57:01,353] Trial 1731 finished with value: 0.9497244526588031 and parameters: {'weight_class_0': 0.004345245213831795, 'weight_class_1': 0.055147249788520876, 'weight_class_2': 0.048802826329434244}. Best is trial 1707 with value: 0.9497320734687417.
[I 2026-07-03 10:57:01,383] Trial 1730 finished with value: 0.9496873473242754 and parameters: {'weight_class_0': 0.004450914610649123, 'weight_class_1': 0.05227469783296271, 'weight_class_2': 0.050255214402081735}. Best is trial 1707 with value: 0.9497320734687417.
[I 2026-07-03 10:57:01,388] Trial 1732 finished with value: 0.9496067198794559 and parameters: {'weight_class_0': 0.004553483521373909, 'weight_class_1': 0.05253520589995197, 'weight_class_2': 0.044820102974039766}. Best is trial 1707 with value: 0.9497320734687417.
[I 2026-07-03 10:57:01,430] Trial 1733 finished with value: 0.9496650815699471 and parameters: {'weight_class_0': 0.004314950088011777, 'weight_class_1': 0.049237863149600165, 'weight_class_2': 0.0473038295165635}. Best is trial 1707 with value: 0.9497320734687417.
[I 2026-07-03 10:57:01,495] Trial 1735 finished with value: 0.9496825824872066 and parameters: {'weight_class_0': 0.004342586131496741, 'weight_class_1': 0.05718376779760829, 'weight_class_2': 0.04822718749336749}. Best is trial 1707 with value: 0.9497320734687417.
[I 2026-07-03 10:57:01,497] Trial 1734 finished with value: 0.9496716471499896 and parameters: {'weight_class_0': 0.0045011540472881155, 'weight_class_1': 0.05771419644101283, 'weight_class_2': 0.04903606863361289}. Best is trial 1707 with value: 0.9497320734687417.
[I 2026-07-03 10:57:01,530] Trial 1736 finished with value: 0.9496684831132276 and parameters: {'weight_class_0': 0.0041983415959144085, 'weight_class_1': 0.057123760734244036, 'weight_class_2': 0.050932014105351545}. Best is trial 1707 with value: 0.9497320734687417.
[I 2026-07-03 10:57:01,539] Trial 1737 finished with value: 0.9497005264591941 and parameters: {'weight_class_0': 0.004492923730864057, 'weight_class_1': 0.057348904914980556, 'weight_class_2': 0.054461108751492265}. Best is trial 1707 with value: 0.9497320734687417.

[I 2026-07-03 10:57:01,570] Trial 1738 finished with value: 0.9489895026409725 and parameters: {'weight_class_0': 0.003011807388017174, 'weight_class_1': 0.05753292799272724, 'weight_class_2': 0.056664256016687925}. Best is trial 1707 with value: 0.9497320734687417.
[I 2026-07-03 10:57:01,614] Trial 1740 finished with value: 0.9496477830344809 and parameters: {'weight_class_0': 0.004711032504272702, 'weight_class_1': 0.056152011846893175, 'weight_class_2': 0.051068210705008776}. Best is trial 1707 with value: 0.9497320734687417.
[I 2026-07-03 10:57:01,616] Trial 1739 finished with value: 0.9496939890851187 and parameters: {'weight_class_0': 0.0044168254994685335, 'weight_class_1': 0.052253044218579285, 'weight_class_2': 0.05050441885475612}. Best is trial 1707 with value: 0.9497320734687417.
[I 2026-07-03 10:57:01,659] Trial 1741 finished with value: 0.9497368888684448 and parameters: {'weight_class_0': 0.0046211977363148785, 'weight_class_1': 0.05696724052571766, 'weight_class_2': 0.05329217237247829}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:01,674] Trial 1743 finished with value: 0.9496646778932368 and parameters: {'weight_class_0': 0.004521657939619046, 'weight_class_1': 0.061921599437236755, 'weight_class_2': 0.05038044391739168}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:01,683] Trial 1742 finished with value: 0.9496029331947718 and parameters: {'weight_class_0': 0.004512760048850696, 'weight_class_1': 0.05783583786937684, 'weight_class_2': 0.05839645652532947}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:01,755] Trial 1744 finished with value: 0.9497163375814104 and parameters: {'weight_class_0': 0.004799780387820473, 'weight_class_1': 0.0598264957765443, 'weight_class_2': 0.054397693385646664}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  58%|███████████████████████████████████████████████████████████████████████████▉                                                      | 1752/3000 [00:38<00:35, 35.64it/s]

[I 2026-07-03 10:57:01,757] Trial 1745 finished with value: 0.9496959749780897 and parameters: {'weight_class_0': 0.004660638170457908, 'weight_class_1': 0.05924514061643539, 'weight_class_2': 0.05674651837548633}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:01,828] Trial 1746 finished with value: 0.9496745388643643 and parameters: {'weight_class_0': 0.004783780055861724, 'weight_class_1': 0.05854436851623638, 'weight_class_2': 0.05853169827256666}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:01,830] Trial 1747 finished with value: 0.9496182873585869 and parameters: {'weight_class_0': 0.004696699258059699, 'weight_class_1': 0.05981313189980682, 'weight_class_2': 0.06024298640823701}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:01,854] Trial 1748 finished with value: 0.9496443976901778 and parameters: {'weight_class_0': 0.004927279880563213, 'weight_class_1': 0.05842140463644652, 'weight_class_2': 0.058411468697434146}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:01,874] Trial 1749 finished with value: 0.9495545485815216 and parameters: {'weight_class_0': 0.00481292117036484, 'weight_class_1': 0.05716419730945855, 'weight_class_2': 0.06309739943248102}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:01,908] Trial 1750 finished with value: 0.9495402525027675 and parameters: {'weight_class_0': 0.004688307019340687, 'weight_class_1': 0.0635789456307905, 'weight_class_2': 0.06429658984793463}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:01,944] Trial 1751 finished with value: 0.9495680403009898 and parameters: {'weight_class_0': 0.005188217533849164, 'weight_class_1': 0.05935344395101322, 'weight_class_2': 0.06195429331533101}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:01,953] Trial 1752 finished with value: 0.9495478107633618 and parameters: {'weight_class_0': 0.005556994611986522, 'weight_class_1': 0.060831254792742956, 'weight_class_2': 0.06770420921285406}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  59%|████████████████████████████████████████████████████████████████████████████▎                                                     | 1761/3000 [00:38<00:33, 37.18it/s]

[I 2026-07-03 10:57:01,960] Trial 1753 finished with value: 0.9496286199731369 and parameters: {'weight_class_0': 0.005446950027916287, 'weight_class_1': 0.06262352273919124, 'weight_class_2': 0.0639639810173777}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:02,039] Trial 1754 finished with value: 0.9495952075945925 and parameters: {'weight_class_0': 0.005488392254819072, 'weight_class_1': 0.0626902651114546, 'weight_class_2': 0.06481514303149494}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:02,046] Trial 1755 finished with value: 0.9495503938791153 and parameters: {'weight_class_0': 0.005449314405629128, 'weight_class_1': 0.06364403096607481, 'weight_class_2': 0.07084564383252978}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:02,082] Trial 1756 finished with value: 0.9495899277294098 and parameters: {'weight_class_0': 0.005478287853943189, 'weight_class_1': 0.061829882364250265, 'weight_class_2': 0.06550347525007402}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:02,098] Trial 1757 finished with value: 0.949572490792934 and parameters: {'weight_class_0': 0.005748016940428899, 'weight_class_1': 0.0665252483930381, 'weight_class_2': 0.07171745865182587}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:02,134] Trial 1759 finished with value: 0.9496700714128408 and parameters: {'weight_class_0': 0.005224747419381759, 'weight_class_1': 0.06932591542224671, 'weight_class_2': 0.06657101568516617}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:02,155] Trial 1758 finished with value: 0.9496391010710091 and parameters: {'weight_class_0': 0.005613637242239881, 'weight_class_1': 0.06883789188427622, 'weight_class_2': 0.07052348403311438}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:02,196] Trial 1761 finished with value: 0.9496539726249447 and parameters: {'weight_class_0': 0.005708837603605705, 'weight_class_1': 0.07003979702173527, 'weight_class_2': 0.0704126721229989}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:02,197] Trial 1760 finished with value: 0.9495745099882837 and parameters: {'weight_class_0': 0.005534599179036974, 'weight_class_1': 0.06561997477653422, 'weight_class_2': 0.0692675311291307}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  59%|████████████████████████████████████████████████████████████████████████████▋                                                     | 1770/3000 [00:38<00:30, 40.00it/s]

[I 2026-07-03 10:57:02,216] Trial 1762 finished with value: 0.9494499046470256 and parameters: {'weight_class_0': 0.0058054526278621486, 'weight_class_1': 0.06942679108472277, 'weight_class_2': 0.08202422344810541}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:02,282] Trial 1763 finished with value: 0.9496625114611564 and parameters: {'weight_class_0': 0.005852923682150363, 'weight_class_1': 0.07178176941522312, 'weight_class_2': 0.07027879916447238}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:02,289] Trial 1764 finished with value: 0.9496838058790611 and parameters: {'weight_class_0': 0.005816843115790246, 'weight_class_1': 0.07530367266459843, 'weight_class_2': 0.07146140236214847}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:02,321] Trial 1765 finished with value: 0.9495413175886375 and parameters: {'weight_class_0': 0.005829608767703077, 'weight_class_1': 0.07316624605111641, 'weight_class_2': 0.08097242657154737}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:02,350] Trial 1766 finished with value: 0.9495868015156835 and parameters: {'weight_class_0': 0.00599208736123209, 'weight_class_1': 0.06743725642826874, 'weight_class_2': 0.07363250370372437}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:02,378] Trial 1768 finished with value: 0.9497009549442638 and parameters: {'weight_class_0': 0.006301820293098143, 'weight_class_1': 0.07542101851355851, 'weight_class_2': 0.06976089844024555}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:02,390] Trial 1767 finished with value: 0.9496998857078977 and parameters: {'weight_class_0': 0.00634826829351015, 'weight_class_1': 0.07951483339810536, 'weight_class_2': 0.07767436416049839}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:02,391] Trial 1769 finished with value: 0.9495682992877446 and parameters: {'weight_class_0': 0.005641080652523853, 'weight_class_1': 0.07141399813209272, 'weight_class_2': 0.07471098622150765}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:02,427] Trial 1770 finished with value: 0.9496431862850333 and parameters: {'weight_class_0': 0.005915201479265734, 'weight_class_1': 0.07724956159211657, 'weight_class_2': 0.07544447416759623}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  59%|█████████████████████████████████████████████████████████████████████████████                                                     | 1778/3000 [00:38<00:30, 39.53it/s]

[I 2026-07-03 10:57:02,450] Trial 1771 finished with value: 0.9496387741918796 and parameters: {'weight_class_0': 0.006628171193517506, 'weight_class_1': 0.07616729515215126, 'weight_class_2': 0.07691910267226743}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:02,497] Trial 1772 finished with value: 0.9495263467491979 and parameters: {'weight_class_0': 0.004311740778733371, 'weight_class_1': 0.08355805689412481, 'weight_class_2': 0.056951463933428446}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:02,517] Trial 1773 finished with value: 0.9486610671159577 and parameters: {'weight_class_0': 0.004204144877333812, 'weight_class_1': 0.08156357460059316, 'weight_class_2': 0.09552838978275502}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:02,530] Trial 1774 finished with value: 0.9496014512529473 and parameters: {'weight_class_0': 0.004321375649565275, 'weight_class_1': 0.07875409196538986, 'weight_class_2': 0.050877072640527266}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:02,566] Trial 1775 finished with value: 0.9484001988032126 and parameters: {'weight_class_0': 0.004157016476719795, 'weight_class_1': 0.04990806900150385, 'weight_class_2': 0.09550865623041223}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:02,617] Trial 1777 finished with value: 0.9495603628117525 and parameters: {'weight_class_0': 0.004366492569519022, 'weight_class_1': 0.04762887853211946, 'weight_class_2': 0.05168263079594089}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:02,618] Trial 1776 finished with value: 0.9494821676017292 and parameters: {'weight_class_0': 0.004104201265904013, 'weight_class_1': 0.051708577518475435, 'weight_class_2': 0.05882615812525479}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:02,655] Trial 1778 finished with value: 0.9495784987338048 and parameters: {'weight_class_0': 0.004142375759314608, 'weight_class_1': 0.05135775944612822, 'weight_class_2': 0.05383210987066957}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:02,657] Trial 1779 finished with value: 0.9497094424364936 and parameters: {'weight_class_0': 0.007212205841310266, 'weight_class_1': 0.08863895196237126, 'weight_class_2': 0.07946228593264645}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:02,666] Trial 1780 finished with value: 0.9496367016863795 and parameters: {'weight_class_0': 0.007600387380883235, 'weight_class_1': 0.08631075844313015, 'weight_class_2': 0.08258334437466497}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:02,716] Trial 1782 finished with value: 0.9496313749568465 and parameters: {'weight_class_0': 0.007424705891696462, 'weight_class_1': 0.0914965161922442, 'weight_class_2': 0.09346824474295}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:02,731] Trial 1781 finished with value: 0.9494898424747066 and parameters: {'weight_class_0': 0.006993081943955458, 'weight_class_1': 0.08726592796005407, 'weight_class_2': 0.10035118498612072}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:02,752] Trial 1783 finished with value: 0.9496378392470525 and parameters: {'weight_class_0': 0.007515107051720171, 'weight_class_1': 0.0847419406844723, 'weight_class_2': 0.08719487462803646}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:02,781] Trial 1784 finished with value: 0.9497215347046296 and parameters: {'weight_class_0': 0.007507922506062199, 'weight_class_1': 0.0927891247942083, 'weight_class_2': 0.08760179362008655}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:02,783] Trial 1785 finished with value: 0.9494651900671677 and parameters: {'weight_class_0': 0.007331812635890066, 'weight_class_1': 0.08947810056508095, 'weight_class_2': 0.056670970400646406}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:02,829] Trial 1787 finished with value: 0.949664927846391 and parameters: {'weight_class_0': 0.007796113888576261, 'weight_class_1': 0.08831908488203334, 'weight_class_2': 0.08620247725729512}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:02,843] Trial 1786 finished with value: 0.9494082174536645 and parameters: {'weight_class_0': 0.007467296086282597, 'weight_class_1': 0.08706366958145809, 'weight_class_2': 0.10703787296679407}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  60%|█████████████████████████████████████████████████████████████████████████████▊                                                    | 1795/3000 [00:39<00:31, 38.32it/s]

[I 2026-07-03 10:57:02,883] Trial 1788 finished with value: 0.9492745958037524 and parameters: {'weight_class_0': 0.007510849873750154, 'weight_class_1': 0.07678061553837617, 'weight_class_2': 0.10565439286107614}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:02,907] Trial 1789 finished with value: 0.9495786125320484 and parameters: {'weight_class_0': 0.00854480283850729, 'weight_class_1': 0.0959661000497222, 'weight_class_2': 0.10780094539144916}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:02,968] Trial 1791 finished with value: 0.9494810515135791 and parameters: {'weight_class_0': 0.007350502258817445, 'weight_class_1': 0.12051203925960187, 'weight_class_2': 0.10192488759927254}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:02,982] Trial 1790 finished with value: 0.9496248214378512 and parameters: {'weight_class_0': 0.00818320674138282, 'weight_class_1': 0.11652881599185093, 'weight_class_2': 0.10823726324229174}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:03,011] Trial 1792 finished with value: 0.9495010427584886 and parameters: {'weight_class_0': 0.010503662016362155, 'weight_class_1': 0.10822446577504874, 'weight_class_2': 0.12501346278060552}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:03,026] Trial 1793 finished with value: 0.9496134745259389 and parameters: {'weight_class_0': 0.00972907257425855, 'weight_class_1': 0.13910493991310333, 'weight_class_2': 0.08732204348222394}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:03,051] Trial 1794 finished with value: 0.9496396108666031 and parameters: {'weight_class_0': 0.008668926330624063, 'weight_class_1': 0.10462616732059622, 'weight_class_2': 0.10473878507465725}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:03,068] Trial 1795 finished with value: 0.9494751769752502 and parameters: {'weight_class_0': 0.012133603715811821, 'weight_class_1': 0.13241270731133167, 'weight_class_2': 0.16267583207274627}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  60%|██████████████████████████████████████████████████████████████████████████████▏                                                   | 1805/3000 [00:39<00:30, 38.91it/s]

[I 2026-07-03 10:57:03,090] Trial 1797 finished with value: 0.9495966250465023 and parameters: {'weight_class_0': 0.010162192273062892, 'weight_class_1': 0.11965637441408994, 'weight_class_2': 0.12370704043234809}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:03,099] Trial 1796 finished with value: 0.9495807172294439 and parameters: {'weight_class_0': 0.01085212422828177, 'weight_class_1': 0.12045130837646376, 'weight_class_2': 0.1131701815817332}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:03,137] Trial 1799 finished with value: 0.949652207258167 and parameters: {'weight_class_0': 0.008020851960391116, 'weight_class_1': 0.1123718314940017, 'weight_class_2': 0.09477614627776695}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:03,163] Trial 1798 finished with value: 0.949663376218305 and parameters: {'weight_class_0': 0.010480646767706566, 'weight_class_1': 0.12836921736923834, 'weight_class_2': 0.09575556164409642}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:03,208] Trial 1800 finished with value: 0.9496081031448428 and parameters: {'weight_class_0': 0.008764543009220227, 'weight_class_1': 0.12957561391292882, 'weight_class_2': 0.09437160989143895}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:03,224] Trial 1801 finished with value: 0.94954923895539 and parameters: {'weight_class_0': 0.010394980363091739, 'weight_class_1': 0.11273415290530599, 'weight_class_2': 0.12308019750575867}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:03,268] Trial 1802 finished with value: 0.9492898533263171 and parameters: {'weight_class_0': 0.013498254149507033, 'weight_class_1': 0.12974436559125618, 'weight_class_2': 0.10436502552064159}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:03,280] Trial 1803 finished with value: 0.9492679387073304 and parameters: {'weight_class_0': 0.015072558215518546, 'weight_class_1': 0.10895316179976108, 'weight_class_2': 0.12918888690537855}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:03,298] Trial 1804 finished with value: 0.9496517836021444 and parameters: {'weight_class_0': 0.009352733395255278, 'weight_class_1': 0.12890158708248234, 'weight_class_2': 0.11058082327702883}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  60%|██████████████████████████████████████████████████████████████████████████████▌                                                   | 1813/3000 [00:39<00:30, 38.44it/s]

[I 2026-07-03 10:57:03,345] Trial 1805 finished with value: 0.9493392084897909 and parameters: {'weight_class_0': 0.014150070910166793, 'weight_class_1': 0.11368393384227989, 'weight_class_2': 0.1166984608481551}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:03,362] Trial 1806 finished with value: 0.9495685977963392 and parameters: {'weight_class_0': 0.008909414264188302, 'weight_class_1': 0.11628073580328066, 'weight_class_2': 0.1207087967701645}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:03,372] Trial 1807 finished with value: 0.9488301691678261 and parameters: {'weight_class_0': 0.01573592171677259, 'weight_class_1': 0.10001288534983944, 'weight_class_2': 0.1452326029176979}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:03,425] Trial 1809 finished with value: 0.9493499771302663 and parameters: {'weight_class_0': 0.00926539720900162, 'weight_class_1': 0.1059884741675543, 'weight_class_2': 0.13899376492516433}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:03,429] Trial 1808 finished with value: 0.9495726493455373 and parameters: {'weight_class_0': 0.009554597236477788, 'weight_class_1': 0.10422341855261308, 'weight_class_2': 0.10795433197613426}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:03,448] Trial 1810 finished with value: 0.9495736582424849 and parameters: {'weight_class_0': 0.010092362747984545, 'weight_class_1': 0.15364059807299904, 'weight_class_2': 0.09012170516972123}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:03,468] Trial 1811 finished with value: 0.949069694861494 and parameters: {'weight_class_0': 0.011877806286957091, 'weight_class_1': 0.1026207780395667, 'weight_class_2': 0.08466671958121633}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:03,518] Trial 1812 finished with value: 0.9494089789726924 and parameters: {'weight_class_0': 0.006814634050683349, 'weight_class_1': 0.15788700681108572, 'weight_class_2': 0.08519394033719088}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:03,543] Trial 1813 finished with value: 0.9495760569359972 and parameters: {'weight_class_0': 0.00909471767359287, 'weight_class_1': 0.15019271791110525, 'weight_class_2': 0.11648998504037689}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  61%|██████████████████████████████████████████████████████████████████████████████▉                                                   | 1821/3000 [00:39<00:29, 40.27it/s]

[I 2026-07-03 10:57:03,556] Trial 1814 finished with value: 0.9489336179806628 and parameters: {'weight_class_0': 0.007058017095251441, 'weight_class_1': 0.16792363751451128, 'weight_class_2': 0.12480188248797305}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:03,574] Trial 1815 finished with value: 0.9492739184239453 and parameters: {'weight_class_0': 0.006661670858199867, 'weight_class_1': 0.1789333757851025, 'weight_class_2': 0.08972641602870012}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:03,621] Trial 1816 finished with value: 0.9496227038078301 and parameters: {'weight_class_0': 0.006893384185393685, 'weight_class_1': 0.09919634904363851, 'weight_class_2': 0.08368360214821353}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:03,627] Trial 1817 finished with value: 0.9495619131619262 and parameters: {'weight_class_0': 0.007322007392389594, 'weight_class_1': 0.1557332054963608, 'weight_class_2': 0.08093506574862916}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:03,654] Trial 1818 finished with value: 0.9496499599600609 and parameters: {'weight_class_0': 0.006743373460613501, 'weight_class_1': 0.09707778262047034, 'weight_class_2': 0.07689008024272528}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:03,670] Trial 1819 finished with value: 0.9495699136910482 and parameters: {'weight_class_0': 0.007671961505172614, 'weight_class_1': 0.0841700790120445, 'weight_class_2': 0.09046756178160542}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:03,700] Trial 1820 finished with value: 0.9496167062576619 and parameters: {'weight_class_0': 0.006301286842660011, 'weight_class_1': 0.09058465396834285, 'weight_class_2': 0.08599501224790378}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:03,754] Trial 1821 finished with value: 0.9496637537502992 and parameters: {'weight_class_0': 0.006420979307099753, 'weight_class_1': 0.08503956530522053, 'weight_class_2': 0.07716062480521159}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  61%|███████████████████████████████████████████████████████████████████████████████▎                                                  | 1830/3000 [00:40<00:30, 38.86it/s]

[I 2026-07-03 10:57:03,764] Trial 1822 finished with value: 0.9497005882349044 and parameters: {'weight_class_0': 0.0068484477224692855, 'weight_class_1': 0.08776608905284848, 'weight_class_2': 0.08108835743625241}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:03,768] Trial 1823 finished with value: 0.9496337170246519 and parameters: {'weight_class_0': 0.00651671300836464, 'weight_class_1': 0.08171525106291823, 'weight_class_2': 0.082964391818075}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:03,840] Trial 1825 finished with value: 0.9497220836108767 and parameters: {'weight_class_0': 0.006844525696402317, 'weight_class_1': 0.08375591638081249, 'weight_class_2': 0.07648777814798707}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:03,845] Trial 1824 finished with value: 0.9477800099456717 and parameters: {'weight_class_0': 0.006629287227834075, 'weight_class_1': 0.08126140232844221, 'weight_class_2': 0.1969294965640967}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:03,851] Trial 1826 finished with value: 0.9496398784627401 and parameters: {'weight_class_0': 0.00730452682188583, 'weight_class_1': 0.09120734913979062, 'weight_class_2': 0.0758711320529981}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:03,872] Trial 1827 finished with value: 0.949598481147846 and parameters: {'weight_class_0': 0.007434635864642605, 'weight_class_1': 0.0864297319725817, 'weight_class_2': 0.0782852429292943}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:03,913] Trial 1828 finished with value: 0.9496534832198495 and parameters: {'weight_class_0': 0.006432038310376581, 'weight_class_1': 0.09042570283304964, 'weight_class_2': 0.07758407903236463}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:03,923] Trial 1829 finished with value: 0.9496663656887998 and parameters: {'weight_class_0': 0.006791225012055524, 'weight_class_1': 0.08638841289922577, 'weight_class_2': 0.07340929508628528}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:03,939] Trial 1830 finished with value: 0.9496448687785914 and parameters: {'weight_class_0': 0.006007235181538242, 'weight_class_1': 0.0863195539402898, 'weight_class_2': 0.07591213042218391}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  61%|███████████████████████████████████████████████████████████████████████████████▋                                                  | 1839/3000 [00:40<00:28, 40.88it/s]

[I 2026-07-03 10:57:03,952] Trial 1831 finished with value: 0.9473716572772869 and parameters: {'weight_class_0': 0.006558206554972772, 'weight_class_1': 0.08608749941099669, 'weight_class_2': 0.23104940063468335}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:03,985] Trial 1832 finished with value: 0.9496530386385992 and parameters: {'weight_class_0': 0.006648577383944507, 'weight_class_1': 0.08086359451038035, 'weight_class_2': 0.07116643104776291}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:03,998] Trial 1833 finished with value: 0.9495373299864457 and parameters: {'weight_class_0': 0.0084392334044912, 'weight_class_1': 0.0889101359744833, 'weight_class_2': 0.07203420212290099}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:04,040] Trial 1834 finished with value: 0.9495529330754483 and parameters: {'weight_class_0': 0.007788829807077849, 'weight_class_1': 0.08556277162502259, 'weight_class_2': 0.07761115547939296}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:04,048] Trial 1835 finished with value: 0.9495496420689121 and parameters: {'weight_class_0': 0.00839449133269916, 'weight_class_1': 0.09131881306961577, 'weight_class_2': 0.074291422561158}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:04,123] Trial 1836 finished with value: 0.9494855211238322 and parameters: {'weight_class_0': 0.010284585438665967, 'weight_class_1': 0.09364795457361458, 'weight_class_2': 0.09395071426957508}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:04,150] Trial 1837 finished with value: 0.9489995421801886 and parameters: {'weight_class_0': 0.008356801728775627, 'weight_class_1': 0.1016763861971903, 'weight_class_2': 0.14881348054301563}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:04,153] Trial 1838 finished with value: 0.9495269294462091 and parameters: {'weight_class_0': 0.010880428116303985, 'weight_class_1': 0.10241733630117154, 'weight_class_2': 0.10119874020904308}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:04,197] Trial 1839 finished with value: 0.9496666163127913 and parameters: {'weight_class_0': 0.008088190839124171, 'weight_class_1': 0.10791430608452017, 'weight_class_2': 0.10399312218085657}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:04,205] Trial 1840 finished with value: 0.9495372916571402 and parameters: {'weight_class_0': 0.011674835770039492, 'weight_class_1': 0.10689136446184806, 'weight_class_2': 0.1006745835785655}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:04,222] Trial 1841 finished with value: 0.9496360003852189 and parameters: {'weight_class_0': 0.009340036075183977, 'weight_class_1': 0.10513081903991785, 'weight_class_2': 0.09970211073578239}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:04,224] Trial 1842 finished with value: 0.949559823152413 and parameters: {'weight_class_0': 0.008916210300096566, 'weight_class_1': 0.09180488180668431, 'weight_class_2': 0.0996580359293428}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:04,249] Trial 1843 finished with value: 0.9496581581495782 and parameters: {'weight_class_0': 0.008381928226437975, 'weight_class_1': 0.120781881144166, 'weight_class_2': 0.09800072554424032}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:04,282] Trial 1844 finished with value: 0.949479701393717 and parameters: {'weight_class_0': 0.011680097955119246, 'weight_class_1': 0.10454494069063246, 'weight_class_2': 0.10632820793708936}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:04,346] Trial 1846 finished with value: 0.9495352004932568 and parameters: {'weight_class_0': 0.012712490345573651, 'weight_class_1': 0.13509253198649684, 'weight_class_2': 0.10918625015862043}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:04,350] Trial 1847 finished with value: 0.9492556541860576 and parameters: {'weight_class_0': 0.009511459295503484, 'weight_class_1': 0.11647092635185519, 'weight_class_2': 0.1536482981909022}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:04,354] Trial 1845 finished with value: 0.9494960377576162 and parameters: {'weight_class_0': 0.011554314418651478, 'weight_class_1': 0.1075022234031976, 'weight_class_2': 0.1266144314526703}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:04,386] Trial 1848 finished with value: 0.9496545415925551 and parameters: {'weight_class_0': 0.011243933964158624, 'weight_class_1': 0.13942388228332578, 'weight_class_2': 0.10227328815333642}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:04,417] Trial 1849 finished with value: 0.9485746689336526 and parameters: {'weight_class_0': 0.012451426357934359, 'weight_class_1': 0.0717621281616188, 'weight_class_2': 0.10891854624656505}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:04,435] Trial 1850 finished with value: 0.9494178848140874 and parameters: {'weight_class_0': 0.006986376513572601, 'weight_class_1': 0.126108129376446, 'weight_class_2': 0.10096753940014405}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:04,465] Trial 1851 finished with value: 0.9490929244407807 and parameters: {'weight_class_0': 0.008836709290777565, 'weight_class_1': 0.07690074621160593, 'weight_class_2': 0.12751254004600404}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:04,499] Trial 1852 finished with value: 0.949608923312199 and parameters: {'weight_class_0': 0.00919174927236296, 'weight_class_1': 0.1342953928607206, 'weight_class_2': 0.08973111437396042}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:04,523] Trial 1853 finished with value: 0.9495382761906922 and parameters: {'weight_class_0': 0.006806895841173973, 'weight_class_1': 0.12758800859792424, 'weight_class_2': 0.08986506034014305}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:04,550] Trial 1854 finished with value: 0.9494604087796504 and parameters: {'weight_class_0': 0.008004421533092972, 'weight_class_1': 0.07483660308983349, 'weight_class_2': 0.06459560609907783}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:04,584] Trial 1856 finished with value: 0.9488420980360228 and parameters: {'weight_class_0': 0.006561100941153893, 'weight_class_1': 0.14747844336398155, 'weight_class_2': 0.12754427721742526}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  62%|████████████████████████████████████████████████████████████████████████████████▊                                                 | 1865/3000 [00:40<00:27, 41.22it/s]

[I 2026-07-03 10:57:04,584] Trial 1855 finished with value: 0.9484498694295422 and parameters: {'weight_class_0': 0.012604677894655619, 'weight_class_1': 0.07258879882089518, 'weight_class_2': 0.1313625988267942}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:04,621] Trial 1857 finished with value: 0.9496054305613949 and parameters: {'weight_class_0': 0.006603545674214866, 'weight_class_1': 0.07491153143414737, 'weight_class_2': 0.06697900292935734}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:04,674] Trial 1858 finished with value: 0.9494516202040574 and parameters: {'weight_class_0': 0.00680983902785334, 'weight_class_1': 0.07311255695701922, 'weight_class_2': 0.09060711450106002}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:04,683] Trial 1859 finished with value: 0.9496038394399283 and parameters: {'weight_class_0': 0.006605745766525153, 'weight_class_1': 0.07489995460581413, 'weight_class_2': 0.06593417540711588}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:04,689] Trial 1861 finished with value: 0.9495540233398388 and parameters: {'weight_class_0': 0.006578901626590037, 'weight_class_1': 0.07336396606003213, 'weight_class_2': 0.06657297995378922}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:04,725] Trial 1860 finished with value: 0.9468487892291888 and parameters: {'weight_class_0': 0.006409053547251725, 'weight_class_1': 0.35451577567328907, 'weight_class_2': 0.06666726978196881}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:04,727] Trial 1862 finished with value: 0.9495492259199679 and parameters: {'weight_class_0': 0.006891185206886565, 'weight_class_1': 0.07540769296657199, 'weight_class_2': 0.06373889764327975}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:04,765] Trial 1863 finished with value: 0.945956768484398 and parameters: {'weight_class_0': 0.006604409977849205, 'weight_class_1': 0.4046324029799565, 'weight_class_2': 0.06999547726737884}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:04,771] Trial 1864 finished with value: 0.9496538052158746 and parameters: {'weight_class_0': 0.00620573524332129, 'weight_class_1': 0.0701318084182013, 'weight_class_2': 0.06551450767671918}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  62%|█████████████████████████████████████████████████████████████████████████████████                                                 | 1872/3000 [00:41<00:27, 40.46it/s]

[I 2026-07-03 10:57:04,826] Trial 1865 finished with value: 0.9497150043646747 and parameters: {'weight_class_0': 0.0062204010888063915, 'weight_class_1': 0.07670591361184469, 'weight_class_2': 0.06855773516633244}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:04,839] Trial 1866 finished with value: 0.9451675714913983 and parameters: {'weight_class_0': 0.005917184491455934, 'weight_class_1': 0.39268662994561243, 'weight_class_2': 0.06694013428207797}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:04,867] Trial 1867 finished with value: 0.949066165659779 and parameters: {'weight_class_0': 0.006282758284632251, 'weight_class_1': 0.20033650197632077, 'weight_class_2': 0.06800617709828079}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:04,904] Trial 1868 finished with value: 0.9496676615964829 and parameters: {'weight_class_0': 0.006068824891237203, 'weight_class_1': 0.07294409218828754, 'weight_class_2': 0.06656420996610607}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:04,920] Trial 1869 finished with value: 0.9496913327749855 and parameters: {'weight_class_0': 0.0057428684078696685, 'weight_class_1': 0.07386952504420163, 'weight_class_2': 0.0654584200435787}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:04,968] Trial 1870 finished with value: 0.9496004294851454 and parameters: {'weight_class_0': 0.005488258204924084, 'weight_class_1': 0.07363382174202678, 'weight_class_2': 0.07263355298498023}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:04,971] Trial 1871 finished with value: 0.949683290172396 and parameters: {'weight_class_0': 0.005730548793387775, 'weight_class_1': 0.07373761132613671, 'weight_class_2': 0.07090718341786718}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:04,991] Trial 1872 finished with value: 0.9493921286863102 and parameters: {'weight_class_0': 0.005505315418346734, 'weight_class_1': 0.0658213724627973, 'weight_class_2': 0.0830181741687819}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:05,040] Trial 1873 finished with value: 0.949445811309143 and parameters: {'weight_class_0': 0.0052363517913970575, 'weight_class_1': 0.0673240281066892, 'weight_class_2': 0.07816357529690722}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:05,053] Trial 1875 finished with value: 0.9493831440068289 and parameters: {'weight_class_0': 0.005166437150211503, 'weight_class_1': 0.09096636327213359, 'weight_class_2': 0.07809017981972698}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:05,074] Trial 1874 finished with value: 0.9493982714944744 and parameters: {'weight_class_0': 0.0055338633852424135, 'weight_class_1': 0.0642058949530906, 'weight_class_2': 0.0809623492241629}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:05,096] Trial 1876 finished with value: 0.9493150359455468 and parameters: {'weight_class_0': 0.0055188292263202285, 'weight_class_1': 0.09292025314467384, 'weight_class_2': 0.08949720198463684}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:05,130] Trial 1878 finished with value: 0.9496087705755838 and parameters: {'weight_class_0': 0.008162853611755188, 'weight_class_1': 0.09685401114698634, 'weight_class_2': 0.07788066311809413}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:05,136] Trial 1877 finished with value: 0.9496494463633862 and parameters: {'weight_class_0': 0.00819647247596966, 'weight_class_1': 0.0993134531104129, 'weight_class_2': 0.08848732435588474}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:05,199] Trial 1879 finished with value: 0.9496247282434137 and parameters: {'weight_class_0': 0.007736960137694794, 'weight_class_1': 0.09246130739088235, 'weight_class_2': 0.08102527845104547}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:05,205] Trial 1880 finished with value: 0.9496791465928354 and parameters: {'weight_class_0': 0.008102643837701332, 'weight_class_1': 0.10437138359889366, 'weight_class_2': 0.07896876352117757}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  63%|█████████████████████████████████████████████████████████████████████████████████▊                                                | 1889/3000 [00:41<00:26, 41.27it/s]

[I 2026-07-03 10:57:05,215] Trial 1881 finished with value: 0.9496313710245099 and parameters: {'weight_class_0': 0.00816991356216848, 'weight_class_1': 0.10555352554348058, 'weight_class_2': 0.0855132166853026}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:05,254] Trial 1882 finished with value: 0.9495888576909502 and parameters: {'weight_class_0': 0.008514726925315215, 'weight_class_1': 0.09890167804094499, 'weight_class_2': 0.08561696509186462}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:05,277] Trial 1883 finished with value: 0.9497164868871062 and parameters: {'weight_class_0': 0.00759316011539548, 'weight_class_1': 0.09480722685345853, 'weight_class_2': 0.08614503854744357}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:05,278] Trial 1884 finished with value: 0.9496386003577552 and parameters: {'weight_class_0': 0.008006648213404398, 'weight_class_1': 0.09046638478245939, 'weight_class_2': 0.0854032294752089}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:05,326] Trial 1885 finished with value: 0.9496547391119895 and parameters: {'weight_class_0': 0.008361518506190206, 'weight_class_1': 0.10901891923288096, 'weight_class_2': 0.08066955843530955}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:05,354] Trial 1886 finished with value: 0.949538920902319 and parameters: {'weight_class_0': 0.008974464627539524, 'weight_class_1': 0.09722404041328553, 'weight_class_2': 0.08061274673725764}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:05,385] Trial 1887 finished with value: 0.9486199320570314 and parameters: {'weight_class_0': 0.00826750921254352, 'weight_class_1': 0.0979408784381159, 'weight_class_2': 0.1728403535161058}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:05,394] Trial 1888 finished with value: 0.9496137814667818 and parameters: {'weight_class_0': 0.007340762590097158, 'weight_class_1': 0.08834593744713964, 'weight_class_2': 0.06047033831161661}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:05,431] Trial 1889 finished with value: 0.9496476171929588 and parameters: {'weight_class_0': 0.00691771085571564, 'weight_class_1': 0.09267070416236062, 'weight_class_2': 0.05968802216025277}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  63%|██████████████████████████████████████████████████████████████████████████████████▏                                               | 1898/3000 [00:41<00:28, 38.10it/s]

[I 2026-07-03 10:57:05,475] Trial 1890 finished with value: 0.9482970834037344 and parameters: {'weight_class_0': 0.010522641056806111, 'weight_class_1': 0.0840386564548113, 'weight_class_2': 0.05786018982665921}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:05,488] Trial 1891 finished with value: 0.9271717670081546 and parameters: {'weight_class_0': 0.00981350140640904, 'weight_class_1': 0.08225224789460697, 'weight_class_2': 1.5292241699543923}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:05,509] Trial 1892 finished with value: 0.9484447475711932 and parameters: {'weight_class_0': 0.009860927077572166, 'weight_class_1': 0.07522566951845595, 'weight_class_2': 0.05834636985761808}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:05,521] Trial 1893 finished with value: 0.9482828762864052 and parameters: {'weight_class_0': 0.010369582904388124, 'weight_class_1': 0.08649074302158277, 'weight_class_2': 0.0561535727204964}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:05,559] Trial 1894 finished with value: 0.8972568537272471 and parameters: {'weight_class_0': 0.01125713353376303, 'weight_class_1': 2.2196538480168018, 'weight_class_2': 0.12223320079648739}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:05,600] Trial 1896 finished with value: 0.9484651806185164 and parameters: {'weight_class_0': 0.010952049428936446, 'weight_class_1': 0.1437019368220793, 'weight_class_2': 0.05793317668426265}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:05,615] Trial 1895 finished with value: 0.9495776907380064 and parameters: {'weight_class_0': 0.010233753394150003, 'weight_class_1': 0.1198658036896679, 'weight_class_2': 0.12712175384990115}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:05,622] Trial 1897 finished with value: 0.9493468787113205 and parameters: {'weight_class_0': 0.009581178691327364, 'weight_class_1': 0.1213252858829287, 'weight_class_2': 0.1521675271475524}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:05,646] Trial 1898 finished with value: 0.9493431861742376 and parameters: {'weight_class_0': 0.009747987067230346, 'weight_class_1': 0.08247820847327039, 'weight_class_2': 0.11643194349868537}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:05,680] Trial 1899 finished with value: 0.9495773858043574 and parameters: {'weight_class_0': 0.01024532952146297, 'weight_class_1': 0.12533265662794227, 'weight_class_2': 0.13337212230640016}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:05,710] Trial 1900 finished with value: 0.9496445276999648 and parameters: {'weight_class_0': 0.009059768492449235, 'weight_class_1': 0.1259145463995008, 'weight_class_2': 0.09864938446902918}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:05,757] Trial 1901 finished with value: 0.9495749870003345 and parameters: {'weight_class_0': 0.0112567135272435, 'weight_class_1': 0.18539856877615093, 'weight_class_2': 0.11930749949302026}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:05,766] Trial 1902 finished with value: 0.9482517860976252 and parameters: {'weight_class_0': 0.011464447590385599, 'weight_class_1': 0.059740083856719355, 'weight_class_2': 0.10278817242986112}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:05,792] Trial 1903 finished with value: 0.9492424108619003 and parameters: {'weight_class_0': 0.007658215917133706, 'weight_class_1': 0.16542669190228798, 'weight_class_2': 0.11889269389717613}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:05,822] Trial 1904 finished with value: 0.9496781994764506 and parameters: {'weight_class_0': 0.009695151633488113, 'weight_class_1': 0.13882317713815046, 'weight_class_2': 0.10744421997791267}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:05,838] Trial 1905 finished with value: 0.94949571185 and parameters: {'weight_class_0': 0.009715887611731616, 'weight_class_1': 0.12505699369570683, 'weight_class_2': 0.13625498411271147}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:05,880] Trial 1907 finished with value: 0.9491292376160398 and parameters: {'weight_class_0': 0.007931407682003913, 'weight_class_1': 0.06221617429940643, 'weight_class_2': 0.10238298790416457}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  64%|██████████████████████████████████████████████████████████████████████████████████▉                                               | 1914/3000 [00:42<00:29, 36.94it/s]

[I 2026-07-03 10:57:05,880] Trial 1906 finished with value: 0.9489725528350333 and parameters: {'weight_class_0': 0.007240163158348172, 'weight_class_1': 0.1408536972817562, 'weight_class_2': 0.14038256428592505}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:05,900] Trial 1908 finished with value: 0.9490494864913259 and parameters: {'weight_class_0': 0.0075342590363558105, 'weight_class_1': 0.061232326156741936, 'weight_class_2': 0.10541670430095025}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:05,978] Trial 1909 finished with value: 0.9491797261327718 and parameters: {'weight_class_0': 0.007440936180933578, 'weight_class_1': 0.06203242756151079, 'weight_class_2': 0.10146154942199444}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:05,983] Trial 1911 finished with value: 0.9488958797826532 and parameters: {'weight_class_0': 0.007222577257355434, 'weight_class_1': 0.06096395313604282, 'weight_class_2': 0.11247402477520754}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:05,994] Trial 1910 finished with value: 0.9491754941265153 and parameters: {'weight_class_0': 0.007249406041988325, 'weight_class_1': 0.061406169545116185, 'weight_class_2': 0.10030700778802999}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:06,020] Trial 1912 finished with value: 0.9491519187997356 and parameters: {'weight_class_0': 0.006905477980818564, 'weight_class_1': 0.06248088393340421, 'weight_class_2': 0.10195097230521108}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:06,090] Trial 1914 finished with value: 0.9491666149873016 and parameters: {'weight_class_0': 0.007611827430136434, 'weight_class_1': 0.22617128307753792, 'weight_class_2': 0.10260800022466358}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:06,092] Trial 1913 finished with value: 0.9493027626064339 and parameters: {'weight_class_0': 0.00743765304194931, 'weight_class_1': 0.0644941983862916, 'weight_class_2': 0.09466967519340655}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  64%|███████████████████████████████████████████████████████████████████████████████████▎                                              | 1923/3000 [00:42<00:27, 39.50it/s]

[I 2026-07-03 10:57:06,105] Trial 1915 finished with value: 0.9494439336937854 and parameters: {'weight_class_0': 0.007530903925105373, 'weight_class_1': 0.06468798002330867, 'weight_class_2': 0.06985917885402514}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:06,106] Trial 1917 finished with value: 0.9494045452660552 and parameters: {'weight_class_0': 0.007434296557641295, 'weight_class_1': 0.06608062740733846, 'weight_class_2': 0.09001810294940489}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:06,109] Trial 1916 finished with value: 0.9492879529310053 and parameters: {'weight_class_0': 0.007529444565491573, 'weight_class_1': 0.06367879082205254, 'weight_class_2': 0.09406052734677402}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:06,167] Trial 1918 finished with value: 0.9492046557709349 and parameters: {'weight_class_0': 0.005405091358638269, 'weight_class_1': 0.06472384145111378, 'weight_class_2': 0.088036139712266}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:06,200] Trial 1919 finished with value: 0.9489795975274126 and parameters: {'weight_class_0': 0.005326712102405262, 'weight_class_1': 0.0628235060050016, 'weight_class_2': 0.09461493141638805}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:06,223] Trial 1920 finished with value: 0.9489112144372526 and parameters: {'weight_class_0': 0.0051566210435623075, 'weight_class_1': 0.06381545349652096, 'weight_class_2': 0.09627002086222618}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:06,269] Trial 1921 finished with value: 0.9492380715803991 and parameters: {'weight_class_0': 0.0053400987108447925, 'weight_class_1': 0.07693864199049466, 'weight_class_2': 0.08982887621056337}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:06,294] Trial 1923 finished with value: 0.9496248026559257 and parameters: {'weight_class_0': 0.005209385030303258, 'weight_class_1': 0.07793070595443745, 'weight_class_2': 0.057061084618124897}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:06,310] Trial 1924 finished with value: 0.9496190869424171 and parameters: {'weight_class_0': 0.0055871923431052095, 'weight_class_1': 0.07680531505990365, 'weight_class_2': 0.05506794442672523}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  64%|███████████████████████████████████████████████████████████████████████████████████▋                                              | 1931/3000 [00:42<00:26, 40.28it/s]

[I 2026-07-03 10:57:06,311] Trial 1922 finished with value: 0.9495963910042153 and parameters: {'weight_class_0': 0.00549495073577562, 'weight_class_1': 0.079857527591849, 'weight_class_2': 0.056892651428094416}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:06,382] Trial 1927 finished with value: 0.949669182818381 and parameters: {'weight_class_0': 0.005336016404724987, 'weight_class_1': 0.07418076892149149, 'weight_class_2': 0.06448891713115239}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:06,386] Trial 1926 finished with value: 0.9495999821153535 and parameters: {'weight_class_0': 0.005225775989316615, 'weight_class_1': 0.08027476676081106, 'weight_class_2': 0.06362885649467889}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:06,392] Trial 1925 finished with value: 0.9496204864144949 and parameters: {'weight_class_0': 0.005216721476345033, 'weight_class_1': 0.07848904452046879, 'weight_class_2': 0.05748919723839948}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:06,438] Trial 1929 finished with value: 0.9496726298355976 and parameters: {'weight_class_0': 0.005223369606044794, 'weight_class_1': 0.07568998243095017, 'weight_class_2': 0.05722400343508291}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:06,447] Trial 1928 finished with value: 0.9430728925772184 and parameters: {'weight_class_0': 0.013848889520932446, 'weight_class_1': 0.04997314576138887, 'weight_class_2': 0.05676574114928118}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:06,494] Trial 1931 finished with value: 0.9496061259230251 and parameters: {'weight_class_0': 0.00588905074317006, 'weight_class_1': 0.07919239392288756, 'weight_class_2': 0.053383464828632765}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:06,508] Trial 1930 finished with value: 0.9495769721814428 and parameters: {'weight_class_0': 0.005114385948121744, 'weight_class_1': 0.07958592531424996, 'weight_class_2': 0.055056753300551375}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:06,519] Trial 1932 finished with value: 0.949646805758527 and parameters: {'weight_class_0': 0.005957937835146108, 'weight_class_1': 0.08474987448090592, 'weight_class_2': 0.05627616196600248}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:06,598] Trial 1934 finished with value: 0.949406766912683 and parameters: {'weight_class_0': 0.0059567424596521255, 'weight_class_1': 0.05119150279399044, 'weight_class_2': 0.06954158773298648}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:06,599] Trial 1933 finished with value: 0.9494590854063224 and parameters: {'weight_class_0': 0.005836230137578764, 'weight_class_1': 0.05315634488750223, 'weight_class_2': 0.05562049642498693}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:06,638] Trial 1935 finished with value: 0.9494196417307327 and parameters: {'weight_class_0': 0.006076774592552048, 'weight_class_1': 0.05247997547796955, 'weight_class_2': 0.07076413168363141}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:06,639] Trial 1936 finished with value: 0.9494181878872262 and parameters: {'weight_class_0': 0.006309307108738844, 'weight_class_1': 0.053520853307068884, 'weight_class_2': 0.07105213212398771}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:06,685] Trial 1937 finished with value: 0.9493247449073495 and parameters: {'weight_class_0': 0.006091013074024397, 'weight_class_1': 0.052679606695942745, 'weight_class_2': 0.07474552524307919}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:06,692] Trial 1938 finished with value: 0.949361901997046 and parameters: {'weight_class_0': 0.00653681115545333, 'weight_class_1': 0.05387032393448435, 'weight_class_2': 0.0726440291425893}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:06,711] Trial 1939 finished with value: 0.9491445275162792 and parameters: {'weight_class_0': 0.004655630224531975, 'weight_class_1': 0.05256393965131816, 'weight_class_2': 0.07614422005440132}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  65%|████████████████████████████████████████████████████████████████████████████████████▎                                             | 1947/3000 [00:43<00:26, 40.29it/s]

[I 2026-07-03 10:57:06,736] Trial 1940 finished with value: 0.9493902951341954 and parameters: {'weight_class_0': 0.006371333029804123, 'weight_class_1': 0.053371143355480884, 'weight_class_2': 0.06961932300043788}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:06,769] Trial 1941 finished with value: 0.9496199553519716 and parameters: {'weight_class_0': 0.004667314288453978, 'weight_class_1': 0.05357780047459046, 'weight_class_2': 0.04923017591783249}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:06,779] Trial 1942 finished with value: 0.9493050700842431 and parameters: {'weight_class_0': 0.00635039140995013, 'weight_class_1': 0.05413013618255518, 'weight_class_2': 0.08011715061500585}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:06,797] Trial 1943 finished with value: 0.9492349361274788 and parameters: {'weight_class_0': 0.0046054498889818475, 'weight_class_1': 0.05299807955678164, 'weight_class_2': 0.07269169641595223}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:06,812] Trial 1944 finished with value: 0.9493686357057353 and parameters: {'weight_class_0': 0.006296326572908735, 'weight_class_1': 0.05254374995191301, 'weight_class_2': 0.07178724452595445}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:06,897] Trial 1945 finished with value: 0.9490133368232506 and parameters: {'weight_class_0': 0.004365029238897947, 'weight_class_1': 0.11009104171068197, 'weight_class_2': 0.07310217299848058}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:06,916] Trial 1946 finished with value: 0.7373952019973468 and parameters: {'weight_class_0': 6.354739210493226, 'weight_class_1': 0.10688645238321128, 'weight_class_2': 0.047049806607901146}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:06,940] Trial 1947 finished with value: 0.8034857712337774 and parameters: {'weight_class_0': 2.107791011743706, 'weight_class_1': 0.10401738360962963, 'weight_class_2': 0.049460283562710504}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  65%|████████████████████████████████████████████████████████████████████████████████████▊                                             | 1956/3000 [00:43<00:26, 39.31it/s]

[I 2026-07-03 10:57:06,974] Trial 1948 finished with value: 0.9494057481048338 and parameters: {'weight_class_0': 0.004270557282134707, 'weight_class_1': 0.1060309012613224, 'weight_class_2': 0.05142459492678714}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:07,008] Trial 1949 finished with value: 0.949529432638991 and parameters: {'weight_class_0': 0.004459697459018165, 'weight_class_1': 0.09304123906395738, 'weight_class_2': 0.046987032273867746}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:07,010] Trial 1950 finished with value: 0.9473027708137259 and parameters: {'weight_class_0': 0.0044292235250832515, 'weight_class_1': 0.1086536085819585, 'weight_class_2': 0.17973381773449584}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:07,036] Trial 1951 finished with value: 0.949398653638882 and parameters: {'weight_class_0': 0.00437669788244295, 'weight_class_1': 0.10998536627891364, 'weight_class_2': 0.04837553483858267}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:07,042] Trial 1952 finished with value: 0.9492426201132464 and parameters: {'weight_class_0': 0.003914429591116822, 'weight_class_1': 0.10980103271153793, 'weight_class_2': 0.05057520916716909}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:07,091] Trial 1953 finished with value: 0.9492404680577972 and parameters: {'weight_class_0': 0.003678012457144921, 'weight_class_1': 0.1026131071887571, 'weight_class_2': 0.047850661217396305}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:07,100] Trial 1954 finished with value: 0.9491732959615948 and parameters: {'weight_class_0': 0.0038146928455695247, 'weight_class_1': 0.1128967929852734, 'weight_class_2': 0.050741123190199654}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:07,106] Trial 1955 finished with value: 0.9492050269696307 and parameters: {'weight_class_0': 0.0035865058024839368, 'weight_class_1': 0.10336586464248772, 'weight_class_2': 0.04644860434112831}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:07,129] Trial 1956 finished with value: 0.9491675891455786 and parameters: {'weight_class_0': 0.003688743179107442, 'weight_class_1': 0.10939756202617854, 'weight_class_2': 0.04847363409697661}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  65%|█████████████████████████████████████████████████████████████████████████████████████                                             | 1964/3000 [00:43<00:26, 39.01it/s]

[I 2026-07-03 10:57:07,178] Trial 1958 finished with value: 0.9495848662471181 and parameters: {'weight_class_0': 0.0037315932309395362, 'weight_class_1': 0.04488120816561322, 'weight_class_2': 0.048133467731927615}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:07,201] Trial 1957 finished with value: 0.9492098072320427 and parameters: {'weight_class_0': 0.0036835104414907156, 'weight_class_1': 0.09116382130357661, 'weight_class_2': 0.05167221136221465}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:07,210] Trial 1959 finished with value: 0.9493854578117483 and parameters: {'weight_class_0': 0.0037717565619885462, 'weight_class_1': 0.09522518480680867, 'weight_class_2': 0.04654307797323814}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:07,269] Trial 1960 finished with value: 0.9495547709426271 and parameters: {'weight_class_0': 0.0036514547549500566, 'weight_class_1': 0.0646489018292144, 'weight_class_2': 0.048178007368886305}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:07,315] Trial 1962 finished with value: 0.949578963096488 and parameters: {'weight_class_0': 0.0034812274220816035, 'weight_class_1': 0.044765105937988894, 'weight_class_2': 0.04576929066641977}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:07,331] Trial 1961 finished with value: 0.9490160995224933 and parameters: {'weight_class_0': 0.003466588386993763, 'weight_class_1': 0.044159322319562745, 'weight_class_2': 0.06182135774769566}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:07,341] Trial 1963 finished with value: 0.9491550896573114 and parameters: {'weight_class_0': 0.0036175826950200374, 'weight_class_1': 0.04442970990083334, 'weight_class_2': 0.061428777320592536}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:07,356] Trial 1964 finished with value: 0.949124770292911 and parameters: {'weight_class_0': 0.0035640234878669807, 'weight_class_1': 0.04461663450511098, 'weight_class_2': 0.061598591661663}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  66%|█████████████████████████████████████████████████████████████████████████████████████▍                                            | 1973/3000 [00:43<00:25, 40.73it/s]

[I 2026-07-03 10:57:07,364] Trial 1965 finished with value: 0.9475555917642584 and parameters: {'weight_class_0': 0.008823059621561371, 'weight_class_1': 0.04296936526855309, 'weight_class_2': 0.06136196224024942}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:07,442] Trial 1966 finished with value: 0.9493031166712779 and parameters: {'weight_class_0': 0.004852573525923661, 'weight_class_1': 0.044304030328498945, 'weight_class_2': 0.06356143161948073}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:07,455] Trial 1967 finished with value: 0.9478271769236803 and parameters: {'weight_class_0': 0.008902084048345138, 'weight_class_1': 0.04510987846951824, 'weight_class_2': 0.06465322724755292}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:07,463] Trial 1968 finished with value: 0.9492009475947362 and parameters: {'weight_class_0': 0.008299311250281308, 'weight_class_1': 0.06816420848275571, 'weight_class_2': 0.06365146279200586}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:07,471] Trial 1969 finished with value: 0.9363374500339207 and parameters: {'weight_class_0': 0.008713015847768185, 'weight_class_1': 0.06771522482365548, 'weight_class_2': 1.0651954607872582}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:07,479] Trial 1970 finished with value: 0.9024744851849674 and parameters: {'weight_class_0': 0.004947002589136448, 'weight_class_1': 0.0463410368546857, 'weight_class_2': 1.095250349593421}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:07,542] Trial 1971 finished with value: 0.9477807344075228 and parameters: {'weight_class_0': 0.00880800014338246, 'weight_class_1': 0.04441013134382587, 'weight_class_2': 0.0635707303128267}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:07,577] Trial 1972 finished with value: 0.9493182417120836 and parameters: {'weight_class_0': 0.004869287613168692, 'weight_class_1': 0.04348237072733257, 'weight_class_2': 0.06247162243875746}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  66%|█████████████████████████████████████████████████████████████████████████████████████▊                                            | 1981/3000 [00:43<00:25, 39.61it/s]

[I 2026-07-03 10:57:07,611] Trial 1973 finished with value: 0.9495437249658694 and parameters: {'weight_class_0': 0.004694164431840023, 'weight_class_1': 0.07157630674092053, 'weight_class_2': 0.06428760451863427}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:07,624] Trial 1974 finished with value: 0.9493495532556185 and parameters: {'weight_class_0': 0.008662703579694076, 'weight_class_1': 0.06959197969886208, 'weight_class_2': 0.08480184333409323}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:07,628] Trial 1976 finished with value: 0.9495267644526582 and parameters: {'weight_class_0': 0.004989259286440153, 'weight_class_1': 0.07111841370258237, 'weight_class_2': 0.0389479295485066}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:07,642] Trial 1975 finished with value: 0.9491347126489001 and parameters: {'weight_class_0': 0.004957151566836185, 'weight_class_1': 0.06973539438670485, 'weight_class_2': 0.0872600066157027}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:07,682] Trial 1977 finished with value: 0.8085156105111002 and parameters: {'weight_class_0': 1.456722083683775, 'weight_class_1': 0.07641297024652788, 'weight_class_2': 0.08773417293311761}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:07,710] Trial 1978 finished with value: 0.9491617940085245 and parameters: {'weight_class_0': 0.00498682886084492, 'weight_class_1': 0.06990190644099781, 'weight_class_2': 0.08623694545703059}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:07,766] Trial 1979 finished with value: 0.8948103930895869 and parameters: {'weight_class_0': 0.0047537946357839945, 'weight_class_1': 0.06070500387133154, 'weight_class_2': 0.0015191282428196249}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:07,771] Trial 1981 finished with value: 0.9491185243238247 and parameters: {'weight_class_0': 0.005012911159460954, 'weight_class_1': 0.072766297823076, 'weight_class_2': 0.08788997343639147}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:07,795] Trial 1980 finished with value: 0.9495219386212268 and parameters: {'weight_class_0': 0.005044204357097021, 'weight_class_1': 0.07095306373306759, 'weight_class_2': 0.03958891979976008}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  66%|██████████████████████████████████████████████████████████████████████████████████████▏                                           | 1990/3000 [00:44<00:26, 38.77it/s]

[I 2026-07-03 10:57:07,806] Trial 1983 finished with value: 0.808272747745312 and parameters: {'weight_class_0': 1.39709402384603, 'weight_class_1': 0.07168738636999053, 'weight_class_2': 0.08408918527769287}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:07,806] Trial 1982 finished with value: 0.9489798127516008 and parameters: {'weight_class_0': 0.004579267761087251, 'weight_class_1': 0.07303903137639743, 'weight_class_2': 0.08686717594509526}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:07,880] Trial 1985 finished with value: 0.9485464444329447 and parameters: {'weight_class_0': 0.00669584498859311, 'weight_class_1': 0.05912728814367513, 'weight_class_2': 0.038321199910441826}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:07,881] Trial 1984 finished with value: 0.9486180081005461 and parameters: {'weight_class_0': 0.006803724681464897, 'weight_class_1': 0.0717398949721696, 'weight_class_2': 0.03932348061226776}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:07,929] Trial 1986 finished with value: 0.94864153663246 and parameters: {'weight_class_0': 0.006608773349745545, 'weight_class_1': 0.05670548056804061, 'weight_class_2': 0.03971233835714757}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:07,938] Trial 1987 finished with value: 0.9464661799217987 and parameters: {'weight_class_0': 0.013676665159076336, 'weight_class_1': 0.05826548272164744, 'weight_class_2': 0.08393603871522343}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:07,962] Trial 1988 finished with value: 0.949339006902377 and parameters: {'weight_class_0': 0.006597529272648978, 'weight_class_1': 0.05893568807322962, 'weight_class_2': 0.08229672142868008}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:07,996] Trial 1990 finished with value: 0.9487083056325587 and parameters: {'weight_class_0': 0.00665258610625274, 'weight_class_1': 0.08242426960824437, 'weight_class_2': 0.037865078958894925}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:08,019] Trial 1989 finished with value: 0.9450505614899319 and parameters: {'weight_class_0': 0.006420409929175515, 'weight_class_1': 0.08617537408789612, 'weight_class_2': 0.4437655687368048}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:08,061] Trial 1991 finished with value: 0.948984722187929 and parameters: {'weight_class_0': 0.00654138086191694, 'weight_class_1': 0.05787118755195231, 'weight_class_2': 0.04372809093537526}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:08,081] Trial 1992 finished with value: 0.9486609744142922 and parameters: {'weight_class_0': 0.006628380054008623, 'weight_class_1': 0.059081138478383526, 'weight_class_2': 0.039417390754957475}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:08,103] Trial 1993 finished with value: 0.8173087945628871 and parameters: {'weight_class_0': 0.45978842240887735, 'weight_class_1': 0.05739059493875352, 'weight_class_2': 0.03900351238717796}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:08,146] Trial 1995 finished with value: 0.9488233832894547 and parameters: {'weight_class_0': 0.006560385163652998, 'weight_class_1': 0.05670796974088422, 'weight_class_2': 0.042220096544078704}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:08,159] Trial 1994 finished with value: 0.948661609048924 and parameters: {'weight_class_0': 0.006267465921941208, 'weight_class_1': 0.05768096409164735, 'weight_class_2': 0.037178325408368455}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:08,208] Trial 1996 finished with value: 0.9458560195390725 and parameters: {'weight_class_0': 0.013863233365434876, 'weight_class_1': 0.0571023462796168, 'weight_class_2': 0.07459177723537996}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:08,244] Trial 1997 finished with value: 0.9492062242370493 and parameters: {'weight_class_0': 0.0031660805888103763, 'weight_class_1': 0.09316826208192072, 'weight_class_2': 0.03983680811920397}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  67%|██████████████████████████████████████████████████████████████████████████████████████▉                                           | 2006/3000 [00:44<00:25, 38.43it/s]

[I 2026-07-03 10:57:08,254] Trial 1998 finished with value: 0.9477000308688669 and parameters: {'weight_class_0': 0.003004269764942588, 'weight_class_1': 0.1475677688613663, 'weight_class_2': 0.040436032198520926}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:08,255] Trial 2000 finished with value: 0.948627476757645 and parameters: {'weight_class_0': 0.003102108720494153, 'weight_class_1': 0.091651310819943, 'weight_class_2': 0.05685484135174799}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:08,256] Trial 1999 finished with value: 0.9492282323950366 and parameters: {'weight_class_0': 0.0032601663122388135, 'weight_class_1': 0.09322858911925033, 'weight_class_2': 0.0408578089865442}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:08,281] Trial 2001 finished with value: 0.9488491153752584 and parameters: {'weight_class_0': 0.0031721228410338136, 'weight_class_1': 0.08722865143761603, 'weight_class_2': 0.05522529991270984}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:08,283] Trial 2002 finished with value: 0.9487672420998662 and parameters: {'weight_class_0': 0.00315790091738277, 'weight_class_1': 0.09140950021475552, 'weight_class_2': 0.055465360015938193}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:08,351] Trial 2003 finished with value: 0.8707922909836862 and parameters: {'weight_class_0': 0.0033747248993741485, 'weight_class_1': 0.8746856871603051, 'weight_class_2': 0.05512372408211017}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:08,396] Trial 2004 finished with value: 0.949037684975226 and parameters: {'weight_class_0': 0.0030938149973611805, 'weight_class_1': 0.05171535916434143, 'weight_class_2': 0.05583088716190626}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:08,416] Trial 2005 finished with value: 0.9485981816696576 and parameters: {'weight_class_0': 0.003085513214888954, 'weight_class_1': 0.09019082986985932, 'weight_class_2': 0.05842322537328926}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:08,442] Trial 2006 finished with value: 0.9488730871723462 and parameters: {'weight_class_0': 0.0032562489122433605, 'weight_class_1': 0.08621408913972871, 'weight_class_2': 0.05581447842189383}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  67%|███████████████████████████████████████████████████████████████████████████████████████▎                                          | 2014/3000 [00:44<00:27, 36.40it/s]

[I 2026-07-03 10:57:08,468] Trial 2007 finished with value: 0.943724477707827 and parameters: {'weight_class_0': 0.017670380479988642, 'weight_class_1': 0.14866668215990445, 'weight_class_2': 0.05373179009925484}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:08,503] Trial 2008 finished with value: 0.9444728139073146 and parameters: {'weight_class_0': 0.01709097987361246, 'weight_class_1': 0.15972766943367975, 'weight_class_2': 0.05534816682279088}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:08,553] Trial 2010 finished with value: 0.9490117121633617 and parameters: {'weight_class_0': 0.004315972087157443, 'weight_class_1': 0.0473465740623499, 'weight_class_2': 0.07262839290919781}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:08,555] Trial 2009 finished with value: 0.7421012404466606 and parameters: {'weight_class_0': 0.004164524851634821, 'weight_class_1': 2.856330332486715, 'weight_class_2': 0.05506117084624684}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:08,573] Trial 2011 finished with value: 0.9488649229255945 and parameters: {'weight_class_0': 0.004007499530949578, 'weight_class_1': 0.04853656491723017, 'weight_class_2': 0.07393472281248344}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:08,616] Trial 2012 finished with value: 0.9477059895973623 and parameters: {'weight_class_0': 0.00439039160135848, 'weight_class_1': 0.046083652960066876, 'weight_class_2': 0.1201711855475819}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:08,641] Trial 2013 finished with value: 0.9488565067233473 and parameters: {'weight_class_0': 0.0041690627346520435, 'weight_class_1': 0.04610771762445401, 'weight_class_2': 0.075094187763467}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:08,683] Trial 2014 finished with value: 0.9489526360826958 and parameters: {'weight_class_0': 0.004181363757902074, 'weight_class_1': 0.04566050772171913, 'weight_class_2': 0.07138579542516055}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  67%|███████████████████████████████████████████████████████████████████████████████████████▌                                          | 2022/3000 [00:45<00:24, 39.47it/s]

[I 2026-07-03 10:57:08,693] Trial 2015 finished with value: 0.8930085485579182 and parameters: {'weight_class_0': 0.004363654947352155, 'weight_class_1': 0.046057578967671174, 'weight_class_2': 0.0010128325764683938}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:08,709] Trial 2016 finished with value: 0.9474006892975085 and parameters: {'weight_class_0': 0.00415657359863439, 'weight_class_1': 0.03960454821444638, 'weight_class_2': 0.12599245480412483}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:08,760] Trial 2017 finished with value: 0.9471961825799253 and parameters: {'weight_class_0': 0.004140171907303517, 'weight_class_1': 0.04586318753848381, 'weight_class_2': 0.14685806226618606}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:08,778] Trial 2019 finished with value: 0.947731338954359 and parameters: {'weight_class_0': 0.004065787942369914, 'weight_class_1': 0.046281686064466525, 'weight_class_2': 0.11849527181364043}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:08,785] Trial 2018 finished with value: 0.9488383070878755 and parameters: {'weight_class_0': 0.004494416984770362, 'weight_class_1': 0.03921888562167701, 'weight_class_2': 0.07363320467973547}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:08,827] Trial 2020 finished with value: 0.9488865769159412 and parameters: {'weight_class_0': 0.003987594604440606, 'weight_class_1': 0.0458769165586607, 'weight_class_2': 0.07165519326797769}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:08,869] Trial 2022 finished with value: 0.9479766520196881 and parameters: {'weight_class_0': 0.005605687354497949, 'weight_class_1': 0.03891651130780927, 'weight_class_2': 0.11149479437576348}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:08,872] Trial 2021 finished with value: 0.9480400242929874 and parameters: {'weight_class_0': 0.005431169436950292, 'weight_class_1': 0.03927231230254223, 'weight_class_2': 0.11022317120774715}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  68%|████████████████████████████████████████████████████████████████████████████████████████                                          | 2031/3000 [00:45<00:25, 38.46it/s]

[I 2026-07-03 10:57:08,927] Trial 2023 finished with value: 0.9181950527631345 and parameters: {'weight_class_0': 0.005356163981946466, 'weight_class_1': 0.005473927262714675, 'weight_class_2': 0.0715715037435534}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:08,950] Trial 2024 finished with value: 0.8915191530558348 and parameters: {'weight_class_0': 0.005588780241965791, 'weight_class_1': 0.04180928693869684, 'weight_class_2': 0.0010078531137773408}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:08,977] Trial 2025 finished with value: 0.9473576706557005 and parameters: {'weight_class_0': 0.005488983629443653, 'weight_class_1': 0.038780025102043, 'weight_class_2': 0.14589793616000032}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:08,992] Trial 2026 finished with value: 0.8875982712050057 and parameters: {'weight_class_0': 0.005384642736107088, 'weight_class_1': 0.0013649207036520157, 'weight_class_2': 0.04570407821460191}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:08,997] Trial 2028 finished with value: 0.9495070366562507 and parameters: {'weight_class_0': 0.005658577994403328, 'weight_class_1': 0.06512099872520331, 'weight_class_2': 0.044399290800308376}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:09,007] Trial 2027 finished with value: 0.8506099138280984 and parameters: {'weight_class_0': 0.005740864488433318, 'weight_class_1': 1.7866068724959987, 'weight_class_2': 0.14885391900941536}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:09,082] Trial 2029 finished with value: 0.9495814931279644 and parameters: {'weight_class_0': 0.005594568763881583, 'weight_class_1': 0.06290982755740919, 'weight_class_2': 0.046996271006792385}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:09,090] Trial 2030 finished with value: 0.949608804630851 and parameters: {'weight_class_0': 0.005604282369339964, 'weight_class_1': 0.06775582841722426, 'weight_class_2': 0.04635576202230148}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:09,097] Trial 2031 finished with value: 0.6878946033159079 and parameters: {'weight_class_0': 0.005633428562210009, 'weight_class_1': 0.12338756612890835, 'weight_class_2': 7.709004471780918}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:09,118] Trial 2032 finished with value: 0.9495708172914853 and parameters: {'weight_class_0': 0.005751690407805408, 'weight_class_1': 0.06315237387428635, 'weight_class_2': 0.04770333598620819}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:09,144] Trial 2033 finished with value: 0.9484274430218593 and parameters: {'weight_class_0': 0.008040163631848798, 'weight_class_1': 0.06279517126741796, 'weight_class_2': 0.04678319242294392}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:09,193] Trial 2034 finished with value: 0.9486044461856853 and parameters: {'weight_class_0': 0.008337705581329556, 'weight_class_1': 0.1294894912510611, 'weight_class_2': 0.04631014402301747}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:09,240] Trial 2036 finished with value: 0.9483156430512943 and parameters: {'weight_class_0': 0.008496989947109722, 'weight_class_1': 0.06471788397228471, 'weight_class_2': 0.04837859593052238}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:09,240] Trial 2035 finished with value: 0.9485296177720923 and parameters: {'weight_class_0': 0.008183821824525308, 'weight_class_1': 0.122754183430365, 'weight_class_2': 0.04450955407113885}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:09,272] Trial 2037 finished with value: 0.9488207294976373 and parameters: {'weight_class_0': 0.008167717721509886, 'weight_class_1': 0.12224651768990166, 'weight_class_2': 0.048961347037469544}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:09,299] Trial 2038 finished with value: 0.9482150164794735 and parameters: {'weight_class_0': 0.008414757947219244, 'weight_class_1': 0.06424429857789896, 'weight_class_2': 0.04651040169271323}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  68%|████████████████████████████████████████████████████████████████████████████████████████▋                                         | 2048/3000 [00:45<00:24, 39.28it/s]

[I 2026-07-03 10:57:09,355] Trial 2039 finished with value: 0.9485273257842589 and parameters: {'weight_class_0': 0.007897084458121126, 'weight_class_1': 0.06310435479121257, 'weight_class_2': 0.046600954556436085}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:09,366] Trial 2040 finished with value: 0.9485786966523827 and parameters: {'weight_class_0': 0.00839869520727875, 'weight_class_1': 0.12511456072783916, 'weight_class_2': 0.046200371747829955}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:09,381] Trial 2041 finished with value: 0.9494709760170941 and parameters: {'weight_class_0': 0.008025415547836296, 'weight_class_1': 0.0785095628721716, 'weight_class_2': 0.06623745947568105}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:09,396] Trial 2042 finished with value: 0.949541710874645 and parameters: {'weight_class_0': 0.008120102345490595, 'weight_class_1': 0.08142384977225461, 'weight_class_2': 0.09339716845123071}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:09,425] Trial 2043 finished with value: 0.9495876910275997 and parameters: {'weight_class_0': 0.006766277246914537, 'weight_class_1': 0.08051487879578509, 'weight_class_2': 0.08754404804321829}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:09,436] Trial 2044 finished with value: 0.8965309290743249 and parameters: {'weight_class_0': 0.07988691881232336, 'weight_class_1': 0.1271647519080276, 'weight_class_2': 0.08915642673146161}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:09,480] Trial 2046 finished with value: 0.949470428015737 and parameters: {'weight_class_0': 0.008450095289441715, 'weight_class_1': 0.08212504459114515, 'weight_class_2': 0.09155564379893481}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:09,491] Trial 2045 finished with value: 0.8535325706197826 and parameters: {'weight_class_0': 0.007658917386329568, 'weight_class_1': 0.07926283804131652, 'weight_class_2': 2.5976843071910043}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:09,520] Trial 2047 finished with value: 0.9495634053786249 and parameters: {'weight_class_0': 0.00709060319918708, 'weight_class_1': 0.07751365654775329, 'weight_class_2': 0.06638956400493375}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:09,546] Trial 2048 finished with value: 0.9484000678446489 and parameters: {'weight_class_0': 0.0036467924887107614, 'weight_class_1': 0.08132219583443223, 'weight_class_2': 0.09128686188449607}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  68%|█████████████████████████████████████████████████████████████████████████████████████████                                         | 2055/3000 [00:45<00:25, 36.76it/s]

[I 2026-07-03 10:57:09,586] Trial 2050 finished with value: 0.9482956412110201 and parameters: {'weight_class_0': 0.0035882316721600636, 'weight_class_1': 0.07808732998573728, 'weight_class_2': 0.09460450847005226}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:09,594] Trial 2049 finished with value: 0.9495615754017175 and parameters: {'weight_class_0': 0.007353119058181224, 'weight_class_1': 0.08048611696459107, 'weight_class_2': 0.08909480800211203}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:09,660] Trial 2051 finished with value: 0.9483575899157448 and parameters: {'weight_class_0': 0.003631514815564151, 'weight_class_1': 0.08344063192789627, 'weight_class_2': 0.09100153557866385}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:09,702] Trial 2052 finished with value: 0.9021719349740357 and parameters: {'weight_class_0': 0.05062095615699436, 'weight_class_1': 0.08422756160373462, 'weight_class_2': 0.06365824059430596}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:09,705] Trial 2053 finished with value: 0.8940997435778355 and parameters: {'weight_class_0': 0.04897488370562748, 'weight_class_1': 0.05510652250420079, 'weight_class_2': 0.06813831951088635}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:09,730] Trial 2055 finished with value: 0.949111966695359 and parameters: {'weight_class_0': 0.003747932144980456, 'weight_class_1': 0.05709154632924692, 'weight_class_2': 0.06581191822971844}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:09,755] Trial 2054 finished with value: 0.9489663502250408 and parameters: {'weight_class_0': 0.003552427214318125, 'weight_class_1': 0.05288128878671837, 'weight_class_2': 0.0669675384132527}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  69%|█████████████████████████████████████████████████████████████████████████████████████████▍                                        | 2064/3000 [00:46<00:24, 38.54it/s]

[I 2026-07-03 10:57:09,795] Trial 2056 finished with value: 0.949551280877568 and parameters: {'weight_class_0': 0.004736842188316973, 'weight_class_1': 0.054406945208246, 'weight_class_2': 0.06341692200440806}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:09,807] Trial 2057 finished with value: 0.9463103980322279 and parameters: {'weight_class_0': 0.012104329596873648, 'weight_class_1': 0.05380215895965052, 'weight_class_2': 0.06432070774914797}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:09,833] Trial 2058 finished with value: 0.6676461190777175 and parameters: {'weight_class_0': 0.0035337528746142394, 'weight_class_1': 6.471184659391951, 'weight_class_2': 0.06216723163314057}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:09,847] Trial 2060 finished with value: 0.9494287895342048 and parameters: {'weight_class_0': 0.004553500460361149, 'weight_class_1': 0.05010878895575457, 'weight_class_2': 0.0353396318433532}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:09,852] Trial 2059 finished with value: 0.9456873196730995 and parameters: {'weight_class_0': 0.01243834798353913, 'weight_class_1': 0.053122440416709216, 'weight_class_2': 0.06193152550572577}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:09,863] Trial 2061 finished with value: 0.9495251346683639 and parameters: {'weight_class_0': 0.004752332244040888, 'weight_class_1': 0.053090117168695536, 'weight_class_2': 0.062080011951414826}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:09,939] Trial 2062 finished with value: 0.9452900530457549 and parameters: {'weight_class_0': 0.012486592237001664, 'weight_class_1': 0.05054225125230091, 'weight_class_2': 0.06110492564234872}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:09,954] Trial 2063 finished with value: 0.9495102039549779 and parameters: {'weight_class_0': 0.0045819364735317615, 'weight_class_1': 0.05405265328178756, 'weight_class_2': 0.06301184528754229}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:10,000] Trial 2064 finished with value: 0.9462217464709206 and parameters: {'weight_class_0': 0.011642321684864133, 'weight_class_1': 0.053373612376324264, 'weight_class_2': 0.05855027818991941}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  69%|█████████████████████████████████████████████████████████████████████████████████████████▊                                        | 2073/3000 [00:46<00:24, 37.98it/s]

[I 2026-07-03 10:57:10,035] Trial 2065 finished with value: 0.9412157364435666 and parameters: {'weight_class_0': 0.012218157607496994, 'weight_class_1': 0.05490546148905422, 'weight_class_2': 0.03616943166859492}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:10,040] Trial 2066 finished with value: 0.9494927156045696 and parameters: {'weight_class_0': 0.004588971279495143, 'weight_class_1': 0.051974989190453055, 'weight_class_2': 0.03594373450280149}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:10,043] Trial 2067 finished with value: 0.9494427122111806 and parameters: {'weight_class_0': 0.004682457915911096, 'weight_class_1': 0.052981216857187284, 'weight_class_2': 0.03625357694268506}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:10,095] Trial 2069 finished with value: 0.9490473756198816 and parameters: {'weight_class_0': 0.004722599640524551, 'weight_class_1': 0.037556667952959734, 'weight_class_2': 0.03455671866357882}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:10,099] Trial 2068 finished with value: 0.8839235049592253 and parameters: {'weight_class_0': 0.03469810075760622, 'weight_class_1': 0.039141452796339564, 'weight_class_2': 0.03594511024809319}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:10,144] Trial 2070 finished with value: 0.9497113171141692 and parameters: {'weight_class_0': 0.0030203014112720927, 'weight_class_1': 0.037821455804002466, 'weight_class_2': 0.035577263293485456}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:10,145] Trial 2071 finished with value: 0.9496915001222844 and parameters: {'weight_class_0': 0.003072756622640226, 'weight_class_1': 0.04121416730706483, 'weight_class_2': 0.036099729155060815}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:10,198] Trial 2072 finished with value: 0.9496704502527323 and parameters: {'weight_class_0': 0.0030230820329193255, 'weight_class_1': 0.03700677610788383, 'weight_class_2': 0.036195586373971494}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:10,226] Trial 2073 finished with value: 0.6178780086266945 and parameters: {'weight_class_0': 0.004933931176363524, 'weight_class_1': 9.560026368063893, 'weight_class_2': 0.037145673852002965}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:10,265] Trial 2074 finished with value: 0.948579785217969 and parameters: {'weight_class_0': 0.006362122324156007, 'weight_class_1': 0.10051530227197464, 'weight_class_2': 0.03520299932652004}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:10,276] Trial 2075 finished with value: 0.9198643383208794 and parameters: {'weight_class_0': 0.010062230334376426, 'weight_class_1': 1.312118121862468, 'weight_class_2': 0.03801878810581506}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:10,299] Trial 2076 finished with value: 0.9496473366723758 and parameters: {'weight_class_0': 0.0029460242375043957, 'weight_class_1': 0.03807477016274055, 'weight_class_2': 0.03761236275388607}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:10,343] Trial 2077 finished with value: 0.9480811104185983 and parameters: {'weight_class_0': 0.0030267880262692197, 'weight_class_1': 0.03818581817722554, 'weight_class_2': 0.08019129233814633}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:10,361] Trial 2078 finished with value: 0.9481553852407192 and parameters: {'weight_class_0': 0.002953348294065473, 'weight_class_1': 0.037648168273676244, 'weight_class_2': 0.07682844066850816}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:10,405] Trial 2080 finished with value: 0.8693813662977942 and parameters: {'weight_class_0': 0.1054408383930381, 'weight_class_1': 0.1001005288096014, 'weight_class_2': 0.0773977484649476}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:10,405] Trial 2079 finished with value: 0.9490608830345142 and parameters: {'weight_class_0': 0.0031546092177936968, 'weight_class_1': 0.10195813317102512, 'weight_class_2': 0.0405703306597597}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:10,444] Trial 2081 finished with value: 0.9495785808667024 and parameters: {'weight_class_0': 0.003532208325877006, 'weight_class_1': 0.038932370123642736, 'weight_class_2': 0.04110022194926147}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  70%|██████████████████████████████████████████████████████████████████████████████████████████▌                                       | 2090/3000 [00:46<00:23, 39.01it/s]

[I 2026-07-03 10:57:10,444] Trial 2082 finished with value: 0.9485212724211131 and parameters: {'weight_class_0': 0.0029999822750284384, 'weight_class_1': 0.1004135147213564, 'weight_class_2': 0.05381439533191359}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:10,449] Trial 2083 finished with value: 0.9494980479039378 and parameters: {'weight_class_0': 0.0029328750998618832, 'weight_class_1': 0.03783415104469364, 'weight_class_2': 0.041233274685674996}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:10,500] Trial 2085 finished with value: 0.6571807549247958 and parameters: {'weight_class_0': 9.622546048850678, 'weight_class_1': 0.10193145499158439, 'weight_class_2': 0.05259952616548252}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:10,524] Trial 2084 finished with value: 0.9494050724864723 and parameters: {'weight_class_0': 0.0038411695063641092, 'weight_class_1': 0.03885718054425406, 'weight_class_2': 0.05182660196693076}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:10,570] Trial 2086 finished with value: 0.9494033502037099 and parameters: {'weight_class_0': 0.003812882394163136, 'weight_class_1': 0.038682006074032674, 'weight_class_2': 0.05113440206070571}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:10,576] Trial 2087 finished with value: 0.9495177568773941 and parameters: {'weight_class_0': 0.003665020788220671, 'weight_class_1': 0.06722144847277949, 'weight_class_2': 0.04827346851617641}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:10,587] Trial 2088 finished with value: 0.9494417141340068 and parameters: {'weight_class_0': 0.0034959551447744353, 'weight_class_1': 0.0677622090178685, 'weight_class_2': 0.051440156915985864}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:10,638] Trial 2089 finished with value: 0.9495655058357597 and parameters: {'weight_class_0': 0.0037934146702422017, 'weight_class_1': 0.06610761706433187, 'weight_class_2': 0.05051629809386092}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:10,644] Trial 2090 finished with value: 0.949519817560752 and parameters: {'weight_class_0': 0.003887931052283095, 'weight_class_1': 0.06621578702383642, 'weight_class_2': 0.052445982267961384}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:10,744] Trial 2092 finished with value: 0.9494899371001178 and parameters: {'weight_class_0': 0.00615283170656877, 'weight_class_1': 0.06503869721562033, 'weight_class_2': 0.05108117885029329}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:10,748] Trial 2093 finished with value: 0.9495529792742795 and parameters: {'weight_class_0': 0.003918536244274696, 'weight_class_1': 0.06944299202489118, 'weight_class_2': 0.05098937078064395}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:10,754] Trial 2091 finished with value: 0.9495248004105507 and parameters: {'weight_class_0': 0.0038186066125597447, 'weight_class_1': 0.06393137984029718, 'weight_class_2': 0.05233419582588252}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:10,782] Trial 2094 finished with value: 0.9495467721769414 and parameters: {'weight_class_0': 0.003930153870038413, 'weight_class_1': 0.06654875632225171, 'weight_class_2': 0.0524849228830005}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:10,826] Trial 2097 finished with value: 0.9495910100060504 and parameters: {'weight_class_0': 0.004085411092788919, 'weight_class_1': 0.06694607340995205, 'weight_class_2': 0.05215858619731804}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:10,829] Trial 2095 finished with value: 0.9495794999055146 and parameters: {'weight_class_0': 0.004008707595009448, 'weight_class_1': 0.06637893923291159, 'weight_class_2': 0.05085328604897277}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:10,831] Trial 2096 finished with value: 0.9495965007340139 and parameters: {'weight_class_0': 0.0062439186700740034, 'weight_class_1': 0.06876298678816115, 'weight_class_2': 0.05294200889436152}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:10,901] Trial 2100 finished with value: 0.9487984409869618 and parameters: {'weight_class_0': 0.005913712134688812, 'weight_class_1': 0.06675411758615164, 'weight_class_2': 0.1111208029599873}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:10,901] Trial 2099 finished with value: 0.9489432093305753 and parameters: {'weight_class_0': 0.006483641647241334, 'weight_class_1': 0.06543334467749706, 'weight_class_2': 0.1098870788947711}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:10,915] Trial 2101 finished with value: 0.9492590998490336 and parameters: {'weight_class_0': 0.0058607179814521605, 'weight_class_1': 0.0480825563012742, 'weight_class_2': 0.07257677048811105}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  70%|███████████████████████████████████████████████████████████████████████████████████████████▎                                      | 2107/3000 [00:47<00:24, 36.43it/s]

[I 2026-07-03 10:57:10,918] Trial 2098 finished with value: 0.9488165644778058 and parameters: {'weight_class_0': 0.006148843933545353, 'weight_class_1': 0.0661013923791445, 'weight_class_2': 0.10963445402045467}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:10,926] Trial 2102 finished with value: 0.9482460999114785 and parameters: {'weight_class_0': 0.006282846544280248, 'weight_class_1': 0.04494831467466507, 'weight_class_2': 0.11210571944513047}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:10,998] Trial 2103 finished with value: 0.9482178223046883 and parameters: {'weight_class_0': 0.006170099835617558, 'weight_class_1': 0.04598023916449524, 'weight_class_2': 0.11331560736774463}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:11,018] Trial 2104 finished with value: 0.9483817833677981 and parameters: {'weight_class_0': 0.006185577734667803, 'weight_class_1': 0.047542919123368485, 'weight_class_2': 0.11091810544023852}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:11,087] Trial 2105 finished with value: 0.9491662768597934 and parameters: {'weight_class_0': 0.006173768481851362, 'weight_class_1': 0.04966220586936484, 'weight_class_2': 0.0807106160842245}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:11,126] Trial 2106 finished with value: 0.9491353024007774 and parameters: {'weight_class_0': 0.005106405907724222, 'weight_class_1': 0.04612413432633489, 'weight_class_2': 0.07620592538895266}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:11,136] Trial 2107 finished with value: 0.9482477662601166 and parameters: {'weight_class_0': 0.005180179293865712, 'weight_class_1': 0.04653130629300739, 'weight_class_2': 0.1092332522797463}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  71%|███████████████████████████████████████████████████████████████████████████████████████████▋                                      | 2117/3000 [00:47<00:22, 39.67it/s]

[I 2026-07-03 10:57:11,161] Trial 2109 finished with value: 0.9491299227722806 and parameters: {'weight_class_0': 0.005020206560479547, 'weight_class_1': 0.046469347986744056, 'weight_class_2': 0.07536540639941207}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:11,187] Trial 2108 finished with value: 0.9480642025813389 and parameters: {'weight_class_0': 0.005055993735701968, 'weight_class_1': 0.044104550877366366, 'weight_class_2': 0.1112883906266686}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:11,211] Trial 2110 finished with value: 0.949545340746555 and parameters: {'weight_class_0': 0.004898361723001692, 'weight_class_1': 0.043068306541429326, 'weight_class_2': 0.041731048396602057}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:11,240] Trial 2111 finished with value: 0.9494645226725996 and parameters: {'weight_class_0': 0.005086515878341226, 'weight_class_1': 0.049748245187843584, 'weight_class_2': 0.04138628434096083}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:11,258] Trial 2112 finished with value: 0.9478610432616388 and parameters: {'weight_class_0': 0.009764775389194073, 'weight_class_1': 0.047046097745389, 'weight_class_2': 0.07697609331883985}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:11,268] Trial 2114 finished with value: 0.9494924911334737 and parameters: {'weight_class_0': 0.005048755025912375, 'weight_class_1': 0.04665157482177514, 'weight_class_2': 0.04109225953234518}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:11,274] Trial 2113 finished with value: 0.9495161535790517 and parameters: {'weight_class_0': 0.00497588072116314, 'weight_class_1': 0.04678637321570493, 'weight_class_2': 0.04190751987848097}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:11,317] Trial 2115 finished with value: 0.9496277925217141 and parameters: {'weight_class_0': 0.00491946242702838, 'weight_class_1': 0.0912874850634923, 'weight_class_2': 0.04195024922841348}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:11,325] Trial 2116 finished with value: 0.9495001659036543 and parameters: {'weight_class_0': 0.009755503308876654, 'weight_class_1': 0.09172289361130775, 'weight_class_2': 0.08074994355378488}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:11,426] Trial 2117 finished with value: 0.9486357570023957 and parameters: {'weight_class_0': 0.004811461624434398, 'weight_class_1': 0.18096044545487888, 'weight_class_2': 0.042028280072234116}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:11,434] Trial 2118 finished with value: 0.9472980066567337 and parameters: {'weight_class_0': 0.00465570262624952, 'weight_class_1': 0.2387748105148228, 'weight_class_2': 0.04285442461506267}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:11,478] Trial 2119 finished with value: 0.949587727642208 and parameters: {'weight_class_0': 0.004790829699135548, 'weight_class_1': 0.09048610938579095, 'weight_class_2': 0.042651496576067635}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:11,486] Trial 2120 finished with value: 0.9495548019830138 and parameters: {'weight_class_0': 0.004411672210715281, 'weight_class_1': 0.09211862998062917, 'weight_class_2': 0.04088667313363038}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:11,504] Trial 2122 finished with value: 0.9496743870577715 and parameters: {'weight_class_0': 0.004545094095561209, 'weight_class_1': 0.0563029742027572, 'weight_class_2': 0.04246665343397642}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:11,511] Trial 2121 finished with value: 0.9495757200822039 and parameters: {'weight_class_0': 0.004563681387775239, 'weight_class_1': 0.08521396624514865, 'weight_class_2': 0.04049835671195918}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:11,534] Trial 2123 finished with value: 0.9473828492196454 and parameters: {'weight_class_0': 0.009696187196957022, 'weight_class_1': 0.08862334804149315, 'weight_class_2': 0.043006249022400245}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:11,565] Trial 2124 finished with value: 0.9483720295585436 and parameters: {'weight_class_0': 0.00296554671378225, 'weight_class_1': 0.09159606496068044, 'weight_class_2': 0.0627700404001249}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:11,590] Trial 2125 finished with value: 0.9496421932212887 and parameters: {'weight_class_0': 0.0073567202023029025, 'weight_class_1': 0.08784675338947097, 'weight_class_2': 0.06321377308560129}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  71%|████████████████████████████████████████████████████████████████████████████████████████████▍                                     | 2133/3000 [00:47<00:22, 38.16it/s]

[I 2026-07-03 10:57:11,606] Trial 2126 finished with value: 0.9449598662372874 and parameters: {'weight_class_0': 0.0030422436700250255, 'weight_class_1': 0.19708790744665808, 'weight_class_2': 0.0622629824287135}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:11,631] Trial 2128 finished with value: 0.8084050328836776 and parameters: {'weight_class_0': 1.0767672771352448, 'weight_class_1': 0.05718314080344701, 'weight_class_2': 0.06143715614641389}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:11,638] Trial 2127 finished with value: 0.948556526347236 and parameters: {'weight_class_0': 0.003062127620543689, 'weight_class_1': 0.08583393226122787, 'weight_class_2': 0.06324932878256442}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:11,718] Trial 2129 finished with value: 0.9485009885815412 and parameters: {'weight_class_0': 0.002962936756814276, 'weight_class_1': 0.07847296364783354, 'weight_class_2': 0.0637385753338113}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:11,721] Trial 2130 finished with value: 0.9495918670582407 and parameters: {'weight_class_0': 0.007340274051058426, 'weight_class_1': 0.08653614568515615, 'weight_class_2': 0.06115374551208305}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:11,781] Trial 2131 finished with value: 0.9485933972234376 and parameters: {'weight_class_0': 0.0030504119915803073, 'weight_class_1': 0.08091622571329664, 'weight_class_2': 0.06272390479407873}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:11,799] Trial 2132 finished with value: 0.9490233231140878 and parameters: {'weight_class_0': 0.003431856298330036, 'weight_class_1': 0.05776421920732741, 'weight_class_2': 0.061789167868471086}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:11,830] Trial 2134 finished with value: 0.9488281292142733 and parameters: {'weight_class_0': 0.0029577197825265836, 'weight_class_1': 0.0571172761608959, 'weight_class_2': 0.060926580495746126}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:11,883] Trial 2133 finished with value: 0.9496291639316469 and parameters: {'weight_class_0': 0.0071178323063384305, 'weight_class_1': 0.1203217749565971, 'weight_class_2': 0.06231755435570956}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:11,885] Trial 2135 finished with value: 0.9473972131164369 and parameters: {'weight_class_0': 0.007245255549021035, 'weight_class_1': 0.056154253808894744, 'weight_class_2': 0.03327048942748353}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:11,895] Trial 2136 finished with value: 0.9488998223110544 and parameters: {'weight_class_0': 0.002957384113370494, 'weight_class_1': 0.05704739675218685, 'weight_class_2': 0.05917080262884106}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:11,895] Trial 2137 finished with value: 0.9450243595855086 and parameters: {'weight_class_0': 0.002966245586005234, 'weight_class_1': 0.06006998483916999, 'weight_class_2': 0.21185663222734472}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:11,944] Trial 2138 finished with value: 0.9476400396933604 and parameters: {'weight_class_0': 0.007285264876807566, 'weight_class_1': 0.11875908029716571, 'weight_class_2': 0.03296236801226651}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:11,972] Trial 2139 finished with value: 0.9476127311797562 and parameters: {'weight_class_0': 0.0072133403603132406, 'weight_class_1': 0.0575685152252754, 'weight_class_2': 0.03396002574199953}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:11,979] Trial 2140 finished with value: 0.9466638891797642 and parameters: {'weight_class_0': 0.00764923755110232, 'weight_class_1': 0.05987591796300974, 'weight_class_2': 0.031935334460463816}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:12,034] Trial 2141 finished with value: 0.9495240892992941 and parameters: {'weight_class_0': 0.007142982686159023, 'weight_class_1': 0.15420351601892462, 'weight_class_2': 0.07712527932561408}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:12,046] Trial 2142 finished with value: 0.947152684818661 and parameters: {'weight_class_0': 0.007417848774923648, 'weight_class_1': 0.12497701587025668, 'weight_class_2': 0.0317212565149191}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:12,049] Trial 2143 finished with value: 0.9496424468442676 and parameters: {'weight_class_0': 0.003859970482207076, 'weight_class_1': 0.05692393765810005, 'weight_class_2': 0.03310098256109225}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:12,083] Trial 2144 finished with value: 0.9478055837207667 and parameters: {'weight_class_0': 0.007213527747915558, 'weight_class_1': 0.11169130821880109, 'weight_class_2': 0.03364049735139594}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:12,159] Trial 2145 finished with value: 0.9462689058742285 and parameters: {'weight_class_0': 0.007192944545604924, 'weight_class_1': 0.03747385039233918, 'weight_class_2': 0.20487788746784796}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:12,208] Trial 2146 finished with value: 0.9481294959854778 and parameters: {'weight_class_0': 0.004034083896701127, 'weight_class_1': 0.038704616872288496, 'weight_class_2': 0.09031183887778257}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:12,209] Trial 2147 finished with value: 0.9486793541168469 and parameters: {'weight_class_0': 0.004162098148507696, 'weight_class_1': 0.1100480373432824, 'weight_class_2': 0.08279384670637654}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:12,214] Trial 2148 finished with value: 0.948551104276636 and parameters: {'weight_class_0': 0.0038517744249506555, 'weight_class_1': 0.15046271841553524, 'weight_class_2': 0.032601646783899506}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:12,245] Trial 2149 finished with value: 0.9484735510861168 and parameters: {'weight_class_0': 0.003995801949694438, 'weight_class_1': 0.03787019262805505, 'weight_class_2': 0.07779180153106463}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  72%|█████████████████████████████████████████████████████████████████████████████████████████████▍                                    | 2157/3000 [00:48<00:21, 40.12it/s]

[I 2026-07-03 10:57:12,248] Trial 2150 finished with value: 0.9486007167752746 and parameters: {'weight_class_0': 0.003959027268555877, 'weight_class_1': 0.039604637219798164, 'weight_class_2': 0.07633164146092879}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:12,297] Trial 2151 finished with value: 0.9486148782951253 and parameters: {'weight_class_0': 0.003997621964708533, 'weight_class_1': 0.038338630995424894, 'weight_class_2': 0.07286907638810476}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:12,302] Trial 2152 finished with value: 0.9486468296932459 and parameters: {'weight_class_0': 0.00406160651679308, 'weight_class_1': 0.03706691776542886, 'weight_class_2': 0.07219132217777176}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:12,338] Trial 2153 finished with value: 0.9481078272483389 and parameters: {'weight_class_0': 0.0041012508039729645, 'weight_class_1': 0.039865406896455596, 'weight_class_2': 0.09331678372539004}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:12,338] Trial 2154 finished with value: 0.9480002867371091 and parameters: {'weight_class_0': 0.004075411056238645, 'weight_class_1': 0.03661186399426319, 'weight_class_2': 0.0943508768579453}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:12,381] Trial 2155 finished with value: 0.948075388822478 and parameters: {'weight_class_0': 0.004084807765011247, 'weight_class_1': 0.04104195340965121, 'weight_class_2': 0.09668326194889197}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:12,397] Trial 2156 finished with value: 0.94799634902718 and parameters: {'weight_class_0': 0.00406741315187115, 'weight_class_1': 0.03661395011314526, 'weight_class_2': 0.09428160710248713}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:12,451] Trial 2157 finished with value: 0.9482834461216728 and parameters: {'weight_class_0': 0.0037247170637810054, 'weight_class_1': 0.03710099130628949, 'weight_class_2': 0.08053412011018897}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  72%|█████████████████████████████████████████████████████████████████████████████████████████████▊                                    | 2166/3000 [00:48<00:22, 37.66it/s]

[I 2026-07-03 10:57:12,509] Trial 2158 finished with value: 0.9495929524399923 and parameters: {'weight_class_0': 0.005578010872027205, 'weight_class_1': 0.07289154868227998, 'weight_class_2': 0.0746224544228804}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:12,550] Trial 2160 finished with value: 0.9496397129913788 and parameters: {'weight_class_0': 0.0055385553411547534, 'weight_class_1': 0.07646708113037115, 'weight_class_2': 0.048900660398071026}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:12,571] Trial 2159 finished with value: 0.9496707686581224 and parameters: {'weight_class_0': 0.0057342492196201566, 'weight_class_1': 0.07212159769046966, 'weight_class_2': 0.04866073915886497}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:12,576] Trial 2161 finished with value: 0.9496363018310298 and parameters: {'weight_class_0': 0.00589234179760517, 'weight_class_1': 0.07459289875354734, 'weight_class_2': 0.04848523184098339}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:12,615] Trial 2162 finished with value: 0.9475108631156287 and parameters: {'weight_class_0': 0.0058434275109587085, 'weight_class_1': 0.29181269698202394, 'weight_class_2': 0.04968383432012591}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:12,644] Trial 2163 finished with value: 0.949634397310354 and parameters: {'weight_class_0': 0.005627857819076821, 'weight_class_1': 0.07370013399691736, 'weight_class_2': 0.05136652729860268}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:12,655] Trial 2164 finished with value: 0.9495011517528172 and parameters: {'weight_class_0': 0.005969338819838087, 'weight_class_1': 0.07088179897949619, 'weight_class_2': 0.047237151683206274}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:12,666] Trial 2165 finished with value: 0.9496306888262308 and parameters: {'weight_class_0': 0.005688202661258881, 'weight_class_1': 0.07445958919631547, 'weight_class_2': 0.05157765765488117}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:12,682] Trial 2166 finished with value: 0.9496928069882453 and parameters: {'weight_class_0': 0.005642173881127066, 'weight_class_1': 0.07034635934116239, 'weight_class_2': 0.048816396810396324}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:12,699] Trial 2167 finished with value: 0.94961279969863 and parameters: {'weight_class_0': 0.006302348403074559, 'weight_class_1': 0.07530671019395573, 'weight_class_2': 0.0515375214554088}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:12,712] Trial 2169 finished with value: 0.9496305800626278 and parameters: {'weight_class_0': 0.006037468066389609, 'weight_class_1': 0.0765302431296616, 'weight_class_2': 0.05049980984268295}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:12,721] Trial 2168 finished with value: 0.949643190962079 and parameters: {'weight_class_0': 0.005839410364467946, 'weight_class_1': 0.07421368334404928, 'weight_class_2': 0.04890623455111334}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:12,745] Trial 2170 finished with value: 0.9496452161712964 and parameters: {'weight_class_0': 0.005688342193930522, 'weight_class_1': 0.07676651143686805, 'weight_class_2': 0.04811859738741688}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:12,816] Trial 2171 finished with value: 0.9496123889877991 and parameters: {'weight_class_0': 0.005668909177247528, 'weight_class_1': 0.07314032952366976, 'weight_class_2': 0.047616233217200064}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:12,904] Trial 2172 finished with value: 0.9472664851089033 and parameters: {'weight_class_0': 0.009750093776028161, 'weight_class_1': 0.05137919453196555, 'weight_class_2': 0.05313645653588659}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:12,906] Trial 2174 finished with value: 0.9477246369795694 and parameters: {'weight_class_0': 0.009233650795831303, 'weight_class_1': 0.051522946449547295, 'weight_class_2': 0.05554800125370512}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:12,907] Trial 2173 finished with value: 0.9493264472697094 and parameters: {'weight_class_0': 0.0034323601381270608, 'weight_class_1': 0.0507780072812695, 'weight_class_2': 0.05334646545141663}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:12,937] Trial 2175 finished with value: 0.9452626749319224 and parameters: {'weight_class_0': 0.010025449442662364, 'weight_class_1': 0.05397570317772865, 'weight_class_2': 0.03905346578472695}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:12,981] Trial 2176 finished with value: 0.9452858268700437 and parameters: {'weight_class_0': 0.009813595994058134, 'weight_class_1': 0.05100969399124365, 'weight_class_2': 0.039134115937241656}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:13,001] Trial 2178 finished with value: 0.9442696848740532 and parameters: {'weight_class_0': 0.010616696844530735, 'weight_class_1': 0.051413352358856, 'weight_class_2': 0.03891725190003756}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:13,010] Trial 2177 finished with value: 0.9457666982614249 and parameters: {'weight_class_0': 0.009346993490196803, 'weight_class_1': 0.05221648215646575, 'weight_class_2': 0.038676032477687264}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:13,045] Trial 2180 finished with value: 0.9443175956103481 and parameters: {'weight_class_0': 0.01005768431178958, 'weight_class_1': 0.050629113664198956, 'weight_class_2': 0.03642180268523132}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:13,052] Trial 2179 finished with value: 0.8822952382040868 and parameters: {'weight_class_0': 0.009491792260246698, 'weight_class_1': 0.0020984427784045525, 'weight_class_2': 0.03815585232983435}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:13,109] Trial 2182 finished with value: 0.9481315407116249 and parameters: {'weight_class_0': 0.009458139573149222, 'weight_class_1': 0.05487542500840904, 'weight_class_2': 0.13433410099133122}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:13,113] Trial 2181 finished with value: 0.9478107421414687 and parameters: {'weight_class_0': 0.009403018159264661, 'weight_class_1': 0.04905542665432399, 'weight_class_2': 0.1386898562553799}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  73%|██████████████████████████████████████████████████████████████████████████████████████████████▊                                   | 2189/3000 [00:49<00:23, 35.20it/s]

[I 2026-07-03 10:57:13,148] Trial 2183 finished with value: 0.9496541642048486 and parameters: {'weight_class_0': 0.0033287709819237667, 'weight_class_1': 0.05113553288890173, 'weight_class_2': 0.03786593453625967}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:13,223] Trial 2184 finished with value: 0.8354781204682565 and parameters: {'weight_class_0': 0.14670494336616, 'weight_class_1': 0.10116395446982442, 'weight_class_2': 0.00212631343769714}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:13,242] Trial 2186 finished with value: 0.9490912413450001 and parameters: {'weight_class_0': 0.0032705647360111684, 'weight_class_1': 0.10582418905737397, 'weight_class_2': 0.03659424722733251}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:13,263] Trial 2185 finished with value: 0.9492080638927968 and parameters: {'weight_class_0': 0.0034312724772321075, 'weight_class_1': 0.09941540409528266, 'weight_class_2': 0.03678807789524157}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:13,305] Trial 2187 finished with value: 0.9492954424045053 and parameters: {'weight_class_0': 0.004681627691451312, 'weight_class_1': 0.10090143979469791, 'weight_class_2': 0.07111168975233699}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:13,323] Trial 2188 finished with value: 0.8402351201665086 and parameters: {'weight_class_0': 0.25354368698564816, 'weight_class_1': 0.09971505745365024, 'weight_class_2': 0.06847866720063718}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:13,357] Trial 2189 finished with value: 0.947496136378518 and parameters: {'weight_class_0': 0.0035023320999983155, 'weight_class_1': 0.09872118123086279, 'weight_class_2': 0.1284461336236769}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  73%|███████████████████████████████████████████████████████████████████████████████████████████████▏                                  | 2197/3000 [00:49<00:22, 36.20it/s]

[I 2026-07-03 10:57:13,372] Trial 2191 finished with value: 0.9484347993765403 and parameters: {'weight_class_0': 0.0033141806219668998, 'weight_class_1': 0.09831748368379045, 'weight_class_2': 0.07016669312467778}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:13,386] Trial 2190 finished with value: 0.9484050695222509 and parameters: {'weight_class_0': 0.00337594857467784, 'weight_class_1': 0.10388310486788202, 'weight_class_2': 0.07064214702216727}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:13,388] Trial 2192 finished with value: 0.9493332465267302 and parameters: {'weight_class_0': 0.004746383564127036, 'weight_class_1': 0.10216316714167481, 'weight_class_2': 0.07113815222650537}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:13,431] Trial 2194 finished with value: 0.9492307607643479 and parameters: {'weight_class_0': 0.00463378733205241, 'weight_class_1': 0.09771404311490421, 'weight_class_2': 0.07469909260278355}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:13,432] Trial 2193 finished with value: 0.9491246073272994 and parameters: {'weight_class_0': 0.0047500252804072735, 'weight_class_1': 0.09736910028787706, 'weight_class_2': 0.08181996253284064}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:13,477] Trial 2195 finished with value: 0.9493003207029681 and parameters: {'weight_class_0': 0.004818150515065736, 'weight_class_1': 0.10896850260015362, 'weight_class_2': 0.06734569698627625}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:13,522] Trial 2196 finished with value: 0.9494157667728796 and parameters: {'weight_class_0': 0.004923523704379048, 'weight_class_1': 0.09652404813039142, 'weight_class_2': 0.06989565587195012}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:13,552] Trial 2197 finished with value: 0.8860335157417478 and parameters: {'weight_class_0': 0.004729467531544964, 'weight_class_1': 0.0011312021182508913, 'weight_class_2': 0.07392399364801085}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  74%|███████████████████████████████████████████████████████████████████████████████████████████████▌                                  | 2206/3000 [00:49<00:22, 34.68it/s]

[I 2026-07-03 10:57:13,627] Trial 2198 finished with value: 0.9494215662847778 and parameters: {'weight_class_0': 0.004481669198089027, 'weight_class_1': 0.061870139327688416, 'weight_class_2': 0.06529370166164308}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:13,642] Trial 2199 finished with value: 0.9378740884868244 and parameters: {'weight_class_0': 0.004829154860412913, 'weight_class_1': 0.0448082582839418, 'weight_class_2': 0.5634567229623219}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:13,647] Trial 2200 finished with value: 0.9489370257462655 and parameters: {'weight_class_0': 0.004622243581647951, 'weight_class_1': 0.05939733864412656, 'weight_class_2': 0.08545583950007075}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:13,677] Trial 2201 finished with value: 0.9489764115784816 and parameters: {'weight_class_0': 0.0047052901318679, 'weight_class_1': 0.06207090877522269, 'weight_class_2': 0.08619633610804107}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:13,709] Trial 2202 finished with value: 0.9479146388144732 and parameters: {'weight_class_0': 0.0028295077908103415, 'weight_class_1': 0.06123281626355311, 'weight_class_2': 0.0894437909168337}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:13,710] Trial 2203 finished with value: 0.9487993479647266 and parameters: {'weight_class_0': 0.004653352482274991, 'weight_class_1': 0.061231155158156726, 'weight_class_2': 0.0941168182907827}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:13,747] Trial 2205 finished with value: 0.949651047772759 and parameters: {'weight_class_0': 0.004411163688118581, 'weight_class_1': 0.06131669679845433, 'weight_class_2': 0.05700903129307017}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:13,748] Trial 2204 finished with value: 0.9494916104341372 and parameters: {'weight_class_0': 0.0027037482921967674, 'weight_class_1': 0.06147289991261911, 'weight_class_2': 0.031676572058106936}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:13,793] Trial 2206 finished with value: 0.9486916347013965 and parameters: {'weight_class_0': 0.00449557984443484, 'weight_class_1': 0.06174061195809841, 'weight_class_2': 0.09545521073425442}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  74%|███████████████████████████████████████████████████████████████████████████████████████████████▉                                  | 2214/3000 [00:50<00:21, 36.00it/s]

[I 2026-07-03 10:57:13,800] Trial 2207 finished with value: 0.9488070464868409 and parameters: {'weight_class_0': 0.002824881036460053, 'weight_class_1': 0.06103835783941225, 'weight_class_2': 0.058814628778244074}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:13,800] Trial 2208 finished with value: 0.9486351562825356 and parameters: {'weight_class_0': 0.0028037138709580945, 'weight_class_1': 0.06692371106246323, 'weight_class_2': 0.05965438928841466}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:13,842] Trial 2209 finished with value: 0.9488040619689353 and parameters: {'weight_class_0': 0.002778544343527356, 'weight_class_1': 0.05943356157205467, 'weight_class_2': 0.057654307410384874}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:13,919] Trial 2210 finished with value: 0.9487933051587816 and parameters: {'weight_class_0': 0.002766428785502796, 'weight_class_1': 0.043738128709253664, 'weight_class_2': 0.057431866221822024}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:13,930] Trial 2211 finished with value: 0.9488245794140094 and parameters: {'weight_class_0': 0.0028134670506016236, 'weight_class_1': 0.042437605784276244, 'weight_class_2': 0.05709605169417188}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:13,963] Trial 2212 finished with value: 0.9488543848757409 and parameters: {'weight_class_0': 0.0069528905436494395, 'weight_class_1': 0.043261724917547935, 'weight_class_2': 0.056982667381304815}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:14,003] Trial 2213 finished with value: 0.9446391121700198 and parameters: {'weight_class_0': 0.0027379937078054013, 'weight_class_1': 0.13935361012005051, 'weight_class_2': 0.16852209599519724}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:14,009] Trial 2214 finished with value: 0.9457968141146657 and parameters: {'weight_class_0': 0.0027632423070537144, 'weight_class_1': 0.0427743648862115, 'weight_class_2': 0.16676414327382721}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  74%|████████████████████████████████████████████████████████████████████████████████████████████████▎                                 | 2222/3000 [00:50<00:21, 35.44it/s]

[I 2026-07-03 10:57:14,071] Trial 2216 finished with value: 0.9488814225012584 and parameters: {'weight_class_0': 0.006924839084829411, 'weight_class_1': 0.04349971933464135, 'weight_class_2': 0.05871275750504758}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:14,073] Trial 2215 finished with value: 0.9486658450395836 and parameters: {'weight_class_0': 0.007027835860398887, 'weight_class_1': 0.041165820987670666, 'weight_class_2': 0.059505416544433136}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:14,115] Trial 2217 finished with value: 0.9482869745720247 and parameters: {'weight_class_0': 0.006983892418021857, 'weight_class_1': 0.045608424897497064, 'weight_class_2': 0.04421790673826307}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:14,132] Trial 2218 finished with value: 0.9479773848462935 and parameters: {'weight_class_0': 0.0070935124891497656, 'weight_class_1': 0.043275462156063586, 'weight_class_2': 0.042557889315977225}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:14,156] Trial 2219 finished with value: 0.9478491046316808 and parameters: {'weight_class_0': 0.007576058725512675, 'weight_class_1': 0.04426675612077411, 'weight_class_2': 0.04505481481767957}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:14,174] Trial 2220 finished with value: 0.9476516961270728 and parameters: {'weight_class_0': 0.0074389492037692986, 'weight_class_1': 0.04237968017592708, 'weight_class_2': 0.042471135416155964}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:14,221] Trial 2221 finished with value: 0.9482892428363843 and parameters: {'weight_class_0': 0.006924634006506208, 'weight_class_1': 0.045278636474372025, 'weight_class_2': 0.04427474207139563}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:14,240] Trial 2222 finished with value: 0.9472089884264375 and parameters: {'weight_class_0': 0.007182009360798686, 'weight_class_1': 0.04265161415681152, 'weight_class_2': 0.1639011441139032}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:14,252] Trial 2223 finished with value: 0.9476303580035205 and parameters: {'weight_class_0': 0.0067208635062604005, 'weight_class_1': 0.03534212432340803, 'weight_class_2': 0.04245237591506559}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:14,261] Trial 2224 finished with value: 0.9477260992142987 and parameters: {'weight_class_0': 0.006731002001215028, 'weight_class_1': 0.03613102870735717, 'weight_class_2': 0.04252236479946012}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:14,300] Trial 2225 finished with value: 0.8956652853757373 and parameters: {'weight_class_0': 0.006702953820712475, 'weight_class_1': 0.03520007837455141, 'weight_class_2': 0.003003359332465171}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:14,323] Trial 2226 finished with value: 0.7398404922501441 and parameters: {'weight_class_0': 0.007349756981417456, 'weight_class_1': 4.493364913215127, 'weight_class_2': 0.04433878941955137}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:14,363] Trial 2227 finished with value: 0.9494733802486551 and parameters: {'weight_class_0': 0.003600240100138017, 'weight_class_1': 0.08182601504909102, 'weight_class_2': 0.04276689958461039}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:14,426] Trial 2228 finished with value: 0.9132845868662259 and parameters: {'weight_class_0': 0.0037965928996445413, 'weight_class_1': 0.07831460407682429, 'weight_class_2': 0.00403608429337382}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:14,427] Trial 2229 finished with value: 0.9495174862171717 and parameters: {'weight_class_0': 0.0036275737278161375, 'weight_class_1': 0.08014255524187162, 'weight_class_2': 0.03134550529022789}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:14,456] Trial 2230 finished with value: 0.9494632209127553 and parameters: {'weight_class_0': 0.0036526591748534277, 'weight_class_1': 0.08194112005058825, 'weight_class_2': 0.03306306596699024}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:14,483] Trial 2231 finished with value: 0.9494230300919072 and parameters: {'weight_class_0': 0.003477412951422321, 'weight_class_1': 0.0815626544444944, 'weight_class_2': 0.043076646195783615}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:14,528] Trial 2232 finished with value: 0.9261873890788014 and parameters: {'weight_class_0': 0.003497674417682152, 'weight_class_1': 0.08192385621941102, 'weight_class_2': 0.005405846700372578}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:14,578] Trial 2233 finished with value: 0.9488219466082595 and parameters: {'weight_class_0': 0.005498441930704941, 'weight_class_1': 0.08157140245276388, 'weight_class_2': 0.0328229383041701}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:14,587] Trial 2234 finished with value: 0.949485287921803 and parameters: {'weight_class_0': 0.0035845359330058707, 'weight_class_1': 0.07839658884735677, 'weight_class_2': 0.033116880140914816}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:14,611] Trial 2236 finished with value: 0.949488346345951 and parameters: {'weight_class_0': 0.00355728853266616, 'weight_class_1': 0.07818526321576352, 'weight_class_2': 0.03235303013402785}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:14,614] Trial 2237 finished with value: 0.9493866624627026 and parameters: {'weight_class_0': 0.0034776505975033724, 'weight_class_1': 0.0851538972841977, 'weight_class_2': 0.03408933908373164}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:14,615] Trial 2235 finished with value: 0.9494838928265601 and parameters: {'weight_class_0': 0.0036053993777979995, 'weight_class_1': 0.08065223348699149, 'weight_class_2': 0.033468777298758495}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:14,679] Trial 2239 finished with value: 0.9494959623678678 and parameters: {'weight_class_0': 0.003541046342745804, 'weight_class_1': 0.07598816868453308, 'weight_class_2': 0.03156125497334774}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:14,688] Trial 2238 finished with value: 0.6943744114088225 and parameters: {'weight_class_0': 0.00345136654439274, 'weight_class_1': 0.07847880026385486, 'weight_class_2': 4.343114824427991}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:14,740] Trial 2240 finished with value: 0.9494228544972078 and parameters: {'weight_class_0': 0.003431274435641664, 'weight_class_1': 0.08142456758763346, 'weight_class_2': 0.03362816158376783}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:14,755] Trial 2241 finished with value: 0.9485307036109085 and parameters: {'weight_class_0': 0.005365584099594789, 'weight_class_1': 0.1258441203148129, 'weight_class_2': 0.03246753442625876}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:14,814] Trial 2242 finished with value: 0.9482884354231835 and parameters: {'weight_class_0': 0.00565110443036041, 'weight_class_1': 0.13555845259952393, 'weight_class_2': 0.0316727915644297}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:14,819] Trial 2243 finished with value: 0.9483827712715582 and parameters: {'weight_class_0': 0.005368080264744919, 'weight_class_1': 0.14423310715254042, 'weight_class_2': 0.03247108480839851}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:14,831] Trial 2244 finished with value: 0.9484411207697464 and parameters: {'weight_class_0': 0.005457349457358321, 'weight_class_1': 0.13812792219925327, 'weight_class_2': 0.032902250725453504}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:14,901] Trial 2245 finished with value: 0.9486006144984972 and parameters: {'weight_class_0': 0.005427956339341801, 'weight_class_1': 0.052086360528392724, 'weight_class_2': 0.09941132626826298}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  75%|█████████████████████████████████████████████████████████████████████████████████████████████████▋                                | 2254/3000 [00:51<00:20, 37.25it/s]

[I 2026-07-03 10:57:14,910] Trial 2246 finished with value: 0.9490016552972663 and parameters: {'weight_class_0': 0.0054924277682247055, 'weight_class_1': 0.053787839831158306, 'weight_class_2': 0.0883445923025333}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:14,948] Trial 2247 finished with value: 0.9487104928957152 and parameters: {'weight_class_0': 0.005198234450618669, 'weight_class_1': 0.12617440407687064, 'weight_class_2': 0.10406776846372706}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:14,950] Trial 2248 finished with value: 0.9488282457344348 and parameters: {'weight_class_0': 0.005595055556151971, 'weight_class_1': 0.05374846114120193, 'weight_class_2': 0.09489811723226264}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:14,968] Trial 2249 finished with value: 0.9243214844606359 and parameters: {'weight_class_0': 0.0054234193720369, 'weight_class_1': 0.00684562732239198, 'weight_class_2': 0.08434812334821888}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:14,979] Trial 2250 finished with value: 0.9488650890852114 and parameters: {'weight_class_0': 0.00539730435350825, 'weight_class_1': 0.1250168133116132, 'weight_class_2': 0.0984422252646154}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:15,023] Trial 2251 finished with value: 0.9493183100050698 and parameters: {'weight_class_0': 0.005636733411734569, 'weight_class_1': 0.1227318348343748, 'weight_class_2': 0.08401264327505482}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:15,066] Trial 2252 finished with value: 0.9490257034112632 and parameters: {'weight_class_0': 0.005277645701307063, 'weight_class_1': 0.053856580375968674, 'weight_class_2': 0.0868508731165971}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:15,103] Trial 2253 finished with value: 0.9491305574069124 and parameters: {'weight_class_0': 0.0056193859318251094, 'weight_class_1': 0.05440151390049506, 'weight_class_2': 0.08383297908005391}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:15,127] Trial 2254 finished with value: 0.9484573789315593 and parameters: {'weight_class_0': 0.004479485626355959, 'weight_class_1': 0.056039328641333416, 'weight_class_2': 0.10324625766153112}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  75%|██████████████████████████████████████████████████████████████████████████████████████████████████                                | 2262/3000 [00:51<00:20, 35.33it/s]

[I 2026-07-03 10:57:15,142] Trial 2255 finished with value: 0.704493375967731 and parameters: {'weight_class_0': 5.625017316514538, 'weight_class_1': 0.05499190770967324, 'weight_class_2': 0.08175948519383536}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:15,152] Trial 2256 finished with value: 0.9482746208379137 and parameters: {'weight_class_0': 0.004325394925183464, 'weight_class_1': 0.05091440432099356, 'weight_class_2': 0.10368149016718188}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:15,238] Trial 2257 finished with value: 0.9492414635090062 and parameters: {'weight_class_0': 0.008526651793297195, 'weight_class_1': 0.06164367656715669, 'weight_class_2': 0.07179870861230345}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:15,260] Trial 2258 finished with value: 0.9484559569170354 and parameters: {'weight_class_0': 0.00876950975849159, 'weight_class_1': 0.06155769825971145, 'weight_class_2': 0.05412442987030361}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:15,289] Trial 2260 finished with value: 0.9496256209063186 and parameters: {'weight_class_0': 0.004204645042458555, 'weight_class_1': 0.058662741707745984, 'weight_class_2': 0.055986816763904504}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:15,290] Trial 2259 finished with value: 0.9492831297361138 and parameters: {'weight_class_0': 0.008284183733169926, 'weight_class_1': 0.06178971714605283, 'weight_class_2': 0.07006627494349764}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:15,327] Trial 2261 finished with value: 0.9496477977402477 and parameters: {'weight_class_0': 0.004430692224143077, 'weight_class_1': 0.06135075360379349, 'weight_class_2': 0.05604645930435014}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:15,330] Trial 2262 finished with value: 0.9496215774192076 and parameters: {'weight_class_0': 0.004321280735910148, 'weight_class_1': 0.062138762087008824, 'weight_class_2': 0.05641706624121151}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:15,365] Trial 2263 finished with value: 0.9467026612706003 and parameters: {'weight_class_0': 0.008171016286614525, 'weight_class_1': 0.035133137476157414, 'weight_class_2': 0.054442300148920014}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:15,394] Trial 2264 finished with value: 0.8961422723421227 and parameters: {'weight_class_0': 0.008471400850051866, 'weight_class_1': 0.0034651263516672828, 'weight_class_2': 0.05643722305248336}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:15,438] Trial 2265 finished with value: 0.9491961872121667 and parameters: {'weight_class_0': 0.004261437024429715, 'weight_class_1': 0.03540263986049219, 'weight_class_2': 0.056834489220162036}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:15,448] Trial 2266 finished with value: 0.9462572380299655 and parameters: {'weight_class_0': 0.008639672709211642, 'weight_class_1': 0.03454206709024607, 'weight_class_2': 0.05901136204786865}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:15,495] Trial 2267 finished with value: 0.9495801231909621 and parameters: {'weight_class_0': 0.004401706075926825, 'weight_class_1': 0.0680515198510084, 'weight_class_2': 0.05576412883395753}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:15,508] Trial 2268 finished with value: 0.9485873125771466 and parameters: {'weight_class_0': 0.008611134672733473, 'weight_class_1': 0.06244631808416289, 'weight_class_2': 0.054863585469042096}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:15,565] Trial 2269 finished with value: 0.9467501820234127 and parameters: {'weight_class_0': 0.008234489886691695, 'weight_class_1': 0.03554971478499093, 'weight_class_2': 0.05493182110256998}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  76%|██████████████████████████████████████████████████████████████████████████████████████████████████▋                               | 2277/3000 [00:51<00:20, 36.02it/s]

[I 2026-07-03 10:57:15,575] Trial 2270 finished with value: 0.9488043113158846 and parameters: {'weight_class_0': 0.004158580008755583, 'weight_class_1': 0.03503088443406743, 'weight_class_2': 0.0684723708219212}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:15,615] Trial 2271 finished with value: 0.9492191738434949 and parameters: {'weight_class_0': 0.0044388557216844355, 'weight_class_1': 0.03715742062370075, 'weight_class_2': 0.05759833877127581}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:15,632] Trial 2272 finished with value: 0.9493330100278986 and parameters: {'weight_class_0': 0.002897638785939128, 'weight_class_1': 0.04672117309521915, 'weight_class_2': 0.046300296794550264}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:15,663] Trial 2273 finished with value: 0.9492023769720506 and parameters: {'weight_class_0': 0.00284127037339184, 'weight_class_1': 0.03428936788595243, 'weight_class_2': 0.046676335538639806}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:15,675] Trial 2274 finished with value: 0.9467568464522356 and parameters: {'weight_class_0': 0.0028355135979403713, 'weight_class_1': 0.035028531779766496, 'weight_class_2': 0.12691550097571855}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:15,684] Trial 2275 finished with value: 0.9485067871093597 and parameters: {'weight_class_0': 0.0031503162588402997, 'weight_class_1': 0.036069427013224596, 'weight_class_2': 0.06727286755330039}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:15,730] Trial 2276 finished with value: 0.949671193897586 and parameters: {'weight_class_0': 0.004161559613336348, 'weight_class_1': 0.04795330994286355, 'weight_class_2': 0.04551182516465994}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:15,776] Trial 2278 finished with value: 0.9392682004956749 and parameters: {'weight_class_0': 0.014467140603112147, 'weight_class_1': 0.04653470446815158, 'weight_class_2': 0.0456754941070571}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  76%|██████████████████████████████████████████████████████████████████████████████████████████████████▉                               | 2284/3000 [00:52<00:20, 35.08it/s]

[I 2026-07-03 10:57:15,776] Trial 2277 finished with value: 0.9467994433424183 and parameters: {'weight_class_0': 0.002871452712826583, 'weight_class_1': 0.045499007167478414, 'weight_class_2': 0.13264061347391454}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:15,804] Trial 2279 finished with value: 0.9493472165694735 and parameters: {'weight_class_0': 0.0028382863638648564, 'weight_class_1': 0.0454808709817216, 'weight_class_2': 0.04474589847561712}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:15,833] Trial 2280 finished with value: 0.946915459996693 and parameters: {'weight_class_0': 0.00287716631710845, 'weight_class_1': 0.04590219860087352, 'weight_class_2': 0.1277433155364385}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:15,907] Trial 2282 finished with value: 0.9468145257721664 and parameters: {'weight_class_0': 0.0027132522562116498, 'weight_class_1': 0.04502243375266589, 'weight_class_2': 0.12417981230267917}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:15,907] Trial 2281 finished with value: 0.9491056580379585 and parameters: {'weight_class_0': 0.002857519494453161, 'weight_class_1': 0.07001999466924468, 'weight_class_2': 0.04420218419589753}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:15,912] Trial 2283 finished with value: 0.9494473525513788 and parameters: {'weight_class_0': 0.002952427728731259, 'weight_class_1': 0.04854099677983993, 'weight_class_2': 0.04186283698516134}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:15,985] Trial 2284 finished with value: 0.9468627618610688 and parameters: {'weight_class_0': 0.0028991504901848954, 'weight_class_1': 0.04565103331821731, 'weight_class_2': 0.12993426683674097}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  76%|███████████████████████████████████████████████████████████████████████████████████████████████████▎                              | 2292/3000 [00:52<00:18, 37.80it/s]

[I 2026-07-03 10:57:16,014] Trial 2285 finished with value: 0.948744924744301 and parameters: {'weight_class_0': 0.006182026185100667, 'weight_class_1': 0.04718515964702347, 'weight_class_2': 0.040862914196758464}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:16,021] Trial 2287 finished with value: 0.9489398880250342 and parameters: {'weight_class_0': 0.006286833238681116, 'weight_class_1': 0.07084861717249305, 'weight_class_2': 0.03989283922414692}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:16,022] Trial 2286 finished with value: 0.9490610344859078 and parameters: {'weight_class_0': 0.006262887433535403, 'weight_class_1': 0.06932541441411147, 'weight_class_2': 0.042169229319838096}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:16,043] Trial 2288 finished with value: 0.948826224178683 and parameters: {'weight_class_0': 0.0063522294537900845, 'weight_class_1': 0.06869006845809804, 'weight_class_2': 0.03946060721644999}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:16,097] Trial 2290 finished with value: 0.9479967902098912 and parameters: {'weight_class_0': 0.01166737816941925, 'weight_class_1': 0.07024759601968905, 'weight_class_2': 0.07088005914010143}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:16,114] Trial 2291 finished with value: 0.9491543215173405 and parameters: {'weight_class_0': 0.004109700610931551, 'weight_class_1': 0.07021313291686285, 'weight_class_2': 0.0702860864278885}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:16,138] Trial 2289 finished with value: 0.9495719614625262 and parameters: {'weight_class_0': 0.006001879878557805, 'weight_class_1': 0.06868594829709272, 'weight_class_2': 0.07217539549149547}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:16,152] Trial 2292 finished with value: 0.949652859633726 and parameters: {'weight_class_0': 0.0063594765793984044, 'weight_class_1': 0.07333620896412425, 'weight_class_2': 0.06935100531196117}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:16,240] Trial 2293 finished with value: 0.949586483163885 and parameters: {'weight_class_0': 0.006087040910834118, 'weight_class_1': 0.06889551839558444, 'weight_class_2': 0.07205811498614534}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:16,243] Trial 2294 finished with value: 0.9496047014244283 and parameters: {'weight_class_0': 0.006389700319579824, 'weight_class_1': 0.07033569547776677, 'weight_class_2': 0.07147665477705599}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:16,252] Trial 2295 finished with value: 0.9496548612604302 and parameters: {'weight_class_0': 0.006329317668227545, 'weight_class_1': 0.07114236267128471, 'weight_class_2': 0.07058945968466084}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:16,300] Trial 2296 finished with value: 0.949471478799313 and parameters: {'weight_class_0': 0.006781986641313088, 'weight_class_1': 0.06700698013372346, 'weight_class_2': 0.07003090135814628}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:16,336] Trial 2297 finished with value: 0.9435053647669366 and parameters: {'weight_class_0': 0.020253934670823263, 'weight_class_1': 0.09321259663970925, 'weight_class_2': 0.07046336144679007}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:16,338] Trial 2298 finished with value: 0.9488079418480568 and parameters: {'weight_class_0': 0.0038462685197542643, 'weight_class_1': 0.08947705207275575, 'weight_class_2': 0.07256852226888652}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:16,393] Trial 2300 finished with value: 0.9488138189360221 and parameters: {'weight_class_0': 0.003918360771834222, 'weight_class_1': 0.0920620903918142, 'weight_class_2': 0.07287998592802426}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:16,397] Trial 2299 finished with value: 0.9486371819589271 and parameters: {'weight_class_0': 0.01179250833626521, 'weight_class_1': 0.09516592377779334, 'weight_class_2': 0.07246059645936337}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  77%|████████████████████████████████████████████████████████████████████████████████████████████████████                              | 2308/3000 [00:52<00:19, 35.97it/s]

[I 2026-07-03 10:57:16,398] Trial 2301 finished with value: 0.9494035327061264 and parameters: {'weight_class_0': 0.004919039001974734, 'weight_class_1': 0.10020160367208447, 'weight_class_2': 0.06872567567935992}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:16,494] Trial 2304 finished with value: 0.9492781721034657 and parameters: {'weight_class_0': 0.004857780530754065, 'weight_class_1': 0.09331061448003361, 'weight_class_2': 0.07836186447836328}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:16,495] Trial 2303 finished with value: 0.9493158660306481 and parameters: {'weight_class_0': 0.004967267908085507, 'weight_class_1': 0.09570908981606757, 'weight_class_2': 0.07860581979571403}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:16,496] Trial 2302 finished with value: 0.9491025783058555 and parameters: {'weight_class_0': 0.004626491144615534, 'weight_class_1': 0.0935981203169726, 'weight_class_2': 0.08113738327246021}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:16,509] Trial 2305 finished with value: 0.9358446208292416 and parameters: {'weight_class_0': 0.021803827178354735, 'weight_class_1': 0.09495188257531607, 'weight_class_2': 0.04988164932785127}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:16,596] Trial 2308 finished with value: 0.9494090237680779 and parameters: {'weight_class_0': 0.004816348646072238, 'weight_class_1': 0.10839188978514225, 'weight_class_2': 0.048695920104276515}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:16,596] Trial 2307 finished with value: 0.9493961593817565 and parameters: {'weight_class_0': 0.004902263320206487, 'weight_class_1': 0.1128527199017098, 'weight_class_2': 0.049484383316355185}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:16,601] Trial 2306 finished with value: 0.9495555806497956 and parameters: {'weight_class_0': 0.004678842499298538, 'weight_class_1': 0.09506518542886845, 'weight_class_2': 0.04974519592947917}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  77%|████████████████████████████████████████████████████████████████████████████████████████████████████▎                             | 2316/3000 [00:53<00:18, 36.13it/s]

[I 2026-07-03 10:57:16,652] Trial 2310 finished with value: 0.9489040933836116 and parameters: {'weight_class_0': 0.004875636408949069, 'weight_class_1': 0.16564099886196554, 'weight_class_2': 0.04833381639852976}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:16,666] Trial 2309 finished with value: 0.9496325270379727 and parameters: {'weight_class_0': 0.004698108776643172, 'weight_class_1': 0.05479032249194041, 'weight_class_2': 0.05074248092628551}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:16,714] Trial 2311 finished with value: 0.8227971808415008 and parameters: {'weight_class_0': 0.34153901053326197, 'weight_class_1': 0.055105359512398686, 'weight_class_2': 0.04857027763741456}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:16,716] Trial 2312 finished with value: 0.9494449200289381 and parameters: {'weight_class_0': 0.0034329662504109823, 'weight_class_1': 0.055281295225643165, 'weight_class_2': 0.049934994277682235}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:16,761] Trial 2313 finished with value: 0.9496119967171919 and parameters: {'weight_class_0': 0.004798401946294346, 'weight_class_1': 0.056624698028226665, 'weight_class_2': 0.04997683199738898}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:16,792] Trial 2314 finished with value: 0.9496172543618159 and parameters: {'weight_class_0': 0.0038342215863498646, 'weight_class_1': 0.05417273056114414, 'weight_class_2': 0.03808867167852756}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:16,825] Trial 2316 finished with value: 0.949614599709461 and parameters: {'weight_class_0': 0.003394570856791051, 'weight_class_1': 0.05572983739286647, 'weight_class_2': 0.03824922766821044}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:16,843] Trial 2315 finished with value: 0.9493445151348192 and parameters: {'weight_class_0': 0.0032973545123679373, 'weight_class_1': 0.05588232956164976, 'weight_class_2': 0.051137872184686045}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  77%|████████████████████████████████████████████████████████████████████████████████████████████████████▋                             | 2324/3000 [00:53<00:18, 35.74it/s]

[I 2026-07-03 10:57:16,860] Trial 2317 finished with value: 0.9495955066837939 and parameters: {'weight_class_0': 0.003392523560768828, 'weight_class_1': 0.0570765801411956, 'weight_class_2': 0.038404833105952975}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:16,932] Trial 2319 finished with value: 0.9495917621782352 and parameters: {'weight_class_0': 0.003226882579896203, 'weight_class_1': 0.05450631791233344, 'weight_class_2': 0.03883497308050336}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:16,950] Trial 2318 finished with value: 0.9496288170321797 and parameters: {'weight_class_0': 0.003924077203381652, 'weight_class_1': 0.0547733420135066, 'weight_class_2': 0.03652923073853612}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:16,959] Trial 2320 finished with value: 0.9495680811152992 and parameters: {'weight_class_0': 0.0034160392338758684, 'weight_class_1': 0.05864192454222345, 'weight_class_2': 0.037003159190642614}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:16,973] Trial 2321 finished with value: 0.9495835897840182 and parameters: {'weight_class_0': 0.0035448157313705798, 'weight_class_1': 0.055287562954845604, 'weight_class_2': 0.037800932455874556}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:17,016] Trial 2322 finished with value: 0.9496158706775285 and parameters: {'weight_class_0': 0.0033472003487824914, 'weight_class_1': 0.05745288842581396, 'weight_class_2': 0.03755413263024881}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:17,043] Trial 2324 finished with value: 0.9496074442158347 and parameters: {'weight_class_0': 0.003567784824611468, 'weight_class_1': 0.03973454453834027, 'weight_class_2': 0.037827307477350774}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:17,044] Trial 2323 finished with value: 0.9496935682509494 and parameters: {'weight_class_0': 0.0034362319424756154, 'weight_class_1': 0.04062154403988076, 'weight_class_2': 0.03812768761705152}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  78%|█████████████████████████████████████████████████████████████████████████████████████████████████████                             | 2332/3000 [00:53<00:18, 35.97it/s]

[I 2026-07-03 10:57:17,091] Trial 2326 finished with value: 0.9496414499876217 and parameters: {'weight_class_0': 0.0034626046444601647, 'weight_class_1': 0.040207853586433105, 'weight_class_2': 0.030252778274658623}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:17,105] Trial 2325 finished with value: 0.9496208252262771 and parameters: {'weight_class_0': 0.003556032104883611, 'weight_class_1': 0.04243973767959274, 'weight_class_2': 0.037485779411068204}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:17,179] Trial 2327 finished with value: 0.9476919706574768 and parameters: {'weight_class_0': 0.0039282448183600265, 'weight_class_1': 0.03759194364711073, 'weight_class_2': 0.104837854901569}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:17,188] Trial 2329 finished with value: 0.947713999576124 and parameters: {'weight_class_0': 0.003979394085177068, 'weight_class_1': 0.039356980493658454, 'weight_class_2': 0.1075795244100365}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:17,192] Trial 2328 finished with value: 0.9478274767975566 and parameters: {'weight_class_0': 0.008092424703911548, 'weight_class_1': 0.03953414339153043, 'weight_class_2': 0.09625366295181706}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:17,258] Trial 2330 finished with value: 0.9467928124248944 and parameters: {'weight_class_0': 0.009111605028602204, 'weight_class_1': 0.03695981158338344, 'weight_class_2': 0.09391368889441454}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:17,288] Trial 2332 finished with value: 0.744291732060233 and parameters: {'weight_class_0': 3.3375806854241854, 'weight_class_1': 0.04239607188504331, 'weight_class_2': 0.10296170047986945}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:17,289] Trial 2331 finished with value: 0.9476242065685554 and parameters: {'weight_class_0': 0.008563119688830565, 'weight_class_1': 0.03958260723902145, 'weight_class_2': 0.08810649303624894}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  78%|█████████████████████████████████████████████████████████████████████████████████████████████████████▍                            | 2340/3000 [00:53<00:18, 35.16it/s]

[I 2026-07-03 10:57:17,342] Trial 2333 finished with value: 0.9478690189592602 and parameters: {'weight_class_0': 0.007786401308649214, 'weight_class_1': 0.040378567229563324, 'weight_class_2': 0.1083706246494489}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:17,361] Trial 2334 finished with value: 0.8171112199284574 and parameters: {'weight_class_0': 0.5620560575018886, 'weight_class_1': 0.04012476785999265, 'weight_class_2': 0.10039395936766328}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:17,409] Trial 2335 finished with value: 0.9482217101792735 and parameters: {'weight_class_0': 0.007613546338071006, 'weight_class_1': 0.04140478600836539, 'weight_class_2': 0.09535114980723204}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:17,419] Trial 2336 finished with value: 0.947743346532652 and parameters: {'weight_class_0': 0.007977928359928456, 'weight_class_1': 0.03926753897681755, 'weight_class_2': 0.10804097120895004}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:17,420] Trial 2337 finished with value: 0.947699630456922 and parameters: {'weight_class_0': 0.007879308975848534, 'weight_class_1': 0.03765087229219109, 'weight_class_2': 0.06073374949105725}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:17,469] Trial 2338 finished with value: 0.9471392221273439 and parameters: {'weight_class_0': 0.008146290972077575, 'weight_class_1': 0.03514912583875404, 'weight_class_2': 0.08703611643852566}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:17,512] Trial 2339 finished with value: 0.9494237670313103 and parameters: {'weight_class_0': 0.007892665265315194, 'weight_class_1': 0.11453305338677065, 'weight_class_2': 0.06049206463100616}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:17,521] Trial 2340 finished with value: 0.949592094824148 and parameters: {'weight_class_0': 0.0075607819816607205, 'weight_class_1': 0.11188205657405788, 'weight_class_2': 0.06132355337429652}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  78%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋                            | 2348/3000 [00:53<00:18, 35.50it/s]

[I 2026-07-03 10:57:17,548] Trial 2341 finished with value: 0.9494168553380007 and parameters: {'weight_class_0': 0.008076319979969014, 'weight_class_1': 0.11413534243418581, 'weight_class_2': 0.06080763784119025}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:17,557] Trial 2342 finished with value: 0.9496273311816253 and parameters: {'weight_class_0': 0.006430722612872421, 'weight_class_1': 0.0721689274759796, 'weight_class_2': 0.056031925344267576}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:17,604] Trial 2343 finished with value: 0.9495317541309841 and parameters: {'weight_class_0': 0.007404948081327477, 'weight_class_1': 0.12278440227802083, 'weight_class_2': 0.058981740147269056}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:17,653] Trial 2345 finished with value: 0.9495902423593172 and parameters: {'weight_class_0': 0.0065745856577007055, 'weight_class_1': 0.11252392518517629, 'weight_class_2': 0.059735905780204775}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:17,653] Trial 2344 finished with value: 0.9496192723438855 and parameters: {'weight_class_0': 0.007365013823909489, 'weight_class_1': 0.11662525785503385, 'weight_class_2': 0.060905358458173194}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:17,654] Trial 2346 finished with value: 0.9495898244087725 and parameters: {'weight_class_0': 0.006308945782526111, 'weight_class_1': 0.11458413363336707, 'weight_class_2': 0.060903134641411026}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:17,726] Trial 2348 finished with value: 0.9495792076240949 and parameters: {'weight_class_0': 0.0062164833844689325, 'weight_class_1': 0.06870527990807827, 'weight_class_2': 0.06457008736711273}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:17,763] Trial 2347 finished with value: 0.9495387656083535 and parameters: {'weight_class_0': 0.006002445686690534, 'weight_class_1': 0.11187137257361376, 'weight_class_2': 0.06283747993584529}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  79%|██████████████████████████████████████████████████████████████████████████████████████████████████████                            | 2356/3000 [00:54<00:19, 33.68it/s]

[I 2026-07-03 10:57:17,790] Trial 2349 finished with value: 0.9496423377597084 and parameters: {'weight_class_0': 0.005896408031512467, 'weight_class_1': 0.08127489029292362, 'weight_class_2': 0.061833124684478685}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:17,791] Trial 2350 finished with value: 0.9496729317828256 and parameters: {'weight_class_0': 0.006133288790942866, 'weight_class_1': 0.07767533663359402, 'weight_class_2': 0.060260507007003375}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:17,874] Trial 2351 finished with value: 0.9484111761434807 and parameters: {'weight_class_0': 0.005844521016993374, 'weight_class_1': 0.07874962605052498, 'weight_class_2': 0.030562595200043282}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:17,887] Trial 2352 finished with value: 0.9488831128658676 and parameters: {'weight_class_0': 0.005294725026640436, 'weight_class_1': 0.08193062077668367, 'weight_class_2': 0.03221487947945318}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:17,895] Trial 2353 finished with value: 0.9484083214200639 and parameters: {'weight_class_0': 0.010710402396958132, 'weight_class_1': 0.0841492438707059, 'weight_class_2': 0.06201109626238138}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:17,930] Trial 2354 finished with value: 0.949702206644882 and parameters: {'weight_class_0': 0.005454044541341146, 'weight_class_1': 0.06621733413379341, 'weight_class_2': 0.061410558998032244}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:17,945] Trial 2355 finished with value: 0.9488068321019787 and parameters: {'weight_class_0': 0.005416256194387559, 'weight_class_1': 0.08230477149236967, 'weight_class_2': 0.03225710548781118}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:17,989] Trial 2356 finished with value: 0.9486496975510886 and parameters: {'weight_class_0': 0.005331208585952079, 'weight_class_1': 0.0813104331364383, 'weight_class_2': 0.030184243417336366}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:17,998] Trial 2357 finished with value: 0.9485685528653681 and parameters: {'weight_class_0': 0.005381313582103352, 'weight_class_1': 0.08303734372515838, 'weight_class_2': 0.029691629471000982}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:18,005] Trial 2358 finished with value: 0.9487889737222673 and parameters: {'weight_class_0': 0.005315403322790664, 'weight_class_1': 0.06584655321902597, 'weight_class_2': 0.03093699344269607}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:18,060] Trial 2359 finished with value: 0.9493447438872019 and parameters: {'weight_class_0': 0.004094577687497519, 'weight_class_1': 0.049298068835468015, 'weight_class_2': 0.030563647980222677}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:18,079] Trial 2360 finished with value: 0.9492470523937016 and parameters: {'weight_class_0': 0.004300490350151686, 'weight_class_1': 0.049432454131079974, 'weight_class_2': 0.031060547556763417}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:18,082] Trial 2361 finished with value: 0.9491032274271634 and parameters: {'weight_class_0': 0.004482243553255111, 'weight_class_1': 0.04921595842178419, 'weight_class_2': 0.031230152013300354}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:18,133] Trial 2362 finished with value: 0.9492007454567002 and parameters: {'weight_class_0': 0.004256786426082207, 'weight_class_1': 0.04849170794859302, 'weight_class_2': 0.03012630485523088}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  79%|██████████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 2371/3000 [00:54<00:17, 35.99it/s]

[I 2026-07-03 10:57:18,205] Trial 2363 finished with value: 0.9491745815760538 and parameters: {'weight_class_0': 0.00434304030492345, 'weight_class_1': 0.04692037696234332, 'weight_class_2': 0.03108760638833371}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:18,223] Trial 2364 finished with value: 0.9495545018402477 and parameters: {'weight_class_0': 0.004582036403282852, 'weight_class_1': 0.04756666771218004, 'weight_class_2': 0.04453958426375393}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:18,242] Trial 2365 finished with value: 0.9494743658825202 and parameters: {'weight_class_0': 0.005305798207236109, 'weight_class_1': 0.07007244894144776, 'weight_class_2': 0.0776553415757056}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:18,262] Trial 2366 finished with value: 0.9494715323691141 and parameters: {'weight_class_0': 0.005188897329192714, 'weight_class_1': 0.06571427361886759, 'weight_class_2': 0.07598760896048024}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:18,265] Trial 2367 finished with value: 0.949292249827788 and parameters: {'weight_class_0': 0.0050852965817192305, 'weight_class_1': 0.06701331847896881, 'weight_class_2': 0.0839020036818137}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:18,320] Trial 2368 finished with value: 0.9489184318788707 and parameters: {'weight_class_0': 0.004507489383190013, 'weight_class_1': 0.05977381086495098, 'weight_class_2': 0.08427379244808782}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:18,332] Trial 2370 finished with value: 0.9490819893347551 and parameters: {'weight_class_0': 0.0048195192230277815, 'weight_class_1': 0.06161722279722491, 'weight_class_2': 0.08468275266062485}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:18,361] Trial 2369 finished with value: 0.9490393299208263 and parameters: {'weight_class_0': 0.004502273808789591, 'weight_class_1': 0.06427783678391041, 'weight_class_2': 0.0814716904719701}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:18,384] Trial 2371 finished with value: 0.9037790503964471 and parameters: {'weight_class_0': 0.004855697585091773, 'weight_class_1': 0.0027483036725506256, 'weight_class_2': 0.07985717832327015}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  79%|███████████████████████████████████████████████████████████████████████████████████████████████████████                           | 2378/3000 [00:54<00:17, 36.38it/s]

[I 2026-07-03 10:57:18,410] Trial 2372 finished with value: 0.949325001714629 and parameters: {'weight_class_0': 0.0050227094045678725, 'weight_class_1': 0.06600449996312793, 'weight_class_2': 0.07962263657134452}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:18,433] Trial 2373 finished with value: 0.9488521859969669 and parameters: {'weight_class_0': 0.010329959040704701, 'weight_class_1': 0.06450578372256627, 'weight_class_2': 0.08452792752377314}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:18,487] Trial 2374 finished with value: 0.9485054054472282 and parameters: {'weight_class_0': 0.010656992319790974, 'weight_class_1': 0.06346153358559348, 'weight_class_2': 0.07980584292666652}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:18,516] Trial 2375 finished with value: 0.949480045520536 and parameters: {'weight_class_0': 0.006397686381617383, 'weight_class_1': 0.06459250457028, 'weight_class_2': 0.08178750910567076}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:18,553] Trial 2376 finished with value: 0.9494011066116016 and parameters: {'weight_class_0': 0.006688656767461888, 'weight_class_1': 0.061329303082403454, 'weight_class_2': 0.0824932960114479}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:18,568] Trial 2377 finished with value: 0.9494652792708244 and parameters: {'weight_class_0': 0.006411909029741686, 'weight_class_1': 0.06708153802969369, 'weight_class_2': 0.08020339556590231}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:18,609] Trial 2378 finished with value: 0.9487504751746232 and parameters: {'weight_class_0': 0.010301221415954173, 'weight_class_1': 0.06328318140216636, 'weight_class_2': 0.08187528020059466}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████████▍                          | 2386/3000 [00:54<00:17, 35.03it/s]

[I 2026-07-03 10:57:18,655] Trial 2379 finished with value: 0.9495020263282411 and parameters: {'weight_class_0': 0.00660125807904565, 'weight_class_1': 0.06532409569694522, 'weight_class_2': 0.0781442878631813}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:18,676] Trial 2380 finished with value: 0.9471472704210432 and parameters: {'weight_class_0': 0.010688241179370004, 'weight_class_1': 0.0676113468807148, 'weight_class_2': 0.05101796112819196}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:18,679] Trial 2381 finished with value: 0.94941692380613 and parameters: {'weight_class_0': 0.006749534951069051, 'weight_class_1': 0.08629388086835794, 'weight_class_2': 0.051320518453407175}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:18,728] Trial 2382 finished with value: 0.9484029086663224 and parameters: {'weight_class_0': 0.010191754768067758, 'weight_class_1': 0.08978684393297941, 'weight_class_2': 0.055505341711868154}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:18,737] Trial 2383 finished with value: 0.9496347530122309 and parameters: {'weight_class_0': 0.006600096987320148, 'weight_class_1': 0.08397526982982695, 'weight_class_2': 0.0553331079722172}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:18,762] Trial 2384 finished with value: 0.9494905941657542 and parameters: {'weight_class_0': 0.006460610558315579, 'weight_class_1': 0.08301611399032821, 'weight_class_2': 0.05009182382750949}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:18,826] Trial 2386 finished with value: 0.9493682174434733 and parameters: {'weight_class_0': 0.006851575445889323, 'weight_class_1': 0.08602577429424267, 'weight_class_2': 0.05084733262748713}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:18,827] Trial 2385 finished with value: 0.9494597574986816 and parameters: {'weight_class_0': 0.006636208387867446, 'weight_class_1': 0.08687331158527159, 'weight_class_2': 0.05134106454623202}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████████▊                          | 2395/3000 [00:55<00:16, 35.65it/s]

[I 2026-07-03 10:57:18,899] Trial 2388 finished with value: 0.9492849383737457 and parameters: {'weight_class_0': 0.0067796397327141295, 'weight_class_1': 0.0894530002467579, 'weight_class_2': 0.04776974146020808}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:18,901] Trial 2387 finished with value: 0.9495343463575369 and parameters: {'weight_class_0': 0.006681238454319588, 'weight_class_1': 0.0862675838111353, 'weight_class_2': 0.05250186479602894}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:18,938] Trial 2389 finished with value: 0.9496135842480236 and parameters: {'weight_class_0': 0.006031943928272062, 'weight_class_1': 0.09117784990125395, 'weight_class_2': 0.051481364784567656}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:18,941] Trial 2390 finished with value: 0.9495504677076935 and parameters: {'weight_class_0': 0.00626911144861306, 'weight_class_1': 0.09125736429434149, 'weight_class_2': 0.050357316683584806}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:18,991] Trial 2391 finished with value: 0.949492780913996 and parameters: {'weight_class_0': 0.006757960492011872, 'weight_class_1': 0.08726837206335165, 'weight_class_2': 0.05239547630824784}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:19,001] Trial 2392 finished with value: 0.9495617934603254 and parameters: {'weight_class_0': 0.005709266259818437, 'weight_class_1': 0.09569251211425571, 'weight_class_2': 0.05445411282949903}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:19,012] Trial 2393 finished with value: 0.9496284337334021 and parameters: {'weight_class_0': 0.005546664822897879, 'weight_class_1': 0.09038487203174436, 'weight_class_2': 0.06291922980982297}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:19,070] Trial 2395 finished with value: 0.9495333854658735 and parameters: {'weight_class_0': 0.004188285464872402, 'weight_class_1': 0.09197299530767182, 'weight_class_2': 0.0472753165545271}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:19,076] Trial 2394 finished with value: 0.9496255410605455 and parameters: {'weight_class_0': 0.005664446879534259, 'weight_class_1': 0.0956070686734912, 'weight_class_2': 0.06561823400896548}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  80%|████████████████████████████████████████████████████████████████████████████████████████████████████████                          | 2402/3000 [00:55<00:16, 35.43it/s]

[I 2026-07-03 10:57:19,089] Trial 2396 finished with value: 0.9496080739645006 and parameters: {'weight_class_0': 0.005099295393239616, 'weight_class_1': 0.09392307559293082, 'weight_class_2': 0.04688948865151515}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:19,137] Trial 2397 finished with value: 0.9496692069766487 and parameters: {'weight_class_0': 0.005363117902037079, 'weight_class_1': 0.07458914934233501, 'weight_class_2': 0.06645268891069156}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:19,180] Trial 2398 finished with value: 0.9494143807218127 and parameters: {'weight_class_0': 0.0054590293352166, 'weight_class_1': 0.05267393568699657, 'weight_class_2': 0.06813633026413984}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:19,232] Trial 2399 finished with value: 0.8705496301825422 and parameters: {'weight_class_0': 0.0677500297105479, 'weight_class_1': 0.05083475702562866, 'weight_class_2': 0.06518806837554583}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:19,244] Trial 2400 finished with value: 0.9474268568360072 and parameters: {'weight_class_0': 0.014062974095685615, 'weight_class_1': 0.14368108247809622, 'weight_class_2': 0.062248947887367415}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:19,292] Trial 2401 finished with value: 0.9452437168825337 and parameters: {'weight_class_0': 0.012953938930465612, 'weight_class_1': 0.05114184724424753, 'weight_class_2': 0.06541386355017273}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:19,298] Trial 2402 finished with value: 0.9492512448834362 and parameters: {'weight_class_0': 0.005202088650503074, 'weight_class_1': 0.14766973414902468, 'weight_class_2': 0.06532179824978514}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:19,331] Trial 2403 finished with value: 0.9486140954103531 and parameters: {'weight_class_0': 0.004059225893422763, 'weight_class_1': 0.14558078501296443, 'weight_class_2': 0.06413368354372617}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:19,337] Trial 2404 finished with value: 0.9492743774131475 and parameters: {'weight_class_0': 0.004125594535434981, 'weight_class_1': 0.051270676691207114, 'weight_class_2': 0.06666569385057111}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:19,351] Trial 2405 finished with value: 0.9484441054734308 and parameters: {'weight_class_0': 0.0041443331092168335, 'weight_class_1': 0.16000366582975778, 'weight_class_2': 0.06526542149621282}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:19,416] Trial 2407 finished with value: 0.948479466641487 and parameters: {'weight_class_0': 0.0040873304666704585, 'weight_class_1': 0.1518722103082595, 'weight_class_2': 0.06610892346048722}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:19,423] Trial 2406 finished with value: 0.942908291675416 and parameters: {'weight_class_0': 0.015492669869931875, 'weight_class_1': 0.05248471507986816, 'weight_class_2': 0.06708827018977004}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:19,444] Trial 2408 finished with value: 0.9449992839615322 and parameters: {'weight_class_0': 0.013617704178536978, 'weight_class_1': 0.05254771554057404, 'weight_class_2': 0.06745566148345972}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:19,486] Trial 2409 finished with value: 0.9492884680870483 and parameters: {'weight_class_0': 0.015137771148424144, 'weight_class_1': 0.1574346745101983, 'weight_class_2': 0.11465911162915624}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:19,500] Trial 2410 finished with value: 0.8939503753816807 and parameters: {'weight_class_0': 0.06555576235282824, 'weight_class_1': 0.052045496243888614, 'weight_class_2': 0.12112789110445377}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:19,540] Trial 2411 finished with value: 0.9483937740498082 and parameters: {'weight_class_0': 0.009107420571679088, 'weight_class_1': 0.054568919351230705, 'weight_class_2': 0.06561848545828738}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:19,579] Trial 2412 finished with value: 0.9486002015569949 and parameters: {'weight_class_0': 0.008805396702690208, 'weight_class_1': 0.05609659774250477, 'weight_class_2': 0.1138553204194128}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:19,636] Trial 2413 finished with value: 0.9479972360922563 and parameters: {'weight_class_0': 0.004216692108033774, 'weight_class_1': 0.05553773659696349, 'weight_class_2': 0.11673384370590953}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:19,665] Trial 2415 finished with value: 0.9164544930661758 and parameters: {'weight_class_0': 0.029586620615525232, 'weight_class_1': 0.07179442699828865, 'weight_class_2': 0.044200658105772575}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:19,667] Trial 2414 finished with value: 0.9490479993454407 and parameters: {'weight_class_0': 0.008689398887077758, 'weight_class_1': 0.07229409096925635, 'weight_class_2': 0.12417607158131039}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:19,702] Trial 2416 finished with value: 0.9492503000188731 and parameters: {'weight_class_0': 0.008983387971559146, 'weight_class_1': 0.07285410482276758, 'weight_class_2': 0.10894150670511843}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:19,714] Trial 2417 finished with value: 0.949096931639092 and parameters: {'weight_class_0': 0.00842839997472005, 'weight_class_1': 0.07163918595867239, 'weight_class_2': 0.12037715315320126}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████                         | 2425/3000 [00:56<00:16, 35.18it/s]

[I 2026-07-03 10:57:19,755] Trial 2418 finished with value: 0.9494029132323347 and parameters: {'weight_class_0': 0.008072186189670868, 'weight_class_1': 0.07458413142800711, 'weight_class_2': 0.09812571603182532}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:19,797] Trial 2419 finished with value: 0.9491602837685112 and parameters: {'weight_class_0': 0.008931237324161529, 'weight_class_1': 0.06915787341445714, 'weight_class_2': 0.1109025735680516}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:19,808] Trial 2421 finished with value: 0.9477809791552803 and parameters: {'weight_class_0': 0.009091583248482816, 'weight_class_1': 0.07253843151141436, 'weight_class_2': 0.044928161668314995}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:19,809] Trial 2420 finished with value: 0.9492130250214629 and parameters: {'weight_class_0': 0.00852936961668454, 'weight_class_1': 0.07373380037336827, 'weight_class_2': 0.11225419599059046}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:19,843] Trial 2422 finished with value: 0.947936216705139 and parameters: {'weight_class_0': 0.008793834122755976, 'weight_class_1': 0.07574696059697994, 'weight_class_2': 0.043020264665419375}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:19,881] Trial 2423 finished with value: 0.7919988727357579 and parameters: {'weight_class_0': 2.687242164737315, 'weight_class_1': 0.07457096034655766, 'weight_class_2': 0.043683865018441514}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:19,933] Trial 2424 finished with value: 0.9483356128541317 and parameters: {'weight_class_0': 0.007935003091356243, 'weight_class_1': 0.07120046360645403, 'weight_class_2': 0.042116932036380825}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:19,940] Trial 2425 finished with value: 0.9483643537005553 and parameters: {'weight_class_0': 0.008077180612348552, 'weight_class_1': 0.06958935849918527, 'weight_class_2': 0.04381870066978997}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▍                        | 2433/3000 [00:56<00:16, 34.47it/s]

[I 2026-07-03 10:57:20,003] Trial 2426 finished with value: 0.9496432811083242 and parameters: {'weight_class_0': 0.005118693131688269, 'weight_class_1': 0.07130272277866447, 'weight_class_2': 0.04378741536350901}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:20,011] Trial 2427 finished with value: 0.9495801766575008 and parameters: {'weight_class_0': 0.004876070174398153, 'weight_class_1': 0.07157438466428175, 'weight_class_2': 0.04442857117286061}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:20,053] Trial 2428 finished with value: 0.9496433384661741 and parameters: {'weight_class_0': 0.0050871717142312875, 'weight_class_1': 0.06950274316241796, 'weight_class_2': 0.043088722598980715}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:20,070] Trial 2429 finished with value: 0.9496272705907356 and parameters: {'weight_class_0': 0.004981522303940765, 'weight_class_1': 0.060574694651095384, 'weight_class_2': 0.04822241346533191}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:20,070] Trial 2430 finished with value: 0.9496893926976528 and parameters: {'weight_class_0': 0.004955526976856386, 'weight_class_1': 0.060909980162247454, 'weight_class_2': 0.043128702799597365}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:20,145] Trial 2431 finished with value: 0.9496648692752613 and parameters: {'weight_class_0': 0.00493346841584513, 'weight_class_1': 0.0611461437085968, 'weight_class_2': 0.04552715559560555}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:20,155] Trial 2433 finished with value: 0.9495984047407061 and parameters: {'weight_class_0': 0.004942265407509175, 'weight_class_1': 0.05844902757796293, 'weight_class_2': 0.04110120220505792}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:20,173] Trial 2432 finished with value: 0.9495325378275541 and parameters: {'weight_class_0': 0.004972866852112558, 'weight_class_1': 0.04763434997023559, 'weight_class_2': 0.04364785667268904}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▊                        | 2441/3000 [00:56<00:15, 36.33it/s]

[I 2026-07-03 10:57:20,177] Trial 2434 finished with value: 0.9494869994026757 and parameters: {'weight_class_0': 0.005157319667119835, 'weight_class_1': 0.11588555824454441, 'weight_class_2': 0.04439884846720962}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:20,199] Trial 2435 finished with value: 0.9495282924210325 and parameters: {'weight_class_0': 0.005011975654366205, 'weight_class_1': 0.11154872966544531, 'weight_class_2': 0.05559067048107431}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:20,273] Trial 2437 finished with value: 0.9488330792090528 and parameters: {'weight_class_0': 0.004998562771696121, 'weight_class_1': 0.058481328965381954, 'weight_class_2': 0.09216690848907463}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:20,285] Trial 2436 finished with value: 0.9496571625187785 and parameters: {'weight_class_0': 0.004963499608990233, 'weight_class_1': 0.05713917287396661, 'weight_class_2': 0.05621825037843175}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:20,327] Trial 2438 finished with value: 0.9492761112888517 and parameters: {'weight_class_0': 0.0041167647773194295, 'weight_class_1': 0.1092254309945311, 'weight_class_2': 0.05501450202524278}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:20,344] Trial 2439 finished with value: 0.6837760363694212 and parameters: {'weight_class_0': 0.0039332533977489694, 'weight_class_1': 0.11413473518172201, 'weight_class_2': 6.264107359665668}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:20,363] Trial 2441 finished with value: 0.8595691373989709 and parameters: {'weight_class_0': 0.004126202264498843, 'weight_class_1': 0.04985274625604461, 'weight_class_2': 1.3467651722302465}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:20,387] Trial 2440 finished with value: 0.9484167644026226 and parameters: {'weight_class_0': 0.004324007335976679, 'weight_class_1': 0.11736157457529783, 'weight_class_2': 0.09643714373474853}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:20,401] Trial 2442 finished with value: 0.8870420471665011 and parameters: {'weight_class_0': 0.004083523591372364, 'weight_class_1': 0.0010193996588507425, 'weight_class_2': 0.059692365969188886}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:20,438] Trial 2443 finished with value: 0.948392897159732 and parameters: {'weight_class_0': 0.0036783603052946865, 'weight_class_1': 0.050673039157353245, 'weight_class_2': 0.08864760451426035}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:20,499] Trial 2444 finished with value: 0.9485659656029113 and parameters: {'weight_class_0': 0.003914906712443624, 'weight_class_1': 0.05757337819730313, 'weight_class_2': 0.08766300994087074}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:20,556] Trial 2446 finished with value: 0.9494139634831308 and parameters: {'weight_class_0': 0.004073913638737255, 'weight_class_1': 0.04643416717165712, 'weight_class_2': 0.0575375737948484}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:20,561] Trial 2445 finished with value: 0.9484347284262685 and parameters: {'weight_class_0': 0.003773155332440747, 'weight_class_1': 0.047510900838248306, 'weight_class_2': 0.08733702119869993}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:20,589] Trial 2447 finished with value: 0.9484274502291928 and parameters: {'weight_class_0': 0.003961628629720299, 'weight_class_1': 0.049830944013420655, 'weight_class_2': 0.09279657023455487}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:20,602] Trial 2448 finished with value: 0.9483227893428312 and parameters: {'weight_class_0': 0.004168970900344504, 'weight_class_1': 0.04515064163538894, 'weight_class_2': 0.0923364255638576}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▍                       | 2457/3000 [00:56<00:14, 36.33it/s]

[I 2026-07-03 10:57:20,606] Trial 2449 finished with value: 0.6369487587263868 and parameters: {'weight_class_0': 0.004082630019741602, 'weight_class_1': 0.045198036969806794, 'weight_class_2': 9.803337815539193}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:20,644] Trial 2450 finished with value: 0.9483471959395327 and parameters: {'weight_class_0': 0.0039064281232221295, 'weight_class_1': 0.046734368382297685, 'weight_class_2': 0.09172013164282454}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:20,680] Trial 2451 finished with value: 0.8903801287574491 and parameters: {'weight_class_0': 0.003617568969577894, 'weight_class_1': 0.047006969096913806, 'weight_class_2': 0.9154034288084067}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:20,719] Trial 2452 finished with value: 0.9490924383382106 and parameters: {'weight_class_0': 0.006956631323696318, 'weight_class_1': 0.05056316997994135, 'weight_class_2': 0.08347584672281627}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:20,737] Trial 2454 finished with value: 0.8703314584959098 and parameters: {'weight_class_0': 0.00627725507091724, 'weight_class_1': 0.04347067467256036, 'weight_class_2': 1.8235377495599545}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:20,742] Trial 2453 finished with value: 0.9491110948577464 and parameters: {'weight_class_0': 0.006063312765337755, 'weight_class_1': 0.048981906442321914, 'weight_class_2': 0.08283824521671086}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:20,800] Trial 2455 finished with value: 0.9488787351222793 and parameters: {'weight_class_0': 0.007092440725456312, 'weight_class_1': 0.04702651870347743, 'weight_class_2': 0.07474237484318667}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:20,839] Trial 2456 finished with value: 0.9489439255503439 and parameters: {'weight_class_0': 0.007060192103550452, 'weight_class_1': 0.04690321376240785, 'weight_class_2': 0.05646561418812472}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▊                       | 2464/3000 [00:57<00:15, 34.57it/s]

[I 2026-07-03 10:57:20,898] Trial 2457 finished with value: 0.9490414520536202 and parameters: {'weight_class_0': 0.006187951973754909, 'weight_class_1': 0.04403341175155327, 'weight_class_2': 0.07472764233696955}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:20,910] Trial 2459 finished with value: 0.947922848528318 and parameters: {'weight_class_0': 0.006101451613953977, 'weight_class_1': 0.060829048622143056, 'weight_class_2': 0.15070473162704517}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:20,919] Trial 2458 finished with value: 0.9494985109867172 and parameters: {'weight_class_0': 0.006371742865311364, 'weight_class_1': 0.06001928216614051, 'weight_class_2': 0.06992165903431159}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:20,954] Trial 2460 finished with value: 0.949413150501431 and parameters: {'weight_class_0': 0.007037057391037579, 'weight_class_1': 0.06055159993158205, 'weight_class_2': 0.07731328019638058}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:20,958] Trial 2461 finished with value: 0.949673085938314 and parameters: {'weight_class_0': 0.006142463824592007, 'weight_class_1': 0.08287112801252106, 'weight_class_2': 0.07252363190468482}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:20,997] Trial 2462 finished with value: 0.9492261448753799 and parameters: {'weight_class_0': 0.006901277869054865, 'weight_class_1': 0.1948620309659248, 'weight_class_2': 0.07215732703684877}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:21,013] Trial 2463 finished with value: 0.9495053156769989 and parameters: {'weight_class_0': 0.006313838067824225, 'weight_class_1': 0.061360985444239326, 'weight_class_2': 0.07269070978911364}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:21,057] Trial 2464 finished with value: 0.9495677288472035 and parameters: {'weight_class_0': 0.006008045724130636, 'weight_class_1': 0.06081652510945482, 'weight_class_2': 0.06824765081516504}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▏                      | 2473/3000 [00:57<00:14, 35.22it/s]

[I 2026-07-03 10:57:21,071] Trial 2465 finished with value: 0.9494439081040783 and parameters: {'weight_class_0': 0.0071995929849809044, 'weight_class_1': 0.06285214397998261, 'weight_class_2': 0.07111404646190064}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:21,113] Trial 2466 finished with value: 0.9493052867495756 and parameters: {'weight_class_0': 0.007260692037811027, 'weight_class_1': 0.19111180641049724, 'weight_class_2': 0.06996753891626839}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:21,161] Trial 2467 finished with value: 0.9495692421300909 and parameters: {'weight_class_0': 0.0058082770547263915, 'weight_class_1': 0.06176793482704004, 'weight_class_2': 0.05718366632071583}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:21,166] Trial 2468 finished with value: 0.9483366154818191 and parameters: {'weight_class_0': 0.005900172030045665, 'weight_class_1': 0.08270649890251393, 'weight_class_2': 0.1462675482195539}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:21,212] Trial 2469 finished with value: 0.9440828308996035 and parameters: {'weight_class_0': 0.0031847670879580872, 'weight_class_1': 0.08335834324761085, 'weight_class_2': 0.2587872105453824}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:21,230] Trial 2470 finished with value: 0.9484121250546836 and parameters: {'weight_class_0': 0.003053143147649285, 'weight_class_1': 0.10388932569282601, 'weight_class_2': 0.0560987083999532}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:21,267] Trial 2471 finished with value: 0.9484321304629173 and parameters: {'weight_class_0': 0.0031853549797745055, 'weight_class_1': 0.10599224153544497, 'weight_class_2': 0.058572862986644166}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:21,282] Trial 2472 finished with value: 0.9484982086915279 and parameters: {'weight_class_0': 0.0031108507080255376, 'weight_class_1': 0.10510309485156556, 'weight_class_2': 0.05570286629485615}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  83%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▍                      | 2479/3000 [00:57<00:16, 31.23it/s]

[I 2026-07-03 10:57:21,332] Trial 2473 finished with value: 0.948814423534627 and parameters: {'weight_class_0': 0.0032770439424380264, 'weight_class_1': 0.09714654737964191, 'weight_class_2': 0.05533712910769127}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:21,349] Trial 2474 finished with value: 0.9487902451767903 and parameters: {'weight_class_0': 0.00327845633836267, 'weight_class_1': 0.09961601440891332, 'weight_class_2': 0.055341747002734594}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:21,367] Trial 2475 finished with value: 0.948835217198252 and parameters: {'weight_class_0': 0.0033137365404141386, 'weight_class_1': 0.10183273768538093, 'weight_class_2': 0.05536804233921367}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:21,468] Trial 2477 finished with value: 0.9489034385104825 and parameters: {'weight_class_0': 0.003309533657558537, 'weight_class_1': 0.08438197992581499, 'weight_class_2': 0.05761816995332327}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:21,468] Trial 2476 finished with value: 0.9488770285187881 and parameters: {'weight_class_0': 0.003447795819089431, 'weight_class_1': 0.10403502968316868, 'weight_class_2': 0.05661586300600751}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:21,501] Trial 2479 finished with value: 0.9488737271422947 and parameters: {'weight_class_0': 0.003137695788598285, 'weight_class_1': 0.09564668132030578, 'weight_class_2': 0.05132283986096483}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:21,502] Trial 2478 finished with value: 0.9485049988406108 and parameters: {'weight_class_0': 0.0031709446981658144, 'weight_class_1': 0.09917858652613751, 'weight_class_2': 0.05919932895801969}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  83%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▊                      | 2487/3000 [00:57<00:14, 35.24it/s]

[I 2026-07-03 10:57:21,540] Trial 2480 finished with value: 0.9485478997469863 and parameters: {'weight_class_0': 0.0031332683420090936, 'weight_class_1': 0.1069603514967212, 'weight_class_2': 0.05475820893041925}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:21,554] Trial 2481 finished with value: 0.9484605859515313 and parameters: {'weight_class_0': 0.003152427933083531, 'weight_class_1': 0.1022527640471054, 'weight_class_2': 0.05788641281563915}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:21,593] Trial 2482 finished with value: 0.9473479437792921 and parameters: {'weight_class_0': 0.010869684872881768, 'weight_class_1': 0.07712580376528175, 'weight_class_2': 0.05062785314100013}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:21,604] Trial 2484 finished with value: 0.8124317758550245 and parameters: {'weight_class_0': 0.8975280082209427, 'weight_class_1': 0.07766529335704053, 'weight_class_2': 0.05281388195905268}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:21,659] Trial 2487 finished with value: 0.949643673399677 and parameters: {'weight_class_0': 0.004630769420286285, 'weight_class_1': 0.08079318000570272, 'weight_class_2': 0.040407627391498405}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:21,660] Trial 2486 finished with value: 0.9495450307420924 and parameters: {'weight_class_0': 0.004501369686252713, 'weight_class_1': 0.07792462290561618, 'weight_class_2': 0.046641706419034056}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:21,660] Trial 2483 finished with value: 0.9468304142919189 and parameters: {'weight_class_0': 0.011459177323563998, 'weight_class_1': 0.07581901484369577, 'weight_class_2': 0.050994654025687224}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:21,682] Trial 2485 finished with value: 0.9495669072658264 and parameters: {'weight_class_0': 0.004735751216381371, 'weight_class_1': 0.08394761462871123, 'weight_class_2': 0.04652687305555977}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                     | 2496/3000 [00:58<00:14, 34.76it/s]

[I 2026-07-03 10:57:21,812] Trial 2488 finished with value: 0.9442257703382912 and parameters: {'weight_class_0': 0.01124769691209638, 'weight_class_1': 0.07134490819422934, 'weight_class_2': 0.0377407093834912}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:21,818] Trial 2489 finished with value: 0.945933243198029 and parameters: {'weight_class_0': 0.01058978889245348, 'weight_class_1': 0.07608027916350832, 'weight_class_2': 0.0403837295400443}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:21,825] Trial 2490 finished with value: 0.9492257719258137 and parameters: {'weight_class_0': 0.0045921213201891116, 'weight_class_1': 0.131302179493237, 'weight_class_2': 0.03996016991999371}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:21,865] Trial 2491 finished with value: 0.9496365762146685 and parameters: {'weight_class_0': 0.0044269619720680295, 'weight_class_1': 0.07376896294353927, 'weight_class_2': 0.036521672645116535}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:21,872] Trial 2493 finished with value: 0.9495829735119458 and parameters: {'weight_class_0': 0.004681353299668173, 'weight_class_1': 0.07240749617131853, 'weight_class_2': 0.0389471010718634}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:21,893] Trial 2492 finished with value: 0.9452417010139706 and parameters: {'weight_class_0': 0.01110561133228427, 'weight_class_1': 0.07225699176726463, 'weight_class_2': 0.040808739471587786}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:21,949] Trial 2494 finished with value: 0.9496120756296156 and parameters: {'weight_class_0': 0.004683618869914294, 'weight_class_1': 0.05729237989515032, 'weight_class_2': 0.03889372146712126}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:21,951] Trial 2495 finished with value: 0.9494918203461502 and parameters: {'weight_class_0': 0.005141913726708729, 'weight_class_1': 0.05549035659674001, 'weight_class_2': 0.04108912032470197}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:21,952] Trial 2496 finished with value: 0.9489013393950225 and parameters: {'weight_class_0': 0.005463094811775096, 'weight_class_1': 0.13494786488840746, 'weight_class_2': 0.09634813596790189}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                     | 2502/3000 [00:58<00:14, 34.91it/s]

[I 2026-07-03 10:57:22,017] Trial 2497 finished with value: 0.9484330926397413 and parameters: {'weight_class_0': 0.005434626941248684, 'weight_class_1': 0.034881462702997794, 'weight_class_2': 0.0373457883712672}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:22,036] Trial 2498 finished with value: 0.9491841982044221 and parameters: {'weight_class_0': 0.005509380673324586, 'weight_class_1': 0.05411873198577212, 'weight_class_2': 0.03987288152716096}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:22,049] Trial 2499 finished with value: 0.949101171840217 and parameters: {'weight_class_0': 0.005323908931416372, 'weight_class_1': 0.05830677965166485, 'weight_class_2': 0.036651194926913426}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:22,149] Trial 2500 finished with value: 0.9489811995372063 and parameters: {'weight_class_0': 0.005525842241582069, 'weight_class_1': 0.05738214285732433, 'weight_class_2': 0.036956309119683284}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:22,186] Trial 2502 finished with value: 0.9494359493872476 and parameters: {'weight_class_0': 0.005374750057648565, 'weight_class_1': 0.05691887130617102, 'weight_class_2': 0.0695020715004405}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:22,230] Trial 2501 finished with value: 0.9493848257219005 and parameters: {'weight_class_0': 0.005359477409336067, 'weight_class_1': 0.05693720167871771, 'weight_class_2': 0.07303020584552603}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                     | 2510/3000 [00:58<00:14, 33.19it/s]

[I 2026-07-03 10:57:22,233] Trial 2503 finished with value: 0.9479918221850149 and parameters: {'weight_class_0': 0.005163778653956175, 'weight_class_1': 0.03555279537468893, 'weight_class_2': 0.1007195147008391}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:22,242] Trial 2504 finished with value: 0.9486147231555572 and parameters: {'weight_class_0': 0.005364405224025568, 'weight_class_1': 0.03441228514316294, 'weight_class_2': 0.06964466527323822}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:22,289] Trial 2505 finished with value: 0.9481529292076457 and parameters: {'weight_class_0': 0.007693635582463224, 'weight_class_1': 0.03917385563777096, 'weight_class_2': 0.06936416550391429}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:22,297] Trial 2506 finished with value: 0.9474724147072706 and parameters: {'weight_class_0': 0.007752939850716432, 'weight_class_1': 0.03490627495123294, 'weight_class_2': 0.07873154284278337}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:22,366] Trial 2508 finished with value: 0.9482890727115846 and parameters: {'weight_class_0': 0.007776672982084629, 'weight_class_1': 0.041166770368986944, 'weight_class_2': 0.07061145161142096}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:22,367] Trial 2509 finished with value: 0.9472103689133924 and parameters: {'weight_class_0': 0.008018332244820342, 'weight_class_1': 0.03438292678904114, 'weight_class_2': 0.06872776456039922}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:22,376] Trial 2507 finished with value: 0.9484507169882063 and parameters: {'weight_class_0': 0.00777212323207387, 'weight_class_1': 0.04298878327345064, 'weight_class_2': 0.06826427241671267}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:22,441] Trial 2511 finished with value: 0.9487840948595566 and parameters: {'weight_class_0': 0.003967496046813675, 'weight_class_1': 0.04105977039972219, 'weight_class_2': 0.07069914611395306}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  84%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████                     | 2517/3000 [00:58<00:14, 33.36it/s]

[I 2026-07-03 10:57:22,454] Trial 2510 finished with value: 0.9476047306345516 and parameters: {'weight_class_0': 0.007564780028651209, 'weight_class_1': 0.0346045939908301, 'weight_class_2': 0.0691804460354176}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:22,479] Trial 2512 finished with value: 0.9484041056933102 and parameters: {'weight_class_0': 0.007745966572517309, 'weight_class_1': 0.04236168733954409, 'weight_class_2': 0.07101279856447741}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:22,518] Trial 2513 finished with value: 0.9483903623913689 and parameters: {'weight_class_0': 0.007850994546231959, 'weight_class_1': 0.04294771057568377, 'weight_class_2': 0.07574716381114766}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:22,577] Trial 2514 finished with value: 0.9485543092549817 and parameters: {'weight_class_0': 0.00721325431388408, 'weight_class_1': 0.04171482474866433, 'weight_class_2': 0.06412287550343619}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:22,595] Trial 2515 finished with value: 0.924696592269343 and parameters: {'weight_class_0': 0.003996883659309338, 'weight_class_1': 0.04071112026512335, 'weight_class_2': 0.6594044989802391}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:22,621] Trial 2516 finished with value: 0.9495770242324352 and parameters: {'weight_class_0': 0.003931643285881562, 'weight_class_1': 0.04485062770961702, 'weight_class_2': 0.047278743991060176}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:22,657] Trial 2517 finished with value: 0.9495356990221829 and parameters: {'weight_class_0': 0.0038474043859586336, 'weight_class_1': 0.04232329429670274, 'weight_class_2': 0.04680328446944695}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:22,691] Trial 2519 finished with value: 0.9495633862347179 and parameters: {'weight_class_0': 0.003957531786785677, 'weight_class_1': 0.045942776010377336, 'weight_class_2': 0.0486703904523531}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:22,696] Trial 2518 finished with value: 0.9495574459806284 and parameters: {'weight_class_0': 0.004044252102216385, 'weight_class_1': 0.044703755014909544, 'weight_class_2': 0.048130836783114875}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:22,766] Trial 2520 finished with value: 0.9495710823823384 and parameters: {'weight_class_0': 0.0041967807327657, 'weight_class_1': 0.04616154777242239, 'weight_class_2': 0.04773360350600486}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:22,768] Trial 2521 finished with value: 0.8005539057035381 and parameters: {'weight_class_0': 1.8064420497300642, 'weight_class_1': 0.06426958529415001, 'weight_class_2': 0.05004646943212423}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:22,809] Trial 2522 finished with value: 0.9490107477220887 and parameters: {'weight_class_0': 0.0026691177291522363, 'weight_class_1': 0.04994825742999832, 'weight_class_2': 0.049393050390080094}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:22,829] Trial 2523 finished with value: 0.9496020116396348 and parameters: {'weight_class_0': 0.0038531044238809954, 'weight_class_1': 0.06349382608990416, 'weight_class_2': 0.047768322144426285}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:22,829] Trial 2524 finished with value: 0.9488772503687718 and parameters: {'weight_class_0': 0.002662462873746224, 'weight_class_1': 0.06359785340292869, 'weight_class_2': 0.048066446563205044}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  84%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                    | 2532/3000 [00:59<00:13, 34.18it/s]

[I 2026-07-03 10:57:22,865] Trial 2525 finished with value: 0.9496417899354852 and parameters: {'weight_class_0': 0.004071717610355748, 'weight_class_1': 0.06486093200223841, 'weight_class_2': 0.049366385747318754}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:22,925] Trial 2527 finished with value: 0.9496016453824877 and parameters: {'weight_class_0': 0.004318772874773468, 'weight_class_1': 0.063652180230332, 'weight_class_2': 0.046265822350391665}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:22,936] Trial 2526 finished with value: 0.949643004532644 and parameters: {'weight_class_0': 0.004209193262938407, 'weight_class_1': 0.06110575862525315, 'weight_class_2': 0.04961545370836186}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:22,982] Trial 2528 finished with value: 0.9496357663636776 and parameters: {'weight_class_0': 0.004188137519129963, 'weight_class_1': 0.06776156001196329, 'weight_class_2': 0.04910471988753633}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:22,992] Trial 2529 finished with value: 0.9488773649816746 and parameters: {'weight_class_0': 0.002616868896696448, 'weight_class_1': 0.06297884223190743, 'weight_class_2': 0.04680889337282573}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:23,015] Trial 2530 finished with value: 0.947437346642603 and parameters: {'weight_class_0': 0.0025995321404496423, 'weight_class_1': 0.062268030204179155, 'weight_class_2': 0.09953326340973281}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:23,044] Trial 2531 finished with value: 0.949135903157276 and parameters: {'weight_class_0': 0.006027300852627298, 'weight_class_1': 0.062138445047772876, 'weight_class_2': 0.0919847350452178}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:23,097] Trial 2532 finished with value: 0.9476595929147272 and parameters: {'weight_class_0': 0.002720179819530991, 'weight_class_1': 0.05990866154779962, 'weight_class_2': 0.09727543533141968}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████                    | 2540/3000 [00:59<00:13, 33.20it/s]

[I 2026-07-03 10:57:23,109] Trial 2533 finished with value: 0.947534754682691 and parameters: {'weight_class_0': 0.002737849089334132, 'weight_class_1': 0.06505876302507377, 'weight_class_2': 0.09989228129268984}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:23,156] Trial 2534 finished with value: 0.9489448587273478 and parameters: {'weight_class_0': 0.005971245194354201, 'weight_class_1': 0.06491605986475492, 'weight_class_2': 0.10274997433850937}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:23,173] Trial 2535 finished with value: 0.9496478120961331 and parameters: {'weight_class_0': 0.009659145502848744, 'weight_class_1': 0.12485732018747786, 'weight_class_2': 0.08796290432895455}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:23,196] Trial 2536 finished with value: 0.9476626765173957 and parameters: {'weight_class_0': 0.0027058576142805412, 'weight_class_1': 0.06379629251021471, 'weight_class_2': 0.09367255600249823}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:23,231] Trial 2537 finished with value: 0.9492864310151287 and parameters: {'weight_class_0': 0.0060111166874087735, 'weight_class_1': 0.08650642978781045, 'weight_class_2': 0.09838923965595762}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:23,288] Trial 2539 finished with value: 0.9491457822110324 and parameters: {'weight_class_0': 0.006032176447248108, 'weight_class_1': 0.05499343683011354, 'weight_class_2': 0.0888042939675387}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:23,300] Trial 2540 finished with value: 0.9495054511456448 and parameters: {'weight_class_0': 0.0063599744611082774, 'weight_class_1': 0.08473617322067772, 'weight_class_2': 0.08835979536537675}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:23,308] Trial 2538 finished with value: 0.9493537825940144 and parameters: {'weight_class_0': 0.006162894212983966, 'weight_class_1': 0.13001239283612692, 'weight_class_2': 0.08780640880149837}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:23,348] Trial 2541 finished with value: 0.9494399907976799 and parameters: {'weight_class_0': 0.00593144761116849, 'weight_class_1': 0.08591038517417769, 'weight_class_2': 0.08762170804358056}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:23,409] Trial 2542 finished with value: 0.9492924194211859 and parameters: {'weight_class_0': 0.005737190584029277, 'weight_class_1': 0.08643304612268068, 'weight_class_2': 0.08943100192903786}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:23,410] Trial 2543 finished with value: 0.9488039294037282 and parameters: {'weight_class_0': 0.009473699706657547, 'weight_class_1': 0.08702031002554575, 'weight_class_2': 0.05931720910505329}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:23,462] Trial 2544 finished with value: 0.9486735903826268 and parameters: {'weight_class_0': 0.0061529177291055675, 'weight_class_1': 0.1228356976429491, 'weight_class_2': 0.1384253269902705}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:23,465] Trial 2545 finished with value: 0.9487453151722821 and parameters: {'weight_class_0': 0.00979144357872714, 'weight_class_1': 0.08541469800308978, 'weight_class_2': 0.06127339454028059}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:23,529] Trial 2547 finished with value: 0.9495998115142691 and parameters: {'weight_class_0': 0.006183858037158684, 'weight_class_1': 0.08695160699343973, 'weight_class_2': 0.06220592044126378}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:23,532] Trial 2546 finished with value: 0.9496228556062437 and parameters: {'weight_class_0': 0.0062369750823418856, 'weight_class_1': 0.08533537684970187, 'weight_class_2': 0.059498698983274485}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:23,556] Trial 2548 finished with value: 0.9489637125371176 and parameters: {'weight_class_0': 0.0035318404611879785, 'weight_class_1': 0.08457076921771835, 'weight_class_2': 0.06091814989682203}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:23,593] Trial 2549 finished with value: 0.9490630795262286 and parameters: {'weight_class_0': 0.0034738558551544486, 'weight_class_1': 0.052157457621727826, 'weight_class_2': 0.06163436442147869}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:23,648] Trial 2550 finished with value: 0.9490677924435609 and parameters: {'weight_class_0': 0.003422739730562823, 'weight_class_1': 0.05107263745565858, 'weight_class_2': 0.06080814191729137}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:23,651] Trial 2551 finished with value: 0.9487596257922348 and parameters: {'weight_class_0': 0.009411030872915739, 'weight_class_1': 0.08156456422081439, 'weight_class_2': 0.05906597413359393}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:23,654] Trial 2552 finished with value: 0.9491617636307957 and parameters: {'weight_class_0': 0.003507393579464756, 'weight_class_1': 0.051120824015793195, 'weight_class_2': 0.06076012361708302}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:23,688] Trial 2553 finished with value: 0.9490339407780573 and parameters: {'weight_class_0': 0.0033896690775135786, 'weight_class_1': 0.05332004692365534, 'weight_class_2': 0.061501457350808426}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:23,764] Trial 2555 finished with value: 0.9492682988941569 and parameters: {'weight_class_0': 0.0036490777839305335, 'weight_class_1': 0.052963288557931996, 'weight_class_2': 0.06073016723175331}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                   | 2561/3000 [01:00<00:13, 32.48it/s]

[I 2026-07-03 10:57:23,778] Trial 2554 finished with value: 0.949161487581665 and parameters: {'weight_class_0': 0.003488803850113217, 'weight_class_1': 0.05131302087947942, 'weight_class_2': 0.0604820663172941}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:23,791] Trial 2556 finished with value: 0.9490693637218236 and parameters: {'weight_class_0': 0.003330356523647129, 'weight_class_1': 0.05075921397204098, 'weight_class_2': 0.05923839786382733}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:23,849] Trial 2557 finished with value: 0.9495947605665022 and parameters: {'weight_class_0': 0.0034562876505564093, 'weight_class_1': 0.05258303373154148, 'weight_class_2': 0.036480074231699376}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:23,894] Trial 2558 finished with value: 0.8500309515827342 and parameters: {'weight_class_0': 0.09278345624814342, 'weight_class_1': 0.051165734671158175, 'weight_class_2': 0.03708502928087585}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:23,904] Trial 2559 finished with value: 0.9493384212595046 and parameters: {'weight_class_0': 0.004689582691091661, 'weight_class_1': 0.05114457514833411, 'weight_class_2': 0.035649272552356844}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:23,922] Trial 2560 finished with value: 0.9494586735850081 and parameters: {'weight_class_0': 0.004671317976217567, 'weight_class_1': 0.04877697887102526, 'weight_class_2': 0.037438965019743344}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:23,951] Trial 2561 finished with value: 0.9492387816550437 and parameters: {'weight_class_0': 0.004964681956080145, 'weight_class_1': 0.04921801238148842, 'weight_class_2': 0.03660895163468059}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:23,985] Trial 2562 finished with value: 0.9495852192835298 and parameters: {'weight_class_0': 0.004394554651484512, 'weight_class_1': 0.05153335466737794, 'weight_class_2': 0.03574638296959665}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:24,003] Trial 2563 finished with value: 0.9138281596122164 and parameters: {'weight_class_0': 0.004690624710537834, 'weight_class_1': 0.004115776498677867, 'weight_class_2': 0.03493106744600393}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:24,026] Trial 2564 finished with value: 0.9496266811216502 and parameters: {'weight_class_0': 0.004505895706787647, 'weight_class_1': 0.05035394024755525, 'weight_class_2': 0.038507482837406744}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:24,056] Trial 2565 finished with value: 0.9491867021765606 and parameters: {'weight_class_0': 0.004702980089677791, 'weight_class_1': 0.03348030715780413, 'weight_class_2': 0.038260402609515465}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:24,113] Trial 2566 finished with value: 0.9489866054908801 and parameters: {'weight_class_0': 0.004907755060247915, 'weight_class_1': 0.03535341955062511, 'weight_class_2': 0.03728158777865885}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:24,135] Trial 2567 finished with value: 0.9493038617268251 and parameters: {'weight_class_0': 0.004645456493395395, 'weight_class_1': 0.03538879410823629, 'weight_class_2': 0.0393759139857142}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:24,159] Trial 2568 finished with value: 0.9494012216246502 and parameters: {'weight_class_0': 0.004666228147532998, 'weight_class_1': 0.07345354941345296, 'weight_class_2': 0.03555407351821364}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:24,179] Trial 2569 finished with value: 0.9495626073464495 and parameters: {'weight_class_0': 0.004456064548860243, 'weight_class_1': 0.07232843440565229, 'weight_class_2': 0.03542143236693498}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:24,256] Trial 2570 finished with value: 0.8060208578700719 and parameters: {'weight_class_0': 0.0047458048408411165, 'weight_class_1': 2.042264205760013, 'weight_class_2': 0.07873228326112011}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:24,264] Trial 2571 finished with value: 0.9491345521301283 and parameters: {'weight_class_0': 0.004505220700659677, 'weight_class_1': 0.07030416478646033, 'weight_class_2': 0.07867083179633888}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:24,292] Trial 2572 finished with value: 0.9480638741651121 and parameters: {'weight_class_0': 0.004599110289548384, 'weight_class_1': 0.07273808392598384, 'weight_class_2': 0.13196271685010716}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:24,297] Trial 2573 finished with value: 0.8370796451100643 and parameters: {'weight_class_0': 0.004607463112253306, 'weight_class_1': 1.5793984363839475, 'weight_class_2': 0.07962873550498027}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:24,376] Trial 2574 finished with value: 0.9471362298967666 and parameters: {'weight_class_0': 0.007579288752498249, 'weight_class_1': 0.032772185508904435, 'weight_class_2': 0.07985292197967034}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                  | 2582/3000 [01:00<00:11, 35.06it/s]

[I 2026-07-03 10:57:24,400] Trial 2575 finished with value: 0.9477459749577742 and parameters: {'weight_class_0': 0.007172091226410655, 'weight_class_1': 0.03403805123408963, 'weight_class_2': 0.07649404363174953}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:24,410] Trial 2576 finished with value: 0.9487881281205327 and parameters: {'weight_class_0': 0.007306102012902668, 'weight_class_1': 0.07105425502403363, 'weight_class_2': 0.1255499646679017}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:24,439] Trial 2577 finished with value: 0.949507627099711 and parameters: {'weight_class_0': 0.007368811647014675, 'weight_class_1': 0.07298132603129691, 'weight_class_2': 0.07950883746795816}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:24,453] Trial 2579 finished with value: 0.9491406965342999 and parameters: {'weight_class_0': 0.007267119174833699, 'weight_class_1': 0.10806576667220327, 'weight_class_2': 0.12690953079460165}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:24,453] Trial 2578 finished with value: 0.9486255890879685 and parameters: {'weight_class_0': 0.007476835802395586, 'weight_class_1': 0.0671647659122208, 'weight_class_2': 0.04350369629198815}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:24,528] Trial 2580 finished with value: 0.949579337934558 and parameters: {'weight_class_0': 0.00705624529546693, 'weight_class_1': 0.11574131541554554, 'weight_class_2': 0.07469515424531849}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:24,564] Trial 2581 finished with value: 0.9494941369762501 and parameters: {'weight_class_0': 0.006739770709087776, 'weight_class_1': 0.07154309361437076, 'weight_class_2': 0.08074816783196939}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:24,584] Trial 2582 finished with value: 0.9486161439907069 and parameters: {'weight_class_0': 0.008177529466425408, 'weight_class_1': 0.10342402202379078, 'weight_class_2': 0.04479935516867947}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                  | 2584/3000 [01:00<00:12, 34.24it/s]

[I 2026-07-03 10:57:24,601] Trial 2583 finished with value: 0.9490947021167498 and parameters: {'weight_class_0': 0.0067323571524172355, 'weight_class_1': 0.1215462415373992, 'weight_class_2': 0.04559395754097024}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:24,635] Trial 2584 finished with value: 0.9488174977123225 and parameters: {'weight_class_0': 0.007686889600233014, 'weight_class_1': 0.11139186371561366, 'weight_class_2': 0.0451449313542051}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                 | 2588/3000 [01:00<00:13, 31.04it/s]

[I 2026-07-03 10:57:24,661] Trial 2585 finished with value: 0.9483360278066204 and parameters: {'weight_class_0': 0.007082805180666749, 'weight_class_1': 0.11480285201407174, 'weight_class_2': 0.1791610853906489}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:24,721] Trial 2586 finished with value: 0.9491215273732441 and parameters: {'weight_class_0': 0.006943554994943562, 'weight_class_1': 0.11644875630386693, 'weight_class_2': 0.04664291700373049}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:24,773] Trial 2587 finished with value: 0.9485992436996216 and parameters: {'weight_class_0': 0.002702242638740264, 'weight_class_1': 0.09383937410890093, 'weight_class_2': 0.04532518567146571}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:24,808] Trial 2588 finished with value: 0.9449999073522939 and parameters: {'weight_class_0': 0.0027824930276182025, 'weight_class_1': 0.12784763476816116, 'weight_class_2': 0.17727053636810494}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                 | 2589/3000 [01:00<00:13, 31.04it/s]

[I 2026-07-03 10:57:24,824] Trial 2589 finished with value: 0.9486143670416235 and parameters: {'weight_class_0': 0.0028358809790092667, 'weight_class_1': 0.09961116885351874, 'weight_class_2': 0.045878741410991616}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                 | 2592/3000 [01:01<00:14, 28.06it/s]

[I 2026-07-03 10:57:24,892] Trial 2590 finished with value: 0.9483986203615643 and parameters: {'weight_class_0': 0.002914680031618597, 'weight_class_1': 0.11438590614086386, 'weight_class_2': 0.04652744021361423}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:24,912] Trial 2591 finished with value: 0.9493482157701626 and parameters: {'weight_class_0': 0.002941838797572035, 'weight_class_1': 0.04142225340786424, 'weight_class_2': 0.045602100061355066}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:24,934] Trial 2592 finished with value: 0.9484958092658727 and parameters: {'weight_class_0': 0.0028972469781241295, 'weight_class_1': 0.09810140920238239, 'weight_class_2': 0.05172957795208481}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                 | 2594/3000 [01:01<00:14, 28.06it/s]

[I 2026-07-03 10:57:24,960] Trial 2593 finished with value: 0.9455170829861391 and parameters: {'weight_class_0': 0.002759112338485987, 'weight_class_1': 0.043156042305606886, 'weight_class_2': 0.17784861641420785}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:25,009] Trial 2594 finished with value: 0.94908680215151 and parameters: {'weight_class_0': 0.0027263808905469205, 'weight_class_1': 0.04156948562139923, 'weight_class_2': 0.048244327893641775}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  87%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                 | 2596/3000 [01:01<00:13, 29.97it/s]

[I 2026-07-03 10:57:25,019] Trial 2595 finished with value: 0.9490958342580642 and parameters: {'weight_class_0': 0.005698906934598769, 'weight_class_1': 0.03932482162508571, 'weight_class_2': 0.0535290505406792}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:25,025] Trial 2596 finished with value: 0.8115915752408508 and parameters: {'weight_class_0': 0.6533673955919158, 'weight_class_1': 0.04195697244305012, 'weight_class_2': 0.05364730402758632}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  87%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 2600/3000 [01:01<00:12, 31.29it/s]

[I 2026-07-03 10:57:25,056] Trial 2597 finished with value: 0.9487477385689616 and parameters: {'weight_class_0': 0.003115783567731357, 'weight_class_1': 0.09653059957184165, 'weight_class_2': 0.0529507504098896}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:25,125] Trial 2598 finished with value: 0.9487692734903806 and parameters: {'weight_class_0': 0.0027326122318298064, 'weight_class_1': 0.04170195838106755, 'weight_class_2': 0.056743213069825424}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:25,136] Trial 2599 finished with value: 0.9491538299920846 and parameters: {'weight_class_0': 0.0054943576819199095, 'weight_class_1': 0.04057327155208845, 'weight_class_2': 0.0555908694378258}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:25,163] Trial 2600 finished with value: 0.9492967615761412 and parameters: {'weight_class_0': 0.005743376036634996, 'weight_class_1': 0.04488736088652561, 'weight_class_2': 0.054747230169633995}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:25,167] Trial 2601 finished with value: 0.9490835973694577 and parameters: {'weight_class_0': 0.005611304664676416, 'weight_class_1': 0.038909799401592886, 'weight_class_2': 0.053830904800986464}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  87%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                 | 2602/3000 [01:01<00:12, 31.29it/s]

[I 2026-07-03 10:57:25,268] Trial 2602 finished with value: 0.9492513313704322 and parameters: {'weight_class_0': 0.0052780911609157065, 'weight_class_1': 0.040843025600003365, 'weight_class_2': 0.055720273102722005}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  87%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                 | 2603/3000 [01:01<00:12, 31.29it/s]

[I 2026-07-03 10:57:25,315] Trial 2604 finished with value: 0.9495472688704897 and parameters: {'weight_class_0': 0.005766533149247924, 'weight_class_1': 0.059894388698583496, 'weight_class_2': 0.05564601658528602}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  87%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                 | 2606/3000 [01:01<00:13, 30.11it/s]

[I 2026-07-03 10:57:25,335] Trial 2603 finished with value: 0.949539881971582 and parameters: {'weight_class_0': 0.005480883792609509, 'weight_class_1': 0.058545002162684726, 'weight_class_2': 0.05505188264551573}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:25,359] Trial 2605 finished with value: 0.9495087248711798 and parameters: {'weight_class_0': 0.00554006464148645, 'weight_class_1': 0.05881290604501893, 'weight_class_2': 0.06315262424665609}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:25,429] Trial 2606 finished with value: 0.9495448264510497 and parameters: {'weight_class_0': 0.00547235520210635, 'weight_class_1': 0.057294109245801354, 'weight_class_2': 0.06336436960863306}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:25,475] Trial 2607 finished with value: 0.7474146895950845 and parameters: {'weight_class_0': 0.0054020862461941046, 'weight_class_1': 3.5085588786297093, 'weight_class_2': 0.06486898942317582}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████                 | 2608/3000 [01:01<00:13, 29.10it/s]

[I 2026-07-03 10:57:25,489] Trial 2608 finished with value: 0.948430309244471 and parameters: {'weight_class_0': 0.00944456397025165, 'weight_class_1': 0.05855139330840989, 'weight_class_2': 0.0664243082454508}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:25,502] Trial 2609 finished with value: 0.9487127763648018 and parameters: {'weight_class_0': 0.009142862015999441, 'weight_class_1': 0.05964886671942835, 'weight_class_2': 0.11399168568724498}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                | 2613/3000 [01:01<00:13, 29.24it/s]

[I 2026-07-03 10:57:25,546] Trial 2610 finished with value: 0.9480614070526753 and parameters: {'weight_class_0': 0.0037817981631225505, 'weight_class_1': 0.058076381630575005, 'weight_class_2': 0.10723803235706336}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:25,567] Trial 2611 finished with value: 0.9489921702669782 and parameters: {'weight_class_0': 0.003710321322177604, 'weight_class_1': 0.05888650721822759, 'weight_class_2': 0.06891073065996127}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:25,594] Trial 2612 finished with value: 0.9486915090298149 and parameters: {'weight_class_0': 0.009308624846855153, 'weight_class_1': 0.058743695032016506, 'weight_class_2': 0.11012228144751715}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:25,606] Trial 2613 finished with value: 0.9487412618609836 and parameters: {'weight_class_0': 0.00954403680337551, 'weight_class_1': 0.060345902334101566, 'weight_class_2': 0.10904831299316996}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                | 2614/3000 [01:01<00:13, 29.24it/s]

[I 2026-07-03 10:57:25,672] Trial 2614 finished with value: 0.9442665764491229 and parameters: {'weight_class_0': 0.009466149257644316, 'weight_class_1': 0.0764675793195128, 'weight_class_2': 0.030534936941334523}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                | 2616/3000 [01:01<00:12, 31.32it/s]

[I 2026-07-03 10:57:25,709] Trial 2616 finished with value: 0.9493753070519187 and parameters: {'weight_class_0': 0.004023636036947071, 'weight_class_1': 0.06965480001243085, 'weight_class_2': 0.030740614287320726}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:25,727] Trial 2615 finished with value: 0.9479825192459567 and parameters: {'weight_class_0': 0.003731740712018053, 'weight_class_1': 0.08084394975706753, 'weight_class_2': 0.11388438345749488}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                | 2620/3000 [01:02<00:13, 29.22it/s]

[I 2026-07-03 10:57:25,736] Trial 2617 finished with value: 0.9494106227981046 and parameters: {'weight_class_0': 0.008932281277165676, 'weight_class_1': 0.08268126298456874, 'weight_class_2': 0.10905285271438023}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:25,758] Trial 2618 finished with value: 0.9481656853313766 and parameters: {'weight_class_0': 0.0038685242606249807, 'weight_class_1': 0.07975966575519398, 'weight_class_2': 0.10988216803224737}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:25,874] Trial 2620 finished with value: 0.9495294698245015 and parameters: {'weight_class_0': 0.003753381015558784, 'weight_class_1': 0.0777032004312415, 'weight_class_2': 0.03127740767328156}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:25,889] Trial 2619 finished with value: 0.9494964736976979 and parameters: {'weight_class_0': 0.0038359227883707965, 'weight_class_1': 0.0747538807503226, 'weight_class_2': 0.03033645330943193}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                | 2622/3000 [01:02<00:12, 29.22it/s]

[I 2026-07-03 10:57:25,920] Trial 2621 finished with value: 0.949490303703819 and parameters: {'weight_class_0': 0.0036769624107031904, 'weight_class_1': 0.08029378259683385, 'weight_class_2': 0.030456747288615683}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:25,944] Trial 2622 finished with value: 0.9495079942299619 and parameters: {'weight_class_0': 0.003945294847659146, 'weight_class_1': 0.0772971494644232, 'weight_class_2': 0.03135323466826276}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                | 2627/3000 [01:02<00:12, 29.05it/s]

[I 2026-07-03 10:57:26,020] Trial 2623 finished with value: 0.9489288048555179 and parameters: {'weight_class_0': 0.0037777080044862025, 'weight_class_1': 0.0785431421026371, 'weight_class_2': 0.07387524896773465}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:26,032] Trial 2624 finished with value: 0.9489846612814011 and parameters: {'weight_class_0': 0.0039056784437790687, 'weight_class_1': 0.07783881600651497, 'weight_class_2': 0.07313256372458214}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:26,075] Trial 2626 finished with value: 0.9489280930198324 and parameters: {'weight_class_0': 0.003866483038784625, 'weight_class_1': 0.08026033196743432, 'weight_class_2': 0.07559403904913452}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:26,083] Trial 2625 finished with value: 0.9495072943192152 and parameters: {'weight_class_0': 0.003798016179376856, 'weight_class_1': 0.07975507646867443, 'weight_class_2': 0.030855379280162798}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:26,125] Trial 2629 finished with value: 0.9487217656494481 and parameters: {'weight_class_0': 0.003702997004419205, 'weight_class_1': 0.048787155101656814, 'weight_class_2': 0.07761831879112906}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:26,128] Trial 2628 finished with value: 0.9410258740132486 and parameters: {'weight_class_0': 0.012721526802993566, 'weight_class_1': 0.03271306041260722, 'weight_class_2': 0.08197859291194473}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:26,151] Trial 2627 finished with value: 0.9489147794819329 and parameters: {'weight_class_0': 0.012516956444929507, 'weight_class_1': 0.17142097557242614, 'weight_class_2': 0.07607626382395621}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:26,201] Trial 2630 finished with value: 0.9476769457903013 and parameters: {'weight_class_0': 0.0036653776268180814, 'weight_class_1': 0.1556359172039061, 'weight_class_2': 0.07830356093901547}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:26,249] Trial 2631 finished with value: 0.9484584116755231 and parameters: {'weight_class_0': 0.004585212105137454, 'weight_class_1': 0.1724176821241161, 'weight_class_2': 0.07451786451183097}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:26,270] Trial 2633 finished with value: 0.949234313393713 and parameters: {'weight_class_0': 0.011509410363984656, 'weight_class_1': 0.16101590914804714, 'weight_class_2': 0.08057625842225034}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:26,270] Trial 2632 finished with value: 0.9487651901474418 and parameters: {'weight_class_0': 0.004261979389410047, 'weight_class_1': 0.04705995251551236, 'weight_class_2': 0.07826881056770393}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏               | 2636/3000 [01:02<00:12, 29.57it/s]

[I 2026-07-03 10:57:26,289] Trial 2634 finished with value: 0.944734020187474 and parameters: {'weight_class_0': 0.01147785257987778, 'weight_class_1': 0.04557969733557813, 'weight_class_2': 0.3587308986091904}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:26,397] Trial 2636 finished with value: 0.9491997463080777 and parameters: {'weight_class_0': 0.004663535624322779, 'weight_class_1': 0.03293815113817296, 'weight_class_2': 0.04230066350590269}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:26,407] Trial 2635 finished with value: 0.9492307214789565 and parameters: {'weight_class_0': 0.004734946924072382, 'weight_class_1': 0.033488830189482816, 'weight_class_2': 0.04036402651097371}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍               | 2640/3000 [01:02<00:11, 30.26it/s]

[I 2026-07-03 10:57:26,439] Trial 2637 finished with value: 0.9491489453506183 and parameters: {'weight_class_0': 0.004846400885782635, 'weight_class_1': 0.033887527134063886, 'weight_class_2': 0.04182341573119324}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:26,440] Trial 2638 finished with value: 0.9488511097256099 and parameters: {'weight_class_0': 0.004821954465593537, 'weight_class_1': 0.1676548654771022, 'weight_class_2': 0.041326104681650065}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:26,509] Trial 2639 finished with value: 0.9491676701737156 and parameters: {'weight_class_0': 0.004811726854066891, 'weight_class_1': 0.033670478516660114, 'weight_class_2': 0.042295424865519356}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:26,513] Trial 2640 finished with value: 0.9489664872998033 and parameters: {'weight_class_0': 0.004905870817810551, 'weight_class_1': 0.032337556208040116, 'weight_class_2': 0.04004323819636998}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌               | 2643/3000 [01:02<00:11, 30.26it/s]

[I 2026-07-03 10:57:26,555] Trial 2641 finished with value: 0.9495657297132171 and parameters: {'weight_class_0': 0.0048112730006454, 'weight_class_1': 0.04847155397001382, 'weight_class_2': 0.04221081890483994}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:26,608] Trial 2642 finished with value: 0.94946265889961 and parameters: {'weight_class_0': 0.0051465640166932424, 'weight_class_1': 0.048070424975104, 'weight_class_2': 0.04150701000694339}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:26,652] Trial 2643 finished with value: 0.9495064935249663 and parameters: {'weight_class_0': 0.005025893904229267, 'weight_class_1': 0.05026680969899238, 'weight_class_2': 0.041730716822598074}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋               | 2646/3000 [01:02<00:11, 29.79it/s]

[I 2026-07-03 10:57:26,722] Trial 2645 finished with value: 0.9493067693569195 and parameters: {'weight_class_0': 0.005216581863987977, 'weight_class_1': 0.05230716499069863, 'weight_class_2': 0.0397498375248386}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:26,725] Trial 2644 finished with value: 0.9488749382491587 and parameters: {'weight_class_0': 0.006070575723159838, 'weight_class_1': 0.04782274352612169, 'weight_class_2': 0.041850157171957385}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:26,737] Trial 2646 finished with value: 0.9488427965538989 and parameters: {'weight_class_0': 0.005183230096234611, 'weight_class_1': 0.03207024115145801, 'weight_class_2': 0.042642475792115185}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊               | 2650/3000 [01:03<00:12, 28.20it/s]

[I 2026-07-03 10:57:26,803] Trial 2647 finished with value: 0.9495703691610914 and parameters: {'weight_class_0': 0.005966148821542438, 'weight_class_1': 0.09344192487773108, 'weight_class_2': 0.05908542439714144}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:26,825] Trial 2648 finished with value: 0.9495596538027726 and parameters: {'weight_class_0': 0.005781609894243631, 'weight_class_1': 0.09589353952914305, 'weight_class_2': 0.060659719734855844}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:26,843] Trial 2649 finished with value: 0.9492597373465443 and parameters: {'weight_class_0': 0.006317416680102768, 'weight_class_1': 0.050129665086069836, 'weight_class_2': 0.06563657274979096}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:26,860] Trial 2650 finished with value: 0.9496192687691439 and parameters: {'weight_class_0': 0.006667923668603564, 'weight_class_1': 0.09796270658727277, 'weight_class_2': 0.06258761290495035}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉               | 2653/3000 [01:03<00:11, 29.17it/s]

[I 2026-07-03 10:57:26,924] Trial 2652 finished with value: 0.9495701477507538 and parameters: {'weight_class_0': 0.006393955149178565, 'weight_class_1': 0.09715478857044181, 'weight_class_2': 0.0634053907341508}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:26,934] Trial 2651 finished with value: 0.9495901906736335 and parameters: {'weight_class_0': 0.006436892150054646, 'weight_class_1': 0.09607695907597771, 'weight_class_2': 0.062032171810278695}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:26,994] Trial 2653 finished with value: 0.9495709753841628 and parameters: {'weight_class_0': 0.005938079494727472, 'weight_class_1': 0.09853654962515611, 'weight_class_2': 0.06402126670123814}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  89%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏              | 2658/3000 [01:03<00:11, 30.25it/s]

[I 2026-07-03 10:57:27,033] Trial 2655 finished with value: 0.9484388217169372 and parameters: {'weight_class_0': 0.006244002949410874, 'weight_class_1': 0.2538184091558861, 'weight_class_2': 0.06552749006925938}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:27,036] Trial 2654 finished with value: 0.9495854365718306 and parameters: {'weight_class_0': 0.006538031208134597, 'weight_class_1': 0.06648250129017425, 'weight_class_2': 0.0640580376222674}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:27,090] Trial 2656 finished with value: 0.9484755152334777 and parameters: {'weight_class_0': 0.0031161813273770976, 'weight_class_1': 0.09652162756049387, 'weight_class_2': 0.06264602235403417}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:27,096] Trial 2657 finished with value: 0.8929797042421826 and parameters: {'weight_class_0': 0.007066939731324486, 'weight_class_1': 0.09482199312686586, 'weight_class_2': 0.0017100368927482868}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:27,153] Trial 2658 finished with value: 0.8872650330893711 and parameters: {'weight_class_0': 0.006764940319530177, 'weight_class_1': 0.0016845539352305162, 'weight_class_2': 0.06349520063429102}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  89%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎              | 2660/3000 [01:03<00:11, 29.67it/s]

[I 2026-07-03 10:57:27,215] Trial 2660 finished with value: 0.9480975618447512 and parameters: {'weight_class_0': 0.0031220767127183736, 'weight_class_1': 0.06643543575204792, 'weight_class_2': 0.09201495564330596}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:27,225] Trial 2659 finished with value: 0.9483638622254357 and parameters: {'weight_class_0': 0.008253994544939452, 'weight_class_1': 0.06496945001198277, 'weight_class_2': 0.15037918695881144}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:27,228] Trial 2661 finished with value: 0.9492957608591004 and parameters: {'weight_class_0': 0.0031861069697419597, 'weight_class_1': 0.06574134594055045, 'weight_class_2': 0.049968633155276686}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:27,298] Trial 2662 finished with value: 0.9491912993270853 and parameters: {'weight_class_0': 0.0031134288527441102, 'weight_class_1': 0.06593171575875363, 'weight_class_2': 0.0517871174285363}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:27,352] Trial 2663 finished with value: 0.9033061960025206 and parameters: {'weight_class_0': 0.003223392689104709, 'weight_class_1': 0.001890879868929909, 'weight_class_2': 0.09354307518867958}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:27,390] Trial 2665 finished with value: 0.949301502470706 and parameters: {'weight_class_0': 0.003397673607633422, 'weight_class_1': 0.06814459730554395, 'weight_class_2': 0.053271456070487326}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  89%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌              | 2667/3000 [01:03<00:11, 28.66it/s]

[I 2026-07-03 10:57:27,399] Trial 2664 finished with value: 0.9479114442354145 and parameters: {'weight_class_0': 0.0029902541577991235, 'weight_class_1': 0.06790542184273816, 'weight_class_2': 0.09380034578659474}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:27,409] Trial 2666 finished with value: 0.9468881868564236 and parameters: {'weight_class_0': 0.0031743662958340197, 'weight_class_1': 0.06492834132970515, 'weight_class_2': 0.1486131755398044}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:27,460] Trial 2668 finished with value: 0.949337849010115 and parameters: {'weight_class_0': 0.003272595253528301, 'weight_class_1': 0.057821109916595774, 'weight_class_2': 0.05061346895787358}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  89%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋              | 2670/3000 [01:03<00:10, 30.44it/s]

[I 2026-07-03 10:57:27,461] Trial 2669 finished with value: 0.9494602369170124 and parameters: {'weight_class_0': 0.0033988765486533392, 'weight_class_1': 0.06489250236580467, 'weight_class_2': 0.049005275663713425}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:27,475] Trial 2667 finished with value: 0.9479933036814708 and parameters: {'weight_class_0': 0.003065373581578111, 'weight_class_1': 0.06793509703909356, 'weight_class_2': 0.09272677569312339}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:27,535] Trial 2670 finished with value: 0.9481320323778416 and parameters: {'weight_class_0': 0.0032198240027508803, 'weight_class_1': 0.06040928567340307, 'weight_class_2': 0.09333365122139244}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  89%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊              | 2674/3000 [01:03<00:11, 29.58it/s]

[I 2026-07-03 10:57:27,641] Trial 2671 finished with value: 0.9480272307131156 and parameters: {'weight_class_0': 0.0032212202839197396, 'weight_class_1': 0.0556464286804079, 'weight_class_2': 0.09575890301084343}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:27,642] Trial 2672 finished with value: 0.8410969461344658 and parameters: {'weight_class_0': 0.14476152718595442, 'weight_class_1': 0.05533958279850029, 'weight_class_2': 0.0513148281978538}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:27,644] Trial 2673 finished with value: 0.948927388812311 and parameters: {'weight_class_0': 0.008132817411669943, 'weight_class_1': 0.05551496466383898, 'weight_class_2': 0.09607446845957579}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:27,705] Trial 2675 finished with value: 0.9491231367756848 and parameters: {'weight_class_0': 0.004274291952587095, 'weight_class_1': 0.1350118157607468, 'weight_class_2': 0.051126953409091624}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  89%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████              | 2679/3000 [01:03<00:10, 31.26it/s]

[I 2026-07-03 10:57:27,709] Trial 2674 finished with value: 0.9357171363849344 and parameters: {'weight_class_0': 0.008465609302378791, 'weight_class_1': 0.7639562015275938, 'weight_class_2': 0.03347069449050581}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:27,750] Trial 2676 finished with value: 0.947242290119287 and parameters: {'weight_class_0': 0.008388493996693686, 'weight_class_1': 0.1384109394830873, 'weight_class_2': 0.036164986654703975}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:27,795] Trial 2678 finished with value: 0.9452645170552553 and parameters: {'weight_class_0': 0.0082763533075229, 'weight_class_1': 0.04044154921793907, 'weight_class_2': 0.03411308730047128}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:27,827] Trial 2677 finished with value: 0.9446147596845699 and parameters: {'weight_class_0': 0.008581185228439762, 'weight_class_1': 0.038441446466247794, 'weight_class_2': 0.03450150164267078}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:27,832] Trial 2679 finished with value: 0.9472667080318611 and parameters: {'weight_class_0': 0.008004921858337179, 'weight_class_1': 0.1350289202692838, 'weight_class_2': 0.03466502966806994}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  89%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏             | 2682/3000 [01:04<00:10, 31.76it/s]

[I 2026-07-03 10:57:27,900] Trial 2680 finished with value: 0.9494422178076182 and parameters: {'weight_class_0': 0.00431021126557393, 'weight_class_1': 0.03972281267669726, 'weight_class_2': 0.03444609642435472}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:27,932] Trial 2682 finished with value: 0.9449922452386682 and parameters: {'weight_class_0': 0.008533828721502778, 'weight_class_1': 0.041150175379333465, 'weight_class_2': 0.03404556868109452}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:27,946] Trial 2681 finished with value: 0.9489149315848153 and parameters: {'weight_class_0': 0.0025609227815583963, 'weight_class_1': 0.04362599094408309, 'weight_class_2': 0.05033166548270456}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍             | 2686/3000 [01:04<00:10, 30.41it/s]

[I 2026-07-03 10:57:27,976] Trial 2683 finished with value: 0.9487820271769154 and parameters: {'weight_class_0': 0.004289903827740794, 'weight_class_1': 0.13649763476882243, 'weight_class_2': 0.03304392684262131}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:28,011] Trial 2684 finished with value: 0.9486589898601344 and parameters: {'weight_class_0': 0.004330088660705367, 'weight_class_1': 0.13726973595397293, 'weight_class_2': 0.03172448409117465}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:28,062] Trial 2686 finished with value: 0.9492873045949665 and parameters: {'weight_class_0': 0.004152120089056968, 'weight_class_1': 0.0399806868798495, 'weight_class_2': 0.0320393098541211}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:28,078] Trial 2685 finished with value: 0.9494591750178388 and parameters: {'weight_class_0': 0.004288317547700526, 'weight_class_1': 0.041811420834778734, 'weight_class_2': 0.035535357559795845}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌             | 2689/3000 [01:04<00:10, 30.41it/s]

[I 2026-07-03 10:57:28,108] Trial 2687 finished with value: 0.9495324439883429 and parameters: {'weight_class_0': 0.0025406896354755537, 'weight_class_1': 0.03983221599550883, 'weight_class_2': 0.035047113119220395}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:28,113] Trial 2688 finished with value: 0.9488562738248554 and parameters: {'weight_class_0': 0.0025943937505018976, 'weight_class_1': 0.040284529008011515, 'weight_class_2': 0.052631377658723874}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:28,184] Trial 2691 finished with value: 0.9494869315623674 and parameters: {'weight_class_0': 0.004214623127606233, 'weight_class_1': 0.04237707521061778, 'weight_class_2': 0.05168565199409935}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋             | 2694/3000 [01:04<00:09, 32.62it/s]

[I 2026-07-03 10:57:28,186] Trial 2689 finished with value: 0.9493555807105577 and parameters: {'weight_class_0': 0.005564671676289234, 'weight_class_1': 0.044846346944492875, 'weight_class_2': 0.04693368067912718}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:28,187] Trial 2690 finished with value: 0.9495356272259311 and parameters: {'weight_class_0': 0.004346371244518575, 'weight_class_1': 0.04271510240638136, 'weight_class_2': 0.049890662921238726}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:28,227] Trial 2692 finished with value: 0.9495196015219042 and parameters: {'weight_class_0': 0.004253619152434559, 'weight_class_1': 0.04632888961079125, 'weight_class_2': 0.054102929110389726}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:28,280] Trial 2693 finished with value: 0.9491101176358496 and parameters: {'weight_class_0': 0.004265110566285408, 'weight_class_1': 0.05178580997174958, 'weight_class_2': 0.07247487499763944}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:28,282] Trial 2694 finished with value: 0.9490483877252025 and parameters: {'weight_class_0': 0.004252938523026467, 'weight_class_1': 0.04888045479281166, 'weight_class_2': 0.0727404919112571}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊             | 2696/3000 [01:04<00:09, 32.62it/s]

[I 2026-07-03 10:57:28,337] Trial 2695 finished with value: 0.9237603402000722 and parameters: {'weight_class_0': 0.0025205374709364146, 'weight_class_1': 0.050684082674276654, 'weight_class_2': 0.0036098060775285896}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:28,375] Trial 2696 finished with value: 0.9492376104869291 and parameters: {'weight_class_0': 0.005689712588082671, 'weight_class_1': 0.04864253708133418, 'weight_class_2': 0.07507225029861155}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  90%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████             | 2701/3000 [01:04<00:09, 31.26it/s]

[I 2026-07-03 10:57:28,435] Trial 2698 finished with value: 0.9493744340584107 and parameters: {'weight_class_0': 0.005941190049288726, 'weight_class_1': 0.05421260999775264, 'weight_class_2': 0.07485566579198863}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:28,440] Trial 2697 finished with value: 0.9491366201921698 and parameters: {'weight_class_0': 0.005470411493023154, 'weight_class_1': 0.05213404958768485, 'weight_class_2': 0.08196899724044822}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:28,463] Trial 2699 finished with value: 0.9492908495077389 and parameters: {'weight_class_0': 0.005349726946339709, 'weight_class_1': 0.04969103554971573, 'weight_class_2': 0.07047847403559943}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:28,511] Trial 2700 finished with value: 0.9493121560561758 and parameters: {'weight_class_0': 0.005398078474602212, 'weight_class_1': 0.052118283802426946, 'weight_class_2': 0.07312766765183722}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:28,539] Trial 2701 finished with value: 0.8061605997850737 and parameters: {'weight_class_0': 0.005935515795675706, 'weight_class_1': 0.08269945242553181, 'weight_class_2': 2.821104587289733}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  90%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏            | 2703/3000 [01:04<00:09, 32.43it/s]

[I 2026-07-03 10:57:28,576] Trial 2702 finished with value: 0.9493553711020825 and parameters: {'weight_class_0': 0.005575173875859885, 'weight_class_1': 0.05473805284630856, 'weight_class_2': 0.07444850213929645}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:28,590] Trial 2703 finished with value: 0.9493749841494784 and parameters: {'weight_class_0': 0.005429098612966996, 'weight_class_1': 0.053341290479265085, 'weight_class_2': 0.07220261838023352}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  90%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎            | 2708/3000 [01:04<00:08, 32.50it/s]

[I 2026-07-03 10:57:28,598] Trial 2704 finished with value: 0.949598583075208 and parameters: {'weight_class_0': 0.005406320722205171, 'weight_class_1': 0.07850649178086669, 'weight_class_2': 0.07148376480494334}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:28,651] Trial 2705 finished with value: 0.7040223891487191 and parameters: {'weight_class_0': 8.039501350144803, 'weight_class_1': 0.08512461122027506, 'weight_class_2': 0.07921683739326378}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:28,701] Trial 2706 finished with value: 0.9494786978909958 and parameters: {'weight_class_0': 0.005405228822004978, 'weight_class_1': 0.0810454563045673, 'weight_class_2': 0.0774762896743793}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:28,719] Trial 2707 finished with value: 0.949445425982426 and parameters: {'weight_class_0': 0.005581775776771935, 'weight_class_1': 0.08218970692628287, 'weight_class_2': 0.0824412025655942}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:28,725] Trial 2708 finished with value: 0.949478693575932 and parameters: {'weight_class_0': 0.005665236588842558, 'weight_class_1': 0.08220673095797831, 'weight_class_2': 0.08038980225342916}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  90%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍            | 2710/3000 [01:04<00:08, 33.22it/s]

[I 2026-07-03 10:57:28,785] Trial 2710 finished with value: 0.948798682874236 and parameters: {'weight_class_0': 0.0070766375095056245, 'weight_class_1': 0.07605309672507811, 'weight_class_2': 0.04349547424456857}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:28,809] Trial 2709 finished with value: 0.9489057907909254 and parameters: {'weight_class_0': 0.006907735896956495, 'weight_class_1': 0.07893160728444651, 'weight_class_2': 0.043571897345268146}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  90%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 2714/3000 [01:05<00:09, 31.16it/s]

[I 2026-07-03 10:57:28,825] Trial 2711 finished with value: 0.9489728209857136 and parameters: {'weight_class_0': 0.006812338834310229, 'weight_class_1': 0.0771057295865759, 'weight_class_2': 0.044257394512831366}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:28,862] Trial 2712 finished with value: 0.9489781031254546 and parameters: {'weight_class_0': 0.0071034018068684, 'weight_class_1': 0.07570587586470201, 'weight_class_2': 0.04710780334264289}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:28,942] Trial 2713 finished with value: 0.9494545579932551 and parameters: {'weight_class_0': 0.0072309617687530145, 'weight_class_1': 0.073566374204729, 'weight_class_2': 0.057450484113818985}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:28,961] Trial 2714 finished with value: 0.8559324008937731 and parameters: {'weight_class_0': 0.0067872887297255, 'weight_class_1': 0.07180510768827618, 'weight_class_2': 2.2656464584729594}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋            | 2716/3000 [01:05<00:09, 31.16it/s]

[I 2026-07-03 10:57:29,018] Trial 2715 finished with value: 0.9494624681059062 and parameters: {'weight_class_0': 0.007186836066062309, 'weight_class_1': 0.07320377832781097, 'weight_class_2': 0.05728067584382857}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:29,020] Trial 2716 finished with value: 0.9486319693856982 and parameters: {'weight_class_0': 0.00688972198653893, 'weight_class_1': 0.0703877740456149, 'weight_class_2': 0.13009260516097723}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:29,028] Trial 2717 finished with value: 0.9022342952931455 and parameters: {'weight_class_0': 0.039239438754512294, 'weight_class_1': 0.07204206536274603, 'weight_class_2': 0.04599921723754632}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:29,083] Trial 2718 finished with value: 0.9486393292016881 and parameters: {'weight_class_0': 0.006882395318734617, 'weight_class_1': 0.06809544525990383, 'weight_class_2': 0.12771033679060834}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:29,113] Trial 2719 finished with value: 0.9486745411220269 and parameters: {'weight_class_0': 0.007141385668488754, 'weight_class_1': 0.06709107625314369, 'weight_class_2': 0.04247685695710491}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉            | 2722/3000 [01:05<00:08, 31.15it/s]

[I 2026-07-03 10:57:29,137] Trial 2720 finished with value: 0.8590124914312414 and parameters: {'weight_class_0': 0.0067491644993984716, 'weight_class_1': 0.06834459154731667, 'weight_class_2': 2.1966180236551183}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:29,162] Trial 2723 finished with value: 0.9471101398220229 and parameters: {'weight_class_0': 0.0037408219488881656, 'weight_class_1': 0.03275642468563708, 'weight_class_2': 0.12531012962098567}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:29,179] Trial 2721 finished with value: 0.9482416185524888 and parameters: {'weight_class_0': 0.00977483210450551, 'weight_class_1': 0.06567113141221799, 'weight_class_2': 0.058738236587014166}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:29,196] Trial 2724 finished with value: 0.9469355609921468 and parameters: {'weight_class_0': 0.00358574922250936, 'weight_class_1': 0.03269097650841097, 'weight_class_2': 0.13019353826682167}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏           | 2726/3000 [01:05<00:08, 31.54it/s]

[I 2026-07-03 10:57:29,206] Trial 2722 finished with value: 0.949026081230902 and parameters: {'weight_class_0': 0.003629822477017675, 'weight_class_1': 0.0331110648017651, 'weight_class_2': 0.055860330213095125}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:29,296] Trial 2726 finished with value: 0.9494901675599494 and parameters: {'weight_class_0': 0.010563089769948247, 'weight_class_1': 0.11525512028952005, 'weight_class_2': 0.13705198746361305}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:29,297] Trial 2725 finished with value: 0.9495067839589076 and parameters: {'weight_class_0': 0.010079231684780787, 'weight_class_1': 0.11085229357616964, 'weight_class_2': 0.12922112036493955}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏           | 2728/3000 [01:05<00:08, 31.54it/s]

[I 2026-07-03 10:57:29,371] Trial 2729 finished with value: 0.9437049642569969 and parameters: {'weight_class_0': 0.010121030564582141, 'weight_class_1': 0.03238138166895702, 'weight_class_2': 0.05736661193345555}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:29,386] Trial 2727 finished with value: 0.9254467322341835 and parameters: {'weight_class_0': 0.003502045209635278, 'weight_class_1': 0.4634474299635921, 'weight_class_2': 0.06259126282220925}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎           | 2729/3000 [01:05<00:08, 31.54it/s]

[I 2026-07-03 10:57:29,417] Trial 2728 finished with value: 0.9489047309567957 and parameters: {'weight_class_0': 0.003841033603362446, 'weight_class_1': 0.03235566898397315, 'weight_class_2': 0.05959505845125988}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎           | 2730/3000 [01:05<00:09, 29.10it/s]

[I 2026-07-03 10:57:29,470] Trial 2730 finished with value: 0.9445377836964953 and parameters: {'weight_class_0': 0.01003741201972504, 'weight_class_1': 0.03393732822202514, 'weight_class_2': 0.062012093867966835}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍           | 2733/3000 [01:05<00:09, 28.92it/s]

[I 2026-07-03 10:57:29,485] Trial 2731 finished with value: 0.948895694490825 and parameters: {'weight_class_0': 0.0036000933572515365, 'weight_class_1': 0.10905298415204866, 'weight_class_2': 0.05833464692895702}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:29,570] Trial 2732 finished with value: 0.9477449536437709 and parameters: {'weight_class_0': 0.002626559868056445, 'weight_class_1': 0.10441559315511552, 'weight_class_2': 0.05884053183284702}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍           | 2734/3000 [01:05<00:09, 28.92it/s]

[I 2026-07-03 10:57:29,641] Trial 2735 finished with value: 0.9487214167056824 and parameters: {'weight_class_0': 0.010198705190718894, 'weight_class_1': 0.09498724531253817, 'weight_class_2': 0.06167792242259808}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:29,644] Trial 2733 finished with value: 0.9494975799250218 and parameters: {'weight_class_0': 0.011097765266390952, 'weight_class_1': 0.10280469144106144, 'weight_class_2': 0.10162482718163694}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌           | 2736/3000 [01:05<00:09, 28.71it/s]

[I 2026-07-03 10:57:29,658] Trial 2734 finished with value: 0.9496056084432188 and parameters: {'weight_class_0': 0.009771479122199785, 'weight_class_1': 0.11263120688971089, 'weight_class_2': 0.10034964780339169}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:29,674] Trial 2736 finished with value: 0.6781505928385636 and parameters: {'weight_class_0': 0.0046385092881119205, 'weight_class_1': 7.75282856953724, 'weight_class_2': 0.09988207093936545}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋           | 2739/3000 [01:05<00:09, 28.71it/s]

[I 2026-07-03 10:57:29,707] Trial 2737 finished with value: 0.9176763024924554 and parameters: {'weight_class_0': 0.0026474903606271524, 'weight_class_1': 0.09407012324060048, 'weight_class_2': 0.4959917156934567}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:29,745] Trial 2738 finished with value: 0.9488611504414672 and parameters: {'weight_class_0': 0.0047142234021108195, 'weight_class_1': 0.09402993462592657, 'weight_class_2': 0.02990130459761821}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:29,784] Trial 2739 finished with value: 0.9467932630215988 and parameters: {'weight_class_0': 0.0025020967459957423, 'weight_class_1': 0.0994328017798301, 'weight_class_2': 0.1002281595111495}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊           | 2741/3000 [01:06<00:08, 28.80it/s]

[I 2026-07-03 10:57:29,847] Trial 2740 finished with value: 0.9467615520623601 and parameters: {'weight_class_0': 0.0025328958433468666, 'weight_class_1': 0.09769735347536837, 'weight_class_2': 0.10582455478902243}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:29,882] Trial 2742 finished with value: 0.9486685077695141 and parameters: {'weight_class_0': 0.004593887484051046, 'weight_class_1': 0.09559385014674193, 'weight_class_2': 0.10014934066452338}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊           | 2743/3000 [01:06<00:08, 28.87it/s]

[I 2026-07-03 10:57:29,913] Trial 2741 finished with value: 0.9486919439139364 and parameters: {'weight_class_0': 0.0046177881804681156, 'weight_class_1': 0.09658212752109809, 'weight_class_2': 0.10027899240756068}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:29,920] Trial 2743 finished with value: 0.9496799321701955 and parameters: {'weight_class_0': 0.004654002256129453, 'weight_class_1': 0.05785761030939804, 'weight_class_2': 0.040338023626212534}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:29,966] Trial 2744 finished with value: 0.9488528622779863 and parameters: {'weight_class_0': 0.004722143365068337, 'weight_class_1': 0.060047259733385955, 'weight_class_2': 0.028284820705788694}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:30,015] Trial 2746 finished with value: 0.9496249669960579 and parameters: {'weight_class_0': 0.004763935292566111, 'weight_class_1': 0.05853646912808784, 'weight_class_2': 0.03922710273482943}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████           | 2747/3000 [01:06<00:08, 28.71it/s]

[I 2026-07-03 10:57:30,033] Trial 2745 finished with value: 0.9496383682198655 and parameters: {'weight_class_0': 0.004667907491354198, 'weight_class_1': 0.05924094835192783, 'weight_class_2': 0.04142522922021182}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:30,085] Trial 2748 finished with value: 0.8937865656166091 and parameters: {'weight_class_0': 0.0045885962006446636, 'weight_class_1': 0.058921238528152155, 'weight_class_2': 0.0012357648848457163}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:30,160] Trial 2747 finished with value: 0.9489322637146912 and parameters: {'weight_class_0': 0.0047029045205329795, 'weight_class_1': 0.0575574888341514, 'weight_class_2': 0.029253346603285105}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:30,161] Trial 2750 finished with value: 0.9496100130085487 and parameters: {'weight_class_0': 0.0048774237444469655, 'weight_class_1': 0.05620655978379581, 'weight_class_2': 0.04019098943711725}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:30,166] Trial 2749 finished with value: 0.9496736220147324 and parameters: {'weight_class_0': 0.00449490254533017, 'weight_class_1': 0.05714217541813403, 'weight_class_2': 0.038706306223293636}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:30,233] Trial 2752 finished with value: 0.9496646745776802 and parameters: {'weight_class_0': 0.004751241116583694, 'weight_class_1': 0.057758868675525675, 'weight_class_2': 0.04019469930166922}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:30,235] Trial 2751 finished with value: 0.9496828985437012 and parameters: {'weight_class_0': 0.0046543108510947225, 'weight_class_1': 0.058586943600321094, 'weight_class_2': 0.039976043679381845}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:30,274] Trial 2753 finished with value: 0.9495834404908888 and parameters: {'weight_class_0': 0.0034649731652561353, 'weight_class_1': 0.05917996299417101, 'weight_class_2': 0.029081758000327078}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:30,346] Trial 2755 finished with value: 0.9496096575663229 and parameters: {'weight_class_0': 0.0035238081161609444, 'weight_class_1': 0.05825038562516783, 'weight_class_2': 0.039969171436087234}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:30,361] Trial 2754 finished with value: 0.9495101746308138 and parameters: {'weight_class_0': 0.0032711793823572864, 'weight_class_1': 0.05549399020683949, 'weight_class_2': 0.04474688578940617}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌          | 2758/3000 [01:06<00:08, 29.22it/s]

[I 2026-07-03 10:57:30,409] Trial 2756 finished with value: 0.9494635781521948 and parameters: {'weight_class_0': 0.0035413123720265103, 'weight_class_1': 0.047186907754333464, 'weight_class_2': 0.050413408104631935}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:30,414] Trial 2757 finished with value: 0.9493453667286165 and parameters: {'weight_class_0': 0.003279173693858518, 'weight_class_1': 0.04741155743949509, 'weight_class_2': 0.05040449362359863}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:30,462] Trial 2758 finished with value: 0.7082424081823427 and parameters: {'weight_class_0': 0.003429121941016602, 'weight_class_1': 0.04809000574860011, 'weight_class_2': 3.3475529753356836}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌          | 2760/3000 [01:06<00:08, 28.32it/s]

[I 2026-07-03 10:57:30,495] Trial 2759 finished with value: 0.9495068147401092 and parameters: {'weight_class_0': 0.0034103424467238175, 'weight_class_1': 0.043611756651749496, 'weight_class_2': 0.048907561229280194}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:30,522] Trial 2760 finished with value: 0.9493153015296375 and parameters: {'weight_class_0': 0.0034091694910297985, 'weight_class_1': 0.04428178683614483, 'weight_class_2': 0.05432258661351728}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:30,610] Trial 2761 finished with value: 0.9494725107396582 and parameters: {'weight_class_0': 0.003243084158444645, 'weight_class_1': 0.04417751808343407, 'weight_class_2': 0.047679659660405826}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:30,611] Trial 2762 finished with value: 0.9494675835489056 and parameters: {'weight_class_0': 0.003292027160797817, 'weight_class_1': 0.04570775939880035, 'weight_class_2': 0.047207060328328346}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:30,623] Trial 2763 finished with value: 0.9493989988916117 and parameters: {'weight_class_0': 0.0033410505710163496, 'weight_class_1': 0.04557011824158944, 'weight_class_2': 0.050977868443283364}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:30,672] Trial 2765 finished with value: 0.9492134035785623 and parameters: {'weight_class_0': 0.0032365718263394874, 'weight_class_1': 0.044173796879856904, 'weight_class_2': 0.054537521464614006}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:30,679] Trial 2764 finished with value: 0.9493381413687333 and parameters: {'weight_class_0': 0.0032248676791131687, 'weight_class_1': 0.047000462884379354, 'weight_class_2': 0.05100499989434672}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:30,730] Trial 2766 finished with value: 0.9471654375542385 and parameters: {'weight_class_0': 0.007953777013249806, 'weight_class_1': 0.03784716027737393, 'weight_class_2': 0.049462865414591946}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:30,786] Trial 2767 finished with value: 0.9490480235650138 and parameters: {'weight_class_0': 0.006026928653380635, 'weight_class_1': 0.040861516344487356, 'weight_class_2': 0.05058298614256875}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:30,808] Trial 2768 finished with value: 0.8185609007627317 and parameters: {'weight_class_0': 0.4369161517496148, 'weight_class_1': 0.04121187177266255, 'weight_class_2': 0.06741629901744478}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:30,835] Trial 2770 finished with value: 0.9486877067552199 and parameters: {'weight_class_0': 0.006004056503085998, 'weight_class_1': 0.040568398170059194, 'weight_class_2': 0.08334179358889243}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:30,836] Trial 2769 finished with value: 0.9487037173422933 and parameters: {'weight_class_0': 0.005974523285606636, 'weight_class_1': 0.037181322039782895, 'weight_class_2': 0.06814201188473695}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏         | 2773/3000 [01:07<00:07, 29.09it/s]

[I 2026-07-03 10:57:30,915] Trial 2771 finished with value: 0.9472220625394586 and parameters: {'weight_class_0': 0.008279956042014466, 'weight_class_1': 0.03571941327331424, 'weight_class_2': 0.06877039976298834}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:30,956] Trial 2772 finished with value: 0.9477490812047543 and parameters: {'weight_class_0': 0.008254699293718108, 'weight_class_1': 0.03861942188796214, 'weight_class_2': 0.06733984933185386}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:30,982] Trial 2773 finished with value: 0.948394123219447 and parameters: {'weight_class_0': 0.005909276294259406, 'weight_class_1': 0.03699682250491787, 'weight_class_2': 0.08522479536217317}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎         | 2775/3000 [01:07<00:07, 29.09it/s]

[I 2026-07-03 10:57:31,050] Trial 2774 finished with value: 0.9487838659575681 and parameters: {'weight_class_0': 0.006056485958990621, 'weight_class_1': 0.03868600326375139, 'weight_class_2': 0.06690752692266688}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:31,057] Trial 2775 finished with value: 0.911645877377421 and parameters: {'weight_class_0': 0.006010696644295749, 'weight_class_1': 0.9926226613608712, 'weight_class_2': 0.06973890378208657}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  93%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎         | 2777/3000 [01:07<00:07, 29.80it/s]

[I 2026-07-03 10:57:31,059] Trial 2776 finished with value: 0.9483383771941997 and parameters: {'weight_class_0': 0.006087646860154775, 'weight_class_1': 0.03773355593134461, 'weight_class_2': 0.0878506441319225}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:31,124] Trial 2777 finished with value: 0.9495881991654151 and parameters: {'weight_class_0': 0.006037106786342775, 'weight_class_1': 0.0669180933404405, 'weight_class_2': 0.0649731368632109}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  93%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍         | 2780/3000 [01:07<00:07, 29.46it/s]

[I 2026-07-03 10:57:31,135] Trial 2778 finished with value: 0.9496369176586038 and parameters: {'weight_class_0': 0.005997055691775129, 'weight_class_1': 0.06684818662192821, 'weight_class_2': 0.06634338807719732}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:31,183] Trial 2779 finished with value: 0.949678801692848 and parameters: {'weight_class_0': 0.006012664919950334, 'weight_class_1': 0.0807800986819572, 'weight_class_2': 0.0688208996993051}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:31,211] Trial 2780 finished with value: 0.9494215865879075 and parameters: {'weight_class_0': 0.008501187365299468, 'weight_class_1': 0.07256881850241528, 'weight_class_2': 0.08405770284577796}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  93%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌         | 2781/3000 [01:07<00:07, 29.46it/s]

[I 2026-07-03 10:57:31,285] Trial 2782 finished with value: 0.8073491687197564 and parameters: {'weight_class_0': 0.012861915149224743, 'weight_class_1': 5.127926481565377, 'weight_class_2': 0.09138993594660498}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  93%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌         | 2783/3000 [01:07<00:07, 27.20it/s]

[I 2026-07-03 10:57:31,295] Trial 2781 finished with value: 0.9487236096125456 and parameters: {'weight_class_0': 0.003976891788398925, 'weight_class_1': 0.07017799723966717, 'weight_class_2': 0.08535822968717312}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:31,297] Trial 2783 finished with value: 0.9477389576229864 and parameters: {'weight_class_0': 0.0025399436938372123, 'weight_class_1': 0.06932404020227302, 'weight_class_2': 0.0838159096955962}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  93%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊         | 2787/3000 [01:07<00:07, 28.98it/s]

[I 2026-07-03 10:57:31,360] Trial 2785 finished with value: 0.9487923321568658 and parameters: {'weight_class_0': 0.004072944494656171, 'weight_class_1': 0.08332849487062474, 'weight_class_2': 0.08458406689330705}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:31,377] Trial 2784 finished with value: 0.948320220798727 and parameters: {'weight_class_0': 0.002627859115818187, 'weight_class_1': 0.06795679286041008, 'weight_class_2': 0.06551282636212419}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:31,436] Trial 2786 finished with value: 0.9491882896350461 and parameters: {'weight_class_0': 0.003997004638693735, 'weight_class_1': 0.08671390966581526, 'weight_class_2': 0.029495252175235537}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:31,440] Trial 2787 finished with value: 0.949637675684941 and parameters: {'weight_class_0': 0.0040413176239850095, 'weight_class_1': 0.06975231179253304, 'weight_class_2': 0.03524966356290431}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:31,496] Trial 2789 finished with value: 0.9494689322494287 and parameters: {'weight_class_0': 0.003993988198276839, 'weight_class_1': 0.08796325840656292, 'weight_class_2': 0.035706232359863546}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  93%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉         | 2791/3000 [01:07<00:06, 29.93it/s]

[I 2026-07-03 10:57:31,525] Trial 2790 finished with value: 0.9495268546939863 and parameters: {'weight_class_0': 0.00406214007549993, 'weight_class_1': 0.08899397479786478, 'weight_class_2': 0.03557991736713243}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:31,531] Trial 2788 finished with value: 0.9490632553772516 and parameters: {'weight_class_0': 0.002607008109139321, 'weight_class_1': 0.08307245906193741, 'weight_class_2': 0.034817647394427914}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:31,573] Trial 2791 finished with value: 0.9490343563276401 and parameters: {'weight_class_0': 0.0025839831814576534, 'weight_class_1': 0.08576242538491688, 'weight_class_2': 0.02929209642320098}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████         | 2793/3000 [01:07<00:06, 29.93it/s]

[I 2026-07-03 10:57:31,593] Trial 2792 finished with value: 0.9488619901648486 and parameters: {'weight_class_0': 0.0025550290150876277, 'weight_class_1': 0.08637110174892391, 'weight_class_2': 0.03586414648496137}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:31,698] Trial 2793 finished with value: 0.949062665106073 and parameters: {'weight_class_0': 0.003993143022029493, 'weight_class_1': 0.12398091873138571, 'weight_class_2': 0.035130459412062914}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:31,732] Trial 2794 finished with value: 0.9489725265098565 and parameters: {'weight_class_0': 0.0026220724602723385, 'weight_class_1': 0.0883813024693966, 'weight_class_2': 0.035511094855806065}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏        | 2797/3000 [01:07<00:07, 28.11it/s]

[I 2026-07-03 10:57:31,753] Trial 2795 finished with value: 0.949091322531982 and parameters: {'weight_class_0': 0.004092489845453854, 'weight_class_1': 0.12609358376485008, 'weight_class_2': 0.037866297999859064}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:31,792] Trial 2796 finished with value: 0.9491677618484742 and parameters: {'weight_class_0': 0.00400758150387941, 'weight_class_1': 0.11806098286847408, 'weight_class_2': 0.03518326217083772}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:31,799] Trial 2797 finished with value: 0.9480639840682517 and parameters: {'weight_class_0': 0.007480028319053952, 'weight_class_1': 0.08675328804392138, 'weight_class_2': 0.03629757431590856}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:31,871] Trial 2798 finished with value: 0.9493654641431402 and parameters: {'weight_class_0': 0.005213996321883213, 'weight_class_1': 0.12643793234452275, 'weight_class_2': 0.045997162364984925}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:31,885] Trial 2799 finished with value: 0.9494920144346651 and parameters: {'weight_class_0': 0.005314397489055053, 'weight_class_1': 0.05112892686422578, 'weight_class_2': 0.043880316439696095}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍        | 2801/3000 [01:08<00:06, 29.56it/s]

[I 2026-07-03 10:57:31,892] Trial 2800 finished with value: 0.9486986044606263 and parameters: {'weight_class_0': 0.0074106768116672505, 'weight_class_1': 0.11421197263592978, 'weight_class_2': 0.04283124674020925}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:31,934] Trial 2801 finished with value: 0.9494445170559112 and parameters: {'weight_class_0': 0.005244255829473307, 'weight_class_1': 0.12189215071114624, 'weight_class_2': 0.04539825526087091}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:31,985] Trial 2802 finished with value: 0.9487959219432821 and parameters: {'weight_class_0': 0.007412902965901469, 'weight_class_1': 0.11905191399473933, 'weight_class_2': 0.0434486404678991}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:31,994] Trial 2803 finished with value: 0.9480746781422225 and parameters: {'weight_class_0': 0.007800281488467276, 'weight_class_1': 0.05240312600476435, 'weight_class_2': 0.04334579801558041}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:32,018] Trial 2804 finished with value: 0.9488412243442778 and parameters: {'weight_class_0': 0.007227803209697489, 'weight_class_1': 0.12252034412115967, 'weight_class_2': 0.04414415002248921}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:32,129] Trial 2807 finished with value: 0.9494639009705933 and parameters: {'weight_class_0': 0.00535605699265465, 'weight_class_1': 0.050101565176037866, 'weight_class_2': 0.05626759626823954}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:32,130] Trial 2805 finished with value: 0.9483208057157735 and parameters: {'weight_class_0': 0.0075990059444095695, 'weight_class_1': 0.05069445454572414, 'weight_class_2': 0.04644888363013767}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:32,149] Trial 2806 finished with value: 0.948728481940562 and parameters: {'weight_class_0': 0.0077241798168677205, 'weight_class_1': 0.05263294504819353, 'weight_class_2': 0.0561439748336857}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  94%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊        | 2810/3000 [01:08<00:06, 29.24it/s]

[I 2026-07-03 10:57:32,207] Trial 2808 finished with value: 0.9496424746959669 and parameters: {'weight_class_0': 0.005125746110315716, 'weight_class_1': 0.05846927280389814, 'weight_class_2': 0.054612133327546775}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:32,211] Trial 2809 finished with value: 0.9494602592683615 and parameters: {'weight_class_0': 0.005402107459062951, 'weight_class_1': 0.0529316762249255, 'weight_class_2': 0.04499097585125673}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:32,235] Trial 2810 finished with value: 0.9494614000828201 and parameters: {'weight_class_0': 0.005281607120959696, 'weight_class_1': 0.05189840294834625, 'weight_class_2': 0.055034162275496366}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  94%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉        | 2814/3000 [01:08<00:06, 30.99it/s]

[I 2026-07-03 10:57:32,279] Trial 2811 finished with value: 0.9494914673507641 and parameters: {'weight_class_0': 0.005111862506981212, 'weight_class_1': 0.05297049765328075, 'weight_class_2': 0.05557366626542561}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:32,318] Trial 2812 finished with value: 0.9495425234938973 and parameters: {'weight_class_0': 0.005119649553560911, 'weight_class_1': 0.05333673294670759, 'weight_class_2': 0.058439551038983566}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:32,363] Trial 2814 finished with value: 0.9496916756962382 and parameters: {'weight_class_0': 0.005167785728159035, 'weight_class_1': 0.060564014130635134, 'weight_class_2': 0.05796079629846013}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  94%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████        | 2817/3000 [01:08<00:05, 30.99it/s]

[I 2026-07-03 10:57:32,421] Trial 2813 finished with value: 0.9495967783381264 and parameters: {'weight_class_0': 0.005403860099915088, 'weight_class_1': 0.06257143300234519, 'weight_class_2': 0.0535480898409678}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:32,424] Trial 2815 finished with value: 0.949678301144162 and parameters: {'weight_class_0': 0.005202280643205837, 'weight_class_1': 0.06381205838507083, 'weight_class_2': 0.05661771952714367}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:32,461] Trial 2816 finished with value: 0.949635974322554 and parameters: {'weight_class_0': 0.005119549702630982, 'weight_class_1': 0.06168410217472025, 'weight_class_2': 0.055071561542055975}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:32,502] Trial 2817 finished with value: 0.9496966584432402 and parameters: {'weight_class_0': 0.0051508430359648956, 'weight_class_1': 0.061341070676269524, 'weight_class_2': 0.059289912296401265}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  94%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏       | 2819/3000 [01:08<00:06, 29.20it/s]

[I 2026-07-03 10:57:32,540] Trial 2818 finished with value: 0.9496410630523312 and parameters: {'weight_class_0': 0.005584631466038984, 'weight_class_1': 0.06480132310468621, 'weight_class_2': 0.06049954015778675}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:32,573] Trial 2819 finished with value: 0.948429920800077 and parameters: {'weight_class_0': 0.00921608560974435, 'weight_class_1': 0.06450891006449438, 'weight_class_2': 0.056905643089346175}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  94%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎       | 2824/3000 [01:08<00:06, 29.05it/s]

[I 2026-07-03 10:57:32,627] Trial 2820 finished with value: 0.9487379914302596 and parameters: {'weight_class_0': 0.004313988737598135, 'weight_class_1': 0.0307539461040813, 'weight_class_2': 0.06205925416985493}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:32,649] Trial 2821 finished with value: 0.9486710845402732 and parameters: {'weight_class_0': 0.003857727666094562, 'weight_class_1': 0.03068369860692759, 'weight_class_2': 0.06377746547614949}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:32,686] Trial 2822 finished with value: 0.9492629899842749 and parameters: {'weight_class_0': 0.00406775603653645, 'weight_class_1': 0.06369300808987163, 'weight_class_2': 0.029218731733710236}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:32,728] Trial 2824 finished with value: 0.9347887885026713 and parameters: {'weight_class_0': 0.017558492747065342, 'weight_class_1': 0.03263815947322473, 'weight_class_2': 0.11031366460198545}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:32,731] Trial 2823 finished with value: 0.9483333896770604 and parameters: {'weight_class_0': 0.00295778188343116, 'weight_class_1': 0.03312762178362652, 'weight_class_2': 0.06714766717797195}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:32,771] Trial 2825 finished with value: 0.9480316523311169 and parameters: {'weight_class_0': 0.003965234638427417, 'weight_class_1': 0.03032007021770482, 'weight_class_2': 0.08153534616539229}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:32,798] Trial 2826 finished with value: 0.9477319484104704 and parameters: {'weight_class_0': 0.0029588016264553195, 'weight_class_1': 0.032826495478413764, 'weight_class_2': 0.08378376796984645}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  94%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋       | 2830/3000 [01:09<00:05, 30.31it/s]

[I 2026-07-03 10:57:32,829] Trial 2827 finished with value: 0.9489921282799488 and parameters: {'weight_class_0': 0.004109561085485773, 'weight_class_1': 0.033167565688885646, 'weight_class_2': 0.0289806854219886}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:32,875] Trial 2828 finished with value: 0.9473733675294523 and parameters: {'weight_class_0': 0.002983790107479741, 'weight_class_1': 0.07254375489597335, 'weight_class_2': 0.11607165788106262}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:32,942] Trial 2830 finished with value: 0.9481596469823265 and parameters: {'weight_class_0': 0.003824191183452185, 'weight_class_1': 0.03342823959143846, 'weight_class_2': 0.0812272155213013}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:32,946] Trial 2829 finished with value: 0.9473578866612367 and parameters: {'weight_class_0': 0.003871661289884466, 'weight_class_1': 0.03250745882470283, 'weight_class_2': 0.11469359591833204}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  94%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋       | 2831/3000 [01:09<00:05, 30.31it/s]

[I 2026-07-03 10:57:32,986] Trial 2831 finished with value: 0.9302434081784215 and parameters: {'weight_class_0': 0.0038237937395349713, 'weight_class_1': 0.03417277232743611, 'weight_class_2': 0.006632824672236593}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:33,071] Trial 2834 finished with value: 0.9415406536466356 and parameters: {'weight_class_0': 0.012805264469445028, 'weight_class_1': 0.033900090400571424, 'weight_class_2': 0.08514360371318808}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:33,080] Trial 2832 finished with value: 0.9477877371771002 and parameters: {'weight_class_0': 0.013293625703596868, 'weight_class_1': 0.07352795913054841, 'weight_class_2': 0.0827755041965116}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:33,086] Trial 2833 finished with value: 0.9474982249261413 and parameters: {'weight_class_0': 0.003028213004157111, 'weight_class_1': 0.07282304328426639, 'weight_class_2': 0.11263727319133665}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:33,089] Trial 2835 finished with value: 0.9495196752225534 and parameters: {'weight_class_0': 0.006646678381128304, 'weight_class_1': 0.07458818877724568, 'weight_class_2': 0.0863977090167607}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:33,162] Trial 2837 finished with value: 0.9367325967602697 and parameters: {'weight_class_0': 0.012782281588912052, 'weight_class_1': 0.07433107237475164, 'weight_class_2': 0.02875022268083231}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:33,191] Trial 2836 finished with value: 0.9473319346000512 and parameters: {'weight_class_0': 0.006600257541158435, 'weight_class_1': 0.07705587102670593, 'weight_class_2': 0.028418761270545673}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:33,199] Trial 2838 finished with value: 0.9496263021663959 and parameters: {'weight_class_0': 0.006394099457388427, 'weight_class_1': 0.07182120009305457, 'weight_class_2': 0.07430690871096722}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏      | 2843/3000 [01:09<00:05, 29.91it/s]

[I 2026-07-03 10:57:33,230] Trial 2839 finished with value: 0.949467628865988 and parameters: {'weight_class_0': 0.008849092828373767, 'weight_class_1': 0.07842929689710115, 'weight_class_2': 0.07888704016280591}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:33,272] Trial 2840 finished with value: 0.9479766857168945 and parameters: {'weight_class_0': 0.012759719824702727, 'weight_class_1': 0.07538591579331773, 'weight_class_2': 0.07856870633870705}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:33,341] Trial 2841 finished with value: 0.947798909527132 and parameters: {'weight_class_0': 0.013222864540027012, 'weight_class_1': 0.0778678678386032, 'weight_class_2': 0.07671524208087105}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:33,341] Trial 2842 finished with value: 0.9497119943598588 and parameters: {'weight_class_0': 0.0065795942963300215, 'weight_class_1': 0.08011366299026855, 'weight_class_2': 0.07552760697514463}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:33,366] Trial 2843 finished with value: 0.9479857065872315 and parameters: {'weight_class_0': 0.012214791793667912, 'weight_class_1': 0.07465466147558192, 'weight_class_2': 0.0721485543401914}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎      | 2845/3000 [01:09<00:05, 30.55it/s]

[I 2026-07-03 10:57:33,430] Trial 2844 finished with value: 0.9482409088711464 and parameters: {'weight_class_0': 0.008760559705480777, 'weight_class_1': 0.04627148986071229, 'weight_class_2': 0.06996724024535479}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:33,466] Trial 2845 finished with value: 0.9490021442781429 and parameters: {'weight_class_0': 0.006633386011945475, 'weight_class_1': 0.04609920348534179, 'weight_class_2': 0.07170973262721779}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍      | 2849/3000 [01:09<00:05, 27.98it/s]

[I 2026-07-03 10:57:33,490] Trial 2846 finished with value: 0.9489366949786864 and parameters: {'weight_class_0': 0.006812673162732846, 'weight_class_1': 0.04562140240012351, 'weight_class_2': 0.0700237471245157}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:33,519] Trial 2847 finished with value: 0.9495887931266984 and parameters: {'weight_class_0': 0.006322434973948504, 'weight_class_1': 0.09413546775304302, 'weight_class_2': 0.0678232420449304}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:33,608] Trial 2848 finished with value: 0.9116216481154007 and parameters: {'weight_class_0': 0.009306711085580203, 'weight_class_1': 0.007926672833444672, 'weight_class_2': 0.046196175694152436}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:33,614] Trial 2849 finished with value: 0.7235168847248521 and parameters: {'weight_class_0': 0.006545365994550883, 'weight_class_1': 0.04590622207168103, 'weight_class_2': 4.926248112006224}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:33,626] Trial 2850 finished with value: 0.9466744114142381 and parameters: {'weight_class_0': 0.009065328424449237, 'weight_class_1': 0.04621279623158014, 'weight_class_2': 0.04480198612351334}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:33,676] Trial 2851 finished with value: 0.9209222658728304 and parameters: {'weight_class_0': 0.006810304805797654, 'weight_class_1': 0.007748228259622636, 'weight_class_2': 0.04682346159100932}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊      | 2856/3000 [01:10<00:04, 29.10it/s]

[I 2026-07-03 10:57:33,714] Trial 2852 finished with value: 0.9460221576764368 and parameters: {'weight_class_0': 0.00987383648460861, 'weight_class_1': 0.04623202523579419, 'weight_class_2': 0.04644159234212878}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:33,724] Trial 2853 finished with value: 0.9123157606471547 and parameters: {'weight_class_0': 0.009502059826657822, 'weight_class_1': 0.008282907303343155, 'weight_class_2': 0.047074901260254515}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:33,752] Trial 2854 finished with value: 0.9473483757473478 and parameters: {'weight_class_0': 0.008935673455754906, 'weight_class_1': 0.04824173302887009, 'weight_class_2': 0.048746794682558756}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:33,810] Trial 2855 finished with value: 0.9467072816817509 and parameters: {'weight_class_0': 0.009358943323683876, 'weight_class_1': 0.04635938086011554, 'weight_class_2': 0.04777170532593919}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:33,848] Trial 2857 finished with value: 0.9485241670258945 and parameters: {'weight_class_0': 0.008726285810756022, 'weight_class_1': 0.10229783055908336, 'weight_class_2': 0.047115565369132625}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊      | 2858/3000 [01:10<00:04, 28.99it/s]

[I 2026-07-03 10:57:33,866] Trial 2856 finished with value: 0.9483301041048448 and parameters: {'weight_class_0': 0.00924725367859738, 'weight_class_1': 0.09480910556953898, 'weight_class_2': 0.048249762653327935}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:33,896] Trial 2858 finished with value: 0.9484666822722887 and parameters: {'weight_class_0': 0.008761377359341228, 'weight_class_1': 0.09728524931031711, 'weight_class_2': 0.04694000168301069}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  95%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████      | 2862/3000 [01:10<00:04, 28.66it/s]

[I 2026-07-03 10:57:33,935] Trial 2859 finished with value: 0.9467746871132295 and parameters: {'weight_class_0': 0.009096230343808971, 'weight_class_1': 0.04531109891576521, 'weight_class_2': 0.04660205409187328}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:33,992] Trial 2860 finished with value: 0.9484916693102586 and parameters: {'weight_class_0': 0.002894536901987304, 'weight_class_1': 0.10060294681275897, 'weight_class_2': 0.05090658354256141}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:34,044] Trial 2861 finished with value: 0.9495402926795515 and parameters: {'weight_class_0': 0.004683895864467764, 'weight_class_1': 0.09594055175331666, 'weight_class_2': 0.048711790876835186}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:34,072] Trial 2863 finished with value: 0.9490029952827492 and parameters: {'weight_class_0': 0.002974014430898231, 'weight_class_1': 0.09687356606126477, 'weight_class_2': 0.039283979922111044}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  95%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████      | 2864/3000 [01:10<00:04, 28.11it/s]

[I 2026-07-03 10:57:34,111] Trial 2862 finished with value: 0.9494050042746668 and parameters: {'weight_class_0': 0.00447406261427083, 'weight_class_1': 0.10463604183036507, 'weight_class_2': 0.040441663508239176}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:34,131] Trial 2864 finished with value: 0.9495794522516371 and parameters: {'weight_class_0': 0.004569700713612048, 'weight_class_1': 0.09289182516283118, 'weight_class_2': 0.0391825023494667}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:34,187] Trial 2865 finished with value: 0.9491071672446871 and parameters: {'weight_class_0': 0.0030917296077329604, 'weight_class_1': 0.09791555933155902, 'weight_class_2': 0.03659112392859808}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:34,191] Trial 2866 finished with value: 0.9487015119965689 and parameters: {'weight_class_0': 0.002925278885005703, 'weight_class_1': 0.10649660188896036, 'weight_class_2': 0.0409627787448154}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:34,193] Trial 2867 finished with value: 0.9493826462641026 and parameters: {'weight_class_0': 0.00444649850450882, 'weight_class_1': 0.1068141516419761, 'weight_class_2': 0.04048129423808178}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:34,287] Trial 2868 finished with value: 0.9246067829139659 and parameters: {'weight_class_0': 0.004525349367520423, 'weight_class_1': 0.00570873867102947, 'weight_class_2': 0.03810703922945174}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍     | 2871/3000 [01:10<00:04, 28.27it/s]

[I 2026-07-03 10:57:34,299] Trial 2869 finished with value: 0.949662003417958 and parameters: {'weight_class_0': 0.00445909851520867, 'weight_class_1': 0.05685575176866368, 'weight_class_2': 0.03799175238335075}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:34,351] Trial 2870 finished with value: 0.949670548165241 and parameters: {'weight_class_0': 0.0043761207604280745, 'weight_class_1': 0.05834382301100364, 'weight_class_2': 0.03730350423802733}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:34,355] Trial 2871 finished with value: 0.9208171365873187 and parameters: {'weight_class_0': 0.004534096026644432, 'weight_class_1': 0.6382883657100955, 'weight_class_2': 0.035033208506140924}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:34,362] Trial 2872 finished with value: 0.9496420659020992 and parameters: {'weight_class_0': 0.004549414869753755, 'weight_class_1': 0.05776567697316143, 'weight_class_2': 0.038108912798685765}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:34,439] Trial 2873 finished with value: 0.923191857466779 and parameters: {'weight_class_0': 0.004564214036034312, 'weight_class_1': 0.005658673714952907, 'weight_class_2': 0.09734307187135555}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:34,486] Trial 2875 finished with value: 0.9490960145274135 and parameters: {'weight_class_0': 0.003555436081571609, 'weight_class_1': 0.060868433821851, 'weight_class_2': 0.06237798094525156}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:34,505] Trial 2874 finished with value: 0.9490626463559338 and parameters: {'weight_class_0': 0.0035846386801118, 'weight_class_1': 0.056287804733806936, 'weight_class_2': 0.06395316208052558}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋     | 2878/3000 [01:10<00:04, 30.02it/s]

[I 2026-07-03 10:57:34,528] Trial 2876 finished with value: 0.9495941183345615 and parameters: {'weight_class_0': 0.003627576259924007, 'weight_class_1': 0.05746452624098133, 'weight_class_2': 0.029600933928519212}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:34,559] Trial 2877 finished with value: 0.9490341813530477 and parameters: {'weight_class_0': 0.0035015060922810744, 'weight_class_1': 0.0617860770116625, 'weight_class_2': 0.06270497200963839}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:34,587] Trial 2879 finished with value: 0.9480823986469215 and parameters: {'weight_class_0': 0.003533805795551254, 'weight_class_1': 0.053942819027998946, 'weight_class_2': 0.09887487124551686}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊     | 2881/3000 [01:10<00:03, 30.98it/s]

[I 2026-07-03 10:57:34,589] Trial 2878 finished with value: 0.948979923966896 and parameters: {'weight_class_0': 0.0035007159546593517, 'weight_class_1': 0.05843445936543105, 'weight_class_2': 0.06532429295266327}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:34,674] Trial 2880 finished with value: 0.9482513435800827 and parameters: {'weight_class_0': 0.0035967743225071122, 'weight_class_1': 0.06028202857302345, 'weight_class_2': 0.09453119546356557}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:34,727] Trial 2881 finished with value: 0.9483001170537663 and parameters: {'weight_class_0': 0.003564225850162025, 'weight_class_1': 0.06534066073971322, 'weight_class_2': 0.09374920892464247}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉     | 2884/3000 [01:10<00:04, 28.09it/s]

[I 2026-07-03 10:57:34,763] Trial 2882 finished with value: 0.9489538817694463 and parameters: {'weight_class_0': 0.003594761835875139, 'weight_class_1': 0.03934635049813777, 'weight_class_2': 0.061919845379578314}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:34,789] Trial 2883 finished with value: 0.9490853568353347 and parameters: {'weight_class_0': 0.0035640290810874963, 'weight_class_1': 0.0588925766354951, 'weight_class_2': 0.06264169504136682}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:34,792] Trial 2884 finished with value: 0.9477553619926322 and parameters: {'weight_class_0': 0.003379215868834378, 'weight_class_1': 0.03738613184130163, 'weight_class_2': 0.0952405576298888}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:34,856] Trial 2885 finished with value: 0.9489338694298888 and parameters: {'weight_class_0': 0.0036366049619101313, 'weight_class_1': 0.03728058455794006, 'weight_class_2': 0.06177387004440013}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:34,865] Trial 2886 finished with value: 0.9452006409717703 and parameters: {'weight_class_0': 0.007255527047244871, 'weight_class_1': 0.036975862069714316, 'weight_class_2': 0.028698092687206092}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:34,877] Trial 2887 finished with value: 0.9494136600422266 and parameters: {'weight_class_0': 0.0073426163377333055, 'weight_class_1': 0.0660207094745643, 'weight_class_2': 0.057591271219503415}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:34,904] Trial 2888 finished with value: 0.9458545612310182 and parameters: {'weight_class_0': 0.0025208822074015286, 'weight_class_1': 0.1464921423906734, 'weight_class_2': 0.05776337355775532}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:34,944] Trial 2889 finished with value: 0.9454136355850563 and parameters: {'weight_class_0': 0.0072077920622251315, 'weight_class_1': 0.037927840988624326, 'weight_class_2': 0.028976365629830674}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:35,001] Trial 2891 finished with value: 0.9331225986429025 and parameters: {'weight_class_0': 0.00247742647481205, 'weight_class_1': 0.03927556927090684, 'weight_class_2': 0.0047203613360041205}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:35,002] Trial 2890 finished with value: 0.9460339797216616 and parameters: {'weight_class_0': 0.0024560905930026107, 'weight_class_1': 0.14005978657171544, 'weight_class_2': 0.05453368443733849}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍    | 2894/3000 [01:11<00:03, 30.76it/s]

[I 2026-07-03 10:57:35,055] Trial 2892 finished with value: 0.9478006663824717 and parameters: {'weight_class_0': 0.0076312093296304825, 'weight_class_1': 0.037556988856613474, 'weight_class_2': 0.057946803736176535}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:35,111] Trial 2893 finished with value: 0.9488211251594744 and parameters: {'weight_class_0': 0.005961888149011921, 'weight_class_1': 0.03742544545729105, 'weight_class_2': 0.05581343937329477}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:35,185] Trial 2895 finished with value: 0.9453614828552747 and parameters: {'weight_class_0': 0.0074438731496074585, 'weight_class_1': 0.039738428702029156, 'weight_class_2': 0.02953593065938124}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  97%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌    | 2898/3000 [01:11<00:03, 27.96it/s]

[I 2026-07-03 10:57:35,186] Trial 2894 finished with value: 0.9496523195965118 and parameters: {'weight_class_0': 0.0025104929275176083, 'weight_class_1': 0.0393428334191772, 'weight_class_2': 0.028120296578389502}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:35,209] Trial 2896 finished with value: 0.9459527839303373 and parameters: {'weight_class_0': 0.0071289627513680676, 'weight_class_1': 0.04369637178296634, 'weight_class_2': 0.029053869211791743}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:35,270] Trial 2898 finished with value: 0.9477923368893619 and parameters: {'weight_class_0': 0.005796224855819566, 'weight_class_1': 0.04076386219976559, 'weight_class_2': 0.029663186250826742}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:35,284] Trial 2897 finished with value: 0.9491601885051087 and parameters: {'weight_class_0': 0.0059234243089325124, 'weight_class_1': 0.04151130862087636, 'weight_class_2': 0.05469520411862621}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  97%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋    | 2901/3000 [01:11<00:03, 30.41it/s]

[I 2026-07-03 10:57:35,296] Trial 2899 finished with value: 0.9494330934964288 and parameters: {'weight_class_0': 0.005720406961245231, 'weight_class_1': 0.04841766194853052, 'weight_class_2': 0.054782343168295215}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:35,335] Trial 2900 finished with value: 0.9493146555327893 and parameters: {'weight_class_0': 0.0057429510206219005, 'weight_class_1': 0.04481426163969877, 'weight_class_2': 0.056441908367430974}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:35,391] Trial 2901 finished with value: 0.8087352406137018 and parameters: {'weight_class_0': 1.2243555315099113, 'weight_class_1': 0.08114953463847767, 'weight_class_2': 0.052527768072401226}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  97%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉    | 2905/3000 [01:11<00:03, 28.61it/s]

[I 2026-07-03 10:57:35,453] Trial 2903 finished with value: 0.9488186672727951 and parameters: {'weight_class_0': 0.005844725234447432, 'weight_class_1': 0.21322671211498018, 'weight_class_2': 0.07227240337338219}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:35,454] Trial 2905 finished with value: 0.9496289234058616 and parameters: {'weight_class_0': 0.005674234675809342, 'weight_class_1': 0.08200011924244766, 'weight_class_2': 0.07264620570142856}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:35,464] Trial 2904 finished with value: 0.9495818774474604 and parameters: {'weight_class_0': 0.005537988682769157, 'weight_class_1': 0.08313806722928997, 'weight_class_2': 0.07173374135227141}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:35,470] Trial 2902 finished with value: 0.9495690526983417 and parameters: {'weight_class_0': 0.00570985889650911, 'weight_class_1': 0.08518618154251213, 'weight_class_2': 0.05275867466079987}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████    | 2908/3000 [01:11<00:03, 30.35it/s]

[I 2026-07-03 10:57:35,542] Trial 2906 finished with value: 0.9484967837040803 and parameters: {'weight_class_0': 0.005598885498465047, 'weight_class_1': 0.22589003985419065, 'weight_class_2': 0.07112424118684277}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:35,616] Trial 2907 finished with value: 0.9477237970109661 and parameters: {'weight_class_0': 0.0056410604612281675, 'weight_class_1': 0.05003075354889019, 'weight_class_2': 0.1461738393422849}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:35,620] Trial 2908 finished with value: 0.9484823421901961 and parameters: {'weight_class_0': 0.005440903141082931, 'weight_class_1': 0.21372323321251926, 'weight_class_2': 0.07918114469050112}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏   | 2911/3000 [01:11<00:03, 28.20it/s]

[I 2026-07-03 10:57:35,648] Trial 2909 finished with value: 0.948122214149028 and parameters: {'weight_class_0': 0.0052446995160008785, 'weight_class_1': 0.08411708015896321, 'weight_class_2': 0.1471306719265191}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:35,713] Trial 2910 finished with value: 0.8355075062491557 and parameters: {'weight_class_0': 0.2708233207759551, 'weight_class_1': 0.08433784895980315, 'weight_class_2': 0.07380320101347562}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:35,739] Trial 2912 finished with value: 0.9494764279278325 and parameters: {'weight_class_0': 0.00528016995627125, 'weight_class_1': 0.08143635966585078, 'weight_class_2': 0.07411869792093652}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:35,740] Trial 2911 finished with value: 0.9494828987048641 and parameters: {'weight_class_0': 0.005526187860266637, 'weight_class_1': 0.07303358666700246, 'weight_class_2': 0.07727639876072684}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:35,764] Trial 2913 finished with value: 0.9495505047860204 and parameters: {'weight_class_0': 0.005179412017245804, 'weight_class_1': 0.06865487433549296, 'weight_class_2': 0.07092271819302222}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:35,829] Trial 2914 finished with value: 0.9485386098929598 and parameters: {'weight_class_0': 0.004840286162819828, 'weight_class_1': 0.06949216078547409, 'weight_class_2': 0.11176864459767671}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:35,850] Trial 2915 finished with value: 0.9485813170476698 and parameters: {'weight_class_0': 0.004929739216299547, 'weight_class_1': 0.06870716958715732, 'weight_class_2': 0.11173505348404934}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍   | 2918/3000 [01:12<00:02, 30.35it/s]

[I 2026-07-03 10:57:35,862] Trial 2917 finished with value: 0.9477454264984821 and parameters: {'weight_class_0': 0.004792861141624863, 'weight_class_1': 0.06609571480341485, 'weight_class_2': 0.14899319409887293}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:35,897] Trial 2916 finished with value: 0.9474242816789503 and parameters: {'weight_class_0': 0.0048875863000455814, 'weight_class_1': 0.05058320427981132, 'weight_class_2': 0.15376958484563966}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:35,954] Trial 2918 finished with value: 0.9490024320645034 and parameters: {'weight_class_0': 0.004835542106144981, 'weight_class_1': 0.07124356342477962, 'weight_class_2': 0.08945224951469856}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:36,030] Trial 2919 finished with value: 0.9479959565939962 and parameters: {'weight_class_0': 0.0029264643501674486, 'weight_class_1': 0.06359260800558013, 'weight_class_2': 0.08878347315501983}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:36,039] Trial 2920 finished with value: 0.8338206428218379 and parameters: {'weight_class_0': 0.2559468373691762, 'weight_class_1': 0.06686958686628987, 'weight_class_2': 0.08909662308201419}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:36,072] Trial 2921 finished with value: 0.9480045239035396 and parameters: {'weight_class_0': 0.0029575552099163397, 'weight_class_1': 0.06755142318156539, 'weight_class_2': 0.08900755710807322}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  98%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊   | 2926/3000 [01:12<00:02, 29.45it/s]

[I 2026-07-03 10:57:36,092] Trial 2922 finished with value: 0.949610993509829 and parameters: {'weight_class_0': 0.004262883075230481, 'weight_class_1': 0.05145824922883957, 'weight_class_2': 0.0424938282549093}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:36,130] Trial 2923 finished with value: 0.9484143358564056 and parameters: {'weight_class_0': 0.004328121001284201, 'weight_class_1': 0.05224432297798792, 'weight_class_2': 0.09918331104123118}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:36,177] Trial 2924 finished with value: 0.7125518102505625 and parameters: {'weight_class_0': 0.00290774103832043, 'weight_class_1': 2.9900963316644136, 'weight_class_2': 0.09076798301075921}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:36,219] Trial 2925 finished with value: 0.9481163631932125 and parameters: {'weight_class_0': 0.004347047333174572, 'weight_class_1': 0.0514582560489322, 'weight_class_2': 0.10989237999761337}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  98%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉   | 2928/3000 [01:12<00:02, 29.45it/s]

[I 2026-07-03 10:57:36,245] Trial 2926 finished with value: 0.9496340206422241 and parameters: {'weight_class_0': 0.004178324216587111, 'weight_class_1': 0.054758660122187726, 'weight_class_2': 0.042708315905354934}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:36,281] Trial 2927 finished with value: 0.9494577290979153 and parameters: {'weight_class_0': 0.002890371227693902, 'weight_class_1': 0.05325344415722939, 'weight_class_2': 0.04066460213610592}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:36,299] Trial 2928 finished with value: 0.9496576108803637 and parameters: {'weight_class_0': 0.004011926750070764, 'weight_class_1': 0.052660739884510734, 'weight_class_2': 0.04346910865872797}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████   | 2931/3000 [01:12<00:02, 29.76it/s]

[I 2026-07-03 10:57:36,343] Trial 2929 finished with value: 0.9492463491475839 and parameters: {'weight_class_0': 0.0026089908155051255, 'weight_class_1': 0.051267055119921356, 'weight_class_2': 0.04304353858329884}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:36,360] Trial 2930 finished with value: 0.9494310296674001 and parameters: {'weight_class_0': 0.002974371765669832, 'weight_class_1': 0.05263024571908755, 'weight_class_2': 0.04244306946566476}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:36,412] Trial 2931 finished with value: 0.949622626956192 and parameters: {'weight_class_0': 0.004109735541450101, 'weight_class_1': 0.05149972651109185, 'weight_class_2': 0.04097457705766748}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:36,456] Trial 2932 finished with value: 0.9496662144169359 and parameters: {'weight_class_0': 0.004068359233069472, 'weight_class_1': 0.053549911844080804, 'weight_class_2': 0.04001844936322993}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:36,490] Trial 2933 finished with value: 0.9473455696349541 and parameters: {'weight_class_0': 0.007300856106130954, 'weight_class_1': 0.05306991032722889, 'weight_class_2': 0.03381189502222451}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:36,549] Trial 2935 finished with value: 0.9496110837511572 and parameters: {'weight_class_0': 0.0029479541753954642, 'weight_class_1': 0.052807844804000165, 'weight_class_2': 0.034203073132513855}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:36,549] Trial 2934 finished with value: 0.9476942688020689 and parameters: {'weight_class_0': 0.007081081533186327, 'weight_class_1': 0.053114797600182284, 'weight_class_2': 0.03489296645804185}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:36,559] Trial 2936 finished with value: 0.7815555137164717 and parameters: {'weight_class_0': 2.4501961840742426, 'weight_class_1': 0.05418424462287659, 'weight_class_2': 0.03316814728251181}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:36,624] Trial 2937 finished with value: 0.9475678083589744 and parameters: {'weight_class_0': 0.007008028455318845, 'weight_class_1': 0.05107024454041536, 'weight_class_2': 0.033731509444355386}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:36,647] Trial 2938 finished with value: 0.9473899070932598 and parameters: {'weight_class_0': 0.007715019425588448, 'weight_class_1': 0.1188749367152286, 'weight_class_2': 0.033896434555227506}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:36,660] Trial 2939 finished with value: 0.9474425789606259 and parameters: {'weight_class_0': 0.0076137222857449, 'weight_class_1': 0.1407962326920972, 'weight_class_2': 0.033979324975780226}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:36,681] Trial 2940 finished with value: 0.9477966691749068 and parameters: {'weight_class_0': 0.0074640790477680215, 'weight_class_1': 0.11656877419560535, 'weight_class_2': 0.03483746889791733}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 2944/3000 [01:13<00:01, 29.16it/s]

[I 2026-07-03 10:57:36,756] Trial 2941 finished with value: 0.9447753069536519 and parameters: {'weight_class_0': 0.007635515440102723, 'weight_class_1': 0.030215372407132082, 'weight_class_2': 0.03479058836962363}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:36,760] Trial 2942 finished with value: 0.9471386258839779 and parameters: {'weight_class_0': 0.007920473063810173, 'weight_class_1': 0.1418018168624347, 'weight_class_2': 0.03392035093080343}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:36,816] Trial 2943 finished with value: 0.9492417632531517 and parameters: {'weight_class_0': 0.0075659660883087764, 'weight_class_1': 0.11570167595419419, 'weight_class_2': 0.05393525556013665}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:36,856] Trial 2944 finished with value: 0.9494018189502295 and parameters: {'weight_class_0': 0.007445668889201512, 'weight_class_1': 0.11398544283896607, 'weight_class_2': 0.05606752953624713}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:36,869] Trial 2945 finished with value: 0.8023985705985034 and parameters: {'weight_class_0': 2.3771122022962294, 'weight_class_1': 0.10915149796829432, 'weight_class_2': 0.051736440105017496}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:36,879] Trial 2946 finished with value: 0.9495001127962358 and parameters: {'weight_class_0': 0.006618460388758729, 'weight_class_1': 0.1288059142167928, 'weight_class_2': 0.052251637581759165}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊  | 2950/3000 [01:13<00:01, 29.28it/s]

[I 2026-07-03 10:57:36,955] Trial 2947 finished with value: 0.9475782580935129 and parameters: {'weight_class_0': 0.0064888151677170896, 'weight_class_1': 0.02967963953896315, 'weight_class_2': 0.05182976862997805}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:36,989] Trial 2949 finished with value: 0.9398864585892251 and parameters: {'weight_class_0': 0.01139860637105965, 'weight_class_1': 0.02947983036025627, 'weight_class_2': 0.05306078589633682}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:37,024] Trial 2948 finished with value: 0.9494782697471623 and parameters: {'weight_class_0': 0.006507298162056565, 'weight_class_1': 0.08414020322992466, 'weight_class_2': 0.05039368719008274}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:37,033] Trial 2950 finished with value: 0.9495740206034687 and parameters: {'weight_class_0': 0.006249463741028277, 'weight_class_1': 0.06787687216046107, 'weight_class_2': 0.05160730453842085}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:37,096] Trial 2951 finished with value: 0.9478203060336391 and parameters: {'weight_class_0': 0.011360183475544709, 'weight_class_1': 0.09349073542965795, 'weight_class_2': 0.05546010240886046}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:37,154] Trial 2954 finished with value: 0.949573860920102 and parameters: {'weight_class_0': 0.006076364748259956, 'weight_class_1': 0.09441166221405443, 'weight_class_2': 0.0653362409207924}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  99%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏ | 2957/3000 [01:13<00:01, 29.87it/s]

[I 2026-07-03 10:57:37,155] Trial 2952 finished with value: 0.9496337027759497 and parameters: {'weight_class_0': 0.006319174263193519, 'weight_class_1': 0.08948682763426337, 'weight_class_2': 0.05194080904536513}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:37,165] Trial 2953 finished with value: 0.8965163418722616 and parameters: {'weight_class_0': 0.006390021818275276, 'weight_class_1': 0.08277704937033102, 'weight_class_2': 0.002681911192399527}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:37,231] Trial 2955 finished with value: 0.9495090291103846 and parameters: {'weight_class_0': 0.006656304531796654, 'weight_class_1': 0.09287900245647049, 'weight_class_2': 0.05213750281069328}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:37,278] Trial 2956 finished with value: 0.9492038738349399 and parameters: {'weight_class_0': 0.003946836572504494, 'weight_class_1': 0.08602232097204174, 'weight_class_2': 0.06507605941019165}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:37,280] Trial 2958 finished with value: 0.9488811897775048 and parameters: {'weight_class_0': 0.003710460983978275, 'weight_class_1': 0.08645122777241673, 'weight_class_2': 0.0673093415247145}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  99%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏ | 2959/3000 [01:13<00:01, 29.87it/s]

[I 2026-07-03 10:57:37,299] Trial 2957 finished with value: 0.9485692151205081 and parameters: {'weight_class_0': 0.010735490086677553, 'weight_class_1': 0.08820033763903479, 'weight_class_2': 0.06389203996069542}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:37,331] Trial 2959 finished with value: 0.9476685714462233 and parameters: {'weight_class_0': 0.0024942990957944732, 'weight_class_1': 0.08863507278495589, 'weight_class_2': 0.07004128474370927}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  99%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍ | 2963/3000 [01:13<00:01, 30.05it/s]

[I 2026-07-03 10:57:37,413] Trial 2960 finished with value: 0.9491530665552229 and parameters: {'weight_class_0': 0.003968826473040274, 'weight_class_1': 0.08921364980989717, 'weight_class_2': 0.06391388166107312}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:37,430] Trial 2961 finished with value: 0.9490782559471896 and parameters: {'weight_class_0': 0.004561647845529932, 'weight_class_1': 0.04280790304670205, 'weight_class_2': 0.06938569042069824}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:37,460] Trial 2962 finished with value: 0.9490074246008557 and parameters: {'weight_class_0': 0.0039050145081044626, 'weight_class_1': 0.042665493020704624, 'weight_class_2': 0.06588618862308696}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:37,479] Trial 2963 finished with value: 0.9491759511438262 and parameters: {'weight_class_0': 0.0038923527377595357, 'weight_class_1': 0.06478380812585169, 'weight_class_2': 0.06615266332753543}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  99%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍ | 2965/3000 [01:13<00:01, 28.86it/s]

[I 2026-07-03 10:57:37,555] Trial 2966 finished with value: 0.9481510398445443 and parameters: {'weight_class_0': 0.0024860459718426013, 'weight_class_1': 0.06463010144378308, 'weight_class_2': 0.0655751196149086}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:37,570] Trial 2964 finished with value: 0.9489007747245917 and parameters: {'weight_class_0': 0.003928533958463889, 'weight_class_1': 0.04304863776094395, 'weight_class_2': 0.0694587190147364}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  99%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋ | 2969/3000 [01:13<00:01, 27.29it/s]

[I 2026-07-03 10:57:37,607] Trial 2965 finished with value: 0.9481061507657872 and parameters: {'weight_class_0': 0.0024245611168048366, 'weight_class_1': 0.04122255644690613, 'weight_class_2': 0.0691970186869813}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:37,634] Trial 2967 finished with value: 0.9489678652018799 and parameters: {'weight_class_0': 0.0039375648331792384, 'weight_class_1': 0.04249240989104421, 'weight_class_2': 0.06648538753285567}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:37,711] Trial 2969 finished with value: 0.9485139759415379 and parameters: {'weight_class_0': 0.004448377865932233, 'weight_class_1': 0.04377819998663616, 'weight_class_2': 0.08803565923274191}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:37,730] Trial 2968 finished with value: 0.9484791294598941 and parameters: {'weight_class_0': 0.004255876975611355, 'weight_class_1': 0.041489394057511134, 'weight_class_2': 0.08399748603959607}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:37,748] Trial 2971 finished with value: 0.9490975222978504 and parameters: {'weight_class_0': 0.004599823361828885, 'weight_class_1': 0.06537042948201764, 'weight_class_2': 0.08173120782324225}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:37,759] Trial 2970 finished with value: 0.9494581888038328 and parameters: {'weight_class_0': 0.00422124810249582, 'weight_class_1': 0.06527227193391245, 'weight_class_2': 0.06291181059088992}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  99%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉ | 2976/3000 [01:14<00:00, 29.73it/s]

[I 2026-07-03 10:57:37,818] Trial 2973 finished with value: 0.7638184475448675 and parameters: {'weight_class_0': 3.776186404442463, 'weight_class_1': 0.06490078493141166, 'weight_class_2': 0.045347258405548076}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:37,831] Trial 2972 finished with value: 0.9483256063049831 and parameters: {'weight_class_0': 0.0031339418138151974, 'weight_class_1': 0.06557247815969693, 'weight_class_2': 0.08302816005571328}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:37,842] Trial 2974 finished with value: 0.6644694971661839 and parameters: {'weight_class_0': 0.004966845009485941, 'weight_class_1': 0.06743508009951023, 'weight_class_2': 8.14864959667852}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:37,888] Trial 2975 finished with value: 0.9475562236542966 and parameters: {'weight_class_0': 0.003192153499980229, 'weight_class_1': 0.0674311408464504, 'weight_class_2': 0.11676135356726532}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:37,930] Trial 2977 finished with value: 0.9474998803034699 and parameters: {'weight_class_0': 0.0031347819551129103, 'weight_class_1': 0.06636296579538607, 'weight_class_2': 0.11885304347196929}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ | 2978/3000 [01:14<00:00, 29.03it/s]

[I 2026-07-03 10:57:37,964] Trial 2976 finished with value: 0.9496649228653422 and parameters: {'weight_class_0': 0.005062438173597991, 'weight_class_1': 0.06755027666069806, 'weight_class_2': 0.043235158562419246}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:37,996] Trial 2978 finished with value: 0.9492746166643475 and parameters: {'weight_class_0': 0.002992209917631926, 'weight_class_1': 0.0661947055447498, 'weight_class_2': 0.04508447533110831}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737:  99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏| 2982/3000 [01:14<00:00, 29.00it/s]

[I 2026-07-03 10:57:38,008] Trial 2979 finished with value: 0.9479280224411758 and parameters: {'weight_class_0': 0.0030335472098988875, 'weight_class_1': 0.07420590064896676, 'weight_class_2': 0.09311755769551437}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:38,107] Trial 2980 finished with value: 0.9493479847476083 and parameters: {'weight_class_0': 0.00309130529799021, 'weight_class_1': 0.07215160392766369, 'weight_class_2': 0.042275564897060684}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:38,122] Trial 2982 finished with value: 0.9493866908206715 and parameters: {'weight_class_0': 0.0031116321324543236, 'weight_class_1': 0.07066888729548776, 'weight_class_2': 0.04225708237498481}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:38,124] Trial 2981 finished with value: 0.9476525439434574 and parameters: {'weight_class_0': 0.0032195589220013953, 'weight_class_1': 0.07101562333476621, 'weight_class_2': 0.11475033721780371}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:38,144] Trial 2983 finished with value: 0.9491826613776512 and parameters: {'weight_class_0': 0.003037443189215794, 'weight_class_1': 0.07302564427767985, 'weight_class_2': 0.04526504633220537}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍| 2988/3000 [01:14<00:00, 27.72it/s]

[I 2026-07-03 10:57:38,278] Trial 2985 finished with value: 0.9492423283283914 and parameters: {'weight_class_0': 0.0030736788663982646, 'weight_class_1': 0.030739998685314122, 'weight_class_2': 0.04417740104798558}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:38,294] Trial 2984 finished with value: 0.9485917152080945 and parameters: {'weight_class_0': 0.005201126244872793, 'weight_class_1': 0.029636492256027953, 'weight_class_2': 0.044036866120058984}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:38,308] Trial 2986 finished with value: 0.9485329058678807 and parameters: {'weight_class_0': 0.005245981421158441, 'weight_class_1': 0.029871356357539222, 'weight_class_2': 0.043610888750325226}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:38,347] Trial 2987 finished with value: 0.9195409875527455 and parameters: {'weight_class_0': 0.00881407434868375, 'weight_class_1': 1.2100953692103085, 'weight_class_2': 0.043182174440223244}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:38,412] Trial 2989 finished with value: 0.944257615066717 and parameters: {'weight_class_0': 0.008666764351908437, 'weight_class_1': 0.030877470735667063, 'weight_class_2': 0.04312140277933156}. Best is trial 1741 with value: 0.9497368888684448.

[I 2026-07-03 10:57:38,413] Trial 2988 finished with value: 0.9490812683906661 and parameters: {'weight_class_0': 0.0050943357518784494, 'weight_class_1': 0.03528847312838627, 'weight_class_2': 0.04273092746901227}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:38,420] Trial 2990 finished with value: 0.9445119350215109 and parameters: {'weight_class_0': 0.008876233296078975, 'weight_class_1': 0.03129890143760954, 'weight_class_2': 0.04726115366755209}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:38,454] Trial 2991 finished with value: 0.9455012945540512 and parameters: {'weight_class_0': 0.00848184302932191, 'weight_class_1': 0.03421803794514479, 'weight_class_2': 0.04381978460299145}. Best is trial 1741 with value: 0.9497368888684448.

Best trial: 1741. Best value: 0.949737: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3000/3000 [01:14<00:00, 40.13it/s]

[I 2026-07-03 10:57:38,478] Trial 2992 finished with value: 0.9474425477203687 and parameters: {'weight_class_0': 0.005374661861463073, 'weight_class_1': 0.030883730608804796, 'weight_class_2': 0.02874785576559878}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:38,539] Trial 2993 finished with value: 0.9491811935175042 and parameters: {'weight_class_0': 0.005135790316315338, 'weight_class_1': 0.03702790037856549, 'weight_class_2': 0.050851852439994065}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:38,547] Trial 2994 finished with value: 0.9459279262591824 and parameters: {'weight_class_0': 0.00856330144922181, 'weight_class_1': 0.034644776677395815, 'weight_class_2': 0.049215454240132975}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:38,583] Trial 2995 finished with value: 0.9450792892675608 and parameters: {'weight_class_0': 0.008324993045272847, 'weight_class_1': 0.02974016030471099, 'weight_class_2': 0.050602573986682484}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:38,593] Trial 2996 finished with value: 0.942611358689036 and parameters: {'weight_class_0': 0.00904689674310021, 'weight_class_1': 0.04509403327974062, 'weight_class_2': 0.028482961657966648}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:38,600] Trial 2997 finished with value: 0.9485371997116188 and parameters: {'weight_class_0': 0.006290507936269882, 'weight_class_1': 0.03634760305231432, 'weight_class_2': 0.05680354195500758}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:38,600] Trial 2998 finished with value: 0.9479447719646759 and parameters: {'weight_class_0': 0.008425184669060342, 'weight_class_1': 0.046915354390097586, 'weight_class_2': 0.05503894957363373}. Best is trial 1741 with value: 0.9497368888684448.
[I 2026-07-03 10:57:38,608] Trial 2999 finished with value: 0.9432718790761152 and parameters: {'weight_class_0': 0.010818830565481325, 'weight_class_1': 0.035760298363508726, 'weight_class_2': 0.05148462385721662}. Best is trial 1741 with value: 0.9497368888684448.

Best trial score:
0.9497368888684448

Best params:
{'weight_class_0': 0.0046211977363148785, 'weight_class_1': 0.05696724052571766, 'weight_class_2': 0.05329217237247829}

In [32]:
weights = np.array([study.best_params['weight_class_0'], study.best_params['weight_class_1'], study.best_params['weight_class_2']])
weighted_probas = X_test.loc[:, ['xgb_0', 'xgb_1', 'xgb_2']].to_numpy() * weights

pred = np.argmax(weighted_probas, axis=1)

In [33]:
sub_labels = label_encoder.inverse_transform(pred)

# Submission

In [34]:
submission = pd.read_csv('../data/submission/sample_submission.csv')
submission['health_condition'] = sub_labels

submission.to_csv('../data/submission/submission_from_5.0.0_xgboost_submission.csv', index=False)

In [35]:
submission.head()

       id health_condition
0  690088        unhealthy
1  690089        unhealthy
2  690090          at-risk
3  690091          at-risk
4  690092        unhealthy