# Imports

In [1]:
import optuna
import pickle

import numpy as np
import pandas as pd

from tqdm import tqdm

from sklearn.metrics import balanced_accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold, cross_val_predict

/home/junior/Documentos/GitHub/kaggle-competition-predicting-student-health/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Utils

In [2]:
def load_pickle(file_path):
    with open(file_path, 'rb') as file:
        return pickle.load(file)

# Loading Datasets

In [3]:
X_train = pd.read_parquet('../data/processed/X_train_stacking_layer_one_model_60_trials.parquet')
y_train = pd.read_parquet('../data/interim/y_train.parquet')

X_test = pd.read_parquet('../data/processed/X_test_stacking_layer_one_model_60_trials.parquet')

In [4]:
X_train.head()

     lgbm_0    lgbm_1    lgbm_2     xgb_0     xgb_1     xgb_2
0  0.004922  0.001773  0.993304  0.004134  0.002593  0.993273
1  0.997228  0.000463  0.002309  0.995591  0.000405  0.004004
2  0.002369  0.000604  0.997026  0.001958  0.000503  0.997538
3  0.004656  0.003362  0.991982  0.002466  0.002391  0.995142
4  0.995353  0.000016  0.004632  0.994178  0.000003  0.005819

In [5]:
X_test.head()

     lgbm_0    lgbm_1    lgbm_2     xgb_0     xgb_1     xgb_2
0  0.012452  0.003199  0.984349  0.011048  0.004491  0.984461
1  0.472116  0.002331  0.525553  0.499186  0.001896  0.498918
2  0.998690  0.001012  0.000298  0.997826  0.001594  0.000579
3  0.980854  0.000018  0.019128  0.987434  0.000009  0.012557
4  0.006765  0.001847  0.991388  0.006876  0.001972  0.991152

# Machine Learning

In [6]:
label_encoder = load_pickle('../artifacts/label_encoder.pkl')

In [7]:
def objective(trial, X, y):

    w0 = trial.suggest_float('weight_class_0', 0.001, 10.0, log=True)
    w1 = trial.suggest_float('weight_class_1', 0.001, 10.0, log=True)
    w2 = trial.suggest_float('weight_class_2', 0.001, 10.0, log=True)
    weights = np.array([w0, w1, w2])

    proba = X.loc[:, ['xgb_0', 'xgb_1', 'xgb_2']].to_numpy()
    
    weighted_probas = proba * weights
    pred = np.argmax(weighted_probas, axis=1)
    
    score = balanced_accuracy_score(y, pred)

    return score


study = optuna.create_study(
    direction="maximize", 
    sampler=optuna.samplers.TPESampler(seed=42), 
    pruner=optuna.pruners.MedianPruner(n_warmup_steps=2)
)

study.optimize(
    lambda trial: objective(trial, X_train, y_train.health_condition), 
    n_trials=3000, 
    n_jobs=-1, 
    show_progress_bar=True
)

print("\nBest trial score:")
print(study.best_trial.value)

print("\nBest params:")
print(study.best_trial.params)

[I 2026-07-05 15:22:35,057] A new study created in memory with name: no-name-b00e72f4-a54f-45ac-89f8-33471ce3e38c

[I 2026-07-05 15:22:35,222] Trial 11 finished with value: 0.895963908712824 and parameters: {'weight_class_0': 0.02311989450309244, 'weight_class_1': 0.1570543993352876, 'weight_class_2': 0.009665862343121797}. Best is trial 11 with value: 0.895963908712824.
[I 2026-07-05 15:22:35,230] Trial 2 finished with value: 0.9385700378780707 and parameters: {'weight_class_0': 0.08083819625163449, 'weight_class_1': 1.492086360034119, 'weight_class_2': 9.472588432563894}. Best is trial 2 with value: 0.9385700378780707.
[I 2026-07-05 15:22:35,231] Trial 9 finished with value: 0.8560889758950183 and parameters: {'weight_class_0': 0.03824532413044154, 'weight_class_1': 0.037990348428025525, 'weight_class_2': 0.003739925565184149}. Best is trial 2 with value: 0.9385700378780707.
[I 2026-07-05 15:22:35,238] Trial 5 finished with value: 0.785736939064703 and parameters: {'weight_class_0': 0.3753210395297456, 'weight_class_1': 0.09834779943480151, 'weight_class_2': 0.0027570735187547714}. Best is trial 2 with value: 0.9385700378780707.
[I 2026-07-05 15:22:35,239] Trial 3 finished with value: 0.48170839223307754 and parameters: {'weight_class_0': 0.001336197534866867, 'weight_class_1': 6.963896011155115, 'weight_class_2': 0.0063258168387289445}. Best is trial 2 with value: 0.9385700378780707.
[I 2026-07-05 15:22:35,243] Trial 0 finished with value: 0.8540645960358132 and parameters: {'weight_class_0': 0.008680132886885832, 'weight_class_1': 0.006266270820511349, 'weight_class_2': 0.0025027267219121345}. Best is trial 2 with value: 0.9385700378780707.
[I 2026-07-05 15:22:35,244] Trial 1 finished with value: 0.9027412611718476 and parameters: {'weight_class_0': 0.0693143150685258, 'weight_class_1': 0.2749872168530082, 'weight_class_2': 0.05735124231767413}. Best is trial 2 with value: 0.9385700378780707.
[I 2026-07-05 15:22:35,244] Trial 4 finished with value: 0.903500617954164 and parameters: {'weight_class_0': 0.040476712083236714, 'weight_class_1': 0.025739247221435908, 'weight_class_2': 0.16288512514514875}. Best is trial 2 with value: 0.9385700378780707.
[I 2026-07-05 15:22:35,245] Trial 8 finished with value: 0.8774276167327981 and parameters: {'weight_class_0': 0.005168110851409752, 'weight_class_1': 0.31195753399835957, 'weight_class_2': 0.0017962352937620565}. Best is trial 2 with value: 0.9385700378780707.
[I 2026-07-05 15:22:35,256] Trial 6 finished with value: 0.593284275635172 and parameters: {'weight_class_0': 2.195114231451357, 'weight_class_1': 0.00414119412723677, 'weight_class_2': 0.4445357363720344}. Best is trial 2 with value: 0.9385700378780707.
[I 2026-07-05 15:22:35,257] Trial 10 finished with value: 0.744444632041028 and parameters: {'weight_class_0': 0.002381752090849164, 'weight_class_1': 0.003015012524889866, 'weight_class_2': 1.080654816342352}. Best is trial 2 with value: 0.9385700378780707.
[I 2026-07-05 15:22:35,274] Trial 7 finished with value: 0.8124286116210641 and parameters: {'weight_class_0': 0.3226697813029941, 'weight_class_1': 0.011289803813413381, 'weight_class_2': 0.08909571810268663}. Best is trial 2 with value: 0.9385700378780707.
[I 2026-07-05 15:22:35,377] Trial 12 finished with value: 0.8576359762666831 and parameters: {'weight_class_0': 0.014377050926506235, 'weight_class_1': 4.131460396637339, 'weight_class_2': 0.17637614815733293}. Best is trial 2 with value: 0.9385700378780707.

Best trial: 14. Best value: 0.949275:   1%|█                                                                                                                                     | 24/3000 [00:00<01:03, 46.84it/s]

[I 2026-07-05 15:22:35,385] Trial 13 finished with value: 0.6387573602127433 and parameters: {'weight_class_0': 0.0011493021461955154, 'weight_class_1': 3.7794056030194114, 'weight_class_2': 0.02150331895351918}. Best is trial 2 with value: 0.9385700378780707.
[I 2026-07-05 15:22:35,394] Trial 15 finished with value: 0.9472863819417698 and parameters: {'weight_class_0': 0.19286208680356037, 'weight_class_1': 4.789353901089488, 'weight_class_2': 7.8479742820727}. Best is trial 15 with value: 0.9472863819417698.
[I 2026-07-05 15:22:35,412] Trial 14 finished with value: 0.9492754112371443 and parameters: {'weight_class_0': 0.3109534868100954, 'weight_class_1': 4.429093046889, 'weight_class_2': 5.194426590398563}. Best is trial 14 with value: 0.9492754112371443.
[I 2026-07-05 15:22:35,426] Trial 16 finished with value: 0.9468775274322292 and parameters: {'weight_class_0': 0.21015167794547726, 'weight_class_1': 3.5155167258165214, 'weight_class_2': 9.420726505223355}. Best is trial 14 with value: 0.9492754112371443.
[I 2026-07-05 15:22:35,459] Trial 17 finished with value: 0.9465320540317089 and parameters: {'weight_class_0': 0.20135998455323204, 'weight_class_1': 2.30308631109721, 'weight_class_2': 9.447389630304272}. Best is trial 14 with value: 0.9492754112371443.
[I 2026-07-05 15:22:35,469] Trial 18 finished with value: 0.9467215502852162 and parameters: {'weight_class_0': 0.1716168260081989, 'weight_class_1': 2.7328387991713043, 'weight_class_2': 8.173319631701794}. Best is trial 14 with value: 0.9492754112371443.
[I 2026-07-05 15:22:35,478] Trial 19 finished with value: 0.9473141700739799 and parameters: {'weight_class_0': 0.1787952120849751, 'weight_class_1': 5.66196114138317, 'weight_class_2': 6.803853759110508}. Best is trial 14 with value: 0.9492754112371443.
[I 2026-07-05 15:22:35,493] Trial 20 finished with value: 0.9469082174460394 and parameters: {'weight_class_0': 0.2476397798243245, 'weight_class_1': 2.739356365383754, 'weight_class_2': 9.904087610503018}. Best is trial 14 with value: 0.9492754112371443.
[I 2026-07-05 15:22:35,495] Trial 21 finished with value: 0.9480404683984185 and parameters: {'weight_class_0': 0.1936125914441563, 'weight_class_1': 2.942504423613831, 'weight_class_2': 5.548730058364282}. Best is trial 14 with value: 0.9492754112371443.
[I 2026-07-05 15:22:35,525] Trial 22 finished with value: 0.9454461359506013 and parameters: {'weight_class_0': 0.13677236430113504, 'weight_class_1': 0.7659491484316749, 'weight_class_2': 5.884150921481577}. Best is trial 14 with value: 0.9492754112371443.
[I 2026-07-05 15:22:35,551] Trial 24 finished with value: 0.8728721947190671 and parameters: {'weight_class_0': 2.1489874238463975, 'weight_class_1': 1.051298807234639, 'weight_class_2': 2.90645633917878}. Best is trial 14 with value: 0.9492754112371443.
[I 2026-07-05 15:22:35,561] Trial 23 finished with value: 0.9454493019535318 and parameters: {'weight_class_0': 0.21245186229927165, 'weight_class_1': 1.144054334153498, 'weight_class_2': 8.742081313382768}. Best is trial 14 with value: 0.9492754112371443.

Best trial: 14. Best value: 0.949275:   1%|█▌                                                                                                                                    | 35/3000 [00:00<00:58, 50.67it/s]

[I 2026-07-05 15:22:35,581] Trial 25 finished with value: 0.8469416292479467 and parameters: {'weight_class_0': 2.8513353004387483, 'weight_class_1': 0.7889598586127061, 'weight_class_2': 2.5381920389389445}. Best is trial 14 with value: 0.9492754112371443.
[I 2026-07-05 15:22:35,616] Trial 26 finished with value: 0.8810169406625006 and parameters: {'weight_class_0': 1.5347945621428467, 'weight_class_1': 0.9190252350926942, 'weight_class_2': 2.3103029442456613}. Best is trial 14 with value: 0.9492754112371443.
[I 2026-07-05 15:22:35,623] Trial 27 finished with value: 0.8909576215049997 and parameters: {'weight_class_0': 1.1921700474532677, 'weight_class_1': 0.9194753879186854, 'weight_class_2': 2.0445531523920177}. Best is trial 14 with value: 0.9492754112371443.
[I 2026-07-05 15:22:35,636] Trial 28 finished with value: 0.9005559674286813 and parameters: {'weight_class_0': 0.9821930423950055, 'weight_class_1': 0.8338581026100541, 'weight_class_2': 2.156830810538945}. Best is trial 14 with value: 0.9492754112371443.
[I 2026-07-05 15:22:35,656] Trial 29 finished with value: 0.937079598935644 and parameters: {'weight_class_0': 1.0339916317184006, 'weight_class_1': 9.36118559526196, 'weight_class_2': 2.268530420398589}. Best is trial 14 with value: 0.9492754112371443.
[I 2026-07-05 15:22:35,677] Trial 30 finished with value: 0.9074073463255292 and parameters: {'weight_class_0': 0.9300280022634889, 'weight_class_1': 1.013802007962526, 'weight_class_2': 2.0431430916788234}. Best is trial 14 with value: 0.9492754112371443.
[I 2026-07-05 15:22:35,712] Trial 31 finished with value: 0.9454145056433392 and parameters: {'weight_class_0': 0.5661879159888348, 'weight_class_1': 9.60339362138587, 'weight_class_2': 1.9628078652402303}. Best is trial 14 with value: 0.9492754112371443.
[I 2026-07-05 15:22:35,722] Trial 32 finished with value: 0.9418650559371162 and parameters: {'weight_class_0': 0.748339461456728, 'weight_class_1': 9.415614245278201, 'weight_class_2': 2.0249266237781542}. Best is trial 14 with value: 0.9492754112371443.
[I 2026-07-05 15:22:35,746] Trial 33 finished with value: 0.6282348758789387 and parameters: {'weight_class_0': 0.8223963065275963, 'weight_class_1': 0.0010933929789800564, 'weight_class_2': 1.5091004483157715}. Best is trial 14 with value: 0.9492754112371443.
[I 2026-07-05 15:22:35,761] Trial 35 finished with value: 0.8530566551928089 and parameters: {'weight_class_0': 8.881350404650084, 'weight_class_1': 8.05181706089426, 'weight_class_2': 0.8037109786314016}. Best is trial 14 with value: 0.9492754112371443.
[I 2026-07-05 15:22:35,774] Trial 34 finished with value: 0.9250350093544767 and parameters: {'weight_class_0': 1.0407983360725, 'weight_class_1': 6.7564300929283645, 'weight_class_2': 1.5740785237688726}. Best is trial 14 with value: 0.9492754112371443.

Best trial: 14. Best value: 0.949275:   2%|██                                                                                                                                    | 47/3000 [00:00<00:55, 52.89it/s]

[I 2026-07-05 15:22:35,794] Trial 36 finished with value: 0.8604284870721134 and parameters: {'weight_class_0': 7.727285483229669, 'weight_class_1': 8.987489163263694, 'weight_class_2': 0.7112538393033351}. Best is trial 14 with value: 0.9492754112371443.
[I 2026-07-05 15:22:35,798] Trial 37 finished with value: 0.8806076558468017 and parameters: {'weight_class_0': 4.912593183022711, 'weight_class_1': 9.982236377762602, 'weight_class_2': 0.985122739989062}. Best is trial 14 with value: 0.9492754112371443.
[I 2026-07-05 15:22:35,835] Trial 39 finished with value: 0.9173344504847071 and parameters: {'weight_class_0': 0.5177186811789846, 'weight_class_1': 6.11909076074895, 'weight_class_2': 0.6149962802819768}. Best is trial 14 with value: 0.9492754112371443.
[I 2026-07-05 15:22:35,861] Trial 40 finished with value: 0.9468622385431927 and parameters: {'weight_class_0': 0.10156426082488365, 'weight_class_1': 5.606788632463669, 'weight_class_2': 0.9453038938493621}. Best is trial 14 with value: 0.9492754112371443.
[I 2026-07-05 15:22:35,864] Trial 38 finished with value: 0.9284154605597282 and parameters: {'weight_class_0': 0.5217586763877686, 'weight_class_1': 6.206065296441435, 'weight_class_2': 0.8528919470690021}. Best is trial 14 with value: 0.9492754112371443.
[I 2026-07-05 15:22:35,871] Trial 41 finished with value: 0.9429866784903473 and parameters: {'weight_class_0': 0.10318927214199837, 'weight_class_1': 0.3790945013516705, 'weight_class_2': 4.717980643300795}. Best is trial 14 with value: 0.9492754112371443.
[I 2026-07-05 15:22:35,896] Trial 42 finished with value: 0.8710840633540062 and parameters: {'weight_class_0': 5.5942067706174905, 'weight_class_1': 5.455850860286676, 'weight_class_2': 4.282285992218731}. Best is trial 14 with value: 0.9492754112371443.
[I 2026-07-05 15:22:35,908] Trial 43 finished with value: 0.9436472119053242 and parameters: {'weight_class_0': 0.09275589244567889, 'weight_class_1': 0.3790038575383619, 'weight_class_2': 4.4120031818737635}. Best is trial 14 with value: 0.9492754112371443.
[I 2026-07-05 15:22:35,954] Trial 44 finished with value: 0.9435537597528771 and parameters: {'weight_class_0': 0.09589842693094783, 'weight_class_1': 0.41750141896554216, 'weight_class_2': 5.215409377559505}. Best is trial 14 with value: 0.9492754112371443.
[I 2026-07-05 15:22:35,958] Trial 45 finished with value: 0.9473306159982574 and parameters: {'weight_class_0': 0.11353822568038502, 'weight_class_1': 2.075489708797221, 'weight_class_2': 4.425250280059705}. Best is trial 14 with value: 0.9492754112371443.
[I 2026-07-05 15:22:35,978] Trial 46 finished with value: 0.944425424386025 and parameters: {'weight_class_0': 0.09158726870464104, 'weight_class_1': 0.4180708838686217, 'weight_class_2': 4.220608661593917}. Best is trial 14 with value: 0.9492754112371443.
[I 2026-07-05 15:22:35,995] Trial 47 finished with value: 0.9468219272455847 and parameters: {'weight_class_0': 0.08935455911056563, 'weight_class_1': 1.907519586622014, 'weight_class_2': 4.264680157521258}. Best is trial 14 with value: 0.9492754112371443.

Best trial: 58. Best value: 0.949607:   2%|██▋                                                                                                                                   | 60/3000 [00:01<00:54, 53.91it/s]

[I 2026-07-05 15:22:36,009] Trial 48 finished with value: 0.9444766975796748 and parameters: {'weight_class_0': 0.05882132918557791, 'weight_class_1': 1.6939697608991138, 'weight_class_2': 4.493159963922289}. Best is trial 14 with value: 0.9492754112371443.
[I 2026-07-05 15:22:36,039] Trial 49 finished with value: 0.9440811921039792 and parameters: {'weight_class_0': 0.056073726414506045, 'weight_class_1': 2.0142154489886983, 'weight_class_2': 4.432603259933035}. Best is trial 14 with value: 0.9492754112371443.
[I 2026-07-05 15:22:36,059] Trial 50 finished with value: 0.9390226915388271 and parameters: {'weight_class_0': 0.05255109092392272, 'weight_class_1': 1.9773591492564413, 'weight_class_2': 5.980938128683387}. Best is trial 14 with value: 0.9492754112371443.
[I 2026-07-05 15:22:36,066] Trial 51 finished with value: 0.9462801118138788 and parameters: {'weight_class_0': 0.0693200197165378, 'weight_class_1': 1.8578819399654132, 'weight_class_2': 3.836380422070856}. Best is trial 14 with value: 0.9492754112371443.
[I 2026-07-05 15:22:36,093] Trial 52 finished with value: 0.9414387415720477 and parameters: {'weight_class_0': 0.06048269764609828, 'weight_class_1': 1.65517394922564, 'weight_class_2': 6.124491143962093}. Best is trial 14 with value: 0.9492754112371443.
[I 2026-07-05 15:22:36,122] Trial 53 finished with value: 0.9485408656581513 and parameters: {'weight_class_0': 0.04804054011410223, 'weight_class_1': 1.7838684627178647, 'weight_class_2': 0.3785864476394581}. Best is trial 14 with value: 0.9492754112371443.
[I 2026-07-05 15:22:36,136] Trial 54 finished with value: 0.9481640324637185 and parameters: {'weight_class_0': 0.05342054606303596, 'weight_class_1': 1.626380855865568, 'weight_class_2': 0.3154494528404903}. Best is trial 14 with value: 0.9492754112371443.
[I 2026-07-05 15:22:36,144] Trial 55 finished with value: 0.9478067981176505 and parameters: {'weight_class_0': 0.04542456970845939, 'weight_class_1': 1.783450764162368, 'weight_class_2': 0.29614802257663614}. Best is trial 14 with value: 0.9492754112371443.
[I 2026-07-05 15:22:36,163] Trial 57 finished with value: 0.6873908567499037 and parameters: {'weight_class_0': 0.04060475886322746, 'weight_class_1': 3.8219425148461763, 'weight_class_2': 0.0010108103529461229}. Best is trial 14 with value: 0.9492754112371443.
[I 2026-07-05 15:22:36,169] Trial 56 finished with value: 0.9064686201008691 and parameters: {'weight_class_0': 0.3377985907536335, 'weight_class_1': 3.744580631605781, 'weight_class_2': 0.2885797836087227}. Best is trial 14 with value: 0.9492754112371443.
[I 2026-07-05 15:22:36,195] Trial 58 finished with value: 0.9496066835906559 and parameters: {'weight_class_0': 0.33579790427072154, 'weight_class_1': 3.872295214408219, 'weight_class_2': 3.228038353961431}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:36,212] Trial 59 finished with value: 0.9482764562070566 and parameters: {'weight_class_0': 0.3334143329634369, 'weight_class_1': 3.239062403914605, 'weight_class_2': 7.021493225900493}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:36,227] Trial 60 finished with value: 0.948586348797472 and parameters: {'weight_class_0': 0.31745591065623585, 'weight_class_1': 3.2333744069998134, 'weight_class_2': 6.190842493012698}. Best is trial 58 with value: 0.9496066835906559.

[I 2026-07-05 15:22:36,242] Trial 61 finished with value: 0.9482260211365835 and parameters: {'weight_class_0': 0.32762263639063816, 'weight_class_1': 3.389660242361702, 'weight_class_2': 7.295988323738256}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:36,308] Trial 62 finished with value: 0.9200885877553407 and parameters: {'weight_class_0': 0.025473766592031922, 'weight_class_1': 3.6761346463261964, 'weight_class_2': 0.25824458873524425}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:36,316] Trial 63 finished with value: 0.9304979167328803 and parameters: {'weight_class_0': 0.028008651575462454, 'weight_class_1': 3.3017226137683235, 'weight_class_2': 0.2736991139081994}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:36,327] Trial 64 finished with value: 0.9151269597055399 and parameters: {'weight_class_0': 0.0213123895103213, 'weight_class_1': 3.278487181814617, 'weight_class_2': 0.16146725641204956}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:36,338] Trial 65 finished with value: 0.946740123657048 and parameters: {'weight_class_0': 0.019467035454655703, 'weight_class_1': 0.5640955707867356, 'weight_class_2': 0.08422799506983344}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:36,353] Trial 66 finished with value: 0.9480590518274309 and parameters: {'weight_class_0': 0.016950720828948287, 'weight_class_1': 0.5592486452339799, 'weight_class_2': 0.10248529182305864}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:36,364] Trial 67 finished with value: 0.9353717483895144 and parameters: {'weight_class_0': 0.027186452856044648, 'weight_class_1': 0.5805586293031109, 'weight_class_2': 0.056536961381545375}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:36,405] Trial 69 finished with value: 0.9450906702909778 and parameters: {'weight_class_0': 0.020491881316910016, 'weight_class_1': 0.611242077030103, 'weight_class_2': 0.07274331132054172}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:36,411] Trial 70 finished with value: 0.9428086430781647 and parameters: {'weight_class_0': 0.025339015991454602, 'weight_class_1': 0.5634682724353387, 'weight_class_2': 0.07371651530604773}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:36,421] Trial 68 finished with value: 0.9041618222724579 and parameters: {'weight_class_0': 0.02031044328502933, 'weight_class_1': 2.953035954009174, 'weight_class_2': 0.04960531951529725}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:36,449] Trial 71 finished with value: 0.8770410043588318 and parameters: {'weight_class_0': 0.022816044063241888, 'weight_class_1': 2.8191077757544076, 'weight_class_2': 0.020932395813295104}. Best is trial 58 with value: 0.9496066835906559.

[I 2026-07-05 15:22:36,465] Trial 72 finished with value: 0.9160758651565066 and parameters: {'weight_class_0': 0.02622272507584528, 'weight_class_1': 3.0361864122652613, 'weight_class_2': 0.05948261262471462}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:36,476] Trial 73 finished with value: 0.9304380652802436 and parameters: {'weight_class_0': 0.004802730756354469, 'weight_class_1': 0.5644563109763454, 'weight_class_2': 0.042952341338267065}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:36,503] Trial 75 finished with value: 0.9070488193416484 and parameters: {'weight_class_0': 0.009766883681347004, 'weight_class_1': 1.3748020736230162, 'weight_class_2': 0.024402746762051813}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:36,518] Trial 74 finished with value: 0.9008327203653289 and parameters: {'weight_class_0': 0.00778816228956893, 'weight_class_1': 1.172576329426082, 'weight_class_2': 0.018410740125459128}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:36,522] Trial 76 finished with value: 0.9465195094431217 and parameters: {'weight_class_0': 0.27738407513122393, 'weight_class_1': 1.3177630591085512, 'weight_class_2': 1.4240804200639958}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:36,552] Trial 77 finished with value: 0.9099201018993548 and parameters: {'weight_class_0': 0.007631799628151563, 'weight_class_1': 1.2760549866892856, 'weight_class_2': 0.5001256578229871}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:36,566] Trial 78 finished with value: 0.9420526838559512 and parameters: {'weight_class_0': 0.007678220084577797, 'weight_class_1': 0.1809862535062931, 'weight_class_2': 0.02148753351347857}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:36,584] Trial 79 finished with value: 0.8752552683316722 and parameters: {'weight_class_0': 0.0051762869904625084, 'weight_class_1': 1.2944829393782211, 'weight_class_2': 0.12257309272206908}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:36,613] Trial 81 finished with value: 0.8504829980073977 and parameters: {'weight_class_0': 0.009823372961068798, 'weight_class_1': 1.2816228273561587, 'weight_class_2': 3.1130765475419673}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:36,616] Trial 80 finished with value: 0.8786331008095507 and parameters: {'weight_class_0': 0.01044674335698728, 'weight_class_1': 0.1412106377425562, 'weight_class_2': 2.9403242943709023}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:36,654] Trial 83 finished with value: 0.8577221775157721 and parameters: {'weight_class_0': 0.2616197807372338, 'weight_class_1': 0.19481512133541792, 'weight_class_2': 0.1228113899307865}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:36,664] Trial 84 finished with value: 0.894492710745927 and parameters: {'weight_class_0': 0.4322822678954726, 'weight_class_1': 4.784123722795969, 'weight_class_2': 0.12943964488960594}. Best is trial 58 with value: 0.9496066835906559.

Best trial: 58. Best value: 0.949607:   3%|████▏                                                                                                                                 | 95/3000 [00:01<00:51, 56.21it/s]

[I 2026-07-05 15:22:36,669] Trial 82 finished with value: 0.9373151116308384 and parameters: {'weight_class_0': 0.013183680988990401, 'weight_class_1': 1.2944234537389203, 'weight_class_2': 0.12744576036683802}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:36,698] Trial 86 finished with value: 0.8246203960837212 and parameters: {'weight_class_0': 0.41211111204956247, 'weight_class_1': 0.04588712150373798, 'weight_class_2': 0.1531538656951797}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:36,701] Trial 85 finished with value: 0.8807801065220285 and parameters: {'weight_class_0': 0.38752820952360795, 'weight_class_1': 0.05713504998067177, 'weight_class_2': 3.0771481397975062}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:36,731] Trial 87 finished with value: 0.9020276144439817 and parameters: {'weight_class_0': 0.1399001160043393, 'weight_class_1': 0.07537594770645095, 'weight_class_2': 2.9961201702314346}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:36,754] Trial 89 finished with value: 0.9488757151765769 and parameters: {'weight_class_0': 0.4013564913260555, 'weight_class_1': 4.743233507363019, 'weight_class_2': 7.347064361708709}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:36,767] Trial 88 finished with value: 0.8840947608846421 and parameters: {'weight_class_0': 0.39985393019108717, 'weight_class_1': 0.08312952258260617, 'weight_class_2': 2.850854963051935}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:36,786] Trial 90 finished with value: 0.9477702001852792 and parameters: {'weight_class_0': 0.39685316226302975, 'weight_class_1': 2.5055143335901864, 'weight_class_2': 7.56368288799568}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:36,794] Trial 91 finished with value: 0.9488386602685751 and parameters: {'weight_class_0': 0.42543495094375944, 'weight_class_1': 4.356555609428773, 'weight_class_2': 7.49440939832652}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:36,826] Trial 92 finished with value: 0.8929236926412161 and parameters: {'weight_class_0': 0.14661617681066422, 'weight_class_1': 0.061328042559596646, 'weight_class_2': 7.381247410042326}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:36,839] Trial 93 finished with value: 0.9462199878076635 and parameters: {'weight_class_0': 0.13953005942933497, 'weight_class_1': 2.4156644361807307, 'weight_class_2': 7.714823087733469}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:36,854] Trial 94 finished with value: 0.9466278022071228 and parameters: {'weight_class_0': 0.14649035437502306, 'weight_class_1': 2.4206530981859737, 'weight_class_2': 7.191146767144007}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:36,885] Trial 96 finished with value: 0.9467114655548553 and parameters: {'weight_class_0': 0.15587175704980538, 'weight_class_1': 2.450218248311615, 'weight_class_2': 7.406568352176529}. Best is trial 58 with value: 0.9496066835906559.

Best trial: 58. Best value: 0.949607:   4%|████▋                                                                                                                                | 107/3000 [00:02<00:53, 54.08it/s]

[I 2026-07-05 15:22:36,893] Trial 95 finished with value: 0.9469012352774065 and parameters: {'weight_class_0': 0.17956484676394338, 'weight_class_1': 2.340057970939295, 'weight_class_2': 7.603444743655196}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:36,904] Trial 97 finished with value: 0.9489575508909794 and parameters: {'weight_class_0': 0.648504409317441, 'weight_class_1': 4.377223443118657, 'weight_class_2': 6.871404577001778}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:36,928] Trial 98 finished with value: 0.9491113636053922 and parameters: {'weight_class_0': 0.6164528306476262, 'weight_class_1': 4.64708249607296, 'weight_class_2': 7.672699874050194}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:36,955] Trial 100 finished with value: 0.9491506453592301 and parameters: {'weight_class_0': 0.6260283132093977, 'weight_class_1': 4.818044560417039, 'weight_class_2': 7.636487038157329}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:36,962] Trial 99 finished with value: 0.9486955314401623 and parameters: {'weight_class_0': 0.6387896034508052, 'weight_class_1': 4.809914908640473, 'weight_class_2': 9.833044625607918}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:36,990] Trial 101 finished with value: 0.9483953465495304 and parameters: {'weight_class_0': 0.6892256919109829, 'weight_class_1': 4.214663987284312, 'weight_class_2': 9.54229416093568}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:36,999] Trial 102 finished with value: 0.9485153129824955 and parameters: {'weight_class_0': 0.7721169840954704, 'weight_class_1': 4.573527825012889, 'weight_class_2': 9.157868987195862}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:37,007] Trial 103 finished with value: 0.9492979513162014 and parameters: {'weight_class_0': 0.6825099317050496, 'weight_class_1': 6.3958178687053575, 'weight_class_2': 9.173858520388738}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:37,043] Trial 105 finished with value: 0.9492958101857182 and parameters: {'weight_class_0': 0.5970162614974873, 'weight_class_1': 4.518562485915394, 'weight_class_2': 5.61945539064661}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:37,046] Trial 104 finished with value: 0.9493234353551782 and parameters: {'weight_class_0': 0.6051454581118229, 'weight_class_1': 4.811084828131099, 'weight_class_2': 5.411734239307058}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:37,089] Trial 107 finished with value: 0.9487658767790088 and parameters: {'weight_class_0': 0.6584654637104808, 'weight_class_1': 4.596442856079599, 'weight_class_2': 9.043770406762397}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:37,090] Trial 106 finished with value: 0.9476956058386398 and parameters: {'weight_class_0': 1.4530572156718302, 'weight_class_1': 7.536409592152922, 'weight_class_2': 9.564446949941862}. Best is trial 58 with value: 0.9496066835906559.

[I 2026-07-05 15:22:37,106] Trial 108 finished with value: 0.9493543613668685 and parameters: {'weight_class_0': 0.6533513026721912, 'weight_class_1': 7.181642266513577, 'weight_class_2': 9.157049007889665}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:37,119] Trial 109 finished with value: 0.948558886778471 and parameters: {'weight_class_0': 0.7177603936010014, 'weight_class_1': 4.4999740527906145, 'weight_class_2': 9.400113348757772}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:37,149] Trial 110 finished with value: 0.9465572966516452 and parameters: {'weight_class_0': 1.2487068665394414, 'weight_class_1': 6.764035292242828, 'weight_class_2': 5.794412373825656}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:37,157] Trial 111 finished with value: 0.9440255344605486 and parameters: {'weight_class_0': 1.5216154733617864, 'weight_class_1': 7.426789885705457, 'weight_class_2': 5.3920306981942305}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:37,189] Trial 113 finished with value: 0.94190257703587 and parameters: {'weight_class_0': 1.3531435007196364, 'weight_class_1': 8.234922437930514, 'weight_class_2': 3.86055433165485}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:37,199] Trial 112 finished with value: 0.9410748029337433 and parameters: {'weight_class_0': 1.3771189415372425, 'weight_class_1': 7.586544528040767, 'weight_class_2': 3.826701803439174}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:37,229] Trial 114 finished with value: 0.9350440933935328 and parameters: {'weight_class_0': 1.6147696581273163, 'weight_class_1': 6.533284458187791, 'weight_class_2': 3.653284671300471}. Best is trial 58 with value: 0.9496066835906559.
[I 2026-07-05 15:22:37,248] Trial 116 finished with value: 0.9496287604146522 and parameters: {'weight_class_0': 0.4972466889800421, 'weight_class_1': 6.747170502495633, 'weight_class_2': 5.383025803932024}. Best is trial 116 with value: 0.9496287604146522.
[I 2026-07-05 15:22:37,257] Trial 115 finished with value: 0.9493779081141925 and parameters: {'weight_class_0': 0.4964476738124131, 'weight_class_1': 6.854689634076932, 'weight_class_2': 3.6762972982739934}. Best is trial 116 with value: 0.9496287604146522.
[I 2026-07-05 15:22:37,271] Trial 117 finished with value: 0.9449046663731059 and parameters: {'weight_class_0': 1.3996754375354457, 'weight_class_1': 6.905965253285399, 'weight_class_2': 5.418376783839278}. Best is trial 116 with value: 0.9496287604146522.
[I 2026-07-05 15:22:37,286] Trial 118 finished with value: 0.9416160706773343 and parameters: {'weight_class_0': 1.261183641777857, 'weight_class_1': 7.276938054305378, 'weight_class_2': 3.5742905712974635}. Best is trial 116 with value: 0.9496287604146522.

Best trial: 116. Best value: 0.949629:   4%|█████▊                                                                                                                              | 131/3000 [00:02<00:52, 54.99it/s]

[I 2026-07-05 15:22:37,318] Trial 119 finished with value: 0.9490153087990508 and parameters: {'weight_class_0': 0.5602887421750129, 'weight_class_1': 5.879952642077447, 'weight_class_2': 3.8390500437645403}. Best is trial 116 with value: 0.9496287604146522.
[I 2026-07-05 15:22:37,322] Trial 120 finished with value: 0.9490051485664402 and parameters: {'weight_class_0': 0.5239455544463035, 'weight_class_1': 5.474855821472483, 'weight_class_2': 3.577732809451353}. Best is trial 116 with value: 0.9496287604146522.
[I 2026-07-05 15:22:37,345] Trial 121 finished with value: 0.9495743228388065 and parameters: {'weight_class_0': 0.5093532901294446, 'weight_class_1': 5.619303831129125, 'weight_class_2': 5.2692755134200855}. Best is trial 116 with value: 0.9496287604146522.
[I 2026-07-05 15:22:37,364] Trial 122 finished with value: 0.9496108268410812 and parameters: {'weight_class_0': 0.5304656280836059, 'weight_class_1': 5.833404368189275, 'weight_class_2': 5.199255508166065}. Best is trial 116 with value: 0.9496287604146522.
[I 2026-07-05 15:22:37,394] Trial 123 finished with value: 0.9495448490133102 and parameters: {'weight_class_0': 0.5069268392803716, 'weight_class_1': 5.389785680747292, 'weight_class_2': 5.885818749188529}. Best is trial 116 with value: 0.9496287604146522.
[I 2026-07-05 15:22:37,411] Trial 124 finished with value: 0.9495625489224689 and parameters: {'weight_class_0': 0.5030871886468531, 'weight_class_1': 5.504424435404983, 'weight_class_2': 5.099875567204572}. Best is trial 116 with value: 0.9496287604146522.
[I 2026-07-05 15:22:37,435] Trial 125 finished with value: 0.949582091091069 and parameters: {'weight_class_0': 0.5209003755500673, 'weight_class_1': 5.648067478519189, 'weight_class_2': 5.010516800115549}. Best is trial 116 with value: 0.9496287604146522.
[I 2026-07-05 15:22:37,456] Trial 126 finished with value: 0.9495619788854007 and parameters: {'weight_class_0': 0.5196259270964873, 'weight_class_1': 5.5814166983252385, 'weight_class_2': 5.007799903290925}. Best is trial 116 with value: 0.9496287604146522.
[I 2026-07-05 15:22:37,465] Trial 127 finished with value: 0.9495884733511742 and parameters: {'weight_class_0': 0.505690268391502, 'weight_class_1': 5.59769674342433, 'weight_class_2': 4.8799384785849655}. Best is trial 116 with value: 0.9496287604146522.
[I 2026-07-05 15:22:37,477] Trial 128 finished with value: 0.9495373544120778 and parameters: {'weight_class_0': 0.5267401908351632, 'weight_class_1': 5.489657873018287, 'weight_class_2': 4.99583100996046}. Best is trial 116 with value: 0.9496287604146522.
[I 2026-07-05 15:22:37,504] Trial 129 finished with value: 0.9453400089046111 and parameters: {'weight_class_0': 0.49223676928263166, 'weight_class_1': 5.790782726017883, 'weight_class_2': 1.6882644489105636}. Best is trial 116 with value: 0.9496287604146522.
[I 2026-07-05 15:22:37,507] Trial 130 finished with value: 0.9482201593007487 and parameters: {'weight_class_0': 0.8372559247834743, 'weight_class_1': 5.704157186903868, 'weight_class_2': 4.893602793536749}. Best is trial 116 with value: 0.9496287604146522.
[I 2026-07-05 15:22:37,539] Trial 131 finished with value: 0.947951359108997 and parameters: {'weight_class_0': 0.9636984040009724, 'weight_class_1': 8.953126347959603, 'weight_class_2': 4.681234703972149}. Best is trial 116 with value: 0.9496287604146522.

Best trial: 116. Best value: 0.949629:   5%|██████▎                                                                                                                             | 143/3000 [00:02<00:51, 55.09it/s]

[I 2026-07-05 15:22:37,558] Trial 132 finished with value: 0.9476390052790521 and parameters: {'weight_class_0': 0.9492553041851485, 'weight_class_1': 5.826538514103078, 'weight_class_2': 5.046816970790824}. Best is trial 116 with value: 0.9496287604146522.
[I 2026-07-05 15:22:37,573] Trial 133 finished with value: 0.9485944481373386 and parameters: {'weight_class_0': 0.9284876066327982, 'weight_class_1': 9.572584925096477, 'weight_class_2': 5.178700470857327}. Best is trial 116 with value: 0.9496287604146522.
[I 2026-07-05 15:22:37,587] Trial 134 finished with value: 0.9320763249869976 and parameters: {'weight_class_0': 0.9576364951215033, 'weight_class_1': 9.726443710998584, 'weight_class_2': 1.7653716698491064}. Best is trial 116 with value: 0.9496287604146522.
[I 2026-07-05 15:22:37,618] Trial 135 finished with value: 0.9310723625550755 and parameters: {'weight_class_0': 0.9607039827199868, 'weight_class_1': 9.561066813727606, 'weight_class_2': 1.709417679068996}. Best is trial 116 with value: 0.9496287604146522.
[I 2026-07-05 15:22:37,630] Trial 136 finished with value: 0.9394131033009027 and parameters: {'weight_class_0': 0.9216870640693509, 'weight_class_1': 5.699656901500152, 'weight_class_2': 2.3107080376638023}. Best is trial 116 with value: 0.9496287604146522.
[I 2026-07-05 15:22:37,661] Trial 138 finished with value: 0.9427702925042462 and parameters: {'weight_class_0': 0.9327377978557366, 'weight_class_1': 9.029924309506969, 'weight_class_2': 2.664098320008052}. Best is trial 116 with value: 0.9496287604146522.
[I 2026-07-05 15:22:37,662] Trial 137 finished with value: 0.9484123134835984 and parameters: {'weight_class_0': 0.22569419818462821, 'weight_class_1': 9.465399882349487, 'weight_class_2': 2.634452541876094}. Best is trial 116 with value: 0.9496287604146522.
[I 2026-07-05 15:22:37,693] Trial 139 finished with value: 0.9403198156382649 and parameters: {'weight_class_0': 0.9592557006605091, 'weight_class_1': 9.520016951916002, 'weight_class_2': 2.4062523374454576}. Best is trial 116 with value: 0.9496287604146522.
[I 2026-07-05 15:22:37,702] Trial 140 finished with value: 0.8502899981456687 and parameters: {'weight_class_0': 0.2279820969260023, 'weight_class_1': 0.01362535341880158, 'weight_class_2': 5.8938234180930245}. Best is trial 116 with value: 0.9496287604146522.
[I 2026-07-05 15:22:37,722] Trial 142 finished with value: 0.9484037367008086 and parameters: {'weight_class_0': 0.21863210004746117, 'weight_class_1': 8.923194302029653, 'weight_class_2': 2.236010566218959}. Best is trial 116 with value: 0.9496287604146522.
[I 2026-07-05 15:22:37,739] Trial 141 finished with value: 0.9491630052998316 and parameters: {'weight_class_0': 0.29293543317483195, 'weight_class_1': 8.59063547110635, 'weight_class_2': 2.663386996573693}. Best is trial 116 with value: 0.9496287604146522.
[I 2026-07-05 15:22:37,740] Trial 143 finished with value: 0.949569944484816 and parameters: {'weight_class_0': 0.2689575094479576, 'weight_class_1': 3.8961232275640567, 'weight_class_2': 2.7191703637837357}. Best is trial 116 with value: 0.9496287604146522.

[I 2026-07-05 15:22:37,766] Trial 144 finished with value: 0.8678713705016556 and parameters: {'weight_class_0': 0.23403300166963847, 'weight_class_1': 0.012491611724502976, 'weight_class_2': 2.8059274513381784}. Best is trial 116 with value: 0.9496287604146522.
[I 2026-07-05 15:22:37,782] Trial 145 finished with value: 0.9495876690459459 and parameters: {'weight_class_0': 0.21595158429006756, 'weight_class_1': 3.7284992070405676, 'weight_class_2': 2.616688507944568}. Best is trial 116 with value: 0.9496287604146522.
[I 2026-07-05 15:22:37,812] Trial 146 finished with value: 0.947403182190412 and parameters: {'weight_class_0': 0.276705950592066, 'weight_class_1': 3.696157173791171, 'weight_class_2': 1.205225688807723}. Best is trial 116 with value: 0.9496287604146522.
[I 2026-07-05 15:22:37,827] Trial 147 finished with value: 0.9487059305745573 and parameters: {'weight_class_0': 0.28527752037626847, 'weight_class_1': 3.6538880949065295, 'weight_class_2': 6.008007543556808}. Best is trial 116 with value: 0.9496287604146522.
[I 2026-07-05 15:22:37,852] Trial 148 finished with value: 0.9491264989751297 and parameters: {'weight_class_0': 0.49027402478780313, 'weight_class_1': 3.7383160558291917, 'weight_class_2': 6.104235222868539}. Best is trial 116 with value: 0.9496287604146522.
[I 2026-07-05 15:22:37,859] Trial 149 finished with value: 0.949093415380112 and parameters: {'weight_class_0': 0.48072532244241895, 'weight_class_1': 3.716597954485513, 'weight_class_2': 6.213733565835354}. Best is trial 116 with value: 0.9496287604146522.
[I 2026-07-05 15:22:37,883] Trial 150 finished with value: 0.949226914930323 and parameters: {'weight_class_0': 0.5238656100787431, 'weight_class_1': 3.7048056766213375, 'weight_class_2': 4.424157697767205}. Best is trial 116 with value: 0.9496287604146522.
[I 2026-07-05 15:22:37,901] Trial 151 finished with value: 0.9403280238844971 and parameters: {'weight_class_0': 0.4586156773402948, 'weight_class_1': 3.6142654347436043, 'weight_class_2': 1.1661534419814459}. Best is trial 116 with value: 0.9496287604146522.
[I 2026-07-05 15:22:37,916] Trial 152 finished with value: 0.9489183621303724 and parameters: {'weight_class_0': 0.4840817650132441, 'weight_class_1': 3.664054938653389, 'weight_class_2': 3.4288727016139147}. Best is trial 116 with value: 0.9496287604146522.
[I 2026-07-05 15:22:37,929] Trial 153 finished with value: 0.9490053479854194 and parameters: {'weight_class_0': 0.47160530155360475, 'weight_class_1': 3.5560712129167897, 'weight_class_2': 3.5107205736301212}. Best is trial 116 with value: 0.9496287604146522.
[I 2026-07-05 15:22:37,956] Trial 154 finished with value: 0.9488968239787746 and parameters: {'weight_class_0': 0.4601033389308313, 'weight_class_1': 3.684752758191443, 'weight_class_2': 3.166058168875029}. Best is trial 116 with value: 0.9496287604146522.

Best trial: 167. Best value: 0.949645:   6%|███████▎                                                                                                                            | 166/3000 [00:03<00:50, 55.75it/s]

[I 2026-07-05 15:22:37,965] Trial 155 finished with value: 0.9488613064709025 and parameters: {'weight_class_0': 0.4747125902117412, 'weight_class_1': 3.677999559014465, 'weight_class_2': 3.2570874572513633}. Best is trial 116 with value: 0.9496287604146522.
[I 2026-07-05 15:22:37,995] Trial 157 finished with value: 0.9491838810407714 and parameters: {'weight_class_0': 0.3460464868182244, 'weight_class_1': 2.8102586031442014, 'weight_class_2': 4.58156501351043}. Best is trial 116 with value: 0.9496287604146522.
[I 2026-07-05 15:22:37,997] Trial 156 finished with value: 0.9485132301447368 and parameters: {'weight_class_0': 0.4868151945214486, 'weight_class_1': 3.3374266035007714, 'weight_class_2': 3.205943854313723}. Best is trial 116 with value: 0.9496287604146522.
[I 2026-07-05 15:22:38,034] Trial 158 finished with value: 0.9495622070547807 and parameters: {'weight_class_0': 0.33396543109044974, 'weight_class_1': 5.419468445099858, 'weight_class_2': 3.429596271376264}. Best is trial 116 with value: 0.9496287604146522.
[I 2026-07-05 15:22:38,051] Trial 159 finished with value: 0.9495836029063439 and parameters: {'weight_class_0': 0.3465015916973155, 'weight_class_1': 6.812152242364441, 'weight_class_2': 3.248456616758582}. Best is trial 116 with value: 0.9496287604146522.
[I 2026-07-05 15:22:38,055] Trial 160 finished with value: 0.9496355517944334 and parameters: {'weight_class_0': 0.3501060841672395, 'weight_class_1': 6.652575505659467, 'weight_class_2': 3.3090363016910675}. Best is trial 160 with value: 0.9496355517944334.
[I 2026-07-05 15:22:38,082] Trial 161 finished with value: 0.9496041188094683 and parameters: {'weight_class_0': 0.3428583759822708, 'weight_class_1': 6.527908431126895, 'weight_class_2': 4.139342252234439}. Best is trial 160 with value: 0.9496355517944334.
[I 2026-07-05 15:22:38,103] Trial 162 finished with value: 0.9495890729769099 and parameters: {'weight_class_0': 0.3772898122913974, 'weight_class_1': 6.543236350497604, 'weight_class_2': 4.408920211432828}. Best is trial 160 with value: 0.9496355517944334.
[I 2026-07-05 15:22:38,109] Trial 163 finished with value: 0.9495580388521739 and parameters: {'weight_class_0': 0.35263497407788186, 'weight_class_1': 6.28620912159556, 'weight_class_2': 4.394055114220899}. Best is trial 160 with value: 0.9496355517944334.
[I 2026-07-05 15:22:38,121] Trial 164 finished with value: 0.9495382454428024 and parameters: {'weight_class_0': 0.35339136000393556, 'weight_class_1': 6.952165168259858, 'weight_class_2': 4.345312041357959}. Best is trial 160 with value: 0.9496355517944334.
[I 2026-07-05 15:22:38,151] Trial 165 finished with value: 0.9495662971185977 and parameters: {'weight_class_0': 0.3560701608898102, 'weight_class_1': 6.5462100913017345, 'weight_class_2': 4.4367014892138785}. Best is trial 160 with value: 0.9496355517944334.
[I 2026-07-05 15:22:38,172] Trial 166 finished with value: 0.9495437924185981 and parameters: {'weight_class_0': 0.33671866081573887, 'weight_class_1': 6.617020116492019, 'weight_class_2': 4.258418625839985}. Best is trial 160 with value: 0.9496355517944334.

[I 2026-07-05 15:22:38,177] Trial 167 finished with value: 0.949644702554342 and parameters: {'weight_class_0': 0.35894232704688783, 'weight_class_1': 5.343748167679158, 'weight_class_2': 4.2132842120097305}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:38,204] Trial 168 finished with value: 0.9485902385543726 and parameters: {'weight_class_0': 0.3505846774585316, 'weight_class_1': 6.912465023533582, 'weight_class_2': 2.013492220394041}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:38,221] Trial 169 finished with value: 0.9486215757701316 and parameters: {'weight_class_0': 0.3299377754613213, 'weight_class_1': 6.979818549030417, 'weight_class_2': 1.972529616564845}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:38,232] Trial 170 finished with value: 0.9496286209239048 and parameters: {'weight_class_0': 0.3374814411162696, 'weight_class_1': 5.434375118380489, 'weight_class_2': 4.030231503054001}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:38,264] Trial 172 finished with value: 0.9487505001003363 and parameters: {'weight_class_0': 0.3182942828289306, 'weight_class_1': 5.454928580443175, 'weight_class_2': 1.9081841340814738}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:38,269] Trial 171 finished with value: 0.9487506278640243 and parameters: {'weight_class_0': 0.3543258010638856, 'weight_class_1': 6.444885561164458, 'weight_class_2': 2.087939899072749}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:38,291] Trial 173 finished with value: 0.9495757723595354 and parameters: {'weight_class_0': 0.3377041099189033, 'weight_class_1': 5.131329556318417, 'weight_class_2': 4.206951577544742}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:38,324] Trial 175 finished with value: 0.9495237857763389 and parameters: {'weight_class_0': 0.2629830053160125, 'weight_class_1': 5.216239814634306, 'weight_class_2': 2.1103581727009177}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:38,334] Trial 174 finished with value: 0.9492536756863273 and parameters: {'weight_class_0': 0.19658243253463806, 'weight_class_1': 5.30557659486795, 'weight_class_2': 1.8403823043777805}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:38,348] Trial 176 finished with value: 0.9493330423892141 and parameters: {'weight_class_0': 0.18619090483137538, 'weight_class_1': 5.106361134250894, 'weight_class_2': 2.092497640209265}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:38,366] Trial 177 finished with value: 0.9492342891664262 and parameters: {'weight_class_0': 0.18262992797885, 'weight_class_1': 5.119941658916916, 'weight_class_2': 2.2813989543393176}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:38,392] Trial 178 finished with value: 0.949268651915141 and parameters: {'weight_class_0': 0.1860255602177746, 'weight_class_1': 5.1249300535045315, 'weight_class_2': 2.3795911220763535}. Best is trial 167 with value: 0.949644702554342.

Best trial: 167. Best value: 0.949645:   6%|████████▎                                                                                                                           | 190/3000 [00:03<00:50, 55.19it/s]

[I 2026-07-05 15:22:38,406] Trial 179 finished with value: 0.9491416465724732 and parameters: {'weight_class_0': 0.17773341548315474, 'weight_class_1': 5.258333118427803, 'weight_class_2': 2.4364380047729974}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:38,436] Trial 181 finished with value: 0.949560480963224 and parameters: {'weight_class_0': 0.25953315315626396, 'weight_class_1': 4.945608652088474, 'weight_class_2': 2.803208623536392}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:38,443] Trial 180 finished with value: 0.9492943370564731 and parameters: {'weight_class_0': 0.1919893598481931, 'weight_class_1': 5.003978062875222, 'weight_class_2': 2.5801025686229946}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:38,474] Trial 183 finished with value: 0.9493789812549016 and parameters: {'weight_class_0': 0.19999357738919493, 'weight_class_1': 4.571116485840887, 'weight_class_2': 2.6966495046827}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:38,479] Trial 182 finished with value: 0.9492507243144123 and parameters: {'weight_class_0': 0.1973301867013944, 'weight_class_1': 4.7394293585006055, 'weight_class_2': 2.7573031502894145}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:38,499] Trial 184 finished with value: 0.9490681633005549 and parameters: {'weight_class_0': 0.262279692640152, 'weight_class_1': 7.818360602943202, 'weight_class_2': 3.787521351679519}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:38,521] Trial 186 finished with value: 0.9492437379335122 and parameters: {'weight_class_0': 0.2857113923965885, 'weight_class_1': 7.673012159729597, 'weight_class_2': 3.9048134742504463}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:38,522] Trial 185 finished with value: 0.9496430844194426 and parameters: {'weight_class_0': 0.2541721893867872, 'weight_class_1': 2.868655110803675, 'weight_class_2': 2.909376680681145}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:38,564] Trial 188 finished with value: 0.9488701315722706 and parameters: {'weight_class_0': 0.24987591393845074, 'weight_class_1': 7.8458833608182, 'weight_class_2': 3.959703576024234}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:38,572] Trial 187 finished with value: 0.9492541891989599 and parameters: {'weight_class_0': 0.2708190540678986, 'weight_class_1': 2.9156197118526945, 'weight_class_2': 3.9373368351440874}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:38,587] Trial 189 finished with value: 0.9489926425860903 and parameters: {'weight_class_0': 0.25977646192505766, 'weight_class_1': 7.839457508111997, 'weight_class_2': 3.9419462783671784}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:38,604] Trial 190 finished with value: 0.9496057391981804 and parameters: {'weight_class_0': 0.3947478150196724, 'weight_class_1': 7.811494021635542, 'weight_class_2': 3.8689624742043747}. Best is trial 167 with value: 0.949644702554342.

Best trial: 167. Best value: 0.949645:   7%|████████▊                                                                                                                           | 199/3000 [00:03<00:52, 53.56it/s]

[I 2026-07-05 15:22:38,624] Trial 191 finished with value: 0.9491210699013252 and parameters: {'weight_class_0': 0.2803787777755007, 'weight_class_1': 8.017639949597214, 'weight_class_2': 3.931477039635571}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:38,648] Trial 192 finished with value: 0.9490376211203801 and parameters: {'weight_class_0': 0.4165345737422804, 'weight_class_1': 2.7887768730345135, 'weight_class_2': 3.890539524430374}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:38,659] Trial 194 finished with value: 0.9490381075105949 and parameters: {'weight_class_0': 0.4040726937085733, 'weight_class_1': 2.7680613707329917, 'weight_class_2': 3.271046480886885}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:38,675] Trial 193 finished with value: 0.9493259253382652 and parameters: {'weight_class_0': 0.37343320217436093, 'weight_class_1': 2.9078955994918263, 'weight_class_2': 3.203792235983491}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:38,726] Trial 195 finished with value: 0.9490291990813992 and parameters: {'weight_class_0': 0.4099559186089652, 'weight_class_1': 2.7820025397708403, 'weight_class_2': 3.307976056340475}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:38,737] Trial 196 finished with value: 0.9491919670893578 and parameters: {'weight_class_0': 0.40201108950219305, 'weight_class_1': 2.84460307647685, 'weight_class_2': 3.3292549509010856}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:38,745] Trial 197 finished with value: 0.7246251391998829 and parameters: {'weight_class_0': 0.3846520735304448, 'weight_class_1': 0.002840844719817769, 'weight_class_2': 3.2884471266653117}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:38,757] Trial 198 finished with value: 0.9496380242499004 and parameters: {'weight_class_0': 0.3870727548671718, 'weight_class_1': 6.193972629763129, 'weight_class_2': 3.1721770051050266}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:38,797] Trial 199 finished with value: 0.658758118208591 and parameters: {'weight_class_0': 0.39912098810559715, 'weight_class_1': 0.001147847823610654, 'weight_class_2': 3.234454442349936}. Best is trial 167 with value: 0.949644702554342.

[I 2026-07-05 15:22:38,826] Trial 200 finished with value: 0.9493130943619716 and parameters: {'weight_class_0': 0.4148207479659219, 'weight_class_1': 4.215273592520073, 'weight_class_2': 3.147103154546694}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:38,845] Trial 202 finished with value: 0.9494853912708995 and parameters: {'weight_class_0': 0.39186690545471403, 'weight_class_1': 4.3155218392239725, 'weight_class_2': 5.090660311119085}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:38,868] Trial 201 finished with value: 0.9494988739490533 and parameters: {'weight_class_0': 0.3864892784904798, 'weight_class_1': 4.174279697821975, 'weight_class_2': 4.842153863267777}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:38,878] Trial 203 finished with value: 0.6572649025155576 and parameters: {'weight_class_0': 0.0015307346668894791, 'weight_class_1': 4.168805073346963, 'weight_class_2': 5.033005429042896}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:38,879] Trial 204 finished with value: 0.9494451790928916 and parameters: {'weight_class_0': 0.38908175819079177, 'weight_class_1': 4.081707211684515, 'weight_class_2': 4.980976581275743}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:38,916] Trial 205 finished with value: 0.9491566020791957 and parameters: {'weight_class_0': 0.5901947875410924, 'weight_class_1': 4.1258570616405645, 'weight_class_2': 5.035708492123289}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:38,934] Trial 207 finished with value: 0.9492234251374807 and parameters: {'weight_class_0': 0.5908730713899019, 'weight_class_1': 4.1915589605085115, 'weight_class_2': 5.004240884867061}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:38,939] Trial 206 finished with value: 0.9492819645505461 and parameters: {'weight_class_0': 0.31662801821478487, 'weight_class_1': 4.123070034991396, 'weight_class_2': 5.215419146032693}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:38,976] Trial 209 finished with value: 0.9492953735946742 and parameters: {'weight_class_0': 0.31146154257045655, 'weight_class_1': 6.0961488345899175, 'weight_class_2': 4.962349556969411}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:38,977] Trial 208 finished with value: 0.9480329562101909 and parameters: {'weight_class_0': 0.7522667337349916, 'weight_class_1': 4.272128620208568, 'weight_class_2': 4.975037561951332}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:39,003] Trial 210 finished with value: 0.9493113415296648 and parameters: {'weight_class_0': 0.3132983752048592, 'weight_class_1': 6.214695841058258, 'weight_class_2': 4.902696580822035}. Best is trial 167 with value: 0.949644702554342.

Best trial: 167. Best value: 0.949645:   7%|█████████▋                                                                                                                          | 221/3000 [00:04<00:53, 51.53it/s]

[I 2026-07-05 15:22:39,010] Trial 211 finished with value: 0.9487984869927657 and parameters: {'weight_class_0': 0.31362709733222055, 'weight_class_1': 6.167298995983543, 'weight_class_2': 6.509516072179816}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:39,051] Trial 212 finished with value: 0.9489594818879633 and parameters: {'weight_class_0': 0.32650778395836016, 'weight_class_1': 6.382790394163329, 'weight_class_2': 6.244178951637655}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:39,070] Trial 213 finished with value: 0.9487296803493798 and parameters: {'weight_class_0': 0.29666645132614916, 'weight_class_1': 5.979003176252496, 'weight_class_2': 6.318872764506062}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:39,086] Trial 214 finished with value: 0.9494686935816968 and parameters: {'weight_class_0': 0.7371553221646885, 'weight_class_1': 6.354014782372885, 'weight_class_2': 6.1939854044505465}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:39,118] Trial 215 finished with value: 0.949422797622891 and parameters: {'weight_class_0': 0.7614174436907053, 'weight_class_1': 6.232842712932541, 'weight_class_2': 6.5850095046770445}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:39,134] Trial 216 finished with value: 0.9485510882045282 and parameters: {'weight_class_0': 0.29133298360268506, 'weight_class_1': 6.324007090686658, 'weight_class_2': 6.75153853297206}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:39,147] Trial 217 finished with value: 0.9489486322791311 and parameters: {'weight_class_0': 0.30555762112850904, 'weight_class_1': 6.190461703541394, 'weight_class_2': 5.978688274413488}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:39,181] Trial 219 finished with value: 0.949047507361784 and parameters: {'weight_class_0': 0.5665916066078718, 'weight_class_1': 5.920656514788211, 'weight_class_2': 3.965701606292079}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:39,185] Trial 218 finished with value: 0.949588853396632 and parameters: {'weight_class_0': 0.49973327865833267, 'weight_class_1': 6.37285830664881, 'weight_class_2': 6.545921092362445}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:39,203] Trial 220 finished with value: 0.7715614615068981 and parameters: {'weight_class_0': 0.5522643161545928, 'weight_class_1': 6.022467561241893, 'weight_class_2': 0.008287379161962599}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:39,222] Trial 221 finished with value: 0.6941302450279849 and parameters: {'weight_class_0': 0.5486710933064453, 'weight_class_1': 7.590245835658763, 'weight_class_2': 0.0028639895208826087}. Best is trial 167 with value: 0.949644702554342.

[I 2026-07-05 15:22:39,244] Trial 222 finished with value: 0.9494275538395366 and parameters: {'weight_class_0': 0.5803400631372427, 'weight_class_1': 8.319110590742447, 'weight_class_2': 4.3628778271492346}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:39,271] Trial 223 finished with value: 0.9492989111688575 and parameters: {'weight_class_0': 0.5701468031169822, 'weight_class_1': 7.647700141330049, 'weight_class_2': 4.090172784665881}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:39,292] Trial 224 finished with value: 0.9495007083896994 and parameters: {'weight_class_0': 0.5411649187426147, 'weight_class_1': 8.109674043795042, 'weight_class_2': 4.222764598708276}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:39,316] Trial 225 finished with value: 0.9493094246516524 and parameters: {'weight_class_0': 0.5778671514870731, 'weight_class_1': 7.330940290740659, 'weight_class_2': 4.175334477239117}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:39,336] Trial 226 finished with value: 0.9495350591106786 and parameters: {'weight_class_0': 0.54329880335026, 'weight_class_1': 7.798476501565093, 'weight_class_2': 4.274394460105419}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:39,347] Trial 227 finished with value: 0.9485230954874423 and parameters: {'weight_class_0': 0.23486046645578726, 'weight_class_1': 8.24329199601499, 'weight_class_2': 4.072811584782278}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:39,373] Trial 228 finished with value: 0.9484777823463283 and parameters: {'weight_class_0': 0.22620989629585264, 'weight_class_1': 8.114420023059283, 'weight_class_2': 3.874078534279869}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:39,400] Trial 230 finished with value: 0.9484892082116897 and parameters: {'weight_class_0': 0.22958787597855998, 'weight_class_1': 7.730631838726181, 'weight_class_2': 4.1310671533447465}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:39,407] Trial 229 finished with value: 0.9495521488315832 and parameters: {'weight_class_0': 0.44921348351324397, 'weight_class_1': 7.769879425091556, 'weight_class_2': 4.3119831668275586}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:39,430] Trial 231 finished with value: 0.9489292174543871 and parameters: {'weight_class_0': 0.4502487463520031, 'weight_class_1': 7.439864367671303, 'weight_class_2': 2.826715403460534}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:39,440] Trial 232 finished with value: 0.949509600962085 and parameters: {'weight_class_0': 0.23402512194385947, 'weight_class_1': 5.18733391604549, 'weight_class_2': 2.7504935585065917}. Best is trial 167 with value: 0.949644702554342.

Best trial: 167. Best value: 0.949645:   8%|██████████▋                                                                                                                         | 242/3000 [00:04<00:55, 49.57it/s]

[I 2026-07-05 15:22:39,482] Trial 234 finished with value: 0.9494915383294953 and parameters: {'weight_class_0': 0.23864545674234713, 'weight_class_1': 5.1562012778286155, 'weight_class_2': 2.8396056042726894}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:39,483] Trial 233 finished with value: 0.9493965471809114 and parameters: {'weight_class_0': 0.22850693974334857, 'weight_class_1': 5.5712689476735475, 'weight_class_2': 2.7089984589872422}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:39,512] Trial 236 finished with value: 0.948967406664424 and parameters: {'weight_class_0': 0.44599775939689673, 'weight_class_1': 5.170142270525853, 'weight_class_2': 2.89087442641766}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:39,538] Trial 235 finished with value: 0.9488351882669246 and parameters: {'weight_class_0': 0.4430127864601306, 'weight_class_1': 4.882143614613668, 'weight_class_2': 2.7308016525376018}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:39,557] Trial 237 finished with value: 0.9496223558722168 and parameters: {'weight_class_0': 0.35537153301322094, 'weight_class_1': 5.156111269457541, 'weight_class_2': 3.276200530925385}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:39,570] Trial 238 finished with value: 0.9489190667027371 and parameters: {'weight_class_0': 0.44497315515397623, 'weight_class_1': 5.111423677761601, 'weight_class_2': 2.7939213145138777}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:39,584] Trial 239 finished with value: 0.9489694071396194 and parameters: {'weight_class_0': 0.4473181763680952, 'weight_class_1': 5.6682273679309505, 'weight_class_2': 2.786428652721711}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:39,606] Trial 240 finished with value: 0.9496062864133373 and parameters: {'weight_class_0': 0.35640327979059966, 'weight_class_1': 5.243400891360564, 'weight_class_2': 2.9323051156318574}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:39,649] Trial 242 finished with value: 0.949641742988618 and parameters: {'weight_class_0': 0.3536887538897697, 'weight_class_1': 5.050315427587985, 'weight_class_2': 3.3387033444481444}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:39,659] Trial 241 finished with value: 0.9496191575538487 and parameters: {'weight_class_0': 0.3542457928349375, 'weight_class_1': 4.957365041684282, 'weight_class_2': 3.3530237422051403}. Best is trial 167 with value: 0.949644702554342.

Best trial: 255. Best value: 0.949675:   8%|███████████▏                                                                                                                        | 253/3000 [00:04<00:55, 49.71it/s]

[I 2026-07-05 15:22:39,684] Trial 244 finished with value: 0.9496016221827016 and parameters: {'weight_class_0': 0.35285081180877287, 'weight_class_1': 5.151146964614371, 'weight_class_2': 3.2365449168067637}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:39,688] Trial 243 finished with value: 0.9467167035624628 and parameters: {'weight_class_0': 0.356450413262236, 'weight_class_1': 4.9516012647226, 'weight_class_2': 1.4108380994067582}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:39,719] Trial 245 finished with value: 0.9496232024723991 and parameters: {'weight_class_0': 0.37108466042294713, 'weight_class_1': 4.836952474516779, 'weight_class_2': 3.298392180127437}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:39,732] Trial 246 finished with value: 0.9495223819356055 and parameters: {'weight_class_0': 0.33888703305045936, 'weight_class_1': 5.748894775908267, 'weight_class_2': 3.531613846919338}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:39,754] Trial 247 finished with value: 0.9495199828545134 and parameters: {'weight_class_0': 0.36294819518952415, 'weight_class_1': 3.515907564908638, 'weight_class_2': 3.406092960186448}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:39,769] Trial 248 finished with value: 0.9494474594670376 and parameters: {'weight_class_0': 0.36094401272109367, 'weight_class_1': 3.2404342934310515, 'weight_class_2': 3.6152477933126477}. Best is trial 167 with value: 0.949644702554342.
[I 2026-07-05 15:22:39,786] Trial 249 finished with value: 0.9496472962866714 and parameters: {'weight_class_0': 0.35387871596126674, 'weight_class_1': 4.727975945569554, 'weight_class_2': 3.292496722161458}. Best is trial 249 with value: 0.9496472962866714.
[I 2026-07-05 15:22:39,822] Trial 250 finished with value: 0.9494859479718692 and parameters: {'weight_class_0': 0.35347049342648085, 'weight_class_1': 3.245987071721574, 'weight_class_2': 3.357260062787835}. Best is trial 249 with value: 0.9496472962866714.
[I 2026-07-05 15:22:39,825] Trial 251 finished with value: 0.9469290962962006 and parameters: {'weight_class_0': 0.3506647743172256, 'weight_class_1': 4.256600790140699, 'weight_class_2': 1.4399096606364403}. Best is trial 249 with value: 0.9496472962866714.
[I 2026-07-05 15:22:39,859] Trial 253 finished with value: 0.9495503152669021 and parameters: {'weight_class_0': 0.35613997999432767, 'weight_class_1': 3.6682386332416357, 'weight_class_2': 3.3183407972917274}. Best is trial 249 with value: 0.9496472962866714.
[I 2026-07-05 15:22:39,864] Trial 252 finished with value: 0.9494651916172968 and parameters: {'weight_class_0': 0.35617048099923665, 'weight_class_1': 3.33879098418478, 'weight_class_2': 3.4094116184796737}. Best is trial 249 with value: 0.9496472962866714.

Best trial: 255. Best value: 0.949675:   9%|███████████▌                                                                                                                        | 263/3000 [00:05<00:55, 49.50it/s]

[I 2026-07-05 15:22:39,889] Trial 254 finished with value: 0.9494819812746252 and parameters: {'weight_class_0': 0.33663370226740374, 'weight_class_1': 3.319645652141018, 'weight_class_2': 3.387054355606912}. Best is trial 249 with value: 0.9496472962866714.
[I 2026-07-05 15:22:39,916] Trial 255 finished with value: 0.9496751209701936 and parameters: {'weight_class_0': 0.2908138988540639, 'weight_class_1': 3.4316479508858024, 'weight_class_2': 3.289313971994737}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:39,933] Trial 256 finished with value: 0.9496140546245743 and parameters: {'weight_class_0': 0.2821369662115588, 'weight_class_1': 4.3863596041992805, 'weight_class_2': 2.4608255726751285}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:39,945] Trial 257 finished with value: 0.9496050450416508 and parameters: {'weight_class_0': 0.29333934286721874, 'weight_class_1': 4.420856659957397, 'weight_class_2': 2.410740317817492}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:39,983] Trial 258 finished with value: 0.9495953491717232 and parameters: {'weight_class_0': 0.29335198336242385, 'weight_class_1': 4.530383414469538, 'weight_class_2': 2.4358573457287296}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:39,988] Trial 259 finished with value: 0.9496226292766282 and parameters: {'weight_class_0': 0.2778116365723156, 'weight_class_1': 4.478899284498959, 'weight_class_2': 2.306139737528201}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,030] Trial 260 finished with value: 0.9487756869110878 and parameters: {'weight_class_0': 0.28912195466747154, 'weight_class_1': 9.99738988152179, 'weight_class_2': 2.3399027452044994}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,035] Trial 261 finished with value: 0.9496571429270458 and parameters: {'weight_class_0': 0.26849733817110527, 'weight_class_1': 4.269104589855999, 'weight_class_2': 2.319793249846044}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,063] Trial 262 finished with value: 0.9496459401708259 and parameters: {'weight_class_0': 0.2753951722271312, 'weight_class_1': 4.709946439439516, 'weight_class_2': 2.3454193033109156}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,077] Trial 263 finished with value: 0.9493106120964087 and parameters: {'weight_class_0': 0.2956665337369165, 'weight_class_1': 4.603719944217561, 'weight_class_2': 2.1687632988433783}. Best is trial 255 with value: 0.9496751209701936.

Best trial: 255. Best value: 0.949675:   9%|████████████                                                                                                                        | 274/3000 [00:05<00:53, 50.64it/s]

[I 2026-07-05 15:22:40,115] Trial 265 finished with value: 0.9492181381069215 and parameters: {'weight_class_0': 0.278522892597408, 'weight_class_1': 2.1590474445317396, 'weight_class_2': 2.2269982445019525}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,117] Trial 264 finished with value: 0.9495890802986747 and parameters: {'weight_class_0': 0.2889994636377614, 'weight_class_1': 4.380018397144931, 'weight_class_2': 2.4858629537140717}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,134] Trial 266 finished with value: 0.949477278118184 and parameters: {'weight_class_0': 0.2699611413080926, 'weight_class_1': 2.283003123427422, 'weight_class_2': 2.286678051368772}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,165] Trial 267 finished with value: 0.949430256277025 and parameters: {'weight_class_0': 0.2428048889068268, 'weight_class_1': 2.2159094810632736, 'weight_class_2': 2.4394104778291745}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,174] Trial 268 finished with value: 0.9495803010235809 and parameters: {'weight_class_0': 0.27210749438789766, 'weight_class_1': 4.422271989855151, 'weight_class_2': 2.420769779315269}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,205] Trial 269 finished with value: 0.9490279619032252 and parameters: {'weight_class_0': 0.26111142621947575, 'weight_class_1': 4.3407451451977375, 'weight_class_2': 1.7087432306086354}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,214] Trial 270 finished with value: 0.9492386982296767 and parameters: {'weight_class_0': 0.2732410922368786, 'weight_class_1': 2.1366018290498814, 'weight_class_2': 2.186776217659424}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,254] Trial 271 finished with value: 0.9490157269190158 and parameters: {'weight_class_0': 0.2746966921873659, 'weight_class_1': 4.222992660579254, 'weight_class_2': 1.792063382506269}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,268] Trial 272 finished with value: 0.9489428735583402 and parameters: {'weight_class_0': 0.26737803979474084, 'weight_class_1': 2.320780890939, 'weight_class_2': 1.7975012995652826}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,281] Trial 273 finished with value: 0.9491027268423039 and parameters: {'weight_class_0': 0.25219054071172015, 'weight_class_1': 4.541112179061914, 'weight_class_2': 1.7072109520334087}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,289] Trial 274 finished with value: 0.9493521557923484 and parameters: {'weight_class_0': 0.2417610449818919, 'weight_class_1': 4.23655788624552, 'weight_class_2': 1.8089567414393573}. Best is trial 255 with value: 0.9496751209701936.

Best trial: 255. Best value: 0.949675:  10%|████████████▌                                                                                                                       | 285/3000 [00:05<00:55, 48.54it/s]

[I 2026-07-05 15:22:40,343] Trial 275 finished with value: 0.9495476895782552 and parameters: {'weight_class_0': 0.206688950192173, 'weight_class_1': 4.193580301612184, 'weight_class_2': 1.7042037394388518}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,355] Trial 276 finished with value: 0.9495875734456941 and parameters: {'weight_class_0': 0.2070073348221228, 'weight_class_1': 4.186230037552382, 'weight_class_2': 1.7498337104464703}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,365] Trial 277 finished with value: 0.9494453678065896 and parameters: {'weight_class_0': 0.21106738289233398, 'weight_class_1': 4.227688773893038, 'weight_class_2': 1.6468607602719434}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,398] Trial 278 finished with value: 0.9496135981724425 and parameters: {'weight_class_0': 0.21716356946162985, 'weight_class_1': 4.104487019244092, 'weight_class_2': 2.1187637864596502}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,407] Trial 279 finished with value: 0.9495991966659222 and parameters: {'weight_class_0': 0.21522744625023646, 'weight_class_1': 4.135506186140378, 'weight_class_2': 1.7706210812059548}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,433] Trial 280 finished with value: 0.9495912042842654 and parameters: {'weight_class_0': 0.16895232553501188, 'weight_class_1': 3.000765368978123, 'weight_class_2': 1.5220774939064563}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,468] Trial 282 finished with value: 0.9492364896696669 and parameters: {'weight_class_0': 0.15874726696786107, 'weight_class_1': 3.5898955131479844, 'weight_class_2': 2.393828060559942}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,470] Trial 281 finished with value: 0.9493807035376639 and parameters: {'weight_class_0': 0.17314528479446875, 'weight_class_1': 3.9764503326119622, 'weight_class_2': 2.3451717466965416}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,492] Trial 283 finished with value: 0.9493719377502045 and parameters: {'weight_class_0': 0.15592589311358213, 'weight_class_1': 3.117838397178011, 'weight_class_2': 2.3662071011552768}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,508] Trial 284 finished with value: 0.949297563061973 and parameters: {'weight_class_0': 0.15343179927255432, 'weight_class_1': 3.169094347085396, 'weight_class_2': 2.3894705681350312}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,524] Trial 285 finished with value: 0.8809204509353842 and parameters: {'weight_class_0': 0.1461831676991881, 'weight_class_1': 0.02546235279121999, 'weight_class_2': 2.922029937743708}. Best is trial 255 with value: 0.9496751209701936.

Best trial: 255. Best value: 0.949675:  10%|█████████████                                                                                                                       | 297/3000 [00:05<00:55, 49.01it/s]

[I 2026-07-05 15:22:40,526] Trial 286 finished with value: 0.9493390829080349 and parameters: {'weight_class_0': 0.16676169329379614, 'weight_class_1': 3.583703483186558, 'weight_class_2': 2.433562748843782}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,598] Trial 287 finished with value: 0.9495441411481252 and parameters: {'weight_class_0': 0.16408840245258827, 'weight_class_1': 3.1184799840719784, 'weight_class_2': 2.147149132729032}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,613] Trial 288 finished with value: 0.9492249994123351 and parameters: {'weight_class_0': 0.13598218130329875, 'weight_class_1': 3.025502904817192, 'weight_class_2': 2.0814226531611726}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,616] Trial 289 finished with value: 0.947620909184368 and parameters: {'weight_class_0': 0.4207230327011321, 'weight_class_1': 3.128570682697211, 'weight_class_2': 2.0423420923793714}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,626] Trial 290 finished with value: 0.9493296552843361 and parameters: {'weight_class_0': 0.12343138110397982, 'weight_class_1': 3.2429406525357187, 'weight_class_2': 1.3447896118648919}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,647] Trial 291 finished with value: 0.9489364026736595 and parameters: {'weight_class_0': 0.395119730423548, 'weight_class_1': 2.9507369550258784, 'weight_class_2': 2.886978592428798}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,691] Trial 292 finished with value: 0.9438236566792093 and parameters: {'weight_class_0': 0.4209896698419088, 'weight_class_1': 2.603012420787159, 'weight_class_2': 1.3770433265284594}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,702] Trial 293 finished with value: 0.9450066948881064 and parameters: {'weight_class_0': 0.3784629529906188, 'weight_class_1': 5.095613339088044, 'weight_class_2': 1.2621089111429011}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,713] Trial 294 finished with value: 0.9496213696244333 and parameters: {'weight_class_0': 0.3693697283166969, 'weight_class_1': 4.992620830047593, 'weight_class_2': 3.049555954833359}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,727] Trial 295 finished with value: 0.9439498820284434 and parameters: {'weight_class_0': 0.4275589224134707, 'weight_class_1': 5.168107953539678, 'weight_class_2': 1.3041644642158403}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,750] Trial 297 finished with value: 0.9427175096507853 and parameters: {'weight_class_0': 0.43493205712318733, 'weight_class_1': 2.6871966567165204, 'weight_class_2': 1.303945144131519}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,761] Trial 296 finished with value: 0.9493399130621555 and parameters: {'weight_class_0': 0.40853583993572073, 'weight_class_1': 5.016173061870974, 'weight_class_2': 3.0095885299509737}. Best is trial 255 with value: 0.9496751209701936.

Best trial: 255. Best value: 0.949675:  10%|█████████████▌                                                                                                                      | 308/3000 [00:05<00:52, 51.45it/s]

[I 2026-07-05 15:22:40,787] Trial 299 finished with value: 0.9495746458189113 and parameters: {'weight_class_0': 0.3105238326863619, 'weight_class_1': 5.081937859940294, 'weight_class_2': 2.9007687957397903}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,798] Trial 298 finished with value: 0.9494186113960993 and parameters: {'weight_class_0': 0.39767485721385537, 'weight_class_1': 5.078506438121394, 'weight_class_2': 3.023214811836895}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,832] Trial 301 finished with value: 0.9495351753403343 and parameters: {'weight_class_0': 0.30252092167025496, 'weight_class_1': 5.01915385721229, 'weight_class_2': 3.0661199775917645}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,850] Trial 300 finished with value: 0.9495874441762294 and parameters: {'weight_class_0': 0.30899871248436905, 'weight_class_1': 5.020780872918697, 'weight_class_2': 3.310909168103416}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,854] Trial 302 finished with value: 0.9495963975653782 and parameters: {'weight_class_0': 0.3143733689478268, 'weight_class_1': 5.088762519650363, 'weight_class_2': 3.0608081002783387}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,902] Trial 303 finished with value: 0.9495499265064042 and parameters: {'weight_class_0': 0.32177839240195055, 'weight_class_1': 6.487379848468646, 'weight_class_2': 3.0885508780344484}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,917] Trial 305 finished with value: 0.9495573330018967 and parameters: {'weight_class_0': 0.3075872856560861, 'weight_class_1': 6.572316074398063, 'weight_class_2': 3.42817492249987}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,920] Trial 304 finished with value: 0.9495570823779054 and parameters: {'weight_class_0': 0.32406879139826833, 'weight_class_1': 6.7025147605261814, 'weight_class_2': 3.0510575676101865}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,962] Trial 307 finished with value: 0.9495252475588559 and parameters: {'weight_class_0': 0.32567271230209494, 'weight_class_1': 6.851750833123262, 'weight_class_2': 3.404418983125699}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:40,970] Trial 306 finished with value: 0.9495592710923156 and parameters: {'weight_class_0': 0.3322274000056677, 'weight_class_1': 6.519364332589515, 'weight_class_2': 3.4642880668296625}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,001] Trial 309 finished with value: 0.9495483174668765 and parameters: {'weight_class_0': 0.30761243698123414, 'weight_class_1': 6.7773443074054684, 'weight_class_2': 3.571796143711709}. Best is trial 255 with value: 0.9496751209701936.

Best trial: 255. Best value: 0.949675:  11%|██████████████                                                                                                                      | 319/3000 [00:06<00:52, 50.82it/s]

[I 2026-07-05 15:22:41,003] Trial 308 finished with value: 0.9495207337569654 and parameters: {'weight_class_0': 0.30316467057634616, 'weight_class_1': 6.733022600698208, 'weight_class_2': 3.423753319239538}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,035] Trial 310 finished with value: 0.9489808449844427 and parameters: {'weight_class_0': 0.23523320348756382, 'weight_class_1': 6.667714434202672, 'weight_class_2': 3.6822113919191706}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,037] Trial 312 finished with value: 0.6869586104657109 and parameters: {'weight_class_0': 0.23730408216801785, 'weight_class_1': 6.594828887981527, 'weight_class_2': 0.001013140744741045}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,049] Trial 311 finished with value: 0.9495694960870577 and parameters: {'weight_class_0': 0.31805908150867235, 'weight_class_1': 6.620270944223653, 'weight_class_2': 3.4880485628495372}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,077] Trial 313 finished with value: 0.9488399396298565 and parameters: {'weight_class_0': 0.22728682793190436, 'weight_class_1': 6.619195734265925, 'weight_class_2': 3.827903355733826}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,100] Trial 314 finished with value: 0.9490702967671059 and parameters: {'weight_class_0': 0.23373107246913696, 'weight_class_1': 6.037379140462177, 'weight_class_2': 3.6474286569134917}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,125] Trial 315 finished with value: 0.6940203905777186 and parameters: {'weight_class_0': 0.22995500571686975, 'weight_class_1': 6.38719529453394, 'weight_class_2': 0.001500479568776585}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,149] Trial 316 finished with value: 0.9492894243687552 and parameters: {'weight_class_0': 0.23731567365616119, 'weight_class_1': 3.547654963615563, 'weight_class_2': 3.7794230090261185}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,165] Trial 317 finished with value: 0.9493228515968886 and parameters: {'weight_class_0': 0.23771572669509516, 'weight_class_1': 3.6817862340992504, 'weight_class_2': 3.706259588219518}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,186] Trial 318 finished with value: 0.9490244134812748 and parameters: {'weight_class_0': 0.22268479999667598, 'weight_class_1': 3.7823599972082094, 'weight_class_2': 3.958968868337152}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,193] Trial 319 finished with value: 0.9492579902733068 and parameters: {'weight_class_0': 0.24537268235175794, 'weight_class_1': 3.8971125936799242, 'weight_class_2': 4.061282317453188}. Best is trial 255 with value: 0.9496751209701936.

Best trial: 255. Best value: 0.949675:  11%|██████████████▌                                                                                                                     | 330/3000 [00:06<00:52, 51.19it/s]

[I 2026-07-05 15:22:41,225] Trial 320 finished with value: 0.9494582834243915 and parameters: {'weight_class_0': 0.437270339933815, 'weight_class_1': 3.7636933501371166, 'weight_class_2': 4.048496237503957}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,235] Trial 321 finished with value: 0.947236633115878 and parameters: {'weight_class_0': 0.45694308503487197, 'weight_class_1': 3.8284846054472865, 'weight_class_2': 2.025940474594948}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,255] Trial 322 finished with value: 0.948479287050223 and parameters: {'weight_class_0': 0.4545196715350293, 'weight_class_1': 3.765800128480389, 'weight_class_2': 2.6298031389889314}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,287] Trial 323 finished with value: 0.9484734093865034 and parameters: {'weight_class_0': 0.45764995068944336, 'weight_class_1': 3.90914211015772, 'weight_class_2': 2.5934156879768495}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,303] Trial 325 finished with value: 0.9489726174808708 and parameters: {'weight_class_0': 0.39536215581666545, 'weight_class_1': 3.769922283085772, 'weight_class_2': 2.625752523057872}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,313] Trial 324 finished with value: 0.9484085561867799 and parameters: {'weight_class_0': 0.4638972736998223, 'weight_class_1': 3.7504200775328735, 'weight_class_2': 2.58565090254181}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,326] Trial 326 finished with value: 0.9484410516621006 and parameters: {'weight_class_0': 0.46237512183737683, 'weight_class_1': 3.777737835615996, 'weight_class_2': 2.6342380484364867}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,347] Trial 327 finished with value: 0.9486285648729496 and parameters: {'weight_class_0': 0.4375005026056718, 'weight_class_1': 3.850155526788161, 'weight_class_2': 2.550852518857351}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,390] Trial 328 finished with value: 0.9486178336163298 and parameters: {'weight_class_0': 0.467317604414082, 'weight_class_1': 4.596067804449851, 'weight_class_2': 2.6873931109343654}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,401] Trial 329 finished with value: 0.9485042524091455 and parameters: {'weight_class_0': 0.4681500738685105, 'weight_class_1': 4.560352552210796, 'weight_class_2': 2.5963202841996127}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,414] Trial 330 finished with value: 0.9491497640344688 and parameters: {'weight_class_0': 0.40396156512845227, 'weight_class_1': 4.947003497270079, 'weight_class_2': 2.7339864483385776}. Best is trial 255 with value: 0.9496751209701936.

Best trial: 255. Best value: 0.949675:  11%|███████████████                                                                                                                     | 341/3000 [00:06<00:50, 52.89it/s]

[I 2026-07-05 15:22:41,438] Trial 331 finished with value: 0.948879368044205 and parameters: {'weight_class_0': 0.3745830213061094, 'weight_class_1': 9.897911616119039, 'weight_class_2': 2.699351350293434}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,443] Trial 332 finished with value: 0.9492520346677457 and parameters: {'weight_class_0': 0.378174645747833, 'weight_class_1': 4.6058374829809985, 'weight_class_2': 2.671988968974554}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,480] Trial 333 finished with value: 0.9480297043544629 and parameters: {'weight_class_0': 0.37344887211766586, 'weight_class_1': 9.557513591083838, 'weight_class_2': 1.9872667952145786}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,488] Trial 334 finished with value: 0.9493815940080617 and parameters: {'weight_class_0': 0.38458254602966857, 'weight_class_1': 9.617711632461432, 'weight_class_2': 4.665699944162309}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,507] Trial 335 finished with value: 0.9442367203625203 and parameters: {'weight_class_0': 0.6545351721612575, 'weight_class_1': 9.706575463355767, 'weight_class_2': 2.0690779547084768}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,543] Trial 336 finished with value: 0.948716623667499 and parameters: {'weight_class_0': 0.3700425919103415, 'weight_class_1': 5.536787877006755, 'weight_class_2': 2.1279984045039946}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,564] Trial 337 finished with value: 0.9484855072004018 and parameters: {'weight_class_0': 0.37926600057944865, 'weight_class_1': 4.857375432706696, 'weight_class_2': 2.007992994027422}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,568] Trial 338 finished with value: 0.8869237697646734 and parameters: {'weight_class_0': 4.037421621289822, 'weight_class_1': 8.671947958348971, 'weight_class_2': 2.0279214978078888}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,597] Trial 339 finished with value: 0.9484810596384255 and parameters: {'weight_class_0': 0.28354098069052813, 'weight_class_1': 9.606932822651666, 'weight_class_2': 2.0260549769393372}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,620] Trial 340 finished with value: 0.9492363764182526 and parameters: {'weight_class_0': 0.26746243182146334, 'weight_class_1': 5.445163408929807, 'weight_class_2': 1.960774032249158}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,639] Trial 341 finished with value: 0.943157277349901 and parameters: {'weight_class_0': 0.6952565516464941, 'weight_class_1': 5.660567488755166, 'weight_class_2': 2.0580778300280205}. Best is trial 255 with value: 0.9496751209701936.

Best trial: 255. Best value: 0.949675:  12%|███████████████▌                                                                                                                    | 353/3000 [00:06<00:51, 51.45it/s]

[I 2026-07-05 15:22:41,640] Trial 342 finished with value: 0.9492806670845543 and parameters: {'weight_class_0': 0.28204027775160434, 'weight_class_1': 5.36853418527022, 'weight_class_2': 2.0441764902397535}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,676] Trial 343 finished with value: 0.949049133718486 and parameters: {'weight_class_0': 0.6746229821544415, 'weight_class_1': 5.548574019424386, 'weight_class_2': 4.848847211169806}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,693] Trial 344 finished with value: 0.9489302753502139 and parameters: {'weight_class_0': 0.27646732580347866, 'weight_class_1': 5.676931855238833, 'weight_class_2': 5.512597171938302}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,704] Trial 345 finished with value: 0.9492883461654121 and parameters: {'weight_class_0': 0.2787842829568651, 'weight_class_1': 5.1669508571110505, 'weight_class_2': 4.571689285845946}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,733] Trial 346 finished with value: 0.9492492069220543 and parameters: {'weight_class_0': 0.2763604435263291, 'weight_class_1': 5.554340417254672, 'weight_class_2': 4.578549840625122}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,765] Trial 347 finished with value: 0.9492242369112187 and parameters: {'weight_class_0': 0.27379470134919137, 'weight_class_1': 5.5816527415565895, 'weight_class_2': 4.465508508584644}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,780] Trial 349 finished with value: 0.9488715733831891 and parameters: {'weight_class_0': 0.27095632135166914, 'weight_class_1': 5.515959321506881, 'weight_class_2': 5.493170477616504}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,785] Trial 348 finished with value: 0.9491411603545402 and parameters: {'weight_class_0': 0.27088348551534747, 'weight_class_1': 5.624187244164722, 'weight_class_2': 4.600351949938823}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,807] Trial 351 finished with value: 0.9481721165914209 and parameters: {'weight_class_0': 0.19106769339317764, 'weight_class_1': 5.502738521071999, 'weight_class_2': 4.809645073642301}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,820] Trial 350 finished with value: 0.9482401854392529 and parameters: {'weight_class_0': 0.18846215473347802, 'weight_class_1': 5.560665480480723, 'weight_class_2': 4.502843358350934}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,839] Trial 353 finished with value: 0.9483994877821865 and parameters: {'weight_class_0': 0.18294948370749636, 'weight_class_1': 2.474218091356513, 'weight_class_2': 4.3927277081613205}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,864] Trial 354 finished with value: 0.948577366229972 and parameters: {'weight_class_0': 0.2038717784917084, 'weight_class_1': 7.7293997097983285, 'weight_class_2': 3.0236104960146024}. Best is trial 255 with value: 0.9496751209701936.

[I 2026-07-05 15:22:41,866] Trial 352 finished with value: 0.9486646649653926 and parameters: {'weight_class_0': 0.2803458507859947, 'weight_class_1': 7.532413111470301, 'weight_class_2': 5.57621171049233}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,901] Trial 355 finished with value: 0.9484389567695439 and parameters: {'weight_class_0': 0.19220000934564524, 'weight_class_1': 7.4088274982768425, 'weight_class_2': 3.0247329768762996}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,930] Trial 356 finished with value: 0.8611664443686532 and parameters: {'weight_class_0': 0.20798082778677848, 'weight_class_1': 7.583333765497496, 'weight_class_2': 0.031093912516986674}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,941] Trial 357 finished with value: 0.9483579583620724 and parameters: {'weight_class_0': 0.19495588693783178, 'weight_class_1': 7.68394720455787, 'weight_class_2': 3.213971530783718}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,959] Trial 358 finished with value: 0.9492829325921587 and parameters: {'weight_class_0': 0.19336866195032545, 'weight_class_1': 2.5917170391634787, 'weight_class_2': 3.12007989481557}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,983] Trial 360 finished with value: 0.9481506998527939 and parameters: {'weight_class_0': 0.19217153206366558, 'weight_class_1': 7.880056384087522, 'weight_class_2': 3.2940153908809386}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:41,986] Trial 359 finished with value: 0.9482887082194601 and parameters: {'weight_class_0': 0.19353962719882642, 'weight_class_1': 7.890547676326557, 'weight_class_2': 3.108223093585787}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:42,027] Trial 361 finished with value: 0.9486861630184645 and parameters: {'weight_class_0': 0.5682140988620744, 'weight_class_1': 7.703708269394112, 'weight_class_2': 3.214287540729119}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:42,028] Trial 362 finished with value: 0.9494570210551311 and parameters: {'weight_class_0': 0.35126720119879823, 'weight_class_1': 7.781022450347066, 'weight_class_2': 3.130046758005443}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:42,046] Trial 363 finished with value: 0.9483833178394852 and parameters: {'weight_class_0': 0.5523507518126509, 'weight_class_1': 4.4414198159010585, 'weight_class_2': 3.095495441022225}. Best is trial 255 with value: 0.9496751209701936.

Best trial: 373. Best value: 0.949678:  12%|████████████████▍                                                                                                                   | 374/3000 [00:07<00:51, 51.15it/s]

[I 2026-07-05 15:22:42,069] Trial 364 finished with value: 0.9302604899124467 and parameters: {'weight_class_0': 0.5255848634803473, 'weight_class_1': 2.611501081123463, 'weight_class_2': 0.9610177491520221}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:42,097] Trial 365 finished with value: 0.8773792836097477 and parameters: {'weight_class_0': 0.34319405854310303, 'weight_class_1': 4.4758616919046, 'weight_class_2': 0.028041377386023893}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:42,108] Trial 366 finished with value: 0.9468054307378663 and parameters: {'weight_class_0': 0.5670322735114373, 'weight_class_1': 2.646449983546341, 'weight_class_2': 3.171497841245594}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:42,120] Trial 367 finished with value: 0.948559910015411 and parameters: {'weight_class_0': 0.539727946506154, 'weight_class_1': 4.405235435929806, 'weight_class_2': 3.1812452774212705}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:42,143] Trial 368 finished with value: 0.7632490275795122 and parameters: {'weight_class_0': 0.5638306218084284, 'weight_class_1': 0.005360645665314673, 'weight_class_2': 3.5401955863126036}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:42,172] Trial 369 finished with value: 0.9484085234176046 and parameters: {'weight_class_0': 0.3285590309900697, 'weight_class_1': 1.882570599182837, 'weight_class_2': 3.8953640344004348}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:42,191] Trial 370 finished with value: 0.9488710005392295 and parameters: {'weight_class_0': 0.5644526581980729, 'weight_class_1': 4.445573542272301, 'weight_class_2': 3.894490351374573}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:42,218] Trial 372 finished with value: 0.9496550623135808 and parameters: {'weight_class_0': 0.3222430875349498, 'weight_class_1': 4.4331522660597615, 'weight_class_2': 3.8751979548504263}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:42,229] Trial 371 finished with value: 0.9494945556053459 and parameters: {'weight_class_0': 0.34865079918991304, 'weight_class_1': 3.1646169995689597, 'weight_class_2': 3.9781440646199453}. Best is trial 255 with value: 0.9496751209701936.
[I 2026-07-05 15:22:42,243] Trial 373 finished with value: 0.9496781637634051 and parameters: {'weight_class_0': 0.33776345836362026, 'weight_class_1': 4.444951099758612, 'weight_class_2': 3.792026259715349}. Best is trial 373 with value: 0.9496781637634051.
[I 2026-07-05 15:22:42,267] Trial 375 finished with value: 0.9495269602558704 and parameters: {'weight_class_0': 0.3413544450496738, 'weight_class_1': 3.245362346051798, 'weight_class_2': 3.8156158629305934}. Best is trial 373 with value: 0.9496781637634051.

Best trial: 376. Best value: 0.949725:  13%|████████████████▉                                                                                                                   | 385/3000 [00:07<00:51, 51.10it/s]

[I 2026-07-05 15:22:42,290] Trial 374 finished with value: 0.9494859122177983 and parameters: {'weight_class_0': 0.3452651986252078, 'weight_class_1': 3.2193847842925822, 'weight_class_2': 3.7909951981789343}. Best is trial 373 with value: 0.9496781637634051.
[I 2026-07-05 15:22:42,298] Trial 376 finished with value: 0.9497246321366343 and parameters: {'weight_class_0': 0.3375585315547717, 'weight_class_1': 4.398713187963825, 'weight_class_2': 3.9054212513435473}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:42,318] Trial 377 finished with value: 0.9475134436044862 and parameters: {'weight_class_0': 0.34094848434236513, 'weight_class_1': 3.1862294790835093, 'weight_class_2': 1.528857750271948}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:42,334] Trial 378 finished with value: 0.9490303667288297 and parameters: {'weight_class_0': 0.34598482168837896, 'weight_class_1': 3.285518795600353, 'weight_class_2': 2.3922414712970945}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:42,356] Trial 379 finished with value: 0.9489339788556839 and parameters: {'weight_class_0': 0.3529026734875324, 'weight_class_1': 3.0170888505121143, 'weight_class_2': 2.413998540314493}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:42,388] Trial 381 finished with value: 0.9491524822515686 and parameters: {'weight_class_0': 0.3322428444289111, 'weight_class_1': 3.2916207225209724, 'weight_class_2': 2.3753589174578567}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:42,391] Trial 380 finished with value: 0.9476801682481216 and parameters: {'weight_class_0': 0.34576496739715523, 'weight_class_1': 3.1996261884977466, 'weight_class_2': 1.5969430779711098}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:42,421] Trial 382 finished with value: 0.9480473415733167 and parameters: {'weight_class_0': 0.3206658671257634, 'weight_class_1': 3.159308167947581, 'weight_class_2': 1.5668330794554393}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:42,459] Trial 383 finished with value: 0.5638656018286482 and parameters: {'weight_class_0': 0.003857015267880775, 'weight_class_1': 3.2430220996132757, 'weight_class_2': 0.004696109880325755}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:42,460] Trial 384 finished with value: 0.948544034131063 and parameters: {'weight_class_0': 0.39816185018346273, 'weight_class_1': 3.223771406989964, 'weight_class_2': 2.357631778561922}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:42,462] Trial 385 finished with value: 0.9489759761364901 and parameters: {'weight_class_0': 0.41053981243724325, 'weight_class_1': 3.4480778551951503, 'weight_class_2': 6.201598217505991}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  13%|█████████████████▍                                                                                                                  | 396/3000 [00:07<00:52, 49.85it/s]

[I 2026-07-05 15:22:42,483] Trial 386 finished with value: 0.9492357767137932 and parameters: {'weight_class_0': 0.4139488750176006, 'weight_class_1': 4.396492050741271, 'weight_class_2': 6.049264071662722}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:42,517] Trial 387 finished with value: 0.9494536912573723 and parameters: {'weight_class_0': 0.43498879791168693, 'weight_class_1': 4.20513491644486, 'weight_class_2': 5.170144824624861}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:42,555] Trial 388 finished with value: 0.9494436486240859 and parameters: {'weight_class_0': 0.4463125160638632, 'weight_class_1': 4.4677839368958505, 'weight_class_2': 5.70318275352022}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:42,589] Trial 389 finished with value: 0.9492642410381285 and parameters: {'weight_class_0': 0.4198751380571192, 'weight_class_1': 4.3312674054733185, 'weight_class_2': 5.948403844183179}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:42,605] Trial 390 finished with value: 0.6587432785586217 and parameters: {'weight_class_0': 0.003188328375218641, 'weight_class_1': 4.137741805387989, 'weight_class_2': 6.052434099921723}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:42,608] Trial 391 finished with value: 0.9078066495565859 and parameters: {'weight_class_0': 0.451046473111731, 'weight_class_1': 0.30449586132982803, 'weight_class_2': 5.948954225151937}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:42,619] Trial 392 finished with value: 0.9493393258632418 and parameters: {'weight_class_0': 0.4255479977920432, 'weight_class_1': 4.373793014038819, 'weight_class_2': 5.874384412204837}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:42,625] Trial 393 finished with value: 0.9492160932605591 and parameters: {'weight_class_0': 0.44476557566279673, 'weight_class_1': 4.380033255012346, 'weight_class_2': 6.5691910928170145}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:42,646] Trial 394 finished with value: 0.9486555946221588 and parameters: {'weight_class_0': 0.25436099230833914, 'weight_class_1': 4.623179378577402, 'weight_class_2': 5.691065363108214}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:42,690] Trial 395 finished with value: 0.8284704978735999 and parameters: {'weight_class_0': 0.24605455199399567, 'weight_class_1': 4.586930482524781, 'weight_class_2': 0.012320568787847028}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:42,695] Trial 396 finished with value: 0.9478203411182701 and parameters: {'weight_class_0': 0.23016770457365968, 'weight_class_1': 4.639558982452232, 'weight_class_2': 7.6976548691915925}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  14%|█████████████████▊                                                                                                                  | 406/3000 [00:07<00:51, 50.32it/s]

[I 2026-07-05 15:22:42,705] Trial 397 finished with value: 0.9071608781272867 and parameters: {'weight_class_0': 0.24659939166756575, 'weight_class_1': 4.462951389333403, 'weight_class_2': 0.21648460681310333}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:42,746] Trial 398 finished with value: 0.8997228722372991 and parameters: {'weight_class_0': 0.2372730938129526, 'weight_class_1': 0.11336224870032938, 'weight_class_2': 4.342196123223243}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:42,777] Trial 400 finished with value: 0.949032642526331 and parameters: {'weight_class_0': 0.24699882662576514, 'weight_class_1': 6.0866630492160425, 'weight_class_2': 4.112409639557407}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:42,780] Trial 399 finished with value: 0.9490185037743343 and parameters: {'weight_class_0': 0.24304819967237706, 'weight_class_1': 6.073110805460894, 'weight_class_2': 4.047219561921008}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:42,796] Trial 402 finished with value: 0.9490310992484421 and parameters: {'weight_class_0': 0.24524524954426932, 'weight_class_1': 6.34272065670917, 'weight_class_2': 3.9326840417913775}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:42,816] Trial 401 finished with value: 0.8289994789806094 and parameters: {'weight_class_0': 0.2516936343602062, 'weight_class_1': 6.153244394334424, 'weight_class_2': 0.016502003524533168}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:42,834] Trial 403 finished with value: 0.9490123931454993 and parameters: {'weight_class_0': 0.25230535689151473, 'weight_class_1': 6.038638679882354, 'weight_class_2': 4.264208854608636}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:42,857] Trial 404 finished with value: 0.9489527241571148 and parameters: {'weight_class_0': 0.24735488206068543, 'weight_class_1': 6.077636249456195, 'weight_class_2': 4.233128491478011}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:42,877] Trial 405 finished with value: 0.9493470563924035 and parameters: {'weight_class_0': 0.28459518303520115, 'weight_class_1': 6.0832499059742275, 'weight_class_2': 4.167414522846044}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:42,899] Trial 406 finished with value: 0.9494214564647488 and parameters: {'weight_class_0': 0.2891803191835856, 'weight_class_1': 6.075202101994927, 'weight_class_2': 4.007363532373722}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  14%|██████████████████▎                                                                                                                 | 417/3000 [00:08<00:52, 49.17it/s]

[I 2026-07-05 15:22:42,924] Trial 407 finished with value: 0.949525215099596 and parameters: {'weight_class_0': 0.29647732576019403, 'weight_class_1': 6.120367411237233, 'weight_class_2': 3.724506023130535}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:42,963] Trial 408 finished with value: 0.9495386541464393 and parameters: {'weight_class_0': 0.30290039449211065, 'weight_class_1': 6.071166875524404, 'weight_class_2': 3.820889206385806}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:42,974] Trial 410 finished with value: 0.9496134172014008 and parameters: {'weight_class_0': 0.31782360142216576, 'weight_class_1': 5.891809128606847, 'weight_class_2': 2.8921857952503753}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:42,975] Trial 409 finished with value: 0.9495473656445212 and parameters: {'weight_class_0': 0.30026272580043606, 'weight_class_1': 6.144855103423347, 'weight_class_2': 2.8623478794552226}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,007] Trial 411 finished with value: 0.9106729817655014 and parameters: {'weight_class_0': 0.3067395021949353, 'weight_class_1': 0.23489820304502187, 'weight_class_2': 2.8260543324218372}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,033] Trial 412 finished with value: 0.949348259149536 and parameters: {'weight_class_0': 0.3044013554466422, 'weight_class_1': 2.4472870086859646, 'weight_class_2': 2.8886052180298023}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,086] Trial 414 finished with value: 0.943952911515352 and parameters: {'weight_class_0': 0.7814416958536404, 'weight_class_1': 3.7273134640013774, 'weight_class_2': 2.7939720700042954}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,091] Trial 413 finished with value: 0.9496340310121814 and parameters: {'weight_class_0': 0.3049605902614114, 'weight_class_1': 3.8430552442911097, 'weight_class_2': 2.761150238735792}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,099] Trial 416 finished with value: 0.9457413662674804 and parameters: {'weight_class_0': 0.676677219971556, 'weight_class_1': 3.788877182580659, 'weight_class_2': 2.784060176458431}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,118] Trial 415 finished with value: 0.9457781466890469 and parameters: {'weight_class_0': 0.6876205463321677, 'weight_class_1': 3.7900531742142047, 'weight_class_2': 2.858642458741764}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,121] Trial 417 finished with value: 0.9482386019295913 and parameters: {'weight_class_0': 0.512191992504564, 'weight_class_1': 3.9200350778125994, 'weight_class_2': 2.834354873886107}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  14%|██████████████████▉                                                                                                                 | 429/3000 [00:08<00:49, 52.41it/s]

[I 2026-07-05 15:22:43,129] Trial 418 finished with value: 0.94862957221339 and parameters: {'weight_class_0': 0.3875451521145939, 'weight_class_1': 2.5504483525899393, 'weight_class_2': 2.7978952698583455}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,177] Trial 420 finished with value: 0.9480569668269604 and parameters: {'weight_class_0': 0.5117416375076572, 'weight_class_1': 3.7683900576889977, 'weight_class_2': 2.7230313415295875}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,187] Trial 419 finished with value: 0.9473889627175477 and parameters: {'weight_class_0': 0.48658702664197, 'weight_class_1': 2.582505222786328, 'weight_class_2': 2.7152306081734543}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,196] Trial 421 finished with value: 0.9441097837151909 and parameters: {'weight_class_0': 0.7760032942793572, 'weight_class_1': 3.8986772754897494, 'weight_class_2': 2.75845343802039}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,224] Trial 422 finished with value: 0.9477568450045085 and parameters: {'weight_class_0': 0.4856241420983416, 'weight_class_1': 3.758489671667357, 'weight_class_2': 2.408523411439761}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,238] Trial 424 finished with value: 0.942937970428145 and parameters: {'weight_class_0': 0.728413460110965, 'weight_class_1': 3.8101143572603484, 'weight_class_2': 2.3223029326752753}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,251] Trial 423 finished with value: 0.9453813581224653 and parameters: {'weight_class_0': 0.6771124271628886, 'weight_class_1': 3.67203928975431, 'weight_class_2': 2.669402392566025}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,291] Trial 425 finished with value: 0.9476365228537734 and parameters: {'weight_class_0': 0.5041366622436069, 'weight_class_1': 4.868610204575419, 'weight_class_2': 2.293590838506034}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,301] Trial 426 finished with value: 0.9462030618641076 and parameters: {'weight_class_0': 0.37305025344533516, 'weight_class_1': 1.5295653327512435, 'weight_class_2': 2.2560018396325097}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,328] Trial 427 finished with value: 0.9488372607439652 and parameters: {'weight_class_0': 0.3743708582580115, 'weight_class_1': 4.800734149513411, 'weight_class_2': 2.248354127704442}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,340] Trial 428 finished with value: 0.9458317067619572 and parameters: {'weight_class_0': 0.5014297290915418, 'weight_class_1': 4.966859450223194, 'weight_class_2': 1.8046904357089368}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,367] Trial 429 finished with value: 0.9488234024589598 and parameters: {'weight_class_0': 0.3754637047341255, 'weight_class_1': 4.976199477905616, 'weight_class_2': 2.227186528213098}. Best is trial 376 with value: 0.9497246321366343.

[I 2026-07-05 15:22:43,383] Trial 430 finished with value: 0.925343036252948 and parameters: {'weight_class_0': 0.3639783410585563, 'weight_class_1': 1.6600500538722482, 'weight_class_2': 0.5783704002715498}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,401] Trial 431 finished with value: 0.8472327908922487 and parameters: {'weight_class_0': 0.36107334855699147, 'weight_class_1': 0.022618349693181453, 'weight_class_2': 0.5090152734344898}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,423] Trial 432 finished with value: 0.9481511273861644 and parameters: {'weight_class_0': 0.37956716859670725, 'weight_class_1': 4.927992801833089, 'weight_class_2': 1.8778477832101104}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,442] Trial 433 finished with value: 0.9472507662019581 and parameters: {'weight_class_0': 0.11934496686736096, 'weight_class_1': 4.9252537316771035, 'weight_class_2': 3.476728332207137}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,457] Trial 434 finished with value: 0.9478675835305688 and parameters: {'weight_class_0': 0.3771579702628684, 'weight_class_1': 4.785157487943971, 'weight_class_2': 1.7558057348923282}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,474] Trial 436 finished with value: 0.9493806507540631 and parameters: {'weight_class_0': 0.21119761228239303, 'weight_class_1': 5.235381635475035, 'weight_class_2': 1.8532906123948067}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,474] Trial 435 finished with value: 0.9491922636293885 and parameters: {'weight_class_0': 0.10580996400436615, 'weight_class_1': 1.9843682356625267, 'weight_class_2': 1.8391911958912561}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,519] Trial 437 finished with value: 0.9490219984275444 and parameters: {'weight_class_0': 0.21176423857253734, 'weight_class_1': 2.045725669036432, 'weight_class_2': 3.3677259102063024}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,530] Trial 438 finished with value: 0.8702285605080812 and parameters: {'weight_class_0': 0.2069898551482242, 'weight_class_1': 0.016163167077787033, 'weight_class_2': 3.4976972520850858}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,561] Trial 439 finished with value: 0.9485581994606392 and parameters: {'weight_class_0': 0.21522628792690682, 'weight_class_1': 2.845796519030192, 'weight_class_2': 4.865802750254907}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,567] Trial 440 finished with value: 0.948965483105965 and parameters: {'weight_class_0': 0.2085600763967897, 'weight_class_1': 2.0422242227955176, 'weight_class_2': 3.456436050219975}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  15%|███████████████████▊                                                                                                                | 450/3000 [00:08<00:50, 50.66it/s]

[I 2026-07-05 15:22:43,591] Trial 441 finished with value: 0.9493096354202817 and parameters: {'weight_class_0': 0.20319076648159787, 'weight_class_1': 2.6829588290829345, 'weight_class_2': 3.2549273247050525}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,603] Trial 442 finished with value: 0.948151487522726 and parameters: {'weight_class_0': 0.11963103987739802, 'weight_class_1': 2.627168135797823, 'weight_class_2': 3.4107694242941484}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,626] Trial 444 finished with value: 0.9491179617938347 and parameters: {'weight_class_0': 0.20160978473100047, 'weight_class_1': 2.9371648462950386, 'weight_class_2': 3.5302885432398976}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,632] Trial 443 finished with value: 0.9480687243965775 and parameters: {'weight_class_0': 0.20871402883600426, 'weight_class_1': 2.109116804072357, 'weight_class_2': 4.972996933299677}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,673] Trial 445 finished with value: 0.9494440503346279 and parameters: {'weight_class_0': 0.3001692120326112, 'weight_class_1': 2.6465643503589837, 'weight_class_2': 3.421471622910344}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,687] Trial 446 finished with value: 0.949472497904977 and parameters: {'weight_class_0': 0.2953670076621366, 'weight_class_1': 2.689285170220591, 'weight_class_2': 3.414452664817421}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,709] Trial 447 finished with value: 0.9490176005671995 and parameters: {'weight_class_0': 0.2946092225720347, 'weight_class_1': 2.899743074676643, 'weight_class_2': 4.780574013092592}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,727] Trial 448 finished with value: 0.9488520073675727 and parameters: {'weight_class_0': 0.3008583086456031, 'weight_class_1': 3.0111924791058775, 'weight_class_2': 5.202145747976756}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,756] Trial 449 finished with value: 0.9489036899263968 and parameters: {'weight_class_0': 0.30710315693392537, 'weight_class_1': 2.755801213921061, 'weight_class_2': 5.0045463231151635}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,762] Trial 451 finished with value: 0.9491751242555918 and parameters: {'weight_class_0': 0.3013903920184207, 'weight_class_1': 6.8186769842584685, 'weight_class_2': 4.751704954373606}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  15%|████████████████████▎                                                                                                               | 462/3000 [00:08<00:48, 52.31it/s]

[I 2026-07-05 15:22:43,769] Trial 450 finished with value: 0.9491438618948523 and parameters: {'weight_class_0': 0.3027590433978642, 'weight_class_1': 2.985720935379953, 'weight_class_2': 4.573542931347892}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,804] Trial 452 finished with value: 0.6687981912275559 and parameters: {'weight_class_0': 0.29855949451554753, 'weight_class_1': 0.0012786584117371023, 'weight_class_2': 4.785648512321585}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,815] Trial 453 finished with value: 0.9490973231462356 and parameters: {'weight_class_0': 0.30265438747488294, 'weight_class_1': 7.078037316490195, 'weight_class_2': 4.895113440584268}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,833] Trial 454 finished with value: 0.8300912561836097 and parameters: {'weight_class_0': 0.3042222641104575, 'weight_class_1': 0.008386327031481787, 'weight_class_2': 5.010411467693951}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,851] Trial 455 finished with value: 0.949142941015405 and parameters: {'weight_class_0': 0.30052505846557875, 'weight_class_1': 6.76947594901839, 'weight_class_2': 4.848291576595716}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,893] Trial 456 finished with value: 0.9489274824122121 and parameters: {'weight_class_0': 0.27984898671026054, 'weight_class_1': 7.157864028603507, 'weight_class_2': 4.767239084293147}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,901] Trial 457 finished with value: 0.9491339752283597 and parameters: {'weight_class_0': 0.3130969791649967, 'weight_class_1': 7.089092793132636, 'weight_class_2': 5.0909169646945225}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,916] Trial 458 finished with value: 0.657847401120593 and parameters: {'weight_class_0': 0.0014904873866330584, 'weight_class_1': 5.45451418750936, 'weight_class_2': 4.284686826173711}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,942] Trial 460 finished with value: 0.9483470496290315 and parameters: {'weight_class_0': 0.43996861840534224, 'weight_class_1': 5.339160550182823, 'weight_class_2': 2.267689094771811}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,949] Trial 459 finished with value: 0.9487106298928135 and parameters: {'weight_class_0': 0.41326606983881353, 'weight_class_1': 4.15522115230265, 'weight_class_2': 2.4567164330018696}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,985] Trial 462 finished with value: 0.8603476211171235 and parameters: {'weight_class_0': 8.30133598224153, 'weight_class_1': 4.116395296349237, 'weight_class_2': 7.72009420252302}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:43,986] Trial 461 finished with value: 0.9467102096724203 and parameters: {'weight_class_0': 0.16019105999018074, 'weight_class_1': 5.197465220602761, 'weight_class_2': 7.6587689523871045}. Best is trial 376 with value: 0.9497246321366343.

[I 2026-07-05 15:22:44,012] Trial 463 finished with value: 0.949000999698372 and parameters: {'weight_class_0': 0.15096060932054492, 'weight_class_1': 4.181093485635383, 'weight_class_2': 2.3559463192801684}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,032] Trial 464 finished with value: 0.9481974376874617 and parameters: {'weight_class_0': 0.4190388499173803, 'weight_class_1': 4.119128581981551, 'weight_class_2': 2.1195967227828287}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,063] Trial 465 finished with value: 0.9484062676395705 and parameters: {'weight_class_0': 0.42140130017588806, 'weight_class_1': 4.16243108539599, 'weight_class_2': 2.245680396703074}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,078] Trial 466 finished with value: 0.949219923971847 and parameters: {'weight_class_0': 0.4222430262151334, 'weight_class_1': 4.2275284120722025, 'weight_class_2': 3.088126841574357}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,105] Trial 467 finished with value: 0.9482288027674858 and parameters: {'weight_class_0': 0.4384002551524957, 'weight_class_1': 4.097719253431612, 'weight_class_2': 2.2698751699954935}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,115] Trial 468 finished with value: 0.9486734065925932 and parameters: {'weight_class_0': 0.4222702729393375, 'weight_class_1': 4.218196470690939, 'weight_class_2': 7.723635106395871}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,135] Trial 469 finished with value: 0.9493266738787897 and parameters: {'weight_class_0': 0.4053360694199663, 'weight_class_1': 3.9818068123794492, 'weight_class_2': 3.1309960632227947}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,142] Trial 470 finished with value: 0.9469821112536456 and parameters: {'weight_class_0': 0.1668750906898445, 'weight_class_1': 4.081360110892285, 'weight_class_2': 7.528299786903693}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,156] Trial 471 finished with value: 0.9492319476357455 and parameters: {'weight_class_0': 0.403104063094792, 'weight_class_1': 3.6807697054880526, 'weight_class_2': 3.0771245232393514}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,194] Trial 472 finished with value: 0.9473007406948747 and parameters: {'weight_class_0': 0.6039040602122866, 'weight_class_1': 3.6910641346505026, 'weight_class_2': 3.009055071394116}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,233] Trial 474 finished with value: 0.9494939902042976 and parameters: {'weight_class_0': 0.3732966985372245, 'weight_class_1': 3.486404436101151, 'weight_class_2': 3.0980374896490726}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  16%|█████████████████████▎                                                                                                              | 484/3000 [00:09<00:49, 51.03it/s]

[I 2026-07-05 15:22:44,235] Trial 473 finished with value: 0.6577861473614591 and parameters: {'weight_class_0': 0.0010128974427698685, 'weight_class_1': 3.4547231763597543, 'weight_class_2': 3.0784570075706252}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,252] Trial 475 finished with value: 0.9474865268633991 and parameters: {'weight_class_0': 0.5709214346782275, 'weight_class_1': 3.426850165485014, 'weight_class_2': 2.988078146325754}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,265] Trial 476 finished with value: 0.9285368718000079 and parameters: {'weight_class_0': 0.0332805237189071, 'weight_class_1': 3.5062336663994786, 'weight_class_2': 3.5781876673369304}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,281] Trial 477 finished with value: 0.9495631408639921 and parameters: {'weight_class_0': 0.2513321339322318, 'weight_class_1': 3.581434019837578, 'weight_class_2': 3.486204590587166}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,302] Trial 478 finished with value: 0.9494390801139172 and parameters: {'weight_class_0': 0.249075247609809, 'weight_class_1': 3.4610961789782944, 'weight_class_2': 3.7058442146306603}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,331] Trial 479 finished with value: 0.9486895591598049 and parameters: {'weight_class_0': 0.6043191024325074, 'weight_class_1': 5.585712079826187, 'weight_class_2': 3.64320145201044}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,335] Trial 480 finished with value: 0.9492449717237833 and parameters: {'weight_class_0': 0.251599745522321, 'weight_class_1': 5.370977004357168, 'weight_class_2': 3.9300636879380484}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,348] Trial 481 finished with value: 0.949364764857353 and parameters: {'weight_class_0': 0.2585499189360155, 'weight_class_1': 5.333144190738903, 'weight_class_2': 3.7575915971862885}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,376] Trial 482 finished with value: 0.9494761530350629 and parameters: {'weight_class_0': 0.26246740570435595, 'weight_class_1': 5.471558540089324, 'weight_class_2': 3.552809268390256}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,406] Trial 483 finished with value: 0.9083794082038215 and parameters: {'weight_class_0': 0.031986251538797895, 'weight_class_1': 5.531454217955452, 'weight_class_2': 1.5265997016654131}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,408] Trial 484 finished with value: 0.9494706604924671 and parameters: {'weight_class_0': 0.25985470177193276, 'weight_class_1': 5.404838864845147, 'weight_class_2': 3.558403386528758}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  16%|█████████████████████▊                                                                                                              | 495/3000 [00:09<00:49, 50.98it/s]

[I 2026-07-05 15:22:44,471] Trial 485 finished with value: 0.9485661883303852 and parameters: {'weight_class_0': 0.24868957623060922, 'weight_class_1': 5.5159825964052684, 'weight_class_2': 1.4729514893839244}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,472] Trial 487 finished with value: 0.9496542302956228 and parameters: {'weight_class_0': 0.35054260145777, 'weight_class_1': 5.562991101466166, 'weight_class_2': 3.9276292034666156}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,488] Trial 486 finished with value: 0.9491672367052013 and parameters: {'weight_class_0': 0.24469445268113965, 'weight_class_1': 5.604998421334102, 'weight_class_2': 3.843742275582205}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,495] Trial 488 finished with value: 0.9496281895552107 and parameters: {'weight_class_0': 0.33288746109098305, 'weight_class_1': 5.400801204265398, 'weight_class_2': 3.922571510229226}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,517] Trial 489 finished with value: 0.9478990937373332 and parameters: {'weight_class_0': 0.3428902826426484, 'weight_class_1': 4.982897748136665, 'weight_class_2': 1.6182909953131035}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,523] Trial 490 finished with value: 0.9480683566805911 and parameters: {'weight_class_0': 0.345667892914433, 'weight_class_1': 4.893898703238093, 'weight_class_2': 1.6849867824275775}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,562] Trial 492 finished with value: 0.9474972354951169 and parameters: {'weight_class_0': 0.3318075256723437, 'weight_class_1': 8.517790530240747, 'weight_class_2': 1.5856609956310166}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,574] Trial 491 finished with value: 0.9474295134106435 and parameters: {'weight_class_0': 0.33599157268116187, 'weight_class_1': 8.184325071422066, 'weight_class_2': 1.567561624862124}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,607] Trial 493 finished with value: 0.9480909766976428 and parameters: {'weight_class_0': 0.3560766141539953, 'weight_class_1': 8.46329938891617, 'weight_class_2': 1.8988550776064566}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,618] Trial 494 finished with value: 0.9440410897997203 and parameters: {'weight_class_0': 0.347636510692944, 'weight_class_1': 4.765704288814693, 'weight_class_2': 1.071754499621814}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,649] Trial 495 finished with value: 0.9464349069625566 and parameters: {'weight_class_0': 0.5080279729331112, 'weight_class_1': 8.132438390688456, 'weight_class_2': 1.9496568554053588}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  17%|██████████████████████▎                                                                                                             | 506/3000 [00:09<00:50, 49.17it/s]

[I 2026-07-05 15:22:44,650] Trial 496 finished with value: 0.9481416108217863 and parameters: {'weight_class_0': 0.3590293506254713, 'weight_class_1': 7.2945217276709995, 'weight_class_2': 1.8523942139847023}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,676] Trial 497 finished with value: 0.9491769591151383 and parameters: {'weight_class_0': 0.34844789016881644, 'weight_class_1': 7.676387167533825, 'weight_class_2': 2.5836842624385623}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,678] Trial 498 finished with value: 0.9491830609082522 and parameters: {'weight_class_0': 0.34290173385789174, 'weight_class_1': 7.766919001126608, 'weight_class_2': 2.563830215683919}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,714] Trial 499 finished with value: 0.94900743976036 and parameters: {'weight_class_0': 0.3469788927378319, 'weight_class_1': 8.447369609972531, 'weight_class_2': 2.5563036135930832}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,736] Trial 500 finished with value: 0.9491926300347445 and parameters: {'weight_class_0': 0.3467582512852221, 'weight_class_1': 7.675325421026069, 'weight_class_2': 2.5798458652667966}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,742] Trial 501 finished with value: 0.9491286194618412 and parameters: {'weight_class_0': 0.3545336907396662, 'weight_class_1': 6.918147385156763, 'weight_class_2': 2.480976980427008}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,783] Trial 502 finished with value: 0.9492689579303484 and parameters: {'weight_class_0': 0.35543932547045864, 'weight_class_1': 7.1718989906769055, 'weight_class_2': 2.6290981769826858}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,812] Trial 503 finished with value: 0.9483220292944665 and parameters: {'weight_class_0': 0.5091206290521898, 'weight_class_1': 6.9663426224742055, 'weight_class_2': 2.6059972280246986}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,824] Trial 504 finished with value: 0.9483853554229921 and parameters: {'weight_class_0': 0.4975608248674859, 'weight_class_1': 6.836094056337087, 'weight_class_2': 2.57682224589901}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,836] Trial 505 finished with value: 0.9492835727440937 and parameters: {'weight_class_0': 0.22861666970149197, 'weight_class_1': 6.575903553917323, 'weight_class_2': 2.564798804989372}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,859] Trial 506 finished with value: 0.9485140589519255 and parameters: {'weight_class_0': 0.48417724388284833, 'weight_class_1': 6.334904070021331, 'weight_class_2': 2.593432959806801}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  17%|██████████████████████▋                                                                                                             | 517/3000 [00:10<00:48, 51.44it/s]

[I 2026-07-05 15:22:44,886] Trial 508 finished with value: 0.9477084575597612 and parameters: {'weight_class_0': 0.17145025587639723, 'weight_class_1': 6.481398479378198, 'weight_class_2': 4.212462380691762}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,892] Trial 507 finished with value: 0.9487970760040744 and parameters: {'weight_class_0': 0.17902049271781773, 'weight_class_1': 6.195754557699716, 'weight_class_2': 2.573884511398936}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,926] Trial 509 finished with value: 0.9475882452908263 and parameters: {'weight_class_0': 0.16969053185087385, 'weight_class_1': 6.444296094486417, 'weight_class_2': 4.4617935686507835}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,938] Trial 510 finished with value: 0.9491332071578739 and parameters: {'weight_class_0': 0.2685264854802359, 'weight_class_1': 6.385586727097939, 'weight_class_2': 4.207696000755844}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,949] Trial 511 finished with value: 0.9485949469596928 and parameters: {'weight_class_0': 0.2224060822961035, 'weight_class_1': 6.442276989203659, 'weight_class_2': 4.355534929889447}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,958] Trial 512 finished with value: 0.9480614731121287 and parameters: {'weight_class_0': 0.17356042051623222, 'weight_class_1': 6.157849866387071, 'weight_class_2': 3.7899393762908065}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:44,978] Trial 513 finished with value: 0.9483112213391417 and parameters: {'weight_class_0': 0.1667182657900424, 'weight_class_1': 4.697555100511616, 'weight_class_2': 3.9283750139730396}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:45,012] Trial 514 finished with value: 0.9492850828793191 and parameters: {'weight_class_0': 0.269026741896302, 'weight_class_1': 4.778680614226217, 'weight_class_2': 4.4747757556484}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:45,038] Trial 516 finished with value: 0.9493499459017049 and parameters: {'weight_class_0': 0.27075183302311084, 'weight_class_1': 4.575404182771338, 'weight_class_2': 4.270340938697051}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:45,053] Trial 515 finished with value: 0.9483246620847888 and parameters: {'weight_class_0': 0.17461180384441724, 'weight_class_1': 4.612745994388933, 'weight_class_2': 4.207410470015824}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:45,082] Trial 517 finished with value: 0.9167621333231896 and parameters: {'weight_class_0': 2.4269651123197207, 'weight_class_1': 4.803270548999142, 'weight_class_2': 4.085016890034718}. Best is trial 376 with value: 0.9497246321366343.

[I 2026-07-05 15:22:45,093] Trial 518 finished with value: 0.9494136986109029 and parameters: {'weight_class_0': 0.27234737363851935, 'weight_class_1': 4.717406705533626, 'weight_class_2': 4.073737589404444}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:45,112] Trial 519 finished with value: 0.9493285457399301 and parameters: {'weight_class_0': 0.21950090187293902, 'weight_class_1': 4.695450378684499, 'weight_class_2': 3.301493082587804}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:45,138] Trial 520 finished with value: 0.9496300847261819 and parameters: {'weight_class_0': 0.2695659129821078, 'weight_class_1': 4.726050945435504, 'weight_class_2': 3.1352270405295175}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:45,155] Trial 522 finished with value: 0.8800593388493408 and parameters: {'weight_class_0': 0.27587016144606674, 'weight_class_1': 0.037711122045590684, 'weight_class_2': 3.118414840270707}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:45,181] Trial 521 finished with value: 0.949631544891946 and parameters: {'weight_class_0': 0.27719947535640743, 'weight_class_1': 4.640533079178942, 'weight_class_2': 3.192093747023683}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:45,215] Trial 523 finished with value: 0.8908861732212371 and parameters: {'weight_class_0': 3.074641385813662, 'weight_class_1': 4.4429171515399295, 'weight_class_2': 3.156992195407117}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:45,224] Trial 524 finished with value: 0.8810602535943718 and parameters: {'weight_class_0': 0.21997028472326877, 'weight_class_1': 0.03482423829617257, 'weight_class_2': 3.233443045845675}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:45,260] Trial 525 finished with value: 0.9492304002816977 and parameters: {'weight_class_0': 0.4300265363197426, 'weight_class_1': 4.692609726780492, 'weight_class_2': 3.147843633563813}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:45,266] Trial 526 finished with value: 0.9493551742916494 and parameters: {'weight_class_0': 0.2209594427478812, 'weight_class_1': 4.820725349194656, 'weight_class_2': 3.091825817692089}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:45,292] Trial 528 finished with value: 0.9464361463902176 and parameters: {'weight_class_0': 0.06591512919014728, 'weight_class_1': 3.2511715025642025, 'weight_class_2': 2.0774454207399615}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:45,293] Trial 527 finished with value: 0.874443082867075 and parameters: {'weight_class_0': 0.4549480932845794, 'weight_class_1': 0.034622113403810925, 'weight_class_2': 3.168208243941689}. Best is trial 376 with value: 0.9497246321366343.

[I 2026-07-05 15:22:45,336] Trial 529 finished with value: 0.9494918097503198 and parameters: {'weight_class_0': 0.22477026554592783, 'weight_class_1': 3.2116178016128614, 'weight_class_2': 3.172271404606551}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:45,338] Trial 530 finished with value: 0.9490329579307429 and parameters: {'weight_class_0': 0.4296074464938274, 'weight_class_1': 3.3377765231868186, 'weight_class_2': 5.807427258595673}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:45,369] Trial 531 finished with value: 0.9490680900419474 and parameters: {'weight_class_0': 0.42680160356619207, 'weight_class_1': 3.3153404758393297, 'weight_class_2': 3.1795929892978276}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:45,375] Trial 532 finished with value: 0.5102102608040773 and parameters: {'weight_class_0': 0.006106213437482557, 'weight_class_1': 0.0022635119767287887, 'weight_class_2': 5.423915812327866}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:45,417] Trial 534 finished with value: 0.9492891426503199 and parameters: {'weight_class_0': 0.42212788887032254, 'weight_class_1': 3.777215119947687, 'weight_class_2': 5.6968687686665325}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:45,437] Trial 533 finished with value: 0.6853357770869044 and parameters: {'weight_class_0': 0.006254252055932362, 'weight_class_1': 3.5735595981283335, 'weight_class_2': 5.376334803214606}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:45,471] Trial 535 finished with value: 0.8618262420063547 and parameters: {'weight_class_0': 6.510191727165636, 'weight_class_1': 3.328595817477938, 'weight_class_2': 6.231997038361953}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:45,486] Trial 536 finished with value: 0.9493277682477982 and parameters: {'weight_class_0': 0.41559289744329664, 'weight_class_1': 3.2591331581609855, 'weight_class_2': 3.6024798585866}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:45,493] Trial 537 finished with value: 0.9487951619671356 and parameters: {'weight_class_0': 0.3007216347132522, 'weight_class_1': 3.618035420855665, 'weight_class_2': 5.989575066167567}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:45,530] Trial 538 finished with value: 0.9485660629222469 and parameters: {'weight_class_0': 0.3075831563408789, 'weight_class_1': 3.254961266242759, 'weight_class_2': 6.139579564408535}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  18%|████████████████████████                                                                                                            | 547/3000 [00:10<00:51, 47.20it/s]

[I 2026-07-05 15:22:45,556] Trial 539 finished with value: 0.948969214252284 and parameters: {'weight_class_0': 0.30134076468268434, 'weight_class_1': 5.508298786630843, 'weight_class_2': 5.606187600526456}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:45,567] Trial 541 finished with value: 0.949582311876913 and parameters: {'weight_class_0': 0.2996474565346982, 'weight_class_1': 5.482388420921597, 'weight_class_2': 3.713411856752618}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:45,570] Trial 540 finished with value: 0.7710200636403107 and parameters: {'weight_class_0': 0.013035306489913795, 'weight_class_1': 3.9402832428092696, 'weight_class_2': 5.517762265256165}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:45,624] Trial 542 finished with value: 0.9489289367981614 and parameters: {'weight_class_0': 0.2905911670243624, 'weight_class_1': 5.4216201147021605, 'weight_class_2': 5.634873011074172}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:45,640] Trial 543 finished with value: 0.9495860942672788 and parameters: {'weight_class_0': 0.3036056941936481, 'weight_class_1': 5.5088262563834896, 'weight_class_2': 3.7190578286122205}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:45,665] Trial 544 finished with value: 0.8070596141461265 and parameters: {'weight_class_0': 0.015175480364320206, 'weight_class_1': 5.073796651969046, 'weight_class_2': 3.709872447680895}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:45,693] Trial 546 finished with value: 0.9495457704627891 and parameters: {'weight_class_0': 0.30824210331204316, 'weight_class_1': 5.47045953035381, 'weight_class_2': 4.073035018701612}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:45,706] Trial 545 finished with value: 0.9495864285917155 and parameters: {'weight_class_0': 0.2891207044606762, 'weight_class_1': 5.4747086505377, 'weight_class_2': 3.522834734906932}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:45,726] Trial 547 finished with value: 0.9495778586659122 and parameters: {'weight_class_0': 0.30648280177882453, 'weight_class_1': 5.315997352734021, 'weight_class_2': 3.6929395021076417}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  19%|████████████████████████▌                                                                                                           | 557/3000 [00:10<00:54, 45.22it/s]

[I 2026-07-05 15:22:45,746] Trial 548 finished with value: 0.9420243795132892 and parameters: {'weight_class_0': 0.28247176518819794, 'weight_class_1': 0.7491103205549737, 'weight_class_2': 3.818667486206845}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:45,786] Trial 549 finished with value: 0.9496155701617401 and parameters: {'weight_class_0': 0.30530279211136263, 'weight_class_1': 5.642231785557376, 'weight_class_2': 3.5236906091317137}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:45,807] Trial 550 finished with value: 0.9495406589651582 and parameters: {'weight_class_0': 0.268514107337604, 'weight_class_1': 5.123778203089187, 'weight_class_2': 3.654051631490908}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:45,841] Trial 551 finished with value: 0.9488211880520457 and parameters: {'weight_class_0': 0.3699312088399884, 'weight_class_1': 5.365930602599623, 'weight_class_2': 2.161267197335186}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:45,851] Trial 552 finished with value: 0.9496048741813813 and parameters: {'weight_class_0': 0.3643317266564728, 'weight_class_1': 5.248839859337558, 'weight_class_2': 3.7274430122386337}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:45,875] Trial 553 finished with value: 0.9487254444306009 and parameters: {'weight_class_0': 0.3792317874570454, 'weight_class_1': 4.382435139142227, 'weight_class_2': 2.1789809607051134}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:45,882] Trial 554 finished with value: 0.9495453589986041 and parameters: {'weight_class_0': 0.35351836146088256, 'weight_class_1': 4.316545217096374, 'weight_class_2': 2.7971677077962562}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:45,888] Trial 555 finished with value: 0.9488273635124972 and parameters: {'weight_class_0': 0.37440338648210314, 'weight_class_1': 4.3214722475497265, 'weight_class_2': 2.2414189434342866}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:45,936] Trial 556 finished with value: 0.9486921633161488 and parameters: {'weight_class_0': 0.37088194337621033, 'weight_class_1': 4.165820148741891, 'weight_class_2': 2.090345002629028}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:45,941] Trial 558 finished with value: 0.9487174786589039 and parameters: {'weight_class_0': 0.3766971449741581, 'weight_class_1': 4.305194350080848, 'weight_class_2': 2.1813525803957363}. Best is trial 376 with value: 0.9497246321366343.

[I 2026-07-05 15:22:45,961] Trial 557 finished with value: 0.9488178005026692 and parameters: {'weight_class_0': 0.3759041644643121, 'weight_class_1': 4.367970648505269, 'weight_class_2': 2.2504374390126127}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:45,988] Trial 559 finished with value: 0.9486437015018448 and parameters: {'weight_class_0': 0.38258553209355667, 'weight_class_1': 4.220904968373237, 'weight_class_2': 2.171651994296913}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,009] Trial 560 finished with value: 0.9485899686219064 and parameters: {'weight_class_0': 0.5121768659151058, 'weight_class_1': 9.9908353084846, 'weight_class_2': 2.9313579288739477}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,034] Trial 562 finished with value: 0.94963297421959 and parameters: {'weight_class_0': 0.5096270634684593, 'weight_class_1': 9.710803742314521, 'weight_class_2': 4.350434218827392}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,062] Trial 561 finished with value: 0.9495964268943947 and parameters: {'weight_class_0': 0.5014868114488078, 'weight_class_1': 8.870398372043516, 'weight_class_2': 4.451758315898124}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,069] Trial 563 finished with value: 0.9495154963175269 and parameters: {'weight_class_0': 0.5610021376320934, 'weight_class_1': 9.826648740901913, 'weight_class_2': 4.475597001623623}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,098] Trial 565 finished with value: 0.9496153459421154 and parameters: {'weight_class_0': 0.5006349189732571, 'weight_class_1': 9.655419682791523, 'weight_class_2': 4.668826105612227}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,102] Trial 564 finished with value: 0.949622878037248 and parameters: {'weight_class_0': 0.5279937844398577, 'weight_class_1': 9.043108970583178, 'weight_class_2': 4.601535623351237}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,136] Trial 566 finished with value: 0.9479719419188911 and parameters: {'weight_class_0': 0.49637924785289156, 'weight_class_1': 2.4172578958383086, 'weight_class_2': 4.594837858003791}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,166] Trial 567 finished with value: 0.9495492446449747 and parameters: {'weight_class_0': 0.5320750259438566, 'weight_class_1': 8.283189388094078, 'weight_class_2': 4.742477558015762}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,178] Trial 568 finished with value: 0.9495987187412677 and parameters: {'weight_class_0': 0.510549345219083, 'weight_class_1': 9.867157074835024, 'weight_class_2': 4.4897703458495535}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  19%|█████████████████████████▍                                                                                                          | 579/3000 [00:11<00:50, 47.96it/s]

[I 2026-07-05 15:22:46,183] Trial 569 finished with value: 0.9465789041824504 and parameters: {'weight_class_0': 0.588541259884162, 'weight_class_1': 2.2802767928201106, 'weight_class_2': 4.825119460018525}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,222] Trial 570 finished with value: 0.9462086268356286 and parameters: {'weight_class_0': 0.6141678996733831, 'weight_class_1': 2.3522890317293985, 'weight_class_2': 4.582608136280731}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,255] Trial 571 finished with value: 0.9495986227867479 and parameters: {'weight_class_0': 0.5502486897463745, 'weight_class_1': 9.292352624122245, 'weight_class_2': 4.572739365746937}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,256] Trial 572 finished with value: 0.9491454738890148 and parameters: {'weight_class_0': 0.6302582615392596, 'weight_class_1': 9.630381201939912, 'weight_class_2': 4.267104002893222}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,298] Trial 573 finished with value: 0.9493120532003166 and parameters: {'weight_class_0': 0.6428981090899071, 'weight_class_1': 8.388346813832483, 'weight_class_2': 4.683409118745321}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,310] Trial 575 finished with value: 0.949682072362477 and parameters: {'weight_class_0': 0.7024016532048885, 'weight_class_1': 8.848561883508067, 'weight_class_2': 6.561610263052338}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,322] Trial 574 finished with value: 0.9496464844203074 and parameters: {'weight_class_0': 0.5586616612852412, 'weight_class_1': 7.660352404439229, 'weight_class_2': 4.759682286306315}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,348] Trial 576 finished with value: 0.9493367950055993 and parameters: {'weight_class_0': 0.6373095859726912, 'weight_class_1': 8.947305757198698, 'weight_class_2': 4.6361287738000865}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,360] Trial 577 finished with value: 0.9496090508085224 and parameters: {'weight_class_0': 0.5753640330250879, 'weight_class_1': 8.806541520846512, 'weight_class_2': 5.068895419660399}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,372] Trial 579 finished with value: 0.949646847472874 and parameters: {'weight_class_0': 0.6123486989296656, 'weight_class_1': 8.594643703379102, 'weight_class_2': 7.369721122980589}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,394] Trial 580 finished with value: 0.9496240234418488 and parameters: {'weight_class_0': 0.6732261575605228, 'weight_class_1': 8.7363456164626, 'weight_class_2': 7.016476101204814}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  20%|█████████████████████████▉                                                                                                          | 590/3000 [00:11<00:47, 50.31it/s]

[I 2026-07-05 15:22:46,397] Trial 578 finished with value: 0.949600775138021 and parameters: {'weight_class_0': 0.6709526420765751, 'weight_class_1': 9.498405597748633, 'weight_class_2': 6.7240227910318415}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,411] Trial 581 finished with value: 0.9494345978123392 and parameters: {'weight_class_0': 0.8200466042476433, 'weight_class_1': 8.633918623178815, 'weight_class_2': 6.4577158750995}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,441] Trial 582 finished with value: 0.9495715703685602 and parameters: {'weight_class_0': 0.7114841711847792, 'weight_class_1': 7.882244513244875, 'weight_class_2': 7.067910643696739}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,464] Trial 583 finished with value: 0.9494758773227815 and parameters: {'weight_class_0': 0.48396494621237807, 'weight_class_1': 7.745963543783034, 'weight_class_2': 7.114334885829428}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,490] Trial 584 finished with value: 0.9491353301020004 and parameters: {'weight_class_0': 0.4430441690431493, 'weight_class_1': 7.026687933079319, 'weight_class_2': 3.0057281226438293}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,517] Trial 585 finished with value: 0.9488955979011754 and parameters: {'weight_class_0': 0.9400339171793233, 'weight_class_1': 8.568927751565047, 'weight_class_2': 6.167644558378557}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,522] Trial 586 finished with value: 0.9490902100986335 and parameters: {'weight_class_0': 0.8272666419905401, 'weight_class_1': 8.309755058451083, 'weight_class_2': 5.795622139059221}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,567] Trial 587 finished with value: 0.949662314427246 and parameters: {'weight_class_0': 0.604409433108749, 'weight_class_1': 7.6461906814651535, 'weight_class_2': 5.604945082206044}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,572] Trial 588 finished with value: 0.9495849698317927 and parameters: {'weight_class_0': 0.6828997100008962, 'weight_class_1': 7.634381273312217, 'weight_class_2': 6.4845691918943915}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,591] Trial 589 finished with value: 0.949481083153327 and parameters: {'weight_class_0': 0.7783627536146112, 'weight_class_1': 7.673429692672833, 'weight_class_2': 9.56726533725283}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,596] Trial 590 finished with value: 0.9495397029874542 and parameters: {'weight_class_0': 0.7192708605368521, 'weight_class_1': 8.279071358059403, 'weight_class_2': 9.698672371559999}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  20%|██████████████████████████▍                                                                                                         | 600/3000 [00:11<00:46, 51.46it/s]

[I 2026-07-05 15:22:46,609] Trial 591 finished with value: 0.9494040531211576 and parameters: {'weight_class_0': 0.9273551620343995, 'weight_class_1': 7.763068727790085, 'weight_class_2': 8.580025285617515}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,635] Trial 592 finished with value: 0.9493038060677793 and parameters: {'weight_class_0': 0.9992312715708104, 'weight_class_1': 7.493589002063443, 'weight_class_2': 8.579482709135519}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,648] Trial 593 finished with value: 0.949548686042469 and parameters: {'weight_class_0': 0.7571261271226484, 'weight_class_1': 7.476331161575854, 'weight_class_2': 8.726065574328132}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,696] Trial 594 finished with value: 0.9485147309428242 and parameters: {'weight_class_0': 1.1991921719348415, 'weight_class_1': 7.463802849437171, 'weight_class_2': 8.717597813965764}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,698] Trial 596 finished with value: 0.9495526447186514 and parameters: {'weight_class_0': 0.8567042895663799, 'weight_class_1': 8.552823308022923, 'weight_class_2': 9.719249813818365}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,718] Trial 595 finished with value: 0.9494252378169775 and parameters: {'weight_class_0': 0.8795899287659977, 'weight_class_1': 7.409604589749988, 'weight_class_2': 8.703224748280267}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,729] Trial 597 finished with value: 0.9495422753215982 and parameters: {'weight_class_0': 0.7296472240671307, 'weight_class_1': 7.468629296172273, 'weight_class_2': 6.435558568151816}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,755] Trial 598 finished with value: 0.9492844583911669 and parameters: {'weight_class_0': 0.8912728681883505, 'weight_class_1': 7.069623415991356, 'weight_class_2': 9.11051490349628}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,769] Trial 599 finished with value: 0.9489230579804762 and parameters: {'weight_class_0': 1.1238158383631345, 'weight_class_1': 7.360145038928178, 'weight_class_2': 9.09421902879167}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,829] Trial 601 finished with value: 0.9494930112044074 and parameters: {'weight_class_0': 0.7645434855939632, 'weight_class_1': 7.062203040175652, 'weight_class_2': 8.79027428043567}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  20%|██████████████████████████▉                                                                                                         | 611/3000 [00:11<00:44, 53.65it/s]

[I 2026-07-05 15:22:46,839] Trial 600 finished with value: 0.9479608755295527 and parameters: {'weight_class_0': 1.221217965068661, 'weight_class_1': 9.862636385764155, 'weight_class_2': 6.212328663109624}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,865] Trial 602 finished with value: 0.9493903551493306 and parameters: {'weight_class_0': 0.8430727503420667, 'weight_class_1': 6.891563612124561, 'weight_class_2': 8.000642614636705}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,875] Trial 605 finished with value: 0.9493707133612386 and parameters: {'weight_class_0': 0.90218277862047, 'weight_class_1': 7.1619698109647425, 'weight_class_2': 7.6736028907841565}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,879] Trial 604 finished with value: 0.9495798556561307 and parameters: {'weight_class_0': 0.8994924352488036, 'weight_class_1': 9.888902674478995, 'weight_class_2': 7.745453838995478}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,881] Trial 603 finished with value: 0.9496039451886508 and parameters: {'weight_class_0': 0.7084063230337608, 'weight_class_1': 9.597246374311451, 'weight_class_2': 6.471255598164601}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,926] Trial 606 finished with value: 0.9451881855467458 and parameters: {'weight_class_0': 1.6824403386911224, 'weight_class_1': 7.030777051759684, 'weight_class_2': 7.796964813611263}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,931] Trial 607 finished with value: 0.948441612105707 and parameters: {'weight_class_0': 1.0099102745336164, 'weight_class_1': 6.435932134449868, 'weight_class_2': 7.016520531875674}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,942] Trial 608 finished with value: 0.9494980426506721 and parameters: {'weight_class_0': 0.6393457030981685, 'weight_class_1': 6.527494659519811, 'weight_class_2': 6.6676424602777455}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,968] Trial 609 finished with value: 0.9495199407781847 and parameters: {'weight_class_0': 0.6378126961188235, 'weight_class_1': 6.733667976488847, 'weight_class_2': 7.22069079083705}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,982] Trial 611 finished with value: 0.657445406413085 and parameters: {'weight_class_0': 0.002090269190742699, 'weight_class_1': 6.408705914287255, 'weight_class_2': 6.9053632259041375}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:46,990] Trial 610 finished with value: 0.9495984691534222 and parameters: {'weight_class_0': 0.6651457155008191, 'weight_class_1': 9.840653749666401, 'weight_class_2': 6.966261545522914}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  21%|███████████████████████████▍                                                                                                        | 623/3000 [00:12<00:46, 50.70it/s]

[I 2026-07-05 15:22:47,065] Trial 612 finished with value: 0.9495402232968275 and parameters: {'weight_class_0': 0.6418090314522961, 'weight_class_1': 6.353398634152519, 'weight_class_2': 6.2201691660246246}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:47,066] Trial 613 finished with value: 0.949637057483339 and parameters: {'weight_class_0': 0.6281970899904022, 'weight_class_1': 9.732634259586568, 'weight_class_2': 7.060786071381191}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:47,089] Trial 614 finished with value: 0.9495025523638377 and parameters: {'weight_class_0': 0.6066558572603871, 'weight_class_1': 6.282198347192855, 'weight_class_2': 7.252463355124545}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:47,094] Trial 615 finished with value: 0.9495653762497257 and parameters: {'weight_class_0': 0.6525379267618479, 'weight_class_1': 9.982621210461645, 'weight_class_2': 6.864001725647493}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:47,134] Trial 616 finished with value: 0.9495953026726816 and parameters: {'weight_class_0': 0.6385654458371955, 'weight_class_1': 6.993461964349826, 'weight_class_2': 6.98657684326961}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:47,136] Trial 617 finished with value: 0.9494724941372081 and parameters: {'weight_class_0': 0.6499947266342321, 'weight_class_1': 6.276933380404621, 'weight_class_2': 7.010062302526049}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:47,149] Trial 618 finished with value: 0.949495924164966 and parameters: {'weight_class_0': 0.6220327274118335, 'weight_class_1': 6.136077821442856, 'weight_class_2': 6.755433515287713}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:47,173] Trial 619 finished with value: 0.9495470983311763 and parameters: {'weight_class_0': 0.5923866864920779, 'weight_class_1': 6.0382873166924576, 'weight_class_2': 5.34441605589548}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:47,174] Trial 620 finished with value: 0.8992307925069155 and parameters: {'weight_class_0': 0.6083263792143387, 'weight_class_1': 6.3096998603313805, 'weight_class_2': 0.3491902935272035}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:47,181] Trial 621 finished with value: 0.9495278307184963 and parameters: {'weight_class_0': 0.6052453173585036, 'weight_class_1': 6.083201043376887, 'weight_class_2': 5.542268547126153}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:47,229] Trial 622 finished with value: 0.9496514144203472 and parameters: {'weight_class_0': 0.5083172471097626, 'weight_class_1': 6.1710401793335325, 'weight_class_2': 5.431669977875769}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:47,230] Trial 623 finished with value: 0.9496093411884065 and parameters: {'weight_class_0': 0.5417491572197842, 'weight_class_1': 6.141095747643717, 'weight_class_2': 5.630490556789263}. Best is trial 376 with value: 0.9497246321366343.

[I 2026-07-05 15:22:47,281] Trial 624 finished with value: 0.949574423380607 and parameters: {'weight_class_0': 0.4982658198258295, 'weight_class_1': 9.994230321390043, 'weight_class_2': 5.4966636193983796}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:47,321] Trial 625 finished with value: 0.9496122546267752 and parameters: {'weight_class_0': 0.5437652642540411, 'weight_class_1': 9.912723194394399, 'weight_class_2': 5.071849033428754}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:47,323] Trial 626 finished with value: 0.9497107982154898 and parameters: {'weight_class_0': 0.4887806756684216, 'weight_class_1': 6.175307853296159, 'weight_class_2': 5.548845487912123}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:47,341] Trial 627 finished with value: 0.9495571687848412 and parameters: {'weight_class_0': 0.5179247000861678, 'weight_class_1': 9.842670611151021, 'weight_class_2': 5.237786168216854}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:47,351] Trial 628 finished with value: 0.9495551241643522 and parameters: {'weight_class_0': 0.48325706972633653, 'weight_class_1': 9.77139217162406, 'weight_class_2': 5.704885116420331}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:47,364] Trial 629 finished with value: 0.9495623979435673 and parameters: {'weight_class_0': 0.4416833496534238, 'weight_class_1': 8.649404060543944, 'weight_class_2': 5.2675993101420655}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:47,385] Trial 630 finished with value: 0.9496235176862404 and parameters: {'weight_class_0': 0.4470434691033422, 'weight_class_1': 8.457765343319444, 'weight_class_2': 5.136736108033892}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:47,428] Trial 632 finished with value: 0.9495970102752751 and parameters: {'weight_class_0': 0.47764745085722193, 'weight_class_1': 8.024602300049928, 'weight_class_2': 5.376924288890107}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:47,430] Trial 631 finished with value: 0.9496108711765406 and parameters: {'weight_class_0': 0.4657283130573275, 'weight_class_1': 8.163626676567853, 'weight_class_2': 5.318455531829965}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:47,444] Trial 633 finished with value: 0.9495701930731544 and parameters: {'weight_class_0': 0.48518999286690584, 'weight_class_1': 9.845700989711688, 'weight_class_2': 5.38490598359268}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:47,479] Trial 634 finished with value: 0.9495292694706476 and parameters: {'weight_class_0': 0.4852558298919329, 'weight_class_1': 8.276803988839307, 'weight_class_2': 5.044049660739982}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  21%|████████████████████████████▎                                                                                                       | 644/3000 [00:12<00:48, 48.42it/s]

[I 2026-07-05 15:22:47,488] Trial 635 finished with value: 0.9495348008772778 and parameters: {'weight_class_0': 0.4532239107609401, 'weight_class_1': 8.958011896908626, 'weight_class_2': 5.510583141118734}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:47,514] Trial 636 finished with value: 0.949573181256032 and parameters: {'weight_class_0': 0.4512563213763482, 'weight_class_1': 8.70377060476119, 'weight_class_2': 5.578591548053496}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:47,560] Trial 637 finished with value: 0.9495289978393773 and parameters: {'weight_class_0': 0.49903931129551193, 'weight_class_1': 8.705905638649387, 'weight_class_2': 5.128758692038445}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:47,569] Trial 638 finished with value: 0.9495580387493773 and parameters: {'weight_class_0': 0.4219815835359811, 'weight_class_1': 7.681740452839041, 'weight_class_2': 5.354052916865768}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:47,606] Trial 639 finished with value: 0.9495968729973151 and parameters: {'weight_class_0': 0.4763744558727723, 'weight_class_1': 8.158937870663156, 'weight_class_2': 5.4534675797537995}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:47,614] Trial 640 finished with value: 0.6771755688816526 and parameters: {'weight_class_0': 0.7852069158692517, 'weight_class_1': 8.175064725260171, 'weight_class_2': 0.0020276140991057736}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:47,617] Trial 641 finished with value: 0.9496086316939026 and parameters: {'weight_class_0': 0.48363518460446436, 'weight_class_1': 8.176101994741312, 'weight_class_2': 5.346259970053933}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:47,635] Trial 642 finished with value: 0.9491225883447911 and parameters: {'weight_class_0': 0.8155037635451136, 'weight_class_1': 8.00075358733297, 'weight_class_2': 5.807043155357671}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:47,660] Trial 643 finished with value: 0.9486150125751577 and parameters: {'weight_class_0': 0.7532380440838842, 'weight_class_1': 8.146035811413414, 'weight_class_2': 4.227684130239268}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:47,675] Trial 644 finished with value: 0.9494461647982325 and parameters: {'weight_class_0': 0.527341205255538, 'weight_class_1': 7.9055566515606435, 'weight_class_2': 7.71386185624528}. Best is trial 376 with value: 0.9497246321366343.

[I 2026-07-05 15:22:47,693] Trial 645 finished with value: 0.9496353554549671 and parameters: {'weight_class_0': 0.5582147870214206, 'weight_class_1': 7.3578449059910715, 'weight_class_2': 5.987107787521436}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:47,694] Trial 646 finished with value: 0.9494254203840266 and parameters: {'weight_class_0': 0.7626722477832648, 'weight_class_1': 6.654835019956346, 'weight_class_2': 8.248117353406402}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:47,743] Trial 647 finished with value: 0.9213902985281691 and parameters: {'weight_class_0': 0.5561914398842892, 'weight_class_1': 7.091809129369161, 'weight_class_2': 0.7396607014906474}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:47,754] Trial 648 finished with value: 0.7277813171582985 and parameters: {'weight_class_0': 0.5492031426450389, 'weight_class_1': 7.064522400969598, 'weight_class_2': 0.005627346700363648}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:47,799] Trial 649 finished with value: 0.9478312444267621 and parameters: {'weight_class_0': 0.8140603671695712, 'weight_class_1': 5.988871363798848, 'weight_class_2': 4.14673960464951}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:47,821] Trial 650 finished with value: 0.9493082658814344 and parameters: {'weight_class_0': 0.5610339462100766, 'weight_class_1': 6.056892169748421, 'weight_class_2': 8.078430683596679}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  22%|████████████████████████████▋                                                                                                       | 652/3000 [00:12<00:48, 48.84it/s]

[I 2026-07-05 15:22:47,830] Trial 651 finished with value: 0.947778138504957 and parameters: {'weight_class_0': 0.8202283979003913, 'weight_class_1': 6.2561681122751835, 'weight_class_2': 4.125006056696563}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:47,845] Trial 652 finished with value: 0.9489361855378259 and parameters: {'weight_class_0': 0.5767574615619222, 'weight_class_1': 6.244344665781831, 'weight_class_2': 9.89176088123625}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  22%|████████████████████████████▊                                                                                                       | 654/3000 [00:12<00:48, 48.84it/s]

[I 2026-07-05 15:22:47,871] Trial 654 finished with value: 0.9491937820777067 and parameters: {'weight_class_0': 0.6034421563380774, 'weight_class_1': 6.100595070253782, 'weight_class_2': 4.365457375876615}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:47,889] Trial 653 finished with value: 0.9490318278332612 and parameters: {'weight_class_0': 0.4057786962412878, 'weight_class_1': 6.442313412554787, 'weight_class_2': 7.351454215034588}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  22%|████████████████████████████▊                                                                                                       | 655/3000 [00:12<00:50, 46.28it/s]

[I 2026-07-05 15:22:47,928] Trial 655 finished with value: 0.9490723689791779 and parameters: {'weight_class_0': 0.5899615515671902, 'weight_class_1': 5.906858301163507, 'weight_class_2': 4.081223906763118}. Best is trial 376 with value: 0.9497246321366343.

[I 2026-07-05 15:22:47,946] Trial 656 finished with value: 0.9490373917807368 and parameters: {'weight_class_0': 0.5864555534299059, 'weight_class_1': 6.396962941004063, 'weight_class_2': 3.9192843812500735}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:47,967] Trial 657 finished with value: 0.9495881023600629 and parameters: {'weight_class_0': 0.4016079044293823, 'weight_class_1': 5.8619209593914805, 'weight_class_2': 4.168200129602458}. Best is trial 376 with value: 0.9497246321366343.

[I 2026-07-05 15:22:48,003] Trial 658 finished with value: 0.9457035726797804 and parameters: {'weight_class_0': 1.031494367300266, 'weight_class_1': 5.785448288816614, 'weight_class_2': 4.212253977059192}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:48,009] Trial 659 finished with value: 0.9491192017389344 and parameters: {'weight_class_0': 0.23910974589579534, 'weight_class_1': 5.319151000277952, 'weight_class_2': 4.028051626511321}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  22%|█████████████████████████████▏                                                                                                      | 662/3000 [00:13<00:50, 45.97it/s]

[I 2026-07-05 15:22:48,026] Trial 660 finished with value: 0.9457341922515793 and parameters: {'weight_class_0': 1.0223393221411654, 'weight_class_1': 5.674779784259493, 'weight_class_2': 4.2111017248875}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:48,066] Trial 662 finished with value: 0.9491290457248848 and parameters: {'weight_class_0': 0.4224833602051141, 'weight_class_1': 5.392083255077996, 'weight_class_2': 7.250616746917469}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:48,076] Trial 661 finished with value: 0.8854739659108198 and parameters: {'weight_class_0': 1.0625323833754932, 'weight_class_1': 5.268467496985258, 'weight_class_2': 0.08839673487439594}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  22%|█████████████████████████████▏                                                                                                      | 664/3000 [00:13<00:50, 45.97it/s]

[I 2026-07-05 15:22:48,095] Trial 663 finished with value: 0.948062737925368 and parameters: {'weight_class_0': 0.23484214811878212, 'weight_class_1': 4.949913715024703, 'weight_class_2': 6.980185925557189}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:48,097] Trial 664 finished with value: 0.949197923658253 and parameters: {'weight_class_0': 0.22813441979335777, 'weight_class_1': 2.6780444154640004, 'weight_class_2': 3.695955725367589}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  22%|█████████████████████████████▎                                                                                                      | 665/3000 [00:13<00:50, 46.22it/s]

[I 2026-07-05 15:22:48,138] Trial 665 finished with value: 0.8884163491418468 and parameters: {'weight_class_0': 0.2370570191490496, 'weight_class_1': 0.06506711381651972, 'weight_class_2': 3.8486571773149763}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  22%|█████████████████████████████▎                                                                                                      | 667/3000 [00:13<00:50, 46.22it/s]

[I 2026-07-05 15:22:48,168] Trial 666 finished with value: 0.9479192562835553 and parameters: {'weight_class_0': 0.21330504637781725, 'weight_class_1': 4.866450756366397, 'weight_class_2': 6.673959718917923}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:48,185] Trial 667 finished with value: 0.9481478571571126 and parameters: {'weight_class_0': 0.22087760021495595, 'weight_class_1': 5.035762292018009, 'weight_class_2': 6.25849786999087}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  22%|█████████████████████████████▍                                                                                                      | 669/3000 [00:13<00:50, 46.22it/s]

[I 2026-07-05 15:22:48,211] Trial 668 finished with value: 0.90574295419645 and parameters: {'weight_class_0': 0.21630812290111956, 'weight_class_1': 0.14377719394739935, 'weight_class_2': 6.976928169736753}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:48,240] Trial 669 finished with value: 0.8919378462464594 and parameters: {'weight_class_0': 0.23116070834568547, 'weight_class_1': 3.740509587969498, 'weight_class_2': 0.05101095875011228}. Best is trial 376 with value: 0.9497246321366343.

[I 2026-07-05 15:22:48,257] Trial 670 finished with value: 0.9478653209551999 and parameters: {'weight_class_0': 0.19717278242531638, 'weight_class_1': 3.886452951691527, 'weight_class_2': 6.479540433926264}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:48,282] Trial 672 finished with value: 0.947857632186263 and parameters: {'weight_class_0': 0.21360968253757132, 'weight_class_1': 2.950482449708387, 'weight_class_2': 6.349171312132437}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  22%|█████████████████████████████▌                                                                                                      | 673/3000 [00:13<00:50, 45.76it/s]

[I 2026-07-05 15:22:48,319] Trial 671 finished with value: 0.9495018477934641 and parameters: {'weight_class_0': 0.21359147978327633, 'weight_class_1': 3.8938598637407336, 'weight_class_2': 2.9657455768710475}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:48,321] Trial 673 finished with value: 0.8409179725793406 and parameters: {'weight_class_0': 9.741598987677332, 'weight_class_1': 3.8450040243914225, 'weight_class_2': 2.939549734249877}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  22%|█████████████████████████████▋                                                                                                      | 675/3000 [00:13<00:52, 44.39it/s]

[I 2026-07-05 15:22:48,345] Trial 674 finished with value: 0.947718227128347 and parameters: {'weight_class_0': 0.19699213140663077, 'weight_class_1': 2.9013792173303363, 'weight_class_2': 6.267830466405369}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:48,361] Trial 675 finished with value: 0.9485419448830833 and parameters: {'weight_class_0': 0.4015097978798264, 'weight_class_1': 2.8848672003321725, 'weight_class_2': 6.546377623621644}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  23%|█████████████████████████████▊                                                                                                      | 677/3000 [00:13<00:52, 44.39it/s]

[I 2026-07-05 15:22:48,391] Trial 676 finished with value: 0.9491487258210709 and parameters: {'weight_class_0': 0.39670708672813215, 'weight_class_1': 3.849007565469504, 'weight_class_2': 2.87568121538354}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:48,397] Trial 677 finished with value: 0.949016109858673 and parameters: {'weight_class_0': 0.3873781313868357, 'weight_class_1': 2.94559286034284, 'weight_class_2': 2.880056350577191}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  23%|█████████████████████████████▊                                                                                                      | 678/3000 [00:13<00:52, 44.39it/s]

[I 2026-07-05 15:22:48,440] Trial 678 finished with value: 0.949289796071264 and parameters: {'weight_class_0': 0.40300688800585877, 'weight_class_1': 3.818755810470761, 'weight_class_2': 3.1030824118075753}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  23%|█████████████████████████████▉                                                                                                      | 681/3000 [00:13<00:51, 45.44it/s]

[I 2026-07-05 15:22:48,462] Trial 679 finished with value: 0.9493417960977423 and parameters: {'weight_class_0': 0.40964960168722153, 'weight_class_1': 3.9474929653075113, 'weight_class_2': 3.187352038040653}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:48,488] Trial 680 finished with value: 0.9488189168533315 and parameters: {'weight_class_0': 0.4084621143413864, 'weight_class_1': 2.972541465300572, 'weight_class_2': 2.862606212304622}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:48,514] Trial 681 finished with value: 0.9490663273218801 and parameters: {'weight_class_0': 0.4017885334118223, 'weight_class_1': 9.989897262693699, 'weight_class_2': 2.988648266102021}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  23%|██████████████████████████████                                                                                                      | 683/3000 [00:13<00:50, 45.44it/s]

[I 2026-07-05 15:22:48,519] Trial 682 finished with value: 0.9494267570852735 and parameters: {'weight_class_0': 0.3935124647343027, 'weight_class_1': 4.172963194037779, 'weight_class_2': 3.1118299923977375}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:48,534] Trial 683 finished with value: 0.9492328520951947 and parameters: {'weight_class_0': 0.3825791670965371, 'weight_class_1': 2.7668787042192564, 'weight_class_2': 3.154602357715899}. Best is trial 376 with value: 0.9497246321366343.

[I 2026-07-05 15:22:48,567] Trial 684 finished with value: 0.9463605689679949 and parameters: {'weight_class_0': 0.13543824242366345, 'weight_class_1': 7.180554554715479, 'weight_class_2': 3.3555252014780175}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:48,575] Trial 685 finished with value: 0.9468345373574386 and parameters: {'weight_class_0': 0.7378075985713755, 'weight_class_1': 4.492115586271328, 'weight_class_2': 3.3511428068058704}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  23%|██████████████████████████████▏                                                                                                     | 687/3000 [00:13<00:50, 45.93it/s]

[I 2026-07-05 15:22:48,625] Trial 686 finished with value: 0.9411197339397761 and parameters: {'weight_class_0': 0.7049060926067527, 'weight_class_1': 1.7605252795694286, 'weight_class_2': 9.965313616895264}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:48,656] Trial 687 finished with value: 0.9494579036974944 and parameters: {'weight_class_0': 0.32727030179738803, 'weight_class_1': 7.278308454076056, 'weight_class_2': 3.424837488428509}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  23%|██████████████████████████████▍                                                                                                     | 691/3000 [00:13<00:51, 45.19it/s]

[I 2026-07-05 15:22:48,663] Trial 688 finished with value: 0.9470429976137672 and parameters: {'weight_class_0': 0.735250428377859, 'weight_class_1': 4.554706491685976, 'weight_class_2': 3.477858764310717}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:48,685] Trial 689 finished with value: 0.9493244891048954 and parameters: {'weight_class_0': 0.711599466353753, 'weight_class_1': 7.176477875218447, 'weight_class_2': 9.892035283126328}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:48,706] Trial 690 finished with value: 0.9479480269319535 and parameters: {'weight_class_0': 0.32217174389578374, 'weight_class_1': 7.098434948933231, 'weight_class_2': 9.964332283786698}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:48,734] Trial 692 finished with value: 0.9492011499408219 and parameters: {'weight_class_0': 0.3054730448137027, 'weight_class_1': 6.837566784196636, 'weight_class_2': 4.812901506174724}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  23%|██████████████████████████████▍                                                                                                     | 692/3000 [00:13<00:51, 45.19it/s]

[I 2026-07-05 15:22:48,764] Trial 693 finished with value: 0.9490807243159227 and parameters: {'weight_class_0': 0.3115617363140842, 'weight_class_1': 7.675725513190402, 'weight_class_2': 4.929733724488783}. Best is trial 376 with value: 0.9497246321366343.

[I 2026-07-05 15:22:48,768] Trial 691 finished with value: 0.946015827888742 and parameters: {'weight_class_0': 0.13957840541769703, 'weight_class_1': 7.218955636127473, 'weight_class_2': 4.730763840007321}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:48,794] Trial 694 finished with value: 0.949268078981882 and parameters: {'weight_class_0': 0.3203792579637992, 'weight_class_1': 7.057234752784376, 'weight_class_2': 4.842709930582413}. Best is trial 376 with value: 0.9497246321366343.

[I 2026-07-05 15:22:48,798] Trial 695 finished with value: 0.9487710640270337 and parameters: {'weight_class_0': 0.7130523498668295, 'weight_class_1': 6.886427419875016, 'weight_class_2': 4.453072129848315}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:48,861] Trial 697 finished with value: 0.9491866580414374 and parameters: {'weight_class_0': 0.3129173406354351, 'weight_class_1': 7.349671322687447, 'weight_class_2': 4.745496839810705}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:48,872] Trial 696 finished with value: 0.949249768403332 and parameters: {'weight_class_0': 0.3284768247794143, 'weight_class_1': 7.582676775458499, 'weight_class_2': 4.734110758369385}. Best is trial 376 with value: 0.9497246321366343.

[I 2026-07-05 15:22:48,885] Trial 698 finished with value: 0.9492444764076171 and parameters: {'weight_class_0': 0.31167016856857455, 'weight_class_1': 7.17813519594075, 'weight_class_2': 4.539735012421049}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:48,921] Trial 699 finished with value: 0.9488325050929646 and parameters: {'weight_class_0': 0.2649600609141762, 'weight_class_1': 7.117682432037352, 'weight_class_2': 4.63440855981795}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:48,930] Trial 700 finished with value: 0.9486536018007254 and parameters: {'weight_class_0': 0.26756059160711737, 'weight_class_1': 2.2540358377841976, 'weight_class_2': 4.596075616305272}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:48,933] Trial 701 finished with value: 0.9491210801226079 and parameters: {'weight_class_0': 0.27041989862784527, 'weight_class_1': 5.163850527439214, 'weight_class_2': 4.806429821061646}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:48,964] Trial 702 finished with value: 0.9490672994352648 and parameters: {'weight_class_0': 0.26641817163834236, 'weight_class_1': 4.8380178209334135, 'weight_class_2': 4.783196029432486}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  23%|██████████████████████████████▉                                                                                                     | 703/3000 [00:13<00:48, 47.06it/s]

[I 2026-07-05 15:22:48,982] Trial 703 finished with value: 0.9481428581054754 and parameters: {'weight_class_0': 0.25816885752820057, 'weight_class_1': 9.985288428804653, 'weight_class_2': 4.755270619193802}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  24%|███████████████████████████████                                                                                                     | 705/3000 [00:13<00:48, 47.06it/s]

[I 2026-07-05 15:22:49,013] Trial 704 finished with value: 0.9486476757765835 and parameters: {'weight_class_0': 0.26369646177170863, 'weight_class_1': 4.628597986119785, 'weight_class_2': 5.873048957115719}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:49,037] Trial 705 finished with value: 0.9489084054599891 and parameters: {'weight_class_0': 0.5071639800371163, 'weight_class_1': 4.820186550148646, 'weight_class_2': 8.345761846363619}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  24%|███████████████████████████████                                                                                                     | 707/3000 [00:14<00:49, 46.54it/s]

[I 2026-07-05 15:22:49,070] Trial 707 finished with value: 0.9482071941072534 and parameters: {'weight_class_0': 0.5123675143900206, 'weight_class_1': 4.908599597694662, 'weight_class_2': 2.6280562402104173}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:49,077] Trial 706 finished with value: 0.9479359966735804 and parameters: {'weight_class_0': 0.261083509750174, 'weight_class_1': 4.685028704148384, 'weight_class_2': 8.0325413272523}. Best is trial 376 with value: 0.9497246321366343.

[I 2026-07-05 15:22:49,113] Trial 708 finished with value: 0.9488995725330431 and parameters: {'weight_class_0': 0.5057375340456, 'weight_class_1': 4.686563315237449, 'weight_class_2': 8.283197409355548}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:49,129] Trial 709 finished with value: 0.7337049508065422 and parameters: {'weight_class_0': 0.5220501170516928, 'weight_class_1': 0.004059404645900563, 'weight_class_2': 3.886193300538032}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:49,134] Trial 710 finished with value: 0.9478626558620059 and parameters: {'weight_class_0': 0.5424389937843791, 'weight_class_1': 4.924709706259497, 'weight_class_2': 2.5754570772288385}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:49,176] Trial 711 finished with value: 0.9479964898476299 and parameters: {'weight_class_0': 0.5288027687894586, 'weight_class_1': 4.825671378391685, 'weight_class_2': 2.596028437667261}. Best is trial 376 with value: 0.9497246321366343.

[I 2026-07-05 15:22:49,197] Trial 713 finished with value: 0.9496156874936998 and parameters: {'weight_class_0': 0.5311074704707205, 'weight_class_1': 9.99318575734804, 'weight_class_2': 6.052441545040478}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  24%|███████████████████████████████▍                                                                                                    | 715/3000 [00:14<00:49, 46.23it/s]

[I 2026-07-05 15:22:49,205] Trial 712 finished with value: 0.9490385758186463 and parameters: {'weight_class_0': 0.5090720641753369, 'weight_class_1': 4.78246458388015, 'weight_class_2': 7.862199224246096}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:49,212] Trial 714 finished with value: 0.9472019690367152 and parameters: {'weight_class_0': 0.5755428000527082, 'weight_class_1': 4.773378424455762, 'weight_class_2': 2.5226410471662826}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:49,226] Trial 715 finished with value: 0.9491078621231891 and parameters: {'weight_class_0': 0.5256181896888064, 'weight_class_1': 5.672598937937341, 'weight_class_2': 3.6861018852112926}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  24%|███████████████████████████████▌                                                                                                    | 718/3000 [00:14<00:49, 46.30it/s]

[I 2026-07-05 15:22:49,257] Trial 716 finished with value: 0.895538285855901 and parameters: {'weight_class_0': 0.5542308718675854, 'weight_class_1': 5.652473103598611, 'weight_class_2': 0.19647159194852792}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:49,282] Trial 717 finished with value: 0.6556765405812249 and parameters: {'weight_class_0': 0.5452795405312311, 'weight_class_1': 0.0014863496054215038, 'weight_class_2': 2.4786886002685007}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:49,325] Trial 718 finished with value: 0.9491732113127774 and parameters: {'weight_class_0': 0.45834755026354823, 'weight_class_1': 3.4878936746688916, 'weight_class_2': 3.6360935510936208}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  24%|███████████████████████████████▋                                                                                                    | 721/3000 [00:14<00:49, 46.30it/s]

[I 2026-07-05 15:22:49,350] Trial 719 finished with value: 0.9471586235129164 and parameters: {'weight_class_0': 0.5914100231914704, 'weight_class_1': 5.946298229385034, 'weight_class_2': 2.5192126673992696}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:49,352] Trial 720 finished with value: 0.8850795355922663 and parameters: {'weight_class_0': 0.4501008267046849, 'weight_class_1': 3.4244296701268095, 'weight_class_2': 0.036561922683063304}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:49,380] Trial 721 finished with value: 0.943565843859241 and parameters: {'weight_class_0': 0.08878499005214882, 'weight_class_1': 5.92342871031107, 'weight_class_2': 3.6295558074179777}. Best is trial 376 with value: 0.9497246321366343.

[I 2026-07-05 15:22:49,403] Trial 722 finished with value: 0.9496132243749053 and parameters: {'weight_class_0': 0.47175882843941913, 'weight_class_1': 6.0502074309182605, 'weight_class_2': 3.820744858181712}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:49,427] Trial 723 finished with value: 0.9494415822859805 and parameters: {'weight_class_0': 0.44909586261654905, 'weight_class_1': 9.960370650413322, 'weight_class_2': 3.7689046326964664}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  24%|███████████████████████████████▉                                                                                                    | 725/3000 [00:14<00:48, 47.01it/s]

[I 2026-07-05 15:22:49,441] Trial 725 finished with value: 0.9493033234578997 and parameters: {'weight_class_0': 0.4527172106210168, 'weight_class_1': 3.3884847400589555, 'weight_class_2': 3.8540101008876233}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:49,458] Trial 724 finished with value: 0.9493488501938829 and parameters: {'weight_class_0': 0.4428886528095686, 'weight_class_1': 3.488525916805728, 'weight_class_2': 3.7885412132343586}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  24%|████████████████████████████████                                                                                                    | 728/3000 [00:14<00:47, 47.51it/s]

[I 2026-07-05 15:22:49,495] Trial 727 finished with value: 0.949338736579004 and parameters: {'weight_class_0': 0.4202838784672874, 'weight_class_1': 3.3970903758859703, 'weight_class_2': 3.736294981289112}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:49,499] Trial 726 finished with value: 0.9494787287696761 and parameters: {'weight_class_0': 0.432764619632429, 'weight_class_1': 3.700626414437811, 'weight_class_2': 3.649837713549198}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:49,528] Trial 728 finished with value: 0.9494722766717733 and parameters: {'weight_class_0': 0.35874905027921383, 'weight_class_1': 3.509744977951087, 'weight_class_2': 3.6468019081055996}. Best is trial 376 with value: 0.9497246321366343.

[I 2026-07-05 15:22:49,580] Trial 729 finished with value: 0.9494995318037512 and parameters: {'weight_class_0': 0.37138082431518565, 'weight_class_1': 3.3824939388607422, 'weight_class_2': 3.6257023182552013}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:49,584] Trial 730 finished with value: 0.9494813392974829 and parameters: {'weight_class_0': 0.3462728319551973, 'weight_class_1': 3.330198050419291, 'weight_class_2': 3.6868997439051925}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:49,597] Trial 731 finished with value: 0.9493343049327474 and parameters: {'weight_class_0': 0.3361535620056031, 'weight_class_1': 8.563377788274876, 'weight_class_2': 3.6270109921845575}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  24%|████████████████████████████████▎                                                                                                   | 733/3000 [00:14<00:48, 47.15it/s]

[I 2026-07-05 15:22:49,611] Trial 732 finished with value: 0.9196316406512662 and parameters: {'weight_class_0': 0.34036398937042794, 'weight_class_1': 0.3695188629957989, 'weight_class_2': 5.560827293178991}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:49,635] Trial 733 finished with value: 0.9490121153975645 and parameters: {'weight_class_0': 0.35078296357237754, 'weight_class_1': 8.738866948900634, 'weight_class_2': 5.8604794806132325}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  25%|████████████████████████████████▍                                                                                                   | 736/3000 [00:14<00:48, 47.15it/s]

[I 2026-07-05 15:22:49,663] Trial 734 finished with value: 0.9488567849129189 and parameters: {'weight_class_0': 0.3386208987555384, 'weight_class_1': 8.39581675535994, 'weight_class_2': 6.07670806226334}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:49,664] Trial 735 finished with value: 0.949188195202662 and parameters: {'weight_class_0': 0.37275286557980936, 'weight_class_1': 8.334869546859512, 'weight_class_2': 5.945015215528453}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:49,677] Trial 736 finished with value: 0.9484347646561586 and parameters: {'weight_class_0': 0.3410600703046354, 'weight_class_1': 2.374730456928382, 'weight_class_2': 5.591641129101407}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  25%|████████████████████████████████▌                                                                                                   | 740/3000 [00:14<00:45, 49.52it/s]

[I 2026-07-05 15:22:49,681] Trial 737 finished with value: 0.9489375297307237 and parameters: {'weight_class_0': 0.3430265380522972, 'weight_class_1': 8.544951629164073, 'weight_class_2': 5.9655540279076655}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:49,714] Trial 738 finished with value: 0.9489826666888175 and parameters: {'weight_class_0': 0.35360074742231795, 'weight_class_1': 8.320209142541703, 'weight_class_2': 6.067213390220032}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:49,753] Trial 739 finished with value: 0.6983532365135986 and parameters: {'weight_class_0': 0.3444464129156098, 'weight_class_1': 8.392301467533512, 'weight_class_2': 0.0029393386402070936}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:49,768] Trial 740 finished with value: 0.9491329239718258 and parameters: {'weight_class_0': 0.363456831459692, 'weight_class_1': 8.335466782750093, 'weight_class_2': 5.8970973419621044}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  25%|████████████████████████████████▋                                                                                                   | 742/3000 [00:14<00:45, 49.52it/s]

[I 2026-07-05 15:22:49,805] Trial 741 finished with value: 0.9455398151956613 and parameters: {'weight_class_0': 0.673539167960481, 'weight_class_1': 2.3270028271918592, 'weight_class_2': 6.042053558335018}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:49,815] Trial 743 finished with value: 0.9460207127240446 and parameters: {'weight_class_0': 0.6578013693700969, 'weight_class_1': 2.4009139843835685, 'weight_class_2': 5.577683757175055}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  25%|████████████████████████████████▋                                                                                                   | 744/3000 [00:14<00:46, 48.89it/s]

[I 2026-07-05 15:22:49,818] Trial 742 finished with value: 0.9452606159187198 and parameters: {'weight_class_0': 0.6719468204106575, 'weight_class_1': 2.272544436476901, 'weight_class_2': 5.647794798415714}. Best is trial 376 with value: 0.9497246321366343.

[I 2026-07-05 15:22:49,873] Trial 745 finished with value: 0.9372525822123169 and parameters: {'weight_class_0': 0.8777487681401579, 'weight_class_1': 2.306892814765459, 'weight_class_2': 2.9185088296736654}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:49,906] Trial 744 finished with value: 0.9394263389832092 and parameters: {'weight_class_0': 0.6462888420323682, 'weight_class_1': 2.280604478424735, 'weight_class_2': 1.9155735724555378}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  25%|█████████████████████████████████                                                                                                   | 751/3000 [00:14<00:48, 46.83it/s]

[I 2026-07-05 15:22:49,910] Trial 747 finished with value: 0.9422768597557954 and parameters: {'weight_class_0': 0.6970453706064972, 'weight_class_1': 5.88600873554188, 'weight_class_2': 1.9534654578049229}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:49,911] Trial 746 finished with value: 0.9492970632579957 and parameters: {'weight_class_0': 0.27262234406285674, 'weight_class_1': 5.771909316527789, 'weight_class_2': 2.0954007268992743}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:49,942] Trial 748 finished with value: 0.9422449111795282 and parameters: {'weight_class_0': 0.664566239818894, 'weight_class_1': 5.810107702912173, 'weight_class_2': 1.850212896438336}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:49,958] Trial 749 finished with value: 0.9468971611742556 and parameters: {'weight_class_0': 0.6843513777599507, 'weight_class_1': 5.993940531379056, 'weight_class_2': 2.853728711113689}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:49,980] Trial 752 finished with value: 0.9473617371014251 and parameters: {'weight_class_0': 0.6599671620374612, 'weight_class_1': 5.87705251420435, 'weight_class_2': 2.8914238662056557}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:49,984] Trial 750 finished with value: 0.9364769583688438 and parameters: {'weight_class_0': 0.8680459683352207, 'weight_class_1': 5.75617549443447, 'weight_class_2': 1.9029675531383503}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  25%|█████████████████████████████████▏                                                                                                  | 753/3000 [00:14<00:47, 46.83it/s]

[I 2026-07-05 15:22:50,011] Trial 751 finished with value: 0.9421536165901285 and parameters: {'weight_class_0': 0.6493770444850354, 'weight_class_1': 5.9181875569092925, 'weight_class_2': 1.7963814940407374}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:50,028] Trial 753 finished with value: 0.9349981847478498 and parameters: {'weight_class_0': 0.8766679926041044, 'weight_class_1': 5.683923643703716, 'weight_class_2': 1.837187256780283}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  25%|█████████████████████████████████▏                                                                                                  | 755/3000 [00:15<00:47, 46.83it/s]

[I 2026-07-05 15:22:50,036] Trial 754 finished with value: 0.9443220380291645 and parameters: {'weight_class_0': 0.8644772679282945, 'weight_class_1': 6.052458895078209, 'weight_class_2': 2.8513470674609676}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:50,052] Trial 755 finished with value: 0.9486006883372458 and parameters: {'weight_class_0': 0.17334479769404237, 'weight_class_1': 6.133719337627275, 'weight_class_2': 2.821570025800194}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  25%|█████████████████████████████████▎                                                                                                  | 756/3000 [00:15<00:44, 50.00it/s]

[I 2026-07-05 15:22:50,112] Trial 756 finished with value: 0.9489886615658069 and parameters: {'weight_class_0': 0.17877223337683393, 'weight_class_1': 5.9251550175545775, 'weight_class_2': 1.9294644199060744}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  25%|█████████████████████████████████▍                                                                                                  | 760/3000 [00:15<00:44, 50.00it/s]

[I 2026-07-05 15:22:50,132] Trial 757 finished with value: 0.9493482872295651 and parameters: {'weight_class_0': 0.19185892993856285, 'weight_class_1': 3.9982451219807977, 'weight_class_2': 2.879579574736651}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:50,160] Trial 758 finished with value: 0.949286759803508 and parameters: {'weight_class_0': 0.18487924511480502, 'weight_class_1': 4.177458883266922, 'weight_class_2': 2.7268034033922426}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:50,192] Trial 759 finished with value: 0.949158165140974 and parameters: {'weight_class_0': 0.1828039545306159, 'weight_class_1': 4.278699758691726, 'weight_class_2': 2.821583500487596}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:50,207] Trial 761 finished with value: 0.946946430507945 and parameters: {'weight_class_0': 0.1772967102125631, 'weight_class_1': 4.378122046889835, 'weight_class_2': 8.161758633593518}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  25%|█████████████████████████████████▌                                                                                                  | 762/3000 [00:15<00:49, 44.94it/s]

[I 2026-07-05 15:22:50,208] Trial 762 finished with value: 0.9470867496472314 and parameters: {'weight_class_0': 0.17672706343436412, 'weight_class_1': 4.046304997407385, 'weight_class_2': 7.777202720646606}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:50,209] Trial 760 finished with value: 0.9469634001570878 and parameters: {'weight_class_0': 0.1741058990491551, 'weight_class_1': 4.15213648213336, 'weight_class_2': 7.972488831118235}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  26%|█████████████████████████████████▋                                                                                                  | 765/3000 [00:15<00:49, 44.94it/s]

[I 2026-07-05 15:22:50,238] Trial 763 finished with value: 0.949182179783172 and parameters: {'weight_class_0': 0.2603959248444597, 'weight_class_1': 4.293043899461506, 'weight_class_2': 4.388521888941124}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:50,286] Trial 764 finished with value: 0.9492883408300955 and parameters: {'weight_class_0': 0.26068692234701374, 'weight_class_1': 4.354178702028343, 'weight_class_2': 4.333006994280038}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:50,292] Trial 765 finished with value: 0.8003572251442962 and parameters: {'weight_class_0': 0.18903171162914986, 'weight_class_1': 0.008448521318089784, 'weight_class_2': 7.943088340267863}. Best is trial 376 with value: 0.9497246321366343.

[I 2026-07-05 15:22:50,298] Trial 766 finished with value: 0.94843033426906 and parameters: {'weight_class_0': 0.1825466030570018, 'weight_class_1': 4.101438703821213, 'weight_class_2': 4.4595807988830165}. Best is trial 376 with value: 0.9497246321366343.

[I 2026-07-05 15:22:50,328] Trial 767 finished with value: 0.9478962054325385 and parameters: {'weight_class_0': 0.25299932342404774, 'weight_class_1': 4.218728598110741, 'weight_class_2': 7.857741235014935}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:50,333] Trial 768 finished with value: 0.9478836839674698 and parameters: {'weight_class_0': 0.25298074434961193, 'weight_class_1': 3.9459248787408274, 'weight_class_2': 7.673772728863272}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:50,362] Trial 769 finished with value: 0.9480896221024074 and parameters: {'weight_class_0': 0.2597294048470785, 'weight_class_1': 4.192238444481345, 'weight_class_2': 7.40095701835073}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:50,383] Trial 771 finished with value: 0.948087572529329 and parameters: {'weight_class_0': 0.25390386621660954, 'weight_class_1': 4.1236244159614515, 'weight_class_2': 7.212887631099911}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:50,388] Trial 770 finished with value: 0.9479592149080694 and parameters: {'weight_class_0': 0.2528837152319505, 'weight_class_1': 4.101068379293654, 'weight_class_2': 7.597961645652533}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  26%|██████████████████████████████████                                                                                                  | 773/3000 [00:15<00:45, 48.56it/s]

[I 2026-07-05 15:22:50,433] Trial 772 finished with value: 0.9489555222991771 and parameters: {'weight_class_0': 0.2619187999691076, 'weight_class_1': 7.325497221839429, 'weight_class_2': 4.235681473461349}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:50,453] Trial 773 finished with value: 0.833557065691345 and parameters: {'weight_class_0': 0.24921694080227777, 'weight_class_1': 0.007667444972018281, 'weight_class_2': 4.381692382828894}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  26%|██████████████████████████████████                                                                                                  | 775/3000 [00:15<00:45, 48.56it/s]

[I 2026-07-05 15:22:50,481] Trial 774 finished with value: 0.9489439625534634 and parameters: {'weight_class_0': 0.25463420682814825, 'weight_class_1': 7.185711299746874, 'weight_class_2': 4.213678550966307}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:50,519] Trial 777 finished with value: 0.9493619672341262 and parameters: {'weight_class_0': 0.27385212100728107, 'weight_class_1': 6.939363083936416, 'weight_class_2': 3.2428359864606744}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  26%|██████████████████████████████████▏                                                                                                 | 776/3000 [00:15<00:45, 48.56it/s]

[I 2026-07-05 15:22:50,523] Trial 776 finished with value: 0.9492435936750233 and parameters: {'weight_class_0': 0.25412796247473723, 'weight_class_1': 7.023360541648664, 'weight_class_2': 2.3447548030658596}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  26%|██████████████████████████████████▎                                                                                                 | 781/3000 [00:15<00:46, 47.41it/s]

[I 2026-07-05 15:22:50,531] Trial 775 finished with value: 0.9485971480561064 and parameters: {'weight_class_0': 0.2552935200286295, 'weight_class_1': 9.95337069844695, 'weight_class_2': 3.449733273356358}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:50,576] Trial 778 finished with value: 0.9493903229594262 and parameters: {'weight_class_0': 0.28181801747776997, 'weight_class_1': 7.095200312409405, 'weight_class_2': 3.2918459076573834}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:50,590] Trial 781 finished with value: 0.9487516296809734 and parameters: {'weight_class_0': 0.4152155615384811, 'weight_class_1': 7.012025661089066, 'weight_class_2': 2.4286254479749667}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:50,596] Trial 779 finished with value: 0.9495577224583643 and parameters: {'weight_class_0': 0.4194832547461598, 'weight_class_1': 6.9848220980611435, 'weight_class_2': 3.3643151230779837}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:50,603] Trial 780 finished with value: 0.934105209770037 and parameters: {'weight_class_0': 1.1627651968536978, 'weight_class_1': 7.423856309467206, 'weight_class_2': 2.362258759715086}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  26%|██████████████████████████████████▍                                                                                                 | 783/3000 [00:15<00:46, 47.93it/s]

[I 2026-07-05 15:22:50,641] Trial 782 finished with value: 0.9492978154996655 and parameters: {'weight_class_0': 0.4507826399892492, 'weight_class_1': 7.156943010192588, 'weight_class_2': 3.2839900188822746}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:50,663] Trial 783 finished with value: 0.9485697092205329 and parameters: {'weight_class_0': 0.4351574875732503, 'weight_class_1': 7.056255169958918, 'weight_class_2': 2.392625498465442}. Best is trial 376 with value: 0.9497246321366343.

[I 2026-07-05 15:22:50,698] Trial 785 finished with value: 0.949497225528181 and parameters: {'weight_class_0': 0.41416318765902205, 'weight_class_1': 6.973483486998021, 'weight_class_2': 3.2493073236516565}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:50,699] Trial 784 finished with value: 0.9485329772182984 and parameters: {'weight_class_0': 0.41289494700100254, 'weight_class_1': 7.026216432864041, 'weight_class_2': 2.2779591856349417}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  26%|██████████████████████████████████▌                                                                                                 | 786/3000 [00:15<00:46, 47.93it/s]

[I 2026-07-05 15:22:50,738] Trial 786 finished with value: 0.949324010333795 and parameters: {'weight_class_0': 0.445817260263689, 'weight_class_1': 6.818216377250104, 'weight_class_2': 3.2913161852484074}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  26%|██████████████████████████████████▊                                                                                                 | 791/3000 [00:15<00:46, 47.25it/s]

[I 2026-07-05 15:22:50,739] Trial 787 finished with value: 0.9489150554552012 and parameters: {'weight_class_0': 0.43141700633690766, 'weight_class_1': 2.962240022708855, 'weight_class_2': 5.3004852439699475}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:50,786] Trial 788 finished with value: 0.9485872502826004 and parameters: {'weight_class_0': 0.4515281422582787, 'weight_class_1': 2.876828788178269, 'weight_class_2': 3.329388610826764}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:50,798] Trial 789 finished with value: 0.9477913920885609 and parameters: {'weight_class_0': 0.4312229133657405, 'weight_class_1': 2.9106346093180138, 'weight_class_2': 2.2595562399565714}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:50,821] Trial 790 finished with value: 0.9486011665504152 and parameters: {'weight_class_0': 0.4918002201227745, 'weight_class_1': 2.966299469218716, 'weight_class_2': 5.132380391140918}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:50,843] Trial 791 finished with value: 0.9487665921561242 and parameters: {'weight_class_0': 0.44332489962220034, 'weight_class_1': 2.8317937946432177, 'weight_class_2': 5.100030326996696}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  26%|██████████████████████████████████▉                                                                                                 | 793/3000 [00:15<00:46, 47.30it/s]

[I 2026-07-05 15:22:50,865] Trial 792 finished with value: 0.8168614733856652 and parameters: {'weight_class_0': 0.4510865650308357, 'weight_class_1': 0.10418968663320971, 'weight_class_2': 0.009478361718333968}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:50,905] Trial 794 finished with value: 0.9490077754403735 and parameters: {'weight_class_0': 0.31531998608266454, 'weight_class_1': 3.016923491463416, 'weight_class_2': 5.0147404464086645}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  26%|██████████████████████████████████▉                                                                                                 | 795/3000 [00:15<00:46, 47.30it/s]

[I 2026-07-05 15:22:50,912] Trial 793 finished with value: 0.949112584208705 and parameters: {'weight_class_0': 0.3259811230486429, 'weight_class_1': 2.902952857985789, 'weight_class_2': 4.822672892993584}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:50,919] Trial 795 finished with value: 0.9493122311110657 and parameters: {'weight_class_0': 0.31615310671114005, 'weight_class_1': 5.126951945676538, 'weight_class_2': 5.099166744795388}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  27%|███████████████████████████████████▏                                                                                                | 801/3000 [00:16<00:46, 47.09it/s]

[I 2026-07-05 15:22:50,949] Trial 797 finished with value: 0.9046064055403424 and parameters: {'weight_class_0': 0.321587623908831, 'weight_class_1': 0.18878040097538973, 'weight_class_2': 4.87666159244049}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:50,950] Trial 796 finished with value: 0.764079478996667 and parameters: {'weight_class_0': 0.3196802425180847, 'weight_class_1': 9.991201677683955, 'weight_class_2': 0.012359601084246545}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:51,006] Trial 798 finished with value: 0.9493462018073329 and parameters: {'weight_class_0': 0.32306249093867667, 'weight_class_1': 5.019369065457933, 'weight_class_2': 5.01104913019005}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:51,013] Trial 799 finished with value: 0.8594090810892601 and parameters: {'weight_class_0': 4.700949029674365, 'weight_class_1': 1.7828326291390337, 'weight_class_2': 5.108385458708645}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:51,027] Trial 800 finished with value: 0.9493748466297518 and parameters: {'weight_class_0': 0.31000141935515146, 'weight_class_1': 5.087387567668762, 'weight_class_2': 4.77038887914094}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:51,056] Trial 801 finished with value: 0.9493555729004074 and parameters: {'weight_class_0': 0.31185646075280743, 'weight_class_1': 5.113326686908891, 'weight_class_2': 4.942917785734544}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  27%|███████████████████████████████████▎                                                                                                | 803/3000 [00:16<00:46, 47.71it/s]

[I 2026-07-05 15:22:51,087] Trial 804 finished with value: 0.9495392630552558 and parameters: {'weight_class_0': 0.31194493645262544, 'weight_class_1': 5.473150007424291, 'weight_class_2': 4.208086475879226}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:51,093] Trial 802 finished with value: 0.9494811253170248 and parameters: {'weight_class_0': 0.3118258937492327, 'weight_class_1': 5.170366569938059, 'weight_class_2': 4.310518906703159}. Best is trial 376 with value: 0.9497246321366343.

[I 2026-07-05 15:22:51,096] Trial 803 finished with value: 0.9495702961597389 and parameters: {'weight_class_0': 0.32384027673559374, 'weight_class_1': 5.118194977159948, 'weight_class_2': 4.196707204785054}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:51,147] Trial 805 finished with value: 0.9491762104843833 and parameters: {'weight_class_0': 0.5770952098969442, 'weight_class_1': 9.87836576362497, 'weight_class_2': 4.044171929409117}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  27%|███████████████████████████████████▋                                                                                                | 811/3000 [00:16<00:46, 46.70it/s]

[I 2026-07-05 15:22:51,157] Trial 806 finished with value: 0.949402166744882 and parameters: {'weight_class_0': 0.5979506358376342, 'weight_class_1': 5.044450076225187, 'weight_class_2': 6.289793521936202}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:51,182] Trial 807 finished with value: 0.9384507217475694 and parameters: {'weight_class_0': 0.5578833050819807, 'weight_class_1': 5.05622850381564, 'weight_class_2': 1.292253548052323}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:51,210] Trial 808 finished with value: 0.920405377512235 and parameters: {'weight_class_0': 0.04674639680014701, 'weight_class_1': 5.106193786675416, 'weight_class_2': 6.53406341387053}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:51,229] Trial 809 finished with value: 0.9494592551927474 and parameters: {'weight_class_0': 0.5824694543802019, 'weight_class_1': 5.147565635863523, 'weight_class_2': 6.5675651203846686}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:51,238] Trial 811 finished with value: 0.9489715173605066 and parameters: {'weight_class_0': 0.5979769167489836, 'weight_class_1': 5.189724630302717, 'weight_class_2': 4.0535050374239345}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:51,246] Trial 810 finished with value: 0.9494918923638886 and parameters: {'weight_class_0': 0.5802442230823425, 'weight_class_1': 5.163695729042955, 'weight_class_2': 6.512713889284352}. Best is trial 376 with value: 0.9497246321366343.

[I 2026-07-05 15:22:51,279] Trial 812 finished with value: 0.9492697811536105 and parameters: {'weight_class_0': 0.5723823120576444, 'weight_class_1': 8.761062709634075, 'weight_class_2': 4.108984554344169}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:51,321] Trial 814 finished with value: 0.9496611620377298 and parameters: {'weight_class_0': 0.5743926824768236, 'weight_class_1': 8.525384652918438, 'weight_class_2': 6.466442757500661}. Best is trial 376 with value: 0.9497246321366343.

[I 2026-07-05 15:22:51,326] Trial 813 finished with value: 0.9494824447324183 and parameters: {'weight_class_0': 0.8086322870401627, 'weight_class_1': 8.333179180555184, 'weight_class_2': 6.521923102101071}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  27%|████████████████████████████████████                                                                                                | 821/3000 [00:16<00:48, 45.34it/s]

[I 2026-07-05 15:22:51,351] Trial 815 finished with value: 0.9496012853988588 and parameters: {'weight_class_0': 0.5479169056670998, 'weight_class_1': 9.936679341826986, 'weight_class_2': 6.499935164643459}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:51,370] Trial 816 finished with value: 0.9030357147328552 and parameters: {'weight_class_0': 0.0482229940753963, 'weight_class_1': 8.996830012696275, 'weight_class_2': 1.2743316115913248}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:51,380] Trial 817 finished with value: 0.8837179808768757 and parameters: {'weight_class_0': 1.6908061237087444, 'weight_class_1': 8.806702616475716, 'weight_class_2': 0.11025728060101433}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:51,407] Trial 818 finished with value: 0.9456755129641689 and parameters: {'weight_class_0': 0.7598833792919114, 'weight_class_1': 8.09853690908955, 'weight_class_2': 2.704077461633282}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:51,450] Trial 820 finished with value: 0.9450173430326014 and parameters: {'weight_class_0': 0.7698284157379487, 'weight_class_1': 8.744235269401672, 'weight_class_2': 2.561921618229172}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:51,457] Trial 819 finished with value: 0.9458325063665333 and parameters: {'weight_class_0': 0.7400109831159208, 'weight_class_1': 8.726544531953987, 'weight_class_2': 2.659171720976228}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:51,477] Trial 822 finished with value: 0.8912427937144921 and parameters: {'weight_class_0': 0.8312017392579499, 'weight_class_1': 8.381335512374594, 'weight_class_2': 0.14115527859086197}. Best is trial 376 with value: 0.9497246321366343.

[I 2026-07-05 15:22:51,488] Trial 821 finished with value: 0.9458551019941258 and parameters: {'weight_class_0': 0.8011351369424055, 'weight_class_1': 8.493694071494097, 'weight_class_2': 2.905717049565265}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:51,508] Trial 823 finished with value: 0.9494465876980397 and parameters: {'weight_class_0': 0.3785096943595727, 'weight_class_1': 8.569573720364762, 'weight_class_2': 3.1887680452640894}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:51,527] Trial 824 finished with value: 0.9360269902082673 and parameters: {'weight_class_0': 1.4210071597299587, 'weight_class_1': 8.594929231335277, 'weight_class_2': 3.101679747272389}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  28%|████████████████████████████████████▎                                                                                               | 825/3000 [00:16<00:45, 47.73it/s]

[I 2026-07-05 15:22:51,543] Trial 825 finished with value: 0.9494244941103528 and parameters: {'weight_class_0': 1.0390030710000386, 'weight_class_1': 8.912146027119082, 'weight_class_2': 9.910949945929376}. Best is trial 376 with value: 0.9497246321366343.

[I 2026-07-05 15:22:51,585] Trial 826 finished with value: 0.9495878465527564 and parameters: {'weight_class_0': 0.7593183957824039, 'weight_class_1': 8.812656871191757, 'weight_class_2': 9.565630110560129}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:51,599] Trial 827 finished with value: 0.949582130901019 and parameters: {'weight_class_0': 0.740271535433264, 'weight_class_1': 8.44277630727004, 'weight_class_2': 9.418447763465537}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:51,615] Trial 828 finished with value: 0.9489432106018336 and parameters: {'weight_class_0': 1.0439599843302978, 'weight_class_1': 9.927338321216892, 'weight_class_2': 6.894782171959456}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:51,676] Trial 830 finished with value: 0.9490824106491301 and parameters: {'weight_class_0': 1.149015981109765, 'weight_class_1': 8.241235592123475, 'weight_class_2': 8.938216140016978}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:51,679] Trial 829 finished with value: 0.9488329271481274 and parameters: {'weight_class_0': 0.4749650620155901, 'weight_class_1': 8.530393835412493, 'weight_class_2': 9.74600459048116}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  28%|████████████████████████████████████▋                                                                                               | 833/3000 [00:16<00:45, 47.20it/s]

[I 2026-07-05 15:22:51,701] Trial 831 finished with value: 0.9495533174359699 and parameters: {'weight_class_0': 0.49244661252048355, 'weight_class_1': 6.504810744923645, 'weight_class_2': 6.746133485074117}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:51,718] Trial 832 finished with value: 0.9491186275875432 and parameters: {'weight_class_0': 0.5039706580612738, 'weight_class_1': 6.500093437064306, 'weight_class_2': 8.779238445395283}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:51,738] Trial 833 finished with value: 0.6412946716819076 and parameters: {'weight_class_0': 1.0606421051726436, 'weight_class_1': 1.0002677938439182, 'weight_class_2': 0.001302400479914534}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 376. Best value: 0.949725:  28%|████████████████████████████████████▋                                                                                               | 835/3000 [00:16<00:48, 44.23it/s]

[I 2026-07-05 15:22:51,753] Trial 834 finished with value: 0.9491740663712717 and parameters: {'weight_class_0': 0.5197503073180569, 'weight_class_1': 6.384241072176495, 'weight_class_2': 8.736775334082855}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:51,784] Trial 835 finished with value: 0.9490940811299335 and parameters: {'weight_class_0': 0.4793296133401948, 'weight_class_1': 6.505655794984066, 'weight_class_2': 8.44640846431726}. Best is trial 376 with value: 0.9497246321366343.

Best trial: 841. Best value: 0.949725:  28%|█████████████████████████████████████                                                                                               | 841/3000 [00:16<00:45, 47.23it/s]

[I 2026-07-05 15:22:51,785] Trial 836 finished with value: 0.9492236457023037 and parameters: {'weight_class_0': 0.4895459578070811, 'weight_class_1': 9.994807555727862, 'weight_class_2': 8.071113056006553}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:51,810] Trial 837 finished with value: 0.9495979612496592 and parameters: {'weight_class_0': 0.5107841906799021, 'weight_class_1': 6.254534659237589, 'weight_class_2': 6.961891193721099}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:51,846] Trial 838 finished with value: 0.9496945243265976 and parameters: {'weight_class_0': 0.513737723369602, 'weight_class_1': 6.432548513456448, 'weight_class_2': 6.2742741708963194}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:51,849] Trial 839 finished with value: 0.9423647268826935 and parameters: {'weight_class_0': 0.5214901435214208, 'weight_class_1': 1.4024391405782672, 'weight_class_2': 5.849660910438443}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:51,863] Trial 840 finished with value: 0.9495659200136832 and parameters: {'weight_class_0': 0.5464774294964392, 'weight_class_1': 6.295441571527437, 'weight_class_2': 6.934518640343212}. Best is trial 376 with value: 0.9497246321366343.
[I 2026-07-05 15:22:51,899] Trial 841 finished with value: 0.9497247424344734 and parameters: {'weight_class_0': 0.5107051298810288, 'weight_class_1': 6.294603590350352, 'weight_class_2': 5.862676956274794}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  28%|█████████████████████████████████████▏                                                                                              | 844/3000 [00:16<00:45, 47.23it/s]

[I 2026-07-05 15:22:51,926] Trial 843 finished with value: 0.9494488456083352 and parameters: {'weight_class_0': 0.38082362230628103, 'weight_class_1': 6.264728965322228, 'weight_class_2': 5.495419279183261}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:51,937] Trial 842 finished with value: 0.94950113443897 and parameters: {'weight_class_0': 0.6096675094680829, 'weight_class_1': 6.381377678862253, 'weight_class_2': 6.7014226742446645}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:51,983] Trial 844 finished with value: 0.9494508951814137 and parameters: {'weight_class_0': 0.38943321868335345, 'weight_class_1': 6.302424966573062, 'weight_class_2': 5.653092938243736}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  28%|█████████████████████████████████████▏                                                                                              | 845/3000 [00:16<00:44, 47.97it/s]

[I 2026-07-05 15:22:52,009] Trial 846 finished with value: 0.9495289316332403 and parameters: {'weight_class_0': 0.38734155936506975, 'weight_class_1': 6.0232436371863205, 'weight_class_2': 5.358092677511809}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  28%|█████████████████████████████████████▍                                                                                              | 850/3000 [00:17<00:47, 45.05it/s]

[I 2026-07-05 15:22:52,013] Trial 845 finished with value: 0.9494374020715316 and parameters: {'weight_class_0': 0.3811920029607463, 'weight_class_1': 6.194386494258891, 'weight_class_2': 5.762316948729342}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:52,061] Trial 847 finished with value: 0.9491914420127086 and parameters: {'weight_class_0': 0.39657382040787065, 'weight_class_1': 3.595525437208648, 'weight_class_2': 5.539859939787972}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:52,081] Trial 848 finished with value: 0.9490987622124996 and parameters: {'weight_class_0': 0.3788619719965509, 'weight_class_1': 3.41512108944487, 'weight_class_2': 5.714387519996735}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:52,087] Trial 849 finished with value: 0.9496156959336618 and parameters: {'weight_class_0': 0.6362204508909044, 'weight_class_1': 7.221039695378284, 'weight_class_2': 5.636187576318608}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:52,117] Trial 850 finished with value: 0.949619703131973 and parameters: {'weight_class_0': 0.6531603837454818, 'weight_class_1': 7.314028452094165, 'weight_class_2': 5.721431968867884}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  28%|█████████████████████████████████████▌                                                                                              | 853/3000 [00:17<00:47, 45.05it/s]

[I 2026-07-05 15:22:52,146] Trial 851 finished with value: 0.9495411901536195 and parameters: {'weight_class_0': 0.658244349690808, 'weight_class_1': 6.056221326123757, 'weight_class_2': 5.796933794308715}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:52,152] Trial 852 finished with value: 0.9495518187555868 and parameters: {'weight_class_0': 0.6223538214960105, 'weight_class_1': 6.564729887386863, 'weight_class_2': 5.859768461863471}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:52,168] Trial 853 finished with value: 0.9494806390165751 and parameters: {'weight_class_0': 0.5847201880351912, 'weight_class_1': 5.876524318589415, 'weight_class_2': 6.03058310157014}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  28%|█████████████████████████████████████▌                                                                                              | 855/3000 [00:17<00:48, 44.35it/s]

[I 2026-07-05 15:22:52,194] Trial 854 finished with value: 0.9494975362937114 and parameters: {'weight_class_0': 0.6097689585698434, 'weight_class_1': 5.722564578080482, 'weight_class_2': 5.739072752887563}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:52,210] Trial 855 finished with value: 0.9495228301972555 and parameters: {'weight_class_0': 0.6323553348059086, 'weight_class_1': 6.140991833289234, 'weight_class_2': 5.957261356723867}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  29%|█████████████████████████████████████▊                                                                                              | 860/3000 [00:17<00:47, 44.77it/s]

[I 2026-07-05 15:22:52,243] Trial 856 finished with value: 0.9495007780252306 and parameters: {'weight_class_0': 0.6184925763324642, 'weight_class_1': 5.801485597244496, 'weight_class_2': 7.194791193867801}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:52,244] Trial 857 finished with value: 0.9496359463221803 and parameters: {'weight_class_0': 0.647959486264633, 'weight_class_1': 7.279781607528578, 'weight_class_2': 7.114883582812794}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:52,281] Trial 858 finished with value: 0.9496228572924812 and parameters: {'weight_class_0': 0.6098409637798325, 'weight_class_1': 7.256991325271306, 'weight_class_2': 7.46240374510245}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:52,326] Trial 859 finished with value: 0.9496169878554165 and parameters: {'weight_class_0': 0.6621851364658196, 'weight_class_1': 7.328969497703414, 'weight_class_2': 7.246299673423716}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:52,331] Trial 860 finished with value: 0.9494044712980414 and parameters: {'weight_class_0': 0.6544757533395196, 'weight_class_1': 5.546349369566996, 'weight_class_2': 7.11852067387372}. Best is trial 841 with value: 0.9497247424344734.

[I 2026-07-05 15:22:52,379] Trial 861 finished with value: 0.9482235692462925 and parameters: {'weight_class_0': 0.8792767824029882, 'weight_class_1': 4.560212755372967, 'weight_class_2': 7.9619659460959396}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:52,381] Trial 862 finished with value: 0.9494007506423605 and parameters: {'weight_class_0': 0.6041342880293877, 'weight_class_1': 5.610864757043051, 'weight_class_2': 7.510452559807121}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  29%|██████████████████████████████████████                                                                                              | 864/3000 [00:17<00:47, 44.77it/s]

[I 2026-07-05 15:22:52,421] Trial 863 finished with value: 0.9482418499326379 and parameters: {'weight_class_0': 0.8573410123817656, 'weight_class_1': 4.5167313036733105, 'weight_class_2': 6.819138493831631}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:52,461] Trial 865 finished with value: 0.9482877491862549 and parameters: {'weight_class_0': 0.8641989827836074, 'weight_class_1': 4.674295790777293, 'weight_class_2': 6.8133886915725705}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  29%|██████████████████████████████████████▏                                                                                             | 869/3000 [00:17<00:51, 41.78it/s]

[I 2026-07-05 15:22:52,466] Trial 864 finished with value: 0.9491307647823207 and parameters: {'weight_class_0': 0.4566958943594317, 'weight_class_1': 4.896660070494944, 'weight_class_2': 7.13511334075508}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:52,501] Trial 867 finished with value: 0.949455859675901 and parameters: {'weight_class_0': 0.9250408738466317, 'weight_class_1': 7.792670592602558, 'weight_class_2': 7.621608683196862}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:52,508] Trial 866 finished with value: 0.9493381742546075 and parameters: {'weight_class_0': 0.9279384306782952, 'weight_class_1': 7.277275490578111, 'weight_class_2': 7.959645848058309}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:52,535] Trial 868 finished with value: 0.9494111380110662 and parameters: {'weight_class_0': 0.8884496009590153, 'weight_class_1': 7.524422056507693, 'weight_class_2': 7.918691179061722}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:52,561] Trial 870 finished with value: 0.9495625219423478 and parameters: {'weight_class_0': 0.70148553779213, 'weight_class_1': 7.528113508021667, 'weight_class_2': 7.155537783986582}. Best is trial 841 with value: 0.9497247424344734.

[I 2026-07-05 15:22:52,573] Trial 869 finished with value: 0.9495588171024512 and parameters: {'weight_class_0': 0.888981783050759, 'weight_class_1': 8.056963972078883, 'weight_class_2': 7.658946172496138}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:52,603] Trial 871 finished with value: 0.9494790242508241 and parameters: {'weight_class_0': 0.8395811265385528, 'weight_class_1': 7.497764242252498, 'weight_class_2': 7.670187655358637}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  29%|██████████████████████████████████████▍                                                                                             | 874/3000 [00:17<00:49, 43.11it/s]

[I 2026-07-05 15:22:52,613] Trial 872 finished with value: 0.9493417401997912 and parameters: {'weight_class_0': 0.928437430038391, 'weight_class_1': 7.5928457861012, 'weight_class_2': 7.406328847789533}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:52,635] Trial 873 finished with value: 0.9494400666570589 and parameters: {'weight_class_0': 0.7964421195387429, 'weight_class_1': 7.184018121574116, 'weight_class_2': 8.051742973812823}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:52,674] Trial 875 finished with value: 0.9495471611145733 and parameters: {'weight_class_0': 0.7493601622057067, 'weight_class_1': 7.444106763842529, 'weight_class_2': 8.274349288654241}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  29%|██████████████████████████████████████▋                                                                                             | 878/3000 [00:17<00:49, 42.67it/s]

[I 2026-07-05 15:22:52,686] Trial 874 finished with value: 0.8840341108082406 and parameters: {'weight_class_0': 0.9251405233254467, 'weight_class_1': 7.563147845772348, 'weight_class_2': 0.07167248285474687}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:52,716] Trial 876 finished with value: 0.9490958660030655 and parameters: {'weight_class_0': 0.48520627544941036, 'weight_class_1': 7.374288087576002, 'weight_class_2': 8.554939903579786}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:52,724] Trial 877 finished with value: 0.9495209197244833 and parameters: {'weight_class_0': 0.7084231310799832, 'weight_class_1': 7.4172590711326105, 'weight_class_2': 8.358983156342893}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:52,782] Trial 878 finished with value: 0.9488642007446185 and parameters: {'weight_class_0': 0.742418473445448, 'weight_class_1': 7.512675818339626, 'weight_class_2': 4.750606486660244}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  29%|██████████████████████████████████████▋                                                                                             | 880/3000 [00:17<00:49, 43.00it/s]

[I 2026-07-05 15:22:52,794] Trial 879 finished with value: 0.9494215892249133 and parameters: {'weight_class_0': 0.7583147446579327, 'weight_class_1': 7.74050838476034, 'weight_class_2': 9.860303083165883}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:52,817] Trial 880 finished with value: 0.9489684393320595 and parameters: {'weight_class_0': 0.7297874965061418, 'weight_class_1': 7.542994330354748, 'weight_class_2': 4.875211470587153}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  29%|██████████████████████████████████████▊                                                                                             | 882/3000 [00:17<00:49, 43.00it/s]

[I 2026-07-05 15:22:52,858] Trial 882 finished with value: 0.948876486780779 and parameters: {'weight_class_0': 0.5169001199401733, 'weight_class_1': 6.7392011752008765, 'weight_class_2': 9.981720060238489}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:52,871] Trial 881 finished with value: 0.9495318526635996 and parameters: {'weight_class_0': 0.5227079628366293, 'weight_class_1': 5.438159911988659, 'weight_class_2': 4.767482313014986}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  30%|███████████████████████████████████████                                                                                             | 887/3000 [00:17<00:52, 40.58it/s]

[I 2026-07-05 15:22:52,890] Trial 883 finished with value: 0.9496234837207383 and parameters: {'weight_class_0': 0.5158284155413596, 'weight_class_1': 5.982881521002573, 'weight_class_2': 4.5396958252115525}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:52,908] Trial 884 finished with value: 0.9495470998243869 and parameters: {'weight_class_0': 0.5273113033119029, 'weight_class_1': 5.567027796655808, 'weight_class_2': 4.917101536478342}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:52,935] Trial 885 finished with value: 0.9495691407707696 and parameters: {'weight_class_0': 0.501357385644007, 'weight_class_1': 5.5172515184074795, 'weight_class_2': 4.815594319056459}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:52,977] Trial 886 finished with value: 0.9495988428635903 and parameters: {'weight_class_0': 0.4853186203424693, 'weight_class_1': 5.58610850308986, 'weight_class_2': 4.69162917912393}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:52,980] Trial 887 finished with value: 0.9495415374232478 and parameters: {'weight_class_0': 0.5096050789006765, 'weight_class_1': 5.524750616118099, 'weight_class_2': 4.5516706395563515}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  30%|███████████████████████████████████████▏                                                                                            | 890/3000 [00:18<00:49, 42.83it/s]

[I 2026-07-05 15:22:52,986] Trial 888 finished with value: 0.9495796732126239 and parameters: {'weight_class_0': 0.4778260959804711, 'weight_class_1': 5.543092972463498, 'weight_class_2': 4.784663043408733}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:53,029] Trial 889 finished with value: 0.8625983358781347 and parameters: {'weight_class_0': 0.5275828589093057, 'weight_class_1': 0.01933111049228989, 'weight_class_2': 5.061471391353094}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:53,042] Trial 890 finished with value: 0.9496181750738338 and parameters: {'weight_class_0': 0.5161364769147994, 'weight_class_1': 6.082193748520587, 'weight_class_2': 4.679845041289338}. Best is trial 841 with value: 0.9497247424344734.

[I 2026-07-05 15:22:53,068] Trial 891 finished with value: 0.9495642802465456 and parameters: {'weight_class_0': 0.5034959987014432, 'weight_class_1': 5.416471912891073, 'weight_class_2': 4.840089481667091}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:53,073] Trial 892 finished with value: 0.9496051544094675 and parameters: {'weight_class_0': 0.4618854881344374, 'weight_class_1': 5.411890382336557, 'weight_class_2': 4.753606049328928}. Best is trial 841 with value: 0.9497247424344734.

[I 2026-07-05 15:22:53,113] Trial 893 finished with value: 0.949665571378515 and parameters: {'weight_class_0': 0.4260313053772273, 'weight_class_1': 5.363180471145367, 'weight_class_2': 5.240932926132268}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:53,156] Trial 894 finished with value: 0.9493483979719026 and parameters: {'weight_class_0': 0.41981903193624603, 'weight_class_1': 9.849957555238188, 'weight_class_2': 5.7137388354376615}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:53,171] Trial 895 finished with value: 0.9492294004675559 and parameters: {'weight_class_0': 0.42600163214006936, 'weight_class_1': 4.4720143559049035, 'weight_class_2': 6.258920422353048}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:53,201] Trial 897 finished with value: 0.6569394237831528 and parameters: {'weight_class_0': 0.0019509763970316364, 'weight_class_1': 4.439640544449072, 'weight_class_2': 6.326935503548216}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  30%|███████████████████████████████████████▌                                                                                            | 899/3000 [00:18<00:49, 42.20it/s]

[I 2026-07-05 15:22:53,221] Trial 896 finished with value: 0.9211666358212004 and parameters: {'weight_class_0': 0.4030220703817172, 'weight_class_1': 0.4587945109122258, 'weight_class_2': 6.283955112817669}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:53,234] Trial 898 finished with value: 0.8773203680189576 and parameters: {'weight_class_0': 0.36524796498520506, 'weight_class_1': 0.04481599113381539, 'weight_class_2': 6.312193501123129}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:53,258] Trial 899 finished with value: 0.9491584681702259 and parameters: {'weight_class_0': 0.41658795194219383, 'weight_class_1': 9.868808705914907, 'weight_class_2': 6.354552487639099}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  30%|███████████████████████████████████████▋                                                                                            | 901/3000 [00:18<00:50, 41.87it/s]

[I 2026-07-05 15:22:53,295] Trial 900 finished with value: 0.9491123442760925 and parameters: {'weight_class_0': 0.395190188332222, 'weight_class_1': 4.447901972805826, 'weight_class_2': 6.613989898847288}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:53,306] Trial 901 finished with value: 0.9490478816356062 and parameters: {'weight_class_0': 0.3852502476630427, 'weight_class_1': 4.139181191427159, 'weight_class_2': 6.385195701857208}. Best is trial 841 with value: 0.9497247424344734.

[I 2026-07-05 15:22:53,312] Trial 902 finished with value: 0.9492761588553602 and parameters: {'weight_class_0': 0.3778637099228809, 'weight_class_1': 4.46975435915104, 'weight_class_2': 5.906164386812001}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:53,353] Trial 903 finished with value: 0.9490763538782062 and parameters: {'weight_class_0': 0.39858686053759085, 'weight_class_1': 3.9302497013254114, 'weight_class_2': 6.192044179912722}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:53,369] Trial 904 finished with value: 0.6570249254864496 and parameters: {'weight_class_0': 0.0022362061861451172, 'weight_class_1': 4.012486839849481, 'weight_class_2': 6.276192584906468}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:53,387] Trial 905 finished with value: 0.9495072122794097 and parameters: {'weight_class_0': 0.3819381676290874, 'weight_class_1': 3.795326787535856, 'weight_class_2': 4.0489847714202005}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  30%|███████████████████████████████████████▉                                                                                            | 909/3000 [00:18<00:48, 43.01it/s]

[I 2026-07-05 15:22:53,425] Trial 906 finished with value: 0.9494679999521823 and parameters: {'weight_class_0': 0.3938378607480723, 'weight_class_1': 3.556853905682816, 'weight_class_2': 3.743465381677912}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:53,439] Trial 907 finished with value: 0.9495177521665711 and parameters: {'weight_class_0': 0.3785503800075891, 'weight_class_1': 3.904756566802688, 'weight_class_2': 3.864234504178042}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:53,468] Trial 908 finished with value: 0.949534516275218 and parameters: {'weight_class_0': 0.39093245596581255, 'weight_class_1': 4.0466745740999075, 'weight_class_2': 3.8841866567768486}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:53,475] Trial 909 finished with value: 0.7461111860108952 and parameters: {'weight_class_0': 0.4014282109611215, 'weight_class_1': 3.774593087287462, 'weight_class_2': 0.0038736001371055726}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  30%|████████████████████████████████████████                                                                                            | 910/3000 [00:18<00:49, 42.54it/s]

[I 2026-07-05 15:22:53,514] Trial 910 finished with value: 0.9494752659777005 and parameters: {'weight_class_0': 0.36191218369904565, 'weight_class_1': 3.5532085469189907, 'weight_class_2': 3.913672378198433}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  30%|████████████████████████████████████████▎                                                                                           | 915/3000 [00:18<00:49, 42.14it/s]

[I 2026-07-05 15:22:53,579] Trial 913 finished with value: 0.9495421633123892 and parameters: {'weight_class_0': 0.35185828180072337, 'weight_class_1': 3.488108801196335, 'weight_class_2': 3.9600788927752615}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:53,593] Trial 912 finished with value: 0.9495397801267368 and parameters: {'weight_class_0': 0.34401278669515517, 'weight_class_1': 3.6764471008119064, 'weight_class_2': 4.054820938396584}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:53,595] Trial 911 finished with value: 0.9494956311972814 and parameters: {'weight_class_0': 0.36726028661677124, 'weight_class_1': 3.701996869717979, 'weight_class_2': 3.7535872785941082}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:53,609] Trial 914 finished with value: 0.9495450857461943 and parameters: {'weight_class_0': 0.3218467885542247, 'weight_class_1': 3.4737355924297293, 'weight_class_2': 3.9304282288035974}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  31%|████████████████████████████████████████▍                                                                                           | 918/3000 [00:18<00:49, 42.14it/s]

[I 2026-07-05 15:22:53,656] Trial 915 finished with value: 0.9495863400776505 and parameters: {'weight_class_0': 0.32738634494857066, 'weight_class_1': 3.604029010941306, 'weight_class_2': 3.7462300447445727}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:53,679] Trial 917 finished with value: 0.9496099705828045 and parameters: {'weight_class_0': 0.3261122856858156, 'weight_class_1': 4.7951511281703985, 'weight_class_2': 3.913627952956327}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:53,689] Trial 916 finished with value: 0.9495351086945513 and parameters: {'weight_class_0': 0.310176255893258, 'weight_class_1': 6.116926262396759, 'weight_class_2': 3.9803635159954065}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:53,714] Trial 918 finished with value: 0.9486411262584785 and parameters: {'weight_class_0': 0.6118781772695133, 'weight_class_1': 4.76337419297298, 'weight_class_2': 3.8923914114065483}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  31%|████████████████████████████████████████▍                                                                                           | 919/3000 [00:18<00:49, 42.14it/s]

[I 2026-07-05 15:22:53,725] Trial 919 finished with value: 0.9495951273994039 and parameters: {'weight_class_0': 0.30844342273708875, 'weight_class_1': 4.857664046308279, 'weight_class_2': 3.940764383190611}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  31%|████████████████████████████████████████▌                                                                                           | 923/3000 [00:18<00:50, 40.93it/s]

[I 2026-07-05 15:22:53,769] Trial 920 finished with value: 0.905257387165245 and parameters: {'weight_class_0': 0.3263839800689052, 'weight_class_1': 4.881635334421745, 'weight_class_2': 0.26384281139545473}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:53,810] Trial 922 finished with value: 0.9495871027766466 and parameters: {'weight_class_0': 0.30726182813965924, 'weight_class_1': 4.746008657350027, 'weight_class_2': 3.8567629117726434}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:53,811] Trial 921 finished with value: 0.9486672824264533 and parameters: {'weight_class_0': 0.6076633444708573, 'weight_class_1': 5.009303935503519, 'weight_class_2': 3.7766784062758987}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:53,850] Trial 924 finished with value: 0.7868023430349572 and parameters: {'weight_class_0': 0.009610051293486122, 'weight_class_1': 0.23402630472961947, 'weight_class_2': 5.299801653671116}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  31%|████████████████████████████████████████▊                                                                                           | 928/3000 [00:18<00:49, 41.52it/s]

[I 2026-07-05 15:22:53,863] Trial 923 finished with value: 0.948400870032173 and parameters: {'weight_class_0': 0.2192479506841664, 'weight_class_1': 4.980479576970728, 'weight_class_2': 5.379425698918241}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:53,891] Trial 926 finished with value: 0.949420592421859 and parameters: {'weight_class_0': 0.5631442839717665, 'weight_class_1': 4.8051611837781625, 'weight_class_2': 5.069244452634905}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:53,900] Trial 925 finished with value: 0.7714463422161807 and parameters: {'weight_class_0': 0.6305989788726847, 'weight_class_1': 4.91834702430051, 'weight_class_2': 0.00690626822405406}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:53,949] Trial 928 finished with value: 0.9495268577860655 and parameters: {'weight_class_0': 0.5970497666866118, 'weight_class_1': 6.102211960874724, 'weight_class_2': 5.319722802288145}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:53,952] Trial 927 finished with value: 0.9478479078791772 and parameters: {'weight_class_0': 0.21865577634118644, 'weight_class_1': 1.9241890190694317, 'weight_class_2': 5.305781009368916}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  31%|█████████████████████████████████████████                                                                                           | 932/3000 [00:19<00:47, 43.46it/s]

[I 2026-07-05 15:22:53,973] Trial 929 finished with value: 0.9480652654897246 and parameters: {'weight_class_0': 0.21050558467420172, 'weight_class_1': 6.646989899613411, 'weight_class_2': 5.228042460515381}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:54,007] Trial 930 finished with value: 0.9495165541588305 and parameters: {'weight_class_0': 0.6005639220329312, 'weight_class_1': 6.395997700432217, 'weight_class_2': 5.454044963477706}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:54,043] Trial 931 finished with value: 0.9480286832718662 and parameters: {'weight_class_0': 0.21858009903831327, 'weight_class_1': 1.923395570100729, 'weight_class_2': 4.929524114314328}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:54,070] Trial 932 finished with value: 0.9495745336528479 and parameters: {'weight_class_0': 0.590627907474569, 'weight_class_1': 6.54873097223396, 'weight_class_2': 5.476296795779398}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  31%|█████████████████████████████████████████▏                                                                                          | 936/3000 [00:19<00:48, 42.40it/s]

[I 2026-07-05 15:22:54,087] Trial 933 finished with value: 0.9450192334246009 and parameters: {'weight_class_0': 1.319019400481163, 'weight_class_1': 6.323019928411736, 'weight_class_2': 5.343707628302086}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:54,114] Trial 934 finished with value: 0.9070821024561808 and parameters: {'weight_class_0': 0.45674287412448145, 'weight_class_1': 6.4016638431314945, 'weight_class_2': 0.39871624357445734}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:54,136] Trial 935 finished with value: 0.9494002963002192 and parameters: {'weight_class_0': 0.6414007806701164, 'weight_class_1': 6.398740760426765, 'weight_class_2': 8.481879512182568}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:54,175] Trial 937 finished with value: 0.6582598838934705 and parameters: {'weight_class_0': 0.0028594453229681105, 'weight_class_1': 8.551043583832415, 'weight_class_2': 5.649565142310235}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  31%|█████████████████████████████████████████▍                                                                                          | 941/3000 [00:19<00:49, 41.29it/s]

[I 2026-07-05 15:22:54,189] Trial 939 finished with value: 0.9493451757003943 and parameters: {'weight_class_0': 0.44759850559363223, 'weight_class_1': 6.1773708767515085, 'weight_class_2': 3.2367940595788856}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:54,191] Trial 936 finished with value: 0.6588870580040095 and parameters: {'weight_class_0': 0.0032468679469332754, 'weight_class_1': 6.616598980945587, 'weight_class_2': 5.336435202169439}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:54,215] Trial 938 finished with value: 0.7639684734199971 and parameters: {'weight_class_0': 0.019654177981122057, 'weight_class_1': 6.494078997130234, 'weight_class_2': 8.349273999530748}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:54,235] Trial 940 finished with value: 0.9401619069884645 and parameters: {'weight_class_0': 1.1880696673805757, 'weight_class_1': 6.526930741679683, 'weight_class_2': 3.1280918497548433}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:54,286] Trial 942 finished with value: 0.9492707724693464 and parameters: {'weight_class_0': 0.4512328681618873, 'weight_class_1': 8.426214443168462, 'weight_class_2': 3.2621560796024087}. Best is trial 841 with value: 0.9497247424344734.

[I 2026-07-05 15:22:54,306] Trial 941 finished with value: 0.9117954370070853 and parameters: {'weight_class_0': 0.45214572401255104, 'weight_class_1': 6.338696228798025, 'weight_class_2': 0.45861843978432776}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:54,316] Trial 943 finished with value: 0.949069196042062 and parameters: {'weight_class_0': 0.4479331412335434, 'weight_class_1': 9.852900214679273, 'weight_class_2': 3.1717602723939398}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:54,333] Trial 944 finished with value: 0.9491389016088396 and parameters: {'weight_class_0': 0.446954860758755, 'weight_class_1': 9.903281642866954, 'weight_class_2': 3.2905035485552117}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:54,366] Trial 945 finished with value: 0.9489567239796036 and parameters: {'weight_class_0': 0.46754510892545464, 'weight_class_1': 8.571947207699113, 'weight_class_2': 8.78138667378321}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  32%|█████████████████████████████████████████▊                                                                                          | 950/3000 [00:19<00:50, 40.58it/s]

[I 2026-07-05 15:22:54,381] Trial 947 finished with value: 0.9487339203936509 and parameters: {'weight_class_0': 0.4343657460897899, 'weight_class_1': 9.852354424977275, 'weight_class_2': 2.8175792828463115}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:54,393] Trial 946 finished with value: 0.9490189800740566 and parameters: {'weight_class_0': 0.4628930346655891, 'weight_class_1': 9.919596952420855, 'weight_class_2': 3.1996571811695564}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:54,437] Trial 948 finished with value: 0.9491593598660041 and parameters: {'weight_class_0': 0.4664283488651855, 'weight_class_1': 8.460044828918996, 'weight_class_2': 3.236897683762408}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:54,483] Trial 949 finished with value: 0.9492888925915076 and parameters: {'weight_class_0': 0.4522573923784671, 'weight_class_1': 9.910182697094466, 'weight_class_2': 6.8231682989569835}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:54,504] Trial 950 finished with value: 0.9492368348698648 and parameters: {'weight_class_0': 0.4348275001033955, 'weight_class_1': 8.682277145874588, 'weight_class_2': 3.1628728001786035}. Best is trial 841 with value: 0.9497247424344734.

[I 2026-07-05 15:22:54,525] Trial 951 finished with value: 0.9480174397500761 and parameters: {'weight_class_0': 0.4589890032338677, 'weight_class_1': 2.588018236353728, 'weight_class_2': 6.848379012944194}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:54,536] Trial 952 finished with value: 0.9479020480753895 and parameters: {'weight_class_0': 0.44744592092140667, 'weight_class_1': 9.983551455817416, 'weight_class_2': 2.252277286157179}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:54,552] Trial 953 finished with value: 0.948140061114922 and parameters: {'weight_class_0': 0.28062787564991837, 'weight_class_1': 8.45824558894146, 'weight_class_2': 6.99986085430195}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:54,583] Trial 954 finished with value: 0.9490958861908325 and parameters: {'weight_class_0': 0.28634733220516234, 'weight_class_1': 2.5961326675765775, 'weight_class_2': 4.323445269538921}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  32%|██████████████████████████████████████████▎                                                                                         | 961/3000 [00:19<00:45, 44.36it/s]

[I 2026-07-05 15:22:54,608] Trial 955 finished with value: 0.9477389020029748 and parameters: {'weight_class_0': 0.2791694884499564, 'weight_class_1': 2.6278450875645953, 'weight_class_2': 7.2365774558537534}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:54,623] Trial 957 finished with value: 0.9466544489113606 and parameters: {'weight_class_0': 0.7444646288661374, 'weight_class_1': 2.9341519054785015, 'weight_class_2': 6.95540591413802}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:54,634] Trial 956 finished with value: 0.9484433260479769 and parameters: {'weight_class_0': 0.2811594026542402, 'weight_class_1': 3.077776393376793, 'weight_class_2': 1.4992196164041272}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:54,668] Trial 958 finished with value: 0.9480370404174598 and parameters: {'weight_class_0': 0.285092319684891, 'weight_class_1': 2.84206880147212, 'weight_class_2': 6.795148595059646}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:54,688] Trial 959 finished with value: 0.9479503751887695 and parameters: {'weight_class_0': 0.2829747475062286, 'weight_class_1': 2.6675094381375586, 'weight_class_2': 6.767826860411268}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:54,711] Trial 960 finished with value: 0.9481154908054434 and parameters: {'weight_class_0': 0.2895458741962176, 'weight_class_1': 3.0958918136572517, 'weight_class_2': 6.917186828744376}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  32%|██████████████████████████████████████████▍                                                                                         | 964/3000 [00:19<00:45, 44.36it/s]

[I 2026-07-05 15:22:54,755] Trial 961 finished with value: 0.943920218226764 and parameters: {'weight_class_0': 0.6848159535587114, 'weight_class_1': 5.338434828799013, 'weight_class_2': 2.1673074031801827}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:54,759] Trial 962 finished with value: 0.7220343495731338 and parameters: {'weight_class_0': 0.26906692796661197, 'weight_class_1': 0.0028015704779097857, 'weight_class_2': 0.017682810155058806}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:54,768] Trial 963 finished with value: 0.7274438566888458 and parameters: {'weight_class_0': 0.27225613439296575, 'weight_class_1': 0.0024987992530930724, 'weight_class_2': 4.3003451188318325}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:54,772] Trial 964 finished with value: 0.9481979732609375 and parameters: {'weight_class_0': 0.7417559297599363, 'weight_class_1': 5.0760883322316035, 'weight_class_2': 4.325721759789761}. Best is trial 841 with value: 0.9497247424344734.

[I 2026-07-05 15:22:54,815] Trial 965 finished with value: 0.9365367414276885 and parameters: {'weight_class_0': 0.6782077797686152, 'weight_class_1': 5.16143491635751, 'weight_class_2': 1.4759464196585874}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:54,834] Trial 966 finished with value: 0.9486458060790253 and parameters: {'weight_class_0': 0.6981866333842474, 'weight_class_1': 5.371208202320001, 'weight_class_2': 4.510116677896024}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:54,891] Trial 968 finished with value: 0.9483881278295341 and parameters: {'weight_class_0': 0.7299247362614822, 'weight_class_1': 5.080554575763131, 'weight_class_2': 4.485320716651812}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:54,897] Trial 967 finished with value: 0.8218423546090653 and parameters: {'weight_class_0': 0.7512922412391478, 'weight_class_1': 0.011189266137832807, 'weight_class_2': 2.48605858987998}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:54,901] Trial 969 finished with value: 0.9481531919019236 and parameters: {'weight_class_0': 0.7713948966747374, 'weight_class_1': 5.407019801449124, 'weight_class_2': 4.28103494675145}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:54,928] Trial 970 finished with value: 0.9487948172640964 and parameters: {'weight_class_0': 0.6780259072888483, 'weight_class_1': 5.49733568813347, 'weight_class_2': 4.463867316387347}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  32%|██████████████████████████████████████████▉                                                                                         | 975/3000 [00:19<00:45, 44.99it/s]

[I 2026-07-05 15:22:54,941] Trial 971 finished with value: 0.948337349776037 and parameters: {'weight_class_0': 0.7338112191049465, 'weight_class_1': 5.420905287168232, 'weight_class_2': 4.229486404911857}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:54,961] Trial 972 finished with value: 0.9489389328860626 and parameters: {'weight_class_0': 0.7205830390653982, 'weight_class_1': 5.45009397009263, 'weight_class_2': 9.90637818591072}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:54,997] Trial 973 finished with value: 0.6849311550397905 and parameters: {'weight_class_0': 0.3567728943130619, 'weight_class_1': 0.00172191287275511, 'weight_class_2': 2.492296063758045}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:54,999] Trial 974 finished with value: 0.9475984151265425 and parameters: {'weight_class_0': 0.5490778661025769, 'weight_class_1': 5.4993970894602295, 'weight_class_2': 2.4660141383777328}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:55,020] Trial 975 finished with value: 0.9471693476388684 and parameters: {'weight_class_0': 0.13923709006953305, 'weight_class_1': 5.553572733054747, 'weight_class_2': 4.480837982466473}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  33%|███████████████████████████████████████████                                                                                         | 979/3000 [00:20<00:42, 47.45it/s]

[I 2026-07-05 15:22:55,047] Trial 976 finished with value: 0.9495662254584541 and parameters: {'weight_class_0': 0.22031962706526725, 'weight_class_1': 4.4618838651206865, 'weight_class_2': 2.587231296545299}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:55,088] Trial 977 finished with value: 0.8852340905030821 and parameters: {'weight_class_0': 0.35483429783776055, 'weight_class_1': 0.07867140700817125, 'weight_class_2': 4.420151929163018}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:55,102] Trial 978 finished with value: 0.9493147917002661 and parameters: {'weight_class_0': 0.5414593848963987, 'weight_class_1': 4.385687693841717, 'weight_class_2': 4.326303831834596}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:55,150] Trial 979 finished with value: 0.9478774416513835 and parameters: {'weight_class_0': 0.540967961221611, 'weight_class_1': 7.6473807218440495, 'weight_class_2': 2.5316349544650314}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  33%|███████████████████████████████████████████▎                                                                                        | 984/3000 [00:20<00:48, 41.86it/s]

[I 2026-07-05 15:22:55,164] Trial 980 finished with value: 0.9481195485056775 and parameters: {'weight_class_0': 0.5533639742533356, 'weight_class_1': 7.6944570095140365, 'weight_class_2': 2.728608637658613}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:55,177] Trial 981 finished with value: 0.9490450776490963 and parameters: {'weight_class_0': 0.5473763407755872, 'weight_class_1': 7.503849500801302, 'weight_class_2': 9.783464959921464}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:55,200] Trial 982 finished with value: 0.9492145975888682 and parameters: {'weight_class_0': 0.35623627964945553, 'weight_class_1': 7.220359575582381, 'weight_class_2': 2.584794766766382}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:55,228] Trial 983 finished with value: 0.94803075150924 and parameters: {'weight_class_0': 0.5377852101585869, 'weight_class_1': 7.6542383889243775, 'weight_class_2': 2.596484601180225}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:55,242] Trial 984 finished with value: 0.9479719940076431 and parameters: {'weight_class_0': 0.22821642941451856, 'weight_class_1': 7.476559800622199, 'weight_class_2': 5.7715462632469015}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  33%|███████████████████████████████████████████▌                                                                                        | 990/3000 [00:20<00:44, 45.44it/s]

[I 2026-07-05 15:22:55,273] Trial 985 finished with value: 0.9492511237378297 and parameters: {'weight_class_0': 0.3599673217083972, 'weight_class_1': 7.186865289911196, 'weight_class_2': 5.911995826698947}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:55,283] Trial 986 finished with value: 0.9494789494575757 and parameters: {'weight_class_0': 0.3645895460615688, 'weight_class_1': 7.999456278830021, 'weight_class_2': 3.6066307625069}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:55,309] Trial 987 finished with value: 0.9496118041218876 and parameters: {'weight_class_0': 0.5364117745994534, 'weight_class_1': 7.642096388797009, 'weight_class_2': 5.565264950029796}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:55,327] Trial 988 finished with value: 0.9488995190675641 and parameters: {'weight_class_0': 0.5749802700081926, 'weight_class_1': 7.555160958716986, 'weight_class_2': 3.515417968150627}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:55,343] Trial 989 finished with value: 0.9426874442530563 and parameters: {'weight_class_0': 0.35681050599395336, 'weight_class_1': 7.684431722934961, 'weight_class_2': 1.0247819865623116}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:55,345] Trial 990 finished with value: 0.9495003648106412 and parameters: {'weight_class_0': 0.351092687854388, 'weight_class_1': 7.562793675329424, 'weight_class_2': 3.391253126601293}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  33%|███████████████████████████████████████████▋                                                                                        | 993/3000 [00:20<00:44, 45.06it/s]

[I 2026-07-05 15:22:55,393] Trial 991 finished with value: 0.9493168417849324 and parameters: {'weight_class_0': 0.3732374519504098, 'weight_class_1': 7.207581924064611, 'weight_class_2': 5.889034222051351}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:55,439] Trial 992 finished with value: 0.9461420492272591 and parameters: {'weight_class_0': 1.006767108391221, 'weight_class_1': 4.121607152283052, 'weight_class_2': 6.01365330643006}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:55,477] Trial 993 finished with value: 0.9495671816523265 and parameters: {'weight_class_0': 0.3802188411633989, 'weight_class_1': 4.179858419460219, 'weight_class_2': 3.552065392086543}. Best is trial 841 with value: 0.9497247424344734.

[I 2026-07-05 15:22:55,486] Trial 994 finished with value: 0.9496156355483653 and parameters: {'weight_class_0': 0.3533936777070213, 'weight_class_1': 4.185618340367679, 'weight_class_2': 3.3567202228133564}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:55,491] Trial 995 finished with value: 0.9495454711882743 and parameters: {'weight_class_0': 0.3831064239690497, 'weight_class_1': 3.956919980153904, 'weight_class_2': 3.609624940776035}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:55,521] Trial 996 finished with value: 0.9418185807347049 and parameters: {'weight_class_0': 1.045362818062264, 'weight_class_1': 4.086787711842801, 'weight_class_2': 3.468252674247831}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:55,556] Trial 997 finished with value: 0.9495255122332042 and parameters: {'weight_class_0': 0.3860780605870889, 'weight_class_1': 4.150644807317437, 'weight_class_2': 3.453975424496992}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:55,564] Trial 998 finished with value: 0.949403084344541 and parameters: {'weight_class_0': 0.2372110271595636, 'weight_class_1': 4.185146079632285, 'weight_class_2': 3.5550030108880972}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:55,566] Trial 999 finished with value: 0.9484308464448703 and parameters: {'weight_class_0': 0.39061276350112845, 'weight_class_1': 4.040505952445625, 'weight_class_2': 8.095263042838427}. Best is trial 841 with value: 0.9497247424344734.

[I 2026-07-05 15:22:55,587] Trial 1000 finished with value: 0.9471265400199614 and parameters: {'weight_class_0': 1.0012122845303246, 'weight_class_1': 4.252265315600361, 'weight_class_2': 8.387965613385992}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:55,621] Trial 1001 finished with value: 0.9475278253874239 and parameters: {'weight_class_0': 0.23454113799010648, 'weight_class_1': 4.22953708503499, 'weight_class_2': 8.532475081189698}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  33%|███████████████████████████████████████████▊                                                                                       | 1003/3000 [00:20<00:44, 45.01it/s]

[I 2026-07-05 15:22:55,622] Trial 1002 finished with value: 0.947467777867538 and parameters: {'weight_class_0': 0.2290339600947878, 'weight_class_1': 4.259721317713696, 'weight_class_2': 8.652607468786567}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:55,658] Trial 1003 finished with value: 0.9484951773149947 and parameters: {'weight_class_0': 0.4294262306201624, 'weight_class_1': 4.140738116394736, 'weight_class_2': 8.245681135683755}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  34%|████████████████████████████████████████████                                                                                       | 1008/3000 [00:20<00:43, 45.47it/s]

[I 2026-07-05 15:22:55,683] Trial 1004 finished with value: 0.9475546141495249 and parameters: {'weight_class_0': 0.23375117701429463, 'weight_class_1': 4.218567964702928, 'weight_class_2': 8.42370681540111}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:55,720] Trial 1005 finished with value: 0.9476213713892525 and parameters: {'weight_class_0': 0.23784081750934793, 'weight_class_1': 6.114668464497221, 'weight_class_2': 8.351353028089394}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:55,729] Trial 1006 finished with value: 0.9420437405154249 and parameters: {'weight_class_0': 0.24337742325367434, 'weight_class_1': 0.7433217690669286, 'weight_class_2': 8.142775223889304}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:55,769] Trial 1007 finished with value: 0.9476408603094736 and parameters: {'weight_class_0': 0.22906042875556074, 'weight_class_1': 6.303808293337879, 'weight_class_2': 7.961386747811118}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:55,773] Trial 1008 finished with value: 0.9477611609925379 and parameters: {'weight_class_0': 0.249471064541377, 'weight_class_1': 6.136793341054052, 'weight_class_2': 8.30155765437055}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  34%|████████████████████████████████████████████                                                                                       | 1010/3000 [00:20<00:43, 45.47it/s]

[I 2026-07-05 15:22:55,821] Trial 1009 finished with value: 0.9467909955087307 and parameters: {'weight_class_0': 0.4624794174896398, 'weight_class_1': 6.142418811181801, 'weight_class_2': 1.8563922608664574}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:55,822] Trial 1010 finished with value: 0.948432331243851 and parameters: {'weight_class_0': 0.23508009801375382, 'weight_class_1': 6.387822949149618, 'weight_class_2': 5.162136455497713}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  34%|████████████████████████████████████████████▏                                                                                      | 1013/3000 [00:20<00:43, 45.60it/s]

[I 2026-07-05 15:22:55,853] Trial 1013 finished with value: 0.9490276353247719 and parameters: {'weight_class_0': 0.31331635830370713, 'weight_class_1': 6.235264206976088, 'weight_class_2': 2.092251342037211}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:55,854] Trial 1012 finished with value: 0.948617344072265 and parameters: {'weight_class_0': 0.3166294857385763, 'weight_class_1': 6.229381862967582, 'weight_class_2': 1.835995216408806}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:55,867] Trial 1011 finished with value: 0.9485808122838549 and parameters: {'weight_class_0': 0.24430900810424294, 'weight_class_1': 6.168090638907507, 'weight_class_2': 5.180180227892046}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  34%|████████████████████████████████████████████▍                                                                                      | 1019/3000 [00:20<00:44, 44.70it/s]

[I 2026-07-05 15:22:55,938] Trial 1014 finished with value: 0.9482446532648585 and parameters: {'weight_class_0': 0.3088781238772147, 'weight_class_1': 6.546444127636824, 'weight_class_2': 1.6486514156553247}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:55,947] Trial 1015 finished with value: 0.9486868293517542 and parameters: {'weight_class_0': 0.30494326987822634, 'weight_class_1': 6.074418177367033, 'weight_class_2': 1.796384769194182}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:55,956] Trial 1016 finished with value: 0.9492236335717715 and parameters: {'weight_class_0': 0.30411769881264633, 'weight_class_1': 6.258508951992712, 'weight_class_2': 4.983823476264672}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:55,972] Trial 1017 finished with value: 0.8208513544506517 and parameters: {'weight_class_0': 0.3113041326847234, 'weight_class_1': 0.004690340458190584, 'weight_class_2': 1.9439890626152991}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:55,983] Trial 1018 finished with value: 0.9490384576025422 and parameters: {'weight_class_0': 0.31986992603156394, 'weight_class_1': 3.2703823646051116, 'weight_class_2': 5.1901138646898595}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:56,019] Trial 1020 finished with value: 0.9476985814306548 and parameters: {'weight_class_0': 0.07651140594298178, 'weight_class_1': 3.194837015718658, 'weight_class_2': 1.6675907852994352}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  34%|████████████████████████████████████████████▌                                                                                      | 1020/3000 [00:21<00:44, 44.70it/s]

[I 2026-07-05 15:22:56,047] Trial 1019 finished with value: 0.9486172866116184 and parameters: {'weight_class_0': 0.2911278163829291, 'weight_class_1': 6.172560806612591, 'weight_class_2': 1.7086469387622054}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  34%|████████████████████████████████████████████▋                                                                                      | 1023/3000 [00:21<00:44, 44.02it/s]

[I 2026-07-05 15:22:56,080] Trial 1021 finished with value: 0.9487852801967182 and parameters: {'weight_class_0': 0.5693841450234132, 'weight_class_1': 3.464684133767385, 'weight_class_2': 4.843995175381759}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:56,109] Trial 1023 finished with value: 0.949661637140531 and parameters: {'weight_class_0': 0.5985508714930854, 'weight_class_1': 8.52847524555596, 'weight_class_2': 6.509703641580596}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:56,115] Trial 1022 finished with value: 0.8617671977917759 and parameters: {'weight_class_0': 6.68754431564213, 'weight_class_1': 3.277202299515069, 'weight_class_2': 6.5712171246270765}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  34%|████████████████████████████████████████████▉                                                                                      | 1028/3000 [00:21<00:43, 45.05it/s]

[I 2026-07-05 15:22:56,125] Trial 1024 finished with value: 0.9483784771159139 and parameters: {'weight_class_0': 0.5729615670558742, 'weight_class_1': 3.2254830062404443, 'weight_class_2': 6.351062281626813}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:56,163] Trial 1025 finished with value: 0.9484439446625673 and parameters: {'weight_class_0': 0.5587289715078698, 'weight_class_1': 3.187378014866407, 'weight_class_2': 6.47382181057698}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:56,198] Trial 1026 finished with value: 0.9488350017124221 and parameters: {'weight_class_0': 0.5245899689495509, 'weight_class_1': 3.4898002593095936, 'weight_class_2': 6.44451682139108}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:56,209] Trial 1028 finished with value: 0.9482959663222653 and parameters: {'weight_class_0': 0.603785990199316, 'weight_class_1': 3.283761816252919, 'weight_class_2': 6.230827261564193}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:56,210] Trial 1027 finished with value: 0.9486104692038199 and parameters: {'weight_class_0': 0.5690068611553367, 'weight_class_1': 3.408979650175608, 'weight_class_2': 6.570116906188684}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  34%|████████████████████████████████████████████▉                                                                                      | 1030/3000 [00:21<00:43, 45.05it/s]

[I 2026-07-05 15:22:56,244] Trial 1030 finished with value: 0.949659818286469 and parameters: {'weight_class_0': 0.5738996477922275, 'weight_class_1': 8.495750178403963, 'weight_class_2': 6.3927318780766305}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:56,265] Trial 1029 finished with value: 0.9496038215962046 and parameters: {'weight_class_0': 0.5764360723541967, 'weight_class_1': 8.602792790864248, 'weight_class_2': 6.265408945173893}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  34%|█████████████████████████████████████████████                                                                                      | 1033/3000 [00:21<00:44, 44.45it/s]

[I 2026-07-05 15:22:56,291] Trial 1031 finished with value: 0.9496750099938035 and parameters: {'weight_class_0': 0.5963941384648545, 'weight_class_1': 8.350481996372869, 'weight_class_2': 6.667418538923604}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:56,300] Trial 1032 finished with value: 0.9496361003874382 and parameters: {'weight_class_0': 0.6082543481953402, 'weight_class_1': 8.157150356191273, 'weight_class_2': 6.415922760832656}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:56,345] Trial 1033 finished with value: 0.9496709422456281 and parameters: {'weight_class_0': 0.6118722707073411, 'weight_class_1': 8.801401566551554, 'weight_class_2': 6.722026630572659}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  35%|█████████████████████████████████████████████▎                                                                                     | 1037/3000 [00:21<00:44, 44.45it/s]

[I 2026-07-05 15:22:56,356] Trial 1035 finished with value: 0.9496637456674665 and parameters: {'weight_class_0': 0.6417486612959928, 'weight_class_1': 9.010274031033578, 'weight_class_2': 7.045410773477061}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:56,384] Trial 1034 finished with value: 0.9496414478366056 and parameters: {'weight_class_0': 0.6305662740967666, 'weight_class_1': 9.117413841962867, 'weight_class_2': 6.720451857787692}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:56,440] Trial 1036 finished with value: 0.9496892633587032 and parameters: {'weight_class_0': 0.6337600541459654, 'weight_class_1': 8.598085205809898, 'weight_class_2': 7.080430609439316}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:56,449] Trial 1038 finished with value: 0.949525595283558 and parameters: {'weight_class_0': 0.84684269203187, 'weight_class_1': 8.626996117838985, 'weight_class_2': 6.957577545915779}. Best is trial 841 with value: 0.9497247424344734.

[I 2026-07-05 15:22:56,451] Trial 1037 finished with value: 0.9494863197491809 and parameters: {'weight_class_0': 0.8394351500465813, 'weight_class_1': 8.047999076968589, 'weight_class_2': 6.87915799698681}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:56,479] Trial 1039 finished with value: 0.9495429291952201 and parameters: {'weight_class_0': 0.6978895152753645, 'weight_class_1': 8.939238989029478, 'weight_class_2': 5.531871360042182}. Best is trial 841 with value: 0.9497247424344734.

Best trial: 841. Best value: 0.949725:  35%|█████████████████████████████████████████████▌                                                                                     | 1043/3000 [00:21<00:46, 42.38it/s]

[I 2026-07-05 15:22:56,490] Trial 1040 finished with value: 0.9490420193398453 and parameters: {'weight_class_0': 0.8485926190987597, 'weight_class_1': 8.711934299605112, 'weight_class_2': 5.843518798787394}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:56,509] Trial 1041 finished with value: 0.9488759041238618 and parameters: {'weight_class_0': 0.8166764049683212, 'weight_class_1': 9.299044263204351, 'weight_class_2': 4.957470349794037}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:56,547] Trial 1043 finished with value: 0.949561657428957 and parameters: {'weight_class_0': 0.4380129635481435, 'weight_class_1': 8.676356794866503, 'weight_class_2': 5.241321690176991}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:56,550] Trial 1042 finished with value: 0.9487907745631855 and parameters: {'weight_class_0': 0.8553616480304468, 'weight_class_1': 8.638609247190121, 'weight_class_2': 5.192218264655429}. Best is trial 841 with value: 0.9497247424344734.

[I 2026-07-05 15:22:56,590] Trial 1045 finished with value: 0.9496483149604033 and parameters: {'weight_class_0': 0.8245626144010428, 'weight_class_1': 9.582157357483316, 'weight_class_2': 7.168970202961611}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:56,598] Trial 1044 finished with value: 0.9495808219453475 and parameters: {'weight_class_0': 0.7983199899280038, 'weight_class_1': 8.918833777683648, 'weight_class_2': 9.900452317676598}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:56,614] Trial 1046 finished with value: 0.9496505751009044 and parameters: {'weight_class_0': 0.7577745044629536, 'weight_class_1': 9.807310867319817, 'weight_class_2': 7.026472990387913}. Best is trial 841 with value: 0.9497247424344734.
[I 2026-07-05 15:22:56,638] Trial 1047 finished with value: 0.9495212628638955 and parameters: {'weight_class_0': 0.8538648455698232, 'weight_class_1': 8.45597465526648, 'weight_class_2': 7.600988336457003}. Best is trial 841 with value: 0.9497247424344734.

[I 2026-07-05 15:22:56,673] Trial 1048 finished with value: 0.9497275203916301 and parameters: {'weight_class_0': 0.8039208642026672, 'weight_class_1': 9.863498113363134, 'weight_class_2': 9.197379543749037}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:56,699] Trial 1049 finished with value: 0.9497028549032568 and parameters: {'weight_class_0': 0.7722819964669232, 'weight_class_1': 9.956961260874804, 'weight_class_2': 9.03601546863767}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  35%|█████████████████████████████████████████████▋                                                                                    | 1053/3000 [00:21<00:41, 46.62it/s]

[I 2026-07-05 15:22:56,718] Trial 1050 finished with value: 0.949684386553451 and parameters: {'weight_class_0': 0.7681025574167644, 'weight_class_1': 9.96895169574055, 'weight_class_2': 9.547082970946722}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:56,735] Trial 1052 finished with value: 0.9495148980363273 and parameters: {'weight_class_0': 1.141824471505217, 'weight_class_1': 9.909547633259612, 'weight_class_2': 9.866475227989678}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:56,758] Trial 1051 finished with value: 0.9496204130222358 and parameters: {'weight_class_0': 0.7653452064065701, 'weight_class_1': 9.857056866565257, 'weight_class_2': 7.966411066344637}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:56,773] Trial 1053 finished with value: 0.949564423271009 and parameters: {'weight_class_0': 0.9110552907923243, 'weight_class_1': 9.731928570151672, 'weight_class_2': 7.986842540451464}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  35%|█████████████████████████████████████████████▊                                                                                    | 1057/3000 [00:21<00:43, 44.33it/s]

[I 2026-07-05 15:22:56,798] Trial 1054 finished with value: 0.9497033237865969 and parameters: {'weight_class_0': 0.7384833226894438, 'weight_class_1': 9.790931346076105, 'weight_class_2': 8.477957773413179}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:56,838] Trial 1055 finished with value: 0.9487753916127964 and parameters: {'weight_class_0': 1.2687293473234047, 'weight_class_1': 9.8665736801592, 'weight_class_2': 8.428879988829197}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:56,857] Trial 1056 finished with value: 0.948405594863808 and parameters: {'weight_class_0': 1.4216560016217026, 'weight_class_1': 9.175019173928302, 'weight_class_2': 9.532610420515713}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:56,878] Trial 1057 finished with value: 0.9494030277216954 and parameters: {'weight_class_0': 1.0501308818538515, 'weight_class_1': 8.773569338576719, 'weight_class_2': 9.952213741989809}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  35%|█████████████████████████████████████████████▊                                                                                    | 1058/3000 [00:21<00:43, 44.33it/s]

[I 2026-07-05 15:22:56,888] Trial 1058 finished with value: 0.9495356559174221 and parameters: {'weight_class_0': 0.9101846359669472, 'weight_class_1': 9.759081814507725, 'weight_class_2': 8.21744536528302}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  35%|██████████████████████████████████████████████                                                                                    | 1064/3000 [00:21<00:42, 45.65it/s]

[I 2026-07-05 15:22:56,924] Trial 1059 finished with value: 0.9488620541508895 and parameters: {'weight_class_0': 1.3528752802425859, 'weight_class_1': 9.62450056793014, 'weight_class_2': 9.840970556582185}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:56,932] Trial 1060 finished with value: 0.9486064654741267 and parameters: {'weight_class_0': 1.232836232394232, 'weight_class_1': 9.299593479273424, 'weight_class_2': 7.899834608230152}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:56,954] Trial 1062 finished with value: 0.9488614226798128 and parameters: {'weight_class_0': 1.2961007782643976, 'weight_class_1': 9.963110660884547, 'weight_class_2': 9.04699252188903}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:56,965] Trial 1063 finished with value: 0.9484853130278449 and parameters: {'weight_class_0': 1.4148810730143384, 'weight_class_1': 9.790612790977047, 'weight_class_2': 9.196411351833236}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:56,978] Trial 1061 finished with value: 0.9494097564777951 and parameters: {'weight_class_0': 1.1916303718157641, 'weight_class_1': 9.977706702528556, 'weight_class_2': 9.931905160730555}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:57,014] Trial 1064 finished with value: 0.9488129488377733 and parameters: {'weight_class_0': 1.2943436350051156, 'weight_class_1': 9.789852656178255, 'weight_class_2': 8.89249202817443}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:22:57,048] Trial 1065 finished with value: 0.9483386512530895 and parameters: {'weight_class_0': 1.3855051311432312, 'weight_class_1': 9.33831399953874, 'weight_class_2': 8.486578422117079}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:57,093] Trial 1066 finished with value: 0.9494885084225656 and parameters: {'weight_class_0': 0.9718548723455707, 'weight_class_1': 9.683899150254991, 'weight_class_2': 9.936108165630378}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  36%|██████████████████████████████████████████████▎                                                                                   | 1068/3000 [00:22<00:40, 47.35it/s]

[I 2026-07-05 15:22:57,094] Trial 1067 finished with value: 0.9494919321656593 and parameters: {'weight_class_0': 1.0777334235153095, 'weight_class_1': 9.685233769644823, 'weight_class_2': 9.698362865234794}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:57,101] Trial 1068 finished with value: 0.9494933286513159 and parameters: {'weight_class_0': 1.0548876914234957, 'weight_class_1': 9.779246181927478, 'weight_class_2': 9.874318673790656}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  36%|██████████████████████████████████████████████▍                                                                                   | 1073/3000 [00:22<00:43, 44.71it/s]

[I 2026-07-05 15:22:57,132] Trial 1069 finished with value: 0.949524443839957 and parameters: {'weight_class_0': 0.8987358171311601, 'weight_class_1': 9.573936864909316, 'weight_class_2': 9.887171159986696}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:57,169] Trial 1070 finished with value: 0.9495666698572524 and parameters: {'weight_class_0': 1.087384955064394, 'weight_class_1': 9.993386329480929, 'weight_class_2': 9.485284837766239}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:57,187] Trial 1072 finished with value: 0.9493318774555224 and parameters: {'weight_class_0': 1.1900358283575034, 'weight_class_1': 9.576609425528009, 'weight_class_2': 9.722035352599216}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:57,215] Trial 1071 finished with value: 0.9495384376423477 and parameters: {'weight_class_0': 0.994501876263317, 'weight_class_1': 9.83532164359864, 'weight_class_2': 9.614645060983817}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:57,230] Trial 1073 finished with value: 0.9494484943807722 and parameters: {'weight_class_0': 0.9813238532572913, 'weight_class_1': 8.436387029079999, 'weight_class_2': 9.523710135302707}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:22:57,254] Trial 1075 finished with value: 0.9493839605941256 and parameters: {'weight_class_0': 1.034944720926369, 'weight_class_1': 8.34552672495092, 'weight_class_2': 8.813490011586625}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:57,264] Trial 1074 finished with value: 0.9493418933350268 and parameters: {'weight_class_0': 1.026923904365071, 'weight_class_1': 8.286959740882441, 'weight_class_2': 9.800955099282167}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:57,279] Trial 1076 finished with value: 0.9493044667366167 and parameters: {'weight_class_0': 1.0524599325637307, 'weight_class_1': 8.687003465607424, 'weight_class_2': 8.221528563352024}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:57,305] Trial 1077 finished with value: 0.9495819210247135 and parameters: {'weight_class_0': 0.9694688475913723, 'weight_class_1': 9.867371316157517, 'weight_class_2': 9.139075765326162}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:22:57,312] Trial 1078 finished with value: 0.9493449175519061 and parameters: {'weight_class_0': 0.9930945510434995, 'weight_class_1': 8.274700220794758, 'weight_class_2': 7.859331037508346}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  36%|██████████████████████████████████████████████▉                                                                                   | 1083/3000 [00:22<00:41, 46.48it/s]

[I 2026-07-05 15:22:57,347] Trial 1079 finished with value: 0.9488916764263965 and parameters: {'weight_class_0': 1.0995810107961672, 'weight_class_1': 8.028746859215993, 'weight_class_2': 7.972610925505442}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:57,385] Trial 1080 finished with value: 0.9490257339656604 and parameters: {'weight_class_0': 1.014536162664947, 'weight_class_1': 8.120232276287574, 'weight_class_2': 7.345152859472265}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:57,395] Trial 1081 finished with value: 0.9496334064265505 and parameters: {'weight_class_0': 0.7386196488837277, 'weight_class_1': 8.367515384371105, 'weight_class_2': 7.966651456513157}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:57,436] Trial 1082 finished with value: 0.9490280507521485 and parameters: {'weight_class_0': 1.0517282015104, 'weight_class_1': 8.200112115893376, 'weight_class_2': 7.721634842687785}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:57,457] Trial 1083 finished with value: 0.9495741316416298 and parameters: {'weight_class_0': 0.7872655207875591, 'weight_class_1': 7.888319804053083, 'weight_class_2': 7.3184995714688945}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:22:57,473] Trial 1084 finished with value: 0.949517996241966 and parameters: {'weight_class_0': 0.7551537354112831, 'weight_class_1': 7.978469480750531, 'weight_class_2': 7.593982024981462}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:57,483] Trial 1085 finished with value: 0.9495634975938354 and parameters: {'weight_class_0': 0.7341655316274137, 'weight_class_1': 8.023401904477721, 'weight_class_2': 7.623110659599996}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:57,509] Trial 1086 finished with value: 0.9495277659153393 and parameters: {'weight_class_0': 0.7511074511816245, 'weight_class_1': 7.799193547711444, 'weight_class_2': 7.465874062843106}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  36%|███████████████████████████████████████████████▏                                                                                  | 1088/3000 [00:22<00:42, 44.52it/s]

[I 2026-07-05 15:22:57,549] Trial 1088 finished with value: 0.9495730187121824 and parameters: {'weight_class_0': 0.797472029650525, 'weight_class_1': 7.915781657620471, 'weight_class_2': 7.440224569919991}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:57,567] Trial 1087 finished with value: 0.949505319148944 and parameters: {'weight_class_0': 0.751549103512554, 'weight_class_1': 7.919000934770338, 'weight_class_2': 7.758658271768439}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  36%|███████████████████████████████████████████████▎                                                                                  | 1092/3000 [00:22<00:44, 42.83it/s]

[I 2026-07-05 15:22:57,603] Trial 1089 finished with value: 0.9496112987108424 and parameters: {'weight_class_0': 0.7012662047052642, 'weight_class_1': 8.038491913781378, 'weight_class_2': 7.328411406632212}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:57,612] Trial 1090 finished with value: 0.94955171766363 and parameters: {'weight_class_0': 0.7300380966069896, 'weight_class_1': 7.877413391131692, 'weight_class_2': 7.337383922036171}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:57,626] Trial 1091 finished with value: 0.9446617571493016 and parameters: {'weight_class_0': 1.7976006551116588, 'weight_class_1': 7.786310389134724, 'weight_class_2': 7.589739941862628}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:57,633] Trial 1092 finished with value: 0.949576549211685 and parameters: {'weight_class_0': 0.7772946722199503, 'weight_class_1': 7.75352382145096, 'weight_class_2': 7.329820623634598}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:22:57,662] Trial 1093 finished with value: 0.949521098708611 and parameters: {'weight_class_0': 0.8204074476740849, 'weight_class_1': 7.9210720990212575, 'weight_class_2': 7.357854337327992}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:57,719] Trial 1095 finished with value: 0.9415496292488186 and parameters: {'weight_class_0': 2.0723625777128722, 'weight_class_1': 7.618913326890712, 'weight_class_2': 7.033394702104398}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  37%|███████████████████████████████████████████████▌                                                                                  | 1097/3000 [00:22<00:44, 43.02it/s]

[I 2026-07-05 15:22:57,726] Trial 1094 finished with value: 0.944183526305861 and parameters: {'weight_class_0': 1.8358570492633843, 'weight_class_1': 7.97404066050931, 'weight_class_2': 7.146281221318318}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:57,750] Trial 1097 finished with value: 0.9495858935302319 and parameters: {'weight_class_0': 0.751012551734159, 'weight_class_1': 7.479073867765954, 'weight_class_2': 6.995799242149398}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:57,772] Trial 1096 finished with value: 0.9495404144322331 and parameters: {'weight_class_0': 0.7056898366874438, 'weight_class_1': 7.308251952059726, 'weight_class_2': 6.728843209264373}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  37%|███████████████████████████████████████████████▊                                                                                  | 1103/3000 [00:22<00:42, 44.96it/s]

[I 2026-07-05 15:22:57,781] Trial 1098 finished with value: 0.9495596759282486 and parameters: {'weight_class_0': 0.676474655762941, 'weight_class_1': 7.2490428960848154, 'weight_class_2': 6.414996144720878}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:57,800] Trial 1099 finished with value: 0.9495654442448971 and parameters: {'weight_class_0': 0.6802390587890488, 'weight_class_1': 9.931955064183944, 'weight_class_2': 6.8733549193437}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:57,803] Trial 1100 finished with value: 0.9495646056657764 and parameters: {'weight_class_0': 0.6703551749132061, 'weight_class_1': 9.882171066861526, 'weight_class_2': 6.7731593548310896}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:57,831] Trial 1101 finished with value: 0.9496262241965607 and parameters: {'weight_class_0': 0.6937486894166823, 'weight_class_1': 9.948987971445407, 'weight_class_2': 6.350838306351716}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:57,861] Trial 1102 finished with value: 0.9493012017565724 and parameters: {'weight_class_0': 0.871252775901644, 'weight_class_1': 9.825666184594214, 'weight_class_2': 6.408786191007079}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:57,906] Trial 1103 finished with value: 0.9495700020149475 and parameters: {'weight_class_0': 0.6664652181789243, 'weight_class_1': 7.189724066126829, 'weight_class_2': 6.2943608643305895}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:22:57,910] Trial 1104 finished with value: 0.9495645365552692 and parameters: {'weight_class_0': 0.6840058445866642, 'weight_class_1': 7.372870738818908, 'weight_class_2': 6.351998928722973}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  37%|████████████████████████████████████████████████                                                                                  | 1108/3000 [00:22<00:42, 44.64it/s]

[I 2026-07-05 15:22:57,944] Trial 1105 finished with value: 0.9496237586801314 and parameters: {'weight_class_0': 0.6877159860631946, 'weight_class_1': 9.603326466244852, 'weight_class_2': 6.35190024419033}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:57,966] Trial 1106 finished with value: 0.9495760653808117 and parameters: {'weight_class_0': 0.6673332775841244, 'weight_class_1': 9.935782645634143, 'weight_class_2': 6.041440152283023}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:57,979] Trial 1107 finished with value: 0.9495962083343699 and parameters: {'weight_class_0': 0.6561443009091182, 'weight_class_1': 9.444030401885081, 'weight_class_2': 6.322511969252993}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:58,022] Trial 1109 finished with value: 0.9489687632199156 and parameters: {'weight_class_0': 0.8807915572719165, 'weight_class_1': 6.930925245791854, 'weight_class_2': 6.2691649115546975}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  37%|████████████████████████████████████████████████▏                                                                                 | 1113/3000 [00:23<00:42, 44.84it/s]

[I 2026-07-05 15:22:58,027] Trial 1108 finished with value: 0.9496750955860799 and parameters: {'weight_class_0': 0.8532368090314759, 'weight_class_1': 9.991507246573494, 'weight_class_2': 9.878788341033932}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:58,067] Trial 1110 finished with value: 0.9487834284688826 and parameters: {'weight_class_0': 0.896608677256723, 'weight_class_1': 6.929778332510878, 'weight_class_2': 5.969013161589489}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:58,090] Trial 1111 finished with value: 0.9493346559474082 and parameters: {'weight_class_0': 0.8893108469709158, 'weight_class_1': 7.1072953047210525, 'weight_class_2': 8.499546027276448}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:58,106] Trial 1113 finished with value: 0.9492546699044423 and parameters: {'weight_class_0': 0.6424106324941835, 'weight_class_1': 7.323836181466078, 'weight_class_2': 9.922090359852126}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:58,121] Trial 1112 finished with value: 0.9493151261149334 and parameters: {'weight_class_0': 0.8823147615715669, 'weight_class_1': 6.788730516428271, 'weight_class_2': 8.578124802207507}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  37%|████████████████████████████████████████████████▎                                                                                 | 1114/3000 [00:23<00:42, 44.84it/s]

[I 2026-07-05 15:22:58,152] Trial 1114 finished with value: 0.9496343033837739 and parameters: {'weight_class_0': 0.8417163316123726, 'weight_class_1': 9.924265190127098, 'weight_class_2': 8.830700267328739}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  37%|████████████████████████████████████████████████▍                                                                                 | 1118/3000 [00:23<00:41, 44.95it/s]

[I 2026-07-05 15:22:58,156] Trial 1115 finished with value: 0.9492678856235189 and parameters: {'weight_class_0': 0.8632730765601984, 'weight_class_1': 6.794789767916377, 'weight_class_2': 8.620857386068288}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:58,204] Trial 1116 finished with value: 0.9357177588853959 and parameters: {'weight_class_0': 3.232683703932187, 'weight_class_1': 9.866026165841303, 'weight_class_2': 8.493181798835531}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:58,209] Trial 1117 finished with value: 0.9492639223649082 and parameters: {'weight_class_0': 0.9128145418683823, 'weight_class_1': 6.974662811994335, 'weight_class_2': 8.424403317703993}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:58,231] Trial 1118 finished with value: 0.949292830085673 and parameters: {'weight_class_0': 0.9086410017368367, 'weight_class_1': 6.88909531628453, 'weight_class_2': 8.450958282926441}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:22:58,261] Trial 1120 finished with value: 0.9493325008645122 and parameters: {'weight_class_0': 0.8464833449012407, 'weight_class_1': 6.869340729387093, 'weight_class_2': 8.68955459767337}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:58,269] Trial 1119 finished with value: 0.9492015982178995 and parameters: {'weight_class_0': 0.9746198275993189, 'weight_class_1': 7.178556676997596, 'weight_class_2': 9.713563489673867}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:58,300] Trial 1121 finished with value: 0.9495947880890659 and parameters: {'weight_class_0': 0.8999146775072031, 'weight_class_1': 9.992606519659079, 'weight_class_2': 9.657976499838655}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:58,351] Trial 1122 finished with value: 0.949335714813817 and parameters: {'weight_class_0': 0.8890673113503231, 'weight_class_1': 7.051308271314106, 'weight_class_2': 8.751030002555908}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  37%|████████████████████████████████████████████████▋                                                                                 | 1123/3000 [00:23<00:42, 44.20it/s]

[I 2026-07-05 15:22:58,353] Trial 1123 finished with value: 0.9494240168488218 and parameters: {'weight_class_0': 0.5943703056063535, 'weight_class_1': 8.472714019694914, 'weight_class_2': 8.815327171782336}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  38%|████████████████████████████████████████████████▊                                                                                 | 1127/3000 [00:23<00:42, 44.20it/s]

[I 2026-07-05 15:22:58,404] Trial 1124 finished with value: 0.9491915430274668 and parameters: {'weight_class_0': 0.5737143260931428, 'weight_class_1': 8.291607397950095, 'weight_class_2': 9.81320732350516}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:58,415] Trial 1126 finished with value: 0.9494539230917245 and parameters: {'weight_class_0': 0.6023143442427545, 'weight_class_1': 8.217081196468602, 'weight_class_2': 8.650229274477843}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:58,426] Trial 1125 finished with value: 0.9492989637960699 and parameters: {'weight_class_0': 0.6082915262620961, 'weight_class_1': 8.32143429386152, 'weight_class_2': 9.887989983066857}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:58,445] Trial 1127 finished with value: 0.9494472002877213 and parameters: {'weight_class_0': 0.6479894920798861, 'weight_class_1': 8.319854428623135, 'weight_class_2': 9.645209643394315}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  38%|█████████████████████████████████████████████████                                                                                 | 1132/3000 [00:23<00:41, 44.53it/s]

[I 2026-07-05 15:22:58,456] Trial 1128 finished with value: 0.949398883497361 and parameters: {'weight_class_0': 0.6416314335904391, 'weight_class_1': 9.952483294191467, 'weight_class_2': 9.743180108633931}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:58,480] Trial 1129 finished with value: 0.9493013242138687 and parameters: {'weight_class_0': 0.6127442125641402, 'weight_class_1': 8.028159577591923, 'weight_class_2': 9.810360796774571}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:58,487] Trial 1130 finished with value: 0.9493413793735092 and parameters: {'weight_class_0': 0.5886408745286119, 'weight_class_1': 8.45898253987919, 'weight_class_2': 9.328374581227166}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:58,517] Trial 1131 finished with value: 0.9492345940541972 and parameters: {'weight_class_0': 0.567444778398849, 'weight_class_1': 9.947795892945473, 'weight_class_2': 9.562707090639474}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:58,529] Trial 1132 finished with value: 0.9496848102094736 and parameters: {'weight_class_0': 0.6305005225825477, 'weight_class_1': 8.405203216463786, 'weight_class_2': 7.821043195191555}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  38%|█████████████████████████████████████████████████▏                                                                                | 1134/3000 [00:23<00:40, 45.89it/s]

[I 2026-07-05 15:22:58,564] Trial 1133 finished with value: 0.9492802074721945 and parameters: {'weight_class_0': 0.5999790765915932, 'weight_class_1': 7.995644401049302, 'weight_class_2': 9.992749277116996}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:58,597] Trial 1134 finished with value: 0.9496246698368517 and parameters: {'weight_class_0': 0.5942435481022199, 'weight_class_1': 8.270712379003538, 'weight_class_2': 5.753301862311387}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  38%|█████████████████████████████████████████████████▏                                                                                | 1136/3000 [00:23<00:40, 45.89it/s]

[I 2026-07-05 15:22:58,600] Trial 1135 finished with value: 0.9491760786686093 and parameters: {'weight_class_0': 0.5779536249929786, 'weight_class_1': 8.445685081275023, 'weight_class_2': 9.914601037009016}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:58,666] Trial 1137 finished with value: 0.9496067100283344 and parameters: {'weight_class_0': 0.6135563227220141, 'weight_class_1': 9.936289323604358, 'weight_class_2': 5.709602201952525}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  38%|█████████████████████████████████████████████████▍                                                                                | 1141/3000 [00:23<00:42, 44.22it/s]

[I 2026-07-05 15:22:58,667] Trial 1136 finished with value: 0.9496279502470918 and parameters: {'weight_class_0': 0.6156577387483855, 'weight_class_1': 8.338620310788865, 'weight_class_2': 6.069525617206978}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:58,692] Trial 1138 finished with value: 0.9495378169369871 and parameters: {'weight_class_0': 0.5373918776234884, 'weight_class_1': 9.926718959747838, 'weight_class_2': 5.511871988425628}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:58,729] Trial 1139 finished with value: 0.9477862508632929 and parameters: {'weight_class_0': 1.1268172925014508, 'weight_class_1': 8.43990331100542, 'weight_class_2': 5.683143316866908}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:58,756] Trial 1140 finished with value: 0.6582246178013317 and parameters: {'weight_class_0': 1.1975010828090542, 'weight_class_1': 0.0034997507354800486, 'weight_class_2': 5.600075604822319}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:58,759] Trial 1141 finished with value: 0.9475037481978116 and parameters: {'weight_class_0': 1.1519537867483467, 'weight_class_1': 6.882823314041052, 'weight_class_2': 6.065192434439109}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:22:58,792] Trial 1143 finished with value: 0.9483644371779887 and parameters: {'weight_class_0': 1.232331960459037, 'weight_class_1': 8.31184613189535, 'weight_class_2': 7.68446692332837}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  38%|█████████████████████████████████████████████████▋                                                                                | 1147/3000 [00:23<00:42, 43.99it/s]

[I 2026-07-05 15:22:58,796] Trial 1142 finished with value: 0.9495530283181052 and parameters: {'weight_class_0': 0.7444216596085904, 'weight_class_1': 8.038786940569857, 'weight_class_2': 7.667141129867091}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:58,827] Trial 1144 finished with value: 0.9483208525390984 and parameters: {'weight_class_0': 1.2495498841901884, 'weight_class_1': 8.312669693149411, 'weight_class_2': 7.674735497535205}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:58,829] Trial 1145 finished with value: 0.9496547573591861 and parameters: {'weight_class_0': 0.7877041496025315, 'weight_class_1': 9.884473908719452, 'weight_class_2': 7.587744756759489}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:58,845] Trial 1147 finished with value: 0.9481219250176656 and parameters: {'weight_class_0': 1.2567961811738555, 'weight_class_1': 8.336376579865272, 'weight_class_2': 7.285585163873005}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:58,849] Trial 1146 finished with value: 0.9483836578645471 and parameters: {'weight_class_0': 1.2157575810900254, 'weight_class_1': 8.423163720096627, 'weight_class_2': 7.5632872567558405}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:22:58,881] Trial 1148 finished with value: 0.9479995372420241 and parameters: {'weight_class_0': 1.159385410351335, 'weight_class_1': 6.712580934752123, 'weight_class_2': 7.432267433039561}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:58,929] Trial 1149 finished with value: 0.9494905087616526 and parameters: {'weight_class_0': 0.7599495299505822, 'weight_class_1': 6.852140236168631, 'weight_class_2': 7.415437413698396}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:58,969] Trial 1150 finished with value: 0.949446313338008 and parameters: {'weight_class_0': 0.7457270356325821, 'weight_class_1': 6.828561895247634, 'weight_class_2': 7.713120231757606}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:22:58,995] Trial 1151 finished with value: 0.949467858153565 and parameters: {'weight_class_0': 0.7758340356029426, 'weight_class_1': 7.141224009751723, 'weight_class_2': 7.727058231332276}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  39%|██████████████████████████████████████████████████                                                                                | 1156/3000 [00:24<00:42, 43.67it/s]

[I 2026-07-05 15:22:59,002] Trial 1152 finished with value: 0.6593121465369096 and parameters: {'weight_class_0': 0.004567750938568444, 'weight_class_1': 6.931416246890585, 'weight_class_2': 7.507113318219228}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:59,040] Trial 1153 finished with value: 0.9494505149665358 and parameters: {'weight_class_0': 0.747524463390938, 'weight_class_1': 6.819876111033955, 'weight_class_2': 7.704083631635024}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:59,050] Trial 1154 finished with value: 0.949475142570102 and parameters: {'weight_class_0': 0.7719288498177077, 'weight_class_1': 6.8695729177803, 'weight_class_2': 7.449298115529432}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:59,087] Trial 1155 finished with value: 0.9495316445686148 and parameters: {'weight_class_0': 0.7760950841462971, 'weight_class_1': 8.349590995717707, 'weight_class_2': 7.7910295030486845}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:59,088] Trial 1156 finished with value: 0.9496535418445711 and parameters: {'weight_class_0': 0.7868892542672904, 'weight_class_1': 9.975908083583604, 'weight_class_2': 7.777143182085744}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:22:59,096] Trial 1157 finished with value: 0.9494591370176689 and parameters: {'weight_class_0': 0.774389726864499, 'weight_class_1': 6.90086422868043, 'weight_class_2': 7.891942993600297}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:59,138] Trial 1159 finished with value: 0.949516488232624 and parameters: {'weight_class_0': 0.8119228026552283, 'weight_class_1': 8.524109331704313, 'weight_class_2': 8.288063221914468}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:59,139] Trial 1158 finished with value: 0.94953194780346 and parameters: {'weight_class_0': 0.8083872228421419, 'weight_class_1': 8.465462904599306, 'weight_class_2': 7.755328069630264}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:59,164] Trial 1160 finished with value: 0.949686705359699 and parameters: {'weight_class_0': 0.7956296746900953, 'weight_class_1': 9.96944446703355, 'weight_class_2': 7.4962264704435695}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:22:59,182] Trial 1161 finished with value: 0.9496067328246475 and parameters: {'weight_class_0': 0.7875854446151309, 'weight_class_1': 9.96453174205428, 'weight_class_2': 7.956777223842026}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  39%|██████████████████████████████████████████████████▍                                                                               | 1165/3000 [00:24<00:42, 43.55it/s]

[I 2026-07-05 15:22:59,226] Trial 1162 finished with value: 0.9496006387442053 and parameters: {'weight_class_0': 0.815519743983624, 'weight_class_1': 9.897967307910447, 'weight_class_2': 8.207458103803523}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:59,254] Trial 1163 finished with value: 0.9495146167469629 and parameters: {'weight_class_0': 0.8191832438151148, 'weight_class_1': 8.344764186542895, 'weight_class_2': 8.180037289367316}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:59,294] Trial 1164 finished with value: 0.949240003998186 and parameters: {'weight_class_0': 0.8999549877295413, 'weight_class_1': 9.942567632137504, 'weight_class_2': 6.653804530878379}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:59,311] Trial 1165 finished with value: 0.9491300575744758 and parameters: {'weight_class_0': 0.9523407914363125, 'weight_class_1': 9.905867860442207, 'weight_class_2': 6.749322837672777}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  39%|██████████████████████████████████████████████████▋                                                                               | 1169/3000 [00:24<00:42, 43.55it/s]

[I 2026-07-05 15:22:59,327] Trial 1166 finished with value: 0.9488317162767804 and parameters: {'weight_class_0': 1.0090829595413997, 'weight_class_1': 9.847019637063608, 'weight_class_2': 6.495827931807864}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:59,334] Trial 1167 finished with value: 0.9465471419647971 and parameters: {'weight_class_0': 1.517947851958222, 'weight_class_1': 9.983361447686963, 'weight_class_2': 6.508699077344901}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:59,387] Trial 1168 finished with value: 0.9489951914636591 and parameters: {'weight_class_0': 0.9584653355370703, 'weight_class_1': 8.613944577497893, 'weight_class_2': 6.4397824691755865}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:59,391] Trial 1169 finished with value: 0.9486239484525797 and parameters: {'weight_class_0': 1.0509535839478208, 'weight_class_1': 8.363414286483051, 'weight_class_2': 6.559336860943171}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  39%|██████████████████████████████████████████████████▋                                                                               | 1170/3000 [00:24<00:42, 43.18it/s]

[I 2026-07-05 15:22:59,418] Trial 1170 finished with value: 0.949017426264504 and parameters: {'weight_class_0': 0.9776607642159424, 'weight_class_1': 9.93584321972123, 'weight_class_2': 6.534242054853034}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  39%|██████████████████████████████████████████████████▊                                                                               | 1174/3000 [00:24<00:42, 43.18it/s]

[I 2026-07-05 15:22:59,430] Trial 1172 finished with value: 0.9457214117587304 and parameters: {'weight_class_0': 1.5868461701428642, 'weight_class_1': 8.464175195937436, 'weight_class_2': 6.666042139889539}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:59,462] Trial 1171 finished with value: 0.9455113976899879 and parameters: {'weight_class_0': 1.590261815145326, 'weight_class_1': 8.579992683845747, 'weight_class_2': 6.418911713400959}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:59,480] Trial 1173 finished with value: 0.9496169647096879 and parameters: {'weight_class_0': 0.5220161552049494, 'weight_class_1': 8.447905402165281, 'weight_class_2': 6.4624055511988425}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:59,518] Trial 1174 finished with value: 0.9489402780036645 and parameters: {'weight_class_0': 0.9674822966973184, 'weight_class_1': 8.419099024237115, 'weight_class_2': 6.453148875472143}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  39%|███████████████████████████████████████████████████                                                                               | 1178/3000 [00:24<00:41, 43.65it/s]

[I 2026-07-05 15:22:59,532] Trial 1175 finished with value: 0.9489830345979593 and parameters: {'weight_class_0': 0.9639489487723287, 'weight_class_1': 8.542518265232708, 'weight_class_2': 6.443585271369907}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:59,572] Trial 1176 finished with value: 0.949676796915155 and parameters: {'weight_class_0': 0.6512363230012125, 'weight_class_1': 8.285251245282204, 'weight_class_2': 6.083808984524769}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:59,579] Trial 1177 finished with value: 0.9496772358319531 and parameters: {'weight_class_0': 0.6852053507233321, 'weight_class_1': 8.306055395212468, 'weight_class_2': 5.923756570320103}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:59,612] Trial 1178 finished with value: 0.9496539488904299 and parameters: {'weight_class_0': 0.6785153510344136, 'weight_class_1': 8.281263821167355, 'weight_class_2': 5.986134375726432}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:22:59,613] Trial 1179 finished with value: 0.948951679320783 and parameters: {'weight_class_0': 0.5313442370997266, 'weight_class_1': 7.829396771824549, 'weight_class_2': 9.974384173921864}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  39%|███████████████████████████████████████████████████▎                                                                              | 1183/3000 [00:24<00:41, 43.48it/s]

[I 2026-07-05 15:22:59,638] Trial 1180 finished with value: 0.9492131069410531 and parameters: {'weight_class_0': 0.660179446180615, 'weight_class_1': 6.760132385443494, 'weight_class_2': 9.913518871207044}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:59,684] Trial 1181 finished with value: 0.9489115322132965 and parameters: {'weight_class_0': 0.5264450016960972, 'weight_class_1': 7.020403271482739, 'weight_class_2': 9.826382143022698}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:59,699] Trial 1182 finished with value: 0.9492149725156432 and parameters: {'weight_class_0': 0.6639050359608321, 'weight_class_1': 6.742076543755209, 'weight_class_2': 9.91519563903976}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:59,706] Trial 1183 finished with value: 0.9488865021255544 and parameters: {'weight_class_0': 0.5182800557580242, 'weight_class_1': 6.774366350814773, 'weight_class_2': 9.890981696163756}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  40%|███████████████████████████████████████████████████▍                                                                              | 1188/3000 [00:24<00:40, 44.53it/s]

[I 2026-07-05 15:22:59,718] Trial 1184 finished with value: 0.9495658742926624 and parameters: {'weight_class_0': 0.6333862871364486, 'weight_class_1': 6.810927147965263, 'weight_class_2': 5.87810365381965}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:59,756] Trial 1185 finished with value: 0.9492242881552654 and parameters: {'weight_class_0': 0.6685345041235009, 'weight_class_1': 6.81589143994403, 'weight_class_2': 9.885845781097217}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:59,787] Trial 1186 finished with value: 0.9494909475471945 and parameters: {'weight_class_0': 0.6630504812759481, 'weight_class_1': 6.990109319678401, 'weight_class_2': 5.526761445366223}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:59,800] Trial 1187 finished with value: 0.9495538091074439 and parameters: {'weight_class_0': 0.6332910101562997, 'weight_class_1': 6.752573726144085, 'weight_class_2': 5.462804378208461}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:59,820] Trial 1188 finished with value: 0.9495873867643224 and parameters: {'weight_class_0': 0.6582851095878484, 'weight_class_1': 7.4590449794001, 'weight_class_2': 5.470913778262582}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  40%|███████████████████████████████████████████████████▌                                                                              | 1189/3000 [00:24<00:40, 44.53it/s]

[I 2026-07-05 15:22:59,837] Trial 1189 finished with value: 0.949628374183045 and parameters: {'weight_class_0': 0.6510309269563563, 'weight_class_1': 9.99946693459932, 'weight_class_2': 5.508726030152738}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  40%|███████████████████████████████████████████████████▋                                                                              | 1192/3000 [00:24<00:41, 43.39it/s]

[I 2026-07-05 15:22:59,875] Trial 1190 finished with value: 0.9495423773310113 and parameters: {'weight_class_0': 0.6601700092359344, 'weight_class_1': 7.112847840902631, 'weight_class_2': 5.525770254902723}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:59,908] Trial 1191 finished with value: 0.949291662666107 and parameters: {'weight_class_0': 0.7270545043268402, 'weight_class_1': 7.174666726240203, 'weight_class_2': 5.511067841827716}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:59,929] Trial 1192 finished with value: 0.9495134156500044 and parameters: {'weight_class_0': 0.6675812751118544, 'weight_class_1': 6.956120788050901, 'weight_class_2': 5.6183058525212735}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  40%|███████████████████████████████████████████████████▊                                                                              | 1197/3000 [00:25<00:42, 42.56it/s]

[I 2026-07-05 15:22:59,939] Trial 1193 finished with value: 0.9496067916882741 and parameters: {'weight_class_0': 0.6734476090248336, 'weight_class_1': 9.800900227087148, 'weight_class_2': 5.5083243940844}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:59,974] Trial 1194 finished with value: 0.9496429075704377 and parameters: {'weight_class_0': 0.6224864163999451, 'weight_class_1': 8.11060277154291, 'weight_class_2': 5.4739628244558665}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:22:59,990] Trial 1195 finished with value: 0.9495713107775917 and parameters: {'weight_class_0': 0.6737471384174288, 'weight_class_1': 8.34799808942885, 'weight_class_2': 5.403981472132896}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:00,004] Trial 1196 finished with value: 0.9496043045270404 and parameters: {'weight_class_0': 0.6583006059323825, 'weight_class_1': 9.991406352859915, 'weight_class_2': 5.430145205691143}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:00,031] Trial 1197 finished with value: 0.949576799675961 and parameters: {'weight_class_0': 0.6333721322092078, 'weight_class_1': 9.799257934311159, 'weight_class_2': 5.8251539547516575}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  40%|███████████████████████████████████████████████████▉                                                                              | 1198/3000 [00:25<00:42, 42.56it/s]

[I 2026-07-05 15:23:00,056] Trial 1198 finished with value: 0.9494999454156251 and parameters: {'weight_class_0': 0.7017067851806766, 'weight_class_1': 9.987836264003903, 'weight_class_2': 5.434952010065398}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  40%|████████████████████████████████████████████████████                                                                              | 1201/3000 [00:25<00:42, 42.79it/s]

[I 2026-07-05 15:23:00,084] Trial 1199 finished with value: 0.9496719030475268 and parameters: {'weight_class_0': 0.680096476930214, 'weight_class_1': 9.844872602772549, 'weight_class_2': 7.641574526160296}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:00,116] Trial 1200 finished with value: 0.9496515717060791 and parameters: {'weight_class_0': 0.7003759603850398, 'weight_class_1': 8.39388147504647, 'weight_class_2': 8.293379698723273}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:00,159] Trial 1201 finished with value: 0.9495803170941636 and parameters: {'weight_class_0': 0.8768655263800452, 'weight_class_1': 9.835195187995616, 'weight_class_2': 8.00755204894277}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  40%|████████████████████████████████████████████████████▎                                                                             | 1207/3000 [00:25<00:41, 43.38it/s]

[I 2026-07-05 15:23:00,165] Trial 1202 finished with value: 0.9496861613032448 and parameters: {'weight_class_0': 0.7267234552065402, 'weight_class_1': 9.89911371449585, 'weight_class_2': 8.532121551946256}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:00,172] Trial 1203 finished with value: 0.9495346151954132 and parameters: {'weight_class_0': 0.9097754951949225, 'weight_class_1': 9.801669626739178, 'weight_class_2': 8.093411148500005}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:00,183] Trial 1204 finished with value: 0.949550126274799 and parameters: {'weight_class_0': 0.9054003772991638, 'weight_class_1': 9.83402131119057, 'weight_class_2': 8.212017439032614}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:00,239] Trial 1205 finished with value: 0.9495145001061204 and parameters: {'weight_class_0': 0.9790210554854398, 'weight_class_1': 9.831638307889891, 'weight_class_2': 8.018523687539107}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:00,256] Trial 1206 finished with value: 0.9495174528148577 and parameters: {'weight_class_0': 0.9242395432974211, 'weight_class_1': 9.937281623716208, 'weight_class_2': 8.232782507541122}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:00,271] Trial 1207 finished with value: 0.9495986182612383 and parameters: {'weight_class_0': 0.8918562179202664, 'weight_class_1': 9.993934831156205, 'weight_class_2': 8.288327535019176}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  40%|████████████████████████████████████████████████████▎                                                                             | 1208/3000 [00:25<00:41, 43.38it/s]

[I 2026-07-05 15:23:00,290] Trial 1208 finished with value: 0.9494799187973806 and parameters: {'weight_class_0': 0.9330610728248424, 'weight_class_1': 7.979425683560293, 'weight_class_2': 8.00315044341126}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  40%|████████████████████████████████████████████████████▍                                                                             | 1211/3000 [00:25<00:40, 44.58it/s]

[I 2026-07-05 15:23:00,311] Trial 1209 finished with value: 0.9493114351430026 and parameters: {'weight_class_0': 0.5236811884907439, 'weight_class_1': 8.122018934318238, 'weight_class_2': 8.255507607836751}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:00,334] Trial 1210 finished with value: 0.6794613213978425 and parameters: {'weight_class_0': 0.011856526102078485, 'weight_class_1': 9.884741059764663, 'weight_class_2': 8.57124139149236}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:00,376] Trial 1211 finished with value: 0.9495303126805218 and parameters: {'weight_class_0': 0.9244043542699921, 'weight_class_1': 9.94576698923984, 'weight_class_2': 8.42581759926411}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  41%|████████████████████████████████████████████████████▋                                                                             | 1216/3000 [00:25<00:42, 42.35it/s]

[I 2026-07-05 15:23:00,377] Trial 1212 finished with value: 0.9494077885236308 and parameters: {'weight_class_0': 0.9875510944375697, 'weight_class_1': 8.167110219224304, 'weight_class_2': 8.147170366893418}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:00,421] Trial 1213 finished with value: 0.9493823571080738 and parameters: {'weight_class_0': 1.0283516128517312, 'weight_class_1': 9.939609682067767, 'weight_class_2': 8.1640730331969}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:00,446] Trial 1214 finished with value: 0.9492513888151853 and parameters: {'weight_class_0': 1.0905993755429946, 'weight_class_1': 9.920945970977025, 'weight_class_2': 8.25641654389596}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:00,452] Trial 1215 finished with value: 0.9489237769246196 and parameters: {'weight_class_0': 1.119871961895984, 'weight_class_1': 8.153946508225323, 'weight_class_2': 8.23902167226256}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:00,487] Trial 1216 finished with value: 0.9490219825287777 and parameters: {'weight_class_0': 1.088029332293054, 'weight_class_1': 8.244122512334489, 'weight_class_2': 8.118930375686908}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  41%|████████████████████████████████████████████████████▉                                                                             | 1221/3000 [00:25<00:40, 44.08it/s]

[I 2026-07-05 15:23:00,520] Trial 1217 finished with value: 0.8373729097343049 and parameters: {'weight_class_0': 1.0256198623779031, 'weight_class_1': 8.040038999287635, 'weight_class_2': 0.025047124697512246}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:00,524] Trial 1218 finished with value: 0.9490656944583984 and parameters: {'weight_class_0': 1.0058099940961482, 'weight_class_1': 8.195688851396483, 'weight_class_2': 7.258840021677982}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:00,538] Trial 1219 finished with value: 0.9485430932008275 and parameters: {'weight_class_0': 1.1231098018685841, 'weight_class_1': 7.945078164040082, 'weight_class_2': 7.155609604452137}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:00,566] Trial 1220 finished with value: 0.7930428038078833 and parameters: {'weight_class_0': 1.1334756712076077, 'weight_class_1': 0.030092173904917013, 'weight_class_2': 0.024996968052402806}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:00,600] Trial 1221 finished with value: 0.9487398507328567 and parameters: {'weight_class_0': 1.101037200424152, 'weight_class_1': 9.990980788559932, 'weight_class_2': 6.7356317169205875}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  41%|█████████████████████████████████████████████████████                                                                             | 1225/3000 [00:25<00:40, 44.08it/s]

[I 2026-07-05 15:23:00,623] Trial 1222 finished with value: 0.9496450929900369 and parameters: {'weight_class_0': 0.7589323056740349, 'weight_class_1': 9.995313497863439, 'weight_class_2': 7.1051657617431045}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:00,635] Trial 1223 finished with value: 0.9495407069679854 and parameters: {'weight_class_0': 0.8209229232334864, 'weight_class_1': 8.144385917740207, 'weight_class_2': 6.92735819084969}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:00,671] Trial 1224 finished with value: 0.9494786956526108 and parameters: {'weight_class_0': 0.7746469881595905, 'weight_class_1': 7.939784876845123, 'weight_class_2': 9.866398693555707}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:00,689] Trial 1225 finished with value: 0.9495311412391009 and parameters: {'weight_class_0': 0.7913406779083054, 'weight_class_1': 7.621164042529937, 'weight_class_2': 6.760608249240775}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  41%|█████████████████████████████████████████████████████▎                                                                            | 1230/3000 [00:25<00:41, 42.27it/s]

[I 2026-07-05 15:23:00,710] Trial 1226 finished with value: 0.9494620961640267 and parameters: {'weight_class_0': 0.8130119013347766, 'weight_class_1': 7.965708786416515, 'weight_class_2': 6.776369233615588}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:00,759] Trial 1229 finished with value: 0.9493752708562108 and parameters: {'weight_class_0': 0.781273076182523, 'weight_class_1': 6.261737478549792, 'weight_class_2': 6.694933859786369}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:00,764] Trial 1227 finished with value: 0.9491554032982868 and parameters: {'weight_class_0': 0.7977765265619217, 'weight_class_1': 6.343793216129093, 'weight_class_2': 9.968618033212424}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:00,780] Trial 1228 finished with value: 0.9491736455115044 and parameters: {'weight_class_0': 0.7812589900088993, 'weight_class_1': 6.280254158449776, 'weight_class_2': 9.861838471367248}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:00,805] Trial 1230 finished with value: 0.9492090645021886 and parameters: {'weight_class_0': 0.8497208661199841, 'weight_class_1': 6.085964894462065, 'weight_class_2': 6.896315591492694}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  41%|█████████████████████████████████████████████████████▍                                                                            | 1234/3000 [00:25<00:42, 41.70it/s]

[I 2026-07-05 15:23:00,837] Trial 1231 finished with value: 0.9491885577721004 and parameters: {'weight_class_0': 0.7772030447604145, 'weight_class_1': 6.269585005484341, 'weight_class_2': 9.800331182532908}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:00,847] Trial 1232 finished with value: 0.9492022864836379 and parameters: {'weight_class_0': 0.8189207461929021, 'weight_class_1': 6.258508164570852, 'weight_class_2': 6.593935177016674}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:00,872] Trial 1233 finished with value: 0.949346331531871 and parameters: {'weight_class_0': 0.7879025678893368, 'weight_class_1': 6.350211493267823, 'weight_class_2': 7.055783346663741}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:00,900] Trial 1234 finished with value: 0.9493965819253048 and parameters: {'weight_class_0': 0.7955025708151037, 'weight_class_1': 6.488925617513263, 'weight_class_2': 6.802586240052635}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:00,919] Trial 1235 finished with value: 0.9495800042296835 and parameters: {'weight_class_0': 0.5436082551752469, 'weight_class_1': 6.340635213427163, 'weight_class_2': 6.749643574530092}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:00,974] Trial 1236 finished with value: 0.9495836204575708 and parameters: {'weight_class_0': 0.52172345435185, 'weight_class_1': 6.344596812169304, 'weight_class_2': 6.830711727866375}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:00,975] Trial 1237 finished with value: 0.9488220126077436 and parameters: {'weight_class_0': 0.5265120426189719, 'weight_class_1': 6.159455882612929, 'weight_class_2': 9.817856432799319}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:01,005] Trial 1238 finished with value: 0.9495849911889528 and parameters: {'weight_class_0': 0.5032077942910941, 'weight_class_1': 6.280993657224259, 'weight_class_2': 6.6102808352018005}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:01,012] Trial 1239 finished with value: 0.9488192424660551 and parameters: {'weight_class_0': 0.5300746103937248, 'weight_class_1': 5.979967527080089, 'weight_class_2': 9.878066348168531}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:01,027] Trial 1240 finished with value: 0.9495961828348932 and parameters: {'weight_class_0': 0.5362476563318996, 'weight_class_1': 6.87487748914669, 'weight_class_2': 6.949017300619189}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:01,070] Trial 1241 finished with value: 0.9489060804801577 and parameters: {'weight_class_0': 0.5273940692613404, 'weight_class_1': 6.958262355594341, 'weight_class_2': 9.927082209750465}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:01,112] Trial 1243 finished with value: 0.9493426858157172 and parameters: {'weight_class_0': 0.5382667268446499, 'weight_class_1': 7.24621449412884, 'weight_class_2': 8.54576464067995}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:01,127] Trial 1242 finished with value: 0.9489096215141855 and parameters: {'weight_class_0': 0.5345105882850485, 'weight_class_1': 7.026065510558399, 'weight_class_2': 9.953230592158148}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:01,142] Trial 1244 finished with value: 0.9496451917538437 and parameters: {'weight_class_0': 0.5269538658590345, 'weight_class_1': 7.206850967155912, 'weight_class_2': 6.600350271387871}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:01,170] Trial 1246 finished with value: 0.8908247983377912 and parameters: {'weight_class_0': 0.03806637831495828, 'weight_class_1': 7.2874304623450925, 'weight_class_2': 5.103548722247424}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:01,177] Trial 1245 finished with value: 0.9496291292673136 and parameters: {'weight_class_0': 0.5255206305152111, 'weight_class_1': 7.433480981990753, 'weight_class_2': 5.094102328810911}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:01,207] Trial 1247 finished with value: 0.9489849563257645 and parameters: {'weight_class_0': 0.5415539535984067, 'weight_class_1': 7.528545887419006, 'weight_class_2': 9.90300448413859}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:01,233] Trial 1248 finished with value: 0.949616970332649 and parameters: {'weight_class_0': 0.5605129745000409, 'weight_class_1': 8.062805832395536, 'weight_class_2': 5.056231738443035}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:01,264] Trial 1249 finished with value: 0.9106835268868191 and parameters: {'weight_class_0': 0.6162912448802464, 'weight_class_1': 9.99531767619368, 'weight_class_2': 0.6056862255435046}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  42%|██████████████████████████████████████████████████████▎                                                                           | 1252/3000 [00:26<00:41, 42.31it/s]

[I 2026-07-05 15:23:01,286] Trial 1250 finished with value: 0.8752231061348983 and parameters: {'weight_class_0': 0.6359282517250749, 'weight_class_1': 0.05129409003697795, 'weight_class_2': 5.191802063882912}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:01,313] Trial 1251 finished with value: 0.9496438618855106 and parameters: {'weight_class_0': 0.609277467085146, 'weight_class_1': 8.25918998239415, 'weight_class_2': 5.179289417127932}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:01,349] Trial 1253 finished with value: 0.9496249514679181 and parameters: {'weight_class_0': 0.6423496449094152, 'weight_class_1': 8.465514312784705, 'weight_class_2': 5.257867132688965}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:01,364] Trial 1252 finished with value: 0.8211040121620284 and parameters: {'weight_class_0': 0.02567423234267119, 'weight_class_1': 8.279301254218842, 'weight_class_2': 5.336024383116545}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:01,393] Trial 1254 finished with value: 0.9495854091930891 and parameters: {'weight_class_0': 0.6807148521036067, 'weight_class_1': 8.18401414423168, 'weight_class_2': 5.715686430875353}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:01,395] Trial 1255 finished with value: 0.9440100691890873 and parameters: {'weight_class_0': 1.4852638421883269, 'weight_class_1': 8.080955605820334, 'weight_class_2': 5.07449541151269}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:01,410] Trial 1256 finished with value: 0.9461501111292736 and parameters: {'weight_class_0': 1.337226805364259, 'weight_class_1': 9.969376194068964, 'weight_class_2': 5.203374922443332}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:01,436] Trial 1258 finished with value: 0.9496241283141407 and parameters: {'weight_class_0': 0.6628992197982007, 'weight_class_1': 8.399415993750516, 'weight_class_2': 5.562145494313293}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:01,476] Trial 1257 finished with value: 0.9458975937426609 and parameters: {'weight_class_0': 1.362064990951731, 'weight_class_1': 8.568829513131991, 'weight_class_2': 5.455406459147584}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  42%|██████████████████████████████████████████████████████▋                                                                           | 1262/3000 [00:26<00:41, 41.84it/s]

[I 2026-07-05 15:23:01,481] Trial 1259 finished with value: 0.9496433014244858 and parameters: {'weight_class_0': 0.6618955556112356, 'weight_class_1': 8.402010367087057, 'weight_class_2': 6.031151041615771}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:01,482] Trial 1260 finished with value: 0.8744155112833093 and parameters: {'weight_class_0': 0.6481080190229269, 'weight_class_1': 0.05540613919555714, 'weight_class_2': 8.321850414795342}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:01,534] Trial 1261 finished with value: 0.9479478391960857 and parameters: {'weight_class_0': 1.397347159462069, 'weight_class_1': 8.498759199437336, 'weight_class_2': 8.194336507017528}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:01,555] Trial 1262 finished with value: 0.9496427284835133 and parameters: {'weight_class_0': 0.6749098339131748, 'weight_class_1': 9.992910689082345, 'weight_class_2': 7.918524114825428}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  42%|██████████████████████████████████████████████████████▉                                                                           | 1267/3000 [00:26<00:41, 41.66it/s]

[I 2026-07-05 15:23:01,616] Trial 1263 finished with value: 0.9495946388451415 and parameters: {'weight_class_0': 0.6952071492406804, 'weight_class_1': 8.200688231669114, 'weight_class_2': 8.430777716827462}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:01,623] Trial 1265 finished with value: 0.8572731888030827 and parameters: {'weight_class_0': 0.7114703479474097, 'weight_class_1': 9.995746054339342, 'weight_class_2': 0.040308375582864125}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:01,633] Trial 1264 finished with value: 0.9482970912761215 and parameters: {'weight_class_0': 1.2905488549199147, 'weight_class_1': 8.339360569274094, 'weight_class_2': 8.283455538844118}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:01,646] Trial 1266 finished with value: 0.9496166532225899 and parameters: {'weight_class_0': 0.7160842554834704, 'weight_class_1': 8.007678059878033, 'weight_class_2': 8.320195580684924}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:01,678] Trial 1268 finished with value: 0.9496484314984489 and parameters: {'weight_class_0': 0.7195262680287704, 'weight_class_1': 8.605104280765149, 'weight_class_2': 7.813162427080924}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  42%|███████████████████████████████████████████████████████▏                                                                          | 1273/3000 [00:26<00:39, 43.78it/s]

[I 2026-07-05 15:23:01,704] Trial 1267 finished with value: 0.6442019606824276 and parameters: {'weight_class_0': 0.0013280910738810727, 'weight_class_1': 9.996002507839842, 'weight_class_2': 0.06607151849135162}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:01,717] Trial 1269 finished with value: 0.949693093250945 and parameters: {'weight_class_0': 0.7254418458483795, 'weight_class_1': 8.589205146968535, 'weight_class_2': 8.231883122819777}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:01,734] Trial 1270 finished with value: 0.9496126301670031 and parameters: {'weight_class_0': 0.8705066059454762, 'weight_class_1': 9.842853704079555, 'weight_class_2': 8.261272320397017}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:01,758] Trial 1271 finished with value: 0.9496838228386405 and parameters: {'weight_class_0': 0.7304757661547434, 'weight_class_1': 8.617526532501747, 'weight_class_2': 8.233301996131633}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:01,788] Trial 1272 finished with value: 0.9489361294622753 and parameters: {'weight_class_0': 0.8704312378994107, 'weight_class_1': 5.744806881802062, 'weight_class_2': 8.289513562760638}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:01,816] Trial 1273 finished with value: 0.6822667140337345 and parameters: {'weight_class_0': 0.7457531713306659, 'weight_class_1': 5.769632262521968, 'weight_class_2': 0.0022413039464509545}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  43%|███████████████████████████████████████████████████████▎                                                                          | 1276/3000 [00:26<00:39, 43.77it/s]

[I 2026-07-05 15:23:01,830] Trial 1274 finished with value: 0.9487459742846124 and parameters: {'weight_class_0': 0.9428980516619409, 'weight_class_1': 5.608583377179493, 'weight_class_2': 8.006823519134436}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:01,867] Trial 1275 finished with value: 0.9487839673704813 and parameters: {'weight_class_0': 0.859490068845161, 'weight_class_1': 5.394306041395292, 'weight_class_2': 6.862135913563317}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:01,892] Trial 1276 finished with value: 0.9487389843415369 and parameters: {'weight_class_0': 0.8917672238980051, 'weight_class_1': 5.6451683942752755, 'weight_class_2': 6.933724851170538}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:01,941] Trial 1277 finished with value: 0.9495771052345695 and parameters: {'weight_class_0': 0.48003793822928614, 'weight_class_1': 6.062325509317366, 'weight_class_2': 6.447124962796464}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:01,948] Trial 1278 finished with value: 0.948428848605749 and parameters: {'weight_class_0': 0.9150387570572087, 'weight_class_1': 5.93329320526104, 'weight_class_2': 6.215453499941983}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:01,964] Trial 1279 finished with value: 0.9490120917715691 and parameters: {'weight_class_0': 0.8682309332238127, 'weight_class_1': 5.812123620499439, 'weight_class_2': 8.366425855967053}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:01,981] Trial 1280 finished with value: 0.9486747883879109 and parameters: {'weight_class_0': 0.9405085015919563, 'weight_class_1': 5.7461742819517765, 'weight_class_2': 9.984986283815362}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:01,999] Trial 1281 finished with value: 0.9487752467693139 and parameters: {'weight_class_0': 0.9258532432730449, 'weight_class_1': 5.777622058026988, 'weight_class_2': 8.78164774284124}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  43%|███████████████████████████████████████████████████████▋                                                                          | 1286/3000 [00:27<00:39, 43.43it/s]

[I 2026-07-05 15:23:02,048] Trial 1283 finished with value: 0.9495485083788046 and parameters: {'weight_class_0': 0.9751916342300028, 'weight_class_1': 9.960618666357819, 'weight_class_2': 8.493813109235685}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:02,058] Trial 1282 finished with value: 0.949498998664549 and parameters: {'weight_class_0': 0.9790541584264376, 'weight_class_1': 9.951723114541252, 'weight_class_2': 9.90259280935459}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:02,061] Trial 1284 finished with value: 0.9485148556949587 and parameters: {'weight_class_0': 0.9747439618730128, 'weight_class_1': 5.6668619606933035, 'weight_class_2': 9.896659444402365}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:02,080] Trial 1285 finished with value: 0.9495323827753551 and parameters: {'weight_class_0': 1.0392135446544182, 'weight_class_1': 9.922827844175877, 'weight_class_2': 9.778001199174174}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:02,126] Trial 1286 finished with value: 0.8782108624705711 and parameters: {'weight_class_0': 1.0584868560532814, 'weight_class_1': 0.11619433084207116, 'weight_class_2': 8.701838582787648}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  43%|███████████████████████████████████████████████████████▉                                                                          | 1291/3000 [00:27<00:39, 43.69it/s]

[I 2026-07-05 15:23:02,130] Trial 1287 finished with value: 0.9491479243690165 and parameters: {'weight_class_0': 1.0150696977619618, 'weight_class_1': 7.094851502204362, 'weight_class_2': 8.877803284534288}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:02,162] Trial 1288 finished with value: 0.6632799564224744 and parameters: {'weight_class_0': 0.007333243707462502, 'weight_class_1': 7.261995491919454, 'weight_class_2': 9.742757462255184}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:02,196] Trial 1289 finished with value: 0.9489530005739502 and parameters: {'weight_class_0': 1.1099780222855873, 'weight_class_1': 7.28563051332944, 'weight_class_2': 9.996438920433581}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:02,215] Trial 1290 finished with value: 0.9483838540220271 and parameters: {'weight_class_0': 1.120503794276853, 'weight_class_1': 7.124371935665083, 'weight_class_2': 7.600209720725207}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:02,253] Trial 1291 finished with value: 0.9494123506835481 and parameters: {'weight_class_0': 0.7360856857907139, 'weight_class_1': 7.448807521741744, 'weight_class_2': 9.859389576644006}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  43%|████████████████████████████████████████████████████████▏                                                                         | 1296/3000 [00:27<00:40, 41.98it/s]

[I 2026-07-05 15:23:02,279] Trial 1293 finished with value: 0.9488956470844366 and parameters: {'weight_class_0': 1.1548907482808155, 'weight_class_1': 7.299428464123627, 'weight_class_2': 9.971189033959137}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:02,285] Trial 1292 finished with value: 0.9488200148873124 and parameters: {'weight_class_0': 1.1861040260030413, 'weight_class_1': 7.300087931000116, 'weight_class_2': 9.903173236010721}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:02,320] Trial 1294 finished with value: 0.9485418414258721 and parameters: {'weight_class_0': 1.0864499769073213, 'weight_class_1': 7.199873945798047, 'weight_class_2': 7.5370499671414475}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:02,329] Trial 1295 finished with value: 0.9482299574759129 and parameters: {'weight_class_0': 1.1331825442480583, 'weight_class_1': 7.1786015740736655, 'weight_class_2': 7.302159217279833}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:02,346] Trial 1296 finished with value: 0.9494720930844717 and parameters: {'weight_class_0': 0.779204144687991, 'weight_class_1': 6.930262679126397, 'weight_class_2': 7.361284600725655}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  43%|████████████████████████████████████████████████████████▎                                                                         | 1300/3000 [00:27<00:40, 41.98it/s]

[I 2026-07-05 15:23:02,408] Trial 1298 finished with value: 0.9495308444910812 and parameters: {'weight_class_0': 0.7450666162697965, 'weight_class_1': 7.123504461466537, 'weight_class_2': 7.021353175810397}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:02,409] Trial 1297 finished with value: 0.6682979479969666 and parameters: {'weight_class_0': 0.00746117951727073, 'weight_class_1': 7.409454488773236, 'weight_class_2': 7.244764165150031}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:02,431] Trial 1299 finished with value: 0.9496212224494739 and parameters: {'weight_class_0': 0.7312654039160548, 'weight_class_1': 9.99929026815602, 'weight_class_2': 7.236036179229637}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:02,441] Trial 1300 finished with value: 0.9495028357965044 and parameters: {'weight_class_0': 0.7532818246057864, 'weight_class_1': 7.218822080062378, 'weight_class_2': 7.381540027396162}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  44%|████████████████████████████████████████████████████████▌                                                                         | 1306/3000 [00:27<00:38, 43.48it/s]

[I 2026-07-05 15:23:02,478] Trial 1301 finished with value: 0.9496341874832536 and parameters: {'weight_class_0': 0.746997432501879, 'weight_class_1': 8.3785197772424, 'weight_class_2': 7.302355715793293}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:02,496] Trial 1302 finished with value: 0.9496473733849286 and parameters: {'weight_class_0': 0.7635825205930102, 'weight_class_1': 9.94911852308137, 'weight_class_2': 7.259081127095965}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:02,514] Trial 1303 finished with value: 0.9496370246331725 and parameters: {'weight_class_0': 0.7535971430512631, 'weight_class_1': 9.954234759810848, 'weight_class_2': 7.291245162133072}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:02,538] Trial 1304 finished with value: 0.9495818497347309 and parameters: {'weight_class_0': 0.7664653827628023, 'weight_class_1': 8.414419005139285, 'weight_class_2': 7.398849580416586}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:02,563] Trial 1305 finished with value: 0.9496348146108072 and parameters: {'weight_class_0': 0.756722587883725, 'weight_class_1': 8.520949556653013, 'weight_class_2': 7.053652650096482}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:02,585] Trial 1306 finished with value: 0.9493498421650285 and parameters: {'weight_class_0': 0.4889484742087849, 'weight_class_1': 9.930609612815609, 'weight_class_2': 7.117803022983583}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  44%|████████████████████████████████████████████████████████▊                                                                         | 1310/3000 [00:27<00:38, 43.48it/s]

[I 2026-07-05 15:23:02,618] Trial 1307 finished with value: 0.7799648217052733 and parameters: {'weight_class_0': 0.7616586429605195, 'weight_class_1': 8.444056893833674, 'weight_class_2': 0.012833186037424458}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:02,642] Trial 1308 finished with value: 0.9495741127158822 and parameters: {'weight_class_0': 0.7562856557243077, 'weight_class_1': 8.4453903367381, 'weight_class_2': 6.968103365372298}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:02,677] Trial 1310 finished with value: 0.9494988654188609 and parameters: {'weight_class_0': 0.4899243734386432, 'weight_class_1': 9.851371547467561, 'weight_class_2': 6.366029897508509}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:02,681] Trial 1309 finished with value: 0.9495734778269176 and parameters: {'weight_class_0': 0.4940035818529373, 'weight_class_1': 8.513566021282418, 'weight_class_2': 6.313506740787419}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  44%|████████████████████████████████████████████████████████▉                                                                         | 1315/3000 [00:27<00:38, 44.02it/s]

[I 2026-07-05 15:23:02,732] Trial 1311 finished with value: 0.9495512042571211 and parameters: {'weight_class_0': 0.49205319234036504, 'weight_class_1': 8.504843057093288, 'weight_class_2': 6.1447971107887405}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:02,737] Trial 1313 finished with value: 0.9495624321918616 and parameters: {'weight_class_0': 0.48548160942099616, 'weight_class_1': 8.472370172565101, 'weight_class_2': 6.148421867276184}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:02,775] Trial 1312 finished with value: 0.9494974219042861 and parameters: {'weight_class_0': 0.4783146958732863, 'weight_class_1': 9.956870712806507, 'weight_class_2': 6.07659691924853}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:02,800] Trial 1314 finished with value: 0.9495984528106227 and parameters: {'weight_class_0': 0.5942721718447347, 'weight_class_1': 8.315120067886387, 'weight_class_2': 6.079382634194803}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:02,811] Trial 1315 finished with value: 0.9495963604826644 and parameters: {'weight_class_0': 0.48997408705349493, 'weight_class_1': 8.268919056159085, 'weight_class_2': 5.914485141007257}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  44%|█████████████████████████████████████████████████████████▏                                                                        | 1319/3000 [00:27<00:40, 41.78it/s]

[I 2026-07-05 15:23:02,838] Trial 1316 finished with value: 0.9495527424385987 and parameters: {'weight_class_0': 0.47706183537421354, 'weight_class_1': 8.447456752707627, 'weight_class_2': 6.055820173358518}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:02,864] Trial 1317 finished with value: 0.9496060642090858 and parameters: {'weight_class_0': 0.5836147572350736, 'weight_class_1': 8.330183764607005, 'weight_class_2': 6.0813004143025715}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:02,875] Trial 1318 finished with value: 0.9496112053030977 and parameters: {'weight_class_0': 0.5963276456685546, 'weight_class_1': 8.482310554288054, 'weight_class_2': 6.048491734788682}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:02,915] Trial 1319 finished with value: 0.9494950460562918 and parameters: {'weight_class_0': 0.5919244304161874, 'weight_class_1': 8.58336645963437, 'weight_class_2': 8.346520613940843}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:02,938] Trial 1320 finished with value: 0.949597307455227 and parameters: {'weight_class_0': 0.4821614372636338, 'weight_class_1': 8.374015074012371, 'weight_class_2': 5.95225750571894}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:02,940] Trial 1321 finished with value: 0.9495834653894787 and parameters: {'weight_class_0': 0.600609332428822, 'weight_class_1': 9.972963908786811, 'weight_class_2': 5.888755086970864}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:02,956] Trial 1322 finished with value: 0.9496518902350114 and parameters: {'weight_class_0': 0.5867936733763872, 'weight_class_1': 8.160647242022604, 'weight_class_2': 6.250899739393447}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:03,012] Trial 1323 finished with value: 0.9493708239394739 and parameters: {'weight_class_0': 0.5834876577646048, 'weight_class_1': 6.512555720804157, 'weight_class_2': 8.366124249742962}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:03,034] Trial 1324 finished with value: 0.9492928543597694 and parameters: {'weight_class_0': 0.5577711643913937, 'weight_class_1': 6.1025748585435, 'weight_class_2': 8.229297678749349}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:03,042] Trial 1325 finished with value: 0.9495628963643789 and parameters: {'weight_class_0': 0.6135470849088903, 'weight_class_1': 6.096860092974886, 'weight_class_2': 5.94918705180604}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:03,082] Trial 1326 finished with value: 0.9495330402603576 and parameters: {'weight_class_0': 0.602791416499161, 'weight_class_1': 6.841387380350244, 'weight_class_2': 8.165454983621746}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:03,090] Trial 1328 finished with value: 0.9494117229802401 and parameters: {'weight_class_0': 0.6164443725308419, 'weight_class_1': 6.602185569913493, 'weight_class_2': 8.411608340537562}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:03,108] Trial 1327 finished with value: 0.9494507202604129 and parameters: {'weight_class_0': 0.629244913275533, 'weight_class_1': 6.227424969188891, 'weight_class_2': 7.9353742874640325}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:03,129] Trial 1329 finished with value: 0.9493009241147613 and parameters: {'weight_class_0': 0.6822929824838264, 'weight_class_1': 5.911090686085715, 'weight_class_2': 8.52174173287101}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:03,143] Trial 1330 finished with value: 0.9493938445517319 and parameters: {'weight_class_0': 0.6423882310654835, 'weight_class_1': 6.42758087613511, 'weight_class_2': 8.523336159534804}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:03,187] Trial 1331 finished with value: 0.9493853448261733 and parameters: {'weight_class_0': 0.6259317241092838, 'weight_class_1': 6.301064964862721, 'weight_class_2': 8.51446457385507}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:03,214] Trial 1332 finished with value: 0.9493814343019585 and parameters: {'weight_class_0': 0.6341707451645207, 'weight_class_1': 6.233838431495409, 'weight_class_2': 8.224522200980584}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:03,216] Trial 1333 finished with value: 0.8332918765262814 and parameters: {'weight_class_0': 0.6359257655238578, 'weight_class_1': 0.01524500632209837, 'weight_class_2': 8.269835924823768}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  45%|█████████████████████████████████████████████████████████▉                                                                        | 1336/3000 [00:28<00:38, 42.75it/s]

[I 2026-07-05 15:23:03,246] Trial 1334 finished with value: 0.8252197787030485 and parameters: {'weight_class_0': 0.6399049172988274, 'weight_class_1': 0.013931263773832078, 'weight_class_2': 8.578128763866903}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:03,281] Trial 1335 finished with value: 0.92172140312001 and parameters: {'weight_class_0': 0.056637785391261186, 'weight_class_1': 5.442798911853637, 'weight_class_2': 8.42796826060533}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:03,308] Trial 1336 finished with value: 0.9493327044388399 and parameters: {'weight_class_0': 0.8671268575440465, 'weight_class_1': 6.964276006496379, 'weight_class_2': 8.308365498337645}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:03,366] Trial 1337 finished with value: 0.8189614091919272 and parameters: {'weight_class_0': 0.9025081095075298, 'weight_class_1': 0.013094016695233385, 'weight_class_2': 4.788182367528321}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:03,371] Trial 1339 finished with value: 0.9480154489137549 and parameters: {'weight_class_0': 0.8569109679528577, 'weight_class_1': 5.558637881215784, 'weight_class_2': 4.94350087130042}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:03,376] Trial 1338 finished with value: 0.9476475770064559 and parameters: {'weight_class_0': 0.889692843408825, 'weight_class_1': 5.650973426778076, 'weight_class_2': 4.7039350874551875}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:03,423] Trial 1340 finished with value: 0.9486398151010608 and parameters: {'weight_class_0': 0.9050754032640267, 'weight_class_1': 5.354044713489424, 'weight_class_2': 8.5164941677281}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:03,425] Trial 1341 finished with value: 0.9482021393868655 and parameters: {'weight_class_0': 0.8834463569212747, 'weight_class_1': 7.083396491941014, 'weight_class_2': 4.759308489256}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:03,445] Trial 1342 finished with value: 0.9483387964590193 and parameters: {'weight_class_0': 0.9059399163386943, 'weight_class_1': 9.987300787241344, 'weight_class_2': 4.709939293365842}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:03,455] Trial 1343 finished with value: 0.9476673703130309 and parameters: {'weight_class_0': 0.8884537176146301, 'weight_class_1': 5.385753509174316, 'weight_class_2': 4.802924997275371}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:03,499] Trial 1344 finished with value: 0.9472546933898675 and parameters: {'weight_class_0': 0.9377624676845064, 'weight_class_1': 5.20409601971441, 'weight_class_2': 4.884550491569845}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:03,506] Trial 1345 finished with value: 0.9484502234341403 and parameters: {'weight_class_0': 0.8573136473237852, 'weight_class_1': 7.318614133927488, 'weight_class_2': 4.762620017195527}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:03,524] Trial 1346 finished with value: 0.9476615649643989 and parameters: {'weight_class_0': 0.9583066530294093, 'weight_class_1': 7.289954705062571, 'weight_class_2': 4.665355086229324}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  45%|██████████████████████████████████████████████████████████▌                                                                       | 1351/3000 [00:28<00:38, 42.74it/s]

[I 2026-07-05 15:23:03,556] Trial 1347 finished with value: 0.9485580263012731 and parameters: {'weight_class_0': 0.8929358323682107, 'weight_class_1': 9.967824597798451, 'weight_class_2': 4.885887559288184}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:03,582] Trial 1348 finished with value: 0.9484125554716786 and parameters: {'weight_class_0': 0.8750238605397618, 'weight_class_1': 9.97679656151129, 'weight_class_2': 4.604793765326152}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:03,620] Trial 1349 finished with value: 0.9493841271475105 and parameters: {'weight_class_0': 0.9000638878022429, 'weight_class_1': 7.453412268961913, 'weight_class_2': 9.969193500628961}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:03,628] Trial 1350 finished with value: 0.9434481177477133 and parameters: {'weight_class_0': 1.5072487252178697, 'weight_class_1': 9.891954014608963, 'weight_class_2': 4.727141974906995}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:03,678] Trial 1351 finished with value: 0.9495683995414351 and parameters: {'weight_class_0': 0.49112196421578813, 'weight_class_1': 9.956688295872713, 'weight_class_2': 4.818695198686911}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  45%|██████████████████████████████████████████████████████████▋                                                                       | 1354/3000 [00:28<00:39, 42.05it/s]

[I 2026-07-05 15:23:03,708] Trial 1353 finished with value: 0.9476329427042404 and parameters: {'weight_class_0': 1.3472828665177465, 'weight_class_1': 9.906886013015072, 'weight_class_2': 6.596912093848777}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:03,715] Trial 1352 finished with value: 0.9494624252279498 and parameters: {'weight_class_0': 0.47229859529040036, 'weight_class_1': 7.173333997876141, 'weight_class_2': 6.891297121749361}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:03,746] Trial 1354 finished with value: 0.9487206588699767 and parameters: {'weight_class_0': 0.46260986794392667, 'weight_class_1': 7.3945825049267695, 'weight_class_2': 9.965711902744033}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:03,783] Trial 1355 finished with value: 0.9486787469019822 and parameters: {'weight_class_0': 0.44011672587282874, 'weight_class_1': 8.401881700856864, 'weight_class_2': 9.881849911441895}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:03,785] Trial 1356 finished with value: 0.9476362917138657 and parameters: {'weight_class_0': 1.3259291864603044, 'weight_class_1': 8.408015420997934, 'weight_class_2': 6.998417081297608}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:03,808] Trial 1357 finished with value: 0.9484638245783441 and parameters: {'weight_class_0': 1.3554808002528727, 'weight_class_1': 8.255457665020014, 'weight_class_2': 9.85015203052054}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:03,849] Trial 1358 finished with value: 0.9494685308631698 and parameters: {'weight_class_0': 0.4982123981598563, 'weight_class_1': 8.3774782609453, 'weight_class_2': 6.962227981607125}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:03,866] Trial 1359 finished with value: 0.8880395505253068 and parameters: {'weight_class_0': 1.4098759054239272, 'weight_class_1': 8.353807139131698, 'weight_class_2': 0.15912220046008255}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:03,871] Trial 1360 finished with value: 0.6619361007818562 and parameters: {'weight_class_0': 1.2817683306514471, 'weight_class_1': 8.39980993221594, 'weight_class_2': 0.001548318657335}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  45%|███████████████████████████████████████████████████████████                                                                       | 1364/3000 [00:28<00:39, 41.52it/s]

[I 2026-07-05 15:23:03,905] Trial 1362 finished with value: 0.9494069448534166 and parameters: {'weight_class_0': 0.4694203620295655, 'weight_class_1': 8.545752012945862, 'weight_class_2': 7.000168467825269}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:03,910] Trial 1361 finished with value: 0.9494288429191582 and parameters: {'weight_class_0': 0.47348665952819313, 'weight_class_1': 8.344102532493343, 'weight_class_2': 6.748093774435839}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:03,943] Trial 1363 finished with value: 0.9493340857844018 and parameters: {'weight_class_0': 0.4480148376289065, 'weight_class_1': 8.415081044233464, 'weight_class_2': 7.0065904615362165}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:03,974] Trial 1364 finished with value: 0.949475235044963 and parameters: {'weight_class_0': 0.7134700521164384, 'weight_class_1': 8.512833250097602, 'weight_class_2': 9.957376038576907}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  46%|███████████████████████████████████████████████████████████▎                                                                      | 1369/3000 [00:29<00:39, 41.08it/s]

[I 2026-07-05 15:23:03,988] Trial 1365 finished with value: 0.9495921678003683 and parameters: {'weight_class_0': 0.7035546122775621, 'weight_class_1': 8.308850344192962, 'weight_class_2': 7.069125273682533}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:04,038] Trial 1366 finished with value: 0.9495813695355181 and parameters: {'weight_class_0': 0.7069450501477823, 'weight_class_1': 8.480101122834778, 'weight_class_2': 7.063038440682826}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:04,053] Trial 1367 finished with value: 0.6578606949675144 and parameters: {'weight_class_0': 0.7156235338753644, 'weight_class_1': 0.00201077351480807, 'weight_class_2': 6.070653164344417}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:04,072] Trial 1368 finished with value: 0.9495973784855588 and parameters: {'weight_class_0': 0.7246707718964512, 'weight_class_1': 8.288815582938422, 'weight_class_2': 6.887692029434691}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:04,108] Trial 1369 finished with value: 0.7514158400563552 and parameters: {'weight_class_0': 0.7391179242614262, 'weight_class_1': 0.00690616800183342, 'weight_class_2': 7.046533639783532}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  46%|███████████████████████████████████████████████████████████▍                                                                      | 1373/3000 [00:29<00:38, 42.68it/s]

[I 2026-07-05 15:23:04,123] Trial 1370 finished with value: 0.9495683871463999 and parameters: {'weight_class_0': 0.7007352791198493, 'weight_class_1': 6.883142110995091, 'weight_class_2': 5.979078032883755}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:04,147] Trial 1371 finished with value: 0.9494589851082794 and parameters: {'weight_class_0': 0.742152277497615, 'weight_class_1': 6.914347822372881, 'weight_class_2': 5.97792759241765}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:04,149] Trial 1372 finished with value: 0.7507447938599516 and parameters: {'weight_class_0': 0.01572829438512129, 'weight_class_1': 6.825690767359951, 'weight_class_2': 5.94428127331325}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:04,204] Trial 1373 finished with value: 0.949518672138267 and parameters: {'weight_class_0': 0.7505637380905889, 'weight_class_1': 6.957499282852854, 'weight_class_2': 6.152397993068935}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:04,211] Trial 1374 finished with value: 0.9494569408705176 and parameters: {'weight_class_0': 0.6921654028618577, 'weight_class_1': 7.039446316241336, 'weight_class_2': 5.538029302448882}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:04,238] Trial 1375 finished with value: 0.9495485736549193 and parameters: {'weight_class_0': 0.7001756246085475, 'weight_class_1': 6.652730985339844, 'weight_class_2': 5.919073728601047}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:04,270] Trial 1377 finished with value: 0.9493937725465594 and parameters: {'weight_class_0': 0.7771671618053881, 'weight_class_1': 9.987857470908875, 'weight_class_2': 5.798074305136921}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:04,279] Trial 1376 finished with value: 0.9493705439782865 and parameters: {'weight_class_0': 0.7128980117418301, 'weight_class_1': 6.93934029373097, 'weight_class_2': 5.65980976807798}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  46%|███████████████████████████████████████████████████████████▉                                                                      | 1382/3000 [00:29<00:39, 40.95it/s]

[I 2026-07-05 15:23:04,340] Trial 1379 finished with value: 0.9496255260130773 and parameters: {'weight_class_0': 0.5426994030607695, 'weight_class_1': 6.512706693615163, 'weight_class_2': 5.703103269664202}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:04,363] Trial 1378 finished with value: 0.9496598489725878 and parameters: {'weight_class_0': 0.5277389661954018, 'weight_class_1': 6.792306285334355, 'weight_class_2': 5.610527636352462}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:04,383] Trial 1380 finished with value: 0.9496144486098785 and parameters: {'weight_class_0': 0.5613785636573728, 'weight_class_1': 6.783162804028499, 'weight_class_2': 5.542311222523879}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:04,385] Trial 1381 finished with value: 0.9132935199805937 and parameters: {'weight_class_0': 0.568414309108363, 'weight_class_1': 0.48534096193845844, 'weight_class_2': 5.802378088910124}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  46%|████████████████████████████████████████████████████████████                                                                      | 1386/3000 [00:29<00:39, 40.95it/s]

[I 2026-07-05 15:23:04,448] Trial 1382 finished with value: 0.9491402533796366 and parameters: {'weight_class_0': 0.5780568819638814, 'weight_class_1': 5.319583818168116, 'weight_class_2': 8.337205056261253}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:04,449] Trial 1383 finished with value: 0.94908476495073 and parameters: {'weight_class_0': 0.5513368019060277, 'weight_class_1': 5.20241332603994, 'weight_class_2': 8.440307202201135}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:04,464] Trial 1384 finished with value: 0.9494199934438196 and parameters: {'weight_class_0': 0.5802659379888497, 'weight_class_1': 9.99905122999389, 'weight_class_2': 8.336200467408489}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:04,466] Trial 1385 finished with value: 0.9491100970474712 and parameters: {'weight_class_0': 0.5614086606836294, 'weight_class_1': 5.177302218886714, 'weight_class_2': 8.466811499525791}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:04,500] Trial 1386 finished with value: 0.9491213520651294 and parameters: {'weight_class_0': 0.5565088298492731, 'weight_class_1': 5.200161890381498, 'weight_class_2': 8.259829418624822}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  46%|████████████████████████████████████████████████████████████▎                                                                     | 1392/3000 [00:29<00:39, 40.64it/s]

[I 2026-07-05 15:23:04,509] Trial 1387 finished with value: 0.9493343062772834 and parameters: {'weight_class_0': 0.5477117942421648, 'weight_class_1': 9.934467720852489, 'weight_class_2': 8.511038461978961}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:04,542] Trial 1389 finished with value: 0.9490857815144712 and parameters: {'weight_class_0': 0.5558215775965348, 'weight_class_1': 5.172177648882585, 'weight_class_2': 8.443923424012254}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:04,554] Trial 1388 finished with value: 0.9491321381994474 and parameters: {'weight_class_0': 0.5654275291227623, 'weight_class_1': 5.205206629370209, 'weight_class_2': 8.440135329429907}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:04,581] Trial 1390 finished with value: 0.9493246347712169 and parameters: {'weight_class_0': 0.5555538173390101, 'weight_class_1': 9.990703084310802, 'weight_class_2': 8.582518303753261}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:04,615] Trial 1391 finished with value: 0.9473437479936866 and parameters: {'weight_class_0': 1.1289585118254362, 'weight_class_1': 5.128569907447, 'weight_class_2': 8.492156103654862}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:04,636] Trial 1392 finished with value: 0.9481268857607429 and parameters: {'weight_class_0': 1.029434539490586, 'weight_class_1': 5.385254696081527, 'weight_class_2': 7.98155980208663}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  46%|████████████████████████████████████████████████████████████▍                                                                     | 1395/3000 [00:29<00:36, 43.97it/s]

[I 2026-07-05 15:23:04,662] Trial 1393 finished with value: 0.9492214150910945 and parameters: {'weight_class_0': 1.1237458804936293, 'weight_class_1': 9.88652665503531, 'weight_class_2': 8.39336055886761}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:04,720] Trial 1394 finished with value: 0.9488546765534127 and parameters: {'weight_class_0': 0.4323585836675461, 'weight_class_1': 5.451196224214908, 'weight_class_2': 8.403817188553477}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:04,728] Trial 1395 finished with value: 0.9480782879845556 and parameters: {'weight_class_0': 1.0802466691697832, 'weight_class_1': 5.449818983761146, 'weight_class_2': 9.878718594021144}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  47%|████████████████████████████████████████████████████████████▌                                                                     | 1399/3000 [00:29<00:40, 39.61it/s]

[I 2026-07-05 15:23:04,757] Trial 1396 finished with value: 0.9482044029770407 and parameters: {'weight_class_0': 1.0365478014082186, 'weight_class_1': 5.848790447703029, 'weight_class_2': 7.37418466978218}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:04,779] Trial 1397 finished with value: 0.9492014732196119 and parameters: {'weight_class_0': 0.4331358699077894, 'weight_class_1': 5.562293011131293, 'weight_class_2': 7.29308536198495}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:04,819] Trial 1398 finished with value: 0.6557604132979339 and parameters: {'weight_class_0': 0.4542449560421945, 'weight_class_1': 0.0012417983224153198, 'weight_class_2': 7.242894373394502}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:04,829] Trial 1400 finished with value: 0.9494807901648968 and parameters: {'weight_class_0': 1.11681132004473, 'weight_class_1': 9.968455674247904, 'weight_class_2': 9.950089998524943}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:04,831] Trial 1399 finished with value: 0.9486332332699746 and parameters: {'weight_class_0': 1.1007210376429026, 'weight_class_1': 8.196023661008189, 'weight_class_2': 7.133488930372757}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:04,867] Trial 1401 finished with value: 0.9489477246710886 and parameters: {'weight_class_0': 1.088145531249861, 'weight_class_1': 9.976184550628426, 'weight_class_2': 7.220658449916166}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:04,880] Trial 1402 finished with value: 0.9484488197656885 and parameters: {'weight_class_0': 1.1046337613594854, 'weight_class_1': 7.482381973770125, 'weight_class_2': 7.169336064336871}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:04,898] Trial 1403 finished with value: 0.9066159549453857 and parameters: {'weight_class_0': 0.42649021061558173, 'weight_class_1': 0.27774669851858325, 'weight_class_2': 7.216148184061378}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:04,928] Trial 1404 finished with value: 0.9495251615659681 and parameters: {'weight_class_0': 0.8262887625183645, 'weight_class_1': 8.003185590483632, 'weight_class_2': 7.252344817190985}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:04,940] Trial 1405 finished with value: 0.9485736075152115 and parameters: {'weight_class_0': 0.4312792498229486, 'weight_class_1': 7.49349075871068, 'weight_class_2': 9.928319529180653}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:05,016] Trial 1406 finished with value: 0.949409669606081 and parameters: {'weight_class_0': 0.8142715016051268, 'weight_class_1': 7.601736843400278, 'weight_class_2': 9.986473807571405}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:05,023] Trial 1407 finished with value: 0.9486584796431834 and parameters: {'weight_class_0': 0.8071270416857043, 'weight_class_1': 7.462733702812485, 'weight_class_2': 4.720825540654495}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:05,055] Trial 1408 finished with value: 0.9494917430707592 and parameters: {'weight_class_0': 0.7693174605806238, 'weight_class_1': 7.488274725915719, 'weight_class_2': 6.828766739470779}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  47%|█████████████████████████████████████████████████████████████▏                                                                    | 1413/3000 [00:30<00:37, 41.97it/s]

[I 2026-07-05 15:23:05,064] Trial 1409 finished with value: 0.9485639669950086 and parameters: {'weight_class_0': 0.8130748353146472, 'weight_class_1': 7.573483115713134, 'weight_class_2': 4.695015961154483}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:05,066] Trial 1410 finished with value: 0.9486095500685888 and parameters: {'weight_class_0': 0.7927032692621467, 'weight_class_1': 7.283248443203406, 'weight_class_2': 4.6070624285066835}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:05,101] Trial 1411 finished with value: 0.9484852262556003 and parameters: {'weight_class_0': 0.8108707635266235, 'weight_class_1': 7.4323556256918, 'weight_class_2': 4.490076635445327}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:05,131] Trial 1412 finished with value: 0.9486736287394604 and parameters: {'weight_class_0': 0.808782708577964, 'weight_class_1': 7.536642279737104, 'weight_class_2': 4.819004195054899}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:05,171] Trial 1413 finished with value: 0.9343603326694407 and parameters: {'weight_class_0': 2.0346302592683774, 'weight_class_1': 7.399728976012112, 'weight_class_2': 4.645897094965722}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  47%|█████████████████████████████████████████████████████████████▍                                                                    | 1418/3000 [00:30<00:37, 42.21it/s]

[I 2026-07-05 15:23:05,189] Trial 1414 finished with value: 0.9483590688417577 and parameters: {'weight_class_0': 0.8199871431758139, 'weight_class_1': 7.267780933163706, 'weight_class_2': 4.40511089793465}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:05,191] Trial 1415 finished with value: 0.9113157748775463 and parameters: {'weight_class_0': 0.7941461670772494, 'weight_class_1': 7.280587262506074, 'weight_class_2': 0.7942955935188611}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:05,247] Trial 1416 finished with value: 0.9492366123726508 and parameters: {'weight_class_0': 0.6679692327475287, 'weight_class_1': 7.205676071019837, 'weight_class_2': 4.8962914608823835}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:05,258] Trial 1417 finished with value: 0.9488439252726625 and parameters: {'weight_class_0': 0.8172879952766424, 'weight_class_1': 9.999036807626123, 'weight_class_2': 4.823472292491123}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:05,284] Trial 1418 finished with value: 0.9491299029334636 and parameters: {'weight_class_0': 0.659378961011841, 'weight_class_1': 6.291852804132743, 'weight_class_2': 4.704261407165945}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:05,333] Trial 1419 finished with value: 0.9490390445991898 and parameters: {'weight_class_0': 0.6436451895424257, 'weight_class_1': 6.2753729482063525, 'weight_class_2': 9.993174256200259}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:05,341] Trial 1420 finished with value: 0.949508600353098 and parameters: {'weight_class_0': 0.6199357987069909, 'weight_class_1': 6.23947325067317, 'weight_class_2': 5.184992397008036}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:05,352] Trial 1421 finished with value: 0.7125684233464415 and parameters: {'weight_class_0': 0.6838795087156291, 'weight_class_1': 6.161810605338105, 'weight_class_2': 0.004135527130843965}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  48%|█████████████████████████████████████████████████████████████▉                                                                    | 1428/3000 [00:30<00:37, 41.98it/s]

[I 2026-07-05 15:23:05,385] Trial 1422 finished with value: 0.9496691746120058 and parameters: {'weight_class_0': 0.6663433442145738, 'weight_class_1': 8.550213144481077, 'weight_class_2': 5.823555891207328}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:05,416] Trial 1423 finished with value: 0.9490485807316933 and parameters: {'weight_class_0': 0.6524988732241929, 'weight_class_1': 6.081078811414562, 'weight_class_2': 9.981384595339668}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:05,421] Trial 1424 finished with value: 0.9494897479719061 and parameters: {'weight_class_0': 0.7136239404659913, 'weight_class_1': 6.405869172752725, 'weight_class_2': 5.7809734649635}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:05,454] Trial 1425 finished with value: 0.949589093819621 and parameters: {'weight_class_0': 0.6410896850917402, 'weight_class_1': 9.953429192490713, 'weight_class_2': 5.823115815140804}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:05,477] Trial 1426 finished with value: 0.9495165489263105 and parameters: {'weight_class_0': 0.6407968261542218, 'weight_class_1': 6.003292757826584, 'weight_class_2': 5.777992252843975}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:05,505] Trial 1427 finished with value: 0.9496013050157238 and parameters: {'weight_class_0': 0.6233497673514835, 'weight_class_1': 9.990706459414739, 'weight_class_2': 6.007972570689764}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:05,508] Trial 1428 finished with value: 0.9497010845713234 and parameters: {'weight_class_0': 0.4801376027312215, 'weight_class_1': 6.080117024647532, 'weight_class_2': 5.879665945587699}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  48%|█████████████████████████████████████████████████████████████▉                                                                    | 1430/3000 [00:30<00:37, 41.98it/s]

[I 2026-07-05 15:23:05,557] Trial 1430 finished with value: 0.9495218666763002 and parameters: {'weight_class_0': 0.6490429462901561, 'weight_class_1': 6.1397941219912955, 'weight_class_2': 6.037907665615022}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:05,570] Trial 1429 finished with value: 0.9495221681095449 and parameters: {'weight_class_0': 0.6413552751214319, 'weight_class_1': 6.103585278498818, 'weight_class_2': 5.8277647877511605}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  48%|██████████████████████████████████████████████████████████████▏                                                                   | 1436/3000 [00:30<00:40, 38.63it/s]

[I 2026-07-05 15:23:05,613] Trial 1431 finished with value: 0.9343633878223847 and parameters: {'weight_class_0': 2.56944009670974, 'weight_class_1': 8.587934795785353, 'weight_class_2': 6.065667398608957}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:05,658] Trial 1432 finished with value: 0.9495661191339773 and parameters: {'weight_class_0': 0.4678047995377383, 'weight_class_1': 8.647109902921033, 'weight_class_2': 5.853176672971575}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:05,673] Trial 1433 finished with value: 0.9493852595394255 and parameters: {'weight_class_0': 0.4357853146547016, 'weight_class_1': 9.91280260507706, 'weight_class_2': 5.694361348308512}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:05,699] Trial 1434 finished with value: 0.9496226137976933 and parameters: {'weight_class_0': 0.5075232751087742, 'weight_class_1': 8.561818905965293, 'weight_class_2': 5.9170465012674205}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:05,723] Trial 1436 finished with value: 0.949586635933812 and parameters: {'weight_class_0': 0.4913842468675192, 'weight_class_1': 8.553957895359611, 'weight_class_2': 6.029992782411218}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:05,726] Trial 1435 finished with value: 0.6981067041069761 and parameters: {'weight_class_0': 0.44251148834751, 'weight_class_1': 8.519870558758582, 'weight_class_2': 0.003197868139002789}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  48%|██████████████████████████████████████████████████████████████▎                                                                   | 1438/3000 [00:30<00:39, 39.12it/s]

[I 2026-07-05 15:23:05,772] Trial 1437 finished with value: 0.9495549653728438 and parameters: {'weight_class_0': 0.4642941060618883, 'weight_class_1': 8.394278336564934, 'weight_class_2': 6.166541624921279}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:05,794] Trial 1438 finished with value: 0.9494715544917286 and parameters: {'weight_class_0': 0.4739294343286076, 'weight_class_1': 8.278013771801177, 'weight_class_2': 6.582244905191031}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:05,810] Trial 1440 finished with value: 0.9495418361504676 and parameters: {'weight_class_0': 0.5019004149749693, 'weight_class_1': 8.436917925733312, 'weight_class_2': 6.695289681646282}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:05,835] Trial 1439 finished with value: 0.9495504608178608 and parameters: {'weight_class_0': 0.4864422869352208, 'weight_class_1': 8.414458922922044, 'weight_class_2': 6.430147544534791}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:05,853] Trial 1441 finished with value: 0.8562189059626003 and parameters: {'weight_class_0': 0.5209255862744743, 'weight_class_1': 0.020203127114915766, 'weight_class_2': 7.12705389870448}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:05,882] Trial 1443 finished with value: 0.8969883332049822 and parameters: {'weight_class_0': 0.46579441429666396, 'weight_class_1': 8.709933657794547, 'weight_class_2': 0.21637863794252815}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:05,888] Trial 1442 finished with value: 0.6937956667691432 and parameters: {'weight_class_0': 0.49138175532007583, 'weight_class_1': 8.500521487962521, 'weight_class_2': 0.002778699705163384}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:05,948] Trial 1444 finished with value: 0.9491424103302909 and parameters: {'weight_class_0': 0.976071941133711, 'weight_class_1': 8.738325355117633, 'weight_class_2': 7.096682364541719}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:05,961] Trial 1445 finished with value: 0.949061257590197 and parameters: {'weight_class_0': 1.0084123444980662, 'weight_class_1': 8.208177705627149, 'weight_class_2': 7.270495479046662}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:05,968] Trial 1446 finished with value: 0.949384826022111 and parameters: {'weight_class_0': 0.8968759408595341, 'weight_class_1': 8.498705667908139, 'weight_class_2': 7.081785443011638}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:05,986] Trial 1447 finished with value: 0.94924255214893 and parameters: {'weight_class_0': 0.9936244241314354, 'weight_class_1': 8.248585192253403, 'weight_class_2': 7.664532581734945}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:06,006] Trial 1448 finished with value: 0.7130110331509271 and parameters: {'weight_class_0': 0.8746364597706437, 'weight_class_1': 8.392922642399254, 'weight_class_2': 0.005583455040840617}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:06,075] Trial 1449 finished with value: 0.9494504690399214 and parameters: {'weight_class_0': 0.9694224797930744, 'weight_class_1': 8.555250235801218, 'weight_class_2': 7.792912774096623}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:06,090] Trial 1450 finished with value: 0.8826236950673176 and parameters: {'weight_class_0': 0.8868012941812795, 'weight_class_1': 0.15546497208098833, 'weight_class_2': 7.927006013423712}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:06,107] Trial 1452 finished with value: 0.9483163682418329 and parameters: {'weight_class_0': 0.9164126606862469, 'weight_class_1': 4.870750773369029, 'weight_class_2': 8.507365128781824}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:06,127] Trial 1451 finished with value: 0.9496272316856759 and parameters: {'weight_class_0': 0.8640025926303685, 'weight_class_1': 9.957178101800864, 'weight_class_2': 8.12540838302499}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:06,153] Trial 1453 finished with value: 0.9492715823882967 and parameters: {'weight_class_0': 0.889256560202874, 'weight_class_1': 6.5750016369552196, 'weight_class_2': 8.296860238032284}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:06,172] Trial 1455 finished with value: 0.949061708386056 and parameters: {'weight_class_0': 0.9834139759849598, 'weight_class_1': 6.576085029145925, 'weight_class_2': 8.15243188722891}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  49%|███████████████████████████████████████████████████████████████                                                                   | 1456/3000 [00:31<00:38, 40.60it/s]

[I 2026-07-05 15:23:06,186] Trial 1454 finished with value: 0.9481408531177413 and parameters: {'weight_class_0': 0.9597361306854307, 'weight_class_1': 4.921648255100894, 'weight_class_2': 7.714305313445374}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:06,211] Trial 1456 finished with value: 0.9495470769947619 and parameters: {'weight_class_0': 0.9559160921036116, 'weight_class_1': 9.95276320646381, 'weight_class_2': 8.209277173384555}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  49%|███████████████████████████████████████████████████████████████▍                                                                  | 1463/3000 [00:31<00:37, 41.08it/s]

[I 2026-07-05 15:23:06,252] Trial 1457 finished with value: 0.9490676888202564 and parameters: {'weight_class_0': 0.6960880058287776, 'weight_class_1': 4.927234623454383, 'weight_class_2': 8.206134321329637}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:06,286] Trial 1458 finished with value: 0.949070907549869 and parameters: {'weight_class_0': 0.5727874573843027, 'weight_class_1': 4.913943280985722, 'weight_class_2': 8.389214376201965}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:06,298] Trial 1459 finished with value: 0.9057045037352095 and parameters: {'weight_class_0': 0.5708347715334755, 'weight_class_1': 0.3556358186859609, 'weight_class_2': 4.24744365292367}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:06,330] Trial 1460 finished with value: 0.9458975067613068 and parameters: {'weight_class_0': 1.6023949144341787, 'weight_class_1': 6.56801753271394, 'weight_class_2': 8.770571937471676}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:06,339] Trial 1461 finished with value: 0.915492151906287 and parameters: {'weight_class_0': 4.258742222435718, 'weight_class_1': 6.5297454392266, 'weight_class_2': 8.738250954941202}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:06,369] Trial 1462 finished with value: 0.945302260189306 and parameters: {'weight_class_0': 1.7473344220169638, 'weight_class_1': 6.507266746562176, 'weight_class_2': 9.984089353832955}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:06,396] Trial 1463 finished with value: 0.9493280978918625 and parameters: {'weight_class_0': 0.5728819836277822, 'weight_class_1': 6.413331296945602, 'weight_class_2': 4.321458415469327}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  49%|███████████████████████████████████████████████████████████████▍                                                                  | 1465/3000 [00:31<00:37, 41.08it/s]

[I 2026-07-05 15:23:06,414] Trial 1464 finished with value: 0.949074591395053 and parameters: {'weight_class_0': 0.5863640997350371, 'weight_class_1': 6.631537795305158, 'weight_class_2': 9.95215408728566}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:06,424] Trial 1465 finished with value: 0.6338472520473966 and parameters: {'weight_class_0': 1.6526221853401337, 'weight_class_1': 0.0010254964902631268, 'weight_class_2': 4.4830816344355116}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  49%|███████████████████████████████████████████████████████████████▊                                                                  | 1472/3000 [00:31<00:37, 40.70it/s]

[I 2026-07-05 15:23:06,464] Trial 1466 finished with value: 0.9405784557502782 and parameters: {'weight_class_0': 1.6593822729890952, 'weight_class_1': 6.632205078615462, 'weight_class_2': 4.9444866893919075}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:06,503] Trial 1468 finished with value: 0.9418453571183191 and parameters: {'weight_class_0': 1.610613934318471, 'weight_class_1': 9.967286456294891, 'weight_class_2': 4.573216635520702}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:06,506] Trial 1467 finished with value: 0.9492397020919837 and parameters: {'weight_class_0': 0.5934959493433508, 'weight_class_1': 6.5998973021481175, 'weight_class_2': 4.314882883950275}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:06,569] Trial 1470 finished with value: 0.865929613215648 and parameters: {'weight_class_0': 0.6979578832078183, 'weight_class_1': 6.77521168952678, 'weight_class_2': 0.03294209297727944}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:06,574] Trial 1469 finished with value: 0.9493693067904077 and parameters: {'weight_class_0': 0.6006091665180008, 'weight_class_1': 7.083036714594752, 'weight_class_2': 4.4920228255455}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:06,597] Trial 1471 finished with value: 0.9486795690963464 and parameters: {'weight_class_0': 0.7126351813249446, 'weight_class_1': 6.812580232168519, 'weight_class_2': 4.288837833954436}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:06,612] Trial 1472 finished with value: 0.9486663653919735 and parameters: {'weight_class_0': 0.7242124081229766, 'weight_class_1': 7.001912264171402, 'weight_class_2': 4.286319890672553}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  49%|███████████████████████████████████████████████████████████████▊                                                                  | 1474/3000 [00:31<00:37, 40.94it/s]

[I 2026-07-05 15:23:06,635] Trial 1473 finished with value: 0.9487763493303296 and parameters: {'weight_class_0': 0.689492459300259, 'weight_class_1': 7.041776839663872, 'weight_class_2': 4.177447863060319}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:06,690] Trial 1474 finished with value: 0.9492299981676827 and parameters: {'weight_class_0': 0.7047230686210771, 'weight_class_1': 7.266336324981983, 'weight_class_2': 5.223615223873256}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  49%|████████████████████████████████████████████████████████████████▏                                                                 | 1481/3000 [00:31<00:36, 41.47it/s]

[I 2026-07-05 15:23:06,693] Trial 1475 finished with value: 0.9493411401966464 and parameters: {'weight_class_0': 0.7243281214279179, 'weight_class_1': 7.364310164757503, 'weight_class_2': 9.993887153889872}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:06,703] Trial 1476 finished with value: 0.949320160794238 and parameters: {'weight_class_0': 1.2390255178248277, 'weight_class_1': 9.957612749621402, 'weight_class_2': 9.995407085263421}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:06,725] Trial 1477 finished with value: 0.9490791027906637 and parameters: {'weight_class_0': 0.7352121244704837, 'weight_class_1': 7.323604519056729, 'weight_class_2': 5.12818911177987}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:06,769] Trial 1478 finished with value: 0.9493513061724332 and parameters: {'weight_class_0': 0.7123293996844626, 'weight_class_1': 9.986702204372019, 'weight_class_2': 5.1857718953157415}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:06,790] Trial 1480 finished with value: 0.9494266596013702 and parameters: {'weight_class_0': 0.6921381694720412, 'weight_class_1': 9.969371797899074, 'weight_class_2': 5.264311465861298}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:06,792] Trial 1479 finished with value: 0.9495414232833026 and parameters: {'weight_class_0': 0.7112292999259701, 'weight_class_1': 7.430366203367446, 'weight_class_2': 6.658252191762435}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:06,841] Trial 1482 finished with value: 0.9490942483816838 and parameters: {'weight_class_0': 0.7165425712342001, 'weight_class_1': 5.626956643381743, 'weight_class_2': 5.472997050249478}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  49%|████████████████████████████████████████████████████████████████▎                                                                 | 1483/3000 [00:31<00:36, 41.82it/s]

[I 2026-07-05 15:23:06,850] Trial 1481 finished with value: 0.9489073528869129 and parameters: {'weight_class_0': 0.7319304991343397, 'weight_class_1': 5.521111614684275, 'weight_class_2': 5.165401071793027}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:06,856] Trial 1483 finished with value: 0.6673300845232952 and parameters: {'weight_class_0': 0.7594140806596188, 'weight_class_1': 5.36593415035108, 'weight_class_2': 0.0011896982975369487}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:06,930] Trial 1484 finished with value: 0.9455689095501184 and parameters: {'weight_class_0': 1.2127268257420687, 'weight_class_1': 5.589660348337274, 'weight_class_2': 5.3975104752052845}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:06,935] Trial 1485 finished with value: 0.900540111005628 and parameters: {'weight_class_0': 5.709795812539279, 'weight_class_1': 9.974090790915, 'weight_class_2': 6.618044706307664}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:06,974] Trial 1486 finished with value: 0.9493915279631232 and parameters: {'weight_class_0': 0.41917126380971076, 'weight_class_1': 5.409092364466213, 'weight_class_2': 6.42306866496666}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:06,982] Trial 1487 finished with value: 0.948446711654792 and parameters: {'weight_class_0': 1.2218335084615048, 'weight_class_1': 9.986059446430657, 'weight_class_2': 6.981042549194602}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:06,988] Trial 1488 finished with value: 0.9494910637025131 and parameters: {'weight_class_0': 0.5445306959894373, 'weight_class_1': 5.563734536733999, 'weight_class_2': 6.715562674359348}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:07,024] Trial 1489 finished with value: 0.9465085289070464 and parameters: {'weight_class_0': 1.2390616380147654, 'weight_class_1': 5.606788978008279, 'weight_class_2': 6.764571072862698}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:07,032] Trial 1490 finished with value: 0.9495401314725239 and parameters: {'weight_class_0': 0.5388161287384091, 'weight_class_1': 5.886916831788017, 'weight_class_2': 6.622435057510721}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  50%|████████████████████████████████████████████████████████████████▋                                                                 | 1493/3000 [00:32<00:36, 41.37it/s]

[I 2026-07-05 15:23:07,070] Trial 1491 finished with value: 0.9493046602831546 and parameters: {'weight_class_0': 0.42596938905945675, 'weight_class_1': 5.478838279058197, 'weight_class_2': 6.870458576210749}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:07,095] Trial 1492 finished with value: 0.9491938366426282 and parameters: {'weight_class_0': 0.4159747671241573, 'weight_class_1': 4.8843147222783285, 'weight_class_2': 6.735236093456705}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:07,132] Trial 1493 finished with value: 0.9495659425064588 and parameters: {'weight_class_0': 0.5260685625362727, 'weight_class_1': 8.045560590253931, 'weight_class_2': 6.917447664473496}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  50%|████████████████████████████████████████████████████████████████▉                                                                 | 1499/3000 [00:32<00:37, 40.10it/s]

[I 2026-07-05 15:23:07,169] Trial 1495 finished with value: 0.9492843626524109 and parameters: {'weight_class_0': 0.4147154267049014, 'weight_class_1': 8.394809621716155, 'weight_class_2': 6.522129508303326}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:07,171] Trial 1494 finished with value: 0.9492804838963389 and parameters: {'weight_class_0': 0.42245139073596266, 'weight_class_1': 8.301571341542681, 'weight_class_2': 6.767544076449284}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:07,195] Trial 1496 finished with value: 0.9495817639576069 and parameters: {'weight_class_0': 0.5350243905346116, 'weight_class_1': 8.3652233418849, 'weight_class_2': 6.711306581241308}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:07,237] Trial 1497 finished with value: 0.9495470455070155 and parameters: {'weight_class_0': 0.5155217171232139, 'weight_class_1': 8.294418534223105, 'weight_class_2': 7.015471420649521}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:07,264] Trial 1498 finished with value: 0.9495830369946395 and parameters: {'weight_class_0': 0.5258340757139287, 'weight_class_1': 8.242437306830903, 'weight_class_2': 7.121713732052432}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:07,286] Trial 1499 finished with value: 0.9489818867218521 and parameters: {'weight_class_0': 0.4387494985730801, 'weight_class_1': 8.324056640054353, 'weight_class_2': 8.354289102049181}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  50%|█████████████████████████████████████████████████████████████████                                                                 | 1502/3000 [00:32<00:37, 40.10it/s]

[I 2026-07-05 15:23:07,298] Trial 1500 finished with value: 0.9493051388168755 and parameters: {'weight_class_0': 0.5422217555945298, 'weight_class_1': 8.29765328030301, 'weight_class_2': 8.52322202025691}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:07,317] Trial 1501 finished with value: 0.9493206136074613 and parameters: {'weight_class_0': 0.5443632833427476, 'weight_class_1': 8.3716861359507, 'weight_class_2': 8.523731687757872}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:07,338] Trial 1502 finished with value: 0.9493046847831241 and parameters: {'weight_class_0': 0.5389944191275802, 'weight_class_1': 8.402074908704332, 'weight_class_2': 8.491714310200368}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  50%|█████████████████████████████████████████████████████████████████▎                                                                | 1508/3000 [00:32<00:36, 41.37it/s]

[I 2026-07-05 15:23:07,364] Trial 1503 finished with value: 0.949033064889884 and parameters: {'weight_class_0': 0.5545205661677077, 'weight_class_1': 8.326906514180259, 'weight_class_2': 9.9417666250943}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:07,409] Trial 1505 finished with value: 0.9494243154602131 and parameters: {'weight_class_0': 0.5768310936741133, 'weight_class_1': 8.214968619576574, 'weight_class_2': 8.58325345891049}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:07,424] Trial 1504 finished with value: 0.9494206867934034 and parameters: {'weight_class_0': 0.5774912466943192, 'weight_class_1': 8.491841033104185, 'weight_class_2': 8.591701296196574}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:07,439] Trial 1506 finished with value: 0.9493146732505752 and parameters: {'weight_class_0': 0.5585768162212846, 'weight_class_1': 8.407806575697265, 'weight_class_2': 8.614914145834849}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:07,472] Trial 1507 finished with value: 0.8874219745667392 and parameters: {'weight_class_0': 0.847075195339101, 'weight_class_1': 8.331754071707099, 'weight_class_2': 0.09402400563276421}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:07,511] Trial 1509 finished with value: 0.9494383348600244 and parameters: {'weight_class_0': 0.8651636428876628, 'weight_class_1': 8.44844078465597, 'weight_class_2': 8.69384499670798}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  50%|█████████████████████████████████████████████████████████████████▍                                                                | 1510/3000 [00:32<00:36, 41.37it/s]

[I 2026-07-05 15:23:07,516] Trial 1508 finished with value: 0.9494506564080237 and parameters: {'weight_class_0': 0.6049065884738986, 'weight_class_1': 8.381022141796347, 'weight_class_2': 8.734628794006957}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:07,554] Trial 1510 finished with value: 0.948954401559984 and parameters: {'weight_class_0': 0.6088297262036165, 'weight_class_1': 4.662774789747521, 'weight_class_2': 8.459742641227253}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:07,595] Trial 1511 finished with value: 0.949388313720856 and parameters: {'weight_class_0': 0.8644157079530983, 'weight_class_1': 7.241413612623802, 'weight_class_2': 9.970161616810595}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:07,619] Trial 1512 finished with value: 0.9493691406722821 and parameters: {'weight_class_0': 0.8248057841364739, 'weight_class_1': 7.226246842278202, 'weight_class_2': 9.892692028781328}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:07,624] Trial 1513 finished with value: 0.6579184835118098 and parameters: {'weight_class_0': 0.0017510862264628647, 'weight_class_1': 9.859113792257455, 'weight_class_2': 5.4707033762507296}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:07,649] Trial 1514 finished with value: 0.9482827974134818 and parameters: {'weight_class_0': 0.846154328709578, 'weight_class_1': 4.582123611376923, 'weight_class_2': 8.478460001314753}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:07,667] Trial 1516 finished with value: 0.9491844645052282 and parameters: {'weight_class_0': 0.8069879784352142, 'weight_class_1': 9.920419041800741, 'weight_class_2': 5.558005291784042}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:07,681] Trial 1515 finished with value: 0.947875797973991 and parameters: {'weight_class_0': 0.8374056401312199, 'weight_class_1': 4.646919566760617, 'weight_class_2': 5.3957706535684204}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  51%|█████████████████████████████████████████████████████████████████▊                                                                | 1519/3000 [00:32<00:36, 40.49it/s]

[I 2026-07-05 15:23:07,738] Trial 1517 finished with value: 0.9490093759207836 and parameters: {'weight_class_0': 0.8335042263286688, 'weight_class_1': 9.885439060579806, 'weight_class_2': 5.400434613042188}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:07,750] Trial 1518 finished with value: 0.9486814438483595 and parameters: {'weight_class_0': 0.9120355856324576, 'weight_class_1': 9.964441014360238, 'weight_class_2': 5.227457454278906}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:07,778] Trial 1519 finished with value: 0.9477595655530852 and parameters: {'weight_class_0': 0.8512559132113815, 'weight_class_1': 4.676558928727752, 'weight_class_2': 5.296819911038916}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  51%|██████████████████████████████████████████████████████████████████                                                                | 1525/3000 [00:32<00:37, 39.24it/s]

[I 2026-07-05 15:23:07,785] Trial 1520 finished with value: 0.9491686817945721 and parameters: {'weight_class_0': 0.8132966447693453, 'weight_class_1': 9.987682096060805, 'weight_class_2': 5.435973940055967}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:07,805] Trial 1521 finished with value: 0.9488527065139244 and parameters: {'weight_class_0': 0.8924759884874858, 'weight_class_1': 9.937658840643538, 'weight_class_2': 5.543973354501046}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:07,869] Trial 1523 finished with value: 0.9488133675001809 and parameters: {'weight_class_0': 0.7873480234902532, 'weight_class_1': 6.244605052656432, 'weight_class_2': 5.29352459500594}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:07,875] Trial 1522 finished with value: 0.9485659474165544 and parameters: {'weight_class_0': 0.8420733387241344, 'weight_class_1': 6.707535315321519, 'weight_class_2': 5.086852346170299}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:07,905] Trial 1524 finished with value: 0.9478139600859409 and parameters: {'weight_class_0': 0.9738599723897472, 'weight_class_1': 5.884189091351122, 'weight_class_2': 5.503397954144033}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:07,932] Trial 1526 finished with value: 0.8516869537450655 and parameters: {'weight_class_0': 1.0259259832171423, 'weight_class_1': 0.6671171779482724, 'weight_class_2': 0.2957586211928276}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:07,933] Trial 1527 finished with value: 0.9485430625605867 and parameters: {'weight_class_0': 1.0337538366285521, 'weight_class_1': 9.925858163722372, 'weight_class_2': 5.753999187359303}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:07,944] Trial 1525 finished with value: 0.9471325468108488 and parameters: {'weight_class_0': 1.110176677632982, 'weight_class_1': 6.363693700507401, 'weight_class_2': 5.541790187399617}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:07,962] Trial 1528 finished with value: 0.9476893635186326 and parameters: {'weight_class_0': 1.017143786143362, 'weight_class_1': 6.114195471977755, 'weight_class_2': 5.556425179123615}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  51%|██████████████████████████████████████████████████████████████████▍                                                               | 1533/3000 [00:33<00:36, 39.71it/s]

[I 2026-07-05 15:23:08,017] Trial 1529 finished with value: 0.9453085256634107 and parameters: {'weight_class_0': 1.0934063651179764, 'weight_class_1': 6.102422218877745, 'weight_class_2': 4.204010401545235}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:08,037] Trial 1530 finished with value: 0.8938350764240085 and parameters: {'weight_class_0': 1.0773423119617096, 'weight_class_1': 6.535651768074031, 'weight_class_2': 0.3288075442471877}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:08,053] Trial 1531 finished with value: 0.9477718089285174 and parameters: {'weight_class_0': 1.1143457618667358, 'weight_class_1': 6.022760745318413, 'weight_class_2': 7.165595860764903}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:08,104] Trial 1532 finished with value: 0.9442516853791281 and parameters: {'weight_class_0': 1.168750515586357, 'weight_class_1': 6.016064396080353, 'weight_class_2': 4.151605888414437}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:08,117] Trial 1533 finished with value: 0.9480783661899688 and parameters: {'weight_class_0': 1.0892205816337694, 'weight_class_1': 6.104196820048063, 'weight_class_2': 7.539638899499714}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:08,171] Trial 1534 finished with value: 0.9481847320703777 and parameters: {'weight_class_0': 1.151906281640716, 'weight_class_1': 7.188225299937744, 'weight_class_2': 7.341497148962396}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:08,175] Trial 1535 finished with value: 0.9488372107348143 and parameters: {'weight_class_0': 1.1431877677699749, 'weight_class_1': 7.04480878331477, 'weight_class_2': 9.972755269467354}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:08,199] Trial 1536 finished with value: 0.9495169486504041 and parameters: {'weight_class_0': 0.6719734313471187, 'weight_class_1': 6.94703085432207, 'weight_class_2': 7.368287976419426}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  51%|██████████████████████████████████████████████████████████████████▊                                                               | 1543/3000 [00:33<00:34, 41.99it/s]

[I 2026-07-05 15:23:08,219] Trial 1537 finished with value: 0.9495874922205481 and parameters: {'weight_class_0': 0.6590791694515471, 'weight_class_1': 7.232631078912005, 'weight_class_2': 7.349720411595748}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:08,233] Trial 1538 finished with value: 0.9489395684473897 and parameters: {'weight_class_0': 0.6398243350059738, 'weight_class_1': 7.181853261072001, 'weight_class_2': 4.110560978809926}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:08,276] Trial 1540 finished with value: 0.6573760850832869 and parameters: {'weight_class_0': 0.0010793697593372864, 'weight_class_1': 7.159555534067636, 'weight_class_2': 7.513378671635499}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:08,278] Trial 1539 finished with value: 0.9492433272540022 and parameters: {'weight_class_0': 0.6389861048297123, 'weight_class_1': 7.380660481218526, 'weight_class_2': 9.977173710792766}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:08,321] Trial 1541 finished with value: 0.9495248195496053 and parameters: {'weight_class_0': 0.6731360784647116, 'weight_class_1': 7.074673416089798, 'weight_class_2': 7.5740805486920255}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:08,351] Trial 1542 finished with value: 0.9495841861178042 and parameters: {'weight_class_0': 0.6262095558543292, 'weight_class_1': 7.3166165639629, 'weight_class_2': 7.485408767350327}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:08,361] Trial 1543 finished with value: 0.9496524905136999 and parameters: {'weight_class_0': 0.6556962321519804, 'weight_class_1': 7.333639626407471, 'weight_class_2': 7.26224253373992}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:08,413] Trial 1544 finished with value: 0.9496166169337901 and parameters: {'weight_class_0': 0.6544327872868818, 'weight_class_1': 7.3422087539614, 'weight_class_2': 7.420815979296832}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  52%|███████████████████████████████████████████████████████████████████▎                                                              | 1553/3000 [00:33<00:34, 41.79it/s]

[I 2026-07-05 15:23:08,421] Trial 1545 finished with value: 0.8784185355162705 and parameters: {'weight_class_0': 0.6477229147859866, 'weight_class_1': 7.236632030677077, 'weight_class_2': 0.0480868411543744}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:08,457] Trial 1546 finished with value: 0.9496186725207362 and parameters: {'weight_class_0': 0.6556068613488383, 'weight_class_1': 7.363764259936212, 'weight_class_2': 7.517556374396285}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:08,461] Trial 1547 finished with value: 0.9495532249249359 and parameters: {'weight_class_0': 0.6402486119603535, 'weight_class_1': 9.96859559928998, 'weight_class_2': 6.440986159381487}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:08,496] Trial 1548 finished with value: 0.9493214399199413 and parameters: {'weight_class_0': 0.4080970131386253, 'weight_class_1': 4.965864398182197, 'weight_class_2': 6.396731258380316}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:08,543] Trial 1550 finished with value: 0.9492639281862144 and parameters: {'weight_class_0': 0.4078865384704593, 'weight_class_1': 4.7180169158024095, 'weight_class_2': 6.334772359554582}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:08,550] Trial 1549 finished with value: 0.9491724213923596 and parameters: {'weight_class_0': 0.41355902737975536, 'weight_class_1': 4.853753284055158, 'weight_class_2': 6.756690707720928}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:08,555] Trial 1551 finished with value: 0.949382142226053 and parameters: {'weight_class_0': 0.4374330053141856, 'weight_class_1': 4.979529030004151, 'weight_class_2': 6.3296499217662605}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:08,584] Trial 1552 finished with value: 0.9492421486449669 and parameters: {'weight_class_0': 0.4474014906206982, 'weight_class_1': 4.615379069998972, 'weight_class_2': 6.4396673545541265}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:08,597] Trial 1553 finished with value: 0.9493615143137196 and parameters: {'weight_class_0': 0.45697205077736425, 'weight_class_1': 5.126543969069419, 'weight_class_2': 6.689997004484546}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  52%|███████████████████████████████████████████████████████████████████▎                                                              | 1554/3000 [00:33<00:34, 41.79it/s]

[I 2026-07-05 15:23:08,643] Trial 1555 finished with value: 0.9493703858450492 and parameters: {'weight_class_0': 0.48261213683988696, 'weight_class_1': 4.7494158893734415, 'weight_class_2': 6.396267514584579}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  52%|███████████████████████████████████████████████████████████████████▋                                                              | 1561/3000 [00:33<00:37, 38.66it/s]

[I 2026-07-05 15:23:08,653] Trial 1554 finished with value: 0.9493538003300891 and parameters: {'weight_class_0': 0.412320043309795, 'weight_class_1': 4.613743006203425, 'weight_class_2': 6.057543461646971}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:08,726] Trial 1556 finished with value: 0.9493962428514763 and parameters: {'weight_class_0': 0.4175801448995813, 'weight_class_1': 8.067577981969245, 'weight_class_2': 6.311756813097832}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:08,740] Trial 1558 finished with value: 0.9482622028421569 and parameters: {'weight_class_0': 0.46647796930007956, 'weight_class_1': 4.570054197966175, 'weight_class_2': 9.964767682059788}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:08,746] Trial 1557 finished with value: 0.9494455427748044 and parameters: {'weight_class_0': 0.49213764571817725, 'weight_class_1': 4.976197364554385, 'weight_class_2': 6.350435785466298}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:08,766] Trial 1559 finished with value: 0.949567644074439 and parameters: {'weight_class_0': 0.41891259039945256, 'weight_class_1': 8.342952170116881, 'weight_class_2': 4.272085962264609}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:08,799] Trial 1560 finished with value: 0.9486910645253586 and parameters: {'weight_class_0': 0.4575295377174301, 'weight_class_1': 9.904296059062048, 'weight_class_2': 9.922353778816975}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:08,816] Trial 1561 finished with value: 0.7982822803691225 and parameters: {'weight_class_0': 0.4574300514234936, 'weight_class_1': 0.006051750292567919, 'weight_class_2': 4.044797322858804}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  52%|███████████████████████████████████████████████████████████████████▋                                                              | 1563/3000 [00:33<00:34, 41.47it/s]

[I 2026-07-05 15:23:08,841] Trial 1562 finished with value: 0.9496486563522722 and parameters: {'weight_class_0': 0.49847823695854243, 'weight_class_1': 8.54570709291297, 'weight_class_2': 4.308205932303286}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:08,874] Trial 1563 finished with value: 0.949577521100256 and parameters: {'weight_class_0': 0.51701396479822, 'weight_class_1': 8.82471986174374, 'weight_class_2': 4.211435222233604}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:08,886] Trial 1566 finished with value: 0.9491345817265094 and parameters: {'weight_class_0': 0.49427079841661914, 'weight_class_1': 8.463216441542487, 'weight_class_2': 8.50840759905781}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:08,888] Trial 1564 finished with value: 0.948924158707511 and parameters: {'weight_class_0': 0.4995116442442319, 'weight_class_1': 9.88106982966982, 'weight_class_2': 9.871760068799453}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:08,894] Trial 1565 finished with value: 0.9496219683737381 and parameters: {'weight_class_0': 0.48636478730716287, 'weight_class_1': 8.729952378088411, 'weight_class_2': 4.173481693824882}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:08,937] Trial 1567 finished with value: 0.9494049118615768 and parameters: {'weight_class_0': 0.5261422034400574, 'weight_class_1': 8.550300259657911, 'weight_class_2': 4.0403794874092736}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:09,010] Trial 1568 finished with value: 0.94852681993842 and parameters: {'weight_class_0': 0.7428174905620162, 'weight_class_1': 8.552405198392607, 'weight_class_2': 4.010043399103263}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:09,029] Trial 1569 finished with value: 0.7250831118648678 and parameters: {'weight_class_0': 0.758400929374121, 'weight_class_1': 9.890656646377726, 'weight_class_2': 0.007565396821983085}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:09,054] Trial 1570 finished with value: 0.949514763823978 and parameters: {'weight_class_0': 0.5363441146414861, 'weight_class_1': 8.370884864680994, 'weight_class_2': 4.184482304286903}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  53%|████████████████████████████████████████████████████████████████████▍                                                             | 1578/3000 [00:34<00:35, 39.97it/s]

[I 2026-07-05 15:23:09,077] Trial 1571 finished with value: 0.9495737457265921 and parameters: {'weight_class_0': 0.7739676743712625, 'weight_class_1': 8.526834844498435, 'weight_class_2': 8.782145532265929}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:09,107] Trial 1572 finished with value: 0.9496695276440308 and parameters: {'weight_class_0': 0.7377930775331893, 'weight_class_1': 8.540272746426714, 'weight_class_2': 8.471551792624181}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:09,123] Trial 1574 finished with value: 0.9496704896717757 and parameters: {'weight_class_0': 0.7451445505594656, 'weight_class_1': 8.666519138343908, 'weight_class_2': 8.372480098684663}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:09,130] Trial 1573 finished with value: 0.9496910083065226 and parameters: {'weight_class_0': 0.7493504864205027, 'weight_class_1': 9.969791190392439, 'weight_class_2': 8.294723965425518}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:09,168] Trial 1575 finished with value: 0.9495417499775846 and parameters: {'weight_class_0': 0.7262606117999617, 'weight_class_1': 9.975454575004512, 'weight_class_2': 9.977705071688638}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:09,177] Trial 1576 finished with value: 0.9496694134756263 and parameters: {'weight_class_0': 0.7542194645232598, 'weight_class_1': 9.97472782174773, 'weight_class_2': 8.29628014041779}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:09,213] Trial 1577 finished with value: 0.9492844376922781 and parameters: {'weight_class_0': 0.7491532893230733, 'weight_class_1': 5.991128817833546, 'weight_class_2': 8.458001790033661}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:09,219] Trial 1578 finished with value: 0.9492821799624437 and parameters: {'weight_class_0': 0.7631800030277925, 'weight_class_1': 6.040149120443501, 'weight_class_2': 8.37406791180907}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  53%|████████████████████████████████████████████████████████████████████▍                                                             | 1579/3000 [00:34<00:35, 39.97it/s]

[I 2026-07-05 15:23:09,242] Trial 1579 finished with value: 0.9496321809247057 and parameters: {'weight_class_0': 0.7772429984196241, 'weight_class_1': 9.951190939951353, 'weight_class_2': 8.191402325228424}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  53%|████████████████████████████████████████████████████████████████████▋                                                             | 1586/3000 [00:34<00:35, 40.34it/s]

[I 2026-07-05 15:23:09,266] Trial 1580 finished with value: 0.9492270763872964 and parameters: {'weight_class_0': 0.7663015621153964, 'weight_class_1': 5.939856816855244, 'weight_class_2': 8.354808310969815}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:09,306] Trial 1581 finished with value: 0.9493920777612286 and parameters: {'weight_class_0': 0.7136204525554004, 'weight_class_1': 6.201979000862698, 'weight_class_2': 8.345541432519042}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:09,358] Trial 1583 finished with value: 0.9493817573800074 and parameters: {'weight_class_0': 0.6093179848145781, 'weight_class_1': 5.693580515740537, 'weight_class_2': 7.657057296199131}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:09,361] Trial 1582 finished with value: 0.9493450103225908 and parameters: {'weight_class_0': 0.6096875576181309, 'weight_class_1': 5.964456138004975, 'weight_class_2': 8.121465695266245}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:09,386] Trial 1584 finished with value: 0.9489583651472646 and parameters: {'weight_class_0': 0.9015031934299291, 'weight_class_1': 5.934842512301315, 'weight_class_2': 8.412574167134574}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:09,405] Trial 1585 finished with value: 0.9488146988978977 and parameters: {'weight_class_0': 0.9452999294602827, 'weight_class_1': 5.930297975144913, 'weight_class_2': 8.532217984774423}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:09,458] Trial 1586 finished with value: 0.9472496084389 and parameters: {'weight_class_0': 1.3272656433466519, 'weight_class_1': 5.8975691929080005, 'weight_class_2': 9.971234245717454}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  53%|████████████████████████████████████████████████████████████████████▊                                                             | 1587/3000 [00:34<00:35, 40.34it/s]

[I 2026-07-05 15:23:09,463] Trial 1587 finished with value: 0.9495289055575435 and parameters: {'weight_class_0': 0.9239780042487299, 'weight_class_1': 9.93018214433291, 'weight_class_2': 8.34585942031503}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  53%|█████████████████████████████████████████████████████████████████████                                                             | 1595/3000 [00:34<00:34, 40.71it/s]

[I 2026-07-05 15:23:09,500] Trial 1588 finished with value: 0.9492064723658663 and parameters: {'weight_class_0': 0.9645851715824838, 'weight_class_1': 7.337277474985379, 'weight_class_2': 9.98418240482935}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:09,531] Trial 1589 finished with value: 0.9475287744719071 and parameters: {'weight_class_0': 1.3427546157959183, 'weight_class_1': 7.2859957448223405, 'weight_class_2': 7.797667618870683}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:09,535] Trial 1590 finished with value: 0.948275006076796 and parameters: {'weight_class_0': 1.3366058322386545, 'weight_class_1': 7.492907155556504, 'weight_class_2': 9.946735798311387}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:09,577] Trial 1592 finished with value: 0.9135399221936416 and parameters: {'weight_class_0': 1.3756293669882094, 'weight_class_1': 1.2479145147876864, 'weight_class_2': 7.303140644283427}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:09,582] Trial 1591 finished with value: 0.912034148249805 and parameters: {'weight_class_0': 1.3333824736968578, 'weight_class_1': 1.0940568587142916, 'weight_class_2': 9.924513145924958}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:09,601] Trial 1593 finished with value: 0.9495757417762132 and parameters: {'weight_class_0': 0.6000223232327654, 'weight_class_1': 9.89435293979634, 'weight_class_2': 7.736892705671031}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:09,635] Trial 1594 finished with value: 0.9493991214507732 and parameters: {'weight_class_0': 0.9009879505836672, 'weight_class_1': 7.345590625726884, 'weight_class_2': 7.370620270398185}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:09,669] Trial 1595 finished with value: 0.8805502813976047 and parameters: {'weight_class_0': 1.3282951118652615, 'weight_class_1': 0.21083240291969846, 'weight_class_2': 7.277694124174991}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  53%|█████████████████████████████████████████████████████████████████████▏                                                            | 1596/3000 [00:34<00:34, 40.71it/s]

[I 2026-07-05 15:23:09,684] Trial 1596 finished with value: 0.9491975502101312 and parameters: {'weight_class_0': 0.9881594320749882, 'weight_class_1': 7.536239569355615, 'weight_class_2': 9.979802353163}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  53%|█████████████████████████████████████████████████████████████████████▍                                                            | 1603/3000 [00:34<00:35, 39.30it/s]

[I 2026-07-05 15:23:09,704] Trial 1597 finished with value: 0.949676253434455 and parameters: {'weight_class_0': 0.5926638230727274, 'weight_class_1': 7.374330340963101, 'weight_class_2': 7.203639194228806}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:09,748] Trial 1598 finished with value: 0.9476499507062955 and parameters: {'weight_class_0': 1.3030295767627933, 'weight_class_1': 7.596705252384526, 'weight_class_2': 7.2027717829412286}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:09,767] Trial 1599 finished with value: 0.9496387090928988 and parameters: {'weight_class_0': 0.5949352906403532, 'weight_class_1': 8.46431674252815, 'weight_class_2': 6.237878152348938}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:09,800] Trial 1600 finished with value: 0.9495929792888574 and parameters: {'weight_class_0': 0.5969339494365907, 'weight_class_1': 9.948870750735429, 'weight_class_2': 7.141332213829518}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:09,830] Trial 1602 finished with value: 0.949542230325472 and parameters: {'weight_class_0': 0.5991006771524086, 'weight_class_1': 9.986889761715561, 'weight_class_2': 6.138854502314329}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:09,848] Trial 1601 finished with value: 0.9495863843513389 and parameters: {'weight_class_0': 0.603351613369754, 'weight_class_1': 9.965089705252456, 'weight_class_2': 7.1713284135667585}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:09,856] Trial 1603 finished with value: 0.9496270472760008 and parameters: {'weight_class_0': 0.5999899485883422, 'weight_class_1': 7.473279805452183, 'weight_class_2': 6.046598425601904}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  54%|█████████████████████████████████████████████████████████████████████▌                                                            | 1605/3000 [00:34<00:35, 39.30it/s]

[I 2026-07-05 15:23:09,913] Trial 1605 finished with value: 0.949544281391761 and parameters: {'weight_class_0': 0.580571250284303, 'weight_class_1': 9.935892455979152, 'weight_class_2': 6.165989222479433}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:09,919] Trial 1604 finished with value: 0.9496688597195863 and parameters: {'weight_class_0': 0.6437747239848399, 'weight_class_1': 8.145556138650797, 'weight_class_2': 6.153455589995865}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  54%|█████████████████████████████████████████████████████████████████████▊                                                            | 1611/3000 [00:35<00:35, 38.74it/s]

[I 2026-07-05 15:23:09,948] Trial 1606 finished with value: 0.9495948512267308 and parameters: {'weight_class_0': 0.5991468157068489, 'weight_class_1': 8.4748639178439, 'weight_class_2': 5.999291258780368}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:09,970] Trial 1607 finished with value: 0.949700724019654 and parameters: {'weight_class_0': 0.5841758678568102, 'weight_class_1': 7.185358831852896, 'weight_class_2': 6.506228383758947}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:09,995] Trial 1608 finished with value: 0.9496197558253434 and parameters: {'weight_class_0': 0.5901713000639608, 'weight_class_1': 7.169344519728039, 'weight_class_2': 6.143239921252535}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:10,050] Trial 1609 finished with value: 0.9490412292061204 and parameters: {'weight_class_0': 0.3811410843295587, 'weight_class_1': 9.965792378125716, 'weight_class_2': 6.008261443046096}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:10,065] Trial 1610 finished with value: 0.9496341269951604 and parameters: {'weight_class_0': 0.5748113256402135, 'weight_class_1': 6.79278528267105, 'weight_class_2': 6.183230251565371}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:10,109] Trial 1611 finished with value: 0.9489941832477192 and parameters: {'weight_class_0': 0.3745948221575345, 'weight_class_1': 9.996585406144602, 'weight_class_2': 5.982761601882523}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  54%|█████████████████████████████████████████████████████████████████████▉                                                            | 1613/3000 [00:35<00:35, 39.22it/s]

[I 2026-07-05 15:23:10,120] Trial 1612 finished with value: 0.9481027872072492 and parameters: {'weight_class_0': 0.36623019401755125, 'weight_class_1': 9.98510083884123, 'weight_class_2': 9.973444917036035}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:10,140] Trial 1613 finished with value: 0.9495551962974536 and parameters: {'weight_class_0': 0.38264119797114343, 'weight_class_1': 6.657121581276952, 'weight_class_2': 5.0712748736423565}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  54%|██████████████████████████████████████████████████████████████████████▏                                                           | 1619/3000 [00:35<00:36, 37.67it/s]

[I 2026-07-05 15:23:10,194] Trial 1615 finished with value: 0.9486243826431272 and parameters: {'weight_class_0': 0.8366073505735783, 'weight_class_1': 6.7031235161580165, 'weight_class_2': 5.143713944947446}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:10,217] Trial 1614 finished with value: 0.9495321237321473 and parameters: {'weight_class_0': 0.3636400437637732, 'weight_class_1': 6.2796468818213, 'weight_class_2': 4.947341049587668}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:10,221] Trial 1616 finished with value: 0.9487284058475959 and parameters: {'weight_class_0': 0.394155071384909, 'weight_class_1': 6.533103002027451, 'weight_class_2': 8.41999852027299}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:10,261] Trial 1617 finished with value: 0.948411420757397 and parameters: {'weight_class_0': 0.4132265895271146, 'weight_class_1': 6.228813722234448, 'weight_class_2': 9.984107658172475}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:10,280] Trial 1618 finished with value: 0.9494352040769017 and parameters: {'weight_class_0': 0.3718442665128594, 'weight_class_1': 5.322923948530893, 'weight_class_2': 5.509294522821103}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:10,305] Trial 1619 finished with value: 0.9495269700708185 and parameters: {'weight_class_0': 0.3965007121557149, 'weight_class_1': 4.382572313381047, 'weight_class_2': 4.967981768906927}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:10,325] Trial 1620 finished with value: 0.9380599814524723 and parameters: {'weight_class_0': 0.41206408945869577, 'weight_class_1': 0.8521890890434103, 'weight_class_2': 5.003102435409567}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:10,355] Trial 1622 finished with value: 0.9494712950271637 and parameters: {'weight_class_0': 0.3732756779650041, 'weight_class_1': 4.0454986978549705, 'weight_class_2': 4.833156694110712}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:10,363] Trial 1621 finished with value: 0.949566627225915 and parameters: {'weight_class_0': 0.37565397168921716, 'weight_class_1': 4.451297832622892, 'weight_class_2': 5.010082673360278}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:10,388] Trial 1623 finished with value: 0.8340874585650665 and parameters: {'weight_class_0': 0.4072098791709225, 'weight_class_1': 0.00920180249519357, 'weight_class_2': 4.780482563209599}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:10,409] Trial 1624 finished with value: 0.9494631558943002 and parameters: {'weight_class_0': 0.3925451744348706, 'weight_class_1': 4.057263579636404, 'weight_class_2': 4.909495058976929}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:10,441] Trial 1625 finished with value: 0.9496765171474603 and parameters: {'weight_class_0': 0.3981815940853741, 'weight_class_1': 5.219496676217301, 'weight_class_2': 5.00686848474371}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:10,493] Trial 1626 finished with value: 0.9494607761883064 and parameters: {'weight_class_0': 0.4885869560802424, 'weight_class_1': 4.405613655876711, 'weight_class_2': 4.847492262351297}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:10,509] Trial 1627 finished with value: 0.9495065016695702 and parameters: {'weight_class_0': 0.4661936848318259, 'weight_class_1': 4.696123212115309, 'weight_class_2': 4.695790656107808}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  54%|██████████████████████████████████████████████████████████████████████▋                                                           | 1632/3000 [00:35<00:34, 39.62it/s]

[I 2026-07-05 15:23:10,532] Trial 1628 finished with value: 0.9494401303989376 and parameters: {'weight_class_0': 0.47438942301492654, 'weight_class_1': 4.227143232953232, 'weight_class_2': 5.122538514439649}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:10,560] Trial 1629 finished with value: 0.9494693526009353 and parameters: {'weight_class_0': 0.45420716953366586, 'weight_class_1': 4.431939412516259, 'weight_class_2': 4.818703686906774}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:10,582] Trial 1631 finished with value: 0.9488565019714988 and parameters: {'weight_class_0': 0.5092289058000691, 'weight_class_1': 3.9301678353872784, 'weight_class_2': 7.50919304882047}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:10,591] Trial 1630 finished with value: 0.9493014051078882 and parameters: {'weight_class_0': 0.5101623749175508, 'weight_class_1': 3.9647712389956844, 'weight_class_2': 4.816530443951346}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  55%|██████████████████████████████████████████████████████████████████████▊                                                           | 1635/3000 [00:35<00:34, 39.62it/s]

[I 2026-07-05 15:23:10,632] Trial 1632 finished with value: 0.9492210077450253 and parameters: {'weight_class_0': 0.500703095872602, 'weight_class_1': 5.190699940149201, 'weight_class_2': 7.268933492877777}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:10,667] Trial 1634 finished with value: 0.9492033312538118 and parameters: {'weight_class_0': 0.5019755164468366, 'weight_class_1': 5.205314459613699, 'weight_class_2': 7.5245066460883026}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:10,684] Trial 1633 finished with value: 0.94921617759853 and parameters: {'weight_class_0': 0.5011567972464743, 'weight_class_1': 4.958129394465407, 'weight_class_2': 7.254026061739706}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:10,700] Trial 1635 finished with value: 0.9492251818046458 and parameters: {'weight_class_0': 0.4878499796575847, 'weight_class_1': 3.646721884876808, 'weight_class_2': 4.383553426572343}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:10,716] Trial 1636 finished with value: 0.8805998366098694 and parameters: {'weight_class_0': 0.48085461777786337, 'weight_class_1': 0.06970727051272889, 'weight_class_2': 3.772530553661786}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:10,792] Trial 1637 finished with value: 0.949544383745737 and parameters: {'weight_class_0': 0.48760744550724816, 'weight_class_1': 4.953923594407921, 'weight_class_2': 4.422171150905899}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:10,798] Trial 1638 finished with value: 0.8827938537545189 and parameters: {'weight_class_0': 0.4842466758574452, 'weight_class_1': 0.08703624116825256, 'weight_class_2': 3.7710616410900464}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:10,826] Trial 1639 finished with value: 0.8532805427698492 and parameters: {'weight_class_0': 8.097713912628363, 'weight_class_1': 4.997479045924963, 'weight_class_2': 3.6932190011749215}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  55%|███████████████████████████████████████████████████████████████████████▏                                                          | 1644/3000 [00:35<00:34, 39.05it/s]

[I 2026-07-05 15:23:10,837] Trial 1640 finished with value: 0.9488474058088922 and parameters: {'weight_class_0': 0.50412941302442, 'weight_class_1': 3.569739655545897, 'weight_class_2': 3.664658295672409}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:10,855] Trial 1641 finished with value: 0.9494724166813562 and parameters: {'weight_class_0': 0.4925378360818835, 'weight_class_1': 5.371403654833036, 'weight_class_2': 3.8867264743076144}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:10,881] Trial 1642 finished with value: 0.9494866706220103 and parameters: {'weight_class_0': 0.5003114015727418, 'weight_class_1': 5.0638472551842195, 'weight_class_2': 4.048690690754692}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:10,888] Trial 1643 finished with value: 0.9496516066788022 and parameters: {'weight_class_0': 0.3739500296978214, 'weight_class_1': 5.09503651395195, 'weight_class_2': 3.7989401263336475}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:10,923] Trial 1644 finished with value: 0.6714050437514226 and parameters: {'weight_class_0': 0.004828678365057498, 'weight_class_1': 5.2966395647420175, 'weight_class_2': 3.6752060676090843}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  55%|███████████████████████████████████████████████████████████████████████▎                                                          | 1647/3000 [00:36<00:35, 38.40it/s]

[I 2026-07-05 15:23:10,978] Trial 1645 finished with value: 0.949594570348553 and parameters: {'weight_class_0': 0.33049461410028114, 'weight_class_1': 5.206421236019171, 'weight_class_2': 3.555830693396515}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:10,998] Trial 1646 finished with value: 0.9496113984046716 and parameters: {'weight_class_0': 0.35689907898620477, 'weight_class_1': 5.309942693438859, 'weight_class_2': 3.8679990463880176}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:11,033] Trial 1647 finished with value: 0.8105782924194491 and parameters: {'weight_class_0': 0.37200298364398826, 'weight_class_1': 0.027475604221869235, 'weight_class_2': 0.01956427900963796}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:11,055] Trial 1648 finished with value: 0.9495740844404302 and parameters: {'weight_class_0': 0.367837805891459, 'weight_class_1': 5.1941120690997025, 'weight_class_2': 3.7213027060799098}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:11,070] Trial 1649 finished with value: 0.9496356501547675 and parameters: {'weight_class_0': 0.3448509944849852, 'weight_class_1': 5.606977197545925, 'weight_class_2': 3.9668032266910576}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:11,113] Trial 1650 finished with value: 0.9491227989744506 and parameters: {'weight_class_0': 0.33470303531698264, 'weight_class_1': 5.53826907590031, 'weight_class_2': 5.7686290064565675}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:11,115] Trial 1651 finished with value: 0.9480054465484141 and parameters: {'weight_class_0': 0.33961913029068674, 'weight_class_1': 5.375034334992632, 'weight_class_2': 9.988241474939107}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:11,160] Trial 1652 finished with value: 0.9488153417022657 and parameters: {'weight_class_0': 0.8271633955404023, 'weight_class_1': 5.803049807724682, 'weight_class_2': 5.94667858966372}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  55%|███████████████████████████████████████████████████████████████████████▊                                                          | 1656/3000 [00:36<00:33, 39.77it/s]

[I 2026-07-05 15:23:11,166] Trial 1653 finished with value: 0.842173830904469 and parameters: {'weight_class_0': 0.8022353956750076, 'weight_class_1': 5.781532935880102, 'weight_class_2': 0.019356252238795876}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:11,191] Trial 1654 finished with value: 0.9492460243374193 and parameters: {'weight_class_0': 0.35276870198996235, 'weight_class_1': 6.042222310340876, 'weight_class_2': 5.89729232632268}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:11,210] Trial 1655 finished with value: 0.9490128989628785 and parameters: {'weight_class_0': 0.33535520591318735, 'weight_class_1': 5.692192152230596, 'weight_class_2': 6.011471450284502}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:11,221] Trial 1656 finished with value: 0.7912608286829422 and parameters: {'weight_class_0': 0.32281838364669535, 'weight_class_1': 5.659895805120055, 'weight_class_2': 0.009792797646727523}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  55%|███████████████████████████████████████████████████████████████████████▉                                                          | 1660/3000 [00:36<00:34, 39.04it/s]

[I 2026-07-05 15:23:11,304] Trial 1657 finished with value: 0.9491732682468745 and parameters: {'weight_class_0': 0.8144836314826281, 'weight_class_1': 6.109996509648487, 'weight_class_2': 8.538588873243402}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:11,315] Trial 1659 finished with value: 0.9490473337901717 and parameters: {'weight_class_0': 0.7937867543839681, 'weight_class_1': 6.0873251708383265, 'weight_class_2': 5.888872936098408}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:11,316] Trial 1658 finished with value: 0.9488807338494657 and parameters: {'weight_class_0': 0.8160419783737451, 'weight_class_1': 5.7656439691323635, 'weight_class_2': 5.995363830626878}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:11,361] Trial 1660 finished with value: 0.9472108649539875 and parameters: {'weight_class_0': 0.7950684438891803, 'weight_class_1': 3.5225261178792535, 'weight_class_2': 6.058253502741386}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  56%|████████████████████████████████████████████████████████████████████████▏                                                         | 1665/3000 [00:36<00:35, 37.82it/s]

[I 2026-07-05 15:23:11,410] Trial 1662 finished with value: 0.8887672996962556 and parameters: {'weight_class_0': 0.9408441508026988, 'weight_class_1': 6.242313454438898, 'weight_class_2': 0.11317272057504794}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:11,416] Trial 1661 finished with value: 0.9457339882499824 and parameters: {'weight_class_0': 0.9919775656894079, 'weight_class_1': 3.492014977497978, 'weight_class_2': 8.401119623502073}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:11,437] Trial 1663 finished with value: 0.9477310187985034 and parameters: {'weight_class_0': 0.8225145620283746, 'weight_class_1': 3.9049428360041034, 'weight_class_2': 8.33613271442158}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:11,452] Trial 1664 finished with value: 0.9490684393756884 and parameters: {'weight_class_0': 0.972311472110844, 'weight_class_1': 6.464529426500927, 'weight_class_2': 8.313323358012227}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:11,462] Trial 1665 finished with value: 0.9466098475441611 and parameters: {'weight_class_0': 1.0343133303568377, 'weight_class_1': 4.052667725896669, 'weight_class_2': 8.682539338701716}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  56%|████████████████████████████████████████████████████████████████████████▎                                                         | 1669/3000 [00:36<00:33, 39.28it/s]

[I 2026-07-05 15:23:11,517] Trial 1667 finished with value: 0.9456206124804974 and parameters: {'weight_class_0': 0.9929717680228387, 'weight_class_1': 3.4524164662657544, 'weight_class_2': 8.368133733030136}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:11,519] Trial 1666 finished with value: 0.9469917719326294 and parameters: {'weight_class_0': 0.9574732552894829, 'weight_class_1': 3.9808009879204396, 'weight_class_2': 8.558562321212573}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:11,569] Trial 1668 finished with value: 0.9468391718699528 and parameters: {'weight_class_0': 0.9691968316640753, 'weight_class_1': 3.923546802795325, 'weight_class_2': 8.532485804594408}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:11,577] Trial 1669 finished with value: 0.9441183449765562 and parameters: {'weight_class_0': 0.10496746613731668, 'weight_class_1': 2.5062705605871507, 'weight_class_2': 8.42998761212174}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:11,642] Trial 1670 finished with value: 0.9494975528628498 and parameters: {'weight_class_0': 0.6639404252224508, 'weight_class_1': 7.0667245399370415, 'weight_class_2': 8.094544617993932}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:11,653] Trial 1672 finished with value: 0.9467021849988718 and parameters: {'weight_class_0': 0.9996052075012639, 'weight_class_1': 3.95661010297508, 'weight_class_2': 8.307187235044879}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:11,657] Trial 1671 finished with value: 0.9491874189030645 and parameters: {'weight_class_0': 1.008636684521257, 'weight_class_1': 7.069775193829582, 'weight_class_2': 8.516295436993355}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:11,690] Trial 1673 finished with value: 0.9437618354523907 and parameters: {'weight_class_0': 0.09006815485582403, 'weight_class_1': 2.5495633786864214, 'weight_class_2': 7.582522059323564}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  56%|████████████████████████████████████████████████████████████████████████▋                                                         | 1678/3000 [00:36<00:34, 38.18it/s]

[I 2026-07-05 15:23:11,731] Trial 1674 finished with value: 0.9448039960800205 and parameters: {'weight_class_0': 0.6864791763797901, 'weight_class_1': 2.2798334309164012, 'weight_class_2': 9.955119433170509}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:11,741] Trial 1675 finished with value: 0.9450503744132056 and parameters: {'weight_class_0': 0.7144750311748407, 'weight_class_1': 2.357685828832202, 'weight_class_2': 6.976074733412983}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:11,754] Trial 1676 finished with value: 0.9494985026982912 and parameters: {'weight_class_0': 0.6939621935298037, 'weight_class_1': 7.052295367385972, 'weight_class_2': 7.277576715175842}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:11,812] Trial 1677 finished with value: 0.7968829799127648 and parameters: {'weight_class_0': 0.02267469131308123, 'weight_class_1': 7.013083335018765, 'weight_class_2': 7.0249627446257845}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:11,826] Trial 1679 finished with value: 0.6569657864090798 and parameters: {'weight_class_0': 0.002726714852450926, 'weight_class_1': 7.344289308614823, 'weight_class_2': 9.97372108597381}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  56%|████████████████████████████████████████████████████████████████████████▉                                                         | 1682/3000 [00:36<00:33, 39.05it/s]

[I 2026-07-05 15:23:11,828] Trial 1678 finished with value: 0.9495204969241459 and parameters: {'weight_class_0': 0.6694605470294334, 'weight_class_1': 7.0871502907380375, 'weight_class_2': 7.017787754302773}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:11,865] Trial 1680 finished with value: 0.9495629063849206 and parameters: {'weight_class_0': 0.6654940483680654, 'weight_class_1': 7.349186806377662, 'weight_class_2': 6.941371428793812}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:11,887] Trial 1681 finished with value: 0.9496251961065011 and parameters: {'weight_class_0': 0.6429179248412642, 'weight_class_1': 7.27735606774137, 'weight_class_2': 6.764251385781324}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:11,912] Trial 1682 finished with value: 0.9496261613262602 and parameters: {'weight_class_0': 0.6434659951760052, 'weight_class_1': 7.372276752946404, 'weight_class_2': 6.8692425517841595}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  56%|█████████████████████████████████████████████████████████████████████████                                                         | 1687/3000 [00:37<00:33, 38.82it/s]

[I 2026-07-05 15:23:11,971] Trial 1683 finished with value: 0.9495457182500902 and parameters: {'weight_class_0': 0.667399166675492, 'weight_class_1': 7.280157802903503, 'weight_class_2': 6.69690849899482}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:11,982] Trial 1684 finished with value: 0.9416943671893817 and parameters: {'weight_class_0': 0.6297241424180394, 'weight_class_1': 1.617106211285545, 'weight_class_2': 6.4860685154149795}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:11,999] Trial 1685 finished with value: 0.9496374327895145 and parameters: {'weight_class_0': 0.6395341797882195, 'weight_class_1': 7.571367088709193, 'weight_class_2': 6.8060385738259095}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:12,024] Trial 1686 finished with value: 0.9496538343803235 and parameters: {'weight_class_0': 0.5991466181544287, 'weight_class_1': 7.234228824866855, 'weight_class_2': 5.206413594668215}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:12,064] Trial 1687 finished with value: 0.949584020420104 and parameters: {'weight_class_0': 0.6350384613401161, 'weight_class_1': 7.341379812693193, 'weight_class_2': 5.180387516071361}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  56%|█████████████████████████████████████████████████████████████████████████▎                                                        | 1691/3000 [00:37<00:33, 38.82it/s]

[I 2026-07-05 15:23:12,090] Trial 1688 finished with value: 0.9496527311012565 and parameters: {'weight_class_0': 0.6003334434438627, 'weight_class_1': 8.25641729180668, 'weight_class_2': 5.24820511414846}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:12,100] Trial 1689 finished with value: 0.9496204019529819 and parameters: {'weight_class_0': 0.5823853570735626, 'weight_class_1': 7.499016362468464, 'weight_class_2': 5.194239010082315}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:12,144] Trial 1690 finished with value: 0.9495953056098978 and parameters: {'weight_class_0': 0.6214247058198002, 'weight_class_1': 7.298780567407229, 'weight_class_2': 5.169307929969434}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:12,151] Trial 1691 finished with value: 0.949334865432807 and parameters: {'weight_class_0': 0.5796867960714209, 'weight_class_1': 4.642106651182636, 'weight_class_2': 5.337165315538962}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  56%|█████████████████████████████████████████████████████████████████████████▍                                                        | 1695/3000 [00:37<00:32, 39.91it/s]

[I 2026-07-05 15:23:12,195] Trial 1692 finished with value: 0.9493925009235479 and parameters: {'weight_class_0': 0.5710032348318345, 'weight_class_1': 4.694346220805814, 'weight_class_2': 4.922988626819307}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:12,238] Trial 1694 finished with value: 0.9424050683996509 and parameters: {'weight_class_0': 0.563596034227366, 'weight_class_1': 1.5257638739026484, 'weight_class_2': 5.02140939062339}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:12,248] Trial 1693 finished with value: 0.9494313199724811 and parameters: {'weight_class_0': 0.5438844103966654, 'weight_class_1': 4.5999723892293884, 'weight_class_2': 5.194569453899366}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:12,267] Trial 1695 finished with value: 0.9494052144699374 and parameters: {'weight_class_0': 0.5371320458324258, 'weight_class_1': 4.498498699046246, 'weight_class_2': 5.09182834824817}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:12,297] Trial 1696 finished with value: 0.9495104048512745 and parameters: {'weight_class_0': 0.42868966229012395, 'weight_class_1': 4.539841178205028, 'weight_class_2': 4.73970931440386}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:12,303] Trial 1697 finished with value: 0.9495567372182675 and parameters: {'weight_class_0': 0.5565258180468015, 'weight_class_1': 8.356954702192093, 'weight_class_2': 4.959886382347974}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:12,352] Trial 1698 finished with value: 0.9495962507321204 and parameters: {'weight_class_0': 0.4182740123252084, 'weight_class_1': 8.084759102702021, 'weight_class_2': 4.731106154447862}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:12,368] Trial 1699 finished with value: 0.9496555984802294 and parameters: {'weight_class_0': 0.4204760923098281, 'weight_class_1': 4.779406904746828, 'weight_class_2': 4.582991603044685}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  57%|█████████████████████████████████████████████████████████████████████████▊                                                        | 1704/3000 [00:37<00:32, 39.74it/s]

[I 2026-07-05 15:23:12,392] Trial 1700 finished with value: 0.8985104085795692 and parameters: {'weight_class_0': 0.029244258155871575, 'weight_class_1': 4.473291630589748, 'weight_class_2': 4.776625204722951}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:12,435] Trial 1701 finished with value: 0.9495092419064877 and parameters: {'weight_class_0': 0.4197500151473616, 'weight_class_1': 4.444902621149039, 'weight_class_2': 4.449313332858538}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:12,440] Trial 1702 finished with value: 0.9493056643128908 and parameters: {'weight_class_0': 0.4224051033956247, 'weight_class_1': 4.53212027538313, 'weight_class_2': 5.942065770924998}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:12,457] Trial 1703 finished with value: 0.9496004207647871 and parameters: {'weight_class_0': 0.43021298077733405, 'weight_class_1': 6.1677229817161106, 'weight_class_2': 4.42521291378107}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:12,497] Trial 1704 finished with value: 0.9496404781989859 and parameters: {'weight_class_0': 0.4292735819595805, 'weight_class_1': 6.028390475988769, 'weight_class_2': 4.562200507799369}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  57%|█████████████████████████████████████████████████████████████████████████▉                                                        | 1707/3000 [00:37<00:33, 38.65it/s]

[I 2026-07-05 15:23:12,527] Trial 1705 finished with value: 0.9490986405959264 and parameters: {'weight_class_0': 0.4132212924981455, 'weight_class_1': 8.389815097436587, 'weight_class_2': 7.245872648066839}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:12,547] Trial 1706 finished with value: 0.9491232884823425 and parameters: {'weight_class_0': 0.4192393968808102, 'weight_class_1': 6.082789072496634, 'weight_class_2': 7.320596979029716}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:12,603] Trial 1707 finished with value: 0.9483984191959123 and parameters: {'weight_class_0': 0.40734953425822695, 'weight_class_1': 6.185426513751464, 'weight_class_2': 9.891513300644727}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  57%|██████████████████████████████████████████████████████████████████████████▏                                                       | 1712/3000 [00:37<00:34, 37.32it/s]

[I 2026-07-05 15:23:12,647] Trial 1709 finished with value: 0.9491396091356497 and parameters: {'weight_class_0': 0.8050785642855335, 'weight_class_1': 6.087724717099607, 'weight_class_2': 9.839085481431642}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:12,649] Trial 1708 finished with value: 0.9494397763186662 and parameters: {'weight_class_0': 0.42196101991582957, 'weight_class_1': 6.457411895239003, 'weight_class_2': 6.3255406766528095}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:12,656] Trial 1710 finished with value: 0.9493696466793614 and parameters: {'weight_class_0': 0.7325599678190958, 'weight_class_1': 6.050207971027363, 'weight_class_2': 6.114138745723412}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:12,677] Trial 1711 finished with value: 0.9493756918549477 and parameters: {'weight_class_0': 0.7465323840631435, 'weight_class_1': 6.064843400239966, 'weight_class_2': 7.264247656571276}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:12,721] Trial 1712 finished with value: 0.9493064045060794 and parameters: {'weight_class_0': 0.7841933747412383, 'weight_class_1': 6.106809987788865, 'weight_class_2': 7.400913992693288}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  57%|██████████████████████████████████████████████████████████████████████████▎                                                       | 1716/3000 [00:37<00:34, 37.29it/s]

[I 2026-07-05 15:23:12,730] Trial 1713 finished with value: 0.9491528155590795 and parameters: {'weight_class_0': 0.7992473696656784, 'weight_class_1': 6.1251271244676255, 'weight_class_2': 9.838400372039445}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:12,750] Trial 1714 finished with value: 0.9492502090705347 and parameters: {'weight_class_0': 0.8270030253628101, 'weight_class_1': 6.195255031078559, 'weight_class_2': 7.533749550494393}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:12,755] Trial 1715 finished with value: 0.9495275017293764 and parameters: {'weight_class_0': 0.8057976492134897, 'weight_class_1': 8.428076372054077, 'weight_class_2': 7.354341873456619}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:12,809] Trial 1716 finished with value: 0.6589226946388834 and parameters: {'weight_class_0': 1.211540825434781, 'weight_class_1': 0.003510431343164534, 'weight_class_2': 9.852362753939259}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  57%|██████████████████████████████████████████████████████████████████████████▌                                                       | 1720/3000 [00:37<00:33, 37.66it/s]

[I 2026-07-05 15:23:12,847] Trial 1718 finished with value: 0.9495071261398382 and parameters: {'weight_class_0': 0.796786803724187, 'weight_class_1': 8.393032536612681, 'weight_class_2': 8.678862536106434}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:12,853] Trial 1717 finished with value: 0.9494972558474656 and parameters: {'weight_class_0': 0.7937567920858536, 'weight_class_1': 8.43855632421185, 'weight_class_2': 9.84324915892421}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:12,888] Trial 1719 finished with value: 0.6587013341174649 and parameters: {'weight_class_0': 0.003728409431731122, 'weight_class_1': 8.63860689100558, 'weight_class_2': 6.194082116455396}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:12,903] Trial 1720 finished with value: 0.9495367993891662 and parameters: {'weight_class_0': 0.7923879859810554, 'weight_class_1': 8.429095006662594, 'weight_class_2': 7.894178698819446}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  57%|██████████████████████████████████████████████████████████████████████████▊                                                       | 1725/3000 [00:38<00:32, 38.74it/s]

[I 2026-07-05 15:23:12,942] Trial 1721 finished with value: 0.9488571192474652 and parameters: {'weight_class_0': 1.1708339554924532, 'weight_class_1': 8.50541420183321, 'weight_class_2': 8.309243355731935}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:12,954] Trial 1722 finished with value: 0.9486118495489436 and parameters: {'weight_class_0': 1.2180449880016255, 'weight_class_1': 8.288327417136172, 'weight_class_2': 8.380340432133659}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:12,974] Trial 1723 finished with value: 0.8811651662765133 and parameters: {'weight_class_0': 0.8005678593144882, 'weight_class_1': 0.12342341634326315, 'weight_class_2': 9.923176105003332}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:12,984] Trial 1724 finished with value: 0.9489339597194905 and parameters: {'weight_class_0': 1.158232888821138, 'weight_class_1': 8.513445848004919, 'weight_class_2': 8.562486285619709}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:13,048] Trial 1726 finished with value: 0.9489916362870531 and parameters: {'weight_class_0': 1.1387432610547397, 'weight_class_1': 8.460667855288444, 'weight_class_2': 8.49980063901959}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  58%|██████████████████████████████████████████████████████████████████████████▉                                                       | 1729/3000 [00:38<00:31, 39.98it/s]

[I 2026-07-05 15:23:13,070] Trial 1725 finished with value: 0.9489770724934722 and parameters: {'weight_class_0': 0.8918379519409638, 'weight_class_1': 8.560378898150894, 'weight_class_2': 5.978391450272737}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:13,094] Trial 1727 finished with value: 0.9481934971508267 and parameters: {'weight_class_0': 1.1118878454439838, 'weight_class_1': 8.388437130215916, 'weight_class_2': 6.108783136879609}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:13,119] Trial 1728 finished with value: 0.9480228608599269 and parameters: {'weight_class_0': 1.1452031483469756, 'weight_class_1': 8.208108089385213, 'weight_class_2': 6.0779462624013965}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:13,156] Trial 1730 finished with value: 0.9483007693255971 and parameters: {'weight_class_0': 1.0731848841994398, 'weight_class_1': 8.514179549533557, 'weight_class_2': 5.92746556696516}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:13,178] Trial 1729 finished with value: 0.9483320693351001 and parameters: {'weight_class_0': 1.0614902482620727, 'weight_class_1': 8.163586620848577, 'weight_class_2': 6.010912426668434}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:13,242] Trial 1731 finished with value: 0.9496518323631783 and parameters: {'weight_class_0': 0.515981841934501, 'weight_class_1': 8.380060955265158, 'weight_class_2': 5.985080378578856}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:13,265] Trial 1732 finished with value: 0.9483048057360368 and parameters: {'weight_class_0': 0.548143006373771, 'weight_class_1': 2.9827153822296073, 'weight_class_2': 5.998752191682661}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  58%|███████████████████████████████████████████████████████████████████████████▎                                                      | 1737/3000 [00:38<00:34, 36.73it/s]

[I 2026-07-05 15:23:13,275] Trial 1733 finished with value: 0.9496618093786481 and parameters: {'weight_class_0': 0.5080539925594537, 'weight_class_1': 7.222719398484074, 'weight_class_2': 5.9411284645302525}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:13,293] Trial 1734 finished with value: 0.9434580701630892 and parameters: {'weight_class_0': 0.9922322420204378, 'weight_class_1': 3.052592819292351, 'weight_class_2': 5.98977855054312}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:13,339] Trial 1736 finished with value: 0.9486742381530209 and parameters: {'weight_class_0': 0.5114927826715311, 'weight_class_1': 3.195499397055149, 'weight_class_2': 6.0363343203227755}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:13,349] Trial 1735 finished with value: 0.9497003149048303 and parameters: {'weight_class_0': 0.5245050191093587, 'weight_class_1': 7.252801212806398, 'weight_class_2': 6.075167752404224}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:13,364] Trial 1737 finished with value: 0.9485437197433876 and parameters: {'weight_class_0': 0.51811195010884, 'weight_class_1': 3.1507229501817955, 'weight_class_2': 6.304372430048728}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  58%|███████████████████████████████████████████████████████████████████████████▍                                                      | 1741/3000 [00:38<00:32, 39.21it/s]

[I 2026-07-05 15:23:13,391] Trial 1738 finished with value: 0.9495686204662487 and parameters: {'weight_class_0': 0.5085686421108156, 'weight_class_1': 9.980855610287199, 'weight_class_2': 6.091462609087612}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:13,432] Trial 1740 finished with value: 0.948614412619227 and parameters: {'weight_class_0': 0.5283925275600327, 'weight_class_1': 3.3219069643361503, 'weight_class_2': 6.562479040487539}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:13,433] Trial 1739 finished with value: 0.9266793416032014 and parameters: {'weight_class_0': 3.305494326117868, 'weight_class_1': 9.940814189968123, 'weight_class_2': 6.161619922587665}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:13,464] Trial 1742 finished with value: 0.9491725639723246 and parameters: {'weight_class_0': 0.660135437302218, 'weight_class_1': 7.0033144155592115, 'weight_class_2': 9.998633013501795}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  58%|███████████████████████████████████████████████████████████████████████████▌                                                      | 1744/3000 [00:38<00:32, 39.24it/s]

[I 2026-07-05 15:23:13,476] Trial 1741 finished with value: 0.9495488391130721 and parameters: {'weight_class_0': 0.5306540260719704, 'weight_class_1': 9.987840227504053, 'weight_class_2': 7.181026540052416}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:13,536] Trial 1743 finished with value: 0.9494873804379359 and parameters: {'weight_class_0': 0.689143143118869, 'weight_class_1': 6.921842681841073, 'weight_class_2': 7.384962102879324}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:13,575] Trial 1745 finished with value: 0.8714720616276018 and parameters: {'weight_class_0': 0.6960015760302811, 'weight_class_1': 0.0438754822347305, 'weight_class_2': 7.264072879222904}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  58%|███████████████████████████████████████████████████████████████████████████▊                                                      | 1749/3000 [00:38<00:34, 36.33it/s]

[I 2026-07-05 15:23:13,596] Trial 1746 finished with value: 0.9495346240185681 and parameters: {'weight_class_0': 0.678039474306899, 'weight_class_1': 6.818111143851579, 'weight_class_2': 7.468022752567298}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:13,615] Trial 1744 finished with value: 0.9496682563391139 and parameters: {'weight_class_0': 0.6973221154148164, 'weight_class_1': 9.98473574179137, 'weight_class_2': 7.645012087762666}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:13,629] Trial 1747 finished with value: 0.9495883728272579 and parameters: {'weight_class_0': 0.3203542814339059, 'weight_class_1': 4.782152224266609, 'weight_class_2': 4.0027406379102946}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:13,678] Trial 1748 finished with value: 0.9495010170298118 and parameters: {'weight_class_0': 0.2996108353909815, 'weight_class_1': 5.315146529731607, 'weight_class_2': 4.126306493989501}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:13,690] Trial 1749 finished with value: 0.9496360907293439 and parameters: {'weight_class_0': 0.3280860179931497, 'weight_class_1': 5.295259851463006, 'weight_class_2': 4.050116197887923}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  58%|███████████████████████████████████████████████████████████████████████████▉                                                      | 1753/3000 [00:38<00:31, 39.03it/s]

[I 2026-07-05 15:23:13,717] Trial 1750 finished with value: 0.949615800539055 and parameters: {'weight_class_0': 0.3399368687639102, 'weight_class_1': 5.445385750344751, 'weight_class_2': 4.236400307506685}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:13,733] Trial 1751 finished with value: 0.9496738850366203 and parameters: {'weight_class_0': 0.3841253168321003, 'weight_class_1': 5.14547501272732, 'weight_class_2': 4.2423775823074825}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:13,780] Trial 1752 finished with value: 0.9495905842810628 and parameters: {'weight_class_0': 0.31012931284971246, 'weight_class_1': 5.253724109201281, 'weight_class_2': 3.6629314315221198}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:13,786] Trial 1754 finished with value: 0.8785555354726015 and parameters: {'weight_class_0': 0.37261161989717406, 'weight_class_1': 0.04387733753876132, 'weight_class_2': 3.84168269958402}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  59%|████████████████████████████████████████████████████████████████████████████▏                                                     | 1757/3000 [00:38<00:32, 38.76it/s]

[I 2026-07-05 15:23:13,787] Trial 1753 finished with value: 0.9495560255678953 and parameters: {'weight_class_0': 0.3095515128100885, 'weight_class_1': 5.530862938206092, 'weight_class_2': 3.945568036577956}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:13,839] Trial 1755 finished with value: 0.9495495726963586 and parameters: {'weight_class_0': 0.3090893818804983, 'weight_class_1': 5.2838919543709215, 'weight_class_2': 4.106278309448262}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:13,886] Trial 1756 finished with value: 0.9495565053559215 and parameters: {'weight_class_0': 0.3118945101646864, 'weight_class_1': 5.462014738025991, 'weight_class_2': 4.158378989459521}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:13,907] Trial 1757 finished with value: 0.9495674393027246 and parameters: {'weight_class_0': 0.3071581673541066, 'weight_class_1': 5.28679925503027, 'weight_class_2': 3.9340610364970847}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  59%|████████████████████████████████████████████████████████████████████████████▎                                                     | 1761/3000 [00:38<00:33, 37.03it/s]

[I 2026-07-05 15:23:13,936] Trial 1758 finished with value: 0.9496041757228196 and parameters: {'weight_class_0': 0.32257647663704514, 'weight_class_1': 5.37013645346495, 'weight_class_2': 4.069940650389072}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:13,949] Trial 1759 finished with value: 0.9411722938692545 and parameters: {'weight_class_0': 0.06931717801415861, 'weight_class_1': 5.149010712680641, 'weight_class_2': 4.240354651293087}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:13,979] Trial 1760 finished with value: 0.9495946097342843 and parameters: {'weight_class_0': 0.4462053631340234, 'weight_class_1': 5.091001513133388, 'weight_class_2': 4.486115495601907}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:14,013] Trial 1761 finished with value: 0.9496281724387772 and parameters: {'weight_class_0': 0.44060839950026337, 'weight_class_1': 5.366715047216784, 'weight_class_2': 4.347960971814309}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  59%|████████████████████████████████████████████████████████████████████████████▌                                                     | 1766/3000 [00:39<00:33, 37.03it/s]

[I 2026-07-05 15:23:14,046] Trial 1762 finished with value: 0.9496618973815912 and parameters: {'weight_class_0': 0.4131504630383713, 'weight_class_1': 5.5055008733795985, 'weight_class_2': 5.256734893539423}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:14,052] Trial 1763 finished with value: 0.9496786167769037 and parameters: {'weight_class_0': 0.46307964712699234, 'weight_class_1': 5.49961658803464, 'weight_class_2': 5.2745152226509875}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:14,070] Trial 1764 finished with value: 0.9494048303565003 and parameters: {'weight_class_0': 0.46119800760626595, 'weight_class_1': 3.9893317432240956, 'weight_class_2': 5.250115883678706}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:14,085] Trial 1765 finished with value: 0.9494120618330477 and parameters: {'weight_class_0': 0.44850393943078226, 'weight_class_1': 3.7909326257593174, 'weight_class_2': 4.961090582721594}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:14,108] Trial 1766 finished with value: 0.9496564553398584 and parameters: {'weight_class_0': 0.4554367859972115, 'weight_class_1': 6.4941133647878555, 'weight_class_2': 5.0127232023664705}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  59%|████████████████████████████████████████████████████████████████████████████▋                                                     | 1769/3000 [00:39<00:31, 39.32it/s]

[I 2026-07-05 15:23:14,142] Trial 1767 finished with value: 0.9494162876198433 and parameters: {'weight_class_0': 0.4675194219149294, 'weight_class_1': 3.9816477665544725, 'weight_class_2': 5.264136943712602}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:14,185] Trial 1768 finished with value: 0.9494727586315612 and parameters: {'weight_class_0': 0.4427881712532886, 'weight_class_1': 4.028786871882081, 'weight_class_2': 4.922463538978905}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:14,203] Trial 1769 finished with value: 0.949675852887988 and parameters: {'weight_class_0': 0.45326243532157895, 'weight_class_1': 6.474294381539754, 'weight_class_2': 5.110405264856059}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:14,270] Trial 1770 finished with value: 0.9492922115882473 and parameters: {'weight_class_0': 0.48591707106767945, 'weight_class_1': 3.8315619772589553, 'weight_class_2': 4.832600373886342}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:14,287] Trial 1771 finished with value: 0.9493719249516963 and parameters: {'weight_class_0': 0.4536332201106834, 'weight_class_1': 3.7794650812544015, 'weight_class_2': 5.157606857314517}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:14,289] Trial 1772 finished with value: 0.9493512772989559 and parameters: {'weight_class_0': 0.4747555955348942, 'weight_class_1': 3.8999446486900196, 'weight_class_2': 5.2823686523869835}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:14,312] Trial 1773 finished with value: 0.9496210282866216 and parameters: {'weight_class_0': 0.4927553094286877, 'weight_class_1': 6.597646693904393, 'weight_class_2': 5.299057477166878}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  59%|█████████████████████████████████████████████████████████████████████████████                                                     | 1779/3000 [00:39<00:31, 39.09it/s]

[I 2026-07-05 15:23:14,361] Trial 1775 finished with value: 0.9496449277117028 and parameters: {'weight_class_0': 0.5431149990886158, 'weight_class_1': 6.599692011068905, 'weight_class_2': 5.304836881854107}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:14,373] Trial 1774 finished with value: 0.6842493583885768 and parameters: {'weight_class_0': 0.5362988411725063, 'weight_class_1': 6.729139869821771, 'weight_class_2': 0.0018861968263114523}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:14,394] Trial 1776 finished with value: 0.9496162193119729 and parameters: {'weight_class_0': 0.5345574074900289, 'weight_class_1': 6.4225508844065775, 'weight_class_2': 5.442370782835117}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:14,411] Trial 1777 finished with value: 0.9496313394619604 and parameters: {'weight_class_0': 0.5501364318421693, 'weight_class_1': 6.671077585972768, 'weight_class_2': 5.269779454141386}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:14,443] Trial 1779 finished with value: 0.949637117362366 and parameters: {'weight_class_0': 0.5596293028495657, 'weight_class_1': 6.602355496380879, 'weight_class_2': 5.479539009364389}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:14,445] Trial 1778 finished with value: 0.9495971794318884 and parameters: {'weight_class_0': 0.5711632720009828, 'weight_class_1': 6.647075189557503, 'weight_class_2': 5.644081404241943}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  59%|█████████████████████████████████████████████████████████████████████████████▏                                                    | 1782/3000 [00:39<00:29, 41.03it/s]

[I 2026-07-05 15:23:14,476] Trial 1780 finished with value: 0.9495849982023277 and parameters: {'weight_class_0': 0.5598799475276536, 'weight_class_1': 6.59526286865141, 'weight_class_2': 5.57760320305666}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:14,505] Trial 1781 finished with value: 0.9496363252981802 and parameters: {'weight_class_0': 0.5396773977257331, 'weight_class_1': 6.794187569051861, 'weight_class_2': 5.631379237648629}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:14,564] Trial 1782 finished with value: 0.9495897723070498 and parameters: {'weight_class_0': 0.5665805302263065, 'weight_class_1': 6.526823608469081, 'weight_class_2': 6.816940905310975}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  60%|█████████████████████████████████████████████████████████████████████████████▍                                                    | 1787/3000 [00:39<00:32, 36.86it/s]

[I 2026-07-05 15:23:14,586] Trial 1783 finished with value: 0.9496577082947822 and parameters: {'weight_class_0': 0.5589894533254022, 'weight_class_1': 6.675823583493826, 'weight_class_2': 6.629713924085743}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:14,607] Trial 1784 finished with value: 0.9496631087867357 and parameters: {'weight_class_0': 0.549237278524516, 'weight_class_1': 6.6410693671644205, 'weight_class_2': 6.4861392610469855}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:14,651] Trial 1785 finished with value: 0.9496502975459968 and parameters: {'weight_class_0': 0.5868251229424701, 'weight_class_1': 6.817711555567883, 'weight_class_2': 6.670439630214529}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:14,673] Trial 1786 finished with value: 0.9496988448830922 and parameters: {'weight_class_0': 0.5527771675578136, 'weight_class_1': 7.173291327971179, 'weight_class_2': 6.762623336139524}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  60%|█████████████████████████████████████████████████████████████████████████████▌                                                    | 1790/3000 [00:39<00:32, 36.86it/s]

[I 2026-07-05 15:23:14,692] Trial 1787 finished with value: 0.9497037465251633 and parameters: {'weight_class_0': 0.5895845832105788, 'weight_class_1': 7.128330698064155, 'weight_class_2': 6.758593259178969}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:14,708] Trial 1788 finished with value: 0.9496397809739842 and parameters: {'weight_class_0': 0.6237658156808146, 'weight_class_1': 7.338701529041717, 'weight_class_2': 6.6686807447441065}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:14,754] Trial 1789 finished with value: 0.9496763198336193 and parameters: {'weight_class_0': 0.6129567712468115, 'weight_class_1': 7.314316129933353, 'weight_class_2': 6.931678848052524}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:14,770] Trial 1790 finished with value: 0.9496418794393525 and parameters: {'weight_class_0': 0.6185194487388862, 'weight_class_1': 7.027918738573065, 'weight_class_2': 7.125628376963977}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:14,783] Trial 1791 finished with value: 0.9496991787012594 and parameters: {'weight_class_0': 0.6277059389718507, 'weight_class_1': 7.264742510270823, 'weight_class_2': 7.023166913152385}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:14,799] Trial 1792 finished with value: 0.949694562046837 and parameters: {'weight_class_0': 0.623766307098931, 'weight_class_1': 7.551670806155504, 'weight_class_2': 7.121420276286205}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:14,824] Trial 1793 finished with value: 0.8822025715234004 and parameters: {'weight_class_0': 0.6446176982161025, 'weight_class_1': 7.421946912583762, 'weight_class_2': 0.05696083654121358}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:14,856] Trial 1794 finished with value: 0.9496196583365876 and parameters: {'weight_class_0': 0.6638805613080256, 'weight_class_1': 7.56886347508267, 'weight_class_2': 7.137382469063609}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:14,883] Trial 1795 finished with value: 0.949630191086832 and parameters: {'weight_class_0': 0.6618393026473672, 'weight_class_1': 7.457156626197455, 'weight_class_2': 7.026719404391686}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  60%|█████████████████████████████████████████████████████████████████████████████▉                                                    | 1798/3000 [00:39<00:30, 39.71it/s]

[I 2026-07-05 15:23:14,893] Trial 1796 finished with value: 0.9496228599497668 and parameters: {'weight_class_0': 0.6558466619977739, 'weight_class_1': 7.653355233319034, 'weight_class_2': 6.990614509804265}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:14,937] Trial 1797 finished with value: 0.9496346532363504 and parameters: {'weight_class_0': 0.6462299471535875, 'weight_class_1': 7.640737420715536, 'weight_class_2': 6.7795539783178596}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:14,977] Trial 1798 finished with value: 0.9496300009716792 and parameters: {'weight_class_0': 0.6854490930194928, 'weight_class_1': 7.860372260698434, 'weight_class_2': 7.285187723606627}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  60%|██████████████████████████████████████████████████████████████████████████████                                                    | 1802/3000 [00:40<00:33, 35.63it/s]

[I 2026-07-05 15:23:15,021] Trial 1800 finished with value: 0.9496418778433453 and parameters: {'weight_class_0': 0.6667198638258917, 'weight_class_1': 7.541522389537289, 'weight_class_2': 7.554659014020574}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:15,022] Trial 1799 finished with value: 0.9496208572000132 and parameters: {'weight_class_0': 0.686555425235726, 'weight_class_1': 7.976851421447082, 'weight_class_2': 7.367166831869355}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:15,060] Trial 1801 finished with value: 0.9495422969871482 and parameters: {'weight_class_0': 0.7038148560517322, 'weight_class_1': 7.627794683913646, 'weight_class_2': 8.019538804749393}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:15,103] Trial 1803 finished with value: 0.9494116049774431 and parameters: {'weight_class_0': 0.6945219825656953, 'weight_class_1': 5.8919173999127725, 'weight_class_2': 7.938646265768145}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  60%|██████████████████████████████████████████████████████████████████████████████▎                                                   | 1807/3000 [00:40<00:32, 36.72it/s]

[I 2026-07-05 15:23:15,110] Trial 1802 finished with value: 0.9494164732143388 and parameters: {'weight_class_0': 0.6883870034333126, 'weight_class_1': 5.851235828762949, 'weight_class_2': 7.934128925491426}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:15,146] Trial 1804 finished with value: 0.949429344840374 and parameters: {'weight_class_0': 0.6936017152128149, 'weight_class_1': 5.903392447724583, 'weight_class_2': 7.701318935036598}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:15,169] Trial 1806 finished with value: 0.9493147626593595 and parameters: {'weight_class_0': 0.6893384602853672, 'weight_class_1': 5.92234553767876, 'weight_class_2': 8.402942720839556}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:15,176] Trial 1805 finished with value: 0.949294317252304 and parameters: {'weight_class_0': 0.7029818845556679, 'weight_class_1': 5.841034505074637, 'weight_class_2': 8.374267459690241}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:15,200] Trial 1807 finished with value: 0.9109403440217524 and parameters: {'weight_class_0': 0.720636302841083, 'weight_class_1': 0.5583166816542925, 'weight_class_2': 7.6159204770140025}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:15,204] Trial 1808 finished with value: 0.9493876530235593 and parameters: {'weight_class_0': 0.6853943976344024, 'weight_class_1': 5.860949653805787, 'weight_class_2': 8.05703110155425}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:15,246] Trial 1809 finished with value: 0.9490924213014326 and parameters: {'weight_class_0': 0.47914586362298256, 'weight_class_1': 5.876659681989666, 'weight_class_2': 8.334595497891254}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:15,271] Trial 1810 finished with value: 0.9493427836900618 and parameters: {'weight_class_0': 0.7324956192812856, 'weight_class_1': 5.960496497118748, 'weight_class_2': 8.259001447839834}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:15,297] Trial 1811 finished with value: 0.9490971585826259 and parameters: {'weight_class_0': 0.48700631432082053, 'weight_class_1': 5.757348955572144, 'weight_class_2': 8.278506988673307}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  61%|██████████████████████████████████████████████████████████████████████████████▋                                                   | 1816/3000 [00:40<00:30, 39.00it/s]

[I 2026-07-05 15:23:15,329] Trial 1812 finished with value: 0.9490004285695752 and parameters: {'weight_class_0': 0.504674105855933, 'weight_class_1': 5.451618786888472, 'weight_class_2': 8.45172431596321}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:15,360] Trial 1813 finished with value: 0.9490036700052705 and parameters: {'weight_class_0': 0.48503249519734043, 'weight_class_1': 5.854803531645053, 'weight_class_2': 8.585765855595378}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:15,389] Trial 1814 finished with value: 0.9488604713106009 and parameters: {'weight_class_0': 0.4687367283734328, 'weight_class_1': 5.440298118124445, 'weight_class_2': 8.53028712970726}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:15,408] Trial 1815 finished with value: 0.9489972625666447 and parameters: {'weight_class_0': 0.4883691858238282, 'weight_class_1': 5.555232244436465, 'weight_class_2': 8.436699363192622}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  61%|██████████████████████████████████████████████████████████████████████████████▊                                                   | 1819/3000 [00:40<00:30, 39.00it/s]

[I 2026-07-05 15:23:15,473] Trial 1816 finished with value: 0.8896479691749818 and parameters: {'weight_class_0': 0.0391554488680437, 'weight_class_1': 4.8259362028233115, 'weight_class_2': 8.587158914393989}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:15,483] Trial 1817 finished with value: 0.9488497572476131 and parameters: {'weight_class_0': 0.4889271554704208, 'weight_class_1': 4.890776924175742, 'weight_class_2': 8.460529674892792}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:15,519] Trial 1818 finished with value: 0.6723301851439193 and parameters: {'weight_class_0': 0.49739627835404643, 'weight_class_1': 4.870280446308778, 'weight_class_2': 0.0010013887462338724}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:15,530] Trial 1819 finished with value: 0.9488178007197691 and parameters: {'weight_class_0': 0.5026874223874153, 'weight_class_1': 4.702585150433628, 'weight_class_2': 8.470044899221575}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  61%|███████████████████████████████████████████████████████████████████████████████                                                   | 1824/3000 [00:40<00:31, 37.85it/s]

[I 2026-07-05 15:23:15,542] Trial 1820 finished with value: 0.9484588063784131 and parameters: {'weight_class_0': 0.5110565741430618, 'weight_class_1': 4.693568042506151, 'weight_class_2': 9.912939754059103}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:15,577] Trial 1821 finished with value: 0.9488624898635726 and parameters: {'weight_class_0': 0.5345393412423248, 'weight_class_1': 4.626024018432979, 'weight_class_2': 8.575971301357106}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:15,613] Trial 1822 finished with value: 0.9494502563089166 and parameters: {'weight_class_0': 0.5521075087114629, 'weight_class_1': 4.8769221815959245, 'weight_class_2': 6.347050620343727}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:15,623] Trial 1823 finished with value: 0.9495462183798761 and parameters: {'weight_class_0': 0.47673390423528883, 'weight_class_1': 8.497378552633835, 'weight_class_2': 6.3188097289080245}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:15,655] Trial 1824 finished with value: 0.6562855871980388 and parameters: {'weight_class_0': 0.5595525665082216, 'weight_class_1': 0.0015131354518327699, 'weight_class_2': 6.3328928087749965}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  61%|███████████████████████████████████████████████████████████████████████████████▏                                                  | 1827/3000 [00:40<00:31, 37.00it/s]

[I 2026-07-05 15:23:15,691] Trial 1825 finished with value: 0.9492197116361355 and parameters: {'weight_class_0': 0.8736196654622302, 'weight_class_1': 9.975641867989875, 'weight_class_2': 6.245057155525461}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:15,699] Trial 1826 finished with value: 0.948060759762892 and parameters: {'weight_class_0': 0.8691478806238551, 'weight_class_1': 4.661838035239141, 'weight_class_2': 6.256464070936839}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:15,745] Trial 1827 finished with value: 0.9496534404442242 and parameters: {'weight_class_0': 0.5708555155960503, 'weight_class_1': 8.416535693380466, 'weight_class_2': 6.264866200926343}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  61%|███████████████████████████████████████████████████████████████████████████████▍                                                  | 1832/3000 [00:40<00:29, 39.26it/s]

[I 2026-07-05 15:23:15,774] Trial 1828 finished with value: 0.9491805635237448 and parameters: {'weight_class_0': 0.8624149835582771, 'weight_class_1': 8.543686059353766, 'weight_class_2': 6.211040901606234}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:15,782] Trial 1829 finished with value: 0.9493825121935847 and parameters: {'weight_class_0': 0.8650164652154734, 'weight_class_1': 9.998956097799317, 'weight_class_2': 6.576898988898068}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:15,801] Trial 1830 finished with value: 0.949189207014089 and parameters: {'weight_class_0': 0.8571936313362026, 'weight_class_1': 8.150139488149087, 'weight_class_2': 6.2802250400166635}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:15,830] Trial 1831 finished with value: 0.9491870317178281 and parameters: {'weight_class_0': 0.8531255831752341, 'weight_class_1': 8.623774999578853, 'weight_class_2': 6.177743041200348}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:15,898] Trial 1832 finished with value: 0.9494441095809817 and parameters: {'weight_class_0': 0.8089664556172979, 'weight_class_1': 8.393920074248163, 'weight_class_2': 6.390816374359076}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  61%|███████████████████████████████████████████████████████████████████████████████▌                                                  | 1835/3000 [00:40<00:32, 35.97it/s]

[I 2026-07-05 15:23:15,900] Trial 1833 finished with value: 0.9492389932094075 and parameters: {'weight_class_0': 0.879779743508597, 'weight_class_1': 8.565275434379588, 'weight_class_2': 6.649841939312616}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:15,940] Trial 1835 finished with value: 0.949459264793923 and parameters: {'weight_class_0': 0.8041012679013102, 'weight_class_1': 8.325841279418444, 'weight_class_2': 6.418907761060184}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:15,941] Trial 1834 finished with value: 0.9492238693944478 and parameters: {'weight_class_0': 0.8696361886279538, 'weight_class_1': 8.580757583924582, 'weight_class_2': 6.421640667515559}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  61%|███████████████████████████████████████████████████████████████████████████████▊                                                  | 1841/3000 [00:41<00:32, 35.24it/s]

[I 2026-07-05 15:23:16,028] Trial 1836 finished with value: 0.9494554131207685 and parameters: {'weight_class_0': 0.8481166582344701, 'weight_class_1': 8.578652545341763, 'weight_class_2': 6.698624382238805}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:16,034] Trial 1837 finished with value: 0.9495819416208056 and parameters: {'weight_class_0': 0.7932900780388061, 'weight_class_1': 8.46633018533256, 'weight_class_2': 6.881409959595993}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:16,041] Trial 1839 finished with value: 0.9495521939797111 and parameters: {'weight_class_0': 0.853392642375714, 'weight_class_1': 8.41551553979524, 'weight_class_2': 9.935389253078375}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:16,049] Trial 1838 finished with value: 0.9482805363551196 and parameters: {'weight_class_0': 0.3952548472599789, 'weight_class_1': 9.994677195040175, 'weight_class_2': 9.97293386422065}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:16,067] Trial 1840 finished with value: 0.9482868472586189 and parameters: {'weight_class_0': 0.38375266509875944, 'weight_class_1': 6.894908359408641, 'weight_class_2': 9.989040344760129}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:16,112] Trial 1842 finished with value: 0.9489312823663711 and parameters: {'weight_class_0': 0.38699880479280785, 'weight_class_1': 6.812451446794747, 'weight_class_2': 7.49766881643357}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  62%|███████████████████████████████████████████████████████████████████████████████▉                                                  | 1846/3000 [00:41<00:28, 40.25it/s]

[I 2026-07-05 15:23:16,116] Trial 1841 finished with value: 0.9489258558117527 and parameters: {'weight_class_0': 0.3845816826126699, 'weight_class_1': 7.104395060059788, 'weight_class_2': 7.628812226383501}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:16,128] Trial 1843 finished with value: 0.9489999876504358 and parameters: {'weight_class_0': 0.400141639988872, 'weight_class_1': 7.171257559882244, 'weight_class_2': 7.255569718626265}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:16,167] Trial 1844 finished with value: 0.9483692839814571 and parameters: {'weight_class_0': 0.38985381613807213, 'weight_class_1': 7.1128355245393085, 'weight_class_2': 9.942944698664016}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:16,222] Trial 1846 finished with value: 0.9484672085095577 and parameters: {'weight_class_0': 0.41313341417817834, 'weight_class_1': 6.849238131881675, 'weight_class_2': 9.87894119360894}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:16,223] Trial 1845 finished with value: 0.9489436850062695 and parameters: {'weight_class_0': 0.3900823972086226, 'weight_class_1': 6.918355401944163, 'weight_class_2': 7.452252964793063}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  62%|████████████████████████████████████████████████████████████████████████████████                                                  | 1849/3000 [00:41<00:29, 39.68it/s]

[I 2026-07-05 15:23:16,225] Trial 1847 finished with value: 0.9489443594301057 and parameters: {'weight_class_0': 0.39354209157231596, 'weight_class_1': 6.765563614286505, 'weight_class_2': 7.626904273065106}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:16,296] Trial 1848 finished with value: 0.9495558083032014 and parameters: {'weight_class_0': 0.5923443256891918, 'weight_class_1': 6.656364596969793, 'weight_class_2': 7.540495791547103}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:16,366] Trial 1849 finished with value: 0.9495894482087479 and parameters: {'weight_class_0': 0.5954329423147601, 'weight_class_1': 6.86621110308999, 'weight_class_2': 7.4893271514135895}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:16,372] Trial 1850 finished with value: 0.948948939590135 and parameters: {'weight_class_0': 0.4005831589360895, 'weight_class_1': 6.809251291308992, 'weight_class_2': 7.650458567045676}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:16,400] Trial 1851 finished with value: 0.9494538465769358 and parameters: {'weight_class_0': 0.6300275868699535, 'weight_class_1': 6.147452725289194, 'weight_class_2': 7.5775377882863735}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:16,425] Trial 1852 finished with value: 0.7756976894806454 and parameters: {'weight_class_0': 0.6125256291359336, 'weight_class_1': 0.01109083592279908, 'weight_class_2': 0.013744790797158145}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:16,438] Trial 1853 finished with value: 0.9493682282820016 and parameters: {'weight_class_0': 0.5736883383531131, 'weight_class_1': 6.553843339073114, 'weight_class_2': 8.332932168064252}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  62%|████████████████████████████████████████████████████████████████████████████████▌                                                 | 1858/3000 [00:41<00:30, 36.96it/s]

[I 2026-07-05 15:23:16,449] Trial 1854 finished with value: 0.9495512078728884 and parameters: {'weight_class_0': 0.5869502229328575, 'weight_class_1': 9.965265100070939, 'weight_class_2': 5.567220341918538}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:16,479] Trial 1855 finished with value: 0.9492876529214863 and parameters: {'weight_class_0': 0.5966990923344598, 'weight_class_1': 6.3490056821555, 'weight_class_2': 8.397729293139138}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:16,485] Trial 1856 finished with value: 0.9495415182585951 and parameters: {'weight_class_0': 0.6172888088648162, 'weight_class_1': 6.27962155538029, 'weight_class_2': 5.518256238084644}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:16,509] Trial 1857 finished with value: 0.9495658637581372 and parameters: {'weight_class_0': 0.5850996299914826, 'weight_class_1': 6.242329475380014, 'weight_class_2': 5.54761359353993}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:16,551] Trial 1858 finished with value: 0.949553562271967 and parameters: {'weight_class_0': 0.5761890618098211, 'weight_class_1': 6.133701606890526, 'weight_class_2': 5.861042704479327}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  62%|████████████████████████████████████████████████████████████████████████████████▌                                                 | 1860/3000 [00:41<00:29, 38.23it/s]

[I 2026-07-05 15:23:16,558] Trial 1859 finished with value: 0.9495587033042078 and parameters: {'weight_class_0': 0.6227582943652861, 'weight_class_1': 6.354632998413738, 'weight_class_2': 5.460027496188242}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:16,580] Trial 1860 finished with value: 0.9495314127675744 and parameters: {'weight_class_0': 0.6178576330490891, 'weight_class_1': 5.933441002031961, 'weight_class_2': 5.420807392250382}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:16,689] Trial 1861 finished with value: 0.949572093895546 and parameters: {'weight_class_0': 0.6134992513542005, 'weight_class_1': 9.983462586919513, 'weight_class_2': 5.522453446989474}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:16,691] Trial 1862 finished with value: 0.9495740074782816 and parameters: {'weight_class_0': 0.5606075584349811, 'weight_class_1': 9.96630140914269, 'weight_class_2': 5.491966131804991}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:16,701] Trial 1863 finished with value: 0.9495794401495643 and parameters: {'weight_class_0': 0.597598089439829, 'weight_class_1': 9.878308598915327, 'weight_class_2': 5.745910773566739}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:16,730] Trial 1864 finished with value: 0.949579878313474 and parameters: {'weight_class_0': 0.5759172620797522, 'weight_class_1': 8.528620315009606, 'weight_class_2': 5.68777509329818}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:16,776] Trial 1865 finished with value: 0.9496103024270898 and parameters: {'weight_class_0': 0.4646867842649113, 'weight_class_1': 8.429385789221984, 'weight_class_2': 5.454547903102867}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  62%|█████████████████████████████████████████████████████████████████████████████████                                                 | 1870/3000 [00:41<00:29, 38.15it/s]

[I 2026-07-05 15:23:16,786] Trial 1866 finished with value: 0.949362060567068 and parameters: {'weight_class_0': 0.7339456583729655, 'weight_class_1': 8.499100850986142, 'weight_class_2': 5.609076454141583}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:16,791] Trial 1867 finished with value: 0.8862132633823449 and parameters: {'weight_class_0': 0.7208093111619244, 'weight_class_1': 8.61772241402635, 'weight_class_2': 0.08123027549484564}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:16,809] Trial 1868 finished with value: 0.9493733277152582 and parameters: {'weight_class_0': 0.7353305464161857, 'weight_class_1': 8.502654403255342, 'weight_class_2': 5.568899067253967}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:16,826] Trial 1869 finished with value: 0.9495365481358288 and parameters: {'weight_class_0': 0.7494081437459512, 'weight_class_1': 8.123772945012677, 'weight_class_2': 8.935470259581663}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:16,876] Trial 1871 finished with value: 0.9495905188355279 and parameters: {'weight_class_0': 0.7177174281232684, 'weight_class_1': 8.320903916546417, 'weight_class_2': 8.682599682995448}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  62%|█████████████████████████████████████████████████████████████████████████████████▏                                                | 1873/3000 [00:41<00:29, 38.34it/s]

[I 2026-07-05 15:23:16,884] Trial 1870 finished with value: 0.9495015020865312 and parameters: {'weight_class_0': 0.7173204812248394, 'weight_class_1': 8.464146481191044, 'weight_class_2': 9.927237511980673}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:16,888] Trial 1872 finished with value: 0.9496539216921492 and parameters: {'weight_class_0': 0.7371625896704398, 'weight_class_1': 8.555218566556976, 'weight_class_2': 8.566109426112735}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:16,988] Trial 1873 finished with value: 0.9493522169879176 and parameters: {'weight_class_0': 0.4590292030279448, 'weight_class_1': 7.933473347430758, 'weight_class_2': 7.041205323537772}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  63%|█████████████████████████████████████████████████████████████████████████████████▍                                                | 1878/3000 [00:42<00:30, 37.39it/s]

[I 2026-07-05 15:23:17,001] Trial 1875 finished with value: 0.9495147952663122 and parameters: {'weight_class_0': 0.746860088630704, 'weight_class_1': 7.787269759567868, 'weight_class_2': 8.81490822875006}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:17,036] Trial 1874 finished with value: 0.9495492859843081 and parameters: {'weight_class_0': 0.7606993218702096, 'weight_class_1': 7.816223009487901, 'weight_class_2': 8.701955047164322}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:17,056] Trial 1876 finished with value: 0.9495392553169862 and parameters: {'weight_class_0': 0.7486697705216224, 'weight_class_1': 7.730623314167702, 'weight_class_2': 8.278851039707721}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:17,078] Trial 1877 finished with value: 0.949565956919263 and parameters: {'weight_class_0': 0.7557078954828021, 'weight_class_1': 7.6239987461545065, 'weight_class_2': 8.718266944683954}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:17,085] Trial 1878 finished with value: 0.9495359587285144 and parameters: {'weight_class_0': 0.726748222547063, 'weight_class_1': 7.549692644171759, 'weight_class_2': 8.538804063357873}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  63%|█████████████████████████████████████████████████████████████████████████████████▌                                                | 1882/3000 [00:42<00:30, 36.99it/s]

[I 2026-07-05 15:23:17,104] Trial 1880 finished with value: 0.9485553132823222 and parameters: {'weight_class_0': 0.4457655472548287, 'weight_class_1': 4.491431998330469, 'weight_class_2': 8.714822203332696}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:17,133] Trial 1879 finished with value: 0.9484053337472486 and parameters: {'weight_class_0': 0.4740079738074119, 'weight_class_1': 4.811599645665546, 'weight_class_2': 9.937178267929285}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:17,170] Trial 1881 finished with value: 0.9491240656636276 and parameters: {'weight_class_0': 0.44932156729310047, 'weight_class_1': 4.841464835015011, 'weight_class_2': 7.000941906537704}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:17,192] Trial 1882 finished with value: 0.9491233207311566 and parameters: {'weight_class_0': 0.4557658634296417, 'weight_class_1': 4.890398759893523, 'weight_class_2': 7.230414553525829}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:17,236] Trial 1884 finished with value: 0.9477320180860959 and parameters: {'weight_class_0': 0.9590424899130078, 'weight_class_1': 4.690351772704594, 'weight_class_2': 7.03407062911666}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:17,242] Trial 1883 finished with value: 0.9490131194919332 and parameters: {'weight_class_0': 0.4528203921966476, 'weight_class_1': 4.810092881802247, 'weight_class_2': 7.318142543856866}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:17,305] Trial 1885 finished with value: 0.7776642843223461 and parameters: {'weight_class_0': 0.017649074098483247, 'weight_class_1': 5.096205012082707, 'weight_class_2': 7.208451695524899}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:17,313] Trial 1886 finished with value: 0.9475460061921699 and parameters: {'weight_class_0': 0.9868766325673161, 'weight_class_1': 4.790786577353868, 'weight_class_2': 6.855910467026259}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:17,324] Trial 1887 finished with value: 0.9493114912494084 and parameters: {'weight_class_0': 0.5272108873506886, 'weight_class_1': 4.828908884660393, 'weight_class_2': 6.901766192289387}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:17,349] Trial 1888 finished with value: 0.9491619210270379 and parameters: {'weight_class_0': 0.45372278046682024, 'weight_class_1': 4.8764010539307465, 'weight_class_2': 6.957512513043566}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:17,373] Trial 1889 finished with value: 0.946497271899613 and parameters: {'weight_class_0': 1.0050571518542895, 'weight_class_1': 5.412710144631889, 'weight_class_2': 4.6029285369515405}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:17,446] Trial 1890 finished with value: 0.9086477800390999 and parameters: {'weight_class_0': 0.9648008025207775, 'weight_class_1': 5.429655879185739, 'weight_class_2': 0.9175607789854618}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  63%|██████████████████████████████████████████████████████████████████████████████████                                                | 1893/3000 [00:42<00:32, 34.57it/s]

[I 2026-07-05 15:23:17,487] Trial 1891 finished with value: 0.9482131196950764 and parameters: {'weight_class_0': 0.9666726795308281, 'weight_class_1': 5.526398255211664, 'weight_class_2': 6.808277521564665}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:17,502] Trial 1893 finished with value: 0.9495965699140059 and parameters: {'weight_class_0': 0.5236454084050824, 'weight_class_1': 5.9813414137381855, 'weight_class_2': 4.645310943327909}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:17,522] Trial 1892 finished with value: 0.9486699839464855 and parameters: {'weight_class_0': 0.8843546278081303, 'weight_class_1': 5.347180451182206, 'weight_class_2': 7.001932580146982}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  63%|██████████████████████████████████████████████████████████████████████████████████▎                                               | 1900/3000 [00:42<00:29, 37.71it/s]

[I 2026-07-05 15:23:17,528] Trial 1894 finished with value: 0.9463056625005688 and parameters: {'weight_class_0': 1.0401043299633286, 'weight_class_1': 5.818546372676071, 'weight_class_2': 4.591589285384024}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:17,543] Trial 1895 finished with value: 0.9472291154904683 and parameters: {'weight_class_0': 0.9334528666995591, 'weight_class_1': 5.661155773245099, 'weight_class_2': 4.591477026603291}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:17,568] Trial 1896 finished with value: 0.9465470195315734 and parameters: {'weight_class_0': 1.0152896282940134, 'weight_class_1': 5.7203766794057875, 'weight_class_2': 4.582940067159141}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:17,609] Trial 1897 finished with value: 0.9467752492779108 and parameters: {'weight_class_0': 0.9841887532987653, 'weight_class_1': 5.7453593502239135, 'weight_class_2': 4.548468647307451}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:17,621] Trial 1898 finished with value: 0.9481957422820236 and parameters: {'weight_class_0': 0.966264127498778, 'weight_class_1': 9.933192480499647, 'weight_class_2': 4.891429268219127}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:17,622] Trial 1899 finished with value: 0.9482002633853993 and parameters: {'weight_class_0': 0.9324512758401902, 'weight_class_1': 9.959831147587373, 'weight_class_2': 4.714154117064171}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:17,664] Trial 1901 finished with value: 0.9477722336506705 and parameters: {'weight_class_0': 0.930242715226155, 'weight_class_1': 6.052411684913244, 'weight_class_2': 4.988263015441887}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  63%|██████████████████████████████████████████████████████████████████████████████████▍                                               | 1903/3000 [00:42<00:27, 39.18it/s]

[I 2026-07-05 15:23:17,671] Trial 1900 finished with value: 0.9473159994104395 and parameters: {'weight_class_0': 0.9435797544150101, 'weight_class_1': 5.965821184639647, 'weight_class_2': 4.675269607863607}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:17,705] Trial 1902 finished with value: 0.9496332676269205 and parameters: {'weight_class_0': 0.5154687466546963, 'weight_class_1': 7.127512199127251, 'weight_class_2': 4.908064791953222}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  64%|██████████████████████████████████████████████████████████████████████████████████▋                                               | 1907/3000 [00:42<00:30, 35.73it/s]

[I 2026-07-05 15:23:17,797] Trial 1903 finished with value: 0.9494892233648876 and parameters: {'weight_class_0': 0.5845331583390145, 'weight_class_1': 9.983417039872858, 'weight_class_2': 4.5905245237536}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:17,815] Trial 1905 finished with value: 0.9495516107272254 and parameters: {'weight_class_0': 0.5688698288272983, 'weight_class_1': 9.976420976350662, 'weight_class_2': 6.095139947956852}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:17,830] Trial 1904 finished with value: 0.9496723346218142 and parameters: {'weight_class_0': 0.541758352214883, 'weight_class_1': 7.381845238773767, 'weight_class_2': 5.9685212330857595}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:17,866] Trial 1906 finished with value: 0.9496143122416608 and parameters: {'weight_class_0': 0.5278010862073462, 'weight_class_1': 9.923310874947749, 'weight_class_2': 6.1544226242185145}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:17,893] Trial 1907 finished with value: 0.9496728914053008 and parameters: {'weight_class_0': 0.5387117492153162, 'weight_class_1': 7.2514974657310765, 'weight_class_2': 6.452616347403224}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:17,908] Trial 1908 finished with value: 0.9496666447243518 and parameters: {'weight_class_0': 0.5350544197951175, 'weight_class_1': 7.244736798334299, 'weight_class_2': 6.186591493735202}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:17,940] Trial 1910 finished with value: 0.9490312584052593 and parameters: {'weight_class_0': 0.5494000583240322, 'weight_class_1': 9.957323862488781, 'weight_class_2': 9.990367073973005}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:17,965] Trial 1909 finished with value: 0.9489723245628569 and parameters: {'weight_class_0': 0.5455187924843478, 'weight_class_1': 7.213375897087205, 'weight_class_2': 9.978215445272728}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  64%|███████████████████████████████████████████████████████████████████████████████████                                               | 1916/3000 [00:43<00:28, 37.50it/s]

[I 2026-07-05 15:23:17,974] Trial 1911 finished with value: 0.9493481740432492 and parameters: {'weight_class_0': 0.5463687412273834, 'weight_class_1': 7.04383029748103, 'weight_class_2': 8.49322437924836}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:17,996] Trial 1912 finished with value: 0.9496461702682101 and parameters: {'weight_class_0': 0.5653268679274471, 'weight_class_1': 7.340257759478058, 'weight_class_2': 6.050623684798053}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:18,019] Trial 1913 finished with value: 0.949081010964211 and parameters: {'weight_class_0': 0.5748874816564276, 'weight_class_1': 6.992317425642335, 'weight_class_2': 9.975500346808523}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:18,043] Trial 1914 finished with value: 0.9496704935138817 and parameters: {'weight_class_0': 0.5662858750685709, 'weight_class_1': 7.066150414036788, 'weight_class_2': 6.098470500672192}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:18,105] Trial 1915 finished with value: 0.9483140032363488 and parameters: {'weight_class_0': 0.3731008762392433, 'weight_class_1': 7.364461691513074, 'weight_class_2': 9.873386972250268}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:18,107] Trial 1916 finished with value: 0.9487492290048053 and parameters: {'weight_class_0': 0.3751675404671399, 'weight_class_1': 7.116705658877834, 'weight_class_2': 8.184652373980262}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  64%|███████████████████████████████████████████████████████████████████████████████████▏                                              | 1919/3000 [00:43<00:28, 37.50it/s]

[I 2026-07-05 15:23:18,128] Trial 1917 finished with value: 0.9482917902164165 and parameters: {'weight_class_0': 0.36715350783097567, 'weight_class_1': 7.150428419949005, 'weight_class_2': 9.864118341622772}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:18,177] Trial 1919 finished with value: 0.9487314485380107 and parameters: {'weight_class_0': 0.3936537390614172, 'weight_class_1': 7.232706883835931, 'weight_class_2': 8.555885125185409}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:18,183] Trial 1918 finished with value: 0.9487985433303628 and parameters: {'weight_class_0': 0.39242942414305504, 'weight_class_1': 7.205030698874653, 'weight_class_2': 8.253256251643332}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:18,233] Trial 1920 finished with value: 0.9482871857953229 and parameters: {'weight_class_0': 0.3696920812638635, 'weight_class_1': 7.374588636659175, 'weight_class_2': 9.986106522854206}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:18,258] Trial 1921 finished with value: 0.948921611674964 and parameters: {'weight_class_0': 0.3816270120774211, 'weight_class_1': 7.322926188379431, 'weight_class_2': 7.5823352828641335}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:18,337] Trial 1923 finished with value: 0.9488626764059745 and parameters: {'weight_class_0': 0.3775715864945812, 'weight_class_1': 8.421235487328047, 'weight_class_2': 7.279928234504198}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  64%|███████████████████████████████████████████████████████████████████████████████████▌                                              | 1927/3000 [00:43<00:31, 34.56it/s]

[I 2026-07-05 15:23:18,344] Trial 1922 finished with value: 0.948850881420587 and parameters: {'weight_class_0': 0.3799682490876241, 'weight_class_1': 8.423814523269108, 'weight_class_2': 7.526302988285047}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:18,351] Trial 1924 finished with value: 0.9487541956479131 and parameters: {'weight_class_0': 0.3744716957093465, 'weight_class_1': 8.441168433920025, 'weight_class_2': 7.711777262519357}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:18,372] Trial 1925 finished with value: 0.9486681858145145 and parameters: {'weight_class_0': 0.36277147273580207, 'weight_class_1': 8.453977525426454, 'weight_class_2': 7.666993366428515}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:18,422] Trial 1926 finished with value: 0.9496172236423853 and parameters: {'weight_class_0': 0.7023604796329405, 'weight_class_1': 8.53053594927107, 'weight_class_2': 7.237006261253175}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:18,438] Trial 1928 finished with value: 0.9496765187844932 and parameters: {'weight_class_0': 0.6977288947563188, 'weight_class_1': 8.441063037522593, 'weight_class_2': 7.710972578883821}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  64%|███████████████████████████████████████████████████████████████████████████████████▋                                              | 1932/3000 [00:43<00:28, 37.28it/s]

[I 2026-07-05 15:23:18,457] Trial 1929 finished with value: 0.8993691209574958 and parameters: {'weight_class_0': 0.6998987706948342, 'weight_class_1': 8.559350120002842, 'weight_class_2': 0.4054463434654631}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:18,465] Trial 1927 finished with value: 0.9496521253718884 and parameters: {'weight_class_0': 0.6965596888508602, 'weight_class_1': 9.982273729857852, 'weight_class_2': 7.560793919340132}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:18,486] Trial 1930 finished with value: 0.7101597922804821 and parameters: {'weight_class_0': 0.6936955226712783, 'weight_class_1': 8.3774908004409, 'weight_class_2': 0.005036546374935196}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:18,506] Trial 1931 finished with value: 0.9496399374165971 and parameters: {'weight_class_0': 0.7029151721188632, 'weight_class_1': 8.648807755468933, 'weight_class_2': 7.357675035775694}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:18,533] Trial 1932 finished with value: 0.949643639784056 and parameters: {'weight_class_0': 0.6827241565739306, 'weight_class_1': 8.58472456527361, 'weight_class_2': 7.255515664172184}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  64%|███████████████████████████████████████████████████████████████████████████████████▊                                              | 1935/3000 [00:43<00:27, 38.77it/s]

[I 2026-07-05 15:23:18,569] Trial 1933 finished with value: 0.8929923481356226 and parameters: {'weight_class_0': 0.7172752035132869, 'weight_class_1': 9.989256071521192, 'weight_class_2': 0.17581642056061567}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:18,645] Trial 1934 finished with value: 0.9496236706771882 and parameters: {'weight_class_0': 0.6713592285454382, 'weight_class_1': 9.976589555859794, 'weight_class_2': 5.763532193969066}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:18,657] Trial 1935 finished with value: 0.8930437805023875 and parameters: {'weight_class_0': 0.7337491964577724, 'weight_class_1': 8.59992659045855, 'weight_class_2': 0.17201072363848607}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  65%|████████████████████████████████████████████████████████████████████████████████████                                              | 1939/3000 [00:43<00:29, 35.41it/s]

[I 2026-07-05 15:23:18,674] Trial 1936 finished with value: 0.9496611657562936 and parameters: {'weight_class_0': 0.6993815314323464, 'weight_class_1': 9.958927038910893, 'weight_class_2': 5.9692656751668}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:18,715] Trial 1937 finished with value: 0.9496262993286493 and parameters: {'weight_class_0': 0.6704912425980961, 'weight_class_1': 9.964485309726022, 'weight_class_2': 5.714979122356867}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:18,731] Trial 1938 finished with value: 0.9496067132613742 and parameters: {'weight_class_0': 0.6633101347175451, 'weight_class_1': 9.970212048153057, 'weight_class_2': 5.632107529007906}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:18,760] Trial 1939 finished with value: 0.9495058050328891 and parameters: {'weight_class_0': 0.6803040734732779, 'weight_class_1': 6.102716173921039, 'weight_class_2': 5.67101196198655}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  65%|████████████████████████████████████████████████████████████████████████████████████▏                                             | 1943/3000 [00:43<00:29, 36.26it/s]

[I 2026-07-05 15:23:18,805] Trial 1941 finished with value: 0.8810277715246316 and parameters: {'weight_class_0': 1.5209859785817408, 'weight_class_1': 4.269554579049014, 'weight_class_2': 0.13452132953950857}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:18,807] Trial 1940 finished with value: 0.9493383583356124 and parameters: {'weight_class_0': 0.452835156154671, 'weight_class_1': 4.107244997389846, 'weight_class_2': 5.741041392290973}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:18,831] Trial 1943 finished with value: 0.9494365930603325 and parameters: {'weight_class_0': 0.44746990824747657, 'weight_class_1': 9.972595381118015, 'weight_class_2': 5.756115178759908}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:18,834] Trial 1942 finished with value: 0.9496478627079724 and parameters: {'weight_class_0': 0.4522887812418639, 'weight_class_1': 6.171121764095838, 'weight_class_2': 5.845545353635914}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  65%|████████████████████████████████████████████████████████████████████████████████████▍                                             | 1948/3000 [00:43<00:27, 38.28it/s]

[I 2026-07-05 15:23:18,863] Trial 1944 finished with value: 0.9493987296454103 and parameters: {'weight_class_0': 0.4537800055005781, 'weight_class_1': 4.318514619266445, 'weight_class_2': 5.704019033372486}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:18,869] Trial 1945 finished with value: 0.949401014560959 and parameters: {'weight_class_0': 0.4545223143453306, 'weight_class_1': 4.212977226977101, 'weight_class_2': 5.6347742548215045}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:18,938] Trial 1946 finished with value: 0.6928140155752991 and parameters: {'weight_class_0': 0.009358442399259738, 'weight_class_1': 6.066082888092819, 'weight_class_2': 6.065005497652747}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:18,959] Trial 1947 finished with value: 0.9494713728449972 and parameters: {'weight_class_0': 0.47089315468082826, 'weight_class_1': 4.289522258341021, 'weight_class_2': 5.446068386556509}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:18,986] Trial 1948 finished with value: 0.9398998627599534 and parameters: {'weight_class_0': 1.4747254165769066, 'weight_class_1': 4.270791335462297, 'weight_class_2': 5.624473418588154}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  65%|████████████████████████████████████████████████████████████████████████████████████▌                                             | 1951/3000 [00:44<00:28, 37.39it/s]

[I 2026-07-05 15:23:19,021] Trial 1950 finished with value: 0.9491107524422975 and parameters: {'weight_class_0': 0.8209065848560018, 'weight_class_1': 6.1846138119256855, 'weight_class_2': 6.385962468491303}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:19,035] Trial 1949 finished with value: 0.9489067063818651 and parameters: {'weight_class_0': 0.45408414314734397, 'weight_class_1': 5.963627246631672, 'weight_class_2': 8.532278488808508}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:19,055] Trial 1951 finished with value: 0.944868665053115 and parameters: {'weight_class_0': 1.4899350709271875, 'weight_class_1': 6.263435077060543, 'weight_class_2': 6.507308154653641}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  65%|████████████████████████████████████████████████████████████████████████████████████▋                                             | 1955/3000 [00:44<00:29, 35.11it/s]

[I 2026-07-05 15:23:19,121] Trial 1952 finished with value: 0.949173444841081 and parameters: {'weight_class_0': 0.8429740490072791, 'weight_class_1': 6.045564831811164, 'weight_class_2': 8.342019826848928}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:19,159] Trial 1953 finished with value: 0.9491574541382369 and parameters: {'weight_class_0': 0.8317410729429535, 'weight_class_1': 6.146172146844783, 'weight_class_2': 8.598254438460758}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:19,196] Trial 1954 finished with value: 0.9491348278940105 and parameters: {'weight_class_0': 0.803234180509457, 'weight_class_1': 5.908490486462186, 'weight_class_2': 8.346259602522993}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:19,217] Trial 1955 finished with value: 0.9491438389083736 and parameters: {'weight_class_0': 0.8564813941403513, 'weight_class_1': 6.228484257393489, 'weight_class_2': 8.746712122231477}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  65%|████████████████████████████████████████████████████████████████████████████████████▉                                             | 1959/3000 [00:44<00:29, 35.20it/s]

[I 2026-07-05 15:23:19,236] Trial 1956 finished with value: 0.6736053462753673 and parameters: {'weight_class_0': 0.008509462904398184, 'weight_class_1': 6.116520884079454, 'weight_class_2': 8.521306472229899}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:19,253] Trial 1957 finished with value: 0.9491476498748675 and parameters: {'weight_class_0': 0.8378184344247748, 'weight_class_1': 6.141332902824162, 'weight_class_2': 8.566150318109734}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:19,295] Trial 1959 finished with value: 0.9491960663590572 and parameters: {'weight_class_0': 0.833425155287427, 'weight_class_1': 6.366921923101017, 'weight_class_2': 8.70920119249949}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:19,296] Trial 1958 finished with value: 0.9490029417804421 and parameters: {'weight_class_0': 0.8569325746999814, 'weight_class_1': 5.909010968014916, 'weight_class_2': 8.548641078211746}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  65%|█████████████████████████████████████████████████████████████████████████████████████                                             | 1964/3000 [00:44<00:26, 38.41it/s]

[I 2026-07-05 15:23:19,301] Trial 1960 finished with value: 0.9492033325283974 and parameters: {'weight_class_0': 0.8338900150386692, 'weight_class_1': 6.24358900895409, 'weight_class_2': 8.510609876350392}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:19,326] Trial 1961 finished with value: 0.947630098866755 and parameters: {'weight_class_0': 0.7811824485615981, 'weight_class_1': 6.837894016829562, 'weight_class_2': 3.565626587267215}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:19,376] Trial 1963 finished with value: 0.9479909902709133 and parameters: {'weight_class_0': 0.8512704570439906, 'weight_class_1': 7.355655519855158, 'weight_class_2': 4.233677412616013}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:19,378] Trial 1962 finished with value: 0.9492464179062189 and parameters: {'weight_class_0': 0.8124324062323702, 'weight_class_1': 6.299762866692695, 'weight_class_2': 8.592250386125528}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:19,390] Trial 1964 finished with value: 0.9483680059498781 and parameters: {'weight_class_0': 0.8237930075300148, 'weight_class_1': 7.329218698527726, 'weight_class_2': 4.418815243812232}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  66%|█████████████████████████████████████████████████████████████████████████████████████▏                                            | 1967/3000 [00:44<00:26, 38.41it/s]

[I 2026-07-05 15:23:19,468] Trial 1966 finished with value: 0.9490011559836652 and parameters: {'weight_class_0': 0.5417327711632172, 'weight_class_1': 7.35388372150876, 'weight_class_2': 3.472718117646374}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:19,471] Trial 1965 finished with value: 0.9487925832244243 and parameters: {'weight_class_0': 0.5939950827029316, 'weight_class_1': 6.735276616240354, 'weight_class_2': 3.4673687584694197}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:19,526] Trial 1967 finished with value: 0.948706129316045 and parameters: {'weight_class_0': 0.6064612151930173, 'weight_class_1': 7.6501802260623615, 'weight_class_2': 3.4474267884427063}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:19,557] Trial 1968 finished with value: 0.9431365972740737 and parameters: {'weight_class_0': 1.1872409352569449, 'weight_class_1': 7.522170146084156, 'weight_class_2': 3.63639424062912}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:19,579] Trial 1969 finished with value: 0.9055638067452634 and parameters: {'weight_class_0': 0.5949717922294555, 'weight_class_1': 7.820114840510962, 'weight_class_2': 0.4879615308304824}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:19,611] Trial 1971 finished with value: 0.9494080197947947 and parameters: {'weight_class_0': 0.5964300853609745, 'weight_class_1': 7.6572408046012725, 'weight_class_2': 4.4686290006852145}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:19,619] Trial 1970 finished with value: 0.9495214515934868 and parameters: {'weight_class_0': 0.581980992804622, 'weight_class_1': 8.073588665998455, 'weight_class_2': 4.576364162157005}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:19,649] Trial 1972 finished with value: 0.9493986000767948 and parameters: {'weight_class_0': 0.599561706462532, 'weight_class_1': 7.595420377258546, 'weight_class_2': 4.464591414977766}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:19,662] Trial 1973 finished with value: 0.9446687653347213 and parameters: {'weight_class_0': 2.1334109904606215, 'weight_class_1': 8.158762228445118, 'weight_class_2': 9.988973993974268}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:19,725] Trial 1975 finished with value: 0.9481916267138777 and parameters: {'weight_class_0': 1.1844892062810628, 'weight_class_1': 8.258505921193462, 'weight_class_2': 6.844371336463093}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:19,727] Trial 1974 finished with value: 0.9496820440126879 and parameters: {'weight_class_0': 0.6007040671127063, 'weight_class_1': 8.286496738186417, 'weight_class_2': 6.919560073801103}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:19,747] Trial 1976 finished with value: 0.9496342061956943 and parameters: {'weight_class_0': 0.5658645967693183, 'weight_class_1': 8.224103533962268, 'weight_class_2': 6.814167592410554}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:19,791] Trial 1977 finished with value: 0.9496446921226136 and parameters: {'weight_class_0': 0.5974122657856601, 'weight_class_1': 8.686856355497953, 'weight_class_2': 7.034195626868611}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:19,802] Trial 1978 finished with value: 0.9410566955322365 and parameters: {'weight_class_0': 2.141087451381283, 'weight_class_1': 8.511186178612911, 'weight_class_2': 6.622155315465474}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:19,845] Trial 1979 finished with value: 0.9107608450779057 and parameters: {'weight_class_0': 0.4975550633779746, 'weight_class_1': 8.733864852548185, 'weight_class_2': 0.49016296269041176}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  66%|█████████████████████████████████████████████████████████████████████████████████████▉                                            | 1983/3000 [00:44<00:27, 37.27it/s]

[I 2026-07-05 15:23:19,861] Trial 1980 finished with value: 0.9494269485628464 and parameters: {'weight_class_0': 0.4600974193201154, 'weight_class_1': 8.392077751871325, 'weight_class_2': 6.780172802764176}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:19,890] Trial 1981 finished with value: 0.9355665297561782 and parameters: {'weight_class_0': 2.114709141131955, 'weight_class_1': 5.109074506335531, 'weight_class_2': 6.78063830311878}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:19,949] Trial 1982 finished with value: 0.949382931773914 and parameters: {'weight_class_0': 0.4902141751064932, 'weight_class_1': 9.974586995222081, 'weight_class_2': 6.880792879667508}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:19,966] Trial 1983 finished with value: 0.9493269877152489 and parameters: {'weight_class_0': 0.463152266207354, 'weight_class_1': 9.95353018879183, 'weight_class_2': 6.706209375391118}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:19,998] Trial 1984 finished with value: 0.9492058577312922 and parameters: {'weight_class_0': 0.49964973773393545, 'weight_class_1': 4.769139407021909, 'weight_class_2': 7.027532196847019}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:20,022] Trial 1985 finished with value: 0.9496142847552703 and parameters: {'weight_class_0': 0.6437125672993927, 'weight_class_1': 9.950917909131144, 'weight_class_2': 7.070780495761844}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:20,030] Trial 1986 finished with value: 0.9496341909141731 and parameters: {'weight_class_0': 0.6689420580602375, 'weight_class_1': 8.905987998824209, 'weight_class_2': 6.723681945822782}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  66%|██████████████████████████████████████████████████████████████████████████████████████▎                                           | 1991/3000 [00:45<00:27, 36.56it/s]

[I 2026-07-05 15:23:20,075] Trial 1987 finished with value: 0.865320211690295 and parameters: {'weight_class_0': 9.958103380020747, 'weight_class_1': 8.52607687304418, 'weight_class_2': 6.837569422720534}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:20,104] Trial 1988 finished with value: 0.9496233188458771 and parameters: {'weight_class_0': 0.6431803531341417, 'weight_class_1': 8.561472673494167, 'weight_class_2': 6.440610210763723}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:20,120] Trial 1989 finished with value: 0.9496760553392662 and parameters: {'weight_class_0': 0.664065919688266, 'weight_class_1': 8.618687026792312, 'weight_class_2': 7.261777814187591}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:20,167] Trial 1991 finished with value: 0.9496468294722963 and parameters: {'weight_class_0': 0.6930672056799948, 'weight_class_1': 8.48025805555761, 'weight_class_2': 7.047082535025517}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:20,186] Trial 1990 finished with value: 0.9496234542812112 and parameters: {'weight_class_0': 0.6416247528746553, 'weight_class_1': 9.917528975690226, 'weight_class_2': 7.269228391665171}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  66%|██████████████████████████████████████████████████████████████████████████████████████▍                                           | 1994/3000 [00:45<00:27, 36.29it/s]

[I 2026-07-05 15:23:20,207] Trial 1992 finished with value: 0.6870258382235241 and parameters: {'weight_class_0': 0.012154730640219956, 'weight_class_1': 9.821002218597869, 'weight_class_2': 7.247460979115965}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:20,211] Trial 1993 finished with value: 0.9493991673619601 and parameters: {'weight_class_0': 0.6610086496400849, 'weight_class_1': 9.827489177025802, 'weight_class_2': 9.97315558878745}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:20,271] Trial 1994 finished with value: 0.9496986395481896 and parameters: {'weight_class_0': 0.656013467596775, 'weight_class_1': 8.704464145515699, 'weight_class_2': 7.50249139321163}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:20,307] Trial 1995 finished with value: 0.9497216641671216 and parameters: {'weight_class_0': 0.6577974732345979, 'weight_class_1': 8.451699965002469, 'weight_class_2': 7.54721343703048}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:20,344] Trial 1996 finished with value: 0.9496964135864977 and parameters: {'weight_class_0': 0.6382478143181008, 'weight_class_1': 8.521963152117179, 'weight_class_2': 7.477281930430941}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:20,345] Trial 1997 finished with value: 0.9495642122721198 and parameters: {'weight_class_0': 0.6578711546909826, 'weight_class_1': 8.323187943459727, 'weight_class_2': 8.706214966139912}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:20,363] Trial 1998 finished with value: 0.9495389731101654 and parameters: {'weight_class_0': 0.6495672116634669, 'weight_class_1': 7.326312597988735, 'weight_class_2': 8.450874038072628}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:20,394] Trial 1999 finished with value: 0.9489661559617878 and parameters: {'weight_class_0': 1.1324568212535604, 'weight_class_1': 7.378724226595937, 'weight_class_2': 9.918935722836823}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  67%|██████████████████████████████████████████████████████████████████████████████████████▊                                           | 2003/3000 [00:45<00:27, 36.88it/s]

[I 2026-07-05 15:23:20,415] Trial 2000 finished with value: 0.9489834630245849 and parameters: {'weight_class_0': 1.078344321245319, 'weight_class_1': 7.142556089218744, 'weight_class_2': 9.879130076618043}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:20,460] Trial 2001 finished with value: 0.949499687937974 and parameters: {'weight_class_0': 0.9822341410591863, 'weight_class_1': 9.932531926160799, 'weight_class_2': 9.921973697640835}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:20,476] Trial 2002 finished with value: 0.9493845595982285 and parameters: {'weight_class_0': 0.7927908129031979, 'weight_class_1': 7.187113596154477, 'weight_class_2': 9.985884064388417}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:20,508] Trial 2003 finished with value: 0.9489655457653541 and parameters: {'weight_class_0': 1.0703447118508462, 'weight_class_1': 7.169160887633951, 'weight_class_2': 8.433863206667615}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:20,527] Trial 2004 finished with value: 0.9490744289047951 and parameters: {'weight_class_0': 1.0535798146403543, 'weight_class_1': 7.307243467792401, 'weight_class_2': 8.519451969494876}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:20,577] Trial 2006 finished with value: 0.949429864812898 and parameters: {'weight_class_0': 1.0955430438447475, 'weight_class_1': 9.896633199149829, 'weight_class_2': 8.670787674428647}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:20,612] Trial 2005 finished with value: 0.9493172084146363 and parameters: {'weight_class_0': 0.9553428430959231, 'weight_class_1': 7.503038848934986, 'weight_class_2': 8.585081379403093}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  67%|███████████████████████████████████████████████████████████████████████████████████████                                           | 2009/3000 [00:45<00:28, 35.04it/s]

[I 2026-07-05 15:23:20,634] Trial 2007 finished with value: 0.9490834058638908 and parameters: {'weight_class_0': 1.0842033030795488, 'weight_class_1': 7.390260863208124, 'weight_class_2': 9.88796098752366}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:20,662] Trial 2008 finished with value: 0.949419326048786 and parameters: {'weight_class_0': 1.0875661261424714, 'weight_class_1': 9.900454780969167, 'weight_class_2': 8.62023242740766}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:20,720] Trial 2009 finished with value: 0.9495742822759682 and parameters: {'weight_class_0': 0.9808088618257036, 'weight_class_1': 9.87113586031042, 'weight_class_2': 8.565925858458076}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  67%|███████████████████████████████████████████████████████████████████████████████████████▏                                          | 2013/3000 [00:45<00:29, 33.56it/s]

[I 2026-07-05 15:23:20,756] Trial 2012 finished with value: 0.9495433147767355 and parameters: {'weight_class_0': 0.7932252298787686, 'weight_class_1': 8.558890730914914, 'weight_class_2': 8.57046258321292}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:20,758] Trial 2010 finished with value: 0.9495184448786295 and parameters: {'weight_class_0': 0.9650043483257513, 'weight_class_1': 8.69286770982273, 'weight_class_2': 8.660489356065824}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:20,760] Trial 2011 finished with value: 0.9494380429410519 and parameters: {'weight_class_0': 0.9671340809478229, 'weight_class_1': 8.661852129051672, 'weight_class_2': 9.972306752140698}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:20,815] Trial 2013 finished with value: 0.9495061671805658 and parameters: {'weight_class_0': 0.9269997764209771, 'weight_class_1': 8.529404736740675, 'weight_class_2': 8.498007189177404}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  67%|███████████████████████████████████████████████████████████████████████████████████████▍                                          | 2018/3000 [00:45<00:26, 36.70it/s]

[I 2026-07-05 15:23:20,822] Trial 2015 finished with value: 0.9495478782238044 and parameters: {'weight_class_0': 0.8323433756419518, 'weight_class_1': 8.595262068270452, 'weight_class_2': 8.086040388607486}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:20,834] Trial 2014 finished with value: 0.9494799225574356 and parameters: {'weight_class_0': 0.7922615295331857, 'weight_class_1': 8.363392823811642, 'weight_class_2': 8.520683934090188}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:20,852] Trial 2016 finished with value: 0.9496486339087017 and parameters: {'weight_class_0': 0.8187233475858242, 'weight_class_1': 9.925303523225077, 'weight_class_2': 9.917592922695157}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:20,870] Trial 2017 finished with value: 0.9495705647095051 and parameters: {'weight_class_0': 0.8056319827179133, 'weight_class_1': 8.804987317189491, 'weight_class_2': 8.47631670031635}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:20,911] Trial 2019 finished with value: 0.9495849808392754 and parameters: {'weight_class_0': 0.8017866738790407, 'weight_class_1': 8.562559873649747, 'weight_class_2': 7.859827411358437}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  67%|███████████████████████████████████████████████████████████████████████████████████████▌                                          | 2021/3000 [00:45<00:27, 36.21it/s]

[I 2026-07-05 15:23:20,920] Trial 2018 finished with value: 0.9496178914765993 and parameters: {'weight_class_0': 0.7962902356455762, 'weight_class_1': 9.915241754226063, 'weight_class_2': 7.924328506591498}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:20,944] Trial 2020 finished with value: 0.9494867049320758 and parameters: {'weight_class_0': 0.8233572312973091, 'weight_class_1': 7.788914348608724, 'weight_class_2': 7.843251239838514}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:21,019] Trial 2021 finished with value: 0.9495661351838143 and parameters: {'weight_class_0': 0.7710828092927834, 'weight_class_1': 8.479537137419856, 'weight_class_2': 7.650530373892176}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:21,066] Trial 2022 finished with value: 0.9495516693470946 and parameters: {'weight_class_0': 0.7852560119812825, 'weight_class_1': 8.417274585662199, 'weight_class_2': 7.5405806695418525}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:21,074] Trial 2023 finished with value: 0.9494527723262092 and parameters: {'weight_class_0': 0.7758611701474484, 'weight_class_1': 7.293201721709229, 'weight_class_2': 7.683934674578228}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:21,111] Trial 2024 finished with value: 0.9496729240701539 and parameters: {'weight_class_0': 0.7705282620470792, 'weight_class_1': 9.941304382990108, 'weight_class_2': 7.469842676882266}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:21,113] Trial 2025 finished with value: 0.6574892570110797 and parameters: {'weight_class_0': 0.0013670449692863142, 'weight_class_1': 7.346821981477132, 'weight_class_2': 7.401755419251531}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:21,172] Trial 2026 finished with value: 0.9494436422810826 and parameters: {'weight_class_0': 0.7343297288063374, 'weight_class_1': 6.861128112788712, 'weight_class_2': 7.519237846551076}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  68%|███████████████████████████████████████████████████████████████████████████████████████▉                                          | 2030/3000 [00:46<00:25, 37.41it/s]

[I 2026-07-05 15:23:21,182] Trial 2028 finished with value: 0.9492451062855481 and parameters: {'weight_class_0': 0.6994774784235278, 'weight_class_1': 6.987985422149564, 'weight_class_2': 9.975381399291837}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:21,186] Trial 2027 finished with value: 0.9495014529345905 and parameters: {'weight_class_0': 0.7361778935356964, 'weight_class_1': 6.928085516047794, 'weight_class_2': 7.187538604622477}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:21,207] Trial 2029 finished with value: 0.9491622153233652 and parameters: {'weight_class_0': 0.6567282282248911, 'weight_class_1': 6.779359458398403, 'weight_class_2': 9.983794771228853}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:21,250] Trial 2030 finished with value: 0.716151874944929 and parameters: {'weight_class_0': 0.6473942324246647, 'weight_class_1': 0.004721442672875519, 'weight_class_2': 7.28525520679385}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:21,300] Trial 2031 finished with value: 0.9495835153999655 and parameters: {'weight_class_0': 0.627556304629963, 'weight_class_1': 6.827462679121441, 'weight_class_2': 7.035112268284511}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:21,317] Trial 2032 finished with value: 0.7266085455751702 and parameters: {'weight_class_0': 0.6262597586329004, 'weight_class_1': 0.005053399693246728, 'weight_class_2': 7.20724814354526}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:21,337] Trial 2033 finished with value: 0.5368031165648769 and parameters: {'weight_class_0': 0.005665984728061829, 'weight_class_1': 6.850586639107882, 'weight_class_2': 0.009487892680379348}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  68%|████████████████████████████████████████████████████████████████████████████████████████▎                                         | 2038/3000 [00:46<00:26, 36.82it/s]

[I 2026-07-05 15:23:21,400] Trial 2034 finished with value: 0.9490655433800272 and parameters: {'weight_class_0': 0.6305215452737853, 'weight_class_1': 6.515109710941922, 'weight_class_2': 9.92551311563746}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:21,434] Trial 2036 finished with value: 0.9490931628029841 and parameters: {'weight_class_0': 0.612175497297953, 'weight_class_1': 6.612447758887235, 'weight_class_2': 9.920910253595348}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:21,439] Trial 2035 finished with value: 0.9494975631300102 and parameters: {'weight_class_0': 0.635774795148444, 'weight_class_1': 6.746896481869481, 'weight_class_2': 6.933337458780327}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:21,470] Trial 2037 finished with value: 0.9495833449272758 and parameters: {'weight_class_0': 0.5953045651356675, 'weight_class_1': 9.971031856697195, 'weight_class_2': 6.459115937277984}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:21,497] Trial 2038 finished with value: 0.9496183597098478 and parameters: {'weight_class_0': 0.5901005722919321, 'weight_class_1': 6.877410760396788, 'weight_class_2': 6.296465585062731}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  68%|████████████████████████████████████████████████████████████████████████████████████████▍                                         | 2041/3000 [00:46<00:26, 35.58it/s]

[I 2026-07-05 15:23:21,526] Trial 2039 finished with value: 0.9496559091193563 and parameters: {'weight_class_0': 0.5682348150662776, 'weight_class_1': 6.605129811398848, 'weight_class_2': 6.320667119284352}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:21,562] Trial 2040 finished with value: 0.9497017784682024 and parameters: {'weight_class_0': 0.5355250896550537, 'weight_class_1': 6.465344530695533, 'weight_class_2': 6.193475487169985}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:21,570] Trial 2041 finished with value: 0.9496659200462712 and parameters: {'weight_class_0': 0.562143670279212, 'weight_class_1': 6.523900030636844, 'weight_class_2': 6.265725828180248}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  68%|████████████████████████████████████████████████████████████████████████████████████████▌                                         | 2045/3000 [00:46<00:26, 36.03it/s]

[I 2026-07-05 15:23:21,581] Trial 2042 finished with value: 0.9496465224981416 and parameters: {'weight_class_0': 0.5662213448353296, 'weight_class_1': 6.5440153731037, 'weight_class_2': 6.166080440430087}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:21,671] Trial 2044 finished with value: 0.9473983381764165 and parameters: {'weight_class_0': 1.2822527061930082, 'weight_class_1': 9.923173648791028, 'weight_class_2': 5.889232980921653}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:21,677] Trial 2045 finished with value: 0.9496317580090053 and parameters: {'weight_class_0': 0.5308516582243502, 'weight_class_1': 6.445433900128524, 'weight_class_2': 6.445511176227887}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:21,688] Trial 2043 finished with value: 0.9497201682883117 and parameters: {'weight_class_0': 0.524166459956351, 'weight_class_1': 6.554870459228617, 'weight_class_2': 6.150997438114245}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  68%|████████████████████████████████████████████████████████████████████████████████████████▊                                         | 2049/3000 [00:46<00:26, 36.11it/s]

[I 2026-07-05 15:23:21,737] Trial 2046 finished with value: 0.9496570175614584 and parameters: {'weight_class_0': 0.5360291096470948, 'weight_class_1': 8.31083680502942, 'weight_class_2': 6.168124719856034}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:21,759] Trial 2047 finished with value: 0.9474214219832583 and parameters: {'weight_class_0': 1.2598463817383867, 'weight_class_1': 8.562409015573568, 'weight_class_2': 6.107021547405426}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:21,767] Trial 2048 finished with value: 0.9468637436895948 and parameters: {'weight_class_0': 1.3406679959677965, 'weight_class_1': 8.163481788873177, 'weight_class_2': 6.139584322130406}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  68%|█████████████████████████████████████████████████████████████████████████████████████████                                         | 2054/3000 [00:46<00:24, 38.63it/s]

[I 2026-07-05 15:23:21,827] Trial 2050 finished with value: 0.949630572671378 and parameters: {'weight_class_0': 0.5179888304091377, 'weight_class_1': 9.96830417664257, 'weight_class_2': 6.0068156286374785}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:21,829] Trial 2049 finished with value: 0.9496648972963806 and parameters: {'weight_class_0': 0.5297185768472562, 'weight_class_1': 8.475192189937149, 'weight_class_2': 6.131845880953606}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:21,856] Trial 2051 finished with value: 0.9496563536721472 and parameters: {'weight_class_0': 0.5263399274237196, 'weight_class_1': 8.393835594359592, 'weight_class_2': 5.908534794435316}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:21,875] Trial 2053 finished with value: 0.9496615481457945 and parameters: {'weight_class_0': 0.4734881068801785, 'weight_class_1': 5.45911340059753, 'weight_class_2': 5.3831536540932445}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:21,886] Trial 2052 finished with value: 0.9496422790399041 and parameters: {'weight_class_0': 0.4935123743091597, 'weight_class_1': 5.50999456244749, 'weight_class_2': 5.4641481098673195}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:21,914] Trial 2054 finished with value: 0.9496479506901698 and parameters: {'weight_class_0': 0.49183867854969887, 'weight_class_1': 5.58414322195597, 'weight_class_2': 5.233394633698028}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 1048. Best value: 0.949728:  69%|█████████████████████████████████████████████████████████████████████████████████████████                                         | 2056/3000 [00:46<00:24, 38.63it/s]

[I 2026-07-05 15:23:22,004] Trial 2055 finished with value: 0.9495619367473008 and parameters: {'weight_class_0': 0.5061967398157367, 'weight_class_1': 5.487286577462453, 'weight_class_2': 5.248877821532051}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:22,018] Trial 2056 finished with value: 0.9496266136612076 and parameters: {'weight_class_0': 0.4613922289261208, 'weight_class_1': 5.374790889542369, 'weight_class_2': 4.890334919788476}. Best is trial 1048 with value: 0.9497275203916301.

[I 2026-07-05 15:23:22,038] Trial 2057 finished with value: 0.9495739249370588 and parameters: {'weight_class_0': 0.4938232850274745, 'weight_class_1': 5.409649649236231, 'weight_class_2': 5.32844374859901}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:22,099] Trial 2059 finished with value: 0.9495895094497294 and parameters: {'weight_class_0': 0.4815295334561527, 'weight_class_1': 5.40197790157511, 'weight_class_2': 4.966916865168653}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:22,103] Trial 2058 finished with value: 0.9496657377465868 and parameters: {'weight_class_0': 0.476126455638641, 'weight_class_1': 5.395484376144681, 'weight_class_2': 5.286238915590465}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:22,137] Trial 2060 finished with value: 0.9496206264809968 and parameters: {'weight_class_0': 0.48870303829554973, 'weight_class_1': 5.530388939843395, 'weight_class_2': 5.094146943155574}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:22,141] Trial 2061 finished with value: 0.9495473363516777 and parameters: {'weight_class_0': 0.4716542256311168, 'weight_class_1': 5.241826962588954, 'weight_class_2': 4.772707494457197}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:22,194] Trial 2062 finished with value: 0.9496189916254231 and parameters: {'weight_class_0': 0.45734048961268803, 'weight_class_1': 5.337576498043143, 'weight_class_2': 4.924326104957312}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 2065. Best value: 0.949729:  69%|█████████████████████████████████████████████████████████████████████████████████████████▍                                        | 2064/3000 [00:47<00:27, 34.44it/s]

[I 2026-07-05 15:23:22,196] Trial 2063 finished with value: 0.9496875651314118 and parameters: {'weight_class_0': 0.4432991669607641, 'weight_class_1': 6.223697914756583, 'weight_class_2': 5.118836810684482}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:22,206] Trial 2064 finished with value: 0.9496448213462004 and parameters: {'weight_class_0': 0.4376581157410796, 'weight_class_1': 5.274882522387458, 'weight_class_2': 5.180330789845485}. Best is trial 1048 with value: 0.9497275203916301.

Best trial: 2065. Best value: 0.949729:  69%|█████████████████████████████████████████████████████████████████████████████████████████▋                                        | 2070/3000 [00:47<00:25, 36.26it/s]

[I 2026-07-05 15:23:22,233] Trial 2066 finished with value: 0.9496762643801667 and parameters: {'weight_class_0': 0.47328805764471965, 'weight_class_1': 5.371704291482083, 'weight_class_2': 5.233983159689447}. Best is trial 1048 with value: 0.9497275203916301.
[I 2026-07-05 15:23:22,244] Trial 2065 finished with value: 0.949728674027738 and parameters: {'weight_class_0': 0.4367740806169279, 'weight_class_1': 5.5027863853058205, 'weight_class_2': 5.044809647718666}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:22,330] Trial 2067 finished with value: 0.9497248917401689 and parameters: {'weight_class_0': 0.44132565186797623, 'weight_class_1': 5.427526179116453, 'weight_class_2': 5.073499474714655}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:22,368] Trial 2069 finished with value: 0.9497123666718993 and parameters: {'weight_class_0': 0.4346912953485608, 'weight_class_1': 5.569375500013022, 'weight_class_2': 5.100000395832344}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:22,378] Trial 2068 finished with value: 0.9495803318283896 and parameters: {'weight_class_0': 0.4411016593590946, 'weight_class_1': 4.822491924692409, 'weight_class_2': 5.132980639841478}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:22,407] Trial 2071 finished with value: 0.9496642303463111 and parameters: {'weight_class_0': 0.4227342025232771, 'weight_class_1': 5.554307973609793, 'weight_class_2': 5.068886021451494}. Best is trial 2065 with value: 0.949728674027738.

[I 2026-07-05 15:23:22,435] Trial 2070 finished with value: 0.9496572673090192 and parameters: {'weight_class_0': 0.4330812587553179, 'weight_class_1': 5.740781250865564, 'weight_class_2': 5.1960943219820654}. Best is trial 2065 with value: 0.949728674027738.

Best trial: 2065. Best value: 0.949729:  69%|██████████████████████████████████████████████████████████████████████████████████████████                                        | 2079/3000 [00:47<00:26, 35.02it/s]

[I 2026-07-05 15:23:22,467] Trial 2072 finished with value: 0.9495169830270932 and parameters: {'weight_class_0': 0.40003011550151, 'weight_class_1': 5.960988842707703, 'weight_class_2': 5.590622433016299}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:22,477] Trial 2073 finished with value: 0.9496787354992772 and parameters: {'weight_class_0': 0.45597237163950544, 'weight_class_1': 5.940576901185228, 'weight_class_2': 5.414718312679237}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:22,525] Trial 2075 finished with value: 0.9495046420060511 and parameters: {'weight_class_0': 0.42852532893473894, 'weight_class_1': 4.5118097520937726, 'weight_class_2': 4.442586493962421}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:22,544] Trial 2074 finished with value: 0.9496949301466101 and parameters: {'weight_class_0': 0.39762343457074867, 'weight_class_1': 4.696834364318779, 'weight_class_2': 4.519149184837754}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:22,569] Trial 2076 finished with value: 0.9496589781398005 and parameters: {'weight_class_0': 0.3521260501931869, 'weight_class_1': 4.283891687997448, 'weight_class_2': 4.30458770425425}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:22,588] Trial 2077 finished with value: 0.9496608550018039 and parameters: {'weight_class_0': 0.357979527751754, 'weight_class_1': 4.54862163271334, 'weight_class_2': 3.8566848695372675}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:22,643] Trial 2078 finished with value: 0.949674977883959 and parameters: {'weight_class_0': 0.40362299061063517, 'weight_class_1': 4.607273628285961, 'weight_class_2': 4.451887380211319}. Best is trial 2065 with value: 0.949728674027738.

Best trial: 2065. Best value: 0.949729:  70%|██████████████████████████████████████████████████████████████████████████████████████████▍                                       | 2087/3000 [00:47<00:26, 35.09it/s]

[I 2026-07-05 15:23:22,681] Trial 2079 finished with value: 0.9496314560410317 and parameters: {'weight_class_0': 0.3854653719063526, 'weight_class_1': 4.532341784091153, 'weight_class_2': 4.02891205678938}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:22,693] Trial 2080 finished with value: 0.9494830696553641 and parameters: {'weight_class_0': 0.33896881067362933, 'weight_class_1': 4.1159162321519505, 'weight_class_2': 4.734654315697521}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:22,719] Trial 2081 finished with value: 0.949521902821278 and parameters: {'weight_class_0': 0.40244370994352785, 'weight_class_1': 4.225958260556615, 'weight_class_2': 4.464032431352813}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:22,742] Trial 2082 finished with value: 0.949698437199708 and parameters: {'weight_class_0': 0.33388393271420136, 'weight_class_1': 4.685511758626948, 'weight_class_2': 3.875448706608538}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:22,794] Trial 2083 finished with value: 0.9496396458677857 and parameters: {'weight_class_0': 0.34820988572959777, 'weight_class_1': 3.962506353580904, 'weight_class_2': 3.986562185140373}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:22,823] Trial 2084 finished with value: 0.9496946206923039 and parameters: {'weight_class_0': 0.3297778886441589, 'weight_class_1': 4.224933530277673, 'weight_class_2': 4.042625067053654}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:22,827] Trial 2085 finished with value: 0.9495283861323145 and parameters: {'weight_class_0': 0.33832714024136357, 'weight_class_1': 3.7380937444544426, 'weight_class_2': 4.11751871710669}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:22,862] Trial 2086 finished with value: 0.9496687927731271 and parameters: {'weight_class_0': 0.3376176056266307, 'weight_class_1': 3.9798377113560623, 'weight_class_2': 3.6782205099372907}. Best is trial 2065 with value: 0.949728674027738.

Best trial: 2065. Best value: 0.949729:  70%|██████████████████████████████████████████████████████████████████████████████████████████▋                                       | 2094/3000 [00:48<00:25, 35.25it/s]

[I 2026-07-05 15:23:22,898] Trial 2087 finished with value: 0.9495868744142394 and parameters: {'weight_class_0': 0.35691734272681785, 'weight_class_1': 4.09959360079695, 'weight_class_2': 3.418140051924853}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:22,913] Trial 2089 finished with value: 0.9497099055733305 and parameters: {'weight_class_0': 0.32443806565956307, 'weight_class_1': 4.0187929738587655, 'weight_class_2': 3.8245120360248515}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:22,915] Trial 2088 finished with value: 0.9494890406776234 and parameters: {'weight_class_0': 0.355643810043155, 'weight_class_1': 3.576814630929924, 'weight_class_2': 3.5779815913987667}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:22,965] Trial 2090 finished with value: 0.9496969736030243 and parameters: {'weight_class_0': 0.32945368459445523, 'weight_class_1': 3.9477656788905757, 'weight_class_2': 3.771355021730187}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:23,004] Trial 2092 finished with value: 0.9496125471166496 and parameters: {'weight_class_0': 0.33584981129949687, 'weight_class_1': 4.00041296019531, 'weight_class_2': 3.486143661167612}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:23,019] Trial 2091 finished with value: 0.9496617668370755 and parameters: {'weight_class_0': 0.3230204410755202, 'weight_class_1': 3.747285056473481, 'weight_class_2': 3.7027057225030684}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:23,062] Trial 2093 finished with value: 0.9496139143476269 and parameters: {'weight_class_0': 0.3120080467097857, 'weight_class_1': 4.227211256091219, 'weight_class_2': 3.2829841202448793}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:23,069] Trial 2094 finished with value: 0.9496917684587437 and parameters: {'weight_class_0': 0.29427012727704543, 'weight_class_1': 4.010687427494256, 'weight_class_2': 3.3968367611708947}. Best is trial 2065 with value: 0.949728674027738.

Best trial: 2065. Best value: 0.949729:  70%|███████████████████████████████████████████████████████████████████████████████████████████▏                                      | 2103/3000 [00:48<00:26, 33.36it/s]

[I 2026-07-05 15:23:23,145] Trial 2095 finished with value: 0.9497202316600294 and parameters: {'weight_class_0': 0.29987323480794736, 'weight_class_1': 3.7187261025396294, 'weight_class_2': 3.521858519432464}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:23,148] Trial 2096 finished with value: 0.9496731707492426 and parameters: {'weight_class_0': 0.259870077865436, 'weight_class_1': 3.2851616876331318, 'weight_class_2': 3.1974596840368408}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:23,163] Trial 2097 finished with value: 0.9495819179152157 and parameters: {'weight_class_0': 0.2793891367729126, 'weight_class_1': 3.3980991208610334, 'weight_class_2': 3.7718683347107826}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:23,210] Trial 2098 finished with value: 0.9496733861457125 and parameters: {'weight_class_0': 0.2802658455681455, 'weight_class_1': 3.7317325136325024, 'weight_class_2': 3.396485607090832}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:23,267] Trial 2099 finished with value: 0.9496328438965606 and parameters: {'weight_class_0': 0.2648712711962387, 'weight_class_1': 2.997343062512937, 'weight_class_2': 2.8577563477392927}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:23,271] Trial 2100 finished with value: 0.9496550089701187 and parameters: {'weight_class_0': 0.2743529887410113, 'weight_class_1': 3.0832143664046043, 'weight_class_2': 3.0047110880709784}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:23,274] Trial 2101 finished with value: 0.9495439075816575 and parameters: {'weight_class_0': 0.29522361007782666, 'weight_class_1': 3.1703440581868705, 'weight_class_2': 3.2266123707474548}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:23,287] Trial 2102 finished with value: 0.9496918430435372 and parameters: {'weight_class_0': 0.2700233403879078, 'weight_class_1': 3.220842602314015, 'weight_class_2': 3.1201939759785873}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:23,348] Trial 2103 finished with value: 0.9495085861617802 and parameters: {'weight_class_0': 0.2996980966177163, 'weight_class_1': 3.3015417504646485, 'weight_class_2': 3.8259988349632756}. Best is trial 2065 with value: 0.949728674027738.

[I 2026-07-05 15:23:23,365] Trial 2104 finished with value: 0.9494678585237262 and parameters: {'weight_class_0': 0.3016685276215125, 'weight_class_1': 2.732968917245114, 'weight_class_2': 3.2187954315790406}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:23,383] Trial 2105 finished with value: 0.9495442959975925 and parameters: {'weight_class_0': 0.270072230330287, 'weight_class_1': 2.652600061153394, 'weight_class_2': 3.1324194863984567}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:23,438] Trial 2106 finished with value: 0.9496724811056566 and parameters: {'weight_class_0': 0.26438574872144727, 'weight_class_1': 3.550689264883657, 'weight_class_2': 3.007874497606656}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:23,521] Trial 2108 finished with value: 0.9497185484879201 and parameters: {'weight_class_0': 0.29688085429958194, 'weight_class_1': 3.7673767571618053, 'weight_class_2': 3.43339139762545}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:23,535] Trial 2107 finished with value: 0.9494992690699732 and parameters: {'weight_class_0': 0.27752841705202874, 'weight_class_1': 2.748533371139176, 'weight_class_2': 2.974900997175956}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:23,554] Trial 2109 finished with value: 0.9496257005590646 and parameters: {'weight_class_0': 0.261423538631541, 'weight_class_1': 3.6710703626150014, 'weight_class_2': 3.134495114612034}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:23,564] Trial 2110 finished with value: 0.9494474065270483 and parameters: {'weight_class_0': 0.28804975836132923, 'weight_class_1': 2.659867108952952, 'weight_class_2': 2.882025429923203}. Best is trial 2065 with value: 0.949728674027738.

Best trial: 2065. Best value: 0.949729:  71%|███████████████████████████████████████████████████████████████████████████████████████████▊                                      | 2118/3000 [00:48<00:23, 36.78it/s]

[I 2026-07-05 15:23:23,601] Trial 2112 finished with value: 0.9492645564985888 and parameters: {'weight_class_0': 0.20402440648977851, 'weight_class_1': 2.570571685305779, 'weight_class_2': 3.359876771874784}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:23,616] Trial 2113 finished with value: 0.949349342528946 and parameters: {'weight_class_0': 0.19719581940751718, 'weight_class_1': 2.68515386913488, 'weight_class_2': 3.0707107147299557}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:23,621] Trial 2111 finished with value: 0.9493442433341288 and parameters: {'weight_class_0': 0.2556530633627837, 'weight_class_1': 2.8778263494340686, 'weight_class_2': 3.8198034541037784}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:23,632] Trial 2114 finished with value: 0.9493694287414346 and parameters: {'weight_class_0': 0.21758378930935612, 'weight_class_1': 2.520721653313698, 'weight_class_2': 3.231468304032382}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:23,653] Trial 2115 finished with value: 0.9494636897246195 and parameters: {'weight_class_0': 0.2898603644962974, 'weight_class_1': 2.6328102676159757, 'weight_class_2': 2.8008150494083375}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:23,691] Trial 2116 finished with value: 0.9496366551304192 and parameters: {'weight_class_0': 0.25607647758091073, 'weight_class_1': 2.9975893560949363, 'weight_class_2': 2.9986383435406725}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:23,713] Trial 2117 finished with value: 0.9494287364662867 and parameters: {'weight_class_0': 0.21326745380889325, 'weight_class_1': 2.0926279324641386, 'weight_class_2': 2.6803291356128867}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:23,729] Trial 2118 finished with value: 0.9496304347100145 and parameters: {'weight_class_0': 0.20829311919443594, 'weight_class_1': 2.9281037123215055, 'weight_class_2': 2.694442768132584}. Best is trial 2065 with value: 0.949728674027738.

[I 2026-07-05 15:23:23,823] Trial 2119 finished with value: 0.9494751196507122 and parameters: {'weight_class_0': 0.1989883673162034, 'weight_class_1': 2.726108011114423, 'weight_class_2': 2.7887304912766986}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:23,907] Trial 2121 finished with value: 0.9493410225896085 and parameters: {'weight_class_0': 0.18513708360327696, 'weight_class_1': 2.3706599562222825, 'weight_class_2': 2.8955581344033954}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:23,945] Trial 2122 finished with value: 0.9496348507147593 and parameters: {'weight_class_0': 0.22791335012241395, 'weight_class_1': 3.065717596677889, 'weight_class_2': 2.959235782184832}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:23,947] Trial 2120 finished with value: 0.9496051926234103 and parameters: {'weight_class_0': 0.22569001875350406, 'weight_class_1': 2.788341505609174, 'weight_class_2': 3.0333614461404457}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:23,953] Trial 2123 finished with value: 0.9496256431394436 and parameters: {'weight_class_0': 0.2510704494394071, 'weight_class_1': 3.3408137103925952, 'weight_class_2': 2.691834791660187}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:23,982] Trial 2125 finished with value: 0.9494852157302575 and parameters: {'weight_class_0': 0.19917600143375336, 'weight_class_1': 3.097853647234018, 'weight_class_2': 2.7845151904648735}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:23,986] Trial 2124 finished with value: 0.9495004674117018 and parameters: {'weight_class_0': 0.22172643224874197, 'weight_class_1': 3.4130534922269082, 'weight_class_2': 3.09395587608725}. Best is trial 2065 with value: 0.949728674027738.

Best trial: 2065. Best value: 0.949729:  71%|████████████████████████████████████████████████████████████████████████████████████████████▍                                     | 2132/3000 [00:49<00:22, 38.44it/s]

[I 2026-07-05 15:23:24,006] Trial 2128 finished with value: 0.9491269823557817 and parameters: {'weight_class_0': 0.2044108230274108, 'weight_class_1': 3.4736628825750073, 'weight_class_2': 3.5235083043738378}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:24,014] Trial 2126 finished with value: 0.9492972997886135 and parameters: {'weight_class_0': 0.2182605141584309, 'weight_class_1': 3.2623855372206623, 'weight_class_2': 3.4704516131401504}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:24,028] Trial 2129 finished with value: 0.9493063046863123 and parameters: {'weight_class_0': 0.22290120637834326, 'weight_class_1': 3.372935636325413, 'weight_class_2': 3.4833082457817253}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:24,031] Trial 2127 finished with value: 0.9490633773562722 and parameters: {'weight_class_0': 0.18796882452046101, 'weight_class_1': 3.16386421079905, 'weight_class_2': 3.3262486403372966}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:24,051] Trial 2130 finished with value: 0.9492551611777614 and parameters: {'weight_class_0': 0.20922045420279714, 'weight_class_1': 3.210655849918059, 'weight_class_2': 3.4266138038463554}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:24,080] Trial 2131 finished with value: 0.9495660027556468 and parameters: {'weight_class_0': 0.29964954569715235, 'weight_class_1': 3.497093285087717, 'weight_class_2': 3.652859508156497}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:24,224] Trial 2132 finished with value: 0.9496011797606467 and parameters: {'weight_class_0': 0.2818420832717475, 'weight_class_1': 3.092910329026065, 'weight_class_2': 3.072203477456799}. Best is trial 2065 with value: 0.949728674027738.

Best trial: 2065. Best value: 0.949729:  71%|████████████████████████████████████████████████████████████████████████████████████████████▊                                     | 2142/3000 [00:49<00:23, 35.98it/s]

[I 2026-07-05 15:23:24,248] Trial 2133 finished with value: 0.9496007920850341 and parameters: {'weight_class_0': 0.30617597822564524, 'weight_class_1': 3.5514854485925804, 'weight_class_2': 3.621055826138632}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:24,267] Trial 2134 finished with value: 0.9483796238641803 and parameters: {'weight_class_0': 0.13770296308193922, 'weight_class_1': 1.9815139296743447, 'weight_class_2': 3.3970320789394486}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:24,317] Trial 2135 finished with value: 0.9496055971558054 and parameters: {'weight_class_0': 0.31327408748377583, 'weight_class_1': 3.500109665755486, 'weight_class_2': 3.5982616292198792}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:24,321] Trial 2136 finished with value: 0.9485625638028417 and parameters: {'weight_class_0': 0.3088867696909297, 'weight_class_1': 1.850026687111501, 'weight_class_2': 3.6311234972238906}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:24,344] Trial 2137 finished with value: 0.9494453705289733 and parameters: {'weight_class_0': 0.2700373564407341, 'weight_class_1': 3.700180686002095, 'weight_class_2': 3.8981883137044404}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:24,355] Trial 2138 finished with value: 0.9482070072801294 and parameters: {'weight_class_0': 0.14850770965634905, 'weight_class_1': 4.0746630785503575, 'weight_class_2': 3.8381384465600967}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:24,361] Trial 2139 finished with value: 0.9485288469018348 and parameters: {'weight_class_0': 0.3054828082417922, 'weight_class_1': 1.7903857251644473, 'weight_class_2': 3.4856171258223974}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:24,392] Trial 2141 finished with value: 0.9496012906265264 and parameters: {'weight_class_0': 0.2824053576532865, 'weight_class_1': 3.795264196720561, 'weight_class_2': 3.747267142259926}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:24,401] Trial 2140 finished with value: 0.948860681654546 and parameters: {'weight_class_0': 0.30311412583058917, 'weight_class_1': 2.111681765755966, 'weight_class_2': 3.885535645274767}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:24,417] Trial 2142 finished with value: 0.9487600618779406 and parameters: {'weight_class_0': 0.30930963930710553, 'weight_class_1': 2.0393537871449627, 'weight_class_2': 3.85025014976813}. Best is trial 2065 with value: 0.949728674027738.

Best trial: 2065. Best value: 0.949729:  72%|█████████████████████████████████████████████████████████████████████████████████████████████                                     | 2147/3000 [00:49<00:22, 37.80it/s]

[I 2026-07-05 15:23:24,427] Trial 2143 finished with value: 0.9489176598455978 and parameters: {'weight_class_0': 0.3088213135952831, 'weight_class_1': 2.1360741513866732, 'weight_class_2': 3.750132715240715}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:24,512] Trial 2144 finished with value: 0.9495464951770427 and parameters: {'weight_class_0': 0.315009183076337, 'weight_class_1': 3.7689098174894022, 'weight_class_2': 4.149704711540157}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:24,588] Trial 2145 finished with value: 0.949455059467577 and parameters: {'weight_class_0': 0.30488374623053854, 'weight_class_1': 3.605716540086814, 'weight_class_2': 4.2783079326899465}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:24,590] Trial 2146 finished with value: 0.949612551151783 and parameters: {'weight_class_0': 0.3197335919719183, 'weight_class_1': 3.621281109789436, 'weight_class_2': 3.9190383975550667}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:24,652] Trial 2147 finished with value: 0.9493146764136645 and parameters: {'weight_class_0': 0.3359487801629292, 'weight_class_1': 4.022646445747943, 'weight_class_2': 2.4867758807353493}. Best is trial 2065 with value: 0.949728674027738.

Best trial: 2065. Best value: 0.949729:  72%|█████████████████████████████████████████████████████████████████████████████████████████████▍                                    | 2156/3000 [00:49<00:23, 36.62it/s]

[I 2026-07-05 15:23:24,683] Trial 2148 finished with value: 0.9496586501091621 and parameters: {'weight_class_0': 0.30976279686533076, 'weight_class_1': 3.915844180631801, 'weight_class_2': 3.2971440976666644}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:24,696] Trial 2150 finished with value: 0.9495874333284622 and parameters: {'weight_class_0': 0.32701964712507947, 'weight_class_1': 3.7892629514879004, 'weight_class_2': 4.126557604446712}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:24,703] Trial 2149 finished with value: 0.9496211719075851 and parameters: {'weight_class_0': 0.3078635273672855, 'weight_class_1': 4.311098142171546, 'weight_class_2': 4.086959859924515}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:24,731] Trial 2151 finished with value: 0.9495548068974391 and parameters: {'weight_class_0': 0.33903185401485886, 'weight_class_1': 3.714095508924342, 'weight_class_2': 4.057446530258834}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:24,754] Trial 2153 finished with value: 0.9495209633557936 and parameters: {'weight_class_0': 0.3495750185165852, 'weight_class_1': 3.637461424936135, 'weight_class_2': 3.984134554463712}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:24,755] Trial 2152 finished with value: 0.9493374256620166 and parameters: {'weight_class_0': 0.3414303133705825, 'weight_class_1': 3.7982208776937525, 'weight_class_2': 2.5633631614383305}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:24,772] Trial 2154 finished with value: 0.9495784236427419 and parameters: {'weight_class_0': 0.34454889582002657, 'weight_class_1': 4.0005779727729545, 'weight_class_2': 4.129670297893413}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:24,787] Trial 2155 finished with value: 0.9495795687515187 and parameters: {'weight_class_0': 0.3370336736973854, 'weight_class_1': 3.6633852630715995, 'weight_class_2': 3.934093585126355}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:24,800] Trial 2156 finished with value: 0.9492334674387702 and parameters: {'weight_class_0': 0.3568007531259029, 'weight_class_1': 3.993496965697248, 'weight_class_2': 2.5825271842002273}. Best is trial 2065 with value: 0.949728674027738.

Best trial: 2065. Best value: 0.949729:  72%|█████████████████████████████████████████████████████████████████████████████████████████████▊                                    | 2164/3000 [00:50<00:25, 32.96it/s]

[I 2026-07-05 15:23:24,923] Trial 2157 finished with value: 0.9492038483268183 and parameters: {'weight_class_0': 0.3428231954854426, 'weight_class_1': 4.273742656598816, 'weight_class_2': 2.368922244120385}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:24,931] Trial 2158 finished with value: 0.9492286840128031 and parameters: {'weight_class_0': 0.3532772054740834, 'weight_class_1': 3.891526950465291, 'weight_class_2': 2.5934270369206587}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:25,011] Trial 2159 finished with value: 0.9495452899754661 and parameters: {'weight_class_0': 0.24554623552669852, 'weight_class_1': 4.211224458479109, 'weight_class_2': 2.3465576366221614}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:25,046] Trial 2160 finished with value: 0.9496351182206658 and parameters: {'weight_class_0': 0.24788448435376426, 'weight_class_1': 4.010528924980278, 'weight_class_2': 2.178614479009438}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:25,058] Trial 2161 finished with value: 0.9496062299319181 and parameters: {'weight_class_0': 0.2461572248404252, 'weight_class_1': 4.316896748605911, 'weight_class_2': 2.315618288426847}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:25,073] Trial 2162 finished with value: 0.9496009604984638 and parameters: {'weight_class_0': 0.24682035017578446, 'weight_class_1': 4.372576809596281, 'weight_class_2': 2.3491452833008775}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:25,083] Trial 2163 finished with value: 0.9495483390499097 and parameters: {'weight_class_0': 0.23662473811524795, 'weight_class_1': 4.440484343649215, 'weight_class_2': 2.476014211172149}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:25,096] Trial 2165 finished with value: 0.9489033361507225 and parameters: {'weight_class_0': 0.3636815335714809, 'weight_class_1': 4.699916172211715, 'weight_class_2': 2.2119248541624676}. Best is trial 2065 with value: 0.949728674027738.

Best trial: 2065. Best value: 0.949729:  72%|██████████████████████████████████████████████████████████████████████████████████████████████                                    | 2171/3000 [00:50<00:21, 38.53it/s]

[I 2026-07-05 15:23:25,105] Trial 2164 finished with value: 0.9492037215833831 and parameters: {'weight_class_0': 0.35871231901897094, 'weight_class_1': 4.509521659873317, 'weight_class_2': 2.4812064735254755}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:25,128] Trial 2167 finished with value: 0.9496180656649916 and parameters: {'weight_class_0': 0.2734666869927078, 'weight_class_1': 4.467972938446344, 'weight_class_2': 2.26765048483559}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:25,130] Trial 2166 finished with value: 0.9489780420828183 and parameters: {'weight_class_0': 0.23338642473447851, 'weight_class_1': 4.741073903593703, 'weight_class_2': 4.265682166111949}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:25,173] Trial 2168 finished with value: 0.9493341906441276 and parameters: {'weight_class_0': 0.2656411769599408, 'weight_class_1': 4.42101535880083, 'weight_class_2': 4.262165933820875}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:25,192] Trial 2169 finished with value: 0.9481194382990003 and parameters: {'weight_class_0': 0.1584817901449214, 'weight_class_1': 4.345601127848665, 'weight_class_2': 4.275266279159081}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:25,220] Trial 2170 finished with value: 0.9496714209106049 and parameters: {'weight_class_0': 0.35732990509961654, 'weight_class_1': 4.859594612184368, 'weight_class_2': 4.2312867562952325}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:25,308] Trial 2171 finished with value: 0.9496941546308171 and parameters: {'weight_class_0': 0.35434389669265315, 'weight_class_1': 4.540005026176043, 'weight_class_2': 4.267715907581255}. Best is trial 2065 with value: 0.949728674027738.

Best trial: 2065. Best value: 0.949729:  73%|██████████████████████████████████████████████████████████████████████████████████████████████▍                                   | 2180/3000 [00:50<00:24, 33.66it/s]

[I 2026-07-05 15:23:25,367] Trial 2172 finished with value: 0.949363944183727 and parameters: {'weight_class_0': 0.2650454705544821, 'weight_class_1': 4.545518670554123, 'weight_class_2': 4.0506117774226205}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:25,378] Trial 2173 finished with value: 0.9496934653573921 and parameters: {'weight_class_0': 0.3627369543749291, 'weight_class_1': 4.697753414141734, 'weight_class_2': 4.369726492298861}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:25,443] Trial 2174 finished with value: 0.9492768350446236 and parameters: {'weight_class_0': 0.2612758996450346, 'weight_class_1': 4.590431936512438, 'weight_class_2': 4.344366310484173}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:25,454] Trial 2176 finished with value: 0.9492078528788847 and parameters: {'weight_class_0': 0.3819303968270709, 'weight_class_1': 2.871952162587227, 'weight_class_2': 4.272035064192995}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:25,473] Trial 2175 finished with value: 0.9496770316693048 and parameters: {'weight_class_0': 0.3790366405000099, 'weight_class_1': 4.526876197135275, 'weight_class_2': 4.2904738083512575}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:25,505] Trial 2177 finished with value: 0.9496874134150496 and parameters: {'weight_class_0': 0.37297665046191747, 'weight_class_1': 4.5321470656748595, 'weight_class_2': 4.154736358290765}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:25,507] Trial 2178 finished with value: 0.949158426967871 and parameters: {'weight_class_0': 0.3866962276937953, 'weight_class_1': 2.9165103221599997, 'weight_class_2': 4.170169037016449}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:25,517] Trial 2179 finished with value: 0.9493656230354541 and parameters: {'weight_class_0': 0.3762746707274501, 'weight_class_1': 3.085280762749582, 'weight_class_2': 3.1398599457510246}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:25,529] Trial 2180 finished with value: 0.9488778202880205 and parameters: {'weight_class_0': 0.37118432285256137, 'weight_class_1': 2.4476297032922, 'weight_class_2': 4.273752639440079}. Best is trial 2065 with value: 0.949728674027738.

[I 2026-07-05 15:23:25,533] Trial 2181 finished with value: 0.9493331760822622 and parameters: {'weight_class_0': 0.3888457105075038, 'weight_class_1': 3.093016337127662, 'weight_class_2': 3.186490987869872}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:25,547] Trial 2182 finished with value: 0.9492672447076549 and parameters: {'weight_class_0': 0.3812114302028836, 'weight_class_1': 2.911274977698031, 'weight_class_2': 3.465844131798051}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:25,593] Trial 2183 finished with value: 0.9494849369900638 and parameters: {'weight_class_0': 0.38430810840442936, 'weight_class_1': 3.4774703744329316, 'weight_class_2': 3.098621439681415}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:25,666] Trial 2184 finished with value: 0.9492802945239042 and parameters: {'weight_class_0': 0.38533663468382784, 'weight_class_1': 2.845022845205146, 'weight_class_2': 3.2533355236673893}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:25,683] Trial 2185 finished with value: 0.9494290695441316 and parameters: {'weight_class_0': 0.3628027000093171, 'weight_class_1': 3.234959826379487, 'weight_class_2': 3.6646249018150603}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:25,746] Trial 2186 finished with value: 0.9492878028642419 and parameters: {'weight_class_0': 0.37214907575158956, 'weight_class_1': 2.9121135496058383, 'weight_class_2': 3.1245915415771983}. Best is trial 2065 with value: 0.949728674027738.

Best trial: 2193. Best value: 0.949739:  73%|███████████████████████████████████████████████████████████████████████████████████████████████                                   | 2195/3000 [00:50<00:23, 33.55it/s]

[I 2026-07-05 15:23:25,774] Trial 2187 finished with value: 0.9494270711504674 and parameters: {'weight_class_0': 0.35087156440204587, 'weight_class_1': 3.0355681186120775, 'weight_class_2': 3.128166709302906}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:25,799] Trial 2188 finished with value: 0.9492812729687855 and parameters: {'weight_class_0': 0.3885007411045409, 'weight_class_1': 3.270665677918192, 'weight_class_2': 2.9973278423302685}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:25,849] Trial 2189 finished with value: 0.9489758629444512 and parameters: {'weight_class_0': 0.165032828302473, 'weight_class_1': 3.313903897353524, 'weight_class_2': 3.1812069794649642}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:25,861] Trial 2190 finished with value: 0.9496197625795334 and parameters: {'weight_class_0': 0.2942354813894442, 'weight_class_1': 3.5057316348123675, 'weight_class_2': 3.5615570991603462}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:25,885] Trial 2192 finished with value: 0.9496718861574323 and parameters: {'weight_class_0': 0.2726542994821403, 'weight_class_1': 3.245374488325734, 'weight_class_2': 3.2127621143517873}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:25,887] Trial 2191 finished with value: 0.9496297777597409 and parameters: {'weight_class_0': 0.297804064789608, 'weight_class_1': 3.463394806699886, 'weight_class_2': 3.2160708318804816}. Best is trial 2065 with value: 0.949728674027738.
[I 2026-07-05 15:23:25,901] Trial 2193 finished with value: 0.949738926310991 and parameters: {'weight_class_0': 0.2878947205240242, 'weight_class_1': 3.575237223527607, 'weight_class_2': 3.3174590149664986}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:25,954] Trial 2195 finished with value: 0.9497079839695332 and parameters: {'weight_class_0': 0.27782843087210085, 'weight_class_1': 3.5042740641067542, 'weight_class_2': 3.0946170674922366}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:25,965] Trial 2194 finished with value: 0.9496772517509996 and parameters: {'weight_class_0': 0.27279085429194794, 'weight_class_1': 3.4168128336148866, 'weight_class_2': 3.3239043687686967}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  73%|███████████████████████████████████████████████████████████████████████████████████████████████▍                                  | 2201/3000 [00:51<00:24, 33.19it/s]

[I 2026-07-05 15:23:25,997] Trial 2196 finished with value: 0.9483448348070098 and parameters: {'weight_class_0': 0.17063814167015948, 'weight_class_1': 3.596761052180057, 'weight_class_2': 4.4193818376561085}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:26,009] Trial 2197 finished with value: 0.949175872889208 and parameters: {'weight_class_0': 0.27524103545973805, 'weight_class_1': 3.51866050823389, 'weight_class_2': 4.668254917133732}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:26,079] Trial 2198 finished with value: 0.9493403151022988 and parameters: {'weight_class_0': 0.2894563167054075, 'weight_class_1': 4.8242053024492515, 'weight_class_2': 4.644944271308014}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:26,126] Trial 2199 finished with value: 0.9492921024598013 and parameters: {'weight_class_0': 0.28465419053651875, 'weight_class_1': 4.490619566385067, 'weight_class_2': 4.550504410145956}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:26,132] Trial 2200 finished with value: 0.9494055071138044 and parameters: {'weight_class_0': 0.3036671732194232, 'weight_class_1': 4.734025615839179, 'weight_class_2': 4.613605617887074}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  74%|███████████████████████████████████████████████████████████████████████████████████████████████▊                                  | 2210/3000 [00:51<00:21, 37.34it/s]

[I 2026-07-05 15:23:26,205] Trial 2201 finished with value: 0.9490200486149187 and parameters: {'weight_class_0': 0.2665601147195988, 'weight_class_1': 4.805621004907108, 'weight_class_2': 4.8303963340742}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:26,208] Trial 2202 finished with value: 0.9495605227185965 and parameters: {'weight_class_0': 0.2344658460959487, 'weight_class_1': 4.12653246345749, 'weight_class_2': 2.8131966404699003}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:26,238] Trial 2203 finished with value: 0.9495921076539768 and parameters: {'weight_class_0': 0.2506251024865136, 'weight_class_1': 3.884355784728981, 'weight_class_2': 2.6493829477307766}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:26,265] Trial 2204 finished with value: 0.9486669191615108 and parameters: {'weight_class_0': 0.16473015475781524, 'weight_class_1': 3.71208349667545, 'weight_class_2': 3.5895565497361144}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:26,267] Trial 2205 finished with value: 0.9493620775555723 and parameters: {'weight_class_0': 0.17625801466446286, 'weight_class_1': 2.1945237918972653, 'weight_class_2': 2.7334294080411445}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:26,287] Trial 2206 finished with value: 0.9489248332389962 and parameters: {'weight_class_0': 0.12253014023750478, 'weight_class_1': 3.5416297383117503, 'weight_class_2': 1.9609053565039845}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:26,298] Trial 2207 finished with value: 0.9493711201373372 and parameters: {'weight_class_0': 0.18259951030813662, 'weight_class_1': 3.796646809843707, 'weight_class_2': 2.6854073842559134}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:26,327] Trial 2209 finished with value: 0.9494672544569888 and parameters: {'weight_class_0': 0.18181382312984787, 'weight_class_1': 2.68394637937112, 'weight_class_2': 2.6545328418546683}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:26,340] Trial 2208 finished with value: 0.9495644906006612 and parameters: {'weight_class_0': 0.15795299727325418, 'weight_class_1': 2.8194684118567883, 'weight_class_2': 1.9585127551144281}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  74%|███████████████████████████████████████████████████████████████████████████████████████████████▉                                  | 2215/3000 [00:51<00:24, 31.95it/s]

[I 2026-07-05 15:23:26,408] Trial 2210 finished with value: 0.9494363135754299 and parameters: {'weight_class_0': 0.21206691800193173, 'weight_class_1': 2.5233556880043464, 'weight_class_2': 3.0362688355152714}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:26,463] Trial 2211 finished with value: 0.949565095816046 and parameters: {'weight_class_0': 0.20505652334403648, 'weight_class_1': 3.8892323877020507, 'weight_class_2': 2.2065297978981504}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:26,490] Trial 2212 finished with value: 0.949480790753683 and parameters: {'weight_class_0': 0.2236822537319794, 'weight_class_1': 2.7818484911180366, 'weight_class_2': 3.228641969339343}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:26,527] Trial 2213 finished with value: 0.9492727941737726 and parameters: {'weight_class_0': 0.15815847207643371, 'weight_class_1': 3.0316509700647383, 'weight_class_2': 2.5729794116671325}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:26,576] Trial 2214 finished with value: 0.9495820366501554 and parameters: {'weight_class_0': 0.1793990224561108, 'weight_class_1': 2.7202361600862788, 'weight_class_2': 1.9369389384340179}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:26,577] Trial 2215 finished with value: 0.9492105554877842 and parameters: {'weight_class_0': 0.12728120535104465, 'weight_class_1': 2.4556070923825106, 'weight_class_2': 2.1566513322755214}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  74%|████████████████████████████████████████████████████████████████████████████████████████████████▎                                 | 2224/3000 [00:51<00:21, 35.95it/s]

[I 2026-07-05 15:23:26,632] Trial 2216 finished with value: 0.9495977413040727 and parameters: {'weight_class_0': 0.2019191550352192, 'weight_class_1': 3.0211577899406215, 'weight_class_2': 2.548095357468462}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:26,633] Trial 2217 finished with value: 0.9494186128231522 and parameters: {'weight_class_0': 0.21464389950050347, 'weight_class_1': 2.548060816584531, 'weight_class_2': 3.168610214292114}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:26,664] Trial 2218 finished with value: 0.9496684656473787 and parameters: {'weight_class_0': 0.22188145469898385, 'weight_class_1': 2.7079522019286224, 'weight_class_2': 2.7079476539019915}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:26,671] Trial 2219 finished with value: 0.9485922166583437 and parameters: {'weight_class_0': 0.3202370505780163, 'weight_class_1': 2.1987300742265834, 'weight_class_2': 2.1846881493339967}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:26,676] Trial 2220 finished with value: 0.9495949011059617 and parameters: {'weight_class_0': 0.26556279251424747, 'weight_class_1': 2.962431752271183, 'weight_class_2': 2.780874113140618}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:26,707] Trial 2221 finished with value: 0.9493340851087121 and parameters: {'weight_class_0': 0.20704087808226257, 'weight_class_1': 2.1478074614107556, 'weight_class_2': 2.8754643184421687}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:26,724] Trial 2222 finished with value: 0.9493017869549464 and parameters: {'weight_class_0': 0.2796064158979238, 'weight_class_1': 2.366580210531986, 'weight_class_2': 3.508242291955626}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:26,794] Trial 2223 finished with value: 0.9496702498086479 and parameters: {'weight_class_0': 0.22662850675504145, 'weight_class_1': 2.7154590747870384, 'weight_class_2': 2.657314552423066}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:26,800] Trial 2224 finished with value: 0.9495439456720579 and parameters: {'weight_class_0': 0.24840067815852088, 'weight_class_1': 2.5145520993212354, 'weight_class_2': 2.745206378961542}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  74%|████████████████████████████████████████████████████████████████████████████████████████████████▋                                 | 2232/3000 [00:52<00:22, 33.96it/s]

[I 2026-07-05 15:23:26,873] Trial 2225 finished with value: 0.9490951483001959 and parameters: {'weight_class_0': 0.27914398371227955, 'weight_class_1': 2.1080154795218182, 'weight_class_2': 3.4942495286737634}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:26,910] Trial 2226 finished with value: 0.9495101986578254 and parameters: {'weight_class_0': 0.22911504533260874, 'weight_class_1': 4.820483400704253, 'weight_class_2': 2.885901107624766}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:26,947] Trial 2227 finished with value: 0.9492305613921169 and parameters: {'weight_class_0': 0.2866989724154203, 'weight_class_1': 2.2187947357123172, 'weight_class_2': 2.9412557452072594}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:26,986] Trial 2229 finished with value: 0.9493088153605744 and parameters: {'weight_class_0': 0.23624418146554174, 'weight_class_1': 4.732073022869866, 'weight_class_2': 3.697425020245894}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:26,988] Trial 2228 finished with value: 0.9492807565478619 and parameters: {'weight_class_0': 0.2301514626259532, 'weight_class_1': 4.788982142092857, 'weight_class_2': 3.640394696460747}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:27,026] Trial 2232 finished with value: 0.949194618814667 and parameters: {'weight_class_0': 0.23369460040347337, 'weight_class_1': 3.80314645737135, 'weight_class_2': 3.938101801332483}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:27,032] Trial 2231 finished with value: 0.9492404754572265 and parameters: {'weight_class_0': 0.24671977913413298, 'weight_class_1': 4.510685494109207, 'weight_class_2': 4.168814911049468}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:27,036] Trial 2230 finished with value: 0.948947398116708 and parameters: {'weight_class_0': 0.23153286308073204, 'weight_class_1': 2.119192618989677, 'weight_class_2': 3.6658743435388526}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  75%|█████████████████████████████████████████████████████████████████████████████████████████████████                                 | 2239/3000 [00:52<00:20, 36.93it/s]

[I 2026-07-05 15:23:27,057] Trial 2233 finished with value: 0.9493270854380574 and parameters: {'weight_class_0': 0.25747620366590374, 'weight_class_1': 4.641076792024958, 'weight_class_2': 3.973169271196461}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:27,066] Trial 2234 finished with value: 0.9494734573753715 and parameters: {'weight_class_0': 0.26661920249805, 'weight_class_1': 4.863445027756063, 'weight_class_2': 3.728092676905884}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:27,112] Trial 2235 finished with value: 0.9496647801700143 and parameters: {'weight_class_0': 0.3175095063131217, 'weight_class_1': 4.683064272910718, 'weight_class_2': 3.62579531665908}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:27,113] Trial 2236 finished with value: 0.9496367205218966 and parameters: {'weight_class_0': 0.40450964784249044, 'weight_class_1': 4.666702918112437, 'weight_class_2': 3.5665747460109}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:27,192] Trial 2237 finished with value: 0.9492849362926802 and parameters: {'weight_class_0': 0.2448069601807113, 'weight_class_1': 4.555977660442593, 'weight_class_2': 3.9778242725744155}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:27,216] Trial 2238 finished with value: 0.9496478792356196 and parameters: {'weight_class_0': 0.3949684204605277, 'weight_class_1': 4.698755985943244, 'weight_class_2': 3.861864097396629}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:27,301] Trial 2239 finished with value: 0.9495029067293578 and parameters: {'weight_class_0': 0.31947804727930684, 'weight_class_1': 4.424116097716166, 'weight_class_2': 4.457916586956424}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  75%|█████████████████████████████████████████████████████████████████████████████████████████████████▍                                | 2248/3000 [00:52<00:20, 36.47it/s]

[I 2026-07-05 15:23:27,316] Trial 2240 finished with value: 0.9496827276424061 and parameters: {'weight_class_0': 0.32140132759049556, 'weight_class_1': 4.130493383208205, 'weight_class_2': 3.9787742143506657}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:27,331] Trial 2241 finished with value: 0.9496802673995224 and parameters: {'weight_class_0': 0.32418865486949006, 'weight_class_1': 4.274528487566445, 'weight_class_2': 3.5370305612492925}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:27,333] Trial 2242 finished with value: 0.9494800320946727 and parameters: {'weight_class_0': 0.3279836347821804, 'weight_class_1': 4.119888782615778, 'weight_class_2': 4.682306539333023}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:27,383] Trial 2243 finished with value: 0.9494447559431386 and parameters: {'weight_class_0': 0.3284023913815034, 'weight_class_1': 3.9174893591610034, 'weight_class_2': 4.633557411703474}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:27,420] Trial 2244 finished with value: 0.9495502522166065 and parameters: {'weight_class_0': 0.3224916653484942, 'weight_class_1': 4.821748046314383, 'weight_class_2': 4.423467569436703}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:27,431] Trial 2245 finished with value: 0.9494570187916135 and parameters: {'weight_class_0': 0.3325461275154488, 'weight_class_1': 3.844956064182465, 'weight_class_2': 4.618995444099235}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:27,463] Trial 2246 finished with value: 0.9495423586190364 and parameters: {'weight_class_0': 0.34421250382694296, 'weight_class_1': 4.031707815601609, 'weight_class_2': 4.55407104556196}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:27,477] Trial 2247 finished with value: 0.9494459347577671 and parameters: {'weight_class_0': 0.3227223812669492, 'weight_class_1': 4.23336875377837, 'weight_class_2': 4.68007264954288}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:27,516] Trial 2248 finished with value: 0.9494203967788281 and parameters: {'weight_class_0': 0.33096969735447984, 'weight_class_1': 4.0215501421890405, 'weight_class_2': 4.897941231761639}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  75%|█████████████████████████████████████████████████████████████████████████████████████████████████▋                                | 2254/3000 [00:52<00:23, 31.76it/s]

[I 2026-07-05 15:23:27,538] Trial 2249 finished with value: 0.949437219841332 and parameters: {'weight_class_0': 0.31865383494885335, 'weight_class_1': 3.856754011562233, 'weight_class_2': 4.604396096201016}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:27,560] Trial 2250 finished with value: 0.9493936812111068 and parameters: {'weight_class_0': 0.3178233646691665, 'weight_class_1': 3.444914122196425, 'weight_class_2': 4.383776683099177}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:27,637] Trial 2251 finished with value: 0.8982253178648065 and parameters: {'weight_class_0': 0.4094738476177817, 'weight_class_1': 0.17775627527164073, 'weight_class_2': 4.689415295144509}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:27,676] Trial 2253 finished with value: 0.9493915117718598 and parameters: {'weight_class_0': 0.4173431791675515, 'weight_class_1': 3.555406875631146, 'weight_class_2': 4.323177553361723}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:27,686] Trial 2252 finished with value: 0.9494048993719244 and parameters: {'weight_class_0': 0.40096275438626683, 'weight_class_1': 3.4886602079941373, 'weight_class_2': 4.31451749801062}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:27,709] Trial 2254 finished with value: 0.9494189461350498 and parameters: {'weight_class_0': 0.3674391332902672, 'weight_class_1': 3.3788196194007956, 'weight_class_2': 4.505107996323685}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  75%|██████████████████████████████████████████████████████████████████████████████████████████████████                                | 2262/3000 [00:52<00:20, 35.86it/s]

[I 2026-07-05 15:23:27,750] Trial 2255 finished with value: 0.9493713167832022 and parameters: {'weight_class_0': 0.39921930443246467, 'weight_class_1': 3.6039571312961254, 'weight_class_2': 4.97710810330673}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:27,774] Trial 2256 finished with value: 0.9494301171231272 and parameters: {'weight_class_0': 0.4016938107578193, 'weight_class_1': 3.4815604981028496, 'weight_class_2': 4.658022493920201}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:27,781] Trial 2258 finished with value: 0.9494047731014471 and parameters: {'weight_class_0': 0.39997552977962325, 'weight_class_1': 3.421847848728588, 'weight_class_2': 4.517819599262856}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:27,782] Trial 2257 finished with value: 0.9492668879445 and parameters: {'weight_class_0': 0.417087979541145, 'weight_class_1': 3.2974552543086277, 'weight_class_2': 4.816505070144254}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:27,816] Trial 2259 finished with value: 0.9493272319657867 and parameters: {'weight_class_0': 0.3876957306805741, 'weight_class_1': 3.2660288216681113, 'weight_class_2': 4.788463199703603}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:27,857] Trial 2260 finished with value: 0.9493552391671528 and parameters: {'weight_class_0': 0.40548789278718944, 'weight_class_1': 3.366739667372673, 'weight_class_2': 4.60811759127361}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:27,865] Trial 2261 finished with value: 0.9493420160925337 and parameters: {'weight_class_0': 0.40269294353233176, 'weight_class_1': 3.3314505342645986, 'weight_class_2': 4.66165875805271}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:27,870] Trial 2262 finished with value: 0.899620303218123 and parameters: {'weight_class_0': 0.3893932411144688, 'weight_class_1': 5.163823405321922, 'weight_class_2': 0.23163537729868536}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  76%|██████████████████████████████████████████████████████████████████████████████████████████████████▎                               | 2270/3000 [00:53<00:22, 32.19it/s]

[I 2026-07-05 15:23:27,982] Trial 2263 finished with value: 0.9492629953890764 and parameters: {'weight_class_0': 0.41100936304081354, 'weight_class_1': 5.218393490784704, 'weight_class_2': 2.890454531595141}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:28,020] Trial 2264 finished with value: 0.9493409996851807 and parameters: {'weight_class_0': 0.40868467525932023, 'weight_class_1': 3.357822515275353, 'weight_class_2': 3.2715794222271284}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:28,053] Trial 2265 finished with value: 0.9490443668457641 and parameters: {'weight_class_0': 0.4306608302947272, 'weight_class_1': 4.756363733592906, 'weight_class_2': 2.9327418864886203}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:28,091] Trial 2266 finished with value: 0.9492447800531831 and parameters: {'weight_class_0': 0.37940826929333804, 'weight_class_1': 5.042196238125754, 'weight_class_2': 2.6622825658641944}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:28,095] Trial 2267 finished with value: 0.9492679678071467 and parameters: {'weight_class_0': 0.4093909671376279, 'weight_class_1': 5.134729102988812, 'weight_class_2': 2.8956201168004116}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:28,119] Trial 2268 finished with value: 0.94953706264178 and parameters: {'weight_class_0': 0.4065107845736835, 'weight_class_1': 5.101683854489793, 'weight_class_2': 3.1907882268265095}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:28,124] Trial 2269 finished with value: 0.9491029810772101 and parameters: {'weight_class_0': 0.41450483842915126, 'weight_class_1': 4.834984427375083, 'weight_class_2': 2.824937814799675}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:28,138] Trial 2270 finished with value: 0.949203728954353 and parameters: {'weight_class_0': 0.4262538541763153, 'weight_class_1': 4.648147777724557, 'weight_class_2': 3.0514350166966357}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  76%|██████████████████████████████████████████████████████████████████████████████████████████████████▋                               | 2277/3000 [00:53<00:19, 36.91it/s]

[I 2026-07-05 15:23:28,193] Trial 2271 finished with value: 0.9492883373702509 and parameters: {'weight_class_0': 0.4267765961584812, 'weight_class_1': 4.895523379717128, 'weight_class_2': 3.1426531605124364}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:28,195] Trial 2272 finished with value: 0.9492753396508723 and parameters: {'weight_class_0': 0.4183472570654154, 'weight_class_1': 5.150637741069342, 'weight_class_2': 2.9776967505288763}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:28,211] Trial 2274 finished with value: 0.9491139071057483 and parameters: {'weight_class_0': 0.43097323091133855, 'weight_class_1': 5.190205378569589, 'weight_class_2': 2.9033851404711366}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:28,232] Trial 2273 finished with value: 0.92104795811751 and parameters: {'weight_class_0': 0.2809907048421857, 'weight_class_1': 0.31473085285685926, 'weight_class_2': 2.940785637397548}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:28,304] Trial 2275 finished with value: 0.9495477165945494 and parameters: {'weight_class_0': 0.4229683317677529, 'weight_class_1': 5.0207840884237145, 'weight_class_2': 3.38768118307059}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:28,324] Trial 2276 finished with value: 0.8830251681947879 and parameters: {'weight_class_0': 0.43649839672468915, 'weight_class_1': 0.09249714552733386, 'weight_class_2': 2.1241943925265128}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:28,364] Trial 2277 finished with value: 0.9495343003903628 and parameters: {'weight_class_0': 0.2662677881384744, 'weight_class_1': 5.239422593985611, 'weight_class_2': 3.4763030002963764}. Best is trial 2193 with value: 0.949738926310991.

[I 2026-07-05 15:23:28,408] Trial 2278 finished with value: 0.9495073310192016 and parameters: {'weight_class_0': 0.27859383196676435, 'weight_class_1': 5.122943577428616, 'weight_class_2': 2.2110947437127604}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:28,493] Trial 2280 finished with value: 0.9494956698113698 and parameters: {'weight_class_0': 0.2645941650259692, 'weight_class_1': 5.253671890644439, 'weight_class_2': 2.0979471885876526}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:28,495] Trial 2279 finished with value: 0.9495914724025649 and parameters: {'weight_class_0': 0.2878208700498921, 'weight_class_1': 4.9798885679796365, 'weight_class_2': 3.368575622399377}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:28,504] Trial 2281 finished with value: 0.9495806678690487 and parameters: {'weight_class_0': 0.2783973178920568, 'weight_class_1': 5.3005273405430025, 'weight_class_2': 2.3162767873819314}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:28,564] Trial 2283 finished with value: 0.8725417569118625 and parameters: {'weight_class_0': 0.2772917368682526, 'weight_class_1': 0.017302315743273452, 'weight_class_2': 2.2161376269752733}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:28,569] Trial 2282 finished with value: 0.9495421972494321 and parameters: {'weight_class_0': 0.27798379832739756, 'weight_class_1': 5.308021396734803, 'weight_class_2': 3.7760471261341224}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:28,571] Trial 2284 finished with value: 0.9486780202215601 and parameters: {'weight_class_0': 0.18881736316552544, 'weight_class_1': 5.369406196368665, 'weight_class_2': 3.462048479371206}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  76%|███████████████████████████████████████████████████████████████████████████████████████████████████▎                              | 2291/3000 [00:53<00:19, 37.18it/s]

[I 2026-07-05 15:23:28,577] Trial 2285 finished with value: 0.9493709588367519 and parameters: {'weight_class_0': 0.2893603604364842, 'weight_class_1': 5.237355804527052, 'weight_class_2': 2.1789235885691087}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:28,597] Trial 2286 finished with value: 0.9496376529045211 and parameters: {'weight_class_0': 0.3187979837433717, 'weight_class_1': 5.203147246519407, 'weight_class_2': 3.6484726151438194}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:28,638] Trial 2287 finished with value: 0.9495607881304058 and parameters: {'weight_class_0': 0.2848841141482049, 'weight_class_1': 5.124535293375975, 'weight_class_2': 3.544597524098985}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:28,644] Trial 2288 finished with value: 0.9496101833471212 and parameters: {'weight_class_0': 0.2791372413498377, 'weight_class_1': 5.308549872524082, 'weight_class_2': 2.3027156144846357}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:28,654] Trial 2289 finished with value: 0.9492819794334468 and parameters: {'weight_class_0': 0.30465315562860973, 'weight_class_1': 5.187914015173286, 'weight_class_2': 5.026911019268666}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:28,656] Trial 2290 finished with value: 0.9495523167753822 and parameters: {'weight_class_0': 0.29301905545968293, 'weight_class_1': 5.542161605198388, 'weight_class_2': 3.9322552862521007}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:28,798] Trial 2291 finished with value: 0.9494195174235621 and parameters: {'weight_class_0': 0.3327927184989879, 'weight_class_1': 5.267679428033617, 'weight_class_2': 5.054288929662552}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  77%|███████████████████████████████████████████████████████████████████████████████████████████████████▋                              | 2301/3000 [00:53<00:19, 36.51it/s]

[I 2026-07-05 15:23:28,857] Trial 2293 finished with value: 0.9493982428155497 and parameters: {'weight_class_0': 0.3486309127771238, 'weight_class_1': 4.069595054060066, 'weight_class_2': 5.131002754058264}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:28,876] Trial 2292 finished with value: 0.7067354545759194 and parameters: {'weight_class_0': 0.3276334789953113, 'weight_class_1': 0.002197839261933027, 'weight_class_2': 3.7967896180343277}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:28,891] Trial 2295 finished with value: 0.9494100828226615 and parameters: {'weight_class_0': 0.3427509037033486, 'weight_class_1': 4.113576455426184, 'weight_class_2': 5.105055130820419}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:28,895] Trial 2294 finished with value: 0.9494087737641935 and parameters: {'weight_class_0': 0.3378035240636591, 'weight_class_1': 4.052068574093836, 'weight_class_2': 4.994065239923233}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:28,945] Trial 2296 finished with value: 0.9494484801609951 and parameters: {'weight_class_0': 0.3597441521713484, 'weight_class_1': 3.974908969454192, 'weight_class_2': 4.914316467383752}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:28,960] Trial 2297 finished with value: 0.9493581580928397 and parameters: {'weight_class_0': 0.3337426176071669, 'weight_class_1': 4.060447002390815, 'weight_class_2': 5.133972117111388}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:28,974] Trial 2299 finished with value: 0.9493556296158795 and parameters: {'weight_class_0': 0.35726275706539784, 'weight_class_1': 3.969497595337508, 'weight_class_2': 5.0565178643539905}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:28,977] Trial 2298 finished with value: 0.9493400121425318 and parameters: {'weight_class_0': 0.33360055943299216, 'weight_class_1': 4.2424425960529435, 'weight_class_2': 5.2025048111064915}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:29,015] Trial 2301 finished with value: 0.9493438813510201 and parameters: {'weight_class_0': 0.34100032419230725, 'weight_class_1': 3.8527997660982454, 'weight_class_2': 5.081332363349708}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:29,025] Trial 2300 finished with value: 0.9486586230980537 and parameters: {'weight_class_0': 0.458245876137903, 'weight_class_1': 2.799106349530501, 'weight_class_2': 5.108017205218787}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  77%|███████████████████████████████████████████████████████████████████████████████████████████████████▉                              | 2305/3000 [00:54<00:23, 29.46it/s]

[I 2026-07-05 15:23:29,080] Trial 2302 finished with value: 0.9493813339218645 and parameters: {'weight_class_0': 0.3486110597697919, 'weight_class_1': 3.9860741412612746, 'weight_class_2': 5.128002690932076}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:29,128] Trial 2303 finished with value: 0.8609234155674891 and parameters: {'weight_class_0': 6.757920140760911, 'weight_class_1': 4.1457123752258624, 'weight_class_2': 5.381750160105461}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:29,226] Trial 2304 finished with value: 0.9486362276756405 and parameters: {'weight_class_0': 0.45309891873836555, 'weight_class_1': 2.748120127472355, 'weight_class_2': 5.141685567640852}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:29,235] Trial 2305 finished with value: 0.9488469409829562 and parameters: {'weight_class_0': 0.19951031636724856, 'weight_class_1': 2.78228473241892, 'weight_class_2': 1.1923478719458183}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  77%|████████████████████████████████████████████████████████████████████████████████████████████████████▎                             | 2316/3000 [00:54<00:18, 37.94it/s]

[I 2026-07-05 15:23:29,276] Trial 2306 finished with value: 0.9494750391292494 and parameters: {'weight_class_0': 0.46145911369854264, 'weight_class_1': 4.049404275196795, 'weight_class_2': 5.118508617075032}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:29,277] Trial 2307 finished with value: 0.9487236467753196 and parameters: {'weight_class_0': 0.47854966173579255, 'weight_class_1': 3.0035219332103438, 'weight_class_2': 5.1794947295796225}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:29,300] Trial 2309 finished with value: 0.9488126208514874 and parameters: {'weight_class_0': 0.46442896270113404, 'weight_class_1': 2.8635947938692055, 'weight_class_2': 4.074287866474557}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:29,302] Trial 2308 finished with value: 0.9488890221779802 and parameters: {'weight_class_0': 0.20193080017414083, 'weight_class_1': 2.6779045970140474, 'weight_class_2': 3.898176138253809}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:29,342] Trial 2310 finished with value: 0.9484939380479807 and parameters: {'weight_class_0': 0.4564096534350916, 'weight_class_1': 2.5661703468621884, 'weight_class_2': 4.002513449565062}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:29,345] Trial 2311 finished with value: 0.9488301922648157 and parameters: {'weight_class_0': 0.45091843152918243, 'weight_class_1': 2.90953943306251, 'weight_class_2': 4.935046249834349}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:29,348] Trial 2313 finished with value: 0.9486791429021939 and parameters: {'weight_class_0': 0.21174782969779699, 'weight_class_1': 2.338433220084479, 'weight_class_2': 4.043046097888445}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:29,361] Trial 2312 finished with value: 0.9489057642553028 and parameters: {'weight_class_0': 0.19020321498870602, 'weight_class_1': 2.4362128571513026, 'weight_class_2': 1.1517136197423659}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:29,378] Trial 2314 finished with value: 0.9459431986302764 and parameters: {'weight_class_0': 0.4547143065173466, 'weight_class_1': 1.6586504814761611, 'weight_class_2': 4.652545290700644}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:29,395] Trial 2315 finished with value: 0.9488945034047035 and parameters: {'weight_class_0': 0.20216977324498764, 'weight_class_1': 3.0355950221995953, 'weight_class_2': 3.942953611540855}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  77%|████████████████████████████████████████████████████████████████████████████████████████████████████▋                             | 2324/3000 [00:54<00:20, 32.24it/s]

[I 2026-07-05 15:23:29,556] Trial 2317 finished with value: 0.8731118112074707 and parameters: {'weight_class_0': 0.24005833176500646, 'weight_class_1': 0.022845237034097757, 'weight_class_2': 4.341905967724297}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:29,568] Trial 2316 finished with value: 0.9496548163130432 and parameters: {'weight_class_0': 0.44718150034732784, 'weight_class_1': 5.515171452801374, 'weight_class_2': 4.341018609069871}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:29,617] Trial 2318 finished with value: 0.9465560818709746 and parameters: {'weight_class_0': 0.4372777285493913, 'weight_class_1': 1.7042156780940776, 'weight_class_2': 4.004392058276652}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:29,646] Trial 2320 finished with value: 0.9496242453661696 and parameters: {'weight_class_0': 0.429928170883903, 'weight_class_1': 5.141069558853581, 'weight_class_2': 4.089104495730878}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:29,657] Trial 2319 finished with value: 0.9489590508609709 and parameters: {'weight_class_0': 0.23263792611221204, 'weight_class_1': 5.602517656946005, 'weight_class_2': 3.995846372673704}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:29,679] Trial 2321 finished with value: 0.9496637845517807 and parameters: {'weight_class_0': 0.4509299040063317, 'weight_class_1': 5.822473958223756, 'weight_class_2': 3.952476648641954}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:29,693] Trial 2322 finished with value: 0.9490447967757706 and parameters: {'weight_class_0': 0.23799816254359404, 'weight_class_1': 5.617809563854564, 'weight_class_2': 3.9847922510154987}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:29,730] Trial 2324 finished with value: 0.9492074782406851 and parameters: {'weight_class_0': 0.25248322655087285, 'weight_class_1': 5.493998548570244, 'weight_class_2': 4.111926270457715}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:29,742] Trial 2323 finished with value: 0.9496608394118929 and parameters: {'weight_class_0': 0.4332687710904411, 'weight_class_1': 5.6198235888662005, 'weight_class_2': 4.09318731657275}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  78%|████████████████████████████████████████████████████████████████████████████████████████████████████▉                             | 2330/3000 [00:54<00:19, 35.13it/s]

[I 2026-07-05 15:23:29,747] Trial 2325 finished with value: 0.9493201617503241 and parameters: {'weight_class_0': 0.24807305468058966, 'weight_class_1': 5.535143038364135, 'weight_class_2': 3.639673200904608}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:29,766] Trial 2326 finished with value: 0.9489899448858933 and parameters: {'weight_class_0': 0.23793592131009492, 'weight_class_1': 5.62636378926919, 'weight_class_2': 4.039087397427797}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:29,794] Trial 2327 finished with value: 0.949196420475097 and parameters: {'weight_class_0': 0.2499299735638692, 'weight_class_1': 5.619363855366671, 'weight_class_2': 3.966882393154609}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:29,894] Trial 2328 finished with value: 0.9488956204682882 and parameters: {'weight_class_0': 0.41557719734452536, 'weight_class_1': 5.560611926129853, 'weight_class_2': 2.528293875215173}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:29,896] Trial 2329 finished with value: 0.8726393824112288 and parameters: {'weight_class_0': 0.23437174204142014, 'weight_class_1': 5.617839681561652, 'weight_class_2': 0.029053946903772117}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:29,978] Trial 2331 finished with value: 0.9493910673725958 and parameters: {'weight_class_0': 0.46201261947716016, 'weight_class_1': 5.607474496875755, 'weight_class_2': 3.5145119092153947}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  78%|█████████████████████████████████████████████████████████████████████████████████████████████████████▎                            | 2339/3000 [00:55<00:18, 35.06it/s]

[I 2026-07-05 15:23:29,980] Trial 2330 finished with value: 0.9495661706628069 and parameters: {'weight_class_0': 0.3755658862776934, 'weight_class_1': 5.596347795024011, 'weight_class_2': 3.4442212819837144}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:30,047] Trial 2332 finished with value: 0.9486937087098118 and parameters: {'weight_class_0': 0.14690279056146213, 'weight_class_1': 4.511433292121521, 'weight_class_2': 2.5653513441147786}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:30,049] Trial 2333 finished with value: 0.8492265434198888 and parameters: {'weight_class_0': 0.14752131696450366, 'weight_class_1': 4.453106467742202, 'weight_class_2': 0.015407409035715433}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:30,058] Trial 2334 finished with value: 0.9495190630473852 and parameters: {'weight_class_0': 0.39867475658263624, 'weight_class_1': 4.467328420256953, 'weight_class_2': 5.300099718315079}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:30,065] Trial 2335 finished with value: 0.9494556911775588 and parameters: {'weight_class_0': 0.3656311450268816, 'weight_class_1': 4.552157475213158, 'weight_class_2': 5.430869995471483}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:30,124] Trial 2336 finished with value: 0.8495367825376192 and parameters: {'weight_class_0': 0.3975746908948755, 'weight_class_1': 4.25295404674688, 'weight_class_2': 0.015491022627254037}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:30,137] Trial 2338 finished with value: 0.9494019391691406 and parameters: {'weight_class_0': 0.3734676750382352, 'weight_class_1': 4.378550969358999, 'weight_class_2': 5.528289704472304}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:30,138] Trial 2339 finished with value: 0.9481837674771033 and parameters: {'weight_class_0': 0.5000769199459336, 'weight_class_1': 4.439729923275933, 'weight_class_2': 2.571671462651761}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:30,140] Trial 2337 finished with value: 0.9493859819742685 and parameters: {'weight_class_0': 0.3870476421386163, 'weight_class_1': 4.312701068336422, 'weight_class_2': 5.437316206622848}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  78%|█████████████████████████████████████████████████████████████████████████████████████████████████████▌                            | 2345/3000 [00:55<00:18, 34.50it/s]

[I 2026-07-05 15:23:30,206] Trial 2341 finished with value: 0.8853874955303761 and parameters: {'weight_class_0': 0.5002257369176396, 'weight_class_1': 4.383199888573418, 'weight_class_2': 0.044193925251640315}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:30,227] Trial 2340 finished with value: 0.9286124255651099 and parameters: {'weight_class_0': 0.36174829067288583, 'weight_class_1': 4.88017290116264, 'weight_class_2': 0.5950670774961915}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:30,283] Trial 2342 finished with value: 0.9494549102723918 and parameters: {'weight_class_0': 0.49842260937193666, 'weight_class_1': 4.450037792521381, 'weight_class_2': 5.685687456135107}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:30,313] Trial 2343 finished with value: 0.949449474771542 and parameters: {'weight_class_0': 0.3712586861632634, 'weight_class_1': 4.530501088618361, 'weight_class_2': 5.433665843566785}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:30,385] Trial 2344 finished with value: 0.9490550472269729 and parameters: {'weight_class_0': 0.358182313920073, 'weight_class_1': 3.504236849668313, 'weight_class_2': 5.508961425019332}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:30,417] Trial 2345 finished with value: 0.9435486588300545 and parameters: {'weight_class_0': 0.5100245279205466, 'weight_class_1': 3.52377807786421, 'weight_class_2': 1.5886849527449658}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  78%|██████████████████████████████████████████████████████████████████████████████████████████████████████                            | 2355/3000 [00:55<00:18, 34.00it/s]

[I 2026-07-05 15:23:30,451] Trial 2346 finished with value: 0.683847652004554 and parameters: {'weight_class_0': 0.5127711405414792, 'weight_class_1': 3.741440966986213, 'weight_class_2': 0.0015831345759149402}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:30,475] Trial 2347 finished with value: 0.9494191543328315 and parameters: {'weight_class_0': 0.5058823410854171, 'weight_class_1': 4.3358052963594895, 'weight_class_2': 5.5201187287756985}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:30,488] Trial 2348 finished with value: 0.8726157146162105 and parameters: {'weight_class_0': 0.4899066836771097, 'weight_class_1': 0.03483826192729831, 'weight_class_2': 5.648783049883583}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:30,495] Trial 2349 finished with value: 0.9491923433955062 and parameters: {'weight_class_0': 0.4962430125229003, 'weight_class_1': 3.6862095760916866, 'weight_class_2': 5.541255666694701}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:30,531] Trial 2350 finished with value: 0.8855352334346572 and parameters: {'weight_class_0': 0.5117325389316791, 'weight_class_1': 3.4529515923104293, 'weight_class_2': 0.041781624412731165}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:30,542] Trial 2351 finished with value: 0.9489988357647322 and parameters: {'weight_class_0': 0.4961065938613928, 'weight_class_1': 3.373979390741157, 'weight_class_2': 5.47561832067095}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:30,569] Trial 2352 finished with value: 0.9489757947002043 and parameters: {'weight_class_0': 0.5024259748609674, 'weight_class_1': 3.3880748883541387, 'weight_class_2': 5.482241954115355}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:30,585] Trial 2353 finished with value: 0.9447152890621228 and parameters: {'weight_class_0': 0.4896021374270132, 'weight_class_1': 3.4071948094344235, 'weight_class_2': 1.6717611190317576}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:30,643] Trial 2354 finished with value: 0.6920078986046948 and parameters: {'weight_class_0': 0.30608577151113425, 'weight_class_1': 3.3461015057281682, 'weight_class_2': 0.0013544352038890532}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:30,652] Trial 2355 finished with value: 0.9491530386064498 and parameters: {'weight_class_0': 0.48426220906043443, 'weight_class_1': 3.5707297638116904, 'weight_class_2': 5.257260512809157}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  79%|██████████████████████████████████████████████████████████████████████████████████████████████████████▎                           | 2361/3000 [00:55<00:20, 30.80it/s]

[I 2026-07-05 15:23:30,703] Trial 2356 finished with value: 0.9491614851136139 and parameters: {'weight_class_0': 0.46935320448553375, 'weight_class_1': 5.818404912950934, 'weight_class_2': 3.189553002352897}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:30,782] Trial 2357 finished with value: 0.9496884074165304 and parameters: {'weight_class_0': 0.30125479982933756, 'weight_class_1': 3.570842461845892, 'weight_class_2': 3.3329711737500487}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:30,828] Trial 2358 finished with value: 0.9490191107985676 and parameters: {'weight_class_0': 0.48562573536725406, 'weight_class_1': 5.798734837916844, 'weight_class_2': 3.154682382438896}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:30,840] Trial 2360 finished with value: 0.9495402126566445 and parameters: {'weight_class_0': 0.27783842623569466, 'weight_class_1': 5.886588047837289, 'weight_class_2': 2.9496420066102544}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:30,861] Trial 2359 finished with value: 0.9496087364841435 and parameters: {'weight_class_0': 0.2931653697974168, 'weight_class_1': 5.735704445329776, 'weight_class_2': 3.3784311272817824}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:30,869] Trial 2362 finished with value: 0.9494939922911468 and parameters: {'weight_class_0': 0.27967033492645804, 'weight_class_1': 5.904489354447277, 'weight_class_2': 3.400166803499624}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  79%|██████████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 2369/3000 [00:56<00:18, 33.41it/s]

[I 2026-07-05 15:23:30,897] Trial 2361 finished with value: 0.9495509373854132 and parameters: {'weight_class_0': 0.29492808663524633, 'weight_class_1': 6.15756180879666, 'weight_class_2': 3.438833504358956}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:30,932] Trial 2364 finished with value: 0.9495572922952364 and parameters: {'weight_class_0': 0.27959442288463493, 'weight_class_1': 5.890147089534539, 'weight_class_2': 3.077866156300219}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:30,936] Trial 2365 finished with value: 0.9495394080174283 and parameters: {'weight_class_0': 0.28956652450628845, 'weight_class_1': 5.862604291717085, 'weight_class_2': 3.443250640681952}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:30,951] Trial 2363 finished with value: 0.9495769568922078 and parameters: {'weight_class_0': 0.30814821979932905, 'weight_class_1': 5.988755080866458, 'weight_class_2': 3.225995713092337}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:30,999] Trial 2366 finished with value: 0.9495657699314922 and parameters: {'weight_class_0': 0.2865142466923473, 'weight_class_1': 5.739343423314209, 'weight_class_2': 3.2564593288038037}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:31,007] Trial 2368 finished with value: 0.9495738396169994 and parameters: {'weight_class_0': 0.30508842079054477, 'weight_class_1': 5.863433051254898, 'weight_class_2': 3.1631348164502184}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:31,024] Trial 2367 finished with value: 0.9495713015847413 and parameters: {'weight_class_0': 0.28335654218606765, 'weight_class_1': 5.747667708874916, 'weight_class_2': 3.1647914382571716}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:31,098] Trial 2369 finished with value: 0.9493952663853292 and parameters: {'weight_class_0': 0.31454932923003165, 'weight_class_1': 5.341032478486602, 'weight_class_2': 4.563105331690882}. Best is trial 2193 with value: 0.949738926310991.

[I 2026-07-05 15:23:31,138] Trial 2371 finished with value: 0.9495409445285611 and parameters: {'weight_class_0': 0.3391742380065373, 'weight_class_1': 6.024376185741457, 'weight_class_2': 4.615103422830107}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:31,142] Trial 2370 finished with value: 0.9493053863231897 and parameters: {'weight_class_0': 0.31716477198762777, 'weight_class_1': 5.932831592735487, 'weight_class_2': 4.98134956419878}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:31,261] Trial 2373 finished with value: 0.9495264576227914 and parameters: {'weight_class_0': 0.3307939289254751, 'weight_class_1': 5.813650219064167, 'weight_class_2': 4.518043263290488}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:31,263] Trial 2374 finished with value: 0.9496847474545359 and parameters: {'weight_class_0': 0.4246486183488679, 'weight_class_1': 4.89637118562627, 'weight_class_2': 4.713106601409456}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:31,292] Trial 2375 finished with value: 0.9495566933354859 and parameters: {'weight_class_0': 0.39578350611219254, 'weight_class_1': 4.437113821997137, 'weight_class_2': 4.724431340020878}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:31,293] Trial 2372 finished with value: 0.9497071305408237 and parameters: {'weight_class_0': 0.4023282701673526, 'weight_class_1': 4.948099413648423, 'weight_class_2': 4.528824476511829}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  79%|███████████████████████████████████████████████████████████████████████████████████████████████████████▎                          | 2383/3000 [00:56<00:17, 34.86it/s]

[I 2026-07-05 15:23:31,316] Trial 2376 finished with value: 0.9497058318112872 and parameters: {'weight_class_0': 0.40446062236786284, 'weight_class_1': 5.298362689020821, 'weight_class_2': 4.592629389123804}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:31,344] Trial 2377 finished with value: 0.9496692984182249 and parameters: {'weight_class_0': 0.39783348060589346, 'weight_class_1': 4.61360854684699, 'weight_class_2': 4.5976590377215025}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:31,361] Trial 2379 finished with value: 0.9496951245768267 and parameters: {'weight_class_0': 0.39201700702898884, 'weight_class_1': 4.7443854163486785, 'weight_class_2': 4.475589900636899}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:31,364] Trial 2378 finished with value: 0.9496910541095946 and parameters: {'weight_class_0': 0.39718958233532203, 'weight_class_1': 4.799194028670434, 'weight_class_2': 4.500604595681785}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:31,382] Trial 2380 finished with value: 0.9495861593739733 and parameters: {'weight_class_0': 0.3978095985964345, 'weight_class_1': 4.243953165953994, 'weight_class_2': 4.615159310276645}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:31,426] Trial 2381 finished with value: 0.9497089613198245 and parameters: {'weight_class_0': 0.37930998251372455, 'weight_class_1': 4.782274953891131, 'weight_class_2': 4.304361648892868}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:31,446] Trial 2383 finished with value: 0.9496017845933041 and parameters: {'weight_class_0': 0.4015070793023742, 'weight_class_1': 4.471202893001058, 'weight_class_2': 4.521097908096557}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:31,455] Trial 2382 finished with value: 0.9495352840373137 and parameters: {'weight_class_0': 0.40894680429525354, 'weight_class_1': 4.367949816244705, 'weight_class_2': 4.37800692251374}. Best is trial 2193 with value: 0.949738926310991.

[I 2026-07-05 15:23:31,600] Trial 2384 finished with value: 0.9494565196333412 and parameters: {'weight_class_0': 0.41189387038504593, 'weight_class_1': 4.724164565616818, 'weight_class_2': 5.724122223302619}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:31,621] Trial 2385 finished with value: 0.9494966068695144 and parameters: {'weight_class_0': 0.4186164199184086, 'weight_class_1': 4.87882696325798, 'weight_class_2': 5.7531293176363185}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:31,639] Trial 2386 finished with value: 0.9496294714356782 and parameters: {'weight_class_0': 0.41656815672189296, 'weight_class_1': 4.914118988695088, 'weight_class_2': 4.429543077358754}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:31,674] Trial 2388 finished with value: 0.949478905179035 and parameters: {'weight_class_0': 0.42003972903967923, 'weight_class_1': 4.012776215438837, 'weight_class_2': 4.457037189804731}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:31,686] Trial 2387 finished with value: 0.949498923635257 and parameters: {'weight_class_0': 0.4084929206884219, 'weight_class_1': 4.06405062613804, 'weight_class_2': 4.338395365489961}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:31,732] Trial 2389 finished with value: 0.9494226794685581 and parameters: {'weight_class_0': 0.4119277218106897, 'weight_class_1': 3.7703048352237194, 'weight_class_2': 4.1596923531761165}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:31,735] Trial 2390 finished with value: 0.9494853435093727 and parameters: {'weight_class_0': 0.4214803182994651, 'weight_class_1': 3.7813899608380144, 'weight_class_2': 4.140997995486638}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:31,744] Trial 2392 finished with value: 0.9495718330613127 and parameters: {'weight_class_0': 0.3515094621623514, 'weight_class_1': 3.817775339909419, 'weight_class_2': 3.6639558918695}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:31,771] Trial 2391 finished with value: 0.9494220166279589 and parameters: {'weight_class_0': 0.353476513796243, 'weight_class_1': 3.018516077479932, 'weight_class_2': 3.7835543077984513}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████████▉                          | 2399/3000 [00:56<00:18, 33.26it/s]

[I 2026-07-05 15:23:31,790] Trial 2393 finished with value: 0.9432912250381524 and parameters: {'weight_class_0': 0.05449638033678635, 'weight_class_1': 3.101581117638711, 'weight_class_2': 3.86758621385055}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:31,793] Trial 2394 finished with value: 0.9493397942813379 and parameters: {'weight_class_0': 0.3539684896525898, 'weight_class_1': 2.9257733825106667, 'weight_class_2': 3.8272708929734964}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:31,812] Trial 2395 finished with value: 0.9493870341969979 and parameters: {'weight_class_0': 0.36670918307000205, 'weight_class_1': 3.0873131155866402, 'weight_class_2': 3.745364562880315}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:31,957] Trial 2396 finished with value: 0.9494543049667765 and parameters: {'weight_class_0': 0.3490198583355667, 'weight_class_1': 3.1615485805003627, 'weight_class_2': 3.6704090388426316}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:31,979] Trial 2397 finished with value: 0.9495529409937133 and parameters: {'weight_class_0': 0.36806487574455315, 'weight_class_1': 3.7766688388320264, 'weight_class_2': 3.579289547357897}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:31,984] Trial 2398 finished with value: 0.9494141230637007 and parameters: {'weight_class_0': 0.35024487342745636, 'weight_class_1': 3.0164087513292066, 'weight_class_2': 3.702013395631996}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  80%|████████████████████████████████████████████████████████████████████████████████████████████████████████▎                         | 2407/3000 [00:57<00:17, 33.84it/s]

[I 2026-07-05 15:23:32,037] Trial 2400 finished with value: 0.9496564611148214 and parameters: {'weight_class_0': 0.33635842668968635, 'weight_class_1': 3.9211290662063902, 'weight_class_2': 3.8061449519952846}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:32,052] Trial 2399 finished with value: 0.9494517544338251 and parameters: {'weight_class_0': 0.34628444783877815, 'weight_class_1': 3.3317538114505716, 'weight_class_2': 3.680238638372367}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:32,058] Trial 2401 finished with value: 0.9493122181320967 and parameters: {'weight_class_0': 0.3529348231929531, 'weight_class_1': 2.9807672707758663, 'weight_class_2': 2.7347224883782317}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:32,073] Trial 2402 finished with value: 0.949109807954739 and parameters: {'weight_class_0': 0.3490830538932882, 'weight_class_1': 3.032258277767166, 'weight_class_2': 2.520671763448}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:32,123] Trial 2403 finished with value: 0.9350077219387702 and parameters: {'weight_class_0': 0.3382845222474119, 'weight_class_1': 3.0493661846436577, 'weight_class_2': 0.6931991218924659}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:32,129] Trial 2405 finished with value: 0.9465567335887282 and parameters: {'weight_class_0': 0.244428991406925, 'weight_class_1': 0.9554459591700409, 'weight_class_2': 2.6262309759170415}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:32,135] Trial 2404 finished with value: 0.9495517653300736 and parameters: {'weight_class_0': 0.24103690169732075, 'weight_class_1': 2.4631806645520227, 'weight_class_2': 2.7429389424775144}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:32,188] Trial 2407 finished with value: 0.9496596282741129 and parameters: {'weight_class_0': 0.24027761261287958, 'weight_class_1': 3.5346104884452374, 'weight_class_2': 2.6358826512384073}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:32,243] Trial 2406 finished with value: 0.9494885606096665 and parameters: {'weight_class_0': 0.2551567870550054, 'weight_class_1': 2.393210369760129, 'weight_class_2': 2.8661869952180563}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  80%|████████████████████████████████████████████████████████████████████████████████████████████████████████▋                         | 2415/3000 [00:57<00:18, 31.15it/s]

[I 2026-07-05 15:23:32,299] Trial 2408 finished with value: 0.9494699459816118 and parameters: {'weight_class_0': 0.25435104546470716, 'weight_class_1': 2.309249631993178, 'weight_class_2': 2.830716035803792}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:32,350] Trial 2409 finished with value: 0.9100295669067425 and parameters: {'weight_class_0': 0.32945081530476006, 'weight_class_1': 0.24607304603695263, 'weight_class_2': 2.57902246928575}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:32,357] Trial 2410 finished with value: 0.9494859603287403 and parameters: {'weight_class_0': 0.2402652070462806, 'weight_class_1': 2.3767634354424025, 'weight_class_2': 2.8667934946662306}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:32,410] Trial 2411 finished with value: 0.9496033261772417 and parameters: {'weight_class_0': 0.25022049029110327, 'weight_class_1': 4.04839201030501, 'weight_class_2': 2.646474817296231}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:32,418] Trial 2413 finished with value: 0.9496154863092933 and parameters: {'weight_class_0': 0.25599846024472644, 'weight_class_1': 4.856626621322246, 'weight_class_2': 2.491873353549635}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:32,429] Trial 2412 finished with value: 0.9495511334526627 and parameters: {'weight_class_0': 0.25457857110667076, 'weight_class_1': 4.8655832904466045, 'weight_class_2': 2.677721007262855}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:32,464] Trial 2414 finished with value: 0.9481276410091747 and parameters: {'weight_class_0': 0.17975538743867298, 'weight_class_1': 4.902559532395445, 'weight_class_2': 4.804744744097064}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:32,479] Trial 2416 finished with value: 0.9484970264439889 and parameters: {'weight_class_0': 0.2505072796311839, 'weight_class_1': 2.3424213704854853, 'weight_class_2': 4.698896511612452}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  81%|████████████████████████████████████████████████████████████████████████████████████████████████████████▉                         | 2422/3000 [00:57<00:18, 31.61it/s]

[I 2026-07-05 15:23:32,510] Trial 2417 finished with value: 0.9495015174911288 and parameters: {'weight_class_0': 0.45829104993306813, 'weight_class_1': 4.66114933960532, 'weight_class_2': 4.893717780619112}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:32,523] Trial 2415 finished with value: 0.7364822551378521 and parameters: {'weight_class_0': 0.20308912904285914, 'weight_class_1': 4.2018477372606835, 'weight_class_2': 0.0037097713253622603}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:32,545] Trial 2418 finished with value: 0.8442881548554442 and parameters: {'weight_class_0': 0.1768367671405248, 'weight_class_1': 0.010044752095042618, 'weight_class_2': 4.908736519498623}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:32,600] Trial 2419 finished with value: 0.9494370891732741 and parameters: {'weight_class_0': 0.46455859996405213, 'weight_class_1': 4.518394557763321, 'weight_class_2': 4.6364646821855535}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:32,612] Trial 2420 finished with value: 0.9495060872194299 and parameters: {'weight_class_0': 0.46989815483434527, 'weight_class_1': 4.685812296913529, 'weight_class_2': 4.979493353141806}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:32,710] Trial 2421 finished with value: 0.9494858916960434 and parameters: {'weight_class_0': 0.44918515683458204, 'weight_class_1': 4.729693711243247, 'weight_class_2': 4.771859953973929}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:32,729] Trial 2422 finished with value: 0.7220317680482556 and parameters: {'weight_class_0': 0.19890244688098244, 'weight_class_1': 4.597511065653331, 'weight_class_2': 0.0032879856214270736}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▍                        | 2432/3000 [00:57<00:15, 35.93it/s]

[I 2026-07-05 15:23:32,798] Trial 2423 finished with value: 0.9495226945770737 and parameters: {'weight_class_0': 0.45598013531779374, 'weight_class_1': 4.7571217840418045, 'weight_class_2': 5.026561679511125}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:32,800] Trial 2424 finished with value: 0.9481745298464119 and parameters: {'weight_class_0': 0.1776117079818431, 'weight_class_1': 4.907646455663786, 'weight_class_2': 4.645400492554256}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:32,829] Trial 2425 finished with value: 0.9140008813412418 and parameters: {'weight_class_0': 0.46581498485752354, 'weight_class_1': 0.4073814154622411, 'weight_class_2': 4.847745464078595}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:32,845] Trial 2426 finished with value: 0.94943130790372 and parameters: {'weight_class_0': 0.4590941960749798, 'weight_class_1': 4.082991509430945, 'weight_class_2': 4.940751646393689}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:32,869] Trial 2427 finished with value: 0.914837535535341 and parameters: {'weight_class_0': 0.4637107990876863, 'weight_class_1': 0.41954355860288456, 'weight_class_2': 5.208810317567695}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:32,894] Trial 2428 finished with value: 0.9494212010840566 and parameters: {'weight_class_0': 0.4607285422442135, 'weight_class_1': 3.9221079524624103, 'weight_class_2': 5.173624036169869}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:32,904] Trial 2429 finished with value: 0.9495640532542725 and parameters: {'weight_class_0': 0.47088736992190544, 'weight_class_1': 5.037143234740983, 'weight_class_2': 5.410069712777238}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:32,911] Trial 2430 finished with value: 0.9495719285713341 and parameters: {'weight_class_0': 0.4636802241877838, 'weight_class_1': 5.073008555625633, 'weight_class_2': 5.434945537357664}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:32,914] Trial 2431 finished with value: 0.9494461986633338 and parameters: {'weight_class_0': 0.44347236024309905, 'weight_class_1': 3.8836218255504447, 'weight_class_2': 4.080626299117503}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:32,931] Trial 2432 finished with value: 0.949292395710278 and parameters: {'weight_class_0': 0.42820699027202586, 'weight_class_1': 3.7421466653001656, 'weight_class_2': 5.489748614541547}. Best is trial 2193 with value: 0.949738926310991.

[I 2026-07-05 15:23:33,043] Trial 2433 finished with value: 0.9490281001511734 and parameters: {'weight_class_0': 0.31163214297604025, 'weight_class_1': 3.7219909201086763, 'weight_class_2': 5.4486249004637335}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:33,089] Trial 2434 finished with value: 0.9489731258329247 and parameters: {'weight_class_0': 0.30766675074543276, 'weight_class_1': 3.780663221325114, 'weight_class_2': 5.545865604012433}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:33,156] Trial 2435 finished with value: 0.9497057008555849 and parameters: {'weight_class_0': 0.31002594437697695, 'weight_class_1': 3.7954372367909945, 'weight_class_2': 3.441248409071119}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:33,194] Trial 2436 finished with value: 0.9495631767493191 and parameters: {'weight_class_0': 0.304435988620657, 'weight_class_1': 3.5275000181246132, 'weight_class_2': 3.8936932992736764}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:33,213] Trial 2438 finished with value: 0.8615069660888549 and parameters: {'weight_class_0': 5.241235412727502, 'weight_class_1': 3.7351892701559395, 'weight_class_2': 3.7150583303622287}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:33,215] Trial 2437 finished with value: 0.9495748010308255 and parameters: {'weight_class_0': 0.33174664130419496, 'weight_class_1': 3.62050694640153, 'weight_class_2': 3.4970771269200704}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▉                        | 2446/3000 [00:58<00:16, 33.92it/s]

[I 2026-07-05 15:23:33,232] Trial 2439 finished with value: 0.9497126246794269 and parameters: {'weight_class_0': 0.30361749023772705, 'weight_class_1': 3.713533034788477, 'weight_class_2': 3.455558814749573}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:33,234] Trial 2440 finished with value: 0.9495659482245028 and parameters: {'weight_class_0': 0.3137722657351666, 'weight_class_1': 5.771523052030079, 'weight_class_2': 3.395669400713158}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:33,284] Trial 2441 finished with value: 0.9495717290495582 and parameters: {'weight_class_0': 0.3313240607381854, 'weight_class_1': 5.795989388300597, 'weight_class_2': 3.508301294149989}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:33,302] Trial 2443 finished with value: 0.6594584307816617 and parameters: {'weight_class_0': 0.0025325359631884732, 'weight_class_1': 5.66769946188276, 'weight_class_2': 3.4088532096964705}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:33,327] Trial 2444 finished with value: 0.9495556991950354 and parameters: {'weight_class_0': 0.2955108378233867, 'weight_class_1': 5.71403997007438, 'weight_class_2': 3.7841628556015054}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:33,332] Trial 2445 finished with value: 0.9496088561934583 and parameters: {'weight_class_0': 0.3100476408344671, 'weight_class_1': 5.594218671520696, 'weight_class_2': 3.616577676285694}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:33,338] Trial 2442 finished with value: 0.9496093240565456 and parameters: {'weight_class_0': 0.33488164662379705, 'weight_class_1': 5.792732123799352, 'weight_class_2': 3.899265787930419}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:33,376] Trial 2446 finished with value: 0.9495543589234333 and parameters: {'weight_class_0': 0.35413154182549544, 'weight_class_1': 5.521780723966318, 'weight_class_2': 3.4236536710468277}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▎                       | 2453/3000 [00:58<00:17, 30.64it/s]

[I 2026-07-05 15:23:33,463] Trial 2447 finished with value: 0.9482208920283502 and parameters: {'weight_class_0': 0.28902757244056465, 'weight_class_1': 1.8393160099560149, 'weight_class_2': 1.8337766334711638}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:33,529] Trial 2448 finished with value: 0.9494389346783215 and parameters: {'weight_class_0': 0.282808421819333, 'weight_class_1': 2.5629649440603313, 'weight_class_2': 2.2544613613697098}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:33,541] Trial 2449 finished with value: 0.94951814368429 and parameters: {'weight_class_0': 0.24534375711598036, 'weight_class_1': 2.614058380421466, 'weight_class_2': 2.219563190534058}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:33,586] Trial 2450 finished with value: 0.9493914257350852 and parameters: {'weight_class_0': 0.20966304683078865, 'weight_class_1': 1.8269047055346073, 'weight_class_2': 2.2038776761237253}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:33,630] Trial 2452 finished with value: 0.7563632438318191 and parameters: {'weight_class_0': 0.22034302440273557, 'weight_class_1': 1.9655568877214369, 'weight_class_2': 0.0022829388595484515}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:33,640] Trial 2451 finished with value: 0.9496473959061635 and parameters: {'weight_class_0': 0.19040499064727276, 'weight_class_1': 2.7762015300620244, 'weight_class_2': 2.0768066376991543}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:33,641] Trial 2453 finished with value: 0.949670696512455 and parameters: {'weight_class_0': 0.19724220816061025, 'weight_class_1': 2.599772744717391, 'weight_class_2': 1.9124689250030096}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▌                       | 2460/3000 [00:58<00:15, 34.76it/s]

[I 2026-07-05 15:23:33,688] Trial 2454 finished with value: 0.9495644218395696 and parameters: {'weight_class_0': 0.2156328958186816, 'weight_class_1': 2.3811507678269783, 'weight_class_2': 2.0480472672329597}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:33,706] Trial 2456 finished with value: 0.9494618154171048 and parameters: {'weight_class_0': 0.20997583142898343, 'weight_class_1': 1.8468173479083898, 'weight_class_2': 2.039751346404514}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:33,718] Trial 2455 finished with value: 0.9495165602754949 and parameters: {'weight_class_0': 0.23116117767571426, 'weight_class_1': 2.4186018964387936, 'weight_class_2': 2.0823071658898344}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:33,732] Trial 2457 finished with value: 0.9495426223779195 and parameters: {'weight_class_0': 0.20521003253176678, 'weight_class_1': 3.5738655927756335, 'weight_class_2': 2.206395264831245}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:33,737] Trial 2458 finished with value: 0.9494559897348928 and parameters: {'weight_class_0': 0.22077865133692326, 'weight_class_1': 1.9918563494593244, 'weight_class_2': 2.388212837997478}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:33,791] Trial 2459 finished with value: 0.6615846164956372 and parameters: {'weight_class_0': 0.0017620835012023234, 'weight_class_1': 2.8741018846578674, 'weight_class_2': 1.9838102245464628}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:33,889] Trial 2460 finished with value: 0.949689341477213 and parameters: {'weight_class_0': 0.20935197501618438, 'weight_class_1': 3.0173471620578742, 'weight_class_2': 2.348704333293088}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▉                       | 2468/3000 [00:59<00:16, 32.20it/s]

[I 2026-07-05 15:23:33,909] Trial 2461 finished with value: 0.9491209268130998 and parameters: {'weight_class_0': 0.2073808140620423, 'weight_class_1': 1.8988889838734238, 'weight_class_2': 3.012520738554428}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:33,972] Trial 2462 finished with value: 0.9495982037290469 and parameters: {'weight_class_0': 0.22117203184277112, 'weight_class_1': 2.82565746198924, 'weight_class_2': 2.8904176568543405}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:33,989] Trial 2464 finished with value: 0.9496366916991495 and parameters: {'weight_class_0': 0.23100862558161245, 'weight_class_1': 2.9386510824777137, 'weight_class_2': 2.390218818529064}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:33,990] Trial 2463 finished with value: 0.9496604454424818 and parameters: {'weight_class_0': 0.2347747035861305, 'weight_class_1': 2.844644644234989, 'weight_class_2': 2.777770978019761}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:34,024] Trial 2465 finished with value: 0.8091958829369895 and parameters: {'weight_class_0': 0.2642581667798179, 'weight_class_1': 2.9979722335280985, 'weight_class_2': 0.006502704168578556}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:34,034] Trial 2466 finished with value: 0.949640650005171 and parameters: {'weight_class_0': 0.2705892408273369, 'weight_class_1': 3.6568967410904527, 'weight_class_2': 2.5534083702712387}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:34,076] Trial 2467 finished with value: 0.9495594158391899 and parameters: {'weight_class_0': 0.29379560363429735, 'weight_class_1': 3.1246968473319083, 'weight_class_2': 3.379247964512774}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:34,084] Trial 2468 finished with value: 0.9496555185601192 and parameters: {'weight_class_0': 0.26651072694760414, 'weight_class_1': 3.0456530270996747, 'weight_class_2': 2.9255309683972373}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▏                      | 2474/3000 [00:59<00:16, 31.25it/s]

[I 2026-07-05 15:23:34,097] Trial 2469 finished with value: 0.9495935903486897 and parameters: {'weight_class_0': 0.2803452121135196, 'weight_class_1': 3.209276239270383, 'weight_class_2': 2.9171102966882425}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:34,132] Trial 2471 finished with value: 0.9496745085894323 and parameters: {'weight_class_0': 0.2440122918203952, 'weight_class_1': 3.0009004596021067, 'weight_class_2': 2.94122197185502}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:34,170] Trial 2470 finished with value: 0.9495912214035601 and parameters: {'weight_class_0': 0.2943542344194863, 'weight_class_1': 3.1957474864752635, 'weight_class_2': 2.9932238369963455}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:34,255] Trial 2472 finished with value: 0.9496464486946957 and parameters: {'weight_class_0': 0.2711626450631329, 'weight_class_1': 3.092040473098427, 'weight_class_2': 2.9555543591881084}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:34,272] Trial 2473 finished with value: 0.9490603407130368 and parameters: {'weight_class_0': 0.16368592215098363, 'weight_class_1': 3.0636841722969845, 'weight_class_2': 2.9679521928559716}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:34,298] Trial 2474 finished with value: 0.9495056987417239 and parameters: {'weight_class_0': 0.30350392633290824, 'weight_class_1': 3.1615302872694815, 'weight_class_2': 2.683272108584042}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  83%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▌                      | 2483/3000 [00:59<00:14, 35.84it/s]

[I 2026-07-05 15:23:34,345] Trial 2475 finished with value: 0.9496469619829804 and parameters: {'weight_class_0': 0.2659197100674471, 'weight_class_1': 3.837053592100177, 'weight_class_2': 3.247418159664423}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:34,383] Trial 2478 finished with value: 0.9496576515870241 and parameters: {'weight_class_0': 0.2675959021518318, 'weight_class_1': 3.595577294637589, 'weight_class_2': 2.9372737293383215}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:34,398] Trial 2476 finished with value: 0.9496437716239026 and parameters: {'weight_class_0': 0.2812305482621449, 'weight_class_1': 3.247315331944319, 'weight_class_2': 3.003762832129844}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:34,400] Trial 2477 finished with value: 0.9496339120431889 and parameters: {'weight_class_0': 0.28374526926598365, 'weight_class_1': 3.7784606762691504, 'weight_class_2': 2.9352230631371303}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:34,443] Trial 2479 finished with value: 0.9495896615772784 and parameters: {'weight_class_0': 0.2963855931212524, 'weight_class_1': 3.3638153554838035, 'weight_class_2': 2.975715987225208}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:34,462] Trial 2480 finished with value: 0.9487876933846812 and parameters: {'weight_class_0': 0.15365852933004523, 'weight_class_1': 3.7974531543910923, 'weight_class_2': 2.9035352954630853}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:34,465] Trial 2481 finished with value: 0.9496215276504872 and parameters: {'weight_class_0': 0.2900406569420825, 'weight_class_1': 3.6271746880349425, 'weight_class_2': 3.0223657006738542}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:34,503] Trial 2482 finished with value: 0.949625486223873 and parameters: {'weight_class_0': 0.2844104410892887, 'weight_class_1': 3.7358534540965986, 'weight_class_2': 2.95396829553756}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:34,521] Trial 2483 finished with value: 0.9484827182651531 and parameters: {'weight_class_0': 0.15313054692499453, 'weight_class_1': 3.7461329834705053, 'weight_class_2': 3.5539876775268597}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  83%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▉                      | 2490/3000 [00:59<00:16, 31.36it/s]

[I 2026-07-05 15:23:34,621] Trial 2485 finished with value: 0.9495341963274123 and parameters: {'weight_class_0': 0.348004984937855, 'weight_class_1': 3.688707822020065, 'weight_class_2': 3.2655418957510918}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:34,630] Trial 2484 finished with value: 0.9474452172382666 and parameters: {'weight_class_0': 0.10807089636102231, 'weight_class_1': 3.806450721114514, 'weight_class_2': 3.6115911505090836}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:34,664] Trial 2486 finished with value: 0.9494982673558209 and parameters: {'weight_class_0': 0.3469941304989038, 'weight_class_1': 3.6191689781959515, 'weight_class_2': 3.6835825601093495}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:34,693] Trial 2487 finished with value: 0.9495712912302118 and parameters: {'weight_class_0': 0.34845908985363927, 'weight_class_1': 3.8513027070292027, 'weight_class_2': 3.263407260724564}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:34,760] Trial 2488 finished with value: 0.9496452158913659 and parameters: {'weight_class_0': 0.3328449919213592, 'weight_class_1': 3.960837481877091, 'weight_class_2': 3.260452867475122}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:34,771] Trial 2489 finished with value: 0.9496318785740048 and parameters: {'weight_class_0': 0.34472051688523814, 'weight_class_1': 3.9960278659784545, 'weight_class_2': 3.7166377738472}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:34,798] Trial 2490 finished with value: 0.9495760796497937 and parameters: {'weight_class_0': 0.36790352326831405, 'weight_class_1': 4.00443247775195, 'weight_class_2': 3.4499423257074957}. Best is trial 2193 with value: 0.949738926310991.

[I 2026-07-05 15:23:34,811] Trial 2491 finished with value: 0.9496199417282288 and parameters: {'weight_class_0': 0.35850871938392886, 'weight_class_1': 4.059014325819226, 'weight_class_2': 3.6409119326839234}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:34,817] Trial 2492 finished with value: 0.9464665333398777 and parameters: {'weight_class_0': 0.3520561053198227, 'weight_class_1': 1.354261343750369, 'weight_class_2': 3.8370286347519076}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:34,854] Trial 2494 finished with value: 0.9496824773885758 and parameters: {'weight_class_0': 0.3460132986389295, 'weight_class_1': 4.1775464401252815, 'weight_class_2': 3.848284599634093}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:34,864] Trial 2495 finished with value: 0.9496249437426801 and parameters: {'weight_class_0': 0.35556515073869904, 'weight_class_1': 4.298738407731007, 'weight_class_2': 3.618359071648437}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:34,866] Trial 2493 finished with value: 0.8817322296746236 and parameters: {'weight_class_0': 3.543439140432068, 'weight_class_1': 4.048304263798054, 'weight_class_2': 3.385313754984101}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:34,956] Trial 2496 finished with value: 0.949664799404152 and parameters: {'weight_class_0': 0.3603556575778002, 'weight_class_1': 4.2196253407061795, 'weight_class_2': 3.977540869594248}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:35,011] Trial 2498 finished with value: 0.9488966640390846 and parameters: {'weight_class_0': 0.3390601294084091, 'weight_class_1': 2.2690787502078753, 'weight_class_2': 4.032772692548313}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                     | 2505/3000 [01:00<00:15, 31.87it/s]

[I 2026-07-05 15:23:35,020] Trial 2497 finished with value: 0.9486440002429669 and parameters: {'weight_class_0': 0.37534004052443803, 'weight_class_1': 2.2740668849402725, 'weight_class_2': 4.009091704482423}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:35,028] Trial 2499 finished with value: 0.9497122956903068 and parameters: {'weight_class_0': 0.3555091049124809, 'weight_class_1': 4.551637078724092, 'weight_class_2': 4.046762357320144}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:35,092] Trial 2500 finished with value: 0.9488648458094534 and parameters: {'weight_class_0': 0.3636392081087989, 'weight_class_1': 2.3931972755765347, 'weight_class_2': 4.108001953394222}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:35,149] Trial 2502 finished with value: 0.9496923451264595 and parameters: {'weight_class_0': 0.36896196748911597, 'weight_class_1': 4.363823587681906, 'weight_class_2': 4.082504416202841}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:35,154] Trial 2501 finished with value: 0.9496906563106436 and parameters: {'weight_class_0': 0.37459542442911914, 'weight_class_1': 4.401902622743652, 'weight_class_2': 4.341047250337326}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:35,176] Trial 2503 finished with value: 0.9483969844735763 and parameters: {'weight_class_0': 0.3989343872813655, 'weight_class_1': 2.258131108013786, 'weight_class_2': 4.2631186490668185}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:35,190] Trial 2504 finished with value: 0.9489664320331895 and parameters: {'weight_class_0': 0.3842372751621794, 'weight_class_1': 4.53718969706878, 'weight_class_2': 2.4275786994586888}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:35,239] Trial 2505 finished with value: 0.9496115913083659 and parameters: {'weight_class_0': 0.39460470429174144, 'weight_class_1': 4.463435996962221, 'weight_class_2': 4.100057135207622}. Best is trial 2193 with value: 0.949738926310991.

[I 2026-07-05 15:23:35,286] Trial 2507 finished with value: 0.9481828681945914 and parameters: {'weight_class_0': 0.38169183765275966, 'weight_class_1': 2.352474150173117, 'weight_class_2': 2.447132913529901}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:35,295] Trial 2506 finished with value: 0.9458010535079137 and parameters: {'weight_class_0': 0.38618485682506015, 'weight_class_1': 2.5249859721160166, 'weight_class_2': 1.498254879112992}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:35,300] Trial 2508 finished with value: 0.9485525119019019 and parameters: {'weight_class_0': 0.38849167089183984, 'weight_class_1': 2.2945343873664585, 'weight_class_2': 4.12382027030084}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:35,360] Trial 2509 finished with value: 0.7809490817158139 and parameters: {'weight_class_0': 0.25038482110889154, 'weight_class_1': 0.0029601642480836243, 'weight_class_2': 2.466150319133041}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:35,396] Trial 2511 finished with value: 0.9495584800512441 and parameters: {'weight_class_0': 0.2493057340607052, 'weight_class_1': 2.7227641290001285, 'weight_class_2': 2.5572137082247224}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:35,414] Trial 2510 finished with value: 0.9493648804518787 and parameters: {'weight_class_0': 0.2951589117875679, 'weight_class_1': 2.4798799558741593, 'weight_class_2': 2.3292954583641037}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:35,455] Trial 2512 finished with value: 0.9496393505227462 and parameters: {'weight_class_0': 0.24696972901320388, 'weight_class_1': 3.2187027011116855, 'weight_class_2': 2.618692218985244}. Best is trial 2193 with value: 0.949738926310991.

[I 2026-07-05 15:23:35,490] Trial 2513 finished with value: 0.9496244700713183 and parameters: {'weight_class_0': 0.26262405807428124, 'weight_class_1': 3.1764639270855737, 'weight_class_2': 2.5462119216364263}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:35,536] Trial 2514 finished with value: 0.9495418819405078 and parameters: {'weight_class_0': 0.2584892070689432, 'weight_class_1': 2.5591486086851276, 'weight_class_2': 2.319744394721954}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:35,553] Trial 2516 finished with value: 0.949539705788562 and parameters: {'weight_class_0': 0.258307850633763, 'weight_class_1': 2.6398316418515333, 'weight_class_2': 2.565122114309642}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:35,583] Trial 2515 finished with value: 0.9495644821017896 and parameters: {'weight_class_0': 0.2506000060126481, 'weight_class_1': 3.2935390750704236, 'weight_class_2': 3.41023323552444}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:35,589] Trial 2517 finished with value: 0.9496459130010048 and parameters: {'weight_class_0': 0.2596447079171044, 'weight_class_1': 3.3701005725319044, 'weight_class_2': 3.303323234448313}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:35,647] Trial 2518 finished with value: 0.9496147339884337 and parameters: {'weight_class_0': 0.2426230671928479, 'weight_class_1': 3.3032134539571483, 'weight_class_2': 3.252009092930932}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:35,675] Trial 2520 finished with value: 0.949676438083035 and parameters: {'weight_class_0': 0.23849698553564155, 'weight_class_1': 3.35743527591152, 'weight_class_2': 2.6488310769352443}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  84%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                    | 2526/3000 [01:00<00:13, 34.59it/s]

[I 2026-07-05 15:23:35,679] Trial 2519 finished with value: 0.9495710711282369 and parameters: {'weight_class_0': 0.2510796620642379, 'weight_class_1': 3.2332100426808332, 'weight_class_2': 3.33219128206233}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:35,716] Trial 2521 finished with value: 0.9496578441823286 and parameters: {'weight_class_0': 0.2922870373705846, 'weight_class_1': 3.2966212975592684, 'weight_class_2': 3.2133791261672755}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:35,753] Trial 2522 finished with value: 0.9496952122096087 and parameters: {'weight_class_0': 0.28413128119178516, 'weight_class_1': 3.359452018459912, 'weight_class_2': 3.2574516553168413}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:35,771] Trial 2524 finished with value: 0.9494732733923108 and parameters: {'weight_class_0': 0.30401442787493377, 'weight_class_1': 2.986045210541645, 'weight_class_2': 3.036370328342866}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:35,778] Trial 2523 finished with value: 0.9495647025739254 and parameters: {'weight_class_0': 0.3031593522408665, 'weight_class_1': 3.3075169192324902, 'weight_class_2': 3.1200478001702883}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:35,859] Trial 2525 finished with value: 0.9495827612205869 and parameters: {'weight_class_0': 0.2928554898417289, 'weight_class_1': 3.3607579218448627, 'weight_class_2': 3.6849978104227286}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:35,900] Trial 2526 finished with value: 0.9490461932281157 and parameters: {'weight_class_0': 0.18063067330666144, 'weight_class_1': 3.316544311144958, 'weight_class_2': 3.28662251010536}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  84%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                    | 2534/3000 [01:01<00:15, 31.05it/s]

[I 2026-07-05 15:23:35,942] Trial 2527 finished with value: 0.9496276640335971 and parameters: {'weight_class_0': 0.32049274149239404, 'weight_class_1': 4.301243974521319, 'weight_class_2': 3.4513106188405107}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:35,969] Trial 2528 finished with value: 0.9484371863299615 and parameters: {'weight_class_0': 0.17800157770628428, 'weight_class_1': 4.50625465152369, 'weight_class_2': 4.1772297795885365}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:36,018] Trial 2530 finished with value: 0.948766548066879 and parameters: {'weight_class_0': 0.17593287678867117, 'weight_class_1': 4.357076392811165, 'weight_class_2': 3.4143739784467253}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:36,025] Trial 2529 finished with value: 0.9496578200573725 and parameters: {'weight_class_0': 0.29762553139237813, 'weight_class_1': 4.310584249614183, 'weight_class_2': 3.2493387607775137}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:36,052] Trial 2532 finished with value: 0.9496075940895709 and parameters: {'weight_class_0': 0.3096009138200406, 'weight_class_1': 4.462476071128178, 'weight_class_2': 4.018432397934081}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:36,057] Trial 2531 finished with value: 0.9496004807263306 and parameters: {'weight_class_0': 0.31627697371270774, 'weight_class_1': 4.270050525806945, 'weight_class_2': 4.16945815376917}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:36,073] Trial 2533 finished with value: 0.9496409146230663 and parameters: {'weight_class_0': 0.3416320332420823, 'weight_class_1': 4.774782486782161, 'weight_class_2': 4.276857544198367}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:36,118] Trial 2534 finished with value: 0.9496296732291508 and parameters: {'weight_class_0': 0.31722886747156853, 'weight_class_1': 4.388405477381369, 'weight_class_2': 4.208635542147934}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████                    | 2540/3000 [01:01<00:14, 32.58it/s]

[I 2026-07-05 15:23:36,128] Trial 2535 finished with value: 0.9486939388482217 and parameters: {'weight_class_0': 0.19653112562137748, 'weight_class_1': 4.329112901814633, 'weight_class_2': 4.231642801171094}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:36,139] Trial 2536 finished with value: 0.9496949646338096 and parameters: {'weight_class_0': 0.34379903149139385, 'weight_class_1': 4.245916090457325, 'weight_class_2': 4.084646093881816}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:36,226] Trial 2537 finished with value: 0.9494449174126781 and parameters: {'weight_class_0': 0.29722139322316277, 'weight_class_1': 4.51292202444158, 'weight_class_2': 4.305719805201305}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:36,265] Trial 2538 finished with value: 0.9495130244537074 and parameters: {'weight_class_0': 0.3190284707123776, 'weight_class_1': 4.573926194591193, 'weight_class_2': 4.4686209543072035}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:36,271] Trial 2539 finished with value: 0.9496245531013919 and parameters: {'weight_class_0': 0.318546357038791, 'weight_class_1': 4.490245628829444, 'weight_class_2': 4.28136443354078}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:36,307] Trial 2540 finished with value: 0.6671152547725646 and parameters: {'weight_class_0': 0.004324113747031551, 'weight_class_1': 4.4846792376409255, 'weight_class_2': 4.323452028276272}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                   | 2548/3000 [01:01<00:13, 34.21it/s]

[I 2026-07-05 15:23:36,358] Trial 2541 finished with value: 0.9495679633673006 and parameters: {'weight_class_0': 0.3288047098565486, 'weight_class_1': 3.8891124170201747, 'weight_class_2': 4.291307549058358}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:36,360] Trial 2543 finished with value: 0.9488057131673083 and parameters: {'weight_class_0': 0.21012323824820844, 'weight_class_1': 4.68673584057775, 'weight_class_2': 4.241062068733035}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:36,400] Trial 2542 finished with value: 0.9496866217620505 and parameters: {'weight_class_0': 0.4014460455632444, 'weight_class_1': 4.7859236238499365, 'weight_class_2': 4.421732021866931}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:36,433] Trial 2544 finished with value: 0.949630851002781 and parameters: {'weight_class_0': 0.39727422003176943, 'weight_class_1': 4.875251660859899, 'weight_class_2': 4.155897109903449}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:36,452] Trial 2545 finished with value: 0.9487740726139077 and parameters: {'weight_class_0': 0.21397522710597808, 'weight_class_1': 4.961808736972121, 'weight_class_2': 4.291454382529801}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:36,481] Trial 2546 finished with value: 0.9496614280663188 and parameters: {'weight_class_0': 0.38945358071678937, 'weight_class_1': 4.901637829130915, 'weight_class_2': 4.128366517829527}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:36,491] Trial 2547 finished with value: 0.9476579999130643 and parameters: {'weight_class_0': 0.41274121960553617, 'weight_class_1': 4.8640155379074965, 'weight_class_2': 1.854000201215994}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:36,497] Trial 2548 finished with value: 0.6856106774812701 and parameters: {'weight_class_0': 0.004302137952920309, 'weight_class_1': 4.772039830765686, 'weight_class_2': 1.8147486118699114}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                   | 2555/3000 [01:01<00:13, 32.90it/s]

[I 2026-07-05 15:23:36,576] Trial 2549 finished with value: 0.9496873119529315 and parameters: {'weight_class_0': 0.4009076005487446, 'weight_class_1': 5.249038792988186, 'weight_class_2': 4.423531422793175}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:36,626] Trial 2550 finished with value: 0.9472935889140895 and parameters: {'weight_class_0': 0.40168579255778025, 'weight_class_1': 4.720268943370926, 'weight_class_2': 1.7212824255327652}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:36,647] Trial 2551 finished with value: 0.949641808943284 and parameters: {'weight_class_0': 0.41446460543102914, 'weight_class_1': 4.9015270616073785, 'weight_class_2': 3.851040174490181}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:36,670] Trial 2552 finished with value: 0.949528909057948 and parameters: {'weight_class_0': 0.4043674690538189, 'weight_class_1': 4.00349350225892, 'weight_class_2': 3.6205478282717376}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:36,704] Trial 2553 finished with value: 0.9470230376814609 and parameters: {'weight_class_0': 0.4360517654169653, 'weight_class_1': 5.028242716606401, 'weight_class_2': 1.8211139392427964}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:36,741] Trial 2554 finished with value: 0.9496720187627335 and parameters: {'weight_class_0': 0.39769518308626844, 'weight_class_1': 5.100028804842254, 'weight_class_2': 3.3667613994605667}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:36,777] Trial 2555 finished with value: 0.9493360430390078 and parameters: {'weight_class_0': 0.39429038025743884, 'weight_class_1': 5.100210003040751, 'weight_class_2': 2.9141006534150407}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  85%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████                   | 2562/3000 [01:01<00:14, 30.21it/s]

[I 2026-07-05 15:23:36,816] Trial 2556 finished with value: 0.9496659619913439 and parameters: {'weight_class_0': 0.393695896723157, 'weight_class_1': 5.219122000991536, 'weight_class_2': 3.3506469165766624}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:36,833] Trial 2557 finished with value: 0.9489794509528742 and parameters: {'weight_class_0': 0.42359460558017875, 'weight_class_1': 4.027762584219686, 'weight_class_2': 2.891958622287674}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:36,849] Trial 2558 finished with value: 0.9489970046740144 and parameters: {'weight_class_0': 0.4133088748604943, 'weight_class_1': 3.6090055857397463, 'weight_class_2': 2.8561014396329436}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:36,923] Trial 2560 finished with value: 0.9485779589783802 and parameters: {'weight_class_0': 0.41441449100761585, 'weight_class_1': 2.8110988476317647, 'weight_class_2': 2.816566674227092}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:36,927] Trial 2559 finished with value: 0.9489679807443393 and parameters: {'weight_class_0': 0.4084195021699865, 'weight_class_1': 3.563413784018161, 'weight_class_2': 2.7629468027426096}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:36,949] Trial 2561 finished with value: 0.9490912533007938 and parameters: {'weight_class_0': 0.40219845278834954, 'weight_class_1': 3.5533065494907206, 'weight_class_2': 2.8660309602838154}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:37,011] Trial 2562 finished with value: 0.9489355656620867 and parameters: {'weight_class_0': 0.4313612262342307, 'weight_class_1': 3.6083064580150657, 'weight_class_2': 2.972224978722209}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                  | 2570/3000 [01:02<00:12, 35.19it/s]

[I 2026-07-05 15:23:37,029] Trial 2563 finished with value: 0.9496600301284771 and parameters: {'weight_class_0': 0.3308740313556313, 'weight_class_1': 3.7249061455605075, 'weight_class_2': 2.8183272603855323}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:37,030] Trial 2564 finished with value: 0.9496074080505771 and parameters: {'weight_class_0': 0.21981213804589902, 'weight_class_1': 2.7086324279116827, 'weight_class_2': 2.9369524415196566}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:37,088] Trial 2565 finished with value: 0.9495861123986469 and parameters: {'weight_class_0': 0.3216211746280526, 'weight_class_1': 3.642671665790618, 'weight_class_2': 2.6702810231848604}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:37,093] Trial 2566 finished with value: 0.9496566003715158 and parameters: {'weight_class_0': 0.3023266467818442, 'weight_class_1': 3.715320801753453, 'weight_class_2': 2.8892662436927194}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:37,129] Trial 2567 finished with value: 0.9496514286531562 and parameters: {'weight_class_0': 0.23525747256910182, 'weight_class_1': 3.566331188117686, 'weight_class_2': 2.7319193354519853}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:37,147] Trial 2568 finished with value: 0.8947036557861341 and parameters: {'weight_class_0': 0.22703431454440054, 'weight_class_1': 2.7813318105745792, 'weight_class_2': 0.07057785299810058}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:37,184] Trial 2570 finished with value: 0.9485040368441867 and parameters: {'weight_class_0': 0.21646461772077497, 'weight_class_1': 2.8528978524368047, 'weight_class_2': 4.9345668752405105}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:37,189] Trial 2569 finished with value: 0.9486567465594632 and parameters: {'weight_class_0': 0.2227354791765651, 'weight_class_1': 4.19816401331481, 'weight_class_2': 5.054691184617524}. Best is trial 2193 with value: 0.949738926310991.

[I 2026-07-05 15:23:37,308] Trial 2573 finished with value: 0.9485151563854853 and parameters: {'weight_class_0': 0.21662487043403122, 'weight_class_1': 2.7675931708493304, 'weight_class_2': 4.881015522468288}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:37,321] Trial 2572 finished with value: 0.9490217302966787 and parameters: {'weight_class_0': 0.3079730008232413, 'weight_class_1': 2.81181830615182, 'weight_class_2': 4.752641760977494}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:37,339] Trial 2574 finished with value: 0.9486634016795462 and parameters: {'weight_class_0': 0.2669174638692945, 'weight_class_1': 2.6971051626138385, 'weight_class_2': 4.940163498368981}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:37,340] Trial 2571 finished with value: 0.9485342780900773 and parameters: {'weight_class_0': 0.22409368695783757, 'weight_class_1': 2.7538368156857183, 'weight_class_2': 4.94008891664999}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:37,400] Trial 2575 finished with value: 0.9489575236565259 and parameters: {'weight_class_0': 0.30419246434741165, 'weight_class_1': 2.782196481814459, 'weight_class_2': 4.803613095329793}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:37,443] Trial 2577 finished with value: 0.709684908326277 and parameters: {'weight_class_0': 0.006691803372272995, 'weight_class_1': 2.7010802854050726, 'weight_class_2': 4.754253826984364}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:37,449] Trial 2576 finished with value: 0.948668928100275 and parameters: {'weight_class_0': 0.28751763351035264, 'weight_class_1': 2.661980265206973, 'weight_class_2': 5.093653226809634}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:37,456] Trial 2578 finished with value: 0.9494044767207273 and parameters: {'weight_class_0': 0.3156991779012279, 'weight_class_1': 5.210244590244761, 'weight_class_2': 4.767531896332371}. Best is trial 2193 with value: 0.949738926310991.

[I 2026-07-05 15:23:37,491] Trial 2580 finished with value: 0.9492756797097118 and parameters: {'weight_class_0': 0.2961962443030256, 'weight_class_1': 5.308129622589111, 'weight_class_2': 4.805482987121202}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:37,506] Trial 2579 finished with value: 0.9491673613053342 and parameters: {'weight_class_0': 0.27580908297441553, 'weight_class_1': 5.3762576448484145, 'weight_class_2': 4.759437029765479}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:37,523] Trial 2581 finished with value: 0.9494322619693131 and parameters: {'weight_class_0': 0.2740520910834884, 'weight_class_1': 5.863628415577912, 'weight_class_2': 3.6220200127459576}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:37,552] Trial 2582 finished with value: 0.9470472883842417 and parameters: {'weight_class_0': 0.12455017958559769, 'weight_class_1': 5.457762654237024, 'weight_class_2': 3.6363519539933282}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:37,664] Trial 2583 finished with value: 0.885444652326563 and parameters: {'weight_class_0': 0.29641418070054787, 'weight_class_1': 0.0666115723531159, 'weight_class_2': 3.5540059013682845}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:37,696] Trial 2585 finished with value: 0.9178268021650844 and parameters: {'weight_class_0': 0.13013418031222823, 'weight_class_1': 0.13786921648081177, 'weight_class_2': 3.5910873644049572}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                 | 2593/3000 [01:02<00:12, 33.76it/s]

[I 2026-07-05 15:23:37,707] Trial 2584 finished with value: 0.9495898436018845 and parameters: {'weight_class_0': 0.33106321581099846, 'weight_class_1': 5.377043405349405, 'weight_class_2': 3.551889283719255}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:37,711] Trial 2586 finished with value: 0.9495655099244846 and parameters: {'weight_class_0': 0.3334268374752018, 'weight_class_1': 5.524238935177277, 'weight_class_2': 3.5385314765710425}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:37,743] Trial 2587 finished with value: 0.6881089865436797 and parameters: {'weight_class_0': 0.006342290988371982, 'weight_class_1': 5.173875057305419, 'weight_class_2': 3.625813909827296}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:37,789] Trial 2588 finished with value: 0.9491977493840169 and parameters: {'weight_class_0': 0.4831295558528902, 'weight_class_1': 5.24341698602877, 'weight_class_2': 3.4894113947216026}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:37,807] Trial 2589 finished with value: 0.9492886123991289 and parameters: {'weight_class_0': 0.4952050105227402, 'weight_class_1': 5.390447195570284, 'weight_class_2': 3.6807287112583245}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:37,810] Trial 2590 finished with value: 0.9492347071116528 and parameters: {'weight_class_0': 0.49435299951063055, 'weight_class_1': 5.542429398844724, 'weight_class_2': 3.564748159539048}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:37,855] Trial 2591 finished with value: 0.9495949550662037 and parameters: {'weight_class_0': 0.3544197868887991, 'weight_class_1': 4.120977425655578, 'weight_class_2': 3.6554699736793643}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:37,892] Trial 2592 finished with value: 0.9496237724351301 and parameters: {'weight_class_0': 0.35393842392025426, 'weight_class_1': 4.027265292831035, 'weight_class_2': 3.709406585518405}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:37,921] Trial 2593 finished with value: 0.9491768839525991 and parameters: {'weight_class_0': 0.48462470600443663, 'weight_class_1': 3.966351175114345, 'weight_class_2': 3.652265118747075}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  87%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                 | 2599/3000 [01:03<00:13, 29.85it/s]

[I 2026-07-05 15:23:37,924] Trial 2594 finished with value: 0.9495811524402443 and parameters: {'weight_class_0': 0.34623985987461425, 'weight_class_1': 4.125206757772407, 'weight_class_2': 3.4973346015341567}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:37,996] Trial 2595 finished with value: 0.9491164112834802 and parameters: {'weight_class_0': 0.4966341863189722, 'weight_class_1': 4.031177404742518, 'weight_class_2': 3.682694481777773}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:38,059] Trial 2596 finished with value: 0.9493130297310962 and parameters: {'weight_class_0': 0.48900200692621376, 'weight_class_1': 4.069996868418912, 'weight_class_2': 3.804160030738719}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:38,109] Trial 2597 finished with value: 0.9475978550767041 and parameters: {'weight_class_0': 0.5094456003785975, 'weight_class_1': 4.511344396128522, 'weight_class_2': 2.3009874156927452}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:38,125] Trial 2599 finished with value: 0.873661738544401 and parameters: {'weight_class_0': 0.5016414472169456, 'weight_class_1': 3.9608109548239177, 'weight_class_2': 0.023866656922291885}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:38,134] Trial 2600 finished with value: 0.9492045655218931 and parameters: {'weight_class_0': 0.34639737853814057, 'weight_class_1': 4.030529622743005, 'weight_class_2': 5.5669921227545265}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████                 | 2608/3000 [01:03<00:11, 33.32it/s]

[I 2026-07-05 15:23:38,142] Trial 2598 finished with value: 0.9483515479939442 and parameters: {'weight_class_0': 0.1633937882031318, 'weight_class_1': 3.9938397421757617, 'weight_class_2': 3.9871187906885024}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:38,198] Trial 2602 finished with value: 0.9477533226621758 and parameters: {'weight_class_0': 0.4874408880076855, 'weight_class_1': 3.9876117511446605, 'weight_class_2': 2.3355185823562974}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:38,217] Trial 2601 finished with value: 0.949297121873478 and parameters: {'weight_class_0': 0.35449933964344826, 'weight_class_1': 4.122786390252222, 'weight_class_2': 5.39514341269622}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:38,225] Trial 2603 finished with value: 0.9494169768932683 and parameters: {'weight_class_0': 0.5029110336820914, 'weight_class_1': 4.228597363262268, 'weight_class_2': 5.661966804471531}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:38,251] Trial 2604 finished with value: 0.9493329232946887 and parameters: {'weight_class_0': 0.5067667831465499, 'weight_class_1': 4.151538534143544, 'weight_class_2': 5.451095314508381}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:38,294] Trial 2605 finished with value: 0.9493227029851715 and parameters: {'weight_class_0': 0.49866909069857507, 'weight_class_1': 4.033508984288646, 'weight_class_2': 5.447569448390542}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:38,307] Trial 2606 finished with value: 0.947803864558543 and parameters: {'weight_class_0': 0.4595973064283106, 'weight_class_1': 3.328359762943061, 'weight_class_2': 2.325774392057359}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:38,334] Trial 2607 finished with value: 0.9478401694043507 and parameters: {'weight_class_0': 0.4550347201453726, 'weight_class_1': 3.3766873176832473, 'weight_class_2': 2.3112484902194614}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:38,374] Trial 2608 finished with value: 0.9495768040117705 and parameters: {'weight_class_0': 0.18364679539137593, 'weight_class_1': 3.3698240703827076, 'weight_class_2': 2.204795600184902}. Best is trial 2193 with value: 0.949738926310991.

[I 2026-07-05 15:23:38,490] Trial 2609 finished with value: 0.9478086113062005 and parameters: {'weight_class_0': 0.17041406994085082, 'weight_class_1': 3.2580056356710076, 'weight_class_2': 5.701743004592969}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:38,527] Trial 2611 finished with value: 0.9479855872939559 and parameters: {'weight_class_0': 0.4371790128953578, 'weight_class_1': 3.2410954109708894, 'weight_class_2': 2.3055679054328184}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:38,532] Trial 2612 finished with value: 0.947798107746003 and parameters: {'weight_class_0': 0.1865717677834422, 'weight_class_1': 6.034757286285258, 'weight_class_2': 5.404847629113801}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:38,540] Trial 2610 finished with value: 0.9496825001689958 and parameters: {'weight_class_0': 0.2642806790936986, 'weight_class_1': 3.428916827073829, 'weight_class_2': 2.25122327954439}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:38,572] Trial 2613 finished with value: 0.9490817987104715 and parameters: {'weight_class_0': 0.26387683778988336, 'weight_class_1': 6.046790101361724, 'weight_class_2': 4.440986324671121}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:38,596] Trial 2614 finished with value: 0.9485286527901785 and parameters: {'weight_class_0': 0.257532667132218, 'weight_class_1': 3.1647531694182054, 'weight_class_2': 5.691984505154275}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:38,624] Trial 2617 finished with value: 0.9491978595718112 and parameters: {'weight_class_0': 0.26378553908096036, 'weight_class_1': 5.664060960181964, 'weight_class_2': 4.390406189239212}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:38,628] Trial 2616 finished with value: 0.8426711220566571 and parameters: {'weight_class_0': 0.25324331134338535, 'weight_class_1': 3.3265157492070703, 'weight_class_2': 0.01085374710669177}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:38,629] Trial 2615 finished with value: 0.9490900323075057 and parameters: {'weight_class_0': 0.25719304174654967, 'weight_class_1': 3.1888334738022155, 'weight_class_2': 4.489000403964996}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                | 2622/3000 [01:03<00:12, 31.37it/s]

[I 2026-07-05 15:23:38,660] Trial 2618 finished with value: 0.9496624483283439 and parameters: {'weight_class_0': 0.3790087343957124, 'weight_class_1': 5.889726334280562, 'weight_class_2': 4.415383713791936}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:38,676] Trial 2619 finished with value: 0.9495988465208488 and parameters: {'weight_class_0': 0.3765792551865106, 'weight_class_1': 5.810744462422589, 'weight_class_2': 4.666344485771256}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:38,696] Trial 2620 finished with value: 0.9489883900532265 and parameters: {'weight_class_0': 0.2591521832469178, 'weight_class_1': 6.087897805218536, 'weight_class_2': 4.464209705877945}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:38,835] Trial 2621 finished with value: 0.9492267509497768 and parameters: {'weight_class_0': 0.2699706081029994, 'weight_class_1': 5.4713593298853285, 'weight_class_2': 4.393447477097562}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████                | 2631/3000 [01:04<00:10, 34.47it/s]

[I 2026-07-05 15:23:38,902] Trial 2622 finished with value: 0.9496343565216425 and parameters: {'weight_class_0': 0.3661518945482769, 'weight_class_1': 5.703967312530715, 'weight_class_2': 4.321209374997759}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:38,909] Trial 2623 finished with value: 0.9496103725940227 and parameters: {'weight_class_0': 0.36465698090291465, 'weight_class_1': 5.938097967738157, 'weight_class_2': 4.334713003037938}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:38,938] Trial 2624 finished with value: 0.8047401726675298 and parameters: {'weight_class_0': 0.3800260146026179, 'weight_class_1': 0.005984664567161301, 'weight_class_2': 4.47374977396378}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:38,939] Trial 2625 finished with value: 0.9496204160704279 and parameters: {'weight_class_0': 0.3553035017222526, 'weight_class_1': 5.188728998115935, 'weight_class_2': 4.5077475526553865}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:38,944] Trial 2626 finished with value: 0.9469101111782621 and parameters: {'weight_class_0': 0.3575293637847615, 'weight_class_1': 1.4913426481669934, 'weight_class_2': 4.792082298076836}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:38,991] Trial 2627 finished with value: 0.9496277713657607 and parameters: {'weight_class_0': 0.36161076610122145, 'weight_class_1': 5.080557624609731, 'weight_class_2': 4.686165652456351}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:39,032] Trial 2628 finished with value: 0.9496605970560476 and parameters: {'weight_class_0': 0.36897439454371334, 'weight_class_1': 5.204528839561433, 'weight_class_2': 4.645560195601045}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:39,038] Trial 2631 finished with value: 0.9495017459563325 and parameters: {'weight_class_0': 0.39808945795777095, 'weight_class_1': 5.0171978591079425, 'weight_class_2': 5.635088007178498}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:39,039] Trial 2629 finished with value: 0.9495997763485186 and parameters: {'weight_class_0': 0.3381672392123603, 'weight_class_1': 4.960172265998074, 'weight_class_2': 3.2129514975016273}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:39,065] Trial 2630 finished with value: 0.7686452305650353 and parameters: {'weight_class_0': 0.021630408678077594, 'weight_class_1': 0.0079232115303375, 'weight_class_2': 5.6879183501767}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏               | 2635/3000 [01:04<00:12, 30.32it/s]

[I 2026-07-05 15:23:39,067] Trial 2632 finished with value: 0.9493627086897997 and parameters: {'weight_class_0': 0.35378545249577875, 'weight_class_1': 5.080601243491732, 'weight_class_2': 5.5358512618504685}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:39,170] Trial 2633 finished with value: 0.9492307586905305 and parameters: {'weight_class_0': 0.33953390262180844, 'weight_class_1': 4.916825797326183, 'weight_class_2': 5.710041720742919}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:39,239] Trial 2634 finished with value: 0.9493165783798512 and parameters: {'weight_class_0': 0.4116762933014533, 'weight_class_1': 4.7976957325186795, 'weight_class_2': 3.057350032729724}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:39,316] Trial 2635 finished with value: 0.9438794794904637 and parameters: {'weight_class_0': 0.07455196843654431, 'weight_class_1': 4.836690142369861, 'weight_class_2': 3.0305637862828685}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌               | 2645/3000 [01:04<00:10, 33.74it/s]

[I 2026-07-05 15:23:39,324] Trial 2636 finished with value: 0.9474819511322711 and parameters: {'weight_class_0': 0.427804351196754, 'weight_class_1': 2.024531445561422, 'weight_class_2': 3.08338000981267}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:39,358] Trial 2638 finished with value: 0.9494812666378319 and parameters: {'weight_class_0': 0.4308252218621827, 'weight_class_1': 4.794503876409051, 'weight_class_2': 5.86342847082325}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:39,373] Trial 2639 finished with value: 0.9495871183173527 and parameters: {'weight_class_0': 0.3114701725479335, 'weight_class_1': 4.903352811681266, 'weight_class_2': 3.081570324380511}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:39,377] Trial 2637 finished with value: 0.9495488588896525 and parameters: {'weight_class_0': 0.43263763516087117, 'weight_class_1': 4.907451861273385, 'weight_class_2': 5.77825796246709}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:39,405] Trial 2640 finished with value: 0.9470695287162308 and parameters: {'weight_class_0': 0.4569111344788845, 'weight_class_1': 2.0674911431096685, 'weight_class_2': 3.1221359815190444}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:39,417] Trial 2641 finished with value: 0.9474152382690285 and parameters: {'weight_class_0': 0.43298674181644214, 'weight_class_1': 2.0115879552418927, 'weight_class_2': 3.1523162188238967}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:39,435] Trial 2644 finished with value: 0.9486676882797775 and parameters: {'weight_class_0': 0.5198085769549501, 'weight_class_1': 4.818006154374438, 'weight_class_2': 3.1159981955539595}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:39,441] Trial 2642 finished with value: 0.9477286643453676 and parameters: {'weight_class_0': 0.4453535826392219, 'weight_class_1': 2.1638875036165697, 'weight_class_2': 3.3594488310185433}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:39,447] Trial 2643 finished with value: 0.6642135077138257 and parameters: {'weight_class_0': 0.4434853807151391, 'weight_class_1': 0.0014949568251465155, 'weight_class_2': 3.1152476896047188}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:39,460] Trial 2645 finished with value: 0.9437519058095317 and parameters: {'weight_class_0': 0.07394643045030769, 'weight_class_1': 4.827420930135212, 'weight_class_2': 3.135635001134363}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊               | 2649/3000 [01:04<00:11, 29.38it/s]

[I 2026-07-05 15:23:39,511] Trial 2646 finished with value: 0.94736856178013 and parameters: {'weight_class_0': 0.08168146370149562, 'weight_class_1': 2.219793563606737, 'weight_class_2': 3.147998687822028}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:39,682] Trial 2647 finished with value: 0.9496258440154602 and parameters: {'weight_class_0': 0.44028090378503015, 'weight_class_1': 6.214082217405643, 'weight_class_2': 5.873099006014439}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:39,688] Trial 2648 finished with value: 0.9488113201780536 and parameters: {'weight_class_0': 0.5376643740480169, 'weight_class_1': 6.137642706248066, 'weight_class_2': 3.1969290929400556}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:39,741] Trial 2649 finished with value: 0.9491465267082441 and parameters: {'weight_class_0': 0.5278646717241597, 'weight_class_1': 6.085107030326707, 'weight_class_2': 3.6255130608245483}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  89%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏              | 2659/3000 [01:04<00:09, 34.91it/s]

[I 2026-07-05 15:23:39,775] Trial 2652 finished with value: 0.9488406774254102 and parameters: {'weight_class_0': 0.2209399123080539, 'weight_class_1': 6.081008319971129, 'weight_class_2': 3.855198546845653}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:39,780] Trial 2650 finished with value: 0.9492727909195214 and parameters: {'weight_class_0': 0.5278303818836584, 'weight_class_1': 6.524475122124621, 'weight_class_2': 3.748052298490414}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:39,786] Trial 2651 finished with value: 0.6578494412870484 and parameters: {'weight_class_0': 0.0010081686040905975, 'weight_class_1': 6.249211697005539, 'weight_class_2': 3.82400609601666}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:39,792] Trial 2653 finished with value: 0.9484478019582779 and parameters: {'weight_class_0': 0.19762137431983398, 'weight_class_1': 6.165590134236569, 'weight_class_2': 3.975724572281672}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:39,794] Trial 2654 finished with value: 0.9494962834879278 and parameters: {'weight_class_0': 0.29588318553210863, 'weight_class_1': 6.0995291714640825, 'weight_class_2': 3.9659050836822405}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:39,823] Trial 2656 finished with value: 0.9493710456215627 and parameters: {'weight_class_0': 0.5199220462130937, 'weight_class_1': 6.150382444366878, 'weight_class_2': 3.875632388409518}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:39,851] Trial 2655 finished with value: 0.7672031107477743 and parameters: {'weight_class_0': 0.19407497744405397, 'weight_class_1': 6.417217570166987, 'weight_class_2': 0.008252591807559967}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:39,857] Trial 2657 finished with value: 0.9484275960031633 and parameters: {'weight_class_0': 0.1914131747780029, 'weight_class_1': 6.0743525048497675, 'weight_class_2': 3.8724356076617026}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:39,885] Trial 2658 finished with value: 0.949425075720083 and parameters: {'weight_class_0': 0.28528802800468517, 'weight_class_1': 6.24543571199487, 'weight_class_2': 3.843979331413386}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:39,978] Trial 2659 finished with value: 0.9485075188930366 and parameters: {'weight_class_0': 0.20105520984068356, 'weight_class_1': 6.310081912856841, 'weight_class_2': 3.7983932520850305}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  89%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌              | 2666/3000 [01:05<00:10, 30.36it/s]

[I 2026-07-05 15:23:40,039] Trial 2660 finished with value: 0.9486665376769 and parameters: {'weight_class_0': 0.2182815764840966, 'weight_class_1': 6.103909671899876, 'weight_class_2': 4.138509763119684}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:40,087] Trial 2662 finished with value: 0.8723100626530425 and parameters: {'weight_class_0': 2.572080816117159, 'weight_class_1': 0.5632536578360876, 'weight_class_2': 5.620387605587185}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:40,097] Trial 2661 finished with value: 0.9495081479616975 and parameters: {'weight_class_0': 0.30426226026040776, 'weight_class_1': 6.1082195377155, 'weight_class_2': 3.9848384170872615}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:40,150] Trial 2663 finished with value: 0.9489695214271796 and parameters: {'weight_class_0': 0.30050277092311284, 'weight_class_1': 3.717095231705342, 'weight_class_2': 5.465528743017135}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:40,174] Trial 2664 finished with value: 0.9488922662994206 and parameters: {'weight_class_0': 0.3012467018337718, 'weight_class_1': 3.843442831666068, 'weight_class_2': 5.760869895718447}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:40,204] Trial 2666 finished with value: 0.7525580532417045 and parameters: {'weight_class_0': 0.2595651797589925, 'weight_class_1': 0.003773819336312727, 'weight_class_2': 5.789993663467081}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:40,225] Trial 2665 finished with value: 0.9488466700750554 and parameters: {'weight_class_0': 0.29910023510008377, 'weight_class_1': 3.6853777401317345, 'weight_class_2': 5.754608281924132}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  89%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊              | 2674/3000 [01:05<00:10, 32.26it/s]

[I 2026-07-05 15:23:40,245] Trial 2667 finished with value: 0.9488452237386271 and parameters: {'weight_class_0': 0.2925973669727102, 'weight_class_1': 3.6744598352909863, 'weight_class_2': 5.741910927382402}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:40,279] Trial 2669 finished with value: 0.9488605468128505 and parameters: {'weight_class_0': 0.32500439771226936, 'weight_class_1': 3.666152386945765, 'weight_class_2': 5.956341444430962}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:40,284] Trial 2670 finished with value: 0.9488570308545468 and parameters: {'weight_class_0': 0.2996176327182183, 'weight_class_1': 3.7108258911477163, 'weight_class_2': 5.780038391383697}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:40,303] Trial 2668 finished with value: 0.9488529847511757 and parameters: {'weight_class_0': 0.30825397242163416, 'weight_class_1': 3.6775672969620286, 'weight_class_2': 5.722716761606745}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:40,318] Trial 2671 finished with value: 0.9490757129546283 and parameters: {'weight_class_0': 0.31901714800800407, 'weight_class_1': 3.866883097806971, 'weight_class_2': 5.5067294965462805}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:40,379] Trial 2672 finished with value: 0.9488319686902721 and parameters: {'weight_class_0': 0.2935933406228726, 'weight_class_1': 3.8097237263489325, 'weight_class_2': 5.802167160514098}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:40,442] Trial 2673 finished with value: 0.9495153754185393 and parameters: {'weight_class_0': 0.31572413833737617, 'weight_class_1': 3.5335446825711334, 'weight_class_2': 2.5313975603398586}. Best is trial 2193 with value: 0.949738926310991.

[I 2026-07-05 15:23:40,468] Trial 2674 finished with value: 0.9495793355031457 and parameters: {'weight_class_0': 0.3110795565485613, 'weight_class_1': 3.8509077851869153, 'weight_class_2': 2.4951630232925024}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:40,528] Trial 2675 finished with value: 0.9476473773485717 and parameters: {'weight_class_0': 0.5354865558087304, 'weight_class_1': 3.7833567210508634, 'weight_class_2': 2.6485776224751203}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:40,563] Trial 2677 finished with value: 0.9476963976167067 and parameters: {'weight_class_0': 0.519506737366127, 'weight_class_1': 4.1023910752480015, 'weight_class_2': 2.5174043009649805}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:40,594] Trial 2676 finished with value: 0.8540783898173895 and parameters: {'weight_class_0': 0.015103555324883071, 'weight_class_1': 3.956294363825827, 'weight_class_2': 2.5207749305975247}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:40,612] Trial 2678 finished with value: 0.9488607352128405 and parameters: {'weight_class_0': 0.40544936115376284, 'weight_class_1': 4.074418393942315, 'weight_class_2': 2.6125823450065973}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:40,653] Trial 2680 finished with value: 0.9478625314959257 and parameters: {'weight_class_0': 0.5246358189564981, 'weight_class_1': 4.423181965274148, 'weight_class_2': 2.5364111168719523}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍             | 2687/3000 [01:05<00:09, 33.20it/s]

[I 2026-07-05 15:23:40,667] Trial 2679 finished with value: 0.9484593783445451 and parameters: {'weight_class_0': 0.4015267968481831, 'weight_class_1': 2.9122101033886003, 'weight_class_2': 2.4243857148358927}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:40,693] Trial 2681 finished with value: 0.940950354890783 and parameters: {'weight_class_0': 0.5281153326302543, 'weight_class_1': 3.0073218086408393, 'weight_class_2': 1.4488682242280648}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:40,714] Trial 2683 finished with value: 0.9490435796834374 and parameters: {'weight_class_0': 0.41667893342360357, 'weight_class_1': 2.929955805264735, 'weight_class_2': 4.48682699005188}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:40,715] Trial 2682 finished with value: 0.9478759181785343 and parameters: {'weight_class_0': 0.53030079439058, 'weight_class_1': 4.326900581907691, 'weight_class_2': 2.6345690914833653}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:40,762] Trial 2684 finished with value: 0.9412127112287054 and parameters: {'weight_class_0': 0.5069992976389727, 'weight_class_1': 2.8790473309065137, 'weight_class_2': 1.4127259034617934}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:40,803] Trial 2685 finished with value: 0.949402018706058 and parameters: {'weight_class_0': 0.5431276015181165, 'weight_class_1': 4.45975887813103, 'weight_class_2': 4.7336196274379905}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:40,817] Trial 2686 finished with value: 0.9494309653318829 and parameters: {'weight_class_0': 0.5288003401105705, 'weight_class_1': 4.472978639947474, 'weight_class_2': 4.782382126963538}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:40,888] Trial 2687 finished with value: 0.9489612145179462 and parameters: {'weight_class_0': 0.41955706581455315, 'weight_class_1': 2.828307360456898, 'weight_class_2': 4.818840480266126}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋             | 2694/3000 [01:06<00:09, 31.35it/s]

[I 2026-07-05 15:23:40,947] Trial 2689 finished with value: 0.9486926115275341 and parameters: {'weight_class_0': 0.41330697338678796, 'weight_class_1': 2.5939587395989476, 'weight_class_2': 4.8774280711522815}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:40,958] Trial 2688 finished with value: 0.9490868130383118 and parameters: {'weight_class_0': 0.40338777392049097, 'weight_class_1': 2.9339566585712475, 'weight_class_2': 4.84530951967093}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:40,974] Trial 2690 finished with value: 0.9487468869552891 and parameters: {'weight_class_0': 0.4199463937287521, 'weight_class_1': 2.7294209154724847, 'weight_class_2': 5.000755571634171}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:41,019] Trial 2691 finished with value: 0.948986642877597 and parameters: {'weight_class_0': 0.41884769849038, 'weight_class_1': 2.8609534612750838, 'weight_class_2': 4.866767039456398}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:41,052] Trial 2692 finished with value: 0.9488370055669361 and parameters: {'weight_class_0': 0.23145535115906102, 'weight_class_1': 4.825978884724565, 'weight_class_2': 4.745895586321807}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:41,075] Trial 2693 finished with value: 0.9496655530285217 and parameters: {'weight_class_0': 0.3744225379496398, 'weight_class_1': 5.005794394412263, 'weight_class_2': 4.714354544669706}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:41,142] Trial 2694 finished with value: 0.9489338510770341 and parameters: {'weight_class_0': 0.24324546119594714, 'weight_class_1': 5.008417787539193, 'weight_class_2': 4.828396369695323}. Best is trial 2193 with value: 0.949738926310991.

[I 2026-07-05 15:23:41,143] Trial 2695 finished with value: 0.9495887572775445 and parameters: {'weight_class_0': 0.43551615582320186, 'weight_class_1': 4.820354413899788, 'weight_class_2': 4.7240589713852446}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:41,161] Trial 2696 finished with value: 0.9497099038745266 and parameters: {'weight_class_0': 0.3910174150493804, 'weight_class_1': 5.04083717220432, 'weight_class_2': 4.580089565194774}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:41,214] Trial 2698 finished with value: 0.9496605216565945 and parameters: {'weight_class_0': 0.39276015172736756, 'weight_class_1': 5.501662004890934, 'weight_class_2': 4.843888564018077}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:41,225] Trial 2697 finished with value: 0.9488526913361314 and parameters: {'weight_class_0': 0.23950402249691063, 'weight_class_1': 5.131002619787564, 'weight_class_2': 4.860675406327671}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:41,249] Trial 2699 finished with value: 0.948822953871967 and parameters: {'weight_class_0': 0.24701943465122986, 'weight_class_1': 5.580856972774288, 'weight_class_2': 4.725721831326935}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:41,282] Trial 2700 finished with value: 0.9490475996725429 and parameters: {'weight_class_0': 0.24553311492030314, 'weight_class_1': 4.989298624104283, 'weight_class_2': 4.369833296547596}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:41,337] Trial 2701 finished with value: 0.9486249091280747 and parameters: {'weight_class_0': 0.359655231374999, 'weight_class_1': 4.7132184799595205, 'weight_class_2': 1.9858381274548544}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  90%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎            | 2708/3000 [01:06<00:09, 31.09it/s]

[I 2026-07-05 15:23:41,342] Trial 2702 finished with value: 0.9495301983113763 and parameters: {'weight_class_0': 0.24913265670951817, 'weight_class_1': 5.067793442754971, 'weight_class_2': 2.0260637293166557}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:41,372] Trial 2703 finished with value: 0.9490234725558917 and parameters: {'weight_class_0': 0.23400203370052802, 'weight_class_1': 4.906843318383422, 'weight_class_2': 4.147319892987872}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:41,440] Trial 2705 finished with value: 0.9483387867685447 and parameters: {'weight_class_0': 0.23686755317850186, 'weight_class_1': 5.384775485266601, 'weight_class_2': 6.082137906516156}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:41,471] Trial 2704 finished with value: 0.9486932267365266 and parameters: {'weight_class_0': 0.35718167821429136, 'weight_class_1': 5.185266778319906, 'weight_class_2': 2.0278196259679366}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:41,488] Trial 2706 finished with value: 0.9493211542537416 and parameters: {'weight_class_0': 0.24191323318232977, 'weight_class_1': 3.3159835210220034, 'weight_class_2': 3.8901240645791844}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:41,545] Trial 2707 finished with value: 0.9493655416607631 and parameters: {'weight_class_0': 0.22650017857893595, 'weight_class_1': 4.6642688973179345, 'weight_class_2': 3.372072491317583}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:41,546] Trial 2708 finished with value: 0.949343353922148 and parameters: {'weight_class_0': 0.234825222804468, 'weight_class_1': 5.053888592223418, 'weight_class_2': 3.4560287479208633}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  90%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋            | 2715/3000 [01:06<00:09, 30.32it/s]

[I 2026-07-05 15:23:41,592] Trial 2709 finished with value: 0.9494837896969589 and parameters: {'weight_class_0': 0.33991256121099855, 'weight_class_1': 3.272320817124292, 'weight_class_2': 3.3083837406708723}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:41,619] Trial 2711 finished with value: 0.9496702894048251 and parameters: {'weight_class_0': 0.3480080916477669, 'weight_class_1': 4.433061284509606, 'weight_class_2': 3.366753620069529}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:41,636] Trial 2712 finished with value: 0.9494896667849243 and parameters: {'weight_class_0': 0.3405874227081154, 'weight_class_1': 3.2831535179194673, 'weight_class_2': 3.2979516960414417}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:41,637] Trial 2710 finished with value: 0.9484798119343109 and parameters: {'weight_class_0': 0.33920450868625324, 'weight_class_1': 3.1956931587438127, 'weight_class_2': 1.8701599633355086}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:41,747] Trial 2715 finished with value: 0.9495555596453783 and parameters: {'weight_class_0': 0.3229807320137988, 'weight_class_1': 3.436197729997241, 'weight_class_2': 3.762227115599787}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:41,749] Trial 2714 finished with value: 0.9495315574087907 and parameters: {'weight_class_0': 0.3237075819395862, 'weight_class_1': 3.4497651258014166, 'weight_class_2': 3.398857319162443}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:41,753] Trial 2713 finished with value: 0.9495288187678804 and parameters: {'weight_class_0': 0.3354550370256818, 'weight_class_1': 3.4404096703197546, 'weight_class_2': 3.404305605363038}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉            | 2722/3000 [01:06<00:08, 31.28it/s]

[I 2026-07-05 15:23:41,814] Trial 2716 finished with value: 0.9494917419477099 and parameters: {'weight_class_0': 0.34791509258527187, 'weight_class_1': 3.2494813454899445, 'weight_class_2': 3.1827650539240366}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:41,854] Trial 2717 finished with value: 0.9494491028499424 and parameters: {'weight_class_0': 0.3419093522186954, 'weight_class_1': 3.3249250513278517, 'weight_class_2': 3.401202227966801}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:41,860] Trial 2718 finished with value: 0.9496313120706529 and parameters: {'weight_class_0': 0.34070749627272184, 'weight_class_1': 4.49181572682155, 'weight_class_2': 3.5296495195627937}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:41,903] Trial 2720 finished with value: 0.9494868375865821 and parameters: {'weight_class_0': 0.34358030651324634, 'weight_class_1': 3.3243636589542587, 'weight_class_2': 3.351816389139386}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:41,920] Trial 2719 finished with value: 0.9377003224891967 and parameters: {'weight_class_0': 0.34883386487427415, 'weight_class_1': 0.7068673112639772, 'weight_class_2': 3.2976674478648365}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:41,984] Trial 2722 finished with value: 0.9482741550124706 and parameters: {'weight_class_0': 0.1594219366295451, 'weight_class_1': 4.276502987390926, 'weight_class_2': 3.945908714528609}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:41,994] Trial 2721 finished with value: 0.9496323425872722 and parameters: {'weight_class_0': 0.2944222966724709, 'weight_class_1': 4.1235474930229135, 'weight_class_2': 3.944483295760926}. Best is trial 2193 with value: 0.949738926310991.

[I 2026-07-05 15:23:42,029] Trial 2723 finished with value: 0.9495930481271477 and parameters: {'weight_class_0': 0.2848232215172163, 'weight_class_1': 4.235313446408177, 'weight_class_2': 3.72689208161414}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:42,054] Trial 2724 finished with value: 0.9495345013768898 and parameters: {'weight_class_0': 0.28568155007742174, 'weight_class_1': 4.29283156609405, 'weight_class_2': 3.9243944503268775}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:42,143] Trial 2726 finished with value: 0.9491264631154005 and parameters: {'weight_class_0': 0.16164152918074198, 'weight_class_1': 2.3211907523804785, 'weight_class_2': 2.8308577958114736}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:42,145] Trial 2725 finished with value: 0.9494977336616098 and parameters: {'weight_class_0': 0.2867817056567411, 'weight_class_1': 4.086918611580797, 'weight_class_2': 4.055531540250418}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:42,177] Trial 2727 finished with value: 0.9480572006332646 and parameters: {'weight_class_0': 0.1479509699217496, 'weight_class_1': 4.334374675215826, 'weight_class_2': 4.005800749322888}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:42,191] Trial 2728 finished with value: 0.9494944123391159 and parameters: {'weight_class_0': 0.2861486651338343, 'weight_class_1': 4.37770579214204, 'weight_class_2': 4.041913344878942}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌           | 2736/3000 [01:07<00:07, 34.05it/s]

[I 2026-07-05 15:23:42,204] Trial 2730 finished with value: 0.9494686400379595 and parameters: {'weight_class_0': 0.27589721514303767, 'weight_class_1': 4.2297103195437415, 'weight_class_2': 3.9998223340967027}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:42,243] Trial 2729 finished with value: 0.9492739217139041 and parameters: {'weight_class_0': 0.26511861412586757, 'weight_class_1': 4.407001760234354, 'weight_class_2': 4.361504076949107}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:42,262] Trial 2731 finished with value: 0.8932289428791949 and parameters: {'weight_class_0': 0.4299400831442644, 'weight_class_1': 4.297428686987604, 'weight_class_2': 0.10371040683562735}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:42,286] Trial 2732 finished with value: 0.6679761611288164 and parameters: {'weight_class_0': 0.003320270519306832, 'weight_class_1': 2.482316308433025, 'weight_class_2': 4.0724226541215485}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:42,342] Trial 2733 finished with value: 0.9492056276184805 and parameters: {'weight_class_0': 0.27523254035741046, 'weight_class_1': 6.113675933986989, 'weight_class_2': 4.325612444087385}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:42,350] Trial 2735 finished with value: 0.8996051583341133 and parameters: {'weight_class_0': 0.44219689494885295, 'weight_class_1': 6.254417231198068, 'weight_class_2': 0.26284454320596345}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:42,380] Trial 2734 finished with value: 0.9496243591977249 and parameters: {'weight_class_0': 0.44175102259740634, 'weight_class_1': 6.055787556220628, 'weight_class_2': 4.187140306933495}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:42,436] Trial 2736 finished with value: 0.8850544394783824 and parameters: {'weight_class_0': 0.4459624767307385, 'weight_class_1': 2.504345733990756, 'weight_class_2': 0.033944105170331376}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉           | 2745/3000 [01:07<00:08, 31.55it/s]

[I 2026-07-05 15:23:42,516] Trial 2738 finished with value: 0.6521960617067951 and parameters: {'weight_class_0': 0.44844539558425095, 'weight_class_1': 0.0010039729017012405, 'weight_class_2': 2.7101629875888023}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:42,539] Trial 2737 finished with value: 0.9487556725590182 and parameters: {'weight_class_0': 0.470824511327915, 'weight_class_1': 6.162740992933389, 'weight_class_2': 2.725077562846761}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:42,565] Trial 2739 finished with value: 0.949132302363971 and parameters: {'weight_class_0': 0.4377812609242204, 'weight_class_1': 6.030976754203738, 'weight_class_2': 2.9007185682729792}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:42,608] Trial 2740 finished with value: 0.9489607833896825 and parameters: {'weight_class_0': 0.4619901371481765, 'weight_class_1': 6.317936929911744, 'weight_class_2': 2.8916362125946264}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:42,610] Trial 2741 finished with value: 0.8790914042371138 and parameters: {'weight_class_0': 0.033305148650176045, 'weight_class_1': 6.345845182904965, 'weight_class_2': 5.979818763841936}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:42,635] Trial 2742 finished with value: 0.6720635430201308 and parameters: {'weight_class_0': 0.44507130297799485, 'weight_class_1': 0.0019529712055203867, 'weight_class_2': 5.957112543077706}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:42,638] Trial 2744 finished with value: 0.9488573938130901 and parameters: {'weight_class_0': 0.47005100365659896, 'weight_class_1': 6.477068425375973, 'weight_class_2': 2.8003558561205275}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:42,670] Trial 2743 finished with value: 0.9496268197697444 and parameters: {'weight_class_0': 0.4454652965025077, 'weight_class_1': 6.297629841489595, 'weight_class_2': 5.925966477865666}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:42,694] Trial 2745 finished with value: 0.9489241783364765 and parameters: {'weight_class_0': 0.44987563944965314, 'weight_class_1': 5.959331698430566, 'weight_class_2': 2.7559310242135076}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏          | 2750/3000 [01:07<00:07, 33.84it/s]

[I 2026-07-05 15:23:42,713] Trial 2747 finished with value: 0.9107285614606889 and parameters: {'weight_class_0': 0.043339498337709594, 'weight_class_1': 6.012728677566353, 'weight_class_2': 5.9675542578935925}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:42,779] Trial 2746 finished with value: 0.9496635912938186 and parameters: {'weight_class_0': 0.4968377947425317, 'weight_class_1': 6.156755767747673, 'weight_class_2': 6.0486900074841}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:42,791] Trial 2748 finished with value: 0.9484652855810388 and parameters: {'weight_class_0': 0.5305216865653258, 'weight_class_1': 5.978512031852534, 'weight_class_2': 2.8203877735816185}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:42,904] Trial 2749 finished with value: 0.9493318424596578 and parameters: {'weight_class_0': 0.3818784860718208, 'weight_class_1': 6.38609879592974, 'weight_class_2': 6.1016979927218795}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:42,915] Trial 2751 finished with value: 0.9495295358645454 and parameters: {'weight_class_0': 0.5369456274715347, 'weight_class_1': 5.293537912280222, 'weight_class_2': 6.0774998941149825}. Best is trial 2193 with value: 0.949738926310991.

[I 2026-07-05 15:23:42,954] Trial 2750 finished with value: 0.9478077809508734 and parameters: {'weight_class_0': 0.20285993309986822, 'weight_class_1': 6.41034968875778, 'weight_class_2': 6.055169795671361}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:42,995] Trial 2752 finished with value: 0.9494577069212435 and parameters: {'weight_class_0': 0.5460659709194999, 'weight_class_1': 5.343709233435432, 'weight_class_2': 5.877875286362375}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:43,008] Trial 2753 finished with value: 0.9213911339010493 and parameters: {'weight_class_0': 0.045080695101235156, 'weight_class_1': 5.5036889875315484, 'weight_class_2': 5.26113632117281}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:43,047] Trial 2754 finished with value: 0.9481198923327515 and parameters: {'weight_class_0': 0.19146133428875944, 'weight_class_1': 5.182896228467291, 'weight_class_2': 5.121818031505792}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:43,076] Trial 2755 finished with value: 0.9496162991500322 and parameters: {'weight_class_0': 0.37992977163999764, 'weight_class_1': 5.39739887918114, 'weight_class_2': 5.143996037464748}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:43,080] Trial 2756 finished with value: 0.9495980074972298 and parameters: {'weight_class_0': 0.37664818402243017, 'weight_class_1': 4.966860222864221, 'weight_class_2': 4.965929531181728}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:43,092] Trial 2757 finished with value: 0.947996034951411 and parameters: {'weight_class_0': 0.18487656727794843, 'weight_class_1': 4.984817835584902, 'weight_class_2': 5.213813004595981}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:43,131] Trial 2758 finished with value: 0.9495058611238673 and parameters: {'weight_class_0': 0.5376431222468145, 'weight_class_1': 5.1273611951561815, 'weight_class_2': 5.2718427820849145}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊          | 2764/3000 [01:08<00:06, 34.71it/s]

[I 2026-07-05 15:23:43,163] Trial 2760 finished with value: 0.9481702292359176 and parameters: {'weight_class_0': 0.1989317782354452, 'weight_class_1': 5.116015939657021, 'weight_class_2': 5.236936107979678}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:43,181] Trial 2759 finished with value: 0.9481882206813218 and parameters: {'weight_class_0': 0.19151650806571408, 'weight_class_1': 5.2137374812160004, 'weight_class_2': 4.9661297423785}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:43,241] Trial 2761 finished with value: 0.9285293043206951 and parameters: {'weight_class_0': 0.1988281537296964, 'weight_class_1': 5.112324338001103, 'weight_class_2': 0.3304355268871048}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:43,286] Trial 2762 finished with value: 0.9494893816457397 and parameters: {'weight_class_0': 0.35801183709162826, 'weight_class_1': 5.15146405587129, 'weight_class_2': 5.080193047551376}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:43,340] Trial 2763 finished with value: 0.9495841238281105 and parameters: {'weight_class_0': 0.3805001064794167, 'weight_class_1': 5.057791717820852, 'weight_class_2': 5.121734091082383}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:43,352] Trial 2764 finished with value: 0.9493085762198848 and parameters: {'weight_class_0': 0.3813189585073951, 'weight_class_1': 3.403699421940558, 'weight_class_2': 4.929903755447083}. Best is trial 2193 with value: 0.949738926310991.

[I 2026-07-05 15:23:43,368] Trial 2765 finished with value: 0.9493944830979547 and parameters: {'weight_class_0': 0.3732793974239985, 'weight_class_1': 3.304189773687852, 'weight_class_2': 4.524474583478288}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:43,446] Trial 2766 finished with value: 0.9494564296926892 and parameters: {'weight_class_0': 0.3750405171442538, 'weight_class_1': 3.888259571034888, 'weight_class_2': 4.800582594658911}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:43,447] Trial 2767 finished with value: 0.9495424045659306 and parameters: {'weight_class_0': 0.3656728976970982, 'weight_class_1': 3.6570242297442643, 'weight_class_2': 4.1703886062252655}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:43,461] Trial 2768 finished with value: 0.9495117837682856 and parameters: {'weight_class_0': 0.366074973698191, 'weight_class_1': 3.6725534416183194, 'weight_class_2': 4.350646579722782}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:43,499] Trial 2769 finished with value: 0.9494818626140229 and parameters: {'weight_class_0': 0.37326524118556054, 'weight_class_1': 3.6172941518737476, 'weight_class_2': 4.0613162732018075}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:43,507] Trial 2770 finished with value: 0.9495387609467355 and parameters: {'weight_class_0': 0.36396380677544043, 'weight_class_1': 3.6822704482469146, 'weight_class_2': 4.292762852401061}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:43,555] Trial 2772 finished with value: 0.9495377730619192 and parameters: {'weight_class_0': 0.36004740803021434, 'weight_class_1': 3.697663501615485, 'weight_class_2': 4.226286219603811}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  93%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎         | 2777/3000 [01:08<00:07, 28.32it/s]

[I 2026-07-05 15:23:43,556] Trial 2771 finished with value: 0.9113882544281185 and parameters: {'weight_class_0': 0.37150196043253975, 'weight_class_1': 3.7715750194609745, 'weight_class_2': 0.3715692060226951}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:43,578] Trial 2773 finished with value: 0.9493424186795062 and parameters: {'weight_class_0': 0.3597289035531985, 'weight_class_1': 3.0263118359436145, 'weight_class_2': 4.343299111913829}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:43,628] Trial 2774 finished with value: 0.9495600269941051 and parameters: {'weight_class_0': 0.36340277257396486, 'weight_class_1': 3.6298007100649428, 'weight_class_2': 4.156527914513451}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:43,689] Trial 2775 finished with value: 0.9488008762357071 and parameters: {'weight_class_0': 0.558355583547738, 'weight_class_1': 3.8473410221179933, 'weight_class_2': 4.128682391531685}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:43,776] Trial 2776 finished with value: 0.9493743395199029 and parameters: {'weight_class_0': 0.2623379712296075, 'weight_class_1': 3.642087133096336, 'weight_class_2': 4.081894690090646}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:43,783] Trial 2777 finished with value: 0.9494255507152353 and parameters: {'weight_class_0': 0.2724024680529385, 'weight_class_1': 3.8291115929617074, 'weight_class_2': 4.092651788459895}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  93%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊         | 2787/3000 [01:08<00:05, 35.72it/s]

[I 2026-07-05 15:23:43,865] Trial 2778 finished with value: 0.8599490358795295 and parameters: {'weight_class_0': 4.240104115237726, 'weight_class_1': 2.4497705059040475, 'weight_class_2': 3.4244344556466446}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:43,871] Trial 2779 finished with value: 0.9466031125368138 and parameters: {'weight_class_0': 0.5507074007047019, 'weight_class_1': 2.476859989781855, 'weight_class_2': 3.1288360623717946}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:43,892] Trial 2781 finished with value: 0.9494406376400426 and parameters: {'weight_class_0': 0.2838839696797878, 'weight_class_1': 2.496817153240434, 'weight_class_2': 3.3111318592932903}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:43,905] Trial 2783 finished with value: 0.9494122799075488 and parameters: {'weight_class_0': 0.2734378741588679, 'weight_class_1': 2.645111083884844, 'weight_class_2': 3.4167258240857192}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:43,906] Trial 2780 finished with value: 0.9495878269151459 and parameters: {'weight_class_0': 0.26768881010255813, 'weight_class_1': 3.035510588185143, 'weight_class_2': 3.2062202911124236}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:43,907] Trial 2782 finished with value: 0.8040665572024953 and parameters: {'weight_class_0': 0.010811931054196632, 'weight_class_1': 3.057808998284851, 'weight_class_2': 3.3757246636570115}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:43,923] Trial 2784 finished with value: 0.8924733489349013 and parameters: {'weight_class_0': 0.2722857795888075, 'weight_class_1': 2.686400984416662, 'weight_class_2': 0.05616759603879678}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:43,958] Trial 2785 finished with value: 0.8586019780765479 and parameters: {'weight_class_0': 4.177506978933623, 'weight_class_1': 2.5395967502710053, 'weight_class_2': 3.0355969279133324}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:43,968] Trial 2786 finished with value: 0.9496381657893327 and parameters: {'weight_class_0': 0.26954731664626697, 'weight_class_1': 4.375147310817067, 'weight_class_2': 3.1626689017874594}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:43,975] Trial 2787 finished with value: 0.9495129969875968 and parameters: {'weight_class_0': 0.2666530577030084, 'weight_class_1': 2.592890487984211, 'weight_class_2': 2.300518301564259}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████         | 2793/3000 [01:09<00:07, 29.00it/s]

[I 2026-07-05 15:23:44,127] Trial 2789 finished with value: 0.9494405484112535 and parameters: {'weight_class_0': 0.2862709651915307, 'weight_class_1': 2.562976623687712, 'weight_class_2': 3.2643554727368236}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:44,130] Trial 2788 finished with value: 0.9453139196969979 and parameters: {'weight_class_0': 0.5482257534523062, 'weight_class_1': 2.9168117233493582, 'weight_class_2': 2.1476081724050142}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:44,217] Trial 2790 finished with value: 0.9496049799711294 and parameters: {'weight_class_0': 0.2868680813056375, 'weight_class_1': 4.4640899052744825, 'weight_class_2': 2.3495868440891927}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:44,239] Trial 2791 finished with value: 0.9466873131936543 and parameters: {'weight_class_0': 0.5497577936950644, 'weight_class_1': 4.349979801193507, 'weight_class_2': 2.2895046647764126}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:44,282] Trial 2792 finished with value: 0.9464616618778453 and parameters: {'weight_class_0': 0.5622500286108402, 'weight_class_1': 4.390733038951014, 'weight_class_2': 2.264720901338638}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:44,301] Trial 2793 finished with value: 0.9492870114583273 and parameters: {'weight_class_0': 0.46638225674073136, 'weight_class_1': 4.339527196777409, 'weight_class_2': 6.3170235366352765}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2193. Best value: 0.949739:  93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍        | 2801/3000 [01:09<00:05, 34.24it/s]

[I 2026-07-05 15:23:44,329] Trial 2795 finished with value: 0.949306932775209 and parameters: {'weight_class_0': 0.5335650413566476, 'weight_class_1': 4.307952387659067, 'weight_class_2': 6.05758461498543}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:44,331] Trial 2794 finished with value: 0.9468480037309571 and parameters: {'weight_class_0': 0.5451639938642259, 'weight_class_1': 4.337610005650563, 'weight_class_2': 2.314086528081956}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:44,332] Trial 2797 finished with value: 0.9497176316874931 and parameters: {'weight_class_0': 0.5224527983145597, 'weight_class_1': 6.460462308189041, 'weight_class_2': 6.137918276360886}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:44,344] Trial 2796 finished with value: 0.9497012324866051 and parameters: {'weight_class_0': 0.5389874297118981, 'weight_class_1': 6.509773586424794, 'weight_class_2': 6.190645675722148}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:44,395] Trial 2799 finished with value: 0.9478621735243431 and parameters: {'weight_class_0': 0.4781484112201319, 'weight_class_1': 6.597270346601091, 'weight_class_2': 2.2282387758000883}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:44,396] Trial 2798 finished with value: 0.9497046405577366 and parameters: {'weight_class_0': 0.5118990070012603, 'weight_class_1': 6.5769293183598725, 'weight_class_2': 6.0248684460002035}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:44,488] Trial 2801 finished with value: 0.9496932256998578 and parameters: {'weight_class_0': 0.5202350876864548, 'weight_class_1': 6.572864197954602, 'weight_class_2': 6.326729559649071}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:44,511] Trial 2800 finished with value: 0.9496767601408312 and parameters: {'weight_class_0': 0.5628875586485248, 'weight_class_1': 6.707673416668777, 'weight_class_2': 6.195984407744722}. Best is trial 2193 with value: 0.949738926310991.

Best trial: 2808. Best value: 0.94974:  94%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌        | 2808/3000 [01:09<00:06, 29.24it/s]

[I 2026-07-05 15:23:44,580] Trial 2802 finished with value: 0.9496237473183807 and parameters: {'weight_class_0': 0.5498315131471727, 'weight_class_1': 6.234039988937193, 'weight_class_2': 6.456207017587043}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:44,590] Trial 2803 finished with value: 0.9497346673246135 and parameters: {'weight_class_0': 0.5273705684267983, 'weight_class_1': 6.623745764639904, 'weight_class_2': 6.186848974132386}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:44,678] Trial 2804 finished with value: 0.9479464576247113 and parameters: {'weight_class_0': 0.2182943197388888, 'weight_class_1': 6.572592066115763, 'weight_class_2': 6.298979090682431}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:44,682] Trial 2805 finished with value: 0.9494544595590494 and parameters: {'weight_class_0': 0.43821014818669835, 'weight_class_1': 6.428896845640637, 'weight_class_2': 6.354420108504929}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:44,718] Trial 2807 finished with value: 0.9488848233351327 and parameters: {'weight_class_0': 0.3096443681554147, 'weight_class_1': 6.706217301004287, 'weight_class_2': 6.108542380540462}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:44,764] Trial 2806 finished with value: 0.9495719903393307 and parameters: {'weight_class_0': 0.44668108288555697, 'weight_class_1': 6.569012583329496, 'weight_class_2': 6.140988626353061}. Best is trial 2193 with value: 0.949738926310991.
[I 2026-07-05 15:23:44,767] Trial 2808 finished with value: 0.9497396954017296 and parameters: {'weight_class_0': 0.43487408463538746, 'weight_class_1': 5.488241343500694, 'weight_class_2': 5.056185904732619}. Best is trial 2808 with value: 0.9497396954017296.

Best trial: 2808. Best value: 0.94974:  94%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉        | 2815/3000 [01:09<00:05, 32.97it/s]

[I 2026-07-05 15:23:44,769] Trial 2809 finished with value: 0.9497198471146598 and parameters: {'weight_class_0': 0.4179820795144132, 'weight_class_1': 5.164358214379148, 'weight_class_2': 4.878603652077796}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:44,778] Trial 2810 finished with value: 0.9496948215475749 and parameters: {'weight_class_0': 0.4350442935546437, 'weight_class_1': 5.196147503952896, 'weight_class_2': 4.9973685487986295}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:44,819] Trial 2811 finished with value: 0.9496743051589268 and parameters: {'weight_class_0': 0.45755151173467484, 'weight_class_1': 5.271591534601222, 'weight_class_2': 5.014656842962303}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:44,838] Trial 2812 finished with value: 0.9496069824694118 and parameters: {'weight_class_0': 0.4651862595660394, 'weight_class_1': 5.33612806619536, 'weight_class_2': 4.898518591247436}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:44,845] Trial 2813 finished with value: 0.9497200356338054 and parameters: {'weight_class_0': 0.4326312141030482, 'weight_class_1': 5.269557712471499, 'weight_class_2': 4.935639788679318}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:44,930] Trial 2814 finished with value: 0.9496916479347696 and parameters: {'weight_class_0': 0.42090592015357836, 'weight_class_1': 5.457233052105605, 'weight_class_2': 4.761113904286312}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:44,961] Trial 2815 finished with value: 0.9496213893522744 and parameters: {'weight_class_0': 0.4231841384527322, 'weight_class_1': 5.051430456219891, 'weight_class_2': 4.548811036113228}. Best is trial 2808 with value: 0.9497396954017296.

Best trial: 2808. Best value: 0.94974:  94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏       | 2822/3000 [01:10<00:05, 29.84it/s]

[I 2026-07-05 15:23:45,012] Trial 2817 finished with value: 0.9496766346850133 and parameters: {'weight_class_0': 0.4224176872992556, 'weight_class_1': 5.467311183450335, 'weight_class_2': 5.03305173734972}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:45,019] Trial 2816 finished with value: 0.8793783298884845 and parameters: {'weight_class_0': 0.42364224942793033, 'weight_class_1': 0.05448776664322917, 'weight_class_2': 4.5583758178092015}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:45,088] Trial 2818 finished with value: 0.9496910373556086 and parameters: {'weight_class_0': 0.41799323673046845, 'weight_class_1': 5.280931728120304, 'weight_class_2': 4.969130453466336}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:45,136] Trial 2819 finished with value: 0.9496404816583648 and parameters: {'weight_class_0': 0.32516278058974873, 'weight_class_1': 4.608007733333855, 'weight_class_2': 3.935382377505814}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:45,142] Trial 2821 finished with value: 0.949609992679821 and parameters: {'weight_class_0': 0.4093020424820935, 'weight_class_1': 4.576118901963639, 'weight_class_2': 3.9719546617937}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:45,147] Trial 2820 finished with value: 0.9496656599287533 and parameters: {'weight_class_0': 0.3258551734666514, 'weight_class_1': 4.50017197855473, 'weight_class_2': 4.023394518862245}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:45,187] Trial 2822 finished with value: 0.9496832481781184 and parameters: {'weight_class_0': 0.426266090384683, 'weight_class_1': 5.062160741203437, 'weight_class_2': 4.794193576977711}. Best is trial 2808 with value: 0.9497396954017296.

[I 2026-07-05 15:23:45,227] Trial 2823 finished with value: 0.9496635614300731 and parameters: {'weight_class_0': 0.41473690349765824, 'weight_class_1': 4.740641165304016, 'weight_class_2': 4.607711597280842}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:45,252] Trial 2825 finished with value: 0.8732730651791879 and parameters: {'weight_class_0': 0.4099205403094255, 'weight_class_1': 0.0299559710671119, 'weight_class_2': 4.487039698917226}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:45,287] Trial 2824 finished with value: 0.9496261717579886 and parameters: {'weight_class_0': 0.40951214171704525, 'weight_class_1': 4.7917560087781546, 'weight_class_2': 4.364240719734787}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:45,292] Trial 2826 finished with value: 0.9495741376144721 and parameters: {'weight_class_0': 0.4181681579746109, 'weight_class_1': 4.569126529446871, 'weight_class_2': 4.514012603497457}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:45,315] Trial 2827 finished with value: 0.9496317869963201 and parameters: {'weight_class_0': 0.4073211517219467, 'weight_class_1': 4.625348624642242, 'weight_class_2': 4.645169994265825}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:45,369] Trial 2828 finished with value: 0.9495970741276643 and parameters: {'weight_class_0': 0.4061910441987884, 'weight_class_1': 4.582067868122466, 'weight_class_2': 4.168664062690557}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:45,411] Trial 2829 finished with value: 0.9496564099764325 and parameters: {'weight_class_0': 0.3834409071697265, 'weight_class_1': 4.378889551177667, 'weight_class_2': 4.273083758034912}. Best is trial 2808 with value: 0.9497396954017296.

Best trial: 2808. Best value: 0.94974:  94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊       | 2835/3000 [01:10<00:05, 29.78it/s]

[I 2026-07-05 15:23:45,440] Trial 2830 finished with value: 0.949690066327575 and parameters: {'weight_class_0': 0.3836756418846979, 'weight_class_1': 4.56546656024983, 'weight_class_2': 4.267476739229384}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:45,454] Trial 2831 finished with value: 0.949655687606222 and parameters: {'weight_class_0': 0.3962374622506706, 'weight_class_1': 4.54692217730813, 'weight_class_2': 4.490540689124752}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:45,548] Trial 2833 finished with value: 0.9496422410523002 and parameters: {'weight_class_0': 0.39963332441766425, 'weight_class_1': 4.506717047258709, 'weight_class_2': 4.330948666273191}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:45,559] Trial 2832 finished with value: 0.9495477650013152 and parameters: {'weight_class_0': 0.40223533590465593, 'weight_class_1': 4.324435153269203, 'weight_class_2': 4.153519772185518}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:45,580] Trial 2834 finished with value: 0.9496872536776256 and parameters: {'weight_class_0': 0.3801144737759258, 'weight_class_1': 4.525796379008355, 'weight_class_2': 4.229672177974891}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:45,648] Trial 2835 finished with value: 0.9496015793201728 and parameters: {'weight_class_0': 0.3731676014258009, 'weight_class_1': 4.366409721005441, 'weight_class_2': 4.511819244020059}. Best is trial 2808 with value: 0.9497396954017296.

Best trial: 2808. Best value: 0.94974:  95%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏      | 2843/3000 [01:10<00:04, 33.85it/s]

[I 2026-07-05 15:23:45,679] Trial 2839 finished with value: 0.9497131689622199 and parameters: {'weight_class_0': 0.34203688957422124, 'weight_class_1': 4.344415920017274, 'weight_class_2': 3.909669346341636}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:45,684] Trial 2836 finished with value: 0.9494646161551472 and parameters: {'weight_class_0': 0.34486968961359776, 'weight_class_1': 4.3402573522946755, 'weight_class_2': 5.104342745581617}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:45,689] Trial 2837 finished with value: 0.949653595660991 and parameters: {'weight_class_0': 0.34907443128470894, 'weight_class_1': 5.335445247591251, 'weight_class_2': 3.923979736679986}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:45,693] Trial 2838 finished with value: 0.949607261332682 and parameters: {'weight_class_0': 0.327227311382443, 'weight_class_1': 5.354039007277506, 'weight_class_2': 3.8819844859624646}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:45,743] Trial 2841 finished with value: 0.9494647082391015 and parameters: {'weight_class_0': 0.33875422806525546, 'weight_class_1': 5.393651640375847, 'weight_class_2': 5.07069890740206}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:45,747] Trial 2840 finished with value: 0.9493526560692834 and parameters: {'weight_class_0': 0.32655252781050836, 'weight_class_1': 5.447819597287694, 'weight_class_2': 5.191434191013089}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:45,783] Trial 2842 finished with value: 0.9492995603403015 and parameters: {'weight_class_0': 0.32966446897132856, 'weight_class_1': 5.022058464361364, 'weight_class_2': 5.225773502429258}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:45,818] Trial 2843 finished with value: 0.9493849479085054 and parameters: {'weight_class_0': 0.3285469529918089, 'weight_class_1': 5.521128365494852, 'weight_class_2': 4.990825365774414}. Best is trial 2808 with value: 0.9497396954017296.

Best trial: 2808. Best value: 0.94974:  95%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍      | 2851/3000 [01:11<00:04, 30.45it/s]

[I 2026-07-05 15:23:45,935] Trial 2844 finished with value: 0.9492120572443533 and parameters: {'weight_class_0': 0.32306822945568703, 'weight_class_1': 5.264351687691101, 'weight_class_2': 5.414812190717313}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:45,949] Trial 2845 finished with value: 0.9493146392696453 and parameters: {'weight_class_0': 0.3279411975734744, 'weight_class_1': 5.5641307804541595, 'weight_class_2': 5.260595699022}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:45,954] Trial 2846 finished with value: 0.9492994239797975 and parameters: {'weight_class_0': 0.3281281318788567, 'weight_class_1': 5.4715626426258215, 'weight_class_2': 5.340527275477261}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:46,033] Trial 2847 finished with value: 0.9493087335027551 and parameters: {'weight_class_0': 0.3284094513041744, 'weight_class_1': 5.554307731033009, 'weight_class_2': 5.356055086493066}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:46,043] Trial 2848 finished with value: 0.9496388537418289 and parameters: {'weight_class_0': 0.32628874648425776, 'weight_class_1': 3.723833048216491, 'weight_class_2': 3.5314274824337666}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:46,073] Trial 2849 finished with value: 0.9497116307807428 and parameters: {'weight_class_0': 0.3161683420651861, 'weight_class_1': 3.883439389973058, 'weight_class_2': 3.5539061495124913}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:46,106] Trial 2851 finished with value: 0.9496289149195559 and parameters: {'weight_class_0': 0.31811288202247684, 'weight_class_1': 3.758140560990924, 'weight_class_2': 3.4214212507540696}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:46,110] Trial 2850 finished with value: 0.9497186074417772 and parameters: {'weight_class_0': 0.2979037599954864, 'weight_class_1': 3.670989261670911, 'weight_class_2': 3.4912249716928274}. Best is trial 2808 with value: 0.9497396954017296.

Best trial: 2808. Best value: 0.94974:  95%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊      | 2857/3000 [01:11<00:04, 32.47it/s]

[I 2026-07-05 15:23:46,136] Trial 2853 finished with value: 0.9496815561702882 and parameters: {'weight_class_0': 0.3169458565288748, 'weight_class_1': 3.728328030871803, 'weight_class_2': 3.6045089726243726}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:46,137] Trial 2852 finished with value: 0.9497186691146909 and parameters: {'weight_class_0': 0.3056658031225722, 'weight_class_1': 3.9038020940820752, 'weight_class_2': 3.5675133857548205}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:46,189] Trial 2854 finished with value: 0.9497040225742941 and parameters: {'weight_class_0': 0.32035850217290396, 'weight_class_1': 3.8331398786979762, 'weight_class_2': 3.672082872276738}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:46,205] Trial 2855 finished with value: 0.9496027283328269 and parameters: {'weight_class_0': 0.307119875432436, 'weight_class_1': 3.7387740029239325, 'weight_class_2': 3.9497170065920244}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:46,300] Trial 2856 finished with value: 0.9489133461837884 and parameters: {'weight_class_0': 0.4834199534963474, 'weight_class_1': 3.656895355808371, 'weight_class_2': 3.4419453142819747}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:46,354] Trial 2857 finished with value: 0.9496672588656881 and parameters: {'weight_class_0': 0.29984122974005084, 'weight_class_1': 3.8635243004923847, 'weight_class_2': 3.759991348751008}. Best is trial 2808 with value: 0.9497396954017296.

Best trial: 2808. Best value: 0.94974:  96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████      | 2865/3000 [01:11<00:04, 29.40it/s]

[I 2026-07-05 15:23:46,388] Trial 2858 finished with value: 0.94903508929169 and parameters: {'weight_class_0': 0.483570339570961, 'weight_class_1': 3.708941178260685, 'weight_class_2': 3.557369621244221}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:46,451] Trial 2859 finished with value: 0.949411425450407 and parameters: {'weight_class_0': 0.46300357825948746, 'weight_class_1': 3.9443501134074244, 'weight_class_2': 3.656608556433859}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:46,481] Trial 2861 finished with value: 0.9493507826459132 and parameters: {'weight_class_0': 0.2328628632926227, 'weight_class_1': 3.2690867494294715, 'weight_class_2': 3.6810850807582116}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:46,488] Trial 2860 finished with value: 0.9495999801081597 and parameters: {'weight_class_0': 0.2199142054323097, 'weight_class_1': 3.6924202057352526, 'weight_class_2': 2.8100645927317203}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:46,506] Trial 2862 finished with value: 0.9495556344613633 and parameters: {'weight_class_0': 0.19845534968254086, 'weight_class_1': 3.080830023714777, 'weight_class_2': 2.715424181179029}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:46,519] Trial 2863 finished with value: 0.9496593997886292 and parameters: {'weight_class_0': 0.21914924788795095, 'weight_class_1': 3.0201615013254695, 'weight_class_2': 2.8236360922043526}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:46,540] Trial 2864 finished with value: 0.9496545819164882 and parameters: {'weight_class_0': 0.2447960240948872, 'weight_class_1': 2.8333564105093503, 'weight_class_2': 2.675823036769803}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:46,559] Trial 2865 finished with value: 0.949672078518684 and parameters: {'weight_class_0': 0.24087196238801353, 'weight_class_1': 3.09768109713894, 'weight_class_2': 2.6503025010819354}. Best is trial 2808 with value: 0.9497396954017296.

Best trial: 2808. Best value: 0.94974:  96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎     | 2871/3000 [01:11<00:04, 30.73it/s]

[I 2026-07-05 15:23:46,593] Trial 2867 finished with value: 0.9495570446117881 and parameters: {'weight_class_0': 0.22325713987344536, 'weight_class_1': 3.3884128998890177, 'weight_class_2': 2.862152002788951}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:46,612] Trial 2866 finished with value: 0.9496711238952208 and parameters: {'weight_class_0': 0.2304544238844744, 'weight_class_1': 3.120046752393408, 'weight_class_2': 2.7822563070711457}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:46,653] Trial 2868 finished with value: 0.9496671289302384 and parameters: {'weight_class_0': 0.22978860120805525, 'weight_class_1': 3.029076988498013, 'weight_class_2': 2.761513178256757}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:46,669] Trial 2869 finished with value: 0.9496604583876737 and parameters: {'weight_class_0': 0.22277281946316385, 'weight_class_1': 3.047001797066753, 'weight_class_2': 2.7014935468457955}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:46,770] Trial 2870 finished with value: 0.9496341554274665 and parameters: {'weight_class_0': 0.2255510793487727, 'weight_class_1': 3.0559696872383033, 'weight_class_2': 2.8924251201414233}. Best is trial 2808 with value: 0.9497396954017296.

Best trial: 2808. Best value: 0.94974:  96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋     | 2879/3000 [01:11<00:03, 32.18it/s]

[I 2026-07-05 15:23:46,846] Trial 2872 finished with value: 0.9496379126393117 and parameters: {'weight_class_0': 0.24715866601871356, 'weight_class_1': 3.070234705631628, 'weight_class_2': 3.106204187005279}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:46,855] Trial 2871 finished with value: 0.9497282035483906 and parameters: {'weight_class_0': 0.23588781028888814, 'weight_class_1': 2.9298551388276675, 'weight_class_2': 2.7113010660200483}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:46,876] Trial 2873 finished with value: 0.9496560387464159 and parameters: {'weight_class_0': 0.24657362719129683, 'weight_class_1': 3.016314700214072, 'weight_class_2': 3.0228509397468772}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:46,880] Trial 2875 finished with value: 0.9496264840548937 and parameters: {'weight_class_0': 0.2530797660563674, 'weight_class_1': 3.1645532591013104, 'weight_class_2': 3.201139780456569}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:46,936] Trial 2874 finished with value: 0.9493810519693763 and parameters: {'weight_class_0': 0.25019027223831936, 'weight_class_1': 2.137089405435243, 'weight_class_2': 2.951601925579018}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:46,953] Trial 2876 finished with value: 0.9495975599913294 and parameters: {'weight_class_0': 0.25633099844214075, 'weight_class_1': 3.058496869742808, 'weight_class_2': 3.126457245957164}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:46,959] Trial 2877 finished with value: 0.9491495205048438 and parameters: {'weight_class_0': 0.26636658842957783, 'weight_class_1': 1.9839014241496158, 'weight_class_2': 3.1106674484593397}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:47,008] Trial 2879 finished with value: 0.9495925185578349 and parameters: {'weight_class_0': 0.2723240387252733, 'weight_class_1': 3.2274984393056183, 'weight_class_2': 3.503914756109561}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:47,021] Trial 2878 finished with value: 0.9495708786024175 and parameters: {'weight_class_0': 0.26633690629063184, 'weight_class_1': 3.1187811656182474, 'weight_class_2': 3.3847977502527486}. Best is trial 2808 with value: 0.9497396954017296.

Best trial: 2808. Best value: 0.94974:  96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉     | 2884/3000 [01:12<00:03, 32.30it/s]

[I 2026-07-05 15:23:47,079] Trial 2881 finished with value: 0.8299695960701561 and parameters: {'weight_class_0': 0.28745943681309394, 'weight_class_1': 1.6274246620222996, 'weight_class_2': 0.004689956980669559}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:47,092] Trial 2880 finished with value: 0.9496142185901587 and parameters: {'weight_class_0': 0.259797330727546, 'weight_class_1': 3.2047289869180453, 'weight_class_2': 3.3139211859405826}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:47,115] Trial 2882 finished with value: 0.9491027881719906 and parameters: {'weight_class_0': 0.27075406078700875, 'weight_class_1': 2.1500492254405796, 'weight_class_2': 3.5739902531547485}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:47,201] Trial 2883 finished with value: 0.9489552306837422 and parameters: {'weight_class_0': 0.17199470030454028, 'weight_class_1': 2.6221175034885706, 'weight_class_2': 3.273087294974798}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:47,243] Trial 2884 finished with value: 0.9490378672082868 and parameters: {'weight_class_0': 0.1837469197862512, 'weight_class_1': 2.0703461756442665, 'weight_class_2': 3.1291205575930032}. Best is trial 2808 with value: 0.9497396954017296.

Best trial: 2808. Best value: 0.94974:  96%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏    | 2891/3000 [01:12<00:03, 29.91it/s]

[I 2026-07-05 15:23:47,288] Trial 2886 finished with value: 0.9486261608840864 and parameters: {'weight_class_0': 0.22047180659336932, 'weight_class_1': 1.3642099156384409, 'weight_class_2': 2.6320880701242437}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:47,301] Trial 2885 finished with value: 0.9488905919268594 and parameters: {'weight_class_0': 0.1175312760448118, 'weight_class_1': 2.5143991337664042, 'weight_class_2': 2.28576044561422}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:47,308] Trial 2887 finished with value: 0.9493209854798558 and parameters: {'weight_class_0': 0.1378804470265521, 'weight_class_1': 2.977033246934584, 'weight_class_2': 2.0603354308189163}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:47,346] Trial 2888 finished with value: 0.9493801582341521 and parameters: {'weight_class_0': 0.23116707459595195, 'weight_class_1': 3.1859618311030014, 'weight_class_2': 1.711813280340618}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:47,394] Trial 2889 finished with value: 0.9496687399977056 and parameters: {'weight_class_0': 0.14024752501180038, 'weight_class_1': 1.7426156720331794, 'weight_class_2': 1.710857874694}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:47,411] Trial 2890 finished with value: 0.9494242126848799 and parameters: {'weight_class_0': 0.19957272405116783, 'weight_class_1': 1.6948853924800669, 'weight_class_2': 2.1982794065894002}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:47,473] Trial 2891 finished with value: 0.9495381319558103 and parameters: {'weight_class_0': 0.1787175841155967, 'weight_class_1': 1.7929451867266677, 'weight_class_2': 1.9835265694525022}. Best is trial 2808 with value: 0.9497396954017296.

Best trial: 2808. Best value: 0.94974:  97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍    | 2896/3000 [01:12<00:03, 29.12it/s]

[I 2026-07-05 15:23:47,489] Trial 2892 finished with value: 0.9496574729523118 and parameters: {'weight_class_0': 0.1592792513626918, 'weight_class_1': 1.9323072955077425, 'weight_class_2': 1.9202713005638383}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:47,491] Trial 2893 finished with value: 0.9495728243819009 and parameters: {'weight_class_0': 0.15417793466206575, 'weight_class_1': 3.049925061856316, 'weight_class_2': 1.4880591849223197}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:47,574] Trial 2894 finished with value: 0.949616162049206 and parameters: {'weight_class_0': 0.16905776736707562, 'weight_class_1': 2.844376350150198, 'weight_class_2': 1.9796234306457041}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:47,581] Trial 2895 finished with value: 0.9497221876892548 and parameters: {'weight_class_0': 0.18155017682650157, 'weight_class_1': 2.2180378734070136, 'weight_class_2': 2.0620436851267243}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:47,641] Trial 2896 finished with value: 0.9494541656198514 and parameters: {'weight_class_0': 0.18452775728431797, 'weight_class_1': 1.7970768782445188, 'weight_class_2': 1.8340539713993973}. Best is trial 2808 with value: 0.9497396954017296.

Best trial: 2808. Best value: 0.94974:  97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊    | 2904/3000 [01:12<00:03, 28.31it/s]

[I 2026-07-05 15:23:47,722] Trial 2897 finished with value: 0.9493880637266763 and parameters: {'weight_class_0': 0.1618834065992757, 'weight_class_1': 1.6915464259583202, 'weight_class_2': 2.209085331526955}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:47,739] Trial 2898 finished with value: 0.9488839948707053 and parameters: {'weight_class_0': 0.15223920446641695, 'weight_class_1': 2.4497983985069256, 'weight_class_2': 0.9264850234142535}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:47,790] Trial 2899 finished with value: 0.9495121908759154 and parameters: {'weight_class_0': 0.1768071250852401, 'weight_class_1': 1.795272639293891, 'weight_class_2': 2.118804638941945}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:47,813] Trial 2900 finished with value: 0.9493805204184675 and parameters: {'weight_class_0': 0.16140934831049983, 'weight_class_1': 1.984720554714519, 'weight_class_2': 2.473680342911424}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:47,840] Trial 2901 finished with value: 0.9496636727071395 and parameters: {'weight_class_0': 0.15440771960219718, 'weight_class_1': 1.9535902065573805, 'weight_class_2': 1.9375169102395704}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:47,853] Trial 2902 finished with value: 0.9490667272215826 and parameters: {'weight_class_0': 0.15648779746005723, 'weight_class_1': 1.980927408338005, 'weight_class_2': 2.7560278465095505}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:47,866] Trial 2903 finished with value: 0.9496295579454106 and parameters: {'weight_class_0': 0.21857688125808744, 'weight_class_1': 2.4561844476065664, 'weight_class_2': 2.4056248825104025}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:47,880] Trial 2904 finished with value: 0.9493981821628887 and parameters: {'weight_class_0': 0.17301808600214952, 'weight_class_1': 2.0800898813563964, 'weight_class_2': 2.5128681063806715}. Best is trial 2808 with value: 0.9497396954017296.

Best trial: 2808. Best value: 0.94974:  97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████    | 2910/3000 [01:13<00:03, 29.58it/s]

[I 2026-07-05 15:23:47,921] Trial 2905 finished with value: 0.9496242365019892 and parameters: {'weight_class_0': 0.1873787707730585, 'weight_class_1': 2.6480625325789564, 'weight_class_2': 1.6526010155298563}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:48,003] Trial 2906 finished with value: 0.9495948702552752 and parameters: {'weight_class_0': 0.14981322213900636, 'weight_class_1': 1.7933708493723768, 'weight_class_2': 1.4933992828756628}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:48,060] Trial 2908 finished with value: 0.949587369627609 and parameters: {'weight_class_0': 0.14233103077588585, 'weight_class_1': 1.5531244123625445, 'weight_class_2': 1.4503751354839625}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:48,061] Trial 2907 finished with value: 0.9490261199757809 and parameters: {'weight_class_0': 0.19330950145117035, 'weight_class_1': 1.7989353470509761, 'weight_class_2': 1.3340101934084443}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:48,126] Trial 2909 finished with value: 0.9493118238673275 and parameters: {'weight_class_0': 0.1804931271746744, 'weight_class_1': 2.3176659417113425, 'weight_class_2': 2.9038286033693126}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:48,147] Trial 2910 finished with value: 0.94955020583778 and parameters: {'weight_class_0': 0.11190363352315037, 'weight_class_1': 1.9648561848232364, 'weight_class_2': 1.4213578042797594}. Best is trial 2808 with value: 0.9497396954017296.

Best trial: 2808. Best value: 0.94974:  97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎   | 2915/3000 [01:13<00:03, 26.72it/s]

[I 2026-07-05 15:23:48,153] Trial 2911 finished with value: 0.9496320900999092 and parameters: {'weight_class_0': 0.1580359413956872, 'weight_class_1': 2.0952528635856162, 'weight_class_2': 1.5938551272570236}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:48,256] Trial 2913 finished with value: 0.9496236174572684 and parameters: {'weight_class_0': 0.16779863926984484, 'weight_class_1': 2.2350488601430407, 'weight_class_2': 1.683533563129897}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:48,284] Trial 2912 finished with value: 0.9495884473218212 and parameters: {'weight_class_0': 0.17473938285780216, 'weight_class_1': 2.642878483633299, 'weight_class_2': 1.7325578000873276}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:48,327] Trial 2914 finished with value: 0.9495545389721665 and parameters: {'weight_class_0': 0.16969993871701758, 'weight_class_1': 1.6799808820102429, 'weight_class_2': 1.9043605507347137}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:48,336] Trial 2915 finished with value: 0.949028560210893 and parameters: {'weight_class_0': 0.16128815697173196, 'weight_class_1': 1.471981167485465, 'weight_class_2': 1.1136822758994418}. Best is trial 2808 with value: 0.9497396954017296.

Best trial: 2808. Best value: 0.94974:  97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌   | 2922/3000 [01:13<00:02, 28.72it/s]

[I 2026-07-05 15:23:48,341] Trial 2916 finished with value: 0.9490296625681172 and parameters: {'weight_class_0': 0.16966074262592895, 'weight_class_1': 1.3440984465601407, 'weight_class_2': 2.32293642426993}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:48,363] Trial 2917 finished with value: 0.9489272891335044 and parameters: {'weight_class_0': 0.1097061817012408, 'weight_class_1': 2.3055900950243124, 'weight_class_2': 2.1533425835762343}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:48,394] Trial 2918 finished with value: 0.9492425844392356 and parameters: {'weight_class_0': 0.170313368706621, 'weight_class_1': 1.3749360515796991, 'weight_class_2': 2.032438088436011}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:48,405] Trial 2919 finished with value: 0.949616650097199 and parameters: {'weight_class_0': 0.12952908054803855, 'weight_class_1': 2.3324371910689257, 'weight_class_2': 1.4892657109104894}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:48,489] Trial 2920 finished with value: 0.9496755491468734 and parameters: {'weight_class_0': 0.18037617525483882, 'weight_class_1': 2.1352416944292436, 'weight_class_2': 1.9837678695174574}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:48,524] Trial 2921 finished with value: 0.9486188645900139 and parameters: {'weight_class_0': 0.19435059342739097, 'weight_class_1': 2.506889335124109, 'weight_class_2': 1.0672956231879884}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:48,556] Trial 2923 finished with value: 0.9495190917929338 and parameters: {'weight_class_0': 0.12416770186722015, 'weight_class_1': 2.2285385081927185, 'weight_class_2': 1.6996561733173932}. Best is trial 2808 with value: 0.9497396954017296.

Best trial: 2808. Best value: 0.94974:  98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊   | 2927/3000 [01:13<00:02, 26.87it/s]

[I 2026-07-05 15:23:48,608] Trial 2922 finished with value: 0.9494646792464684 and parameters: {'weight_class_0': 0.19812350689538144, 'weight_class_1': 1.6923851430397647, 'weight_class_2': 1.7075621120233664}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:48,686] Trial 2924 finished with value: 0.9493611521631816 and parameters: {'weight_class_0': 0.09962082769922126, 'weight_class_1': 2.3257107044105925, 'weight_class_2': 1.347825269491223}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:48,709] Trial 2925 finished with value: 0.9489365456498494 and parameters: {'weight_class_0': 0.12876635817101298, 'weight_class_1': 1.8072680707200848, 'weight_class_2': 2.43444656975049}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:48,770] Trial 2926 finished with value: 0.9493627086897997 and parameters: {'weight_class_0': 0.14662323942872124, 'weight_class_1': 2.111122385858921, 'weight_class_2': 2.293660140958321}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:48,788] Trial 2929 finished with value: 0.9488332507507348 and parameters: {'weight_class_0': 0.19004772731305586, 'weight_class_1': 1.2665569057376385, 'weight_class_2': 2.3380723245050037}. Best is trial 2808 with value: 0.9497396954017296.

Best trial: 2808. Best value: 0.94974:  98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████   | 2934/3000 [01:13<00:02, 28.69it/s]

[I 2026-07-05 15:23:48,795] Trial 2927 finished with value: 0.9491933362011254 and parameters: {'weight_class_0': 0.1979619025934356, 'weight_class_1': 2.2082333534374596, 'weight_class_2': 1.3997136347467887}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:48,842] Trial 2928 finished with value: 0.9485368530510566 and parameters: {'weight_class_0': 0.20916061608079672, 'weight_class_1': 1.1968015077746095, 'weight_class_2': 1.9586764727491468}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:48,873] Trial 2930 finished with value: 0.9494132206606501 and parameters: {'weight_class_0': 0.13937773347640903, 'weight_class_1': 1.428151372246638, 'weight_class_2': 1.83007429347513}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:48,898] Trial 2933 finished with value: 0.9491605875806362 and parameters: {'weight_class_0': 0.20479664463924296, 'weight_class_1': 2.612502394650064, 'weight_class_2': 1.3776415836859126}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:48,926] Trial 2931 finished with value: 0.9495517280953583 and parameters: {'weight_class_0': 0.21077224838256647, 'weight_class_1': 2.315187509617106, 'weight_class_2': 2.121346632982645}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:48,977] Trial 2932 finished with value: 0.9495595627598169 and parameters: {'weight_class_0': 0.14290510278883287, 'weight_class_1': 2.348834442536633, 'weight_class_2': 1.9117812386264732}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:48,992] Trial 2934 finished with value: 0.9495026731469968 and parameters: {'weight_class_0': 0.210194807711268, 'weight_class_1': 2.2034605092671455, 'weight_class_2': 1.713203717178923}. Best is trial 2808 with value: 0.9497396954017296.

[I 2026-07-05 15:23:49,060] Trial 2936 finished with value: 0.9488004872204109 and parameters: {'weight_class_0': 0.21426477826331683, 'weight_class_1': 2.488858875956565, 'weight_class_2': 1.260468869395745}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:49,070] Trial 2935 finished with value: 0.9494919190892115 and parameters: {'weight_class_0': 0.208955903210768, 'weight_class_1': 2.0639229938136965, 'weight_class_2': 1.7045810386934297}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:49,152] Trial 2938 finished with value: 0.9494985372882873 and parameters: {'weight_class_0': 0.215471778540309, 'weight_class_1': 2.2876566215853154, 'weight_class_2': 2.302363450175393}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:49,165] Trial 2937 finished with value: 0.946682489209512 and parameters: {'weight_class_0': 0.23100734777973625, 'weight_class_1': 0.9120296613437749, 'weight_class_2': 1.9869635317515149}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:49,253] Trial 2940 finished with value: 0.9477498662145397 and parameters: {'weight_class_0': 0.21535471537094003, 'weight_class_1': 1.0221658527895716, 'weight_class_2': 2.426769873235766}. Best is trial 2808 with value: 0.9497396954017296.

[I 2026-07-05 15:23:49,267] Trial 2939 finished with value: 0.9495283586584903 and parameters: {'weight_class_0': 0.20877995350310682, 'weight_class_1': 2.0531442994708935, 'weight_class_2': 1.871469119562874}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:49,298] Trial 2941 finished with value: 0.949607629070008 and parameters: {'weight_class_0': 0.20697903551486718, 'weight_class_1': 2.416908061931219, 'weight_class_2': 1.9545994155209845}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:49,312] Trial 2942 finished with value: 0.9491567559847383 and parameters: {'weight_class_0': 0.24916456794097466, 'weight_class_1': 2.5471749203485383, 'weight_class_2': 1.7733611705612877}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:49,327] Trial 2943 finished with value: 0.9487751289668532 and parameters: {'weight_class_0': 0.12106340068703701, 'weight_class_1': 2.4878443408037074, 'weight_class_2': 2.539022405578727}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:49,378] Trial 2944 finished with value: 0.9474589661254096 and parameters: {'weight_class_0': 0.22643132993329654, 'weight_class_1': 1.0130768747494947, 'weight_class_2': 1.8130885097751206}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:49,384] Trial 2945 finished with value: 0.9496979509533156 and parameters: {'weight_class_0': 0.21601943070785767, 'weight_class_1': 2.5866196688936367, 'weight_class_2': 2.51977728430009}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:49,439] Trial 2946 finished with value: 0.9495532562562939 and parameters: {'weight_class_0': 0.261877660739278, 'weight_class_1': 2.6314720271307177, 'weight_class_2': 2.4941341767290566}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:49,482] Trial 2947 finished with value: 0.948947210306564 and parameters: {'weight_class_0': 0.12454776644067689, 'weight_class_1': 2.469818725570558, 'weight_class_2': 2.4394377901472977}. Best is trial 2808 with value: 0.9497396954017296.

Best trial: 2808. Best value: 0.94974:  98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉  | 2953/3000 [01:14<00:01, 25.96it/s]

[I 2026-07-05 15:23:49,528] Trial 2949 finished with value: 0.8976888077595958 and parameters: {'weight_class_0': 0.23900845361010759, 'weight_class_1': 0.1015311699437156, 'weight_class_2': 2.3388026211825195}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:49,536] Trial 2948 finished with value: 0.9468485269493637 and parameters: {'weight_class_0': 0.2325841061660046, 'weight_class_1': 0.9470241021966623, 'weight_class_2': 2.476297181315263}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:49,622] Trial 2950 finished with value: 0.9495740774757945 and parameters: {'weight_class_0': 0.2649967897242778, 'weight_class_1': 2.670767921588079, 'weight_class_2': 2.5895413675059484}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:49,664] Trial 2951 finished with value: 0.9495168082832265 and parameters: {'weight_class_0': 0.2589727478348198, 'weight_class_1': 2.6425961122369404, 'weight_class_2': 2.7443241296588674}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:49,684] Trial 2952 finished with value: 0.9495722371825215 and parameters: {'weight_class_0': 0.2716769153718263, 'weight_class_1': 2.9009485552082754, 'weight_class_2': 2.634421111882525}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:49,738] Trial 2953 finished with value: 0.9495169135874505 and parameters: {'weight_class_0': 0.2711206579008023, 'weight_class_1': 2.8221343796360263, 'weight_class_2': 2.767371167419739}. Best is trial 2808 with value: 0.9497396954017296.

Best trial: 2808. Best value: 0.94974:  99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏ | 2959/3000 [01:14<00:01, 28.18it/s]

[I 2026-07-05 15:23:49,746] Trial 2954 finished with value: 0.9484676711401251 and parameters: {'weight_class_0': 0.10869223941296238, 'weight_class_1': 1.5265921349174085, 'weight_class_2': 2.5753953627907893}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:49,798] Trial 2955 finished with value: 0.9495395512218869 and parameters: {'weight_class_0': 0.2762457714315411, 'weight_class_1': 2.9975700317706497, 'weight_class_2': 2.45997899952321}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:49,822] Trial 2956 finished with value: 0.9495009601729133 and parameters: {'weight_class_0': 0.2900686261282, 'weight_class_1': 2.929085507826164, 'weight_class_2': 2.4356447971954873}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:49,856] Trial 2957 finished with value: 0.9484729146803348 and parameters: {'weight_class_0': 0.12957220232435973, 'weight_class_1': 2.8662301595390973, 'weight_class_2': 3.113936746236102}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:49,880] Trial 2958 finished with value: 0.9497062165622498 and parameters: {'weight_class_0': 0.24658918019629533, 'weight_class_1': 3.0366045730074576, 'weight_class_2': 2.7213518259319196}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:49,899] Trial 2959 finished with value: 0.9496485357824204 and parameters: {'weight_class_0': 0.25768866441199345, 'weight_class_1': 2.968191401922962, 'weight_class_2': 2.744603500163756}. Best is trial 2808 with value: 0.9497396954017296.

Best trial: 2808. Best value: 0.94974:  99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍ | 2965/3000 [01:15<00:01, 26.52it/s]

[I 2026-07-05 15:23:49,995] Trial 2961 finished with value: 0.9496153261968558 and parameters: {'weight_class_0': 0.27777410010183967, 'weight_class_1': 3.412447606729123, 'weight_class_2': 2.784891823091039}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:50,001] Trial 2960 finished with value: 0.94958234868741 and parameters: {'weight_class_0': 0.26713281157023544, 'weight_class_1': 3.059364127813701, 'weight_class_2': 2.6793676390807195}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:50,045] Trial 2962 finished with value: 0.9495289299831757 and parameters: {'weight_class_0': 0.2839262632427443, 'weight_class_1': 3.0505228496640715, 'weight_class_2': 2.866954081133734}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:50,101] Trial 2963 finished with value: 0.9497107002537762 and parameters: {'weight_class_0': 0.2837745076983197, 'weight_class_1': 3.4752421521135446, 'weight_class_2': 3.152626207542077}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:50,137] Trial 2964 finished with value: 0.9483611834094949 and parameters: {'weight_class_0': 0.2909322201957014, 'weight_class_1': 1.5953477096670075, 'weight_class_2': 2.95878869590816}. Best is trial 2808 with value: 0.9497396954017296.

Best trial: 2808. Best value: 0.94974:  99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋ | 2971/3000 [01:15<00:01, 24.69it/s]

[I 2026-07-05 15:23:50,207] Trial 2965 finished with value: 0.9496227393229962 and parameters: {'weight_class_0': 0.29296923628177274, 'weight_class_1': 3.4052428015553264, 'weight_class_2': 3.1034389742756012}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:50,236] Trial 2966 finished with value: 0.9496609939785681 and parameters: {'weight_class_0': 0.29411877950657017, 'weight_class_1': 3.5757913006803332, 'weight_class_2': 3.114383861125814}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:50,294] Trial 2967 finished with value: 0.947424604175522 and parameters: {'weight_class_0': 0.09535603206805376, 'weight_class_1': 3.4042607250000563, 'weight_class_2': 3.1546753784908077}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:50,299] Trial 2968 finished with value: 0.9496209018515764 and parameters: {'weight_class_0': 0.30133686618871974, 'weight_class_1': 3.6887564984076415, 'weight_class_2': 3.0855337892939794}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:50,311] Trial 2969 finished with value: 0.9496604230858147 and parameters: {'weight_class_0': 0.29742078114157433, 'weight_class_1': 3.4283736746768714, 'weight_class_2': 3.3817092956309582}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:50,360] Trial 2971 finished with value: 0.9496640312926407 and parameters: {'weight_class_0': 0.27857097464620756, 'weight_class_1': 3.731284454634022, 'weight_class_2': 3.4852436362398707}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:50,378] Trial 2970 finished with value: 0.9497255341902692 and parameters: {'weight_class_0': 0.28728201669781767, 'weight_class_1': 3.533330532816831, 'weight_class_2': 3.2788124376929906}. Best is trial 2808 with value: 0.9497396954017296.

Best trial: 2808. Best value: 0.94974:  99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉ | 2977/3000 [01:15<00:00, 29.42it/s]

[I 2026-07-05 15:23:50,411] Trial 2972 finished with value: 0.9497155007010937 and parameters: {'weight_class_0': 0.30704600772009455, 'weight_class_1': 3.7382115241587934, 'weight_class_2': 3.4902509616759922}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:50,454] Trial 2973 finished with value: 0.9496735859807307 and parameters: {'weight_class_0': 0.3085229914359738, 'weight_class_1': 3.5978138831768396, 'weight_class_2': 3.558141731092866}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:50,456] Trial 2974 finished with value: 0.9495737603088167 and parameters: {'weight_class_0': 0.33672586040507013, 'weight_class_1': 3.715531589250176, 'weight_class_2': 3.4835540768818913}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:50,486] Trial 2975 finished with value: 0.9497195062006011 and parameters: {'weight_class_0': 0.3031537918771902, 'weight_class_1': 3.736200896251371, 'weight_class_2': 3.400983614929317}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:50,544] Trial 2976 finished with value: 0.9496461998930504 and parameters: {'weight_class_0': 0.32278365616878585, 'weight_class_1': 3.814040452381231, 'weight_class_2': 3.812952776520334}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:50,636] Trial 2977 finished with value: 0.9496559283868057 and parameters: {'weight_class_0': 0.314474283481731, 'weight_class_1': 3.774738404047268, 'weight_class_2': 3.428544294445968}. Best is trial 2808 with value: 0.9497396954017296.

Best trial: 2808. Best value: 0.94974:  99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎| 2984/3000 [01:15<00:00, 27.52it/s]

[I 2026-07-05 15:23:50,680] Trial 2978 finished with value: 0.949644672246098 and parameters: {'weight_class_0': 0.32298198410756873, 'weight_class_1': 3.742247827764971, 'weight_class_2': 3.678530978175103}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:50,717] Trial 2979 finished with value: 0.9497092494994875 and parameters: {'weight_class_0': 0.32462925540264764, 'weight_class_1': 3.9683777740517763, 'weight_class_2': 3.6984792747721245}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:50,736] Trial 2981 finished with value: 0.9497347186685955 and parameters: {'weight_class_0': 0.33554044843467495, 'weight_class_1': 4.126206411044075, 'weight_class_2': 3.8444044132699378}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:50,746] Trial 2980 finished with value: 0.9497009609581316 and parameters: {'weight_class_0': 0.3292192474456202, 'weight_class_1': 3.9872810830708345, 'weight_class_2': 3.6770866295724627}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:50,783] Trial 2982 finished with value: 0.949540253530734 and parameters: {'weight_class_0': 0.20097946338235606, 'weight_class_1': 2.1593730567075107, 'weight_class_2': 2.2654886685829556}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:50,833] Trial 2984 finished with value: 0.6687855474277323 and parameters: {'weight_class_0': 0.0022142029542742804, 'weight_class_1': 2.02744889056984, 'weight_class_2': 2.23706509802209}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:50,852] Trial 2983 finished with value: 0.9495233521441273 and parameters: {'weight_class_0': 0.1921954228850732, 'weight_class_1': 2.065816193112403, 'weight_class_2': 2.2805760095006598}. Best is trial 2808 with value: 0.9497396954017296.

Best trial: 2808. Best value: 0.94974: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌| 2990/3000 [01:16<00:00, 27.55it/s]

[I 2026-07-05 15:23:50,868] Trial 2986 finished with value: 0.9494355563555726 and parameters: {'weight_class_0': 0.21696021465270202, 'weight_class_1': 1.9169162045445418, 'weight_class_2': 2.34377588939595}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:50,889] Trial 2985 finished with value: 0.9496704606844607 and parameters: {'weight_class_0': 0.18102994205946119, 'weight_class_1': 2.239642170459803, 'weight_class_2': 2.175045970309914}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:50,958] Trial 2987 finished with value: 0.949626037733814 and parameters: {'weight_class_0': 0.19143418425427852, 'weight_class_1': 2.3736057162333974, 'weight_class_2': 2.4638959579175213}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:50,979] Trial 2988 finished with value: 0.9495455152925424 and parameters: {'weight_class_0': 0.18857937812899514, 'weight_class_1': 1.858288521092577, 'weight_class_2': 1.816348624626746}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:51,065] Trial 2990 finished with value: 0.9495335566991655 and parameters: {'weight_class_0': 0.19712755369859616, 'weight_class_1': 2.115993998385947, 'weight_class_2': 1.812857165575609}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:51,075] Trial 2989 finished with value: 0.9496280620666009 and parameters: {'weight_class_0': 0.17796485996152062, 'weight_class_1': 1.9845102239376957, 'weight_class_2': 1.9882921077626479}. Best is trial 2808 with value: 0.9497396954017296.

Best trial: 2808. Best value: 0.94974: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3000/3000 [01:16<00:00, 39.38it/s]

[I 2026-07-05 15:23:51,159] Trial 2993 finished with value: 0.9496772434625737 and parameters: {'weight_class_0': 0.18026106362764202, 'weight_class_1': 2.564529095039632, 'weight_class_2': 2.067348297654121}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:51,168] Trial 2991 finished with value: 0.9496347458342881 and parameters: {'weight_class_0': 0.19217855496299668, 'weight_class_1': 2.5864361401203593, 'weight_class_2': 1.8685749438380488}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:51,174] Trial 2992 finished with value: 0.9496118785010879 and parameters: {'weight_class_0': 0.1888982362300205, 'weight_class_1': 2.5546760188863034, 'weight_class_2': 2.029023564542855}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:51,181] Trial 2994 finished with value: 0.9495109450863684 and parameters: {'weight_class_0': 0.2082697549785295, 'weight_class_1': 2.1705386689061035, 'weight_class_2': 2.520778744808888}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:51,206] Trial 2996 finished with value: 0.9496482993912377 and parameters: {'weight_class_0': 0.20588755044785886, 'weight_class_1': 2.742685650459047, 'weight_class_2': 2.0352272731821217}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:51,213] Trial 2995 finished with value: 0.949632041133282 and parameters: {'weight_class_0': 0.22312509043862933, 'weight_class_1': 2.651154214927379, 'weight_class_2': 2.338076588001848}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:51,221] Trial 2997 finished with value: 0.9496659740065132 and parameters: {'weight_class_0': 0.22327222097646993, 'weight_class_1': 2.6690205174659885, 'weight_class_2': 2.452651040960766}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:51,234] Trial 2999 finished with value: 0.9495459346542466 and parameters: {'weight_class_0': 0.23329724095009358, 'weight_class_1': 2.584034019586965, 'weight_class_2': 2.907280123982666}. Best is trial 2808 with value: 0.9497396954017296.
[I 2026-07-05 15:23:51,241] Trial 2998 finished with value: 0.9496159867295848 and parameters: {'weight_class_0': 0.22817819853922539, 'weight_class_1': 2.678987866152244, 'weight_class_2': 2.0349671399280376}. Best is trial 2808 with value: 0.9497396954017296.

Best trial score:
0.9497396954017296

Best params:
{'weight_class_0': 0.43487408463538746, 'weight_class_1': 5.488241343500694, 'weight_class_2': 5.056185904732619}

In [8]:
weights = np.array([study.best_params['weight_class_0'], study.best_params['weight_class_1'], study.best_params['weight_class_2']])
weighted_probas = X_test.loc[:, ['xgb_0', 'xgb_1', 'xgb_2']].to_numpy() * weights

pred = np.argmax(weighted_probas, axis=1)

In [9]:
sub_labels = label_encoder.inverse_transform(pred)

# Submission

In [10]:
submission = pd.read_csv('../data/submission/sample_submission.csv')
submission['health_condition'] = sub_labels

submission.to_csv('../data/submission/submission_from_5.0.1_xgboost_submission.csv', index=False)

In [11]:
submission.head()

       id health_condition
0  690088        unhealthy
1  690089        unhealthy
2  690090          at-risk
3  690091          at-risk
4  690092        unhealthy