# Imports

In [1]:
import optuna
import pickle

import numpy as np
import pandas as pd

from tqdm import tqdm

from sklearn.metrics import balanced_accuracy_score
from sklearn.model_selection import StratifiedKFold, cross_val_predict

/home/junior/Documentos/GitHub/kaggle-competition-predicting-student-health/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Utils

In [2]:
def load_pickle(file_path):
    with open(file_path, 'rb') as file:
        return pickle.load(file)

# Loading Datasets

In [3]:
X_train = pd.read_parquet('../data/processed/X_train_stacking_layer_one_model_60_trials_data_type_raw.parquet')
y_train = pd.read_parquet('../data/interim/y_train.parquet')

X_test = pd.read_parquet('../data/processed/X_test_stacking_layer_one_model_60_trials_data_type_raw.parquet')

In [4]:
X_train.head()

     lgbm_0    lgbm_1    lgbm_2     xgb_0     xgb_1     xgb_2
0  0.006100  0.001768  0.992131  0.002865  0.000664  0.996471
1  0.996506  0.000362  0.003132  0.997038  0.000276  0.002686
2  0.003045  0.000595  0.996360  0.003027  0.000586  0.996388
3  0.004197  0.002691  0.993113  0.004076  0.002232  0.993692
4  0.993760  0.000033  0.006206  0.993914  0.000017  0.006069

In [5]:
X_test.head()

     lgbm_0    lgbm_1    lgbm_2     xgb_0     xgb_1     xgb_2
0  0.011001  0.003238  0.985761  0.011256  0.003791  0.984953
1  0.475895  0.002462  0.521643  0.427169  0.002915  0.569917
2  0.998080  0.001354  0.000566  0.999067  0.000780  0.000153
3  0.986703  0.000025  0.013272  0.987436  0.000011  0.012554
4  0.007872  0.001685  0.990443  0.009200  0.002601  0.988199

# Machine Learning

In [6]:
label_encoder = load_pickle('../artifacts/label_encoder.pkl')

In [45]:
def objective(trial, X, y):

    w0 = trial.suggest_float('weight_class_0', 0.001, 10.0, log=True)
    w1 = trial.suggest_float('weight_class_1', 0.001, 10.0, log=True)
    w2 = trial.suggest_float('weight_class_2', 0.001, 10.0, log=True)
    weights = np.array([w0, w1, w2])

    proba = X.loc[:, ['xgb_0', 'xgb_1', 'xgb_2']].to_numpy()
    
    weighted_probas = proba * weights
    pred = np.argmax(weighted_probas, axis=1)
    
    score = balanced_accuracy_score(y, pred)

    return score


study = optuna.create_study(
    direction="maximize", 
    sampler=optuna.samplers.TPESampler(seed=42), 
    pruner=optuna.pruners.MedianPruner(n_warmup_steps=2)
)

study.optimize(
    lambda trial: objective(trial, X_train, y_train.health_condition), 
    n_trials=510, 
    n_jobs=-1, 
    show_progress_bar=True
)

print("\nBest trial score:")
print(study.best_trial.value)

print("\nBest params:")
print(study.best_trial.params)

[I 2026-07-13 11:43:27,075] A new study created in memory with name: no-name-d3e0224f-2c6d-49a4-8030-0c1bb560942f
Best trial: 8. Best value: 0.947757:   2%|███▏                                                                                                                                    | 12/510 [00:00<00:13, 36.13it/s]

[I 2026-07-13 11:43:27,219] Trial 1 finished with value: 0.9430452914402774 and parameters: {'weight_class_0': 0.0016075222143598087, 'weight_class_1': 0.0253848319773283, 'weight_class_2': 0.005627120344500736}. Best is trial 1 with value: 0.9430452914402774.
[I 2026-07-13 11:43:27,228] Trial 0 finished with value: 0.5907115112485416 and parameters: {'weight_class_0': 0.0016742285327395947, 'weight_class_1': 0.01444149831283666, 'weight_class_2': 7.13747262649839}. Best is trial 1 with value: 0.9430452914402774.
[I 2026-07-13 11:43:27,233] Trial 6 finished with value: 0.7612862127240101 and parameters: {'weight_class_0': 3.041872028361448, 'weight_class_1': 0.10912677266983431, 'weight_class_2': 0.019875026729748644}. Best is trial 1 with value: 0.9430452914402774.
[I 2026-07-13 11:43:27,239] Trial 2 finished with value: 0.8848936602831922 and parameters: {'weight_class_0': 0.961924674874167, 'weight_class_1': 6.020594849351361, 'weight_class_2': 0.08156086693627719}. Best is trial 1 with value: 0.9430452914402774.
[I 2026-07-13 11:43:27,247] Trial 3 finished with value: 0.9325518124897458 and parameters: {'weight_class_0': 0.0035312763840410952, 'weight_class_1': 0.024447244046453646, 'weight_class_2': 0.007507854020310621}. Best is trial 1 with value: 0.9430452914402774.
[I 2026-07-13 11:43:27,248] Trial 5 finished with value: 0.894310526992137 and parameters: {'weight_class_0': 0.012250131535692342, 'weight_class_1': 0.1378578755039676, 'weight_class_2': 3.0973090749941843}. Best is trial 1 with value: 0.9430452914402774.
[I 2026-07-13 11:43:27,252] Trial 7 finished with value: 0.8990153327493311 and parameters: {'weight_class_0': 0.0035388575438955235, 'weight_class_1': 0.014574026128962954, 'weight_class_2': 0.7333898457271072}. Best is trial 1 with value: 0.9430452914402774.
[I 2026-07-13 11:43:27,254] Trial 4 finished with value: 0.9351053600709852 and parameters: {'weight_class_0': 0.002710978465383793, 'weight_class_1': 0.14244331698424195, 'weight_class_2': 0.007270736487971245}. Best is trial 1 with value: 0.9430452914402774.
[I 2026-07-13 11:43:27,258] Trial 8 finished with value: 0.9477571089202458 and parameters: {'weight_class_0': 0.0036955060291105767, 'weight_class_1': 0.06732986808582994, 'weight_class_2': 0.022382038421489905}. Best is trial 8 with value: 0.9477571089202458.
[I 2026-07-13 11:43:27,259] Trial 10 finished with value: 0.9380472552296872 and parameters: {'weight_class_0': 0.004814196020647075, 'weight_class_1': 0.3360727666312558, 'weight_class_2': 0.3731997748266642}. Best is trial 8 with value: 0.9477571089202458.
[I 2026-07-13 11:43:27,269] Trial 9 finished with value: 0.827318084840648 and parameters: {'weight_class_0': 0.0020173585162731327, 'weight_class_1': 0.6991912959058998, 'weight_class_2': 0.006759499710712877}. Best is trial 8 with value: 0.9477571089202458.
[I 2026-07-13 11:43:27,285] Trial 11 finished with value: 0.6254651717760762 and parameters: {'weight_class_0': 1.461272860203109, 'weight_class_1': 0.003921149143468289, 'weight_class_2': 0.02076741740906394}. Best is trial 8 with value: 0.9477571089202458.
[I 2026-07-13 11:43:27,366] Trial 12 finished with value: 0.6781558495140563 and parameters: {'weight_class_0': 0.0030198072847382263, 'weight_class_1': 2.696103696162559, 'weight_class_2': 0.008260652893158901}. Best is trial 8 with value: 0.9477571089202458.

Best trial: 8. Best value: 0.947757:   5%|██████▏                                                                                                                                 | 23/510 [00:00<00:10, 46.28it/s]

[I 2026-07-13 11:43:27,390] Trial 13 finished with value: 0.7983750863689852 and parameters: {'weight_class_0': 0.054377427830902304, 'weight_class_1': 0.0015840907955032605, 'weight_class_2': 0.0010328498873944188}. Best is trial 8 with value: 0.9477571089202458.
[I 2026-07-13 11:43:27,415] Trial 14 finished with value: 0.806874640290875 and parameters: {'weight_class_0': 0.03776543819646967, 'weight_class_1': 0.0017031659955336579, 'weight_class_2': 0.0010379722130668366}. Best is trial 8 with value: 0.9477571089202458.
[I 2026-07-13 11:43:27,435] Trial 15 finished with value: 0.8092279245494115 and parameters: {'weight_class_0': 0.02705846236845676, 'weight_class_1': 0.0011107662509510507, 'weight_class_2': 0.0013621351254984797}. Best is trial 8 with value: 0.9477571089202458.
[I 2026-07-13 11:43:27,449] Trial 16 finished with value: 0.8083498579949407 and parameters: {'weight_class_0': 0.03249710280090409, 'weight_class_1': 0.0014155591135849605, 'weight_class_2': 0.0012243844783606543}. Best is trial 8 with value: 0.9477571089202458.
[I 2026-07-13 11:43:27,464] Trial 17 finished with value: 0.8131258079096684 and parameters: {'weight_class_0': 0.03603889767468106, 'weight_class_1': 0.001867042374901129, 'weight_class_2': 0.0026502277400034034}. Best is trial 8 with value: 0.9477571089202458.
[I 2026-07-13 11:43:27,494] Trial 18 finished with value: 0.8079482673155495 and parameters: {'weight_class_0': 0.034727541498808384, 'weight_class_1': 0.001568613732004256, 'weight_class_2': 0.0011435051547633807}. Best is trial 8 with value: 0.9477571089202458.
[I 2026-07-13 11:43:27,510] Trial 20 finished with value: 0.8101906428982831 and parameters: {'weight_class_0': 0.03168792178212087, 'weight_class_1': 0.0015981245253567145, 'weight_class_2': 0.0013501257157467067}. Best is trial 8 with value: 0.9477571089202458.
[I 2026-07-13 11:43:27,513] Trial 19 finished with value: 0.8121950067203279 and parameters: {'weight_class_0': 0.032560050797885265, 'weight_class_1': 0.0016549505827136005, 'weight_class_2': 0.0020021363464886774}. Best is trial 8 with value: 0.9477571089202458.
[I 2026-07-13 11:43:27,531] Trial 21 finished with value: 0.804871532030309 and parameters: {'weight_class_0': 0.04327389924030493, 'weight_class_1': 0.0016388768957498428, 'weight_class_2': 0.0011571616253778915}. Best is trial 8 with value: 0.9477571089202458.
[I 2026-07-13 11:43:27,534] Trial 22 finished with value: 0.8587641112261556 and parameters: {'weight_class_0': 0.03080889670358452, 'weight_class_1': 0.0396772570603895, 'weight_class_2': 0.001127108114754191}. Best is trial 8 with value: 0.9477571089202458.
[I 2026-07-13 11:43:27,563] Trial 23 finished with value: 0.86845008007597 and parameters: {'weight_class_0': 0.02274384036651862, 'weight_class_1': 0.04126893135951512, 'weight_class_2': 0.0012873485757406331}. Best is trial 8 with value: 0.9477571089202458.

Best trial: 8. Best value: 0.947757:   7%|█████████▎                                                                                                                              | 35/510 [00:00<00:09, 50.98it/s]

[I 2026-07-13 11:43:27,564] Trial 24 finished with value: 0.836070459867935 and parameters: {'weight_class_0': 0.19846750618334388, 'weight_class_1': 0.04150154573771408, 'weight_class_2': 0.07633788556430156}. Best is trial 8 with value: 0.9477571089202458.
[I 2026-07-13 11:43:27,578] Trial 25 finished with value: 0.8502333567338464 and parameters: {'weight_class_0': 0.13521359937712743, 'weight_class_1': 0.04480311188587243, 'weight_class_2': 0.08843652175828767}. Best is trial 8 with value: 0.9477571089202458.
[I 2026-07-13 11:43:27,606] Trial 26 finished with value: 0.939525444345509 and parameters: {'weight_class_0': 0.01016339279012713, 'weight_class_1': 0.03275416523883383, 'weight_class_2': 0.0546905659855703}. Best is trial 8 with value: 0.9477571089202458.
[I 2026-07-13 11:43:27,626] Trial 27 finished with value: 0.9440968403385924 and parameters: {'weight_class_0': 0.009822394257123999, 'weight_class_1': 0.04165940577177041, 'weight_class_2': 0.07636108742547627}. Best is trial 8 with value: 0.9477571089202458.
[I 2026-07-13 11:43:27,636] Trial 28 finished with value: 0.9443163626711862 and parameters: {'weight_class_0': 0.011555217607638255, 'weight_class_1': 0.04843941296719687, 'weight_class_2': 0.20924183919806136}. Best is trial 8 with value: 0.9477571089202458.
[I 2026-07-13 11:43:27,664] Trial 29 finished with value: 0.9458168006783324 and parameters: {'weight_class_0': 0.00831795021791227, 'weight_class_1': 0.46536893027329473, 'weight_class_2': 0.16860757608825308}. Best is trial 8 with value: 0.9477571089202458.
[I 2026-07-13 11:43:27,701] Trial 30 finished with value: 0.945292364010593 and parameters: {'weight_class_0': 0.0077488209577955105, 'weight_class_1': 0.4580025051685813, 'weight_class_2': 0.1516508496189045}. Best is trial 8 with value: 0.9477571089202458.
[I 2026-07-13 11:43:27,710] Trial 31 finished with value: 0.9449148420571842 and parameters: {'weight_class_0': 0.008366748323400593, 'weight_class_1': 0.48786520547464113, 'weight_class_2': 0.2347124311257033}. Best is trial 8 with value: 0.9477571089202458.
[I 2026-07-13 11:43:27,724] Trial 32 finished with value: 0.9436905286476517 and parameters: {'weight_class_0': 0.007985571622729427, 'weight_class_1': 0.5227314862361775, 'weight_class_2': 0.21405551649192497}. Best is trial 8 with value: 0.9477571089202458.
[I 2026-07-13 11:43:27,738] Trial 33 finished with value: 0.9460687258593845 and parameters: {'weight_class_0': 0.007203576685055549, 'weight_class_1': 0.3341596658589365, 'weight_class_2': 0.26520154831421533}. Best is trial 8 with value: 0.9477571089202458.
[I 2026-07-13 11:43:27,765] Trial 34 finished with value: 0.9466235904764071 and parameters: {'weight_class_0': 0.0010236328797106082, 'weight_class_1': 0.0058077557899456215, 'weight_class_2': 0.01940220910419292}. Best is trial 8 with value: 0.9477571089202458.
[I 2026-07-13 11:43:27,771] Trial 35 finished with value: 0.9148707805178472 and parameters: {'weight_class_0': 0.011089995318907338, 'weight_class_1': 0.009964982881393587, 'weight_class_2': 0.22289263611670385}. Best is trial 8 with value: 0.9477571089202458.

Best trial: 8. Best value: 0.947757:   9%|████████████▌                                                                                                                           | 47/510 [00:00<00:08, 52.16it/s]

[I 2026-07-13 11:43:27,802] Trial 37 finished with value: 0.924943562485392 and parameters: {'weight_class_0': 0.006495475845665717, 'weight_class_1': 0.8647032004066779, 'weight_class_2': 0.26237280209479413}. Best is trial 8 with value: 0.9477571089202458.
[I 2026-07-13 11:43:27,804] Trial 36 finished with value: 0.9153932963192503 and parameters: {'weight_class_0': 0.007578776204383585, 'weight_class_1': 0.007142995306152096, 'weight_class_2': 0.1993977596220204}. Best is trial 8 with value: 0.9477571089202458.
[I 2026-07-13 11:43:27,836] Trial 38 finished with value: 0.7463432595735835 and parameters: {'weight_class_0': 0.001260364656856474, 'weight_class_1': 1.054800958535894, 'weight_class_2': 0.3440465031139611}. Best is trial 8 with value: 0.9477571089202458.
[I 2026-07-13 11:43:27,857] Trial 39 finished with value: 0.6915075258924431 and parameters: {'weight_class_0': 0.0011385804180933656, 'weight_class_1': 0.9408369688054047, 'weight_class_2': 1.2628761101620964}. Best is trial 8 with value: 0.9477571089202458.
[I 2026-07-13 11:43:27,872] Trial 40 finished with value: 0.6784894278195432 and parameters: {'weight_class_0': 0.0012758358939767608, 'weight_class_1': 1.7128259271223507, 'weight_class_2': 1.444039185803194}. Best is trial 8 with value: 0.9477571089202458.
[I 2026-07-13 11:43:27,881] Trial 41 finished with value: 0.6770931308959051 and parameters: {'weight_class_0': 0.0010962570007115677, 'weight_class_1': 1.479009376573389, 'weight_class_2': 1.3199336514772348}. Best is trial 8 with value: 0.9477571089202458.
[I 2026-07-13 11:43:27,906] Trial 42 finished with value: 0.6842233442896145 and parameters: {'weight_class_0': 0.0010286648344852878, 'weight_class_1': 1.1616114005283804, 'weight_class_2': 1.09655709730571}. Best is trial 8 with value: 0.9477571089202458.
[I 2026-07-13 11:43:27,931] Trial 43 finished with value: 0.6882258794876098 and parameters: {'weight_class_0': 0.001246143291568225, 'weight_class_1': 1.2581068890768352, 'weight_class_2': 1.2884882660780037}. Best is trial 8 with value: 0.9477571089202458.
[I 2026-07-13 11:43:27,945] Trial 44 finished with value: 0.678619943168418 and parameters: {'weight_class_0': 0.001225277891218383, 'weight_class_1': 1.5829901712966987, 'weight_class_2': 1.436267528319375}. Best is trial 8 with value: 0.9477571089202458.
[I 2026-07-13 11:43:27,968] Trial 45 finished with value: 0.6813578023501276 and parameters: {'weight_class_0': 0.0013429693387097548, 'weight_class_1': 1.5459381045922567, 'weight_class_2': 1.5664677155761948}. Best is trial 8 with value: 0.9477571089202458.
[I 2026-07-13 11:43:27,985] Trial 46 finished with value: 0.7353436936876196 and parameters: {'weight_class_0': 0.0011049702241870498, 'weight_class_1': 0.24972529387683054, 'weight_class_2': 1.131946284886883}. Best is trial 8 with value: 0.9477571089202458.
[I 2026-07-13 11:43:27,998] Trial 47 finished with value: 0.9353709312987425 and parameters: {'weight_class_0': 0.002342009503089978, 'weight_class_1': 0.23374351387062942, 'weight_class_2': 0.02630271426810966}. Best is trial 8 with value: 0.9477571089202458.

Best trial: 54. Best value: 0.948306:  12%|███████████████▌                                                                                                                       | 59/510 [00:01<00:08, 54.86it/s]

[I 2026-07-13 11:43:28,001] Trial 48 finished with value: 0.933570051753246 and parameters: {'weight_class_0': 0.0021077234491866307, 'weight_class_1': 0.22620547900302948, 'weight_class_2': 0.0296225453863126}. Best is trial 8 with value: 0.9477571089202458.
[I 2026-07-13 11:43:28,030] Trial 49 finished with value: 0.9374800426066461 and parameters: {'weight_class_0': 0.002124879784939725, 'weight_class_1': 0.19661734696485475, 'weight_class_2': 0.024385382244252324}. Best is trial 8 with value: 0.9477571089202458.
[I 2026-07-13 11:43:28,080] Trial 50 finished with value: 0.9398424084543381 and parameters: {'weight_class_0': 0.002237733058963179, 'weight_class_1': 0.18710127361061682, 'weight_class_2': 0.02408576845138941}. Best is trial 8 with value: 0.9477571089202458.
[I 2026-07-13 11:43:28,084] Trial 51 finished with value: 0.9364964522310117 and parameters: {'weight_class_0': 0.002429226337144435, 'weight_class_1': 0.2352181418562195, 'weight_class_2': 0.03548509787882142}. Best is trial 8 with value: 0.9477571089202458.
[I 2026-07-13 11:43:28,099] Trial 52 finished with value: 0.9445409780904909 and parameters: {'weight_class_0': 0.0041920433205112975, 'weight_class_1': 0.19485388169055684, 'weight_class_2': 0.021813698801620065}. Best is trial 8 with value: 0.9477571089202458.
[I 2026-07-13 11:43:28,110] Trial 53 finished with value: 0.941959726910557 and parameters: {'weight_class_0': 0.0024525343964540017, 'weight_class_1': 0.1759429163853421, 'weight_class_2': 0.01957985208708121}. Best is trial 8 with value: 0.9477571089202458.
[I 2026-07-13 11:43:28,130] Trial 54 finished with value: 0.9483058043649534 and parameters: {'weight_class_0': 0.0023173234829563507, 'weight_class_1': 0.08629556425326713, 'weight_class_2': 0.025295433822947706}. Best is trial 54 with value: 0.9483058043649534.
[I 2026-07-13 11:43:28,152] Trial 55 finished with value: 0.9398245039559843 and parameters: {'weight_class_0': 0.004784159694761352, 'weight_class_1': 0.11092012482292184, 'weight_class_2': 0.01360217361966069}. Best is trial 54 with value: 0.9483058043649534.
[I 2026-07-13 11:43:28,168] Trial 57 finished with value: 0.9423944879476339 and parameters: {'weight_class_0': 0.004201408761366473, 'weight_class_1': 0.08445198100252527, 'weight_class_2': 0.014018793461330633}. Best is trial 54 with value: 0.9483058043649534.
[I 2026-07-13 11:43:28,177] Trial 56 finished with value: 0.9375437101555675 and parameters: {'weight_class_0': 0.004092959010940234, 'weight_class_1': 0.08335607014672433, 'weight_class_2': 0.010369975610946491}. Best is trial 54 with value: 0.9483058043649534.
[I 2026-07-13 11:43:28,199] Trial 58 finished with value: 0.9346194612265157 and parameters: {'weight_class_0': 0.004610059959354171, 'weight_class_1': 0.09277016984095884, 'weight_class_2': 0.010153312367866905}. Best is trial 54 with value: 0.9483058043649534.
[I 2026-07-13 11:43:28,219] Trial 60 finished with value: 0.9019462893275052 and parameters: {'weight_class_0': 0.01757750453198103, 'weight_class_1': 0.07025493586852782, 'weight_class_2': 0.01326936901548534}. Best is trial 54 with value: 0.9483058043649534.

Best trial: 67. Best value: 0.948426:  14%|██████████████████▊                                                                                                                    | 71/510 [00:01<00:07, 55.94it/s]

[I 2026-07-13 11:43:28,222] Trial 59 finished with value: 0.9361692990846219 and parameters: {'weight_class_0': 0.0045550379256197775, 'weight_class_1': 0.07780978420025712, 'weight_class_2': 0.010788479729626588}. Best is trial 54 with value: 0.9483058043649534.
[I 2026-07-13 11:43:28,259] Trial 61 finished with value: 0.9069038916569703 and parameters: {'weight_class_0': 0.015617607810330534, 'weight_class_1': 0.44385794710761617, 'weight_class_2': 0.012195550405366174}. Best is trial 54 with value: 0.9483058043649534.
[I 2026-07-13 11:43:28,275] Trial 63 finished with value: 0.9372271626250646 and parameters: {'weight_class_0': 0.004935586105452586, 'weight_class_1': 0.09695060498836809, 'weight_class_2': 0.012334539750956374}. Best is trial 54 with value: 0.9483058043649534.
[I 2026-07-13 11:43:28,284] Trial 62 finished with value: 0.912021808103313 and parameters: {'weight_class_0': 0.014825963817396384, 'weight_class_1': 0.11079682753761295, 'weight_class_2': 0.01431653905106778}. Best is trial 54 with value: 0.9483058043649534.
[I 2026-07-13 11:43:28,310] Trial 65 finished with value: 0.7060166772312009 and parameters: {'weight_class_0': 0.006064160838238639, 'weight_class_1': 9.030263814455726, 'weight_class_2': 0.13178016579406693}. Best is trial 54 with value: 0.9483058043649534.
[I 2026-07-13 11:43:28,311] Trial 64 finished with value: 0.9049994210897037 and parameters: {'weight_class_0': 0.015079953811939578, 'weight_class_1': 0.0830932552265494, 'weight_class_2': 0.011558711652087158}. Best is trial 54 with value: 0.9483058043649534.
[I 2026-07-13 11:43:28,332] Trial 66 finished with value: 0.8380136393500784 and parameters: {'weight_class_0': 0.01661869541952111, 'weight_class_1': 6.123363932472551, 'weight_class_2': 0.1236650246725921}. Best is trial 54 with value: 0.9483058043649534.
[I 2026-07-13 11:43:28,349] Trial 67 finished with value: 0.9484257280300068 and parameters: {'weight_class_0': 0.015703705339719657, 'weight_class_1': 0.45183039753032844, 'weight_class_2': 0.1291953883995717}. Best is trial 67 with value: 0.9484257280300068.
[I 2026-07-13 11:43:28,386] Trial 68 finished with value: 0.8897637922142193 and parameters: {'weight_class_0': 0.015571810853202334, 'weight_class_1': 0.468641586031366, 'weight_class_2': 0.0046558638835509595}. Best is trial 67 with value: 0.9484257280300068.
[I 2026-07-13 11:43:28,393] Trial 69 finished with value: 0.9481926202651372 and parameters: {'weight_class_0': 0.01717765273492946, 'weight_class_1': 0.4798329143007867, 'weight_class_2': 0.12785504055002128}. Best is trial 67 with value: 0.9484257280300068.
[I 2026-07-13 11:43:28,427] Trial 70 finished with value: 0.8140963758942524 and parameters: {'weight_class_0': 0.006605499690628456, 'weight_class_1': 3.317753648273515, 'weight_class_2': 0.12910474123681212}. Best is trial 67 with value: 0.9484257280300068.
[I 2026-07-13 11:43:28,432] Trial 71 finished with value: 0.7903900435204374 and parameters: {'weight_class_0': 0.007097471795633298, 'weight_class_1': 4.600299534186437, 'weight_class_2': 0.5167355499205711}. Best is trial 67 with value: 0.9484257280300068.

Best trial: 67. Best value: 0.948426:  16%|█████████████████████▉                                                                                                                 | 83/510 [00:01<00:07, 54.11it/s]

[I 2026-07-13 11:43:28,442] Trial 72 finished with value: 0.8119220676265267 and parameters: {'weight_class_0': 9.513346791258336, 'weight_class_1': 0.5926948342858745, 'weight_class_2': 0.4039477137538581}. Best is trial 67 with value: 0.9484257280300068.
[I 2026-07-13 11:43:28,482] Trial 73 finished with value: 0.9136976741438531 and parameters: {'weight_class_0': 0.003113371401936462, 'weight_class_1': 0.017345080807912295, 'weight_class_2': 0.5528844693410142}. Best is trial 67 with value: 0.9484257280300068.
[I 2026-07-13 11:43:28,488] Trial 74 finished with value: 0.890949103289057 and parameters: {'weight_class_0': 0.0029815994914618683, 'weight_class_1': 0.3655107883415343, 'weight_class_2': 0.003814168562871764}. Best is trial 67 with value: 0.9484257280300068.
[I 2026-07-13 11:43:28,518] Trial 76 finished with value: 0.8096633960461888 and parameters: {'weight_class_0': 8.817683644081095, 'weight_class_1': 0.34368418655440564, 'weight_class_2': 0.5492006179001094}. Best is trial 67 with value: 0.9484257280300068.
[I 2026-07-13 11:43:28,526] Trial 75 finished with value: 0.879788165070714 and parameters: {'weight_class_0': 0.08238706444559889, 'weight_class_1': 0.3407933267150793, 'weight_class_2': 0.004664345978676046}. Best is trial 67 with value: 0.9484257280300068.
[I 2026-07-13 11:43:28,546] Trial 77 finished with value: 0.9069383877839178 and parameters: {'weight_class_0': 0.0030713904790499414, 'weight_class_1': 0.021948867107742766, 'weight_class_2': 0.6300943274936718}. Best is trial 67 with value: 0.9484257280300068.
[I 2026-07-13 11:43:28,575] Trial 79 finished with value: 0.775202139257639 and parameters: {'weight_class_0': 7.697602800368061, 'weight_class_1': 0.3360180489420198, 'weight_class_2': 0.059780457576350546}. Best is trial 67 with value: 0.9484257280300068.
[I 2026-07-13 11:43:28,582] Trial 78 finished with value: 0.8694893803138427 and parameters: {'weight_class_0': 0.0016947095245890714, 'weight_class_1': 0.022411459267729528, 'weight_class_2': 0.5668482939781998}. Best is trial 67 with value: 0.9484257280300068.
[I 2026-07-13 11:43:28,592] Trial 80 finished with value: 0.9319463561475989 and parameters: {'weight_class_0': 0.0030839793685277827, 'weight_class_1': 0.3478475707824759, 'weight_class_2': 0.048504182873254226}. Best is trial 67 with value: 0.9484257280300068.
[I 2026-07-13 11:43:28,617] Trial 81 finished with value: 0.9032511411655048 and parameters: {'weight_class_0': 0.06733602942260648, 'weight_class_1': 0.33656593923497297, 'weight_class_2': 0.04898636090712546}. Best is trial 67 with value: 0.9484257280300068.
[I 2026-07-13 11:43:28,646] Trial 82 finished with value: 0.9351948632666497 and parameters: {'weight_class_0': 0.024369337682188453, 'weight_class_1': 0.724396223409782, 'weight_class_2': 0.056842882901809604}. Best is trial 67 with value: 0.9484257280300068.
[I 2026-07-13 11:43:28,647] Trial 83 finished with value: 0.935070728522963 and parameters: {'weight_class_0': 0.021580160265990963, 'weight_class_1': 0.309445753765708, 'weight_class_2': 0.04841695924025001}. Best is trial 67 with value: 0.9484257280300068.

Best trial: 92. Best value: 0.949253:  19%|█████████████████████████▏                                                                                                             | 95/510 [00:01<00:07, 54.08it/s]

[I 2026-07-13 11:43:28,659] Trial 84 finished with value: 0.8254075323654219 and parameters: {'weight_class_0': 0.0016515964253024265, 'weight_class_1': 0.7604201919676978, 'weight_class_2': 0.04444085994267284}. Best is trial 67 with value: 0.9484257280300068.
[I 2026-07-13 11:43:28,676] Trial 85 finished with value: 0.8600766387115262 and parameters: {'weight_class_0': 0.02482630820168703, 'weight_class_1': 0.002827281435942277, 'weight_class_2': 0.04186906820621527}. Best is trial 67 with value: 0.9484257280300068.
[I 2026-07-13 11:43:28,718] Trial 87 finished with value: 0.8568108810073721 and parameters: {'weight_class_0': 0.026041721649442028, 'weight_class_1': 0.0030819959955031635, 'weight_class_2': 0.03818843097884843}. Best is trial 67 with value: 0.9484257280300068.
[I 2026-07-13 11:43:28,730] Trial 86 finished with value: 0.8696919016291442 and parameters: {'weight_class_0': 0.020642828798866086, 'weight_class_1': 0.003384804747195983, 'weight_class_2': 0.044227023086405005}. Best is trial 67 with value: 0.9484257280300068.
[I 2026-07-13 11:43:28,745] Trial 88 finished with value: 0.9481430460276551 and parameters: {'weight_class_0': 0.02115622642749044, 'weight_class_1': 0.6705176960548338, 'weight_class_2': 0.16323387659455657}. Best is trial 67 with value: 0.9484257280300068.
[I 2026-07-13 11:43:28,761] Trial 89 finished with value: 0.9454453179595825 and parameters: {'weight_class_0': 0.019856425357912728, 'weight_class_1': 0.6957578057559952, 'weight_class_2': 0.09787411837225568}. Best is trial 67 with value: 0.9484257280300068.
[I 2026-07-13 11:43:28,798] Trial 90 finished with value: 0.5239019662990668 and parameters: {'weight_class_0': 0.009192981270653973, 'weight_class_1': 0.0025305487408719, 'weight_class_2': 9.255046760191592}. Best is trial 67 with value: 0.9484257280300068.
[I 2026-07-13 11:43:28,811] Trial 91 finished with value: 0.9113012343694846 and parameters: {'weight_class_0': 0.00962964984497073, 'weight_class_1': 0.0073791563457829435, 'weight_class_2': 0.15992405918086575}. Best is trial 67 with value: 0.9484257280300068.
[I 2026-07-13 11:43:28,837] Trial 92 finished with value: 0.9492533230972754 and parameters: {'weight_class_0': 0.008390017290993658, 'weight_class_1': 0.144067582136571, 'weight_class_2': 0.15650922427715405}. Best is trial 92 with value: 0.9492533230972754.
[I 2026-07-13 11:43:28,843] Trial 93 finished with value: 0.9118787946145783 and parameters: {'weight_class_0': 0.008991360989399677, 'weight_class_1': 0.007049451374256657, 'weight_class_2': 0.09619269468230911}. Best is trial 92 with value: 0.9492533230972754.
[I 2026-07-13 11:43:28,848] Trial 94 finished with value: 0.9444549915195809 and parameters: {'weight_class_0': 0.009074410987808267, 'weight_class_1': 0.5782381160176352, 'weight_class_2': 0.16618630962765357}. Best is trial 92 with value: 0.9492533230972754.
[I 2026-07-13 11:43:28,884] Trial 95 finished with value: 0.9120165283022477 and parameters: {'weight_class_0': 0.009262147234302062, 'weight_class_1': 0.0073621237438586265, 'weight_class_2': 0.16258934626455637}. Best is trial 92 with value: 0.9492533230972754.

Best trial: 92. Best value: 0.949253:  21%|████████████████████████████                                                                                                          | 107/510 [00:02<00:07, 55.81it/s]

[I 2026-07-13 11:43:28,890] Trial 96 finished with value: 0.9073031964615653 and parameters: {'weight_class_0': 0.011016868816811944, 'weight_class_1': 0.007083313173390903, 'weight_class_2': 0.0992476969209351}. Best is trial 92 with value: 0.9492533230972754.
[I 2026-07-13 11:43:28,901] Trial 97 finished with value: 0.8685362507086413 and parameters: {'weight_class_0': 0.04370701866675245, 'weight_class_1': 0.005396711292264494, 'weight_class_2': 0.10033911617240013}. Best is trial 92 with value: 0.9492533230972754.
[I 2026-07-13 11:43:28,924] Trial 99 finished with value: 0.9412674111267375 and parameters: {'weight_class_0': 0.04532840913510389, 'weight_class_1': 2.1939394568755755, 'weight_class_2': 0.1747917536139195}. Best is trial 92 with value: 0.9492533230972754.
[I 2026-07-13 11:43:28,929] Trial 98 finished with value: 0.9047554261538421 and parameters: {'weight_class_0': 0.01227799362050214, 'weight_class_1': 0.007083885325086539, 'weight_class_2': 0.09277118671430706}. Best is trial 92 with value: 0.9492533230972754.
[I 2026-07-13 11:43:28,967] Trial 100 finished with value: 0.9103187290512947 and parameters: {'weight_class_0': 0.012666174936934756, 'weight_class_1': 2.1437693591805704, 'weight_class_2': 0.09730153772013811}. Best is trial 92 with value: 0.9492533230972754.
[I 2026-07-13 11:43:28,973] Trial 101 finished with value: 0.9132859354912175 and parameters: {'weight_class_0': 0.012092785397166725, 'weight_class_1': 1.964778953249531, 'weight_class_2': 0.10100318254396772}. Best is trial 92 with value: 0.9492533230972754.
[I 2026-07-13 11:43:28,990] Trial 102 finished with value: 0.9484628606056424 and parameters: {'weight_class_0': 0.01236273383854231, 'weight_class_1': 0.13712894424440003, 'weight_class_2': 0.2982348474106178}. Best is trial 92 with value: 0.9492533230972754.
[I 2026-07-13 11:43:29,016] Trial 103 finished with value: 0.8496130229266993 and parameters: {'weight_class_0': 0.45786245559457733, 'weight_class_1': 0.14936234487928213, 'weight_class_2': 0.29396056717700514}. Best is trial 92 with value: 0.9492533230972754.
[I 2026-07-13 11:43:29,039] Trial 104 finished with value: 0.8378891793019733 and parameters: {'weight_class_0': 0.40420369285993724, 'weight_class_1': 0.1360123919809983, 'weight_class_2': 0.07037014854079604}. Best is trial 92 with value: 0.9492533230972754.
[I 2026-07-13 11:43:29,046] Trial 105 finished with value: 0.9449013582065259 and parameters: {'weight_class_0': 0.012631628748704202, 'weight_class_1': 0.05999264667727452, 'weight_class_2': 0.30052048470765286}. Best is trial 92 with value: 0.9492533230972754.
[I 2026-07-13 11:43:29,068] Trial 106 finished with value: 0.8603844313691237 and parameters: {'weight_class_0': 0.3464371258478117, 'weight_class_1': 0.15426815671890676, 'weight_class_2': 0.28853033100829006}. Best is trial 92 with value: 0.9492533230972754.
[I 2026-07-13 11:43:29,077] Trial 107 finished with value: 0.8547223721230633 and parameters: {'weight_class_0': 0.3566577631438991, 'weight_class_1': 0.13996051821115588, 'weight_class_2': 0.2561006585184112}. Best is trial 92 with value: 0.9492533230972754.

Best trial: 113. Best value: 0.949459:  23%|███████████████████████████████                                                                                                      | 119/510 [00:02<00:07, 54.84it/s]

[I 2026-07-13 11:43:29,100] Trial 108 finished with value: 0.9486608012007404 and parameters: {'weight_class_0': 0.01304806897524955, 'weight_class_1': 0.14577607033526518, 'weight_class_2': 0.28254812122877226}. Best is trial 92 with value: 0.9492533230972754.
[I 2026-07-13 11:43:29,112] Trial 109 finished with value: 0.9466000518950871 and parameters: {'weight_class_0': 0.005807414673330653, 'weight_class_1': 0.13369100429201497, 'weight_class_2': 0.2816425892206177}. Best is trial 92 with value: 0.9492533230972754.
[I 2026-07-13 11:43:29,154] Trial 110 finished with value: 0.9469409200265425 and parameters: {'weight_class_0': 0.006069249138794297, 'weight_class_1': 0.1504165881731779, 'weight_class_2': 0.2731485335671641}. Best is trial 92 with value: 0.9492533230972754.
[I 2026-07-13 11:43:29,158] Trial 111 finished with value: 0.9409883473879529 and parameters: {'weight_class_0': 0.01963537596694899, 'weight_class_1': 0.06133233933830032, 'weight_class_2': 0.3852221635825917}. Best is trial 92 with value: 0.9492533230972754.
[I 2026-07-13 11:43:29,174] Trial 112 finished with value: 0.9457313976702282 and parameters: {'weight_class_0': 0.0054116800778067605, 'weight_class_1': 0.12623185535761267, 'weight_class_2': 0.30638424149378024}. Best is trial 92 with value: 0.9492533230972754.
[I 2026-07-13 11:43:29,192] Trial 113 finished with value: 0.9494592046349655 and parameters: {'weight_class_0': 0.01866141961780416, 'weight_class_1': 0.26841587072461276, 'weight_class_2': 0.24643442907286134}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:29,216] Trial 114 finished with value: 0.9376378790731481 and parameters: {'weight_class_0': 0.006259987933211644, 'weight_class_1': 0.27956035689127073, 'weight_class_2': 0.0178236533945693}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:29,243] Trial 115 finished with value: 0.9456759904920657 and parameters: {'weight_class_0': 0.005445157537351606, 'weight_class_1': 0.2679917478338086, 'weight_class_2': 0.20430212165159958}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:29,257] Trial 116 finished with value: 0.935884031727875 and parameters: {'weight_class_0': 0.0036564796870268454, 'weight_class_1': 0.054721460440994664, 'weight_class_2': 0.41620976321673403}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:29,282] Trial 117 finished with value: 0.9421348866974256 and parameters: {'weight_class_0': 0.005775171562233192, 'weight_class_1': 0.05283654202947445, 'weight_class_2': 0.4385980008547104}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:29,286] Trial 118 finished with value: 0.9417580128512602 and parameters: {'weight_class_0': 0.005841950788933335, 'weight_class_1': 0.03109137069470541, 'weight_class_2': 0.36025781950751473}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:29,299] Trial 119 finished with value: 0.9433953754532304 and parameters: {'weight_class_0': 0.00658300830430407, 'weight_class_1': 0.27578447290910285, 'weight_class_2': 0.44953227331321316}. Best is trial 113 with value: 0.9494592046349655.

Best trial: 113. Best value: 0.949459:  25%|█████████████████████████████████▉                                                                                                   | 130/510 [00:02<00:07, 52.18it/s]

[I 2026-07-13 11:43:29,323] Trial 120 finished with value: 0.9413041189266892 and parameters: {'weight_class_0': 0.003837244142630994, 'weight_class_1': 0.2606984935740835, 'weight_class_2': 0.2032247919448629}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:29,344] Trial 121 finished with value: 0.9383600275010863 and parameters: {'weight_class_0': 0.005529731341103372, 'weight_class_1': 0.2607870955654602, 'weight_class_2': 0.016955554286452394}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:29,366] Trial 122 finished with value: 0.884591753059014 and parameters: {'weight_class_0': 0.001522173710589099, 'weight_class_1': 0.03138172678541873, 'weight_class_2': 0.4418509322548984}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:29,387] Trial 123 finished with value: 0.9451149076381896 and parameters: {'weight_class_0': 0.033464725490331776, 'weight_class_1': 0.17807431547483496, 'weight_class_2': 0.20764257417974993}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:29,400] Trial 124 finished with value: 0.9329058512662916 and parameters: {'weight_class_0': 0.0035908989572887673, 'weight_class_1': 0.17743941312993453, 'weight_class_2': 0.4349947657902794}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:29,416] Trial 125 finished with value: 0.9104786482469814 and parameters: {'weight_class_0': 0.03205357150604794, 'weight_class_1': 0.17189679259865626, 'weight_class_2': 0.03120894453425507}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:29,430] Trial 126 finished with value: 0.9438517529682754 and parameters: {'weight_class_0': 0.01411127216788143, 'weight_class_1': 0.10361240435381291, 'weight_class_2': 0.8371170189509168}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:29,464] Trial 127 finished with value: 0.9458091597880257 and parameters: {'weight_class_0': 0.029701825092079692, 'weight_class_1': 0.16966956051162416, 'weight_class_2': 0.8171553859888624}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:29,497] Trial 128 finished with value: 0.9418320803647244 and parameters: {'weight_class_0': 0.032810930485101086, 'weight_class_1': 0.17420193827580474, 'weight_class_2': 0.13229669995858379}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:29,523] Trial 129 finished with value: 0.9481437495864213 and parameters: {'weight_class_0': 0.007624880799266797, 'weight_class_1': 0.18075934672638974, 'weight_class_2': 0.24396504670912803}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:29,525] Trial 131 finished with value: 0.9334879411275346 and parameters: {'weight_class_0': 0.007413787038139792, 'weight_class_1': 0.19285655005991795, 'weight_class_2': 0.9258981222921147}. Best is trial 113 with value: 0.9494592046349655.

Best trial: 113. Best value: 0.949459:  28%|█████████████████████████████████████                                                                                                | 142/510 [00:02<00:06, 55.19it/s]

[I 2026-07-13 11:43:29,532] Trial 130 finished with value: 0.9461619190649816 and parameters: {'weight_class_0': 0.030228530799399342, 'weight_class_1': 0.17962126733685124, 'weight_class_2': 0.8146625486442762}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:29,555] Trial 132 finished with value: 0.9422926778963264 and parameters: {'weight_class_0': 0.029439987611838775, 'weight_class_1': 0.11288689473831585, 'weight_class_2': 0.9039394974010326}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:29,564] Trial 133 finished with value: 0.9347440454525895 and parameters: {'weight_class_0': 0.007341187259984717, 'weight_class_1': 0.11881205949355182, 'weight_class_2': 0.8745204287419454}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:29,588] Trial 134 finished with value: 0.9094448904855005 and parameters: {'weight_class_0': 0.007872300617032446, 'weight_class_1': 0.4348301153141142, 'weight_class_2': 0.008240042597163042}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:29,595] Trial 135 finished with value: 0.9483251953514543 and parameters: {'weight_class_0': 0.017282476306668283, 'weight_class_1': 0.41414451648139305, 'weight_class_2': 0.12488668205119201}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:29,624] Trial 136 finished with value: 0.9494241252832891 and parameters: {'weight_class_0': 0.007547448736269802, 'weight_class_1': 0.12419874783153838, 'weight_class_2': 0.12438115078604678}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:29,630] Trial 137 finished with value: 0.9145537922284355 and parameters: {'weight_class_0': 0.007953696221331262, 'weight_class_1': 0.11423796212514443, 'weight_class_2': 0.008191006641851573}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:29,664] Trial 138 finished with value: 0.8956598317783563 and parameters: {'weight_class_0': 0.018578965752851166, 'weight_class_1': 0.40295681126717714, 'weight_class_2': 0.0070459417394871295}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:29,687] Trial 139 finished with value: 0.8971523083647924 and parameters: {'weight_class_0': 0.01778390763133927, 'weight_class_1': 0.4258027876710912, 'weight_class_2': 0.00778260216850849}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:29,707] Trial 140 finished with value: 0.8872786564133021 and parameters: {'weight_class_0': 0.0019108233912115773, 'weight_class_1': 0.40669207401358953, 'weight_class_2': 0.2426037376665345}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:29,729] Trial 142 finished with value: 0.9494037399608537 and parameters: {'weight_class_0': 0.018034591974015846, 'weight_class_1': 0.2249703554178703, 'weight_class_2': 0.23026343704827745}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:29,732] Trial 141 finished with value: 0.9197166034588437 and parameters: {'weight_class_0': 0.018446419176503272, 'weight_class_1': 0.06896854804328438, 'weight_class_2': 2.6240289879169927}. Best is trial 113 with value: 0.9494592046349655.

Best trial: 113. Best value: 0.949459:  30%|████████████████████████████████████████▏                                                                                            | 154/510 [00:02<00:06, 54.03it/s]

[I 2026-07-13 11:43:29,755] Trial 143 finished with value: 0.9043448324669057 and parameters: {'weight_class_0': 0.018061721047877767, 'weight_class_1': 0.21834215389804335, 'weight_class_2': 4.0175059954005965}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:29,776] Trial 144 finished with value: 0.9481092645112006 and parameters: {'weight_class_0': 0.018090559690211446, 'weight_class_1': 0.22188067522954502, 'weight_class_2': 0.12147836028119331}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:29,798] Trial 146 finished with value: 0.8834708730688545 and parameters: {'weight_class_0': 0.0169255669239781, 'weight_class_1': 0.07170449156038874, 'weight_class_2': 4.261298298820712}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:29,802] Trial 145 finished with value: 0.9481378813332456 and parameters: {'weight_class_0': 0.018335817951977047, 'weight_class_1': 0.2231868794594566, 'weight_class_2': 0.12454291537381222}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:29,833] Trial 147 finished with value: 0.9482904908073978 and parameters: {'weight_class_0': 0.016831921199013777, 'weight_class_1': 0.21914827064789333, 'weight_class_2': 0.11639317739831595}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:29,870] Trial 148 finished with value: 0.9440854760156044 and parameters: {'weight_class_0': 0.014153494444549173, 'weight_class_1': 0.897721271574539, 'weight_class_2': 0.1297675203896431}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:29,876] Trial 149 finished with value: 0.9493625219973872 and parameters: {'weight_class_0': 0.010706805919685355, 'weight_class_1': 0.22062882641247494, 'weight_class_2': 0.11746523675300921}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:29,882] Trial 150 finished with value: 0.8780081139510619 and parameters: {'weight_class_0': 0.010607177434242918, 'weight_class_1': 0.0010198304043341766, 'weight_class_2': 0.06938343852280346}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:29,896] Trial 151 finished with value: 0.9494193970149509 and parameters: {'weight_class_0': 0.01045736071614767, 'weight_class_1': 0.2115038559672456, 'weight_class_2': 0.140506997408325}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:29,908] Trial 152 finished with value: 0.9447205435582143 and parameters: {'weight_class_0': 0.015069490788168605, 'weight_class_1': 0.5547389389270355, 'weight_class_2': 0.06990662879964347}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:29,940] Trial 154 finished with value: 0.9468926519446837 and parameters: {'weight_class_0': 0.013920409487878604, 'weight_class_1': 0.6395900757641944, 'weight_class_2': 0.12230087622192622}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:29,944] Trial 153 finished with value: 0.9472760158077413 and parameters: {'weight_class_0': 0.013708914517388914, 'weight_class_1': 0.5960750015928402, 'weight_class_2': 0.12500914788796305}. Best is trial 113 with value: 0.9494592046349655.

Best trial: 165. Best value: 0.949515:  33%|███████████████████████████████████████████▎                                                                                         | 166/510 [00:03<00:06, 55.23it/s]

[I 2026-07-13 11:43:29,973] Trial 156 finished with value: 0.9472467145075408 and parameters: {'weight_class_0': 0.022204353519684066, 'weight_class_1': 0.5436834796404479, 'weight_class_2': 0.12718280420419134}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:29,979] Trial 155 finished with value: 0.9473251475662496 and parameters: {'weight_class_0': 0.013702112033319499, 'weight_class_1': 0.569855409106892, 'weight_class_2': 0.11593793228461209}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:30,015] Trial 157 finished with value: 0.9470083789313423 and parameters: {'weight_class_0': 0.02297055705141766, 'weight_class_1': 0.2209728280360967, 'weight_class_2': 0.13001428303276982}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:30,025] Trial 158 finished with value: 0.9475073791773436 and parameters: {'weight_class_0': 0.021778446975785147, 'weight_class_1': 0.21754750255562344, 'weight_class_2': 0.13378430024589952}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:30,040] Trial 159 finished with value: 0.9476759379975878 and parameters: {'weight_class_0': 0.022523756952178016, 'weight_class_1': 0.22048090681119567, 'weight_class_2': 0.14374517356770755}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:30,044] Trial 160 finished with value: 0.9494457091810401 and parameters: {'weight_class_0': 0.011062453606529467, 'weight_class_1': 0.22436343524655666, 'weight_class_2': 0.14790000119517943}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:30,084] Trial 162 finished with value: 0.949403478622342 and parameters: {'weight_class_0': 0.011271195320932613, 'weight_class_1': 0.2357390150278791, 'weight_class_2': 0.1514899703313715}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:30,087] Trial 161 finished with value: 0.9484291322396227 and parameters: {'weight_class_0': 0.011469472022267526, 'weight_class_1': 0.090731372849577, 'weight_class_2': 0.1488831024214542}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:30,114] Trial 163 finished with value: 0.9484435047965265 and parameters: {'weight_class_0': 0.02162495330573198, 'weight_class_1': 0.20064154002525586, 'weight_class_2': 0.17645865757740772}. Best is trial 113 with value: 0.9494592046349655.
[I 2026-07-13 11:43:30,122] Trial 164 finished with value: 0.9494951519078109 and parameters: {'weight_class_0': 0.011120108257802111, 'weight_class_1': 0.2214012092149432, 'weight_class_2': 0.1736948509154114}. Best is trial 164 with value: 0.9494951519078109.
[I 2026-07-13 11:43:30,139] Trial 165 finished with value: 0.9495150983621875 and parameters: {'weight_class_0': 0.010764577273262708, 'weight_class_1': 0.21218257047004452, 'weight_class_2': 0.16484923573197413}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:30,166] Trial 167 finished with value: 0.9491035390175236 and parameters: {'weight_class_0': 0.011073258500423773, 'weight_class_1': 0.2990507481644707, 'weight_class_2': 0.18150435097432793}. Best is trial 165 with value: 0.9495150983621875.

[I 2026-07-13 11:43:30,184] Trial 166 finished with value: 0.9488790997776966 and parameters: {'weight_class_0': 0.010168157205858267, 'weight_class_1': 0.3007678661806313, 'weight_class_2': 0.17634545999657306}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:30,187] Trial 168 finished with value: 0.9489220906942087 and parameters: {'weight_class_0': 0.010411962149224706, 'weight_class_1': 0.29695857546519944, 'weight_class_2': 0.18271561523907462}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:30,214] Trial 169 finished with value: 0.9486491965714018 and parameters: {'weight_class_0': 0.010005184768840499, 'weight_class_1': 0.32237935511828314, 'weight_class_2': 0.1897706408087042}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:30,237] Trial 170 finished with value: 0.9484742335387283 and parameters: {'weight_class_0': 0.01041584405952037, 'weight_class_1': 0.09489238519516112, 'weight_class_2': 0.19387053846043234}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:30,246] Trial 171 finished with value: 0.9490604898257052 and parameters: {'weight_class_0': 0.011096570289560766, 'weight_class_1': 0.29677142702580017, 'weight_class_2': 0.18366997912325744}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:30,289] Trial 172 finished with value: 0.9483875097673676 and parameters: {'weight_class_0': 0.01097871200298041, 'weight_class_1': 0.09158283421961466, 'weight_class_2': 0.18334451374440314}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:30,292] Trial 173 finished with value: 0.9484095567276182 and parameters: {'weight_class_0': 0.010236757569227919, 'weight_class_1': 0.08750577409279903, 'weight_class_2': 0.18014446946249804}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:30,302] Trial 174 finished with value: 0.9484798350915461 and parameters: {'weight_class_0': 0.010868497815547155, 'weight_class_1': 0.09244838570196999, 'weight_class_2': 0.17811558930796328}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:30,330] Trial 175 finished with value: 0.948959051922249 and parameters: {'weight_class_0': 0.010966124299478394, 'weight_class_1': 0.3051321858399078, 'weight_class_2': 0.18984088420696774}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:30,345] Trial 176 finished with value: 0.9489112230437734 and parameters: {'weight_class_0': 0.010518978417416202, 'weight_class_1': 0.30332107927563823, 'weight_class_2': 0.1803619106258978}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:30,375] Trial 177 finished with value: 0.9488286740159021 and parameters: {'weight_class_0': 0.009753371999257111, 'weight_class_1': 0.2985213932567816, 'weight_class_2': 0.18152188878531564}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:30,391] Trial 178 finished with value: 0.9489285517513749 and parameters: {'weight_class_0': 0.010212176816033765, 'weight_class_1': 0.28594627894794167, 'weight_class_2': 0.18748883484384415}. Best is trial 165 with value: 0.9495150983621875.

Best trial: 165. Best value: 0.949515:  37%|█████████████████████████████████████████████████▌                                                                                   | 190/510 [00:03<00:05, 55.46it/s]

[I 2026-07-13 11:43:30,399] Trial 179 finished with value: 0.9487430218505487 and parameters: {'weight_class_0': 0.010038988102734264, 'weight_class_1': 0.30693665710012036, 'weight_class_2': 0.19056771480464885}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:30,427] Trial 181 finished with value: 0.9485481542207976 and parameters: {'weight_class_0': 0.009646879376941773, 'weight_class_1': 0.3045970017188557, 'weight_class_2': 0.21035345039465636}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:30,444] Trial 180 finished with value: 0.948687067833113 and parameters: {'weight_class_0': 0.01015547897051196, 'weight_class_1': 0.30143847645007843, 'weight_class_2': 0.22081219642759994}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:30,462] Trial 183 finished with value: 0.9485011809427929 and parameters: {'weight_class_0': 0.00932256412382654, 'weight_class_1': 0.28927768599949205, 'weight_class_2': 0.22208464348025686}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:30,467] Trial 182 finished with value: 0.9488324135181413 and parameters: {'weight_class_0': 0.009342984697998992, 'weight_class_1': 0.14797330625824034, 'weight_class_2': 0.22176475288228306}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:30,486] Trial 184 finished with value: 0.9482009037308271 and parameters: {'weight_class_0': 0.009050823052534109, 'weight_class_1': 0.31300959141438744, 'weight_class_2': 0.08068389918615344}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:30,506] Trial 185 finished with value: 0.9479067054658632 and parameters: {'weight_class_0': 0.008487434741735285, 'weight_class_1': 0.3011544942584129, 'weight_class_2': 0.2280474339432835}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:30,529] Trial 186 finished with value: 0.94810833765499 and parameters: {'weight_class_0': 0.008835990275695713, 'weight_class_1': 0.28099068494003687, 'weight_class_2': 0.24397563574925427}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:30,537] Trial 187 finished with value: 0.9482338055280431 and parameters: {'weight_class_0': 0.008809677169685703, 'weight_class_1': 0.29290298586815394, 'weight_class_2': 0.2186172941241251}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:30,557] Trial 188 finished with value: 0.9484243233750798 and parameters: {'weight_class_0': 0.009155260460906294, 'weight_class_1': 0.26190910889062846, 'weight_class_2': 0.2335394119525423}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:30,577] Trial 189 finished with value: 0.9482876833624404 and parameters: {'weight_class_0': 0.008845074658765278, 'weight_class_1': 0.2858532686492232, 'weight_class_2': 0.22202114662021608}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:30,593] Trial 190 finished with value: 0.9488186283961947 and parameters: {'weight_class_0': 0.008639077833613625, 'weight_class_1': 0.26468442583629176, 'weight_class_2': 0.15918774807153277}. Best is trial 165 with value: 0.9495150983621875.

[I 2026-07-13 11:43:30,599] Trial 191 finished with value: 0.9480750084209507 and parameters: {'weight_class_0': 0.012062475133205118, 'weight_class_1': 0.2653486365414675, 'weight_class_2': 0.08108435167202711}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:30,641] Trial 192 finished with value: 0.9473711085217054 and parameters: {'weight_class_0': 0.008120567797584998, 'weight_class_1': 0.36821156091639917, 'weight_class_2': 0.15487961129494673}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:30,647] Trial 193 finished with value: 0.9481059613388902 and parameters: {'weight_class_0': 0.007021712579758925, 'weight_class_1': 0.25496500139089445, 'weight_class_2': 0.15775649711296952}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:30,656] Trial 194 finished with value: 0.948218672301608 and parameters: {'weight_class_0': 0.0071548360690983585, 'weight_class_1': 0.2567025209644581, 'weight_class_2': 0.15562385296439532}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:30,679] Trial 195 finished with value: 0.9480968208620354 and parameters: {'weight_class_0': 0.007003875432739242, 'weight_class_1': 0.24818924317835142, 'weight_class_2': 0.16991751769507815}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:30,711] Trial 197 finished with value: 0.9443579736844624 and parameters: {'weight_class_0': 0.007176978459228029, 'weight_class_1': 0.37972279137916015, 'weight_class_2': 0.33961011254882295}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:30,729] Trial 198 finished with value: 0.9461687322475419 and parameters: {'weight_class_0': 0.007060253559468395, 'weight_class_1': 0.3737105291672504, 'weight_class_2': 0.1604286584745979}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:30,734] Trial 196 finished with value: 0.9494663752865705 and parameters: {'weight_class_0': 0.012342229136268682, 'weight_class_1': 0.2374308777979266, 'weight_class_2': 0.1622216743380535}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:30,767] Trial 200 finished with value: 0.9465025088661546 and parameters: {'weight_class_0': 0.0071285511604435026, 'weight_class_1': 0.362578776721619, 'weight_class_2': 0.15455305874999684}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:30,775] Trial 199 finished with value: 0.94599091541289 and parameters: {'weight_class_0': 0.006874656647410979, 'weight_class_1': 0.37038317519201974, 'weight_class_2': 0.1602065973987641}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:30,792] Trial 201 finished with value: 0.9464620882230008 and parameters: {'weight_class_0': 0.007001334247247385, 'weight_class_1': 0.3557983591161692, 'weight_class_2': 0.15640591939240647}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:30,802] Trial 202 finished with value: 0.9480835940481068 and parameters: {'weight_class_0': 0.012147407841912941, 'weight_class_1': 0.38200698421633966, 'weight_class_2': 0.34623570173703627}. Best is trial 165 with value: 0.9495150983621875.

[I 2026-07-13 11:43:30,844] Trial 203 finished with value: 0.948182598851377 and parameters: {'weight_class_0': 0.011804334206360996, 'weight_class_1': 0.1588076120982854, 'weight_class_2': 0.33814922889178434}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:30,854] Trial 204 finished with value: 0.9490531879558858 and parameters: {'weight_class_0': 0.012453459469440846, 'weight_class_1': 0.36259964035128134, 'weight_class_2': 0.15312228381383244}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:30,866] Trial 205 finished with value: 0.9480020601935631 and parameters: {'weight_class_0': 0.011208702759377322, 'weight_class_1': 0.3645754004443396, 'weight_class_2': 0.31943485261835686}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:30,885] Trial 206 finished with value: 0.949038262600958 and parameters: {'weight_class_0': 0.011891508351136924, 'weight_class_1': 0.15940415058050944, 'weight_class_2': 0.103139995880008}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:30,896] Trial 207 finished with value: 0.9488785072140753 and parameters: {'weight_class_0': 0.012441576511944285, 'weight_class_1': 0.16208081133968427, 'weight_class_2': 0.10205128844036745}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:30,925] Trial 208 finished with value: 0.9489944338866726 and parameters: {'weight_class_0': 0.01265966008050355, 'weight_class_1': 0.16275651235270464, 'weight_class_2': 0.10932725434492682}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:30,927] Trial 209 finished with value: 0.949076451301864 and parameters: {'weight_class_0': 0.012310829862489629, 'weight_class_1': 0.20229755143213393, 'weight_class_2': 0.10744325280992094}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:30,959] Trial 210 finished with value: 0.9489477578296454 and parameters: {'weight_class_0': 0.012793797570807109, 'weight_class_1': 0.15697956786357756, 'weight_class_2': 0.10990611185075705}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:30,989] Trial 211 finished with value: 0.9489978117856687 and parameters: {'weight_class_0': 0.012230421856678709, 'weight_class_1': 0.16151858730780852, 'weight_class_2': 0.10456259465792525}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,017] Trial 213 finished with value: 0.9490959514351608 and parameters: {'weight_class_0': 0.012489844975350724, 'weight_class_1': 0.20119327731051598, 'weight_class_2': 0.1094308031020422}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,024] Trial 212 finished with value: 0.9483922205554891 and parameters: {'weight_class_0': 0.01272126920950204, 'weight_class_1': 0.15426169176721777, 'weight_class_2': 0.09158051694312702}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,028] Trial 214 finished with value: 0.9486535787129752 and parameters: {'weight_class_0': 0.014235028742314861, 'weight_class_1': 0.1988225514242412, 'weight_class_2': 0.10605864477293862}. Best is trial 165 with value: 0.9495150983621875.

[I 2026-07-13 11:43:31,055] Trial 215 finished with value: 0.948392264322908 and parameters: {'weight_class_0': 0.014596134878630537, 'weight_class_1': 0.20892468377168769, 'weight_class_2': 0.10205867880134425}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,072] Trial 217 finished with value: 0.9488040202618363 and parameters: {'weight_class_0': 0.013229361562419545, 'weight_class_1': 0.1821529756690265, 'weight_class_2': 0.10305105981209668}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,079] Trial 216 finished with value: 0.948943571392408 and parameters: {'weight_class_0': 0.013048572948584691, 'weight_class_1': 0.18602865640066052, 'weight_class_2': 0.10852731992044959}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,090] Trial 218 finished with value: 0.9483687813551609 and parameters: {'weight_class_0': 0.014727960034936555, 'weight_class_1': 0.2092852447833284, 'weight_class_2': 0.10264331261711214}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,119] Trial 219 finished with value: 0.9477362068298669 and parameters: {'weight_class_0': 0.014769847350381183, 'weight_class_1': 0.19294299252991, 'weight_class_2': 0.08857377127409351}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,138] Trial 220 finished with value: 0.9481751481040014 and parameters: {'weight_class_0': 0.01541588404686751, 'weight_class_1': 0.19777621207132834, 'weight_class_2': 0.10451336027654336}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,159] Trial 221 finished with value: 0.9484617189857634 and parameters: {'weight_class_0': 0.014817021848607868, 'weight_class_1': 0.1866402508007365, 'weight_class_2': 0.10750060338047285}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,182] Trial 222 finished with value: 0.9468955956250776 and parameters: {'weight_class_0': 0.013897870382842722, 'weight_class_1': 0.12032345886365584, 'weight_class_2': 0.080665437984896}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,193] Trial 223 finished with value: 0.947418881714606 and parameters: {'weight_class_0': 0.014653703159771178, 'weight_class_1': 0.2123180446573604, 'weight_class_2': 0.08318412062110078}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,211] Trial 224 finished with value: 0.9476794413065237 and parameters: {'weight_class_0': 0.01549900427762637, 'weight_class_1': 0.12455498797085197, 'weight_class_2': 0.10973783460257137}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,224] Trial 225 finished with value: 0.9465623183085593 and parameters: {'weight_class_0': 0.015209385616345926, 'weight_class_1': 0.13026332626126397, 'weight_class_2': 0.08309406736247774}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,244] Trial 226 finished with value: 0.9441412847542373 and parameters: {'weight_class_0': 0.015851858040362134, 'weight_class_1': 0.1340558011775005, 'weight_class_2': 0.0646813172444745}. Best is trial 165 with value: 0.9495150983621875.

[I 2026-07-13 11:43:31,255] Trial 227 finished with value: 0.9451097408170259 and parameters: {'weight_class_0': 0.016783650910868152, 'weight_class_1': 0.1261442991616389, 'weight_class_2': 0.07884031538018363}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,289] Trial 229 finished with value: 0.9479103345047638 and parameters: {'weight_class_0': 0.012463004147130587, 'weight_class_1': 0.12985440582278113, 'weight_class_2': 0.08395163432618329}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,294] Trial 228 finished with value: 0.9477377960136247 and parameters: {'weight_class_0': 0.012331770707291849, 'weight_class_1': 0.14246612912553042, 'weight_class_2': 0.07584321787683375}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,314] Trial 230 finished with value: 0.947164586694575 and parameters: {'weight_class_0': 0.012238868305300198, 'weight_class_1': 0.12616695123005675, 'weight_class_2': 0.0704821994907261}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,351] Trial 231 finished with value: 0.9469766549289677 and parameters: {'weight_class_0': 0.01206648111472338, 'weight_class_1': 0.136575788592019, 'weight_class_2': 0.06474141338946816}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,370] Trial 232 finished with value: 0.9470241135643679 and parameters: {'weight_class_0': 0.012136094759287362, 'weight_class_1': 0.12867144925562446, 'weight_class_2': 0.06742753108166824}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,394] Trial 233 finished with value: 0.9467483406106066 and parameters: {'weight_class_0': 0.011801235635518739, 'weight_class_1': 0.14594782899322067, 'weight_class_2': 0.059929020847542494}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,410] Trial 234 finished with value: 0.9463814953903872 and parameters: {'weight_class_0': 0.01270322584644857, 'weight_class_1': 0.1608606861341487, 'weight_class_2': 0.062286436922166295}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,414] Trial 235 finished with value: 0.9494602221571884 and parameters: {'weight_class_0': 0.011503632731125878, 'weight_class_1': 0.1632501699288898, 'weight_class_2': 0.13004146954820472}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,435] Trial 236 finished with value: 0.9494556852505944 and parameters: {'weight_class_0': 0.011716821326718627, 'weight_class_1': 0.22920693642133783, 'weight_class_2': 0.13925253739090765}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,465] Trial 237 finished with value: 0.949447038768977 and parameters: {'weight_class_0': 0.011955627134085564, 'weight_class_1': 0.16153508810279923, 'weight_class_2': 0.14285462187397927}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,473] Trial 238 finished with value: 0.9494675042914532 and parameters: {'weight_class_0': 0.011348277650425587, 'weight_class_1': 0.2290888584014939, 'weight_class_2': 0.13839044334012846}. Best is trial 165 with value: 0.9495150983621875.

Best trial: 165. Best value: 0.949515:  49%|████████████████████████████████████████████████████████████████▋                                                                    | 248/510 [00:04<00:04, 56.32it/s]

[I 2026-07-13 11:43:31,483] Trial 240 finished with value: 0.949410151472777 and parameters: {'weight_class_0': 0.010045243860257052, 'weight_class_1': 0.23233229326673754, 'weight_class_2': 0.14156656815481627}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,486] Trial 239 finished with value: 0.9494331278779701 and parameters: {'weight_class_0': 0.01084303175836057, 'weight_class_1': 0.23558146557128049, 'weight_class_2': 0.14346581095754932}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,513] Trial 241 finished with value: 0.9494296740037668 and parameters: {'weight_class_0': 0.010278835747375724, 'weight_class_1': 0.22907005166614866, 'weight_class_2': 0.12891960483181278}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,537] Trial 242 finished with value: 0.9493970792380896 and parameters: {'weight_class_0': 0.010710060410530117, 'weight_class_1': 0.23057658146604063, 'weight_class_2': 0.13824435415129332}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,557] Trial 243 finished with value: 0.8185711152597767 and parameters: {'weight_class_0': 2.203159524967579, 'weight_class_1': 0.23709480901224853, 'weight_class_2': 0.14232589197553414}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,596] Trial 244 finished with value: 0.9494032202446535 and parameters: {'weight_class_0': 0.010816350550605942, 'weight_class_1': 0.23440845229814555, 'weight_class_2': 0.13813660963817823}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,598] Trial 245 finished with value: 0.9494154587292675 and parameters: {'weight_class_0': 0.010760160928971883, 'weight_class_1': 0.23065234662128903, 'weight_class_2': 0.13753080268449977}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,642] Trial 246 finished with value: 0.9485555032498599 and parameters: {'weight_class_0': 0.018866843673244194, 'weight_class_1': 0.2369173981419513, 'weight_class_2': 0.13930545058658483}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,662] Trial 247 finished with value: 0.94908386259841 and parameters: {'weight_class_0': 0.0082230823591486, 'weight_class_1': 0.22096977977430315, 'weight_class_2': 0.13601690775198919}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,663] Trial 248 finished with value: 0.9489325506612601 and parameters: {'weight_class_0': 0.008262261832124874, 'weight_class_1': 0.2428922523391073, 'weight_class_2': 0.13855441813147695}. Best is trial 165 with value: 0.9495150983621875.

Best trial: 165. Best value: 0.949515:  51%|███████████████████████████████████████████████████████████████████▊                                                                 | 260/510 [00:04<00:04, 55.08it/s]

[I 2026-07-13 11:43:31,675] Trial 249 finished with value: 0.9490740053950514 and parameters: {'weight_class_0': 0.008302464543601286, 'weight_class_1': 0.22841050896110604, 'weight_class_2': 0.13397505324482847}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,709] Trial 250 finished with value: 0.9489677339474922 and parameters: {'weight_class_0': 0.00838024785268851, 'weight_class_1': 0.2384031388291198, 'weight_class_2': 0.1402488530180586}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,710] Trial 252 finished with value: 0.9491207240631362 and parameters: {'weight_class_0': 0.00857975105288693, 'weight_class_1': 0.23336411113670527, 'weight_class_2': 0.13636205614113783}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,721] Trial 251 finished with value: 0.9490574159762141 and parameters: {'weight_class_0': 0.008852260403027164, 'weight_class_1': 0.2467154427279782, 'weight_class_2': 0.1422911125277183}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,730] Trial 253 finished with value: 0.9491179807987722 and parameters: {'weight_class_0': 0.008491445600095269, 'weight_class_1': 0.22964818050547792, 'weight_class_2': 0.13747678075019618}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,744] Trial 254 finished with value: 0.9492502434443622 and parameters: {'weight_class_0': 0.009136610292313219, 'weight_class_1': 0.22880361855413864, 'weight_class_2': 0.1358619471639922}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,761] Trial 255 finished with value: 0.9491595871545667 and parameters: {'weight_class_0': 0.008781146149688595, 'weight_class_1': 0.22843053861766047, 'weight_class_2': 0.14223249954613387}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,802] Trial 256 finished with value: 0.9491878700966735 and parameters: {'weight_class_0': 0.008636786445150323, 'weight_class_1': 0.23566556390809798, 'weight_class_2': 0.13352945705751057}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,813] Trial 257 finished with value: 0.9492293844018255 and parameters: {'weight_class_0': 0.008565587456432553, 'weight_class_1': 0.22464059991361193, 'weight_class_2': 0.13411469090586892}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,830] Trial 258 finished with value: 0.9493728376731033 and parameters: {'weight_class_0': 0.008857987956944416, 'weight_class_1': 0.20472064692284905, 'weight_class_2': 0.12951119727911956}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,857] Trial 259 finished with value: 0.9493783936902135 and parameters: {'weight_class_0': 0.009627130328445626, 'weight_class_1': 0.21756546613491928, 'weight_class_2': 0.13604857869798573}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,880] Trial 261 finished with value: 0.9494331495227745 and parameters: {'weight_class_0': 0.009544694236127927, 'weight_class_1': 0.1951568371231554, 'weight_class_2': 0.12671808022038916}. Best is trial 165 with value: 0.9495150983621875.

[I 2026-07-13 11:43:31,894] Trial 260 finished with value: 0.9494435330701197 and parameters: {'weight_class_0': 0.00985522025294368, 'weight_class_1': 0.19306300131925516, 'weight_class_2': 0.12658468212115523}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,896] Trial 262 finished with value: 0.9494053751837273 and parameters: {'weight_class_0': 0.010043358220606225, 'weight_class_1': 0.23414063666052107, 'weight_class_2': 0.1414759196216376}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,941] Trial 263 finished with value: 0.9483155200862642 and parameters: {'weight_class_0': 0.005607215930134427, 'weight_class_1': 0.18695487855909085, 'weight_class_2': 0.13119699495661827}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,950] Trial 264 finished with value: 0.9482638411306411 and parameters: {'weight_class_0': 0.005569462096369922, 'weight_class_1': 0.1894417148415197, 'weight_class_2': 0.13011908042344675}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,960] Trial 265 finished with value: 0.9487048875133576 and parameters: {'weight_class_0': 0.00611770811624774, 'weight_class_1': 0.1896080343619739, 'weight_class_2': 0.12634040138517796}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:31,986] Trial 266 finished with value: 0.9478306460095153 and parameters: {'weight_class_0': 0.0050093165714946465, 'weight_class_1': 0.18603349422471405, 'weight_class_2': 0.12772339601183694}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:32,027] Trial 267 finished with value: 0.9485024278553894 and parameters: {'weight_class_0': 0.0057125885854576106, 'weight_class_1': 0.18443058820564112, 'weight_class_2': 0.12302678574188995}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:32,028] Trial 269 finished with value: 0.9487241326665736 and parameters: {'weight_class_0': 0.00609975001224092, 'weight_class_1': 0.18666820279664617, 'weight_class_2': 0.1202750186943892}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:32,037] Trial 268 finished with value: 0.9477412549823097 and parameters: {'weight_class_0': 0.0049323105687972294, 'weight_class_1': 0.18724371295401915, 'weight_class_2': 0.1253745126248512}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:32,047] Trial 270 finished with value: 0.9480437061045093 and parameters: {'weight_class_0': 0.005083383738720145, 'weight_class_1': 0.18475089941230977, 'weight_class_2': 0.1207512463285218}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:32,071] Trial 271 finished with value: 0.9487060125733372 and parameters: {'weight_class_0': 0.005733668835423224, 'weight_class_1': 0.17747034467189785, 'weight_class_2': 0.1185131122489634}. Best is trial 165 with value: 0.9495150983621875.

Best trial: 277. Best value: 0.949562:  55%|█████████████████████████████████████████████████████████████████████████▊                                                           | 283/510 [00:05<00:04, 54.68it/s]

[I 2026-07-13 11:43:32,094] Trial 272 finished with value: 0.9494583947063103 and parameters: {'weight_class_0': 0.010272723606259056, 'weight_class_1': 0.17553309327880484, 'weight_class_2': 0.118976927652641}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:32,135] Trial 273 finished with value: 0.9495108209925051 and parameters: {'weight_class_0': 0.010405197998567182, 'weight_class_1': 0.17420676157657222, 'weight_class_2': 0.16517500001032973}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:32,136] Trial 274 finished with value: 0.9494716956812798 and parameters: {'weight_class_0': 0.010201278417736694, 'weight_class_1': 0.17463806672010082, 'weight_class_2': 0.16138810914869187}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:32,166] Trial 276 finished with value: 0.9491719704193667 and parameters: {'weight_class_0': 0.009950480762903512, 'weight_class_1': 0.17537832581431217, 'weight_class_2': 0.19992560886134625}. Best is trial 165 with value: 0.9495150983621875.
[I 2026-07-13 11:43:32,167] Trial 275 finished with value: 0.9495196027810621 and parameters: {'weight_class_0': 0.010656404279847891, 'weight_class_1': 0.1791055716275782, 'weight_class_2': 0.16633483849241798}. Best is trial 275 with value: 0.9495196027810621.
[I 2026-07-13 11:43:32,198] Trial 277 finished with value: 0.9495624141169466 and parameters: {'weight_class_0': 0.010880207806710639, 'weight_class_1': 0.173906383023136, 'weight_class_2': 0.16713098563667145}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:32,209] Trial 278 finished with value: 0.9492944936713678 and parameters: {'weight_class_0': 0.01056522676454131, 'weight_class_1': 0.2555920326529603, 'weight_class_2': 0.16736479279103442}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:32,213] Trial 280 finished with value: 0.9492439832014413 and parameters: {'weight_class_0': 0.01092259060867905, 'weight_class_1': 0.2805170399172538, 'weight_class_2': 0.1729065661226514}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:32,227] Trial 279 finished with value: 0.9490575523984891 and parameters: {'weight_class_0': 0.010424674537003966, 'weight_class_1': 0.26688148112162324, 'weight_class_2': 0.19925737560650686}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:32,257] Trial 282 finished with value: 0.9492079317397075 and parameters: {'weight_class_0': 0.010338672860054597, 'weight_class_1': 0.261500114234227, 'weight_class_2': 0.1662205402483471}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:32,263] Trial 281 finished with value: 0.9491867186323272 and parameters: {'weight_class_0': 0.010608396710442756, 'weight_class_1': 0.2649161233404091, 'weight_class_2': 0.1775622344006189}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:32,299] Trial 283 finished with value: 0.9491938789216889 and parameters: {'weight_class_0': 0.01028828313897437, 'weight_class_1': 0.2640007099608707, 'weight_class_2': 0.16587031088230603}. Best is trial 277 with value: 0.9495624141169466.

Best trial: 277. Best value: 0.949562:  58%|████████████████████████████████████████████████████████████████████████████▋                                                        | 294/510 [00:05<00:04, 51.96it/s]

[I 2026-07-13 11:43:32,317] Trial 284 finished with value: 0.9490205085312818 and parameters: {'weight_class_0': 0.010482767910153885, 'weight_class_1': 0.26795520274415296, 'weight_class_2': 0.21206332723986634}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:32,340] Trial 285 finished with value: 0.9486261315444945 and parameters: {'weight_class_0': 0.010104210150235934, 'weight_class_1': 0.15597202187729092, 'weight_class_2': 0.25518948817311315}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:32,350] Trial 286 finished with value: 0.9481366651800456 and parameters: {'weight_class_0': 0.010502106478319456, 'weight_class_1': 0.11096820077662574, 'weight_class_2': 0.26586693646706694}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:32,370] Trial 287 finished with value: 0.9479824632557841 and parameters: {'weight_class_0': 0.010270159030318197, 'weight_class_1': 0.10491731477479804, 'weight_class_2': 0.2687182534334398}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:32,394] Trial 288 finished with value: 0.948704565468998 and parameters: {'weight_class_0': 0.017125045132483446, 'weight_class_1': 0.15169806211328574, 'weight_class_2': 0.2536353010880546}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:32,404] Trial 290 finished with value: 0.9475889285743953 and parameters: {'weight_class_0': 0.017084941096218657, 'weight_class_1': 0.10966310749955067, 'weight_class_2': 0.2550323410008849}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:32,422] Trial 289 finished with value: 0.9486995720846744 and parameters: {'weight_class_0': 0.017289818792516155, 'weight_class_1': 0.15461013346377114, 'weight_class_2': 0.2585785052696614}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:32,471] Trial 291 finished with value: 0.9474921693066652 and parameters: {'weight_class_0': 0.01776933053659069, 'weight_class_1': 0.11142136315568582, 'weight_class_2': 0.25458209101566365}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:32,482] Trial 292 finished with value: 0.9487118149871487 and parameters: {'weight_class_0': 0.01726633605489776, 'weight_class_1': 0.1534495000256263, 'weight_class_2': 0.25561337246056504}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:32,491] Trial 293 finished with value: 0.9488405038026019 and parameters: {'weight_class_0': 0.016164914016036497, 'weight_class_1': 0.15630865418373388, 'weight_class_2': 0.25591068606814177}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:32,507] Trial 294 finished with value: 0.948496777596 and parameters: {'weight_class_0': 0.017193663086055834, 'weight_class_1': 0.138267166121584, 'weight_class_2': 0.2480991425890867}. Best is trial 277 with value: 0.9495624141169466.

Best trial: 277. Best value: 0.949562:  60%|███████████████████████████████████████████████████████████████████████████████▌                                                     | 305/510 [00:05<00:03, 53.30it/s]

[I 2026-07-13 11:43:32,512] Trial 295 finished with value: 0.9478370257724551 and parameters: {'weight_class_0': 0.01597472461083186, 'weight_class_1': 0.10822579066067424, 'weight_class_2': 0.24819180300479068}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:32,548] Trial 296 finished with value: 0.9482604815767859 and parameters: {'weight_class_0': 0.0071151014879994486, 'weight_class_1': 0.16012080536786577, 'weight_class_2': 0.2189260793910634}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:32,582] Trial 298 finished with value: 0.9485129110583999 and parameters: {'weight_class_0': 0.007302083382158926, 'weight_class_1': 0.1577645861600829, 'weight_class_2': 0.20290540411136682}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:32,585] Trial 297 finished with value: 0.9483992182247337 and parameters: {'weight_class_0': 0.007047767543240958, 'weight_class_1': 0.15645895174222502, 'weight_class_2': 0.2064041158407453}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:32,598] Trial 299 finished with value: 0.8037557539364505 and parameters: {'weight_class_0': 5.49133951445854, 'weight_class_1': 0.16604609807241288, 'weight_class_2': 0.204996226243726}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:32,638] Trial 301 finished with value: 0.9486657100386383 and parameters: {'weight_class_0': 0.007470991415117811, 'weight_class_1': 0.14965662086249681, 'weight_class_2': 0.19754236908275585}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:32,643] Trial 300 finished with value: 0.949121748823082 and parameters: {'weight_class_0': 0.015146967957643477, 'weight_class_1': 0.1605088748504152, 'weight_class_2': 0.20588790380812197}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:32,668] Trial 302 finished with value: 0.9485503749784288 and parameters: {'weight_class_0': 0.0072682720461627204, 'weight_class_1': 0.17585459150613852, 'weight_class_2': 0.19572714964847804}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:32,686] Trial 304 finished with value: 0.9485753406742005 and parameters: {'weight_class_0': 0.007331503561979023, 'weight_class_1': 0.17242203051391555, 'weight_class_2': 0.19834741920750668}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:32,695] Trial 303 finished with value: 0.9487028179894262 and parameters: {'weight_class_0': 0.0075907605403489975, 'weight_class_1': 0.17135421369819362, 'weight_class_2': 0.19793535521146705}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:32,734] Trial 305 finished with value: 0.9490196055601907 and parameters: {'weight_class_0': 0.007686659608277149, 'weight_class_1': 0.18914366017229245, 'weight_class_2': 0.16030625468058318}. Best is trial 277 with value: 0.9495624141169466.

Best trial: 277. Best value: 0.949562:  62%|██████████████████████████████████████████████████████████████████████████████████▋                                                  | 317/510 [00:05<00:03, 53.15it/s]

[I 2026-07-13 11:43:32,745] Trial 306 finished with value: 0.9486322319443333 and parameters: {'weight_class_0': 0.0075438090227502325, 'weight_class_1': 0.19987643352376122, 'weight_class_2': 0.1932483413003179}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:32,754] Trial 307 finished with value: 0.9489434478337393 and parameters: {'weight_class_0': 0.007500264326963401, 'weight_class_1': 0.199508967621576, 'weight_class_2': 0.15881974295646775}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:32,768] Trial 308 finished with value: 0.9494442844971301 and parameters: {'weight_class_0': 0.0141272909601899, 'weight_class_1': 0.19865920572787102, 'weight_class_2': 0.16409101184649916}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:32,812] Trial 310 finished with value: 0.947274631959291 and parameters: {'weight_class_0': 0.026143758826482132, 'weight_class_1': 0.21009718617649548, 'weight_class_2': 0.16554081250097208}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:32,817] Trial 309 finished with value: 0.9494123933815092 and parameters: {'weight_class_0': 0.013921001920633615, 'weight_class_1': 0.20301586432368346, 'weight_class_2': 0.15445689940686352}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:32,843] Trial 311 finished with value: 0.9473089523025413 and parameters: {'weight_class_0': 0.02558862906673349, 'weight_class_1': 0.20616601111660293, 'weight_class_2': 0.16292216609361806}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:32,849] Trial 312 finished with value: 0.9495184912212827 and parameters: {'weight_class_0': 0.013658005531974039, 'weight_class_1': 0.21032717273351995, 'weight_class_2': 0.16715565231560384}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:32,874] Trial 313 finished with value: 0.949502085327976 and parameters: {'weight_class_0': 0.013706874545867276, 'weight_class_1': 0.22118685389188572, 'weight_class_2': 0.15989572445159173}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:32,896] Trial 314 finished with value: 0.9494795214352143 and parameters: {'weight_class_0': 0.013759603761236814, 'weight_class_1': 0.20690502630370922, 'weight_class_2': 0.16453156528337493}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:32,900] Trial 315 finished with value: 0.9494607039857201 and parameters: {'weight_class_0': 0.013910880910502747, 'weight_class_1': 0.22042098146296038, 'weight_class_2': 0.1579309097481791}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:32,938] Trial 317 finished with value: 0.9448435469172067 and parameters: {'weight_class_0': 0.021476856423147922, 'weight_class_1': 0.33470661362917287, 'weight_class_2': 0.08841437856142889}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:32,951] Trial 316 finished with value: 0.9481681363028143 and parameters: {'weight_class_0': 0.013827293033338598, 'weight_class_1': 0.3234686157230516, 'weight_class_2': 0.09545446806498609}. Best is trial 277 with value: 0.9495624141169466.

Best trial: 277. Best value: 0.949562:  64%|█████████████████████████████████████████████████████████████████████████████████████▌                                               | 328/510 [00:06<00:03, 53.37it/s]

[I 2026-07-13 11:43:32,962] Trial 318 finished with value: 0.9451497526967625 and parameters: {'weight_class_0': 0.022526834582226544, 'weight_class_1': 0.3081469877630661, 'weight_class_2': 0.09598310736680182}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:32,977] Trial 319 finished with value: 0.9493220071936004 and parameters: {'weight_class_0': 0.013630463630628462, 'weight_class_1': 0.3254889034373717, 'weight_class_2': 0.16114352361018405}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,013] Trial 321 finished with value: 0.9475872424632682 and parameters: {'weight_class_0': 0.01426138942237066, 'weight_class_1': 0.1360602717658206, 'weight_class_2': 0.08961781484580224}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,018] Trial 320 finished with value: 0.9479066230646699 and parameters: {'weight_class_0': 0.013624614319031178, 'weight_class_1': 0.3195386061373576, 'weight_class_2': 0.08880407152763127}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,049] Trial 322 finished with value: 0.9485646718554834 and parameters: {'weight_class_0': 0.013729650464220169, 'weight_class_1': 0.33149888122645116, 'weight_class_2': 0.1048002914765064}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,065] Trial 323 finished with value: 0.9477085949091362 and parameters: {'weight_class_0': 0.01349104766146904, 'weight_class_1': 0.1326859674363309, 'weight_class_2': 0.08842719133302354}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,098] Trial 324 finished with value: 0.9435070223777978 and parameters: {'weight_class_0': 0.021565109413425453, 'weight_class_1': 0.12406213216100402, 'weight_class_2': 0.09829811746068086}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,115] Trial 325 finished with value: 0.9471480268769712 and parameters: {'weight_class_0': 0.02044130504741642, 'weight_class_1': 0.30614731418930796, 'weight_class_2': 0.10997894331492458}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,118] Trial 326 finished with value: 0.9487545394369513 and parameters: {'weight_class_0': 0.013846200663522547, 'weight_class_1': 0.2797713786936953, 'weight_class_2': 0.10724122242921132}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,131] Trial 327 finished with value: 0.9490682693016191 and parameters: {'weight_class_0': 0.013547898504098514, 'weight_class_1': 0.1386519028420238, 'weight_class_2': 0.1615915792565526}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,164] Trial 329 finished with value: 0.9486752979335588 and parameters: {'weight_class_0': 0.01291940203102355, 'weight_class_1': 0.13136743162643527, 'weight_class_2': 0.1111206692171331}. Best is trial 277 with value: 0.9495624141169466.

[I 2026-07-13 11:43:33,201] Trial 330 finished with value: 0.9485252510200937 and parameters: {'weight_class_0': 0.01365759274202079, 'weight_class_1': 0.12832969381306614, 'weight_class_2': 0.11588322057105194}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,207] Trial 328 finished with value: 0.9485120413018527 and parameters: {'weight_class_0': 0.013604881823789525, 'weight_class_1': 0.12786311060667369, 'weight_class_2': 0.11263605836458468}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,226] Trial 331 finished with value: 0.9459999792798123 and parameters: {'weight_class_0': 0.0197459943202812, 'weight_class_1': 0.12844087889956593, 'weight_class_2': 0.1147135101087313}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,229] Trial 333 finished with value: 0.9476369877240621 and parameters: {'weight_class_0': 0.01922240599612065, 'weight_class_1': 0.12881348004781634, 'weight_class_2': 0.17320173907497782}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,236] Trial 332 finished with value: 0.8237028585117473 and parameters: {'weight_class_0': 0.9501896521379686, 'weight_class_1': 0.126737898117359, 'weight_class_2': 0.11255175131887486}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,276] Trial 335 finished with value: 0.8291972585902365 and parameters: {'weight_class_0': 1.0264495091402814, 'weight_class_1': 0.1978729208420407, 'weight_class_2': 0.16210261959147698}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,287] Trial 334 finished with value: 0.9485699150186885 and parameters: {'weight_class_0': 0.02012799967591373, 'weight_class_1': 0.19866311657406752, 'weight_class_2': 0.16791149256955812}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,291] Trial 336 finished with value: 0.918775984914102 and parameters: {'weight_class_0': 0.011786615948596766, 'weight_class_1': 0.012217468044487824, 'weight_class_2': 0.16589172252650844}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,319] Trial 337 finished with value: 0.9494909887190991 and parameters: {'weight_class_0': 0.01222054930297922, 'weight_class_1': 0.20073603260697045, 'weight_class_2': 0.15552346929323016}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,337] Trial 338 finished with value: 0.9494799162684897 and parameters: {'weight_class_0': 0.011521821608811671, 'weight_class_1': 0.19336419297463095, 'weight_class_2': 0.16669094472800625}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,361] Trial 339 finished with value: 0.9494740919149205 and parameters: {'weight_class_0': 0.011202575834243143, 'weight_class_1': 0.1935836440759014, 'weight_class_2': 0.1687380809690163}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,396] Trial 341 finished with value: 0.8928662301331093 and parameters: {'weight_class_0': 0.00894006150692928, 'weight_class_1': 0.195873084646975, 'weight_class_2': 0.0026761961180090835}. Best is trial 277 with value: 0.9495624141169466.

[I 2026-07-13 11:43:33,427] Trial 340 finished with value: 0.9495504479136946 and parameters: {'weight_class_0': 0.011408491922798216, 'weight_class_1': 0.19680978347529976, 'weight_class_2': 0.15924512377500874}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,430] Trial 342 finished with value: 0.9493368983725802 and parameters: {'weight_class_0': 0.009297616854035172, 'weight_class_1': 0.1960422790255682, 'weight_class_2': 0.15880695288376248}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,441] Trial 343 finished with value: 0.9495047023836337 and parameters: {'weight_class_0': 0.011479139496391089, 'weight_class_1': 0.18901651151470544, 'weight_class_2': 0.16215262979124379}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,467] Trial 344 finished with value: 0.8865116375639754 and parameters: {'weight_class_0': 0.17977092875629666, 'weight_class_1': 0.2504669980863512, 'weight_class_2': 0.1539751200354618}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,477] Trial 345 finished with value: 0.9489511783657626 and parameters: {'weight_class_0': 0.008996147490896562, 'weight_class_1': 0.24328177682370064, 'weight_class_2': 0.18542411285721494}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,507] Trial 346 finished with value: 0.8960433858540974 and parameters: {'weight_class_0': 0.15985356185029834, 'weight_class_1': 0.24273743298780553, 'weight_class_2': 0.18334997992876417}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,518] Trial 347 finished with value: 0.9195063318224155 and parameters: {'weight_class_0': 0.10126375158544296, 'weight_class_1': 0.2513708520892036, 'weight_class_2': 0.19302048867037797}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,543] Trial 348 finished with value: 0.9492999789153399 and parameters: {'weight_class_0': 0.015749509986985592, 'weight_class_1': 0.186635452995454, 'weight_class_2': 0.2122100907772089}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,565] Trial 349 finished with value: 0.949287419195303 and parameters: {'weight_class_0': 0.015599283944351974, 'weight_class_1': 0.1754594488405135, 'weight_class_2': 0.18242652178403426}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,566] Trial 350 finished with value: 0.9492976819102844 and parameters: {'weight_class_0': 0.01594475020074018, 'weight_class_1': 0.18049156983858133, 'weight_class_2': 0.18589268175554705}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,606] Trial 351 finished with value: 0.9491567204521537 and parameters: {'weight_class_0': 0.016183133390627432, 'weight_class_1': 0.17235857704905444, 'weight_class_2': 0.21409193694425355}. Best is trial 277 with value: 0.9495624141169466.

[I 2026-07-13 11:43:33,622] Trial 352 finished with value: 0.9490319751549045 and parameters: {'weight_class_0': 0.016497520889256507, 'weight_class_1': 0.1690419099994367, 'weight_class_2': 0.2153125220122007}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,636] Trial 354 finished with value: 0.949167936256362 and parameters: {'weight_class_0': 0.01598160773799034, 'weight_class_1': 0.1730788090070448, 'weight_class_2': 0.21489040726493644}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,652] Trial 353 finished with value: 0.9491809983677112 and parameters: {'weight_class_0': 0.015902526979981155, 'weight_class_1': 0.17074887643713377, 'weight_class_2': 0.21992363434435622}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,685] Trial 355 finished with value: 0.9491811989145922 and parameters: {'weight_class_0': 0.015999114436727288, 'weight_class_1': 0.1721813963814466, 'weight_class_2': 0.22090615640768635}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,694] Trial 357 finished with value: 0.9487517189984677 and parameters: {'weight_class_0': 0.0167870767432231, 'weight_class_1': 0.1710412530426524, 'weight_class_2': 0.302439643808853}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,696] Trial 356 finished with value: 0.9490411959220305 and parameters: {'weight_class_0': 0.016392111778218303, 'weight_class_1': 0.1673109993953073, 'weight_class_2': 0.2227289663334969}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,745] Trial 358 finished with value: 0.9494483509166627 and parameters: {'weight_class_0': 0.011548170691213604, 'weight_class_1': 0.15874775104300876, 'weight_class_2': 0.14747225750507745}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,747] Trial 359 finished with value: 0.9491135835788143 and parameters: {'weight_class_0': 0.011275734727214038, 'weight_class_1': 0.16089163988898258, 'weight_class_2': 0.22349948994051666}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,780] Trial 360 finished with value: 0.9485551510647466 and parameters: {'weight_class_0': 0.011715580625943179, 'weight_class_1': 0.164811460408852, 'weight_class_2': 0.30163229258491614}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,794] Trial 362 finished with value: 0.9484137172638968 and parameters: {'weight_class_0': 0.012151191393276072, 'weight_class_1': 0.15467969103965826, 'weight_class_2': 0.31615920085846044}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,810] Trial 361 finished with value: 0.9490947413209607 and parameters: {'weight_class_0': 0.011503056336269897, 'weight_class_1': 0.16152255464752766, 'weight_class_2': 0.23223764987598763}. Best is trial 277 with value: 0.9495624141169466.

[I 2026-07-13 11:43:33,821] Trial 363 finished with value: 0.9494565245082663 and parameters: {'weight_class_0': 0.012245233476144712, 'weight_class_1': 0.22133664727216026, 'weight_class_2': 0.14838854834179235}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,852] Trial 365 finished with value: 0.9494940317179038 and parameters: {'weight_class_0': 0.012566531020387404, 'weight_class_1': 0.21563840577578272, 'weight_class_2': 0.1520264001041054}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,858] Trial 364 finished with value: 0.9493793464092793 and parameters: {'weight_class_0': 0.011602757745684571, 'weight_class_1': 0.26654579636037534, 'weight_class_2': 0.1532266282067427}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,876] Trial 366 finished with value: 0.9493629637567841 and parameters: {'weight_class_0': 0.011856843567189761, 'weight_class_1': 0.2670608307654974, 'weight_class_2': 0.15223723665149055}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,903] Trial 367 finished with value: 0.9494235227710678 and parameters: {'weight_class_0': 0.012467962353796384, 'weight_class_1': 0.2605633845297837, 'weight_class_2': 0.1526656125524405}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,919] Trial 368 finished with value: 0.9494852165241713 and parameters: {'weight_class_0': 0.011808699880173893, 'weight_class_1': 0.21772727584869184, 'weight_class_2': 0.15583054700451054}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,933] Trial 369 finished with value: 0.949503813007826 and parameters: {'weight_class_0': 0.01183509522931331, 'weight_class_1': 0.22116448907336014, 'weight_class_2': 0.1564273244838368}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,964] Trial 370 finished with value: 0.9494417919644066 and parameters: {'weight_class_0': 0.012536537144233239, 'weight_class_1': 0.2680124452069082, 'weight_class_2': 0.15390765262280554}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:33,993] Trial 372 finished with value: 0.9494267918654353 and parameters: {'weight_class_0': 0.011953497314438231, 'weight_class_1': 0.2718011560269548, 'weight_class_2': 0.15107552041872307}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,002] Trial 371 finished with value: 0.9494867548084454 and parameters: {'weight_class_0': 0.01187403105827275, 'weight_class_1': 0.21849974543973616, 'weight_class_2': 0.1565276833230195}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,035] Trial 374 finished with value: 0.9494104290561438 and parameters: {'weight_class_0': 0.01214740512281169, 'weight_class_1': 0.2629870864014768, 'weight_class_2': 0.15259171953085934}. Best is trial 277 with value: 0.9495624141169466.

Best trial: 277. Best value: 0.949562:  75%|████████████████████████████████████████████████████████████████████████████████████████████████████▏                                | 384/510 [00:07<00:02, 52.03it/s]

[I 2026-07-13 11:43:34,036] Trial 373 finished with value: 0.9494099776386525 and parameters: {'weight_class_0': 0.0119488163731068, 'weight_class_1': 0.2784389928569353, 'weight_class_2': 0.15029614317676887}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,067] Trial 375 finished with value: 0.9483993549119166 and parameters: {'weight_class_0': 0.012678542052502349, 'weight_class_1': 0.09935827604285119, 'weight_class_2': 0.1806384883350492}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,084] Trial 376 finished with value: 0.9485688005993573 and parameters: {'weight_class_0': 0.012781474687679695, 'weight_class_1': 0.10580827581780104, 'weight_class_2': 0.1821787194132623}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,100] Trial 377 finished with value: 0.9485861182986058 and parameters: {'weight_class_0': 0.013050658456861907, 'weight_class_1': 0.4627317697739338, 'weight_class_2': 0.1777228935684403}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,125] Trial 378 finished with value: 0.9495383753859657 and parameters: {'weight_class_0': 0.013107770142820383, 'weight_class_1': 0.22192222007496193, 'weight_class_2': 0.17903944789491083}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,133] Trial 379 finished with value: 0.9490904087695767 and parameters: {'weight_class_0': 0.018974049109152825, 'weight_class_1': 0.22273662642974718, 'weight_class_2': 0.17742150919801647}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,146] Trial 380 finished with value: 0.9489009787429522 and parameters: {'weight_class_0': 0.019782562328585246, 'weight_class_1': 0.21693594901090982, 'weight_class_2': 0.18096192736210145}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,174] Trial 381 finished with value: 0.9474126635335178 and parameters: {'weight_class_0': 0.009155678356219684, 'weight_class_1': 0.40988905187024777, 'weight_class_2': 0.18191962588602617}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,208] Trial 382 finished with value: 0.9491006899016404 and parameters: {'weight_class_0': 0.009159617986378404, 'weight_class_1': 0.2162578842220269, 'weight_class_2': 0.18288889081806053}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,210] Trial 383 finished with value: 0.9491051901415594 and parameters: {'weight_class_0': 0.008967321798765823, 'weight_class_1': 0.21022397577240684, 'weight_class_2': 0.1797713149279441}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,219] Trial 384 finished with value: 0.9469421436052357 and parameters: {'weight_class_0': 0.009105724974119453, 'weight_class_1': 0.4415180969415627, 'weight_class_2': 0.18382339188920438}. Best is trial 277 with value: 0.9495624141169466.

Best trial: 277. Best value: 0.949562:  77%|███████████████████████████████████████████████████████████████████████████████████████████████████████                              | 395/510 [00:07<00:02, 50.89it/s]

[I 2026-07-13 11:43:34,254] Trial 385 finished with value: 0.9490747743086559 and parameters: {'weight_class_0': 0.008972527080106046, 'weight_class_1': 0.2152302874362387, 'weight_class_2': 0.18539256134467663}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,268] Trial 386 finished with value: 0.9489185277065211 and parameters: {'weight_class_0': 0.01979987466925352, 'weight_class_1': 0.4816656558734924, 'weight_class_2': 0.18005830886090965}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,295] Trial 387 finished with value: 0.9490644928348906 and parameters: {'weight_class_0': 0.019621409358115592, 'weight_class_1': 0.2136911506132447, 'weight_class_2': 0.19261864578532642}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,348] Trial 390 finished with value: 0.9467595294409432 and parameters: {'weight_class_0': 0.008852172887960164, 'weight_class_1': 0.38706039718721474, 'weight_class_2': 0.28193482273048}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,350] Trial 389 finished with value: 0.9468903384075945 and parameters: {'weight_class_0': 0.00909072283231256, 'weight_class_1': 0.37875801922009633, 'weight_class_2': 0.3006689083637169}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,356] Trial 388 finished with value: 0.9469008446222161 and parameters: {'weight_class_0': 0.00888627989768733, 'weight_class_1': 0.3986259653817085, 'weight_class_2': 0.24320944078234732}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,365] Trial 391 finished with value: 0.9482945537684828 and parameters: {'weight_class_0': 0.008318348722298235, 'weight_class_1': 0.20585395925543695, 'weight_class_2': 0.2513873767114979}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,385] Trial 392 finished with value: 0.9485652679691187 and parameters: {'weight_class_0': 0.02612473877657776, 'weight_class_1': 0.2100722838185148, 'weight_class_2': 0.2961523320329716}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,395] Trial 393 finished with value: 0.9491913443898352 and parameters: {'weight_class_0': 0.014759361610083711, 'weight_class_1': 0.3487477538138471, 'weight_class_2': 0.26936239778156246}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,410] Trial 394 finished with value: 0.9494030811394948 and parameters: {'weight_class_0': 0.025724831071308945, 'weight_class_1': 0.35505196261699284, 'weight_class_2': 0.28969461950697284}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,444] Trial 396 finished with value: 0.949450816062931 and parameters: {'weight_class_0': 0.02399164217096238, 'weight_class_1': 0.3445479723280901, 'weight_class_2': 0.28055844101991645}. Best is trial 277 with value: 0.9495624141169466.

Best trial: 277. Best value: 0.949562:  80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▉                           | 406/510 [00:07<00:02, 51.97it/s]

[I 2026-07-13 11:43:34,444] Trial 395 finished with value: 0.9491845851942357 and parameters: {'weight_class_0': 0.014712664117911067, 'weight_class_1': 0.3404757138854924, 'weight_class_2': 0.2793174205095598}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,476] Trial 397 finished with value: 0.9493289596707691 and parameters: {'weight_class_0': 0.026010150946806053, 'weight_class_1': 0.3607138439487183, 'weight_class_2': 0.2722862527435767}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,495] Trial 399 finished with value: 0.9494397930929321 and parameters: {'weight_class_0': 0.02412255608234945, 'weight_class_1': 0.34821324008168364, 'weight_class_2': 0.2743832502039844}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,501] Trial 398 finished with value: 0.9492957270784457 and parameters: {'weight_class_0': 0.02597137204482965, 'weight_class_1': 0.3371569411301021, 'weight_class_2': 0.2688147822201187}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,536] Trial 400 finished with value: 0.9488588985483667 and parameters: {'weight_class_0': 0.014544178745478203, 'weight_class_1': 0.30584335448232663, 'weight_class_2': 0.1211512392248133}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,551] Trial 402 finished with value: 0.948835334064502 and parameters: {'weight_class_0': 0.01465780389481246, 'weight_class_1': 0.3093491370186391, 'weight_class_2': 0.1198332843193283}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,594] Trial 401 finished with value: 0.9488520876386238 and parameters: {'weight_class_0': 0.014611617555847122, 'weight_class_1': 0.3129789279278593, 'weight_class_2': 0.11791455193915368}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,604] Trial 403 finished with value: 0.9490724482670808 and parameters: {'weight_class_0': 0.010619431800608231, 'weight_class_1': 0.29236306871991935, 'weight_class_2': 0.11963695979877673}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,614] Trial 404 finished with value: 0.9490684949749543 and parameters: {'weight_class_0': 0.01462098680551029, 'weight_class_1': 0.29219482256279733, 'weight_class_2': 0.1303452736788764}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,627] Trial 405 finished with value: 0.9489085643225078 and parameters: {'weight_class_0': 0.014002200245913508, 'weight_class_1': 0.2811194788376384, 'weight_class_2': 0.11720283659075913}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,656] Trial 406 finished with value: 0.8707571381497198 and parameters: {'weight_class_0': 0.24843601212993868, 'weight_class_1': 0.27446877075372184, 'weight_class_2': 0.12162459637276274}. Best is trial 277 with value: 0.9495624141169466.

Best trial: 277. Best value: 0.949562:  82%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                        | 417/510 [00:07<00:01, 51.62it/s]

[I 2026-07-13 11:43:34,680] Trial 408 finished with value: 0.9485505852601371 and parameters: {'weight_class_0': 0.014683126794031666, 'weight_class_1': 0.14489814192629397, 'weight_class_2': 0.11841305718699231}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,686] Trial 407 finished with value: 0.9489458060078347 and parameters: {'weight_class_0': 0.014565526346982747, 'weight_class_1': 0.1444088713959105, 'weight_class_2': 0.14081219380991633}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,712] Trial 409 finished with value: 0.9492457019630538 and parameters: {'weight_class_0': 0.010329690934961671, 'weight_class_1': 0.2598322460874352, 'weight_class_2': 0.12139576536315051}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,748] Trial 410 finished with value: 0.9494081274638076 and parameters: {'weight_class_0': 0.010782227923688622, 'weight_class_1': 0.14545971384980635, 'weight_class_2': 0.12022262948132001}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,759] Trial 411 finished with value: 0.9494742965789859 and parameters: {'weight_class_0': 0.010638028794067519, 'weight_class_1': 0.14887297065096652, 'weight_class_2': 0.1398329775964731}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,775] Trial 412 finished with value: 0.9493785769483795 and parameters: {'weight_class_0': 0.010998767342565585, 'weight_class_1': 0.25530323404885125, 'weight_class_2': 0.13241554627405766}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,812] Trial 413 finished with value: 0.9488977418901507 and parameters: {'weight_class_0': 0.010478847434129088, 'weight_class_1': 0.14217841381081603, 'weight_class_2': 0.22600607326801012}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,815] Trial 414 finished with value: 0.9490562435074502 and parameters: {'weight_class_0': 0.010558711493479535, 'weight_class_1': 0.14973175642096823, 'weight_class_2': 0.2193063742894733}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,828] Trial 415 finished with value: 0.9494909107318453 and parameters: {'weight_class_0': 0.01054339483095041, 'weight_class_1': 0.141081280272927, 'weight_class_2': 0.14772060116310845}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,873] Trial 416 finished with value: 0.9495156043567009 and parameters: {'weight_class_0': 0.011071244921269324, 'weight_class_1': 0.18340270607672216, 'weight_class_2': 0.14704279735637504}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,878] Trial 417 finished with value: 0.9490115674449466 and parameters: {'weight_class_0': 0.010171383123995799, 'weight_class_1': 0.1998560253066634, 'weight_class_2': 0.22885068492011626}. Best is trial 277 with value: 0.9495624141169466.

Best trial: 277. Best value: 0.949562:  84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                     | 428/510 [00:08<00:01, 52.23it/s]

[I 2026-07-13 11:43:34,897] Trial 418 finished with value: 0.9491574922465217 and parameters: {'weight_class_0': 0.010536998230627384, 'weight_class_1': 0.1918779429992946, 'weight_class_2': 0.21149200481198466}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,897] Trial 419 finished with value: 0.9495134292250079 and parameters: {'weight_class_0': 0.01049960767496239, 'weight_class_1': 0.1925250403294284, 'weight_class_2': 0.15464944831975194}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,937] Trial 420 finished with value: 0.9491620363387719 and parameters: {'weight_class_0': 0.018120238504845097, 'weight_class_1': 0.19283208089968287, 'weight_class_2': 0.22051585988195616}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,943] Trial 421 finished with value: 0.949037954457876 and parameters: {'weight_class_0': 0.01895168623995603, 'weight_class_1': 0.1946123879498651, 'weight_class_2': 0.22240237857472736}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,964] Trial 422 finished with value: 0.9491006606985618 and parameters: {'weight_class_0': 0.01881391339360633, 'weight_class_1': 0.19409681073531235, 'weight_class_2': 0.22706900536807362}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:34,993] Trial 423 finished with value: 0.9486691106055529 and parameters: {'weight_class_0': 0.016899526871253172, 'weight_class_1': 0.1979182773881574, 'weight_class_2': 0.3746553685018921}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,030] Trial 424 finished with value: 0.9486842527010211 and parameters: {'weight_class_0': 0.00631257483445247, 'weight_class_1': 0.08360352076887775, 'weight_class_2': 0.15188819858220495}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,038] Trial 425 finished with value: 0.948878762387649 and parameters: {'weight_class_0': 0.006692623022112014, 'weight_class_1': 0.10888912086591905, 'weight_class_2': 0.15679301402409732}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,046] Trial 426 finished with value: 0.9487363507997232 and parameters: {'weight_class_0': 0.007790942865124196, 'weight_class_1': 0.08340611203989046, 'weight_class_2': 0.1498178226527818}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,061] Trial 427 finished with value: 0.8688170961148204 and parameters: {'weight_class_0': 0.0065070918773009155, 'weight_class_1': 0.11104200466942568, 'weight_class_2': 2.2179219370408196}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,081] Trial 428 finished with value: 0.9488046689810682 and parameters: {'weight_class_0': 0.006469195495854805, 'weight_class_1': 0.11861356583390578, 'weight_class_2': 0.15943671188615233}. Best is trial 277 with value: 0.9495624141169466.

Best trial: 277. Best value: 0.949562:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                  | 439/510 [00:08<00:01, 51.63it/s]

[I 2026-07-13 11:43:35,098] Trial 429 finished with value: 0.8874100979718382 and parameters: {'weight_class_0': 0.007615349057147989, 'weight_class_1': 0.10134872581295576, 'weight_class_2': 2.1082876986860395}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,117] Trial 430 finished with value: 0.9489730662700016 and parameters: {'weight_class_0': 0.007563981622538147, 'weight_class_1': 0.10588719010705407, 'weight_class_2': 0.16042393771173846}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,159] Trial 432 finished with value: 0.9490201261605354 and parameters: {'weight_class_0': 0.007570561565807373, 'weight_class_1': 0.09894911012752822, 'weight_class_2': 0.15445908464545682}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,165] Trial 431 finished with value: 0.9493572527854193 and parameters: {'weight_class_0': 0.009142473885767064, 'weight_class_1': 0.14047810338051567, 'weight_class_2': 0.14960301489429811}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,173] Trial 433 finished with value: 0.9484889036177515 and parameters: {'weight_class_0': 0.006245384507498858, 'weight_class_1': 0.10849889004642994, 'weight_class_2': 0.17071227518959123}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,187] Trial 434 finished with value: 0.949084805793499 and parameters: {'weight_class_0': 0.007863561694073243, 'weight_class_1': 0.11182825700305608, 'weight_class_2': 0.16238775684234968}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,200] Trial 435 finished with value: 0.9489483565745634 and parameters: {'weight_class_0': 0.007498730335437692, 'weight_class_1': 0.11371716582657637, 'weight_class_2': 0.16388114662850475}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,249] Trial 436 finished with value: 0.9490382338481614 and parameters: {'weight_class_0': 0.008015143826398244, 'weight_class_1': 0.132668571709119, 'weight_class_2': 0.17243716881241633}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,255] Trial 438 finished with value: 0.9491669146502666 and parameters: {'weight_class_0': 0.00928350127413424, 'weight_class_1': 0.14310172394889956, 'weight_class_2': 0.18063562022667756}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,270] Trial 437 finished with value: 0.9490190756491761 and parameters: {'weight_class_0': 0.00801978834081242, 'weight_class_1': 0.14268068317729002, 'weight_class_2': 0.1772084742660847}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,289] Trial 439 finished with value: 0.949403664566253 and parameters: {'weight_class_0': 0.008348954610739132, 'weight_class_1': 0.1511158527114378, 'weight_class_2': 0.09426024139834405}. Best is trial 277 with value: 0.9495624141169466.

Best trial: 277. Best value: 0.949562:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎               | 450/510 [00:08<00:01, 51.64it/s]

[I 2026-07-13 11:43:35,311] Trial 440 finished with value: 0.9494463951673678 and parameters: {'weight_class_0': 0.008580612736609422, 'weight_class_1': 0.13080634716208214, 'weight_class_2': 0.09559463973772733}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,340] Trial 441 finished with value: 0.9487640635417195 and parameters: {'weight_class_0': 0.012518375876826414, 'weight_class_1': 0.23360960598725874, 'weight_class_2': 0.0952721798458305}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,367] Trial 442 finished with value: 0.9485342766881569 and parameters: {'weight_class_0': 0.012482465446603006, 'weight_class_1': 0.2329396122603621, 'weight_class_2': 0.09108031202935543}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,396] Trial 443 finished with value: 0.8139539982548415 and parameters: {'weight_class_0': 0.012173537270684116, 'weight_class_1': 0.22638552491509722, 'weight_class_2': 6.743891168682037}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,397] Trial 444 finished with value: 0.9486886637624156 and parameters: {'weight_class_0': 0.012772564977956442, 'weight_class_1': 0.22912115762687466, 'weight_class_2': 0.09672670911764997}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,404] Trial 445 finished with value: 0.948896168004867 and parameters: {'weight_class_0': 0.012316600802956192, 'weight_class_1': 0.22646135152668645, 'weight_class_2': 0.10071388416576661}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,431] Trial 446 finished with value: 0.9489365308789844 and parameters: {'weight_class_0': 0.011412488999007722, 'weight_class_1': 0.23674995639908775, 'weight_class_2': 0.09749546555500108}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,449] Trial 447 finished with value: 0.9486519380491271 and parameters: {'weight_class_0': 0.012614916925989806, 'weight_class_1': 0.17029316388350713, 'weight_class_2': 0.0933481377925692}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,467] Trial 448 finished with value: 0.8353062996833235 and parameters: {'weight_class_0': 0.012032454361750482, 'weight_class_1': 0.23087917579731984, 'weight_class_2': 5.585528010313435}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,496] Trial 449 finished with value: 0.9494308136821439 and parameters: {'weight_class_0': 0.012431109859835879, 'weight_class_1': 0.17570464843075556, 'weight_class_2': 0.13665065363036102}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,515] Trial 450 finished with value: 0.9493662358530002 and parameters: {'weight_class_0': 0.0129286179965784, 'weight_class_1': 0.18182805464425453, 'weight_class_2': 0.13730039405075495}. Best is trial 277 with value: 0.9495624141169466.

[I 2026-07-13 11:43:35,540] Trial 451 finished with value: 0.8652923919699879 and parameters: {'weight_class_0': 0.012293458530842764, 'weight_class_1': 3.7771056109226055, 'weight_class_2': 0.20085336212273328}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,562] Trial 452 finished with value: 0.9493759004074628 and parameters: {'weight_class_0': 0.011760987268506235, 'weight_class_1': 0.1889889418189125, 'weight_class_2': 0.19602473291819103}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,567] Trial 453 finished with value: 0.949170474540557 and parameters: {'weight_class_0': 0.010008351068308774, 'weight_class_1': 0.17475148998981718, 'weight_class_2': 0.20565771783926}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,591] Trial 454 finished with value: 0.9492002177512248 and parameters: {'weight_class_0': 0.010414385870075968, 'weight_class_1': 0.17602248523673217, 'weight_class_2': 0.2004273883655125}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,618] Trial 455 finished with value: 0.9491401761424099 and parameters: {'weight_class_0': 0.009826253164080888, 'weight_class_1': 0.17746418334224656, 'weight_class_2': 0.19997587142414996}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,628] Trial 456 finished with value: 0.9492089509148564 and parameters: {'weight_class_0': 0.010176026088945729, 'weight_class_1': 0.18061908413658312, 'weight_class_2': 0.19360529623637093}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,648] Trial 457 finished with value: 0.949167102182471 and parameters: {'weight_class_0': 0.01013818759689432, 'weight_class_1': 0.17837069612468856, 'weight_class_2': 0.20035843118355565}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,666] Trial 458 finished with value: 0.9491894747342338 and parameters: {'weight_class_0': 0.009664039311596158, 'weight_class_1': 0.18150733962487403, 'weight_class_2': 0.1990171397695236}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,681] Trial 459 finished with value: 0.9491806480267492 and parameters: {'weight_class_0': 0.00999931400507815, 'weight_class_1': 0.17871116350714197, 'weight_class_2': 0.19825887382681587}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,694] Trial 460 finished with value: 0.9492803350713147 and parameters: {'weight_class_0': 0.010219950556905732, 'weight_class_1': 0.1735310262882535, 'weight_class_2': 0.18589425980970073}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,729] Trial 461 finished with value: 0.9495504479136946 and parameters: {'weight_class_0': 0.009792975381682707, 'weight_class_1': 0.16880222556909374, 'weight_class_2': 0.13677286155881108}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,740] Trial 462 finished with value: 0.9494916279361593 and parameters: {'weight_class_0': 0.009592764824149926, 'weight_class_1': 0.1711358827172699, 'weight_class_2': 0.13536474034301468}. Best is trial 277 with value: 0.9495624141169466.

[I 2026-07-13 11:43:35,770] Trial 463 finished with value: 0.9494934004398542 and parameters: {'weight_class_0': 0.009308109962079565, 'weight_class_1': 0.15557002870611655, 'weight_class_2': 0.13559230773865372}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,781] Trial 464 finished with value: 0.8886685733295834 and parameters: {'weight_class_0': 0.009446237968200266, 'weight_class_1': 0.0021374479020030597, 'weight_class_2': 0.14031876886543018}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,818] Trial 466 finished with value: 0.9488943035200146 and parameters: {'weight_class_0': 0.016436040138166044, 'weight_class_1': 0.24912633617441315, 'weight_class_2': 0.13072322630812583}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,829] Trial 465 finished with value: 0.9491276717030784 and parameters: {'weight_class_0': 0.01572706972898826, 'weight_class_1': 0.26019966656228455, 'weight_class_2': 0.14056576032393744}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,872] Trial 468 finished with value: 0.9489452868799549 and parameters: {'weight_class_0': 0.01613618852654202, 'weight_class_1': 0.25475519546296604, 'weight_class_2': 0.13258862397629087}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,882] Trial 467 finished with value: 0.8144123139798133 and parameters: {'weight_class_0': 0.015717071768521093, 'weight_class_1': 7.212261084106465, 'weight_class_2': 0.13214170165240793}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,886] Trial 469 finished with value: 0.8765473527353475 and parameters: {'weight_class_0': 0.015009926965591183, 'weight_class_1': 0.001283145752084208, 'weight_class_2': 0.13807301561565108}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,905] Trial 470 finished with value: 0.9490497876871907 and parameters: {'weight_class_0': 0.015897139802294822, 'weight_class_1': 0.2581491502701819, 'weight_class_2': 0.13659586548969954}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,931] Trial 471 finished with value: 0.948396923982156 and parameters: {'weight_class_0': 0.016353082300042485, 'weight_class_1': 0.1459978114872236, 'weight_class_2': 0.13677034582928285}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:35,959] Trial 473 finished with value: 0.9484512247196877 and parameters: {'weight_class_0': 0.014701134541893599, 'weight_class_1': 0.1281487910398501, 'weight_class_2': 0.1332861108296582}. Best is trial 277 with value: 0.9495624141169466.

Best trial: 277. Best value: 0.949562:  95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋       | 482/510 [00:09<00:00, 46.75it/s]

[I 2026-07-13 11:43:35,972] Trial 472 finished with value: 0.9486238114704434 and parameters: {'weight_class_0': 0.015405245820875709, 'weight_class_1': 0.14495100041932016, 'weight_class_2': 0.135513867884377}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:36,026] Trial 475 finished with value: 0.9494946109608543 and parameters: {'weight_class_0': 0.008231636333077955, 'weight_class_1': 0.14465062687422897, 'weight_class_2': 0.11187445944494444}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:36,034] Trial 474 finished with value: 0.9483154505129088 and parameters: {'weight_class_0': 0.015018670644569755, 'weight_class_1': 0.1336088736136223, 'weight_class_2': 0.11826604518400081}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:36,041] Trial 476 finished with value: 0.9495011704526917 and parameters: {'weight_class_0': 0.008211195765041698, 'weight_class_1': 0.13959722603398314, 'weight_class_2': 0.12651883783631193}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:36,066] Trial 477 finished with value: 0.9494946356948764 and parameters: {'weight_class_0': 0.008406195324714765, 'weight_class_1': 0.1398034531591154, 'weight_class_2': 0.12313944474425075}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:36,072] Trial 478 finished with value: 0.9495154809080768 and parameters: {'weight_class_0': 0.00837386830346059, 'weight_class_1': 0.13695095696775927, 'weight_class_2': 0.11457890549996325}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:36,092] Trial 479 finished with value: 0.9494986288992836 and parameters: {'weight_class_0': 0.008582897178929757, 'weight_class_1': 0.14055419632225305, 'weight_class_2': 0.10875770761714135}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:36,126] Trial 480 finished with value: 0.9494679118387289 and parameters: {'weight_class_0': 0.008564483948591287, 'weight_class_1': 0.1343820159448237, 'weight_class_2': 0.11118554587676316}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:36,157] Trial 481 finished with value: 0.9494829846514085 and parameters: {'weight_class_0': 0.008002369167415401, 'weight_class_1': 0.14463938651410177, 'weight_class_2': 0.10488169991955627}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:36,158] Trial 482 finished with value: 0.9495008154419322 and parameters: {'weight_class_0': 0.008409795514510947, 'weight_class_1': 0.14397781474132437, 'weight_class_2': 0.110741009360835}. Best is trial 277 with value: 0.9495624141169466.

Best trial: 277. Best value: 0.949562:  96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎    | 492/510 [00:09<00:00, 46.58it/s]

[I 2026-07-13 11:43:36,173] Trial 483 finished with value: 0.9495123269328819 and parameters: {'weight_class_0': 0.00815852253252738, 'weight_class_1': 0.1447738756416158, 'weight_class_2': 0.11522188399327078}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:36,216] Trial 484 finished with value: 0.9493212269211063 and parameters: {'weight_class_0': 0.006312207882246911, 'weight_class_1': 0.07199038070989322, 'weight_class_2': 0.07960784572283136}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:36,253] Trial 485 finished with value: 0.9494572782431465 and parameters: {'weight_class_0': 0.006151439706506706, 'weight_class_1': 0.09001340533319895, 'weight_class_2': 0.07152311205084502}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:36,261] Trial 486 finished with value: 0.9492926054756072 and parameters: {'weight_class_0': 0.005954421924720634, 'weight_class_1': 0.07148386172229176, 'weight_class_2': 0.07734313320262276}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:36,272] Trial 487 finished with value: 0.9493661112041281 and parameters: {'weight_class_0': 0.005121962050902386, 'weight_class_1': 0.11814533117374058, 'weight_class_2': 0.06931864146148574}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:36,319] Trial 488 finished with value: 0.9494643516400485 and parameters: {'weight_class_0': 0.0056778853528569526, 'weight_class_1': 0.08459436784111972, 'weight_class_2': 0.07459747717403399}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:36,325] Trial 489 finished with value: 0.9489737008351486 and parameters: {'weight_class_0': 0.004591867405557521, 'weight_class_1': 0.08164726425256298, 'weight_class_2': 0.1022643998361483}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:36,360] Trial 491 finished with value: 0.9495002483912852 and parameters: {'weight_class_0': 0.005376008923366938, 'weight_class_1': 0.09383253790808857, 'weight_class_2': 0.0731727843193724}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:36,365] Trial 490 finished with value: 0.9494330606926059 and parameters: {'weight_class_0': 0.004969468438395163, 'weight_class_1': 0.08324715284897666, 'weight_class_2': 0.08170932889798656}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:36,387] Trial 492 finished with value: 0.949162295310099 and parameters: {'weight_class_0': 0.004020711505861546, 'weight_class_1': 0.07660256864241635, 'weight_class_2': 0.08375227816516154}. Best is trial 277 with value: 0.9495624141169466.

Best trial: 277. Best value: 0.949562:  99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉ | 506/510 [00:09<00:00, 50.36it/s]

[I 2026-07-13 11:43:36,412] Trial 493 finished with value: 0.9494255533802344 and parameters: {'weight_class_0': 0.006063916424036061, 'weight_class_1': 0.07800964457564957, 'weight_class_2': 0.08094735995835844}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:36,434] Trial 494 finished with value: 0.9495503003068029 and parameters: {'weight_class_0': 0.005625935263460346, 'weight_class_1': 0.0941895829540638, 'weight_class_2': 0.078989084692306}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:36,468] Trial 496 finished with value: 0.9493342918388811 and parameters: {'weight_class_0': 0.004534381459873493, 'weight_class_1': 0.08435647310445883, 'weight_class_2': 0.08526441475185628}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:36,483] Trial 497 finished with value: 0.949535092256669 and parameters: {'weight_class_0': 0.006169189431739487, 'weight_class_1': 0.1031705947380858, 'weight_class_2': 0.08382470264739536}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:36,491] Trial 495 finished with value: 0.9493964970579231 and parameters: {'weight_class_0': 0.0051480094470669445, 'weight_class_1': 0.0969674581167743, 'weight_class_2': 0.08642051779958913}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:36,522] Trial 498 finished with value: 0.8901376519262229 and parameters: {'weight_class_0': 0.006891799129579283, 'weight_class_1': 0.13192736430097865, 'weight_class_2': 0.0015149203322624867}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:36,535] Trial 499 finished with value: 0.9495006888012938 and parameters: {'weight_class_0': 0.006326359362251152, 'weight_class_1': 0.10661536572942171, 'weight_class_2': 0.08184608944369673}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:36,563] Trial 500 finished with value: 0.9490793495440896 and parameters: {'weight_class_0': 0.00658375020296236, 'weight_class_1': 0.09513727336383286, 'weight_class_2': 0.0596461031107068}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:36,570] Trial 501 finished with value: 0.9482650527746906 and parameters: {'weight_class_0': 0.002716021010478001, 'weight_class_1': 0.09979815104109586, 'weight_class_2': 0.05298406504882857}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:36,579] Trial 502 finished with value: 0.9484588162228804 and parameters: {'weight_class_0': 0.006968838450362597, 'weight_class_1': 0.10343154826799893, 'weight_class_2': 0.049895051868116116}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:36,608] Trial 503 finished with value: 0.949419977216383 and parameters: {'weight_class_0': 0.004613151329596044, 'weight_class_1': 0.09674097776028569, 'weight_class_2': 0.05868486710560676}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:36,640] Trial 504 finished with value: 0.9483454156918453 and parameters: {'weight_class_0': 0.0028874464877855226, 'weight_class_1': 0.09465222637697013, 'weight_class_2': 0.06918923064176935}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:36,657] Trial 505 finished with value: 0.949454066663483 and parameters: {'weight_class_0': 0.003630024082120569, 'weight_class_1': 0.06608562260520642, 'weight_class_2': 0.05393738756512809}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:36,668] Trial 507 finished with value: 0.9495162450669716 and parameters: {'weight_class_0': 0.0031116143938149463, 'weight_class_1': 0.05733213494149894, 'weight_class_2': 0.04786224224808194}. Best is trial 277 with value: 0.9495624141169466.

Best trial: 277. Best value: 0.949562: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 510/510 [00:09<00:00, 53.02it/s]

[I 2026-07-13 11:43:36,675] Trial 506 finished with value: 0.9493901406056843 and parameters: {'weight_class_0': 0.0051628136724108905, 'weight_class_1': 0.099715723785754, 'weight_class_2': 0.05718245227751937}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:36,679] Trial 508 finished with value: 0.9491651582581797 and parameters: {'weight_class_0': 0.0035960059933299203, 'weight_class_1': 0.04111301405354791, 'weight_class_2': 0.05803865184875706}. Best is trial 277 with value: 0.9495624141169466.
[I 2026-07-13 11:43:36,694] Trial 509 finished with value: 0.9493408133508288 and parameters: {'weight_class_0': 0.004266641118092803, 'weight_class_1': 0.061202820563150635, 'weight_class_2': 0.07176064010297077}. Best is trial 277 with value: 0.9495624141169466.

Best trial score:
0.9495624141169466

Best params:
{'weight_class_0': 0.010880207806710639, 'weight_class_1': 0.173906383023136, 'weight_class_2': 0.16713098563667145}

In [46]:
weights = np.array([study.best_params['weight_class_0'], study.best_params['weight_class_1'], study.best_params['weight_class_2']])
weighted_probas = X_test.loc[:, ['xgb_0', 'xgb_1', 'xgb_2']].to_numpy() * weights

pred = np.argmax(weighted_probas, axis=1)

In [47]:
sub_labels = label_encoder.inverse_transform(pred)

# Submission

In [48]:
submission = pd.read_csv('../data/submission/sample_submission.csv')
submission['health_condition'] = sub_labels

submission.to_csv('../data/submission/submission_from_5.0_xgboost_submission.csv', index=False)

In [49]:
submission.head()

       id health_condition
0  690088        unhealthy
1  690089        unhealthy
2  690090          at-risk
3  690091          at-risk
4  690092        unhealthy