# Imports

In [1]:
import optuna
import pickle

import numpy as np
import pandas as pd

from tqdm import tqdm

from sklearn.metrics import balanced_accuracy_score
from sklearn.model_selection import StratifiedKFold, cross_val_predict

/home/junior/Documentos/GitHub/kaggle-competition-predicting-student-health/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Utils

In [2]:
def load_pickle(file_path):
    with open(file_path, 'rb') as file:
        return pickle.load(file)

# Loading Datasets

In [3]:
X_train = pd.read_parquet('../data/processed/X_train_stacking_layer_one_model_60_trials.parquet')
y_train = pd.read_parquet('../data/interim/y_train.parquet')

X_test = pd.read_parquet('../data/processed/X_test_stacking_layer_one_model_60_trials.parquet')

In [4]:
X_train.head()

     lgbm_0    lgbm_1    lgbm_2     xgb_0     xgb_1     xgb_2
0  0.004922  0.001773  0.993304  0.004134  0.002593  0.993273
1  0.997228  0.000463  0.002309  0.995591  0.000405  0.004004
2  0.002369  0.000604  0.997026  0.001958  0.000503  0.997538
3  0.004656  0.003362  0.991982  0.002466  0.002391  0.995142
4  0.995353  0.000016  0.004632  0.994178  0.000003  0.005819

In [5]:
X_test.head()

     lgbm_0    lgbm_1    lgbm_2     xgb_0     xgb_1     xgb_2
0  0.012452  0.003199  0.984349  0.011048  0.004491  0.984461
1  0.472116  0.002331  0.525553  0.499186  0.001896  0.498918
2  0.998690  0.001012  0.000298  0.997826  0.001594  0.000579
3  0.980854  0.000018  0.019128  0.987434  0.000009  0.012557
4  0.006765  0.001847  0.991388  0.006876  0.001972  0.991152

# Machine Learning

In [6]:
label_encoder = load_pickle('../artifacts/label_encoder.pkl')

In [7]:
cols_use = ['lgbm_0', 'lgbm_1', 'lgbm_2']

In [8]:
def objective(trial, X, y):

    w0 = trial.suggest_float('weight_class_0', 0.0, 10.0, log=False)
    w1 = trial.suggest_float('weight_class_1', 0.0, 10.0, log=False)
    w2 = trial.suggest_float('weight_class_2', 0.0, 10.0, log=False)
    weights = np.array([w0, w1, w2])

    proba = X.loc[:, cols_use].to_numpy()
    
    weighted_probas = proba * weights
    pred = np.argmax(weighted_probas, axis=1)
    
    score = balanced_accuracy_score(y, pred)

    return score


study = optuna.create_study(
    direction="maximize", 
    sampler=optuna.samplers.TPESampler(seed=42), 
    pruner=optuna.pruners.MedianPruner(n_warmup_steps=2)
)

study.optimize(
    lambda trial: objective(trial, X_train, y_train.health_condition), 
    n_trials=1000, 
    n_jobs=-1, 
    show_progress_bar=True
)

print("\nBest trial score:")
print(study.best_trial.value)

print("\nBest params:")
print(study.best_trial.params)

[I 2026-07-05 15:04:15,093] A new study created in memory with name: no-name-ff6e9dd6-4fe5-4e64-a47a-5814f95751ba

[I 2026-07-05 15:04:15,257] Trial 8 finished with value: 0.918852203716967 and parameters: {'weight_class_0': 0.3814428378181878, 'weight_class_1': 0.39411919330551215, 'weight_class_2': 3.439349748982803}. Best is trial 8 with value: 0.918852203716967.
[I 2026-07-05 15:04:15,273] Trial 1 finished with value: 0.8541214198552605 and parameters: {'weight_class_0': 6.489242893387227, 'weight_class_1': 1.2243729189974817, 'weight_class_2': 7.751264470212734}. Best is trial 8 with value: 0.918852203716967.
[I 2026-07-05 15:04:15,275] Trial 5 finished with value: 0.8400025005253053 and parameters: {'weight_class_0': 4.172370295868767, 'weight_class_1': 1.308952215170579, 'weight_class_2': 1.6014568741014656}. Best is trial 8 with value: 0.918852203716967.
[I 2026-07-05 15:04:15,276] Trial 11 finished with value: 0.8413032521260743 and parameters: {'weight_class_0': 6.072748681784892, 'weight_class_1': 2.598935670213993, 'weight_class_2': 1.0451972104993912}. Best is trial 8 with value: 0.918852203716967.
[I 2026-07-05 15:04:15,280] Trial 3 finished with value: 0.9022630398648395 and parameters: {'weight_class_0': 2.814136467311801, 'weight_class_1': 1.9752135992442466, 'weight_class_2': 8.466353390364134}. Best is trial 8 with value: 0.918852203716967.
[I 2026-07-05 15:04:15,282] Trial 6 finished with value: 0.8790848169513009 and parameters: {'weight_class_0': 1.6083292917868142, 'weight_class_1': 0.24884775321330155, 'weight_class_2': 6.147829378984053}. Best is trial 8 with value: 0.918852203716967.
[I 2026-07-05 15:04:15,286] Trial 7 finished with value: 0.861634398738615 and parameters: {'weight_class_0': 4.8654318638650285, 'weight_class_1': 3.771580835386199, 'weight_class_2': 2.689540994222388}. Best is trial 8 with value: 0.918852203716967.
[I 2026-07-05 15:04:15,287] Trial 4 finished with value: 0.9437059633423232 and parameters: {'weight_class_0': 0.9290375274050866, 'weight_class_1': 3.19521949244586, 'weight_class_2': 6.695204640036081}. Best is trial 4 with value: 0.9437059633423232.
[I 2026-07-05 15:04:15,289] Trial 2 finished with value: 0.8586917102983979 and parameters: {'weight_class_0': 6.819678290418604, 'weight_class_1': 5.0899109884327975, 'weight_class_2': 3.102470253125027}. Best is trial 4 with value: 0.9437059633423232.
[I 2026-07-05 15:04:15,293] Trial 9 finished with value: 0.9253333751126674 and parameters: {'weight_class_0': 3.773606860785942, 'weight_class_1': 9.900730364348618, 'weight_class_2': 7.74282172588914}. Best is trial 4 with value: 0.9437059633423232.
[I 2026-07-05 15:04:15,304] Trial 10 finished with value: 0.9431240110210863 and parameters: {'weight_class_0': 1.1581154107067793, 'weight_class_1': 4.090250501318613, 'weight_class_2': 6.238252655305574}. Best is trial 4 with value: 0.9437059633423232.
[I 2026-07-05 15:04:15,310] Trial 0 finished with value: 0.8262822433977909 and parameters: {'weight_class_0': 8.284812235063729, 'weight_class_1': 0.7509243481326477, 'weight_class_2': 3.6932568080223325}. Best is trial 4 with value: 0.9437059633423232.

Best trial: 14. Best value: 0.949616:   2%|██▉                                                                                                                                   | 22/1000 [00:00<00:21, 45.92it/s]

[I 2026-07-05 15:04:15,419] Trial 12 finished with value: 0.8675662578778782 and parameters: {'weight_class_0': 8.895016442189174, 'weight_class_1': 5.754974154026845, 'weight_class_2': 8.080092868740795}. Best is trial 4 with value: 0.9437059633423232.
[I 2026-07-05 15:04:15,421] Trial 13 finished with value: 0.8774642825630953 and parameters: {'weight_class_0': 9.208814926022495, 'weight_class_1': 7.348200751975093, 'weight_class_2': 9.964256735918514}. Best is trial 4 with value: 0.9437059633423232.
[I 2026-07-05 15:04:15,430] Trial 14 finished with value: 0.949616096912061 and parameters: {'weight_class_0': 0.4671959043557937, 'weight_class_1': 5.5882527153470605, 'weight_class_2': 5.791298450230845}. Best is trial 14 with value: 0.949616096912061.
[I 2026-07-05 15:04:15,462] Trial 16 finished with value: 0.9489327990058407 and parameters: {'weight_class_0': 0.25421834987736636, 'weight_class_1': 5.010253954794902, 'weight_class_2': 5.530522603692354}. Best is trial 14 with value: 0.949616096912061.
[I 2026-07-05 15:04:15,464] Trial 15 finished with value: 0.947714286462447 and parameters: {'weight_class_0': 0.1769578831866454, 'weight_class_1': 5.757627983713552, 'weight_class_2': 5.658422551359056}. Best is trial 14 with value: 0.949616096912061.
[I 2026-07-05 15:04:15,484] Trial 17 finished with value: 0.9493614749612999 and parameters: {'weight_class_0': 0.30847891457749177, 'weight_class_1': 6.06551732101094, 'weight_class_2': 5.664781156086811}. Best is trial 14 with value: 0.949616096912061.
[I 2026-07-05 15:04:15,511] Trial 18 finished with value: 0.949563607842935 and parameters: {'weight_class_0': 0.36393896257170577, 'weight_class_1': 6.238370449618683, 'weight_class_2': 5.695897476752065}. Best is trial 14 with value: 0.949616096912061.
[I 2026-07-05 15:04:15,524] Trial 19 finished with value: 0.9482503151580263 and parameters: {'weight_class_0': 0.2197403578996191, 'weight_class_1': 5.864293096521733, 'weight_class_2': 6.031806528869823}. Best is trial 14 with value: 0.949616096912061.
[I 2026-07-05 15:04:15,551] Trial 20 finished with value: 0.9495092231042822 and parameters: {'weight_class_0': 0.41336151537514976, 'weight_class_1': 5.913088995485957, 'weight_class_2': 6.26419690079118}. Best is trial 14 with value: 0.949616096912061.
[I 2026-07-05 15:04:15,595] Trial 22 finished with value: 0.8033860318737625 and parameters: {'weight_class_0': 0.020332743179974244, 'weight_class_1': 7.074769877676344, 'weight_class_2': 5.319321123738899}. Best is trial 14 with value: 0.949616096912061.
[I 2026-07-05 15:04:15,610] Trial 21 finished with value: 0.9284653474706803 and parameters: {'weight_class_0': 2.4015460045365637, 'weight_class_1': 6.94892552182969, 'weight_class_2': 5.24841422053408}. Best is trial 14 with value: 0.949616096912061.

Best trial: 14. Best value: 0.949616:   3%|████▌                                                                                                                                 | 34/1000 [00:00<00:19, 48.93it/s]

[I 2026-07-05 15:04:15,619] Trial 23 finished with value: 0.9289774861720632 and parameters: {'weight_class_0': 2.1558421244885095, 'weight_class_1': 7.471481361106866, 'weight_class_2': 4.3887467071429125}. Best is trial 14 with value: 0.949616096912061.
[I 2026-07-05 15:04:15,641] Trial 24 finished with value: 0.9272117052278083 and parameters: {'weight_class_0': 2.3322891501061527, 'weight_class_1': 7.4332033444114884, 'weight_class_2': 4.5818435683125305}. Best is trial 14 with value: 0.949616096912061.
[I 2026-07-05 15:04:15,656] Trial 25 finished with value: 0.9268283706937673 and parameters: {'weight_class_0': 2.318253745030796, 'weight_class_1': 7.556686063812084, 'weight_class_2': 4.449030070096469}. Best is trial 14 with value: 0.949616096912061.
[I 2026-07-05 15:04:15,671] Trial 26 finished with value: 0.930266025098757 and parameters: {'weight_class_0': 2.2091302320063564, 'weight_class_1': 7.7243749130479955, 'weight_class_2': 4.708291847473935}. Best is trial 14 with value: 0.949616096912061.
[I 2026-07-05 15:04:15,695] Trial 27 finished with value: 0.9309896271723223 and parameters: {'weight_class_0': 2.2651180045288446, 'weight_class_1': 7.723142158176888, 'weight_class_2': 5.015623597438748}. Best is trial 14 with value: 0.949616096912061.
[I 2026-07-05 15:04:15,706] Trial 29 finished with value: 0.9305388781370288 and parameters: {'weight_class_0': 2.1797347983758413, 'weight_class_1': 7.7931058139421, 'weight_class_2': 4.6522974103460335}. Best is trial 14 with value: 0.949616096912061.
[I 2026-07-05 15:04:15,725] Trial 30 finished with value: 0.9284912690636302 and parameters: {'weight_class_0': 2.168606071889114, 'weight_class_1': 7.438610625987705, 'weight_class_2': 4.351991275732872}. Best is trial 14 with value: 0.949616096912061.
[I 2026-07-05 15:04:15,737] Trial 28 finished with value: 0.9303358384547625 and parameters: {'weight_class_0': 2.1332036746542995, 'weight_class_1': 7.775988920086931, 'weight_class_2': 4.479587658076149}. Best is trial 14 with value: 0.949616096912061.
[I 2026-07-05 15:04:15,776] Trial 31 finished with value: 0.9389125269378865 and parameters: {'weight_class_0': 1.6180627523598075, 'weight_class_1': 8.544875180931491, 'weight_class_2': 4.404600437397252}. Best is trial 14 with value: 0.949616096912061.
[I 2026-07-05 15:04:15,778] Trial 32 finished with value: 0.938832608671467 and parameters: {'weight_class_0': 1.668963725416483, 'weight_class_1': 8.755057129153744, 'weight_class_2': 4.53824812491008}. Best is trial 14 with value: 0.949616096912061.
[I 2026-07-05 15:04:15,790] Trial 33 finished with value: 0.9471134383598384 and parameters: {'weight_class_0': 1.3749422381253649, 'weight_class_1': 8.926162743020493, 'weight_class_2': 7.174358411767748}. Best is trial 14 with value: 0.949616096912061.
[I 2026-07-05 15:04:15,818] Trial 34 finished with value: 0.9479824480891601 and parameters: {'weight_class_0': 1.360749870424697, 'weight_class_1': 9.020304305547013, 'weight_class_2': 9.062248838249282}. Best is trial 14 with value: 0.949616096912061.

Best trial: 14. Best value: 0.949616:   4%|██████                                                                                                                                | 45/1000 [00:01<00:18, 50.33it/s]

[I 2026-07-05 15:04:15,841] Trial 35 finished with value: 0.94825283799321 and parameters: {'weight_class_0': 1.1227549083383919, 'weight_class_1': 8.976439448190554, 'weight_class_2': 7.223973608990065}. Best is trial 14 with value: 0.949616096912061.
[I 2026-07-05 15:04:15,854] Trial 36 finished with value: 0.9486014698152451 and parameters: {'weight_class_0': 1.0418583220314401, 'weight_class_1': 9.076365728335116, 'weight_class_2': 6.968871748985202}. Best is trial 14 with value: 0.949616096912061.
[I 2026-07-05 15:04:15,877] Trial 37 finished with value: 0.9467610907680882 and parameters: {'weight_class_0': 1.1555637574218358, 'weight_class_1': 6.474593026156866, 'weight_class_2': 6.984784145501893}. Best is trial 14 with value: 0.949616096912061.
[I 2026-07-05 15:04:15,889] Trial 38 finished with value: 0.9468928443299472 and parameters: {'weight_class_0': 1.12824743848924, 'weight_class_1': 6.425961712148474, 'weight_class_2': 6.81681110960554}. Best is trial 14 with value: 0.949616096912061.
[I 2026-07-05 15:04:15,935] Trial 40 finished with value: 0.9481550127790727 and parameters: {'weight_class_0': 0.9863522343706014, 'weight_class_1': 6.412111931178922, 'weight_class_2': 7.192652200840058}. Best is trial 14 with value: 0.949616096912061.
[I 2026-07-05 15:04:15,943] Trial 39 finished with value: 0.9480763390304762 and parameters: {'weight_class_0': 0.8128845845487788, 'weight_class_1': 4.757056227059848, 'weight_class_2': 7.174055440858866}. Best is trial 14 with value: 0.949616096912061.
[I 2026-07-05 15:04:15,960] Trial 41 finished with value: 0.9495920738815017 and parameters: {'weight_class_0': 0.6557392481901765, 'weight_class_1': 6.272772066962264, 'weight_class_2': 6.903497042633178}. Best is trial 14 with value: 0.949616096912061.
[I 2026-07-05 15:04:15,971] Trial 42 finished with value: 0.9491909323812168 and parameters: {'weight_class_0': 0.7838661001982108, 'weight_class_1': 6.350770773073239, 'weight_class_2': 6.906766678695647}. Best is trial 14 with value: 0.949616096912061.
[I 2026-07-05 15:04:15,999] Trial 43 finished with value: 0.9490829627473918 and parameters: {'weight_class_0': 0.7830586496179355, 'weight_class_1': 6.291817323423992, 'weight_class_2': 6.50314329647559}. Best is trial 14 with value: 0.949616096912061.
[I 2026-07-05 15:04:16,022] Trial 44 finished with value: 0.9137613049076924 and parameters: {'weight_class_0': 3.578427120592564, 'weight_class_1': 6.365835811057516, 'weight_class_2': 6.317636361066252}. Best is trial 14 with value: 0.949616096912061.
[I 2026-07-05 15:04:16,037] Trial 45 finished with value: 0.8885214928805589 and parameters: {'weight_class_0': 2.9473198878032365, 'weight_class_1': 4.872717787913242, 'weight_class_2': 2.39792593304214}. Best is trial 14 with value: 0.949616096912061.

Best trial: 59. Best value: 0.949617:   6%|███████▋                                                                                                                              | 57/1000 [00:01<00:17, 52.91it/s]

[I 2026-07-05 15:04:16,043] Trial 46 finished with value: 0.8833216578337776 and parameters: {'weight_class_0': 3.1880906189242992, 'weight_class_1': 4.467557068765068, 'weight_class_2': 2.4517927619829583}. Best is trial 14 with value: 0.949616096912061.
[I 2026-07-05 15:04:16,062] Trial 47 finished with value: 0.8863149762524944 and parameters: {'weight_class_0': 3.135170931644878, 'weight_class_1': 4.652673971126316, 'weight_class_2': 2.590210773261601}. Best is trial 14 with value: 0.949616096912061.
[I 2026-07-05 15:04:16,083] Trial 48 finished with value: 0.9494222356686555 and parameters: {'weight_class_0': 0.5945040607280162, 'weight_class_1': 5.117608187522504, 'weight_class_2': 5.727253006569406}. Best is trial 14 with value: 0.949616096912061.
[I 2026-07-05 15:04:16,106] Trial 49 finished with value: 0.9492105924449649 and parameters: {'weight_class_0': 0.6001921686226025, 'weight_class_1': 4.60911437680064, 'weight_class_2': 6.366266558239934}. Best is trial 14 with value: 0.949616096912061.
[I 2026-07-05 15:04:16,137] Trial 51 finished with value: 0.9137376332527157 and parameters: {'weight_class_0': 2.9544669674767055, 'weight_class_1': 4.602086615034849, 'weight_class_2': 5.9296790913060295}. Best is trial 14 with value: 0.949616096912061.
[I 2026-07-05 15:04:16,140] Trial 50 finished with value: 0.908254266378074 and parameters: {'weight_class_0': 3.3726972695540445, 'weight_class_1': 4.4503326638848755, 'weight_class_2': 6.38321277866167}. Best is trial 14 with value: 0.949616096912061.
[I 2026-07-05 15:04:16,174] Trial 52 finished with value: 0.949387432736271 and parameters: {'weight_class_0': 0.4685761018075235, 'weight_class_1': 4.595622924847292, 'weight_class_2': 5.8066491040072865}. Best is trial 14 with value: 0.949616096912061.
[I 2026-07-05 15:04:16,193] Trial 53 finished with value: 0.8705793628520131 and parameters: {'weight_class_0': 0.5848970745071316, 'weight_class_1': 4.450930597609212, 'weight_class_2': 0.022937848207432943}. Best is trial 14 with value: 0.949616096912061.
[I 2026-07-05 15:04:16,199] Trial 54 finished with value: 0.9480165248015142 and parameters: {'weight_class_0': 0.5723072148471485, 'weight_class_1': 3.997494296326237, 'weight_class_2': 3.7365374211624847}. Best is trial 14 with value: 0.949616096912061.
[I 2026-07-05 15:04:16,227] Trial 56 finished with value: 0.9492323985141212 and parameters: {'weight_class_0': 0.5547541529421306, 'weight_class_1': 5.396254412186717, 'weight_class_2': 7.862678139814778}. Best is trial 14 with value: 0.949616096912061.
[I 2026-07-05 15:04:16,245] Trial 55 finished with value: 0.9493027298180383 and parameters: {'weight_class_0': 0.5884351558641986, 'weight_class_1': 5.512085349248657, 'weight_class_2': 7.833118020577922}. Best is trial 14 with value: 0.949616096912061.
[I 2026-07-05 15:04:16,260] Trial 57 finished with value: 0.8748995179026468 and parameters: {'weight_class_0': 0.03371152639408315, 'weight_class_1': 5.396211431675133, 'weight_class_2': 7.772112386570155}. Best is trial 14 with value: 0.949616096912061.

Best trial: 59. Best value: 0.949617:   7%|█████████▍                                                                                                                            | 70/1000 [00:01<00:16, 55.56it/s]

[I 2026-07-05 15:04:16,290] Trial 58 finished with value: 0.9495690648857927 and parameters: {'weight_class_0': 0.4764436354326086, 'weight_class_1': 5.554673205888068, 'weight_class_2': 5.895011096776942}. Best is trial 14 with value: 0.949616096912061.
[I 2026-07-05 15:04:16,303] Trial 60 finished with value: 0.9491021042261685 and parameters: {'weight_class_0': 0.4279092591074808, 'weight_class_1': 5.455415429001508, 'weight_class_2': 7.682458368322665}. Best is trial 14 with value: 0.949616096912061.
[I 2026-07-05 15:04:16,305] Trial 59 finished with value: 0.949616534911403 and parameters: {'weight_class_0': 0.5111134596292148, 'weight_class_1': 5.475211071270607, 'weight_class_2': 5.765893381699381}. Best is trial 59 with value: 0.949616534911403.
[I 2026-07-05 15:04:16,354] Trial 61 finished with value: 0.8104448029003404 and parameters: {'weight_class_0': 0.01930434527509134, 'weight_class_1': 5.484976386264361, 'weight_class_2': 5.966628775791343}. Best is trial 59 with value: 0.949616534911403.
[I 2026-07-05 15:04:16,361] Trial 62 finished with value: 0.8608738565018882 and parameters: {'weight_class_0': 9.97092519099723, 'weight_class_1': 5.292893969303714, 'weight_class_2': 8.150207355941252}. Best is trial 59 with value: 0.949616534911403.
[I 2026-07-05 15:04:16,367] Trial 63 finished with value: 0.8560345353480162 and parameters: {'weight_class_0': 7.288807628947753, 'weight_class_1': 3.1082812448643455, 'weight_class_2': 5.808057654220467}. Best is trial 59 with value: 0.949616534911403.
[I 2026-07-05 15:04:16,395] Trial 64 finished with value: 0.9266408762794557 and parameters: {'weight_class_0': 0.04467464943130428, 'weight_class_1': 5.325054121589266, 'weight_class_2': 3.840578767226968}. Best is trial 59 with value: 0.949616534911403.
[I 2026-07-05 15:04:16,411] Trial 66 finished with value: 0.8574207313602007 and parameters: {'weight_class_0': 7.2579686190118515, 'weight_class_1': 3.3246189890663858, 'weight_class_2': 5.8180835772960275}. Best is trial 59 with value: 0.949616534911403.
[I 2026-07-05 15:04:16,416] Trial 65 finished with value: 0.9297495667131388 and parameters: {'weight_class_0': 1.6922793802334501, 'weight_class_1': 3.2612173965285605, 'weight_class_2': 5.865585725442047}. Best is trial 59 with value: 0.949616534911403.
[I 2026-07-05 15:04:16,447] Trial 67 finished with value: 0.9270802701684396 and parameters: {'weight_class_0': 1.7850020855417092, 'weight_class_1': 3.4056892762349125, 'weight_class_2': 5.211263332206427}. Best is trial 59 with value: 0.949616534911403.
[I 2026-07-05 15:04:16,461] Trial 68 finished with value: 0.8708889194029075 and parameters: {'weight_class_0': 7.3120213023581, 'weight_class_1': 6.88532307903175, 'weight_class_2': 5.25588443536333}. Best is trial 59 with value: 0.949616534911403.
[I 2026-07-05 15:04:16,471] Trial 69 finished with value: 0.9406280790446176 and parameters: {'weight_class_0': 1.5728519463422197, 'weight_class_1': 6.840371201630146, 'weight_class_2': 5.134275058774072}. Best is trial 59 with value: 0.949616534911403.
[I 2026-07-05 15:04:16,495] Trial 70 finished with value: 0.9274089226164465 and parameters: {'weight_class_0': 1.7619979962434096, 'weight_class_1': 3.4235194381819256, 'weight_class_2': 5.074713830015492}. Best is trial 59 with value: 0.949616534911403.

[I 2026-07-05 15:04:16,507] Trial 71 finished with value: 0.9393537531130125 and parameters: {'weight_class_0': 1.6569666068737865, 'weight_class_1': 6.734082925300636, 'weight_class_2': 5.100819995011484}. Best is trial 59 with value: 0.949616534911403.
[I 2026-07-05 15:04:16,533] Trial 72 finished with value: 0.9366250890367804 and parameters: {'weight_class_0': 1.8698047523102597, 'weight_class_1': 6.761234244339911, 'weight_class_2': 5.221914768771101}. Best is trial 59 with value: 0.949616534911403.
[I 2026-07-05 15:04:16,550] Trial 73 finished with value: 0.9375382908380171 and parameters: {'weight_class_0': 1.7775676085327663, 'weight_class_1': 6.930179324705722, 'weight_class_2': 5.049770707511304}. Best is trial 59 with value: 0.949616534911403.
[I 2026-07-05 15:04:16,567] Trial 74 finished with value: 0.9376275782598024 and parameters: {'weight_class_0': 1.7895680717313962, 'weight_class_1': 6.90160879426056, 'weight_class_2': 5.133790946818997}. Best is trial 59 with value: 0.949616534911403.
[I 2026-07-05 15:04:16,595] Trial 75 finished with value: 0.9016744957578912 and parameters: {'weight_class_0': 4.237067938014471, 'weight_class_1': 6.91598642918421, 'weight_class_2': 5.472021635806218}. Best is trial 59 with value: 0.949616534911403.
[I 2026-07-05 15:04:16,611] Trial 76 finished with value: 0.9437329353564018 and parameters: {'weight_class_0': 1.4279918811674133, 'weight_class_1': 5.9369679974508935, 'weight_class_2': 6.626064701031877}. Best is trial 59 with value: 0.949616534911403.
[I 2026-07-05 15:04:16,646] Trial 77 finished with value: 0.934855156811334 and parameters: {'weight_class_0': 1.9427138667990538, 'weight_class_1': 5.963663006198845, 'weight_class_2': 5.4707144832666765}. Best is trial 59 with value: 0.949616534911403.
[I 2026-07-05 15:04:16,648] Trial 78 finished with value: 0.9420617058800035 and parameters: {'weight_class_0': 1.436074189384261, 'weight_class_1': 6.027292927444336, 'weight_class_2': 5.499245494525293}. Best is trial 59 with value: 0.949616534911403.
[I 2026-07-05 15:04:16,663] Trial 79 finished with value: 0.9494134362883114 and parameters: {'weight_class_0': 0.3243797461138973, 'weight_class_1': 5.902199211597013, 'weight_class_2': 5.599056907813258}. Best is trial 59 with value: 0.949616534911403.
[I 2026-07-05 15:04:16,692] Trial 80 finished with value: 0.9490587129610685 and parameters: {'weight_class_0': 0.33487130079781113, 'weight_class_1': 5.911605492831059, 'weight_class_2': 6.698630859583984}. Best is trial 59 with value: 0.949616534911403.
[I 2026-07-05 15:04:16,695] Trial 81 finished with value: 0.9489176777043444 and parameters: {'weight_class_0': 0.2652154609295724, 'weight_class_1': 5.950966463620037, 'weight_class_2': 5.5703968536584965}. Best is trial 59 with value: 0.949616534911403.

[I 2026-07-05 15:04:16,719] Trial 82 finished with value: 0.9494315354152946 and parameters: {'weight_class_0': 0.3298601043624271, 'weight_class_1': 5.832246868063349, 'weight_class_2': 5.586026965950936}. Best is trial 59 with value: 0.949616534911403.
[I 2026-07-05 15:04:16,728] Trial 83 finished with value: 0.949340121383945 and parameters: {'weight_class_0': 0.2996906679153375, 'weight_class_1': 5.941328031311677, 'weight_class_2': 5.556544099803782}. Best is trial 59 with value: 0.949616534911403.
[I 2026-07-05 15:04:16,755] Trial 84 finished with value: 0.949463753348274 and parameters: {'weight_class_0': 0.33642166360608117, 'weight_class_1': 6.014675906339487, 'weight_class_2': 5.59462787137256}. Best is trial 59 with value: 0.949616534911403.
[I 2026-07-05 15:04:16,763] Trial 85 finished with value: 0.9490516267140578 and parameters: {'weight_class_0': 0.30219269521573733, 'weight_class_1': 6.0753289300858775, 'weight_class_2': 6.1316460920241616}. Best is trial 59 with value: 0.949616534911403.
[I 2026-07-05 15:04:16,803] Trial 86 finished with value: 0.9497157122887693 and parameters: {'weight_class_0': 0.310205023238052, 'weight_class_1': 5.060216687759511, 'weight_class_2': 4.064850235028525}. Best is trial 86 with value: 0.9497157122887693.
[I 2026-07-05 15:04:16,806] Trial 87 finished with value: 0.9492403451800752 and parameters: {'weight_class_0': 0.3304104265984318, 'weight_class_1': 5.801305070656107, 'weight_class_2': 6.135660846286564}. Best is trial 86 with value: 0.9497157122887693.
[I 2026-07-05 15:04:16,845] Trial 89 finished with value: 0.9474656795638151 and parameters: {'weight_class_0': 0.8790716012711859, 'weight_class_1': 5.082575856270885, 'weight_class_2': 6.168098906520705}. Best is trial 86 with value: 0.9497157122887693.
[I 2026-07-05 15:04:16,848] Trial 88 finished with value: 0.9484797022826424 and parameters: {'weight_class_0': 0.29172401617645927, 'weight_class_1': 5.022248064149284, 'weight_class_2': 7.435248657874547}. Best is trial 86 with value: 0.9497157122887693.
[I 2026-07-05 15:04:16,864] Trial 90 finished with value: 0.9472973406891575 and parameters: {'weight_class_0': 0.8870844225960359, 'weight_class_1': 4.991334586045091, 'weight_class_2': 6.253884814235256}. Best is trial 86 with value: 0.9497157122887693.
[I 2026-07-05 15:04:16,876] Trial 91 finished with value: 0.9464838653848414 and parameters: {'weight_class_0': 0.967221332101364, 'weight_class_1': 4.969981582322521, 'weight_class_2': 6.110899326934403}. Best is trial 86 with value: 0.9497157122887693.
[I 2026-07-05 15:04:16,890] Trial 92 finished with value: 0.947072356084513 and parameters: {'weight_class_0': 0.9152278896748139, 'weight_class_1': 5.080261546429504, 'weight_class_2': 6.169397595899497}. Best is trial 86 with value: 0.9497157122887693.

[I 2026-07-05 15:04:16,913] Trial 93 finished with value: 0.9469091669798732 and parameters: {'weight_class_0': 0.8472020047323456, 'weight_class_1': 5.061746971426459, 'weight_class_2': 4.851918292763214}. Best is trial 86 with value: 0.9497157122887693.
[I 2026-07-05 15:04:16,935] Trial 94 finished with value: 0.9456138249999304 and parameters: {'weight_class_0': 0.8884797094446466, 'weight_class_1': 5.056754098353213, 'weight_class_2': 4.024273506813429}. Best is trial 86 with value: 0.9497157122887693.
[I 2026-07-05 15:04:16,958] Trial 95 finished with value: 0.9448047168698405 and parameters: {'weight_class_0': 0.9441300606910826, 'weight_class_1': 5.030904152124259, 'weight_class_2': 4.0778493636987285}. Best is trial 86 with value: 0.9497157122887693.
[I 2026-07-05 15:04:16,977] Trial 96 finished with value: 0.944524388929718 and parameters: {'weight_class_0': 0.9653728972419711, 'weight_class_1': 5.058984254091777, 'weight_class_2': 4.073301126605941}. Best is trial 86 with value: 0.9497157122887693.
[I 2026-07-05 15:04:16,988] Trial 97 finished with value: 0.942555370184401 and parameters: {'weight_class_0': 1.1902291773579998, 'weight_class_1': 6.589092611141984, 'weight_class_2': 4.026942860449564}. Best is trial 86 with value: 0.9497157122887693.
[I 2026-07-05 15:04:17,021] Trial 99 finished with value: 0.9426058405754875 and parameters: {'weight_class_0': 1.2400378054795018, 'weight_class_1': 5.6068457444149296, 'weight_class_2': 4.7840728857903185}. Best is trial 86 with value: 0.9497157122887693.
[I 2026-07-05 15:04:17,026] Trial 98 finished with value: 0.9468768119224608 and parameters: {'weight_class_0': 0.7237586084765946, 'weight_class_1': 5.629034027223599, 'weight_class_2': 3.424864889008752}. Best is trial 86 with value: 0.9497157122887693.
[I 2026-07-05 15:04:17,052] Trial 100 finished with value: 0.943664379428763 and parameters: {'weight_class_0': 1.1822408527423813, 'weight_class_1': 5.695503976154088, 'weight_class_2': 4.803096021669057}. Best is trial 86 with value: 0.9497157122887693.
[I 2026-07-05 15:04:17,073] Trial 101 finished with value: 0.9414763944465486 and parameters: {'weight_class_0': 1.2042228630314706, 'weight_class_1': 5.640835048482148, 'weight_class_2': 4.026460005538214}. Best is trial 86 with value: 0.9497157122887693.
[I 2026-07-05 15:04:17,075] Trial 102 finished with value: 0.9376259629897729 and parameters: {'weight_class_0': 1.2556417301568885, 'weight_class_1': 5.629237037042512, 'weight_class_2': 3.3906489476465533}. Best is trial 86 with value: 0.9497157122887693.
[I 2026-07-05 15:04:17,107] Trial 103 finished with value: 0.9456782336294444 and parameters: {'weight_class_0': 1.178194372707751, 'weight_class_1': 5.656929482598097, 'weight_class_2': 6.499189613886849}. Best is trial 86 with value: 0.9497157122887693.

Best trial: 109. Best value: 0.94976:  12%|███████████████▎                                                                                                                     | 115/1000 [00:02<00:16, 55.15it/s]

[I 2026-07-05 15:04:17,119] Trial 104 finished with value: 0.9389428269271884 and parameters: {'weight_class_0': 1.186588585639401, 'weight_class_1': 5.661740400485805, 'weight_class_2': 3.3328281478131534}. Best is trial 86 with value: 0.9497157122887693.
[I 2026-07-05 15:04:17,135] Trial 105 finished with value: 0.9462795185756278 and parameters: {'weight_class_0': 0.6818118309865662, 'weight_class_1': 5.637429670868028, 'weight_class_2': 2.9640763129987917}. Best is trial 86 with value: 0.9497157122887693.
[I 2026-07-05 15:04:17,161] Trial 106 finished with value: 0.9474224628129161 and parameters: {'weight_class_0': 0.6314763740127891, 'weight_class_1': 5.631779063861027, 'weight_class_2': 3.1067355013175324}. Best is trial 86 with value: 0.9497157122887693.
[I 2026-07-05 15:04:17,181] Trial 107 finished with value: 0.9238924928366687 and parameters: {'weight_class_0': 0.056176810926465315, 'weight_class_1': 6.208873944314355, 'weight_class_2': 6.5562434561266265}. Best is trial 86 with value: 0.9497157122887693.
[I 2026-07-05 15:04:17,198] Trial 108 finished with value: 0.7893163593578741 and parameters: {'weight_class_0': 0.019486557405145155, 'weight_class_1': 7.27042388185998, 'weight_class_2': 5.7281438645776355}. Best is trial 86 with value: 0.9497157122887693.
[I 2026-07-05 15:04:17,228] Trial 110 finished with value: 0.6581274008196315 and parameters: {'weight_class_0': 0.002221236554770134, 'weight_class_1': 6.275564041921855, 'weight_class_2': 5.681538263695523}. Best is trial 86 with value: 0.9497157122887693.
[I 2026-07-05 15:04:17,230] Trial 109 finished with value: 0.9497603768708324 and parameters: {'weight_class_0': 0.582287048627997, 'weight_class_1': 7.195930799017077, 'weight_class_2': 6.511632580573239}. Best is trial 109 with value: 0.9497603768708324.
[I 2026-07-05 15:04:17,257] Trial 111 finished with value: 0.9497053992987979 and parameters: {'weight_class_0': 0.5863494036689434, 'weight_class_1': 7.209641953188083, 'weight_class_2': 5.672529358311195}. Best is trial 109 with value: 0.9497603768708324.
[I 2026-07-05 15:04:17,280] Trial 112 finished with value: 0.7578967107440278 and parameters: {'weight_class_0': 0.011591331711138742, 'weight_class_1': 7.226405015720992, 'weight_class_2': 2.0929558335429146}. Best is trial 109 with value: 0.9497603768708324.
[I 2026-07-05 15:04:17,289] Trial 113 finished with value: 0.9459896880302548 and parameters: {'weight_class_0': 0.14110098043765684, 'weight_class_1': 6.206707788603798, 'weight_class_2': 6.5238006633465275}. Best is trial 109 with value: 0.9497603768708324.
[I 2026-07-05 15:04:17,300] Trial 114 finished with value: 0.8780434364082818 and parameters: {'weight_class_0': 5.643106901810542, 'weight_class_1': 4.219210177290402, 'weight_class_2': 6.504983040913657}. Best is trial 109 with value: 0.9497603768708324.
[I 2026-07-05 15:04:17,321] Trial 115 finished with value: 0.7737195946449241 and parameters: {'weight_class_0': 0.016081362996720805, 'weight_class_1': 6.201963496219, 'weight_class_2': 5.67634988929289}. Best is trial 109 with value: 0.9497603768708324.

Best trial: 124. Best value: 0.949842:  13%|████████████████▊                                                                                                                   | 127/1000 [00:02<00:16, 54.11it/s]

[I 2026-07-05 15:04:17,338] Trial 116 finished with value: 0.9494189618943811 and parameters: {'weight_class_0': 0.4169612300803472, 'weight_class_1': 6.203379581266988, 'weight_class_2': 6.839541491352992}. Best is trial 109 with value: 0.9497603768708324.
[I 2026-07-05 15:04:17,374] Trial 117 finished with value: 0.9493681790557238 and parameters: {'weight_class_0': 0.5644737352588125, 'weight_class_1': 5.271142248336685, 'weight_class_2': 6.971387827172091}. Best is trial 109 with value: 0.9497603768708324.
[I 2026-07-05 15:04:17,400] Trial 119 finished with value: 0.9456514216585075 and parameters: {'weight_class_0': 0.47329773285555327, 'weight_class_1': 4.177347111158995, 'weight_class_2': 1.8733703662564016}. Best is trial 109 with value: 0.9497603768708324.
[I 2026-07-05 15:04:17,410] Trial 118 finished with value: 0.9467585942891259 and parameters: {'weight_class_0': 0.47540431089984186, 'weight_class_1': 7.9505082399395235, 'weight_class_2': 2.0945169102159165}. Best is trial 109 with value: 0.9497603768708324.
[I 2026-07-05 15:04:17,425] Trial 120 finished with value: 0.949608537939604 and parameters: {'weight_class_0': 0.5048203426176502, 'weight_class_1': 6.554384402487884, 'weight_class_2': 6.733370038425928}. Best is trial 109 with value: 0.9497603768708324.
[I 2026-07-05 15:04:17,431] Trial 121 finished with value: 0.9495651148397379 and parameters: {'weight_class_0': 0.5410330730225992, 'weight_class_1': 6.5326313821656585, 'weight_class_2': 6.978487849667068}. Best is trial 109 with value: 0.9497603768708324.
[I 2026-07-05 15:04:17,444] Trial 122 finished with value: 0.9495801520421686 and parameters: {'weight_class_0': 0.5188208498177692, 'weight_class_1': 6.61725386138237, 'weight_class_2': 6.76968358211889}. Best is trial 109 with value: 0.9497603768708324.
[I 2026-07-05 15:04:17,477] Trial 123 finished with value: 0.9497527417585999 and parameters: {'weight_class_0': 0.579536114271175, 'weight_class_1': 7.939142975703751, 'weight_class_2': 5.907676347036844}. Best is trial 109 with value: 0.9497603768708324.
[I 2026-07-05 15:04:17,502] Trial 124 finished with value: 0.9498417729049734 and parameters: {'weight_class_0': 0.48905967612629975, 'weight_class_1': 7.872126275715952, 'weight_class_2': 5.395849649914689}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:17,518] Trial 125 finished with value: 0.9497750322184909 and parameters: {'weight_class_0': 0.5333515887382327, 'weight_class_1': 8.430394052997, 'weight_class_2': 5.345928564173784}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:17,523] Trial 126 finished with value: 0.9421025956277947 and parameters: {'weight_class_0': 0.5094866903802653, 'weight_class_1': 1.4629411761882056, 'weight_class_2': 5.357367565169252}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:17,553] Trial 127 finished with value: 0.949806917176422 and parameters: {'weight_class_0': 0.48694651779966935, 'weight_class_1': 8.113264167598961, 'weight_class_2': 5.946690070274038}. Best is trial 124 with value: 0.9498417729049734.

Best trial: 124. Best value: 0.949842:  14%|██████████████████▎                                                                                                                 | 139/1000 [00:02<00:16, 53.48it/s]

[I 2026-07-05 15:04:17,574] Trial 128 finished with value: 0.9489988916878156 and parameters: {'weight_class_0': 0.71135439085839, 'weight_class_1': 6.636612863355062, 'weight_class_2': 5.380014310831743}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:17,588] Trial 129 finished with value: 0.9495897438414319 and parameters: {'weight_class_0': 0.692716503531899, 'weight_class_1': 6.6481819710862835, 'weight_class_2': 7.357308572628423}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:17,608] Trial 130 finished with value: 0.9495587799169408 and parameters: {'weight_class_0': 0.6219560545492078, 'weight_class_1': 6.658936584791073, 'weight_class_2': 7.2944618063884965}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:17,626] Trial 131 finished with value: 0.9496490659352013 and parameters: {'weight_class_0': 0.7188664333819603, 'weight_class_1': 8.03097048078133, 'weight_class_2': 7.386889924297113}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:17,639] Trial 132 finished with value: 0.9496993820699938 and parameters: {'weight_class_0': 0.6053090330819866, 'weight_class_1': 8.01867913447019, 'weight_class_2': 7.132627155618627}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:17,667] Trial 133 finished with value: 0.9495603838600569 and parameters: {'weight_class_0': 0.7786742714291998, 'weight_class_1': 8.175791677417129, 'weight_class_2': 7.428764269706322}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:17,678] Trial 134 finished with value: 0.9497719395411961 and parameters: {'weight_class_0': 0.6805443492231719, 'weight_class_1': 8.225534590659693, 'weight_class_2': 7.123477820733544}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:17,697] Trial 135 finished with value: 0.946183175742961 and parameters: {'weight_class_0': 1.4627883496729153, 'weight_class_1': 8.198412925363996, 'weight_class_2': 7.383908018552108}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:17,729] Trial 137 finished with value: 0.9496499820855367 and parameters: {'weight_class_0': 0.7701228127989432, 'weight_class_1': 8.15723832745985, 'weight_class_2': 8.513641190874914}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:17,739] Trial 136 finished with value: 0.9497057093906299 and parameters: {'weight_class_0': 0.709910613287598, 'weight_class_1': 8.144381157163396, 'weight_class_2': 7.45323822049383}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:17,758] Trial 138 finished with value: 0.9446866664838693 and parameters: {'weight_class_0': 1.4689736770662094, 'weight_class_1': 8.376931684462589, 'weight_class_2': 5.9813573859590985}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:17,772] Trial 139 finished with value: 0.9465933012441763 and parameters: {'weight_class_0': 1.4455395410695149, 'weight_class_1': 8.10038188487334, 'weight_class_2': 8.19672782889284}. Best is trial 124 with value: 0.9498417729049734.

[I 2026-07-05 15:04:17,789] Trial 140 finished with value: 0.9465089974535373 and parameters: {'weight_class_0': 1.4746662772574564, 'weight_class_1': 8.122710988940776, 'weight_class_2': 8.199421313372845}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:17,797] Trial 141 finished with value: 0.946179797843965 and parameters: {'weight_class_0': 1.492299532422116, 'weight_class_1': 8.285205671118975, 'weight_class_2': 7.58338205870157}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:17,844] Trial 142 finished with value: 0.9459525359051875 and parameters: {'weight_class_0': 1.4800333155205132, 'weight_class_1': 8.500115382883685, 'weight_class_2': 7.049320263939334}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:17,851] Trial 143 finished with value: 0.9468042942307578 and parameters: {'weight_class_0': 1.4598765459274534, 'weight_class_1': 8.451230184086237, 'weight_class_2': 8.320473418600823}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:17,859] Trial 144 finished with value: 0.9485258369680291 and parameters: {'weight_class_0': 1.024189605002862, 'weight_class_1': 8.427989860241514, 'weight_class_2': 7.102775564596325}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:17,875] Trial 145 finished with value: 0.9490863824760977 and parameters: {'weight_class_0': 1.0321423034186663, 'weight_class_1': 8.64327379301906, 'weight_class_2': 8.379808581756429}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:17,905] Trial 146 finished with value: 0.9464147393950633 and parameters: {'weight_class_0': 0.20970235769176143, 'weight_class_1': 8.554432915096026, 'weight_class_2': 9.07536006264137}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:17,928] Trial 147 finished with value: 0.9493247441462818 and parameters: {'weight_class_0': 0.9765504176443203, 'weight_class_1': 8.546238997054854, 'weight_class_2': 8.716526456168978}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:17,956] Trial 148 finished with value: 0.949115943078691 and parameters: {'weight_class_0': 1.0332762119164298, 'weight_class_1': 8.699419560753991, 'weight_class_2': 8.389528082677174}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:17,962] Trial 149 finished with value: 0.9493239056699577 and parameters: {'weight_class_0': 1.013524029619476, 'weight_class_1': 8.75439491695345, 'weight_class_2': 8.904390695543452}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:17,967] Trial 150 finished with value: 0.9493475737592426 and parameters: {'weight_class_0': 1.0456667727819222, 'weight_class_1': 9.255747916274172, 'weight_class_2': 9.034572134519365}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:17,981] Trial 151 finished with value: 0.947075919241216 and parameters: {'weight_class_0': 0.22458731253578235, 'weight_class_1': 9.308982844852752, 'weight_class_2': 7.115685826540368}. Best is trial 124 with value: 0.9498417729049734.

Best trial: 124. Best value: 0.949842:  16%|█████████████████████▌                                                                                                              | 163/1000 [00:03<00:15, 52.79it/s]

[I 2026-07-05 15:04:18,031] Trial 153 finished with value: 0.9469553382967536 and parameters: {'weight_class_0': 0.21132218198916597, 'weight_class_1': 9.25010890184483, 'weight_class_2': 6.369429742309951}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,033] Trial 152 finished with value: 0.9471307926731013 and parameters: {'weight_class_0': 0.19087639929449118, 'weight_class_1': 7.587282617643009, 'weight_class_2': 6.411216050986324}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,053] Trial 154 finished with value: 0.9495112675963765 and parameters: {'weight_class_0': 0.8430397652635385, 'weight_class_1': 7.638590350926885, 'weight_class_2': 8.760885367971259}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,055] Trial 155 finished with value: 0.9491063016135038 and parameters: {'weight_class_0': 0.8085283817126682, 'weight_class_1': 7.749186039887659, 'weight_class_2': 6.300189474049094}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,085] Trial 156 finished with value: 0.9495212293226117 and parameters: {'weight_class_0': 0.772534181144134, 'weight_class_1': 7.739674278255544, 'weight_class_2': 7.864557994550423}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,107] Trial 157 finished with value: 0.9493067565478364 and parameters: {'weight_class_0': 0.7888029518958253, 'weight_class_1': 9.471179441844972, 'weight_class_2': 6.326398637814634}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,127] Trial 158 finished with value: 0.9473688460197424 and parameters: {'weight_class_0': 0.2164426393135261, 'weight_class_1': 7.727601120278114, 'weight_class_2': 7.621512696971726}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,148] Trial 159 finished with value: 0.9494284730124664 and parameters: {'weight_class_0': 0.7676571515759609, 'weight_class_1': 7.71727177584262, 'weight_class_2': 6.672844675325206}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,173] Trial 161 finished with value: 0.9492456567178519 and parameters: {'weight_class_0': 0.7946814954920901, 'weight_class_1': 7.753716305404361, 'weight_class_2': 6.414665563447112}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,189] Trial 160 finished with value: 0.9495677667112651 and parameters: {'weight_class_0': 0.7707390226662264, 'weight_class_1': 7.76326719957898, 'weight_class_2': 7.6163821062272765}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,199] Trial 162 finished with value: 0.9495947365472044 and parameters: {'weight_class_0': 0.7612633385956378, 'weight_class_1': 7.804514152077101, 'weight_class_2': 7.882622985195154}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,213] Trial 163 finished with value: 0.9496767654428361 and parameters: {'weight_class_0': 0.6734176687481449, 'weight_class_1': 8.030992896530869, 'weight_class_2': 7.827845732349547}. Best is trial 124 with value: 0.9498417729049734.

Best trial: 124. Best value: 0.949842:  17%|██████████████████████▉                                                                                                             | 174/1000 [00:03<00:15, 54.68it/s]

[I 2026-07-05 15:04:18,235] Trial 164 finished with value: 0.9494351987492989 and parameters: {'weight_class_0': 0.7066332848509891, 'weight_class_1': 7.877777354476639, 'weight_class_2': 9.470532897533625}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,247] Trial 165 finished with value: 0.9495722132428789 and parameters: {'weight_class_0': 0.4224828158133659, 'weight_class_1': 7.09539134973714, 'weight_class_2': 6.742471454871536}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,264] Trial 166 finished with value: 0.9497818583146719 and parameters: {'weight_class_0': 0.6280740633871189, 'weight_class_1': 8.040038841927062, 'weight_class_2': 6.713425620808733}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,277] Trial 167 finished with value: 0.9495812946630799 and parameters: {'weight_class_0': 0.4411079464552161, 'weight_class_1': 7.911560947664667, 'weight_class_2': 6.789550748842183}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,311] Trial 168 finished with value: 0.9488186920304242 and parameters: {'weight_class_0': 0.41437358501957633, 'weight_class_1': 7.914769976841303, 'weight_class_2': 9.491881607678977}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,320] Trial 169 finished with value: 0.9488322129017752 and parameters: {'weight_class_0': 0.44992497960670025, 'weight_class_1': 7.95069785060818, 'weight_class_2': 9.66156340342041}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,354] Trial 170 finished with value: 0.9494892599987163 and parameters: {'weight_class_0': 0.5024716954706756, 'weight_class_1': 7.432128242798866, 'weight_class_2': 7.991033644242389}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,368] Trial 171 finished with value: 0.949706691760134 and parameters: {'weight_class_0': 0.444551792048519, 'weight_class_1': 7.951539772986504, 'weight_class_2': 5.920692978636952}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,397] Trial 172 finished with value: 0.9494918876632362 and parameters: {'weight_class_0': 0.47113358894567425, 'weight_class_1': 7.953047337314122, 'weight_class_2': 7.7953552357483575}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,402] Trial 173 finished with value: 0.9368309446428462 and parameters: {'weight_class_0': 0.4309681279180401, 'weight_class_1': 7.986279693694946, 'weight_class_2': 0.9688699600354305}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,418] Trial 174 finished with value: 0.9497155142553516 and parameters: {'weight_class_0': 0.44705160942077343, 'weight_class_1': 8.0040158481126, 'weight_class_2': 5.973150922804832}. Best is trial 124 with value: 0.9498417729049734.

[I 2026-07-05 15:04:18,455] Trial 175 finished with value: 0.949747752237128 and parameters: {'weight_class_0': 0.45413669236726234, 'weight_class_1': 7.43209994795874, 'weight_class_2': 5.895884583417072}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,458] Trial 176 finished with value: 0.9497699840182401 and parameters: {'weight_class_0': 0.5033586961314398, 'weight_class_1': 7.4175057578810595, 'weight_class_2': 5.875812916110118}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,473] Trial 177 finished with value: 0.9497828830355831 and parameters: {'weight_class_0': 0.5822638007912025, 'weight_class_1': 8.045426754798717, 'weight_class_2': 5.994100505913301}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,496] Trial 178 finished with value: 0.9497098995387171 and parameters: {'weight_class_0': 0.6148873186531381, 'weight_class_1': 7.5168516636848475, 'weight_class_2': 5.949095124547578}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,520] Trial 179 finished with value: 0.9497762472886074 and parameters: {'weight_class_0': 0.5860248956682655, 'weight_class_1': 8.090445821093606, 'weight_class_2': 6.017656746996582}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,530] Trial 180 finished with value: 0.9497763828677638 and parameters: {'weight_class_0': 0.5890326833027612, 'weight_class_1': 8.254426916043073, 'weight_class_2': 5.9222631602536016}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,565] Trial 181 finished with value: 0.9497635383246462 and parameters: {'weight_class_0': 0.599193853564715, 'weight_class_1': 8.282581102775799, 'weight_class_2': 6.125280580646925}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,574] Trial 182 finished with value: 0.9475724614571209 and parameters: {'weight_class_0': 0.21374848667158325, 'weight_class_1': 8.235525497031235, 'weight_class_2': 6.0025614990608}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,593] Trial 183 finished with value: 0.9469323682138183 and parameters: {'weight_class_0': 0.18929553356873924, 'weight_class_1': 8.20497383372296, 'weight_class_2': 5.929071194479768}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,614] Trial 184 finished with value: 0.9465502201327403 and parameters: {'weight_class_0': 0.18004288256035816, 'weight_class_1': 8.317281968831212, 'weight_class_2': 6.032454753101081}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,636] Trial 185 finished with value: 0.9473498053583101 and parameters: {'weight_class_0': 0.19226797959897002, 'weight_class_1': 7.373361726848769, 'weight_class_2': 5.987835586457519}. Best is trial 124 with value: 0.9498417729049734.

Best trial: 124. Best value: 0.949842:  20%|█████████████████████████▊                                                                                                          | 196/1000 [00:03<00:14, 53.87it/s]

[I 2026-07-05 15:04:18,643] Trial 186 finished with value: 0.9479563803430898 and parameters: {'weight_class_0': 0.21839477179994343, 'weight_class_1': 7.456967869593349, 'weight_class_2': 5.959908755488309}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,673] Trial 187 finished with value: 0.9470814663198085 and parameters: {'weight_class_0': 0.18200176896306858, 'weight_class_1': 7.389972214989625, 'weight_class_2': 6.004527208855098}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,687] Trial 188 finished with value: 0.9454189190747123 and parameters: {'weight_class_0': 0.13954562949242066, 'weight_class_1': 7.364864725698497, 'weight_class_2': 5.883859183652663}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,704] Trial 189 finished with value: 0.9475891159464797 and parameters: {'weight_class_0': 0.2021099297917744, 'weight_class_1': 7.464109842522735, 'weight_class_2': 5.885680071796417}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,706] Trial 190 finished with value: 0.9482688910171295 and parameters: {'weight_class_0': 0.23744226399498397, 'weight_class_1': 7.324354676882497, 'weight_class_2': 6.057912966746729}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,739] Trial 192 finished with value: 0.8692552153895318 and parameters: {'weight_class_0': 8.289885665429374, 'weight_class_1': 7.206979649069185, 'weight_class_2': 6.094612007194149}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,770] Trial 193 finished with value: 0.949470718220478 and parameters: {'weight_class_0': 0.3564033422113374, 'weight_class_1': 7.428162081292197, 'weight_class_2': 5.9011899855176235}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,777] Trial 191 finished with value: 0.948812395264651 and parameters: {'weight_class_0': 0.2941018362029025, 'weight_class_1': 7.321351248527546, 'weight_class_2': 6.090774942441196}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,810] Trial 194 finished with value: 0.9468078026868357 and parameters: {'weight_class_0': 1.1349964388424838, 'weight_class_1': 7.201842143194233, 'weight_class_2': 5.766725405573799}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,825] Trial 195 finished with value: 0.9458812180450967 and parameters: {'weight_class_0': 1.2301656279953113, 'weight_class_1': 7.141396152197061, 'weight_class_2': 5.7967918711369535}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,842] Trial 196 finished with value: 0.949668816943961 and parameters: {'weight_class_0': 0.6078954116644747, 'weight_class_1': 8.92739665977484, 'weight_class_2': 5.753299879328814}. Best is trial 124 with value: 0.9498417729049734.

[I 2026-07-05 15:04:18,868] Trial 198 finished with value: 0.9495350015139237 and parameters: {'weight_class_0': 0.6251149779633698, 'weight_class_1': 8.39649546395024, 'weight_class_2': 5.387167499597558}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,897] Trial 197 finished with value: 0.9496262636156039 and parameters: {'weight_class_0': 0.5851942031245769, 'weight_class_1': 8.792057252306577, 'weight_class_2': 5.441884982207447}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,913] Trial 199 finished with value: 0.9495988761375097 and parameters: {'weight_class_0': 0.60232259736718, 'weight_class_1': 8.837647233808402, 'weight_class_2': 5.398619717090968}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,925] Trial 200 finished with value: 0.9497231424898517 and parameters: {'weight_class_0': 0.5825402946485508, 'weight_class_1': 8.850023189500702, 'weight_class_2': 5.686560352632991}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,927] Trial 201 finished with value: 0.9496726747337799 and parameters: {'weight_class_0': 0.5973145340572553, 'weight_class_1': 8.794458830994904, 'weight_class_2': 5.6997924058103475}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:18,938] Trial 202 finished with value: 0.9496372487007956 and parameters: {'weight_class_0': 0.5899559284376966, 'weight_class_1': 8.928062670535018, 'weight_class_2': 5.377791719616063}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:19,005] Trial 205 finished with value: 0.9495866758460929 and parameters: {'weight_class_0': 0.6147638411266912, 'weight_class_1': 8.448708704752484, 'weight_class_2': 5.478535451357956}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:19,007] Trial 204 finished with value: 0.9498100606581173 and parameters: {'weight_class_0': 0.6063362947039895, 'weight_class_1': 8.757144870198672, 'weight_class_2': 6.26998632090252}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:19,016] Trial 203 finished with value: 0.9497465314692475 and parameters: {'weight_class_0': 0.6313219988161125, 'weight_class_1': 8.40905832095029, 'weight_class_2': 6.307618774266437}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:19,027] Trial 206 finished with value: 0.9494870781741387 and parameters: {'weight_class_0': 0.6444752424579672, 'weight_class_1': 8.164762218885453, 'weight_class_2': 5.395396249109028}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:19,046] Trial 207 finished with value: 0.9478800619019173 and parameters: {'weight_class_0': 0.9857153386364601, 'weight_class_1': 8.277122766550848, 'weight_class_2': 5.518781073391293}. Best is trial 124 with value: 0.9498417729049734.

[I 2026-07-05 15:04:19,061] Trial 208 finished with value: 0.9481702585258388 and parameters: {'weight_class_0': 1.0048242906726244, 'weight_class_1': 8.367544630707945, 'weight_class_2': 6.224412114132873}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:19,086] Trial 210 finished with value: 0.9486060438586099 and parameters: {'weight_class_0': 0.9433119717648204, 'weight_class_1': 8.2860262534121, 'weight_class_2': 6.303898834250674}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:19,095] Trial 209 finished with value: 0.9386549031492105 and parameters: {'weight_class_0': 0.9171513686206039, 'weight_class_1': 2.2181839643306263, 'weight_class_2': 6.241074377951427}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:19,131] Trial 211 finished with value: 0.9485601274808458 and parameters: {'weight_class_0': 0.9483762432901622, 'weight_class_1': 8.331632490787761, 'weight_class_2': 6.269859258590143}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:19,135] Trial 212 finished with value: 0.9486311901552623 and parameters: {'weight_class_0': 0.9239673500871652, 'weight_class_1': 8.244962705974137, 'weight_class_2': 6.184630974053705}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:19,149] Trial 213 finished with value: 0.9486272177525406 and parameters: {'weight_class_0': 0.9365960116309859, 'weight_class_1': 8.316876001416885, 'weight_class_2': 6.24699294243434}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:19,179] Trial 214 finished with value: 0.9486303681245344 and parameters: {'weight_class_0': 0.9243890040044802, 'weight_class_1': 8.29415512651674, 'weight_class_2': 6.151693621038306}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:19,212] Trial 215 finished with value: 0.9494591491660853 and parameters: {'weight_class_0': 0.3917014057335775, 'weight_class_1': 8.679238843544583, 'weight_class_2': 6.275876857344441}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:19,216] Trial 216 finished with value: 0.9488275517184004 and parameters: {'weight_class_0': 0.8888598763003764, 'weight_class_1': 8.632930283110701, 'weight_class_2': 6.261265293485021}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:19,240] Trial 217 finished with value: 0.9484386190653226 and parameters: {'weight_class_0': 0.9262622343113462, 'weight_class_1': 7.588637801717072, 'weight_class_2': 6.252683494309732}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:19,247] Trial 218 finished with value: 0.9495197201053078 and parameters: {'weight_class_0': 0.4112241951017157, 'weight_class_1': 8.599478991173989, 'weight_class_2': 6.549615546585054}. Best is trial 124 with value: 0.9498417729049734.

Best trial: 124. Best value: 0.949842:  23%|██████████████████████████████▏                                                                                                     | 229/1000 [00:04<00:14, 52.33it/s]

[I 2026-07-05 15:04:19,275] Trial 219 finished with value: 0.9496809792274942 and parameters: {'weight_class_0': 0.4399806758680952, 'weight_class_1': 8.592751473993328, 'weight_class_2': 6.176545413673536}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:19,309] Trial 220 finished with value: 0.9493219809745471 and parameters: {'weight_class_0': 0.3812814797467533, 'weight_class_1': 8.58265424378957, 'weight_class_2': 6.612424192911481}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:19,335] Trial 222 finished with value: 0.9495056959662141 and parameters: {'weight_class_0': 0.40683153389817606, 'weight_class_1': 8.627053982046466, 'weight_class_2': 6.447186189472492}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:19,344] Trial 221 finished with value: 0.9494205313015586 and parameters: {'weight_class_0': 0.37841883750196836, 'weight_class_1': 7.606230798420693, 'weight_class_2': 6.567181456325409}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:19,347] Trial 223 finished with value: 0.9494185401065826 and parameters: {'weight_class_0': 0.39862640505100044, 'weight_class_1': 8.57765099624653, 'weight_class_2': 6.599640564596192}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:19,377] Trial 224 finished with value: 0.9495242254416386 and parameters: {'weight_class_0': 0.4014386759496542, 'weight_class_1': 7.635393731651454, 'weight_class_2': 6.543819417919321}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:19,394] Trial 225 finished with value: 0.9492531650224824 and parameters: {'weight_class_0': 0.3379884682537136, 'weight_class_1': 8.06690089204783, 'weight_class_2': 5.636677206939667}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:19,410] Trial 226 finished with value: 0.9495724113096083 and parameters: {'weight_class_0': 0.4160247384467948, 'weight_class_1': 8.033206991286578, 'weight_class_2': 6.538011645916406}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:19,419] Trial 227 finished with value: 0.9494872052597412 and parameters: {'weight_class_0': 0.39931599637168647, 'weight_class_1': 7.983148997507674, 'weight_class_2': 6.535875783055973}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:19,464] Trial 228 finished with value: 0.9494967963727396 and parameters: {'weight_class_0': 0.3695945147507573, 'weight_class_1': 8.038239878866477, 'weight_class_2': 5.636248871057702}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:19,472] Trial 229 finished with value: 0.9495820156761884 and parameters: {'weight_class_0': 0.3527146579735891, 'weight_class_1': 7.581497122464167, 'weight_class_2': 4.977452894078879}. Best is trial 124 with value: 0.9498417729049734.

Best trial: 124. Best value: 0.949842:  24%|███████████████████████████████▌                                                                                                    | 239/1000 [00:04<00:14, 51.36it/s]

[I 2026-07-05 15:04:19,485] Trial 230 finished with value: 0.9493556095999284 and parameters: {'weight_class_0': 0.6914535153306431, 'weight_class_1': 8.076845394131183, 'weight_class_2': 5.64132055447765}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:19,512] Trial 232 finished with value: 0.9494599838693224 and parameters: {'weight_class_0': 0.690284118808021, 'weight_class_1': 8.029390948099172, 'weight_class_2': 5.702216965539421}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:19,518] Trial 231 finished with value: 0.9494239638055703 and parameters: {'weight_class_0': 0.687966188264672, 'weight_class_1': 8.04726055026285, 'weight_class_2': 5.651774297268408}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:19,548] Trial 233 finished with value: 0.9495474291962341 and parameters: {'weight_class_0': 0.6713874352807552, 'weight_class_1': 8.058490682806996, 'weight_class_2': 5.751712622951153}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:19,573] Trial 234 finished with value: 0.9492948234698293 and parameters: {'weight_class_0': 0.6956085217203938, 'weight_class_1': 7.85799601672902, 'weight_class_2': 5.60007069398374}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:19,575] Trial 235 finished with value: 0.9494263952049614 and parameters: {'weight_class_0': 0.6915901875383961, 'weight_class_1': 7.866277595349759, 'weight_class_2': 5.769818427839708}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:19,618] Trial 236 finished with value: 0.9494891979141502 and parameters: {'weight_class_0': 0.6867556707013265, 'weight_class_1': 7.892238889426978, 'weight_class_2': 5.77494822610824}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:19,651] Trial 237 finished with value: 0.9116105895669394 and parameters: {'weight_class_0': 0.7020602967605926, 'weight_class_1': 0.5530926298369669, 'weight_class_2': 5.761598099885872}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:19,656] Trial 238 finished with value: 0.9494909460539841 and parameters: {'weight_class_0': 0.6839752353994899, 'weight_class_1': 7.7418219321928525, 'weight_class_2': 5.914004703897424}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:19,675] Trial 239 finished with value: 0.9494399427480434 and parameters: {'weight_class_0': 0.6964056487000285, 'weight_class_1': 7.8350638662063705, 'weight_class_2': 5.840690947719558}. Best is trial 124 with value: 0.9498417729049734.

[I 2026-07-05 15:04:19,707] Trial 240 finished with value: 0.9496247663463802 and parameters: {'weight_class_0': 0.6487154241949542, 'weight_class_1': 9.05851718068139, 'weight_class_2': 5.848857747003597}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:19,714] Trial 241 finished with value: 0.9497119778240322 and parameters: {'weight_class_0': 0.5974680943008267, 'weight_class_1': 9.14238283864211, 'weight_class_2': 5.854908375063622}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:19,736] Trial 242 finished with value: 0.9497831957152155 and parameters: {'weight_class_0': 0.5789749433493457, 'weight_class_1': 9.123446357709014, 'weight_class_2': 5.924382590971317}. Best is trial 124 with value: 0.9498417729049734.
[I 2026-07-05 15:04:19,752] Trial 243 finished with value: 0.9498680470834587 and parameters: {'weight_class_0': 0.5551523927937929, 'weight_class_1': 9.170666297890232, 'weight_class_2': 5.938827354020749}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:19,787] Trial 244 finished with value: 0.9498623600078496 and parameters: {'weight_class_0': 0.5460467760100486, 'weight_class_1': 8.99612524466622, 'weight_class_2': 5.992501791396378}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:19,789] Trial 245 finished with value: 0.9070027187123318 and parameters: {'weight_class_0': 0.055503165596840875, 'weight_class_1': 9.145193997573417, 'weight_class_2': 5.918207276038799}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:19,832] Trial 247 finished with value: 0.9498511554167174 and parameters: {'weight_class_0': 0.5590308000160757, 'weight_class_1': 8.432479383994934, 'weight_class_2': 6.0253573963562825}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:19,848] Trial 246 finished with value: 0.9497820652788934 and parameters: {'weight_class_0': 0.578702427399484, 'weight_class_1': 9.001168747692306, 'weight_class_2': 6.892511090511777}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:19,870] Trial 248 finished with value: 0.8852740052344331 and parameters: {'weight_class_0': 0.04417143970125714, 'weight_class_1': 8.484175074840504, 'weight_class_2': 6.881826770281385}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:19,895] Trial 249 finished with value: 0.8483577412047566 and parameters: {'weight_class_0': 0.03554332162227258, 'weight_class_1': 9.97212933544013, 'weight_class_2': 5.970053902060558}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:19,905] Trial 250 finished with value: 0.9496920846720922 and parameters: {'weight_class_0': 0.48193107042522554, 'weight_class_1': 9.48203365196394, 'weight_class_2': 6.029621463419157}. Best is trial 243 with value: 0.9498680470834587.

Best trial: 243. Best value: 0.949868:  26%|██████████████████████████████████▎                                                                                                 | 260/1000 [00:05<00:14, 51.44it/s]

[I 2026-07-05 15:04:19,910] Trial 251 finished with value: 0.9498341929044919 and parameters: {'weight_class_0': 0.569758590326808, 'weight_class_1': 9.225939933855203, 'weight_class_2': 6.049564007005458}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:19,939] Trial 252 finished with value: 0.9309721771146351 and parameters: {'weight_class_0': 0.08669881403798652, 'weight_class_1': 9.629843144823983, 'weight_class_2': 6.024757387684761}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:19,954] Trial 253 finished with value: 0.9497718329749527 and parameters: {'weight_class_0': 0.5024365217261569, 'weight_class_1': 9.306078624050201, 'weight_class_2': 6.070980391319919}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:19,967] Trial 254 finished with value: 0.949745831550787 and parameters: {'weight_class_0': 0.4908176661061696, 'weight_class_1': 9.007502834157112, 'weight_class_2': 5.985185454729636}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,012] Trial 255 finished with value: 0.9497645413597277 and parameters: {'weight_class_0': 0.5335723030823396, 'weight_class_1': 9.561446374462168, 'weight_class_2': 5.974426315223528}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,020] Trial 256 finished with value: 0.9497333319694278 and parameters: {'weight_class_0': 0.5122889154749011, 'weight_class_1': 9.670261211742107, 'weight_class_2': 6.046306533035431}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,028] Trial 257 finished with value: 0.9497208027916876 and parameters: {'weight_class_0': 0.5238381339133548, 'weight_class_1': 9.513193708877006, 'weight_class_2': 6.027307537071147}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,077] Trial 259 finished with value: 0.9497176116102367 and parameters: {'weight_class_0': 0.5209408199832954, 'weight_class_1': 9.453227278363537, 'weight_class_2': 6.035176439434392}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,087] Trial 258 finished with value: 0.9497511913360799 and parameters: {'weight_class_0': 0.5067054111396743, 'weight_class_1': 9.33407932386282, 'weight_class_2': 6.0506910662162205}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,101] Trial 260 finished with value: 0.9488698369492035 and parameters: {'weight_class_0': 0.8440877683171386, 'weight_class_1': 9.289082908786591, 'weight_class_2': 6.03362855176093}. Best is trial 243 with value: 0.9498680470834587.

Best trial: 243. Best value: 0.949868:  27%|███████████████████████████████████▊                                                                                                | 271/1000 [00:05<00:14, 49.94it/s]

[I 2026-07-05 15:04:20,130] Trial 262 finished with value: 0.9477906252772329 and parameters: {'weight_class_0': 1.134541815903496, 'weight_class_1': 9.697314792305008, 'weight_class_2': 6.118840888331655}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,136] Trial 261 finished with value: 0.9488646448195993 and parameters: {'weight_class_0': 0.8604967961258105, 'weight_class_1': 9.073167171677222, 'weight_class_2': 6.126139404133076}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,149] Trial 263 finished with value: 0.9490757483713844 and parameters: {'weight_class_0': 0.8392740638679252, 'weight_class_1': 9.688811970359563, 'weight_class_2': 6.322569315865488}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,202] Trial 265 finished with value: 0.9483110947670568 and parameters: {'weight_class_0': 0.8785216349132305, 'weight_class_1': 9.436967194587329, 'weight_class_2': 5.209949449174444}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,206] Trial 264 finished with value: 0.9485179305995399 and parameters: {'weight_class_0': 0.8215816629683791, 'weight_class_1': 9.542401357433011, 'weight_class_2': 5.200624332395281}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,239] Trial 267 finished with value: 0.9480192791525507 and parameters: {'weight_class_0': 1.1128878925056402, 'weight_class_1': 9.840171917945193, 'weight_class_2': 6.415659052565553}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,250] Trial 266 finished with value: 0.9488847613403314 and parameters: {'weight_class_0': 0.8928192109328784, 'weight_class_1': 9.784866246861897, 'weight_class_2': 6.382881649012087}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,257] Trial 268 finished with value: 0.9491825159497692 and parameters: {'weight_class_0': 0.8339492456893893, 'weight_class_1': 9.764576058781572, 'weight_class_2': 6.407770084718284}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,275] Trial 269 finished with value: 0.9490691872092024 and parameters: {'weight_class_0': 0.8522163594947307, 'weight_class_1': 9.069875532293587, 'weight_class_2': 6.38920579666277}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,308] Trial 271 finished with value: 0.9478827985337035 and parameters: {'weight_class_0': 0.25431400002090404, 'weight_class_1': 9.328240247767537, 'weight_class_2': 6.390425631729277}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,310] Trial 270 finished with value: 0.9478059159235782 and parameters: {'weight_class_0': 0.24838284531933974, 'weight_class_1': 9.264314778828519, 'weight_class_2': 6.360276700037899}. Best is trial 243 with value: 0.9498680470834587.

[I 2026-07-05 15:04:20,335] Trial 272 finished with value: 0.9477256173240566 and parameters: {'weight_class_0': 0.24504247977222948, 'weight_class_1': 9.344510747192606, 'weight_class_2': 6.398987854377557}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,349] Trial 273 finished with value: 0.9482966466693341 and parameters: {'weight_class_0': 0.2579079081774935, 'weight_class_1': 9.315083394487374, 'weight_class_2': 5.179169108604741}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,401] Trial 274 finished with value: 0.9467682917564577 and parameters: {'weight_class_0': 0.20081325513385195, 'weight_class_1': 9.00560320472781, 'weight_class_2': 6.3860878230315805}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,425] Trial 275 finished with value: 0.9480930024502343 and parameters: {'weight_class_0': 0.2594076791509427, 'weight_class_1': 9.015659916995624, 'weight_class_2': 6.383142540669794}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,429] Trial 276 finished with value: 0.9063559100607018 and parameters: {'weight_class_0': 4.89481096219175, 'weight_class_1': 9.033204780737602, 'weight_class_2': 6.6718679421820735}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,453] Trial 277 finished with value: 0.9478656377491553 and parameters: {'weight_class_0': 0.2543297289744976, 'weight_class_1': 9.259179881509313, 'weight_class_2': 6.684581012116606}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,472] Trial 279 finished with value: 0.9481394770429245 and parameters: {'weight_class_0': 0.2712756248842037, 'weight_class_1': 9.031693712774048, 'weight_class_2': 6.906229873874822}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,478] Trial 278 finished with value: 0.9352668699558824 and parameters: {'weight_class_0': 2.563918499603808, 'weight_class_1': 8.979994829975633, 'weight_class_2': 6.815466738323915}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,525] Trial 280 finished with value: 0.9062215126560913 and parameters: {'weight_class_0': 4.933613860783187, 'weight_class_1': 8.906824531170132, 'weight_class_2': 6.786006768278435}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,532] Trial 281 finished with value: 0.949806339426682 and parameters: {'weight_class_0': 0.5370547424542444, 'weight_class_1': 8.919252758872705, 'weight_class_2': 6.149606515854833}. Best is trial 243 with value: 0.9498680470834587.

[I 2026-07-05 15:04:20,553] Trial 282 finished with value: 0.9496911040554491 and parameters: {'weight_class_0': 0.5195551637329027, 'weight_class_1': 9.06577278355814, 'weight_class_2': 6.978307958682898}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,570] Trial 283 finished with value: 0.9496845813253693 and parameters: {'weight_class_0': 0.5177661717655073, 'weight_class_1': 8.961276708015195, 'weight_class_2': 6.782072344506267}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,579] Trial 284 finished with value: 0.9498026130655233 and parameters: {'weight_class_0': 0.5441258652168248, 'weight_class_1': 8.918459797467774, 'weight_class_2': 6.7272339862165}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,625] Trial 286 finished with value: 0.949802064467666 and parameters: {'weight_class_0': 0.5615172114201613, 'weight_class_1': 8.820165525123144, 'weight_class_2': 6.833533468814129}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,630] Trial 285 finished with value: 0.9496757025953514 and parameters: {'weight_class_0': 0.4850793449053883, 'weight_class_1': 8.84727441851901, 'weight_class_2': 6.157040004700109}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,655] Trial 287 finished with value: 0.9498140208275103 and parameters: {'weight_class_0': 0.5911058651577372, 'weight_class_1': 8.867287352512932, 'weight_class_2': 6.218248969345974}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,678] Trial 289 finished with value: 0.9497617683961858 and parameters: {'weight_class_0': 0.5257941314548465, 'weight_class_1': 8.829866883865545, 'weight_class_2': 6.1284400033341}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,687] Trial 288 finished with value: 0.9497479479959874 and parameters: {'weight_class_0': 0.5127457450324338, 'weight_class_1': 8.807778149510959, 'weight_class_2': 6.1692823423075}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,722] Trial 290 finished with value: 0.9498396451105884 and parameters: {'weight_class_0': 0.5520807684594279, 'weight_class_1': 8.705880997311205, 'weight_class_2': 6.147444905191794}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,756] Trial 291 finished with value: 0.9474720060510369 and parameters: {'weight_class_0': 1.179202725812516, 'weight_class_1': 8.719712303312098, 'weight_class_2': 6.177914864383294}. Best is trial 243 with value: 0.9498680470834587.

[I 2026-07-05 15:04:20,764] Trial 292 finished with value: 0.9474884157864497 and parameters: {'weight_class_0': 1.1807772147438995, 'weight_class_1': 8.77893975917265, 'weight_class_2': 6.202852927021278}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,787] Trial 293 finished with value: 0.9477060434254171 and parameters: {'weight_class_0': 1.2259848495527041, 'weight_class_1': 8.793326175080448, 'weight_class_2': 7.174880723569351}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,792] Trial 295 finished with value: 0.9478012979501568 and parameters: {'weight_class_0': 1.0797453761270306, 'weight_class_1': 8.657733901617313, 'weight_class_2': 6.165228595817913}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,815] Trial 294 finished with value: 0.9474899540707238 and parameters: {'weight_class_0': 1.1724011580975229, 'weight_class_1': 8.757243396121376, 'weight_class_2': 6.137768392163433}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,853] Trial 297 finished with value: 0.9479298092206352 and parameters: {'weight_class_0': 1.1773758698715646, 'weight_class_1': 8.778497656366625, 'weight_class_2': 7.204405325409025}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,854] Trial 296 finished with value: 0.9475077652569489 and parameters: {'weight_class_0': 1.0690210429518054, 'weight_class_1': 8.758194965948329, 'weight_class_2': 5.488480504549027}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,868] Trial 298 finished with value: 0.9479834802886904 and parameters: {'weight_class_0': 1.1622459200883721, 'weight_class_1': 8.716691827078684, 'weight_class_2': 7.250870312159032}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,875] Trial 299 finished with value: 0.9485875862489225 and parameters: {'weight_class_0': 1.0324875641198756, 'weight_class_1': 8.81323920450656, 'weight_class_2': 6.910100234375513}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,913] Trial 300 finished with value: 0.9480244452146375 and parameters: {'weight_class_0': 1.1384795692725553, 'weight_class_1': 8.710817166919751, 'weight_class_2': 7.0174933343168}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,943] Trial 301 finished with value: 0.9497396534484775 and parameters: {'weight_class_0': 0.7203705983972406, 'weight_class_1': 8.771766515642017, 'weight_class_2': 7.2085184962198925}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,955] Trial 302 finished with value: 0.9494724478404328 and parameters: {'weight_class_0': 0.8395444207811267, 'weight_class_1': 8.769128889866577, 'weight_class_2': 7.066480981065226}. Best is trial 243 with value: 0.9498680470834587.

Best trial: 243. Best value: 0.949868:  31%|█████████████████████████████████████████▏                                                                                          | 312/1000 [00:06<00:13, 50.12it/s]

[I 2026-07-05 15:04:20,961] Trial 303 finished with value: 0.9494892133394934 and parameters: {'weight_class_0': 0.7664719360905841, 'weight_class_1': 8.471447762429017, 'weight_class_2': 6.6181119549909395}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:20,982] Trial 304 finished with value: 0.870733135661006 and parameters: {'weight_class_0': 9.378308330879378, 'weight_class_1': 8.529719543194147, 'weight_class_2': 7.0079763893974585}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:21,011] Trial 305 finished with value: 0.9489716458360573 and parameters: {'weight_class_0': 0.7492135586903572, 'weight_class_1': 8.433168567301058, 'weight_class_2': 5.516773071046556}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:21,039] Trial 306 finished with value: 0.865333089676752 and parameters: {'weight_class_0': 9.608109240039225, 'weight_class_1': 8.430309119904337, 'weight_class_2': 5.528456748656097}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:21,043] Trial 307 finished with value: 0.9488972923196722 and parameters: {'weight_class_0': 0.7651825255400418, 'weight_class_1': 8.492719785838291, 'weight_class_2': 5.51129083044318}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:21,089] Trial 309 finished with value: 0.8865761998504222 and parameters: {'weight_class_0': 6.775845463881873, 'weight_class_1': 8.45416200621497, 'weight_class_2': 6.621215254736981}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:21,093] Trial 308 finished with value: 0.9491409494859756 and parameters: {'weight_class_0': 0.7590832416471232, 'weight_class_1': 8.499123207402048, 'weight_class_2': 5.823602487649569}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:21,102] Trial 310 finished with value: 0.8648444999123394 and parameters: {'weight_class_0': 9.919079176653995, 'weight_class_1': 8.486846861305395, 'weight_class_2': 5.804694743614262}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:21,131] Trial 311 finished with value: 0.9491128631173877 and parameters: {'weight_class_0': 0.769652030919062, 'weight_class_1': 9.176719221692963, 'weight_class_2': 5.844795275977322}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:21,180] Trial 314 finished with value: 0.9490843200987883 and parameters: {'weight_class_0': 0.7413066711153784, 'weight_class_1': 9.138872753358296, 'weight_class_2': 5.545001201233256}. Best is trial 243 with value: 0.9498680470834587.

Best trial: 243. Best value: 0.949868:  32%|██████████████████████████████████████████▋                                                                                         | 323/1000 [00:06<00:13, 48.99it/s]

[I 2026-07-05 15:04:21,184] Trial 313 finished with value: 0.9489626507943325 and parameters: {'weight_class_0': 0.7629446973590089, 'weight_class_1': 9.144257827080255, 'weight_class_2': 5.524741585780583}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:21,188] Trial 312 finished with value: 0.6576945198144298 and parameters: {'weight_class_0': 0.0007825688800811026, 'weight_class_1': 9.150492816985167, 'weight_class_2': 5.542231131585391}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:21,207] Trial 315 finished with value: 0.8790832505871083 and parameters: {'weight_class_0': 6.776919663420784, 'weight_class_1': 8.406844610262738, 'weight_class_2': 4.9255159730352}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:21,241] Trial 317 finished with value: 0.9490541058257707 and parameters: {'weight_class_0': 0.34227071219091787, 'weight_class_1': 9.262759978758494, 'weight_class_2': 5.793565160129766}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:21,243] Trial 316 finished with value: 0.6581493807480446 and parameters: {'weight_class_0': 0.002563785062817847, 'weight_class_1': 9.170011440989796, 'weight_class_2': 5.782592861127782}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:21,286] Trial 319 finished with value: 0.9494030285542391 and parameters: {'weight_class_0': 0.39356152020310553, 'weight_class_1': 9.200693466256846, 'weight_class_2': 5.833286498197704}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:21,289] Trial 318 finished with value: 0.7106140776422674 and parameters: {'weight_class_0': 0.012782955987946543, 'weight_class_1': 9.160044811578057, 'weight_class_2': 5.879051762338106}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:21,338] Trial 322 finished with value: 0.9491697595794805 and parameters: {'weight_class_0': 0.3646709421857618, 'weight_class_1': 9.163931481674313, 'weight_class_2': 6.092515238774431}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:21,344] Trial 320 finished with value: 0.9494326520555921 and parameters: {'weight_class_0': 0.3648351753204433, 'weight_class_1': 9.183847827417583, 'weight_class_2': 4.9491693036419875}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:21,345] Trial 321 finished with value: 0.9495413157918894 and parameters: {'weight_class_0': 0.3622191014099968, 'weight_class_1': 8.234400202870779, 'weight_class_2': 4.908217129115847}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:21,357] Trial 323 finished with value: 0.9493843221429064 and parameters: {'weight_class_0': 0.36902634306200977, 'weight_class_1': 8.246240947522772, 'weight_class_2': 6.135146873731027}. Best is trial 243 with value: 0.9498680470834587.

[I 2026-07-05 15:04:21,413] Trial 324 finished with value: 0.9497752331973041 and parameters: {'weight_class_0': 0.5047449734807075, 'weight_class_1': 8.235018104337172, 'weight_class_2': 6.1692882473233315}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:21,429] Trial 325 finished with value: 0.9497702233673845 and parameters: {'weight_class_0': 0.5100277466915537, 'weight_class_1': 8.164607294019914, 'weight_class_2': 6.2356460521953085}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:21,438] Trial 326 finished with value: 0.9494372226270121 and parameters: {'weight_class_0': 0.38090232844273897, 'weight_class_1': 8.233541801332885, 'weight_class_2': 6.20021552847705}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:21,454] Trial 327 finished with value: 0.9497944045470743 and parameters: {'weight_class_0': 0.5216005185929476, 'weight_class_1': 8.221380354106534, 'weight_class_2': 6.153954881661967}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:21,476] Trial 328 finished with value: 0.9497572136202702 and parameters: {'weight_class_0': 0.5457137394468131, 'weight_class_1': 9.46901847188109, 'weight_class_2': 6.217207671063963}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:21,489] Trial 329 finished with value: 0.9497878505218095 and parameters: {'weight_class_0': 0.541176699932811, 'weight_class_1': 8.203611929946744, 'weight_class_2': 6.213238569254218}. Best is trial 243 with value: 0.9498680470834587.
[I 2026-07-05 15:04:21,512] Trial 330 finished with value: 0.9498700288669591 and parameters: {'weight_class_0': 0.5778174468346758, 'weight_class_1': 9.450528047426932, 'weight_class_2': 6.261528171660667}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:21,549] Trial 332 finished with value: 0.9498073304007161 and parameters: {'weight_class_0': 0.5369186660659852, 'weight_class_1': 8.983800615416042, 'weight_class_2': 6.531748663707731}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:21,552] Trial 331 finished with value: 0.9497037250164674 and parameters: {'weight_class_0': 0.5253367255763428, 'weight_class_1': 9.528698402473614, 'weight_class_2': 6.532501708440928}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:21,565] Trial 333 finished with value: 0.9497183161034116 and parameters: {'weight_class_0': 0.5269145518202146, 'weight_class_1': 9.513303907515354, 'weight_class_2': 6.51029629049494}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:21,573] Trial 334 finished with value: 0.9497550934357603 and parameters: {'weight_class_0': 0.5549932200930623, 'weight_class_1': 9.492666331559807, 'weight_class_2': 6.5810700731087675}. Best is trial 330 with value: 0.9498700288669591.

Best trial: 330. Best value: 0.94987:  35%|██████████████████████████████████████████████▏                                                                                      | 347/1000 [00:06<00:12, 52.32it/s]

[I 2026-07-05 15:04:21,618] Trial 336 finished with value: 0.9498271209264632 and parameters: {'weight_class_0': 0.586869038744927, 'weight_class_1': 8.232895123990229, 'weight_class_2': 6.57024086469316}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:21,635] Trial 335 finished with value: 0.9497961078707773 and parameters: {'weight_class_0': 0.5746189403707332, 'weight_class_1': 8.165195193296254, 'weight_class_2': 6.6025062724791805}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:21,666] Trial 338 finished with value: 0.9498256296711073 and parameters: {'weight_class_0': 0.6067743867014669, 'weight_class_1': 8.200340831358314, 'weight_class_2': 6.589052812758753}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:21,671] Trial 337 finished with value: 0.9498319321138989 and parameters: {'weight_class_0': 0.6065893909008457, 'weight_class_1': 8.196564807277044, 'weight_class_2': 6.545282015636225}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:21,689] Trial 339 finished with value: 0.9487364530191162 and parameters: {'weight_class_0': 0.9348025486034081, 'weight_class_1': 8.192032779969574, 'weight_class_2': 6.642002597461054}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:21,714] Trial 340 finished with value: 0.9497532520271516 and parameters: {'weight_class_0': 0.6339768989802794, 'weight_class_1': 8.201385251106178, 'weight_class_2': 6.560645928955756}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:21,733] Trial 342 finished with value: 0.9458937335996209 and parameters: {'weight_class_0': 0.17570113189286246, 'weight_class_1': 8.917048343742186, 'weight_class_2': 6.6059282788719935}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:21,739] Trial 341 finished with value: 0.9487237110611662 and parameters: {'weight_class_0': 0.9531633174180938, 'weight_class_1': 8.178377324541762, 'weight_class_2': 6.724376154463784}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:21,767] Trial 343 finished with value: 0.9490086161338714 and parameters: {'weight_class_0': 0.8884174502723926, 'weight_class_1': 8.195867984621797, 'weight_class_2': 6.735118181803139}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:21,772] Trial 344 finished with value: 0.9489429775339215 and parameters: {'weight_class_0': 0.9160736178927317, 'weight_class_1': 8.948453986052801, 'weight_class_2': 6.762462126663573}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:21,809] Trial 346 finished with value: 0.9464663552178738 and parameters: {'weight_class_0': 0.1802361252201956, 'weight_class_1': 8.163216529823156, 'weight_class_2': 6.753201954289629}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:21,819] Trial 345 finished with value: 0.9488126202931516 and parameters: {'weight_class_0': 0.939309484311516, 'weight_class_1': 8.583893460120636, 'weight_class_2': 6.656638763966731}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:21,839] Trial 347 finished with value: 0.9488268641437791 and parameters: {'weight_class_0': 0.9257232980407347, 'weight_class_1': 8.901854463907178, 'weight_class_2': 6.53690655879645}. Best is trial 330 with value: 0.9498700288669591.

Best trial: 330. Best value: 0.94987:  36%|███████████████████████████████████████████████▋                                                                                     | 359/1000 [00:06<00:12, 52.79it/s]

[I 2026-07-05 15:04:21,851] Trial 348 finished with value: 0.9473069142051119 and parameters: {'weight_class_0': 0.2201492507328341, 'weight_class_1': 8.613768869742115, 'weight_class_2': 6.8147239012636005}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:21,881] Trial 349 finished with value: 0.9473388924805569 and parameters: {'weight_class_0': 0.22135187751581709, 'weight_class_1': 8.595859953346345, 'weight_class_2': 6.810778777643864}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:21,917] Trial 350 finished with value: 0.9488129249184106 and parameters: {'weight_class_0': 0.9417452826570092, 'weight_class_1': 8.63262838128145, 'weight_class_2': 6.755062647199035}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:21,932] Trial 352 finished with value: 0.9461903622726481 and parameters: {'weight_class_0': 0.185831618216378, 'weight_class_1': 8.930011869199724, 'weight_class_2': 6.839709394302775}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:21,937] Trial 351 finished with value: 0.9467519183098446 and parameters: {'weight_class_0': 0.19545713414709137, 'weight_class_1': 8.593696923440735, 'weight_class_2': 6.752128908086723}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:21,960] Trial 353 finished with value: 0.9482580927522793 and parameters: {'weight_class_0': 0.2742726381279743, 'weight_class_1': 8.589772013253963, 'weight_class_2': 6.881332739131929}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:21,972] Trial 354 finished with value: 0.9465037141420685 and parameters: {'weight_class_0': 0.1867569482871994, 'weight_class_1': 8.65343683714882, 'weight_class_2': 6.419583650132321}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:21,990] Trial 355 finished with value: 0.9473630708383937 and parameters: {'weight_class_0': 0.22279568091084867, 'weight_class_1': 8.508166603978776, 'weight_class_2': 6.8994808754223325}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,006] Trial 356 finished with value: 0.9469105397392553 and parameters: {'weight_class_0': 0.19998852394183847, 'weight_class_1': 8.635002111811687, 'weight_class_2': 6.437583232965299}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,019] Trial 358 finished with value: 0.9496556340697327 and parameters: {'weight_class_0': 0.6976803005558951, 'weight_class_1': 8.52557787665954, 'weight_class_2': 6.379087987826839}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,025] Trial 357 finished with value: 0.9459100216880102 and parameters: {'weight_class_0': 0.173923798432842, 'weight_class_1': 8.590529217582185, 'weight_class_2': 6.881202589827646}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,060] Trial 359 finished with value: 0.9494874701932745 and parameters: {'weight_class_0': 0.7404060515243628, 'weight_class_1': 7.8370514319683595, 'weight_class_2': 6.376428450636251}. Best is trial 330 with value: 0.9498700288669591.

Best trial: 330. Best value: 0.94987:  37%|█████████████████████████████████████████████████▏                                                                                   | 370/1000 [00:07<00:11, 53.74it/s]

[I 2026-07-05 15:04:22,081] Trial 360 finished with value: 0.8765386582037381 and parameters: {'weight_class_0': 7.6973409452960935, 'weight_class_1': 7.845362286126226, 'weight_class_2': 6.427019597085543}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,085] Trial 361 finished with value: 0.9495561228047142 and parameters: {'weight_class_0': 0.7056762684774996, 'weight_class_1': 7.832227957049762, 'weight_class_2': 6.352962302682569}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,114] Trial 362 finished with value: 0.9495705720930413 and parameters: {'weight_class_0': 0.6860276216724, 'weight_class_1': 7.826633752306538, 'weight_class_2': 6.400042183092091}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,126] Trial 363 finished with value: 0.9308269938201779 and parameters: {'weight_class_0': 0.7286275587488987, 'weight_class_1': 1.1911054813673312, 'weight_class_2': 6.387148086673979}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,163] Trial 365 finished with value: 0.9495648940587463 and parameters: {'weight_class_0': 0.7083317632572109, 'weight_class_1': 7.8813568908222615, 'weight_class_2': 6.409316451615671}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,171] Trial 364 finished with value: 0.9495435827840591 and parameters: {'weight_class_0': 0.6843950075266045, 'weight_class_1': 7.804814783865806, 'weight_class_2': 6.426401052197455}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,198] Trial 366 finished with value: 0.9495873317838274 and parameters: {'weight_class_0': 0.6954383660279999, 'weight_class_1': 7.955115231955849, 'weight_class_2': 6.365227051483462}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,210] Trial 368 finished with value: 0.9495484645829263 and parameters: {'weight_class_0': 0.723837076756201, 'weight_class_1': 7.836460970582093, 'weight_class_2': 6.357843263480399}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,218] Trial 367 finished with value: 0.9495403598344655 and parameters: {'weight_class_0': 0.7047845305345717, 'weight_class_1': 7.95008603875682, 'weight_class_2': 6.325217354916127}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,236] Trial 369 finished with value: 0.9495854661064405 and parameters: {'weight_class_0': 0.6755526403290277, 'weight_class_1': 7.893753661574485, 'weight_class_2': 6.326574397769917}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,259] Trial 370 finished with value: 0.8912932127230193 and parameters: {'weight_class_0': 5.877083192065407, 'weight_class_1': 7.7689628369219434, 'weight_class_2': 6.379881197294349}. Best is trial 330 with value: 0.9498700288669591.

Best trial: 330. Best value: 0.94987:  38%|██████████████████████████████████████████████████▊                                                                                  | 382/1000 [00:07<00:11, 53.88it/s]

[I 2026-07-05 15:04:22,265] Trial 371 finished with value: 0.9496237521599941 and parameters: {'weight_class_0': 0.6935374441277721, 'weight_class_1': 8.981111857713428, 'weight_class_2': 6.365733205466262}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,298] Trial 372 finished with value: 0.9496634597416161 and parameters: {'weight_class_0': 0.6653435543015124, 'weight_class_1': 8.324442629740169, 'weight_class_2': 6.312824381341851}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,309] Trial 373 finished with value: 0.9464548762730267 and parameters: {'weight_class_0': 1.3386715051290348, 'weight_class_1': 8.9619665508689, 'weight_class_2': 6.278491156566373}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,322] Trial 374 finished with value: 0.8915695283212051 and parameters: {'weight_class_0': 6.144960798055968, 'weight_class_1': 8.95091794913227, 'weight_class_2': 6.2581297980417485}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,353] Trial 375 finished with value: 0.9492974169482916 and parameters: {'weight_class_0': 0.38774292177556574, 'weight_class_1': 8.361260340681241, 'weight_class_2': 7.054541450887485}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,359] Trial 376 finished with value: 0.9495475238351431 and parameters: {'weight_class_0': 0.40650191371899397, 'weight_class_1': 8.362418895217443, 'weight_class_2': 6.274042428868317}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,374] Trial 377 finished with value: 0.9490324773507938 and parameters: {'weight_class_0': 0.3584785989859012, 'weight_class_1': 8.365646266362658, 'weight_class_2': 7.025220690585984}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,394] Trial 378 finished with value: 0.9496854464734245 and parameters: {'weight_class_0': 0.44193126289777085, 'weight_class_1': 8.353610745857049, 'weight_class_2': 6.212720124243882}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,425] Trial 379 finished with value: 0.949630833015235 and parameters: {'weight_class_0': 0.441725891796968, 'weight_class_1': 8.309808176615967, 'weight_class_2': 6.643522291197607}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,456] Trial 380 finished with value: 0.949492511084792 and parameters: {'weight_class_0': 0.4334282612757333, 'weight_class_1': 8.36405073048734, 'weight_class_2': 7.084547611405728}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,472] Trial 381 finished with value: 0.9495643457745971 and parameters: {'weight_class_0': 0.4204352639000132, 'weight_class_1': 8.248183642748087, 'weight_class_2': 6.623806327167535}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,479] Trial 382 finished with value: 0.8971060383265277 and parameters: {'weight_class_0': 1.3338682493338254, 'weight_class_1': 8.319350561968003, 'weight_class_2': 0.6344260977248233}. Best is trial 330 with value: 0.9498700288669591.

[I 2026-07-05 15:04:22,492] Trial 383 finished with value: 0.9495002910564002 and parameters: {'weight_class_0': 0.40787841090838417, 'weight_class_1': 8.414884226317374, 'weight_class_2': 6.624262102524227}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,523] Trial 384 finished with value: 0.9493376838678894 and parameters: {'weight_class_0': 0.39283570833921744, 'weight_class_1': 8.32520713329573, 'weight_class_2': 7.088208529712284}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,548] Trial 386 finished with value: 0.9482571323557836 and parameters: {'weight_class_0': 0.9844107770507098, 'weight_class_1': 9.378076615472638, 'weight_class_2': 6.01463905003853}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,571] Trial 385 finished with value: 0.9484764940378841 and parameters: {'weight_class_0': 1.0292483012365634, 'weight_class_1': 9.398421285284638, 'weight_class_2': 6.62682804858124}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,577] Trial 387 finished with value: 0.9481764689179881 and parameters: {'weight_class_0': 1.06093860046047, 'weight_class_1': 8.87114347040068, 'weight_class_2': 6.58509927651295}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,589] Trial 388 finished with value: 0.9487621126450788 and parameters: {'weight_class_0': 0.9527158406301857, 'weight_class_1': 9.384716622842083, 'weight_class_2': 6.600006836615733}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,600] Trial 389 finished with value: 0.9482500261294606 and parameters: {'weight_class_0': 0.9886652844144268, 'weight_class_1': 9.320132655896135, 'weight_class_2': 6.009195806409915}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,645] Trial 390 finished with value: 0.9483693185705216 and parameters: {'weight_class_0': 0.9687403523067257, 'weight_class_1': 9.36850631826792, 'weight_class_2': 6.085603987920798}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,658] Trial 391 finished with value: 0.9410396474304067 and parameters: {'weight_class_0': 1.020924130684542, 'weight_class_1': 2.998277301585384, 'weight_class_2': 5.950182509477432}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,667] Trial 392 finished with value: 0.9482458470631934 and parameters: {'weight_class_0': 0.9782374775285311, 'weight_class_1': 9.320232175132237, 'weight_class_2': 5.9611265611286415}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,676] Trial 393 finished with value: 0.9480008336733953 and parameters: {'weight_class_0': 1.0289297786922948, 'weight_class_1': 8.839186401335573, 'weight_class_2': 5.941762671464696}. Best is trial 330 with value: 0.9498700288669591.

Best trial: 330. Best value: 0.94987:  40%|█████████████████████████████████████████████████████▊                                                                               | 405/1000 [00:07<00:11, 53.66it/s]

[I 2026-07-05 15:04:22,703] Trial 394 finished with value: 0.9482514723630922 and parameters: {'weight_class_0': 0.9900845324715694, 'weight_class_1': 9.38488215951219, 'weight_class_2': 6.036730599652442}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,736] Trial 395 finished with value: 0.9480339160425669 and parameters: {'weight_class_0': 1.0409396366171593, 'weight_class_1': 8.847008059887902, 'weight_class_2': 6.062565901982589}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,747] Trial 396 finished with value: 0.9488246773955372 and parameters: {'weight_class_0': 0.8482978806000077, 'weight_class_1': 8.098464698455787, 'weight_class_2': 5.998573436864556}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,761] Trial 397 finished with value: 0.9498355781437607 and parameters: {'weight_class_0': 0.5515218758159227, 'weight_class_1': 8.113337453299936, 'weight_class_2': 6.018604447009522}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,773] Trial 398 finished with value: 0.9498514081222401 and parameters: {'weight_class_0': 0.556000781030837, 'weight_class_1': 9.08179636742238, 'weight_class_2': 5.98736488869584}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,794] Trial 399 finished with value: 0.9472475433535749 and parameters: {'weight_class_0': 0.5672041825525339, 'weight_class_1': 2.782407303236814, 'weight_class_2': 5.980209177188375}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,820] Trial 400 finished with value: 0.9497939383210197 and parameters: {'weight_class_0': 0.5827359790274089, 'weight_class_1': 9.055455702182751, 'weight_class_2': 6.048809820197865}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,830] Trial 402 finished with value: 0.9498393335540055 and parameters: {'weight_class_0': 0.5653959929729692, 'weight_class_1': 8.086540767080715, 'weight_class_2': 6.150109297838682}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,834] Trial 401 finished with value: 0.6578239520642909 and parameters: {'weight_class_0': 0.0010505965509834958, 'weight_class_1': 8.09476467182816, 'weight_class_2': 6.0789430807037474}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,862] Trial 403 finished with value: 0.9497892098755475 and parameters: {'weight_class_0': 0.5541272511207356, 'weight_class_1': 9.089724781039296, 'weight_class_2': 5.714919574516081}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,893] Trial 404 finished with value: 0.8708221688750083 and parameters: {'weight_class_0': 8.83981683911477, 'weight_class_1': 8.940886519989396, 'weight_class_2': 5.662666831433657}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,904] Trial 405 finished with value: 0.9497503955118392 and parameters: {'weight_class_0': 0.5679709625958825, 'weight_class_1': 9.06696427289903, 'weight_class_2': 5.679634664066872}. Best is trial 330 with value: 0.9498700288669591.

Best trial: 330. Best value: 0.94987:  42%|███████████████████████████████████████████████████████▎                                                                             | 416/1000 [00:08<00:10, 54.24it/s]

[I 2026-07-05 15:04:22,915] Trial 406 finished with value: 0.9496542362887451 and parameters: {'weight_class_0': 0.5954971177921451, 'weight_class_1': 9.024069903954292, 'weight_class_2': 5.663529524544377}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,926] Trial 407 finished with value: 0.8725265110619341 and parameters: {'weight_class_0': 0.03930359621015744, 'weight_class_1': 9.109540189854778, 'weight_class_2': 5.671224934640249}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,967] Trial 409 finished with value: 0.9236045531250608 and parameters: {'weight_class_0': 0.06918074058516832, 'weight_class_1': 8.99317960431317, 'weight_class_2': 5.651081366841901}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:22,977] Trial 408 finished with value: 0.9116093585836359 and parameters: {'weight_class_0': 4.054115498897176, 'weight_class_1': 9.082522378307788, 'weight_class_2': 5.690020137944354}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,007] Trial 411 finished with value: 0.9488610205556883 and parameters: {'weight_class_0': 0.3099426612584236, 'weight_class_1': 9.070841213370374, 'weight_class_2': 5.742300645382893}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,009] Trial 410 finished with value: 0.9492902606781701 and parameters: {'weight_class_0': 0.3307916424405796, 'weight_class_1': 9.09268214855398, 'weight_class_2': 4.642501458086657}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,061] Trial 413 finished with value: 0.9485726535466924 and parameters: {'weight_class_0': 0.2845374690190525, 'weight_class_1': 9.084536458330083, 'weight_class_2': 5.60171409821167}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,065] Trial 414 finished with value: 0.948976183986847 and parameters: {'weight_class_0': 0.3228501220366966, 'weight_class_1': 9.076848026055803, 'weight_class_2': 5.674183411285347}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,074] Trial 412 finished with value: 0.9489410943472646 and parameters: {'weight_class_0': 0.31405526071963175, 'weight_class_1': 9.032548504980888, 'weight_class_2': 5.6528547460248255}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,093] Trial 416 finished with value: 0.9489811305478457 and parameters: {'weight_class_0': 0.3091809476765088, 'weight_class_1': 8.736353088501989, 'weight_class_2': 5.305265292135561}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,096] Trial 415 finished with value: 0.9475441641099235 and parameters: {'weight_class_0': 0.2174132461336793, 'weight_class_1': 8.770852303911632, 'weight_class_2': 5.718108960058229}. Best is trial 330 with value: 0.9498700288669591.

Best trial: 330. Best value: 0.94987:  43%|████████████████████████████████████████████████████████▉                                                                            | 428/1000 [00:08<00:10, 53.46it/s]

[I 2026-07-05 15:04:23,139] Trial 418 finished with value: 0.9491904331920894 and parameters: {'weight_class_0': 0.35716582142228376, 'weight_class_1': 8.711351442218868, 'weight_class_2': 6.2235867758216985}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,150] Trial 419 finished with value: 0.9490108200656359 and parameters: {'weight_class_0': 0.3301416420871254, 'weight_class_1': 8.703322343638913, 'weight_class_2': 6.1979667567731305}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,155] Trial 417 finished with value: 0.9485168005184171 and parameters: {'weight_class_0': 0.28731555375170187, 'weight_class_1': 8.781793169701597, 'weight_class_2': 6.153259251950047}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,186] Trial 421 finished with value: 0.9487052236543567 and parameters: {'weight_class_0': 0.7900566880305266, 'weight_class_1': 8.759546647636363, 'weight_class_2': 5.364068397753821}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,192] Trial 420 finished with value: 0.9489912808216857 and parameters: {'weight_class_0': 0.3285768334193222, 'weight_class_1': 8.711888371471467, 'weight_class_2': 6.1864451966477825}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,211] Trial 422 finished with value: 0.9468815055326539 and parameters: {'weight_class_0': 0.7708467706274644, 'weight_class_1': 3.7867499973128034, 'weight_class_2': 6.162470972829436}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,251] Trial 423 finished with value: 0.9489728906053516 and parameters: {'weight_class_0': 0.8319472620179023, 'weight_class_1': 8.720454645946136, 'weight_class_2': 6.1445846843644985}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,265] Trial 424 finished with value: 0.9486301071638974 and parameters: {'weight_class_0': 0.8160532574645031, 'weight_class_1': 8.682748586937008, 'weight_class_2': 5.321138483981284}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,270] Trial 425 finished with value: 0.9492134246186872 and parameters: {'weight_class_0': 0.7878573955586327, 'weight_class_1': 9.64957420440762, 'weight_class_2': 6.1721768995425945}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,289] Trial 427 finished with value: 0.9490734453114356 and parameters: {'weight_class_0': 0.8228831189048698, 'weight_class_1': 9.740379579928602, 'weight_class_2': 6.199817559480149}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,295] Trial 426 finished with value: 0.9491657025043342 and parameters: {'weight_class_0': 0.7954066899651524, 'weight_class_1': 8.61421842701381, 'weight_class_2': 6.106541068129938}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,346] Trial 428 finished with value: 0.9491955959666131 and parameters: {'weight_class_0': 0.8112737609070027, 'weight_class_1': 8.102863664395551, 'weight_class_2': 6.519901980633971}. Best is trial 330 with value: 0.9498700288669591.

[I 2026-07-05 15:04:23,356] Trial 430 finished with value: 0.9493199151276883 and parameters: {'weight_class_0': 0.8077674235289799, 'weight_class_1': 9.635893322756472, 'weight_class_2': 6.515872869068023}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,371] Trial 429 finished with value: 0.9494110533772716 and parameters: {'weight_class_0': 0.7964967497923574, 'weight_class_1': 8.484846295291788, 'weight_class_2': 6.52618673119469}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,394] Trial 431 finished with value: 0.9497850444614824 and parameters: {'weight_class_0': 0.5399365983471508, 'weight_class_1': 7.604635873922197, 'weight_class_2': 6.535440051974326}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,399] Trial 432 finished with value: 0.9497312511011643 and parameters: {'weight_class_0': 0.5508202405699931, 'weight_class_1': 9.925443646761746, 'weight_class_2': 6.504178765480268}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,410] Trial 433 finished with value: 0.9497841001051798 and parameters: {'weight_class_0': 0.5511292364273324, 'weight_class_1': 8.064091717512866, 'weight_class_2': 6.525927687739191}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,444] Trial 434 finished with value: 0.9497421804245135 and parameters: {'weight_class_0': 0.5482556627904599, 'weight_class_1': 9.995792244104546, 'weight_class_2': 6.554802139285802}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,460] Trial 436 finished with value: 0.9497473169645566 and parameters: {'weight_class_0': 0.5511728275286564, 'weight_class_1': 8.102042684820066, 'weight_class_2': 6.488898797921534}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,478] Trial 435 finished with value: 0.9497213520347839 and parameters: {'weight_class_0': 0.5522695516101871, 'weight_class_1': 7.640120703571224, 'weight_class_2': 6.49370138027023}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,493] Trial 437 finished with value: 0.9497848257702014 and parameters: {'weight_class_0': 0.5441598074870346, 'weight_class_1': 7.641888218828512, 'weight_class_2': 6.509297632739261}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,503] Trial 438 finished with value: 0.9497325227144713 and parameters: {'weight_class_0': 0.5497301965626146, 'weight_class_1': 7.619847523416499, 'weight_class_2': 6.49779251366862}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,547] Trial 439 finished with value: 0.9497191604290355 and parameters: {'weight_class_0': 0.5139599258479332, 'weight_class_1': 9.277644493391582, 'weight_class_2': 5.846262303164915}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,553] Trial 440 finished with value: 0.949803746352158 and parameters: {'weight_class_0': 0.5218513320323042, 'weight_class_1': 7.578763972834892, 'weight_class_2': 5.9487891700512625}. Best is trial 330 with value: 0.9498700288669591.

Best trial: 330. Best value: 0.94987:  45%|███████████████████████████████████████████████████████████▉                                                                         | 451/1000 [00:08<00:10, 52.96it/s]

[I 2026-07-05 15:04:23,584] Trial 442 finished with value: 0.9497741799746019 and parameters: {'weight_class_0': 0.5352778689401043, 'weight_class_1': 9.3170118819758, 'weight_class_2': 5.889507085872347}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,592] Trial 441 finished with value: 0.9498215063999943 and parameters: {'weight_class_0': 0.5480889746015316, 'weight_class_1': 9.258222080337093, 'weight_class_2': 5.892059568024673}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,626] Trial 443 finished with value: 0.9497280809887633 and parameters: {'weight_class_0': 0.5130808653148006, 'weight_class_1': 9.273950082247957, 'weight_class_2': 5.870344198644375}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,641] Trial 444 finished with value: 0.9497935985917815 and parameters: {'weight_class_0': 0.5383410544669568, 'weight_class_1': 9.224649906908512, 'weight_class_2': 5.871390307423822}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,642] Trial 445 finished with value: 0.949725801881489 and parameters: {'weight_class_0': 0.47937975945231803, 'weight_class_1': 9.254315071060462, 'weight_class_2': 5.814273053930201}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,644] Trial 446 finished with value: 0.9497580158077943 and parameters: {'weight_class_0': 0.5217884756762372, 'weight_class_1': 9.272962062736546, 'weight_class_2': 5.870014513972627}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,685] Trial 447 finished with value: 0.9439558403800562 and parameters: {'weight_class_0': 0.14351602647639494, 'weight_class_1': 9.208616556838399, 'weight_class_2': 5.935921805092074}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,716] Trial 448 finished with value: 0.9426941497991322 and parameters: {'weight_class_0': 0.13152640514429453, 'weight_class_1': 9.287395510102623, 'weight_class_2': 5.815053960928295}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,721] Trial 449 finished with value: 0.946217066734416 and parameters: {'weight_class_0': 1.3294500704480052, 'weight_class_1': 9.327527004374765, 'weight_class_2': 5.932439494078697}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,731] Trial 450 finished with value: 0.9464085801094555 and parameters: {'weight_class_0': 1.2999480508842165, 'weight_class_1': 9.243046811323937, 'weight_class_2': 5.88560803594968}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,781] Trial 452 finished with value: 0.9403417463562262 and parameters: {'weight_class_0': 0.11040210798253924, 'weight_class_1': 8.874447533374411, 'weight_class_2': 5.842508301261028}. Best is trial 330 with value: 0.9498700288669591.

[I 2026-07-05 15:04:23,782] Trial 451 finished with value: 0.9452826125718502 and parameters: {'weight_class_0': 0.1576228093066654, 'weight_class_1': 8.89628359888497, 'weight_class_2': 5.877608222049005}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,795] Trial 453 finished with value: 0.9467623293401926 and parameters: {'weight_class_0': 1.2473319312644207, 'weight_class_1': 9.25836834851051, 'weight_class_2': 5.8576728402440725}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,811] Trial 455 finished with value: 0.9466599189439515 and parameters: {'weight_class_0': 1.2888823217503456, 'weight_class_1': 8.895899578038046, 'weight_class_2': 6.218416242787368}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,817] Trial 454 finished with value: 0.9423436422714548 and parameters: {'weight_class_0': 0.12447146012889815, 'weight_class_1': 8.910106728086054, 'weight_class_2': 5.970583345515836}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,833] Trial 456 finished with value: 0.947831374660958 and parameters: {'weight_class_0': 0.2412048758946439, 'weight_class_1': 8.874080243402833, 'weight_class_2': 6.313546008837612}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,865] Trial 457 finished with value: 0.9470928802775888 and parameters: {'weight_class_0': 1.2279996253639238, 'weight_class_1': 8.439196505155524, 'weight_class_2': 6.283992010805438}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,886] Trial 458 finished with value: 0.8525143306173245 and parameters: {'weight_class_0': 0.03622320460244188, 'weight_class_1': 9.617577816845632, 'weight_class_2': 6.308396801139238}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,890] Trial 459 finished with value: 0.6582782034105382 and parameters: {'weight_class_0': 0.0028434648780392147, 'weight_class_1': 9.609042834422342, 'weight_class_2': 6.240626432098103}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,957] Trial 461 finished with value: 0.8911903455480507 and parameters: {'weight_class_0': 0.04669692652877877, 'weight_class_1': 8.882311801663588, 'weight_class_2': 6.27225642724433}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,958] Trial 462 finished with value: 0.9495676427612239 and parameters: {'weight_class_0': 0.720102753387783, 'weight_class_1': 8.468800797443945, 'weight_class_2': 6.2979696726317}. Best is trial 330 with value: 0.9498700288669591.

Best trial: 330. Best value: 0.94987:  47%|██████████████████████████████████████████████████████████████▉                                                                      | 473/1000 [00:09<00:09, 53.03it/s]

[I 2026-07-05 15:04:23,971] Trial 460 finished with value: 0.7738147798917275 and parameters: {'weight_class_0': 0.021636881616243997, 'weight_class_1': 9.540954380851709, 'weight_class_2': 6.283962698401903}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:23,982] Trial 463 finished with value: 0.9000038342085706 and parameters: {'weight_class_0': 5.188406362135348, 'weight_class_1': 8.579376791743003, 'weight_class_2': 6.27865178122047}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,016] Trial 464 finished with value: 0.9497044079135772 and parameters: {'weight_class_0': 0.7014379214816525, 'weight_class_1': 9.5376573468392, 'weight_class_2': 6.831465162548904}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,020] Trial 465 finished with value: 0.9495718284171133 and parameters: {'weight_class_0': 0.7633251182995481, 'weight_class_1': 8.518340641116804, 'weight_class_2': 6.926501881150832}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,055] Trial 467 finished with value: 0.9496265542754184 and parameters: {'weight_class_0': 0.7349815606040979, 'weight_class_1': 9.530008972803577, 'weight_class_2': 6.868440599883283}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,059] Trial 466 finished with value: 0.9496049006962582 and parameters: {'weight_class_0': 0.767353559409192, 'weight_class_1': 9.53779435595396, 'weight_class_2': 6.81611366922235}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,072] Trial 468 finished with value: 0.9491087835755293 and parameters: {'weight_class_0': 0.7861814168671143, 'weight_class_1': 7.974969479507574, 'weight_class_2': 6.098356779956814}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,108] Trial 470 finished with value: 0.9495600890907717 and parameters: {'weight_class_0': 0.7539764159692287, 'weight_class_1': 8.552431325174862, 'weight_class_2': 6.84129926271489}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,118] Trial 469 finished with value: 0.9495682846640289 and parameters: {'weight_class_0': 0.7483208857606346, 'weight_class_1': 8.016744827718865, 'weight_class_2': 6.932509033367007}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,134] Trial 471 finished with value: 0.881084241779671 and parameters: {'weight_class_0': 0.8547930026994939, 'weight_class_1': 0.11538029949819073, 'weight_class_2': 6.054324122269429}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,177] Trial 472 finished with value: 0.9494057305593296 and parameters: {'weight_class_0': 0.7996139346631146, 'weight_class_1': 7.979568619419007, 'weight_class_2': 6.902487076974797}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,201] Trial 473 finished with value: 0.9486673118172408 and parameters: {'weight_class_0': 0.8000537567123668, 'weight_class_1': 8.041661604510132, 'weight_class_2': 5.447588649152863}. Best is trial 330 with value: 0.9498700288669591.

[I 2026-07-05 15:04:24,218] Trial 474 finished with value: 0.949145396573064 and parameters: {'weight_class_0': 0.35534880773507493, 'weight_class_1': 8.057223215912275, 'weight_class_2': 6.8197195844777205}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,219] Trial 476 finished with value: 0.9492779636383196 and parameters: {'weight_class_0': 0.3680334838368936, 'weight_class_1': 8.028831906116432, 'weight_class_2': 6.736378077829921}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,236] Trial 477 finished with value: 0.9492958588208139 and parameters: {'weight_class_0': 0.34231570300032854, 'weight_class_1': 7.744065778182245, 'weight_class_2': 6.062318149569076}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,243] Trial 475 finished with value: 0.9489440884228636 and parameters: {'weight_class_0': 0.8933497043705945, 'weight_class_1': 7.982683142118647, 'weight_class_2': 6.745371270336341}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,258] Trial 478 finished with value: 0.9493997099792613 and parameters: {'weight_class_0': 0.3909838675406341, 'weight_class_1': 8.007194883207719, 'weight_class_2': 6.685364760861891}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,290] Trial 480 finished with value: 0.9492719129835944 and parameters: {'weight_class_0': 0.36828265205122124, 'weight_class_1': 8.15292875218569, 'weight_class_2': 6.717372201779396}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,305] Trial 479 finished with value: 0.949472036114667 and parameters: {'weight_class_0': 0.37296938939791036, 'weight_class_1': 8.122265378101504, 'weight_class_2': 6.015306649152921}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,330] Trial 481 finished with value: 0.9493774737185174 and parameters: {'weight_class_0': 0.36556260859326717, 'weight_class_1': 8.227380756655194, 'weight_class_2': 6.046935888597186}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,341] Trial 482 finished with value: 0.9492071839443579 and parameters: {'weight_class_0': 0.3383976059506544, 'weight_class_1': 8.185276036183437, 'weight_class_2': 6.04079702991052}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,357] Trial 483 finished with value: 0.9492565692515075 and parameters: {'weight_class_0': 0.3626512055986928, 'weight_class_1': 8.19078227323724, 'weight_class_2': 6.682844123255624}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,381] Trial 484 finished with value: 0.9494549673807614 and parameters: {'weight_class_0': 0.36724786788185415, 'weight_class_1': 7.7197903664685885, 'weight_class_2': 6.081656217511844}. Best is trial 330 with value: 0.9498700288669591.

Best trial: 330. Best value: 0.94987:  50%|█████████████████████████████████████████████████████████████████▉                                                                   | 496/1000 [00:09<00:09, 54.05it/s]

[I 2026-07-05 15:04:24,408] Trial 485 finished with value: 0.947745197757269 and parameters: {'weight_class_0': 1.075442821863936, 'weight_class_1': 8.238434951442269, 'weight_class_2': 6.112974831058753}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,439] Trial 486 finished with value: 0.9495512080582018 and parameters: {'weight_class_0': 0.3945277703009501, 'weight_class_1': 8.260981270601276, 'weight_class_2': 6.083970772678634}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,445] Trial 487 finished with value: 0.9477245892151814 and parameters: {'weight_class_0': 1.090459036642471, 'weight_class_1': 8.354607179914963, 'weight_class_2': 6.052626453849558}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,449] Trial 488 finished with value: 0.920282912006884 and parameters: {'weight_class_0': 3.4333417515626126, 'weight_class_1': 8.391036842410795, 'weight_class_2': 6.039010709568596}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,502] Trial 489 finished with value: 0.9477713198082052 and parameters: {'weight_class_0': 1.07431786546067, 'weight_class_1': 8.298016945288483, 'weight_class_2': 6.112701284909142}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,505] Trial 490 finished with value: 0.9475607318602884 and parameters: {'weight_class_0': 1.122120497038504, 'weight_class_1': 8.377933768259995, 'weight_class_2': 6.063042997847544}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,543] Trial 492 finished with value: 0.949862908572395 and parameters: {'weight_class_0': 0.5964139259104332, 'weight_class_1': 8.402742525683504, 'weight_class_2': 6.495299573870023}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,549] Trial 491 finished with value: 0.9475387077012035 and parameters: {'weight_class_0': 1.0559357549098678, 'weight_class_1': 8.449821635911393, 'weight_class_2': 5.492971736291567}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,563] Trial 493 finished with value: 0.9477786574036364 and parameters: {'weight_class_0': 1.011930146351847, 'weight_class_1': 8.394443952508881, 'weight_class_2': 5.54197629425696}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,572] Trial 494 finished with value: 0.947801110212359 and parameters: {'weight_class_0': 1.1092402511844317, 'weight_class_1': 8.364114703113325, 'weight_class_2': 6.4366890021886825}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,585] Trial 495 finished with value: 0.9476647053776223 and parameters: {'weight_class_0': 1.0354346645549644, 'weight_class_1': 8.349868546776776, 'weight_class_2': 5.563581849906769}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,600] Trial 496 finished with value: 0.9496150904224532 and parameters: {'weight_class_0': 0.6128703111920599, 'weight_class_1': 8.427680178150691, 'weight_class_2': 5.552077389604502}. Best is trial 330 with value: 0.9498700288669591.

[I 2026-07-05 15:04:24,642] Trial 498 finished with value: 0.892704560616196 and parameters: {'weight_class_0': 0.6064662642647684, 'weight_class_1': 8.625657045803733, 'weight_class_2': 0.14361592858766503}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,656] Trial 497 finished with value: 0.9497728286419256 and parameters: {'weight_class_0': 0.6156540001264572, 'weight_class_1': 8.691969413581182, 'weight_class_2': 7.324780282019433}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,672] Trial 499 finished with value: 0.9496424579545469 and parameters: {'weight_class_0': 0.5840997214905254, 'weight_class_1': 8.60209059622169, 'weight_class_2': 5.501553380897453}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,688] Trial 500 finished with value: 0.9495129372239327 and parameters: {'weight_class_0': 0.6124178581669677, 'weight_class_1': 8.667520707674251, 'weight_class_2': 5.138249030704864}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,709] Trial 502 finished with value: 0.9498560811142595 and parameters: {'weight_class_0': 0.601603826472754, 'weight_class_1': 8.642828778632902, 'weight_class_2': 6.3982880345143816}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,720] Trial 501 finished with value: 0.888923191487036 and parameters: {'weight_class_0': 0.5550435425403206, 'weight_class_1': 8.981209992887552, 'weight_class_2': 0.08960730202354839}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,750] Trial 503 finished with value: 0.9497579787738198 and parameters: {'weight_class_0': 0.6168218031217878, 'weight_class_1': 7.513073056204978, 'weight_class_2': 6.436837397305584}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,764] Trial 504 finished with value: 0.9498134375368604 and parameters: {'weight_class_0': 0.6187264792449146, 'weight_class_1': 8.62442047594374, 'weight_class_2': 6.429463806881879}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,784] Trial 505 finished with value: 0.9497953866236162 and parameters: {'weight_class_0': 0.5762810073948009, 'weight_class_1': 8.663682127502302, 'weight_class_2': 6.479760523726346}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,800] Trial 506 finished with value: 0.9494616430192723 and parameters: {'weight_class_0': 0.6195807710786012, 'weight_class_1': 8.601636657183926, 'weight_class_2': 5.084854082192288}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,822] Trial 507 finished with value: 0.9498515522982123 and parameters: {'weight_class_0': 0.6153314626215044, 'weight_class_1': 8.646950006739903, 'weight_class_2': 6.47829212970642}. Best is trial 330 with value: 0.9498700288669591.

[I 2026-07-05 15:04:24,825] Trial 508 finished with value: 0.9497384528452226 and parameters: {'weight_class_0': 0.560817825340464, 'weight_class_1': 7.517744017820692, 'weight_class_2': 6.467925828747308}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,853] Trial 509 finished with value: 0.9497294495845566 and parameters: {'weight_class_0': 0.6199280996609159, 'weight_class_1': 7.575641714066439, 'weight_class_2': 6.388477213861253}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,856] Trial 510 finished with value: 0.947502373413939 and parameters: {'weight_class_0': 0.2111640242655488, 'weight_class_1': 7.715881913755486, 'weight_class_2': 6.437181322581345}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,885] Trial 511 finished with value: 0.949707740243554 and parameters: {'weight_class_0': 0.6287709194170656, 'weight_class_1': 7.534134563273651, 'weight_class_2': 6.350039764495703}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,894] Trial 512 finished with value: 0.949035989206875 and parameters: {'weight_class_0': 0.8582097278035326, 'weight_class_1': 8.83009893332333, 'weight_class_2': 6.470656978108446}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,914] Trial 513 finished with value: 0.9491627890708179 and parameters: {'weight_class_0': 0.8411623786119928, 'weight_class_1': 8.82481671951784, 'weight_class_2': 6.520934304659818}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,953] Trial 514 finished with value: 0.948931667980267 and parameters: {'weight_class_0': 0.8826403790928621, 'weight_class_1': 8.85794480608257, 'weight_class_2': 6.450173646652861}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,975] Trial 515 finished with value: 0.9390925082534994 and parameters: {'weight_class_0': 0.8730253747898478, 'weight_class_1': 2.1486996237299607, 'weight_class_2': 6.340295682931339}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:24,979] Trial 516 finished with value: 0.9383315618615712 and parameters: {'weight_class_0': 0.9156219943036698, 'weight_class_1': 2.1685443416893513, 'weight_class_2': 6.384500949001685}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:25,011] Trial 517 finished with value: 0.9487685660923698 and parameters: {'weight_class_0': 0.9181375167285646, 'weight_class_1': 8.801090153721994, 'weight_class_2': 6.360752683821632}. Best is trial 330 with value: 0.9498700288669591.

Best trial: 330. Best value: 0.94987:  53%|██████████████████████████████████████████████████████████████████████▏                                                              | 528/1000 [00:10<00:09, 49.46it/s]

[I 2026-07-05 15:04:25,029] Trial 518 finished with value: 0.9489556605380146 and parameters: {'weight_class_0': 0.8680973098872843, 'weight_class_1': 8.866747248342945, 'weight_class_2': 6.378308889066067}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:25,035] Trial 519 finished with value: 0.9489752917298105 and parameters: {'weight_class_0': 0.8548571863154136, 'weight_class_1': 8.784483234429311, 'weight_class_2': 6.326029351355268}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:25,053] Trial 520 finished with value: 0.9489547360249159 and parameters: {'weight_class_0': 0.8628509953378192, 'weight_class_1': 8.835163633083026, 'weight_class_2': 6.328112046931878}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:25,096] Trial 521 finished with value: 0.9489239671474214 and parameters: {'weight_class_0': 0.8686099602030504, 'weight_class_1': 8.996601011657226, 'weight_class_2': 6.32218699651404}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:25,126] Trial 522 finished with value: 0.9487812793713951 and parameters: {'weight_class_0': 0.8989638711543907, 'weight_class_1': 8.960858423921389, 'weight_class_2': 6.280897999915163}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:25,137] Trial 523 finished with value: 0.948973297815778 and parameters: {'weight_class_0': 0.8601638743614183, 'weight_class_1': 8.95620842631395, 'weight_class_2': 6.293485469482147}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:25,179] Trial 524 finished with value: 0.9468267992932659 and parameters: {'weight_class_0': 0.2016313357458016, 'weight_class_1': 9.031570937025798, 'weight_class_2': 6.209437605096769}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:25,180] Trial 525 finished with value: 0.9468963376155409 and parameters: {'weight_class_0': 0.2076628479922762, 'weight_class_1': 9.05420288703143, 'weight_class_2': 6.635974931597724}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:25,189] Trial 526 finished with value: 0.9469941528660554 and parameters: {'weight_class_0': 0.2087750930963213, 'weight_class_1': 9.094276822353663, 'weight_class_2': 6.258465238311514}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:25,223] Trial 528 finished with value: 0.9476311546912211 and parameters: {'weight_class_0': 0.23866253620303834, 'weight_class_1': 9.035128330553613, 'weight_class_2': 6.651491842167047}. Best is trial 330 with value: 0.9498700288669591.

Best trial: 330. Best value: 0.94987:  54%|███████████████████████████████████████████████████████████████████████▌                                                             | 538/1000 [00:10<00:09, 49.36it/s]

[I 2026-07-05 15:04:25,232] Trial 527 finished with value: 0.9460766887064315 and parameters: {'weight_class_0': 0.18374763589494147, 'weight_class_1': 9.133242023525334, 'weight_class_2': 6.62828426765853}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:25,256] Trial 529 finished with value: 0.9481696679650858 and parameters: {'weight_class_0': 0.26994698970505365, 'weight_class_1': 9.107423735794962, 'weight_class_2': 6.680957157295394}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:25,273] Trial 530 finished with value: 0.9476850082645539 and parameters: {'weight_class_0': 0.2427538697095104, 'weight_class_1': 9.144120443462272, 'weight_class_2': 6.651388937931623}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:25,293] Trial 531 finished with value: 0.9476524691579229 and parameters: {'weight_class_0': 0.23252058870349313, 'weight_class_1': 8.569634617073058, 'weight_class_2': 6.638511225466093}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:25,340] Trial 532 finished with value: 0.9481520549483866 and parameters: {'weight_class_0': 0.2599376168849336, 'weight_class_1': 8.481924541191507, 'weight_class_2': 6.665392659967854}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:25,345] Trial 533 finished with value: 0.9477148912666452 and parameters: {'weight_class_0': 0.2345774213150369, 'weight_class_1': 9.188594527934248, 'weight_class_2': 5.750958503964967}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:25,357] Trial 534 finished with value: 0.9474993976289579 and parameters: {'weight_class_0': 0.22583601748263732, 'weight_class_1': 8.545211723130693, 'weight_class_2': 6.61808747070295}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:25,389] Trial 535 finished with value: 0.9496868711650482 and parameters: {'weight_class_0': 0.4202903462941421, 'weight_class_1': 8.549592475738882, 'weight_class_2': 5.7528453416241145}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:25,422] Trial 536 finished with value: 0.9496584581846951 and parameters: {'weight_class_0': 0.42161132935337553, 'weight_class_1': 8.559819681800771, 'weight_class_2': 5.799766515832237}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:25,439] Trial 537 finished with value: 0.9496613446380904 and parameters: {'weight_class_0': 0.4173325780694341, 'weight_class_1': 8.565107400566855, 'weight_class_2': 5.735093825334988}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:25,460] Trial 538 finished with value: 0.9496371046073402 and parameters: {'weight_class_0': 0.41890039871690793, 'weight_class_1': 8.60324603519488, 'weight_class_2': 5.809868324971989}. Best is trial 330 with value: 0.9498700288669591.

Best trial: 330. Best value: 0.94987:  55%|████████████████████████████████████████████████████████████████████████▉                                                            | 548/1000 [00:10<00:09, 48.40it/s]

[I 2026-07-05 15:04:25,480] Trial 539 finished with value: 0.9496944149795264 and parameters: {'weight_class_0': 0.42829294303061494, 'weight_class_1': 8.460875823065903, 'weight_class_2': 5.835578673558415}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:25,495] Trial 540 finished with value: 0.9496557193381916 and parameters: {'weight_class_0': 0.41807966908731853, 'weight_class_1': 8.572824679014293, 'weight_class_2': 5.752690514434845}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:25,523] Trial 542 finished with value: 0.9497633339405115 and parameters: {'weight_class_0': 0.4529098536229447, 'weight_class_1': 8.519165431550721, 'weight_class_2': 4.428805636801034}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:25,527] Trial 541 finished with value: 0.9495970277000986 and parameters: {'weight_class_0': 0.40399653581653133, 'weight_class_1': 8.500830367381955, 'weight_class_2': 5.7518609175310385}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:25,560] Trial 543 finished with value: 0.9394721962736537 and parameters: {'weight_class_0': 0.49620268579069815, 'weight_class_1': 8.61220870257716, 'weight_class_2': 1.260472760122553}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:25,598] Trial 544 finished with value: 0.9496074637144755 and parameters: {'weight_class_0': 0.452491704361105, 'weight_class_1': 9.398616228609766, 'weight_class_2': 5.847746401704074}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:25,606] Trial 546 finished with value: 0.9484406830865083 and parameters: {'weight_class_0': 0.4718412921396874, 'weight_class_1': 8.641926144779516, 'weight_class_2': 2.875992348086666}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:25,616] Trial 545 finished with value: 0.9496356522570442 and parameters: {'weight_class_0': 0.41935582399222854, 'weight_class_1': 8.65413357630116, 'weight_class_2': 5.831265630263083}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:25,650] Trial 548 finished with value: 0.949484129266482 and parameters: {'weight_class_0': 0.7076459016511493, 'weight_class_1': 9.804262998801612, 'weight_class_2': 5.930742894439708}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:25,660] Trial 549 finished with value: 0.9495712096523231 and parameters: {'weight_class_0': 0.6695870352254103, 'weight_class_1': 7.827238834398829, 'weight_class_2': 5.9424927829201275}. Best is trial 330 with value: 0.9498700288669591.

[I 2026-07-05 15:04:25,667] Trial 547 finished with value: 0.9449518775187401 and parameters: {'weight_class_0': 0.48277509695311693, 'weight_class_1': 9.43735702741807, 'weight_class_2': 1.7660641677745028}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:25,694] Trial 550 finished with value: 0.9495802467626628 and parameters: {'weight_class_0': 0.6903765776929567, 'weight_class_1': 9.377904163362185, 'weight_class_2': 6.084024233701137}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:25,749] Trial 551 finished with value: 0.9494743667251733 and parameters: {'weight_class_0': 0.6917892636288734, 'weight_class_1': 7.006055106079667, 'weight_class_2': 6.180668638193007}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:25,764] Trial 553 finished with value: 0.949545675070992 and parameters: {'weight_class_0': 0.6765044983758229, 'weight_class_1': 7.047674658738432, 'weight_class_2': 6.145273679827208}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:25,773] Trial 552 finished with value: 0.9495951137959411 and parameters: {'weight_class_0': 0.6872997698204237, 'weight_class_1': 9.407076650674666, 'weight_class_2': 6.121262706481875}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:25,779] Trial 554 finished with value: 0.9495702294801784 and parameters: {'weight_class_0': 0.6806537757108682, 'weight_class_1': 7.868397433132196, 'weight_class_2': 6.1177054456641375}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:25,824] Trial 555 finished with value: 0.949515417153632 and parameters: {'weight_class_0': 0.6813128720096178, 'weight_class_1': 9.437479655968643, 'weight_class_2': 9.960488359906178}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:25,839] Trial 557 finished with value: 0.9490586466434898 and parameters: {'weight_class_0': 0.6921233245506148, 'weight_class_1': 7.808556374482917, 'weight_class_2': 5.261348404149203}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:25,846] Trial 556 finished with value: 0.949306583322778 and parameters: {'weight_class_0': 0.6749190944352206, 'weight_class_1': 9.499653480854114, 'weight_class_2': 5.238552215272453}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:25,865] Trial 558 finished with value: 0.9491800096238827 and parameters: {'weight_class_0': 0.6752096536599195, 'weight_class_1': 7.817929046134247, 'weight_class_2': 5.264529880605151}. Best is trial 330 with value: 0.9498700288669591.

Best trial: 330. Best value: 0.94987:  57%|███████████████████████████████████████████████████████████████████████████▌                                                         | 568/1000 [00:11<00:08, 48.08it/s]

[I 2026-07-05 15:04:25,908] Trial 559 finished with value: 0.9496075925138436 and parameters: {'weight_class_0': 0.674773179978728, 'weight_class_1': 8.867430871637879, 'weight_class_2': 6.156698452559133}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:25,932] Trial 560 finished with value: 0.949055836034046 and parameters: {'weight_class_0': 0.7042800307030247, 'weight_class_1': 8.876037692091513, 'weight_class_2': 5.229990225921708}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:25,947] Trial 561 finished with value: 0.9491647249484495 and parameters: {'weight_class_0': 0.6885244112668627, 'weight_class_1': 7.881504239642606, 'weight_class_2': 5.362523907545862}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:25,969] Trial 562 finished with value: 0.9495992119218454 and parameters: {'weight_class_0': 0.6821423867439305, 'weight_class_1': 8.818156671526335, 'weight_class_2': 6.17504206303359}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:25,995] Trial 563 finished with value: 0.6584298953724004 and parameters: {'weight_class_0': 0.002548645783360004, 'weight_class_1': 7.87732150473196, 'weight_class_2': 5.322921801509094}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:26,013] Trial 564 finished with value: 0.945108327230829 and parameters: {'weight_class_0': 1.6194460047549368, 'weight_class_1': 8.84989917454275, 'weight_class_2': 7.16630903738856}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:26,015] Trial 565 finished with value: 0.9468253848577007 and parameters: {'weight_class_0': 1.133955234129992, 'weight_class_1': 8.805118366890904, 'weight_class_2': 5.292050122295023}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:26,032] Trial 566 finished with value: 0.9471802194856168 and parameters: {'weight_class_0': 1.3401611300956238, 'weight_class_1': 8.779829271767873, 'weight_class_2': 7.138473359213437}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:26,050] Trial 567 finished with value: 0.9478747127824052 and parameters: {'weight_class_0': 1.173082804925003, 'weight_class_1': 8.790687729320249, 'weight_class_2': 7.040001557342689}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:26,087] Trial 568 finished with value: 0.9458482007464465 and parameters: {'weight_class_0': 1.5201571272327172, 'weight_class_1': 8.791952833019609, 'weight_class_2': 7.092461746058593}. Best is trial 330 with value: 0.9498700288669591.

Best trial: 330. Best value: 0.94987:  58%|████████████████████████████████████████████████████████████████████████████▊                                                        | 578/1000 [00:11<00:08, 47.64it/s]

[I 2026-07-05 15:04:26,111] Trial 569 finished with value: 0.948042569520141 and parameters: {'weight_class_0': 1.137044532767351, 'weight_class_1': 8.825973476359792, 'weight_class_2': 6.984287190007341}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:26,117] Trial 570 finished with value: 0.9472304712694646 and parameters: {'weight_class_0': 1.2217218003812835, 'weight_class_1': 8.296363199774005, 'weight_class_2': 6.527162113627502}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:26,129] Trial 571 finished with value: 0.9472617541548202 and parameters: {'weight_class_0': 1.2091886343035534, 'weight_class_1': 8.261450342695722, 'weight_class_2': 6.491146180858746}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:26,173] Trial 572 finished with value: 0.9475933602241682 and parameters: {'weight_class_0': 1.1873733841547707, 'weight_class_1': 8.294388004239606, 'weight_class_2': 7.030310359179902}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:26,201] Trial 573 finished with value: 0.9474926284509197 and parameters: {'weight_class_0': 1.204574588033016, 'weight_class_1': 8.264313194140895, 'weight_class_2': 7.005942772076628}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:26,220] Trial 574 finished with value: 0.947718074123436 and parameters: {'weight_class_0': 1.160192557088028, 'weight_class_1': 8.245111403933393, 'weight_class_2': 7.014322047814634}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:26,246] Trial 577 finished with value: 0.9487395481765626 and parameters: {'weight_class_0': 0.950512810767516, 'weight_class_1': 9.187673875887237, 'weight_class_2': 6.508701067346963}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:26,252] Trial 575 finished with value: 0.9474704342254792 and parameters: {'weight_class_0': 1.178818879312085, 'weight_class_1': 8.25462217440616, 'weight_class_2': 6.5032039428147534}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:26,274] Trial 576 finished with value: 0.948146218021717 and parameters: {'weight_class_0': 1.0286222419308817, 'weight_class_1': 8.290571452839462, 'weight_class_2': 6.466959201448671}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:26,302] Trial 579 finished with value: 0.9484203570089013 and parameters: {'weight_class_0': 0.9919515354614509, 'weight_class_1': 8.191283192141313, 'weight_class_2': 6.549531238778912}. Best is trial 330 with value: 0.9498700288669591.

[I 2026-07-05 15:04:26,323] Trial 578 finished with value: 0.9174285658581632 and parameters: {'weight_class_0': 0.9709362498307643, 'weight_class_1': 0.9789417854156968, 'weight_class_2': 6.473140683414771}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:26,339] Trial 580 finished with value: 0.9484002563580106 and parameters: {'weight_class_0': 0.9708299213293483, 'weight_class_1': 8.16480693594354, 'weight_class_2': 6.282483348484374}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:26,367] Trial 581 finished with value: 0.8735361962474077 and parameters: {'weight_class_0': 7.56492169685443, 'weight_class_1': 7.263385023367769, 'weight_class_2': 5.997561720191261}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:26,394] Trial 582 finished with value: 0.9484306618952941 and parameters: {'weight_class_0': 0.9833968292559867, 'weight_class_1': 9.193429657983163, 'weight_class_2': 6.265963208937663}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:26,425] Trial 584 finished with value: 0.9392156047215252 and parameters: {'weight_class_0': 0.9343106894704702, 'weight_class_1': 9.19899939168427, 'weight_class_2': 2.348101293782045}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:26,427] Trial 583 finished with value: 0.9484682012099238 and parameters: {'weight_class_0': 0.908152122333219, 'weight_class_1': 7.291997846011199, 'weight_class_2': 6.216425555336017}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:26,460] Trial 585 finished with value: 0.9486528414598642 and parameters: {'weight_class_0': 0.9209002357561291, 'weight_class_1': 9.111892746062606, 'weight_class_2': 6.253093128468621}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:26,464] Trial 586 finished with value: 0.9486552628720254 and parameters: {'weight_class_0': 0.940966565929868, 'weight_class_1': 9.771818825055737, 'weight_class_2': 6.209214837881146}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:26,483] Trial 587 finished with value: 0.9408305594156531 and parameters: {'weight_class_0': 0.46681941994965825, 'weight_class_1': 1.2366250731864605, 'weight_class_2': 6.261083667860549}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:26,513] Trial 588 finished with value: 0.9496747956793575 and parameters: {'weight_class_0': 0.4471797330026005, 'weight_class_1': 7.242201144204888, 'weight_class_2': 6.265018085572098}. Best is trial 330 with value: 0.9498700288669591.

Best trial: 330. Best value: 0.94987:  60%|███████████████████████████████████████████████████████████████████████████████▌                                                     | 598/1000 [00:11<00:08, 47.10it/s]

[I 2026-07-05 15:04:26,532] Trial 589 finished with value: 0.9496469283437522 and parameters: {'weight_class_0': 0.4501177734269748, 'weight_class_1': 9.195163103869163, 'weight_class_2': 5.943669359139355}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:26,540] Trial 591 finished with value: 0.9494349087651739 and parameters: {'weight_class_0': 0.4258158483109401, 'weight_class_1': 9.82128219525308, 'weight_class_2': 6.240840923349557}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:26,549] Trial 590 finished with value: 0.9495685118672136 and parameters: {'weight_class_0': 0.45570171681845406, 'weight_class_1': 9.757471878398668, 'weight_class_2': 6.011443237828215}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:26,597] Trial 592 finished with value: 0.9495263901749151 and parameters: {'weight_class_0': 0.42590438055596336, 'weight_class_1': 9.21241710004397, 'weight_class_2': 6.225183656329259}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:26,633] Trial 593 finished with value: 0.8721872090300131 and parameters: {'weight_class_0': 8.782798787716652, 'weight_class_1': 9.031046425006897, 'weight_class_2': 5.950905968467724}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:26,639] Trial 594 finished with value: 0.9495927458840961 and parameters: {'weight_class_0': 0.4587675737731191, 'weight_class_1': 9.747039810505457, 'weight_class_2': 5.951637033981982}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:26,661] Trial 595 finished with value: 0.9495904385375428 and parameters: {'weight_class_0': 0.4556340066136, 'weight_class_1': 8.038034672686978, 'weight_class_2': 6.769169241077107}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:26,680] Trial 596 finished with value: 0.9496258274921998 and parameters: {'weight_class_0': 0.42297884377532813, 'weight_class_1': 8.016887107753467, 'weight_class_2': 3.6978315014598575}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:26,700] Trial 597 finished with value: 0.9401816891194724 and parameters: {'weight_class_0': 2.0220404177267803, 'weight_class_1': 7.971217250051097, 'weight_class_2': 6.7940504606697285}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:26,742] Trial 598 finished with value: 0.9430817908957638 and parameters: {'weight_class_0': 0.11942246234644777, 'weight_class_1': 7.998363278139805, 'weight_class_2': 5.9297116623741575}. Best is trial 330 with value: 0.9498700288669591.

Best trial: 330. Best value: 0.94987:  61%|████████████████████████████████████████████████████████████████████████████████▊                                                    | 608/1000 [00:11<00:08, 47.24it/s]

[I 2026-07-05 15:04:26,746] Trial 599 finished with value: 0.9445584512505402 and parameters: {'weight_class_0': 0.14552747476596656, 'weight_class_1': 8.434468214378182, 'weight_class_2': 6.7659363820657825}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:26,775] Trial 600 finished with value: 0.9248029870236404 and parameters: {'weight_class_0': 2.9092112677963606, 'weight_class_1': 7.997980543997088, 'weight_class_2': 5.670875966840755}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:26,784] Trial 601 finished with value: 0.9087883353710607 and parameters: {'weight_class_0': 4.481136620918496, 'weight_class_1': 8.049077265945545, 'weight_class_2': 6.6743384101047765}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:26,812] Trial 602 finished with value: 0.9452334803070723 and parameters: {'weight_class_0': 0.1514690583939341, 'weight_class_1': 8.05208201787545, 'weight_class_2': 6.713977709513069}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:26,827] Trial 603 finished with value: 0.9397936151948354 and parameters: {'weight_class_0': 0.10297776018123223, 'weight_class_1': 8.052351010577905, 'weight_class_2': 6.757471292426198}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:26,856] Trial 604 finished with value: 0.942507328642536 and parameters: {'weight_class_0': 0.12278340554254297, 'weight_class_1': 8.39955048257573, 'weight_class_2': 6.740218644101485}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:26,870] Trial 605 finished with value: 0.9444820974978647 and parameters: {'weight_class_0': 0.13392866987800445, 'weight_class_1': 8.068909072314788, 'weight_class_2': 5.674650839945328}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:26,899] Trial 606 finished with value: 0.9443740657799395 and parameters: {'weight_class_0': 0.13789705285361603, 'weight_class_1': 8.523837642173012, 'weight_class_2': 5.619001846900129}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:26,925] Trial 607 finished with value: 0.6622971954061763 and parameters: {'weight_class_0': 0.004682987541043571, 'weight_class_1': 8.515205043118588, 'weight_class_2': 5.6017202125581145}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:26,940] Trial 608 finished with value: 0.9452099261521393 and parameters: {'weight_class_0': 0.15524399924006677, 'weight_class_1': 8.406368061430603, 'weight_class_2': 6.714261247935747}. Best is trial 330 with value: 0.9498700288669591.

Best trial: 330. Best value: 0.94987:  62%|██████████████████████████████████████████████████████████████████████████████████▍                                                  | 620/1000 [00:12<00:07, 49.23it/s]

[I 2026-07-05 15:04:26,953] Trial 609 finished with value: 0.9482484128549902 and parameters: {'weight_class_0': 0.24627191215720234, 'weight_class_1': 8.47593183593833, 'weight_class_2': 5.555053543978955}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:26,972] Trial 610 finished with value: 0.9477962184576435 and parameters: {'weight_class_0': 0.22751977130368428, 'weight_class_1': 8.644311644050575, 'weight_class_2': 5.6496146539547585}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:27,000] Trial 611 finished with value: 0.9462766866900761 and parameters: {'weight_class_0': 0.17595355572704185, 'weight_class_1': 8.689901494243003, 'weight_class_2': 5.488186069128727}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:27,020] Trial 613 finished with value: 0.9490719478366186 and parameters: {'weight_class_0': 0.7469219035629961, 'weight_class_1': 8.709936493197215, 'weight_class_2': 5.618339303378257}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:27,022] Trial 612 finished with value: 0.948990690236799 and parameters: {'weight_class_0': 0.7530225421098193, 'weight_class_1': 8.666185104544805, 'weight_class_2': 5.562314400640757}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:27,068] Trial 614 finished with value: 0.949548424793722 and parameters: {'weight_class_0': 0.7391766286018421, 'weight_class_1': 8.66622233376672, 'weight_class_2': 6.4043716724336255}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:27,083] Trial 615 finished with value: 0.949360477158273 and parameters: {'weight_class_0': 0.682032483968208, 'weight_class_1': 8.724711413047972, 'weight_class_2': 5.538539611821622}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:27,090] Trial 616 finished with value: 0.9490431200359642 and parameters: {'weight_class_0': 0.7481119750180083, 'weight_class_1': 8.702518768859303, 'weight_class_2': 5.561820235343268}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:27,105] Trial 617 finished with value: 0.9495158493982911 and parameters: {'weight_class_0': 0.7517480555390217, 'weight_class_1': 8.681995176642731, 'weight_class_2': 6.4210778552286545}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:27,131] Trial 618 finished with value: 0.9496060257562382 and parameters: {'weight_class_0': 0.7210527474281839, 'weight_class_1': 8.971733862477794, 'weight_class_2': 6.402872424753859}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:27,164] Trial 620 finished with value: 0.9495299803348196 and parameters: {'weight_class_0': 0.7519579929486726, 'weight_class_1': 8.952859235609717, 'weight_class_2': 6.447421576801322}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:27,168] Trial 619 finished with value: 0.9495157678821736 and parameters: {'weight_class_0': 0.7676088012178467, 'weight_class_1': 8.976689649298873, 'weight_class_2': 6.464609969062282}. Best is trial 330 with value: 0.9498700288669591.

Best trial: 330. Best value: 0.94987:  63%|███████████████████████████████████████████████████████████████████████████████████▋                                                 | 629/1000 [00:12<00:07, 47.66it/s]

[I 2026-07-05 15:04:27,205] Trial 621 finished with value: 0.9359138468994561 and parameters: {'weight_class_0': 0.7742345304942868, 'weight_class_1': 1.5555338501277678, 'weight_class_2': 6.411657186746216}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:27,234] Trial 622 finished with value: 0.9491679048140278 and parameters: {'weight_class_0': 0.5977546746989805, 'weight_class_1': 7.659420553840358, 'weight_class_2': 4.7138668842437195}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:27,254] Trial 623 finished with value: 0.9498269043784844 and parameters: {'weight_class_0': 0.5749192587320554, 'weight_class_1': 8.991822432024264, 'weight_class_2': 6.036489652372606}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:27,282] Trial 625 finished with value: 0.9497505784900745 and parameters: {'weight_class_0': 0.5987105615955839, 'weight_class_1': 8.9938057146414, 'weight_class_2': 6.122178843506214}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:27,292] Trial 624 finished with value: 0.9497380807103161 and parameters: {'weight_class_0': 0.6161180693781795, 'weight_class_1': 8.967978490864493, 'weight_class_2': 6.049547100807805}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:27,305] Trial 626 finished with value: 0.9498564402755151 and parameters: {'weight_class_0': 0.543388439949466, 'weight_class_1': 7.647585996028098, 'weight_class_2': 5.9855836282156645}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:27,326] Trial 627 finished with value: 0.9498350722930696 and parameters: {'weight_class_0': 0.5693064046259382, 'weight_class_1': 8.990650475269863, 'weight_class_2': 6.034018504650844}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:27,343] Trial 628 finished with value: 0.9498412330400406 and parameters: {'weight_class_0': 0.5633331873181096, 'weight_class_1': 9.005585912065003, 'weight_class_2': 6.107115469444854}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:27,366] Trial 629 finished with value: 0.949824115784006 and parameters: {'weight_class_0': 0.5552823177125121, 'weight_class_1': 8.96737274463719, 'weight_class_2': 6.076940336704097}. Best is trial 330 with value: 0.9498700288669591.

[I 2026-07-05 15:04:27,396] Trial 630 finished with value: 0.9497917150783847 and parameters: {'weight_class_0': 0.5765509471042808, 'weight_class_1': 9.376514341604375, 'weight_class_2': 6.040834451010324}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:27,414] Trial 632 finished with value: 0.9498204627200236 and parameters: {'weight_class_0': 0.5524598183512764, 'weight_class_1': 7.615113746376533, 'weight_class_2': 6.018946644363994}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:27,421] Trial 631 finished with value: 0.9497566180345204 and parameters: {'weight_class_0': 0.5996439820590094, 'weight_class_1': 9.524047298438498, 'weight_class_2': 6.029098196286039}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:27,435] Trial 633 finished with value: 0.9498414706570694 and parameters: {'weight_class_0': 0.5447314826778306, 'weight_class_1': 7.703608772635495, 'weight_class_2': 6.082692471841131}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:27,477] Trial 634 finished with value: 0.9498556714236814 and parameters: {'weight_class_0': 0.5649272248892839, 'weight_class_1': 9.368532302517748, 'weight_class_2': 6.054087755522284}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:27,499] Trial 635 finished with value: 0.9497718755242391 and parameters: {'weight_class_0': 0.5690000026319362, 'weight_class_1': 9.532959136772133, 'weight_class_2': 5.950737736243768}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:27,548] Trial 637 finished with value: 0.9490797590961636 and parameters: {'weight_class_0': 0.35371853198812, 'weight_class_1': 9.387893605936508, 'weight_class_2': 5.978183186645007}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:27,551] Trial 636 finished with value: 0.9494364922767655 and parameters: {'weight_class_0': 0.40970672034678435, 'weight_class_1': 9.462960235333343, 'weight_class_2': 5.887002949994565}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:27,571] Trial 638 finished with value: 0.9491081600487812 and parameters: {'weight_class_0': 0.35598027677518534, 'weight_class_1': 9.419458638260924, 'weight_class_2': 5.8442008767249956}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:27,577] Trial 639 finished with value: 0.9492014827720482 and parameters: {'weight_class_0': 0.36360145953174317, 'weight_class_1': 9.42400741866946, 'weight_class_2': 5.841360893206602}. Best is trial 330 with value: 0.9498700288669591.

Best trial: 330. Best value: 0.94987:  65%|██████████████████████████████████████████████████████████████████████████████████████▎                                              | 649/1000 [00:12<00:07, 46.96it/s]

[I 2026-07-05 15:04:27,590] Trial 640 finished with value: 0.948959979113379 and parameters: {'weight_class_0': 0.33267652198527825, 'weight_class_1': 9.494421562324673, 'weight_class_2': 5.868995226747827}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:27,643] Trial 642 finished with value: 0.9493213837517644 and parameters: {'weight_class_0': 0.3389358311194678, 'weight_class_1': 7.614754023094039, 'weight_class_2': 5.836437335158022}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:27,673] Trial 641 finished with value: 0.9493975606428687 and parameters: {'weight_class_0': 0.3468013923428013, 'weight_class_1': 7.433634251582033, 'weight_class_2': 5.813419525558319}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:27,679] Trial 643 finished with value: 0.9492763195768639 and parameters: {'weight_class_0': 0.3308505698766062, 'weight_class_1': 7.5277905548428565, 'weight_class_2': 5.876274442596722}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:27,718] Trial 644 finished with value: 0.9492278620776237 and parameters: {'weight_class_0': 0.32189075795795513, 'weight_class_1': 7.4768733109632155, 'weight_class_2': 5.806399356011052}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:27,738] Trial 645 finished with value: 0.9492216092800102 and parameters: {'weight_class_0': 0.33061787376982366, 'weight_class_1': 7.763298290491887, 'weight_class_2': 5.806952265366243}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:27,764] Trial 647 finished with value: 0.9490071843647057 and parameters: {'weight_class_0': 0.29885368827968073, 'weight_class_1': 7.355027407668796, 'weight_class_2': 5.783277065345397}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:27,767] Trial 646 finished with value: 0.9492281408458112 and parameters: {'weight_class_0': 0.3263002736955649, 'weight_class_1': 7.776357047421538, 'weight_class_2': 5.7630390381071965}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:27,808] Trial 648 finished with value: 0.9489255767067161 and parameters: {'weight_class_0': 0.293607540461442, 'weight_class_1': 7.44673891690771, 'weight_class_2': 5.799732064690568}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:27,814] Trial 649 finished with value: 0.948237591749879 and parameters: {'weight_class_0': 0.9024315922191531, 'weight_class_1': 7.529760694413916, 'weight_class_2': 5.708511791468546}. Best is trial 330 with value: 0.9498700288669591.

[I 2026-07-05 15:04:27,856] Trial 650 finished with value: 0.9480918532623761 and parameters: {'weight_class_0': 0.93204091114625, 'weight_class_1': 7.453833487613679, 'weight_class_2': 5.800775048169447}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:27,878] Trial 651 finished with value: 0.9484276770356869 and parameters: {'weight_class_0': 0.8821878094854171, 'weight_class_1': 7.444690933928361, 'weight_class_2': 5.725396086256779}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:27,912] Trial 652 finished with value: 0.8696915192223619 and parameters: {'weight_class_0': 8.281876288125982, 'weight_class_1': 7.342398142104168, 'weight_class_2': 6.046751718468803}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:27,920] Trial 653 finished with value: 0.9487145040205793 and parameters: {'weight_class_0': 0.8707802883739102, 'weight_class_1': 7.40892271352357, 'weight_class_2': 6.099438673486483}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:27,940] Trial 654 finished with value: 0.948188800028999 and parameters: {'weight_class_0': 0.9680276287574945, 'weight_class_1': 7.685593902501867, 'weight_class_2': 6.142295894182901}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:27,947] Trial 655 finished with value: 0.9486681611649392 and parameters: {'weight_class_0': 0.8573438045735244, 'weight_class_1': 7.240829757975758, 'weight_class_2': 6.100291312389644}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:27,961] Trial 656 finished with value: 0.9484219454113112 and parameters: {'weight_class_0': 0.8998955881460307, 'weight_class_1': 7.27229215815859, 'weight_class_2': 6.102940423705089}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:28,022] Trial 657 finished with value: 0.9486027744558525 and parameters: {'weight_class_0': 0.8963301501046184, 'weight_class_1': 7.719959369794545, 'weight_class_2': 6.107016897218171}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:28,028] Trial 659 finished with value: 0.9487101406189744 and parameters: {'weight_class_0': 0.8995993100136848, 'weight_class_1': 9.258784290431507, 'weight_class_2': 6.021505835973066}. Best is trial 330 with value: 0.9498700288669591.

[I 2026-07-05 15:04:28,029] Trial 658 finished with value: 0.948910672309862 and parameters: {'weight_class_0': 0.8504769016805549, 'weight_class_1': 9.674190527695655, 'weight_class_2': 6.155685199896766}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:28,046] Trial 660 finished with value: 0.9485410412503942 and parameters: {'weight_class_0': 0.9111968522341918, 'weight_class_1': 7.67756696045155, 'weight_class_2': 6.089840779074179}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:28,070] Trial 661 finished with value: 0.9487567189483409 and parameters: {'weight_class_0': 0.8582878361280024, 'weight_class_1': 7.651587936797561, 'weight_class_2': 6.023337782929603}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:28,097] Trial 662 finished with value: 0.9488474954870322 and parameters: {'weight_class_0': 0.852696836180477, 'weight_class_1': 9.696981322035505, 'weight_class_2': 6.097992029159203}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:28,113] Trial 663 finished with value: 0.9487735149279269 and parameters: {'weight_class_0': 0.8634267437433747, 'weight_class_1': 7.705566260942738, 'weight_class_2': 6.097766651445034}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:28,145] Trial 664 finished with value: 0.9497214225767306 and parameters: {'weight_class_0': 0.5294470801903851, 'weight_class_1': 9.660168803734088, 'weight_class_2': 6.143338131020193}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:28,171] Trial 666 finished with value: 0.9496645590806327 and parameters: {'weight_class_0': 0.5861247712866444, 'weight_class_1': 9.190548849702864, 'weight_class_2': 5.4234894120924535}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:28,185] Trial 665 finished with value: 0.8891539459401607 and parameters: {'weight_class_0': 6.506893135752922, 'weight_class_1': 9.274434993848555, 'weight_class_2': 6.195315644921338}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:28,215] Trial 668 finished with value: 0.9497274990885275 and parameters: {'weight_class_0': 0.5194142008665765, 'weight_class_1': 9.245323552963399, 'weight_class_2': 6.193008586808444}. Best is trial 330 with value: 0.9498700288669591.

[I 2026-07-05 15:04:28,256] Trial 667 finished with value: 0.9498640129050265 and parameters: {'weight_class_0': 0.5667300165930573, 'weight_class_1': 9.318979142136001, 'weight_class_2': 6.179192323717878}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:28,264] Trial 669 finished with value: 0.9498112347464954 and parameters: {'weight_class_0': 0.5561966247237935, 'weight_class_1': 9.275695117926714, 'weight_class_2': 6.2651530361629515}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:28,293] Trial 670 finished with value: 0.9497324590469299 and parameters: {'weight_class_0': 0.5580248632763134, 'weight_class_1': 9.21477212090903, 'weight_class_2': 5.418392156075592}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:28,305] Trial 671 finished with value: 0.9496548632107054 and parameters: {'weight_class_0': 0.5747951800646046, 'weight_class_1': 9.228758495037123, 'weight_class_2': 5.3677722012340165}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:28,332] Trial 672 finished with value: 0.9497396577558277 and parameters: {'weight_class_0': 0.5302080469059702, 'weight_class_1': 9.137755129779661, 'weight_class_2': 6.258714247400792}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:28,353] Trial 673 finished with value: 0.9294000977052322 and parameters: {'weight_class_0': 2.6305394646925526, 'weight_class_1': 9.24694267359314, 'weight_class_2': 5.415502935229003}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:28,374] Trial 674 finished with value: 0.9496019570211217 and parameters: {'weight_class_0': 0.6024127720943053, 'weight_class_1': 9.22823771064264, 'weight_class_2': 5.416502847741039}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:28,391] Trial 675 finished with value: 0.9498344252195157 and parameters: {'weight_class_0': 0.5597976642199047, 'weight_class_1': 9.154051623764667, 'weight_class_2': 6.272421700030871}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:28,402] Trial 676 finished with value: 0.6599000110439024 and parameters: {'weight_class_0': 0.004117811718436948, 'weight_class_1': 9.210839496623684, 'weight_class_2': 6.294766742049573}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:28,436] Trial 677 finished with value: 0.9463954093990711 and parameters: {'weight_class_0': 1.3881022682996016, 'weight_class_1': 9.971102829068322, 'weight_class_2': 6.245733951525589}. Best is trial 330 with value: 0.9498700288669591.

Best trial: 330. Best value: 0.94987:  69%|███████████████████████████████████████████████████████████████████████████████████████████▏                                         | 686/1000 [00:13<00:07, 42.76it/s]

[I 2026-07-05 15:04:28,458] Trial 678 finished with value: 0.9496750808233944 and parameters: {'weight_class_0': 0.5675990081227689, 'weight_class_1': 9.091488539162679, 'weight_class_2': 5.0164599766544145}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:28,489] Trial 679 finished with value: 0.9498159957129987 and parameters: {'weight_class_0': 0.5908459200450167, 'weight_class_1': 9.977959074339205, 'weight_class_2': 6.3366611919881635}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:28,517] Trial 680 finished with value: 0.9497189696430456 and parameters: {'weight_class_0': 0.65792977549734, 'weight_class_1': 9.5625627551648, 'weight_class_2': 6.318349268399611}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:28,536] Trial 681 finished with value: 0.9496904751465749 and parameters: {'weight_class_0': 0.6615796857940959, 'weight_class_1': 9.593145859591488, 'weight_class_2': 6.317482691265331}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:28,586] Trial 682 finished with value: 0.9496833221997237 and parameters: {'weight_class_0': 0.6841492444136384, 'weight_class_1': 9.661900913141771, 'weight_class_2': 6.3289788573295995}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:28,595] Trial 684 finished with value: 0.9496475726441922 and parameters: {'weight_class_0': 0.6634684719789083, 'weight_class_1': 9.070226838395804, 'weight_class_2': 6.328209390845413}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:28,618] Trial 683 finished with value: 0.9490812968119312 and parameters: {'weight_class_0': 0.6940720167944252, 'weight_class_1': 9.630280464290417, 'weight_class_2': 5.059676194232993}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:28,628] Trial 685 finished with value: 0.9495933342581256 and parameters: {'weight_class_0': 0.7185808022956084, 'weight_class_1': 9.6465909997638, 'weight_class_2': 6.340480556570902}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:28,645] Trial 686 finished with value: 0.9177150221606863 and parameters: {'weight_class_0': 3.8398454265319124, 'weight_class_1': 9.01805389895163, 'weight_class_2': 6.3358471292255}. Best is trial 330 with value: 0.9498700288669591.

Best trial: 330. Best value: 0.94987:  70%|████████████████████████████████████████████████████████████████████████████████████████████▌                                        | 696/1000 [00:13<00:06, 45.72it/s]

[I 2026-07-05 15:04:28,679] Trial 687 finished with value: 0.9496336903037158 and parameters: {'weight_class_0': 0.7099287016966438, 'weight_class_1': 9.563246724414382, 'weight_class_2': 6.447460789022359}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:28,683] Trial 688 finished with value: 0.9478970155070067 and parameters: {'weight_class_0': 0.25940488330418227, 'weight_class_1': 9.580593984346974, 'weight_class_2': 6.390122269448652}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:28,705] Trial 689 finished with value: 0.9496451232031978 and parameters: {'weight_class_0': 0.695033739838292, 'weight_class_1': 9.557654566822269, 'weight_class_2': 6.332721284384672}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:28,731] Trial 690 finished with value: 0.9481804660262726 and parameters: {'weight_class_0': 1.0816921516988698, 'weight_class_1': 9.588811029618624, 'weight_class_2': 6.536794195519115}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:28,769] Trial 691 finished with value: 0.9480668776821711 and parameters: {'weight_class_0': 1.1057492369165258, 'weight_class_1': 9.408951096270034, 'weight_class_2': 6.560244443747484}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:28,775] Trial 692 finished with value: 0.9477666881299823 and parameters: {'weight_class_0': 0.25236496528213503, 'weight_class_1': 9.475480425907582, 'weight_class_2': 6.508618355163895}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:28,814] Trial 693 finished with value: 0.9481948979515472 and parameters: {'weight_class_0': 1.0652212962124696, 'weight_class_1': 9.010630411088094, 'weight_class_2': 6.553443894871573}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:28,845] Trial 694 finished with value: 0.9479717190815616 and parameters: {'weight_class_0': 0.2627290601001867, 'weight_class_1': 9.4021769177748, 'weight_class_2': 6.534181752964705}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:28,865] Trial 695 finished with value: 0.9482014666599031 and parameters: {'weight_class_0': 0.2763172981727116, 'weight_class_1': 9.420016661205764, 'weight_class_2': 6.5322501580088925}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:28,887] Trial 696 finished with value: 0.9479313225368345 and parameters: {'weight_class_0': 1.0766533242711653, 'weight_class_1': 9.345975639468204, 'weight_class_2': 5.976078383427816}. Best is trial 330 with value: 0.9498700288669591.

Best trial: 330. Best value: 0.94987:  71%|█████████████████████████████████████████████████████████████████████████████████████████████▉                                       | 706/1000 [00:14<00:06, 42.92it/s]

[I 2026-07-05 15:04:28,921] Trial 697 finished with value: 0.94540902957766 and parameters: {'weight_class_0': 1.0964898226710296, 'weight_class_1': 9.014921745154782, 'weight_class_2': 4.291868644013765}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:28,958] Trial 699 finished with value: 0.9485147872341386 and parameters: {'weight_class_0': 0.29606531721384743, 'weight_class_1': 9.002092466176864, 'weight_class_2': 6.608297699283264}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:28,974] Trial 698 finished with value: 0.7689643088406944 and parameters: {'weight_class_0': 0.017529581992604237, 'weight_class_1': 8.948755170440695, 'weight_class_2': 4.187470484623805}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:28,979] Trial 700 finished with value: 0.948635490031218 and parameters: {'weight_class_0': 0.31329712794800324, 'weight_class_1': 9.011814688830087, 'weight_class_2': 6.58235944379702}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:28,982] Trial 701 finished with value: 0.94860175138261 and parameters: {'weight_class_0': 0.2917728040027301, 'weight_class_1': 8.954754019687398, 'weight_class_2': 5.936429890401223}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:29,014] Trial 702 finished with value: 0.9495608582278541 and parameters: {'weight_class_0': 0.4134168045167106, 'weight_class_1': 8.939457830267445, 'weight_class_2': 5.951485739192277}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:29,029] Trial 703 finished with value: 0.9495009434652709 and parameters: {'weight_class_0': 0.3999055648978257, 'weight_class_1': 8.997339475665138, 'weight_class_2': 5.920298437903901}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:29,065] Trial 705 finished with value: 0.9494994685527144 and parameters: {'weight_class_0': 0.40051151799572776, 'weight_class_1': 8.94280080037027, 'weight_class_2': 5.954994956705468}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:29,067] Trial 704 finished with value: 0.9493780148092964 and parameters: {'weight_class_0': 0.3811678491969982, 'weight_class_1': 9.04847973632676, 'weight_class_2': 5.9609418832088235}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:29,083] Trial 706 finished with value: 0.9496786955377914 and parameters: {'weight_class_0': 0.44550351681901523, 'weight_class_1': 9.050587324257718, 'weight_class_2': 5.967756280502701}. Best is trial 330 with value: 0.9498700288669591.

[I 2026-07-05 15:04:29,111] Trial 707 finished with value: 0.9496687993265761 and parameters: {'weight_class_0': 0.45357427479504714, 'weight_class_1': 8.927542856703822, 'weight_class_2': 5.945703421035636}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:29,138] Trial 708 finished with value: 0.9496570041355953 and parameters: {'weight_class_0': 0.4304408441409556, 'weight_class_1': 8.969952354815174, 'weight_class_2': 5.925606418591922}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:29,157] Trial 709 finished with value: 0.9497054458677902 and parameters: {'weight_class_0': 0.42839802287475204, 'weight_class_1': 7.876722696931349, 'weight_class_2': 5.898920180721728}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:29,208] Trial 710 finished with value: 0.949792890421068 and parameters: {'weight_class_0': 0.49162731044925967, 'weight_class_1': 7.862847435821992, 'weight_class_2': 5.941587863275857}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:29,221] Trial 711 finished with value: 0.9496990124692962 and parameters: {'weight_class_0': 0.4424028397551094, 'weight_class_1': 7.898885530259222, 'weight_class_2': 5.947674116570722}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:29,254] Trial 712 finished with value: 0.9496664310599975 and parameters: {'weight_class_0': 0.4545884742890482, 'weight_class_1': 7.918170805973714, 'weight_class_2': 5.95367228564275}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:29,262] Trial 713 finished with value: 0.9497515055784077 and parameters: {'weight_class_0': 0.47538813064622376, 'weight_class_1': 8.18537838874747, 'weight_class_2': 5.630902068648828}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:29,321] Trial 714 finished with value: 0.9450477236108599 and parameters: {'weight_class_0': 1.3833988704159075, 'weight_class_1': 8.359694925874267, 'weight_class_2': 5.722570178674755}. Best is trial 330 with value: 0.9498700288669591.

[I 2026-07-05 15:04:29,332] Trial 715 finished with value: 0.9489246530232386 and parameters: {'weight_class_0': 0.7858771057178331, 'weight_class_1': 8.377619825230404, 'weight_class_2': 5.7102655321505775}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:29,347] Trial 716 finished with value: 0.9461146358795273 and parameters: {'weight_class_0': 0.7870443677543487, 'weight_class_1': 3.6060328576226874, 'weight_class_2': 5.704703997744138}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:29,361] Trial 717 finished with value: 0.948868577091415 and parameters: {'weight_class_0': 0.7807417553734514, 'weight_class_1': 7.88717144718106, 'weight_class_2': 5.652284628773616}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:29,395] Trial 718 finished with value: 0.9487250925659779 and parameters: {'weight_class_0': 0.8191084615116883, 'weight_class_1': 8.224558125504624, 'weight_class_2': 5.616919719197207}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:29,414] Trial 719 finished with value: 0.9489972765441897 and parameters: {'weight_class_0': 0.7679028343263015, 'weight_class_1': 8.362449488495649, 'weight_class_2': 5.63319058933252}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:29,421] Trial 720 finished with value: 0.9491581421414632 and parameters: {'weight_class_0': 0.7329187156796875, 'weight_class_1': 8.212300846121364, 'weight_class_2': 5.693154234875004}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:29,460] Trial 721 finished with value: 0.8953432806616576 and parameters: {'weight_class_0': 5.264844237240462, 'weight_class_1': 8.356562431298752, 'weight_class_2': 5.653027687081455}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:29,474] Trial 722 finished with value: 0.9447382587241666 and parameters: {'weight_class_0': 1.394421077291318, 'weight_class_1': 8.218902464908801, 'weight_class_2': 5.6662397337178865}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:29,515] Trial 723 finished with value: 0.944650834157915 and parameters: {'weight_class_0': 1.418051176687925, 'weight_class_1': 8.393377261759388, 'weight_class_2': 5.685037950935353}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:29,527] Trial 724 finished with value: 0.9459387528883791 and parameters: {'weight_class_0': 1.3688135203714173, 'weight_class_1': 8.452570291255547, 'weight_class_2': 6.212350871989073}. Best is trial 330 with value: 0.9498700288669591.

Best trial: 330. Best value: 0.94987:  73%|█████████████████████████████████████████████████████████████████████████████████████████████████▌                                   | 734/1000 [00:14<00:06, 43.96it/s]

[I 2026-07-05 15:04:29,538] Trial 725 finished with value: 0.9491846582520412 and parameters: {'weight_class_0': 0.7926431223984141, 'weight_class_1': 8.41809324121053, 'weight_class_2': 6.176428185358182}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:29,551] Trial 726 finished with value: 0.9490415484159996 and parameters: {'weight_class_0': 0.8079072617387026, 'weight_class_1': 8.167518519399877, 'weight_class_2': 6.147309520968127}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:29,599] Trial 727 finished with value: 0.934493785665676 and parameters: {'weight_class_0': 0.08407888360888072, 'weight_class_1': 8.185992972719916, 'weight_class_2': 6.197359910206825}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:29,613] Trial 728 finished with value: 0.8767581702111215 and parameters: {'weight_class_0': 0.03947248433036854, 'weight_class_1': 8.400325517320628, 'weight_class_2': 6.228217176487759}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:29,671] Trial 730 finished with value: 0.945283321688479 and parameters: {'weight_class_0': 0.15702234559979167, 'weight_class_1': 8.705737121053506, 'weight_class_2': 6.1714872729376316}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:29,673] Trial 729 finished with value: 0.7489769982637408 and parameters: {'weight_class_0': 0.01727708824348917, 'weight_class_1': 8.74406593933815, 'weight_class_2': 6.187199288294672}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:29,694] Trial 731 finished with value: 0.9251039071630509 and parameters: {'weight_class_0': 3.15036001169275, 'weight_class_1': 8.730243643036246, 'weight_class_2': 6.193682197697802}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:29,715] Trial 732 finished with value: 0.9268191514629228 and parameters: {'weight_class_0': 0.07326338472645794, 'weight_class_1': 8.761292396445029, 'weight_class_2': 6.132307733065816}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:29,747] Trial 733 finished with value: 0.9233583209876078 and parameters: {'weight_class_0': 0.06874255932347428, 'weight_class_1': 8.757900714575507, 'weight_class_2': 6.18741241799756}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:29,766] Trial 734 finished with value: 0.9395349140926571 and parameters: {'weight_class_0': 0.10568018282849156, 'weight_class_1': 8.695393498410713, 'weight_class_2': 6.161524702347929}. Best is trial 330 with value: 0.9498700288669591.

Best trial: 330. Best value: 0.94987:  74%|██████████████████████████████████████████████████████████████████████████████████████████████████▊                                  | 743/1000 [00:14<00:06, 42.35it/s]

[I 2026-07-05 15:04:29,771] Trial 735 finished with value: 0.9457633031644712 and parameters: {'weight_class_0': 0.1756632880264959, 'weight_class_1': 9.294189961852949, 'weight_class_2': 6.2525846049016565}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:29,805] Trial 736 finished with value: 0.742406879618414 and parameters: {'weight_class_0': 0.016490336064400313, 'weight_class_1': 8.72936886995905, 'weight_class_2': 6.200663233388793}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:29,834] Trial 737 finished with value: 0.941880011522711 and parameters: {'weight_class_0': 0.10099643171929124, 'weight_class_1': 0.4329782840833838, 'weight_class_2': 6.202776801226613}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:29,844] Trial 738 finished with value: 0.9462092270927621 and parameters: {'weight_class_0': 0.17940594407238525, 'weight_class_1': 8.797020443378655, 'weight_class_2': 6.235401948413352}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:29,889] Trial 740 finished with value: 0.9480861077802051 and parameters: {'weight_class_0': 1.0303952479240999, 'weight_class_1': 8.773976983438127, 'weight_class_2': 6.176206770789116}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:29,897] Trial 739 finished with value: 0.9463762820541604 and parameters: {'weight_class_0': 0.1830601094869186, 'weight_class_1': 8.738853487721816, 'weight_class_2': 6.1689913107951675}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:29,905] Trial 741 finished with value: 0.9481025400778784 and parameters: {'weight_class_0': 1.0709715033469012, 'weight_class_1': 9.31072455384978, 'weight_class_2': 6.434615106217062}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:29,962] Trial 743 finished with value: 0.9483725252801126 and parameters: {'weight_class_0': 1.0155371611246804, 'weight_class_1': 9.34318010390919, 'weight_class_2': 6.381309100459673}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:29,968] Trial 742 finished with value: 0.9481452454309878 and parameters: {'weight_class_0': 1.0594403505983736, 'weight_class_1': 9.315050045886018, 'weight_class_2': 6.392166441889413}. Best is trial 330 with value: 0.9498700288669591.

[I 2026-07-05 15:04:30,037] Trial 744 finished with value: 0.9483284430789571 and parameters: {'weight_class_0': 1.022645799416209, 'weight_class_1': 9.236980219058825, 'weight_class_2': 6.420732344974596}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:30,047] Trial 746 finished with value: 0.948427403705613 and parameters: {'weight_class_0': 1.0685721093355793, 'weight_class_1': 9.221079994494929, 'weight_class_2': 6.885129979646893}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:30,049] Trial 745 finished with value: 0.9482691605403394 and parameters: {'weight_class_0': 1.046416939474365, 'weight_class_1': 9.188546100415978, 'weight_class_2': 6.45542763102201}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:30,052] Trial 747 finished with value: 0.9483056847559789 and parameters: {'weight_class_0': 1.0843440994743245, 'weight_class_1': 9.18682374220011, 'weight_class_2': 6.8777957396603355}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:30,067] Trial 748 finished with value: 0.9485611302152508 and parameters: {'weight_class_0': 1.044079588154815, 'weight_class_1': 9.328679756411885, 'weight_class_2': 6.853879699428561}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:30,132] Trial 751 finished with value: 0.9498004371601962 and parameters: {'weight_class_0': 0.5946158950192815, 'weight_class_1': 9.167880895242051, 'weight_class_2': 6.803225446031261}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:30,137] Trial 750 finished with value: 0.9486139941021668 and parameters: {'weight_class_0': 1.0076325394396553, 'weight_class_1': 9.354440135894986, 'weight_class_2': 6.644866642618766}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:30,149] Trial 749 finished with value: 0.9483256823487441 and parameters: {'weight_class_0': 1.0790361420952426, 'weight_class_1': 9.203267769109068, 'weight_class_2': 6.8486302317405}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:30,176] Trial 752 finished with value: 0.9498407024837867 and parameters: {'weight_class_0': 0.5968530760419064, 'weight_class_1': 9.21600890677116, 'weight_class_2': 6.593229334954923}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:30,183] Trial 753 finished with value: 0.949789432129004 and parameters: {'weight_class_0': 0.5708936480738248, 'weight_class_1': 9.183290309849937, 'weight_class_2': 6.684838734584983}. Best is trial 330 with value: 0.9498700288669591.

Best trial: 330. Best value: 0.94987:  76%|█████████████████████████████████████████████████████████████████████████████████████████████████████▍                               | 763/1000 [00:15<00:05, 44.22it/s]

[I 2026-07-05 15:04:30,228] Trial 754 finished with value: 0.9498173173749566 and parameters: {'weight_class_0': 0.5799829323860222, 'weight_class_1': 9.195149801960149, 'weight_class_2': 6.666822878881901}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:30,230] Trial 755 finished with value: 0.9497949383981393 and parameters: {'weight_class_0': 0.5763848359804139, 'weight_class_1': 9.163644608584192, 'weight_class_2': 6.831997207074601}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:30,264] Trial 756 finished with value: 0.9497763574426243 and parameters: {'weight_class_0': 0.5518136939684246, 'weight_class_1': 8.055319158467253, 'weight_class_2': 6.614251490478499}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:30,279] Trial 757 finished with value: 0.9497890074937542 and parameters: {'weight_class_0': 0.579571951314952, 'weight_class_1': 8.038596084510381, 'weight_class_2': 5.964371170826563}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:30,312] Trial 758 finished with value: 0.9497897154873335 and parameters: {'weight_class_0': 0.6159348180952754, 'weight_class_1': 8.067481715770443, 'weight_class_2': 6.616569705732144}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:30,357] Trial 759 finished with value: 0.9498071397792939 and parameters: {'weight_class_0': 0.5726861127363342, 'weight_class_1': 8.071545065793158, 'weight_class_2': 6.51304743503401}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:30,372] Trial 761 finished with value: 0.9497473473422854 and parameters: {'weight_class_0': 0.5629231055363468, 'weight_class_1': 7.976478945774453, 'weight_class_2': 6.62191358546346}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:30,378] Trial 760 finished with value: 0.9498199694728225 and parameters: {'weight_class_0': 0.5806759471469409, 'weight_class_1': 8.070672868785788, 'weight_class_2': 6.538820926082029}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:30,404] Trial 762 finished with value: 0.9498043184992166 and parameters: {'weight_class_0': 0.5985264178760465, 'weight_class_1': 8.028895212056181, 'weight_class_2': 6.646316488959408}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:30,426] Trial 763 finished with value: 0.9497870007296129 and parameters: {'weight_class_0': 0.5827853282476236, 'weight_class_1': 9.826560926818967, 'weight_class_2': 6.673712771399324}. Best is trial 330 with value: 0.9498700288669591.

Best trial: 330. Best value: 0.94987:  77%|██████████████████████████████████████████████████████████████████████████████████████████████████████▋                              | 772/1000 [00:15<00:05, 44.72it/s]

[I 2026-07-05 15:04:30,464] Trial 765 finished with value: 0.9468162542749838 and parameters: {'weight_class_0': 0.7408517687958349, 'weight_class_1': 9.895795119173515, 'weight_class_2': 3.2870738392215184}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:30,474] Trial 764 finished with value: 0.9495500104770752 and parameters: {'weight_class_0': 0.7299337368850898, 'weight_class_1': 7.983056018608238, 'weight_class_2': 6.594309854029795}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:30,513] Trial 766 finished with value: 0.9495857712789947 and parameters: {'weight_class_0': 0.7433420417248073, 'weight_class_1': 9.828995822156697, 'weight_class_2': 6.5929641439596915}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:30,531] Trial 769 finished with value: 0.9494892710390451 and parameters: {'weight_class_0': 0.7850292355125137, 'weight_class_1': 9.817461736935726, 'weight_class_2': 6.52676436173576}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:30,537] Trial 767 finished with value: 0.9495555727469583 and parameters: {'weight_class_0': 0.7553755946680705, 'weight_class_1': 9.719433744697199, 'weight_class_2': 6.593085760386289}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:30,563] Trial 768 finished with value: 0.9492390843425939 and parameters: {'weight_class_0': 0.8046096662128688, 'weight_class_1': 7.809540175812364, 'weight_class_2': 6.479662363339797}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:30,594] Trial 770 finished with value: 0.9493169027122056 and parameters: {'weight_class_0': 0.7980773852376177, 'weight_class_1': 8.49704115752524, 'weight_class_2': 6.461698437607131}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:30,599] Trial 771 finished with value: 0.9490846737886187 and parameters: {'weight_class_0': 0.8301204060821543, 'weight_class_1': 7.774064269897228, 'weight_class_2': 6.412519005114281}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:30,661] Trial 772 finished with value: 0.9496590167567502 and parameters: {'weight_class_0': 0.7806142580821132, 'weight_class_1': 9.882443459932693, 'weight_class_2': 7.473185692546194}. Best is trial 330 with value: 0.9498700288669591.

Best trial: 330. Best value: 0.94987:  78%|████████████████████████████████████████████████████████████████████████████████████████████████████████                             | 782/1000 [00:15<00:04, 44.89it/s]

[I 2026-07-05 15:04:30,668] Trial 773 finished with value: 0.9482541577614069 and parameters: {'weight_class_0': 0.3020125118945807, 'weight_class_1': 9.81778970833896, 'weight_class_2': 7.316629609606766}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:30,701] Trial 774 finished with value: 0.9483722038038547 and parameters: {'weight_class_0': 0.29313187259602924, 'weight_class_1': 8.47889248970538, 'weight_class_2': 7.407962746347113}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:30,725] Trial 775 finished with value: 0.9490788383508337 and parameters: {'weight_class_0': 0.32761462704051725, 'weight_class_1': 7.780146173726066, 'weight_class_2': 6.325446283560626}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:30,739] Trial 776 finished with value: 0.9480404667796747 and parameters: {'weight_class_0': 0.3633250158958823, 'weight_class_1': 2.503609864045234, 'weight_class_2': 6.388360834344208}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:30,749] Trial 777 finished with value: 0.9489322619960733 and parameters: {'weight_class_0': 0.32665245547706334, 'weight_class_1': 8.538638734865001, 'weight_class_2': 6.367097525173078}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:30,769] Trial 779 finished with value: 0.948613566786956 and parameters: {'weight_class_0': 0.33644169719936357, 'weight_class_1': 9.46235443165599, 'weight_class_2': 7.442146653979176}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:30,796] Trial 778 finished with value: 0.9493159353877741 and parameters: {'weight_class_0': 0.32805932233830526, 'weight_class_1': 8.55822967198131, 'weight_class_2': 4.867556952459128}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:30,809] Trial 780 finished with value: 0.9490317345616249 and parameters: {'weight_class_0': 0.3564794377030113, 'weight_class_1': 9.474029023158495, 'weight_class_2': 6.394725092251188}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:30,831] Trial 781 finished with value: 0.9494755360718733 and parameters: {'weight_class_0': 0.4147850165489477, 'weight_class_1': 9.449783997716594, 'weight_class_2': 5.875959676195604}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:30,850] Trial 782 finished with value: 0.9489884560412042 and parameters: {'weight_class_0': 0.3206289715236821, 'weight_class_1': 8.552414809993286, 'weight_class_2': 6.016026388272695}. Best is trial 330 with value: 0.9498700288669591.

[I 2026-07-05 15:04:30,881] Trial 783 finished with value: 0.9490941827330123 and parameters: {'weight_class_0': 0.35466782021427656, 'weight_class_1': 9.463374402804208, 'weight_class_2': 5.835950637446071}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:30,907] Trial 784 finished with value: 0.9490305868365881 and parameters: {'weight_class_0': 0.3189317784270703, 'weight_class_1': 8.53597786009861, 'weight_class_2': 5.84660217680663}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:30,938] Trial 785 finished with value: 0.9489371687678676 and parameters: {'weight_class_0': 0.33241649542124596, 'weight_class_1': 9.480329129352388, 'weight_class_2': 6.0335385955310095}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:30,973] Trial 786 finished with value: 0.9495309731567977 and parameters: {'weight_class_0': 0.4250955805836323, 'weight_class_1': 9.483598518962399, 'weight_class_2': 5.872400300582561}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:30,974] Trial 787 finished with value: 0.9495273175098672 and parameters: {'weight_class_0': 0.4277256460684112, 'weight_class_1': 9.455621578070323, 'weight_class_2': 6.00173923066107}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:31,002] Trial 788 finished with value: 0.9496856434581299 and parameters: {'weight_class_0': 0.4760046416184064, 'weight_class_1': 9.40197743452952, 'weight_class_2': 5.857981151293106}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:31,018] Trial 789 finished with value: 0.949619008405007 and parameters: {'weight_class_0': 0.4511379823377314, 'weight_class_1': 9.504173907611705, 'weight_class_2': 5.9982067096479605}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:31,068] Trial 791 finished with value: 0.9493329009997926 and parameters: {'weight_class_0': 0.47380534630405646, 'weight_class_1': 4.486583927310799, 'weight_class_2': 6.028869807364691}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:31,069] Trial 790 finished with value: 0.9497157638716563 and parameters: {'weight_class_0': 0.46739205123102534, 'weight_class_1': 8.935691174813963, 'weight_class_2': 5.8392464515339}. Best is trial 330 with value: 0.9498700288669591.

Best trial: 330. Best value: 0.94987:  80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▌                          | 801/1000 [00:16<00:04, 44.14it/s]

[I 2026-07-05 15:04:31,105] Trial 792 finished with value: 0.9497194093952487 and parameters: {'weight_class_0': 0.4977826553330382, 'weight_class_1': 8.869621584152128, 'weight_class_2': 5.830491006594513}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:31,107] Trial 793 finished with value: 0.948721568080343 and parameters: {'weight_class_0': 0.88323264449126, 'weight_class_1': 8.898145079040061, 'weight_class_2': 6.047918179749005}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:31,147] Trial 795 finished with value: 0.9462251588396974 and parameters: {'weight_class_0': 0.8881506984196832, 'weight_class_1': 4.198604265791377, 'weight_class_2': 6.073635616865188}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:31,154] Trial 794 finished with value: 0.9490724143377515 and parameters: {'weight_class_0': 0.8865825633266944, 'weight_class_1': 8.284506451265617, 'weight_class_2': 6.97108199084667}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:31,190] Trial 796 finished with value: 0.9490836432927447 and parameters: {'weight_class_0': 0.8858726400045791, 'weight_class_1': 8.929473544715094, 'weight_class_2': 6.928480244453129}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:31,192] Trial 797 finished with value: 0.9289850183774909 and parameters: {'weight_class_0': 0.8213090184182998, 'weight_class_1': 9.060770719912572, 'weight_class_2': 1.3762775649901577}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:31,235] Trial 798 finished with value: 0.9491023787531635 and parameters: {'weight_class_0': 0.8965132134199469, 'weight_class_1': 8.894020625296099, 'weight_class_2': 6.897017759415707}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:31,254] Trial 799 finished with value: 0.9490898658154262 and parameters: {'weight_class_0': 0.8856590957504475, 'weight_class_1': 8.899224936104979, 'weight_class_2': 6.954726907018618}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:31,279] Trial 800 finished with value: 0.9475126795309694 and parameters: {'weight_class_0': 1.2561395336342813, 'weight_class_1': 8.889745462724314, 'weight_class_2': 6.9288303590636895}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:31,303] Trial 801 finished with value: 0.9483203516868746 and parameters: {'weight_class_0': 0.8962931723547001, 'weight_class_1': 8.268777549919747, 'weight_class_2': 5.53249249191179}. Best is trial 330 with value: 0.9498700288669591.

Best trial: 330. Best value: 0.94987:  81%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▋                         | 810/1000 [00:16<00:04, 42.26it/s]

[I 2026-07-05 15:04:31,335] Trial 803 finished with value: 0.9103873006364381 and parameters: {'weight_class_0': 4.501844975228235, 'weight_class_1': 8.249753417759155, 'weight_class_2': 6.961037107647135}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:31,336] Trial 802 finished with value: 0.9495244570727932 and parameters: {'weight_class_0': 0.7800630819009365, 'weight_class_1': 8.2652126118543, 'weight_class_2': 6.987311680050245}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:31,366] Trial 804 finished with value: 0.9496568488314594 and parameters: {'weight_class_0': 0.7110972824925008, 'weight_class_1': 8.256950529490364, 'weight_class_2': 6.983054276341581}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:31,390] Trial 805 finished with value: 0.9490506324524608 and parameters: {'weight_class_0': 0.7369671081080176, 'weight_class_1': 8.211233159824069, 'weight_class_2': 5.5236255783897565}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:31,419] Trial 806 finished with value: 0.9492903104208268 and parameters: {'weight_class_0': 0.6898621453369828, 'weight_class_1': 8.278846059105291, 'weight_class_2': 5.512209413188606}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:31,454] Trial 807 finished with value: 0.9455270204291674 and parameters: {'weight_class_0': 1.2898615066068855, 'weight_class_1': 8.246067157032996, 'weight_class_2': 5.473445139708962}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:31,462] Trial 808 finished with value: 0.948825839530517 and parameters: {'weight_class_0': 0.6867465255240719, 'weight_class_1': 8.233744439193808, 'weight_class_2': 4.598730653315743}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:31,470] Trial 809 finished with value: 0.9468412353530824 and parameters: {'weight_class_0': 1.2634881976222503, 'weight_class_1': 8.279080526260122, 'weight_class_2': 6.290736881882025}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:31,497] Trial 810 finished with value: 0.9482782186689986 and parameters: {'weight_class_0': 1.2304533058929945, 'weight_class_1': 8.190368786872156, 'weight_class_2': 9.269914722136388}. Best is trial 330 with value: 0.9498700288669591.

Best trial: 330. Best value: 0.94987:  82%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                        | 819/1000 [00:16<00:04, 43.17it/s]

[I 2026-07-05 15:04:31,512] Trial 811 finished with value: 0.9496824319349194 and parameters: {'weight_class_0': 0.6490378242209748, 'weight_class_1': 8.263913629924115, 'weight_class_2': 6.299588397630424}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:31,553] Trial 812 finished with value: 0.9497594298698103 and parameters: {'weight_class_0': 0.6412009474449849, 'weight_class_1': 9.166412817752496, 'weight_class_2': 6.314406089745382}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:31,588] Trial 813 finished with value: 0.9496736762090271 and parameters: {'weight_class_0': 0.6493331513211555, 'weight_class_1': 7.7216364663805575, 'weight_class_2': 6.310463576572108}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:31,612] Trial 814 finished with value: 0.9497383216221557 and parameters: {'weight_class_0': 0.6105833541018703, 'weight_class_1': 7.8329979263267555, 'weight_class_2': 6.260179846916402}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:31,635] Trial 815 finished with value: 0.8844593965372147 and parameters: {'weight_class_0': 7.12836105358105, 'weight_class_1': 9.08364332149149, 'weight_class_2': 6.333981040660505}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:31,642] Trial 816 finished with value: 0.9497615532463347 and parameters: {'weight_class_0': 0.6360867754896932, 'weight_class_1': 9.129062998926797, 'weight_class_2': 6.276609079927984}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:31,684] Trial 817 finished with value: 0.9497605729713934 and parameters: {'weight_class_0': 0.6231807020705713, 'weight_class_1': 9.077068709734334, 'weight_class_2': 6.337528202278427}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:31,694] Trial 818 finished with value: 0.9497621791480423 and parameters: {'weight_class_0': 0.6372314061943549, 'weight_class_1': 9.12493150501146, 'weight_class_2': 6.284161821489019}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:31,717] Trial 819 finished with value: 0.94985556190719 and parameters: {'weight_class_0': 0.5838389762655488, 'weight_class_1': 9.08924931746494, 'weight_class_2': 6.321443638157284}. Best is trial 330 with value: 0.9498700288669591.

[I 2026-07-05 15:04:31,740] Trial 820 finished with value: 0.9498105123762849 and parameters: {'weight_class_0': 0.5459639021044668, 'weight_class_1': 9.107294141633878, 'weight_class_2': 6.266572357752377}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:31,777] Trial 821 finished with value: 0.9481137098381796 and parameters: {'weight_class_0': 0.226971103754474, 'weight_class_1': 7.019913440593681, 'weight_class_2': 6.270024541382209}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:31,806] Trial 822 finished with value: 0.9464953528175196 and parameters: {'weight_class_0': 0.1936532438323132, 'weight_class_1': 9.132988571887028, 'weight_class_2': 6.100428253035114}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:31,827] Trial 823 finished with value: 0.9474758660362853 and parameters: {'weight_class_0': 0.2158306186702088, 'weight_class_1': 8.51897031675378, 'weight_class_2': 6.114400998754793}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:31,846] Trial 824 finished with value: 0.9497707354375367 and parameters: {'weight_class_0': 0.4952108803792519, 'weight_class_1': 6.974674821449034, 'weight_class_2': 6.113393860718905}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:31,848] Trial 825 finished with value: 0.948095542345864 and parameters: {'weight_class_0': 0.2573802014509805, 'weight_class_1': 8.664108483542753, 'weight_class_2': 6.72006448359493}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:31,883] Trial 826 finished with value: 0.948051937760973 and parameters: {'weight_class_0': 0.24540369639146836, 'weight_class_1': 8.597628047643507, 'weight_class_2': 6.0700559882351826}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:31,951] Trial 829 finished with value: 0.946159571853146 and parameters: {'weight_class_0': 0.18513582464773043, 'weight_class_1': 9.298501516225219, 'weight_class_2': 6.00693766010114}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:31,967] Trial 828 finished with value: 0.9454512400075009 and parameters: {'weight_class_0': 0.202660035555366, 'weight_class_1': 7.051648996748864, 'weight_class_2': 0.8481585169637533}. Best is trial 330 with value: 0.9498700288669591.

[I 2026-07-05 15:04:31,985] Trial 827 finished with value: 0.9477025849924532 and parameters: {'weight_class_0': 0.23890857279128502, 'weight_class_1': 9.2992059713858, 'weight_class_2': 6.004203684312701}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:32,022] Trial 830 finished with value: 0.9472194861384557 and parameters: {'weight_class_0': 0.2191123142616681, 'weight_class_1': 9.33773568096683, 'weight_class_2': 6.101722831225922}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:32,025] Trial 831 finished with value: 0.9472273615583141 and parameters: {'weight_class_0': 0.2177358178083259, 'weight_class_1': 9.286182354341921, 'weight_class_2': 6.036201517617509}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:32,043] Trial 832 finished with value: 0.9467395994321627 and parameters: {'weight_class_0': 0.20356418262479714, 'weight_class_1': 9.368659849186765, 'weight_class_2': 6.06639652645148}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:32,063] Trial 833 finished with value: 0.9496318757159784 and parameters: {'weight_class_0': 0.45386410237708985, 'weight_class_1': 9.310878419335623, 'weight_class_2': 5.743006024935289}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:32,077] Trial 834 finished with value: 0.9494345677483184 and parameters: {'weight_class_0': 0.4069341878219286, 'weight_class_1': 9.647361509485451, 'weight_class_2': 5.764943769957063}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:32,111] Trial 836 finished with value: 0.9496649052479573 and parameters: {'weight_class_0': 0.4679527037376354, 'weight_class_1': 9.321426142863217, 'weight_class_2': 5.9012396942382965}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:32,112] Trial 835 finished with value: 0.9469771303797199 and parameters: {'weight_class_0': 0.20626452446557714, 'weight_class_1': 9.31029704971415, 'weight_class_2': 5.748540457993796}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:32,142] Trial 838 finished with value: 0.9423719664486407 and parameters: {'weight_class_0': 1.7391279716292063, 'weight_class_1': 9.330816320845774, 'weight_class_2': 5.838684020699195}. Best is trial 330 with value: 0.9498700288669591.

[I 2026-07-05 15:04:32,164] Trial 837 finished with value: 0.9495739878614167 and parameters: {'weight_class_0': 0.43466616249529555, 'weight_class_1': 9.299644521247924, 'weight_class_2': 5.723935584535878}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:32,208] Trial 839 finished with value: 0.9496361180511665 and parameters: {'weight_class_0': 0.4528781055953108, 'weight_class_1': 9.358078822655559, 'weight_class_2': 5.803010141680114}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:32,222] Trial 840 finished with value: 0.9481793324722735 and parameters: {'weight_class_0': 0.968669207420219, 'weight_class_1': 9.64027433995077, 'weight_class_2': 5.781340576212731}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:32,239] Trial 841 finished with value: 0.9497087495931792 and parameters: {'weight_class_0': 0.46150770167017674, 'weight_class_1': 8.818752321256483, 'weight_class_2': 5.788935689528789}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:32,272] Trial 842 finished with value: 0.87069046496318 and parameters: {'weight_class_0': 8.517892109370283, 'weight_class_1': 8.812079273654371, 'weight_class_2': 5.207574397774539}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:32,282] Trial 844 finished with value: 0.9480373185443289 and parameters: {'weight_class_0': 0.9136496938890837, 'weight_class_1': 8.806588309488937, 'weight_class_2': 5.134344466745487}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:32,287] Trial 843 finished with value: 0.9480523184377069 and parameters: {'weight_class_0': 0.9322493970238537, 'weight_class_1': 8.82777314093026, 'weight_class_2': 5.257718424422026}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:32,352] Trial 845 finished with value: 0.9486284226298339 and parameters: {'weight_class_0': 0.9708758498166306, 'weight_class_1': 8.753501925444999, 'weight_class_2': 6.544248200231318}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:32,364] Trial 846 finished with value: 0.9482590053013437 and parameters: {'weight_class_0': 1.0404494225837908, 'weight_class_1': 8.802221000658433, 'weight_class_2': 6.542251593277245}. Best is trial 330 with value: 0.9498700288669591.

[I 2026-07-05 15:04:32,395] Trial 847 finished with value: 0.9485726160547222 and parameters: {'weight_class_0': 0.987378871105731, 'weight_class_1': 8.831521650409547, 'weight_class_2': 6.4902280405116715}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:32,425] Trial 848 finished with value: 0.9484919556776851 and parameters: {'weight_class_0': 0.995919445118753, 'weight_class_1': 8.79261508836119, 'weight_class_2': 6.450294232728802}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:32,433] Trial 849 finished with value: 0.946865808254559 and parameters: {'weight_class_0': 0.9211860630420755, 'weight_class_1': 4.7830401198035295, 'weight_class_2': 6.419919152429787}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:32,449] Trial 850 finished with value: 0.9486634184171733 and parameters: {'weight_class_0': 0.968749586197641, 'weight_class_1': 8.87430023217154, 'weight_class_2': 6.52726909654758}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:32,498] Trial 851 finished with value: 0.949094792533221 and parameters: {'weight_class_0': 0.8546890366411547, 'weight_class_1': 8.732017439225412, 'weight_class_2': 6.516591430405049}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:32,511] Trial 852 finished with value: 0.6601227813111176 and parameters: {'weight_class_0': 0.0041715845274867824, 'weight_class_1': 8.688978103319833, 'weight_class_2': 6.376334255278798}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:32,520] Trial 853 finished with value: 0.9486000308323682 and parameters: {'weight_class_0': 0.723525045550081, 'weight_class_1': 4.735787130412778, 'weight_class_2': 6.5360727165507075}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:32,556] Trial 854 finished with value: 0.94957760516601 and parameters: {'weight_class_0': 0.7469770382206166, 'weight_class_1': 9.095129007858052, 'weight_class_2': 6.484088757086664}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:32,560] Trial 855 finished with value: 0.9496300033616003 and parameters: {'weight_class_0': 0.7015378517329743, 'weight_class_1': 9.01142786716841, 'weight_class_2': 6.430104345418898}. Best is trial 330 with value: 0.9498700288669591.

Best trial: 330. Best value: 0.94987:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                  | 864/1000 [00:17<00:03, 42.59it/s]

[I 2026-07-05 15:04:32,605] Trial 856 finished with value: 0.9495853553356436 and parameters: {'weight_class_0': 0.711428711733159, 'weight_class_1': 9.071245899014865, 'weight_class_2': 6.396666952136184}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:32,608] Trial 857 finished with value: 0.94983107019117 and parameters: {'weight_class_0': 0.5982586189271705, 'weight_class_1': 9.082011600031374, 'weight_class_2': 6.421352935312592}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:32,659] Trial 859 finished with value: 0.9496269086486523 and parameters: {'weight_class_0': 0.7029985483562573, 'weight_class_1': 9.045196820376258, 'weight_class_2': 6.384645053341014}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:32,679] Trial 858 finished with value: 0.9496319080468436 and parameters: {'weight_class_0': 0.7068129547697539, 'weight_class_1': 9.124357013928314, 'weight_class_2': 6.4207286179066}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:32,699] Trial 860 finished with value: 0.949746725899464 and parameters: {'weight_class_0': 0.6707929365516383, 'weight_class_1': 9.121596951873121, 'weight_class_2': 6.738515235219049}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:32,734] Trial 861 finished with value: 0.9491923619400519 and parameters: {'weight_class_0': 0.7045795236510628, 'weight_class_1': 9.101042659372512, 'weight_class_2': 5.474047976880068}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:32,757] Trial 862 finished with value: 0.9496940933816562 and parameters: {'weight_class_0': 0.646915141490575, 'weight_class_1': 9.083783154390808, 'weight_class_2': 6.160540803441491}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:32,766] Trial 863 finished with value: 0.9494621151974235 and parameters: {'weight_class_0': 0.6591948753947049, 'weight_class_1': 9.082414740727687, 'weight_class_2': 5.441089042801067}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:32,776] Trial 864 finished with value: 0.9496735150117043 and parameters: {'weight_class_0': 0.6410987804692847, 'weight_class_1': 9.14254623883804, 'weight_class_2': 6.132583031367531}. Best is trial 330 with value: 0.9498700288669591.

Best trial: 330. Best value: 0.94987:  87%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                 | 873/1000 [00:17<00:03, 41.05it/s]

[I 2026-07-05 15:04:32,812] Trial 865 finished with value: 0.949811498665094 and parameters: {'weight_class_0': 0.5474563868399702, 'weight_class_1': 9.098132640918745, 'weight_class_2': 6.14762135067217}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:32,831] Trial 866 finished with value: 0.949779042033062 and parameters: {'weight_class_0': 0.5512210831306887, 'weight_class_1': 9.096281244926328, 'weight_class_2': 5.485076335463536}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:32,875] Trial 867 finished with value: 0.949801291876523 and parameters: {'weight_class_0': 0.5467815141531518, 'weight_class_1': 9.100166029644688, 'weight_class_2': 6.684310303451262}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:32,901] Trial 868 finished with value: 0.9496880781523321 and parameters: {'weight_class_0': 0.5253165191749287, 'weight_class_1': 9.678728552530714, 'weight_class_2': 6.7843327646867975}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:32,903] Trial 869 finished with value: 0.9497484834430597 and parameters: {'weight_class_0': 0.49921068274276076, 'weight_class_1': 8.554514926860893, 'weight_class_2': 6.185220298770168}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:32,910] Trial 870 finished with value: 0.949671065180269 and parameters: {'weight_class_0': 0.5259010401488895, 'weight_class_1': 9.542091090327519, 'weight_class_2': 6.6821242714878055}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:32,970] Trial 871 finished with value: 0.9497606683786181 and parameters: {'weight_class_0': 0.5238707098686848, 'weight_class_1': 7.637470513200105, 'weight_class_2': 6.158121159630451}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:32,998] Trial 872 finished with value: 0.9444990724149848 and parameters: {'weight_class_0': 0.4824191353230906, 'weight_class_1': 1.709332066372435, 'weight_class_2': 6.686136937056002}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:33,004] Trial 873 finished with value: 0.9496804604316113 and parameters: {'weight_class_0': 0.5029893588672586, 'weight_class_1': 9.627673339750793, 'weight_class_2': 6.656152120107243}. Best is trial 330 with value: 0.9498700288669591.

[I 2026-07-05 15:04:33,041] Trial 874 finished with value: 0.9497642665982139 and parameters: {'weight_class_0': 0.50943203336701, 'weight_class_1': 9.661885049610772, 'weight_class_2': 6.170972074116645}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:33,047] Trial 875 finished with value: 0.9496365382352442 and parameters: {'weight_class_0': 0.4535131207616555, 'weight_class_1': 8.518535104191205, 'weight_class_2': 6.748398952393724}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:33,072] Trial 876 finished with value: 0.9494726301454354 and parameters: {'weight_class_0': 0.4362222242902228, 'weight_class_1': 9.684682206403624, 'weight_class_2': 6.688899183153334}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:33,145] Trial 877 finished with value: 0.9494271059229155 and parameters: {'weight_class_0': 0.4233864117620285, 'weight_class_1': 9.663426537595049, 'weight_class_2': 6.637761665973783}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:33,156] Trial 878 finished with value: 0.9448844955348131 and parameters: {'weight_class_0': 0.46944739901416493, 'weight_class_1': 1.7353049891428034, 'weight_class_2': 6.816582567888407}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:33,167] Trial 879 finished with value: 0.9461617736375653 and parameters: {'weight_class_0': 0.3746057876612144, 'weight_class_1': 1.748697502283982, 'weight_class_2': 6.757078987726716}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:33,191] Trial 880 finished with value: 0.9488742344528847 and parameters: {'weight_class_0': 0.32452056643956134, 'weight_class_1': 7.696918619063604, 'weight_class_2': 6.776937588858068}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:33,210] Trial 881 finished with value: 0.9493503824001225 and parameters: {'weight_class_0': 0.3669110586444057, 'weight_class_1': 7.558725853066196, 'weight_class_2': 6.705544823323407}. Best is trial 330 with value: 0.9498700288669591.

[I 2026-07-05 15:04:33,253] Trial 883 finished with value: 0.9475085511301331 and parameters: {'weight_class_0': 1.1680316838327864, 'weight_class_1': 8.541246957521826, 'weight_class_2': 6.304024252411384}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:33,257] Trial 882 finished with value: 0.9491019456089326 and parameters: {'weight_class_0': 0.3403328038974902, 'weight_class_1': 8.499391514041056, 'weight_class_2': 6.287803324209345}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:33,289] Trial 884 finished with value: 0.9472153583307313 and parameters: {'weight_class_0': 1.1764625769189652, 'weight_class_1': 8.552107735257163, 'weight_class_2': 5.966308863934773}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:33,319] Trial 886 finished with value: 0.9467554367038865 and parameters: {'weight_class_0': 1.2086751505165827, 'weight_class_1': 7.865872029846286, 'weight_class_2': 5.953557589208048}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:33,334] Trial 885 finished with value: 0.947194071653958 and parameters: {'weight_class_0': 1.1534577183479973, 'weight_class_1': 7.556151714752407, 'weight_class_2': 6.250423954755627}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:33,364] Trial 887 finished with value: 0.9470369310892003 and parameters: {'weight_class_0': 1.1653908627563205, 'weight_class_1': 7.586663787302208, 'weight_class_2': 5.965097874994042}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:33,371] Trial 888 finished with value: 0.9471568929604826 and parameters: {'weight_class_0': 1.1420603574621813, 'weight_class_1': 7.653290891568435, 'weight_class_2': 5.95422910121195}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:33,409] Trial 889 finished with value: 0.9474270758592853 and parameters: {'weight_class_0': 1.1440668506385099, 'weight_class_1': 8.507352671787656, 'weight_class_2': 5.943060948418048}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:33,416] Trial 890 finished with value: 0.8677409718986498 and parameters: {'weight_class_0': 9.169150166194594, 'weight_class_1': 7.9454915827979615, 'weight_class_2': 6.272476585306377}. Best is trial 330 with value: 0.9498700288669591.

Best trial: 330. Best value: 0.94987:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋             | 900/1000 [00:18<00:02, 41.24it/s]

[I 2026-07-05 15:04:33,456] Trial 891 finished with value: 0.9472368777906341 and parameters: {'weight_class_0': 1.1603523071299122, 'weight_class_1': 7.88737895147349, 'weight_class_2': 6.265356115404774}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:33,499] Trial 893 finished with value: 0.9489301826359822 and parameters: {'weight_class_0': 0.8170084881515922, 'weight_class_1': 7.9746632035103335, 'weight_class_2': 5.9893607745401125}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:33,512] Trial 892 finished with value: 0.7975705749879846 and parameters: {'weight_class_0': 0.02181226034400907, 'weight_class_1': 7.881829604444921, 'weight_class_2': 5.911546539247425}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:33,532] Trial 894 finished with value: 0.8044410803328432 and parameters: {'weight_class_0': 0.023140557852874832, 'weight_class_1': 8.01117583651599, 'weight_class_2': 5.9991894498930485}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:33,549] Trial 895 finished with value: 0.6997535826845854 and parameters: {'weight_class_0': 0.010828789268940264, 'weight_class_1': 7.9327235581391, 'weight_class_2': 6.25844806747336}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:33,570] Trial 896 finished with value: 0.9488305577783135 and parameters: {'weight_class_0': 0.8367274205152755, 'weight_class_1': 7.847134075956512, 'weight_class_2': 6.0123802940971105}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:33,595] Trial 897 finished with value: 0.9486601622679975 and parameters: {'weight_class_0': 0.8511383603277198, 'weight_class_1': 7.950439137859257, 'weight_class_2': 5.6556943806988205}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:33,609] Trial 898 finished with value: 0.9486855454003308 and parameters: {'weight_class_0': 0.8346349928787582, 'weight_class_1': 7.919881388327723, 'weight_class_2': 5.672373119820818}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:33,645] Trial 899 finished with value: 0.9495672492773367 and parameters: {'weight_class_0': 0.798522007489412, 'weight_class_1': 9.486574451299012, 'weight_class_2': 7.2102405766145115}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:33,675] Trial 900 finished with value: 0.6821356841887826 and parameters: {'weight_class_0': 0.009061916682385873, 'weight_class_1': 9.451313021345554, 'weight_class_2': 5.706693292232893}. Best is trial 330 with value: 0.9498700288669591.

Best trial: 330. Best value: 0.94987:  91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████            | 910/1000 [00:18<00:02, 42.60it/s]

[I 2026-07-05 15:04:33,716] Trial 901 finished with value: 0.9486905631818271 and parameters: {'weight_class_0': 0.8491085130134136, 'weight_class_1': 9.452003745323143, 'weight_class_2': 5.7463379385109725}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:33,720] Trial 902 finished with value: 0.9487356019726141 and parameters: {'weight_class_0': 0.8312031703957239, 'weight_class_1': 8.850510103726878, 'weight_class_2': 5.653121476698429}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:33,748] Trial 904 finished with value: 0.9431130781917992 and parameters: {'weight_class_0': 0.8256916078398278, 'weight_class_1': 9.438764765395529, 'weight_class_2': 2.5648984792617897}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:33,757] Trial 903 finished with value: 0.9495503874125696 and parameters: {'weight_class_0': 0.8163297043423441, 'weight_class_1': 8.909644362436874, 'weight_class_2': 7.183457205347226}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:33,790] Trial 905 finished with value: 0.948704510222664 and parameters: {'weight_class_0': 0.8464035703301156, 'weight_class_1': 9.451763926532644, 'weight_class_2': 5.624706455430179}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:33,813] Trial 906 finished with value: 0.8751274470186877 and parameters: {'weight_class_0': 8.01057529214765, 'weight_class_1': 8.891744912708022, 'weight_class_2': 5.6390691221163705}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:33,850] Trial 908 finished with value: 0.8802005395781308 and parameters: {'weight_class_0': 7.919484343561836, 'weight_class_1': 9.461660551922353, 'weight_class_2': 6.35984100061918}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:33,851] Trial 907 finished with value: 0.947494719326754 and parameters: {'weight_class_0': 0.1914916109459613, 'weight_class_1': 9.490248178565073, 'weight_class_2': 2.1727769514779944}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:33,871] Trial 909 finished with value: 0.9466852769754897 and parameters: {'weight_class_0': 0.20719436104911165, 'weight_class_1': 9.49505706738336, 'weight_class_2': 6.45682560163003}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:33,885] Trial 910 finished with value: 0.9485189889654629 and parameters: {'weight_class_0': 0.29707851682517034, 'weight_class_1': 8.91554328451338, 'weight_class_2': 6.422137218329886}. Best is trial 330 with value: 0.9498700288669591.

[I 2026-07-05 15:04:33,922] Trial 911 finished with value: 0.9480901385590994 and parameters: {'weight_class_0': 0.25696887000074914, 'weight_class_1': 8.885360058029798, 'weight_class_2': 6.365424734664747}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:33,932] Trial 912 finished with value: 0.9485722574465454 and parameters: {'weight_class_0': 0.3018639712038854, 'weight_class_1': 8.883404664579972, 'weight_class_2': 6.444362557828322}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:33,982] Trial 913 finished with value: 0.947372871806952 and parameters: {'weight_class_0': 0.21981317473267403, 'weight_class_1': 8.68939646645099, 'weight_class_2': 6.484452838238868}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:33,984] Trial 914 finished with value: 0.9430729389298529 and parameters: {'weight_class_0': 0.2358076369010877, 'weight_class_1': 0.8299838441748433, 'weight_class_2': 6.382373212557517}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:34,021] Trial 915 finished with value: 0.9479850310432681 and parameters: {'weight_class_0': 0.29631178174563466, 'weight_class_1': 8.918722074074006, 'weight_class_2': 8.67336243045187}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:34,053] Trial 916 finished with value: 0.9476160297532119 and parameters: {'weight_class_0': 0.23002944156384852, 'weight_class_1': 8.678715754841893, 'weight_class_2': 6.470911766020535}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:34,071] Trial 917 finished with value: 0.9474836676526978 and parameters: {'weight_class_0': 0.2229159094009956, 'weight_class_1': 8.639430342372163, 'weight_class_2': 6.438884220158804}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:34,109] Trial 918 finished with value: 0.8947554223741259 and parameters: {'weight_class_0': 5.810042350880132, 'weight_class_1': 8.67039926728821, 'weight_class_2': 6.4385618565397795}. Best is trial 330 with value: 0.9498700288669591.

[I 2026-07-05 15:04:34,119] Trial 919 finished with value: 0.9479598751010876 and parameters: {'weight_class_0': 0.22497668145542227, 'weight_class_1': 8.651215789248806, 'weight_class_2': 4.896861342538193}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:34,129] Trial 920 finished with value: 0.949738624075653 and parameters: {'weight_class_0': 0.6224875494571164, 'weight_class_1': 8.618300250803333, 'weight_class_2': 6.114218378421083}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:34,149] Trial 921 finished with value: 0.8902074299369399 and parameters: {'weight_class_0': 6.11997808891885, 'weight_class_1': 8.665291634429396, 'weight_class_2': 6.086499133871682}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:34,164] Trial 922 finished with value: 0.9498357438950524 and parameters: {'weight_class_0': 0.5550668472620015, 'weight_class_1': 8.426135753549088, 'weight_class_2': 6.113616998033822}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:34,191] Trial 923 finished with value: 0.9490629224171653 and parameters: {'weight_class_0': 0.6462652364075657, 'weight_class_1': 8.452486641291102, 'weight_class_2': 4.766794789963173}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:34,196] Trial 924 finished with value: 0.9497623588314665 and parameters: {'weight_class_0': 0.6225444750207579, 'weight_class_1': 8.648215819060987, 'weight_class_2': 6.124945543271664}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:34,271] Trial 926 finished with value: 0.9497132529710554 and parameters: {'weight_class_0': 0.6271943823382062, 'weight_class_1': 8.642911484209616, 'weight_class_2': 6.14355374614234}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:34,275] Trial 925 finished with value: 0.9491883679953222 and parameters: {'weight_class_0': 0.6430376612561464, 'weight_class_1': 8.621999259425523, 'weight_class_2': 4.896156594019927}. Best is trial 330 with value: 0.9498700288669591.

Best trial: 330. Best value: 0.94987:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎        | 935/1000 [00:19<00:01, 39.85it/s]

[I 2026-07-05 15:04:34,290] Trial 927 finished with value: 0.949737402649967 and parameters: {'weight_class_0': 0.6246915381090231, 'weight_class_1': 8.42207542840573, 'weight_class_2': 6.133553848574415}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:34,308] Trial 928 finished with value: 0.9496518289115131 and parameters: {'weight_class_0': 0.6436919946185609, 'weight_class_1': 8.403295020943148, 'weight_class_2': 6.13427760053898}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:34,360] Trial 930 finished with value: 0.9496544922557669 and parameters: {'weight_class_0': 0.643403999837237, 'weight_class_1': 8.40270957692633, 'weight_class_2': 6.117676919092365}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:34,365] Trial 929 finished with value: 0.9354801185005369 and parameters: {'weight_class_0': 2.322003480637855, 'weight_class_1': 8.379991632676981, 'weight_class_2': 6.144834870390079}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:34,395] Trial 931 finished with value: 0.9371378047996474 and parameters: {'weight_class_0': 2.259208140483426, 'weight_class_1': 9.233485877859186, 'weight_class_2': 6.149104840293024}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:34,424] Trial 932 finished with value: 0.9497751862711826 and parameters: {'weight_class_0': 0.49786445222539233, 'weight_class_1': 8.418596446096767, 'weight_class_2': 6.140583814791902}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:34,452] Trial 933 finished with value: 0.9497461736906919 and parameters: {'weight_class_0': 0.49112285278516243, 'weight_class_1': 9.194617595742573, 'weight_class_2': 5.902948055214844}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:34,481] Trial 934 finished with value: 0.9497188246731594 and parameters: {'weight_class_0': 0.48596924096502503, 'weight_class_1': 8.405683011292858, 'weight_class_2': 6.118783003913764}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:34,504] Trial 935 finished with value: 0.949785245350065 and parameters: {'weight_class_0': 0.5040962243140901, 'weight_class_1': 8.409551575603047, 'weight_class_2': 5.849484863112142}. Best is trial 330 with value: 0.9498700288669591.

[I 2026-07-05 15:04:34,522] Trial 936 finished with value: 0.949732696314543 and parameters: {'weight_class_0': 0.48699943974326665, 'weight_class_1': 8.443653831227568, 'weight_class_2': 5.874537828231714}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:34,540] Trial 937 finished with value: 0.9496271025161462 and parameters: {'weight_class_0': 0.43295014313482416, 'weight_class_1': 9.167728351288476, 'weight_class_2': 5.814964791609516}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:34,568] Trial 938 finished with value: 0.9496193824158515 and parameters: {'weight_class_0': 0.43183743331596225, 'weight_class_1': 9.266360234665436, 'weight_class_2': 5.860593374369738}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:34,606] Trial 940 finished with value: 0.9495792633087389 and parameters: {'weight_class_0': 0.4379374041995743, 'weight_class_1': 9.276931669898394, 'weight_class_2': 5.782886706175898}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:34,623] Trial 939 finished with value: 0.9480446485583446 and parameters: {'weight_class_0': 1.0124377069896515, 'weight_class_1': 9.210037536397701, 'weight_class_2': 5.84389140049595}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:34,665] Trial 942 finished with value: 0.9481766152705743 and parameters: {'weight_class_0': 0.9822861673399796, 'weight_class_1': 9.15031663110356, 'weight_class_2': 5.888972950103489}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:34,666] Trial 941 finished with value: 0.9496074893659537 and parameters: {'weight_class_0': 0.4275109510593058, 'weight_class_1': 9.21121302466498, 'weight_class_2': 5.8715833692319555}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:34,701] Trial 943 finished with value: 0.9479627948587916 and parameters: {'weight_class_0': 0.9772996470755513, 'weight_class_1': 9.006631918500714, 'weight_class_2': 5.361975153519299}. Best is trial 330 with value: 0.9498700288669591.

Best trial: 330. Best value: 0.94987:  95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋      | 953/1000 [00:19<00:01, 41.35it/s]

[I 2026-07-05 15:04:34,750] Trial 944 finished with value: 0.9483392389664523 and parameters: {'weight_class_0': 0.939983600809354, 'weight_class_1': 9.191800834231547, 'weight_class_2': 5.830526976668364}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:34,763] Trial 945 finished with value: 0.9480318139739975 and parameters: {'weight_class_0': 0.971649936720127, 'weight_class_1': 9.188092126572156, 'weight_class_2': 5.431294669325515}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:34,764] Trial 946 finished with value: 0.9480187308963952 and parameters: {'weight_class_0': 0.9680410356970183, 'weight_class_1': 9.281678896072613, 'weight_class_2': 5.35064462947578}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:34,793] Trial 947 finished with value: 0.9480447190669793 and parameters: {'weight_class_0': 0.9549951014786163, 'weight_class_1': 8.994720730361962, 'weight_class_2': 5.394763810748977}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:34,829] Trial 948 finished with value: 0.9478224281843174 and parameters: {'weight_class_0': 1.0079636478001428, 'weight_class_1': 8.915161009751412, 'weight_class_2': 5.457058214460384}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:34,852] Trial 950 finished with value: 0.9479855390107322 and parameters: {'weight_class_0': 0.9761394769398115, 'weight_class_1': 8.90821794006407, 'weight_class_2': 5.401259757285833}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:34,878] Trial 949 finished with value: 0.9480380380926862 and parameters: {'weight_class_0': 0.955432427132858, 'weight_class_1': 9.026301245427282, 'weight_class_2': 5.454071929286762}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:34,911] Trial 951 finished with value: 0.9491411003876785 and parameters: {'weight_class_0': 0.7984830243073143, 'weight_class_1': 8.973605370689171, 'weight_class_2': 6.2565205670199155}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:34,937] Trial 952 finished with value: 0.9489137697418665 and parameters: {'weight_class_0': 0.75769678672475, 'weight_class_1': 8.862025798951281, 'weight_class_2': 5.4763421191536015}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:34,953] Trial 954 finished with value: 0.9494480093033072 and parameters: {'weight_class_0': 0.7608629980785548, 'weight_class_1': 8.92334507738689, 'weight_class_2': 6.280343814183333}. Best is trial 330 with value: 0.9498700288669591.

Best trial: 330. Best value: 0.94987:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊     | 961/1000 [00:20<00:00, 39.07it/s]

[I 2026-07-05 15:04:34,956] Trial 953 finished with value: 0.9491232819332801 and parameters: {'weight_class_0': 0.8159987219966685, 'weight_class_1': 8.970225702272389, 'weight_class_2': 6.223180497992306}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:35,019] Trial 955 finished with value: 0.9493705883909446 and parameters: {'weight_class_0': 0.7591905379284849, 'weight_class_1': 7.2697222517352165, 'weight_class_2': 6.281403511556989}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:35,066] Trial 956 finished with value: 0.9494685424459414 and parameters: {'weight_class_0': 0.757174105334504, 'weight_class_1': 8.87541852587474, 'weight_class_2': 6.2836799444962015}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:35,068] Trial 957 finished with value: 0.9027305380556344 and parameters: {'weight_class_0': 0.7408777371110913, 'weight_class_1': 7.316614028135418, 'weight_class_2': 0.49466776563443293}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:35,087] Trial 958 finished with value: 0.8647718285714175 and parameters: {'weight_class_0': 9.917499358463203, 'weight_class_1': 8.0965417606299, 'weight_class_2': 6.265797754497789}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:35,124] Trial 959 finished with value: 0.949631355270031 and parameters: {'weight_class_0': 0.6972201137955456, 'weight_class_1': 9.77840874171558, 'weight_class_2': 6.257359595455086}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:35,147] Trial 961 finished with value: 0.9495355640439135 and parameters: {'weight_class_0': 0.729043525517889, 'weight_class_1': 9.834531394571751, 'weight_class_2': 6.277404235927355}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:35,154] Trial 960 finished with value: 0.9437383534961903 and parameters: {'weight_class_0': 1.524116206789266, 'weight_class_1': 7.239588777245367, 'weight_class_2': 6.2981091068145005}. Best is trial 330 with value: 0.9498700288669591.

[I 2026-07-05 15:04:35,194] Trial 962 finished with value: 0.9495719342970919 and parameters: {'weight_class_0': 0.691311830271885, 'weight_class_1': 7.353374143395569, 'weight_class_2': 6.279976753417722}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:35,207] Trial 963 finished with value: 0.9433913007727387 and parameters: {'weight_class_0': 1.6284165158273565, 'weight_class_1': 8.11756822361429, 'weight_class_2': 6.295876477901485}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:35,235] Trial 965 finished with value: 0.6683324817058862 and parameters: {'weight_class_0': 0.007029663919830509, 'weight_class_1': 9.755790498783, 'weight_class_2': 6.291473122759}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:35,249] Trial 966 finished with value: 0.9447594737928631 and parameters: {'weight_class_0': 1.371825346123864, 'weight_class_1': 7.202221135268966, 'weight_class_2': 6.014414538569533}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:35,259] Trial 964 finished with value: 0.9491671297021732 and parameters: {'weight_class_0': 0.3336630827189253, 'weight_class_1': 8.166786062316335, 'weight_class_2': 6.020203569669667}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:35,273] Trial 967 finished with value: 0.9491070717505591 and parameters: {'weight_class_0': 0.3280110480357516, 'weight_class_1': 8.122576784387046, 'weight_class_2': 6.057689676484741}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:35,321] Trial 968 finished with value: 0.664969803491267 and parameters: {'weight_class_0': 0.006029636283490403, 'weight_class_1': 9.799199020031427, 'weight_class_2': 6.012385774897276}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:35,364] Trial 969 finished with value: 0.9488070402389205 and parameters: {'weight_class_0': 0.32280107500021593, 'weight_class_1': 9.661087333481486, 'weight_class_2': 6.020789928790598}. Best is trial 330 with value: 0.9498700288669591.

[I 2026-07-05 15:04:35,390] Trial 970 finished with value: 0.9495297173056834 and parameters: {'weight_class_0': 0.38622946893422627, 'weight_class_1': 8.182395315790743, 'weight_class_2': 5.9969106736789834}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:35,412] Trial 972 finished with value: 0.9488406747063535 and parameters: {'weight_class_0': 0.3410616524339806, 'weight_class_1': 9.629786185826331, 'weight_class_2': 6.605335544570468}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:35,414] Trial 971 finished with value: 0.9494981788929518 and parameters: {'weight_class_0': 0.3673934590520931, 'weight_class_1': 6.780015814786509, 'weight_class_2': 6.0176451674293565}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:35,444] Trial 973 finished with value: 0.9491131715775047 and parameters: {'weight_class_0': 0.3626788734874331, 'weight_class_1': 9.54420713663942, 'weight_class_2': 5.981493029135231}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:35,499] Trial 975 finished with value: 0.9490388623299557 and parameters: {'weight_class_0': 0.34669849928137014, 'weight_class_1': 8.717686694281108, 'weight_class_2': 6.5756935350690195}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:35,508] Trial 974 finished with value: 0.94922428906986 and parameters: {'weight_class_0': 0.33899270414942473, 'weight_class_1': 8.130969817550666, 'weight_class_2': 5.994873823208664}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:35,512] Trial 976 finished with value: 0.949291359806741 and parameters: {'weight_class_0': 0.3985721175618303, 'weight_class_1': 9.365784899228174, 'weight_class_2': 6.564488416307689}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:35,540] Trial 977 finished with value: 0.9493936830098461 and parameters: {'weight_class_0': 0.41003272561856113, 'weight_class_1': 9.380949546927543, 'weight_class_2': 6.602664784320811}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:35,573] Trial 978 finished with value: 0.9491417448710361 and parameters: {'weight_class_0': 0.37620551014208214, 'weight_class_1': 9.399754752934417, 'weight_class_2': 6.550228958075725}. Best is trial 330 with value: 0.9498700288669591.

Best trial: 330. Best value: 0.94987:  99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍ | 988/1000 [00:20<00:00, 41.78it/s]

[I 2026-07-05 15:04:35,604] Trial 980 finished with value: 0.9497118647250854 and parameters: {'weight_class_0': 0.49321437245491234, 'weight_class_1': 8.746445560056655, 'weight_class_2': 6.612587038912376}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:35,608] Trial 979 finished with value: 0.9497135271080751 and parameters: {'weight_class_0': 0.4779733449237096, 'weight_class_1': 9.347453241516831, 'weight_class_2': 5.6415676662646845}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:35,644] Trial 981 finished with value: 0.9476069259385841 and parameters: {'weight_class_0': 0.5954658830141337, 'weight_class_1': 3.1235234680757937, 'weight_class_2': 6.560159284831501}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:35,665] Trial 982 finished with value: 0.9498016855660034 and parameters: {'weight_class_0': 0.5802485510738203, 'weight_class_1': 9.371620978611976, 'weight_class_2': 6.584623029720483}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:35,683] Trial 983 finished with value: 0.8942432378370141 and parameters: {'weight_class_0': 5.427664779714374, 'weight_class_1': 8.675515773653773, 'weight_class_2': 5.6149362784842225}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:35,731] Trial 984 finished with value: 0.9496615353492776 and parameters: {'weight_class_0': 0.600190564602402, 'weight_class_1': 9.37097459934108, 'weight_class_2': 5.67315945184914}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:35,748] Trial 986 finished with value: 0.9498088895894723 and parameters: {'weight_class_0': 0.5416790815170115, 'weight_class_1': 8.73880487817753, 'weight_class_2': 5.678490104463913}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:35,749] Trial 985 finished with value: 0.9497033871708807 and parameters: {'weight_class_0': 0.5808353067248466, 'weight_class_1': 9.370658416378273, 'weight_class_2': 5.653215137590278}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:35,779] Trial 987 finished with value: 0.949650634465948 and parameters: {'weight_class_0': 0.5941453821460303, 'weight_class_1': 7.748854673213021, 'weight_class_2': 5.60626540579814}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:35,781] Trial 988 finished with value: 0.9497138640231739 and parameters: {'weight_class_0': 0.5790973690068666, 'weight_class_1': 7.681934669892158, 'weight_class_2': 5.725934591125716}. Best is trial 330 with value: 0.9498700288669591.

Best trial: 330. Best value: 0.94987: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:20<00:00, 47.82it/s]

[I 2026-07-05 15:04:35,865] Trial 989 finished with value: 0.9496442747681032 and parameters: {'weight_class_0': 0.6079234011102213, 'weight_class_1': 7.7507057883761945, 'weight_class_2': 5.7296691927118735}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:35,867] Trial 990 finished with value: 0.949688535768539 and parameters: {'weight_class_0': 0.5894837303180845, 'weight_class_1': 8.517315882706425, 'weight_class_2': 5.652187637631107}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:35,890] Trial 991 finished with value: 0.9441303514203542 and parameters: {'weight_class_0': 0.13846818767363056, 'weight_class_1': 8.76031151560454, 'weight_class_2': 5.677886932677937}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:35,928] Trial 992 finished with value: 0.9492873340836984 and parameters: {'weight_class_0': 0.6261300964997237, 'weight_class_1': 5.30610660236197, 'weight_class_2': 5.638525317074819}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:35,934] Trial 993 finished with value: 0.9457125696882002 and parameters: {'weight_class_0': 0.1679974727047206, 'weight_class_1': 9.049657263321203, 'weight_class_2': 5.661540705714875}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:35,953] Trial 994 finished with value: 0.9496137388557241 and parameters: {'weight_class_0': 0.6355362391021976, 'weight_class_1': 9.059582035164615, 'weight_class_2': 5.737569590208813}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:35,961] Trial 995 finished with value: 0.9468127570097721 and parameters: {'weight_class_0': 0.1978220087266518, 'weight_class_1': 9.059319361478211, 'weight_class_2': 5.73304256981328}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:35,968] Trial 996 finished with value: 0.9466102869200755 and parameters: {'weight_class_0': 0.16699536846104945, 'weight_class_1': 7.778500759799691, 'weight_class_2': 5.146426579019965}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:35,987] Trial 997 finished with value: 0.9461595795658176 and parameters: {'weight_class_0': 0.18175570200826868, 'weight_class_1': 9.036562169178527, 'weight_class_2': 6.121892645743057}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:35,994] Trial 998 finished with value: 0.9479412749760677 and parameters: {'weight_class_0': 0.1642616746345268, 'weight_class_1': 3.907103513871475, 'weight_class_2': 5.170169262549628}. Best is trial 330 with value: 0.9498700288669591.
[I 2026-07-05 15:04:36,005] Trial 999 finished with value: 0.9413621208801706 and parameters: {'weight_class_0': 0.11396725071910357, 'weight_class_1': 8.460978105086546, 'weight_class_2': 6.453518245895744}. Best is trial 330 with value: 0.9498700288669591.

Best trial score:
0.9498700288669591

Best params:
{'weight_class_0': 0.5778174468346758, 'weight_class_1': 9.450528047426932, 'weight_class_2': 6.261528171660667}

In [9]:
weights = np.array([study.best_params['weight_class_0'], study.best_params['weight_class_1'], study.best_params['weight_class_2']])
weighted_probas = X_test.loc[:, cols_use].to_numpy() * weights

pred = np.argmax(weighted_probas, axis=1)

In [10]:
sub_labels = label_encoder.inverse_transform(pred)

# Submission

In [11]:
submission = pd.read_csv('../data/submission/sample_submission.csv')
submission['health_condition'] = sub_labels

submission.to_csv('../data/submission/submission_from_5.1.1_lightgbm_submission.csv', index=False)

In [12]:
submission.head()

       id health_condition
0  690088        unhealthy
1  690089        unhealthy
2  690090          at-risk
3  690091          at-risk
4  690092        unhealthy