# Imports

In [1]:
import optuna
import pickle

import numpy as np
import pandas as pd

from tqdm import tqdm

from sklearn.metrics import balanced_accuracy_score
from sklearn.model_selection import StratifiedKFold, cross_val_predict

/home/junior/Documentos/GitHub/kaggle-competition-predicting-student-health/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Utils

In [2]:
def load_pickle(file_path):
    with open(file_path, 'rb') as file:
        return pickle.load(file)

# Loading Datasets

In [3]:
X_train = pd.read_parquet('../data/processed/X_train_stacking_layer_one.parquet')
y_train = pd.read_parquet('../data/interim/y_train.parquet')

X_test = pd.read_parquet('../data/processed/X_test_stacking_layer_one.parquet')

In [4]:
X_train.head()

     lgbm_0    lgbm_1    lgbm_2     xgb_0     xgb_1     xgb_2
0  0.004922  0.001773  0.993304  0.004134  0.002593  0.993273
1  0.997228  0.000463  0.002309  0.995591  0.000405  0.004004
2  0.002369  0.000604  0.997026  0.001958  0.000503  0.997538
3  0.004656  0.003362  0.991982  0.002466  0.002391  0.995142
4  0.995353  0.000016  0.004632  0.994178  0.000003  0.005819

In [5]:
X_test.head()

     lgbm_0    lgbm_1    lgbm_2     xgb_0     xgb_1     xgb_2
0  0.012452  0.003199  0.984349  0.011048  0.004491  0.984461
1  0.472116  0.002331  0.525553  0.499186  0.001896  0.498918
2  0.998690  0.001012  0.000298  0.997826  0.001594  0.000579
3  0.980854  0.000018  0.019128  0.987434  0.000009  0.012557
4  0.006765  0.001847  0.991388  0.006876  0.001972  0.991152

# Machine Learning

In [6]:
label_encoder = load_pickle('../artifacts/label_encoder.pkl')

In [7]:
cols_use = ['lgbm_0', 'lgbm_1', 'lgbm_2']

In [8]:
def objective(trial, X, y):

    w0 = trial.suggest_float('weight_class_0', 0.0, 10.0, log=False)
    w1 = trial.suggest_float('weight_class_1', 0.0, 10.0, log=False)
    w2 = trial.suggest_float('weight_class_2', 0.0, 10.0, log=False)
    weights = np.array([w0, w1, w2])

    proba = X.loc[:, cols_use].to_numpy()
    
    weighted_probas = proba * weights
    pred = np.argmax(weighted_probas, axis=1)
    
    score = balanced_accuracy_score(y, pred)

    return score


study = optuna.create_study(
    direction="maximize", 
    sampler=optuna.samplers.TPESampler(seed=42), 
    pruner=optuna.pruners.MedianPruner(n_warmup_steps=2)
)

study.optimize(
    lambda trial: objective(trial, X_train, y_train.health_condition), 
    n_trials=1000, 
    n_jobs=-1, 
    show_progress_bar=True
)

print("\nBest trial score:")
print(study.best_trial.value)

print("\nBest params:")
print(study.best_trial.params)

[I 2026-07-05 15:03:12,753] A new study created in memory with name: no-name-10d19b54-52d8-41f2-96d4-0fecd001b340
Best trial: 3. Best value: 0.944814:   1%|█▍                                                                                                                                     | 11/1000 [00:00<00:31, 31.20it/s]

[I 2026-07-05 15:03:12,923] Trial 9 finished with value: 0.9378633900057229 and parameters: {'weight_class_0': 0.30702977718320756, 'weight_class_1': 0.6933869563074491, 'weight_class_2': 5.125333506862581}. Best is trial 9 with value: 0.9378633900057229.
[I 2026-07-05 15:03:12,928] Trial 5 finished with value: 0.8433900855586592 and parameters: {'weight_class_0': 2.5233907004976674, 'weight_class_1': 0.3736195578831414, 'weight_class_2': 2.3286421882156247}. Best is trial 9 with value: 0.9378633900057229.
[I 2026-07-05 15:03:12,941] Trial 7 finished with value: 0.8355775924344732 and parameters: {'weight_class_0': 9.094137661097395, 'weight_class_1': 3.4816009989986494, 'weight_class_2': 0.8060038630659616}. Best is trial 9 with value: 0.9378633900057229.
[I 2026-07-05 15:03:12,942] Trial 0 finished with value: 0.8977311578968941 and parameters: {'weight_class_0': 5.822720498237296, 'weight_class_1': 7.165158413308951, 'weight_class_2': 8.24689409830422}. Best is trial 9 with value: 0.9378633900057229.
[I 2026-07-05 15:03:12,943] Trial 10 finished with value: 0.9311718517473917 and parameters: {'weight_class_0': 0.8864961502756752, 'weight_class_1': 1.551292416045228, 'weight_class_2': 5.17419579919976}. Best is trial 9 with value: 0.9378633900057229.
[I 2026-07-05 15:03:12,953] Trial 4 finished with value: 0.8565446082689485 and parameters: {'weight_class_0': 7.423061701706505, 'weight_class_1': 5.361638781629676, 'weight_class_2': 2.895040913334409}. Best is trial 9 with value: 0.9378633900057229.
[I 2026-07-05 15:03:12,955] Trial 11 finished with value: 0.9428487474010021 and parameters: {'weight_class_0': 0.7784667457843153, 'weight_class_1': 2.5850352698889023, 'weight_class_2': 4.844221213181552}. Best is trial 11 with value: 0.9428487474010021.
[I 2026-07-05 15:03:12,956] Trial 2 finished with value: 0.8655804492147118 and parameters: {'weight_class_0': 7.9725732133713665, 'weight_class_1': 5.894368530248254, 'weight_class_2': 5.885325616793089}. Best is trial 11 with value: 0.9428487474010021.
[I 2026-07-05 15:03:12,957] Trial 1 finished with value: 0.9097520940925521 and parameters: {'weight_class_0': 1.983884188957964, 'weight_class_1': 2.3830923706654437, 'weight_class_2': 4.372273366598247}. Best is trial 11 with value: 0.9428487474010021.
[I 2026-07-05 15:03:12,958] Trial 8 finished with value: 0.8823223802069675 and parameters: {'weight_class_0': 5.061754856224288, 'weight_class_1': 8.035998125124024, 'weight_class_2': 3.1578931443783445}. Best is trial 11 with value: 0.9428487474010021.
[I 2026-07-05 15:03:12,969] Trial 6 finished with value: 0.9234805874868502 and parameters: {'weight_class_0': 0.4060983863086798, 'weight_class_1': 0.495282437628215, 'weight_class_2': 6.432751966336923}. Best is trial 11 with value: 0.9428487474010021.
[I 2026-07-05 15:03:12,983] Trial 3 finished with value: 0.9448142829901585 and parameters: {'weight_class_0': 0.14784093133312304, 'weight_class_1': 6.914808179491235, 'weight_class_2': 8.555586724081635}. Best is trial 3 with value: 0.9448142829901585.

[I 2026-07-05 15:03:13,093] Trial 12 finished with value: 0.9225897479471769 and parameters: {'weight_class_0': 4.360737476174032, 'weight_class_1': 9.158154524477787, 'weight_class_2': 9.34557340983936}. Best is trial 3 with value: 0.9448142829901585.
[I 2026-07-05 15:03:13,098] Trial 13 finished with value: 0.9060997873112244 and parameters: {'weight_class_0': 4.012823652685961, 'weight_class_1': 4.0778213094312115, 'weight_class_2': 9.250176777669491}. Best is trial 3 with value: 0.9448142829901585.
[I 2026-07-05 15:03:13,124] Trial 14 finished with value: 0.9134439977284027 and parameters: {'weight_class_0': 2.8692085640490665, 'weight_class_1': 3.372292518041746, 'weight_class_2': 7.728976207825054}. Best is trial 3 with value: 0.9448142829901585.
[I 2026-07-05 15:03:13,135] Trial 16 finished with value: 0.9384293053874986 and parameters: {'weight_class_0': 2.967894432381838, 'weight_class_1': 9.965713454255347, 'weight_class_2': 9.783855764280446}. Best is trial 3 with value: 0.9448142829901585.
[I 2026-07-05 15:03:13,144] Trial 15 finished with value: 0.9316288484278124 and parameters: {'weight_class_0': 3.3691294253663493, 'weight_class_1': 9.10789508196681, 'weight_class_2': 8.862521155676147}. Best is trial 3 with value: 0.9448142829901585.
[I 2026-07-05 15:03:13,162] Trial 18 finished with value: 0.9186602751121539 and parameters: {'weight_class_0': 3.031619119644096, 'weight_class_1': 3.9002713427576685, 'weight_class_2': 9.553996389537517}. Best is trial 3 with value: 0.9448142829901585.
[I 2026-07-05 15:03:13,168] Trial 17 finished with value: 0.9333196515499821 and parameters: {'weight_class_0': 3.37177290190172, 'weight_class_1': 9.708691059796825, 'weight_class_2': 9.220392954444213}. Best is trial 3 with value: 0.9448142829901585.
[I 2026-07-05 15:03:13,197] Trial 19 finished with value: 0.9380686199967941 and parameters: {'weight_class_0': 2.937478803414498, 'weight_class_1': 9.751772696764533, 'weight_class_2': 9.500713360825513}. Best is trial 3 with value: 0.9448142829901585.
[I 2026-07-05 15:03:13,221] Trial 20 finished with value: 0.9365172157130793 and parameters: {'weight_class_0': 3.150278086871589, 'weight_class_1': 9.746047304232865, 'weight_class_2': 9.70003689831128}. Best is trial 3 with value: 0.9448142829901585.
[I 2026-07-05 15:03:13,253] Trial 21 finished with value: 0.9423168627943038 and parameters: {'weight_class_0': 2.03220137319441, 'weight_class_1': 9.53862783718111, 'weight_class_2': 7.4449117166737535}. Best is trial 3 with value: 0.9448142829901585.
[I 2026-07-05 15:03:13,254] Trial 22 finished with value: 0.938856099365788 and parameters: {'weight_class_0': 2.479945242942617, 'weight_class_1': 9.826140169005905, 'weight_class_2': 7.52584835004553}. Best is trial 3 with value: 0.9448142829901585.
[I 2026-07-05 15:03:13,278] Trial 23 finished with value: 0.9417283794384788 and parameters: {'weight_class_0': 1.5865060746370037, 'weight_class_1': 5.473556075896544, 'weight_class_2': 7.116752023094579}. Best is trial 3 with value: 0.9448142829901585.

Best trial: 37. Best value: 0.948704:   4%|████▋                                                                                                                                 | 35/1000 [00:00<00:19, 49.17it/s]

[I 2026-07-05 15:03:13,298] Trial 24 finished with value: 0.9426726388726272 and parameters: {'weight_class_0': 1.505891414167728, 'weight_class_1': 5.43031946724064, 'weight_class_2': 7.189308900020879}. Best is trial 3 with value: 0.9448142829901585.
[I 2026-07-05 15:03:13,328] Trial 25 finished with value: 0.9450440155441119 and parameters: {'weight_class_0': 1.3576811884301294, 'weight_class_1': 6.144563213372406, 'weight_class_2': 7.085021898362447}. Best is trial 25 with value: 0.9450440155441119.
[I 2026-07-05 15:03:13,346] Trial 26 finished with value: 0.9407781916751796 and parameters: {'weight_class_0': 1.672130707644831, 'weight_class_1': 5.4669510543666435, 'weight_class_2': 7.1793837860603755}. Best is trial 25 with value: 0.9450440155441119.
[I 2026-07-05 15:03:13,350] Trial 27 finished with value: 0.9418513006491461 and parameters: {'weight_class_0': 1.499438073169074, 'weight_class_1': 5.152263994162983, 'weight_class_2': 6.826993338365206}. Best is trial 25 with value: 0.9450440155441119.
[I 2026-07-05 15:03:13,368] Trial 28 finished with value: 0.9461637892023141 and parameters: {'weight_class_0': 1.393210514915327, 'weight_class_1': 7.680932435362561, 'weight_class_2': 7.062801086458765}. Best is trial 28 with value: 0.9461637892023141.
[I 2026-07-05 15:03:13,402] Trial 30 finished with value: 0.9451263919275315 and parameters: {'weight_class_0': 1.4361014033253534, 'weight_class_1': 7.04757777759366, 'weight_class_2': 6.88920082334181}. Best is trial 28 with value: 0.9461637892023141.
[I 2026-07-05 15:03:13,406] Trial 29 finished with value: 0.9453804309423764 and parameters: {'weight_class_0': 1.4663957918769606, 'weight_class_1': 7.177986551231061, 'weight_class_2': 7.279642645231764}. Best is trial 28 with value: 0.9461637892023141.
[I 2026-07-05 15:03:13,447] Trial 32 finished with value: 0.9461494246221193 and parameters: {'weight_class_0': 1.3315794798567022, 'weight_class_1': 7.217899163220308, 'weight_class_2': 6.7991869350329655}. Best is trial 28 with value: 0.9461637892023141.
[I 2026-07-05 15:03:13,458] Trial 31 finished with value: 0.9461491557099057 and parameters: {'weight_class_0': 1.3272318004744832, 'weight_class_1': 7.370012651122872, 'weight_class_2': 6.690960154270857}. Best is trial 28 with value: 0.9461637892023141.
[I 2026-07-05 15:03:13,467] Trial 33 finished with value: 0.9415484407983666 and parameters: {'weight_class_0': 1.2710955014664818, 'weight_class_1': 6.44612692004043, 'weight_class_2': 4.112353319833763}. Best is trial 28 with value: 0.9461637892023141.
[I 2026-07-05 15:03:13,484] Trial 34 finished with value: 0.9355558660746762 and parameters: {'weight_class_0': 0.06950079159852843, 'weight_class_1': 6.775512244948647, 'weight_class_2': 4.294474365970107}. Best is trial 28 with value: 0.9461637892023141.
[I 2026-07-05 15:03:13,505] Trial 35 finished with value: 0.9456281720404659 and parameters: {'weight_class_0': 0.16290531746418802, 'weight_class_1': 7.007959180857231, 'weight_class_2': 8.440398059524096}. Best is trial 28 with value: 0.9461637892023141.

[I 2026-07-05 15:03:13,524] Trial 36 finished with value: 0.9176371310404384 and parameters: {'weight_class_0': 0.06071532561337886, 'weight_class_1': 6.913750100171538, 'weight_class_2': 8.423269055326832}. Best is trial 28 with value: 0.9461637892023141.
[I 2026-07-05 15:03:13,558] Trial 37 finished with value: 0.9487036908033436 and parameters: {'weight_class_0': 0.8504195128200469, 'weight_class_1': 7.290271651571249, 'weight_class_2': 6.094216125661241}. Best is trial 37 with value: 0.9487036908033436.
[I 2026-07-05 15:03:13,561] Trial 38 finished with value: 0.9483987864390692 and parameters: {'weight_class_0': 0.8933866377350679, 'weight_class_1': 7.306450255401185, 'weight_class_2': 5.881326918165566}. Best is trial 37 with value: 0.9487036908033436.
[I 2026-07-05 15:03:13,583] Trial 39 finished with value: 0.9493787787649935 and parameters: {'weight_class_0': 0.7137281330784881, 'weight_class_1': 7.221742340028705, 'weight_class_2': 6.041601494300362}. Best is trial 39 with value: 0.9493787787649935.
[I 2026-07-05 15:03:13,596] Trial 40 finished with value: 0.9482976815724324 and parameters: {'weight_class_0': 0.9711461443236934, 'weight_class_1': 8.062464043970005, 'weight_class_2': 6.225655719446129}. Best is trial 39 with value: 0.9493787787649935.
[I 2026-07-05 15:03:13,624] Trial 41 finished with value: 0.9381386106352622 and parameters: {'weight_class_0': 2.1074973607601013, 'weight_class_1': 8.113858975731569, 'weight_class_2': 6.220734871583415}. Best is trial 39 with value: 0.9493787787649935.
[I 2026-07-05 15:03:13,633] Trial 42 finished with value: 0.9348983701396821 and parameters: {'weight_class_0': 2.274532068244684, 'weight_class_1': 8.00528699965639, 'weight_class_2': 5.937135995795757}. Best is trial 39 with value: 0.9493787787649935.
[I 2026-07-05 15:03:13,684] Trial 43 finished with value: 0.9407842283457057 and parameters: {'weight_class_0': 2.1139355266078814, 'weight_class_1': 7.783308495276353, 'weight_class_2': 8.01777282742595}. Best is trial 39 with value: 0.9493787787649935.
[I 2026-07-05 15:03:13,691] Trial 44 finished with value: 0.9373527882208496 and parameters: {'weight_class_0': 2.157781617619879, 'weight_class_1': 7.921662742883128, 'weight_class_2': 6.223714105001828}. Best is trial 39 with value: 0.9493787787649935.
[I 2026-07-05 15:03:13,694] Trial 45 finished with value: 0.9357141212564616 and parameters: {'weight_class_0': 2.1883479320547234, 'weight_class_1': 8.02813966878378, 'weight_class_2': 5.80967031980812}. Best is trial 39 with value: 0.9493787787649935.
[I 2026-07-05 15:03:13,704] Trial 46 finished with value: 0.9374448379452479 and parameters: {'weight_class_0': 2.0765925264183593, 'weight_class_1': 8.401270365350792, 'weight_class_2': 5.7432085894166125}. Best is trial 39 with value: 0.9493787787649935.

[I 2026-07-05 15:03:13,731] Trial 47 finished with value: 0.8841789173821469 and parameters: {'weight_class_0': 6.53776878194248, 'weight_class_1': 8.097251021254733, 'weight_class_2': 5.915296536153199}. Best is trial 39 with value: 0.9493787787649935.
[I 2026-07-05 15:03:13,746] Trial 48 finished with value: 0.949169519484696 and parameters: {'weight_class_0': 0.742401477351964, 'weight_class_1': 8.216767250914396, 'weight_class_2': 5.7573651960135}. Best is trial 39 with value: 0.9493787787649935.
[I 2026-07-05 15:03:13,788] Trial 49 finished with value: 0.9497732983809507 and parameters: {'weight_class_0': 0.5592637085395094, 'weight_class_1': 8.419413903983276, 'weight_class_2': 5.750934032314543}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:13,807] Trial 50 finished with value: 0.9491907004127471 and parameters: {'weight_class_0': 0.7109192580001717, 'weight_class_1': 8.480949643620548, 'weight_class_2': 5.473220635587403}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:13,819] Trial 51 finished with value: 0.9488484026370786 and parameters: {'weight_class_0': 0.8528636806037194, 'weight_class_1': 8.719306579286432, 'weight_class_2': 6.0409438136147156}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:13,838] Trial 52 finished with value: 0.9496017539607773 and parameters: {'weight_class_0': 0.6244527982113617, 'weight_class_1': 8.630939774514374, 'weight_class_2': 5.5203846086288495}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:13,853] Trial 53 finished with value: 0.9488168864497583 and parameters: {'weight_class_0': 0.7526553354318625, 'weight_class_1': 8.645441729225269, 'weight_class_2': 5.238791800976493}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:13,871] Trial 54 finished with value: 0.9487100556024525 and parameters: {'weight_class_0': 0.7706939445425552, 'weight_class_1': 8.624676793071481, 'weight_class_2': 5.147010345596591}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:13,901] Trial 55 finished with value: 0.9486583012473763 and parameters: {'weight_class_0': 0.7744533144182538, 'weight_class_1': 8.735980396127289, 'weight_class_2': 5.113787243372541}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:13,909] Trial 57 finished with value: 0.9490651091654071 and parameters: {'weight_class_0': 0.6613067038801563, 'weight_class_1': 8.702605163084659, 'weight_class_2': 4.877548496944322}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:13,912] Trial 56 finished with value: 0.9492245917979701 and parameters: {'weight_class_0': 0.6435376342577339, 'weight_class_1': 8.657701531400116, 'weight_class_2': 5.113550370256863}. Best is trial 49 with value: 0.9497732983809507.

[I 2026-07-05 15:03:13,964] Trial 58 finished with value: 0.9481733701337336 and parameters: {'weight_class_0': 0.6551532798641672, 'weight_class_1': 8.63786692478604, 'weight_class_2': 3.6801879796310892}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:13,970] Trial 59 finished with value: 0.9497553147843268 and parameters: {'weight_class_0': 0.5105601663122358, 'weight_class_1': 8.735625255052046, 'weight_class_2': 5.297248525096707}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:13,981] Trial 60 finished with value: 0.9487649497949976 and parameters: {'weight_class_0': 0.7709514308360559, 'weight_class_1': 8.71855132774663, 'weight_class_2': 5.289144770420428}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,007] Trial 61 finished with value: 0.9495591588693338 and parameters: {'weight_class_0': 0.4102839005481298, 'weight_class_1': 8.856580494493228, 'weight_class_2': 3.662799287919431}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,021] Trial 62 finished with value: 0.9492023557761313 and parameters: {'weight_class_0': 0.5168140424950723, 'weight_class_1': 8.998031724869808, 'weight_class_2': 3.9413859148418573}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,045] Trial 63 finished with value: 0.9494716980350276 and parameters: {'weight_class_0': 0.3456359571069319, 'weight_class_1': 9.291612568020653, 'weight_class_2': 3.672863604487712}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,056] Trial 64 finished with value: 0.9492637868697941 and parameters: {'weight_class_0': 0.48161473976657065, 'weight_class_1': 9.447701639079215, 'weight_class_2': 3.7375055488220394}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,075] Trial 65 finished with value: 0.8593667269590245 and parameters: {'weight_class_0': 9.32468325833814, 'weight_class_1': 7.591253163410728, 'weight_class_2': 3.7376987674781836}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,114] Trial 66 finished with value: 0.9495715828456466 and parameters: {'weight_class_0': 0.4137670869175028, 'weight_class_1': 9.122124640292084, 'weight_class_2': 3.84324454827879}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,134] Trial 67 finished with value: 0.9494408439638774 and parameters: {'weight_class_0': 0.36442369720071527, 'weight_class_1': 9.23360962485432, 'weight_class_2': 4.539445590274778}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,149] Trial 68 finished with value: 0.9493614094921581 and parameters: {'weight_class_0': 0.34099918106779403, 'weight_class_1': 9.164407861042971, 'weight_class_2': 4.68700080337295}. Best is trial 49 with value: 0.9497732983809507.

Best trial: 49. Best value: 0.949773:   8%|██████████▋                                                                                                                           | 80/1000 [00:01<00:16, 54.29it/s]

[I 2026-07-05 15:03:14,162] Trial 69 finished with value: 0.9486557213207759 and parameters: {'weight_class_0': 0.4069490960909788, 'weight_class_1': 9.259999742070315, 'weight_class_2': 2.7034472123158455}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,184] Trial 70 finished with value: 0.9489541774987386 and parameters: {'weight_class_0': 0.3531700566968808, 'weight_class_1': 9.003217978725793, 'weight_class_2': 2.75733918707574}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,200] Trial 72 finished with value: 0.9483881338173991 and parameters: {'weight_class_0': 0.23863772804278763, 'weight_class_1': 9.380210310750721, 'weight_class_2': 2.180957241243068}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,208] Trial 71 finished with value: 0.8596868887185898 and parameters: {'weight_class_0': 9.611710068414373, 'weight_class_1': 9.302899475515563, 'weight_class_2': 1.8624041300323861}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,248] Trial 73 finished with value: 0.9486253260019136 and parameters: {'weight_class_0': 0.30593141047954275, 'weight_class_1': 9.20088611108297, 'weight_class_2': 2.341179015001523}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,260] Trial 74 finished with value: 0.8593194686274027 and parameters: {'weight_class_0': 9.949056650244763, 'weight_class_1': 9.407092231958533, 'weight_class_2': 2.0526458884251086}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,267] Trial 75 finished with value: 0.9483999899897109 and parameters: {'weight_class_0': 0.3548341447376417, 'weight_class_1': 9.18844706550757, 'weight_class_2': 2.333990086058223}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,282] Trial 76 finished with value: 0.9491272707377111 and parameters: {'weight_class_0': 0.32844148543816853, 'weight_class_1': 9.223907627561756, 'weight_class_2': 2.8428560419246454}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,315] Trial 77 finished with value: 0.9408807352961478 and parameters: {'weight_class_0': 1.1576971707871462, 'weight_class_1': 9.458339540244328, 'weight_class_2': 3.211284128977174}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,316] Trial 78 finished with value: 0.9404424150946737 and parameters: {'weight_class_0': 1.1204747485119522, 'weight_class_1': 9.498333069716496, 'weight_class_2': 3.02838771767777}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,348] Trial 80 finished with value: 0.9413608047007457 and parameters: {'weight_class_0': 1.164914955149812, 'weight_class_1': 8.356543969951725, 'weight_class_2': 3.359447085818532}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,349] Trial 79 finished with value: 0.9378055344323295 and parameters: {'weight_class_0': 1.761604094618824, 'weight_class_1': 9.615126442919138, 'weight_class_2': 4.483858060724048}. Best is trial 49 with value: 0.9497732983809507.

Best trial: 49. Best value: 0.949773:   9%|████████████▏                                                                                                                         | 91/1000 [00:01<00:16, 54.03it/s]

[I 2026-07-05 15:03:14,363] Trial 81 finished with value: 0.9414418614168351 and parameters: {'weight_class_0': 1.1782271464452527, 'weight_class_1': 9.62516154299909, 'weight_class_2': 3.369331928249928}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,399] Trial 82 finished with value: 0.9409172157492209 and parameters: {'weight_class_0': 1.1247913889722043, 'weight_class_1': 9.874636438333722, 'weight_class_2': 3.0949576632211677}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,425] Trial 83 finished with value: 0.9380926386921988 and parameters: {'weight_class_0': 1.7793023218595256, 'weight_class_1': 9.850560706667569, 'weight_class_2': 4.608819189100457}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,442] Trial 84 finished with value: 0.9379730788321347 and parameters: {'weight_class_0': 1.7693873994197356, 'weight_class_1': 9.926862207949993, 'weight_class_2': 4.5263180601768696}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,456] Trial 85 finished with value: 0.9059897799511258 and parameters: {'weight_class_0': 0.05628001914914332, 'weight_class_1': 9.936787917638457, 'weight_class_2': 4.574267402767543}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,458] Trial 86 finished with value: 0.9458749314533921 and parameters: {'weight_class_0': 1.099152836640122, 'weight_class_1': 9.87960395132377, 'weight_class_2': 4.431198960367838}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,492] Trial 87 finished with value: 0.9121761872581734 and parameters: {'weight_class_0': 0.0600219549415999, 'weight_class_1': 9.808294507329517, 'weight_class_2': 4.386520703518448}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,507] Trial 88 finished with value: 0.9384459175463853 and parameters: {'weight_class_0': 1.7666190659090983, 'weight_class_1': 9.98391546540744, 'weight_class_2': 4.619853305430647}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,523] Trial 89 finished with value: 0.9349398692001348 and parameters: {'weight_class_0': 0.08765837821059352, 'weight_class_1': 8.975483009385126, 'weight_class_2': 4.454838229699729}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,533] Trial 90 finished with value: 0.9287878985813564 and parameters: {'weight_class_0': 0.0741730048543583, 'weight_class_1': 8.932801992594001, 'weight_class_2': 4.543498676488874}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,586] Trial 91 finished with value: 0.940942148360706 and parameters: {'weight_class_0': 0.09647697037469857, 'weight_class_1': 7.614246447085028, 'weight_class_2': 4.572629464646199}. Best is trial 49 with value: 0.9497732983809507.

Best trial: 49. Best value: 0.949773:  10%|█████████████▌                                                                                                                       | 102/1000 [00:02<00:16, 54.15it/s]

[I 2026-07-05 15:03:14,592] Trial 92 finished with value: 0.7790183490412034 and parameters: {'weight_class_0': 0.01933740793228489, 'weight_class_1': 8.952934562835372, 'weight_class_2': 4.627468867793094}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,610] Trial 93 finished with value: 0.9478927362044676 and parameters: {'weight_class_0': 0.22547324527440668, 'weight_class_1': 8.964556663349715, 'weight_class_2': 4.765513791174405}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,618] Trial 94 finished with value: 0.6607993842621727 and parameters: {'weight_class_0': 0.0046172113576843365, 'weight_class_1': 8.946054502055922, 'weight_class_2': 6.525326147880021}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,635] Trial 95 finished with value: 0.9497305298540034 and parameters: {'weight_class_0': 0.4723717787558056, 'weight_class_1': 8.936009071978223, 'weight_class_2': 5.4783850768315245}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,655] Trial 96 finished with value: 0.8975768451687962 and parameters: {'weight_class_0': 0.046011905191021385, 'weight_class_1': 8.939868920765559, 'weight_class_2': 4.120338978685878}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,679] Trial 98 finished with value: 0.8860730161864012 and parameters: {'weight_class_0': 0.4913583412328681, 'weight_class_1': 0.09762499556191173, 'weight_class_2': 4.069322231949918}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,699] Trial 97 finished with value: 0.9497095232330345 and parameters: {'weight_class_0': 0.46971774851157644, 'weight_class_1': 7.558121616007023, 'weight_class_2': 6.528668293866407}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,703] Trial 99 finished with value: 0.9492705388951648 and parameters: {'weight_class_0': 0.510061986294693, 'weight_class_1': 7.632728618961571, 'weight_class_2': 3.9604931215657033}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,731] Trial 100 finished with value: 0.9488650811867608 and parameters: {'weight_class_0': 0.5741609218185384, 'weight_class_1': 8.33094514712057, 'weight_class_2': 3.896286762998212}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,753] Trial 102 finished with value: 0.9495734480167638 and parameters: {'weight_class_0': 0.4808694004576338, 'weight_class_1': 8.389797352721288, 'weight_class_2': 4.165585945535772}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,760] Trial 101 finished with value: 0.949302352131181 and parameters: {'weight_class_0': 0.5035396322567967, 'weight_class_1': 8.286821223121823, 'weight_class_2': 3.9714622632258707}. Best is trial 49 with value: 0.9497732983809507.

[I 2026-07-05 15:03:14,810] Trial 103 finished with value: 0.9497313815916227 and parameters: {'weight_class_0': 0.569256737577367, 'weight_class_1': 8.336182766187065, 'weight_class_2': 5.5825685089659896}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,818] Trial 104 finished with value: 0.8590007163167854 and parameters: {'weight_class_0': 8.179032869363486, 'weight_class_1': 4.78744053895412, 'weight_class_2': 5.593810852431419}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,828] Trial 105 finished with value: 0.9496988150319128 and parameters: {'weight_class_0': 0.5805488962010974, 'weight_class_1': 8.452206104277598, 'weight_class_2': 5.506216819434631}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,855] Trial 106 finished with value: 0.947683015380418 and parameters: {'weight_class_0': 1.0258079184126638, 'weight_class_1': 8.362065261909112, 'weight_class_2': 5.509750331500195}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,859] Trial 107 finished with value: 0.9481620558156644 and parameters: {'weight_class_0': 0.9925900289377037, 'weight_class_1': 8.281769377139769, 'weight_class_2': 6.175315277711396}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,881] Trial 108 finished with value: 0.9479446772457071 and parameters: {'weight_class_0': 0.9944137658081299, 'weight_class_1': 8.448978000368223, 'weight_class_2': 5.607880982339302}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,903] Trial 109 finished with value: 0.9479097001785219 and parameters: {'weight_class_0': 0.9460468483474153, 'weight_class_1': 7.784140576530059, 'weight_class_2': 5.522006045520272}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,914] Trial 111 finished with value: 0.947702332090981 and parameters: {'weight_class_0': 1.0061622733030768, 'weight_class_1': 7.808996887174243, 'weight_class_2': 5.533712405138262}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,919] Trial 110 finished with value: 0.9474707835307608 and parameters: {'weight_class_0': 0.9621386135487119, 'weight_class_1': 6.463273269275315, 'weight_class_2': 5.59287362638681}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,955] Trial 112 finished with value: 0.9484526618961114 and parameters: {'weight_class_0': 0.9900746955409154, 'weight_class_1': 8.475396731272633, 'weight_class_2': 6.421263298040204}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,985] Trial 113 finished with value: 0.9480947853875875 and parameters: {'weight_class_0': 0.9093548013153031, 'weight_class_1': 7.804432515443485, 'weight_class_2': 5.414065798797477}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:14,994] Trial 114 finished with value: 0.9476999655280586 and parameters: {'weight_class_0': 0.9683538463628436, 'weight_class_1': 8.500634950291909, 'weight_class_2': 4.999081458449694}. Best is trial 49 with value: 0.9497732983809507.

Best trial: 49. Best value: 0.949773:  12%|████████████████▋                                                                                                                    | 125/1000 [00:02<00:16, 52.99it/s]

[I 2026-07-05 15:03:15,022] Trial 115 finished with value: 0.9418093165515664 and parameters: {'weight_class_0': 1.5186331223548748, 'weight_class_1': 7.918418781125228, 'weight_class_2': 4.941986451701027}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:15,039] Trial 116 finished with value: 0.9432304730366653 and parameters: {'weight_class_0': 1.4053844053099376, 'weight_class_1': 8.06697135930613, 'weight_class_2': 4.9182456581899014}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:15,063] Trial 118 finished with value: 0.9433523224690439 and parameters: {'weight_class_0': 1.415600967139829, 'weight_class_1': 8.485265908831558, 'weight_class_2': 4.939123168689618}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:15,065] Trial 117 finished with value: 0.942840824944701 and parameters: {'weight_class_0': 1.4386471809094683, 'weight_class_1': 7.9161060953207105, 'weight_class_2': 4.967507551140608}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:15,103] Trial 119 finished with value: 0.9061941024203661 and parameters: {'weight_class_0': 1.3429903411870958, 'weight_class_1': 1.018317279577964, 'weight_class_2': 4.927902946842291}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:15,112] Trial 120 finished with value: 0.9452274132139381 and parameters: {'weight_class_0': 1.4582706421403269, 'weight_class_1': 7.9795396510089365, 'weight_class_2': 6.518977288947262}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:15,121] Trial 121 finished with value: 0.9435262911927169 and parameters: {'weight_class_0': 1.3620933418596217, 'weight_class_1': 7.964175252886159, 'weight_class_2': 4.915205552775049}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:15,162] Trial 122 finished with value: 0.9062850186317911 and parameters: {'weight_class_0': 1.5142557118783828, 'weight_class_1': 1.2211834174238727, 'weight_class_2': 4.916141830324131}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:15,167] Trial 123 finished with value: 0.9352671496088693 and parameters: {'weight_class_0': 1.5418279712638303, 'weight_class_1': 8.784661125331501, 'weight_class_2': 3.4571704784299206}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:15,180] Trial 124 finished with value: 0.9441344892601329 and parameters: {'weight_class_0': 1.3528466976347304, 'weight_class_1': 7.431438028931982, 'weight_class_2': 5.33249236682628}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:15,192] Trial 125 finished with value: 0.8861162377189676 and parameters: {'weight_class_0': 5.036486953354651, 'weight_class_1': 8.689415305941395, 'weight_class_2': 3.495362518423935}. Best is trial 49 with value: 0.9497732983809507.

Best trial: 49. Best value: 0.949773:  14%|██████████████████                                                                                                                   | 136/1000 [00:02<00:16, 53.47it/s]

[I 2026-07-05 15:03:15,227] Trial 126 finished with value: 0.9342025929905615 and parameters: {'weight_class_0': 0.642662911106626, 'weight_class_1': 1.2747467085667585, 'weight_class_2': 3.485542821209182}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:15,233] Trial 127 finished with value: 0.9480223600410148 and parameters: {'weight_class_0': 0.6689433419427762, 'weight_class_1': 8.841890110408057, 'weight_class_2': 3.5592919729712875}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:15,255] Trial 128 finished with value: 0.948003663794046 and parameters: {'weight_class_0': 0.6634690284069206, 'weight_class_1': 8.78920794740018, 'weight_class_2': 3.5096048377181233}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:15,262] Trial 129 finished with value: 0.947581026576087 and parameters: {'weight_class_0': 0.7191410324639651, 'weight_class_1': 6.69985105738231, 'weight_class_2': 3.58688350220745}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:15,292] Trial 130 finished with value: 0.9481568650528672 and parameters: {'weight_class_0': 0.6525983086763523, 'weight_class_1': 8.749399078103933, 'weight_class_2': 3.6096209630685276}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:15,309] Trial 131 finished with value: 0.9482106814484035 and parameters: {'weight_class_0': 0.7198924674554382, 'weight_class_1': 7.388615758681011, 'weight_class_2': 4.262915891270487}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:15,345] Trial 132 finished with value: 0.9478576856156972 and parameters: {'weight_class_0': 0.689434931478865, 'weight_class_1': 6.6687407402560375, 'weight_class_2': 3.5984649355399445}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:15,355] Trial 133 finished with value: 0.9487378973198912 and parameters: {'weight_class_0': 0.6329375441245938, 'weight_class_1': 6.737877556334569, 'weight_class_2': 4.241720217443344}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:15,381] Trial 134 finished with value: 0.9485211828506221 and parameters: {'weight_class_0': 0.29144821233771917, 'weight_class_1': 9.161760324246236, 'weight_class_2': 5.990509591878786}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:15,383] Trial 135 finished with value: 0.9485549655007014 and parameters: {'weight_class_0': 0.2575346106901245, 'weight_class_1': 7.412327279677586, 'weight_class_2': 5.901093789605949}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:15,415] Trial 136 finished with value: 0.94924274913124 and parameters: {'weight_class_0': 0.2783483415400686, 'weight_class_1': 7.422999795809975, 'weight_class_2': 4.223492473927953}. Best is trial 49 with value: 0.9497732983809507.

Best trial: 148. Best value: 0.949814:  15%|███████████████████▌                                                                                                                | 148/1000 [00:02<00:16, 52.55it/s]

[I 2026-07-05 15:03:15,422] Trial 137 finished with value: 0.9485867406130054 and parameters: {'weight_class_0': 0.2621824691330927, 'weight_class_1': 7.12024075775534, 'weight_class_2': 6.000477316213675}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:15,466] Trial 138 finished with value: 0.9494204011730817 and parameters: {'weight_class_0': 0.3471661095896486, 'weight_class_1': 9.103248380524644, 'weight_class_2': 4.203292488919701}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:15,469] Trial 139 finished with value: 0.9488927861537202 and parameters: {'weight_class_0': 0.31406447626385625, 'weight_class_1': 9.132900725955013, 'weight_class_2': 5.764554450410455}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:15,494] Trial 140 finished with value: 0.9478231670599652 and parameters: {'weight_class_0': 0.24375303911573024, 'weight_class_1': 9.361049391816227, 'weight_class_2': 5.784393477177235}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:15,512] Trial 141 finished with value: 0.9488557285599736 and parameters: {'weight_class_0': 0.31131301446970105, 'weight_class_1': 9.133821242980886, 'weight_class_2': 5.8358548250288145}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:15,529] Trial 142 finished with value: 0.948273060096167 and parameters: {'weight_class_0': 0.2689790081491922, 'weight_class_1': 9.166175909425158, 'weight_class_2': 5.930375081768622}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:15,558] Trial 143 finished with value: 0.9491336544992063 and parameters: {'weight_class_0': 0.3276706238274699, 'weight_class_1': 9.12507786347481, 'weight_class_2': 5.291043498389446}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:15,570] Trial 145 finished with value: 0.9153581151642696 and parameters: {'weight_class_0': 0.4202566253924838, 'weight_class_1': 9.17519349765736, 'weight_class_2': 0.45982487062823196}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:15,574] Trial 144 finished with value: 0.9492921762680995 and parameters: {'weight_class_0': 0.34524561790226405, 'weight_class_1': 9.232912410977251, 'weight_class_2': 5.179119378269883}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:15,603] Trial 146 finished with value: 0.9478725621443038 and parameters: {'weight_class_0': 0.4847438033857897, 'weight_class_1': 2.7486409799331573, 'weight_class_2': 5.712581856297874}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:15,640] Trial 147 finished with value: 0.9495980962579135 and parameters: {'weight_class_0': 0.41941970098067, 'weight_class_1': 9.5410150047854, 'weight_class_2': 5.193473351066329}. Best is trial 49 with value: 0.9497732983809507.
[I 2026-07-05 15:03:15,645] Trial 148 finished with value: 0.9498135258120204 and parameters: {'weight_class_0': 0.47848364180453956, 'weight_class_1': 9.635408170112125, 'weight_class_2': 5.2990882507565775}. Best is trial 148 with value: 0.9498135258120204.

[I 2026-07-05 15:03:15,666] Trial 149 finished with value: 0.9498046685212135 and parameters: {'weight_class_0': 0.47316110335767164, 'weight_class_1': 9.611452933354462, 'weight_class_2': 5.302156981832577}. Best is trial 148 with value: 0.9498135258120204.
[I 2026-07-05 15:03:15,685] Trial 150 finished with value: 0.9497952895098738 and parameters: {'weight_class_0': 0.46900675203224107, 'weight_class_1': 9.570637955483964, 'weight_class_2': 5.298777872126685}. Best is trial 148 with value: 0.9498135258120204.
[I 2026-07-05 15:03:15,698] Trial 151 finished with value: 0.94968053233066 and parameters: {'weight_class_0': 0.46162370870544434, 'weight_class_1': 9.603903209597, 'weight_class_2': 6.298599780620576}. Best is trial 148 with value: 0.9498135258120204.
[I 2026-07-05 15:03:15,717] Trial 152 finished with value: 0.9479013354707332 and parameters: {'weight_class_0': 0.4941474148410316, 'weight_class_1': 2.87672597582503, 'weight_class_2': 6.653993926580769}. Best is trial 148 with value: 0.9498135258120204.
[I 2026-07-05 15:03:15,738] Trial 153 finished with value: 0.9496781783379159 and parameters: {'weight_class_0': 0.4827846756628073, 'weight_class_1': 9.515276320035449, 'weight_class_2': 6.267420897662236}. Best is trial 148 with value: 0.9498135258120204.
[I 2026-07-05 15:03:15,776] Trial 154 finished with value: 0.949725809799754 and parameters: {'weight_class_0': 0.531815581457764, 'weight_class_1': 9.640353006708327, 'weight_class_2': 6.320228803017726}. Best is trial 148 with value: 0.9498135258120204.
[I 2026-07-05 15:03:15,792] Trial 155 finished with value: 0.9494815070039021 and parameters: {'weight_class_0': 0.46520189647945837, 'weight_class_1': 9.629239533576708, 'weight_class_2': 3.822553270077488}. Best is trial 148 with value: 0.9498135258120204.
[I 2026-07-05 15:03:15,803] Trial 157 finished with value: 0.9491456647160303 and parameters: {'weight_class_0': 0.5115531118475102, 'weight_class_1': 9.578563254424106, 'weight_class_2': 3.796338703731199}. Best is trial 148 with value: 0.9498135258120204.
[I 2026-07-05 15:03:15,808] Trial 156 finished with value: 0.9497267505528554 and parameters: {'weight_class_0': 0.5049733605336388, 'weight_class_1': 9.607892670125919, 'weight_class_2': 6.320090878506002}. Best is trial 148 with value: 0.9498135258120204.
[I 2026-07-05 15:03:15,842] Trial 158 finished with value: 0.9497296042178552 and parameters: {'weight_class_0': 0.5263190328364498, 'weight_class_1': 9.582096746366666, 'weight_class_2': 6.315427613827811}. Best is trial 148 with value: 0.9498135258120204.
[I 2026-07-05 15:03:15,859] Trial 160 finished with value: 0.9497444755661973 and parameters: {'weight_class_0': 0.5113704007088042, 'weight_class_1': 9.573862466906405, 'weight_class_2': 6.273691153784583}. Best is trial 148 with value: 0.9498135258120204.

Best trial: 148. Best value: 0.949814:  17%|██████████████████████▍                                                                                                             | 170/1000 [00:03<00:15, 52.90it/s]

[I 2026-07-05 15:03:15,873] Trial 159 finished with value: 0.9496904213431869 and parameters: {'weight_class_0': 0.4985687302145082, 'weight_class_1': 9.652807432492757, 'weight_class_2': 6.277618386824454}. Best is trial 148 with value: 0.9498135258120204.
[I 2026-07-05 15:03:15,877] Trial 161 finished with value: 0.9485010685291795 and parameters: {'weight_class_0': 0.8485189285859529, 'weight_class_1': 9.66715432307548, 'weight_class_2': 5.394085045517591}. Best is trial 148 with value: 0.9498135258120204.
[I 2026-07-05 15:03:15,907] Trial 162 finished with value: 0.9489802453249299 and parameters: {'weight_class_0': 0.884260582741695, 'weight_class_1': 9.578707090201156, 'weight_class_2': 6.447524495411623}. Best is trial 148 with value: 0.9498135258120204.
[I 2026-07-05 15:03:15,937] Trial 163 finished with value: 0.9492053096440912 and parameters: {'weight_class_0': 0.8126428933399124, 'weight_class_1': 9.573439489911138, 'weight_class_2': 6.301774842928975}. Best is trial 148 with value: 0.9498135258120204.
[I 2026-07-05 15:03:15,958] Trial 165 finished with value: 0.9490009442188558 and parameters: {'weight_class_0': 0.8609273788909437, 'weight_class_1': 9.554752926631426, 'weight_class_2': 6.369529849269934}. Best is trial 148 with value: 0.9498135258120204.
[I 2026-07-05 15:03:15,983] Trial 164 finished with value: 0.9491021932947765 and parameters: {'weight_class_0': 0.836390133884936, 'weight_class_1': 9.703680041896641, 'weight_class_2': 6.333463236743866}. Best is trial 148 with value: 0.9498135258120204.
[I 2026-07-05 15:03:15,986] Trial 166 finished with value: 0.9492151122086568 and parameters: {'weight_class_0': 0.7952428394348549, 'weight_class_1': 9.7140010141545, 'weight_class_2': 6.228969723464044}. Best is trial 148 with value: 0.9498135258120204.
[I 2026-07-05 15:03:16,004] Trial 168 finished with value: 0.9491646687136491 and parameters: {'weight_class_0': 0.8232206781704408, 'weight_class_1': 9.739367944908231, 'weight_class_2': 6.287026237320272}. Best is trial 148 with value: 0.9498135258120204.
[I 2026-07-05 15:03:16,008] Trial 167 finished with value: 0.9493467237329932 and parameters: {'weight_class_0': 0.828913421672107, 'weight_class_1': 9.710931757581296, 'weight_class_2': 6.743562035929752}. Best is trial 148 with value: 0.9498135258120204.
[I 2026-07-05 15:03:16,053] Trial 169 finished with value: 0.9491501190119166 and parameters: {'weight_class_0': 0.8686481609602299, 'weight_class_1': 9.754002719800534, 'weight_class_2': 6.87109038450082}. Best is trial 148 with value: 0.9498135258120204.
[I 2026-07-05 15:03:16,074] Trial 170 finished with value: 0.9494727032650121 and parameters: {'weight_class_0': 0.8297927167632577, 'weight_class_1': 9.798096533223072, 'weight_class_2': 6.890337961470305}. Best is trial 148 with value: 0.9498135258120204.

Best trial: 148. Best value: 0.949814:  18%|███████████████████████▉                                                                                                            | 181/1000 [00:03<00:15, 52.21it/s]

[I 2026-07-05 15:03:16,089] Trial 171 finished with value: 0.9494741165046546 and parameters: {'weight_class_0': 0.8383200050175015, 'weight_class_1': 9.743374055842477, 'weight_class_2': 6.971827255010847}. Best is trial 148 with value: 0.9498135258120204.
[I 2026-07-05 15:03:16,091] Trial 172 finished with value: 0.9482555981476685 and parameters: {'weight_class_0': 1.124919279268291, 'weight_class_1': 9.775655749216952, 'weight_class_2': 6.968623719663051}. Best is trial 148 with value: 0.9498135258120204.
[I 2026-07-05 15:03:16,120] Trial 173 finished with value: 0.9477571209508427 and parameters: {'weight_class_0': 1.1516851203059473, 'weight_class_1': 9.749519111669983, 'weight_class_2': 6.163674804943061}. Best is trial 148 with value: 0.9498135258120204.
[I 2026-07-05 15:03:16,140] Trial 174 finished with value: 0.9480148853683646 and parameters: {'weight_class_0': 1.1665320877340997, 'weight_class_1': 9.797493376240322, 'weight_class_2': 6.8773868158153615}. Best is trial 148 with value: 0.9498135258120204.
[I 2026-07-05 15:03:16,142] Trial 175 finished with value: 0.9479350150483193 and parameters: {'weight_class_0': 1.1844022255753828, 'weight_class_1': 9.953580647825877, 'weight_class_2': 6.839068299716014}. Best is trial 148 with value: 0.9498135258120204.
[I 2026-07-05 15:03:16,180] Trial 177 finished with value: 0.9479118947422323 and parameters: {'weight_class_0': 1.1889939272794257, 'weight_class_1': 9.382326651591386, 'weight_class_2': 6.928370489826923}. Best is trial 148 with value: 0.9498135258120204.
[I 2026-07-05 15:03:16,188] Trial 176 finished with value: 0.6635003442304573 and parameters: {'weight_class_0': 0.005873168192731759, 'weight_class_1': 9.376260286715304, 'weight_class_2': 6.852868990995521}. Best is trial 148 with value: 0.9498135258120204.
[I 2026-07-05 15:03:16,232] Trial 179 finished with value: 0.9477913609294845 and parameters: {'weight_class_0': 1.1806109154373639, 'weight_class_1': 9.396047786055302, 'weight_class_2': 6.6194022535987305}. Best is trial 148 with value: 0.9498135258120204.
[I 2026-07-05 15:03:16,238] Trial 178 finished with value: 0.8011008953995545 and parameters: {'weight_class_0': 0.025981822868763604, 'weight_class_1': 9.378355478936495, 'weight_class_2': 6.649226045690755}. Best is trial 148 with value: 0.9498135258120204.
[I 2026-07-05 15:03:16,250] Trial 180 finished with value: 0.9410849753190896 and parameters: {'weight_class_0': 0.12097655075041291, 'weight_class_1': 9.376683530843719, 'weight_class_2': 6.1124961916331255}. Best is trial 148 with value: 0.9498135258120204.
[I 2026-07-05 15:03:16,257] Trial 181 finished with value: 0.9400368429711791 and parameters: {'weight_class_0': 0.11571388232338875, 'weight_class_1': 9.451642671874557, 'weight_class_2': 6.115100277925205}. Best is trial 148 with value: 0.9498135258120204.

Best trial: 187. Best value: 0.949816:  19%|█████████████████████████▍                                                                                                          | 193/1000 [00:03<00:14, 54.66it/s]

[I 2026-07-05 15:03:16,282] Trial 182 finished with value: 0.9497387529831361 and parameters: {'weight_class_0': 0.5375699847165817, 'weight_class_1': 9.312476987422905, 'weight_class_2': 6.557789675828528}. Best is trial 148 with value: 0.9498135258120204.
[I 2026-07-05 15:03:16,298] Trial 183 finished with value: 0.6589245687473632 and parameters: {'weight_class_0': 0.0037578411311828264, 'weight_class_1': 9.43449585645459, 'weight_class_2': 7.28596465503742}. Best is trial 148 with value: 0.9498135258120204.
[I 2026-07-05 15:03:16,328] Trial 185 finished with value: 0.9248526003729509 and parameters: {'weight_class_0': 0.07582625035328927, 'weight_class_1': 9.391692581613578, 'weight_class_2': 6.636784335914757}. Best is trial 148 with value: 0.9498135258120204.
[I 2026-07-05 15:03:16,339] Trial 184 finished with value: 0.8476578158331854 and parameters: {'weight_class_0': 0.036173981976025504, 'weight_class_1': 9.354195934724006, 'weight_class_2': 7.309670696347042}. Best is trial 148 with value: 0.9498135258120204.
[I 2026-07-05 15:03:16,360] Trial 186 finished with value: 0.9497658784470288 and parameters: {'weight_class_0': 0.586205487645259, 'weight_class_1': 9.434460850903056, 'weight_class_2': 7.263437871400399}. Best is trial 148 with value: 0.9498135258120204.
[I 2026-07-05 15:03:16,376] Trial 187 finished with value: 0.9498164936454248 and parameters: {'weight_class_0': 0.57678962352252, 'weight_class_1': 9.45235807715706, 'weight_class_2': 6.567323257554458}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:16,384] Trial 188 finished with value: 0.9496337365512862 and parameters: {'weight_class_0': 0.5858881717709514, 'weight_class_1': 8.23002658542287, 'weight_class_2': 5.197824795317946}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:16,436] Trial 189 finished with value: 0.9497467136868808 and parameters: {'weight_class_0': 0.5508586658455701, 'weight_class_1': 8.58777037242919, 'weight_class_2': 7.443774794112851}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:16,453] Trial 190 finished with value: 0.9496432332980583 and parameters: {'weight_class_0': 0.5505508365989641, 'weight_class_1': 9.948776070163483, 'weight_class_2': 5.145385326432916}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:16,473] Trial 192 finished with value: 0.9494313618480689 and parameters: {'weight_class_0': 0.6484321707853706, 'weight_class_1': 8.58471177531142, 'weight_class_2': 5.336033988163673}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:16,477] Trial 191 finished with value: 0.9497508046474085 and parameters: {'weight_class_0': 0.5821040434147933, 'weight_class_1': 9.522725023190981, 'weight_class_2': 7.3424297512144525}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:16,492] Trial 193 finished with value: 0.9496057575558874 and parameters: {'weight_class_0': 0.5710488590937254, 'weight_class_1': 8.581574995526678, 'weight_class_2': 5.149860352632412}. Best is trial 187 with value: 0.9498164936454248.

Best trial: 187. Best value: 0.949816:  20%|██████████████████████████▉                                                                                                         | 204/1000 [00:03<00:15, 51.71it/s]

[I 2026-07-05 15:03:16,527] Trial 194 finished with value: 0.9497691491166579 and parameters: {'weight_class_0': 0.5675314837935078, 'weight_class_1': 8.885113846336699, 'weight_class_2': 5.655958074331922}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:16,533] Trial 195 finished with value: 0.9496962196625507 and parameters: {'weight_class_0': 0.5694159885209844, 'weight_class_1': 9.980115961685998, 'weight_class_2': 7.781201765848139}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:16,539] Trial 196 finished with value: 0.949730676366305 and parameters: {'weight_class_0': 0.5754937499505922, 'weight_class_1': 8.936504992792097, 'weight_class_2': 7.802141814190853}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:16,551] Trial 197 finished with value: 0.9496892013773995 and parameters: {'weight_class_0': 0.5759836057929824, 'weight_class_1': 8.928712755615019, 'weight_class_2': 7.461210472352768}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:16,578] Trial 198 finished with value: 0.9497019527468251 and parameters: {'weight_class_0': 0.5861679328067574, 'weight_class_1': 8.949358807679193, 'weight_class_2': 7.782751621222852}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:16,582] Trial 199 finished with value: 0.9497446545995302 and parameters: {'weight_class_0': 0.5948788949688426, 'weight_class_1': 9.988343665911414, 'weight_class_2': 8.029826990152928}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:16,601] Trial 200 finished with value: 0.949667174561029 and parameters: {'weight_class_0': 0.5571126570463959, 'weight_class_1': 9.966207941576982, 'weight_class_2': 7.939895781292408}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:16,670] Trial 201 finished with value: 0.9496907713270195 and parameters: {'weight_class_0': 0.564353615536419, 'weight_class_1': 8.955755291822996, 'weight_class_2': 7.9280440561087175}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:16,674] Trial 202 finished with value: 0.949733280653905 and parameters: {'weight_class_0': 0.5588140948467378, 'weight_class_1': 9.00235785007216, 'weight_class_2': 7.619644171678693}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:16,688] Trial 203 finished with value: 0.9496716001828426 and parameters: {'weight_class_0': 0.5685917797595936, 'weight_class_1': 8.923732427097782, 'weight_class_2': 7.9708446795812895}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:16,692] Trial 204 finished with value: 0.8931729438535237 and parameters: {'weight_class_0': 6.713908461292519, 'weight_class_1': 8.90935017679856, 'weight_class_2': 7.737687244442085}. Best is trial 187 with value: 0.9498164936454248.

[I 2026-07-05 15:03:16,713] Trial 205 finished with value: 0.9475388826487335 and parameters: {'weight_class_0': 0.21962941435462136, 'weight_class_1': 8.868057270862451, 'weight_class_2': 5.670684725596745}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:16,750] Trial 207 finished with value: 0.9231793473168147 and parameters: {'weight_class_0': 3.7826716515364858, 'weight_class_1': 9.003586792626777, 'weight_class_2': 7.56324338517997}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:16,757] Trial 208 finished with value: 0.9468245140360151 and parameters: {'weight_class_0': 0.21762331727360767, 'weight_class_1': 8.932095491082098, 'weight_class_2': 8.124860792202853}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:16,762] Trial 206 finished with value: 0.9497528899002207 and parameters: {'weight_class_0': 0.6429417225693758, 'weight_class_1': 8.958930981600528, 'weight_class_2': 7.890367566932313}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:16,791] Trial 209 finished with value: 0.9467390050596928 and parameters: {'weight_class_0': 0.2203870610300307, 'weight_class_1': 9.00149082652714, 'weight_class_2': 8.617495448581836}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:16,821] Trial 210 finished with value: 0.9466909382224866 and parameters: {'weight_class_0': 0.21821271067084236, 'weight_class_1': 8.938555897801837, 'weight_class_2': 8.669877376639072}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:16,831] Trial 211 finished with value: 0.9475249439991195 and parameters: {'weight_class_0': 0.2435637600693601, 'weight_class_1': 8.799589281962483, 'weight_class_2': 7.588513218950946}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:16,846] Trial 212 finished with value: 0.9477808014978653 and parameters: {'weight_class_0': 0.2607734166267096, 'weight_class_1': 9.199304241761062, 'weight_class_2': 7.497744849554917}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:16,883] Trial 213 finished with value: 0.9245589627173816 and parameters: {'weight_class_0': 3.882832377033446, 'weight_class_1': 9.209608820781133, 'weight_class_2': 8.205869251434445}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:16,904] Trial 214 finished with value: 0.9474849018874671 and parameters: {'weight_class_0': 0.2544141826857519, 'weight_class_1': 9.187119224494065, 'weight_class_2': 8.145981506317266}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:16,921] Trial 215 finished with value: 0.9473613320072385 and parameters: {'weight_class_0': 0.24054260926111853, 'weight_class_1': 9.149246559620204, 'weight_class_2': 7.503904862729496}. Best is trial 187 with value: 0.9498164936454248.

Best trial: 187. Best value: 0.949816:  23%|█████████████████████████████▊                                                                                                      | 226/1000 [00:04<00:14, 52.96it/s]

[I 2026-07-05 15:03:16,931] Trial 216 finished with value: 0.9497247984429347 and parameters: {'weight_class_0': 0.7516733075013686, 'weight_class_1': 9.232390400779925, 'weight_class_2': 7.603665818651177}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:16,951] Trial 217 finished with value: 0.9496785311513155 and parameters: {'weight_class_0': 0.7346597369261703, 'weight_class_1': 9.138551244037084, 'weight_class_2': 8.61283204212028}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:16,964] Trial 218 finished with value: 0.9490394979254649 and parameters: {'weight_class_0': 0.9900168044811772, 'weight_class_1': 9.220953028748, 'weight_class_2': 7.536738237710576}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:16,994] Trial 219 finished with value: 0.9497294029257995 and parameters: {'weight_class_0': 0.7201215148519925, 'weight_class_1': 9.198204041868895, 'weight_class_2': 8.220893190039243}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,012] Trial 220 finished with value: 0.9497765062420506 and parameters: {'weight_class_0': 0.7500707787482287, 'weight_class_1': 9.256982321453073, 'weight_class_2': 8.304782426934535}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,015] Trial 221 finished with value: 0.9497250319838045 and parameters: {'weight_class_0': 0.7245744900073409, 'weight_class_1': 9.262210587065367, 'weight_class_2': 7.319847790346624}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,047] Trial 222 finished with value: 0.9496802518790961 and parameters: {'weight_class_0': 0.739152042775217, 'weight_class_1': 8.614110042744997, 'weight_class_2': 7.345980528646492}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,075] Trial 223 finished with value: 0.9495305135357928 and parameters: {'weight_class_0': 0.765818164785998, 'weight_class_1': 8.563631187024823, 'weight_class_2': 7.159130349349283}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,095] Trial 224 finished with value: 0.9496734244209607 and parameters: {'weight_class_0': 0.7288114616306395, 'weight_class_1': 8.620170256094704, 'weight_class_2': 7.110518932887341}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,119] Trial 226 finished with value: 0.9489061819210645 and parameters: {'weight_class_0': 0.9769037812200829, 'weight_class_1': 8.579815378705362, 'weight_class_2': 7.348244297755111}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,136] Trial 225 finished with value: 0.9486036560161919 and parameters: {'weight_class_0': 1.0388907785175827, 'weight_class_1': 8.628523534034139, 'weight_class_2': 7.370872618753475}. Best is trial 187 with value: 0.9498164936454248.

Best trial: 187. Best value: 0.949816:  24%|███████████████████████████████▎                                                                                                    | 237/1000 [00:04<00:14, 53.86it/s]

[I 2026-07-05 15:03:17,152] Trial 227 finished with value: 0.9497088591868693 and parameters: {'weight_class_0': 0.7114276079289077, 'weight_class_1': 8.638786596610993, 'weight_class_2': 7.242823134235022}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,154] Trial 228 finished with value: 0.9496455432227076 and parameters: {'weight_class_0': 0.7790019467651084, 'weight_class_1': 9.573350578493333, 'weight_class_2': 7.166556767084071}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,192] Trial 229 finished with value: 0.9496900761502373 and parameters: {'weight_class_0': 0.7294994670035039, 'weight_class_1': 8.632406474490255, 'weight_class_2': 8.310125965814974}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,208] Trial 230 finished with value: 0.9493115207015016 and parameters: {'weight_class_0': 0.9829601024330914, 'weight_class_1': 8.618608281324663, 'weight_class_2': 8.39893002856239}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,211] Trial 231 finished with value: 0.9489597448345828 and parameters: {'weight_class_0': 0.957343861926454, 'weight_class_1': 9.516885163117598, 'weight_class_2': 7.117857562495441}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,238] Trial 232 finished with value: 0.9491836049550018 and parameters: {'weight_class_0': 0.9829856242917882, 'weight_class_1': 9.545678085816323, 'weight_class_2': 7.858960687908275}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,259] Trial 233 finished with value: 0.9490042483689289 and parameters: {'weight_class_0': 0.4189851453676234, 'weight_class_1': 9.542827087800697, 'weight_class_2': 8.424680316778906}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,274] Trial 234 finished with value: 0.949311711019852 and parameters: {'weight_class_0': 0.44947430599902966, 'weight_class_1': 9.509943523733957, 'weight_class_2': 8.368088155607836}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,297] Trial 235 finished with value: 0.9492237149850925 and parameters: {'weight_class_0': 0.4398342846653514, 'weight_class_1': 9.537690197983961, 'weight_class_2': 8.372151983196797}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,312] Trial 236 finished with value: 0.9491605457721376 and parameters: {'weight_class_0': 0.43043245617151416, 'weight_class_1': 9.473387589380277, 'weight_class_2': 8.355008328975883}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,339] Trial 237 finished with value: 0.9489521319279474 and parameters: {'weight_class_0': 0.39285925794834853, 'weight_class_1': 9.475343264054832, 'weight_class_2': 7.804824663592928}. Best is trial 187 with value: 0.9498164936454248.

[I 2026-07-05 15:03:17,365] Trial 238 finished with value: 0.9493077777277833 and parameters: {'weight_class_0': 0.4359876486892714, 'weight_class_1': 9.423044654041325, 'weight_class_2': 7.944491400602839}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,366] Trial 239 finished with value: 0.9488273290672548 and parameters: {'weight_class_0': 0.40891182670075016, 'weight_class_1': 9.488308965751822, 'weight_class_2': 8.86971749195867}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,389] Trial 240 finished with value: 0.9493037254049512 and parameters: {'weight_class_0': 0.4376239704899599, 'weight_class_1': 9.461376549411597, 'weight_class_2': 8.024691582776594}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,405] Trial 241 finished with value: 0.9488116310647307 and parameters: {'weight_class_0': 0.40168021462410686, 'weight_class_1': 9.399864336373136, 'weight_class_2': 8.927761904002866}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,439] Trial 242 finished with value: 0.9490824313045979 and parameters: {'weight_class_0': 0.4469702342690782, 'weight_class_1': 9.369330422336871, 'weight_class_2': 9.027128979399498}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,453] Trial 243 finished with value: 0.9490674522746766 and parameters: {'weight_class_0': 0.41264124915010536, 'weight_class_1': 9.36370195815905, 'weight_class_2': 8.152866741391412}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,466] Trial 244 finished with value: 0.9491999741126146 and parameters: {'weight_class_0': 0.4232724415213928, 'weight_class_1': 9.302878571888822, 'weight_class_2': 8.114783139204967}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,498] Trial 245 finished with value: 0.9496687744849049 and parameters: {'weight_class_0': 0.6416407577912349, 'weight_class_1': 9.312233636826923, 'weight_class_2': 8.946692804572848}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,509] Trial 246 finished with value: 0.9497016360938306 and parameters: {'weight_class_0': 0.6279160958764423, 'weight_class_1': 9.313865396789197, 'weight_class_2': 8.057384418369844}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,520] Trial 248 finished with value: 0.9495109578177873 and parameters: {'weight_class_0': 0.6453885347701305, 'weight_class_1': 8.240122391900977, 'weight_class_2': 5.449934405622838}. Best is trial 187 with value: 0.9498164936454248.

Best trial: 187. Best value: 0.949816:  26%|██████████████████████████████████▏                                                                                                 | 259/1000 [00:05<00:13, 53.72it/s]

[I 2026-07-05 15:03:17,527] Trial 247 finished with value: 0.873081596311258 and parameters: {'weight_class_0': 8.504514144705956, 'weight_class_1': 9.269650904596382, 'weight_class_2': 5.504726190415479}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,564] Trial 250 finished with value: 0.9497360351723708 and parameters: {'weight_class_0': 0.661699487103457, 'weight_class_1': 9.107543445844616, 'weight_class_2': 7.6657547032510935}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,577] Trial 249 finished with value: 0.9497694294065152 and parameters: {'weight_class_0': 0.67329816262042, 'weight_class_1': 9.293445836817332, 'weight_class_2': 7.675801605202281}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,601] Trial 251 finished with value: 0.949546455379659 and parameters: {'weight_class_0': 0.6614726059861444, 'weight_class_1': 9.268342269859808, 'weight_class_2': 5.607177634539219}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,617] Trial 252 finished with value: 0.9489856187339655 and parameters: {'weight_class_0': 0.7372360714214252, 'weight_class_1': 8.178310979533078, 'weight_class_2': 5.467956957563468}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,649] Trial 253 finished with value: 0.9497266848399559 and parameters: {'weight_class_0': 0.6621186693244725, 'weight_class_1': 9.066864259772759, 'weight_class_2': 7.694149000720824}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,669] Trial 254 finished with value: 0.9497546844932182 and parameters: {'weight_class_0': 0.6546588360355615, 'weight_class_1': 9.102153430859008, 'weight_class_2': 7.727404557132325}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,695] Trial 256 finished with value: 0.9496072025303609 and parameters: {'weight_class_0': 0.8227059778994525, 'weight_class_1': 9.80949904087023, 'weight_class_2': 7.669844939985901}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,700] Trial 255 finished with value: 0.948950302114676 and parameters: {'weight_class_0': 0.805092857928698, 'weight_class_1': 9.807094430713768, 'weight_class_2': 5.805597254453485}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,714] Trial 257 finished with value: 0.9489698881819512 and parameters: {'weight_class_0': 0.8147081469752557, 'weight_class_1': 9.815182225130183, 'weight_class_2': 5.8899780002558755}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,746] Trial 258 finished with value: 0.9495299903220494 and parameters: {'weight_class_0': 0.8442878115355142, 'weight_class_1': 9.034167010167968, 'weight_class_2': 7.613771117835506}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,753] Trial 260 finished with value: 0.9495188901509971 and parameters: {'weight_class_0': 0.8760070389963361, 'weight_class_1': 9.827063916450616, 'weight_class_2': 7.6413738469169}. Best is trial 187 with value: 0.9498164936454248.

[I 2026-07-05 15:03:17,754] Trial 259 finished with value: 0.9487175916014624 and parameters: {'weight_class_0': 0.8627733732559971, 'weight_class_1': 9.784112848708247, 'weight_class_2': 5.756681805622098}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,786] Trial 261 finished with value: 0.9486764923222051 and parameters: {'weight_class_0': 0.8934216240977172, 'weight_class_1': 9.820001127273299, 'weight_class_2': 5.893789300726857}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,821] Trial 263 finished with value: 0.9494381610669255 and parameters: {'weight_class_0': 0.8861565066153549, 'weight_class_1': 9.013083831572576, 'weight_class_2': 7.681371876419586}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,833] Trial 262 finished with value: 0.9494203910318593 and parameters: {'weight_class_0': 0.8846252443764211, 'weight_class_1': 8.815996022950815, 'weight_class_2': 7.650798086637689}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,859] Trial 264 finished with value: 0.9493226875106234 and parameters: {'weight_class_0': 0.9426674892251827, 'weight_class_1': 8.84049535263186, 'weight_class_2': 7.734167670301275}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,877] Trial 265 finished with value: 0.9494130209897342 and parameters: {'weight_class_0': 0.9190000667970767, 'weight_class_1': 8.84168902983655, 'weight_class_2': 7.791907473378784}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,904] Trial 266 finished with value: 0.949086025252551 and parameters: {'weight_class_0': 0.987265639797307, 'weight_class_1': 9.04800717640221, 'weight_class_2': 7.8055623480286025}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,923] Trial 268 finished with value: 0.9496905937535857 and parameters: {'weight_class_0': 0.6057790240666011, 'weight_class_1': 8.819483223225722, 'weight_class_2': 7.89170910268195}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,945] Trial 267 finished with value: 0.9473103742987764 and parameters: {'weight_class_0': 0.23651949369149605, 'weight_class_1': 8.86316010728774, 'weight_class_2': 7.832566680654118}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,959] Trial 269 finished with value: 0.9469635735564186 and parameters: {'weight_class_0': 0.21814582264226084, 'weight_class_1': 8.770894966000384, 'weight_class_2': 7.941312383367638}. Best is trial 187 with value: 0.9498164936454248.

Best trial: 283. Best value: 0.949822:  28%|████████████████████████████████████▉                                                                                               | 280/1000 [00:05<00:14, 51.41it/s]

[I 2026-07-05 15:03:17,966] Trial 270 finished with value: 0.9497076716933736 and parameters: {'weight_class_0': 0.5824466371407628, 'weight_class_1': 8.75512613684277, 'weight_class_2': 7.847057442284078}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:17,981] Trial 271 finished with value: 0.9470253659213274 and parameters: {'weight_class_0': 0.22184094248507552, 'weight_class_1': 8.831308438995324, 'weight_class_2': 7.967098705460116}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:18,011] Trial 272 finished with value: 0.9466641747417027 and parameters: {'weight_class_0': 0.20789957664835557, 'weight_class_1': 8.800934244767248, 'weight_class_2': 7.91373471481913}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:18,021] Trial 273 finished with value: 0.9483355792491466 and parameters: {'weight_class_0': 0.25685047771671254, 'weight_class_1': 8.790378643309621, 'weight_class_2': 5.290051869755634}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:18,049] Trial 274 finished with value: 0.9485716022901588 and parameters: {'weight_class_0': 0.27197577567440057, 'weight_class_1': 8.791079042265087, 'weight_class_2': 5.326533681027305}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:18,062] Trial 275 finished with value: 0.9496442370194046 and parameters: {'weight_class_0': 0.5790942384001113, 'weight_class_1': 9.062574195082798, 'weight_class_2': 5.230033899667619}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:18,076] Trial 276 finished with value: 0.9497644587615861 and parameters: {'weight_class_0': 0.5274780811365778, 'weight_class_1': 8.368347553279516, 'weight_class_2': 5.26756358280826}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:18,109] Trial 277 finished with value: 0.9477975771612898 and parameters: {'weight_class_0': 0.2153047568375318, 'weight_class_1': 8.349093399566058, 'weight_class_2': 5.100422434357958}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:18,115] Trial 278 finished with value: 0.9496711922113484 and parameters: {'weight_class_0': 0.5747395365309218, 'weight_class_1': 8.333595997193028, 'weight_class_2': 5.3336611553585485}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:18,151] Trial 280 finished with value: 0.9496089852317314 and parameters: {'weight_class_0': 0.5874455109872256, 'weight_class_1': 8.324542018011465, 'weight_class_2': 5.222674566379982}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:18,159] Trial 279 finished with value: 0.9496077828679015 and parameters: {'weight_class_0': 0.5949333879833905, 'weight_class_1': 9.110504156803579, 'weight_class_2': 5.332218554296542}. Best is trial 187 with value: 0.9498164936454248.

[I 2026-07-05 15:03:18,172] Trial 281 finished with value: 0.9497264647298017 and parameters: {'weight_class_0': 0.5454550265756128, 'weight_class_1': 8.44506131276117, 'weight_class_2': 5.32927409549303}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:18,202] Trial 282 finished with value: 0.9497887359242551 and parameters: {'weight_class_0': 0.5661034578797584, 'weight_class_1': 8.440349474257635, 'weight_class_2': 6.538811276366225}. Best is trial 187 with value: 0.9498164936454248.
[I 2026-07-05 15:03:18,211] Trial 283 finished with value: 0.949821861924737 and parameters: {'weight_class_0': 0.5773762665209728, 'weight_class_1': 8.389470097293566, 'weight_class_2': 6.5265825687068455}. Best is trial 283 with value: 0.949821861924737.
[I 2026-07-05 15:03:18,242] Trial 284 finished with value: 0.9465186450909714 and parameters: {'weight_class_0': 1.1219294455378317, 'weight_class_1': 8.35699436591273, 'weight_class_2': 5.057205313276565}. Best is trial 283 with value: 0.949821861924737.
[I 2026-07-05 15:03:18,274] Trial 286 finished with value: 0.9472487838600608 and parameters: {'weight_class_0': 1.1275697597331549, 'weight_class_1': 8.416835375619954, 'weight_class_2': 5.678929172660428}. Best is trial 283 with value: 0.949821861924737.
[I 2026-07-05 15:03:18,283] Trial 285 finished with value: 0.9466783129478689 and parameters: {'weight_class_0': 1.1909204428520415, 'weight_class_1': 9.117031511039592, 'weight_class_2': 5.520407609698004}. Best is trial 283 with value: 0.949821861924737.
[I 2026-07-05 15:03:18,289] Trial 287 finished with value: 0.9468949985794289 and parameters: {'weight_class_0': 1.1836537355982122, 'weight_class_1': 9.07907770973813, 'weight_class_2': 5.629785530260139}. Best is trial 283 with value: 0.949821861924737.
[I 2026-07-05 15:03:18,302] Trial 288 finished with value: 0.946712295227373 and parameters: {'weight_class_0': 1.192988628416618, 'weight_class_1': 8.484943506607072, 'weight_class_2': 5.6768318094502925}. Best is trial 283 with value: 0.949821861924737.
[I 2026-07-05 15:03:18,327] Trial 289 finished with value: 0.9112141497454234 and parameters: {'weight_class_0': 1.1916392865625385, 'weight_class_1': 8.502855594601433, 'weight_class_2': 1.1598471703960032}. Best is trial 283 with value: 0.949821861924737.
[I 2026-07-05 15:03:18,345] Trial 290 finished with value: 0.9483745690733761 and parameters: {'weight_class_0': 1.1325210900461538, 'weight_class_1': 9.16040463763533, 'weight_class_2': 7.407789387928364}. Best is trial 283 with value: 0.949821861924737.

[I 2026-07-05 15:03:18,376] Trial 292 finished with value: 0.946509964998585 and parameters: {'weight_class_0': 1.1860007275170092, 'weight_class_1': 8.042034008064926, 'weight_class_2': 5.627305063725084}. Best is trial 283 with value: 0.949821861924737.
[I 2026-07-05 15:03:18,400] Trial 291 finished with value: 0.9494594329278877 and parameters: {'weight_class_0': 0.40237415224636647, 'weight_class_1': 8.427807629778734, 'weight_class_2': 6.6277524306258355}. Best is trial 283 with value: 0.949821861924737.
[I 2026-07-05 15:03:18,416] Trial 293 finished with value: 0.9493546832162099 and parameters: {'weight_class_0': 0.3761817581065143, 'weight_class_1': 8.148139570582686, 'weight_class_2': 6.555101150214514}. Best is trial 283 with value: 0.949821861924737.
[I 2026-07-05 15:03:18,426] Trial 294 finished with value: 0.9136306417851253 and parameters: {'weight_class_0': 1.2183209405950086, 'weight_class_1': 8.190085309447651, 'weight_class_2': 1.2930911222545016}. Best is trial 283 with value: 0.949821861924737.
[I 2026-07-05 15:03:18,460] Trial 295 finished with value: 0.9487248851345823 and parameters: {'weight_class_0': 0.32857602133448627, 'weight_class_1': 8.108629395226625, 'weight_class_2': 7.380686786736628}. Best is trial 283 with value: 0.949821861924737.
[I 2026-07-05 15:03:18,485] Trial 296 finished with value: 0.9493880042226629 and parameters: {'weight_class_0': 0.4121812407570551, 'weight_class_1': 8.186132884871128, 'weight_class_2': 7.439311562919882}. Best is trial 283 with value: 0.949821861924737.
[I 2026-07-05 15:03:18,499] Trial 297 finished with value: 0.9492202043287937 and parameters: {'weight_class_0': 0.3862074207234408, 'weight_class_1': 8.00968166805898, 'weight_class_2': 7.4620788459341325}. Best is trial 283 with value: 0.949821861924737.
[I 2026-07-05 15:03:18,514] Trial 298 finished with value: 0.9018095384580622 and parameters: {'weight_class_0': 4.972662191764678, 'weight_class_1': 7.936474513338343, 'weight_class_2': 6.54798138824285}. Best is trial 283 with value: 0.949821861924737.
[I 2026-07-05 15:03:18,527] Trial 299 finished with value: 0.9492967034138023 and parameters: {'weight_class_0': 0.36593213024514226, 'weight_class_1': 8.192519742708352, 'weight_class_2': 6.576466221723075}. Best is trial 283 with value: 0.949821861924737.
[I 2026-07-05 15:03:18,535] Trial 300 finished with value: 0.9493499824294099 and parameters: {'weight_class_0': 0.38165935940853846, 'weight_class_1': 8.208719184855696, 'weight_class_2': 6.672286808145512}. Best is trial 283 with value: 0.949821861924737.
[I 2026-07-05 15:03:18,557] Trial 301 finished with value: 0.9492694215072968 and parameters: {'weight_class_0': 0.3651289256108801, 'weight_class_1': 8.181718772574191, 'weight_class_2': 6.703627148821219}. Best is trial 283 with value: 0.949821861924737.

[I 2026-07-05 15:03:18,573] Trial 302 finished with value: 0.8931687377508717 and parameters: {'weight_class_0': 4.91613076643215, 'weight_class_1': 8.070476582394658, 'weight_class_2': 4.796408933838602}. Best is trial 283 with value: 0.949821861924737.
[I 2026-07-05 15:03:18,594] Trial 303 finished with value: 0.9492025102404754 and parameters: {'weight_class_0': 0.40954502242750207, 'weight_class_1': 9.979596623107316, 'weight_class_2': 7.081216822543894}. Best is trial 283 with value: 0.949821861924737.
[I 2026-07-05 15:03:18,632] Trial 304 finished with value: 0.9492299028149812 and parameters: {'weight_class_0': 0.3935151008074883, 'weight_class_1': 8.573131067970987, 'weight_class_2': 7.457849369405619}. Best is trial 283 with value: 0.949821861924737.
[I 2026-07-05 15:03:18,655] Trial 305 finished with value: 0.9497289879409303 and parameters: {'weight_class_0': 0.698598499727195, 'weight_class_1': 8.649917895722133, 'weight_class_2': 7.022191006016789}. Best is trial 283 with value: 0.949821861924737.
[I 2026-07-05 15:03:18,665] Trial 306 finished with value: 0.9341445500513332 and parameters: {'weight_class_0': 2.6750651801825027, 'weight_class_1': 8.557871022695817, 'weight_class_2': 7.064873916924385}. Best is trial 283 with value: 0.949821861924737.
[I 2026-07-05 15:03:18,677] Trial 307 finished with value: 0.9496038695218333 and parameters: {'weight_class_0': 0.6828313638186333, 'weight_class_1': 9.97020239848505, 'weight_class_2': 6.065014696490357}. Best is trial 283 with value: 0.949821861924737.
[I 2026-07-05 15:03:18,723] Trial 308 finished with value: 0.9498248152502544 and parameters: {'weight_class_0': 0.6322592907673967, 'weight_class_1': 8.634010234583142, 'weight_class_2': 7.016923661836476}. Best is trial 308 with value: 0.9498248152502544.
[I 2026-07-05 15:03:18,733] Trial 309 finished with value: 0.9497586481012444 and parameters: {'weight_class_0': 0.6701248958125489, 'weight_class_1': 8.650329872286681, 'weight_class_2': 6.984579732216824}. Best is trial 308 with value: 0.9498248152502544.
[I 2026-07-05 15:03:18,741] Trial 310 finished with value: 0.9491882947676308 and parameters: {'weight_class_0': 0.6956696599504801, 'weight_class_1': 8.631591003031952, 'weight_class_2': 5.490031838720485}. Best is trial 308 with value: 0.9498248152502544.
[I 2026-07-05 15:03:18,773] Trial 311 finished with value: 0.9497314748965708 and parameters: {'weight_class_0': 0.693830986505072, 'weight_class_1': 8.64701836482484, 'weight_class_2': 7.116693001545581}. Best is trial 308 with value: 0.9498248152502544.
[I 2026-07-05 15:03:18,778] Trial 312 finished with value: 0.930923088212689 and parameters: {'weight_class_0': 2.6526517317527496, 'weight_class_1': 8.63198491281513, 'weight_class_2': 5.963186573903526}. Best is trial 308 with value: 0.9498248152502544.
[I 2026-07-05 15:03:18,803] Trial 313 finished with value: 0.9495644994233504 and parameters: {'weight_class_0': 0.6810440881690426, 'weight_class_1': 8.59567516956534, 'weight_class_2': 5.93876727986755}. Best is trial 308 with value: 0.9498248152502544.

Best trial: 308. Best value: 0.949825:  32%|██████████████████████████████████████████▉                                                                                         | 325/1000 [00:06<00:12, 54.08it/s]

[I 2026-07-05 15:03:18,818] Trial 314 finished with value: 0.949809029717745 and parameters: {'weight_class_0': 0.6357974119133595, 'weight_class_1': 8.680693052616853, 'weight_class_2': 7.046054115946314}. Best is trial 308 with value: 0.9498248152502544.
[I 2026-07-05 15:03:18,851] Trial 315 finished with value: 0.9492020233560918 and parameters: {'weight_class_0': 0.6638467142509227, 'weight_class_1': 9.646273057693366, 'weight_class_2': 5.027809866951028}. Best is trial 308 with value: 0.9498248152502544.
[I 2026-07-05 15:03:18,876] Trial 316 finished with value: 0.9225937136105706 and parameters: {'weight_class_0': 0.07281035189220186, 'weight_class_1': 9.642002524728479, 'weight_class_2': 6.059121143759823}. Best is trial 308 with value: 0.9498248152502544.
[I 2026-07-05 15:03:18,885] Trial 317 finished with value: 0.9482581228630483 and parameters: {'weight_class_0': 0.6743875282977257, 'weight_class_1': 4.1304265191390765, 'weight_class_2': 6.070991345235912}. Best is trial 308 with value: 0.9498248152502544.
[I 2026-07-05 15:03:18,903] Trial 318 finished with value: 0.927928409909076 and parameters: {'weight_class_0': 0.07432931568591034, 'weight_class_1': 9.031246833883188, 'weight_class_2': 5.027168170428303}. Best is trial 308 with value: 0.9498248152502544.
[I 2026-07-05 15:03:18,924] Trial 320 finished with value: 0.7357647814982435 and parameters: {'weight_class_0': 0.017287204285245217, 'weight_class_1': 9.613261689710104, 'weight_class_2': 6.817250428890665}. Best is trial 308 with value: 0.9498248152502544.
[I 2026-07-05 15:03:18,925] Trial 319 finished with value: 0.9249833910924053 and parameters: {'weight_class_0': 0.07890055102270205, 'weight_class_1': 9.631563004492511, 'weight_class_2': 7.176734614056176}. Best is trial 308 with value: 0.9498248152502544.
[I 2026-07-05 15:03:18,965] Trial 322 finished with value: 0.9496802721667983 and parameters: {'weight_class_0': 0.7452542920201322, 'weight_class_1': 9.697114173285746, 'weight_class_2': 7.168120163348037}. Best is trial 308 with value: 0.9498248152502544.
[I 2026-07-05 15:03:18,970] Trial 321 finished with value: 0.7773234644408026 and parameters: {'weight_class_0': 0.014687117391692261, 'weight_class_1': 4.037203649593653, 'weight_class_2': 6.800544593255565}. Best is trial 308 with value: 0.9498248152502544.
[I 2026-07-05 15:03:18,980] Trial 323 finished with value: 0.9323544502360287 and parameters: {'weight_class_0': 0.09172423838430116, 'weight_class_1': 9.596334616444425, 'weight_class_2': 6.867346802948356}. Best is trial 308 with value: 0.9498248152502544.
[I 2026-07-05 15:03:19,009] Trial 324 finished with value: 0.7012178773716666 and parameters: {'weight_class_0': 0.012808340029923704, 'weight_class_1': 9.6735995494905, 'weight_class_2': 6.863044663580513}. Best is trial 308 with value: 0.9498248152502544.
[I 2026-07-05 15:03:19,024] Trial 325 finished with value: 0.9455086372208227 and parameters: {'weight_class_0': 0.1127757435631187, 'weight_class_1': 1.8755131623221182, 'weight_class_2': 6.905708985592248}. Best is trial 308 with value: 0.9498248152502544.

Best trial: 308. Best value: 0.949825:  34%|████████████████████████████████████████████▍                                                                                       | 337/1000 [00:06<00:12, 54.65it/s]

[I 2026-07-05 15:03:19,043] Trial 326 finished with value: 0.9423048226683831 and parameters: {'weight_class_0': 0.0785734589652975, 'weight_class_1': 1.9178630885955639, 'weight_class_2': 6.860657911194339}. Best is trial 308 with value: 0.9498248152502544.
[I 2026-07-05 15:03:19,054] Trial 327 finished with value: 0.9489334823136716 and parameters: {'weight_class_0': 0.9439260348934981, 'weight_class_1': 9.38651626284387, 'weight_class_2': 6.8925221873065405}. Best is trial 308 with value: 0.9498248152502544.
[I 2026-07-05 15:03:19,068] Trial 328 finished with value: 0.948825016713589 and parameters: {'weight_class_0': 0.964984840975303, 'weight_class_1': 9.289194387699991, 'weight_class_2': 6.931374217903127}. Best is trial 308 with value: 0.9498248152502544.
[I 2026-07-05 15:03:19,094] Trial 329 finished with value: 0.9492881712772574 and parameters: {'weight_class_0': 0.8649007255504002, 'weight_class_1': 9.302167777475184, 'weight_class_2': 6.937236436584433}. Best is trial 308 with value: 0.9498248152502544.
[I 2026-07-05 15:03:19,111] Trial 330 finished with value: 0.9494116714635109 and parameters: {'weight_class_0': 0.8346149254842284, 'weight_class_1': 9.29212218313164, 'weight_class_2': 6.850651267512196}. Best is trial 308 with value: 0.9498248152502544.
[I 2026-07-05 15:03:19,132] Trial 331 finished with value: 0.9488193671526258 and parameters: {'weight_class_0': 0.9542757056199906, 'weight_class_1': 9.314199375030789, 'weight_class_2': 6.827266450360153}. Best is trial 308 with value: 0.9498248152502544.
[I 2026-07-05 15:03:19,148] Trial 332 finished with value: 0.9489415676918865 and parameters: {'weight_class_0': 0.9812390287552422, 'weight_class_1': 9.318299187185909, 'weight_class_2': 7.268691179103918}. Best is trial 308 with value: 0.9498248152502544.
[I 2026-07-05 15:03:19,176] Trial 333 finished with value: 0.9490917027110913 and parameters: {'weight_class_0': 0.9237978545380605, 'weight_class_1': 9.287433668084548, 'weight_class_2': 7.2569282078276025}. Best is trial 308 with value: 0.9498248152502544.
[I 2026-07-05 15:03:19,206] Trial 335 finished with value: 0.9487359089752281 and parameters: {'weight_class_0': 0.9252279676991617, 'weight_class_1': 9.268501069419301, 'weight_class_2': 6.4348425549915325}. Best is trial 308 with value: 0.9498248152502544.
[I 2026-07-05 15:03:19,208] Trial 334 finished with value: 0.9495074088321829 and parameters: {'weight_class_0': 0.8531458069135301, 'weight_class_1': 9.288526803550669, 'weight_class_2': 7.274882952139488}. Best is trial 308 with value: 0.9498248152502544.
[I 2026-07-05 15:03:19,220] Trial 336 finished with value: 0.9488021630451571 and parameters: {'weight_class_0': 1.0121201037398184, 'weight_class_1': 9.230861547018778, 'weight_class_2': 7.270343711921358}. Best is trial 308 with value: 0.9498248152502544.
[I 2026-07-05 15:03:19,223] Trial 337 finished with value: 0.9494792945660177 and parameters: {'weight_class_0': 0.8626199013283669, 'weight_class_1': 9.154285003783537, 'weight_class_2': 7.271249214820042}. Best is trial 308 with value: 0.9498248152502544.

Best trial: 346. Best value: 0.949827:  35%|█████████████████████████████████████████████▉                                                                                      | 348/1000 [00:06<00:12, 52.69it/s]

[I 2026-07-05 15:03:19,262] Trial 338 finished with value: 0.9497375257081501 and parameters: {'weight_class_0': 0.5322789422131291, 'weight_class_1': 8.995924244493478, 'weight_class_2': 7.231692419668546}. Best is trial 308 with value: 0.9498248152502544.
[I 2026-07-05 15:03:19,276] Trial 339 finished with value: 0.949711602710884 and parameters: {'weight_class_0': 0.5579435358501531, 'weight_class_1': 9.029333320764806, 'weight_class_2': 7.284399113091721}. Best is trial 308 with value: 0.9498248152502544.
[I 2026-07-05 15:03:19,280] Trial 340 finished with value: 0.9497831868384689 and parameters: {'weight_class_0': 0.5359879724222276, 'weight_class_1': 9.01861481606012, 'weight_class_2': 6.446149070095956}. Best is trial 308 with value: 0.9498248152502544.
[I 2026-07-05 15:03:19,312] Trial 341 finished with value: 0.9497150351458764 and parameters: {'weight_class_0': 0.5462695659190638, 'weight_class_1': 8.910026933934256, 'weight_class_2': 7.191316690811222}. Best is trial 308 with value: 0.9498248152502544.
[I 2026-07-05 15:03:19,325] Trial 342 finished with value: 0.949596094927033 and parameters: {'weight_class_0': 0.4789092342922542, 'weight_class_1': 9.076785028609866, 'weight_class_2': 7.4362564877778246}. Best is trial 308 with value: 0.9498248152502544.
[I 2026-07-05 15:03:19,345] Trial 343 finished with value: 0.9496380063192733 and parameters: {'weight_class_0': 0.5270599620992575, 'weight_class_1': 8.994621053319092, 'weight_class_2': 7.547061857478362}. Best is trial 308 with value: 0.9498248152502544.
[I 2026-07-05 15:03:19,364] Trial 344 finished with value: 0.9498257267486765 and parameters: {'weight_class_0': 0.5716913582528771, 'weight_class_1': 8.954293263525779, 'weight_class_2': 6.472399374205131}. Best is trial 344 with value: 0.9498257267486765.
[I 2026-07-05 15:03:19,396] Trial 345 finished with value: 0.9497994248087221 and parameters: {'weight_class_0': 0.5471454751797314, 'weight_class_1': 8.954586542914774, 'weight_class_2': 6.446800227923148}. Best is trial 344 with value: 0.9498257267486765.
[I 2026-07-05 15:03:19,416] Trial 346 finished with value: 0.9498267655662881 and parameters: {'weight_class_0': 0.5404955463723516, 'weight_class_1': 8.88763124779615, 'weight_class_2': 6.461231892579734}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:19,430] Trial 347 finished with value: 0.9496949686404834 and parameters: {'weight_class_0': 0.5449898905021558, 'weight_class_1': 8.414169849548264, 'weight_class_2': 7.555149968618883}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:19,446] Trial 348 finished with value: 0.9497434978742043 and parameters: {'weight_class_0': 0.5181437585043354, 'weight_class_1': 8.44884426692085, 'weight_class_2': 6.472521779883045}. Best is trial 346 with value: 0.9498267655662881.

Best trial: 346. Best value: 0.949827:  36%|███████████████████████████████████████████████▍                                                                                    | 359/1000 [00:06<00:12, 51.24it/s]

[I 2026-07-05 15:03:19,460] Trial 349 finished with value: 0.9497792404984119 and parameters: {'weight_class_0': 0.5352940037579442, 'weight_class_1': 8.392264964655249, 'weight_class_2': 6.360154079276175}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:19,492] Trial 350 finished with value: 0.9497602409138013 and parameters: {'weight_class_0': 0.5115386981814597, 'weight_class_1': 8.409586533861152, 'weight_class_2': 6.456316438630943}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:19,497] Trial 352 finished with value: 0.9485654861204136 and parameters: {'weight_class_0': 0.28781625130342475, 'weight_class_1': 8.349742216285065, 'weight_class_2': 6.36904760946612}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:19,511] Trial 351 finished with value: 0.9488750228110727 and parameters: {'weight_class_0': 0.32585947180668484, 'weight_class_1': 8.403328306768039, 'weight_class_2': 6.49279147942274}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:19,527] Trial 353 finished with value: 0.9492379551658955 and parameters: {'weight_class_0': 0.34509948720280925, 'weight_class_1': 5.681423021284763, 'weight_class_2': 6.589883913422969}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:19,553] Trial 354 finished with value: 0.8888468552214124 and parameters: {'weight_class_0': 6.462235287601237, 'weight_class_1': 8.757035082780796, 'weight_class_2': 6.367890221599353}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:19,576] Trial 355 finished with value: 0.8901646960313091 and parameters: {'weight_class_0': 6.209124504571426, 'weight_class_1': 8.4063092125766, 'weight_class_2': 6.399714854959306}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:19,595] Trial 356 finished with value: 0.9485424449530889 and parameters: {'weight_class_0': 0.29712865344529366, 'weight_class_1': 8.753797595993461, 'weight_class_2': 6.606922387773771}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:19,625] Trial 357 finished with value: 0.9486311737897872 and parameters: {'weight_class_0': 0.30231810134304404, 'weight_class_1': 8.701201575333862, 'weight_class_2': 6.418282044894372}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:19,654] Trial 358 finished with value: 0.949128511261892 and parameters: {'weight_class_0': 0.3549156717249852, 'weight_class_1': 8.68002208995113, 'weight_class_2': 6.533382092225751}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:19,664] Trial 359 finished with value: 0.8897471897811625 and parameters: {'weight_class_0': 6.341188953714605, 'weight_class_1': 8.742356787842166, 'weight_class_2': 6.356898007724431}. Best is trial 346 with value: 0.9498267655662881.

Best trial: 346. Best value: 0.949827:  37%|████████████████████████████████████████████████▊                                                                                   | 370/1000 [00:07<00:12, 51.66it/s]

[I 2026-07-05 15:03:19,678] Trial 360 finished with value: 0.8779261505264234 and parameters: {'weight_class_0': 6.4796300551414365, 'weight_class_1': 5.847049182542325, 'weight_class_2': 6.456543087580362}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:19,680] Trial 361 finished with value: 0.9494663782599598 and parameters: {'weight_class_0': 0.744847770622578, 'weight_class_1': 8.74453523811239, 'weight_class_2': 6.195169009930258}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:19,727] Trial 362 finished with value: 0.8948112551195515 and parameters: {'weight_class_0': 5.714071863683669, 'weight_class_1': 8.735008909902366, 'weight_class_2': 6.2108144468274755}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:19,742] Trial 364 finished with value: 0.9496484026959818 and parameters: {'weight_class_0': 0.7193477460747116, 'weight_class_1': 8.75587589620587, 'weight_class_2': 6.661041387880126}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:19,759] Trial 363 finished with value: 0.9495588158481457 and parameters: {'weight_class_0': 0.7526969156067823, 'weight_class_1': 8.778285881092595, 'weight_class_2': 6.614228348916303}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:19,760] Trial 365 finished with value: 0.9494447389830937 and parameters: {'weight_class_0': 0.7400211825386375, 'weight_class_1': 7.784400224290369, 'weight_class_2': 6.204459281937617}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:19,805] Trial 366 finished with value: 0.9494295446594991 and parameters: {'weight_class_0': 0.742790430051346, 'weight_class_1': 7.788360407497198, 'weight_class_2': 6.180490513205115}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:19,816] Trial 367 finished with value: 0.9494542543882489 and parameters: {'weight_class_0': 0.7384514732822319, 'weight_class_1': 8.763500649517939, 'weight_class_2': 6.126121567302189}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:19,838] Trial 368 finished with value: 0.9494846761322235 and parameters: {'weight_class_0': 0.7421493931647554, 'weight_class_1': 8.872221992596488, 'weight_class_2': 6.170639115589806}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:19,867] Trial 369 finished with value: 0.94938779783373 and parameters: {'weight_class_0': 0.751449606203853, 'weight_class_1': 8.467911350666602, 'weight_class_2': 6.148037958484055}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:19,879] Trial 370 finished with value: 0.8802125813815768 and parameters: {'weight_class_0': 7.329645703716869, 'weight_class_1': 8.491256082554063, 'weight_class_2': 6.112944895693036}. Best is trial 346 with value: 0.9498267655662881.

Best trial: 346. Best value: 0.949827:  38%|██████████████████████████████████████████████████▌                                                                                 | 383/1000 [00:07<00:11, 53.80it/s]

[I 2026-07-05 15:03:19,894] Trial 371 finished with value: 0.8825680020694783 and parameters: {'weight_class_0': 7.348389202783504, 'weight_class_1': 8.524729728604077, 'weight_class_2': 6.75491130891929}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:19,900] Trial 372 finished with value: 0.9495769996832607 and parameters: {'weight_class_0': 0.7393061620191079, 'weight_class_1': 8.411634907609304, 'weight_class_2': 6.716400052597604}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:19,946] Trial 373 finished with value: 0.9496518037329927 and parameters: {'weight_class_0': 0.709470814042805, 'weight_class_1': 8.469148395564911, 'weight_class_2': 6.726276344866079}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:19,964] Trial 374 finished with value: 0.949582164359786 and parameters: {'weight_class_0': 0.7003493034101668, 'weight_class_1': 8.395707684611445, 'weight_class_2': 6.133048441823509}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:19,979] Trial 375 finished with value: 0.9497258216011506 and parameters: {'weight_class_0': 0.5001406376972688, 'weight_class_1': 8.517033264569342, 'weight_class_2': 4.820138027082743}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:19,993] Trial 376 finished with value: 0.9484863460193589 and parameters: {'weight_class_0': 0.2425572533394681, 'weight_class_1': 8.45206695758729, 'weight_class_2': 4.7487469117134475}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:19,997] Trial 377 finished with value: 0.9477999275175212 and parameters: {'weight_class_0': 0.2335414733233373, 'weight_class_1': 8.217871750722793, 'weight_class_2': 6.701649350425191}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:20,035] Trial 378 finished with value: 0.9475445614643762 and parameters: {'weight_class_0': 0.22795904509654435, 'weight_class_1': 8.477887716167345, 'weight_class_2': 6.751387568154414}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:20,037] Trial 380 finished with value: 0.9479349854833199 and parameters: {'weight_class_0': 0.24225072732326236, 'weight_class_1': 8.951278190806011, 'weight_class_2': 5.794391575166308}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:20,049] Trial 379 finished with value: 0.9481093208135558 and parameters: {'weight_class_0': 0.25356950346892054, 'weight_class_1': 8.281940577707243, 'weight_class_2': 6.7350745632979745}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:20,090] Trial 382 finished with value: 0.9484697131748044 and parameters: {'weight_class_0': 0.24245683897037779, 'weight_class_1': 8.24082060030031, 'weight_class_2': 4.793612430456375}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:20,106] Trial 381 finished with value: 0.9497022232265865 and parameters: {'weight_class_0': 0.47407133003356206, 'weight_class_1': 8.280786770006175, 'weight_class_2': 5.83973332519642}. Best is trial 346 with value: 0.9498267655662881.

Best trial: 346. Best value: 0.949827:  39%|███████████████████████████████████████████████████▉                                                                                | 393/1000 [00:07<00:11, 52.16it/s]

[I 2026-07-05 15:03:20,122] Trial 383 finished with value: 0.9497452494242121 and parameters: {'weight_class_0': 0.47936209668958035, 'weight_class_1': 8.24650625554609, 'weight_class_2': 4.778315145800626}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:20,137] Trial 384 finished with value: 0.9485135905140151 and parameters: {'weight_class_0': 0.24435157711707672, 'weight_class_1': 8.232516980335589, 'weight_class_2': 4.8088466216031485}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:20,160] Trial 385 finished with value: 0.9471879240577717 and parameters: {'weight_class_0': 1.3347517142103962, 'weight_class_1': 9.014682402080211, 'weight_class_2': 6.99055867578756}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:20,206] Trial 386 finished with value: 0.9486734117754426 and parameters: {'weight_class_0': 1.0191945242351514, 'weight_class_1': 8.986346051872072, 'weight_class_2': 7.004954728247864}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:20,207] Trial 387 finished with value: 0.9470716562703746 and parameters: {'weight_class_0': 1.0829624609463728, 'weight_class_1': 8.973386371844539, 'weight_class_2': 5.211381315269662}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:20,226] Trial 388 finished with value: 0.949612067279884 and parameters: {'weight_class_0': 0.46600159818494685, 'weight_class_1': 9.051741744112173, 'weight_class_2': 6.9946090474877325}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:20,247] Trial 390 finished with value: 0.949818172741375 and parameters: {'weight_class_0': 0.4709420201406231, 'weight_class_1': 8.93678597489311, 'weight_class_2': 5.216250650537108}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:20,255] Trial 389 finished with value: 0.9475759991775217 and parameters: {'weight_class_0': 1.024706128213184, 'weight_class_1': 8.991516042953599, 'weight_class_2': 5.186534916402674}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:20,271] Trial 391 finished with value: 0.9472843462584014 and parameters: {'weight_class_0': 1.0486288959196572, 'weight_class_1': 8.98738389020918, 'weight_class_2': 5.099069677225487}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:20,289] Trial 392 finished with value: 0.9485885272076171 and parameters: {'weight_class_0': 1.0334313683597953, 'weight_class_1': 8.913066136218015, 'weight_class_2': 7.010235339146855}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:20,305] Trial 393 finished with value: 0.9485810016403354 and parameters: {'weight_class_0': 1.0380770744248198, 'weight_class_1': 9.02333179319346, 'weight_class_2': 7.037735122376766}. Best is trial 346 with value: 0.9498267655662881.

Best trial: 402. Best value: 0.949837:  40%|█████████████████████████████████████████████████████▍                                                                              | 405/1000 [00:07<00:10, 54.37it/s]

[I 2026-07-05 15:03:20,328] Trial 394 finished with value: 0.9470371003457488 and parameters: {'weight_class_0': 1.0482693739031754, 'weight_class_1': 7.954080991438332, 'weight_class_2': 5.1204168458084975}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:20,337] Trial 395 finished with value: 0.9474247088518645 and parameters: {'weight_class_0': 1.029842566023416, 'weight_class_1': 7.980750743262371, 'weight_class_2': 5.249669550647264}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:20,369] Trial 396 finished with value: 0.9478849758106289 and parameters: {'weight_class_0': 0.9837231331593044, 'weight_class_1': 8.93264019852241, 'weight_class_2': 5.28950372253338}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:20,391] Trial 398 finished with value: 0.9497082207149835 and parameters: {'weight_class_0': 0.5478618098436331, 'weight_class_1': 8.895574559853078, 'weight_class_2': 5.360715539556081}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:20,394] Trial 397 finished with value: 0.9497820640245881 and parameters: {'weight_class_0': 0.48288596505992887, 'weight_class_1': 8.896126685937796, 'weight_class_2': 5.3692758620113805}. Best is trial 346 with value: 0.9498267655662881.
[I 2026-07-05 15:03:20,420] Trial 399 finished with value: 0.9498285361038148 and parameters: {'weight_class_0': 0.49353684040035384, 'weight_class_1': 7.989012733779929, 'weight_class_2': 5.439069477986693}. Best is trial 399 with value: 0.9498285361038148.
[I 2026-07-05 15:03:20,455] Trial 400 finished with value: 0.9498026148053528 and parameters: {'weight_class_0': 0.516704486739393, 'weight_class_1': 7.945219220040726, 'weight_class_2': 5.47502361885423}. Best is trial 399 with value: 0.9498285361038148.
[I 2026-07-05 15:03:20,467] Trial 401 finished with value: 0.949813652049186 and parameters: {'weight_class_0': 0.5282688293909519, 'weight_class_1': 8.657973675563216, 'weight_class_2': 5.515142476615177}. Best is trial 399 with value: 0.9498285361038148.
[I 2026-07-05 15:03:20,479] Trial 402 finished with value: 0.9498372606373188 and parameters: {'weight_class_0': 0.49846939011193386, 'weight_class_1': 7.967955322107089, 'weight_class_2': 5.3793125145298095}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:20,500] Trial 403 finished with value: 0.9497499563894477 and parameters: {'weight_class_0': 0.48741002743755757, 'weight_class_1': 8.665077337519593, 'weight_class_2': 5.455866944489517}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:20,510] Trial 404 finished with value: 0.9497911508495909 and parameters: {'weight_class_0': 0.51913700491922, 'weight_class_1': 8.620996510991894, 'weight_class_2': 5.430520911471632}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:20,523] Trial 405 finished with value: 0.9497852269383008 and parameters: {'weight_class_0': 0.5210720790784586, 'weight_class_1': 8.687845679156073, 'weight_class_2': 5.437344427606161}. Best is trial 402 with value: 0.9498372606373188.

[I 2026-07-05 15:03:20,573] Trial 406 finished with value: 0.9496394134137923 and parameters: {'weight_class_0': 0.4306630797338388, 'weight_class_1': 8.71702875084962, 'weight_class_2': 5.463764054468011}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:20,583] Trial 408 finished with value: 0.9497415241450774 and parameters: {'weight_class_0': 0.45774159195092445, 'weight_class_1': 8.59263266271241, 'weight_class_2': 5.4917154868470215}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:20,603] Trial 409 finished with value: 0.9496913038209823 and parameters: {'weight_class_0': 0.41310128108031946, 'weight_class_1': 7.994754382720494, 'weight_class_2': 5.515450348018277}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:20,607] Trial 407 finished with value: 0.9496566179942186 and parameters: {'weight_class_0': 0.4139016415855076, 'weight_class_1': 8.658250364602168, 'weight_class_2': 5.5293697144071805}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:20,622] Trial 410 finished with value: 0.9496906209726118 and parameters: {'weight_class_0': 0.4399531695672728, 'weight_class_1': 7.954578687649864, 'weight_class_2': 5.518103909782027}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:20,658] Trial 411 finished with value: 0.9496896238408876 and parameters: {'weight_class_0': 0.40510545832574874, 'weight_class_1': 7.853233093769745, 'weight_class_2': 5.603478709505476}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:20,684] Trial 412 finished with value: 0.9493117888709972 and parameters: {'weight_class_0': 0.33324260901530667, 'weight_class_1': 7.758408464935624, 'weight_class_2': 5.458625101644466}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:20,699] Trial 413 finished with value: 0.9495228959642122 and parameters: {'weight_class_0': 0.37651857786891213, 'weight_class_1': 8.041882942304465, 'weight_class_2': 5.618627990559528}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:20,714] Trial 414 finished with value: 0.9492508955322766 and parameters: {'weight_class_0': 0.32137391080754407, 'weight_class_1': 7.490318750574219, 'weight_class_2': 5.662387925115902}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:20,717] Trial 415 finished with value: 0.9496427349008538 and parameters: {'weight_class_0': 0.3902587669032721, 'weight_class_1': 7.519261940137596, 'weight_class_2': 5.620105313569837}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:20,735] Trial 416 finished with value: 0.9495460472237826 and parameters: {'weight_class_0': 0.36645382503167684, 'weight_class_1': 7.793275101057524, 'weight_class_2': 5.595142145269166}. Best is trial 402 with value: 0.9498372606373188.

Best trial: 402. Best value: 0.949837:  43%|████████████████████████████████████████████████████████▍                                                                           | 428/1000 [00:08<00:10, 53.70it/s]

[I 2026-07-05 15:03:20,757] Trial 417 finished with value: 0.9494625755872099 and parameters: {'weight_class_0': 0.35120125682904757, 'weight_class_1': 7.80318963272058, 'weight_class_2': 5.599191156266142}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:20,778] Trial 418 finished with value: 0.9455570744676632 and parameters: {'weight_class_0': 0.17960956570201542, 'weight_class_1': 7.834264049755424, 'weight_class_2': 9.438536740335064}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:20,794] Trial 419 finished with value: 0.9457707113997932 and parameters: {'weight_class_0': 0.1513963039967477, 'weight_class_1': 7.816432414319167, 'weight_class_2': 5.767524748198595}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:20,809] Trial 420 finished with value: 0.9452502426141184 and parameters: {'weight_class_0': 0.13819694275408728, 'weight_class_1': 7.596875072917188, 'weight_class_2': 5.68188616026719}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:20,832] Trial 421 finished with value: 0.9476601302015641 and parameters: {'weight_class_0': 0.21166403008191914, 'weight_class_1': 8.058849465822744, 'weight_class_2': 5.798648996940145}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:20,837] Trial 422 finished with value: 0.9474312889919214 and parameters: {'weight_class_0': 0.19637908806209226, 'weight_class_1': 7.683126798367889, 'weight_class_2': 5.731374491253458}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:20,860] Trial 423 finished with value: 0.9476645340757767 and parameters: {'weight_class_0': 0.20645586813208122, 'weight_class_1': 7.6828491957992116, 'weight_class_2': 5.773540443551777}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:20,890] Trial 425 finished with value: 0.9457545837273789 and parameters: {'weight_class_0': 0.1485477383192278, 'weight_class_1': 7.572559880164796, 'weight_class_2': 5.876599550289314}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:20,909] Trial 424 finished with value: 0.9471938422795384 and parameters: {'weight_class_0': 0.1956515686830575, 'weight_class_1': 8.103016381214976, 'weight_class_2': 5.884489494588751}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:20,933] Trial 426 finished with value: 0.9469560996748206 and parameters: {'weight_class_0': 0.1713312292889974, 'weight_class_1': 7.616458526332632, 'weight_class_2': 5.044619545729455}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:20,945] Trial 427 finished with value: 0.9449944963306679 and parameters: {'weight_class_0': 0.14031517630465362, 'weight_class_1': 7.9833741446373185, 'weight_class_2': 5.841671357336763}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:20,955] Trial 428 finished with value: 0.948879011098598 and parameters: {'weight_class_0': 0.83156316411095, 'weight_class_1': 8.803325858309119, 'weight_class_2': 5.871463128034323}. Best is trial 402 with value: 0.9498372606373188.

[I 2026-07-05 15:03:20,972] Trial 429 finished with value: 0.9491094989116192 and parameters: {'weight_class_0': 0.7670771946392985, 'weight_class_1': 7.245826091132713, 'weight_class_2': 5.895434742803083}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,000] Trial 431 finished with value: 0.9482029317517275 and parameters: {'weight_class_0': 0.8407297830703513, 'weight_class_1': 8.11604936369321, 'weight_class_2': 5.058377295462275}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,017] Trial 430 finished with value: 0.9482803435894639 and parameters: {'weight_class_0': 0.8116724742643552, 'weight_class_1': 8.191558248221227, 'weight_class_2': 4.990856903202257}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,026] Trial 432 finished with value: 0.9482948850312298 and parameters: {'weight_class_0': 0.8130874574763649, 'weight_class_1': 8.099732425403017, 'weight_class_2': 5.069769089604635}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,048] Trial 433 finished with value: 0.944760172483952 and parameters: {'weight_class_0': 0.8361228389024615, 'weight_class_1': 3.4142484891634393, 'weight_class_2': 5.063349198132277}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,067] Trial 434 finished with value: 0.9482407886083483 and parameters: {'weight_class_0': 0.8139193385511552, 'weight_class_1': 8.105492026156183, 'weight_class_2': 4.974237714169041}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,091] Trial 435 finished with value: 0.9483560612476083 and parameters: {'weight_class_0': 0.8260477872711676, 'weight_class_1': 8.778737836631123, 'weight_class_2': 5.047429283357344}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,114] Trial 437 finished with value: 0.9064905928616147 and parameters: {'weight_class_0': 0.662053503449157, 'weight_class_1': 0.4181503124560422, 'weight_class_2': 5.027416396214935}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,134] Trial 436 finished with value: 0.9492364942593433 and parameters: {'weight_class_0': 0.636208092054007, 'weight_class_1': 8.203610808079489, 'weight_class_2': 5.070720262784825}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,164] Trial 439 finished with value: 0.9494974487068074 and parameters: {'weight_class_0': 0.6041828456138987, 'weight_class_1': 8.596209242483768, 'weight_class_2': 4.977677621156588}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,165] Trial 438 finished with value: 0.8935046047630871 and parameters: {'weight_class_0': 3.3625579329870856, 'weight_class_1': 3.311726110258552, 'weight_class_2': 5.073158435303249}. Best is trial 402 with value: 0.9498372606373188.

[I 2026-07-05 15:03:21,175] Trial 440 finished with value: 0.9481191290917176 and parameters: {'weight_class_0': 0.5719504699375534, 'weight_class_1': 3.360710422066624, 'weight_class_2': 5.325810084182939}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,216] Trial 441 finished with value: 0.9495822990547979 and parameters: {'weight_class_0': 0.6152873389100263, 'weight_class_1': 8.579677045861528, 'weight_class_2': 5.371951176180353}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,248] Trial 443 finished with value: 0.9496080547047651 and parameters: {'weight_class_0': 0.6076187388584058, 'weight_class_1': 8.55924788182223, 'weight_class_2': 5.346928359864378}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,249] Trial 442 finished with value: 0.9496524288533523 and parameters: {'weight_class_0': 0.6365046383614741, 'weight_class_1': 8.56765120150073, 'weight_class_2': 6.019837518717607}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,272] Trial 445 finished with value: 0.9068558200420176 and parameters: {'weight_class_0': 0.6051419630544578, 'weight_class_1': 0.38131587663627364, 'weight_class_2': 5.275803734827561}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,277] Trial 444 finished with value: 0.9494389959115891 and parameters: {'weight_class_0': 0.6405182188457997, 'weight_class_1': 8.557089361811435, 'weight_class_2': 5.282692138855425}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,287] Trial 446 finished with value: 0.9497167793943991 and parameters: {'weight_class_0': 0.5491555759768518, 'weight_class_1': 8.646702008170697, 'weight_class_2': 5.329048114633643}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,302] Trial 447 finished with value: 0.9495243314938987 and parameters: {'weight_class_0': 0.6046895318451927, 'weight_class_1': 8.633990905651793, 'weight_class_2': 9.2355145132314}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,354] Trial 449 finished with value: 0.9072710930273226 and parameters: {'weight_class_0': 4.252135388179922, 'weight_class_1': 9.184429978036608, 'weight_class_2': 5.340707854968273}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,361] Trial 448 finished with value: 0.949658684814521 and parameters: {'weight_class_0': 0.584075994360166, 'weight_class_1': 9.167637790631627, 'weight_class_2': 5.2855249060394485}. Best is trial 402 with value: 0.9498372606373188.

Best trial: 402. Best value: 0.949837:  46%|████████████████████████████████████████████████████████████▊                                                                       | 461/1000 [00:08<00:10, 53.83it/s]

[I 2026-07-05 15:03:21,386] Trial 450 finished with value: 0.9497473702872732 and parameters: {'weight_class_0': 0.5440103595934379, 'weight_class_1': 8.517567809486728, 'weight_class_2': 5.349402013161443}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,390] Trial 451 finished with value: 0.8707102758384004 and parameters: {'weight_class_0': 8.904526741946007, 'weight_class_1': 9.18681300474578, 'weight_class_2': 5.459850215378632}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,435] Trial 452 finished with value: 0.9494020042729737 and parameters: {'weight_class_0': 0.5835420179257697, 'weight_class_1': 9.113748386072128, 'weight_class_2': 9.873876103747808}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,444] Trial 453 finished with value: 0.9448677265606696 and parameters: {'weight_class_0': 1.3807700141273407, 'weight_class_1': 9.17439900076235, 'weight_class_2': 5.363567436562213}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,451] Trial 455 finished with value: 0.6890489688214526 and parameters: {'weight_class_0': 0.010172295509811247, 'weight_class_1': 8.833930350029204, 'weight_class_2': 6.350349635879397}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,464] Trial 454 finished with value: 0.9484075264263758 and parameters: {'weight_class_0': 1.2730820593121606, 'weight_class_1': 9.184260793996279, 'weight_class_2': 9.192808167206381}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,492] Trial 456 finished with value: 0.9473638450762133 and parameters: {'weight_class_0': 1.2396105272211835, 'weight_class_1': 9.096737798292509, 'weight_class_2': 6.426071715379611}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,505] Trial 457 finished with value: 0.9494380700418539 and parameters: {'weight_class_0': 0.40514309790058345, 'weight_class_1': 9.140550283512452, 'weight_class_2': 6.351901995174007}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,519] Trial 458 finished with value: 0.6577399050601858 and parameters: {'weight_class_0': 0.0004869871674709758, 'weight_class_1': 9.176921716520162, 'weight_class_2': 5.5073819989951875}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,533] Trial 459 finished with value: 0.9469199496596646 and parameters: {'weight_class_0': 1.2914873938980955, 'weight_class_1': 8.908603334744486, 'weight_class_2': 6.402455542480248}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,559] Trial 460 finished with value: 0.9489935744701589 and parameters: {'weight_class_0': 0.3263847478727237, 'weight_class_1': 8.847904178143487, 'weight_class_2': 5.976345058540184}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,587] Trial 461 finished with value: 0.8874348819655999 and parameters: {'weight_class_0': 1.3749626881784653, 'weight_class_1': 8.865774636934132, 'weight_class_2': 0.1363518596095048}. Best is trial 402 with value: 0.9498372606373188.

[I 2026-07-05 15:03:21,609] Trial 462 finished with value: 0.6771111499020369 and parameters: {'weight_class_0': 0.008332078091284945, 'weight_class_1': 8.79226023218505, 'weight_class_2': 6.321313606938417}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,622] Trial 463 finished with value: 0.94934414397914 and parameters: {'weight_class_0': 0.37334635196491794, 'weight_class_1': 8.836374122842647, 'weight_class_2': 5.973248674353562}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,665] Trial 464 finished with value: 0.9495389381756064 and parameters: {'weight_class_0': 0.40562915258989796, 'weight_class_1': 8.315696603468561, 'weight_class_2': 6.408921905186419}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,671] Trial 465 finished with value: 0.9494071742181923 and parameters: {'weight_class_0': 0.40124977911523607, 'weight_class_1': 4.990810476045424, 'weight_class_2': 6.0151155322288945}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,683] Trial 466 finished with value: 0.9487189040575382 and parameters: {'weight_class_0': 0.8920639766415129, 'weight_class_1': 9.451203224200114, 'weight_class_2': 6.059136836942093}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,687] Trial 467 finished with value: 0.9486732679078603 and parameters: {'weight_class_0': 0.8940465702040405, 'weight_class_1': 8.31052218259808, 'weight_class_2': 6.0067872994762705}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,710] Trial 468 finished with value: 0.9486802821863375 and parameters: {'weight_class_0': 0.8926784738440668, 'weight_class_1': 8.307199887925872, 'weight_class_2': 5.972194004297641}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,744] Trial 469 finished with value: 0.9488351345407352 and parameters: {'weight_class_0': 0.8449362708439535, 'weight_class_1': 8.302080997528382, 'weight_class_2': 5.983019602221928}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,760] Trial 470 finished with value: 0.9486720282349775 and parameters: {'weight_class_0': 0.8909154079970708, 'weight_class_1': 8.246294097076689, 'weight_class_2': 6.0135656250599805}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,769] Trial 471 finished with value: 0.9484309534725647 and parameters: {'weight_class_0': 0.940941616847055, 'weight_class_1': 8.373778189741008, 'weight_class_2': 6.020244250466637}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,799] Trial 472 finished with value: 0.9483107782453182 and parameters: {'weight_class_0': 0.9127473890043359, 'weight_class_1': 8.334348737459349, 'weight_class_2': 5.634823764625597}. Best is trial 402 with value: 0.9498372606373188.

Best trial: 402. Best value: 0.949837:  48%|███████████████████████████████████████████████████████████████▊                                                                    | 483/1000 [00:09<00:09, 51.98it/s]

[I 2026-07-05 15:03:21,810] Trial 473 finished with value: 0.9483742701251354 and parameters: {'weight_class_0': 0.8860787620720313, 'weight_class_1': 8.306366514643763, 'weight_class_2': 5.596344024513602}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,841] Trial 474 finished with value: 0.9487227073113607 and parameters: {'weight_class_0': 0.8583540674410349, 'weight_class_1': 9.461801316753167, 'weight_class_2': 5.735446581010161}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,853] Trial 475 finished with value: 0.9484683940489855 and parameters: {'weight_class_0': 0.8882906063593138, 'weight_class_1': 9.390838228491953, 'weight_class_2': 5.641845760743824}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,854] Trial 476 finished with value: 0.9489648766532276 and parameters: {'weight_class_0': 0.7851625888301914, 'weight_class_1': 9.502113090105794, 'weight_class_2': 5.6689000038135235}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,886] Trial 477 finished with value: 0.9490408483739969 and parameters: {'weight_class_0': 0.770496096958586, 'weight_class_1': 9.423442351133685, 'weight_class_2': 5.643715423146963}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,912] Trial 478 finished with value: 0.8677113386017578 and parameters: {'weight_class_0': 9.811362579610178, 'weight_class_1': 9.406779077243481, 'weight_class_2': 5.697352821895023}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,930] Trial 479 finished with value: 0.9495627718516152 and parameters: {'weight_class_0': 0.4232054677523753, 'weight_class_1': 9.48222360439461, 'weight_class_2': 5.682089357852726}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,953] Trial 480 finished with value: 0.9495728672192975 and parameters: {'weight_class_0': 0.43538121028559895, 'weight_class_1': 9.490652664891797, 'weight_class_2': 5.651888894855528}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,956] Trial 481 finished with value: 0.9495526810045899 and parameters: {'weight_class_0': 0.4196364840407609, 'weight_class_1': 9.489520571761739, 'weight_class_2': 5.657867083141683}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,975] Trial 482 finished with value: 0.9495519122840124 and parameters: {'weight_class_0': 0.4458013939483071, 'weight_class_1': 9.445838324022931, 'weight_class_2': 6.603128169362236}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:21,993] Trial 483 finished with value: 0.9494043529352538 and parameters: {'weight_class_0': 0.4164678534812753, 'weight_class_1': 9.452308590468768, 'weight_class_2': 6.598720076289282}. Best is trial 402 with value: 0.9498372606373188.

Best trial: 402. Best value: 0.949837:  50%|█████████████████████████████████████████████████████████████████▎                                                                  | 495/1000 [00:09<00:09, 51.93it/s]

[I 2026-07-05 15:03:22,011] Trial 484 finished with value: 0.9497650004614311 and parameters: {'weight_class_0': 0.45706270012114725, 'weight_class_1': 8.718502614444903, 'weight_class_2': 4.623707860732643}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,031] Trial 485 finished with value: 0.949788030991434 and parameters: {'weight_class_0': 0.4483974118246953, 'weight_class_1': 8.702372151510465, 'weight_class_2': 4.650279330801794}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,044] Trial 486 finished with value: 0.9497076283009683 and parameters: {'weight_class_0': 0.4801373940338091, 'weight_class_1': 8.664675595841771, 'weight_class_2': 6.541714220837064}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,085] Trial 487 finished with value: 0.9495918491942371 and parameters: {'weight_class_0': 0.4384934485172719, 'weight_class_1': 8.754913423292397, 'weight_class_2': 6.6104480020903305}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,094] Trial 488 finished with value: 0.9496668969158909 and parameters: {'weight_class_0': 0.4784663525866768, 'weight_class_1': 8.713637122320378, 'weight_class_2': 6.628915955754908}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,119] Trial 489 finished with value: 0.9496658624133433 and parameters: {'weight_class_0': 0.4946442061962056, 'weight_class_1': 8.748077206063568, 'weight_class_2': 6.5314026213241325}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,130] Trial 490 finished with value: 0.9486604075465627 and parameters: {'weight_class_0': 0.2533454198146089, 'weight_class_1': 8.643474010486827, 'weight_class_2': 4.614836009895116}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,148] Trial 491 finished with value: 0.9483874466211185 and parameters: {'weight_class_0': 0.25594397793364987, 'weight_class_1': 8.714838258027264, 'weight_class_2': 5.1735008741818485}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,163] Trial 492 finished with value: 0.9493151033644982 and parameters: {'weight_class_0': 0.6461338917634294, 'weight_class_1': 8.736988834009754, 'weight_class_2': 5.193211024168768}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,181] Trial 493 finished with value: 0.9479532955889124 and parameters: {'weight_class_0': 0.23730828930145353, 'weight_class_1': 8.850692749053133, 'weight_class_2': 5.430253782293956}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,184] Trial 494 finished with value: 0.9492068140502322 and parameters: {'weight_class_0': 0.6599846685301438, 'weight_class_1': 8.835896780670435, 'weight_class_2': 5.167868900008962}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,210] Trial 495 finished with value: 0.9481833412028907 and parameters: {'weight_class_0': 0.22461634882362536, 'weight_class_1': 8.483915822590179, 'weight_class_2': 4.4364235308914495}. Best is trial 402 with value: 0.9498372606373188.

Best trial: 402. Best value: 0.949837:  51%|██████████████████████████████████████████████████████████████████▊                                                                 | 506/1000 [00:09<00:09, 52.77it/s]

[I 2026-07-05 15:03:22,251] Trial 496 finished with value: 0.9479015995091422 and parameters: {'weight_class_0': 0.21577212749698205, 'weight_class_1': 8.504144363906105, 'weight_class_2': 4.587590354019344}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,275] Trial 497 finished with value: 0.9474751553236493 and parameters: {'weight_class_0': 0.20513702812212292, 'weight_class_1': 8.436574380292102, 'weight_class_2': 5.243931822375584}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,281] Trial 498 finished with value: 0.9473643704853862 and parameters: {'weight_class_0': 0.2130241998612182, 'weight_class_1': 8.477992943528887, 'weight_class_2': 6.2714089957530925}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,305] Trial 499 finished with value: 0.947079557661203 and parameters: {'weight_class_0': 0.1810713876785659, 'weight_class_1': 7.94796868875379, 'weight_class_2': 5.19038459330348}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,322] Trial 500 finished with value: 0.9486907041990967 and parameters: {'weight_class_0': 0.6796320769390145, 'weight_class_1': 7.978251983229035, 'weight_class_2': 4.414783177773028}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,350] Trial 501 finished with value: 0.9482822946926291 and parameters: {'weight_class_0': 0.18875067398590695, 'weight_class_1': 6.228050924106542, 'weight_class_2': 4.491787919145327}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,379] Trial 503 finished with value: 0.9478337244336602 and parameters: {'weight_class_0': 0.6917276603938933, 'weight_class_1': 4.362073255124451, 'weight_class_2': 4.823017425950362}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,387] Trial 502 finished with value: 0.9472828447880124 and parameters: {'weight_class_0': 0.19103288462429469, 'weight_class_1': 8.47366752294286, 'weight_class_2': 4.798625308340451}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,421] Trial 504 finished with value: 0.949604091371817 and parameters: {'weight_class_0': 0.6902676423659609, 'weight_class_1': 8.061591461668069, 'weight_class_2': 6.309876730003959}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,429] Trial 506 finished with value: 0.9492835031475969 and parameters: {'weight_class_0': 0.7060165824444081, 'weight_class_1': 9.801957799389081, 'weight_class_2': 5.42802365000567}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,436] Trial 507 finished with value: 0.9496050670233043 and parameters: {'weight_class_0': 0.6675381001703228, 'weight_class_1': 7.950902894446913, 'weight_class_2': 6.2077133869353025}. Best is trial 402 with value: 0.9498372606373188.

Best trial: 402. Best value: 0.949837:  52%|████████████████████████████████████████████████████████████████████▏                                                               | 517/1000 [00:09<00:09, 53.57it/s]

[I 2026-07-05 15:03:22,440] Trial 505 finished with value: 0.9489705079669942 and parameters: {'weight_class_0': 0.651707090457029, 'weight_class_1': 8.017037082430619, 'weight_class_2': 4.7338173266451875}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,456] Trial 508 finished with value: 0.9495581932412493 and parameters: {'weight_class_0': 0.6935922347502139, 'weight_class_1': 7.959889653795364, 'weight_class_2': 6.240264657282057}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,502] Trial 509 finished with value: 0.9463891187499623 and parameters: {'weight_class_0': 1.1110089926137556, 'weight_class_1': 8.97692987003818, 'weight_class_2': 4.892804375997823}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,519] Trial 510 finished with value: 0.9489545090785206 and parameters: {'weight_class_0': 0.6722304205394085, 'weight_class_1': 9.041970957532799, 'weight_class_2': 4.794054805136246}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,523] Trial 511 finished with value: 0.9489339610862976 and parameters: {'weight_class_0': 0.6796562945154041, 'weight_class_1': 8.99497464414234, 'weight_class_2': 4.855732865421659}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,549] Trial 512 finished with value: 0.9462426165070377 and parameters: {'weight_class_0': 1.1073760123372391, 'weight_class_1': 8.97438772340646, 'weight_class_2': 4.780895785754675}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,575] Trial 513 finished with value: 0.9469225632323366 and parameters: {'weight_class_0': 1.0791048413027715, 'weight_class_1': 9.756881546339542, 'weight_class_2': 4.897457871583453}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,581] Trial 514 finished with value: 0.9490645328060813 and parameters: {'weight_class_0': 0.6641641581352892, 'weight_class_1': 8.95226068603099, 'weight_class_2': 4.885998626641154}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,625] Trial 517 finished with value: 0.9470870649701862 and parameters: {'weight_class_0': 1.1174336674236407, 'weight_class_1': 9.17120039498133, 'weight_class_2': 5.414725088958946}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,633] Trial 515 finished with value: 0.9460098683763812 and parameters: {'weight_class_0': 1.1714230781334762, 'weight_class_1': 8.998365156961118, 'weight_class_2': 4.931028148288217}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,642] Trial 516 finished with value: 0.9485914979989832 and parameters: {'weight_class_0': 1.0179181867232052, 'weight_class_1': 8.937270470584986, 'weight_class_2': 6.768156975268433}. Best is trial 402 with value: 0.9498372606373188.

[I 2026-07-05 15:03:22,676] Trial 518 finished with value: 0.9481000586916073 and parameters: {'weight_class_0': 1.100737350248645, 'weight_class_1': 8.94978937558594, 'weight_class_2': 6.770730709518862}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,683] Trial 519 finished with value: 0.9466159403530687 and parameters: {'weight_class_0': 1.0950438826656077, 'weight_class_1': 9.031210872808337, 'weight_class_2': 4.905737907581294}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,703] Trial 520 finished with value: 0.9497981751486096 and parameters: {'weight_class_0': 0.4903820370466192, 'weight_class_1': 9.206392162222821, 'weight_class_2': 5.433072121821495}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,748] Trial 523 finished with value: 0.6673884595726626 and parameters: {'weight_class_0': 0.0068404450125557625, 'weight_class_1': 9.278041225108735, 'weight_class_2': 6.678263801174003}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,757] Trial 522 finished with value: 0.8136460021312288 and parameters: {'weight_class_0': 0.027074052390094194, 'weight_class_1': 9.792252371941627, 'weight_class_2': 5.434877702608148}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,759] Trial 521 finished with value: 0.9474835439178938 and parameters: {'weight_class_0': 1.0845421483742501, 'weight_class_1': 9.288394939944771, 'weight_class_2': 5.410452475651041}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,776] Trial 524 finished with value: 0.7463550344212795 and parameters: {'weight_class_0': 0.020057009878700016, 'weight_class_1': 9.133710470775993, 'weight_class_2': 8.630124282261592}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,792] Trial 526 finished with value: 0.9493048193468798 and parameters: {'weight_class_0': 0.3653850879060692, 'weight_class_1': 9.197854668608208, 'weight_class_2': 5.423621708088538}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,801] Trial 525 finished with value: 0.9496743390626579 and parameters: {'weight_class_0': 0.4778533294705932, 'weight_class_1': 9.21471656776561, 'weight_class_2': 6.782596272470173}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,842] Trial 527 finished with value: 0.949287835321106 and parameters: {'weight_class_0': 0.39378072759573424, 'weight_class_1': 9.258921283044193, 'weight_class_2': 6.477226413355687}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,853] Trial 528 finished with value: 0.949466506160222 and parameters: {'weight_class_0': 0.40169464700206325, 'weight_class_1': 8.195138448662348, 'weight_class_2': 6.690481013084797}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,875] Trial 529 finished with value: 0.9494017143993595 and parameters: {'weight_class_0': 0.3796613405957948, 'weight_class_1': 9.695914029687984, 'weight_class_2': 5.436508285429925}. Best is trial 402 with value: 0.9498372606373188.

Best trial: 402. Best value: 0.949837:  54%|███████████████████████████████████████████████████████████████████████▎                                                            | 540/1000 [00:10<00:08, 53.92it/s]

[I 2026-07-05 15:03:22,882] Trial 530 finished with value: 0.7986490802208914 and parameters: {'weight_class_0': 0.02225399340514833, 'weight_class_1': 8.528422817052757, 'weight_class_2': 5.331912905881668}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,900] Trial 531 finished with value: 0.9496677458239433 and parameters: {'weight_class_0': 0.37734380331348816, 'weight_class_1': 7.005508804089155, 'weight_class_2': 5.346068520586815}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,921] Trial 532 finished with value: 0.9496839769989812 and parameters: {'weight_class_0': 0.40136023457258907, 'weight_class_1': 8.17933019468174, 'weight_class_2': 5.42467993258631}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,956] Trial 534 finished with value: 0.8747388568805285 and parameters: {'weight_class_0': 7.63654021330651, 'weight_class_1': 8.541048700606522, 'weight_class_2': 5.221287383774314}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,974] Trial 533 finished with value: 0.949721972770595 and parameters: {'weight_class_0': 0.43170976971152025, 'weight_class_1': 8.222326302427833, 'weight_class_2': 5.180783009178016}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:22,995] Trial 535 finished with value: 0.9495365019881934 and parameters: {'weight_class_0': 0.36990849680292254, 'weight_class_1': 8.186648684570102, 'weight_class_2': 5.2137203645536}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:23,018] Trial 536 finished with value: 0.9494658132218247 and parameters: {'weight_class_0': 0.35833749542541027, 'weight_class_1': 8.210932869905633, 'weight_class_2': 5.199988076467356}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:23,025] Trial 537 finished with value: 0.9496780319568701 and parameters: {'weight_class_0': 0.41716650351635814, 'weight_class_1': 8.231165940451875, 'weight_class_2': 5.130700652997113}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:23,042] Trial 538 finished with value: 0.949757156303446 and parameters: {'weight_class_0': 0.5246971677463141, 'weight_class_1': 8.568559844585563, 'weight_class_2': 5.226571501911903}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:23,083] Trial 539 finished with value: 0.9490718510312663 and parameters: {'weight_class_0': 0.5549137595493038, 'weight_class_1': 8.260565889313558, 'weight_class_2': 4.040582809598254}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:23,085] Trial 540 finished with value: 0.9496789657245904 and parameters: {'weight_class_0': 0.535239215916547, 'weight_class_1': 7.360614159198519, 'weight_class_2': 5.142236206116914}. Best is trial 402 with value: 0.9498372606373188.

Best trial: 544. Best value: 0.94986:  55%|█████████████████████████████████████████████████████████████████████████▎                                                           | 551/1000 [00:10<00:08, 52.20it/s]

[I 2026-07-05 15:03:23,098] Trial 541 finished with value: 0.9496646300622253 and parameters: {'weight_class_0': 0.5336861600003998, 'weight_class_1': 8.321406206535391, 'weight_class_2': 5.096136679953412}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:23,118] Trial 542 finished with value: 0.9495959472786502 and parameters: {'weight_class_0': 0.5838398193973131, 'weight_class_1': 8.576271209364586, 'weight_class_2': 5.154593544251567}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:23,138] Trial 543 finished with value: 0.9497117452006186 and parameters: {'weight_class_0': 0.5294916710870722, 'weight_class_1': 8.588725088533284, 'weight_class_2': 5.187717227085604}. Best is trial 402 with value: 0.9498372606373188.
[I 2026-07-05 15:03:23,164] Trial 544 finished with value: 0.9498598945942169 and parameters: {'weight_class_0': 0.5338154837630474, 'weight_class_1': 8.420277430237832, 'weight_class_2': 5.811089238148999}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:23,193] Trial 545 finished with value: 0.9470820813772041 and parameters: {'weight_class_0': 0.5697650250741638, 'weight_class_1': 8.663429861406822, 'weight_class_2': 2.584811017077277}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:23,216] Trial 546 finished with value: 0.9498151893132073 and parameters: {'weight_class_0': 0.5523606651082759, 'weight_class_1': 8.634755587367495, 'weight_class_2': 5.828657148782156}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:23,223] Trial 547 finished with value: 0.9498532562309813 and parameters: {'weight_class_0': 0.575648935180271, 'weight_class_1': 8.645868391646557, 'weight_class_2': 6.19754702456591}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:23,227] Trial 548 finished with value: 0.9489825813788676 and parameters: {'weight_class_0': 0.8002656352946438, 'weight_class_1': 8.716967890533368, 'weight_class_2': 5.837030991662253}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:23,263] Trial 549 finished with value: 0.9490491679716326 and parameters: {'weight_class_0': 0.7765881939267142, 'weight_class_1': 8.765626693896772, 'weight_class_2': 5.823562927265218}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:23,290] Trial 550 finished with value: 0.9489518654413622 and parameters: {'weight_class_0': 0.8133141701958024, 'weight_class_1': 8.767620820301644, 'weight_class_2': 5.886527522987547}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:23,306] Trial 551 finished with value: 0.9488844584138763 and parameters: {'weight_class_0': 0.8220007435021891, 'weight_class_1': 8.734166695076084, 'weight_class_2': 5.827059519475782}. Best is trial 544 with value: 0.9498598945942169.

Best trial: 544. Best value: 0.94986:  56%|██████████████████████████████████████████████████████████████████████████▋                                                          | 562/1000 [00:10<00:08, 52.94it/s]

[I 2026-07-05 15:03:23,331] Trial 552 finished with value: 0.94913623374679 and parameters: {'weight_class_0': 0.7873402386952757, 'weight_class_1': 8.810456753925509, 'weight_class_2': 6.215067348720035}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:23,332] Trial 553 finished with value: 0.9488582588201845 and parameters: {'weight_class_0': 0.8046180105518482, 'weight_class_1': 7.729253871470629, 'weight_class_2': 5.8402337851716934}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:23,367] Trial 554 finished with value: 0.9488204592186168 and parameters: {'weight_class_0': 0.8131248910897262, 'weight_class_1': 7.716806325060618, 'weight_class_2': 5.815751268603138}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:23,371] Trial 555 finished with value: 0.9488126492109816 and parameters: {'weight_class_0': 0.8417915243765708, 'weight_class_1': 8.806055244798456, 'weight_class_2': 5.8521538465158764}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:23,376] Trial 556 finished with value: 0.9490167870064182 and parameters: {'weight_class_0': 0.7776947061014922, 'weight_class_1': 8.784590508024527, 'weight_class_2': 5.7873525125357}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:23,424] Trial 557 finished with value: 0.8982572392599355 and parameters: {'weight_class_0': 1.648012159381292, 'weight_class_1': 0.867851087348896, 'weight_class_2': 5.81721095591042}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:23,435] Trial 558 finished with value: 0.9473047042160584 and parameters: {'weight_class_0': 0.21101830432939284, 'weight_class_1': 8.831683552980344, 'weight_class_2': 5.847812108772956}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:23,459] Trial 559 finished with value: 0.9482117971644626 and parameters: {'weight_class_0': 0.2558515083359667, 'weight_class_1': 8.825209746746099, 'weight_class_2': 5.861058458074124}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:23,467] Trial 560 finished with value: 0.9465699340664999 and parameters: {'weight_class_0': 0.18912507012737295, 'weight_class_1': 8.84215550191767, 'weight_class_2': 5.862876094380528}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:23,515] Trial 561 finished with value: 0.9475060421088579 and parameters: {'weight_class_0': 0.21497838022682136, 'weight_class_1': 8.421648627696435, 'weight_class_2': 6.119996760394011}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:23,520] Trial 562 finished with value: 0.9474581636880005 and parameters: {'weight_class_0': 0.2144621019969376, 'weight_class_1': 8.450563723888187, 'weight_class_2': 6.1598750935822215}. Best is trial 544 with value: 0.9498598945942169.

Best trial: 544. Best value: 0.94986:  57%|████████████████████████████████████████████████████████████████████████████▎                                                        | 574/1000 [00:11<00:08, 52.96it/s]

[I 2026-07-05 15:03:23,544] Trial 564 finished with value: 0.9474165044950134 and parameters: {'weight_class_0': 0.20578797530979903, 'weight_class_1': 8.44170887747072, 'weight_class_2': 5.563993987819882}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:23,552] Trial 563 finished with value: 0.9478930777970774 and parameters: {'weight_class_0': 0.2276627145324835, 'weight_class_1': 8.434185180661535, 'weight_class_2': 5.601093416328833}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:23,569] Trial 565 finished with value: 0.8961836070413752 and parameters: {'weight_class_0': 5.475327974126654, 'weight_class_1': 8.500893401833197, 'weight_class_2': 6.177339461699188}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:23,597] Trial 566 finished with value: 0.9473136160428619 and parameters: {'weight_class_0': 0.21216533162563583, 'weight_class_1': 8.569502974360908, 'weight_class_2': 6.253348918281174}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:23,623] Trial 568 finished with value: 0.9470125643309691 and parameters: {'weight_class_0': 0.19888234426935159, 'weight_class_1': 8.441345540688934, 'weight_class_2': 6.198746511952364}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:23,623] Trial 567 finished with value: 0.9472429725038106 and parameters: {'weight_class_0': 0.2060559874758996, 'weight_class_1': 8.399637469442707, 'weight_class_2': 6.182543037218136}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:23,637] Trial 569 finished with value: 0.9474355991166877 and parameters: {'weight_class_0': 0.21290604601638302, 'weight_class_1': 8.420609991221937, 'weight_class_2': 6.153240467776476}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:23,653] Trial 571 finished with value: 0.9486723183991588 and parameters: {'weight_class_0': 0.2968041400745707, 'weight_class_1': 8.541278365632088, 'weight_class_2': 6.158961216367412}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:23,674] Trial 570 finished with value: 0.9485184203188086 and parameters: {'weight_class_0': 0.2803210497740212, 'weight_class_1': 8.498023326577677, 'weight_class_2': 6.13668121519607}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:23,691] Trial 572 finished with value: 0.9480920851768494 and parameters: {'weight_class_0': 0.2756804491823103, 'weight_class_1': 9.996107776909732, 'weight_class_2': 6.092518948776248}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:23,709] Trial 573 finished with value: 0.9496531401132834 and parameters: {'weight_class_0': 0.5979516755963293, 'weight_class_1': 8.521118866089923, 'weight_class_2': 5.481291458526507}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:23,741] Trial 574 finished with value: 0.9497994535904439 and parameters: {'weight_class_0': 0.5593167528865889, 'weight_class_1': 9.029005846796299, 'weight_class_2': 6.426745366257264}. Best is trial 544 with value: 0.9498598945942169.

[I 2026-07-05 15:03:23,759] Trial 575 finished with value: 0.9497541185989323 and parameters: {'weight_class_0': 0.5426717490289624, 'weight_class_1': 9.97115790164904, 'weight_class_2': 6.453374279656709}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:23,794] Trial 576 finished with value: 0.9497391597616304 and parameters: {'weight_class_0': 0.5554918308718172, 'weight_class_1': 9.085270946463577, 'weight_class_2': 5.506448819288283}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:23,806] Trial 577 finished with value: 0.9498289301634563 and parameters: {'weight_class_0': 0.5894247407411103, 'weight_class_1': 9.043553080825461, 'weight_class_2': 6.4992533106792205}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:23,828] Trial 578 finished with value: 0.9497985349884162 and parameters: {'weight_class_0': 0.5457173153435628, 'weight_class_1': 9.064464920195347, 'weight_class_2': 6.437277701756684}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:23,849] Trial 580 finished with value: 0.9496375653537902 and parameters: {'weight_class_0': 0.5868813474044288, 'weight_class_1': 9.041833529749436, 'weight_class_2': 5.5255866261100515}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:23,855] Trial 579 finished with value: 0.9498293250377573 and parameters: {'weight_class_0': 0.5705311621650793, 'weight_class_1': 9.050105722437486, 'weight_class_2': 6.455385167327071}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:23,881] Trial 581 finished with value: 0.9498475163181794 and parameters: {'weight_class_0': 0.5953924059924325, 'weight_class_1': 8.99225365426023, 'weight_class_2': 6.435950643472856}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:23,919] Trial 583 finished with value: 0.9498397206128382 and parameters: {'weight_class_0': 0.5777566981681889, 'weight_class_1': 9.050501050259493, 'weight_class_2': 6.436687465046027}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:23,926] Trial 582 finished with value: 0.9498246016886968 and parameters: {'weight_class_0': 0.574358229581361, 'weight_class_1': 9.01233761943946, 'weight_class_2': 6.502896976754532}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:23,940] Trial 584 finished with value: 0.949795124136457 and parameters: {'weight_class_0': 0.624005892299261, 'weight_class_1': 9.082595894923578, 'weight_class_2': 6.43895907894602}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:23,960] Trial 585 finished with value: 0.949833579709071 and parameters: {'weight_class_0': 0.595381951575998, 'weight_class_1': 9.088815619949852, 'weight_class_2': 6.574459744076542}. Best is trial 544 with value: 0.9498598945942169.

Best trial: 544. Best value: 0.94986:  60%|███████████████████████████████████████████████████████████████████████████████▎                                                     | 596/1000 [00:11<00:07, 52.65it/s]

[I 2026-07-05 15:03:23,989] Trial 586 finished with value: 0.9497256920025503 and parameters: {'weight_class_0': 0.6639530709627026, 'weight_class_1': 9.07141581223225, 'weight_class_2': 6.4863056204523355}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:23,994] Trial 587 finished with value: 0.9498009394487119 and parameters: {'weight_class_0': 0.6165663636167613, 'weight_class_1': 9.094159309991245, 'weight_class_2': 6.455760137818126}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,020] Trial 589 finished with value: 0.9490131419968093 and parameters: {'weight_class_0': 0.8942160538480226, 'weight_class_1': 9.702353958588196, 'weight_class_2': 6.531785812545845}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,024] Trial 588 finished with value: 0.9489644136476469 and parameters: {'weight_class_0': 0.8922011940017993, 'weight_class_1': 9.11994178176646, 'weight_class_2': 6.519618863489613}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,050] Trial 590 finished with value: 0.9486457683303265 and parameters: {'weight_class_0': 0.9782824828992425, 'weight_class_1': 9.637922323388104, 'weight_class_2': 6.497669580904644}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,074] Trial 591 finished with value: 0.9489767615459556 and parameters: {'weight_class_0': 0.8816701389410749, 'weight_class_1': 9.693539864544075, 'weight_class_2': 6.491681222496291}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,091] Trial 592 finished with value: 0.948761319190479 and parameters: {'weight_class_0': 0.9188417160739839, 'weight_class_1': 9.287304429805813, 'weight_class_2': 6.3899192976711525}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,114] Trial 593 finished with value: 0.9491384415640818 and parameters: {'weight_class_0': 0.8490581635436947, 'weight_class_1': 9.357873141084024, 'weight_class_2': 6.489339626544302}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,142] Trial 594 finished with value: 0.9486562244552715 and parameters: {'weight_class_0': 0.9803731857168174, 'weight_class_1': 9.34691423965727, 'weight_class_2': 6.617811515325301}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,146] Trial 595 finished with value: 0.948889158077627 and parameters: {'weight_class_0': 0.8915651739618857, 'weight_class_1': 9.291800126573573, 'weight_class_2': 6.468527631459089}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,160] Trial 596 finished with value: 0.9491475401084303 and parameters: {'weight_class_0': 0.8502864018280116, 'weight_class_1': 9.324043951568347, 'weight_class_2': 6.518923633864116}. Best is trial 544 with value: 0.9498598945942169.

[I 2026-07-05 15:03:24,212] Trial 597 finished with value: 0.9488882127010716 and parameters: {'weight_class_0': 0.9088008892915498, 'weight_class_1': 9.270335554506646, 'weight_class_2': 6.5769615869282365}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,216] Trial 599 finished with value: 0.9491808351550151 and parameters: {'weight_class_0': 0.8722034669951494, 'weight_class_1': 9.269683005300344, 'weight_class_2': 6.7791731582545705}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,241] Trial 598 finished with value: 0.9487526703648181 and parameters: {'weight_class_0': 0.9630077435621353, 'weight_class_1': 9.303917939745778, 'weight_class_2': 6.618879115208489}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,280] Trial 600 finished with value: 0.9488295439336291 and parameters: {'weight_class_0': 0.9555283935944564, 'weight_class_1': 9.336534509790079, 'weight_class_2': 6.811557715859845}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,282] Trial 601 finished with value: 0.9487807412052662 and parameters: {'weight_class_0': 0.9811955738185523, 'weight_class_1': 9.288646250798072, 'weight_class_2': 6.8154567235217565}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,296] Trial 603 finished with value: 0.9487592956800653 and parameters: {'weight_class_0': 0.9861123925704703, 'weight_class_1': 9.360667069245103, 'weight_class_2': 6.805224255441282}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,303] Trial 602 finished with value: 0.9496606560301846 and parameters: {'weight_class_0': 0.7482734402249007, 'weight_class_1': 9.33730954685105, 'weight_class_2': 6.843660865601244}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,314] Trial 604 finished with value: 0.9486013849015197 and parameters: {'weight_class_0': 1.029545070112137, 'weight_class_1': 9.305232679612798, 'weight_class_2': 6.800125786654981}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,358] Trial 605 finished with value: 0.9475040508902142 and parameters: {'weight_class_0': 1.2657317234040635, 'weight_class_1': 9.243897634014292, 'weight_class_2': 6.841107605258817}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,362] Trial 606 finished with value: 0.9475763730807172 and parameters: {'weight_class_0': 1.241825900481592, 'weight_class_1': 9.035040877041151, 'weight_class_2': 6.83875460848567}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,375] Trial 607 finished with value: 0.9497051639563278 and parameters: {'weight_class_0': 0.7109447351804903, 'weight_class_1': 8.954435619870381, 'weight_class_2': 6.965865207081446}. Best is trial 544 with value: 0.9498598945942169.

Best trial: 544. Best value: 0.94986:  62%|██████████████████████████████████████████████████████████████████████████████████                                                   | 617/1000 [00:11<00:07, 50.00it/s]

[I 2026-07-05 15:03:24,412] Trial 608 finished with value: 0.8726386136365619 and parameters: {'weight_class_0': 1.279019458316078, 'weight_class_1': 0.0754320032417306, 'weight_class_2': 6.754355205020369}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,418] Trial 609 finished with value: 0.941725672255985 and parameters: {'weight_class_0': 1.9783217856316062, 'weight_class_1': 8.951167569861775, 'weight_class_2': 6.955535509614403}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,437] Trial 610 finished with value: 0.8880334392695738 and parameters: {'weight_class_0': 6.918144171931723, 'weight_class_1': 9.032471459746734, 'weight_class_2': 6.8554461536836335}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,461] Trial 611 finished with value: 0.8886054335879917 and parameters: {'weight_class_0': 6.8262259252556925, 'weight_class_1': 8.978098888605444, 'weight_class_2': 6.849401135589966}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,515] Trial 612 finished with value: 0.9496244109528936 and parameters: {'weight_class_0': 0.6752761602341876, 'weight_class_1': 9.05911919155865, 'weight_class_2': 6.3281454212561075}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,517] Trial 613 finished with value: 0.9497239701927457 and parameters: {'weight_class_0': 0.6783877276882564, 'weight_class_1': 8.939410970515238, 'weight_class_2': 6.948831747411248}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,546] Trial 614 finished with value: 0.9471307107013835 and parameters: {'weight_class_0': 1.254517762271221, 'weight_class_1': 8.94203050878952, 'weight_class_2': 6.311104075124483}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,578] Trial 615 finished with value: 0.949679403209949 and parameters: {'weight_class_0': 0.65616246496371, 'weight_class_1': 8.923316585624265, 'weight_class_2': 6.32193464310875}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,586] Trial 616 finished with value: 0.9497517016123455 and parameters: {'weight_class_0': 0.6835215198737922, 'weight_class_1': 8.951223951210764, 'weight_class_2': 7.0597529337835985}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,600] Trial 618 finished with value: 0.9498155939073736 and parameters: {'weight_class_0': 0.6123089369486575, 'weight_class_1': 8.916944544743568, 'weight_class_2': 6.360680425411833}. Best is trial 544 with value: 0.9498598945942169.

[I 2026-07-05 15:03:24,604] Trial 617 finished with value: 0.9495788280849067 and parameters: {'weight_class_0': 0.6931633093333103, 'weight_class_1': 9.026463862602588, 'weight_class_2': 6.242843127590462}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,623] Trial 619 finished with value: 0.9497533071104431 and parameters: {'weight_class_0': 0.6440590619191862, 'weight_class_1': 8.933672254928624, 'weight_class_2': 6.359367184757753}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,629] Trial 620 finished with value: 0.9496998487198013 and parameters: {'weight_class_0': 0.6514997247235366, 'weight_class_1': 8.976081312403252, 'weight_class_2': 6.301342758246008}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,659] Trial 621 finished with value: 0.9498176600288448 and parameters: {'weight_class_0': 0.6138251330609646, 'weight_class_1': 8.904310044930565, 'weight_class_2': 6.340641929913776}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,664] Trial 622 finished with value: 0.9496240733336458 and parameters: {'weight_class_0': 0.6798586785432482, 'weight_class_1': 8.912977849033762, 'weight_class_2': 6.264897652533876}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,671] Trial 623 finished with value: 0.9496826290841925 and parameters: {'weight_class_0': 0.6554214771547019, 'weight_class_1': 8.895120466919918, 'weight_class_2': 6.301551363957549}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,717] Trial 624 finished with value: 0.949466656588967 and parameters: {'weight_class_0': 0.40293996631950724, 'weight_class_1': 8.893294849313504, 'weight_class_2': 6.344301359403502}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,747] Trial 626 finished with value: 0.9494243594665369 and parameters: {'weight_class_0': 0.41364048081251975, 'weight_class_1': 9.538762464041918, 'weight_class_2': 6.241158354117645}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,751] Trial 625 finished with value: 0.9494511062961314 and parameters: {'weight_class_0': 0.39620650877025465, 'weight_class_1': 8.824258617410957, 'weight_class_2': 6.239352782956312}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,784] Trial 627 finished with value: 0.9492600828324566 and parameters: {'weight_class_0': 0.3708001595311231, 'weight_class_1': 8.807311162800874, 'weight_class_2': 6.281392042407881}. Best is trial 544 with value: 0.9498598945942169.

[I 2026-07-05 15:03:24,823] Trial 629 finished with value: 0.9493441004506263 and parameters: {'weight_class_0': 0.38429745158564843, 'weight_class_1': 8.841835649363855, 'weight_class_2': 6.308254155161104}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,829] Trial 628 finished with value: 0.9492213994244504 and parameters: {'weight_class_0': 0.39554949433534226, 'weight_class_1': 9.548713567268953, 'weight_class_2': 6.630594437342703}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,856] Trial 630 finished with value: 0.9491001522417811 and parameters: {'weight_class_0': 0.3723522168438112, 'weight_class_1': 9.57238721447016, 'weight_class_2': 6.6741124849999345}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,875] Trial 632 finished with value: 0.9491751286734523 and parameters: {'weight_class_0': 0.3549629646895762, 'weight_class_1': 8.73897866186831, 'weight_class_2': 6.039610004693565}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,881] Trial 631 finished with value: 0.949640446690494 and parameters: {'weight_class_0': 0.4289197057536887, 'weight_class_1': 8.733838289732976, 'weight_class_2': 6.05447892789046}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,900] Trial 634 finished with value: 0.9496933473801931 and parameters: {'weight_class_0': 0.4569658826640401, 'weight_class_1': 8.714541312622536, 'weight_class_2': 6.056688642931899}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,919] Trial 633 finished with value: 0.9495143934168003 and parameters: {'weight_class_0': 0.41754300140318723, 'weight_class_1': 8.755798923321272, 'weight_class_2': 6.677051603375917}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,926] Trial 635 finished with value: 0.9493293419135864 and parameters: {'weight_class_0': 0.37531452307025936, 'weight_class_1': 8.722835901334475, 'weight_class_2': 6.105379839437894}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,943] Trial 636 finished with value: 0.9457808379308777 and parameters: {'weight_class_0': 1.4995508712667514, 'weight_class_1': 9.564162587532307, 'weight_class_2': 6.638465182706477}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:24,989] Trial 637 finished with value: 0.9491661127682711 and parameters: {'weight_class_0': 0.367642345157569, 'weight_class_1': 9.520251249970714, 'weight_class_2': 6.0370512320562915}. Best is trial 544 with value: 0.9498598945942169.

[I 2026-07-05 15:03:25,003] Trial 638 finished with value: 0.8783769260842971 and parameters: {'weight_class_0': 0.040566709534027634, 'weight_class_1': 8.691683217100321, 'weight_class_2': 6.027599137236206}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:25,016] Trial 639 finished with value: 0.6886319634853008 and parameters: {'weight_class_0': 0.00906052734964452, 'weight_class_1': 7.5499148466109665, 'weight_class_2': 6.029326032315624}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:25,064] Trial 640 finished with value: 0.9182184957497729 and parameters: {'weight_class_0': 0.064775081555705, 'weight_class_1': 9.149817856133524, 'weight_class_2': 6.0085624140777485}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:25,073] Trial 641 finished with value: 0.6637945055854547 and parameters: {'weight_class_0': 0.005122547384731835, 'weight_class_1': 7.8727851028339355, 'weight_class_2': 6.006155498323708}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:25,088] Trial 642 finished with value: 0.9494981361737795 and parameters: {'weight_class_0': 0.736557302457953, 'weight_class_1': 7.506613215812752, 'weight_class_2': 6.632039464976724}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:25,104] Trial 643 finished with value: 0.9454120137726184 and parameters: {'weight_class_0': 1.444985733084305, 'weight_class_1': 7.859085084580951, 'weight_class_2': 6.595366620101891}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:25,136] Trial 645 finished with value: 0.8291901703950204 and parameters: {'weight_class_0': 0.02794931806839618, 'weight_class_1': 7.590490869011841, 'weight_class_2': 7.09273365298922}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:25,143] Trial 644 finished with value: 0.8727582497276023 and parameters: {'weight_class_0': 0.036617255453741115, 'weight_class_1': 7.607297754937673, 'weight_class_2': 6.611372639339624}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:25,161] Trial 646 finished with value: 0.9494840046614966 and parameters: {'weight_class_0': 0.7531461380705414, 'weight_class_1': 7.915990146798021, 'weight_class_2': 6.525781777350275}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:25,198] Trial 647 finished with value: 0.9236910820058132 and parameters: {'weight_class_0': 0.05325607508880614, 'weight_class_1': 7.439730885783639, 'weight_class_2': 1.6476822726936922}. Best is trial 544 with value: 0.9498598945942169.

Best trial: 544. Best value: 0.94986:  66%|███████████████████████████████████████████████████████████████████████████████████████▌                                             | 658/1000 [00:12<00:06, 51.18it/s]

[I 2026-07-05 15:03:25,222] Trial 649 finished with value: 0.9496138141190689 and parameters: {'weight_class_0': 0.7739935793861967, 'weight_class_1': 9.180578760427435, 'weight_class_2': 7.076722171911085}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:25,225] Trial 648 finished with value: 0.9480869496541368 and parameters: {'weight_class_0': 1.0924275888287074, 'weight_class_1': 9.161954524955275, 'weight_class_2': 6.641690894426018}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:25,243] Trial 650 finished with value: 0.9496471117819137 and parameters: {'weight_class_0': 0.7583673217519622, 'weight_class_1': 9.160596793350994, 'weight_class_2': 7.0654084472843905}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:25,283] Trial 651 finished with value: 0.9496530598514714 and parameters: {'weight_class_0': 0.746600371657804, 'weight_class_1': 9.141065156841233, 'weight_class_2': 7.128018909980336}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:25,298] Trial 652 finished with value: 0.8779991305076468 and parameters: {'weight_class_0': 8.249236682164767, 'weight_class_1': 9.116871963583268, 'weight_class_2': 6.6456889904194965}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:25,313] Trial 653 finished with value: 0.9495786442920117 and parameters: {'weight_class_0': 0.7525262331987379, 'weight_class_1': 9.12820205904173, 'weight_class_2': 6.522041189102689}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:25,326] Trial 654 finished with value: 0.9496685120797967 and parameters: {'weight_class_0': 0.7458882469589161, 'weight_class_1': 9.107353072465665, 'weight_class_2': 7.080021768100743}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:25,356] Trial 655 finished with value: 0.8722927099505418 and parameters: {'weight_class_0': 9.160761345795162, 'weight_class_1': 9.147029498776323, 'weight_class_2': 6.479605605492903}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:25,363] Trial 656 finished with value: 0.9486953834390368 and parameters: {'weight_class_0': 1.0210582159283572, 'weight_class_1': 9.151649843494486, 'weight_class_2': 7.0279061291855704}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:25,391] Trial 657 finished with value: 0.9112830630669254 and parameters: {'weight_class_0': 4.710713717506415, 'weight_class_1': 9.17932472179909, 'weight_class_2': 7.1247900083121065}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:25,404] Trial 658 finished with value: 0.948250517130563 and parameters: {'weight_class_0': 1.0387446944059937, 'weight_class_1': 9.12953331801572, 'weight_class_2': 6.477215318565408}. Best is trial 544 with value: 0.9498598945942169.

[I 2026-07-05 15:03:25,462] Trial 659 finished with value: 0.947949022194522 and parameters: {'weight_class_0': 1.0556840837809616, 'weight_class_1': 8.145906458045182, 'weight_class_2': 6.399552217381738}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:25,475] Trial 660 finished with value: 0.9352977739680348 and parameters: {'weight_class_0': 2.37175871590007, 'weight_class_1': 8.144282661833582, 'weight_class_2': 6.382058173485319}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:25,493] Trial 661 finished with value: 0.9497992008849213 and parameters: {'weight_class_0': 0.5526747994920921, 'weight_class_1': 8.080674119608545, 'weight_class_2': 6.384956078782377}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:25,510] Trial 662 finished with value: 0.9480002420199821 and parameters: {'weight_class_0': 1.0671238331881758, 'weight_class_1': 8.628379983312048, 'weight_class_2': 6.424567006528672}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:25,518] Trial 663 finished with value: 0.9476616784827118 and parameters: {'weight_class_0': 1.1064154535418593, 'weight_class_1': 8.145698295686696, 'weight_class_2': 6.350342535796541}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:25,530] Trial 664 finished with value: 0.9498246363814894 and parameters: {'weight_class_0': 0.5596334710995661, 'weight_class_1': 8.71841786636885, 'weight_class_2': 6.3868971226629565}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:25,562] Trial 665 finished with value: 0.9480409324928057 and parameters: {'weight_class_0': 1.0476979102817623, 'weight_class_1': 8.641753181665987, 'weight_class_2': 6.344045805757656}. Best is trial 544 with value: 0.9498598945942169.
[I 2026-07-05 15:03:25,571] Trial 666 finished with value: 0.9498641691087344 and parameters: {'weight_class_0': 0.5874888013159347, 'weight_class_1': 8.629195687506948, 'weight_class_2': 6.349313022612121}. Best is trial 666 with value: 0.9498641691087344.
[I 2026-07-05 15:03:25,585] Trial 668 finished with value: 0.9497773479437007 and parameters: {'weight_class_0': 0.5212305809465982, 'weight_class_1': 8.079685818757158, 'weight_class_2': 6.273452123960058}. Best is trial 666 with value: 0.9498641691087344.
[I 2026-07-05 15:03:25,598] Trial 667 finished with value: 0.9498422017602041 and parameters: {'weight_class_0': 0.5814790760315383, 'weight_class_1': 8.606587306493722, 'weight_class_2': 6.343682865863407}. Best is trial 666 with value: 0.9498641691087344.
[I 2026-07-05 15:03:25,628] Trial 669 finished with value: 0.9498037629005508 and parameters: {'weight_class_0': 0.5540834365073497, 'weight_class_1': 8.143348078311623, 'weight_class_2': 6.246916384300748}. Best is trial 666 with value: 0.9498641691087344.

Best trial: 673. Best value: 0.949875:  68%|█████████████████████████████████████████████████████████████████████████████████████████▊                                          | 680/1000 [00:13<00:06, 48.97it/s]

[I 2026-07-05 15:03:25,640] Trial 670 finished with value: 0.9497895398105832 and parameters: {'weight_class_0': 0.5472416336861422, 'weight_class_1': 8.079557085268755, 'weight_class_2': 6.294644139774514}. Best is trial 666 with value: 0.9498641691087344.
[I 2026-07-05 15:03:25,676] Trial 671 finished with value: 0.9498299164522654 and parameters: {'weight_class_0': 0.5730501672421943, 'weight_class_1': 8.779049601039459, 'weight_class_2': 6.18670998338647}. Best is trial 666 with value: 0.9498641691087344.
[I 2026-07-05 15:03:25,696] Trial 672 finished with value: 0.949819607016756 and parameters: {'weight_class_0': 0.5840113205443611, 'weight_class_1': 8.629925634406522, 'weight_class_2': 6.172830267155494}. Best is trial 666 with value: 0.9498641691087344.
[I 2026-07-05 15:03:25,727] Trial 673 finished with value: 0.949874946749033 and parameters: {'weight_class_0': 0.5779101744296922, 'weight_class_1': 9.477512278163818, 'weight_class_2': 6.194078893277037}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:25,733] Trial 674 finished with value: 0.949810015019613 and parameters: {'weight_class_0': 0.5455577782219488, 'weight_class_1': 8.701112819429882, 'weight_class_2': 6.140229601805759}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:25,778] Trial 675 finished with value: 0.9498348540747464 and parameters: {'weight_class_0': 0.5649392508890063, 'weight_class_1': 8.652251309146749, 'weight_class_2': 6.2396459439424214}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:25,796] Trial 676 finished with value: 0.9498445256836096 and parameters: {'weight_class_0': 0.5678513686682873, 'weight_class_1': 8.606083316391356, 'weight_class_2': 6.176714570009634}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:25,817] Trial 679 finished with value: 0.948888897556636 and parameters: {'weight_class_0': 0.8433509452361319, 'weight_class_1': 8.527178168132798, 'weight_class_2': 6.137359579360784}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:25,826] Trial 677 finished with value: 0.9498408398645436 and parameters: {'weight_class_0': 0.5782062179870128, 'weight_class_1': 8.599796540198604, 'weight_class_2': 6.145121358320644}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:25,833] Trial 678 finished with value: 0.9467213466162102 and parameters: {'weight_class_0': 0.5538855554880584, 'weight_class_1': 2.528409426951252, 'weight_class_2': 6.113069233140806}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:25,869] Trial 680 finished with value: 0.9492878082738958 and parameters: {'weight_class_0': 0.8292726173632333, 'weight_class_1': 8.58322374043198, 'weight_class_2': 6.6955423116820585}. Best is trial 673 with value: 0.949874946749033.

[I 2026-07-05 15:03:25,892] Trial 681 finished with value: 0.9487874506528909 and parameters: {'weight_class_0': 0.8646480724158087, 'weight_class_1': 8.611610374627125, 'weight_class_2': 6.079752540330748}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:25,903] Trial 682 finished with value: 0.9484792497802658 and parameters: {'weight_class_0': 0.27621241808989433, 'weight_class_1': 8.583682696570103, 'weight_class_2': 6.1057322818665325}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:25,932] Trial 683 finished with value: 0.9488238595770765 and parameters: {'weight_class_0': 0.8467037681792067, 'weight_class_1': 8.620618555396081, 'weight_class_2': 6.071094873830801}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:25,942] Trial 684 finished with value: 0.9441948181768433 and parameters: {'weight_class_0': 0.8398238884425113, 'weight_class_1': 3.0068287114646948, 'weight_class_2': 6.128831454338977}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:25,955] Trial 686 finished with value: 0.9487950047963009 and parameters: {'weight_class_0': 0.8539229929800056, 'weight_class_1': 8.600566528517836, 'weight_class_2': 6.073677153860259}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:25,964] Trial 685 finished with value: 0.9432148849978031 and parameters: {'weight_class_0': 0.9071529404867683, 'weight_class_1': 3.031152678472375, 'weight_class_2': 6.022573015496943}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:25,989] Trial 687 finished with value: 0.9256411823190146 and parameters: {'weight_class_0': 3.040780808617405, 'weight_class_1': 8.39523698268431, 'weight_class_2': 6.103633518896613}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,015] Trial 688 finished with value: 0.9490928122689949 and parameters: {'weight_class_0': 0.3254492566694499, 'weight_class_1': 8.313494170748886, 'weight_class_2': 6.09932797540595}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,057] Trial 690 finished with value: 0.9487132112204639 and parameters: {'weight_class_0': 0.2948720121357619, 'weight_class_1': 8.38824609878662, 'weight_class_2': 6.043592020422767}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,058] Trial 689 finished with value: 0.9485326163258586 and parameters: {'weight_class_0': 0.27759878844554203, 'weight_class_1': 8.374629826963243, 'weight_class_2': 6.136337269535813}. Best is trial 673 with value: 0.949874946749033.

Best trial: 673. Best value: 0.949875:  70%|████████████████████████████████████████████████████████████████████████████████████████████▌                                       | 701/1000 [00:13<00:06, 48.91it/s]

[I 2026-07-05 15:03:26,078] Trial 691 finished with value: 0.9485108495242094 and parameters: {'weight_class_0': 0.27437542728004066, 'weight_class_1': 8.382052421255162, 'weight_class_2': 6.11430722867755}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,110] Trial 692 finished with value: 0.9484848403873719 and parameters: {'weight_class_0': 0.2707391097908701, 'weight_class_1': 8.348728338984017, 'weight_class_2': 5.965927515561657}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,124] Trial 693 finished with value: 0.9485893460236551 and parameters: {'weight_class_0': 0.288422575871981, 'weight_class_1': 8.363385257956006, 'weight_class_2': 6.196332284009872}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,137] Trial 694 finished with value: 0.948868792472923 and parameters: {'weight_class_0': 0.30719575843719804, 'weight_class_1': 8.383749288248769, 'weight_class_2': 5.994932042855557}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,176] Trial 695 finished with value: 0.9485419788916022 and parameters: {'weight_class_0': 0.2856489446522951, 'weight_class_1': 8.378390161580626, 'weight_class_2': 6.221784385988296}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,193] Trial 697 finished with value: 0.9484597061184551 and parameters: {'weight_class_0': 0.27233559889317127, 'weight_class_1': 8.286283292380755, 'weight_class_2': 6.259131117752989}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,198] Trial 696 finished with value: 0.9490927897067344 and parameters: {'weight_class_0': 0.3320929376310427, 'weight_class_1': 8.411549475915796, 'weight_class_2': 6.206910810549843}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,231] Trial 698 finished with value: 0.9487111182216683 and parameters: {'weight_class_0': 0.3028026797566244, 'weight_class_1': 8.309029621316812, 'weight_class_2': 6.235549676408509}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,238] Trial 699 finished with value: 0.9484636438283843 and parameters: {'weight_class_0': 0.2731449910211543, 'weight_class_1': 8.318458298795274, 'weight_class_2': 6.267198348430108}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,252] Trial 700 finished with value: 0.9488563838191569 and parameters: {'weight_class_0': 0.3171398644186655, 'weight_class_1': 8.343738465801403, 'weight_class_2': 6.2761261032501325}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,292] Trial 701 finished with value: 0.9496281771032565 and parameters: {'weight_class_0': 0.7239384290043113, 'weight_class_1': 8.820076354669956, 'weight_class_2': 6.42564598808159}. Best is trial 673 with value: 0.949874946749033.

[I 2026-07-05 15:03:26,292] Trial 702 finished with value: 0.9496278391756188 and parameters: {'weight_class_0': 0.685575720521232, 'weight_class_1': 8.864477293222633, 'weight_class_2': 6.295245692467921}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,314] Trial 703 finished with value: 0.9496523385015138 and parameters: {'weight_class_0': 0.6596345137761315, 'weight_class_1': 8.81186896164177, 'weight_class_2': 6.278399780458213}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,334] Trial 704 finished with value: 0.9496093510854058 and parameters: {'weight_class_0': 0.6717509771007018, 'weight_class_1': 8.80475014030779, 'weight_class_2': 6.30884050628541}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,360] Trial 705 finished with value: 0.9496235289480559 and parameters: {'weight_class_0': 0.6767601204622352, 'weight_class_1': 8.83749599499092, 'weight_class_2': 6.315530757479997}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,391] Trial 706 finished with value: 0.9496294302970855 and parameters: {'weight_class_0': 0.688006260515192, 'weight_class_1': 8.790198941976861, 'weight_class_2': 6.432408399317905}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,407] Trial 708 finished with value: 0.9496893585806147 and parameters: {'weight_class_0': 0.6734051277401931, 'weight_class_1': 8.78588958969823, 'weight_class_2': 6.487457580647226}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,423] Trial 707 finished with value: 0.9474766484597344 and parameters: {'weight_class_0': 1.2165910728841565, 'weight_class_1': 8.748761380542847, 'weight_class_2': 6.500761100174211}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,450] Trial 709 finished with value: 0.9496305553570652 and parameters: {'weight_class_0': 0.6878998102764491, 'weight_class_1': 8.840521284889544, 'weight_class_2': 6.422236074254798}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,452] Trial 710 finished with value: 0.9474678997679628 and parameters: {'weight_class_0': 1.2195667627339375, 'weight_class_1': 8.83644944719715, 'weight_class_2': 6.490394437908399}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,482] Trial 711 finished with value: 0.9496516902431392 and parameters: {'weight_class_0': 0.7052198086627409, 'weight_class_1': 8.815069167353862, 'weight_class_2': 6.4923228161898034}. Best is trial 673 with value: 0.949874946749033.

Best trial: 673. Best value: 0.949875:  72%|███████████████████████████████████████████████████████████████████████████████████████████████▎                                    | 722/1000 [00:13<00:05, 50.32it/s]

[I 2026-07-05 15:03:26,514] Trial 712 finished with value: 0.9498057973566758 and parameters: {'weight_class_0': 0.6280194311587436, 'weight_class_1': 8.794169410460034, 'weight_class_2': 6.559170193746857}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,530] Trial 713 finished with value: 0.9318734948115831 and parameters: {'weight_class_0': 1.1979159923524096, 'weight_class_1': 2.1693331868359778, 'weight_class_2': 6.579286513858323}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,541] Trial 714 finished with value: 0.9479089934392481 and parameters: {'weight_class_0': 1.1164799702170702, 'weight_class_1': 8.644703999612679, 'weight_class_2': 6.562480355094563}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,558] Trial 715 finished with value: 0.9473760571564606 and parameters: {'weight_class_0': 1.2213188093210618, 'weight_class_1': 8.60313099731748, 'weight_class_2': 6.538157977644316}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,590] Trial 717 finished with value: 0.9478053118408868 and parameters: {'weight_class_0': 1.1504641295581148, 'weight_class_1': 8.645130393217164, 'weight_class_2': 6.66674134686488}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,603] Trial 716 finished with value: 0.9477200123499632 and parameters: {'weight_class_0': 1.1498946254142286, 'weight_class_1': 8.612072752160877, 'weight_class_2': 6.579930565856642}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,618] Trial 718 finished with value: 0.9475276925751324 and parameters: {'weight_class_0': 1.2014727285312943, 'weight_class_1': 8.618367890470946, 'weight_class_2': 6.5953948599031165}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,655] Trial 720 finished with value: 0.9485205516362737 and parameters: {'weight_class_0': 1.012338001664314, 'weight_class_1': 8.602354451472635, 'weight_class_2': 6.652098311332289}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,661] Trial 719 finished with value: 0.948602146855341 and parameters: {'weight_class_0': 0.9822532677428495, 'weight_class_1': 8.672535960132505, 'weight_class_2': 6.6724354465541245}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,670] Trial 721 finished with value: 0.9485834992332975 and parameters: {'weight_class_0': 1.006089782685464, 'weight_class_1': 8.59033272287032, 'weight_class_2': 6.729444676810987}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,683] Trial 722 finished with value: 0.94859497283944 and parameters: {'weight_class_0': 0.9833172292489691, 'weight_class_1': 8.60327387036025, 'weight_class_2': 6.687886468358155}. Best is trial 673 with value: 0.949874946749033.

[I 2026-07-05 15:03:26,711] Trial 723 finished with value: 0.9488051355353271 and parameters: {'weight_class_0': 0.9472294225157104, 'weight_class_1': 8.621563157308554, 'weight_class_2': 6.689114017272632}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,747] Trial 724 finished with value: 0.9484359733925111 and parameters: {'weight_class_0': 1.0261927680194733, 'weight_class_1': 8.568185566969628, 'weight_class_2': 6.712905437031175}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,779] Trial 726 finished with value: 0.9497106207371387 and parameters: {'weight_class_0': 0.5011077999443186, 'weight_class_1': 8.627123866856682, 'weight_class_2': 6.692992494374338}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,804] Trial 725 finished with value: 0.9486789224624385 and parameters: {'weight_class_0': 0.9689731059699263, 'weight_class_1': 8.551525544643644, 'weight_class_2': 6.674107236813773}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,806] Trial 728 finished with value: 0.9484671359927979 and parameters: {'weight_class_0': 0.925553155339913, 'weight_class_1': 8.506719706584954, 'weight_class_2': 5.9143583977059775}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,819] Trial 727 finished with value: 0.9497112505837491 and parameters: {'weight_class_0': 0.47326728055597833, 'weight_class_1': 8.506708074078132, 'weight_class_2': 5.892001443672099}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,827] Trial 729 finished with value: 0.9497032606537843 and parameters: {'weight_class_0': 0.4818160853779296, 'weight_class_1': 8.55090562526399, 'weight_class_2': 5.913711940339147}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,866] Trial 730 finished with value: 0.9483666724532118 and parameters: {'weight_class_0': 0.9343534147436809, 'weight_class_1': 8.521277731058706, 'weight_class_2': 5.915843453014554}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,884] Trial 732 finished with value: 0.9498239620604498 and parameters: {'weight_class_0': 0.535153238943687, 'weight_class_1': 8.547026196581418, 'weight_class_2': 5.905828304452632}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,894] Trial 731 finished with value: 0.9497306883655812 and parameters: {'weight_class_0': 0.4823753466242786, 'weight_class_1': 8.97695096049129, 'weight_class_2': 5.9303865649240715}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,923] Trial 733 finished with value: 0.9493887381992518 and parameters: {'weight_class_0': 0.5519205414355149, 'weight_class_1': 4.6741154075988725, 'weight_class_2': 5.9408535588323765}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,942] Trial 734 finished with value: 0.9497434631814117 and parameters: {'weight_class_0': 0.549196447982578, 'weight_class_1': 8.940738295261486, 'weight_class_2': 6.835155837883197}. Best is trial 673 with value: 0.949874946749033.

Best trial: 673. Best value: 0.949875:  74%|██████████████████████████████████████████████████████████████████████████████████████████████████▏                                 | 744/1000 [00:14<00:05, 47.80it/s]

[I 2026-07-05 15:03:26,957] Trial 735 finished with value: 0.9496871094321685 and parameters: {'weight_class_0': 0.45810382497041674, 'weight_class_1': 8.972454556796775, 'weight_class_2': 5.887184707334719}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:26,978] Trial 736 finished with value: 0.9496677149732567 and parameters: {'weight_class_0': 0.4496438103952757, 'weight_class_1': 9.041221125724107, 'weight_class_2': 5.96640554360808}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,009] Trial 737 finished with value: 0.9495279280918894 and parameters: {'weight_class_0': 0.4748904829668305, 'weight_class_1': 5.400631098214515, 'weight_class_2': 5.92643087189286}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,054] Trial 738 finished with value: 0.949688895189445 and parameters: {'weight_class_0': 0.4665298994777044, 'weight_class_1': 8.944104596859555, 'weight_class_2': 5.911534232887112}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,060] Trial 740 finished with value: 0.9497117874622606 and parameters: {'weight_class_0': 0.5087330099838214, 'weight_class_1': 8.948867375503243, 'weight_class_2': 5.950994324996424}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,061] Trial 739 finished with value: 0.9496676108948788 and parameters: {'weight_class_0': 0.45348155049476957, 'weight_class_1': 8.964299094625414, 'weight_class_2': 5.945681298856475}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,113] Trial 741 finished with value: 0.9498073409352411 and parameters: {'weight_class_0': 0.4935170265977873, 'weight_class_1': 8.218656113076914, 'weight_class_2': 5.8945201599865085}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,117] Trial 742 finished with value: 0.9497391496590376 and parameters: {'weight_class_0': 0.47761748790754566, 'weight_class_1': 8.201440793400511, 'weight_class_2': 5.876385148378875}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,148] Trial 743 finished with value: 0.9495329561690057 and parameters: {'weight_class_0': 0.46494483068305537, 'weight_class_1': 5.2816023274766675, 'weight_class_2': 5.7679725629290886}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,167] Trial 744 finished with value: 0.9497925658498084 and parameters: {'weight_class_0': 0.48367029330506617, 'weight_class_1': 8.107891993697823, 'weight_class_2': 5.7748543222747335}. Best is trial 673 with value: 0.949874946749033.

Best trial: 673. Best value: 0.949875:  75%|███████████████████████████████████████████████████████████████████████████████████████████████████▌                                | 754/1000 [00:14<00:05, 46.78it/s]

[I 2026-07-05 15:03:27,182] Trial 746 finished with value: 0.9468150104245426 and parameters: {'weight_class_0': 0.18322946990569172, 'weight_class_1': 8.148847536944345, 'weight_class_2': 5.7527416323548515}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,189] Trial 745 finished with value: 0.9496987272142832 and parameters: {'weight_class_0': 0.4514115690086701, 'weight_class_1': 8.094187037767693, 'weight_class_2': 5.754200833006292}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,216] Trial 747 finished with value: 0.9430902018654909 and parameters: {'weight_class_0': 0.11935789958267962, 'weight_class_1': 7.884943124460741, 'weight_class_2': 6.186327686499806}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,221] Trial 748 finished with value: 0.9490836167571222 and parameters: {'weight_class_0': 0.7624616388641942, 'weight_class_1': 8.269153481985818, 'weight_class_2': 5.761467135735202}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,250] Trial 749 finished with value: 0.9489427709731727 and parameters: {'weight_class_0': 0.8462066428061592, 'weight_class_1': 8.194586994395461, 'weight_class_2': 6.201399221031089}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,275] Trial 751 finished with value: 0.9463279243182345 and parameters: {'weight_class_0': 0.17276812611680015, 'weight_class_1': 8.141142976215475, 'weight_class_2': 6.195050742438375}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,332] Trial 753 finished with value: 0.9436702866995609 and parameters: {'weight_class_0': 0.1273791385258648, 'weight_class_1': 8.097716908713668, 'weight_class_2': 6.1573687701252435}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,335] Trial 750 finished with value: 0.9442743415291179 and parameters: {'weight_class_0': 0.1358585235832565, 'weight_class_1': 8.227745750956343, 'weight_class_2': 6.202177466057286}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,363] Trial 752 finished with value: 0.9449264153523037 and parameters: {'weight_class_0': 0.1440604415861601, 'weight_class_1': 8.119928583872005, 'weight_class_2': 6.31848409968691}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,367] Trial 754 finished with value: 0.9446454948500852 and parameters: {'weight_class_0': 0.13832449920641082, 'weight_class_1': 8.17922238558253, 'weight_class_2': 0.78730281409526}. Best is trial 673 with value: 0.949874946749033.

Best trial: 673. Best value: 0.949875:  76%|████████████████████████████████████████████████████████████████████████████████████████████████████▉                               | 765/1000 [00:14<00:04, 49.07it/s]

[I 2026-07-05 15:03:27,395] Trial 755 finished with value: 0.949163535599296 and parameters: {'weight_class_0': 0.7975986219302578, 'weight_class_1': 8.380120040906293, 'weight_class_2': 6.216436977293532}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,430] Trial 756 finished with value: 0.9460656485025843 and parameters: {'weight_class_0': 0.8316100624414323, 'weight_class_1': 3.714670332908452, 'weight_class_2': 6.214431862268914}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,449] Trial 757 finished with value: 0.9496709323689085 and parameters: {'weight_class_0': 0.6539218152854912, 'weight_class_1': 8.341991524507904, 'weight_class_2': 6.204765886754449}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,451] Trial 758 finished with value: 0.9491587696391779 and parameters: {'weight_class_0': 0.7864057545921849, 'weight_class_1': 8.766067355887305, 'weight_class_2': 6.220373015325377}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,473] Trial 759 finished with value: 0.9491881105302374 and parameters: {'weight_class_0': 0.8015341445760705, 'weight_class_1': 8.422480786082941, 'weight_class_2': 6.37151915027234}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,488] Trial 760 finished with value: 0.949372018417885 and parameters: {'weight_class_0': 0.7754755394724173, 'weight_class_1': 8.422147458001161, 'weight_class_2': 6.327313214242388}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,496] Trial 761 finished with value: 0.9493428997185109 and parameters: {'weight_class_0': 0.7894839045793653, 'weight_class_1': 8.437019312460668, 'weight_class_2': 6.403102023887599}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,521] Trial 762 finished with value: 0.9492973574543878 and parameters: {'weight_class_0': 0.7936433772473266, 'weight_class_1': 8.419003967847072, 'weight_class_2': 6.384643301095169}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,567] Trial 763 finished with value: 0.9494386337923718 and parameters: {'weight_class_0': 0.7774105494817772, 'weight_class_1': 8.434860058253397, 'weight_class_2': 6.407683503427118}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,583] Trial 764 finished with value: 0.9495022947182918 and parameters: {'weight_class_0': 0.7465605401250242, 'weight_class_1': 8.410715683591437, 'weight_class_2': 6.469522733643947}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,603] Trial 765 finished with value: 0.9494222162414907 and parameters: {'weight_class_0': 0.7777475059979633, 'weight_class_1': 8.737737736875237, 'weight_class_2': 6.416813098382822}. Best is trial 673 with value: 0.949874946749033.

Best trial: 673. Best value: 0.949875:  78%|██████████████████████████████████████████████████████████████████████████████████████████████████████▍                             | 776/1000 [00:15<00:04, 47.21it/s]

[I 2026-07-05 15:03:27,650] Trial 767 finished with value: 0.9494576208352639 and parameters: {'weight_class_0': 0.7693101863333927, 'weight_class_1': 8.802056305412703, 'weight_class_2': 6.3844383484866345}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,660] Trial 766 finished with value: 0.9494650769141634 and parameters: {'weight_class_0': 0.7609067493586177, 'weight_class_1': 8.761373188617194, 'weight_class_2': 6.367001892089056}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,664] Trial 768 finished with value: 0.9495204068932632 and parameters: {'weight_class_0': 0.7498195004197789, 'weight_class_1': 8.72052058811615, 'weight_class_2': 6.446287913154632}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,689] Trial 769 finished with value: 0.9497185619881207 and parameters: {'weight_class_0': 0.6756070873283289, 'weight_class_1': 8.917852625054715, 'weight_class_2': 6.877211773266868}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,721] Trial 771 finished with value: 0.9462656600753242 and parameters: {'weight_class_0': 1.4231935963817195, 'weight_class_1': 8.773212639280574, 'weight_class_2': 6.855287880500466}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,722] Trial 770 finished with value: 0.9498517560371077 and parameters: {'weight_class_0': 0.622630840718895, 'weight_class_1': 8.772077962030648, 'weight_class_2': 6.822801361587904}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,738] Trial 773 finished with value: 0.9497761465050406 and parameters: {'weight_class_0': 0.656553227077664, 'weight_class_1': 8.834354029736215, 'weight_class_2': 6.786998633720772}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,752] Trial 772 finished with value: 0.9498138371991831 and parameters: {'weight_class_0': 0.6021119580274406, 'weight_class_1': 8.766815551605921, 'weight_class_2': 6.804203714755238}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,790] Trial 774 finished with value: 0.9498192109166088 and parameters: {'weight_class_0': 0.6333408854614586, 'weight_class_1': 8.748910086776265, 'weight_class_2': 6.9225037612773805}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,816] Trial 775 finished with value: 0.9489268642231764 and parameters: {'weight_class_0': 0.32206731464392235, 'weight_class_1': 8.771658108500539, 'weight_class_2': 6.08621919989719}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,824] Trial 776 finished with value: 0.9488834607609209 and parameters: {'weight_class_0': 0.34253664783012167, 'weight_class_1': 8.852271690656623, 'weight_class_2': 6.803810896863808}. Best is trial 673 with value: 0.949874946749033.

[I 2026-07-05 15:03:27,845] Trial 777 finished with value: 0.9486203111329666 and parameters: {'weight_class_0': 0.3161392018833903, 'weight_class_1': 8.800830683886112, 'weight_class_2': 6.912369019628062}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,865] Trial 778 finished with value: 0.9485551132103899 and parameters: {'weight_class_0': 0.3124390558153722, 'weight_class_1': 9.074748652446512, 'weight_class_2': 6.888435284121366}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,904] Trial 779 finished with value: 0.9459482409717116 and parameters: {'weight_class_0': 1.483135373123976, 'weight_class_1': 9.014479515718172, 'weight_class_2': 6.876440570873059}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,918] Trial 780 finished with value: 0.946206524465047 and parameters: {'weight_class_0': 1.4392183775963718, 'weight_class_1': 9.018394151334633, 'weight_class_2': 6.7777164905205085}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,937] Trial 781 finished with value: 0.9491000790140897 and parameters: {'weight_class_0': 0.3476175102792666, 'weight_class_1': 7.870743959694328, 'weight_class_2': 6.812883158863062}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,946] Trial 782 finished with value: 0.9492714441002542 and parameters: {'weight_class_0': 0.3635199987248331, 'weight_class_1': 7.814331119148155, 'weight_class_2': 6.825137050696725}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,980] Trial 783 finished with value: 0.9495775410544359 and parameters: {'weight_class_0': 0.44210026623536147, 'weight_class_1': 7.807309063448017, 'weight_class_2': 6.714165965812128}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:27,981] Trial 784 finished with value: 0.9488797104470877 and parameters: {'weight_class_0': 0.33159151354325034, 'weight_class_1': 7.904915432584195, 'weight_class_2': 6.889516862413796}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:28,012] Trial 785 finished with value: 0.9489304935685371 and parameters: {'weight_class_0': 0.3367305279285019, 'weight_class_1': 7.908460039299572, 'weight_class_2': 6.8411004478250605}. Best is trial 673 with value: 0.949874946749033.

Best trial: 673. Best value: 0.949875:  80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▏                          | 797/1000 [00:15<00:04, 48.24it/s]

[I 2026-07-05 15:03:28,066] Trial 787 finished with value: 0.9432644334563435 and parameters: {'weight_class_0': 0.3649167748942329, 'weight_class_1': 1.207673293912002, 'weight_class_2': 6.678795231321271}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:28,068] Trial 788 finished with value: 0.9497324470066283 and parameters: {'weight_class_0': 0.5387246827861398, 'weight_class_1': 7.9306131212364805, 'weight_class_2': 6.60444918284159}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:28,070] Trial 786 finished with value: 0.9488109203520946 and parameters: {'weight_class_0': 0.31872537985742805, 'weight_class_1': 7.908095519233409, 'weight_class_2': 6.604768824434052}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:28,099] Trial 789 finished with value: 0.9497972777468879 and parameters: {'weight_class_0': 0.5455540863369921, 'weight_class_1': 8.529809939403034, 'weight_class_2': 6.632732371994865}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:28,119] Trial 790 finished with value: 0.9497424066923578 and parameters: {'weight_class_0': 0.5322467624441078, 'weight_class_1': 7.771767905237364, 'weight_class_2': 6.575797578321079}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:28,151] Trial 791 finished with value: 0.949774472127627 and parameters: {'weight_class_0': 0.5702967376681407, 'weight_class_1': 8.493671271024278, 'weight_class_2': 6.619315264756923}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:28,163] Trial 792 finished with value: 0.9498030857576579 and parameters: {'weight_class_0': 0.5832647296788881, 'weight_class_1': 8.537865018043536, 'weight_class_2': 6.617937660760427}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:28,185] Trial 793 finished with value: 0.9498006863320027 and parameters: {'weight_class_0': 0.5818941217325431, 'weight_class_1': 8.542255130940491, 'weight_class_2': 6.586868581377445}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:28,202] Trial 794 finished with value: 0.9487080532923448 and parameters: {'weight_class_0': 0.9542365144154122, 'weight_class_1': 8.500161220948199, 'weight_class_2': 6.623036893157814}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:28,217] Trial 796 finished with value: 0.9486924848551093 and parameters: {'weight_class_0': 0.958154678059565, 'weight_class_1': 8.57180747651828, 'weight_class_2': 6.583128478322017}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:28,240] Trial 795 finished with value: 0.9498544706225468 and parameters: {'weight_class_0': 0.6021379723059971, 'weight_class_1': 8.50259864873538, 'weight_class_2': 6.565665824412077}. Best is trial 673 with value: 0.949874946749033.

Best trial: 673. Best value: 0.949875:  80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▎                         | 805/1000 [00:15<00:04, 46.30it/s]

[I 2026-07-05 15:03:28,250] Trial 797 finished with value: 0.9485943921650503 and parameters: {'weight_class_0': 0.9707759133475423, 'weight_class_1': 8.49981644942938, 'weight_class_2': 6.518633836949067}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:28,276] Trial 798 finished with value: 0.9481533308092027 and parameters: {'weight_class_0': 0.9964044610282493, 'weight_class_1': 8.558616228398678, 'weight_class_2': 6.05534222531806}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:28,336] Trial 799 finished with value: 0.9483248811814727 and parameters: {'weight_class_0': 0.9682557130086671, 'weight_class_1': 8.547872452251267, 'weight_class_2': 6.099336302124147}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:28,350] Trial 800 finished with value: 0.9483417162717122 and parameters: {'weight_class_0': 0.9629750634069578, 'weight_class_1': 8.56759372600026, 'weight_class_2': 6.076034732120808}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:28,356] Trial 801 finished with value: 0.9487581332082363 and parameters: {'weight_class_0': 0.9314266797117956, 'weight_class_1': 8.535716163247498, 'weight_class_2': 6.477660144139794}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:28,418] Trial 802 finished with value: 0.9483333636800877 and parameters: {'weight_class_0': 0.9860345118762216, 'weight_class_1': 9.157899666785934, 'weight_class_2': 6.079866980821569}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:28,419] Trial 803 finished with value: 0.9483266722740661 and parameters: {'weight_class_0': 0.9965180864625797, 'weight_class_1': 9.141782243258673, 'weight_class_2': 6.1926493535949865}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:28,422] Trial 804 finished with value: 0.948605710793331 and parameters: {'weight_class_0': 0.9160949099239388, 'weight_class_1': 9.251564882387768, 'weight_class_2': 6.015686400682554}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:28,451] Trial 805 finished with value: 0.9484976870964674 and parameters: {'weight_class_0': 0.9443747504509238, 'weight_class_1': 9.142023414547245, 'weight_class_2': 6.059651265896225}. Best is trial 673 with value: 0.949874946749033.

Best trial: 673. Best value: 0.949875:  82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▌                        | 815/1000 [00:15<00:03, 47.22it/s]

[I 2026-07-05 15:03:28,490] Trial 806 finished with value: 0.9486838180211569 and parameters: {'weight_class_0': 0.9039301573447086, 'weight_class_1': 9.16773006644253, 'weight_class_2': 6.062251634916234}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:28,493] Trial 807 finished with value: 0.9491023092647817 and parameters: {'weight_class_0': 0.9120659495501411, 'weight_class_1': 9.200109196832248, 'weight_class_2': 7.07989814979107}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:28,508] Trial 808 finished with value: 0.946163618635068 and parameters: {'weight_class_0': 0.1716939603624506, 'weight_class_1': 8.295648132283544, 'weight_class_2': 6.403424584204143}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:28,519] Trial 809 finished with value: 0.943669377036051 and parameters: {'weight_class_0': 0.14150129312865595, 'weight_class_1': 9.15625644173848, 'weight_class_2': 6.402984360466771}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:28,555] Trial 810 finished with value: 0.9439630557811688 and parameters: {'weight_class_0': 0.14807567785341252, 'weight_class_1': 9.191315405432508, 'weight_class_2': 7.00329060007298}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:28,581] Trial 811 finished with value: 0.7965207705782441 and parameters: {'weight_class_0': 0.025426266830304023, 'weight_class_1': 9.140011270427799, 'weight_class_2': 7.065401029352164}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:28,592] Trial 812 finished with value: 0.9498248423331721 and parameters: {'weight_class_0': 0.664958086108543, 'weight_class_1': 9.126117028840943, 'weight_class_2': 7.178700591694892}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:28,635] Trial 813 finished with value: 0.9391127388523123 and parameters: {'weight_class_0': 0.10932542340436341, 'weight_class_1': 9.189405851404752, 'weight_class_2': 6.342873984508381}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:28,652] Trial 814 finished with value: 0.8030760947345806 and parameters: {'weight_class_0': 0.02509048419586113, 'weight_class_1': 8.33072955612338, 'weight_class_2': 7.0745837582578615}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:28,659] Trial 815 finished with value: 0.8980378589262648 and parameters: {'weight_class_0': 0.05210042791601993, 'weight_class_1': 8.96748621894164, 'weight_class_2': 7.113176668323221}. Best is trial 673 with value: 0.949874946749033.

[I 2026-07-05 15:03:28,686] Trial 816 finished with value: 0.9444122143166278 and parameters: {'weight_class_0': 0.13985084589640973, 'weight_class_1': 8.32451566690871, 'weight_class_2': 6.377164563742548}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:28,704] Trial 817 finished with value: 0.9395282337969149 and parameters: {'weight_class_0': 0.10578705409419187, 'weight_class_1': 8.29994004247544, 'weight_class_2': 7.189381136605761}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:28,724] Trial 818 finished with value: 0.6692999933916265 and parameters: {'weight_class_0': 0.007357470383035358, 'weight_class_1': 8.923566934195248, 'weight_class_2': 7.107001631482977}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:28,752] Trial 819 finished with value: 0.6621443816742931 and parameters: {'weight_class_0': 0.005199378397431675, 'weight_class_1': 8.287304752863824, 'weight_class_2': 7.044627073324427}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:28,758] Trial 820 finished with value: 0.9494357409221017 and parameters: {'weight_class_0': 0.6578162782239381, 'weight_class_1': 8.241930339345679, 'weight_class_2': 9.714313857901043}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:28,807] Trial 822 finished with value: 0.9474556811265527 and parameters: {'weight_class_0': 1.2996510157973051, 'weight_class_1': 9.33360375006554, 'weight_class_2': 7.024543911290526}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:28,810] Trial 821 finished with value: 0.90061143343359 and parameters: {'weight_class_0': 5.277376950151946, 'weight_class_1': 8.961000924459128, 'weight_class_2': 6.384739607455235}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:28,836] Trial 823 finished with value: 0.9498145625968403 and parameters: {'weight_class_0': 0.6768944083035706, 'weight_class_1': 9.426020480614733, 'weight_class_2': 7.030167387949131}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:28,846] Trial 824 finished with value: 0.92275275146569 and parameters: {'weight_class_0': 3.6924235272722647, 'weight_class_1': 9.400563077811656, 'weight_class_2': 6.983453266161909}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:28,880] Trial 825 finished with value: 0.9498047369560308 and parameters: {'weight_class_0': 0.621342906061808, 'weight_class_1': 9.407111291614429, 'weight_class_2': 6.959006080789254}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:28,883] Trial 826 finished with value: 0.9498430888614536 and parameters: {'weight_class_0': 0.6626490076342757, 'weight_class_1': 9.386454153654418, 'weight_class_2': 7.313478260565563}. Best is trial 673 with value: 0.949874946749033.

[I 2026-07-05 15:03:28,913] Trial 827 finished with value: 0.9496286675160382 and parameters: {'weight_class_0': 0.6519807176199137, 'weight_class_1': 7.205289249848336, 'weight_class_2': 7.362636170180175}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:28,942] Trial 828 finished with value: 0.9476811422244121 and parameters: {'weight_class_0': 1.2780860851162972, 'weight_class_1': 9.44795137807209, 'weight_class_2': 7.303424987353052}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:28,971] Trial 830 finished with value: 0.9251966464136817 and parameters: {'weight_class_0': 3.58921205287547, 'weight_class_1': 9.326037585305855, 'weight_class_2': 7.37400513545192}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:28,977] Trial 829 finished with value: 0.9474311253887233 and parameters: {'weight_class_0': 1.2902393691035337, 'weight_class_1': 8.958210662549527, 'weight_class_2': 7.411669961259793}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:29,007] Trial 831 finished with value: 0.9460648377294744 and parameters: {'weight_class_0': 1.3018890594800436, 'weight_class_1': 9.321101553235154, 'weight_class_2': 5.690834085615201}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:29,022] Trial 832 finished with value: 0.9494481742732511 and parameters: {'weight_class_0': 0.687121850702758, 'weight_class_1': 9.340477749579858, 'weight_class_2': 5.727850888739991}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:29,060] Trial 833 finished with value: 0.9498077006104798 and parameters: {'weight_class_0': 0.642506160380509, 'weight_class_1': 9.442021756184579, 'weight_class_2': 7.234762248376895}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:29,074] Trial 835 finished with value: 0.9497947147827283 and parameters: {'weight_class_0': 0.667792437063381, 'weight_class_1': 8.933287303366106, 'weight_class_2': 7.320073353454322}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:29,082] Trial 834 finished with value: 0.9498026882670968 and parameters: {'weight_class_0': 0.6679573099331861, 'weight_class_1': 8.907252792746839, 'weight_class_2': 7.341955916075375}. Best is trial 673 with value: 0.949874946749033.

[I 2026-07-05 15:03:29,090] Trial 836 finished with value: 0.9496983156347355 and parameters: {'weight_class_0': 0.7680951758911414, 'weight_class_1': 9.414987433434616, 'weight_class_2': 7.381493878150869}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:29,131] Trial 837 finished with value: 0.9479430757209714 and parameters: {'weight_class_0': 1.2319272571349629, 'weight_class_1': 9.448694470096994, 'weight_class_2': 7.443391255728011}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:29,152] Trial 838 finished with value: 0.9496843261884343 and parameters: {'weight_class_0': 0.7553307729641834, 'weight_class_1': 9.438841569876045, 'weight_class_2': 7.263882451786445}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:29,182] Trial 839 finished with value: 0.9496590956566079 and parameters: {'weight_class_0': 0.7588151965779204, 'weight_class_1': 8.983798133483107, 'weight_class_2': 7.295849503346233}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:29,228] Trial 840 finished with value: 0.9497118222655638 and parameters: {'weight_class_0': 0.7387332206461387, 'weight_class_1': 9.443547798427234, 'weight_class_2': 7.259420771657478}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:29,229] Trial 841 finished with value: 0.9496983199497994 and parameters: {'weight_class_0': 0.7488757589480026, 'weight_class_1': 9.595769967690686, 'weight_class_2': 7.245470700427667}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:29,241] Trial 842 finished with value: 0.8784066982333879 and parameters: {'weight_class_0': 4.183454164582574, 'weight_class_1': 1.6077922582551194, 'weight_class_2': 7.513791047718452}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:29,259] Trial 843 finished with value: 0.9497157946682856 and parameters: {'weight_class_0': 0.7462431361147893, 'weight_class_1': 9.568669860481522, 'weight_class_2': 7.358532779513801}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:29,273] Trial 844 finished with value: 0.9497258991390535 and parameters: {'weight_class_0': 0.7015036608159076, 'weight_class_1': 9.032071990420103, 'weight_class_2': 7.17081844449219}. Best is trial 673 with value: 0.949874946749033.

Best trial: 673. Best value: 0.949875:  85%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                   | 853/1000 [00:16<00:03, 41.95it/s]

[I 2026-07-05 15:03:29,324] Trial 845 finished with value: 0.9493263996983486 and parameters: {'weight_class_0': 0.42423551320424246, 'weight_class_1': 9.549086406289726, 'weight_class_2': 7.2307289000106945}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:29,332] Trial 846 finished with value: 0.8960535644179467 and parameters: {'weight_class_0': 6.093679645803905, 'weight_class_1': 9.590292952982729, 'weight_class_2': 6.767139263078968}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:29,375] Trial 847 finished with value: 0.8944579430609306 and parameters: {'weight_class_0': 6.1547020172163, 'weight_class_1': 9.06933524969079, 'weight_class_2': 6.80726615287062}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:29,416] Trial 848 finished with value: 0.9492296340055643 and parameters: {'weight_class_0': 0.386507303635114, 'weight_class_1': 9.049376013020328, 'weight_class_2': 6.795918401387844}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:29,421] Trial 849 finished with value: 0.9493186857147181 and parameters: {'weight_class_0': 0.40317825825764775, 'weight_class_1': 9.062749574792054, 'weight_class_2': 6.916829822182239}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:29,469] Trial 850 finished with value: 0.9492077223160799 and parameters: {'weight_class_0': 0.37498497058645586, 'weight_class_1': 9.132712994175057, 'weight_class_2': 6.488970813354583}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:29,485] Trial 851 finished with value: 0.949216511714512 and parameters: {'weight_class_0': 0.3784671006207231, 'weight_class_1': 9.04718706727524, 'weight_class_2': 6.74425091217718}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:29,494] Trial 852 finished with value: 0.9495275999430269 and parameters: {'weight_class_0': 0.4329208636708806, 'weight_class_1': 9.116458175953568, 'weight_class_2': 6.79990268803256}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:29,534] Trial 853 finished with value: 0.894888871917177 and parameters: {'weight_class_0': 6.097149434636284, 'weight_class_1': 9.076306125472724, 'weight_class_2': 6.809300062313534}. Best is trial 673 with value: 0.949874946749033.

Best trial: 673. Best value: 0.949875:  86%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                  | 863/1000 [00:17<00:03, 44.28it/s]

[I 2026-07-05 15:03:29,546] Trial 854 finished with value: 0.9494636615365365 and parameters: {'weight_class_0': 0.4195733872081879, 'weight_class_1': 9.063503563067593, 'weight_class_2': 6.794338430393594}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:29,562] Trial 855 finished with value: 0.9491720431663865 and parameters: {'weight_class_0': 0.3734174707745025, 'weight_class_1': 9.101286028202326, 'weight_class_2': 6.723607940812906}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:29,600] Trial 856 finished with value: 0.94930481088132 and parameters: {'weight_class_0': 0.3976702251171551, 'weight_class_1': 9.106349617725852, 'weight_class_2': 6.765558415676356}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:29,633] Trial 857 finished with value: 0.8726043933203079 and parameters: {'weight_class_0': 8.856856890503735, 'weight_class_1': 8.776979025399214, 'weight_class_2': 6.424733326384964}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:29,643] Trial 858 finished with value: 0.9494204552235543 and parameters: {'weight_class_0': 0.39642993331271237, 'weight_class_1': 8.82596200113704, 'weight_class_2': 6.4682096624253145}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:29,644] Trial 859 finished with value: 0.9497395067103026 and parameters: {'weight_class_0': 0.47425236564342876, 'weight_class_1': 8.800023706604549, 'weight_class_2': 6.49977518999335}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:29,699] Trial 860 finished with value: 0.9496703053982091 and parameters: {'weight_class_0': 0.4994072347325289, 'weight_class_1': 8.766209702126977, 'weight_class_2': 6.52942739754026}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:29,703] Trial 861 finished with value: 0.9497400108004187 and parameters: {'weight_class_0': 0.5090999269845088, 'weight_class_1': 8.772402017556805, 'weight_class_2': 6.27519664089817}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:29,713] Trial 862 finished with value: 0.9413861606189053 and parameters: {'weight_class_0': 1.1114031214693387, 'weight_class_1': 8.778257958232393, 'weight_class_2': 3.168553333977971}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:29,735] Trial 863 finished with value: 0.878506186951521 and parameters: {'weight_class_0': 7.788648557740818, 'weight_class_1': 8.76214984857667, 'weight_class_2': 6.293763343655757}. Best is trial 673 with value: 0.949874946749033.

[I 2026-07-05 15:03:29,779] Trial 864 finished with value: 0.947922828483442 and parameters: {'weight_class_0': 1.0864133040442496, 'weight_class_1': 8.77625018029071, 'weight_class_2': 6.328026248050088}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:29,792] Trial 866 finished with value: 0.9480757321511247 and parameters: {'weight_class_0': 1.043518165595413, 'weight_class_1': 8.757463404080442, 'weight_class_2': 6.283757454533198}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:29,814] Trial 865 finished with value: 0.9480486222153718 and parameters: {'weight_class_0': 1.0542994527945626, 'weight_class_1': 8.827221184401772, 'weight_class_2': 6.340584484735392}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:29,822] Trial 867 finished with value: 0.9480349887383118 and parameters: {'weight_class_0': 1.0452637350441352, 'weight_class_1': 8.756126526671984, 'weight_class_2': 6.246292076043316}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:29,855] Trial 868 finished with value: 0.9305236893931634 and parameters: {'weight_class_0': 1.0959054917598288, 'weight_class_1': 8.813482270287059, 'weight_class_2': 1.9596366925632118}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:29,885] Trial 869 finished with value: 0.9478089381303413 and parameters: {'weight_class_0': 1.099741516801009, 'weight_class_1': 8.73092696965178, 'weight_class_2': 6.25644780884092}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:29,909] Trial 871 finished with value: 0.8794894304122606 and parameters: {'weight_class_0': 7.643589688121182, 'weight_class_1': 8.725313980131697, 'weight_class_2': 6.297912952817954}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:29,934] Trial 872 finished with value: 0.9477454125779842 and parameters: {'weight_class_0': 1.1401517242534, 'weight_class_1': 9.292287435701368, 'weight_class_2': 6.241207026455116}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:29,937] Trial 870 finished with value: 0.9055450197296512 and parameters: {'weight_class_0': 1.095057856989981, 'weight_class_1': 0.6945572843833574, 'weight_class_2': 6.227981491436121}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:29,950] Trial 873 finished with value: 0.7045493191392999 and parameters: {'weight_class_0': 0.8474937393623543, 'weight_class_1': 8.732048166989468, 'weight_class_2': 0.004511939380269503}. Best is trial 673 with value: 0.949874946749033.

[I 2026-07-05 15:03:29,954] Trial 874 finished with value: 0.9480167812178868 and parameters: {'weight_class_0': 1.0428596616179278, 'weight_class_1': 8.703718650284653, 'weight_class_2': 6.2000656453044565}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:29,995] Trial 875 finished with value: 0.9478644333877752 and parameters: {'weight_class_0': 1.1097695833405288, 'weight_class_1': 9.287629538930283, 'weight_class_2': 6.253209866220575}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:30,034] Trial 877 finished with value: 0.9490399808770462 and parameters: {'weight_class_0': 0.8763077562699972, 'weight_class_1': 9.297825093672976, 'weight_class_2': 6.52475143521183}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:30,037] Trial 876 finished with value: 0.9492994322059868 and parameters: {'weight_class_0': 0.8146302592358753, 'weight_class_1': 9.323919131898126, 'weight_class_2': 6.581271665599101}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:30,060] Trial 878 finished with value: 0.9491630451739481 and parameters: {'weight_class_0': 0.8455677321931561, 'weight_class_1': 9.296754999150707, 'weight_class_2': 6.563205678376757}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:30,083] Trial 879 finished with value: 0.9492267106205254 and parameters: {'weight_class_0': 0.8301875171675875, 'weight_class_1': 9.2596293196089, 'weight_class_2': 6.622836014706215}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:30,133] Trial 881 finished with value: 0.9491632683858864 and parameters: {'weight_class_0': 0.8592427814178573, 'weight_class_1': 9.275938673936334, 'weight_class_2': 6.561928972333527}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:30,141] Trial 880 finished with value: 0.9498473261002301 and parameters: {'weight_class_0': 0.595075576221388, 'weight_class_1': 9.262535472943208, 'weight_class_2': 6.577226688956674}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:30,147] Trial 882 finished with value: 0.9493530383063171 and parameters: {'weight_class_0': 0.8027316870135872, 'weight_class_1': 9.276707049351222, 'weight_class_2': 6.519611913234179}. Best is trial 673 with value: 0.949874946749033.

Best trial: 673. Best value: 0.949875:  89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉              | 893/1000 [00:17<00:02, 46.31it/s]

[I 2026-07-05 15:03:30,173] Trial 883 finished with value: 0.9498252380221325 and parameters: {'weight_class_0': 0.5864825799551405, 'weight_class_1': 9.302482755290852, 'weight_class_2': 6.632023685906776}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:30,213] Trial 884 finished with value: 0.949839422001447 and parameters: {'weight_class_0': 0.5916952109378585, 'weight_class_1': 9.283207785378945, 'weight_class_2': 6.578648255650699}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:30,220] Trial 885 finished with value: 0.9498481944813252 and parameters: {'weight_class_0': 0.6155574921166923, 'weight_class_1': 9.731822298728295, 'weight_class_2': 6.545839577007185}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:30,249] Trial 886 finished with value: 0.9497620868918064 and parameters: {'weight_class_0': 0.5869891648742666, 'weight_class_1': 8.957971061575961, 'weight_class_2': 6.015353850179833}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:30,271] Trial 887 finished with value: 0.9498347515923756 and parameters: {'weight_class_0': 0.5933270051406697, 'weight_class_1': 8.96506083868624, 'weight_class_2': 6.595946306063903}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:30,279] Trial 888 finished with value: 0.949767948348835 and parameters: {'weight_class_0': 0.5855742262547282, 'weight_class_1': 9.782585024338196, 'weight_class_2': 6.0224555929360655}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:30,305] Trial 889 finished with value: 0.9497704256130693 and parameters: {'weight_class_0': 0.5711290837110096, 'weight_class_1': 8.95133168809951, 'weight_class_2': 6.98968437505277}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:30,316] Trial 890 finished with value: 0.949846633531994 and parameters: {'weight_class_0': 0.5570521667366796, 'weight_class_1': 8.987864628776444, 'weight_class_2': 6.017821459579179}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:30,339] Trial 891 finished with value: 0.9496691303021443 and parameters: {'weight_class_0': 0.6264243001539418, 'weight_class_1': 9.764596534297874, 'weight_class_2': 5.978661852403464}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:30,373] Trial 892 finished with value: 0.9480575977536644 and parameters: {'weight_class_0': 0.2777474413744843, 'weight_class_1': 9.684264210517194, 'weight_class_2': 6.940785407447334}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:30,390] Trial 894 finished with value: 0.9479541494905797 and parameters: {'weight_class_0': 0.27337241941100515, 'weight_class_1': 9.798400512887193, 'weight_class_2': 6.955297202717732}. Best is trial 673 with value: 0.949874946749033.

Best trial: 673. Best value: 0.949875:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████             | 902/1000 [00:17<00:02, 44.99it/s]

[I 2026-07-05 15:03:30,403] Trial 893 finished with value: 0.9470652746999222 and parameters: {'weight_class_0': 0.2314887710424589, 'weight_class_1': 9.852734820863889, 'weight_class_2': 6.913741701519222}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:30,455] Trial 895 finished with value: 0.947968385834129 and parameters: {'weight_class_0': 0.2651024209598063, 'weight_class_1': 9.902087718272641, 'weight_class_2': 5.984136826112938}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:30,457] Trial 896 finished with value: 0.9474718406935744 and parameters: {'weight_class_0': 0.24005307807527976, 'weight_class_1': 9.657254270500266, 'weight_class_2': 6.62308179574326}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:30,504] Trial 898 finished with value: 0.9476276086635784 and parameters: {'weight_class_0': 0.247638818497821, 'weight_class_1': 9.76432438322245, 'weight_class_2': 6.471306815498065}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:30,512] Trial 897 finished with value: 0.9481005324353765 and parameters: {'weight_class_0': 0.2704374438988253, 'weight_class_1': 9.449195925463922, 'weight_class_2': 6.512010648439789}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:30,519] Trial 899 finished with value: 0.9488253353921272 and parameters: {'weight_class_0': 0.3386968182831859, 'weight_class_1': 9.841749165397477, 'weight_class_2': 6.501366148477895}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:30,552] Trial 900 finished with value: 0.948723616548722 and parameters: {'weight_class_0': 0.3063991239542314, 'weight_class_1': 9.811159293354718, 'weight_class_2': 5.699194996871571}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:30,568] Trial 901 finished with value: 0.9065345583285073 and parameters: {'weight_class_0': 4.648075280822986, 'weight_class_1': 9.71834061789397, 'weight_class_2': 5.810420430178421}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:30,579] Trial 902 finished with value: 0.9481224827625562 and parameters: {'weight_class_0': 0.2745379248869533, 'weight_class_1': 9.98593804560074, 'weight_class_2': 5.81973346917776}. Best is trial 673 with value: 0.949874946749033.

[I 2026-07-05 15:03:30,599] Trial 903 finished with value: 0.9477922878846315 and parameters: {'weight_class_0': 0.24845465575028064, 'weight_class_1': 9.913762562327049, 'weight_class_2': 5.709826674789048}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:30,647] Trial 904 finished with value: 0.9481128563810106 and parameters: {'weight_class_0': 0.2692844720008376, 'weight_class_1': 9.84355105338496, 'weight_class_2': 5.708449203707671}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:30,655] Trial 905 finished with value: 0.9482998638106533 and parameters: {'weight_class_0': 0.27620491376621586, 'weight_class_1': 9.636594232576627, 'weight_class_2': 5.675984115739142}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:30,686] Trial 906 finished with value: 0.948986647351506 and parameters: {'weight_class_0': 0.34440848201292873, 'weight_class_1': 9.597050474566528, 'weight_class_2': 5.88875745211252}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:30,711] Trial 908 finished with value: 0.9497563394642126 and parameters: {'weight_class_0': 0.4980074892749681, 'weight_class_1': 9.925303484401079, 'weight_class_2': 5.696548859718215}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:30,743] Trial 909 finished with value: 0.9497977167997944 and parameters: {'weight_class_0': 0.5230475024005851, 'weight_class_1': 9.612857528606687, 'weight_class_2': 5.784666777595024}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:30,753] Trial 907 finished with value: 0.9497229634772646 and parameters: {'weight_class_0': 0.49664715318571556, 'weight_class_1': 9.576709046539108, 'weight_class_2': 5.767294324049463}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:30,777] Trial 910 finished with value: 0.9497292015691116 and parameters: {'weight_class_0': 0.5653214298061601, 'weight_class_1': 9.600405757562166, 'weight_class_2': 5.774332936198918}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:30,798] Trial 911 finished with value: 0.9435328217382651 and parameters: {'weight_class_0': 1.6675554854171528, 'weight_class_1': 9.595970596200782, 'weight_class_2': 6.102181603762939}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:30,815] Trial 912 finished with value: 0.949746128874561 and parameters: {'weight_class_0': 0.5409091126591312, 'weight_class_1': 9.529336020527483, 'weight_class_2': 6.107226621874646}. Best is trial 673 with value: 0.949874946749033.

[I 2026-07-05 15:03:30,848] Trial 913 finished with value: 0.949732591557614 and parameters: {'weight_class_0': 0.522913604596387, 'weight_class_1': 9.674653791528812, 'weight_class_2': 6.1070020280269315}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:30,868] Trial 914 finished with value: 0.9497419601372253 and parameters: {'weight_class_0': 0.52622530769704, 'weight_class_1': 9.629639726387932, 'weight_class_2': 6.087932834819154}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:30,879] Trial 915 finished with value: 0.949755043420421 and parameters: {'weight_class_0': 0.5472061430353106, 'weight_class_1': 9.541311683507601, 'weight_class_2': 6.154078220467426}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:30,917] Trial 916 finished with value: 0.9498415011709064 and parameters: {'weight_class_0': 0.5440432290390866, 'weight_class_1': 9.132894557357321, 'weight_class_2': 6.040584906117889}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:30,955] Trial 917 finished with value: 0.9497920603075073 and parameters: {'weight_class_0': 0.5587312667380007, 'weight_class_1': 9.578345825483877, 'weight_class_2': 6.10350504058952}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:30,979] Trial 919 finished with value: 0.9489952147377823 and parameters: {'weight_class_0': 0.8225159933866093, 'weight_class_1': 9.332483953211405, 'weight_class_2': 6.101446339563115}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:30,980] Trial 918 finished with value: 0.9497667330398133 and parameters: {'weight_class_0': 0.5996138889524594, 'weight_class_1': 9.519972865792505, 'weight_class_2': 6.132855453624136}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:30,994] Trial 920 finished with value: 0.9490544053285545 and parameters: {'weight_class_0': 0.8213750115409073, 'weight_class_1': 9.542628177981188, 'weight_class_2': 6.12025942023571}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:31,035] Trial 921 finished with value: 0.949093542667515 and parameters: {'weight_class_0': 0.8089751577975839, 'weight_class_1': 9.467158828420402, 'weight_class_2': 6.126751325444809}. Best is trial 673 with value: 0.949874946749033.

Best trial: 673. Best value: 0.949875:  93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊         | 930/1000 [00:18<00:01, 44.55it/s]

[I 2026-07-05 15:03:31,038] Trial 923 finished with value: 0.9495678425267572 and parameters: {'weight_class_0': 0.6980032876946427, 'weight_class_1': 9.332247500170283, 'weight_class_2': 6.0886306291045775}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:31,056] Trial 922 finished with value: 0.9489851283086178 and parameters: {'weight_class_0': 0.8278284986199151, 'weight_class_1': 9.49914339802349, 'weight_class_2': 6.1167118730446335}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:31,079] Trial 924 finished with value: 0.9491714086417994 and parameters: {'weight_class_0': 0.8076417157784193, 'weight_class_1': 9.371894699991715, 'weight_class_2': 6.165939873328321}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:31,113] Trial 926 finished with value: 0.949145719658361 and parameters: {'weight_class_0': 0.8237745552499262, 'weight_class_1': 9.332805483216747, 'weight_class_2': 6.3566468797109}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:31,119] Trial 925 finished with value: 0.9491655391637092 and parameters: {'weight_class_0': 0.8051741840028664, 'weight_class_1': 9.396229309265403, 'weight_class_2': 6.357366984500443}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:31,150] Trial 927 finished with value: 0.9492184813747283 and parameters: {'weight_class_0': 0.7739729558022497, 'weight_class_1': 9.376209270435428, 'weight_class_2': 6.000377163153405}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:31,163] Trial 928 finished with value: 0.9488768285626233 and parameters: {'weight_class_0': 0.8267368217470494, 'weight_class_1': 9.265430111506394, 'weight_class_2': 5.962751554321504}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:31,190] Trial 929 finished with value: 0.9488697388846932 and parameters: {'weight_class_0': 0.8374396001046167, 'weight_class_1': 9.309459860321478, 'weight_class_2': 5.955798532755379}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:31,223] Trial 930 finished with value: 0.9495347637607866 and parameters: {'weight_class_0': 0.7583797396560134, 'weight_class_1': 9.31323984229765, 'weight_class_2': 6.3769714518544385}. Best is trial 673 with value: 0.949874946749033.

Best trial: 673. Best value: 0.949875:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████        | 940/1000 [00:18<00:01, 43.29it/s]

[I 2026-07-05 15:03:31,245] Trial 931 finished with value: 0.9489460647731031 and parameters: {'weight_class_0': 0.8115738517690078, 'weight_class_1': 9.393772202885817, 'weight_class_2': 5.902889615951257}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:31,288] Trial 933 finished with value: 0.9494312749966346 and parameters: {'weight_class_0': 0.7744104715412048, 'weight_class_1': 9.227898791675445, 'weight_class_2': 6.351483641503824}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:31,303] Trial 932 finished with value: 0.9490055607704817 and parameters: {'weight_class_0': 0.8567399736808134, 'weight_class_1': 9.222153929578017, 'weight_class_2': 6.33449645897656}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:31,318] Trial 935 finished with value: 0.9496358500718367 and parameters: {'weight_class_0': 0.692407155845223, 'weight_class_1': 9.199022482836902, 'weight_class_2': 6.333715759093874}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:31,337] Trial 934 finished with value: 0.9489878419766008 and parameters: {'weight_class_0': 0.865684950770602, 'weight_class_1': 9.176396118995642, 'weight_class_2': 6.362960002496582}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:31,342] Trial 936 finished with value: 0.9496334521393921 and parameters: {'weight_class_0': 0.666948150319265, 'weight_class_1': 9.08399158824263, 'weight_class_2': 6.318755589947596}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:31,388] Trial 938 finished with value: 0.9497349772644436 and parameters: {'weight_class_0': 0.6548075387229163, 'weight_class_1': 9.170517659046125, 'weight_class_2': 6.389967702721838}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:31,400] Trial 937 finished with value: 0.9496772586128387 and parameters: {'weight_class_0': 0.4648723415777551, 'weight_class_1': 9.177678647951184, 'weight_class_2': 6.435151372329895}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:31,413] Trial 939 finished with value: 0.949468635180453 and parameters: {'weight_class_0': 0.4168315252108566, 'weight_class_1': 9.148128367564345, 'weight_class_2': 6.347451096674617}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:31,436] Trial 940 finished with value: 0.9496878246654618 and parameters: {'weight_class_0': 0.488981872079904, 'weight_class_1': 9.152186053062296, 'weight_class_2': 6.332944425700022}. Best is trial 673 with value: 0.949874946749033.

[I 2026-07-05 15:03:31,480] Trial 941 finished with value: 0.9495229729596725 and parameters: {'weight_class_0': 0.42554540094458654, 'weight_class_1': 9.0800353553517, 'weight_class_2': 6.68487460748885}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:31,501] Trial 942 finished with value: 0.9494846047114506 and parameters: {'weight_class_0': 0.4134831641308037, 'weight_class_1': 9.082880863095697, 'weight_class_2': 6.364595584372088}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:31,531] Trial 943 finished with value: 0.9496520383071472 and parameters: {'weight_class_0': 0.4584968952806755, 'weight_class_1': 9.066020954738116, 'weight_class_2': 6.663858039307457}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:31,558] Trial 944 finished with value: 0.9494798481628078 and parameters: {'weight_class_0': 0.4151629660852023, 'weight_class_1': 9.086999122594463, 'weight_class_2': 6.687737044430667}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:31,581] Trial 945 finished with value: 0.8682822244273432 and parameters: {'weight_class_0': 9.96315779691508, 'weight_class_1': 8.96516294246858, 'weight_class_2': 6.665214718836517}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:31,616] Trial 946 finished with value: 0.9496541694991398 and parameters: {'weight_class_0': 0.46260860283356503, 'weight_class_1': 8.918899584150957, 'weight_class_2': 6.68690976036287}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:31,632] Trial 947 finished with value: 0.945049051307958 and parameters: {'weight_class_0': 0.15952916059347455, 'weight_class_1': 8.96416703829414, 'weight_class_2': 6.713686431917697}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:31,641] Trial 948 finished with value: 0.9463787233095254 and parameters: {'weight_class_0': 0.18533578739096368, 'weight_class_1': 9.007741780096884, 'weight_class_2': 5.90925894815311}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:31,657] Trial 949 finished with value: 0.9477345096445055 and parameters: {'weight_class_0': 0.20182065700154905, 'weight_class_1': 6.021580613354385, 'weight_class_2': 6.674695012354067}. Best is trial 673 with value: 0.949874946749033.

Best trial: 673. Best value: 0.949875:  96%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌     | 959/1000 [00:19<00:00, 45.50it/s]

[I 2026-07-05 15:03:31,680] Trial 950 finished with value: 0.9462069725549421 and parameters: {'weight_class_0': 0.18555498494421102, 'weight_class_1': 8.998508440084969, 'weight_class_2': 6.705048801187372}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:31,688] Trial 951 finished with value: 0.9468763113438508 and parameters: {'weight_class_0': 0.20698121208292614, 'weight_class_1': 8.973302807137177, 'weight_class_2': 6.739732451554832}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:31,723] Trial 952 finished with value: 0.9474279750403974 and parameters: {'weight_class_0': 0.19081300201335194, 'weight_class_1': 6.721989610481552, 'weight_class_2': 6.676627580219113}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:31,756] Trial 954 finished with value: 0.9496109714330924 and parameters: {'weight_class_0': 0.6270090332385267, 'weight_class_1': 8.887441736906363, 'weight_class_2': 5.585404850124097}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:31,771] Trial 953 finished with value: 0.9459599932104599 and parameters: {'weight_class_0': 0.17914934391400494, 'weight_class_1': 8.946287479172899, 'weight_class_2': 6.710195782387018}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:31,785] Trial 955 finished with value: 0.9444886544477794 and parameters: {'weight_class_0': 0.1450542864806405, 'weight_class_1': 8.947018983976273, 'weight_class_2': 5.6046529434633605}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:31,810] Trial 956 finished with value: 0.9464395581673468 and parameters: {'weight_class_0': 0.1866666105486947, 'weight_class_1': 8.950462811644226, 'weight_class_2': 5.900413709698917}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:31,818] Trial 957 finished with value: 0.9430146789792647 and parameters: {'weight_class_0': 0.13077440957750308, 'weight_class_1': 8.973724640906802, 'weight_class_2': 5.990127674515089}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:31,855] Trial 958 finished with value: 0.9480680565976662 and parameters: {'weight_class_0': 0.23244582840784073, 'weight_class_1': 8.07809650038226, 'weight_class_2': 5.877574892255389}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:31,859] Trial 959 finished with value: 0.9474773751450088 and parameters: {'weight_class_0': 1.0539283651917954, 'weight_class_1': 7.714141917546412, 'weight_class_2': 5.5841371378610365}. Best is trial 673 with value: 0.949874946749033.

[I 2026-07-05 15:03:31,895] Trial 961 finished with value: 0.9495439558489879 and parameters: {'weight_class_0': 0.6483058285090539, 'weight_class_1': 8.08210586968424, 'weight_class_2': 5.618681077073885}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:31,904] Trial 960 finished with value: 0.9496028857131759 and parameters: {'weight_class_0': 0.6202228154557451, 'weight_class_1': 8.031739682149396, 'weight_class_2': 5.620742990811589}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:31,956] Trial 962 finished with value: 0.947768009123033 and parameters: {'weight_class_0': 1.0255433046225964, 'weight_class_1': 8.107473886672311, 'weight_class_2': 5.672528674103941}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:31,997] Trial 964 finished with value: 0.9267010238764986 and parameters: {'weight_class_0': 0.9961765598107084, 'weight_class_1': 8.023928253327469, 'weight_class_2': 1.5703224399596816}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:32,008] Trial 963 finished with value: 0.9449342339070231 and parameters: {'weight_class_0': 1.4150311075264552, 'weight_class_1': 8.110508766476514, 'weight_class_2': 5.9089556763944495}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:32,025] Trial 965 finished with value: 0.9480768968975121 and parameters: {'weight_class_0': 0.9748405448065034, 'weight_class_1': 8.006066133247874, 'weight_class_2': 5.984759863475547}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:32,034] Trial 966 finished with value: 0.9479389941434601 and parameters: {'weight_class_0': 0.9915741699350238, 'weight_class_1': 8.004541849251927, 'weight_class_2': 5.860188995963602}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:32,034] Trial 967 finished with value: 0.9480642308863101 and parameters: {'weight_class_0': 0.9908109872617857, 'weight_class_1': 8.431253145639975, 'weight_class_2': 5.848491848523437}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:32,091] Trial 968 finished with value: 0.9469153399032543 and parameters: {'weight_class_0': 1.3010246824238934, 'weight_class_1': 8.593091543759863, 'weight_class_2': 6.506770389072751}. Best is trial 673 with value: 0.949874946749033.

Best trial: 673. Best value: 0.949875:  98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉   | 977/1000 [00:19<00:00, 43.51it/s]

[I 2026-07-05 15:03:32,097] Trial 969 finished with value: 0.947049467062156 and parameters: {'weight_class_0': 1.2420051254298112, 'weight_class_1': 8.011166200200792, 'weight_class_2': 6.483423602060442}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:32,108] Trial 970 finished with value: 0.9482427128978905 and parameters: {'weight_class_0': 1.0027708835492353, 'weight_class_1': 8.54569073507172, 'weight_class_2': 6.2280164907133395}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:32,127] Trial 971 finished with value: 0.9458268304894428 and parameters: {'weight_class_0': 1.3866032027700284, 'weight_class_1': 8.57908684824255, 'weight_class_2': 6.216449307877622}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:32,170] Trial 972 finished with value: 0.9475154359461184 and parameters: {'weight_class_0': 1.1951505987739643, 'weight_class_1': 8.602864002393183, 'weight_class_2': 6.503417017543227}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:32,186] Trial 974 finished with value: 0.9459341942703574 and parameters: {'weight_class_0': 1.414173587866122, 'weight_class_1': 8.627660215564749, 'weight_class_2': 6.523692733029537}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:32,213] Trial 973 finished with value: 0.9459064915296826 and parameters: {'weight_class_0': 1.4220962712916116, 'weight_class_1': 8.654087373392699, 'weight_class_2': 6.487792699948765}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:32,242] Trial 975 finished with value: 0.9498346053141266 and parameters: {'weight_class_0': 0.5949843892184934, 'weight_class_1': 8.605261008196189, 'weight_class_2': 6.192283249359334}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:32,250] Trial 976 finished with value: 0.941195382226616 and parameters: {'weight_class_0': 1.8731446097035818, 'weight_class_1': 8.569116834642914, 'weight_class_2': 6.221251197580269}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:32,262] Trial 977 finished with value: 0.9467331613324895 and parameters: {'weight_class_0': 1.2789280792831557, 'weight_class_1': 8.605298570482493, 'weight_class_2': 6.244615194759552}. Best is trial 673 with value: 0.949874946749033.

Best trial: 673. Best value: 0.949875:  99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎ | 987/1000 [00:19<00:00, 43.36it/s]

[I 2026-07-05 15:03:32,336] Trial 979 finished with value: 0.949425603148955 and parameters: {'weight_class_0': 0.6617036663743333, 'weight_class_1': 8.603004382753085, 'weight_class_2': 9.98906018272401}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:32,345] Trial 978 finished with value: 0.9497266798873666 and parameters: {'weight_class_0': 0.6370937182222245, 'weight_class_1': 8.617749228354093, 'weight_class_2': 6.2377517147305355}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:32,356] Trial 980 finished with value: 0.949743027168518 and parameters: {'weight_class_0': 0.6341762871593332, 'weight_class_1': 9.45933723949305, 'weight_class_2': 6.227736260673934}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:32,372] Trial 981 finished with value: 0.9497646765354109 and parameters: {'weight_class_0': 0.6456395881118843, 'weight_class_1': 9.427383542406025, 'weight_class_2': 6.518368122711991}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:32,386] Trial 982 finished with value: 0.9495754597286422 and parameters: {'weight_class_0': 0.6485720008415289, 'weight_class_1': 6.519023605442468, 'weight_class_2': 6.494181644037375}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:32,420] Trial 984 finished with value: 0.945138325474299 and parameters: {'weight_class_0': 0.637259745560066, 'weight_class_1': 9.346023018228236, 'weight_class_2': 2.3677970359598444}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:32,422] Trial 983 finished with value: 0.9057117805031366 and parameters: {'weight_class_0': 0.6267018398267269, 'weight_class_1': 9.50681676056427, 'weight_class_2': 0.48096059490330667}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:32,462] Trial 985 finished with value: 0.9496719042810865 and parameters: {'weight_class_0': 0.625879810794675, 'weight_class_1': 7.428918144842199, 'weight_class_2': 6.176673070666713}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:32,505] Trial 986 finished with value: 0.9494842290249438 and parameters: {'weight_class_0': 0.6767092871270771, 'weight_class_1': 6.325149097074016, 'weight_class_2': 6.168835662130065}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:32,521] Trial 987 finished with value: 0.9496593912120931 and parameters: {'weight_class_0': 0.6566398775977894, 'weight_class_1': 9.477952549111864, 'weight_class_2': 6.113685965014051}. Best is trial 673 with value: 0.949874946749033.

Best trial: 673. Best value: 0.949875: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:19<00:00, 50.06it/s]

[I 2026-07-05 15:03:32,548] Trial 989 finished with value: 0.9497128677471349 and parameters: {'weight_class_0': 0.6431022319293364, 'weight_class_1': 9.445070910992431, 'weight_class_2': 6.185250119629408}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:32,563] Trial 988 finished with value: 0.9293382772274481 and parameters: {'weight_class_0': 2.84335527090625, 'weight_class_1': 8.85418211709563, 'weight_class_2': 6.153023147096167}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:32,588] Trial 990 finished with value: 0.9494441884861572 and parameters: {'weight_class_0': 0.3971535504388346, 'weight_class_1': 8.861804956873161, 'weight_class_2': 6.169604938445288}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:32,603] Trial 991 finished with value: 0.9495032646696197 and parameters: {'weight_class_0': 0.4061202987778293, 'weight_class_1': 8.856645953624755, 'weight_class_2': 6.118057253311774}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:32,633] Trial 992 finished with value: 0.9496511287464339 and parameters: {'weight_class_0': 0.43763399630001487, 'weight_class_1': 8.856504774895592, 'weight_class_2': 6.091225592013911}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:32,652] Trial 993 finished with value: 0.9495160188608986 and parameters: {'weight_class_0': 0.4099752982511914, 'weight_class_1': 8.870097287547212, 'weight_class_2': 6.128095150825009}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:32,662] Trial 994 finished with value: 0.9494462893004211 and parameters: {'weight_class_0': 0.39612920059270246, 'weight_class_1': 8.839826591558012, 'weight_class_2': 6.140614240635114}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:32,677] Trial 995 finished with value: 0.94925963933323 and parameters: {'weight_class_0': 0.3678697625984769, 'weight_class_1': 8.888517610958619, 'weight_class_2': 6.110392823374344}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:32,695] Trial 996 finished with value: 0.9495598268145239 and parameters: {'weight_class_0': 0.41423739207942534, 'weight_class_1': 8.849561993019487, 'weight_class_2': 6.061732617060392}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:32,696] Trial 997 finished with value: 0.9488569706102111 and parameters: {'weight_class_0': 0.34368617707005905, 'weight_class_1': 8.870770541131906, 'weight_class_2': 6.908346521609559}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:32,719] Trial 998 finished with value: 0.94918060785967 and parameters: {'weight_class_0': 0.3814430527600871, 'weight_class_1': 9.187840278793917, 'weight_class_2': 6.8580715045464915}. Best is trial 673 with value: 0.949874946749033.
[I 2026-07-05 15:03:32,729] Trial 999 finished with value: 0.9495342599510668 and parameters: {'weight_class_0': 0.42887145877607435, 'weight_class_1': 8.867575302306301, 'weight_class_2': 6.817022906111108}. Best is trial 673 with value: 0.949874946749033.

Best trial score:
0.949874946749033

Best params:
{'weight_class_0': 0.5779101744296922, 'weight_class_1': 9.477512278163818, 'weight_class_2': 6.194078893277037}

In [29]:
weights = np.array([study.best_params['weight_class_0'], study.best_params['weight_class_1'], study.best_params['weight_class_2']])
weighted_probas = X_test.loc[:, cols_use].to_numpy() * weights

pred = np.argmax(weighted_probas, axis=1)

In [30]:
sub_labels = label_encoder.inverse_transform(pred)

# Submission

In [31]:
submission = pd.read_csv('../data/submission/sample_submission.csv')
submission['health_condition'] = sub_labels

submission.to_csv('../data/submission/submission_from_5.1.0_lightgbm_submission.csv', index=False)

In [32]:
submission.head()

       id health_condition
0  690088        unhealthy
1  690089        unhealthy
2  690090          at-risk
3  690091          at-risk
4  690092        unhealthy