# Imports

In [1]:
import optuna
import pickle

import numpy as np
import pandas as pd

from tqdm import tqdm

from sklearn.metrics import balanced_accuracy_score
from sklearn.model_selection import StratifiedKFold, cross_val_predict

/home/junior/Documentos/GitHub/kaggle-competition-predicting-student-health/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Utils

In [2]:
def load_pickle(file_path):
    with open(file_path, 'rb') as file:
        return pickle.load(file)

# Loading Datasets

In [4]:
X_train = pd.read_parquet('../data/processed/X_train_stacking_layer_one_model_60_trials_data_type_raw_target_encoding.parquet')
y_train = pd.read_parquet('../data/interim/y_train.parquet')

X_test = pd.read_parquet('../data/processed/X_test_stacking_layer_one_model_60_trials_data_type_raw_target_encoding.parquet')

In [5]:
X_train.head()

     lgbm_0    lgbm_1    lgbm_2     xgb_0     xgb_1     xgb_2
0  0.003278  0.000834  0.995889  0.005375  0.001396  0.993230
1  0.997061  0.000223  0.002716  0.995312  0.000386  0.004302
2  0.003584  0.000622  0.995794  0.003329  0.000530  0.996142
3  0.003934  0.003009  0.993058  0.004901  0.001941  0.993158
4  0.995190  0.000011  0.004800  0.993787  0.000018  0.006195

In [6]:
X_test.head()

     lgbm_0    lgbm_1    lgbm_2     xgb_0     xgb_1     xgb_2
0  0.012261  0.002968  0.984771  0.011874  0.003576  0.984551
1  0.405696  0.002057  0.592248  0.459639  0.002737  0.537624
2  0.999251  0.000597  0.000152  0.998100  0.001247  0.000653
3  0.981066  0.000008  0.018926  0.987928  0.000017  0.012055
4  0.012981  0.002376  0.984643  0.009526  0.002050  0.988424

# Machine Learning

In [7]:
label_encoder = load_pickle('../artifacts/label_encoder.pkl')

In [8]:
def objective(trial, X, y):

    w0 = trial.suggest_float('weight_class_0', 0.001, 10.0, log=True)
    w1 = trial.suggest_float('weight_class_1', 0.001, 10.0, log=True)
    w2 = trial.suggest_float('weight_class_2', 0.001, 10.0, log=True)
    weights = np.array([w0, w1, w2])

    proba = X.loc[:, ['xgb_0', 'xgb_1', 'xgb_2']].to_numpy()
    
    weighted_probas = proba * weights
    pred = np.argmax(weighted_probas, axis=1)
    
    score = balanced_accuracy_score(y, pred)

    return score


study = optuna.create_study(
    direction="maximize", 
    sampler=optuna.samplers.TPESampler(seed=42), 
    pruner=optuna.pruners.MedianPruner(n_warmup_steps=2)
)

study.optimize(
    lambda trial: objective(trial, X_train, y_train.health_condition), 
    n_trials=500, 
    n_jobs=-1, 
    show_progress_bar=True
)

print("\nBest trial score:")
print(study.best_trial.value)

print("\nBest params:")
print(study.best_trial.params)

[I 2026-07-13 11:29:19,474] A new study created in memory with name: no-name-de9356d6-65b2-4934-aeda-ad27eb5af3ab
Best trial: 6. Best value: 0.949769:   2%|███▎                                                                                                                                    | 12/500 [00:00<00:12, 38.28it/s]

[I 2026-07-13 11:29:19,633] Trial 4 finished with value: 0.5840954108970536 and parameters: {'weight_class_0': 9.36612653802759, 'weight_class_1': 0.0020783866337358223, 'weight_class_2': 2.066964605179856}. Best is trial 4 with value: 0.5840954108970536.
[I 2026-07-13 11:29:19,636] Trial 10 finished with value: 0.609288813387205 and parameters: {'weight_class_0': 3.334438667662059, 'weight_class_1': 0.11209246625021807, 'weight_class_2': 0.007803132439923141}. Best is trial 10 with value: 0.609288813387205.
[I 2026-07-13 11:29:19,640] Trial 5 finished with value: 0.6761491590029621 and parameters: {'weight_class_0': 0.1609400218146566, 'weight_class_1': 0.0011556652010483528, 'weight_class_2': 0.016267395904175082}. Best is trial 5 with value: 0.6761491590029621.
[I 2026-07-13 11:29:19,649] Trial 6 finished with value: 0.9497686830141454 and parameters: {'weight_class_0': 0.635411096028422, 'weight_class_1': 9.440117768949326, 'weight_class_2': 7.042410518539365}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:19,652] Trial 11 finished with value: 0.8152263971949111 and parameters: {'weight_class_0': 3.6889748774980227, 'weight_class_1': 0.5201427728228325, 'weight_class_2': 0.13698160311375765}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:19,654] Trial 3 finished with value: 0.6679197190718714 and parameters: {'weight_class_0': 0.00718941604554306, 'weight_class_1': 5.611471230390485, 'weight_class_2': 0.022550629368125148}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:19,654] Trial 0 finished with value: 0.5729343616411978 and parameters: {'weight_class_0': 2.955529544675406, 'weight_class_1': 0.0017779622303747845, 'weight_class_2': 0.0693516530636373}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:19,656] Trial 9 finished with value: 0.946445130531643 and parameters: {'weight_class_0': 0.04455777764971315, 'weight_class_1': 2.476917486855752, 'weight_class_2': 0.3785881783606753}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:19,657] Trial 8 finished with value: 0.849839336891416 and parameters: {'weight_class_0': 0.028554368022940098, 'weight_class_1': 0.009543857337215593, 'weight_class_2': 0.024207952023515285}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:19,657] Trial 7 finished with value: 0.8713209282080316 and parameters: {'weight_class_0': 0.255582503623312, 'weight_class_1': 3.6079029749852443, 'weight_class_2': 0.015105775031373081}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:19,658] Trial 2 finished with value: 0.937236765401421 and parameters: {'weight_class_0': 0.0043507334243941655, 'weight_class_1': 0.267592718844479, 'weight_class_2': 0.011771027486321804}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:19,677] Trial 1 finished with value: 0.4807748066159719 and parameters: {'weight_class_0': 0.008831722377934182, 'weight_class_1': 7.5345217608922255, 'weight_class_2': 0.0036022045100784087}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:19,792] Trial 12 finished with value: 0.9486177692016837 and parameters: {'weight_class_0': 0.281286362725664, 'weight_class_1': 9.843174299333612, 'weight_class_2': 4.8455714317982475}. Best is trial 6 with value: 0.9497686830141454.

Best trial: 6. Best value: 0.949769:   5%|██████▊                                                                                                                                 | 25/500 [00:00<00:09, 49.45it/s]

[I 2026-07-13 11:29:19,811] Trial 13 finished with value: 0.9481969073633304 and parameters: {'weight_class_0': 0.2853738559208835, 'weight_class_1': 9.455553622131278, 'weight_class_2': 6.971465635537982}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:19,818] Trial 14 finished with value: 0.9475582634871685 and parameters: {'weight_class_0': 0.24889988177815953, 'weight_class_1': 1.2025852361647902, 'weight_class_2': 2.192296987316923}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:19,824] Trial 15 finished with value: 0.9456926216110976 and parameters: {'weight_class_0': 0.24611777092063994, 'weight_class_1': 1.212906284204062, 'weight_class_2': 7.9401665505443555}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:19,859] Trial 17 finished with value: 0.9456290078091786 and parameters: {'weight_class_0': 0.2606593206207706, 'weight_class_1': 1.37883415382351, 'weight_class_2': 9.857470622569783}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:19,861] Trial 16 finished with value: 0.9439435582508499 and parameters: {'weight_class_0': 0.35688987867054456, 'weight_class_1': 1.2705036450718252, 'weight_class_2': 9.182914658244865}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:19,887] Trial 18 finished with value: 0.9453650899157204 and parameters: {'weight_class_0': 0.24418702517260732, 'weight_class_1': 0.9977962600646945, 'weight_class_2': 5.668938242202175}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:19,909] Trial 19 finished with value: 0.944267054634575 and parameters: {'weight_class_0': 0.3841223375281775, 'weight_class_1': 1.2354451564016165, 'weight_class_2': 5.36480038377896}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:19,916] Trial 20 finished with value: 0.9429077455030592 and parameters: {'weight_class_0': 0.32361914681841353, 'weight_class_1': 1.0189666489010611, 'weight_class_2': 7.407295943851135}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:19,919] Trial 21 finished with value: 0.9464548278352164 and parameters: {'weight_class_0': 0.2509596109458493, 'weight_class_1': 1.204785297004075, 'weight_class_2': 5.4168912186261}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:19,936] Trial 22 finished with value: 0.9359597714835953 and parameters: {'weight_class_0': 0.6659156222265102, 'weight_class_1': 1.3044215209625076, 'weight_class_2': 7.291301141968667}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:19,955] Trial 23 finished with value: 0.8557443832261651 and parameters: {'weight_class_0': 0.9174565593626172, 'weight_class_1': 0.06755791503642208, 'weight_class_2': 1.5381187502506888}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:19,984] Trial 24 finished with value: 0.6980469559617423 and parameters: {'weight_class_0': 0.0010472140223468569, 'weight_class_1': 0.05702398089406591, 'weight_class_2': 1.258586985138522}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,001] Trial 25 finished with value: 0.6913570158817959 and parameters: {'weight_class_0': 0.0010376375258084138, 'weight_class_1': 0.059595531869404576, 'weight_class_2': 1.4009756321010762}. Best is trial 6 with value: 0.9497686830141454.

Best trial: 6. Best value: 0.949769:   8%|██████████▎                                                                                                                             | 38/500 [00:00<00:08, 54.28it/s]

[I 2026-07-13 11:29:20,003] Trial 26 finished with value: 0.8350137231542618 and parameters: {'weight_class_0': 1.1407166178402088, 'weight_class_1': 0.05698926758708491, 'weight_class_2': 1.1438577393626739}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,029] Trial 27 finished with value: 0.8392396005633943 and parameters: {'weight_class_0': 1.1407691383620104, 'weight_class_1': 0.06908093366510976, 'weight_class_2': 1.23389972099241}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,039] Trial 28 finished with value: 0.8273003154721886 and parameters: {'weight_class_0': 1.1622791140150681, 'weight_class_1': 0.07898190067988657, 'weight_class_2': 0.7795004863192683}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,061] Trial 29 finished with value: 0.9191144353112604 and parameters: {'weight_class_0': 1.0300767898466412, 'weight_class_1': 8.21182932998234, 'weight_class_2': 1.2940217864799497}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,074] Trial 30 finished with value: 0.9267689118680514 and parameters: {'weight_class_0': 0.07357489923357034, 'weight_class_1': 9.395352437776415, 'weight_class_2': 1.1856493890576738}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,090] Trial 31 finished with value: 0.9015819088117016 and parameters: {'weight_class_0': 1.1188586059738588, 'weight_class_1': 8.920910089006831, 'weight_class_2': 0.7625846646149594}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,128] Trial 33 finished with value: 0.9349580918621797 and parameters: {'weight_class_0': 0.08728002009625087, 'weight_class_1': 8.886878982466465, 'weight_class_2': 0.6620604046313274}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,145] Trial 32 finished with value: 0.9305342518324086 and parameters: {'weight_class_0': 0.08831727856045182, 'weight_class_1': 9.714300702957766, 'weight_class_2': 0.5175007755383666}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,154] Trial 34 finished with value: 0.920747339492527 and parameters: {'weight_class_0': 0.07002375862460078, 'weight_class_1': 9.902860760937108, 'weight_class_2': 3.0450293864535483}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,164] Trial 35 finished with value: 0.9327205668212928 and parameters: {'weight_class_0': 0.09183522196225861, 'weight_class_1': 9.592075487960013, 'weight_class_2': 0.5428515904116344}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,185] Trial 36 finished with value: 0.9318727060838562 and parameters: {'weight_class_0': 0.08786764124680747, 'weight_class_1': 9.829177074837407, 'weight_class_2': 3.355354872956599}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,204] Trial 37 finished with value: 0.9464879864403669 and parameters: {'weight_class_0': 0.0776435978308541, 'weight_class_1': 3.3874831088041963, 'weight_class_2': 3.3008667225480917}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,212] Trial 38 finished with value: 0.9478137163141446 and parameters: {'weight_class_0': 0.10034464578041612, 'weight_class_1': 3.4127786306784027, 'weight_class_2': 3.0761382594911924}. Best is trial 6 with value: 0.9497686830141454.

Best trial: 6. Best value: 0.949769:  10%|█████████████▊                                                                                                                          | 51/500 [00:01<00:07, 57.80it/s]

[I 2026-07-13 11:29:20,232] Trial 40 finished with value: 0.9471010621402608 and parameters: {'weight_class_0': 0.09978330124435719, 'weight_class_1': 4.249360683911283, 'weight_class_2': 3.1253350126481725}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,233] Trial 39 finished with value: 0.9478444455052316 and parameters: {'weight_class_0': 0.10105735959081671, 'weight_class_1': 3.532872982651593, 'weight_class_2': 2.925222212142966}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,262] Trial 41 finished with value: 0.9476878990330131 and parameters: {'weight_class_0': 0.09336067626635434, 'weight_class_1': 3.4926086409412966, 'weight_class_2': 2.645116332241726}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,288] Trial 42 finished with value: 0.8820020492232498 and parameters: {'weight_class_0': 0.018137588804373703, 'weight_class_1': 3.3557975320020774, 'weight_class_2': 3.1912363393926624}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,308] Trial 44 finished with value: 0.9480833242488265 and parameters: {'weight_class_0': 0.5480994232114721, 'weight_class_1': 3.7231366241595865, 'weight_class_2': 3.1778007474471606}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,314] Trial 43 finished with value: 0.9031734613352658 and parameters: {'weight_class_0': 0.024862173562933233, 'weight_class_1': 4.051539470229847, 'weight_class_2': 3.149499306916214}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,352] Trial 45 finished with value: 0.9473947998614456 and parameters: {'weight_class_0': 0.5560580574550217, 'weight_class_1': 4.426905573159157, 'weight_class_2': 2.5799753804189653}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,359] Trial 46 finished with value: 0.8723690467575294 and parameters: {'weight_class_0': 0.01842995462124564, 'weight_class_1': 4.661895478537678, 'weight_class_2': 0.27613803676184456}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,371] Trial 47 finished with value: 0.9154674609090109 and parameters: {'weight_class_0': 0.030206109707650176, 'weight_class_1': 4.489220741035553, 'weight_class_2': 0.21641923884693115}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,378] Trial 48 finished with value: 0.693168522029976 and parameters: {'weight_class_0': 0.021533486663490208, 'weight_class_1': 2.8090079405459716, 'weight_class_2': 0.0018625679044198284}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,394] Trial 49 finished with value: 0.9323435957961584 and parameters: {'weight_class_0': 0.03355451438806938, 'weight_class_1': 2.3565759407805458, 'weight_class_2': 4.315504923808703}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,409] Trial 50 finished with value: 0.9304555807559313 and parameters: {'weight_class_0': 0.033585970864223935, 'weight_class_1': 2.214403336948553, 'weight_class_2': 4.6714481849884795}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,436] Trial 51 finished with value: 0.8957560000575375 and parameters: {'weight_class_0': 0.556647919639339, 'weight_class_1': 2.2272098810179872, 'weight_class_2': 0.3079055002443574}. Best is trial 6 with value: 0.9497686830141454.

[I 2026-07-13 11:29:20,452] Trial 53 finished with value: 0.6150472537214765 and parameters: {'weight_class_0': 2.2263555655395644, 'weight_class_1': 2.184953650417864, 'weight_class_2': 0.0018865217998727023}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,467] Trial 52 finished with value: 0.8902344013097351 and parameters: {'weight_class_0': 0.6408160111256921, 'weight_class_1': 2.1336615051251, 'weight_class_2': 0.2181956572677245}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,490] Trial 54 finished with value: 0.8549936598920879 and parameters: {'weight_class_0': 5.624878141670178, 'weight_class_1': 2.4436153131655693, 'weight_class_2': 4.795491528085415}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,515] Trial 55 finished with value: 0.893756469849159 and parameters: {'weight_class_0': 2.448360911096114, 'weight_class_1': 1.9668376018828246, 'weight_class_2': 4.498228165517642}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,530] Trial 56 finished with value: 0.9478130134149859 and parameters: {'weight_class_0': 0.140229864223296, 'weight_class_1': 1.9266159049315958, 'weight_class_2': 4.592337844652872}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,532] Trial 57 finished with value: 0.7656452447381432 and parameters: {'weight_class_0': 5.494631890563757, 'weight_class_1': 0.47902339254617565, 'weight_class_2': 0.04683018428428645}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,552] Trial 58 finished with value: 0.8529582276456277 and parameters: {'weight_class_0': 2.1540157056984697, 'weight_class_1': 0.6730812707394866, 'weight_class_2': 2.123436967741057}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,564] Trial 59 finished with value: 0.9485524049930865 and parameters: {'weight_class_0': 0.15383621049833207, 'weight_class_1': 5.991858539190469, 'weight_class_2': 1.9584792385138217}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,584] Trial 60 finished with value: 0.9487540111195484 and parameters: {'weight_class_0': 0.15593935953554086, 'weight_class_1': 5.72206020474148, 'weight_class_2': 2.019326709837656}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,604] Trial 61 finished with value: 0.9483476212061195 and parameters: {'weight_class_0': 0.15073874644083007, 'weight_class_1': 6.202703873917248, 'weight_class_2': 2.0643712293531067}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,626] Trial 62 finished with value: 0.948275487534762 and parameters: {'weight_class_0': 0.14446169470024567, 'weight_class_1': 6.087365177126561, 'weight_class_2': 1.833685937569312}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,634] Trial 63 finished with value: 0.9460853802410941 and parameters: {'weight_class_0': 0.17202187520202095, 'weight_class_1': 6.51323251081241, 'weight_class_2': 9.602213797892308}. Best is trial 6 with value: 0.9497686830141454.

[I 2026-07-13 11:29:20,653] Trial 64 finished with value: 0.9421447748343922 and parameters: {'weight_class_0': 0.15845081161697344, 'weight_class_1': 0.6350928391944153, 'weight_class_2': 9.998662669902254}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,672] Trial 65 finished with value: 0.9488890785996192 and parameters: {'weight_class_0': 0.16273318118556673, 'weight_class_1': 5.708903795653758, 'weight_class_2': 1.9595941307242342}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,697] Trial 66 finished with value: 0.9467578104814515 and parameters: {'weight_class_0': 0.16154616767424806, 'weight_class_1': 6.135039713979106, 'weight_class_2': 7.4159590166534795}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,711] Trial 67 finished with value: 0.9461235445115156 and parameters: {'weight_class_0': 0.16874081738764882, 'weight_class_1': 5.612619197121787, 'weight_class_2': 9.8090411618436}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,724] Trial 68 finished with value: 0.9489118707389598 and parameters: {'weight_class_0': 0.1814392552865645, 'weight_class_1': 6.1353234396874265, 'weight_class_2': 1.863428097637843}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,748] Trial 69 finished with value: 0.9469769437934309 and parameters: {'weight_class_0': 0.16733286306655099, 'weight_class_1': 6.159788167593288, 'weight_class_2': 7.179871280757248}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,766] Trial 70 finished with value: 0.946643572686441 and parameters: {'weight_class_0': 0.15700771690144646, 'weight_class_1': 6.3367271486095795, 'weight_class_2': 7.095903300043072}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,782] Trial 72 finished with value: 0.9487800138516113 and parameters: {'weight_class_0': 0.17998303841902039, 'weight_class_1': 6.058559574055041, 'weight_class_2': 1.6533404585835685}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,790] Trial 71 finished with value: 0.9469004050220148 and parameters: {'weight_class_0': 0.14949628733152864, 'weight_class_1': 5.577286835674416, 'weight_class_2': 6.417106489343384}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,810] Trial 73 finished with value: 0.9492509603638931 and parameters: {'weight_class_0': 0.34183321664517846, 'weight_class_1': 5.689596322548364, 'weight_class_2': 6.390443171319976}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,821] Trial 74 finished with value: 0.9472511129228943 and parameters: {'weight_class_0': 0.4000181407007568, 'weight_class_1': 5.8388361182220585, 'weight_class_2': 1.7076705977065938}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,839] Trial 75 finished with value: 0.9482415877448188 and parameters: {'weight_class_0': 0.3554142533596985, 'weight_class_1': 6.123570045058544, 'weight_class_2': 1.8078879241215682}. Best is trial 6 with value: 0.9497686830141454.

Best trial: 6. Best value: 0.949769:  17%|███████████████████████▋                                                                                                                | 87/500 [00:01<00:07, 57.38it/s]

[I 2026-07-13 11:29:20,855] Trial 76 finished with value: 0.9301511251017872 and parameters: {'weight_class_0': 0.05605729708612624, 'weight_class_1': 6.582686958786299, 'weight_class_2': 1.702675046704413}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,876] Trial 77 finished with value: 0.8461332970124064 and parameters: {'weight_class_0': 0.04573863162699834, 'weight_class_1': 0.005217169070484073, 'weight_class_2': 1.8396392496529996}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,898] Trial 79 finished with value: 0.9479998897997554 and parameters: {'weight_class_0': 0.40378176504629415, 'weight_class_1': 6.7919430590818015, 'weight_class_2': 1.9364066171876917}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,899] Trial 78 finished with value: 0.9381688809044254 and parameters: {'weight_class_0': 0.3848773924981008, 'weight_class_1': 7.172581387283559, 'weight_class_2': 0.8775000870726879}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,921] Trial 80 finished with value: 0.9401048982952712 and parameters: {'weight_class_0': 0.36685593965834346, 'weight_class_1': 7.299850077953095, 'weight_class_2': 0.9052066293795932}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,941] Trial 81 finished with value: 0.9204293129115376 and parameters: {'weight_class_0': 0.05055305427203094, 'weight_class_1': 7.26287506130592, 'weight_class_2': 0.9733050963493611}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,955] Trial 82 finished with value: 0.8779489277486313 and parameters: {'weight_class_0': 0.04729461819818176, 'weight_class_1': 0.006487083739890049, 'weight_class_2': 0.8090214994714063}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,973] Trial 83 finished with value: 0.8684343472083745 and parameters: {'weight_class_0': 0.053724860696615646, 'weight_class_1': 0.004550928627843237, 'weight_class_2': 0.8672533771422085}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:20,997] Trial 85 finished with value: 0.9473943763463839 and parameters: {'weight_class_0': 0.22229006463469128, 'weight_class_1': 2.8765230010476524, 'weight_class_2': 0.959134212414576}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:21,014] Trial 84 finished with value: 0.8746741986412531 and parameters: {'weight_class_0': 0.23706160311900268, 'weight_class_1': 0.021715540141261088, 'weight_class_2': 0.9575466096674738}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:21,027] Trial 86 finished with value: 0.9465735116808928 and parameters: {'weight_class_0': 0.21080351317787635, 'weight_class_1': 7.647281087896144, 'weight_class_2': 0.9568764277694692}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:21,042] Trial 87 finished with value: 0.8727435145819715 and parameters: {'weight_class_0': 0.22052570571659913, 'weight_class_1': 1.7285956692682507, 'weight_class_2': 0.008007263548289529}. Best is trial 6 with value: 0.9497686830141454.

[I 2026-07-13 11:29:21,056] Trial 88 finished with value: 0.9482567467665545 and parameters: {'weight_class_0': 0.21128249371889424, 'weight_class_1': 2.942197196773008, 'weight_class_2': 1.0424657595799924}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:21,096] Trial 89 finished with value: 0.9490379892819245 and parameters: {'weight_class_0': 0.21239470983305508, 'weight_class_1': 1.5562640559818266, 'weight_class_2': 2.2968705388535104}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:21,119] Trial 91 finished with value: 0.9497324015167986 and parameters: {'weight_class_0': 0.23663103528839022, 'weight_class_1': 4.798504803111111, 'weight_class_2': 2.332649285740219}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:21,121] Trial 90 finished with value: 0.9491968153493979 and parameters: {'weight_class_0': 0.22367216309876756, 'weight_class_1': 4.965332994412267, 'weight_class_2': 4.060991548209984}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:21,139] Trial 92 finished with value: 0.9490707877864971 and parameters: {'weight_class_0': 0.21502836842043382, 'weight_class_1': 1.5974351395775608, 'weight_class_2': 2.3714324134026525}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:21,149] Trial 93 finished with value: 0.94312744487228 and parameters: {'weight_class_0': 0.8171548360457261, 'weight_class_1': 4.941131935007656, 'weight_class_2': 2.5152031586260417}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:21,177] Trial 94 finished with value: 0.9479152261909868 and parameters: {'weight_class_0': 0.11833331302208996, 'weight_class_1': 4.847331819027414, 'weight_class_2': 2.4110784538056906}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:21,185] Trial 95 finished with value: 0.9477836966557257 and parameters: {'weight_class_0': 0.11890594936406022, 'weight_class_1': 5.055845227008435, 'weight_class_2': 2.3754628228912793}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:21,213] Trial 96 finished with value: 0.9478324527663569 and parameters: {'weight_class_0': 0.11846242326953722, 'weight_class_1': 4.997650265205251, 'weight_class_2': 2.3333736791408315}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:21,234] Trial 97 finished with value: 0.9481219021580559 and parameters: {'weight_class_0': 0.29127660480224726, 'weight_class_1': 1.5420504761800824, 'weight_class_2': 2.5241714371114625}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:21,245] Trial 98 finished with value: 0.9470788194211508 and parameters: {'weight_class_0': 0.11408216342093698, 'weight_class_1': 4.593457802781771, 'weight_class_2': 4.027643312586602}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:21,277] Trial 99 finished with value: 0.9467072576026728 and parameters: {'weight_class_0': 0.8347837609901805, 'weight_class_1': 5.04828001855672, 'weight_class_2': 3.715037625048539}. Best is trial 6 with value: 0.9497686830141454.

[I 2026-07-13 11:29:21,290] Trial 100 finished with value: 0.9478625264858236 and parameters: {'weight_class_0': 0.11849500221377197, 'weight_class_1': 1.6413627958442298, 'weight_class_2': 3.817776361352196}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:21,304] Trial 101 finished with value: 0.9475858884810201 and parameters: {'weight_class_0': 0.2624395555574193, 'weight_class_1': 1.542546841794816, 'weight_class_2': 1.4503831549714374}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:21,339] Trial 102 finished with value: 0.94335113800234 and parameters: {'weight_class_0': 0.27402077500411554, 'weight_class_1': 0.9181585832372461, 'weight_class_2': 1.3498378149832595}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:21,345] Trial 103 finished with value: 0.8950250877221645 and parameters: {'weight_class_0': 0.4946073130463337, 'weight_class_1': 0.27913958725042165, 'weight_class_2': 1.3117412208056909}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:21,358] Trial 104 finished with value: 0.9470302189225187 and parameters: {'weight_class_0': 0.2789880321740374, 'weight_class_1': 1.6194741279213634, 'weight_class_2': 1.3448116327119395}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:21,391] Trial 105 finished with value: 0.9332819062735868 and parameters: {'weight_class_0': 0.4982637918811033, 'weight_class_1': 0.8689293719849066, 'weight_class_2': 5.705618305656131}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:21,401] Trial 106 finished with value: 0.9249514178162697 and parameters: {'weight_class_0': 0.5014348492732151, 'weight_class_1': 0.8416725289152097, 'weight_class_2': 1.3797641955118647}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:21,418] Trial 107 finished with value: 0.9402252308424316 and parameters: {'weight_class_0': 0.49002940475071394, 'weight_class_1': 2.8197621292144213, 'weight_class_2': 1.2754667364151022}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:21,451] Trial 108 finished with value: 0.9497321315717661 and parameters: {'weight_class_0': 0.46345934554077406, 'weight_class_1': 8.326889874664836, 'weight_class_2': 6.007374428230924}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:21,479] Trial 110 finished with value: 0.8966660496701332 and parameters: {'weight_class_0': 0.46376094044510013, 'weight_class_1': 0.18889439732354008, 'weight_class_2': 5.705237398900297}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:21,484] Trial 109 finished with value: 0.9014094637022199 and parameters: {'weight_class_0': 0.46421235790842147, 'weight_class_1': 0.24087982605538305, 'weight_class_2': 5.136024522046032}. Best is trial 6 with value: 0.9497686830141454.

Best trial: 124. Best value: 0.949825:  24%|████████████████████████████████▍                                                                                                    | 122/500 [00:02<00:06, 54.24it/s]

[I 2026-07-13 11:29:21,499] Trial 111 finished with value: 0.9482409531347252 and parameters: {'weight_class_0': 0.19253228790995847, 'weight_class_1': 3.9290275582526766, 'weight_class_2': 5.937630516437471}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:21,526] Trial 112 finished with value: 0.9451545962594162 and parameters: {'weight_class_0': 1.4335711123191388, 'weight_class_1': 8.443451701956647, 'weight_class_2': 5.444872488818632}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:21,546] Trial 114 finished with value: 0.948465206471667 and parameters: {'weight_class_0': 0.19359651073575657, 'weight_class_1': 3.770714292623882, 'weight_class_2': 5.525935998296124}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:21,547] Trial 113 finished with value: 0.9369653170127844 and parameters: {'weight_class_0': 1.5346431520481452, 'weight_class_1': 3.8975193232080088, 'weight_class_2': 5.601659568957774}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:21,581] Trial 115 finished with value: 0.9484729612647546 and parameters: {'weight_class_0': 0.1958187688887577, 'weight_class_1': 3.7739412229968945, 'weight_class_2': 5.498597957647609}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:21,592] Trial 116 finished with value: 0.9471405653044366 and parameters: {'weight_class_0': 0.19063322879397954, 'weight_class_1': 8.539235016793533, 'weight_class_2': 5.314794867052349}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:21,614] Trial 117 finished with value: 0.9355453101112419 and parameters: {'weight_class_0': 1.7029498305065058, 'weight_class_1': 3.9859881234271, 'weight_class_2': 6.167000950872156}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:21,648] Trial 118 finished with value: 0.9473353237593981 and parameters: {'weight_class_0': 0.18673245978279812, 'weight_class_1': 8.688854549402452, 'weight_class_2': 3.848291709729768}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:21,650] Trial 119 finished with value: 0.9484854489250959 and parameters: {'weight_class_0': 0.6844486621517446, 'weight_class_1': 8.23954811760215, 'weight_class_2': 3.7149936133090997}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:21,667] Trial 120 finished with value: 0.9497118280945838 and parameters: {'weight_class_0': 0.627743136332614, 'weight_class_1': 8.467991999995203, 'weight_class_2': 8.41395417636134}. Best is trial 6 with value: 0.9497686830141454.
[I 2026-07-13 11:29:21,696] Trial 121 finished with value: 0.9491556443815377 and parameters: {'weight_class_0': 0.3141155318072868, 'weight_class_1': 9.835541126111087, 'weight_class_2': 4.1347171788656}. Best is trial 6 with value: 0.9497686830141454.

Best trial: 124. Best value: 0.949825:  26%|███████████████████████████████████                                                                                                  | 132/500 [00:02<00:06, 52.80it/s]

[I 2026-07-13 11:29:21,720] Trial 122 finished with value: 0.9498232641158716 and parameters: {'weight_class_0': 0.6849369453954879, 'weight_class_1': 9.866148285307043, 'weight_class_2': 8.513499341488824}. Best is trial 122 with value: 0.9498232641158716.
[I 2026-07-13 11:29:21,729] Trial 123 finished with value: 0.9494526364691134 and parameters: {'weight_class_0': 0.3179620093474701, 'weight_class_1': 8.383495340414846, 'weight_class_2': 3.7409041341061}. Best is trial 122 with value: 0.9498232641158716.
[I 2026-07-13 11:29:21,752] Trial 124 finished with value: 0.9498254611930451 and parameters: {'weight_class_0': 0.6569235682453494, 'weight_class_1': 9.866803621795825, 'weight_class_2': 8.348334381411135}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:21,764] Trial 125 finished with value: 0.9480902051228316 and parameters: {'weight_class_0': 0.3016534776676753, 'weight_class_1': 9.674140524870552, 'weight_class_2': 8.435131337689178}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:21,792] Trial 126 finished with value: 0.9481607594330935 and parameters: {'weight_class_0': 0.30378469498740923, 'weight_class_1': 9.775373754701793, 'weight_class_2': 7.905893104974419}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:21,830] Trial 127 finished with value: 0.9491200251234374 and parameters: {'weight_class_0': 0.3254792514532075, 'weight_class_1': 9.39201311054455, 'weight_class_2': 2.930552924508414}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:21,831] Trial 128 finished with value: 0.9478259673051745 and parameters: {'weight_class_0': 0.2949882678668321, 'weight_class_1': 3.0922859861049155, 'weight_class_2': 8.384476532978523}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:21,838] Trial 129 finished with value: 0.9485524645101316 and parameters: {'weight_class_0': 0.3318074288777857, 'weight_class_1': 9.539441108904104, 'weight_class_2': 7.792825035168058}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:21,861] Trial 130 finished with value: 0.9485990594906873 and parameters: {'weight_class_0': 0.3155842180897258, 'weight_class_1': 7.329657402068083, 'weight_class_2': 8.229220350382327}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:21,878] Trial 131 finished with value: 0.9496799446993482 and parameters: {'weight_class_0': 0.7417536939801177, 'weight_class_1': 7.552838869195559, 'weight_class_2': 7.9994094240585385}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:21,902] Trial 132 finished with value: 0.9484343816315889 and parameters: {'weight_class_0': 0.3328341497859704, 'weight_class_1': 9.686939735911574, 'weight_class_2': 8.369164073526639}. Best is trial 124 with value: 0.9498254611930451.

Best trial: 124. Best value: 0.949825:  29%|██████████████████████████████████████▎                                                                                              | 144/500 [00:02<00:06, 54.25it/s]

[I 2026-07-13 11:29:21,937] Trial 133 finished with value: 0.9497836772020456 and parameters: {'weight_class_0': 0.7142969653954105, 'weight_class_1': 9.693222655607382, 'weight_class_2': 7.435000671350248}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:21,938] Trial 134 finished with value: 0.9496994656550762 and parameters: {'weight_class_0': 0.6864917185349121, 'weight_class_1': 7.836793688940074, 'weight_class_2': 8.639823020547281}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:21,952] Trial 135 finished with value: 0.9496915987007779 and parameters: {'weight_class_0': 0.6469254298826947, 'weight_class_1': 7.716463592137564, 'weight_class_2': 7.3711967108013425}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:21,964] Trial 136 finished with value: 0.9488836502868218 and parameters: {'weight_class_0': 0.7308173865835698, 'weight_class_1': 7.485642348655807, 'weight_class_2': 4.482702469285567}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:21,986] Trial 137 finished with value: 0.9489830336853555 and parameters: {'weight_class_0': 0.6779475217741533, 'weight_class_1': 7.698214011816632, 'weight_class_2': 4.340443189600315}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,004] Trial 138 finished with value: 0.9476356949452862 and parameters: {'weight_class_0': 0.6554426097320941, 'weight_class_1': 7.748758001588029, 'weight_class_2': 2.967281458921598}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,044] Trial 139 finished with value: 0.9485647047621031 and parameters: {'weight_class_0': 0.8180352807122433, 'weight_class_1': 8.014405279326345, 'weight_class_2': 4.4644785184260645}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,051] Trial 140 finished with value: 0.9470371598469008 and parameters: {'weight_class_0': 0.9663797953409007, 'weight_class_1': 7.099738496528433, 'weight_class_2': 4.277207826079391}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,063] Trial 141 finished with value: 0.946975126472208 and parameters: {'weight_class_0': 0.7386597325170636, 'weight_class_1': 8.028248538156419, 'weight_class_2': 3.064189441738426}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,079] Trial 142 finished with value: 0.9488279956336657 and parameters: {'weight_class_0': 0.6951439844789671, 'weight_class_1': 7.656890890510328, 'weight_class_2': 4.170291472703806}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,108] Trial 143 finished with value: 0.9488455511105287 and parameters: {'weight_class_0': 0.9582502969143775, 'weight_class_1': 7.744491604953787, 'weight_class_2': 6.857272641757777}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,120] Trial 144 finished with value: 0.9497554855987184 and parameters: {'weight_class_0': 0.6547217495902968, 'weight_class_1': 7.491473628768305, 'weight_class_2': 6.650774083338722}. Best is trial 124 with value: 0.9498254611930451.

[I 2026-07-13 11:29:22,155] Trial 145 finished with value: 0.9482437309499899 and parameters: {'weight_class_0': 1.0484558945809463, 'weight_class_1': 6.779982042640927, 'weight_class_2': 6.7881360583272405}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,157] Trial 146 finished with value: 0.9492656315586566 and parameters: {'weight_class_0': 0.8876889675066083, 'weight_class_1': 7.118729146488951, 'weight_class_2': 9.776825386324122}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,180] Trial 147 finished with value: 0.9482679036356604 and parameters: {'weight_class_0': 1.0764932580089694, 'weight_class_1': 7.38981754591694, 'weight_class_2': 6.726882020075304}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,190] Trial 148 finished with value: 0.948425387018874 and parameters: {'weight_class_0': 1.07884453510471, 'weight_class_1': 7.171093353137734, 'weight_class_2': 7.181712968955965}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,223] Trial 149 finished with value: 0.9498123472647563 and parameters: {'weight_class_0': 0.596647818934707, 'weight_class_1': 9.83970705034772, 'weight_class_2': 7.052961578157108}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,235] Trial 150 finished with value: 0.9468393625324006 and parameters: {'weight_class_0': 1.16731404838212, 'weight_class_1': 5.073061871655048, 'weight_class_2': 9.994998171859711}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,262] Trial 151 finished with value: 0.9473148428148445 and parameters: {'weight_class_0': 1.1394664954620182, 'weight_class_1': 5.319936991041301, 'weight_class_2': 9.67248901860258}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,268] Trial 152 finished with value: 0.9463018906224571 and parameters: {'weight_class_0': 1.171949898539922, 'weight_class_1': 5.272224040441282, 'weight_class_2': 6.83464346574171}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,286] Trial 153 finished with value: 0.946323165652697 and parameters: {'weight_class_0': 1.2635130859476662, 'weight_class_1': 5.124240916366608, 'weight_class_2': 9.844527717840803}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,288] Trial 154 finished with value: 0.9464431871279282 and parameters: {'weight_class_0': 1.2495024272301667, 'weight_class_1': 5.186293975389499, 'weight_class_2': 9.398020953408784}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,320] Trial 155 finished with value: 0.949027110027972 and parameters: {'weight_class_0': 0.5755006081684394, 'weight_class_1': 5.3041426580738795, 'weight_class_2': 9.21681987368699}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,327] Trial 156 finished with value: 0.9488636785008633 and parameters: {'weight_class_0': 0.5803151828010094, 'weight_class_1': 5.1064153194131725, 'weight_class_2': 9.469871215063455}. Best is trial 124 with value: 0.9498254611930451.

[I 2026-07-13 11:29:22,367] Trial 157 finished with value: 0.945392089367855 and parameters: {'weight_class_0': 1.404260602176786, 'weight_class_1': 5.285514968796818, 'weight_class_2': 9.813904042290876}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,375] Trial 158 finished with value: 0.9488995804513083 and parameters: {'weight_class_0': 0.562494299453457, 'weight_class_1': 5.175211929417178, 'weight_class_2': 9.552775782573404}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,394] Trial 159 finished with value: 0.9487746589710389 and parameters: {'weight_class_0': 0.5968620553520968, 'weight_class_1': 5.113780265957612, 'weight_class_2': 9.763194703401586}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,404] Trial 160 finished with value: 0.9485333169208792 and parameters: {'weight_class_0': 0.5850655085285285, 'weight_class_1': 4.572608336437741, 'weight_class_2': 9.91424676074509}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,431] Trial 161 finished with value: 0.9488886675812688 and parameters: {'weight_class_0': 0.578516382471996, 'weight_class_1': 4.413827044625797, 'weight_class_2': 7.805929584873227}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,459] Trial 162 finished with value: 0.9491284323803235 and parameters: {'weight_class_0': 0.5774836377555014, 'weight_class_1': 4.406055935660718, 'weight_class_2': 6.3652135778830745}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,469] Trial 163 finished with value: 0.6521983332490128 and parameters: {'weight_class_0': 0.4197928952374902, 'weight_class_1': 0.00113499439383149, 'weight_class_2': 6.305631291554458}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,476] Trial 164 finished with value: 0.9493438219213438 and parameters: {'weight_class_0': 0.41898309741069634, 'weight_class_1': 9.938465951940854, 'weight_class_2': 6.680976332608927}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,505] Trial 165 finished with value: 0.9494918682978426 and parameters: {'weight_class_0': 0.4292568491309672, 'weight_class_1': 9.902527081111039, 'weight_class_2': 6.297099864459504}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,516] Trial 166 finished with value: 0.9492063315359012 and parameters: {'weight_class_0': 0.44211177542133745, 'weight_class_1': 9.949549913630626, 'weight_class_2': 7.900801339278947}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,536] Trial 167 finished with value: 0.9490445217159768 and parameters: {'weight_class_0': 0.8430127445331637, 'weight_class_1': 6.444820632226602, 'weight_class_2': 6.591185520705461}. Best is trial 124 with value: 0.9498254611930451.

Best trial: 124. Best value: 0.949825:  36%|███████████████████████████████████████████████▉                                                                                     | 180/500 [00:03<00:05, 56.74it/s]

[I 2026-07-13 11:29:22,548] Trial 168 finished with value: 0.9492687630560989 and parameters: {'weight_class_0': 0.4145617507962086, 'weight_class_1': 9.461706567981226, 'weight_class_2': 6.939947328956224}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,579] Trial 169 finished with value: 0.9494728133625759 and parameters: {'weight_class_0': 0.4153186745027573, 'weight_class_1': 9.378943557170498, 'weight_class_2': 6.220610318477009}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,591] Trial 170 finished with value: 0.9494947591690983 and parameters: {'weight_class_0': 0.41933105560117323, 'weight_class_1': 9.899812434540026, 'weight_class_2': 6.050281961683942}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,612] Trial 171 finished with value: 0.9493990854395084 and parameters: {'weight_class_0': 0.41824899254486486, 'weight_class_1': 9.977074200432702, 'weight_class_2': 6.396471099293605}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,636] Trial 172 finished with value: 0.9496072602144849 and parameters: {'weight_class_0': 0.4213144899730598, 'weight_class_1': 9.803722277048301, 'weight_class_2': 4.892579790887695}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,639] Trial 173 finished with value: 0.948234788141244 and parameters: {'weight_class_0': 0.8444185282523898, 'weight_class_1': 6.464895798228458, 'weight_class_2': 4.868639613540117}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,650] Trial 174 finished with value: 0.9496639114853817 and parameters: {'weight_class_0': 0.4199028562397864, 'weight_class_1': 9.593944198077443, 'weight_class_2': 5.003607870617274}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,680] Trial 175 finished with value: 0.9496387060292791 and parameters: {'weight_class_0': 0.41740346172143267, 'weight_class_1': 9.917336475366158, 'weight_class_2': 5.100270833778951}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,692] Trial 176 finished with value: 0.9486608666014571 and parameters: {'weight_class_0': 0.8671455375234354, 'weight_class_1': 9.95405220660669, 'weight_class_2': 4.94412283624887}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,712] Trial 177 finished with value: 0.6585417522327098 and parameters: {'weight_class_0': 0.003428728694587196, 'weight_class_1': 8.811583005946185, 'weight_class_2': 4.86121650532027}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,725] Trial 178 finished with value: 0.6578605408823465 and parameters: {'weight_class_0': 0.00222654039922774, 'weight_class_1': 8.728346817167457, 'weight_class_2': 5.580324522261949}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,738] Trial 179 finished with value: 0.9495899710904944 and parameters: {'weight_class_0': 0.4171719546986439, 'weight_class_1': 9.786344086181707, 'weight_class_2': 4.858679232061078}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,762] Trial 180 finished with value: 0.949674555923879 and parameters: {'weight_class_0': 0.4023980554979502, 'weight_class_1': 9.171991549549036, 'weight_class_2': 4.968526532267672}. Best is trial 124 with value: 0.9498254611930451.

Best trial: 124. Best value: 0.949825:  38%|███████████████████████████████████████████████████                                                                                  | 192/500 [00:03<00:05, 55.01it/s]

[I 2026-07-13 11:29:22,806] Trial 182 finished with value: 0.6549930248981207 and parameters: {'weight_class_0': 0.7444193489731104, 'weight_class_1': 8.338081225238705, 'weight_class_2': 0.0010007109047286246}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,810] Trial 181 finished with value: 0.6578835786520633 and parameters: {'weight_class_0': 0.002125303357401696, 'weight_class_1': 8.354472659767756, 'weight_class_2': 5.217574912625606}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,833] Trial 183 finished with value: 0.9492664209955416 and parameters: {'weight_class_0': 0.7250736249791788, 'weight_class_1': 8.2889007054718, 'weight_class_2': 5.1141163938663565}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,839] Trial 184 finished with value: 0.9493289916570714 and parameters: {'weight_class_0': 0.7132845025730415, 'weight_class_1': 8.186744984385873, 'weight_class_2': 5.255938982081861}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,858] Trial 185 finished with value: 0.9495011353072211 and parameters: {'weight_class_0': 0.7074222078072077, 'weight_class_1': 8.14925596642686, 'weight_class_2': 5.764578850049718}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,875] Trial 186 finished with value: 0.9493730803117405 and parameters: {'weight_class_0': 0.7195001658943336, 'weight_class_1': 6.638265681502763, 'weight_class_2': 5.497577385529053}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,895] Trial 187 finished with value: 0.9491904610636027 and parameters: {'weight_class_0': 0.6961506243825512, 'weight_class_1': 6.685074763063605, 'weight_class_2': 4.9816870524216466}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,918] Trial 189 finished with value: 0.9496626636992159 and parameters: {'weight_class_0': 0.7338355316559199, 'weight_class_1': 6.820686543657959, 'weight_class_2': 7.447345632375401}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,936] Trial 190 finished with value: 0.9498076776780583 and parameters: {'weight_class_0': 0.4970535700486217, 'weight_class_1': 6.501383952155331, 'weight_class_2': 5.077751207738352}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,938] Trial 188 finished with value: 0.9495622621539654 and parameters: {'weight_class_0': 0.49348219472551685, 'weight_class_1': 6.538779310669922, 'weight_class_2': 7.5689737996021815}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,970] Trial 191 finished with value: 0.9494622705869374 and parameters: {'weight_class_0': 0.4898745267777188, 'weight_class_1': 6.631550002138449, 'weight_class_2': 7.869487602998475}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:22,983] Trial 192 finished with value: 0.9496164041125544 and parameters: {'weight_class_0': 0.5033828892273466, 'weight_class_1': 6.318684018814483, 'weight_class_2': 7.302108857205407}. Best is trial 124 with value: 0.9498254611930451.

Best trial: 124. Best value: 0.949825:  41%|█████████████████████████████████████████████████████▉                                                                               | 203/500 [00:03<00:05, 54.42it/s]

[I 2026-07-13 11:29:22,997] Trial 193 finished with value: 0.9494840435052511 and parameters: {'weight_class_0': 0.4922135456225251, 'weight_class_1': 6.466694813131323, 'weight_class_2': 7.748107027179852}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:23,024] Trial 195 finished with value: 0.9494706529805365 and parameters: {'weight_class_0': 0.49768262880738817, 'weight_class_1': 6.491729651833262, 'weight_class_2': 7.922759836689054}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:23,039] Trial 196 finished with value: 0.9495302812622604 and parameters: {'weight_class_0': 0.5064132610376895, 'weight_class_1': 6.42552589702061, 'weight_class_2': 7.7702727735835415}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:23,041] Trial 194 finished with value: 0.9495816105709 and parameters: {'weight_class_0': 0.5420882170735957, 'weight_class_1': 6.4964322446479565, 'weight_class_2': 7.861053957217176}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:23,061] Trial 197 finished with value: 0.9494599259028721 and parameters: {'weight_class_0': 0.49695357866295137, 'weight_class_1': 6.335214725586779, 'weight_class_2': 7.768705989384364}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:23,079] Trial 198 finished with value: 0.9495440459006161 and parameters: {'weight_class_0': 0.5080380636050565, 'weight_class_1': 6.423009473364875, 'weight_class_2': 7.76125690711543}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:23,105] Trial 199 finished with value: 0.9494610466477881 and parameters: {'weight_class_0': 0.5207213797497839, 'weight_class_1': 6.470956341017233, 'weight_class_2': 8.051003573187907}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:23,125] Trial 200 finished with value: 0.9495444959276935 and parameters: {'weight_class_0': 0.5615160135549975, 'weight_class_1': 6.407884432759561, 'weight_class_2': 7.871038615945244}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:23,162] Trial 202 finished with value: 0.9488063653286289 and parameters: {'weight_class_0': 0.5903611750696203, 'weight_class_1': 7.365121850817536, 'weight_class_2': 3.489177056677738}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:23,177] Trial 201 finished with value: 0.9496437035877058 and parameters: {'weight_class_0': 0.564107410526977, 'weight_class_1': 7.413100655978845, 'weight_class_2': 7.864844639906742}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:23,181] Trial 203 finished with value: 0.9497701884356867 and parameters: {'weight_class_0': 0.6155482171689279, 'weight_class_1': 7.540393358632337, 'weight_class_2': 7.453023030074652}. Best is trial 124 with value: 0.9498254611930451.

[I 2026-07-13 11:29:23,208] Trial 204 finished with value: 0.9495604570848869 and parameters: {'weight_class_0': 0.36983349173387914, 'weight_class_1': 7.87596889092977, 'weight_class_2': 3.4456215102517356}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:23,238] Trial 206 finished with value: 0.9485131588026879 and parameters: {'weight_class_0': 0.6228903807021905, 'weight_class_1': 7.829758660967862, 'weight_class_2': 3.3589392680393217}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:23,244] Trial 205 finished with value: 0.9485734265070654 and parameters: {'weight_class_0': 0.6243169711111598, 'weight_class_1': 7.8557926542522845, 'weight_class_2': 3.4617239343334836}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:23,263] Trial 208 finished with value: 0.9496281175992433 and parameters: {'weight_class_0': 0.36771329848455436, 'weight_class_1': 7.852875563641046, 'weight_class_2': 3.4899242955420426}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:23,283] Trial 207 finished with value: 0.9495820683613795 and parameters: {'weight_class_0': 0.35623090735938523, 'weight_class_1': 7.867029841512146, 'weight_class_2': 3.353670553906072}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:23,295] Trial 209 finished with value: 0.9486343279286186 and parameters: {'weight_class_0': 0.6486265592343866, 'weight_class_1': 7.820852730188568, 'weight_class_2': 3.670027264449967}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:23,325] Trial 210 finished with value: 0.9496347186534261 and parameters: {'weight_class_0': 0.375118759362722, 'weight_class_1': 8.015683885556495, 'weight_class_2': 3.5496790836177854}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:23,358] Trial 212 finished with value: 0.9490005572628197 and parameters: {'weight_class_0': 0.8844894900348304, 'weight_class_1': 7.981511009305162, 'weight_class_2': 6.0595952617832936}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:23,369] Trial 211 finished with value: 0.9488001967897967 and parameters: {'weight_class_0': 0.9617242313855695, 'weight_class_1': 7.943887402096469, 'weight_class_2': 6.524471674323905}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:23,389] Trial 214 finished with value: 0.649989488021557 and parameters: {'weight_class_0': 0.9508560734749134, 'weight_class_1': 0.002250518436073701, 'weight_class_2': 6.480199177619601}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:23,401] Trial 213 finished with value: 0.9490822435122771 and parameters: {'weight_class_0': 0.9135228337018586, 'weight_class_1': 8.094322873433835, 'weight_class_2': 6.5033128023279305}. Best is trial 124 with value: 0.9498254611930451.

Best trial: 225. Best value: 0.949837:  45%|████████████████████████████████████████████████████████████                                                                         | 226/500 [00:04<00:05, 53.17it/s]

[I 2026-07-13 11:29:23,436] Trial 215 finished with value: 0.9487789612229524 and parameters: {'weight_class_0': 0.9612432001367304, 'weight_class_1': 7.741807556565043, 'weight_class_2': 6.553200291757957}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:23,446] Trial 216 finished with value: 0.8803063076749732 and parameters: {'weight_class_0': 0.828136670589776, 'weight_class_1': 4.267262052178121, 'weight_class_2': 0.03188347053218702}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:23,458] Trial 217 finished with value: 0.9485997791929762 and parameters: {'weight_class_0': 0.881452838176085, 'weight_class_1': 5.781436194414892, 'weight_class_2': 6.337578601111436}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:23,467] Trial 218 finished with value: 0.9490690669477404 and parameters: {'weight_class_0': 0.7938912333805271, 'weight_class_1': 5.834050540632128, 'weight_class_2': 6.414164426660934}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:23,509] Trial 219 finished with value: 0.9484762674519452 and parameters: {'weight_class_0': 0.9034209111848198, 'weight_class_1': 5.776571310258242, 'weight_class_2': 6.464440664500701}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:23,531] Trial 220 finished with value: 0.948206524569383 and parameters: {'weight_class_0': 0.7577633800442195, 'weight_class_1': 5.668516087682019, 'weight_class_2': 4.320581847110519}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:23,533] Trial 221 finished with value: 0.9489856759098291 and parameters: {'weight_class_0': 0.8079560692732305, 'weight_class_1': 5.755898642477481, 'weight_class_2': 6.814560263115438}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:23,559] Trial 222 finished with value: 0.9480323759233807 and parameters: {'weight_class_0': 0.7811532151162147, 'weight_class_1': 5.604232936878474, 'weight_class_2': 4.281648101128984}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:23,582] Trial 223 finished with value: 0.7972411632513247 and parameters: {'weight_class_0': 0.8142388135114637, 'weight_class_1': 0.020386477292432245, 'weight_class_2': 0.03846095659353936}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:23,600] Trial 224 finished with value: 0.7619156517512877 and parameters: {'weight_class_0': 0.013270778275022842, 'weight_class_1': 5.649505862704979, 'weight_class_2': 4.439313106913017}. Best is trial 124 with value: 0.9498254611930451.
[I 2026-07-13 11:29:23,634] Trial 225 finished with value: 0.949837159236972 and parameters: {'weight_class_0': 0.36791956594161135, 'weight_class_1': 5.789268926934826, 'weight_class_2': 4.406824315043099}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:23,636] Trial 226 finished with value: 0.94941276462941 and parameters: {'weight_class_0': 0.37184569358690583, 'weight_class_1': 9.975531966520021, 'weight_class_2': 4.335777364238364}. Best is trial 225 with value: 0.949837159236972.

Best trial: 225. Best value: 0.949837:  47%|███████████████████████████████████████████████████████████████                                                                      | 237/500 [00:04<00:04, 54.38it/s]

[I 2026-07-13 11:29:23,653] Trial 227 finished with value: 0.9482477704792273 and parameters: {'weight_class_0': 0.25432701120554185, 'weight_class_1': 9.957549125694932, 'weight_class_2': 4.269917170437523}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:23,673] Trial 228 finished with value: 0.8735431723368356 and parameters: {'weight_class_0': 0.36689771011281536, 'weight_class_1': 0.029983344087298164, 'weight_class_2': 4.192616642475796}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:23,706] Trial 229 finished with value: 0.9494020057425775 and parameters: {'weight_class_0': 0.3580379160170699, 'weight_class_1': 9.891372376087686, 'weight_class_2': 4.547581262600983}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:23,711] Trial 230 finished with value: 0.9494683134025874 and parameters: {'weight_class_0': 0.3741417142672494, 'weight_class_1': 9.963545920471883, 'weight_class_2': 4.483112069943897}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:23,733] Trial 232 finished with value: 0.949530484504591 and parameters: {'weight_class_0': 0.3952375289863348, 'weight_class_1': 9.60889089708731, 'weight_class_2': 4.550302096023701}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:23,740] Trial 231 finished with value: 0.9494356732039995 and parameters: {'weight_class_0': 0.362916919955655, 'weight_class_1': 9.705469891341622, 'weight_class_2': 4.720598116795611}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:23,764] Trial 233 finished with value: 0.9496668185917878 and parameters: {'weight_class_0': 0.6106106227594218, 'weight_class_1': 9.853940818529694, 'weight_class_2': 8.650716342192236}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:23,782] Trial 234 finished with value: 0.9497146979995863 and parameters: {'weight_class_0': 0.6220231081401819, 'weight_class_1': 8.461845289368702, 'weight_class_2': 8.405506558802138}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:23,807] Trial 235 finished with value: 0.9496638333287079 and parameters: {'weight_class_0': 0.6283379339031946, 'weight_class_1': 7.2939588706533875, 'weight_class_2': 8.24827935380209}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:23,857] Trial 236 finished with value: 0.9495581364388741 and parameters: {'weight_class_0': 0.5971702712879019, 'weight_class_1': 7.294764827044221, 'weight_class_2': 8.417752178557059}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:23,870] Trial 237 finished with value: 0.8901896036028538 and parameters: {'weight_class_0': 0.61064151736176, 'weight_class_1': 7.391773681376265, 'weight_class_2': 0.0891033820015507}. Best is trial 225 with value: 0.949837159236972.

Best trial: 225. Best value: 0.949837:  50%|█████████████████████████████████████████████████████████████████▉                                                                   | 248/500 [00:04<00:04, 54.73it/s]

[I 2026-07-13 11:29:23,872] Trial 238 finished with value: 0.9497147674879685 and parameters: {'weight_class_0': 0.6288444657979554, 'weight_class_1': 8.418617099377292, 'weight_class_2': 8.418981376953285}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:23,879] Trial 239 finished with value: 0.9496682701969092 and parameters: {'weight_class_0': 0.6237018930581341, 'weight_class_1': 7.282663755236645, 'weight_class_2': 8.178732570817909}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:23,897] Trial 240 finished with value: 0.9496027193943091 and parameters: {'weight_class_0': 0.5902835010262039, 'weight_class_1': 7.407053851015113, 'weight_class_2': 8.530738858712478}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:23,921] Trial 241 finished with value: 0.9495284811693782 and parameters: {'weight_class_0': 0.6186341587567342, 'weight_class_1': 7.094521529801281, 'weight_class_2': 8.729723756474499}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:23,940] Trial 242 finished with value: 0.9495832619748664 and parameters: {'weight_class_0': 0.6262746864015303, 'weight_class_1': 7.37508674375051, 'weight_class_2': 8.620450752390177}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:23,954] Trial 244 finished with value: 0.9496043014126903 and parameters: {'weight_class_0': 0.6388292452483167, 'weight_class_1': 7.794983668448011, 'weight_class_2': 8.692287964546166}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:23,959] Trial 243 finished with value: 0.949658848266122 and parameters: {'weight_class_0': 0.6061446685430898, 'weight_class_1': 7.8817904843139655, 'weight_class_2': 8.772179562456444}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:24,000] Trial 245 finished with value: 0.9495889593794073 and parameters: {'weight_class_0': 0.6108571269606087, 'weight_class_1': 7.4415617342076965, 'weight_class_2': 8.403284850109225}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:24,020] Trial 246 finished with value: 0.949604793536842 and parameters: {'weight_class_0': 0.6355344423743032, 'weight_class_1': 7.256155879261152, 'weight_class_2': 8.684842823878018}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:24,034] Trial 247 finished with value: 0.9496863379259107 and parameters: {'weight_class_0': 0.6630877830161821, 'weight_class_1': 7.205546608052712, 'weight_class_2': 8.722242905762831}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:24,044] Trial 248 finished with value: 0.9495457946572299 and parameters: {'weight_class_0': 0.6503493105695983, 'weight_class_1': 7.1053621201546475, 'weight_class_2': 8.994073666921015}. Best is trial 225 with value: 0.949837159236972.

Best trial: 225. Best value: 0.949837:  52%|█████████████████████████████████████████████████████████████████████▏                                                               | 260/500 [00:04<00:04, 54.27it/s]

[I 2026-07-13 11:29:24,097] Trial 249 finished with value: 0.9496548371639336 and parameters: {'weight_class_0': 0.6891848914826354, 'weight_class_1': 8.302247502669971, 'weight_class_2': 9.145021419991023}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:24,098] Trial 250 finished with value: 0.9497068035178721 and parameters: {'weight_class_0': 0.6602642351050357, 'weight_class_1': 8.466097600161405, 'weight_class_2': 8.749855258008882}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:24,110] Trial 251 finished with value: 0.9495836237523821 and parameters: {'weight_class_0': 0.680611725879424, 'weight_class_1': 8.359619201686536, 'weight_class_2': 9.805900084401095}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:24,135] Trial 252 finished with value: 0.9495850008060215 and parameters: {'weight_class_0': 0.7080234269940099, 'weight_class_1': 8.387224447531747, 'weight_class_2': 9.715347196923648}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:24,137] Trial 253 finished with value: 0.9496277599137798 and parameters: {'weight_class_0': 0.6731612286401191, 'weight_class_1': 8.63963817370111, 'weight_class_2': 9.58186935640688}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:24,168] Trial 254 finished with value: 0.9495924838650422 and parameters: {'weight_class_0': 0.705007386725297, 'weight_class_1': 8.59336014421729, 'weight_class_2': 9.706700833876289}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:24,178] Trial 255 finished with value: 0.9495319119055668 and parameters: {'weight_class_0': 0.6943117518839313, 'weight_class_1': 8.275848053053412, 'weight_class_2': 9.843682820892845}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:24,195] Trial 256 finished with value: 0.9485551532186239 and parameters: {'weight_class_0': 0.7246891452492314, 'weight_class_1': 4.577032237578372, 'weight_class_2': 9.610456000802941}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:24,211] Trial 257 finished with value: 0.9484619771847926 and parameters: {'weight_class_0': 0.7242346962642259, 'weight_class_1': 4.440870096664134, 'weight_class_2': 9.800335486305848}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:24,236] Trial 258 finished with value: 0.948460876488674 and parameters: {'weight_class_0': 0.7354836640412394, 'weight_class_1': 4.423578695247, 'weight_class_2': 9.794884940755635}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:24,256] Trial 260 finished with value: 0.9490313032319654 and parameters: {'weight_class_0': 0.4952693037100093, 'weight_class_1': 4.288825725707952, 'weight_class_2': 7.294872175041433}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:24,258] Trial 259 finished with value: 0.9482295238234214 and parameters: {'weight_class_0': 0.7375564749287916, 'weight_class_1': 4.22371968887767, 'weight_class_2': 9.979752618462848}. Best is trial 225 with value: 0.949837159236972.

Best trial: 225. Best value: 0.949837:  54%|████████████████████████████████████████████████████████████████████████▎                                                            | 272/500 [00:05<00:04, 53.60it/s]

[I 2026-07-13 11:29:24,294] Trial 261 finished with value: 0.9494692222209874 and parameters: {'weight_class_0': 0.5174089889947961, 'weight_class_1': 4.645296633791774, 'weight_class_2': 5.8240358624720665}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:24,309] Trial 262 finished with value: 0.9491124474447282 and parameters: {'weight_class_0': 0.507608555166741, 'weight_class_1': 4.451482853720251, 'weight_class_2': 7.285384910982768}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:24,327] Trial 263 finished with value: 0.9490930938980703 and parameters: {'weight_class_0': 0.5116655493087596, 'weight_class_1': 4.452494886390647, 'weight_class_2': 7.423436069164339}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:24,347] Trial 264 finished with value: 0.9493762150894366 and parameters: {'weight_class_0': 0.49720178702775364, 'weight_class_1': 4.832684379943901, 'weight_class_2': 7.049148388990783}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:24,357] Trial 265 finished with value: 0.9495639992863166 and parameters: {'weight_class_0': 0.46485120481646913, 'weight_class_1': 6.3277469729605835, 'weight_class_2': 7.089187931295632}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:24,387] Trial 266 finished with value: 0.9495444244321177 and parameters: {'weight_class_0': 0.47539576960130553, 'weight_class_1': 6.033932333350857, 'weight_class_2': 7.184874578686225}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:24,405] Trial 267 finished with value: 0.9496301656616924 and parameters: {'weight_class_0': 0.5017002847975477, 'weight_class_1': 6.1419970277478955, 'weight_class_2': 6.7768284678921225}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:24,427] Trial 268 finished with value: 0.9495804264542667 and parameters: {'weight_class_0': 0.4894621398094502, 'weight_class_1': 6.093260901337896, 'weight_class_2': 7.179261766818385}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:24,431] Trial 269 finished with value: 0.9497484666557617 and parameters: {'weight_class_0': 0.45960777981913414, 'weight_class_1': 5.869088789318886, 'weight_class_2': 5.739587786545362}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:24,461] Trial 270 finished with value: 0.9494711356932126 and parameters: {'weight_class_0': 0.4598324868653163, 'weight_class_1': 5.902914550989348, 'weight_class_2': 7.217035254338924}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:24,476] Trial 271 finished with value: 0.948130906834268 and parameters: {'weight_class_0': 1.0474324734197922, 'weight_class_1': 6.129973233808856, 'weight_class_2': 7.00252535992764}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:24,486] Trial 272 finished with value: 0.9483463442989262 and parameters: {'weight_class_0': 0.9817861175353912, 'weight_class_1': 6.104589675856324, 'weight_class_2': 6.7334639041869035}. Best is trial 225 with value: 0.949837159236972.

[I 2026-07-13 11:29:24,514] Trial 273 finished with value: 0.9482762721999233 and parameters: {'weight_class_0': 0.9062495683803995, 'weight_class_1': 6.205926830524412, 'weight_class_2': 5.60713433692209}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:24,533] Trial 275 finished with value: 0.9480511626534441 and parameters: {'weight_class_0': 0.974660259568385, 'weight_class_1': 6.333504085658317, 'weight_class_2': 5.714510424817844}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:24,539] Trial 274 finished with value: 0.948128489680252 and parameters: {'weight_class_0': 0.9297067395443828, 'weight_class_1': 6.284177765628368, 'weight_class_2': 5.463425147866071}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:24,560] Trial 276 finished with value: 0.9487770243014609 and parameters: {'weight_class_0': 0.9505596090926438, 'weight_class_1': 9.96504179563346, 'weight_class_2': 5.634016380932794}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:24,582] Trial 277 finished with value: 0.9480089186814492 and parameters: {'weight_class_0': 1.0797909392644784, 'weight_class_1': 8.609787361309357, 'weight_class_2': 5.606520607355631}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:24,610] Trial 278 finished with value: 0.9498361370420901 and parameters: {'weight_class_0': 0.5741880825625887, 'weight_class_1': 9.880845512942336, 'weight_class_2': 5.642522517488195}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:24,628] Trial 279 finished with value: 0.9485107868995964 and parameters: {'weight_class_0': 1.0607240402398495, 'weight_class_1': 9.834909933721576, 'weight_class_2': 5.823151468916894}. Best is trial 225 with value: 0.949837159236972.
[I 2026-07-13 11:29:24,648] Trial 280 finished with value: 0.9498545110951545 and parameters: {'weight_class_0': 0.5650795829127894, 'weight_class_1': 8.874499438112315, 'weight_class_2': 5.685646141432975}. Best is trial 280 with value: 0.9498545110951545.
[I 2026-07-13 11:29:24,662] Trial 281 finished with value: 0.9498204026479696 and parameters: {'weight_class_0': 0.5580951985097908, 'weight_class_1': 9.975698258395614, 'weight_class_2': 5.525991212039722}. Best is trial 280 with value: 0.9498545110951545.
[I 2026-07-13 11:29:24,678] Trial 282 finished with value: 0.9498395553060449 and parameters: {'weight_class_0': 0.5599390531164725, 'weight_class_1': 8.511164771227874, 'weight_class_2': 5.7547530891972}. Best is trial 280 with value: 0.9498545110951545.
[I 2026-07-13 11:29:24,697] Trial 283 finished with value: 0.9498528366559699 and parameters: {'weight_class_0': 0.5955233210130302, 'weight_class_1': 9.894089715320021, 'weight_class_2': 5.9038944152407185}. Best is trial 280 with value: 0.9498545110951545.

Best trial: 284. Best value: 0.949869:  59%|██████████████████████████████████████████████████████████████████████████████▏                                                      | 294/500 [00:05<00:03, 52.50it/s]

[I 2026-07-13 11:29:24,712] Trial 284 finished with value: 0.9498687991528469 and parameters: {'weight_class_0': 0.5759670083018597, 'weight_class_1': 8.885748477657396, 'weight_class_2': 5.804397054769949}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:24,726] Trial 285 finished with value: 0.9498231652082425 and parameters: {'weight_class_0': 0.5557584476187144, 'weight_class_1': 8.466548925477426, 'weight_class_2': 6.017800287326586}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:24,771] Trial 286 finished with value: 0.9498257685499271 and parameters: {'weight_class_0': 0.5669589145775479, 'weight_class_1': 9.952307512336128, 'weight_class_2': 5.473632161499728}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:24,788] Trial 287 finished with value: 0.9484946780892285 and parameters: {'weight_class_0': 0.2944284031541342, 'weight_class_1': 9.929361252448375, 'weight_class_2': 5.8219660835691185}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:24,809] Trial 288 finished with value: 0.949824335330972 and parameters: {'weight_class_0': 0.5925320217818767, 'weight_class_1': 8.728206830318257, 'weight_class_2': 5.681132117020548}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:24,819] Trial 289 finished with value: 0.9498049256112848 and parameters: {'weight_class_0': 0.5419747366140515, 'weight_class_1': 8.673779701871146, 'weight_class_2': 5.826093603872417}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:24,852] Trial 290 finished with value: 0.9498161658821509 and parameters: {'weight_class_0': 0.5425899294512857, 'weight_class_1': 8.26792192331078, 'weight_class_2': 5.7382511744000055}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:24,855] Trial 291 finished with value: 0.9485409008938523 and parameters: {'weight_class_0': 0.270055463331583, 'weight_class_1': 8.592911220862373, 'weight_class_2': 5.600477337731796}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:24,863] Trial 292 finished with value: 0.9498617623121093 and parameters: {'weight_class_0': 0.5568086765354547, 'weight_class_1': 8.556757871609175, 'weight_class_2': 5.614342357280023}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:24,891] Trial 294 finished with value: 0.94981571626626 and parameters: {'weight_class_0': 0.549350032235182, 'weight_class_1': 8.65162514197235, 'weight_class_2': 5.755728121445964}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:24,908] Trial 293 finished with value: 0.9498227288459334 and parameters: {'weight_class_0': 0.5402597568258328, 'weight_class_1': 8.67400665524045, 'weight_class_2': 5.617907223279381}. Best is trial 284 with value: 0.9498687991528469.

Best trial: 284. Best value: 0.949869:  61%|█████████████████████████████████████████████████████████████████████████████████▋                                                   | 307/500 [00:05<00:03, 56.52it/s]

[I 2026-07-13 11:29:24,944] Trial 295 finished with value: 0.9498050628892449 and parameters: {'weight_class_0': 0.5515783363752357, 'weight_class_1': 8.715889368383543, 'weight_class_2': 5.811120092519629}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:24,949] Trial 296 finished with value: 0.9498582300110061 and parameters: {'weight_class_0': 0.5394068581456355, 'weight_class_1': 8.64905617927935, 'weight_class_2': 5.44934904657295}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:24,972] Trial 297 finished with value: 0.9498512653777071 and parameters: {'weight_class_0': 0.5375712452140128, 'weight_class_1': 8.658309958741661, 'weight_class_2': 5.3352064744412235}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:24,990] Trial 298 finished with value: 0.9497549483756437 and parameters: {'weight_class_0': 0.43699474279326017, 'weight_class_1': 8.852363311475868, 'weight_class_2': 5.248403656747803}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,007] Trial 299 finished with value: 0.9497256035807068 and parameters: {'weight_class_0': 0.46781223110436915, 'weight_class_1': 8.755514083962758, 'weight_class_2': 5.174265024074751}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,023] Trial 300 finished with value: 0.8666343413671518 and parameters: {'weight_class_0': 9.807824746457804, 'weight_class_1': 9.99060970261765, 'weight_class_2': 5.292891142737395}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,045] Trial 301 finished with value: 0.9496399504284122 and parameters: {'weight_class_0': 0.4333082977142414, 'weight_class_1': 9.633900276517823, 'weight_class_2': 4.942477512228346}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,061] Trial 302 finished with value: 0.9496788513839042 and parameters: {'weight_class_0': 0.5351320422896058, 'weight_class_1': 9.864753915526123, 'weight_class_2': 4.980474537849398}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,063] Trial 303 finished with value: 0.7925436842733363 and parameters: {'weight_class_0': 0.438722204566067, 'weight_class_1': 9.750849250313223, 'weight_class_2': 0.015316237154353743}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,111] Trial 304 finished with value: 0.9497698229980513 and parameters: {'weight_class_0': 0.5273630140135491, 'weight_class_1': 9.59130983540456, 'weight_class_2': 5.0224389471030975}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,135] Trial 305 finished with value: 0.9494098802034884 and parameters: {'weight_class_0': 0.5288443740456161, 'weight_class_1': 9.968602850044032, 'weight_class_2': 4.082489345976355}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,151] Trial 306 finished with value: 0.9494462969431422 and parameters: {'weight_class_0': 0.5328451978732885, 'weight_class_1': 9.883385931079749, 'weight_class_2': 4.177850755596198}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,159] Trial 307 finished with value: 0.9496266370840057 and parameters: {'weight_class_0': 0.5450219266228098, 'weight_class_1': 9.97207050172015, 'weight_class_2': 4.890106346133169}. Best is trial 284 with value: 0.9498687991528469.

Best trial: 284. Best value: 0.949869:  64%|████████████████████████████████████████████████████████████████████████████████████▌                                                | 318/500 [00:05<00:03, 56.39it/s]

[I 2026-07-13 11:29:25,180] Trial 308 finished with value: 0.949235317860234 and parameters: {'weight_class_0': 0.5412371552316395, 'weight_class_1': 9.83812475686217, 'weight_class_2': 3.8384892735930567}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,187] Trial 309 finished with value: 0.9493043446881114 and parameters: {'weight_class_0': 0.5408749208790109, 'weight_class_1': 9.979917604573005, 'weight_class_2': 3.9579921899421153}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,212] Trial 310 finished with value: 0.9494420507040767 and parameters: {'weight_class_0': 0.5585063574900468, 'weight_class_1': 8.522047737546307, 'weight_class_2': 4.109389271103418}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,224] Trial 312 finished with value: 0.949449926123935 and parameters: {'weight_class_0': 0.5360450078725434, 'weight_class_1': 8.17666148654568, 'weight_class_2': 3.937880521559761}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,227] Trial 311 finished with value: 0.9496395968568061 and parameters: {'weight_class_0': 0.5386521598155334, 'weight_class_1': 8.387823926471782, 'weight_class_2': 4.339548726763708}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,250] Trial 313 finished with value: 0.9492623660202764 and parameters: {'weight_class_0': 0.5371668330080476, 'weight_class_1': 9.986976744433285, 'weight_class_2': 3.8782263561140047}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,279] Trial 314 finished with value: 0.9494323322718888 and parameters: {'weight_class_0': 0.5401315639039971, 'weight_class_1': 8.453571319574072, 'weight_class_2': 3.9929066097269628}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,290] Trial 315 finished with value: 0.949723971896402 and parameters: {'weight_class_0': 0.513095954965339, 'weight_class_1': 8.43307226745823, 'weight_class_2': 4.722729896457398}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,317] Trial 316 finished with value: 0.9496801021052952 and parameters: {'weight_class_0': 0.5372859264256201, 'weight_class_1': 8.438846642904188, 'weight_class_2': 4.558195755812952}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,339] Trial 317 finished with value: 0.949439756240944 and parameters: {'weight_class_0': 0.5506547917815109, 'weight_class_1': 7.163478030620264, 'weight_class_2': 4.066871322349534}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,350] Trial 318 finished with value: 0.9494368511624772 and parameters: {'weight_class_0': 0.36487842633100287, 'weight_class_1': 7.272686429261042, 'weight_class_2': 2.8434158201098603}. Best is trial 284 with value: 0.9498687991528469.

[I 2026-07-13 11:29:25,378] Trial 320 finished with value: 0.949168105468558 and parameters: {'weight_class_0': 0.4139758332938785, 'weight_class_1': 7.126792592686873, 'weight_class_2': 2.819283307621291}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,385] Trial 319 finished with value: 0.9494076936608398 and parameters: {'weight_class_0': 0.4038170835261919, 'weight_class_1': 7.075803508768357, 'weight_class_2': 3.0317327550288127}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,400] Trial 321 finished with value: 0.949492647264835 and parameters: {'weight_class_0': 0.3278682092755794, 'weight_class_1': 7.024496170744938, 'weight_class_2': 2.985693655180865}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,407] Trial 322 finished with value: 0.949380289634353 and parameters: {'weight_class_0': 0.408588164325549, 'weight_class_1': 6.86487321787902, 'weight_class_2': 3.0076515854463266}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,433] Trial 323 finished with value: 0.9492159926102394 and parameters: {'weight_class_0': 0.32993939354618634, 'weight_class_1': 7.340301242470291, 'weight_class_2': 5.93560840401314}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,467] Trial 324 finished with value: 0.9492307572639435 and parameters: {'weight_class_0': 0.3231930269823262, 'weight_class_1': 7.034291541697686, 'weight_class_2': 5.825331780746719}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,474] Trial 325 finished with value: 0.7813803899939327 and parameters: {'weight_class_0': 0.34393355618830845, 'weight_class_1': 7.03073742868884, 'weight_class_2': 0.009874248571148941}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,506] Trial 326 finished with value: 0.9494403113260924 and parameters: {'weight_class_0': 0.3632568244311574, 'weight_class_1': 7.077499036313055, 'weight_class_2': 5.822579468954345}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,521] Trial 327 finished with value: 0.9493481526706616 and parameters: {'weight_class_0': 0.3448182483493664, 'weight_class_1': 7.080646768030362, 'weight_class_2': 5.7582671256226625}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,522] Trial 328 finished with value: 0.9496874933274461 and parameters: {'weight_class_0': 0.4143321779700038, 'weight_class_1': 6.76522473591441, 'weight_class_2': 5.843754093037829}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,564] Trial 329 finished with value: 0.9492539090732045 and parameters: {'weight_class_0': 0.7910627656221855, 'weight_class_1': 6.970890005683194, 'weight_class_2': 6.003293024073209}. Best is trial 284 with value: 0.9498687991528469.

Best trial: 284. Best value: 0.949869:  68%|██████████████████████████████████████████████████████████████████████████████████████████▋                                          | 341/500 [00:06<00:02, 55.89it/s]

[I 2026-07-13 11:29:25,588] Trial 330 finished with value: 0.9492628461813251 and parameters: {'weight_class_0': 0.7821968674809523, 'weight_class_1': 6.90267359372419, 'weight_class_2': 5.9325142506614315}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,602] Trial 332 finished with value: 0.9488961835407208 and parameters: {'weight_class_0': 0.8502669930134652, 'weight_class_1': 8.196639021495233, 'weight_class_2': 5.439137892413903}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,615] Trial 331 finished with value: 0.9490593627609275 and parameters: {'weight_class_0': 0.8264560720375701, 'weight_class_1': 7.189471917128838, 'weight_class_2': 5.979099746710291}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,635] Trial 333 finished with value: 0.9486183679639595 and parameters: {'weight_class_0': 0.8047333788504034, 'weight_class_1': 5.438629819699988, 'weight_class_2': 5.732682863282094}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,640] Trial 334 finished with value: 0.9486498679445888 and parameters: {'weight_class_0': 0.8008312823730372, 'weight_class_1': 5.511960758905434, 'weight_class_2': 5.6696782771272165}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,663] Trial 335 finished with value: 0.9488960026550571 and parameters: {'weight_class_0': 0.7756749281920317, 'weight_class_1': 5.461860858455643, 'weight_class_2': 5.945748033777479}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,688] Trial 336 finished with value: 0.9482646551991563 and parameters: {'weight_class_0': 0.7955447566679946, 'weight_class_1': 5.429481412976935, 'weight_class_2': 4.961641939920393}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,703] Trial 337 finished with value: 0.9490262084975595 and parameters: {'weight_class_0': 0.7672977888163083, 'weight_class_1': 8.549337638122484, 'weight_class_2': 5.019043231657991}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,720] Trial 338 finished with value: 0.9482590123306119 and parameters: {'weight_class_0': 0.808660356714975, 'weight_class_1': 5.287719951917011, 'weight_class_2': 5.149585758410215}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,746] Trial 339 finished with value: 0.6958328074156533 and parameters: {'weight_class_0': 0.7882905044940837, 'weight_class_1': 5.332937320036659, 'weight_class_2': 0.00367215040072826}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,763] Trial 340 finished with value: 0.948142662001992 and parameters: {'weight_class_0': 0.839265808153088, 'weight_class_1': 5.472905136178842, 'weight_class_2': 5.083325839221038}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,776] Trial 341 finished with value: 0.9483641792732579 and parameters: {'weight_class_0': 0.7671860073038862, 'weight_class_1': 5.3292500558222695, 'weight_class_2': 4.949618169474322}. Best is trial 284 with value: 0.9498687991528469.

Best trial: 284. Best value: 0.949869:  71%|██████████████████████████████████████████████████████████████████████████████████████████████▏                                      | 354/500 [00:06<00:02, 56.06it/s]

[I 2026-07-13 11:29:25,805] Trial 342 finished with value: 0.8822332315468137 and parameters: {'weight_class_0': 0.6313594566651651, 'weight_class_1': 0.10122471762445708, 'weight_class_2': 4.740314190617029}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,807] Trial 343 finished with value: 0.9497537555671114 and parameters: {'weight_class_0': 0.44756601028445964, 'weight_class_1': 8.455425768500815, 'weight_class_2': 4.684903466101914}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,841] Trial 344 finished with value: 0.9498246571136901 and parameters: {'weight_class_0': 0.4748923009734893, 'weight_class_1': 8.463412750943867, 'weight_class_2': 4.76928274710909}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,846] Trial 345 finished with value: 0.9497088057995202 and parameters: {'weight_class_0': 0.42992186532889626, 'weight_class_1': 8.512166328598381, 'weight_class_2': 4.769906290574731}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,856] Trial 346 finished with value: 0.9495401926980779 and parameters: {'weight_class_0': 0.4432463775946311, 'weight_class_1': 8.625342155024565, 'weight_class_2': 6.715532714249729}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,873] Trial 347 finished with value: 0.949765740564855 and parameters: {'weight_class_0': 0.45457209479375993, 'weight_class_1': 8.632108451884852, 'weight_class_2': 4.76634478493089}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,912] Trial 349 finished with value: 0.9494322849017345 and parameters: {'weight_class_0': 0.42374294965951, 'weight_class_1': 8.44371479412467, 'weight_class_2': 6.755414532685489}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,919] Trial 348 finished with value: 0.8898862535645136 and parameters: {'weight_class_0': 0.4637019900634063, 'weight_class_1': 0.13175720064110996, 'weight_class_2': 6.742352095241883}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,927] Trial 350 finished with value: 0.94975905401634 and parameters: {'weight_class_0': 0.6040395496362234, 'weight_class_1': 8.563503780124222, 'weight_class_2': 6.669711203332582}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,941] Trial 351 finished with value: 0.9495105296131138 and parameters: {'weight_class_0': 0.44920310011813475, 'weight_class_1': 8.546321950586293, 'weight_class_2': 6.894767737750104}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,962] Trial 352 finished with value: 0.9493000941262681 and parameters: {'weight_class_0': 0.4544246008418161, 'weight_class_1': 9.93324594899451, 'weight_class_2': 3.444600239225281}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:25,995] Trial 353 finished with value: 0.9496118875964595 and parameters: {'weight_class_0': 0.4626028497738016, 'weight_class_1': 8.47840823345055, 'weight_class_2': 6.788507420515223}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,010] Trial 354 finished with value: 0.9485691720746567 and parameters: {'weight_class_0': 0.6173466907370505, 'weight_class_1': 9.972529906135609, 'weight_class_2': 3.3847760423649706}. Best is trial 284 with value: 0.9498687991528469.

[I 2026-07-13 11:29:26,026] Trial 355 finished with value: 0.9485720949196486 and parameters: {'weight_class_0': 0.6245353556583573, 'weight_class_1': 9.969936544161202, 'weight_class_2': 3.4455120244118613}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,044] Trial 356 finished with value: 0.9488002973441633 and parameters: {'weight_class_0': 0.5821117426925734, 'weight_class_1': 8.307895495430662, 'weight_class_2': 3.4401110619442865}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,071] Trial 357 finished with value: 0.9497547152126486 and parameters: {'weight_class_0': 0.6093399087337489, 'weight_class_1': 8.553639594309411, 'weight_class_2': 6.766290106985382}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,081] Trial 358 finished with value: 0.9486722796910471 and parameters: {'weight_class_0': 0.6359825547212206, 'weight_class_1': 9.963846516034819, 'weight_class_2': 3.5869132276366904}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,082] Trial 359 finished with value: 0.8811681444486039 and parameters: {'weight_class_0': 7.337757158801735, 'weight_class_1': 8.36548824150614, 'weight_class_2': 6.838604887544713}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,137] Trial 360 finished with value: 0.8834324559311296 and parameters: {'weight_class_0': 5.762673573491277, 'weight_class_1': 9.782261363929424, 'weight_class_2': 3.601401539195624}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,146] Trial 361 finished with value: 0.9483840281868123 and parameters: {'weight_class_0': 0.6486490536289536, 'weight_class_1': 6.646426402122266, 'weight_class_2': 3.354793467704738}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,159] Trial 362 finished with value: 0.9492287028072948 and parameters: {'weight_class_0': 0.5718919177081105, 'weight_class_1': 6.633296475248214, 'weight_class_2': 4.069252788531826}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,175] Trial 363 finished with value: 0.949014753035817 and parameters: {'weight_class_0': 0.6036958564220688, 'weight_class_1': 6.426533295649463, 'weight_class_2': 3.9475784077146963}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,179] Trial 364 finished with value: 0.9488726861678831 and parameters: {'weight_class_0': 0.61228623580289, 'weight_class_1': 6.415768679947628, 'weight_class_2': 3.753755595707509}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,224] Trial 365 finished with value: 0.9489867742460114 and parameters: {'weight_class_0': 0.6016638916688302, 'weight_class_1': 6.458008562840287, 'weight_class_2': 3.8828281168778926}. Best is trial 284 with value: 0.9498687991528469.

[I 2026-07-13 11:29:26,240] Trial 367 finished with value: 0.9489394854380616 and parameters: {'weight_class_0': 0.6000048276129802, 'weight_class_1': 6.43756260653215, 'weight_class_2': 3.8085421403507}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,252] Trial 366 finished with value: 0.9489739844444838 and parameters: {'weight_class_0': 0.6517715455624306, 'weight_class_1': 6.385966982858154, 'weight_class_2': 4.210357964431599}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,281] Trial 368 finished with value: 0.949463084464882 and parameters: {'weight_class_0': 0.5617930177556665, 'weight_class_1': 6.940621212241369, 'weight_class_2': 4.251111974026286}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,298] Trial 369 finished with value: 0.9494269096573209 and parameters: {'weight_class_0': 0.5626718055875221, 'weight_class_1': 6.545380076371022, 'weight_class_2': 4.3289720019773155}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,299] Trial 370 finished with value: 0.9495313124000465 and parameters: {'weight_class_0': 0.5441122141445345, 'weight_class_1': 6.6065473844390326, 'weight_class_2': 4.358575571989775}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,313] Trial 371 finished with value: 0.9495793640792739 and parameters: {'weight_class_0': 0.5313540620849622, 'weight_class_1': 6.685303931325099, 'weight_class_2': 4.48320023195292}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,365] Trial 373 finished with value: 0.9489163647192624 and parameters: {'weight_class_0': 0.5012031624626385, 'weight_class_1': 3.5646356266874615, 'weight_class_2': 6.230170826568528}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,366] Trial 372 finished with value: 0.9493527207001589 and parameters: {'weight_class_0': 0.37517085226691155, 'weight_class_1': 7.798508773435348, 'weight_class_2': 6.136783833300385}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,372] Trial 374 finished with value: 0.9494490462913246 and parameters: {'weight_class_0': 0.37908372830754233, 'weight_class_1': 7.4292008767794595, 'weight_class_2': 5.9094926695059895}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,390] Trial 375 finished with value: 0.6629128553253439 and parameters: {'weight_class_0': 0.3818907549300818, 'weight_class_1': 0.0016462470345525082, 'weight_class_2': 6.048553449238025}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,395] Trial 376 finished with value: 0.8951333872026807 and parameters: {'weight_class_0': 0.39251127513983836, 'weight_class_1': 7.806748598109307, 'weight_class_2': 0.14152875197942727}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,422] Trial 377 finished with value: 0.9488501725428633 and parameters: {'weight_class_0': 0.29636902972600954, 'weight_class_1': 7.945121018716719, 'weight_class_2': 5.996358375587328}. Best is trial 284 with value: 0.9498687991528469.

[I 2026-07-13 11:29:26,464] Trial 379 finished with value: 0.9495385051081083 and parameters: {'weight_class_0': 0.4013580681193943, 'weight_class_1': 7.7984896703447335, 'weight_class_2': 6.087151373737237}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,477] Trial 378 finished with value: 0.9487398939997899 and parameters: {'weight_class_0': 0.2860779280595084, 'weight_class_1': 7.94050268784619, 'weight_class_2': 6.044914706439858}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,492] Trial 380 finished with value: 0.9481449594954938 and parameters: {'weight_class_0': 0.28058682347208125, 'weight_class_1': 9.994955039438846, 'weight_class_2': 6.3753620286784205}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,525] Trial 381 finished with value: 0.9278900464027277 and parameters: {'weight_class_0': 0.28557362766690897, 'weight_class_1': 7.913987873161714, 'weight_class_2': 0.4622343692953258}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,530] Trial 382 finished with value: 0.9485233649754102 and parameters: {'weight_class_0': 0.2721758782843258, 'weight_class_1': 8.173884615058327, 'weight_class_2': 6.1803821623042525}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,539] Trial 383 finished with value: 0.9485709939855561 and parameters: {'weight_class_0': 0.3086942918367654, 'weight_class_1': 8.068586828284623, 'weight_class_2': 7.571648143452789}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,567] Trial 384 finished with value: 0.9485592546592145 and parameters: {'weight_class_0': 0.3060998742560697, 'weight_class_1': 8.126233647150094, 'weight_class_2': 7.502530626588229}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,587] Trial 385 finished with value: 0.9480791198013678 and parameters: {'weight_class_0': 0.29017388147686307, 'weight_class_1': 9.95267467303475, 'weight_class_2': 7.217710301477481}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,594] Trial 386 finished with value: 0.948035813483244 and parameters: {'weight_class_0': 1.276366369840685, 'weight_class_1': 8.15503132166713, 'weight_class_2': 7.662544202311298}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,606] Trial 387 finished with value: 0.9498476454105104 and parameters: {'weight_class_0': 0.7237979300574394, 'weight_class_1': 9.994839170210494, 'weight_class_2': 7.052180718936507}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,625] Trial 388 finished with value: 0.9497894742671038 and parameters: {'weight_class_0': 0.7129562398964089, 'weight_class_1': 9.99443743381593, 'weight_class_2': 7.589074727330319}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,646] Trial 389 finished with value: 0.902523372945432 and parameters: {'weight_class_0': 0.6890090157452223, 'weight_class_1': 0.37690319432944297, 'weight_class_2': 7.537725363234205}. Best is trial 284 with value: 0.9498687991528469.

[I 2026-07-13 11:29:26,681] Trial 391 finished with value: 0.6637357198277541 and parameters: {'weight_class_0': 0.00805146054966464, 'weight_class_1': 9.894490669359328, 'weight_class_2': 7.545273520510336}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,687] Trial 390 finished with value: 0.9493251401822621 and parameters: {'weight_class_0': 0.47503519449785886, 'weight_class_1': 9.893735110430004, 'weight_class_2': 7.890538546597245}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,698] Trial 392 finished with value: 0.94916175697455 and parameters: {'weight_class_0': 0.46833443580323114, 'weight_class_1': 4.995272431374801, 'weight_class_2': 7.616960846449052}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,737] Trial 394 finished with value: 0.9497930350415387 and parameters: {'weight_class_0': 0.704842424097173, 'weight_class_1': 9.912532670687959, 'weight_class_2': 7.69467369823338}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,739] Trial 393 finished with value: 0.9452400073038204 and parameters: {'weight_class_0': 1.3459868397020538, 'weight_class_1': 5.292676129826838, 'weight_class_2': 7.489872377679604}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,748] Trial 395 finished with value: 0.9449575627018634 and parameters: {'weight_class_0': 1.2139908392273553, 'weight_class_1': 5.621339005449193, 'weight_class_2': 5.148349113322455}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,778] Trial 397 finished with value: 0.9496828990422569 and parameters: {'weight_class_0': 0.47056217763637165, 'weight_class_1': 9.700137472530445, 'weight_class_2': 5.234213638911265}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,791] Trial 396 finished with value: 0.9493913389754067 and parameters: {'weight_class_0': 0.7070405032971039, 'weight_class_1': 9.8246039738101, 'weight_class_2': 5.098550830054944}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,806] Trial 398 finished with value: 0.9493061107744657 and parameters: {'weight_class_0': 0.7550376416098142, 'weight_class_1': 9.80458736891342, 'weight_class_2': 5.2540806546684715}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,824] Trial 399 finished with value: 0.9497547323416482 and parameters: {'weight_class_0': 0.4930895482085344, 'weight_class_1': 9.971372930691192, 'weight_class_2': 5.015538044565439}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,856] Trial 400 finished with value: 0.9497091192605002 and parameters: {'weight_class_0': 0.4748268555199102, 'weight_class_1': 9.819354881018901, 'weight_class_2': 5.1789955330546835}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,866] Trial 401 finished with value: 0.9496591774372284 and parameters: {'weight_class_0': 0.4538286477648279, 'weight_class_1': 9.983859094328327, 'weight_class_2': 4.92005113955247}. Best is trial 284 with value: 0.9498687991528469.

[I 2026-07-13 11:29:26,888] Trial 402 finished with value: 0.9485481333056794 and parameters: {'weight_class_0': 0.7397858817073105, 'weight_class_1': 5.46542164308203, 'weight_class_2': 4.875599995726443}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,891] Trial 403 finished with value: 0.9493102803264608 and parameters: {'weight_class_0': 0.7248115928024977, 'weight_class_1': 9.94946301694687, 'weight_class_2': 5.030133497265162}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,919] Trial 404 finished with value: 0.9482742387814693 and parameters: {'weight_class_0': 1.046930168073544, 'weight_class_1': 9.94043925271923, 'weight_class_2': 5.240095650869554}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,932] Trial 405 finished with value: 0.9484082303612148 and parameters: {'weight_class_0': 0.9354303793145577, 'weight_class_1': 8.449007234278232, 'weight_class_2': 5.0573588793439175}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,954] Trial 407 finished with value: 0.9485024288698586 and parameters: {'weight_class_0': 0.9186226672758806, 'weight_class_1': 8.528906806376035, 'weight_class_2': 5.008463468771071}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,960] Trial 406 finished with value: 0.9485428532807813 and parameters: {'weight_class_0': 0.9264133415764764, 'weight_class_1': 8.31204195005643, 'weight_class_2': 5.300446899280748}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:26,973] Trial 408 finished with value: 0.9498498512206082 and parameters: {'weight_class_0': 0.49960706413764505, 'weight_class_1': 7.524814325533102, 'weight_class_2': 4.943023605035653}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,018] Trial 410 finished with value: 0.9481995679904576 and parameters: {'weight_class_0': 0.9180275606262244, 'weight_class_1': 7.512794223022131, 'weight_class_2': 5.058191362988616}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,021] Trial 409 finished with value: 0.9482770443229609 and parameters: {'weight_class_0': 0.8878904720179251, 'weight_class_1': 7.495006655828283, 'weight_class_2': 4.908107793822989}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,029] Trial 411 finished with value: 0.947810753792389 and parameters: {'weight_class_0': 1.0275698936426823, 'weight_class_1': 7.535710220811168, 'weight_class_2': 5.231221456494741}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,051] Trial 412 finished with value: 0.9473032741085312 and parameters: {'weight_class_0': 0.9885274335145958, 'weight_class_1': 7.4241514462898115, 'weight_class_2': 4.602523578790969}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,063] Trial 413 finished with value: 0.9484981387480115 and parameters: {'weight_class_0': 0.9556424456203613, 'weight_class_1': 7.123658198436208, 'weight_class_2': 6.129543037090532}. Best is trial 284 with value: 0.9498687991528469.

[I 2026-07-13 11:29:27,097] Trial 414 finished with value: 0.9487520111274201 and parameters: {'weight_class_0': 0.9132110029741457, 'weight_class_1': 7.246198638430084, 'weight_class_2': 6.151439761125422}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,118] Trial 415 finished with value: 0.9498160841888993 and parameters: {'weight_class_0': 0.5273735559594259, 'weight_class_1': 7.266998300303899, 'weight_class_2': 6.373128577332741}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,122] Trial 416 finished with value: 0.9497566293093677 and parameters: {'weight_class_0': 0.5394905230150613, 'weight_class_1': 7.213296785253196, 'weight_class_2': 6.037538371938859}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,138] Trial 417 finished with value: 0.9498032640096428 and parameters: {'weight_class_0': 0.5388159574645757, 'weight_class_1': 7.102993880861124, 'weight_class_2': 6.540705296282504}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,153] Trial 418 finished with value: 0.9498257348030498 and parameters: {'weight_class_0': 0.38758762635597954, 'weight_class_1': 6.102294831273977, 'weight_class_2': 4.204738316432736}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,168] Trial 419 finished with value: 0.856087441913434 and parameters: {'weight_class_0': 0.3823851441712247, 'weight_class_1': 0.01141267564092187, 'weight_class_2': 2.613358752268426}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,176] Trial 420 finished with value: 0.9483907523812295 and parameters: {'weight_class_0': 0.5341127729951963, 'weight_class_1': 6.328276862874164, 'weight_class_2': 2.790200325044402}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,191] Trial 421 finished with value: 0.9494031424881254 and parameters: {'weight_class_0': 0.3858587183999606, 'weight_class_1': 6.043564806552323, 'weight_class_2': 2.805880449909618}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,238] Trial 423 finished with value: 0.949779479477395 and parameters: {'weight_class_0': 0.38117528663513683, 'weight_class_1': 5.886304277603522, 'weight_class_2': 4.317734826135768}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,242] Trial 422 finished with value: 0.9482946339675924 and parameters: {'weight_class_0': 0.5437737540891705, 'weight_class_1': 5.752038075810615, 'weight_class_2': 2.7318740549484195}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,271] Trial 424 finished with value: 0.9498336932732618 and parameters: {'weight_class_0': 0.393711395089217, 'weight_class_1': 5.881232396144036, 'weight_class_2': 3.8758630702914973}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,275] Trial 425 finished with value: 0.9491989907605559 and parameters: {'weight_class_0': 0.38074811813701004, 'weight_class_1': 5.94605606940225, 'weight_class_2': 2.6070797034279196}. Best is trial 284 with value: 0.9498687991528469.

Best trial: 284. Best value: 0.949869:  87%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                | 437/500 [00:08<00:01, 56.73it/s]

[I 2026-07-13 11:29:27,290] Trial 426 finished with value: 0.949329354899338 and parameters: {'weight_class_0': 0.4035426119967394, 'weight_class_1': 5.833192650597396, 'weight_class_2': 2.8832123770266738}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,311] Trial 427 finished with value: 0.9498305140167497 and parameters: {'weight_class_0': 0.38535782483662206, 'weight_class_1': 5.970489742677917, 'weight_class_2': 3.9717990251389486}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,350] Trial 428 finished with value: 0.9496576285595197 and parameters: {'weight_class_0': 0.3809580597325487, 'weight_class_1': 3.798343570439084, 'weight_class_2': 3.5558092125733785}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,358] Trial 429 finished with value: 0.949624025785892 and parameters: {'weight_class_0': 0.36304357546747623, 'weight_class_1': 3.3953233730870256, 'weight_class_2': 3.9653620137923364}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,361] Trial 430 finished with value: 0.9497621505642001 and parameters: {'weight_class_0': 0.35010413538643637, 'weight_class_1': 5.865251244524517, 'weight_class_2': 3.911458148265898}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,383] Trial 431 finished with value: 0.9494577214701562 and parameters: {'weight_class_0': 0.4228944221323942, 'weight_class_1': 3.6029652751627674, 'weight_class_2': 4.203653442569012}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,398] Trial 432 finished with value: 0.9497667895419782 and parameters: {'weight_class_0': 0.3532770668865504, 'weight_class_1': 4.7049098379411, 'weight_class_2': 3.9732076108615693}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,428] Trial 433 finished with value: 0.9496485613103562 and parameters: {'weight_class_0': 0.43137698587607204, 'weight_class_1': 4.578378113875349, 'weight_class_2': 4.019658715401393}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,450] Trial 435 finished with value: 0.9497913375338239 and parameters: {'weight_class_0': 0.3381410995445455, 'weight_class_1': 4.170216222610549, 'weight_class_2': 3.3742797167979295}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,455] Trial 434 finished with value: 0.9496389474753819 and parameters: {'weight_class_0': 0.43144708432843165, 'weight_class_1': 6.004151515101703, 'weight_class_2': 3.484557382724736}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,466] Trial 436 finished with value: 0.9493791922619703 and parameters: {'weight_class_0': 0.2262575319100941, 'weight_class_1': 4.122024688498957, 'weight_class_2': 3.9243461957640315}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,480] Trial 437 finished with value: 0.9496461844266818 and parameters: {'weight_class_0': 0.2450633363012172, 'weight_class_1': 3.26138701408319, 'weight_class_2': 3.541967871128828}. Best is trial 284 with value: 0.9498687991528469.

[I 2026-07-13 11:29:27,509] Trial 438 finished with value: 0.9496764082603151 and parameters: {'weight_class_0': 0.3624762238199484, 'weight_class_1': 4.244121492461583, 'weight_class_2': 3.3893735624094696}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,519] Trial 439 finished with value: 0.9496805054533356 and parameters: {'weight_class_0': 0.24790445198643757, 'weight_class_1': 4.516347916846196, 'weight_class_2': 3.3072722175074576}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,549] Trial 441 finished with value: 0.9493437973185778 and parameters: {'weight_class_0': 0.2356073920171119, 'weight_class_1': 4.811319984077367, 'weight_class_2': 3.9992327031240595}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,570] Trial 440 finished with value: 0.8731656620579861 and parameters: {'weight_class_0': 0.31717177412080727, 'weight_class_1': 4.540210251656921, 'weight_class_2': 0.01987923593990687}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,598] Trial 442 finished with value: 0.9497591660540085 and parameters: {'weight_class_0': 0.32873570195026314, 'weight_class_1': 4.090109386445362, 'weight_class_2': 3.1111670196016648}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,605] Trial 443 finished with value: 0.8776793521915341 and parameters: {'weight_class_0': 0.4806793641830929, 'weight_class_1': 4.5171080739216665, 'weight_class_2': 0.02357782249196069}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,623] Trial 444 finished with value: 0.9497171073145271 and parameters: {'weight_class_0': 0.2518793058837469, 'weight_class_1': 4.777208319318074, 'weight_class_2': 3.291549378931002}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,626] Trial 445 finished with value: 0.9495824315167427 and parameters: {'weight_class_0': 0.23326795889162166, 'weight_class_1': 4.835944901418481, 'weight_class_2': 3.241188620924039}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,669] Trial 446 finished with value: 0.9497677121583935 and parameters: {'weight_class_0': 0.47314083949043534, 'weight_class_1': 5.133227584565572, 'weight_class_2': 4.632691172322356}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,676] Trial 447 finished with value: 0.8769818669972541 and parameters: {'weight_class_0': 0.4946051625831406, 'weight_class_1': 0.04668831015465269, 'weight_class_2': 4.385167591391852}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,693] Trial 449 finished with value: 0.9497558583219455 and parameters: {'weight_class_0': 0.4674553993902381, 'weight_class_1': 5.03615340682266, 'weight_class_2': 4.521244880621738}. Best is trial 284 with value: 0.9498687991528469.

Best trial: 284. Best value: 0.949869:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎          | 460/500 [00:08<00:00, 56.74it/s]

[I 2026-07-13 11:29:27,702] Trial 448 finished with value: 0.9476616319774817 and parameters: {'weight_class_0': 0.4681047746450301, 'weight_class_1': 5.189329514795734, 'weight_class_2': 2.14925543277279}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,720] Trial 450 finished with value: 0.9496542632847592 and parameters: {'weight_class_0': 0.47714059594811, 'weight_class_1': 5.16796714339894, 'weight_class_2': 6.2979961839455765}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,747] Trial 451 finished with value: 0.9487661437627525 and parameters: {'weight_class_0': 0.663504309770102, 'weight_class_1': 5.276419935589393, 'weight_class_2': 4.488933046260367}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,778] Trial 453 finished with value: 0.944932561045091 and parameters: {'weight_class_0': 0.6550573993259932, 'weight_class_1': 5.3530391229655425, 'weight_class_2': 2.2640970727896668}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,797] Trial 452 finished with value: 0.9490831537230818 and parameters: {'weight_class_0': 0.6477920706601893, 'weight_class_1': 6.005837205096951, 'weight_class_2': 4.404561818066355}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,798] Trial 454 finished with value: 0.9492777236178723 and parameters: {'weight_class_0': 0.6519819649999312, 'weight_class_1': 6.541135199323916, 'weight_class_2': 4.596293998873156}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,835] Trial 455 finished with value: 0.9496985184074355 and parameters: {'weight_class_0': 0.46991702965741666, 'weight_class_1': 6.874130455152063, 'weight_class_2': 6.323055302114559}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,843] Trial 456 finished with value: 0.9492145953171711 and parameters: {'weight_class_0': 0.6587931360811466, 'weight_class_1': 6.414821209298775, 'weight_class_2': 4.623008085216354}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,852] Trial 457 finished with value: 0.9497489635471896 and parameters: {'weight_class_0': 0.6437648863310295, 'weight_class_1': 6.668916378071431, 'weight_class_2': 6.4958263559858995}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,876] Trial 459 finished with value: 0.9497176537845097 and parameters: {'weight_class_0': 0.6615429374051874, 'weight_class_1': 6.478227502488638, 'weight_class_2': 6.588812024250962}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,888] Trial 458 finished with value: 0.9497561237337546 and parameters: {'weight_class_0': 0.6561332139613353, 'weight_class_1': 7.214835780415958, 'weight_class_2': 6.5683599770581935}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,907] Trial 461 finished with value: 0.9497415438598864 and parameters: {'weight_class_0': 0.6562588900339127, 'weight_class_1': 6.544163257711919, 'weight_class_2': 6.607954833740434}. Best is trial 284 with value: 0.9498687991528469.

Best trial: 284. Best value: 0.949869:  94%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 472/500 [00:08<00:00, 55.33it/s]

[I 2026-07-13 11:29:27,918] Trial 460 finished with value: 0.7079300097660419 and parameters: {'weight_class_0': 0.6565921551691782, 'weight_class_1': 6.683547606780894, 'weight_class_2': 0.004420292220121945}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,948] Trial 463 finished with value: 0.9420572461078396 and parameters: {'weight_class_0': 1.80325433456134, 'weight_class_1': 6.896754478239845, 'weight_class_2': 6.624761555289973}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,950] Trial 462 finished with value: 0.7205986018390043 and parameters: {'weight_class_0': 0.013315106439532012, 'weight_class_1': 6.77797847436737, 'weight_class_2': 6.4736524620245515}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:27,990] Trial 464 finished with value: 0.9497727950721825 and parameters: {'weight_class_0': 0.5762629902076984, 'weight_class_1': 7.4957811530655905, 'weight_class_2': 6.429701499751161}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:28,005] Trial 466 finished with value: 0.9498159394038609 and parameters: {'weight_class_0': 0.5824585297952253, 'weight_class_1': 7.873013279890872, 'weight_class_2': 6.821439676591558}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:28,009] Trial 465 finished with value: 0.9279445168644735 and parameters: {'weight_class_0': 3.0269264420891058, 'weight_class_1': 7.475258777485728, 'weight_class_2': 6.614446429089058}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:28,041] Trial 467 finished with value: 0.6619404065047573 and parameters: {'weight_class_0': 0.0057304050090656615, 'weight_class_1': 8.060666460313284, 'weight_class_2': 5.678957148502271}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:28,060] Trial 469 finished with value: 0.9498379538556465 and parameters: {'weight_class_0': 0.5574876773531408, 'weight_class_1': 8.22223182870703, 'weight_class_2': 5.523051749040538}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:28,062] Trial 468 finished with value: 0.9498516688488241 and parameters: {'weight_class_0': 0.5517691164389171, 'weight_class_1': 7.986616841888956, 'weight_class_2': 5.575180097934282}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:28,093] Trial 471 finished with value: 0.9498046832757194 and parameters: {'weight_class_0': 0.5693487761212102, 'weight_class_1': 7.97293936420018, 'weight_class_2': 5.422474165854269}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:28,112] Trial 472 finished with value: 0.8859623918969527 and parameters: {'weight_class_0': 0.5541593481477747, 'weight_class_1': 8.166301133397383, 'weight_class_2': 0.05863932081079437}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:28,113] Trial 470 finished with value: 0.9498421840603025 and parameters: {'weight_class_0': 0.5477807912370186, 'weight_class_1': 8.165192479083288, 'weight_class_2': 5.47707472596704}. Best is trial 284 with value: 0.9498687991528469.

Best trial: 284. Best value: 0.949869:  97%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍    | 483/500 [00:08<00:00, 54.90it/s]

[I 2026-07-13 11:29:28,122] Trial 473 finished with value: 0.9498143725149992 and parameters: {'weight_class_0': 0.5295771535932572, 'weight_class_1': 8.308358975273839, 'weight_class_2': 5.4853648523688765}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:28,151] Trial 474 finished with value: 0.9498413878866462 and parameters: {'weight_class_0': 0.5498598835683911, 'weight_class_1': 8.121524388505092, 'weight_class_2': 5.593023312906279}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:28,186] Trial 475 finished with value: 0.9492043841034916 and parameters: {'weight_class_0': 0.42409320058853667, 'weight_class_1': 8.195357794655248, 'weight_class_2': 8.076395942822257}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:28,206] Trial 477 finished with value: 0.9491441750445812 and parameters: {'weight_class_0': 0.4200040246544635, 'weight_class_1': 8.529047408444882, 'weight_class_2': 8.377332208963681}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:28,207] Trial 476 finished with value: 0.949300253962102 and parameters: {'weight_class_0': 0.43669048462658155, 'weight_class_1': 8.336718513166248, 'weight_class_2': 7.796226426355178}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:28,232] Trial 478 finished with value: 0.8877381758450053 and parameters: {'weight_class_0': 0.413371160382255, 'weight_class_1': 8.382503785061164, 'weight_class_2': 0.06158077863458761}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:28,241] Trial 479 finished with value: 0.4674641570753837 and parameters: {'weight_class_0': 0.0015922351474266113, 'weight_class_1': 0.0033727787254376235, 'weight_class_2': 5.289275284194329}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:28,254] Trial 480 finished with value: 0.9497523980482857 and parameters: {'weight_class_0': 0.4120497923662178, 'weight_class_1': 8.335533827983092, 'weight_class_2': 4.827983796324729}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:28,288] Trial 481 finished with value: 0.680991724618282 and parameters: {'weight_class_0': 0.4395023207825285, 'weight_class_1': 8.524082760676304, 'weight_class_2': 0.001976463561824759}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:28,331] Trial 483 finished with value: 0.657905400097358 and parameters: {'weight_class_0': 0.0016134170171647427, 'weight_class_1': 8.355235993546962, 'weight_class_2': 4.163053928714691}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:28,336] Trial 484 finished with value: 0.9497319430651867 and parameters: {'weight_class_0': 0.41545178997120824, 'weight_class_1': 8.453734163557558, 'weight_class_2': 4.152258516609799}. Best is trial 284 with value: 0.9498687991528469.

Best trial: 284. Best value: 0.949869: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 500/500 [00:09<00:00, 55.03it/s]

[I 2026-07-13 11:29:28,341] Trial 482 finished with value: 0.9497526844673736 and parameters: {'weight_class_0': 0.4273900718856847, 'weight_class_1': 8.446345585837355, 'weight_class_2': 4.368681688680055}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:28,357] Trial 485 finished with value: 0.6729840976204837 and parameters: {'weight_class_0': 0.4304358487352327, 'weight_class_1': 8.282016667793059, 'weight_class_2': 0.0013876641208885733}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:28,386] Trial 487 finished with value: 0.9496373961846108 and parameters: {'weight_class_0': 0.3183574194162161, 'weight_class_1': 5.5243100636438545, 'weight_class_2': 4.4092521662532285}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:28,392] Trial 486 finished with value: 0.9485625838990419 and parameters: {'weight_class_0': 0.7868854889859811, 'weight_class_1': 8.52869403368548, 'weight_class_2': 4.356933999614687}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:28,397] Trial 488 finished with value: 0.9492689919507783 and parameters: {'weight_class_0': 0.3221839178363634, 'weight_class_1': 2.708193637449706, 'weight_class_2': 4.070541066071763}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:28,423] Trial 489 finished with value: 0.9481667363890995 and parameters: {'weight_class_0': 0.7397152584889305, 'weight_class_1': 5.925032202003287, 'weight_class_2': 4.070831482030488}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:28,453] Trial 490 finished with value: 0.9483100089156745 and parameters: {'weight_class_0': 0.7564903472557862, 'weight_class_1': 5.78646954164157, 'weight_class_2': 4.456012564204611}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:28,466] Trial 491 finished with value: 0.9476896470179229 and parameters: {'weight_class_0': 0.8003878192531083, 'weight_class_1': 5.769277372289196, 'weight_class_2': 3.9339609518768532}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:28,483] Trial 492 finished with value: 0.9497456956632407 and parameters: {'weight_class_0': 0.3189815820550507, 'weight_class_1': 5.680003242780475, 'weight_class_2': 4.124131251792716}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:28,501] Trial 493 finished with value: 0.9478954917735755 and parameters: {'weight_class_0': 0.7629283977233255, 'weight_class_1': 5.8218240036889775, 'weight_class_2': 3.8998007501772456}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:28,524] Trial 494 finished with value: 0.9477585222655466 and parameters: {'weight_class_0': 0.7726358834086684, 'weight_class_1': 5.928099765112055, 'weight_class_2': 3.791654326919163}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:28,525] Trial 495 finished with value: 0.9472245008480918 and parameters: {'weight_class_0': 0.8131031730980443, 'weight_class_1': 5.841678721887311, 'weight_class_2': 3.7738829093629445}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:28,542] Trial 496 finished with value: 0.9485395598794716 and parameters: {'weight_class_0': 0.7872514412811917, 'weight_class_1': 5.6820460048127615, 'weight_class_2': 5.213607400653928}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:28,547] Trial 497 finished with value: 0.9458504576428669 and parameters: {'weight_class_0': 0.7999837972581608, 'weight_class_1': 5.942344419215238, 'weight_class_2': 3.081634949604533}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:28,552] Trial 498 finished with value: 0.9491479940837375 and parameters: {'weight_class_0': 0.7511299178121501, 'weight_class_1': 5.8389890790951045, 'weight_class_2': 8.423673594413797}. Best is trial 284 with value: 0.9498687991528469.
[I 2026-07-13 11:29:28,559] Trial 499 finished with value: 0.9491940325197118 and parameters: {'weight_class_0': 0.7932167350470872, 'weight_class_1': 5.966117944940486, 'weight_class_2': 8.332633506157231}. Best is trial 284 with value: 0.9498687991528469.

Best trial score:
0.9498687991528469

Best params:
{'weight_class_0': 0.5759670083018597, 'weight_class_1': 8.885748477657396, 'weight_class_2': 5.804397054769949}

In [9]:
weights = np.array([study.best_params['weight_class_0'], study.best_params['weight_class_1'], study.best_params['weight_class_2']])
weighted_probas = X_test.loc[:, ['xgb_0', 'xgb_1', 'xgb_2']].to_numpy() * weights

pred = np.argmax(weighted_probas, axis=1)

In [10]:
sub_labels = label_encoder.inverse_transform(pred)

# Submission

In [11]:
submission = pd.read_csv('../data/submission/sample_submission.csv')
submission['health_condition'] = sub_labels

submission.to_csv('../data/submission/submission_from_5.1_xgboost_submission.csv', index=False)

In [12]:
submission.head()

       id health_condition
0  690088        unhealthy
1  690089        unhealthy
2  690090          at-risk
3  690091          at-risk
4  690092        unhealthy