# Imports

In [1]:
import optuna
import pickle

import numpy as np
import pandas as pd

from tqdm import tqdm

from sklearn.metrics import balanced_accuracy_score
from sklearn.model_selection import StratifiedKFold, cross_val_predict

/home/junior/Documentos/GitHub/kaggle-competition-predicting-student-health/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Utils

In [2]:
def load_pickle(file_path):
    with open(file_path, 'rb') as file:
        return pickle.load(file)

# Loading Datasets

In [3]:
X_train = pd.read_parquet('../data/processed/X_train_stacking_layer_one.parquet')
y_train = pd.read_parquet('../data/interim/y_train.parquet')

X_test = pd.read_parquet('../data/processed/X_test_stacking_layer_one.parquet')

In [4]:
X_train.head()

,lgbm_0,lgbm_1,lgbm_2,xgb_0,xgb_1,xgb_2,cat_0,cat_1,cat_2
0,0.004831,0.002142,0.993027,0.005220,0.002128,0.992652,0.005655,0.000463,0.993882
1,0.998229,0.000143,0.001628,0.997774,0.000322,0.001904,0.994638,0.000368,0.004994
2,0.003982,0.000584,0.995434,0.002362,0.000710,0.996928,0.002327,0.000919,0.996754
3,0.007424,0.001954,0.990622,0.002922,0.003628,0.993450,0.003433,0.002374,0.994194
4,0.993583,0.000012,0.006405,0.997151,0.000013,0.002836,0.994112,0.000005,0.005883

In [5]:
X_test.head()

,lgbm_0,lgbm_1,lgbm_2,xgb_0,xgb_1,xgb_2,cat_0,cat_1,cat_2
0,0.011986,0.002516,0.985498,0.009749,0.003956,0.986295,0.008185,0.005526,0.986288
1,0.469590,0.002922,0.527488,0.344531,0.002104,0.653365,0.530403,0.002094,0.467503
2,0.998492,0.000991,0.000517,0.998555,0.001132,0.000313,0.996306,0.003216,0.000478
3,0.986619,0.000009,0.013372,0.978274,0.000024,0.021702,0.990683,0.000093,0.009224
4,0.008520,0.001975,0.989505,0.005601,0.002080,0.992319,0.003507,0.001947,0.994546

# Machine Learning

In [6]:
label_encoder = load_pickle('../artifacts/label_encoder.pkl')

In [7]:
cols_use = ['cat_0', 'cat_1', 'cat_2']

In [8]:
def objective(trial, X, y):

    w0 = trial.suggest_float('weight_class_0', 0.0, 10.0, log=False)
    w1 = trial.suggest_float('weight_class_1', 0.0, 10.0, log=False)
    w2 = trial.suggest_float('weight_class_2', 0.0, 10.0, log=False)
    weights = np.array([w0, w1, w2])

    proba = X.loc[:, cols_use].to_numpy()
    
    weighted_probas = proba * weights
    pred = np.argmax(weighted_probas, axis=1)
    
    score = balanced_accuracy_score(y, pred)

    return score


study = optuna.create_study(
    direction="maximize", 
    sampler=optuna.samplers.TPESampler(seed=42), 
    pruner=optuna.pruners.MedianPruner(n_warmup_steps=2)
)

study.optimize(
    lambda trial: objective(trial, X_train, y_train.health_condition), 
    n_trials=2000, 
    n_jobs=-1, 
    show_progress_bar=True
)

print("\nBest trial score:")
print(study.best_trial.value)

print("\nBest params:")
print(study.best_trial.params)

[I 2026-07-08 13:32:35,717] A new study created in memory with name: no-name-bc2e9180-4698-4d31-8cb7-031ce4286e80

[I 2026-07-08 13:32:35,876] Trial 7 finished with value: 0.9128511430403047 and parameters: {'weight_class_0': 4.300377413443663, 'weight_class_1': 8.766256680198415, 'weight_class_2': 6.772197382686124}. Best is trial 7 with value: 0.9128511430403047.
[I 2026-07-08 13:32:35,883] Trial 11 finished with value: 0.949077759307233 and parameters: {'weight_class_0': 0.5903968610470989, 'weight_class_1': 9.572000138935445, 'weight_class_2': 8.88297755793739}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:35,887] Trial 8 finished with value: 0.8530178058835266 and parameters: {'weight_class_0': 7.666224939193928, 'weight_class_1': 4.4402309306423415, 'weight_class_2': 3.9413886943357523}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:35,893] Trial 5 finished with value: 0.8670943688371734 and parameters: {'weight_class_0': 7.46563800755879, 'weight_class_1': 3.6848184965121913, 'weight_class_2': 8.370166635898837}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:35,895] Trial 0 finished with value: 0.8694426903328725 and parameters: {'weight_class_0': 7.934518861524042, 'weight_class_1': 3.934518966743746, 'weight_class_2': 9.47907569801387}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:35,897] Trial 4 finished with value: 0.8762834868239122 and parameters: {'weight_class_0': 8.698110788072245, 'weight_class_1': 8.329583043945131, 'weight_class_2': 8.570587100099674}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:35,900] Trial 3 finished with value: 0.8825694667099956 and parameters: {'weight_class_0': 5.355915281361384, 'weight_class_1': 9.913901244195134, 'weight_class_2': 3.012340314883888}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:35,901] Trial 1 finished with value: 0.8639799475853769 and parameters: {'weight_class_0': 8.022447204840708, 'weight_class_1': 2.954490276799161, 'weight_class_2': 9.470830740772003}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:35,904] Trial 10 finished with value: 0.8669500006497491 and parameters: {'weight_class_0': 8.258746252970132, 'weight_class_1': 9.184544803348789, 'weight_class_2': 4.158343785073754}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:35,906] Trial 2 finished with value: 0.948134013178322 and parameters: {'weight_class_0': 0.47677852535965237, 'weight_class_1': 8.67096619851253, 'weight_class_2': 2.7670171330973767}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:35,931] Trial 9 finished with value: 0.9487507641714022 and parameters: {'weight_class_0': 0.41162147819709505, 'weight_class_1': 9.975401099532245, 'weight_class_2': 7.068728824132499}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:35,932] Trial 6 finished with value: 0.8942173891569357 and parameters: {'weight_class_0': 1.2368556934443187, 'weight_class_1': 6.741212240204807, 'weight_class_2': 0.49185842156264425}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,032] Trial 12 finished with value: 0.9302565927285539 and parameters: {'weight_class_0': 0.31205661436263704, 'weight_class_1': 0.5952409370593603, 'weight_class_2': 1.1670322431986753}. Best is trial 11 with value: 0.949077759307233.

Best trial: 11. Best value: 0.949078:   1%|█▋                                                                                                                                    | 25/2000 [00:00<00:42, 46.78it/s]

[I 2026-07-08 13:32:36,041] Trial 13 finished with value: 0.8980058994336458 and parameters: {'weight_class_0': 0.28180424509909513, 'weight_class_1': 0.15013756803684242, 'weight_class_2': 0.9444942828120428}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,062] Trial 14 finished with value: 0.9468625322622404 and parameters: {'weight_class_0': 0.013955393758803503, 'weight_class_1': 0.407796354541496, 'weight_class_2': 0.6474532016269485}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,065] Trial 15 finished with value: 0.8642786951452398 and parameters: {'weight_class_0': 2.3585565616202473, 'weight_class_1': 0.08419346849631903, 'weight_class_2': 6.390241314366317}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,089] Trial 16 finished with value: 0.9354915631332666 and parameters: {'weight_class_0': 2.200849976841212, 'weight_class_1': 6.564899077760393, 'weight_class_2': 6.2692018389356665}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,098] Trial 17 finished with value: 0.8881041371783915 and parameters: {'weight_class_0': 2.1266374277674154, 'weight_class_1': 0.6829578235909075, 'weight_class_2': 6.51171535394589}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,119] Trial 18 finished with value: 0.9402641183921511 and parameters: {'weight_class_0': 1.878915592535483, 'weight_class_1': 6.740726152355746, 'weight_class_2': 6.35307667679212}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,144] Trial 19 finished with value: 0.9349471255161798 and parameters: {'weight_class_0': 2.275246637594466, 'weight_class_1': 6.821303351872688, 'weight_class_2': 6.259982029380673}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,154] Trial 20 finished with value: 0.9391395119760458 and parameters: {'weight_class_0': 1.9933309638360437, 'weight_class_1': 6.613478984270856, 'weight_class_2': 6.646277485713617}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,179] Trial 21 finished with value: 0.9365446733629589 and parameters: {'weight_class_0': 2.255011396858266, 'weight_class_1': 7.102634858303897, 'weight_class_2': 6.538337533113024}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,213] Trial 22 finished with value: 0.9335796634712036 and parameters: {'weight_class_0': 2.558366962882112, 'weight_class_1': 7.106923394600042, 'weight_class_2': 6.9071749577949735}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,216] Trial 23 finished with value: 0.9316912054152829 and parameters: {'weight_class_0': 2.6085398259809125, 'weight_class_1': 6.491454658455315, 'weight_class_2': 6.99796973572351}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,226] Trial 24 finished with value: 0.9198158931123244 and parameters: {'weight_class_0': 3.732822153463318, 'weight_class_1': 7.366526654386252, 'weight_class_2': 7.479712140232865}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,249] Trial 25 finished with value: 0.9214136467051928 and parameters: {'weight_class_0': 3.9183811859167683, 'weight_class_1': 7.900474335994733, 'weight_class_2': 8.139442299066213}. Best is trial 11 with value: 0.949077759307233.

[I 2026-07-08 13:32:36,268] Trial 26 finished with value: 0.9242677313581954 and parameters: {'weight_class_0': 3.608016405949927, 'weight_class_1': 7.696715044355569, 'weight_class_2': 7.877402503139606}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,280] Trial 27 finished with value: 0.9266698395224485 and parameters: {'weight_class_0': 3.776085551326833, 'weight_class_1': 9.919652247268935, 'weight_class_2': 7.775091531249599}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,302] Trial 28 finished with value: 0.9252898529988594 and parameters: {'weight_class_0': 3.593038947276659, 'weight_class_1': 7.888389707942375, 'weight_class_2': 7.954100785421646}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,315] Trial 29 finished with value: 0.928261361415213 and parameters: {'weight_class_0': 3.7085289017791725, 'weight_class_1': 9.863447602176318, 'weight_class_2': 7.998990130682921}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,335] Trial 30 finished with value: 0.9287217895428407 and parameters: {'weight_class_0': 3.621806467075804, 'weight_class_1': 9.910526965897658, 'weight_class_2': 7.816532800449368}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,369] Trial 32 finished with value: 0.9476631477564138 and parameters: {'weight_class_0': 0.9476605948079467, 'weight_class_1': 9.943364618073186, 'weight_class_2': 5.05999595663206}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,375] Trial 31 finished with value: 0.9472897503125304 and parameters: {'weight_class_0': 1.0297016488046395, 'weight_class_1': 9.888414733963417, 'weight_class_2': 5.085698166544546}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,387] Trial 33 finished with value: 0.9479463418622296 and parameters: {'weight_class_0': 0.9615955959418105, 'weight_class_1': 9.858301066940207, 'weight_class_2': 5.429922072003734}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,422] Trial 34 finished with value: 0.9474676951782346 and parameters: {'weight_class_0': 0.9884790887285662, 'weight_class_1': 9.731366394839787, 'weight_class_2': 5.014807860300206}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,440] Trial 35 finished with value: 0.9476818222224702 and parameters: {'weight_class_0': 0.9914788174950104, 'weight_class_1': 9.154645666638883, 'weight_class_2': 5.359518820996045}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,454] Trial 37 finished with value: 0.9476410562473968 and parameters: {'weight_class_0': 1.0035074286905474, 'weight_class_1': 9.12598182766074, 'weight_class_2': 5.371057866806008}. Best is trial 11 with value: 0.949077759307233.

Best trial: 11. Best value: 0.949078:   2%|███▎                                                                                                                                  | 49/2000 [00:01<00:34, 56.96it/s]

[I 2026-07-08 13:32:36,456] Trial 36 finished with value: 0.9487824287083324 and parameters: {'weight_class_0': 1.063781474639122, 'weight_class_1': 9.129254177636161, 'weight_class_2': 9.767242813869917}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,477] Trial 38 finished with value: 0.9289830225111922 and parameters: {'weight_class_0': 0.9655964098513733, 'weight_class_1': 5.708373441183902, 'weight_class_2': 1.712080595097687}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,484] Trial 39 finished with value: 0.9305119183604503 and parameters: {'weight_class_0': 1.0021853093539859, 'weight_class_1': 9.077849631682906, 'weight_class_2': 1.8026346584285453}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,511] Trial 40 finished with value: 0.948863223335883 and parameters: {'weight_class_0': 1.0090103043200234, 'weight_class_1': 8.957614871897666, 'weight_class_2': 9.826209374397576}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,524] Trial 41 finished with value: 0.9476407617975425 and parameters: {'weight_class_0': 1.4164409812827217, 'weight_class_1': 9.012247961776886, 'weight_class_2': 9.906123042296752}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,544] Trial 42 finished with value: 0.9479490418890513 and parameters: {'weight_class_0': 1.3075560649423263, 'weight_class_1': 9.097877395064979, 'weight_class_2': 9.36671662907446}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,563] Trial 43 finished with value: 0.947413387281515 and parameters: {'weight_class_0': 1.4756486925030559, 'weight_class_1': 9.002231043934046, 'weight_class_2': 9.763093581060588}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,588] Trial 45 finished with value: 0.9469466717662778 and parameters: {'weight_class_0': 1.5360627280514867, 'weight_class_1': 8.523546182621551, 'weight_class_2': 9.857244297157788}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,606] Trial 44 finished with value: 0.8743528093480322 and parameters: {'weight_class_0': 9.72339831119535, 'weight_class_1': 8.386582874560341, 'weight_class_2': 9.773374739954306}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,621] Trial 46 finished with value: 0.9472185192482913 and parameters: {'weight_class_0': 1.4772189524891575, 'weight_class_1': 8.512654174343428, 'weight_class_2': 9.777125714606445}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,636] Trial 47 finished with value: 0.9011395419146065 and parameters: {'weight_class_0': 6.322896269701984, 'weight_class_1': 8.453907462734394, 'weight_class_2': 9.899741302639955}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,650] Trial 48 finished with value: 0.9467495651678721 and parameters: {'weight_class_0': 1.5852233637954896, 'weight_class_1': 8.483211775855642, 'weight_class_2': 9.908910449090195}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,686] Trial 49 finished with value: 0.9485202415169138 and parameters: {'weight_class_0': 0.4032530622970715, 'weight_class_1': 8.4655992750618, 'weight_class_2': 8.965845238244434}. Best is trial 11 with value: 0.949077759307233.

Best trial: 11. Best value: 0.949078:   3%|████                                                                                                                                  | 61/2000 [00:01<00:36, 53.63it/s]

[I 2026-07-08 13:32:36,697] Trial 50 finished with value: 0.9485783253976994 and parameters: {'weight_class_0': 0.40545370590826424, 'weight_class_1': 8.321354990583771, 'weight_class_2': 8.781440814294857}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,718] Trial 52 finished with value: 0.9481704274749289 and parameters: {'weight_class_0': 0.34408777561884557, 'weight_class_1': 8.237296101968942, 'weight_class_2': 8.951084825929838}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,721] Trial 51 finished with value: 0.9485863110126002 and parameters: {'weight_class_0': 0.4149362378121979, 'weight_class_1': 8.398687955629043, 'weight_class_2': 9.098550702721788}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,735] Trial 53 finished with value: 0.9487359172153805 and parameters: {'weight_class_0': 0.4356978730137613, 'weight_class_1': 8.162340380323172, 'weight_class_2': 8.859758822603355}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,769] Trial 54 finished with value: 0.9483008728624639 and parameters: {'weight_class_0': 0.3656057322359216, 'weight_class_1': 8.182787446382992, 'weight_class_2': 9.034468645473511}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,784] Trial 55 finished with value: 0.9451868302099132 and parameters: {'weight_class_0': 0.17606730933412784, 'weight_class_1': 9.468821812262442, 'weight_class_2': 9.07126746268999}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,789] Trial 56 finished with value: 0.948533152048009 and parameters: {'weight_class_0': 0.4172468185267426, 'weight_class_1': 9.436141314998578, 'weight_class_2': 8.8869169086546}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,830] Trial 57 finished with value: 0.9484727078522215 and parameters: {'weight_class_0': 0.4081902247521487, 'weight_class_1': 9.478377737158553, 'weight_class_2': 8.848107222329919}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,845] Trial 58 finished with value: 0.9489149116798403 and parameters: {'weight_class_0': 0.5240582681188464, 'weight_class_1': 9.501959073511399, 'weight_class_2': 8.93475433652807}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,860] Trial 59 finished with value: 0.9490235948891801 and parameters: {'weight_class_0': 0.5658119167792589, 'weight_class_1': 9.452553072700537, 'weight_class_2': 8.753117209848655}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,873] Trial 60 finished with value: 0.9364495320940199 and parameters: {'weight_class_0': 2.9852966426774747, 'weight_class_1': 9.380130225581407, 'weight_class_2': 8.639076203261194}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,882] Trial 61 finished with value: 0.9489112535194463 and parameters: {'weight_class_0': 0.5563042797740897, 'weight_class_1': 9.349319989810425, 'weight_class_2': 9.366924855250183}. Best is trial 11 with value: 0.949077759307233.

Best trial: 75. Best value: 0.949111:   4%|████▉                                                                                                                                 | 73/2000 [00:01<00:34, 55.67it/s]

[I 2026-07-08 13:32:36,903] Trial 62 finished with value: 0.9379082056447303 and parameters: {'weight_class_0': 2.8277437890579655, 'weight_class_1': 9.413726090852082, 'weight_class_2': 8.603013772570241}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,931] Trial 63 finished with value: 0.9192093030433376 and parameters: {'weight_class_0': 0.05876101873863876, 'weight_class_1': 7.547650460175994, 'weight_class_2': 8.431280077168706}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,943] Trial 64 finished with value: 0.9355057940435549 and parameters: {'weight_class_0': 3.0460296865065115, 'weight_class_1': 9.472889123720245, 'weight_class_2': 8.404104245602161}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,967] Trial 65 finished with value: 0.8708466848455152 and parameters: {'weight_class_0': 0.0345749811341326, 'weight_class_1': 5.705369603422296, 'weight_class_2': 8.582881495016762}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:36,980] Trial 66 finished with value: 0.8942044486106638 and parameters: {'weight_class_0': 2.977882956418692, 'weight_class_1': 1.4706868156406143, 'weight_class_2': 8.476418520840209}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:37,011] Trial 67 finished with value: 0.936480469778712 and parameters: {'weight_class_0': 2.8781216259707114, 'weight_class_1': 8.80307391058647, 'weight_class_2': 8.49194493846642}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:37,024] Trial 68 finished with value: 0.9450227520845429 and parameters: {'weight_class_0': 1.9292177119592535, 'weight_class_1': 8.842060510453766, 'weight_class_2': 9.351048617401899}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:37,039] Trial 69 finished with value: 0.9453259022666561 and parameters: {'weight_class_0': 1.7915487407447217, 'weight_class_1': 8.884184074862954, 'weight_class_2': 8.411278628838083}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:37,056] Trial 70 finished with value: 0.9445264249359724 and parameters: {'weight_class_0': 1.9063993553550156, 'weight_class_1': 8.893803097592079, 'weight_class_2': 8.382645241024942}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:37,083] Trial 71 finished with value: 0.945405335232599 and parameters: {'weight_class_0': 1.863135370523734, 'weight_class_1': 8.77822955315866, 'weight_class_2': 9.443290441692715}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:37,099] Trial 73 finished with value: 0.9453699410705542 and parameters: {'weight_class_0': 1.862007480920398, 'weight_class_1': 8.771734270714706, 'weight_class_2': 9.382628406045749}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:37,104] Trial 72 finished with value: 0.9441632386290354 and parameters: {'weight_class_0': 1.8328341674906474, 'weight_class_1': 8.976371878809383, 'weight_class_2': 7.32232917654183}. Best is trial 11 with value: 0.949077759307233.

[I 2026-07-08 13:32:37,122] Trial 74 finished with value: 0.9435427860995147 and parameters: {'weight_class_0': 1.8937586445268983, 'weight_class_1': 8.72690080490508, 'weight_class_2': 7.27536857669712}. Best is trial 11 with value: 0.949077759307233.
[I 2026-07-08 13:32:37,144] Trial 75 finished with value: 0.9491106486443157 and parameters: {'weight_class_0': 0.705795648081161, 'weight_class_1': 8.7605705852644, 'weight_class_2': 9.46784736125466}. Best is trial 75 with value: 0.9491106486443157.
[I 2026-07-08 13:32:37,155] Trial 76 finished with value: 0.9440324380251476 and parameters: {'weight_class_0': 1.885726095911211, 'weight_class_1': 9.591338237618308, 'weight_class_2': 7.256946033775485}. Best is trial 75 with value: 0.9491106486443157.
[I 2026-07-08 13:32:37,173] Trial 77 finished with value: 0.9490727304357373 and parameters: {'weight_class_0': 0.7869715360755063, 'weight_class_1': 9.671397921766985, 'weight_class_2': 7.553268782884485}. Best is trial 75 with value: 0.9491106486443157.
[I 2026-07-08 13:32:37,206] Trial 78 finished with value: 0.9490203348848665 and parameters: {'weight_class_0': 0.7289884601330465, 'weight_class_1': 7.942195613436263, 'weight_class_2': 7.325322533552617}. Best is trial 75 with value: 0.9491106486443157.
[I 2026-07-08 13:32:37,223] Trial 79 finished with value: 0.9491912061070499 and parameters: {'weight_class_0': 0.6554624945513838, 'weight_class_1': 7.994560964004775, 'weight_class_2': 7.31981721458762}. Best is trial 79 with value: 0.9491912061070499.
[I 2026-07-08 13:32:37,225] Trial 80 finished with value: 0.9491358507153769 and parameters: {'weight_class_0': 0.7086349951886196, 'weight_class_1': 9.666080391756692, 'weight_class_2': 7.114088820696675}. Best is trial 79 with value: 0.9491912061070499.
[I 2026-07-08 13:32:37,238] Trial 81 finished with value: 0.9491901670838448 and parameters: {'weight_class_0': 0.6707669127932072, 'weight_class_1': 7.970397086947825, 'weight_class_2': 7.397751392589027}. Best is trial 79 with value: 0.9491912061070499.
[I 2026-07-08 13:32:37,272] Trial 82 finished with value: 0.9490635491778847 and parameters: {'weight_class_0': 0.7407660646120269, 'weight_class_1': 7.921840952443222, 'weight_class_2': 8.170790427699785}. Best is trial 79 with value: 0.9491912061070499.
[I 2026-07-08 13:32:37,277] Trial 83 finished with value: 0.9490331542543159 and parameters: {'weight_class_0': 0.6579017736158561, 'weight_class_1': 9.685650763013033, 'weight_class_2': 5.955960279642068}. Best is trial 79 with value: 0.9491912061070499.
[I 2026-07-08 13:32:37,312] Trial 84 finished with value: 0.9490949377299119 and parameters: {'weight_class_0': 0.6992900077427125, 'weight_class_1': 9.726163017717871, 'weight_class_2': 9.575755013053575}. Best is trial 79 with value: 0.9491912061070499.
[I 2026-07-08 13:32:37,316] Trial 85 finished with value: 0.9491067125714193 and parameters: {'weight_class_0': 0.691061136200229, 'weight_class_1': 7.944398704889343, 'weight_class_2': 8.131700774282113}. Best is trial 79 with value: 0.9491912061070499.

Best trial: 87. Best value: 0.949194:   5%|██████▍                                                                                                                               | 97/2000 [00:01<00:33, 56.55it/s]

[I 2026-07-08 13:32:37,330] Trial 86 finished with value: 0.9489981443528573 and parameters: {'weight_class_0': 0.8347735888661889, 'weight_class_1': 7.9611287215279365, 'weight_class_2': 9.573479722960087}. Best is trial 79 with value: 0.9491912061070499.
[I 2026-07-08 13:32:37,350] Trial 87 finished with value: 0.9491939983380412 and parameters: {'weight_class_0': 0.7230317126755897, 'weight_class_1': 9.608067675527167, 'weight_class_2': 7.671457732564356}. Best is trial 87 with value: 0.9491939983380412.
[I 2026-07-08 13:32:37,368] Trial 88 finished with value: 0.948877148464551 and parameters: {'weight_class_0': 0.865408893347957, 'weight_class_1': 8.034923996885729, 'weight_class_2': 7.666010574734013}. Best is trial 87 with value: 0.9491939983380412.
[I 2026-07-08 13:32:37,397] Trial 89 finished with value: 0.9491395897084849 and parameters: {'weight_class_0': 0.6948175848519355, 'weight_class_1': 7.790455318162787, 'weight_class_2': 7.652854547681036}. Best is trial 87 with value: 0.9491939983380412.
[I 2026-07-08 13:32:37,423] Trial 91 finished with value: 0.948887259702075 and parameters: {'weight_class_0': 0.7254116395985628, 'weight_class_1': 7.201963430282208, 'weight_class_2': 6.060497859887832}. Best is trial 87 with value: 0.9491939983380412.
[I 2026-07-08 13:32:37,425] Trial 90 finished with value: 0.949125279088532 and parameters: {'weight_class_0': 0.6975706536556473, 'weight_class_1': 7.854235874863464, 'weight_class_2': 7.6616169231070375}. Best is trial 87 with value: 0.9491939983380412.
[I 2026-07-08 13:32:37,443] Trial 92 finished with value: 0.9485153115192698 and parameters: {'weight_class_0': 0.7976968797198218, 'weight_class_1': 7.35824251851378, 'weight_class_2': 5.826281166548673}. Best is trial 87 with value: 0.9491939983380412.
[I 2026-07-08 13:32:37,457] Trial 93 finished with value: 0.9486533105362315 and parameters: {'weight_class_0': 0.7615720164974523, 'weight_class_1': 7.3530940252556185, 'weight_class_2': 5.904061398389386}. Best is trial 87 with value: 0.9491939983380412.
[I 2026-07-08 13:32:37,474] Trial 94 finished with value: 0.946338064961913 and parameters: {'weight_class_0': 1.2773534382866796, 'weight_class_1': 7.116310845829772, 'weight_class_2': 6.78883437397664}. Best is trial 87 with value: 0.9491939983380412.
[I 2026-07-08 13:32:37,491] Trial 95 finished with value: 0.9473980700565917 and parameters: {'weight_class_0': 1.204450976990862, 'weight_class_1': 7.588903337120376, 'weight_class_2': 7.6743387333879545}. Best is trial 87 with value: 0.9491939983380412.
[I 2026-07-08 13:32:37,514] Trial 96 finished with value: 0.9467923884002363 and parameters: {'weight_class_0': 1.295984660349366, 'weight_class_1': 7.406619608408905, 'weight_class_2': 7.633583028510292}. Best is trial 87 with value: 0.9491939983380412.
[I 2026-07-08 13:32:37,531] Trial 98 finished with value: 0.9463747168099843 and parameters: {'weight_class_0': 1.195379262937586, 'weight_class_1': 7.159372090124984, 'weight_class_2': 6.0455365506749565}. Best is trial 87 with value: 0.9491939983380412.

Best trial: 87. Best value: 0.949194:   5%|███████▏                                                                                                                             | 109/2000 [00:02<00:32, 57.45it/s]

[I 2026-07-08 13:32:37,534] Trial 97 finished with value: 0.9461909429339452 and parameters: {'weight_class_0': 1.329688961992312, 'weight_class_1': 7.40480159972847, 'weight_class_2': 6.823121241702529}. Best is trial 87 with value: 0.9491939983380412.
[I 2026-07-08 13:32:37,562] Trial 99 finished with value: 0.9468147220184798 and parameters: {'weight_class_0': 1.2430890918537556, 'weight_class_1': 7.612601243252228, 'weight_class_2': 6.7840855212873805}. Best is trial 87 with value: 0.9491939983380412.
[I 2026-07-08 13:32:37,577] Trial 100 finished with value: 0.946850984458823 and parameters: {'weight_class_0': 1.237723806105227, 'weight_class_1': 7.730137377820042, 'weight_class_2': 6.703791853588108}. Best is trial 87 with value: 0.9491939983380412.
[I 2026-07-08 13:32:37,597] Trial 101 finished with value: 0.9468756410086785 and parameters: {'weight_class_0': 1.2404431720296196, 'weight_class_1': 7.641680507111178, 'weight_class_2': 6.79477913174816}. Best is trial 87 with value: 0.9491939983380412.
[I 2026-07-08 13:32:37,625] Trial 102 finished with value: 0.9473046698649066 and parameters: {'weight_class_0': 1.1771550199738001, 'weight_class_1': 7.586275195430168, 'weight_class_2': 7.039202130298782}. Best is trial 87 with value: 0.9491939983380412.
[I 2026-07-08 13:32:37,645] Trial 104 finished with value: 0.9477500940229976 and parameters: {'weight_class_0': 1.190306221566113, 'weight_class_1': 9.197962164773974, 'weight_class_2': 6.988817009856555}. Best is trial 87 with value: 0.9491939983380412.
[I 2026-07-08 13:32:37,656] Trial 103 finished with value: 0.9442111267238804 and parameters: {'weight_class_0': 1.5831181995704935, 'weight_class_1': 6.850268088332441, 'weight_class_2': 7.038060958469703}. Best is trial 87 with value: 0.9491939983380412.
[I 2026-07-08 13:32:37,669] Trial 105 finished with value: 0.6686396786032982 and parameters: {'weight_class_0': 0.010262024742863307, 'weight_class_1': 9.234345244462412, 'weight_class_2': 6.964641318069717}. Best is trial 87 with value: 0.9491939983380412.
[I 2026-07-08 13:32:37,681] Trial 106 finished with value: 0.9458196712160083 and parameters: {'weight_class_0': 0.1639179711290355, 'weight_class_1': 7.697078953076851, 'weight_class_2': 8.132087870588167}. Best is trial 87 with value: 0.9491939983380412.
[I 2026-07-08 13:32:37,720] Trial 107 finished with value: 0.9460735337804685 and parameters: {'weight_class_0': 0.17254907481216047, 'weight_class_1': 7.707734114800736, 'weight_class_2': 8.12788151023049}. Best is trial 87 with value: 0.9491939983380412.
[I 2026-07-08 13:32:37,729] Trial 108 finished with value: 0.9460705260217516 and parameters: {'weight_class_0': 0.19194563023161915, 'weight_class_1': 9.18948576528961, 'weight_class_2': 7.992139112062912}. Best is trial 87 with value: 0.9491939983380412.
[I 2026-07-08 13:32:37,747] Trial 110 finished with value: 0.9470197483007884 and parameters: {'weight_class_0': 0.19230065222445547, 'weight_class_1': 6.259485120704809, 'weight_class_2': 8.138621365899567}. Best is trial 87 with value: 0.9491939983380412.

Best trial: 87. Best value: 0.949194:   6%|████████                                                                                                                             | 121/2000 [00:02<00:32, 57.17it/s]

[I 2026-07-08 13:32:37,750] Trial 109 finished with value: 0.9467296633081399 and parameters: {'weight_class_0': 1.5583288795819006, 'weight_class_1': 9.727013328831717, 'weight_class_2': 8.101524828815103}. Best is trial 87 with value: 0.9491939983380412.
[I 2026-07-08 13:32:37,764] Trial 111 finished with value: 0.9473305662884468 and parameters: {'weight_class_0': 0.21818442243735242, 'weight_class_1': 6.898674420937871, 'weight_class_2': 7.997250971579001}. Best is trial 87 with value: 0.9491939983380412.
[I 2026-07-08 13:32:37,803] Trial 112 finished with value: 0.9473124089889544 and parameters: {'weight_class_0': 0.21009915289294812, 'weight_class_1': 6.2393274940197205, 'weight_class_2': 8.128414606487878}. Best is trial 87 with value: 0.9491939983380412.
[I 2026-07-08 13:32:37,811] Trial 113 finished with value: 0.9475873217646686 and parameters: {'weight_class_0': 0.2852110182134028, 'weight_class_1': 9.808154297301831, 'weight_class_2': 8.059967667559018}. Best is trial 87 with value: 0.9491939983380412.
[I 2026-07-08 13:32:37,819] Trial 114 finished with value: 0.9473653980232983 and parameters: {'weight_class_0': 0.20597962345017612, 'weight_class_1': 6.349377777665133, 'weight_class_2': 7.502584754649999}. Best is trial 87 with value: 0.9491939983380412.
[I 2026-07-08 13:32:37,846] Trial 115 finished with value: 0.9470769662854829 and parameters: {'weight_class_0': 0.24650226074406928, 'weight_class_1': 9.760501906627367, 'weight_class_2': 7.984225192552562}. Best is trial 87 with value: 0.9491939983380412.
[I 2026-07-08 13:32:37,853] Trial 116 finished with value: 0.9476713167177812 and parameters: {'weight_class_0': 0.289474505069949, 'weight_class_1': 9.7079154135461, 'weight_class_2': 8.002273186573358}. Best is trial 87 with value: 0.9491939983380412.
[I 2026-07-08 13:32:37,873] Trial 117 finished with value: 0.9491546895963682 and parameters: {'weight_class_0': 0.5856028321041801, 'weight_class_1': 9.752516927704674, 'weight_class_2': 7.489392537814915}. Best is trial 87 with value: 0.9491939983380412.
[I 2026-07-08 13:32:37,891] Trial 118 finished with value: 0.9491834690471755 and parameters: {'weight_class_0': 0.6113491023542852, 'weight_class_1': 8.12781664985011, 'weight_class_2': 7.508711361117906}. Best is trial 87 with value: 0.9491939983380412.
[I 2026-07-08 13:32:37,922] Trial 119 finished with value: 0.9491723511018844 and parameters: {'weight_class_0': 0.5996247305089404, 'weight_class_1': 8.127734463414678, 'weight_class_2': 7.60231013960718}. Best is trial 87 with value: 0.9491939983380412.
[I 2026-07-08 13:32:37,923] Trial 120 finished with value: 0.9491767129818193 and parameters: {'weight_class_0': 0.65550845141761, 'weight_class_1': 8.147918005993171, 'weight_class_2': 7.542748744978625}. Best is trial 87 with value: 0.9491939983380412.
[I 2026-07-08 13:32:37,956] Trial 121 finished with value: 0.9491521334607359 and parameters: {'weight_class_0': 0.628130643395918, 'weight_class_1': 9.990766379099554, 'weight_class_2': 7.507143984284971}. Best is trial 87 with value: 0.9491939983380412.

[I 2026-07-08 13:32:37,968] Trial 122 finished with value: 0.9491512905332394 and parameters: {'weight_class_0': 0.6401738305887805, 'weight_class_1': 8.146321697487004, 'weight_class_2': 7.463079951192676}. Best is trial 87 with value: 0.9491939983380412.
[I 2026-07-08 13:32:37,986] Trial 123 finished with value: 0.949175747486982 and parameters: {'weight_class_0': 0.6163397010718052, 'weight_class_1': 9.997011419146245, 'weight_class_2': 7.4736570400318145}. Best is trial 87 with value: 0.9491939983380412.
[I 2026-07-08 13:32:38,008] Trial 124 finished with value: 0.9491714882616993 and parameters: {'weight_class_0': 0.5945526923497709, 'weight_class_1': 8.290114039118686, 'weight_class_2': 7.486552678786329}. Best is trial 87 with value: 0.9491939983380412.
[I 2026-07-08 13:32:38,018] Trial 125 finished with value: 0.949154206644787 and parameters: {'weight_class_0': 0.572358956689536, 'weight_class_1': 8.166140505128427, 'weight_class_2': 7.611860751640584}. Best is trial 87 with value: 0.9491939983380412.
[I 2026-07-08 13:32:38,025] Trial 126 finished with value: 0.9491367816047908 and parameters: {'weight_class_0': 0.5637182189995245, 'weight_class_1': 9.99500212033623, 'weight_class_2': 7.194981403826711}. Best is trial 87 with value: 0.9491939983380412.
[I 2026-07-08 13:32:38,062] Trial 127 finished with value: 0.9491612460733253 and parameters: {'weight_class_0': 0.5565519614385186, 'weight_class_1': 9.991811037016745, 'weight_class_2': 6.54219631069348}. Best is trial 87 with value: 0.9491939983380412.
[I 2026-07-08 13:32:38,077] Trial 128 finished with value: 0.9492193587025205 and parameters: {'weight_class_0': 0.5765030135683549, 'weight_class_1': 8.15138571241525, 'weight_class_2': 6.458512772080344}. Best is trial 128 with value: 0.9492193587025205.
[I 2026-07-08 13:32:38,087] Trial 129 finished with value: 0.949166952753233 and parameters: {'weight_class_0': 0.543661311711704, 'weight_class_1': 8.103062460751497, 'weight_class_2': 6.51259991520281}. Best is trial 128 with value: 0.9492193587025205.
[I 2026-07-08 13:32:38,108] Trial 130 finished with value: 0.9492053179122374 and parameters: {'weight_class_0': 0.5671607780501613, 'weight_class_1': 8.224580994456547, 'weight_class_2': 6.4907816908227165}. Best is trial 128 with value: 0.9492193587025205.
[I 2026-07-08 13:32:38,116] Trial 131 finished with value: 0.9491652089284631 and parameters: {'weight_class_0': 0.5529028893969958, 'weight_class_1': 8.67806711368583, 'weight_class_2': 6.455452860399491}. Best is trial 128 with value: 0.9492193587025205.
[I 2026-07-08 13:32:38,134] Trial 132 finished with value: 0.9490932627767439 and parameters: {'weight_class_0': 0.49947248535243194, 'weight_class_1': 8.181799854579968, 'weight_class_2': 7.402748312483662}. Best is trial 128 with value: 0.9492193587025205.

[I 2026-07-08 13:32:38,165] Trial 133 finished with value: 0.9482655885069504 and parameters: {'weight_class_0': 1.0568344291488496, 'weight_class_1': 8.637981457930369, 'weight_class_2': 7.445467718783802}. Best is trial 128 with value: 0.9492193587025205.
[I 2026-07-08 13:32:38,185] Trial 134 finished with value: 0.8933512970575564 and parameters: {'weight_class_0': 5.582942129722297, 'weight_class_1': 8.152048746478986, 'weight_class_2': 6.489865456299214}. Best is trial 128 with value: 0.9492193587025205.
[I 2026-07-08 13:32:38,187] Trial 135 finished with value: 0.9490669670562507 and parameters: {'weight_class_0': 0.4923712088115626, 'weight_class_1': 8.151557913266215, 'weight_class_2': 7.424541980784304}. Best is trial 128 with value: 0.9492193587025205.
[I 2026-07-08 13:32:38,222] Trial 136 finished with value: 0.9481053924426949 and parameters: {'weight_class_0': 1.0138247582066708, 'weight_class_1': 8.201630065480103, 'weight_class_2': 6.505661429250734}. Best is trial 128 with value: 0.9492193587025205.
[I 2026-07-08 13:32:38,234] Trial 137 finished with value: 0.9486576914036853 and parameters: {'weight_class_0': 0.9755418558750977, 'weight_class_1': 8.343884265543156, 'weight_class_2': 7.839143118513373}. Best is trial 128 with value: 0.9492193587025205.
[I 2026-07-08 13:32:38,251] Trial 138 finished with value: 0.9482860301462374 and parameters: {'weight_class_0': 0.9667516796590789, 'weight_class_1': 8.5998733127454, 'weight_class_2': 6.481794339029873}. Best is trial 128 with value: 0.9492193587025205.
[I 2026-07-08 13:32:38,296] Trial 139 finished with value: 0.9043066297637398 and parameters: {'weight_class_0': 4.8116007075949225, 'weight_class_1': 8.565567048661864, 'weight_class_2': 6.505951872636544}. Best is trial 128 with value: 0.9492193587025205.
[I 2026-07-08 13:32:38,302] Trial 140 finished with value: 0.94811440267571 and parameters: {'weight_class_0': 0.9903206276595569, 'weight_class_1': 8.60823985907301, 'weight_class_2': 6.260780691478702}. Best is trial 128 with value: 0.9492193587025205.
[I 2026-07-08 13:32:38,308] Trial 141 finished with value: 0.9480689167491839 and parameters: {'weight_class_0': 1.0264161871516317, 'weight_class_1': 8.405556544621497, 'weight_class_2': 6.449211925528938}. Best is trial 128 with value: 0.9492193587025205.
[I 2026-07-08 13:32:38,321] Trial 142 finished with value: 0.9483302468034998 and parameters: {'weight_class_0': 0.9567122948275948, 'weight_class_1': 8.528471716962896, 'weight_class_2': 6.484013060650716}. Best is trial 128 with value: 0.9492193587025205.
[I 2026-07-08 13:32:38,338] Trial 143 finished with value: 0.948172667630334 and parameters: {'weight_class_0': 0.9681669422743306, 'weight_class_1': 8.486348861030754, 'weight_class_2': 6.299816942358871}. Best is trial 128 with value: 0.9492193587025205.
[I 2026-07-08 13:32:38,355] Trial 144 finished with value: 0.9484177990306426 and parameters: {'weight_class_0': 0.926530999652871, 'weight_class_1': 8.575627772446385, 'weight_class_2': 6.426281955076948}. Best is trial 128 with value: 0.9492193587025205.

Best trial: 158. Best value: 0.949224:   8%|██████████▎                                                                                                                         | 156/2000 [00:02<00:31, 58.74it/s]

[I 2026-07-08 13:32:38,388] Trial 145 finished with value: 0.9483968362181182 and parameters: {'weight_class_0': 0.936477060418064, 'weight_class_1': 8.587021877532518, 'weight_class_2': 6.384897438868726}. Best is trial 128 with value: 0.9492193587025205.
[I 2026-07-08 13:32:38,396] Trial 146 finished with value: 0.9483989744442315 and parameters: {'weight_class_0': 0.9149491149471873, 'weight_class_1': 8.60082450908764, 'weight_class_2': 6.192584113626875}. Best is trial 128 with value: 0.9492193587025205.
[I 2026-07-08 13:32:38,400] Trial 147 finished with value: 0.949078142289907 and parameters: {'weight_class_0': 0.4283160457502928, 'weight_class_1': 8.56746043621885, 'weight_class_2': 6.34670316322949}. Best is trial 128 with value: 0.9492193587025205.
[I 2026-07-08 13:32:38,425] Trial 148 finished with value: 0.9491550758738532 and parameters: {'weight_class_0': 0.4302637434868949, 'weight_class_1': 8.490924358250126, 'weight_class_2': 5.605925525625486}. Best is trial 128 with value: 0.9492193587025205.
[I 2026-07-08 13:32:38,440] Trial 149 finished with value: 0.6574109698706292 and parameters: {'weight_class_0': 0.0004201807419124126, 'weight_class_1': 7.981769025818103, 'weight_class_2': 5.749520739605842}. Best is trial 128 with value: 0.9492193587025205.
[I 2026-07-08 13:32:38,446] Trial 150 finished with value: 0.9491369879599462 and parameters: {'weight_class_0': 0.4293152759202864, 'weight_class_1': 7.964993982729281, 'weight_class_2': 5.744570893667074}. Best is trial 128 with value: 0.9492193587025205.
[I 2026-07-08 13:32:38,478] Trial 151 finished with value: 0.949014782825691 and parameters: {'weight_class_0': 0.46740499364282795, 'weight_class_1': 7.996723548671603, 'weight_class_2': 7.178820184853208}. Best is trial 128 with value: 0.9492193587025205.
[I 2026-07-08 13:32:38,498] Trial 152 finished with value: 0.9491947021449513 and parameters: {'weight_class_0': 0.4297578309811776, 'weight_class_1': 8.048178888681255, 'weight_class_2': 5.533868959601875}. Best is trial 128 with value: 0.9492193587025205.
[I 2026-07-08 13:32:38,521] Trial 153 finished with value: 0.7544997416104732 and parameters: {'weight_class_0': 0.0107041067282867, 'weight_class_1': 2.5935743124271298, 'weight_class_2': 5.696826845729087}. Best is trial 128 with value: 0.9492193587025205.
[I 2026-07-08 13:32:38,534] Trial 154 finished with value: 0.9489611295936458 and parameters: {'weight_class_0': 0.4457452482736038, 'weight_class_1': 8.063147377839611, 'weight_class_2': 7.197673131189941}. Best is trial 128 with value: 0.9492193587025205.
[I 2026-07-08 13:32:38,557] Trial 155 finished with value: 0.9473590064500664 and parameters: {'weight_class_0': 0.48346996406897147, 'weight_class_1': 2.485844553397107, 'weight_class_2': 5.569954499024168}. Best is trial 128 with value: 0.9492193587025205.
[I 2026-07-08 13:32:38,569] Trial 156 finished with value: 0.733222697672086 and parameters: {'weight_class_0': 0.016925326893359238, 'weight_class_1': 8.050710415580342, 'weight_class_2': 5.759843494170736}. Best is trial 128 with value: 0.9492193587025205.

Best trial: 158. Best value: 0.949224:   8%|███████████                                                                                                                         | 167/2000 [00:03<00:32, 55.57it/s]

[I 2026-07-08 13:32:38,594] Trial 157 finished with value: 0.9490699667857267 and parameters: {'weight_class_0': 0.5036361249389177, 'weight_class_1': 8.35832176155913, 'weight_class_2': 4.67652122733463}. Best is trial 128 with value: 0.9492193587025205.
[I 2026-07-08 13:32:38,613] Trial 158 finished with value: 0.9492241819510037 and parameters: {'weight_class_0': 0.4956695705431603, 'weight_class_1': 8.252930092665308, 'weight_class_2': 5.557858960935659}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:38,634] Trial 159 finished with value: 0.9491056532369052 and parameters: {'weight_class_0': 0.46777178686788834, 'weight_class_1': 8.271438374943115, 'weight_class_2': 4.539104746020914}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:38,657] Trial 160 finished with value: 0.949070028014142 and parameters: {'weight_class_0': 0.5549744187357946, 'weight_class_1': 8.35348390010927, 'weight_class_2': 5.429408149892789}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:38,671] Trial 161 finished with value: 0.9491166808303578 and parameters: {'weight_class_0': 0.4906749554909929, 'weight_class_1': 8.333300405967984, 'weight_class_2': 4.698819714328055}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:38,675] Trial 162 finished with value: 0.9490482191284504 and parameters: {'weight_class_0': 0.39253114573366155, 'weight_class_1': 8.320493718944807, 'weight_class_2': 5.518316440569727}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:38,703] Trial 163 finished with value: 0.9490088198906511 and parameters: {'weight_class_0': 0.3746580702879366, 'weight_class_1': 8.265040876275304, 'weight_class_2': 3.714053516453313}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:38,729] Trial 165 finished with value: 0.8620585827619908 and parameters: {'weight_class_0': 8.903289605043163, 'weight_class_1': 8.330765152719119, 'weight_class_2': 4.258233449417373}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:38,737] Trial 164 finished with value: 0.8747514332184431 and parameters: {'weight_class_0': 7.013843977086631, 'weight_class_1': 8.341110999015278, 'weight_class_2': 5.316911121579403}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:38,750] Trial 166 finished with value: 0.9484160535070689 and parameters: {'weight_class_0': 0.7802220475631494, 'weight_class_1': 7.762205489278511, 'weight_class_2': 5.274330530909475}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:38,770] Trial 168 finished with value: 0.9435464433188456 and parameters: {'weight_class_0': 1.4301855741012985, 'weight_class_1': 7.79521881860391, 'weight_class_2': 5.019470125899311}. Best is trial 158 with value: 0.9492241819510037.

Best trial: 158. Best value: 0.949224:   9%|███████████▉                                                                                                                        | 180/2000 [00:03<00:32, 56.37it/s]

[I 2026-07-08 13:32:38,772] Trial 167 finished with value: 0.9479243580681033 and parameters: {'weight_class_0': 0.8277033936679674, 'weight_class_1': 8.334522529246248, 'weight_class_2': 4.669762763642108}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:38,790] Trial 169 finished with value: 0.9480679137807262 and parameters: {'weight_class_0': 0.8143843690497186, 'weight_class_1': 7.755973757571365, 'weight_class_2': 4.8487780110335645}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:38,822] Trial 170 finished with value: 0.9483798615753605 and parameters: {'weight_class_0': 0.7843019469838154, 'weight_class_1': 7.765076365769373, 'weight_class_2': 5.245476248921443}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:38,827] Trial 171 finished with value: 0.9489712611009878 and parameters: {'weight_class_0': 0.7783915927206722, 'weight_class_1': 7.843772757111902, 'weight_class_2': 7.790101286811898}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:38,853] Trial 172 finished with value: 0.9484610149940056 and parameters: {'weight_class_0': 0.7613830439168159, 'weight_class_1': 7.803802797280194, 'weight_class_2': 5.212232845300398}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:38,883] Trial 173 finished with value: 0.9484549417770198 and parameters: {'weight_class_0': 0.7567406681812081, 'weight_class_1': 7.767530230681322, 'weight_class_2': 5.163785180020517}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:38,898] Trial 174 finished with value: 0.9486987565707566 and parameters: {'weight_class_0': 0.7838524877820676, 'weight_class_1': 8.943952328697831, 'weight_class_2': 6.1112958901431815}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:38,902] Trial 175 finished with value: 0.9486953758214479 and parameters: {'weight_class_0': 0.692675266129372, 'weight_class_1': 8.857615434023161, 'weight_class_2': 5.112299500867414}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:38,926] Trial 176 finished with value: 0.9475538194787839 and parameters: {'weight_class_0': 0.24732243583836505, 'weight_class_1': 9.330852981863117, 'weight_class_2': 6.063029859254015}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:38,952] Trial 177 finished with value: 0.948069857849771 and parameters: {'weight_class_0': 0.2900938988823962, 'weight_class_1': 7.487018911115021, 'weight_class_2': 7.82126019806073}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:38,971] Trial 178 finished with value: 0.9491515501367741 and parameters: {'weight_class_0': 0.6676903216362209, 'weight_class_1': 8.073145704561872, 'weight_class_2': 7.737143022147511}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:38,983] Trial 179 finished with value: 0.9478118843503233 and parameters: {'weight_class_0': 0.2774057701908048, 'weight_class_1': 9.01190794237068, 'weight_class_2': 6.888888199910129}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,008] Trial 180 finished with value: 0.9479033650815132 and parameters: {'weight_class_0': 0.26452768662641846, 'weight_class_1': 8.958295942992176, 'weight_class_2': 6.096494258419794}. Best is trial 158 with value: 0.9492241819510037.

[I 2026-07-08 13:32:39,025] Trial 181 finished with value: 0.946841224731715 and parameters: {'weight_class_0': 0.19868301605731598, 'weight_class_1': 8.842799330105032, 'weight_class_2': 6.080299799918743}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,048] Trial 182 finished with value: 0.9478559115709838 and parameters: {'weight_class_0': 0.24989521204756648, 'weight_class_1': 7.532455524502764, 'weight_class_2': 6.93043255266797}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,056] Trial 183 finished with value: 0.9480359273872065 and parameters: {'weight_class_0': 0.2637926498652276, 'weight_class_1': 7.485875991150925, 'weight_class_2': 6.694314567151383}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,077] Trial 184 finished with value: 0.9481009770243406 and parameters: {'weight_class_0': 0.2819168638213892, 'weight_class_1': 8.100931694933013, 'weight_class_2': 6.7232794037603645}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,102] Trial 185 finished with value: 0.9491520030113029 and parameters: {'weight_class_0': 0.5605151523520618, 'weight_class_1': 9.999751381259774, 'weight_class_2': 7.009037423801793}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,121] Trial 186 finished with value: 0.9476250713508971 and parameters: {'weight_class_0': 0.26242248027393333, 'weight_class_1': 9.132077375206425, 'weight_class_2': 6.899627195250898}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,125] Trial 187 finished with value: 0.9491921942307714 and parameters: {'weight_class_0': 0.6135585868958812, 'weight_class_1': 8.800469309664763, 'weight_class_2': 6.7409408889208375}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,155] Trial 188 finished with value: 0.9491667875082109 and parameters: {'weight_class_0': 0.5895185676759411, 'weight_class_1': 9.99902943200662, 'weight_class_2': 7.526237868623901}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,179] Trial 189 finished with value: 0.9491695775958998 and parameters: {'weight_class_0': 0.5913446660144006, 'weight_class_1': 9.928902142252442, 'weight_class_2': 7.532218665455979}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,196] Trial 190 finished with value: 0.9481646732825088 and parameters: {'weight_class_0': 1.1617080816479661, 'weight_class_1': 9.899917393258761, 'weight_class_2': 7.545986547498168}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,209] Trial 192 finished with value: 0.9491549187193774 and parameters: {'weight_class_0': 0.5837362743116608, 'weight_class_1': 9.881733130959606, 'weight_class_2': 7.551208192174149}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,210] Trial 191 finished with value: 0.9491855983680829 and parameters: {'weight_class_0': 0.5877073683980844, 'weight_class_1': 9.93255945359094, 'weight_class_2': 7.516738875118399}. Best is trial 158 with value: 0.9492241819510037.

Best trial: 158. Best value: 0.949224:  10%|█████████████▍                                                                                                                      | 204/2000 [00:03<00:32, 54.89it/s]

[I 2026-07-08 13:32:39,241] Trial 193 finished with value: 0.9491728501906717 and parameters: {'weight_class_0': 0.5783199261115517, 'weight_class_1': 9.9463518186878, 'weight_class_2': 7.51409974153951}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,273] Trial 195 finished with value: 0.9482587264588189 and parameters: {'weight_class_0': 1.0769413468304745, 'weight_class_1': 8.7177081895264, 'weight_class_2': 7.300941235197562}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,280] Trial 194 finished with value: 0.9435092401377778 and parameters: {'weight_class_0': 1.1176499355554559, 'weight_class_1': 3.7616617571716144, 'weight_class_2': 7.300078830619671}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,294] Trial 196 finished with value: 0.9479652297127094 and parameters: {'weight_class_0': 1.1475270520488325, 'weight_class_1': 8.695035630196601, 'weight_class_2': 7.2664743768651965}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,310] Trial 197 finished with value: 0.9483202056016525 and parameters: {'weight_class_0': 1.0921794844753223, 'weight_class_1': 9.758458677622446, 'weight_class_2': 7.271634601858892}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,325] Trial 198 finished with value: 0.9491832730542634 and parameters: {'weight_class_0': 0.5919035251606974, 'weight_class_1': 9.52835600101759, 'weight_class_2': 7.180331663841356}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,359] Trial 200 finished with value: 0.9483827625366429 and parameters: {'weight_class_0': 1.0669088981165316, 'weight_class_1': 9.647725255405142, 'weight_class_2': 7.285774376510741}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,365] Trial 199 finished with value: 0.9491100720509372 and parameters: {'weight_class_0': 0.5967564763064689, 'weight_class_1': 9.562349962528227, 'weight_class_2': 7.306775900831852}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,412] Trial 201 finished with value: 0.9483345933198626 and parameters: {'weight_class_0': 1.077819829177841, 'weight_class_1': 9.579516992635495, 'weight_class_2': 7.339415972133528}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,413] Trial 202 finished with value: 0.9480761028956174 and parameters: {'weight_class_0': 1.1575743993435528, 'weight_class_1': 9.537966780888038, 'weight_class_2': 7.278974709829937}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,426] Trial 203 finished with value: 0.9482563203407451 and parameters: {'weight_class_0': 1.1021762014007805, 'weight_class_1': 9.489295113103744, 'weight_class_2': 7.269168339066379}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,441] Trial 204 finished with value: 0.9492071635408271 and parameters: {'weight_class_0': 0.6257706406885959, 'weight_class_1': 9.544063726594684, 'weight_class_2': 7.11626515570845}. Best is trial 158 with value: 0.9492241819510037.

[I 2026-07-08 13:32:39,463] Trial 205 finished with value: 0.9491819066379455 and parameters: {'weight_class_0': 0.5832652057077519, 'weight_class_1': 9.530986570587244, 'weight_class_2': 7.089064220922486}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,470] Trial 206 finished with value: 0.9491455204405884 and parameters: {'weight_class_0': 0.5836231661019935, 'weight_class_1': 9.58589796799774, 'weight_class_2': 7.7941573306525695}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,509] Trial 207 finished with value: 0.9491681585479826 and parameters: {'weight_class_0': 0.5818847634886866, 'weight_class_1': 9.55986006359503, 'weight_class_2': 7.046192564895639}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,520] Trial 208 finished with value: 0.9491287192617941 and parameters: {'weight_class_0': 0.5315056260711138, 'weight_class_1': 9.50518107453529, 'weight_class_2': 7.112680401779624}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,563] Trial 209 finished with value: 0.9491500331194297 and parameters: {'weight_class_0': 0.6148282529379687, 'weight_class_1': 9.455478614622377, 'weight_class_2': 7.78978878739587}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,570] Trial 211 finished with value: 0.9491491021195054 and parameters: {'weight_class_0': 0.60098807472203, 'weight_class_1': 9.54726773462775, 'weight_class_2': 7.11190344462163}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,575] Trial 210 finished with value: 0.949169244970267 and parameters: {'weight_class_0': 0.6045865869343285, 'weight_class_1': 9.503178187129103, 'weight_class_2': 7.779494600185729}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,590] Trial 212 finished with value: 0.9485727811592493 and parameters: {'weight_class_0': 0.6036067539769147, 'weight_class_1': 4.529785193480791, 'weight_class_2': 7.101142246042553}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,633] Trial 213 finished with value: 0.9489330373419804 and parameters: {'weight_class_0': 0.8300580825457475, 'weight_class_1': 9.870278836388795, 'weight_class_2': 7.052693840532009}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,646] Trial 214 finished with value: 0.948762244814061 and parameters: {'weight_class_0': 0.8731687596345188, 'weight_class_1': 9.333772158309527, 'weight_class_2': 7.013921303792107}. Best is trial 158 with value: 0.9492241819510037.

Best trial: 158. Best value: 0.949224:  11%|██████████████▉                                                                                                                     | 226/2000 [00:04<00:32, 55.22it/s]

[I 2026-07-08 13:32:39,654] Trial 215 finished with value: 0.9489831359780263 and parameters: {'weight_class_0': 0.7960319843446062, 'weight_class_1': 9.329090301471586, 'weight_class_2': 7.058282868802667}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,659] Trial 216 finished with value: 0.9487848032687095 and parameters: {'weight_class_0': 0.8773287080586369, 'weight_class_1': 9.427773654902438, 'weight_class_2': 7.074545769123156}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,689] Trial 217 finished with value: 0.9488898727225997 and parameters: {'weight_class_0': 0.8476649019115221, 'weight_class_1': 9.233926394898274, 'weight_class_2': 7.091659679960537}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,706] Trial 218 finished with value: 0.9489221718633066 and parameters: {'weight_class_0': 0.8045698311289684, 'weight_class_1': 9.217194360697027, 'weight_class_2': 7.063677326789118}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,730] Trial 219 finished with value: 0.9488712492588238 and parameters: {'weight_class_0': 0.9038044262316414, 'weight_class_1': 9.285151148411382, 'weight_class_2': 7.648494484460116}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,737] Trial 220 finished with value: 0.9489246501888192 and parameters: {'weight_class_0': 0.85964134457059, 'weight_class_1': 9.350734376076142, 'weight_class_2': 7.617972868583845}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,761] Trial 221 finished with value: 0.9490444129036343 and parameters: {'weight_class_0': 0.7994072834513881, 'weight_class_1': 9.287660594797542, 'weight_class_2': 7.676564679985753}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,779] Trial 222 finished with value: 0.9489164266151882 and parameters: {'weight_class_0': 0.863096300730911, 'weight_class_1': 9.18971774918596, 'weight_class_2': 7.660619678568073}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,782] Trial 223 finished with value: 0.9488820971688522 and parameters: {'weight_class_0': 0.9107338256974908, 'weight_class_1': 9.322972581311795, 'weight_class_2': 7.572794904810107}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,823] Trial 224 finished with value: 0.9487204878910175 and parameters: {'weight_class_0': 0.41190824965246287, 'weight_class_1': 9.164496623426068, 'weight_class_2': 7.715437727289066}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,837] Trial 225 finished with value: 0.9484618168581779 and parameters: {'weight_class_0': 0.3759744202290694, 'weight_class_1': 9.750672335051092, 'weight_class_2': 7.674089036751843}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,854] Trial 226 finished with value: 0.948475231643957 and parameters: {'weight_class_0': 0.37650989004095836, 'weight_class_1': 9.740067108589404, 'weight_class_2': 7.632829313701955}. Best is trial 158 with value: 0.9492241819510037.

[I 2026-07-08 13:32:39,871] Trial 227 finished with value: 0.9487046349106317 and parameters: {'weight_class_0': 0.3821802412933051, 'weight_class_1': 9.780551562556578, 'weight_class_2': 6.686783927175209}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,890] Trial 228 finished with value: 0.9486858013857026 and parameters: {'weight_class_0': 0.3761984764391256, 'weight_class_1': 9.777909221934122, 'weight_class_2': 6.696732409110821}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,904] Trial 230 finished with value: 0.9485275062263554 and parameters: {'weight_class_0': 0.38406519442197956, 'weight_class_1': 9.824469624419027, 'weight_class_2': 7.497692800854449}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,923] Trial 229 finished with value: 0.9485668668800509 and parameters: {'weight_class_0': 0.39523412063033114, 'weight_class_1': 9.814772160084805, 'weight_class_2': 7.568865005831348}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,954] Trial 232 finished with value: 0.9488466121463034 and parameters: {'weight_class_0': 0.46543784380238984, 'weight_class_1': 9.999911407307604, 'weight_class_2': 7.8985056818722885}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,968] Trial 231 finished with value: 0.9485463353334239 and parameters: {'weight_class_0': 0.4014626017626437, 'weight_class_1': 9.96437702663997, 'weight_class_2': 7.887231039819661}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,985] Trial 233 finished with value: 0.9485981265245949 and parameters: {'weight_class_0': 0.36753999300410856, 'weight_class_1': 9.78160007196685, 'weight_class_2': 6.746330052592161}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:39,992] Trial 234 finished with value: 0.9083270446218341 and parameters: {'weight_class_0': 0.058557009694140794, 'weight_class_1': 9.801800778279116, 'weight_class_2': 7.476399363005745}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,012] Trial 235 finished with value: 0.9448356816968868 and parameters: {'weight_class_0': 0.1617654190804093, 'weight_class_1': 9.982746832384347, 'weight_class_2': 6.723792886614219}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,031] Trial 236 finished with value: 0.9282768014311987 and parameters: {'weight_class_0': 0.07858221240832064, 'weight_class_1': 9.933313423812946, 'weight_class_2': 7.4317975290726}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,057] Trial 238 finished with value: 0.9182494862098866 and parameters: {'weight_class_0': 0.06656370527687744, 'weight_class_1': 9.90300061275035, 'weight_class_2': 7.48518519305459}. Best is trial 158 with value: 0.9492241819510037.

Best trial: 158. Best value: 0.949224:  12%|████████████████▍                                                                                                                   | 249/2000 [00:04<00:33, 52.79it/s]

[I 2026-07-08 13:32:40,074] Trial 237 finished with value: 0.9491468099642427 and parameters: {'weight_class_0': 0.6289679512228901, 'weight_class_1': 9.990860106974846, 'weight_class_2': 7.875951526592265}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,077] Trial 239 finished with value: 0.9040368842865557 and parameters: {'weight_class_0': 0.057737866812013094, 'weight_class_1': 9.959330383141856, 'weight_class_2': 7.95673730869184}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,114] Trial 240 finished with value: 0.9491202230033281 and parameters: {'weight_class_0': 0.5927463210127958, 'weight_class_1': 8.148452211083027, 'weight_class_2': 7.953419108235544}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,123] Trial 241 finished with value: 0.9491490055559195 and parameters: {'weight_class_0': 0.6483522161215404, 'weight_class_1': 7.9523997513679525, 'weight_class_2': 6.77837999347697}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,137] Trial 242 finished with value: 0.9491608649540231 and parameters: {'weight_class_0': 0.5582181522836431, 'weight_class_1': 8.023787533876586, 'weight_class_2': 7.461990961472807}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,192] Trial 243 finished with value: 0.9492077201264341 and parameters: {'weight_class_0': 0.6776879044467811, 'weight_class_1': 8.004132384495563, 'weight_class_2': 7.415124063159757}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,207] Trial 245 finished with value: 0.9491529781232092 and parameters: {'weight_class_0': 0.6284701896217806, 'weight_class_1': 7.927793279252934, 'weight_class_2': 7.3468303476421335}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,210] Trial 244 finished with value: 0.9492138732635302 and parameters: {'weight_class_0': 0.6856178932660651, 'weight_class_1': 8.075094116014691, 'weight_class_2': 7.458096221075776}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,227] Trial 246 finished with value: 0.9490301326614103 and parameters: {'weight_class_0': 0.7188422979044937, 'weight_class_1': 8.09681944652998, 'weight_class_2': 6.8694165432034655}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,238] Trial 247 finished with value: 0.9491941300750911 and parameters: {'weight_class_0': 0.6384555734112369, 'weight_class_1': 8.076106462431513, 'weight_class_2': 6.918755451245123}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,256] Trial 248 finished with value: 0.9491510626360764 and parameters: {'weight_class_0': 0.628474218986835, 'weight_class_1': 8.02319864744011, 'weight_class_2': 6.896724763130162}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,282] Trial 249 finished with value: 0.9491922963714403 and parameters: {'weight_class_0': 0.651795059433822, 'weight_class_1': 8.138044480866794, 'weight_class_2': 7.372095581074212}. Best is trial 158 with value: 0.9492241819510037.

[I 2026-07-08 13:32:40,310] Trial 251 finished with value: 0.9491314902668813 and parameters: {'weight_class_0': 0.6590146856946346, 'weight_class_1': 9.609364482469736, 'weight_class_2': 6.610463494421838}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,313] Trial 250 finished with value: 0.9491757100133614 and parameters: {'weight_class_0': 0.6377589250558222, 'weight_class_1': 9.6140307031209, 'weight_class_2': 6.866259640481766}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,330] Trial 253 finished with value: 0.9491477236136809 and parameters: {'weight_class_0': 0.6398022736221296, 'weight_class_1': 9.648846381018682, 'weight_class_2': 6.553907021004452}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,346] Trial 252 finished with value: 0.9490540220582363 and parameters: {'weight_class_0': 0.6556230938081165, 'weight_class_1': 8.190864355368838, 'weight_class_2': 6.233511510984111}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,360] Trial 254 finished with value: 0.9491748505374723 and parameters: {'weight_class_0': 0.694283382683087, 'weight_class_1': 8.187139740367602, 'weight_class_2': 7.371443416086217}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,394] Trial 255 finished with value: 0.9490756267735657 and parameters: {'weight_class_0': 0.7038458250310782, 'weight_class_1': 8.17064456584567, 'weight_class_2': 7.187790924839956}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,419] Trial 256 finished with value: 0.9490423334257848 and parameters: {'weight_class_0': 0.7121542253065164, 'weight_class_1': 8.23459968282273, 'weight_class_2': 7.214158123797475}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,441] Trial 257 finished with value: 0.9490826228048465 and parameters: {'weight_class_0': 0.7052912475244951, 'weight_class_1': 8.294288471126531, 'weight_class_2': 7.235029587564646}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,447] Trial 258 finished with value: 0.9491144516717992 and parameters: {'weight_class_0': 0.6970399335523126, 'weight_class_1': 8.244454936071978, 'weight_class_2': 7.242235650017217}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,470] Trial 259 finished with value: 0.9490322713604814 and parameters: {'weight_class_0': 0.7307492538673706, 'weight_class_1': 8.193215498216183, 'weight_class_2': 7.284055868030743}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,477] Trial 261 finished with value: 0.9489947088001878 and parameters: {'weight_class_0': 0.7516618401812153, 'weight_class_1': 8.207131115825094, 'weight_class_2': 7.248763839335945}. Best is trial 158 with value: 0.9492241819510037.

[I 2026-07-08 13:32:40,482] Trial 260 finished with value: 0.9487100935441783 and parameters: {'weight_class_0': 0.9018352648688336, 'weight_class_1': 8.274625614592809, 'weight_class_2': 7.24021183702339}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,521] Trial 262 finished with value: 0.9488198318111326 and parameters: {'weight_class_0': 0.8839625590191206, 'weight_class_1': 8.397434056381766, 'weight_class_2': 7.23730611231239}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,538] Trial 263 finished with value: 0.9485083089268262 and parameters: {'weight_class_0': 0.9493421374131092, 'weight_class_1': 7.86979227788082, 'weight_class_2': 7.246139763280779}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,555] Trial 264 finished with value: 0.94845694091872 and parameters: {'weight_class_0': 0.9708545227853856, 'weight_class_1': 7.880277175684612, 'weight_class_2': 7.253471525317471}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,581] Trial 265 finished with value: 0.9484945789812632 and parameters: {'weight_class_0': 0.9539795302195273, 'weight_class_1': 7.933165292465755, 'weight_class_2': 7.353122446841001}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,595] Trial 266 finished with value: 0.9486259997118959 and parameters: {'weight_class_0': 0.922965767209425, 'weight_class_1': 7.82245350682046, 'weight_class_2': 7.3599250934601}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,612] Trial 267 finished with value: 0.9484629071326777 and parameters: {'weight_class_0': 0.9602752869241014, 'weight_class_1': 7.807459031784221, 'weight_class_2': 7.422566931543411}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,632] Trial 269 finished with value: 0.9485627160916313 and parameters: {'weight_class_0': 0.9462847468412472, 'weight_class_1': 7.784934335330618, 'weight_class_2': 7.4262795449208525}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,644] Trial 268 finished with value: 0.9483969889498809 and parameters: {'weight_class_0': 1.0096714416097536, 'weight_class_1': 7.852605687082728, 'weight_class_2': 7.525802089492652}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,666] Trial 270 finished with value: 0.9484432022402324 and parameters: {'weight_class_0': 0.9926146845830772, 'weight_class_1': 7.8811803587327365, 'weight_class_2': 7.479035890363475}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,678] Trial 271 finished with value: 0.9466691681052198 and parameters: {'weight_class_0': 1.342703181691855, 'weight_class_1': 7.857940190292941, 'weight_class_2': 7.403804090847703}. Best is trial 158 with value: 0.9492241819510037.

[I 2026-07-08 13:32:40,694] Trial 272 finished with value: 0.9477820360410246 and parameters: {'weight_class_0': 0.256607959752414, 'weight_class_1': 7.878643600557778, 'weight_class_2': 7.448734735503585}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,717] Trial 273 finished with value: 0.9463313531369332 and parameters: {'weight_class_0': 1.3376702411028767, 'weight_class_1': 7.692140465935394, 'weight_class_2': 6.89093856707905}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,745] Trial 274 finished with value: 0.9475734590618026 and parameters: {'weight_class_0': 0.2449240840785391, 'weight_class_1': 8.477399244111016, 'weight_class_2': 6.890553810093025}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,746] Trial 275 finished with value: 0.946198667349304 and parameters: {'weight_class_0': 1.358091607853451, 'weight_class_1': 7.641780849516438, 'weight_class_2': 6.952752465022295}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,773] Trial 276 finished with value: 0.9483814851618707 and parameters: {'weight_class_0': 0.3212381047224525, 'weight_class_1': 8.48767211810847, 'weight_class_2': 6.9431761702834365}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,807] Trial 277 finished with value: 0.9469015646560361 and parameters: {'weight_class_0': 1.3101610249109008, 'weight_class_1': 8.4609264854125, 'weight_class_2': 6.919232365094411}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,810] Trial 278 finished with value: 0.9461449420869542 and parameters: {'weight_class_0': 1.4191830958786085, 'weight_class_1': 8.49210156830029, 'weight_class_2': 6.8942474550787525}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,829] Trial 279 finished with value: 0.9483485190016093 and parameters: {'weight_class_0': 0.3155807264809139, 'weight_class_1': 8.458285279972802, 'weight_class_2': 6.874730728538026}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,844] Trial 280 finished with value: 0.9489696014549388 and parameters: {'weight_class_0': 0.4281495171759344, 'weight_class_1': 8.485955969935164, 'weight_class_2': 6.89642558498778}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,881] Trial 281 finished with value: 0.9489625931903295 and parameters: {'weight_class_0': 0.4249839530301951, 'weight_class_1': 8.492725778217894, 'weight_class_2': 6.973830421013224}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,893] Trial 282 finished with value: 0.9488425001828836 and parameters: {'weight_class_0': 0.3477632521532643, 'weight_class_1': 8.475618759178259, 'weight_class_2': 3.1332254882817425}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,913] Trial 283 finished with value: 0.9486551230940994 and parameters: {'weight_class_0': 0.38703956053371974, 'weight_class_1': 8.478423493757235, 'weight_class_2': 7.737291247916012}. Best is trial 158 with value: 0.9492241819510037.

Best trial: 158. Best value: 0.949224:  15%|███████████████████▍                                                                                                                | 294/2000 [00:05<00:32, 53.18it/s]

[I 2026-07-08 13:32:40,924] Trial 284 finished with value: 0.9006648420162352 and parameters: {'weight_class_0': 0.4038765051898363, 'weight_class_1': 8.413324656912929, 'weight_class_2': 0.26881869579534}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,957] Trial 285 finished with value: 0.9488123686624048 and parameters: {'weight_class_0': 0.45310708235894115, 'weight_class_1': 8.06205441067967, 'weight_class_2': 8.289941318927035}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,977] Trial 286 finished with value: 0.948904448417978 and parameters: {'weight_class_0': 0.4484285598830018, 'weight_class_1': 8.049075071476638, 'weight_class_2': 7.706029695918521}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:40,981] Trial 287 finished with value: 0.9488920216198119 and parameters: {'weight_class_0': 0.4594880925968429, 'weight_class_1': 8.088270090146576, 'weight_class_2': 7.749478869845312}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,007] Trial 288 finished with value: 0.9488953662164291 and parameters: {'weight_class_0': 0.4345456150924799, 'weight_class_1': 8.15139282943594, 'weight_class_2': 7.736517178454725}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,014] Trial 289 finished with value: 0.9489821308049606 and parameters: {'weight_class_0': 0.49186210176610934, 'weight_class_1': 8.077324922773172, 'weight_class_2': 7.7359488062790085}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,031] Trial 290 finished with value: 0.9489464759163316 and parameters: {'weight_class_0': 0.4616032431305831, 'weight_class_1': 7.548447747961587, 'weight_class_2': 7.620635995847548}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,066] Trial 291 finished with value: 0.9489774177848318 and parameters: {'weight_class_0': 0.4815122158469705, 'weight_class_1': 8.067021149507717, 'weight_class_2': 7.751367254248617}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,091] Trial 293 finished with value: 0.9314370873848393 and parameters: {'weight_class_0': 0.5262503978369266, 'weight_class_1': 0.9211144440318151, 'weight_class_2': 7.642757674689052}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,101] Trial 292 finished with value: 0.949069674710366 and parameters: {'weight_class_0': 0.5219852211719953, 'weight_class_1': 8.078581521868655, 'weight_class_2': 7.70669749397971}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,113] Trial 294 finished with value: 0.9491015551268941 and parameters: {'weight_class_0': 0.5550918545516451, 'weight_class_1': 8.04629681302183, 'weight_class_2': 7.801011538088311}. Best is trial 158 with value: 0.9492241819510037.

Best trial: 158. Best value: 0.949224:  15%|████████████████████▎                                                                                                               | 307/2000 [00:05<00:30, 56.30it/s]

[I 2026-07-08 13:32:41,133] Trial 295 finished with value: 0.9338123053103162 and parameters: {'weight_class_0': 0.5518900247863507, 'weight_class_1': 1.0576784958139922, 'weight_class_2': 7.739223284024027}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,144] Trial 296 finished with value: 0.948970486099178 and parameters: {'weight_class_0': 0.7801410381496623, 'weight_class_1': 7.553150697581896, 'weight_class_2': 7.541072026476679}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,177] Trial 297 finished with value: 0.9380623075819846 and parameters: {'weight_class_0': 0.7552859581720257, 'weight_class_1': 7.496395422547867, 'weight_class_2': 1.7565635487400062}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,202] Trial 298 finished with value: 0.9489715404164704 and parameters: {'weight_class_0': 0.7677472884559234, 'weight_class_1': 8.758977633419235, 'weight_class_2': 7.093807492133123}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,209] Trial 299 finished with value: 0.9489979523743329 and parameters: {'weight_class_0': 0.7675986988563066, 'weight_class_1': 7.328183033774085, 'weight_class_2': 7.90094619129559}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,231] Trial 300 finished with value: 0.9348147139264973 and parameters: {'weight_class_0': 0.7753524802202137, 'weight_class_1': 1.5432270095333815, 'weight_class_2': 7.091087120321175}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,252] Trial 302 finished with value: 0.9489976580495463 and parameters: {'weight_class_0': 0.7630913054636884, 'weight_class_1': 8.748333731882365, 'weight_class_2': 7.111548050766833}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,254] Trial 301 finished with value: 0.9490903666932479 and parameters: {'weight_class_0': 0.7356852803073619, 'weight_class_1': 8.702249876387816, 'weight_class_2': 7.104903074841081}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,279] Trial 303 finished with value: 0.9488569743803756 and parameters: {'weight_class_0': 0.7733194878009851, 'weight_class_1': 7.256510054053448, 'weight_class_2': 7.123719279703301}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,298] Trial 304 finished with value: 0.9457491598585056 and parameters: {'weight_class_0': 0.17688761521389879, 'weight_class_1': 8.802820169657572, 'weight_class_2': 7.99857306792351}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,311] Trial 305 finished with value: 0.9489577135294466 and parameters: {'weight_class_0': 0.7356014779414296, 'weight_class_1': 8.727248102091567, 'weight_class_2': 6.648172101488319}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,340] Trial 306 finished with value: 0.9421095080458445 and parameters: {'weight_class_0': 0.11465944755122892, 'weight_class_1': 8.763413974536379, 'weight_class_2': 7.115325042981141}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,355] Trial 307 finished with value: 0.945368252470563 and parameters: {'weight_class_0': 0.15888822940344827, 'weight_class_1': 8.72496846642846, 'weight_class_2': 7.103540226968559}. Best is trial 158 with value: 0.9492241819510037.

Best trial: 158. Best value: 0.949224:  16%|████████████████████▉                                                                                                               | 318/2000 [00:05<00:31, 54.06it/s]

[I 2026-07-08 13:32:41,360] Trial 308 finished with value: 0.9447091097301071 and parameters: {'weight_class_0': 0.15726321700617985, 'weight_class_1': 9.592509763855627, 'weight_class_2': 7.146550738266764}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,397] Trial 309 finished with value: 0.9441726383166493 and parameters: {'weight_class_0': 0.15024852036751762, 'weight_class_1': 9.717238130981833, 'weight_class_2': 7.377157179032477}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,423] Trial 310 finished with value: 0.9445821515191541 and parameters: {'weight_class_0': 0.15739106113464868, 'weight_class_1': 9.660748160769023, 'weight_class_2': 7.388996463332825}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,429] Trial 311 finished with value: 0.9380161224695391 and parameters: {'weight_class_0': 0.09638378615780252, 'weight_class_1': 9.552662150366377, 'weight_class_2': 5.89777463094433}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,457] Trial 312 finished with value: 0.9370520160282244 and parameters: {'weight_class_0': 0.09648354285449223, 'weight_class_1': 9.541783207436756, 'weight_class_2': 7.396395526365409}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,464] Trial 313 finished with value: 0.9481380295110395 and parameters: {'weight_class_0': 1.150255618689015, 'weight_class_1': 9.541362223813056, 'weight_class_2': 7.463941758839657}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,479] Trial 314 finished with value: 0.9472972078513289 and parameters: {'weight_class_0': 1.1674930047700116, 'weight_class_1': 9.641833752703072, 'weight_class_2': 5.901209450825513}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,495] Trial 315 finished with value: 0.866117489074738 and parameters: {'weight_class_0': 9.765752117709628, 'weight_class_1': 9.704817223905804, 'weight_class_2': 5.901931928104637}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,508] Trial 316 finished with value: 0.9482102910488818 and parameters: {'weight_class_0': 1.1345959262348437, 'weight_class_1': 9.635975282661523, 'weight_class_2': 7.432455147137421}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,538] Trial 318 finished with value: 0.9478593392768034 and parameters: {'weight_class_0': 1.1454567821613555, 'weight_class_1': 8.284011889821976, 'weight_class_2': 7.432856407114222}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,542] Trial 317 finished with value: 0.9481636635139831 and parameters: {'weight_class_0': 1.1332808206053513, 'weight_class_1': 9.062172093903621, 'weight_class_2': 7.444503502127964}. Best is trial 158 with value: 0.9492241819510037.

[I 2026-07-08 13:32:41,572] Trial 319 finished with value: 0.9481607015583381 and parameters: {'weight_class_0': 1.1269100417739304, 'weight_class_1': 9.010535308363504, 'weight_class_2': 7.3980458887845515}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,581] Trial 320 finished with value: 0.9447162968720048 and parameters: {'weight_class_0': 1.1590513568793535, 'weight_class_1': 4.394266126241112, 'weight_class_2': 7.414536383097609}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,608] Trial 321 finished with value: 0.9478012285186935 and parameters: {'weight_class_0': 1.1476344599681867, 'weight_class_1': 8.219547536728415, 'weight_class_2': 7.474201035223766}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,619] Trial 322 finished with value: 0.9473300246030979 and parameters: {'weight_class_0': 1.087789421148202, 'weight_class_1': 9.086840021575503, 'weight_class_2': 5.538595185316168}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,662] Trial 324 finished with value: 0.9474643793917984 and parameters: {'weight_class_0': 1.0420584635225925, 'weight_class_1': 8.28610020761387, 'weight_class_2': 5.498281830125441}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,668] Trial 323 finished with value: 0.9484958991500108 and parameters: {'weight_class_0': 1.0433508298088543, 'weight_class_1': 8.334209112895445, 'weight_class_2': 8.191757165819139}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,677] Trial 325 finished with value: 0.9483489579000576 and parameters: {'weight_class_0': 0.9913572345424637, 'weight_class_1': 9.001064225225079, 'weight_class_2': 6.692808808365793}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,701] Trial 326 finished with value: 0.8703955694533393 and parameters: {'weight_class_0': 8.44850923684114, 'weight_class_1': 8.228964225455567, 'weight_class_2': 6.68244623467857}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,707] Trial 327 finished with value: 0.9491253551588225 and parameters: {'weight_class_0': 0.602589683279376, 'weight_class_1': 8.271577512712826, 'weight_class_2': 8.17141269851368}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,743] Trial 328 finished with value: 0.9490416305001578 and parameters: {'weight_class_0': 0.6173798018516014, 'weight_class_1': 8.262326860832955, 'weight_class_2': 5.4641076436199745}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,760] Trial 330 finished with value: 0.8807001221174812 and parameters: {'weight_class_0': 7.883612428526439, 'weight_class_1': 8.299421128098837, 'weight_class_2': 8.276910436412978}. Best is trial 158 with value: 0.9492241819510037.

Best trial: 158. Best value: 0.949224:  17%|██████████████████████▍                                                                                                             | 340/2000 [00:06<00:30, 53.67it/s]

[I 2026-07-08 13:32:41,780] Trial 329 finished with value: 0.949080800676719 and parameters: {'weight_class_0': 0.6013764115050116, 'weight_class_1': 8.285369481038598, 'weight_class_2': 8.265942934335934}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,787] Trial 331 finished with value: 0.9491328684720296 and parameters: {'weight_class_0': 0.6077290322530625, 'weight_class_1': 7.636526223754419, 'weight_class_2': 6.314998446154284}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,806] Trial 332 finished with value: 0.871891473115844 and parameters: {'weight_class_0': 8.231042563670066, 'weight_class_1': 8.31354511828331, 'weight_class_2': 6.6330322826070285}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,832] Trial 333 finished with value: 0.9491717225221455 and parameters: {'weight_class_0': 0.6094736645345453, 'weight_class_1': 7.634481456694261, 'weight_class_2': 6.742183288337843}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,854] Trial 334 finished with value: 0.9491446408951566 and parameters: {'weight_class_0': 0.6145034164745126, 'weight_class_1': 7.660398425147007, 'weight_class_2': 6.264979600334988}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,881] Trial 335 finished with value: 0.9491268185576266 and parameters: {'weight_class_0': 0.6319776615107263, 'weight_class_1': 7.663037478145454, 'weight_class_2': 7.609118781469866}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,886] Trial 336 finished with value: 0.949109509755 and parameters: {'weight_class_0': 0.5967807197193286, 'weight_class_1': 7.6366139634788865, 'weight_class_2': 7.968660876185875}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,900] Trial 337 finished with value: 0.883339489045874 and parameters: {'weight_class_0': 6.339505666535956, 'weight_class_1': 7.644451940696909, 'weight_class_2': 6.4292779297687535}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,921] Trial 338 finished with value: 0.9227117414388287 and parameters: {'weight_class_0': 3.2580171223893446, 'weight_class_1': 7.69021353190274, 'weight_class_2': 6.2263338225662554}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,931] Trial 339 finished with value: 0.8976578563252988 and parameters: {'weight_class_0': 5.802952211742781, 'weight_class_1': 7.988898276091706, 'weight_class_2': 7.953779234458504}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,962] Trial 340 finished with value: 0.8841548309256234 and parameters: {'weight_class_0': 7.10855813647156, 'weight_class_1': 7.930248404489747, 'weight_class_2': 7.929461006152192}. Best is trial 158 with value: 0.9492241819510037.

Best trial: 158. Best value: 0.949224:  18%|███████████████████████▏                                                                                                            | 352/2000 [00:06<00:30, 54.05it/s]

[I 2026-07-08 13:32:41,978] Trial 341 finished with value: 0.9483612200139939 and parameters: {'weight_class_0': 0.3428522760590022, 'weight_class_1': 7.982977741099513, 'weight_class_2': 7.924507313481575}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:41,997] Trial 342 finished with value: 0.9487786536320177 and parameters: {'weight_class_0': 0.7957736183542766, 'weight_class_1': 7.877508585552287, 'weight_class_2': 6.392069412787092}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,033] Trial 344 finished with value: 0.9482799839894936 and parameters: {'weight_class_0': 0.2963385450697694, 'weight_class_1': 7.920934298065086, 'weight_class_2': 6.785429627923735}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,040] Trial 343 finished with value: 0.8643425019469172 and parameters: {'weight_class_0': 9.444400928818162, 'weight_class_1': 8.018674186447807, 'weight_class_2': 6.55302959994809}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,066] Trial 346 finished with value: 0.9483977776681206 and parameters: {'weight_class_0': 0.30942864646134094, 'weight_class_1': 7.883679789709496, 'weight_class_2': 6.7531966654391615}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,071] Trial 345 finished with value: 0.9486024858500409 and parameters: {'weight_class_0': 0.3282928761083262, 'weight_class_1': 7.947844970047518, 'weight_class_2': 6.481029336546006}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,111] Trial 347 finished with value: 0.9487546243385762 and parameters: {'weight_class_0': 0.36676274962137706, 'weight_class_1': 7.925503402513463, 'weight_class_2': 6.729730801509797}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,124] Trial 348 finished with value: 0.9482650491666372 and parameters: {'weight_class_0': 0.29782941624401127, 'weight_class_1': 7.904189786787699, 'weight_class_2': 6.813407590395338}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,133] Trial 349 finished with value: 0.9484455145987507 and parameters: {'weight_class_0': 0.3243675630613472, 'weight_class_1': 7.941027068291168, 'weight_class_2': 6.960836049642381}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,145] Trial 350 finished with value: 0.9488259231725182 and parameters: {'weight_class_0': 0.8247337382019719, 'weight_class_1': 7.89962566311025, 'weight_class_2': 6.8398674202429826}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,187] Trial 351 finished with value: 0.9483184582204908 and parameters: {'weight_class_0': 0.29609819167319007, 'weight_class_1': 7.400919432369052, 'weight_class_2': 6.821645586629709}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,193] Trial 352 finished with value: 0.9481543020819251 and parameters: {'weight_class_0': 0.3039818560902537, 'weight_class_1': 9.327607865792624, 'weight_class_2': 6.759769277867522}. Best is trial 158 with value: 0.9492241819510037.

Best trial: 158. Best value: 0.949224:  18%|███████████████████████▉                                                                                                            | 363/2000 [00:06<00:30, 53.07it/s]

[I 2026-07-08 13:32:42,232] Trial 353 finished with value: 0.9167269267286257 and parameters: {'weight_class_0': 0.8874926712771152, 'weight_class_1': 8.028851569825529, 'weight_class_2': 1.0539495931693303}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,238] Trial 354 finished with value: 0.9485764452558466 and parameters: {'weight_class_0': 0.8958602677409128, 'weight_class_1': 8.069832901961536, 'weight_class_2': 6.989217440745925}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,259] Trial 355 finished with value: 0.9485685583840072 and parameters: {'weight_class_0': 0.8797741896682575, 'weight_class_1': 7.4242147403522205, 'weight_class_2': 6.9558623617996105}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,277] Trial 356 finished with value: 0.9486171215576323 and parameters: {'weight_class_0': 0.873550980458657, 'weight_class_1': 7.363953382209854, 'weight_class_2': 7.0073470622490355}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,289] Trial 357 finished with value: 0.9488452202787826 and parameters: {'weight_class_0': 0.8664458757994667, 'weight_class_1': 9.378600137330563, 'weight_class_2': 7.172311522367489}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,316] Trial 358 finished with value: 0.9486156587756082 and parameters: {'weight_class_0': 0.8819716049225683, 'weight_class_1': 7.377722714371421, 'weight_class_2': 7.093366895693952}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,328] Trial 359 finished with value: 0.9486628842118404 and parameters: {'weight_class_0': 0.887046104064938, 'weight_class_1': 7.431307980341315, 'weight_class_2': 7.2264714510891555}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,332] Trial 360 finished with value: 0.9486995119301036 and parameters: {'weight_class_0': 0.875938135347367, 'weight_class_1': 7.4136916422750065, 'weight_class_2': 7.207755576772389}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,367] Trial 361 finished with value: 0.9488660994318874 and parameters: {'weight_class_0': 0.8276023037378726, 'weight_class_1': 8.134308888085368, 'weight_class_2': 7.215697646760794}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,380] Trial 362 finished with value: 0.9487671478465461 and parameters: {'weight_class_0': 0.9006485143817287, 'weight_class_1': 9.419146680941923, 'weight_class_2': 7.229273663966874}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,396] Trial 363 finished with value: 0.948541771999261 and parameters: {'weight_class_0': 0.8994865956519869, 'weight_class_1': 7.029223668854764, 'weight_class_2': 7.236045970103619}. Best is trial 158 with value: 0.9492241819510037.

Best trial: 158. Best value: 0.949224:  19%|████████████████████████▋                                                                                                           | 374/2000 [00:06<00:32, 50.18it/s]

[I 2026-07-08 13:32:42,416] Trial 364 finished with value: 0.9488652872855926 and parameters: {'weight_class_0': 0.7744107343302089, 'weight_class_1': 7.152457716716539, 'weight_class_2': 7.152036839689623}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,463] Trial 365 finished with value: 0.9491599754754186 and parameters: {'weight_class_0': 0.5584426883189437, 'weight_class_1': 9.391550840031945, 'weight_class_2': 7.141568335183457}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,476] Trial 366 finished with value: 0.9451421541073829 and parameters: {'weight_class_0': 0.589990332745302, 'weight_class_1': 7.1032685105201825, 'weight_class_2': 2.0891676323222192}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,488] Trial 367 finished with value: 0.7974292724485377 and parameters: {'weight_class_0': 0.5291132611896188, 'weight_class_1': 0.0148838686061179, 'weight_class_2': 7.248496836000508}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,501] Trial 368 finished with value: 0.9491073283753865 and parameters: {'weight_class_0': 0.5432770411118307, 'weight_class_1': 9.4006590422659, 'weight_class_2': 7.232594084048874}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,515] Trial 369 finished with value: 0.9491247181801473 and parameters: {'weight_class_0': 0.5439637145488848, 'weight_class_1': 9.80515035108572, 'weight_class_2': 7.281274416002673}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,531] Trial 370 finished with value: 0.9490707374188809 and parameters: {'weight_class_0': 0.525711614809306, 'weight_class_1': 8.624983487627242, 'weight_class_2': 7.588049353592015}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,560] Trial 371 finished with value: 0.9490986858309577 and parameters: {'weight_class_0': 0.5112281879395566, 'weight_class_1': 8.52451439441865, 'weight_class_2': 7.550169246307412}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,570] Trial 372 finished with value: 0.9491043523515003 and parameters: {'weight_class_0': 0.5635286317086629, 'weight_class_1': 8.613769726117495, 'weight_class_2': 7.628067420849901}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,601] Trial 373 finished with value: 0.9489473302624974 and parameters: {'weight_class_0': 0.473168022041652, 'weight_class_1': 8.595985541464556, 'weight_class_2': 7.6249513842144685}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,620] Trial 374 finished with value: 0.94905635931774 and parameters: {'weight_class_0': 0.5572848869046951, 'weight_class_1': 8.605922253773176, 'weight_class_2': 7.65336043752445}. Best is trial 158 with value: 0.9492241819510037.

[I 2026-07-08 13:32:42,625] Trial 375 finished with value: 0.9469800511417836 and parameters: {'weight_class_0': 0.5043128285853504, 'weight_class_1': 8.516618890713882, 'weight_class_2': 2.2547605766738754}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,658] Trial 376 finished with value: 0.949103978340656 and parameters: {'weight_class_0': 0.5697529216154156, 'weight_class_1': 8.60030309753142, 'weight_class_2': 7.526762811788288}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,688] Trial 377 finished with value: 0.9491845459962133 and parameters: {'weight_class_0': 0.6714383374971413, 'weight_class_1': 8.604310221785974, 'weight_class_2': 7.556679270347448}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,710] Trial 378 finished with value: 0.9119899868817797 and parameters: {'weight_class_0': 4.589017804488269, 'weight_class_1': 8.488362665551332, 'weight_class_2': 7.600520305872506}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,714] Trial 379 finished with value: 0.9457802498347879 and parameters: {'weight_class_0': 1.553674800186851, 'weight_class_1': 8.347879119237993, 'weight_class_2': 7.583545337050984}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,730] Trial 380 finished with value: 0.9468592925619269 and parameters: {'weight_class_0': 0.6872314320747602, 'weight_class_1': 3.141741029539412, 'weight_class_2': 7.608666056500681}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,749] Trial 381 finished with value: 0.9126932539822367 and parameters: {'weight_class_0': 4.413065920168523, 'weight_class_1': 8.13117895607376, 'weight_class_2': 7.513862531597207}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,770] Trial 382 finished with value: 0.9491538953348228 and parameters: {'weight_class_0': 0.6993143478798545, 'weight_class_1': 8.1893121325908, 'weight_class_2': 7.527902846791962}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,802] Trial 383 finished with value: 0.9491059403630034 and parameters: {'weight_class_0': 0.7594252929785673, 'weight_class_1': 9.99351598230814, 'weight_class_2': 7.515560584746601}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,821] Trial 384 finished with value: 0.9484985316484303 and parameters: {'weight_class_0': 0.7007714254439019, 'weight_class_1': 8.127500080106834, 'weight_class_2': 4.912408053136916}. Best is trial 158 with value: 0.9492241819510037.

Best trial: 158. Best value: 0.949224:  20%|██████████████████████████                                                                                                          | 395/2000 [00:07<00:30, 52.21it/s]

[I 2026-07-08 13:32:42,837] Trial 385 finished with value: 0.9445037370188324 and parameters: {'weight_class_0': 1.6711862337825072, 'weight_class_1': 7.720786339232584, 'weight_class_2': 7.3869846241528485}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,850] Trial 386 finished with value: 0.9107981378136235 and parameters: {'weight_class_0': 4.265646768112141, 'weight_class_1': 8.185297685481395, 'weight_class_2': 6.598004497226807}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,873] Trial 387 finished with value: 0.9477425853506628 and parameters: {'weight_class_0': 0.6926129232630692, 'weight_class_1': 8.158643437290944, 'weight_class_2': 3.6260318424080094}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,891] Trial 388 finished with value: 0.696989446201861 and parameters: {'weight_class_0': 0.01394632996415135, 'weight_class_1': 8.198282576125644, 'weight_class_2': 6.573521798729224}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,907] Trial 389 finished with value: 0.9471924623422744 and parameters: {'weight_class_0': 0.23805858868599078, 'weight_class_1': 9.803211208811298, 'weight_class_2': 6.568607492659996}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,924] Trial 390 finished with value: 0.9460122200520772 and parameters: {'weight_class_0': 0.19681226125556317, 'weight_class_1': 9.747843915456707, 'weight_class_2': 7.887099627768533}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,945] Trial 391 finished with value: 0.9461770343049917 and parameters: {'weight_class_0': 0.190815308657602, 'weight_class_1': 8.92525281884923, 'weight_class_2': 7.883191834854028}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,972] Trial 392 finished with value: 0.9473140999813842 and parameters: {'weight_class_0': 0.24842355368704527, 'weight_class_1': 9.999617256465635, 'weight_class_2': 6.5545732649302}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:42,987] Trial 393 finished with value: 0.6615516560770267 and parameters: {'weight_class_0': 0.008368172416274078, 'weight_class_1': 9.174458607053554, 'weight_class_2': 7.857956212289913}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,022] Trial 394 finished with value: 0.9458729741558307 and parameters: {'weight_class_0': 0.1830090615549924, 'weight_class_1': 9.778417538978987, 'weight_class_2': 6.619124982249178}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,032] Trial 395 finished with value: 0.9474921356101137 and parameters: {'weight_class_0': 0.23071492492314033, 'weight_class_1': 8.897965204636309, 'weight_class_2': 5.727346564546841}. Best is trial 158 with value: 0.9492241819510037.

[I 2026-07-08 13:32:43,066] Trial 396 finished with value: 0.947130600147282 and parameters: {'weight_class_0': 0.23586514434424638, 'weight_class_1': 8.904738900546946, 'weight_class_2': 7.825291975830178}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,075] Trial 397 finished with value: 0.948554649834648 and parameters: {'weight_class_0': 0.3785551011245697, 'weight_class_1': 9.125190237607852, 'weight_class_2': 7.82380311408044}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,092] Trial 398 finished with value: 0.9473758016527526 and parameters: {'weight_class_0': 0.2530532584304898, 'weight_class_1': 8.876980975337833, 'weight_class_2': 7.850072314220658}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,115] Trial 399 finished with value: 0.9484008673874537 and parameters: {'weight_class_0': 0.33344934329679154, 'weight_class_1': 8.946379460064989, 'weight_class_2': 6.971376386425746}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,128] Trial 400 finished with value: 0.9455792371348802 and parameters: {'weight_class_0': 1.285785423119215, 'weight_class_1': 7.704993881907443, 'weight_class_2': 5.641436561687871}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,143] Trial 401 finished with value: 0.9469620984223147 and parameters: {'weight_class_0': 1.3456861889088505, 'weight_class_1': 9.139700555528552, 'weight_class_2': 7.014903152666048}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,158] Trial 402 finished with value: 0.9487528306992078 and parameters: {'weight_class_0': 0.37941924462549587, 'weight_class_1': 5.874809118134526, 'weight_class_2': 6.9793698455472555}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,195] Trial 403 finished with value: 0.9431839608265324 and parameters: {'weight_class_0': 1.2992203264173348, 'weight_class_1': 7.765273581461773, 'weight_class_2': 4.354081313520543}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,202] Trial 404 finished with value: 0.9465198984396633 and parameters: {'weight_class_0': 1.3183759214356794, 'weight_class_1': 7.755043452219722, 'weight_class_2': 6.970699690020907}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,214] Trial 405 finished with value: 0.9449132239356605 and parameters: {'weight_class_0': 1.2748669236922674, 'weight_class_1': 5.2549461537274755, 'weight_class_2': 6.966488257329628}. Best is trial 158 with value: 0.9492241819510037.

[I 2026-07-08 13:32:43,244] Trial 406 finished with value: 0.9481520653361671 and parameters: {'weight_class_0': 1.0244745203233638, 'weight_class_1': 7.759134872553765, 'weight_class_2': 6.953577346939044}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,274] Trial 409 finished with value: 0.9483806672917483 and parameters: {'weight_class_0': 1.0185828378502233, 'weight_class_1': 8.402897959707971, 'weight_class_2': 7.337123124685249}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,277] Trial 407 finished with value: 0.9465504799210618 and parameters: {'weight_class_0': 1.3021575690794074, 'weight_class_1': 7.748803751783719, 'weight_class_2': 6.927251805353766}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,289] Trial 408 finished with value: 0.9480497500513271 and parameters: {'weight_class_0': 1.041047912026288, 'weight_class_1': 7.791361769074185, 'weight_class_2': 7.031334464467905}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,328] Trial 410 finished with value: 0.9481351821682975 and parameters: {'weight_class_0': 0.9459369197396867, 'weight_class_1': 7.794385647102899, 'weight_class_2': 6.124962067369392}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,333] Trial 411 finished with value: 0.9489801949142972 and parameters: {'weight_class_0': 0.7496924787077427, 'weight_class_1': 7.775867208038038, 'weight_class_2': 7.338463676841242}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,364] Trial 412 finished with value: 0.9484128992929688 and parameters: {'weight_class_0': 1.033681522434089, 'weight_class_1': 9.54104483276738, 'weight_class_2': 7.325618727459478}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,379] Trial 413 finished with value: 0.9484869294923999 and parameters: {'weight_class_0': 0.9778595511549759, 'weight_class_1': 8.350044019662553, 'weight_class_2': 7.33812851726355}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,386] Trial 414 finished with value: 0.9483536840994308 and parameters: {'weight_class_0': 1.0268653905374896, 'weight_class_1': 8.36540537936327, 'weight_class_2': 7.376178626665921}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,412] Trial 415 finished with value: 0.948086173796642 and parameters: {'weight_class_0': 0.9770454461905314, 'weight_class_1': 8.372593339326135, 'weight_class_2': 6.118564432725473}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,424] Trial 416 finished with value: 0.9490548583912579 and parameters: {'weight_class_0': 0.7259252534000583, 'weight_class_1': 8.377542361744007, 'weight_class_2': 7.344841113187037}. Best is trial 158 with value: 0.9492241819510037.

Best trial: 158. Best value: 0.949224:  21%|████████████████████████████▏                                                                                                       | 427/2000 [00:07<00:31, 49.99it/s]

[I 2026-07-08 13:32:43,466] Trial 417 finished with value: 0.949142295326947 and parameters: {'weight_class_0': 0.7260143223747811, 'weight_class_1': 9.540930223465763, 'weight_class_2': 7.431578977745449}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,468] Trial 418 finished with value: 0.9490512969382721 and parameters: {'weight_class_0': 0.7582319122995713, 'weight_class_1': 9.541324285100668, 'weight_class_2': 7.356496118126942}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,509] Trial 419 finished with value: 0.9346332367029341 and parameters: {'weight_class_0': 0.7014934318962954, 'weight_class_1': 8.403702138071793, 'weight_class_2': 1.4220192379272971}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,525] Trial 420 finished with value: 0.9486816200188133 and parameters: {'weight_class_0': 0.7365864370876535, 'weight_class_1': 9.64393293546139, 'weight_class_2': 5.360668328402069}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,532] Trial 421 finished with value: 0.9490654685814609 and parameters: {'weight_class_0': 0.7421544913535091, 'weight_class_1': 9.584284578313504, 'weight_class_2': 7.3522734664086835}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,560] Trial 422 finished with value: 0.9490509400231154 and parameters: {'weight_class_0': 0.7176475798172999, 'weight_class_1': 9.775864763815193, 'weight_class_2': 6.350136306782009}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,570] Trial 423 finished with value: 0.9492030486276252 and parameters: {'weight_class_0': 0.7059876190476899, 'weight_class_1': 9.71252625682178, 'weight_class_2': 8.126617392455607}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,592] Trial 424 finished with value: 0.9491801417518394 and parameters: {'weight_class_0': 0.734248783892384, 'weight_class_1': 9.655554165610058, 'weight_class_2': 7.731202867214122}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,603] Trial 425 finished with value: 0.9492222288131164 and parameters: {'weight_class_0': 0.7069807889389945, 'weight_class_1': 9.631539031796848, 'weight_class_2': 7.713122625042754}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,632] Trial 426 finished with value: 0.9491857293981226 and parameters: {'weight_class_0': 0.46701588814508344, 'weight_class_1': 9.665141525968993, 'weight_class_2': 5.269626866437014}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,658] Trial 427 finished with value: 0.9490894013012072 and parameters: {'weight_class_0': 0.5235035180485564, 'weight_class_1': 8.062493738193481, 'weight_class_2': 5.214595735592943}. Best is trial 158 with value: 0.9492241819510037.

Best trial: 158. Best value: 0.949224:  22%|████████████████████████████▉                                                                                                       | 439/2000 [00:08<00:29, 52.62it/s]

[I 2026-07-08 13:32:43,679] Trial 428 finished with value: 0.9488652467203588 and parameters: {'weight_class_0': 0.47038868790126126, 'weight_class_1': 9.799137232287634, 'weight_class_2': 8.11627425402464}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,689] Trial 429 finished with value: 0.9489757746075203 and parameters: {'weight_class_0': 0.5261242555696208, 'weight_class_1': 8.076480198201097, 'weight_class_2': 8.12896720127606}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,713] Trial 430 finished with value: 0.9489031167972494 and parameters: {'weight_class_0': 0.4535183895417931, 'weight_class_1': 8.037582358897332, 'weight_class_2': 7.709255455699049}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,732] Trial 431 finished with value: 0.9490546678161792 and parameters: {'weight_class_0': 0.4492222127329629, 'weight_class_1': 7.980637148195013, 'weight_class_2': 6.779895875351374}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,759] Trial 433 finished with value: 0.9487503671537992 and parameters: {'weight_class_0': 0.4457919530793347, 'weight_class_1': 9.316235509507656, 'weight_class_2': 8.18910204930462}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,769] Trial 434 finished with value: 0.9487993601001113 and parameters: {'weight_class_0': 0.45336714711175696, 'weight_class_1': 9.312858479902271, 'weight_class_2': 8.514318613121691}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,771] Trial 432 finished with value: 0.9488623706986917 and parameters: {'weight_class_0': 0.4679136503660513, 'weight_class_1': 9.811564872826697, 'weight_class_2': 8.078567797408528}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,815] Trial 436 finished with value: 0.9490633737038662 and parameters: {'weight_class_0': 0.41993227966249336, 'weight_class_1': 9.349359741047648, 'weight_class_2': 4.942072067100143}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,821] Trial 435 finished with value: 0.9484821953597997 and parameters: {'weight_class_0': 0.3959052671184844, 'weight_class_1': 9.39452647645372, 'weight_class_2': 8.451334784743846}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,851] Trial 438 finished with value: 0.9487289848975191 and parameters: {'weight_class_0': 0.433534118911858, 'weight_class_1': 9.305428010073932, 'weight_class_2': 8.04180131177987}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,855] Trial 437 finished with value: 0.9485422836891427 and parameters: {'weight_class_0': 0.4081893906642824, 'weight_class_1': 9.317075388958486, 'weight_class_2': 8.485034395237312}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,890] Trial 439 finished with value: 0.9488200470690984 and parameters: {'weight_class_0': 0.4616763507570564, 'weight_class_1': 9.337911814157128, 'weight_class_2': 8.429193221656199}. Best is trial 158 with value: 0.9492241819510037.

Best trial: 158. Best value: 0.949224:  23%|█████████████████████████████▊                                                                                                      | 451/2000 [00:08<00:27, 55.60it/s]

[I 2026-07-08 13:32:43,908] Trial 441 finished with value: 0.9490099347452414 and parameters: {'weight_class_0': 0.395166834586951, 'weight_class_1': 9.232976278188147, 'weight_class_2': 4.952668133754443}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,919] Trial 440 finished with value: 0.9484714560488067 and parameters: {'weight_class_0': 0.40003223646808106, 'weight_class_1': 9.422954266393768, 'weight_class_2': 8.645826638695665}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,943] Trial 442 finished with value: 0.9479519098042785 and parameters: {'weight_class_0': 0.9038093995597702, 'weight_class_1': 9.423729624141258, 'weight_class_2': 5.141817029984737}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,977] Trial 444 finished with value: 0.9476591015502462 and parameters: {'weight_class_0': 0.9206694639875795, 'weight_class_1': 9.477997792845391, 'weight_class_2': 4.909419119645135}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,991] Trial 443 finished with value: 0.9480102391508728 and parameters: {'weight_class_0': 0.8661719961771182, 'weight_class_1': 9.469356162935378, 'weight_class_2': 5.015673180393521}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:43,993] Trial 445 finished with value: 0.9482288231454185 and parameters: {'weight_class_0': 0.8434604735690668, 'weight_class_1': 9.696058058713799, 'weight_class_2': 5.165834468485335}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:44,010] Trial 446 finished with value: 0.9481606718640126 and parameters: {'weight_class_0': 0.8920573187417766, 'weight_class_1': 9.513659600629744, 'weight_class_2': 5.507739209895764}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:44,038] Trial 447 finished with value: 0.9482519865355211 and parameters: {'weight_class_0': 0.8420352260223176, 'weight_class_1': 9.6125133391522, 'weight_class_2': 5.270246074371957}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:44,046] Trial 448 finished with value: 0.9480162958194658 and parameters: {'weight_class_0': 0.8859904667012918, 'weight_class_1': 9.655011868042216, 'weight_class_2': 5.1800628766038415}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:44,078] Trial 449 finished with value: 0.9481495804258847 and parameters: {'weight_class_0': 0.8649641368213424, 'weight_class_1': 9.733182611938686, 'weight_class_2': 5.183976115025638}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:44,107] Trial 451 finished with value: 0.9483440329887154 and parameters: {'weight_class_0': 0.8191275091642131, 'weight_class_1': 9.70422050366744, 'weight_class_2': 5.192612246419153}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:44,116] Trial 450 finished with value: 0.6773893922553592 and parameters: {'weight_class_0': 0.013133425746904903, 'weight_class_1': 9.640124495537517, 'weight_class_2': 7.755137864381213}. Best is trial 158 with value: 0.9492241819510037.

[I 2026-07-08 13:32:44,145] Trial 452 finished with value: 0.7622027886808627 and parameters: {'weight_class_0': 0.022014518454596788, 'weight_class_1': 9.715414101538098, 'weight_class_2': 5.396534745522301}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:44,151] Trial 454 finished with value: 0.9485594065343609 and parameters: {'weight_class_0': 0.7971099864534484, 'weight_class_1': 9.741773811325562, 'weight_class_2': 5.49288428367417}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:44,153] Trial 453 finished with value: 0.9484957532183159 and parameters: {'weight_class_0': 0.8057247185027865, 'weight_class_1': 9.708564930117417, 'weight_class_2': 5.39548107249619}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:44,186] Trial 456 finished with value: 0.9490162013591591 and parameters: {'weight_class_0': 0.6596237244383967, 'weight_class_1': 9.712640382167152, 'weight_class_2': 5.743228325208079}. Best is trial 158 with value: 0.9492241819510037.
[I 2026-07-08 13:32:44,197] Trial 455 finished with value: 0.9492501666906682 and parameters: {'weight_class_0': 0.6918828617764884, 'weight_class_1': 9.674244046765274, 'weight_class_2': 7.8185379180545285}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:44,225] Trial 458 finished with value: 0.8560672275613195 and parameters: {'weight_class_0': 0.040233331268265615, 'weight_class_1': 9.821347117927454, 'weight_class_2': 7.763502151766553}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:44,227] Trial 457 finished with value: 0.6687790312969795 and parameters: {'weight_class_0': 0.011197677140958262, 'weight_class_1': 9.795955359348424, 'weight_class_2': 7.756775353619448}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:44,238] Trial 459 finished with value: 0.797722674002083 and parameters: {'weight_class_0': 0.023597617659319448, 'weight_class_1': 9.99222987821515, 'weight_class_2': 0.7800522364091531}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:44,273] Trial 460 finished with value: 0.949017727512901 and parameters: {'weight_class_0': 0.6655636207332587, 'weight_class_1': 9.84408447889711, 'weight_class_2': 5.767458658287392}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:44,291] Trial 462 finished with value: 0.9489981580968153 and parameters: {'weight_class_0': 0.6747224642593813, 'weight_class_1': 9.902871814375715, 'weight_class_2': 5.6939088001537135}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:44,295] Trial 461 finished with value: 0.6731731046045798 and parameters: {'weight_class_0': 0.0106508665216547, 'weight_class_1': 9.78215024464932, 'weight_class_2': 5.727486221244082}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:44,315] Trial 463 finished with value: 0.9491324301642977 and parameters: {'weight_class_0': 0.6468504653687149, 'weight_class_1': 9.917971089484235, 'weight_class_2': 7.6904502397790795}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:32:44,355] Trial 464 finished with value: 0.9490056398271932 and parameters: {'weight_class_0': 0.6378346199259545, 'weight_class_1': 9.85074572776519, 'weight_class_2': 5.719717930512774}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:44,372] Trial 465 finished with value: 0.948294303940801 and parameters: {'weight_class_0': 1.1409069621408618, 'weight_class_1': 9.906457913794586, 'weight_class_2': 7.708477164643051}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:44,377] Trial 466 finished with value: 0.9491484228333102 and parameters: {'weight_class_0': 0.6298654176958767, 'weight_class_1': 9.117828494572043, 'weight_class_2': 7.897990743842029}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:44,398] Trial 467 finished with value: 0.9483656970975481 and parameters: {'weight_class_0': 1.1319220095173697, 'weight_class_1': 9.819594568302525, 'weight_class_2': 8.011859999567125}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:44,413] Trial 468 finished with value: 0.9482439953748579 and parameters: {'weight_class_0': 1.1352535356031317, 'weight_class_1': 9.104507846348193, 'weight_class_2': 7.97531197655354}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:44,434] Trial 469 finished with value: 0.9482335343590945 and parameters: {'weight_class_0': 1.1850951133823378, 'weight_class_1': 9.97399463159845, 'weight_class_2': 7.852074013804259}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:44,456] Trial 470 finished with value: 0.9484918082638204 and parameters: {'weight_class_0': 1.0772873141202148, 'weight_class_1': 9.163783659314905, 'weight_class_2': 8.03421765587963}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:44,473] Trial 472 finished with value: 0.9485332348333939 and parameters: {'weight_class_0': 1.055305023742699, 'weight_class_1': 9.076939523778787, 'weight_class_2': 7.963851760529827}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:44,487] Trial 471 finished with value: 0.9485273229498392 and parameters: {'weight_class_0': 1.0431376357276636, 'weight_class_1': 9.113190337719614, 'weight_class_2': 8.00869272397985}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:44,520] Trial 473 finished with value: 0.9482457397469229 and parameters: {'weight_class_0': 1.1970527388067604, 'weight_class_1': 9.988331583154126, 'weight_class_2': 8.048837949695006}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:44,529] Trial 475 finished with value: 0.948485270581355 and parameters: {'weight_class_0': 1.0698721065138774, 'weight_class_1': 9.071689882340042, 'weight_class_2': 7.998696437125709}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  24%|████████████████████████████████▎                                                                                                    | 486/2000 [00:09<00:27, 55.39it/s]

[I 2026-07-08 13:32:44,544] Trial 474 finished with value: 0.9485303935045195 and parameters: {'weight_class_0': 1.0527981429159978, 'weight_class_1': 9.065859157087722, 'weight_class_2': 7.9903170941795025}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:44,565] Trial 476 finished with value: 0.9485020979589227 and parameters: {'weight_class_0': 1.1012972908211132, 'weight_class_1': 9.497227651646401, 'weight_class_2': 8.16698705587052}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:44,573] Trial 477 finished with value: 0.9486187937222588 and parameters: {'weight_class_0': 1.0549216509709158, 'weight_class_1': 9.07501544070867, 'weight_class_2': 8.294424115773257}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:44,587] Trial 478 finished with value: 0.9474749346946595 and parameters: {'weight_class_0': 0.2634953916849391, 'weight_class_1': 9.441244319237295, 'weight_class_2': 7.601069839795969}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:44,627] Trial 480 finished with value: 0.9477932442353579 and parameters: {'weight_class_0': 0.3035440464850642, 'weight_class_1': 9.58233308198493, 'weight_class_2': 8.261139354151899}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:44,641] Trial 479 finished with value: 0.9479668308653538 and parameters: {'weight_class_0': 0.31933813786249904, 'weight_class_1': 9.54816819846206, 'weight_class_2': 8.095629465410955}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:44,643] Trial 481 finished with value: 0.9402658163902419 and parameters: {'weight_class_0': 2.3972680840485445, 'weight_class_1': 9.50172194529907, 'weight_class_2': 7.554150216205014}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:44,663] Trial 482 finished with value: 0.9475177217694797 and parameters: {'weight_class_0': 0.2697228290279596, 'weight_class_1': 9.473325781594035, 'weight_class_2': 7.541938222394332}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:44,683] Trial 483 finished with value: 0.9478981752264674 and parameters: {'weight_class_0': 0.29130011767160735, 'weight_class_1': 8.713044248066886, 'weight_class_2': 7.61194344168216}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:44,717] Trial 484 finished with value: 0.9473334636180688 and parameters: {'weight_class_0': 0.25765097613363985, 'weight_class_1': 9.536155374013543, 'weight_class_2': 7.5797686126088895}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:44,727] Trial 485 finished with value: 0.9483324574199692 and parameters: {'weight_class_0': 0.35091746757740405, 'weight_class_1': 9.528967076670666, 'weight_class_2': 7.572848047871006}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:44,746] Trial 486 finished with value: 0.9472675649700858 and parameters: {'weight_class_0': 0.26107838644597836, 'weight_class_1': 9.515433122476137, 'weight_class_2': 8.318237629198608}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  25%|█████████████████████████████████                                                                                                    | 497/2000 [00:09<00:26, 56.28it/s]

[I 2026-07-08 13:32:44,760] Trial 487 finished with value: 0.9472434527030235 and parameters: {'weight_class_0': 0.2509952394892506, 'weight_class_1': 9.52295653367461, 'weight_class_2': 7.592140730466293}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:44,761] Trial 488 finished with value: 0.9481773213655403 and parameters: {'weight_class_0': 0.3180216267995848, 'weight_class_1': 8.762052695676648, 'weight_class_2': 7.549683650440765}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:44,797] Trial 489 finished with value: 0.9475330522479849 and parameters: {'weight_class_0': 0.24779125679555924, 'weight_class_1': 8.233100069813194, 'weight_class_2': 7.534506640054808}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:44,798] Trial 490 finished with value: 0.9492030876354818 and parameters: {'weight_class_0': 0.6182633014443344, 'weight_class_1': 8.777825187333786, 'weight_class_2': 7.178264022251748}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:44,832] Trial 491 finished with value: 0.9491569122299371 and parameters: {'weight_class_0': 0.5935741142831712, 'weight_class_1': 8.251160166615035, 'weight_class_2': 7.1530317838661475}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:44,841] Trial 492 finished with value: 0.949149728082984 and parameters: {'weight_class_0': 0.5303751157775709, 'weight_class_1': 8.740093776699602, 'weight_class_2': 7.147727198022116}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:44,863] Trial 493 finished with value: 0.9492259752848434 and parameters: {'weight_class_0': 0.6272842301168302, 'weight_class_1': 8.357128735938277, 'weight_class_2': 7.080994592902906}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:44,882] Trial 494 finished with value: 0.949161602585009 and parameters: {'weight_class_0': 0.5978925607992377, 'weight_class_1': 8.17911001188935, 'weight_class_2': 7.186755870219766}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:44,898] Trial 495 finished with value: 0.9491331199106806 and parameters: {'weight_class_0': 0.5679105208737559, 'weight_class_1': 8.220933032955411, 'weight_class_2': 7.173761200136593}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:44,914] Trial 496 finished with value: 0.9491761530680894 and parameters: {'weight_class_0': 0.6188194373257899, 'weight_class_1': 8.194936584421251, 'weight_class_2': 7.139093646079039}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:44,965] Trial 497 finished with value: 0.9491799611099334 and parameters: {'weight_class_0': 0.6038924413097528, 'weight_class_1': 8.127690910315991, 'weight_class_2': 7.34121363201109}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  25%|█████████████████████████████████▊                                                                                                   | 509/2000 [00:09<00:27, 54.53it/s]

[I 2026-07-08 13:32:44,967] Trial 498 finished with value: 0.9491776684817129 and parameters: {'weight_class_0': 0.5883034702873433, 'weight_class_1': 8.225480164304784, 'weight_class_2': 7.154420943697993}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:44,981] Trial 499 finished with value: 0.9491589903791439 and parameters: {'weight_class_0': 0.5861071143517643, 'weight_class_1': 8.194621180304726, 'weight_class_2': 7.178068597266999}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:44,983] Trial 500 finished with value: 0.9491791809089154 and parameters: {'weight_class_0': 0.6056337220732794, 'weight_class_1': 8.580227902508264, 'weight_class_2': 7.1504698127348485}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,022] Trial 502 finished with value: 0.9491719485559371 and parameters: {'weight_class_0': 0.6874138270105333, 'weight_class_1': 8.563292546307089, 'weight_class_2': 7.242217483217712}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,028] Trial 501 finished with value: 0.9491836299076489 and parameters: {'weight_class_0': 0.6064109528013567, 'weight_class_1': 8.537084449798801, 'weight_class_2': 7.194165026496943}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,047] Trial 503 finished with value: 0.9484008995532854 and parameters: {'weight_class_0': 0.688596112321515, 'weight_class_1': 8.547044767418832, 'weight_class_2': 4.455368090449706}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,073] Trial 504 finished with value: 0.9489271895086945 and parameters: {'weight_class_0': 0.7709218112714711, 'weight_class_1': 8.597895608220284, 'weight_class_2': 6.753272918729775}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,085] Trial 505 finished with value: 0.9483322997790383 and parameters: {'weight_class_0': 0.7465948596468399, 'weight_class_1': 8.867707308172779, 'weight_class_2': 4.698589443316424}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,103] Trial 506 finished with value: 0.9487136843594924 and parameters: {'weight_class_0': 0.7695323061556816, 'weight_class_1': 8.454808365007692, 'weight_class_2': 6.025905933207785}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,134] Trial 507 finished with value: 0.9484545663062766 and parameters: {'weight_class_0': 0.706741781455229, 'weight_class_1': 8.580347680423738, 'weight_class_2': 4.633481204262899}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,146] Trial 508 finished with value: 0.8866535042684105 and parameters: {'weight_class_0': 5.043264244917066, 'weight_class_1': 8.575111845319217, 'weight_class_2': 4.075021681581288}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,172] Trial 509 finished with value: 0.9486687977990512 and parameters: {'weight_class_0': 0.7972623133412227, 'weight_class_1': 8.84675970906823, 'weight_class_2': 5.982468941604822}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  26%|██████████████████████████████████▋                                                                                                  | 521/2000 [00:09<00:26, 55.76it/s]

[I 2026-07-08 13:32:45,193] Trial 510 finished with value: 0.9477820392065097 and parameters: {'weight_class_0': 0.8175212746342708, 'weight_class_1': 8.58057602398672, 'weight_class_2': 4.479063776122047}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,211] Trial 511 finished with value: 0.9480039566540815 and parameters: {'weight_class_0': 0.8131477619041362, 'weight_class_1': 8.507621589104858, 'weight_class_2': 4.720541588765318}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,222] Trial 512 finished with value: 0.9485165305676008 and parameters: {'weight_class_0': 0.8355253054012169, 'weight_class_1': 8.765757938869596, 'weight_class_2': 5.989126160858126}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,243] Trial 513 finished with value: 0.9479312168214237 and parameters: {'weight_class_0': 0.7979419713098745, 'weight_class_1': 8.485399966482897, 'weight_class_2': 4.562374375956648}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,247] Trial 514 finished with value: 0.9488242635829224 and parameters: {'weight_class_0': 0.8488918595856029, 'weight_class_1': 8.725621403050328, 'weight_class_2': 6.900480692211493}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,269] Trial 515 finished with value: 0.9486023001961702 and parameters: {'weight_class_0': 0.9160885462424792, 'weight_class_1': 8.404162459066242, 'weight_class_2': 6.890108489645042}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,300] Trial 516 finished with value: 0.9462242395831914 and parameters: {'weight_class_0': 0.4442363328529466, 'weight_class_1': 1.9192828297956686, 'weight_class_2': 6.853062802932609}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,304] Trial 517 finished with value: 0.9490903721443931 and parameters: {'weight_class_0': 0.47315984626298413, 'weight_class_1': 8.825345863193624, 'weight_class_2': 6.926971918536392}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,317] Trial 518 finished with value: 0.9489450715457218 and parameters: {'weight_class_0': 0.4306287133917378, 'weight_class_1': 8.85619574656505, 'weight_class_2': 6.932354241463715}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,335] Trial 519 finished with value: 0.9486104344382155 and parameters: {'weight_class_0': 0.9157092941136438, 'weight_class_1': 8.930244618514122, 'weight_class_2': 6.831120365436804}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,356] Trial 520 finished with value: 0.949086835528226 and parameters: {'weight_class_0': 0.4682568914672259, 'weight_class_1': 8.860591187993357, 'weight_class_2': 6.810476102022999}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,370] Trial 521 finished with value: 0.9489946228097565 and parameters: {'weight_class_0': 0.43247606489067336, 'weight_class_1': 8.404576827953862, 'weight_class_2': 6.860940714770309}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  27%|███████████████████████████████████▍                                                                                                 | 533/2000 [00:09<00:27, 54.06it/s]

[I 2026-07-08 13:32:45,409] Trial 522 finished with value: 0.9490845150024283 and parameters: {'weight_class_0': 0.4665894386428635, 'weight_class_1': 8.319696043883344, 'weight_class_2': 6.853492234280595}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,412] Trial 523 finished with value: 0.945701175688399 and parameters: {'weight_class_0': 1.4765478528861626, 'weight_class_1': 7.990038127103672, 'weight_class_2': 6.950926795553858}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,446] Trial 524 finished with value: 0.9490533483259829 and parameters: {'weight_class_0': 0.45429224738958757, 'weight_class_1': 7.979957660369873, 'weight_class_2': 6.806966761460753}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,460] Trial 525 finished with value: 0.9489976299927193 and parameters: {'weight_class_0': 0.41018236754979603, 'weight_class_1': 7.9419662926839365, 'weight_class_2': 6.403536036357112}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,469] Trial 526 finished with value: 0.9491047421293897 and parameters: {'weight_class_0': 0.47221279718345754, 'weight_class_1': 7.956237826442445, 'weight_class_2': 6.489566890293113}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,503] Trial 527 finished with value: 0.9491487341843 and parameters: {'weight_class_0': 0.48101714949493374, 'weight_class_1': 7.9389173858696, 'weight_class_2': 6.3945423343215575}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,517] Trial 528 finished with value: 0.9453276567336002 and parameters: {'weight_class_0': 1.4322503476105808, 'weight_class_1': 7.873987749022393, 'weight_class_2': 6.355091549230063}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,521] Trial 529 finished with value: 0.945403373371492 and parameters: {'weight_class_0': 1.415407481314542, 'weight_class_1': 7.87689085736692, 'weight_class_2': 6.301060826953955}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,544] Trial 530 finished with value: 0.9491103795598206 and parameters: {'weight_class_0': 0.47436485372978177, 'weight_class_1': 7.904572625774151, 'weight_class_2': 6.5417748631391515}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,572] Trial 532 finished with value: 0.9447389890695609 and parameters: {'weight_class_0': 1.532939146325512, 'weight_class_1': 7.917295900636224, 'weight_class_2': 6.415059808043447}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,578] Trial 531 finished with value: 0.9459491577393537 and parameters: {'weight_class_0': 0.16580206630928235, 'weight_class_1': 8.354312046059565, 'weight_class_2': 6.515770171107782}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,600] Trial 533 finished with value: 0.9475159030182142 and parameters: {'weight_class_0': 0.2254861235498043, 'weight_class_1': 7.900795422231602, 'weight_class_2': 6.472382727299274}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:32:45,642] Trial 534 finished with value: 0.948617951169776 and parameters: {'weight_class_0': 0.9687269853255266, 'weight_class_1': 9.225586339831475, 'weight_class_2': 7.349531297585247}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,680] Trial 535 finished with value: 0.9468796779964589 and parameters: {'weight_class_0': 0.2205642409708749, 'weight_class_1': 9.21879974964878, 'weight_class_2': 7.291916784750221}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,695] Trial 536 finished with value: 0.9467199200550874 and parameters: {'weight_class_0': 0.18765733090869802, 'weight_class_1': 7.523889763020986, 'weight_class_2': 7.343202332852675}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,705] Trial 537 finished with value: 0.9447406599316691 and parameters: {'weight_class_0': 0.15454246291657753, 'weight_class_1': 9.273208627836468, 'weight_class_2': 7.33175575873353}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,726] Trial 538 finished with value: 0.944064625421675 and parameters: {'weight_class_0': 0.1311846491399563, 'weight_class_1': 8.351856048194424, 'weight_class_2': 7.124948556538912}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,751] Trial 540 finished with value: 0.9485166801073491 and parameters: {'weight_class_0': 0.9639428394590879, 'weight_class_1': 8.377795521476624, 'weight_class_2': 7.32435833858197}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,753] Trial 539 finished with value: 0.9454991726525095 and parameters: {'weight_class_0': 0.16967880771619548, 'weight_class_1': 9.198100525391576, 'weight_class_2': 7.394225089431325}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,771] Trial 541 finished with value: 0.9464935988978705 and parameters: {'weight_class_0': 0.17878955126111812, 'weight_class_1': 7.561253398860824, 'weight_class_2': 7.346770763970126}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,783] Trial 542 finished with value: 0.9456622039700006 and parameters: {'weight_class_0': 0.17475377019987376, 'weight_class_1': 9.197578656158566, 'weight_class_2': 7.3525962293700395}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,829] Trial 543 finished with value: 0.9486236215941958 and parameters: {'weight_class_0': 0.9617798962993537, 'weight_class_1': 9.268741770242517, 'weight_class_2': 7.331484574912033}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,854] Trial 545 finished with value: 0.9467708750444928 and parameters: {'weight_class_0': 0.19076717594500703, 'weight_class_1': 7.559551394709202, 'weight_class_2': 7.364519243402359}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  28%|████████████████████████████████████▊                                                                                                | 554/2000 [00:10<00:28, 50.21it/s]

[I 2026-07-08 13:32:45,856] Trial 544 finished with value: 0.9485995475203305 and parameters: {'weight_class_0': 0.9798684373185309, 'weight_class_1': 9.27974230735506, 'weight_class_2': 7.355866539482323}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,887] Trial 546 finished with value: 0.9484934357768836 and parameters: {'weight_class_0': 0.9628851894003851, 'weight_class_1': 8.060362075066688, 'weight_class_2': 7.321009691639368}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,893] Trial 547 finished with value: 0.9485176453271084 and parameters: {'weight_class_0': 0.9555378216223077, 'weight_class_1': 8.354969492797688, 'weight_class_2': 7.380594489690133}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,931] Trial 548 finished with value: 0.949173811308674 and parameters: {'weight_class_0': 0.6577977859950901, 'weight_class_1': 8.077005300778545, 'weight_class_2': 7.115153710056631}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,947] Trial 549 finished with value: 0.8636728973378741 and parameters: {'weight_class_0': 9.982120270648092, 'weight_class_1': 8.061981482496943, 'weight_class_2': 7.028994808331219}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,975] Trial 550 finished with value: 0.9491528530785779 and parameters: {'weight_class_0': 0.6608858211790294, 'weight_class_1': 8.147257513954191, 'weight_class_2': 7.7699253476342784}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:45,997] Trial 551 finished with value: 0.9491967359586985 and parameters: {'weight_class_0': 0.6345165662429343, 'weight_class_1': 8.215516249265756, 'weight_class_2': 7.0835809499107}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,030] Trial 552 finished with value: 0.9491393643865562 and parameters: {'weight_class_0': 0.6464949431610783, 'weight_class_1': 8.159673382697784, 'weight_class_2': 7.759845121567917}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,049] Trial 554 finished with value: 0.878670780822262 and parameters: {'weight_class_0': 0.6628887020358966, 'weight_class_1': 8.096351040132197, 'weight_class_2': 0.053595289861448236}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,057] Trial 553 finished with value: 0.9491696943882783 and parameters: {'weight_class_0': 0.6766394769885542, 'weight_class_1': 8.11643234626811, 'weight_class_2': 7.761035639789437}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  28%|█████████████████████████████████████▌                                                                                               | 565/2000 [00:10<00:29, 49.36it/s]

[I 2026-07-08 13:32:46,073] Trial 555 finished with value: 0.9491422976015053 and parameters: {'weight_class_0': 0.6650755793896923, 'weight_class_1': 8.10378056939476, 'weight_class_2': 7.076371557946293}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,100] Trial 556 finished with value: 0.9491434393744456 and parameters: {'weight_class_0': 0.6563941244636368, 'weight_class_1': 8.115179489225904, 'weight_class_2': 7.7445347280876655}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,124] Trial 557 finished with value: 0.9491663094267023 and parameters: {'weight_class_0': 0.674647778184414, 'weight_class_1': 8.681194700358867, 'weight_class_2': 7.06626610428946}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,168] Trial 559 finished with value: 0.9491624504728086 and parameters: {'weight_class_0': 0.6264954771325868, 'weight_class_1': 8.240717128784548, 'weight_class_2': 7.827756915984155}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,173] Trial 558 finished with value: 0.9066506407924293 and parameters: {'weight_class_0': 0.6931826403667856, 'weight_class_1': 0.4546177355735912, 'weight_class_2': 7.731055237913302}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,186] Trial 560 finished with value: 0.9492077563124374 and parameters: {'weight_class_0': 0.6772160141865785, 'weight_class_1': 8.200945036632955, 'weight_class_2': 7.727776100471861}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,198] Trial 561 finished with value: 0.9491740024030539 and parameters: {'weight_class_0': 0.6277754257916772, 'weight_class_1': 8.603842980713905, 'weight_class_2': 7.72285326921908}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,215] Trial 563 finished with value: 0.9491317157533778 and parameters: {'weight_class_0': 0.6480120330568045, 'weight_class_1': 8.663450085839251, 'weight_class_2': 6.673141821046322}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,220] Trial 562 finished with value: 0.9492381818985178 and parameters: {'weight_class_0': 0.6496537274235641, 'weight_class_1': 8.657057440751593, 'weight_class_2': 7.075460348418268}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,248] Trial 565 finished with value: 0.9475223128722982 and parameters: {'weight_class_0': 1.2166565470852806, 'weight_class_1': 8.69754853096926, 'weight_class_2': 7.059596726564667}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,252] Trial 564 finished with value: 0.9490769112008085 and parameters: {'weight_class_0': 0.7339611394404347, 'weight_class_1': 8.69035442582861, 'weight_class_2': 7.017456880972186}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:32:46,295] Trial 566 finished with value: 0.9474248002808746 and parameters: {'weight_class_0': 1.2007356068947137, 'weight_class_1': 8.690561744730768, 'weight_class_2': 6.710822551608961}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,325] Trial 567 finished with value: 0.9470477267995615 and parameters: {'weight_class_0': 1.2353012546559685, 'weight_class_1': 8.367069944240516, 'weight_class_2': 6.659024132834092}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,340] Trial 568 finished with value: 0.9470473422541922 and parameters: {'weight_class_0': 1.2456837819038937, 'weight_class_1': 8.39894175205436, 'weight_class_2': 6.687885313644693}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,364] Trial 569 finished with value: 0.9474605250280467 and parameters: {'weight_class_0': 1.1740356418053541, 'weight_class_1': 8.391721114419143, 'weight_class_2': 6.715963236593734}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,407] Trial 570 finished with value: 0.9404727645637418 and parameters: {'weight_class_0': 1.2029073211205794, 'weight_class_1': 3.2639439412602353, 'weight_class_2': 7.5455826860325805}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,413] Trial 571 finished with value: 0.9475870499943676 and parameters: {'weight_class_0': 1.2152896700255051, 'weight_class_1': 8.32752133503606, 'weight_class_2': 7.53771853729326}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,420] Trial 572 finished with value: 0.9469744305535782 and parameters: {'weight_class_0': 1.2548824115942614, 'weight_class_1': 8.423275600873204, 'weight_class_2': 6.611087221039476}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,436] Trial 573 finished with value: 0.9467082110905203 and parameters: {'weight_class_0': 1.3070520997847581, 'weight_class_1': 8.439682746138427, 'weight_class_2': 6.628309766873372}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,471] Trial 574 finished with value: 0.9470557047017906 and parameters: {'weight_class_0': 1.2367580061613266, 'weight_class_1': 8.391365092259328, 'weight_class_2': 6.6221612070999445}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,483] Trial 575 finished with value: 0.9489670736898415 and parameters: {'weight_class_0': 0.4214281086900099, 'weight_class_1': 8.431365590556549, 'weight_class_2': 6.616598391191446}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:32:46,510] Trial 577 finished with value: 0.9488036069559568 and parameters: {'weight_class_0': 0.40666390667328317, 'weight_class_1': 8.313443901980946, 'weight_class_2': 7.449463203392729}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,520] Trial 576 finished with value: 0.9489485354814926 and parameters: {'weight_class_0': 0.4005258011205963, 'weight_class_1': 8.446981680506985, 'weight_class_2': 6.176280146719771}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,544] Trial 578 finished with value: 0.9487046770771909 and parameters: {'weight_class_0': 0.3969142871931619, 'weight_class_1': 8.447091135279688, 'weight_class_2': 7.582691525736696}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,558] Trial 579 finished with value: 0.8935749819027069 and parameters: {'weight_class_0': 6.133063785213244, 'weight_class_1': 8.474114665425882, 'weight_class_2': 7.491818417060976}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,584] Trial 580 finished with value: 0.9488101680177378 and parameters: {'weight_class_0': 0.9106477660281029, 'weight_class_1': 8.468729141008323, 'weight_class_2': 7.5203615571925795}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,616] Trial 582 finished with value: 0.949037865485876 and parameters: {'weight_class_0': 0.39581830600090395, 'weight_class_1': 8.839421375268342, 'weight_class_2': 5.364010563339222}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,620] Trial 581 finished with value: 0.9486263525484979 and parameters: {'weight_class_0': 0.3821161674333567, 'weight_class_1': 8.508950966873178, 'weight_class_2': 7.5066855409732876}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,649] Trial 584 finished with value: 0.9484833871891049 and parameters: {'weight_class_0': 0.40216310571938546, 'weight_class_1': 8.969944441474535, 'weight_class_2': 8.797079770328509}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,669] Trial 583 finished with value: 0.8700256708025867 and parameters: {'weight_class_0': 9.14455383293662, 'weight_class_1': 8.880144075395274, 'weight_class_2': 7.1573380306258105}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,697] Trial 585 finished with value: 0.9488747148933983 and parameters: {'weight_class_0': 0.8705622387959409, 'weight_class_1': 8.913005623724514, 'weight_class_2': 7.171609422726515}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:32:46,725] Trial 586 finished with value: 0.8680270778232199 and parameters: {'weight_class_0': 9.007441650682313, 'weight_class_1': 8.999778420834984, 'weight_class_2': 6.193286386507307}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,740] Trial 587 finished with value: 0.8847782879982398 and parameters: {'weight_class_0': 6.518149747545076, 'weight_class_1': 7.637666526815068, 'weight_class_2': 7.110779895919648}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,781] Trial 589 finished with value: 0.9487612421824526 and parameters: {'weight_class_0': 0.8849373380155698, 'weight_class_1': 8.931730978102266, 'weight_class_2': 7.0849492750699}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,789] Trial 588 finished with value: 0.9488506366974964 and parameters: {'weight_class_0': 0.8917598444812767, 'weight_class_1': 7.711453159891624, 'weight_class_2': 8.734790046415522}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,793] Trial 590 finished with value: 0.9487892314039864 and parameters: {'weight_class_0': 0.8792973726515886, 'weight_class_1': 8.982494211250645, 'weight_class_2': 7.125152652142522}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,831] Trial 591 finished with value: 0.9488516990358503 and parameters: {'weight_class_0': 0.9655016256983066, 'weight_class_1': 8.935591517208339, 'weight_class_2': 8.76630791847143}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,854] Trial 592 finished with value: 0.9479404203282944 and parameters: {'weight_class_0': 0.9706017685682025, 'weight_class_1': 8.90237462979425, 'weight_class_2': 5.604474716982965}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,873] Trial 594 finished with value: 0.9483518150987734 and parameters: {'weight_class_0': 0.8518121687873981, 'weight_class_1': 8.219872037091047, 'weight_class_2': 5.591660096131023}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,886] Trial 595 finished with value: 0.9485285599036654 and parameters: {'weight_class_0': 0.9174553172276655, 'weight_class_1': 7.710571104111705, 'weight_class_2': 7.113153878415999}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,890] Trial 593 finished with value: 0.9488473191553375 and parameters: {'weight_class_0': 0.8435620568614186, 'weight_class_1': 7.856378253020156, 'weight_class_2': 7.075993783441783}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:32:46,932] Trial 596 finished with value: 0.948195316436821 and parameters: {'weight_class_0': 0.8655321610417647, 'weight_class_1': 7.703307880537999, 'weight_class_2': 5.616527189245668}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,939] Trial 597 finished with value: 0.948190291181558 and parameters: {'weight_class_0': 0.8672874142034377, 'weight_class_1': 7.768249376938662, 'weight_class_2': 5.511496420409029}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,974] Trial 599 finished with value: 0.9465458521042934 and parameters: {'weight_class_0': 0.8558563694011638, 'weight_class_1': 7.750172521770331, 'weight_class_2': 3.7327328544757057}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:46,976] Trial 598 finished with value: 0.9487617582877381 and parameters: {'weight_class_0': 0.8887537253791568, 'weight_class_1': 7.816827132973832, 'weight_class_2': 8.243272914793717}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,013] Trial 601 finished with value: 0.8820652419821505 and parameters: {'weight_class_0': 7.504800076787932, 'weight_class_1': 7.824233402037084, 'weight_class_2': 8.260732526828585}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,022] Trial 600 finished with value: 0.9491832234501109 and parameters: {'weight_class_0': 0.5165396971871219, 'weight_class_1': 7.816930731444258, 'weight_class_2': 5.542929985667268}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,057] Trial 603 finished with value: 0.9489644231213591 and parameters: {'weight_class_0': 0.5127052931608245, 'weight_class_1': 7.777601547570038, 'weight_class_2': 8.217911172788448}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,067] Trial 602 finished with value: 0.9484333883361873 and parameters: {'weight_class_0': 0.5643335647260088, 'weight_class_1': 7.766249268530034, 'weight_class_2': 3.6274879829398374}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,091] Trial 604 finished with value: 0.9482644363737579 and parameters: {'weight_class_0': 0.5274260242279342, 'weight_class_1': 8.692575300432775, 'weight_class_2': 3.197095937610124}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,120] Trial 606 finished with value: 0.9489976976461891 and parameters: {'weight_class_0': 0.5311564900997915, 'weight_class_1': 8.66560917393095, 'weight_class_2': 8.2755352696054}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,132] Trial 605 finished with value: 0.9489903499607313 and parameters: {'weight_class_0': 0.5189868488771552, 'weight_class_1': 8.628681783917314, 'weight_class_2': 8.225216392929028}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  31%|████████████████████████████████████████▉                                                                                            | 616/2000 [00:11<00:27, 49.60it/s]

[I 2026-07-08 13:32:47,151] Trial 607 finished with value: 0.9490996425233859 and parameters: {'weight_class_0': 0.5615639565207677, 'weight_class_1': 8.67775190890028, 'weight_class_2': 8.167646245525352}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,171] Trial 608 finished with value: 0.9489715971372602 and parameters: {'weight_class_0': 0.5197889091588815, 'weight_class_1': 8.047624269521108, 'weight_class_2': 8.290767183398383}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,198] Trial 609 finished with value: 0.9490757873463949 and parameters: {'weight_class_0': 0.5602987866686686, 'weight_class_1': 8.053879051193345, 'weight_class_2': 7.803774966758228}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,215] Trial 610 finished with value: 0.9490367848670139 and parameters: {'weight_class_0': 0.5133400357929165, 'weight_class_1': 8.67604511539239, 'weight_class_2': 7.847594107450535}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,221] Trial 611 finished with value: 0.9490647326700244 and parameters: {'weight_class_0': 0.5414062560830296, 'weight_class_1': 8.199421211851847, 'weight_class_2': 7.907793298137697}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,253] Trial 612 finished with value: 0.9226737422265908 and parameters: {'weight_class_0': 3.944208000787227, 'weight_class_1': 8.677727529131129, 'weight_class_2': 7.935085818726622}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,275] Trial 613 finished with value: 0.949064411393576 and parameters: {'weight_class_0': 0.5231218213635087, 'weight_class_1': 8.050247173838118, 'weight_class_2': 7.771156332026009}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,283] Trial 614 finished with value: 0.9490596662969145 and parameters: {'weight_class_0': 0.5243284895788319, 'weight_class_1': 8.642212490048404, 'weight_class_2': 7.9416897133156805}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,307] Trial 615 finished with value: 0.9490738780376976 and parameters: {'weight_class_0': 0.5344381505264334, 'weight_class_1': 8.03643166604285, 'weight_class_2': 7.89573833349094}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,332] Trial 616 finished with value: 0.9488332275355212 and parameters: {'weight_class_0': 0.3550750330672234, 'weight_class_1': 4.1490480947069805, 'weight_class_2': 5.86526887377059}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  31%|█████████████████████████████████████████▊                                                                                           | 629/2000 [00:11<00:27, 49.99it/s]

[I 2026-07-08 13:32:47,373] Trial 618 finished with value: 0.9480982101774632 and parameters: {'weight_class_0': 0.3022674109100741, 'weight_class_1': 8.068201913176583, 'weight_class_2': 7.765689395106759}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,378] Trial 617 finished with value: 0.9480381730893055 and parameters: {'weight_class_0': 0.29808074369216836, 'weight_class_1': 8.225935316831679, 'weight_class_2': 7.864534413120704}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,394] Trial 619 finished with value: 0.9484043386941942 and parameters: {'weight_class_0': 0.35374639223257043, 'weight_class_1': 8.232936278607022, 'weight_class_2': 7.936076249176859}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,420] Trial 621 finished with value: 0.9482403833727352 and parameters: {'weight_class_0': 0.2769212424231736, 'weight_class_1': 4.391402452664901, 'weight_class_2': 6.897143325780051}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,439] Trial 620 finished with value: 0.9481105285821873 and parameters: {'weight_class_0': 0.3105087108861713, 'weight_class_1': 8.222161668709273, 'weight_class_2': 7.858976773366869}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,448] Trial 622 finished with value: 0.9490287889101495 and parameters: {'weight_class_0': 0.7324986158374336, 'weight_class_1': 8.24036369452953, 'weight_class_2': 6.926724492573214}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,482] Trial 623 finished with value: 0.9478141316484293 and parameters: {'weight_class_0': 0.25825995353961667, 'weight_class_1': 8.234367088576175, 'weight_class_2': 6.9438874539273865}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,485] Trial 625 finished with value: 0.9481741692947425 and parameters: {'weight_class_0': 0.29464791204219587, 'weight_class_1': 8.239827258512152, 'weight_class_2': 6.961669789389336}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,491] Trial 624 finished with value: 0.9468054543127268 and parameters: {'weight_class_0': 0.19801880285494805, 'weight_class_1': 8.26737289002705, 'weight_class_2': 6.9590491215543615}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,505] Trial 626 finished with value: 0.9480080301135185 and parameters: {'weight_class_0': 0.28936813583780724, 'weight_class_1': 8.245313548517206, 'weight_class_2': 7.276950369564157}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,513] Trial 628 finished with value: 0.9478014799395211 and parameters: {'weight_class_0': 0.2565130418069925, 'weight_class_1': 8.256418449637927, 'weight_class_2': 6.88786999834029}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,525] Trial 627 finished with value: 0.94778152475222 and parameters: {'weight_class_0': 0.2650539718230929, 'weight_class_1': 8.20080819879968, 'weight_class_2': 7.610068870699554}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,576] Trial 630 finished with value: 0.9489022305053414 and parameters: {'weight_class_0': 0.7603535073748594, 'weight_class_1': 8.238388056797406, 'weight_class_2': 6.847668932693459}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:32:47,606] Trial 632 finished with value: 0.9485007257502236 and parameters: {'weight_class_0': 0.7526910651248095, 'weight_class_1': 5.435675284895202, 'weight_class_2': 7.245654276890221}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,610] Trial 631 finished with value: 0.6573519344917715 and parameters: {'weight_class_0': 0.0002225119909029516, 'weight_class_1': 8.281277402769051, 'weight_class_2': 7.474405088894374}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,612] Trial 629 finished with value: 0.9489426587583702 and parameters: {'weight_class_0': 0.7596779876472601, 'weight_class_1': 8.271203653490055, 'weight_class_2': 6.922770271360598}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,632] Trial 633 finished with value: 0.9490427197727548 and parameters: {'weight_class_0': 0.7537762781831019, 'weight_class_1': 8.33520697859082, 'weight_class_2': 7.562005780260427}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,663] Trial 634 finished with value: 0.9481971458538673 and parameters: {'weight_class_0': 1.066297147105653, 'weight_class_1': 8.260396119949085, 'weight_class_2': 7.253552753265298}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,706] Trial 635 finished with value: 0.9490405373395768 and parameters: {'weight_class_0': 0.747958956608652, 'weight_class_1': 8.502034844904344, 'weight_class_2': 7.553121644567947}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,709] Trial 636 finished with value: 0.662451603468959 and parameters: {'weight_class_0': 0.003996033546092126, 'weight_class_1': 7.980296243582529, 'weight_class_2': 2.67474371523373}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,728] Trial 637 finished with value: 0.949029027239041 and parameters: {'weight_class_0': 0.7478874245695933, 'weight_class_1': 8.587515480104921, 'weight_class_2': 7.501141006300911}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,756] Trial 638 finished with value: 0.9483750017740401 and parameters: {'weight_class_0': 0.7350924942969826, 'weight_class_1': 5.14973539969799, 'weight_class_2': 7.351538432209799}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,762] Trial 639 finished with value: 0.9488643953219844 and parameters: {'weight_class_0': 0.7750585691328115, 'weight_class_1': 6.668015739279369, 'weight_class_2': 7.471971041920826}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  32%|███████████████████████████████████████████▏                                                                                         | 650/2000 [00:12<00:25, 52.68it/s]

[I 2026-07-08 13:32:47,786] Trial 640 finished with value: 0.9484120018627878 and parameters: {'weight_class_0': 1.0824349541325267, 'weight_class_1': 9.99291692950374, 'weight_class_2': 7.479777016355472}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,796] Trial 641 finished with value: 0.9480890835193082 and parameters: {'weight_class_0': 1.0715276869794952, 'weight_class_1': 7.950399727652127, 'weight_class_2': 7.431755313286784}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,836] Trial 642 finished with value: 0.9481473336243432 and parameters: {'weight_class_0': 1.0286823046049998, 'weight_class_1': 7.545632804517609, 'weight_class_2': 7.417309010498426}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,848] Trial 643 finished with value: 0.9481513776587492 and parameters: {'weight_class_0': 1.0455776331174695, 'weight_class_1': 7.955721113396226, 'weight_class_2': 7.246843737999523}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,854] Trial 645 finished with value: 0.9481589004041776 and parameters: {'weight_class_0': 1.053388272479983, 'weight_class_1': 7.955245133566762, 'weight_class_2': 7.478171381409089}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,869] Trial 644 finished with value: 0.94838223972152 and parameters: {'weight_class_0': 0.9751455156759696, 'weight_class_1': 7.5400509467246035, 'weight_class_2': 7.419540953133435}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,875] Trial 646 finished with value: 0.9470738056352266 and parameters: {'weight_class_0': 1.024260979034584, 'weight_class_1': 7.9611510520167945, 'weight_class_2': 5.061098106626334}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,917] Trial 647 finished with value: 0.9467310799217835 and parameters: {'weight_class_0': 1.09902951298769, 'weight_class_1': 8.52683870391881, 'weight_class_2': 5.060288820975597}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,956] Trial 649 finished with value: 0.9483531270644731 and parameters: {'weight_class_0': 1.113011768046002, 'weight_class_1': 7.946158058785168, 'weight_class_2': 9.18637547229984}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,962] Trial 648 finished with value: 0.947282147983841 and parameters: {'weight_class_0': 0.9917757892598029, 'weight_class_1': 8.010870989959976, 'weight_class_2': 5.025779858654886}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:47,993] Trial 650 finished with value: 0.9469185008430848 and parameters: {'weight_class_0': 1.0502910982404061, 'weight_class_1': 7.9861446900378255, 'weight_class_2': 5.030879825268558}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  33%|███████████████████████████████████████████▉                                                                                         | 661/2000 [00:12<00:26, 50.35it/s]

[I 2026-07-08 13:32:48,011] Trial 651 finished with value: 0.9409211739059127 and parameters: {'weight_class_0': 2.122246098387652, 'weight_class_1': 7.992504210947107, 'weight_class_2': 7.2589907997361545}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,036] Trial 652 finished with value: 0.945201977956275 and parameters: {'weight_class_0': 1.6958169080486527, 'weight_class_1': 9.704301033879112, 'weight_class_2': 7.185123012401317}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,056] Trial 653 finished with value: 0.9489139881865287 and parameters: {'weight_class_0': 0.6627297372526773, 'weight_class_1': 9.707554279096096, 'weight_class_2': 5.362077087859874}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,086] Trial 655 finished with value: 0.9492101241060582 and parameters: {'weight_class_0': 0.665445931926161, 'weight_class_1': 9.693720914563258, 'weight_class_2': 7.190167472789295}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,095] Trial 654 finished with value: 0.9491366619649609 and parameters: {'weight_class_0': 0.6254503981743986, 'weight_class_1': 9.700641477260135, 'weight_class_2': 7.672818545460443}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,118] Trial 656 finished with value: 0.9491391246387915 and parameters: {'weight_class_0': 0.6147006976447904, 'weight_class_1': 8.478802605115721, 'weight_class_2': 5.903070730649592}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,138] Trial 657 finished with value: 0.9492096976281824 and parameters: {'weight_class_0': 0.6857901435637851, 'weight_class_1': 9.716731038729815, 'weight_class_2': 7.666897125431014}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,162] Trial 658 finished with value: 0.9492073054422411 and parameters: {'weight_class_0': 0.6698219898600948, 'weight_class_1': 9.656222930733433, 'weight_class_2': 7.17977852114507}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,182] Trial 659 finished with value: 0.9492069269107395 and parameters: {'weight_class_0': 0.670729632332404, 'weight_class_1': 9.680678802352004, 'weight_class_2': 7.228212365055252}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,209] Trial 660 finished with value: 0.9430787754213918 and parameters: {'weight_class_0': 2.115578312302631, 'weight_class_1': 9.785277507429843, 'weight_class_2': 7.687640503866395}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,227] Trial 661 finished with value: 0.9489266035038404 and parameters: {'weight_class_0': 0.6624097118889695, 'weight_class_1': 9.786966910416398, 'weight_class_2': 5.319477686221283}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  34%|████████████████████████████████████████████▌                                                                                        | 671/2000 [00:12<00:28, 46.94it/s]

[I 2026-07-08 13:32:48,243] Trial 662 finished with value: 0.9491379469679581 and parameters: {'weight_class_0': 0.6440440094613774, 'weight_class_1': 9.660563360859614, 'weight_class_2': 7.636998325422728}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,261] Trial 663 finished with value: 0.948930313789564 and parameters: {'weight_class_0': 0.6710160579526603, 'weight_class_1': 9.399468158446219, 'weight_class_2': 5.378041403587098}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,273] Trial 664 finished with value: 0.9491709198206383 and parameters: {'weight_class_0': 0.6270888749665928, 'weight_class_1': 8.517292324346139, 'weight_class_2': 7.664213332270407}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,298] Trial 665 finished with value: 0.9489703614705857 and parameters: {'weight_class_0': 0.7434616090664221, 'weight_class_1': 9.400856950151065, 'weight_class_2': 6.215885781039034}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,355] Trial 667 finished with value: 0.9487483201969806 and parameters: {'weight_class_0': 0.4204974967011819, 'weight_class_1': 9.426963819826403, 'weight_class_2': 7.662505786233638}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,368] Trial 666 finished with value: 0.9490143773753736 and parameters: {'weight_class_0': 0.7667302981055084, 'weight_class_1': 9.978310417414566, 'weight_class_2': 6.720844295291652}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,374] Trial 668 finished with value: 0.9490378409728747 and parameters: {'weight_class_0': 0.7429727235135153, 'weight_class_1': 9.599512739225927, 'weight_class_2': 6.795884444978787}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,384] Trial 670 finished with value: 0.946476169699138 and parameters: {'weight_class_0': 1.4468834673129902, 'weight_class_1': 9.312307098318318, 'weight_class_2': 7.092834404390035}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,387] Trial 669 finished with value: 0.9490122666023394 and parameters: {'weight_class_0': 0.7576471252560646, 'weight_class_1': 9.374990599506345, 'weight_class_2': 7.011313140362987}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,414] Trial 671 finished with value: 0.948975279928414 and parameters: {'weight_class_0': 0.7922586142149218, 'weight_class_1': 9.351505607834099, 'weight_class_2': 6.801472502505973}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  34%|█████████████████████████████████████████████▎                                                                                       | 682/2000 [00:12<00:25, 51.01it/s]

[I 2026-07-08 13:32:48,459] Trial 673 finished with value: 0.9460015361245252 and parameters: {'weight_class_0': 1.4829365039205427, 'weight_class_1': 9.400429305326082, 'weight_class_2': 6.695359489393491}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,468] Trial 672 finished with value: 0.9489363856445953 and parameters: {'weight_class_0': 0.8109027203167125, 'weight_class_1': 9.363470560816015, 'weight_class_2': 6.795689835571493}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,481] Trial 674 finished with value: 0.948922426576023 and parameters: {'weight_class_0': 0.8150303688640003, 'weight_class_1': 9.299603461694561, 'weight_class_2': 6.807995636592062}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,494] Trial 675 finished with value: 0.9487188798867043 and parameters: {'weight_class_0': 0.856159024969644, 'weight_class_1': 9.365504052589635, 'weight_class_2': 6.768449054648522}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,510] Trial 676 finished with value: 0.9487719338887731 and parameters: {'weight_class_0': 0.8504807430951139, 'weight_class_1': 9.475257873550765, 'weight_class_2': 6.748259425654246}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,529] Trial 677 finished with value: 0.9488009518045805 and parameters: {'weight_class_0': 0.8456332266775309, 'weight_class_1': 9.393410840329866, 'weight_class_2': 6.772596733075142}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,561] Trial 678 finished with value: 0.9487753427412523 and parameters: {'weight_class_0': 0.8829337125152471, 'weight_class_1': 9.568683532657449, 'weight_class_2': 7.094369753218676}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,598] Trial 679 finished with value: 0.928145998194914 and parameters: {'weight_class_0': 3.4002441574820805, 'weight_class_1': 9.572050164665194, 'weight_class_2': 7.098081428272864}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,618] Trial 680 finished with value: 0.9488725274666052 and parameters: {'weight_class_0': 0.8712770628831275, 'weight_class_1': 9.60745941262871, 'weight_class_2': 7.0750940249712775}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,630] Trial 681 finished with value: 0.9488193495072471 and parameters: {'weight_class_0': 0.4286114981181457, 'weight_class_1': 9.651963601839533, 'weight_class_2': 7.120456019835985}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,647] Trial 682 finished with value: 0.9487809046694334 and parameters: {'weight_class_0': 0.880967689539718, 'weight_class_1': 9.556636492658823, 'weight_class_2': 7.079229011861611}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  35%|██████████████████████████████████████████████                                                                                       | 693/2000 [00:13<00:25, 50.62it/s]

[I 2026-07-08 13:32:48,664] Trial 683 finished with value: 0.9488664527207016 and parameters: {'weight_class_0': 0.43008351768214403, 'weight_class_1': 9.61094775124792, 'weight_class_2': 7.067894349313726}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,679] Trial 685 finished with value: 0.9488021341867025 and parameters: {'weight_class_0': 0.42806617858083074, 'weight_class_1': 9.783195205214147, 'weight_class_2': 7.1305251236008305}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,689] Trial 684 finished with value: 0.9487787838734616 and parameters: {'weight_class_0': 0.4148815877914491, 'weight_class_1': 9.66373233064506, 'weight_class_2': 7.105339683174847}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,737] Trial 687 finished with value: 0.9487311284589491 and parameters: {'weight_class_0': 0.4033981421215169, 'weight_class_1': 9.796171658795584, 'weight_class_2': 7.1393995176677265}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,743] Trial 686 finished with value: 0.948732695422148 and parameters: {'weight_class_0': 0.4040881708991567, 'weight_class_1': 9.762633766831339, 'weight_class_2': 7.087416784097413}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,752] Trial 688 finished with value: 0.9488594202978246 and parameters: {'weight_class_0': 0.4387621589337781, 'weight_class_1': 9.802998389502864, 'weight_class_2': 7.126141095833182}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,774] Trial 689 finished with value: 0.9487654324594001 and parameters: {'weight_class_0': 0.4210817858042439, 'weight_class_1': 9.83563689044092, 'weight_class_2': 7.239716601816845}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,811] Trial 690 finished with value: 0.9488602648908128 and parameters: {'weight_class_0': 0.4405494458317738, 'weight_class_1': 9.858652798235413, 'weight_class_2': 7.24658204705413}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,832] Trial 691 finished with value: 0.9487696506363207 and parameters: {'weight_class_0': 0.42750785711457906, 'weight_class_1': 9.99281059646166, 'weight_class_2': 7.249099846646026}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,834] Trial 692 finished with value: 0.9487363075405649 and parameters: {'weight_class_0': 0.41341357583441074, 'weight_class_1': 9.885456408247055, 'weight_class_2': 7.2983263667999365}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,864] Trial 693 finished with value: 0.9489544604130353 and parameters: {'weight_class_0': 0.43259541866400064, 'weight_class_1': 9.8931956049992, 'weight_class_2': 6.431455351461812}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:32:48,901] Trial 694 finished with value: 0.9487947474933881 and parameters: {'weight_class_0': 0.43872888357060424, 'weight_class_1': 9.946603121440065, 'weight_class_2': 7.3181886003281145}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,916] Trial 695 finished with value: 0.9491533990240018 and parameters: {'weight_class_0': 0.5165900339507232, 'weight_class_1': 9.831385738419767, 'weight_class_2': 6.366610377094763}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,923] Trial 696 finished with value: 0.9436891377931355 and parameters: {'weight_class_0': 0.13219331606181683, 'weight_class_1': 9.158629614155759, 'weight_class_2': 6.3120261521725185}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,933] Trial 697 finished with value: 0.9447537919758986 and parameters: {'weight_class_0': 0.15677618676920735, 'weight_class_1': 9.818432496283737, 'weight_class_2': 6.39219286013236}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,946] Trial 698 finished with value: 0.94560886508308 and parameters: {'weight_class_0': 0.1418897051225816, 'weight_class_1': 7.26746412873297, 'weight_class_2': 6.391095257985508}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:48,993] Trial 699 finished with value: 0.9443375357844849 and parameters: {'weight_class_0': 0.1482244530403828, 'weight_class_1': 9.03992307374652, 'weight_class_2': 8.053332424882363}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,009] Trial 700 finished with value: 0.9453540476277921 and parameters: {'weight_class_0': 0.13505084649748794, 'weight_class_1': 7.310652825817691, 'weight_class_2': 6.2901948231055}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,029] Trial 701 finished with value: 0.9326342263364262 and parameters: {'weight_class_0': 2.770117272884603, 'weight_class_1': 9.121080429100845, 'weight_class_2': 6.354013122070684}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,053] Trial 702 finished with value: 0.9480526270647874 and parameters: {'weight_class_0': 1.0756009546469674, 'weight_class_1': 9.130235430517603, 'weight_class_2': 6.579285894327274}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,059] Trial 704 finished with value: 0.9436963560161015 and parameters: {'weight_class_0': 0.13279735354462213, 'weight_class_1': 9.069480661937286, 'weight_class_2': 6.556949298654236}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,064] Trial 703 finished with value: 0.9410781285935047 and parameters: {'weight_class_0': 0.10960052063078085, 'weight_class_1': 9.22462222393024, 'weight_class_2': 6.307711468646962}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:32:49,079] Trial 705 finished with value: 0.943707812156395 and parameters: {'weight_class_0': 0.1367013863943925, 'weight_class_1': 9.10364978520058, 'weight_class_2': 7.422467132662043}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,114] Trial 706 finished with value: 0.9354669702028943 and parameters: {'weight_class_0': 1.2586656525530668, 'weight_class_1': 2.63045755259682, 'weight_class_2': 8.531834371591094}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,138] Trial 707 finished with value: 0.948193913862959 and parameters: {'weight_class_0': 1.1650410144455137, 'weight_class_1': 9.090493875853172, 'weight_class_2': 8.003894743209568}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,173] Trial 708 finished with value: 0.9480400074608714 and parameters: {'weight_class_0': 1.2094035236110043, 'weight_class_1': 9.096931617634018, 'weight_class_2': 8.051639886030177}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,181] Trial 709 finished with value: 0.9476446119774864 and parameters: {'weight_class_0': 1.1820712337983625, 'weight_class_1': 7.556964938788773, 'weight_class_2': 8.074831701908712}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,211] Trial 710 finished with value: 0.9482321205721568 and parameters: {'weight_class_0': 1.1424190288320002, 'weight_class_1': 9.089881498590955, 'weight_class_2': 8.04531491441795}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,234] Trial 711 finished with value: 0.9468862216309599 and parameters: {'weight_class_0': 1.2760409237419963, 'weight_class_1': 7.567282686094647, 'weight_class_2': 7.431367656799102}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,256] Trial 712 finished with value: 0.9469891451460652 and parameters: {'weight_class_0': 1.2791856559653052, 'weight_class_1': 7.581182424686743, 'weight_class_2': 7.713927684878879}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,263] Trial 713 finished with value: 0.9468697909292937 and parameters: {'weight_class_0': 1.3050254955769724, 'weight_class_1': 7.596823340726567, 'weight_class_2': 7.719137769353583}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,307] Trial 715 finished with value: 0.9471116530296416 and parameters: {'weight_class_0': 1.2818949264685455, 'weight_class_1': 7.617652024260403, 'weight_class_2': 8.035638196893872}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  36%|████████████████████████████████████████████████▏                                                                                    | 724/2000 [00:13<00:26, 48.10it/s]

[I 2026-07-08 13:32:49,317] Trial 714 finished with value: 0.9469827567692954 and parameters: {'weight_class_0': 1.2723283065552646, 'weight_class_1': 7.5354268940744795, 'weight_class_2': 7.694743060854209}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,326] Trial 716 finished with value: 0.9490959990147011 and parameters: {'weight_class_0': 0.6527443222588503, 'weight_class_1': 7.585953226092687, 'weight_class_2': 8.060174764565767}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,347] Trial 717 finished with value: 0.9491418183482079 and parameters: {'weight_class_0': 0.6287238734625077, 'weight_class_1': 7.700171551026207, 'weight_class_2': 7.729298011760796}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,389] Trial 718 finished with value: 0.9491267161780524 and parameters: {'weight_class_0': 0.647964514646619, 'weight_class_1': 7.615654348151089, 'weight_class_2': 7.702843861193002}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,393] Trial 719 finished with value: 0.9483951386978374 and parameters: {'weight_class_0': 0.9861144034184206, 'weight_class_1': 7.650883130052785, 'weight_class_2': 7.6825124668848375}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,450] Trial 721 finished with value: 0.9491363061680014 and parameters: {'weight_class_0': 0.6480279383674052, 'weight_class_1': 7.792128087458035, 'weight_class_2': 7.630622113451448}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,452] Trial 720 finished with value: 0.9491494117050676 and parameters: {'weight_class_0': 0.6340006733378307, 'weight_class_1': 7.75316139111806, 'weight_class_2': 7.711866614881632}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,454] Trial 722 finished with value: 0.9491153443347042 and parameters: {'weight_class_0': 0.5814786953307869, 'weight_class_1': 7.826659074392138, 'weight_class_2': 7.704991032574972}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,492] Trial 723 finished with value: 0.9491842368502971 and parameters: {'weight_class_0': 0.6064379674745861, 'weight_class_1': 7.774416452493509, 'weight_class_2': 6.936850388567274}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,508] Trial 724 finished with value: 0.9491538708681652 and parameters: {'weight_class_0': 0.6237111347109582, 'weight_class_1': 7.8763074383702225, 'weight_class_2': 6.912889547173635}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  37%|████████████████████████████████████████████████▉                                                                                    | 735/2000 [00:14<00:24, 51.35it/s]

[I 2026-07-08 13:32:49,535] Trial 725 finished with value: 0.949060771768023 and parameters: {'weight_class_0': 0.6720215917496932, 'weight_class_1': 7.8193261540085075, 'weight_class_2': 6.940812281651596}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,550] Trial 726 finished with value: 0.9491543806637591 and parameters: {'weight_class_0': 0.643419473033744, 'weight_class_1': 7.871563723823043, 'weight_class_2': 6.896508491140849}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,559] Trial 727 finished with value: 0.9483346016082885 and parameters: {'weight_class_0': 0.971655968518705, 'weight_class_1': 8.01673558633509, 'weight_class_2': 6.919482386858951}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,582] Trial 728 finished with value: 0.9485135661269518 and parameters: {'weight_class_0': 0.9587517986373267, 'weight_class_1': 8.063780269072653, 'weight_class_2': 7.357971454322023}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,597] Trial 729 finished with value: 0.9484981138986265 and parameters: {'weight_class_0': 0.956578421674187, 'weight_class_1': 8.083811775167993, 'weight_class_2': 7.375454696632301}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,628] Trial 730 finished with value: 0.9484625385599467 and parameters: {'weight_class_0': 0.9357847317322199, 'weight_class_1': 8.016149396178564, 'weight_class_2': 6.934242679068456}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,629] Trial 731 finished with value: 0.9485059270698167 and parameters: {'weight_class_0': 0.9251650681766292, 'weight_class_1': 8.104658016709665, 'weight_class_2': 6.928790904863826}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,672] Trial 732 finished with value: 0.9483239533276852 and parameters: {'weight_class_0': 1.0208538642158551, 'weight_class_1': 8.060789968570083, 'weight_class_2': 7.330688545768754}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,675] Trial 733 finished with value: 0.9002052984711276 and parameters: {'weight_class_0': 5.327967612214659, 'weight_class_1': 8.087223919624877, 'weight_class_2': 7.302283078523647}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,706] Trial 734 finished with value: 0.9484992389586062 and parameters: {'weight_class_0': 0.956862580452106, 'weight_class_1': 8.093245840155902, 'weight_class_2': 7.37447130788334}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,725] Trial 735 finished with value: 0.9485091865138036 and parameters: {'weight_class_0': 0.9533896308395682, 'weight_class_1': 8.07419008029924, 'weight_class_2': 7.370854689717001}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  37%|█████████████████████████████████████████████████▌                                                                                   | 746/2000 [00:14<00:25, 48.57it/s]

[I 2026-07-08 13:32:49,756] Trial 736 finished with value: 0.9486526209211048 and parameters: {'weight_class_0': 0.9342877922015075, 'weight_class_1': 8.087184517738349, 'weight_class_2': 7.4454535906169985}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,772] Trial 737 finished with value: 0.9485001695883694 and parameters: {'weight_class_0': 0.9747617912780047, 'weight_class_1': 8.083775435445858, 'weight_class_2': 7.470015835722917}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,784] Trial 738 finished with value: 0.9488289989597186 and parameters: {'weight_class_0': 0.8945453294234322, 'weight_class_1': 9.588223393969415, 'weight_class_2': 7.3708037790818555}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,812] Trial 739 finished with value: 0.9489472112597276 and parameters: {'weight_class_0': 0.830116967561155, 'weight_class_1': 9.499441319714261, 'weight_class_2': 7.413284383314505}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,843] Trial 740 finished with value: 0.9489895832058565 and parameters: {'weight_class_0': 0.8030908410920912, 'weight_class_1': 9.537147859201106, 'weight_class_2': 7.303594163368255}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,867] Trial 741 finished with value: 0.9489489666392753 and parameters: {'weight_class_0': 0.8238911214902328, 'weight_class_1': 9.488762201697423, 'weight_class_2': 7.28029738357243}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,885] Trial 742 finished with value: 0.9477804052331504 and parameters: {'weight_class_0': 0.2902192652173289, 'weight_class_1': 9.530631025305805, 'weight_class_2': 7.282353762560879}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,887] Trial 743 finished with value: 0.9490457516612802 and parameters: {'weight_class_0': 0.7883429716829524, 'weight_class_1': 9.604055047994112, 'weight_class_2': 7.485900810036268}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,902] Trial 744 finished with value: 0.9490684428732314 and parameters: {'weight_class_0': 0.7765386012963285, 'weight_class_1': 9.509481970384925, 'weight_class_2': 7.461442666712504}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,915] Trial 745 finished with value: 0.8873753884208363 and parameters: {'weight_class_0': 7.13888961078541, 'weight_class_1': 9.523967749172014, 'weight_class_2': 7.476342001906188}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,945] Trial 746 finished with value: 0.9489957403906518 and parameters: {'weight_class_0': 0.7886869774046252, 'weight_class_1': 9.560582941623256, 'weight_class_2': 6.594314945702351}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  38%|██████████████████████████████████████████████████▎                                                                                  | 756/2000 [00:14<00:24, 51.38it/s]

[I 2026-07-08 13:32:49,954] Trial 747 finished with value: 0.9489414631612965 and parameters: {'weight_class_0': 0.7868057592390627, 'weight_class_1': 9.457450912098375, 'weight_class_2': 6.655268632265637}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:49,978] Trial 748 finished with value: 0.9483403574425937 and parameters: {'weight_class_0': 0.3084472009804226, 'weight_class_1': 9.474760561608036, 'weight_class_2': 6.034744898849466}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,011] Trial 749 finished with value: 0.9491658679964409 and parameters: {'weight_class_0': 0.7545286780067221, 'weight_class_1': 9.463698932600654, 'weight_class_2': 8.407741296594754}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,020] Trial 751 finished with value: 0.9481034401634151 and parameters: {'weight_class_0': 0.2901411749605488, 'weight_class_1': 9.56002526057561, 'weight_class_2': 6.082508779558599}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,031] Trial 750 finished with value: 0.9480833754596225 and parameters: {'weight_class_0': 0.28317388154940365, 'weight_class_1': 8.386894002565011, 'weight_class_2': 6.609735421259699}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,073] Trial 752 finished with value: 0.8819241729536061 and parameters: {'weight_class_0': 6.904312541187118, 'weight_class_1': 8.374079779382326, 'weight_class_2': 6.65894395272108}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,103] Trial 754 finished with value: 0.9490986446513395 and parameters: {'weight_class_0': 0.5142044119383341, 'weight_class_1': 8.856783686057796, 'weight_class_2': 6.992889172081377}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,109] Trial 753 finished with value: 0.9484050871603813 and parameters: {'weight_class_0': 0.31403804551761716, 'weight_class_1': 8.407532617996251, 'weight_class_2': 6.662568352988843}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,128] Trial 755 finished with value: 0.948401265083608 and parameters: {'weight_class_0': 0.2962510492786381, 'weight_class_1': 8.441806178335092, 'weight_class_2': 5.954537365714385}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,156] Trial 756 finished with value: 0.9462957891591337 and parameters: {'weight_class_0': 0.3293325798546759, 'weight_class_1': 8.315807910012591, 'weight_class_2': 1.3779805494351685}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  38%|███████████████████████████████████████████████████                                                                                  | 767/2000 [00:14<00:23, 51.44it/s]

[I 2026-07-08 13:32:50,173] Trial 757 finished with value: 0.9481016921548372 and parameters: {'weight_class_0': 0.3079004574490743, 'weight_class_1': 8.478564001662349, 'weight_class_2': 7.861748078055525}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,200] Trial 759 finished with value: 0.9489668816369797 and parameters: {'weight_class_0': 0.487750558743971, 'weight_class_1': 8.696907158430454, 'weight_class_2': 7.869935418223488}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,207] Trial 758 finished with value: 0.9490723983371195 and parameters: {'weight_class_0': 0.5699406259114663, 'weight_class_1': 8.54234260806755, 'weight_class_2': 7.854688877802836}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,216] Trial 760 finished with value: 0.9489954864312894 and parameters: {'weight_class_0': 0.48847226875563254, 'weight_class_1': 8.37599910748388, 'weight_class_2': 7.895343351606444}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,243] Trial 761 finished with value: 0.9490911090224907 and parameters: {'weight_class_0': 0.529484022574378, 'weight_class_1': 8.85225288080347, 'weight_class_2': 7.857900770842636}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,267] Trial 762 finished with value: 0.9491670854077393 and parameters: {'weight_class_0': 0.5724418548398167, 'weight_class_1': 8.757353340963853, 'weight_class_2': 7.04036078557287}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,279] Trial 763 finished with value: 0.9437728268972885 and parameters: {'weight_class_0': 0.5244862666488194, 'weight_class_1': 1.7389653091605695, 'weight_class_2': 7.904973677245786}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,309] Trial 764 finished with value: 0.9490261698193043 and parameters: {'weight_class_0': 0.46378201707639377, 'weight_class_1': 8.849234014751726, 'weight_class_2': 7.001073694961457}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,314] Trial 765 finished with value: 0.9489965619232897 and parameters: {'weight_class_0': 0.6012742024693989, 'weight_class_1': 6.4170274349317085, 'weight_class_2': 7.829534179391224}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,340] Trial 766 finished with value: 0.9491378491013274 and parameters: {'weight_class_0': 0.5354304648043948, 'weight_class_1': 9.968127290023304, 'weight_class_2': 7.177089026483166}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,366] Trial 768 finished with value: 0.9491299313454896 and parameters: {'weight_class_0': 0.564517704035405, 'weight_class_1': 8.728566759715674, 'weight_class_2': 7.172286994662407}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:32:50,380] Trial 767 finished with value: 0.9490965685710978 and parameters: {'weight_class_0': 0.5368834138277045, 'weight_class_1': 8.755964777187858, 'weight_class_2': 7.868061985466075}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,395] Trial 769 finished with value: 0.9491084037901881 and parameters: {'weight_class_0': 0.5183775869522927, 'weight_class_1': 8.809688743383942, 'weight_class_2': 7.115050594645702}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,438] Trial 770 finished with value: 0.949153504767872 and parameters: {'weight_class_0': 0.5728894698538315, 'weight_class_1': 8.809630794767683, 'weight_class_2': 7.121855255183997}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,451] Trial 771 finished with value: 0.9491740018272997 and parameters: {'weight_class_0': 0.6043016471291746, 'weight_class_1': 8.816325897752177, 'weight_class_2': 7.124181972173025}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,467] Trial 772 finished with value: 0.9409949233456661 and parameters: {'weight_class_0': 0.6060422068908582, 'weight_class_1': 1.6109730370457092, 'weight_class_2': 7.0636533121679355}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,474] Trial 773 finished with value: 0.9491637991892249 and parameters: {'weight_class_0': 0.6232784039293952, 'weight_class_1': 9.257939659338678, 'weight_class_2': 7.188739211312842}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,509] Trial 774 finished with value: 0.9491956641804098 and parameters: {'weight_class_0': 0.6666378098477995, 'weight_class_1': 9.749152582933327, 'weight_class_2': 7.170210400741181}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,525] Trial 775 finished with value: 0.9491377725247675 and parameters: {'weight_class_0': 0.7101456586856979, 'weight_class_1': 9.283923840585253, 'weight_class_2': 7.246315261066016}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,537] Trial 777 finished with value: 0.9491103981974582 and parameters: {'weight_class_0': 0.7336490223735515, 'weight_class_1': 9.811613847551774, 'weight_class_2': 7.132070674282899}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,556] Trial 776 finished with value: 0.9491078537811714 and parameters: {'weight_class_0': 0.7240027310603284, 'weight_class_1': 9.986795149765008, 'weight_class_2': 7.08055119458564}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:32:50,597] Trial 778 finished with value: 0.9491201595080683 and parameters: {'weight_class_0': 0.7326601719758769, 'weight_class_1': 9.22095077090826, 'weight_class_2': 7.567334536380093}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,607] Trial 779 finished with value: 0.948138522049705 and parameters: {'weight_class_0': 0.7530604833363344, 'weight_class_1': 4.80633784353374, 'weight_class_2': 7.587898026000901}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,627] Trial 780 finished with value: 0.9492196289433769 and parameters: {'weight_class_0': 0.7020622321008654, 'weight_class_1': 9.318223552162582, 'weight_class_2': 7.534737235303543}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,666] Trial 781 finished with value: 0.9489941434198851 and parameters: {'weight_class_0': 0.7509843255157109, 'weight_class_1': 9.286085487085462, 'weight_class_2': 6.802928381045892}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,682] Trial 782 finished with value: 0.9490580020708329 and parameters: {'weight_class_0': 0.7709071073264478, 'weight_class_1': 9.681357524412078, 'weight_class_2': 7.58304060204174}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,683] Trial 783 finished with value: 0.9490027594571506 and parameters: {'weight_class_0': 0.7711387387141435, 'weight_class_1': 9.266257669649075, 'weight_class_2': 6.817309315708157}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,698] Trial 784 finished with value: 0.9483780181185324 and parameters: {'weight_class_0': 1.0803359496090055, 'weight_class_1': 9.750138175505768, 'weight_class_2': 7.634567509453816}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,706] Trial 785 finished with value: 0.6873658254398792 and parameters: {'weight_class_0': 0.014840337424337102, 'weight_class_1': 9.70658152194231, 'weight_class_2': 7.574081274331929}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,743] Trial 786 finished with value: 0.9484039621848482 and parameters: {'weight_class_0': 1.0661734428687941, 'weight_class_1': 9.830693149502347, 'weight_class_2': 7.557781616002801}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,751] Trial 787 finished with value: 0.9482952652899946 and parameters: {'weight_class_0': 1.0463987623184325, 'weight_class_1': 9.729578376678237, 'weight_class_2': 6.822238841147315}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,774] Trial 788 finished with value: 0.8748916002537875 and parameters: {'weight_class_0': 8.617548598964646, 'weight_class_1': 9.849064671593293, 'weight_class_2': 6.87782709585076}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  40%|█████████████████████████████████████████████████████▏                                                                               | 799/2000 [00:15<00:24, 49.66it/s]

[I 2026-07-08 13:32:50,777] Trial 789 finished with value: 0.6971610897193637 and parameters: {'weight_class_0': 0.015757487856726593, 'weight_class_1': 9.78538114378741, 'weight_class_2': 6.81852095048797}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,814] Trial 790 finished with value: 0.9479983762397987 and parameters: {'weight_class_0': 1.1004118127018476, 'weight_class_1': 9.935029255319613, 'weight_class_2': 6.537987462265584}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,828] Trial 791 finished with value: 0.9483910113915911 and parameters: {'weight_class_0': 1.014166867295303, 'weight_class_1': 9.724148231232702, 'weight_class_2': 6.842234977612311}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,835] Trial 792 finished with value: 0.8417322689978167 and parameters: {'weight_class_0': 0.035394740671705005, 'weight_class_1': 9.757155020620003, 'weight_class_2': 6.745147434197925}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,890] Trial 793 finished with value: 0.9484360302363776 and parameters: {'weight_class_0': 0.9988202153420754, 'weight_class_1': 9.678154390715493, 'weight_class_2': 6.769707998511089}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,915] Trial 794 finished with value: 0.9482017995832899 and parameters: {'weight_class_0': 1.071024509003396, 'weight_class_1': 9.715761621982852, 'weight_class_2': 6.839509061111913}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,920] Trial 795 finished with value: 0.9481420899910417 and parameters: {'weight_class_0': 1.0879651811618074, 'weight_class_1': 9.745896675624602, 'weight_class_2': 6.80826850674223}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,948] Trial 796 finished with value: 0.946644924203904 and parameters: {'weight_class_0': 1.6053923194685678, 'weight_class_1': 9.747872965379472, 'weight_class_2': 8.49047234627173}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,955] Trial 797 finished with value: 0.948245063943309 and parameters: {'weight_class_0': 0.30789868659528413, 'weight_class_1': 9.326847352752331, 'weight_class_2': 6.552020709821259}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,981] Trial 798 finished with value: 0.9474912002207883 and parameters: {'weight_class_0': 0.28229760794288716, 'weight_class_1': 9.684308198507535, 'weight_class_2': 8.408055580826677}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:50,990] Trial 800 finished with value: 0.9469987493813893 and parameters: {'weight_class_0': 1.5171008822274017, 'weight_class_1': 9.988834479977395, 'weight_class_2': 8.132761547588656}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  40%|█████████████████████████████████████████████████████▊                                                                               | 809/2000 [00:15<00:23, 50.41it/s]

[I 2026-07-08 13:32:51,005] Trial 799 finished with value: 0.9476855188414955 and parameters: {'weight_class_0': 0.304440770700671, 'weight_class_1': 9.99792713890966, 'weight_class_2': 8.529045266856011}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,045] Trial 802 finished with value: 0.9483272783383535 and parameters: {'weight_class_0': 0.338236026039993, 'weight_class_1': 9.343955010795876, 'weight_class_2': 7.29260110318625}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,051] Trial 801 finished with value: 0.9482848314657293 and parameters: {'weight_class_0': 0.3641095001495126, 'weight_class_1': 9.355736197966039, 'weight_class_2': 8.287596351029084}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,070] Trial 803 finished with value: 0.9479031546786582 and parameters: {'weight_class_0': 0.3219823334464127, 'weight_class_1': 9.98783017337838, 'weight_class_2': 8.356052519147388}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,101] Trial 804 finished with value: 0.9479764832067675 and parameters: {'weight_class_0': 0.324216792389879, 'weight_class_1': 9.2956044698129, 'weight_class_2': 8.442890468926208}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,132] Trial 806 finished with value: 0.9451493732061244 and parameters: {'weight_class_0': 1.438018449791879, 'weight_class_1': 5.9601750111750516, 'weight_class_2': 8.198730537062398}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,135] Trial 805 finished with value: 0.9479855861689764 and parameters: {'weight_class_0': 0.3209205853209147, 'weight_class_1': 9.316244395977122, 'weight_class_2': 8.176275570697474}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,164] Trial 807 finished with value: 0.9478317359322039 and parameters: {'weight_class_0': 0.31483622908782544, 'weight_class_1': 9.996007945453618, 'weight_class_2': 8.28154362211207}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,194] Trial 808 finished with value: 0.9479249110485791 and parameters: {'weight_class_0': 0.3123840895968584, 'weight_class_1': 9.432167530123971, 'weight_class_2': 8.105209133213432}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,202] Trial 809 finished with value: 0.9481761407493113 and parameters: {'weight_class_0': 0.34551196925373967, 'weight_class_1': 9.320810404722437, 'weight_class_2': 8.167455793880345}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  41%|██████████████████████████████████████████████████████▌                                                                              | 820/2000 [00:15<00:22, 51.77it/s]

[I 2026-07-08 13:32:51,212] Trial 810 finished with value: 0.9472069580649495 and parameters: {'weight_class_0': 0.8606749988535394, 'weight_class_1': 9.281786681959066, 'weight_class_2': 4.122099240468196}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,242] Trial 811 finished with value: 0.9485199988034735 and parameters: {'weight_class_0': 0.3657985688610267, 'weight_class_1': 9.360518598360839, 'weight_class_2': 7.308807174259722}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,254] Trial 812 finished with value: 0.9485082655937965 and parameters: {'weight_class_0': 0.36734725021305964, 'weight_class_1': 9.378148103073718, 'weight_class_2': 7.283657237707924}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,301] Trial 814 finished with value: 0.9488355895821732 and parameters: {'weight_class_0': 0.8805554179708475, 'weight_class_1': 9.196214293589685, 'weight_class_2': 7.254051841450006}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,304] Trial 813 finished with value: 0.9488782694483721 and parameters: {'weight_class_0': 0.8424732698295893, 'weight_class_1': 9.031710461913438, 'weight_class_2': 7.261068130560421}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,308] Trial 815 finished with value: 0.9489432240074169 and parameters: {'weight_class_0': 0.8120856536635835, 'weight_class_1': 9.007497320511902, 'weight_class_2': 7.32220351080222}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,329] Trial 816 finished with value: 0.9488895096164414 and parameters: {'weight_class_0': 0.8681058246410233, 'weight_class_1': 8.99535667883693, 'weight_class_2': 7.496363599453945}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,352] Trial 817 finished with value: 0.9484581718635307 and parameters: {'weight_class_0': 0.834570488732738, 'weight_class_1': 9.068588351181113, 'weight_class_2': 5.820071851111196}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,373] Trial 818 finished with value: 0.9484460199962982 and parameters: {'weight_class_0': 0.6196371744017003, 'weight_class_1': 9.02383228184259, 'weight_class_2': 4.025189495008433}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,385] Trial 819 finished with value: 0.9489783657028442 and parameters: {'weight_class_0': 0.8072839746877407, 'weight_class_1': 9.550636159730702, 'weight_class_2': 7.248599373452675}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  42%|███████████████████████████████████████████████████████▏                                                                             | 830/2000 [00:15<00:23, 49.58it/s]

[I 2026-07-08 13:32:51,442] Trial 820 finished with value: 0.9488193350635269 and parameters: {'weight_class_0': 0.8584312539020147, 'weight_class_1': 9.084705168418516, 'weight_class_2': 7.271364898645705}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,443] Trial 821 finished with value: 0.9488778562240778 and parameters: {'weight_class_0': 0.8445404238978349, 'weight_class_1': 9.060559270990456, 'weight_class_2': 7.288551325157509}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,453] Trial 822 finished with value: 0.9489339970208296 and parameters: {'weight_class_0': 0.8384959754719704, 'weight_class_1': 9.649255687836554, 'weight_class_2': 7.511963582327865}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,478] Trial 823 finished with value: 0.9247880300451604 and parameters: {'weight_class_0': 0.8872380198204716, 'weight_class_1': 1.22199309696627, 'weight_class_2': 7.628399181484598}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,491] Trial 824 finished with value: 0.9488841090216913 and parameters: {'weight_class_0': 0.8551668891693713, 'weight_class_1': 9.08987655056148, 'weight_class_2': 7.51184208703913}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,536] Trial 825 finished with value: 0.9490401457649392 and parameters: {'weight_class_0': 0.6221984941884378, 'weight_class_1': 9.553141759255427, 'weight_class_2': 5.7597574216411624}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,542] Trial 826 finished with value: 0.9491688133342083 and parameters: {'weight_class_0': 0.6040050112894703, 'weight_class_1': 9.449712541018673, 'weight_class_2': 6.997858744923493}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,554] Trial 827 finished with value: 0.949141540633585 and parameters: {'weight_class_0': 0.6086584374046706, 'weight_class_1': 9.57470558899746, 'weight_class_2': 7.543922527243596}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,572] Trial 828 finished with value: 0.9491697649919959 and parameters: {'weight_class_0': 0.5918489440282018, 'weight_class_1': 9.57019867531952, 'weight_class_2': 7.623679970959362}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,602] Trial 830 finished with value: 0.9491368731491637 and parameters: {'weight_class_0': 0.64644563798926, 'weight_class_1': 9.72350424087351, 'weight_class_2': 7.644038908239004}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,615] Trial 829 finished with value: 0.9491382344280445 and parameters: {'weight_class_0': 0.567353906573396, 'weight_class_1': 9.602261796471538, 'weight_class_2': 7.687226626872334}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  42%|███████████████████████████████████████████████████████▊                                                                             | 840/2000 [00:16<00:23, 49.58it/s]

[I 2026-07-08 13:32:51,630] Trial 831 finished with value: 0.9490544008286427 and parameters: {'weight_class_0': 0.6594176445315852, 'weight_class_1': 9.609949207248956, 'weight_class_2': 6.125849863079664}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,673] Trial 832 finished with value: 0.949086280916501 and parameters: {'weight_class_0': 0.5398211516026123, 'weight_class_1': 9.606997901480339, 'weight_class_2': 7.673915121263884}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,695] Trial 834 finished with value: 0.9488721539624961 and parameters: {'weight_class_0': 0.5560379807653973, 'weight_class_1': 9.522637438443438, 'weight_class_2': 9.987772573889712}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,699] Trial 833 finished with value: 0.9490637225646493 and parameters: {'weight_class_0': 0.5543536605056386, 'weight_class_1': 9.606836959871021, 'weight_class_2': 7.692870940960386}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,727] Trial 835 finished with value: 0.9491499139574101 and parameters: {'weight_class_0': 0.5268487593335186, 'weight_class_1': 9.64267262208163, 'weight_class_2': 6.0973253622880605}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,753] Trial 836 finished with value: 0.9457730629498341 and parameters: {'weight_class_0': 0.5614662169637867, 'weight_class_1': 2.2288517440282773, 'weight_class_2': 6.988432888141481}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,763] Trial 837 finished with value: 0.948243368209606 and parameters: {'weight_class_0': 0.5300419265451102, 'weight_class_1': 3.7228202005902054, 'weight_class_2': 7.780059041450582}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,779] Trial 838 finished with value: 0.9491402001771353 and parameters: {'weight_class_0': 0.557763505950198, 'weight_class_1': 8.544482835662619, 'weight_class_2': 7.016809462285528}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,808] Trial 839 finished with value: 0.9421291266338395 and parameters: {'weight_class_0': 1.1593319552531138, 'weight_class_1': 3.37808307747115, 'weight_class_2': 9.983720429373017}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,824] Trial 840 finished with value: 0.946179260465838 and parameters: {'weight_class_0': 0.49941610160159094, 'weight_class_1': 2.0961833372288896, 'weight_class_2': 6.590495187684825}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  42%|████████████████████████████████████████████████████████▌                                                                            | 850/2000 [00:16<00:24, 47.67it/s]

[I 2026-07-08 13:32:51,856] Trial 841 finished with value: 0.9440650490776976 and parameters: {'weight_class_0': 0.13230775781800647, 'weight_class_1': 8.512658243425362, 'weight_class_2': 7.015450056069365}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,889] Trial 842 finished with value: 0.9477239621160872 and parameters: {'weight_class_0': 1.1529501939770714, 'weight_class_1': 8.490325523146335, 'weight_class_2': 6.94408531261306}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,891] Trial 843 finished with value: 0.9477167004674042 and parameters: {'weight_class_0': 1.1590473236026526, 'weight_class_1': 8.544471663171311, 'weight_class_2': 6.9734285792966375}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,939] Trial 844 finished with value: 0.9476668490987676 and parameters: {'weight_class_0': 1.102642281865123, 'weight_class_1': 8.28951249705243, 'weight_class_2': 6.510624580577115}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,942] Trial 845 finished with value: 0.9420482903414579 and parameters: {'weight_class_0': 0.11104319233631788, 'weight_class_1': 8.492147004396951, 'weight_class_2': 6.995045522607355}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,958] Trial 846 finished with value: 0.9476155119413477 and parameters: {'weight_class_0': 1.1693251946881245, 'weight_class_1': 8.347054255414012, 'weight_class_2': 7.0191499464001605}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,982] Trial 847 finished with value: 0.8765632927670876 and parameters: {'weight_class_0': 7.874581158656107, 'weight_class_1': 8.597132630105277, 'weight_class_2': 7.009384725093387}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:51,992] Trial 848 finished with value: 0.9474985279983489 and parameters: {'weight_class_0': 1.1501756864838075, 'weight_class_1': 8.26847179069322, 'weight_class_2': 6.5160742871823905}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,014] Trial 850 finished with value: 0.9446963346753715 and parameters: {'weight_class_0': 0.13814269949762664, 'weight_class_1': 8.327960849538139, 'weight_class_2': 6.5070663823360135}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,037] Trial 849 finished with value: 0.9474481774714398 and parameters: {'weight_class_0': 1.1628275771165582, 'weight_class_1': 8.502104474556338, 'weight_class_2': 6.454955982291232}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  43%|█████████████████████████████████████████████████████████▏                                                                           | 860/2000 [00:16<00:23, 48.53it/s]

[I 2026-07-08 13:32:52,053] Trial 851 finished with value: 0.9436200756223737 and parameters: {'weight_class_0': 0.12496599635146899, 'weight_class_1': 8.3501250496741, 'weight_class_2': 7.010140562847609}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,066] Trial 852 finished with value: 0.947602858060678 and parameters: {'weight_class_0': 1.1350828336649115, 'weight_class_1': 8.429569727004608, 'weight_class_2': 6.528685473049137}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,076] Trial 853 finished with value: 0.874785320190003 and parameters: {'weight_class_0': 8.01607502569088, 'weight_class_1': 8.281380618709163, 'weight_class_2': 7.019049396313437}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,096] Trial 855 finished with value: 0.8798208233638944 and parameters: {'weight_class_0': 7.838184880906167, 'weight_class_1': 8.3171861314848, 'weight_class_2': 7.939556142670408}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,136] Trial 854 finished with value: 0.9464577787024483 and parameters: {'weight_class_0': 0.18024647075628208, 'weight_class_1': 8.255443198212495, 'weight_class_2': 6.496828731313381}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,146] Trial 856 finished with value: 0.9486701215994592 and parameters: {'weight_class_0': 0.9765463376621726, 'weight_class_1': 8.227756253927142, 'weight_class_2': 7.94345670782375}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,164] Trial 857 finished with value: 0.8778732339148162 and parameters: {'weight_class_0': 8.102791482776578, 'weight_class_1': 8.249217461860505, 'weight_class_2': 7.972232410699132}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,197] Trial 858 finished with value: 0.9492314419703677 and parameters: {'weight_class_0': 0.7251331974262367, 'weight_class_1': 9.839315210898656, 'weight_class_2': 7.902055976651666}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,234] Trial 859 finished with value: 0.9488605490584838 and parameters: {'weight_class_0': 0.9406698548126535, 'weight_class_1': 9.85390894995183, 'weight_class_2': 7.934104177749121}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,241] Trial 860 finished with value: 0.949156836768713 and parameters: {'weight_class_0': 0.7564463477611891, 'weight_class_1': 9.837705942391992, 'weight_class_2': 7.874313382408838}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  44%|█████████████████████████████████████████████████████████▉                                                                           | 871/2000 [00:16<00:23, 48.35it/s]

[I 2026-07-08 13:32:52,279] Trial 862 finished with value: 0.9491713704978073 and parameters: {'weight_class_0': 0.7480345358802479, 'weight_class_1': 9.83394171704155, 'weight_class_2': 7.825473517571096}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,287] Trial 861 finished with value: 0.9486790084866469 and parameters: {'weight_class_0': 0.9228988668676634, 'weight_class_1': 8.159154740423329, 'weight_class_2': 7.447276871534413}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,299] Trial 863 finished with value: 0.9474324801474667 and parameters: {'weight_class_0': 1.392182955904973, 'weight_class_1': 9.846839600129718, 'weight_class_2': 7.938313623474123}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,319] Trial 864 finished with value: 0.9490787358631448 and parameters: {'weight_class_0': 0.7668991549425486, 'weight_class_1': 9.395564091303958, 'weight_class_2': 7.448486924178001}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,337] Trial 865 finished with value: 0.9491279785903296 and parameters: {'weight_class_0': 0.7244475946474819, 'weight_class_1': 9.772649634118807, 'weight_class_2': 7.438343715647538}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,360] Trial 866 finished with value: 0.9491260481508114 and parameters: {'weight_class_0': 0.7444065089775886, 'weight_class_1': 9.82078533100835, 'weight_class_2': 7.411813514939927}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,364] Trial 867 finished with value: 0.9491217048264629 and parameters: {'weight_class_0': 0.7287295933387703, 'weight_class_1': 9.792321713826208, 'weight_class_2': 7.477133048820508}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,422] Trial 868 finished with value: 0.9490960803377915 and parameters: {'weight_class_0': 0.7411160676772929, 'weight_class_1': 9.803839278753294, 'weight_class_2': 7.46566073888154}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,441] Trial 869 finished with value: 0.8942477894998632 and parameters: {'weight_class_0': 1.424193747803798, 'weight_class_1': 9.990084700108104, 'weight_class_2': 0.48989473966906516}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,443] Trial 870 finished with value: 0.9491706690938502 and parameters: {'weight_class_0': 0.7463074181126351, 'weight_class_1': 9.987401199462969, 'weight_class_2': 7.796298392022743}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,484] Trial 871 finished with value: 0.9473864094703921 and parameters: {'weight_class_0': 1.3513055305434962, 'weight_class_1': 9.77161952508416, 'weight_class_2': 7.4663665937005135}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:32:52,490] Trial 872 finished with value: 0.9492261499746529 and parameters: {'weight_class_0': 0.7342671640943375, 'weight_class_1': 9.985126160271832, 'weight_class_2': 8.073968337778705}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,498] Trial 873 finished with value: 0.9491992461266912 and parameters: {'weight_class_0': 0.7115282230435682, 'weight_class_1': 9.9694725976619, 'weight_class_2': 7.468928298713083}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,545] Trial 874 finished with value: 0.9486463814364483 and parameters: {'weight_class_0': 0.4151020533492915, 'weight_class_1': 9.836744964848192, 'weight_class_2': 8.034410845459695}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,559] Trial 875 finished with value: 0.9488888249664701 and parameters: {'weight_class_0': 0.9760894230071606, 'weight_class_1': 9.876676470582185, 'weight_class_2': 8.089143995917976}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,564] Trial 876 finished with value: 0.9487429709462126 and parameters: {'weight_class_0': 0.42373695845431986, 'weight_class_1': 9.39530444253477, 'weight_class_2': 7.7479268157443455}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,569] Trial 877 finished with value: 0.9486984615886301 and parameters: {'weight_class_0': 0.4352855466396052, 'weight_class_1': 9.968420059184668, 'weight_class_2': 8.083197756868097}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,605] Trial 878 finished with value: 0.9488241984766935 and parameters: {'weight_class_0': 0.4381496046777794, 'weight_class_1': 9.523567885293042, 'weight_class_2': 7.674144028015615}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,637] Trial 879 finished with value: 0.9485772910312601 and parameters: {'weight_class_0': 0.40399748997103885, 'weight_class_1': 9.98571748465804, 'weight_class_2': 7.7727601229951375}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,641] Trial 880 finished with value: 0.9486965326423222 and parameters: {'weight_class_0': 0.4327446376228097, 'weight_class_1': 9.999916196585152, 'weight_class_2': 8.08289565289777}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  45%|███████████████████████████████████████████████████████████▎                                                                         | 891/2000 [00:17<00:23, 46.44it/s]

[I 2026-07-08 13:32:52,698] Trial 882 finished with value: 0.9486488382199533 and parameters: {'weight_class_0': 0.40299754573201607, 'weight_class_1': 9.442703284244052, 'weight_class_2': 7.684198275762402}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,702] Trial 881 finished with value: 0.9488309896460292 and parameters: {'weight_class_0': 0.442529795318097, 'weight_class_1': 9.45677065268341, 'weight_class_2': 7.724647065760876}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,713] Trial 884 finished with value: 0.9487089777904817 and parameters: {'weight_class_0': 0.4406588586745492, 'weight_class_1': 9.950457828516802, 'weight_class_2': 8.141221798966132}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,740] Trial 883 finished with value: 0.9486373930871425 and parameters: {'weight_class_0': 0.42008306851938265, 'weight_class_1': 9.887684421098637, 'weight_class_2': 8.19547425240968}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,771] Trial 885 finished with value: 0.9487344243973291 and parameters: {'weight_class_0': 0.4351904157755964, 'weight_class_1': 9.746521672237561, 'weight_class_2': 8.125763889197438}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,799] Trial 888 finished with value: 0.9487865020717551 and parameters: {'weight_class_0': 1.0036431922762132, 'weight_class_1': 9.694270753629977, 'weight_class_2': 8.11922434363156}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,820] Trial 886 finished with value: 0.9488515851758357 and parameters: {'weight_class_0': 0.9992877551695253, 'weight_class_1': 9.667071003087111, 'weight_class_2': 8.249708266608037}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,826] Trial 889 finished with value: 0.9488638790111055 and parameters: {'weight_class_0': 0.9510779110420013, 'weight_class_1': 9.999061581264781, 'weight_class_2': 8.121037450031277}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,827] Trial 887 finished with value: 0.9487709344134716 and parameters: {'weight_class_0': 0.44311503801294594, 'weight_class_1': 9.931766127298642, 'weight_class_2': 7.740070374676877}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,833] Trial 890 finished with value: 0.9488920134288644 and parameters: {'weight_class_0': 0.9922497492505158, 'weight_class_1': 9.654515339371287, 'weight_class_2': 8.283225734539247}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,874] Trial 891 finished with value: 0.9488319329149896 and parameters: {'weight_class_0': 0.989286733434747, 'weight_class_1': 9.640161860280324, 'weight_class_2': 8.38212045611541}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:32:52,906] Trial 892 finished with value: 0.9087072355593736 and parameters: {'weight_class_0': 0.9231989943901479, 'weight_class_1': 0.6764614156581104, 'weight_class_2': 8.204581273019496}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,910] Trial 893 finished with value: 0.9488539739641692 and parameters: {'weight_class_0': 0.9710388435882513, 'weight_class_1': 9.677494532651012, 'weight_class_2': 8.289214211816539}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,942] Trial 895 finished with value: 0.9488944384032013 and parameters: {'weight_class_0': 0.9522111113650966, 'weight_class_1': 9.713622678626098, 'weight_class_2': 8.566263685805318}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,961] Trial 894 finished with value: 0.9488960235108 and parameters: {'weight_class_0': 0.9562209456204196, 'weight_class_1': 9.706137932487701, 'weight_class_2': 8.651509791871055}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,990] Trial 896 finished with value: 0.9486164755786684 and parameters: {'weight_class_0': 0.9672342269678554, 'weight_class_1': 9.984755406019703, 'weight_class_2': 7.22504981284725}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:52,999] Trial 897 finished with value: 0.948584051187737 and parameters: {'weight_class_0': 0.9779729339242615, 'weight_class_1': 9.673620199088088, 'weight_class_2': 7.241554117248072}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:53,025] Trial 898 finished with value: 0.9491545027837404 and parameters: {'weight_class_0': 0.760071817244348, 'weight_class_1': 9.637550299524815, 'weight_class_2': 8.49607409449268}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:53,044] Trial 899 finished with value: 0.9491681743227414 and parameters: {'weight_class_0': 0.7033995041121496, 'weight_class_1': 9.748270758060595, 'weight_class_2': 7.20749109379987}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:53,069] Trial 900 finished with value: 0.9492166391234664 and parameters: {'weight_class_0': 0.657930671113153, 'weight_class_1': 9.699760306470704, 'weight_class_2': 7.22477181308453}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:53,084] Trial 901 finished with value: 0.9491483609548034 and parameters: {'weight_class_0': 0.6514664236451819, 'weight_class_1': 9.657245924869423, 'weight_class_2': 8.487439541785726}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:53,109] Trial 902 finished with value: 0.9074570936420671 and parameters: {'weight_class_0': 0.7279047010343196, 'weight_class_1': 0.65255715469298, 'weight_class_2': 2.296612724314092}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  46%|████████████████████████████████████████████████████████████▋                                                                        | 912/2000 [00:17<00:22, 47.89it/s]

[I 2026-07-08 13:32:53,130] Trial 903 finished with value: 0.9491321646907175 and parameters: {'weight_class_0': 0.7075677570148844, 'weight_class_1': 9.990203262720522, 'weight_class_2': 7.192101359244744}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:53,174] Trial 905 finished with value: 0.9491032857516742 and parameters: {'weight_class_0': 0.7281016494804254, 'weight_class_1': 9.98701789817806, 'weight_class_2': 7.1992079082345315}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:53,186] Trial 906 finished with value: 0.9489983812059569 and parameters: {'weight_class_0': 0.669218599965361, 'weight_class_1': 9.984139530490769, 'weight_class_2': 5.632309417244756}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:53,195] Trial 904 finished with value: 0.8968546329730334 and parameters: {'weight_class_0': 0.6670830179827547, 'weight_class_1': 0.2521480479446687, 'weight_class_2': 7.197803122994203}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:53,230] Trial 908 finished with value: 0.942265402011781 and parameters: {'weight_class_0': 0.6854919542786305, 'weight_class_1': 9.998530384010815, 'weight_class_2': 1.9734942670667004}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:53,237] Trial 907 finished with value: 0.9489794924331685 and parameters: {'weight_class_0': 0.6923595870234309, 'weight_class_1': 9.48674323821187, 'weight_class_2': 5.630065407314943}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:53,269] Trial 911 finished with value: 0.9489812057774131 and parameters: {'weight_class_0': 0.6964849378516232, 'weight_class_1': 9.503748695059267, 'weight_class_2': 5.904904597338715}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:53,276] Trial 909 finished with value: 0.9492003743786853 and parameters: {'weight_class_0': 0.6649931229729317, 'weight_class_1': 9.427344443976102, 'weight_class_2': 7.248633902503326}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:53,284] Trial 910 finished with value: 0.9465562925350666 and parameters: {'weight_class_0': 0.2131303135538719, 'weight_class_1': 9.481616596203482, 'weight_class_2': 7.863897764801938}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:53,293] Trial 912 finished with value: 0.94904372329336 and parameters: {'weight_class_0': 0.6480659700713556, 'weight_class_1': 9.471889399706791, 'weight_class_2': 5.925354373592224}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:32:53,330] Trial 913 finished with value: 0.9469390152766666 and parameters: {'weight_class_0': 0.23104418063985982, 'weight_class_1': 9.322371926773535, 'weight_class_2': 7.894007196073999}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:53,363] Trial 914 finished with value: 0.6970641646260048 and parameters: {'weight_class_0': 0.01614687641981344, 'weight_class_1': 9.497901568161142, 'weight_class_2': 7.589142173353668}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:53,377] Trial 915 finished with value: 0.9467979517522039 and parameters: {'weight_class_0': 0.20251018530688614, 'weight_class_1': 9.482406658910518, 'weight_class_2': 5.688770101232463}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:53,392] Trial 916 finished with value: 0.9435107311066709 and parameters: {'weight_class_0': 0.14519773066079106, 'weight_class_1': 9.460422442597341, 'weight_class_2': 9.043942353177881}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:53,425] Trial 917 finished with value: 0.7017212200322741 and parameters: {'weight_class_0': 0.01701016778794684, 'weight_class_1': 9.433912637571664, 'weight_class_2': 7.885935559909571}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:53,439] Trial 918 finished with value: 0.9443684836668528 and parameters: {'weight_class_0': 0.1522657590670639, 'weight_class_1': 9.4650142687691, 'weight_class_2': 7.896437567111811}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:53,465] Trial 920 finished with value: 0.9458996958069047 and parameters: {'weight_class_0': 0.18589619400012092, 'weight_class_1': 9.42781001791686, 'weight_class_2': 7.575791497251017}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:53,474] Trial 919 finished with value: 0.9449015920309035 and parameters: {'weight_class_0': 0.16283767236962554, 'weight_class_1': 9.516457057399803, 'weight_class_2': 7.907161034504561}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:53,510] Trial 921 finished with value: 0.9472719692935883 and parameters: {'weight_class_0': 1.3560308367005212, 'weight_class_1': 9.377325048225071, 'weight_class_2': 7.520743818773824}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:53,517] Trial 922 finished with value: 0.9474354299725798 and parameters: {'weight_class_0': 1.3080820648826335, 'weight_class_1': 9.2928599996847, 'weight_class_2': 7.45056927890377}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:32:53,549] Trial 923 finished with value: 0.9489320021893408 and parameters: {'weight_class_0': 0.8500659675915584, 'weight_class_1': 9.308633451611545, 'weight_class_2': 7.486362925420519}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:53,570] Trial 924 finished with value: 0.9473106240226694 and parameters: {'weight_class_0': 1.336007164778401, 'weight_class_1': 9.239943082353541, 'weight_class_2': 7.4812150686374}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:53,603] Trial 925 finished with value: 0.9474446265814382 and parameters: {'weight_class_0': 1.3068669816397045, 'weight_class_1': 9.242471954144076, 'weight_class_2': 7.481107660551334}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:53,621] Trial 926 finished with value: 0.9472151885601997 and parameters: {'weight_class_0': 1.339067962833798, 'weight_class_1': 9.23922633869819, 'weight_class_2': 7.383614703169389}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:53,663] Trial 928 finished with value: 0.9478435047492076 and parameters: {'weight_class_0': 1.2275788639022838, 'weight_class_1': 9.227426622774114, 'weight_class_2': 7.527185285492418}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:53,669] Trial 927 finished with value: 0.9475105763678101 and parameters: {'weight_class_0': 1.290316928692957, 'weight_class_1': 9.29969699765496, 'weight_class_2': 7.322935507294585}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:53,680] Trial 929 finished with value: 0.947586640036425 and parameters: {'weight_class_0': 1.2812448318466885, 'weight_class_1': 9.279521528056511, 'weight_class_2': 7.488258238027724}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:53,708] Trial 930 finished with value: 0.9479128946832435 and parameters: {'weight_class_0': 1.2124331641969333, 'weight_class_1': 9.297029238192708, 'weight_class_2': 7.480031871402784}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:32:53,761] Trial 931 finished with value: 0.9475606491467842 and parameters: {'weight_class_0': 1.2847438462654661, 'weight_class_1': 9.233840376992914, 'weight_class_2': 7.430578089354816}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:53,769] Trial 932 finished with value: 0.8999907669167677 and parameters: {'weight_class_0': 5.736274439313085, 'weight_class_1': 9.26352205934784, 'weight_class_2': 7.386631850301921}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:53,774] Trial 933 finished with value: 0.9489026989157239 and parameters: {'weight_class_0': 0.8708650559297799, 'weight_class_1': 9.781143799155924, 'weight_class_2': 7.355898328862617}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:53,803] Trial 935 finished with value: 0.9481068805060362 and parameters: {'weight_class_0': 1.1539749736700982, 'weight_class_1': 9.729407854022353, 'weight_class_2': 7.319074185536682}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:53,811] Trial 934 finished with value: 0.9478713633567409 and parameters: {'weight_class_0': 1.2292862977521377, 'weight_class_1': 9.79330046167488, 'weight_class_2': 7.3049367036921975}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:53,843] Trial 936 finished with value: 0.9481258632338644 and parameters: {'weight_class_0': 1.1480143414154, 'weight_class_1': 9.72566513762357, 'weight_class_2': 7.3203511543296855}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:53,907] Trial 937 finished with value: 0.9491225539941658 and parameters: {'weight_class_0': 0.5388713934887925, 'weight_class_1': 9.775729631526382, 'weight_class_2': 7.221292341976608}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:53,920] Trial 939 finished with value: 0.949083331803251 and parameters: {'weight_class_0': 0.4907056282605712, 'weight_class_1': 9.743025133693008, 'weight_class_2': 7.261807032959547}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:53,934] Trial 938 finished with value: 0.9491003044798405 and parameters: {'weight_class_0': 0.528040588336105, 'weight_class_1': 9.772901276445648, 'weight_class_2': 7.225199875287735}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:32:53,955] Trial 940 finished with value: 0.9490718972049651 and parameters: {'weight_class_0': 0.49286279138309785, 'weight_class_1': 9.78134908195098, 'weight_class_2': 7.247119745692557}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:53,982] Trial 941 finished with value: 0.9490858053407419 and parameters: {'weight_class_0': 0.5191502649833853, 'weight_class_1': 9.7583009601151, 'weight_class_2': 7.2526615675796995}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:54,008] Trial 942 finished with value: 0.9490731823107588 and parameters: {'weight_class_0': 0.5192452543325268, 'weight_class_1': 9.798568668788578, 'weight_class_2': 7.223709360362679}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:54,022] Trial 943 finished with value: 0.9490806098135303 and parameters: {'weight_class_0': 0.5193490788618078, 'weight_class_1': 9.768349537559592, 'weight_class_2': 7.186799785349626}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:54,032] Trial 944 finished with value: 0.9491193732444433 and parameters: {'weight_class_0': 0.5297877712917952, 'weight_class_1': 9.758807677563862, 'weight_class_2': 7.152122035635489}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:54,086] Trial 945 finished with value: 0.9491243717251784 and parameters: {'weight_class_0': 0.572158238272506, 'weight_class_1': 9.793964276378626, 'weight_class_2': 7.739915072403504}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:54,097] Trial 946 finished with value: 0.949077945346227 and parameters: {'weight_class_0': 0.534741747083615, 'weight_class_1': 9.813122718461422, 'weight_class_2': 7.701544646235516}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:54,174] Trial 948 finished with value: 0.949065419141876 and parameters: {'weight_class_0': 0.7854490884286085, 'weight_class_1': 9.621063924515406, 'weight_class_2': 7.700004386375379}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  48%|███████████████████████████████████████████████████████████████▌                                                                     | 956/2000 [00:18<00:26, 39.78it/s]

[I 2026-07-08 13:32:54,180] Trial 947 finished with value: 0.94900325467052 and parameters: {'weight_class_0': 0.8314180540592732, 'weight_class_1': 9.638486549708134, 'weight_class_2': 7.7868283492095935}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:54,192] Trial 949 finished with value: 0.9490090986616999 and parameters: {'weight_class_0': 0.8227457069284062, 'weight_class_1': 9.591561794359178, 'weight_class_2': 7.770237030139952}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:54,225] Trial 950 finished with value: 0.8725542500563058 and parameters: {'weight_class_0': 9.391500351779285, 'weight_class_1': 9.6032044277274, 'weight_class_2': 7.693344600235083}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:54,257] Trial 951 finished with value: 0.9489796390482668 and parameters: {'weight_class_0': 0.8458271259025638, 'weight_class_1': 9.55357570249123, 'weight_class_2': 7.700872634744487}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:54,296] Trial 952 finished with value: 0.8729420724656808 and parameters: {'weight_class_0': 9.356382457477864, 'weight_class_1': 9.621511074942259, 'weight_class_2': 7.747266940290201}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:54,312] Trial 953 finished with value: 0.9489611234021783 and parameters: {'weight_class_0': 0.8394790961369316, 'weight_class_1': 9.994434831835271, 'weight_class_2': 7.615524392949235}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:54,316] Trial 954 finished with value: 0.948932777396744 and parameters: {'weight_class_0': 0.8773094201228876, 'weight_class_1': 9.58181407009581, 'weight_class_2': 7.729671567348717}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:54,343] Trial 955 finished with value: 0.9489437822223428 and parameters: {'weight_class_0': 0.876702883958918, 'weight_class_1': 9.572267537828871, 'weight_class_2': 7.814879136908408}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:54,362] Trial 956 finished with value: 0.9489525682231671 and parameters: {'weight_class_0': 0.849771136639089, 'weight_class_1': 9.571097795325032, 'weight_class_2': 7.703315738970221}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:32:54,375] Trial 957 finished with value: 0.9283549120543976 and parameters: {'weight_class_0': 4.125890410089016, 'weight_class_1': 9.995361882390402, 'weight_class_2': 9.575722661921898}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:54,392] Trial 958 finished with value: 0.9450940187826378 and parameters: {'weight_class_0': 1.7812253253598271, 'weight_class_1': 9.50545506271026, 'weight_class_2': 7.683870304615975}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:54,449] Trial 959 finished with value: 0.9488661580155832 and parameters: {'weight_class_0': 0.9731129573371824, 'weight_class_1': 9.638634678137587, 'weight_class_2': 7.99769743246673}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:54,463] Trial 960 finished with value: 0.9486072725114437 and parameters: {'weight_class_0': 1.039322535894022, 'weight_class_1': 9.526673600045392, 'weight_class_2': 8.026888357561369}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:54,476] Trial 961 finished with value: 0.9410635252265768 and parameters: {'weight_class_0': 1.0291128269746326, 'weight_class_1': 2.854449448538371, 'weight_class_2': 7.015514444554101}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:54,526] Trial 963 finished with value: 0.9303705629719431 and parameters: {'weight_class_0': 1.779641583658265, 'weight_class_1': 9.022456108668207, 'weight_class_2': 3.3352004437979677}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:54,547] Trial 962 finished with value: 0.9487059590266775 and parameters: {'weight_class_0': 1.0138675183176393, 'weight_class_1': 9.970888104341013, 'weight_class_2': 7.9776043921222}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  48%|████████████████████████████████████████████████████████████████▏                                                                    | 966/2000 [00:18<00:24, 41.98it/s]

[I 2026-07-08 13:32:54,554] Trial 964 finished with value: 0.9193510889420923 and parameters: {'weight_class_0': 3.940676803048114, 'weight_class_1': 8.960495037941188, 'weight_class_2': 7.024823876862971}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:54,570] Trial 965 finished with value: 0.9485562471162002 and parameters: {'weight_class_0': 1.0291844684563622, 'weight_class_1': 9.143108086701492, 'weight_class_2': 8.037348245888678}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:54,600] Trial 966 finished with value: 0.9159667601940488 and parameters: {'weight_class_0': 4.738212162774523, 'weight_class_1': 9.989917171737556, 'weight_class_2': 8.028305802511417}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  49%|████████████████████████████████████████████████████████████████▋                                                                    | 972/2000 [00:19<00:24, 41.37it/s]

[I 2026-07-08 13:32:54,657] Trial 967 finished with value: 0.9483958289630557 and parameters: {'weight_class_0': 0.9886442399109345, 'weight_class_1': 8.985888876160764, 'weight_class_2': 6.982272981927085}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:54,673] Trial 968 finished with value: 0.9486343052461429 and parameters: {'weight_class_0': 1.0442301666538771, 'weight_class_1': 9.99706037168357, 'weight_class_2': 8.021640356657972}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:54,680] Trial 969 finished with value: 0.9482643241000456 and parameters: {'weight_class_0': 1.0453895321080258, 'weight_class_1': 8.893297347260042, 'weight_class_2': 7.02381980672585}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:54,710] Trial 970 finished with value: 0.9485609142898358 and parameters: {'weight_class_0': 0.36253709731524225, 'weight_class_1': 9.074398490184796, 'weight_class_2': 6.957807627978604}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:54,726] Trial 971 finished with value: 0.9481865146795877 and parameters: {'weight_class_0': 0.31193335126469995, 'weight_class_1': 8.90131723386783, 'weight_class_2': 7.043294916620024}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:54,751] Trial 973 finished with value: 0.9482059784212882 and parameters: {'weight_class_0': 0.31679781970710086, 'weight_class_1': 9.14128049253234, 'weight_class_2': 7.03784235267568}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:32:54,783] Trial 974 finished with value: 0.9479344056930746 and parameters: {'weight_class_0': 0.2849261949410091, 'weight_class_1': 9.089862986152884, 'weight_class_2': 6.863010864441537}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:54,789] Trial 972 finished with value: 0.9483011033474277 and parameters: {'weight_class_0': 0.32506414844326315, 'weight_class_1': 9.104143071752373, 'weight_class_2': 6.964143918190015}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  49%|█████████████████████████████████████████████████████████████████▎                                                                   | 983/2000 [00:19<00:23, 43.48it/s]

[I 2026-07-08 13:32:54,830] Trial 975 finished with value: 0.9117892896694556 and parameters: {'weight_class_0': 4.684319046568927, 'weight_class_1': 9.838442251746129, 'weight_class_2': 7.004529737198002}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:54,861] Trial 976 finished with value: 0.9483756845964081 and parameters: {'weight_class_0': 0.3344430490142564, 'weight_class_1': 9.17089880261121, 'weight_class_2': 7.049937812981832}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:54,880] Trial 978 finished with value: 0.9486445694234797 and parameters: {'weight_class_0': 0.3089334090843142, 'weight_class_1': 9.405477817258886, 'weight_class_2': 4.253092391188406}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:54,882] Trial 977 finished with value: 0.9479163032712804 and parameters: {'weight_class_0': 0.2952721039140469, 'weight_class_1': 9.999021194207927, 'weight_class_2': 6.769649720498555}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:54,900] Trial 979 finished with value: 0.9486360454368566 and parameters: {'weight_class_0': 0.30498628270017, 'weight_class_1': 9.43826124592005, 'weight_class_2': 4.267168334382084}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:54,934] Trial 980 finished with value: 0.9491817488459443 and parameters: {'weight_class_0': 0.6718111439730108, 'weight_class_1': 9.373531799126118, 'weight_class_2': 6.857899856234138}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:54,962] Trial 981 finished with value: 0.9492292777843861 and parameters: {'weight_class_0': 0.6915253341869011, 'weight_class_1': 9.41720527485664, 'weight_class_2': 7.556831939941597}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:55,000] Trial 982 finished with value: 0.9491653747207804 and parameters: {'weight_class_0': 0.6619082800245045, 'weight_class_1': 9.828094127148697, 'weight_class_2': 6.785636518583669}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:55,011] Trial 983 finished with value: 0.9491825286357759 and parameters: {'weight_class_0': 0.6708007999965167, 'weight_class_1': 9.814140820545425, 'weight_class_2': 7.536682638723455}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:32:55,046] Trial 984 finished with value: 0.9460049944311463 and parameters: {'weight_class_0': 0.6699319340240153, 'weight_class_1': 9.402512575705746, 'weight_class_2': 2.598122334042303}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  50%|█████████████████████████████████████████████████████████████████▉                                                                   | 992/2000 [00:19<00:23, 43.42it/s]

[I 2026-07-08 13:32:55,049] Trial 985 finished with value: 0.9491581121136156 and parameters: {'weight_class_0': 0.6353282056884662, 'weight_class_1': 9.417371601718715, 'weight_class_2': 7.511359936217193}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:55,122] Trial 986 finished with value: 0.9492113913348165 and parameters: {'weight_class_0': 0.6741314731697741, 'weight_class_1': 9.37921380326822, 'weight_class_2': 7.501860684483163}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:55,130] Trial 988 finished with value: 0.9491983247028101 and parameters: {'weight_class_0': 0.679134352973733, 'weight_class_1': 9.833878899390184, 'weight_class_2': 7.525948582955086}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:55,152] Trial 987 finished with value: 0.949190042175322 and parameters: {'weight_class_0': 0.6845946956291218, 'weight_class_1': 9.801122860327508, 'weight_class_2': 7.557500372977378}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:55,181] Trial 989 finished with value: 0.9491339909080355 and parameters: {'weight_class_0': 0.6165566691939092, 'weight_class_1': 9.768894489134833, 'weight_class_2': 7.474517576982817}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:55,189] Trial 991 finished with value: 0.9492220161357032 and parameters: {'weight_class_0': 0.689164866522527, 'weight_class_1': 9.40503915937671, 'weight_class_2': 7.517001100469013}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:55,204] Trial 990 finished with value: 0.9492150436869359 and parameters: {'weight_class_0': 0.6885397111457479, 'weight_class_1': 9.822608981103215, 'weight_class_2': 7.390857800894082}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:55,230] Trial 992 finished with value: 0.9491683236902082 and parameters: {'weight_class_0': 0.6449023751540206, 'weight_class_1': 9.400272534584794, 'weight_class_2': 7.474585855527675}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:32:55,256] Trial 993 finished with value: 0.9491331776179459 and parameters: {'weight_class_0': 0.7447981345984479, 'weight_class_1': 9.388655405762721, 'weight_class_2': 7.593946264098671}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  50%|██████████████████████████████████████████████████████████████████                                                                  | 1000/2000 [00:19<00:22, 43.71it/s]

[I 2026-07-08 13:32:55,258] Trial 994 finished with value: 0.9490841560955054 and parameters: {'weight_class_0': 0.7563312132108154, 'weight_class_1': 9.366182947138704, 'weight_class_2': 7.55405772676995}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:55,274] Trial 995 finished with value: 0.9490166622165853 and parameters: {'weight_class_0': 0.7798508563928181, 'weight_class_1': 8.775437332808323, 'weight_class_2': 7.564943031174884}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:55,316] Trial 996 finished with value: 0.9490041145860552 and parameters: {'weight_class_0': 0.7727416286902384, 'weight_class_1': 8.81617510005684, 'weight_class_2': 7.618383170311265}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:55,342] Trial 997 finished with value: 0.9490982027968599 and parameters: {'weight_class_0': 0.751217631955146, 'weight_class_1': 9.205601646072525, 'weight_class_2': 7.550755635477829}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:55,416] Trial 1000 finished with value: 0.9490249311203307 and parameters: {'weight_class_0': 0.8371734637448498, 'weight_class_1': 9.392456294414014, 'weight_class_2': 7.86749977412756}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:55,418] Trial 998 finished with value: 0.9490526864926049 and parameters: {'weight_class_0': 0.7875799271556001, 'weight_class_1': 9.217628680293883, 'weight_class_2': 7.898169976307772}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:55,422] Trial 999 finished with value: 0.9490347083007825 and parameters: {'weight_class_0': 0.807922156185731, 'weight_class_1': 9.21019528941144, 'weight_class_2': 7.854183198822506}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  50%|██████████████████████████████████████████████████████████████████▏                                                                 | 1002/2000 [00:19<00:24, 39.95it/s]

[I 2026-07-08 13:32:55,439] Trial 1001 finished with value: 0.948918682851812 and parameters: {'weight_class_0': 0.8918566510048355, 'weight_class_1': 9.239394295227932, 'weight_class_2': 7.878034981022801}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:55,454] Trial 1002 finished with value: 0.9489447627646487 and parameters: {'weight_class_0': 0.8436409610300473, 'weight_class_1': 9.18478391022097, 'weight_class_2': 7.960376564818778}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  51%|██████████████████████████████████████████████████████████████████▋                                                                 | 1011/2000 [00:19<00:22, 44.20it/s]

[I 2026-07-08 13:32:55,497] Trial 1003 finished with value: 0.9488899727532782 and parameters: {'weight_class_0': 0.8654508335412106, 'weight_class_1': 9.208881572797607, 'weight_class_2': 7.925893751798942}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:55,498] Trial 1004 finished with value: 0.9488965947790323 and parameters: {'weight_class_0': 0.46041032987918173, 'weight_class_1': 9.21109379546715, 'weight_class_2': 7.854432452126633}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:55,528] Trial 1005 finished with value: 0.9488777386918429 and parameters: {'weight_class_0': 0.4547038724838358, 'weight_class_1': 9.171338248365517, 'weight_class_2': 7.875431778210143}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:55,561] Trial 1006 finished with value: 0.9489238089934385 and parameters: {'weight_class_0': 0.8953301917099359, 'weight_class_1': 9.207676163882793, 'weight_class_2': 7.903494266336614}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:55,562] Trial 1007 finished with value: 0.9463305712371112 and parameters: {'weight_class_0': 1.558625424299203, 'weight_class_1': 9.262755541085387, 'weight_class_2': 7.875915576265151}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:55,585] Trial 1009 finished with value: 0.9488960158034465 and parameters: {'weight_class_0': 0.4697978815512378, 'weight_class_1': 9.188077110139526, 'weight_class_2': 7.909235836288509}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:55,591] Trial 1008 finished with value: 0.9463032971460739 and parameters: {'weight_class_0': 1.5539206603454048, 'weight_class_1': 9.124368655732196, 'weight_class_2': 7.879017081689218}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:55,655] Trial 1010 finished with value: 0.9489172860630833 and parameters: {'weight_class_0': 0.4727951741464807, 'weight_class_1': 9.580966762482571, 'weight_class_2': 7.90516821316444}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:55,662] Trial 1011 finished with value: 0.9486181679827235 and parameters: {'weight_class_0': 0.43034937129338713, 'weight_class_1': 9.561836534612144, 'weight_class_2': 8.720492349260544}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:32:55,714] Trial 1012 finished with value: 0.9489457338390258 and parameters: {'weight_class_0': 0.47798480680676125, 'weight_class_1': 9.588577106836285, 'weight_class_2': 7.7834154785345255}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:32:55,724] Trial 1013 finished with value: 0.9487037100558311 and parameters: {'weight_class_0': 0.4297880120048566, 'weight_class_1': 9.576518657804902, 'weight_class_2': 8.12887132269714}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:55,750] Trial 1015 finished with value: 0.9485120999473198 and parameters: {'weight_class_0': 1.0949146191714987, 'weight_class_1': 9.572728324514715, 'weight_class_2': 8.390065722945165}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:55,752] Trial 1014 finished with value: 0.9489676829403594 and parameters: {'weight_class_0': 0.47442915127727797, 'weight_class_1': 9.596346699299204, 'weight_class_2': 7.6990246221530745}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:55,767] Trial 1016 finished with value: 0.9490968420372803 and parameters: {'weight_class_0': 0.5142848000286881, 'weight_class_1': 9.613388180820618, 'weight_class_2': 7.61582121018268}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:55,811] Trial 1017 finished with value: 0.9484879399394767 and parameters: {'weight_class_0': 1.1201752999740238, 'weight_class_1': 9.607175458801686, 'weight_class_2': 8.418859260888185}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:55,816] Trial 1018 finished with value: 0.9486039441548293 and parameters: {'weight_class_0': 1.0500031464348394, 'weight_class_1': 9.587557172341121, 'weight_class_2': 8.165994446211178}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:55,839] Trial 1019 finished with value: 0.948499348680691 and parameters: {'weight_class_0': 1.1146768220118477, 'weight_class_1': 9.58915268806175, 'weight_class_2': 8.264002062614967}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:55,844] Trial 1020 finished with value: 0.948566714795923 and parameters: {'weight_class_0': 1.0678402741922768, 'weight_class_1': 9.575844116424491, 'weight_class_2': 8.24014236727344}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:55,872] Trial 1021 finished with value: 0.9485302607472167 and parameters: {'weight_class_0': 1.1078725562996872, 'weight_class_1': 9.597965978714157, 'weight_class_2': 8.335787192228427}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  51%|███████████████████████████████████████████████████████████████████▍                                                                | 1022/2000 [00:20<00:21, 44.90it/s]

[I 2026-07-08 13:32:55,909] Trial 1022 finished with value: 0.9483261118415006 and parameters: {'weight_class_0': 1.1017909806362152, 'weight_class_1': 9.583543745591067, 'weight_class_2': 7.640794395011562}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  52%|████████████████████████████████████████████████████████████████████                                                                | 1031/2000 [00:20<00:21, 45.59it/s]

[I 2026-07-08 13:32:55,918] Trial 1023 finished with value: 0.9484135110236386 and parameters: {'weight_class_0': 1.1476038634156993, 'weight_class_1': 9.644065392094232, 'weight_class_2': 8.29142404848638}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:55,947] Trial 1024 finished with value: 0.9398292841129537 and parameters: {'weight_class_0': 2.59760634964536, 'weight_class_1': 9.608653729160626, 'weight_class_2': 8.285039881776767}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:55,970] Trial 1025 finished with value: 0.9482185510141093 and parameters: {'weight_class_0': 1.1223309028819832, 'weight_class_1': 9.575821852045335, 'weight_class_2': 7.374414548709378}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:55,989] Trial 1026 finished with value: 0.9482293839717522 and parameters: {'weight_class_0': 1.116263316996404, 'weight_class_1': 9.45676752614417, 'weight_class_2': 7.392159026678101}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:56,005] Trial 1027 finished with value: 0.9486579789047972 and parameters: {'weight_class_0': 1.0429152973838445, 'weight_class_1': 9.457329804935485, 'weight_class_2': 8.29038964835419}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:56,052] Trial 1028 finished with value: 0.948224250796005 and parameters: {'weight_class_0': 1.1022795118751936, 'weight_class_1': 8.848232509387875, 'weight_class_2': 7.345762417016722}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:56,072] Trial 1029 finished with value: 0.9491478247263835 and parameters: {'weight_class_0': 0.5797414531813425, 'weight_class_1': 9.462075330804947, 'weight_class_2': 7.338855020857625}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:56,078] Trial 1030 finished with value: 0.9468555194818261 and parameters: {'weight_class_0': 0.21288900300565416, 'weight_class_1': 8.844284966543448, 'weight_class_2': 7.370446061668803}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:56,089] Trial 1031 finished with value: 0.9469418157960838 and parameters: {'weight_class_0': 0.21946966766648157, 'weight_class_1': 8.95816461510831, 'weight_class_2': 7.383322653113508}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  52%|████████████████████████████████████████████████████████████████████                                                                | 1032/2000 [00:20<00:21, 45.59it/s]

[I 2026-07-08 13:32:56,118] Trial 1032 finished with value: 0.9464057063657348 and parameters: {'weight_class_0': 0.19282596724644624, 'weight_class_1': 8.802732106566058, 'weight_class_2': 7.358979444617236}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  52%|████████████████████████████████████████████████████████████████████▋                                                               | 1041/2000 [00:20<00:20, 47.70it/s]

[I 2026-07-08 13:32:56,152] Trial 1033 finished with value: 0.9491679887489916 and parameters: {'weight_class_0': 0.5635735369342249, 'weight_class_1': 8.814276991601096, 'weight_class_2': 7.358973074197166}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:56,192] Trial 1034 finished with value: 0.9476826516555498 and parameters: {'weight_class_0': 0.2799132336562815, 'weight_class_1': 9.405869774883591, 'weight_class_2': 7.404006662305671}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:56,197] Trial 1037 finished with value: 0.9460984893862138 and parameters: {'weight_class_0': 0.18309917595675806, 'weight_class_1': 8.883471409143604, 'weight_class_2': 7.3624883771024985}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:56,210] Trial 1036 finished with value: 0.9491718223805427 and parameters: {'weight_class_0': 0.5762018690913457, 'weight_class_1': 8.983294570849186, 'weight_class_2': 7.395386821243511}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:56,212] Trial 1035 finished with value: 0.9463192998564347 and parameters: {'weight_class_0': 0.1918046826641765, 'weight_class_1': 8.928149895025657, 'weight_class_2': 7.368162008672458}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:56,229] Trial 1039 finished with value: 0.9463399988531572 and parameters: {'weight_class_0': 0.19104888551075733, 'weight_class_1': 8.880355001098355, 'weight_class_2': 7.350170984883273}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:56,240] Trial 1038 finished with value: 0.9473441819628086 and parameters: {'weight_class_0': 0.241933693227172, 'weight_class_1': 8.83891230539394, 'weight_class_2': 7.404533415415231}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:56,280] Trial 1040 finished with value: 0.9477887031859819 and parameters: {'weight_class_0': 0.2798603489870245, 'weight_class_1': 8.955014771560089, 'weight_class_2': 7.636311786089747}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:56,297] Trial 1041 finished with value: 0.9491567394778366 and parameters: {'weight_class_0': 0.6263323738562331, 'weight_class_1': 9.7857352936098, 'weight_class_2': 7.620348814623953}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  53%|█████████████████████████████████████████████████████████████████████▎                                                              | 1051/2000 [00:20<00:20, 46.28it/s]

[I 2026-07-08 13:32:56,313] Trial 1042 finished with value: 0.949157657565881 and parameters: {'weight_class_0': 0.5894536130926165, 'weight_class_1': 9.836642686451228, 'weight_class_2': 7.631302214763161}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:56,339] Trial 1043 finished with value: 0.9489748957532057 and parameters: {'weight_class_0': 0.8399126745706464, 'weight_class_1': 9.833494897235338, 'weight_class_2': 7.663604480570288}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:56,353] Trial 1044 finished with value: 0.9491045851110224 and parameters: {'weight_class_0': 0.5671371488644165, 'weight_class_1': 9.813380432031332, 'weight_class_2': 7.6453675311862455}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:56,362] Trial 1045 finished with value: 0.9489572342143778 and parameters: {'weight_class_0': 0.8384767494092791, 'weight_class_1': 9.776476661075165, 'weight_class_2': 7.654071937187021}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:56,426] Trial 1046 finished with value: 0.9489260191186005 and parameters: {'weight_class_0': 0.8557170146923292, 'weight_class_1': 9.79884856720185, 'weight_class_2': 7.724519948350652}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:56,458] Trial 1047 finished with value: 0.9489038332843825 and parameters: {'weight_class_0': 0.8773990948692851, 'weight_class_1': 9.719511740122647, 'weight_class_2': 7.642976787906174}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:56,460] Trial 1049 finished with value: 0.9489410868015565 and parameters: {'weight_class_0': 0.859681172126258, 'weight_class_1': 9.810001003841624, 'weight_class_2': 7.679385558192854}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:56,469] Trial 1048 finished with value: 0.9322011351194058 and parameters: {'weight_class_0': 3.2524205794444345, 'weight_class_1': 9.754392558668943, 'weight_class_2': 7.73791816431229}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:56,492] Trial 1050 finished with value: 0.9490442027396845 and parameters: {'weight_class_0': 0.7772761841004073, 'weight_class_1': 9.819906239563482, 'weight_class_2': 7.634257008931448}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:56,536] Trial 1051 finished with value: 0.9488653268407443 and parameters: {'weight_class_0': 0.880326720677977, 'weight_class_1': 9.326389780761104, 'weight_class_2': 7.678217764124376}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:32:56,542] Trial 1052 finished with value: 0.9490356096758662 and parameters: {'weight_class_0': 0.823586806665935, 'weight_class_1': 9.814147905907696, 'weight_class_2': 7.7631053525168765}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:56,572] Trial 1053 finished with value: 0.946600781331333 and parameters: {'weight_class_0': 0.8920955293724763, 'weight_class_1': 9.36620235409658, 'weight_class_2': 3.8658681128638888}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:56,614] Trial 1055 finished with value: 0.6575117674957468 and parameters: {'weight_class_0': 0.002974841370854686, 'weight_class_1': 9.362051506151145, 'weight_class_2': 7.170987375722174}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:56,618] Trial 1054 finished with value: 0.9487401117142392 and parameters: {'weight_class_0': 0.8923830846535301, 'weight_class_1': 9.385015923016637, 'weight_class_2': 7.154968690280577}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:56,632] Trial 1056 finished with value: 0.9489755630401248 and parameters: {'weight_class_0': 0.8565276342423195, 'weight_class_1': 9.365410883562085, 'weight_class_2': 8.053494310456665}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:56,683] Trial 1057 finished with value: 0.9487858501073827 and parameters: {'weight_class_0': 0.8865629782814882, 'weight_class_1': 9.393178554702727, 'weight_class_2': 7.195306013098849}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:56,685] Trial 1058 finished with value: 0.6585470913504347 and parameters: {'weight_class_0': 0.006186885776201412, 'weight_class_1': 9.288982030954923, 'weight_class_2': 8.00032413060351}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:56,718] Trial 1059 finished with value: 0.9488882323314339 and parameters: {'weight_class_0': 0.4698180751121221, 'weight_class_1': 9.35185396207266, 'weight_class_2': 8.045964456953435}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:56,725] Trial 1060 finished with value: 0.9491785174925619 and parameters: {'weight_class_0': 0.6641587791299968, 'weight_class_1': 9.357957192924705, 'weight_class_2': 8.072933941416625}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:32:56,766] Trial 1061 finished with value: 0.9491320144313926 and parameters: {'weight_class_0': 0.45777488312114434, 'weight_class_1': 9.377643826578513, 'weight_class_2': 4.759003560215501}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:56,801] Trial 1062 finished with value: 0.9489477167455757 and parameters: {'weight_class_0': 0.4531229320378509, 'weight_class_1': 9.387974560258286, 'weight_class_2': 7.142208018274675}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:56,811] Trial 1063 finished with value: 0.9488659541381836 and parameters: {'weight_class_0': 0.4570226685015018, 'weight_class_1': 9.368122404067426, 'weight_class_2': 8.057900737569998}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:56,834] Trial 1064 finished with value: 0.9489541866384629 and parameters: {'weight_class_0': 0.45287191497420565, 'weight_class_1': 9.343700581449344, 'weight_class_2': 7.227112471637229}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:56,854] Trial 1066 finished with value: 0.9487728154134051 and parameters: {'weight_class_0': 0.44032210303924146, 'weight_class_1': 9.391377502384035, 'weight_class_2': 8.023546414354918}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:56,856] Trial 1065 finished with value: 0.9490251166250614 and parameters: {'weight_class_0': 0.521569623689597, 'weight_class_1': 8.675132961075807, 'weight_class_2': 8.150131914995734}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:56,886] Trial 1067 finished with value: 0.9490601156787526 and parameters: {'weight_class_0': 0.4443238501593645, 'weight_class_1': 8.655161833358896, 'weight_class_2': 6.163074181238464}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:56,899] Trial 1068 finished with value: 0.9490591911656537 and parameters: {'weight_class_0': 0.44554204731216773, 'weight_class_1': 8.706892368857702, 'weight_class_2': 6.164359999935458}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:56,949] Trial 1069 finished with value: 0.9490043803525979 and parameters: {'weight_class_0': 0.5160325688108827, 'weight_class_1': 9.978118093421893, 'weight_class_2': 8.045649763611674}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  54%|███████████████████████████████████████████████████████████████████████▏                                                            | 1079/2000 [00:21<00:20, 44.94it/s]

[I 2026-07-08 13:32:56,969] Trial 1070 finished with value: 0.9490933721904385 and parameters: {'weight_class_0': 0.48244430662560955, 'weight_class_1': 8.638686080047698, 'weight_class_2': 7.1749520703212735}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:56,989] Trial 1071 finished with value: 0.9486168897855171 and parameters: {'weight_class_0': 0.46495261387772513, 'weight_class_1': 4.064251623783224, 'weight_class_2': 7.180811233395895}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:57,000] Trial 1072 finished with value: 0.9032935449104684 and parameters: {'weight_class_0': 5.299721566364135, 'weight_class_1': 8.630524219427624, 'weight_class_2': 7.482287551621095}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:57,007] Trial 1073 finished with value: 0.9491557120711805 and parameters: {'weight_class_0': 0.573762950279283, 'weight_class_1': 9.660850285698624, 'weight_class_2': 7.539509771925665}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:57,064] Trial 1075 finished with value: 0.9491393733868451 and parameters: {'weight_class_0': 0.6523739484373632, 'weight_class_1': 8.581639457613107, 'weight_class_2': 8.603800058199296}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:57,076] Trial 1074 finished with value: 0.9491502618722779 and parameters: {'weight_class_0': 0.6084960218256524, 'weight_class_1': 9.690800804756831, 'weight_class_2': 7.22660762337674}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:57,096] Trial 1076 finished with value: 0.9492064004639561 and parameters: {'weight_class_0': 0.657797448999832, 'weight_class_1': 9.996927341575125, 'weight_class_2': 7.4977681069769115}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:57,117] Trial 1077 finished with value: 0.949171358902004 and parameters: {'weight_class_0': 0.6875010697522452, 'weight_class_1': 9.1005174469072, 'weight_class_2': 8.642953082158808}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:57,126] Trial 1078 finished with value: 0.9492024567401592 and parameters: {'weight_class_0': 0.6637867397069126, 'weight_class_1': 9.988690939895989, 'weight_class_2': 7.507388080311521}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:57,185] Trial 1080 finished with value: 0.9491989249530394 and parameters: {'weight_class_0': 0.7187415753233004, 'weight_class_1': 9.991876480066535, 'weight_class_2': 7.510085040340051}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  54%|███████████████████████████████████████████████████████████████████████▊                                                            | 1089/2000 [00:21<00:20, 44.60it/s]

[I 2026-07-08 13:32:57,187] Trial 1081 finished with value: 0.9492047807663614 and parameters: {'weight_class_0': 0.6730556555121603, 'weight_class_1': 9.98599020665896, 'weight_class_2': 7.491384793634497}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:57,188] Trial 1079 finished with value: 0.9491520121838734 and parameters: {'weight_class_0': 0.6801055714557223, 'weight_class_1': 9.985386040359188, 'weight_class_2': 8.866341190485956}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:57,238] Trial 1082 finished with value: 0.9492440086627539 and parameters: {'weight_class_0': 0.6938511566085835, 'weight_class_1': 9.99464138069414, 'weight_class_2': 7.530644629423158}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:57,265] Trial 1083 finished with value: 0.9492116584454294 and parameters: {'weight_class_0': 0.6536394719201424, 'weight_class_1': 9.03505301294224, 'weight_class_2': 7.536956755047647}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:57,294] Trial 1085 finished with value: 0.949215853484335 and parameters: {'weight_class_0': 0.6866360564323889, 'weight_class_1': 9.98715951451149, 'weight_class_2': 7.536616280347966}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:57,302] Trial 1084 finished with value: 0.9492361218937111 and parameters: {'weight_class_0': 0.6868386698789168, 'weight_class_1': 9.044780015436649, 'weight_class_2': 7.4677382072404725}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:57,318] Trial 1086 finished with value: 0.9274456707218942 and parameters: {'weight_class_0': 3.63676605891309, 'weight_class_1': 9.991167514518331, 'weight_class_2': 7.499331888160082}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:57,349] Trial 1087 finished with value: 0.9329138503549307 and parameters: {'weight_class_0': 1.4242617562440474, 'weight_class_1': 6.9648424770602615, 'weight_class_2': 2.913303035968395}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:57,358] Trial 1088 finished with value: 0.9491700806039921 and parameters: {'weight_class_0': 0.7195444019278119, 'weight_class_1': 9.986475704932538, 'weight_class_2': 7.45819327483568}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:57,395] Trial 1089 finished with value: 0.9491914748880074 and parameters: {'weight_class_0': 0.7140132052250415, 'weight_class_1': 9.878334922558123, 'weight_class_2': 7.478793929632797}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  55%|████████████████████████████████████████████████████████████████████████▍                                                           | 1098/2000 [00:21<00:19, 45.23it/s]

[I 2026-07-08 13:32:57,404] Trial 1090 finished with value: 0.9491909712090779 and parameters: {'weight_class_0': 0.7005772444424543, 'weight_class_1': 9.853321102238215, 'weight_class_2': 7.535533765112532}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:57,423] Trial 1091 finished with value: 0.9486138668732078 and parameters: {'weight_class_0': 0.999912246209101, 'weight_class_1': 9.868708472774655, 'weight_class_2': 7.499720911807497}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:57,441] Trial 1092 finished with value: 0.9487059104017522 and parameters: {'weight_class_0': 0.9529690821656567, 'weight_class_1': 9.982624957776157, 'weight_class_2': 7.541378408400424}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:57,456] Trial 1093 finished with value: 0.9471400928304005 and parameters: {'weight_class_0': 1.435450965972319, 'weight_class_1': 9.99107755841119, 'weight_class_2': 7.732268601286803}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:57,487] Trial 1094 finished with value: 0.9486792440680224 and parameters: {'weight_class_0': 0.9856609469743618, 'weight_class_1': 9.865340168299651, 'weight_class_2': 7.772503450103372}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:57,501] Trial 1095 finished with value: 0.9488382016852416 and parameters: {'weight_class_0': 0.9467618271317113, 'weight_class_1': 9.855713042413866, 'weight_class_2': 7.80726568215819}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:57,555] Trial 1096 finished with value: 0.9468695705107496 and parameters: {'weight_class_0': 1.4460943448535282, 'weight_class_1': 9.054143456552783, 'weight_class_2': 7.836542780683398}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:57,593] Trial 1098 finished with value: 0.9486444539239757 and parameters: {'weight_class_0': 0.9815322799533012, 'weight_class_1': 9.03577621411701, 'weight_class_2': 7.79095285077038}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:57,595] Trial 1099 finished with value: 0.9487583078854795 and parameters: {'weight_class_0': 0.9670403268550583, 'weight_class_1': 9.13477423873829, 'weight_class_2': 7.808032962907823}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:32:57,596] Trial 1097 finished with value: 0.9486493326953962 and parameters: {'weight_class_0': 0.9922664898842544, 'weight_class_1': 9.07446792279856, 'weight_class_2': 7.832662806296297}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:57,607] Trial 1101 finished with value: 0.9485255825226769 and parameters: {'weight_class_0': 1.0248559674796407, 'weight_class_1': 8.981417056767784, 'weight_class_2': 7.741900082068905}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:57,631] Trial 1100 finished with value: 0.9486784679431631 and parameters: {'weight_class_0': 0.9801447517013951, 'weight_class_1': 9.08954516238557, 'weight_class_2': 7.724881898747398}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:57,681] Trial 1103 finished with value: 0.9485695108974798 and parameters: {'weight_class_0': 1.0061292329941827, 'weight_class_1': 9.04147386489705, 'weight_class_2': 7.812189016872375}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:57,683] Trial 1102 finished with value: 0.9486663457702561 and parameters: {'weight_class_0': 0.9913131203883072, 'weight_class_1': 9.099282541680953, 'weight_class_2': 7.796135302681552}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:57,695] Trial 1105 finished with value: 0.9486649220988851 and parameters: {'weight_class_0': 0.9952589388191158, 'weight_class_1': 9.116866334469368, 'weight_class_2': 7.814379444905136}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:57,706] Trial 1104 finished with value: 0.9486000863650105 and parameters: {'weight_class_0': 0.9936534537889741, 'weight_class_1': 9.048549316808089, 'weight_class_2': 7.670194905223708}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:57,725] Trial 1106 finished with value: 0.9480268698472725 and parameters: {'weight_class_0': 1.1953110160799467, 'weight_class_1': 9.050885969354713, 'weight_class_2': 7.798804277213581}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:57,761] Trial 1107 finished with value: 0.9482715516316903 and parameters: {'weight_class_0': 1.1298031129916009, 'weight_class_1': 9.112676331572013, 'weight_class_2': 7.813800143123917}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:32:57,822] Trial 1108 finished with value: 0.9480627389065251 and parameters: {'weight_class_0': 1.1924465204232337, 'weight_class_1': 9.167786351236533, 'weight_class_2': 7.799332833679458}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:57,847] Trial 1109 finished with value: 0.9480822246347317 and parameters: {'weight_class_0': 1.1947162192326641, 'weight_class_1': 9.633798895999583, 'weight_class_2': 7.599527768601434}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:57,853] Trial 1110 finished with value: 0.9475749074025023 and parameters: {'weight_class_0': 1.2913153002573843, 'weight_class_1': 9.144824620316168, 'weight_class_2': 7.687625579949334}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:57,864] Trial 1111 finished with value: 0.9483665590719387 and parameters: {'weight_class_0': 0.35514034626428076, 'weight_class_1': 9.619796108400354, 'weight_class_2': 7.5904433175890516}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:57,897] Trial 1112 finished with value: 0.9479866068725776 and parameters: {'weight_class_0': 1.2214358647471593, 'weight_class_1': 9.611785583561803, 'weight_class_2': 7.615850623358918}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:57,931] Trial 1113 finished with value: 0.9480986436894595 and parameters: {'weight_class_0': 0.32423276262534667, 'weight_class_1': 9.642771417688898, 'weight_class_2': 7.371079529600353}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:57,960] Trial 1114 finished with value: 0.8921175744438031 and parameters: {'weight_class_0': 6.551083375955171, 'weight_class_1': 9.628108490866174, 'weight_class_2': 7.335197556009895}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:57,972] Trial 1115 finished with value: 0.9485574757381791 and parameters: {'weight_class_0': 0.38221235780364315, 'weight_class_1': 9.589185841631876, 'weight_class_2': 7.357872312175165}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:57,986] Trial 1116 finished with value: 0.9473881601883828 and parameters: {'weight_class_0': 0.2602733123837988, 'weight_class_1': 9.632408578140765, 'weight_class_2': 7.340137699954669}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  56%|██████████████████████████████████████████████████████████████████████████▎                                                         | 1126/2000 [00:22<00:19, 45.84it/s]

[I 2026-07-08 13:32:57,991] Trial 1117 finished with value: 0.9476784153342294 and parameters: {'weight_class_0': 0.2792781921333273, 'weight_class_1': 9.416683992587, 'weight_class_2': 7.331142210892256}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:58,025] Trial 1119 finished with value: 0.9481369695322174 and parameters: {'weight_class_0': 0.3242865684569762, 'weight_class_1': 9.637229973413515, 'weight_class_2': 7.314182442067459}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:58,044] Trial 1118 finished with value: 0.9479501565327912 and parameters: {'weight_class_0': 0.3046953834578152, 'weight_class_1': 9.670592830264217, 'weight_class_2': 7.326102249502518}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:58,071] Trial 1120 finished with value: 0.9484179134563022 and parameters: {'weight_class_0': 0.3525261965733681, 'weight_class_1': 9.647303856726294, 'weight_class_2': 7.327421238105743}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:58,107] Trial 1121 finished with value: 0.9479788638094718 and parameters: {'weight_class_0': 0.3108467726470884, 'weight_class_1': 9.629307854425214, 'weight_class_2': 7.414133951773047}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:58,116] Trial 1122 finished with value: 0.9481038557650642 and parameters: {'weight_class_0': 0.3208848963833381, 'weight_class_1': 9.527216314565678, 'weight_class_2': 7.3121569873907415}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:58,158] Trial 1124 finished with value: 0.949048500939512 and parameters: {'weight_class_0': 0.77318553460712, 'weight_class_1': 9.453254709403812, 'weight_class_2': 7.345731711016303}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:58,163] Trial 1123 finished with value: 0.9478169471202321 and parameters: {'weight_class_0': 0.29545885414305967, 'weight_class_1': 9.58790864774844, 'weight_class_2': 7.3341803763932}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:58,188] Trial 1125 finished with value: 0.9480352947930802 and parameters: {'weight_class_0': 0.3132170156844967, 'weight_class_1': 9.574738502171357, 'weight_class_2': 7.316688853447788}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:58,217] Trial 1126 finished with value: 0.9479516072874846 and parameters: {'weight_class_0': 0.7782747844153031, 'weight_class_1': 4.7607648668418046, 'weight_class_2': 7.268431008821046}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:32:58,255] Trial 1127 finished with value: 0.9491509381387401 and parameters: {'weight_class_0': 0.6990783315279363, 'weight_class_1': 9.485034026146621, 'weight_class_2': 7.193786857722737}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:58,260] Trial 1129 finished with value: 0.94909113829745 and parameters: {'weight_class_0': 0.7538456102346328, 'weight_class_1': 9.769261115997837, 'weight_class_2': 7.512526988841269}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:58,273] Trial 1128 finished with value: 0.9490649605874676 and parameters: {'weight_class_0': 0.7454624089426045, 'weight_class_1': 9.473581776659174, 'weight_class_2': 7.518354974249964}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:58,324] Trial 1131 finished with value: 0.949074092331398 and parameters: {'weight_class_0': 0.7678070185545027, 'weight_class_1': 9.472725198660939, 'weight_class_2': 7.535686335406396}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:58,332] Trial 1130 finished with value: 0.949067605890118 and parameters: {'weight_class_0': 0.7709769659483278, 'weight_class_1': 9.477815680157944, 'weight_class_2': 7.559822303327641}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:58,366] Trial 1132 finished with value: 0.9479268156314307 and parameters: {'weight_class_0': 0.7715239582544589, 'weight_class_1': 4.655841389998011, 'weight_class_2': 7.611790934412948}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:58,379] Trial 1133 finished with value: 0.9490368311015525 and parameters: {'weight_class_0': 0.805435247214654, 'weight_class_1': 9.815482764376384, 'weight_class_2': 7.596759576349321}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:58,388] Trial 1134 finished with value: 0.9490869748621193 and parameters: {'weight_class_0': 0.7612840902815742, 'weight_class_1': 9.237726815513252, 'weight_class_2': 7.552591200185679}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:58,423] Trial 1135 finished with value: 0.9490422225521914 and parameters: {'weight_class_0': 0.7680379604766941, 'weight_class_1': 9.766980238079935, 'weight_class_2': 7.598874274872479}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:32:58,432] Trial 1136 finished with value: 0.9490795578938728 and parameters: {'weight_class_0': 0.7679569185620972, 'weight_class_1': 9.25622898967825, 'weight_class_2': 7.522522440994166}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:58,473] Trial 1137 finished with value: 0.9490348749695303 and parameters: {'weight_class_0': 0.7681682412558741, 'weight_class_1': 9.792432136031335, 'weight_class_2': 7.576298603097667}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:58,480] Trial 1138 finished with value: 0.9490730262252752 and parameters: {'weight_class_0': 0.761117660414502, 'weight_class_1': 9.248020010997655, 'weight_class_2': 7.5417727551990135}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:58,514] Trial 1139 finished with value: 0.9491545330509586 and parameters: {'weight_class_0': 0.5678544850674241, 'weight_class_1': 9.210218241822927, 'weight_class_2': 7.615369303617026}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:58,517] Trial 1140 finished with value: 0.9491534879110892 and parameters: {'weight_class_0': 0.5732324568651352, 'weight_class_1': 9.28609211310329, 'weight_class_2': 7.611332884105744}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:58,550] Trial 1141 finished with value: 0.9491308576601889 and parameters: {'weight_class_0': 0.632577685323467, 'weight_class_1': 9.228690693606152, 'weight_class_2': 7.964457047873494}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:58,584] Trial 1142 finished with value: 0.9490997003257339 and parameters: {'weight_class_0': 0.5682699613239249, 'weight_class_1': 9.805821211922353, 'weight_class_2': 7.626498579844177}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:58,625] Trial 1143 finished with value: 0.9490881048669747 and parameters: {'weight_class_0': 0.5706474336159139, 'weight_class_1': 9.251885775478856, 'weight_class_2': 7.9686421493643085}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:58,646] Trial 1144 finished with value: 0.9490513114307316 and parameters: {'weight_class_0': 0.5150292965939851, 'weight_class_1': 9.814102715298107, 'weight_class_2': 7.088653256492114}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  58%|████████████████████████████████████████████████████████████████████████████▏                                                       | 1154/2000 [00:23<00:19, 43.63it/s]

[I 2026-07-08 13:32:58,658] Trial 1145 finished with value: 0.9491067629207466 and parameters: {'weight_class_0': 0.5639466422807523, 'weight_class_1': 9.800503257230748, 'weight_class_2': 7.9426948623544975}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:58,671] Trial 1146 finished with value: 0.9490971079630728 and parameters: {'weight_class_0': 0.5725766698189895, 'weight_class_1': 9.816094455113086, 'weight_class_2': 7.988464081072149}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:58,689] Trial 1147 finished with value: 0.949063376245789 and parameters: {'weight_class_0': 0.5135050220849949, 'weight_class_1': 9.99864810001084, 'weight_class_2': 7.152758891808721}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:58,715] Trial 1148 finished with value: 0.9490214507853075 and parameters: {'weight_class_0': 0.5205772937054397, 'weight_class_1': 9.990535941833096, 'weight_class_2': 7.9827259515030144}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:58,777] Trial 1149 finished with value: 0.949088790434402 and parameters: {'weight_class_0': 0.5441384054594434, 'weight_class_1': 9.828063366321057, 'weight_class_2': 7.954696929382287}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:58,780] Trial 1150 finished with value: 0.9491001393043031 and parameters: {'weight_class_0': 0.5672593431041609, 'weight_class_1': 9.801823522291096, 'weight_class_2': 7.992741714686953}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:58,786] Trial 1151 finished with value: 0.9491292331668585 and parameters: {'weight_class_0': 0.5250318256476888, 'weight_class_1': 9.829548028581998, 'weight_class_2': 7.083027025498502}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:58,806] Trial 1152 finished with value: 0.949068882987882 and parameters: {'weight_class_0': 0.5282414005604572, 'weight_class_1': 9.82672025925035, 'weight_class_2': 8.01444077028001}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:58,841] Trial 1153 finished with value: 0.6794674866370114 and parameters: {'weight_class_0': 0.01400946874783815, 'weight_class_1': 9.997509381095293, 'weight_class_2': 7.986996875108536}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:58,851] Trial 1154 finished with value: 0.9490828212957942 and parameters: {'weight_class_0': 0.5375114413106853, 'weight_class_1': 9.815911915895535, 'weight_class_2': 7.957396224026312}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  58%|████████████████████████████████████████████████████████████████████████████▊                                                       | 1163/2000 [00:23<00:19, 43.58it/s]

[I 2026-07-08 13:32:58,853] Trial 1155 finished with value: 0.9490503424716631 and parameters: {'weight_class_0': 0.5096984673105421, 'weight_class_1': 8.919551294470438, 'weight_class_2': 7.13447949048407}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:58,880] Trial 1156 finished with value: 0.9490835412886498 and parameters: {'weight_class_0': 0.5045306065010939, 'weight_class_1': 9.988681648913257, 'weight_class_2': 7.12627961133721}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:58,912] Trial 1157 finished with value: 0.9485674955442361 and parameters: {'weight_class_0': 0.9514452837416443, 'weight_class_1': 8.84908019071081, 'weight_class_2': 7.078719554418007}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:58,931] Trial 1158 finished with value: 0.8756778195267586 and parameters: {'weight_class_0': 0.04151628056269663, 'weight_class_1': 8.965630833643836, 'weight_class_2': 7.142082688499559}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:58,963] Trial 1159 finished with value: 0.8502068345824235 and parameters: {'weight_class_0': 0.030232214860474782, 'weight_class_1': 8.865704425978176, 'weight_class_2': 3.43706287109079}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:58,996] Trial 1160 finished with value: 0.9444163665055707 and parameters: {'weight_class_0': 0.14286242629812218, 'weight_class_1': 8.894915150280198, 'weight_class_2': 7.143609523989271}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:59,016] Trial 1161 finished with value: 0.9442027304908969 and parameters: {'weight_class_0': 0.10748548889970067, 'weight_class_1': 6.014030559104288, 'weight_class_2': 7.135827459451033}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:59,053] Trial 1162 finished with value: 0.9478676113441038 and parameters: {'weight_class_0': 1.2027166914432832, 'weight_class_1': 9.433045073827829, 'weight_class_2': 7.195600430181546}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:59,071] Trial 1163 finished with value: 0.943475796313694 and parameters: {'weight_class_0': 0.13059857955523813, 'weight_class_1': 8.912011746864716, 'weight_class_2': 7.165393524436335}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  59%|█████████████████████████████████████████████████████████████████████████████▍                                                      | 1173/2000 [00:23<00:18, 44.06it/s]

[I 2026-07-08 13:32:59,074] Trial 1165 finished with value: 0.9486185336457664 and parameters: {'weight_class_0': 0.9512616078803491, 'weight_class_1': 8.692229524036447, 'weight_class_2': 7.198149130417988}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:59,107] Trial 1164 finished with value: 0.920831667955086 and parameters: {'weight_class_0': 0.9213924701466951, 'weight_class_1': 8.908595798528205, 'weight_class_2': 1.2266096176101597}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:59,126] Trial 1166 finished with value: 0.9485641733042862 and parameters: {'weight_class_0': 0.9616646640369855, 'weight_class_1': 8.815009669905562, 'weight_class_2': 7.1412080706997285}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:59,138] Trial 1167 finished with value: 0.9485623094285 and parameters: {'weight_class_0': 0.9698757042722268, 'weight_class_1': 8.76171474117684, 'weight_class_2': 7.237163948166477}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:59,166] Trial 1168 finished with value: 0.9487097908566282 and parameters: {'weight_class_0': 0.9149668690097789, 'weight_class_1': 9.454786257341869, 'weight_class_2': 7.182530182358224}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:59,195] Trial 1170 finished with value: 0.948881530118205 and parameters: {'weight_class_0': 0.913401279861692, 'weight_class_1': 9.46934958015795, 'weight_class_2': 7.79367899882762}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:59,216] Trial 1169 finished with value: 0.9475205921855432 and parameters: {'weight_class_0': 1.3226342406359497, 'weight_class_1': 9.420889043127605, 'weight_class_2': 7.780877950826897}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:59,236] Trial 1172 finished with value: 0.9477274353605368 and parameters: {'weight_class_0': 1.2902370381881787, 'weight_class_1': 9.47794167447854, 'weight_class_2': 7.804470951234582}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:59,241] Trial 1171 finished with value: 0.9477351614746995 and parameters: {'weight_class_0': 1.28597559532057, 'weight_class_1': 9.377868736601542, 'weight_class_2': 7.776370094350747}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:59,275] Trial 1173 finished with value: 0.9475304069834376 and parameters: {'weight_class_0': 1.3206319737865215, 'weight_class_1': 9.423378661432258, 'weight_class_2': 7.7298282078764675}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  59%|██████████████████████████████████████████████████████████████████████████████                                                      | 1183/2000 [00:23<00:19, 42.08it/s]

[I 2026-07-08 13:32:59,339] Trial 1174 finished with value: 0.9489277735806919 and parameters: {'weight_class_0': 0.8743552392492134, 'weight_class_1': 9.480273861106891, 'weight_class_2': 7.769176231485077}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:59,366] Trial 1176 finished with value: 0.9478360937948289 and parameters: {'weight_class_0': 1.2676923637193471, 'weight_class_1': 9.552678864479782, 'weight_class_2': 7.7507863459148}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:59,372] Trial 1175 finished with value: 0.9258379088312396 and parameters: {'weight_class_0': 0.8902863477308409, 'weight_class_1': 1.2823681399690567, 'weight_class_2': 7.724217626337929}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:59,394] Trial 1177 finished with value: 0.9471391750097204 and parameters: {'weight_class_0': 1.409992915907723, 'weight_class_1': 9.455868243355185, 'weight_class_2': 7.733079575886138}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:59,410] Trial 1178 finished with value: 0.9476823983713505 and parameters: {'weight_class_0': 1.3075857236084434, 'weight_class_1': 9.470818324302481, 'weight_class_2': 7.786817430635284}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:59,447] Trial 1179 finished with value: 0.947589876342397 and parameters: {'weight_class_0': 1.3211030222103326, 'weight_class_1': 9.6548344117808, 'weight_class_2': 7.725744069061603}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:59,464] Trial 1180 finished with value: 0.9477507155068445 and parameters: {'weight_class_0': 1.2596111725473318, 'weight_class_1': 9.638868074936706, 'weight_class_2': 7.457241111012999}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:59,465] Trial 1181 finished with value: 0.9480451819933705 and parameters: {'weight_class_0': 1.182143934042497, 'weight_class_1': 9.64701031607216, 'weight_class_2': 7.413282646088386}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:59,508] Trial 1182 finished with value: 0.9483102531329615 and parameters: {'weight_class_0': 0.3455074805046644, 'weight_class_1': 9.650925319879894, 'weight_class_2': 7.41825237830858}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:59,535] Trial 1183 finished with value: 0.9483669193562436 and parameters: {'weight_class_0': 0.3508145365356673, 'weight_class_1': 9.676161487846107, 'weight_class_2': 7.423633138560952}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  60%|██████████████████████████████████████████████████████████████████████████████▋                                                     | 1193/2000 [00:24<00:19, 42.14it/s]

[I 2026-07-08 13:32:59,540] Trial 1185 finished with value: 0.9482836019552195 and parameters: {'weight_class_0': 0.35343057305937886, 'weight_class_1': 3.5621277601519794, 'weight_class_2': 7.4330027288103}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:59,558] Trial 1184 finished with value: 0.9490371175824115 and parameters: {'weight_class_0': 0.7856213923356286, 'weight_class_1': 9.70374623166671, 'weight_class_2': 7.408661392473328}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:59,614] Trial 1186 finished with value: 0.9484006772723008 and parameters: {'weight_class_0': 0.35559338312506905, 'weight_class_1': 9.669354441238283, 'weight_class_2': 7.4200232592021775}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:59,643] Trial 1187 finished with value: 0.9478835036436585 and parameters: {'weight_class_0': 0.3036942408905769, 'weight_class_1': 9.691471436112174, 'weight_class_2': 7.418630738736381}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:59,658] Trial 1188 finished with value: 0.9483050410573569 and parameters: {'weight_class_0': 0.3459917699316635, 'weight_class_1': 9.682110140651872, 'weight_class_2': 7.398402324414722}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:59,702] Trial 1189 finished with value: 0.9483657942962639 and parameters: {'weight_class_0': 0.3510793030090214, 'weight_class_1': 9.685014599719677, 'weight_class_2': 7.435905865455759}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:59,716] Trial 1190 finished with value: 0.948515408211716 and parameters: {'weight_class_0': 0.36434509118798786, 'weight_class_1': 9.213090614795288, 'weight_class_2': 7.412546732333464}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:59,722] Trial 1191 finished with value: 0.9488065533834619 and parameters: {'weight_class_0': 0.3850489986158595, 'weight_class_1': 8.51305424299969, 'weight_class_2': 6.856109801160198}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:59,746] Trial 1192 finished with value: 0.8798713028664352 and parameters: {'weight_class_0': 7.3193647085155416, 'weight_class_1': 8.568113749690182, 'weight_class_2': 6.848911380940192}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  60%|███████████████████████████████████████████████████████████████████████████████▎                                                    | 1201/2000 [00:24<00:19, 40.55it/s]

[I 2026-07-08 13:32:59,788] Trial 1193 finished with value: 0.949231230786165 and parameters: {'weight_class_0': 0.720135474895196, 'weight_class_1': 9.996761769840711, 'weight_class_2': 8.150928707959377}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:59,791] Trial 1195 finished with value: 0.9491565295605057 and parameters: {'weight_class_0': 0.6639548093146435, 'weight_class_1': 9.99499635055061, 'weight_class_2': 6.884599508346465}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:59,813] Trial 1194 finished with value: 0.9491002456775194 and parameters: {'weight_class_0': 0.7014818453578504, 'weight_class_1': 9.216478642828076, 'weight_class_2': 6.881527157006996}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:59,846] Trial 1196 finished with value: 0.94911683499356 and parameters: {'weight_class_0': 0.690621505858583, 'weight_class_1': 9.195411348424406, 'weight_class_2': 6.874561886812427}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:59,857] Trial 1197 finished with value: 0.9491747317045883 and parameters: {'weight_class_0': 0.6694282069473887, 'weight_class_1': 9.998528592712319, 'weight_class_2': 8.149575978818877}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:59,885] Trial 1198 finished with value: 0.9491097514322941 and parameters: {'weight_class_0': 0.7096754906395146, 'weight_class_1': 9.204857090351666, 'weight_class_2': 6.896485595081455}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:59,939] Trial 1201 finished with value: 0.9491737770603796 and parameters: {'weight_class_0': 0.6765448652650703, 'weight_class_1': 9.24786821651678, 'weight_class_2': 6.912412223330983}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:59,960] Trial 1199 finished with value: 0.8937778225917375 and parameters: {'weight_class_0': 6.060791035296568, 'weight_class_1': 9.215424310208471, 'weight_class_2': 6.910564306432166}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:32:59,965] Trial 1200 finished with value: 0.9490826916146773 and parameters: {'weight_class_0': 0.6883438660064383, 'weight_class_1': 8.585810454473084, 'weight_class_2': 6.886222664189138}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  60%|███████████████████████████████████████████████████████████████████████████████▊                                                    | 1210/2000 [00:24<00:19, 40.30it/s]

[I 2026-07-08 13:33:00,007] Trial 1202 finished with value: 0.9491660970166537 and parameters: {'weight_class_0': 0.7034844739922025, 'weight_class_1': 9.209342283606118, 'weight_class_2': 8.058849670103479}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:00,012] Trial 1203 finished with value: 0.9491468969879584 and parameters: {'weight_class_0': 0.6818124834069775, 'weight_class_1': 9.194829118117951, 'weight_class_2': 8.134608052454347}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:00,038] Trial 1204 finished with value: 0.9492210783690228 and parameters: {'weight_class_0': 0.7489194209921651, 'weight_class_1': 9.97253168275668, 'weight_class_2': 8.41430813215659}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:00,057] Trial 1206 finished with value: 0.9472278428964088 and parameters: {'weight_class_0': 1.0550222816165649, 'weight_class_1': 5.584625631380291, 'weight_class_2': 8.205217896952126}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:00,076] Trial 1205 finished with value: 0.9492201946653812 and parameters: {'weight_class_0': 0.7509055709175079, 'weight_class_1': 9.90741104573215, 'weight_class_2': 8.397150287173922}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:00,085] Trial 1207 finished with value: 0.9486035987201132 and parameters: {'weight_class_0': 1.0860567442334286, 'weight_class_1': 9.960354420412797, 'weight_class_2': 8.369549350068278}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:00,125] Trial 1208 finished with value: 0.9488384810291833 and parameters: {'weight_class_0': 0.9964677254102648, 'weight_class_1': 9.868639582533865, 'weight_class_2': 8.423968793970555}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:00,171] Trial 1210 finished with value: 0.9490166650384387 and parameters: {'weight_class_0': 0.8733858224160762, 'weight_class_1': 9.89458569540832, 'weight_class_2': 8.239235668378539}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:00,173] Trial 1209 finished with value: 0.948599470997828 and parameters: {'weight_class_0': 1.0772138554839628, 'weight_class_1': 9.821871663832738, 'weight_class_2': 8.168207805356653}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  61%|████████████████████████████████████████████████████████████████████████████████▌                                                   | 1220/2000 [00:24<00:17, 44.12it/s]

[I 2026-07-08 13:33:00,203] Trial 1211 finished with value: 0.9488597123837604 and parameters: {'weight_class_0': 1.0117461313767988, 'weight_class_1': 9.84663670167404, 'weight_class_2': 8.30377986052024}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:00,210] Trial 1212 finished with value: 0.9487606257950173 and parameters: {'weight_class_0': 1.0431839424199782, 'weight_class_1': 9.882812354697728, 'weight_class_2': 8.349110943295091}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:00,262] Trial 1213 finished with value: 0.9488568650410184 and parameters: {'weight_class_0': 1.012274192761927, 'weight_class_1': 9.875352618057434, 'weight_class_2': 8.272702731019873}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:00,287] Trial 1215 finished with value: 0.9467409634503191 and parameters: {'weight_class_0': 1.5605031261012052, 'weight_class_1': 9.84398440111719, 'weight_class_2': 8.078331862393648}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:00,297] Trial 1214 finished with value: 0.9488379159857302 and parameters: {'weight_class_0': 1.0759468578674922, 'weight_class_1': 9.963214486088049, 'weight_class_2': 8.906840081188749}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:00,320] Trial 1216 finished with value: 0.9491393555918607 and parameters: {'weight_class_0': 0.8636815127816397, 'weight_class_1': 9.980763361951619, 'weight_class_2': 9.153970767336393}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:00,329] Trial 1217 finished with value: 0.9487283523057886 and parameters: {'weight_class_0': 1.0811299566221346, 'weight_class_1': 9.994023928106593, 'weight_class_2': 8.705216905040617}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:00,368] Trial 1218 finished with value: 0.9490012250434421 and parameters: {'weight_class_0': 0.9002909533136234, 'weight_class_1': 9.955315067530977, 'weight_class_2': 8.415795174712578}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:00,399] Trial 1219 finished with value: 0.9489473368801132 and parameters: {'weight_class_0': 0.9076203921126466, 'weight_class_1': 9.961927222297252, 'weight_class_2': 8.365583965152242}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:00,437] Trial 1220 finished with value: 0.9490077883773856 and parameters: {'weight_class_0': 0.876075658849961, 'weight_class_1': 9.99686857377364, 'weight_class_2': 8.648925968740818}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:33:00,443] Trial 1221 finished with value: 0.9490355936004313 and parameters: {'weight_class_0': 0.8596562119769184, 'weight_class_1': 9.880755860208685, 'weight_class_2': 8.55746054332048}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:00,446] Trial 1222 finished with value: 0.9489803420482312 and parameters: {'weight_class_0': 0.9043153396262956, 'weight_class_1': 9.995245441831948, 'weight_class_2': 8.404366158819013}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:00,493] Trial 1223 finished with value: 0.9490990777675771 and parameters: {'weight_class_0': 0.8447465642225056, 'weight_class_1': 9.949800278196669, 'weight_class_2': 8.56575894266024}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:00,523] Trial 1224 finished with value: 0.9491613282757075 and parameters: {'weight_class_0': 0.8008692783296558, 'weight_class_1': 9.993004732916878, 'weight_class_2': 8.351158759668012}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:00,532] Trial 1225 finished with value: 0.9489692330414576 and parameters: {'weight_class_0': 0.8865096171841318, 'weight_class_1': 9.935700636119405, 'weight_class_2': 8.162426774802782}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:00,570] Trial 1227 finished with value: 0.9490831594777647 and parameters: {'weight_class_0': 0.8450629838907004, 'weight_class_1': 9.963318599565213, 'weight_class_2': 8.46958928835183}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:00,580] Trial 1226 finished with value: 0.9491447543850103 and parameters: {'weight_class_0': 0.8188759983081141, 'weight_class_1': 9.835813836664643, 'weight_class_2': 8.627803093863191}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:00,610] Trial 1228 finished with value: 0.9490452921894156 and parameters: {'weight_class_0': 0.8597325450875146, 'weight_class_1': 9.98400335307157, 'weight_class_2': 8.376351132647828}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:00,633] Trial 1229 finished with value: 0.9490980028257331 and parameters: {'weight_class_0': 0.8463280667962696, 'weight_class_1': 9.799085758839093, 'weight_class_2': 8.825105693791448}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:00,637] Trial 1230 finished with value: 0.9491780024026767 and parameters: {'weight_class_0': 0.7936353122950606, 'weight_class_1': 9.798592017967728, 'weight_class_2': 8.730139970748853}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:33:00,653] Trial 1231 finished with value: 0.9491245981778702 and parameters: {'weight_class_0': 0.8190232313247987, 'weight_class_1': 9.785533287063359, 'weight_class_2': 8.336720009880855}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:00,705] Trial 1232 finished with value: 0.9123724197830771 and parameters: {'weight_class_0': 5.08499856556069, 'weight_class_1': 9.772439519763905, 'weight_class_2': 8.236475962554481}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:00,721] Trial 1233 finished with value: 0.9490991349738908 and parameters: {'weight_class_0': 0.5794305444384356, 'weight_class_1': 9.766214374851442, 'weight_class_2': 8.09313533567888}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:00,744] Trial 1234 finished with value: 0.9490475636998469 and parameters: {'weight_class_0': 0.6084259707911773, 'weight_class_1': 9.749226269276338, 'weight_class_2': 8.409601714509156}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:00,794] Trial 1235 finished with value: 0.9489598205351776 and parameters: {'weight_class_0': 0.538954025916856, 'weight_class_1': 9.781606262093531, 'weight_class_2': 8.623917132976702}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:00,810] Trial 1236 finished with value: 0.9489797609756866 and parameters: {'weight_class_0': 0.5471049468239544, 'weight_class_1': 9.695129515726428, 'weight_class_2': 8.486465724131902}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:00,818] Trial 1238 finished with value: 0.9489796583905191 and parameters: {'weight_class_0': 0.5384969061283094, 'weight_class_1': 9.712219661404738, 'weight_class_2': 8.613754871602028}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:00,821] Trial 1237 finished with value: 0.9489680789043983 and parameters: {'weight_class_0': 0.5350436681006273, 'weight_class_1': 9.741170227768688, 'weight_class_2': 8.380266798862927}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  62%|██████████████████████████████████████████████████████████████████████████████████▎                                                 | 1248/2000 [00:25<00:16, 45.20it/s]

[I 2026-07-08 13:33:00,869] Trial 1239 finished with value: 0.9486990730214849 and parameters: {'weight_class_0': 0.5551295569422257, 'weight_class_1': 5.046013808023793, 'weight_class_2': 8.477899417983005}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:00,893] Trial 1240 finished with value: 0.9489331523998473 and parameters: {'weight_class_0': 0.5392624844396983, 'weight_class_1': 9.777572527504937, 'weight_class_2': 8.78412073732686}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:00,898] Trial 1241 finished with value: 0.9489048746902605 and parameters: {'weight_class_0': 0.5034078409012475, 'weight_class_1': 9.690374691969781, 'weight_class_2': 8.622899575177437}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:00,905] Trial 1242 finished with value: 0.8801922827347778 and parameters: {'weight_class_0': 8.702904226704014, 'weight_class_1': 9.702783555482831, 'weight_class_2': 8.579945206662792}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:00,917] Trial 1243 finished with value: 0.9489501532413783 and parameters: {'weight_class_0': 0.521288010021691, 'weight_class_1': 9.692014119514834, 'weight_class_2': 8.648683866450876}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:00,959] Trial 1244 finished with value: 0.9490879812127573 and parameters: {'weight_class_0': 0.5861800756408141, 'weight_class_1': 9.70654811326644, 'weight_class_2': 8.788476852890508}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:00,994] Trial 1246 finished with value: 0.9489190430386384 and parameters: {'weight_class_0': 0.4749412535642866, 'weight_class_1': 9.661294953426163, 'weight_class_2': 8.060804280277825}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:00,999] Trial 1245 finished with value: 0.9489440418311955 and parameters: {'weight_class_0': 0.4860458895316708, 'weight_class_1': 9.664275464450075, 'weight_class_2': 8.048028075443778}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:01,055] Trial 1247 finished with value: 0.9483098547065945 and parameters: {'weight_class_0': 1.1426818286069398, 'weight_class_1': 9.555645283060528, 'weight_class_2': 8.09239848365854}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:01,060] Trial 1248 finished with value: 0.9485479288756666 and parameters: {'weight_class_0': 1.1393518827578388, 'weight_class_1': 9.47105665943011, 'weight_class_2': 8.927874937009909}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  63%|███████████████████████████████████████████████████████████████████████████████████                                                 | 1258/2000 [00:25<00:16, 43.85it/s]

[I 2026-07-08 13:33:01,085] Trial 1249 finished with value: 0.9457621701529147 and parameters: {'weight_class_0': 0.18833959136101863, 'weight_class_1': 9.623828824195128, 'weight_class_2': 8.136250404278934}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:01,103] Trial 1250 finished with value: 0.9459630001129652 and parameters: {'weight_class_0': 1.6727869229101084, 'weight_class_1': 9.503472858829488, 'weight_class_2': 8.107941884727289}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:01,152] Trial 1251 finished with value: 0.9484405244908882 and parameters: {'weight_class_0': 1.1214933545502581, 'weight_class_1': 9.512443252332334, 'weight_class_2': 8.203143496542863}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:01,154] Trial 1252 finished with value: 0.9462158394628178 and parameters: {'weight_class_0': 0.20909180449883896, 'weight_class_1': 9.994876619877772, 'weight_class_2': 8.132721373803882}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:01,177] Trial 1253 finished with value: 0.9451079789670724 and parameters: {'weight_class_0': 0.17637073218944488, 'weight_class_1': 9.999557419273541, 'weight_class_2': 8.229183831979295}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:01,186] Trial 1254 finished with value: 0.9452034614584602 and parameters: {'weight_class_0': 0.17223284735468136, 'weight_class_1': 9.54023661527283, 'weight_class_2': 8.14692963946637}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:01,188] Trial 1255 finished with value: 0.9458967190016708 and parameters: {'weight_class_0': 0.1912265142569891, 'weight_class_1': 9.513682154472162, 'weight_class_2': 8.16064724755006}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:01,236] Trial 1256 finished with value: 0.9458367409701668 and parameters: {'weight_class_0': 0.18968957619006027, 'weight_class_1': 9.49716854884603, 'weight_class_2': 8.181073059904676}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:01,259] Trial 1258 finished with value: 0.9486052400625123 and parameters: {'weight_class_0': 1.129405602783362, 'weight_class_1': 9.993726453740322, 'weight_class_2': 8.892214877849128}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:01,273] Trial 1257 finished with value: 0.9437524013312911 and parameters: {'weight_class_0': 0.15068084158152983, 'weight_class_1': 9.997199097432068, 'weight_class_2': 8.180380700078238}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:33:01,316] Trial 1260 finished with value: 0.946204243428304 and parameters: {'weight_class_0': 0.20850705135468778, 'weight_class_1': 9.989346746462592, 'weight_class_2': 7.959704281189137}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:01,319] Trial 1259 finished with value: 0.9457139722572094 and parameters: {'weight_class_0': 0.18679041191793094, 'weight_class_1': 9.452419545954044, 'weight_class_2': 8.249866711455685}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:01,344] Trial 1261 finished with value: 0.9426702973049029 and parameters: {'weight_class_0': 2.286817393371044, 'weight_class_1': 9.978720236131897, 'weight_class_2': 8.183073811420124}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:01,391] Trial 1262 finished with value: 0.9465718202656417 and parameters: {'weight_class_0': 0.21604600711521765, 'weight_class_1': 9.505822630026257, 'weight_class_2': 7.993402238439415}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:01,402] Trial 1263 finished with value: 0.9492331025802163 and parameters: {'weight_class_0': 0.7165302196004053, 'weight_class_1': 9.49309143773133, 'weight_class_2': 7.890540248850318}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:01,452] Trial 1264 finished with value: 0.9491879068328332 and parameters: {'weight_class_0': 0.6474207583742999, 'weight_class_1': 9.374478295785329, 'weight_class_2': 7.935953413748785}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:01,460] Trial 1265 finished with value: 0.9492159714948457 and parameters: {'weight_class_0': 0.7179498079327442, 'weight_class_1': 9.987539359558147, 'weight_class_2': 7.9173547259595285}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:01,487] Trial 1266 finished with value: 0.9491638721369856 and parameters: {'weight_class_0': 0.6947461339385387, 'weight_class_1': 9.995454819293531, 'weight_class_2': 9.146909011743203}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:01,518] Trial 1267 finished with value: 0.9492216088224801 and parameters: {'weight_class_0': 0.7073273397394065, 'weight_class_1': 9.998475906983524, 'weight_class_2': 7.921082673614211}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  64%|████████████████████████████████████████████████████████████████████████████████████▎                                               | 1277/2000 [00:26<00:16, 43.93it/s]

[I 2026-07-08 13:33:01,542] Trial 1269 finished with value: 0.9491963261320119 and parameters: {'weight_class_0': 0.7069249284681651, 'weight_class_1': 8.707913401513702, 'weight_class_2': 7.950367624724265}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:01,547] Trial 1268 finished with value: 0.9491723876373029 and parameters: {'weight_class_0': 0.7301366420635351, 'weight_class_1': 8.999986680301928, 'weight_class_2': 7.883011920705083}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:01,559] Trial 1270 finished with value: 0.9491669551716136 and parameters: {'weight_class_0': 0.7454870062995078, 'weight_class_1': 9.351065603316714, 'weight_class_2': 7.934801655853266}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:01,610] Trial 1271 finished with value: 0.9491753415308609 and parameters: {'weight_class_0': 0.7050295185730112, 'weight_class_1': 9.996446213836794, 'weight_class_2': 9.185885959776522}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:01,626] Trial 1273 finished with value: 0.9491831753676282 and parameters: {'weight_class_0': 0.7147660802546213, 'weight_class_1': 8.657495261224375, 'weight_class_2': 7.914208744362698}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:01,647] Trial 1272 finished with value: 0.9492244564736122 and parameters: {'weight_class_0': 0.7393189382434892, 'weight_class_1': 9.747152880220229, 'weight_class_2': 7.909757138819492}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:01,670] Trial 1274 finished with value: 0.9491647594438284 and parameters: {'weight_class_0': 0.7035140552092356, 'weight_class_1': 9.326426589158018, 'weight_class_2': 9.040204067356457}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:01,699] Trial 1275 finished with value: 0.9491323819790184 and parameters: {'weight_class_0': 0.7187405061605158, 'weight_class_1': 8.959024602025877, 'weight_class_2': 9.015734821941074}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:01,715] Trial 1276 finished with value: 0.9468252469532558 and parameters: {'weight_class_0': 1.5643726955692916, 'weight_class_1': 9.730973188653392, 'weight_class_2': 8.505209330717083}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:01,724] Trial 1277 finished with value: 0.9469704962412567 and parameters: {'weight_class_0': 1.5029383279327786, 'weight_class_1': 9.779631555420695, 'weight_class_2': 7.949893605508678}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  64%|████████████████████████████████████████████████████████████████████████████████████▉                                               | 1286/2000 [00:26<00:16, 44.40it/s]

[I 2026-07-08 13:33:01,750] Trial 1279 finished with value: 0.9484085991554324 and parameters: {'weight_class_0': 1.1550412448403868, 'weight_class_1': 9.74381411184305, 'weight_class_2': 8.489518363830182}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:01,751] Trial 1278 finished with value: 0.9485593159720765 and parameters: {'weight_class_0': 1.0950457177148545, 'weight_class_1': 9.777664606793318, 'weight_class_2': 8.446495183672877}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:01,809] Trial 1280 finished with value: 0.9483920021267203 and parameters: {'weight_class_0': 1.182107823246504, 'weight_class_1': 9.987059316049127, 'weight_class_2': 8.490485410103433}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:01,833] Trial 1281 finished with value: 0.9486350342059756 and parameters: {'weight_class_0': 1.0724984874618149, 'weight_class_1': 9.789494467517413, 'weight_class_2': 8.458930767038623}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:01,868] Trial 1283 finished with value: 0.9488626864699375 and parameters: {'weight_class_0': 1.0114511740074674, 'weight_class_1': 9.793443078649227, 'weight_class_2': 8.315538413975844}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:01,887] Trial 1282 finished with value: 0.9033050114863355 and parameters: {'weight_class_0': 1.5399756962869615, 'weight_class_1': 0.907474757232797, 'weight_class_2': 8.483124480798068}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:01,900] Trial 1284 finished with value: 0.9475397336305423 and parameters: {'weight_class_0': 1.4056811189280083, 'weight_class_1': 9.822618226787032, 'weight_class_2': 8.393984977509394}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:01,921] Trial 1286 finished with value: 0.948472226614406 and parameters: {'weight_class_0': 1.147487773238746, 'weight_class_1': 9.854965307465125, 'weight_class_2': 8.491739639598745}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:01,925] Trial 1285 finished with value: 0.9473551531206591 and parameters: {'weight_class_0': 1.4621306132926764, 'weight_class_1': 9.990830125354844, 'weight_class_2': 8.308944713684152}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:33:01,965] Trial 1287 finished with value: 0.9484323851524313 and parameters: {'weight_class_0': 1.152734047977714, 'weight_class_1': 9.781902708429937, 'weight_class_2': 8.464809207799311}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:02,018] Trial 1289 finished with value: 0.9487959262076157 and parameters: {'weight_class_0': 1.0222269738069278, 'weight_class_1': 9.997901909359225, 'weight_class_2': 8.254959040103635}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:02,025] Trial 1288 finished with value: 0.9488727034107202 and parameters: {'weight_class_0': 1.001880946861197, 'weight_class_1': 9.774534162149177, 'weight_class_2': 8.341082275602451}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:02,035] Trial 1290 finished with value: 0.9489032530829503 and parameters: {'weight_class_0': 0.9278212432690534, 'weight_class_1': 9.982439165326525, 'weight_class_2': 8.406415952144078}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:02,048] Trial 1291 finished with value: 0.9488931428039082 and parameters: {'weight_class_0': 0.9919081092520718, 'weight_class_1': 9.990209327323626, 'weight_class_2': 8.328113382721439}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:02,086] Trial 1293 finished with value: 0.9488857726589867 and parameters: {'weight_class_0': 1.0001458005265862, 'weight_class_1': 9.98900100767956, 'weight_class_2': 8.34134189765485}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:02,095] Trial 1292 finished with value: 0.9488939360529144 and parameters: {'weight_class_0': 0.9625926944344793, 'weight_class_1': 9.826647450156681, 'weight_class_2': 8.32101129320492}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:02,128] Trial 1294 finished with value: 0.9486090720546351 and parameters: {'weight_class_0': 0.4123031806739964, 'weight_class_1': 9.767089084436721, 'weight_class_2': 8.263615119457713}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:02,166] Trial 1295 finished with value: 0.9486070902711347 and parameters: {'weight_class_0': 0.4089966795169999, 'weight_class_1': 9.820527044609419, 'weight_class_2': 8.001728742919322}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  65%|██████████████████████████████████████████████████████████████████████████████████████                                              | 1304/2000 [00:26<00:16, 41.00it/s]

[I 2026-07-08 13:33:02,182] Trial 1296 finished with value: 0.9488544653069731 and parameters: {'weight_class_0': 0.9408821630159993, 'weight_class_1': 9.995155539099422, 'weight_class_2': 8.034828436495966}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:02,212] Trial 1297 finished with value: 0.9488852446161959 and parameters: {'weight_class_0': 0.9285435283319504, 'weight_class_1': 9.781062271091685, 'weight_class_2': 8.026241895553358}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:02,222] Trial 1298 finished with value: 0.9485615583359431 and parameters: {'weight_class_0': 0.40441276611082816, 'weight_class_1': 9.993443996922268, 'weight_class_2': 8.003435513079618}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:02,248] Trial 1299 finished with value: 0.9486942825223629 and parameters: {'weight_class_0': 0.43166554576480043, 'weight_class_1': 9.989086499494874, 'weight_class_2': 8.060494134776608}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:02,267] Trial 1300 finished with value: 0.9485967129432504 and parameters: {'weight_class_0': 0.4033618384916234, 'weight_class_1': 9.616775134493635, 'weight_class_2': 8.00597070380347}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:02,323] Trial 1302 finished with value: 0.9486004726685592 and parameters: {'weight_class_0': 0.4027100544293973, 'weight_class_1': 9.658446123319768, 'weight_class_2': 8.017631267339906}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:02,324] Trial 1301 finished with value: 0.9488119902670117 and parameters: {'weight_class_0': 0.44489018107190637, 'weight_class_1': 9.688524284639342, 'weight_class_2': 7.986062659773703}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:02,334] Trial 1304 finished with value: 0.9487464094978694 and parameters: {'weight_class_0': 0.436679856174077, 'weight_class_1': 9.61106381012843, 'weight_class_2': 7.9920279238180125}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:02,361] Trial 1303 finished with value: 0.9489898256572502 and parameters: {'weight_class_0': 0.5065693499885255, 'weight_class_1': 9.663860006128758, 'weight_class_2': 8.048282726588402}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:33:02,384] Trial 1305 finished with value: 0.9489491375950934 and parameters: {'weight_class_0': 0.4756800546582639, 'weight_class_1': 9.635089177163042, 'weight_class_2': 7.894117424297193}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:02,388] Trial 1306 finished with value: 0.9487894890674166 and parameters: {'weight_class_0': 0.4410971456955861, 'weight_class_1': 9.638654318539427, 'weight_class_2': 7.966138168020393}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:02,424] Trial 1307 finished with value: 0.9486521968514997 and parameters: {'weight_class_0': 0.411841845978069, 'weight_class_1': 9.61158331218279, 'weight_class_2': 7.952834529903977}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:02,451] Trial 1308 finished with value: 0.9484058415043278 and parameters: {'weight_class_0': 0.36909955947277967, 'weight_class_1': 9.56110207484483, 'weight_class_2': 7.897995660150195}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:02,456] Trial 1309 finished with value: 0.9488003793829093 and parameters: {'weight_class_0': 0.4519215285843705, 'weight_class_1': 9.586118344537306, 'weight_class_2': 8.196268236782782}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:02,460] Trial 1310 finished with value: 0.9440942106781086 and parameters: {'weight_class_0': 1.9884226586036635, 'weight_class_1': 9.567191822100446, 'weight_class_2': 7.920239294723831}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:02,482] Trial 1311 finished with value: 0.9490892763260609 and parameters: {'weight_class_0': 0.8066282283152783, 'weight_class_1': 9.607898337263288, 'weight_class_2': 7.8328049771734864}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:02,507] Trial 1312 finished with value: 0.9490878239757649 and parameters: {'weight_class_0': 0.8023418126099092, 'weight_class_1': 9.59701541694261, 'weight_class_2': 7.822165314956427}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:02,592] Trial 1314 finished with value: 0.9483417292502155 and parameters: {'weight_class_0': 0.7150705870930933, 'weight_class_1': 9.537697604546642, 'weight_class_2': 4.436449918187421}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:33:02,595] Trial 1313 finished with value: 0.9490926800821283 and parameters: {'weight_class_0': 0.7987238668212412, 'weight_class_1': 9.624801377440452, 'weight_class_2': 7.856056396421293}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:02,608] Trial 1315 finished with value: 0.9490936619530769 and parameters: {'weight_class_0': 0.8056719215336466, 'weight_class_1': 9.519881280706894, 'weight_class_2': 7.856761727659925}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:02,631] Trial 1316 finished with value: 0.9489853171853581 and parameters: {'weight_class_0': 0.8525424335123812, 'weight_class_1': 9.538401419741701, 'weight_class_2': 7.8905477837452525}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:02,652] Trial 1317 finished with value: 0.8628643525197769 and parameters: {'weight_class_0': 9.746787153453138, 'weight_class_1': 9.492968262459746, 'weight_class_2': 4.534438953756552}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:02,676] Trial 1318 finished with value: 0.9490178413396038 and parameters: {'weight_class_0': 0.8296634230416453, 'weight_class_1': 9.46584889673318, 'weight_class_2': 7.797273809116707}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:02,733] Trial 1320 finished with value: 0.9490421655027316 and parameters: {'weight_class_0': 0.8210358252034247, 'weight_class_1': 9.83805362964108, 'weight_class_2': 7.807262290428006}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:02,747] Trial 1321 finished with value: 0.9490773814745626 and parameters: {'weight_class_0': 0.7744542957950413, 'weight_class_1': 9.771386853429041, 'weight_class_2': 7.701861683325787}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:02,753] Trial 1319 finished with value: 0.9490399153827721 and parameters: {'weight_class_0': 0.8167231960944855, 'weight_class_1': 9.78199807404189, 'weight_class_2': 7.777644462698123}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:02,778] Trial 1322 finished with value: 0.9490435136718528 and parameters: {'weight_class_0': 0.8128434413566388, 'weight_class_1': 9.813435785678655, 'weight_class_2': 7.743862605586061}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  67%|███████████████████████████████████████████████████████████████████████████████████████▊                                            | 1331/2000 [00:27<00:15, 42.65it/s]

[I 2026-07-08 13:33:02,795] Trial 1323 finished with value: 0.7773476833719689 and parameters: {'weight_class_0': 9.986725793675127, 'weight_class_1': 9.801698956002893, 'weight_class_2': 0.057189118661614025}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:02,827] Trial 1324 finished with value: 0.9490804460153749 and parameters: {'weight_class_0': 0.7981056997251317, 'weight_class_1': 9.851897219139476, 'weight_class_2': 7.779993662686716}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:02,845] Trial 1325 finished with value: 0.9491271951152461 and parameters: {'weight_class_0': 0.6098110143550808, 'weight_class_1': 9.996620361053456, 'weight_class_2': 7.7873593727912365}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:02,870] Trial 1326 finished with value: 0.9491771053759687 and parameters: {'weight_class_0': 0.6623048769080178, 'weight_class_1': 9.854077904364722, 'weight_class_2': 7.708266236445641}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:02,902] Trial 1327 finished with value: 0.8429337249486443 and parameters: {'weight_class_0': 6.8047728073059695, 'weight_class_1': 2.924799667879803, 'weight_class_2': 1.5769793807242123}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:02,924] Trial 1328 finished with value: 0.9480732517107692 and parameters: {'weight_class_0': 1.2544694992199728, 'weight_class_1': 9.812869067691533, 'weight_class_2': 8.164290219344593}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:02,968] Trial 1329 finished with value: 0.9491237583651898 and parameters: {'weight_class_0': 0.6138549437876335, 'weight_class_1': 9.742170642272939, 'weight_class_2': 7.72480334768441}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:02,969] Trial 1330 finished with value: 0.948980963889673 and parameters: {'weight_class_0': 0.6329215826753103, 'weight_class_1': 6.211033476058342, 'weight_class_2': 8.195491614866723}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:03,005] Trial 1331 finished with value: 0.9488329138038495 and parameters: {'weight_class_0': 0.6157709080081438, 'weight_class_1': 9.99557883193449, 'weight_class_2': 4.883897550437883}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  67%|████████████████████████████████████████████████████████████████████████████████████████▍                                           | 1340/2000 [00:27<00:15, 42.80it/s]

[I 2026-07-08 13:33:03,014] Trial 1332 finished with value: 0.9491709775819609 and parameters: {'weight_class_0': 0.6188594105095072, 'weight_class_1': 9.993938470549708, 'weight_class_2': 8.168215798979865}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:03,050] Trial 1333 finished with value: 0.8982276309985074 and parameters: {'weight_class_0': 1.2702815336891502, 'weight_class_1': 9.991106913742865, 'weight_class_2': 0.698499015322966}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:03,098] Trial 1334 finished with value: 0.9483674537314014 and parameters: {'weight_class_0': 1.197667045671733, 'weight_class_1': 9.34640015850618, 'weight_class_2': 8.746141202325761}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:03,101] Trial 1335 finished with value: 0.9490875127406037 and parameters: {'weight_class_0': 0.6185503239672713, 'weight_class_1': 9.328286697253722, 'weight_class_2': 8.681353485725078}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:03,104] Trial 1336 finished with value: 0.9480147267081122 and parameters: {'weight_class_0': 1.2381967363620916, 'weight_class_1': 9.351968561710226, 'weight_class_2': 8.170128908602793}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:03,149] Trial 1338 finished with value: 0.9482130398826151 and parameters: {'weight_class_0': 1.280572274309354, 'weight_class_1': 9.992847465753895, 'weight_class_2': 8.77267618053222}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:03,150] Trial 1337 finished with value: 0.948349609214338 and parameters: {'weight_class_0': 1.1404761047600047, 'weight_class_1': 9.274407692317576, 'weight_class_2': 8.199280195727818}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:03,180] Trial 1340 finished with value: 0.9489692091379882 and parameters: {'weight_class_0': 0.6474767066888484, 'weight_class_1': 6.748125318946913, 'weight_class_2': 8.171039138882296}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:03,209] Trial 1339 finished with value: 0.948961619307131 and parameters: {'weight_class_0': 0.6009903197255216, 'weight_class_1': 9.322608147303667, 'weight_class_2': 9.37650378589121}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  67%|█████████████████████████████████████████████████████████████████████████████████████████                                           | 1349/2000 [00:27<00:16, 40.64it/s]

[I 2026-07-08 13:33:03,246] Trial 1341 finished with value: 0.9485050890664505 and parameters: {'weight_class_0': 1.1170149244283418, 'weight_class_1': 9.323928643886415, 'weight_class_2': 8.630506013642991}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:03,258] Trial 1342 finished with value: 0.9369856927293813 and parameters: {'weight_class_0': 2.8345211756745807, 'weight_class_1': 9.374759000854503, 'weight_class_2': 8.173534547877766}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:03,296] Trial 1343 finished with value: 0.9482973331387292 and parameters: {'weight_class_0': 1.1548755771734929, 'weight_class_1': 9.29281251898065, 'weight_class_2': 8.209431791104352}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:03,300] Trial 1345 finished with value: 0.9483741764326078 and parameters: {'weight_class_0': 1.138384463123642, 'weight_class_1': 9.31090188055909, 'weight_class_2': 8.254302132469983}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:03,314] Trial 1344 finished with value: 0.9487822062492826 and parameters: {'weight_class_0': 1.0163340545876376, 'weight_class_1': 9.130599388483295, 'weight_class_2': 8.636810468911133}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:03,354] Trial 1346 finished with value: 0.9484650040763761 and parameters: {'weight_class_0': 1.0398059934349821, 'weight_class_1': 9.069248648266992, 'weight_class_2': 7.649594054358324}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:03,391] Trial 1347 finished with value: 0.9486037541424732 and parameters: {'weight_class_0': 0.9990569942200436, 'weight_class_1': 9.069265437490172, 'weight_class_2': 7.633809650779691}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:03,402] Trial 1348 finished with value: 0.9486771005065924 and parameters: {'weight_class_0': 1.015199460338347, 'weight_class_1': 9.130163525680924, 'weight_class_2': 8.113164013003917}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:03,434] Trial 1350 finished with value: 0.9486884033678283 and parameters: {'weight_class_0': 0.9682240575239065, 'weight_class_1': 9.06573084499851, 'weight_class_2': 7.634625358220735}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:33:03,453] Trial 1349 finished with value: 0.9486859527009878 and parameters: {'weight_class_0': 0.9797963576468891, 'weight_class_1': 9.153033742787985, 'weight_class_2': 7.737773678681364}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:03,474] Trial 1351 finished with value: 0.9486721082453183 and parameters: {'weight_class_0': 0.9765232828217052, 'weight_class_1': 9.020188920098189, 'weight_class_2': 7.668268015501104}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:03,493] Trial 1352 finished with value: 0.9407314057410154 and parameters: {'weight_class_0': 0.9250582713500665, 'weight_class_1': 2.4384586924663716, 'weight_class_2': 7.6696375575160936}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:03,511] Trial 1353 finished with value: 0.9488282932406974 and parameters: {'weight_class_0': 0.9334378336539513, 'weight_class_1': 9.789156567501264, 'weight_class_2': 7.646413946916983}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:03,583] Trial 1355 finished with value: 0.948379913883608 and parameters: {'weight_class_0': 0.35036733637564993, 'weight_class_1': 9.040343279316676, 'weight_class_2': 7.62729640845624}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:03,585] Trial 1354 finished with value: 0.9480858355379386 and parameters: {'weight_class_0': 0.31616245108565993, 'weight_class_1': 9.033259327292319, 'weight_class_2': 7.696884141487155}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:03,592] Trial 1356 finished with value: 0.9482679140780248 and parameters: {'weight_class_0': 0.35382455064798146, 'weight_class_1': 9.997923540374149, 'weight_class_2': 7.627055105982952}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:03,629] Trial 1357 finished with value: 0.9477408848420309 and parameters: {'weight_class_0': 0.29471316635576, 'weight_class_1': 9.802026823012783, 'weight_class_2': 7.566293516396452}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:03,633] Trial 1358 finished with value: 0.9486218455133635 and parameters: {'weight_class_0': 0.4011653089409514, 'weight_class_1': 9.792057973924557, 'weight_class_2': 7.612778896218713}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:33:03,663] Trial 1359 finished with value: 0.9184502910399122 and parameters: {'weight_class_0': 4.373643476765812, 'weight_class_1': 9.792903698864157, 'weight_class_2': 7.6587444550067945}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:03,709] Trial 1360 finished with value: 0.947804755458943 and parameters: {'weight_class_0': 0.30131747354635297, 'weight_class_1': 9.76645689702428, 'weight_class_2': 7.624925019829506}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:03,713] Trial 1361 finished with value: 0.9481232534159904 and parameters: {'weight_class_0': 0.33697047335292696, 'weight_class_1': 9.755932104640992, 'weight_class_2': 7.897109850332621}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:03,747] Trial 1362 finished with value: 0.9477018591913232 and parameters: {'weight_class_0': 0.2925780403675918, 'weight_class_1': 9.79032606228955, 'weight_class_2': 7.921681719267675}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:03,783] Trial 1364 finished with value: 0.94788391846396 and parameters: {'weight_class_0': 0.3099717037995715, 'weight_class_1': 9.779723342093055, 'weight_class_2': 7.918200426650354}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:03,790] Trial 1363 finished with value: 0.9480683832789163 and parameters: {'weight_class_0': 0.3314733309852409, 'weight_class_1': 9.798247314452343, 'weight_class_2': 7.912663023866354}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:03,804] Trial 1365 finished with value: 0.6599914152192782 and parameters: {'weight_class_0': 0.007606983376398313, 'weight_class_1': 9.997534661488015, 'weight_class_2': 7.892018926422024}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:03,833] Trial 1366 finished with value: 0.9491456639380097 and parameters: {'weight_class_0': 0.6219940991030795, 'weight_class_1': 9.77862988830283, 'weight_class_2': 7.926502123800745}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:03,879] Trial 1367 finished with value: 0.949143844981151 and parameters: {'weight_class_0': 0.586763456729815, 'weight_class_1': 9.54063040871302, 'weight_class_2': 7.878247216820707}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:33:03,894] Trial 1368 finished with value: 0.9490993416374364 and parameters: {'weight_class_0': 0.5703386729388797, 'weight_class_1': 9.49247340338454, 'weight_class_2': 7.882976124138344}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:03,932] Trial 1370 finished with value: 0.689314443832711 and parameters: {'weight_class_0': 0.015353829664372487, 'weight_class_1': 9.587249947235938, 'weight_class_2': 7.9300312045422245}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:03,955] Trial 1369 finished with value: 0.9491623348729646 and parameters: {'weight_class_0': 0.6153983413311336, 'weight_class_1': 9.545086143405383, 'weight_class_2': 7.922659786813943}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:03,969] Trial 1371 finished with value: 0.949184679465379 and parameters: {'weight_class_0': 0.670599350803294, 'weight_class_1': 9.556563456583522, 'weight_class_2': 7.919668079398631}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:03,975] Trial 1372 finished with value: 0.9491506014576939 and parameters: {'weight_class_0': 0.5957640717119171, 'weight_class_1': 9.572336762955612, 'weight_class_2': 7.925395980448366}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:04,015] Trial 1373 finished with value: 0.949180254624913 and parameters: {'weight_class_0': 0.6601109749737307, 'weight_class_1': 9.502077065353342, 'weight_class_2': 7.95665954817471}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:04,025] Trial 1374 finished with value: 0.9490813936177492 and parameters: {'weight_class_0': 0.5792459584504343, 'weight_class_1': 9.530307697585481, 'weight_class_2': 8.022034670101855}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:04,058] Trial 1375 finished with value: 0.9491355928313916 and parameters: {'weight_class_0': 0.6078537878606286, 'weight_class_1': 9.486106786761255, 'weight_class_2': 8.111082201892362}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:04,072] Trial 1376 finished with value: 0.949127418800142 and parameters: {'weight_class_0': 0.6086689378945266, 'weight_class_1': 9.528969245093455, 'weight_class_2': 8.091529380450185}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:04,101] Trial 1377 finished with value: 0.9491181766555759 and parameters: {'weight_class_0': 0.5711233076957938, 'weight_class_1': 9.531252059959694, 'weight_class_2': 8.123295143200245}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  69%|███████████████████████████████████████████████████████████████████████████████████████████▍                                        | 1385/2000 [00:28<00:14, 42.08it/s]

[I 2026-07-08 13:33:04,107] Trial 1378 finished with value: 0.9491113753629019 and parameters: {'weight_class_0': 0.6010865742553498, 'weight_class_1': 9.532176575575326, 'weight_class_2': 8.07932781689889}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:04,145] Trial 1379 finished with value: 0.9491341044056029 and parameters: {'weight_class_0': 0.7620490072054741, 'weight_class_1': 8.691078404161354, 'weight_class_2': 8.135604393790887}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:04,167] Trial 1380 finished with value: 0.9491185022958275 and parameters: {'weight_class_0': 0.7862666964319877, 'weight_class_1': 9.531659245302386, 'weight_class_2': 8.11082250756757}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:04,186] Trial 1381 finished with value: 0.949145911418726 and parameters: {'weight_class_0': 0.7556202421756131, 'weight_class_1': 8.763983694708786, 'weight_class_2': 8.105997137915747}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:04,231] Trial 1382 finished with value: 0.9491082996577527 and parameters: {'weight_class_0': 0.8094058046198933, 'weight_class_1': 9.998316699021597, 'weight_class_2': 8.171011126718424}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:04,249] Trial 1383 finished with value: 0.9490202715131488 and parameters: {'weight_class_0': 0.8083165077891964, 'weight_class_1': 8.83201089908827, 'weight_class_2': 8.127803021206892}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:04,286] Trial 1385 finished with value: 0.9489932372852391 and parameters: {'weight_class_0': 0.855354265837872, 'weight_class_1': 8.700811904827985, 'weight_class_2': 8.333183238062933}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:04,304] Trial 1384 finished with value: 0.9489712759505767 and parameters: {'weight_class_0': 0.8376588151046555, 'weight_class_1': 8.710774455091096, 'weight_class_2': 8.293534607178676}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:33:04,337] Trial 1386 finished with value: 0.948972769007533 and parameters: {'weight_class_0': 0.8307980748833294, 'weight_class_1': 8.6448968735493, 'weight_class_2': 8.321527251401266}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:04,354] Trial 1387 finished with value: 0.9490832211506784 and parameters: {'weight_class_0': 0.8243485911674566, 'weight_class_1': 9.999151022346721, 'weight_class_2': 8.225715523652879}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:04,382] Trial 1388 finished with value: 0.9490019858742141 and parameters: {'weight_class_0': 0.8369334531192076, 'weight_class_1': 8.649009120155437, 'weight_class_2': 8.318325333624493}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:04,387] Trial 1390 finished with value: 0.9490132990643816 and parameters: {'weight_class_0': 0.8576497735948604, 'weight_class_1': 9.805617432207477, 'weight_class_2': 8.48710138031514}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:04,402] Trial 1389 finished with value: 0.9491335699787835 and parameters: {'weight_class_0': 0.8322922772681324, 'weight_class_1': 9.998560363875933, 'weight_class_2': 8.506400652965073}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:04,429] Trial 1391 finished with value: 0.9490580629290871 and parameters: {'weight_class_0': 0.8682610098448407, 'weight_class_1': 9.995210818817982, 'weight_class_2': 8.337006589685041}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:04,443] Trial 1392 finished with value: 0.9490351441901339 and parameters: {'weight_class_0': 0.8763252495293916, 'weight_class_1': 9.842454114531591, 'weight_class_2': 8.393813174174879}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:04,455] Trial 1393 finished with value: 0.9491646131038083 and parameters: {'weight_class_0': 0.799935849480054, 'weight_class_1': 9.840382114235574, 'weight_class_2': 8.423745725173102}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:04,519] Trial 1395 finished with value: 0.9489577643261335 and parameters: {'weight_class_0': 0.9038988305656717, 'weight_class_1': 9.807664000454949, 'weight_class_2': 8.503641146084451}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  70%|████████████████████████████████████████████████████████████████████████████████████████████▌                                       | 1403/2000 [00:29<00:14, 40.59it/s]

[I 2026-07-08 13:33:04,533] Trial 1394 finished with value: 0.9488647142954151 and parameters: {'weight_class_0': 0.9049874943921538, 'weight_class_1': 9.804132582792905, 'weight_class_2': 7.546101506838108}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:04,543] Trial 1396 finished with value: 0.9488572398665222 and parameters: {'weight_class_0': 0.8878142566960423, 'weight_class_1': 9.773992212760616, 'weight_class_2': 7.535761938680886}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:04,578] Trial 1397 finished with value: 0.9337309975122133 and parameters: {'weight_class_0': 3.064724601421803, 'weight_class_1': 9.808165509879968, 'weight_class_2': 7.548375951774588}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:04,612] Trial 1398 finished with value: 0.9488584937442202 and parameters: {'weight_class_0': 0.4937155038548552, 'weight_class_1': 9.817708455791292, 'weight_class_2': 8.510435774883078}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:04,652] Trial 1399 finished with value: 0.9486612001531912 and parameters: {'weight_class_0': 0.4140123916474665, 'weight_class_1': 9.782945898749512, 'weight_class_2': 7.593194818585045}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:04,654] Trial 1400 finished with value: 0.9488491201709938 and parameters: {'weight_class_0': 0.45633154355817784, 'weight_class_1': 9.785618551728154, 'weight_class_2': 7.569224001284752}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:04,665] Trial 1401 finished with value: 0.9471154111304839 and parameters: {'weight_class_0': 1.3280600046303648, 'weight_class_1': 8.405828213373693, 'weight_class_2': 7.589304048093553}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:04,686] Trial 1402 finished with value: 0.9489342774598271 and parameters: {'weight_class_0': 0.4622586509031818, 'weight_class_1': 8.403864729344978, 'weight_class_2': 7.52008028805196}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:04,713] Trial 1403 finished with value: 0.94672369202623 and parameters: {'weight_class_0': 1.3875586975248118, 'weight_class_1': 8.413386418443071, 'weight_class_2': 7.553507302017792}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  71%|█████████████████████████████████████████████████████████████████████████████████████████████▏                                      | 1412/2000 [00:29<00:14, 40.69it/s]

[I 2026-07-08 13:33:04,739] Trial 1404 finished with value: 0.9489638338501534 and parameters: {'weight_class_0': 0.4805699151848512, 'weight_class_1': 8.395821667054049, 'weight_class_2': 7.549362778623326}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:04,758] Trial 1405 finished with value: 0.946529897236046 and parameters: {'weight_class_0': 1.4299982413376355, 'weight_class_1': 8.417720721653271, 'weight_class_2': 7.575398608645543}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:04,799] Trial 1406 finished with value: 0.9473894128112487 and parameters: {'weight_class_0': 1.3250638106775292, 'weight_class_1': 9.314701626125157, 'weight_class_2': 7.491814190192056}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:04,842] Trial 1408 finished with value: 0.9489047384325532 and parameters: {'weight_class_0': 0.45235399537274834, 'weight_class_1': 9.308745135118098, 'weight_class_2': 7.735760690616351}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:04,852] Trial 1407 finished with value: 0.9488622907785814 and parameters: {'weight_class_0': 0.4427902409137566, 'weight_class_1': 9.293665908831247, 'weight_class_2': 7.740356192079511}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:04,878] Trial 1410 finished with value: 0.9488673475346227 and parameters: {'weight_class_0': 0.4472617060466097, 'weight_class_1': 9.324391495511227, 'weight_class_2': 7.697838689004465}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:04,882] Trial 1409 finished with value: 0.9470982162004379 and parameters: {'weight_class_0': 1.4114779693319575, 'weight_class_1': 9.308422910524985, 'weight_class_2': 7.757312405973311}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:04,917] Trial 1411 finished with value: 0.9460080807750142 and parameters: {'weight_class_0': 0.19795804146636475, 'weight_class_1': 9.318387936499773, 'weight_class_2': 8.831492984844282}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:04,938] Trial 1412 finished with value: 0.9466740167253116 and parameters: {'weight_class_0': 0.21681699233590201, 'weight_class_1': 9.373051335039333, 'weight_class_2': 7.79500074788614}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  71%|█████████████████████████████████████████████████████████████████████████████████████████████▊                                      | 1421/2000 [00:29<00:14, 39.39it/s]

[I 2026-07-08 13:33:04,978] Trial 1413 finished with value: 0.9457860828933488 and parameters: {'weight_class_0': 0.1815150623337186, 'weight_class_1': 9.301813866416385, 'weight_class_2': 7.75936163947148}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:05,008] Trial 1414 finished with value: 0.9454001282636374 and parameters: {'weight_class_0': 0.17216901241420024, 'weight_class_1': 9.327409642438576, 'weight_class_2': 7.802784801461258}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:05,031] Trial 1415 finished with value: 0.8777498138688237 and parameters: {'weight_class_0': 8.437518016460967, 'weight_class_1': 9.339958426584072, 'weight_class_2': 7.761279279666907}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:05,048] Trial 1416 finished with value: 0.9451907433948689 and parameters: {'weight_class_0': 0.25123727942786517, 'weight_class_1': 9.278887427148563, 'weight_class_2': 0.9883280318388756}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:05,077] Trial 1417 finished with value: 0.9456624850127463 and parameters: {'weight_class_0': 0.18708649604190442, 'weight_class_1': 9.3596880363109, 'weight_class_2': 8.841384102428346}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:05,082] Trial 1418 finished with value: 0.9450633472839153 and parameters: {'weight_class_0': 0.16778522557561504, 'weight_class_1': 9.674417136105195, 'weight_class_2': 7.761849231997126}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:05,120] Trial 1420 finished with value: 0.9484441420474186 and parameters: {'weight_class_0': 1.0877277937799712, 'weight_class_1': 9.647720808490151, 'weight_class_2': 7.82946331613743}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:05,123] Trial 1419 finished with value: 0.9485897609568626 and parameters: {'weight_class_0': 1.1289918791980669, 'weight_class_1': 9.603014003488415, 'weight_class_2': 8.851597084329393}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:05,167] Trial 1421 finished with value: 0.9460335961916927 and parameters: {'weight_class_0': 0.19510959091776509, 'weight_class_1': 9.634285811289255, 'weight_class_2': 7.811978273447596}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  72%|██████████████████████████████████████████████████████████████████████████████████████████████▍                                     | 1430/2000 [00:29<00:13, 43.47it/s]

[I 2026-07-08 13:33:05,179] Trial 1422 finished with value: 0.9480423225200963 and parameters: {'weight_class_0': 1.1772215845541463, 'weight_class_1': 9.637917081040264, 'weight_class_2': 7.3397131401409075}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:05,218] Trial 1423 finished with value: 0.9482592536174651 and parameters: {'weight_class_0': 1.114509858131255, 'weight_class_1': 9.678457110208944, 'weight_class_2': 7.385609107368522}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:05,250] Trial 1425 finished with value: 0.9480909473666351 and parameters: {'weight_class_0': 1.1682143736555026, 'weight_class_1': 9.660718185372238, 'weight_class_2': 7.398159398846854}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:05,257] Trial 1424 finished with value: 0.9483104618881475 and parameters: {'weight_class_0': 1.0864433071662243, 'weight_class_1': 9.606339816817322, 'weight_class_2': 7.357228083980651}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:05,300] Trial 1426 finished with value: 0.9482324753898889 and parameters: {'weight_class_0': 1.1198003591754175, 'weight_class_1': 9.640551228685531, 'weight_class_2': 7.340601142765835}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:05,308] Trial 1427 finished with value: 0.9468908765626215 and parameters: {'weight_class_0': 1.0321271967649988, 'weight_class_1': 8.971019876739078, 'weight_class_2': 4.7730156931614465}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:05,352] Trial 1428 finished with value: 0.9491454975158806 and parameters: {'weight_class_0': 0.7030538573873294, 'weight_class_1': 8.920358789062373, 'weight_class_2': 7.401881203997485}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:05,381] Trial 1429 finished with value: 0.9487077072741606 and parameters: {'weight_class_0': 0.6552976507280422, 'weight_class_1': 8.933468994119707, 'weight_class_2': 4.809621165955373}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:05,392] Trial 1430 finished with value: 0.9492488653448717 and parameters: {'weight_class_0': 0.646632427069918, 'weight_class_1': 8.950411214051702, 'weight_class_2': 7.34086450739918}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:33:05,406] Trial 1431 finished with value: 0.9492263522203377 and parameters: {'weight_class_0': 0.6695316853052203, 'weight_class_1': 8.917337688763773, 'weight_class_2': 7.375102313406758}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:05,437] Trial 1432 finished with value: 0.9490486291476984 and parameters: {'weight_class_0': 0.6665842459729492, 'weight_class_1': 9.648804017305013, 'weight_class_2': 5.909426353573537}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:05,477] Trial 1434 finished with value: 0.9491435284309531 and parameters: {'weight_class_0': 0.5791972213342654, 'weight_class_1': 9.09262154651531, 'weight_class_2': 7.353514488286128}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:05,478] Trial 1433 finished with value: 0.945172042033604 and parameters: {'weight_class_0': 0.6605267704033662, 'weight_class_1': 9.993481420307289, 'weight_class_2': 2.3351480843325096}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:05,504] Trial 1435 finished with value: 0.9491792133889209 and parameters: {'weight_class_0': 0.6184355906495067, 'weight_class_1': 9.981609475041687, 'weight_class_2': 7.984521311890343}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:05,534] Trial 1437 finished with value: 0.949101676979511 and parameters: {'weight_class_0': 0.5992962462708409, 'weight_class_1': 9.02509222207759, 'weight_class_2': 7.9484653758094135}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:05,541] Trial 1436 finished with value: 0.9491500421607441 and parameters: {'weight_class_0': 0.6707223372837132, 'weight_class_1': 9.99917759660295, 'weight_class_2': 8.019177979667445}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:05,577] Trial 1438 finished with value: 0.9490285650939976 and parameters: {'weight_class_0': 0.6292728652682005, 'weight_class_1': 8.963814187665651, 'weight_class_2': 5.2767618898471245}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:05,618] Trial 1440 finished with value: 0.9491621999105883 and parameters: {'weight_class_0': 0.6717649520682015, 'weight_class_1': 8.98088173194354, 'weight_class_2': 7.978654835664365}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  72%|███████████████████████████████████████████████████████████████████████████████████████████████▌                                    | 1448/2000 [00:30<00:13, 40.39it/s]

[I 2026-07-08 13:33:05,619] Trial 1439 finished with value: 0.9490990443339422 and parameters: {'weight_class_0': 0.6076576011271131, 'weight_class_1': 9.049224610829505, 'weight_class_2': 5.903687700744259}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:05,629] Trial 1441 finished with value: 0.9491266983676404 and parameters: {'weight_class_0': 0.5486215663999394, 'weight_class_1': 9.813827276908867, 'weight_class_2': 7.279716670590238}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:05,647] Trial 1442 finished with value: 0.9491326066146822 and parameters: {'weight_class_0': 0.5526008250151897, 'weight_class_1': 8.792305405247172, 'weight_class_2': 7.303600836233412}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:05,717] Trial 1443 finished with value: 0.9491045762753013 and parameters: {'weight_class_0': 0.5220158784009838, 'weight_class_1': 8.753321099562584, 'weight_class_2': 7.237340531083521}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:05,720] Trial 1444 finished with value: 0.9490623074408894 and parameters: {'weight_class_0': 0.5576477141127685, 'weight_class_1': 8.898192697911691, 'weight_class_2': 5.2198756847219565}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:05,733] Trial 1445 finished with value: 0.9490026128425181 and parameters: {'weight_class_0': 0.4593398946741257, 'weight_class_1': 8.910073882149977, 'weight_class_2': 7.241872145874553}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:05,759] Trial 1446 finished with value: 0.9489811385355956 and parameters: {'weight_class_0': 0.4509482525098596, 'weight_class_1': 8.998335409921246, 'weight_class_2': 7.233915858065712}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:05,780] Trial 1447 finished with value: 0.9491533382685442 and parameters: {'weight_class_0': 0.44202261861233905, 'weight_class_1': 8.870423227619396, 'weight_class_2': 5.458104683841687}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:05,815] Trial 1449 finished with value: 0.948732282876405 and parameters: {'weight_class_0': 0.393181870340209, 'weight_class_1': 8.74738266867813, 'weight_class_2': 7.206756728748336}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  73%|████████████████████████████████████████████████████████████████████████████████████████████████▏                                   | 1457/2000 [00:30<00:13, 40.86it/s]

[I 2026-07-08 13:33:05,828] Trial 1448 finished with value: 0.9488271604323385 and parameters: {'weight_class_0': 0.40953370807566325, 'weight_class_1': 8.865261117475065, 'weight_class_2': 7.191619474976227}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:05,859] Trial 1450 finished with value: 0.9489857655189496 and parameters: {'weight_class_0': 0.4505695661325025, 'weight_class_1': 8.90315130977379, 'weight_class_2': 7.229952782448029}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:05,881] Trial 1451 finished with value: 0.9486765063706321 and parameters: {'weight_class_0': 0.38238276462980125, 'weight_class_1': 8.7768558717121, 'weight_class_2': 7.223269379621196}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:05,909] Trial 1452 finished with value: 0.657900394876335 and parameters: {'weight_class_0': 0.005522138922329223, 'weight_class_1': 8.893005411965126, 'weight_class_2': 8.62464471608839}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:05,943] Trial 1453 finished with value: 0.9488824722284086 and parameters: {'weight_class_0': 0.9337323753293043, 'weight_class_1': 8.737893355449105, 'weight_class_2': 8.627131282280038}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:05,969] Trial 1454 finished with value: 0.9488417393501208 and parameters: {'weight_class_0': 0.9522629035615996, 'weight_class_1': 8.825915752796975, 'weight_class_2': 8.611126322681336}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:06,009] Trial 1456 finished with value: 0.9486217991036209 and parameters: {'weight_class_0': 0.9617377307951172, 'weight_class_1': 8.611518328061988, 'weight_class_2': 7.5872360090660305}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:06,025] Trial 1455 finished with value: 0.9487920976724763 and parameters: {'weight_class_0': 0.928119873140876, 'weight_class_1': 8.665365458960371, 'weight_class_2': 7.60622449864115}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:06,047] Trial 1457 finished with value: 0.9486148994380468 and parameters: {'weight_class_0': 0.9561114579149379, 'weight_class_1': 8.577474380669845, 'weight_class_2': 7.538344717636516}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  73%|████████████████████████████████████████████████████████████████████████████████████████████████▋                                   | 1465/2000 [00:30<00:12, 42.29it/s]

[I 2026-07-08 13:33:06,062] Trial 1458 finished with value: 0.9488236150446171 and parameters: {'weight_class_0': 0.9533310425363493, 'weight_class_1': 8.591372247500379, 'weight_class_2': 8.666155583601325}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:06,094] Trial 1459 finished with value: 0.9486460627168843 and parameters: {'weight_class_0': 0.9683037382636188, 'weight_class_1': 9.116105099907397, 'weight_class_2': 7.52360038495376}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:06,125] Trial 1460 finished with value: 0.9489938268981467 and parameters: {'weight_class_0': 0.9049255931884013, 'weight_class_1': 9.152703134439008, 'weight_class_2': 8.600956893534342}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:06,146] Trial 1461 finished with value: 0.948664939564734 and parameters: {'weight_class_0': 0.9592440493202568, 'weight_class_1': 9.453297755803995, 'weight_class_2': 7.500153656150091}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:06,176] Trial 1462 finished with value: 0.9487893147217045 and parameters: {'weight_class_0': 0.9475221921301207, 'weight_class_1': 9.140740074186784, 'weight_class_2': 7.664068784383441}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:06,224] Trial 1464 finished with value: 0.9483255548524206 and parameters: {'weight_class_0': 0.9465878814533459, 'weight_class_1': 8.53888446115384, 'weight_class_2': 6.297183428523443}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:06,233] Trial 1463 finished with value: 0.9487033718632247 and parameters: {'weight_class_0': 0.9442493370971969, 'weight_class_1': 8.598978928620816, 'weight_class_2': 7.555080501878318}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:06,246] Trial 1465 finished with value: 0.9488702498192296 and parameters: {'weight_class_0': 0.9365237763504175, 'weight_class_1': 9.148461619954547, 'weight_class_2': 8.169201998661066}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  74%|█████████████████████████████████████████████████████████████████████████████████████████████████▎                                  | 1475/2000 [00:30<00:12, 41.01it/s]

[I 2026-07-08 13:33:06,283] Trial 1466 finished with value: 0.9489832450500192 and parameters: {'weight_class_0': 0.8193601294625713, 'weight_class_1': 9.134022273420323, 'weight_class_2': 7.550579235803878}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:06,286] Trial 1467 finished with value: 0.9490634351122768 and parameters: {'weight_class_0': 0.7855170402335027, 'weight_class_1': 9.1429143319044, 'weight_class_2': 8.094705996393438}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:06,320] Trial 1469 finished with value: 0.9491761881720686 and parameters: {'weight_class_0': 0.7555340820468259, 'weight_class_1': 9.223087281648233, 'weight_class_2': 8.15628309199858}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:06,342] Trial 1468 finished with value: 0.9491669071224426 and parameters: {'weight_class_0': 0.7384408950532699, 'weight_class_1': 9.203773500465928, 'weight_class_2': 8.219210453501136}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:06,384] Trial 1470 finished with value: 0.9491916761134395 and parameters: {'weight_class_0': 0.7766669827390441, 'weight_class_1': 9.991769128999703, 'weight_class_2': 8.257301109413717}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:06,389] Trial 1471 finished with value: 0.949178845091268 and parameters: {'weight_class_0': 0.7164294896264223, 'weight_class_1': 9.45644618894995, 'weight_class_2': 8.214564263752852}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:06,419] Trial 1472 finished with value: 0.9492297108518843 and parameters: {'weight_class_0': 0.7410850277827532, 'weight_class_1': 9.809399545662288, 'weight_class_2': 8.22036271174694}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:06,429] Trial 1473 finished with value: 0.9491678240256665 and parameters: {'weight_class_0': 0.7625296295876957, 'weight_class_1': 9.49142426282226, 'weight_class_2': 8.230594056898623}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:06,452] Trial 1474 finished with value: 0.9489998161932006 and parameters: {'weight_class_0': 0.7499778351081839, 'weight_class_1': 9.999803274492011, 'weight_class_2': 6.267382934747451}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:06,484] Trial 1476 finished with value: 0.9492302898274704 and parameters: {'weight_class_0': 0.7346978255517946, 'weight_class_1': 9.989564774555037, 'weight_class_2': 8.216969958896339}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  74%|█████████████████████████████████████████████████████████████████████████████████████████████████▊                                  | 1482/2000 [00:30<00:13, 38.35it/s]

[I 2026-07-08 13:33:06,486] Trial 1475 finished with value: 0.94919012287678 and parameters: {'weight_class_0': 0.7369354191309152, 'weight_class_1': 9.451061485033476, 'weight_class_2': 8.082071747939223}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:06,527] Trial 1477 finished with value: 0.9009954756007538 and parameters: {'weight_class_0': 5.521047012490198, 'weight_class_1': 9.99745510090884, 'weight_class_2': 6.690006447953593}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:06,580] Trial 1478 finished with value: 0.9492114592271913 and parameters: {'weight_class_0': 0.7252108471147771, 'weight_class_1': 9.999491226728404, 'weight_class_2': 7.826449134559942}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:06,582] Trial 1479 finished with value: 0.9477455134213922 and parameters: {'weight_class_0': 0.28998381593890693, 'weight_class_1': 9.494474959399742, 'weight_class_2': 7.835035260655857}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:06,632] Trial 1480 finished with value: 0.9476577013851211 and parameters: {'weight_class_0': 0.2817628919353981, 'weight_class_1': 9.449318232051683, 'weight_class_2': 7.892141382845077}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:06,663] Trial 1483 finished with value: 0.9482841095911523 and parameters: {'weight_class_0': 1.1979786599919966, 'weight_class_1': 9.808744074339685, 'weight_class_2': 8.300582181307385}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:06,672] Trial 1481 finished with value: 0.9478111741106447 and parameters: {'weight_class_0': 0.30353122868297905, 'weight_class_1': 9.779256607886792, 'weight_class_2': 7.870213097260118}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  75%|██████████████████████████████████████████████████████████████████████████████████████████████████▍                                 | 1492/2000 [00:31<00:12, 41.61it/s]

[I 2026-07-08 13:33:06,683] Trial 1482 finished with value: 0.9477564185864736 and parameters: {'weight_class_0': 0.299834075080869, 'weight_class_1': 9.830086480936853, 'weight_class_2': 7.881366306955403}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:06,688] Trial 1484 finished with value: 0.9479512044505661 and parameters: {'weight_class_0': 1.297920489256373, 'weight_class_1': 9.789310234772422, 'weight_class_2': 8.408912670137603}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:06,724] Trial 1485 finished with value: 0.948175071132148 and parameters: {'weight_class_0': 1.2446352885347094, 'weight_class_1': 9.81468713941149, 'weight_class_2': 8.260265540736532}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:06,727] Trial 1486 finished with value: 0.9481330412231275 and parameters: {'weight_class_0': 1.2248486579685172, 'weight_class_1': 9.687600300919092, 'weight_class_2': 8.051093903376872}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:06,767] Trial 1487 finished with value: 0.9480858455145323 and parameters: {'weight_class_0': 1.2882599191818065, 'weight_class_1': 9.65617514465473, 'weight_class_2': 8.921888422187218}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:06,804] Trial 1488 finished with value: 0.9477524885862939 and parameters: {'weight_class_0': 1.3584878029333762, 'weight_class_1': 9.76722448460017, 'weight_class_2': 8.370146627031327}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:06,812] Trial 1489 finished with value: 0.9462080176817187 and parameters: {'weight_class_0': 1.7213753812723156, 'weight_class_1': 9.69287922436633, 'weight_class_2': 8.80311118645127}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:06,847] Trial 1490 finished with value: 0.9485113534188416 and parameters: {'weight_class_0': 1.1060588598117866, 'weight_class_1': 9.683096578438148, 'weight_class_2': 8.414685003680587}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:06,886] Trial 1491 finished with value: 0.948272627046492 and parameters: {'weight_class_0': 1.2002518605221082, 'weight_class_1': 9.685372552941523, 'weight_class_2': 8.471617257994579}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:06,902] Trial 1492 finished with value: 0.9478214911531069 and parameters: {'weight_class_0': 1.315178065596335, 'weight_class_1': 9.66566969387843, 'weight_class_2': 8.339681962457181}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  75%|███████████████████████████████████████████████████████████████████████████████████████████████████                                 | 1500/2000 [00:31<00:12, 39.71it/s]

[I 2026-07-08 13:33:06,941] Trial 1493 finished with value: 0.8876363740461315 and parameters: {'weight_class_0': 7.654979960239096, 'weight_class_1': 9.631431081393869, 'weight_class_2': 8.53826576274099}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:06,971] Trial 1494 finished with value: 0.8877479443179327 and parameters: {'weight_class_0': 7.6293879884666165, 'weight_class_1': 9.638336254429708, 'weight_class_2': 8.50063633357151}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:07,000] Trial 1495 finished with value: 0.9485308127426816 and parameters: {'weight_class_0': 1.1062937495450607, 'weight_class_1': 9.643525706377126, 'weight_class_2': 8.464470566491913}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:07,018] Trial 1496 finished with value: 0.8881247473938215 and parameters: {'weight_class_0': 7.551014078522323, 'weight_class_1': 9.669411738377082, 'weight_class_2': 8.408210829450367}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:07,036] Trial 1497 finished with value: 0.9488845091005186 and parameters: {'weight_class_0': 0.5050656500715767, 'weight_class_1': 9.643056889201578, 'weight_class_2': 8.485872212382418}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:07,072] Trial 1498 finished with value: 0.948942347309902 and parameters: {'weight_class_0': 0.5126555610331802, 'weight_class_1': 9.449491359283922, 'weight_class_2': 8.399878793935889}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:07,102] Trial 1500 finished with value: 0.948882970713448 and parameters: {'weight_class_0': 0.48743828865159633, 'weight_class_1': 9.446895712787105, 'weight_class_2': 8.436051513493995}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:07,108] Trial 1501 finished with value: 0.9489421528796854 and parameters: {'weight_class_0': 0.5211205501567896, 'weight_class_1': 9.443524866883202, 'weight_class_2': 8.470716708043689}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:33:07,111] Trial 1499 finished with value: 0.6604989096576418 and parameters: {'weight_class_0': 0.00823934168728524, 'weight_class_1': 9.508685171605372, 'weight_class_2': 8.50057170184043}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:07,166] Trial 1502 finished with value: 0.9489412795049755 and parameters: {'weight_class_0': 0.5124375056129775, 'weight_class_1': 9.489841655955184, 'weight_class_2': 8.48665086615271}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:07,197] Trial 1504 finished with value: 0.9489209945472066 and parameters: {'weight_class_0': 0.4931714886489219, 'weight_class_1': 9.993942930100966, 'weight_class_2': 8.352469491297658}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:07,216] Trial 1503 finished with value: 0.9489558193507343 and parameters: {'weight_class_0': 0.5118885805792007, 'weight_class_1': 9.447634712586028, 'weight_class_2': 8.419548995736774}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:07,239] Trial 1505 finished with value: 0.9489205639598602 and parameters: {'weight_class_0': 0.5102383272214572, 'weight_class_1': 9.418025987059233, 'weight_class_2': 8.557633244852793}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:07,257] Trial 1506 finished with value: 0.6622731579246485 and parameters: {'weight_class_0': 0.009122163044506193, 'weight_class_1': 9.378399044295278, 'weight_class_2': 8.343656396747535}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:07,298] Trial 1507 finished with value: 0.9489026834213613 and parameters: {'weight_class_0': 0.48509264916243244, 'weight_class_1': 9.328156021786997, 'weight_class_2': 8.690277727480877}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:07,333] Trial 1508 finished with value: 0.948960047959383 and parameters: {'weight_class_0': 0.5031794862427975, 'weight_class_1': 9.425696283282523, 'weight_class_2': 8.145201730277362}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:07,355] Trial 1510 finished with value: 0.9491749444847982 and parameters: {'weight_class_0': 0.681215363429873, 'weight_class_1': 9.828151494375398, 'weight_class_2': 8.165907908368116}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  76%|████████████████████████████████████████████████████████████████████████████████████████████████████                                | 1517/2000 [00:31<00:12, 37.43it/s]

[I 2026-07-08 13:33:07,356] Trial 1509 finished with value: 0.9488451647896224 and parameters: {'weight_class_0': 0.4881979163487729, 'weight_class_1': 9.99595398817882, 'weight_class_2': 8.700922674118925}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:07,408] Trial 1511 finished with value: 0.8964687387570778 and parameters: {'weight_class_0': 0.7181795686354997, 'weight_class_1': 0.2669296247244084, 'weight_class_2': 8.27810845089953}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:07,443] Trial 1512 finished with value: 0.9492398408095628 and parameters: {'weight_class_0': 0.7466360690074687, 'weight_class_1': 9.984124979837558, 'weight_class_2': 8.177277614634216}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:07,467] Trial 1513 finished with value: 0.9492258861588508 and parameters: {'weight_class_0': 0.7507176651396652, 'weight_class_1': 9.999246606446714, 'weight_class_2': 8.124861015425441}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:07,507] Trial 1514 finished with value: 0.9492183665026404 and parameters: {'weight_class_0': 0.7221538221917703, 'weight_class_1': 9.98920508940253, 'weight_class_2': 8.034336411387908}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:07,517] Trial 1515 finished with value: 0.9475208590890375 and parameters: {'weight_class_0': 0.7391356222730276, 'weight_class_1': 3.8595486673870516, 'weight_class_2': 8.157655116784387}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:07,569] Trial 1516 finished with value: 0.9491291252951136 and parameters: {'weight_class_0': 0.7972271408078372, 'weight_class_1': 9.998710892640485, 'weight_class_2': 8.179513401395196}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:07,587] Trial 1517 finished with value: 0.9491942005837259 and parameters: {'weight_class_0': 0.7665477025547596, 'weight_class_1': 9.992545117154853, 'weight_class_2': 8.125371222870244}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:33:07,596] Trial 1518 finished with value: 0.9476739995418603 and parameters: {'weight_class_0': 0.7548963255423662, 'weight_class_1': 9.996047389265003, 'weight_class_2': 3.865184972180406}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:07,621] Trial 1519 finished with value: 0.9491451962882294 and parameters: {'weight_class_0': 0.7725265019103487, 'weight_class_1': 9.132284035734209, 'weight_class_2': 8.086650441294335}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:07,675] Trial 1520 finished with value: 0.9490551916954418 and parameters: {'weight_class_0': 0.7919446555783132, 'weight_class_1': 9.215589462243914, 'weight_class_2': 8.06123957580531}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:07,696] Trial 1521 finished with value: 0.9487116493970978 and parameters: {'weight_class_0': 1.0436335572873048, 'weight_class_1': 9.98815635348848, 'weight_class_2': 8.216287227481233}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:07,713] Trial 1522 finished with value: 0.9490020319161913 and parameters: {'weight_class_0': 0.8051842831285226, 'weight_class_1': 9.186893822777074, 'weight_class_2': 8.038883779614393}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:07,733] Trial 1523 finished with value: 0.9485205725899607 and parameters: {'weight_class_0': 1.057678600211537, 'weight_class_1': 9.22902306278423, 'weight_class_2': 8.134371802477672}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:07,776] Trial 1524 finished with value: 0.948723008493134 and parameters: {'weight_class_0': 1.0351893558702998, 'weight_class_1': 9.998598173566824, 'weight_class_2': 8.171283571855064}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:07,817] Trial 1526 finished with value: 0.9485726068362738 and parameters: {'weight_class_0': 1.1022816774504993, 'weight_class_1': 9.99716175719787, 'weight_class_2': 8.251037845944971}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  77%|█████████████████████████████████████████████████████████████████████████████████████████████████████▏                              | 1533/2000 [00:32<00:12, 37.05it/s]

[I 2026-07-08 13:33:07,820] Trial 1525 finished with value: 0.9489223719656891 and parameters: {'weight_class_0': 0.9674967914425887, 'weight_class_1': 9.80698423759592, 'weight_class_2': 8.929467693262906}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:07,849] Trial 1527 finished with value: 0.9485354517537713 and parameters: {'weight_class_0': 1.1257620915573743, 'weight_class_1': 9.838346950933447, 'weight_class_2': 8.77576018601757}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:07,854] Trial 1528 finished with value: 0.9485876474363121 and parameters: {'weight_class_0': 1.0897576031209935, 'weight_class_1': 9.813139527225278, 'weight_class_2': 8.267889815034025}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:07,880] Trial 1529 finished with value: 0.9487031322056904 and parameters: {'weight_class_0': 1.0895643547503246, 'weight_class_1': 9.818898556476778, 'weight_class_2': 8.762118804497797}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:07,921] Trial 1530 finished with value: 0.9486903895691893 and parameters: {'weight_class_0': 1.046619776266925, 'weight_class_1': 9.802186077029154, 'weight_class_2': 8.271094059935859}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:07,960] Trial 1531 finished with value: 0.9162709590636501 and parameters: {'weight_class_0': 4.9743621821628095, 'weight_class_1': 9.83028238413898, 'weight_class_2': 8.960785258900824}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:07,968] Trial 1532 finished with value: 0.9488141057276668 and parameters: {'weight_class_0': 1.0604917477539098, 'weight_class_1': 9.848536761505784, 'weight_class_2': 8.751900261269608}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:08,013] Trial 1534 finished with value: 0.9488823462378617 and parameters: {'weight_class_0': 0.980738352524753, 'weight_class_1': 9.789039679755273, 'weight_class_2': 8.200664852460758}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  77%|█████████████████████████████████████████████████████████████████████████████████████████████████████▊                              | 1542/2000 [00:32<00:12, 37.51it/s]

[I 2026-07-08 13:33:08,027] Trial 1533 finished with value: 0.9487678654571942 and parameters: {'weight_class_0': 1.095693316085685, 'weight_class_1': 9.824604244749697, 'weight_class_2': 8.982080205121896}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:08,055] Trial 1535 finished with value: 0.9486067099814539 and parameters: {'weight_class_0': 1.0696610247134721, 'weight_class_1': 9.822518322108825, 'weight_class_2': 8.25801664801921}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:08,087] Trial 1536 finished with value: 0.9465427185383519 and parameters: {'weight_class_0': 1.6150293244488765, 'weight_class_1': 9.812817214686154, 'weight_class_2': 8.341177777458578}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:08,106] Trial 1537 finished with value: 0.9464500228891078 and parameters: {'weight_class_0': 0.22189848709421733, 'weight_class_1': 9.817752678280444, 'weight_class_2': 8.698396685794496}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:08,152] Trial 1538 finished with value: 0.9479577383348733 and parameters: {'weight_class_0': 0.32464695325767245, 'weight_class_1': 9.802449276063449, 'weight_class_2': 8.318108181504712}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:08,154] Trial 1539 finished with value: 0.9469125780659461 and parameters: {'weight_class_0': 0.2456050909099165, 'weight_class_1': 9.782875116962865, 'weight_class_2': 8.592938316888256}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:08,209] Trial 1541 finished with value: 0.9477254365870676 and parameters: {'weight_class_0': 0.28597387304665856, 'weight_class_1': 8.484866070709199, 'weight_class_2': 8.636375589872651}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:08,216] Trial 1540 finished with value: 0.9467986197176742 and parameters: {'weight_class_0': 0.23987286692898774, 'weight_class_1': 9.80285438020016, 'weight_class_2': 8.585473549302087}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:08,236] Trial 1542 finished with value: 0.9465446265184064 and parameters: {'weight_class_0': 1.6005991579564949, 'weight_class_1': 9.656387394098621, 'weight_class_2': 8.338419636818916}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  78%|██████████████████████████████████████████████████████████████████████████████████████████████████████▎                             | 1550/2000 [00:32<00:11, 37.77it/s]

[I 2026-07-08 13:33:08,277] Trial 1543 finished with value: 0.9482463552970232 and parameters: {'weight_class_0': 0.35417478922807993, 'weight_class_1': 8.451999003165392, 'weight_class_2': 8.64816672635256}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:08,303] Trial 1544 finished with value: 0.9477181594102447 and parameters: {'weight_class_0': 0.30150222886895706, 'weight_class_1': 9.609360562798528, 'weight_class_2': 8.58152905435935}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:08,340] Trial 1545 finished with value: 0.9403320072731117 and parameters: {'weight_class_0': 1.526068191043903, 'weight_class_1': 4.274689769695629, 'weight_class_2': 7.99856118472071}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:08,353] Trial 1546 finished with value: 0.9476644871163434 and parameters: {'weight_class_0': 0.2773263625069456, 'weight_class_1': 8.490445836421472, 'weight_class_2': 8.613346183840145}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:08,400] Trial 1547 finished with value: 0.9478876057429249 and parameters: {'weight_class_0': 0.3194101907597368, 'weight_class_1': 8.427581959770984, 'weight_class_2': 9.689856400175515}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:08,409] Trial 1548 finished with value: 0.9468272392997404 and parameters: {'weight_class_0': 1.4725889160314745, 'weight_class_1': 8.516580311073163, 'weight_class_2': 8.611643417899884}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:08,439] Trial 1549 finished with value: 0.9464889070287817 and parameters: {'weight_class_0': 1.4829121314456737, 'weight_class_1': 8.479279734479702, 'weight_class_2': 8.010082737536436}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:08,481] Trial 1550 finished with value: 0.9480609800372092 and parameters: {'weight_class_0': 0.3281385851876141, 'weight_class_1': 9.574234323024779, 'weight_class_2': 8.034104443686035}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  78%|██████████████████████████████████████████████████████████████████████████████████████████████████████▉                             | 1559/2000 [00:33<00:11, 36.92it/s]

[I 2026-07-08 13:33:08,487] Trial 1551 finished with value: 0.9490681399467763 and parameters: {'weight_class_0': 0.8457940325597015, 'weight_class_1': 9.999340735691078, 'weight_class_2': 8.044059776556322}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:08,540] Trial 1552 finished with value: 0.8984576621485378 and parameters: {'weight_class_0': 5.968927328753372, 'weight_class_1': 8.729533612670563, 'weight_class_2': 8.029219001853912}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:08,541] Trial 1553 finished with value: 0.9490563239951354 and parameters: {'weight_class_0': 0.8179893423793364, 'weight_class_1': 9.590205019883797, 'weight_class_2': 8.02267446799997}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:08,545] Trial 1554 finished with value: 0.9489394604400022 and parameters: {'weight_class_0': 0.8549711484865619, 'weight_class_1': 8.908179775107044, 'weight_class_2': 7.9864613699248155}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:08,588] Trial 1555 finished with value: 0.9469802511663127 and parameters: {'weight_class_0': 0.8976839058032795, 'weight_class_1': 4.284576720027495, 'weight_class_2': 8.01216821739715}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:08,615] Trial 1556 finished with value: 0.9488805261579537 and parameters: {'weight_class_0': 0.8806771178767864, 'weight_class_1': 8.813837460428653, 'weight_class_2': 7.9590641118266845}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:08,667] Trial 1557 finished with value: 0.94902181985899 and parameters: {'weight_class_0': 0.8561617251223207, 'weight_class_1': 9.562469726090875, 'weight_class_2': 8.040519585901476}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:08,683] Trial 1559 finished with value: 0.9489393503477563 and parameters: {'weight_class_0': 0.8773018340169396, 'weight_class_1': 8.954257816140542, 'weight_class_2': 8.035278220656128}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:08,697] Trial 1558 finished with value: 0.9489289098537478 and parameters: {'weight_class_0': 0.8992337600139466, 'weight_class_1': 8.751046902856954, 'weight_class_2': 8.01766192542151}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  78%|███████████████████████████████████████████████████████████████████████████████████████████████████████▍                            | 1568/2000 [00:33<00:10, 39.33it/s]

[I 2026-07-08 13:33:08,739] Trial 1560 finished with value: 0.9489865817978563 and parameters: {'weight_class_0': 0.859614359690311, 'weight_class_1': 8.822000665861212, 'weight_class_2': 8.093963948011773}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:08,749] Trial 1561 finished with value: 0.9489203736337961 and parameters: {'weight_class_0': 0.874883495966001, 'weight_class_1': 8.92356789519591, 'weight_class_2': 8.048305869785596}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:08,778] Trial 1562 finished with value: 0.9491759191160329 and parameters: {'weight_class_0': 0.6435139254434732, 'weight_class_1': 8.974856197562543, 'weight_class_2': 7.999300952054111}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:08,800] Trial 1563 finished with value: 0.8995190086296884 and parameters: {'weight_class_0': 5.922117035942028, 'weight_class_1': 8.992347448252877, 'weight_class_2': 7.965194534535207}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:08,803] Trial 1564 finished with value: 0.9491695722605832 and parameters: {'weight_class_0': 0.6140230513668652, 'weight_class_1': 9.596818099064798, 'weight_class_2': 7.877812745200698}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:08,827] Trial 1565 finished with value: 0.9491047378143258 and parameters: {'weight_class_0': 0.6092991166499203, 'weight_class_1': 9.990756763580116, 'weight_class_2': 8.308216500623477}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:08,835] Trial 1566 finished with value: 0.9490937291466207 and parameters: {'weight_class_0': 0.5848804987484393, 'weight_class_1': 9.020197363218054, 'weight_class_2': 8.310972617009485}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:08,862] Trial 1567 finished with value: 0.9490922014996683 and parameters: {'weight_class_0': 0.6068764588790417, 'weight_class_1': 9.028137407730423, 'weight_class_2': 8.310162591116555}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:08,892] Trial 1568 finished with value: 0.9491704300043565 and parameters: {'weight_class_0': 0.6132126730009517, 'weight_class_1': 9.990682356357267, 'weight_class_2': 7.849623190088286}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  79%|████████████████████████████████████████████████████████████████████████████████████████████████████████                            | 1577/2000 [00:33<00:11, 38.01it/s]

[I 2026-07-08 13:33:08,972] Trial 1570 finished with value: 0.9490555311703476 and parameters: {'weight_class_0': 0.6077425165971974, 'weight_class_1': 9.62891427606222, 'weight_class_2': 8.333046157413506}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:08,977] Trial 1569 finished with value: 0.9491779665916872 and parameters: {'weight_class_0': 0.5906677093756774, 'weight_class_1': 9.9990824381194, 'weight_class_2': 6.049052501502872}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:08,998] Trial 1571 finished with value: 0.9491325920734833 and parameters: {'weight_class_0': 0.6582651737787689, 'weight_class_1': 9.600906154578297, 'weight_class_2': 8.337713853854627}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:09,047] Trial 1572 finished with value: 0.9491135066576911 and parameters: {'weight_class_0': 0.6340490751759366, 'weight_class_1': 9.606964984791636, 'weight_class_2': 8.318060240284884}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:09,062] Trial 1573 finished with value: 0.9491536182577255 and parameters: {'weight_class_0': 0.6510716606917363, 'weight_class_1': 9.6174040162976, 'weight_class_2': 8.372286233972636}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:09,080] Trial 1575 finished with value: 0.9490973033802305 and parameters: {'weight_class_0': 0.6145383744117366, 'weight_class_1': 9.405453714331252, 'weight_class_2': 8.309076695376742}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:09,109] Trial 1576 finished with value: 0.9491253118692137 and parameters: {'weight_class_0': 0.5825864199890863, 'weight_class_1': 9.288627720370709, 'weight_class_2': 7.821787117502913}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:09,112] Trial 1574 finished with value: 0.949081650605024 and parameters: {'weight_class_0': 0.6120122519685058, 'weight_class_1': 9.243355646918515, 'weight_class_2': 8.367463550210037}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:09,151] Trial 1577 finished with value: 0.8959422095849768 and parameters: {'weight_class_0': 6.322290976003021, 'weight_class_1': 9.397926198947525, 'weight_class_2': 7.833102375513756}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  79%|████████████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 1586/2000 [00:33<00:10, 39.23it/s]

[I 2026-07-08 13:33:09,171] Trial 1578 finished with value: 0.9489079348132125 and parameters: {'weight_class_0': 0.4932194615307759, 'weight_class_1': 9.311007513187622, 'weight_class_2': 8.30065849652777}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:09,200] Trial 1580 finished with value: 0.9487449979570307 and parameters: {'weight_class_0': 0.42600045159238564, 'weight_class_1': 9.31144068173501, 'weight_class_2': 7.815284843760601}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:09,213] Trial 1579 finished with value: 0.9490655789951284 and parameters: {'weight_class_0': 0.5176266439096545, 'weight_class_1': 9.29380112491135, 'weight_class_2': 7.802291964552594}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:09,243] Trial 1581 finished with value: 0.9489136304161527 and parameters: {'weight_class_0': 0.4589850250842654, 'weight_class_1': 9.292753863340344, 'weight_class_2': 7.807586222711706}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:09,286] Trial 1582 finished with value: 0.9479562060948564 and parameters: {'weight_class_0': 1.276783903339322, 'weight_class_1': 9.9998789739761, 'weight_class_2': 7.821510084556421}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:09,300] Trial 1583 finished with value: 0.9481112354136219 and parameters: {'weight_class_0': 1.1904916046457437, 'weight_class_1': 9.231327264570416, 'weight_class_2': 7.787057349094842}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:09,315] Trial 1584 finished with value: 0.9486382316662629 and parameters: {'weight_class_0': 0.40005205325506416, 'weight_class_1': 9.327996019805944, 'weight_class_2': 7.817871947753773}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:09,345] Trial 1585 finished with value: 0.9480022949163311 and parameters: {'weight_class_0': 1.219039955524528, 'weight_class_1': 9.227486897965576, 'weight_class_2': 7.829025431795998}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:09,380] Trial 1587 finished with value: 0.947918475878874 and parameters: {'weight_class_0': 1.281239531314002, 'weight_class_1': 9.999912806816926, 'weight_class_2': 7.798736768997056}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:33:09,392] Trial 1586 finished with value: 0.9479827325343662 and parameters: {'weight_class_0': 1.2513554409121712, 'weight_class_1': 9.806335768336734, 'weight_class_2': 7.804686243516859}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:09,452] Trial 1588 finished with value: 0.9461396383544752 and parameters: {'weight_class_0': 1.3358215853632083, 'weight_class_1': 6.52985882561741, 'weight_class_2': 7.854668453776418}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:09,475] Trial 1589 finished with value: 0.9372802563115498 and parameters: {'weight_class_0': 1.2915620291795618, 'weight_class_1': 9.754028761089323, 'weight_class_2': 2.934562783161589}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:09,482] Trial 1590 finished with value: 0.9481711846634041 and parameters: {'weight_class_0': 1.229524013759963, 'weight_class_1': 9.751420667698921, 'weight_class_2': 8.137375215445541}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:09,538] Trial 1592 finished with value: 0.9432724165604879 and parameters: {'weight_class_0': 0.14052271177806075, 'weight_class_1': 9.805421337906242, 'weight_class_2': 7.783725072191106}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:09,539] Trial 1591 finished with value: 0.9482537853359335 and parameters: {'weight_class_0': 1.1526382020973442, 'weight_class_1': 9.824648071825218, 'weight_class_2': 7.765717647298237}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:09,567] Trial 1594 finished with value: 0.9488813069062668 and parameters: {'weight_class_0': 0.9474175111600475, 'weight_class_1': 9.997221676578722, 'weight_class_2': 8.191841424550066}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:09,586] Trial 1593 finished with value: 0.9488026131957766 and parameters: {'weight_class_0': 1.0008565712354613, 'weight_class_1': 9.81003950270923, 'weight_class_2': 8.07879135508428}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▊                          | 1603/2000 [00:34<00:09, 39.76it/s]

[I 2026-07-08 13:33:09,631] Trial 1595 finished with value: 0.9441468919753611 and parameters: {'weight_class_0': 0.15399608583118352, 'weight_class_1': 9.813267813616081, 'weight_class_2': 8.153073736207627}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:09,654] Trial 1596 finished with value: 0.9489080911477107 and parameters: {'weight_class_0': 0.9169317156340935, 'weight_class_1': 9.801029626940903, 'weight_class_2': 8.11015803270666}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:09,685] Trial 1598 finished with value: 0.9435367170026968 and parameters: {'weight_class_0': 0.14483104882772935, 'weight_class_1': 9.791526606947091, 'weight_class_2': 8.165668767277007}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:09,696] Trial 1597 finished with value: 0.9391270984388923 and parameters: {'weight_class_0': 0.10300969878283328, 'weight_class_1': 9.784799111992257, 'weight_class_2': 5.792974799767531}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:09,725] Trial 1599 finished with value: 0.9378800774002717 and parameters: {'weight_class_0': 0.10335252857707278, 'weight_class_1': 9.732774807781874, 'weight_class_2': 8.189951541039354}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:09,739] Trial 1600 finished with value: 0.9429028298364793 and parameters: {'weight_class_0': 0.13391900177271177, 'weight_class_1': 9.51382837339351, 'weight_class_2': 8.151606651688848}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:09,771] Trial 1601 finished with value: 0.9420024498076452 and parameters: {'weight_class_0': 0.11723336088278957, 'weight_class_1': 9.510672085930127, 'weight_class_2': 5.674402484903065}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:09,806] Trial 1602 finished with value: 0.9489196932988889 and parameters: {'weight_class_0': 0.9216551164184963, 'weight_class_1': 9.532087709766284, 'weight_class_2': 8.174052511051174}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:09,820] Trial 1603 finished with value: 0.9309783566688857 and parameters: {'weight_class_0': 3.4602867507567407, 'weight_class_1': 9.579230904810382, 'weight_class_2': 8.176513755948593}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:33:09,863] Trial 1606 finished with value: 0.9491177998716175 and parameters: {'weight_class_0': 0.8142201046752165, 'weight_class_1': 9.52504477590363, 'weight_class_2': 8.502386599018598}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:09,867] Trial 1605 finished with value: 0.9484819936763716 and parameters: {'weight_class_0': 0.8426148302924321, 'weight_class_1': 9.523073246285794, 'weight_class_2': 5.706420697299543}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:09,892] Trial 1604 finished with value: 0.9490991290087624 and parameters: {'weight_class_0': 0.8078310640456215, 'weight_class_1': 9.540441557193489, 'weight_class_2': 8.168590159784786}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:09,978] Trial 1607 finished with value: 0.899359213528352 and parameters: {'weight_class_0': 0.8237500268976818, 'weight_class_1': 9.480187691797283, 'weight_class_2': 0.4907664486549965}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:09,984] Trial 1608 finished with value: 0.949166418601492 and parameters: {'weight_class_0': 0.7914318347614211, 'weight_class_1': 9.515126448721636, 'weight_class_2': 8.500410400402366}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:10,012] Trial 1609 finished with value: 0.9491993846589567 and parameters: {'weight_class_0': 0.787750066271706, 'weight_class_1': 9.486443787111948, 'weight_class_2': 8.560207361726583}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:10,029] Trial 1610 finished with value: 0.9389345931106589 and parameters: {'weight_class_0': 0.8196109942996666, 'weight_class_1': 9.511928363461285, 'weight_class_2': 1.9821818387135752}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:10,048] Trial 1611 finished with value: 0.9491004022513883 and parameters: {'weight_class_0': 0.817379649797603, 'weight_class_1': 9.48200334056643, 'weight_class_2': 8.529387782220127}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:10,081] Trial 1612 finished with value: 0.949076843336893 and parameters: {'weight_class_0': 0.7853993133288846, 'weight_class_1': 8.283484104085575, 'weight_class_2': 8.560581429859806}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  81%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▉                         | 1620/2000 [00:34<00:10, 35.23it/s]

[I 2026-07-08 13:33:10,087] Trial 1613 finished with value: 0.9491931228200289 and parameters: {'weight_class_0': 0.758397588122304, 'weight_class_1': 9.478054620835168, 'weight_class_2': 8.55066859413209}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:10,120] Trial 1614 finished with value: 0.9490741677593104 and parameters: {'weight_class_0': 0.7653513064656415, 'weight_class_1': 8.279518331363043, 'weight_class_2': 8.51575018165082}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:10,133] Trial 1615 finished with value: 0.9485345333139157 and parameters: {'weight_class_0': 0.41129013032973194, 'weight_class_1': 9.655115773963217, 'weight_class_2': 8.437407874479428}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:10,194] Trial 1616 finished with value: 0.9486746040627435 and parameters: {'weight_class_0': 0.4159387428027846, 'weight_class_1': 8.315088671018076, 'weight_class_2': 8.57292248119187}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:10,254] Trial 1617 finished with value: 0.9484738746391145 and parameters: {'weight_class_0': 0.39964947456414407, 'weight_class_1': 9.990917974360505, 'weight_class_2': 8.442944688274538}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:10,272] Trial 1618 finished with value: 0.9484818775837557 and parameters: {'weight_class_0': 0.3910143923692022, 'weight_class_1': 8.676051302963291, 'weight_class_2': 8.505884621709935}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:10,313] Trial 1622 finished with value: 0.9489221716297195 and parameters: {'weight_class_0': 0.44946092192343173, 'weight_class_1': 8.292807982935804, 'weight_class_2': 7.646756028622163}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:10,314] Trial 1619 finished with value: 0.9484902659912224 and parameters: {'weight_class_0': 0.3855145562496653, 'weight_class_1': 8.231374160596966, 'weight_class_2': 8.538450528387521}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:33:10,319] Trial 1620 finished with value: 0.9487325049652936 and parameters: {'weight_class_0': 0.40593752337181677, 'weight_class_1': 8.611246651461137, 'weight_class_2': 7.6741703319160415}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:10,324] Trial 1621 finished with value: 0.9487469501441499 and parameters: {'weight_class_0': 0.4177755333414672, 'weight_class_1': 8.273964296742163, 'weight_class_2': 8.004956815077643}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:10,333] Trial 1624 finished with value: 0.9484478907835943 and parameters: {'weight_class_0': 0.37956806643600444, 'weight_class_1': 9.996883022256208, 'weight_class_2': 7.7085953693022145}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:10,386] Trial 1623 finished with value: 0.9486454145178853 and parameters: {'weight_class_0': 0.4134102612893359, 'weight_class_1': 9.992662141193613, 'weight_class_2': 7.725834612642697}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:10,457] Trial 1625 finished with value: 0.9484462698601533 and parameters: {'weight_class_0': 0.3579637235985549, 'weight_class_1': 9.10804310141888, 'weight_class_2': 7.6291676514108175}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:10,498] Trial 1626 finished with value: 0.9489365691754439 and parameters: {'weight_class_0': 0.3632539863784635, 'weight_class_1': 8.641994857337133, 'weight_class_2': 5.078436474274205}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▉                        | 1635/2000 [00:35<00:10, 33.22it/s]

[I 2026-07-08 13:33:10,506] Trial 1627 finished with value: 0.9487512458638258 and parameters: {'weight_class_0': 0.44246738817169484, 'weight_class_1': 9.999701558664219, 'weight_class_2': 7.72855548316453}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:10,530] Trial 1628 finished with value: 0.9484299708771874 and parameters: {'weight_class_0': 1.0405444277280802, 'weight_class_1': 8.679163749177157, 'weight_class_2': 7.691157450146642}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:10,563] Trial 1629 finished with value: 0.9491112016933453 and parameters: {'weight_class_0': 0.5612552583655318, 'weight_class_1': 9.095832027567957, 'weight_class_2': 7.66780212130919}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:10,646] Trial 1630 finished with value: 0.9472687510056126 and parameters: {'weight_class_0': 1.0179946668187814, 'weight_class_1': 9.997575580496287, 'weight_class_2': 5.000462775882627}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:10,671] Trial 1631 finished with value: 0.9470978514746653 and parameters: {'weight_class_0': 1.0317480191948394, 'weight_class_1': 9.100216814071349, 'weight_class_2': 4.970443515671103}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:10,702] Trial 1632 finished with value: 0.9487708581322698 and parameters: {'weight_class_0': 0.9981079102927498, 'weight_class_1': 9.828751310824908, 'weight_class_2': 7.983007702843825}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:10,730] Trial 1636 finished with value: 0.862742737424199 and parameters: {'weight_class_0': 9.09555182508393, 'weight_class_1': 5.337959204577561, 'weight_class_2': 8.02212639164862}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:10,731] Trial 1634 finished with value: 0.9475546467168386 and parameters: {'weight_class_0': 1.035735591160891, 'weight_class_1': 5.744910286980612, 'weight_class_2': 8.846285622481421}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:10,740] Trial 1633 finished with value: 0.9482024925960243 and parameters: {'weight_class_0': 0.9997011702345875, 'weight_class_1': 9.686867894745124, 'weight_class_2': 6.216702206569232}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  82%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                       | 1643/2000 [00:35<00:09, 36.43it/s]

[I 2026-07-08 13:33:10,742] Trial 1635 finished with value: 0.8775333929844239 and parameters: {'weight_class_0': 9.041258904287831, 'weight_class_1': 9.105185482833194, 'weight_class_2': 8.863568971403625}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:10,762] Trial 1637 finished with value: 0.9485608724007505 and parameters: {'weight_class_0': 1.01844707366207, 'weight_class_1': 9.098277613508541, 'weight_class_2': 7.9404283629396435}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:10,862] Trial 1638 finished with value: 0.9479072294628842 and parameters: {'weight_class_0': 1.065799661322175, 'weight_class_1': 9.835894607237853, 'weight_class_2': 6.082000268335646}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:10,876] Trial 1639 finished with value: 0.9491720114754426 and parameters: {'weight_class_0': 0.6711597111186145, 'weight_class_1': 9.651597220342975, 'weight_class_2': 8.807642540384556}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:10,891] Trial 1640 finished with value: 0.9456006091100974 and parameters: {'weight_class_0': 0.6833168364292778, 'weight_class_1': 9.67757984763783, 'weight_class_2': 2.5348165000894123}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:10,942] Trial 1642 finished with value: 0.9490208888923776 and parameters: {'weight_class_0': 0.6778686820384802, 'weight_class_1': 9.658331365179814, 'weight_class_2': 6.0841119857257535}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:10,944] Trial 1641 finished with value: 0.9491110289079331 and parameters: {'weight_class_0': 0.6514398765115293, 'weight_class_1': 9.736507845676375, 'weight_class_2': 8.840604414028363}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:10,981] Trial 1643 finished with value: 0.9491871587083477 and parameters: {'weight_class_0': 0.6658932750885471, 'weight_class_1': 9.698678962589534, 'weight_class_2': 7.926460781500557}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:33:11,066] Trial 1645 finished with value: 0.9491519092285449 and parameters: {'weight_class_0': 0.6430009177801194, 'weight_class_1': 9.765820269244468, 'weight_class_2': 7.950398017131061}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:11,067] Trial 1644 finished with value: 0.9491770798890582 and parameters: {'weight_class_0': 0.6524834002426195, 'weight_class_1': 9.648805508961555, 'weight_class_2': 7.993120105615105}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:11,098] Trial 1646 finished with value: 0.9491788187202133 and parameters: {'weight_class_0': 0.6511616484509679, 'weight_class_1': 9.714499981359378, 'weight_class_2': 7.9323859658857385}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:11,112] Trial 1648 finished with value: 0.9492111062443712 and parameters: {'weight_class_0': 0.6766339166804209, 'weight_class_1': 9.696062175518817, 'weight_class_2': 7.927731312121799}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:11,124] Trial 1647 finished with value: 0.9491356999372162 and parameters: {'weight_class_0': 0.6312034414458606, 'weight_class_1': 9.690532743902793, 'weight_class_2': 7.944080283325891}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  82%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                       | 1649/2000 [00:35<00:10, 34.19it/s]

[I 2026-07-08 13:33:11,176] Trial 1649 finished with value: 0.9491640269835914 and parameters: {'weight_class_0': 0.6332688467118404, 'weight_class_1': 9.689611173677967, 'weight_class_2': 7.919412528712088}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                      | 1656/2000 [00:35<00:10, 33.43it/s]

[I 2026-07-08 13:33:11,205] Trial 1650 finished with value: 0.9492133850432557 and parameters: {'weight_class_0': 0.678851482497331, 'weight_class_1': 9.69489665561469, 'weight_class_2': 7.899604028190254}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:11,260] Trial 1651 finished with value: 0.9491423462187168 and parameters: {'weight_class_0': 0.6368671120354686, 'weight_class_1': 9.689156641173843, 'weight_class_2': 7.882978506288588}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:11,273] Trial 1652 finished with value: 0.9491490903591343 and parameters: {'weight_class_0': 0.6222310280438815, 'weight_class_1': 9.822599768925768, 'weight_class_2': 7.895008398096492}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:11,286] Trial 1654 finished with value: 0.9491675325101667 and parameters: {'weight_class_0': 0.677825645248698, 'weight_class_1': 9.388086890218787, 'weight_class_2': 8.254599640294035}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:11,287] Trial 1653 finished with value: 0.9483810906157739 and parameters: {'weight_class_0': 0.6708194919022936, 'weight_class_1': 9.831513490546328, 'weight_class_2': 4.227925540127079}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:11,312] Trial 1655 finished with value: 0.9486845666836982 and parameters: {'weight_class_0': 0.5782278557798445, 'weight_class_1': 4.950055100907251, 'weight_class_2': 7.92516831451682}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:11,355] Trial 1656 finished with value: 0.949104417319225 and parameters: {'weight_class_0': 0.5938483312668978, 'weight_class_1': 8.799443505064891, 'weight_class_2': 8.297682895056498}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:33:11,416] Trial 1658 finished with value: 0.9487404980612091 and parameters: {'weight_class_0': 0.9345449723549935, 'weight_class_1': 9.28502661964193, 'weight_class_2': 7.4479909999591}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:11,438] Trial 1659 finished with value: 0.9348361032294639 and parameters: {'weight_class_0': 0.896030282665106, 'weight_class_1': 1.8104977782392173, 'weight_class_2': 6.657316160143704}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                      | 1664/2000 [00:35<00:09, 34.53it/s]

[I 2026-07-08 13:33:11,439] Trial 1657 finished with value: 0.9489086916653043 and parameters: {'weight_class_0': 0.9040784140592207, 'weight_class_1': 9.369226265312651, 'weight_class_2': 8.229957908592864}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:11,505] Trial 1660 finished with value: 0.9458117384523307 and parameters: {'weight_class_0': 0.9092882853061759, 'weight_class_1': 9.378500459589151, 'weight_class_2': 3.5252653343789104}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:11,537] Trial 1661 finished with value: 0.9488848404332161 and parameters: {'weight_class_0': 0.9054798469390408, 'weight_class_1': 9.248153945115458, 'weight_class_2': 7.451257348526882}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:11,588] Trial 1663 finished with value: 0.9488862386176766 and parameters: {'weight_class_0': 0.8700083917179378, 'weight_class_1': 8.85308646996214, 'weight_class_2': 7.497690449995341}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:11,591] Trial 1662 finished with value: 0.9481278977233011 and parameters: {'weight_class_0': 0.9090863394106341, 'weight_class_1': 8.829241072275721, 'weight_class_2': 5.514670694375585}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:11,633] Trial 1665 finished with value: 0.9486520422872206 and parameters: {'weight_class_0': 0.9708297243909481, 'weight_class_1': 9.268372301033951, 'weight_class_2': 7.454188691575359}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                      | 1666/2000 [00:35<00:09, 35.80it/s]

[I 2026-07-08 13:33:11,639] Trial 1664 finished with value: 0.6573785368780293 and parameters: {'weight_class_0': 0.000351577302291739, 'weight_class_1': 8.825342040212334, 'weight_class_2': 7.459379519251314}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:11,675] Trial 1666 finished with value: 0.9488735898334185 and parameters: {'weight_class_0': 0.9066722992366737, 'weight_class_1': 9.298417143842487, 'weight_class_2': 7.469215990669672}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  84%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                     | 1672/2000 [00:36<00:09, 35.67it/s]

[I 2026-07-08 13:33:11,694] Trial 1667 finished with value: 0.9485215499117926 and parameters: {'weight_class_0': 0.9308045543214143, 'weight_class_1': 9.220731192388648, 'weight_class_2': 6.675226259430716}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:11,707] Trial 1668 finished with value: 0.9466860843622221 and parameters: {'weight_class_0': 0.2237033218292105, 'weight_class_1': 9.985520908336895, 'weight_class_2': 7.485560939878589}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:11,761] Trial 1669 finished with value: 0.9473977264930218 and parameters: {'weight_class_0': 0.24802068015114664, 'weight_class_1': 8.862637946441684, 'weight_class_2': 7.47666009051737}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:11,798] Trial 1671 finished with value: 0.9478283728827969 and parameters: {'weight_class_0': 0.28034433536331543, 'weight_class_1': 8.819603646798091, 'weight_class_2': 7.495079595286493}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:11,804] Trial 1670 finished with value: 0.9468811798891363 and parameters: {'weight_class_0': 0.23487803882817948, 'weight_class_1': 9.985257503460158, 'weight_class_2': 7.504385334040494}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:11,854] Trial 1672 finished with value: 0.9469576421380501 and parameters: {'weight_class_0': 0.22022990857485464, 'weight_class_1': 8.800830073730486, 'weight_class_2': 7.532533324492993}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:33:11,880] Trial 1674 finished with value: 0.9468739474951325 and parameters: {'weight_class_0': 0.21339803626611165, 'weight_class_1': 8.553607606683864, 'weight_class_2': 7.625963633686259}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  84%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                     | 1674/2000 [00:36<00:09, 36.06it/s]

[I 2026-07-08 13:33:11,881] Trial 1673 finished with value: 0.9471749028413189 and parameters: {'weight_class_0': 0.22966461883865158, 'weight_class_1': 8.537921529063413, 'weight_class_2': 7.634795623746141}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  84%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                     | 1680/2000 [00:36<00:09, 35.05it/s]

[I 2026-07-08 13:33:11,912] Trial 1675 finished with value: 0.9472424185706366 and parameters: {'weight_class_0': 0.27310983436871067, 'weight_class_1': 9.855852162015893, 'weight_class_2': 9.15946339641604}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:11,956] Trial 1676 finished with value: 0.9297330733356985 and parameters: {'weight_class_0': 2.4099037563564183, 'weight_class_1': 9.981872102349186, 'weight_class_2': 4.581057962541682}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:11,974] Trial 1677 finished with value: 0.9476369501269604 and parameters: {'weight_class_0': 0.27187724289426785, 'weight_class_1': 8.529579919415204, 'weight_class_2': 8.256906869356188}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:12,007] Trial 1678 finished with value: 0.9480887216886668 and parameters: {'weight_class_0': 0.34715215619153406, 'weight_class_1': 3.2028928244804464, 'weight_class_2': 7.667282976467178}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:12,014] Trial 1679 finished with value: 0.948271911340241 and parameters: {'weight_class_0': 1.1439717264148017, 'weight_class_1': 9.841664569093945, 'weight_class_2': 7.663444555987715}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:12,065] Trial 1680 finished with value: 0.9482799123804849 and parameters: {'weight_class_0': 1.1979720809674754, 'weight_class_1': 9.986752359729804, 'weight_class_2': 8.22607250626572}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████                     | 1682/2000 [00:36<00:09, 33.52it/s]

[I 2026-07-08 13:33:12,139] Trial 1682 finished with value: 0.9468582191558443 and parameters: {'weight_class_0': 1.399810761692208, 'weight_class_1': 8.108757175904914, 'weight_class_2': 8.257051232043347}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:12,146] Trial 1681 finished with value: 0.9482203879097746 and parameters: {'weight_class_0': 1.1713462373238466, 'weight_class_1': 9.994364478942149, 'weight_class_2': 7.699747424710692}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:33:12,155] Trial 1683 finished with value: 0.9479622814092664 and parameters: {'weight_class_0': 1.1438098953047962, 'weight_class_1': 8.123475256204735, 'weight_class_2': 8.125524187527358}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:12,162] Trial 1684 finished with value: 0.9485065056009043 and parameters: {'weight_class_0': 1.1701331270332482, 'weight_class_1': 9.487035105177442, 'weight_class_2': 9.238478579794995}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:12,216] Trial 1685 finished with value: 0.9475741668878919 and parameters: {'weight_class_0': 1.3873245428526226, 'weight_class_1': 9.843199734556759, 'weight_class_2': 8.29212490948806}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:12,252] Trial 1686 finished with value: 0.948248581548755 and parameters: {'weight_class_0': 1.1755651257618651, 'weight_class_1': 9.437135480336881, 'weight_class_2': 8.269193693781613}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:12,263] Trial 1687 finished with value: 0.9367102931829056 and parameters: {'weight_class_0': 1.4128794508210865, 'weight_class_1': 9.447686203527539, 'weight_class_2': 3.1782287914297056}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:12,308] Trial 1688 finished with value: 0.9472963806449997 and parameters: {'weight_class_0': 1.4174066456001215, 'weight_class_1': 9.451333435053767, 'weight_class_2': 8.275989257971254}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  85%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                    | 1691/2000 [00:36<00:08, 35.79it/s]

[I 2026-07-08 13:33:12,315] Trial 1689 finished with value: 0.9471754006139688 and parameters: {'weight_class_0': 1.4520892892020032, 'weight_class_1': 9.47799828466577, 'weight_class_2': 8.160858977426903}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:12,321] Trial 1690 finished with value: 0.9478268283018022 and parameters: {'weight_class_0': 1.187726266630434, 'weight_class_1': 8.138132403750388, 'weight_class_2': 8.129080449915897}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:12,351] Trial 1691 finished with value: 0.9489694026068617 and parameters: {'weight_class_0': 0.49705384119604895, 'weight_class_1': 9.529929996494463, 'weight_class_2': 8.10823484088999}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  85%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                    | 1696/2000 [00:36<00:08, 36.82it/s]

[I 2026-07-08 13:33:12,386] Trial 1692 finished with value: 0.9464165734654871 and parameters: {'weight_class_0': 1.3789779457546587, 'weight_class_1': 9.453488446791269, 'weight_class_2': 6.385088822337817}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:12,458] Trial 1694 finished with value: 0.949105150051679 and parameters: {'weight_class_0': 0.5021254053864899, 'weight_class_1': 9.457335661810895, 'weight_class_2': 7.075768256392038}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:12,461] Trial 1693 finished with value: 0.9489919247727102 and parameters: {'weight_class_0': 0.5152639171932933, 'weight_class_1': 9.997568119372465, 'weight_class_2': 8.145312593151804}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:12,506] Trial 1695 finished with value: 0.9480133123694926 and parameters: {'weight_class_0': 0.5244138111355074, 'weight_class_1': 3.5014594845646716, 'weight_class_2': 8.140292578763958}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:12,549] Trial 1698 finished with value: 0.9489245651443036 and parameters: {'weight_class_0': 0.4971152644438202, 'weight_class_1': 9.09231264879081, 'weight_class_2': 8.076664012810175}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  85%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 1699/2000 [00:36<00:08, 36.79it/s]

[I 2026-07-08 13:33:12,551] Trial 1696 finished with value: 0.9491393756662557 and parameters: {'weight_class_0': 0.5182507606008497, 'weight_class_1': 9.044603448428001, 'weight_class_2': 6.396581442540282}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:12,570] Trial 1697 finished with value: 0.9488920346678001 and parameters: {'weight_class_0': 0.4785644046286957, 'weight_class_1': 9.078272963855317, 'weight_class_2': 8.051385042163025}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:12,605] Trial 1700 finished with value: 0.9490078899886439 and parameters: {'weight_class_0': 0.48554678222396747, 'weight_class_1': 9.167965792291715, 'weight_class_2': 7.709280698631884}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:33:12,607] Trial 1699 finished with value: 0.9490013247503031 and parameters: {'weight_class_0': 0.4626057205385684, 'weight_class_1': 9.103713253015492, 'weight_class_2': 7.04148969680981}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:12,677] Trial 1701 finished with value: 0.9483890010227234 and parameters: {'weight_class_0': 0.4832737860753629, 'weight_class_1': 3.4738977835668585, 'weight_class_2': 7.01164480527035}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:12,680] Trial 1702 finished with value: 0.9490017918320429 and parameters: {'weight_class_0': 0.46894923839615027, 'weight_class_1': 9.781414359026833, 'weight_class_2': 7.083015501065645}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:12,704] Trial 1703 finished with value: 0.9490767917101189 and parameters: {'weight_class_0': 0.4987038205443549, 'weight_class_1': 9.044318256875451, 'weight_class_2': 7.082685476320506}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:12,716] Trial 1704 finished with value: 0.9490064272066198 and parameters: {'weight_class_0': 0.486171995006795, 'weight_class_1': 9.095406301050785, 'weight_class_2': 7.752473369672564}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  85%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                   | 1706/2000 [00:37<00:08, 36.50it/s]

[I 2026-07-08 13:33:12,765] Trial 1705 finished with value: 0.9490279865170321 and parameters: {'weight_class_0': 0.7850060046030694, 'weight_class_1': 9.054632450699684, 'weight_class_2': 7.745826274279554}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:12,798] Trial 1707 finished with value: 0.8596265275314519 and parameters: {'weight_class_0': 0.7656757345928545, 'weight_class_1': 0.04356078044962697, 'weight_class_2': 7.719985337121412}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                   | 1712/2000 [00:37<00:08, 35.07it/s]

[I 2026-07-08 13:33:12,799] Trial 1706 finished with value: 0.9489291761830131 and parameters: {'weight_class_0': 0.8412874424359906, 'weight_class_1': 9.149726961889291, 'weight_class_2': 7.762268782179131}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:12,856] Trial 1708 finished with value: 0.9490559359493617 and parameters: {'weight_class_0': 0.7817172794137406, 'weight_class_1': 9.844394220346743, 'weight_class_2': 7.734801792211444}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:12,912] Trial 1711 finished with value: 0.9490762338523222 and parameters: {'weight_class_0': 0.7872242625092509, 'weight_class_1': 9.815523337028996, 'weight_class_2': 7.823542839459713}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:12,918] Trial 1710 finished with value: 0.9490525789138223 and parameters: {'weight_class_0': 0.77527775741431, 'weight_class_1': 9.790976844756546, 'weight_class_2': 7.7584219798162435}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:12,919] Trial 1709 finished with value: 0.9490663662172353 and parameters: {'weight_class_0': 0.7858410510880229, 'weight_class_1': 9.67513013405885, 'weight_class_2': 7.73802905860531}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:12,943] Trial 1712 finished with value: 0.9490614874458146 and parameters: {'weight_class_0': 0.7816741795444381, 'weight_class_1': 9.693973402877333, 'weight_class_2': 7.74326726583187}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  86%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████                   | 1714/2000 [00:37<00:08, 35.07it/s]

[I 2026-07-08 13:33:12,985] Trial 1713 finished with value: 0.9492185870983185 and parameters: {'weight_class_0': 0.7739531890002932, 'weight_class_1': 9.993672558176408, 'weight_class_2': 8.41032172991564}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:12,998] Trial 1714 finished with value: 0.9491414574263773 and parameters: {'weight_class_0': 0.8050167230995383, 'weight_class_1': 9.822515302766432, 'weight_class_2': 8.394034582912981}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  86%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                  | 1719/2000 [00:37<00:08, 34.37it/s]

[I 2026-07-08 13:33:13,029] Trial 1715 finished with value: 0.9490675774167864 and parameters: {'weight_class_0': 0.8195383187210833, 'weight_class_1': 9.651219278813244, 'weight_class_2': 7.803133408000144}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:13,049] Trial 1716 finished with value: 0.9491827197378697 and parameters: {'weight_class_0': 0.7735007019772592, 'weight_class_1': 9.65710248117357, 'weight_class_2': 8.384438454797188}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:13,090] Trial 1717 finished with value: 0.9491996858866081 and parameters: {'weight_class_0': 0.7666101564415712, 'weight_class_1': 9.826412831700738, 'weight_class_2': 8.388377464077056}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:13,128] Trial 1718 finished with value: 0.9491708129614325 and parameters: {'weight_class_0': 0.7811659881961281, 'weight_class_1': 9.831200816663374, 'weight_class_2': 8.388327163449965}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:13,149] Trial 1719 finished with value: 0.9491763268404427 and parameters: {'weight_class_0': 0.7798035522770231, 'weight_class_1': 9.833832807584663, 'weight_class_2': 8.724604382938308}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:33:13,190] Trial 1720 finished with value: 0.9491591989470866 and parameters: {'weight_class_0': 0.7463824871338984, 'weight_class_1': 9.62996554737564, 'weight_class_2': 8.732901026288637}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:13,244] Trial 1721 finished with value: 0.9487068676699346 and parameters: {'weight_class_0': 1.0493757972117723, 'weight_class_1': 9.633015336324569, 'weight_class_2': 8.43972153828824}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  86%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                  | 1727/2000 [00:37<00:07, 35.46it/s]

[I 2026-07-08 13:33:13,281] Trial 1722 finished with value: 0.9488142730749658 and parameters: {'weight_class_0': 1.0204752155076389, 'weight_class_1': 9.609036814543126, 'weight_class_2': 8.678669585260879}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:13,282] Trial 1723 finished with value: 0.9352129997748686 and parameters: {'weight_class_0': 1.0505123885336207, 'weight_class_1': 2.1281574546717517, 'weight_class_2': 8.698325689028472}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:13,287] Trial 1724 finished with value: 0.9483952527065265 and parameters: {'weight_class_0': 1.0513432855767337, 'weight_class_1': 9.652268218539913, 'weight_class_2': 7.272292290165921}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:13,305] Trial 1725 finished with value: 0.948503888504221 and parameters: {'weight_class_0': 1.1323850362024905, 'weight_class_1': 9.56562856360821, 'weight_class_2': 8.733189700354425}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:13,356] Trial 1726 finished with value: 0.9486262676038567 and parameters: {'weight_class_0': 1.0655889181936204, 'weight_class_1': 8.409004099718695, 'weight_class_2': 8.712876800120052}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:13,395] Trial 1727 finished with value: 0.9475197151507134 and parameters: {'weight_class_0': 1.0458506360898212, 'weight_class_1': 9.989269036771676, 'weight_class_2': 5.374810129048415}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████                  | 1729/2000 [00:37<00:07, 35.46it/s]

[I 2026-07-08 13:33:13,412] Trial 1728 finished with value: 0.948801648551772 and parameters: {'weight_class_0': 1.066286521859545, 'weight_class_1': 9.992708227857891, 'weight_class_2': 8.71463748552424}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:13,421] Trial 1729 finished with value: 0.9475058208109607 and parameters: {'weight_class_0': 1.0267303060927166, 'weight_class_1': 8.391156309709269, 'weight_class_2': 5.440618642227342}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                 | 1735/2000 [00:37<00:07, 36.27it/s]

[I 2026-07-08 13:33:13,496] Trial 1731 finished with value: 0.9484269422550137 and parameters: {'weight_class_0': 1.0139066889514659, 'weight_class_1': 8.613810507851229, 'weight_class_2': 7.373830591606271}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:13,504] Trial 1730 finished with value: 0.9484058074717364 and parameters: {'weight_class_0': 1.021093239748002, 'weight_class_1': 8.640757886501865, 'weight_class_2': 7.412177954290693}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:13,520] Trial 1732 finished with value: 0.9482546878625261 and parameters: {'weight_class_0': 1.0548949941141608, 'weight_class_1': 8.480137647239355, 'weight_class_2': 7.3248147702843855}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:13,540] Trial 1733 finished with value: 0.9491470369439498 and parameters: {'weight_class_0': 0.5952221068144974, 'weight_class_1': 8.608849317441871, 'weight_class_2': 7.999685474617148}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:13,584] Trial 1734 finished with value: 0.7462864568391318 and parameters: {'weight_class_0': 0.020610497037360398, 'weight_class_1': 8.413949330130228, 'weight_class_2': 7.345600192553187}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:13,612] Trial 1735 finished with value: 0.9491615572882064 and parameters: {'weight_class_0': 0.586538730728378, 'weight_class_1': 9.993225647120603, 'weight_class_2': 7.386411961474729}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:33:13,621] Trial 1736 finished with value: 0.65994940821422 and parameters: {'weight_class_0': 0.006629746795175584, 'weight_class_1': 9.320793312005241, 'weight_class_2': 6.669229760677552}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:13,649] Trial 1737 finished with value: 0.9440343749181798 and parameters: {'weight_class_0': 1.824154303592416, 'weight_class_1': 8.616734326745291, 'weight_class_2': 7.330177891499533}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  87%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████                 | 1743/2000 [00:38<00:07, 35.90it/s]

[I 2026-07-08 13:33:13,698] Trial 1739 finished with value: 0.9491434981560211 and parameters: {'weight_class_0': 0.5883271550879415, 'weight_class_1': 9.319545423761335, 'weight_class_2': 7.361727150444427}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:13,720] Trial 1738 finished with value: 0.9491290786286429 and parameters: {'weight_class_0': 0.5532337779358587, 'weight_class_1': 9.348482302348476, 'weight_class_2': 7.403901253415035}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:13,747] Trial 1740 finished with value: 0.9491673631556741 and parameters: {'weight_class_0': 0.5932236709989167, 'weight_class_1': 8.705003730128034, 'weight_class_2': 7.344247098963838}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:13,764] Trial 1741 finished with value: 0.9465056997612363 and parameters: {'weight_class_0': 0.6089780439029582, 'weight_class_1': 2.658814153955904, 'weight_class_2': 7.99776379720208}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:13,782] Trial 1742 finished with value: 0.75018259701454 and parameters: {'weight_class_0': 0.021599351540074863, 'weight_class_1': 9.335863539538595, 'weight_class_2': 6.6810595929181105}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:13,815] Trial 1743 finished with value: 0.9481949883424815 and parameters: {'weight_class_0': 0.30952993855767635, 'weight_class_1': 9.292162295124161, 'weight_class_2': 6.714017749588487}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  87%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                | 1745/2000 [00:38<00:07, 35.90it/s]

[I 2026-07-08 13:33:13,875] Trial 1744 finished with value: 0.9485248239563538 and parameters: {'weight_class_0': 0.3585091369647417, 'weight_class_1': 9.99902759495635, 'weight_class_2': 6.720846083143688}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:13,914] Trial 1745 finished with value: 0.9476597686296419 and parameters: {'weight_class_0': 0.2684165102983192, 'weight_class_1': 9.357690781053982, 'weight_class_2': 6.749800913282492}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                | 1751/2000 [00:38<00:06, 35.59it/s]

[I 2026-07-08 13:33:13,920] Trial 1746 finished with value: 0.948311078561297 and parameters: {'weight_class_0': 0.3552544580866513, 'weight_class_1': 9.32166745244914, 'weight_class_2': 8.001929795960228}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:13,957] Trial 1747 finished with value: 0.9481821080863183 and parameters: {'weight_class_0': 0.3369994294841299, 'weight_class_1': 9.367216561693532, 'weight_class_2': 7.966900312816141}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:13,969] Trial 1748 finished with value: 0.9480768350581005 and parameters: {'weight_class_0': 0.32721516803205497, 'weight_class_1': 9.335698315301306, 'weight_class_2': 7.994767351102605}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:13,979] Trial 1749 finished with value: 0.9485128958719616 and parameters: {'weight_class_0': 0.3838802053501687, 'weight_class_1': 9.426624370815468, 'weight_class_2': 7.98303750131018}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:14,021] Trial 1751 finished with value: 0.9483510694317641 and parameters: {'weight_class_0': 0.362260152364841, 'weight_class_1': 9.51921132937907, 'weight_class_2': 7.991827521944598}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:14,048] Trial 1750 finished with value: 0.947813833037038 and parameters: {'weight_class_0': 0.2970464435178329, 'weight_class_1': 9.455194457777726, 'weight_class_2': 7.957343737953352}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                | 1753/2000 [00:38<00:06, 35.59it/s]

[I 2026-07-08 13:33:14,078] Trial 1752 finished with value: 0.9480691116629946 and parameters: {'weight_class_0': 0.33801005336717915, 'weight_class_1': 9.994038009965589, 'weight_class_2': 7.978102667232634}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:14,101] Trial 1753 finished with value: 0.9485866716386068 and parameters: {'weight_class_0': 0.4026891493404709, 'weight_class_1': 9.840807108742052, 'weight_class_2': 7.973568531435956}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                | 1758/2000 [00:38<00:07, 34.48it/s]

[I 2026-07-08 13:33:14,184] Trial 1754 finished with value: 0.948101963210353 and parameters: {'weight_class_0': 0.33651314487209644, 'weight_class_1': 9.821974285884016, 'weight_class_2': 7.948392037868041}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:14,187] Trial 1755 finished with value: 0.9482923683821954 and parameters: {'weight_class_0': 0.35410362698703407, 'weight_class_1': 9.810411813259165, 'weight_class_2': 7.931358726335544}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:14,198] Trial 1756 finished with value: 0.9485833449807962 and parameters: {'weight_class_0': 0.40040552070255386, 'weight_class_1': 9.586896767282383, 'weight_class_2': 8.07038535346134}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:14,211] Trial 1757 finished with value: 0.9491508132253648 and parameters: {'weight_class_0': 0.7093763578404904, 'weight_class_1': 7.931809709422608, 'weight_class_2': 8.001763190977835}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:14,235] Trial 1758 finished with value: 0.948904704857492 and parameters: {'weight_class_0': 0.8741183329834108, 'weight_class_1': 9.818888775022367, 'weight_class_2': 7.62068278735232}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏               | 1761/2000 [00:38<00:06, 34.65it/s]

[I 2026-07-08 13:33:14,285] Trial 1759 finished with value: 0.9492036244111967 and parameters: {'weight_class_0': 0.6790988846261657, 'weight_class_1': 9.616109156974144, 'weight_class_2': 7.574301611046336}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:14,316] Trial 1760 finished with value: 0.9491985148179628 and parameters: {'weight_class_0': 0.6875939637733259, 'weight_class_1': 9.807114148440283, 'weight_class_2': 7.621234954657344}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:14,349] Trial 1761 finished with value: 0.9492001163711578 and parameters: {'weight_class_0': 0.6787696135877116, 'weight_class_1': 9.819162540741033, 'weight_class_2': 7.629890470519379}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:33:14,364] Trial 1763 finished with value: 0.9491477740686661 and parameters: {'weight_class_0': 0.6810615344928513, 'weight_class_1': 7.937075226568856, 'weight_class_2': 7.630317214615774}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:14,367] Trial 1762 finished with value: 0.949004006665571 and parameters: {'weight_class_0': 0.7430920922314622, 'weight_class_1': 7.953140393205331, 'weight_class_2': 7.553896955067331}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:14,406] Trial 1764 finished with value: 0.9492049909303111 and parameters: {'weight_class_0': 0.6985934437103279, 'weight_class_1': 9.62946198104473, 'weight_class_2': 7.625575282856605}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:14,437] Trial 1765 finished with value: 0.949135592941902 and parameters: {'weight_class_0': 0.6851494135602285, 'weight_class_1': 7.9256656877483405, 'weight_class_2': 7.612485530759038}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:14,498] Trial 1767 finished with value: 0.9488985048970712 and parameters: {'weight_class_0': 0.8781752361532833, 'weight_class_1': 9.99731222093944, 'weight_class_2': 7.63794700445423}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊               | 1769/2000 [00:38<00:06, 36.28it/s]

[I 2026-07-08 13:33:14,516] Trial 1766 finished with value: 0.9488862125550117 and parameters: {'weight_class_0': 0.8783873147287432, 'weight_class_1': 9.604976659441554, 'weight_class_2': 7.632944430147643}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:14,526] Trial 1768 finished with value: 0.9492008396255126 and parameters: {'weight_class_0': 0.696518364608063, 'weight_class_1': 8.916011928772631, 'weight_class_2': 7.564481292873325}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:14,544] Trial 1769 finished with value: 0.9487487563276328 and parameters: {'weight_class_0': 0.8779184711753258, 'weight_class_1': 8.950961017321601, 'weight_class_2': 7.003873076964612}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:33:14,624] Trial 1770 finished with value: 0.9489120998392324 and parameters: {'weight_class_0': 0.9033884990325799, 'weight_class_1': 9.649193500736843, 'weight_class_2': 8.232308498947031}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:14,660] Trial 1771 finished with value: 0.9486929166557356 and parameters: {'weight_class_0': 0.894020803011251, 'weight_class_1': 8.996414857674285, 'weight_class_2': 7.066281240469064}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:14,674] Trial 1772 finished with value: 0.9485506631730535 and parameters: {'weight_class_0': 0.9489582341675538, 'weight_class_1': 8.972752856350935, 'weight_class_2': 6.987853048208889}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:14,681] Trial 1773 finished with value: 0.948643312657305 and parameters: {'weight_class_0': 0.9146667521266519, 'weight_class_1': 9.60103639533925, 'weight_class_2': 7.090574214600863}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 1774/2000 [00:39<00:06, 34.41it/s]

[I 2026-07-08 13:33:14,733] Trial 1775 finished with value: 0.9489094522287118 and parameters: {'weight_class_0': 0.9323247447154355, 'weight_class_1': 8.860196180687304, 'weight_class_2': 8.304361809173049}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎              | 1777/2000 [00:39<00:06, 34.70it/s]

[I 2026-07-08 13:33:14,743] Trial 1776 finished with value: 0.9489874075678938 and parameters: {'weight_class_0': 0.9047549981801922, 'weight_class_1': 9.999568026334222, 'weight_class_2': 8.35973255790987}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:14,749] Trial 1774 finished with value: 0.9488747316063589 and parameters: {'weight_class_0': 0.909223449139344, 'weight_class_1': 9.667484972858563, 'weight_class_2': 8.222296240738277}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:14,763] Trial 1777 finished with value: 0.9489101006926797 and parameters: {'weight_class_0': 0.932771095483818, 'weight_class_1': 8.930533535351843, 'weight_class_2': 8.317307778928745}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌              | 1781/2000 [00:39<00:06, 35.75it/s]

[I 2026-07-08 13:33:14,822] Trial 1778 finished with value: 0.9482134012899696 and parameters: {'weight_class_0': 1.2355676085786245, 'weight_class_1': 9.99739816049511, 'weight_class_2': 8.214500398483871}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:14,858] Trial 1779 finished with value: 0.9474909142794495 and parameters: {'weight_class_0': 1.2695713098486592, 'weight_class_1': 8.17914689538739, 'weight_class_2': 8.220079898263702}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:14,883] Trial 1780 finished with value: 0.9488748236570013 and parameters: {'weight_class_0': 0.9223464167419022, 'weight_class_1': 9.635353101294186, 'weight_class_2': 8.303308606647425}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:14,924] Trial 1781 finished with value: 0.9461776502112288 and parameters: {'weight_class_0': 1.2731069112806028, 'weight_class_1': 8.149103921769905, 'weight_class_2': 5.867916224641346}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌              | 1782/2000 [00:39<00:06, 35.75it/s]

[I 2026-07-08 13:33:14,954] Trial 1782 finished with value: 0.9478405371783153 and parameters: {'weight_class_0': 1.1966624673262873, 'weight_class_1': 8.172823287436994, 'weight_class_2': 8.423280299683125}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊              | 1785/2000 [00:39<00:06, 35.19it/s]

[I 2026-07-08 13:33:14,966] Trial 1783 finished with value: 0.9249806360581263 and parameters: {'weight_class_0': 3.756080548688173, 'weight_class_1': 8.16362169746909, 'weight_class_2': 8.305520654584386}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:14,987] Trial 1784 finished with value: 0.948007069506577 and parameters: {'weight_class_0': 1.2835694168705607, 'weight_class_1': 9.838464327622868, 'weight_class_2': 8.219025953462696}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:15,044] Trial 1785 finished with value: 0.9490940208599999 and parameters: {'weight_class_0': 0.5756829375689787, 'weight_class_1': 9.996647492862806, 'weight_class_2': 8.20032267785991}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████              | 1789/2000 [00:39<00:06, 34.61it/s]

[I 2026-07-08 13:33:15,074] Trial 1786 finished with value: 0.9489236239467037 and parameters: {'weight_class_0': 0.5410012022616734, 'weight_class_1': 8.191193635758378, 'weight_class_2': 8.989557449558285}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:15,080] Trial 1787 finished with value: 0.947644021891621 and parameters: {'weight_class_0': 1.2605047626915553, 'weight_class_1': 8.157613657161383, 'weight_class_2': 8.450760041679944}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:15,106] Trial 1788 finished with value: 0.949094058032944 and parameters: {'weight_class_0': 0.5395402238843982, 'weight_class_1': 8.240987615377742, 'weight_class_2': 7.82539096789238}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:15,124] Trial 1789 finished with value: 0.9489377984450577 and parameters: {'weight_class_0': 0.5112468792918464, 'weight_class_1': 9.817567089370705, 'weight_class_2': 8.465591295649459}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  90%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎             | 1793/2000 [00:39<00:05, 35.17it/s]

[I 2026-07-08 13:33:15,178] Trial 1791 finished with value: 0.9118244994879076 and parameters: {'weight_class_0': 0.5393515938121382, 'weight_class_1': 0.46525676269979765, 'weight_class_2': 8.986103030543303}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:15,220] Trial 1790 finished with value: 0.9490966860058542 and parameters: {'weight_class_0': 0.5561171503609498, 'weight_class_1': 9.166995802799816, 'weight_class_2': 7.805873657341318}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:15,221] Trial 1792 finished with value: 0.9490895110030119 and parameters: {'weight_class_0': 0.5370389132351109, 'weight_class_1': 9.999200791084402, 'weight_class_2': 7.844851832270668}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:15,242] Trial 1793 finished with value: 0.9490858390132818 and parameters: {'weight_class_0': 0.5470264458677659, 'weight_class_1': 9.812378465460265, 'weight_class_2': 7.8269416563904315}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:33:15,291] Trial 1794 finished with value: 0.9293515951025194 and parameters: {'weight_class_0': 0.5259271366158481, 'weight_class_1': 0.8524317094436125, 'weight_class_2': 7.846477125571206}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:15,293] Trial 1795 finished with value: 0.9491503116820237 and parameters: {'weight_class_0': 0.5620375813511743, 'weight_class_1': 9.191260102331904, 'weight_class_2': 7.2747079321272885}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:15,304] Trial 1796 finished with value: 0.9490886041280436 and parameters: {'weight_class_0': 0.5713852728617306, 'weight_class_1': 9.179671846627567, 'weight_class_2': 7.816461434431892}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:33:15,343] Trial 1797 finished with value: 0.8780887282268571 and parameters: {'weight_class_0': 8.312169737997756, 'weight_class_1': 9.811844765028471, 'weight_class_2': 7.2351368093675585}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:15,391] Trial 1798 finished with value: 0.949065047965917 and parameters: {'weight_class_0': 0.5059765571628002, 'weight_class_1': 9.242868940670116, 'weight_class_2': 7.271729248112642}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:15,433] Trial 1799 finished with value: 0.9490724408786922 and parameters: {'weight_class_0': 0.5216544889531383, 'weight_class_1': 9.199291776677654, 'weight_class_2': 7.289999675153153}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:15,448] Trial 1800 finished with value: 0.9491537381031486 and parameters: {'weight_class_0': 0.5610610352662275, 'weight_class_1': 9.198209715276844, 'weight_class_2': 7.232592172301521}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:33:15,482] Trial 1801 finished with value: 0.9491703562009107 and parameters: {'weight_class_0': 0.5698334974307872, 'weight_class_1': 9.18536692023851, 'weight_class_2': 7.297496223446558}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:15,542] Trial 1802 finished with value: 0.8850002285130056 and parameters: {'weight_class_0': 7.278587509470144, 'weight_class_1': 9.444114031067608, 'weight_class_2': 7.246956095327967}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:15,547] Trial 1804 finished with value: 0.9491432693824272 and parameters: {'weight_class_0': 0.7011284636802674, 'weight_class_1': 9.452640165670719, 'weight_class_2': 7.1371250670653055}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:15,571] Trial 1803 finished with value: 0.9449343708978656 and parameters: {'weight_class_0': 0.16102827953107957, 'weight_class_1': 9.490641023250054, 'weight_class_2': 7.225561770337029}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎            | 1808/2000 [00:40<00:05, 34.94it/s]

[I 2026-07-08 13:33:15,593] Trial 1805 finished with value: 0.9466457964479117 and parameters: {'weight_class_0': 0.18657754105535462, 'weight_class_1': 9.554319546673067, 'weight_class_2': 4.354032155217121}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:15,622] Trial 1807 finished with value: 0.9490625430174124 and parameters: {'weight_class_0': 0.7429029236785827, 'weight_class_1': 9.451473611714015, 'weight_class_2': 7.3951734618793035}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:15,634] Trial 1806 finished with value: 0.8867557139538839 and parameters: {'weight_class_0': 7.2380818192250285, 'weight_class_1': 9.65258140713514, 'weight_class_2': 7.435297593360125}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:15,681] Trial 1808 finished with value: 0.8854883659237164 and parameters: {'weight_class_0': 6.705934300134341, 'weight_class_1': 9.454980621524847, 'weight_class_2': 6.283577475503511}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  91%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌            | 1811/2000 [00:40<00:05, 34.18it/s]

[I 2026-07-08 13:33:15,729] Trial 1809 finished with value: 0.9417530203436174 and parameters: {'weight_class_0': 0.11186427987866743, 'weight_class_1': 9.577921500300961, 'weight_class_2': 3.9421103093447374}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:15,761] Trial 1811 finished with value: 0.9489490254903356 and parameters: {'weight_class_0': 0.8209714098865921, 'weight_class_1': 9.52579911282751, 'weight_class_2': 7.462235855146804}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:15,775] Trial 1810 finished with value: 0.9465603110541027 and parameters: {'weight_class_0': 0.17774291639188322, 'weight_class_1': 9.528265254220942, 'weight_class_2': 3.974461182701898}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  91%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉            | 1817/2000 [00:40<00:05, 35.08it/s]

[I 2026-07-08 13:33:15,811] Trial 1812 finished with value: 0.9491305290204842 and parameters: {'weight_class_0': 0.725041869150939, 'weight_class_1': 9.496647649705183, 'weight_class_2': 7.491358564553377}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:15,847] Trial 1813 finished with value: 0.9245776428653086 and parameters: {'weight_class_0': 4.069555689868229, 'weight_class_1': 9.99869219514729, 'weight_class_2': 8.086410717290045}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:15,893] Trial 1814 finished with value: 0.9491831445169416 and parameters: {'weight_class_0': 0.7721173876188697, 'weight_class_1': 9.99749538006972, 'weight_class_2': 8.102950380283502}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:15,909] Trial 1815 finished with value: 0.9489895914658231 and parameters: {'weight_class_0': 0.7560043212231, 'weight_class_1': 9.712976512919242, 'weight_class_2': 6.5075851328798775}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:15,916] Trial 1816 finished with value: 0.9489335948783553 and parameters: {'weight_class_0': 0.7588408435993101, 'weight_class_1': 9.67669571422032, 'weight_class_2': 6.26135519967153}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:15,951] Trial 1817 finished with value: 0.94852694394538 and parameters: {'weight_class_0': 1.0962912779714975, 'weight_class_1': 9.828762675221357, 'weight_class_2': 8.098139997401185}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  91%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████            | 1819/2000 [00:40<00:05, 35.08it/s]

[I 2026-07-08 13:33:16,001] Trial 1819 finished with value: 0.9491526611000535 and parameters: {'weight_class_0': 0.7684668717523302, 'weight_class_1': 9.704956969436335, 'weight_class_2': 8.075066209824286}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:16,007] Trial 1818 finished with value: 0.9490954022774426 and parameters: {'weight_class_0': 0.806018943511275, 'weight_class_1': 9.804304283775089, 'weight_class_2': 8.127780294111737}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  91%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍           | 1824/2000 [00:40<00:05, 33.00it/s]

[I 2026-07-08 13:33:16,021] Trial 1820 finished with value: 0.9487902436526637 and parameters: {'weight_class_0': 1.006312166762778, 'weight_class_1': 9.747744386344506, 'weight_class_2': 8.086707939792802}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:16,058] Trial 1821 finished with value: 0.8781426335461721 and parameters: {'weight_class_0': 4.16105091820143, 'weight_class_1': 1.312835458956621, 'weight_class_2': 8.085709676643328}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:16,142] Trial 1824 finished with value: 0.9484346832187652 and parameters: {'weight_class_0': 1.1239691191350256, 'weight_class_1': 9.814901915454426, 'weight_class_2': 8.0717098116194}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:16,149] Trial 1822 finished with value: 0.9462132285030177 and parameters: {'weight_class_0': 1.6445199968357547, 'weight_class_1': 9.809093675150738, 'weight_class_2': 8.121083557075831}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:16,171] Trial 1823 finished with value: 0.9468157305090931 and parameters: {'weight_class_0': 1.0410393525685742, 'weight_class_1': 9.817249575961535, 'weight_class_2': 4.719086709920838}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  91%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌           | 1826/2000 [00:40<00:05, 33.00it/s]

[I 2026-07-08 13:33:16,205] Trial 1825 finished with value: 0.9478797389551242 and parameters: {'weight_class_0': 1.182785579886255, 'weight_class_1': 9.795166140838733, 'weight_class_2': 6.952043174504567}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:16,236] Trial 1826 finished with value: 0.9483212453318681 and parameters: {'weight_class_0': 1.143432199603591, 'weight_class_1': 8.735252591706383, 'weight_class_2': 8.52909917609776}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊           | 1831/2000 [00:40<00:04, 35.23it/s]

[I 2026-07-08 13:33:16,251] Trial 1827 finished with value: 0.9480554254409025 and parameters: {'weight_class_0': 1.089273463563646, 'weight_class_1': 8.713291472468399, 'weight_class_2': 6.956469717073436}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:16,292] Trial 1829 finished with value: 0.9483159660139805 and parameters: {'weight_class_0': 1.085979937526303, 'weight_class_1': 8.745496140345944, 'weight_class_2': 7.761007529030164}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:16,297] Trial 1828 finished with value: 0.9484631782909902 and parameters: {'weight_class_0': 1.0508440060926119, 'weight_class_1': 8.699719735274662, 'weight_class_2': 7.8154391646962305}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:16,299] Trial 1830 finished with value: 0.9486202139960221 and parameters: {'weight_class_0': 1.085262227858452, 'weight_class_1': 9.826072811388244, 'weight_class_2': 8.513071536400258}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:16,346] Trial 1832 finished with value: 0.9480244467363074 and parameters: {'weight_class_0': 1.1766790421591211, 'weight_class_1': 8.798801303503947, 'weight_class_2': 7.829829987733082}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:33:16,370] Trial 1831 finished with value: 0.9483663803855649 and parameters: {'weight_class_0': 1.1273778533360819, 'weight_class_1': 8.669582370099674, 'weight_class_2': 8.553467579479836}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:16,386] Trial 1833 finished with value: 0.9480244203034814 and parameters: {'weight_class_0': 1.0913069558594666, 'weight_class_1': 8.440789526325117, 'weight_class_2': 6.947919605441992}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎          | 1839/2000 [00:40<00:04, 34.27it/s]

[I 2026-07-08 13:33:16,461] Trial 1834 finished with value: 0.9484942724081858 and parameters: {'weight_class_0': 0.3663024149328118, 'weight_class_1': 8.690273923712605, 'weight_class_2': 7.7435957009816265}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:16,509] Trial 1837 finished with value: 0.9485266760384573 and parameters: {'weight_class_0': 0.36661676999890386, 'weight_class_1': 8.478738286760287, 'weight_class_2': 7.738401595956898}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:16,524] Trial 1835 finished with value: 0.9480515140716387 and parameters: {'weight_class_0': 0.323451668391819, 'weight_class_1': 8.794831019070857, 'weight_class_2': 8.539723986468426}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:16,526] Trial 1836 finished with value: 0.9480552694818835 and parameters: {'weight_class_0': 0.32745860748280553, 'weight_class_1': 8.759363895708358, 'weight_class_2': 8.556156483292787}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:16,541] Trial 1838 finished with value: 0.9487895331716847 and parameters: {'weight_class_0': 0.41119083325082556, 'weight_class_1': 8.452240781207967, 'weight_class_2': 7.763632158842114}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:16,587] Trial 1839 finished with value: 0.9484744146068439 and parameters: {'weight_class_0': 0.3617688410369109, 'weight_class_1': 8.9720053479632, 'weight_class_2': 7.639571547971548}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌          | 1841/2000 [00:40<00:04, 35.36it/s]

[I 2026-07-08 13:33:16,600] Trial 1841 finished with value: 0.9486553236409804 and parameters: {'weight_class_0': 0.3834996331363121, 'weight_class_1': 8.434522830334688, 'weight_class_2': 7.635974212030617}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:16,659] Trial 1840 finished with value: 0.9486501402443007 and parameters: {'weight_class_0': 0.3840192598941442, 'weight_class_1': 8.401767554986355, 'weight_class_2': 7.593123358136623}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊          | 1846/2000 [00:41<00:04, 34.99it/s]

[I 2026-07-08 13:33:16,672] Trial 1842 finished with value: 0.9479967595677206 and parameters: {'weight_class_0': 0.30296859939461857, 'weight_class_1': 9.008690597912956, 'weight_class_2': 7.560356716661474}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:16,682] Trial 1843 finished with value: 0.9484764426379146 and parameters: {'weight_class_0': 0.37044881559714526, 'weight_class_1': 9.609890332229591, 'weight_class_2': 7.535997270587005}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:16,759] Trial 1844 finished with value: 0.9485819752696673 and parameters: {'weight_class_0': 0.38958915147091383, 'weight_class_1': 9.63976797864979, 'weight_class_2': 7.5578267754480155}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:16,769] Trial 1845 finished with value: 0.9465408177444807 and parameters: {'weight_class_0': 0.20265874045703458, 'weight_class_1': 8.980287218367447, 'weight_class_2': 7.562833309184011}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:16,801] Trial 1846 finished with value: 0.9492284045124729 and parameters: {'weight_class_0': 0.6998888146455453, 'weight_class_1': 9.643534099403748, 'weight_class_2': 7.601051980977995}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉          | 1848/2000 [00:41<00:04, 34.99it/s]

[I 2026-07-08 13:33:16,832] Trial 1847 finished with value: 0.9492212921694856 and parameters: {'weight_class_0': 0.6954354539116522, 'weight_class_1': 9.61275183732777, 'weight_class_2': 7.547470660448784}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:16,872] Trial 1848 finished with value: 0.9492153302705918 and parameters: {'weight_class_0': 0.7135975034266588, 'weight_class_1': 9.996021520437873, 'weight_class_2': 7.535983060838189}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎         | 1854/2000 [00:41<00:04, 33.60it/s]

[I 2026-07-08 13:33:16,894] Trial 1849 finished with value: 0.9490458269579366 and parameters: {'weight_class_0': 0.7606051856117548, 'weight_class_1': 9.66942098448316, 'weight_class_2': 7.46395958426463}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:16,937] Trial 1851 finished with value: 0.9491821609471892 and parameters: {'weight_class_0': 0.7058511193565374, 'weight_class_1': 9.564490798240426, 'weight_class_2': 7.459937889242957}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:16,941] Trial 1850 finished with value: 0.9492122222012654 and parameters: {'weight_class_0': 0.6857911004922602, 'weight_class_1': 9.64484629569163, 'weight_class_2': 7.525194058635132}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:16,973] Trial 1852 finished with value: 0.9492341945434107 and parameters: {'weight_class_0': 0.7094290638023372, 'weight_class_1': 9.365265740809496, 'weight_class_2': 7.922642735520555}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:16,976] Trial 1853 finished with value: 0.9492107306375196 and parameters: {'weight_class_0': 0.6990317649431541, 'weight_class_1': 9.989782795856483, 'weight_class_2': 7.861171599277193}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:17,025] Trial 1854 finished with value: 0.9490077671153087 and parameters: {'weight_class_0': 0.7139985035999697, 'weight_class_1': 9.371364493816873, 'weight_class_2': 5.9707653695990075}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:33:17,071] Trial 1855 finished with value: 0.9492259614555073 and parameters: {'weight_class_0': 0.7015552202386973, 'weight_class_1': 9.665413698454207, 'weight_class_2': 7.878938389284939}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:33:17,097] Trial 1856 finished with value: 0.9489067716575144 and parameters: {'weight_class_0': 0.893505350432178, 'weight_class_1': 9.309148560620239, 'weight_class_2': 7.872411924857309}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:17,112] Trial 1857 finished with value: 0.9157853256667584 and parameters: {'weight_class_0': 4.548984117612878, 'weight_class_1': 9.449903488166639, 'weight_class_2': 7.7699605163698395}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:17,144] Trial 1858 finished with value: 0.9303065892419781 and parameters: {'weight_class_0': 0.9117824304322264, 'weight_class_1': 9.625570544186811, 'weight_class_2': 1.625673603997535}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:17,163] Trial 1859 finished with value: 0.9489325255058808 and parameters: {'weight_class_0': 0.8773264061370201, 'weight_class_1': 9.661766699639674, 'weight_class_2': 7.913504663319168}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:17,225] Trial 1860 finished with value: 0.9459753380052893 and parameters: {'weight_class_0': 0.9165859280416587, 'weight_class_1': 9.824489964237438, 'weight_class_2': 3.618954205495877}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:17,243] Trial 1862 finished with value: 0.9489115131509749 and parameters: {'weight_class_0': 0.889915551450483, 'weight_class_1': 9.464728515239745, 'weight_class_2': 7.91339899593323}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉         | 1863/2000 [00:41<00:04, 33.52it/s]

[I 2026-07-08 13:33:17,260] Trial 1861 finished with value: 0.9488782633317075 and parameters: {'weight_class_0': 0.9047890383588001, 'weight_class_1': 9.816045177660643, 'weight_class_2': 7.870761112362263}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:17,271] Trial 1863 finished with value: 0.9488588285773222 and parameters: {'weight_class_0': 0.9436793865593259, 'weight_class_1': 9.31368081463359, 'weight_class_2': 7.843218612645363}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  93%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎        | 1869/2000 [00:41<00:03, 35.05it/s]

[I 2026-07-08 13:33:17,357] Trial 1864 finished with value: 0.948873908185217 and parameters: {'weight_class_0': 0.9188217646155461, 'weight_class_1': 9.3197784831023, 'weight_class_2': 7.844687442758633}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:17,361] Trial 1865 finished with value: 0.9488845963578214 and parameters: {'weight_class_0': 0.9393397417252645, 'weight_class_1': 9.366260674369629, 'weight_class_2': 7.853412592439511}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:17,367] Trial 1866 finished with value: 0.9489153136857406 and parameters: {'weight_class_0': 0.8804160974711319, 'weight_class_1': 9.232739430199581, 'weight_class_2': 7.849555899749513}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:17,397] Trial 1867 finished with value: 0.9488611420689992 and parameters: {'weight_class_0': 0.944336114247611, 'weight_class_1': 9.252769615442565, 'weight_class_2': 7.848871807005971}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:17,442] Trial 1868 finished with value: 0.9488467560495932 and parameters: {'weight_class_0': 0.9558975998967563, 'weight_class_1': 9.321078038667556, 'weight_class_2': 7.780764446035498}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:17,476] Trial 1869 finished with value: 0.9488775820793443 and parameters: {'weight_class_0': 0.9307163015914539, 'weight_class_1': 9.328613687703013, 'weight_class_2': 7.803733385441615}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍        | 1871/2000 [00:41<00:03, 35.13it/s]

[I 2026-07-08 13:33:17,511] Trial 1870 finished with value: 0.9491108128329121 and parameters: {'weight_class_0': 0.5766997573175933, 'weight_class_1': 9.142532229807003, 'weight_class_2': 7.757433825842325}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:17,542] Trial 1871 finished with value: 0.9468767516635679 and parameters: {'weight_class_0': 1.4489302594745388, 'weight_class_1': 9.298817105330457, 'weight_class_2': 7.699763959059521}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  94%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉        | 1877/2000 [00:41<00:03, 34.83it/s]

[I 2026-07-08 13:33:17,568] Trial 1873 finished with value: 0.9490896475691093 and parameters: {'weight_class_0': 0.5621697733591984, 'weight_class_1': 9.205289773729206, 'weight_class_2': 7.72550890773932}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:17,593] Trial 1872 finished with value: 0.9491108290729148 and parameters: {'weight_class_0': 0.5519041310228565, 'weight_class_1': 9.207658204352743, 'weight_class_2': 7.827590434681517}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:17,614] Trial 1874 finished with value: 0.9468814992736928 and parameters: {'weight_class_0': 1.4399470063279214, 'weight_class_1': 9.2218464683705, 'weight_class_2': 7.691757622166896}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:17,622] Trial 1875 finished with value: 0.9491334512076707 and parameters: {'weight_class_0': 0.5765545388087954, 'weight_class_1': 9.202587540406874, 'weight_class_2': 7.703045057754974}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:17,659] Trial 1876 finished with value: 0.949144759165318 and parameters: {'weight_class_0': 0.5834881684687748, 'weight_class_1': 9.182370854473826, 'weight_class_2': 7.685635673461989}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:17,688] Trial 1877 finished with value: 0.9491498447030807 and parameters: {'weight_class_0': 0.6041388729514029, 'weight_class_1': 9.133720050121234, 'weight_class_2': 7.6921877256314914}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████        | 1880/2000 [00:42<00:03, 37.42it/s]

[I 2026-07-08 13:33:17,689] Trial 1878 finished with value: 0.9491518514595084 and parameters: {'weight_class_0': 0.5678286012663768, 'weight_class_1': 9.381603468105983, 'weight_class_2': 7.667049114630802}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:17,744] Trial 1880 finished with value: 0.9491665773109492 and parameters: {'weight_class_0': 0.5978046339410523, 'weight_class_1': 9.10397069624586, 'weight_class_2': 7.659274113464597}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:17,770] Trial 1879 finished with value: 0.9491451151345592 and parameters: {'weight_class_0': 0.5870424068601919, 'weight_class_1': 9.124909756540855, 'weight_class_2': 7.68736341175003}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍       | 1885/2000 [00:42<00:03, 36.05it/s]

[I 2026-07-08 13:33:17,822] Trial 1882 finished with value: 0.9491406459842318 and parameters: {'weight_class_0': 0.562451305712969, 'weight_class_1': 9.490704985927954, 'weight_class_2': 7.639044718279498}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:17,851] Trial 1881 finished with value: 0.9491405722835825 and parameters: {'weight_class_0': 0.5745286229496275, 'weight_class_1': 9.448539620192324, 'weight_class_2': 7.64612269719193}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:17,858] Trial 1883 finished with value: 0.9378498590947992 and parameters: {'weight_class_0': 3.0669313580584747, 'weight_class_1': 9.48727415568943, 'weight_class_2': 9.842192948162852}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:17,891] Trial 1884 finished with value: 0.9491484163464848 and parameters: {'weight_class_0': 0.6346294827492419, 'weight_class_1': 9.478324886546128, 'weight_class_2': 7.423410219276339}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:17,931] Trial 1885 finished with value: 0.9491813191350286 and parameters: {'weight_class_0': 0.639113249986224, 'weight_class_1': 9.41616169849589, 'weight_class_2': 7.447349428439524}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋       | 1889/2000 [00:42<00:03, 35.27it/s]

[I 2026-07-08 13:33:17,945] Trial 1886 finished with value: 0.9492082921012113 and parameters: {'weight_class_0': 0.664431025685792, 'weight_class_1': 9.438977746513544, 'weight_class_2': 7.496785769577281}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:17,963] Trial 1887 finished with value: 0.9450016061601919 and parameters: {'weight_class_0': 0.16304562560720115, 'weight_class_1': 9.487037781101117, 'weight_class_2': 7.516583225492103}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:17,979] Trial 1888 finished with value: 0.9491757952354766 and parameters: {'weight_class_0': 0.7109468105613934, 'weight_class_1': 9.419842448240425, 'weight_class_2': 7.4206806410961015}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:18,010] Trial 1889 finished with value: 0.9466233179418331 and parameters: {'weight_class_0': 0.21290514620514678, 'weight_class_1': 9.465865794487893, 'weight_class_2': 7.389055856994404}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  95%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉       | 1893/2000 [00:42<00:02, 37.69it/s]

[I 2026-07-08 13:33:18,034] Trial 1891 finished with value: 0.9462698241974463 and parameters: {'weight_class_0': 0.19871924625108167, 'weight_class_1': 9.431761006381786, 'weight_class_2': 7.46150309435054}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:18,039] Trial 1890 finished with value: 0.9492043120886144 and parameters: {'weight_class_0': 0.6780253510836108, 'weight_class_1': 9.569166415789235, 'weight_class_2': 7.396502257056012}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:18,079] Trial 1892 finished with value: 0.946444151239256 and parameters: {'weight_class_0': 0.20538785865332748, 'weight_class_1': 9.46386952024809, 'weight_class_2': 7.405879833379482}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:18,114] Trial 1893 finished with value: 0.9455859940849076 and parameters: {'weight_class_0': 0.18178181203882648, 'weight_class_1': 9.562663729458883, 'weight_class_2': 8.02787053954979}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏      | 1896/2000 [00:42<00:03, 34.51it/s]

[I 2026-07-08 13:33:18,169] Trial 1894 finished with value: 0.9458596234203203 and parameters: {'weight_class_0': 0.18542105649048035, 'weight_class_1': 9.480133624673984, 'weight_class_2': 7.42549323008797}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:18,194] Trial 1895 finished with value: 0.9420090201423976 and parameters: {'weight_class_0': 0.12296869282761325, 'weight_class_1': 9.522227668233784, 'weight_class_2': 7.383754827060404}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:18,200] Trial 1896 finished with value: 0.6687901774766973 and parameters: {'weight_class_0': 0.011279629069824715, 'weight_class_1': 9.510540019851735, 'weight_class_2': 8.059218675839416}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌      | 1902/2000 [00:42<00:02, 37.16it/s]

[I 2026-07-08 13:33:18,258] Trial 1897 finished with value: 0.9449291560004077 and parameters: {'weight_class_0': 0.1645117467413112, 'weight_class_1': 9.584787507808008, 'weight_class_2': 7.966949038404358}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:18,283] Trial 1898 finished with value: 0.6587378577240383 and parameters: {'weight_class_0': 0.006362938161480813, 'weight_class_1': 9.632636594025332, 'weight_class_2': 7.926861804944282}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:18,304] Trial 1899 finished with value: 0.6859705312457939 and parameters: {'weight_class_0': 0.01607090380649856, 'weight_class_1': 9.62996149794718, 'weight_class_2': 9.450454018175513}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:18,310] Trial 1900 finished with value: 0.947932200283527 and parameters: {'weight_class_0': 1.2726179269386577, 'weight_class_1': 9.63464990131242, 'weight_class_2': 7.971150719324426}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:18,345] Trial 1902 finished with value: 0.9374505499895868 and parameters: {'weight_class_0': 1.226384713471309, 'weight_class_1': 9.636793071272136, 'weight_class_2': 2.7961558675815392}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:18,346] Trial 1901 finished with value: 0.9481211074665694 and parameters: {'weight_class_0': 1.2246049925536822, 'weight_class_1': 9.635636065824572, 'weight_class_2': 8.014632985599413}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊      | 1906/2000 [00:42<00:02, 37.68it/s]

[I 2026-07-08 13:33:18,392] Trial 1904 finished with value: 0.9478863671206842 and parameters: {'weight_class_0': 1.2804627534098776, 'weight_class_1': 9.652628916708855, 'weight_class_2': 7.997292753314731}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:18,418] Trial 1903 finished with value: 0.9478953042288047 and parameters: {'weight_class_0': 1.27841948694588, 'weight_class_1': 9.646634070178612, 'weight_class_2': 7.982629326463423}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:18,456] Trial 1905 finished with value: 0.9486723553786102 and parameters: {'weight_class_0': 0.4416339357517875, 'weight_class_1': 9.670927125794014, 'weight_class_2': 3.3485799373145824}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉      | 1909/2000 [00:42<00:02, 37.68it/s]

[I 2026-07-08 13:33:18,486] Trial 1906 finished with value: 0.9478746972827246 and parameters: {'weight_class_0': 1.2863758577619087, 'weight_class_1': 9.668702798766379, 'weight_class_2': 7.976459161373844}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:18,503] Trial 1907 finished with value: 0.9477871659190381 and parameters: {'weight_class_0': 1.3054346255377465, 'weight_class_1': 9.680870535172334, 'weight_class_2': 7.930489458244757}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:18,528] Trial 1908 finished with value: 0.947871713237777 and parameters: {'weight_class_0': 1.2279400135494947, 'weight_class_1': 9.008885429070768, 'weight_class_2': 7.951399686586212}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:18,589] Trial 1909 finished with value: 0.9359287981250551 and parameters: {'weight_class_0': 1.314479906586238, 'weight_class_1': 8.966370131893893, 'weight_class_2': 2.8571121095846914}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:33:18,590] Trial 1910 finished with value: 0.9489849226812184 and parameters: {'weight_class_0': 0.8304341743559785, 'weight_class_1': 8.99679489167653, 'weight_class_2': 8.009542580584116}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:18,617] Trial 1911 finished with value: 0.948926378958407 and parameters: {'weight_class_0': 0.8473258644652617, 'weight_class_1': 8.996325054652123, 'weight_class_2': 7.991364123324711}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:18,666] Trial 1913 finished with value: 0.9490572578169131 and parameters: {'weight_class_0': 0.7842648352386912, 'weight_class_1': 9.005189062815752, 'weight_class_2': 7.9518882280353695}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  96%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌     | 1918/2000 [00:43<00:02, 37.28it/s]

[I 2026-07-08 13:33:18,669] Trial 1914 finished with value: 0.9489923259229253 and parameters: {'weight_class_0': 0.8269719871842861, 'weight_class_1': 9.031950037190686, 'weight_class_2': 7.921489098940163}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:18,686] Trial 1912 finished with value: 0.948971479319311 and parameters: {'weight_class_0': 0.834234421152472, 'weight_class_1': 8.927950652661647, 'weight_class_2': 7.98855661340675}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:18,708] Trial 1915 finished with value: 0.9488733621008231 and parameters: {'weight_class_0': 0.8434301167488636, 'weight_class_1': 8.944343468561875, 'weight_class_2': 7.235786720677365}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:18,715] Trial 1916 finished with value: 0.9488823734906653 and parameters: {'weight_class_0': 0.4608029747126146, 'weight_class_1': 8.960709122177631, 'weight_class_2': 7.901544567757681}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:18,757] Trial 1917 finished with value: 0.9488529722500169 and parameters: {'weight_class_0': 0.854665649134663, 'weight_class_1': 8.971240479853574, 'weight_class_2': 7.231650555773186}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:18,804] Trial 1918 finished with value: 0.9490339193668399 and parameters: {'weight_class_0': 0.7996234084129898, 'weight_class_1': 9.222419722363073, 'weight_class_2': 7.609228276299517}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  96%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊     | 1921/2000 [00:43<00:02, 37.28it/s]

[I 2026-07-08 13:33:18,810] Trial 1919 finished with value: 0.9489586354262851 and parameters: {'weight_class_0': 0.8089085665244268, 'weight_class_1': 9.036742565086458, 'weight_class_2': 7.279279277256564}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:18,834] Trial 1920 finished with value: 0.9471759775302946 and parameters: {'weight_class_0': 0.7995425874660086, 'weight_class_1': 9.013195652264033, 'weight_class_2': 3.7313497463866607}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:18,890] Trial 1922 finished with value: 0.9015591011396107 and parameters: {'weight_class_0': 5.63477001964987, 'weight_class_1': 9.819251515782293, 'weight_class_2': 7.152720309457442}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏    | 1927/2000 [00:43<00:01, 37.25it/s]

[I 2026-07-08 13:33:18,898] Trial 1921 finished with value: 0.9484485017714851 and parameters: {'weight_class_0': 0.8476370726191208, 'weight_class_1': 6.234678127819647, 'weight_class_2': 7.1868362615819255}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:18,944] Trial 1923 finished with value: 0.9487587080593899 and parameters: {'weight_class_0': 0.4350689018208512, 'weight_class_1': 9.812525695356998, 'weight_class_2': 7.613218292076059}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:18,974] Trial 1924 finished with value: 0.8984548809448523 and parameters: {'weight_class_0': 0.4329756608900382, 'weight_class_1': 9.828287308767132, 'weight_class_2': 0.24896146628036764}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:18,997] Trial 1925 finished with value: 0.9489197451873045 and parameters: {'weight_class_0': 0.45101055286532, 'weight_class_1': 9.811746293740324, 'weight_class_2': 3.7918960369593364}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:19,003] Trial 1926 finished with value: 0.9487328889349085 and parameters: {'weight_class_0': 0.42752381126193945, 'weight_class_1': 9.80063684762605, 'weight_class_2': 7.581299308713618}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:19,048] Trial 1928 finished with value: 0.9488079981238827 and parameters: {'weight_class_0': 0.44894598085332754, 'weight_class_1': 9.812393953363362, 'weight_class_2': 7.629381880515042}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:33:19,050] Trial 1927 finished with value: 0.9487995631966287 and parameters: {'weight_class_0': 0.41801301751585607, 'weight_class_1': 6.129855146300708, 'weight_class_2': 7.640049120061984}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:19,108] Trial 1929 finished with value: 0.9487951293197008 and parameters: {'weight_class_0': 0.4465309921598576, 'weight_class_1': 9.796313259614976, 'weight_class_2': 7.707505097733582}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:33:19,120] Trial 1931 finished with value: 0.948453763453699 and parameters: {'weight_class_0': 0.37375839230442487, 'weight_class_1': 9.770291597494355, 'weight_class_2': 7.68542050426673}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:19,162] Trial 1930 finished with value: 0.948759121283684 and parameters: {'weight_class_0': 0.43571058964493, 'weight_class_1': 9.81467042518775, 'weight_class_2': 7.611968935384063}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:19,206] Trial 1933 finished with value: 0.9488195473350717 and parameters: {'weight_class_0': 0.4497639453886406, 'weight_class_1': 9.810343345081375, 'weight_class_2': 7.650077373905125}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:19,210] Trial 1932 finished with value: 0.9488237489635994 and parameters: {'weight_class_0': 0.4496884063377504, 'weight_class_1': 9.78990413906467, 'weight_class_2': 7.630441528871679}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:19,231] Trial 1934 finished with value: 0.9488711585011166 and parameters: {'weight_class_0': 0.4437716129058684, 'weight_class_1': 9.344228784638242, 'weight_class_2': 7.632272698232696}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊    | 1937/2000 [00:43<00:01, 35.85it/s]

[I 2026-07-08 13:33:19,248] Trial 1935 finished with value: 0.9488952763090888 and parameters: {'weight_class_0': 0.46600058398490196, 'weight_class_1': 9.800429271774354, 'weight_class_2': 7.633253006168481}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:19,284] Trial 1936 finished with value: 0.9485778701530637 and parameters: {'weight_class_0': 1.0246732926583877, 'weight_class_1': 9.312919464866075, 'weight_class_2': 7.644097870499446}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:19,320] Trial 1937 finished with value: 0.9485449392613495 and parameters: {'weight_class_0': 1.0540926459051612, 'weight_class_1': 9.317927861352793, 'weight_class_2': 8.187524944215575}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  97%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏   | 1943/2000 [00:43<00:01, 37.53it/s]

[I 2026-07-08 13:33:19,337] Trial 1938 finished with value: 0.9484802028178311 and parameters: {'weight_class_0': 1.0497380523490258, 'weight_class_1': 9.309349663016986, 'weight_class_2': 7.689816367064999}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:19,365] Trial 1939 finished with value: 0.915833162611277 and parameters: {'weight_class_0': 1.0126548235654542, 'weight_class_1': 9.34328317999641, 'weight_class_2': 1.1705368022632197}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:19,382] Trial 1940 finished with value: 0.9485319031098687 and parameters: {'weight_class_0': 1.0740015508070315, 'weight_class_1': 9.27590346622268, 'weight_class_2': 8.187283656133495}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:19,413] Trial 1941 finished with value: 0.9485419139339868 and parameters: {'weight_class_0': 1.056321127182835, 'weight_class_1': 9.376797246477192, 'weight_class_2': 8.200253014927867}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:19,451] Trial 1943 finished with value: 0.9487716565804845 and parameters: {'weight_class_0': 1.004988398975494, 'weight_class_1': 9.294957043073687, 'weight_class_2': 8.158441588293009}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:19,460] Trial 1942 finished with value: 0.9418321674127021 and parameters: {'weight_class_0': 1.0756294115366778, 'weight_class_1': 9.28653686807503, 'weight_class_2': 3.0659798173087873}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  97%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎   | 1945/2000 [00:43<00:01, 37.53it/s]

[I 2026-07-08 13:33:19,535] Trial 1945 finished with value: 0.948404458624064 and parameters: {'weight_class_0': 1.0279963321830552, 'weight_class_1': 9.247580808068738, 'weight_class_2': 7.356593526916194}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:19,537] Trial 1944 finished with value: 0.9485302502126917 and parameters: {'weight_class_0': 1.0679380317239477, 'weight_class_1': 9.315607502590467, 'weight_class_2': 8.168251800474758}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:33:19,594] Trial 1946 finished with value: 0.9491664674653224 and parameters: {'weight_class_0': 0.6957981834162941, 'weight_class_1': 9.339960285530957, 'weight_class_2': 7.287259992826439}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:19,610] Trial 1947 finished with value: 0.9486464566737293 and parameters: {'weight_class_0': 1.0204701319329632, 'weight_class_1': 9.365623454722954, 'weight_class_2': 8.069132312619058}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:19,616] Trial 1948 finished with value: 0.949193951679284 and parameters: {'weight_class_0': 0.6919197856308744, 'weight_class_1': 9.476807654057707, 'weight_class_2': 8.112192417781422}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:19,663] Trial 1949 finished with value: 0.9491811279996231 and parameters: {'weight_class_0': 0.6802685271863301, 'weight_class_1': 9.493495051806281, 'weight_class_2': 8.11864097215574}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:19,692] Trial 1951 finished with value: 0.9454972412950083 and parameters: {'weight_class_0': 1.6521556009858287, 'weight_class_1': 9.524550263446121, 'weight_class_2': 7.327345415466557}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:19,707] Trial 1952 finished with value: 0.9491838320505374 and parameters: {'weight_class_0': 0.6754792681196875, 'weight_class_1': 9.566124716453455, 'weight_class_2': 8.146176976922819}. Best is trial 455 with value: 0.9492501666906682.

Best trial: 455. Best value: 0.94925:  98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉   | 1953/2000 [00:44<00:01, 35.87it/s]

[I 2026-07-08 13:33:19,716] Trial 1950 finished with value: 0.949185037133424 and parameters: {'weight_class_0': 0.6896683827217023, 'weight_class_1': 9.538420014682458, 'weight_class_2': 8.105007111650066}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:19,747] Trial 1953 finished with value: 0.9492158266070106 and parameters: {'weight_class_0': 0.6779822642004532, 'weight_class_1': 9.564193741287836, 'weight_class_2': 7.355298659328827}. Best is trial 455 with value: 0.9492501666906682.

[I 2026-07-08 13:33:19,769] Trial 1954 finished with value: 0.949123713692881 and parameters: {'weight_class_0': 0.7228731778221937, 'weight_class_1': 9.546158195552822, 'weight_class_2': 7.3262752869603}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:19,793] Trial 1955 finished with value: 0.9491280766548398 and parameters: {'weight_class_0': 0.710491578519926, 'weight_class_1': 9.561058206320988, 'weight_class_2': 7.327911743640465}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:19,862] Trial 1956 finished with value: 0.9463155432121035 and parameters: {'weight_class_0': 1.617161093520544, 'weight_class_1': 9.9934218007425, 'weight_class_2': 7.830783569598136}. Best is trial 455 with value: 0.9492501666906682.
[I 2026-07-08 13:33:19,871] Trial 1957 finished with value: 0.9492629103474223 and parameters: {'weight_class_0': 0.6878593354026348, 'weight_class_1': 9.617609913172789, 'weight_class_2': 7.846235980568103}. Best is trial 1957 with value: 0.9492629103474223.
[I 2026-07-08 13:33:19,885] Trial 1958 finished with value: 0.9492498576475487 and parameters: {'weight_class_0': 0.6942622570968642, 'weight_class_1': 9.586532046989193, 'weight_class_2': 7.830074609320602}. Best is trial 1957 with value: 0.9492629103474223.
[I 2026-07-08 13:33:19,886] Trial 1959 finished with value: 0.9492244745152153 and parameters: {'weight_class_0': 0.7116788659837929, 'weight_class_1': 9.609055614878496, 'weight_class_2': 7.848434926701768}. Best is trial 1957 with value: 0.9492629103474223.

Best trial: 1957. Best value: 0.949263:  98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 1962/2000 [00:44<00:01, 37.41it/s]

[I 2026-07-08 13:33:19,919] Trial 1960 finished with value: 0.9492588641412545 and parameters: {'weight_class_0': 0.6939657977628406, 'weight_class_1': 9.628913848044663, 'weight_class_2': 7.881072667465222}. Best is trial 1957 with value: 0.9492629103474223.
[I 2026-07-08 13:33:19,966] Trial 1961 finished with value: 0.9492384577420555 and parameters: {'weight_class_0': 0.6971290665723824, 'weight_class_1': 9.66015751913799, 'weight_class_2': 7.86184589089917}. Best is trial 1957 with value: 0.9492629103474223.
[I 2026-07-08 13:33:19,995] Trial 1962 finished with value: 0.9492113988418948 and parameters: {'weight_class_0': 0.6760431729427073, 'weight_class_1': 9.644248007547688, 'weight_class_2': 7.851822382359821}. Best is trial 1957 with value: 0.9492629103474223.

Best trial: 1957. Best value: 0.949263:  98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊  | 1967/2000 [00:44<00:00, 38.31it/s]

[I 2026-07-08 13:33:20,023] Trial 1963 finished with value: 0.949185172506987 and parameters: {'weight_class_0': 0.6605971286736492, 'weight_class_1': 9.615561756049141, 'weight_class_2': 7.850093529922151}. Best is trial 1957 with value: 0.9492629103474223.
[I 2026-07-08 13:33:20,049] Trial 1964 finished with value: 0.9492240551742567 and parameters: {'weight_class_0': 0.7086771556673581, 'weight_class_1': 9.695113361090852, 'weight_class_2': 7.883301738067117}. Best is trial 1957 with value: 0.9492629103474223.
[I 2026-07-08 13:33:20,066] Trial 1965 finished with value: 0.8775694695823167 and parameters: {'weight_class_0': 8.81269995052452, 'weight_class_1': 9.99547909910523, 'weight_class_2': 7.852635054090685}. Best is trial 1957 with value: 0.9492629103474223.
[I 2026-07-08 13:33:20,108] Trial 1967 finished with value: 0.9490980490245642 and parameters: {'weight_class_0': 0.5675530064730175, 'weight_class_1': 9.667674455928806, 'weight_class_2': 7.873877982726574}. Best is trial 1957 with value: 0.9492629103474223.
[I 2026-07-08 13:33:20,133] Trial 1966 finished with value: 0.949179558823637 and parameters: {'weight_class_0': 0.6012394734773232, 'weight_class_1': 9.685562092454187, 'weight_class_2': 7.842286424311268}. Best is trial 1957 with value: 0.9492629103474223.

Best trial: 1957. Best value: 0.949263:  98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉  | 1969/2000 [00:44<00:00, 36.57it/s]

[I 2026-07-08 13:33:20,156] Trial 1968 finished with value: 0.9490656104959067 and parameters: {'weight_class_0': 0.5469419441016593, 'weight_class_1': 9.997274832326935, 'weight_class_2': 7.859255570298479}. Best is trial 1957 with value: 0.9492629103474223.
[I 2026-07-08 13:33:20,196] Trial 1969 finished with value: 0.9491443258922266 and parameters: {'weight_class_0': 0.5816878916529932, 'weight_class_1': 9.685289384402289, 'weight_class_2': 7.848313353355401}. Best is trial 1957 with value: 0.9492629103474223.

[I 2026-07-08 13:33:20,230] Trial 1971 finished with value: 0.9468578963452208 and parameters: {'weight_class_0': 0.23553201805080082, 'weight_class_1': 9.646173718679664, 'weight_class_2': 8.250259726035926}. Best is trial 1957 with value: 0.9492629103474223.
[I 2026-07-08 13:33:20,234] Trial 1970 finished with value: 0.949092024432504 and parameters: {'weight_class_0': 0.5964638111821706, 'weight_class_1': 9.675093457870044, 'weight_class_2': 8.199446604064521}. Best is trial 1957 with value: 0.9492629103474223.
[I 2026-07-08 13:33:20,267] Trial 1972 finished with value: 0.9488565948001618 and parameters: {'weight_class_0': 0.927928895399164, 'weight_class_1': 9.657689009076233, 'weight_class_2': 7.8993171873047645}. Best is trial 1957 with value: 0.9492629103474223.
[I 2026-07-08 13:33:20,301] Trial 1974 finished with value: 0.9488968812545734 and parameters: {'weight_class_0': 0.9001969285855274, 'weight_class_1': 9.678543130768281, 'weight_class_2': 8.114228980804244}. Best is trial 1957 with value: 0.9492629103474223.
[I 2026-07-08 13:33:20,302] Trial 1973 finished with value: 0.9488864842890786 and parameters: {'weight_class_0': 0.9123928391965793, 'weight_class_1': 9.61960592035288, 'weight_class_2': 7.856668301674634}. Best is trial 1957 with value: 0.9492629103474223.
[I 2026-07-08 13:33:20,355] Trial 1976 finished with value: 0.9489136608913603 and parameters: {'weight_class_0': 0.9287839369912487, 'weight_class_1': 9.473359333860685, 'weight_class_2': 8.192815827516007}. Best is trial 1957 with value: 0.9492629103474223.

Best trial: 1957. Best value: 0.949263:  99%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌ | 1978/2000 [00:44<00:00, 37.98it/s]

[I 2026-07-08 13:33:20,356] Trial 1975 finished with value: 0.9488752926431382 and parameters: {'weight_class_0': 0.9361730884977619, 'weight_class_1': 9.614819350562339, 'weight_class_2': 8.17316729114565}. Best is trial 1957 with value: 0.9492629103474223.
[I 2026-07-08 13:33:20,387] Trial 1977 finished with value: 0.9490197509156655 and parameters: {'weight_class_0': 0.847215332460531, 'weight_class_1': 9.433172395390768, 'weight_class_2': 8.219278958330824}. Best is trial 1957 with value: 0.9492629103474223.
[I 2026-07-08 13:33:20,419] Trial 1978 finished with value: 0.9488453083845223 and parameters: {'weight_class_0': 0.9395567153662727, 'weight_class_1': 9.432617441254914, 'weight_class_2': 8.206977305496284}. Best is trial 1957 with value: 0.9492629103474223.

Best trial: 1957. Best value: 0.949263:  99%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉ | 1983/2000 [00:44<00:00, 37.30it/s]

[I 2026-07-08 13:33:20,441] Trial 1980 finished with value: 0.9488824518094504 and parameters: {'weight_class_0': 0.924366534830328, 'weight_class_1': 9.415907324735885, 'weight_class_2': 8.1342391368823}. Best is trial 1957 with value: 0.9492629103474223.
[I 2026-07-08 13:33:20,454] Trial 1979 finished with value: 0.9489019155511508 and parameters: {'weight_class_0': 0.9259266442763171, 'weight_class_1': 9.4441349873121, 'weight_class_2': 8.10561550619558}. Best is trial 1957 with value: 0.9492629103474223.
[I 2026-07-08 13:33:20,504] Trial 1981 finished with value: 0.9489191307688989 and parameters: {'weight_class_0': 0.9118379621641113, 'weight_class_1': 9.443396323026697, 'weight_class_2': 8.084342035441624}. Best is trial 1957 with value: 0.9492629103474223.
[I 2026-07-08 13:33:20,516] Trial 1982 finished with value: 0.9485691654627636 and parameters: {'weight_class_0': 1.0500859954506874, 'weight_class_1': 9.442952684445661, 'weight_class_2': 8.08802313639093}. Best is trial 1957 with value: 0.9492629103474223.
[I 2026-07-08 13:33:20,586] Trial 1983 finished with value: 0.9469888145324785 and parameters: {'weight_class_0': 1.4790212187061988, 'weight_class_1': 9.412808267929558, 'weight_class_2': 8.136034711267095}. Best is trial 1957 with value: 0.9492629103474223.

[I 2026-07-08 13:33:20,608] Trial 1985 finished with value: 0.948908833361125 and parameters: {'weight_class_0': 0.9173521967591465, 'weight_class_1': 9.431119505207064, 'weight_class_2': 8.119661088604849}. Best is trial 1957 with value: 0.9492629103474223.
[I 2026-07-08 13:33:20,624] Trial 1984 finished with value: 0.9471215697056931 and parameters: {'weight_class_0': 1.4491411346105934, 'weight_class_1': 9.410440093600648, 'weight_class_2': 8.096854822880227}. Best is trial 1957 with value: 0.9492629103474223.

Best trial: 1957. Best value: 0.949263: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌| 1994/2000 [00:45<00:00, 39.70it/s]

[I 2026-07-08 13:33:20,631] Trial 1986 finished with value: 0.9482582801377392 and parameters: {'weight_class_0': 1.1651137875901427, 'weight_class_1': 9.39966100227459, 'weight_class_2': 8.015746653408016}. Best is trial 1957 with value: 0.9492629103474223.
[I 2026-07-08 13:33:20,662] Trial 1987 finished with value: 0.946925608010471 and parameters: {'weight_class_0': 1.468909675866017, 'weight_class_1': 9.162103908419683, 'weight_class_2': 8.091488493537256}. Best is trial 1957 with value: 0.9492629103474223.
[I 2026-07-08 13:33:20,694] Trial 1988 finished with value: 0.947245018650761 and parameters: {'weight_class_0': 1.3965934639552726, 'weight_class_1': 9.19267120105116, 'weight_class_2': 8.045790080735394}. Best is trial 1957 with value: 0.9492629103474223.
[I 2026-07-08 13:33:20,708] Trial 1989 finished with value: 0.9469930117431459 and parameters: {'weight_class_0': 1.4436441276922123, 'weight_class_1': 9.14691235258784, 'weight_class_2': 7.977686270167525}. Best is trial 1957 with value: 0.9492629103474223.
[I 2026-07-08 13:33:20,746] Trial 1990 finished with value: 0.9483815284331296 and parameters: {'weight_class_0': 1.1085318162787168, 'weight_class_1': 9.169355806088593, 'weight_class_2': 8.001734671127972}. Best is trial 1957 with value: 0.9492629103474223.
[I 2026-07-08 13:33:20,770] Trial 1991 finished with value: 0.9482520426626725 and parameters: {'weight_class_0': 1.1413640849686626, 'weight_class_1': 9.188627238559407, 'weight_class_2': 8.035098122025895}. Best is trial 1957 with value: 0.9492629103474223.
[I 2026-07-08 13:33:20,792] Trial 1992 finished with value: 0.9466794208329712 and parameters: {'weight_class_0': 1.5073038216464658, 'weight_class_1': 9.178751411926656, 'weight_class_2': 8.001689777343556}. Best is trial 1957 with value: 0.9492629103474223.
[I 2026-07-08 13:33:20,819] Trial 1993 finished with value: 0.9481397436366318 and parameters: {'weight_class_0': 1.1897770906866616, 'weight_class_1': 9.213154219710532, 'weight_class_2': 8.001273763424763}. Best is trial 1957 with value: 0.9492629103474223.
[I 2026-07-08 13:33:20,826] Trial 1994 finished with value: 0.947016895804655 and parameters: {'weight_class_0': 1.439057243983271, 'weight_class_1': 9.19442926929062, 'weight_class_2': 7.971775916136276}. Best is trial 1957 with value: 0.9492629103474223.

Best trial: 1957. Best value: 0.949263: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊| 1998/2000 [00:45<00:00, 43.77it/s]

[I 2026-07-08 13:33:20,852] Trial 1995 finished with value: 0.8960131178524339 and parameters: {'weight_class_0': 6.292620847587896, 'weight_class_1': 9.15564839201461, 'weight_class_2': 7.926684213198196}. Best is trial 1957 with value: 0.9492629103474223.
[I 2026-07-08 13:33:20,870] Trial 1997 finished with value: 0.949167161835159 and parameters: {'weight_class_0': 0.741192517094062, 'weight_class_1': 9.136596386519143, 'weight_class_2': 7.82799989333556}. Best is trial 1957 with value: 0.9492629103474223.
[I 2026-07-08 13:33:20,876] Trial 1996 finished with value: 0.9491605260881834 and parameters: {'weight_class_0': 0.7454272586308692, 'weight_class_1': 9.192649992882156, 'weight_class_2': 7.842471747441204}. Best is trial 1957 with value: 0.9492629103474223.
[I 2026-07-08 13:33:20,881] Trial 1998 finished with value: 0.9482631086882273 and parameters: {'weight_class_0': 1.159097291083694, 'weight_class_1': 9.81337953020939, 'weight_class_2': 7.837827394092884}. Best is trial 1957 with value: 0.9492629103474223.

Best trial: 1957. Best value: 0.949263: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2000/2000 [00:45<00:00, 44.27it/s]

[I 2026-07-08 13:33:20,891] Trial 1999 finished with value: 0.9491563601727012 and parameters: {'weight_class_0': 0.7472281813207152, 'weight_class_1': 9.806990513808321, 'weight_class_2': 7.792860884760827}. Best is trial 1957 with value: 0.9492629103474223.

Best trial score:
0.9492629103474223

Best params:
{'weight_class_0': 0.6878593354026348, 'weight_class_1': 9.617609913172789, 'weight_class_2': 7.846235980568103}

In [9]:
weights = np.array([study.best_params['weight_class_0'], study.best_params['weight_class_1'], study.best_params['weight_class_2']])
weighted_probas = X_test.loc[:, cols_use].to_numpy() * weights

pred = np.argmax(weighted_probas, axis=1)

In [10]:
sub_labels = label_encoder.inverse_transform(pred)

# Submission

In [11]:
submission = pd.read_csv('../data/submission/sample_submission.csv')
submission['health_condition'] = sub_labels

submission.to_csv('../data/submission/submission_from_5.2.0_catboost_submission.csv', index=False)

In [12]:
submission.head()

       id health_condition
0  690088        unhealthy
1  690089        unhealthy
2  690090          at-risk
3  690091          at-risk
4  690092        unhealthy