# Imports

In [1]:
import optuna
import pickle

import numpy as np
import pandas as pd

from tqdm import tqdm

from sklearn.metrics import balanced_accuracy_score
from sklearn.model_selection import StratifiedKFold, cross_val_predict

/home/junior/Documentos/GitHub/kaggle-competition-predicting-student-health/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Utils

In [2]:
def load_pickle(file_path):
    with open(file_path, 'rb') as file:
        return pickle.load(file)

# Loading Datasets

In [4]:
X_train = pd.read_parquet('../data/processed/X_train_stacking_layer_one_model_60_trials_data_type_feat_eng.parquet')
y_train = pd.read_parquet('../data/interim/y_train.parquet')

X_test = pd.read_parquet('../data/processed/X_test_stacking_layer_one_model_60_trials_data_type_feat_eng.parquet')

In [5]:
X_train.head()

     lgbm_0    lgbm_1    lgbm_2     xgb_0     xgb_1     xgb_2
0  0.003635  0.000557  0.995808  0.004425  0.000993  0.994582
1  0.995015  0.000736  0.004249  0.994982  0.000534  0.004484
2  0.003843  0.001026  0.995131  0.002812  0.000825  0.996363
3  0.003649  0.001574  0.994777  0.004159  0.001883  0.993958
4  0.995310  0.000026  0.004664  0.991897  0.000029  0.008074

In [6]:
X_test.head()

     lgbm_0    lgbm_1    lgbm_2     xgb_0     xgb_1     xgb_2
0  0.012695  0.003805  0.983500  0.010483  0.004324  0.985194
1  0.494675  0.003871  0.501454  0.506439  0.002756  0.490805
2  0.997004  0.002221  0.000775  0.997250  0.002230  0.000520
3  0.990545  0.000021  0.009434  0.989391  0.000017  0.010592
4  0.006499  0.001510  0.991991  0.009692  0.001897  0.988410

# Machine Learning

In [7]:
label_encoder = load_pickle('../artifacts/label_encoder.pkl')

In [8]:
def objective(trial, X, y):

    w0 = trial.suggest_float('weight_class_0', 0.001, 10.0, log=True)
    w1 = trial.suggest_float('weight_class_1', 0.001, 10.0, log=True)
    w2 = trial.suggest_float('weight_class_2', 0.001, 10.0, log=True)
    weights = np.array([w0, w1, w2])

    proba = X.loc[:, ['xgb_0', 'xgb_1', 'xgb_2']].to_numpy()
    
    weighted_probas = proba * weights
    pred = np.argmax(weighted_probas, axis=1)
    
    score = balanced_accuracy_score(y, pred)

    return score


study = optuna.create_study(
    direction="maximize", 
    sampler=optuna.samplers.TPESampler(seed=42), 
    pruner=optuna.pruners.MedianPruner(n_warmup_steps=2)
)

study.optimize(
    lambda trial: objective(trial, X_train, y_train.health_condition), 
    n_trials=500, 
    n_jobs=-1, 
    show_progress_bar=True
)

print("\nBest trial score:")
print(study.best_trial.value)

print("\nBest params:")
print(study.best_trial.params)

[I 2026-07-13 11:33:48,231] A new study created in memory with name: no-name-ae4c531e-de4e-4930-afea-23b234ae6327

[I 2026-07-13 11:33:48,393] Trial 9 finished with value: 0.5948266534833779 and parameters: {'weight_class_0': 0.7508109608873067, 'weight_class_1': 0.0017896934277486895, 'weight_class_2': 0.39374864154686906}. Best is trial 9 with value: 0.5948266534833779.
[I 2026-07-13 11:33:48,397] Trial 6 finished with value: 0.8666613453789284 and parameters: {'weight_class_0': 1.9951465472062095, 'weight_class_1': 0.1880216634308751, 'weight_class_2': 4.790734804918955}. Best is trial 6 with value: 0.8666613453789284.
[I 2026-07-13 11:33:48,398] Trial 10 finished with value: 0.8422306015053239 and parameters: {'weight_class_0': 0.05094593775052039, 'weight_class_1': 0.023035850791264738, 'weight_class_2': 0.013149627889062307}. Best is trial 6 with value: 0.8666613453789284.
[I 2026-07-13 11:33:48,406] Trial 4 finished with value: 0.7719207124132869 and parameters: {'weight_class_0': 0.5526022123125292, 'weight_class_1': 0.012180390259252424, 'weight_class_2': 0.06354383867694655}. Best is trial 6 with value: 0.8666613453789284.
[I 2026-07-13 11:33:48,407] Trial 7 finished with value: 0.8917257026768143 and parameters: {'weight_class_0': 0.004934580443011969, 'weight_class_1': 0.1270436379318377, 'weight_class_2': 0.0013283335296484925}. Best is trial 7 with value: 0.8917257026768143.
[I 2026-07-13 11:33:48,410] Trial 2 finished with value: 0.6235231558044438 and parameters: {'weight_class_0': 5.856877420760729, 'weight_class_1': 8.27966603698564, 'weight_class_2': 0.001978687052418609}. Best is trial 7 with value: 0.8917257026768143.
[I 2026-07-13 11:33:48,411] Trial 1 finished with value: 0.8874845525203431 and parameters: {'weight_class_0': 0.05330332431543632, 'weight_class_1': 0.035915723873157133, 'weight_class_2': 0.09075162755305725}. Best is trial 7 with value: 0.8917257026768143.
[I 2026-07-13 11:33:48,412] Trial 0 finished with value: 0.4265835648520436 and parameters: {'weight_class_0': 9.200012594501207, 'weight_class_1': 0.0932469654800845, 'weight_class_2': 0.009102178893864318}. Best is trial 7 with value: 0.8917257026768143.
[I 2026-07-13 11:33:48,414] Trial 8 finished with value: 0.3733542395981609 and parameters: {'weight_class_0': 7.569556087691743, 'weight_class_1': 0.03500191190140166, 'weight_class_2': 0.011332825426859983}. Best is trial 7 with value: 0.8917257026768143.
[I 2026-07-13 11:33:48,416] Trial 11 finished with value: 0.8618794413278646 and parameters: {'weight_class_0': 0.5281621009752138, 'weight_class_1': 0.023097985684431742, 'weight_class_2': 1.7611224643274288}. Best is trial 7 with value: 0.8917257026768143.
[I 2026-07-13 11:33:48,417] Trial 5 finished with value: 0.730256570312739 and parameters: {'weight_class_0': 1.8662190046346434, 'weight_class_1': 0.04498079676464709, 'weight_class_2': 0.01609303974162805}. Best is trial 7 with value: 0.8917257026768143.
[I 2026-07-13 11:33:48,419] Trial 3 finished with value: 0.6636112870156434 and parameters: {'weight_class_0': 0.002107425807500968, 'weight_class_1': 0.050735560373851504, 'weight_class_2': 4.359572148789174}. Best is trial 7 with value: 0.8917257026768143.
[I 2026-07-13 11:33:48,552] Trial 12 finished with value: 0.8274405272005524 and parameters: {'weight_class_0': 0.008161407514742038, 'weight_class_1': 0.6989653929706826, 'weight_class_2': 0.001648214880217692}. Best is trial 7 with value: 0.8917257026768143.

[I 2026-07-13 11:33:48,558] Trial 13 finished with value: 0.76185593250411 and parameters: {'weight_class_0': 0.009764906410084156, 'weight_class_1': 0.8699526074133042, 'weight_class_2': 0.001043609058715541}. Best is trial 7 with value: 0.8917257026768143.
[I 2026-07-13 11:33:48,572] Trial 15 finished with value: 0.8323191437637307 and parameters: {'weight_class_0': 0.008614050893175513, 'weight_class_1': 0.5511961081061859, 'weight_class_2': 0.0012938115882767222}. Best is trial 7 with value: 0.8917257026768143.
[I 2026-07-13 11:33:48,576] Trial 14 finished with value: 0.9400701104744545 and parameters: {'weight_class_0': 0.008340046602435014, 'weight_class_1': 0.6930059377775365, 'weight_class_2': 0.1438796129863513}. Best is trial 14 with value: 0.9400701104744545.
[I 2026-07-13 11:33:48,594] Trial 16 finished with value: 0.8491212584797637 and parameters: {'weight_class_0': 0.007678778229679644, 'weight_class_1': 0.36079530132583254, 'weight_class_2': 0.0010010478919744447}. Best is trial 14 with value: 0.9400701104744545.
[I 2026-07-13 11:33:48,598] Trial 17 finished with value: 0.9400881579900912 and parameters: {'weight_class_0': 0.008066996587659086, 'weight_class_1': 0.6721291799858577, 'weight_class_2': 0.11923015605871201}. Best is trial 17 with value: 0.9400881579900912.
[I 2026-07-13 11:33:48,610] Trial 18 finished with value: 0.7274479225705258 and parameters: {'weight_class_0': 0.007448544026071965, 'weight_class_1': 1.018788816937708, 'weight_class_2': 0.0010493252944884144}. Best is trial 17 with value: 0.9400881579900912.
[I 2026-07-13 11:33:48,639] Trial 19 finished with value: 0.7996812999101098 and parameters: {'weight_class_0': 0.006257285247610922, 'weight_class_1': 0.6813458116948063, 'weight_class_2': 0.0012999765868095762}. Best is trial 17 with value: 0.9400881579900912.
[I 2026-07-13 11:33:48,659] Trial 20 finished with value: 0.9421165985510004 and parameters: {'weight_class_0': 0.007681398460443648, 'weight_class_1': 0.5693345969554214, 'weight_class_2': 0.15070523345453377}. Best is trial 20 with value: 0.9421165985510004.
[I 2026-07-13 11:33:48,686] Trial 21 finished with value: 0.8398832937197435 and parameters: {'weight_class_0': 0.0076410905168888855, 'weight_class_1': 0.5254362926688804, 'weight_class_2': 0.001355731185946924}. Best is trial 20 with value: 0.9421165985510004.
[I 2026-07-13 11:33:48,697] Trial 22 finished with value: 0.949131320999292 and parameters: {'weight_class_0': 0.042236205916112504, 'weight_class_1': 0.6887752094553597, 'weight_class_2': 0.2917840812056254}. Best is trial 22 with value: 0.949131320999292.
[I 2026-07-13 11:33:48,710] Trial 23 finished with value: 0.6803937701602735 and parameters: {'weight_class_0': 0.001425874676449645, 'weight_class_1': 2.267242681319221, 'weight_class_2': 0.4103276991599476}. Best is trial 22 with value: 0.949131320999292.
[I 2026-07-13 11:33:48,722] Trial 24 finished with value: 0.9430461656281826 and parameters: {'weight_class_0': 0.043757479043997904, 'weight_class_1': 2.993120335912884, 'weight_class_2': 0.29123636310316403}. Best is trial 22 with value: 0.949131320999292.

Best trial: 34. Best value: 0.949567:   7%|█████████▋                                                                                                                             | 36/500 [00:00<00:08, 53.95it/s]

[I 2026-07-13 11:33:48,757] Trial 25 finished with value: 0.9417307940619241 and parameters: {'weight_class_0': 0.036854116631509434, 'weight_class_1': 2.855573749299493, 'weight_class_2': 0.37985814616467656}. Best is trial 22 with value: 0.949131320999292.
[I 2026-07-13 11:33:48,758] Trial 26 finished with value: 0.938409398343703 and parameters: {'weight_class_0': 0.03957119553150766, 'weight_class_1': 3.555346776911412, 'weight_class_2': 0.40640678166796956}. Best is trial 22 with value: 0.949131320999292.
[I 2026-07-13 11:33:48,778] Trial 27 finished with value: 0.9392307122394961 and parameters: {'weight_class_0': 0.04298272557342732, 'weight_class_1': 3.746271985022204, 'weight_class_2': 0.49910708650043956}. Best is trial 22 with value: 0.949131320999292.
[I 2026-07-13 11:33:48,792] Trial 28 finished with value: 0.936150255601269 and parameters: {'weight_class_0': 0.03081121636799222, 'weight_class_1': 2.9290046119283204, 'weight_class_2': 0.22513618996009305}. Best is trial 22 with value: 0.949131320999292.
[I 2026-07-13 11:33:48,809] Trial 29 finished with value: 0.9404762819350417 and parameters: {'weight_class_0': 0.03501939689421373, 'weight_class_1': 2.8183808074978014, 'weight_class_2': 0.26122392568413494}. Best is trial 22 with value: 0.949131320999292.
[I 2026-07-13 11:33:48,839] Trial 30 finished with value: 0.9336528134175048 and parameters: {'weight_class_0': 0.036068422787193764, 'weight_class_1': 3.7778761133846652, 'weight_class_2': 0.42043394771915593}. Best is trial 22 with value: 0.949131320999292.
[I 2026-07-13 11:33:48,867] Trial 31 finished with value: 0.9378481158629194 and parameters: {'weight_class_0': 0.04219511164269168, 'weight_class_1': 3.8509879141734866, 'weight_class_2': 0.6184053172711438}. Best is trial 22 with value: 0.949131320999292.
[I 2026-07-13 11:33:48,888] Trial 32 finished with value: 0.9378797920058233 and parameters: {'weight_class_0': 0.04373789320702063, 'weight_class_1': 4.003433356351351, 'weight_class_2': 0.44921267527955266}. Best is trial 22 with value: 0.949131320999292.
[I 2026-07-13 11:33:48,901] Trial 33 finished with value: 0.942271521496084 and parameters: {'weight_class_0': 0.041466502336900475, 'weight_class_1': 3.1079289219532846, 'weight_class_2': 0.5207763570623963}. Best is trial 22 with value: 0.949131320999292.
[I 2026-07-13 11:33:48,914] Trial 34 finished with value: 0.9495669478774039 and parameters: {'weight_class_0': 0.1295627522862249, 'weight_class_1': 1.6176195057825369, 'weight_class_2': 1.120025979906808}. Best is trial 34 with value: 0.9495669478774039.
[I 2026-07-13 11:33:48,945] Trial 35 finished with value: 0.8865010886606405 and parameters: {'weight_class_0': 0.19493748334947603, 'weight_class_1': 8.704006280793754, 'weight_class_2': 0.05438004097342565}. Best is trial 34 with value: 0.9495669478774039.
[I 2026-07-13 11:33:48,950] Trial 36 finished with value: 0.9458393430078753 and parameters: {'weight_class_0': 0.1853064458056433, 'weight_class_1': 9.451144762165557, 'weight_class_2': 1.1437487553976824}. Best is trial 34 with value: 0.9495669478774039.

Best trial: 47. Best value: 0.949764:  10%|█████████████▏                                                                                                                         | 49/500 [00:00<00:07, 56.41it/s]

[I 2026-07-13 11:33:48,983] Trial 38 finished with value: 0.8777509548776279 and parameters: {'weight_class_0': 0.14730249955981578, 'weight_class_1': 9.184145252312119, 'weight_class_2': 0.043542465163643664}. Best is trial 34 with value: 0.9495669478774039.
[I 2026-07-13 11:33:48,987] Trial 37 finished with value: 0.8641538246258526 and parameters: {'weight_class_0': 0.257146344352922, 'weight_class_1': 9.909911685108442, 'weight_class_2': 0.03382060906302903}. Best is trial 34 with value: 0.9495669478774039.
[I 2026-07-13 11:33:49,000] Trial 39 finished with value: 0.8649331034066347 and parameters: {'weight_class_0': 0.13318628022915494, 'weight_class_1': 9.931250640379977, 'weight_class_2': 0.03734501888200618}. Best is trial 34 with value: 0.9495669478774039.
[I 2026-07-13 11:33:49,025] Trial 40 finished with value: 0.8942673031971227 and parameters: {'weight_class_0': 0.11859913698598706, 'weight_class_1': 1.3363139613690644, 'weight_class_2': 0.036616717710257686}. Best is trial 34 with value: 0.9495669478774039.
[I 2026-07-13 11:33:49,036] Trial 41 finished with value: 0.879348517672406 and parameters: {'weight_class_0': 0.12336360134505124, 'weight_class_1': 9.302498741529496, 'weight_class_2': 0.050735917695904534}. Best is trial 34 with value: 0.9495669478774039.
[I 2026-07-13 11:33:49,050] Trial 42 finished with value: 0.8812581505459017 and parameters: {'weight_class_0': 0.11120821709631167, 'weight_class_1': 8.911127558485923, 'weight_class_2': 0.05460554786197731}. Best is trial 34 with value: 0.9495669478774039.
[I 2026-07-13 11:33:49,070] Trial 43 finished with value: 0.9451616733136378 and parameters: {'weight_class_0': 0.14083916901693455, 'weight_class_1': 8.551816594423899, 'weight_class_2': 1.2678586823340579}. Best is trial 34 with value: 0.9495669478774039.
[I 2026-07-13 11:33:49,091] Trial 44 finished with value: 0.9496591428423801 and parameters: {'weight_class_0': 0.11329906206443054, 'weight_class_1': 1.584907116545102, 'weight_class_2': 1.2354241500897363}. Best is trial 44 with value: 0.9496591428423801.
[I 2026-07-13 11:33:49,102] Trial 45 finished with value: 0.9491995169225563 and parameters: {'weight_class_0': 0.15816290203941014, 'weight_class_1': 1.4369201562588698, 'weight_class_2': 1.2069308364202984}. Best is trial 44 with value: 0.9496591428423801.
[I 2026-07-13 11:33:49,121] Trial 46 finished with value: 0.9496456886375578 and parameters: {'weight_class_0': 0.09944495570588628, 'weight_class_1': 1.4583659806339127, 'weight_class_2': 1.1572782110128212}. Best is trial 44 with value: 0.9496591428423801.
[I 2026-07-13 11:33:49,139] Trial 47 finished with value: 0.9497640908263807 and parameters: {'weight_class_0': 0.10958802743546375, 'weight_class_1': 1.5972590682026655, 'weight_class_2': 1.099305316896185}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:49,161] Trial 48 finished with value: 0.9493877297077682 and parameters: {'weight_class_0': 0.08612632456385944, 'weight_class_1': 1.5248624366579222, 'weight_class_2': 1.1898834780594594}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:49,195] Trial 49 finished with value: 0.9366991143768968 and parameters: {'weight_class_0': 0.016864191628243576, 'weight_class_1': 1.4585505768011295, 'weight_class_2': 1.1942078530939653}. Best is trial 47 with value: 0.9497640908263807.

Best trial: 47. Best value: 0.949764:  12%|████████████████▍                                                                                                                      | 61/500 [00:01<00:07, 55.87it/s]

[I 2026-07-13 11:33:49,199] Trial 50 finished with value: 0.9486258302111853 and parameters: {'weight_class_0': 0.06837592104848375, 'weight_class_1': 1.5873033312990885, 'weight_class_2': 1.4683380098979688}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:49,214] Trial 51 finished with value: 0.9424597385041383 and parameters: {'weight_class_0': 0.019606719621445275, 'weight_class_1': 1.283010357719209, 'weight_class_2': 1.0407990062433414}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:49,220] Trial 52 finished with value: 0.935935225527964 and parameters: {'weight_class_0': 0.016329198413914652, 'weight_class_1': 1.4483232571587032, 'weight_class_2': 1.1968305801060282}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:49,250] Trial 53 finished with value: 0.906867703269719 and parameters: {'weight_class_0': 0.45684648480161655, 'weight_class_1': 0.3082164127465644, 'weight_class_2': 8.429129923199799}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:49,268] Trial 54 finished with value: 0.9176413486766571 and parameters: {'weight_class_0': 0.02075297154857056, 'weight_class_1': 0.24061079135371077, 'weight_class_2': 3.87930798643047}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:49,282] Trial 55 finished with value: 0.7641477329990715 and parameters: {'weight_class_0': 0.015337243127241662, 'weight_class_1': 0.27390267486161185, 'weight_class_2': 8.815067559390636}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:49,299] Trial 57 finished with value: 0.9375912449540326 and parameters: {'weight_class_0': 0.07560056442445691, 'weight_class_1': 0.3000401273940627, 'weight_class_2': 8.272245091974618}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:49,310] Trial 56 finished with value: 0.8030718387438284 and parameters: {'weight_class_0': 0.018964960290600335, 'weight_class_1': 0.21406608905016283, 'weight_class_2': 8.428241074999931}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:49,338] Trial 58 finished with value: 0.9307481268732447 and parameters: {'weight_class_0': 0.07777403602413092, 'weight_class_1': 0.18788022681451078, 'weight_class_2': 8.541919619936376}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:49,368] Trial 60 finished with value: 0.9148693697168649 and parameters: {'weight_class_0': 0.35286735053636487, 'weight_class_1': 0.33114305821210566, 'weight_class_2': 3.0758710260703044}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:49,375] Trial 59 finished with value: 0.9148112863057101 and parameters: {'weight_class_0': 0.40314331036985857, 'weight_class_1': 0.390356019351966, 'weight_class_2': 2.409470413212181}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:49,390] Trial 61 finished with value: 0.9441694091932223 and parameters: {'weight_class_0': 0.07785545208258017, 'weight_class_1': 0.2880591024279593, 'weight_class_2': 2.803439400555228}. Best is trial 47 with value: 0.9497640908263807.

Best trial: 47. Best value: 0.949764:  14%|███████████████████▍                                                                                                                   | 72/500 [00:01<00:07, 54.32it/s]

[I 2026-07-13 11:33:49,398] Trial 62 finished with value: 0.9422662670642201 and parameters: {'weight_class_0': 0.07657133014113647, 'weight_class_1': 5.426962600077904, 'weight_class_2': 2.480375270156521}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:49,433] Trial 63 finished with value: 0.941921815732178 and parameters: {'weight_class_0': 0.07612433309769576, 'weight_class_1': 5.56363137141911, 'weight_class_2': 2.1886811938910453}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:49,436] Trial 64 finished with value: 0.9481163082276794 and parameters: {'weight_class_0': 0.3504931459826304, 'weight_class_1': 1.8781876103996171, 'weight_class_2': 2.6243239919852495}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:49,463] Trial 65 finished with value: 0.9495255275939151 and parameters: {'weight_class_0': 0.2896865278713851, 'weight_class_1': 5.5937254348129235, 'weight_class_2': 2.454457620628138}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:49,485] Trial 66 finished with value: 0.9492220476539001 and parameters: {'weight_class_0': 0.301969749943947, 'weight_class_1': 5.575300156538663, 'weight_class_2': 2.1787631596612522}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:49,492] Trial 67 finished with value: 0.935496468262495 and parameters: {'weight_class_0': 1.0889284598286333, 'weight_class_1': 6.0869988630245935, 'weight_class_2': 2.304026237212663}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:49,503] Trial 68 finished with value: 0.9481806205137581 and parameters: {'weight_class_0': 0.34371618997232334, 'weight_class_1': 2.0048890844164973, 'weight_class_2': 2.4182345798564255}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:49,531] Trial 69 finished with value: 0.9345636339123602 and parameters: {'weight_class_0': 1.080839516320691, 'weight_class_1': 5.553550564508604, 'weight_class_2': 2.2454699342861457}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:49,553] Trial 70 finished with value: 0.9489209221365704 and parameters: {'weight_class_0': 0.2447101610254399, 'weight_class_1': 1.7849892670067236, 'weight_class_2': 1.8637907038827155}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:49,572] Trial 71 finished with value: 0.897051007003387 and parameters: {'weight_class_0': 0.8537041259522303, 'weight_class_1': 2.087559747152145, 'weight_class_2': 0.7513542808086944}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:49,586] Trial 72 finished with value: 0.8915069350182253 and parameters: {'weight_class_0': 0.7166683358838399, 'weight_class_1': 0.9943871992070705, 'weight_class_2': 0.8103952359112536}. Best is trial 47 with value: 0.9497640908263807.

Best trial: 47. Best value: 0.949764:  17%|██████████████████████▋                                                                                                                | 84/500 [00:01<00:07, 53.18it/s]

[I 2026-07-13 11:33:49,604] Trial 73 finished with value: 0.8442722105561166 and parameters: {'weight_class_0': 2.11913806206319, 'weight_class_1': 0.9699666081261501, 'weight_class_2': 0.7736064846152589}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:49,623] Trial 74 finished with value: 0.8755003274682891 and parameters: {'weight_class_0': 0.8623289463367982, 'weight_class_1': 0.9902800326642647, 'weight_class_2': 0.7314847798435002}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:49,640] Trial 75 finished with value: 0.8718012757076017 and parameters: {'weight_class_0': 0.9657197741033747, 'weight_class_1': 0.8911560811440805, 'weight_class_2': 0.893880990768403}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:49,661] Trial 76 finished with value: 0.94085612468967 and parameters: {'weight_class_0': 0.24529445857649335, 'weight_class_1': 0.9395995025913646, 'weight_class_2': 0.7338094938114424}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:49,681] Trial 77 finished with value: 0.8916646266512869 and parameters: {'weight_class_0': 0.6747299340850336, 'weight_class_1': 0.8916429816531073, 'weight_class_2': 0.796898507695263}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:49,692] Trial 78 finished with value: 0.9418770828903185 and parameters: {'weight_class_0': 0.2557133369429795, 'weight_class_1': 0.8956056057620584, 'weight_class_2': 0.8826854457375413}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:49,713] Trial 79 finished with value: 0.9317215135454832 and parameters: {'weight_class_0': 0.5953587929274237, 'weight_class_1': 0.9701488948361354, 'weight_class_2': 4.977646498230435}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:49,733] Trial 80 finished with value: 0.9338690520909579 and parameters: {'weight_class_0': 0.23384653292627597, 'weight_class_1': 0.4799257540067546, 'weight_class_2': 0.8101025239068085}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:49,749] Trial 81 finished with value: 0.6536348288809087 and parameters: {'weight_class_0': 0.2500832097362385, 'weight_class_1': 0.0010272061343663645, 'weight_class_2': 4.984051685735565}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:49,770] Trial 83 finished with value: 0.6589929426101206 and parameters: {'weight_class_0': 0.18736274492711938, 'weight_class_1': 0.0010811398063257712, 'weight_class_2': 6.077935920872407}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:49,792] Trial 82 finished with value: 0.9365880631210332 and parameters: {'weight_class_0': 0.2418693043056491, 'weight_class_1': 0.4903918859736989, 'weight_class_2': 5.757375004157908}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:49,809] Trial 84 finished with value: 0.7611741744954531 and parameters: {'weight_class_0': 0.1776615782005162, 'weight_class_1': 0.003728069316057167, 'weight_class_2': 0.005163642554717788}. Best is trial 47 with value: 0.9497640908263807.

[I 2026-07-13 11:33:49,833] Trial 85 finished with value: 0.9402872520630723 and parameters: {'weight_class_0': 0.17517408687940997, 'weight_class_1': 0.43820452290105866, 'weight_class_2': 5.187321550106046}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:49,858] Trial 87 finished with value: 0.830713745708317 and parameters: {'weight_class_0': 0.05720718320262065, 'weight_class_1': 0.0027472181609731134, 'weight_class_2': 1.594102935017026}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:49,862] Trial 86 finished with value: 0.7313430014354045 and parameters: {'weight_class_0': 0.05920160927989804, 'weight_class_1': 0.0010416130032499167, 'weight_class_2': 1.8011892065858468}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:49,890] Trial 88 finished with value: 0.9491436968241028 and parameters: {'weight_class_0': 0.10622538959508979, 'weight_class_1': 2.667929898588625, 'weight_class_2': 1.4982387903789902}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:49,901] Trial 89 finished with value: 0.767973786718343 and parameters: {'weight_class_0': 0.09564717594906344, 'weight_class_1': 2.351994748751809, 'weight_class_2': 0.00273027647198195}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:49,921] Trial 90 finished with value: 0.9490272282050416 and parameters: {'weight_class_0': 0.09710907894309329, 'weight_class_1': 2.305991009237207, 'weight_class_2': 1.6053586579241301}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:49,938] Trial 91 finished with value: 0.9490377819215392 and parameters: {'weight_class_0': 0.09976808372383383, 'weight_class_1': 2.3763686956918013, 'weight_class_2': 1.5716901234471643}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:49,977] Trial 92 finished with value: 0.9478728943689205 and parameters: {'weight_class_0': 0.05776334670624033, 'weight_class_1': 0.6490368134955636, 'weight_class_2': 1.5427398353710786}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:49,978] Trial 93 finished with value: 0.9477669050871566 and parameters: {'weight_class_0': 0.05707872532658641, 'weight_class_1': 0.6654977367164293, 'weight_class_2': 1.6228011764626629}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,010] Trial 94 finished with value: 0.9481656405447646 and parameters: {'weight_class_0': 0.10242325857622767, 'weight_class_1': 2.4893471188121645, 'weight_class_2': 0.5857666801476216}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,023] Trial 95 finished with value: 0.931494544327928 and parameters: {'weight_class_0': 0.02853754308704664, 'weight_class_1': 2.524871178334863, 'weight_class_2': 3.2239489771745804}. Best is trial 47 with value: 0.9497640908263807.

Best trial: 47. Best value: 0.949764:  21%|████████████████████████████▋                                                                                                         | 107/500 [00:02<00:07, 54.58it/s]

[I 2026-07-13 11:33:50,047] Trial 96 finished with value: 0.9490940586058372 and parameters: {'weight_class_0': 0.09643230631008777, 'weight_class_1': 2.3905889091678785, 'weight_class_2': 1.4243796895657228}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,055] Trial 97 finished with value: 0.9476674388743129 and parameters: {'weight_class_0': 0.10309965373866325, 'weight_class_1': 2.526482783442569, 'weight_class_2': 3.6378709170785943}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,065] Trial 98 finished with value: 0.9079031266552305 and parameters: {'weight_class_0': 0.02817033333404303, 'weight_class_1': 4.537004694000577, 'weight_class_2': 0.19401816466517854}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,076] Trial 99 finished with value: 0.9475986670655508 and parameters: {'weight_class_0': 0.1415272456018225, 'weight_class_1': 1.2665975831538476, 'weight_class_2': 3.659744892450689}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,101] Trial 100 finished with value: 0.9151821370387209 and parameters: {'weight_class_0': 0.029882342803304512, 'weight_class_1': 4.512353484475832, 'weight_class_2': 0.5653548046782993}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,118] Trial 101 finished with value: 0.9098638723419192 and parameters: {'weight_class_0': 0.029546904559760563, 'weight_class_1': 4.429427244023802, 'weight_class_2': 3.3172802266074344}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,147] Trial 102 finished with value: 0.9018003138078262 and parameters: {'weight_class_0': 0.026703159853944707, 'weight_class_1': 4.40684888014375, 'weight_class_2': 3.282340046196839}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,164] Trial 103 finished with value: 0.9374922794798927 and parameters: {'weight_class_0': 0.14908161331865633, 'weight_class_1': 4.497611470103569, 'weight_class_2': 0.3320916177368804}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,190] Trial 104 finished with value: 0.9479316550862 and parameters: {'weight_class_0': 0.15160444657585134, 'weight_class_1': 4.672432898821321, 'weight_class_2': 3.8010655617028206}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,195] Trial 105 finished with value: 0.9365179351112104 and parameters: {'weight_class_0': 0.15581790025689193, 'weight_class_1': 4.459301886784505, 'weight_class_2': 0.3342558596608894}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,226] Trial 106 finished with value: 0.6966227695693439 and parameters: {'weight_class_0': 0.0035448816083670266, 'weight_class_1': 3.411041304656064, 'weight_class_2': 1.0813724516737784}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,244] Trial 107 finished with value: 0.9359034761584958 and parameters: {'weight_class_0': 0.1504886787640665, 'weight_class_1': 3.3735706696592564, 'weight_class_2': 0.3117919884244298}. Best is trial 47 with value: 0.9497640908263807.

Best trial: 47. Best value: 0.949764:  24%|███████████████████████████████▉                                                                                                      | 119/500 [00:02<00:06, 54.58it/s]

[I 2026-07-13 11:33:50,248] Trial 108 finished with value: 0.9491475759811911 and parameters: {'weight_class_0': 0.15674807513470854, 'weight_class_1': 1.2078968032556165, 'weight_class_2': 1.2705434673157763}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,270] Trial 109 finished with value: 0.9367062761383251 and parameters: {'weight_class_0': 0.14394472985132825, 'weight_class_1': 1.1844861416062462, 'weight_class_2': 0.30736940739622776}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,292] Trial 110 finished with value: 0.9347930039221294 and parameters: {'weight_class_0': 0.1516037004101547, 'weight_class_1': 6.916122354481992, 'weight_class_2': 0.3251069299663871}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,311] Trial 111 finished with value: 0.8986864371434069 and parameters: {'weight_class_0': 0.12559457452215445, 'weight_class_1': 3.2758682318117387, 'weight_class_2': 0.08225147961490219}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,337] Trial 112 finished with value: 0.9451276681301711 and parameters: {'weight_class_0': 0.11893064929393035, 'weight_class_1': 7.2287910100609905, 'weight_class_2': 1.054968501192371}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,363] Trial 113 finished with value: 0.9171553331843474 and parameters: {'weight_class_0': 0.04911052945433345, 'weight_class_1': 7.181435246181817, 'weight_class_2': 1.0012522434282192}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,375] Trial 114 finished with value: 0.9397172722205099 and parameters: {'weight_class_0': 0.4408239970839607, 'weight_class_1': 6.789357962059042, 'weight_class_2': 1.0411425820244153}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,389] Trial 115 finished with value: 0.9467772857403595 and parameters: {'weight_class_0': 0.3173876576936926, 'weight_class_1': 7.129226435591503, 'weight_class_2': 1.2905771501323549}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,428] Trial 116 finished with value: 0.9486763850079258 and parameters: {'weight_class_0': 0.30303338958996834, 'weight_class_1': 7.255087684122485, 'weight_class_2': 1.9881831529082548}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,436] Trial 117 finished with value: 0.9222446119925917 and parameters: {'weight_class_0': 0.048749938189331384, 'weight_class_1': 6.469580577170068, 'weight_class_2': 1.966712180785976}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,448] Trial 118 finished with value: 0.9496044267990232 and parameters: {'weight_class_0': 0.11591758422047271, 'weight_class_1': 1.6296249642149752, 'weight_class_2': 1.3626666684429385}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,463] Trial 120 finished with value: 0.9443626005278544 and parameters: {'weight_class_0': 0.2983669676994054, 'weight_class_1': 1.7691512680697499, 'weight_class_2': 0.9900041205492058}. Best is trial 47 with value: 0.9497640908263807.

Best trial: 47. Best value: 0.949764:  26%|███████████████████████████████████                                                                                                   | 131/500 [00:02<00:06, 55.27it/s]

[I 2026-07-13 11:33:50,465] Trial 119 finished with value: 0.9443445496840949 and parameters: {'weight_class_0': 0.3036820512949115, 'weight_class_1': 1.6583298058457976, 'weight_class_2': 1.0286743244246617}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,492] Trial 121 finished with value: 0.9492459882875245 and parameters: {'weight_class_0': 0.08470546543473301, 'weight_class_1': 1.67750489872155, 'weight_class_2': 1.3002787259919117}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,513] Trial 122 finished with value: 0.9492074235685802 and parameters: {'weight_class_0': 0.08713982683364677, 'weight_class_1': 1.5143900956622798, 'weight_class_2': 1.3777052455997087}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,544] Trial 123 finished with value: 0.9477263221178468 and parameters: {'weight_class_0': 0.3011480958842768, 'weight_class_1': 1.622535501765091, 'weight_class_2': 1.916793767711362}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,546] Trial 124 finished with value: 0.949390313773824 and parameters: {'weight_class_0': 0.08600681522012416, 'weight_class_1': 1.5765698591986796, 'weight_class_2': 0.6603212311423368}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,571] Trial 125 finished with value: 0.9487083084220317 and parameters: {'weight_class_0': 0.0874232050491552, 'weight_class_1': 1.8198549691881698, 'weight_class_2': 1.9593601870127229}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,589] Trial 126 finished with value: 0.9488443187985064 and parameters: {'weight_class_0': 0.06972809163234048, 'weight_class_1': 1.6877545351031622, 'weight_class_2': 1.2929379981780642}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,618] Trial 128 finished with value: 0.9479378797033834 and parameters: {'weight_class_0': 0.20462481560241164, 'weight_class_1': 1.1367865077578136, 'weight_class_2': 1.3808770882605084}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,623] Trial 127 finished with value: 0.9478823624309841 and parameters: {'weight_class_0': 0.20425334271334758, 'weight_class_1': 1.1425231304965544, 'weight_class_2': 1.3145904308612424}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,639] Trial 129 finished with value: 0.9494349800136653 and parameters: {'weight_class_0': 0.08503600197822034, 'weight_class_1': 1.170408622367885, 'weight_class_2': 0.6608107704560843}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,666] Trial 131 finished with value: 0.9492095381093836 and parameters: {'weight_class_0': 0.08321586686135263, 'weight_class_1': 1.424996545908967, 'weight_class_2': 1.359915747216122}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,682] Trial 130 finished with value: 0.9493216708778629 and parameters: {'weight_class_0': 0.08336573049995884, 'weight_class_1': 1.1980244452318474, 'weight_class_2': 1.300537704680464}. Best is trial 47 with value: 0.9497640908263807.

[I 2026-07-13 11:33:50,697] Trial 132 finished with value: 0.9496053475569193 and parameters: {'weight_class_0': 0.0714017458447141, 'weight_class_1': 1.1502450373657602, 'weight_class_2': 0.6206900139846683}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,713] Trial 133 finished with value: 0.9437542297034853 and parameters: {'weight_class_0': 0.20267648086972995, 'weight_class_1': 1.1800496351905896, 'weight_class_2': 0.6470082052719394}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,729] Trial 134 finished with value: 0.9429099569788583 and parameters: {'weight_class_0': 0.20534810207160664, 'weight_class_1': 1.14978803564877, 'weight_class_2': 0.6201639853286742}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,743] Trial 135 finished with value: 0.9496252273037417 and parameters: {'weight_class_0': 0.062362598994664495, 'weight_class_1': 1.133048382939856, 'weight_class_2': 0.5942771924600905}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,769] Trial 136 finished with value: 0.9496673091658104 and parameters: {'weight_class_0': 0.06659441023997441, 'weight_class_1': 1.4222420531180742, 'weight_class_2': 0.6488194766821741}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,799] Trial 138 finished with value: 0.9492814924795784 and parameters: {'weight_class_0': 0.06644026265370126, 'weight_class_1': 0.8395107842766019, 'weight_class_2': 0.4817243209498998}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,805] Trial 137 finished with value: 0.9492508283228397 and parameters: {'weight_class_0': 0.06763544068632704, 'weight_class_1': 1.3951319571939422, 'weight_class_2': 0.5077346748675372}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,824] Trial 139 finished with value: 0.94902009327373 and parameters: {'weight_class_0': 0.08319878026873913, 'weight_class_1': 0.7765670469677931, 'weight_class_2': 0.5904150247245991}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,837] Trial 140 finished with value: 0.9492877660329994 and parameters: {'weight_class_0': 0.08247340273422767, 'weight_class_1': 0.7830143677793198, 'weight_class_2': 0.6578255139468946}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,849] Trial 141 finished with value: 0.9496607991781904 and parameters: {'weight_class_0': 0.0635977687560183, 'weight_class_1': 0.7608056438789603, 'weight_class_2': 0.6102802085804501}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,886] Trial 143 finished with value: 0.9493173099559439 and parameters: {'weight_class_0': 0.07227953098153775, 'weight_class_1': 0.8101244823547148, 'weight_class_2': 0.5414562000096496}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,899] Trial 142 finished with value: 0.9493392765231264 and parameters: {'weight_class_0': 0.06690956118925953, 'weight_class_1': 0.8268446035391501, 'weight_class_2': 0.4984160321656614}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,927] Trial 144 finished with value: 0.9492648326549028 and parameters: {'weight_class_0': 0.06426828832713118, 'weight_class_1': 0.774096138159045, 'weight_class_2': 0.46933503732791}. Best is trial 47 with value: 0.9497640908263807.

Best trial: 47. Best value: 0.949764:  31%|█████████████████████████████████████████▊                                                                                            | 156/500 [00:02<00:06, 55.86it/s]

[I 2026-07-13 11:33:50,937] Trial 145 finished with value: 0.9488874866992006 and parameters: {'weight_class_0': 0.06738247820717534, 'weight_class_1': 0.7497679151975336, 'weight_class_2': 0.4267232468498221}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,938] Trial 146 finished with value: 0.9494102719837193 and parameters: {'weight_class_0': 0.06427776960744207, 'weight_class_1': 0.7608486133235888, 'weight_class_2': 0.501982661649333}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,967] Trial 147 finished with value: 0.948925274404289 and parameters: {'weight_class_0': 0.06477953375072715, 'weight_class_1': 0.6050593372668583, 'weight_class_2': 0.44111449517167545}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:50,992] Trial 149 finished with value: 0.9496558497876243 and parameters: {'weight_class_0': 0.0362885919259118, 'weight_class_1': 0.577923506558536, 'weight_class_2': 0.42455963658946444}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,003] Trial 148 finished with value: 0.9487247113154198 and parameters: {'weight_class_0': 0.0676307204764398, 'weight_class_1': 0.5758751679611077, 'weight_class_2': 0.4326582759861392}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,013] Trial 150 finished with value: 0.9496835052397303 and parameters: {'weight_class_0': 0.04714646471064212, 'weight_class_1': 0.5861344386117672, 'weight_class_2': 0.45297682976489806}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,036] Trial 151 finished with value: 0.9493538335962947 and parameters: {'weight_class_0': 0.048984698707352906, 'weight_class_1': 0.8187787799582452, 'weight_class_2': 0.7069188098776972}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,059] Trial 152 finished with value: 0.9475959474156758 and parameters: {'weight_class_0': 0.046827035654334964, 'weight_class_1': 2.033558482558248, 'weight_class_2': 0.40510672851301294}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,060] Trial 153 finished with value: 0.9495468775014455 and parameters: {'weight_class_0': 0.04875226455968667, 'weight_class_1': 0.6321847537093092, 'weight_class_2': 0.41498508912009563}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,080] Trial 154 finished with value: 0.949278042031442 and parameters: {'weight_class_0': 0.05015620292423182, 'weight_class_1': 0.5328783566729072, 'weight_class_2': 0.38313461001053656}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,096] Trial 155 finished with value: 0.9483072799633091 and parameters: {'weight_class_0': 0.049040503804624894, 'weight_class_1': 0.6162334127685196, 'weight_class_2': 0.25511739628979596}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,136] Trial 156 finished with value: 0.9489358835790914 and parameters: {'weight_class_0': 0.0398359483165328, 'weight_class_1': 0.5731543221421308, 'weight_class_2': 0.24844053075679354}. Best is trial 47 with value: 0.9497640908263807.

Best trial: 47. Best value: 0.949764:  33%|████████████████████████████████████████████▊                                                                                         | 167/500 [00:03<00:05, 55.74it/s]

[I 2026-07-13 11:33:51,142] Trial 157 finished with value: 0.9489187328676171 and parameters: {'weight_class_0': 0.04489464611399602, 'weight_class_1': 0.538679604792228, 'weight_class_2': 0.8502973700147866}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,143] Trial 158 finished with value: 0.9487091054826937 and parameters: {'weight_class_0': 0.049997292987587004, 'weight_class_1': 0.5050028880394543, 'weight_class_2': 0.8949996141810899}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,162] Trial 159 finished with value: 0.9487051900846134 and parameters: {'weight_class_0': 0.039130924781372874, 'weight_class_1': 0.3798294625551924, 'weight_class_2': 0.23705944657742634}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,211] Trial 161 finished with value: 0.9484489620174493 and parameters: {'weight_class_0': 0.04296044739008643, 'weight_class_1': 0.4573567692478846, 'weight_class_2': 0.8666979188639445}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,220] Trial 160 finished with value: 0.9452508036755645 and parameters: {'weight_class_0': 0.036604633740624455, 'weight_class_1': 2.0176471349998613, 'weight_class_2': 0.22892233315240615}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,235] Trial 162 finished with value: 0.9484949838650651 and parameters: {'weight_class_0': 0.038923306605299676, 'weight_class_1': 0.5131154966420478, 'weight_class_2': 0.21344514043517884}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,251] Trial 163 finished with value: 0.9490857412900077 and parameters: {'weight_class_0': 0.0385591306328145, 'weight_class_1': 0.46424359275767135, 'weight_class_2': 0.26526597665393553}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,269] Trial 165 finished with value: 0.9484084175850294 and parameters: {'weight_class_0': 0.041992308943418336, 'weight_class_1': 0.44671793513964975, 'weight_class_2': 0.2299126755709808}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,271] Trial 164 finished with value: 0.9479495985481252 and parameters: {'weight_class_0': 0.03549226082186612, 'weight_class_1': 0.9962278711188868, 'weight_class_2': 0.2047328813948841}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,313] Trial 166 finished with value: 0.9483340050080696 and parameters: {'weight_class_0': 0.023915126137875806, 'weight_class_1': 0.41079962444410467, 'weight_class_2': 0.6444790547169128}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,318] Trial 167 finished with value: 0.9486403431376628 and parameters: {'weight_class_0': 0.03564430005864962, 'weight_class_1': 0.38060427480644166, 'weight_class_2': 0.21162724354259516}. Best is trial 47 with value: 0.9497640908263807.

[I 2026-07-13 11:33:51,350] Trial 168 finished with value: 0.9483830260937255 and parameters: {'weight_class_0': 0.03387089379216595, 'weight_class_1': 0.40510260024416134, 'weight_class_2': 0.750540420753723}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,366] Trial 169 finished with value: 0.9486276112450726 and parameters: {'weight_class_0': 0.03410159049146888, 'weight_class_1': 0.4210016415897578, 'weight_class_2': 0.7221761922347495}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,375] Trial 170 finished with value: 0.9467449607106663 and parameters: {'weight_class_0': 0.024539460061685288, 'weight_class_1': 1.0664030261505983, 'weight_class_2': 0.6900335173423716}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,390] Trial 171 finished with value: 0.9486951417458492 and parameters: {'weight_class_0': 0.11449691990195986, 'weight_class_1': 1.0756429026443242, 'weight_class_2': 0.6983499718067738}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,420] Trial 172 finished with value: 0.9488098432583034 and parameters: {'weight_class_0': 0.11744528366668094, 'weight_class_1': 1.3990155350807751, 'weight_class_2': 0.7149933306049948}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,438] Trial 173 finished with value: 0.948770283283573 and parameters: {'weight_class_0': 0.11442895098705252, 'weight_class_1': 1.4155921994883047, 'weight_class_2': 0.6770263303940763}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,463] Trial 174 finished with value: 0.9490058913604614 and parameters: {'weight_class_0': 0.10891890076400083, 'weight_class_1': 1.4032958643320204, 'weight_class_2': 0.6977597921855845}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,471] Trial 175 finished with value: 0.9447446623752703 and parameters: {'weight_class_0': 0.023437223399153245, 'weight_class_1': 1.3728530396370904, 'weight_class_2': 0.6486975289906873}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,480] Trial 176 finished with value: 0.8991787788378556 and parameters: {'weight_class_0': 0.12384300345839148, 'weight_class_1': 0.06391992448564864, 'weight_class_2': 0.5572681759659487}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,493] Trial 177 finished with value: 0.9484809406592628 and parameters: {'weight_class_0': 0.12110729529103458, 'weight_class_1': 1.0608116054030945, 'weight_class_2': 0.7076422960726286}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,540] Trial 179 finished with value: 0.9480028140018493 and parameters: {'weight_class_0': 0.11825189974106574, 'weight_class_1': 1.4446648084874378, 'weight_class_2': 0.5730750561685706}. Best is trial 47 with value: 0.9497640908263807.

Best trial: 47. Best value: 0.949764:  38%|██████████████████████████████████████████████████▉                                                                                   | 190/500 [00:03<00:05, 53.79it/s]

[I 2026-07-13 11:33:51,541] Trial 178 finished with value: 0.9476091845401861 and parameters: {'weight_class_0': 0.11869964164274802, 'weight_class_1': 1.452790286498808, 'weight_class_2': 0.5362445828195738}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,558] Trial 180 finished with value: 0.94398765172524 and parameters: {'weight_class_0': 0.12089871960809782, 'weight_class_1': 1.3943506286627827, 'weight_class_2': 0.3619697422392991}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,573] Trial 181 finished with value: 0.8858974555758071 and parameters: {'weight_class_0': 0.05686037287785314, 'weight_class_1': 0.012700011377413284, 'weight_class_2': 0.5446378272738422}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,610] Trial 182 finished with value: 0.9496117754145033 and parameters: {'weight_class_0': 0.05892709078978982, 'weight_class_1': 0.9546756258443904, 'weight_class_2': 0.5437808737141266}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,626] Trial 183 finished with value: 0.9486757841230326 and parameters: {'weight_class_0': 0.0910699836158026, 'weight_class_1': 0.9687135497676169, 'weight_class_2': 0.5477005193743935}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,645] Trial 184 finished with value: 0.949052352312456 and parameters: {'weight_class_0': 0.058529282589094844, 'weight_class_1': 0.689925965354181, 'weight_class_2': 0.993817162657867}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,652] Trial 185 finished with value: 0.949162427116634 and parameters: {'weight_class_0': 0.05985626152755526, 'weight_class_1': 0.6830465919406365, 'weight_class_2': 0.9129744426984224}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,691] Trial 187 finished with value: 0.9491816784242131 and parameters: {'weight_class_0': 0.05178457165180109, 'weight_class_1': 0.685523972372582, 'weight_class_2': 0.3681040524147956}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,692] Trial 186 finished with value: 0.8875946133867791 and parameters: {'weight_class_0': 0.056575119275453147, 'weight_class_1': 0.014183919717029762, 'weight_class_2': 0.9394003505375917}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,726] Trial 188 finished with value: 0.9489991689506919 and parameters: {'weight_class_0': 0.060002784730713514, 'weight_class_1': 0.6609100649080444, 'weight_class_2': 0.9986718193191712}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,742] Trial 189 finished with value: 0.9492576024152423 and parameters: {'weight_class_0': 0.09088369175430878, 'weight_class_1': 0.6891081677126042, 'weight_class_2': 0.9355633378827868}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,756] Trial 190 finished with value: 0.9490711181506035 and parameters: {'weight_class_0': 0.05877526848974182, 'weight_class_1': 0.6628331089296585, 'weight_class_2': 0.9667724854952341}. Best is trial 47 with value: 0.9497640908263807.

Best trial: 47. Best value: 0.949764:  40%|██████████████████████████████████████████████████████▏                                                                               | 202/500 [00:03<00:05, 55.68it/s]

[I 2026-07-13 11:33:51,787] Trial 191 finished with value: 0.9490323485002294 and parameters: {'weight_class_0': 0.054859102428637334, 'weight_class_1': 0.6621040720270991, 'weight_class_2': 0.9726151971578283}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,795] Trial 192 finished with value: 0.821233129216008 and parameters: {'weight_class_0': 4.9403884659991295, 'weight_class_1': 0.6505716891426132, 'weight_class_2': 0.9082560069983816}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,808] Trial 193 finished with value: 0.6719277480401847 and parameters: {'weight_class_0': 0.0010607426420186413, 'weight_class_1': 2.0034021327544305, 'weight_class_2': 0.4022892239593238}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,842] Trial 195 finished with value: 0.7310164310503788 and parameters: {'weight_class_0': 3.9452657517328125, 'weight_class_1': 2.035068612314196, 'weight_class_2': 0.02075722462605994}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,844] Trial 194 finished with value: 0.9479474852128881 and parameters: {'weight_class_0': 0.05487893258093457, 'weight_class_1': 1.9916076601842896, 'weight_class_2': 0.39228806722919296}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,880] Trial 197 finished with value: 0.948168162090401 and parameters: {'weight_class_0': 0.07754496392426177, 'weight_class_1': 1.986422287567204, 'weight_class_2': 0.4547152580817637}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,881] Trial 196 finished with value: 0.9478166877879829 and parameters: {'weight_class_0': 0.07829393570833988, 'weight_class_1': 1.9718200827294, 'weight_class_2': 0.4203468647161963}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,918] Trial 199 finished with value: 0.9487797807783811 and parameters: {'weight_class_0': 0.07600470523559251, 'weight_class_1': 0.8678170586256445, 'weight_class_2': 0.4681881184274054}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,931] Trial 198 finished with value: 0.9487005287501683 and parameters: {'weight_class_0': 0.07806654132440695, 'weight_class_1': 0.8805233092222943, 'weight_class_2': 0.45814933670460667}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,941] Trial 200 finished with value: 0.9484698588715154 and parameters: {'weight_class_0': 0.08007713196970676, 'weight_class_1': 0.8329466187449223, 'weight_class_2': 0.45393100616112314}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,962] Trial 201 finished with value: 0.9487555920916129 and parameters: {'weight_class_0': 0.07803648923516827, 'weight_class_1': 0.8701641268463658, 'weight_class_2': 0.47553960645308135}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:51,981] Trial 202 finished with value: 0.9489531123872705 and parameters: {'weight_class_0': 0.07527753489715132, 'weight_class_1': 0.8822350372643253, 'weight_class_2': 0.4875432190565075}. Best is trial 47 with value: 0.9497640908263807.

[I 2026-07-13 11:33:51,984] Trial 203 finished with value: 0.9486665042992525 and parameters: {'weight_class_0': 0.07745592618612654, 'weight_class_1': 0.8482258379387833, 'weight_class_2': 0.4575935666205189}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,021] Trial 204 finished with value: 0.9490458585456182 and parameters: {'weight_class_0': 0.07276744424354989, 'weight_class_1': 0.8991694454464826, 'weight_class_2': 0.4753876979492761}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,044] Trial 205 finished with value: 0.948375199500593 and parameters: {'weight_class_0': 0.09669326286394607, 'weight_class_1': 0.8747942403616346, 'weight_class_2': 0.5347339693672365}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,045] Trial 206 finished with value: 0.9481633165624493 and parameters: {'weight_class_0': 0.09523433775027466, 'weight_class_1': 0.8924928939777896, 'weight_class_2': 0.49338993597010905}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,076] Trial 208 finished with value: 0.948216532000746 and parameters: {'weight_class_0': 0.09636117973550762, 'weight_class_1': 0.9287601293836218, 'weight_class_2': 0.5019427979112999}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,087] Trial 207 finished with value: 0.94901158400544 and parameters: {'weight_class_0': 0.07360912438818716, 'weight_class_1': 0.8613351290202043, 'weight_class_2': 0.4868023019378358}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,110] Trial 209 finished with value: 0.9496177641448437 and parameters: {'weight_class_0': 0.09809532226054342, 'weight_class_1': 1.1873750163774692, 'weight_class_2': 1.1623418276647268}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,124] Trial 210 finished with value: 0.9496070144021221 and parameters: {'weight_class_0': 0.0986108958737851, 'weight_class_1': 1.1633073466442265, 'weight_class_2': 1.1765692169331032}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,155] Trial 212 finished with value: 0.949635529864846 and parameters: {'weight_class_0': 0.09821834439966375, 'weight_class_1': 1.1734341664303871, 'weight_class_2': 1.1572378708896454}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,171] Trial 211 finished with value: 0.9495799452758265 and parameters: {'weight_class_0': 0.09728785074415883, 'weight_class_1': 1.1340464187759334, 'weight_class_2': 1.1520973357114421}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,176] Trial 213 finished with value: 0.9495663274297029 and parameters: {'weight_class_0': 0.10047373868919915, 'weight_class_1': 1.0811877383770065, 'weight_class_2': 1.1675046940947855}. Best is trial 47 with value: 0.9497640908263807.

[I 2026-07-13 11:33:52,198] Trial 214 finished with value: 0.9494713181903109 and parameters: {'weight_class_0': 0.10161119979783453, 'weight_class_1': 1.18353941699272, 'weight_class_2': 0.8299562629388952}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,215] Trial 215 finished with value: 0.9484277005211873 and parameters: {'weight_class_0': 0.047625256745040034, 'weight_class_1': 1.1562171443259694, 'weight_class_2': 1.1389246617198332}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,245] Trial 217 finished with value: 0.9486829295019655 and parameters: {'weight_class_0': 0.049937498685095914, 'weight_class_1': 1.0858349124825124, 'weight_class_2': 1.1114475032401416}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,247] Trial 216 finished with value: 0.9491150554277509 and parameters: {'weight_class_0': 0.06585479201797524, 'weight_class_1': 1.2174903353990998, 'weight_class_2': 1.160680195104244}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,267] Trial 218 finished with value: 0.9488837317136402 and parameters: {'weight_class_0': 0.04852091487381348, 'weight_class_1': 1.216383747504593, 'weight_class_2': 0.838940419581911}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,296] Trial 219 finished with value: 0.9490681422628257 and parameters: {'weight_class_0': 0.10096776247074721, 'weight_class_1': 1.1909054032108477, 'weight_class_2': 1.6967912020414697}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,300] Trial 220 finished with value: 0.9495820235944534 and parameters: {'weight_class_0': 0.06477004606975789, 'weight_class_1': 1.1705548839621946, 'weight_class_2': 0.795001540430404}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,313] Trial 221 finished with value: 0.9496438910248273 and parameters: {'weight_class_0': 0.10384076400237167, 'weight_class_1': 1.192034460917962, 'weight_class_2': 1.1347002004624256}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,340] Trial 222 finished with value: 0.949616354677822 and parameters: {'weight_class_0': 0.09940824420941409, 'weight_class_1': 1.7054030589876734, 'weight_class_2': 1.1613542474681484}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,352] Trial 223 finished with value: 0.9493896692450541 and parameters: {'weight_class_0': 0.13838398932079757, 'weight_class_1': 1.2278542527954406, 'weight_class_2': 1.1751062307358524}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,371] Trial 224 finished with value: 0.949251398049527 and parameters: {'weight_class_0': 0.1405298041653069, 'weight_class_1': 1.1032192031159043, 'weight_class_2': 1.1773078755141537}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,385] Trial 225 finished with value: 0.9493405493989183 and parameters: {'weight_class_0': 0.1365175868304389, 'weight_class_1': 1.269979178337705, 'weight_class_2': 1.6823815812213696}. Best is trial 47 with value: 0.9497640908263807.

Best trial: 47. Best value: 0.949764:  47%|███████████████████████████████████████████████████████████████▌                                                                      | 237/500 [00:04<00:04, 55.41it/s]

[I 2026-07-13 11:33:52,414] Trial 226 finished with value: 0.9492915597474173 and parameters: {'weight_class_0': 0.13677989801612495, 'weight_class_1': 1.2434880371812345, 'weight_class_2': 1.710916602456272}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,441] Trial 227 finished with value: 0.9496186252862246 and parameters: {'weight_class_0': 0.13334725648529264, 'weight_class_1': 1.618487574174762, 'weight_class_2': 1.5855964804302547}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,467] Trial 228 finished with value: 0.9494165479478069 and parameters: {'weight_class_0': 0.17099491746140694, 'weight_class_1': 1.68461198160251, 'weight_class_2': 1.531213835302423}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,483] Trial 229 finished with value: 0.9496740697136598 and parameters: {'weight_class_0': 0.14317397721932357, 'weight_class_1': 1.7230869909653854, 'weight_class_2': 1.5691623806404014}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,493] Trial 230 finished with value: 0.9496398133178814 and parameters: {'weight_class_0': 0.13720120414260636, 'weight_class_1': 1.5343785146550983, 'weight_class_2': 1.5432156579583485}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,512] Trial 231 finished with value: 0.9496274401715673 and parameters: {'weight_class_0': 0.13486714476607153, 'weight_class_1': 1.6321596262760822, 'weight_class_2': 1.558370780974558}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,523] Trial 232 finished with value: 0.949643914874705 and parameters: {'weight_class_0': 0.13725704618387838, 'weight_class_1': 1.6788625658499867, 'weight_class_2': 1.6173078488652408}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,545] Trial 233 finished with value: 0.9494602732622655 and parameters: {'weight_class_0': 0.16851574167794872, 'weight_class_1': 1.582587732499457, 'weight_class_2': 1.5193662413405413}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,558] Trial 235 finished with value: 0.9493107417934188 and parameters: {'weight_class_0': 0.09803093145544182, 'weight_class_1': 1.722411067327788, 'weight_class_2': 1.4565171476298089}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,589] Trial 234 finished with value: 0.9495278093951138 and parameters: {'weight_class_0': 0.10392036825343888, 'weight_class_1': 1.5851062002769154, 'weight_class_2': 1.346478616393804}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,600] Trial 236 finished with value: 0.9494168519075469 and parameters: {'weight_class_0': 0.10538020907348603, 'weight_class_1': 1.7411348345338693, 'weight_class_2': 1.4469677858637016}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,612] Trial 237 finished with value: 0.9494084956663776 and parameters: {'weight_class_0': 0.1621661354912369, 'weight_class_1': 1.6775040107418369, 'weight_class_2': 1.4139810081060602}. Best is trial 47 with value: 0.9497640908263807.

[I 2026-07-13 11:33:52,631] Trial 238 finished with value: 0.9494835127149446 and parameters: {'weight_class_0': 0.10630056743216504, 'weight_class_1': 1.6654727475322013, 'weight_class_2': 1.4004876740231071}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,658] Trial 239 finished with value: 0.9492369953504722 and parameters: {'weight_class_0': 0.18360690662088489, 'weight_class_1': 1.6699265160046024, 'weight_class_2': 1.4157755368724543}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,679] Trial 241 finished with value: 0.9494527258445861 and parameters: {'weight_class_0': 0.15774439928393172, 'weight_class_1': 1.6798790500534035, 'weight_class_2': 1.4748292137378005}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,690] Trial 240 finished with value: 0.9496750072747467 and parameters: {'weight_class_0': 0.1298775633946511, 'weight_class_1': 1.6810767654614274, 'weight_class_2': 1.4287512683005323}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,731] Trial 243 finished with value: 0.9496000479513294 and parameters: {'weight_class_0': 0.17261745076267665, 'weight_class_1': 2.7447122485771325, 'weight_class_2': 1.474284456764309}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,739] Trial 244 finished with value: 0.9495868455581805 and parameters: {'weight_class_0': 0.1673993563890973, 'weight_class_1': 1.710133113349678, 'weight_class_2': 1.7793160317119618}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,746] Trial 242 finished with value: 0.9494999046505206 and parameters: {'weight_class_0': 0.17525467079126983, 'weight_class_1': 1.6705848566328692, 'weight_class_2': 1.9978662289430797}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,759] Trial 245 finished with value: 0.9494958745453858 and parameters: {'weight_class_0': 0.15608672511937374, 'weight_class_1': 2.511669489370591, 'weight_class_2': 2.0445200494540616}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,801] Trial 246 finished with value: 0.9493372572254457 and parameters: {'weight_class_0': 0.12793463408822284, 'weight_class_1': 2.340713240932908, 'weight_class_2': 1.8594652333268054}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,818] Trial 247 finished with value: 0.9492052932940437 and parameters: {'weight_class_0': 0.1308691496404988, 'weight_class_1': 2.5502206562890204, 'weight_class_2': 2.077822007109721}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,824] Trial 248 finished with value: 0.9492609942975668 and parameters: {'weight_class_0': 0.1320636145461104, 'weight_class_1': 2.5431299759876316, 'weight_class_2': 2.0149205559018784}. Best is trial 47 with value: 0.9497640908263807.

Best trial: 47. Best value: 0.949764:  52%|█████████████████████████████████████████████████████████████████████▍                                                                | 259/500 [00:04<00:04, 51.66it/s]

[I 2026-07-13 11:33:52,842] Trial 249 finished with value: 0.9494095172700773 and parameters: {'weight_class_0': 0.14848852578295269, 'weight_class_1': 2.7253752749011233, 'weight_class_2': 2.0845776797561846}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,860] Trial 250 finished with value: 0.9493502971162361 and parameters: {'weight_class_0': 0.13419004604907392, 'weight_class_1': 2.74946392930065, 'weight_class_2': 1.9086930612659263}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,878] Trial 251 finished with value: 0.9492719220249088 and parameters: {'weight_class_0': 0.13072205714250745, 'weight_class_1': 2.5518027551423286, 'weight_class_2': 1.968826733332026}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,908] Trial 252 finished with value: 0.9497096679973273 and parameters: {'weight_class_0': 0.2089225776870013, 'weight_class_1': 2.659234681036728, 'weight_class_2': 2.0303604539058866}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,949] Trial 253 finished with value: 0.9488249399705312 and parameters: {'weight_class_0': 0.12787724972168119, 'weight_class_1': 2.906451724517966, 'weight_class_2': 2.501667278433795}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,958] Trial 254 finished with value: 0.949609807722851 and parameters: {'weight_class_0': 0.21985028174568705, 'weight_class_1': 2.434095078833496, 'weight_class_2': 2.351971190907392}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,959] Trial 255 finished with value: 0.9487782499813711 and parameters: {'weight_class_0': 0.1247165128096157, 'weight_class_1': 2.8766191740487437, 'weight_class_2': 2.456013379681448}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,959] Trial 256 finished with value: 0.9489493313057333 and parameters: {'weight_class_0': 0.12573370748381396, 'weight_class_1': 2.8140061388121924, 'weight_class_2': 2.321530562105075}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:52,974] Trial 257 finished with value: 0.9493959675088902 and parameters: {'weight_class_0': 0.209526141298364, 'weight_class_1': 2.156660102694615, 'weight_class_2': 1.7613231949121888}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,040] Trial 259 finished with value: 0.9494260244971074 and parameters: {'weight_class_0': 0.20851034030444074, 'weight_class_1': 2.126203641704458, 'weight_class_2': 2.5562136063855463}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,063] Trial 258 finished with value: 0.9492738091776798 and parameters: {'weight_class_0': 0.18922558543427573, 'weight_class_1': 2.174642000661508, 'weight_class_2': 2.723359821435743}. Best is trial 47 with value: 0.9497640908263807.

[I 2026-07-13 11:33:53,072] Trial 260 finished with value: 0.949088508058161 and parameters: {'weight_class_0': 0.1756017675440867, 'weight_class_1': 2.0340960203901366, 'weight_class_2': 2.841616450290518}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,078] Trial 261 finished with value: 0.949204697197172 and parameters: {'weight_class_0': 0.1936915750805365, 'weight_class_1': 2.0007269871053475, 'weight_class_2': 2.6276510605391676}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,083] Trial 262 finished with value: 0.9492414582818043 and parameters: {'weight_class_0': 0.1753643951927087, 'weight_class_1': 2.08743172988481, 'weight_class_2': 2.660613929440826}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,085] Trial 263 finished with value: 0.9490167329433796 and parameters: {'weight_class_0': 0.21752455182482688, 'weight_class_1': 2.0825709526788874, 'weight_class_2': 1.532232622220265}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,137] Trial 264 finished with value: 0.9490504853185268 and parameters: {'weight_class_0': 0.22810414997333928, 'weight_class_1': 2.1056505049729246, 'weight_class_2': 1.640909106876519}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,156] Trial 266 finished with value: 0.9481915427224609 and parameters: {'weight_class_0': 0.22235125940535305, 'weight_class_1': 2.076598332399012, 'weight_class_2': 1.1764770502485902}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,161] Trial 265 finished with value: 0.9493131607977747 and parameters: {'weight_class_0': 0.22696625574949664, 'weight_class_1': 2.005888055026862, 'weight_class_2': 2.7813779754694217}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,176] Trial 267 finished with value: 0.9492598043755204 and parameters: {'weight_class_0': 0.22490839416147065, 'weight_class_1': 2.1695871673508402, 'weight_class_2': 2.9619834807905865}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,178] Trial 268 finished with value: 0.948443599069661 and parameters: {'weight_class_0': 0.19717959050992354, 'weight_class_1': 2.109026976650543, 'weight_class_2': 1.0852979488380396}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,214] Trial 269 finished with value: 0.947836992450856 and parameters: {'weight_class_0': 0.20908577574647674, 'weight_class_1': 1.3661924838525181, 'weight_class_2': 1.1960750505494493}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,238] Trial 271 finished with value: 0.946898723874457 and parameters: {'weight_class_0': 0.24279456362633017, 'weight_class_1': 1.4144322739358286, 'weight_class_2': 1.1720868238538809}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,251] Trial 270 finished with value: 0.9481902003389383 and parameters: {'weight_class_0': 0.08832769468046887, 'weight_class_1': 3.429379617266598, 'weight_class_2': 1.1537824521921884}. Best is trial 47 with value: 0.9497640908263807.

[I 2026-07-13 11:33:53,265] Trial 272 finished with value: 0.9458582632562486 and parameters: {'weight_class_0': 0.2661802884476941, 'weight_class_1': 1.424444879933427, 'weight_class_2': 1.098668623910698}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,287] Trial 273 finished with value: 0.9463822582186484 and parameters: {'weight_class_0': 0.2513269560265185, 'weight_class_1': 1.4261898522301435, 'weight_class_2': 1.1046258623716116}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,299] Trial 274 finished with value: 0.9463267756675012 and parameters: {'weight_class_0': 0.25863940990896156, 'weight_class_1': 1.380932146691382, 'weight_class_2': 1.1778497086897035}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,315] Trial 275 finished with value: 0.9496912315184608 and parameters: {'weight_class_0': 0.11103738590076638, 'weight_class_1': 1.418814584763005, 'weight_class_2': 1.1735100077000706}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,347] Trial 277 finished with value: 0.9496839868911282 and parameters: {'weight_class_0': 0.10974822740840062, 'weight_class_1': 1.3631097200835494, 'weight_class_2': 1.209313356089095}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,357] Trial 276 finished with value: 0.949566540140428 and parameters: {'weight_class_0': 0.10860824817223377, 'weight_class_1': 1.4510318599599445, 'weight_class_2': 1.2935661893160952}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,382] Trial 278 finished with value: 0.9496105684841382 and parameters: {'weight_class_0': 0.10973015257673382, 'weight_class_1': 1.40832991555025, 'weight_class_2': 1.3046278542840646}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,400] Trial 279 finished with value: 0.9488716813495511 and parameters: {'weight_class_0': 0.10556961859425427, 'weight_class_1': 3.3514391681454248, 'weight_class_2': 1.281343356230669}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,419] Trial 280 finished with value: 0.9484245106732314 and parameters: {'weight_class_0': 0.10933875820562951, 'weight_class_1': 3.797883021564983, 'weight_class_2': 1.7191493750964832}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,444] Trial 281 finished with value: 0.9495161827439663 and parameters: {'weight_class_0': 0.11182715379563019, 'weight_class_1': 1.4591183600929019, 'weight_class_2': 1.4700034499199015}. Best is trial 47 with value: 0.9497640908263807.

Best trial: 47. Best value: 0.949764:  59%|██████████████████████████████████████████████████████████████████████████████▌                                                       | 293/500 [00:05<00:04, 51.03it/s]

[I 2026-07-13 11:33:53,500] Trial 283 finished with value: 0.9489538299191947 and parameters: {'weight_class_0': 0.10862801222701222, 'weight_class_1': 1.0118344803105688, 'weight_class_2': 1.678343808331686}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,509] Trial 284 finished with value: 0.9495039694296934 and parameters: {'weight_class_0': 0.10970804139082213, 'weight_class_1': 1.462848390456631, 'weight_class_2': 0.8860666731019664}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,517] Trial 282 finished with value: 0.9489472599546035 and parameters: {'weight_class_0': 0.09871776521365833, 'weight_class_1': 1.0080239830058098, 'weight_class_2': 1.6182073646696282}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,528] Trial 285 finished with value: 0.9494797112545431 and parameters: {'weight_class_0': 0.1089586084396015, 'weight_class_1': 1.4531846603798508, 'weight_class_2': 0.8759917051649582}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,533] Trial 286 finished with value: 0.9494385379613943 and parameters: {'weight_class_0': 0.1069358979467059, 'weight_class_1': 1.0263487791215287, 'weight_class_2': 0.9370059146666805}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,561] Trial 287 finished with value: 0.9493066733613743 and parameters: {'weight_class_0': 0.10855122817368633, 'weight_class_1': 1.022503265968313, 'weight_class_2': 0.8551146825085546}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,606] Trial 289 finished with value: 0.949684580276657 and parameters: {'weight_class_0': 0.0876277720288463, 'weight_class_1': 1.5078984259444765, 'weight_class_2': 0.9302615027500809}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,617] Trial 288 finished with value: 0.9376558667771843 and parameters: {'weight_class_0': 0.012486498174102396, 'weight_class_1': 1.0389935962119945, 'weight_class_2': 0.862217748360591}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,619] Trial 290 finished with value: 0.9496340140810614 and parameters: {'weight_class_0': 0.0896343238383728, 'weight_class_1': 1.052075860321237, 'weight_class_2': 0.9352783309004852}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,635] Trial 291 finished with value: 0.9497610005312932 and parameters: {'weight_class_0': 0.0900012893774582, 'weight_class_1': 1.3281583161768784, 'weight_class_2': 0.886881469456648}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,650] Trial 292 finished with value: 0.9495943387815652 and parameters: {'weight_class_0': 0.09224360650254083, 'weight_class_1': 0.9944407593169122, 'weight_class_2': 0.9008121063082699}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,675] Trial 293 finished with value: 0.9497088124586273 and parameters: {'weight_class_0': 0.09393212826760447, 'weight_class_1': 1.3393340202484496, 'weight_class_2': 0.9795680842167498}. Best is trial 47 with value: 0.9497640908263807.

Best trial: 47. Best value: 0.949764:  61%|█████████████████████████████████████████████████████████████████████████████████▋                                                    | 305/500 [00:05<00:03, 55.56it/s]

[I 2026-07-13 11:33:53,691] Trial 294 finished with value: 0.9496386171040275 and parameters: {'weight_class_0': 0.0862926245825858, 'weight_class_1': 1.2502111710520964, 'weight_class_2': 1.0005003393252665}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,703] Trial 295 finished with value: 0.9496044554572025 and parameters: {'weight_class_0': 0.14572679202880226, 'weight_class_1': 1.748479673496022, 'weight_class_2': 1.3345420966124506}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,745] Trial 297 finished with value: 0.9496474025624092 and parameters: {'weight_class_0': 0.08438027998464391, 'weight_class_1': 1.754012643698673, 'weight_class_2': 0.9580748049024834}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,760] Trial 296 finished with value: 0.9489769832979947 and parameters: {'weight_class_0': 0.15325317764491125, 'weight_class_1': 1.7415771798500155, 'weight_class_2': 1.0033248005669673}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,782] Trial 298 finished with value: 0.9490706544423989 and parameters: {'weight_class_0': 0.14792884411906096, 'weight_class_1': 1.7222311686593952, 'weight_class_2': 1.0237543549628152}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,788] Trial 299 finished with value: 0.9495761485469938 and parameters: {'weight_class_0': 0.08627049193027708, 'weight_class_1': 1.7560187500683888, 'weight_class_2': 1.0205103342090827}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,819] Trial 300 finished with value: 0.9494964417857329 and parameters: {'weight_class_0': 0.08622751835182019, 'weight_class_1': 1.7236827769896033, 'weight_class_2': 0.738709916159958}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,831] Trial 301 finished with value: 0.9494736283510038 and parameters: {'weight_class_0': 0.0881469028466209, 'weight_class_1': 1.7425180756721965, 'weight_class_2': 0.7283414153378234}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,853] Trial 302 finished with value: 0.9495108638883455 and parameters: {'weight_class_0': 0.08189529822871255, 'weight_class_1': 1.7401263305417025, 'weight_class_2': 0.7571295973256621}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,867] Trial 303 finished with value: 0.8710215702532819 and parameters: {'weight_class_0': 0.08082827380223637, 'weight_class_1': 0.005024392508897243, 'weight_class_2': 0.7653868541775303}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,885] Trial 304 finished with value: 0.9496295429361062 and parameters: {'weight_class_0': 0.08371364312807719, 'weight_class_1': 1.2613278608420724, 'weight_class_2': 0.7598543854821885}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,897] Trial 305 finished with value: 0.9496096539423761 and parameters: {'weight_class_0': 0.08416973411958949, 'weight_class_1': 1.235147002555628, 'weight_class_2': 0.7547171731995805}. Best is trial 47 with value: 0.9497640908263807.

[I 2026-07-13 11:33:53,915] Trial 306 finished with value: 0.949749103980991 and parameters: {'weight_class_0': 0.07806822645620828, 'weight_class_1': 1.2660167854307478, 'weight_class_2': 0.7815810236815657}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,951] Trial 308 finished with value: 0.9497458207488977 and parameters: {'weight_class_0': 0.07897161330597834, 'weight_class_1': 1.2916537440912064, 'weight_class_2': 0.8010798145033425}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,959] Trial 307 finished with value: 0.9497511264711518 and parameters: {'weight_class_0': 0.08162272110866574, 'weight_class_1': 1.306454573457527, 'weight_class_2': 0.8419501980331008}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,975] Trial 309 finished with value: 0.9496051971281743 and parameters: {'weight_class_0': 0.08344925155446282, 'weight_class_1': 1.2894834728011317, 'weight_class_2': 0.7482449254296875}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,976] Trial 310 finished with value: 0.9496998423898297 and parameters: {'weight_class_0': 0.07221477709011409, 'weight_class_1': 1.2595174488312442, 'weight_class_2': 0.7633082659964996}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:53,994] Trial 311 finished with value: 0.9497008023075839 and parameters: {'weight_class_0': 0.07041513975771008, 'weight_class_1': 1.3949045750185962, 'weight_class_2': 0.7723409991054211}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,003] Trial 312 finished with value: 0.9493749824478132 and parameters: {'weight_class_0': 0.0689900611784759, 'weight_class_1': 1.3301553755590847, 'weight_class_2': 0.9779325157730262}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,053] Trial 314 finished with value: 0.9495698271577089 and parameters: {'weight_class_0': 0.06638099261274416, 'weight_class_1': 1.3431584122935774, 'weight_class_2': 0.6040144233502457}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,055] Trial 313 finished with value: 0.9494124367174613 and parameters: {'weight_class_0': 0.06785956560971197, 'weight_class_1': 1.2873440986695768, 'weight_class_2': 0.9540296298586345}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,069] Trial 315 finished with value: 0.9495938004480071 and parameters: {'weight_class_0': 0.06606387165739157, 'weight_class_1': 1.3063175033336603, 'weight_class_2': 0.6194460219546132}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,081] Trial 316 finished with value: 0.9494239904493075 and parameters: {'weight_class_0': 0.0718063446821778, 'weight_class_1': 1.3376687665484182, 'weight_class_2': 0.975594433049842}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,096] Trial 317 finished with value: 0.9495278216617544 and parameters: {'weight_class_0': 0.07218791825156694, 'weight_class_1': 1.3236796787680383, 'weight_class_2': 0.9388117556820799}. Best is trial 47 with value: 0.9497640908263807.

[I 2026-07-13 11:33:54,133] Trial 318 finished with value: 0.9290405522736038 and parameters: {'weight_class_0': 0.06842448897051019, 'weight_class_1': 0.10225673995379672, 'weight_class_2': 0.9320097774248883}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,143] Trial 320 finished with value: 0.9495713956141182 and parameters: {'weight_class_0': 0.06473051144974899, 'weight_class_1': 1.3276449880629209, 'weight_class_2': 0.6068046719420905}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,144] Trial 319 finished with value: 0.9494078670919571 and parameters: {'weight_class_0': 0.06928217517122236, 'weight_class_1': 1.309051693685613, 'weight_class_2': 0.9640351418769851}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,168] Trial 321 finished with value: 0.9493568574637585 and parameters: {'weight_class_0': 0.06421078923580073, 'weight_class_1': 1.3052236831207569, 'weight_class_2': 0.8943758108118414}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,181] Trial 322 finished with value: 0.9495498353732179 and parameters: {'weight_class_0': 0.06454874512356826, 'weight_class_1': 1.3709532301950007, 'weight_class_2': 0.6106634988421452}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,203] Trial 324 finished with value: 0.9497565089548138 and parameters: {'weight_class_0': 0.066881318832343, 'weight_class_1': 1.343333090998373, 'weight_class_2': 0.6701198852237124}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,209] Trial 323 finished with value: 0.9390415528972601 and parameters: {'weight_class_0': 0.06225223065587612, 'weight_class_1': 0.13384868113263151, 'weight_class_2': 0.6249453964676699}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,240] Trial 325 finished with value: 0.9490096140368337 and parameters: {'weight_class_0': 0.057773228539982596, 'weight_class_1': 1.5114943846841762, 'weight_class_2': 0.8496450453614843}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,267] Trial 328 finished with value: 0.9488752126921728 and parameters: {'weight_class_0': 0.05370786859518415, 'weight_class_1': 1.525709367134093, 'weight_class_2': 0.8124851774162408}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,270] Trial 326 finished with value: 0.9492270198050715 and parameters: {'weight_class_0': 0.05539541968140815, 'weight_class_1': 1.5028837306693288, 'weight_class_2': 0.6536520697038106}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,272] Trial 327 finished with value: 0.9490284154852301 and parameters: {'weight_class_0': 0.05661552719601514, 'weight_class_1': 1.527071395331293, 'weight_class_2': 0.8137152220167442}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,299] Trial 329 finished with value: 0.9492979468385608 and parameters: {'weight_class_0': 0.0577264636141406, 'weight_class_1': 1.518456959421075, 'weight_class_2': 0.6271622297543102}. Best is trial 47 with value: 0.9497640908263807.

[I 2026-07-13 11:33:54,319] Trial 330 finished with value: 0.9487530185369408 and parameters: {'weight_class_0': 0.05266425790996771, 'weight_class_1': 1.5360766627642148, 'weight_class_2': 0.8381334269407686}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,342] Trial 331 finished with value: 0.9490935552068382 and parameters: {'weight_class_0': 0.05428687989076144, 'weight_class_1': 1.5558624251492195, 'weight_class_2': 0.6515730562517635}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,369] Trial 332 finished with value: 0.8014478253654992 and parameters: {'weight_class_0': 0.003088106962333901, 'weight_class_1': 1.0200051933232885, 'weight_class_2': 0.7883760648319756}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,378] Trial 333 finished with value: 0.948398786421246 and parameters: {'weight_class_0': 0.05209109477040188, 'weight_class_1': 1.8549786889892605, 'weight_class_2': 0.7736590272990781}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,395] Trial 334 finished with value: 0.8848046567222743 and parameters: {'weight_class_0': 0.04809748194502158, 'weight_class_1': 1.6077085587726192, 'weight_class_2': 0.009141525707070802}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,415] Trial 336 finished with value: 0.9486078863468469 and parameters: {'weight_class_0': 0.05585862363147157, 'weight_class_1': 1.8807158525373673, 'weight_class_2': 0.7788397383746084}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,428] Trial 335 finished with value: 0.9490095589250828 and parameters: {'weight_class_0': 0.053840810427740325, 'weight_class_1': 1.5579365808023278, 'weight_class_2': 0.7115496065191479}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,432] Trial 337 finished with value: 0.9481757362627938 and parameters: {'weight_class_0': 0.049943207369292836, 'weight_class_1': 1.8813155871830556, 'weight_class_2': 0.7624986254258571}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,447] Trial 338 finished with value: 0.9444178736023089 and parameters: {'weight_class_0': 0.030455199592319727, 'weight_class_1': 1.9017528146727636, 'weight_class_2': 0.712325502063639}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,490] Trial 340 finished with value: 0.9472034409739524 and parameters: {'weight_class_0': 0.04047007910843316, 'weight_class_1': 1.8503567024165166, 'weight_class_2': 0.7094612266411388}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,492] Trial 339 finished with value: 0.947017328226509 and parameters: {'weight_class_0': 0.04344970997781494, 'weight_class_1': 2.0301295974427456, 'weight_class_2': 0.331055884661991}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,513] Trial 341 finished with value: 0.8688282296861626 and parameters: {'weight_class_0': 0.04452353135312512, 'weight_class_1': 1.9806977005461006, 'weight_class_2': 0.007370495729129423}. Best is trial 47 with value: 0.9497640908263807.

Best trial: 47. Best value: 0.949764:  70%|██████████████████████████████████████████████████████████████████████████████████████████████▎                                       | 352/500 [00:06<00:02, 56.55it/s]

[I 2026-07-13 11:33:54,517] Trial 342 finished with value: 0.9465099619176076 and parameters: {'weight_class_0': 0.03926698488747027, 'weight_class_1': 1.9502982387712027, 'weight_class_2': 0.7806170359954304}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,562] Trial 343 finished with value: 0.9497420038713326 and parameters: {'weight_class_0': 0.12321472960890202, 'weight_class_1': 1.9309311431100897, 'weight_class_2': 1.220469927729416}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,569] Trial 344 finished with value: 0.9487253001300266 and parameters: {'weight_class_0': 0.08101534704953185, 'weight_class_1': 0.756906476612388, 'weight_class_2': 1.3511929074148692}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,586] Trial 345 finished with value: 0.948039498691314 and parameters: {'weight_class_0': 0.04192291094426876, 'weight_class_1': 0.7822144622358762, 'weight_class_2': 1.3068785580274793}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,610] Trial 347 finished with value: 0.9488742912817284 and parameters: {'weight_class_0': 0.11958263712467591, 'weight_class_1': 0.7871876606634179, 'weight_class_2': 1.3642364338996458}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,626] Trial 346 finished with value: 0.8415509932515869 and parameters: {'weight_class_0': 0.12092454077210976, 'weight_class_1': 0.7679288610070231, 'weight_class_2': 0.002061704462877643}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,645] Trial 348 finished with value: 0.9403903010261946 and parameters: {'weight_class_0': 0.12370812599480704, 'weight_class_1': 0.7691813153871286, 'weight_class_2': 0.31340249905376427}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,673] Trial 349 finished with value: 0.948089418055122 and parameters: {'weight_class_0': 0.041453536386498985, 'weight_class_1': 0.7211142546403426, 'weight_class_2': 1.2234107398716059}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,680] Trial 351 finished with value: 0.9482682244839693 and parameters: {'weight_class_0': 0.0776093389597598, 'weight_class_1': 0.5349834885004132, 'weight_class_2': 1.2769675308224184}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,683] Trial 350 finished with value: 0.9492296693257121 and parameters: {'weight_class_0': 0.1240921298387655, 'weight_class_1': 0.9171823972178926, 'weight_class_2': 1.3071713908297142}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,705] Trial 352 finished with value: 0.9488484405946975 and parameters: {'weight_class_0': 0.12236323505449039, 'weight_class_1': 0.778725142783443, 'weight_class_2': 1.3000619870322627}. Best is trial 47 with value: 0.9497640908263807.

Best trial: 47. Best value: 0.949764:  73%|█████████████████████████████████████████████████████████████████████████████████████████████████▊                                    | 365/500 [00:06<00:02, 55.51it/s]

[I 2026-07-13 11:33:54,765] Trial 354 finished with value: 0.9493223354737189 and parameters: {'weight_class_0': 0.1227113473238718, 'weight_class_1': 1.005793343237626, 'weight_class_2': 1.0797494171851716}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,767] Trial 353 finished with value: 0.949224320542179 and parameters: {'weight_class_0': 0.09119704455498123, 'weight_class_1': 2.379939514975489, 'weight_class_2': 1.1547884685714402}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,775] Trial 355 finished with value: 0.8861884223232863 and parameters: {'weight_class_0': 0.12001948339457677, 'weight_class_1': 0.02732394589814724, 'weight_class_2': 1.052563254858256}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,786] Trial 356 finished with value: 0.829616724595016 and parameters: {'weight_class_0': 8.42109752619223, 'weight_class_1': 2.335604751287788, 'weight_class_2': 1.0746612544041103}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,805] Trial 357 finished with value: 0.9482727067927955 and parameters: {'weight_class_0': 0.09344271906707863, 'weight_class_1': 0.5227269434616901, 'weight_class_2': 1.135337057255564}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,825] Trial 358 finished with value: 0.9494004935209683 and parameters: {'weight_class_0': 0.09357770572498723, 'weight_class_1': 2.3001747738364515, 'weight_class_2': 1.0884784957646627}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,834] Trial 359 finished with value: 0.9492369403801478 and parameters: {'weight_class_0': 0.08888777849870486, 'weight_class_1': 2.3636130338172574, 'weight_class_2': 1.070146847326728}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,871] Trial 360 finished with value: 0.9493159448735868 and parameters: {'weight_class_0': 0.08795700970407776, 'weight_class_1': 2.314216941856691, 'weight_class_2': 1.000351917731694}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,884] Trial 361 finished with value: 0.9492162155263536 and parameters: {'weight_class_0': 0.08854848250455939, 'weight_class_1': 2.417588415148051, 'weight_class_2': 1.029299116701106}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,895] Trial 363 finished with value: 0.9493836038947325 and parameters: {'weight_class_0': 0.09405729699873104, 'weight_class_1': 2.3805936747156307, 'weight_class_2': 1.0618731480125867}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,898] Trial 362 finished with value: 0.9495775805429639 and parameters: {'weight_class_0': 0.09154880273232537, 'weight_class_1': 1.0681401110921893, 'weight_class_2': 1.0899399024752214}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,909] Trial 364 finished with value: 0.949294725649542 and parameters: {'weight_class_0': 0.08914670421352912, 'weight_class_1': 2.3352492949364194, 'weight_class_2': 1.051741226731572}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,944] Trial 365 finished with value: 0.8564115653654217 and parameters: {'weight_class_0': 1.4201645480504166, 'weight_class_1': 1.11934417131842, 'weight_class_2': 0.5367629155746834}. Best is trial 47 with value: 0.9497640908263807.

Best trial: 47. Best value: 0.949764:  75%|█████████████████████████████████████████████████████████████████████████████████████████████████████                                 | 377/500 [00:06<00:02, 56.01it/s]

[I 2026-07-13 11:33:54,986] Trial 366 finished with value: 0.9490996406233753 and parameters: {'weight_class_0': 0.07880429730934407, 'weight_class_1': 1.0984978989771514, 'weight_class_2': 0.5357861730807799}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,990] Trial 367 finished with value: 0.9491537222994646 and parameters: {'weight_class_0': 0.08162071947527519, 'weight_class_1': 1.0733561009406207, 'weight_class_2': 0.5639279666688838}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:54,997] Trial 368 finished with value: 0.949313323962791 and parameters: {'weight_class_0': 0.07743266290586692, 'weight_class_1': 1.0611007754738915, 'weight_class_2': 0.5669456648426817}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,009] Trial 369 finished with value: 0.9495088831328117 and parameters: {'weight_class_0': 0.07054552868481635, 'weight_class_1': 1.1194997164490503, 'weight_class_2': 0.5601925361921386}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,037] Trial 370 finished with value: 0.9495020441198984 and parameters: {'weight_class_0': 0.07179960428962914, 'weight_class_1': 1.0980031188598969, 'weight_class_2': 0.575362210474593}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,067] Trial 371 finished with value: 0.9495116297947837 and parameters: {'weight_class_0': 0.07313813433441234, 'weight_class_1': 1.0913924932180004, 'weight_class_2': 0.5791583043297395}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,075] Trial 372 finished with value: 0.9494261552438895 and parameters: {'weight_class_0': 0.0744139878743273, 'weight_class_1': 1.1055864859225237, 'weight_class_2': 0.5588859306008505}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,089] Trial 373 finished with value: 0.9494957263545603 and parameters: {'weight_class_0': 0.07354260154718287, 'weight_class_1': 1.135780843291619, 'weight_class_2': 0.5698959020920089}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,108] Trial 374 finished with value: 0.9458590463916213 and parameters: {'weight_class_0': 0.1551094797664479, 'weight_class_1': 1.141793081159069, 'weight_class_2': 0.5709171487635114}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,131] Trial 375 finished with value: 0.9493809099951503 and parameters: {'weight_class_0': 0.07468439158278005, 'weight_class_1': 1.095277004855088, 'weight_class_2': 0.5492284553217348}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,145] Trial 376 finished with value: 0.9495776013905274 and parameters: {'weight_class_0': 0.07176849855702497, 'weight_class_1': 1.0941856221752275, 'weight_class_2': 0.6156335609614304}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,157] Trial 377 finished with value: 0.9494938579581168 and parameters: {'weight_class_0': 0.07221243227035865, 'weight_class_1': 1.115105258803212, 'weight_class_2': 0.5771737691586101}. Best is trial 47 with value: 0.9497640908263807.

Best trial: 47. Best value: 0.949764:  78%|████████████████████████████████████████████████████████████████████████████████████████████████████████▎                             | 389/500 [00:07<00:02, 53.72it/s]

[I 2026-07-13 11:33:55,195] Trial 379 finished with value: 0.9496452846268594 and parameters: {'weight_class_0': 0.16166650252124107, 'weight_class_1': 1.7971473170054235, 'weight_class_2': 1.6773778252938158}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,206] Trial 378 finished with value: 0.9495472680070908 and parameters: {'weight_class_0': 0.1391524748451518, 'weight_class_1': 1.8475136420480456, 'weight_class_2': 1.7299695145781462}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,224] Trial 380 finished with value: 0.9494189296171075 and parameters: {'weight_class_0': 0.14212501114598522, 'weight_class_1': 3.1039715318905023, 'weight_class_2': 1.8737490811618076}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,235] Trial 381 finished with value: 0.9496788305411932 and parameters: {'weight_class_0': 0.15121545405049305, 'weight_class_1': 3.0076651088309534, 'weight_class_2': 1.684268485660371}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,265] Trial 382 finished with value: 0.9496685067652257 and parameters: {'weight_class_0': 0.1546917794327022, 'weight_class_1': 1.7489006115505394, 'weight_class_2': 1.7142043595860594}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,274] Trial 383 finished with value: 0.9496569156596945 and parameters: {'weight_class_0': 0.15327222437297258, 'weight_class_1': 3.141386198150008, 'weight_class_2': 1.633770753647781}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,327] Trial 385 finished with value: 0.9480693184950288 and parameters: {'weight_class_0': 0.14934709961685844, 'weight_class_1': 3.115413797054449, 'weight_class_2': 0.79701674708488}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,329] Trial 384 finished with value: 0.9495763925195918 and parameters: {'weight_class_0': 0.15251002700625205, 'weight_class_1': 3.2736921330421285, 'weight_class_2': 1.7959087441604282}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,332] Trial 386 finished with value: 0.9496079329013533 and parameters: {'weight_class_0': 0.15060317021009126, 'weight_class_1': 1.7710228362126725, 'weight_class_2': 1.7744235461764208}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,350] Trial 387 finished with value: 0.9496389801407009 and parameters: {'weight_class_0': 0.15451772139829112, 'weight_class_1': 3.0002947750150817, 'weight_class_2': 1.781472934017539}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,364] Trial 388 finished with value: 0.9461322470050503 and parameters: {'weight_class_0': 0.10256649859937769, 'weight_class_1': 1.7778197904388149, 'weight_class_2': 0.37384893190102897}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,368] Trial 389 finished with value: 0.9493727559132283 and parameters: {'weight_class_0': 0.16025829204443054, 'weight_class_1': 1.7028822610031147, 'weight_class_2': 2.0343764493034344}. Best is trial 47 with value: 0.9497640908263807.

Best trial: 47. Best value: 0.949764:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▍                          | 401/500 [00:07<00:01, 56.18it/s]

[I 2026-07-13 11:33:55,407] Trial 391 finished with value: 0.937694719772304 and parameters: {'weight_class_0': 0.16697331889657038, 'weight_class_1': 0.3396408896391572, 'weight_class_2': 1.9511785505368775}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,416] Trial 392 finished with value: 0.9495969916168919 and parameters: {'weight_class_0': 0.1804948287475152, 'weight_class_1': 3.2450488363553975, 'weight_class_2': 2.1339382094468933}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,417] Trial 390 finished with value: 0.9484015279038237 and parameters: {'weight_class_0': 0.14430697943527462, 'weight_class_1': 3.188507194081656, 'weight_class_2': 0.8391321608101776}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,432] Trial 393 finished with value: 0.9360283934959828 and parameters: {'weight_class_0': 0.17863464195556478, 'weight_class_1': 3.09963373976299, 'weight_class_2': 0.36871399263626614}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,463] Trial 394 finished with value: 0.9496839332031031 and parameters: {'weight_class_0': 0.16414263148899932, 'weight_class_1': 2.933254757733662, 'weight_class_2': 1.8315024548563226}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,488] Trial 395 finished with value: 0.9494677761823741 and parameters: {'weight_class_0': 0.17511954821111175, 'weight_class_1': 3.7839022908774598, 'weight_class_2': 2.206427406376913}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,521] Trial 396 finished with value: 0.9496827281202164 and parameters: {'weight_class_0': 0.18106831698727846, 'weight_class_1': 3.3178031360156863, 'weight_class_2': 2.073916998636266}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,528] Trial 397 finished with value: 0.8862486651180914 and parameters: {'weight_class_0': 0.18016041424596704, 'weight_class_1': 3.9141400975414293, 'weight_class_2': 0.024687785337020686}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,541] Trial 398 finished with value: 0.9495416423008578 and parameters: {'weight_class_0': 0.18141176079524143, 'weight_class_1': 3.953894895023154, 'weight_class_2': 2.1885246999129877}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,567] Trial 399 finished with value: 0.9487255302009426 and parameters: {'weight_class_0': 0.11072865755097493, 'weight_class_1': 2.6836294411829864, 'weight_class_2': 2.1769436011215317}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,578] Trial 400 finished with value: 0.9495467925182353 and parameters: {'weight_class_0': 0.1738300754542901, 'weight_class_1': 3.131907025054599, 'weight_class_2': 1.4913642104928255}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,615] Trial 402 finished with value: 0.9481750890246721 and parameters: {'weight_class_0': 0.10604651075373614, 'weight_class_1': 4.087664751723775, 'weight_class_2': 1.4776070694635406}. Best is trial 47 with value: 0.9497640908263807.

Best trial: 47. Best value: 0.949764:  83%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                       | 413/500 [00:07<00:01, 55.67it/s]

[I 2026-07-13 11:33:55,619] Trial 401 finished with value: 0.8841830079788998 and parameters: {'weight_class_0': 0.11777211879279278, 'weight_class_1': 4.100111784617262, 'weight_class_2': 0.0226493498119486}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,650] Trial 403 finished with value: 0.9494714070127658 and parameters: {'weight_class_0': 0.1898158873128398, 'weight_class_1': 3.637245738551649, 'weight_class_2': 1.5406806750571151}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,660] Trial 405 finished with value: 0.9155096208523564 and parameters: {'weight_class_0': 0.03354909191820404, 'weight_class_1': 4.991110342918679, 'weight_class_2': 1.570875960006032}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,675] Trial 404 finished with value: 0.9494670235372314 and parameters: {'weight_class_0': 0.19157768817187032, 'weight_class_1': 4.201471172930588, 'weight_class_2': 2.418069034967917}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,692] Trial 406 finished with value: 0.9287931873850567 and parameters: {'weight_class_0': 0.03236247783180765, 'weight_class_1': 3.731290298148439, 'weight_class_2': 1.5682371622190752}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,714] Trial 408 finished with value: 0.897298681864802 and parameters: {'weight_class_0': 0.19575759869908096, 'weight_class_1': 2.771833033595877, 'weight_class_2': 0.10196487475082945}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,715] Trial 407 finished with value: 0.9495677041054676 and parameters: {'weight_class_0': 0.1865741607695975, 'weight_class_1': 2.6587044893025498, 'weight_class_2': 2.292090084715287}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,746] Trial 409 finished with value: 0.9494118333447027 and parameters: {'weight_class_0': 0.2826255646844018, 'weight_class_1': 4.365687666528793, 'weight_class_2': 3.9087148707585877}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,752] Trial 410 finished with value: 0.9476985410608437 and parameters: {'weight_class_0': 0.12107823869430631, 'weight_class_1': 4.042894839858984, 'weight_class_2': 3.1655464132760573}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,790] Trial 411 finished with value: 0.9471754203404738 and parameters: {'weight_class_0': 0.35290421494803187, 'weight_class_1': 4.872581132159293, 'weight_class_2': 1.4559560742247106}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,793] Trial 412 finished with value: 0.9488191653649367 and parameters: {'weight_class_0': 0.1199413537841173, 'weight_class_1': 2.7404824190566726, 'weight_class_2': 2.33782330039682}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,816] Trial 413 finished with value: 0.9492606926200992 and parameters: {'weight_class_0': 0.3411528470463726, 'weight_class_1': 2.7026442815675464, 'weight_class_2': 2.9418584016817113}. Best is trial 47 with value: 0.9497640908263807.

Best trial: 47. Best value: 0.949764:  85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 426/500 [00:07<00:01, 56.14it/s]

[I 2026-07-13 11:33:55,829] Trial 414 finished with value: 0.9494231656531794 and parameters: {'weight_class_0': 0.2814252246666105, 'weight_class_1': 2.702440954906564, 'weight_class_2': 2.456562325345922}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,858] Trial 415 finished with value: 0.9485775882956586 and parameters: {'weight_class_0': 0.33204042776934634, 'weight_class_1': 2.4551030175082427, 'weight_class_2': 2.250998213664045}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,864] Trial 416 finished with value: 0.9495584697812222 and parameters: {'weight_class_0': 0.11686809277663307, 'weight_class_1': 2.580919681260187, 'weight_class_2': 1.3636459236334764}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,894] Trial 417 finished with value: 0.9492778769335689 and parameters: {'weight_class_0': 0.26253518530090225, 'weight_class_1': 2.2567723993263025, 'weight_class_2': 3.1481357291622425}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,915] Trial 418 finished with value: 0.9481556038712885 and parameters: {'weight_class_0': 0.3677585466273988, 'weight_class_1': 5.592723217729437, 'weight_class_2': 1.8590949095138511}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,922] Trial 419 finished with value: 0.9496914366526226 and parameters: {'weight_class_0': 0.2833984541753095, 'weight_class_1': 5.6905370752888755, 'weight_class_2': 2.9815122918430292}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,949] Trial 420 finished with value: 0.9497074387741362 and parameters: {'weight_class_0': 0.1319669506107691, 'weight_class_1': 2.218131605175922, 'weight_class_2': 1.2953822964639246}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,978] Trial 421 finished with value: 0.9484645234278125 and parameters: {'weight_class_0': 0.24257849912199142, 'weight_class_1': 1.4369115929015472, 'weight_class_2': 1.889950546545927}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,988] Trial 422 finished with value: 0.9497057799658881 and parameters: {'weight_class_0': 0.13615598090283823, 'weight_class_1': 2.207159029305767, 'weight_class_2': 1.3145549888582575}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:55,991] Trial 423 finished with value: 0.9494581823170072 and parameters: {'weight_class_0': 0.13941056281089256, 'weight_class_1': 2.1585935555555076, 'weight_class_2': 1.867020056658029}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:56,022] Trial 424 finished with value: 0.9135221305200698 and parameters: {'weight_class_0': 0.1333380835047783, 'weight_class_1': 2.174492505111934, 'weight_class_2': 0.14804600437555918}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:56,051] Trial 426 finished with value: 0.9487287016284888 and parameters: {'weight_class_0': 0.14019962177678189, 'weight_class_1': 1.392862793796643, 'weight_class_2': 0.8624021997564456}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:56,060] Trial 425 finished with value: 0.9490061726421123 and parameters: {'weight_class_0': 0.1340684482396684, 'weight_class_1': 1.9868560025956852, 'weight_class_2': 0.860899046499013}. Best is trial 47 with value: 0.9497640908263807.

Best trial: 47. Best value: 0.949764:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                | 438/500 [00:08<00:01, 56.52it/s]

[I 2026-07-13 11:33:56,087] Trial 428 finished with value: 0.949535042932447 and parameters: {'weight_class_0': 0.10530747071843122, 'weight_class_1': 1.4049163353087302, 'weight_class_2': 0.8685794232694874}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:56,091] Trial 427 finished with value: 0.9493224319219419 and parameters: {'weight_class_0': 0.14475978681518306, 'weight_class_1': 1.4460266272643834, 'weight_class_2': 1.8715637811967332}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:56,112] Trial 430 finished with value: 0.9221118283700026 and parameters: {'weight_class_0': 0.5533748054052587, 'weight_class_1': 1.4225141412007285, 'weight_class_2': 0.9329594109568473}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:56,113] Trial 429 finished with value: 0.9444771689098547 and parameters: {'weight_class_0': 0.06226666530826764, 'weight_class_1': 1.4010510322416727, 'weight_class_2': 4.999901587934861}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:56,155] Trial 431 finished with value: 0.9466117929188357 and parameters: {'weight_class_0': 0.2114300440348095, 'weight_class_1': 1.433774465549428, 'weight_class_2': 0.8756771394996168}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:56,173] Trial 432 finished with value: 0.9453688607863348 and parameters: {'weight_class_0': 0.2416039933132704, 'weight_class_1': 6.029147362724907, 'weight_class_2': 0.8420637995737628}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:56,185] Trial 434 finished with value: 0.9490030999368816 and parameters: {'weight_class_0': 0.23840157663551909, 'weight_class_1': 6.661529278745566, 'weight_class_2': 3.379289612574818}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:56,187] Trial 433 finished with value: 0.9462749293352494 and parameters: {'weight_class_0': 0.2193284667684533, 'weight_class_1': 6.138152990109271, 'weight_class_2': 0.878856324606088}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:56,203] Trial 435 finished with value: 0.9372152842065287 and parameters: {'weight_class_0': 0.10494396970779457, 'weight_class_1': 9.842077574426362, 'weight_class_2': 1.2937101395774349}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:56,246] Trial 438 finished with value: 0.9471243487714031 and parameters: {'weight_class_0': 0.10385684816529771, 'weight_class_1': 1.978590681083678, 'weight_class_2': 4.487111221832528}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:56,248] Trial 437 finished with value: 0.9351966066332346 and parameters: {'weight_class_0': 0.5376488871178216, 'weight_class_1': 2.052335374185263, 'weight_class_2': 1.2044484686008277}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:56,253] Trial 436 finished with value: 0.9478037948255332 and parameters: {'weight_class_0': 0.2453719704911125, 'weight_class_1': 6.168221914708692, 'weight_class_2': 1.3024021636475256}. Best is trial 47 with value: 0.9497640908263807.

Best trial: 47. Best value: 0.949764:  90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌             | 450/500 [00:08<00:00, 56.75it/s]

[I 2026-07-13 11:33:56,285] Trial 439 finished with value: 0.9486197861736102 and parameters: {'weight_class_0': 0.22502235773212084, 'weight_class_1': 1.952127076791035, 'weight_class_2': 1.3642120507917215}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:56,300] Trial 440 finished with value: 0.9488513500698746 and parameters: {'weight_class_0': 0.22073590455929842, 'weight_class_1': 6.028990555361647, 'weight_class_2': 3.5546944592108356}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:56,318] Trial 442 finished with value: 0.9082653829173609 and parameters: {'weight_class_0': 0.23332311929504532, 'weight_class_1': 0.1752730531324789, 'weight_class_2': 1.1943459799123493}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:56,321] Trial 441 finished with value: 0.9488134291914445 and parameters: {'weight_class_0': 0.2285471792430472, 'weight_class_1': 5.7387431569545635, 'weight_class_2': 4.181560259572952}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:56,344] Trial 443 finished with value: 0.9486047600645061 and parameters: {'weight_class_0': 0.22978716006549438, 'weight_class_1': 1.8984889183435563, 'weight_class_2': 3.5689777611489277}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:56,385] Trial 445 finished with value: 0.9496722123295515 and parameters: {'weight_class_0': 0.12248076823488134, 'weight_class_1': 2.0937085140447134, 'weight_class_2': 1.3178876358559262}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:56,395] Trial 444 finished with value: 0.9471261431588074 and parameters: {'weight_class_0': 0.10278431499450467, 'weight_class_1': 2.029208285139772, 'weight_class_2': 4.42847886117759}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:56,415] Trial 446 finished with value: 0.8556777944763324 and parameters: {'weight_class_0': 2.902472772359158, 'weight_class_1': 2.095426593895773, 'weight_class_2': 1.3647197834874811}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:56,418] Trial 447 finished with value: 0.8524994705866739 and parameters: {'weight_class_0': 3.0490427298287672, 'weight_class_1': 1.945133247878978, 'weight_class_2': 1.3012675244591163}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:56,427] Trial 448 finished with value: 0.9338182184892018 and parameters: {'weight_class_0': 0.12453853292286383, 'weight_class_1': 0.21496334228134134, 'weight_class_2': 1.3683377775079653}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:56,465] Trial 449 finished with value: 0.9386376744345889 and parameters: {'weight_class_0': 0.1172562551918693, 'weight_class_1': 0.24749001802877402, 'weight_class_2': 1.3871324164735837}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:56,473] Trial 450 finished with value: 0.9292413637529316 and parameters: {'weight_class_0': 0.09901192114229079, 'weight_class_1': 0.14957547422568093, 'weight_class_2': 1.4995659581584497}. Best is trial 47 with value: 0.9497640908263807.

Best trial: 457. Best value: 0.949773:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉          | 462/500 [00:08<00:00, 57.18it/s]

[I 2026-07-13 11:33:56,513] Trial 451 finished with value: 0.8477568815704001 and parameters: {'weight_class_0': 2.935018317222796, 'weight_class_1': 1.7246832578480569, 'weight_class_2': 0.7072342656101608}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:56,519] Trial 453 finished with value: 0.9484565433399196 and parameters: {'weight_class_0': 0.12201508095849939, 'weight_class_1': 2.224954236321312, 'weight_class_2': 0.6822614441821706}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:56,521] Trial 452 finished with value: 0.9495252493145786 and parameters: {'weight_class_0': 0.12139506967487668, 'weight_class_1': 1.667320267828635, 'weight_class_2': 1.565016939764756}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:56,542] Trial 454 finished with value: 0.9489618262062542 and parameters: {'weight_class_0': 0.09756928881027957, 'weight_class_1': 2.346189373545969, 'weight_class_2': 0.7179788587568862}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:56,550] Trial 455 finished with value: 0.925484396489257 and parameters: {'weight_class_0': 0.46420776213466575, 'weight_class_1': 2.265357519995456, 'weight_class_2': 0.7262653144973839}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:56,593] Trial 456 finished with value: 0.9358202993764233 and parameters: {'weight_class_0': 0.12593822774910923, 'weight_class_1': 0.23417531715990048, 'weight_class_2': 1.5306574765505334}. Best is trial 47 with value: 0.9497640908263807.
[I 2026-07-13 11:33:56,612] Trial 457 finished with value: 0.9497733188665324 and parameters: {'weight_class_0': 0.16158000859014726, 'weight_class_1': 3.024953878433461, 'weight_class_2': 1.6231917599188501}. Best is trial 457 with value: 0.9497733188665324.
[I 2026-07-13 11:33:56,617] Trial 458 finished with value: 0.9496240322491104 and parameters: {'weight_class_0': 0.16916844304330084, 'weight_class_1': 2.5481117916027958, 'weight_class_2': 1.5311836413230429}. Best is trial 457 with value: 0.9497733188665324.
[I 2026-07-13 11:33:56,632] Trial 459 finished with value: 0.7352076808248788 and parameters: {'weight_class_0': 0.16397816205312712, 'weight_class_1': 0.0018717527504366414, 'weight_class_2': 1.623607936273004}. Best is trial 457 with value: 0.9497733188665324.
[I 2026-07-13 11:33:56,643] Trial 460 finished with value: 0.9463837768450928 and parameters: {'weight_class_0': 0.15857909047190605, 'weight_class_1': 8.200006263519438, 'weight_class_2': 2.655299048170711}. Best is trial 457 with value: 0.9497733188665324.
[I 2026-07-13 11:33:56,675] Trial 461 finished with value: 0.9497365278771293 and parameters: {'weight_class_0': 0.16740362553537216, 'weight_class_1': 2.6266456513155805, 'weight_class_2': 1.6604950095928972}. Best is trial 457 with value: 0.9497733188665324.
[I 2026-07-13 11:33:56,684] Trial 462 finished with value: 0.7764890700188344 and parameters: {'weight_class_0': 0.4081374897277885, 'weight_class_1': 0.005913769926757403, 'weight_class_2': 1.7427086275624206}. Best is trial 457 with value: 0.9497733188665324.

Best trial: 457. Best value: 0.949773:  95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊       | 473/500 [00:08<00:00, 52.31it/s]

[I 2026-07-13 11:33:56,709] Trial 463 finished with value: 0.949219013622538 and parameters: {'weight_class_0': 0.16711342876168583, 'weight_class_1': 3.5302282371686706, 'weight_class_2': 2.67853717527647}. Best is trial 457 with value: 0.9497733188665324.
[I 2026-07-13 11:33:56,715] Trial 464 finished with value: 0.8959271608760507 and parameters: {'weight_class_0': 0.15903957672230248, 'weight_class_1': 3.2379401353913475, 'weight_class_2': 0.07172315727106332}. Best is trial 457 with value: 0.9497733188665324.
[I 2026-07-13 11:33:56,734] Trial 465 finished with value: 0.9496184408842637 and parameters: {'weight_class_0': 0.16043174660918683, 'weight_class_1': 1.5935857387600012, 'weight_class_2': 1.7259383390855416}. Best is trial 457 with value: 0.9497733188665324.
[I 2026-07-13 11:33:56,759] Trial 466 finished with value: 0.9491611327687851 and parameters: {'weight_class_0': 0.16249703589882017, 'weight_class_1': 3.110191723336458, 'weight_class_2': 2.6933040071864616}. Best is trial 457 with value: 0.9497733188665324.
[I 2026-07-13 11:33:56,774] Trial 467 finished with value: 0.9491782823402574 and parameters: {'weight_class_0': 0.16949367504914636, 'weight_class_1': 3.546677447286963, 'weight_class_2': 2.7020533707572527}. Best is trial 457 with value: 0.9497733188665324.
[I 2026-07-13 11:33:56,819] Trial 469 finished with value: 0.948890522072703 and parameters: {'weight_class_0': 0.14034623359618084, 'weight_class_1': 3.478339448766557, 'weight_class_2': 1.034910326155044}. Best is trial 457 with value: 0.9497733188665324.
[I 2026-07-13 11:33:56,824] Trial 468 finished with value: 0.9490913936940354 and parameters: {'weight_class_0': 0.15586523195605637, 'weight_class_1': 3.252683259608223, 'weight_class_2': 2.7030127830948025}. Best is trial 457 with value: 0.9497733188665324.
[I 2026-07-13 11:33:56,841] Trial 470 finished with value: 0.9487381396530609 and parameters: {'weight_class_0': 0.08978632178495127, 'weight_class_1': 3.0378309687608986, 'weight_class_2': 1.071159322656733}. Best is trial 457 with value: 0.9497733188665324.
[I 2026-07-13 11:33:56,867] Trial 471 finished with value: 0.9037560842661283 and parameters: {'weight_class_0': 0.08717708111644566, 'weight_class_1': 0.04998797185648088, 'weight_class_2': 1.045685832876735}. Best is trial 457 with value: 0.9497733188665324.
[I 2026-07-13 11:33:56,892] Trial 472 finished with value: 0.9489966304908884 and parameters: {'weight_class_0': 0.3063843003648408, 'weight_class_1': 3.2370170626272174, 'weight_class_2': 2.126892184392423}. Best is trial 457 with value: 0.9497733188665324.
[I 2026-07-13 11:33:56,908] Trial 473 finished with value: 0.9488596949637893 and parameters: {'weight_class_0': 0.29895344718979183, 'weight_class_1': 2.7738390708250615, 'weight_class_2': 1.943011235724923}. Best is trial 457 with value: 0.9497733188665324.

[I 2026-07-13 11:33:56,919] Trial 474 finished with value: 0.9491863620820137 and parameters: {'weight_class_0': 0.29083988907479197, 'weight_class_1': 2.8930745863157434, 'weight_class_2': 2.159248124365757}. Best is trial 457 with value: 0.9497733188665324.
[I 2026-07-13 11:33:56,964] Trial 476 finished with value: 0.9491640779776923 and parameters: {'weight_class_0': 0.2813876696065295, 'weight_class_1': 2.8262592747864574, 'weight_class_2': 2.0779544607438867}. Best is trial 457 with value: 0.9497733188665324.
[I 2026-07-13 11:33:56,965] Trial 475 finished with value: 0.947840945517575 and parameters: {'weight_class_0': 0.19601359599797438, 'weight_class_1': 3.0798596416034543, 'weight_class_2': 6.09792907045335}. Best is trial 457 with value: 0.9497733188665324.
[I 2026-07-13 11:33:56,978] Trial 477 finished with value: 0.9493602670406666 and parameters: {'weight_class_0': 0.19327797599273758, 'weight_class_1': 4.951963211081684, 'weight_class_2': 2.081397666532235}. Best is trial 457 with value: 0.9497733188665324.
[I 2026-07-13 11:33:56,996] Trial 478 finished with value: 0.9497465798808657 and parameters: {'weight_class_0': 0.1971154628254052, 'weight_class_1': 3.0251253609391124, 'weight_class_2': 2.137522929610446}. Best is trial 457 with value: 0.9497733188665324.
[I 2026-07-13 11:33:57,001] Trial 479 finished with value: 0.9491926964985412 and parameters: {'weight_class_0': 0.2947866609040873, 'weight_class_1': 2.8672391160487534, 'weight_class_2': 2.202534622831661}. Best is trial 457 with value: 0.9497733188665324.
[I 2026-07-13 11:33:57,024] Trial 480 finished with value: 0.9484882361214466 and parameters: {'weight_class_0': 0.20024783018049438, 'weight_class_1': 2.8529469116954216, 'weight_class_2': 1.0996199122841739}. Best is trial 457 with value: 0.9497733188665324.
[I 2026-07-13 11:33:57,069] Trial 482 finished with value: 0.9493653374204506 and parameters: {'weight_class_0': 0.19403259193536762, 'weight_class_1': 4.984915258362505, 'weight_class_2': 2.1451925232244657}. Best is trial 457 with value: 0.9497733188665324.
[I 2026-07-13 11:33:57,079] Trial 481 finished with value: 0.9496766237803272 and parameters: {'weight_class_0': 0.19484666978118387, 'weight_class_1': 2.565208635857254, 'weight_class_2': 2.1236347657449204}. Best is trial 457 with value: 0.9497733188665324.
[I 2026-07-13 11:33:57,095] Trial 483 finished with value: 0.9497006931689675 and parameters: {'weight_class_0': 0.1967905898113606, 'weight_class_1': 2.6205515166781392, 'weight_class_2': 2.014323641271856}. Best is trial 457 with value: 0.9497733188665324.

Best trial: 457. Best value: 0.949773: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍| 498/500 [00:09<00:00, 61.88it/s]

[I 2026-07-13 11:33:57,107] Trial 484 finished with value: 0.9484366023854274 and parameters: {'weight_class_0': 0.19106611765823867, 'weight_class_1': 4.327062897537358, 'weight_class_2': 1.1449168202780562}. Best is trial 457 with value: 0.9497733188665324.
[I 2026-07-13 11:33:57,135] Trial 485 finished with value: 0.9483775878748787 and parameters: {'weight_class_0': 0.1963393442090156, 'weight_class_1': 4.70150419663289, 'weight_class_2': 1.1864931351990498}. Best is trial 457 with value: 0.9497733188665324.
[I 2026-07-13 11:33:57,139] Trial 486 finished with value: 0.9493226637326871 and parameters: {'weight_class_0': 0.09819806686371707, 'weight_class_1': 2.501890288638061, 'weight_class_2': 1.1694954539313913}. Best is trial 457 with value: 0.9497733188665324.
[I 2026-07-13 11:33:57,189] Trial 487 finished with value: 0.9494116757964589 and parameters: {'weight_class_0': 0.10126806722765751, 'weight_class_1': 2.5093118263942897, 'weight_class_2': 0.9928647221728296}. Best is trial 457 with value: 0.9497733188665324.
[I 2026-07-13 11:33:57,203] Trial 488 finished with value: 0.9478743653352382 and parameters: {'weight_class_0': 0.10289209820803843, 'weight_class_1': 4.247523563353635, 'weight_class_2': 0.9658819048530497}. Best is trial 457 with value: 0.9497733188665324.
[I 2026-07-13 11:33:57,235] Trial 489 finished with value: 0.9468907547462387 and parameters: {'weight_class_0': 0.09337123817356077, 'weight_class_1': 4.699116571747906, 'weight_class_2': 0.9772355852676664}. Best is trial 457 with value: 0.9497733188665324.
[I 2026-07-13 11:33:57,241] Trial 490 finished with value: 0.9492905522062358 and parameters: {'weight_class_0': 0.1045355026316849, 'weight_class_1': 2.505153326269861, 'weight_class_2': 0.9210991774823573}. Best is trial 457 with value: 0.9497733188665324.
[I 2026-07-13 11:33:57,255] Trial 491 finished with value: 0.9482195843883506 and parameters: {'weight_class_0': 0.10395491176662254, 'weight_class_1': 4.075053646894141, 'weight_class_2': 1.2193210833432213}. Best is trial 457 with value: 0.9497733188665324.
[I 2026-07-13 11:33:57,269] Trial 492 finished with value: 0.9478953470522992 and parameters: {'weight_class_0': 0.19810158483415677, 'weight_class_1': 4.371680932867646, 'weight_class_2': 0.9997603243179554}. Best is trial 457 with value: 0.9497733188665324.
[I 2026-07-13 11:33:57,289] Trial 493 finished with value: 0.7516207200753621 and parameters: {'weight_class_0': 0.08036217134707202, 'weight_class_1': 3.694495026712298, 'weight_class_2': 0.0036859173448518844}. Best is trial 457 with value: 0.9497733188665324.
[I 2026-07-13 11:33:57,298] Trial 495 finished with value: 0.9187376801611397 and parameters: {'weight_class_0': 0.06132058378040721, 'weight_class_1': 0.06629438235190524, 'weight_class_2': 0.896913752675888}. Best is trial 457 with value: 0.9497733188665324.
[I 2026-07-13 11:33:57,302] Trial 494 finished with value: 0.9444255326180105 and parameters: {'weight_class_0': 0.06360186226400952, 'weight_class_1': 4.1292946916066615, 'weight_class_2': 0.877672020540004}. Best is trial 457 with value: 0.9497733188665324.
[I 2026-07-13 11:33:57,320] Trial 496 finished with value: 0.9476083398501848 and parameters: {'weight_class_0': 0.08379055599370898, 'weight_class_1': 3.765598339641581, 'weight_class_2': 0.8779405832620891}. Best is trial 457 with value: 0.9497733188665324.
[I 2026-07-13 11:33:57,335] Trial 497 finished with value: 0.9431879014828496 and parameters: {'weight_class_0': 0.061516748943958824, 'weight_class_1': 3.8089452319764807, 'weight_class_2': 3.138431378987574}. Best is trial 457 with value: 0.9497733188665324.
[I 2026-07-13 11:33:57,341] Trial 498 finished with value: 0.9442398115692127 and parameters: {'weight_class_0': 0.06015000523309842, 'weight_class_1': 3.7049601398615915, 'weight_class_2': 1.8010163298998696}. Best is trial 457 with value: 0.9497733188665324.

Best trial: 457. Best value: 0.949773: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 500/500 [00:09<00:00, 54.76it/s]

[I 2026-07-13 11:33:57,361] Trial 499 finished with value: 0.9465854560221123 and parameters: {'weight_class_0': 0.0777290885987139, 'weight_class_1': 3.707566387098161, 'weight_class_2': 1.815596842335533}. Best is trial 457 with value: 0.9497733188665324.

Best trial score:
0.9497733188665324

Best params:
{'weight_class_0': 0.16158000859014726, 'weight_class_1': 3.024953878433461, 'weight_class_2': 1.6231917599188501}

In [9]:
weights = np.array([study.best_params['weight_class_0'], study.best_params['weight_class_1'], study.best_params['weight_class_2']])
weighted_probas = X_test.loc[:, ['xgb_0', 'xgb_1', 'xgb_2']].to_numpy() * weights

pred = np.argmax(weighted_probas, axis=1)

In [10]:
sub_labels = label_encoder.inverse_transform(pred)

# Submission

In [11]:
submission = pd.read_csv('../data/submission/sample_submission.csv')
submission['health_condition'] = sub_labels

submission.to_csv('../data/submission/submission_from_5.2_xgboost_submission.csv', index=False)

In [12]:
submission.head()

       id health_condition
0  690088        unhealthy
1  690089        unhealthy
2  690090          at-risk
3  690091          at-risk
4  690092        unhealthy