# Imports

In [1]:
import optuna
import pickle

import numpy as np
import pandas as pd

from tqdm import tqdm

from sklearn.metrics import balanced_accuracy_score
from sklearn.model_selection import StratifiedKFold, cross_val_predict

/home/junior/Documentos/GitHub/kaggle-competition-predicting-student-health/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Utils

In [2]:
def load_pickle(file_path):
    with open(file_path, 'rb') as file:
        return pickle.load(file)

# Loading Datasets

In [4]:
X_train = pd.read_parquet('../data/processed/X_train_stacking_layer_one_model_60_trials.parquet')
y_train = pd.read_parquet('../data/interim/y_train.parquet')

X_test = pd.read_parquet('../data/processed/X_test_stacking_layer_one_model_60_trials.parquet')

In [5]:
X_train.head()

     lgbm_0    lgbm_1    lgbm_2     xgb_0     xgb_1     xgb_2
0  0.004922  0.001773  0.993304  0.004134  0.002593  0.993273
1  0.997228  0.000463  0.002309  0.995591  0.000405  0.004004
2  0.002369  0.000604  0.997026  0.001958  0.000503  0.997538
3  0.004656  0.003362  0.991982  0.002466  0.002391  0.995142
4  0.995353  0.000016  0.004632  0.994178  0.000003  0.005819

In [6]:
X_test.head()

     lgbm_0    lgbm_1    lgbm_2     xgb_0     xgb_1     xgb_2
0  0.012452  0.003199  0.984349  0.011048  0.004491  0.984461
1  0.472116  0.002331  0.525553  0.499186  0.001896  0.498918
2  0.998690  0.001012  0.000298  0.997826  0.001594  0.000579
3  0.980854  0.000018  0.019128  0.987434  0.000009  0.012557
4  0.006765  0.001847  0.991388  0.006876  0.001972  0.991152

In [7]:
y_train.head()

    health_condition
id
0                  2
1                  0
2                  2
3                  2
4                  0

# Machine Learning

In [8]:
label_encoder = load_pickle('../artifacts/label_encoder.pkl')

In [9]:
def objective(trial, X, y):

    lgbm_w0 = trial.suggest_float('weight_lgbm_class_0', 0.0, 1.0)
    lgbm_w1 = trial.suggest_float('weight_lgbm_class_1', 0.0, 1.0)
    lgbm_w2 = trial.suggest_float('weight_lgbm_class_2', 0.0, 1.0)
    
    xgb_w0 = trial.suggest_float('weight_xgb_class_0', 0.0, 1.0)
    xgb_w1 = trial.suggest_float('weight_xgb_class_1', 0.0, 1.0)
    xgb_w2 = trial.suggest_float('weight_xgb_class_2', 0.0, 1.0)
    
    # cat_w0 = trial.suggest_float('weight_cat_class_0', 0.0, 1.0)
    # cat_w1 = trial.suggest_float('weight_cat_class_1', 0.0, 1.0)
    # cat_w2 = trial.suggest_float('weight_cat_class_2', 0.0, 1.0)
    
    proba_lgbm = X[['lgbm_0', 'lgbm_1', 'lgbm_2']].to_numpy()
    proba_xgb  = X[['xgb_0', 'xgb_1', 'xgb_2']].to_numpy()
    # proba_cat  = X[['cat_0', 'cat_1', 'cat_2']].to_numpy()

    w_lgbm = np.array([lgbm_w0, lgbm_w1, lgbm_w2])
    w_xgb  = np.array([xgb_w0, xgb_w1, xgb_w2])
    # w_cat  = np.array([cat_w0, cat_w1, cat_w2])
    
    blend_proba = (proba_lgbm * w_lgbm) + (proba_xgb * w_xgb) # + (proba_cat * w_cat)
    
    pred = np.argmax(blend_proba, axis=1)
    
    score = balanced_accuracy_score(y, pred)

    return score


study = optuna.create_study(
    direction="maximize", 
    sampler=optuna.samplers.TPESampler(seed=42), 
    pruner=optuna.pruners.MedianPruner(n_warmup_steps=2)
)

study.optimize(
    lambda trial: objective(trial, X_train, y_train.health_condition), 
    n_trials=2000, 
    n_jobs=-1, 
    show_progress_bar=True
)

print("\nBest trial score:")
print(study.best_trial.value)

print("\nBest params:")
print(study.best_trial.params)

[I 2026-07-05 15:31:31,403] A new study created in memory with name: no-name-034458e4-c8bd-4b33-8ded-8758fa325dac

[I 2026-07-05 15:31:31,600] Trial 0 finished with value: 0.8759317873440423 and parameters: {'weight_lgbm_class_0': 0.37110426259962925, 'weight_lgbm_class_1': 0.7667893969991753, 'weight_lgbm_class_2': 0.3870816026439209, 'weight_xgb_class_0': 0.8987224659612689, 'weight_xgb_class_1': 0.5844597872283822, 'weight_xgb_class_2': 0.6620972639911515}. Best is trial 0 with value: 0.8759317873440423.
[I 2026-07-05 15:31:31,620] Trial 5 finished with value: 0.8740848614910811 and parameters: {'weight_lgbm_class_0': 0.5609230725323702, 'weight_lgbm_class_1': 0.31730592558460113, 'weight_lgbm_class_2': 0.6781136203704915, 'weight_xgb_class_0': 0.09698154555303051, 'weight_xgb_class_1': 0.07084341947817996, 'weight_xgb_class_2': 0.11830012684951408}. Best is trial 0 with value: 0.8759317873440423.
[I 2026-07-05 15:31:31,626] Trial 4 finished with value: 0.8467341294934693 and parameters: {'weight_lgbm_class_0': 0.0373100738319081, 'weight_lgbm_class_1': 0.06527270877525782, 'weight_lgbm_class_2': 0.07695371227813241, 'weight_xgb_class_0': 0.7287759194657534, 'weight_xgb_class_1': 0.41492261634061833, 'weight_xgb_class_2': 0.02290801419570665}. Best is trial 0 with value: 0.8759317873440423.
[I 2026-07-05 15:31:31,632] Trial 2 finished with value: 0.9240431970952069 and parameters: {'weight_lgbm_class_0': 0.08301174273080758, 'weight_lgbm_class_1': 0.02358596087497422, 'weight_lgbm_class_2': 0.5971238856472099, 'weight_xgb_class_0': 0.4702480085883233, 'weight_xgb_class_1': 0.9737153013110078, 'weight_xgb_class_2': 0.729811642911125}. Best is trial 2 with value: 0.9240431970952069.
[I 2026-07-05 15:31:31,634] Trial 7 finished with value: 0.8839281644975511 and parameters: {'weight_lgbm_class_0': 0.4171971993484963, 'weight_lgbm_class_1': 0.8242609002616612, 'weight_lgbm_class_2': 0.09285822366050989, 'weight_xgb_class_0': 0.3031322362947969, 'weight_xgb_class_1': 0.7106301098201323, 'weight_xgb_class_2': 0.16991002119614596}. Best is trial 2 with value: 0.9240431970952069.
[I 2026-07-05 15:31:31,635] Trial 11 finished with value: 0.9055610644826392 and parameters: {'weight_lgbm_class_0': 0.5086393336948164, 'weight_lgbm_class_1': 0.6440959015583189, 'weight_lgbm_class_2': 0.4536252120567795, 'weight_xgb_class_0': 0.03136259212906278, 'weight_xgb_class_1': 0.3834574065577059, 'weight_xgb_class_2': 0.23714896886193537}. Best is trial 2 with value: 0.9240431970952069.
[I 2026-07-05 15:31:31,640] Trial 9 finished with value: 0.8732720715055563 and parameters: {'weight_lgbm_class_0': 0.5227912454503716, 'weight_lgbm_class_1': 0.7845092547719397, 'weight_lgbm_class_2': 0.3970086414734634, 'weight_xgb_class_0': 0.7161791919478929, 'weight_xgb_class_1': 0.36105120951642466, 'weight_xgb_class_2': 0.6783923090662397}. Best is trial 2 with value: 0.9240431970952069.
[I 2026-07-05 15:31:31,642] Trial 3 finished with value: 0.8847454906681019 and parameters: {'weight_lgbm_class_0': 0.8967557898975018, 'weight_lgbm_class_1': 0.9106134640200508, 'weight_lgbm_class_2': 0.9806523341597867, 'weight_xgb_class_0': 0.3490459133556256, 'weight_xgb_class_1': 0.7535441290358789, 'weight_xgb_class_2': 0.09968297654455271}. Best is trial 2 with value: 0.9240431970952069.
[I 2026-07-05 15:31:31,643] Trial 8 finished with value: 0.8906006764777263 and parameters: {'weight_lgbm_class_0': 0.19058541921790906, 'weight_lgbm_class_1': 0.00907542963576824, 'weight_lgbm_class_2': 0.458469440986384, 'weight_xgb_class_0': 0.7740901474102087, 'weight_xgb_class_1': 0.8681436741273195, 'weight_xgb_class_2': 0.974658540701335}. Best is trial 2 with value: 0.9240431970952069.
[I 2026-07-05 15:31:31,645] Trial 10 finished with value: 0.9395374134151561 and parameters: {'weight_lgbm_class_0': 0.12563835722010253, 'weight_lgbm_class_1': 0.6242363417757807, 'weight_lgbm_class_2': 0.006062726177706312, 'weight_xgb_class_0': 0.17410399636534013, 'weight_xgb_class_1': 0.4051022958576622, 'weight_xgb_class_2': 0.9494937273508366}. Best is trial 10 with value: 0.9395374134151561.

Best trial: 15. Best value: 0.942462:   1%|█▎                                                                                                                                    | 19/2000 [00:00<00:54, 36.24it/s]

[I 2026-07-05 15:31:31,647] Trial 1 finished with value: 0.9038460381975165 and parameters: {'weight_lgbm_class_0': 0.19876765697596588, 'weight_lgbm_class_1': 0.8366848626402802, 'weight_lgbm_class_2': 0.008206597684362604, 'weight_xgb_class_0': 0.3886423133116683, 'weight_xgb_class_1': 0.9730547996152823, 'weight_xgb_class_2': 0.5460402937409152}. Best is trial 10 with value: 0.9395374134151561.
[I 2026-07-05 15:31:31,648] Trial 6 finished with value: 0.9224504378173392 and parameters: {'weight_lgbm_class_0': 0.21118493876401734, 'weight_lgbm_class_1': 0.8528518532638305, 'weight_lgbm_class_2': 0.502835392382978, 'weight_xgb_class_0': 0.4865591315081631, 'weight_xgb_class_1': 0.7022562854103667, 'weight_xgb_class_2': 0.8388633220836711}. Best is trial 10 with value: 0.9395374134151561.
[I 2026-07-05 15:31:31,769] Trial 12 finished with value: 0.8613484270972153 and parameters: {'weight_lgbm_class_0': 0.6810664911133526, 'weight_lgbm_class_1': 0.32667323334537346, 'weight_lgbm_class_2': 0.10583257885813302, 'weight_xgb_class_0': 0.5117488523556422, 'weight_xgb_class_1': 0.3772907117278381, 'weight_xgb_class_2': 0.8767243076959657}. Best is trial 10 with value: 0.9395374134151561.
[I 2026-07-05 15:31:31,819] Trial 13 finished with value: 0.9400948367062786 and parameters: {'weight_lgbm_class_0': 0.011626376779864528, 'weight_lgbm_class_1': 0.4198110936481664, 'weight_lgbm_class_2': 0.9961051512781822, 'weight_xgb_class_0': 0.20763479928574005, 'weight_xgb_class_1': 0.1025123636459968, 'weight_xgb_class_2': 0.9930546611185049}. Best is trial 13 with value: 0.9400948367062786.
[I 2026-07-05 15:31:31,829] Trial 14 finished with value: 0.9034597272192424 and parameters: {'weight_lgbm_class_0': 0.0018433615420419547, 'weight_lgbm_class_1': 0.35657019594224465, 'weight_lgbm_class_2': 0.9993073913791097, 'weight_xgb_class_0': 0.5398329920647823, 'weight_xgb_class_1': 0.0022353975701009943, 'weight_xgb_class_2': 0.9875269227368199}. Best is trial 13 with value: 0.9400948367062786.
[I 2026-07-05 15:31:31,853] Trial 15 finished with value: 0.9424617502538698 and parameters: {'weight_lgbm_class_0': 0.05552186690222363, 'weight_lgbm_class_1': 0.474105168788136, 'weight_lgbm_class_2': 0.9751366345466628, 'weight_xgb_class_0': 0.1621021345866614, 'weight_xgb_class_1': 0.1365975025167222, 'weight_xgb_class_2': 0.9629186424190009}. Best is trial 15 with value: 0.9424617502538698.
[I 2026-07-05 15:31:31,873] Trial 16 finished with value: 0.9410010232420968 and parameters: {'weight_lgbm_class_0': 0.007974854313051394, 'weight_lgbm_class_1': 0.47738254871161484, 'weight_lgbm_class_2': 0.9361552451152548, 'weight_xgb_class_0': 0.18612054965540675, 'weight_xgb_class_1': 0.01990438850532983, 'weight_xgb_class_2': 0.9961467404649905}. Best is trial 15 with value: 0.9424617502538698.
[I 2026-07-05 15:31:31,893] Trial 17 finished with value: 0.9392405089456161 and parameters: {'weight_lgbm_class_0': 0.03172808977108239, 'weight_lgbm_class_1': 0.46307449556173397, 'weight_lgbm_class_2': 0.9424862314287399, 'weight_xgb_class_0': 0.20016080478518894, 'weight_xgb_class_1': 0.0712857695007797, 'weight_xgb_class_2': 0.9929826900811949}. Best is trial 15 with value: 0.9424617502538698.
[I 2026-07-05 15:31:31,911] Trial 18 finished with value: 0.9397132195593292 and parameters: {'weight_lgbm_class_0': 0.0302551371927278, 'weight_lgbm_class_1': 0.4883972778735469, 'weight_lgbm_class_2': 0.9478658227600508, 'weight_xgb_class_0': 0.18688799727474664, 'weight_xgb_class_1': 0.02584778436298324, 'weight_xgb_class_2': 0.9235062252776309}. Best is trial 15 with value: 0.9424617502538698.
[I 2026-07-05 15:31:31,933] Trial 20 finished with value: 0.9418742941436493 and parameters: {'weight_lgbm_class_0': 0.017633055508348955, 'weight_lgbm_class_1': 0.4219438356340745, 'weight_lgbm_class_2': 0.9288552791865587, 'weight_xgb_class_0': 0.18693751510703277, 'weight_xgb_class_1': 0.14995974821556268, 'weight_xgb_class_2': 0.42141163598921627}. Best is trial 15 with value: 0.9424617502538698.

Best trial: 32. Best value: 0.943075:   2%|██                                                                                                                                    | 30/2000 [00:00<00:46, 42.56it/s]

[I 2026-07-05 15:31:31,948] Trial 19 finished with value: 0.9354702163474217 and parameters: {'weight_lgbm_class_0': 0.059042367589582645, 'weight_lgbm_class_1': 0.4513787546351029, 'weight_lgbm_class_2': 0.9103649858631154, 'weight_xgb_class_0': 0.1760617958151866, 'weight_xgb_class_1': 0.0028858854436684678, 'weight_xgb_class_2': 0.9995453633968667}. Best is trial 15 with value: 0.9424617502538698.
[I 2026-07-05 15:31:31,979] Trial 21 finished with value: 0.9403386789497671 and parameters: {'weight_lgbm_class_0': 0.0015934110051992467, 'weight_lgbm_class_1': 0.45761059445064445, 'weight_lgbm_class_2': 0.9236900395579314, 'weight_xgb_class_0': 0.1891187599558133, 'weight_xgb_class_1': 0.028366451960153583, 'weight_xgb_class_2': 0.3888964797051345}. Best is trial 15 with value: 0.9424617502538698.
[I 2026-07-05 15:31:32,030] Trial 22 finished with value: 0.9195123624713863 and parameters: {'weight_lgbm_class_0': 0.2946939905502094, 'weight_lgbm_class_1': 0.5221752705217385, 'weight_lgbm_class_2': 0.8078426121857425, 'weight_xgb_class_0': 0.1965428368549693, 'weight_xgb_class_1': 0.1905071082117147, 'weight_xgb_class_2': 0.4795209928630822}. Best is trial 15 with value: 0.9424617502538698.
[I 2026-07-05 15:31:32,033] Trial 23 finished with value: 0.9193724714803201 and parameters: {'weight_lgbm_class_0': 0.2858842176297839, 'weight_lgbm_class_1': 0.5382843909563323, 'weight_lgbm_class_2': 0.7606126846607277, 'weight_xgb_class_0': 0.18762911600424104, 'weight_xgb_class_1': 0.16199445265206386, 'weight_xgb_class_2': 0.4430426593986425}. Best is trial 15 with value: 0.9424617502538698.
[I 2026-07-05 15:31:32,052] Trial 25 finished with value: 0.93526756086416 and parameters: {'weight_lgbm_class_0': 0.2971730826651032, 'weight_lgbm_class_1': 0.5448515092554833, 'weight_lgbm_class_2': 0.8222594765262148, 'weight_xgb_class_0': 0.028156811830889805, 'weight_xgb_class_1': 0.2056354509430824, 'weight_xgb_class_2': 0.44415855445886404}. Best is trial 15 with value: 0.9424617502538698.
[I 2026-07-05 15:31:32,055] Trial 24 finished with value: 0.9140067552313828 and parameters: {'weight_lgbm_class_0': 0.3086379011032262, 'weight_lgbm_class_1': 0.50155565073158, 'weight_lgbm_class_2': 0.8068131474123996, 'weight_xgb_class_0': 0.23439839057957473, 'weight_xgb_class_1': 0.19321489197422193, 'weight_xgb_class_2': 0.4844767969759658}. Best is trial 15 with value: 0.9424617502538698.
[I 2026-07-05 15:31:32,083] Trial 26 finished with value: 0.9273929289408942 and parameters: {'weight_lgbm_class_0': 0.27879000152081246, 'weight_lgbm_class_1': 0.1968311449288241, 'weight_lgbm_class_2': 0.8095795624235071, 'weight_xgb_class_0': 0.0069582980067619815, 'weight_xgb_class_1': 0.22090177801577518, 'weight_xgb_class_2': 0.7907896750535478}. Best is trial 15 with value: 0.9424617502538698.
[I 2026-07-05 15:31:32,108] Trial 27 finished with value: 0.9197363773098269 and parameters: {'weight_lgbm_class_0': 0.28621132772462154, 'weight_lgbm_class_1': 0.14865617165269535, 'weight_lgbm_class_2': 0.8067386632280542, 'weight_xgb_class_0': 0.009326157424394632, 'weight_xgb_class_1': 0.20718775501316083, 'weight_xgb_class_2': 0.3624995040344168}. Best is trial 15 with value: 0.9424617502538698.
[I 2026-07-05 15:31:32,127] Trial 28 finished with value: 0.9230242296157325 and parameters: {'weight_lgbm_class_0': 0.2794055484645132, 'weight_lgbm_class_1': 0.18679489049748665, 'weight_lgbm_class_2': 0.800392963772449, 'weight_xgb_class_0': 0.020633925137803433, 'weight_xgb_class_1': 0.22111503099148283, 'weight_xgb_class_2': 0.3824826036400043}. Best is trial 15 with value: 0.9424617502538698.
[I 2026-07-05 15:31:32,130] Trial 29 finished with value: 0.9200610601769655 and parameters: {'weight_lgbm_class_0': 0.2854093195822863, 'weight_lgbm_class_1': 0.2013509802879106, 'weight_lgbm_class_2': 0.8006061530181966, 'weight_xgb_class_0': 0.044487665138339266, 'weight_xgb_class_1': 0.20381950474491958, 'weight_xgb_class_2': 0.4529607433037073}. Best is trial 15 with value: 0.9424617502538698.
[I 2026-07-05 15:31:32,151] Trial 30 finished with value: 0.9198071536346406 and parameters: {'weight_lgbm_class_0': 0.2710041453187623, 'weight_lgbm_class_1': 0.15902902137987202, 'weight_lgbm_class_2': 0.7994910308818238, 'weight_xgb_class_0': 0.033457524151251, 'weight_xgb_class_1': 0.2032935211215677, 'weight_xgb_class_2': 0.4530594230156122}. Best is trial 15 with value: 0.9424617502538698.

Best trial: 43. Best value: 0.945741:   2%|██▋                                                                                                                                   | 40/2000 [00:01<00:43, 45.31it/s]

[I 2026-07-05 15:31:32,152] Trial 31 finished with value: 0.9162937863782825 and parameters: {'weight_lgbm_class_0': 0.3070263393808359, 'weight_lgbm_class_1': 0.1514783181720163, 'weight_lgbm_class_2': 0.807362272754908, 'weight_xgb_class_0': 0.024276830927225684, 'weight_xgb_class_1': 0.2060618937728375, 'weight_xgb_class_2': 0.4638906321361035}. Best is trial 15 with value: 0.9424617502538698.
[I 2026-07-05 15:31:32,197] Trial 32 finished with value: 0.9430749790528262 and parameters: {'weight_lgbm_class_0': 0.14452072918049969, 'weight_lgbm_class_1': 0.22716721288969463, 'weight_lgbm_class_2': 0.8253372048518657, 'weight_xgb_class_0': 0.015326499882588801, 'weight_xgb_class_1': 0.2443380539019982, 'weight_xgb_class_2': 0.8101245635668628}. Best is trial 32 with value: 0.9430749790528262.
[I 2026-07-05 15:31:32,204] Trial 33 finished with value: 0.9420827455391243 and parameters: {'weight_lgbm_class_0': 0.14744902768051016, 'weight_lgbm_class_1': 0.20243184502577588, 'weight_lgbm_class_2': 0.8186744807504375, 'weight_xgb_class_0': 0.011877513148001728, 'weight_xgb_class_1': 0.23266565178826137, 'weight_xgb_class_2': 0.831374700626863}. Best is trial 32 with value: 0.9430749790528262.
[I 2026-07-05 15:31:32,246] Trial 34 finished with value: 0.9324588506279005 and parameters: {'weight_lgbm_class_0': 0.1415193430203473, 'weight_lgbm_class_1': 0.17150982678700882, 'weight_lgbm_class_2': 0.7023433475676414, 'weight_xgb_class_0': 0.10444264888057858, 'weight_xgb_class_1': 0.2933298602655582, 'weight_xgb_class_2': 0.33236964403423197}. Best is trial 32 with value: 0.9430749790528262.
[I 2026-07-05 15:31:32,263] Trial 36 finished with value: 0.9117953425813466 and parameters: {'weight_lgbm_class_0': 0.13548661474967905, 'weight_lgbm_class_1': 0.22155203897423642, 'weight_lgbm_class_2': 0.6986261150976121, 'weight_xgb_class_0': 0.2871469119585178, 'weight_xgb_class_1': 0.2924652938523417, 'weight_xgb_class_2': 0.274388112022414}. Best is trial 32 with value: 0.9430749790528262.
[I 2026-07-05 15:31:32,280] Trial 35 finished with value: 0.9331517416311716 and parameters: {'weight_lgbm_class_0': 0.13602271915037234, 'weight_lgbm_class_1': 0.17492899910427018, 'weight_lgbm_class_2': 0.6971222631841757, 'weight_xgb_class_0': 0.10310988425077872, 'weight_xgb_class_1': 0.2881262604276381, 'weight_xgb_class_2': 0.3112380827687208}. Best is trial 32 with value: 0.9430749790528262.
[I 2026-07-05 15:31:32,306] Trial 37 finished with value: 0.9333910079366029 and parameters: {'weight_lgbm_class_0': 0.14282146128946607, 'weight_lgbm_class_1': 0.6729244586610457, 'weight_lgbm_class_2': 0.8833323827726437, 'weight_xgb_class_0': 0.2943526813483787, 'weight_xgb_class_1': 0.28706854635845247, 'weight_xgb_class_2': 0.5875312285565264}. Best is trial 32 with value: 0.9430749790528262.
[I 2026-07-05 15:31:32,323] Trial 38 finished with value: 0.9448954673138911 and parameters: {'weight_lgbm_class_0': 0.1291556467994366, 'weight_lgbm_class_1': 0.6454151822039753, 'weight_lgbm_class_2': 0.8951209255098146, 'weight_xgb_class_0': 0.11659461382612352, 'weight_xgb_class_1': 0.2855748753067, 'weight_xgb_class_2': 0.5921006976767735}. Best is trial 38 with value: 0.9448954673138911.
[I 2026-07-05 15:31:32,337] Trial 39 finished with value: 0.9324357024784827 and parameters: {'weight_lgbm_class_0': 0.13284198485653842, 'weight_lgbm_class_1': 0.6359127138663716, 'weight_lgbm_class_2': 0.8878959355229694, 'weight_xgb_class_0': 0.2707001102413326, 'weight_xgb_class_1': 0.3053812566042083, 'weight_xgb_class_2': 0.27490062902153484}. Best is trial 38 with value: 0.9448954673138911.
[I 2026-07-05 15:31:32,379] Trial 40 finished with value: 0.9398978850872598 and parameters: {'weight_lgbm_class_0': 0.13142483736887922, 'weight_lgbm_class_1': 0.2688789853621774, 'weight_lgbm_class_2': 0.6780661956790226, 'weight_xgb_class_0': 0.09417529572215613, 'weight_xgb_class_1': 0.30102348652014577, 'weight_xgb_class_2': 0.583805170658757}. Best is trial 38 with value: 0.9448954673138911.

Best trial: 51. Best value: 0.946304:   2%|███▎                                                                                                                                  | 49/2000 [00:01<00:46, 41.81it/s]

[I 2026-07-05 15:31:32,392] Trial 41 finished with value: 0.935730528050487 and parameters: {'weight_lgbm_class_0': 0.15742092158549817, 'weight_lgbm_class_1': 0.2669515600905483, 'weight_lgbm_class_2': 0.7031341367579967, 'weight_xgb_class_0': 0.11550943512310426, 'weight_xgb_class_1': 0.3040784124955874, 'weight_xgb_class_2': 0.5793277788472517}. Best is trial 38 with value: 0.9448954673138911.
[I 2026-07-05 15:31:32,413] Trial 42 finished with value: 0.9448185400063247 and parameters: {'weight_lgbm_class_0': 0.11091713535581138, 'weight_lgbm_class_1': 0.2585649303010491, 'weight_lgbm_class_2': 0.8786095985053218, 'weight_xgb_class_0': 0.10752559971650091, 'weight_xgb_class_1': 0.4928649631134449, 'weight_xgb_class_2': 0.7469289065861031}. Best is trial 38 with value: 0.9448954673138911.
[I 2026-07-05 15:31:32,432] Trial 43 finished with value: 0.9457410710424669 and parameters: {'weight_lgbm_class_0': 0.10252153852166632, 'weight_lgbm_class_1': 0.2769632849577458, 'weight_lgbm_class_2': 0.8623501158000438, 'weight_xgb_class_0': 0.09773294157892667, 'weight_xgb_class_1': 0.49323470600725183, 'weight_xgb_class_2': 0.6126866845371889}. Best is trial 43 with value: 0.9457410710424669.
[I 2026-07-05 15:31:32,482] Trial 44 finished with value: 0.9392435442048152 and parameters: {'weight_lgbm_class_0': 0.20342131962008642, 'weight_lgbm_class_1': 0.273713796167995, 'weight_lgbm_class_2': 0.8787322893562296, 'weight_xgb_class_0': 0.11141489137730594, 'weight_xgb_class_1': 0.520596424172559, 'weight_xgb_class_2': 0.6100660932921171}. Best is trial 43 with value: 0.9457410710424669.
[I 2026-07-05 15:31:32,487] Trial 45 finished with value: 0.9170968913563673 and parameters: {'weight_lgbm_class_0': 0.19480047685771193, 'weight_lgbm_class_1': 0.387498316538276, 'weight_lgbm_class_2': 0.6064336654170819, 'weight_xgb_class_0': 0.401362943609867, 'weight_xgb_class_1': 0.5078358408333082, 'weight_xgb_class_2': 0.736195407323218}. Best is trial 43 with value: 0.9457410710424669.
[I 2026-07-05 15:31:32,513] Trial 47 finished with value: 0.9007870380073282 and parameters: {'weight_lgbm_class_0': 0.1950417976294521, 'weight_lgbm_class_1': 0.06857308013296881, 'weight_lgbm_class_2': 0.5582379732847501, 'weight_xgb_class_0': 0.39578262013275783, 'weight_xgb_class_1': 0.4609434632861865, 'weight_xgb_class_2': 0.6943257563547852}. Best is trial 43 with value: 0.9457410710424669.
[I 2026-07-05 15:31:32,518] Trial 46 finished with value: 0.9287747039826862 and parameters: {'weight_lgbm_class_0': 0.20002536549505034, 'weight_lgbm_class_1': 0.9703167167110979, 'weight_lgbm_class_2': 0.624884010595945, 'weight_xgb_class_0': 0.4051060405959308, 'weight_xgb_class_1': 0.5346374110454413, 'weight_xgb_class_2': 0.7569333353129842}. Best is trial 43 with value: 0.9457410710424669.
[I 2026-07-05 15:31:32,554] Trial 48 finished with value: 0.8904591444350695 and parameters: {'weight_lgbm_class_0': 0.20605302497537692, 'weight_lgbm_class_1': 0.09771437065396874, 'weight_lgbm_class_2': 0.8626358371903635, 'weight_xgb_class_0': 0.35210998747608874, 'weight_xgb_class_1': 0.13044814032324303, 'weight_xgb_class_2': 0.7587879567752763}. Best is trial 43 with value: 0.9457410710424669.
[I 2026-07-05 15:31:32,581] Trial 50 finished with value: 0.9155447512598416 and parameters: {'weight_lgbm_class_0': 0.08154931433641839, 'weight_lgbm_class_1': 0.08161534532736536, 'weight_lgbm_class_2': 0.858264661840688, 'weight_xgb_class_0': 0.39853655627056056, 'weight_xgb_class_1': 0.44654233698384127, 'weight_xgb_class_2': 0.7755828101436769}. Best is trial 43 with value: 0.9457410710424669.

Best trial: 54. Best value: 0.949525:   3%|███▉                                                                                                                                  | 59/2000 [00:01<00:44, 43.35it/s]

[I 2026-07-05 15:31:32,586] Trial 49 finished with value: 0.9185750364159988 and parameters: {'weight_lgbm_class_0': 0.07724150809032508, 'weight_lgbm_class_1': 0.08871365795787983, 'weight_lgbm_class_2': 0.8723160092847426, 'weight_xgb_class_0': 0.13269542987121613, 'weight_xgb_class_1': 0.1290176121007316, 'weight_xgb_class_2': 0.750349884205845}. Best is trial 43 with value: 0.9457410710424669.
[I 2026-07-05 15:31:32,626] Trial 52 finished with value: 0.9142819277432236 and parameters: {'weight_lgbm_class_0': 0.0848012192358683, 'weight_lgbm_class_1': 0.08000837286025761, 'weight_lgbm_class_2': 0.5988018441141157, 'weight_xgb_class_0': 0.41126169864292794, 'weight_xgb_class_1': 0.4966429940429323, 'weight_xgb_class_2': 0.7458559022200746}. Best is trial 43 with value: 0.9457410710424669.
[I 2026-07-05 15:31:32,640] Trial 51 finished with value: 0.9463041830625029 and parameters: {'weight_lgbm_class_0': 0.20814587502644608, 'weight_lgbm_class_1': 0.9337427308539219, 'weight_lgbm_class_2': 0.6399188311192333, 'weight_xgb_class_0': 0.08143684896212998, 'weight_xgb_class_1': 0.5830722194995057, 'weight_xgb_class_2': 0.7503914976758658}. Best is trial 51 with value: 0.9463041830625029.
[I 2026-07-05 15:31:32,654] Trial 53 finished with value: 0.8818454299458542 and parameters: {'weight_lgbm_class_0': 0.07295853079561061, 'weight_lgbm_class_1': 0.05925198187315567, 'weight_lgbm_class_2': 0.8722256973422902, 'weight_xgb_class_0': 0.989817936345686, 'weight_xgb_class_1': 0.6319315149018647, 'weight_xgb_class_2': 0.6726061123893062}. Best is trial 51 with value: 0.9463041830625029.
[I 2026-07-05 15:31:32,678] Trial 54 finished with value: 0.9495246095989627 and parameters: {'weight_lgbm_class_0': 0.08095034393132558, 'weight_lgbm_class_1': 0.7149585467836166, 'weight_lgbm_class_2': 0.8618576201754128, 'weight_xgb_class_0': 0.07332383388536667, 'weight_xgb_class_1': 0.6220965595660751, 'weight_xgb_class_2': 0.6558608996792716}. Best is trial 54 with value: 0.9495246095989627.
[I 2026-07-05 15:31:32,713] Trial 55 finished with value: 0.8981193835433333 and parameters: {'weight_lgbm_class_0': 0.07430517292039222, 'weight_lgbm_class_1': 0.6972367276165286, 'weight_lgbm_class_2': 0.8606186595354536, 'weight_xgb_class_0': 0.9986289891038164, 'weight_xgb_class_1': 0.6352980934099992, 'weight_xgb_class_2': 0.6608869375303598}. Best is trial 54 with value: 0.9495246095989627.
[I 2026-07-05 15:31:32,729] Trial 56 finished with value: 0.9487020167579271 and parameters: {'weight_lgbm_class_0': 0.09179860675064641, 'weight_lgbm_class_1': 0.7571566728198076, 'weight_lgbm_class_2': 0.9696130294858615, 'weight_xgb_class_0': 0.13560647659572667, 'weight_xgb_class_1': 0.641944363740274, 'weight_xgb_class_2': 0.9021652288964445}. Best is trial 54 with value: 0.9495246095989627.
[I 2026-07-05 15:31:32,743] Trial 57 finished with value: 0.9463065858670111 and parameters: {'weight_lgbm_class_0': 0.07068373151808825, 'weight_lgbm_class_1': 0.7094149502535108, 'weight_lgbm_class_2': 0.21215147270023454, 'weight_xgb_class_0': 0.1393205751655084, 'weight_xgb_class_1': 0.8025693567074594, 'weight_xgb_class_2': 0.6417051258549848}. Best is trial 54 with value: 0.9495246095989627.
[I 2026-07-05 15:31:32,750] Trial 58 finished with value: 0.8939183908666837 and parameters: {'weight_lgbm_class_0': 0.9316463193203799, 'weight_lgbm_class_1': 0.32467738453611605, 'weight_lgbm_class_2': 0.7473537397407233, 'weight_xgb_class_0': 0.07080212910210508, 'weight_xgb_class_1': 0.6259690208706139, 'weight_xgb_class_2': 0.8364976369532605}. Best is trial 54 with value: 0.9495246095989627.
[I 2026-07-05 15:31:32,816] Trial 59 finished with value: 0.9298014710552969 and parameters: {'weight_lgbm_class_0': 0.39358760004542803, 'weight_lgbm_class_1': 0.9075503410013698, 'weight_lgbm_class_2': 0.3033859285066827, 'weight_xgb_class_0': 0.06936011863272164, 'weight_xgb_class_1': 0.6587386514041963, 'weight_xgb_class_2': 0.6375978691107375}. Best is trial 54 with value: 0.9495246095989627.

[I 2026-07-05 15:31:32,821] Trial 60 finished with value: 0.890992648768148 and parameters: {'weight_lgbm_class_0': 0.9906422345343275, 'weight_lgbm_class_1': 0.8641783350046356, 'weight_lgbm_class_2': 0.24252833928374645, 'weight_xgb_class_0': 0.0725594204579115, 'weight_xgb_class_1': 0.6044323849438417, 'weight_xgb_class_2': 0.8793892976616718}. Best is trial 54 with value: 0.9495246095989627.
[I 2026-07-05 15:31:32,853] Trial 61 finished with value: 0.909879627571076 and parameters: {'weight_lgbm_class_0': 0.78516407778266, 'weight_lgbm_class_1': 0.8940765363129259, 'weight_lgbm_class_2': 0.7534249514253117, 'weight_xgb_class_0': 0.0588164618209005, 'weight_xgb_class_1': 0.6149894641711766, 'weight_xgb_class_2': 0.5332179636863719}. Best is trial 54 with value: 0.9495246095989627.
[I 2026-07-05 15:31:32,876] Trial 62 finished with value: 0.9395528008674479 and parameters: {'weight_lgbm_class_0': 0.24268501631174588, 'weight_lgbm_class_1': 0.7407637097829474, 'weight_lgbm_class_2': 0.237446286975112, 'weight_xgb_class_0': 0.06891302846945918, 'weight_xgb_class_1': 0.6120593852064061, 'weight_xgb_class_2': 0.6334748779267404}. Best is trial 54 with value: 0.9495246095989627.
[I 2026-07-05 15:31:32,888] Trial 63 finished with value: 0.9418816764067262 and parameters: {'weight_lgbm_class_0': 0.37791412595175955, 'weight_lgbm_class_1': 0.8558318968476069, 'weight_lgbm_class_2': 0.7502348129943618, 'weight_xgb_class_0': 0.06969479051557295, 'weight_xgb_class_1': 0.8629070635174059, 'weight_xgb_class_2': 0.8774640253073874}. Best is trial 54 with value: 0.9495246095989627.
[I 2026-07-05 15:31:32,930] Trial 65 finished with value: 0.9310890347847064 and parameters: {'weight_lgbm_class_0': 0.23866795033595883, 'weight_lgbm_class_1': 0.742892397163671, 'weight_lgbm_class_2': 0.2796153237690173, 'weight_xgb_class_0': 0.15573781682192223, 'weight_xgb_class_1': 0.7923013001004443, 'weight_xgb_class_2': 0.5144742381540494}. Best is trial 54 with value: 0.9495246095989627.
[I 2026-07-05 15:31:32,931] Trial 64 finished with value: 0.9114428207512922 and parameters: {'weight_lgbm_class_0': 0.3721266357241224, 'weight_lgbm_class_1': 0.7547953103897467, 'weight_lgbm_class_2': 0.26597760201766074, 'weight_xgb_class_0': 0.24304410412976651, 'weight_xgb_class_1': 0.8019418512068672, 'weight_xgb_class_2': 0.5219082122620671}. Best is trial 54 with value: 0.9495246095989627.
[I 2026-07-05 15:31:32,963] Trial 66 finished with value: 0.904374839910082 and parameters: {'weight_lgbm_class_0': 0.40540552807907937, 'weight_lgbm_class_1': 0.8731836950430429, 'weight_lgbm_class_2': 0.15279997636313794, 'weight_xgb_class_0': 0.2437645186866292, 'weight_xgb_class_1': 0.8271927376074845, 'weight_xgb_class_2': 0.5136387064571206}. Best is trial 54 with value: 0.9495246095989627.
[I 2026-07-05 15:31:32,988] Trial 67 finished with value: 0.9344093223257942 and parameters: {'weight_lgbm_class_0': 0.2291110015490964, 'weight_lgbm_class_1': 0.7661610285397775, 'weight_lgbm_class_2': 0.15699588392840452, 'weight_xgb_class_0': 0.15077666068419068, 'weight_xgb_class_1': 0.8007520211682552, 'weight_xgb_class_2': 0.6953544946540409}. Best is trial 54 with value: 0.9495246095989627.
[I 2026-07-05 15:31:33,015] Trial 68 finished with value: 0.9436004718396477 and parameters: {'weight_lgbm_class_0': 0.22767160863428862, 'weight_lgbm_class_1': 0.754772013530949, 'weight_lgbm_class_2': 0.9595772914280268, 'weight_xgb_class_0': 0.1442445297007947, 'weight_xgb_class_1': 0.8119949635490288, 'weight_xgb_class_2': 0.5354873873119228}. Best is trial 54 with value: 0.9495246095989627.

Best trial: 54. Best value: 0.949525:   4%|█████▏                                                                                                                                | 78/2000 [00:01<00:42, 44.71it/s]

[I 2026-07-05 15:31:33,030] Trial 70 finished with value: 0.9483514065958772 and parameters: {'weight_lgbm_class_0': 0.09828576876554947, 'weight_lgbm_class_1': 0.8097348666627219, 'weight_lgbm_class_2': 0.9477827754600501, 'weight_xgb_class_0': 0.15314240427640485, 'weight_xgb_class_1': 0.7986217162165732, 'weight_xgb_class_2': 0.7115646020694308}. Best is trial 54 with value: 0.9495246095989627.
[I 2026-07-05 15:31:33,060] Trial 69 finished with value: 0.9485842361398545 and parameters: {'weight_lgbm_class_0': 0.09807148337911756, 'weight_lgbm_class_1': 0.8185025831067072, 'weight_lgbm_class_2': 0.9559339480843871, 'weight_xgb_class_0': 0.13899802600486233, 'weight_xgb_class_1': 0.7893573018039299, 'weight_xgb_class_2': 0.7061953998676849}. Best is trial 54 with value: 0.9495246095989627.
[I 2026-07-05 15:31:33,083] Trial 71 finished with value: 0.9424370489533599 and parameters: {'weight_lgbm_class_0': 0.11018563047868214, 'weight_lgbm_class_1': 0.7921004280580681, 'weight_lgbm_class_2': 0.06736233498088473, 'weight_xgb_class_0': 0.14771536650632255, 'weight_xgb_class_1': 0.7609991066778721, 'weight_xgb_class_2': 0.6986089828847625}. Best is trial 54 with value: 0.9495246095989627.
[I 2026-07-05 15:31:33,103] Trial 72 finished with value: 0.9479576435907111 and parameters: {'weight_lgbm_class_0': 0.10888998342360107, 'weight_lgbm_class_1': 0.7950074641854491, 'weight_lgbm_class_2': 0.9653308969807213, 'weight_xgb_class_0': 0.1495560081829562, 'weight_xgb_class_1': 0.7103021424750374, 'weight_xgb_class_2': 0.7081481062005427}. Best is trial 54 with value: 0.9495246095989627.
[I 2026-07-05 15:31:33,112] Trial 73 finished with value: 0.9473054576709471 and parameters: {'weight_lgbm_class_0': 0.11065032922360045, 'weight_lgbm_class_1': 0.5875529509236357, 'weight_lgbm_class_2': 0.9728974405588738, 'weight_xgb_class_0': 0.14423069202246194, 'weight_xgb_class_1': 0.6940091901112422, 'weight_xgb_class_2': 0.6978282546738549}. Best is trial 54 with value: 0.9495246095989627.
[I 2026-07-05 15:31:33,172] Trial 75 finished with value: 0.9473220485829951 and parameters: {'weight_lgbm_class_0': 0.10621153439969841, 'weight_lgbm_class_1': 0.5667627822386411, 'weight_lgbm_class_2': 0.9712999105341656, 'weight_xgb_class_0': 0.1426006556976952, 'weight_xgb_class_1': 0.6861729662428449, 'weight_xgb_class_2': 0.714481133479019}. Best is trial 54 with value: 0.9495246095989627.
[I 2026-07-05 15:31:33,175] Trial 74 finished with value: 0.943981926371737 and parameters: {'weight_lgbm_class_0': 0.10347573791239384, 'weight_lgbm_class_1': 0.5915079044780429, 'weight_lgbm_class_2': 0.972506606510518, 'weight_xgb_class_0': 0.22188767528637093, 'weight_xgb_class_1': 0.5641843312069, 'weight_xgb_class_2': 0.7177887836648017}. Best is trial 54 with value: 0.9495246095989627.
[I 2026-07-05 15:31:33,194] Trial 76 finished with value: 0.9455020544944904 and parameters: {'weight_lgbm_class_0': 0.0449935555809137, 'weight_lgbm_class_1': 0.8127175695798289, 'weight_lgbm_class_2': 0.3786628739652602, 'weight_xgb_class_0': 0.2249144952711898, 'weight_xgb_class_1': 0.7141506346992841, 'weight_xgb_class_2': 0.7089928957093737}. Best is trial 54 with value: 0.9495246095989627.
[I 2026-07-05 15:31:33,221] Trial 77 finished with value: 0.9488087847238914 and parameters: {'weight_lgbm_class_0': 0.034016553854245346, 'weight_lgbm_class_1': 0.9870662622733944, 'weight_lgbm_class_2': 0.9894717686057428, 'weight_xgb_class_0': 0.21228036475244572, 'weight_xgb_class_1': 0.9558458055014706, 'weight_xgb_class_2': 0.7120642087634595}. Best is trial 54 with value: 0.9495246095989627.
[I 2026-07-05 15:31:33,237] Trial 78 finished with value: 0.9469360001087544 and parameters: {'weight_lgbm_class_0': 0.046791582225025934, 'weight_lgbm_class_1': 0.5877490071647583, 'weight_lgbm_class_2': 0.9748373493223219, 'weight_xgb_class_0': 0.22092940813445172, 'weight_xgb_class_1': 0.7071265838625881, 'weight_xgb_class_2': 0.6999928505035558}. Best is trial 54 with value: 0.9495246095989627.

Best trial: 54. Best value: 0.949525:   4%|█████▉                                                                                                                                | 88/2000 [00:02<00:43, 44.21it/s]

[I 2026-07-05 15:31:33,274] Trial 79 finished with value: 0.9307208461222974 and parameters: {'weight_lgbm_class_0': 0.043748576724784674, 'weight_lgbm_class_1': 0.8264803842636409, 'weight_lgbm_class_2': 0.9995291896284296, 'weight_xgb_class_0': 0.6239824990146124, 'weight_xgb_class_1': 0.7155342516633589, 'weight_xgb_class_2': 0.7145818285810145}. Best is trial 54 with value: 0.9495246095989627.
[I 2026-07-05 15:31:33,295] Trial 80 finished with value: 0.9472565794403347 and parameters: {'weight_lgbm_class_0': 0.03350172434606651, 'weight_lgbm_class_1': 0.5891632440398736, 'weight_lgbm_class_2': 0.981097443330103, 'weight_xgb_class_0': 0.2331419855209942, 'weight_xgb_class_1': 0.7310458585711912, 'weight_xgb_class_2': 0.716957471606052}. Best is trial 54 with value: 0.9495246095989627.
[I 2026-07-05 15:31:33,315] Trial 81 finished with value: 0.9480231915304324 and parameters: {'weight_lgbm_class_0': 0.04945894749566599, 'weight_lgbm_class_1': 0.5935722783191255, 'weight_lgbm_class_2': 0.9450620236417488, 'weight_xgb_class_0': 0.22058720799528864, 'weight_xgb_class_1': 0.949266328391281, 'weight_xgb_class_2': 0.931658878445652}. Best is trial 54 with value: 0.9495246095989627.
[I 2026-07-05 15:31:33,335] Trial 82 finished with value: 0.9479606039503489 and parameters: {'weight_lgbm_class_0': 0.03531091633618097, 'weight_lgbm_class_1': 0.8061106919712444, 'weight_lgbm_class_2': 0.9505927031288178, 'weight_xgb_class_0': 0.22713270466479657, 'weight_xgb_class_1': 0.7146204743391451, 'weight_xgb_class_2': 0.716027638506357}. Best is trial 54 with value: 0.9495246095989627.
[I 2026-07-05 15:31:33,344] Trial 83 finished with value: 0.9481022178047841 and parameters: {'weight_lgbm_class_0': 0.044704480041112354, 'weight_lgbm_class_1': 0.8070678569464459, 'weight_lgbm_class_2': 0.9983487955725829, 'weight_xgb_class_0': 0.2095065131814121, 'weight_xgb_class_1': 0.7140193790354257, 'weight_xgb_class_2': 0.7152871857468317}. Best is trial 54 with value: 0.9495246095989627.
[I 2026-07-05 15:31:33,378] Trial 84 finished with value: 0.9277737757242339 and parameters: {'weight_lgbm_class_0': 0.04238073473544619, 'weight_lgbm_class_1': 0.5891668268917899, 'weight_lgbm_class_2': 0.9932650963700465, 'weight_xgb_class_0': 0.6421812647735774, 'weight_xgb_class_1': 0.6880760857646754, 'weight_xgb_class_2': 0.9255459172543062}. Best is trial 54 with value: 0.9495246095989627.
[I 2026-07-05 15:31:33,389] Trial 85 finished with value: 0.9420586160530213 and parameters: {'weight_lgbm_class_0': 0.17265802620546955, 'weight_lgbm_class_1': 0.8253902419920837, 'weight_lgbm_class_2': 0.9863960869855324, 'weight_xgb_class_0': 0.320302631030688, 'weight_xgb_class_1': 0.9632352952508452, 'weight_xgb_class_2': 0.9146792617015479}. Best is trial 54 with value: 0.9495246095989627.
[I 2026-07-05 15:31:33,424] Trial 86 finished with value: 0.9464772746721564 and parameters: {'weight_lgbm_class_0': 0.02578606087698715, 'weight_lgbm_class_1': 0.8242706304109589, 'weight_lgbm_class_2': 0.9228157972815408, 'weight_xgb_class_0': 0.3358364199768682, 'weight_xgb_class_1': 0.9480562439984641, 'weight_xgb_class_2': 0.9257448459755233}. Best is trial 54 with value: 0.9495246095989627.
[I 2026-07-05 15:31:33,462] Trial 87 finished with value: 0.9422412931826969 and parameters: {'weight_lgbm_class_0': 0.1620040904665311, 'weight_lgbm_class_1': 0.9776470632551227, 'weight_lgbm_class_2': 0.9197024393741976, 'weight_xgb_class_0': 0.3232638237902403, 'weight_xgb_class_1': 0.994424620799462, 'weight_xgb_class_2': 0.8046190096583898}. Best is trial 54 with value: 0.9495246095989627.
[I 2026-07-05 15:31:33,467] Trial 88 finished with value: 0.9440779780098602 and parameters: {'weight_lgbm_class_0': 0.16933392769333133, 'weight_lgbm_class_1': 0.982008878449736, 'weight_lgbm_class_2': 0.9177763606298855, 'weight_xgb_class_0': 0.2621481121098176, 'weight_xgb_class_1': 0.9374483316147134, 'weight_xgb_class_2': 0.8162371143277778}. Best is trial 54 with value: 0.9495246095989627.

Best trial: 96. Best value: 0.949556:   5%|██████▍                                                                                                                               | 97/2000 [00:02<00:43, 43.71it/s]

[I 2026-07-05 15:31:33,505] Trial 89 finished with value: 0.9464787209057879 and parameters: {'weight_lgbm_class_0': 0.16765768273991905, 'weight_lgbm_class_1': 0.705971790116794, 'weight_lgbm_class_2': 0.9285395914908285, 'weight_xgb_class_0': 0.16838669485389227, 'weight_xgb_class_1': 0.952293177826246, 'weight_xgb_class_2': 0.8065193520593479}. Best is trial 54 with value: 0.9495246095989627.
[I 2026-07-05 15:31:33,511] Trial 90 finished with value: 0.9485356779598443 and parameters: {'weight_lgbm_class_0': 0.0009748553001638072, 'weight_lgbm_class_1': 0.7168950365090956, 'weight_lgbm_class_2': 0.9182699224546583, 'weight_xgb_class_0': 0.26250913402753007, 'weight_xgb_class_1': 0.9932917258524151, 'weight_xgb_class_2': 0.9215728101148306}. Best is trial 54 with value: 0.9495246095989627.
[I 2026-07-05 15:31:33,520] Trial 91 finished with value: 0.9410404162239855 and parameters: {'weight_lgbm_class_0': 0.17162306893619272, 'weight_lgbm_class_1': 0.7941120865075014, 'weight_lgbm_class_2': 0.9192033402756252, 'weight_xgb_class_0': 0.33869092640467924, 'weight_xgb_class_1': 0.9635209335161272, 'weight_xgb_class_2': 0.9398000156242778}. Best is trial 54 with value: 0.9495246095989627.
[I 2026-07-05 15:31:33,555] Trial 92 finished with value: 0.9419465103105408 and parameters: {'weight_lgbm_class_0': 0.16205966305907216, 'weight_lgbm_class_1': 0.9969405316454927, 'weight_lgbm_class_2': 0.913066660540787, 'weight_xgb_class_0': 0.3266994300158656, 'weight_xgb_class_1': 0.9513586546365512, 'weight_xgb_class_2': 0.8055206796234089}. Best is trial 54 with value: 0.9495246095989627.
[I 2026-07-05 15:31:33,561] Trial 93 finished with value: 0.9484399494268932 and parameters: {'weight_lgbm_class_0': 0.00047496447413857, 'weight_lgbm_class_1': 0.7902708485428197, 'weight_lgbm_class_2': 0.9172530626906977, 'weight_xgb_class_0': 0.2579970342539021, 'weight_xgb_class_1': 0.9375097377625133, 'weight_xgb_class_2': 0.8021942039647634}. Best is trial 54 with value: 0.9495246095989627.
[I 2026-07-05 15:31:33,587] Trial 94 finished with value: 0.9464755187168542 and parameters: {'weight_lgbm_class_0': 0.1676393022684125, 'weight_lgbm_class_1': 0.7898438141814884, 'weight_lgbm_class_2': 0.9416766277307529, 'weight_xgb_class_0': 0.17492555891140812, 'weight_xgb_class_1': 0.9243285365196736, 'weight_xgb_class_2': 0.7958898047840149}. Best is trial 54 with value: 0.9495246095989627.
[I 2026-07-05 15:31:33,642] Trial 96 finished with value: 0.94955569619073 and parameters: {'weight_lgbm_class_0': 0.024144452748799228, 'weight_lgbm_class_1': 0.7913786625003437, 'weight_lgbm_class_2': 0.9401763514730591, 'weight_xgb_class_0': 0.1700693080648415, 'weight_xgb_class_1': 0.8682302123343129, 'weight_xgb_class_2': 0.7740740428486309}. Best is trial 96 with value: 0.94955569619073.
[I 2026-07-05 15:31:33,657] Trial 97 finished with value: 0.949399190363401 and parameters: {'weight_lgbm_class_0': 0.021727570128773115, 'weight_lgbm_class_1': 0.7849851874102994, 'weight_lgbm_class_2': 0.9556118759041534, 'weight_xgb_class_0': 0.17728678097186934, 'weight_xgb_class_1': 0.9103136472412289, 'weight_xgb_class_2': 0.6679196033561865}. Best is trial 96 with value: 0.94955569619073.
[I 2026-07-05 15:31:33,659] Trial 95 finished with value: 0.9483602440434803 and parameters: {'weight_lgbm_class_0': 0.01075709331995979, 'weight_lgbm_class_1': 0.7850493971021599, 'weight_lgbm_class_2': 0.948927257154632, 'weight_xgb_class_0': 0.25855855022802404, 'weight_xgb_class_1': 0.933355727902316, 'weight_xgb_class_2': 0.7858138160969304}. Best is trial 96 with value: 0.94955569619073.

Best trial: 96. Best value: 0.949556:   5%|███████                                                                                                                              | 107/2000 [00:02<00:42, 44.88it/s]

[I 2026-07-05 15:31:33,675] Trial 98 finished with value: 0.9485479588499225 and parameters: {'weight_lgbm_class_0': 0.005749656398567393, 'weight_lgbm_class_1': 0.7900665970991063, 'weight_lgbm_class_2': 0.9516601287439763, 'weight_xgb_class_0': 0.26352981426289634, 'weight_xgb_class_1': 0.9281084118520199, 'weight_xgb_class_2': 0.9572818955693171}. Best is trial 96 with value: 0.94955569619073.
[I 2026-07-05 15:31:33,712] Trial 99 finished with value: 0.9493397900072994 and parameters: {'weight_lgbm_class_0': 0.0006208206093150925, 'weight_lgbm_class_1': 0.669061244143663, 'weight_lgbm_class_2': 0.9432488297734397, 'weight_xgb_class_0': 0.1989137859036686, 'weight_xgb_class_1': 0.9111085041781692, 'weight_xgb_class_2': 0.9686415114298328}. Best is trial 96 with value: 0.94955569619073.
[I 2026-07-05 15:31:33,760] Trial 101 finished with value: 0.9481650883778885 and parameters: {'weight_lgbm_class_0': 0.009907747455326021, 'weight_lgbm_class_1': 0.9388535742024992, 'weight_lgbm_class_2': 0.9468333295489285, 'weight_xgb_class_0': 0.2837921259209485, 'weight_xgb_class_1': 0.9159381710190879, 'weight_xgb_class_2': 0.8497144993890114}. Best is trial 96 with value: 0.94955569619073.
[I 2026-07-05 15:31:33,764] Trial 100 finished with value: 0.9479193722839497 and parameters: {'weight_lgbm_class_0': 0.004343646062048444, 'weight_lgbm_class_1': 0.6717536359224365, 'weight_lgbm_class_2': 0.9486602753222684, 'weight_xgb_class_0': 0.277298992679353, 'weight_xgb_class_1': 0.9202554617110095, 'weight_xgb_class_2': 0.9021461259648299}. Best is trial 96 with value: 0.94955569619073.
[I 2026-07-05 15:31:33,778] Trial 102 finished with value: 0.9476723184984962 and parameters: {'weight_lgbm_class_0': 0.0011517923230537491, 'weight_lgbm_class_1': 0.6711845151216512, 'weight_lgbm_class_2': 0.8397332867191677, 'weight_xgb_class_0': 0.26955555575225704, 'weight_xgb_class_1': 0.888673254220288, 'weight_xgb_class_2': 0.7759965135849305}. Best is trial 96 with value: 0.94955569619073.
[I 2026-07-05 15:31:33,795] Trial 103 finished with value: 0.9494158777724112 and parameters: {'weight_lgbm_class_0': 0.0019743743177807254, 'weight_lgbm_class_1': 0.6633209642368884, 'weight_lgbm_class_2': 0.944399514461374, 'weight_xgb_class_0': 0.19761473747601072, 'weight_xgb_class_1': 0.8905751902889251, 'weight_xgb_class_2': 0.8509716658966803}. Best is trial 96 with value: 0.94955569619073.
[I 2026-07-05 15:31:33,826] Trial 104 finished with value: 0.9479616325418257 and parameters: {'weight_lgbm_class_0': 0.01483368455824006, 'weight_lgbm_class_1': 0.6739659728718075, 'weight_lgbm_class_2': 0.8981585020716282, 'weight_xgb_class_0': 0.25942757890214957, 'weight_xgb_class_1': 0.8980880993635673, 'weight_xgb_class_2': 0.861738350138354}. Best is trial 96 with value: 0.94955569619073.
[I 2026-07-05 15:31:33,860] Trial 105 finished with value: 0.9483601292534435 and parameters: {'weight_lgbm_class_0': 0.0008938427473597875, 'weight_lgbm_class_1': 0.6803669241882704, 'weight_lgbm_class_2': 0.9049642185209081, 'weight_xgb_class_0': 0.2601265374356908, 'weight_xgb_class_1': 0.8956149025139947, 'weight_xgb_class_2': 0.9679034116772625}. Best is trial 96 with value: 0.94955569619073.
[I 2026-07-05 15:31:33,877] Trial 106 finished with value: 0.9454898984622048 and parameters: {'weight_lgbm_class_0': 0.005114297022491603, 'weight_lgbm_class_1': 0.724778252189736, 'weight_lgbm_class_2': 0.836532915649173, 'weight_xgb_class_0': 0.36266579596524373, 'weight_xgb_class_1': 0.9061632549718346, 'weight_xgb_class_2': 0.8958316774039911}. Best is trial 96 with value: 0.94955569619073.
[I 2026-07-05 15:31:33,893] Trial 107 finished with value: 0.9455389768979966 and parameters: {'weight_lgbm_class_0': 0.0023591060479744544, 'weight_lgbm_class_1': 0.6767035314350192, 'weight_lgbm_class_2': 0.8375513209825407, 'weight_xgb_class_0': 0.36689977583071665, 'weight_xgb_class_1': 0.9079891082005774, 'weight_xgb_class_2': 0.9773789148099581}. Best is trial 96 with value: 0.94955569619073.

Best trial: 96. Best value: 0.949556:   6%|███████▊                                                                                                                             | 118/2000 [00:02<00:40, 46.53it/s]

[I 2026-07-05 15:31:33,908] Trial 108 finished with value: 0.9473379213496659 and parameters: {'weight_lgbm_class_0': 0.005378568780183907, 'weight_lgbm_class_1': 0.6657980419788883, 'weight_lgbm_class_2': 0.8366480014739283, 'weight_xgb_class_0': 0.2992354292965494, 'weight_xgb_class_1': 0.9055083325379099, 'weight_xgb_class_2': 0.9728205505935097}. Best is trial 96 with value: 0.94955569619073.
[I 2026-07-05 15:31:33,948] Trial 109 finished with value: 0.9483012180809505 and parameters: {'weight_lgbm_class_0': 0.0037245255085320995, 'weight_lgbm_class_1': 0.7155581527015646, 'weight_lgbm_class_2': 0.8396052397574361, 'weight_xgb_class_0': 0.2511179945179806, 'weight_xgb_class_1': 0.8760176659429827, 'weight_xgb_class_2': 0.8484044358643418}. Best is trial 96 with value: 0.94955569619073.
[I 2026-07-05 15:31:33,971] Trial 111 finished with value: 0.9484704251595694 and parameters: {'weight_lgbm_class_0': 0.06398388174302783, 'weight_lgbm_class_1': 0.7392628785269622, 'weight_lgbm_class_2': 0.8996117629861231, 'weight_xgb_class_0': 0.1976409742742312, 'weight_xgb_class_1': 0.893034778839488, 'weight_xgb_class_2': 0.9651844961974179}. Best is trial 96 with value: 0.94955569619073.
[I 2026-07-05 15:31:33,981] Trial 110 finished with value: 0.9483778629997098 and parameters: {'weight_lgbm_class_0': 0.06898849114009922, 'weight_lgbm_class_1': 0.7246806985088028, 'weight_lgbm_class_2': 0.8996856331025098, 'weight_xgb_class_0': 0.19293624476958252, 'weight_xgb_class_1': 0.8738554433130638, 'weight_xgb_class_2': 0.9536254606993511}. Best is trial 96 with value: 0.94955569619073.
[I 2026-07-05 15:31:34,017] Trial 112 finished with value: 0.948608600667941 and parameters: {'weight_lgbm_class_0': 0.06264944998767555, 'weight_lgbm_class_1': 0.7311845133003946, 'weight_lgbm_class_2': 0.898090275574709, 'weight_xgb_class_0': 0.1930274459085345, 'weight_xgb_class_1': 0.8898259238890203, 'weight_xgb_class_2': 0.9668933034702734}. Best is trial 96 with value: 0.94955569619073.
[I 2026-07-05 15:31:34,028] Trial 113 finished with value: 0.9482244645916155 and parameters: {'weight_lgbm_class_0': 0.07637484979316105, 'weight_lgbm_class_1': 0.7268233402055044, 'weight_lgbm_class_2': 0.8353586867021094, 'weight_xgb_class_0': 0.1870084309595459, 'weight_xgb_class_1': 0.8527809279537353, 'weight_xgb_class_2': 0.9539719919495978}. Best is trial 96 with value: 0.94955569619073.
[I 2026-07-05 15:31:34,061] Trial 115 finished with value: 0.9482125423898351 and parameters: {'weight_lgbm_class_0': 0.06447757564397659, 'weight_lgbm_class_1': 0.7219455267361762, 'weight_lgbm_class_2': 0.8941547868023229, 'weight_xgb_class_0': 0.19611702267863523, 'weight_xgb_class_1': 0.8615895451761351, 'weight_xgb_class_2': 0.8305524113137573}. Best is trial 96 with value: 0.94955569619073.
[I 2026-07-05 15:31:34,062] Trial 114 finished with value: 0.9481963374420297 and parameters: {'weight_lgbm_class_0': 0.06326584016123521, 'weight_lgbm_class_1': 0.6395664511157109, 'weight_lgbm_class_2': 0.8975023354126952, 'weight_xgb_class_0': 0.19145480751557137, 'weight_xgb_class_1': 0.8575512727578308, 'weight_xgb_class_2': 0.9491551222031457}. Best is trial 96 with value: 0.94955569619073.
[I 2026-07-05 15:31:34,092] Trial 116 finished with value: 0.9483464937074184 and parameters: {'weight_lgbm_class_0': 0.06576532052450769, 'weight_lgbm_class_1': 0.7265410630106871, 'weight_lgbm_class_2': 0.7822337627878833, 'weight_xgb_class_0': 0.19187964377297495, 'weight_xgb_class_1': 0.8610725004369238, 'weight_xgb_class_2': 0.9577829496034947}. Best is trial 96 with value: 0.94955569619073.
[I 2026-07-05 15:31:34,107] Trial 117 finished with value: 0.947884428285091 and parameters: {'weight_lgbm_class_0': 0.0618872828659405, 'weight_lgbm_class_1': 0.6177726663836683, 'weight_lgbm_class_2': 0.8987186215052922, 'weight_xgb_class_0': 0.18842260277529282, 'weight_xgb_class_1': 0.8560792462572138, 'weight_xgb_class_2': 0.65998509264182}. Best is trial 96 with value: 0.94955569619073.
[I 2026-07-05 15:31:34,127] Trial 118 finished with value: 0.9487694589970413 and parameters: {'weight_lgbm_class_0': 0.06840859287448685, 'weight_lgbm_class_1': 0.7652078220080116, 'weight_lgbm_class_2': 0.8912195763061297, 'weight_xgb_class_0': 0.18236351714285126, 'weight_xgb_class_1': 0.9994890318065484, 'weight_xgb_class_2': 0.9543847523434341}. Best is trial 96 with value: 0.94955569619073.

Best trial: 96. Best value: 0.949556:   6%|████████▍                                                                                                                            | 127/2000 [00:03<00:42, 43.67it/s]

[I 2026-07-05 15:31:34,155] Trial 119 finished with value: 0.9492285248178218 and parameters: {'weight_lgbm_class_0': 0.06573024753992882, 'weight_lgbm_class_1': 0.7696365596420314, 'weight_lgbm_class_2': 0.784285565622961, 'weight_xgb_class_0': 0.1237968940833317, 'weight_xgb_class_1': 0.8496410534483986, 'weight_xgb_class_2': 0.6634469717059859}. Best is trial 96 with value: 0.94955569619073.
[I 2026-07-05 15:31:34,169] Trial 120 finished with value: 0.9484084126101692 and parameters: {'weight_lgbm_class_0': 0.060597657800673554, 'weight_lgbm_class_1': 0.7661794589293991, 'weight_lgbm_class_2': 0.8897878721655376, 'weight_xgb_class_0': 0.19886548154305989, 'weight_xgb_class_1': 0.8484185953771883, 'weight_xgb_class_2': 0.9053603891859179}. Best is trial 96 with value: 0.94955569619073.
[I 2026-07-05 15:31:34,198] Trial 121 finished with value: 0.9484718620845219 and parameters: {'weight_lgbm_class_0': 0.06109388784170165, 'weight_lgbm_class_1': 0.7686016623862463, 'weight_lgbm_class_2': 0.7850124276751114, 'weight_xgb_class_0': 0.1940230065965343, 'weight_xgb_class_1': 0.8493703692942087, 'weight_xgb_class_2': 0.9917455282503584}. Best is trial 96 with value: 0.94955569619073.
[I 2026-07-05 15:31:34,237] Trial 122 finished with value: 0.9493945725115917 and parameters: {'weight_lgbm_class_0': 0.05934612716092869, 'weight_lgbm_class_1': 0.6414855970165187, 'weight_lgbm_class_2': 0.8853516997562714, 'weight_xgb_class_0': 0.1287093656113527, 'weight_xgb_class_1': 0.8416067125164486, 'weight_xgb_class_2': 0.8927544420340124}. Best is trial 96 with value: 0.94955569619073.
[I 2026-07-05 15:31:34,260] Trial 124 finished with value: 0.949299527546588 and parameters: {'weight_lgbm_class_0': 0.09019040140748703, 'weight_lgbm_class_1': 0.6199137814917908, 'weight_lgbm_class_2': 0.7696673434376935, 'weight_xgb_class_0': 0.11990739705193312, 'weight_xgb_class_1': 0.9858600344407118, 'weight_xgb_class_2': 0.9926307252499218}. Best is trial 96 with value: 0.94955569619073.
[I 2026-07-05 15:31:34,261] Trial 123 finished with value: 0.9493909872087279 and parameters: {'weight_lgbm_class_0': 0.0920745216293884, 'weight_lgbm_class_1': 0.7658261417706066, 'weight_lgbm_class_2': 0.8755778646083863, 'weight_xgb_class_0': 0.12882637343107695, 'weight_xgb_class_1': 0.9934785638609047, 'weight_xgb_class_2': 0.9965548642115556}. Best is trial 96 with value: 0.94955569619073.
[I 2026-07-05 15:31:34,293] Trial 125 finished with value: 0.9486035945773309 and parameters: {'weight_lgbm_class_0': 0.09215241454140474, 'weight_lgbm_class_1': 0.7675753252279625, 'weight_lgbm_class_2': 0.8746923930501633, 'weight_xgb_class_0': 0.16990210413694853, 'weight_xgb_class_1': 0.9865115956478856, 'weight_xgb_class_2': 0.9943334033070934}. Best is trial 96 with value: 0.94955569619073.
[I 2026-07-05 15:31:34,344] Trial 127 finished with value: 0.9494219212617598 and parameters: {'weight_lgbm_class_0': 0.08840862557352977, 'weight_lgbm_class_1': 0.7709715400170654, 'weight_lgbm_class_2': 0.856108041483708, 'weight_xgb_class_0': 0.12236848012585741, 'weight_xgb_class_1': 0.9986876661420876, 'weight_xgb_class_2': 0.912363073491669}. Best is trial 96 with value: 0.94955569619073.
[I 2026-07-05 15:31:34,352] Trial 126 finished with value: 0.9492199205693869 and parameters: {'weight_lgbm_class_0': 0.09314226815856695, 'weight_lgbm_class_1': 0.76758490112564, 'weight_lgbm_class_2': 0.8595947375071048, 'weight_xgb_class_0': 0.1269460039858648, 'weight_xgb_class_1': 0.9933775566048996, 'weight_xgb_class_2': 0.8959234048390915}. Best is trial 96 with value: 0.94955569619073.

Best trial: 139. Best value: 0.949647:   7%|█████████                                                                                                                           | 137/2000 [00:03<00:40, 45.46it/s]

[I 2026-07-05 15:31:34,355] Trial 128 finished with value: 0.9493953485746798 and parameters: {'weight_lgbm_class_0': 0.032962965089636045, 'weight_lgbm_class_1': 0.7697817620708234, 'weight_lgbm_class_2': 0.7788148547008454, 'weight_xgb_class_0': 0.16563189647128954, 'weight_xgb_class_1': 0.8347725489488542, 'weight_xgb_class_2': 0.8976123709593281}. Best is trial 96 with value: 0.94955569619073.
[I 2026-07-05 15:31:34,377] Trial 129 finished with value: 0.94888730190966 and parameters: {'weight_lgbm_class_0': 0.09092902917726847, 'weight_lgbm_class_1': 0.7684405541451163, 'weight_lgbm_class_2': 0.9690236480918967, 'weight_xgb_class_0': 0.12750289132932985, 'weight_xgb_class_1': 0.8306109251948881, 'weight_xgb_class_2': 0.6741212267174087}. Best is trial 96 with value: 0.94955569619073.
[I 2026-07-05 15:31:34,399] Trial 130 finished with value: 0.9494337563780534 and parameters: {'weight_lgbm_class_0': 0.0877481406324352, 'weight_lgbm_class_1': 0.8484915050971666, 'weight_lgbm_class_2': 0.8606143126773407, 'weight_xgb_class_0': 0.12425127124200366, 'weight_xgb_class_1': 0.9934343055754182, 'weight_xgb_class_2': 0.8788214892866246}. Best is trial 96 with value: 0.94955569619073.
[I 2026-07-05 15:31:34,424] Trial 131 finished with value: 0.9486575946345059 and parameters: {'weight_lgbm_class_0': 0.12522100955237267, 'weight_lgbm_class_1': 0.6954481749333981, 'weight_lgbm_class_2': 0.8602713049957575, 'weight_xgb_class_0': 0.12914059576413245, 'weight_xgb_class_1': 0.9788328525797847, 'weight_xgb_class_2': 0.9923624365178796}. Best is trial 96 with value: 0.94955569619073.
[I 2026-07-05 15:31:34,456] Trial 132 finished with value: 0.9488881085435038 and parameters: {'weight_lgbm_class_0': 0.088012934170389, 'weight_lgbm_class_1': 0.6152016940566885, 'weight_lgbm_class_2': 0.7271633855351706, 'weight_xgb_class_0': 0.127644604522673, 'weight_xgb_class_1': 0.8294876654851242, 'weight_xgb_class_2': 0.9992432029535712}. Best is trial 96 with value: 0.94955569619073.
[I 2026-07-05 15:31:34,470] Trial 133 finished with value: 0.9484763799958832 and parameters: {'weight_lgbm_class_0': 0.12299182680080273, 'weight_lgbm_class_1': 0.8447951446452703, 'weight_lgbm_class_2': 0.7754560001389658, 'weight_xgb_class_0': 0.12321572974479222, 'weight_xgb_class_1': 0.7702406912090396, 'weight_xgb_class_2': 0.8891614573908658}. Best is trial 96 with value: 0.94955569619073.
[I 2026-07-05 15:31:34,502] Trial 134 finished with value: 0.9496161680992469 and parameters: {'weight_lgbm_class_0': 0.02943188104206753, 'weight_lgbm_class_1': 0.6154184009961318, 'weight_lgbm_class_2': 0.8643922843469205, 'weight_xgb_class_0': 0.12131062208972626, 'weight_xgb_class_1': 0.9751873257499152, 'weight_xgb_class_2': 0.8887176901330682}. Best is trial 134 with value: 0.9496161680992469.
[I 2026-07-05 15:31:34,526] Trial 135 finished with value: 0.9496350853863924 and parameters: {'weight_lgbm_class_0': 0.030032140269824894, 'weight_lgbm_class_1': 0.65097375534209, 'weight_lgbm_class_2': 0.727610083650997, 'weight_xgb_class_0': 0.11630202375000052, 'weight_xgb_class_1': 0.9776323184782191, 'weight_xgb_class_2': 0.8653184204651315}. Best is trial 135 with value: 0.9496350853863924.
[I 2026-07-05 15:31:34,544] Trial 136 finished with value: 0.948621413681821 and parameters: {'weight_lgbm_class_0': 0.12056466125275772, 'weight_lgbm_class_1': 0.843684240794636, 'weight_lgbm_class_2': 0.7243593592322329, 'weight_xgb_class_0': 0.11432624888785137, 'weight_xgb_class_1': 0.8297284370556541, 'weight_xgb_class_2': 0.882805986649729}. Best is trial 135 with value: 0.9496350853863924.
[I 2026-07-05 15:31:34,563] Trial 137 finished with value: 0.9478082560917778 and parameters: {'weight_lgbm_class_0': 0.12459930559448909, 'weight_lgbm_class_1': 0.6942798133167455, 'weight_lgbm_class_2': 0.7833949036425025, 'weight_xgb_class_0': 0.12268704187564743, 'weight_xgb_class_1': 0.8287397658163003, 'weight_xgb_class_2': 0.6092395304865479}. Best is trial 135 with value: 0.9496350853863924.

Best trial: 148. Best value: 0.949728:   7%|█████████▋                                                                                                                          | 147/2000 [00:03<00:41, 44.65it/s]

[I 2026-07-05 15:31:34,587] Trial 138 finished with value: 0.9479891027049646 and parameters: {'weight_lgbm_class_0': 0.1239978866516976, 'weight_lgbm_class_1': 0.8458837314661277, 'weight_lgbm_class_2': 0.7439357857891866, 'weight_xgb_class_0': 0.1196839098824176, 'weight_xgb_class_1': 0.8279445959611511, 'weight_xgb_class_2': 0.6054165379561406}. Best is trial 135 with value: 0.9496350853863924.
[I 2026-07-05 15:31:34,611] Trial 139 finished with value: 0.9496474886430707 and parameters: {'weight_lgbm_class_0': 0.12280293208490672, 'weight_lgbm_class_1': 0.8398419190191533, 'weight_lgbm_class_2': 0.7290058081993049, 'weight_xgb_class_0': 0.043002812560726425, 'weight_xgb_class_1': 0.8286770040119628, 'weight_xgb_class_2': 0.8812133906046966}. Best is trial 139 with value: 0.9496474886430707.
[I 2026-07-05 15:31:34,620] Trial 140 finished with value: 0.9277814122019371 and parameters: {'weight_lgbm_class_0': 0.6206939540340253, 'weight_lgbm_class_1': 0.6518526417378228, 'weight_lgbm_class_2': 0.7352461313395957, 'weight_xgb_class_0': 0.04745243264692926, 'weight_xgb_class_1': 0.8337571194273037, 'weight_xgb_class_2': 0.874786930262425}. Best is trial 139 with value: 0.9496474886430707.
[I 2026-07-05 15:31:34,657] Trial 141 finished with value: 0.9250667917760058 and parameters: {'weight_lgbm_class_0': 0.623567722509406, 'weight_lgbm_class_1': 0.6183190536565444, 'weight_lgbm_class_2': 0.7189825230186356, 'weight_xgb_class_0': 0.10652413562481144, 'weight_xgb_class_1': 0.978885543327506, 'weight_xgb_class_2': 0.8658173602082606}. Best is trial 139 with value: 0.9496474886430707.
[I 2026-07-05 15:31:34,678] Trial 143 finished with value: 0.9496230452976436 and parameters: {'weight_lgbm_class_0': 0.02608674041540513, 'weight_lgbm_class_1': 0.6467442468436811, 'weight_lgbm_class_2': 0.7644174401497409, 'weight_xgb_class_0': 0.09357468939572067, 'weight_xgb_class_1': 0.9781106839698248, 'weight_xgb_class_2': 0.8650792193648577}. Best is trial 139 with value: 0.9496474886430707.
[I 2026-07-05 15:31:34,695] Trial 142 finished with value: 0.94860543074331 and parameters: {'weight_lgbm_class_0': 0.024907759328042716, 'weight_lgbm_class_1': 0.8823894925636196, 'weight_lgbm_class_2': 0.7255854810662216, 'weight_xgb_class_0': 0.0466769526235986, 'weight_xgb_class_1': 0.9727262495521118, 'weight_xgb_class_2': 0.8605535418620803}. Best is trial 139 with value: 0.9496474886430707.
[I 2026-07-05 15:31:34,727] Trial 144 finished with value: 0.9496161964697819 and parameters: {'weight_lgbm_class_0': 0.03685984151066765, 'weight_lgbm_class_1': 0.5579029864379622, 'weight_lgbm_class_2': 0.8107120774257204, 'weight_xgb_class_0': 0.09951113092460356, 'weight_xgb_class_1': 0.9746761462356135, 'weight_xgb_class_2': 0.85950860994916}. Best is trial 139 with value: 0.9496474886430707.
[I 2026-07-05 15:31:34,747] Trial 146 finished with value: 0.9064415914293232 and parameters: {'weight_lgbm_class_0': 0.6187614222568315, 'weight_lgbm_class_1': 0.5502733258391254, 'weight_lgbm_class_2': 0.7343023940228269, 'weight_xgb_class_0': 0.04192287042171658, 'weight_xgb_class_1': 0.9711031384307938, 'weight_xgb_class_2': 0.018504986871886286}. Best is trial 139 with value: 0.9496474886430707.
[I 2026-07-05 15:31:34,757] Trial 145 finished with value: 0.9488444467876018 and parameters: {'weight_lgbm_class_0': 0.027793539984325197, 'weight_lgbm_class_1': 0.6449702204371983, 'weight_lgbm_class_2': 0.6602642425631087, 'weight_xgb_class_0': 0.08968649529146823, 'weight_xgb_class_1': 0.9635119185771194, 'weight_xgb_class_2': 0.08757905806329147}. Best is trial 139 with value: 0.9496474886430707.
[I 2026-07-05 15:31:34,815] Trial 148 finished with value: 0.9497284500344522 and parameters: {'weight_lgbm_class_0': 0.03883643847739968, 'weight_lgbm_class_1': 0.8879082381765171, 'weight_lgbm_class_2': 0.6492693614764566, 'weight_xgb_class_0': 0.08595865551764617, 'weight_xgb_class_1': 0.9724858449439359, 'weight_xgb_class_2': 0.8628107137500443}. Best is trial 148 with value: 0.9497284500344522.

Best trial: 148. Best value: 0.949728:   8%|██████████▎                                                                                                                         | 156/2000 [00:03<00:42, 43.25it/s]

[I 2026-07-05 15:31:34,824] Trial 147 finished with value: 0.9496140300710132 and parameters: {'weight_lgbm_class_0': 0.02902903638745065, 'weight_lgbm_class_1': 0.5579261786447096, 'weight_lgbm_class_2': 0.7661256560671412, 'weight_xgb_class_0': 0.09141038989617797, 'weight_xgb_class_1': 0.9698493552384013, 'weight_xgb_class_2': 0.8667353334714738}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:34,827] Trial 149 finished with value: 0.9496593868767492 and parameters: {'weight_lgbm_class_0': 0.028467538403799328, 'weight_lgbm_class_1': 0.8762975776199405, 'weight_lgbm_class_2': 0.6885867682984907, 'weight_xgb_class_0': 0.08859889793899975, 'weight_xgb_class_1': 0.9715372138933104, 'weight_xgb_class_2': 0.8699282043593225}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:34,843] Trial 150 finished with value: 0.9496867124840502 and parameters: {'weight_lgbm_class_0': 0.03235864261924486, 'weight_lgbm_class_1': 0.5648825029374033, 'weight_lgbm_class_2': 0.6817594707096984, 'weight_xgb_class_0': 0.09267423219711661, 'weight_xgb_class_1': 0.9727292964202415, 'weight_xgb_class_2': 0.8311451774139127}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:34,903] Trial 151 finished with value: 0.9496554453247139 and parameters: {'weight_lgbm_class_0': 0.030987586882401247, 'weight_lgbm_class_1': 0.6422939685598374, 'weight_lgbm_class_2': 0.6862292612514723, 'weight_xgb_class_0': 0.07783146259969961, 'weight_xgb_class_1': 0.9711137681567688, 'weight_xgb_class_2': 0.8344550608604427}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:34,940] Trial 154 finished with value: 0.9496263653325201 and parameters: {'weight_lgbm_class_0': 0.0356508918570415, 'weight_lgbm_class_1': 0.5103035715796067, 'weight_lgbm_class_2': 0.6784238476118464, 'weight_xgb_class_0': 0.08604284437300586, 'weight_xgb_class_1': 0.9399122422344475, 'weight_xgb_class_2': 0.8420292527754436}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:34,943] Trial 152 finished with value: 0.949634954895934 and parameters: {'weight_lgbm_class_0': 0.024553724510065288, 'weight_lgbm_class_1': 0.5290312022702872, 'weight_lgbm_class_2': 0.6559278990839877, 'weight_xgb_class_0': 0.08776045145976757, 'weight_xgb_class_1': 0.9678005466711495, 'weight_xgb_class_2': 0.8419590597996405}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:34,955] Trial 153 finished with value: 0.9496066676387632 and parameters: {'weight_lgbm_class_0': 0.03019329016451024, 'weight_lgbm_class_1': 0.5485461745880537, 'weight_lgbm_class_2': 0.8083706747916699, 'weight_xgb_class_0': 0.09077211131573974, 'weight_xgb_class_1': 0.9654651708105585, 'weight_xgb_class_2': 0.842365740172528}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:34,985] Trial 155 finished with value: 0.9496328788567178 and parameters: {'weight_lgbm_class_0': 0.038428313168265296, 'weight_lgbm_class_1': 0.5683395191211804, 'weight_lgbm_class_2': 0.6859400574480897, 'weight_xgb_class_0': 0.08666582387778662, 'weight_xgb_class_1': 0.9287269870398631, 'weight_xgb_class_2': 0.8328324523005151}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:35,005] Trial 156 finished with value: 0.9496332495317255 and parameters: {'weight_lgbm_class_0': 0.03161199147898494, 'weight_lgbm_class_1': 0.5708455301284603, 'weight_lgbm_class_2': 0.8126088680923412, 'weight_xgb_class_0': 0.08286620749902911, 'weight_xgb_class_1': 0.9370522708641001, 'weight_xgb_class_2': 0.8275684884487265}. Best is trial 148 with value: 0.9497284500344522.

Best trial: 148. Best value: 0.949728:   8%|██████████▉                                                                                                                         | 165/2000 [00:03<00:42, 42.80it/s]

[I 2026-07-05 15:31:35,038] Trial 157 finished with value: 0.9496377184146886 and parameters: {'weight_lgbm_class_0': 0.03435331033079343, 'weight_lgbm_class_1': 0.5182431325821403, 'weight_lgbm_class_2': 0.6602964396978349, 'weight_xgb_class_0': 0.08636192093588749, 'weight_xgb_class_1': 0.944012124902631, 'weight_xgb_class_2': 0.8313957365813979}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:35,054] Trial 159 finished with value: 0.9496208875367165 and parameters: {'weight_lgbm_class_0': 0.029816844617997284, 'weight_lgbm_class_1': 0.5182071289181963, 'weight_lgbm_class_2': 0.6552913197375817, 'weight_xgb_class_0': 0.08799209615023165, 'weight_xgb_class_1': 0.9463335287601946, 'weight_xgb_class_2': 0.8482285266098509}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:35,056] Trial 158 finished with value: 0.9496332161675757 and parameters: {'weight_lgbm_class_0': 0.03145339987505082, 'weight_lgbm_class_1': 0.5434253010246264, 'weight_lgbm_class_2': 0.6698010445591612, 'weight_xgb_class_0': 0.08353889480612997, 'weight_xgb_class_1': 0.9426638085678668, 'weight_xgb_class_2': 0.8431335829983381}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:35,104] Trial 160 finished with value: 0.9496824202286055 and parameters: {'weight_lgbm_class_0': 0.02879225977027395, 'weight_lgbm_class_1': 0.923421147659605, 'weight_lgbm_class_2': 0.6742715474447372, 'weight_xgb_class_0': 0.08455566038683547, 'weight_xgb_class_1': 0.9396609893052512, 'weight_xgb_class_2': 0.8304279885090478}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:35,125] Trial 161 finished with value: 0.9496144541382224 and parameters: {'weight_lgbm_class_0': 0.03675854971232337, 'weight_lgbm_class_1': 0.5257078501210842, 'weight_lgbm_class_2': 0.6734349942300609, 'weight_xgb_class_0': 0.08449366485992318, 'weight_xgb_class_1': 0.9428633955978867, 'weight_xgb_class_2': 0.8339639393616598}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:35,150] Trial 163 finished with value: 0.9496000805577386 and parameters: {'weight_lgbm_class_0': 0.04010830527210233, 'weight_lgbm_class_1': 0.5146350033429279, 'weight_lgbm_class_2': 0.6690313844451875, 'weight_xgb_class_0': 0.0901848631525174, 'weight_xgb_class_1': 0.9405263381455771, 'weight_xgb_class_2': 0.8283907324986084}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:35,178] Trial 162 finished with value: 0.9472181936568398 and parameters: {'weight_lgbm_class_0': 0.0383051071181332, 'weight_lgbm_class_1': 0.513096131165997, 'weight_lgbm_class_2': 0.679127639740611, 'weight_xgb_class_0': 0.0016219552205758714, 'weight_xgb_class_1': 0.93761789835341, 'weight_xgb_class_2': 0.8265229335467686}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:35,180] Trial 164 finished with value: 0.9496102632498129 and parameters: {'weight_lgbm_class_0': 0.039165238089357304, 'weight_lgbm_class_1': 0.5197859620055876, 'weight_lgbm_class_2': 0.6569255060096116, 'weight_xgb_class_0': 0.08829992421644269, 'weight_xgb_class_1': 0.9416152507533324, 'weight_xgb_class_2': 0.8461814188596164}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:35,220] Trial 165 finished with value: 0.9496359268491376 and parameters: {'weight_lgbm_class_0': 0.0374970327997061, 'weight_lgbm_class_1': 0.5151690429620139, 'weight_lgbm_class_2': 0.6678441053856267, 'weight_xgb_class_0': 0.08705818842230226, 'weight_xgb_class_1': 0.9426857110233425, 'weight_xgb_class_2': 0.8221736323817559}. Best is trial 148 with value: 0.9497284500344522.

Best trial: 148. Best value: 0.949728:   9%|███████████▌                                                                                                                        | 175/2000 [00:04<00:43, 41.96it/s]

[I 2026-07-05 15:31:35,251] Trial 166 finished with value: 0.949637581239525 and parameters: {'weight_lgbm_class_0': 0.03402849127652234, 'weight_lgbm_class_1': 0.5083458669334899, 'weight_lgbm_class_2': 0.6723871948736594, 'weight_xgb_class_0': 0.08714175962053503, 'weight_xgb_class_1': 0.9421148392197195, 'weight_xgb_class_2': 0.8283571110235748}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:35,270] Trial 167 finished with value: 0.9486706519066984 and parameters: {'weight_lgbm_class_0': 0.04245013366040378, 'weight_lgbm_class_1': 0.5138571734533202, 'weight_lgbm_class_2': 0.6717022121809143, 'weight_xgb_class_0': 0.02199734568572087, 'weight_xgb_class_1': 0.9399420042176763, 'weight_xgb_class_2': 0.8142188988274093}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:35,284] Trial 168 finished with value: 0.9486391363979291 and parameters: {'weight_lgbm_class_0': 0.042138055344194444, 'weight_lgbm_class_1': 0.5109969138162949, 'weight_lgbm_class_2': 0.5695732548884276, 'weight_xgb_class_0': 0.019242832365929788, 'weight_xgb_class_1': 0.9359098934395209, 'weight_xgb_class_2': 0.8269929912030803}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:35,316] Trial 169 finished with value: 0.9481024251213438 and parameters: {'weight_lgbm_class_0': 0.04928984799039292, 'weight_lgbm_class_1': 0.5206736600690509, 'weight_lgbm_class_2': 0.6724322606060608, 'weight_xgb_class_0': 0.0026158236847610705, 'weight_xgb_class_1': 0.9391978569134158, 'weight_xgb_class_2': 0.8226334584866754}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:35,340] Trial 170 finished with value: 0.9488110805624763 and parameters: {'weight_lgbm_class_0': 0.043366607378777844, 'weight_lgbm_class_1': 0.5725673196626901, 'weight_lgbm_class_2': 0.6312975506122136, 'weight_xgb_class_0': 0.02401027876936645, 'weight_xgb_class_1': 0.9325355405868694, 'weight_xgb_class_2': 0.8228193008134644}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:35,349] Trial 171 finished with value: 0.9495495963073313 and parameters: {'weight_lgbm_class_0': 0.03812093699073244, 'weight_lgbm_class_1': 0.49919821974738876, 'weight_lgbm_class_2': 0.6371850854856604, 'weight_xgb_class_0': 0.05552918553986378, 'weight_xgb_class_1': 0.9321215313766568, 'weight_xgb_class_2': 0.8208875475895718}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:35,410] Trial 172 finished with value: 0.949627278324153 and parameters: {'weight_lgbm_class_0': 0.041962929081747986, 'weight_lgbm_class_1': 0.4924788892103236, 'weight_lgbm_class_2': 0.5650244305362818, 'weight_xgb_class_0': 0.06003310547312528, 'weight_xgb_class_1': 0.9269664302247067, 'weight_xgb_class_2': 0.7902837484193738}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:35,421] Trial 173 finished with value: 0.9496341042890778 and parameters: {'weight_lgbm_class_0': 0.04927230152990661, 'weight_lgbm_class_1': 0.4791930132402501, 'weight_lgbm_class_2': 0.5717096510132968, 'weight_xgb_class_0': 0.05686673812004047, 'weight_xgb_class_1': 0.9230912465027459, 'weight_xgb_class_2': 0.8146342286461072}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:35,435] Trial 174 finished with value: 0.9350403912135938 and parameters: {'weight_lgbm_class_0': 0.4443466772508241, 'weight_lgbm_class_1': 0.43461029993244304, 'weight_lgbm_class_2': 0.6351778418218482, 'weight_xgb_class_0': 0.058934852866345644, 'weight_xgb_class_1': 0.9238395861176996, 'weight_xgb_class_2': 0.8212793339678681}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:35,461] Trial 175 finished with value: 0.9490778458092518 and parameters: {'weight_lgbm_class_0': 0.04991025781481461, 'weight_lgbm_class_1': 0.4321568859999472, 'weight_lgbm_class_2': 0.6278099718852449, 'weight_xgb_class_0': 0.024404272519217958, 'weight_xgb_class_1': 0.9217425292952, 'weight_xgb_class_2': 0.8161304072670816}. Best is trial 148 with value: 0.9497284500344522.

[I 2026-07-05 15:31:35,485] Trial 176 finished with value: 0.9496316960277017 and parameters: {'weight_lgbm_class_0': 0.051555068009305004, 'weight_lgbm_class_1': 0.4525948459947896, 'weight_lgbm_class_2': 0.6380351267206577, 'weight_xgb_class_0': 0.054946513095223394, 'weight_xgb_class_1': 0.9239013179099975, 'weight_xgb_class_2': 0.7856495264307418}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:35,512] Trial 177 finished with value: 0.9493129713172861 and parameters: {'weight_lgbm_class_0': 0.021763350418318575, 'weight_lgbm_class_1': 0.4709656724173297, 'weight_lgbm_class_2': 0.629815464814742, 'weight_xgb_class_0': 0.057839111953940606, 'weight_xgb_class_1': 0.9217230536843636, 'weight_xgb_class_2': 0.7863288361401084}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:35,545] Trial 179 finished with value: 0.9492443547890529 and parameters: {'weight_lgbm_class_0': 0.01907587414067401, 'weight_lgbm_class_1': 0.44382789420621566, 'weight_lgbm_class_2': 0.6981973998499394, 'weight_xgb_class_0': 0.061803637690578755, 'weight_xgb_class_1': 0.9613255367331125, 'weight_xgb_class_2': 0.7763851265710893}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:35,549] Trial 178 finished with value: 0.9492926915587256 and parameters: {'weight_lgbm_class_0': 0.02007993726242762, 'weight_lgbm_class_1': 0.48057571132039506, 'weight_lgbm_class_2': 0.634940429229521, 'weight_xgb_class_0': 0.059055834408334076, 'weight_xgb_class_1': 0.9200411102455058, 'weight_xgb_class_2': 0.7872684692004644}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:35,585] Trial 180 finished with value: 0.9495362413928654 and parameters: {'weight_lgbm_class_0': 0.021791517423205797, 'weight_lgbm_class_1': 0.47668078349806475, 'weight_lgbm_class_2': 0.6094434544110702, 'weight_xgb_class_0': 0.06587056242465394, 'weight_xgb_class_1': 0.9612102493455731, 'weight_xgb_class_2': 0.7805866106998692}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:35,605] Trial 181 finished with value: 0.9493768420369949 and parameters: {'weight_lgbm_class_0': 0.021135013427148224, 'weight_lgbm_class_1': 0.4785384654213498, 'weight_lgbm_class_2': 0.6989154051605567, 'weight_xgb_class_0': 0.06581072351665723, 'weight_xgb_class_1': 0.9597376636800945, 'weight_xgb_class_2': 0.7944877665724309}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:35,659] Trial 183 finished with value: 0.9496051429087471 and parameters: {'weight_lgbm_class_0': 0.02176579559328344, 'weight_lgbm_class_1': 0.4540635792344326, 'weight_lgbm_class_2': 0.5174994970212221, 'weight_xgb_class_0': 0.06611288683563517, 'weight_xgb_class_1': 0.959702686130428, 'weight_xgb_class_2': 0.7961038642439426}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:35,680] Trial 184 finished with value: 0.9493903080639594 and parameters: {'weight_lgbm_class_0': 0.020474353993398538, 'weight_lgbm_class_1': 0.47492154110765755, 'weight_lgbm_class_2': 0.6986346507908396, 'weight_xgb_class_0': 0.06672564177296528, 'weight_xgb_class_1': 0.9574458073791955, 'weight_xgb_class_2': 0.785782741106981}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:35,683] Trial 185 finished with value: 0.9493543408373998 and parameters: {'weight_lgbm_class_0': 0.02144628956866041, 'weight_lgbm_class_1': 0.47308727121284017, 'weight_lgbm_class_2': 0.6958062697568292, 'weight_xgb_class_0': 0.06445820526468377, 'weight_xgb_class_1': 0.9626974418582497, 'weight_xgb_class_2': 0.7824472759591283}. Best is trial 148 with value: 0.9497284500344522.

Best trial: 148. Best value: 0.949728:  10%|████████████▋                                                                                                                       | 193/2000 [00:04<00:42, 42.76it/s]

[I 2026-07-05 15:31:35,690] Trial 182 finished with value: 0.9493538321648552 and parameters: {'weight_lgbm_class_0': 0.019708952743087135, 'weight_lgbm_class_1': 0.47291421359375035, 'weight_lgbm_class_2': 0.6102373643321005, 'weight_xgb_class_0': 0.06085682800187936, 'weight_xgb_class_1': 0.9641170709096586, 'weight_xgb_class_2': 0.7716911225155565}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:35,708] Trial 186 finished with value: 0.949603038342142 and parameters: {'weight_lgbm_class_0': 0.07484496431932672, 'weight_lgbm_class_1': 0.403057704798117, 'weight_lgbm_class_2': 0.581818516541513, 'weight_xgb_class_0': 0.06353559490492645, 'weight_xgb_class_1': 0.9594379699938146, 'weight_xgb_class_2': 0.7677261437649647}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:35,742] Trial 187 finished with value: 0.9496226604308524 and parameters: {'weight_lgbm_class_0': 0.07848318810125829, 'weight_lgbm_class_1': 0.48340214900261225, 'weight_lgbm_class_2': 0.6106408044849673, 'weight_xgb_class_0': 0.07055073326866668, 'weight_xgb_class_1': 0.9554280868682212, 'weight_xgb_class_2': 0.7622469601426308}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:35,760] Trial 188 finished with value: 0.9496111914071381 and parameters: {'weight_lgbm_class_0': 0.05970186158078765, 'weight_lgbm_class_1': 0.40216813940594365, 'weight_lgbm_class_2': 0.5556949717943411, 'weight_xgb_class_0': 0.07302881718567919, 'weight_xgb_class_1': 0.8851863737260882, 'weight_xgb_class_2': 0.7623774748991763}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:35,788] Trial 189 finished with value: 0.9496273910403724 and parameters: {'weight_lgbm_class_0': 0.07552101644477191, 'weight_lgbm_class_1': 0.38993489980632057, 'weight_lgbm_class_2': 0.5309840391513988, 'weight_xgb_class_0': 0.03797800291958961, 'weight_xgb_class_1': 0.8932592768527025, 'weight_xgb_class_2': 0.770117983921473}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:35,812] Trial 190 finished with value: 0.9496502798383816 and parameters: {'weight_lgbm_class_0': 0.058185565162935875, 'weight_lgbm_class_1': 0.9386783080178015, 'weight_lgbm_class_2': 0.5149897506266152, 'weight_xgb_class_0': 0.040217519232374134, 'weight_xgb_class_1': 0.8902310986345879, 'weight_xgb_class_2': 0.7562203469676322}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:35,829] Trial 191 finished with value: 0.9496821829687061 and parameters: {'weight_lgbm_class_0': 0.07455191611052588, 'weight_lgbm_class_1': 0.9278878779002989, 'weight_lgbm_class_2': 0.5293779814489601, 'weight_xgb_class_0': 0.07800452701155532, 'weight_xgb_class_1': 0.8886994185540019, 'weight_xgb_class_2': 0.8478085368048065}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:35,852] Trial 192 finished with value: 0.9496937188235167 and parameters: {'weight_lgbm_class_0': 0.07440273944042511, 'weight_lgbm_class_1': 0.9216102268168148, 'weight_lgbm_class_2': 0.5852237670096669, 'weight_xgb_class_0': 0.07814823377804206, 'weight_xgb_class_1': 0.902805116308903, 'weight_xgb_class_2': 0.8498713412973813}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:35,904] Trial 194 finished with value: 0.9496075807665045 and parameters: {'weight_lgbm_class_0': 0.06550962915645742, 'weight_lgbm_class_1': 0.9319964593183924, 'weight_lgbm_class_2': 0.5814686949511043, 'weight_xgb_class_0': 0.033634862190234656, 'weight_xgb_class_1': 0.8914609432854365, 'weight_xgb_class_2': 0.843964338905871}. Best is trial 148 with value: 0.9497284500344522.

Best trial: 148. Best value: 0.949728:  10%|█████████████▎                                                                                                                      | 201/2000 [00:04<00:42, 42.12it/s]

[I 2026-07-05 15:31:35,915] Trial 195 finished with value: 0.9495229928028763 and parameters: {'weight_lgbm_class_0': 0.0533937625099273, 'weight_lgbm_class_1': 0.9459140776501422, 'weight_lgbm_class_2': 0.516710432689369, 'weight_xgb_class_0': 0.03808279538297884, 'weight_xgb_class_1': 0.8888666959245856, 'weight_xgb_class_2': 0.8504567386798829}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:35,928] Trial 193 finished with value: 0.949606423629992 and parameters: {'weight_lgbm_class_0': 0.057027268095438836, 'weight_lgbm_class_1': 0.9405316993764533, 'weight_lgbm_class_2': 0.5665907979044135, 'weight_xgb_class_0': 0.03537759917944471, 'weight_xgb_class_1': 0.8821128762121543, 'weight_xgb_class_2': 0.7581229717729845}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:35,949] Trial 196 finished with value: 0.9494340286237078 and parameters: {'weight_lgbm_class_0': 0.05117285807959132, 'weight_lgbm_class_1': 0.9268335741103527, 'weight_lgbm_class_2': 0.5401330512659964, 'weight_xgb_class_0': 0.03639038484660778, 'weight_xgb_class_1': 0.8820932990213203, 'weight_xgb_class_2': 0.8460044102812191}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:35,980] Trial 197 finished with value: 0.9495119156670421 and parameters: {'weight_lgbm_class_0': 0.0561806007527296, 'weight_lgbm_class_1': 0.928900721695001, 'weight_lgbm_class_2': 0.5378854518432793, 'weight_xgb_class_0': 0.03513877077483549, 'weight_xgb_class_1': 0.9165126106281313, 'weight_xgb_class_2': 0.8662424270897767}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:35,988] Trial 198 finished with value: 0.9159478532581059 and parameters: {'weight_lgbm_class_0': 0.798152555800252, 'weight_lgbm_class_1': 0.9094734119077246, 'weight_lgbm_class_2': 0.5879762291707799, 'weight_xgb_class_0': 0.033734631421335586, 'weight_xgb_class_1': 0.8967119832269173, 'weight_xgb_class_2': 0.7347751701379582}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:36,049] Trial 200 finished with value: 0.9495335872260343 and parameters: {'weight_lgbm_class_0': 0.056079200652451894, 'weight_lgbm_class_1': 0.927233565226993, 'weight_lgbm_class_2': 0.5142201979758232, 'weight_xgb_class_0': 0.033868527032664006, 'weight_xgb_class_1': 0.9039463535991772, 'weight_xgb_class_2': 0.8026064391679906}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:36,069] Trial 199 finished with value: 0.9491396890784966 and parameters: {'weight_lgbm_class_0': 0.05171135475258227, 'weight_lgbm_class_1': 0.9431130900605964, 'weight_lgbm_class_2': 0.5137291814713707, 'weight_xgb_class_0': 0.022822562671084137, 'weight_xgb_class_1': 0.905587626279544, 'weight_xgb_class_2': 0.7353844723458567}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:36,081] Trial 201 finished with value: 0.9496263895574112 and parameters: {'weight_lgbm_class_0': 0.06012378057332089, 'weight_lgbm_class_1': 0.9314424085372359, 'weight_lgbm_class_2': 0.5252877988247201, 'weight_xgb_class_0': 0.03529658479604056, 'weight_xgb_class_1': 0.902451965763772, 'weight_xgb_class_2': 0.737588430671495}. Best is trial 148 with value: 0.9497284500344522.

Best trial: 148. Best value: 0.949728:  11%|█████████████▉                                                                                                                      | 211/2000 [00:04<00:41, 43.19it/s]

[I 2026-07-05 15:31:36,109] Trial 202 finished with value: 0.9496863677404512 and parameters: {'weight_lgbm_class_0': 0.10829211990975035, 'weight_lgbm_class_1': 0.9372386055313604, 'weight_lgbm_class_2': 0.5139129170643063, 'weight_xgb_class_0': 0.03500141342289576, 'weight_xgb_class_1': 0.8946989511279299, 'weight_xgb_class_2': 0.8486206733930638}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:36,132] Trial 203 finished with value: 0.9495864894089442 and parameters: {'weight_lgbm_class_0': 0.05868804115091324, 'weight_lgbm_class_1': 0.9432859896344546, 'weight_lgbm_class_2': 0.5261482714318245, 'weight_xgb_class_0': 0.03709781168154436, 'weight_xgb_class_1': 0.9015948830915635, 'weight_xgb_class_2': 0.8436273877776069}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:36,181] Trial 204 finished with value: 0.949604155188033 and parameters: {'weight_lgbm_class_0': 0.10768446038401344, 'weight_lgbm_class_1': 0.9080620645051397, 'weight_lgbm_class_2': 0.4598674686426809, 'weight_xgb_class_0': 0.03692912619233829, 'weight_xgb_class_1': 0.9012439158469543, 'weight_xgb_class_2': 0.7443032687475146}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:36,191] Trial 206 finished with value: 0.9484286023870521 and parameters: {'weight_lgbm_class_0': 0.10835804531658826, 'weight_lgbm_class_1': 0.35672458813451385, 'weight_lgbm_class_2': 0.7089908808238756, 'weight_xgb_class_0': 0.0992617958477359, 'weight_xgb_class_1': 0.9105841133272778, 'weight_xgb_class_2': 0.8075584046357857}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:36,208] Trial 205 finished with value: 0.9487982624797128 and parameters: {'weight_lgbm_class_0': 0.1018175947461403, 'weight_lgbm_class_1': 0.8881410627973987, 'weight_lgbm_class_2': 0.4850636104619227, 'weight_xgb_class_0': 0.1038661011243521, 'weight_xgb_class_1': 0.8974398745543279, 'weight_xgb_class_2': 0.8073098158342704}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:36,214] Trial 207 finished with value: 0.9494589983618611 and parameters: {'weight_lgbm_class_0': 0.08418162870072182, 'weight_lgbm_class_1': 0.8861528973126074, 'weight_lgbm_class_2': 0.6562941488123116, 'weight_xgb_class_0': 0.09716709523398909, 'weight_xgb_class_1': 0.910311440233656, 'weight_xgb_class_2': 0.8066092430529633}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:36,249] Trial 208 finished with value: 0.948640270082253 and parameters: {'weight_lgbm_class_0': 0.10667520883812438, 'weight_lgbm_class_1': 0.8850371553223448, 'weight_lgbm_class_2': 0.46973254105488754, 'weight_xgb_class_0': 0.10311019760164368, 'weight_xgb_class_1': 0.9036935874500088, 'weight_xgb_class_2': 0.8055427733572296}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:36,263] Trial 209 finished with value: 0.948837238279649 and parameters: {'weight_lgbm_class_0': 0.1071821002749303, 'weight_lgbm_class_1': 0.95908239797861, 'weight_lgbm_class_2': 0.48631821574036305, 'weight_xgb_class_0': 0.1016938791748318, 'weight_xgb_class_1': 0.9084687576087034, 'weight_xgb_class_2': 0.8678763367204357}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:36,302] Trial 211 finished with value: 0.9491058824781385 and parameters: {'weight_lgbm_class_0': 0.10456080752054352, 'weight_lgbm_class_1': 0.9602802072874538, 'weight_lgbm_class_2': 0.6519536172602116, 'weight_xgb_class_0': 0.10599201858690374, 'weight_xgb_class_1': 0.8719278360461197, 'weight_xgb_class_2': 0.8790818782103226}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:36,348] Trial 212 finished with value: 0.9479571284313412 and parameters: {'weight_lgbm_class_0': 0.10713437895691624, 'weight_lgbm_class_1': 0.36431247876585005, 'weight_lgbm_class_2': 0.47346631160128944, 'weight_xgb_class_0': 0.10133514692907886, 'weight_xgb_class_1': 0.8690417348725872, 'weight_xgb_class_2': 0.804021677867911}. Best is trial 148 with value: 0.9497284500344522.

Best trial: 148. Best value: 0.949728:  11%|██████████████▍                                                                                                                     | 219/2000 [00:05<00:41, 42.61it/s]

[I 2026-07-05 15:31:36,351] Trial 210 finished with value: 0.9480101923178431 and parameters: {'weight_lgbm_class_0': 0.10657817809721798, 'weight_lgbm_class_1': 0.3578114317358613, 'weight_lgbm_class_2': 0.49428294241946696, 'weight_xgb_class_0': 0.10443051964303388, 'weight_xgb_class_1': 0.8702168004990444, 'weight_xgb_class_2': 0.8726067138157869}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:36,370] Trial 213 finished with value: 0.9491015490097641 and parameters: {'weight_lgbm_class_0': 0.08118054813645142, 'weight_lgbm_class_1': 0.8885866064111239, 'weight_lgbm_class_2': 0.47864369568421195, 'weight_xgb_class_0': 0.10639903185919997, 'weight_xgb_class_1': 0.873348348452642, 'weight_xgb_class_2': 0.8768336997390362}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:36,413] Trial 214 finished with value: 0.9480239319596646 and parameters: {'weight_lgbm_class_0': 0.14165596246929035, 'weight_lgbm_class_1': 0.8789416097147249, 'weight_lgbm_class_2': 0.4609852163795619, 'weight_xgb_class_0': 0.10327042826778836, 'weight_xgb_class_1': 0.9224627991307883, 'weight_xgb_class_2': 0.8719336118900141}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:36,441] Trial 216 finished with value: 0.9483414212635219 and parameters: {'weight_lgbm_class_0': 0.14638645536866274, 'weight_lgbm_class_1': 0.9608249395913759, 'weight_lgbm_class_2': 0.4859399111663657, 'weight_xgb_class_0': 0.08364986961708594, 'weight_xgb_class_1': 0.8728956290335932, 'weight_xgb_class_2': 0.8607814094177679}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:36,457] Trial 215 finished with value: 0.94796781534964 and parameters: {'weight_lgbm_class_0': 0.14628602704813515, 'weight_lgbm_class_1': 0.5648758940061591, 'weight_lgbm_class_2': 0.47093395745177574, 'weight_xgb_class_0': 0.08409998459760565, 'weight_xgb_class_1': 0.8731399710429657, 'weight_xgb_class_2': 0.8735655206938745}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:36,509] Trial 217 finished with value: 0.949556278152737 and parameters: {'weight_lgbm_class_0': 0.07649835398308023, 'weight_lgbm_class_1': 0.5451709422170495, 'weight_lgbm_class_2': 0.6449140429601665, 'weight_xgb_class_0': 0.0832335446335707, 'weight_xgb_class_1': 0.873442820220601, 'weight_xgb_class_2': 0.8768296956069984}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:36,528] Trial 219 finished with value: 0.9495926132734765 and parameters: {'weight_lgbm_class_0': 0.07966900769958021, 'weight_lgbm_class_1': 0.5753185871857561, 'weight_lgbm_class_2': 0.6830096687927417, 'weight_xgb_class_0': 0.08060121150500794, 'weight_xgb_class_1': 0.8694790398261206, 'weight_xgb_class_2': 0.8783766095856924}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:36,545] Trial 218 finished with value: 0.9497044465797321 and parameters: {'weight_lgbm_class_0': 0.07922497190765151, 'weight_lgbm_class_1': 0.9080954260949712, 'weight_lgbm_class_2': 0.6877586723087828, 'weight_xgb_class_0': 0.08076674576633608, 'weight_xgb_class_1': 0.8688101549058107, 'weight_xgb_class_2': 0.8771745901770869}. Best is trial 148 with value: 0.9497284500344522.

Best trial: 148. Best value: 0.949728:  11%|███████████████                                                                                                                     | 229/2000 [00:05<00:41, 42.72it/s]

[I 2026-07-05 15:31:36,576] Trial 220 finished with value: 0.9481735907197071 and parameters: {'weight_lgbm_class_0': 0.14149559294849937, 'weight_lgbm_class_1': 0.5698117271201033, 'weight_lgbm_class_2': 0.5535663881603413, 'weight_xgb_class_0': 0.0888342719171077, 'weight_xgb_class_1': 0.9279159981926647, 'weight_xgb_class_2': 0.8369927548991405}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:36,597] Trial 221 finished with value: 0.9495954120940899 and parameters: {'weight_lgbm_class_0': 0.07860947033018906, 'weight_lgbm_class_1': 0.538771720736841, 'weight_lgbm_class_2': 0.6874576002699726, 'weight_xgb_class_0': 0.07830194236933771, 'weight_xgb_class_1': 0.9282717184507902, 'weight_xgb_class_2': 0.8306275854068284}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:36,608] Trial 222 finished with value: 0.949620615686821 and parameters: {'weight_lgbm_class_0': 0.082319904080892, 'weight_lgbm_class_1': 0.5302043639867173, 'weight_lgbm_class_2': 0.5498018149172934, 'weight_xgb_class_0': 0.080639408649953, 'weight_xgb_class_1': 0.9280142205143308, 'weight_xgb_class_2': 0.837695318339699}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:36,620] Trial 223 finished with value: 0.949582111921214 and parameters: {'weight_lgbm_class_0': 0.07692952818831465, 'weight_lgbm_class_1': 0.5470678065763454, 'weight_lgbm_class_2': 0.683051618315374, 'weight_xgb_class_0': 0.07977229947357256, 'weight_xgb_class_1': 0.9287485864314324, 'weight_xgb_class_2': 0.8334521578953064}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:36,658] Trial 224 finished with value: 0.9495139433564113 and parameters: {'weight_lgbm_class_0': 0.07973486038593003, 'weight_lgbm_class_1': 0.5361932204873202, 'weight_lgbm_class_2': 0.5521557538815252, 'weight_xgb_class_0': 0.006499445767919672, 'weight_xgb_class_1': 0.9796234803277619, 'weight_xgb_class_2': 0.825103147764208}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:36,699] Trial 225 finished with value: 0.9496318401211571 and parameters: {'weight_lgbm_class_0': 0.07899581245507574, 'weight_lgbm_class_1': 0.5653031173223073, 'weight_lgbm_class_2': 0.5488886108342493, 'weight_xgb_class_0': 0.07938745498606636, 'weight_xgb_class_1': 0.9845095477817778, 'weight_xgb_class_2': 0.8320449839845392}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:36,705] Trial 227 finished with value: 0.9492038248683127 and parameters: {'weight_lgbm_class_0': 0.0744205034739346, 'weight_lgbm_class_1': 0.4956480221983297, 'weight_lgbm_class_2': 0.550904099214352, 'weight_xgb_class_0': 0.0010774045656801803, 'weight_xgb_class_1': 0.9863108341819982, 'weight_xgb_class_2': 0.8308296997104553}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:36,705] Trial 226 finished with value: 0.9492706939352633 and parameters: {'weight_lgbm_class_0': 0.07925161166526129, 'weight_lgbm_class_1': 0.5450025871075761, 'weight_lgbm_class_2': 0.6869420230163784, 'weight_xgb_class_0': 0.00541688898214121, 'weight_xgb_class_1': 0.983170861587041, 'weight_xgb_class_2': 0.8340702634946583}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:36,743] Trial 228 finished with value: 0.9496379355099623 and parameters: {'weight_lgbm_class_0': 0.07385338725349325, 'weight_lgbm_class_1': 0.5333965382917779, 'weight_lgbm_class_2': 0.686769235784849, 'weight_xgb_class_0': 0.050099296032292545, 'weight_xgb_class_1': 0.9811741814341951, 'weight_xgb_class_2': 0.8331630848447545}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:36,768] Trial 229 finished with value: 0.912044182692962 and parameters: {'weight_lgbm_class_0': 0.07625053310149855, 'weight_lgbm_class_1': 0.5419711923237219, 'weight_lgbm_class_2': 0.6891485185827272, 'weight_xgb_class_0': 0.8331494263673995, 'weight_xgb_class_1': 0.9871983673528884, 'weight_xgb_class_2': 0.8285665754231868}. Best is trial 148 with value: 0.9497284500344522.

Best trial: 148. Best value: 0.949728:  12%|███████████████▋                                                                                                                    | 238/2000 [00:05<00:41, 41.97it/s]

[I 2026-07-05 15:31:36,800] Trial 230 finished with value: 0.9496253082677119 and parameters: {'weight_lgbm_class_0': 0.07596710411861318, 'weight_lgbm_class_1': 0.4978263063393597, 'weight_lgbm_class_2': 0.6856038074428702, 'weight_xgb_class_0': 0.05155959667482464, 'weight_xgb_class_1': 0.9838132295790856, 'weight_xgb_class_2': 0.8321611031248172}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:36,844] Trial 231 finished with value: 0.9495177796042223 and parameters: {'weight_lgbm_class_0': 0.05313912434783155, 'weight_lgbm_class_1': 0.9123199460325719, 'weight_lgbm_class_2': 0.6581286533989934, 'weight_xgb_class_0': 0.04668392450992986, 'weight_xgb_class_1': 0.9846071225719939, 'weight_xgb_class_2': 0.9071360617077798}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:36,855] Trial 232 finished with value: 0.9494877630301688 and parameters: {'weight_lgbm_class_0': 0.04547294427211612, 'weight_lgbm_class_1': 0.5005993122975859, 'weight_lgbm_class_2': 0.7145317368516496, 'weight_xgb_class_0': 0.04826136994320722, 'weight_xgb_class_1': 0.9788200160003976, 'weight_xgb_class_2': 0.8184696240378446}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:36,888] Trial 234 finished with value: 0.9187686206627195 and parameters: {'weight_lgbm_class_0': 0.04317747235547034, 'weight_lgbm_class_1': 0.90943923746003, 'weight_lgbm_class_2': 0.6567955424284424, 'weight_xgb_class_0': 0.825519124368371, 'weight_xgb_class_1': 0.9497731986781157, 'weight_xgb_class_2': 0.8521159492226414}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:36,907] Trial 233 finished with value: 0.9463890471501255 and parameters: {'weight_lgbm_class_0': 0.03818210628185958, 'weight_lgbm_class_1': 0.9085215503959267, 'weight_lgbm_class_2': 0.7128880942037971, 'weight_xgb_class_0': 0.0019740544691404516, 'weight_xgb_class_1': 0.9780421738780912, 'weight_xgb_class_2': 0.8196033851157231}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:36,918] Trial 235 finished with value: 0.9493493433769173 and parameters: {'weight_lgbm_class_0': 0.044421450594714716, 'weight_lgbm_class_1': 0.9037857505572175, 'weight_lgbm_class_2': 0.657554230509765, 'weight_xgb_class_0': 0.05018516542351237, 'weight_xgb_class_1': 0.9780581942831227, 'weight_xgb_class_2': 0.9128792606782045}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:36,939] Trial 236 finished with value: 0.9223417412086046 and parameters: {'weight_lgbm_class_0': 0.0017400331716700482, 'weight_lgbm_class_1': 0.6028978825686554, 'weight_lgbm_class_2': 0.655539146907927, 'weight_xgb_class_0': 0.7703602029195413, 'weight_xgb_class_1': 0.9545736105604421, 'weight_xgb_class_2': 0.9097604857038498}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:36,975] Trial 237 finished with value: 0.9495551705021531 and parameters: {'weight_lgbm_class_0': 0.05047148070912455, 'weight_lgbm_class_1': 0.9042637460479606, 'weight_lgbm_class_2': 0.6616844529806305, 'weight_xgb_class_0': 0.050351216112132134, 'weight_xgb_class_1': 0.9993721514758436, 'weight_xgb_class_2': 0.9012734976072396}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:37,015] Trial 239 finished with value: 0.9494434454865429 and parameters: {'weight_lgbm_class_0': 0.04557235319606751, 'weight_lgbm_class_1': 0.5746030402768791, 'weight_lgbm_class_2': 0.7168026068826795, 'weight_xgb_class_0': 0.05257552022821867, 'weight_xgb_class_1': 0.9505346557036608, 'weight_xgb_class_2': 0.9188444632759583}. Best is trial 148 with value: 0.9497284500344522.

[I 2026-07-05 15:31:37,017] Trial 238 finished with value: 0.9495339905943548 and parameters: {'weight_lgbm_class_0': 0.04661400656325196, 'weight_lgbm_class_1': 0.8596149195632257, 'weight_lgbm_class_2': 0.6602421040794118, 'weight_xgb_class_0': 0.05143858320374922, 'weight_xgb_class_1': 0.9450630366373645, 'weight_xgb_class_2': 0.8503858807433365}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:37,045] Trial 240 finished with value: 0.9494335328630433 and parameters: {'weight_lgbm_class_0': 0.04630774656573933, 'weight_lgbm_class_1': 0.9081975905655975, 'weight_lgbm_class_2': 0.7178303345942155, 'weight_xgb_class_0': 0.050579049423623346, 'weight_xgb_class_1': 0.9522313726761877, 'weight_xgb_class_2': 0.8485888950336183}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:37,061] Trial 241 finished with value: 0.949408863059606 and parameters: {'weight_lgbm_class_0': 0.04592146058939332, 'weight_lgbm_class_1': 0.8661137007566664, 'weight_lgbm_class_2': 0.7143390439421129, 'weight_xgb_class_0': 0.04941595804447538, 'weight_xgb_class_1': 0.9488213422848123, 'weight_xgb_class_2': 0.8583590737735022}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:37,106] Trial 243 finished with value: 0.9492355523759444 and parameters: {'weight_lgbm_class_0': 0.033811832732166355, 'weight_lgbm_class_1': 0.8646263437261783, 'weight_lgbm_class_2': 0.7107731558950162, 'weight_xgb_class_0': 0.053668389705178614, 'weight_xgb_class_1': 0.9485329074715866, 'weight_xgb_class_2': 0.8547377206368969}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:37,109] Trial 242 finished with value: 0.9496494742817091 and parameters: {'weight_lgbm_class_0': 0.0422693605679424, 'weight_lgbm_class_1': 0.5999771461483635, 'weight_lgbm_class_2': 0.5964520085463486, 'weight_xgb_class_0': 0.05583908467655532, 'weight_xgb_class_1': 0.9503639524280707, 'weight_xgb_class_2': 0.8550593674932095}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:37,135] Trial 244 finished with value: 0.9492780980944264 and parameters: {'weight_lgbm_class_0': 0.012712264162596215, 'weight_lgbm_class_1': 0.5774072553548616, 'weight_lgbm_class_2': 0.43338055290933825, 'weight_xgb_class_0': 0.061705819976533655, 'weight_xgb_class_1': 0.9467550901423578, 'weight_xgb_class_2': 0.848692130979159}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:37,163] Trial 245 finished with value: 0.9496586294720443 and parameters: {'weight_lgbm_class_0': 0.01880291539170885, 'weight_lgbm_class_1': 0.31566198263061596, 'weight_lgbm_class_2': 0.4328920885475134, 'weight_xgb_class_0': 0.07422436179555492, 'weight_xgb_class_1': 0.948235056973454, 'weight_xgb_class_2': 0.8538755132225688}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:37,205] Trial 246 finished with value: 0.9494933432055466 and parameters: {'weight_lgbm_class_0': 0.020315772746240204, 'weight_lgbm_class_1': 0.45465202699539736, 'weight_lgbm_class_2': 0.5959773618309792, 'weight_xgb_class_0': 0.06978931122971371, 'weight_xgb_class_1': 0.9479356629281314, 'weight_xgb_class_2': 0.8542812906308506}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:37,217] Trial 248 finished with value: 0.9493355958627089 and parameters: {'weight_lgbm_class_0': 0.019677043072161723, 'weight_lgbm_class_1': 0.5806789532222283, 'weight_lgbm_class_2': 0.6114880517290894, 'weight_xgb_class_0': 0.06418966421838157, 'weight_xgb_class_1': 0.9468770795962805, 'weight_xgb_class_2': 0.8551688869171421}. Best is trial 148 with value: 0.9497284500344522.

Best trial: 148. Best value: 0.949728:  13%|████████████████▉                                                                                                                   | 256/2000 [00:06<00:40, 42.56it/s]

[I 2026-07-05 15:31:37,243] Trial 247 finished with value: 0.9492893409815523 and parameters: {'weight_lgbm_class_0': 0.019216460123369007, 'weight_lgbm_class_1': 0.8611334910597966, 'weight_lgbm_class_2': 0.6142082472189012, 'weight_xgb_class_0': 0.06740628597723305, 'weight_xgb_class_1': 0.9473305302475158, 'weight_xgb_class_2': 0.8612492675162389}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:37,264] Trial 250 finished with value: 0.9495884725495468 and parameters: {'weight_lgbm_class_0': 0.017207663308402215, 'weight_lgbm_class_1': 0.4570686211650963, 'weight_lgbm_class_2': 0.6010704826294359, 'weight_xgb_class_0': 0.07376157154873983, 'weight_xgb_class_1': 0.9415262674628456, 'weight_xgb_class_2': 0.7985938599170407}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:37,268] Trial 249 finished with value: 0.9492893062887596 and parameters: {'weight_lgbm_class_0': 0.015243884392949415, 'weight_lgbm_class_1': 0.8681374863624461, 'weight_lgbm_class_2': 0.6190981529619825, 'weight_xgb_class_0': 0.07215930581213535, 'weight_xgb_class_1': 0.9521742321621298, 'weight_xgb_class_2': 0.8609413440241097}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:37,289] Trial 251 finished with value: 0.9496740196572949 and parameters: {'weight_lgbm_class_0': 0.0215250670365661, 'weight_lgbm_class_1': 0.3106453430215833, 'weight_lgbm_class_2': 0.42088642954800604, 'weight_xgb_class_0': 0.07256459039320616, 'weight_xgb_class_1': 0.9221674112770522, 'weight_xgb_class_2': 0.7874391832421501}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:37,339] Trial 253 finished with value: 0.9495607315128781 and parameters: {'weight_lgbm_class_0': 0.016111703511762658, 'weight_lgbm_class_1': 0.5852933557232818, 'weight_lgbm_class_2': 0.6038354297560101, 'weight_xgb_class_0': 0.07476549426949972, 'weight_xgb_class_1': 0.9676950400587923, 'weight_xgb_class_2': 0.8090158083844025}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:37,359] Trial 252 finished with value: 0.949446418894169 and parameters: {'weight_lgbm_class_0': 0.01959404974363238, 'weight_lgbm_class_1': 0.5951629806461137, 'weight_lgbm_class_2': 0.6020206144313981, 'weight_xgb_class_0': 0.07090065895280344, 'weight_xgb_class_1': 0.9671059687729995, 'weight_xgb_class_2': 0.8556122197586641}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:37,369] Trial 254 finished with value: 0.9495890376957966 and parameters: {'weight_lgbm_class_0': 0.018991593411819843, 'weight_lgbm_class_1': 0.5915940632457353, 'weight_lgbm_class_2': 0.6213910382198277, 'weight_xgb_class_0': 0.07324541717705996, 'weight_xgb_class_1': 0.9222242505300027, 'weight_xgb_class_2': 0.8090017662969399}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:37,414] Trial 256 finished with value: 0.9495812884103073 and parameters: {'weight_lgbm_class_0': 0.01810453420867256, 'weight_lgbm_class_1': 0.3163264795940662, 'weight_lgbm_class_2': 0.4345307208188838, 'weight_xgb_class_0': 0.07420468278883899, 'weight_xgb_class_1': 0.9594377564838075, 'weight_xgb_class_2': 0.8888481162239221}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:37,428] Trial 255 finished with value: 0.9496983713762982 and parameters: {'weight_lgbm_class_0': 0.018248317014617432, 'weight_lgbm_class_1': 0.29214899333977856, 'weight_lgbm_class_2': 0.3862188674263587, 'weight_xgb_class_0': 0.07550376133280513, 'weight_xgb_class_1': 0.9665625909853119, 'weight_xgb_class_2': 0.8623858421011605}. Best is trial 148 with value: 0.9497284500344522.

Best trial: 265. Best value: 0.949735:  13%|█████████████████▍                                                                                                                  | 264/2000 [00:06<00:42, 41.18it/s]

[I 2026-07-05 15:31:37,463] Trial 258 finished with value: 0.941761085811883 and parameters: {'weight_lgbm_class_0': 0.33725589515255405, 'weight_lgbm_class_1': 0.5919309046498403, 'weight_lgbm_class_2': 0.6390866905473774, 'weight_xgb_class_0': 0.08448958578224039, 'weight_xgb_class_1': 0.999144437386882, 'weight_xgb_class_2': 0.8893092494736466}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:37,497] Trial 257 finished with value: 0.9496952348669522 and parameters: {'weight_lgbm_class_0': 0.02038804581640708, 'weight_lgbm_class_1': 0.6062622957198788, 'weight_lgbm_class_2': 0.43365058684602675, 'weight_xgb_class_0': 0.0759758338236918, 'weight_xgb_class_1': 0.9661941316628483, 'weight_xgb_class_2': 0.891345383210496}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:37,499] Trial 259 finished with value: 0.9492555671956535 and parameters: {'weight_lgbm_class_0': 0.000680044467486686, 'weight_lgbm_class_1': 0.6000821161872727, 'weight_lgbm_class_2': 0.6359542522904964, 'weight_xgb_class_0': 0.08319475010926194, 'weight_xgb_class_1': 0.9692347903729681, 'weight_xgb_class_2': 0.8884955685044306}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:37,528] Trial 260 finished with value: 0.9493812500978769 and parameters: {'weight_lgbm_class_0': 0.000373383000643511, 'weight_lgbm_class_1': 0.2365379594805909, 'weight_lgbm_class_2': 0.6447580069187359, 'weight_xgb_class_0': 0.11124566503091307, 'weight_xgb_class_1': 0.9701074313532136, 'weight_xgb_class_2': 0.887938213513017}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:37,551] Trial 261 finished with value: 0.9496107209688164 and parameters: {'weight_lgbm_class_0': 0.0015334594737336088, 'weight_lgbm_class_1': 0.3015382844710544, 'weight_lgbm_class_2': 0.3930153480890405, 'weight_xgb_class_0': 0.1472948889865387, 'weight_xgb_class_1': 0.9979549045298681, 'weight_xgb_class_2': 0.8828956177777351}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:37,569] Trial 262 finished with value: 0.9496081504078134 and parameters: {'weight_lgbm_class_0': 0.001995053417110454, 'weight_lgbm_class_1': 0.3181760031229811, 'weight_lgbm_class_2': 0.4350338639851774, 'weight_xgb_class_0': 0.11351465275269662, 'weight_xgb_class_1': 0.9747111545759187, 'weight_xgb_class_2': 0.8855758081148285}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:37,602] Trial 263 finished with value: 0.9496333774879749 and parameters: {'weight_lgbm_class_0': 0.06592179435481416, 'weight_lgbm_class_1': 0.6032522503001443, 'weight_lgbm_class_2': 0.6742714699638597, 'weight_xgb_class_0': 0.11315919367084981, 'weight_xgb_class_1': 0.9971062531939575, 'weight_xgb_class_2': 0.886115676208071}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:37,630] Trial 264 finished with value: 0.949620003511653 and parameters: {'weight_lgbm_class_0': 0.003390140873038107, 'weight_lgbm_class_1': 0.30107508636949804, 'weight_lgbm_class_2': 0.3969084343383192, 'weight_xgb_class_0': 0.144868371794675, 'weight_xgb_class_1': 0.9965681485107012, 'weight_xgb_class_2': 0.8828541644119181}. Best is trial 148 with value: 0.9497284500344522.

Best trial: 265. Best value: 0.949735:  14%|██████████████████                                                                                                                  | 274/2000 [00:06<00:39, 44.24it/s]

[I 2026-07-05 15:31:37,640] Trial 266 finished with value: 0.9494895363432051 and parameters: {'weight_lgbm_class_0': 0.00033733790183068657, 'weight_lgbm_class_1': 0.2275735190734221, 'weight_lgbm_class_2': 0.4042100671904932, 'weight_xgb_class_0': 0.1451056194702129, 'weight_xgb_class_1': 0.9945516314292413, 'weight_xgb_class_2': 0.887275465449082}. Best is trial 148 with value: 0.9497284500344522.
[I 2026-07-05 15:31:37,651] Trial 265 finished with value: 0.949734712633982 and parameters: {'weight_lgbm_class_0': 0.05759771090162166, 'weight_lgbm_class_1': 0.974921534498515, 'weight_lgbm_class_2': 0.6711233766149751, 'weight_xgb_class_0': 0.11497499320816743, 'weight_xgb_class_1': 0.9997925670612773, 'weight_xgb_class_2': 0.8811401865155591}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:37,698] Trial 267 finished with value: 0.9495662867640681 and parameters: {'weight_lgbm_class_0': 0.006018563538277469, 'weight_lgbm_class_1': 0.29619468471382765, 'weight_lgbm_class_2': 0.35119079607912207, 'weight_xgb_class_0': 0.11298773135619679, 'weight_xgb_class_1': 0.9274367602569954, 'weight_xgb_class_2': 0.8920876529958004}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:37,706] Trial 269 finished with value: 0.9495077665286872 and parameters: {'weight_lgbm_class_0': 0.033523004881061164, 'weight_lgbm_class_1': 0.3118763354586149, 'weight_lgbm_class_2': 0.4024928283502534, 'weight_xgb_class_0': 0.11319778432292596, 'weight_xgb_class_1': 0.9208902413465765, 'weight_xgb_class_2': 0.8898217175025324}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:37,709] Trial 268 finished with value: 0.9486033141103395 and parameters: {'weight_lgbm_class_0': 0.03339924467192651, 'weight_lgbm_class_1': 0.23813498772759634, 'weight_lgbm_class_2': 0.3599963729565236, 'weight_xgb_class_0': 0.14175025645474132, 'weight_xgb_class_1': 0.9249135570296684, 'weight_xgb_class_2': 0.886114540564686}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:37,754] Trial 271 finished with value: 0.9487349766418087 and parameters: {'weight_lgbm_class_0': 0.03427363124862517, 'weight_lgbm_class_1': 0.3122703909152815, 'weight_lgbm_class_2': 0.4116792410498786, 'weight_xgb_class_0': 0.1478973485441902, 'weight_xgb_class_1': 0.9980118484791848, 'weight_xgb_class_2': 0.8734159650076807}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:37,764] Trial 270 finished with value: 0.9477292926418485 and parameters: {'weight_lgbm_class_0': 0.06263349913744626, 'weight_lgbm_class_1': 0.2432702707101222, 'weight_lgbm_class_2': 0.3732983348499594, 'weight_xgb_class_0': 0.14418660297818675, 'weight_xgb_class_1': 0.9138998289526231, 'weight_xgb_class_2': 0.879870626356329}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:37,801] Trial 273 finished with value: 0.9479230736026966 and parameters: {'weight_lgbm_class_0': 0.06448376507344683, 'weight_lgbm_class_1': 0.28965629558207284, 'weight_lgbm_class_2': 0.3495523233174545, 'weight_xgb_class_0': 0.14206027131740626, 'weight_xgb_class_1': 0.9199733144552699, 'weight_xgb_class_2': 0.925378690178516}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:37,825] Trial 272 finished with value: 0.9488599357679801 and parameters: {'weight_lgbm_class_0': 0.061525258490866014, 'weight_lgbm_class_1': 0.2869396530437449, 'weight_lgbm_class_2': 0.35376246319184557, 'weight_xgb_class_0': 0.11063682651581536, 'weight_xgb_class_1': 0.917454108327029, 'weight_xgb_class_2': 0.9358871453953478}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:37,828] Trial 274 finished with value: 0.9490259506164357 and parameters: {'weight_lgbm_class_0': 0.058522803508437624, 'weight_lgbm_class_1': 0.27948349109564125, 'weight_lgbm_class_2': 0.3453312762281866, 'weight_xgb_class_0': 0.10160742927335709, 'weight_xgb_class_1': 0.9203257917536429, 'weight_xgb_class_2': 0.8656872008535149}. Best is trial 265 with value: 0.949734712633982.

Best trial: 265. Best value: 0.949735:  14%|██████████████████▋                                                                                                                 | 283/2000 [00:06<00:39, 43.04it/s]

[I 2026-07-05 15:31:37,870] Trial 275 finished with value: 0.9492322791098696 and parameters: {'weight_lgbm_class_0': 0.06412892725699028, 'weight_lgbm_class_1': 0.9946176137882244, 'weight_lgbm_class_2': 0.3506481044118088, 'weight_xgb_class_0': 0.10992669811992592, 'weight_xgb_class_1': 0.9686071227587074, 'weight_xgb_class_2': 0.910995950215864}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:37,898] Trial 276 finished with value: 0.9493941117285027 and parameters: {'weight_lgbm_class_0': 0.06211793864558067, 'weight_lgbm_class_1': 0.9810032927625385, 'weight_lgbm_class_2': 0.42333542094902166, 'weight_xgb_class_0': 0.11335782416389148, 'weight_xgb_class_1': 0.9660101868758796, 'weight_xgb_class_2': 0.9276078720688392}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:37,935] Trial 277 finished with value: 0.9447398964494625 and parameters: {'weight_lgbm_class_0': 0.06151229188180251, 'weight_lgbm_class_1': 0.9932383819488559, 'weight_lgbm_class_2': 0.363203625767361, 'weight_xgb_class_0': 0.1007625407366025, 'weight_xgb_class_1': 0.9674631321620354, 'weight_xgb_class_2': 0.18182343316613486}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:37,951] Trial 279 finished with value: 0.9495115369989665 and parameters: {'weight_lgbm_class_0': 0.05766063244083782, 'weight_lgbm_class_1': 0.9785687174992131, 'weight_lgbm_class_2': 0.412091533231387, 'weight_xgb_class_0': 0.11111704632733133, 'weight_xgb_class_1': 0.9709588379191778, 'weight_xgb_class_2': 0.9202129525124884}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:37,955] Trial 278 finished with value: 0.9488720129090534 and parameters: {'weight_lgbm_class_0': 0.06061549931512375, 'weight_lgbm_class_1': 0.9641986812015366, 'weight_lgbm_class_2': 0.6950047105083075, 'weight_xgb_class_0': 0.02155881164928771, 'weight_xgb_class_1': 0.9714387277932289, 'weight_xgb_class_2': 0.9270394411298263}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:37,975] Trial 280 finished with value: 0.9497084759291171 and parameters: {'weight_lgbm_class_0': 0.06164976724273627, 'weight_lgbm_class_1': 0.9705972350563912, 'weight_lgbm_class_2': 0.7453241966902174, 'weight_xgb_class_0': 0.09932069403065993, 'weight_xgb_class_1': 0.975791386906806, 'weight_xgb_class_2': 0.9259074361826526}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:38,027] Trial 283 finished with value: 0.9497146958278248 and parameters: {'weight_lgbm_class_0': 0.10306925223059915, 'weight_lgbm_class_1': 0.9673852427677033, 'weight_lgbm_class_2': 0.700068206933634, 'weight_xgb_class_0': 0.02305003419429092, 'weight_xgb_class_1': 0.9773305966272338, 'weight_xgb_class_2': 0.8411718067803544}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:38,030] Trial 281 finished with value: 0.9488958744083019 and parameters: {'weight_lgbm_class_0': 0.06103781152862313, 'weight_lgbm_class_1': 0.9817223411734103, 'weight_lgbm_class_2': 0.750078199574567, 'weight_xgb_class_0': 0.02086991043825616, 'weight_xgb_class_1': 0.968557789886171, 'weight_xgb_class_2': 0.8629581953215777}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:38,033] Trial 282 finished with value: 0.9496735191496343 and parameters: {'weight_lgbm_class_0': 0.05997997154611803, 'weight_lgbm_class_1': 0.9869122307010993, 'weight_lgbm_class_2': 0.7487291144551281, 'weight_xgb_class_0': 0.10042550839271763, 'weight_xgb_class_1': 0.9722469199087869, 'weight_xgb_class_2': 0.9348970536788209}. Best is trial 265 with value: 0.949734712633982.

Best trial: 265. Best value: 0.949735:  15%|███████████████████▎                                                                                                                | 292/2000 [00:06<00:41, 41.45it/s]

[I 2026-07-05 15:31:38,048] Trial 284 finished with value: 0.9495662501461326 and parameters: {'weight_lgbm_class_0': 0.09824006213261448, 'weight_lgbm_class_1': 0.997332693075448, 'weight_lgbm_class_2': 0.751514924405455, 'weight_xgb_class_0': 0.09798943219235111, 'weight_xgb_class_1': 0.9688243700478135, 'weight_xgb_class_2': 0.9086913659008858}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:38,092] Trial 285 finished with value: 0.9217495144890249 and parameters: {'weight_lgbm_class_0': 0.09510302702772576, 'weight_lgbm_class_1': 0.11141759816078373, 'weight_lgbm_class_2': 0.6990868500404874, 'weight_xgb_class_0': 0.5542168783035694, 'weight_xgb_class_1': 0.9702558730990796, 'weight_xgb_class_2': 0.8429003542365491}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:38,110] Trial 286 finished with value: 0.9487460624821079 and parameters: {'weight_lgbm_class_0': 0.09521668534714767, 'weight_lgbm_class_1': 0.6262010814942442, 'weight_lgbm_class_2': 0.424490002291953, 'weight_xgb_class_0': 0.09902428311830262, 'weight_xgb_class_1': 0.9718810569712614, 'weight_xgb_class_2': 0.8159775486918893}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:38,135] Trial 287 finished with value: 0.9496875978170108 and parameters: {'weight_lgbm_class_0': 0.0981209621381256, 'weight_lgbm_class_1': 0.9637523423442584, 'weight_lgbm_class_2': 0.748671010652719, 'weight_xgb_class_0': 0.02646662726798113, 'weight_xgb_class_1': 0.9998885928395542, 'weight_xgb_class_2': 0.8433277449825876}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:38,197] Trial 289 finished with value: 0.949594971026276 and parameters: {'weight_lgbm_class_0': 0.09298582161139794, 'weight_lgbm_class_1': 0.6245147221600413, 'weight_lgbm_class_2': 0.741369000945289, 'weight_xgb_class_0': 0.02796699786768901, 'weight_xgb_class_1': 0.8070573245492617, 'weight_xgb_class_2': 0.8472345389279409}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:38,199] Trial 288 finished with value: 0.9497290340446787 and parameters: {'weight_lgbm_class_0': 0.09238338898117687, 'weight_lgbm_class_1': 0.6251959300632459, 'weight_lgbm_class_2': 0.45059084636703545, 'weight_xgb_class_0': 0.027447047006491046, 'weight_xgb_class_1': 0.9820455749880229, 'weight_xgb_class_2': 0.8460188294845253}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:38,207] Trial 290 finished with value: 0.949710092797145 and parameters: {'weight_lgbm_class_0': 0.09003468790896814, 'weight_lgbm_class_1': 0.9637396867953639, 'weight_lgbm_class_2': 0.7312545170190302, 'weight_xgb_class_0': 0.027988933652370374, 'weight_xgb_class_1': 0.9571822214224223, 'weight_xgb_class_2': 0.8152752826192681}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:38,245] Trial 291 finished with value: 0.9496976983839014 and parameters: {'weight_lgbm_class_0': 0.09631646447740731, 'weight_lgbm_class_1': 0.9541075497949741, 'weight_lgbm_class_2': 0.7379990211907711, 'weight_xgb_class_0': 0.03090282995368351, 'weight_xgb_class_1': 0.8101714414686003, 'weight_xgb_class_2': 0.8154295884214123}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:38,258] Trial 292 finished with value: 0.9496392985286723 and parameters: {'weight_lgbm_class_0': 0.12034535135919892, 'weight_lgbm_class_1': 0.9606267559386794, 'weight_lgbm_class_2': 0.747059449818519, 'weight_xgb_class_0': 0.01874030552957162, 'weight_xgb_class_1': 0.8133183893710753, 'weight_xgb_class_2': 0.9463558658738453}. Best is trial 265 with value: 0.949734712633982.

Best trial: 265. Best value: 0.949735:  15%|███████████████████▊                                                                                                                | 301/2000 [00:07<00:42, 40.42it/s]

[I 2026-07-05 15:31:38,277] Trial 293 finished with value: 0.9496803825881798 and parameters: {'weight_lgbm_class_0': 0.11585799026004422, 'weight_lgbm_class_1': 0.9651080751333232, 'weight_lgbm_class_2': 0.7023841424062681, 'weight_xgb_class_0': 0.025492116873353673, 'weight_xgb_class_1': 0.8497681086642002, 'weight_xgb_class_2': 0.9375273307708551}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:38,290] Trial 294 finished with value: 0.9497178690371574 and parameters: {'weight_lgbm_class_0': 0.12424657072949336, 'weight_lgbm_class_1': 0.9166388977344112, 'weight_lgbm_class_2': 0.7421833248040773, 'weight_xgb_class_0': 0.02367739483477694, 'weight_xgb_class_1': 0.8063735492397022, 'weight_xgb_class_2': 0.9365509407510549}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:38,331] Trial 295 finished with value: 0.949702321196014 and parameters: {'weight_lgbm_class_0': 0.1303160382217138, 'weight_lgbm_class_1': 0.9571897100554336, 'weight_lgbm_class_2': 0.7583027892627459, 'weight_xgb_class_0': 0.023459417976388154, 'weight_xgb_class_1': 0.9432259665838194, 'weight_xgb_class_2': 0.8185995018247753}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:38,355] Trial 296 finished with value: 0.9491213428259355 and parameters: {'weight_lgbm_class_0': 0.09118572472399974, 'weight_lgbm_class_1': 0.9510305743759814, 'weight_lgbm_class_2': 0.7240083314010862, 'weight_xgb_class_0': 0.027673901535326294, 'weight_xgb_class_1': 0.06197600594342373, 'weight_xgb_class_2': 0.9402823007240652}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:38,367] Trial 297 finished with value: 0.9496451372796183 and parameters: {'weight_lgbm_class_0': 0.09312192121245982, 'weight_lgbm_class_1': 0.9598589581378009, 'weight_lgbm_class_2': 0.7461196422390065, 'weight_xgb_class_0': 0.022357904891405003, 'weight_xgb_class_1': 0.7836952252080214, 'weight_xgb_class_2': 0.9480092579672955}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:38,405] Trial 299 finished with value: 0.9497241434100901 and parameters: {'weight_lgbm_class_0': 0.09292923314510987, 'weight_lgbm_class_1': 0.9728397000858044, 'weight_lgbm_class_2': 0.7412171374344725, 'weight_xgb_class_0': 0.038794290324681666, 'weight_xgb_class_1': 0.8167609309760684, 'weight_xgb_class_2': 0.8439295436540325}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:38,413] Trial 298 finished with value: 0.9497004155933144 and parameters: {'weight_lgbm_class_0': 0.13404278274969605, 'weight_lgbm_class_1': 0.9493631810964118, 'weight_lgbm_class_2': 0.7275146183828316, 'weight_xgb_class_0': 0.027268650975406317, 'weight_xgb_class_1': 0.8465181803627535, 'weight_xgb_class_2': 0.9411400723492181}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:38,444] Trial 300 finished with value: 0.9496991899476472 and parameters: {'weight_lgbm_class_0': 0.12958867115672823, 'weight_lgbm_class_1': 0.9485134961936637, 'weight_lgbm_class_2': 0.7401807646650137, 'weight_xgb_class_0': 0.012346954373313264, 'weight_xgb_class_1': 0.9893492087756277, 'weight_xgb_class_2': 0.941695235283376}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:38,478] Trial 301 finished with value: 0.9496749442731903 and parameters: {'weight_lgbm_class_0': 0.11108652730859854, 'weight_lgbm_class_1': 0.9534973064107569, 'weight_lgbm_class_2': 0.7373891257812771, 'weight_xgb_class_0': 0.020466078395014728, 'weight_xgb_class_1': 0.7949657735604031, 'weight_xgb_class_2': 0.9362685469981179}. Best is trial 265 with value: 0.949734712633982.

Best trial: 265. Best value: 0.949735:  16%|████████████████████▍                                                                                                               | 310/2000 [00:07<00:39, 42.81it/s]

[I 2026-07-05 15:31:38,493] Trial 302 finished with value: 0.9496630801078108 and parameters: {'weight_lgbm_class_0': 0.11774246505063966, 'weight_lgbm_class_1': 0.9595055678672518, 'weight_lgbm_class_2': 0.7630649546027032, 'weight_xgb_class_0': 0.01840501777317727, 'weight_xgb_class_1': 0.7848709107010226, 'weight_xgb_class_2': 0.912050105935317}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:38,543] Trial 305 finished with value: 0.9496739116750397 and parameters: {'weight_lgbm_class_0': 0.12854239485022687, 'weight_lgbm_class_1': 0.9535037937056702, 'weight_lgbm_class_2': 0.7635824024256697, 'weight_xgb_class_0': 0.015703713808557528, 'weight_xgb_class_1': 0.783725354154261, 'weight_xgb_class_2': 0.9296482592254488}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:38,544] Trial 303 finished with value: 0.9497074079596227 and parameters: {'weight_lgbm_class_0': 0.12675664253359162, 'weight_lgbm_class_1': 0.9516187002899681, 'weight_lgbm_class_2': 0.45460813819844403, 'weight_xgb_class_0': 0.018876177013172457, 'weight_xgb_class_1': 0.7907779613223641, 'weight_xgb_class_2': 0.9071656929690617}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:38,565] Trial 304 finished with value: 0.9495700004473996 and parameters: {'weight_lgbm_class_0': 0.11442230740500278, 'weight_lgbm_class_1': 0.9533729416270645, 'weight_lgbm_class_2': 0.4512400354581677, 'weight_xgb_class_0': 0.01763505348339025, 'weight_xgb_class_1': 0.33385096124473734, 'weight_xgb_class_2': 0.933290826463254}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:38,610] Trial 306 finished with value: 0.9496600320125944 and parameters: {'weight_lgbm_class_0': 0.13351463998937568, 'weight_lgbm_class_1': 0.9644980233005351, 'weight_lgbm_class_2': 0.7641552462196625, 'weight_xgb_class_0': 5.133620534624253e-05, 'weight_xgb_class_1': 0.8010183310397014, 'weight_xgb_class_2': 0.9447864078664931}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:38,626] Trial 307 finished with value: 0.9496620695579373 and parameters: {'weight_lgbm_class_0': 0.1273403916594279, 'weight_lgbm_class_1': 0.9362898989492787, 'weight_lgbm_class_2': 0.7675162291877434, 'weight_xgb_class_0': 0.009349276347860848, 'weight_xgb_class_1': 0.8432538062312798, 'weight_xgb_class_2': 0.9430956931784543}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:38,661] Trial 308 finished with value: 0.9496113046296273 and parameters: {'weight_lgbm_class_0': 0.18392985813794965, 'weight_lgbm_class_1': 0.9763997832364654, 'weight_lgbm_class_2': 0.7605326409430956, 'weight_xgb_class_0': 0.0003665196029311868, 'weight_xgb_class_1': 0.7823074203267835, 'weight_xgb_class_2': 0.9739855402711621}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:38,678] Trial 309 finished with value: 0.9496568061383508 and parameters: {'weight_lgbm_class_0': 0.12538257259503996, 'weight_lgbm_class_1': 0.9730433494192934, 'weight_lgbm_class_2': 0.7560612656919423, 'weight_xgb_class_0': 0.009503655510984662, 'weight_xgb_class_1': 0.8134845257092836, 'weight_xgb_class_2': 0.9695576565191181}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:38,705] Trial 310 finished with value: 0.9496719700842166 and parameters: {'weight_lgbm_class_0': 0.1297417053312639, 'weight_lgbm_class_1': 0.9732805691334057, 'weight_lgbm_class_2': 0.7601491287048785, 'weight_xgb_class_0': 0.0034379029981597177, 'weight_xgb_class_1': 0.8485002907745074, 'weight_xgb_class_2': 0.9658174791825861}. Best is trial 265 with value: 0.949734712633982.

Best trial: 265. Best value: 0.949735:  16%|█████████████████████                                                                                                               | 320/2000 [00:07<00:40, 41.12it/s]

[I 2026-07-05 15:31:38,721] Trial 311 finished with value: 0.9496176916159831 and parameters: {'weight_lgbm_class_0': 0.18834253738395298, 'weight_lgbm_class_1': 0.9726141900804597, 'weight_lgbm_class_2': 0.756181308447468, 'weight_xgb_class_0': 0.002285692281113548, 'weight_xgb_class_1': 0.7921444513031302, 'weight_xgb_class_2': 0.9441344029658165}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:38,753] Trial 312 finished with value: 0.949614301586455 and parameters: {'weight_lgbm_class_0': 0.18458819038011903, 'weight_lgbm_class_1': 0.9748443272573034, 'weight_lgbm_class_2': 0.7837198054348827, 'weight_xgb_class_0': 0.009262966851207406, 'weight_xgb_class_1': 0.7778342824686867, 'weight_xgb_class_2': 0.9619806321213336}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:38,804] Trial 314 finished with value: 0.9496058919043451 and parameters: {'weight_lgbm_class_0': 0.1692451390745553, 'weight_lgbm_class_1': 0.9317017273407103, 'weight_lgbm_class_2': 0.7337377311367522, 'weight_xgb_class_0': 0.005734908846757772, 'weight_xgb_class_1': 0.758436537276466, 'weight_xgb_class_2': 0.9454316209585774}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:38,820] Trial 313 finished with value: 0.949576376631866 and parameters: {'weight_lgbm_class_0': 0.18029593126099913, 'weight_lgbm_class_1': 0.9735693206643966, 'weight_lgbm_class_2': 0.7628578525390237, 'weight_xgb_class_0': 0.005271490428578281, 'weight_xgb_class_1': 0.7746518222356512, 'weight_xgb_class_2': 0.9677396083009867}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:38,835] Trial 315 finished with value: 0.949650175939999 and parameters: {'weight_lgbm_class_0': 0.15888066849842664, 'weight_lgbm_class_1': 0.9265866620374642, 'weight_lgbm_class_2': 0.7353880739392566, 'weight_xgb_class_0': 0.003641370086950233, 'weight_xgb_class_1': 0.8007052572269109, 'weight_xgb_class_2': 0.9407533820425805}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:38,850] Trial 316 finished with value: 0.949620398604579 and parameters: {'weight_lgbm_class_0': 0.13043232170337163, 'weight_lgbm_class_1': 0.9319260492794761, 'weight_lgbm_class_2': 0.7908356169437466, 'weight_xgb_class_0': 0.0011005628438947729, 'weight_xgb_class_1': 0.8168388325498316, 'weight_xgb_class_2': 0.9619621320584278}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:38,878] Trial 317 finished with value: 0.9496477778019609 and parameters: {'weight_lgbm_class_0': 0.15739842164654672, 'weight_lgbm_class_1': 0.9292568012924125, 'weight_lgbm_class_2': 0.7967982536349846, 'weight_xgb_class_0': 0.0012290756156146127, 'weight_xgb_class_1': 0.8430936170668459, 'weight_xgb_class_2': 0.9680858183655942}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:38,900] Trial 318 finished with value: 0.9495874962759613 and parameters: {'weight_lgbm_class_0': 0.16170616434190557, 'weight_lgbm_class_1': 0.9195234752037478, 'weight_lgbm_class_2': 0.787652696217584, 'weight_xgb_class_0': 0.030363670455783226, 'weight_xgb_class_1': 0.8110150602164465, 'weight_xgb_class_2': 0.9586230197945994}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:38,929] Trial 320 finished with value: 0.9496019585094798 and parameters: {'weight_lgbm_class_0': 0.13152400570925435, 'weight_lgbm_class_1': 0.9312806225623362, 'weight_lgbm_class_2': 0.7309482630118507, 'weight_xgb_class_0': 0.03839476982472341, 'weight_xgb_class_1': 0.7678931236921491, 'weight_xgb_class_2': 0.9120047876439834}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:38,935] Trial 319 finished with value: 0.9495496120280326 and parameters: {'weight_lgbm_class_0': 0.14827992704920595, 'weight_lgbm_class_1': 0.9311443143051695, 'weight_lgbm_class_2': 0.7303976412846185, 'weight_xgb_class_0': 0.02971807538161275, 'weight_xgb_class_1': 0.7486154165957065, 'weight_xgb_class_2': 0.9688974971196621}. Best is trial 265 with value: 0.949734712633982.

Best trial: 265. Best value: 0.949735:  16%|█████████████████████▋                                                                                                              | 328/2000 [00:07<00:40, 41.22it/s]

[I 2026-07-05 15:31:38,969] Trial 321 finished with value: 0.9495913630042979 and parameters: {'weight_lgbm_class_0': 0.15018552805261, 'weight_lgbm_class_1': 0.9268060564249737, 'weight_lgbm_class_2': 0.7349209056225281, 'weight_xgb_class_0': 0.03585858061875901, 'weight_xgb_class_1': 0.7448078725891849, 'weight_xgb_class_2': 0.9119022949118163}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:39,006] Trial 322 finished with value: 0.9495585612666854 and parameters: {'weight_lgbm_class_0': 0.15056206460884605, 'weight_lgbm_class_1': 0.9226778125297287, 'weight_lgbm_class_2': 0.7933734269749749, 'weight_xgb_class_0': 0.028515926149245422, 'weight_xgb_class_1': 0.7612970036855334, 'weight_xgb_class_2': 0.9220119737072069}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:39,032] Trial 323 finished with value: 0.9496075598567043 and parameters: {'weight_lgbm_class_0': 0.14631469175511191, 'weight_lgbm_class_1': 0.9171944271184643, 'weight_lgbm_class_2': 0.7263740198896537, 'weight_xgb_class_0': 0.03439475753444988, 'weight_xgb_class_1': 0.8151411342067482, 'weight_xgb_class_2': 0.9219016089539416}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:39,047] Trial 324 finished with value: 0.949642700429082 and parameters: {'weight_lgbm_class_0': 0.14587343986031398, 'weight_lgbm_class_1': 0.9223017371401092, 'weight_lgbm_class_2': 0.7191863889879379, 'weight_xgb_class_0': 0.029920978917314045, 'weight_xgb_class_1': 0.8134206954164315, 'weight_xgb_class_2': 0.9286578642929002}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:39,061] Trial 325 finished with value: 0.9495889588523921 and parameters: {'weight_lgbm_class_0': 0.14029866205084943, 'weight_lgbm_class_1': 0.9196364997085574, 'weight_lgbm_class_2': 0.7292943282842076, 'weight_xgb_class_0': 0.034056882892558746, 'weight_xgb_class_1': 0.7377489836518606, 'weight_xgb_class_2': 0.9027372048083094}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:39,105] Trial 326 finished with value: 0.9495844479133804 and parameters: {'weight_lgbm_class_0': 0.1525398303211837, 'weight_lgbm_class_1': 0.9188266167934162, 'weight_lgbm_class_2': 0.7218557660310314, 'weight_xgb_class_0': 0.036166027950426914, 'weight_xgb_class_1': 0.8333242512332738, 'weight_xgb_class_2': 0.906026998835489}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:39,128] Trial 327 finished with value: 0.9492087358263109 and parameters: {'weight_lgbm_class_0': 0.14122481684777144, 'weight_lgbm_class_1': 0.9998583444846952, 'weight_lgbm_class_2': 0.4486286783754795, 'weight_xgb_class_0': 0.040784747140250155, 'weight_xgb_class_1': 0.7603100274872355, 'weight_xgb_class_2': 0.906881194005686}. Best is trial 265 with value: 0.949734712633982.
[I 2026-07-05 15:31:39,172] Trial 329 finished with value: 0.9496644079684843 and parameters: {'weight_lgbm_class_0': 0.13608235461647686, 'weight_lgbm_class_1': 0.9468290977419711, 'weight_lgbm_class_2': 0.7288571325843036, 'weight_xgb_class_0': 0.03274677720164022, 'weight_xgb_class_1': 0.8260598856395229, 'weight_xgb_class_2': 0.9138738716144003}. Best is trial 265 with value: 0.949734712633982.

[I 2026-07-05 15:31:39,200] Trial 330 finished with value: 0.9497391533032641 and parameters: {'weight_lgbm_class_0': 0.10534521806363052, 'weight_lgbm_class_1': 0.9593288109457921, 'weight_lgbm_class_2': 0.44215738539310784, 'weight_xgb_class_0': 0.0313268319238726, 'weight_xgb_class_1': 0.8518655837745421, 'weight_xgb_class_2': 0.9052054223872155}. Best is trial 330 with value: 0.9497391533032641.
[I 2026-07-05 15:31:39,203] Trial 328 finished with value: 0.9493457591917851 and parameters: {'weight_lgbm_class_0': 0.14028638131355134, 'weight_lgbm_class_1': 0.9442958504149433, 'weight_lgbm_class_2': 0.45148387492079944, 'weight_xgb_class_0': 0.03446439579169957, 'weight_xgb_class_1': 0.8246566270662077, 'weight_xgb_class_2': 0.9078530382656965}. Best is trial 330 with value: 0.9497391533032641.
[I 2026-07-05 15:31:39,237] Trial 331 finished with value: 0.9497177884177503 and parameters: {'weight_lgbm_class_0': 0.11482867757644064, 'weight_lgbm_class_1': 0.9493493571242742, 'weight_lgbm_class_2': 0.451516647576871, 'weight_xgb_class_0': 0.04286469334473379, 'weight_xgb_class_1': 0.834746544681455, 'weight_xgb_class_2': 0.9099846452106851}. Best is trial 330 with value: 0.9497391533032641.
[I 2026-07-05 15:31:39,252] Trial 333 finished with value: 0.9496918219127162 and parameters: {'weight_lgbm_class_0': 0.1115678874568663, 'weight_lgbm_class_1': 0.9491363092150784, 'weight_lgbm_class_2': 0.7098553308713811, 'weight_xgb_class_0': 0.03600752874598489, 'weight_xgb_class_1': 0.8289352201127904, 'weight_xgb_class_2': 0.9092990513689043}. Best is trial 330 with value: 0.9497391533032641.
[I 2026-07-05 15:31:39,259] Trial 332 finished with value: 0.9496800147967964 and parameters: {'weight_lgbm_class_0': 0.10859434481019176, 'weight_lgbm_class_1': 0.9479234164829993, 'weight_lgbm_class_2': 0.7076698488956621, 'weight_xgb_class_0': 0.036513704954620474, 'weight_xgb_class_1': 0.8293428552368312, 'weight_xgb_class_2': 0.9009274933494494}. Best is trial 330 with value: 0.9497391533032641.
[I 2026-07-05 15:31:39,294] Trial 334 finished with value: 0.949725216352454 and parameters: {'weight_lgbm_class_0': 0.11084288622047968, 'weight_lgbm_class_1': 0.9448895090374558, 'weight_lgbm_class_2': 0.704943737010659, 'weight_xgb_class_0': 0.04304568326446528, 'weight_xgb_class_1': 0.833627389067452, 'weight_xgb_class_2': 0.9003322076360999}. Best is trial 330 with value: 0.9497391533032641.
[I 2026-07-05 15:31:39,304] Trial 335 finished with value: 0.9495079611693494 and parameters: {'weight_lgbm_class_0': 0.10894239862755732, 'weight_lgbm_class_1': 0.9993651940232933, 'weight_lgbm_class_2': 0.45314942426074256, 'weight_xgb_class_0': 0.04651876593331357, 'weight_xgb_class_1': 0.8620243028586904, 'weight_xgb_class_2': 0.7976286558161712}. Best is trial 330 with value: 0.9497391533032641.
[I 2026-07-05 15:31:39,330] Trial 336 finished with value: 0.9330160826394925 and parameters: {'weight_lgbm_class_0': 0.10668382676355205, 'weight_lgbm_class_1': 0.9991711423275186, 'weight_lgbm_class_2': 0.44740747902589345, 'weight_xgb_class_0': 0.43953919977528494, 'weight_xgb_class_1': 0.8496190453215231, 'weight_xgb_class_2': 0.794885716062101}. Best is trial 330 with value: 0.9497391533032641.
[I 2026-07-05 15:31:39,355] Trial 337 finished with value: 0.9494814546758404 and parameters: {'weight_lgbm_class_0': 0.11152643571152085, 'weight_lgbm_class_1': 0.9547895325452739, 'weight_lgbm_class_2': 0.4571391592503389, 'weight_xgb_class_0': 0.04847139201088698, 'weight_xgb_class_1': 0.8555292678838481, 'weight_xgb_class_2': 0.8094728596550508}. Best is trial 330 with value: 0.9497391533032641.

[I 2026-07-05 15:31:39,390] Trial 338 finished with value: 0.9495615250982682 and parameters: {'weight_lgbm_class_0': 0.1194723724969515, 'weight_lgbm_class_1': 0.9528844792775097, 'weight_lgbm_class_2': 0.6987330976660413, 'weight_xgb_class_0': 0.05711087238899955, 'weight_xgb_class_1': 0.8527030432848315, 'weight_xgb_class_2': 0.791670611161139}. Best is trial 330 with value: 0.9497391533032641.
[I 2026-07-05 15:31:39,402] Trial 339 finished with value: 0.9497046501540597 and parameters: {'weight_lgbm_class_0': 0.11205288080005162, 'weight_lgbm_class_1': 0.9512176069376953, 'weight_lgbm_class_2': 0.7091664840089613, 'weight_xgb_class_0': 0.052886368946227384, 'weight_xgb_class_1': 0.8571183087858882, 'weight_xgb_class_2': 0.7999419464812331}. Best is trial 330 with value: 0.9497391533032641.
[I 2026-07-05 15:31:39,421] Trial 340 finished with value: 0.9496287215916431 and parameters: {'weight_lgbm_class_0': 0.1075508768058856, 'weight_lgbm_class_1': 0.9504961362303984, 'weight_lgbm_class_2': 0.457521243569312, 'weight_xgb_class_0': 0.0526920399655716, 'weight_xgb_class_1': 0.8427387490118265, 'weight_xgb_class_2': 0.866924625757859}. Best is trial 330 with value: 0.9497391533032641.
[I 2026-07-05 15:31:39,481] Trial 341 finished with value: 0.9497089824709256 and parameters: {'weight_lgbm_class_0': 0.1090593548827896, 'weight_lgbm_class_1': 0.9629202533924843, 'weight_lgbm_class_2': 0.5008413300618367, 'weight_xgb_class_0': 0.05131881967456611, 'weight_xgb_class_1': 0.8553943908082166, 'weight_xgb_class_2': 0.8731984830037238}. Best is trial 330 with value: 0.9497391533032641.
[I 2026-07-05 15:31:39,496] Trial 343 finished with value: 0.948571702868537 and parameters: {'weight_lgbm_class_0': 0.1053243793217506, 'weight_lgbm_class_1': 0.04460537078219767, 'weight_lgbm_class_2': 0.492797446440369, 'weight_xgb_class_0': 0.05371309282583847, 'weight_xgb_class_1': 0.8553979903453472, 'weight_xgb_class_2': 0.8650417954263361}. Best is trial 330 with value: 0.9497391533032641.
[I 2026-07-05 15:31:39,500] Trial 342 finished with value: 0.9483426864628154 and parameters: {'weight_lgbm_class_0': 0.1109081984509179, 'weight_lgbm_class_1': 0.02801290199820422, 'weight_lgbm_class_2': 0.5036665385810095, 'weight_xgb_class_0': 0.05562368081198901, 'weight_xgb_class_1': 0.8507063819789704, 'weight_xgb_class_2': 0.895484353099052}. Best is trial 330 with value: 0.9497391533032641.
[I 2026-07-05 15:31:39,554] Trial 344 finished with value: 0.9497267320744675 and parameters: {'weight_lgbm_class_0': 0.10042859815934943, 'weight_lgbm_class_1': 0.8947337711852662, 'weight_lgbm_class_2': 0.7026552124051139, 'weight_xgb_class_0': 0.051109722647421245, 'weight_xgb_class_1': 0.8427241980978192, 'weight_xgb_class_2': 0.8705554006986409}. Best is trial 330 with value: 0.9497391533032641.
[I 2026-07-05 15:31:39,570] Trial 345 finished with value: 0.937646718913749 and parameters: {'weight_lgbm_class_0': 0.10268181950484563, 'weight_lgbm_class_1': 0.8947727468875586, 'weight_lgbm_class_2': 0.7069545848560609, 'weight_xgb_class_0': 0.4366821255728126, 'weight_xgb_class_1': 0.8504266975064653, 'weight_xgb_class_2': 0.8709177076270324}. Best is trial 330 with value: 0.9497391533032641.

[I 2026-07-05 15:31:39,582] Trial 346 finished with value: 0.948530532772255 and parameters: {'weight_lgbm_class_0': 0.09888836596912878, 'weight_lgbm_class_1': 0.020227498747338257, 'weight_lgbm_class_2': 0.4988760633964763, 'weight_xgb_class_0': 0.05255680278823313, 'weight_xgb_class_1': 0.8385437491602283, 'weight_xgb_class_2': 0.8675320568592076}. Best is trial 330 with value: 0.9497391533032641.
[I 2026-07-05 15:31:39,593] Trial 347 finished with value: 0.9497184089431157 and parameters: {'weight_lgbm_class_0': 0.10221410792405661, 'weight_lgbm_class_1': 0.8980914378314054, 'weight_lgbm_class_2': 0.7084741158732513, 'weight_xgb_class_0': 0.05588731397255636, 'weight_xgb_class_1': 0.8377152635902395, 'weight_xgb_class_2': 0.8756179902879196}. Best is trial 330 with value: 0.9497391533032641.
[I 2026-07-05 15:31:39,626] Trial 348 finished with value: 0.9497269367433852 and parameters: {'weight_lgbm_class_0': 0.09601372448270441, 'weight_lgbm_class_1': 0.9517858115515007, 'weight_lgbm_class_2': 0.32683036983300195, 'weight_xgb_class_0': 0.04618856524741287, 'weight_xgb_class_1': 0.9998706762642567, 'weight_xgb_class_2': 0.8727482917360351}. Best is trial 330 with value: 0.9497391533032641.
[I 2026-07-05 15:31:39,681] Trial 349 finished with value: 0.9076734246144375 and parameters: {'weight_lgbm_class_0': 0.09368926672861985, 'weight_lgbm_class_1': 0.8961356995920841, 'weight_lgbm_class_2': 0.7111509772252753, 'weight_xgb_class_0': 0.9716446416145994, 'weight_xgb_class_1': 0.8286302999309316, 'weight_xgb_class_2': 0.8973025507428367}. Best is trial 330 with value: 0.9497391533032641.
[I 2026-07-05 15:31:39,684] Trial 350 finished with value: 0.9497104098405805 and parameters: {'weight_lgbm_class_0': 0.09512302391463534, 'weight_lgbm_class_1': 0.9696325661940914, 'weight_lgbm_class_2': 0.5009240557704653, 'weight_xgb_class_0': 0.05218374924869208, 'weight_xgb_class_1': 0.9996042939800923, 'weight_xgb_class_2': 0.9003082593111054}. Best is trial 330 with value: 0.9497391533032641.
[I 2026-07-05 15:31:39,711] Trial 352 finished with value: 0.8996575852686503 and parameters: {'weight_lgbm_class_0': 0.09085593739927333, 'weight_lgbm_class_1': 0.8957339928572098, 'weight_lgbm_class_2': 0.38270286728803155, 'weight_xgb_class_0': 0.9709072156958349, 'weight_xgb_class_1': 0.8303368938870195, 'weight_xgb_class_2': 0.8964425840936944}. Best is trial 330 with value: 0.9497391533032641.
[I 2026-07-05 15:31:39,715] Trial 351 finished with value: 0.9496955469452321 and parameters: {'weight_lgbm_class_0': 0.0988419261972139, 'weight_lgbm_class_1': 0.9754741746467588, 'weight_lgbm_class_2': 0.7439660936323262, 'weight_xgb_class_0': 0.05061770944841844, 'weight_xgb_class_1': 0.8335277522509088, 'weight_xgb_class_2': 0.8949106018479683}. Best is trial 330 with value: 0.9497391533032641.
[I 2026-07-05 15:31:39,752] Trial 353 finished with value: 0.9496773112111262 and parameters: {'weight_lgbm_class_0': 0.09400782352801132, 'weight_lgbm_class_1': 0.9783078676084226, 'weight_lgbm_class_2': 0.70594753141427, 'weight_xgb_class_0': 0.022118420570258035, 'weight_xgb_class_1': 0.8267889275520529, 'weight_xgb_class_2': 0.8963309947531658}. Best is trial 330 with value: 0.9497391533032641.
[I 2026-07-05 15:31:39,767] Trial 354 finished with value: 0.9497700283614133 and parameters: {'weight_lgbm_class_0': 0.09841145078075218, 'weight_lgbm_class_1': 0.9772596564295527, 'weight_lgbm_class_2': 0.3809867560641257, 'weight_xgb_class_0': 0.016703787210841932, 'weight_xgb_class_1': 0.8324523976819728, 'weight_xgb_class_2': 0.8917337561908973}. Best is trial 354 with value: 0.9497700283614133.
[I 2026-07-05 15:31:39,798] Trial 356 finished with value: 0.9488268208590229 and parameters: {'weight_lgbm_class_0': 0.0937811013308909, 'weight_lgbm_class_1': 0.9779817149486538, 'weight_lgbm_class_2': 0.7100748557379813, 'weight_xgb_class_0': 0.024315205110065734, 'weight_xgb_class_1': 0.8226040103493076, 'weight_xgb_class_2': 0.05280203122387711}. Best is trial 354 with value: 0.9497700283614133.

Best trial: 358. Best value: 0.949793:  18%|███████████████████████▉                                                                                                            | 363/2000 [00:08<00:41, 39.90it/s]

[I 2026-07-05 15:31:39,799] Trial 355 finished with value: 0.949780998391423 and parameters: {'weight_lgbm_class_0': 0.09308227303343955, 'weight_lgbm_class_1': 0.9764431790531578, 'weight_lgbm_class_2': 0.38412212940493146, 'weight_xgb_class_0': 0.0198615720874807, 'weight_xgb_class_1': 0.8287433882548366, 'weight_xgb_class_2': 0.8967476249586107}. Best is trial 355 with value: 0.949780998391423.
[I 2026-07-05 15:31:39,856] Trial 357 finished with value: 0.9496304908289863 and parameters: {'weight_lgbm_class_0': 0.12645769559819844, 'weight_lgbm_class_1': 0.895190243380814, 'weight_lgbm_class_2': 0.7115835973637745, 'weight_xgb_class_0': 0.05232245861725998, 'weight_xgb_class_1': 0.8174748356666907, 'weight_xgb_class_2': 0.8980741096654532}. Best is trial 355 with value: 0.949780998391423.
[I 2026-07-05 15:31:39,866] Trial 358 finished with value: 0.9497927483550862 and parameters: {'weight_lgbm_class_0': 0.09101580855329594, 'weight_lgbm_class_1': 0.8860203234911661, 'weight_lgbm_class_2': 0.32499089335708164, 'weight_xgb_class_0': 0.020595701917506405, 'weight_xgb_class_1': 0.8139559573921641, 'weight_xgb_class_2': 0.8939437357466177}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:39,938] Trial 360 finished with value: 0.9489462733410455 and parameters: {'weight_lgbm_class_0': 0.12666156987066998, 'weight_lgbm_class_1': 0.975637877560904, 'weight_lgbm_class_2': 0.28835359909573777, 'weight_xgb_class_0': 0.05098611693123435, 'weight_xgb_class_1': 0.8048697740032458, 'weight_xgb_class_2': 0.8960771460066661}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:39,953] Trial 362 finished with value: 0.9490279592536535 and parameters: {'weight_lgbm_class_0': 0.12633022887116713, 'weight_lgbm_class_1': 0.9835084614037317, 'weight_lgbm_class_2': 0.06364939513619894, 'weight_xgb_class_0': 0.017506961382585125, 'weight_xgb_class_1': 0.7929627365786005, 'weight_xgb_class_2': 0.8816348595637764}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:39,959] Trial 359 finished with value: 0.948961927815056 and parameters: {'weight_lgbm_class_0': 0.12527099679145776, 'weight_lgbm_class_1': 0.9792505601157058, 'weight_lgbm_class_2': 0.308281141702707, 'weight_xgb_class_0': 0.05580081776347058, 'weight_xgb_class_1': 0.8021961988903424, 'weight_xgb_class_2': 0.8938264141260739}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:39,970] Trial 361 finished with value: 0.9496919320049618 and parameters: {'weight_lgbm_class_0': 0.1271764941248517, 'weight_lgbm_class_1': 0.9851874128223238, 'weight_lgbm_class_2': 0.7448992897251658, 'weight_xgb_class_0': 0.01770955922261761, 'weight_xgb_class_1': 0.7964058981496364, 'weight_xgb_class_2': 0.8847222461628405}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:40,002] Trial 363 finished with value: 0.9488140620804631 and parameters: {'weight_lgbm_class_0': 0.13047738628835934, 'weight_lgbm_class_1': 0.9825025376090757, 'weight_lgbm_class_2': 0.263861772823294, 'weight_xgb_class_0': 0.05238966275300178, 'weight_xgb_class_1': 0.8055828882628752, 'weight_xgb_class_2': 0.8772017728486863}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  19%|████████████████████████▌                                                                                                           | 373/2000 [00:08<00:38, 42.26it/s]

[I 2026-07-05 15:31:40,050] Trial 365 finished with value: 0.9496063767318642 and parameters: {'weight_lgbm_class_0': 0.127076121117633, 'weight_lgbm_class_1': 0.9814353987036855, 'weight_lgbm_class_2': 0.32724436368704074, 'weight_xgb_class_0': 0.019157889250986677, 'weight_xgb_class_1': 0.8001950959601165, 'weight_xgb_class_2': 0.8754133227474366}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:40,057] Trial 364 finished with value: 0.949673459763845 and parameters: {'weight_lgbm_class_0': 0.12750092457972423, 'weight_lgbm_class_1': 0.9825009265532859, 'weight_lgbm_class_2': 0.38059529717314355, 'weight_xgb_class_0': 0.019386554463752596, 'weight_xgb_class_1': 0.8050673373234647, 'weight_xgb_class_2': 0.8789758582403212}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:40,066] Trial 366 finished with value: 0.9496773310746099 and parameters: {'weight_lgbm_class_0': 0.12439227017881282, 'weight_lgbm_class_1': 0.9857964647986244, 'weight_lgbm_class_2': 0.4201623532208847, 'weight_xgb_class_0': 0.01755886957215692, 'weight_xgb_class_1': 0.8043777285115653, 'weight_xgb_class_2': 0.8754278015184435}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:40,108] Trial 367 finished with value: 0.9496606945650834 and parameters: {'weight_lgbm_class_0': 0.12693960915958571, 'weight_lgbm_class_1': 0.9855451946181474, 'weight_lgbm_class_2': 0.30048991770293965, 'weight_xgb_class_0': 0.014034390311744084, 'weight_xgb_class_1': 0.8016678939246877, 'weight_xgb_class_2': 0.8781045235366557}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:40,114] Trial 368 finished with value: 0.9480776853348898 and parameters: {'weight_lgbm_class_0': 0.12687475117025207, 'weight_lgbm_class_1': 0.9863501768559096, 'weight_lgbm_class_2': 0.2881517918520811, 'weight_xgb_class_0': 0.017363264762073973, 'weight_xgb_class_1': 0.7986650674502651, 'weight_xgb_class_2': 0.4226192167501019}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:40,140] Trial 369 finished with value: 0.9496422626068742 and parameters: {'weight_lgbm_class_0': 0.12853206082005816, 'weight_lgbm_class_1': 0.9850731355548162, 'weight_lgbm_class_2': 0.3245380500569907, 'weight_xgb_class_0': 0.012695648021857554, 'weight_xgb_class_1': 0.7970335702431213, 'weight_xgb_class_2': 0.9228052871576253}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:40,156] Trial 370 finished with value: 0.9496350282467021 and parameters: {'weight_lgbm_class_0': 0.12918289250011553, 'weight_lgbm_class_1': 0.9849480484504486, 'weight_lgbm_class_2': 0.3144051837195011, 'weight_xgb_class_0': 0.01898067428213828, 'weight_xgb_class_1': 0.7934505190941851, 'weight_xgb_class_2': 0.9224074546781562}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:40,198] Trial 371 finished with value: 0.9495743549409372 and parameters: {'weight_lgbm_class_0': 0.08354302243689223, 'weight_lgbm_class_1': 0.9431345388316587, 'weight_lgbm_class_2': 0.32436679315202227, 'weight_xgb_class_0': 0.015073030669758677, 'weight_xgb_class_1': 0.86613932263282, 'weight_xgb_class_2': 0.9210191091066251}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:40,226] Trial 373 finished with value: 0.9497292847430073 and parameters: {'weight_lgbm_class_0': 0.08792727798099559, 'weight_lgbm_class_1': 0.945553720567997, 'weight_lgbm_class_2': 0.32756468142264983, 'weight_xgb_class_0': 0.02213265491643941, 'weight_xgb_class_1': 0.8504822084536657, 'weight_xgb_class_2': 0.9208648029973885}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:40,248] Trial 372 finished with value: 0.9488707583730842 and parameters: {'weight_lgbm_class_0': 0.16007999778318566, 'weight_lgbm_class_1': 0.9445484868781765, 'weight_lgbm_class_2': 0.22096711004049946, 'weight_xgb_class_0': 0.017922696147750224, 'weight_xgb_class_1': 0.8704045428202255, 'weight_xgb_class_2': 0.9222952111310386}. Best is trial 358 with value: 0.9497927483550862.

[I 2026-07-05 15:31:40,288] Trial 374 finished with value: 0.9489916816220197 and parameters: {'weight_lgbm_class_0': 0.1649069179724997, 'weight_lgbm_class_1': 0.9444144509151795, 'weight_lgbm_class_2': 0.3235972898473775, 'weight_xgb_class_0': 0.014327951378956337, 'weight_xgb_class_1': 0.867934077559739, 'weight_xgb_class_2': 0.9236218155771625}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:40,319] Trial 377 finished with value: 0.9496940779230011 and parameters: {'weight_lgbm_class_0': 0.16057497317996045, 'weight_lgbm_class_1': 0.9488650738191645, 'weight_lgbm_class_2': 0.4664263365028537, 'weight_xgb_class_0': 0.00011190252469828188, 'weight_xgb_class_1': 0.8464989519762522, 'weight_xgb_class_2': 0.9259427607864643}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:40,327] Trial 376 finished with value: 0.9484865812199371 and parameters: {'weight_lgbm_class_0': 0.16867036220020948, 'weight_lgbm_class_1': 0.9456949573012314, 'weight_lgbm_class_2': 0.2612568446774453, 'weight_xgb_class_0': 0.03916261163181019, 'weight_xgb_class_1': 0.8672216837617335, 'weight_xgb_class_2': 0.9157709130735779}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:40,342] Trial 375 finished with value: 0.9489474062164936 and parameters: {'weight_lgbm_class_0': 0.1711550638237574, 'weight_lgbm_class_1': 0.9462087811960703, 'weight_lgbm_class_2': 0.33288372997553295, 'weight_xgb_class_0': 0.016061604859312212, 'weight_xgb_class_1': 0.8697212845834978, 'weight_xgb_class_2': 0.912536035126946}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:40,365] Trial 378 finished with value: 0.9485411184229884 and parameters: {'weight_lgbm_class_0': 0.16978529768624395, 'weight_lgbm_class_1': 0.9448342837423657, 'weight_lgbm_class_2': 0.3255585408892171, 'weight_xgb_class_0': 0.041526055396517526, 'weight_xgb_class_1': 0.8674873319091629, 'weight_xgb_class_2': 0.9206001243787224}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:40,408] Trial 380 finished with value: 0.9486223429260227 and parameters: {'weight_lgbm_class_0': 0.16007182882698318, 'weight_lgbm_class_1': 0.9442233917912854, 'weight_lgbm_class_2': 0.3368367052713849, 'weight_xgb_class_0': 0.04865071443754494, 'weight_xgb_class_1': 0.8643415320397477, 'weight_xgb_class_2': 0.932494147111574}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:40,422] Trial 379 finished with value: 0.9487306122942881 and parameters: {'weight_lgbm_class_0': 0.15894954728862962, 'weight_lgbm_class_1': 0.9454086963871853, 'weight_lgbm_class_2': 0.32104448078344144, 'weight_xgb_class_0': 0.03966514847075919, 'weight_xgb_class_1': 0.8677112762142836, 'weight_xgb_class_2': 0.9195840254541789}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:40,448] Trial 381 finished with value: 0.9486034626805654 and parameters: {'weight_lgbm_class_0': 0.1693575466056079, 'weight_lgbm_class_1': 0.9453525179994956, 'weight_lgbm_class_2': 0.34062324526000864, 'weight_xgb_class_0': 0.03995585883708029, 'weight_xgb_class_1': 0.8721292447137596, 'weight_xgb_class_2': 0.9196003303797201}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:40,460] Trial 382 finished with value: 0.9482487280167041 and parameters: {'weight_lgbm_class_0': 0.1720115099947429, 'weight_lgbm_class_1': 0.9047621927385658, 'weight_lgbm_class_2': 0.2189243796234125, 'weight_xgb_class_0': 0.04237384517043231, 'weight_xgb_class_1': 0.86746624896816, 'weight_xgb_class_2': 0.9218440124765641}. Best is trial 358 with value: 0.9497927483550862.

[I 2026-07-05 15:31:40,494] Trial 383 finished with value: 0.9497464869537926 and parameters: {'weight_lgbm_class_0': 0.08236318067990443, 'weight_lgbm_class_1': 0.9031254171003226, 'weight_lgbm_class_2': 0.3326768077895407, 'weight_xgb_class_0': 0.04340466322764998, 'weight_xgb_class_1': 0.8675984675195098, 'weight_xgb_class_2': 0.9202304407425774}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:40,496] Trial 384 finished with value: 0.9496971861902069 and parameters: {'weight_lgbm_class_0': 0.0867784381812799, 'weight_lgbm_class_1': 0.9001925227254027, 'weight_lgbm_class_2': 0.2644693368453438, 'weight_xgb_class_0': 0.0383208591973119, 'weight_xgb_class_1': 0.8472176154895857, 'weight_xgb_class_2': 0.9060107374061416}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:40,510] Trial 385 finished with value: 0.949756360705544 and parameters: {'weight_lgbm_class_0': 0.08113420290288274, 'weight_lgbm_class_1': 0.8806954526015172, 'weight_lgbm_class_2': 0.34011249659826637, 'weight_xgb_class_0': 0.04369542411909827, 'weight_xgb_class_1': 0.8479888081029706, 'weight_xgb_class_2': 0.9105175969176574}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:40,546] Trial 386 finished with value: 0.949663159123031 and parameters: {'weight_lgbm_class_0': 0.0881148895899663, 'weight_lgbm_class_1': 0.904976585154883, 'weight_lgbm_class_2': 0.3646518371174416, 'weight_xgb_class_0': 0.04806171437561748, 'weight_xgb_class_1': 0.8493331125010444, 'weight_xgb_class_2': 0.9129979073027661}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:40,584] Trial 387 finished with value: 0.9497214496263365 and parameters: {'weight_lgbm_class_0': 0.08546333263933144, 'weight_lgbm_class_1': 0.9079926457147744, 'weight_lgbm_class_2': 0.4779133820437045, 'weight_xgb_class_0': 0.045123471841334375, 'weight_xgb_class_1': 0.8425981880997352, 'weight_xgb_class_2': 0.8998776650060536}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:40,606] Trial 388 finished with value: 0.948105020078588 and parameters: {'weight_lgbm_class_0': 0.079312075583619, 'weight_lgbm_class_1': 0.9039964949852711, 'weight_lgbm_class_2': 0.3663130701858434, 'weight_xgb_class_0': 0.06322267355729072, 'weight_xgb_class_1': 0.8420661296275328, 'weight_xgb_class_2': 0.33939176818654043}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:40,656] Trial 390 finished with value: 0.9496781143030747 and parameters: {'weight_lgbm_class_0': 0.08659902454922916, 'weight_lgbm_class_1': 0.9019490661006822, 'weight_lgbm_class_2': 0.48062011338877186, 'weight_xgb_class_0': 0.06558642305744283, 'weight_xgb_class_1': 0.8364520533065891, 'weight_xgb_class_2': 0.8609636991679491}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:40,667] Trial 389 finished with value: 0.9496840981884747 and parameters: {'weight_lgbm_class_0': 0.08882627716630341, 'weight_lgbm_class_1': 0.9018955036287732, 'weight_lgbm_class_2': 0.38085850759773665, 'weight_xgb_class_0': 0.05765157354149348, 'weight_xgb_class_1': 0.8427160865754688, 'weight_xgb_class_2': 0.9012920216083421}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  20%|██████████████████████████▍                                                                                                         | 400/2000 [00:09<00:37, 42.66it/s]

[I 2026-07-05 15:31:40,672] Trial 391 finished with value: 0.9307570773375956 and parameters: {'weight_lgbm_class_0': 0.5116453942146011, 'weight_lgbm_class_1': 0.9043502768702059, 'weight_lgbm_class_2': 0.37031854041724177, 'weight_xgb_class_0': 0.06304634145345535, 'weight_xgb_class_1': 0.8400913131109159, 'weight_xgb_class_2': 0.8995679026596635}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:40,708] Trial 392 finished with value: 0.9495293355025121 and parameters: {'weight_lgbm_class_0': 0.08049738871558054, 'weight_lgbm_class_1': 0.8840145325262466, 'weight_lgbm_class_2': 0.3788628583091888, 'weight_xgb_class_0': 0.0663156258883869, 'weight_xgb_class_1': 0.4133689665020866, 'weight_xgb_class_2': 0.8980947037593674}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:40,740] Trial 393 finished with value: 0.949695856987859 and parameters: {'weight_lgbm_class_0': 0.08491610937949913, 'weight_lgbm_class_1': 0.876315171538543, 'weight_lgbm_class_2': 0.371587668117453, 'weight_xgb_class_0': 0.06358687918681177, 'weight_xgb_class_1': 0.8417860424763224, 'weight_xgb_class_2': 0.8637707273815627}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:40,764] Trial 394 finished with value: 0.9496777791972901 and parameters: {'weight_lgbm_class_0': 0.08133976667834188, 'weight_lgbm_class_1': 0.8761630451940243, 'weight_lgbm_class_2': 0.37474651558140204, 'weight_xgb_class_0': 0.062479572923577475, 'weight_xgb_class_1': 0.8331702744090428, 'weight_xgb_class_2': 0.8977004738983756}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:40,776] Trial 395 finished with value: 0.9495047310828387 and parameters: {'weight_lgbm_class_0': 0.08556040268289622, 'weight_lgbm_class_1': 0.8654885283832776, 'weight_lgbm_class_2': 0.2929000287785799, 'weight_xgb_class_0': 0.06624391333541702, 'weight_xgb_class_1': 0.8364634467752577, 'weight_xgb_class_2': 0.897515792544772}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:40,794] Trial 396 finished with value: 0.9497037808270493 and parameters: {'weight_lgbm_class_0': 0.08366811137429497, 'weight_lgbm_class_1': 0.8778035626225957, 'weight_lgbm_class_2': 0.3782298306462196, 'weight_xgb_class_0': 0.06599031489795386, 'weight_xgb_class_1': 0.8341653699970221, 'weight_xgb_class_2': 0.896665732921642}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:40,831] Trial 397 finished with value: 0.9495013212101067 and parameters: {'weight_lgbm_class_0': 0.08397856396215332, 'weight_lgbm_class_1': 0.8868403501457127, 'weight_lgbm_class_2': 0.30576491665046407, 'weight_xgb_class_0': 0.06963297890792414, 'weight_xgb_class_1': 0.8297067983637856, 'weight_xgb_class_2': 0.8957226843914452}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:40,832] Trial 398 finished with value: 0.9495544478925718 and parameters: {'weight_lgbm_class_0': 0.08170379489556606, 'weight_lgbm_class_1': 0.87412757190312, 'weight_lgbm_class_2': 0.30634051476415974, 'weight_xgb_class_0': 0.06815262835858402, 'weight_xgb_class_1': 0.830809342050445, 'weight_xgb_class_2': 0.9016392496192838}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:40,860] Trial 399 finished with value: 0.9049996526721452 and parameters: {'weight_lgbm_class_0': 0.800937819374038, 'weight_lgbm_class_1': 0.8678067690513446, 'weight_lgbm_class_2': 0.48538627378283195, 'weight_xgb_class_0': 0.05952678090823716, 'weight_xgb_class_1': 0.8321935740269537, 'weight_xgb_class_2': 0.5603764332183684}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:40,897] Trial 400 finished with value: 0.9496292415105755 and parameters: {'weight_lgbm_class_0': 0.08649251359869357, 'weight_lgbm_class_1': 0.8833882127710677, 'weight_lgbm_class_2': 0.29220017795515874, 'weight_xgb_class_0': 0.056399157561824884, 'weight_xgb_class_1': 0.832845307331871, 'weight_xgb_class_2': 0.8961352073569666}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  20%|██████████████████████████▉                                                                                                         | 408/2000 [00:09<00:37, 42.42it/s]

[I 2026-07-05 15:31:40,920] Trial 401 finished with value: 0.897696940508291 and parameters: {'weight_lgbm_class_0': 0.9872830897594456, 'weight_lgbm_class_1': 0.8842566009903683, 'weight_lgbm_class_2': 0.3027125965200954, 'weight_xgb_class_0': 0.06357178804153166, 'weight_xgb_class_1': 0.8189958736752698, 'weight_xgb_class_2': 0.8922838729431143}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:40,920] Trial 402 finished with value: 0.9492745118403292 and parameters: {'weight_lgbm_class_0': 0.10106279768661261, 'weight_lgbm_class_1': 0.8778743563648583, 'weight_lgbm_class_2': 0.30979198539941066, 'weight_xgb_class_0': 0.05912835143197902, 'weight_xgb_class_1': 0.8284358472271243, 'weight_xgb_class_2': 0.89298105127107}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:40,980] Trial 403 finished with value: 0.9362001049268214 and parameters: {'weight_lgbm_class_0': 0.4382204198356253, 'weight_lgbm_class_1': 0.8598107442166518, 'weight_lgbm_class_2': 0.3440450132667525, 'weight_xgb_class_0': 0.040263598251985486, 'weight_xgb_class_1': 0.8205832324461155, 'weight_xgb_class_2': 0.8882303948099022}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:41,019] Trial 405 finished with value: 0.8709980740187556 and parameters: {'weight_lgbm_class_0': 0.9762348222053425, 'weight_lgbm_class_1': 0.8326381969374156, 'weight_lgbm_class_2': 0.3082312929754424, 'weight_xgb_class_0': 0.682689833008159, 'weight_xgb_class_1': 0.823366231556599, 'weight_xgb_class_2': 0.8717106080492222}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:41,030] Trial 404 finished with value: 0.9497167405177986 and parameters: {'weight_lgbm_class_0': 0.10406508297107789, 'weight_lgbm_class_1': 0.8510997176343457, 'weight_lgbm_class_2': 0.47891670411541365, 'weight_xgb_class_0': 0.03923335466931495, 'weight_xgb_class_1': 0.8194348206404047, 'weight_xgb_class_2': 0.9473727198206371}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:41,081] Trial 406 finished with value: 0.9496593679997408 and parameters: {'weight_lgbm_class_0': 0.10433852765135623, 'weight_lgbm_class_1': 0.9636871285114502, 'weight_lgbm_class_2': 0.40506597208878525, 'weight_xgb_class_0': 0.03798649620269315, 'weight_xgb_class_1': 0.819213412791243, 'weight_xgb_class_2': 0.9534141720278284}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:41,088] Trial 408 finished with value: 0.949298189788915 and parameters: {'weight_lgbm_class_0': 0.10779569346550821, 'weight_lgbm_class_1': 0.827391109719003, 'weight_lgbm_class_2': 0.40503665271235534, 'weight_xgb_class_0': 0.0006172315305210396, 'weight_xgb_class_1': 0.17667564064322178, 'weight_xgb_class_2': 0.94812063101394}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:41,093] Trial 407 finished with value: 0.9481850685193622 and parameters: {'weight_lgbm_class_0': 0.10775791201873214, 'weight_lgbm_class_1': 0.854875143533144, 'weight_lgbm_class_2': 0.2993422371130559, 'weight_xgb_class_0': 3.7758800485593325e-08, 'weight_xgb_class_1': 0.7711143412290495, 'weight_xgb_class_2': 0.24370449369932723}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  21%|███████████████████████████▌                                                                                                        | 417/2000 [00:09<00:36, 42.96it/s]

[I 2026-07-05 15:31:41,133] Trial 409 finished with value: 0.9496704121415864 and parameters: {'weight_lgbm_class_0': 0.107379884677227, 'weight_lgbm_class_1': 0.9626995125529109, 'weight_lgbm_class_2': 0.407470744361351, 'weight_xgb_class_0': 0.03806847516069647, 'weight_xgb_class_1': 0.7821287558013482, 'weight_xgb_class_2': 0.9440026759209519}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:41,157] Trial 411 finished with value: 0.9395142362797596 and parameters: {'weight_lgbm_class_0': 0.46823288498769744, 'weight_lgbm_class_1': 0.9206148745367033, 'weight_lgbm_class_2': 0.40924569461206434, 'weight_xgb_class_0': 0.000719560480163875, 'weight_xgb_class_1': 0.9986474510461285, 'weight_xgb_class_2': 0.9460083500613354}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:41,163] Trial 410 finished with value: 0.9201032467912738 and parameters: {'weight_lgbm_class_0': 0.10170233214847141, 'weight_lgbm_class_1': 0.9644581618219111, 'weight_lgbm_class_2': 0.4144432370411281, 'weight_xgb_class_0': 0.6745516876094169, 'weight_xgb_class_1': 0.7821283461954129, 'weight_xgb_class_2': 0.948145999164778}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:41,202] Trial 413 finished with value: 0.9496954632983785 and parameters: {'weight_lgbm_class_0': 0.10636095109827373, 'weight_lgbm_class_1': 0.9646849711408642, 'weight_lgbm_class_2': 0.39822735925919134, 'weight_xgb_class_0': 0.03685021656747537, 'weight_xgb_class_1': 0.7863579757159074, 'weight_xgb_class_2': 0.8705207319385495}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:41,207] Trial 412 finished with value: 0.9496663187419326 and parameters: {'weight_lgbm_class_0': 0.1054470825730025, 'weight_lgbm_class_1': 0.966864384888217, 'weight_lgbm_class_2': 0.3367451596044911, 'weight_xgb_class_0': 0.035546309073961724, 'weight_xgb_class_1': 0.7822081809262951, 'weight_xgb_class_2': 0.8718813293606555}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:41,240] Trial 414 finished with value: 0.9496073403556161 and parameters: {'weight_lgbm_class_0': 0.11178275116596792, 'weight_lgbm_class_1': 0.8252847223955921, 'weight_lgbm_class_2': 0.344111831964511, 'weight_xgb_class_0': 0.03700979675299217, 'weight_xgb_class_1': 0.9968572729074008, 'weight_xgb_class_2': 0.8719356143123591}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:41,255] Trial 415 finished with value: 0.9496781805584167 and parameters: {'weight_lgbm_class_0': 0.10731678437989917, 'weight_lgbm_class_1': 0.9630930110234829, 'weight_lgbm_class_2': 0.4454795857876528, 'weight_xgb_class_0': 0.03687088146259895, 'weight_xgb_class_1': 0.7758031540288309, 'weight_xgb_class_2': 0.9417615618330049}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:41,295] Trial 416 finished with value: 0.9496904342627804 and parameters: {'weight_lgbm_class_0': 0.10735466571027502, 'weight_lgbm_class_1': 0.9247485966594093, 'weight_lgbm_class_2': 0.4955479893377195, 'weight_xgb_class_0': 0.03343396641023408, 'weight_xgb_class_1': 0.7727771687911752, 'weight_xgb_class_2': 0.9456237080673159}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:41,307] Trial 417 finished with value: 0.9497092957880834 and parameters: {'weight_lgbm_class_0': 0.10988837652817965, 'weight_lgbm_class_1': 0.8384176371352332, 'weight_lgbm_class_2': 0.4817002186913151, 'weight_xgb_class_0': 0.03374378096747091, 'weight_xgb_class_1': 0.9954709363936356, 'weight_xgb_class_2': 0.9345999082773508}. Best is trial 358 with value: 0.9497927483550862.

[I 2026-07-05 15:31:41,388] Trial 418 finished with value: 0.9496912908835045 and parameters: {'weight_lgbm_class_0': 0.10761732077828888, 'weight_lgbm_class_1': 0.9160908873029582, 'weight_lgbm_class_2': 0.46944470367418895, 'weight_xgb_class_0': 0.03116577143040574, 'weight_xgb_class_1': 0.7874771451969897, 'weight_xgb_class_2': 0.9841721599385262}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:41,389] Trial 419 finished with value: 0.9497040831984956 and parameters: {'weight_lgbm_class_0': 0.10756427606749852, 'weight_lgbm_class_1': 0.9217841941131524, 'weight_lgbm_class_2': 0.47198835595289584, 'weight_xgb_class_0': 0.027477829378606867, 'weight_xgb_class_1': 0.9968607088783088, 'weight_xgb_class_2': 0.9806067794544299}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:41,401] Trial 420 finished with value: 0.9495962762064648 and parameters: {'weight_lgbm_class_0': 0.0699270277593326, 'weight_lgbm_class_1': 0.923220121863602, 'weight_lgbm_class_2': 0.5004880396466866, 'weight_xgb_class_0': 0.02723588184113781, 'weight_xgb_class_1': 0.7686492779639528, 'weight_xgb_class_2': 0.9381474602360446}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:41,428] Trial 421 finished with value: 0.94965110367071 and parameters: {'weight_lgbm_class_0': 0.07563558637903223, 'weight_lgbm_class_1': 0.922236923541479, 'weight_lgbm_class_2': 0.47321179533111896, 'weight_xgb_class_0': 0.028736418411586175, 'weight_xgb_class_1': 0.8848284700851915, 'weight_xgb_class_2': 0.8692632921740565}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:41,456] Trial 422 finished with value: 0.9496942604413108 and parameters: {'weight_lgbm_class_0': 0.07047371865140907, 'weight_lgbm_class_1': 0.9231689913103127, 'weight_lgbm_class_2': 0.47130981517972054, 'weight_xgb_class_0': 0.03347468879468131, 'weight_xgb_class_1': 0.7697786851583953, 'weight_xgb_class_2': 0.8666656738488168}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:41,488] Trial 423 finished with value: 0.9493896355778322 and parameters: {'weight_lgbm_class_0': 0.06365409313963855, 'weight_lgbm_class_1': 0.9209258979429809, 'weight_lgbm_class_2': 0.4699824327849117, 'weight_xgb_class_0': 0.023820748115894397, 'weight_xgb_class_1': 0.8860076840806912, 'weight_xgb_class_2': 0.9345842298248612}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:41,508] Trial 424 finished with value: 0.9495739842866749 and parameters: {'weight_lgbm_class_0': 0.07041947278963197, 'weight_lgbm_class_1': 0.9208580152394519, 'weight_lgbm_class_2': 0.4963259274761456, 'weight_xgb_class_0': 0.027189138706003972, 'weight_xgb_class_1': 0.8873821024322652, 'weight_xgb_class_2': 0.9332412082096896}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:41,520] Trial 425 finished with value: 0.949459621919991 and parameters: {'weight_lgbm_class_0': 0.06394585589701249, 'weight_lgbm_class_1': 0.9241790841707593, 'weight_lgbm_class_2': 0.47761639191967237, 'weight_xgb_class_0': 0.027392180023264903, 'weight_xgb_class_1': 0.8077779059334536, 'weight_xgb_class_2': 0.9795473690170149}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:41,544] Trial 427 finished with value: 0.9495011918841888 and parameters: {'weight_lgbm_class_0': 0.0694928269719253, 'weight_lgbm_class_1': 0.9191143538916263, 'weight_lgbm_class_2': 0.4838110391422558, 'weight_xgb_class_0': 0.023557613115976345, 'weight_xgb_class_1': 0.8157937685921758, 'weight_xgb_class_2': 0.9772118538807367}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:41,564] Trial 426 finished with value: 0.9496405932771329 and parameters: {'weight_lgbm_class_0': 0.07394215137583302, 'weight_lgbm_class_1': 0.9999649269593283, 'weight_lgbm_class_2': 0.46840760177888585, 'weight_xgb_class_0': 0.023730549028028503, 'weight_xgb_class_1': 0.8173106985743166, 'weight_xgb_class_2': 0.8564276654541118}. Best is trial 358 with value: 0.9497927483550862.

[I 2026-07-05 15:31:41,581] Trial 428 finished with value: 0.9496937623520306 and parameters: {'weight_lgbm_class_0': 0.07365399200580174, 'weight_lgbm_class_1': 0.9127399760730014, 'weight_lgbm_class_2': 0.47352241773816695, 'weight_xgb_class_0': 0.08436868027513819, 'weight_xgb_class_1': 0.9879498198917954, 'weight_xgb_class_2': 0.9881957019144021}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:41,627] Trial 429 finished with value: 0.9496046205096632 and parameters: {'weight_lgbm_class_0': 0.07211165088163433, 'weight_lgbm_class_1': 0.8436337970802514, 'weight_lgbm_class_2': 0.47691194492019323, 'weight_xgb_class_0': 0.025782467838463455, 'weight_xgb_class_1': 0.8859045886303253, 'weight_xgb_class_2': 0.9353746234229229}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:41,644] Trial 430 finished with value: 0.9494887766354826 and parameters: {'weight_lgbm_class_0': 0.07428996970505607, 'weight_lgbm_class_1': 0.89208400729099, 'weight_lgbm_class_2': 0.4796702263707666, 'weight_xgb_class_0': 0.08831121656627008, 'weight_xgb_class_1': 0.6700819638729842, 'weight_xgb_class_2': 0.8528631655382141}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:41,701] Trial 431 finished with value: 0.9497026875352121 and parameters: {'weight_lgbm_class_0': 0.07045573084384002, 'weight_lgbm_class_1': 0.8515290415960478, 'weight_lgbm_class_2': 0.5036910725706144, 'weight_xgb_class_0': 0.08896199924734019, 'weight_xgb_class_1': 0.9957126234190923, 'weight_xgb_class_2': 0.9266277915619965}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:41,736] Trial 432 finished with value: 0.949686058902925 and parameters: {'weight_lgbm_class_0': 0.06802156876050981, 'weight_lgbm_class_1': 0.8534848707616649, 'weight_lgbm_class_2': 0.49853213739376795, 'weight_xgb_class_0': 0.08793156585142106, 'weight_xgb_class_1': 0.9990942560753909, 'weight_xgb_class_2': 0.9279544307695794}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:41,743] Trial 433 finished with value: 0.9286217175542854 and parameters: {'weight_lgbm_class_0': 0.5771081781597617, 'weight_lgbm_class_1': 0.8499512190950015, 'weight_lgbm_class_2': 0.5108536801194615, 'weight_xgb_class_0': 0.09247929125404487, 'weight_xgb_class_1': 0.9878650540496926, 'weight_xgb_class_2': 0.9291737388236887}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:41,748] Trial 434 finished with value: 0.9289152713957326 and parameters: {'weight_lgbm_class_0': 0.07169329356204573, 'weight_lgbm_class_1': 0.8611067965992851, 'weight_lgbm_class_2': 0.43915056002600056, 'weight_xgb_class_0': 0.578484072519624, 'weight_xgb_class_1': 0.999130231110614, 'weight_xgb_class_2': 0.9215800879033799}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  22%|█████████████████████████████▏                                                                                                      | 443/2000 [00:10<00:39, 39.50it/s]

[I 2026-07-05 15:31:41,758] Trial 435 finished with value: 0.9493582645529594 and parameters: {'weight_lgbm_class_0': 0.08955417283838452, 'weight_lgbm_class_1': 0.9966551569316713, 'weight_lgbm_class_2': 0.3541627767501027, 'weight_xgb_class_0': 0.07844339121944252, 'weight_xgb_class_1': 0.9979523536653547, 'weight_xgb_class_2': 0.9174519667583602}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:41,815] Trial 436 finished with value: 0.9495652721172902 and parameters: {'weight_lgbm_class_0': 0.0851528079499462, 'weight_lgbm_class_1': 0.8094414396329737, 'weight_lgbm_class_2': 0.5183864287572676, 'weight_xgb_class_0': 0.08263018491041191, 'weight_xgb_class_1': 0.9953170873029018, 'weight_xgb_class_2': 0.853430554269186}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:41,825] Trial 437 finished with value: 0.9490438309541935 and parameters: {'weight_lgbm_class_0': 0.09359975930503298, 'weight_lgbm_class_1': 0.8561747706438722, 'weight_lgbm_class_2': 0.43205561585868146, 'weight_xgb_class_0': 0.0878877244346743, 'weight_xgb_class_1': 0.9930764007435149, 'weight_xgb_class_2': 0.8490121318595419}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:41,849] Trial 438 finished with value: 0.9212573695563746 and parameters: {'weight_lgbm_class_0': 0.566093144491113, 'weight_lgbm_class_1': 0.8533521844569381, 'weight_lgbm_class_2': 0.43431306571650197, 'weight_xgb_class_0': 0.07725361365874922, 'weight_xgb_class_1': 0.3834520138573559, 'weight_xgb_class_2': 0.9149671077388548}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:41,876] Trial 439 finished with value: 0.9495270764155754 and parameters: {'weight_lgbm_class_0': 0.08573657489671885, 'weight_lgbm_class_1': 0.8529256261247498, 'weight_lgbm_class_2': 0.43919488200309104, 'weight_xgb_class_0': 0.08018679825242245, 'weight_xgb_class_1': 0.854045065203643, 'weight_xgb_class_2': 0.9198668789937929}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:41,892] Trial 440 finished with value: 0.9302501816465457 and parameters: {'weight_lgbm_class_0': 0.09359595798073599, 'weight_lgbm_class_1': 0.8311544507575228, 'weight_lgbm_class_2': 0.43563945060590853, 'weight_xgb_class_0': 0.5125088637232642, 'weight_xgb_class_1': 0.8561999307130038, 'weight_xgb_class_2': 0.9175874181491337}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:41,907] Trial 441 finished with value: 0.949676834190896 and parameters: {'weight_lgbm_class_0': 0.0969152881972656, 'weight_lgbm_class_1': 0.8412055184245085, 'weight_lgbm_class_2': 0.5114018320652169, 'weight_xgb_class_0': 0.05322253552863642, 'weight_xgb_class_1': 0.854201283585093, 'weight_xgb_class_2': 0.9148489807540728}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:41,941] Trial 442 finished with value: 0.9174145723881219 and parameters: {'weight_lgbm_class_0': 0.7541606476039437, 'weight_lgbm_class_1': 0.845425265077832, 'weight_lgbm_class_2': 0.43748257375299565, 'weight_xgb_class_0': 0.05040165609655398, 'weight_xgb_class_1': 0.8533520481517233, 'weight_xgb_class_2': 0.9211530596796466}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:41,999] Trial 443 finished with value: 0.9293993755593696 and parameters: {'weight_lgbm_class_0': 0.09115931952222421, 'weight_lgbm_class_1': 0.8417222954934774, 'weight_lgbm_class_2': 0.4345181378822765, 'weight_xgb_class_0': 0.5462604407572882, 'weight_xgb_class_1': 0.999247377719534, 'weight_xgb_class_2': 0.9214806824055022}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  22%|█████████████████████████████▋                                                                                                      | 450/2000 [00:10<00:43, 35.42it/s]

[I 2026-07-05 15:31:42,020] Trial 444 finished with value: 0.9490668823143413 and parameters: {'weight_lgbm_class_0': 0.1434971637372498, 'weight_lgbm_class_1': 0.8063309962779307, 'weight_lgbm_class_2': 0.5220274835388081, 'weight_xgb_class_0': 0.048399582015676804, 'weight_xgb_class_1': 0.8624275715548396, 'weight_xgb_class_2': 0.8491724423167991}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:42,079] Trial 445 finished with value: 0.9495342414186214 and parameters: {'weight_lgbm_class_0': 0.0956456795462774, 'weight_lgbm_class_1': 0.9670251931925924, 'weight_lgbm_class_2': 0.4349693357456444, 'weight_xgb_class_0': 0.0513500551346094, 'weight_xgb_class_1': 0.38089238543559933, 'weight_xgb_class_2': 0.9608790429291107}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:42,098] Trial 446 finished with value: 0.9487058479267452 and parameters: {'weight_lgbm_class_0': 0.14573032514383663, 'weight_lgbm_class_1': 0.8050791240178953, 'weight_lgbm_class_2': 0.3396439600730256, 'weight_xgb_class_0': 0.050049046441036464, 'weight_xgb_class_1': 0.8609536968125369, 'weight_xgb_class_2': 0.8828203611829654}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:42,103] Trial 447 finished with value: 0.9496542522280715 and parameters: {'weight_lgbm_class_0': 0.0951335167208881, 'weight_lgbm_class_1': 0.9683925799366955, 'weight_lgbm_class_2': 0.3369920244737192, 'weight_xgb_class_0': 0.04896069307891664, 'weight_xgb_class_1': 0.8117588309400828, 'weight_xgb_class_2': 0.8818291992276461}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:42,124] Trial 448 finished with value: 0.9208876407511463 and parameters: {'weight_lgbm_class_0': 0.755840337954089, 'weight_lgbm_class_1': 0.9982520927728235, 'weight_lgbm_class_2': 0.3457656145173796, 'weight_xgb_class_0': 0.0003572423025752537, 'weight_xgb_class_1': 0.8532282633970412, 'weight_xgb_class_2': 0.9602950319763757}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:42,161] Trial 449 finished with value: 0.9488683812707847 and parameters: {'weight_lgbm_class_0': 0.14736855956357317, 'weight_lgbm_class_1': 0.8936499109281119, 'weight_lgbm_class_2': 0.35308363651888475, 'weight_xgb_class_0': 0.05224674952165101, 'weight_xgb_class_1': 0.8493366323159216, 'weight_xgb_class_2': 0.957907380778283}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:42,208] Trial 450 finished with value: 0.9486216078495255 and parameters: {'weight_lgbm_class_0': 0.14306504953842317, 'weight_lgbm_class_1': 0.96724900316418, 'weight_lgbm_class_2': 0.27344191651521665, 'weight_xgb_class_0': 0.05064480308697677, 'weight_xgb_class_1': 0.8200965001997024, 'weight_xgb_class_2': 0.8819218762016026}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  23%|██████████████████████████████▎                                                                                                     | 459/2000 [00:11<00:40, 37.99it/s]

[I 2026-07-05 15:31:42,244] Trial 452 finished with value: 0.9497378889581305 and parameters: {'weight_lgbm_class_0': 0.12074933964273746, 'weight_lgbm_class_1': 0.9984916472265825, 'weight_lgbm_class_2': 0.3259224448594965, 'weight_xgb_class_0': 0.0015699650958893967, 'weight_xgb_class_1': 0.8102700741485057, 'weight_xgb_class_2': 0.9596038464491019}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:42,261] Trial 451 finished with value: 0.9487642884886346 and parameters: {'weight_lgbm_class_0': 0.1437464883641731, 'weight_lgbm_class_1': 0.9702749695577348, 'weight_lgbm_class_2': 0.33971662400794067, 'weight_xgb_class_0': 0.050572239365282975, 'weight_xgb_class_1': 0.8524419234353026, 'weight_xgb_class_2': 0.883876329223546}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:42,267] Trial 453 finished with value: 0.9485699984850812 and parameters: {'weight_lgbm_class_0': 0.14548669490413338, 'weight_lgbm_class_1': 0.8967277981449807, 'weight_lgbm_class_2': 0.162837491843155, 'weight_xgb_class_0': 0.045553099413536156, 'weight_xgb_class_1': 0.8217976275863617, 'weight_xgb_class_2': 0.9570841732411417}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:42,283] Trial 454 finished with value: 0.9496559396124479 and parameters: {'weight_lgbm_class_0': 0.13772357367439234, 'weight_lgbm_class_1': 0.9668701734396005, 'weight_lgbm_class_2': 0.3396142376843608, 'weight_xgb_class_0': 0.0012881850015236986, 'weight_xgb_class_1': 0.8145364659817826, 'weight_xgb_class_2': 0.8808739312351926}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:42,330] Trial 456 finished with value: 0.9495689599768619 and parameters: {'weight_lgbm_class_0': 0.14135246405752525, 'weight_lgbm_class_1': 0.9652664413344696, 'weight_lgbm_class_2': 0.2772138568734681, 'weight_xgb_class_0': 0.0017131231428267318, 'weight_xgb_class_1': 0.8122392173341086, 'weight_xgb_class_2': 0.8812611001845173}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:42,346] Trial 455 finished with value: 0.9497481892905544 and parameters: {'weight_lgbm_class_0': 0.1203606592831513, 'weight_lgbm_class_1': 0.9998014773344137, 'weight_lgbm_class_2': 0.2800140762740053, 'weight_xgb_class_0': 0.0028843370142754426, 'weight_xgb_class_1': 0.8147258152575261, 'weight_xgb_class_2': 0.9606533048421888}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:42,367] Trial 457 finished with value: 0.9497294557345328 and parameters: {'weight_lgbm_class_0': 0.11613203617792284, 'weight_lgbm_class_1': 0.8972092602734727, 'weight_lgbm_class_2': 0.3182212954812134, 'weight_xgb_class_0': 0.005153810447479718, 'weight_xgb_class_1': 0.8208734703364737, 'weight_xgb_class_2': 0.8791636781416877}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:42,398] Trial 458 finished with value: 0.9497526416868959 and parameters: {'weight_lgbm_class_0': 0.12076206626468404, 'weight_lgbm_class_1': 0.8950052272396471, 'weight_lgbm_class_2': 0.35646040734676376, 'weight_xgb_class_0': 0.0014762665235580064, 'weight_xgb_class_1': 0.8239257495509829, 'weight_xgb_class_2': 0.8843812830366129}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:42,426] Trial 459 finished with value: 0.9496910921097647 and parameters: {'weight_lgbm_class_0': 0.12119900193648239, 'weight_lgbm_class_1': 0.9391043806939762, 'weight_lgbm_class_2': 0.316094645050971, 'weight_xgb_class_0': 0.007404448387006234, 'weight_xgb_class_1': 0.8158726729420053, 'weight_xgb_class_2': 0.8852813032070516}. Best is trial 358 with value: 0.9497927483550862.

[I 2026-07-05 15:31:42,440] Trial 460 finished with value: 0.949743915084427 and parameters: {'weight_lgbm_class_0': 0.11856582211651209, 'weight_lgbm_class_1': 0.9383078979802479, 'weight_lgbm_class_2': 0.2755598547954591, 'weight_xgb_class_0': 0.0018364046022454894, 'weight_xgb_class_1': 0.8135740509194478, 'weight_xgb_class_2': 0.882810226585932}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:42,511] Trial 463 finished with value: 0.9497534675597299 and parameters: {'weight_lgbm_class_0': 0.11755243552598296, 'weight_lgbm_class_1': 0.9395581994634232, 'weight_lgbm_class_2': 0.3187030994054506, 'weight_xgb_class_0': 0.0008103047805969156, 'weight_xgb_class_1': 0.8107141356207102, 'weight_xgb_class_2': 0.8399242772177652}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:42,526] Trial 461 finished with value: 0.9496487066224097 and parameters: {'weight_lgbm_class_0': 0.11458156257535954, 'weight_lgbm_class_1': 0.9358217271189779, 'weight_lgbm_class_2': 0.6919631006327096, 'weight_xgb_class_0': 0.00419209473113254, 'weight_xgb_class_1': 0.8784899181589001, 'weight_xgb_class_2': 0.8896458770391548}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:42,547] Trial 462 finished with value: 0.9496591145128704 and parameters: {'weight_lgbm_class_0': 0.12012395096631714, 'weight_lgbm_class_1': 0.8934861299450519, 'weight_lgbm_class_2': 0.27343260183486606, 'weight_xgb_class_0': 0.013380703462098478, 'weight_xgb_class_1': 0.8024959561111461, 'weight_xgb_class_2': 0.9987486418689726}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:42,577] Trial 464 finished with value: 0.9497627893160164 and parameters: {'weight_lgbm_class_0': 0.12432844672242482, 'weight_lgbm_class_1': 0.9981557998144377, 'weight_lgbm_class_2': 0.3637495927646895, 'weight_xgb_class_0': 3.291726656565186e-05, 'weight_xgb_class_1': 0.8117825141417855, 'weight_xgb_class_2': 0.8379055747315527}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:42,623] Trial 465 finished with value: 0.948735115931815 and parameters: {'weight_lgbm_class_0': 0.20501443511926404, 'weight_lgbm_class_1': 0.993467272985494, 'weight_lgbm_class_2': 0.31658486938811525, 'weight_xgb_class_0': 0.0017099983565275027, 'weight_xgb_class_1': 0.8081774996454058, 'weight_xgb_class_2': 0.9822939456690681}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:42,643] Trial 468 finished with value: 0.9497381511161541 and parameters: {'weight_lgbm_class_0': 0.12231898593162174, 'weight_lgbm_class_1': 0.9867254263414087, 'weight_lgbm_class_2': 0.31624544581139913, 'weight_xgb_class_0': 0.00220398064200307, 'weight_xgb_class_1': 0.803106315292394, 'weight_xgb_class_2': 0.8386310684419693}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  24%|███████████████████████████████▎                                                                                                    | 474/2000 [00:11<00:42, 36.25it/s]

[I 2026-07-05 15:31:42,647] Trial 466 finished with value: 0.9495358518075374 and parameters: {'weight_lgbm_class_0': 0.12147215538835825, 'weight_lgbm_class_1': 0.9955850740056245, 'weight_lgbm_class_2': 0.2854205679769464, 'weight_xgb_class_0': 0.012262284137577194, 'weight_xgb_class_1': 0.26978632897382715, 'weight_xgb_class_2': 0.9810737716757766}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:42,670] Trial 467 finished with value: 0.9497416993898956 and parameters: {'weight_lgbm_class_0': 0.11843782271924394, 'weight_lgbm_class_1': 0.9995704760751617, 'weight_lgbm_class_2': 0.24057791754883198, 'weight_xgb_class_0': 0.0035931188913362715, 'weight_xgb_class_1': 0.8022808694062811, 'weight_xgb_class_2': 0.8386134455475008}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:42,718] Trial 469 finished with value: 0.9496857160844688 and parameters: {'weight_lgbm_class_0': 0.1241011858467662, 'weight_lgbm_class_1': 0.8865033689992768, 'weight_lgbm_class_2': 0.2427044690813136, 'weight_xgb_class_0': 0.0020851709768952634, 'weight_xgb_class_1': 0.7286570905933145, 'weight_xgb_class_2': 0.9024986452265624}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:42,734] Trial 471 finished with value: 0.9497338122096662 and parameters: {'weight_lgbm_class_0': 0.11708143886274079, 'weight_lgbm_class_1': 0.8963987156417272, 'weight_lgbm_class_2': 0.26925041231330965, 'weight_xgb_class_0': 0.00040956824876642664, 'weight_xgb_class_1': 0.8029419681292135, 'weight_xgb_class_2': 0.8435587749076469}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:42,740] Trial 470 finished with value: 0.9488150192458491 and parameters: {'weight_lgbm_class_0': 0.201868206916198, 'weight_lgbm_class_1': 0.9993615599207717, 'weight_lgbm_class_2': 0.31844416727052005, 'weight_xgb_class_0': 0.0006381602237744491, 'weight_xgb_class_1': 0.7983746526023545, 'weight_xgb_class_2': 0.9852795732499355}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:42,780] Trial 472 finished with value: 0.9476951482934434 and parameters: {'weight_lgbm_class_0': 0.21839686256418994, 'weight_lgbm_class_1': 0.8917511705187783, 'weight_lgbm_class_2': 0.2398565966460222, 'weight_xgb_class_0': 0.0049416541066149115, 'weight_xgb_class_1': 0.7941212186913001, 'weight_xgb_class_2': 0.8607749496477461}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:42,841] Trial 473 finished with value: 0.9496231612184437 and parameters: {'weight_lgbm_class_0': 0.12982666587183223, 'weight_lgbm_class_1': 0.8865579413152134, 'weight_lgbm_class_2': 0.28019995105924994, 'weight_xgb_class_0': 0.003972036876182224, 'weight_xgb_class_1': 0.7339226909528196, 'weight_xgb_class_2': 0.9942829652473245}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:42,860] Trial 474 finished with value: 0.9485202198996374 and parameters: {'weight_lgbm_class_0': 0.19563599109929874, 'weight_lgbm_class_1': 0.9940680106691948, 'weight_lgbm_class_2': 0.3140661499776211, 'weight_xgb_class_0': 0.004392680522678695, 'weight_xgb_class_1': 0.7942931387744843, 'weight_xgb_class_2': 0.8557855739534017}. Best is trial 358 with value: 0.9497927483550862.

[I 2026-07-05 15:31:42,882] Trial 476 finished with value: 0.9484214364429429 and parameters: {'weight_lgbm_class_0': 0.19865010571798933, 'weight_lgbm_class_1': 0.9990374579940812, 'weight_lgbm_class_2': 0.2824546799743256, 'weight_xgb_class_0': 0.002758143412516862, 'weight_xgb_class_1': 0.739886076515566, 'weight_xgb_class_2': 0.8416209414610943}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:42,885] Trial 475 finished with value: 0.9467076233250912 and parameters: {'weight_lgbm_class_0': 0.25577903889282205, 'weight_lgbm_class_1': 0.901346111891895, 'weight_lgbm_class_2': 0.32213648049795357, 'weight_xgb_class_0': 0.00782145590153344, 'weight_xgb_class_1': 0.7924569996462748, 'weight_xgb_class_2': 0.8407251517985049}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:42,920] Trial 477 finished with value: 0.9491420975527142 and parameters: {'weight_lgbm_class_0': 0.14459208587213357, 'weight_lgbm_class_1': 0.9949410287635962, 'weight_lgbm_class_2': 0.23513032269041256, 'weight_xgb_class_0': 0.007517227292301365, 'weight_xgb_class_1': 0.7905255639246418, 'weight_xgb_class_2': 0.8358095937803199}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:42,971] Trial 479 finished with value: 0.9493147294564505 and parameters: {'weight_lgbm_class_0': 0.14512341579567378, 'weight_lgbm_class_1': 0.9981958939141409, 'weight_lgbm_class_2': 0.26143464990367904, 'weight_xgb_class_0': 0.003874736007933512, 'weight_xgb_class_1': 0.786959100079095, 'weight_xgb_class_2': 0.844342570429354}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:42,979] Trial 478 finished with value: 0.9492282597810262 and parameters: {'weight_lgbm_class_0': 0.14544341401176292, 'weight_lgbm_class_1': 0.9954856832624218, 'weight_lgbm_class_2': 0.25420886619273275, 'weight_xgb_class_0': 0.003862163668029674, 'weight_xgb_class_1': 0.7498728661165481, 'weight_xgb_class_2': 0.8364421745943954}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:43,050] Trial 480 finished with value: 0.94919117031634 and parameters: {'weight_lgbm_class_0': 0.14353101203803642, 'weight_lgbm_class_1': 0.9967378507964079, 'weight_lgbm_class_2': 0.19272997725437355, 'weight_xgb_class_0': 0.0017271732059083397, 'weight_xgb_class_1': 0.7582739289635103, 'weight_xgb_class_2': 0.8420532071473871}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:43,053] Trial 481 finished with value: 0.9495981447670104 and parameters: {'weight_lgbm_class_0': 0.1312385323477418, 'weight_lgbm_class_1': 0.9958251726446532, 'weight_lgbm_class_2': 0.23408122151786706, 'weight_xgb_class_0': 0.0024705639739999764, 'weight_xgb_class_1': 0.7436862594015704, 'weight_xgb_class_2': 0.8387952608999112}. Best is trial 358 with value: 0.9497927483550862.

[I 2026-07-05 15:31:43,056] Trial 482 finished with value: 0.9493548078569026 and parameters: {'weight_lgbm_class_0': 0.1467680785036591, 'weight_lgbm_class_1': 0.9830766243073729, 'weight_lgbm_class_2': 0.25539325787985173, 'weight_xgb_class_0': 0.00025757778934871935, 'weight_xgb_class_1': 0.7743026067578143, 'weight_xgb_class_2': 0.846712115926652}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:43,099] Trial 483 finished with value: 0.9490761775683169 and parameters: {'weight_lgbm_class_0': 0.15047597774506724, 'weight_lgbm_class_1': 0.9998770841622979, 'weight_lgbm_class_2': 0.19979299780791604, 'weight_xgb_class_0': 0.0011770165738254359, 'weight_xgb_class_1': 0.7489535897932855, 'weight_xgb_class_2': 0.8469463182374226}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:43,150] Trial 484 finished with value: 0.9493586370705932 and parameters: {'weight_lgbm_class_0': 0.1457521275027656, 'weight_lgbm_class_1': 0.9990304451597609, 'weight_lgbm_class_2': 0.25917426887091605, 'weight_xgb_class_0': 0.0014266648133696852, 'weight_xgb_class_1': 0.7388940998066906, 'weight_xgb_class_2': 0.8403922356779233}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:43,156] Trial 485 finished with value: 0.9492103718382457 and parameters: {'weight_lgbm_class_0': 0.14942617051929888, 'weight_lgbm_class_1': 0.9828228834932566, 'weight_lgbm_class_2': 0.24353929194178, 'weight_xgb_class_0': 0.00032589238934543907, 'weight_xgb_class_1': 0.766392664011475, 'weight_xgb_class_2': 0.8294383057518859}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:43,187] Trial 487 finished with value: 0.94917891538613 and parameters: {'weight_lgbm_class_0': 0.15080349709039564, 'weight_lgbm_class_1': 0.9800990866125632, 'weight_lgbm_class_2': 0.24379101355833616, 'weight_xgb_class_0': 6.788121298306315e-05, 'weight_xgb_class_1': 0.7824034882371939, 'weight_xgb_class_2': 0.8294687412286209}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:43,190] Trial 486 finished with value: 0.949715319537025 and parameters: {'weight_lgbm_class_0': 0.1201654465278683, 'weight_lgbm_class_1': 0.9865388565548069, 'weight_lgbm_class_2': 0.23889490743708747, 'weight_xgb_class_0': 0.0014398020374129946, 'weight_xgb_class_1': 0.7613620406922693, 'weight_xgb_class_2': 0.8320134283656277}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:43,237] Trial 489 finished with value: 0.9491699870109341 and parameters: {'weight_lgbm_class_0': 0.12340459660057544, 'weight_lgbm_class_1': 0.9785624565846124, 'weight_lgbm_class_2': 0.17450877460087866, 'weight_xgb_class_0': 0.01716506060130749, 'weight_xgb_class_1': 0.7540147418836594, 'weight_xgb_class_2': 0.8170201910028467}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:43,256] Trial 488 finished with value: 0.9490321825269855 and parameters: {'weight_lgbm_class_0': 0.15299710608901118, 'weight_lgbm_class_1': 0.9882417387751992, 'weight_lgbm_class_2': 0.18573062338630683, 'weight_xgb_class_0': 0.001088636082823436, 'weight_xgb_class_1': 0.7770298957696161, 'weight_xgb_class_2': 0.8308507752741533}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:43,277] Trial 490 finished with value: 0.9493737774339456 and parameters: {'weight_lgbm_class_0': 0.12754787535404402, 'weight_lgbm_class_1': 0.9367297968056062, 'weight_lgbm_class_2': 0.29519933339206944, 'weight_xgb_class_0': 0.02054348228301452, 'weight_xgb_class_1': 0.7609629368010633, 'weight_xgb_class_2': 0.8361927692576414}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  25%|████████████████████████████████▊                                                                                                   | 497/2000 [00:12<00:42, 35.54it/s]

[I 2026-07-05 15:31:43,292] Trial 491 finished with value: 0.9497178248426587 and parameters: {'weight_lgbm_class_0': 0.12671249265872475, 'weight_lgbm_class_1': 0.9781856089778524, 'weight_lgbm_class_2': 0.29425097283549384, 'weight_xgb_class_0': 0.00031762516047633554, 'weight_xgb_class_1': 0.7591223198650732, 'weight_xgb_class_2': 0.8276087781995076}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:43,339] Trial 492 finished with value: 0.9492681115719325 and parameters: {'weight_lgbm_class_0': 0.11713625406973538, 'weight_lgbm_class_1': 0.9414971160470346, 'weight_lgbm_class_2': 0.20746431534116652, 'weight_xgb_class_0': 0.021767474089380352, 'weight_xgb_class_1': 0.8164083087397239, 'weight_xgb_class_2': 0.8209762420804207}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:43,374] Trial 493 finished with value: 0.943860998077775 and parameters: {'weight_lgbm_class_0': 0.11597151957033434, 'weight_lgbm_class_1': 0.9421202411801878, 'weight_lgbm_class_2': 0.29463977035381556, 'weight_xgb_class_0': 0.024862691267971526, 'weight_xgb_class_1': 0.7697035453032953, 'weight_xgb_class_2': 0.1453217752974803}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:43,382] Trial 494 finished with value: 0.9496313450438961 and parameters: {'weight_lgbm_class_0': 0.11682249197400368, 'weight_lgbm_class_1': 0.9381360905026159, 'weight_lgbm_class_2': 0.29254706716713563, 'weight_xgb_class_0': 0.01954201967368616, 'weight_xgb_class_1': 0.7688986108068865, 'weight_xgb_class_2': 0.8304510618651445}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:43,389] Trial 495 finished with value: 0.9495158965633177 and parameters: {'weight_lgbm_class_0': 0.12024600279693214, 'weight_lgbm_class_1': 0.942592445110537, 'weight_lgbm_class_2': 0.2994460525654588, 'weight_xgb_class_0': 0.020744378896085852, 'weight_xgb_class_1': 0.8167551924286739, 'weight_xgb_class_2': 0.8240960389315762}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:43,469] Trial 496 finished with value: 0.9495894193160503 and parameters: {'weight_lgbm_class_0': 0.11996841480762623, 'weight_lgbm_class_1': 0.9376000503678877, 'weight_lgbm_class_2': 0.3574354330304108, 'weight_xgb_class_0': 0.02339716175535056, 'weight_xgb_class_1': 0.8201361129597301, 'weight_xgb_class_2': 0.8130316958827005}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:43,481] Trial 497 finished with value: 0.9496469690373809 and parameters: {'weight_lgbm_class_0': 0.11394849585950724, 'weight_lgbm_class_1': 0.9391809225461015, 'weight_lgbm_class_2': 0.28650605346821434, 'weight_xgb_class_0': 0.02374233792135639, 'weight_xgb_class_1': 0.8254702110710442, 'weight_xgb_class_2': 0.8623344279292068}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  25%|█████████████████████████████████▍                                                                                                  | 507/2000 [00:12<00:39, 38.13it/s]

[I 2026-07-05 15:31:43,516] Trial 498 finished with value: 0.9496491636010912 and parameters: {'weight_lgbm_class_0': 0.11673991913108454, 'weight_lgbm_class_1': 0.9317103930561289, 'weight_lgbm_class_2': 0.29865576103286534, 'weight_xgb_class_0': 0.023070703981971946, 'weight_xgb_class_1': 0.8124109658685715, 'weight_xgb_class_2': 0.862148621546737}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:43,527] Trial 499 finished with value: 0.9495956809493848 and parameters: {'weight_lgbm_class_0': 0.11611083568936102, 'weight_lgbm_class_1': 0.9288997763742111, 'weight_lgbm_class_2': 0.2972551183902445, 'weight_xgb_class_0': 0.02588078208819272, 'weight_xgb_class_1': 0.8161821185119226, 'weight_xgb_class_2': 0.859764985868531}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:43,529] Trial 500 finished with value: 0.9485087374626263 and parameters: {'weight_lgbm_class_0': 0.11854733012325562, 'weight_lgbm_class_1': 0.9387629873115588, 'weight_lgbm_class_2': 0.2934214769917475, 'weight_xgb_class_0': 0.023572484600282072, 'weight_xgb_class_1': 0.8129226719862135, 'weight_xgb_class_2': 0.48072236301046284}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:43,556] Trial 502 finished with value: 0.9496741063234158 and parameters: {'weight_lgbm_class_0': 0.11230843436602667, 'weight_lgbm_class_1': 0.9392716162978969, 'weight_lgbm_class_2': 0.33216985236687885, 'weight_xgb_class_0': 0.022925381825248784, 'weight_xgb_class_1': 0.8238049791510407, 'weight_xgb_class_2': 0.8644437489780379}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:43,588] Trial 501 finished with value: 0.9496805699968419 and parameters: {'weight_lgbm_class_0': 0.10071972580675335, 'weight_lgbm_class_1': 0.936608614190263, 'weight_lgbm_class_2': 0.32632220703335696, 'weight_xgb_class_0': 0.02911956432761601, 'weight_xgb_class_1': 0.8099864145069859, 'weight_xgb_class_2': 0.8586594764111314}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:43,589] Trial 503 finished with value: 0.9497005919534683 and parameters: {'weight_lgbm_class_0': 0.11168930626570535, 'weight_lgbm_class_1': 0.9440644322698559, 'weight_lgbm_class_2': 0.3540995349624305, 'weight_xgb_class_0': 0.02315902459383808, 'weight_xgb_class_1': 0.8335268717157873, 'weight_xgb_class_2': 0.8634768824235405}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:43,625] Trial 504 finished with value: 0.9497286350942188 and parameters: {'weight_lgbm_class_0': 0.09498337402906752, 'weight_lgbm_class_1': 0.9376785003458351, 'weight_lgbm_class_2': 0.3647166823847531, 'weight_xgb_class_0': 0.023429610414246148, 'weight_xgb_class_1': 0.8212313616052689, 'weight_xgb_class_2': 0.8630962554212198}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:43,692] Trial 505 finished with value: 0.9100952100868008 and parameters: {'weight_lgbm_class_0': 0.8468465992598249, 'weight_lgbm_class_1': 0.9057958838336837, 'weight_lgbm_class_2': 0.3620512698536773, 'weight_xgb_class_0': 0.025952933328301564, 'weight_xgb_class_1': 0.8283872300499213, 'weight_xgb_class_2': 0.866907469265575}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:43,702] Trial 506 finished with value: 0.9497270621171521 and parameters: {'weight_lgbm_class_0': 0.09111442905941117, 'weight_lgbm_class_1': 0.9074345290836048, 'weight_lgbm_class_2': 0.35575258664689546, 'weight_xgb_class_0': 0.026728789493916917, 'weight_xgb_class_1': 0.8339162016572393, 'weight_xgb_class_2': 0.8633944353443969}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:43,707] Trial 507 finished with value: 0.9497279580541226 and parameters: {'weight_lgbm_class_0': 0.09303250921253783, 'weight_lgbm_class_1': 0.9117385791305599, 'weight_lgbm_class_2': 0.35995793717948005, 'weight_xgb_class_0': 0.026678729953285556, 'weight_xgb_class_1': 0.8305155358180148, 'weight_xgb_class_2': 0.8651314356069942}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  26%|██████████████████████████████████                                                                                                  | 516/2000 [00:12<00:37, 39.68it/s]

[I 2026-07-05 15:31:43,777] Trial 508 finished with value: 0.949691294252653 and parameters: {'weight_lgbm_class_0': 0.0936576158445559, 'weight_lgbm_class_1': 0.9140300163618238, 'weight_lgbm_class_2': 0.35836022964231795, 'weight_xgb_class_0': 0.035204855570177704, 'weight_xgb_class_1': 0.8382304786990865, 'weight_xgb_class_2': 0.8701570574855998}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:43,787] Trial 509 finished with value: 0.9497481049525837 and parameters: {'weight_lgbm_class_0': 0.09369639837378652, 'weight_lgbm_class_1': 0.9097951915153325, 'weight_lgbm_class_2': 0.3562710398444937, 'weight_xgb_class_0': 0.02499091756049013, 'weight_xgb_class_1': 0.8385782268619765, 'weight_xgb_class_2': 0.8609688433067102}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:43,788] Trial 510 finished with value: 0.9479195871790026 and parameters: {'weight_lgbm_class_0': 0.17927020282700196, 'weight_lgbm_class_1': 0.9098452081985751, 'weight_lgbm_class_2': 0.3547887443167468, 'weight_xgb_class_0': 0.03206846422582547, 'weight_xgb_class_1': 0.44138909691390177, 'weight_xgb_class_2': 0.8666699689334915}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:43,805] Trial 511 finished with value: 0.9497199908920116 and parameters: {'weight_lgbm_class_0': 0.09439659473035737, 'weight_lgbm_class_1': 0.8753422298090732, 'weight_lgbm_class_2': 0.3632863925812746, 'weight_xgb_class_0': 0.03174652225403546, 'weight_xgb_class_1': 0.839423386006496, 'weight_xgb_class_2': 0.8707141415183585}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:43,838] Trial 512 finished with value: 0.9496892779819531 and parameters: {'weight_lgbm_class_0': 0.0937583333401802, 'weight_lgbm_class_1': 0.9072611506733813, 'weight_lgbm_class_2': 0.3242669834922018, 'weight_xgb_class_0': 0.03844002001482913, 'weight_xgb_class_1': 0.8405864620303539, 'weight_xgb_class_2': 0.8697523339304074}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:43,866] Trial 514 finished with value: 0.9495132998575988 and parameters: {'weight_lgbm_class_0': 0.05127255587119968, 'weight_lgbm_class_1': 0.9630584075351223, 'weight_lgbm_class_2': 0.36252644199918616, 'weight_xgb_class_0': 0.03620950146399312, 'weight_xgb_class_1': 0.8376570693548536, 'weight_xgb_class_2': 0.8716160145843456}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:43,886] Trial 513 finished with value: 0.9495983974112274 and parameters: {'weight_lgbm_class_0': 0.05526828434816518, 'weight_lgbm_class_1': 0.9081123553395525, 'weight_lgbm_class_2': 0.3587072624714879, 'weight_xgb_class_0': 0.03539953997325747, 'weight_xgb_class_1': 0.8389026559260652, 'weight_xgb_class_2': 0.8755393125561535}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:43,925] Trial 515 finished with value: 0.9484475171371272 and parameters: {'weight_lgbm_class_0': 0.17225167534516506, 'weight_lgbm_class_1': 0.9630895423614667, 'weight_lgbm_class_2': 0.36818884153636616, 'weight_xgb_class_0': 0.038479465249725814, 'weight_xgb_class_1': 0.7937853333026667, 'weight_xgb_class_2': 0.8734317627409949}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:43,945] Trial 516 finished with value: 0.9496511690573352 and parameters: {'weight_lgbm_class_0': 0.08857072825422523, 'weight_lgbm_class_1': 0.9680846145106912, 'weight_lgbm_class_2': 0.36295605160110056, 'weight_xgb_class_0': 0.030993959671223988, 'weight_xgb_class_1': 0.44528101100088613, 'weight_xgb_class_2': 0.8737005398107307}. Best is trial 358 with value: 0.9497927483550862.

[I 2026-07-05 15:31:43,997] Trial 517 finished with value: 0.9494543639385178 and parameters: {'weight_lgbm_class_0': 0.048226795786177876, 'weight_lgbm_class_1': 0.9031562721308367, 'weight_lgbm_class_2': 0.36242379925899226, 'weight_xgb_class_0': 0.031504745327034595, 'weight_xgb_class_1': 0.7944055144668324, 'weight_xgb_class_2': 0.8804058073186519}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:43,997] Trial 518 finished with value: 0.9497575713500863 and parameters: {'weight_lgbm_class_0': 0.08497502915101515, 'weight_lgbm_class_1': 0.876737111471859, 'weight_lgbm_class_2': 0.38900834082975977, 'weight_xgb_class_0': 0.018467516131989443, 'weight_xgb_class_1': 0.7927151407147258, 'weight_xgb_class_2': 0.8725455448660223}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:44,000] Trial 519 finished with value: 0.9492227298193328 and parameters: {'weight_lgbm_class_0': 0.05353014475123886, 'weight_lgbm_class_1': 0.8740340594075429, 'weight_lgbm_class_2': 0.3794261807717379, 'weight_xgb_class_0': 0.020331993838179338, 'weight_xgb_class_1': 0.7977796596389686, 'weight_xgb_class_2': 0.8726779059868065}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:44,080] Trial 520 finished with value: 0.9490989791326303 and parameters: {'weight_lgbm_class_0': 0.05157017121632247, 'weight_lgbm_class_1': 0.8745714978419906, 'weight_lgbm_class_2': 0.3801476488300753, 'weight_xgb_class_0': 0.018655026325062447, 'weight_xgb_class_1': 0.7972476549140545, 'weight_xgb_class_2': 0.8790470249847174}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:44,091] Trial 521 finished with value: 0.949226667529262 and parameters: {'weight_lgbm_class_0': 0.05663958571408538, 'weight_lgbm_class_1': 0.8689958891680118, 'weight_lgbm_class_2': 0.3910840683808793, 'weight_xgb_class_0': 0.016888498682389425, 'weight_xgb_class_1': 0.8013627178099278, 'weight_xgb_class_2': 0.8541876488769836}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:44,126] Trial 522 finished with value: 0.9497437520729375 and parameters: {'weight_lgbm_class_0': 0.07757340610642165, 'weight_lgbm_class_1': 0.8784184255919869, 'weight_lgbm_class_2': 0.390077170840085, 'weight_xgb_class_0': 0.020623279077547848, 'weight_xgb_class_1': 0.7962924287120827, 'weight_xgb_class_2': 0.8072732657011487}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:44,162] Trial 523 finished with value: 0.949186750462241 and parameters: {'weight_lgbm_class_0': 0.05535693888247056, 'weight_lgbm_class_1': 0.8862358813631485, 'weight_lgbm_class_2': 0.3919695967845351, 'weight_xgb_class_0': 0.017298140646739867, 'weight_xgb_class_1': 0.7936922358930815, 'weight_xgb_class_2': 0.8496646201913213}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:44,164] Trial 524 finished with value: 0.9493575454085409 and parameters: {'weight_lgbm_class_0': 0.05772432357751919, 'weight_lgbm_class_1': 0.877195261009521, 'weight_lgbm_class_2': 0.3875652653026691, 'weight_xgb_class_0': 0.017866532008279007, 'weight_xgb_class_1': 0.7876640859855878, 'weight_xgb_class_2': 0.8066404799157706}. Best is trial 358 with value: 0.9497927483550862.

[I 2026-07-05 15:31:44,199] Trial 525 finished with value: 0.9493173478745284 and parameters: {'weight_lgbm_class_0': 0.0570559387948732, 'weight_lgbm_class_1': 0.8735686520174533, 'weight_lgbm_class_2': 0.3858246004253213, 'weight_xgb_class_0': 0.017342756692895533, 'weight_xgb_class_1': 0.7969872151051328, 'weight_xgb_class_2': 0.812548673826095}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:44,204] Trial 526 finished with value: 0.9496201067522302 and parameters: {'weight_lgbm_class_0': 0.06770974433468763, 'weight_lgbm_class_1': 0.8815210940683175, 'weight_lgbm_class_2': 0.3903483838038909, 'weight_xgb_class_0': 0.01775563843987365, 'weight_xgb_class_1': 0.795381521168129, 'weight_xgb_class_2': 0.8075062017195166}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:44,221] Trial 527 finished with value: 0.9492826428831119 and parameters: {'weight_lgbm_class_0': 0.058148214054809036, 'weight_lgbm_class_1': 0.881943755369007, 'weight_lgbm_class_2': 0.38460826855984986, 'weight_xgb_class_0': 0.015004800515885153, 'weight_xgb_class_1': 0.7885621976031291, 'weight_xgb_class_2': 0.8054652406519227}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:44,245] Trial 528 finished with value: 0.9493645943798107 and parameters: {'weight_lgbm_class_0': 0.058873004403940145, 'weight_lgbm_class_1': 0.8714524675531017, 'weight_lgbm_class_2': 0.3956629631304117, 'weight_xgb_class_0': 0.016982357568765226, 'weight_xgb_class_1': 0.793020938504058, 'weight_xgb_class_2': 0.8074746246816348}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:44,286] Trial 529 finished with value: 0.9496416081420702 and parameters: {'weight_lgbm_class_0': 0.0711750731810873, 'weight_lgbm_class_1': 0.8820556841911158, 'weight_lgbm_class_2': 0.3901773953783836, 'weight_xgb_class_0': 0.01765684021186871, 'weight_xgb_class_1': 0.7920333473039052, 'weight_xgb_class_2': 0.8020288389848208}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:44,327] Trial 530 finished with value: 0.9496294512763704 and parameters: {'weight_lgbm_class_0': 0.07257063174642221, 'weight_lgbm_class_1': 0.8736361689307146, 'weight_lgbm_class_2': 0.3918685487858562, 'weight_xgb_class_0': 0.017718351710478118, 'weight_xgb_class_1': 0.7922326679316368, 'weight_xgb_class_2': 0.812315163274404}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:44,343] Trial 532 finished with value: 0.9426055111925994 and parameters: {'weight_lgbm_class_0': 0.3429256375994475, 'weight_lgbm_class_1': 0.884677664896872, 'weight_lgbm_class_2': 0.3372242406218739, 'weight_xgb_class_0': 0.001594219520820834, 'weight_xgb_class_1': 0.7912186744109072, 'weight_xgb_class_2': 0.7992405296144468}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:44,370] Trial 531 finished with value: 0.9493931611865166 and parameters: {'weight_lgbm_class_0': 0.07421535200298637, 'weight_lgbm_class_1': 0.8787981162319136, 'weight_lgbm_class_2': 0.3317904891718606, 'weight_xgb_class_0': 0.0010494164177699541, 'weight_xgb_class_1': 0.7818174610712753, 'weight_xgb_class_2': 0.8108800994862145}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:44,377] Trial 533 finished with value: 0.9496106223748954 and parameters: {'weight_lgbm_class_0': 0.07712634635402257, 'weight_lgbm_class_1': 0.8821033635880927, 'weight_lgbm_class_2': 0.3855759662502257, 'weight_xgb_class_0': 0.015560753122917673, 'weight_xgb_class_1': 0.7908590226077994, 'weight_xgb_class_2': 0.8071562421098984}. Best is trial 358 with value: 0.9497927483550862.

[I 2026-07-05 15:31:44,401] Trial 534 finished with value: 0.9495002365204037 and parameters: {'weight_lgbm_class_0': 0.0792236562111814, 'weight_lgbm_class_1': 0.8833713082494921, 'weight_lgbm_class_2': 0.390023231949411, 'weight_xgb_class_0': 0.0012949866236709809, 'weight_xgb_class_1': 0.7814697108207169, 'weight_xgb_class_2': 0.7866873306849879}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:44,475] Trial 535 finished with value: 0.9433194584445991 and parameters: {'weight_lgbm_class_0': 0.33549472413464343, 'weight_lgbm_class_1': 0.8709437808996211, 'weight_lgbm_class_2': 0.39720313804689716, 'weight_xgb_class_0': 0.0011562449803017676, 'weight_xgb_class_1': 0.7725345615784222, 'weight_xgb_class_2': 0.7857261407568057}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:44,489] Trial 536 finished with value: 0.9493890830066128 and parameters: {'weight_lgbm_class_0': 0.07323980266255764, 'weight_lgbm_class_1': 0.8854319308920326, 'weight_lgbm_class_2': 0.33901743545942836, 'weight_xgb_class_0': 0.0022952083232834126, 'weight_xgb_class_1': 0.8065760962268581, 'weight_xgb_class_2': 0.7815148084043799}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:44,533] Trial 537 finished with value: 0.949549535317821 and parameters: {'weight_lgbm_class_0': 0.0801113415594649, 'weight_lgbm_class_1': 0.916534856331412, 'weight_lgbm_class_2': 0.33525126223008783, 'weight_xgb_class_0': 0.0003772408060066061, 'weight_xgb_class_1': 0.7759267916224147, 'weight_xgb_class_2': 0.7977605609465197}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:44,552] Trial 538 finished with value: 0.9494622571326149 and parameters: {'weight_lgbm_class_0': 0.07751018388149018, 'weight_lgbm_class_1': 0.917240951044386, 'weight_lgbm_class_2': 0.3357503494122549, 'weight_xgb_class_0': 4.785192895798065e-05, 'weight_xgb_class_1': 0.7778407544087518, 'weight_xgb_class_2': 0.7887824887755142}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:44,559] Trial 539 finished with value: 0.9491797404988277 and parameters: {'weight_lgbm_class_0': 0.0703484690931912, 'weight_lgbm_class_1': 0.9159341469879149, 'weight_lgbm_class_2': 0.3350081513797655, 'weight_xgb_class_0': 0.0009340767410449639, 'weight_xgb_class_1': 0.7729375792998489, 'weight_xgb_class_2': 0.9006446735004027}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:44,579] Trial 540 finished with value: 0.949492651999265 and parameters: {'weight_lgbm_class_0': 0.07654020925706348, 'weight_lgbm_class_1': 0.9184475686631746, 'weight_lgbm_class_2': 0.340409114198803, 'weight_xgb_class_0': 0.0005031639700854781, 'weight_xgb_class_1': 0.7155206840690884, 'weight_xgb_class_2': 0.7654006455345299}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  27%|████████████████████████████████████▏                                                                                               | 548/2000 [00:13<00:39, 37.15it/s]

[I 2026-07-05 15:31:44,586] Trial 541 finished with value: 0.9496134996841796 and parameters: {'weight_lgbm_class_0': 0.08197846253641947, 'weight_lgbm_class_1': 0.9184354386570834, 'weight_lgbm_class_2': 0.3375436629082302, 'weight_xgb_class_0': 0.007221095704260121, 'weight_xgb_class_1': 0.8126432622524766, 'weight_xgb_class_2': 0.8982761472800791}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:44,638] Trial 542 finished with value: 0.9495741869768582 and parameters: {'weight_lgbm_class_0': 0.08192806269159303, 'weight_lgbm_class_1': 0.9229885872301473, 'weight_lgbm_class_2': 0.33593434696676483, 'weight_xgb_class_0': 0.00038926763960940385, 'weight_xgb_class_1': 0.8143086386012558, 'weight_xgb_class_2': 0.7865469606880882}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:44,655] Trial 543 finished with value: 0.9495647404843305 and parameters: {'weight_lgbm_class_0': 0.08391086266504516, 'weight_lgbm_class_1': 0.9171605963637312, 'weight_lgbm_class_2': 0.3380525281517605, 'weight_xgb_class_0': 0.00572682519075482, 'weight_xgb_class_1': 0.8103413136443944, 'weight_xgb_class_2': 0.8472722423552543}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:44,668] Trial 545 finished with value: 0.9496560227245726 and parameters: {'weight_lgbm_class_0': 0.09057961740840413, 'weight_lgbm_class_1': 0.9132847756948629, 'weight_lgbm_class_2': 0.3198832039129875, 'weight_xgb_class_0': 0.044969937424595915, 'weight_xgb_class_1': 0.8122972771618627, 'weight_xgb_class_2': 0.9005556715798441}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:44,707] Trial 544 finished with value: 0.9496022111995748 and parameters: {'weight_lgbm_class_0': 0.08772811520098764, 'weight_lgbm_class_1': 0.9186592156370744, 'weight_lgbm_class_2': 0.2697658886287769, 'weight_xgb_class_0': 0.0013307243954153803, 'weight_xgb_class_1': 0.8139614815605956, 'weight_xgb_class_2': 0.9041566836598397}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:44,708] Trial 546 finished with value: 0.9493594185340962 and parameters: {'weight_lgbm_class_0': 0.08784716688341188, 'weight_lgbm_class_1': 0.11969519213321028, 'weight_lgbm_class_2': 0.2734972116740356, 'weight_xgb_class_0': 0.0024507644696939064, 'weight_xgb_class_1': 0.8137164994557338, 'weight_xgb_class_2': 0.8942475900191599}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:44,786] Trial 547 finished with value: 0.9495905068744159 and parameters: {'weight_lgbm_class_0': 0.09354587107073457, 'weight_lgbm_class_1': 0.9145676910634046, 'weight_lgbm_class_2': 0.2717743219737651, 'weight_xgb_class_0': 0.00012180322491519408, 'weight_xgb_class_1': 0.8154400307698059, 'weight_xgb_class_2': 0.8997170237977579}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:44,791] Trial 548 finished with value: 0.9496557550922625 and parameters: {'weight_lgbm_class_0': 0.09219753409082398, 'weight_lgbm_class_1': 0.9147229765660155, 'weight_lgbm_class_2': 0.11439785445698764, 'weight_xgb_class_0': 0.0005396215147488374, 'weight_xgb_class_1': 0.8769738399785157, 'weight_xgb_class_2': 0.8970469219742616}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  28%|████████████████████████████████████▊                                                                                               | 558/2000 [00:13<00:36, 39.08it/s]

[I 2026-07-05 15:31:44,858] Trial 549 finished with value: 0.9213795365488181 and parameters: {'weight_lgbm_class_0': 0.6642445743007079, 'weight_lgbm_class_1': 0.9659817710892018, 'weight_lgbm_class_2': 0.3146000594201901, 'weight_xgb_class_0': 0.04517357671851391, 'weight_xgb_class_1': 0.8754729960837787, 'weight_xgb_class_2': 0.8965805702706832}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:44,874] Trial 550 finished with value: 0.9496172158061714 and parameters: {'weight_lgbm_class_0': 0.09757999422578842, 'weight_lgbm_class_1': 0.9657378932668645, 'weight_lgbm_class_2': 0.31458116890318644, 'weight_xgb_class_0': 0.04371471514131619, 'weight_xgb_class_1': 0.7182249023864178, 'weight_xgb_class_2': 0.8460256009067487}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:44,905] Trial 551 finished with value: 0.9493950805847747 and parameters: {'weight_lgbm_class_0': 0.09919819462256274, 'weight_lgbm_class_1': 0.9638901382354492, 'weight_lgbm_class_2': 0.27095916924136154, 'weight_xgb_class_0': 0.0458734601889073, 'weight_xgb_class_1': 0.8713877890763483, 'weight_xgb_class_2': 0.8484527686774369}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:44,908] Trial 552 finished with value: 0.9495186606911382 and parameters: {'weight_lgbm_class_0': 0.09971249339592275, 'weight_lgbm_class_1': 0.9620063422629103, 'weight_lgbm_class_2': 0.27521395234522866, 'weight_xgb_class_0': 0.043714081888312134, 'weight_xgb_class_1': 0.8814126142136877, 'weight_xgb_class_2': 0.8535697923300919}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:44,926] Trial 553 finished with value: 0.9066478327060402 and parameters: {'weight_lgbm_class_0': 0.6710853697474412, 'weight_lgbm_class_1': 0.1923389829236703, 'weight_lgbm_class_2': 0.26295255481154556, 'weight_xgb_class_0': 0.042023883350572916, 'weight_xgb_class_1': 0.8818805931494899, 'weight_xgb_class_2': 0.8484005246560347}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:44,959] Trial 554 finished with value: 0.948820755082492 and parameters: {'weight_lgbm_class_0': 0.13641379590789166, 'weight_lgbm_class_1': 0.9622600402549392, 'weight_lgbm_class_2': 0.27374280625792535, 'weight_xgb_class_0': 0.049537281614234256, 'weight_xgb_class_1': 0.8787535511877074, 'weight_xgb_class_2': 0.8926615686589751}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:44,985] Trial 555 finished with value: 0.8992471904301326 and parameters: {'weight_lgbm_class_0': 0.1357633125298113, 'weight_lgbm_class_1': 0.9630377294769953, 'weight_lgbm_class_2': 0.2734862392027446, 'weight_xgb_class_0': 0.8846116055021432, 'weight_xgb_class_1': 0.8687357285115209, 'weight_xgb_class_2': 0.846979730539758}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:45,007] Trial 556 finished with value: 0.9485396021252205 and parameters: {'weight_lgbm_class_0': 0.15911374214076787, 'weight_lgbm_class_1': 0.9605431634022803, 'weight_lgbm_class_2': 0.3189395567514679, 'weight_xgb_class_0': 0.04437401105075009, 'weight_xgb_class_1': 0.8761952603624555, 'weight_xgb_class_2': 0.8515754268980756}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:45,043] Trial 557 finished with value: 0.9466491973141054 and parameters: {'weight_lgbm_class_0': 0.1339319332839851, 'weight_lgbm_class_1': 0.9647840807114817, 'weight_lgbm_class_2': 0.30706997496854643, 'weight_xgb_class_0': 0.03744891834118485, 'weight_xgb_class_1': 0.8434266771081571, 'weight_xgb_class_2': 0.3878512096970764}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:45,046] Trial 558 finished with value: 0.9488892176815756 and parameters: {'weight_lgbm_class_0': 0.13785286974013894, 'weight_lgbm_class_1': 0.9672797210876798, 'weight_lgbm_class_2': 0.3076409987554432, 'weight_xgb_class_0': 0.04086690559086914, 'weight_xgb_class_1': 0.8813598767516319, 'weight_xgb_class_2': 0.8447986811988}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  28%|█████████████████████████████████████▍                                                                                              | 567/2000 [00:13<00:37, 38.44it/s]

[I 2026-07-05 15:31:45,114] Trial 559 finished with value: 0.947942626025891 and parameters: {'weight_lgbm_class_0': 0.13073566496028619, 'weight_lgbm_class_1': 0.9628286531420166, 'weight_lgbm_class_2': 0.30880627737553173, 'weight_xgb_class_0': 0.043468323583396445, 'weight_xgb_class_1': 0.09251821737345106, 'weight_xgb_class_2': 0.8420100310215086}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:45,119] Trial 560 finished with value: 0.9488928689106456 and parameters: {'weight_lgbm_class_0': 0.13584175081287458, 'weight_lgbm_class_1': 0.9618209523323991, 'weight_lgbm_class_2': 0.308373943076565, 'weight_xgb_class_0': 0.04132072111397443, 'weight_xgb_class_1': 0.8597165886298668, 'weight_xgb_class_2': 0.8327331522032061}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:45,165] Trial 561 finished with value: 0.9489909285039193 and parameters: {'weight_lgbm_class_0': 0.13281767238526998, 'weight_lgbm_class_1': 0.9618723474673581, 'weight_lgbm_class_2': 0.30903992424569937, 'weight_xgb_class_0': 0.04000975450233472, 'weight_xgb_class_1': 0.8478003092082912, 'weight_xgb_class_2': 0.8435049404663393}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:45,193] Trial 562 finished with value: 0.9486251255399449 and parameters: {'weight_lgbm_class_0': 0.13969291749646037, 'weight_lgbm_class_1': 0.9582419659563267, 'weight_lgbm_class_2': 0.21970913952720592, 'weight_xgb_class_0': 0.03772501767264612, 'weight_xgb_class_1': 0.8520303801993763, 'weight_xgb_class_2': 0.8272638415306863}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:45,210] Trial 563 finished with value: 0.9469012526077409 and parameters: {'weight_lgbm_class_0': 0.13595406085089518, 'weight_lgbm_class_1': 0.9821158502405564, 'weight_lgbm_class_2': 0.0045789449288793915, 'weight_xgb_class_0': 0.06563140850771063, 'weight_xgb_class_1': 0.8581994359633621, 'weight_xgb_class_2': 0.829251001879223}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:45,239] Trial 564 finished with value: 0.9486477723059265 and parameters: {'weight_lgbm_class_0': 0.13498023636225923, 'weight_lgbm_class_1': 0.9767092790552002, 'weight_lgbm_class_2': 0.3713751505855449, 'weight_xgb_class_0': 0.06226326238912219, 'weight_xgb_class_1': 0.8481194908986739, 'weight_xgb_class_2': 0.8244006418379296}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:45,258] Trial 565 finished with value: 0.9487218497731805 and parameters: {'weight_lgbm_class_0': 0.16678591254148245, 'weight_lgbm_class_1': 0.9804132539612712, 'weight_lgbm_class_2': 0.36631248607524086, 'weight_xgb_class_0': 0.02539048639094085, 'weight_xgb_class_1': 0.8456442667160591, 'weight_xgb_class_2': 0.8302789618234716}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:45,286] Trial 567 finished with value: 0.949302551727294 and parameters: {'weight_lgbm_class_0': 0.13492541987487885, 'weight_lgbm_class_1': 0.98011713574667, 'weight_lgbm_class_2': 0.36619436292661717, 'weight_xgb_class_0': 0.026002801094173366, 'weight_xgb_class_1': 0.8426901853931461, 'weight_xgb_class_2': 0.827479180557182}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:45,300] Trial 566 finished with value: 0.9480918369939141 and parameters: {'weight_lgbm_class_0': 0.16369833225853658, 'weight_lgbm_class_1': 0.9813443723204035, 'weight_lgbm_class_2': 0.37377573758602595, 'weight_xgb_class_0': 0.0646558881083899, 'weight_xgb_class_1': 0.8469066268453728, 'weight_xgb_class_2': 0.8304125250329034}. Best is trial 358 with value: 0.9497927483550862.

[I 2026-07-05 15:31:45,343] Trial 569 finished with value: 0.9476532451278582 and parameters: {'weight_lgbm_class_0': 0.1756229429543578, 'weight_lgbm_class_1': 0.9848724400953236, 'weight_lgbm_class_2': 0.3698274088169802, 'weight_xgb_class_0': 0.06991748432664383, 'weight_xgb_class_1': 0.8518979585788984, 'weight_xgb_class_2': 0.8285893966947149}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:45,345] Trial 568 finished with value: 0.9486218777819918 and parameters: {'weight_lgbm_class_0': 0.13608751783407325, 'weight_lgbm_class_1': 0.9963025521755913, 'weight_lgbm_class_2': 0.3653413811560711, 'weight_xgb_class_0': 0.06200584039651894, 'weight_xgb_class_1': 0.8515514007171134, 'weight_xgb_class_2': 0.8257419434440094}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:45,378] Trial 570 finished with value: 0.9476130399839707 and parameters: {'weight_lgbm_class_0': 0.18269702274854405, 'weight_lgbm_class_1': 0.9988332183299874, 'weight_lgbm_class_2': 0.36343009800258275, 'weight_xgb_class_0': 0.06214074990105238, 'weight_xgb_class_1': 0.8454384672621632, 'weight_xgb_class_2': 0.8207687427110412}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:45,428] Trial 572 finished with value: 0.9476242356032735 and parameters: {'weight_lgbm_class_0': 0.18021684235489424, 'weight_lgbm_class_1': 0.8964509662405314, 'weight_lgbm_class_2': 0.3736116324704597, 'weight_xgb_class_0': 0.0627027446873246, 'weight_xgb_class_1': 0.8296355224113079, 'weight_xgb_class_2': 0.8229368924609198}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:45,448] Trial 571 finished with value: 0.9490407373642951 and parameters: {'weight_lgbm_class_0': 0.11097665881264258, 'weight_lgbm_class_1': 0.9977507232604085, 'weight_lgbm_class_2': 0.36774477429584745, 'weight_xgb_class_0': 0.06365144656270452, 'weight_xgb_class_1': 0.8300459370080195, 'weight_xgb_class_2': 0.8243925647217961}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:45,501] Trial 573 finished with value: 0.9474593671227526 and parameters: {'weight_lgbm_class_0': 0.18251895361041603, 'weight_lgbm_class_1': 0.9814589675420089, 'weight_lgbm_class_2': 0.36467658100178885, 'weight_xgb_class_0': 0.06841794408377916, 'weight_xgb_class_1': 0.8280266791144059, 'weight_xgb_class_2': 0.821801920400938}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:45,529] Trial 574 finished with value: 0.9486471680490233 and parameters: {'weight_lgbm_class_0': 0.18237030529529819, 'weight_lgbm_class_1': 0.9815744002484269, 'weight_lgbm_class_2': 0.3714325384749513, 'weight_xgb_class_0': 0.023588735924368973, 'weight_xgb_class_1': 0.8248658765991337, 'weight_xgb_class_2': 0.8780031324142499}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  29%|██████████████████████████████████████▍                                                                                             | 582/2000 [00:14<00:40, 35.35it/s]

[I 2026-07-05 15:31:45,543] Trial 576 finished with value: 0.912585619285431 and parameters: {'weight_lgbm_class_0': 0.10924954026314576, 'weight_lgbm_class_1': 0.897045139845701, 'weight_lgbm_class_2': 0.40878385555776975, 'weight_xgb_class_0': 0.7548478724023409, 'weight_xgb_class_1': 0.832912707647708, 'weight_xgb_class_2': 0.8802332104916265}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:45,568] Trial 575 finished with value: 0.9487727748578149 and parameters: {'weight_lgbm_class_0': 0.1704303361201104, 'weight_lgbm_class_1': 0.9966522512281246, 'weight_lgbm_class_2': 0.3663657237930369, 'weight_xgb_class_0': 0.02331381999149333, 'weight_xgb_class_1': 0.8286302879373795, 'weight_xgb_class_2': 0.8837792425829248}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:45,586] Trial 577 finished with value: 0.9496763777797897 and parameters: {'weight_lgbm_class_0': 0.10991798368749206, 'weight_lgbm_class_1': 0.8994847482351381, 'weight_lgbm_class_2': 0.3644516178027826, 'weight_xgb_class_0': 0.024727311787715908, 'weight_xgb_class_1': 0.8373984087318572, 'weight_xgb_class_2': 0.8866186290200788}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:45,610] Trial 579 finished with value: 0.949666094098555 and parameters: {'weight_lgbm_class_0': 0.11277864401531476, 'weight_lgbm_class_1': 0.8966808253427683, 'weight_lgbm_class_2': 0.4051220700133386, 'weight_xgb_class_0': 0.022581783884330978, 'weight_xgb_class_1': 0.8284221719115087, 'weight_xgb_class_2': 0.8800900918253484}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:45,625] Trial 578 finished with value: 0.9483822641076519 and parameters: {'weight_lgbm_class_0': 0.10312186727796539, 'weight_lgbm_class_1': 0.8957684084530374, 'weight_lgbm_class_2': 0.4163599901324412, 'weight_xgb_class_0': 0.02766599458602955, 'weight_xgb_class_1': 0.8300375344442058, 'weight_xgb_class_2': 0.2839314977769626}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:45,686] Trial 581 finished with value: 0.9496263955867067 and parameters: {'weight_lgbm_class_0': 0.11142314562772597, 'weight_lgbm_class_1': 0.8975624533735436, 'weight_lgbm_class_2': 0.4062137357535667, 'weight_xgb_class_0': 0.021879262406518166, 'weight_xgb_class_1': 0.5335140179839956, 'weight_xgb_class_2': 0.8846859843461324}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:45,725] Trial 580 finished with value: 0.9497009545123317 and parameters: {'weight_lgbm_class_0': 0.11626565876875516, 'weight_lgbm_class_1': 0.8944749660133087, 'weight_lgbm_class_2': 0.417476981760122, 'weight_xgb_class_0': 0.022879183686078188, 'weight_xgb_class_1': 0.8281620921987577, 'weight_xgb_class_2': 0.8812843636752412}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:45,742] Trial 582 finished with value: 0.9496638654178066 and parameters: {'weight_lgbm_class_0': 0.10875295366385626, 'weight_lgbm_class_1': 0.8220123978653293, 'weight_lgbm_class_2': 0.41825068212021815, 'weight_xgb_class_0': 0.02338806865198354, 'weight_xgb_class_1': 0.8251172262793792, 'weight_xgb_class_2': 0.8827207091570375}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  29%|██████████████████████████████████████▊                                                                                             | 589/2000 [00:14<00:41, 33.75it/s]

[I 2026-07-05 15:31:45,784] Trial 583 finished with value: 0.9496822344772561 and parameters: {'weight_lgbm_class_0': 0.1089392917736779, 'weight_lgbm_class_1': 0.8573211531403283, 'weight_lgbm_class_2': 0.41482071754014, 'weight_xgb_class_0': 0.024515344037964362, 'weight_xgb_class_1': 0.7541537603339951, 'weight_xgb_class_2': 0.890048639680169}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:45,807] Trial 584 finished with value: 0.9496938936161229 and parameters: {'weight_lgbm_class_0': 0.11385540510346265, 'weight_lgbm_class_1': 0.8595604149208549, 'weight_lgbm_class_2': 0.3487469810184213, 'weight_xgb_class_0': 0.02354363578807523, 'weight_xgb_class_1': 0.7603721242498367, 'weight_xgb_class_2': 0.8914253211246603}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:45,830] Trial 585 finished with value: 0.9496791883892334 and parameters: {'weight_lgbm_class_0': 0.10573646765619642, 'weight_lgbm_class_1': 0.6946928094783459, 'weight_lgbm_class_2': 0.35143999595429903, 'weight_xgb_class_0': 0.022596939503610906, 'weight_xgb_class_1': 0.7568933458239397, 'weight_xgb_class_2': 0.8815132734900938}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:45,907] Trial 586 finished with value: 0.9496691027747284 and parameters: {'weight_lgbm_class_0': 0.10562074140080893, 'weight_lgbm_class_1': 0.8589187969824662, 'weight_lgbm_class_2': 0.3389815351928118, 'weight_xgb_class_0': 0.020192244116979074, 'weight_xgb_class_1': 0.7584758665551681, 'weight_xgb_class_2': 0.8858182942168659}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:45,908] Trial 588 finished with value: 0.9483334943331837 and parameters: {'weight_lgbm_class_0': 0.04088452226831164, 'weight_lgbm_class_1': 0.9448292765692881, 'weight_lgbm_class_2': 0.40574252942509104, 'weight_xgb_class_0': 0.017609904761291744, 'weight_xgb_class_1': 0.807971556706507, 'weight_xgb_class_2': 0.9623806746847491}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:45,937] Trial 589 finished with value: 0.9488789985086056 and parameters: {'weight_lgbm_class_0': 0.04761352519223143, 'weight_lgbm_class_1': 0.8619694743868477, 'weight_lgbm_class_2': 0.41487458227844304, 'weight_xgb_class_0': 0.023039821833228547, 'weight_xgb_class_1': 0.8147122196648429, 'weight_xgb_class_2': 0.9626386238487438}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:45,947] Trial 587 finished with value: 0.9490924943901543 and parameters: {'weight_lgbm_class_0': 0.04859893935630861, 'weight_lgbm_class_1': 0.8233256397872093, 'weight_lgbm_class_2': 0.4133954686600723, 'weight_xgb_class_0': 0.02190190964567066, 'weight_xgb_class_1': 0.8063342038890482, 'weight_xgb_class_2': 0.8605780054493759}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  30%|███████████████████████████████████████▎                                                                                            | 596/2000 [00:14<00:39, 35.50it/s]

[I 2026-07-05 15:31:45,974] Trial 591 finished with value: 0.9487001738431369 and parameters: {'weight_lgbm_class_0': 0.04264595280100719, 'weight_lgbm_class_1': 0.9326291788532401, 'weight_lgbm_class_2': 0.3493530686976596, 'weight_xgb_class_0': 0.021868974872547436, 'weight_xgb_class_1': 0.760307837922477, 'weight_xgb_class_2': 0.9591905712454332}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:45,994] Trial 590 finished with value: 0.9492161783075314 and parameters: {'weight_lgbm_class_0': 0.049273657883390914, 'weight_lgbm_class_1': 0.9353617176090084, 'weight_lgbm_class_2': 0.3402043987460433, 'weight_xgb_class_0': 0.022328631788891513, 'weight_xgb_class_1': 0.7483803848160648, 'weight_xgb_class_2': 0.8622652387646736}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:46,037] Trial 592 finished with value: 0.9492725146242375 and parameters: {'weight_lgbm_class_0': 0.05682057399497577, 'weight_lgbm_class_1': 0.9358848431629511, 'weight_lgbm_class_2': 0.3428658098662273, 'weight_xgb_class_0': 0.021216678326760316, 'weight_xgb_class_1': 0.7617644302879942, 'weight_xgb_class_2': 0.9628082539502133}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:46,070] Trial 593 finished with value: 0.9492811845189483 and parameters: {'weight_lgbm_class_0': 0.05413491961000433, 'weight_lgbm_class_1': 0.9351632277887205, 'weight_lgbm_class_2': 0.3343824029843483, 'weight_xgb_class_0': 0.019971903648157294, 'weight_xgb_class_1': 0.7525615554632363, 'weight_xgb_class_2': 0.8573615938861655}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:46,085] Trial 594 finished with value: 0.9490853439567664 and parameters: {'weight_lgbm_class_0': 0.05173215061333468, 'weight_lgbm_class_1': 0.9411724140156867, 'weight_lgbm_class_2': 0.3365372562289288, 'weight_xgb_class_0': 0.01930871435832332, 'weight_xgb_class_1': 0.8062503605482902, 'weight_xgb_class_2': 0.9117753088482009}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:46,124] Trial 595 finished with value: 0.9472257014214233 and parameters: {'weight_lgbm_class_0': 0.04242213853871183, 'weight_lgbm_class_1': 0.9365834538245157, 'weight_lgbm_class_2': 0.34691841563357945, 'weight_xgb_class_0': 1.179109880257434e-05, 'weight_xgb_class_1': 0.7961795760270884, 'weight_xgb_class_2': 0.9589447005180256}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:46,168] Trial 596 finished with value: 0.9485861062172787 and parameters: {'weight_lgbm_class_0': 0.041598998351796465, 'weight_lgbm_class_1': 0.9358522931770998, 'weight_lgbm_class_2': 0.22561393222717943, 'weight_xgb_class_0': 0.01740505993253449, 'weight_xgb_class_1': 0.8052228544684643, 'weight_xgb_class_2': 0.9610139289393077}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  30%|███████████████████████████████████████▊                                                                                            | 604/2000 [00:15<00:41, 33.42it/s]

[I 2026-07-05 15:31:46,175] Trial 597 finished with value: 0.9492283490025671 and parameters: {'weight_lgbm_class_0': 0.05761227470929557, 'weight_lgbm_class_1': 0.9463925133826839, 'weight_lgbm_class_2': 0.3458141961708789, 'weight_xgb_class_0': 0.018637264471126045, 'weight_xgb_class_1': 0.8039790119178762, 'weight_xgb_class_2': 0.9556463631114614}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:46,264] Trial 598 finished with value: 0.9495935698809923 and parameters: {'weight_lgbm_class_0': 0.04737193169437378, 'weight_lgbm_class_1': 0.9334337392269785, 'weight_lgbm_class_2': 0.31472129350001027, 'weight_xgb_class_0': 0.042496750623382956, 'weight_xgb_class_1': 0.8063644267148675, 'weight_xgb_class_2': 0.9105078435993459}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:46,278] Trial 599 finished with value: 0.9488040997224862 and parameters: {'weight_lgbm_class_0': 0.06276577109517625, 'weight_lgbm_class_1': 0.9351672460116746, 'weight_lgbm_class_2': 0.32547971968406997, 'weight_xgb_class_0': 0.0006704449934361379, 'weight_xgb_class_1': 0.8081004344649807, 'weight_xgb_class_2': 0.8609631452337325}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:46,283] Trial 601 finished with value: 0.949707299558467 and parameters: {'weight_lgbm_class_0': 0.06749245252615305, 'weight_lgbm_class_1': 0.9408702861854622, 'weight_lgbm_class_2': 0.29449515917228314, 'weight_xgb_class_0': 0.04485330502414401, 'weight_xgb_class_1': 0.7796504383351914, 'weight_xgb_class_2': 0.9101881187966503}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:46,309] Trial 600 finished with value: 0.9497126896186922 and parameters: {'weight_lgbm_class_0': 0.07022042883709079, 'weight_lgbm_class_1': 0.943671232423289, 'weight_lgbm_class_2': 0.3194074844270344, 'weight_xgb_class_0': 0.04518910110590479, 'weight_xgb_class_1': 0.7995320307398527, 'weight_xgb_class_2': 0.9143558897988396}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:46,340] Trial 602 finished with value: 0.9497871803102406 and parameters: {'weight_lgbm_class_0': 0.06528249241412624, 'weight_lgbm_class_1': 0.9350928939955097, 'weight_lgbm_class_2': 0.32106173346374234, 'weight_xgb_class_0': 0.04686489262606422, 'weight_xgb_class_1': 0.8034676144111631, 'weight_xgb_class_2': 0.9098526721031144}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:46,361] Trial 603 finished with value: 0.9061468655031754 and parameters: {'weight_lgbm_class_0': 0.9198718857650431, 'weight_lgbm_class_1': 0.9344977031948918, 'weight_lgbm_class_2': 0.2901466100159801, 'weight_xgb_class_0': 0.00016843338617641805, 'weight_xgb_class_1': 0.8013565333001249, 'weight_xgb_class_2': 0.9151750337657284}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:46,377] Trial 604 finished with value: 0.9497294163154896 and parameters: {'weight_lgbm_class_0': 0.0724670778055425, 'weight_lgbm_class_1': 0.9377003804388614, 'weight_lgbm_class_2': 0.3219552520675878, 'weight_xgb_class_0': 0.04520191139749332, 'weight_xgb_class_1': 0.8005312824098144, 'weight_xgb_class_2': 0.9086036153153524}. Best is trial 358 with value: 0.9497927483550862.

[I 2026-07-05 15:31:46,434] Trial 605 finished with value: 0.9497368797368998 and parameters: {'weight_lgbm_class_0': 0.07198829004036222, 'weight_lgbm_class_1': 0.9505643171054498, 'weight_lgbm_class_2': 0.24990333969204478, 'weight_xgb_class_0': 0.04445144888252603, 'weight_xgb_class_1': 0.7814937881263071, 'weight_xgb_class_2': 0.9096596809429128}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:46,460] Trial 606 finished with value: 0.9492218428208802 and parameters: {'weight_lgbm_class_0': 0.07439696245518145, 'weight_lgbm_class_1': 0.9503103548894986, 'weight_lgbm_class_2': 0.2926473812321922, 'weight_xgb_class_0': 0.00026691744418052415, 'weight_xgb_class_1': 0.800250701837342, 'weight_xgb_class_2': 0.9137085308251629}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:46,469] Trial 607 finished with value: 0.94971949584321 and parameters: {'weight_lgbm_class_0': 0.07105161167307181, 'weight_lgbm_class_1': 0.948454395849719, 'weight_lgbm_class_2': 0.2520123746578655, 'weight_xgb_class_0': 0.04635473256320437, 'weight_xgb_class_1': 0.7801700312170163, 'weight_xgb_class_2': 0.9400955255714596}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:46,529] Trial 608 finished with value: 0.9496572786374582 and parameters: {'weight_lgbm_class_0': 0.07935080390851464, 'weight_lgbm_class_1': 0.9519925775451339, 'weight_lgbm_class_2': 0.29102614683157185, 'weight_xgb_class_0': 0.049718937858436354, 'weight_xgb_class_1': 0.7798284065983865, 'weight_xgb_class_2': 0.9193998765375717}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:46,546] Trial 609 finished with value: 0.9496441689909214 and parameters: {'weight_lgbm_class_0': 0.08699984757816326, 'weight_lgbm_class_1': 0.9091429379027267, 'weight_lgbm_class_2': 0.2913675571478837, 'weight_xgb_class_0': 0.05016473360146197, 'weight_xgb_class_1': 0.7790566710167663, 'weight_xgb_class_2': 0.9108449518149249}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:46,619] Trial 610 finished with value: 0.9496344083588624 and parameters: {'weight_lgbm_class_0': 0.08804502056944136, 'weight_lgbm_class_1': 0.8363058665328739, 'weight_lgbm_class_2': 0.25257255138076573, 'weight_xgb_class_0': 0.052855971323676365, 'weight_xgb_class_1': 0.8615290902467307, 'weight_xgb_class_2': 0.9327223033589138}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:46,640] Trial 611 finished with value: 0.9495533315655166 and parameters: {'weight_lgbm_class_0': 0.09064035445034523, 'weight_lgbm_class_1': 0.9985476177468183, 'weight_lgbm_class_2': 0.2874500869493315, 'weight_xgb_class_0': 0.05902783474695843, 'weight_xgb_class_1': 0.7809991947201238, 'weight_xgb_class_2': 0.9141699073544567}. Best is trial 358 with value: 0.9497927483550862.

[I 2026-07-05 15:31:46,656] Trial 612 finished with value: 0.9482058084186337 and parameters: {'weight_lgbm_class_0': 0.15546860679697316, 'weight_lgbm_class_1': 0.8382789002588282, 'weight_lgbm_class_2': 0.29235082148904945, 'weight_xgb_class_0': 0.060661089011557985, 'weight_xgb_class_1': 0.7784853293066398, 'weight_xgb_class_2': 0.9276847240402707}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:46,714] Trial 613 finished with value: 0.9496440979065323 and parameters: {'weight_lgbm_class_0': 0.08506836065647008, 'weight_lgbm_class_1': 0.9994908693215796, 'weight_lgbm_class_2': 0.28427137132865826, 'weight_xgb_class_0': 0.055272812407119246, 'weight_xgb_class_1': 0.776222437470012, 'weight_xgb_class_2': 0.930186473053054}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:46,723] Trial 614 finished with value: 0.9494169826238784 and parameters: {'weight_lgbm_class_0': 0.09066065537247187, 'weight_lgbm_class_1': 0.9558528603588998, 'weight_lgbm_class_2': 0.30432865685199006, 'weight_xgb_class_0': 0.06890273986905301, 'weight_xgb_class_1': 0.7801213840868673, 'weight_xgb_class_2': 0.9351660267983795}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:46,728] Trial 616 finished with value: 0.9495689225650126 and parameters: {'weight_lgbm_class_0': 0.08571009433449102, 'weight_lgbm_class_1': 0.9530237378066596, 'weight_lgbm_class_2': 0.2501481500390206, 'weight_xgb_class_0': 0.059489436319441376, 'weight_xgb_class_1': 0.7792139885998998, 'weight_xgb_class_2': 0.9286702400892729}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:46,734] Trial 615 finished with value: 0.9495157099485695 and parameters: {'weight_lgbm_class_0': 0.08859100018562911, 'weight_lgbm_class_1': 0.9771238968684081, 'weight_lgbm_class_2': 0.25579680832183943, 'weight_xgb_class_0': 0.06220593248697623, 'weight_xgb_class_1': 0.7777869647017692, 'weight_xgb_class_2': 0.9318063437986975}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:46,802] Trial 617 finished with value: 0.947323135986032 and parameters: {'weight_lgbm_class_0': 0.0875749672350307, 'weight_lgbm_class_1': 0.9761619779495384, 'weight_lgbm_class_2': 0.24249031758183176, 'weight_xgb_class_0': 0.16597048672104261, 'weight_xgb_class_1': 0.7757711632882295, 'weight_xgb_class_2': 0.9405558386803206}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:46,808] Trial 618 finished with value: 0.9496356100441413 and parameters: {'weight_lgbm_class_0': 0.08292497277246069, 'weight_lgbm_class_1': 0.9992269262944057, 'weight_lgbm_class_2': 0.24628619227273366, 'weight_xgb_class_0': 0.060867513987486334, 'weight_xgb_class_1': 0.7717469315807599, 'weight_xgb_class_2': 0.9310559622152764}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:46,810] Trial 619 finished with value: 0.9496832815958599 and parameters: {'weight_lgbm_class_0': 0.08886958780855707, 'weight_lgbm_class_1': 0.977554294615638, 'weight_lgbm_class_2': 0.22736045601391114, 'weight_xgb_class_0': 0.04754849172713131, 'weight_xgb_class_1': 0.7792793233665296, 'weight_xgb_class_2': 0.9256784644451107}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  31%|█████████████████████████████████████████▎                                                                                          | 626/2000 [00:15<00:41, 33.30it/s]

[I 2026-07-05 15:31:46,872] Trial 620 finished with value: 0.948080174868626 and parameters: {'weight_lgbm_class_0': 0.15235484018622134, 'weight_lgbm_class_1': 0.9755426572295481, 'weight_lgbm_class_2': 0.2451681479524095, 'weight_xgb_class_0': 0.07172786517869201, 'weight_xgb_class_1': 0.7845301318342148, 'weight_xgb_class_2': 0.9386513524100701}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:46,896] Trial 621 finished with value: 0.9478022747941787 and parameters: {'weight_lgbm_class_0': 0.15892634315981916, 'weight_lgbm_class_1': 0.9791429922496394, 'weight_lgbm_class_2': 0.24831783709263477, 'weight_xgb_class_0': 0.07005464890615501, 'weight_xgb_class_1': 0.5958671255899302, 'weight_xgb_class_2': 0.9364211476210743}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:46,956] Trial 622 finished with value: 0.9485624487595317 and parameters: {'weight_lgbm_class_0': 0.12319807793508623, 'weight_lgbm_class_1': 0.9763544879879081, 'weight_lgbm_class_2': 0.20697386985405078, 'weight_xgb_class_0': 0.07434450984383277, 'weight_xgb_class_1': 0.7794086581867203, 'weight_xgb_class_2': 0.9304157282102992}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:46,957] Trial 623 finished with value: 0.9486512141523943 and parameters: {'weight_lgbm_class_0': 0.1249550716328856, 'weight_lgbm_class_1': 0.9722841452238241, 'weight_lgbm_class_2': 0.24699940112215413, 'weight_xgb_class_0': 0.06822688769195139, 'weight_xgb_class_1': 0.7701617646223281, 'weight_xgb_class_2': 0.942735477615737}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:46,966] Trial 624 finished with value: 0.9419938617560746 and parameters: {'weight_lgbm_class_0': 0.11582195049270998, 'weight_lgbm_class_1': 0.9741746044442873, 'weight_lgbm_class_2': 0.24380614617002336, 'weight_xgb_class_0': 0.17018098509885693, 'weight_xgb_class_1': 0.020771547200273854, 'weight_xgb_class_2': 0.9460338440113097}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:47,033] Trial 626 finished with value: 0.9455121612113572 and parameters: {'weight_lgbm_class_0': 0.12805717448365866, 'weight_lgbm_class_1': 0.9824880694830611, 'weight_lgbm_class_2': 0.20093923753597576, 'weight_xgb_class_0': 0.16275865363116132, 'weight_xgb_class_1': 0.7245117341651044, 'weight_xgb_class_2': 0.9470006435624524}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:47,048] Trial 627 finished with value: 0.9461200689322012 and parameters: {'weight_lgbm_class_0': 0.12377737335460902, 'weight_lgbm_class_1': 0.9756458713095684, 'weight_lgbm_class_2': 0.22166580418269788, 'weight_xgb_class_0': 0.16170370900273418, 'weight_xgb_class_1': 0.8188050208708917, 'weight_xgb_class_2': 0.9401988016861892}. Best is trial 358 with value: 0.9497927483550862.

[I 2026-07-05 15:31:47,058] Trial 625 finished with value: 0.9492426161991987 and parameters: {'weight_lgbm_class_0': 0.12071950029554747, 'weight_lgbm_class_1': 0.9692124931021944, 'weight_lgbm_class_2': 0.3213204225192569, 'weight_xgb_class_0': 0.03883991102403129, 'weight_xgb_class_1': 0.344963815374273, 'weight_xgb_class_2': 0.9488461116377619}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:47,083] Trial 628 finished with value: 0.9490763127029748 and parameters: {'weight_lgbm_class_0': 0.1250962043631214, 'weight_lgbm_class_1': 0.9758052836899035, 'weight_lgbm_class_2': 0.21436616679949555, 'weight_xgb_class_0': 0.03866060186847229, 'weight_xgb_class_1': 0.7367737876058287, 'weight_xgb_class_2': 0.9413028609853503}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:47,117] Trial 629 finished with value: 0.949322157637773 and parameters: {'weight_lgbm_class_0': 0.1267412592418653, 'weight_lgbm_class_1': 0.974325776666575, 'weight_lgbm_class_2': 0.31956335765534777, 'weight_xgb_class_0': 0.03639895978658291, 'weight_xgb_class_1': 0.8166911132668511, 'weight_xgb_class_2': 0.9038577089423643}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:47,150] Trial 631 finished with value: 0.9493949745686878 and parameters: {'weight_lgbm_class_0': 0.12041984602817568, 'weight_lgbm_class_1': 0.9726035549206418, 'weight_lgbm_class_2': 0.31718395534718924, 'weight_xgb_class_0': 0.03684312339775819, 'weight_xgb_class_1': 0.7392494460680679, 'weight_xgb_class_2': 0.9002314026658206}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:47,150] Trial 630 finished with value: 0.9494720079777194 and parameters: {'weight_lgbm_class_0': 0.12122951521811957, 'weight_lgbm_class_1': 0.9756596963222917, 'weight_lgbm_class_2': 0.3198811445371519, 'weight_xgb_class_0': 0.03396350358499594, 'weight_xgb_class_1': 0.7372628776375454, 'weight_xgb_class_2': 0.9040424491914709}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:47,189] Trial 632 finished with value: 0.9497400274926336 and parameters: {'weight_lgbm_class_0': 0.12376861370633999, 'weight_lgbm_class_1': 0.9776332421746275, 'weight_lgbm_class_2': 0.3212460795464342, 'weight_xgb_class_0': 0.00015774190514311615, 'weight_xgb_class_1': 0.818083317595243, 'weight_xgb_class_2': 0.9035556080707625}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:47,204] Trial 633 finished with value: 0.9489172821664543 and parameters: {'weight_lgbm_class_0': 0.12709076044765139, 'weight_lgbm_class_1': 0.7409159856444267, 'weight_lgbm_class_2': 0.20611641132848516, 'weight_xgb_class_0': 0.03997729638425488, 'weight_xgb_class_1': 0.7273226864423631, 'weight_xgb_class_2': 0.9009426484106107}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:47,265] Trial 636 finished with value: 0.9495148885963923 and parameters: {'weight_lgbm_class_0': 0.1182574079482796, 'weight_lgbm_class_1': 0.9195513446566067, 'weight_lgbm_class_2': 0.3240304080018018, 'weight_xgb_class_0': 0.03460364160090351, 'weight_xgb_class_1': 0.7368897596049309, 'weight_xgb_class_2': 0.8954180664026878}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  32%|██████████████████████████████████████████▎                                                                                         | 642/2000 [00:16<00:37, 36.39it/s]

[I 2026-07-05 15:31:47,269] Trial 634 finished with value: 0.9494187665795545 and parameters: {'weight_lgbm_class_0': 0.11868950520006577, 'weight_lgbm_class_1': 0.9220950998613601, 'weight_lgbm_class_2': 0.3128645113286467, 'weight_xgb_class_0': 0.03729802980616844, 'weight_xgb_class_1': 0.8177786368570137, 'weight_xgb_class_2': 0.9029951800215301}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:47,307] Trial 635 finished with value: 0.9497447558353093 and parameters: {'weight_lgbm_class_0': 0.1203648834695574, 'weight_lgbm_class_1': 0.9177443095450459, 'weight_lgbm_class_2': 0.32149691570379174, 'weight_xgb_class_0': 4.263769625008977e-05, 'weight_xgb_class_1': 0.7388545336283812, 'weight_xgb_class_2': 0.9025554131710493}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:47,358] Trial 637 finished with value: 0.9495927156940764 and parameters: {'weight_lgbm_class_0': 0.10633485948523372, 'weight_lgbm_class_1': 0.4155533695652466, 'weight_lgbm_class_2': 0.3116769528306037, 'weight_xgb_class_0': 0.03606822908829531, 'weight_xgb_class_1': 0.8219045355626776, 'weight_xgb_class_2': 0.9049157925075721}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:47,386] Trial 639 finished with value: 0.9497415818730882 and parameters: {'weight_lgbm_class_0': 0.06698106386227765, 'weight_lgbm_class_1': 0.909398148688222, 'weight_lgbm_class_2': 0.31954804310569407, 'weight_xgb_class_0': 0.03470398293776092, 'weight_xgb_class_1': 0.8198374300129428, 'weight_xgb_class_2': 0.9051323991733007}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:47,389] Trial 640 finished with value: 0.9497603233473747 and parameters: {'weight_lgbm_class_0': 0.10177169705060607, 'weight_lgbm_class_1': 0.9221658401646354, 'weight_lgbm_class_2': 0.31489433359586283, 'weight_xgb_class_0': 0.00037427027282137476, 'weight_xgb_class_1': 0.8030364025142506, 'weight_xgb_class_2': 0.9071436496682398}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:47,399] Trial 638 finished with value: 0.9497329192180913 and parameters: {'weight_lgbm_class_0': 0.06824394597864161, 'weight_lgbm_class_1': 0.9225587250049245, 'weight_lgbm_class_2': 0.31580655588306167, 'weight_xgb_class_0': 0.035049019970562936, 'weight_xgb_class_1': 0.8197271078828238, 'weight_xgb_class_2': 0.90288436396302}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:47,421] Trial 641 finished with value: 0.9492093150335538 and parameters: {'weight_lgbm_class_0': 0.07004734908725811, 'weight_lgbm_class_1': 0.9240760280570954, 'weight_lgbm_class_2': 0.3150148919607794, 'weight_xgb_class_0': 0.0012351384669341047, 'weight_xgb_class_1': 0.7002603217962299, 'weight_xgb_class_2': 0.9010458334051371}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:47,449] Trial 642 finished with value: 0.9492171904534121 and parameters: {'weight_lgbm_class_0': 0.06946696401458963, 'weight_lgbm_class_1': 0.9199253775507205, 'weight_lgbm_class_2': 0.30189283325417643, 'weight_xgb_class_0': 0.0012897792483850439, 'weight_xgb_class_1': 0.6921619393803782, 'weight_xgb_class_2': 0.9014832924137094}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  32%|██████████████████████████████████████████▉                                                                                         | 650/2000 [00:16<00:36, 36.96it/s]

[I 2026-07-05 15:31:47,509] Trial 644 finished with value: 0.9492107490077929 and parameters: {'weight_lgbm_class_0': 0.15671648351771766, 'weight_lgbm_class_1': 0.9245282611540989, 'weight_lgbm_class_2': 0.27211429181679947, 'weight_xgb_class_0': 0.002452377435307418, 'weight_xgb_class_1': 0.6380969521462289, 'weight_xgb_class_2': 0.9071213012987376}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:47,539] Trial 645 finished with value: 0.9493701878777894 and parameters: {'weight_lgbm_class_0': 0.1519494457446669, 'weight_lgbm_class_1': 0.9996203375578772, 'weight_lgbm_class_2': 0.27683520050228977, 'weight_xgb_class_0': 0.0033145158664141146, 'weight_xgb_class_1': 0.8234139424549161, 'weight_xgb_class_2': 0.9068607812762303}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:47,544] Trial 643 finished with value: 0.9491385127512677 and parameters: {'weight_lgbm_class_0': 0.1476100705951731, 'weight_lgbm_class_1': 0.9064750676875182, 'weight_lgbm_class_2': 0.2736637404760565, 'weight_xgb_class_0': 0.015143659000058513, 'weight_xgb_class_1': 0.7002494222890084, 'weight_xgb_class_2': 0.9106679496906481}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:47,587] Trial 646 finished with value: 0.9487405947811832 and parameters: {'weight_lgbm_class_0': 0.15003738468218228, 'weight_lgbm_class_1': 0.9525341885897256, 'weight_lgbm_class_2': 0.032625944866551626, 'weight_xgb_class_0': 0.0029208117474270796, 'weight_xgb_class_1': 0.7016039623440758, 'weight_xgb_class_2': 0.9104735311669728}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:47,602] Trial 647 finished with value: 0.9489164913281146 and parameters: {'weight_lgbm_class_0': 0.16271127775801025, 'weight_lgbm_class_1': 0.9037848318042419, 'weight_lgbm_class_2': 0.2824219420533681, 'weight_xgb_class_0': 0.014785880996435918, 'weight_xgb_class_1': 0.799536516428226, 'weight_xgb_class_2': 0.9059087107950898}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:47,621] Trial 648 finished with value: 0.9490272389190961 and parameters: {'weight_lgbm_class_0': 0.1665941004379708, 'weight_lgbm_class_1': 0.9041803363846261, 'weight_lgbm_class_2': 0.2733356510852897, 'weight_xgb_class_0': 0.000610244302647798, 'weight_xgb_class_1': 0.7170967154719131, 'weight_xgb_class_2': 0.9070767339531235}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:47,676] Trial 649 finished with value: 0.9491940051868483 and parameters: {'weight_lgbm_class_0': 0.1572179492975919, 'weight_lgbm_class_1': 0.9020466785289041, 'weight_lgbm_class_2': 0.28375411042314713, 'weight_xgb_class_0': 0.0027170448604852612, 'weight_xgb_class_1': 0.8023203099954521, 'weight_xgb_class_2': 0.8942920563424186}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:47,696] Trial 650 finished with value: 0.9492682172130058 and parameters: {'weight_lgbm_class_0': 0.15575452885963717, 'weight_lgbm_class_1': 0.8997156188597725, 'weight_lgbm_class_2': 0.2776226226176559, 'weight_xgb_class_0': 0.00020874164454317182, 'weight_xgb_class_1': 0.7130596271323764, 'weight_xgb_class_2': 0.8935657653043914}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  33%|███████████████████████████████████████████▌                                                                                        | 660/2000 [00:16<00:35, 37.42it/s]

[I 2026-07-05 15:31:47,763] Trial 653 finished with value: 0.9490336663037224 and parameters: {'weight_lgbm_class_0': 0.1498773371297597, 'weight_lgbm_class_1': 0.8995538016367272, 'weight_lgbm_class_2': 0.2668189987936438, 'weight_xgb_class_0': 0.012434053597436608, 'weight_xgb_class_1': 0.7570770150269788, 'weight_xgb_class_2': 0.8837164574640154}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:47,764] Trial 652 finished with value: 0.9492545958664781 and parameters: {'weight_lgbm_class_0': 0.14063688410891337, 'weight_lgbm_class_1': 0.8941415806352246, 'weight_lgbm_class_2': 0.2737548094693954, 'weight_xgb_class_0': 0.015141830672084201, 'weight_xgb_class_1': 0.7164111326186231, 'weight_xgb_class_2': 0.8895674810353849}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:47,775] Trial 651 finished with value: 0.949299869794142 and parameters: {'weight_lgbm_class_0': 0.15419473924201904, 'weight_lgbm_class_1': 0.9043793310444693, 'weight_lgbm_class_2': 0.26961278978287917, 'weight_xgb_class_0': 0.0013447561911588703, 'weight_xgb_class_1': 0.6974796931885736, 'weight_xgb_class_2': 0.9170254948810759}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:47,794] Trial 654 finished with value: 0.9491645366348974 and parameters: {'weight_lgbm_class_0': 0.15738086653647465, 'weight_lgbm_class_1': 0.9003141813399146, 'weight_lgbm_class_2': 0.275453652910659, 'weight_xgb_class_0': 0.0008326430308320774, 'weight_xgb_class_1': 0.7515444771565755, 'weight_xgb_class_2': 0.8864608197291658}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:47,838] Trial 655 finished with value: 0.9489820644130446 and parameters: {'weight_lgbm_class_0': 0.1470288850392737, 'weight_lgbm_class_1': 0.8960794261657656, 'weight_lgbm_class_2': 0.2700446731260062, 'weight_xgb_class_0': 0.014506218566340068, 'weight_xgb_class_1': 0.4816896901804719, 'weight_xgb_class_2': 0.8841829698207809}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:47,870] Trial 656 finished with value: 0.9493386181698727 and parameters: {'weight_lgbm_class_0': 0.14462629295022658, 'weight_lgbm_class_1': 0.8939232250840278, 'weight_lgbm_class_2': 0.27779541710576755, 'weight_xgb_class_0': 0.01642918441861273, 'weight_xgb_class_1': 0.7546719368660774, 'weight_xgb_class_2': 0.9764840410234326}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:47,883] Trial 657 finished with value: 0.9490016882338708 and parameters: {'weight_lgbm_class_0': 0.15882318321042094, 'weight_lgbm_class_1': 0.8672370817532435, 'weight_lgbm_class_2': 0.13129337111229844, 'weight_xgb_class_0': 0.0009348207993014373, 'weight_xgb_class_1': 0.680224090412523, 'weight_xgb_class_2': 0.9733893347000128}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:47,919] Trial 660 finished with value: 0.9497340982460268 and parameters: {'weight_lgbm_class_0': 0.10573007163196048, 'weight_lgbm_class_1': 0.8645668916977041, 'weight_lgbm_class_2': 0.3428960043272963, 'weight_xgb_class_0': 0.01771657859864696, 'weight_xgb_class_1': 0.7546850735191836, 'weight_xgb_class_2': 0.8852378691728309}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:47,923] Trial 658 finished with value: 0.9497451016401864 and parameters: {'weight_lgbm_class_0': 0.10235244894997317, 'weight_lgbm_class_1': 0.8682098964978686, 'weight_lgbm_class_2': 0.3428613257175903, 'weight_xgb_class_0': 0.017720927347310286, 'weight_xgb_class_1': 0.7570178342100743, 'weight_xgb_class_2': 0.9673791869492463}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:47,930] Trial 659 finished with value: 0.9476933828620332 and parameters: {'weight_lgbm_class_0': 0.10364132942303723, 'weight_lgbm_class_1': 0.8670556825590954, 'weight_lgbm_class_2': 0.3482403045093806, 'weight_xgb_class_0': 0.01708092914270498, 'weight_xgb_class_1': 0.8011975143891621, 'weight_xgb_class_2': 0.2135236187266098}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  33%|███████████████████████████████████████████▉                                                                                        | 666/2000 [00:16<00:36, 36.80it/s]

[I 2026-07-05 15:31:47,979] Trial 661 finished with value: 0.9497591584031079 and parameters: {'weight_lgbm_class_0': 0.09941624850139107, 'weight_lgbm_class_1': 0.8735625452000573, 'weight_lgbm_class_2': 0.34423599546124856, 'weight_xgb_class_0': 0.019302951945183403, 'weight_xgb_class_1': 0.7591348905787935, 'weight_xgb_class_2': 0.8801338976001816}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:48,008] Trial 662 finished with value: 0.949659149370231 and parameters: {'weight_lgbm_class_0': 0.10528892599767933, 'weight_lgbm_class_1': 0.8682220905312733, 'weight_lgbm_class_2': 0.34662235624864535, 'weight_xgb_class_0': 0.01871115641258103, 'weight_xgb_class_1': 0.7508796424857778, 'weight_xgb_class_2': 0.976177648575121}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:48,064] Trial 663 finished with value: 0.9497173142941763 and parameters: {'weight_lgbm_class_0': 0.10451682392027481, 'weight_lgbm_class_1': 0.8696281707342438, 'weight_lgbm_class_2': 0.30140276495325846, 'weight_xgb_class_0': 0.02208112239085024, 'weight_xgb_class_1': 0.8021301297474134, 'weight_xgb_class_2': 0.9750773520128754}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:48,105] Trial 664 finished with value: 0.9497399572513633 and parameters: {'weight_lgbm_class_0': 0.09819163017183291, 'weight_lgbm_class_1': 0.8616864169615502, 'weight_lgbm_class_2': 0.34027422663125695, 'weight_xgb_class_0': 0.021196107395281782, 'weight_xgb_class_1': 0.7979068335130451, 'weight_xgb_class_2': 0.972686096670548}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:48,145] Trial 665 finished with value: 0.9497369105875864 and parameters: {'weight_lgbm_class_0': 0.10285352943723142, 'weight_lgbm_class_1': 0.9528272100851246, 'weight_lgbm_class_2': 0.3478685219379907, 'weight_xgb_class_0': 0.0235739703324398, 'weight_xgb_class_1': 0.7926642320321875, 'weight_xgb_class_2': 0.9768869882342588}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:48,152] Trial 666 finished with value: 0.9451859391618983 and parameters: {'weight_lgbm_class_0': 0.10146301584782771, 'weight_lgbm_class_1': 0.8703622506255139, 'weight_lgbm_class_2': 0.34706174016937863, 'weight_xgb_class_0': 0.022660466422197975, 'weight_xgb_class_1': 0.6679279940869631, 'weight_xgb_class_2': 0.09902909665685489}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  34%|████████████████████████████████████████████▌                                                                                       | 675/2000 [00:16<00:34, 38.18it/s]

[I 2026-07-05 15:31:48,172] Trial 667 finished with value: 0.9497340632448442 and parameters: {'weight_lgbm_class_0': 0.10316715939167571, 'weight_lgbm_class_1': 0.9550525095817969, 'weight_lgbm_class_2': 0.3456127680136694, 'weight_xgb_class_0': 0.023556961408203327, 'weight_xgb_class_1': 0.7965219223115116, 'weight_xgb_class_2': 0.9768089211219183}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:48,199] Trial 669 finished with value: 0.9496702946040334 and parameters: {'weight_lgbm_class_0': 0.09830570974821096, 'weight_lgbm_class_1': 0.8595882227404441, 'weight_lgbm_class_2': 0.3490107318536087, 'weight_xgb_class_0': 0.03215285695493629, 'weight_xgb_class_1': 0.7393406810701115, 'weight_xgb_class_2': 0.9251805205527853}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:48,214] Trial 668 finished with value: 0.9496496850416932 and parameters: {'weight_lgbm_class_0': 0.10154503367831116, 'weight_lgbm_class_1': 0.8691589210187449, 'weight_lgbm_class_2': 0.347542556618055, 'weight_xgb_class_0': 0.023876066777382608, 'weight_xgb_class_1': 0.5728367502592235, 'weight_xgb_class_2': 0.864667901686059}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:48,250] Trial 670 finished with value: 0.9496782779443759 and parameters: {'weight_lgbm_class_0': 0.10217920821580886, 'weight_lgbm_class_1': 0.99945562216826, 'weight_lgbm_class_2': 0.34553367629010734, 'weight_xgb_class_0': 0.03509038390069715, 'weight_xgb_class_1': 0.7940808630604895, 'weight_xgb_class_2': 0.9531941774250989}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:48,281] Trial 671 finished with value: 0.9496479039078706 and parameters: {'weight_lgbm_class_0': 0.1066578916668143, 'weight_lgbm_class_1': 0.849570820679131, 'weight_lgbm_class_2': 0.3470127147899121, 'weight_xgb_class_0': 0.03425335905348523, 'weight_xgb_class_1': 0.7352373386215313, 'weight_xgb_class_2': 0.972541499970324}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:48,292] Trial 672 finished with value: 0.9496937470912551 and parameters: {'weight_lgbm_class_0': 0.10045468071342586, 'weight_lgbm_class_1': 0.9989802696518792, 'weight_lgbm_class_2': 0.34747885478623436, 'weight_xgb_class_0': 0.0329036191897781, 'weight_xgb_class_1': 0.7319632648595468, 'weight_xgb_class_2': 0.9885445569268654}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:48,302] Trial 673 finished with value: 0.9496619443897637 and parameters: {'weight_lgbm_class_0': 0.10303277686010893, 'weight_lgbm_class_1': 0.8365139541693775, 'weight_lgbm_class_2': 0.3481811861894923, 'weight_xgb_class_0': 0.033534712032818215, 'weight_xgb_class_1': 0.740116872393181, 'weight_xgb_class_2': 0.9727027003371729}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:48,325] Trial 674 finished with value: 0.949676422562609 and parameters: {'weight_lgbm_class_0': 0.10253829672537332, 'weight_lgbm_class_1': 0.8402716348382373, 'weight_lgbm_class_2': 0.3896261867327787, 'weight_xgb_class_0': 0.03953001508857272, 'weight_xgb_class_1': 0.7475755089813501, 'weight_xgb_class_2': 0.9862258356737534}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:48,365] Trial 675 finished with value: 0.9496383182329855 and parameters: {'weight_lgbm_class_0': 0.09691693418050226, 'weight_lgbm_class_1': 0.837758777855987, 'weight_lgbm_class_2': 0.3477431171211045, 'weight_xgb_class_0': 0.040460443250263975, 'weight_xgb_class_1': 0.7256557309648733, 'weight_xgb_class_2': 0.9628157033987637}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  34%|████████████████████████████████████████████▉                                                                                       | 681/2000 [00:17<00:43, 30.59it/s]

[I 2026-07-05 15:31:48,432] Trial 676 finished with value: 0.949722246786934 and parameters: {'weight_lgbm_class_0': 0.10315132344149626, 'weight_lgbm_class_1': 0.843979423578812, 'weight_lgbm_class_2': 0.39238777557658044, 'weight_xgb_class_0': 0.03404726137494607, 'weight_xgb_class_1': 0.7323035234755099, 'weight_xgb_class_2': 0.9876817182465815}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:48,453] Trial 677 finished with value: 0.9497010243708747 and parameters: {'weight_lgbm_class_0': 0.0981772493439172, 'weight_lgbm_class_1': 0.8495595277855723, 'weight_lgbm_class_2': 0.3828712306035893, 'weight_xgb_class_0': 0.037240860161432285, 'weight_xgb_class_1': 0.7380612173322504, 'weight_xgb_class_2': 0.9679944973616685}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:48,516] Trial 678 finished with value: 0.9497112479752028 and parameters: {'weight_lgbm_class_0': 0.09864904568368121, 'weight_lgbm_class_1': 0.8366285847421406, 'weight_lgbm_class_2': 0.38801559152858695, 'weight_xgb_class_0': 0.03716449262576305, 'weight_xgb_class_1': 0.7405050706486247, 'weight_xgb_class_2': 0.9725781571337052}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:48,579] Trial 680 finished with value: 0.9494022941509751 and parameters: {'weight_lgbm_class_0': 0.12883903943190628, 'weight_lgbm_class_1': 0.88121343037494, 'weight_lgbm_class_2': 0.38220585270687923, 'weight_xgb_class_0': 0.04092801925447803, 'weight_xgb_class_1': 0.8592717575822767, 'weight_xgb_class_2': 0.9590280039912417}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:48,602] Trial 681 finished with value: 0.9493124847697518 and parameters: {'weight_lgbm_class_0': 0.13374114279817836, 'weight_lgbm_class_1': 0.8431576143112397, 'weight_lgbm_class_2': 0.383883622855091, 'weight_xgb_class_0': 0.04251967713579444, 'weight_xgb_class_1': 0.7617814733593746, 'weight_xgb_class_2': 0.9893077517986579}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:48,611] Trial 679 finished with value: 0.9493888541866755 and parameters: {'weight_lgbm_class_0': 0.13262003923802554, 'weight_lgbm_class_1': 0.8005882595072171, 'weight_lgbm_class_2': 0.3854692938229508, 'weight_xgb_class_0': 0.03811879271608237, 'weight_xgb_class_1': 0.851221348349437, 'weight_xgb_class_2': 0.9581351766189691}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  34%|█████████████████████████████████████████████▌                                                                                      | 690/2000 [00:17<00:36, 35.42it/s]

[I 2026-07-05 15:31:48,621] Trial 682 finished with value: 0.9493192404649471 and parameters: {'weight_lgbm_class_0': 0.13142441769844693, 'weight_lgbm_class_1': 0.8455466626354203, 'weight_lgbm_class_2': 0.38541723290979485, 'weight_xgb_class_0': 0.04051807291637757, 'weight_xgb_class_1': 0.8567852614520935, 'weight_xgb_class_2': 0.9432842431941951}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:48,668] Trial 683 finished with value: 0.9489871551833273 and parameters: {'weight_lgbm_class_0': 0.13758412627937455, 'weight_lgbm_class_1': 0.8413565087949212, 'weight_lgbm_class_2': 0.32075019306118463, 'weight_xgb_class_0': 0.05020406354032291, 'weight_xgb_class_1': 0.8409465131824326, 'weight_xgb_class_2': 0.9938232931099157}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:48,696] Trial 685 finished with value: 0.9491926627926897 and parameters: {'weight_lgbm_class_0': 0.1309503883951512, 'weight_lgbm_class_1': 0.8427887883445456, 'weight_lgbm_class_2': 0.38187417749988856, 'weight_xgb_class_0': 0.05335654538652053, 'weight_xgb_class_1': 0.8403064930605887, 'weight_xgb_class_2': 0.9984637403147231}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:48,710] Trial 684 finished with value: 0.9476679729849676 and parameters: {'weight_lgbm_class_0': 0.12525858335581969, 'weight_lgbm_class_1': 0.8247035927170567, 'weight_lgbm_class_2': 0.38022328994599286, 'weight_xgb_class_0': 0.05431738340275494, 'weight_xgb_class_1': 0.13776579381617787, 'weight_xgb_class_2': 0.9552584348017429}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:48,731] Trial 686 finished with value: 0.9489986999766556 and parameters: {'weight_lgbm_class_0': 0.13408152823353953, 'weight_lgbm_class_1': 0.8118154890729523, 'weight_lgbm_class_2': 0.38087137418554734, 'weight_xgb_class_0': 0.05445311866261566, 'weight_xgb_class_1': 0.843112937275368, 'weight_xgb_class_2': 0.9555151521731408}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:48,748] Trial 687 finished with value: 0.9489919826107659 and parameters: {'weight_lgbm_class_0': 0.13052721821378901, 'weight_lgbm_class_1': 0.8543507451526934, 'weight_lgbm_class_2': 0.3806121891120754, 'weight_xgb_class_0': 0.05738083982615377, 'weight_xgb_class_1': 0.8550434290921061, 'weight_xgb_class_2': 0.9535847588245783}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:48,795] Trial 689 finished with value: 0.9490836556288702 and parameters: {'weight_lgbm_class_0': 0.13155209239970558, 'weight_lgbm_class_1': 0.8132063421140054, 'weight_lgbm_class_2': 0.3759857214709814, 'weight_xgb_class_0': 0.05756704012380853, 'weight_xgb_class_1': 0.8601344327525251, 'weight_xgb_class_2': 0.9943835420101246}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:48,831] Trial 688 finished with value: 0.949070155929366 and parameters: {'weight_lgbm_class_0': 0.1281031340118064, 'weight_lgbm_class_1': 0.8776977372956807, 'weight_lgbm_class_2': 0.3255041685327908, 'weight_xgb_class_0': 0.05689492043875972, 'weight_xgb_class_1': 0.8585757381464258, 'weight_xgb_class_2': 0.9966139107340916}. Best is trial 358 with value: 0.9497927483550862.

[I 2026-07-05 15:31:48,886] Trial 690 finished with value: 0.9490146600961777 and parameters: {'weight_lgbm_class_0': 0.13115766386707375, 'weight_lgbm_class_1': 0.8808886685737155, 'weight_lgbm_class_2': 0.3281394871459113, 'weight_xgb_class_0': 0.05762233654581977, 'weight_xgb_class_1': 0.8592267557054178, 'weight_xgb_class_2': 0.9987405789898065}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:48,936] Trial 691 finished with value: 0.9497107343090433 and parameters: {'weight_lgbm_class_0': 0.07205762188908998, 'weight_lgbm_class_1': 0.8773263106288515, 'weight_lgbm_class_2': 0.3293334631977786, 'weight_xgb_class_0': 0.05968525836098357, 'weight_xgb_class_1': 0.8357147556050285, 'weight_xgb_class_2': 0.9518739594756754}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:48,971] Trial 693 finished with value: 0.9491842303070185 and parameters: {'weight_lgbm_class_0': 0.07306616498284174, 'weight_lgbm_class_1': 0.8809494245255433, 'weight_lgbm_class_2': 0.3287670228671321, 'weight_xgb_class_0': 0.00047664278991256005, 'weight_xgb_class_1': 0.8335202315814193, 'weight_xgb_class_2': 0.9437337374792331}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:48,990] Trial 692 finished with value: 0.9496473031846837 and parameters: {'weight_lgbm_class_0': 0.07422785553548727, 'weight_lgbm_class_1': 0.8687484363345328, 'weight_lgbm_class_2': 0.32600175532536185, 'weight_xgb_class_0': 0.061131093423627776, 'weight_xgb_class_1': 0.764586608746064, 'weight_xgb_class_2': 0.9491617577902511}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:49,026] Trial 694 finished with value: 0.9497189203680284 and parameters: {'weight_lgbm_class_0': 0.06527317753653025, 'weight_lgbm_class_1': 0.8814971460808458, 'weight_lgbm_class_2': 0.32897297048741936, 'weight_xgb_class_0': 0.06367898777824268, 'weight_xgb_class_1': 0.8339103189394818, 'weight_xgb_class_2': 0.9497397923696224}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:49,034] Trial 695 finished with value: 0.9496518229106772 and parameters: {'weight_lgbm_class_0': 0.07609468017001125, 'weight_lgbm_class_1': 0.8852346222746069, 'weight_lgbm_class_2': 0.3293244296482511, 'weight_xgb_class_0': 0.01741583182266079, 'weight_xgb_class_1': 0.8302362339606367, 'weight_xgb_class_2': 0.9506491519442787}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:49,066] Trial 696 finished with value: 0.9470250076684171 and parameters: {'weight_lgbm_class_0': 0.07227061712778746, 'weight_lgbm_class_1': 0.8716756866065368, 'weight_lgbm_class_2': 0.3302786800987769, 'weight_xgb_class_0': 0.00035866551850351897, 'weight_xgb_class_1': 0.7693055125190189, 'weight_xgb_class_2': 0.008263632846729985}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  35%|██████████████████████████████████████████████▍                                                                                     | 703/2000 [00:17<00:40, 32.15it/s]

[I 2026-07-05 15:31:49,081] Trial 697 finished with value: 0.9491521269869421 and parameters: {'weight_lgbm_class_0': 0.07111346211045325, 'weight_lgbm_class_1': 0.8805832179326324, 'weight_lgbm_class_2': 0.3263895623329747, 'weight_xgb_class_0': 2.5425061161012813e-05, 'weight_xgb_class_1': 0.7669400452695044, 'weight_xgb_class_2': 0.9248582539202735}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:49,122] Trial 698 finished with value: 0.9493049286862373 and parameters: {'weight_lgbm_class_0': 0.07369668994969263, 'weight_lgbm_class_1': 0.8693922847459374, 'weight_lgbm_class_2': 0.32739319005452405, 'weight_xgb_class_0': 0.001826395352476723, 'weight_xgb_class_1': 0.7688193767280724, 'weight_xgb_class_2': 0.9275816095950065}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:49,149] Trial 700 finished with value: 0.9491401011797413 and parameters: {'weight_lgbm_class_0': 0.06910851847115493, 'weight_lgbm_class_1': 0.8842500449796472, 'weight_lgbm_class_2': 0.3215771992309851, 'weight_xgb_class_0': 0.001536869711866784, 'weight_xgb_class_1': 0.7680045156250089, 'weight_xgb_class_2': 0.9202470725851614}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:49,165] Trial 699 finished with value: 0.9491667285056146 and parameters: {'weight_lgbm_class_0': 0.07199758134614444, 'weight_lgbm_class_1': 0.8826291163875342, 'weight_lgbm_class_2': 0.32557340942040297, 'weight_xgb_class_0': 0.0004061441723767212, 'weight_xgb_class_1': 0.8240700439593762, 'weight_xgb_class_2': 0.9305018811899508}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:49,204] Trial 701 finished with value: 0.9225392537207696 and parameters: {'weight_lgbm_class_0': 0.07303032989038166, 'weight_lgbm_class_1': 0.882651336038945, 'weight_lgbm_class_2': 0.32677194176780533, 'weight_xgb_class_0': 0.6191958062725276, 'weight_xgb_class_1': 0.7695143569755296, 'weight_xgb_class_2': 0.944372234929097}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:49,265] Trial 702 finished with value: 0.9493975137167472 and parameters: {'weight_lgbm_class_0': 0.06205124793165115, 'weight_lgbm_class_1': 0.8799592217044493, 'weight_lgbm_class_2': 0.30848578312616326, 'weight_xgb_class_0': 0.01712390344903533, 'weight_xgb_class_1': 0.8270860362879182, 'weight_xgb_class_2': 0.9264099016463814}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:49,288] Trial 703 finished with value: 0.9496368638267564 and parameters: {'weight_lgbm_class_0': 0.07263338329523494, 'weight_lgbm_class_1': 0.8895308321900941, 'weight_lgbm_class_2': 0.30274531597917287, 'weight_xgb_class_0': 0.01780376223995611, 'weight_xgb_class_1': 0.7690522688274624, 'weight_xgb_class_2': 0.9289372759405279}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  36%|██████████████████████████████████████████████▉                                                                                     | 711/2000 [00:18<00:38, 33.06it/s]

[I 2026-07-05 15:31:49,326] Trial 704 finished with value: 0.9494148193891306 and parameters: {'weight_lgbm_class_0': 0.07986999040002442, 'weight_lgbm_class_1': 0.9226080753600675, 'weight_lgbm_class_2': 0.30353055360002823, 'weight_xgb_class_0': 0.00029582322444683044, 'weight_xgb_class_1': 0.8177881771084146, 'weight_xgb_class_2': 0.9260163911535129}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:49,374] Trial 705 finished with value: 0.949639798534916 and parameters: {'weight_lgbm_class_0': 0.08167826649494306, 'weight_lgbm_class_1': 0.9270291743847353, 'weight_lgbm_class_2': 0.30601269393995345, 'weight_xgb_class_0': 0.01676496961313747, 'weight_xgb_class_1': 0.8117867225378181, 'weight_xgb_class_2': 0.9257355041670827}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:49,400] Trial 706 finished with value: 0.9496033154988947 and parameters: {'weight_lgbm_class_0': 0.0789098196281782, 'weight_lgbm_class_1': 0.9176123147312871, 'weight_lgbm_class_2': 0.30826982045560086, 'weight_xgb_class_0': 0.015904147277947568, 'weight_xgb_class_1': 0.8112252693834437, 'weight_xgb_class_2': 0.9209355995142909}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:49,429] Trial 708 finished with value: 0.9483408163280678 and parameters: {'weight_lgbm_class_0': 0.19377427359328095, 'weight_lgbm_class_1': 0.9187095765220974, 'weight_lgbm_class_2': 0.30138905205924316, 'weight_xgb_class_0': 0.01979812192387495, 'weight_xgb_class_1': 0.8113185134231609, 'weight_xgb_class_2': 0.9255855429590961}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:49,444] Trial 707 finished with value: 0.9237327045338118 and parameters: {'weight_lgbm_class_0': 0.18589269225723826, 'weight_lgbm_class_1': 0.9211263526021679, 'weight_lgbm_class_2': 0.2945152694263155, 'weight_xgb_class_0': 0.48244288851358025, 'weight_xgb_class_1': 0.8130586053836131, 'weight_xgb_class_2': 0.930555480783791}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:49,477] Trial 710 finished with value: 0.9093636320438633 and parameters: {'weight_lgbm_class_0': 0.8625830462144154, 'weight_lgbm_class_1': 0.9265326600798688, 'weight_lgbm_class_2': 0.29453537094057414, 'weight_xgb_class_0': 0.016746835118257093, 'weight_xgb_class_1': 0.8125372363619849, 'weight_xgb_class_2': 0.9236843633604379}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:49,503] Trial 709 finished with value: 0.9063969019292607 and parameters: {'weight_lgbm_class_0': 0.8520362684111047, 'weight_lgbm_class_1': 0.9220018112985857, 'weight_lgbm_class_2': 0.3047749306724422, 'weight_xgb_class_0': 0.019292519725681634, 'weight_xgb_class_1': 0.8945833089119797, 'weight_xgb_class_2': 0.7670168196981397}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  36%|███████████████████████████████████████████████▎                                                                                    | 717/2000 [00:18<00:42, 30.28it/s]

[I 2026-07-05 15:31:49,544] Trial 711 finished with value: 0.8999253687181907 and parameters: {'weight_lgbm_class_0': 0.19127589918987914, 'weight_lgbm_class_1': 0.9226640928573298, 'weight_lgbm_class_2': 0.3017562343883232, 'weight_xgb_class_0': 0.8140211263881375, 'weight_xgb_class_1': 0.8085365910520899, 'weight_xgb_class_2': 0.8645834538754369}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:49,563] Trial 712 finished with value: 0.9497456203048132 and parameters: {'weight_lgbm_class_0': 0.09041676801987406, 'weight_lgbm_class_1': 0.920606547549389, 'weight_lgbm_class_2': 0.30050145152150365, 'weight_xgb_class_0': 0.01960725252760292, 'weight_xgb_class_1': 0.8919158728887648, 'weight_xgb_class_2': 0.8652601093861131}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:49,601] Trial 713 finished with value: 0.9489323444296468 and parameters: {'weight_lgbm_class_0': 0.04048004944357954, 'weight_lgbm_class_1': 0.9227726631000629, 'weight_lgbm_class_2': 0.3085227205777875, 'weight_xgb_class_0': 0.023896934360892283, 'weight_xgb_class_1': 0.8092765444277501, 'weight_xgb_class_2': 0.8630377026253644}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:49,653] Trial 714 finished with value: 0.9482904686230121 and parameters: {'weight_lgbm_class_0': 0.1984964444220108, 'weight_lgbm_class_1': 0.918777232071238, 'weight_lgbm_class_2': 0.351755418473129, 'weight_xgb_class_0': 0.02128020535799424, 'weight_xgb_class_1': 0.8935281673716893, 'weight_xgb_class_2': 0.8613110875407}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:49,674] Trial 715 finished with value: 0.949679947595539 and parameters: {'weight_lgbm_class_0': 0.11576526537767332, 'weight_lgbm_class_1': 0.9232667739996442, 'weight_lgbm_class_2': 0.35375609671719577, 'weight_xgb_class_0': 0.019498472423295863, 'weight_xgb_class_1': 0.7939282735407124, 'weight_xgb_class_2': 0.8676689301880518}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:49,697] Trial 716 finished with value: 0.9496556635633171 and parameters: {'weight_lgbm_class_0': 0.11858435044445949, 'weight_lgbm_class_1': 0.9997385601100743, 'weight_lgbm_class_2': 0.35847345353566684, 'weight_xgb_class_0': 0.020337503043266963, 'weight_xgb_class_1': 0.7932588655760294, 'weight_xgb_class_2': 0.8622004771155852}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:49,748] Trial 717 finished with value: 0.9488439686935272 and parameters: {'weight_lgbm_class_0': 0.11136491812715892, 'weight_lgbm_class_1': 0.9208093395782169, 'weight_lgbm_class_2': 0.3642807332260572, 'weight_xgb_class_0': 0.08012365595451935, 'weight_xgb_class_1': 0.89236686393943, 'weight_xgb_class_2': 0.8703918785478958}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  36%|███████████████████████████████████████████████▊                                                                                    | 725/2000 [00:18<00:39, 32.21it/s]

[I 2026-07-05 15:31:49,795] Trial 718 finished with value: 0.9453564931553329 and parameters: {'weight_lgbm_class_0': 0.03666932380472673, 'weight_lgbm_class_1': 0.9567527132378337, 'weight_lgbm_class_2': 0.3617869187555384, 'weight_xgb_class_0': 0.07922899033974638, 'weight_xgb_class_1': 0.7917598382797981, 'weight_xgb_class_2': 0.05815332570355741}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:49,820] Trial 719 finished with value: 0.9486936060445235 and parameters: {'weight_lgbm_class_0': 0.11330758382358132, 'weight_lgbm_class_1': 0.9998208692220749, 'weight_lgbm_class_2': 0.36158376237955175, 'weight_xgb_class_0': 0.0840998594913788, 'weight_xgb_class_1': 0.7912402805779081, 'weight_xgb_class_2': 0.8663009684880052}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:49,828] Trial 720 finished with value: 0.9487554919532853 and parameters: {'weight_lgbm_class_0': 0.11469576305325092, 'weight_lgbm_class_1': 0.95426802390174, 'weight_lgbm_class_2': 0.36068747913135896, 'weight_xgb_class_0': 0.07870480005081662, 'weight_xgb_class_1': 0.7889041147020164, 'weight_xgb_class_2': 0.8637243311526802}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:49,878] Trial 721 finished with value: 0.9496645979523809 and parameters: {'weight_lgbm_class_0': 0.11270299850485727, 'weight_lgbm_class_1': 0.954722706515153, 'weight_lgbm_class_2': 0.36960509880722003, 'weight_xgb_class_0': 0.026078248893028448, 'weight_xgb_class_1': 0.7921551573383416, 'weight_xgb_class_2': 0.860508525815866}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:49,893] Trial 722 finished with value: 0.9496685176207068 and parameters: {'weight_lgbm_class_0': 0.11665736340284853, 'weight_lgbm_class_1': 0.9568022265642934, 'weight_lgbm_class_2': 0.35493991924675644, 'weight_xgb_class_0': 0.025294078920419984, 'weight_xgb_class_1': 0.7920050149513975, 'weight_xgb_class_2': 0.8677013275850739}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:49,933] Trial 723 finished with value: 0.948751988331107 and parameters: {'weight_lgbm_class_0': 0.11323328268968104, 'weight_lgbm_class_1': 0.9035652944299546, 'weight_lgbm_class_2': 0.35622319738381025, 'weight_xgb_class_0': 0.07888075451817331, 'weight_xgb_class_1': 0.8813477831729893, 'weight_xgb_class_2': 0.8559339803889365}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:49,947] Trial 725 finished with value: 0.9497183875372163 and parameters: {'weight_lgbm_class_0': 0.03646076499044798, 'weight_lgbm_class_1': 0.9044304668262118, 'weight_lgbm_class_2': 0.361121705660411, 'weight_xgb_class_0': 0.0893752272820483, 'weight_xgb_class_1': 0.8660339941185212, 'weight_xgb_class_2': 0.8631349537784435}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:49,954] Trial 724 finished with value: 0.948966406415023 and parameters: {'weight_lgbm_class_0': 0.03254165678028859, 'weight_lgbm_class_1': 0.9554808510753476, 'weight_lgbm_class_2': 0.36056922979678335, 'weight_xgb_class_0': 0.08464949347171125, 'weight_xgb_class_1': 0.8639080621407027, 'weight_xgb_class_2': 0.3609848458814078}. Best is trial 358 with value: 0.9497927483550862.

[I 2026-07-05 15:31:50,026] Trial 726 finished with value: 0.9497159264386474 and parameters: {'weight_lgbm_class_0': 0.047228809937722355, 'weight_lgbm_class_1': 0.8579258264040548, 'weight_lgbm_class_2': 0.3645748088741006, 'weight_xgb_class_0': 0.08022400594551465, 'weight_xgb_class_1': 0.8909083228063871, 'weight_xgb_class_2': 0.8794720787254335}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:50,086] Trial 727 finished with value: 0.9497545403582714 and parameters: {'weight_lgbm_class_0': 0.044593666685515954, 'weight_lgbm_class_1': 0.8570883685772976, 'weight_lgbm_class_2': 0.3682431333941024, 'weight_xgb_class_0': 0.08138424631677289, 'weight_xgb_class_1': 0.8957342474300277, 'weight_xgb_class_2': 0.879445023508007}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:50,091] Trial 728 finished with value: 0.9489654468674299 and parameters: {'weight_lgbm_class_0': 0.04745330878873166, 'weight_lgbm_class_1': 0.9047678957891632, 'weight_lgbm_class_2': 0.3630700429701207, 'weight_xgb_class_0': 0.09008802520095971, 'weight_xgb_class_1': 0.8982354564258193, 'weight_xgb_class_2': 0.5050657538781199}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:50,116] Trial 729 finished with value: 0.9491394841953404 and parameters: {'weight_lgbm_class_0': 0.04909830737797796, 'weight_lgbm_class_1': 0.8588274779638709, 'weight_lgbm_class_2': 0.36332575299062675, 'weight_xgb_class_0': 0.08099878707411858, 'weight_xgb_class_1': 0.8979727877196915, 'weight_xgb_class_2': 0.513457783218567}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:50,153] Trial 731 finished with value: 0.9070141371952559 and parameters: {'weight_lgbm_class_0': 0.051010602129164195, 'weight_lgbm_class_1': 0.8984897375132277, 'weight_lgbm_class_2': 0.4001022909452245, 'weight_xgb_class_0': 0.9075086025387091, 'weight_xgb_class_1': 0.8823761560476884, 'weight_xgb_class_2': 0.8855792756072047}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:50,173] Trial 730 finished with value: 0.9497610162650264 and parameters: {'weight_lgbm_class_0': 0.08904907918098598, 'weight_lgbm_class_1': 0.8966064498308166, 'weight_lgbm_class_2': 0.40376983247845716, 'weight_xgb_class_0': 0.0376925398267404, 'weight_xgb_class_1': 0.8787513019585321, 'weight_xgb_class_2': 0.8827322373100978}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:50,183] Trial 732 finished with value: 0.9204300396785582 and parameters: {'weight_lgbm_class_0': 0.7000079559956465, 'weight_lgbm_class_1': 0.8631441002681945, 'weight_lgbm_class_2': 0.4055972003931252, 'weight_xgb_class_0': 0.03690990290481519, 'weight_xgb_class_1': 0.8789473726211557, 'weight_xgb_class_2': 0.8796003092125133}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  37%|████████████████████████████████████████████████▊                                                                                   | 739/2000 [00:19<00:35, 35.36it/s]

[I 2026-07-05 15:31:50,212] Trial 733 finished with value: 0.9497260536772693 and parameters: {'weight_lgbm_class_0': 0.0906908999994373, 'weight_lgbm_class_1': 0.8963633969547472, 'weight_lgbm_class_2': 0.4103548586669768, 'weight_xgb_class_0': 0.04161233495957723, 'weight_xgb_class_1': 0.8682395293770474, 'weight_xgb_class_2': 0.8876193459661621}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:50,258] Trial 734 finished with value: 0.905235427945667 and parameters: {'weight_lgbm_class_0': 0.04703332045011206, 'weight_lgbm_class_1': 0.8567230260997148, 'weight_lgbm_class_2': 0.40021805948400724, 'weight_xgb_class_0': 0.9296419564195946, 'weight_xgb_class_1': 0.8749227875454508, 'weight_xgb_class_2': 0.8856616189662393}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:50,288] Trial 735 finished with value: 0.949700298027302 and parameters: {'weight_lgbm_class_0': 0.08981254601640132, 'weight_lgbm_class_1': 0.8564631130505971, 'weight_lgbm_class_2': 0.39870445049489417, 'weight_xgb_class_0': 0.04193927586689357, 'weight_xgb_class_1': 0.882102429574412, 'weight_xgb_class_2': 0.8840063955144389}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:50,308] Trial 736 finished with value: 0.9497188042619148 and parameters: {'weight_lgbm_class_0': 0.09094269657038143, 'weight_lgbm_class_1': 0.8557936573448086, 'weight_lgbm_class_2': 0.40379349564845834, 'weight_xgb_class_0': 0.04329811790869291, 'weight_xgb_class_1': 0.892828565688272, 'weight_xgb_class_2': 0.8901217133254938}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:50,317] Trial 737 finished with value: 0.9047533038667265 and parameters: {'weight_lgbm_class_0': 0.09398885255105899, 'weight_lgbm_class_1': 0.8610802632659496, 'weight_lgbm_class_2': 0.40870765730965286, 'weight_xgb_class_0': 0.8998559294537365, 'weight_xgb_class_1': 0.8955366577928675, 'weight_xgb_class_2': 0.8861757765582916}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:50,345] Trial 738 finished with value: 0.8756507458742827 and parameters: {'weight_lgbm_class_0': 0.7051479784104103, 'weight_lgbm_class_1': 0.905714205725399, 'weight_lgbm_class_2': 0.4085036422478981, 'weight_xgb_class_0': 0.9313970818327719, 'weight_xgb_class_1': 0.8729912964041121, 'weight_xgb_class_2': 0.8917918361933925}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:50,419] Trial 739 finished with value: 0.9492674666011207 and parameters: {'weight_lgbm_class_0': 0.0285471950887594, 'weight_lgbm_class_1': 0.8619298242732714, 'weight_lgbm_class_2': 0.40481850146368714, 'weight_xgb_class_0': 0.048573459471952886, 'weight_xgb_class_1': 0.9065419998567295, 'weight_xgb_class_2': 0.8887084442243048}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  37%|█████████████████████████████████████████████████▎                                                                                  | 748/2000 [00:19<00:35, 35.53it/s]

[I 2026-07-05 15:31:50,431] Trial 740 finished with value: 0.9034670302748897 and parameters: {'weight_lgbm_class_0': 0.05426445441892906, 'weight_lgbm_class_1': 0.8262112201575305, 'weight_lgbm_class_2': 0.3973174815367145, 'weight_xgb_class_0': 0.9401229666711088, 'weight_xgb_class_1': 0.8754359079829497, 'weight_xgb_class_2': 0.8847998230233374}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:50,442] Trial 741 finished with value: 0.9496622665836684 and parameters: {'weight_lgbm_class_0': 0.09008460264526635, 'weight_lgbm_class_1': 0.8615851814172425, 'weight_lgbm_class_2': 0.4218353743347356, 'weight_xgb_class_0': 0.04798495569272645, 'weight_xgb_class_1': 0.8744010247202989, 'weight_xgb_class_2': 0.896912319899795}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:50,498] Trial 742 finished with value: 0.9132595112465344 and parameters: {'weight_lgbm_class_0': 0.488440387924733, 'weight_lgbm_class_1': 0.8620814944145444, 'weight_lgbm_class_2': 0.3978181259213238, 'weight_xgb_class_0': 0.3625220100162892, 'weight_xgb_class_1': 0.8763185359520953, 'weight_xgb_class_2': 0.8886721177374695}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:50,524] Trial 743 finished with value: 0.94968012738176 and parameters: {'weight_lgbm_class_0': 0.08651272351201517, 'weight_lgbm_class_1': 0.8281688684800028, 'weight_lgbm_class_2': 0.40439538381205575, 'weight_xgb_class_0': 0.059234854938898795, 'weight_xgb_class_1': 0.9042928477318662, 'weight_xgb_class_2': 0.889001566416036}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:50,560] Trial 744 finished with value: 0.9497599983726425 and parameters: {'weight_lgbm_class_0': 0.05438456462833516, 'weight_lgbm_class_1': 0.8146718560958062, 'weight_lgbm_class_2': 0.39726932738915544, 'weight_xgb_class_0': 0.06428891336447484, 'weight_xgb_class_1': 0.8846313274749866, 'weight_xgb_class_2': 0.8895876090914875}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:50,562] Trial 745 finished with value: 0.9497391650226098 and parameters: {'weight_lgbm_class_0': 0.0538071103273183, 'weight_lgbm_class_1': 0.8551827114933537, 'weight_lgbm_class_2': 0.3982673316056009, 'weight_xgb_class_0': 0.06855598737053586, 'weight_xgb_class_1': 0.9045317745986223, 'weight_xgb_class_2': 0.8914496242049319}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:50,593] Trial 746 finished with value: 0.9492140800042742 and parameters: {'weight_lgbm_class_0': 0.08523822390647423, 'weight_lgbm_class_1': 0.8265712081593457, 'weight_lgbm_class_2': 0.39460765617601157, 'weight_xgb_class_0': 0.06513686566401353, 'weight_xgb_class_1': 0.2458679485885521, 'weight_xgb_class_2': 0.8925784656764921}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:50,610] Trial 747 finished with value: 0.9497173999197644 and parameters: {'weight_lgbm_class_0': 0.06169568579758511, 'weight_lgbm_class_1': 0.8212295001436749, 'weight_lgbm_class_2': 0.396853957352879, 'weight_xgb_class_0': 0.059774732417046825, 'weight_xgb_class_1': 0.8925846922328743, 'weight_xgb_class_2': 0.8965740611653031}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:50,643] Trial 748 finished with value: 0.9497197419875697 and parameters: {'weight_lgbm_class_0': 0.05727532065021504, 'weight_lgbm_class_1': 0.8248833597734968, 'weight_lgbm_class_2': 0.3889753516507483, 'weight_xgb_class_0': 0.06312744023684518, 'weight_xgb_class_1': 0.9078949774258315, 'weight_xgb_class_2': 0.9047710092639998}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  38%|█████████████████████████████████████████████████▊                                                                                  | 755/2000 [00:19<00:37, 33.42it/s]

[I 2026-07-05 15:31:50,665] Trial 749 finished with value: 0.9496272690487858 and parameters: {'weight_lgbm_class_0': 0.03414017732685086, 'weight_lgbm_class_1': 0.8134526868951586, 'weight_lgbm_class_2': 0.3867711249347907, 'weight_xgb_class_0': 0.06178022637641971, 'weight_xgb_class_1': 0.9001678870753899, 'weight_xgb_class_2': 0.8523426176010857}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:50,690] Trial 750 finished with value: 0.9406473718073588 and parameters: {'weight_lgbm_class_0': 0.026561603648904086, 'weight_lgbm_class_1': 0.8338709334014017, 'weight_lgbm_class_2': 0.38958897249966534, 'weight_xgb_class_0': 0.3860790150222698, 'weight_xgb_class_1': 0.9096758147826507, 'weight_xgb_class_2': 0.8479255776751311}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:50,756] Trial 751 finished with value: 0.9497357747257172 and parameters: {'weight_lgbm_class_0': 0.05684533975852524, 'weight_lgbm_class_1': 0.8272201572629536, 'weight_lgbm_class_2': 0.3778804404371684, 'weight_xgb_class_0': 0.06859680461666925, 'weight_xgb_class_1': 0.9155318591824708, 'weight_xgb_class_2': 0.8481430585092725}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:50,793] Trial 752 finished with value: 0.9497430577108146 and parameters: {'weight_lgbm_class_0': 0.059084570015361354, 'weight_lgbm_class_1': 0.8835431625183244, 'weight_lgbm_class_2': 0.380374446050209, 'weight_xgb_class_0': 0.06599701198067204, 'weight_xgb_class_1': 0.8424541723863811, 'weight_xgb_class_2': 0.9086883650546578}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:50,806] Trial 753 finished with value: 0.9496273142761034 and parameters: {'weight_lgbm_class_0': 0.02863307443099765, 'weight_lgbm_class_1': 0.824275232630166, 'weight_lgbm_class_2': 0.37888597763251847, 'weight_xgb_class_0': 0.06798792376709405, 'weight_xgb_class_1': 0.9071181149959588, 'weight_xgb_class_2': 0.848887146360689}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:50,833] Trial 754 finished with value: 0.9263563384633503 and parameters: {'weight_lgbm_class_0': 0.406452512244495, 'weight_lgbm_class_1': 0.7876974536010699, 'weight_lgbm_class_2': 0.3785718254166077, 'weight_xgb_class_0': 0.06608409783880319, 'weight_xgb_class_1': 0.9025641314681618, 'weight_xgb_class_2': 0.45177661631248}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  38%|██████████████████████████████████████████████████▎                                                                                 | 762/2000 [00:19<00:33, 36.78it/s]

[I 2026-07-05 15:31:50,878] Trial 755 finished with value: 0.9491894372650002 and parameters: {'weight_lgbm_class_0': 0.05520648836662492, 'weight_lgbm_class_1': 0.8927584661120398, 'weight_lgbm_class_2': 0.3385410714844124, 'weight_xgb_class_0': 0.06118946594197351, 'weight_xgb_class_1': 0.8397210816275398, 'weight_xgb_class_2': 0.4564522617239645}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:50,900] Trial 756 finished with value: 0.9495091922121045 and parameters: {'weight_lgbm_class_0': 0.05521977363940367, 'weight_lgbm_class_1': 0.806253811205531, 'weight_lgbm_class_2': 0.37950966576433354, 'weight_xgb_class_0': 0.09996675496655993, 'weight_xgb_class_1': 0.9021099637546331, 'weight_xgb_class_2': 0.8456211468947429}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:50,915] Trial 757 finished with value: 0.9497384048703889 and parameters: {'weight_lgbm_class_0': 0.025615505099421496, 'weight_lgbm_class_1': 0.9053418814093417, 'weight_lgbm_class_2': 0.42798541678018104, 'weight_xgb_class_0': 0.10098191488383024, 'weight_xgb_class_1': 0.9131384913165785, 'weight_xgb_class_2': 0.8478028578562111}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:50,937] Trial 758 finished with value: 0.9497240111383111 and parameters: {'weight_lgbm_class_0': 0.022028442461023534, 'weight_lgbm_class_1': 0.8873381612166867, 'weight_lgbm_class_2': 0.37027492074341, 'weight_xgb_class_0': 0.10310521357595431, 'weight_xgb_class_1': 0.9134804653307518, 'weight_xgb_class_2': 0.8450439681033028}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:50,957] Trial 759 finished with value: 0.949696250533517 and parameters: {'weight_lgbm_class_0': 0.035344290335478666, 'weight_lgbm_class_1': 0.818146223305625, 'weight_lgbm_class_2': 0.42460165068703487, 'weight_xgb_class_0': 0.10568213372067227, 'weight_xgb_class_1': 0.9117153003012337, 'weight_xgb_class_2': 0.8463266494604181}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:50,962] Trial 760 finished with value: 0.949764518188401 and parameters: {'weight_lgbm_class_0': 0.022462995995211725, 'weight_lgbm_class_1': 0.897744984965029, 'weight_lgbm_class_2': 0.4273253929078732, 'weight_xgb_class_0': 0.10373588112843528, 'weight_xgb_class_1': 0.8400192025375863, 'weight_xgb_class_2': 0.8497754872602031}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:51,005] Trial 761 finished with value: 0.9496925746321961 and parameters: {'weight_lgbm_class_0': 0.02531813948674282, 'weight_lgbm_class_1': 0.8925010807938895, 'weight_lgbm_class_2': 0.42161019497241914, 'weight_xgb_class_0': 0.10666629365731677, 'weight_xgb_class_1': 0.9119990736522462, 'weight_xgb_class_2': 0.847969408658019}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:51,037] Trial 762 finished with value: 0.9497592200760216 and parameters: {'weight_lgbm_class_0': 0.02644538628138761, 'weight_lgbm_class_1': 0.8915599932953144, 'weight_lgbm_class_2': 0.4273417167395882, 'weight_xgb_class_0': 0.09756397963765936, 'weight_xgb_class_1': 0.8478078712247176, 'weight_xgb_class_2': 0.8454641935823772}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  38%|██████████████████████████████████████████████████▊                                                                                 | 770/2000 [00:19<00:37, 32.99it/s]

[I 2026-07-05 15:31:51,082] Trial 763 finished with value: 0.9497497553362972 and parameters: {'weight_lgbm_class_0': 0.020616688457781696, 'weight_lgbm_class_1': 0.8057346727203435, 'weight_lgbm_class_2': 0.37513607416848394, 'weight_xgb_class_0': 0.10279040398641828, 'weight_xgb_class_1': 0.8503863577887186, 'weight_xgb_class_2': 0.8490436993273313}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:51,144] Trial 764 finished with value: 0.9497279385810798 and parameters: {'weight_lgbm_class_0': 0.0303141602895107, 'weight_lgbm_class_1': 0.8907452974353822, 'weight_lgbm_class_2': 0.42885882664486735, 'weight_xgb_class_0': 0.08987102321083995, 'weight_xgb_class_1': 0.8547280850989101, 'weight_xgb_class_2': 0.8663034555752689}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:51,192] Trial 765 finished with value: 0.9496962732603453 and parameters: {'weight_lgbm_class_0': 0.03993303788069072, 'weight_lgbm_class_1': 0.8027668496848354, 'weight_lgbm_class_2': 0.43055560355372496, 'weight_xgb_class_0': 0.09013384732890102, 'weight_xgb_class_1': 0.8528268316463503, 'weight_xgb_class_2': 0.8725352925337385}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:51,197] Trial 766 finished with value: 0.9497132533412165 and parameters: {'weight_lgbm_class_0': 0.027305321452488894, 'weight_lgbm_class_1': 0.7766647530442907, 'weight_lgbm_class_2': 0.4292339009406859, 'weight_xgb_class_0': 0.10341324546913742, 'weight_xgb_class_1': 0.8570547481394937, 'weight_xgb_class_2': 0.8700501302637761}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:51,225] Trial 767 finished with value: 0.9496709473830652 and parameters: {'weight_lgbm_class_0': 0.026240961011363497, 'weight_lgbm_class_1': 0.8059502556134239, 'weight_lgbm_class_2': 0.37294886345765726, 'weight_xgb_class_0': 0.10475874249041155, 'weight_xgb_class_1': 0.8396367930478049, 'weight_xgb_class_2': 0.91217940283787}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:51,255] Trial 768 finished with value: 0.9493248242768377 and parameters: {'weight_lgbm_class_0': 0.03181404302132968, 'weight_lgbm_class_1': 0.8891500202817385, 'weight_lgbm_class_2': 0.3716316680916273, 'weight_xgb_class_0': 0.1312906093503463, 'weight_xgb_class_1': 0.857944794851984, 'weight_xgb_class_2': 0.8721545467503355}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:51,271] Trial 769 finished with value: 0.9497641305127882 and parameters: {'weight_lgbm_class_0': 0.025761798920975076, 'weight_lgbm_class_1': 0.8900727970804498, 'weight_lgbm_class_2': 0.43376269072052137, 'weight_xgb_class_0': 0.09389888549181129, 'weight_xgb_class_1': 0.8595764920879412, 'weight_xgb_class_2': 0.8679275956957466}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:51,274] Trial 770 finished with value: 0.9497117027208168 and parameters: {'weight_lgbm_class_0': 0.0346882781621637, 'weight_lgbm_class_1': 0.7915801590193017, 'weight_lgbm_class_2': 0.43204340065569374, 'weight_xgb_class_0': 0.09152286039447352, 'weight_xgb_class_1': 0.8627994727223943, 'weight_xgb_class_2': 0.868409631009236}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  39%|███████████████████████████████████████████████████▏                                                                                | 776/2000 [00:20<00:31, 38.58it/s]

[I 2026-07-05 15:31:51,288] Trial 772 finished with value: 0.9496677112209154 and parameters: {'weight_lgbm_class_0': 0.035508405481047625, 'weight_lgbm_class_1': 0.7788641446149229, 'weight_lgbm_class_2': 0.37153773990733946, 'weight_xgb_class_0': 0.11128114020973737, 'weight_xgb_class_1': 0.8590579377191034, 'weight_xgb_class_2': 0.8741901438754306}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:51,291] Trial 771 finished with value: 0.9496655541308258 and parameters: {'weight_lgbm_class_0': 0.01907105900612838, 'weight_lgbm_class_1': 0.7736331638514808, 'weight_lgbm_class_2': 0.42632883599328525, 'weight_xgb_class_0': 0.11105833659641841, 'weight_xgb_class_1': 0.8594849222853982, 'weight_xgb_class_2': 0.8126414373435815}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:51,316] Trial 773 finished with value: 0.9497230037394266 and parameters: {'weight_lgbm_class_0': 0.01591898595485572, 'weight_lgbm_class_1': 0.874994451647848, 'weight_lgbm_class_2': 0.42551673800570683, 'weight_xgb_class_0': 0.09370492899365275, 'weight_xgb_class_1': 0.8517807414917702, 'weight_xgb_class_2': 0.867564232428622}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:51,362] Trial 774 finished with value: 0.9495696500316346 and parameters: {'weight_lgbm_class_0': 0.01646815296564262, 'weight_lgbm_class_1': 0.8879561881143689, 'weight_lgbm_class_2': 0.4307481841197544, 'weight_xgb_class_0': 0.14434696870609492, 'weight_xgb_class_1': 0.8663457104150252, 'weight_xgb_class_2': 0.869966612398381}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:51,415] Trial 775 finished with value: 0.9497461472863254 and parameters: {'weight_lgbm_class_0': 0.006887818916100651, 'weight_lgbm_class_1': 0.8081176925176676, 'weight_lgbm_class_2': 0.42117678320672236, 'weight_xgb_class_0': 0.09734135796257423, 'weight_xgb_class_1': 0.8661181521270372, 'weight_xgb_class_2': 0.8157904685363132}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:51,469] Trial 776 finished with value: 0.949675458568696 and parameters: {'weight_lgbm_class_0': 0.01173079399152252, 'weight_lgbm_class_1': 0.7889975763156184, 'weight_lgbm_class_2': 0.4494150269207668, 'weight_xgb_class_0': 0.13347273738353352, 'weight_xgb_class_1': 0.8623013300236244, 'weight_xgb_class_2': 0.8627602140420301}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  39%|███████████████████████████████████████████████████▉                                                                                | 786/2000 [00:20<00:34, 34.96it/s]

[I 2026-07-05 15:31:51,530] Trial 777 finished with value: 0.9495925313587387 and parameters: {'weight_lgbm_class_0': 0.03960973608446898, 'weight_lgbm_class_1': 0.8122578191794132, 'weight_lgbm_class_2': 0.4441779673534315, 'weight_xgb_class_0': 0.11413005209671064, 'weight_xgb_class_1': 0.8673712424116415, 'weight_xgb_class_2': 0.8102249885218687}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:51,534] Trial 778 finished with value: 0.949707925419149 and parameters: {'weight_lgbm_class_0': 0.006378416166540248, 'weight_lgbm_class_1': 0.7878861112693041, 'weight_lgbm_class_2': 0.44767147740052743, 'weight_xgb_class_0': 0.09572223535167765, 'weight_xgb_class_1': 0.8692944157065667, 'weight_xgb_class_2': 0.816016895713432}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:51,545] Trial 779 finished with value: 0.9496270191520848 and parameters: {'weight_lgbm_class_0': 0.009228333397145828, 'weight_lgbm_class_1': 0.7996196895813938, 'weight_lgbm_class_2': 0.4291271598524039, 'weight_xgb_class_0': 0.14260531372612573, 'weight_xgb_class_1': 0.8659027447021668, 'weight_xgb_class_2': 0.8274141657835906}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:51,604] Trial 780 finished with value: 0.9497476785775043 and parameters: {'weight_lgbm_class_0': 0.020125251911229804, 'weight_lgbm_class_1': 0.7745106980356538, 'weight_lgbm_class_2': 0.4208016833163676, 'weight_xgb_class_0': 0.10097825159939908, 'weight_xgb_class_1': 0.8775806050297966, 'weight_xgb_class_2': 0.8373500567685637}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:51,616] Trial 782 finished with value: 0.9497036639603337 and parameters: {'weight_lgbm_class_0': 0.012834413166592245, 'weight_lgbm_class_1': 0.7931650329279127, 'weight_lgbm_class_2': 0.4059447703510153, 'weight_xgb_class_0': 0.10591187226616429, 'weight_xgb_class_1': 0.8774052489386527, 'weight_xgb_class_2': 0.8551740415866664}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:51,621] Trial 781 finished with value: 0.9496917955209158 and parameters: {'weight_lgbm_class_0': 0.014780096827102306, 'weight_lgbm_class_1': 0.9041651058070638, 'weight_lgbm_class_2': 0.4391475353976631, 'weight_xgb_class_0': 0.13054422058013143, 'weight_xgb_class_1': 0.8727457459334111, 'weight_xgb_class_2': 0.8558815416504711}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:51,667] Trial 783 finished with value: 0.9496689931964659 and parameters: {'weight_lgbm_class_0': 0.012017210794271052, 'weight_lgbm_class_1': 0.7857995537471824, 'weight_lgbm_class_2': 0.45025656753665055, 'weight_xgb_class_0': 0.13500863740583532, 'weight_xgb_class_1': 0.8767947023554629, 'weight_xgb_class_2': 0.8339510476182288}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:51,675] Trial 786 finished with value: 0.9496824960184996 and parameters: {'weight_lgbm_class_0': 0.007056395560108206, 'weight_lgbm_class_1': 0.906964846836891, 'weight_lgbm_class_2': 0.4495982609516573, 'weight_xgb_class_0': 0.127415900817843, 'weight_xgb_class_1': 0.8773895923725411, 'weight_xgb_class_2': 0.8326963666969569}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:51,679] Trial 784 finished with value: 0.9496666233671918 and parameters: {'weight_lgbm_class_0': 0.0004143292412606761, 'weight_lgbm_class_1': 0.7880947699068306, 'weight_lgbm_class_2': 0.3482059503529006, 'weight_xgb_class_0': 0.13650624345060863, 'weight_xgb_class_1': 0.8809559619740185, 'weight_xgb_class_2': 0.8394659480705939}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:51,683] Trial 785 finished with value: 0.9496930394060655 and parameters: {'weight_lgbm_class_0': 0.006437775060659581, 'weight_lgbm_class_1': 0.9060684686616086, 'weight_lgbm_class_2': 0.41657606260941044, 'weight_xgb_class_0': 0.13191135893363076, 'weight_xgb_class_1': 0.8742674735502621, 'weight_xgb_class_2': 0.8387121158298743}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  40%|████████████████████████████████████████████████████▎                                                                               | 792/2000 [00:20<00:38, 31.64it/s]

[I 2026-07-05 15:31:51,744] Trial 787 finished with value: 0.9496723106073688 and parameters: {'weight_lgbm_class_0': 0.013570886000926312, 'weight_lgbm_class_1': 0.7973582393664116, 'weight_lgbm_class_2': 0.44153160617968235, 'weight_xgb_class_0': 0.12170755397423938, 'weight_xgb_class_1': 0.8858529646006473, 'weight_xgb_class_2': 0.8331122701249672}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:51,818] Trial 788 finished with value: 0.9497694995039634 and parameters: {'weight_lgbm_class_0': 0.009461035946611773, 'weight_lgbm_class_1': 0.78078916906884, 'weight_lgbm_class_2': 0.4524626966911994, 'weight_xgb_class_0': 0.10393217819689302, 'weight_xgb_class_1': 0.8820143932217391, 'weight_xgb_class_2': 0.822659548117042}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:51,876] Trial 790 finished with value: 0.9496798994435712 and parameters: {'weight_lgbm_class_0': 0.0002564372998460594, 'weight_lgbm_class_1': 0.7495004228541757, 'weight_lgbm_class_2': 0.4141671460892896, 'weight_xgb_class_0': 0.13045980715753067, 'weight_xgb_class_1': 0.8888207514865711, 'weight_xgb_class_2': 0.835839231270448}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:51,897] Trial 789 finished with value: 0.949656466840579 and parameters: {'weight_lgbm_class_0': 0.025734592283658222, 'weight_lgbm_class_1': 0.8433505329628238, 'weight_lgbm_class_2': 0.4464468024239854, 'weight_xgb_class_0': 0.12995518911778736, 'weight_xgb_class_1': 0.8414914234758788, 'weight_xgb_class_2': 0.8459686442763406}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:51,922] Trial 791 finished with value: 0.9497439864979517 and parameters: {'weight_lgbm_class_0': 0.01052068101143453, 'weight_lgbm_class_1': 0.7906561714777145, 'weight_lgbm_class_2': 0.45698585251098156, 'weight_xgb_class_0': 0.0980788759596136, 'weight_xgb_class_1': 0.8808737285546517, 'weight_xgb_class_2': 0.8414403513707905}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  40%|████████████████████████████████████████████████████▊                                                                               | 800/2000 [00:20<00:35, 33.87it/s]

[I 2026-07-05 15:31:51,964] Trial 792 finished with value: 0.9496977845027272 and parameters: {'weight_lgbm_class_0': 0.01671730432270173, 'weight_lgbm_class_1': 0.7510494697032623, 'weight_lgbm_class_2': 0.4535240646610418, 'weight_xgb_class_0': 0.12267257402969525, 'weight_xgb_class_1': 0.8865829321047566, 'weight_xgb_class_2': 0.7960492684536009}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:51,983] Trial 793 finished with value: 0.9496703833598646 and parameters: {'weight_lgbm_class_0': 0.004435484110279192, 'weight_lgbm_class_1': 0.7462150772967426, 'weight_lgbm_class_2': 0.44536520797222423, 'weight_xgb_class_0': 0.12923391267077577, 'weight_xgb_class_1': 0.8872820731230243, 'weight_xgb_class_2': 0.8247612446076317}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:52,005] Trial 794 finished with value: 0.9497194120809936 and parameters: {'weight_lgbm_class_0': 0.011027655616050477, 'weight_lgbm_class_1': 0.7385820807572613, 'weight_lgbm_class_2': 0.4586725542249757, 'weight_xgb_class_0': 0.1088855223400115, 'weight_xgb_class_1': 0.8855158010328166, 'weight_xgb_class_2': 0.8273608828606268}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:52,012] Trial 795 finished with value: 0.9497377252140327 and parameters: {'weight_lgbm_class_0': 0.006271155421602725, 'weight_lgbm_class_1': 0.7792780745917647, 'weight_lgbm_class_2': 0.453563230150469, 'weight_xgb_class_0': 0.1212442383876512, 'weight_xgb_class_1': 0.8920404472244933, 'weight_xgb_class_2': 0.8062743260319188}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:52,036] Trial 796 finished with value: 0.9494914160603738 and parameters: {'weight_lgbm_class_0': 0.029996440314099034, 'weight_lgbm_class_1': 0.7964086142838589, 'weight_lgbm_class_2': 0.4173696046260417, 'weight_xgb_class_0': 0.12393946599013121, 'weight_xgb_class_1': 0.8891284320917185, 'weight_xgb_class_2': 0.8040724223733094}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:52,080] Trial 797 finished with value: 0.9497200346878899 and parameters: {'weight_lgbm_class_0': 0.004199620037249208, 'weight_lgbm_class_1': 0.7319563769990355, 'weight_lgbm_class_2': 0.40078380860458, 'weight_xgb_class_0': 0.11284313500149155, 'weight_xgb_class_1': 0.8905008589221892, 'weight_xgb_class_2': 0.8267057156335949}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:52,118] Trial 799 finished with value: 0.9497409109496565 and parameters: {'weight_lgbm_class_0': 0.005232451089553093, 'weight_lgbm_class_1': 0.7627964111879214, 'weight_lgbm_class_2': 0.40981855526347927, 'weight_xgb_class_0': 0.09672572209435121, 'weight_xgb_class_1': 0.887429004512309, 'weight_xgb_class_2': 0.7932021155384708}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:52,133] Trial 798 finished with value: 0.9497051799289661 and parameters: {'weight_lgbm_class_0': 0.011329229150527384, 'weight_lgbm_class_1': 0.8083108593130239, 'weight_lgbm_class_2': 0.4231641605287685, 'weight_xgb_class_0': 0.12458166595864167, 'weight_xgb_class_1': 0.88780924052857, 'weight_xgb_class_2': 0.7859626033104778}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  40%|█████████████████████████████████████████████████████▏                                                                              | 806/2000 [00:20<00:37, 31.80it/s]

[I 2026-07-05 15:31:52,176] Trial 800 finished with value: 0.949750909075202 and parameters: {'weight_lgbm_class_0': 0.0005252338170117672, 'weight_lgbm_class_1': 0.718663422670701, 'weight_lgbm_class_2': 0.44379908856001793, 'weight_xgb_class_0': 0.12333960605199526, 'weight_xgb_class_1': 0.9306046599490777, 'weight_xgb_class_2': 0.7805555418334933}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:52,219] Trial 801 finished with value: 0.9497423581084578 and parameters: {'weight_lgbm_class_0': 0.009238709986444486, 'weight_lgbm_class_1': 0.7592647930874893, 'weight_lgbm_class_2': 0.4588221976448911, 'weight_xgb_class_0': 0.11527122455954003, 'weight_xgb_class_1': 0.8963734605971152, 'weight_xgb_class_2': 0.8056312515001122}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:52,263] Trial 802 finished with value: 0.9497776040878566 and parameters: {'weight_lgbm_class_0': 0.006711788241021067, 'weight_lgbm_class_1': 0.8084814178057685, 'weight_lgbm_class_2': 0.4577094541632062, 'weight_xgb_class_0': 0.11760492219128696, 'weight_xgb_class_1': 0.9006325032265987, 'weight_xgb_class_2': 0.775651602123179}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:52,265] Trial 803 finished with value: 0.9497791258237379 and parameters: {'weight_lgbm_class_0': 0.006820646637090137, 'weight_lgbm_class_1': 0.7609200170377334, 'weight_lgbm_class_2': 0.4177350685729287, 'weight_xgb_class_0': 0.11386874065313887, 'weight_xgb_class_1': 0.8932365060171961, 'weight_xgb_class_2': 0.7831537797327733}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:52,308] Trial 804 finished with value: 0.9496944107542274 and parameters: {'weight_lgbm_class_0': 0.029549967030162005, 'weight_lgbm_class_1': 0.7266455908132716, 'weight_lgbm_class_2': 0.41958995029604196, 'weight_xgb_class_0': 0.11549829014717557, 'weight_xgb_class_1': 0.9266576043257448, 'weight_xgb_class_2': 0.7816581938592799}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:52,326] Trial 805 finished with value: 0.9495001873144059 and parameters: {'weight_lgbm_class_0': 0.03419903549841271, 'weight_lgbm_class_1': 0.7670380501364524, 'weight_lgbm_class_2': 0.4133138739011182, 'weight_xgb_class_0': 0.11684162388823031, 'weight_xgb_class_1': 0.8916184554844003, 'weight_xgb_class_2': 0.7899212970814748}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:52,355] Trial 806 finished with value: 0.9493867945235704 and parameters: {'weight_lgbm_class_0': 0.003402525111365535, 'weight_lgbm_class_1': 0.748896218625357, 'weight_lgbm_class_2': 0.41107266372613227, 'weight_xgb_class_0': 0.1546154108315883, 'weight_xgb_class_1': 0.9212870220464853, 'weight_xgb_class_2': 0.7965438025053981}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  41%|█████████████████████████████████████████████████████▋                                                                              | 813/2000 [00:21<00:33, 35.38it/s]

[I 2026-07-05 15:31:52,388] Trial 808 finished with value: 0.9496986529866188 and parameters: {'weight_lgbm_class_0': 0.033426581617946635, 'weight_lgbm_class_1': 0.7684054574757359, 'weight_lgbm_class_2': 0.4091971730064734, 'weight_xgb_class_0': 0.10859862021694368, 'weight_xgb_class_1': 0.9174547585773524, 'weight_xgb_class_2': 0.7946913299840058}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:52,412] Trial 807 finished with value: 0.9496609453328969 and parameters: {'weight_lgbm_class_0': 0.02743995024862586, 'weight_lgbm_class_1': 0.813308439126222, 'weight_lgbm_class_2': 0.41454153967071694, 'weight_xgb_class_0': 0.11724558549927899, 'weight_xgb_class_1': 0.9276089974791429, 'weight_xgb_class_2': 0.8032254576019392}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:52,420] Trial 809 finished with value: 0.9496911406318933 and parameters: {'weight_lgbm_class_0': 0.029984965651541552, 'weight_lgbm_class_1': 0.7740385566575063, 'weight_lgbm_class_2': 0.4021255425018044, 'weight_xgb_class_0': 0.09397449313291688, 'weight_xgb_class_1': 0.8476701226220115, 'weight_xgb_class_2': 0.7668187102013243}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:52,454] Trial 810 finished with value: 0.9497361174413766 and parameters: {'weight_lgbm_class_0': 0.03126940922262692, 'weight_lgbm_class_1': 0.7451050048930489, 'weight_lgbm_class_2': 0.41631334352250615, 'weight_xgb_class_0': 0.08878648429465487, 'weight_xgb_class_1': 0.8500701691359844, 'weight_xgb_class_2': 0.7836546165704379}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:52,494] Trial 811 finished with value: 0.9447134107269992 and parameters: {'weight_lgbm_class_0': 0.030235247910453872, 'weight_lgbm_class_1': 0.7144501967338255, 'weight_lgbm_class_2': 0.4652661925036489, 'weight_xgb_class_0': 0.17254413330779733, 'weight_xgb_class_1': 0.0438419485631143, 'weight_xgb_class_2': 0.7445984557933971}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:52,501] Trial 812 finished with value: 0.9488159481768083 and parameters: {'weight_lgbm_class_0': 0.03703463295366344, 'weight_lgbm_class_1': 0.7575407492061006, 'weight_lgbm_class_2': 0.42134049246836813, 'weight_xgb_class_0': 0.15438882388133163, 'weight_xgb_class_1': 0.9269886313183716, 'weight_xgb_class_2': 0.7985375341171055}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:52,591] Trial 813 finished with value: 0.9496953037665478 and parameters: {'weight_lgbm_class_0': 0.0010594321312901275, 'weight_lgbm_class_1': 0.6944116494293652, 'weight_lgbm_class_2': 0.42508961657437777, 'weight_xgb_class_0': 0.14228991942861838, 'weight_xgb_class_1': 0.937024318787638, 'weight_xgb_class_2': 0.7991951578933204}. Best is trial 358 with value: 0.9497927483550862.

[I 2026-07-05 15:31:52,622] Trial 814 finished with value: 0.949401490264647 and parameters: {'weight_lgbm_class_0': 0.0017785328623370058, 'weight_lgbm_class_1': 0.7140143035746628, 'weight_lgbm_class_2': 0.46276596236497314, 'weight_xgb_class_0': 0.15056526853024987, 'weight_xgb_class_1': 0.8484890150563493, 'weight_xgb_class_2': 0.7443734761619809}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:52,668] Trial 815 finished with value: 0.9490512194491082 and parameters: {'weight_lgbm_class_0': 0.0014326211809750017, 'weight_lgbm_class_1': 0.7235441229836376, 'weight_lgbm_class_2': 0.4617003826387422, 'weight_xgb_class_0': 0.171298255258886, 'weight_xgb_class_1': 0.9299846358851913, 'weight_xgb_class_2': 0.7434496949792438}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:52,694] Trial 816 finished with value: 0.9496991896185115 and parameters: {'weight_lgbm_class_0': 0.0038896230648439445, 'weight_lgbm_class_1': 0.7029559105908008, 'weight_lgbm_class_2': 0.4453408339473904, 'weight_xgb_class_0': 0.12296181501432937, 'weight_xgb_class_1': 0.9179343809110607, 'weight_xgb_class_2': 0.7568758389383943}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:52,704] Trial 818 finished with value: 0.949243455461723 and parameters: {'weight_lgbm_class_0': 0.0007360513956302505, 'weight_lgbm_class_1': 0.7266844816160546, 'weight_lgbm_class_2': 0.46293263263341256, 'weight_xgb_class_0': 0.160168094897584, 'weight_xgb_class_1': 0.9083409371775424, 'weight_xgb_class_2': 0.7438753702309141}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:52,710] Trial 817 finished with value: 0.949380910298688 and parameters: {'weight_lgbm_class_0': 0.003127492994516619, 'weight_lgbm_class_1': 0.7255858766216869, 'weight_lgbm_class_2': 0.47463020447539644, 'weight_xgb_class_0': 0.15597212396546606, 'weight_xgb_class_1': 0.9201634359949925, 'weight_xgb_class_2': 0.7699144706326806}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:52,745] Trial 819 finished with value: 0.9492418477918635 and parameters: {'weight_lgbm_class_0': 0.00020304345219564549, 'weight_lgbm_class_1': 0.707375675700965, 'weight_lgbm_class_2': 0.47307992376880537, 'weight_xgb_class_0': 0.1604415536850507, 'weight_xgb_class_1': 0.9148906651152874, 'weight_xgb_class_2': 0.7255052830042623}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:52,768] Trial 820 finished with value: 0.9486562317977821 and parameters: {'weight_lgbm_class_0': 0.02898570392319641, 'weight_lgbm_class_1': 0.7453478413592047, 'weight_lgbm_class_2': 0.4549507694992384, 'weight_xgb_class_0': 0.1609096140934877, 'weight_xgb_class_1': 0.9286206159283863, 'weight_xgb_class_2': 0.7113035678663275}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  41%|██████████████████████████████████████████████████████▋                                                                             | 828/2000 [00:21<00:34, 34.04it/s]

[I 2026-07-05 15:31:52,819] Trial 821 finished with value: 0.94894645040821 and parameters: {'weight_lgbm_class_0': 0.023275869095956817, 'weight_lgbm_class_1': 0.7044977544422337, 'weight_lgbm_class_2': 0.4382626618511834, 'weight_xgb_class_0': 0.1555106713257607, 'weight_xgb_class_1': 0.9222745615798483, 'weight_xgb_class_2': 0.7485562030600139}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:52,832] Trial 822 finished with value: 0.9487088143002508 and parameters: {'weight_lgbm_class_0': 0.025576071303979306, 'weight_lgbm_class_1': 0.7068376204575402, 'weight_lgbm_class_2': 0.46656081426025686, 'weight_xgb_class_0': 0.16688883154511036, 'weight_xgb_class_1': 0.932324401951258, 'weight_xgb_class_2': 0.7275526777228327}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:52,833] Trial 823 finished with value: 0.9491450668793293 and parameters: {'weight_lgbm_class_0': 0.005139418002694194, 'weight_lgbm_class_1': 0.7036553168316396, 'weight_lgbm_class_2': 0.4601219210176377, 'weight_xgb_class_0': 0.1569086559935753, 'weight_xgb_class_1': 0.9276779478149357, 'weight_xgb_class_2': 0.7230290560382424}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:52,856] Trial 824 finished with value: 0.9492915933833183 and parameters: {'weight_lgbm_class_0': 0.006207415708722373, 'weight_lgbm_class_1': 0.7291229745507263, 'weight_lgbm_class_2': 0.4679973379284269, 'weight_xgb_class_0': 0.15350294370184853, 'weight_xgb_class_1': 0.8368895983676443, 'weight_xgb_class_2': 0.7363735357459096}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:52,931] Trial 826 finished with value: 0.9493202018141408 and parameters: {'weight_lgbm_class_0': 0.002393604444448064, 'weight_lgbm_class_1': 0.7103525511412043, 'weight_lgbm_class_2': 0.4416067424134443, 'weight_xgb_class_0': 0.15349039265227382, 'weight_xgb_class_1': 0.9330159685552394, 'weight_xgb_class_2': 0.7204300091100224}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:52,937] Trial 825 finished with value: 0.9491450669821259 and parameters: {'weight_lgbm_class_0': 0.017544401024017525, 'weight_lgbm_class_1': 0.7106740506617613, 'weight_lgbm_class_2': 0.4710742981866738, 'weight_xgb_class_0': 0.15064372322054703, 'weight_xgb_class_1': 0.9268477526964406, 'weight_xgb_class_2': 0.7416448088912884}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:53,006] Trial 827 finished with value: 0.9497382483660047 and parameters: {'weight_lgbm_class_0': 0.03770268248209174, 'weight_lgbm_class_1': 0.7294294996493828, 'weight_lgbm_class_2': 0.43191808357677647, 'weight_xgb_class_0': 0.09213642763186843, 'weight_xgb_class_1': 0.9308270873892066, 'weight_xgb_class_2': 0.7521689328179973}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:53,036] Trial 830 finished with value: 0.9487123767734894 and parameters: {'weight_lgbm_class_0': 0.04273765530781583, 'weight_lgbm_class_1': 0.77395464044649, 'weight_lgbm_class_2': 0.43948710752082015, 'weight_xgb_class_0': 0.1481082767775623, 'weight_xgb_class_1': 0.8375101504692497, 'weight_xgb_class_2': 0.7689699385749016}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  42%|███████████████████████████████████████████████████████▏                                                                            | 836/2000 [00:21<00:33, 34.42it/s]

[I 2026-07-05 15:31:53,059] Trial 829 finished with value: 0.9490507340173755 and parameters: {'weight_lgbm_class_0': 0.033522504237135584, 'weight_lgbm_class_1': 0.7531997224197177, 'weight_lgbm_class_2': 0.4353181165882761, 'weight_xgb_class_0': 0.1344440424328267, 'weight_xgb_class_1': 0.8382623351771521, 'weight_xgb_class_2': 0.7605969275776038}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:53,089] Trial 828 finished with value: 0.9488065857138613 and parameters: {'weight_lgbm_class_0': 0.026210402210046068, 'weight_lgbm_class_1': 0.7575058881481344, 'weight_lgbm_class_2': 0.45091279148956676, 'weight_xgb_class_0': 0.15422633133028418, 'weight_xgb_class_1': 0.8423209928199961, 'weight_xgb_class_2': 0.7014591547583655}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:53,091] Trial 831 finished with value: 0.9496678076894184 and parameters: {'weight_lgbm_class_0': 0.04280851416120219, 'weight_lgbm_class_1': 0.7618822677510552, 'weight_lgbm_class_2': 0.42795050784756117, 'weight_xgb_class_0': 0.09934994290831788, 'weight_xgb_class_1': 0.8404783033445571, 'weight_xgb_class_2': 0.7612981937571259}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:53,115] Trial 832 finished with value: 0.948820013205927 and parameters: {'weight_lgbm_class_0': 0.04358431056801048, 'weight_lgbm_class_1': 0.7610664402235489, 'weight_lgbm_class_2': 0.4333573560791592, 'weight_xgb_class_0': 0.14678362121521, 'weight_xgb_class_1': 0.8402635802765175, 'weight_xgb_class_2': 0.814727049585564}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:53,158] Trial 833 finished with value: 0.9490495863951351 and parameters: {'weight_lgbm_class_0': 0.04004825589378483, 'weight_lgbm_class_1': 0.7668589777627444, 'weight_lgbm_class_2': 0.4331900770630019, 'weight_xgb_class_0': 0.1310954483354954, 'weight_xgb_class_1': 0.8451238146798464, 'weight_xgb_class_2': 0.7802308633612148}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:53,183] Trial 834 finished with value: 0.9496976231692958 and parameters: {'weight_lgbm_class_0': 0.041259727098168525, 'weight_lgbm_class_1': 0.764371020607734, 'weight_lgbm_class_2': 0.43797401026226257, 'weight_xgb_class_0': 0.09753540014173916, 'weight_xgb_class_1': 0.8405031168347106, 'weight_xgb_class_2': 0.7834653058445904}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:53,219] Trial 835 finished with value: 0.9496751794303474 and parameters: {'weight_lgbm_class_0': 0.043777620622419855, 'weight_lgbm_class_1': 0.7632363477460714, 'weight_lgbm_class_2': 0.42413805312141845, 'weight_xgb_class_0': 0.09775072175077262, 'weight_xgb_class_1': 0.8431774327760972, 'weight_xgb_class_2': 0.78869069093291}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:53,252] Trial 836 finished with value: 0.9496719401997255 and parameters: {'weight_lgbm_class_0': 0.040889810878296025, 'weight_lgbm_class_1': 0.6624949812755098, 'weight_lgbm_class_2': 0.431463200870113, 'weight_xgb_class_0': 0.09307253341871202, 'weight_xgb_class_1': 0.8523455745583007, 'weight_xgb_class_2': 0.7721850684946532}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  42%|███████████████████████████████████████████████████████▋                                                                            | 843/2000 [00:22<00:37, 31.04it/s]

[I 2026-07-05 15:31:53,296] Trial 837 finished with value: 0.9496816204387163 and parameters: {'weight_lgbm_class_0': 0.04310201286241162, 'weight_lgbm_class_1': 0.7687966710999213, 'weight_lgbm_class_2': 0.43727678900921824, 'weight_xgb_class_0': 0.09284141408218971, 'weight_xgb_class_1': 0.842336365527175, 'weight_xgb_class_2': 0.7868820075843644}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:53,305] Trial 838 finished with value: 0.9496824229346305 and parameters: {'weight_lgbm_class_0': 0.04746246625896822, 'weight_lgbm_class_1': 0.7767225344306519, 'weight_lgbm_class_2': 0.4264789394567158, 'weight_xgb_class_0': 0.09501843965776202, 'weight_xgb_class_1': 0.838686139448752, 'weight_xgb_class_2': 0.7829937295015666}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:53,327] Trial 839 finished with value: 0.9488820113502369 and parameters: {'weight_lgbm_class_0': 0.04821861174881643, 'weight_lgbm_class_1': 0.7762812952730669, 'weight_lgbm_class_2': 0.3946700909152284, 'weight_xgb_class_0': 0.1290539911908979, 'weight_xgb_class_1': 0.8420966954547557, 'weight_xgb_class_2': 0.7691024679541032}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:53,412] Trial 840 finished with value: 0.9216416049362777 and parameters: {'weight_lgbm_class_0': 0.5414083736091608, 'weight_lgbm_class_1': 0.7732717218704438, 'weight_lgbm_class_2': 0.39687523880821785, 'weight_xgb_class_0': 0.12747759539047104, 'weight_xgb_class_1': 0.8420572284556214, 'weight_xgb_class_2': 0.793879189132431}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:53,456] Trial 841 finished with value: 0.9491536811149941 and parameters: {'weight_lgbm_class_0': 0.04204427159142898, 'weight_lgbm_class_1': 0.7784223661431766, 'weight_lgbm_class_2': 0.3868277424206051, 'weight_xgb_class_0': 0.11853597702826398, 'weight_xgb_class_1': 0.8616619643678853, 'weight_xgb_class_2': 0.7788490840157586}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:53,468] Trial 842 finished with value: 0.9425879048683193 and parameters: {'weight_lgbm_class_0': 0.04500581185353466, 'weight_lgbm_class_1': 0.7698327233172181, 'weight_lgbm_class_2': 0.39465143157027943, 'weight_xgb_class_0': 0.30987917051670344, 'weight_xgb_class_1': 0.8637597534106001, 'weight_xgb_class_2': 0.788278624229284}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:53,474] Trial 843 finished with value: 0.9491789618677533 and parameters: {'weight_lgbm_class_0': 0.04713048680339596, 'weight_lgbm_class_1': 0.7802313131352898, 'weight_lgbm_class_2': 0.39952257951376, 'weight_xgb_class_0': 0.11439947185670338, 'weight_xgb_class_1': 0.8673250293338537, 'weight_xgb_class_2': 0.7851760113244312}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  42%|████████████████████████████████████████████████████████                                                                            | 850/2000 [00:22<00:33, 34.71it/s]

[I 2026-07-05 15:31:53,504] Trial 844 finished with value: 0.9492923365141888 and parameters: {'weight_lgbm_class_0': 0.046384230610025744, 'weight_lgbm_class_1': 0.7753149400165193, 'weight_lgbm_class_2': 0.3980626715252523, 'weight_xgb_class_0': 0.11166352682659766, 'weight_xgb_class_1': 0.8654660918615776, 'weight_xgb_class_2': 0.7902548706029988}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:53,532] Trial 845 finished with value: 0.949320203410148 and parameters: {'weight_lgbm_class_0': 0.04695486206732654, 'weight_lgbm_class_1': 0.7896441755770168, 'weight_lgbm_class_2': 0.3952556010827817, 'weight_xgb_class_0': 0.11371960019838204, 'weight_xgb_class_1': 0.9026865185801121, 'weight_xgb_class_2': 0.8263035911683151}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:53,543] Trial 847 finished with value: 0.948964873222308 and parameters: {'weight_lgbm_class_0': 0.052299050741733334, 'weight_lgbm_class_1': 0.7838978227202882, 'weight_lgbm_class_2': 0.39566214003326006, 'weight_xgb_class_0': 0.12140658200793013, 'weight_xgb_class_1': 0.8985123840522707, 'weight_xgb_class_2': 0.7682356875815181}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:53,552] Trial 846 finished with value: 0.9496925378371267 and parameters: {'weight_lgbm_class_0': 0.05240080891242273, 'weight_lgbm_class_1': 0.6751439984417099, 'weight_lgbm_class_2': 0.3926311779480055, 'weight_xgb_class_0': 0.08167836287889173, 'weight_xgb_class_1': 0.8680443111367685, 'weight_xgb_class_2': 0.7833005812888671}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:53,601] Trial 848 finished with value: 0.9490300499730383 and parameters: {'weight_lgbm_class_0': 0.05472769430094978, 'weight_lgbm_class_1': 0.783648788420463, 'weight_lgbm_class_2': 0.39665638277171705, 'weight_xgb_class_0': 0.1216453208836652, 'weight_xgb_class_1': 0.8981180397644398, 'weight_xgb_class_2': 0.8259775663859209}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:53,684] Trial 851 finished with value: 0.9496670925719538 and parameters: {'weight_lgbm_class_0': 0.017627308976410478, 'weight_lgbm_class_1': 0.8154346505900771, 'weight_lgbm_class_2': 0.39413277633622945, 'weight_xgb_class_0': 0.08061262046122246, 'weight_xgb_class_1': 0.9021040427961983, 'weight_xgb_class_2': 0.8186817097140292}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:53,685] Trial 849 finished with value: 0.9496521016658329 and parameters: {'weight_lgbm_class_0': 0.024041514816114967, 'weight_lgbm_class_1': 0.7952632652234157, 'weight_lgbm_class_2': 0.39583910948372086, 'weight_xgb_class_0': 0.11350097943473916, 'weight_xgb_class_1': 0.898794797268414, 'weight_xgb_class_2': 0.8174512739985046}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  43%|████████████████████████████████████████████████████████▋                                                                           | 858/2000 [00:22<00:33, 33.79it/s]

[I 2026-07-05 15:31:53,711] Trial 850 finished with value: 0.9496738848102814 and parameters: {'weight_lgbm_class_0': 0.023602200842670843, 'weight_lgbm_class_1': 0.810719065408039, 'weight_lgbm_class_2': 0.38894508865176164, 'weight_xgb_class_0': 0.11084445883113021, 'weight_xgb_class_1': 0.8972166185549542, 'weight_xgb_class_2': 0.818066575874852}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:53,746] Trial 852 finished with value: 0.9496915586852347 and parameters: {'weight_lgbm_class_0': 0.022742247954458263, 'weight_lgbm_class_1': 0.8175937804318161, 'weight_lgbm_class_2': 0.39161954945140093, 'weight_xgb_class_0': 0.11675590915468305, 'weight_xgb_class_1': 0.892730598744606, 'weight_xgb_class_2': 0.822833798845467}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:53,793] Trial 853 finished with value: 0.9496209364338587 and parameters: {'weight_lgbm_class_0': 0.02106935048276779, 'weight_lgbm_class_1': 0.8021852291973807, 'weight_lgbm_class_2': 0.3750873415369529, 'weight_xgb_class_0': 0.0746615903056212, 'weight_xgb_class_1': 0.8960509925178394, 'weight_xgb_class_2': 0.820973067020105}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:53,800] Trial 855 finished with value: 0.9496098637158848 and parameters: {'weight_lgbm_class_0': 0.020794206175232935, 'weight_lgbm_class_1': 0.8092586195298266, 'weight_lgbm_class_2': 0.3816394110911141, 'weight_xgb_class_0': 0.0738151590696584, 'weight_xgb_class_1': 0.9002403931741366, 'weight_xgb_class_2': 0.8209651108666177}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:53,816] Trial 854 finished with value: 0.9496466001359799 and parameters: {'weight_lgbm_class_0': 0.021241854795618263, 'weight_lgbm_class_1': 0.8107230047020025, 'weight_lgbm_class_2': 0.3765988390348159, 'weight_xgb_class_0': 0.07497536124390182, 'weight_xgb_class_1': 0.899605554799137, 'weight_xgb_class_2': 0.8192540100452157}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:53,879] Trial 856 finished with value: 0.9496704856776678 and parameters: {'weight_lgbm_class_0': 0.058811914929398454, 'weight_lgbm_class_1': 0.8167370253036671, 'weight_lgbm_class_2': 0.37892229179802916, 'weight_xgb_class_0': 0.08211778227231695, 'weight_xgb_class_1': 0.8980882040753873, 'weight_xgb_class_2': 0.8232765630750537}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:53,886] Trial 857 finished with value: 0.9496926402707581 and parameters: {'weight_lgbm_class_0': 0.022497818260297085, 'weight_lgbm_class_1': 0.8201694658010151, 'weight_lgbm_class_2': 0.38370807261089307, 'weight_xgb_class_0': 0.07995486235328192, 'weight_xgb_class_1': 0.9005158278670846, 'weight_xgb_class_2': 0.8125820373917244}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:53,898] Trial 858 finished with value: 0.9487049547088313 and parameters: {'weight_lgbm_class_0': 0.0015695288244651701, 'weight_lgbm_class_1': 0.815176468876004, 'weight_lgbm_class_2': 0.3693462748285776, 'weight_xgb_class_0': 0.19064997422076146, 'weight_xgb_class_1': 0.8977662370402402, 'weight_xgb_class_2': 0.8262693871994603}. Best is trial 358 with value: 0.9497927483550862.

[I 2026-07-05 15:31:53,913] Trial 859 finished with value: 0.9497112173301095 and parameters: {'weight_lgbm_class_0': 0.0610717874267297, 'weight_lgbm_class_1': 0.8182420713149636, 'weight_lgbm_class_2': 0.49322744314469696, 'weight_xgb_class_0': 0.08169498568338289, 'weight_xgb_class_1': 0.8998898210753834, 'weight_xgb_class_2': 0.8184321663119047}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:53,953] Trial 860 finished with value: 0.9497121403012585 and parameters: {'weight_lgbm_class_0': 0.01833516350744361, 'weight_lgbm_class_1': 0.8058133539645034, 'weight_lgbm_class_2': 0.37330727484042175, 'weight_xgb_class_0': 0.08172641205168585, 'weight_xgb_class_1': 0.9040140164458345, 'weight_xgb_class_2': 0.8138765295053995}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:54,017] Trial 861 finished with value: 0.949717093863066 and parameters: {'weight_lgbm_class_0': 0.024381299219216442, 'weight_lgbm_class_1': 0.8318558636005646, 'weight_lgbm_class_2': 0.4889791153088143, 'weight_xgb_class_0': 0.09274995425735219, 'weight_xgb_class_1': 0.8781422533355854, 'weight_xgb_class_2': 0.8501636419340045}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:54,051] Trial 862 finished with value: 0.9494014867690949 and parameters: {'weight_lgbm_class_0': 0.020847943415188724, 'weight_lgbm_class_1': 0.8348335917613363, 'weight_lgbm_class_2': 0.3717570081276025, 'weight_xgb_class_0': 0.08446257300652169, 'weight_xgb_class_1': 0.8781622059235589, 'weight_xgb_class_2': 0.41189596868927936}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:54,061] Trial 863 finished with value: 0.9496808373130482 and parameters: {'weight_lgbm_class_0': 0.059469223875067485, 'weight_lgbm_class_1': 0.8301501137779587, 'weight_lgbm_class_2': 0.37833600548392715, 'weight_xgb_class_0': 0.07466186906540773, 'weight_xgb_class_1': 0.8721730002258758, 'weight_xgb_class_2': 0.8484829425702825}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:54,096] Trial 864 finished with value: 0.9496516063293868 and parameters: {'weight_lgbm_class_0': 0.0196793915076593, 'weight_lgbm_class_1': 0.8098034917447035, 'weight_lgbm_class_2': 0.4860006059050053, 'weight_xgb_class_0': 0.0859482047792416, 'weight_xgb_class_1': 0.8739919605870492, 'weight_xgb_class_2': 0.8574060073395597}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  44%|█████████████████████████████████████████████████████████▌                                                                          | 872/2000 [00:22<00:34, 32.88it/s]

[I 2026-07-05 15:31:54,149] Trial 865 finished with value: 0.9494992096277309 and parameters: {'weight_lgbm_class_0': 0.0016719133805361414, 'weight_lgbm_class_1': 0.8405087205249391, 'weight_lgbm_class_2': 0.368654043216958, 'weight_xgb_class_0': 0.08382675555112186, 'weight_xgb_class_1': 0.8743408896566557, 'weight_xgb_class_2': 0.8519034632431605}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:54,150] Trial 866 finished with value: 0.9497218618714035 and parameters: {'weight_lgbm_class_0': 0.05940037677867367, 'weight_lgbm_class_1': 0.8300345249533638, 'weight_lgbm_class_2': 0.4903656903989028, 'weight_xgb_class_0': 0.08522425499111025, 'weight_xgb_class_1': 0.8771147532175296, 'weight_xgb_class_2': 0.8522601919759567}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:54,192] Trial 867 finished with value: 0.949672481084911 and parameters: {'weight_lgbm_class_0': 0.06131079379282105, 'weight_lgbm_class_1': 0.8331263325633642, 'weight_lgbm_class_2': 0.41377685873379216, 'weight_xgb_class_0': 0.07954127707674015, 'weight_xgb_class_1': 0.8715345702846437, 'weight_xgb_class_2': 0.8520454128178506}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:54,234] Trial 868 finished with value: 0.9497013393660909 and parameters: {'weight_lgbm_class_0': 0.06438068665258478, 'weight_lgbm_class_1': 0.837346168181654, 'weight_lgbm_class_2': 0.48382487792434337, 'weight_xgb_class_0': 0.08429951944954703, 'weight_xgb_class_1': 0.873079232199012, 'weight_xgb_class_2': 0.8476155867998225}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:54,270] Trial 870 finished with value: 0.9496311449830047 and parameters: {'weight_lgbm_class_0': 0.0007038284896090687, 'weight_lgbm_class_1': 0.8464078791203529, 'weight_lgbm_class_2': 0.41388842945018606, 'weight_xgb_class_0': 0.09515212920431451, 'weight_xgb_class_1': 0.8746252682144128, 'weight_xgb_class_2': 0.850968512994161}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:54,281] Trial 869 finished with value: 0.9496744015169193 and parameters: {'weight_lgbm_class_0': 0.001826314900775415, 'weight_lgbm_class_1': 0.7500839054759081, 'weight_lgbm_class_2': 0.41491874043478505, 'weight_xgb_class_0': 0.09353398063244721, 'weight_xgb_class_1': 0.8267160795486485, 'weight_xgb_class_2': 0.8508925025549803}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:54,295] Trial 871 finished with value: 0.9495147227423041 and parameters: {'weight_lgbm_class_0': 0.06102610554266294, 'weight_lgbm_class_1': 0.8439433966853229, 'weight_lgbm_class_2': 0.4167445798065689, 'weight_xgb_class_0': 0.097626092586736, 'weight_xgb_class_1': 0.8763199596237322, 'weight_xgb_class_2': 0.8541820529165858}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:54,312] Trial 872 finished with value: 0.9495630098667985 and parameters: {'weight_lgbm_class_0': 0.05949701562699036, 'weight_lgbm_class_1': 0.8308095130356539, 'weight_lgbm_class_2': 0.4132049059459091, 'weight_xgb_class_0': 0.09665855033528073, 'weight_xgb_class_1': 0.871964624417586, 'weight_xgb_class_2': 0.8574367715324858}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  44%|██████████████████████████████████████████████████████████                                                                          | 879/2000 [00:23<00:31, 35.78it/s]

[I 2026-07-05 15:31:54,353] Trial 873 finished with value: 0.9494387405898066 and parameters: {'weight_lgbm_class_0': 0.05982720016424724, 'weight_lgbm_class_1': 0.8338914904403776, 'weight_lgbm_class_2': 0.41459810356182725, 'weight_xgb_class_0': 0.1014719173802347, 'weight_xgb_class_1': 0.869561611924555, 'weight_xgb_class_2': 0.8524540823357494}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:54,385] Trial 874 finished with value: 0.9488602116573954 and parameters: {'weight_lgbm_class_0': 0.05942464678074513, 'weight_lgbm_class_1': 0.8565859926588351, 'weight_lgbm_class_2': 0.4132690590442329, 'weight_xgb_class_0': 0.13541191954988022, 'weight_xgb_class_1': 0.8603620107062002, 'weight_xgb_class_2': 0.8501445223760244}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:54,413] Trial 875 finished with value: 0.948804667877833 and parameters: {'weight_lgbm_class_0': 0.06095367579136923, 'weight_lgbm_class_1': 0.8408659451039577, 'weight_lgbm_class_2': 0.421830744558134, 'weight_xgb_class_0': 0.13556996307682917, 'weight_xgb_class_1': 0.8261108799951649, 'weight_xgb_class_2': 0.8565757991361779}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:54,427] Trial 876 finished with value: 0.9420930948182741 and parameters: {'weight_lgbm_class_0': 0.060386213395909515, 'weight_lgbm_class_1': 0.6807657564805456, 'weight_lgbm_class_2': 0.4222470763140267, 'weight_xgb_class_0': 0.13368481752683953, 'weight_xgb_class_1': 0.8254644045685314, 'weight_xgb_class_2': 0.1323370432913974}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:54,505] Trial 877 finished with value: 0.947052928826165 and parameters: {'weight_lgbm_class_0': 0.06116616304195488, 'weight_lgbm_class_1': 0.8463614942962796, 'weight_lgbm_class_2': 0.41432317047571654, 'weight_xgb_class_0': 0.2133133327518693, 'weight_xgb_class_1': 0.8288290840802548, 'weight_xgb_class_2': 0.8771783253130148}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:54,546] Trial 878 finished with value: 0.9496336793246924 and parameters: {'weight_lgbm_class_0': 0.0009525966709749071, 'weight_lgbm_class_1': 0.7408715907379735, 'weight_lgbm_class_2': 0.41072168404853815, 'weight_xgb_class_0': 0.13929912959041188, 'weight_xgb_class_1': 0.822419279048074, 'weight_xgb_class_2': 0.8728772118921267}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:54,561] Trial 880 finished with value: 0.9496988667668016 and parameters: {'weight_lgbm_class_0': 0.0007803553575091507, 'weight_lgbm_class_1': 0.7459710140696415, 'weight_lgbm_class_2': 0.4205996709694081, 'weight_xgb_class_0': 0.10512105695476948, 'weight_xgb_class_1': 0.8273459191582322, 'weight_xgb_class_2': 0.8737811214218432}. Best is trial 358 with value: 0.9497927483550862.

[I 2026-07-05 15:31:54,598] Trial 879 finished with value: 0.9493357829576629 and parameters: {'weight_lgbm_class_0': 0.033271261500209086, 'weight_lgbm_class_1': 0.8453783861553623, 'weight_lgbm_class_2': 0.4173607598564446, 'weight_xgb_class_0': 0.13318159818220768, 'weight_xgb_class_1': 0.8211316163431658, 'weight_xgb_class_2': 0.8752801237896305}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:54,627] Trial 881 finished with value: 0.9493085106682262 and parameters: {'weight_lgbm_class_0': 0.03497824756351482, 'weight_lgbm_class_1': 0.7387668782370446, 'weight_lgbm_class_2': 0.44995165753736044, 'weight_xgb_class_0': 0.13611447618167632, 'weight_xgb_class_1': 0.8303952673773746, 'weight_xgb_class_2': 0.8741700693207358}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:54,642] Trial 882 finished with value: 0.9494138042515106 and parameters: {'weight_lgbm_class_0': 0.034232312960736616, 'weight_lgbm_class_1': 0.860835072703717, 'weight_lgbm_class_2': 0.44875838291457903, 'weight_xgb_class_0': 0.1326083013804248, 'weight_xgb_class_1': 0.8255110631863624, 'weight_xgb_class_2': 0.8734600320011626}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:54,694] Trial 883 finished with value: 0.9496243635205025 and parameters: {'weight_lgbm_class_0': 0.027851568635908007, 'weight_lgbm_class_1': 0.8654994473726132, 'weight_lgbm_class_2': 0.4470149797953515, 'weight_xgb_class_0': 0.1293625701398537, 'weight_xgb_class_1': 0.8245790438583183, 'weight_xgb_class_2': 0.871160463190111}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:54,720] Trial 884 finished with value: 0.9496563372752904 and parameters: {'weight_lgbm_class_0': 0.029863273298630408, 'weight_lgbm_class_1': 0.8598011131265626, 'weight_lgbm_class_2': 0.44650874604285123, 'weight_xgb_class_0': 0.1251773818843919, 'weight_xgb_class_1': 0.8259450491339927, 'weight_xgb_class_2': 0.8767470202038319}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:54,744] Trial 885 finished with value: 0.949652138468616 and parameters: {'weight_lgbm_class_0': 0.03189016893270184, 'weight_lgbm_class_1': 0.89639350447699, 'weight_lgbm_class_2': 0.44511713632979616, 'weight_xgb_class_0': 0.1262601274753939, 'weight_xgb_class_1': 0.8276440859424095, 'weight_xgb_class_2': 0.8766704243448813}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:54,772] Trial 886 finished with value: 0.949407111249482 and parameters: {'weight_lgbm_class_0': 0.03192049812739819, 'weight_lgbm_class_1': 0.8577536449334702, 'weight_lgbm_class_2': 0.45398373237735606, 'weight_xgb_class_0': 0.1374315725144929, 'weight_xgb_class_1': 0.82349355908835, 'weight_xgb_class_2': 0.878009513349503}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:54,788] Trial 887 finished with value: 0.9378850401620556 and parameters: {'weight_lgbm_class_0': 0.03204246668838244, 'weight_lgbm_class_1': 0.869620822231709, 'weight_lgbm_class_2': 0.4496339534022409, 'weight_xgb_class_0': 0.4500891752278613, 'weight_xgb_class_1': 0.8260569612125482, 'weight_xgb_class_2': 0.8863894928783497}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 358. Best value: 0.949793:  45%|██████████████████████████████████████████████████████████▉                                                                         | 893/2000 [00:23<00:32, 33.68it/s]

[I 2026-07-05 15:31:54,800] Trial 888 finished with value: 0.9496957594580775 and parameters: {'weight_lgbm_class_0': 0.02934184986249599, 'weight_lgbm_class_1': 0.7476154913105086, 'weight_lgbm_class_2': 0.44426080286903125, 'weight_xgb_class_0': 0.10540340771685834, 'weight_xgb_class_1': 0.8256551313719046, 'weight_xgb_class_2': 0.8753120539367446}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:54,876] Trial 889 finished with value: 0.94968325267803 and parameters: {'weight_lgbm_class_0': 0.03237762316129453, 'weight_lgbm_class_1': 0.743884929284954, 'weight_lgbm_class_2': 0.35862471384666106, 'weight_xgb_class_0': 0.11062991350542377, 'weight_xgb_class_1': 0.8317119991933128, 'weight_xgb_class_2': 0.8739998405819059}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:54,887] Trial 891 finished with value: 0.9496910069571344 and parameters: {'weight_lgbm_class_0': 0.034420926812043805, 'weight_lgbm_class_1': 0.8704789291611812, 'weight_lgbm_class_2': 0.45170413598356535, 'weight_xgb_class_0': 0.10755782553208575, 'weight_xgb_class_1': 0.8503445564808118, 'weight_xgb_class_2': 0.8723744788897201}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:54,912] Trial 890 finished with value: 0.948648102549352 and parameters: {'weight_lgbm_class_0': 0.029376283024377906, 'weight_lgbm_class_1': 0.8674901834665599, 'weight_lgbm_class_2': 0.45288339497348545, 'weight_xgb_class_0': 0.18210325483572065, 'weight_xgb_class_1': 0.8528011911577718, 'weight_xgb_class_2': 0.8758920931488888}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:54,945] Trial 892 finished with value: 0.9492505604370675 and parameters: {'weight_lgbm_class_0': 0.025237052332796862, 'weight_lgbm_class_1': 0.8766101375305726, 'weight_lgbm_class_2': 0.45030057132857715, 'weight_xgb_class_0': 0.06954906868849586, 'weight_xgb_class_1': 0.001035144992958037, 'weight_xgb_class_2': 0.7528476891308725}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:55,011] Trial 893 finished with value: 0.9165385794101345 and parameters: {'weight_lgbm_class_0': 0.02622319582333014, 'weight_lgbm_class_1': 0.8763172525788006, 'weight_lgbm_class_2': 0.35235431447250176, 'weight_xgb_class_0': 0.7344305927343541, 'weight_xgb_class_1': 0.8547526675503833, 'weight_xgb_class_2': 0.8339653812449015}. Best is trial 358 with value: 0.9497927483550862.

Best trial: 896. Best value: 0.949806:  45%|███████████████████████████████████████████████████████████▍                                                                        | 901/2000 [00:23<00:34, 31.84it/s]

[I 2026-07-05 15:31:55,025] Trial 894 finished with value: 0.9496294256248922 and parameters: {'weight_lgbm_class_0': 0.029313815944361256, 'weight_lgbm_class_1': 0.87532224949654, 'weight_lgbm_class_2': 0.3628227416410104, 'weight_xgb_class_0': 0.06717106599764656, 'weight_xgb_class_1': 0.8538291724696627, 'weight_xgb_class_2': 0.8353660697292197}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:55,055] Trial 895 finished with value: 0.9391879844644994 and parameters: {'weight_lgbm_class_0': 0.2870978271001045, 'weight_lgbm_class_1': 0.7995189347522783, 'weight_lgbm_class_2': 0.35347071686965165, 'weight_xgb_class_0': 0.0692497746982147, 'weight_xgb_class_1': 0.8535235553653722, 'weight_xgb_class_2': 0.5925330718478258}. Best is trial 358 with value: 0.9497927483550862.
[I 2026-07-05 15:31:55,090] Trial 896 finished with value: 0.9498060162868619 and parameters: {'weight_lgbm_class_0': 0.04013165882326928, 'weight_lgbm_class_1': 0.883892295945212, 'weight_lgbm_class_2': 0.3512417789039712, 'weight_xgb_class_0': 0.07221105894612641, 'weight_xgb_class_1': 0.8569638967519366, 'weight_xgb_class_2': 0.7566444468039462}. Best is trial 896 with value: 0.9498060162868619.
[I 2026-07-05 15:31:55,097] Trial 897 finished with value: 0.9481779662282372 and parameters: {'weight_lgbm_class_0': 0.03896032440650267, 'weight_lgbm_class_1': 0.8757601649319293, 'weight_lgbm_class_2': 0.3534508029849769, 'weight_xgb_class_0': 0.1813460585752659, 'weight_xgb_class_1': 0.8570969806807022, 'weight_xgb_class_2': 0.8370157030745445}. Best is trial 896 with value: 0.9498060162868619.
[I 2026-07-05 15:31:55,141] Trial 898 finished with value: 0.9494030080271662 and parameters: {'weight_lgbm_class_0': 0.075322269844587, 'weight_lgbm_class_1': 0.791346709101742, 'weight_lgbm_class_2': 0.35655820403141353, 'weight_xgb_class_0': 0.06931080658821646, 'weight_xgb_class_1': 0.8526395336863363, 'weight_xgb_class_2': 0.7591340061738772}. Best is trial 896 with value: 0.9498060162868619.
[I 2026-07-05 15:31:55,147] Trial 899 finished with value: 0.9493714769212377 and parameters: {'weight_lgbm_class_0': 0.0005156924511526169, 'weight_lgbm_class_1': 0.879972696010208, 'weight_lgbm_class_2': 0.3576429104253275, 'weight_xgb_class_0': 0.0735954653675436, 'weight_xgb_class_1': 0.8578141673503357, 'weight_xgb_class_2': 0.7609753266940595}. Best is trial 896 with value: 0.9498060162868619.
[I 2026-07-05 15:31:55,147] Trial 900 finished with value: 0.9497150062406127 and parameters: {'weight_lgbm_class_0': 0.04815271040296712, 'weight_lgbm_class_1': 0.8910464403020508, 'weight_lgbm_class_2': 0.3516092117021504, 'weight_xgb_class_0': 0.07295087893120392, 'weight_xgb_class_1': 0.849573002117896, 'weight_xgb_class_2': 0.8364698069843857}. Best is trial 896 with value: 0.9498060162868619.
[I 2026-07-05 15:31:55,239] Trial 901 finished with value: 0.9403582541180525 and parameters: {'weight_lgbm_class_0': 0.0753115861459627, 'weight_lgbm_class_1': 0.7961640931556034, 'weight_lgbm_class_2': 0.3526969070341068, 'weight_xgb_class_0': 0.18141545419266647, 'weight_xgb_class_1': 0.85322183606764, 'weight_xgb_class_2': 0.31253911252732425}. Best is trial 896 with value: 0.9498060162868619.

Best trial: 896. Best value: 0.949806:  45%|███████████████████████████████████████████████████████████▉                                                                        | 908/2000 [00:24<00:35, 31.12it/s]

[I 2026-07-05 15:31:55,261] Trial 902 finished with value: 0.9496578565310201 and parameters: {'weight_lgbm_class_0': 0.07494516639573517, 'weight_lgbm_class_1': 0.8910568225323867, 'weight_lgbm_class_2': 0.35579802554189, 'weight_xgb_class_0': 0.06451215417197555, 'weight_xgb_class_1': 0.8622879070252276, 'weight_xgb_class_2': 0.8354902639507303}. Best is trial 896 with value: 0.9498060162868619.
[I 2026-07-05 15:31:55,293] Trial 903 finished with value: 0.9475196222618044 and parameters: {'weight_lgbm_class_0': 0.0741059157822191, 'weight_lgbm_class_1': 0.7962192103924561, 'weight_lgbm_class_2': 0.3592567883810771, 'weight_xgb_class_0': 0.07530870663298406, 'weight_xgb_class_1': 0.9411012458711717, 'weight_xgb_class_2': 0.30822921224096833}. Best is trial 896 with value: 0.9498060162868619.
[I 2026-07-05 15:31:55,328] Trial 904 finished with value: 0.9494866800388039 and parameters: {'weight_lgbm_class_0': 0.0005271574153796494, 'weight_lgbm_class_1': 0.7914329194568174, 'weight_lgbm_class_2': 0.3540021748491043, 'weight_xgb_class_0': 0.07884100340566833, 'weight_xgb_class_1': 0.8554360384029982, 'weight_xgb_class_2': 0.8404525173854153}. Best is trial 896 with value: 0.9498060162868619.
[I 2026-07-05 15:31:55,377] Trial 905 finished with value: 0.9494510973576137 and parameters: {'weight_lgbm_class_0': 0.00042964535799864395, 'weight_lgbm_class_1': 0.7940596517223647, 'weight_lgbm_class_2': 0.3491410881845096, 'weight_xgb_class_0': 0.07719323805746067, 'weight_xgb_class_1': 0.8473857517058724, 'weight_xgb_class_2': 0.8355163650490681}. Best is trial 896 with value: 0.9498060162868619.
[I 2026-07-05 15:31:55,387] Trial 906 finished with value: 0.9495830326380844 and parameters: {'weight_lgbm_class_0': 0.07110786480439496, 'weight_lgbm_class_1': 0.7922327062339752, 'weight_lgbm_class_2': 0.35672386596776684, 'weight_xgb_class_0': 0.066616602843364, 'weight_xgb_class_1': 0.8534084279701704, 'weight_xgb_class_2': 0.768253924374139}. Best is trial 896 with value: 0.9498060162868619.
[I 2026-07-05 15:31:55,399] Trial 907 finished with value: 0.9250028408313131 and parameters: {'weight_lgbm_class_0': 0.07694538020244784, 'weight_lgbm_class_1': 0.6852165290206942, 'weight_lgbm_class_2': 0.35662520134488984, 'weight_xgb_class_0': 0.5128260910669619, 'weight_xgb_class_1': 0.8565440272870591, 'weight_xgb_class_2': 0.7614078892251827}. Best is trial 896 with value: 0.9498060162868619.
[I 2026-07-05 15:31:55,463] Trial 909 finished with value: 0.9491234178541381 and parameters: {'weight_lgbm_class_0': 0.07380930150305605, 'weight_lgbm_class_1': 0.8939911193600677, 'weight_lgbm_class_2': 0.34035462534470867, 'weight_xgb_class_0': 0.07468999423748997, 'weight_xgb_class_1': 0.8500425419987623, 'weight_xgb_class_2': 0.6945522991371205}. Best is trial 896 with value: 0.9498060162868619.

Best trial: 896. Best value: 0.949806:  46%|████████████████████████████████████████████████████████████▍                                                                       | 916/2000 [00:24<00:34, 31.36it/s]

[I 2026-07-05 15:31:55,467] Trial 908 finished with value: 0.8977919104662736 and parameters: {'weight_lgbm_class_0': 0.9546046249980109, 'weight_lgbm_class_1': 0.8931614470473848, 'weight_lgbm_class_2': 0.3467803640203805, 'weight_xgb_class_0': 0.062038759068839246, 'weight_xgb_class_1': 0.8585742405915462, 'weight_xgb_class_2': 0.7573248325119719}. Best is trial 896 with value: 0.9498060162868619.
[I 2026-07-05 15:31:55,491] Trial 910 finished with value: 0.9497178911390263 and parameters: {'weight_lgbm_class_0': 0.07423725454963176, 'weight_lgbm_class_1': 0.8934817776082441, 'weight_lgbm_class_2': 0.34398181634803926, 'weight_xgb_class_0': 0.05196106616934454, 'weight_xgb_class_1': 0.8068046444369593, 'weight_xgb_class_2': 0.7201280167387936}. Best is trial 896 with value: 0.9498060162868619.
[I 2026-07-05 15:31:55,543] Trial 911 finished with value: 0.9496824656817964 and parameters: {'weight_lgbm_class_0': 0.07415466684695321, 'weight_lgbm_class_1': 0.8977760343253878, 'weight_lgbm_class_2': 0.3501216319441812, 'weight_xgb_class_0': 0.05827441197288658, 'weight_xgb_class_1': 0.8099360377043674, 'weight_xgb_class_2': 0.7574464463588062}. Best is trial 896 with value: 0.9498060162868619.
[I 2026-07-05 15:31:55,550] Trial 912 finished with value: 0.9493530733408114 and parameters: {'weight_lgbm_class_0': 0.07994412183214702, 'weight_lgbm_class_1': 0.8957927715415717, 'weight_lgbm_class_2': 0.3749164682915956, 'weight_xgb_class_0': 0.06686134513224046, 'weight_xgb_class_1': 0.9431209497320521, 'weight_xgb_class_2': 0.7343802989985166}. Best is trial 896 with value: 0.9498060162868619.
[I 2026-07-05 15:31:55,612] Trial 913 finished with value: 0.9497767436583383 and parameters: {'weight_lgbm_class_0': 0.05334652258255258, 'weight_lgbm_class_1': 0.8965129874814594, 'weight_lgbm_class_2': 0.3407103148448211, 'weight_xgb_class_0': 0.05462350656368114, 'weight_xgb_class_1': 0.8089827810301783, 'weight_xgb_class_2': 0.7678739302141256}. Best is trial 896 with value: 0.9498060162868619.
[I 2026-07-05 15:31:55,631] Trial 914 finished with value: 0.9497804582591258 and parameters: {'weight_lgbm_class_0': 0.053530630076152906, 'weight_lgbm_class_1': 0.9002250234223664, 'weight_lgbm_class_2': 0.3840333745301955, 'weight_xgb_class_0': 0.05561194869007126, 'weight_xgb_class_1': 0.8063915172173076, 'weight_xgb_class_2': 0.7368068885934272}. Best is trial 896 with value: 0.9498060162868619.
[I 2026-07-05 15:31:55,638] Trial 915 finished with value: 0.9497576854282604 and parameters: {'weight_lgbm_class_0': 0.05204383494807022, 'weight_lgbm_class_1': 0.9084555192001078, 'weight_lgbm_class_2': 0.33783296439996585, 'weight_xgb_class_0': 0.05609948935233477, 'weight_xgb_class_1': 0.8153025849046438, 'weight_xgb_class_2': 0.7647943327488335}. Best is trial 896 with value: 0.9498060162868619.
[I 2026-07-05 15:31:55,678] Trial 916 finished with value: 0.9497061645730285 and parameters: {'weight_lgbm_class_0': 0.05227741559425007, 'weight_lgbm_class_1': 0.9088483480312821, 'weight_lgbm_class_2': 0.3412858839308521, 'weight_xgb_class_0': 0.04332315971906853, 'weight_xgb_class_1': 0.8069318051259162, 'weight_xgb_class_2': 0.756871786054953}. Best is trial 896 with value: 0.9498060162868619.

Best trial: 896. Best value: 0.949806:  46%|████████████████████████████████████████████████████████████▉                                                                       | 924/2000 [00:24<00:33, 32.51it/s]

[I 2026-07-05 15:31:55,740] Trial 917 finished with value: 0.9497991150870516 and parameters: {'weight_lgbm_class_0': 0.052653740408851124, 'weight_lgbm_class_1': 0.9046808250682236, 'weight_lgbm_class_2': 0.37990066872618183, 'weight_xgb_class_0': 0.05201267179851635, 'weight_xgb_class_1': 0.8210087599311634, 'weight_xgb_class_2': 0.7605669241998602}. Best is trial 896 with value: 0.9498060162868619.
[I 2026-07-05 15:31:55,769] Trial 918 finished with value: 0.9497674384504444 and parameters: {'weight_lgbm_class_0': 0.053257288648869944, 'weight_lgbm_class_1': 0.9027529449173014, 'weight_lgbm_class_2': 0.33576792009826967, 'weight_xgb_class_0': 0.05370335528472251, 'weight_xgb_class_1': 0.8129716249747644, 'weight_xgb_class_2': 0.7700010586054962}. Best is trial 896 with value: 0.9498060162868619.
[I 2026-07-05 15:31:55,791] Trial 919 finished with value: 0.9497945375843079 and parameters: {'weight_lgbm_class_0': 0.054887746456857414, 'weight_lgbm_class_1': 0.9081734418908154, 'weight_lgbm_class_2': 0.335050566889193, 'weight_xgb_class_0': 0.0508038347051287, 'weight_xgb_class_1': 0.8102818003492624, 'weight_xgb_class_2': 0.6845160554470748}. Best is trial 896 with value: 0.9498060162868619.
[I 2026-07-05 15:31:55,817] Trial 920 finished with value: 0.9497873108957818 and parameters: {'weight_lgbm_class_0': 0.054963837214860714, 'weight_lgbm_class_1': 0.9099769038883165, 'weight_lgbm_class_2': 0.37915725134900274, 'weight_xgb_class_0': 0.0498772672878839, 'weight_xgb_class_1': 0.8027527465496671, 'weight_xgb_class_2': 0.7271281265809761}. Best is trial 896 with value: 0.9498060162868619.
[I 2026-07-05 15:31:55,854] Trial 922 finished with value: 0.9497240170083567 and parameters: {'weight_lgbm_class_0': 0.055158885804947724, 'weight_lgbm_class_1': 0.9108557502477763, 'weight_lgbm_class_2': 0.3333917252857685, 'weight_xgb_class_0': 0.05278894528022846, 'weight_xgb_class_1': 0.8121760775494791, 'weight_xgb_class_2': 0.9068697631610518}. Best is trial 896 with value: 0.9498060162868619.
[I 2026-07-05 15:31:55,856] Trial 921 finished with value: 0.9497578028219911 and parameters: {'weight_lgbm_class_0': 0.04879014110930482, 'weight_lgbm_class_1': 0.9162437057177231, 'weight_lgbm_class_2': 0.3756789720318002, 'weight_xgb_class_0': 0.050680019095668535, 'weight_xgb_class_1': 0.8178463198839948, 'weight_xgb_class_2': 0.7465833556049972}. Best is trial 896 with value: 0.9498060162868619.
[I 2026-07-05 15:31:55,905] Trial 923 finished with value: 0.9496887056500466 and parameters: {'weight_lgbm_class_0': 0.0508826409751978, 'weight_lgbm_class_1': 0.9248867696778338, 'weight_lgbm_class_2': 0.37620294360717854, 'weight_xgb_class_0': 0.051336270194926634, 'weight_xgb_class_1': 0.807272393319098, 'weight_xgb_class_2': 0.8961667115091592}. Best is trial 896 with value: 0.9498060162868619.
[I 2026-07-05 15:31:55,907] Trial 924 finished with value: 0.9496961331528181 and parameters: {'weight_lgbm_class_0': 0.048524400769590595, 'weight_lgbm_class_1': 0.9351309822579076, 'weight_lgbm_class_2': 0.37933846917000147, 'weight_xgb_class_0': 0.05452510114994363, 'weight_xgb_class_1': 0.803522491234229, 'weight_xgb_class_2': 0.8981619719049104}. Best is trial 896 with value: 0.9498060162868619.

Best trial: 896. Best value: 0.949806:  47%|█████████████████████████████████████████████████████████████▍                                                                      | 931/2000 [00:24<00:35, 30.20it/s]

[I 2026-07-05 15:31:55,976] Trial 925 finished with value: 0.9497981345447459 and parameters: {'weight_lgbm_class_0': 0.048324243047814665, 'weight_lgbm_class_1': 0.9167195374145031, 'weight_lgbm_class_2': 0.334296086669361, 'weight_xgb_class_0': 0.05460631371606436, 'weight_xgb_class_1': 0.7787789125894593, 'weight_xgb_class_2': 0.7284950876787418}. Best is trial 896 with value: 0.9498060162868619.
[I 2026-07-05 15:31:55,992] Trial 926 finished with value: 0.9496433718587833 and parameters: {'weight_lgbm_class_0': 0.04803034462409061, 'weight_lgbm_class_1': 0.9220035264806048, 'weight_lgbm_class_2': 0.33218201260515057, 'weight_xgb_class_0': 0.05266131050017065, 'weight_xgb_class_1': 0.31120461032353514, 'weight_xgb_class_2': 0.7003388708426942}. Best is trial 896 with value: 0.9498060162868619.
[I 2026-07-05 15:31:56,046] Trial 927 finished with value: 0.9497489613059432 and parameters: {'weight_lgbm_class_0': 0.051053683608911694, 'weight_lgbm_class_1': 0.9179480404703897, 'weight_lgbm_class_2': 0.3820250292754882, 'weight_xgb_class_0': 0.0654280435660525, 'weight_xgb_class_1': 0.8015331812152379, 'weight_xgb_class_2': 0.7461681898229316}. Best is trial 896 with value: 0.9498060162868619.
[I 2026-07-05 15:31:56,051] Trial 928 finished with value: 0.9497476603636196 and parameters: {'weight_lgbm_class_0': 0.04922460375862704, 'weight_lgbm_class_1': 0.9176429331790077, 'weight_lgbm_class_2': 0.3306610812867554, 'weight_xgb_class_0': 0.04702761863520219, 'weight_xgb_class_1': 0.7924163873786397, 'weight_xgb_class_2': 0.6896418412072026}. Best is trial 896 with value: 0.9498060162868619.
[I 2026-07-05 15:31:56,141] Trial 930 finished with value: 0.9497249051091133 and parameters: {'weight_lgbm_class_0': 0.050404929700148315, 'weight_lgbm_class_1': 0.9112064187315866, 'weight_lgbm_class_2': 0.3314828657725621, 'weight_xgb_class_0': 0.06687852338680625, 'weight_xgb_class_1': 0.7870708620303084, 'weight_xgb_class_2': 0.7022065934213482}. Best is trial 896 with value: 0.9498060162868619.
[I 2026-07-05 15:31:56,150] Trial 931 finished with value: 0.9497684581444289 and parameters: {'weight_lgbm_class_0': 0.05240495493549757, 'weight_lgbm_class_1': 0.9178299733036168, 'weight_lgbm_class_2': 0.37935357066147585, 'weight_xgb_class_0': 0.0627118969002622, 'weight_xgb_class_1': 0.7894327478240402, 'weight_xgb_class_2': 0.7137232534470755}. Best is trial 896 with value: 0.9498060162868619.
[I 2026-07-05 15:31:56,156] Trial 929 finished with value: 0.9497927744920885 and parameters: {'weight_lgbm_class_0': 0.04927517557587315, 'weight_lgbm_class_1': 0.9108555781147694, 'weight_lgbm_class_2': 0.33511560998075646, 'weight_xgb_class_0': 0.054309066785190006, 'weight_xgb_class_1': 0.7948102317690746, 'weight_xgb_class_2': 0.6614149163969327}. Best is trial 896 with value: 0.9498060162868619.

Best trial: 933. Best value: 0.949806:  47%|█████████████████████████████████████████████████████████████▉                                                                      | 938/2000 [00:25<00:33, 31.60it/s]

[I 2026-07-05 15:31:56,191] Trial 932 finished with value: 0.9497998897597258 and parameters: {'weight_lgbm_class_0': 0.05313482416119596, 'weight_lgbm_class_1': 0.9120324564237873, 'weight_lgbm_class_2': 0.33356694924988844, 'weight_xgb_class_0': 0.05181184057815572, 'weight_xgb_class_1': 0.7860998624586812, 'weight_xgb_class_2': 0.6315771166618197}. Best is trial 896 with value: 0.9498060162868619.
[I 2026-07-05 15:31:56,241] Trial 933 finished with value: 0.9498064580872844 and parameters: {'weight_lgbm_class_0': 0.051914656647452505, 'weight_lgbm_class_1': 0.9298443719872209, 'weight_lgbm_class_2': 0.38238709699325796, 'weight_xgb_class_0': 0.05673690069668973, 'weight_xgb_class_1': 0.7945098062762219, 'weight_xgb_class_2': 0.7055896936245813}. Best is trial 933 with value: 0.9498064580872844.
[I 2026-07-05 15:31:56,260] Trial 934 finished with value: 0.9497658869536143 and parameters: {'weight_lgbm_class_0': 0.05896852567890288, 'weight_lgbm_class_1': 0.9248539793723886, 'weight_lgbm_class_2': 0.3873951611647529, 'weight_xgb_class_0': 0.05907323797988145, 'weight_xgb_class_1': 0.7868984631129546, 'weight_xgb_class_2': 0.7058744662391202}. Best is trial 933 with value: 0.9498064580872844.
[I 2026-07-05 15:31:56,280] Trial 936 finished with value: 0.9498047686957142 and parameters: {'weight_lgbm_class_0': 0.047397622422626566, 'weight_lgbm_class_1': 0.9142878847069501, 'weight_lgbm_class_2': 0.3914173497904155, 'weight_xgb_class_0': 0.0554093879946989, 'weight_xgb_class_1': 0.7870972704003004, 'weight_xgb_class_2': 0.6551073291608152}. Best is trial 933 with value: 0.9498064580872844.
[I 2026-07-05 15:31:56,288] Trial 935 finished with value: 0.9497666467974453 and parameters: {'weight_lgbm_class_0': 0.04667290377555558, 'weight_lgbm_class_1': 0.9217627774693886, 'weight_lgbm_class_2': 0.39127319737656197, 'weight_xgb_class_0': 0.06124691776331018, 'weight_xgb_class_1': 0.7850688723953, 'weight_xgb_class_2': 0.7147373021052095}. Best is trial 933 with value: 0.9498064580872844.
[I 2026-07-05 15:31:56,369] Trial 938 finished with value: 0.9497425878197877 and parameters: {'weight_lgbm_class_0': 0.0538025801402825, 'weight_lgbm_class_1': 0.927545158502822, 'weight_lgbm_class_2': 0.33387523505303424, 'weight_xgb_class_0': 0.06881770657992693, 'weight_xgb_class_1': 0.7906387503429103, 'weight_xgb_class_2': 0.6958423483778947}. Best is trial 933 with value: 0.9498064580872844.
[I 2026-07-05 15:31:56,398] Trial 937 finished with value: 0.9497625867001704 and parameters: {'weight_lgbm_class_0': 0.04741494389156326, 'weight_lgbm_class_1': 0.9288040051851653, 'weight_lgbm_class_2': 0.33043983632976937, 'weight_xgb_class_0': 0.06547321040504256, 'weight_xgb_class_1': 0.7901889078323059, 'weight_xgb_class_2': 0.6836015577666732}. Best is trial 933 with value: 0.9498064580872844.

Best trial: 933. Best value: 0.949806:  47%|██████████████████████████████████████████████████████████████▎                                                                     | 945/2000 [00:25<00:31, 33.10it/s]

[I 2026-07-05 15:31:56,398] Trial 939 finished with value: 0.9497159787411112 and parameters: {'weight_lgbm_class_0': 0.05162146555068275, 'weight_lgbm_class_1': 0.9283783758953598, 'weight_lgbm_class_2': 0.33319423239581897, 'weight_xgb_class_0': 0.07448603505579504, 'weight_xgb_class_1': 0.7864910303228522, 'weight_xgb_class_2': 0.7272850297583069}. Best is trial 933 with value: 0.9498064580872844.
[I 2026-07-05 15:31:56,428] Trial 940 finished with value: 0.9497436557892822 and parameters: {'weight_lgbm_class_0': 0.05082423365221554, 'weight_lgbm_class_1': 0.9344170496040038, 'weight_lgbm_class_2': 0.3768027409797991, 'weight_xgb_class_0': 0.06875627895276307, 'weight_xgb_class_1': 0.7735743019033133, 'weight_xgb_class_2': 0.7230611056309939}. Best is trial 933 with value: 0.9498064580872844.
[I 2026-07-05 15:31:56,483] Trial 941 finished with value: 0.9492450359174085 and parameters: {'weight_lgbm_class_0': 0.061151437920038965, 'weight_lgbm_class_1': 0.9303065323373136, 'weight_lgbm_class_2': 0.38690959646840944, 'weight_xgb_class_0': 0.08056803059332399, 'weight_xgb_class_1': 0.7735068810675834, 'weight_xgb_class_2': 0.6389225944222451}. Best is trial 933 with value: 0.9498064580872844.
[I 2026-07-05 15:31:56,506] Trial 942 finished with value: 0.9493688346122564 and parameters: {'weight_lgbm_class_0': 0.05394693924602401, 'weight_lgbm_class_1': 0.937587202430683, 'weight_lgbm_class_2': 0.39499427875237886, 'weight_xgb_class_0': 0.08140704198527474, 'weight_xgb_class_1': 0.7768534696509354, 'weight_xgb_class_2': 0.6264208406510354}. Best is trial 933 with value: 0.9498064580872844.
[I 2026-07-05 15:31:56,524] Trial 943 finished with value: 0.9494871546966411 and parameters: {'weight_lgbm_class_0': 0.05655457794035783, 'weight_lgbm_class_1': 0.9342266472364968, 'weight_lgbm_class_2': 0.39239033816161095, 'weight_xgb_class_0': 0.08056925201923425, 'weight_xgb_class_1': 0.7766414984532389, 'weight_xgb_class_2': 0.689565714199172}. Best is trial 933 with value: 0.9498064580872844.
[I 2026-07-05 15:31:56,563] Trial 944 finished with value: 0.949642216433641 and parameters: {'weight_lgbm_class_0': 0.04682655564472059, 'weight_lgbm_class_1': 0.9290919271801681, 'weight_lgbm_class_2': 0.3968408813106877, 'weight_xgb_class_0': 0.08124943571487739, 'weight_xgb_class_1': 0.7790228055025473, 'weight_xgb_class_2': 0.6508015110690972}. Best is trial 933 with value: 0.9498064580872844.
[I 2026-07-05 15:31:56,623] Trial 947 finished with value: 0.9496813173810051 and parameters: {'weight_lgbm_class_0': 0.04435326212912731, 'weight_lgbm_class_1': 0.9314750502123732, 'weight_lgbm_class_2': 0.377613723024271, 'weight_xgb_class_0': 0.07926074710626124, 'weight_xgb_class_1': 0.7668759834051133, 'weight_xgb_class_2': 0.6439808500875807}. Best is trial 933 with value: 0.9498064580872844.

Best trial: 933. Best value: 0.949806:  48%|██████████████████████████████████████████████████████████████▉                                                                     | 954/2000 [00:25<00:31, 33.59it/s]

[I 2026-07-05 15:31:56,654] Trial 946 finished with value: 0.9497661523036524 and parameters: {'weight_lgbm_class_0': 0.045924766626007314, 'weight_lgbm_class_1': 0.9396484791853251, 'weight_lgbm_class_2': 0.39863604374590267, 'weight_xgb_class_0': 0.07670257236655761, 'weight_xgb_class_1': 0.779303811904262, 'weight_xgb_class_2': 0.6502005849261749}. Best is trial 933 with value: 0.9498064580872844.
[I 2026-07-05 15:31:56,671] Trial 945 finished with value: 0.9495692127851812 and parameters: {'weight_lgbm_class_0': 0.05011373654116623, 'weight_lgbm_class_1': 0.9289160849582282, 'weight_lgbm_class_2': 0.3768661309750077, 'weight_xgb_class_0': 0.08021771778020335, 'weight_xgb_class_1': 0.7749322138527447, 'weight_xgb_class_2': 0.6634562366317766}. Best is trial 933 with value: 0.9498064580872844.
[I 2026-07-05 15:31:56,680] Trial 948 finished with value: 0.9498034552604112 and parameters: {'weight_lgbm_class_0': 0.0414774367230819, 'weight_lgbm_class_1': 0.9339550287865437, 'weight_lgbm_class_2': 0.3697989058925263, 'weight_xgb_class_0': 0.06973207547285032, 'weight_xgb_class_1': 0.7714827290705168, 'weight_xgb_class_2': 0.6157458197051048}. Best is trial 933 with value: 0.9498064580872844.
[I 2026-07-05 15:31:56,729] Trial 949 finished with value: 0.9490541305288765 and parameters: {'weight_lgbm_class_0': 0.04137975948391643, 'weight_lgbm_class_1': 0.15260943878309707, 'weight_lgbm_class_2': 0.3782841132982744, 'weight_xgb_class_0': 0.08734318936434474, 'weight_xgb_class_1': 0.7695851767212827, 'weight_xgb_class_2': 0.6352823621491556}. Best is trial 933 with value: 0.9498064580872844.
[I 2026-07-05 15:31:56,759] Trial 950 finished with value: 0.9496607495455782 and parameters: {'weight_lgbm_class_0': 0.0400242187070653, 'weight_lgbm_class_1': 0.9374657932844819, 'weight_lgbm_class_2': 0.3777169972552923, 'weight_xgb_class_0': 0.08354174514152447, 'weight_xgb_class_1': 0.7631756743286624, 'weight_xgb_class_2': 0.6333832122008269}. Best is trial 933 with value: 0.9498064580872844.
[I 2026-07-05 15:31:56,782] Trial 951 finished with value: 0.9495662325823395 and parameters: {'weight_lgbm_class_0': 0.042071973809526916, 'weight_lgbm_class_1': 0.9405074517397617, 'weight_lgbm_class_2': 0.3821383765176195, 'weight_xgb_class_0': 0.08463870057226464, 'weight_xgb_class_1': 0.7654137256376088, 'weight_xgb_class_2': 0.6315099658307978}. Best is trial 933 with value: 0.9498064580872844.
[I 2026-07-05 15:31:56,801] Trial 952 finished with value: 0.9496678982801622 and parameters: {'weight_lgbm_class_0': 0.039937619203356624, 'weight_lgbm_class_1': 0.9299397897248785, 'weight_lgbm_class_2': 0.3833645761990464, 'weight_xgb_class_0': 0.08598481003658279, 'weight_xgb_class_1': 0.7564379750204275, 'weight_xgb_class_2': 0.6526789684985862}. Best is trial 933 with value: 0.9498064580872844.
[I 2026-07-05 15:31:56,844] Trial 953 finished with value: 0.9495872831304425 and parameters: {'weight_lgbm_class_0': 0.043291922395830296, 'weight_lgbm_class_1': 0.9475393468064106, 'weight_lgbm_class_2': 0.37993208985713, 'weight_xgb_class_0': 0.08717809518214698, 'weight_xgb_class_1': 0.7637588867685347, 'weight_xgb_class_2': 0.6667290522605793}. Best is trial 933 with value: 0.9498064580872844.
[I 2026-07-05 15:31:56,859] Trial 954 finished with value: 0.9497988838950774 and parameters: {'weight_lgbm_class_0': 0.043051670912868524, 'weight_lgbm_class_1': 0.9380073290157399, 'weight_lgbm_class_2': 0.37020426104980014, 'weight_xgb_class_0': 0.0575883677448584, 'weight_xgb_class_1': 0.7522767961355317, 'weight_xgb_class_2': 0.6443796128161634}. Best is trial 933 with value: 0.9498064580872844.

[I 2026-07-05 15:31:56,916] Trial 955 finished with value: 0.9495381061856422 and parameters: {'weight_lgbm_class_0': 0.0393711678073527, 'weight_lgbm_class_1': 0.9415438342425382, 'weight_lgbm_class_2': 0.3754235024450906, 'weight_xgb_class_0': 0.0904635591054038, 'weight_xgb_class_1': 0.762199265695081, 'weight_xgb_class_2': 0.6529628038728241}. Best is trial 933 with value: 0.9498064580872844.
[I 2026-07-05 15:31:56,919] Trial 956 finished with value: 0.9497390468885568 and parameters: {'weight_lgbm_class_0': 0.03736667376032575, 'weight_lgbm_class_1': 0.94431080073671, 'weight_lgbm_class_2': 0.3678233396675804, 'weight_xgb_class_0': 0.08694316644856641, 'weight_xgb_class_1': 0.7588133378171773, 'weight_xgb_class_2': 0.6662649696449084}. Best is trial 933 with value: 0.9498064580872844.
[I 2026-07-05 15:31:56,994] Trial 957 finished with value: 0.9495517396627022 and parameters: {'weight_lgbm_class_0': 0.035635102826671455, 'weight_lgbm_class_1': 0.9372756322538767, 'weight_lgbm_class_2': 0.3725089912339117, 'weight_xgb_class_0': 0.09485940984747344, 'weight_xgb_class_1': 0.764800678172207, 'weight_xgb_class_2': 0.6662489383169167}. Best is trial 933 with value: 0.9498064580872844.
[I 2026-07-05 15:31:57,025] Trial 958 finished with value: 0.9497904537606975 and parameters: {'weight_lgbm_class_0': 0.039153724319797405, 'weight_lgbm_class_1': 0.9425873588937604, 'weight_lgbm_class_2': 0.3762604003607726, 'weight_xgb_class_0': 0.06537703657657865, 'weight_xgb_class_1': 0.749374770847798, 'weight_xgb_class_2': 0.6753391131997271}. Best is trial 933 with value: 0.9498064580872844.
[I 2026-07-05 15:31:57,035] Trial 959 finished with value: 0.9497638261264343 and parameters: {'weight_lgbm_class_0': 0.040878733663664304, 'weight_lgbm_class_1': 0.9446255512831646, 'weight_lgbm_class_2': 0.3719889274106706, 'weight_xgb_class_0': 0.05754218443543803, 'weight_xgb_class_1': 0.7539570328827905, 'weight_xgb_class_2': 0.6730788393602993}. Best is trial 933 with value: 0.9498064580872844.
[I 2026-07-05 15:31:57,069] Trial 960 finished with value: 0.949822106074469 and parameters: {'weight_lgbm_class_0': 0.038631959005020235, 'weight_lgbm_class_1': 0.9465290380563535, 'weight_lgbm_class_2': 0.36914256230460984, 'weight_xgb_class_0': 0.06741533540589849, 'weight_xgb_class_1': 0.7522255054648278, 'weight_xgb_class_2': 0.6198736749425829}. Best is trial 960 with value: 0.949822106074469.

Best trial: 960. Best value: 0.949822:  48%|███████████████████████████████████████████████████████████████▉                                                                    | 968/2000 [00:25<00:31, 32.93it/s]

[I 2026-07-05 15:31:57,128] Trial 961 finished with value: 0.9496761843210866 and parameters: {'weight_lgbm_class_0': 0.02814065527588948, 'weight_lgbm_class_1': 0.9470558980616143, 'weight_lgbm_class_2': 0.3685745064445893, 'weight_xgb_class_0': 0.05767403064420045, 'weight_xgb_class_1': 0.7446340275484752, 'weight_xgb_class_2': 0.6779671217748926}. Best is trial 960 with value: 0.949822106074469.
[I 2026-07-05 15:31:57,162] Trial 964 finished with value: 0.949736584091184 and parameters: {'weight_lgbm_class_0': 0.06543961151272316, 'weight_lgbm_class_1': 0.9514841560954563, 'weight_lgbm_class_2': 0.3707652373872044, 'weight_xgb_class_0': 0.05936410365081994, 'weight_xgb_class_1': 0.7606880775506826, 'weight_xgb_class_2': 0.6703038458965084}. Best is trial 960 with value: 0.949822106074469.
[I 2026-07-05 15:31:57,163] Trial 962 finished with value: 0.949774194968013 and parameters: {'weight_lgbm_class_0': 0.0633987996905985, 'weight_lgbm_class_1': 0.948385352509688, 'weight_lgbm_class_2': 0.3649459570187542, 'weight_xgb_class_0': 0.0517305658939196, 'weight_xgb_class_1': 0.7419798387912397, 'weight_xgb_class_2': 0.6624177364047568}. Best is trial 960 with value: 0.949822106074469.
[I 2026-07-05 15:31:57,170] Trial 963 finished with value: 0.9497445635894204 and parameters: {'weight_lgbm_class_0': 0.06413848878079781, 'weight_lgbm_class_1': 0.9399337019476839, 'weight_lgbm_class_2': 0.36837757410765354, 'weight_xgb_class_0': 0.05835122942167199, 'weight_xgb_class_1': 0.7492315321292473, 'weight_xgb_class_2': 0.6642586571165718}. Best is trial 960 with value: 0.949822106074469.
[I 2026-07-05 15:31:57,217] Trial 965 finished with value: 0.9496041555297347 and parameters: {'weight_lgbm_class_0': 0.06401374030815596, 'weight_lgbm_class_1': 0.955039590642802, 'weight_lgbm_class_2': 0.36318644000008304, 'weight_xgb_class_0': 0.056494783162198955, 'weight_xgb_class_1': 0.751964702344383, 'weight_xgb_class_2': 0.6133088446485774}. Best is trial 960 with value: 0.949822106074469.
[I 2026-07-05 15:31:57,225] Trial 966 finished with value: 0.9497424793235493 and parameters: {'weight_lgbm_class_0': 0.06637664279607529, 'weight_lgbm_class_1': 0.9510250962100667, 'weight_lgbm_class_2': 0.3657863822513101, 'weight_xgb_class_0': 0.057521961263907656, 'weight_xgb_class_1': 0.7625914120848499, 'weight_xgb_class_2': 0.6729473040909822}. Best is trial 960 with value: 0.949822106074469.
[I 2026-07-05 15:31:57,288] Trial 967 finished with value: 0.9491898561614605 and parameters: {'weight_lgbm_class_0': 0.06682286695398407, 'weight_lgbm_class_1': 0.9496155307844956, 'weight_lgbm_class_2': 0.3615714395871235, 'weight_xgb_class_0': 0.06392672549447538, 'weight_xgb_class_1': 0.7420506820377358, 'weight_xgb_class_2': 0.5644987260912803}. Best is trial 960 with value: 0.949822106074469.
[I 2026-07-05 15:31:57,303] Trial 968 finished with value: 0.9493861611480964 and parameters: {'weight_lgbm_class_0': 0.06662342500644122, 'weight_lgbm_class_1': 0.9127838190611035, 'weight_lgbm_class_2': 0.36411932572506595, 'weight_xgb_class_0': 0.060873919999917224, 'weight_xgb_class_1': 0.7452799438490891, 'weight_xgb_class_2': 0.5900288393522855}. Best is trial 960 with value: 0.949822106074469.

Best trial: 960. Best value: 0.949822:  49%|████████████████████████████████████████████████████████████████▎                                                                   | 974/2000 [00:26<00:32, 31.95it/s]

[I 2026-07-05 15:31:57,347] Trial 969 finished with value: 0.9495730611635245 and parameters: {'weight_lgbm_class_0': 0.06626654195358654, 'weight_lgbm_class_1': 0.9507601253108717, 'weight_lgbm_class_2': 0.362461598674876, 'weight_xgb_class_0': 0.056708121723932844, 'weight_xgb_class_1': 0.7279777347787368, 'weight_xgb_class_2': 0.6145281506501755}. Best is trial 960 with value: 0.949822106074469.
[I 2026-07-05 15:31:57,394] Trial 970 finished with value: 0.9496124128787023 and parameters: {'weight_lgbm_class_0': 0.07020383811658083, 'weight_lgbm_class_1': 0.9491388141372947, 'weight_lgbm_class_2': 0.3563803486306421, 'weight_xgb_class_0': 0.05795006912948866, 'weight_xgb_class_1': 0.7602096177742701, 'weight_xgb_class_2': 0.6796783822254104}. Best is trial 960 with value: 0.949822106074469.
[I 2026-07-05 15:31:57,395] Trial 971 finished with value: 0.9495282819762724 and parameters: {'weight_lgbm_class_0': 0.06591019693095687, 'weight_lgbm_class_1': 0.9494574136521745, 'weight_lgbm_class_2': 0.3570281296223729, 'weight_xgb_class_0': 0.057074336010482986, 'weight_xgb_class_1': 0.7252492176861092, 'weight_xgb_class_2': 0.6097427436247483}. Best is trial 960 with value: 0.949822106074469.
[I 2026-07-05 15:31:57,427] Trial 972 finished with value: 0.9494567966660861 and parameters: {'weight_lgbm_class_0': 0.0632674911117924, 'weight_lgbm_class_1': 0.9528830591233528, 'weight_lgbm_class_2': 0.3568993179349653, 'weight_xgb_class_0': 0.05626712141947631, 'weight_xgb_class_1': 0.7280698883306312, 'weight_xgb_class_2': 0.5620726143212459}. Best is trial 960 with value: 0.949822106074469.
[I 2026-07-05 15:31:57,483] Trial 973 finished with value: 0.9496202049808424 and parameters: {'weight_lgbm_class_0': 0.06630235909170648, 'weight_lgbm_class_1': 0.9501905155768812, 'weight_lgbm_class_2': 0.3503700581573331, 'weight_xgb_class_0': 0.0521545256524739, 'weight_xgb_class_1': 0.7241135626141855, 'weight_xgb_class_2': 0.609859426701731}. Best is trial 960 with value: 0.949822106074469.
[I 2026-07-05 15:31:57,544] Trial 974 finished with value: 0.9494225761889462 and parameters: {'weight_lgbm_class_0': 0.06941487556157383, 'weight_lgbm_class_1': 0.9458267782417226, 'weight_lgbm_class_2': 0.3433017513723574, 'weight_xgb_class_0': 0.05700839679476401, 'weight_xgb_class_1': 0.7288637746287332, 'weight_xgb_class_2': 0.6118162192746774}. Best is trial 960 with value: 0.949822106074469.

Best trial: 960. Best value: 0.949822:  49%|████████████████████████████████████████████████████████████████▉                                                                   | 983/2000 [00:26<00:30, 32.97it/s]

[I 2026-07-05 15:31:57,554] Trial 976 finished with value: 0.9493961825067396 and parameters: {'weight_lgbm_class_0': 0.06692886457099467, 'weight_lgbm_class_1': 0.9529255117448278, 'weight_lgbm_class_2': 0.3464488214309234, 'weight_xgb_class_0': 0.0600371655646547, 'weight_xgb_class_1': 0.7241227946899796, 'weight_xgb_class_2': 0.6046438844300561}. Best is trial 960 with value: 0.949822106074469.
[I 2026-07-05 15:31:57,555] Trial 975 finished with value: 0.915891454210724 and parameters: {'weight_lgbm_class_0': 0.06993748337388077, 'weight_lgbm_class_1': 0.9532925978115621, 'weight_lgbm_class_2': 0.3373902596783874, 'weight_xgb_class_0': 0.5842189680682733, 'weight_xgb_class_1': 0.7220611505559271, 'weight_xgb_class_2': 0.6109256954494586}. Best is trial 960 with value: 0.949822106074469.
[I 2026-07-05 15:31:57,626] Trial 977 finished with value: 0.9495303211176225 and parameters: {'weight_lgbm_class_0': 0.06812347449815001, 'weight_lgbm_class_1': 0.9124111526583791, 'weight_lgbm_class_2': 0.3431647349845041, 'weight_xgb_class_0': 0.052950352604285995, 'weight_xgb_class_1': 0.7086216012922054, 'weight_xgb_class_2': 0.6086593509213526}. Best is trial 960 with value: 0.949822106074469.
[I 2026-07-05 15:31:57,643] Trial 979 finished with value: 0.9494512790197724 and parameters: {'weight_lgbm_class_0': 0.021150011738985272, 'weight_lgbm_class_1': 0.9110847020290975, 'weight_lgbm_class_2': 0.3377220881830446, 'weight_xgb_class_0': 0.05235058591659654, 'weight_xgb_class_1': 0.7397986577800475, 'weight_xgb_class_2': 0.5957267624848939}. Best is trial 960 with value: 0.949822106074469.
[I 2026-07-05 15:31:57,645] Trial 978 finished with value: 0.9495118783575238 and parameters: {'weight_lgbm_class_0': 0.0652239177095083, 'weight_lgbm_class_1': 0.912614530932658, 'weight_lgbm_class_2': 0.342457656497708, 'weight_xgb_class_0': 0.05751187774339192, 'weight_xgb_class_1': 0.706670433963341, 'weight_xgb_class_2': 0.6140463251459302}. Best is trial 960 with value: 0.949822106074469.
[I 2026-07-05 15:31:57,676] Trial 980 finished with value: 0.949492355839566 and parameters: {'weight_lgbm_class_0': 0.018876330078730134, 'weight_lgbm_class_1': 0.9089217237434409, 'weight_lgbm_class_2': 0.34039806904035075, 'weight_xgb_class_0': 0.05636520085281156, 'weight_xgb_class_1': 0.7381883247115704, 'weight_xgb_class_2': 0.6152628985666205}. Best is trial 960 with value: 0.949822106074469.
[I 2026-07-05 15:31:57,715] Trial 981 finished with value: 0.9163769263818339 and parameters: {'weight_lgbm_class_0': 0.593340987294968, 'weight_lgbm_class_1': 0.9129191391713786, 'weight_lgbm_class_2': 0.34082304506142846, 'weight_xgb_class_0': 0.04915508265913922, 'weight_xgb_class_1': 0.7091853404796363, 'weight_xgb_class_2': 0.6153337220187928}. Best is trial 960 with value: 0.949822106074469.
[I 2026-07-05 15:31:57,760] Trial 982 finished with value: 0.9494930646478048 and parameters: {'weight_lgbm_class_0': 0.02434240984208065, 'weight_lgbm_class_1': 0.9116929031683869, 'weight_lgbm_class_2': 0.34040920255227625, 'weight_xgb_class_0': 0.04647678145337939, 'weight_xgb_class_1': 0.7250239770639297, 'weight_xgb_class_2': 0.6206517142971467}. Best is trial 960 with value: 0.949822106074469.
[I 2026-07-05 15:31:57,776] Trial 983 finished with value: 0.9492765387126431 and parameters: {'weight_lgbm_class_0': 0.01849718774184731, 'weight_lgbm_class_1': 0.9152948254542366, 'weight_lgbm_class_2': 0.33889993347502423, 'weight_xgb_class_0': 0.044480706101007565, 'weight_xgb_class_1': 0.7026781097082611, 'weight_xgb_class_2': 0.6191418380569831}. Best is trial 960 with value: 0.949822106074469.

Best trial: 960. Best value: 0.949822:  49%|█████████████████████████████████████████████████████████████████▏                                                                  | 988/2000 [00:26<00:34, 29.56it/s]

[I 2026-07-05 15:31:57,789] Trial 984 finished with value: 0.9492257555911938 and parameters: {'weight_lgbm_class_0': 0.01631355648625522, 'weight_lgbm_class_1': 0.9155582502778338, 'weight_lgbm_class_2': 0.34034230239351076, 'weight_xgb_class_0': 0.04566246446661389, 'weight_xgb_class_1': 0.7075273288186845, 'weight_xgb_class_2': 0.616371309929097}. Best is trial 960 with value: 0.949822106074469.
[I 2026-07-05 15:31:57,855] Trial 985 finished with value: 0.9495045460694156 and parameters: {'weight_lgbm_class_0': 0.021533208121155927, 'weight_lgbm_class_1': 0.9135492655319568, 'weight_lgbm_class_2': 0.3426758762390533, 'weight_xgb_class_0': 0.0493192821719833, 'weight_xgb_class_1': 0.7051712395909109, 'weight_xgb_class_2': 0.632393883498678}. Best is trial 960 with value: 0.949822106074469.
[I 2026-07-05 15:31:57,908] Trial 986 finished with value: 0.9495549989141275 and parameters: {'weight_lgbm_class_0': 0.030254623764181313, 'weight_lgbm_class_1': 0.9075199928778918, 'weight_lgbm_class_2': 0.3307236977649306, 'weight_xgb_class_0': 0.04554273118226005, 'weight_xgb_class_1': 0.6745331682887464, 'weight_xgb_class_2': 0.6320897438771876}. Best is trial 960 with value: 0.949822106074469.
[I 2026-07-05 15:31:57,929] Trial 987 finished with value: 0.9497772757078028 and parameters: {'weight_lgbm_class_0': 0.022003071440619908, 'weight_lgbm_class_1': 0.907730484007691, 'weight_lgbm_class_2': 0.3240741324197781, 'weight_xgb_class_0': 0.07465996670051603, 'weight_xgb_class_1': 0.6886851111179042, 'weight_xgb_class_2': 0.6886059699024494}. Best is trial 960 with value: 0.949822106074469.
[I 2026-07-05 15:31:57,989] Trial 988 finished with value: 0.9494478875588049 and parameters: {'weight_lgbm_class_0': 0.022402952343103973, 'weight_lgbm_class_1': 0.9178634195475085, 'weight_lgbm_class_2': 0.32769452215033695, 'weight_xgb_class_0': 0.04918252685788782, 'weight_xgb_class_1': 0.6886956668502358, 'weight_xgb_class_2': 0.6863960799375828}. Best is trial 960 with value: 0.949822106074469.

Best trial: 960. Best value: 0.949822:  50%|█████████████████████████████████████████████████████████████████▋                                                                  | 996/2000 [00:26<00:31, 32.12it/s]

[I 2026-07-05 15:31:58,016] Trial 991 finished with value: 0.9497419497465226 and parameters: {'weight_lgbm_class_0': 0.027374460151406252, 'weight_lgbm_class_1': 0.91399876318531, 'weight_lgbm_class_2': 0.31729607711397406, 'weight_xgb_class_0': 0.07734628896492568, 'weight_xgb_class_1': 0.6780582146938217, 'weight_xgb_class_2': 0.6875149751091797}. Best is trial 960 with value: 0.949822106074469.
[I 2026-07-05 15:31:58,025] Trial 990 finished with value: 0.9497848989694336 and parameters: {'weight_lgbm_class_0': 0.02105060617377982, 'weight_lgbm_class_1': 0.9146553937401467, 'weight_lgbm_class_2': 0.31915713289055975, 'weight_xgb_class_0': 0.07707013908329984, 'weight_xgb_class_1': 0.7417677420194241, 'weight_xgb_class_2': 0.6395350966456238}. Best is trial 960 with value: 0.949822106074469.
[I 2026-07-05 15:31:58,031] Trial 989 finished with value: 0.9497732988872203 and parameters: {'weight_lgbm_class_0': 0.019013772230922335, 'weight_lgbm_class_1': 0.9081565168814001, 'weight_lgbm_class_2': 0.32336553851837746, 'weight_xgb_class_0': 0.07846577150596516, 'weight_xgb_class_1': 0.6837417527976424, 'weight_xgb_class_2': 0.7036413236205822}. Best is trial 960 with value: 0.949822106074469.
[I 2026-07-05 15:31:58,086] Trial 992 finished with value: 0.9498029952745632 and parameters: {'weight_lgbm_class_0': 0.028346513784182674, 'weight_lgbm_class_1': 0.9319377863943086, 'weight_lgbm_class_2': 0.31646287177697674, 'weight_xgb_class_0': 0.0747778719234915, 'weight_xgb_class_1': 0.7430494535779736, 'weight_xgb_class_2': 0.7064230546313058}. Best is trial 960 with value: 0.949822106074469.
[I 2026-07-05 15:31:58,087] Trial 993 finished with value: 0.9497659435918876 and parameters: {'weight_lgbm_class_0': 0.02101743594932635, 'weight_lgbm_class_1': 0.9271538650561493, 'weight_lgbm_class_2': 0.31544753904501793, 'weight_xgb_class_0': 0.07823338674749077, 'weight_xgb_class_1': 0.7395493011032896, 'weight_xgb_class_2': 0.7098503002569476}. Best is trial 960 with value: 0.949822106074469.
[I 2026-07-05 15:31:58,156] Trial 994 finished with value: 0.9497815410574635 and parameters: {'weight_lgbm_class_0': 0.03666525758105953, 'weight_lgbm_class_1': 0.9258351800640737, 'weight_lgbm_class_2': 0.3075653702752071, 'weight_xgb_class_0': 0.07897208498584578, 'weight_xgb_class_1': 0.7458938835984372, 'weight_xgb_class_2': 0.6869847486204438}. Best is trial 960 with value: 0.949822106074469.
[I 2026-07-05 15:31:58,156] Trial 996 finished with value: 0.9497719203813957 and parameters: {'weight_lgbm_class_0': 0.035772195655080066, 'weight_lgbm_class_1': 0.9291074349542969, 'weight_lgbm_class_2': 0.31507506863635837, 'weight_xgb_class_0': 0.0735791167346536, 'weight_xgb_class_1': 0.7824297660133077, 'weight_xgb_class_2': 0.6867586845287452}. Best is trial 960 with value: 0.949822106074469.
[I 2026-07-05 15:31:58,157] Trial 995 finished with value: 0.9497485233476267 and parameters: {'weight_lgbm_class_0': 0.03389466241175138, 'weight_lgbm_class_1': 0.933144555657072, 'weight_lgbm_class_2': 0.3073656884189933, 'weight_xgb_class_0': 0.07548858949572526, 'weight_xgb_class_1': 0.7815544490655231, 'weight_xgb_class_2': 0.6914315946035099}. Best is trial 960 with value: 0.949822106074469.

Best trial: 1003. Best value: 0.949823:  50%|█████████████████████████████████████████████████████████████████▏                                                                | 1003/2000 [00:27<00:31, 31.23it/s]

[I 2026-07-05 15:31:58,207] Trial 997 finished with value: 0.9497476685285032 and parameters: {'weight_lgbm_class_0': 0.03728419191397224, 'weight_lgbm_class_1': 0.9282595743211183, 'weight_lgbm_class_2': 0.3149830703315457, 'weight_xgb_class_0': 0.07704544330410762, 'weight_xgb_class_1': 0.7464383388615331, 'weight_xgb_class_2': 0.6867735553361398}. Best is trial 960 with value: 0.949822106074469.
[I 2026-07-05 15:31:58,287] Trial 998 finished with value: 0.9497392467776322 and parameters: {'weight_lgbm_class_0': 0.021598899792942453, 'weight_lgbm_class_1': 0.9312453823778665, 'weight_lgbm_class_2': 0.3193023885516951, 'weight_xgb_class_0': 0.07677990448314218, 'weight_xgb_class_1': 0.7424977064788494, 'weight_xgb_class_2': 0.7129291484867587}. Best is trial 960 with value: 0.949822106074469.
[I 2026-07-05 15:31:58,307] Trial 999 finished with value: 0.9497955225444742 and parameters: {'weight_lgbm_class_0': 0.02035736939757877, 'weight_lgbm_class_1': 0.9310390368224724, 'weight_lgbm_class_2': 0.3179364232960228, 'weight_xgb_class_0': 0.07858480438146097, 'weight_xgb_class_1': 0.6780527162344924, 'weight_xgb_class_2': 0.6842531779358852}. Best is trial 960 with value: 0.949822106074469.
[I 2026-07-05 15:31:58,347] Trial 1000 finished with value: 0.9497375660239037 and parameters: {'weight_lgbm_class_0': 0.03597540977323929, 'weight_lgbm_class_1': 0.9274730570415535, 'weight_lgbm_class_2': 0.3873927352682517, 'weight_xgb_class_0': 0.08149229901379403, 'weight_xgb_class_1': 0.7482749026210399, 'weight_xgb_class_2': 0.6985484479565124}. Best is trial 960 with value: 0.949822106074469.
[I 2026-07-05 15:31:58,364] Trial 1001 finished with value: 0.9496446209557078 and parameters: {'weight_lgbm_class_0': 0.01541545153477147, 'weight_lgbm_class_1': 0.9327298245478975, 'weight_lgbm_class_2': 0.30875148302179284, 'weight_xgb_class_0': 0.10236471584164836, 'weight_xgb_class_1': 0.549467203987071, 'weight_xgb_class_2': 0.6563357933495055}. Best is trial 960 with value: 0.949822106074469.
[I 2026-07-05 15:31:58,384] Trial 1003 finished with value: 0.9498228027521759 and parameters: {'weight_lgbm_class_0': 0.01819586606598044, 'weight_lgbm_class_1': 0.9296265173026895, 'weight_lgbm_class_2': 0.30892966670028366, 'weight_xgb_class_0': 0.07827393351585984, 'weight_xgb_class_1': 0.6808713117967573, 'weight_xgb_class_2': 0.6483313759192944}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:58,391] Trial 1002 finished with value: 0.9497684653841428 and parameters: {'weight_lgbm_class_0': 0.01927858710413612, 'weight_lgbm_class_1': 0.9386042957903099, 'weight_lgbm_class_2': 0.3124448114276662, 'weight_xgb_class_0': 0.08660690127796078, 'weight_xgb_class_1': 0.6834293920304628, 'weight_xgb_class_2': 0.6500917107894363}. Best is trial 1003 with value: 0.9498228027521759.

Best trial: 1003. Best value: 0.949823:  50%|█████████████████████████████████████████████████████████████████▌                                                                | 1009/2000 [00:27<00:30, 32.03it/s]

[I 2026-07-05 15:31:58,456] Trial 1005 finished with value: 0.9497413800178444 and parameters: {'weight_lgbm_class_0': 0.034361833933871856, 'weight_lgbm_class_1': 0.9343233147024428, 'weight_lgbm_class_2': 0.3007739676295667, 'weight_xgb_class_0': 0.07970567053411635, 'weight_xgb_class_1': 0.6662476670247606, 'weight_xgb_class_2': 0.6897077492186033}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:58,463] Trial 1004 finished with value: 0.9497218117248082 and parameters: {'weight_lgbm_class_0': 0.023616623692290603, 'weight_lgbm_class_1': 0.9362743644707001, 'weight_lgbm_class_2': 0.3036170152789557, 'weight_xgb_class_0': 0.09198076188953654, 'weight_xgb_class_1': 0.7204277347165914, 'weight_xgb_class_2': 0.6456724650179902}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:58,533] Trial 1006 finished with value: 0.9491016677036782 and parameters: {'weight_lgbm_class_0': 0.03578208922304235, 'weight_lgbm_class_1': 0.9315544681031528, 'weight_lgbm_class_2': 0.2959903310768337, 'weight_xgb_class_0': 0.10214452563268551, 'weight_xgb_class_1': 0.6712701638492417, 'weight_xgb_class_2': 0.6491916576715868}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:58,546] Trial 1007 finished with value: 0.9495873128296203 and parameters: {'weight_lgbm_class_0': 0.02154885218531033, 'weight_lgbm_class_1': 0.9328944681694927, 'weight_lgbm_class_2': 0.29207914410649227, 'weight_xgb_class_0': 0.09883932267467407, 'weight_xgb_class_1': 0.7254541314815597, 'weight_xgb_class_2': 0.6523028968366451}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:58,597] Trial 1008 finished with value: 0.9495472664029042 and parameters: {'weight_lgbm_class_0': 0.020962172402603264, 'weight_lgbm_class_1': 0.931317211764168, 'weight_lgbm_class_2': 0.2943348454605946, 'weight_xgb_class_0': 0.10098277084454428, 'weight_xgb_class_1': 0.6962803617814185, 'weight_xgb_class_2': 0.666093657213953}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:58,625] Trial 1009 finished with value: 0.9491272409511642 and parameters: {'weight_lgbm_class_0': 0.03687790346830397, 'weight_lgbm_class_1': 0.9293961715862552, 'weight_lgbm_class_2': 0.29639582955925575, 'weight_xgb_class_0': 0.10127612620990414, 'weight_xgb_class_1': 0.7009253156356119, 'weight_xgb_class_2': 0.6654755237587816}. Best is trial 1003 with value: 0.9498228027521759.

Best trial: 1003. Best value: 0.949823:  51%|██████████████████████████████████████████████████████████████████                                                                | 1017/2000 [00:27<00:30, 31.83it/s]

[I 2026-07-05 15:31:58,682] Trial 1010 finished with value: 0.9492609126164159 and parameters: {'weight_lgbm_class_0': 0.017185877899060953, 'weight_lgbm_class_1': 0.9298854039006461, 'weight_lgbm_class_2': 0.2925899685814716, 'weight_xgb_class_0': 0.10100068581808325, 'weight_xgb_class_1': 0.6743162596650168, 'weight_xgb_class_2': 0.5707451557180097}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:58,694] Trial 1011 finished with value: 0.9497145126642758 and parameters: {'weight_lgbm_class_0': 0.017801410273342533, 'weight_lgbm_class_1': 0.9326662354346927, 'weight_lgbm_class_2': 0.304973015390964, 'weight_xgb_class_0': 0.09731996174557789, 'weight_xgb_class_1': 0.6505408949257527, 'weight_xgb_class_2': 0.6468204171308827}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:58,721] Trial 1012 finished with value: 0.9493781501490819 and parameters: {'weight_lgbm_class_0': 0.01906860584079522, 'weight_lgbm_class_1': 0.9076370340175834, 'weight_lgbm_class_2': 0.28765563694236046, 'weight_xgb_class_0': 0.10556030143728684, 'weight_xgb_class_1': 0.7010763622957151, 'weight_xgb_class_2': 0.6593113456773603}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:58,740] Trial 1014 finished with value: 0.9495790969686609 and parameters: {'weight_lgbm_class_0': 0.01643821731488424, 'weight_lgbm_class_1': 0.960025924584137, 'weight_lgbm_class_2': 0.28760210393830665, 'weight_xgb_class_0': 0.10093483076962269, 'weight_xgb_class_1': 0.6014626972791988, 'weight_xgb_class_2': 0.6465047337141032}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:58,751] Trial 1013 finished with value: 0.9495563996400452 and parameters: {'weight_lgbm_class_0': 0.01682260679727513, 'weight_lgbm_class_1': 0.9317636108237672, 'weight_lgbm_class_2': 0.29320739858449435, 'weight_xgb_class_0': 0.10151695063117043, 'weight_xgb_class_1': 0.6514653976635661, 'weight_xgb_class_2': 0.6454755925209336}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:58,819] Trial 1015 finished with value: 0.949629671624964 and parameters: {'weight_lgbm_class_0': 0.016520655722473285, 'weight_lgbm_class_1': 0.959622358571841, 'weight_lgbm_class_2': 0.29278364468788465, 'weight_xgb_class_0': 0.1008284558155251, 'weight_xgb_class_1': 0.6517015680939385, 'weight_xgb_class_2': 0.6506035225334313}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:58,827] Trial 1017 finished with value: 0.9495346824835741 and parameters: {'weight_lgbm_class_0': 0.018102167152698863, 'weight_lgbm_class_1': 0.9642851001711956, 'weight_lgbm_class_2': 0.2967096058447578, 'weight_xgb_class_0': 0.10336781223915747, 'weight_xgb_class_1': 0.6726046140330898, 'weight_xgb_class_2': 0.6535997489829986}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:58,844] Trial 1016 finished with value: 0.9495902720662087 and parameters: {'weight_lgbm_class_0': 0.016325978882201622, 'weight_lgbm_class_1': 0.9034013194261308, 'weight_lgbm_class_2': 0.29416602537461584, 'weight_xgb_class_0': 0.1016724784336678, 'weight_xgb_class_1': 0.6664037804331828, 'weight_xgb_class_2': 0.6442029620891339}. Best is trial 1003 with value: 0.9498228027521759.

Best trial: 1003. Best value: 0.949823:  51%|██████████████████████████████████████████████████████████████████▍                                                               | 1022/2000 [00:27<00:30, 32.04it/s]

[I 2026-07-05 15:31:58,892] Trial 1018 finished with value: 0.949693686924118 and parameters: {'weight_lgbm_class_0': 0.01506589390629029, 'weight_lgbm_class_1': 0.9621419966405755, 'weight_lgbm_class_2': 0.29168701608309267, 'weight_xgb_class_0': 0.1020044452298659, 'weight_xgb_class_1': 0.6784508120509033, 'weight_xgb_class_2': 0.6750913872796203}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:58,915] Trial 1019 finished with value: 0.9497552056505626 and parameters: {'weight_lgbm_class_0': 0.0010533181231221003, 'weight_lgbm_class_1': 0.9056469138323683, 'weight_lgbm_class_2': 0.2890277741596205, 'weight_xgb_class_0': 0.1018825123778537, 'weight_xgb_class_1': 0.6937990741356337, 'weight_xgb_class_2': 0.5834950363872976}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:58,965] Trial 1020 finished with value: 0.9496734405297075 and parameters: {'weight_lgbm_class_0': 0.008502976023791244, 'weight_lgbm_class_1': 0.9645960920764184, 'weight_lgbm_class_2': 0.287950336288001, 'weight_xgb_class_0': 0.10548500940380412, 'weight_xgb_class_1': 0.661529406466925, 'weight_xgb_class_2': 0.7262830641266819}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:58,985] Trial 1021 finished with value: 0.9497254286312468 and parameters: {'weight_lgbm_class_0': 0.014283923111223652, 'weight_lgbm_class_1': 0.961805260207267, 'weight_lgbm_class_2': 0.29970101514289127, 'weight_xgb_class_0': 0.1033983385758534, 'weight_xgb_class_1': 0.6531409964688081, 'weight_xgb_class_2': 0.7275575563191629}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:59,042] Trial 1022 finished with value: 0.9495736219947105 and parameters: {'weight_lgbm_class_0': 0.006329468264971621, 'weight_lgbm_class_1': 0.960437112257791, 'weight_lgbm_class_2': 0.3116911915472942, 'weight_xgb_class_0': 0.10765176136421549, 'weight_xgb_class_1': 0.6451385635705478, 'weight_xgb_class_2': 0.5876616969889416}. Best is trial 1003 with value: 0.9498228027521759.

Best trial: 1003. Best value: 0.949823:  52%|███████████████████████████████████████████████████████████████████                                                               | 1031/2000 [00:27<00:30, 31.76it/s]

[I 2026-07-05 15:31:59,109] Trial 1025 finished with value: 0.9496509173928112 and parameters: {'weight_lgbm_class_0': 0.00029749194527432105, 'weight_lgbm_class_1': 0.3417855216746035, 'weight_lgbm_class_2': 0.31468354168569074, 'weight_xgb_class_0': 0.07796596658618977, 'weight_xgb_class_1': 0.6337330020575532, 'weight_xgb_class_2': 0.7316706952110533}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:59,113] Trial 1024 finished with value: 0.9495624597810489 and parameters: {'weight_lgbm_class_0': 0.004532384182558621, 'weight_lgbm_class_1': 0.9030704179226737, 'weight_lgbm_class_2': 0.3125674339932473, 'weight_xgb_class_0': 0.07210152837946399, 'weight_xgb_class_1': 0.7122562302216925, 'weight_xgb_class_2': 0.7321184387471971}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:59,117] Trial 1023 finished with value: 0.9490899752006614 and parameters: {'weight_lgbm_class_0': 0.03898942480111975, 'weight_lgbm_class_1': 0.9007482700305055, 'weight_lgbm_class_2': 0.31355861946907265, 'weight_xgb_class_0': 0.09035200434769101, 'weight_xgb_class_1': 0.6213795443121388, 'weight_xgb_class_2': 0.5807873776056619}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:59,151] Trial 1026 finished with value: 0.9497440916786335 and parameters: {'weight_lgbm_class_0': 0.04018059849219396, 'weight_lgbm_class_1': 0.9620005030362269, 'weight_lgbm_class_2': 0.3143342900063621, 'weight_xgb_class_0': 0.07465811949686556, 'weight_xgb_class_1': 0.6474767589644626, 'weight_xgb_class_2': 0.7264470918263817}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:59,186] Trial 1027 finished with value: 0.9495854722694484 and parameters: {'weight_lgbm_class_0': 0.00020831848913792014, 'weight_lgbm_class_1': 0.89616589064519, 'weight_lgbm_class_2': 0.31294154196917223, 'weight_xgb_class_0': 0.07635681849244515, 'weight_xgb_class_1': 0.697205927669228, 'weight_xgb_class_2': 0.7318397970970141}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:59,196] Trial 1028 finished with value: 0.9496485868846358 and parameters: {'weight_lgbm_class_0': 0.0014562856367153418, 'weight_lgbm_class_1': 0.8985373566359445, 'weight_lgbm_class_2': 0.3146178293612962, 'weight_xgb_class_0': 0.0759399566391939, 'weight_xgb_class_1': 0.6556864946240591, 'weight_xgb_class_2': 0.5786582204895099}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:59,254] Trial 1029 finished with value: 0.9495969335804911 and parameters: {'weight_lgbm_class_0': 0.0017416810564647028, 'weight_lgbm_class_1': 0.8953730479391807, 'weight_lgbm_class_2': 0.31375701805811285, 'weight_xgb_class_0': 0.07197274849956879, 'weight_xgb_class_1': 0.6984776461873093, 'weight_xgb_class_2': 0.5880019357773699}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:59,266] Trial 1030 finished with value: 0.9496823557541184 and parameters: {'weight_lgbm_class_0': 0.04058188792259867, 'weight_lgbm_class_1': 0.8988099251411142, 'weight_lgbm_class_2': 0.3194871406286557, 'weight_xgb_class_0': 0.07513610767692042, 'weight_xgb_class_1': 0.622615760936248, 'weight_xgb_class_2': 0.7238409923995172}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:59,280] Trial 1031 finished with value: 0.9494180012619027 and parameters: {'weight_lgbm_class_0': 0.0011222083679941694, 'weight_lgbm_class_1': 0.8961498925548848, 'weight_lgbm_class_2': 0.3134506318535027, 'weight_xgb_class_0': 0.06942641296830782, 'weight_xgb_class_1': 0.6528744698312092, 'weight_xgb_class_2': 0.720527097059118}. Best is trial 1003 with value: 0.9498228027521759.

Best trial: 1003. Best value: 0.949823:  52%|███████████████████████████████████████████████████████████████████▌                                                              | 1039/2000 [00:28<00:29, 32.35it/s]

[I 2026-07-05 15:31:59,375] Trial 1032 finished with value: 0.9496571391341447 and parameters: {'weight_lgbm_class_0': 0.000283365479954778, 'weight_lgbm_class_1': 0.3362115777570994, 'weight_lgbm_class_2': 0.32571105249863364, 'weight_xgb_class_0': 0.07663573525903045, 'weight_xgb_class_1': 0.7352744627612539, 'weight_xgb_class_2': 0.7116911487429801}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:59,375] Trial 1033 finished with value: 0.9131833419180909 and parameters: {'weight_lgbm_class_0': 0.04408418929760855, 'weight_lgbm_class_1': 0.903278654598899, 'weight_lgbm_class_2': 0.32003626290975423, 'weight_xgb_class_0': 0.676692037059105, 'weight_xgb_class_1': 0.7080507269177058, 'weight_xgb_class_2': 0.7132159474131178}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:59,390] Trial 1034 finished with value: 0.949068430642764 and parameters: {'weight_lgbm_class_0': 0.041663867208080706, 'weight_lgbm_class_1': 0.06465098575371492, 'weight_lgbm_class_2': 0.3261262550889503, 'weight_xgb_class_0': 0.07443129867526903, 'weight_xgb_class_1': 0.7065796613095517, 'weight_xgb_class_2': 0.6766020910099866}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:59,457] Trial 1035 finished with value: 0.9495152255370892 and parameters: {'weight_lgbm_class_0': 0.04685421128711717, 'weight_lgbm_class_1': 0.8905078400815869, 'weight_lgbm_class_2': 0.32037857756151267, 'weight_xgb_class_0': 0.08245806259852632, 'weight_xgb_class_1': 0.6901006677083852, 'weight_xgb_class_2': 0.7072965438754129}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:59,493] Trial 1036 finished with value: 0.9288968026618636 and parameters: {'weight_lgbm_class_0': 0.3746713540791428, 'weight_lgbm_class_1': 0.8926306957578957, 'weight_lgbm_class_2': 0.32607819822922196, 'weight_xgb_class_0': 0.07319882180133988, 'weight_xgb_class_1': 0.6862269144417219, 'weight_xgb_class_2': 0.5420055628847439}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:59,514] Trial 1037 finished with value: 0.9497291598832237 and parameters: {'weight_lgbm_class_0': 0.04373318165736945, 'weight_lgbm_class_1': 0.8930354169539935, 'weight_lgbm_class_2': 0.33164846991660046, 'weight_xgb_class_0': 0.07480543111546437, 'weight_xgb_class_1': 0.693973353887194, 'weight_xgb_class_2': 0.6782396712208173}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:59,533] Trial 1038 finished with value: 0.9496829288186334 and parameters: {'weight_lgbm_class_0': 0.043341322999128434, 'weight_lgbm_class_1': 0.8934696876798084, 'weight_lgbm_class_2': 0.3227624859906501, 'weight_xgb_class_0': 0.07253743719534822, 'weight_xgb_class_1': 0.6228606216231005, 'weight_xgb_class_2': 0.704469806882725}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:59,568] Trial 1039 finished with value: 0.9497719346219183 and parameters: {'weight_lgbm_class_0': 0.044706424368797335, 'weight_lgbm_class_1': 0.9137182131024819, 'weight_lgbm_class_2': 0.3307937469672473, 'weight_xgb_class_0': 0.07282040410042849, 'weight_xgb_class_1': 0.6949659494542026, 'weight_xgb_class_2': 0.682867864190143}. Best is trial 1003 with value: 0.9498228027521759.

[I 2026-07-05 15:31:59,584] Trial 1040 finished with value: 0.94974133468773 and parameters: {'weight_lgbm_class_0': 0.041720184441221914, 'weight_lgbm_class_1': 0.9168208433437578, 'weight_lgbm_class_2': 0.32945200730269586, 'weight_xgb_class_0': 0.07067288656071144, 'weight_xgb_class_1': 0.6905812852540182, 'weight_xgb_class_2': 0.6772057548062403}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:59,639] Trial 1042 finished with value: 0.9497388026075687 and parameters: {'weight_lgbm_class_0': 0.04357188984340926, 'weight_lgbm_class_1': 0.9179558192409423, 'weight_lgbm_class_2': 0.3333486608274257, 'weight_xgb_class_0': 0.07246943451563284, 'weight_xgb_class_1': 0.7143310847954176, 'weight_xgb_class_2': 0.6780826396341953}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:59,661] Trial 1043 finished with value: 0.9497618734330455 and parameters: {'weight_lgbm_class_0': 0.04029411934968148, 'weight_lgbm_class_1': 0.9209827546045609, 'weight_lgbm_class_2': 0.3294799741891347, 'weight_xgb_class_0': 0.06329617055248458, 'weight_xgb_class_1': 0.7211111800440122, 'weight_xgb_class_2': 0.6799109937285335}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:59,661] Trial 1041 finished with value: 0.9497485314714851 and parameters: {'weight_lgbm_class_0': 0.04601318298096488, 'weight_lgbm_class_1': 0.9440282920051475, 'weight_lgbm_class_2': 0.3354639564693215, 'weight_xgb_class_0': 0.0716222708414078, 'weight_xgb_class_1': 0.7208321987436024, 'weight_xgb_class_2': 0.6808384057804648}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:59,736] Trial 1044 finished with value: 0.9497647685783397 and parameters: {'weight_lgbm_class_0': 0.04765767143407002, 'weight_lgbm_class_1': 0.9431795389181353, 'weight_lgbm_class_2': 0.33104037374576467, 'weight_xgb_class_0': 0.04371712298327561, 'weight_xgb_class_1': 0.7206984909157829, 'weight_xgb_class_2': 0.681133306357497}. Best is trial 1003 with value: 0.9498228027521759.

Best trial: 1003. Best value: 0.949823:  53%|████████████████████████████████████████████████████████████████████▍                                                             | 1052/2000 [00:28<00:29, 32.14it/s]

[I 2026-07-05 15:31:59,796] Trial 1045 finished with value: 0.9497262777371785 and parameters: {'weight_lgbm_class_0': 0.043462350146810866, 'weight_lgbm_class_1': 0.9184665814523049, 'weight_lgbm_class_2': 0.3272255126811165, 'weight_xgb_class_0': 0.043620471852180265, 'weight_xgb_class_1': 0.7176237486826639, 'weight_xgb_class_2': 0.5419343301198236}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:59,835] Trial 1046 finished with value: 0.9497388779042252 and parameters: {'weight_lgbm_class_0': 0.0432077746684118, 'weight_lgbm_class_1': 0.9134589701694288, 'weight_lgbm_class_2': 0.33311244056284073, 'weight_xgb_class_0': 0.06969211718607803, 'weight_xgb_class_1': 0.7224880184874085, 'weight_xgb_class_2': 0.6857959862421471}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:59,839] Trial 1047 finished with value: 0.9497696821453495 and parameters: {'weight_lgbm_class_0': 0.04711574820691082, 'weight_lgbm_class_1': 0.9188938611089987, 'weight_lgbm_class_2': 0.3340544632336628, 'weight_xgb_class_0': 0.045768090354270916, 'weight_xgb_class_1': 0.7218784755682662, 'weight_xgb_class_2': 0.6774734698194331}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:59,880] Trial 1050 finished with value: 0.9495725068321957 and parameters: {'weight_lgbm_class_0': 0.03527634375829556, 'weight_lgbm_class_1': 0.9181582618105466, 'weight_lgbm_class_2': 0.33304153059601715, 'weight_xgb_class_0': 0.045671169815726206, 'weight_xgb_class_1': 0.7204722394774461, 'weight_xgb_class_2': 0.685103990233618}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:59,881] Trial 1048 finished with value: 0.9496851382859898 and parameters: {'weight_lgbm_class_0': 0.04083228026306992, 'weight_lgbm_class_1': 0.919537493020372, 'weight_lgbm_class_2': 0.33482318526923543, 'weight_xgb_class_0': 0.04304795143550369, 'weight_xgb_class_1': 0.6109880315537946, 'weight_xgb_class_2': 0.6318536569902536}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:59,886] Trial 1049 finished with value: 0.9497058538311051 and parameters: {'weight_lgbm_class_0': 0.04299333734921629, 'weight_lgbm_class_1': 0.9197518629945742, 'weight_lgbm_class_2': 0.3455994493983876, 'weight_xgb_class_0': 0.046704073136558485, 'weight_xgb_class_1': 0.7269736374891019, 'weight_xgb_class_2': 0.6780722272015874}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:59,914] Trial 1051 finished with value: 0.9496008834209523 and parameters: {'weight_lgbm_class_0': 0.036524710943526884, 'weight_lgbm_class_1': 0.9443159505935553, 'weight_lgbm_class_2': 0.3477730746836532, 'weight_xgb_class_0': 0.04318976122252373, 'weight_xgb_class_1': 0.7465138402554619, 'weight_xgb_class_2': 0.6368115783764052}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:31:59,958] Trial 1052 finished with value: 0.9498092870800332 and parameters: {'weight_lgbm_class_0': 0.05433686504661954, 'weight_lgbm_class_1': 0.9471347129344502, 'weight_lgbm_class_2': 0.34841217898317006, 'weight_xgb_class_0': 0.04673857083069946, 'weight_xgb_class_1': 0.7235301193328743, 'weight_xgb_class_2': 0.6910610744315102}. Best is trial 1003 with value: 0.9498228027521759.

[I 2026-07-05 15:32:00,011] Trial 1054 finished with value: 0.9494522970767244 and parameters: {'weight_lgbm_class_0': 0.030411162638250513, 'weight_lgbm_class_1': 0.9473258936426185, 'weight_lgbm_class_2': 0.3528524036490622, 'weight_xgb_class_0': 0.04429784118501846, 'weight_xgb_class_1': 0.7459757228684503, 'weight_xgb_class_2': 0.6308740127903746}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:32:00,049] Trial 1053 finished with value: 0.9489810068057936 and parameters: {'weight_lgbm_class_0': 0.05959745896742536, 'weight_lgbm_class_1': 0.25736662312585706, 'weight_lgbm_class_2': 0.03948308319678917, 'weight_xgb_class_0': 0.04015986050107716, 'weight_xgb_class_1': 0.7472196703658132, 'weight_xgb_class_2': 0.6313696553500155}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:32:00,052] Trial 1055 finished with value: 0.9497926597763889 and parameters: {'weight_lgbm_class_0': 0.056628587032031254, 'weight_lgbm_class_1': 0.9423752192896798, 'weight_lgbm_class_2': 0.3516880300374014, 'weight_xgb_class_0': 0.043266683235629724, 'weight_xgb_class_1': 0.7443149181115543, 'weight_xgb_class_2': 0.6303536126833976}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:32:00,084] Trial 1056 finished with value: 0.9495065683950087 and parameters: {'weight_lgbm_class_0': 0.03357457715008883, 'weight_lgbm_class_1': 0.9429002286117029, 'weight_lgbm_class_2': 0.356284558501926, 'weight_xgb_class_0': 0.04363720972907281, 'weight_xgb_class_1': 0.7392357297371911, 'weight_xgb_class_2': 0.6270044269226337}. Best is trial 1003 with value: 0.9498228027521759.
[I 2026-07-05 15:32:00,167] Trial 1057 finished with value: 0.9498290916740215 and parameters: {'weight_lgbm_class_0': 0.06095191641679855, 'weight_lgbm_class_1': 0.9392970848167118, 'weight_lgbm_class_2': 0.3534292701855225, 'weight_xgb_class_0': 0.044633520299641904, 'weight_xgb_class_1': 0.7500360333068712, 'weight_xgb_class_2': 0.6341778037472675}. Best is trial 1057 with value: 0.9498290916740215.

Best trial: 1057. Best value: 0.949829:  53%|█████████████████████████████████████████████████████████████████████▎                                                            | 1066/2000 [00:29<00:28, 32.54it/s]

[I 2026-07-05 15:32:00,215] Trial 1059 finished with value: 0.9481956120048723 and parameters: {'weight_lgbm_class_0': 0.06017403158496554, 'weight_lgbm_class_1': 0.9455943703772224, 'weight_lgbm_class_2': 0.27847687467120386, 'weight_xgb_class_0': 0.117398985878755, 'weight_xgb_class_1': 0.7518818573908465, 'weight_xgb_class_2': 0.6281186708727147}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:00,226] Trial 1058 finished with value: 0.949781430554031 and parameters: {'weight_lgbm_class_0': 0.06551755281879945, 'weight_lgbm_class_1': 0.9478287548519817, 'weight_lgbm_class_2': 0.35023876730626996, 'weight_xgb_class_0': 0.042854936390912785, 'weight_xgb_class_1': 0.7503271186719399, 'weight_xgb_class_2': 0.6319105942881663}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:00,260] Trial 1060 finished with value: 0.9481483942813118 and parameters: {'weight_lgbm_class_0': 0.06234862253293519, 'weight_lgbm_class_1': 0.9463734214546202, 'weight_lgbm_class_2': 0.2772180204790551, 'weight_xgb_class_0': 0.11708079916779801, 'weight_xgb_class_1': 0.7461359241922225, 'weight_xgb_class_2': 0.6344368760487892}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:00,300] Trial 1061 finished with value: 0.9483506414264343 and parameters: {'weight_lgbm_class_0': 0.06464017018972962, 'weight_lgbm_class_1': 0.9450262309029512, 'weight_lgbm_class_2': 0.2790372324199129, 'weight_xgb_class_0': 0.11847942899847706, 'weight_xgb_class_1': 0.7473088456552702, 'weight_xgb_class_2': 0.6994142750083071}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:00,314] Trial 1062 finished with value: 0.9489337801152559 and parameters: {'weight_lgbm_class_0': 0.06102726016187621, 'weight_lgbm_class_1': 0.9394404519704177, 'weight_lgbm_class_2': 0.27355905116753265, 'weight_xgb_class_0': 0.08239129078852221, 'weight_xgb_class_1': 0.755412333832065, 'weight_xgb_class_2': 0.6394360570978533}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:00,314] Trial 1063 finished with value: 0.8999640858876311 and parameters: {'weight_lgbm_class_0': 0.06729356981070408, 'weight_lgbm_class_1': 0.9562951736257215, 'weight_lgbm_class_2': 0.3581160064884503, 'weight_xgb_class_0': 0.8388122550175459, 'weight_xgb_class_1': 0.7493997965588622, 'weight_xgb_class_2': 0.6262857132481214}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:00,354] Trial 1064 finished with value: 0.9497864586311474 and parameters: {'weight_lgbm_class_0': 0.06543640186008146, 'weight_lgbm_class_1': 0.9566127078555524, 'weight_lgbm_class_2': 0.36069479856024417, 'weight_xgb_class_0': 0.04427955569736862, 'weight_xgb_class_1': 0.7555348076872771, 'weight_xgb_class_2': 0.6295709275174227}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:00,369] Trial 1065 finished with value: 0.9484816081233157 and parameters: {'weight_lgbm_class_0': 0.06321768183356236, 'weight_lgbm_class_1': 0.9593138988495845, 'weight_lgbm_class_2': 0.3588243303902712, 'weight_xgb_class_0': 0.11526833496142629, 'weight_xgb_class_1': 0.7560542926812073, 'weight_xgb_class_2': 0.6307148155326965}. Best is trial 1057 with value: 0.9498290916740215.

[I 2026-07-05 15:32:00,440] Trial 1066 finished with value: 0.9497581923402297 and parameters: {'weight_lgbm_class_0': 0.07524133718112261, 'weight_lgbm_class_1': 0.9667048245062401, 'weight_lgbm_class_2': 0.3562834600004804, 'weight_xgb_class_0': 0.04278774331344491, 'weight_xgb_class_1': 0.7530002885558502, 'weight_xgb_class_2': 0.7072467848839926}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:00,461] Trial 1067 finished with value: 0.9497830868488158 and parameters: {'weight_lgbm_class_0': 0.07735726731845266, 'weight_lgbm_class_1': 0.9665459794563849, 'weight_lgbm_class_2': 0.35626408311742286, 'weight_xgb_class_0': 0.0394026571179404, 'weight_xgb_class_1': 0.7549313943899205, 'weight_xgb_class_2': 0.7012462188619057}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:00,481] Trial 1068 finished with value: 0.949807857497591 and parameters: {'weight_lgbm_class_0': 0.06682959119122982, 'weight_lgbm_class_1': 0.9620600194067652, 'weight_lgbm_class_2': 0.3544919467299743, 'weight_xgb_class_0': 0.038955217905953146, 'weight_xgb_class_1': 0.7474201663710269, 'weight_xgb_class_2': 0.7023733765184365}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:00,527] Trial 1069 finished with value: 0.949581756915307 and parameters: {'weight_lgbm_class_0': 0.06685118773995044, 'weight_lgbm_class_1': 0.9601867395464915, 'weight_lgbm_class_2': 0.35435003299560514, 'weight_xgb_class_0': 0.05689694904079974, 'weight_xgb_class_1': 0.7530464381571826, 'weight_xgb_class_2': 0.6317581932083561}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:00,600] Trial 1071 finished with value: 0.9000018026111268 and parameters: {'weight_lgbm_class_0': 0.07561582260790314, 'weight_lgbm_class_1': 0.9617805920625078, 'weight_lgbm_class_2': 0.35848840652671016, 'weight_xgb_class_0': 0.850608616175377, 'weight_xgb_class_1': 0.7508601919434623, 'weight_xgb_class_2': 0.6595975106623976}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:00,601] Trial 1070 finished with value: 0.8970334294740758 and parameters: {'weight_lgbm_class_0': 0.07895801109695065, 'weight_lgbm_class_1': 0.9598887591577914, 'weight_lgbm_class_2': 0.3640040640617037, 'weight_xgb_class_0': 0.8658373556575287, 'weight_xgb_class_1': 0.7544426183527383, 'weight_xgb_class_2': 0.600908913024959}. Best is trial 1057 with value: 0.9498290916740215.

Best trial: 1057. Best value: 0.949829:  54%|██████████████████████████████████████████████████████████████████████                                                            | 1078/2000 [00:29<00:29, 31.76it/s]

[I 2026-07-05 15:32:00,622] Trial 1072 finished with value: 0.9495846598142982 and parameters: {'weight_lgbm_class_0': 0.08193189271191331, 'weight_lgbm_class_1': 0.9655413168157863, 'weight_lgbm_class_2': 0.3541205479468299, 'weight_xgb_class_0': 0.037270958829015655, 'weight_xgb_class_1': 0.7568588396278965, 'weight_xgb_class_2': 0.6048027745048284}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:00,696] Trial 1073 finished with value: 0.9496629544382201 and parameters: {'weight_lgbm_class_0': 0.08392078608701033, 'weight_lgbm_class_1': 0.9563737477507317, 'weight_lgbm_class_2': 0.3596004979443717, 'weight_xgb_class_0': 0.0389415165953735, 'weight_xgb_class_1': 0.7606322945282142, 'weight_xgb_class_2': 0.6566252569364822}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:00,702] Trial 1074 finished with value: 0.9136894233987336 and parameters: {'weight_lgbm_class_0': 0.6470518336975363, 'weight_lgbm_class_1': 0.9683136842774586, 'weight_lgbm_class_2': 0.35552136918993327, 'weight_xgb_class_0': 0.04576734090926789, 'weight_xgb_class_1': 0.7660789496285356, 'weight_xgb_class_2': 0.5998813967424452}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:00,724] Trial 1075 finished with value: 0.9497916032255639 and parameters: {'weight_lgbm_class_0': 0.07959610319243612, 'weight_lgbm_class_1': 0.9666222812502625, 'weight_lgbm_class_2': 0.3547613510946339, 'weight_xgb_class_0': 0.03752874247760355, 'weight_xgb_class_1': 0.7325353555153604, 'weight_xgb_class_2': 0.6575844844906259}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:00,748] Trial 1076 finished with value: 0.9497145890839818 and parameters: {'weight_lgbm_class_0': 0.0762878398439687, 'weight_lgbm_class_1': 0.9664803612386692, 'weight_lgbm_class_2': 0.35566034143655995, 'weight_xgb_class_0': 0.0376269017125635, 'weight_xgb_class_1': 0.7354454778927673, 'weight_xgb_class_2': 0.5950221371278965}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:00,780] Trial 1077 finished with value: 0.9495489505952661 and parameters: {'weight_lgbm_class_0': 0.07955813645037266, 'weight_lgbm_class_1': 0.9624133042785193, 'weight_lgbm_class_2': 0.3497767295522891, 'weight_xgb_class_0': 0.04043849466614385, 'weight_xgb_class_1': 0.733149747279901, 'weight_xgb_class_2': 0.5966923531162639}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:00,832] Trial 1079 finished with value: 0.9497714850060276 and parameters: {'weight_lgbm_class_0': 0.08129583350801466, 'weight_lgbm_class_1': 0.9658792786013944, 'weight_lgbm_class_2': 0.35608031886673847, 'weight_xgb_class_0': 0.037375518292410544, 'weight_xgb_class_1': 0.7318681470222447, 'weight_xgb_class_2': 0.6641907952674162}. Best is trial 1057 with value: 0.9498290916740215.

[I 2026-07-05 15:32:00,835] Trial 1078 finished with value: 0.9495787133407476 and parameters: {'weight_lgbm_class_0': 0.07742960997927364, 'weight_lgbm_class_1': 0.9671126187242455, 'weight_lgbm_class_2': 0.355051248134386, 'weight_xgb_class_0': 0.04077299102492443, 'weight_xgb_class_1': 0.7278033619993188, 'weight_xgb_class_2': 0.5923449200977231}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:00,863] Trial 1080 finished with value: 0.9498097292298712 and parameters: {'weight_lgbm_class_0': 0.08012339155217008, 'weight_lgbm_class_1': 0.9700240528745844, 'weight_lgbm_class_2': 0.356833924129462, 'weight_xgb_class_0': 0.03811496260844388, 'weight_xgb_class_1': 0.7642163877650683, 'weight_xgb_class_2': 0.6595509134076546}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:00,887] Trial 1081 finished with value: 0.9495971952114995 and parameters: {'weight_lgbm_class_0': 0.08284668850548958, 'weight_lgbm_class_1': 0.9593095914058815, 'weight_lgbm_class_2': 0.35848473383169416, 'weight_xgb_class_0': 0.03551602309931054, 'weight_xgb_class_1': 0.7693674010447094, 'weight_xgb_class_2': 0.5940163538723413}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:00,979] Trial 1082 finished with value: 0.9498018327409631 and parameters: {'weight_lgbm_class_0': 0.07843110389799805, 'weight_lgbm_class_1': 0.9735079764193054, 'weight_lgbm_class_2': 0.3518325853194633, 'weight_xgb_class_0': 0.035456047111033215, 'weight_xgb_class_1': 0.7263663063280805, 'weight_xgb_class_2': 0.6594714641002137}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:00,991] Trial 1083 finished with value: 0.9496820874919966 and parameters: {'weight_lgbm_class_0': 0.07938796756857909, 'weight_lgbm_class_1': 0.9664326548433138, 'weight_lgbm_class_2': 0.3483833922475314, 'weight_xgb_class_0': 0.034904980365592045, 'weight_xgb_class_1': 0.7253717329763893, 'weight_xgb_class_2': 0.5927613420932861}. Best is trial 1057 with value: 0.9498290916740215.

Best trial: 1057. Best value: 0.949829:  55%|██████████████████████████████████████████████████████████████████████▊                                                           | 1090/2000 [00:29<00:31, 29.25it/s]

[I 2026-07-05 15:32:01,048] Trial 1084 finished with value: 0.9497563297930863 and parameters: {'weight_lgbm_class_0': 0.08080662908437049, 'weight_lgbm_class_1': 0.9802630584332505, 'weight_lgbm_class_2': 0.3499534396472446, 'weight_xgb_class_0': 0.03825273041716634, 'weight_xgb_class_1': 0.7306210214098088, 'weight_xgb_class_2': 0.6596680340429999}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:01,083] Trial 1086 finished with value: 0.949515472228744 and parameters: {'weight_lgbm_class_0': 0.08193242642264949, 'weight_lgbm_class_1': 0.9755021824546369, 'weight_lgbm_class_2': 0.3453263502128786, 'weight_xgb_class_0': 0.04579816538756128, 'weight_xgb_class_1': 0.7188307846198727, 'weight_xgb_class_2': 0.6598473844164932}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:01,085] Trial 1085 finished with value: 0.9498084514255626 and parameters: {'weight_lgbm_class_0': 0.06815629003999113, 'weight_lgbm_class_1': 0.9740284889073145, 'weight_lgbm_class_2': 0.34346589643868364, 'weight_xgb_class_0': 0.03418305426143285, 'weight_xgb_class_1': 0.7255293640975995, 'weight_xgb_class_2': 0.6596596787083656}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:01,138] Trial 1087 finished with value: 0.9496770523807597 and parameters: {'weight_lgbm_class_0': 0.08321090777630442, 'weight_lgbm_class_1': 0.9758649096082922, 'weight_lgbm_class_2': 0.3451168197456738, 'weight_xgb_class_0': 0.038226218747713175, 'weight_xgb_class_1': 0.7305335013635892, 'weight_xgb_class_2': 0.6602626251554519}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:01,168] Trial 1088 finished with value: 0.9008686054198671 and parameters: {'weight_lgbm_class_0': 0.0826578972777804, 'weight_lgbm_class_1': 0.9433590909729638, 'weight_lgbm_class_2': 0.3417978435835397, 'weight_xgb_class_0': 0.8095955171453669, 'weight_xgb_class_1': 0.7150174654575895, 'weight_xgb_class_2': 0.6616048424168167}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:01,186] Trial 1089 finished with value: 0.949621808335638 and parameters: {'weight_lgbm_class_0': 0.07999891053106059, 'weight_lgbm_class_1': 0.9710333675028677, 'weight_lgbm_class_2': 0.3430757734566428, 'weight_xgb_class_0': 0.04352564937158074, 'weight_xgb_class_1': 0.7211553030850332, 'weight_xgb_class_2': 0.6580670719653676}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:01,213] Trial 1090 finished with value: 0.9004725400617627 and parameters: {'weight_lgbm_class_0': 0.8885123287904618, 'weight_lgbm_class_1': 0.9764270301767066, 'weight_lgbm_class_2': 0.3712586595775921, 'weight_xgb_class_0': 0.031894455937482684, 'weight_xgb_class_1': 0.7110802066621733, 'weight_xgb_class_2': 0.6661603747790995}. Best is trial 1057 with value: 0.9498290916740215.

[I 2026-07-05 15:32:01,277] Trial 1092 finished with value: 0.9497983940865096 and parameters: {'weight_lgbm_class_0': 0.08093576298263501, 'weight_lgbm_class_1': 0.9787742482020204, 'weight_lgbm_class_2': 0.37685619290728894, 'weight_xgb_class_0': 0.03340825864060622, 'weight_xgb_class_1': 0.7763491440546082, 'weight_xgb_class_2': 0.6610452901318287}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:01,281] Trial 1091 finished with value: 0.903793729033517 and parameters: {'weight_lgbm_class_0': 0.08437687126252724, 'weight_lgbm_class_1': 0.9809488054363977, 'weight_lgbm_class_2': 0.37165998733830796, 'weight_xgb_class_0': 0.7986451106517559, 'weight_xgb_class_1': 0.774913131933374, 'weight_xgb_class_2': 0.6590128969668889}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:01,318] Trial 1093 finished with value: 0.949677480454643 and parameters: {'weight_lgbm_class_0': 0.08610913025075692, 'weight_lgbm_class_1': 0.9705337059707508, 'weight_lgbm_class_2': 0.34309973245659475, 'weight_xgb_class_0': 0.03598911890126062, 'weight_xgb_class_1': 0.771398264952132, 'weight_xgb_class_2': 0.6593785746602903}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:01,377] Trial 1094 finished with value: 0.9498036304231783 and parameters: {'weight_lgbm_class_0': 0.07806258039392353, 'weight_lgbm_class_1': 0.9799488349155758, 'weight_lgbm_class_2': 0.3716925248975724, 'weight_xgb_class_0': 0.035042753634596024, 'weight_xgb_class_1': 0.7215702908806263, 'weight_xgb_class_2': 0.6590103018265543}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:01,402] Trial 1095 finished with value: 0.9398211618229707 and parameters: {'weight_lgbm_class_0': 0.08616688294016614, 'weight_lgbm_class_1': 0.9856834204208473, 'weight_lgbm_class_2': 0.37415718762130773, 'weight_xgb_class_0': 0.2882288646481196, 'weight_xgb_class_1': 0.7100165742914613, 'weight_xgb_class_2': 0.6571949502410244}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:01,467] Trial 1096 finished with value: 0.9497742012902707 and parameters: {'weight_lgbm_class_0': 0.08829207233854526, 'weight_lgbm_class_1': 0.9777944023853006, 'weight_lgbm_class_2': 0.3766963003443286, 'weight_xgb_class_0': 0.03233127386847949, 'weight_xgb_class_1': 0.7105217722080909, 'weight_xgb_class_2': 0.6605088614545543}. Best is trial 1057 with value: 0.9498290916740215.

Best trial: 1057. Best value: 0.949829:  55%|███████████████████████████████████████████████████████████████████████▋                                                          | 1102/2000 [00:30<00:33, 26.49it/s]

[I 2026-07-05 15:32:01,484] Trial 1098 finished with value: 0.9497018703668432 and parameters: {'weight_lgbm_class_0': 0.08688052251176419, 'weight_lgbm_class_1': 0.9665964209130373, 'weight_lgbm_class_2': 0.3744154765060498, 'weight_xgb_class_0': 0.036781732301571904, 'weight_xgb_class_1': 0.7068497089321116, 'weight_xgb_class_2': 0.6669116665002645}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:01,548] Trial 1099 finished with value: 0.9497418521959956 and parameters: {'weight_lgbm_class_0': 0.06346437901663458, 'weight_lgbm_class_1': 0.9802128352128046, 'weight_lgbm_class_2': 0.37603222007562437, 'weight_xgb_class_0': 0.0591879944457883, 'weight_xgb_class_1': 0.697940738304044, 'weight_xgb_class_2': 0.7015964981558124}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:01,561] Trial 1097 finished with value: 0.9497200068028789 and parameters: {'weight_lgbm_class_0': 0.0862088158785389, 'weight_lgbm_class_1': 0.98153632370826, 'weight_lgbm_class_2': 0.374001363863253, 'weight_xgb_class_0': 0.03548605214946342, 'weight_xgb_class_1': 0.7069484831786501, 'weight_xgb_class_2': 0.6469332845128203}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:01,600] Trial 1100 finished with value: 0.9497475467786831 and parameters: {'weight_lgbm_class_0': 0.05955753267886933, 'weight_lgbm_class_1': 0.9728090510105132, 'weight_lgbm_class_2': 0.3738370274993884, 'weight_xgb_class_0': 0.05925052051722956, 'weight_xgb_class_1': 0.7007047423762972, 'weight_xgb_class_2': 0.6980157045941245}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:01,661] Trial 1101 finished with value: 0.9497626564969425 and parameters: {'weight_lgbm_class_0': 0.05950693837412987, 'weight_lgbm_class_1': 0.9867106840447111, 'weight_lgbm_class_2': 0.3746643181983936, 'weight_xgb_class_0': 0.06071044330120626, 'weight_xgb_class_1': 0.7032344875470281, 'weight_xgb_class_2': 0.6468585731069951}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:01,680] Trial 1102 finished with value: 0.9497413409071912 and parameters: {'weight_lgbm_class_0': 0.05993451262121832, 'weight_lgbm_class_1': 0.9813039952557607, 'weight_lgbm_class_2': 0.3726831255194602, 'weight_xgb_class_0': 0.06283456731651484, 'weight_xgb_class_1': 0.7051711905141012, 'weight_xgb_class_2': 0.7026512256608125}. Best is trial 1057 with value: 0.9498290916740215.

Best trial: 1057. Best value: 0.949829:  56%|████████████████████████████████████████████████████████████████████████▏                                                         | 1110/2000 [00:30<00:29, 29.69it/s]

[I 2026-07-05 15:32:01,712] Trial 1103 finished with value: 0.9497588778666316 and parameters: {'weight_lgbm_class_0': 0.06392709562250581, 'weight_lgbm_class_1': 0.9867134006022279, 'weight_lgbm_class_2': 0.3757543909466691, 'weight_xgb_class_0': 0.03139106647431475, 'weight_xgb_class_1': 0.699510258804393, 'weight_xgb_class_2': 0.6510573150866982}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:01,751] Trial 1104 finished with value: 0.9497592045889073 and parameters: {'weight_lgbm_class_0': 0.06212260516591498, 'weight_lgbm_class_1': 0.9766675001394585, 'weight_lgbm_class_2': 0.3743307879633211, 'weight_xgb_class_0': 0.05855190260930537, 'weight_xgb_class_1': 0.7005981471442796, 'weight_xgb_class_2': 0.6993041546765095}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:01,763] Trial 1105 finished with value: 0.9497359642033443 and parameters: {'weight_lgbm_class_0': 0.05785224852505794, 'weight_lgbm_class_1': 0.9863447792841631, 'weight_lgbm_class_2': 0.3720295399905248, 'weight_xgb_class_0': 0.06270918507665756, 'weight_xgb_class_1': 0.7046542430045264, 'weight_xgb_class_2': 0.6417704778434172}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:01,789] Trial 1106 finished with value: 0.9497701699336919 and parameters: {'weight_lgbm_class_0': 0.08953163631892247, 'weight_lgbm_class_1': 0.9845261351764357, 'weight_lgbm_class_2': 0.3720796167961488, 'weight_xgb_class_0': 0.029748986361969064, 'weight_xgb_class_1': 0.7038078772146603, 'weight_xgb_class_2': 0.6399884796278238}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:01,818] Trial 1107 finished with value: 0.9498024416420656 and parameters: {'weight_lgbm_class_0': 0.06220546639384411, 'weight_lgbm_class_1': 0.9792896386304644, 'weight_lgbm_class_2': 0.3739474040450912, 'weight_xgb_class_0': 0.034830894174354275, 'weight_xgb_class_1': 0.6987427211445146, 'weight_xgb_class_2': 0.6961190152056749}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:01,846] Trial 1108 finished with value: 0.949785205087903 and parameters: {'weight_lgbm_class_0': 0.06266103664746855, 'weight_lgbm_class_1': 0.984684082889033, 'weight_lgbm_class_2': 0.33599124112933837, 'weight_xgb_class_0': 0.03241917880902835, 'weight_xgb_class_1': 0.680442165713369, 'weight_xgb_class_2': 0.6417420981327044}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:01,901] Trial 1109 finished with value: 0.949724313242393 and parameters: {'weight_lgbm_class_0': 0.05980866979561562, 'weight_lgbm_class_1': 0.9842606236847241, 'weight_lgbm_class_2': 0.33056880077533224, 'weight_xgb_class_0': 0.03189919499113432, 'weight_xgb_class_1': 0.6880073830148647, 'weight_xgb_class_2': 0.6989592688174431}. Best is trial 1057 with value: 0.9498290916740215.

Best trial: 1057. Best value: 0.949829:  56%|████████████████████████████████████████████████████████████████████████▍                                                         | 1114/2000 [00:30<00:34, 25.85it/s]

[I 2026-07-05 15:32:01,966] Trial 1110 finished with value: 0.9497220687661402 and parameters: {'weight_lgbm_class_0': 0.0645956364237933, 'weight_lgbm_class_1': 0.9919733235410594, 'weight_lgbm_class_2': 0.33577067546520784, 'weight_xgb_class_0': 0.02753646707014029, 'weight_xgb_class_1': 0.7319680013244996, 'weight_xgb_class_2': 0.6380895259562703}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:02,008] Trial 1112 finished with value: 0.9497928134999448 and parameters: {'weight_lgbm_class_0': 0.06765927592026616, 'weight_lgbm_class_1': 0.9913565925404366, 'weight_lgbm_class_2': 0.3340890582886374, 'weight_xgb_class_0': 0.03047780761277994, 'weight_xgb_class_1': 0.6783164216566269, 'weight_xgb_class_2': 0.6251602297234254}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:02,020] Trial 1111 finished with value: 0.9497564812628299 and parameters: {'weight_lgbm_class_0': 0.061243108509266106, 'weight_lgbm_class_1': 0.9940371084068393, 'weight_lgbm_class_2': 0.33719412867926407, 'weight_xgb_class_0': 0.030745241138478062, 'weight_xgb_class_1': 0.6769448771982775, 'weight_xgb_class_2': 0.6195707907472324}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:02,108] Trial 1113 finished with value: 0.949668778586196 and parameters: {'weight_lgbm_class_0': 0.08411961250635999, 'weight_lgbm_class_1': 0.9840491448233738, 'weight_lgbm_class_2': 0.334831388884203, 'weight_xgb_class_0': 0.031324739787801065, 'weight_xgb_class_1': 0.6735861154390406, 'weight_xgb_class_2': 0.6158084502399931}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:02,116] Trial 1114 finished with value: 0.9495768252038971 and parameters: {'weight_lgbm_class_0': 0.09174088947106923, 'weight_lgbm_class_1': 0.9831126497165361, 'weight_lgbm_class_2': 0.334620245847772, 'weight_xgb_class_0': 0.028101483308337515, 'weight_xgb_class_1': 0.7317813884671225, 'weight_xgb_class_2': 0.6270740835943484}. Best is trial 1057 with value: 0.9498290916740215.

[I 2026-07-05 15:32:02,184] Trial 1115 finished with value: 0.9496960361288406 and parameters: {'weight_lgbm_class_0': 0.08030811337520323, 'weight_lgbm_class_1': 0.9786695029671753, 'weight_lgbm_class_2': 0.3347944806367726, 'weight_xgb_class_0': 0.03532421946860798, 'weight_xgb_class_1': 0.7268757136595072, 'weight_xgb_class_2': 0.6175567014943789}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:02,186] Trial 1116 finished with value: 0.9492286696077127 and parameters: {'weight_lgbm_class_0': 0.09052983788903345, 'weight_lgbm_class_1': 0.9807050532181311, 'weight_lgbm_class_2': 0.3323459004285186, 'weight_xgb_class_0': 0.04163044608725159, 'weight_xgb_class_1': 0.6661090734309694, 'weight_xgb_class_2': 0.6257888727904289}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:02,210] Trial 1117 finished with value: 0.9497238019535885 and parameters: {'weight_lgbm_class_0': 0.06335112164405526, 'weight_lgbm_class_1': 0.9837263850613466, 'weight_lgbm_class_2': 0.3967895288063802, 'weight_xgb_class_0': 0.026706298552014406, 'weight_xgb_class_1': 0.6756489661502894, 'weight_xgb_class_2': 0.6150455927176748}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:02,242] Trial 1118 finished with value: 0.9497509358830413 and parameters: {'weight_lgbm_class_0': 0.06341210444020826, 'weight_lgbm_class_1': 0.9969980912765803, 'weight_lgbm_class_2': 0.33348045209843163, 'weight_xgb_class_0': 0.028731828897472677, 'weight_xgb_class_1': 0.6748184393559913, 'weight_xgb_class_2': 0.6190054664866781}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:02,292] Trial 1120 finished with value: 0.9068406633244961 and parameters: {'weight_lgbm_class_0': 0.7756353196048165, 'weight_lgbm_class_1': 0.947939901133551, 'weight_lgbm_class_2': 0.32848472511396304, 'weight_xgb_class_0': 0.026825692481386713, 'weight_xgb_class_1': 0.6641768615230312, 'weight_xgb_class_2': 0.69399514955491}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:02,296] Trial 1119 finished with value: 0.9496990669768333 and parameters: {'weight_lgbm_class_0': 0.06038587341263958, 'weight_lgbm_class_1': 0.95097158463495, 'weight_lgbm_class_2': 0.394447732463913, 'weight_xgb_class_0': 0.02713886386068843, 'weight_xgb_class_1': 0.7319991836739558, 'weight_xgb_class_2': 0.6188764945298101}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:02,307] Trial 1121 finished with value: 0.94960649498128 and parameters: {'weight_lgbm_class_0': 0.0916998983290715, 'weight_lgbm_class_1': 0.9976779646225693, 'weight_lgbm_class_2': 0.3952059053528852, 'weight_xgb_class_0': 0.031734095879354024, 'weight_xgb_class_1': 0.6646328387267758, 'weight_xgb_class_2': 0.6151299720067303}. Best is trial 1057 with value: 0.9498290916740215.

Best trial: 1057. Best value: 0.949829:  56%|█████████████████████████████████████████████████████████████████████████▎                                                        | 1127/2000 [00:31<00:30, 28.39it/s]

[I 2026-07-05 15:32:02,396] Trial 1122 finished with value: 0.9497483458769894 and parameters: {'weight_lgbm_class_0': 0.09012365220013784, 'weight_lgbm_class_1': 0.9994738900203, 'weight_lgbm_class_2': 0.30828827998453867, 'weight_xgb_class_0': 0.027199540201321218, 'weight_xgb_class_1': 0.6673057664658824, 'weight_xgb_class_2': 0.6844385087472645}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:02,400] Trial 1123 finished with value: 0.9497730803397615 and parameters: {'weight_lgbm_class_0': 0.08332652036837568, 'weight_lgbm_class_1': 0.9852279245576928, 'weight_lgbm_class_2': 0.3061200781143386, 'weight_xgb_class_0': 0.026886485910681258, 'weight_xgb_class_1': 0.669370354523677, 'weight_xgb_class_2': 0.6780785824534056}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:02,448] Trial 1124 finished with value: 0.9088635035888842 and parameters: {'weight_lgbm_class_0': 0.7438904462883598, 'weight_lgbm_class_1': 0.9996135546028528, 'weight_lgbm_class_2': 0.3141345255828296, 'weight_xgb_class_0': 0.029613167630181014, 'weight_xgb_class_1': 0.6639202864786327, 'weight_xgb_class_2': 0.6930926615525473}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:02,508] Trial 1126 finished with value: 0.9490862788470705 and parameters: {'weight_lgbm_class_0': 0.0889476440669281, 'weight_lgbm_class_1': 0.9959184645020528, 'weight_lgbm_class_2': 0.3079309654797911, 'weight_xgb_class_0': 0.05417392669281418, 'weight_xgb_class_1': 0.674388051113075, 'weight_xgb_class_2': 0.6787403730388242}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:02,517] Trial 1125 finished with value: 0.9490927080332971 and parameters: {'weight_lgbm_class_0': 0.09378461273784003, 'weight_lgbm_class_1': 0.9953854180096758, 'weight_lgbm_class_2': 0.3042487992181182, 'weight_xgb_class_0': 0.04973857911938087, 'weight_xgb_class_1': 0.662234306816482, 'weight_xgb_class_2': 0.6792096583393926}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:02,589] Trial 1127 finished with value: 0.9497322422600463 and parameters: {'weight_lgbm_class_0': 0.05559678029577398, 'weight_lgbm_class_1': 0.9575923439183353, 'weight_lgbm_class_2': 0.3116969779504873, 'weight_xgb_class_0': 0.058840131011823685, 'weight_xgb_class_1': 0.6705086253666024, 'weight_xgb_class_2': 0.7026902569085416}. Best is trial 1057 with value: 0.9498290916740215.

[I 2026-07-05 15:32:02,662] Trial 1128 finished with value: 0.9490067343241307 and parameters: {'weight_lgbm_class_0': 0.09342958021584773, 'weight_lgbm_class_1': 0.9601124850930624, 'weight_lgbm_class_2': 0.3092301288381216, 'weight_xgb_class_0': 0.058637559589496034, 'weight_xgb_class_1': 0.7694072845273561, 'weight_xgb_class_2': 0.677275427641333}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:02,680] Trial 1130 finished with value: 0.948959405385275 and parameters: {'weight_lgbm_class_0': 0.09133112535586417, 'weight_lgbm_class_1': 0.9998715665932414, 'weight_lgbm_class_2': 0.309688111427355, 'weight_xgb_class_0': 0.06073000997117942, 'weight_xgb_class_1': 0.6494890777528931, 'weight_xgb_class_2': 0.6780657124724724}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:02,697] Trial 1129 finished with value: 0.9490772531887118 and parameters: {'weight_lgbm_class_0': 0.08839863691857833, 'weight_lgbm_class_1': 0.9540259628664958, 'weight_lgbm_class_2': 0.31387740166824774, 'weight_xgb_class_0': 0.05670695693186298, 'weight_xgb_class_1': 0.6327524607745305, 'weight_xgb_class_2': 0.6806785636605441}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:02,723] Trial 1131 finished with value: 0.9490408634291793 and parameters: {'weight_lgbm_class_0': 0.0899181971508049, 'weight_lgbm_class_1': 0.9591513598977892, 'weight_lgbm_class_2': 0.30611274164796765, 'weight_xgb_class_0': 0.056374884640250054, 'weight_xgb_class_1': 0.6854129980064141, 'weight_xgb_class_2': 0.6783780902961883}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:02,742] Trial 1132 finished with value: 0.9488808353907734 and parameters: {'weight_lgbm_class_0': 0.09277086585954326, 'weight_lgbm_class_1': 0.9595249597146733, 'weight_lgbm_class_2': 0.3092327550501111, 'weight_xgb_class_0': 0.06060169634173965, 'weight_xgb_class_1': 0.6522022151157647, 'weight_xgb_class_2': 0.672240352384065}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:02,774] Trial 1133 finished with value: 0.9490167336962679 and parameters: {'weight_lgbm_class_0': 0.08809296261127858, 'weight_lgbm_class_1': 0.962049092622356, 'weight_lgbm_class_2': 0.3077327333348845, 'weight_xgb_class_0': 0.05916694196084833, 'weight_xgb_class_1': 0.6377136753809286, 'weight_xgb_class_2': 0.679250136106396}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:02,829] Trial 1135 finished with value: 0.949780665881153 and parameters: {'weight_lgbm_class_0': 0.05136385378793831, 'weight_lgbm_class_1': 0.9543551966451046, 'weight_lgbm_class_2': 0.3042182827505383, 'weight_xgb_class_0': 0.05904193368850839, 'weight_xgb_class_1': 0.7730692182252712, 'weight_xgb_class_2': 0.6738607330887523}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:02,849] Trial 1134 finished with value: 0.9356689053512962 and parameters: {'weight_lgbm_class_0': 0.32052077195714246, 'weight_lgbm_class_1': 0.9603519849023173, 'weight_lgbm_class_2': 0.31540825661282995, 'weight_xgb_class_0': 0.05588673878594271, 'weight_xgb_class_1': 0.6876274874968785, 'weight_xgb_class_2': 0.5627528954585058}. Best is trial 1057 with value: 0.9498290916740215.

Best trial: 1057. Best value: 0.949829:  57%|██████████████████████████████████████████████████████████████████████████                                                        | 1139/2000 [00:31<00:30, 27.83it/s]

[I 2026-07-05 15:32:02,854] Trial 1136 finished with value: 0.9497535035811654 and parameters: {'weight_lgbm_class_0': 0.0518599724076657, 'weight_lgbm_class_1': 0.9591452866767022, 'weight_lgbm_class_2': 0.35323479358180976, 'weight_xgb_class_0': 0.05983606541217426, 'weight_xgb_class_1': 0.6799790155393648, 'weight_xgb_class_2': 0.6725727164252203}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:02,945] Trial 1138 finished with value: 0.9496987260704882 and parameters: {'weight_lgbm_class_0': 0.052787094430042224, 'weight_lgbm_class_1': 0.9551717054327231, 'weight_lgbm_class_2': 0.35757852046813304, 'weight_xgb_class_0': 0.05858508144916563, 'weight_xgb_class_1': 0.6275469045180191, 'weight_xgb_class_2': 0.7078059714621966}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:02,950] Trial 1137 finished with value: 0.9497231727647839 and parameters: {'weight_lgbm_class_0': 0.05333820516951056, 'weight_lgbm_class_1': 0.9566714327869804, 'weight_lgbm_class_2': 0.3594106585873818, 'weight_xgb_class_0': 0.06037269291237079, 'weight_xgb_class_1': 0.6344849330064999, 'weight_xgb_class_2': 0.7096839501632398}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:02,994] Trial 1139 finished with value: 0.9387468766790951 and parameters: {'weight_lgbm_class_0': 0.05023243010129627, 'weight_lgbm_class_1': 0.9610464222905362, 'weight_lgbm_class_2': 0.3926032618386586, 'weight_xgb_class_0': 0.3395611400657247, 'weight_xgb_class_1': 0.6341857630715637, 'weight_xgb_class_2': 0.668935361443658}. Best is trial 1057 with value: 0.9498290916740215.

Best trial: 1057. Best value: 0.949829:  57%|██████████████████████████████████████████████████████████████████████████▌                                                       | 1147/2000 [00:31<00:29, 28.45it/s]

[I 2026-07-05 15:32:03,094] Trial 1141 finished with value: 0.9134299517077537 and parameters: {'weight_lgbm_class_0': 0.05299541857621891, 'weight_lgbm_class_1': 0.9572953254878609, 'weight_lgbm_class_2': 0.39696570842627005, 'weight_xgb_class_0': 0.6405429759431237, 'weight_xgb_class_1': 0.6827890483706214, 'weight_xgb_class_2': 0.574309942148696}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:03,137] Trial 1140 finished with value: 0.9496607885534347 and parameters: {'weight_lgbm_class_0': 0.05110476019476025, 'weight_lgbm_class_1': 0.9609497306050276, 'weight_lgbm_class_2': 0.35759016714323005, 'weight_xgb_class_0': 0.05958609539513415, 'weight_xgb_class_1': 0.6339871080282176, 'weight_xgb_class_2': 0.5585906798236387}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:03,144] Trial 1143 finished with value: 0.94957360204871 and parameters: {'weight_lgbm_class_0': 0.05673969653932176, 'weight_lgbm_class_1': 0.9413465306870101, 'weight_lgbm_class_2': 0.358678964163565, 'weight_xgb_class_0': 0.059170647954430694, 'weight_xgb_class_1': 0.774441228775763, 'weight_xgb_class_2': 0.5621498614472666}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:03,185] Trial 1142 finished with value: 0.9168777011338715 and parameters: {'weight_lgbm_class_0': 0.04329731630057787, 'weight_lgbm_class_1': 0.9455897523669161, 'weight_lgbm_class_2': 0.358326612971371, 'weight_xgb_class_0': 0.653371593682414, 'weight_xgb_class_1': 0.690005790972386, 'weight_xgb_class_2': 0.7186648003106936}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:03,191] Trial 1144 finished with value: 0.9177003665317612 and parameters: {'weight_lgbm_class_0': 0.051751730959987995, 'weight_lgbm_class_1': 0.9483361612098228, 'weight_lgbm_class_2': 0.36008520280160644, 'weight_xgb_class_0': 0.6412621937451317, 'weight_xgb_class_1': 0.7645534950184396, 'weight_xgb_class_2': 0.7101029495193195}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:03,208] Trial 1145 finished with value: 0.9497616635157144 and parameters: {'weight_lgbm_class_0': 0.05057812215647382, 'weight_lgbm_class_1': 0.9392426576164206, 'weight_lgbm_class_2': 0.3918228682348631, 'weight_xgb_class_0': 0.06138633564450401, 'weight_xgb_class_1': 0.7719653075145141, 'weight_xgb_class_2': 0.5543512305771945}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:03,240] Trial 1146 finished with value: 0.8930818108545341 and parameters: {'weight_lgbm_class_0': 0.05369174971119436, 'weight_lgbm_class_1': 0.9403822328194942, 'weight_lgbm_class_2': 0.39164316974960534, 'weight_xgb_class_0': 0.999666791562263, 'weight_xgb_class_1': 0.7774623023026476, 'weight_xgb_class_2': 0.6465638235705379}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:03,262] Trial 1147 finished with value: 0.949555322994545 and parameters: {'weight_lgbm_class_0': 0.05276244615322277, 'weight_lgbm_class_1': 0.9384273256202533, 'weight_lgbm_class_2': 0.3588726304803833, 'weight_xgb_class_0': 0.06809244062690532, 'weight_xgb_class_1': 0.19050357815100993, 'weight_xgb_class_2': 0.704823748691694}. Best is trial 1057 with value: 0.9498290916740215.

Best trial: 1057. Best value: 0.949829:  58%|██████████████████████████████████████████████████████████████████████████▉                                                       | 1153/2000 [00:32<00:31, 27.14it/s]

[I 2026-07-05 15:32:03,295] Trial 1148 finished with value: 0.9497457338356923 and parameters: {'weight_lgbm_class_0': 0.05173851056590265, 'weight_lgbm_class_1': 0.9375009584090275, 'weight_lgbm_class_2': 0.3907349484978495, 'weight_xgb_class_0': 0.06453487370789142, 'weight_xgb_class_1': 0.7792253928326178, 'weight_xgb_class_2': 0.716354331481315}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:03,379] Trial 1150 finished with value: 0.9497159822955729 and parameters: {'weight_lgbm_class_0': 0.06916030946783283, 'weight_lgbm_class_1': 0.9397538091106765, 'weight_lgbm_class_2': 0.3888029807435008, 'weight_xgb_class_0': 0.025524128929948445, 'weight_xgb_class_1': 0.771204123885816, 'weight_xgb_class_2': 0.6450487499251187}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:03,402] Trial 1149 finished with value: 0.949763313508987 and parameters: {'weight_lgbm_class_0': 0.0711004361170411, 'weight_lgbm_class_1': 0.9402467751920409, 'weight_lgbm_class_2': 0.3887997260561179, 'weight_xgb_class_0': 0.026841148740063048, 'weight_xgb_class_1': 0.7720755049803791, 'weight_xgb_class_2': 0.7221750566175007}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:03,421] Trial 1151 finished with value: 0.9498199855815693 and parameters: {'weight_lgbm_class_0': 0.07129166398129387, 'weight_lgbm_class_1': 0.9371999609040225, 'weight_lgbm_class_2': 0.38920041128199406, 'weight_xgb_class_0': 0.02949662624826925, 'weight_xgb_class_1': 0.7732731403121368, 'weight_xgb_class_2': 0.6434347310794166}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:03,490] Trial 1152 finished with value: 0.9357502400396681 and parameters: {'weight_lgbm_class_0': 0.4234584334519017, 'weight_lgbm_class_1': 0.9335875694043427, 'weight_lgbm_class_2': 0.3893573425543946, 'weight_xgb_class_0': 0.026841125524628702, 'weight_xgb_class_1': 0.7682977852418532, 'weight_xgb_class_2': 0.7193576320759754}. Best is trial 1057 with value: 0.9498290916740215.

Best trial: 1057. Best value: 0.949829:  58%|███████████████████████████████████████████████████████████████████████████▍                                                      | 1160/2000 [00:32<00:29, 28.16it/s]

[I 2026-07-05 15:32:03,530] Trial 1154 finished with value: 0.9497717757609251 and parameters: {'weight_lgbm_class_0': 0.07293654826782285, 'weight_lgbm_class_1': 0.9334415620211682, 'weight_lgbm_class_2': 0.39152950271076087, 'weight_xgb_class_0': 0.03088797172297245, 'weight_xgb_class_1': 0.7149249895867772, 'weight_xgb_class_2': 0.6456401369266296}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:03,535] Trial 1153 finished with value: 0.9495657511114026 and parameters: {'weight_lgbm_class_0': 0.07022476388043838, 'weight_lgbm_class_1': 0.9360300673073286, 'weight_lgbm_class_2': 0.3882085810092427, 'weight_xgb_class_0': 0.026713200408698397, 'weight_xgb_class_1': 0.1596570577097603, 'weight_xgb_class_2': 0.6481401684657092}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:03,555] Trial 1155 finished with value: 0.9449236776534553 and parameters: {'weight_lgbm_class_0': 0.24675475013053189, 'weight_lgbm_class_1': 0.9761752911962774, 'weight_lgbm_class_2': 0.3393640294366433, 'weight_xgb_class_0': 0.02337272263438521, 'weight_xgb_class_1': 0.7193085072444384, 'weight_xgb_class_2': 0.6496211119314058}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:03,629] Trial 1157 finished with value: 0.9498065118419331 and parameters: {'weight_lgbm_class_0': 0.07092459480378854, 'weight_lgbm_class_1': 0.9366545009373839, 'weight_lgbm_class_2': 0.33475034492923544, 'weight_xgb_class_0': 0.025413307403706425, 'weight_xgb_class_1': 0.7297562772883781, 'weight_xgb_class_2': 0.6467509680503339}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:03,629] Trial 1156 finished with value: 0.9497609694750134 and parameters: {'weight_lgbm_class_0': 0.06966258940594676, 'weight_lgbm_class_1': 0.9760151568764024, 'weight_lgbm_class_2': 0.3353489559281677, 'weight_xgb_class_0': 0.026037438359797414, 'weight_xgb_class_1': 0.7210549431959078, 'weight_xgb_class_2': 0.6454201762983057}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:03,630] Trial 1158 finished with value: 0.9498012801287182 and parameters: {'weight_lgbm_class_0': 0.07636607002960913, 'weight_lgbm_class_1': 0.9753218221119583, 'weight_lgbm_class_2': 0.3370983728829141, 'weight_xgb_class_0': 0.024278437007662003, 'weight_xgb_class_1': 0.7297997527896126, 'weight_xgb_class_2': 0.6374146521534644}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:03,696] Trial 1159 finished with value: 0.9447418010916895 and parameters: {'weight_lgbm_class_0': 0.24960297518657865, 'weight_lgbm_class_1': 0.9788166697060077, 'weight_lgbm_class_2': 0.33889569936651054, 'weight_xgb_class_0': 0.024018175012522666, 'weight_xgb_class_1': 0.717809459556731, 'weight_xgb_class_2': 0.6479579423327427}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:03,723] Trial 1160 finished with value: 0.9498163479144708 and parameters: {'weight_lgbm_class_0': 0.07759800800180573, 'weight_lgbm_class_1': 0.9732119215787673, 'weight_lgbm_class_2': 0.33610537454074896, 'weight_xgb_class_0': 0.026481210796807424, 'weight_xgb_class_1': 0.722497686977699, 'weight_xgb_class_2': 0.6494204053515534}. Best is trial 1057 with value: 0.9498290916740215.

Best trial: 1057. Best value: 0.949829:  58%|███████████████████████████████████████████████████████████████████████████▊                                                      | 1167/2000 [00:32<00:28, 28.95it/s]

[I 2026-07-05 15:32:03,781] Trial 1161 finished with value: 0.9299420238715617 and parameters: {'weight_lgbm_class_0': 0.4595358010843242, 'weight_lgbm_class_1': 0.9756222670951167, 'weight_lgbm_class_2': 0.34100608619376666, 'weight_xgb_class_0': 0.02812883702624903, 'weight_xgb_class_1': 0.7169892864724603, 'weight_xgb_class_2': 0.6474934091760155}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:03,806] Trial 1162 finished with value: 0.9497705046282897 and parameters: {'weight_lgbm_class_0': 0.03028614598447548, 'weight_lgbm_class_1': 0.9736223293130531, 'weight_lgbm_class_2': 0.3946591190005561, 'weight_xgb_class_0': 0.08517945571859632, 'weight_xgb_class_1': 0.7181512953520899, 'weight_xgb_class_2': 0.6442300719039703}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:03,827] Trial 1163 finished with value: 0.9497471424929067 and parameters: {'weight_lgbm_class_0': 0.03481564334738706, 'weight_lgbm_class_1': 0.9766069778966115, 'weight_lgbm_class_2': 0.40254667003574185, 'weight_xgb_class_0': 0.08619627779323938, 'weight_xgb_class_1': 0.7235240122686272, 'weight_xgb_class_2': 0.6504937463816612}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:03,882] Trial 1164 finished with value: 0.9490275165357748 and parameters: {'weight_lgbm_class_0': 0.06786840756844531, 'weight_lgbm_class_1': 0.9765883882910854, 'weight_lgbm_class_2': 0.3709953613324004, 'weight_xgb_class_0': 0.08583276328333606, 'weight_xgb_class_1': 0.7172718740355145, 'weight_xgb_class_2': 0.6438446138306572}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:03,904] Trial 1165 finished with value: 0.9498096779886858 and parameters: {'weight_lgbm_class_0': 0.03298119974526159, 'weight_lgbm_class_1': 0.9713815053405265, 'weight_lgbm_class_2': 0.37159670257971805, 'weight_xgb_class_0': 0.08437702937204622, 'weight_xgb_class_1': 0.7417420765861736, 'weight_xgb_class_2': 0.6375693646201126}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:03,939] Trial 1166 finished with value: 0.9496763145852061 and parameters: {'weight_lgbm_class_0': 0.03202779477649763, 'weight_lgbm_class_1': 0.973266163296335, 'weight_lgbm_class_2': 0.3731657726320846, 'weight_xgb_class_0': 0.08627271898620284, 'weight_xgb_class_1': 0.7426195865467918, 'weight_xgb_class_2': 0.5987882295630067}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:03,974] Trial 1167 finished with value: 0.8993295209361429 and parameters: {'weight_lgbm_class_0': 0.8296437329065331, 'weight_lgbm_class_1': 0.9735342282040594, 'weight_lgbm_class_2': 0.36901202353695206, 'weight_xgb_class_0': 0.08161719032131345, 'weight_xgb_class_1': 0.7377380326872106, 'weight_xgb_class_2': 0.6058306674471141}. Best is trial 1057 with value: 0.9498290916740215.

[I 2026-07-05 15:32:04,021] Trial 1169 finished with value: 0.9494933557521179 and parameters: {'weight_lgbm_class_0': 0.03339175623997154, 'weight_lgbm_class_1': 0.9711228440439699, 'weight_lgbm_class_2': 0.36783791120545106, 'weight_xgb_class_0': 0.04391162782509252, 'weight_xgb_class_1': 0.7363239948609227, 'weight_xgb_class_2': 0.637415396651631}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:04,054] Trial 1168 finished with value: 0.949453467261225 and parameters: {'weight_lgbm_class_0': 0.03156851956904127, 'weight_lgbm_class_1': 0.9713236549195688, 'weight_lgbm_class_2': 0.3701045893496119, 'weight_xgb_class_0': 0.04201163157907494, 'weight_xgb_class_1': 0.7389403410263186, 'weight_xgb_class_2': 0.6026228805362478}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:04,078] Trial 1170 finished with value: 0.9495854031430483 and parameters: {'weight_lgbm_class_0': 0.03406180252600365, 'weight_lgbm_class_1': 0.9709704569552461, 'weight_lgbm_class_2': 0.08857852171297198, 'weight_xgb_class_0': 0.046429293930347004, 'weight_xgb_class_1': 0.7367307950363616, 'weight_xgb_class_2': 0.6057075761868729}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:04,121] Trial 1171 finished with value: 0.9496066574377607 and parameters: {'weight_lgbm_class_0': 0.1011871959899805, 'weight_lgbm_class_1': 0.9710631174746255, 'weight_lgbm_class_2': 0.3672244247345061, 'weight_xgb_class_0': 0.018216959507706305, 'weight_xgb_class_1': 0.7364182287441536, 'weight_xgb_class_2': 0.59911692854785}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:04,153] Trial 1172 finished with value: 0.9497158695663215 and parameters: {'weight_lgbm_class_0': 0.0996293063109799, 'weight_lgbm_class_1': 0.9751406688199632, 'weight_lgbm_class_2': 0.37837838245735816, 'weight_xgb_class_0': 0.018124831760826902, 'weight_xgb_class_1': 0.736772286340389, 'weight_xgb_class_2': 0.6029741135836229}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:04,230] Trial 1175 finished with value: 0.9496904984617238 and parameters: {'weight_lgbm_class_0': 0.07633959037327426, 'weight_lgbm_class_1': 0.9713293533808942, 'weight_lgbm_class_2': 0.3648377590788998, 'weight_xgb_class_0': 0.04128655925344945, 'weight_xgb_class_1': 0.737229416791686, 'weight_xgb_class_2': 0.6088926695955051}. Best is trial 1057 with value: 0.9498290916740215.

Best trial: 1057. Best value: 0.949829:  59%|████████████████████████████████████████████████████████████████████████████▋                                                     | 1180/2000 [00:33<00:29, 27.50it/s]

[I 2026-07-05 15:32:04,255] Trial 1174 finished with value: 0.9061555503412219 and parameters: {'weight_lgbm_class_0': 0.09475948818781964, 'weight_lgbm_class_1': 0.9707691377851559, 'weight_lgbm_class_2': 0.37018158640186904, 'weight_xgb_class_0': 0.7072886412961882, 'weight_xgb_class_1': 0.7392657272882701, 'weight_xgb_class_2': 0.5954368052923465}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:04,278] Trial 1173 finished with value: 0.9496087417036317 and parameters: {'weight_lgbm_class_0': 0.07659488569660733, 'weight_lgbm_class_1': 0.9708868501631545, 'weight_lgbm_class_2': 0.3704025443530571, 'weight_xgb_class_0': 0.043376964682934484, 'weight_xgb_class_1': 0.7422481088917149, 'weight_xgb_class_2': 0.6031978331950932}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:04,319] Trial 1176 finished with value: 0.9491182432931794 and parameters: {'weight_lgbm_class_0': 0.10111564830017544, 'weight_lgbm_class_1': 0.9999929118370045, 'weight_lgbm_class_2': 0.3723228056565365, 'weight_xgb_class_0': 0.043833446849250286, 'weight_xgb_class_1': 0.7353523171077905, 'weight_xgb_class_2': 0.6180828870299641}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:04,329] Trial 1177 finished with value: 0.949049216465302 and parameters: {'weight_lgbm_class_0': 0.10276395766954569, 'weight_lgbm_class_1': 0.9816200275871803, 'weight_lgbm_class_2': 0.37040493429746757, 'weight_xgb_class_0': 0.043026424976311754, 'weight_xgb_class_1': 0.7394145639297214, 'weight_xgb_class_2': 0.5984909794880543}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:04,384] Trial 1178 finished with value: 0.949811944657038 and parameters: {'weight_lgbm_class_0': 0.09859232145759407, 'weight_lgbm_class_1': 0.9660165165719854, 'weight_lgbm_class_2': 0.4042739531985351, 'weight_xgb_class_0': 0.018530340535441628, 'weight_xgb_class_1': 0.7409591915810242, 'weight_xgb_class_2': 0.6032248211088626}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:04,397] Trial 1179 finished with value: 0.9497060173565779 and parameters: {'weight_lgbm_class_0': 0.09998106102191842, 'weight_lgbm_class_1': 0.9687574187584346, 'weight_lgbm_class_2': 0.40395521368482196, 'weight_xgb_class_0': 0.020286186277611782, 'weight_xgb_class_1': 0.7344235465689701, 'weight_xgb_class_2': 0.6077588050760426}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:04,461] Trial 1180 finished with value: 0.9497342870451031 and parameters: {'weight_lgbm_class_0': 0.1000579139041486, 'weight_lgbm_class_1': 0.9985859664637645, 'weight_lgbm_class_2': 0.40218715985076775, 'weight_xgb_class_0': 0.020748707789363375, 'weight_xgb_class_1': 0.7285452953644206, 'weight_xgb_class_2': 0.6181453187804318}. Best is trial 1057 with value: 0.9498290916740215.

Best trial: 1057. Best value: 0.949829:  59%|█████████████████████████████████████████████████████████████████████████████                                                     | 1185/2000 [00:33<00:27, 29.81it/s]

[I 2026-07-05 15:32:04,484] Trial 1182 finished with value: 0.9497650844987257 and parameters: {'weight_lgbm_class_0': 0.1009838181107715, 'weight_lgbm_class_1': 0.9612018724982975, 'weight_lgbm_class_2': 0.4053100215329793, 'weight_xgb_class_0': 0.017983334461314462, 'weight_xgb_class_1': 0.7441291418261439, 'weight_xgb_class_2': 0.6225993511303515}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:04,499] Trial 1181 finished with value: 0.9497635666256962 and parameters: {'weight_lgbm_class_0': 0.07951951126296618, 'weight_lgbm_class_1': 0.9570312379793132, 'weight_lgbm_class_2': 0.4021036286096509, 'weight_xgb_class_0': 0.01824027296242476, 'weight_xgb_class_1': 0.7481327112357818, 'weight_xgb_class_2': 0.6299624634166189}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:04,534] Trial 1183 finished with value: 0.9497498426940009 and parameters: {'weight_lgbm_class_0': 0.07616461592641742, 'weight_lgbm_class_1': 0.9519043157595963, 'weight_lgbm_class_2': 0.39842145830226905, 'weight_xgb_class_0': 0.01898221140635147, 'weight_xgb_class_1': 0.736725560980863, 'weight_xgb_class_2': 0.6237434529848135}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:04,575] Trial 1184 finished with value: 0.9490941692713806 and parameters: {'weight_lgbm_class_0': 0.07863608858353571, 'weight_lgbm_class_1': 0.09308761634063029, 'weight_lgbm_class_2': 0.3993841095712135, 'weight_xgb_class_0': 0.043600065007648514, 'weight_xgb_class_1': 0.748679034429775, 'weight_xgb_class_2': 0.6308913587963355}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:04,662] Trial 1185 finished with value: 0.949752442666537 and parameters: {'weight_lgbm_class_0': 0.07617957311341059, 'weight_lgbm_class_1': 0.9553585347900059, 'weight_lgbm_class_2': 0.40371299006996186, 'weight_xgb_class_0': 0.019554044719102874, 'weight_xgb_class_1': 0.7517755637884498, 'weight_xgb_class_2': 0.6230243089101855}. Best is trial 1057 with value: 0.9498290916740215.

Best trial: 1057. Best value: 0.949829:  60%|█████████████████████████████████████████████████████████████████████████████▍                                                    | 1192/2000 [00:33<00:31, 25.49it/s]

[I 2026-07-05 15:32:04,711] Trial 1186 finished with value: 0.9497810805576323 and parameters: {'weight_lgbm_class_0': 0.07565780190899962, 'weight_lgbm_class_1': 0.9509533592200712, 'weight_lgbm_class_2': 0.3993957215540331, 'weight_xgb_class_0': 0.02167033630108286, 'weight_xgb_class_1': 0.7084442534284221, 'weight_xgb_class_2': 0.6304463227543469}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:04,760] Trial 1187 finished with value: 0.9498273739736875 and parameters: {'weight_lgbm_class_0': 0.07496073443097824, 'weight_lgbm_class_1': 0.9567005824405825, 'weight_lgbm_class_2': 0.4026659804349402, 'weight_xgb_class_0': 0.028217589080766495, 'weight_xgb_class_1': 0.7566804997786657, 'weight_xgb_class_2': 0.659661297543292}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:04,768] Trial 1189 finished with value: 0.9258230580522184 and parameters: {'weight_lgbm_class_0': 0.5352882800837693, 'weight_lgbm_class_1': 0.9575422211563186, 'weight_lgbm_class_2': 0.39528695053225565, 'weight_xgb_class_0': 0.018434097588249508, 'weight_xgb_class_1': 0.7544759774042622, 'weight_xgb_class_2': 0.6228029447132889}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:04,809] Trial 1188 finished with value: 0.9498150212255861 and parameters: {'weight_lgbm_class_0': 0.09799883656563105, 'weight_lgbm_class_1': 0.9534725709643228, 'weight_lgbm_class_2': 0.4042767975872395, 'weight_xgb_class_0': 0.01638542336450199, 'weight_xgb_class_1': 0.7114625592400984, 'weight_xgb_class_2': 0.5781633263348251}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:04,865] Trial 1190 finished with value: 0.9497709819979354 and parameters: {'weight_lgbm_class_0': 0.07925179927859954, 'weight_lgbm_class_1': 0.9516404830870824, 'weight_lgbm_class_2': 0.39854599870694724, 'weight_xgb_class_0': 0.014155718271881335, 'weight_xgb_class_1': 0.6985401027425424, 'weight_xgb_class_2': 0.5819126275589306}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:04,867] Trial 1191 finished with value: 0.9497434828933594 and parameters: {'weight_lgbm_class_0': 0.07821737810963945, 'weight_lgbm_class_1': 0.9993413680694035, 'weight_lgbm_class_2': 0.4033877893578393, 'weight_xgb_class_0': 0.016357115783457016, 'weight_xgb_class_1': 0.7062076875544759, 'weight_xgb_class_2': 0.6290902207991833}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:04,903] Trial 1193 finished with value: 0.9498043130659557 and parameters: {'weight_lgbm_class_0': 0.07803321208756782, 'weight_lgbm_class_1': 0.9522280128646169, 'weight_lgbm_class_2': 0.4034503399124675, 'weight_xgb_class_0': 0.019670001232852022, 'weight_xgb_class_1': 0.7067366278411749, 'weight_xgb_class_2': 0.5774320419610218}. Best is trial 1057 with value: 0.9498290916740215.

Best trial: 1195. Best value: 0.949847:  60%|█████████████████████████████████████████████████████████████████████████████▊                                                    | 1197/2000 [00:33<00:27, 29.20it/s]

[I 2026-07-05 15:32:04,929] Trial 1192 finished with value: 0.949692657736607 and parameters: {'weight_lgbm_class_0': 0.0749286912801404, 'weight_lgbm_class_1': 0.9505366206604031, 'weight_lgbm_class_2': 0.4036827189725049, 'weight_xgb_class_0': 0.014529429865998932, 'weight_xgb_class_1': 0.7126361469286537, 'weight_xgb_class_2': 0.6379791478653852}. Best is trial 1057 with value: 0.9498290916740215.
[I 2026-07-05 15:32:04,962] Trial 1195 finished with value: 0.9498465511727576 and parameters: {'weight_lgbm_class_0': 0.08532444411174266, 'weight_lgbm_class_1': 0.9984993115117289, 'weight_lgbm_class_2': 0.40007451987310577, 'weight_xgb_class_0': 0.021598518781434678, 'weight_xgb_class_1': 0.7059507641362244, 'weight_xgb_class_2': 0.5714504511448489}. Best is trial 1195 with value: 0.9498465511727576.
[I 2026-07-05 15:32:04,979] Trial 1194 finished with value: 0.9497426067995929 and parameters: {'weight_lgbm_class_0': 0.06823842923003594, 'weight_lgbm_class_1': 0.944835618854107, 'weight_lgbm_class_2': 0.3973817282661265, 'weight_xgb_class_0': 0.02396173810392159, 'weight_xgb_class_1': 0.7056518374047209, 'weight_xgb_class_2': 0.6335497420853904}. Best is trial 1195 with value: 0.9498465511727576.
[I 2026-07-05 15:32:04,992] Trial 1196 finished with value: 0.9497536794147697 and parameters: {'weight_lgbm_class_0': 0.07752029692314799, 'weight_lgbm_class_1': 0.9995449593823914, 'weight_lgbm_class_2': 0.40724256141118653, 'weight_xgb_class_0': 0.017370675880515517, 'weight_xgb_class_1': 0.7099287732039833, 'weight_xgb_class_2': 0.657753705693098}. Best is trial 1195 with value: 0.9498465511727576.
[I 2026-07-05 15:32:05,059] Trial 1197 finished with value: 0.949794760487856 and parameters: {'weight_lgbm_class_0': 0.07742866231743668, 'weight_lgbm_class_1': 0.9492968052049922, 'weight_lgbm_class_2': 0.3876723139882333, 'weight_xgb_class_0': 0.01828122283550974, 'weight_xgb_class_1': 0.708588795587887, 'weight_xgb_class_2': 0.5737432003729475}. Best is trial 1195 with value: 0.9498465511727576.

Best trial: 1206. Best value: 0.949858:  60%|██████████████████████████████████████████████████████████████████████████████▏                                                   | 1203/2000 [00:33<00:31, 25.29it/s]

[I 2026-07-05 15:32:05,151] Trial 1198 finished with value: 0.9266486387088321 and parameters: {'weight_lgbm_class_0': 0.5358603359642509, 'weight_lgbm_class_1': 0.9832429796526376, 'weight_lgbm_class_2': 0.38656640357684, 'weight_xgb_class_0': 0.01473970540277208, 'weight_xgb_class_1': 0.7056456145678798, 'weight_xgb_class_2': 0.6602730672292123}. Best is trial 1195 with value: 0.9498465511727576.
[I 2026-07-05 15:32:05,198] Trial 1200 finished with value: 0.9497996593490994 and parameters: {'weight_lgbm_class_0': 0.09608448431551421, 'weight_lgbm_class_1': 0.9473496174201422, 'weight_lgbm_class_2': 0.40863199761474045, 'weight_xgb_class_0': 0.013621327130424063, 'weight_xgb_class_1': 0.6944972296486033, 'weight_xgb_class_2': 0.5318982083340918}. Best is trial 1195 with value: 0.9498465511727576.
[I 2026-07-05 15:32:05,208] Trial 1199 finished with value: 0.9497836936886671 and parameters: {'weight_lgbm_class_0': 0.09864940708788383, 'weight_lgbm_class_1': 0.9437474569814065, 'weight_lgbm_class_2': 0.41202723877281566, 'weight_xgb_class_0': 0.021650782586351842, 'weight_xgb_class_1': 0.7095570000695552, 'weight_xgb_class_2': 0.6610890218585525}. Best is trial 1195 with value: 0.9498465511727576.
[I 2026-07-05 15:32:05,225] Trial 1201 finished with value: 0.9496348489049793 and parameters: {'weight_lgbm_class_0': 0.10042170211733092, 'weight_lgbm_class_1': 0.9994665120262014, 'weight_lgbm_class_2': 0.400927323013559, 'weight_xgb_class_0': 0.019247426323803746, 'weight_xgb_class_1': 0.7010309789948538, 'weight_xgb_class_2': 0.5821438641583436}. Best is trial 1195 with value: 0.9498465511727576.
[I 2026-07-05 15:32:05,304] Trial 1202 finished with value: 0.9496492063482571 and parameters: {'weight_lgbm_class_0': 0.09988339950587077, 'weight_lgbm_class_1': 0.9450906186580079, 'weight_lgbm_class_2': 0.4122152761671807, 'weight_xgb_class_0': 0.018184971319368547, 'weight_xgb_class_1': 0.7118421939038349, 'weight_xgb_class_2': 0.5665113472083263}. Best is trial 1195 with value: 0.9498465511727576.
[I 2026-07-05 15:32:05,317] Trial 1203 finished with value: 0.9496038464866151 and parameters: {'weight_lgbm_class_0': 0.10659792306522083, 'weight_lgbm_class_1': 0.9828716281361857, 'weight_lgbm_class_2': 0.4185205821689258, 'weight_xgb_class_0': 0.015147381585815165, 'weight_xgb_class_1': 0.7079611684271647, 'weight_xgb_class_2': 0.5732288702366624}. Best is trial 1195 with value: 0.9498465511727576.

Best trial: 1206. Best value: 0.949858:  60%|██████████████████████████████████████████████████████████████████████████████▌                                                   | 1209/2000 [00:34<00:28, 28.11it/s]

[I 2026-07-05 15:32:05,348] Trial 1206 finished with value: 0.9498581274668642 and parameters: {'weight_lgbm_class_0': 0.09564619752377986, 'weight_lgbm_class_1': 0.9989866119288622, 'weight_lgbm_class_2': 0.4164919536671644, 'weight_xgb_class_0': 0.010908617862171108, 'weight_xgb_class_1': 0.7046036902243331, 'weight_xgb_class_2': 0.5319929060865869}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:05,362] Trial 1204 finished with value: 0.9498268403692413 and parameters: {'weight_lgbm_class_0': 0.10409404655163976, 'weight_lgbm_class_1': 0.9842762572507684, 'weight_lgbm_class_2': 0.4081977981406668, 'weight_xgb_class_0': 0.010855874716171648, 'weight_xgb_class_1': 0.6983914394541371, 'weight_xgb_class_2': 0.5875357573918111}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:05,393] Trial 1205 finished with value: 0.9497190536108553 and parameters: {'weight_lgbm_class_0': 0.10380607972463271, 'weight_lgbm_class_1': 0.9824813300058989, 'weight_lgbm_class_2': 0.4198604460731793, 'weight_xgb_class_0': 0.014867414772263542, 'weight_xgb_class_1': 0.6910666348591219, 'weight_xgb_class_2': 0.5829345321123736}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:05,439] Trial 1207 finished with value: 0.9498528837876847 and parameters: {'weight_lgbm_class_0': 0.10246280661574292, 'weight_lgbm_class_1': 0.9844997451409927, 'weight_lgbm_class_2': 0.41862808609306357, 'weight_xgb_class_0': 0.0014661429696746463, 'weight_xgb_class_1': 0.687592806827216, 'weight_xgb_class_2': 0.5536639659192025}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:05,447] Trial 1208 finished with value: 0.9498149391954852 and parameters: {'weight_lgbm_class_0': 0.1013981446765358, 'weight_lgbm_class_1': 0.9982224621645744, 'weight_lgbm_class_2': 0.4159989361964398, 'weight_xgb_class_0': 0.0001563121997578583, 'weight_xgb_class_1': 0.6903702593818064, 'weight_xgb_class_2': 0.5220185584167512}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:05,470] Trial 1209 finished with value: 0.9491967756702384 and parameters: {'weight_lgbm_class_0': 0.11751775168826775, 'weight_lgbm_class_1': 0.9855900844136267, 'weight_lgbm_class_2': 0.42419140414697465, 'weight_xgb_class_0': 0.015099642444426825, 'weight_xgb_class_1': 0.7019600763885292, 'weight_xgb_class_2': 0.5314643264656579}. Best is trial 1206 with value: 0.9498581274668642.

[I 2026-07-05 15:32:05,591] Trial 1210 finished with value: 0.949842251376923 and parameters: {'weight_lgbm_class_0': 0.1032236197885843, 'weight_lgbm_class_1': 0.9989758263477846, 'weight_lgbm_class_2': 0.415264589014575, 'weight_xgb_class_0': 0.00038342029490304533, 'weight_xgb_class_1': 0.6895661454231864, 'weight_xgb_class_2': 0.5436230765292593}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:05,596] Trial 1211 finished with value: 0.9496029324052446 and parameters: {'weight_lgbm_class_0': 0.10431883945855985, 'weight_lgbm_class_1': 0.9794372086014033, 'weight_lgbm_class_2': 0.4199255103615705, 'weight_xgb_class_0': 0.012862389056706044, 'weight_xgb_class_1': 0.6931108839654768, 'weight_xgb_class_2': 0.5334655908022444}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:05,666] Trial 1212 finished with value: 0.949848304038842 and parameters: {'weight_lgbm_class_0': 0.11262246325659755, 'weight_lgbm_class_1': 0.9857122228298878, 'weight_lgbm_class_2': 0.41382372525239847, 'weight_xgb_class_0': 0.0010687430623947392, 'weight_xgb_class_1': 0.6894042180276448, 'weight_xgb_class_2': 0.5891663168456415}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:05,682] Trial 1213 finished with value: 0.9495227304798194 and parameters: {'weight_lgbm_class_0': 0.1070813016362001, 'weight_lgbm_class_1': 0.9759683289105694, 'weight_lgbm_class_2': 0.4134268277958321, 'weight_xgb_class_0': 0.012611165681052292, 'weight_xgb_class_1': 0.6891335902892133, 'weight_xgb_class_2': 0.5328608543141505}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:05,712] Trial 1214 finished with value: 0.949823665736183 and parameters: {'weight_lgbm_class_0': 0.10814872183845725, 'weight_lgbm_class_1': 0.9796972409042343, 'weight_lgbm_class_2': 0.42510080818892904, 'weight_xgb_class_0': 0.004624205425908402, 'weight_xgb_class_1': 0.686315929484995, 'weight_xgb_class_2': 0.5530381784969213}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:05,734] Trial 1215 finished with value: 0.9498379640200105 and parameters: {'weight_lgbm_class_0': 0.10607281641720512, 'weight_lgbm_class_1': 0.9927317814209509, 'weight_lgbm_class_2': 0.4256074016987636, 'weight_xgb_class_0': 0.000507630474656337, 'weight_xgb_class_1': 0.6904203625394598, 'weight_xgb_class_2': 0.5285883175729503}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:05,805] Trial 1216 finished with value: 0.9497336065046024 and parameters: {'weight_lgbm_class_0': 0.11150207420540018, 'weight_lgbm_class_1': 0.9985385865658037, 'weight_lgbm_class_2': 0.42877921663705054, 'weight_xgb_class_0': 0.0005672876805917597, 'weight_xgb_class_1': 0.688302232864757, 'weight_xgb_class_2': 0.5214545600993051}. Best is trial 1206 with value: 0.9498581274668642.

[I 2026-07-05 15:32:05,832] Trial 1217 finished with value: 0.9497424845560692 and parameters: {'weight_lgbm_class_0': 0.1067104452084311, 'weight_lgbm_class_1': 0.998315353517127, 'weight_lgbm_class_2': 0.41221941399045986, 'weight_xgb_class_0': 0.00045711030813452846, 'weight_xgb_class_1': 0.7002408310385226, 'weight_xgb_class_2': 0.5023648138527627}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:05,860] Trial 1218 finished with value: 0.9494922741458488 and parameters: {'weight_lgbm_class_0': 0.11338019034706207, 'weight_lgbm_class_1': 0.9933737646336991, 'weight_lgbm_class_2': 0.4276647870593462, 'weight_xgb_class_0': 0.013649101289514198, 'weight_xgb_class_1': 0.6870823366097043, 'weight_xgb_class_2': 0.5583918281876826}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:05,891] Trial 1219 finished with value: 0.9498281261458722 and parameters: {'weight_lgbm_class_0': 0.09554643242007838, 'weight_lgbm_class_1': 0.9975777865284097, 'weight_lgbm_class_2': 0.4287400630452961, 'weight_xgb_class_0': 0.001981710996076807, 'weight_xgb_class_1': 0.6820545155946741, 'weight_xgb_class_2': 0.5251950836643169}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:05,928] Trial 1220 finished with value: 0.9496904984617238 and parameters: {'weight_lgbm_class_0': 0.11519261668657851, 'weight_lgbm_class_1': 0.9936354706068223, 'weight_lgbm_class_2': 0.4271442025736142, 'weight_xgb_class_0': 0.0003027191939250981, 'weight_xgb_class_1': 0.6866840208501691, 'weight_xgb_class_2': 0.5339078643600109}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:05,972] Trial 1221 finished with value: 0.9497349442419954 and parameters: {'weight_lgbm_class_0': 0.11138260046071605, 'weight_lgbm_class_1': 0.9908004432380644, 'weight_lgbm_class_2': 0.42323106562564994, 'weight_xgb_class_0': 0.0008486780479854579, 'weight_xgb_class_1': 0.6897333910697782, 'weight_xgb_class_2': 0.5284779449186335}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  61%|███████████████████████████████████████████████████████████████████████████████▉                                                  | 1229/2000 [00:34<00:27, 27.72it/s]

[I 2026-07-05 15:32:06,043] Trial 1222 finished with value: 0.9494098307305917 and parameters: {'weight_lgbm_class_0': 0.11580565987957131, 'weight_lgbm_class_1': 0.999212535211884, 'weight_lgbm_class_2': 0.42816033831585365, 'weight_xgb_class_0': 0.003582911151971877, 'weight_xgb_class_1': 0.6850172884027828, 'weight_xgb_class_2': 0.4842493250221578}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:06,072] Trial 1223 finished with value: 0.9251935271681074 and parameters: {'weight_lgbm_class_0': 0.11463135275681635, 'weight_lgbm_class_1': 0.9921104766125595, 'weight_lgbm_class_2': 0.42773456874931204, 'weight_xgb_class_0': 0.41632982510263433, 'weight_xgb_class_1': 0.6888696695357472, 'weight_xgb_class_2': 0.5114840112475263}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:06,090] Trial 1224 finished with value: 0.949231970305655 and parameters: {'weight_lgbm_class_0': 0.12269552421436088, 'weight_lgbm_class_1': 0.9997005226069792, 'weight_lgbm_class_2': 0.4250600062009433, 'weight_xgb_class_0': 0.003344254880305197, 'weight_xgb_class_1': 0.6827675164457243, 'weight_xgb_class_2': 0.480299100600536}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:06,134] Trial 1225 finished with value: 0.9495446751632924 and parameters: {'weight_lgbm_class_0': 0.1158970509700818, 'weight_lgbm_class_1': 0.9949042600879018, 'weight_lgbm_class_2': 0.4186865469162425, 'weight_xgb_class_0': 0.0021346396685545353, 'weight_xgb_class_1': 0.6654169083612463, 'weight_xgb_class_2': 0.5200673494973957}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:06,163] Trial 1226 finished with value: 0.9489285956983234 and parameters: {'weight_lgbm_class_0': 0.14370061051318123, 'weight_lgbm_class_1': 0.9913432600781054, 'weight_lgbm_class_2': 0.4302981901633812, 'weight_xgb_class_0': 0.0019977952576012876, 'weight_xgb_class_1': 0.6493995991226259, 'weight_xgb_class_2': 0.5176503053577041}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:06,215] Trial 1227 finished with value: 0.949787433262382 and parameters: {'weight_lgbm_class_0': 0.10608927227881532, 'weight_lgbm_class_1': 0.9972941426913173, 'weight_lgbm_class_2': 0.45998142177014795, 'weight_xgb_class_0': 0.0017863986447722545, 'weight_xgb_class_1': 0.6594447604037724, 'weight_xgb_class_2': 0.5453356242839855}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:06,221] Trial 1228 finished with value: 0.9491304712432683 and parameters: {'weight_lgbm_class_0': 0.13715223678396485, 'weight_lgbm_class_1': 0.9992168488287104, 'weight_lgbm_class_2': 0.43913354934381105, 'weight_xgb_class_0': 4.2260634344374465e-05, 'weight_xgb_class_1': 0.6536153329304606, 'weight_xgb_class_2': 0.5176166529460431}. Best is trial 1206 with value: 0.9498581274668642.

[I 2026-07-05 15:32:06,309] Trial 1229 finished with value: 0.9492292817828806 and parameters: {'weight_lgbm_class_0': 0.13029045155052343, 'weight_lgbm_class_1': 0.9957156751084594, 'weight_lgbm_class_2': 0.4387929370700054, 'weight_xgb_class_0': 0.0013867357639954347, 'weight_xgb_class_1': 0.6579598176724403, 'weight_xgb_class_2': 0.5031230499421607}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:06,334] Trial 1230 finished with value: 0.9492088874114172 and parameters: {'weight_lgbm_class_0': 0.12114712617407743, 'weight_lgbm_class_1': 0.9993583182939343, 'weight_lgbm_class_2': 0.44015223876746373, 'weight_xgb_class_0': 0.008410476870834835, 'weight_xgb_class_1': 0.6506489059527768, 'weight_xgb_class_2': 0.49695597315128287}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:06,338] Trial 1231 finished with value: 0.9487496492212634 and parameters: {'weight_lgbm_class_0': 0.14675561921876012, 'weight_lgbm_class_1': 0.9921606244940029, 'weight_lgbm_class_2': 0.4373825282848014, 'weight_xgb_class_0': 0.0022963396762796656, 'weight_xgb_class_1': 0.6641188732618956, 'weight_xgb_class_2': 0.4853552107528018}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:06,358] Trial 1232 finished with value: 0.9491260491218592 and parameters: {'weight_lgbm_class_0': 0.12708221684252918, 'weight_lgbm_class_1': 0.9943748959606153, 'weight_lgbm_class_2': 0.4264101200238907, 'weight_xgb_class_0': 0.0038029802566334203, 'weight_xgb_class_1': 0.6682876911595376, 'weight_xgb_class_2': 0.49177264485275146}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:06,451] Trial 1233 finished with value: 0.9491372909887322 and parameters: {'weight_lgbm_class_0': 0.13433470078199927, 'weight_lgbm_class_1': 0.9910855979884576, 'weight_lgbm_class_2': 0.4398666699829097, 'weight_xgb_class_0': 0.001671388994224871, 'weight_xgb_class_1': 0.651004769678838, 'weight_xgb_class_2': 0.5146905690517378}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:06,496] Trial 1234 finished with value: 0.9489543800272154 and parameters: {'weight_lgbm_class_0': 0.14344942502715724, 'weight_lgbm_class_1': 0.9999859829322149, 'weight_lgbm_class_2': 0.43843537586982684, 'weight_xgb_class_0': 0.002835943647067287, 'weight_xgb_class_1': 0.6565866089377191, 'weight_xgb_class_2': 0.5151426985834494}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  62%|████████████████████████████████████████████████████████████████████████████████▌                                                 | 1240/2000 [00:35<00:27, 27.60it/s]

[I 2026-07-05 15:32:06,503] Trial 1235 finished with value: 0.948944943658026 and parameters: {'weight_lgbm_class_0': 0.1406954058901071, 'weight_lgbm_class_1': 0.9993125965408166, 'weight_lgbm_class_2': 0.44489805317485437, 'weight_xgb_class_0': 0.004158666598994523, 'weight_xgb_class_1': 0.6635709243134373, 'weight_xgb_class_2': 0.5128566754626117}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:06,576] Trial 1236 finished with value: 0.9496013280301964 and parameters: {'weight_lgbm_class_0': 0.11671666552512086, 'weight_lgbm_class_1': 0.9950864211047503, 'weight_lgbm_class_2': 0.42900530898480826, 'weight_xgb_class_0': 0.0016119138246111606, 'weight_xgb_class_1': 0.6535906483577414, 'weight_xgb_class_2': 0.5442036243403702}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:06,581] Trial 1238 finished with value: 0.9491136769624862 and parameters: {'weight_lgbm_class_0': 0.14067934338575994, 'weight_lgbm_class_1': 0.9969876680131743, 'weight_lgbm_class_2': 0.4374756907169365, 'weight_xgb_class_0': 0.0008657265734087795, 'weight_xgb_class_1': 0.65671629780514, 'weight_xgb_class_2': 0.5472566295442587}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:06,593] Trial 1237 finished with value: 0.9489677914153868 and parameters: {'weight_lgbm_class_0': 0.13710606629659466, 'weight_lgbm_class_1': 0.9981136764328439, 'weight_lgbm_class_2': 0.4381697243566042, 'weight_xgb_class_0': 0.007110618267785144, 'weight_xgb_class_1': 0.6747752845190141, 'weight_xgb_class_2': 0.4970668748675626}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:06,647] Trial 1239 finished with value: 0.9490063782520931 and parameters: {'weight_lgbm_class_0': 0.13716018401374877, 'weight_lgbm_class_1': 0.9991096823489019, 'weight_lgbm_class_2': 0.43621713109515, 'weight_xgb_class_0': 0.002037207141671056, 'weight_xgb_class_1': 0.6525950563117036, 'weight_xgb_class_2': 0.4985125614985508}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:06,670] Trial 1240 finished with value: 0.9491433338279892 and parameters: {'weight_lgbm_class_0': 0.133470347915964, 'weight_lgbm_class_1': 0.998549309472547, 'weight_lgbm_class_2': 0.45069159133518394, 'weight_xgb_class_0': 0.001388354248789035, 'weight_xgb_class_1': 0.6812648091664942, 'weight_xgb_class_2': 0.5024897432233626}. Best is trial 1206 with value: 0.9498581274668642.

[I 2026-07-05 15:32:06,750] Trial 1241 finished with value: 0.9496074690367603 and parameters: {'weight_lgbm_class_0': 0.11734809775152899, 'weight_lgbm_class_1': 0.9983377365996755, 'weight_lgbm_class_2': 0.43496913027531514, 'weight_xgb_class_0': 0.0030113356947004365, 'weight_xgb_class_1': 0.67590793561858, 'weight_xgb_class_2': 0.5495208428436844}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:06,775] Trial 1242 finished with value: 0.949032034817297 and parameters: {'weight_lgbm_class_0': 0.14438506017096978, 'weight_lgbm_class_1': 0.9836042183380554, 'weight_lgbm_class_2': 0.4374899695386475, 'weight_xgb_class_0': 0.000190384160962383, 'weight_xgb_class_1': 0.6769398025285638, 'weight_xgb_class_2': 0.5467727463350103}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:06,858] Trial 1243 finished with value: 0.9491373726076465 and parameters: {'weight_lgbm_class_0': 0.13801768725079272, 'weight_lgbm_class_1': 0.979328023294823, 'weight_lgbm_class_2': 0.4381343685634663, 'weight_xgb_class_0': 0.004575731547541118, 'weight_xgb_class_1': 0.6757677802919798, 'weight_xgb_class_2': 0.5593047227299691}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:06,864] Trial 1244 finished with value: 0.9492773760731658 and parameters: {'weight_lgbm_class_0': 0.13313257179172908, 'weight_lgbm_class_1': 0.978015240591161, 'weight_lgbm_class_2': 0.4373927778903886, 'weight_xgb_class_0': 0.000938486032026075, 'weight_xgb_class_1': 0.6754698913747449, 'weight_xgb_class_2': 0.5500480391410524}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:06,888] Trial 1245 finished with value: 0.9491589023680215 and parameters: {'weight_lgbm_class_0': 0.12430618603106366, 'weight_lgbm_class_1': 0.9749925265040987, 'weight_lgbm_class_2': 0.41951988754206787, 'weight_xgb_class_0': 0.013866585810541683, 'weight_xgb_class_1': 0.6769910476358402, 'weight_xgb_class_2': 0.5500998268317788}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  63%|█████████████████████████████████████████████████████████████████████████████████▍                                                | 1253/2000 [00:35<00:25, 29.35it/s]

[I 2026-07-05 15:32:06,957] Trial 1246 finished with value: 0.949614505877498 and parameters: {'weight_lgbm_class_0': 0.11543738598684186, 'weight_lgbm_class_1': 0.9733416885742381, 'weight_lgbm_class_2': 0.41976264887628917, 'weight_xgb_class_0': 0.0028602896340695905, 'weight_xgb_class_1': 0.6893415927870797, 'weight_xgb_class_2': 0.5472453932674628}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:06,977] Trial 1247 finished with value: 0.9497191984986904 and parameters: {'weight_lgbm_class_0': 0.11757027974598169, 'weight_lgbm_class_1': 0.9770668746404063, 'weight_lgbm_class_2': 0.46761443418105963, 'weight_xgb_class_0': 0.0006117559641495991, 'weight_xgb_class_1': 0.6809983297424859, 'weight_xgb_class_2': 0.5443341475678832}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:07,034] Trial 1249 finished with value: 0.9498252040204571 and parameters: {'weight_lgbm_class_0': 0.11115357541858087, 'weight_lgbm_class_1': 0.9751779004710388, 'weight_lgbm_class_2': 0.41579043678619776, 'weight_xgb_class_0': 0.0009639462835375567, 'weight_xgb_class_1': 0.6865539895765194, 'weight_xgb_class_2': 0.5540147930077025}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:07,035] Trial 1248 finished with value: 0.9498113928261409 and parameters: {'weight_lgbm_class_0': 0.1071810449990292, 'weight_lgbm_class_1': 0.9699008189777459, 'weight_lgbm_class_2': 0.46469861652675276, 'weight_xgb_class_0': 0.0010171847590480661, 'weight_xgb_class_1': 0.6763217402950354, 'weight_xgb_class_2': 0.5493361766203873}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:07,061] Trial 1250 finished with value: 0.9492125039476945 and parameters: {'weight_lgbm_class_0': 0.11365246699443379, 'weight_lgbm_class_1': 0.9754067121548938, 'weight_lgbm_class_2': 0.4143002091589099, 'weight_xgb_class_0': 0.01912792070667358, 'weight_xgb_class_1': 0.682982309317083, 'weight_xgb_class_2': 0.5385672493212277}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:07,072] Trial 1251 finished with value: 0.9496019149240474 and parameters: {'weight_lgbm_class_0': 0.10740967878095457, 'weight_lgbm_class_1': 0.9731803150555657, 'weight_lgbm_class_2': 0.46632625742214184, 'weight_xgb_class_0': 0.017285637181252075, 'weight_xgb_class_1': 0.6811243018224863, 'weight_xgb_class_2': 0.5505463989801879}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:07,114] Trial 1252 finished with value: 0.9495740975704695 and parameters: {'weight_lgbm_class_0': 0.10942919313634646, 'weight_lgbm_class_1': 0.9747496397842846, 'weight_lgbm_class_2': 0.4648152936426599, 'weight_xgb_class_0': 0.016390761541290044, 'weight_xgb_class_1': 0.683445383456038, 'weight_xgb_class_2': 0.5523618827779454}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:07,130] Trial 1253 finished with value: 0.9494641988875402 and parameters: {'weight_lgbm_class_0': 0.10713041967174315, 'weight_lgbm_class_1': 0.9721379402765264, 'weight_lgbm_class_2': 0.4199816663424073, 'weight_xgb_class_0': 0.016806839073820856, 'weight_xgb_class_1': 0.6911078624521448, 'weight_xgb_class_2': 0.5404396784372851}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  63%|█████████████████████████████████████████████████████████████████████████████████▋                                                | 1257/2000 [00:35<00:28, 26.08it/s]

[I 2026-07-05 15:32:07,169] Trial 1254 finished with value: 0.9494429478953528 and parameters: {'weight_lgbm_class_0': 0.10602232590037582, 'weight_lgbm_class_1': 0.9726173518922496, 'weight_lgbm_class_2': 0.4136061102801057, 'weight_xgb_class_0': 0.019168871462652195, 'weight_xgb_class_1': 0.6900660147874934, 'weight_xgb_class_2': 0.5411051919673532}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:07,282] Trial 1255 finished with value: 0.9498281944084082 and parameters: {'weight_lgbm_class_0': 0.10022603431595821, 'weight_lgbm_class_1': 0.9716182494299936, 'weight_lgbm_class_2': 0.4670214166498741, 'weight_xgb_class_0': 0.000528789620779721, 'weight_xgb_class_1': 0.6937416486311396, 'weight_xgb_class_2': 0.5646076903165669}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:07,286] Trial 1256 finished with value: 0.9494820792204458 and parameters: {'weight_lgbm_class_0': 0.10785782975543329, 'weight_lgbm_class_1': 0.9751427376540981, 'weight_lgbm_class_2': 0.4096983677959168, 'weight_xgb_class_0': 0.01893342666116438, 'weight_xgb_class_1': 0.6905013112189045, 'weight_xgb_class_2': 0.5669571512109356}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:07,317] Trial 1257 finished with value: 0.9493300990407564 and parameters: {'weight_lgbm_class_0': 0.10618149757424561, 'weight_lgbm_class_1': 0.37413301696576823, 'weight_lgbm_class_2': 0.4676485355234491, 'weight_xgb_class_0': 0.02134097222123873, 'weight_xgb_class_1': 0.6893349778677241, 'weight_xgb_class_2': 0.5670312924169075}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  63%|██████████████████████████████████████████████████████████████████████████████████▏                                               | 1265/2000 [00:36<00:24, 29.60it/s]

[I 2026-07-05 15:32:07,380] Trial 1259 finished with value: 0.9494891975773009 and parameters: {'weight_lgbm_class_0': 0.10417073200291034, 'weight_lgbm_class_1': 0.9720837721501165, 'weight_lgbm_class_2': 0.40898744932175574, 'weight_xgb_class_0': 0.021417687649254568, 'weight_xgb_class_1': 0.6951703665511486, 'weight_xgb_class_2': 0.5671438930453309}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:07,394] Trial 1258 finished with value: 0.9495897381123471 and parameters: {'weight_lgbm_class_0': 0.10434570181754473, 'weight_lgbm_class_1': 0.9727264244041847, 'weight_lgbm_class_2': 0.4132240753471955, 'weight_xgb_class_0': 0.017058036120108637, 'weight_xgb_class_1': 0.6944543815750424, 'weight_xgb_class_2': 0.5712864895610236}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:07,435] Trial 1261 finished with value: 0.9493886697485413 and parameters: {'weight_lgbm_class_0': 0.11119499106964081, 'weight_lgbm_class_1': 0.9724519826537338, 'weight_lgbm_class_2': 0.4742691330500095, 'weight_xgb_class_0': 0.019949845323114376, 'weight_xgb_class_1': 0.6304965668943505, 'weight_xgb_class_2': 0.5357198084131111}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:07,444] Trial 1260 finished with value: 0.9484267933035859 and parameters: {'weight_lgbm_class_0': 0.15505430476434115, 'weight_lgbm_class_1': 0.9724859630309536, 'weight_lgbm_class_2': 0.4689683913957952, 'weight_xgb_class_0': 0.025757243175717218, 'weight_xgb_class_1': 0.6316616931968678, 'weight_xgb_class_2': 0.569716282617002}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:07,474] Trial 1262 finished with value: 0.9485446636692833 and parameters: {'weight_lgbm_class_0': 0.15395975104825135, 'weight_lgbm_class_1': 0.9692754617842074, 'weight_lgbm_class_2': 0.4773015202173439, 'weight_xgb_class_0': 0.019449612040615183, 'weight_xgb_class_1': 0.6310385969455163, 'weight_xgb_class_2': 0.5698759590248429}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:07,517] Trial 1265 finished with value: 0.9484363944038142 and parameters: {'weight_lgbm_class_0': 0.16556249456944816, 'weight_lgbm_class_1': 0.9698268259827751, 'weight_lgbm_class_2': 0.4910256844502891, 'weight_xgb_class_0': 0.01743276366004343, 'weight_xgb_class_1': 0.605229887040354, 'weight_xgb_class_2': 0.5653163318686064}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:07,523] Trial 1264 finished with value: 0.9484705185152476 and parameters: {'weight_lgbm_class_0': 0.15623890983766284, 'weight_lgbm_class_1': 0.9709558306990387, 'weight_lgbm_class_2': 0.4778160291065181, 'weight_xgb_class_0': 0.023138309329041193, 'weight_xgb_class_1': 0.6034111787693502, 'weight_xgb_class_2': 0.5730106108831631}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:07,549] Trial 1263 finished with value: 0.9473052095132051 and parameters: {'weight_lgbm_class_0': 0.17417296567122106, 'weight_lgbm_class_1': 0.970483221704887, 'weight_lgbm_class_2': 0.4141123947216621, 'weight_xgb_class_0': 0.01957517040804059, 'weight_xgb_class_1': 0.6341189194395167, 'weight_xgb_class_2': 0.4707981112738295}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  64%|██████████████████████████████████████████████████████████████████████████████████▌                                               | 1270/2000 [00:36<00:27, 26.74it/s]

[I 2026-07-05 15:32:07,591] Trial 1266 finished with value: 0.9486052762326224 and parameters: {'weight_lgbm_class_0': 0.1632896051060509, 'weight_lgbm_class_1': 0.9687879362202104, 'weight_lgbm_class_2': 0.4791313411520438, 'weight_xgb_class_0': 0.002371121663561751, 'weight_xgb_class_1': 0.6205369980386473, 'weight_xgb_class_2': 0.5280311839453956}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:07,709] Trial 1268 finished with value: 0.9488699353221035 and parameters: {'weight_lgbm_class_0': 0.14149688304138977, 'weight_lgbm_class_1': 0.9766399919768298, 'weight_lgbm_class_2': 0.48416008254032905, 'weight_xgb_class_0': 0.018636610986098846, 'weight_xgb_class_1': 0.61701641546418, 'weight_xgb_class_2': 0.5635686593887934}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:07,740] Trial 1267 finished with value: 0.9495744210186796 and parameters: {'weight_lgbm_class_0': 0.12481196318538497, 'weight_lgbm_class_1': 0.9723948048276745, 'weight_lgbm_class_2': 0.49418930685963225, 'weight_xgb_class_0': 0.0029428412766822204, 'weight_xgb_class_1': 0.6454784206405584, 'weight_xgb_class_2': 0.5707964984378724}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:07,772] Trial 1269 finished with value: 0.9488485531686203 and parameters: {'weight_lgbm_class_0': 0.14717952973985, 'weight_lgbm_class_1': 0.9999123441694283, 'weight_lgbm_class_2': 0.4750167392480477, 'weight_xgb_class_0': 0.013862247790753322, 'weight_xgb_class_1': 0.6013262708582803, 'weight_xgb_class_2': 0.5725005815675112}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:07,817] Trial 1270 finished with value: 0.9489720299084689 and parameters: {'weight_lgbm_class_0': 0.14516624082581073, 'weight_lgbm_class_1': 0.9807168008452628, 'weight_lgbm_class_2': 0.4683503264477509, 'weight_xgb_class_0': 0.0006940112196764053, 'weight_xgb_class_1': 0.645953255449265, 'weight_xgb_class_2': 0.5260571488833926}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  64%|███████████████████████████████████████████████████████████████████████████████████                                               | 1277/2000 [00:36<00:24, 29.19it/s]

[I 2026-07-05 15:32:07,835] Trial 1271 finished with value: 0.9485722804759801 and parameters: {'weight_lgbm_class_0': 0.177375496964081, 'weight_lgbm_class_1': 0.9999926309380223, 'weight_lgbm_class_2': 0.510017267074343, 'weight_xgb_class_0': 0.0005256280055139492, 'weight_xgb_class_1': 0.6427919206482833, 'weight_xgb_class_2': 0.5763672869620085}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:07,880] Trial 1272 finished with value: 0.9483694373339208 and parameters: {'weight_lgbm_class_0': 0.1719621885023076, 'weight_lgbm_class_1': 0.9989408157720461, 'weight_lgbm_class_2': 0.4494284228523455, 'weight_xgb_class_0': 0.004000014643388096, 'weight_xgb_class_1': 0.6363732424789184, 'weight_xgb_class_2': 0.5289815744171837}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:07,902] Trial 1274 finished with value: 0.9491137750269965 and parameters: {'weight_lgbm_class_0': 0.13681925061820155, 'weight_lgbm_class_1': 0.9983022160312889, 'weight_lgbm_class_2': 0.46391972696454803, 'weight_xgb_class_0': 0.004488180264211854, 'weight_xgb_class_1': 0.6455565488480712, 'weight_xgb_class_2': 0.5241226928550924}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:07,908] Trial 1273 finished with value: 0.949501628348829 and parameters: {'weight_lgbm_class_0': 0.1277888763735441, 'weight_lgbm_class_1': 0.9995974225663216, 'weight_lgbm_class_2': 0.5251710244136999, 'weight_xgb_class_0': 0.00031046401357993426, 'weight_xgb_class_1': 0.6111943290084593, 'weight_xgb_class_2': 0.519409911186295}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:07,974] Trial 1276 finished with value: 0.9495605351777986 and parameters: {'weight_lgbm_class_0': 0.12434545189767676, 'weight_lgbm_class_1': 0.9818241284044343, 'weight_lgbm_class_2': 0.5024850725659076, 'weight_xgb_class_0': 0.0019925486508178512, 'weight_xgb_class_1': 0.66044438413817, 'weight_xgb_class_2': 0.52407202945077}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:07,989] Trial 1275 finished with value: 0.9493738208596628 and parameters: {'weight_lgbm_class_0': 0.1307192639207332, 'weight_lgbm_class_1': 0.9811035538829329, 'weight_lgbm_class_2': 0.5065131280270786, 'weight_xgb_class_0': 0.0031038208034294386, 'weight_xgb_class_1': 0.6520539752885328, 'weight_xgb_class_2': 0.5256815646930819}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:08,010] Trial 1277 finished with value: 0.9493419070789847 and parameters: {'weight_lgbm_class_0': 0.12622647811257165, 'weight_lgbm_class_1': 0.9998292659609818, 'weight_lgbm_class_2': 0.4536766858571725, 'weight_xgb_class_0': 0.003455091828411617, 'weight_xgb_class_1': 0.6437012296569776, 'weight_xgb_class_2': 0.5222327926793906}. Best is trial 1206 with value: 0.9498581274668642.

[I 2026-07-05 15:32:08,059] Trial 1278 finished with value: 0.949653595372881 and parameters: {'weight_lgbm_class_0': 0.12312290547768975, 'weight_lgbm_class_1': 0.9829355925133599, 'weight_lgbm_class_2': 0.5246198311422577, 'weight_xgb_class_0': 0.000897467695071023, 'weight_xgb_class_1': 0.6664352843562819, 'weight_xgb_class_2': 0.5167627865749158}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:08,120] Trial 1279 finished with value: 0.9495070783831641 and parameters: {'weight_lgbm_class_0': 0.12678436365504564, 'weight_lgbm_class_1': 0.9994236175943773, 'weight_lgbm_class_2': 0.5252018404881437, 'weight_xgb_class_0': 0.0015194480267995622, 'weight_xgb_class_1': 0.6489545395681913, 'weight_xgb_class_2': 0.5157308209717951}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:08,200] Trial 1280 finished with value: 0.9494629223785626 and parameters: {'weight_lgbm_class_0': 0.12375511545470286, 'weight_lgbm_class_1': 0.9830699598386271, 'weight_lgbm_class_2': 0.5242050729321719, 'weight_xgb_class_0': 0.0060793596361117565, 'weight_xgb_class_1': 0.6526864492687146, 'weight_xgb_class_2': 0.525909867888887}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:08,238] Trial 1282 finished with value: 0.9493902680069249 and parameters: {'weight_lgbm_class_0': 0.1281443894334567, 'weight_lgbm_class_1': 0.9996182338537881, 'weight_lgbm_class_2': 0.4610260351667882, 'weight_xgb_class_0': 0.0008799174529230194, 'weight_xgb_class_1': 0.6612886405279482, 'weight_xgb_class_2': 0.5245048847822922}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  64%|███████████████████████████████████████████████████████████████████████████████████▊                                              | 1290/2000 [00:37<00:24, 29.52it/s]

[I 2026-07-05 15:32:08,259] Trial 1281 finished with value: 0.9489932307825204 and parameters: {'weight_lgbm_class_0': 0.1286664474707498, 'weight_lgbm_class_1': 0.9999047989629705, 'weight_lgbm_class_2': 0.44976625455419145, 'weight_xgb_class_0': 0.016210003688389946, 'weight_xgb_class_1': 0.661158790704636, 'weight_xgb_class_2': 0.5265021367816166}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:08,276] Trial 1283 finished with value: 0.9494476806558888 and parameters: {'weight_lgbm_class_0': 0.12395554325641737, 'weight_lgbm_class_1': 0.9985668988567244, 'weight_lgbm_class_2': 0.46125213749676747, 'weight_xgb_class_0': 0.003393989122161594, 'weight_xgb_class_1': 0.6607522053626448, 'weight_xgb_class_2': 0.5262098295835532}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:08,284] Trial 1284 finished with value: 0.949298656764531 and parameters: {'weight_lgbm_class_0': 0.12470562278277478, 'weight_lgbm_class_1': 0.9818499354814965, 'weight_lgbm_class_2': 0.4601824356486683, 'weight_xgb_class_0': 0.0019370715851042871, 'weight_xgb_class_1': 0.667735500530457, 'weight_xgb_class_2': 0.4736909789307614}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:08,331] Trial 1285 finished with value: 0.9495987088930075 and parameters: {'weight_lgbm_class_0': 0.12426297011512598, 'weight_lgbm_class_1': 0.9615607348614496, 'weight_lgbm_class_2': 0.45144952040627423, 'weight_xgb_class_0': 0.0009094418966193729, 'weight_xgb_class_1': 0.66532885785488, 'weight_xgb_class_2': 0.5827356848416833}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:08,356] Trial 1286 finished with value: 0.9495456774531991 and parameters: {'weight_lgbm_class_0': 0.12564889881482053, 'weight_lgbm_class_1': 0.9611033852716957, 'weight_lgbm_class_2': 0.45495920541804025, 'weight_xgb_class_0': 0.0009050731297435607, 'weight_xgb_class_1': 0.6647615354372246, 'weight_xgb_class_2': 0.5873077282516652}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:08,382] Trial 1288 finished with value: 0.9493024434699606 and parameters: {'weight_lgbm_class_0': 0.09748412702205587, 'weight_lgbm_class_1': 0.9596807782075101, 'weight_lgbm_class_2': 0.4506205001724005, 'weight_xgb_class_0': 0.028138200717682044, 'weight_xgb_class_1': 0.7122443891180452, 'weight_xgb_class_2': 0.4684572869664693}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:08,395] Trial 1287 finished with value: 0.9413835865916802 and parameters: {'weight_lgbm_class_0': 0.10278020327787084, 'weight_lgbm_class_1': 0.9565622092290204, 'weight_lgbm_class_2': 0.4369866681486039, 'weight_xgb_class_0': 0.23833556865031896, 'weight_xgb_class_1': 0.7095726360495569, 'weight_xgb_class_2': 0.5828726777794936}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:08,422] Trial 1289 finished with value: 0.9495402555220348 and parameters: {'weight_lgbm_class_0': 0.10085211940508727, 'weight_lgbm_class_1': 0.9589417047289426, 'weight_lgbm_class_2': 0.45920407851662937, 'weight_xgb_class_0': 0.029656340235135494, 'weight_xgb_class_1': 0.7113577692269987, 'weight_xgb_class_2': 0.5894099542327834}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:08,435] Trial 1290 finished with value: 0.9498189872650246 and parameters: {'weight_lgbm_class_0': 0.0993450047516669, 'weight_lgbm_class_1': 0.9604578398298402, 'weight_lgbm_class_2': 0.4408492039927108, 'weight_xgb_class_0': 0.00037500602839252335, 'weight_xgb_class_1': 0.7120041308348611, 'weight_xgb_class_2': 0.5869870508548891}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  65%|████████████████████████████████████████████████████████████████████████████████████▏                                             | 1295/2000 [00:37<00:24, 28.56it/s]

[I 2026-07-05 15:32:08,547] Trial 1291 finished with value: 0.9496415861140729 and parameters: {'weight_lgbm_class_0': 0.09658434808423183, 'weight_lgbm_class_1': 0.9600498191171543, 'weight_lgbm_class_2': 0.4534538788497756, 'weight_xgb_class_0': 0.028372754367463088, 'weight_xgb_class_1': 0.7085158132542387, 'weight_xgb_class_2': 0.5846456018253192}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:08,581] Trial 1292 finished with value: 0.9492752520180904 and parameters: {'weight_lgbm_class_0': 0.09853891563769951, 'weight_lgbm_class_1': 0.9603215322543397, 'weight_lgbm_class_2': 0.45409934221340037, 'weight_xgb_class_0': 0.02836763550781476, 'weight_xgb_class_1': 0.7090099855736197, 'weight_xgb_class_2': 0.4667823716385619}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:08,630] Trial 1293 finished with value: 0.9494698969706321 and parameters: {'weight_lgbm_class_0': 0.10084527839943204, 'weight_lgbm_class_1': 0.9603087781579478, 'weight_lgbm_class_2': 0.43491378865433505, 'weight_xgb_class_0': 0.02927359204567857, 'weight_xgb_class_1': 0.7149152640317703, 'weight_xgb_class_2': 0.5841179829421097}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:08,696] Trial 1295 finished with value: 0.9494800417778994 and parameters: {'weight_lgbm_class_0': 0.10007443917833764, 'weight_lgbm_class_1': 0.9624770035001387, 'weight_lgbm_class_2': 0.4282159194316039, 'weight_xgb_class_0': 0.027519516425446488, 'weight_xgb_class_1': 0.7112313302042892, 'weight_xgb_class_2': 0.5543968138558502}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:08,713] Trial 1294 finished with value: 0.949592483075515 and parameters: {'weight_lgbm_class_0': 0.09834760398149767, 'weight_lgbm_class_1': 0.9616211109536079, 'weight_lgbm_class_2': 0.43916177551901053, 'weight_xgb_class_0': 0.02817143270596194, 'weight_xgb_class_1': 0.7129431433557862, 'weight_xgb_class_2': 0.5815710837902487}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  65%|████████████████████████████████████████████████████████████████████████████████████▋                                             | 1303/2000 [00:37<00:24, 28.31it/s]

[I 2026-07-05 15:32:08,752] Trial 1296 finished with value: 0.9494087047531559 and parameters: {'weight_lgbm_class_0': 0.09773102148127921, 'weight_lgbm_class_1': 0.9600072332114922, 'weight_lgbm_class_2': 0.4286874013411771, 'weight_xgb_class_0': 0.03175109003792303, 'weight_xgb_class_1': 0.7075941414932138, 'weight_xgb_class_2': 0.5566937867623233}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:08,757] Trial 1297 finished with value: 0.9493175342909316 and parameters: {'weight_lgbm_class_0': 0.09919285091369288, 'weight_lgbm_class_1': 0.9605270037393663, 'weight_lgbm_class_2': 0.4312481611553852, 'weight_xgb_class_0': 0.03242876531083963, 'weight_xgb_class_1': 0.703239185111334, 'weight_xgb_class_2': 0.554146250884967}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:08,806] Trial 1298 finished with value: 0.9494980608819755 and parameters: {'weight_lgbm_class_0': 0.09653687177233292, 'weight_lgbm_class_1': 0.9604718682374983, 'weight_lgbm_class_2': 0.4250035708107694, 'weight_xgb_class_0': 0.030161882452212282, 'weight_xgb_class_1': 0.7054371932379558, 'weight_xgb_class_2': 0.5589920118601891}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:08,849] Trial 1301 finished with value: 0.94943395682699 and parameters: {'weight_lgbm_class_0': 0.09843598294089459, 'weight_lgbm_class_1': 0.9621997984365929, 'weight_lgbm_class_2': 0.4293426472959207, 'weight_xgb_class_0': 0.03014930257323798, 'weight_xgb_class_1': 0.6982988974981518, 'weight_xgb_class_2': 0.5649066842927061}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:08,851] Trial 1300 finished with value: 0.9493034363483918 and parameters: {'weight_lgbm_class_0': 0.10550116970376762, 'weight_lgbm_class_1': 0.9610280168796201, 'weight_lgbm_class_2': 0.42664060787515107, 'weight_xgb_class_0': 0.025705531829408216, 'weight_xgb_class_1': 0.6987688153055844, 'weight_xgb_class_2': 0.5539399918237137}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:08,853] Trial 1299 finished with value: 0.9493863000220637 and parameters: {'weight_lgbm_class_0': 0.10065941248952533, 'weight_lgbm_class_1': 0.9636833252109487, 'weight_lgbm_class_2': 0.4237067402013673, 'weight_xgb_class_0': 0.02963235827716736, 'weight_xgb_class_1': 0.70695931380233, 'weight_xgb_class_2': 0.558241948482514}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:08,883] Trial 1302 finished with value: 0.9495089736569319 and parameters: {'weight_lgbm_class_0': 0.09788524707814512, 'weight_lgbm_class_1': 0.9616627692754999, 'weight_lgbm_class_2': 0.4306491210974432, 'weight_xgb_class_0': 0.02662438619169235, 'weight_xgb_class_1': 0.6996318739521383, 'weight_xgb_class_2': 0.5522907821686442}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:08,947] Trial 1303 finished with value: 0.9495087715140436 and parameters: {'weight_lgbm_class_0': 0.09921034076016419, 'weight_lgbm_class_1': 0.9584429612804395, 'weight_lgbm_class_2': 0.43121929841017026, 'weight_xgb_class_0': 0.02663381941054129, 'weight_xgb_class_1': 0.7017668402463632, 'weight_xgb_class_2': 0.5475758976716958}. Best is trial 1206 with value: 0.9498581274668642.

[I 2026-07-05 15:32:08,995] Trial 1304 finished with value: 0.9494986867836829 and parameters: {'weight_lgbm_class_0': 0.1002818492893711, 'weight_lgbm_class_1': 0.9601099256364937, 'weight_lgbm_class_2': 0.4213687210762761, 'weight_xgb_class_0': 0.02618432694675624, 'weight_xgb_class_1': 0.6945040027868117, 'weight_xgb_class_2': 0.5602477169710203}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:09,033] Trial 1305 finished with value: 0.9495379100566216 and parameters: {'weight_lgbm_class_0': 0.0993665370866186, 'weight_lgbm_class_1': 0.9592361412628239, 'weight_lgbm_class_2': 0.4262335543467156, 'weight_xgb_class_0': 0.025951006342167647, 'weight_xgb_class_1': 0.6892246502567828, 'weight_xgb_class_2': 0.5657661373352459}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:09,088] Trial 1306 finished with value: 0.9498553165774898 and parameters: {'weight_lgbm_class_0': 0.10255380666930938, 'weight_lgbm_class_1': 0.9811016340580875, 'weight_lgbm_class_2': 0.4892860171023894, 'weight_xgb_class_0': 0.0008609226427775257, 'weight_xgb_class_1': 0.69109457914476, 'weight_xgb_class_2': 0.5562658012449346}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:09,180] Trial 1307 finished with value: 0.9493818735855905 and parameters: {'weight_lgbm_class_0': 0.10897083433833651, 'weight_lgbm_class_1': 0.9782236206460275, 'weight_lgbm_class_2': 0.41506035549345055, 'weight_xgb_class_0': 0.019050669400088642, 'weight_xgb_class_1': 0.6890011796262968, 'weight_xgb_class_2': 0.5497421040555979}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:09,189] Trial 1308 finished with value: 0.9486236193322036 and parameters: {'weight_lgbm_class_0': 0.1522895553097924, 'weight_lgbm_class_1': 0.9797225008791454, 'weight_lgbm_class_2': 0.49380066530574696, 'weight_xgb_class_0': 0.020580832494497124, 'weight_xgb_class_1': 0.6912423927383744, 'weight_xgb_class_2': 0.5437310927238251}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  66%|█████████████████████████████████████████████████████████████████████████████████████▌                                            | 1316/2000 [00:38<00:23, 28.84it/s]

[I 2026-07-05 15:32:09,206] Trial 1309 finished with value: 0.9485221508864509 and parameters: {'weight_lgbm_class_0': 0.1476121216504639, 'weight_lgbm_class_1': 0.9771788257123559, 'weight_lgbm_class_2': 0.41567951117236607, 'weight_xgb_class_0': 0.02107385794488708, 'weight_xgb_class_1': 0.6899958772672781, 'weight_xgb_class_2': 0.548953194016963}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:09,245] Trial 1310 finished with value: 0.9488401901452675 and parameters: {'weight_lgbm_class_0': 0.16297350552685283, 'weight_lgbm_class_1': 0.9809511964059565, 'weight_lgbm_class_2': 0.4900186175129796, 'weight_xgb_class_0': 0.00010632733886362875, 'weight_xgb_class_1': 0.6865184242714334, 'weight_xgb_class_2': 0.5475526399854596}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:09,281] Trial 1312 finished with value: 0.9492064462588488 and parameters: {'weight_lgbm_class_0': 0.1403369547110652, 'weight_lgbm_class_1': 0.9844523940293602, 'weight_lgbm_class_2': 0.4781481295870248, 'weight_xgb_class_0': 0.0007140454841253448, 'weight_xgb_class_1': 0.6785462152563555, 'weight_xgb_class_2': 0.5430821438276916}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:09,282] Trial 1311 finished with value: 0.9489153892748936 and parameters: {'weight_lgbm_class_0': 0.15091702475968366, 'weight_lgbm_class_1': 0.9822469561007042, 'weight_lgbm_class_2': 0.49376440868112453, 'weight_xgb_class_0': 0.0015221127921492116, 'weight_xgb_class_1': 0.6815035996336114, 'weight_xgb_class_2': 0.49890009625849696}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:09,302] Trial 1314 finished with value: 0.9496194357873072 and parameters: {'weight_lgbm_class_0': 0.11395604163562059, 'weight_lgbm_class_1': 0.9853422771617497, 'weight_lgbm_class_2': 0.4112873982045897, 'weight_xgb_class_0': 0.0018928628389581809, 'weight_xgb_class_1': 0.6825494751302955, 'weight_xgb_class_2': 0.5414279093067034}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:09,320] Trial 1313 finished with value: 0.9489852227081558 and parameters: {'weight_lgbm_class_0': 0.14530950995489855, 'weight_lgbm_class_1': 0.9807859989676628, 'weight_lgbm_class_2': 0.4829351810666432, 'weight_xgb_class_0': 0.002115643289177932, 'weight_xgb_class_1': 0.6754207949100481, 'weight_xgb_class_2': 0.4886243121044733}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:09,358] Trial 1315 finished with value: 0.949279200838299 and parameters: {'weight_lgbm_class_0': 0.11645961085170242, 'weight_lgbm_class_1': 0.9817913942152201, 'weight_lgbm_class_2': 0.4777675114677048, 'weight_xgb_class_0': 0.01702443390518275, 'weight_xgb_class_1': 0.6790306100713908, 'weight_xgb_class_2': 0.5045881416334383}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:09,385] Trial 1316 finished with value: 0.9488912622610393 and parameters: {'weight_lgbm_class_0': 0.15153485361869226, 'weight_lgbm_class_1': 0.9835053239431208, 'weight_lgbm_class_2': 0.47950193155974263, 'weight_xgb_class_0': 0.0015231087417080548, 'weight_xgb_class_1': 0.6833701096360012, 'weight_xgb_class_2': 0.5017328939236624}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  66%|█████████████████████████████████████████████████████████████████████████████████████▊                                            | 1320/2000 [00:38<00:22, 30.51it/s]

[I 2026-07-05 15:32:09,454] Trial 1317 finished with value: 0.9488931778509686 and parameters: {'weight_lgbm_class_0': 0.15329764170750468, 'weight_lgbm_class_1': 0.9825686027211283, 'weight_lgbm_class_2': 0.48893510807632445, 'weight_xgb_class_0': 0.001631567312920775, 'weight_xgb_class_1': 0.6887784001993204, 'weight_xgb_class_2': 0.5402551719198214}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:09,517] Trial 1318 finished with value: 0.9491155893604012 and parameters: {'weight_lgbm_class_0': 0.1431373470207923, 'weight_lgbm_class_1': 0.983364768517676, 'weight_lgbm_class_2': 0.5123457523174678, 'weight_xgb_class_0': 0.0002178549019670288, 'weight_xgb_class_1': 0.6767454209504117, 'weight_xgb_class_2': 0.49044220311022224}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:09,598] Trial 1319 finished with value: 0.9477326980967199 and parameters: {'weight_lgbm_class_0': 0.14065297892302228, 'weight_lgbm_class_1': 0.2191051469000963, 'weight_lgbm_class_2': 0.49015371383379747, 'weight_xgb_class_0': 0.017649661698819014, 'weight_xgb_class_1': 0.6733258544848226, 'weight_xgb_class_2': 0.48989215531418095}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:09,599] Trial 1320 finished with value: 0.9486482542372547 and parameters: {'weight_lgbm_class_0': 0.16025834057369867, 'weight_lgbm_class_1': 0.9823100962611582, 'weight_lgbm_class_2': 0.4954771698537224, 'weight_xgb_class_0': 0.0017906579040188747, 'weight_xgb_class_1': 0.6638187373493322, 'weight_xgb_class_2': 0.49069394252366066}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  66%|██████████████████████████████████████████████████████████████████████████████████████▍                                           | 1329/2000 [00:38<00:22, 30.06it/s]

[I 2026-07-05 15:32:09,654] Trial 1321 finished with value: 0.948890520726176 and parameters: {'weight_lgbm_class_0': 0.14106022570659182, 'weight_lgbm_class_1': 0.9822777693666782, 'weight_lgbm_class_2': 0.5407787317585991, 'weight_xgb_class_0': 0.017104667175938663, 'weight_xgb_class_1': 0.6683150103163953, 'weight_xgb_class_2': 0.49188948070950395}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:09,685] Trial 1322 finished with value: 0.9490847031509472 and parameters: {'weight_lgbm_class_0': 0.14159693038691223, 'weight_lgbm_class_1': 0.9842568134319911, 'weight_lgbm_class_2': 0.5140162888983906, 'weight_xgb_class_0': 0.003930862722369482, 'weight_xgb_class_1': 0.6879723729255397, 'weight_xgb_class_2': 0.506143314033642}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:09,697] Trial 1323 finished with value: 0.9496468025047413 and parameters: {'weight_lgbm_class_0': 0.11706727032317538, 'weight_lgbm_class_1': 0.9837360895199697, 'weight_lgbm_class_2': 0.5020692462552792, 'weight_xgb_class_0': 0.001268962002997683, 'weight_xgb_class_1': 0.6698033721288131, 'weight_xgb_class_2': 0.49076017610101824}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:09,727] Trial 1325 finished with value: 0.9497466288552067 and parameters: {'weight_lgbm_class_0': 0.1206849284924873, 'weight_lgbm_class_1': 0.9988665393979401, 'weight_lgbm_class_2': 0.5620114338926695, 'weight_xgb_class_0': 0.00021934742136016838, 'weight_xgb_class_1': 0.6732934927325005, 'weight_xgb_class_2': 0.5792933835187478}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:09,742] Trial 1324 finished with value: 0.9492623336207965 and parameters: {'weight_lgbm_class_0': 0.11402320223850447, 'weight_lgbm_class_1': 0.17815263218010463, 'weight_lgbm_class_2': 0.5019727008026098, 'weight_xgb_class_0': 0.00035430092815114177, 'weight_xgb_class_1': 0.6668396174886035, 'weight_xgb_class_2': 0.5869567184450324}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:09,762] Trial 1326 finished with value: 0.9490086357950888 and parameters: {'weight_lgbm_class_0': 0.12549865840000662, 'weight_lgbm_class_1': 0.1224374647657156, 'weight_lgbm_class_2': 0.5074144135098232, 'weight_xgb_class_0': 0.00032213227800651737, 'weight_xgb_class_1': 0.676949899596066, 'weight_xgb_class_2': 0.5855461233197353}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:09,798] Trial 1327 finished with value: 0.9491488694546004 and parameters: {'weight_lgbm_class_0': 0.12873994758104332, 'weight_lgbm_class_1': 0.9997511379437872, 'weight_lgbm_class_2': 0.46671203557419416, 'weight_xgb_class_0': 0.018081708318095073, 'weight_xgb_class_1': 0.6636939299026994, 'weight_xgb_class_2': 0.5896510925681724}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:09,825] Trial 1328 finished with value: 0.9494404334122962 and parameters: {'weight_lgbm_class_0': 0.11958359365463328, 'weight_lgbm_class_1': 0.9977725847840249, 'weight_lgbm_class_2': 0.5077643218894491, 'weight_xgb_class_0': 0.017654249925746435, 'weight_xgb_class_1': 0.6716470290655587, 'weight_xgb_class_2': 0.5881068012906907}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:09,827] Trial 1329 finished with value: 0.949101433039759 and parameters: {'weight_lgbm_class_0': 0.13078083778025215, 'weight_lgbm_class_1': 0.9826677714273224, 'weight_lgbm_class_2': 0.46410460339177867, 'weight_xgb_class_0': 0.01786792876900898, 'weight_xgb_class_1': 0.6720181791748444, 'weight_xgb_class_2': 0.5891441315123093}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  67%|██████████████████████████████████████████████████████████████████████████████████████▋                                           | 1333/2000 [00:38<00:22, 29.42it/s]

[I 2026-07-05 15:32:09,928] Trial 1330 finished with value: 0.9496801201135868 and parameters: {'weight_lgbm_class_0': 0.1200695569631868, 'weight_lgbm_class_1': 0.999326739703536, 'weight_lgbm_class_2': 0.4425392621467922, 'weight_xgb_class_0': 0.0009499287835647366, 'weight_xgb_class_1': 0.6626513257320584, 'weight_xgb_class_2': 0.5822404770564604}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:10,036] Trial 1331 finished with value: 0.949507932387628 and parameters: {'weight_lgbm_class_0': 0.11783857280696018, 'weight_lgbm_class_1': 0.9999116222454554, 'weight_lgbm_class_2': 0.5446209060509983, 'weight_xgb_class_0': 0.018986870229310063, 'weight_xgb_class_1': 0.7220497499585045, 'weight_xgb_class_2': 0.582271808009305}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:10,069] Trial 1332 finished with value: 0.9498342771806917 and parameters: {'weight_lgbm_class_0': 0.11745084550966485, 'weight_lgbm_class_1': 0.9990728938786438, 'weight_lgbm_class_2': 0.46134584793947603, 'weight_xgb_class_0': 0.0009675802746006955, 'weight_xgb_class_1': 0.7191819895613614, 'weight_xgb_class_2': 0.5927829194184808}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:10,117] Trial 1333 finished with value: 0.9493559224851541 and parameters: {'weight_lgbm_class_0': 0.11832799497565118, 'weight_lgbm_class_1': 0.949300618860101, 'weight_lgbm_class_2': 0.46311236089462704, 'weight_xgb_class_0': 0.02225209012880731, 'weight_xgb_class_1': 0.7220017239810108, 'weight_xgb_class_2': 0.5993241154338329}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  67%|███████████████████████████████████████████████████████████████████████████████████████▏                                          | 1342/2000 [00:38<00:21, 30.89it/s]

[I 2026-07-05 15:32:10,154] Trial 1336 finished with value: 0.9492163098177769 and parameters: {'weight_lgbm_class_0': 0.09503022845457437, 'weight_lgbm_class_1': 0.9990160884544106, 'weight_lgbm_class_2': 0.46338296523222, 'weight_xgb_class_0': 0.030962509627139412, 'weight_xgb_class_1': 0.7213115466958187, 'weight_xgb_class_2': 0.4374419401157523}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:10,160] Trial 1334 finished with value: 0.9493023520978691 and parameters: {'weight_lgbm_class_0': 0.11643923687576124, 'weight_lgbm_class_1': 0.9991033016660997, 'weight_lgbm_class_2': 0.4510310556976134, 'weight_xgb_class_0': 0.022038571947383637, 'weight_xgb_class_1': 0.7184651013976345, 'weight_xgb_class_2': 0.5829448597798693}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:10,161] Trial 1335 finished with value: 0.9496831003164283 and parameters: {'weight_lgbm_class_0': 0.09271888315372485, 'weight_lgbm_class_1': 0.949092080094037, 'weight_lgbm_class_2': 0.46254162411236976, 'weight_xgb_class_0': 0.032296899218731585, 'weight_xgb_class_1': 0.7176140389352825, 'weight_xgb_class_2': 0.5909209371592188}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:10,168] Trial 1337 finished with value: 0.9495814016246168 and parameters: {'weight_lgbm_class_0': 0.09661534885550876, 'weight_lgbm_class_1': 0.9551830822916494, 'weight_lgbm_class_2': 0.45990491236526204, 'weight_xgb_class_0': 0.03199639791214666, 'weight_xgb_class_1': 0.7185515946843599, 'weight_xgb_class_2': 0.5932895908462243}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:10,214] Trial 1338 finished with value: 0.9494743685316261 and parameters: {'weight_lgbm_class_0': 0.09740535171457379, 'weight_lgbm_class_1': 0.9988359808552069, 'weight_lgbm_class_2': 0.45698915639612386, 'weight_xgb_class_0': 0.035149101232785, 'weight_xgb_class_1': 0.7198331414141393, 'weight_xgb_class_2': 0.585685177229326}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:10,232] Trial 1339 finished with value: 0.9497000092101135 and parameters: {'weight_lgbm_class_0': 0.09266488441989922, 'weight_lgbm_class_1': 0.9988738790104782, 'weight_lgbm_class_2': 0.4643892854571132, 'weight_xgb_class_0': 0.03309074674684922, 'weight_xgb_class_1': 0.7198349804802363, 'weight_xgb_class_2': 0.5951936248838325}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:10,260] Trial 1341 finished with value: 0.9496595809570847 and parameters: {'weight_lgbm_class_0': 0.09039980974721684, 'weight_lgbm_class_1': 0.951706300553362, 'weight_lgbm_class_2': 0.45622232031647514, 'weight_xgb_class_0': 0.033005461259688895, 'weight_xgb_class_1': 0.7157211960540327, 'weight_xgb_class_2': 0.5727865821338681}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:10,276] Trial 1340 finished with value: 0.9495573467154044 and parameters: {'weight_lgbm_class_0': 0.09346517311173927, 'weight_lgbm_class_1': 0.9996850048626855, 'weight_lgbm_class_2': 0.45988672707834166, 'weight_xgb_class_0': 0.034563073796988496, 'weight_xgb_class_1': 0.7191288178971605, 'weight_xgb_class_2': 0.571470600575352}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:10,340] Trial 1342 finished with value: 0.9497763246667951 and parameters: {'weight_lgbm_class_0': 0.08638129525296492, 'weight_lgbm_class_1': 0.9594130185149334, 'weight_lgbm_class_2': 0.4487053528001203, 'weight_xgb_class_0': 0.03236517528691542, 'weight_xgb_class_1': 0.7115843594643736, 'weight_xgb_class_2': 0.5764272011183317}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  67%|███████████████████████████████████████████████████████████████████████████████████████▍                                          | 1346/2000 [00:39<00:24, 26.84it/s]

[I 2026-07-05 15:32:10,418] Trial 1343 finished with value: 0.9496327680367159 and parameters: {'weight_lgbm_class_0': 0.09281127520533755, 'weight_lgbm_class_1': 0.952238714856194, 'weight_lgbm_class_2': 0.4505639468052416, 'weight_xgb_class_0': 0.0313030537965326, 'weight_xgb_class_1': 0.7134122811633135, 'weight_xgb_class_2': 0.5682937557783496}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:10,467] Trial 1344 finished with value: 0.9491474582554634 and parameters: {'weight_lgbm_class_0': 0.09691411612189293, 'weight_lgbm_class_1': 0.9517939053193589, 'weight_lgbm_class_2': 0.4670795590282192, 'weight_xgb_class_0': 0.03142853109652574, 'weight_xgb_class_1': 0.7146039331477556, 'weight_xgb_class_2': 0.43221540820923054}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:10,546] Trial 1345 finished with value: 0.9480437707040029 and parameters: {'weight_lgbm_class_0': 0.16854669115722667, 'weight_lgbm_class_1': 0.9985713560209949, 'weight_lgbm_class_2': 0.46713744729450835, 'weight_xgb_class_0': 0.034653704140230515, 'weight_xgb_class_1': 0.7138249173877684, 'weight_xgb_class_2': 0.5695916348546906}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:10,611] Trial 1347 finished with value: 0.9495688039787474 and parameters: {'weight_lgbm_class_0': 0.0928224677196411, 'weight_lgbm_class_1': 0.9796426461395696, 'weight_lgbm_class_2': 0.44588393075649935, 'weight_xgb_class_0': 0.03435319408530791, 'weight_xgb_class_1': 0.704294940843205, 'weight_xgb_class_2': 0.5664596348853901}. Best is trial 1206 with value: 0.9498581274668642.

[I 2026-07-05 15:32:10,620] Trial 1349 finished with value: 0.9479318428669533 and parameters: {'weight_lgbm_class_0': 0.18392678230011406, 'weight_lgbm_class_1': 0.9703506841437606, 'weight_lgbm_class_2': 0.48345421444628817, 'weight_xgb_class_0': 0.021664748085087615, 'weight_xgb_class_1': 0.704045159530664, 'weight_xgb_class_2': 0.5684172329407429}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:10,635] Trial 1346 finished with value: 0.9457509773785456 and parameters: {'weight_lgbm_class_0': 0.18461935675031577, 'weight_lgbm_class_1': 0.9758438196363061, 'weight_lgbm_class_2': 0.48542710289871427, 'weight_xgb_class_0': 0.03442067546703283, 'weight_xgb_class_1': 0.11242557428515465, 'weight_xgb_class_2': 0.5674382913597128}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:10,657] Trial 1348 finished with value: 0.9497396235075334 and parameters: {'weight_lgbm_class_0': 0.09134552946712803, 'weight_lgbm_class_1': 0.9754663389674899, 'weight_lgbm_class_2': 0.44553213829426863, 'weight_xgb_class_0': 0.0008122702643038549, 'weight_xgb_class_1': 0.6935784800368724, 'weight_xgb_class_2': 0.5348374593610293}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:10,679] Trial 1350 finished with value: 0.9482006292057618 and parameters: {'weight_lgbm_class_0': 0.1691011615792042, 'weight_lgbm_class_1': 0.9677163286083081, 'weight_lgbm_class_2': 0.4783657093264646, 'weight_xgb_class_0': 0.020011354167211753, 'weight_xgb_class_1': 0.6430131687550777, 'weight_xgb_class_2': 0.5377374251009538}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:10,696] Trial 1351 finished with value: 0.9480801152362179 and parameters: {'weight_lgbm_class_0': 0.17509905285072683, 'weight_lgbm_class_1': 0.9702292630943121, 'weight_lgbm_class_2': 0.4793849003545984, 'weight_xgb_class_0': 0.018279853267281883, 'weight_xgb_class_1': 0.6468112467071739, 'weight_xgb_class_2': 0.5365675090471939}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:10,697] Trial 1352 finished with value: 0.9485177190118644 and parameters: {'weight_lgbm_class_0': 0.16690864126978272, 'weight_lgbm_class_1': 0.9697146754233447, 'weight_lgbm_class_2': 0.44148479471813395, 'weight_xgb_class_0': 0.001317798658611947, 'weight_xgb_class_1': 0.6378874175396374, 'weight_xgb_class_2': 0.5390951960733799}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:10,736] Trial 1353 finished with value: 0.9484716500335933 and parameters: {'weight_lgbm_class_0': 0.17249840208804007, 'weight_lgbm_class_1': 0.9705247496162553, 'weight_lgbm_class_2': 0.44192681238798265, 'weight_xgb_class_0': 0.0007536610882043667, 'weight_xgb_class_1': 0.6949701583181139, 'weight_xgb_class_2': 0.5416414718016086}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:10,788] Trial 1354 finished with value: 0.9498023502492284 and parameters: {'weight_lgbm_class_0': 0.11422789471237021, 'weight_lgbm_class_1': 0.970645048349541, 'weight_lgbm_class_2': 0.47860203338956275, 'weight_xgb_class_0': 0.0009302936162125333, 'weight_xgb_class_1': 0.6936264795720735, 'weight_xgb_class_2': 0.5339674337870018}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  68%|████████████████████████████████████████████████████████████████████████████████████████▎                                         | 1359/2000 [00:39<00:22, 28.80it/s]

[I 2026-07-05 15:32:10,837] Trial 1355 finished with value: 0.9491206504315063 and parameters: {'weight_lgbm_class_0': 0.11537100071279201, 'weight_lgbm_class_1': 0.9776455178543785, 'weight_lgbm_class_2': 0.40828983602525337, 'weight_xgb_class_0': 0.021019705828615332, 'weight_xgb_class_1': 0.6358450099184231, 'weight_xgb_class_2': 0.5388541352130735}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:10,880] Trial 1356 finished with value: 0.9455120214247862 and parameters: {'weight_lgbm_class_0': 0.22619455236140934, 'weight_lgbm_class_1': 0.9756379361413989, 'weight_lgbm_class_2': 0.4102661835440073, 'weight_xgb_class_0': 0.016930362360696748, 'weight_xgb_class_1': 0.6387212091439203, 'weight_xgb_class_2': 0.5311768757346951}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:10,952] Trial 1357 finished with value: 0.9477548350893783 and parameters: {'weight_lgbm_class_0': 0.17815253394576772, 'weight_lgbm_class_1': 0.9729299137689763, 'weight_lgbm_class_2': 0.4135844790640082, 'weight_xgb_class_0': 0.018830091400616877, 'weight_xgb_class_1': 0.6946628769105744, 'weight_xgb_class_2': 0.5345153484329284}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:11,003] Trial 1358 finished with value: 0.9496114050478855 and parameters: {'weight_lgbm_class_0': 0.11459715345817585, 'weight_lgbm_class_1': 0.970835583927123, 'weight_lgbm_class_2': 0.41073500147332936, 'weight_xgb_class_0': 0.0014663741192440533, 'weight_xgb_class_1': 0.6940765352439074, 'weight_xgb_class_2': 0.5356018370864454}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:11,025] Trial 1359 finished with value: 0.9496733630612892 and parameters: {'weight_lgbm_class_0': 0.11357787661629702, 'weight_lgbm_class_1': 0.9761923963431385, 'weight_lgbm_class_2': 0.41392171857600746, 'weight_xgb_class_0': 0.0002602036396256932, 'weight_xgb_class_1': 0.6893300183640205, 'weight_xgb_class_2': 0.5308573198196171}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  68%|████████████████████████████████████████████████████████████████████████████████████████▊                                         | 1366/2000 [00:39<00:22, 28.28it/s]

[I 2026-07-05 15:32:11,052] Trial 1361 finished with value: 0.9490468516296429 and parameters: {'weight_lgbm_class_0': 0.11804760308012349, 'weight_lgbm_class_1': 0.9799666922026172, 'weight_lgbm_class_2': 0.4135434221805369, 'weight_xgb_class_0': 0.01803920303117126, 'weight_xgb_class_1': 0.6936095201433043, 'weight_xgb_class_2': 0.5096295642276691}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:11,073] Trial 1360 finished with value: 0.949408430402829 and parameters: {'weight_lgbm_class_0': 0.11576396730952683, 'weight_lgbm_class_1': 0.9998055223073222, 'weight_lgbm_class_2': 0.40808392434838725, 'weight_xgb_class_0': 0.016776019386094493, 'weight_xgb_class_1': 0.6906855306924508, 'weight_xgb_class_2': 0.6016849271574538}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:11,134] Trial 1363 finished with value: 0.9488885223942828 and parameters: {'weight_lgbm_class_0': 0.12006596727176577, 'weight_lgbm_class_1': 0.9812901559327567, 'weight_lgbm_class_2': 0.4070122676776562, 'weight_xgb_class_0': 0.022089105839834887, 'weight_xgb_class_1': 0.5180499492248841, 'weight_xgb_class_2': 0.5117460797930675}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:11,139] Trial 1362 finished with value: 0.9493830367359708 and parameters: {'weight_lgbm_class_0': 0.11746077498535498, 'weight_lgbm_class_1': 0.9799054402256754, 'weight_lgbm_class_2': 0.4097536428454924, 'weight_xgb_class_0': 0.01606117389482157, 'weight_xgb_class_1': 0.6853321454069486, 'weight_xgb_class_2': 0.6031547202465583}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:11,175] Trial 1364 finished with value: 0.9491664912042239 and parameters: {'weight_lgbm_class_0': 0.13557934520788428, 'weight_lgbm_class_1': 0.9830605942006624, 'weight_lgbm_class_2': 0.4091477301198594, 'weight_xgb_class_0': 0.0003709380149855901, 'weight_xgb_class_1': 0.6848402223715409, 'weight_xgb_class_2': 0.5551046492567925}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:11,213] Trial 1365 finished with value: 0.9493931865368529 and parameters: {'weight_lgbm_class_0': 0.11618727542154968, 'weight_lgbm_class_1': 0.9509352857088492, 'weight_lgbm_class_2': 0.421914839646998, 'weight_xgb_class_0': 0.018012596728123536, 'weight_xgb_class_1': 0.6923192947690184, 'weight_xgb_class_2': 0.6001618780034974}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:11,232] Trial 1366 finished with value: 0.9496688513693892 and parameters: {'weight_lgbm_class_0': 0.12073782003748301, 'weight_lgbm_class_1': 0.9810354652213779, 'weight_lgbm_class_2': 0.4121265791079554, 'weight_xgb_class_0': 0.0005439176647188571, 'weight_xgb_class_1': 0.692836807678438, 'weight_xgb_class_2': 0.6023253647806449}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  69%|█████████████████████████████████████████████████████████████████████████████████████████                                         | 1371/2000 [00:40<00:26, 23.75it/s]

[I 2026-07-05 15:32:11,293] Trial 1367 finished with value: 0.9486010827612645 and parameters: {'weight_lgbm_class_0': 0.1397378704945967, 'weight_lgbm_class_1': 0.9480044970505137, 'weight_lgbm_class_2': 0.4116416649065055, 'weight_xgb_class_0': 0.016914222416948232, 'weight_xgb_class_1': 0.6958342134211153, 'weight_xgb_class_2': 0.5124662499203578}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:11,307] Trial 1368 finished with value: 0.9493625052921404 and parameters: {'weight_lgbm_class_0': 0.13451816554589313, 'weight_lgbm_class_1': 0.9489023679666961, 'weight_lgbm_class_2': 0.4153814726216926, 'weight_xgb_class_0': 0.00036216455864722017, 'weight_xgb_class_1': 0.6916678566990462, 'weight_xgb_class_2': 0.6059956546767105}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:11,384] Trial 1369 finished with value: 0.9487876181773238 and parameters: {'weight_lgbm_class_0': 0.1387568387634184, 'weight_lgbm_class_1': 0.9483542297148249, 'weight_lgbm_class_2': 0.41277415080438634, 'weight_xgb_class_0': 0.01764750674820103, 'weight_xgb_class_1': 0.6894673107431268, 'weight_xgb_class_2': 0.5524465561975522}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:11,480] Trial 1370 finished with value: 0.9492319909302065 and parameters: {'weight_lgbm_class_0': 0.139085322977872, 'weight_lgbm_class_1': 0.9506826845889191, 'weight_lgbm_class_2': 0.4143543191407906, 'weight_xgb_class_0': 0.000168442448835196, 'weight_xgb_class_1': 0.6618450049006368, 'weight_xgb_class_2': 0.6008798170743281}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:11,495] Trial 1371 finished with value: 0.9489160905760542 and parameters: {'weight_lgbm_class_0': 0.13490550260284695, 'weight_lgbm_class_1': 0.9997417574908901, 'weight_lgbm_class_2': 0.4377034134290507, 'weight_xgb_class_0': 0.01707468488698074, 'weight_xgb_class_1': 0.6594566219485738, 'weight_xgb_class_2': 0.5645155334808359}. Best is trial 1206 with value: 0.9498581274668642.

[I 2026-07-05 15:32:11,529] Trial 1372 finished with value: 0.949236173291285 and parameters: {'weight_lgbm_class_0': 0.14019000368701337, 'weight_lgbm_class_1': 0.9496661195295523, 'weight_lgbm_class_2': 0.4407791399554202, 'weight_xgb_class_0': 0.001175789190057147, 'weight_xgb_class_1': 0.6617518817234288, 'weight_xgb_class_2': 0.6021643870889536}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:11,555] Trial 1374 finished with value: 0.9484270009873841 and parameters: {'weight_lgbm_class_0': 0.13923931639588594, 'weight_lgbm_class_1': 0.9483215843205921, 'weight_lgbm_class_2': 0.43739254583392045, 'weight_xgb_class_0': 0.03732090778454818, 'weight_xgb_class_1': 0.6634017057254826, 'weight_xgb_class_2': 0.5573122360171127}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:11,580] Trial 1373 finished with value: 0.9489767246814012 and parameters: {'weight_lgbm_class_0': 0.14636432747464698, 'weight_lgbm_class_1': 0.9512841357635323, 'weight_lgbm_class_2': 0.43635965488119144, 'weight_xgb_class_0': 0.0009678683047038925, 'weight_xgb_class_1': 0.6664335557056964, 'weight_xgb_class_2': 0.5560796790656904}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:11,612] Trial 1375 finished with value: 0.9484397975841273 and parameters: {'weight_lgbm_class_0': 0.1413678727310824, 'weight_lgbm_class_1': 0.9474362897762599, 'weight_lgbm_class_2': 0.4210769673922325, 'weight_xgb_class_0': 0.039007398780752545, 'weight_xgb_class_1': 0.6652775849614923, 'weight_xgb_class_2': 0.60388243188045}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:11,614] Trial 1376 finished with value: 0.9482231656739043 and parameters: {'weight_lgbm_class_0': 0.14448175165862742, 'weight_lgbm_class_1': 0.9471339218792296, 'weight_lgbm_class_2': 0.43732326378727776, 'weight_xgb_class_0': 0.0383759803441488, 'weight_xgb_class_1': 0.5767679273709158, 'weight_xgb_class_2': 0.5686229207472495}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:11,655] Trial 1377 finished with value: 0.948350016203278 and parameters: {'weight_lgbm_class_0': 0.14302789804714705, 'weight_lgbm_class_1': 0.9999877853421343, 'weight_lgbm_class_2': 0.44106530317091686, 'weight_xgb_class_0': 0.03929797078658214, 'weight_xgb_class_1': 0.5831248900706452, 'weight_xgb_class_2': 0.5615884103699338}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:11,683] Trial 1378 finished with value: 0.9484678771574999 and parameters: {'weight_lgbm_class_0': 0.13517460611556875, 'weight_lgbm_class_1': 0.9477517474396757, 'weight_lgbm_class_2': 0.4375926062516189, 'weight_xgb_class_0': 0.0389981422985501, 'weight_xgb_class_1': 0.6588025371794217, 'weight_xgb_class_2': 0.5558186766541118}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:11,744] Trial 1379 finished with value: 0.9494528900124366 and parameters: {'weight_lgbm_class_0': 0.08872542153730874, 'weight_lgbm_class_1': 0.9497550419174141, 'weight_lgbm_class_2': 0.4361821837716462, 'weight_xgb_class_0': 0.038710708595140156, 'weight_xgb_class_1': 0.6570409049333112, 'weight_xgb_class_2': 0.5589139743698283}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  69%|█████████████████████████████████████████████████████████████████████████████████████████▉                                        | 1383/2000 [00:40<00:24, 24.81it/s]

[I 2026-07-05 15:32:11,752] Trial 1380 finished with value: 0.9492869980368507 and parameters: {'weight_lgbm_class_0': 0.09169463780572926, 'weight_lgbm_class_1': 0.9489508043531981, 'weight_lgbm_class_2': 0.43378782087943335, 'weight_xgb_class_0': 0.0424076886725902, 'weight_xgb_class_1': 0.6632866058852624, 'weight_xgb_class_2': 0.5591725589073678}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:11,842] Trial 1381 finished with value: 0.9495473210416973 and parameters: {'weight_lgbm_class_0': 0.09072802440725836, 'weight_lgbm_class_1': 0.9500129128845956, 'weight_lgbm_class_2': 0.436073696286022, 'weight_xgb_class_0': 0.03449759613727406, 'weight_xgb_class_1': 0.6603395143774844, 'weight_xgb_class_2': 0.561496648761411}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:11,925] Trial 1384 finished with value: 0.9494178726830896 and parameters: {'weight_lgbm_class_0': 0.09294125037515027, 'weight_lgbm_class_1': 0.9606606111878723, 'weight_lgbm_class_2': 0.43605553595006075, 'weight_xgb_class_0': 0.03822044845940161, 'weight_xgb_class_1': 0.7278487344454118, 'weight_xgb_class_2': 0.5731479016983978}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:11,936] Trial 1383 finished with value: 0.9491647584897335 and parameters: {'weight_lgbm_class_0': 0.10094233680251834, 'weight_lgbm_class_1': 0.9533890820257891, 'weight_lgbm_class_2': 0.43583833562903834, 'weight_xgb_class_0': 0.040001384294937846, 'weight_xgb_class_1': 0.7299887864521697, 'weight_xgb_class_2': 0.5600064269560541}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  70%|██████████████████████████████████████████████████████████████████████████████████████████▍                                       | 1392/2000 [00:40<00:20, 29.71it/s]

[I 2026-07-05 15:32:11,965] Trial 1382 finished with value: 0.9494460321765724 and parameters: {'weight_lgbm_class_0': 0.09114366543071477, 'weight_lgbm_class_1': 0.956499178025232, 'weight_lgbm_class_2': 0.4399002529940422, 'weight_xgb_class_0': 0.03805304840924882, 'weight_xgb_class_1': 0.7294754002936829, 'weight_xgb_class_2': 0.5536425704930493}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:11,996] Trial 1385 finished with value: 0.949263913883455 and parameters: {'weight_lgbm_class_0': 0.09331317456720269, 'weight_lgbm_class_1': 0.9991111391466577, 'weight_lgbm_class_2': 0.4347651824809478, 'weight_xgb_class_0': 0.03916429052680499, 'weight_xgb_class_1': 0.2510534131611054, 'weight_xgb_class_2': 0.577866167626474}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:12,012] Trial 1386 finished with value: 0.9496640542168827 and parameters: {'weight_lgbm_class_0': 0.08885380334724462, 'weight_lgbm_class_1': 0.9822316384614477, 'weight_lgbm_class_2': 0.49767960201453315, 'weight_xgb_class_0': 0.039156318392967744, 'weight_xgb_class_1': 0.724564780679872, 'weight_xgb_class_2': 0.5759707103399354}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:12,041] Trial 1387 finished with value: 0.9494920223577825 and parameters: {'weight_lgbm_class_0': 0.09109173738250431, 'weight_lgbm_class_1': 0.9831576039358818, 'weight_lgbm_class_2': 0.440868135872192, 'weight_xgb_class_0': 0.039440124773848284, 'weight_xgb_class_1': 0.7276059716705575, 'weight_xgb_class_2': 0.5755042152104823}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:12,061] Trial 1388 finished with value: 0.9493384955074489 and parameters: {'weight_lgbm_class_0': 0.09339800041802312, 'weight_lgbm_class_1': 0.9659777470648778, 'weight_lgbm_class_2': 0.4795747353993447, 'weight_xgb_class_0': 0.03882543194585175, 'weight_xgb_class_1': 0.730773819526998, 'weight_xgb_class_2': 0.5085110520629601}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:12,068] Trial 1389 finished with value: 0.9494452552703655 and parameters: {'weight_lgbm_class_0': 0.09517925831253071, 'weight_lgbm_class_1': 0.9998474768174401, 'weight_lgbm_class_2': 0.47797951339014133, 'weight_xgb_class_0': 0.03378391058887298, 'weight_xgb_class_1': 0.7286109391173867, 'weight_xgb_class_2': 0.512903521309529}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:12,095] Trial 1390 finished with value: 0.9269488136817188 and parameters: {'weight_lgbm_class_0': 0.4943574993002104, 'weight_lgbm_class_1': 0.9647167456235651, 'weight_lgbm_class_2': 0.49754894856432336, 'weight_xgb_class_0': 0.03626689667649729, 'weight_xgb_class_1': 0.7236110032225687, 'weight_xgb_class_2': 0.5095068827283187}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:12,177] Trial 1392 finished with value: 0.9497472069876736 and parameters: {'weight_lgbm_class_0': 0.0981421065955828, 'weight_lgbm_class_1': 0.9814028690314838, 'weight_lgbm_class_2': 0.4910310309731859, 'weight_xgb_class_0': 0.01977853897143915, 'weight_xgb_class_1': 0.7311328918508918, 'weight_xgb_class_2': 0.515185389357225}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  70%|██████████████████████████████████████████████████████████████████████████████████████████▋                                       | 1396/2000 [00:41<00:24, 24.77it/s]

[I 2026-07-05 15:32:12,226] Trial 1391 finished with value: 0.9498276094599799 and parameters: {'weight_lgbm_class_0': 0.0940903905803061, 'weight_lgbm_class_1': 0.9842424594176734, 'weight_lgbm_class_2': 0.47398640998253233, 'weight_xgb_class_0': 0.01948581763590404, 'weight_xgb_class_1': 0.7249865981305097, 'weight_xgb_class_2': 0.5191062606616679}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:12,244] Trial 1393 finished with value: 0.9496668409069638 and parameters: {'weight_lgbm_class_0': 0.10458868662572658, 'weight_lgbm_class_1': 0.9830717408296864, 'weight_lgbm_class_2': 0.504795346816086, 'weight_xgb_class_0': 0.017691773569437658, 'weight_xgb_class_1': 0.7269843296750694, 'weight_xgb_class_2': 0.5153029160838923}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:12,321] Trial 1394 finished with value: 0.9495066557473942 and parameters: {'weight_lgbm_class_0': 0.10888996567875948, 'weight_lgbm_class_1': 0.9813233487743235, 'weight_lgbm_class_2': 0.5042668787276536, 'weight_xgb_class_0': 0.019107525292467252, 'weight_xgb_class_1': 0.725322238206143, 'weight_xgb_class_2': 0.5194286375565482}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:12,384] Trial 1395 finished with value: 0.9497463993620362 and parameters: {'weight_lgbm_class_0': 0.10814075313701611, 'weight_lgbm_class_1': 0.978924608690149, 'weight_lgbm_class_2': 0.5057242093740832, 'weight_xgb_class_0': 0.01689572348291155, 'weight_xgb_class_1': 0.7243001287966051, 'weight_xgb_class_2': 0.5874596107470668}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:12,387] Trial 1396 finished with value: 0.9496266909776242 and parameters: {'weight_lgbm_class_0': 0.11487842959204025, 'weight_lgbm_class_1': 0.9832936623273391, 'weight_lgbm_class_2': 0.5350383376449546, 'weight_xgb_class_0': 0.017502502602857028, 'weight_xgb_class_1': 0.7224991882215211, 'weight_xgb_class_2': 0.5921906694060285}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  70%|███████████████████████████████████████████████████████████████████████████████████████████▎                                      | 1404/2000 [00:41<00:20, 29.19it/s]

[I 2026-07-05 15:32:12,424] Trial 1397 finished with value: 0.9495505374016688 and parameters: {'weight_lgbm_class_0': 0.10683542956087132, 'weight_lgbm_class_1': 0.9853022910519699, 'weight_lgbm_class_2': 0.4709675403919814, 'weight_xgb_class_0': 0.016693927903135116, 'weight_xgb_class_1': 0.7067378806632731, 'weight_xgb_class_2': 0.5168647792843827}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:12,459] Trial 1399 finished with value: 0.9494646816002165 and parameters: {'weight_lgbm_class_0': 0.10961176333085193, 'weight_lgbm_class_1': 0.9809707442081024, 'weight_lgbm_class_2': 0.40034161510179006, 'weight_xgb_class_0': 0.019770395434216895, 'weight_xgb_class_1': 0.7078362960396595, 'weight_xgb_class_2': 0.5945323146859717}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:12,468] Trial 1398 finished with value: 0.9497435648283773 and parameters: {'weight_lgbm_class_0': 0.10945799177186796, 'weight_lgbm_class_1': 0.9781758063041104, 'weight_lgbm_class_2': 0.5356376787466146, 'weight_xgb_class_0': 0.01801401929638487, 'weight_xgb_class_1': 0.6197248682441848, 'weight_xgb_class_2': 0.5962038173618291}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:12,511] Trial 1401 finished with value: 0.9477846244086466 and parameters: {'weight_lgbm_class_0': 0.10161443367539416, 'weight_lgbm_class_1': 0.9776593485783, 'weight_lgbm_class_2': 0.4103245783678392, 'weight_xgb_class_0': 0.018926789190357472, 'weight_xgb_class_1': 0.7103794603371736, 'weight_xgb_class_2': 0.16831191234893028}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:12,527] Trial 1400 finished with value: 0.9480540321979904 and parameters: {'weight_lgbm_class_0': 0.10022398510913413, 'weight_lgbm_class_1': 0.9993719206939711, 'weight_lgbm_class_2': 0.3973276553479754, 'weight_xgb_class_0': 0.0172552824010985, 'weight_xgb_class_1': 0.3999594271863328, 'weight_xgb_class_2': 0.1882811371370754}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:12,530] Trial 1402 finished with value: 0.9495057858730886 and parameters: {'weight_lgbm_class_0': 0.1048022655464929, 'weight_lgbm_class_1': 0.9815146182375819, 'weight_lgbm_class_2': 0.3954123244344846, 'weight_xgb_class_0': 0.019594135454159462, 'weight_xgb_class_1': 0.6192743283057847, 'weight_xgb_class_2': 0.5941422850283202}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:12,588] Trial 1403 finished with value: 0.9498404918879046 and parameters: {'weight_lgbm_class_0': 0.1102991552773442, 'weight_lgbm_class_1': 0.9992392860311878, 'weight_lgbm_class_2': 0.3999613000779353, 'weight_xgb_class_0': 0.001004199466503301, 'weight_xgb_class_1': 0.7086991136330597, 'weight_xgb_class_2': 0.5934167405113461}. Best is trial 1206 with value: 0.9498581274668642.

[I 2026-07-05 15:32:12,655] Trial 1404 finished with value: 0.9493627762448597 and parameters: {'weight_lgbm_class_0': 0.11282704663985642, 'weight_lgbm_class_1': 0.9993385767015794, 'weight_lgbm_class_2': 0.533831756602465, 'weight_xgb_class_0': 0.01811535166170487, 'weight_xgb_class_1': 0.7038555659320606, 'weight_xgb_class_2': 0.4567220860151544}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:12,684] Trial 1405 finished with value: 0.94970585853661 and parameters: {'weight_lgbm_class_0': 0.10985497682265755, 'weight_lgbm_class_1': 0.9815532851236528, 'weight_lgbm_class_2': 0.47019368321288557, 'weight_xgb_class_0': 0.0005868296010470761, 'weight_xgb_class_1': 0.7058799067829803, 'weight_xgb_class_2': 0.4647753311263631}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:12,734] Trial 1406 finished with value: 0.9494475009724642 and parameters: {'weight_lgbm_class_0': 0.12572054997478918, 'weight_lgbm_class_1': 0.9832590360818764, 'weight_lgbm_class_2': 0.5287910221315641, 'weight_xgb_class_0': 0.0008140220004023216, 'weight_xgb_class_1': 0.7050155336499538, 'weight_xgb_class_2': 0.45757049950458684}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:12,812] Trial 1408 finished with value: 0.949828294212748 and parameters: {'weight_lgbm_class_0': 0.1122760492480759, 'weight_lgbm_class_1': 0.9982196868850209, 'weight_lgbm_class_2': 0.4673188520577923, 'weight_xgb_class_0': 5.292433709577489e-05, 'weight_xgb_class_1': 0.704969613554782, 'weight_xgb_class_2': 0.5408839803429234}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:12,825] Trial 1407 finished with value: 0.9492606566160822 and parameters: {'weight_lgbm_class_0': 0.11198518664715541, 'weight_lgbm_class_1': 0.9624640806871368, 'weight_lgbm_class_2': 0.4666258309985982, 'weight_xgb_class_0': 0.017514673399234078, 'weight_xgb_class_1': 0.7022584535579035, 'weight_xgb_class_2': 0.4726762601143147}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  71%|████████████████████████████████████████████████████████████████████████████████████████████                                      | 1416/2000 [00:41<00:19, 29.56it/s]

[I 2026-07-05 15:32:12,848] Trial 1409 finished with value: 0.9188011626898032 and parameters: {'weight_lgbm_class_0': 0.612886006591131, 'weight_lgbm_class_1': 0.9632441647442457, 'weight_lgbm_class_2': 0.4707968602272857, 'weight_xgb_class_0': 0.0014491067211746611, 'weight_xgb_class_1': 0.7018349686886233, 'weight_xgb_class_2': 0.4834468072275298}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:12,890] Trial 1410 finished with value: 0.9485430086003447 and parameters: {'weight_lgbm_class_0': 0.15833052498634415, 'weight_lgbm_class_1': 0.9659789203572702, 'weight_lgbm_class_2': 0.46903129764826157, 'weight_xgb_class_0': 0.015826102910411352, 'weight_xgb_class_1': 0.7006649861158177, 'weight_xgb_class_2': 0.5389582292116067}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:12,945] Trial 1411 finished with value: 0.9481606734725861 and parameters: {'weight_lgbm_class_0': 0.1596406495122788, 'weight_lgbm_class_1': 0.9634324666404726, 'weight_lgbm_class_2': 0.4608323969218633, 'weight_xgb_class_0': 0.017255779916053877, 'weight_xgb_class_1': 0.7040376168838538, 'weight_xgb_class_2': 0.463241853317503}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:12,951] Trial 1412 finished with value: 0.948890936669527 and parameters: {'weight_lgbm_class_0': 0.15637965445024826, 'weight_lgbm_class_1': 0.9986723993152878, 'weight_lgbm_class_2': 0.47343810708707296, 'weight_xgb_class_0': 0.0015552828217769014, 'weight_xgb_class_1': 0.7045045729897101, 'weight_xgb_class_2': 0.5407035094961726}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:12,966] Trial 1413 finished with value: 0.9470713942561731 and parameters: {'weight_lgbm_class_0': 0.207341800478334, 'weight_lgbm_class_1': 0.9973698334666108, 'weight_lgbm_class_2': 0.39850595803728056, 'weight_xgb_class_0': 0.017528768547171572, 'weight_xgb_class_1': 0.7008507643332095, 'weight_xgb_class_2': 0.6119244347840794}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:12,983] Trial 1414 finished with value: 0.9495139036695379 and parameters: {'weight_lgbm_class_0': 0.12711978652245265, 'weight_lgbm_class_1': 0.9961303144841308, 'weight_lgbm_class_2': 0.3965934396354156, 'weight_xgb_class_0': 0.0012526220010060005, 'weight_xgb_class_1': 0.708885821747478, 'weight_xgb_class_2': 0.6082716404757482}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:13,038] Trial 1415 finished with value: 0.9484607855529014 and parameters: {'weight_lgbm_class_0': 0.1282296862029945, 'weight_lgbm_class_1': 0.042850879565412336, 'weight_lgbm_class_2': 0.3995984482806895, 'weight_xgb_class_0': 0.00027406290007912933, 'weight_xgb_class_1': 0.6993928426651126, 'weight_xgb_class_2': 0.6110135332371064}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  71%|████████████████████████████████████████████████████████████████████████████████████████████▎                                     | 1420/2000 [00:41<00:23, 24.60it/s]

[I 2026-07-05 15:32:13,090] Trial 1416 finished with value: 0.9484237464342155 and parameters: {'weight_lgbm_class_0': 0.16067115299167814, 'weight_lgbm_class_1': 0.9624357198550957, 'weight_lgbm_class_2': 0.4005828149928656, 'weight_xgb_class_0': 0.018742462198337775, 'weight_xgb_class_1': 0.7078077788228179, 'weight_xgb_class_2': 0.6138783357829509}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:13,124] Trial 1417 finished with value: 0.8844244888132534 and parameters: {'weight_lgbm_class_0': 0.6049839193870072, 'weight_lgbm_class_1': 0.9656114476611158, 'weight_lgbm_class_2': 0.39851616529935435, 'weight_xgb_class_0': 0.5858256624247855, 'weight_xgb_class_1': 0.7030888980746944, 'weight_xgb_class_2': 0.6052602007438573}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:13,145] Trial 1418 finished with value: 0.9478491976505098 and parameters: {'weight_lgbm_class_0': 0.1616347329489987, 'weight_lgbm_class_1': 0.9992864001593719, 'weight_lgbm_class_2': 0.40583848466621397, 'weight_xgb_class_0': 0.020926915995742326, 'weight_xgb_class_1': 0.7060809031103472, 'weight_xgb_class_2': 0.48031192991212984}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:13,285] Trial 1420 finished with value: 0.9486802308138961 and parameters: {'weight_lgbm_class_0': 0.16369249598264818, 'weight_lgbm_class_1': 0.9992814146535962, 'weight_lgbm_class_2': 0.450887898429685, 'weight_xgb_class_0': 4.490659404550359e-05, 'weight_xgb_class_1': 0.6827300535041471, 'weight_xgb_class_2': 0.5367240678111547}. Best is trial 1206 with value: 0.9498581274668642.

[I 2026-07-05 15:32:13,304] Trial 1419 finished with value: 0.9486442141477515 and parameters: {'weight_lgbm_class_0': 0.14962285504874479, 'weight_lgbm_class_1': 0.9976165100206082, 'weight_lgbm_class_2': 0.4899871051705821, 'weight_xgb_class_0': 0.02013112783544032, 'weight_xgb_class_1': 0.6762304448448815, 'weight_xgb_class_2': 0.5320577244307225}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:13,317] Trial 1421 finished with value: 0.9487858038439191 and parameters: {'weight_lgbm_class_0': 0.15875375534556382, 'weight_lgbm_class_1': 0.996550290012607, 'weight_lgbm_class_2': 0.4484738808307273, 'weight_xgb_class_0': 0.0009612726542592178, 'weight_xgb_class_1': 0.6862113019728908, 'weight_xgb_class_2': 0.5425446264629279}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:13,322] Trial 1422 finished with value: 0.9469847869672755 and parameters: {'weight_lgbm_class_0': 0.13307163510169057, 'weight_lgbm_class_1': 0.032385877760026605, 'weight_lgbm_class_2': 0.45029049842843594, 'weight_xgb_class_0': 0.018809035012838433, 'weight_xgb_class_1': 0.6743279962081707, 'weight_xgb_class_2': 0.5382275269723883}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:13,378] Trial 1424 finished with value: 0.893633965314614 and parameters: {'weight_lgbm_class_0': 0.9319417262770757, 'weight_lgbm_class_1': 0.9996063628128132, 'weight_lgbm_class_2': 0.48866503050000853, 'weight_xgb_class_0': 0.0012500081334904582, 'weight_xgb_class_1': 0.3558719478687976, 'weight_xgb_class_2': 0.5325858352442414}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:13,429] Trial 1423 finished with value: 0.9491287488577095 and parameters: {'weight_lgbm_class_0': 0.13284964465247773, 'weight_lgbm_class_1': 0.9854077900499969, 'weight_lgbm_class_2': 0.45572748119784967, 'weight_xgb_class_0': 0.00223289284574461, 'weight_xgb_class_1': 0.6791685765558692, 'weight_xgb_class_2': 0.49800449436552424}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:13,431] Trial 1426 finished with value: 0.9494026436667024 and parameters: {'weight_lgbm_class_0': 0.08771704407269917, 'weight_lgbm_class_1': 0.9968748667469405, 'weight_lgbm_class_2': 0.48834222876956085, 'weight_xgb_class_0': 0.04261927733297646, 'weight_xgb_class_1': 0.6713933224551192, 'weight_xgb_class_2': 0.5055781071078613}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:13,446] Trial 1425 finished with value: 0.894640927179318 and parameters: {'weight_lgbm_class_0': 0.9592291111811561, 'weight_lgbm_class_1': 0.9855258690571466, 'weight_lgbm_class_2': 0.48215283736195325, 'weight_xgb_class_0': 0.03846304390359915, 'weight_xgb_class_1': 0.6743493470583175, 'weight_xgb_class_2': 0.5299473159050891}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:13,476] Trial 1427 finished with value: 0.9496966795789138 and parameters: {'weight_lgbm_class_0': 0.08357245972301752, 'weight_lgbm_class_1': 0.9984912651682836, 'weight_lgbm_class_2': 0.4875788378212756, 'weight_xgb_class_0': 0.0015816042103547643, 'weight_xgb_class_1': 0.6809783980587857, 'weight_xgb_class_2': 0.5272493001746661}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  72%|█████████████████████████████████████████████████████████████████████████████████████████████                                     | 1432/2000 [00:42<00:18, 31.09it/s]

[I 2026-07-05 15:32:13,514] Trial 1428 finished with value: 0.9492259049769496 and parameters: {'weight_lgbm_class_0': 0.08532229815746126, 'weight_lgbm_class_1': 0.008646578572304886, 'weight_lgbm_class_2': 0.4877522006667803, 'weight_xgb_class_0': 0.0011452424177249543, 'weight_xgb_class_1': 0.6787401062056356, 'weight_xgb_class_2': 0.5271349324052166}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:13,550] Trial 1429 finished with value: 0.9495259867317918 and parameters: {'weight_lgbm_class_0': 0.08444250620202091, 'weight_lgbm_class_1': 0.999448980761702, 'weight_lgbm_class_2': 0.45304852885977936, 'weight_xgb_class_0': 0.040745534589099124, 'weight_xgb_class_1': 0.6785985776349923, 'weight_xgb_class_2': 0.5324011788740579}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:13,558] Trial 1430 finished with value: 0.89614044920816 and parameters: {'weight_lgbm_class_0': 0.938999749629106, 'weight_lgbm_class_1': 0.9825207741963151, 'weight_lgbm_class_2': 0.49390863584371997, 'weight_xgb_class_0': 0.03905085905185819, 'weight_xgb_class_1': 0.6785992288223139, 'weight_xgb_class_2': 0.5294528900073456}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:13,706] Trial 1431 finished with value: 0.8913906661730661 and parameters: {'weight_lgbm_class_0': 0.08057532505318428, 'weight_lgbm_class_1': 0.9998194694499462, 'weight_lgbm_class_2': 0.48765792653100465, 'weight_xgb_class_0': 0.9685294648864076, 'weight_xgb_class_1': 0.6855262388566784, 'weight_xgb_class_2': 0.49999400544364725}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:13,723] Trial 1432 finished with value: 0.9497040453059747 and parameters: {'weight_lgbm_class_0': 0.08442759605731436, 'weight_lgbm_class_1': 0.9989699049614802, 'weight_lgbm_class_2': 0.5149441596685984, 'weight_xgb_class_0': 0.00029944913387740073, 'weight_xgb_class_1': 0.6796201961515557, 'weight_xgb_class_2': 0.511472371555091}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  72%|█████████████████████████████████████████████████████████████████████████████████████████████▌                                    | 1440/2000 [00:42<00:21, 26.51it/s]

[I 2026-07-05 15:32:13,760] Trial 1433 finished with value: 0.9496078778431939 and parameters: {'weight_lgbm_class_0': 0.08252490253443391, 'weight_lgbm_class_1': 0.9995703862103756, 'weight_lgbm_class_2': 0.48436728322903744, 'weight_xgb_class_0': 0.03932650319800936, 'weight_xgb_class_1': 0.6770821501672325, 'weight_xgb_class_2': 0.5191239147011247}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:13,780] Trial 1434 finished with value: 0.9495886554578316 and parameters: {'weight_lgbm_class_0': 0.08271341759734052, 'weight_lgbm_class_1': 0.9818197882521478, 'weight_lgbm_class_2': 0.5117846972140138, 'weight_xgb_class_0': 0.04047815548502946, 'weight_xgb_class_1': 0.6778304575577462, 'weight_xgb_class_2': 0.5045720051017342}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:13,832] Trial 1435 finished with value: 0.9492927598333619 and parameters: {'weight_lgbm_class_0': 0.0839028222751388, 'weight_lgbm_class_1': 0.9826950049721118, 'weight_lgbm_class_2': 0.4266476573158425, 'weight_xgb_class_0': 0.04274575497871458, 'weight_xgb_class_1': 0.6793514039900249, 'weight_xgb_class_2': 0.49599659546876645}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:13,858] Trial 1437 finished with value: 0.9496023611423303 and parameters: {'weight_lgbm_class_0': 0.08395756095265737, 'weight_lgbm_class_1': 0.9375450215955533, 'weight_lgbm_class_2': 0.4232867330577694, 'weight_xgb_class_0': 0.03918586616786883, 'weight_xgb_class_1': 0.728625848069494, 'weight_xgb_class_2': 0.5779764357448769}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:13,875] Trial 1438 finished with value: 0.9491874222722129 and parameters: {'weight_lgbm_class_0': 0.08436667767960072, 'weight_lgbm_class_1': 0.935858550851209, 'weight_lgbm_class_2': 0.42308855766653436, 'weight_xgb_class_0': 0.0406293347592025, 'weight_xgb_class_1': 0.0794190136725848, 'weight_xgb_class_2': 0.5817650191820107}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:13,895] Trial 1436 finished with value: 0.9487182734706058 and parameters: {'weight_lgbm_class_0': 0.12388399814387754, 'weight_lgbm_class_1': 0.998878354449689, 'weight_lgbm_class_2': 0.4219557789541867, 'weight_xgb_class_0': 0.040442741776259505, 'weight_xgb_class_1': 0.6434452946491684, 'weight_xgb_class_2': 0.5780467599895855}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:13,909] Trial 1439 finished with value: 0.9488078891001633 and parameters: {'weight_lgbm_class_0': 0.1227418226851043, 'weight_lgbm_class_1': 0.9989337694245051, 'weight_lgbm_class_2': 0.4241173446674559, 'weight_xgb_class_0': 0.03752658171482315, 'weight_xgb_class_1': 0.6398924729676992, 'weight_xgb_class_2': 0.5743087506148725}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:13,951] Trial 1440 finished with value: 0.8911033248906772 and parameters: {'weight_lgbm_class_0': 0.9993985109719298, 'weight_lgbm_class_1': 0.9405691862622775, 'weight_lgbm_class_2': 0.42443422045037726, 'weight_xgb_class_0': 0.03537177750584424, 'weight_xgb_class_1': 0.6431480791533577, 'weight_xgb_class_2': 0.5809115916798181}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  72%|█████████████████████████████████████████████████████████████████████████████████████████████▊                                    | 1444/2000 [00:42<00:18, 30.16it/s]

[I 2026-07-05 15:32:14,001] Trial 1441 finished with value: 0.9496768943421398 and parameters: {'weight_lgbm_class_0': 0.11960485534177831, 'weight_lgbm_class_1': 0.9360484159745267, 'weight_lgbm_class_2': 0.42604695256988206, 'weight_xgb_class_0': 0.0004385484283877263, 'weight_xgb_class_1': 0.646503230951967, 'weight_xgb_class_2': 0.578892494466024}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:14,006] Trial 1442 finished with value: 0.9497172939162436 and parameters: {'weight_lgbm_class_0': 0.11735049682377109, 'weight_lgbm_class_1': 0.9415494351594867, 'weight_lgbm_class_2': 0.42086354643945545, 'weight_xgb_class_0': 0.0003319976041272892, 'weight_xgb_class_1': 0.6414372681510053, 'weight_xgb_class_2': 0.5790076921539696}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:14,089] Trial 1443 finished with value: 0.9371244289932656 and parameters: {'weight_lgbm_class_0': 0.3489488370438584, 'weight_lgbm_class_1': 0.942368183835097, 'weight_lgbm_class_2': 0.41858073845082133, 'weight_xgb_class_0': 0.03650629871093898, 'weight_xgb_class_1': 0.6389350186143992, 'weight_xgb_class_2': 0.5681823616694771}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:14,151] Trial 1444 finished with value: 0.9489056004368676 and parameters: {'weight_lgbm_class_0': 0.11632530592711691, 'weight_lgbm_class_1': 0.9386648807942436, 'weight_lgbm_class_2': 0.42364239747715066, 'weight_xgb_class_0': 0.03608934665112798, 'weight_xgb_class_1': 0.6415071025686554, 'weight_xgb_class_2': 0.5750628217790186}. Best is trial 1206 with value: 0.9498581274668642.

[I 2026-07-05 15:32:14,213] Trial 1446 finished with value: 0.9489753423952415 and parameters: {'weight_lgbm_class_0': 0.12614525829755063, 'weight_lgbm_class_1': 0.9386794178806347, 'weight_lgbm_class_2': 0.45512883769275736, 'weight_xgb_class_0': 0.024359404446543578, 'weight_xgb_class_1': 0.6411960089720342, 'weight_xgb_class_2': 0.5806050741432972}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:14,234] Trial 1445 finished with value: 0.9488831234983367 and parameters: {'weight_lgbm_class_0': 0.12377370222430502, 'weight_lgbm_class_1': 0.9353251943717728, 'weight_lgbm_class_2': 0.42807981907916043, 'weight_xgb_class_0': 0.028976845169330086, 'weight_xgb_class_1': 0.6420655477323692, 'weight_xgb_class_2': 0.5805872206892789}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:14,320] Trial 1447 finished with value: 0.9494297751444628 and parameters: {'weight_lgbm_class_0': 0.1290723809408118, 'weight_lgbm_class_1': 0.9359503832703452, 'weight_lgbm_class_2': 0.42571820261762383, 'weight_xgb_class_0': 4.5560388668029934e-05, 'weight_xgb_class_1': 0.6481454199575301, 'weight_xgb_class_2': 0.5757779355790109}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:14,327] Trial 1448 finished with value: 0.9494948410215995 and parameters: {'weight_lgbm_class_0': 0.1275262004315266, 'weight_lgbm_class_1': 0.9651809230518499, 'weight_lgbm_class_2': 0.45390167438083034, 'weight_xgb_class_0': 0.00027221028003921247, 'weight_xgb_class_1': 0.7329518603888661, 'weight_xgb_class_2': 0.5525998284433309}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:14,329] Trial 1449 finished with value: 0.9496197135352419 and parameters: {'weight_lgbm_class_0': 0.12221617816807986, 'weight_lgbm_class_1': 0.9662200051646324, 'weight_lgbm_class_2': 0.4567026652990871, 'weight_xgb_class_0': 0.0003908488997237576, 'weight_xgb_class_1': 0.7284930407539187, 'weight_xgb_class_2': 0.5544658649379229}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:14,356] Trial 1450 finished with value: 0.9490976276141749 and parameters: {'weight_lgbm_class_0': 0.12686893830856116, 'weight_lgbm_class_1': 0.9623279699925144, 'weight_lgbm_class_2': 0.45533085565503234, 'weight_xgb_class_0': 0.020814630174083804, 'weight_xgb_class_1': 0.7252216962439745, 'weight_xgb_class_2': 0.5561725602876236}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  73%|██████████████████████████████████████████████████████████████████████████████████████████████▋                                   | 1456/2000 [00:43<00:20, 26.51it/s]

[I 2026-07-05 15:32:14,399] Trial 1451 finished with value: 0.9486746877135181 and parameters: {'weight_lgbm_class_0': 0.12390056067308895, 'weight_lgbm_class_1': 0.9634335656261542, 'weight_lgbm_class_2': 0.14939283673914955, 'weight_xgb_class_0': 0.0002623545958923137, 'weight_xgb_class_1': 0.7240568008318615, 'weight_xgb_class_2': 0.5524462684134078}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:14,417] Trial 1452 finished with value: 0.9495743840513287 and parameters: {'weight_lgbm_class_0': 0.1251294226101922, 'weight_lgbm_class_1': 0.9625321279654151, 'weight_lgbm_class_2': 0.4634344294480931, 'weight_xgb_class_0': 0.000988045881666363, 'weight_xgb_class_1': 0.7221843954160293, 'weight_xgb_class_2': 0.5549297319254819}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:14,468] Trial 1453 finished with value: 0.9491563432049425 and parameters: {'weight_lgbm_class_0': 0.12088609326827071, 'weight_lgbm_class_1': 0.963836348285735, 'weight_lgbm_class_2': 0.4608413139838389, 'weight_xgb_class_0': 0.022921536770335697, 'weight_xgb_class_1': 0.7264409545290528, 'weight_xgb_class_2': 0.5477347534036434}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:14,469] Trial 1454 finished with value: 0.9491501553750537 and parameters: {'weight_lgbm_class_0': 0.12399063972675849, 'weight_lgbm_class_1': 0.9650368831343882, 'weight_lgbm_class_2': 0.45645834384494277, 'weight_xgb_class_0': 0.019710268761263004, 'weight_xgb_class_1': 0.7240612953444538, 'weight_xgb_class_2': 0.552698421493311}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:14,584] Trial 1455 finished with value: 0.9490490253298965 and parameters: {'weight_lgbm_class_0': 0.12803178226990242, 'weight_lgbm_class_1': 0.9667255566850094, 'weight_lgbm_class_2': 0.4541444261286129, 'weight_xgb_class_0': 0.020902936224167383, 'weight_xgb_class_1': 0.724331101389628, 'weight_xgb_class_2': 0.5544881585245569}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:14,586] Trial 1456 finished with value: 0.9479208632247272 and parameters: {'weight_lgbm_class_0': 0.12466837496067916, 'weight_lgbm_class_1': 0.9675996919917795, 'weight_lgbm_class_2': 0.12401327173784116, 'weight_xgb_class_0': 0.020743939050487326, 'weight_xgb_class_1': 0.7329596839674027, 'weight_xgb_class_2': 0.5572875303586017}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  73%|██████████████████████████████████████████████████████████████████████████████████████████████▉                                   | 1460/2000 [00:43<00:21, 25.70it/s]

[I 2026-07-05 15:32:14,657] Trial 1457 finished with value: 0.9492914106439878 and parameters: {'weight_lgbm_class_0': 0.13675213614358375, 'weight_lgbm_class_1': 0.9656975453378938, 'weight_lgbm_class_2': 0.4565950942525755, 'weight_xgb_class_0': 0.0003424124728818277, 'weight_xgb_class_1': 0.7325431103788465, 'weight_xgb_class_2': 0.5553913672572872}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:14,707] Trial 1458 finished with value: 0.9498140711227802 and parameters: {'weight_lgbm_class_0': 0.10937901995908787, 'weight_lgbm_class_1': 0.9617300914156267, 'weight_lgbm_class_2': 0.4551425994295209, 'weight_xgb_class_0': 0.0005382833968986023, 'weight_xgb_class_1': 0.7233683107434833, 'weight_xgb_class_2': 0.5452932388735302}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:14,802] Trial 1459 finished with value: 0.949449926016286 and parameters: {'weight_lgbm_class_0': 0.10531452095444185, 'weight_lgbm_class_1': 0.9645607171308039, 'weight_lgbm_class_2': 0.4464742118015444, 'weight_xgb_class_0': 0.019329851717551527, 'weight_xgb_class_1': 0.47282646038223813, 'weight_xgb_class_2': 0.5513464830865269}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:14,831] Trial 1461 finished with value: 0.9492474545077164 and parameters: {'weight_lgbm_class_0': 0.10746016550953866, 'weight_lgbm_class_1': 0.9681141022778935, 'weight_lgbm_class_2': 0.3982296270845908, 'weight_xgb_class_0': 0.02326214759729206, 'weight_xgb_class_1': 0.7133677107534295, 'weight_xgb_class_2': 0.5494846053837364}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  73%|███████████████████████████████████████████████████████████████████████████████████████████████▍                                  | 1468/2000 [00:43<00:19, 27.34it/s]

[I 2026-07-05 15:32:14,831] Trial 1460 finished with value: 0.9493943169321494 and parameters: {'weight_lgbm_class_0': 0.10550512325030821, 'weight_lgbm_class_1': 0.9666499579780977, 'weight_lgbm_class_2': 0.39779338299024186, 'weight_xgb_class_0': 0.020676567812839736, 'weight_xgb_class_1': 0.7139405367150732, 'weight_xgb_class_2': 0.5564416447674565}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:14,873] Trial 1462 finished with value: 0.9182710222050346 and parameters: {'weight_lgbm_class_0': 0.10224195695084229, 'weight_lgbm_class_1': 0.9778260353393204, 'weight_lgbm_class_2': 0.395382997231416, 'weight_xgb_class_0': 0.5196849266187618, 'weight_xgb_class_1': 0.7156667814182467, 'weight_xgb_class_2': 0.5426197958651268}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:14,894] Trial 1463 finished with value: 0.9494000777084078 and parameters: {'weight_lgbm_class_0': 0.10434539383287618, 'weight_lgbm_class_1': 0.980859372652149, 'weight_lgbm_class_2': 0.39279185728734434, 'weight_xgb_class_0': 0.02060035445655773, 'weight_xgb_class_1': 0.7438372261451085, 'weight_xgb_class_2': 0.5485905086766776}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:14,947] Trial 1466 finished with value: 0.9482368114224572 and parameters: {'weight_lgbm_class_0': 0.10273923713241437, 'weight_lgbm_class_1': 0.9805264049245099, 'weight_lgbm_class_2': 0.39953638548810244, 'weight_xgb_class_0': 0.021111912456030862, 'weight_xgb_class_1': 0.700968145132309, 'weight_xgb_class_2': 0.2446897263070223}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:14,955] Trial 1465 finished with value: 0.9495553015601864 and parameters: {'weight_lgbm_class_0': 0.10230478819905532, 'weight_lgbm_class_1': 0.9774232637667503, 'weight_lgbm_class_2': 0.3970713549731851, 'weight_xgb_class_0': 0.024117226216626327, 'weight_xgb_class_1': 0.7423526327984922, 'weight_xgb_class_2': 0.6060529059827351}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:14,973] Trial 1464 finished with value: 0.9496257399289029 and parameters: {'weight_lgbm_class_0': 0.1026313870380957, 'weight_lgbm_class_1': 0.9792001626680468, 'weight_lgbm_class_2': 0.40299006838620943, 'weight_xgb_class_0': 0.02114606876661173, 'weight_xgb_class_1': 0.7422963555059525, 'weight_xgb_class_2': 0.6117524697263035}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:15,048] Trial 1468 finished with value: 0.9497896077772952 and parameters: {'weight_lgbm_class_0': 0.08877989165631497, 'weight_lgbm_class_1': 0.9790307786068935, 'weight_lgbm_class_2': 0.4034086572092754, 'weight_xgb_class_0': 0.018335645392069652, 'weight_xgb_class_1': 0.6952348124163165, 'weight_xgb_class_2': 0.6080010801981485}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:15,067] Trial 1467 finished with value: 0.9495001764381792 and parameters: {'weight_lgbm_class_0': 0.09719450537837362, 'weight_lgbm_class_1': 0.9798076246069644, 'weight_lgbm_class_2': 0.3972211927469045, 'weight_xgb_class_0': 0.02312118196003228, 'weight_xgb_class_1': 0.22564624958359436, 'weight_xgb_class_2': 0.6092526934784519}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  74%|███████████████████████████████████████████████████████████████████████████████████████████████▌                                  | 1471/2000 [00:43<00:19, 27.70it/s]

[I 2026-07-05 15:32:15,083] Trial 1469 finished with value: 0.9495729616342631 and parameters: {'weight_lgbm_class_0': 0.0973729758178771, 'weight_lgbm_class_1': 0.9814845733796583, 'weight_lgbm_class_2': 0.39977840854703206, 'weight_xgb_class_0': 0.02350489398120939, 'weight_xgb_class_1': 0.4618204467099769, 'weight_xgb_class_2': 0.6127777653020743}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:15,141] Trial 1470 finished with value: 0.9497989233141205 and parameters: {'weight_lgbm_class_0': 0.0853636712244393, 'weight_lgbm_class_1': 0.9812479851421413, 'weight_lgbm_class_2': 0.3981931131506433, 'weight_xgb_class_0': 0.020385696056794474, 'weight_xgb_class_1': 0.6993880746537867, 'weight_xgb_class_2': 0.6134998790791895}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  74%|████████████████████████████████████████████████████████████████████████████████████████████████                                  | 1478/2000 [00:44<00:21, 24.10it/s]

[I 2026-07-05 15:32:15,332] Trial 1472 finished with value: 0.9495518074522803 and parameters: {'weight_lgbm_class_0': 0.08166263258320224, 'weight_lgbm_class_1': 0.9829497819403433, 'weight_lgbm_class_2': 0.3984455478863664, 'weight_xgb_class_0': 0.045687216397692465, 'weight_xgb_class_1': 0.697465720287085, 'weight_xgb_class_2': 0.6082004969529418}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:15,341] Trial 1471 finished with value: 0.9492839319000309 and parameters: {'weight_lgbm_class_0': 0.08845190666573499, 'weight_lgbm_class_1': 0.9790807807741798, 'weight_lgbm_class_2': 0.3948636507841237, 'weight_xgb_class_0': 0.048068165220942566, 'weight_xgb_class_1': 0.7000315405404289, 'weight_xgb_class_2': 0.6146480246225564}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:15,362] Trial 1474 finished with value: 0.9497660107106283 and parameters: {'weight_lgbm_class_0': 0.0777394106974337, 'weight_lgbm_class_1': 0.9986816618601136, 'weight_lgbm_class_2': 0.4367617844784554, 'weight_xgb_class_0': 0.04337138522597375, 'weight_xgb_class_1': 0.6905346489636974, 'weight_xgb_class_2': 0.6133284845326363}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:15,380] Trial 1473 finished with value: 0.9494670721901505 and parameters: {'weight_lgbm_class_0': 0.08286846041325474, 'weight_lgbm_class_1': 0.982905677310173, 'weight_lgbm_class_2': 0.40559205880101573, 'weight_xgb_class_0': 0.04720488141134184, 'weight_xgb_class_1': 0.6997970408437477, 'weight_xgb_class_2': 0.6108439932053402}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:15,389] Trial 1475 finished with value: 0.9497539182576445 and parameters: {'weight_lgbm_class_0': 0.079540030903691, 'weight_lgbm_class_1': 0.9819141239639729, 'weight_lgbm_class_2': 0.5164839693850891, 'weight_xgb_class_0': 0.022901342693772676, 'weight_xgb_class_1': 0.6923297083666987, 'weight_xgb_class_2': 0.6154677135922332}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:15,412] Trial 1476 finished with value: 0.9490820392309388 and parameters: {'weight_lgbm_class_0': 0.08955259394672047, 'weight_lgbm_class_1': 0.9834430003336807, 'weight_lgbm_class_2': 0.4344947870556445, 'weight_xgb_class_0': 0.05070522942006019, 'weight_xgb_class_1': 0.700577121868632, 'weight_xgb_class_2': 0.5165170006394811}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:15,449] Trial 1477 finished with value: 0.9493833302509503 and parameters: {'weight_lgbm_class_0': 0.07978256881252228, 'weight_lgbm_class_1': 0.9986311490665079, 'weight_lgbm_class_2': 0.4411282999827676, 'weight_xgb_class_0': 0.04733795349345973, 'weight_xgb_class_1': 0.6977799896095779, 'weight_xgb_class_2': 0.5208244063055424}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:15,482] Trial 1478 finished with value: 0.94930909906014 and parameters: {'weight_lgbm_class_0': 0.0815129358158439, 'weight_lgbm_class_1': 0.9814735507723558, 'weight_lgbm_class_2': 0.43535212502685044, 'weight_xgb_class_0': 0.04762562022291457, 'weight_xgb_class_1': 0.6957085949243116, 'weight_xgb_class_2': 0.5226364369858618}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  74%|████████████████████████████████████████████████████████████████████████████████████████████████▍                                 | 1483/2000 [00:44<00:19, 27.15it/s]

[I 2026-07-05 15:32:15,522] Trial 1479 finished with value: 0.9480935735505108 and parameters: {'weight_lgbm_class_0': 0.15269140104043963, 'weight_lgbm_class_1': 0.9838780281586482, 'weight_lgbm_class_2': 0.43767553844694, 'weight_xgb_class_0': 0.04739146547488536, 'weight_xgb_class_1': 0.6961531777329432, 'weight_xgb_class_2': 0.5922467712205453}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:15,541] Trial 1480 finished with value: 0.9481711633728677 and parameters: {'weight_lgbm_class_0': 0.14821783831395358, 'weight_lgbm_class_1': 0.9497889232125237, 'weight_lgbm_class_2': 0.5138284329218651, 'weight_xgb_class_0': 0.04529128830520078, 'weight_xgb_class_1': 0.6919811843058284, 'weight_xgb_class_2': 0.5130416344783933}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:15,563] Trial 1481 finished with value: 0.9477049661520961 and parameters: {'weight_lgbm_class_0': 0.14998321403833118, 'weight_lgbm_class_1': 0.9488717463755073, 'weight_lgbm_class_2': 0.43535142070085275, 'weight_xgb_class_0': 0.04722144832604469, 'weight_xgb_class_1': 0.6942586879830003, 'weight_xgb_class_2': 0.5113182092097746}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:15,583] Trial 1482 finished with value: 0.9496907767854128 and parameters: {'weight_lgbm_class_0': 0.07516975689562666, 'weight_lgbm_class_1': 0.9437613025124334, 'weight_lgbm_class_2': 0.5234328375240659, 'weight_xgb_class_0': 0.04609288265151198, 'weight_xgb_class_1': 0.6911245930682979, 'weight_xgb_class_2': 0.5176320304311607}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:15,738] Trial 1483 finished with value: 0.9495949942922198 and parameters: {'weight_lgbm_class_0': 0.07762884405622032, 'weight_lgbm_class_1': 0.9483699224832837, 'weight_lgbm_class_2': 0.5207672696314549, 'weight_xgb_class_0': 0.04741784624649011, 'weight_xgb_class_1': 0.6896573236044978, 'weight_xgb_class_2': 0.5143618034780991}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  74%|████████████████████████████████████████████████████████████████████████████████████████████████▊                                 | 1489/2000 [00:44<00:21, 23.85it/s]

[I 2026-07-05 15:32:15,789] Trial 1484 finished with value: 0.9476068150839344 and parameters: {'weight_lgbm_class_0': 0.15126590835853865, 'weight_lgbm_class_1': 0.9452462266308973, 'weight_lgbm_class_2': 0.4409900689682294, 'weight_xgb_class_0': 0.0494495997389042, 'weight_xgb_class_1': 0.6618982796791425, 'weight_xgb_class_2': 0.5226472363772257}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:15,847] Trial 1486 finished with value: 0.9120244000847987 and parameters: {'weight_lgbm_class_0': 0.7115331130435748, 'weight_lgbm_class_1': 0.9495363496707468, 'weight_lgbm_class_2': 0.47275371051421694, 'weight_xgb_class_0': 0.0001371170181948043, 'weight_xgb_class_1': 0.747847663164479, 'weight_xgb_class_2': 0.48903223987855854}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:15,868] Trial 1485 finished with value: 0.9095983141984845 and parameters: {'weight_lgbm_class_0': 0.7030353760194303, 'weight_lgbm_class_1': 0.9482329162112985, 'weight_lgbm_class_2': 0.47510669807359474, 'weight_xgb_class_0': 0.04580919284381911, 'weight_xgb_class_1': 0.6606399852794296, 'weight_xgb_class_2': 0.5226471398571989}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:15,899] Trial 1487 finished with value: 0.9471829384653097 and parameters: {'weight_lgbm_class_0': 0.1559729468611663, 'weight_lgbm_class_1': 0.9994781326358204, 'weight_lgbm_class_2': 0.4273279913873191, 'weight_xgb_class_0': 0.046292044566937224, 'weight_xgb_class_1': 0.6641552791750188, 'weight_xgb_class_2': 0.4789264914310257}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:15,929] Trial 1488 finished with value: 0.9475077189809191 and parameters: {'weight_lgbm_class_0': 0.15068074058609654, 'weight_lgbm_class_1': 0.9507613249817438, 'weight_lgbm_class_2': 0.4209316362155296, 'weight_xgb_class_0': 0.04541859909834536, 'weight_xgb_class_1': 0.6614742121522696, 'weight_xgb_class_2': 0.49702109046151177}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:15,989] Trial 1489 finished with value: 0.948692458763985 and parameters: {'weight_lgbm_class_0': 0.13864153515588445, 'weight_lgbm_class_1': 0.9432354384404444, 'weight_lgbm_class_2': 0.47625556196382807, 'weight_xgb_class_0': 0.018192663390220284, 'weight_xgb_class_1': 0.6624100237191878, 'weight_xgb_class_2': 0.48408845097937525}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  75%|█████████████████████████████████████████████████████████████████████████████████████████████████▏                                | 1495/2000 [00:44<00:18, 27.49it/s]

[I 2026-07-05 15:32:15,995] Trial 1490 finished with value: 0.9486734440624209 and parameters: {'weight_lgbm_class_0': 0.1525953056949301, 'weight_lgbm_class_1': 0.9461684605921515, 'weight_lgbm_class_2': 0.4184203723527133, 'weight_xgb_class_0': 0.00028747384387324006, 'weight_xgb_class_1': 0.6644484575373159, 'weight_xgb_class_2': 0.4985966403751988}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:16,035] Trial 1491 finished with value: 0.9487150771927432 and parameters: {'weight_lgbm_class_0': 0.1403738354922115, 'weight_lgbm_class_1': 0.9523664476612679, 'weight_lgbm_class_2': 0.4740698664952764, 'weight_xgb_class_0': 0.017776493634144984, 'weight_xgb_class_1': 0.7516433303859114, 'weight_xgb_class_2': 0.4912430801272397}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:16,062] Trial 1494 finished with value: 0.9449639589183633 and parameters: {'weight_lgbm_class_0': 0.14401312837943148, 'weight_lgbm_class_1': 0.9990005032522508, 'weight_lgbm_class_2': 0.4733766462320014, 'weight_xgb_class_0': 0.0008439894325386163, 'weight_xgb_class_1': 0.6622473465543837, 'weight_xgb_class_2': 0.04757427836099132}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:16,064] Trial 1492 finished with value: 0.911044758647597 and parameters: {'weight_lgbm_class_0': 0.7317215313448471, 'weight_lgbm_class_1': 0.9525045818310565, 'weight_lgbm_class_2': 0.4208524338915568, 'weight_xgb_class_0': 0.01978408465297533, 'weight_xgb_class_1': 0.7505068753088432, 'weight_xgb_class_2': 0.5916107961632939}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:16,092] Trial 1493 finished with value: 0.9485994663584808 and parameters: {'weight_lgbm_class_0': 0.14610513222943816, 'weight_lgbm_class_1': 0.9990993121069787, 'weight_lgbm_class_2': 0.4780280324699394, 'weight_xgb_class_0': 0.01930045165738802, 'weight_xgb_class_1': 0.6595819550405819, 'weight_xgb_class_2': 0.49474107381159377}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:16,172] Trial 1495 finished with value: 0.9485923766805505 and parameters: {'weight_lgbm_class_0': 0.14683623341895746, 'weight_lgbm_class_1': 0.9984846163730186, 'weight_lgbm_class_2': 0.47490568852054765, 'weight_xgb_class_0': 0.020172405214788892, 'weight_xgb_class_1': 0.6643553610810704, 'weight_xgb_class_2': 0.49184690670568443}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  75%|█████████████████████████████████████████████████████████████████████████████████████████████████▋                                | 1502/2000 [00:45<00:19, 25.01it/s]

[I 2026-07-05 15:32:16,275] Trial 1496 finished with value: 0.9487410829319729 and parameters: {'weight_lgbm_class_0': 0.13982328978414854, 'weight_lgbm_class_1': 0.9998946660243783, 'weight_lgbm_class_2': 0.47081378446063304, 'weight_xgb_class_0': 0.017361796450173383, 'weight_xgb_class_1': 0.7507098430777809, 'weight_xgb_class_2': 0.4899035006579576}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:16,276] Trial 1497 finished with value: 0.9175417245521363 and parameters: {'weight_lgbm_class_0': 0.19310253191686, 'weight_lgbm_class_1': 0.960994284878564, 'weight_lgbm_class_2': 0.4224060165860996, 'weight_xgb_class_0': 0.4741657570862551, 'weight_xgb_class_1': 0.7530015060713955, 'weight_xgb_class_2': 0.5884697259030451}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:16,348] Trial 1498 finished with value: 0.947461042923892 and parameters: {'weight_lgbm_class_0': 0.19684391045685457, 'weight_lgbm_class_1': 0.960056970719285, 'weight_lgbm_class_2': 0.41520365967203077, 'weight_xgb_class_0': 0.019030923241269194, 'weight_xgb_class_1': 0.7460402414818696, 'weight_xgb_class_2': 0.5914955934858627}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:16,363] Trial 1499 finished with value: 0.947953941849737 and parameters: {'weight_lgbm_class_0': 0.1940853572654084, 'weight_lgbm_class_1': 0.9996039334891693, 'weight_lgbm_class_2': 0.5563111796773376, 'weight_xgb_class_0': 0.024158475206016695, 'weight_xgb_class_1': 0.7432587028518, 'weight_xgb_class_2': 0.5902719431333229}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:16,395] Trial 1500 finished with value: 0.9497896551146033 and parameters: {'weight_lgbm_class_0': 0.10505297651647594, 'weight_lgbm_class_1': 0.9324469321878001, 'weight_lgbm_class_2': 0.47257236694326754, 'weight_xgb_class_0': 0.016511632337230225, 'weight_xgb_class_1': 0.7497881381665081, 'weight_xgb_class_2': 0.5932687943553354}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:16,451] Trial 1501 finished with value: 0.9497660173002506 and parameters: {'weight_lgbm_class_0': 0.10917893870833578, 'weight_lgbm_class_1': 0.9998187590474643, 'weight_lgbm_class_2': 0.5691936635176119, 'weight_xgb_class_0': 0.0187688000116965, 'weight_xgb_class_1': 0.7160590592598477, 'weight_xgb_class_2': 0.5916719703009277}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  75%|█████████████████████████████████████████████████████████████████████████████████████████████████▉                                | 1507/2000 [00:45<00:19, 25.66it/s]

[I 2026-07-05 15:32:16,510] Trial 1502 finished with value: 0.949808848409854 and parameters: {'weight_lgbm_class_0': 0.10670147429386367, 'weight_lgbm_class_1': 0.9656868805567382, 'weight_lgbm_class_2': 0.4158023691392817, 'weight_xgb_class_0': 0.0006342601190300072, 'weight_xgb_class_1': 0.7129230063029248, 'weight_xgb_class_2': 0.5931083752661086}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:16,537] Trial 1503 finished with value: 0.9494679934084381 and parameters: {'weight_lgbm_class_0': 0.10744374495403865, 'weight_lgbm_class_1': 0.9983024409611383, 'weight_lgbm_class_2': 0.4170963686090745, 'weight_xgb_class_0': 0.023486359081098855, 'weight_xgb_class_1': 0.7155871619909885, 'weight_xgb_class_2': 0.5898461361528321}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:16,563] Trial 1504 finished with value: 0.9481666642559983 and parameters: {'weight_lgbm_class_0': 0.192545603347061, 'weight_lgbm_class_1': 0.9695124611093081, 'weight_lgbm_class_2': 0.4135460161133491, 'weight_xgb_class_0': 0.0008841425536519982, 'weight_xgb_class_1': 0.717235802455, 'weight_xgb_class_2': 0.5847821979983098}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:16,566] Trial 1506 finished with value: 0.9494378311652018 and parameters: {'weight_lgbm_class_0': 0.11113668591386322, 'weight_lgbm_class_1': 0.9688304301420431, 'weight_lgbm_class_2': 0.41683811917412195, 'weight_xgb_class_0': 0.018940101300063836, 'weight_xgb_class_1': 0.7153028163501204, 'weight_xgb_class_2': 0.5892392588724119}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:16,594] Trial 1505 finished with value: 0.9498423756068948 and parameters: {'weight_lgbm_class_0': 0.11114003383513588, 'weight_lgbm_class_1': 0.9682498083417628, 'weight_lgbm_class_2': 0.4164623233580786, 'weight_xgb_class_0': 0.000567489522913938, 'weight_xgb_class_1': 0.7136954814352942, 'weight_xgb_class_2': 0.5909726458674893}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:16,605] Trial 1507 finished with value: 0.8986371253518346 and parameters: {'weight_lgbm_class_0': 0.8994404290520235, 'weight_lgbm_class_1': 0.9656257253896104, 'weight_lgbm_class_2': 0.41546895573423986, 'weight_xgb_class_0': 0.019787216458162518, 'weight_xgb_class_1': 0.7099189206204901, 'weight_xgb_class_2': 0.5684103170309093}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  76%|██████████████████████████████████████████████████████████████████████████████████████████████████▎                               | 1512/2000 [00:45<00:20, 23.83it/s]

[I 2026-07-05 15:32:16,744] Trial 1508 finished with value: 0.9498427194456037 and parameters: {'weight_lgbm_class_0': 0.1097845428479265, 'weight_lgbm_class_1': 0.9293167949813432, 'weight_lgbm_class_2': 0.41427014854349875, 'weight_xgb_class_0': 0.00016802154741636104, 'weight_xgb_class_1': 0.7140421566064514, 'weight_xgb_class_2': 0.5684735449503132}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:16,773] Trial 1509 finished with value: 0.9374691000701532 and parameters: {'weight_lgbm_class_0': 0.39513371488689875, 'weight_lgbm_class_1': 0.9693379098152686, 'weight_lgbm_class_2': 0.4465895277610331, 'weight_xgb_class_0': 0.0006740825342318997, 'weight_xgb_class_1': 0.7170485577308326, 'weight_xgb_class_2': 0.5696731577183768}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:16,789] Trial 1510 finished with value: 0.9497983158652029 and parameters: {'weight_lgbm_class_0': 0.10904256398528445, 'weight_lgbm_class_1': 0.9309055818670506, 'weight_lgbm_class_2': 0.45008719618769744, 'weight_xgb_class_0': 0.0018302689486269428, 'weight_xgb_class_1': 0.7159906663269434, 'weight_xgb_class_2': 0.573377235005082}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:16,901] Trial 1511 finished with value: 0.9492160301321334 and parameters: {'weight_lgbm_class_0': 0.1080181214584631, 'weight_lgbm_class_1': 0.9684333356807824, 'weight_lgbm_class_2': 0.4441626413654242, 'weight_xgb_class_0': 0.03204570639190832, 'weight_xgb_class_1': 0.720894545368737, 'weight_xgb_class_2': 0.5653359421866614}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:16,909] Trial 1512 finished with value: 0.9497961455625572 and parameters: {'weight_lgbm_class_0': 0.10734659320601649, 'weight_lgbm_class_1': 0.9655644186467881, 'weight_lgbm_class_2': 0.44304832392770965, 'weight_xgb_class_0': 0.001546233050292854, 'weight_xgb_class_1': 0.7201590516700602, 'weight_xgb_class_2': 0.5676019347638136}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  76%|██████████████████████████████████████████████████████████████████████████████████████████████████▌                               | 1517/2000 [00:45<00:22, 21.51it/s]

[I 2026-07-05 15:32:16,967] Trial 1513 finished with value: 0.949413234857286 and parameters: {'weight_lgbm_class_0': 0.08351189531941511, 'weight_lgbm_class_1': 0.968477911394485, 'weight_lgbm_class_2': 0.8315363526052404, 'weight_xgb_class_0': 0.0006317038801406086, 'weight_xgb_class_1': 0.7209296402453806, 'weight_xgb_class_2': 0.5713675557124452}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:17,047] Trial 1514 finished with value: 0.9497103066178876 and parameters: {'weight_lgbm_class_0': 0.08649320777964747, 'weight_lgbm_class_1': 0.9318558302394275, 'weight_lgbm_class_2': 0.4513187577261513, 'weight_xgb_class_0': 0.03384327840809645, 'weight_xgb_class_1': 0.7191637289588081, 'weight_xgb_class_2': 0.5657382803792046}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:17,062] Trial 1515 finished with value: 0.949584589791653 and parameters: {'weight_lgbm_class_0': 0.07721958226846169, 'weight_lgbm_class_1': 0.9314563351887908, 'weight_lgbm_class_2': 0.44720771686408345, 'weight_xgb_class_0': 0.0007547626105889049, 'weight_xgb_class_1': 0.7174514857249007, 'weight_xgb_class_2': 0.5657603225396467}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:17,144] Trial 1516 finished with value: 0.9497791190695479 and parameters: {'weight_lgbm_class_0': 0.08183653062722658, 'weight_lgbm_class_1': 0.929993354632343, 'weight_lgbm_class_2': 0.43815705111055225, 'weight_xgb_class_0': 0.03444552983217623, 'weight_xgb_class_1': 0.7422049823450751, 'weight_xgb_class_2': 0.570612966380845}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:17,166] Trial 1517 finished with value: 0.9495868173493521 and parameters: {'weight_lgbm_class_0': 0.07842011058143628, 'weight_lgbm_class_1': 0.9307690700091821, 'weight_lgbm_class_2': 0.4477846449020716, 'weight_xgb_class_0': 0.0002225037036460848, 'weight_xgb_class_1': 0.7190583048521588, 'weight_xgb_class_2': 0.5717056552460249}. Best is trial 1206 with value: 0.9498581274668642.

[I 2026-07-05 15:32:17,241] Trial 1518 finished with value: 0.9430082602725133 and parameters: {'weight_lgbm_class_0': 0.30606230842414456, 'weight_lgbm_class_1': 0.9291820989855626, 'weight_lgbm_class_2': 0.4417209800990568, 'weight_xgb_class_0': 0.0006444060873032646, 'weight_xgb_class_1': 0.7324575900567483, 'weight_xgb_class_2': 0.5693922174761079}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:17,252] Trial 1519 finished with value: 0.9489963067554997 and parameters: {'weight_lgbm_class_0': 0.0762728627703928, 'weight_lgbm_class_1': 0.9344718488573891, 'weight_lgbm_class_2': 0.989766189308469, 'weight_xgb_class_0': 0.0008043173975242044, 'weight_xgb_class_1': 0.7375680427226599, 'weight_xgb_class_2': 0.5697808713048017}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:17,302] Trial 1520 finished with value: 0.9497579316136457 and parameters: {'weight_lgbm_class_0': 0.07935239012495283, 'weight_lgbm_class_1': 0.9282112010244747, 'weight_lgbm_class_2': 0.448465897650695, 'weight_xgb_class_0': 0.034670137636680476, 'weight_xgb_class_1': 0.7361736319212955, 'weight_xgb_class_2': 0.6226665997644}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:17,334] Trial 1521 finished with value: 0.9495154804891764 and parameters: {'weight_lgbm_class_0': 0.07795340873721934, 'weight_lgbm_class_1': 0.93331466793539, 'weight_lgbm_class_2': 0.4997985745502075, 'weight_xgb_class_0': 0.0001686457764192911, 'weight_xgb_class_1': 0.735496074957902, 'weight_xgb_class_2': 0.6226511188935817}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:17,357] Trial 1522 finished with value: 0.9497663302472473 and parameters: {'weight_lgbm_class_0': 0.0765052596019622, 'weight_lgbm_class_1': 0.9314973662813568, 'weight_lgbm_class_2': 0.45539422000210494, 'weight_xgb_class_0': 0.033751243803491315, 'weight_xgb_class_1': 0.7419885492112224, 'weight_xgb_class_2': 0.6246922368558858}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  76%|███████████████████████████████████████████████████████████████████████████████████████████████████▎                              | 1527/2000 [00:46<00:20, 23.47it/s]

[I 2026-07-05 15:32:17,452] Trial 1523 finished with value: 0.9480786139192948 and parameters: {'weight_lgbm_class_0': 0.17134424240377988, 'weight_lgbm_class_1': 0.9301735967746689, 'weight_lgbm_class_2': 0.4980369906397426, 'weight_xgb_class_0': 0.035862641431440065, 'weight_xgb_class_1': 0.7358484724660546, 'weight_xgb_class_2': 0.6216701080453573}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:17,482] Trial 1525 finished with value: 0.9474185849645954 and parameters: {'weight_lgbm_class_0': 0.16953642383703388, 'weight_lgbm_class_1': 0.9304111849671169, 'weight_lgbm_class_2': 0.44953259588813455, 'weight_xgb_class_0': 0.03388579520669641, 'weight_xgb_class_1': 0.31345756553690707, 'weight_xgb_class_2': 0.6232089177580026}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:17,499] Trial 1524 finished with value: 0.9486682188360315 and parameters: {'weight_lgbm_class_0': 0.16761330010112074, 'weight_lgbm_class_1': 0.9307601587187355, 'weight_lgbm_class_2': 0.3919647214772118, 'weight_xgb_class_0': 1.2743978373052451e-05, 'weight_xgb_class_1': 0.7335155015295148, 'weight_xgb_class_2': 0.6217682337391623}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:17,556] Trial 1527 finished with value: 0.9484625546764072 and parameters: {'weight_lgbm_class_0': 0.13225528487814472, 'weight_lgbm_class_1': 0.9298251716376721, 'weight_lgbm_class_2': 0.3946400157766839, 'weight_xgb_class_0': 0.03242342908168934, 'weight_xgb_class_1': 0.3165038707233261, 'weight_xgb_class_2': 0.6251482319305576}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:17,558] Trial 1526 finished with value: 0.9282720883192596 and parameters: {'weight_lgbm_class_0': 0.13053384015779107, 'weight_lgbm_class_1': 0.9304489916772867, 'weight_lgbm_class_2': 0.39317266432444614, 'weight_xgb_class_0': 0.39297964359249593, 'weight_xgb_class_1': 0.7373963014547933, 'weight_xgb_class_2': 0.6281521368264813}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  77%|███████████████████████████████████████████████████████████████████████████████████████████████████▋                              | 1533/2000 [00:46<00:20, 22.82it/s]

[I 2026-07-05 15:32:17,661] Trial 1529 finished with value: 0.9487951982806021 and parameters: {'weight_lgbm_class_0': 0.12912613890130942, 'weight_lgbm_class_1': 0.9253537019866351, 'weight_lgbm_class_2': 0.38835637309251003, 'weight_xgb_class_0': 0.03333388521626757, 'weight_xgb_class_1': 0.7373573476328209, 'weight_xgb_class_2': 0.626462159977432}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:17,677] Trial 1528 finished with value: 0.9494320191477579 and parameters: {'weight_lgbm_class_0': 0.1323339868906332, 'weight_lgbm_class_1': 0.929983672040256, 'weight_lgbm_class_2': 0.4959833888961937, 'weight_xgb_class_0': 0.0003290379342950873, 'weight_xgb_class_1': 0.7339173008251182, 'weight_xgb_class_2': 0.5406535253649041}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:17,724] Trial 1530 finished with value: 0.9071733095019345 and parameters: {'weight_lgbm_class_0': 0.13092489481317446, 'weight_lgbm_class_1': 0.9347701240121955, 'weight_lgbm_class_2': 0.4972076777601545, 'weight_xgb_class_0': 0.715544834803174, 'weight_xgb_class_1': 0.6816159467888138, 'weight_xgb_class_2': 0.6244540821736868}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:17,768] Trial 1531 finished with value: 0.9484508392458212 and parameters: {'weight_lgbm_class_0': 0.12917713543195483, 'weight_lgbm_class_1': 0.957253164154808, 'weight_lgbm_class_2': 0.3878756397393571, 'weight_xgb_class_0': 0.03800934028261851, 'weight_xgb_class_1': 0.6802522239709329, 'weight_xgb_class_2': 0.5365668749466058}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:17,821] Trial 1532 finished with value: 0.9474466099783644 and parameters: {'weight_lgbm_class_0': 0.17086447421809345, 'weight_lgbm_class_1': 0.9548231620401407, 'weight_lgbm_class_2': 0.3900837898403195, 'weight_xgb_class_0': 0.03203289227039996, 'weight_xgb_class_1': 0.6798435226707674, 'weight_xgb_class_2': 0.5447247166762152}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:17,848] Trial 1533 finished with value: 0.9476724992529038 and parameters: {'weight_lgbm_class_0': 0.1672547206244706, 'weight_lgbm_class_1': 0.9577377192743062, 'weight_lgbm_class_2': 0.3900401488917008, 'weight_xgb_class_0': 0.028543841385240527, 'weight_xgb_class_1': 0.6785952722713027, 'weight_xgb_class_2': 0.5387098690334436}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  77%|████████████████████████████████████████████████████████████████████████████████████████████████████                              | 1539/2000 [00:46<00:18, 24.72it/s]

[I 2026-07-05 15:32:17,906] Trial 1534 finished with value: 0.9474104406089165 and parameters: {'weight_lgbm_class_0': 0.17436471543459547, 'weight_lgbm_class_1': 0.9615306510812772, 'weight_lgbm_class_2': 0.38827098465999016, 'weight_xgb_class_0': 0.028919952976077253, 'weight_xgb_class_1': 0.6798969043847072, 'weight_xgb_class_2': 0.542329245405013}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:17,943] Trial 1536 finished with value: 0.9484474761964141 and parameters: {'weight_lgbm_class_0': 0.1336535415802792, 'weight_lgbm_class_1': 0.9561554933874503, 'weight_lgbm_class_2': 0.3927129307404976, 'weight_xgb_class_0': 0.03422376252345122, 'weight_xgb_class_1': 0.6771959434515202, 'weight_xgb_class_2': 0.5379991751928856}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:17,954] Trial 1535 finished with value: 0.9161088028141392 and parameters: {'weight_lgbm_class_0': 0.6346173454319306, 'weight_lgbm_class_1': 0.9593450950346324, 'weight_lgbm_class_2': 0.3895187669121405, 'weight_xgb_class_0': 0.0002928543108512687, 'weight_xgb_class_1': 0.6875051977068027, 'weight_xgb_class_2': 0.5404327595790849}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:17,993] Trial 1537 finished with value: 0.9487484113499812 and parameters: {'weight_lgbm_class_0': 0.1281972199713231, 'weight_lgbm_class_1': 0.9559517750919835, 'weight_lgbm_class_2': 0.3899075736519664, 'weight_xgb_class_0': 0.02474812428019136, 'weight_xgb_class_1': 0.6800597652964866, 'weight_xgb_class_2': 0.5438106035295849}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:18,044] Trial 1538 finished with value: 0.9488354297260594 and parameters: {'weight_lgbm_class_0': 0.12727020823064425, 'weight_lgbm_class_1': 0.9799600226600523, 'weight_lgbm_class_2': 0.3906985904726093, 'weight_xgb_class_0': 0.022630248264894664, 'weight_xgb_class_1': 0.6787837627829703, 'weight_xgb_class_2': 0.5378600220536832}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:18,072] Trial 1539 finished with value: 0.9482915596972097 and parameters: {'weight_lgbm_class_0': 0.12870224831755261, 'weight_lgbm_class_1': 0.40218377197412336, 'weight_lgbm_class_2': 0.3874650509603721, 'weight_xgb_class_0': 0.024604254870985456, 'weight_xgb_class_1': 0.6758295455256889, 'weight_xgb_class_2': 0.5413963499969501}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  77%|████████████████████████████████████████████████████████████████████████████████████████████████████▎                             | 1543/2000 [00:46<00:18, 25.34it/s]

[I 2026-07-05 15:32:18,126] Trial 1540 finished with value: 0.9492066329763937 and parameters: {'weight_lgbm_class_0': 0.113619785883435, 'weight_lgbm_class_1': 0.9585963588019274, 'weight_lgbm_class_2': 0.4261329322939377, 'weight_xgb_class_0': 0.020973022331503114, 'weight_xgb_class_1': 0.6786366467904404, 'weight_xgb_class_2': 0.5388575628358857}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:18,165] Trial 1541 finished with value: 0.9485439357297034 and parameters: {'weight_lgbm_class_0': 0.11388413282409277, 'weight_lgbm_class_1': 0.9600068274901563, 'weight_lgbm_class_2': 0.4191675162448788, 'weight_xgb_class_0': 0.05017020545923917, 'weight_xgb_class_1': 0.6796083934408301, 'weight_xgb_class_2': 0.5367351692265467}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:18,228] Trial 1542 finished with value: 0.9491229743549118 and parameters: {'weight_lgbm_class_0': 0.11681195183237232, 'weight_lgbm_class_1': 0.9560947775884682, 'weight_lgbm_class_2': 0.4211656468108617, 'weight_xgb_class_0': 0.020724626665751134, 'weight_xgb_class_1': 0.6804731568752084, 'weight_xgb_class_2': 0.5339457105715442}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:18,232] Trial 1543 finished with value: 0.9486053962836388 and parameters: {'weight_lgbm_class_0': 0.11076587843265845, 'weight_lgbm_class_1': 0.980020250182583, 'weight_lgbm_class_2': 0.42779010585152455, 'weight_xgb_class_0': 0.05199887426928064, 'weight_xgb_class_1': 0.6747387269925943, 'weight_xgb_class_2': 0.5345703074731704}. Best is trial 1206 with value: 0.9498581274668642.

[I 2026-07-05 15:32:18,346] Trial 1544 finished with value: 0.9487933345076124 and parameters: {'weight_lgbm_class_0': 0.11362423604020622, 'weight_lgbm_class_1': 0.9833054087833354, 'weight_lgbm_class_2': 0.42625061415244964, 'weight_xgb_class_0': 0.05077812208430425, 'weight_xgb_class_1': 0.6166784027401752, 'weight_xgb_class_2': 0.5951538665435285}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:18,375] Trial 1545 finished with value: 0.948855010355221 and parameters: {'weight_lgbm_class_0': 0.11269042170829395, 'weight_lgbm_class_1': 0.9820756603693416, 'weight_lgbm_class_2': 0.42813115328515, 'weight_xgb_class_0': 0.049466253808647505, 'weight_xgb_class_1': 0.7026915752772521, 'weight_xgb_class_2': 0.597105531675729}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:18,384] Trial 1546 finished with value: 0.9488306194227679 and parameters: {'weight_lgbm_class_0': 0.11097567919641364, 'weight_lgbm_class_1': 0.9826713716337974, 'weight_lgbm_class_2': 0.42422218956641206, 'weight_xgb_class_0': 0.051550012440618104, 'weight_xgb_class_1': 0.7018178233247172, 'weight_xgb_class_2': 0.5927141283263111}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:18,455] Trial 1547 finished with value: 0.9483238937126955 and parameters: {'weight_lgbm_class_0': 0.10401862158344641, 'weight_lgbm_class_1': 0.9815925223907023, 'weight_lgbm_class_2': 0.42603884498244987, 'weight_xgb_class_0': 0.05273804324785442, 'weight_xgb_class_1': 0.7032649984774533, 'weight_xgb_class_2': 0.41051232768212187}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:18,469] Trial 1549 finished with value: 0.9489117744374201 and parameters: {'weight_lgbm_class_0': 0.10342349169775401, 'weight_lgbm_class_1': 0.9813350113454705, 'weight_lgbm_class_2': 0.4225387918357888, 'weight_xgb_class_0': 0.053725851822487874, 'weight_xgb_class_1': 0.7070659723291688, 'weight_xgb_class_2': 0.5996283498631105}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:18,512] Trial 1548 finished with value: 0.948790722404544 and parameters: {'weight_lgbm_class_0': 0.1122676001624789, 'weight_lgbm_class_1': 0.9787003509471695, 'weight_lgbm_class_2': 0.4163627468838308, 'weight_xgb_class_0': 0.05173386939599603, 'weight_xgb_class_1': 0.6196359205719804, 'weight_xgb_class_2': 0.6013524628008683}. Best is trial 1206 with value: 0.9498581274668642.

Best trial: 1206. Best value: 0.949858:  78%|█████████████████████████████████████████████████████████████████████████████████████████████████████                             | 1555/2000 [00:47<00:17, 24.86it/s]

[I 2026-07-05 15:32:18,547] Trial 1550 finished with value: 0.9489438413659 and parameters: {'weight_lgbm_class_0': 0.10786733786135967, 'weight_lgbm_class_1': 0.9805671008309561, 'weight_lgbm_class_2': 0.4290468414572918, 'weight_xgb_class_0': 0.0524940725945659, 'weight_xgb_class_1': 0.761487513378875, 'weight_xgb_class_2': 0.5998662208705776}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:18,605] Trial 1551 finished with value: 0.9488722993764149 and parameters: {'weight_lgbm_class_0': 0.10782397751604844, 'weight_lgbm_class_1': 0.98121397131703, 'weight_lgbm_class_2': 0.42374703592421303, 'weight_xgb_class_0': 0.051583982160730346, 'weight_xgb_class_1': 0.7087845468285157, 'weight_xgb_class_2': 0.5968032002518101}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:18,613] Trial 1552 finished with value: 0.9469957715086886 and parameters: {'weight_lgbm_class_0': 0.10248475667518275, 'weight_lgbm_class_1': 0.9999861402917377, 'weight_lgbm_class_2': 0.05909745308680264, 'weight_xgb_class_0': 0.054981954323902224, 'weight_xgb_class_1': 0.7045544555947784, 'weight_xgb_class_2': 0.5964180438267989}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:18,669] Trial 1553 finished with value: 0.9492080054065793 and parameters: {'weight_lgbm_class_0': 0.09731048576545567, 'weight_lgbm_class_1': 0.9812043422681118, 'weight_lgbm_class_2': 0.4283702594079625, 'weight_xgb_class_0': 0.045880204421354064, 'weight_xgb_class_1': 0.7574945413522088, 'weight_xgb_class_2': 0.6012136894167764}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:18,716] Trial 1554 finished with value: 0.949093243583166 and parameters: {'weight_lgbm_class_0': 0.09390384251135324, 'weight_lgbm_class_1': 0.9815337977678291, 'weight_lgbm_class_2': 0.4307114372742945, 'weight_xgb_class_0': 0.05434303734472901, 'weight_xgb_class_1': 0.7060398134673136, 'weight_xgb_class_2': 0.5962853963060081}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:18,779] Trial 1555 finished with value: 0.9490892998593692 and parameters: {'weight_lgbm_class_0': 0.10087795521685305, 'weight_lgbm_class_1': 0.978584215726495, 'weight_lgbm_class_2': 0.466920859994972, 'weight_xgb_class_0': 0.05303570278646191, 'weight_xgb_class_1': 0.7589726335776563, 'weight_xgb_class_2': 0.5930031981806149}. Best is trial 1206 with value: 0.9498581274668642.

[I 2026-07-05 15:32:18,886] Trial 1557 finished with value: 0.9497076662601126 and parameters: {'weight_lgbm_class_0': 0.08886082128192546, 'weight_lgbm_class_1': 0.9997606416370491, 'weight_lgbm_class_2': 0.47056994483120834, 'weight_xgb_class_0': 0.0008031550560493143, 'weight_xgb_class_1': 0.7596773958504149, 'weight_xgb_class_2': 0.5955449716105793}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:18,904] Trial 1556 finished with value: 0.9498028052622072 and parameters: {'weight_lgbm_class_0': 0.09201104469912826, 'weight_lgbm_class_1': 0.9830694935105162, 'weight_lgbm_class_2': 0.4719606097638911, 'weight_xgb_class_0': 0.01671556097489927, 'weight_xgb_class_1': 0.7573203978794245, 'weight_xgb_class_2': 0.6035792179912468}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:18,949] Trial 1558 finished with value: 0.9497550847361476 and parameters: {'weight_lgbm_class_0': 0.09180186001247606, 'weight_lgbm_class_1': 0.9827271843257657, 'weight_lgbm_class_2': 0.46666770448185413, 'weight_xgb_class_0': 7.593544892031657e-05, 'weight_xgb_class_1': 0.7582741572609685, 'weight_xgb_class_2': 0.5925011936516252}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:19,000] Trial 1559 finished with value: 0.9498334726775837 and parameters: {'weight_lgbm_class_0': 0.08730139899915398, 'weight_lgbm_class_1': 0.9811502265685651, 'weight_lgbm_class_2': 0.47042393732092413, 'weight_xgb_class_0': 0.016944729397110565, 'weight_xgb_class_1': 0.7554340739048996, 'weight_xgb_class_2': 0.5622762605960081}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:19,008] Trial 1560 finished with value: 0.9498067296900953 and parameters: {'weight_lgbm_class_0': 0.08988965561281463, 'weight_lgbm_class_1': 0.9810201809389952, 'weight_lgbm_class_2': 0.4627622570158464, 'weight_xgb_class_0': 0.0005393844148402424, 'weight_xgb_class_1': 0.7591827664922675, 'weight_xgb_class_2': 0.362451521601483}. Best is trial 1206 with value: 0.9498581274668642.
[I 2026-07-05 15:32:19,036] Trial 1561 finished with value: 0.9498642565074636 and parameters: {'weight_lgbm_class_0': 0.09126475943894025, 'weight_lgbm_class_1': 0.981606914104478, 'weight_lgbm_class_2': 0.46889153085323293, 'weight_xgb_class_0': 0.014570720035774165, 'weight_xgb_class_1': 0.7570400214426172, 'weight_xgb_class_2': 0.563821051956229}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  78%|█████████████████████████████████████████████████████████████████████████████████████████████████████▉                            | 1568/2000 [00:47<00:16, 26.30it/s]

[I 2026-07-05 15:32:19,103] Trial 1563 finished with value: 0.9497311416179848 and parameters: {'weight_lgbm_class_0': 0.08903054347541796, 'weight_lgbm_class_1': 0.981128815159184, 'weight_lgbm_class_2': 0.46932450666044934, 'weight_xgb_class_0': 5.494506420540904e-05, 'weight_xgb_class_1': 0.7552078835711734, 'weight_xgb_class_2': 0.5645528969724646}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:19,114] Trial 1562 finished with value: 0.949756729920653 and parameters: {'weight_lgbm_class_0': 0.09004491513557528, 'weight_lgbm_class_1': 0.9986827217376835, 'weight_lgbm_class_2': 0.4659863834525458, 'weight_xgb_class_0': 0.0004072932581379624, 'weight_xgb_class_1': 0.7491650095678536, 'weight_xgb_class_2': 0.5586692321657977}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:19,146] Trial 1565 finished with value: 0.9495777192779614 and parameters: {'weight_lgbm_class_0': 0.07378396707179985, 'weight_lgbm_class_1': 0.9999197901994255, 'weight_lgbm_class_2': 0.4666161366196969, 'weight_xgb_class_0': 0.0005836033133854297, 'weight_xgb_class_1': 0.4976547012147706, 'weight_xgb_class_2': 0.5601730063332042}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:19,158] Trial 1564 finished with value: 0.9496858647656709 and parameters: {'weight_lgbm_class_0': 0.07086251716800987, 'weight_lgbm_class_1': 0.9656916862568748, 'weight_lgbm_class_2': 0.4538081491681656, 'weight_xgb_class_0': 0.014718940804063415, 'weight_xgb_class_1': 0.747948557741951, 'weight_xgb_class_2': 0.5620917066672825}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:19,183] Trial 1566 finished with value: 0.9497283276804181 and parameters: {'weight_lgbm_class_0': 0.07517327490929084, 'weight_lgbm_class_1': 0.9995197203983768, 'weight_lgbm_class_2': 0.46809398043401124, 'weight_xgb_class_0': 0.020625354364707735, 'weight_xgb_class_1': 0.7494153457301027, 'weight_xgb_class_2': 0.5643237360599777}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:19,252] Trial 1567 finished with value: 0.9065787563732642 and parameters: {'weight_lgbm_class_0': 0.07028947678904184, 'weight_lgbm_class_1': 0.9497953513793013, 'weight_lgbm_class_2': 0.45316890324009734, 'weight_xgb_class_0': 0.7504613495759451, 'weight_xgb_class_1': 0.7543955134317908, 'weight_xgb_class_2': 0.5602094121994193}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  79%|██████████████████████████████████████████████████████████████████████████████████████████████████████▏                           | 1572/2000 [00:48<00:20, 21.40it/s]

[I 2026-07-05 15:32:19,361] Trial 1568 finished with value: 0.949478012390192 and parameters: {'weight_lgbm_class_0': 0.07088935693262549, 'weight_lgbm_class_1': 0.946461473258664, 'weight_lgbm_class_2': 0.4609981413041772, 'weight_xgb_class_0': 0.00017830978459605282, 'weight_xgb_class_1': 0.6487584015102229, 'weight_xgb_class_2': 0.5591954805471012}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:19,408] Trial 1569 finished with value: 0.9498436146629975 and parameters: {'weight_lgbm_class_0': 0.07948085815085686, 'weight_lgbm_class_1': 0.9998002896265353, 'weight_lgbm_class_2': 0.4051432250152388, 'weight_xgb_class_0': 0.017665580964530234, 'weight_xgb_class_1': 0.654911585619647, 'weight_xgb_class_2': 0.5632302707525845}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:19,473] Trial 1570 finished with value: 0.9496239124577448 and parameters: {'weight_lgbm_class_0': 0.07809422892398127, 'weight_lgbm_class_1': 0.9438004462368121, 'weight_lgbm_class_2': 0.4096492781384762, 'weight_xgb_class_0': 0.00046461808153666975, 'weight_xgb_class_1': 0.7184788072843323, 'weight_xgb_class_2': 0.5616257248181046}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:19,520] Trial 1571 finished with value: 0.9493947429993043 and parameters: {'weight_lgbm_class_0': 0.06915124098921491, 'weight_lgbm_class_1': 0.9500655166486573, 'weight_lgbm_class_2': 0.483912376556098, 'weight_xgb_class_0': 0.00013131913273984057, 'weight_xgb_class_1': 0.653979010906275, 'weight_xgb_class_2': 0.5571124747327997}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:19,558] Trial 1572 finished with value: 0.9497252602149557 and parameters: {'weight_lgbm_class_0': 0.07325228254245819, 'weight_lgbm_class_1': 0.9634208824598993, 'weight_lgbm_class_2': 0.5090754104485572, 'weight_xgb_class_0': 0.018917981316709808, 'weight_xgb_class_1': 0.760130280940942, 'weight_xgb_class_2': 0.5616214220744923}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  79%|██████████████████████████████████████████████████████████████████████████████████████████████████████▋                           | 1579/2000 [00:48<00:17, 23.77it/s]

[I 2026-07-05 15:32:19,578] Trial 1573 finished with value: 0.9497159384586692 and parameters: {'weight_lgbm_class_0': 0.07107184301910317, 'weight_lgbm_class_1': 0.9610387928665809, 'weight_lgbm_class_2': 0.5086110789691551, 'weight_xgb_class_0': 0.01980836487338328, 'weight_xgb_class_1': 0.7660245580219618, 'weight_xgb_class_2': 0.5631765854034346}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:19,607] Trial 1574 finished with value: 0.9496812967361737 and parameters: {'weight_lgbm_class_0': 0.0700185881683988, 'weight_lgbm_class_1': 0.9994462326159916, 'weight_lgbm_class_2': 0.4990822288752343, 'weight_xgb_class_0': 0.01859684277955365, 'weight_xgb_class_1': 0.7674714503907414, 'weight_xgb_class_2': 0.566377653642754}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:19,622] Trial 1576 finished with value: 0.921720308113826 and parameters: {'weight_lgbm_class_0': 0.06959736831908107, 'weight_lgbm_class_1': 0.9508534571336715, 'weight_lgbm_class_2': 0.5059535456603216, 'weight_xgb_class_0': 0.5648992498611973, 'weight_xgb_class_1': 0.7655498821969682, 'weight_xgb_class_2': 0.5591076080881593}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:19,623] Trial 1577 finished with value: 0.9488489145759749 and parameters: {'weight_lgbm_class_0': 0.14417009175762077, 'weight_lgbm_class_1': 0.9488201841074988, 'weight_lgbm_class_2': 0.49626777579315595, 'weight_xgb_class_0': 0.021985546400879265, 'weight_xgb_class_1': 0.7630778007590457, 'weight_xgb_class_2': 0.5561354764209716}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:19,666] Trial 1575 finished with value: 0.9497178099443304 and parameters: {'weight_lgbm_class_0': 0.06936853188908854, 'weight_lgbm_class_1': 0.9996133146695176, 'weight_lgbm_class_2': 0.5313650761897657, 'weight_xgb_class_0': 0.020702406970179194, 'weight_xgb_class_1': 0.7596394212401396, 'weight_xgb_class_2': 0.5545147926364014}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:19,682] Trial 1578 finished with value: 0.9488772657806175 and parameters: {'weight_lgbm_class_0': 0.14411819487253716, 'weight_lgbm_class_1': 0.9487639562898108, 'weight_lgbm_class_2': 0.502428811910008, 'weight_xgb_class_0': 0.020413063857400084, 'weight_xgb_class_1': 0.7560105066569405, 'weight_xgb_class_2': 0.556300973961125}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:19,761] Trial 1579 finished with value: 0.9487605402153071 and parameters: {'weight_lgbm_class_0': 0.14845891976352932, 'weight_lgbm_class_1': 0.9636010560839146, 'weight_lgbm_class_2': 0.5381519427996515, 'weight_xgb_class_0': 0.01987835961753281, 'weight_xgb_class_1': 0.7392951554394958, 'weight_xgb_class_2': 0.5211734445619846}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  79%|██████████████████████████████████████████████████████████████████████████████████████████████████████▉                           | 1584/2000 [00:48<00:17, 23.72it/s]

[I 2026-07-05 15:32:19,821] Trial 1580 finished with value: 0.9067883843006301 and parameters: {'weight_lgbm_class_0': 0.8082000619317378, 'weight_lgbm_class_1': 0.9986686124155675, 'weight_lgbm_class_2': 0.5082834763175373, 'weight_xgb_class_0': 0.025612951336237585, 'weight_xgb_class_1': 0.7635571005384473, 'weight_xgb_class_2': 0.5192355754552704}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:19,904] Trial 1581 finished with value: 0.9488532660859526 and parameters: {'weight_lgbm_class_0': 0.14573262344396337, 'weight_lgbm_class_1': 0.982249128066672, 'weight_lgbm_class_2': 0.5442779759584675, 'weight_xgb_class_0': 0.017771112380349993, 'weight_xgb_class_1': 0.6144140603384349, 'weight_xgb_class_2': 0.5256759047735019}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:19,934] Trial 1582 finished with value: 0.9488529161305793 and parameters: {'weight_lgbm_class_0': 0.13805651450266998, 'weight_lgbm_class_1': 0.9988628208350563, 'weight_lgbm_class_2': 0.5315370276101572, 'weight_xgb_class_0': 0.021134805955401327, 'weight_xgb_class_1': 0.5895666180396293, 'weight_xgb_class_2': 0.5252760428733821}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:19,986] Trial 1583 finished with value: 0.9485944933931156 and parameters: {'weight_lgbm_class_0': 0.14828542399158035, 'weight_lgbm_class_1': 0.9996861747599549, 'weight_lgbm_class_2': 0.5199390796104661, 'weight_xgb_class_0': 0.020490946728608028, 'weight_xgb_class_1': 0.6107758832573291, 'weight_xgb_class_2': 0.5205187063470056}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  79%|███████████████████████████████████████████████████████████████████████████████████████████████████████▎                          | 1589/2000 [00:48<00:20, 20.45it/s]

[I 2026-07-05 15:32:20,078] Trial 1584 finished with value: 0.9489396387171194 and parameters: {'weight_lgbm_class_0': 0.13133615072812166, 'weight_lgbm_class_1': 0.9980455589969897, 'weight_lgbm_class_2': 0.4897044100410386, 'weight_xgb_class_0': 0.02325685112361145, 'weight_xgb_class_1': 0.6246598685213783, 'weight_xgb_class_2': 0.5222511994916557}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:20,107] Trial 1585 finished with value: 0.948528854998759 and parameters: {'weight_lgbm_class_0': 0.14188080371211065, 'weight_lgbm_class_1': 0.9988493730071161, 'weight_lgbm_class_2': 0.4893775591470498, 'weight_xgb_class_0': 0.03174760229007, 'weight_xgb_class_1': 0.6501285124010849, 'weight_xgb_class_2': 0.5257737579512125}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:20,165] Trial 1587 finished with value: 0.9484274957277958 and parameters: {'weight_lgbm_class_0': 0.14189928644047772, 'weight_lgbm_class_1': 0.9831526789293333, 'weight_lgbm_class_2': 0.48329116726283344, 'weight_xgb_class_0': 0.03467126556236748, 'weight_xgb_class_1': 0.6302487698810285, 'weight_xgb_class_2': 0.5212019631419833}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:20,189] Trial 1586 finished with value: 0.9484488134893088 and parameters: {'weight_lgbm_class_0': 0.1486052769899554, 'weight_lgbm_class_1': 0.9812241114568054, 'weight_lgbm_class_2': 0.5273540582591044, 'weight_xgb_class_0': 0.03269908039059398, 'weight_xgb_class_1': 0.6295389362810003, 'weight_xgb_class_2': 0.52030451641505}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:20,215] Trial 1588 finished with value: 0.9483640308280997 and parameters: {'weight_lgbm_class_0': 0.14120788386246413, 'weight_lgbm_class_1': 0.982346952312993, 'weight_lgbm_class_2': 0.4486223409059522, 'weight_xgb_class_0': 0.03475875819862932, 'weight_xgb_class_1': 0.6198240755702122, 'weight_xgb_class_2': 0.5231744541285928}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:20,255] Trial 1589 finished with value: 0.9483030980321718 and parameters: {'weight_lgbm_class_0': 0.12693008990053758, 'weight_lgbm_class_1': 0.4274896522115908, 'weight_lgbm_class_2': 0.4973602834512559, 'weight_xgb_class_0': 0.033431502929755615, 'weight_xgb_class_1': 0.6090706149577172, 'weight_xgb_class_2': 0.5150658561371093}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████████▋                          | 1595/2000 [00:49<00:16, 24.31it/s]

[I 2026-07-05 15:32:20,271] Trial 1590 finished with value: 0.9024542151901719 and parameters: {'weight_lgbm_class_0': 0.8234447768732179, 'weight_lgbm_class_1': 0.9988731533733888, 'weight_lgbm_class_2': 0.48450621409794803, 'weight_xgb_class_0': 0.03409465428066019, 'weight_xgb_class_1': 0.6302252827126158, 'weight_xgb_class_2': 0.5143609275514207}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:20,332] Trial 1591 finished with value: 0.9487665440467076 and parameters: {'weight_lgbm_class_0': 0.12696184737761884, 'weight_lgbm_class_1': 0.9998896173960053, 'weight_lgbm_class_2': 0.4927885824104315, 'weight_xgb_class_0': 0.03552105398769585, 'weight_xgb_class_1': 0.622761600632332, 'weight_xgb_class_2': 0.523262430221381}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:20,351] Trial 1592 finished with value: 0.948732264512914 and parameters: {'weight_lgbm_class_0': 0.12859571437358072, 'weight_lgbm_class_1': 0.9990534836690812, 'weight_lgbm_class_2': 0.49224622257956296, 'weight_xgb_class_0': 0.03524734549172137, 'weight_xgb_class_1': 0.6196726433664397, 'weight_xgb_class_2': 0.5241251935749681}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:20,421] Trial 1593 finished with value: 0.9490438005764648 and parameters: {'weight_lgbm_class_0': 0.11430000149068123, 'weight_lgbm_class_1': 0.9992089706320487, 'weight_lgbm_class_2': 0.4922403984526883, 'weight_xgb_class_0': 0.03674760254486817, 'weight_xgb_class_1': 0.6278112047039831, 'weight_xgb_class_2': 0.5817713212388695}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:20,435] Trial 1594 finished with value: 0.9489223319216865 and parameters: {'weight_lgbm_class_0': 0.12278056089362438, 'weight_lgbm_class_1': 0.9996558030678727, 'weight_lgbm_class_2': 0.49397807835442925, 'weight_xgb_class_0': 0.03560770886464837, 'weight_xgb_class_1': 0.634677143125275, 'weight_xgb_class_2': 0.5786804134117632}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:20,463] Trial 1595 finished with value: 0.9488819622523538 and parameters: {'weight_lgbm_class_0': 0.12303180183060983, 'weight_lgbm_class_1': 0.9997920275680602, 'weight_lgbm_class_2': 0.4837112504315288, 'weight_xgb_class_0': 0.03768101643690615, 'weight_xgb_class_1': 0.6297439491527735, 'weight_xgb_class_2': 0.5401002217808685}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  80%|███████████████████████████████████████████████████████████████████████████████████████████████████████▉                          | 1599/2000 [00:49<00:17, 22.61it/s]

[I 2026-07-05 15:32:20,566] Trial 1596 finished with value: 0.9489672482841023 and parameters: {'weight_lgbm_class_0': 0.11963084445343297, 'weight_lgbm_class_1': 0.9780263577817209, 'weight_lgbm_class_2': 0.48205082797331206, 'weight_xgb_class_0': 0.03594400073155994, 'weight_xgb_class_1': 0.6521706273405001, 'weight_xgb_class_2': 0.580440475510335}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:20,602] Trial 1597 finished with value: 0.9487035598476412 and parameters: {'weight_lgbm_class_0': 0.11786165442886545, 'weight_lgbm_class_1': 0.974445490666399, 'weight_lgbm_class_2': 0.48098786254032033, 'weight_xgb_class_0': 0.039941318840030285, 'weight_xgb_class_1': 0.2859803187227861, 'weight_xgb_class_2': 0.5794348821919457}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:20,713] Trial 1598 finished with value: 0.9489358552037043 and parameters: {'weight_lgbm_class_0': 0.1173889375710284, 'weight_lgbm_class_1': 0.9787612358754992, 'weight_lgbm_class_2': 0.49411654088979834, 'weight_xgb_class_0': 0.039967953485341295, 'weight_xgb_class_1': 0.6479541799525503, 'weight_xgb_class_2': 0.5728200594881175}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:20,724] Trial 1600 finished with value: 0.9227847358390449 and parameters: {'weight_lgbm_class_0': 0.5616069633959956, 'weight_lgbm_class_1': 0.9790973367280488, 'weight_lgbm_class_2': 0.4838320562525559, 'weight_xgb_class_0': 0.04044656754966855, 'weight_xgb_class_1': 0.6526164936334444, 'weight_xgb_class_2': 0.5772579167749377}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  80%|████████████████████████████████████████████████████████████████████████████████████████████████████████▎                         | 1605/2000 [00:49<00:16, 23.98it/s]

[I 2026-07-05 15:32:20,735] Trial 1599 finished with value: 0.949009726007413 and parameters: {'weight_lgbm_class_0': 0.1138858511574264, 'weight_lgbm_class_1': 0.9776875392650797, 'weight_lgbm_class_2': 0.48829692579670864, 'weight_xgb_class_0': 0.03741294967837442, 'weight_xgb_class_1': 0.6484927240774723, 'weight_xgb_class_2': 0.5712278917888687}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:20,752] Trial 1601 finished with value: 0.9355048097195781 and parameters: {'weight_lgbm_class_0': 0.11933460517646692, 'weight_lgbm_class_1': 0.9753756529149483, 'weight_lgbm_class_2': 0.4795627542364702, 'weight_xgb_class_0': 0.3169855243304706, 'weight_xgb_class_1': 0.657653182476656, 'weight_xgb_class_2': 0.5837166949181982}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:20,825] Trial 1602 finished with value: 0.9498132930935238 and parameters: {'weight_lgbm_class_0': 0.09266797660866975, 'weight_lgbm_class_1': 0.9722132683389355, 'weight_lgbm_class_2': 0.4465482547015201, 'weight_xgb_class_0': 0.01673773592165188, 'weight_xgb_class_1': 0.6578883193143642, 'weight_xgb_class_2': 0.578697460366569}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:20,856] Trial 1603 finished with value: 0.9497752209432297 and parameters: {'weight_lgbm_class_0': 0.09744036744791218, 'weight_lgbm_class_1': 0.9688516412824644, 'weight_lgbm_class_2': 0.45780451021260277, 'weight_xgb_class_0': 0.01699899058306314, 'weight_xgb_class_1': 0.6497686501665191, 'weight_xgb_class_2': 0.5816700830432594}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:20,883] Trial 1604 finished with value: 0.9497535120674709 and parameters: {'weight_lgbm_class_0': 0.09274095314748794, 'weight_lgbm_class_1': 0.9713150754365519, 'weight_lgbm_class_2': 0.4452522224720142, 'weight_xgb_class_0': 0.0005503926746099994, 'weight_xgb_class_1': 0.657201867564536, 'weight_xgb_class_2': 0.5786760723535322}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:20,940] Trial 1606 finished with value: 0.9497931505101267 and parameters: {'weight_lgbm_class_0': 0.08911494607308962, 'weight_lgbm_class_1': 0.9722243644198525, 'weight_lgbm_class_2': 0.4447302280309793, 'weight_xgb_class_0': 0.016686318123674788, 'weight_xgb_class_1': 0.6641333333446361, 'weight_xgb_class_2': 0.5500235774695296}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  80%|████████████████████████████████████████████████████████████████████████████████████████████████████████▋                         | 1610/2000 [00:49<00:15, 25.17it/s]

[I 2026-07-05 15:32:20,961] Trial 1605 finished with value: 0.9498108999901262 and parameters: {'weight_lgbm_class_0': 0.0946962661665747, 'weight_lgbm_class_1': 0.9743758092360948, 'weight_lgbm_class_2': 0.45009583212926846, 'weight_xgb_class_0': 0.019958047107841305, 'weight_xgb_class_1': 0.6559568592070911, 'weight_xgb_class_2': 0.5798107932994581}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:21,001] Trial 1607 finished with value: 0.9497534894024139 and parameters: {'weight_lgbm_class_0': 0.09225606198468042, 'weight_lgbm_class_1': 0.9714178413301457, 'weight_lgbm_class_2': 0.44784550820026, 'weight_xgb_class_0': 0.00015544697351892525, 'weight_xgb_class_1': 0.6689977582124953, 'weight_xgb_class_2': 0.5809409399208525}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:21,036] Trial 1608 finished with value: 0.9498421238188284 and parameters: {'weight_lgbm_class_0': 0.09221464329024112, 'weight_lgbm_class_1': 0.9672221810667803, 'weight_lgbm_class_2': 0.4476660802197764, 'weight_xgb_class_0': 0.016934022973154418, 'weight_xgb_class_1': 0.6566546042843532, 'weight_xgb_class_2': 0.5429805175806427}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:21,088] Trial 1609 finished with value: 0.9497729290886431 and parameters: {'weight_lgbm_class_0': 0.09296656616770826, 'weight_lgbm_class_1': 0.9693339247851521, 'weight_lgbm_class_2': 0.44832588952750146, 'weight_xgb_class_0': 0.0006812551418140015, 'weight_xgb_class_1': 0.6627612407566287, 'weight_xgb_class_2': 0.5461403741182194}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  81%|████████████████████████████████████████████████████████████████████████████████████████████████████████▉                         | 1615/2000 [00:49<00:18, 21.11it/s]

[I 2026-07-05 15:32:21,199] Trial 1610 finished with value: 0.9497677742680918 and parameters: {'weight_lgbm_class_0': 0.09312508150047134, 'weight_lgbm_class_1': 0.9655797603169746, 'weight_lgbm_class_2': 0.45976318520854137, 'weight_xgb_class_0': 0.0008262738144599279, 'weight_xgb_class_1': 0.6957184789625777, 'weight_xgb_class_2': 0.5441299673085104}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:21,247] Trial 1611 finished with value: 0.9498225027503707 and parameters: {'weight_lgbm_class_0': 0.08706090660175447, 'weight_lgbm_class_1': 0.96643784890793, 'weight_lgbm_class_2': 0.43806568203406127, 'weight_xgb_class_0': 0.01670591782454587, 'weight_xgb_class_1': 0.6923105234733856, 'weight_xgb_class_2': 0.5467102056107864}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:21,284] Trial 1612 finished with value: 0.9498114077785265 and parameters: {'weight_lgbm_class_0': 0.09108027649529546, 'weight_lgbm_class_1': 0.9668405915169836, 'weight_lgbm_class_2': 0.44636051933850646, 'weight_xgb_class_0': 0.017109821627935316, 'weight_xgb_class_1': 0.693035321192354, 'weight_xgb_class_2': 0.5390020283655625}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:21,301] Trial 1613 finished with value: 0.949579236207937 and parameters: {'weight_lgbm_class_0': 0.09033901926497859, 'weight_lgbm_class_1': 0.9648119608453706, 'weight_lgbm_class_2': 0.4507293561649131, 'weight_xgb_class_0': 0.017389870385437257, 'weight_xgb_class_1': 0.04474516477256607, 'weight_xgb_class_2': 0.5484823887754399}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:21,324] Trial 1614 finished with value: 0.9498159771984375 and parameters: {'weight_lgbm_class_0': 0.08996455467355913, 'weight_lgbm_class_1': 0.9671930788278578, 'weight_lgbm_class_2': 0.44589180434702097, 'weight_xgb_class_0': 0.014678264645034885, 'weight_xgb_class_1': 0.6921487117811018, 'weight_xgb_class_2': 0.550613821050608}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:21,377] Trial 1615 finished with value: 0.9498069944518127 and parameters: {'weight_lgbm_class_0': 0.0950705363516563, 'weight_lgbm_class_1': 0.9652040533918393, 'weight_lgbm_class_2': 0.4413046706281651, 'weight_xgb_class_0': 0.00033246128766831044, 'weight_xgb_class_1': 0.6941104010022713, 'weight_xgb_class_2': 0.5450840999664923}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▎                        | 1621/2000 [00:50<00:16, 23.29it/s]

[I 2026-07-05 15:32:21,383] Trial 1616 finished with value: 0.949739332506017 and parameters: {'weight_lgbm_class_0': 0.09026641043882838, 'weight_lgbm_class_1': 0.9623497496850725, 'weight_lgbm_class_2': 0.44433425029355134, 'weight_xgb_class_0': 0.00026782033800138447, 'weight_xgb_class_1': 0.6929163603980271, 'weight_xgb_class_2': 0.5460581635908889}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:21,405] Trial 1617 finished with value: 0.9488527265627216 and parameters: {'weight_lgbm_class_0': 0.09242455034665412, 'weight_lgbm_class_1': 0.9620879480136382, 'weight_lgbm_class_2': 0.4070637393636934, 'weight_xgb_class_0': 0.059599646424511654, 'weight_xgb_class_1': 0.6900157296797472, 'weight_xgb_class_2': 0.5404894235378346}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:21,488] Trial 1618 finished with value: 0.9497753215212033 and parameters: {'weight_lgbm_class_0': 0.09114225459960822, 'weight_lgbm_class_1': 0.9641834686104414, 'weight_lgbm_class_2': 0.4626265364841989, 'weight_xgb_class_0': 0.01689692821975053, 'weight_xgb_class_1': 0.6873951745912089, 'weight_xgb_class_2': 0.5436447591681255}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:21,555] Trial 1621 finished with value: 0.9496989215619832 and parameters: {'weight_lgbm_class_0': 0.10134593390514436, 'weight_lgbm_class_1': 0.9835867095632642, 'weight_lgbm_class_2': 0.4413892618071106, 'weight_xgb_class_0': 0.016414537532368254, 'weight_xgb_class_1': 0.6895280472227294, 'weight_xgb_class_2': 0.5447424455815009}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:21,556] Trial 1619 finished with value: 0.9491593228840959 and parameters: {'weight_lgbm_class_0': 0.09670398720832671, 'weight_lgbm_class_1': 0.1363098040057013, 'weight_lgbm_class_2': 0.4569768808394874, 'weight_xgb_class_0': 0.020483627828493316, 'weight_xgb_class_1': 0.6849321356753812, 'weight_xgb_class_2': 0.5419291290488822}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:21,577] Trial 1620 finished with value: 0.9496680414691934 and parameters: {'weight_lgbm_class_0': 0.10407256830216136, 'weight_lgbm_class_1': 0.9635289878787536, 'weight_lgbm_class_2': 0.45852188333776306, 'weight_xgb_class_0': 0.01621217011795236, 'weight_xgb_class_1': 0.692034053929215, 'weight_xgb_class_2': 0.5453417082438056}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▊                        | 1627/2000 [00:50<00:15, 23.61it/s]

[I 2026-07-05 15:32:21,687] Trial 1622 finished with value: 0.9495237139467751 and parameters: {'weight_lgbm_class_0': 0.10397403912020595, 'weight_lgbm_class_1': 0.9813240497126688, 'weight_lgbm_class_2': 0.4666644705091012, 'weight_xgb_class_0': 0.017261542355226627, 'weight_xgb_class_1': 0.6858569574941635, 'weight_xgb_class_2': 0.5020838344386758}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:21,714] Trial 1623 finished with value: 0.9486862180969037 and parameters: {'weight_lgbm_class_0': 0.1615752000849506, 'weight_lgbm_class_1': 0.9829804215487616, 'weight_lgbm_class_2': 0.47064522721537466, 'weight_xgb_class_0': 9.777842204790961e-05, 'weight_xgb_class_1': 0.675071824951114, 'weight_xgb_class_2': 0.5049090787377744}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:21,768] Trial 1625 finished with value: 0.9497916561655529 and parameters: {'weight_lgbm_class_0': 0.11391229168826075, 'weight_lgbm_class_1': 0.983164358681203, 'weight_lgbm_class_2': 0.45724763589738715, 'weight_xgb_class_0': 0.0005239752705369133, 'weight_xgb_class_1': 0.6691203251895078, 'weight_xgb_class_2': 0.540008265713208}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:21,811] Trial 1624 finished with value: 0.9491985553108505 and parameters: {'weight_lgbm_class_0': 0.11390693134793682, 'weight_lgbm_class_1': 0.9822465320320948, 'weight_lgbm_class_2': 0.46841404250645685, 'weight_xgb_class_0': 0.01736847226518725, 'weight_xgb_class_1': 0.6719308326332297, 'weight_xgb_class_2': 0.4748920805534707}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:21,813] Trial 1626 finished with value: 0.9486266341250413 and parameters: {'weight_lgbm_class_0': 0.1581111568274465, 'weight_lgbm_class_1': 0.9835922672251307, 'weight_lgbm_class_2': 0.4663083405107673, 'weight_xgb_class_0': 0.00028311940604797223, 'weight_xgb_class_1': 0.5553345213484617, 'weight_xgb_class_2': 0.5007885240614155}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:21,861] Trial 1627 finished with value: 0.9482773573109834 and parameters: {'weight_lgbm_class_0': 0.16509314127636907, 'weight_lgbm_class_1': 0.9829992914515121, 'weight_lgbm_class_2': 0.46905376724770664, 'weight_xgb_class_0': 0.01730539984339782, 'weight_xgb_class_1': 0.6678648648125737, 'weight_xgb_class_2': 0.5053347518962424}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████                        | 1631/2000 [00:50<00:14, 24.72it/s]

[I 2026-07-05 15:32:21,901] Trial 1628 finished with value: 0.9492162306790144 and parameters: {'weight_lgbm_class_0': 0.11695472259065665, 'weight_lgbm_class_1': 0.9828978970187241, 'weight_lgbm_class_2': 0.471591344096321, 'weight_xgb_class_0': 0.017724755461030323, 'weight_xgb_class_1': 0.6707259335028413, 'weight_xgb_class_2': 0.4986370222824357}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:21,922] Trial 1629 finished with value: 0.9482356260133541 and parameters: {'weight_lgbm_class_0': 0.16363842017822344, 'weight_lgbm_class_1': 0.9834834291087097, 'weight_lgbm_class_2': 0.46321570381085425, 'weight_xgb_class_0': 0.019239552882440416, 'weight_xgb_class_1': 0.6714166594713048, 'weight_xgb_class_2': 0.5072343400796253}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:21,946] Trial 1630 finished with value: 0.9489807944700822 and parameters: {'weight_lgbm_class_0': 0.11643547227272552, 'weight_lgbm_class_1': 0.9841137737311876, 'weight_lgbm_class_2': 0.43198552040505256, 'weight_xgb_class_0': 0.022813169479839447, 'weight_xgb_class_1': 0.6682200082834369, 'weight_xgb_class_2': 0.4968646885929167}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:22,090] Trial 1633 finished with value: 0.9484747232045336 and parameters: {'weight_lgbm_class_0': 0.16174728631337817, 'weight_lgbm_class_1': 0.9989962269945356, 'weight_lgbm_class_2': 0.411857576062449, 'weight_xgb_class_0': 0.0007591876851678198, 'weight_xgb_class_1': 0.6674688202942434, 'weight_xgb_class_2': 0.5016444083804512}. Best is trial 1561 with value: 0.9498642565074636.

[I 2026-07-05 15:32:22,091] Trial 1631 finished with value: 0.9491864392546079 and parameters: {'weight_lgbm_class_0': 0.11784687867004537, 'weight_lgbm_class_1': 0.985314895839083, 'weight_lgbm_class_2': 0.46719716378804765, 'weight_xgb_class_0': 0.01827474470698521, 'weight_xgb_class_1': 0.6679734866253947, 'weight_xgb_class_2': 0.5042169248218258}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:22,100] Trial 1632 finished with value: 0.948260421437177 and parameters: {'weight_lgbm_class_0': 0.15939403246428308, 'weight_lgbm_class_1': 0.9829065806453761, 'weight_lgbm_class_2': 0.4643215294932242, 'weight_xgb_class_0': 0.020209717938670227, 'weight_xgb_class_1': 0.6001049715172847, 'weight_xgb_class_2': 0.5005319716434684}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:22,155] Trial 1634 finished with value: 0.949741339311184 and parameters: {'weight_lgbm_class_0': 0.11627034190878434, 'weight_lgbm_class_1': 0.9986268417309867, 'weight_lgbm_class_2': 0.5127705557468024, 'weight_xgb_class_0': 0.0001338520749833482, 'weight_xgb_class_1': 0.6453865771637978, 'weight_xgb_class_2': 0.4993673812740728}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:22,177] Trial 1635 finished with value: 0.9497254742287254 and parameters: {'weight_lgbm_class_0': 0.11632442415230469, 'weight_lgbm_class_1': 0.9996439146517483, 'weight_lgbm_class_2': 0.5164132809109775, 'weight_xgb_class_0': 0.00011392135865048774, 'weight_xgb_class_1': 0.6431385211219028, 'weight_xgb_class_2': 0.5638954450608551}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:22,242] Trial 1636 finished with value: 0.9480233262144034 and parameters: {'weight_lgbm_class_0': 0.1304370992584635, 'weight_lgbm_class_1': 0.9859229415322552, 'weight_lgbm_class_2': 0.41022984445602584, 'weight_xgb_class_0': 0.05263766745304779, 'weight_xgb_class_1': 0.5968500114509601, 'weight_xgb_class_2': 0.5107054148585016}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:22,310] Trial 1637 finished with value: 0.9485355850709354 and parameters: {'weight_lgbm_class_0': 0.128634817989418, 'weight_lgbm_class_1': 0.9833749947940633, 'weight_lgbm_class_2': 0.5196002772335474, 'weight_xgb_class_0': 0.051368353110380516, 'weight_xgb_class_1': 0.6020353625917818, 'weight_xgb_class_2': 0.5641860066731682}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▊                       | 1643/2000 [00:51<00:13, 25.70it/s]

[I 2026-07-05 15:32:22,318] Trial 1638 finished with value: 0.948349029914469 and parameters: {'weight_lgbm_class_0': 0.13207046223197857, 'weight_lgbm_class_1': 0.9994015650940309, 'weight_lgbm_class_2': 0.5109628562902547, 'weight_xgb_class_0': 0.0493866805291986, 'weight_xgb_class_1': 0.5962983467939802, 'weight_xgb_class_2': 0.5044963003057501}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:22,358] Trial 1639 finished with value: 0.9488475829552462 and parameters: {'weight_lgbm_class_0': 0.11381330189296444, 'weight_lgbm_class_1': 0.9999639138727512, 'weight_lgbm_class_2': 0.4171045334488537, 'weight_xgb_class_0': 0.042292704529254405, 'weight_xgb_class_1': 0.5900482654360942, 'weight_xgb_class_2': 0.5625603400660898}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:22,392] Trial 1640 finished with value: 0.9424226665892212 and parameters: {'weight_lgbm_class_0': 0.27498755883027554, 'weight_lgbm_class_1': 0.9481442076519008, 'weight_lgbm_class_2': 0.5160788897224624, 'weight_xgb_class_0': 0.053055395391128045, 'weight_xgb_class_1': 0.6366122258456779, 'weight_xgb_class_2': 0.5635843830229482}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:22,406] Trial 1641 finished with value: 0.9389573677883476 and parameters: {'weight_lgbm_class_0': 0.12773518435504919, 'weight_lgbm_class_1': 0.9986936474583978, 'weight_lgbm_class_2': 0.5139439566269148, 'weight_xgb_class_0': 0.26238512983436835, 'weight_xgb_class_1': 0.640520288389903, 'weight_xgb_class_2': 0.5615925283800968}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:22,442] Trial 1642 finished with value: 0.94837420104794 and parameters: {'weight_lgbm_class_0': 0.13214190828984723, 'weight_lgbm_class_1': 0.9467964972748324, 'weight_lgbm_class_2': 0.5109004861017494, 'weight_xgb_class_0': 0.055124974135114996, 'weight_xgb_class_1': 0.6378574105929647, 'weight_xgb_class_2': 0.5668199168494604}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████                       | 1647/2000 [00:51<00:15, 23.45it/s]

[I 2026-07-05 15:32:22,566] Trial 1644 finished with value: 0.9494853171224248 and parameters: {'weight_lgbm_class_0': 0.07256131389071277, 'weight_lgbm_class_1': 0.9999329140038715, 'weight_lgbm_class_2': 0.4148290455478039, 'weight_xgb_class_0': 0.05418221719949189, 'weight_xgb_class_1': 0.7120508000903631, 'weight_xgb_class_2': 0.5726060789178539}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:22,591] Trial 1643 finished with value: 0.949753279760161 and parameters: {'weight_lgbm_class_0': 0.06840643092376893, 'weight_lgbm_class_1': 0.9421504109486818, 'weight_lgbm_class_2': 0.511364499000706, 'weight_xgb_class_0': 0.05239661220253895, 'weight_xgb_class_1': 0.642894416430112, 'weight_xgb_class_2': 0.5646626606111782}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:22,652] Trial 1645 finished with value: 0.9455334460865302 and parameters: {'weight_lgbm_class_0': 0.21755354808361776, 'weight_lgbm_class_1': 0.9452986012735735, 'weight_lgbm_class_2': 0.42818564621220406, 'weight_xgb_class_0': 0.03830772416767144, 'weight_xgb_class_1': 0.7097887499394153, 'weight_xgb_class_2': 0.5644875916838854}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:22,700] Trial 1646 finished with value: 0.9495826935589378 and parameters: {'weight_lgbm_class_0': 0.06972288690519107, 'weight_lgbm_class_1': 0.9459167902625033, 'weight_lgbm_class_2': 0.414679574030113, 'weight_xgb_class_0': 0.051674813592134425, 'weight_xgb_class_1': 0.7151052270737224, 'weight_xgb_class_2': 0.5602805351420129}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:22,724] Trial 1647 finished with value: 0.9496830605272241 and parameters: {'weight_lgbm_class_0': 0.06884988001093659, 'weight_lgbm_class_1': 0.9996164209140257, 'weight_lgbm_class_2': 0.42772990735975985, 'weight_xgb_class_0': 0.05035561045075507, 'weight_xgb_class_1': 0.716071486217097, 'weight_xgb_class_2': 0.5650971892742569}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  83%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▍                      | 1653/2000 [00:51<00:14, 24.24it/s]

[I 2026-07-05 15:32:22,774] Trial 1648 finished with value: 0.9497091919896361 and parameters: {'weight_lgbm_class_0': 0.06818192137132609, 'weight_lgbm_class_1': 0.9502992669160183, 'weight_lgbm_class_2': 0.4325996413848288, 'weight_xgb_class_0': 0.049713035595015005, 'weight_xgb_class_1': 0.7113242986564343, 'weight_xgb_class_2': 0.5606235130083657}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:22,813] Trial 1649 finished with value: 0.9498555083296752 and parameters: {'weight_lgbm_class_0': 0.07001761671192341, 'weight_lgbm_class_1': 0.9505947789357837, 'weight_lgbm_class_2': 0.42976336909459834, 'weight_xgb_class_0': 0.041678687020208355, 'weight_xgb_class_1': 0.715373018099148, 'weight_xgb_class_2': 0.5638329443912058}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:22,834] Trial 1650 finished with value: 0.9497019768225762 and parameters: {'weight_lgbm_class_0': 0.07385755407999244, 'weight_lgbm_class_1': 0.9493925972655802, 'weight_lgbm_class_2': 0.4316765151440667, 'weight_xgb_class_0': 0.036631328625938764, 'weight_xgb_class_1': 0.42883562289773436, 'weight_xgb_class_2': 0.5307740245044965}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:22,872] Trial 1651 finished with value: 0.9498433146611923 and parameters: {'weight_lgbm_class_0': 0.06858912054254743, 'weight_lgbm_class_1': 0.9480494873232775, 'weight_lgbm_class_2': 0.42623060357002407, 'weight_xgb_class_0': 0.03305959646115056, 'weight_xgb_class_1': 0.7103904797354332, 'weight_xgb_class_2': 0.5318805705500137}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:22,906] Trial 1652 finished with value: 0.9497353244723009 and parameters: {'weight_lgbm_class_0': 0.07867798286486768, 'weight_lgbm_class_1': 0.951566982329504, 'weight_lgbm_class_2': 0.43156374579640155, 'weight_xgb_class_0': 0.03584434274130005, 'weight_xgb_class_1': 0.7108998840769595, 'weight_xgb_class_2': 0.5352031112484087}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:22,952] Trial 1653 finished with value: 0.9498560526124686 and parameters: {'weight_lgbm_class_0': 0.07126615046448764, 'weight_lgbm_class_1': 0.9510654513361512, 'weight_lgbm_class_2': 0.4315845652777126, 'weight_xgb_class_0': 0.03677267328779456, 'weight_xgb_class_1': 0.710772308737063, 'weight_xgb_class_2': 0.534542477369042}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  83%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▊                      | 1658/2000 [00:51<00:15, 21.69it/s]

[I 2026-07-05 15:32:23,001] Trial 1654 finished with value: 0.9498119563763835 and parameters: {'weight_lgbm_class_0': 0.06818942454528848, 'weight_lgbm_class_1': 0.9517411992953524, 'weight_lgbm_class_2': 0.4340073014659553, 'weight_xgb_class_0': 0.036075217504063034, 'weight_xgb_class_1': 0.7132875984132862, 'weight_xgb_class_2': 0.5273851053774724}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:23,063] Trial 1656 finished with value: 0.9498540947816426 and parameters: {'weight_lgbm_class_0': 0.06930844829317066, 'weight_lgbm_class_1': 0.9537259308889957, 'weight_lgbm_class_2': 0.42574896868076845, 'weight_xgb_class_0': 0.033333142779738305, 'weight_xgb_class_1': 0.7139761385706274, 'weight_xgb_class_2': 0.5332472549124012}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:23,076] Trial 1655 finished with value: 0.9498147117712797 and parameters: {'weight_lgbm_class_0': 0.0717294029969944, 'weight_lgbm_class_1': 0.9532876248430872, 'weight_lgbm_class_2': 0.4286579285632221, 'weight_xgb_class_0': 0.03306670195353689, 'weight_xgb_class_1': 0.712856579353219, 'weight_xgb_class_2': 0.5305426545440399}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:23,173] Trial 1658 finished with value: 0.9498451545843043 and parameters: {'weight_lgbm_class_0': 0.07389918234514936, 'weight_lgbm_class_1': 0.9606860689900377, 'weight_lgbm_class_2': 0.40417064584080314, 'weight_xgb_class_0': 0.031770744011969734, 'weight_xgb_class_1': 0.7261597463351924, 'weight_xgb_class_2': 0.5322942234689186}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████                      | 1662/2000 [00:51<00:14, 23.04it/s]

[I 2026-07-05 15:32:23,207] Trial 1657 finished with value: 0.9498479585013292 and parameters: {'weight_lgbm_class_0': 0.07418413872828071, 'weight_lgbm_class_1': 0.9579655481381121, 'weight_lgbm_class_2': 0.4284094658867776, 'weight_xgb_class_0': 0.03466504176051652, 'weight_xgb_class_1': 0.7165112790408825, 'weight_xgb_class_2': 0.5374855674026469}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:23,229] Trial 1659 finished with value: 0.9498419935749888 and parameters: {'weight_lgbm_class_0': 0.10424152892904151, 'weight_lgbm_class_1': 0.9581778529602037, 'weight_lgbm_class_2': 0.43464386603129856, 'weight_xgb_class_0': 0.0005676735758956518, 'weight_xgb_class_1': 0.7304223824504119, 'weight_xgb_class_2': 0.5307150268872945}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:23,290] Trial 1661 finished with value: 0.949699470262637 and parameters: {'weight_lgbm_class_0': 0.08125608408993282, 'weight_lgbm_class_1': 0.9628908683500317, 'weight_lgbm_class_2': 0.4374310387530013, 'weight_xgb_class_0': 0.0348499946611645, 'weight_xgb_class_1': 0.7268296020997868, 'weight_xgb_class_2': 0.5304987796455696}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:23,293] Trial 1660 finished with value: 0.9497042057422297 and parameters: {'weight_lgbm_class_0': 0.07971950235081719, 'weight_lgbm_class_1': 0.9617266698117511, 'weight_lgbm_class_2': 0.4352012890021079, 'weight_xgb_class_0': 0.036175058068521435, 'weight_xgb_class_1': 0.7273544744455351, 'weight_xgb_class_2': 0.533617758274641}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:23,354] Trial 1662 finished with value: 0.9498213504429054 and parameters: {'weight_lgbm_class_0': 0.07097549498671041, 'weight_lgbm_class_1': 0.9588663285208574, 'weight_lgbm_class_2': 0.4081410996273941, 'weight_xgb_class_0': 0.03550190256202351, 'weight_xgb_class_1': 0.7238845103037987, 'weight_xgb_class_2': 0.52424848955779}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                     | 1668/2000 [00:52<00:13, 23.98it/s]

[I 2026-07-05 15:32:23,425] Trial 1663 finished with value: 0.9495505261885927 and parameters: {'weight_lgbm_class_0': 0.07676691966524951, 'weight_lgbm_class_1': 0.9604560340709154, 'weight_lgbm_class_2': 0.40856622092703504, 'weight_xgb_class_0': 0.034576409027507755, 'weight_xgb_class_1': 0.7331547957302067, 'weight_xgb_class_2': 0.4780204289361448}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:23,427] Trial 1664 finished with value: 0.9498000239484682 and parameters: {'weight_lgbm_class_0': 0.07155659114794928, 'weight_lgbm_class_1': 0.9624688996401718, 'weight_lgbm_class_2': 0.4389236689051997, 'weight_xgb_class_0': 0.03431121509681948, 'weight_xgb_class_1': 0.7250311896232381, 'weight_xgb_class_2': 0.4743213396836965}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:23,463] Trial 1665 finished with value: 0.9490870672052586 and parameters: {'weight_lgbm_class_0': 0.07326626008230866, 'weight_lgbm_class_1': 0.9378604677457617, 'weight_lgbm_class_2': 0.44243879111226686, 'weight_xgb_class_0': 0.06097183598680569, 'weight_xgb_class_1': 0.7286106362592307, 'weight_xgb_class_2': 0.4765958744600003}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:23,495] Trial 1666 finished with value: 0.9491905575654176 and parameters: {'weight_lgbm_class_0': 0.06569274482532106, 'weight_lgbm_class_1': 0.9297453831865082, 'weight_lgbm_class_2': 0.44530303935723675, 'weight_xgb_class_0': 0.06448945426457836, 'weight_xgb_class_1': 0.7314937475802546, 'weight_xgb_class_2': 0.4795896841688477}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:23,566] Trial 1667 finished with value: 0.949430692862346 and parameters: {'weight_lgbm_class_0': 0.06214692004855098, 'weight_lgbm_class_1': 0.9281503743114682, 'weight_lgbm_class_2': 0.4745336649892041, 'weight_xgb_class_0': 0.06133048108097689, 'weight_xgb_class_1': 0.7267493791120725, 'weight_xgb_class_2': 0.4745088531721503}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:23,584] Trial 1668 finished with value: 0.9495479297164611 and parameters: {'weight_lgbm_class_0': 0.06464947012844356, 'weight_lgbm_class_1': 0.925444956681202, 'weight_lgbm_class_2': 0.4806903269066463, 'weight_xgb_class_0': 0.05650115442883176, 'weight_xgb_class_1': 0.7312613514241574, 'weight_xgb_class_2': 0.4787046998173505}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                     | 1674/2000 [00:52<00:14, 22.92it/s]

[I 2026-07-05 15:32:23,662] Trial 1669 finished with value: 0.9494818587275642 and parameters: {'weight_lgbm_class_0': 0.06042718255020015, 'weight_lgbm_class_1': 0.9359514085778423, 'weight_lgbm_class_2': 0.44737336167076985, 'weight_xgb_class_0': 0.059525527833846695, 'weight_xgb_class_1': 0.7312395244586962, 'weight_xgb_class_2': 0.4783857151374959}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:23,689] Trial 1670 finished with value: 0.9493541917083723 and parameters: {'weight_lgbm_class_0': 0.06150399758878694, 'weight_lgbm_class_1': 0.9244635634409165, 'weight_lgbm_class_2': 0.45220282435387565, 'weight_xgb_class_0': 0.06301414291028418, 'weight_xgb_class_1': 0.7309062861880692, 'weight_xgb_class_2': 0.4746803095753165}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:23,721] Trial 1671 finished with value: 0.9497708513916484 and parameters: {'weight_lgbm_class_0': 0.054050216829737915, 'weight_lgbm_class_1': 0.9228462191820603, 'weight_lgbm_class_2': 0.4381977553694787, 'weight_xgb_class_0': 0.059811704254793124, 'weight_xgb_class_1': 0.7283659668571107, 'weight_xgb_class_2': 0.5347363472942854}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:23,800] Trial 1673 finished with value: 0.9492994528353907 and parameters: {'weight_lgbm_class_0': 0.0602157158253836, 'weight_lgbm_class_1': 0.9267517809507932, 'weight_lgbm_class_2': 0.44636834820327476, 'weight_xgb_class_0': 0.06503135028022372, 'weight_xgb_class_1': 0.7367803407041491, 'weight_xgb_class_2': 0.47307142480647046}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:23,852] Trial 1672 finished with value: 0.9492969162345721 and parameters: {'weight_lgbm_class_0': 0.06462164985247806, 'weight_lgbm_class_1': 0.9300588627479848, 'weight_lgbm_class_2': 0.44382818797350165, 'weight_xgb_class_0': 0.06122874236452154, 'weight_xgb_class_1': 0.7342726862897336, 'weight_xgb_class_2': 0.47948976977446656}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:23,868] Trial 1674 finished with value: 0.9495251602832032 and parameters: {'weight_lgbm_class_0': 0.06370573035621267, 'weight_lgbm_class_1': 0.9233479404336911, 'weight_lgbm_class_2': 0.4515765117494168, 'weight_xgb_class_0': 0.06090146307649272, 'weight_xgb_class_1': 0.73716593156186, 'weight_xgb_class_2': 0.5308225787768657}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  84%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                    | 1680/2000 [00:52<00:13, 23.56it/s]

[I 2026-07-05 15:32:23,938] Trial 1675 finished with value: 0.949665415536789 and parameters: {'weight_lgbm_class_0': 0.057696674921458205, 'weight_lgbm_class_1': 0.92312697050036, 'weight_lgbm_class_2': 0.44654948144991735, 'weight_xgb_class_0': 0.059615738495285744, 'weight_xgb_class_1': 0.7371477012076927, 'weight_xgb_class_2': 0.5271616697427531}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:23,947] Trial 1676 finished with value: 0.949424764635992 and parameters: {'weight_lgbm_class_0': 0.06301952164489757, 'weight_lgbm_class_1': 0.9293951389605284, 'weight_lgbm_class_2': 0.45054369631210084, 'weight_xgb_class_0': 0.06581003069959536, 'weight_xgb_class_1': 0.7384997245366839, 'weight_xgb_class_2': 0.5302237168026162}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:24,018] Trial 1678 finished with value: 0.9491455953999299 and parameters: {'weight_lgbm_class_0': 0.059762232553388694, 'weight_lgbm_class_1': 0.9271201703631304, 'weight_lgbm_class_2': 0.41014409347402037, 'weight_xgb_class_0': 0.06459258061012521, 'weight_xgb_class_1': 0.7401568003225881, 'weight_xgb_class_2': 0.4510738199726412}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:24,062] Trial 1677 finished with value: 0.9152815857010926 and parameters: {'weight_lgbm_class_0': 0.06137776624337199, 'weight_lgbm_class_1': 0.9249349054877402, 'weight_lgbm_class_2': 0.450290761433284, 'weight_xgb_class_0': 0.616364267910856, 'weight_xgb_class_1': 0.7376383883288518, 'weight_xgb_class_2': 0.5326135403385938}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:24,086] Trial 1679 finished with value: 0.9492647270833143 and parameters: {'weight_lgbm_class_0': 0.06674898001976233, 'weight_lgbm_class_1': 0.9260556863919558, 'weight_lgbm_class_2': 0.4112702487177658, 'weight_xgb_class_0': 0.06335549815942687, 'weight_xgb_class_1': 0.7401376792528854, 'weight_xgb_class_2': 0.5318555170717918}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:24,093] Trial 1680 finished with value: 0.9494180351395701 and parameters: {'weight_lgbm_class_0': 0.06225282604191299, 'weight_lgbm_class_1': 0.9240934358418809, 'weight_lgbm_class_2': 0.4145571624063884, 'weight_xgb_class_0': 0.061899144015811605, 'weight_xgb_class_1': 0.7385991767976354, 'weight_xgb_class_2': 0.5306968109104596}. Best is trial 1561 with value: 0.9498642565074636.

[I 2026-07-05 15:32:24,184] Trial 1681 finished with value: 0.949449663459642 and parameters: {'weight_lgbm_class_0': 0.0616202533332208, 'weight_lgbm_class_1': 0.9276338862534926, 'weight_lgbm_class_2': 0.41315186208775484, 'weight_xgb_class_0': 0.061157692625311705, 'weight_xgb_class_1': 0.7374822643035769, 'weight_xgb_class_2': 0.5319514799853043}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:24,188] Trial 1682 finished with value: 0.949279719161224 and parameters: {'weight_lgbm_class_0': 0.06520401440608627, 'weight_lgbm_class_1': 0.9259363841001768, 'weight_lgbm_class_2': 0.4108203385552994, 'weight_xgb_class_0': 0.06190107043486076, 'weight_xgb_class_1': 0.7412000301794153, 'weight_xgb_class_2': 0.5165570753287141}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:24,189] Trial 1683 finished with value: 0.9493691959168142 and parameters: {'weight_lgbm_class_0': 0.06069512425343415, 'weight_lgbm_class_1': 0.9245335413133646, 'weight_lgbm_class_2': 0.40979925655677746, 'weight_xgb_class_0': 0.062380683352952535, 'weight_xgb_class_1': 0.74750076042254, 'weight_xgb_class_2': 0.5122667222779139}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:24,297] Trial 1684 finished with value: 0.9494513780297327 and parameters: {'weight_lgbm_class_0': 0.06413639119827128, 'weight_lgbm_class_1': 0.921890329562387, 'weight_lgbm_class_2': 0.4116500794612295, 'weight_xgb_class_0': 0.057116904719461965, 'weight_xgb_class_1': 0.743485280451393, 'weight_xgb_class_2': 0.5154920581343219}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:24,328] Trial 1685 finished with value: 0.9493976452887637 and parameters: {'weight_lgbm_class_0': 0.07859093618077335, 'weight_lgbm_class_1': 0.9393404188297322, 'weight_lgbm_class_2': 0.4139874576511203, 'weight_xgb_class_0': 0.04503008917407751, 'weight_xgb_class_1': 0.7094065532014902, 'weight_xgb_class_2': 0.5156275814189775}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  84%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                    | 1690/2000 [00:53<00:13, 23.03it/s]

[I 2026-07-05 15:32:24,365] Trial 1686 finished with value: 0.9492823087020318 and parameters: {'weight_lgbm_class_0': 0.0843466058176746, 'weight_lgbm_class_1': 0.9393428878382443, 'weight_lgbm_class_2': 0.41116647907780096, 'weight_xgb_class_0': 0.04241834471733614, 'weight_xgb_class_1': 0.7082156052151865, 'weight_xgb_class_2': 0.5154802345374921}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:24,432] Trial 1688 finished with value: 0.9491428512181096 and parameters: {'weight_lgbm_class_0': 0.08467638382375502, 'weight_lgbm_class_1': 0.9416267700325783, 'weight_lgbm_class_2': 0.41267290815536156, 'weight_xgb_class_0': 0.04816533672736411, 'weight_xgb_class_1': 0.7085055354173373, 'weight_xgb_class_2': 0.5141130904266146}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:24,471] Trial 1687 finished with value: 0.9493188895969701 and parameters: {'weight_lgbm_class_0': 0.08127681814385747, 'weight_lgbm_class_1': 0.94128005286874, 'weight_lgbm_class_2': 0.4047085211953492, 'weight_xgb_class_0': 0.043783381000616975, 'weight_xgb_class_1': 0.7011756619382511, 'weight_xgb_class_2': 0.513384406087531}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:24,491] Trial 1689 finished with value: 0.9493380850022112 and parameters: {'weight_lgbm_class_0': 0.0799461488517333, 'weight_lgbm_class_1': 0.9443990398909249, 'weight_lgbm_class_2': 0.4143530728125423, 'weight_xgb_class_0': 0.04518961978057855, 'weight_xgb_class_1': 0.705562010393706, 'weight_xgb_class_2': 0.5094590804132278}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:24,591] Trial 1691 finished with value: 0.9493720840690133 and parameters: {'weight_lgbm_class_0': 0.08237419363947548, 'weight_lgbm_class_1': 0.9476882390356821, 'weight_lgbm_class_2': 0.41074893662520384, 'weight_xgb_class_0': 0.04042631669018602, 'weight_xgb_class_1': 0.7076836250452264, 'weight_xgb_class_2': 0.5113518823314813}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                   | 1695/2000 [00:53<00:12, 24.20it/s]

[I 2026-07-05 15:32:24,591] Trial 1692 finished with value: 0.9494073289253625 and parameters: {'weight_lgbm_class_0': 0.08244623522119152, 'weight_lgbm_class_1': 0.9423042110630465, 'weight_lgbm_class_2': 0.41244862410286975, 'weight_xgb_class_0': 0.04023257487976423, 'weight_xgb_class_1': 0.7084283281214999, 'weight_xgb_class_2': 0.5133938292822915}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:24,592] Trial 1690 finished with value: 0.9493828927655917 and parameters: {'weight_lgbm_class_0': 0.086897203852609, 'weight_lgbm_class_1': 0.9466633023609481, 'weight_lgbm_class_2': 0.4121103126743769, 'weight_xgb_class_0': 0.03522299534419645, 'weight_xgb_class_1': 0.7086932627224442, 'weight_xgb_class_2': 0.5087765062562213}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:24,683] Trial 1693 finished with value: 0.9010754804373408 and parameters: {'weight_lgbm_class_0': 0.08566986402344522, 'weight_lgbm_class_1': 0.9436986771892993, 'weight_lgbm_class_2': 0.4274473321739996, 'weight_xgb_class_0': 0.7831443037274718, 'weight_xgb_class_1': 0.7057991346525756, 'weight_xgb_class_2': 0.544179246327341}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:24,728] Trial 1694 finished with value: 0.9493873104691405 and parameters: {'weight_lgbm_class_0': 0.08936523925050488, 'weight_lgbm_class_1': 0.9458587458252261, 'weight_lgbm_class_2': 0.42781282635375656, 'weight_xgb_class_0': 0.03998764247481644, 'weight_xgb_class_1': 0.712283456090318, 'weight_xgb_class_2': 0.548830502967152}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:24,753] Trial 1695 finished with value: 0.949470754817202 and parameters: {'weight_lgbm_class_0': 0.08835164865967714, 'weight_lgbm_class_1': 0.945768761395388, 'weight_lgbm_class_2': 0.427257056028327, 'weight_xgb_class_0': 0.03799717611113941, 'weight_xgb_class_1': 0.7050713838777839, 'weight_xgb_class_2': 0.5471723015118193}. Best is trial 1561 with value: 0.9498642565074636.

[I 2026-07-05 15:32:24,829] Trial 1696 finished with value: 0.9492684615273057 and parameters: {'weight_lgbm_class_0': 0.0955009375970252, 'weight_lgbm_class_1': 0.9426309336621012, 'weight_lgbm_class_2': 0.428874074919164, 'weight_xgb_class_0': 0.03745437817189365, 'weight_xgb_class_1': 0.7016642769572745, 'weight_xgb_class_2': 0.5488753072860291}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:24,848] Trial 1697 finished with value: 0.9492107950449175 and parameters: {'weight_lgbm_class_0': 0.08817618266612248, 'weight_lgbm_class_1': 0.2696365740688915, 'weight_lgbm_class_2': 0.4320438522708633, 'weight_xgb_class_0': 0.03538512075439847, 'weight_xgb_class_1': 0.7072720316409358, 'weight_xgb_class_2': 0.5552183503632145}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:24,895] Trial 1698 finished with value: 0.9497839388871115 and parameters: {'weight_lgbm_class_0': 0.07977928114650501, 'weight_lgbm_class_1': 0.9466669002740518, 'weight_lgbm_class_2': 0.4307151896137969, 'weight_xgb_class_0': 0.034444873714572215, 'weight_xgb_class_1': 0.7083370461883236, 'weight_xgb_class_2': 0.5471703686535913}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:24,978] Trial 1700 finished with value: 0.949471116800311 and parameters: {'weight_lgbm_class_0': 0.09315482307544365, 'weight_lgbm_class_1': 0.9483964264248549, 'weight_lgbm_class_2': 0.4346838644747112, 'weight_xgb_class_0': 0.03353247445068504, 'weight_xgb_class_1': 0.7052526100286264, 'weight_xgb_class_2': 0.5436600993048131}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:24,987] Trial 1701 finished with value: 0.9495554283036216 and parameters: {'weight_lgbm_class_0': 0.09031614277015998, 'weight_lgbm_class_1': 0.9534417398096666, 'weight_lgbm_class_2': 0.4310196772545445, 'weight_xgb_class_0': 0.033095937803934855, 'weight_xgb_class_1': 0.7096863069287159, 'weight_xgb_class_2': 0.5494304497955721}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                   | 1705/2000 [00:53<00:13, 22.00it/s]

[I 2026-07-05 15:32:24,990] Trial 1699 finished with value: 0.9494107273461134 and parameters: {'weight_lgbm_class_0': 0.09795879947563194, 'weight_lgbm_class_1': 0.9481783126297566, 'weight_lgbm_class_2': 0.46306298022322256, 'weight_xgb_class_0': 0.03365194705964078, 'weight_xgb_class_1': 0.7128470880264542, 'weight_xgb_class_2': 0.5473465162573594}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:25,111] Trial 1703 finished with value: 0.9495593026418332 and parameters: {'weight_lgbm_class_0': 0.09583835418381675, 'weight_lgbm_class_1': 0.948719938815906, 'weight_lgbm_class_2': 0.4330942381344991, 'weight_xgb_class_0': 0.027393056798215496, 'weight_xgb_class_1': 0.718587525454389, 'weight_xgb_class_2': 0.5463218176234274}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:25,115] Trial 1702 finished with value: 0.9497874198442325 and parameters: {'weight_lgbm_class_0': 0.09001245376935664, 'weight_lgbm_class_1': 0.9539437268043298, 'weight_lgbm_class_2': 0.4680311677160543, 'weight_xgb_class_0': 0.02666093137662613, 'weight_xgb_class_1': 0.7169797062840724, 'weight_xgb_class_2': 0.546595937260748}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:25,136] Trial 1704 finished with value: 0.949678359740424 and parameters: {'weight_lgbm_class_0': 0.08688608933362993, 'weight_lgbm_class_1': 0.9545929302580928, 'weight_lgbm_class_2': 0.4317837942022363, 'weight_xgb_class_0': 0.029969990511978743, 'weight_xgb_class_1': 0.7178291043119595, 'weight_xgb_class_2': 0.5446911907512388}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:25,187] Trial 1705 finished with value: 0.9496151229434843 and parameters: {'weight_lgbm_class_0': 0.10047978390876203, 'weight_lgbm_class_1': 0.9588359885450157, 'weight_lgbm_class_2': 0.4682977430442393, 'weight_xgb_class_0': 0.022035723822354233, 'weight_xgb_class_1': 0.7188944952881988, 'weight_xgb_class_2': 0.5487736139110687}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                  | 1710/2000 [00:54<00:12, 23.64it/s]

[I 2026-07-05 15:32:25,258] Trial 1706 finished with value: 0.9496374852691121 and parameters: {'weight_lgbm_class_0': 0.10061503126346506, 'weight_lgbm_class_1': 0.9614172091579297, 'weight_lgbm_class_2': 0.46133254841291316, 'weight_xgb_class_0': 0.021394462336880977, 'weight_xgb_class_1': 0.7232748676469809, 'weight_xgb_class_2': 0.5484398439444406}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:25,273] Trial 1707 finished with value: 0.9496490587413654 and parameters: {'weight_lgbm_class_0': 0.10104083355720841, 'weight_lgbm_class_1': 0.9604580032315936, 'weight_lgbm_class_2': 0.47547224443048897, 'weight_xgb_class_0': 0.02219017316969571, 'weight_xgb_class_1': 0.7157776284044771, 'weight_xgb_class_2': 0.5490055162307503}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:25,347] Trial 1710 finished with value: 0.9496891839651425 and parameters: {'weight_lgbm_class_0': 0.10131068060705944, 'weight_lgbm_class_1': 0.9626817071335603, 'weight_lgbm_class_2': 0.47741003660881004, 'weight_xgb_class_0': 0.0236321182158286, 'weight_xgb_class_1': 0.7283875454978284, 'weight_xgb_class_2': 0.5792343776998572}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:25,357] Trial 1709 finished with value: 0.9497101573121919 and parameters: {'weight_lgbm_class_0': 0.10338844975338221, 'weight_lgbm_class_1': 0.9636623214307984, 'weight_lgbm_class_2': 0.4578695850944368, 'weight_xgb_class_0': 0.019343937899537235, 'weight_xgb_class_1': 0.7256962145123879, 'weight_xgb_class_2': 0.577167554466496}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:25,380] Trial 1708 finished with value: 0.9496910538547964 and parameters: {'weight_lgbm_class_0': 0.10004078661104497, 'weight_lgbm_class_1': 0.9592151047287248, 'weight_lgbm_class_2': 0.46548517501016423, 'weight_xgb_class_0': 0.019530583689458803, 'weight_xgb_class_1': 0.7228699076247513, 'weight_xgb_class_2': 0.5475839678938899}. Best is trial 1561 with value: 0.9498642565074636.

[I 2026-07-05 15:32:25,480] Trial 1712 finished with value: 0.949812328079358 and parameters: {'weight_lgbm_class_0': 0.10058032749288776, 'weight_lgbm_class_1': 0.9659230945962898, 'weight_lgbm_class_2': 0.4797508758088281, 'weight_xgb_class_0': 0.017287153067158476, 'weight_xgb_class_1': 0.7226324123414537, 'weight_xgb_class_2': 0.5728595237574363}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:25,482] Trial 1711 finished with value: 0.9497946423822624 and parameters: {'weight_lgbm_class_0': 0.10245064284987039, 'weight_lgbm_class_1': 0.9634546385424658, 'weight_lgbm_class_2': 0.4763702337935762, 'weight_xgb_class_0': 0.018255450965285937, 'weight_xgb_class_1': 0.7302462197026726, 'weight_xgb_class_2': 0.5798408732549714}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:25,496] Trial 1713 finished with value: 0.949727975869387 and parameters: {'weight_lgbm_class_0': 0.10436382559239736, 'weight_lgbm_class_1': 0.9631231118697301, 'weight_lgbm_class_2': 0.4729559038466331, 'weight_xgb_class_0': 0.018997263778206062, 'weight_xgb_class_1': 0.7207886281476, 'weight_xgb_class_2': 0.5803800441866986}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:25,629] Trial 1714 finished with value: 0.9496315856188864 and parameters: {'weight_lgbm_class_0': 0.10955149387519125, 'weight_lgbm_class_1': 0.9679968856044507, 'weight_lgbm_class_2': 0.4603667400442578, 'weight_xgb_class_0': 0.016277121106246236, 'weight_xgb_class_1': 0.7479412115733728, 'weight_xgb_class_2': 0.5836353036267435}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:25,647] Trial 1715 finished with value: 0.9496702403479675 and parameters: {'weight_lgbm_class_0': 0.1077861274909398, 'weight_lgbm_class_1': 0.9696041219682539, 'weight_lgbm_class_2': 0.47493145794431596, 'weight_xgb_class_0': 0.017880038992322538, 'weight_xgb_class_1': 0.7417165013741873, 'weight_xgb_class_2': 0.5770710624810921}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                  | 1721/2000 [00:54<00:11, 23.48it/s]

[I 2026-07-05 15:32:25,673] Trial 1716 finished with value: 0.9281112136806716 and parameters: {'weight_lgbm_class_0': 0.10978168720759325, 'weight_lgbm_class_1': 0.9706759282474672, 'weight_lgbm_class_2': 0.4583146884582756, 'weight_xgb_class_0': 0.42719406475062266, 'weight_xgb_class_1': 0.7453995198191053, 'weight_xgb_class_2': 0.5852548896049526}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:25,699] Trial 1717 finished with value: 0.9496398334535819 and parameters: {'weight_lgbm_class_0': 0.10731723261452628, 'weight_lgbm_class_1': 0.9679165924967321, 'weight_lgbm_class_2': 0.4594357269984665, 'weight_xgb_class_0': 0.01695438437744496, 'weight_xgb_class_1': 0.7475857925551856, 'weight_xgb_class_2': 0.5726695034342948}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:25,768] Trial 1719 finished with value: 0.9495924365325864 and parameters: {'weight_lgbm_class_0': 0.05947356877364053, 'weight_lgbm_class_1': 0.965586434034638, 'weight_lgbm_class_2': 0.46018093453235, 'weight_xgb_class_0': 0.02028392882359982, 'weight_xgb_class_1': 0.7438450413572966, 'weight_xgb_class_2': 0.5771187202480804}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:25,781] Trial 1718 finished with value: 0.9494786636760133 and parameters: {'weight_lgbm_class_0': 0.05645191814439231, 'weight_lgbm_class_1': 0.9686557686446491, 'weight_lgbm_class_2': 0.4569282643095002, 'weight_xgb_class_0': 0.01850318514140474, 'weight_xgb_class_1': 0.74799432653734, 'weight_xgb_class_2': 0.5767790430436759}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:25,823] Trial 1720 finished with value: 0.9081354214603055 and parameters: {'weight_lgbm_class_0': 0.7773774635813434, 'weight_lgbm_class_1': 0.9691105948865444, 'weight_lgbm_class_2': 0.39610922922155006, 'weight_xgb_class_0': 0.00019999023609876848, 'weight_xgb_class_1': 0.74752148804835, 'weight_xgb_class_2': 0.5797369406708429}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:25,886] Trial 1721 finished with value: 0.949610502192623 and parameters: {'weight_lgbm_class_0': 0.06327777550302396, 'weight_lgbm_class_1': 0.9690817545313508, 'weight_lgbm_class_2': 0.3967921537819133, 'weight_xgb_class_0': 0.017974716997650953, 'weight_xgb_class_1': 0.7469166651950992, 'weight_xgb_class_2': 0.5780954866024246}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                 | 1725/2000 [00:54<00:11, 24.53it/s]

[I 2026-07-05 15:32:25,888] Trial 1722 finished with value: 0.9494424804772293 and parameters: {'weight_lgbm_class_0': 0.054332991740009856, 'weight_lgbm_class_1': 0.9637162803282798, 'weight_lgbm_class_2': 0.3914067488945164, 'weight_xgb_class_0': 0.01769026540825287, 'weight_xgb_class_1': 0.7506390931438723, 'weight_xgb_class_2': 0.5783112033423461}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:25,976] Trial 1724 finished with value: 0.9495291555285817 and parameters: {'weight_lgbm_class_0': 0.05839265370187574, 'weight_lgbm_class_1': 0.9157340191390276, 'weight_lgbm_class_2': 0.3918639351728432, 'weight_xgb_class_0': 0.01716920530098389, 'weight_xgb_class_1': 0.746803441454691, 'weight_xgb_class_2': 0.5724029388229521}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:25,984] Trial 1723 finished with value: 0.9498263678827001 and parameters: {'weight_lgbm_class_0': 0.05679755001948136, 'weight_lgbm_class_1': 0.9705337149734389, 'weight_lgbm_class_2': 0.3949578387745709, 'weight_xgb_class_0': 0.05084233172194623, 'weight_xgb_class_1': 0.7537102227164326, 'weight_xgb_class_2': 0.5733942713176654}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:26,046] Trial 1725 finished with value: 0.9494918324202294 and parameters: {'weight_lgbm_class_0': 0.058506502529561535, 'weight_lgbm_class_1': 0.9702381032188417, 'weight_lgbm_class_2': 0.39330003380216755, 'weight_xgb_class_0': 0.0178052409732914, 'weight_xgb_class_1': 0.7545716291635691, 'weight_xgb_class_2': 0.5719043079296996}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  87%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                 | 1731/2000 [00:54<00:12, 22.23it/s]

[I 2026-07-05 15:32:26,160] Trial 1727 finished with value: 0.9492388579362455 and parameters: {'weight_lgbm_class_0': 0.05951254458985589, 'weight_lgbm_class_1': 0.9240018211318756, 'weight_lgbm_class_2': 0.38850955567471895, 'weight_xgb_class_0': 0.0003426788162496086, 'weight_xgb_class_1': 0.6909057464059128, 'weight_xgb_class_2': 0.5287533848307492}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:26,161] Trial 1726 finished with value: 0.9494444756451018 and parameters: {'weight_lgbm_class_0': 0.07217939948600782, 'weight_lgbm_class_1': 0.9199717793354834, 'weight_lgbm_class_2': 0.3981769340169605, 'weight_xgb_class_0': 0.04807513712793991, 'weight_xgb_class_1': 0.6934304758887627, 'weight_xgb_class_2': 0.5307740198500716}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:26,225] Trial 1728 finished with value: 0.9493015038326605 and parameters: {'weight_lgbm_class_0': 0.060200211588531366, 'weight_lgbm_class_1': 0.9214628787454479, 'weight_lgbm_class_2': 0.3973570565054604, 'weight_xgb_class_0': 0.0005207344122602001, 'weight_xgb_class_1': 0.6907097849278986, 'weight_xgb_class_2': 0.4937217416933284}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:26,230] Trial 1729 finished with value: 0.9495122143807645 and parameters: {'weight_lgbm_class_0': 0.06362698287383979, 'weight_lgbm_class_1': 0.9224834356127455, 'weight_lgbm_class_2': 0.38922002437686587, 'weight_xgb_class_0': 0.05490155354696752, 'weight_xgb_class_1': 0.691296849687219, 'weight_xgb_class_2': 0.5346588803919441}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:26,318] Trial 1731 finished with value: 0.9469266734241405 and parameters: {'weight_lgbm_class_0': 0.058397548758436765, 'weight_lgbm_class_1': 0.9159881293899703, 'weight_lgbm_class_2': 0.3929357493067339, 'weight_xgb_class_0': 0.050251511537005314, 'weight_xgb_class_1': 0.6925770681105181, 'weight_xgb_class_2': 0.07447884970289981}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:26,336] Trial 1730 finished with value: 0.9495802758860861 and parameters: {'weight_lgbm_class_0': 0.06591588660150875, 'weight_lgbm_class_1': 0.9192079472036271, 'weight_lgbm_class_2': 0.38967762949071827, 'weight_xgb_class_0': 0.04814380546469171, 'weight_xgb_class_1': 0.6904424954814373, 'weight_xgb_class_2': 0.5292049645674338}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  87%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                 | 1737/2000 [00:55<00:10, 24.47it/s]

[I 2026-07-05 15:32:26,347] Trial 1732 finished with value: 0.9497618085063463 and parameters: {'weight_lgbm_class_0': 0.06114977508427524, 'weight_lgbm_class_1': 0.9111286598343069, 'weight_lgbm_class_2': 0.3903024658283194, 'weight_xgb_class_0': 0.04807046988701144, 'weight_xgb_class_1': 0.6923894407691497, 'weight_xgb_class_2': 0.5294150904303505}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:26,433] Trial 1734 finished with value: 0.9495181338741939 and parameters: {'weight_lgbm_class_0': 0.07265856949208886, 'weight_lgbm_class_1': 0.9151949812682334, 'weight_lgbm_class_2': 0.4399426945886859, 'weight_xgb_class_0': 0.04552363495454806, 'weight_xgb_class_1': 0.6870980955585718, 'weight_xgb_class_2': 0.4927133942668366}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:26,460] Trial 1733 finished with value: 0.9494521764779472 and parameters: {'weight_lgbm_class_0': 0.07190000590884203, 'weight_lgbm_class_1': 0.9171377560785046, 'weight_lgbm_class_2': 0.4421738867753068, 'weight_xgb_class_0': 0.05229077958867011, 'weight_xgb_class_1': 0.6871884605281767, 'weight_xgb_class_2': 0.5249369818967908}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:26,508] Trial 1735 finished with value: 0.9493903462282315 and parameters: {'weight_lgbm_class_0': 0.07515393016787451, 'weight_lgbm_class_1': 0.9185650456383853, 'weight_lgbm_class_2': 0.43791569897635735, 'weight_xgb_class_0': 0.04854306888669817, 'weight_xgb_class_1': 0.6891206899010873, 'weight_xgb_class_2': 0.4979429577537598}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:26,512] Trial 1736 finished with value: 0.9495181989447153 and parameters: {'weight_lgbm_class_0': 0.07512132928921879, 'weight_lgbm_class_1': 0.9179391213533181, 'weight_lgbm_class_2': 0.4353799085368742, 'weight_xgb_class_0': 0.04683478877853582, 'weight_xgb_class_1': 0.6856987787749614, 'weight_xgb_class_2': 0.5291570307417535}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:26,532] Trial 1737 finished with value: 0.9496723656419209 and parameters: {'weight_lgbm_class_0': 0.07959853571888303, 'weight_lgbm_class_1': 0.9211276205706731, 'weight_lgbm_class_2': 0.4400780811764886, 'weight_xgb_class_0': 0.00010302136048009701, 'weight_xgb_class_1': 0.6847238674541202, 'weight_xgb_class_2': 0.5275289539426894}. Best is trial 1561 with value: 0.9498642565074636.

[I 2026-07-05 15:32:26,693] Trial 1738 finished with value: 0.8960444351166587 and parameters: {'weight_lgbm_class_0': 0.8758716465534477, 'weight_lgbm_class_1': 0.9361278377777202, 'weight_lgbm_class_2': 0.4386255852497549, 'weight_xgb_class_0': 0.04943750029365725, 'weight_xgb_class_1': 0.6926547535582167, 'weight_xgb_class_2': 0.5009205865354324}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:26,732] Trial 1739 finished with value: 0.948280370405017 and parameters: {'weight_lgbm_class_0': 0.13429754993115825, 'weight_lgbm_class_1': 0.9393582805529316, 'weight_lgbm_class_2': 0.4408153858901272, 'weight_xgb_class_0': 0.04068311599983308, 'weight_xgb_class_1': 0.6895129437578805, 'weight_xgb_class_2': 0.504795614364868}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:26,749] Trial 1740 finished with value: 0.9277156517722963 and parameters: {'weight_lgbm_class_0': 0.13341945984962528, 'weight_lgbm_class_1': 0.9414000750827523, 'weight_lgbm_class_2': 0.43517039501853916, 'weight_xgb_class_0': 0.3711034343985934, 'weight_xgb_class_1': 0.6891900874298472, 'weight_xgb_class_2': 0.5297629609100937}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:26,795] Trial 1741 finished with value: 0.9481899161963389 and parameters: {'weight_lgbm_class_0': 0.13071272796669578, 'weight_lgbm_class_1': 0.9444303983889569, 'weight_lgbm_class_2': 0.43740448588978065, 'weight_xgb_class_0': 0.046616915628754044, 'weight_xgb_class_1': 0.6911672793918963, 'weight_xgb_class_2': 0.4965547679049802}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:26,802] Trial 1743 finished with value: 0.948402291600336 and parameters: {'weight_lgbm_class_0': 0.13409327638704707, 'weight_lgbm_class_1': 0.9418770521087468, 'weight_lgbm_class_2': 0.4380490847163974, 'weight_xgb_class_0': 0.03838874218518377, 'weight_xgb_class_1': 0.6803410446647118, 'weight_xgb_class_2': 0.5063267324290831}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:26,836] Trial 1742 finished with value: 0.9484938856157861 and parameters: {'weight_lgbm_class_0': 0.12683085810295797, 'weight_lgbm_class_1': 0.9410460699294021, 'weight_lgbm_class_2': 0.43809507976134826, 'weight_xgb_class_0': 0.038249584057513, 'weight_xgb_class_1': 0.6820941312091979, 'weight_xgb_class_2': 0.49539396144880826}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                | 1750/2000 [00:55<00:09, 26.72it/s]

[I 2026-07-05 15:32:26,896] Trial 1744 finished with value: 0.9491257401815362 and parameters: {'weight_lgbm_class_0': 0.13433295881868051, 'weight_lgbm_class_1': 0.9419003744910454, 'weight_lgbm_class_2': 0.42852116926444594, 'weight_xgb_class_0': 0.00023694435428190871, 'weight_xgb_class_1': 0.6772738466225854, 'weight_xgb_class_2': 0.4998716552866742}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:26,926] Trial 1746 finished with value: 0.9491682604082555 and parameters: {'weight_lgbm_class_0': 0.13089334144114212, 'weight_lgbm_class_1': 0.9411663060297314, 'weight_lgbm_class_2': 0.43900776713836664, 'weight_xgb_class_0': 7.060908093862572e-05, 'weight_xgb_class_1': 0.20781202195478338, 'weight_xgb_class_2': 0.5550472499938714}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:26,970] Trial 1745 finished with value: 0.9492491003707727 and parameters: {'weight_lgbm_class_0': 0.13508422855304728, 'weight_lgbm_class_1': 0.9434657486026446, 'weight_lgbm_class_2': 0.43170323535642063, 'weight_xgb_class_0': 0.000608407417644744, 'weight_xgb_class_1': 0.676493941673907, 'weight_xgb_class_2': 0.5560131717351183}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:26,977] Trial 1747 finished with value: 0.9281849768771385 and parameters: {'weight_lgbm_class_0': 0.13397270610961606, 'weight_lgbm_class_1': 0.9824058409183064, 'weight_lgbm_class_2': 0.42293438903441255, 'weight_xgb_class_0': 0.3760324939730751, 'weight_xgb_class_1': 0.7030487958058125, 'weight_xgb_class_2': 0.5575867799514699}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:27,047] Trial 1748 finished with value: 0.948232443022385 and parameters: {'weight_lgbm_class_0': 0.13145622158880932, 'weight_lgbm_class_1': 0.9432745339106303, 'weight_lgbm_class_2': 0.4243012706907634, 'weight_xgb_class_0': 0.000878452277721482, 'weight_xgb_class_1': 0.7037091731627391, 'weight_xgb_class_2': 0.2723104842756891}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:27,062] Trial 1749 finished with value: 0.9492155865301103 and parameters: {'weight_lgbm_class_0': 0.1345236325457565, 'weight_lgbm_class_1': 0.9821003822636906, 'weight_lgbm_class_2': 0.42584317589252524, 'weight_xgb_class_0': 0.0007866503475628353, 'weight_xgb_class_1': 0.7250551313760322, 'weight_xgb_class_2': 0.5531610188942331}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████                | 1754/2000 [00:55<00:12, 20.47it/s]

[I 2026-07-05 15:32:27,189] Trial 1750 finished with value: 0.9492100758431145 and parameters: {'weight_lgbm_class_0': 0.13551651635466153, 'weight_lgbm_class_1': 0.9822771005668711, 'weight_lgbm_class_2': 0.42336075401309947, 'weight_xgb_class_0': 5.914716453953722e-05, 'weight_xgb_class_1': 0.7253733786632464, 'weight_xgb_class_2': 0.5542847857809066}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:27,263] Trial 1751 finished with value: 0.9496139884720289 and parameters: {'weight_lgbm_class_0': 0.11998244399488216, 'weight_lgbm_class_1': 0.9999797959056272, 'weight_lgbm_class_2': 0.4287316972127914, 'weight_xgb_class_0': 9.711014070029611e-05, 'weight_xgb_class_1': 0.7204708945562337, 'weight_xgb_class_2': 0.5562551906387379}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:27,305] Trial 1752 finished with value: 0.9494638358841786 and parameters: {'weight_lgbm_class_0': 0.1158357879685836, 'weight_lgbm_class_1': 0.9824738679664295, 'weight_lgbm_class_2': 0.494080092155578, 'weight_xgb_class_0': 0.018027887521300835, 'weight_xgb_class_1': 0.7306583859442799, 'weight_xgb_class_2': 0.558378487096921}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:27,315] Trial 1753 finished with value: 0.949438544699691 and parameters: {'weight_lgbm_class_0': 0.11467323797167905, 'weight_lgbm_class_1': 0.9994558957692081, 'weight_lgbm_class_2': 0.493345270863696, 'weight_xgb_class_0': 0.02060600771717787, 'weight_xgb_class_1': 0.7213124382705709, 'weight_xgb_class_2': 0.5571698730099792}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:27,333] Trial 1754 finished with value: 0.9498231817976607 and parameters: {'weight_lgbm_class_0': 0.1138540824530154, 'weight_lgbm_class_1': 0.9835556409613656, 'weight_lgbm_class_2': 0.4911237738970134, 'weight_xgb_class_0': 0.0003525114446746027, 'weight_xgb_class_1': 0.7246198220984439, 'weight_xgb_class_2': 0.5564846925443051}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍               | 1760/2000 [00:56<00:10, 22.32it/s]

[I 2026-07-05 15:32:27,336] Trial 1755 finished with value: 0.9495232358811597 and parameters: {'weight_lgbm_class_0': 0.11496267766123631, 'weight_lgbm_class_1': 0.2130729277488178, 'weight_lgbm_class_2': 0.4919953764783746, 'weight_xgb_class_0': 0.0005561533546079189, 'weight_xgb_class_1': 0.7276033410373403, 'weight_xgb_class_2': 0.5585840655794923}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:27,433] Trial 1756 finished with value: 0.9482756167810243 and parameters: {'weight_lgbm_class_0': 0.11323502429633282, 'weight_lgbm_class_1': 0.9832072851347581, 'weight_lgbm_class_2': 0.41407424060315257, 'weight_xgb_class_0': 0.07103523266081133, 'weight_xgb_class_1': 0.7225743088350911, 'weight_xgb_class_2': 0.5644719678831563}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:27,517] Trial 1758 finished with value: 0.9127831465679953 and parameters: {'weight_lgbm_class_0': 0.6768484442892655, 'weight_lgbm_class_1': 0.9815806326160401, 'weight_lgbm_class_2': 0.4937839587756634, 'weight_xgb_class_0': 0.06842916726005244, 'weight_xgb_class_1': 0.722330260267011, 'weight_xgb_class_2': 0.5607034426729339}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:27,521] Trial 1757 finished with value: 0.9476023237602623 and parameters: {'weight_lgbm_class_0': 0.08747157961515803, 'weight_lgbm_class_1': 0.08095264265274821, 'weight_lgbm_class_2': 0.40974038770777177, 'weight_xgb_class_0': 0.06777865664757948, 'weight_xgb_class_1': 0.725031992115063, 'weight_xgb_class_2': 0.5551416911028999}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:27,529] Trial 1759 finished with value: 0.9488501943797635 and parameters: {'weight_lgbm_class_0': 0.08553547118733672, 'weight_lgbm_class_1': 0.9770953256402986, 'weight_lgbm_class_2': 0.4123854308730807, 'weight_xgb_class_0': 0.07137581099908938, 'weight_xgb_class_1': 0.7258406662447984, 'weight_xgb_class_2': 0.5576959144065925}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:27,539] Trial 1760 finished with value: 0.930871353003511 and parameters: {'weight_lgbm_class_0': 0.43859046683789166, 'weight_lgbm_class_1': 0.9809142531547919, 'weight_lgbm_class_2': 0.410342381193611, 'weight_xgb_class_0': 0.030312993767136504, 'weight_xgb_class_1': 0.7252188266621425, 'weight_xgb_class_2': 0.5582974467263195}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋               | 1765/2000 [00:56<00:09, 25.57it/s]

[I 2026-07-05 15:32:27,559] Trial 1761 finished with value: 0.9485079658868837 and parameters: {'weight_lgbm_class_0': 0.11130919442943774, 'weight_lgbm_class_1': 0.9822511831944409, 'weight_lgbm_class_2': 0.48178760219767197, 'weight_xgb_class_0': 0.06705799371827517, 'weight_xgb_class_1': 0.7231988324904725, 'weight_xgb_class_2': 0.5618717189945083}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:27,616] Trial 1762 finished with value: 0.9494109808329836 and parameters: {'weight_lgbm_class_0': 0.11200323636280335, 'weight_lgbm_class_1': 0.9811357326327332, 'weight_lgbm_class_2': 0.4939912675460939, 'weight_xgb_class_0': 0.030385297957436906, 'weight_xgb_class_1': 0.7677770121660742, 'weight_xgb_class_2': 0.5995272359851299}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:27,748] Trial 1763 finished with value: 0.9489658785729732 and parameters: {'weight_lgbm_class_0': 0.09248240868096186, 'weight_lgbm_class_1': 0.9821107732314438, 'weight_lgbm_class_2': 0.4849364377651521, 'weight_xgb_class_0': 0.069398672603905, 'weight_xgb_class_1': 0.7311356427136902, 'weight_xgb_class_2': 0.6038296660968364}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:27,799] Trial 1764 finished with value: 0.9490930441593344 and parameters: {'weight_lgbm_class_0': 0.08428126871218168, 'weight_lgbm_class_1': 0.9794857321145882, 'weight_lgbm_class_2': 0.4099866686502035, 'weight_xgb_class_0': 0.06503160018493559, 'weight_xgb_class_1': 0.760718446831039, 'weight_xgb_class_2': 0.5973734564431024}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:27,818] Trial 1766 finished with value: 0.9489191335748591 and parameters: {'weight_lgbm_class_0': 0.09210369550441537, 'weight_lgbm_class_1': 0.999964760490417, 'weight_lgbm_class_2': 0.4097983748196718, 'weight_xgb_class_0': 0.06663075993355502, 'weight_xgb_class_1': 0.7658761251718594, 'weight_xgb_class_2': 0.5956364943329631}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉               | 1769/2000 [00:56<00:09, 23.58it/s]

[I 2026-07-05 15:32:27,850] Trial 1765 finished with value: 0.9488316480142447 and parameters: {'weight_lgbm_class_0': 0.08536937257644082, 'weight_lgbm_class_1': 0.980908113471027, 'weight_lgbm_class_2': 0.4068981854513486, 'weight_xgb_class_0': 0.07236752627443177, 'weight_xgb_class_1': 0.6579442437969057, 'weight_xgb_class_2': 0.5905673022129457}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:27,896] Trial 1767 finished with value: 0.911989652130918 and parameters: {'weight_lgbm_class_0': 0.6779405771550656, 'weight_lgbm_class_1': 0.9802255377251506, 'weight_lgbm_class_2': 0.45780794601326535, 'weight_xgb_class_0': 0.06826944327041091, 'weight_xgb_class_1': 0.6618146119536199, 'weight_xgb_class_2': 0.5957774553217835}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:27,924] Trial 1768 finished with value: 0.9498384605620228 and parameters: {'weight_lgbm_class_0': 0.08748997723958844, 'weight_lgbm_class_1': 0.9776479664313029, 'weight_lgbm_class_2': 0.45801014260741135, 'weight_xgb_class_0': 0.030751985464771658, 'weight_xgb_class_1': 0.763167487737106, 'weight_xgb_class_2': 0.595559181500604}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  89%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍              | 1776/2000 [00:56<00:09, 23.47it/s]

[I 2026-07-05 15:32:28,060] Trial 1769 finished with value: 0.9497383068469042 and parameters: {'weight_lgbm_class_0': 0.08827951956448829, 'weight_lgbm_class_1': 0.9618462840834718, 'weight_lgbm_class_2': 0.4573401030844139, 'weight_xgb_class_0': 0.031178049487880534, 'weight_xgb_class_1': 0.65751318401081, 'weight_xgb_class_2': 0.5949358683434567}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:28,076] Trial 1771 finished with value: 0.9495180532755324 and parameters: {'weight_lgbm_class_0': 0.0856850458193644, 'weight_lgbm_class_1': 0.9617068131790222, 'weight_lgbm_class_2': 0.4566929377545008, 'weight_xgb_class_0': 0.03004858255897021, 'weight_xgb_class_1': 0.7663321048056803, 'weight_xgb_class_2': 0.4512441082477802}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:28,104] Trial 1772 finished with value: 0.9497380548532443 and parameters: {'weight_lgbm_class_0': 0.08494972307690817, 'weight_lgbm_class_1': 0.965560965899121, 'weight_lgbm_class_2': 0.46155086130023076, 'weight_xgb_class_0': 0.030618030586611555, 'weight_xgb_class_1': 0.6620834447959614, 'weight_xgb_class_2': 0.5965302830895285}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:28,144] Trial 1770 finished with value: 0.9496934759455087 and parameters: {'weight_lgbm_class_0': 0.09299684874613849, 'weight_lgbm_class_1': 0.9599118559489764, 'weight_lgbm_class_2': 0.45948863803209705, 'weight_xgb_class_0': 0.03319616342850039, 'weight_xgb_class_1': 0.7662127697939659, 'weight_xgb_class_2': 0.5955499234645687}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:28,157] Trial 1773 finished with value: 0.9497432668260523 and parameters: {'weight_lgbm_class_0': 0.08545483084721683, 'weight_lgbm_class_1': 0.9598298057042027, 'weight_lgbm_class_2': 0.4559873509105937, 'weight_xgb_class_0': 0.02775052575590907, 'weight_xgb_class_1': 0.6714659283097479, 'weight_xgb_class_2': 0.5977855387389733}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:28,163] Trial 1774 finished with value: 0.9497459873225625 and parameters: {'weight_lgbm_class_0': 0.07937925778253102, 'weight_lgbm_class_1': 0.9600838350382684, 'weight_lgbm_class_2': 0.4594931958415419, 'weight_xgb_class_0': 0.031154066193706458, 'weight_xgb_class_1': 0.660369135930716, 'weight_xgb_class_2': 0.5956091581476054}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:28,253] Trial 1775 finished with value: 0.9497447199292366 and parameters: {'weight_lgbm_class_0': 0.08390053209770076, 'weight_lgbm_class_1': 0.9582401834680345, 'weight_lgbm_class_2': 0.45290161434853227, 'weight_xgb_class_0': 0.03227491470928775, 'weight_xgb_class_1': 0.7634161221800327, 'weight_xgb_class_2': 0.5310289568181268}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  89%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋              | 1780/2000 [00:57<00:09, 23.29it/s]

[I 2026-07-05 15:32:28,305] Trial 1776 finished with value: 0.9498453586315897 and parameters: {'weight_lgbm_class_0': 0.08184419467149608, 'weight_lgbm_class_1': 0.9581603489188664, 'weight_lgbm_class_2': 0.45796210059042786, 'weight_xgb_class_0': 0.03130752355779197, 'weight_xgb_class_1': 0.6990533397873967, 'weight_xgb_class_2': 0.5328713686229757}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:28,359] Trial 1777 finished with value: 0.9041258142582179 and parameters: {'weight_lgbm_class_0': 0.08004689673516935, 'weight_lgbm_class_1': 0.9577555991071129, 'weight_lgbm_class_2': 0.45191333840336423, 'weight_xgb_class_0': 0.698700415872113, 'weight_xgb_class_1': 0.6602371007076177, 'weight_xgb_class_2': 0.44210458524107393}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:28,360] Trial 1779 finished with value: 0.9497301913916366 and parameters: {'weight_lgbm_class_0': 0.05272152805651771, 'weight_lgbm_class_1': 0.9569501757904157, 'weight_lgbm_class_2': 0.4544207329790378, 'weight_xgb_class_0': 0.04104678086589277, 'weight_xgb_class_1': 0.7692538287490281, 'weight_xgb_class_2': 0.4483453619933757}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:28,382] Trial 1778 finished with value: 0.9482330631491299 and parameters: {'weight_lgbm_class_0': 0.07818566871638181, 'weight_lgbm_class_1': 0.9587039331615972, 'weight_lgbm_class_2': 0.45948068778615375, 'weight_xgb_class_0': 0.03387660276887991, 'weight_xgb_class_1': 0.7018354619000575, 'weight_xgb_class_2': 0.11585877422784108}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:28,413] Trial 1780 finished with value: 0.9497728358942057 and parameters: {'weight_lgbm_class_0': 0.08014731271672988, 'weight_lgbm_class_1': 0.9590629107496261, 'weight_lgbm_class_2': 0.4585922723456237, 'weight_xgb_class_0': 0.03547434177892567, 'weight_xgb_class_1': 0.7721860673044759, 'weight_xgb_class_2': 0.5319206231125092}. Best is trial 1561 with value: 0.9498642565074636.

[I 2026-07-05 15:32:28,539] Trial 1781 finished with value: 0.9497217203039775 and parameters: {'weight_lgbm_class_0': 0.05090791407941697, 'weight_lgbm_class_1': 0.9558545409493074, 'weight_lgbm_class_2': 0.45138572610659616, 'weight_xgb_class_0': 0.03687779323516911, 'weight_xgb_class_1': 0.7711061620413008, 'weight_xgb_class_2': 0.5329253399910938}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:28,586] Trial 1782 finished with value: 0.9496610831711839 and parameters: {'weight_lgbm_class_0': 0.047424514710648444, 'weight_lgbm_class_1': 0.9581146991702185, 'weight_lgbm_class_2': 0.4515273665457782, 'weight_xgb_class_0': 0.03710156485000933, 'weight_xgb_class_1': 0.7738557224873092, 'weight_xgb_class_2': 0.533563515837289}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:28,661] Trial 1783 finished with value: 0.9497410861249899 and parameters: {'weight_lgbm_class_0': 0.05031958741199657, 'weight_lgbm_class_1': 0.9995524766287317, 'weight_lgbm_class_2': 0.40371874422830284, 'weight_xgb_class_0': 0.04791205819962176, 'weight_xgb_class_1': 0.7739989288598763, 'weight_xgb_class_2': 0.5279775731607099}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:28,678] Trial 1784 finished with value: 0.9497730765309672 and parameters: {'weight_lgbm_class_0': 0.05102782659684711, 'weight_lgbm_class_1': 0.9544978348054334, 'weight_lgbm_class_2': 0.4117609561855447, 'weight_xgb_class_0': 0.04792512691716963, 'weight_xgb_class_1': 0.768667177005716, 'weight_xgb_class_2': 0.5303754301923916}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:28,701] Trial 1785 finished with value: 0.9498582993348204 and parameters: {'weight_lgbm_class_0': 0.05688026773278105, 'weight_lgbm_class_1': 0.9503400186143877, 'weight_lgbm_class_2': 0.4067384284099663, 'weight_xgb_class_0': 0.049547474154186144, 'weight_xgb_class_1': 0.7711374957353733, 'weight_xgb_class_2': 0.5381070282977364}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍             | 1791/2000 [00:57<00:08, 23.31it/s]

[I 2026-07-05 15:32:28,729] Trial 1786 finished with value: 0.9498202234785285 and parameters: {'weight_lgbm_class_0': 0.05258966576634818, 'weight_lgbm_class_1': 0.9997351528473066, 'weight_lgbm_class_2': 0.4033879748017221, 'weight_xgb_class_0': 0.051675275051206566, 'weight_xgb_class_1': 0.7669911414319159, 'weight_xgb_class_2': 0.5333781189963995}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:28,743] Trial 1787 finished with value: 0.9469967951398622 and parameters: {'weight_lgbm_class_0': 0.06932005870548655, 'weight_lgbm_class_1': 0.958507978681135, 'weight_lgbm_class_2': 0.38581599972667346, 'weight_xgb_class_0': 0.04776193404875228, 'weight_xgb_class_1': 0.7669251922458559, 'weight_xgb_class_2': 0.11526242729264535}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:28,822] Trial 1789 finished with value: 0.9495680175582684 and parameters: {'weight_lgbm_class_0': 0.06265910709745215, 'weight_lgbm_class_1': 0.9397914823039878, 'weight_lgbm_class_2': 0.40682261867779373, 'weight_xgb_class_0': 0.054696693646727024, 'weight_xgb_class_1': 0.775052415900266, 'weight_xgb_class_2': 0.5238313795222691}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:28,832] Trial 1788 finished with value: 0.9498042902363307 and parameters: {'weight_lgbm_class_0': 0.052181798861000744, 'weight_lgbm_class_1': 0.9433236764659889, 'weight_lgbm_class_2': 0.4120986675316728, 'weight_xgb_class_0': 0.04958470701300835, 'weight_xgb_class_1': 0.7750770909966166, 'weight_xgb_class_2': 0.5188514794301707}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:28,925] Trial 1790 finished with value: 0.9497747856011735 and parameters: {'weight_lgbm_class_0': 0.050485922691255986, 'weight_lgbm_class_1': 0.9367402019895307, 'weight_lgbm_class_2': 0.404250408357162, 'weight_xgb_class_0': 0.05632924120374425, 'weight_xgb_class_1': 0.7546061042898748, 'weight_xgb_class_2': 0.517167010237949}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:28,927] Trial 1791 finished with value: 0.9497159961533684 and parameters: {'weight_lgbm_class_0': 0.05883564535258731, 'weight_lgbm_class_1': 0.9402881833503357, 'weight_lgbm_class_2': 0.9287797754598871, 'weight_xgb_class_0': 0.05655988814887253, 'weight_xgb_class_1': 0.7565382727692452, 'weight_xgb_class_2': 0.5154162107470517}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋             | 1795/2000 [00:57<00:08, 23.33it/s]

[I 2026-07-05 15:32:28,943] Trial 1792 finished with value: 0.9494511079944696 and parameters: {'weight_lgbm_class_0': 0.05577018124664309, 'weight_lgbm_class_1': 0.941228294559146, 'weight_lgbm_class_2': 0.40499856082936375, 'weight_xgb_class_0': 0.06395358496673363, 'weight_xgb_class_1': 0.7553133432853875, 'weight_xgb_class_2': 0.5174229934637838}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:29,046] Trial 1794 finished with value: 0.9494958810650574 and parameters: {'weight_lgbm_class_0': 0.05771670263174249, 'weight_lgbm_class_1': 0.9439420922553269, 'weight_lgbm_class_2': 0.4044549533720525, 'weight_xgb_class_0': 0.059491943105035, 'weight_xgb_class_1': 0.7507215491532464, 'weight_xgb_class_2': 0.5124773008405015}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:29,062] Trial 1793 finished with value: 0.9333085619884468 and parameters: {'weight_lgbm_class_0': 0.35900984503765176, 'weight_lgbm_class_1': 0.9381688462761129, 'weight_lgbm_class_2': 0.40448293002259245, 'weight_xgb_class_0': 0.057275197131580136, 'weight_xgb_class_1': 0.7624280623200559, 'weight_xgb_class_2': 0.5073524574463256}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:29,156] Trial 1795 finished with value: 0.9490597838055423 and parameters: {'weight_lgbm_class_0': 0.06596517374313857, 'weight_lgbm_class_1': 0.9355410576710989, 'weight_lgbm_class_2': 0.4204940427326398, 'weight_xgb_class_0': 0.07325018950876352, 'weight_xgb_class_1': 0.7491812197805088, 'weight_xgb_class_2': 0.5115417274039775}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  90%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████             | 1801/2000 [00:57<00:07, 25.15it/s]

[I 2026-07-05 15:32:29,228] Trial 1797 finished with value: 0.9495654705257214 and parameters: {'weight_lgbm_class_0': 0.04832236671689433, 'weight_lgbm_class_1': 0.9311682716860896, 'weight_lgbm_class_2': 0.42269911280989503, 'weight_xgb_class_0': 0.06945440158750192, 'weight_xgb_class_1': 0.7441331052071289, 'weight_xgb_class_2': 0.512594147153293}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:29,234] Trial 1796 finished with value: 0.9329453709504069 and parameters: {'weight_lgbm_class_0': 0.35571831967565437, 'weight_lgbm_class_1': 0.9360569154457706, 'weight_lgbm_class_2': 0.42798274845303513, 'weight_xgb_class_0': 0.07294217945969533, 'weight_xgb_class_1': 0.7470637237082414, 'weight_xgb_class_2': 0.507266105555602}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:29,237] Trial 1798 finished with value: 0.9495563433024481 and parameters: {'weight_lgbm_class_0': 0.04969066847551726, 'weight_lgbm_class_1': 0.937135312269217, 'weight_lgbm_class_2': 0.42329235407400745, 'weight_xgb_class_0': 0.06757880295059021, 'weight_xgb_class_1': 0.7506656983380345, 'weight_xgb_class_2': 0.510277449986911}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:29,305] Trial 1800 finished with value: 0.9490623325368932 and parameters: {'weight_lgbm_class_0': 0.07044791352374, 'weight_lgbm_class_1': 0.9381852640872093, 'weight_lgbm_class_2': 0.42891753874659266, 'weight_xgb_class_0': 0.06838962546332848, 'weight_xgb_class_1': 0.7396787037874104, 'weight_xgb_class_2': 0.5031680131937828}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:29,319] Trial 1799 finished with value: 0.9487828857820966 and parameters: {'weight_lgbm_class_0': 0.06859831937030106, 'weight_lgbm_class_1': 0.9364320874514537, 'weight_lgbm_class_2': 0.4224951865363749, 'weight_xgb_class_0': 0.0655852821406141, 'weight_xgb_class_1': 0.14359838030663363, 'weight_xgb_class_2': 0.5065188671141386}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:29,344] Trial 1801 finished with value: 0.9495158577943661 and parameters: {'weight_lgbm_class_0': 0.04839916344577849, 'weight_lgbm_class_1': 0.9397093617909937, 'weight_lgbm_class_2': 0.42949302889818086, 'weight_xgb_class_0': 0.07121789176864135, 'weight_xgb_class_1': 0.7477049332398372, 'weight_xgb_class_2': 0.5076791985307656}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  90%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍            | 1807/2000 [00:58<00:08, 22.12it/s]

[I 2026-07-05 15:32:29,462] Trial 1803 finished with value: 0.9489518384327819 and parameters: {'weight_lgbm_class_0': 0.06995645143825856, 'weight_lgbm_class_1': 0.9376590575698093, 'weight_lgbm_class_2': 0.4269754282136379, 'weight_xgb_class_0': 0.07548673595650433, 'weight_xgb_class_1': 0.7428254590065558, 'weight_xgb_class_2': 0.49818204603930355}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:29,467] Trial 1802 finished with value: 0.9483031695610594 and parameters: {'weight_lgbm_class_0': 0.07414698700488859, 'weight_lgbm_class_1': 0.9322650214762271, 'weight_lgbm_class_2': 0.4308803590952884, 'weight_xgb_class_0': 0.07609254442362387, 'weight_xgb_class_1': 0.13644467174272645, 'weight_xgb_class_2': 0.4884327010948924}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:29,529] Trial 1804 finished with value: 0.9488602366018632 and parameters: {'weight_lgbm_class_0': 0.07354660450085776, 'weight_lgbm_class_1': 0.9348773331904641, 'weight_lgbm_class_2': 0.42458809172468404, 'weight_xgb_class_0': 0.0742836558542541, 'weight_xgb_class_1': 0.7470374520962692, 'weight_xgb_class_2': 0.4917084072216722}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:29,611] Trial 1806 finished with value: 0.9487413980917568 and parameters: {'weight_lgbm_class_0': 0.07250829386374581, 'weight_lgbm_class_1': 0.9769163328245007, 'weight_lgbm_class_2': 0.42955421413348077, 'weight_xgb_class_0': 0.0782869098588112, 'weight_xgb_class_1': 0.7021333588050495, 'weight_xgb_class_2': 0.48414283692441756}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:29,621] Trial 1805 finished with value: 0.9489141820202454 and parameters: {'weight_lgbm_class_0': 0.07071084596268379, 'weight_lgbm_class_1': 0.9805199172717108, 'weight_lgbm_class_2': 0.4247463816743207, 'weight_xgb_class_0': 0.07498893555902669, 'weight_xgb_class_1': 0.7394075401479655, 'weight_xgb_class_2': 0.4907387473752742}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:29,659] Trial 1807 finished with value: 0.948293154192677 and parameters: {'weight_lgbm_class_0': 0.10133161894475043, 'weight_lgbm_class_1': 0.977785799597712, 'weight_lgbm_class_2': 0.4276154978558372, 'weight_xgb_class_0': 0.07012938951199929, 'weight_xgb_class_1': 0.7357535717890582, 'weight_xgb_class_2': 0.48686375385378483}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊            | 1813/2000 [00:58<00:07, 23.39it/s]

[I 2026-07-05 15:32:29,749] Trial 1808 finished with value: 0.9498407654568838 and parameters: {'weight_lgbm_class_0': 0.07607833872391064, 'weight_lgbm_class_1': 0.9765517064295586, 'weight_lgbm_class_2': 0.3837026733817523, 'weight_xgb_class_0': 0.021128626641778236, 'weight_xgb_class_1': 0.7048758682598958, 'weight_xgb_class_2': 0.4826562954604898}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:29,791] Trial 1809 finished with value: 0.9497801301874619 and parameters: {'weight_lgbm_class_0': 0.07334835026156761, 'weight_lgbm_class_1': 0.9781804664454179, 'weight_lgbm_class_2': 0.4260665850745626, 'weight_xgb_class_0': 0.02079551661821245, 'weight_xgb_class_1': 0.7005012351748365, 'weight_xgb_class_2': 0.5429381247580928}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:29,804] Trial 1810 finished with value: 0.9497754307293046 and parameters: {'weight_lgbm_class_0': 0.07546681658735027, 'weight_lgbm_class_1': 0.9782818865219144, 'weight_lgbm_class_2': 0.3853101130377111, 'weight_xgb_class_0': 0.020419894521782042, 'weight_xgb_class_1': 0.7049186214437838, 'weight_xgb_class_2': 0.540508431319839}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:29,804] Trial 1811 finished with value: 0.9493557898639594 and parameters: {'weight_lgbm_class_0': 0.09612498160565996, 'weight_lgbm_class_1': 0.9771096829232205, 'weight_lgbm_class_2': 0.38782252141153656, 'weight_xgb_class_0': 0.020050446309842547, 'weight_xgb_class_1': 0.7043324590560598, 'weight_xgb_class_2': 0.4845609398261332}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:29,841] Trial 1813 finished with value: 0.9493256398540519 and parameters: {'weight_lgbm_class_0': 0.10296477180381347, 'weight_lgbm_class_1': 0.9805234624094088, 'weight_lgbm_class_2': 0.38438857162090084, 'weight_xgb_class_0': 0.0211100034837205, 'weight_xgb_class_1': 0.7021031640424055, 'weight_xgb_class_2': 0.5401038641160462}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:29,847] Trial 1812 finished with value: 0.9492562206653369 and parameters: {'weight_lgbm_class_0': 0.09751248134511645, 'weight_lgbm_class_1': 0.9776968894065726, 'weight_lgbm_class_2': 0.38619468505042986, 'weight_xgb_class_0': 0.022808291830805703, 'weight_xgb_class_1': 0.7039305454148305, 'weight_xgb_class_2': 0.4845831961983301}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏           | 1818/2000 [00:58<00:07, 23.48it/s]

[I 2026-07-05 15:32:29,995] Trial 1814 finished with value: 0.9492942347459183 and parameters: {'weight_lgbm_class_0': 0.0989241972427853, 'weight_lgbm_class_1': 0.9784561219087279, 'weight_lgbm_class_2': 0.38732638265006086, 'weight_xgb_class_0': 0.029216377067339767, 'weight_xgb_class_1': 0.7133657041984341, 'weight_xgb_class_2': 0.5427746070671119}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:30,008] Trial 1815 finished with value: 0.9494153822270448 and parameters: {'weight_lgbm_class_0': 0.10144702917666633, 'weight_lgbm_class_1': 0.9774850092646447, 'weight_lgbm_class_2': 0.38859583926523666, 'weight_xgb_class_0': 0.020541065162779357, 'weight_xgb_class_1': 0.7039207039544696, 'weight_xgb_class_2': 0.5412027135059415}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:30,055] Trial 1816 finished with value: 0.9495595483132352 and parameters: {'weight_lgbm_class_0': 0.1002309598933582, 'weight_lgbm_class_1': 0.9796206604958503, 'weight_lgbm_class_2': 0.3909553344533869, 'weight_xgb_class_0': 0.020929154166113743, 'weight_xgb_class_1': 0.7047897157394526, 'weight_xgb_class_2': 0.5734436960949937}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:30,118] Trial 1817 finished with value: 0.9494245832537639 and parameters: {'weight_lgbm_class_0': 0.10140716730366339, 'weight_lgbm_class_1': 0.9709629360250936, 'weight_lgbm_class_2': 0.3842529450895883, 'weight_xgb_class_0': 0.020375919489728174, 'weight_xgb_class_1': 0.7075537432056719, 'weight_xgb_class_2': 0.5414693879038285}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:30,187] Trial 1818 finished with value: 0.9175955184979134 and parameters: {'weight_lgbm_class_0': 0.09664332510953325, 'weight_lgbm_class_1': 0.999946748184732, 'weight_lgbm_class_2': 0.3853485585593779, 'weight_xgb_class_0': 0.5302620501782465, 'weight_xgb_class_1': 0.7093328288584815, 'weight_xgb_class_2': 0.5418483378528568}. Best is trial 1561 with value: 0.9498642565074636.

[I 2026-07-05 15:32:30,189] Trial 1819 finished with value: 0.9494316547872942 and parameters: {'weight_lgbm_class_0': 0.09893924950265462, 'weight_lgbm_class_1': 0.9998054452239882, 'weight_lgbm_class_2': 0.3874863140261523, 'weight_xgb_class_0': 0.02306991313031408, 'weight_xgb_class_1': 0.712038651686551, 'weight_xgb_class_2': 0.5424968469920853}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:30,283] Trial 1820 finished with value: 0.949074102377072 and parameters: {'weight_lgbm_class_0': 0.09738336708224171, 'weight_lgbm_class_1': 0.9659516598274785, 'weight_lgbm_class_2': 0.3870943793919633, 'weight_xgb_class_0': 0.021107540692577066, 'weight_xgb_class_1': 0.7076439848065403, 'weight_xgb_class_2': 0.40881176471936576}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:30,303] Trial 1821 finished with value: 0.9488144557004587 and parameters: {'weight_lgbm_class_0': 0.10289270496352464, 'weight_lgbm_class_1': 0.9628046283895353, 'weight_lgbm_class_2': 0.38501809857971053, 'weight_xgb_class_0': 0.03511108607676535, 'weight_xgb_class_1': 0.6730942080904606, 'weight_xgb_class_2': 0.45939183999713945}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:30,349] Trial 1822 finished with value: 0.9497771254561914 and parameters: {'weight_lgbm_class_0': 0.04524406471514394, 'weight_lgbm_class_1': 0.9587479330535024, 'weight_lgbm_class_2': 0.3856381446486764, 'weight_xgb_class_0': 0.04193091985864994, 'weight_xgb_class_1': 0.6699429637197486, 'weight_xgb_class_2': 0.4319841877864926}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉           | 1829/2000 [00:59<00:07, 24.29it/s]

[I 2026-07-05 15:32:30,417] Trial 1823 finished with value: 0.9484532713237636 and parameters: {'weight_lgbm_class_0': 0.10687981767696657, 'weight_lgbm_class_1': 0.6394059393143597, 'weight_lgbm_class_2': 0.39464219567244607, 'weight_xgb_class_0': 0.043979587640272516, 'weight_xgb_class_1': 0.6822696268996906, 'weight_xgb_class_2': 0.46659938494251146}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:30,466] Trial 1825 finished with value: 0.9424250743275643 and parameters: {'weight_lgbm_class_0': 0.10275210341156807, 'weight_lgbm_class_1': 0.9999503293837746, 'weight_lgbm_class_2': 0.38404909895092726, 'weight_xgb_class_0': 0.03992495611245943, 'weight_xgb_class_1': 0.6768942964796804, 'weight_xgb_class_2': 0.029852306500756987}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:30,473] Trial 1824 finished with value: 0.9486740995605095 and parameters: {'weight_lgbm_class_0': 0.10559956921593408, 'weight_lgbm_class_1': 0.9600488557144612, 'weight_lgbm_class_2': 0.3861861366401691, 'weight_xgb_class_0': 0.03972413981784029, 'weight_xgb_class_1': 0.6705603830902784, 'weight_xgb_class_2': 0.47938123762415297}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:30,507] Trial 1826 finished with value: 0.9497797453747281 and parameters: {'weight_lgbm_class_0': 0.04390845845071403, 'weight_lgbm_class_1': 0.9098933231875967, 'weight_lgbm_class_2': 0.3926408664578291, 'weight_xgb_class_0': 0.04528792904759363, 'weight_xgb_class_1': 0.669857534210537, 'weight_xgb_class_2': 0.4444234969216424}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:30,532] Trial 1827 finished with value: 0.948297746380442 and parameters: {'weight_lgbm_class_0': 0.11124166442372149, 'weight_lgbm_class_1': 0.9093763539054247, 'weight_lgbm_class_2': 0.3854553223243342, 'weight_xgb_class_0': 0.043685736584145055, 'weight_xgb_class_1': 0.6705972860769001, 'weight_xgb_class_2': 0.4488517491370726}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:30,573] Trial 1828 finished with value: 0.9497399011526714 and parameters: {'weight_lgbm_class_0': 0.04746104879537361, 'weight_lgbm_class_1': 0.9130199150711285, 'weight_lgbm_class_2': 0.38221105584953813, 'weight_xgb_class_0': 0.04142716279367584, 'weight_xgb_class_1': 0.6708129461289337, 'weight_xgb_class_2': 0.5786450535677015}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏          | 1833/2000 [00:59<00:07, 21.52it/s]

[I 2026-07-05 15:32:30,632] Trial 1829 finished with value: 0.9496685090779481 and parameters: {'weight_lgbm_class_0': 0.04228755694764348, 'weight_lgbm_class_1': 0.9072210910636112, 'weight_lgbm_class_2': 0.38664820775986025, 'weight_xgb_class_0': 0.034323229861509694, 'weight_xgb_class_1': 0.6722802440496286, 'weight_xgb_class_2': 0.48253908204141965}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:30,735] Trial 1831 finished with value: 0.9233507832255116 and parameters: {'weight_lgbm_class_0': 0.4671474642004649, 'weight_lgbm_class_1': 0.9585501982836466, 'weight_lgbm_class_2': 0.3991811964128874, 'weight_xgb_class_0': 0.04549658799343738, 'weight_xgb_class_1': 0.6705148491638995, 'weight_xgb_class_2': 0.4578036535038149}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:30,737] Trial 1830 finished with value: 0.9496989659876731 and parameters: {'weight_lgbm_class_0': 0.047186565049056606, 'weight_lgbm_class_1': 0.9080937811042312, 'weight_lgbm_class_2': 0.40299673104973, 'weight_xgb_class_0': 0.03372282391343411, 'weight_xgb_class_1': 0.6702338545187263, 'weight_xgb_class_2': 0.5780826843517745}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:30,783] Trial 1832 finished with value: 0.9497738022577598 and parameters: {'weight_lgbm_class_0': 0.04370412541228967, 'weight_lgbm_class_1': 0.9108564153722429, 'weight_lgbm_class_2': 0.4031920743376829, 'weight_xgb_class_0': 0.04627818482587124, 'weight_xgb_class_1': 0.670902035047375, 'weight_xgb_class_2': 0.5698808039168796}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:30,834] Trial 1834 finished with value: 0.9497317477175139 and parameters: {'weight_lgbm_class_0': 0.043188623305369385, 'weight_lgbm_class_1': 0.9547737998480565, 'weight_lgbm_class_2': 0.4036285649772794, 'weight_xgb_class_0': 0.04374127973391778, 'weight_xgb_class_1': 0.6693504597375574, 'weight_xgb_class_2': 0.4573379195857372}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍          | 1838/2000 [00:59<00:06, 23.72it/s]

[I 2026-07-05 15:32:30,838] Trial 1833 finished with value: 0.9497857375895796 and parameters: {'weight_lgbm_class_0': 0.051082656166732514, 'weight_lgbm_class_1': 0.9136610069621093, 'weight_lgbm_class_2': 0.4083269762792584, 'weight_xgb_class_0': 0.04948625030801486, 'weight_xgb_class_1': 0.6747050582972227, 'weight_xgb_class_2': 0.45751884618819466}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:30,893] Trial 1835 finished with value: 0.9498287065528976 and parameters: {'weight_lgbm_class_0': 0.04661174547790747, 'weight_lgbm_class_1': 0.9563679028233436, 'weight_lgbm_class_2': 0.39988299764351254, 'weight_xgb_class_0': 0.04691662830448235, 'weight_xgb_class_1': 0.6660910293770721, 'weight_xgb_class_2': 0.44483802411440543}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:30,986] Trial 1836 finished with value: 0.9497015353638553 and parameters: {'weight_lgbm_class_0': 0.07072888127030816, 'weight_lgbm_class_1': 0.9176229146741524, 'weight_lgbm_class_2': 0.40480887962229495, 'weight_xgb_class_0': 0.04574160249105674, 'weight_xgb_class_1': 0.680706403904344, 'weight_xgb_class_2': 0.5719694853536118}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:31,020] Trial 1837 finished with value: 0.9497839323182348 and parameters: {'weight_lgbm_class_0': 0.04304733110543421, 'weight_lgbm_class_1': 0.9531446779524522, 'weight_lgbm_class_2': 0.4068301057991963, 'weight_xgb_class_0': 0.05107259758165065, 'weight_xgb_class_1': 0.6778626787945704, 'weight_xgb_class_2': 0.5816078693751342}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:31,067] Trial 1838 finished with value: 0.9497944075460616 and parameters: {'weight_lgbm_class_0': 0.044062662861957154, 'weight_lgbm_class_1': 0.9136903848315638, 'weight_lgbm_class_2': 0.40899784240759834, 'weight_xgb_class_0': 0.04828721771906477, 'weight_xgb_class_1': 0.6511944935291029, 'weight_xgb_class_2': 0.46644629388287473}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋          | 1842/2000 [00:59<00:07, 22.42it/s]

[I 2026-07-05 15:32:31,098] Trial 1840 finished with value: 0.9498322144901398 and parameters: {'weight_lgbm_class_0': 0.07752620482074637, 'weight_lgbm_class_1': 0.9549653812050403, 'weight_lgbm_class_2': 0.40987067659511234, 'weight_xgb_class_0': 0.01790081875992741, 'weight_xgb_class_1': 0.6922632966110245, 'weight_xgb_class_2': 0.4622647533466669}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:31,109] Trial 1839 finished with value: 0.9497388177988593 and parameters: {'weight_lgbm_class_0': 0.07764381489585577, 'weight_lgbm_class_1': 0.9551665072513145, 'weight_lgbm_class_2': 0.4080109370302671, 'weight_xgb_class_0': 0.019387998242744533, 'weight_xgb_class_1': 0.68898532404711, 'weight_xgb_class_2': 0.41074222768680624}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:31,194] Trial 1841 finished with value: 0.8992494471125649 and parameters: {'weight_lgbm_class_0': 0.0763248500457181, 'weight_lgbm_class_1': 0.954112856708285, 'weight_lgbm_class_2': 0.023464302224710964, 'weight_xgb_class_0': 0.49506574660452074, 'weight_xgb_class_1': 0.7001496730461089, 'weight_xgb_class_2': 0.454117807070758}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:31,274] Trial 1843 finished with value: 0.9171231880165612 and parameters: {'weight_lgbm_class_0': 0.07795303437812758, 'weight_lgbm_class_1': 0.9524474129339814, 'weight_lgbm_class_2': 0.41042608798697033, 'weight_xgb_class_0': 0.4987277911442586, 'weight_xgb_class_1': 0.6427218886981433, 'weight_xgb_class_2': 0.4256953480702611}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████          | 1848/2000 [01:00<00:06, 22.68it/s]

[I 2026-07-05 15:32:31,317] Trial 1844 finished with value: 0.9497855278575621 and parameters: {'weight_lgbm_class_0': 0.07254188046832949, 'weight_lgbm_class_1': 0.9541050402850303, 'weight_lgbm_class_2': 0.41198416566119406, 'weight_xgb_class_0': 0.02080587505152454, 'weight_xgb_class_1': 0.6910192946167211, 'weight_xgb_class_2': 0.5733897714523999}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:31,322] Trial 1842 finished with value: 0.9498035677633236 and parameters: {'weight_lgbm_class_0': 0.07321929868614047, 'weight_lgbm_class_1': 0.9597379192670507, 'weight_lgbm_class_2': 0.4088337974361452, 'weight_xgb_class_0': 0.018576946704654953, 'weight_xgb_class_1': 0.6466976076290429, 'weight_xgb_class_2': 0.46053694615911056}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:31,385] Trial 1845 finished with value: 0.9497502377738952 and parameters: {'weight_lgbm_class_0': 0.07516489118378629, 'weight_lgbm_class_1': 0.9999814669097121, 'weight_lgbm_class_2': 0.4125095884688124, 'weight_xgb_class_0': 0.01775538333268005, 'weight_xgb_class_1': 0.6484094671595234, 'weight_xgb_class_2': 0.5739225634945091}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:31,414] Trial 1846 finished with value: 0.949821143841131 and parameters: {'weight_lgbm_class_0': 0.08094476351425323, 'weight_lgbm_class_1': 0.9543929507707326, 'weight_lgbm_class_2': 0.41100489487722175, 'weight_xgb_class_0': 0.017988621772327212, 'weight_xgb_class_1': 0.6925979137538658, 'weight_xgb_class_2': 0.5753487971273427}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:31,426] Trial 1847 finished with value: 0.9498394524535131 and parameters: {'weight_lgbm_class_0': 0.07944485605298686, 'weight_lgbm_class_1': 0.9523630595372307, 'weight_lgbm_class_2': 0.41459576299334716, 'weight_xgb_class_0': 0.019802618474918595, 'weight_xgb_class_1': 0.6451494137677213, 'weight_xgb_class_2': 0.5243005770239131}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:31,485] Trial 1848 finished with value: 0.9497312985620147 and parameters: {'weight_lgbm_class_0': 0.08255717437748888, 'weight_lgbm_class_1': 0.9997209531887862, 'weight_lgbm_class_2': 0.8583000225411787, 'weight_xgb_class_0': 0.01767654945915279, 'weight_xgb_class_1': 0.6433456974345335, 'weight_xgb_class_2': 0.5226283484955356}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  93%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌         | 1854/2000 [01:00<00:06, 23.16it/s]

[I 2026-07-05 15:32:31,545] Trial 1849 finished with value: 0.9498196205092427 and parameters: {'weight_lgbm_class_0': 0.07818225968616342, 'weight_lgbm_class_1': 0.9620964345832334, 'weight_lgbm_class_2': 0.44184598454805163, 'weight_xgb_class_0': 0.020911728074072652, 'weight_xgb_class_1': 0.6997307667340624, 'weight_xgb_class_2': 0.520013633396558}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:31,618] Trial 1850 finished with value: 0.9496700673984532 and parameters: {'weight_lgbm_class_0': 0.07769334881908281, 'weight_lgbm_class_1': 0.9800539044528402, 'weight_lgbm_class_2': 0.9615181415590679, 'weight_xgb_class_0': 0.019502798169218172, 'weight_xgb_class_1': 0.6380147932705658, 'weight_xgb_class_2': 0.522126617897481}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:31,629] Trial 1851 finished with value: 0.9498157537809061 and parameters: {'weight_lgbm_class_0': 0.0789619173240056, 'weight_lgbm_class_1': 0.9791080110383883, 'weight_lgbm_class_2': 0.44195929210085827, 'weight_xgb_class_0': 0.01747262992460861, 'weight_xgb_class_1': 0.6404430777882097, 'weight_xgb_class_2': 0.5246897242014545}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:31,670] Trial 1852 finished with value: 0.9498214981115684 and parameters: {'weight_lgbm_class_0': 0.07532890578477064, 'weight_lgbm_class_1': 0.999305359383414, 'weight_lgbm_class_2': 0.438757732920739, 'weight_xgb_class_0': 0.022014175798861682, 'weight_xgb_class_1': 0.643137166307207, 'weight_xgb_class_2': 0.5229288529042354}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:31,714] Trial 1853 finished with value: 0.9484481819154352 and parameters: {'weight_lgbm_class_0': 0.15429853410218886, 'weight_lgbm_class_1': 0.9782737520545106, 'weight_lgbm_class_2': 0.44342587816793005, 'weight_xgb_class_0': 0.018038051174867332, 'weight_xgb_class_1': 0.7270501547877222, 'weight_xgb_class_2': 0.5216948271199633}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  93%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊         | 1858/2000 [01:00<00:06, 21.42it/s]

[I 2026-07-05 15:32:31,767] Trial 1854 finished with value: 0.9495183006408862 and parameters: {'weight_lgbm_class_0': 0.11471488510352573, 'weight_lgbm_class_1': 0.9816825587613656, 'weight_lgbm_class_2': 0.44369606916954285, 'weight_xgb_class_0': 7.945909631299961e-05, 'weight_xgb_class_1': 0.2609197294625982, 'weight_xgb_class_2': 0.5235345647308914}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:31,859] Trial 1856 finished with value: 0.9484587613862078 and parameters: {'weight_lgbm_class_0': 0.15329922962128126, 'weight_lgbm_class_1': 0.9807527879365477, 'weight_lgbm_class_2': 0.4399532074023643, 'weight_xgb_class_0': 0.01728174241276412, 'weight_xgb_class_1': 0.7209156672055222, 'weight_xgb_class_2': 0.5237602420745179}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:31,892] Trial 1855 finished with value: 0.9487427064716738 and parameters: {'weight_lgbm_class_0': 0.12122142613012948, 'weight_lgbm_class_1': 0.9817672453900416, 'weight_lgbm_class_2': 0.4421862985415045, 'weight_xgb_class_0': 0.017722971658219556, 'weight_xgb_class_1': 0.7305111981665021, 'weight_xgb_class_2': 0.3927244728751348}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:31,942] Trial 1857 finished with value: 0.9495536729240738 and parameters: {'weight_lgbm_class_0': 0.05911447568896971, 'weight_lgbm_class_1': 0.9231971740562761, 'weight_lgbm_class_2': 0.4384167015550364, 'weight_xgb_class_0': 0.0565698429036456, 'weight_xgb_class_1': 0.6390301813076387, 'weight_xgb_class_2': 0.4903697927941319}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:31,979] Trial 1858 finished with value: 0.9493862581923539 and parameters: {'weight_lgbm_class_0': 0.0638139055725368, 'weight_lgbm_class_1': 0.9284673598194715, 'weight_lgbm_class_2': 0.4411062975223746, 'weight_xgb_class_0': 0.061978697861246754, 'weight_xgb_class_1': 0.6199718259249761, 'weight_xgb_class_2': 0.5213073164520965}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏        | 1864/2000 [01:00<00:06, 20.98it/s]

[I 2026-07-05 15:32:32,034] Trial 1860 finished with value: 0.9493810053072922 and parameters: {'weight_lgbm_class_0': 0.060488840630834, 'weight_lgbm_class_1': 0.9237898809162528, 'weight_lgbm_class_2': 0.43579378202919195, 'weight_xgb_class_0': 0.06152648949308741, 'weight_xgb_class_1': 0.609579699875121, 'weight_xgb_class_2': 0.49895228325492225}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:32,035] Trial 1859 finished with value: 0.9491569751205176 and parameters: {'weight_lgbm_class_0': 0.0649348002829034, 'weight_lgbm_class_1': 0.9262408276275614, 'weight_lgbm_class_2': 0.43928446866835374, 'weight_xgb_class_0': 0.0668739647792914, 'weight_xgb_class_1': 0.6305631031344721, 'weight_xgb_class_2': 0.48921434472235004}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:32,108] Trial 1861 finished with value: 0.8933070187739133 and parameters: {'weight_lgbm_class_0': 0.055546731404610875, 'weight_lgbm_class_1': 0.9238933808978638, 'weight_lgbm_class_2': 0.4374260396019537, 'weight_xgb_class_0': 0.8890411365727879, 'weight_xgb_class_1': 0.6200210063033494, 'weight_xgb_class_2': 0.4972967238824708}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:32,172] Trial 1863 finished with value: 0.9493940442806265 and parameters: {'weight_lgbm_class_0': 0.05672426714475769, 'weight_lgbm_class_1': 0.9246791881566122, 'weight_lgbm_class_2': 0.4224300831474614, 'weight_xgb_class_0': 0.06311582354033951, 'weight_xgb_class_1': 0.6205481869606699, 'weight_xgb_class_2': 0.4870698394712813}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:32,173] Trial 1862 finished with value: 0.9495014828852395 and parameters: {'weight_lgbm_class_0': 0.05828227984002853, 'weight_lgbm_class_1': 0.925440128623359, 'weight_lgbm_class_2': 0.4219149298561351, 'weight_xgb_class_0': 0.05967425478643803, 'weight_xgb_class_1': 0.615683032191133, 'weight_xgb_class_2': 0.49899457378371087}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:32,204] Trial 1864 finished with value: 0.9489900627106249 and parameters: {'weight_lgbm_class_0': 0.05976423464766573, 'weight_lgbm_class_1': 0.9244108018779433, 'weight_lgbm_class_2': 0.3801397889039971, 'weight_xgb_class_0': 0.06155305581999945, 'weight_xgb_class_1': 0.6294737156119685, 'weight_xgb_class_2': 0.3902882033826146}. Best is trial 1561 with value: 0.9498642565074636.

[I 2026-07-05 15:32:32,291] Trial 1865 finished with value: 0.949261498490014 and parameters: {'weight_lgbm_class_0': 0.06381093860653309, 'weight_lgbm_class_1': 0.9282973039077672, 'weight_lgbm_class_2': 0.4210975340862245, 'weight_xgb_class_0': 0.05931939238833724, 'weight_xgb_class_1': 0.6082537397247064, 'weight_xgb_class_2': 0.48383437244833255}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:32,343] Trial 1866 finished with value: 0.9495730594647206 and parameters: {'weight_lgbm_class_0': 0.0544466221010057, 'weight_lgbm_class_1': 0.9260003894835019, 'weight_lgbm_class_2': 0.3792805707714799, 'weight_xgb_class_0': 0.05642227536321476, 'weight_xgb_class_1': 0.6411143378830609, 'weight_xgb_class_2': 0.49985467070430745}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:32,405] Trial 1868 finished with value: 0.9495331805908966 and parameters: {'weight_lgbm_class_0': 0.052965649150764245, 'weight_lgbm_class_1': 0.9285078021908191, 'weight_lgbm_class_2': 0.4224743384975076, 'weight_xgb_class_0': 0.06267449394616216, 'weight_xgb_class_1': 0.6147807963711003, 'weight_xgb_class_2': 0.49466956757186187}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:32,416] Trial 1867 finished with value: 0.9496148331678139 and parameters: {'weight_lgbm_class_0': 0.05797769110836161, 'weight_lgbm_class_1': 0.9304304172818821, 'weight_lgbm_class_2': 0.42102168899846604, 'weight_xgb_class_0': 0.054551125574994, 'weight_xgb_class_1': 0.6300528972063307, 'weight_xgb_class_2': 0.49538239814956286}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  94%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋        | 1873/2000 [01:01<00:06, 20.01it/s]

[I 2026-07-05 15:32:32,491] Trial 1869 finished with value: 0.9491827714771451 and parameters: {'weight_lgbm_class_0': 0.060256799881316526, 'weight_lgbm_class_1': 0.9368087509923085, 'weight_lgbm_class_2': 0.42599460226755104, 'weight_xgb_class_0': 0.06817530961533165, 'weight_xgb_class_1': 0.6230400468601395, 'weight_xgb_class_2': 0.4951149871875597}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:32,534] Trial 1870 finished with value: 0.9493990376649499 and parameters: {'weight_lgbm_class_0': 0.058309849033138926, 'weight_lgbm_class_1': 0.9295808429520315, 'weight_lgbm_class_2': 0.3824809082772559, 'weight_xgb_class_0': 0.05910033432776912, 'weight_xgb_class_1': 0.5759200147753362, 'weight_xgb_class_2': 0.4993455510626656}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:32,642] Trial 1872 finished with value: 0.9491259814350776 and parameters: {'weight_lgbm_class_0': 0.09067811473029741, 'weight_lgbm_class_1': 0.9341215128721069, 'weight_lgbm_class_2': 0.3767133452075347, 'weight_xgb_class_0': 0.03557942618306578, 'weight_xgb_class_1': 0.6028892406846321, 'weight_xgb_class_2': 0.5017095382476682}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:32,642] Trial 1871 finished with value: 0.9492192151969198 and parameters: {'weight_lgbm_class_0': 0.09303892957906996, 'weight_lgbm_class_1': 0.9357177739844225, 'weight_lgbm_class_2': 0.3787139117130939, 'weight_xgb_class_0': 0.03569307433226635, 'weight_xgb_class_1': 0.6524133001100111, 'weight_xgb_class_2': 0.5478859419332133}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:32,650] Trial 1873 finished with value: 0.9490221522249723 and parameters: {'weight_lgbm_class_0': 0.09319590236640252, 'weight_lgbm_class_1': 0.4446125155588723, 'weight_lgbm_class_2': 0.4113006710238332, 'weight_xgb_class_0': 0.03701800524353721, 'weight_xgb_class_1': 0.6222957607701152, 'weight_xgb_class_2': 0.5438560950137866}. Best is trial 1561 with value: 0.9498642565074636.

[I 2026-07-05 15:32:32,733] Trial 1876 finished with value: 0.9167657855398555 and parameters: {'weight_lgbm_class_0': 0.5833504019068511, 'weight_lgbm_class_1': 0.9426187672411604, 'weight_lgbm_class_2': 0.3802304106013427, 'weight_xgb_class_0': 0.03540179665364533, 'weight_xgb_class_1': 0.6528501437197204, 'weight_xgb_class_2': 0.5419168067443928}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:32,741] Trial 1874 finished with value: 0.9492616494945135 and parameters: {'weight_lgbm_class_0': 0.08772071163281797, 'weight_lgbm_class_1': 0.944749187240311, 'weight_lgbm_class_2': 0.3770365079969815, 'weight_xgb_class_0': 0.03710892036093316, 'weight_xgb_class_1': 0.5652123266281739, 'weight_xgb_class_2': 0.5443913716683682}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:32,763] Trial 1875 finished with value: 0.9491771522939106 and parameters: {'weight_lgbm_class_0': 0.09137196219260188, 'weight_lgbm_class_1': 0.9428766314245153, 'weight_lgbm_class_2': 0.3751087712632949, 'weight_xgb_class_0': 0.0374660019950555, 'weight_xgb_class_1': 0.5939562002225071, 'weight_xgb_class_2': 0.5436371297382142}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:32,817] Trial 1877 finished with value: 0.949391213486277 and parameters: {'weight_lgbm_class_0': 0.08936837184505128, 'weight_lgbm_class_1': 0.9429467901587584, 'weight_lgbm_class_2': 0.3791859287533464, 'weight_xgb_class_0': 0.034775703293009344, 'weight_xgb_class_1': 0.6541991445405444, 'weight_xgb_class_2': 0.5527288408653163}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:32,886] Trial 1878 finished with value: 0.949372321686042 and parameters: {'weight_lgbm_class_0': 0.08886848056666712, 'weight_lgbm_class_1': 0.9476814507531434, 'weight_lgbm_class_2': 0.4168544764277887, 'weight_xgb_class_0': 0.03608776951076271, 'weight_xgb_class_1': 0.5855987502477786, 'weight_xgb_class_2': 0.5403102262465505}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:32,920] Trial 1879 finished with value: 0.9493116616208269 and parameters: {'weight_lgbm_class_0': 0.09098279778626239, 'weight_lgbm_class_1': 0.9479248627084296, 'weight_lgbm_class_2': 0.40037389866371725, 'weight_xgb_class_0': 0.036026799549829805, 'weight_xgb_class_1': 0.6594927725566271, 'weight_xgb_class_2': 0.5467297872858047}. Best is trial 1561 with value: 0.9498642565074636.

[I 2026-07-05 15:32:32,935] Trial 1880 finished with value: 0.9494604738550242 and parameters: {'weight_lgbm_class_0': 0.08633018079456581, 'weight_lgbm_class_1': 0.9502510517108903, 'weight_lgbm_class_2': 0.4025788756148544, 'weight_xgb_class_0': 0.03692318306161617, 'weight_xgb_class_1': 0.6946937672361105, 'weight_xgb_class_2': 0.5530496864771002}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:33,034] Trial 1881 finished with value: 0.9491756756825506 and parameters: {'weight_lgbm_class_0': 0.09267160344608184, 'weight_lgbm_class_1': 0.9483509399968799, 'weight_lgbm_class_2': 0.37864174346610324, 'weight_xgb_class_0': 0.037793879242954784, 'weight_xgb_class_1': 0.6569581483714462, 'weight_xgb_class_2': 0.5479578697824329}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:33,045] Trial 1882 finished with value: 0.9493817138481666 and parameters: {'weight_lgbm_class_0': 0.09138477171324266, 'weight_lgbm_class_1': 0.9511509358400585, 'weight_lgbm_class_2': 0.40158446392555036, 'weight_xgb_class_0': 0.033895174523920414, 'weight_xgb_class_1': 0.6533269250908234, 'weight_xgb_class_2': 0.5410293122454485}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:33,119] Trial 1883 finished with value: 0.9492578004376191 and parameters: {'weight_lgbm_class_0': 0.09485354516649806, 'weight_lgbm_class_1': 0.9462368844640527, 'weight_lgbm_class_2': 0.4106412428811123, 'weight_xgb_class_0': 0.03472393563976385, 'weight_xgb_class_1': 0.6938171749504715, 'weight_xgb_class_2': 0.536828504320513}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  94%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊       | 1889/2000 [01:02<00:05, 21.52it/s]

[I 2026-07-05 15:32:33,179] Trial 1885 finished with value: 0.9493991565929168 and parameters: {'weight_lgbm_class_0': 0.0919054991406277, 'weight_lgbm_class_1': 0.948496830943986, 'weight_lgbm_class_2': 0.41152728437357344, 'weight_xgb_class_0': 0.033546433486375926, 'weight_xgb_class_1': 0.695084864677495, 'weight_xgb_class_2': 0.5374722357860255}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:33,228] Trial 1884 finished with value: 0.9494263844363836 and parameters: {'weight_lgbm_class_0': 0.08795871125366128, 'weight_lgbm_class_1': 0.9478191067227194, 'weight_lgbm_class_2': 0.403825704199721, 'weight_xgb_class_0': 0.03524218062708724, 'weight_xgb_class_1': 0.6540769646768254, 'weight_xgb_class_2': 0.542410825103704}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:33,292] Trial 1886 finished with value: 0.9492693270865474 and parameters: {'weight_lgbm_class_0': 0.11252013773089048, 'weight_lgbm_class_1': 0.965600138356556, 'weight_lgbm_class_2': 0.3980481408406834, 'weight_xgb_class_0': 0.017707880384443164, 'weight_xgb_class_1': 0.6610176276198545, 'weight_xgb_class_2': 0.5545982944210698}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:33,332] Trial 1887 finished with value: 0.9455605445105218 and parameters: {'weight_lgbm_class_0': 0.03765419484754276, 'weight_lgbm_class_1': 0.9602614016991665, 'weight_lgbm_class_2': 0.10511714649126547, 'weight_xgb_class_0': 0.08691139903598911, 'weight_xgb_class_1': 0.6900306395577942, 'weight_xgb_class_2': 0.33574250469948286}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:33,349] Trial 1888 finished with value: 0.9491169523791113 and parameters: {'weight_lgbm_class_0': 0.11713909717751891, 'weight_lgbm_class_1': 0.9569840443833296, 'weight_lgbm_class_2': 0.4148981007017562, 'weight_xgb_class_0': 0.020757776339531537, 'weight_xgb_class_1': 0.6973078223332098, 'weight_xgb_class_2': 0.5362808420797227}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:33,377] Trial 1889 finished with value: 0.9476700364555309 and parameters: {'weight_lgbm_class_0': 0.11320799070952008, 'weight_lgbm_class_1': 0.9664794558349151, 'weight_lgbm_class_2': 0.40295941865012075, 'weight_xgb_class_0': 0.08523743797361921, 'weight_xgb_class_1': 0.6941754511217069, 'weight_xgb_class_2': 0.5346847801630519}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏      | 1895/2000 [01:02<00:04, 23.82it/s]

[I 2026-07-05 15:32:33,439] Trial 1891 finished with value: 0.9476742727768513 and parameters: {'weight_lgbm_class_0': 0.11403025306620271, 'weight_lgbm_class_1': 0.9659447322248339, 'weight_lgbm_class_2': 0.4152829740194984, 'weight_xgb_class_0': 0.08412757611237437, 'weight_xgb_class_1': 0.6929425429513395, 'weight_xgb_class_2': 0.5238806739921783}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:33,469] Trial 1890 finished with value: 0.9473668194756328 and parameters: {'weight_lgbm_class_0': 0.1180976847398795, 'weight_lgbm_class_1': 0.9647234398754341, 'weight_lgbm_class_2': 0.402647472966051, 'weight_xgb_class_0': 0.08514610653840816, 'weight_xgb_class_1': 0.6957550063442742, 'weight_xgb_class_2': 0.5200248489817352}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:33,503] Trial 1892 finished with value: 0.9491466621846038 and parameters: {'weight_lgbm_class_0': 0.11367189276376827, 'weight_lgbm_class_1': 0.9661015153622577, 'weight_lgbm_class_2': 0.400953568176584, 'weight_xgb_class_0': 0.018886004089061135, 'weight_xgb_class_1': 0.6965313923351383, 'weight_xgb_class_2': 0.5250341972193135}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:33,563] Trial 1894 finished with value: 0.9222030645576925 and parameters: {'weight_lgbm_class_0': 0.11445686861792903, 'weight_lgbm_class_1': 0.9648760854440309, 'weight_lgbm_class_2': 0.41491680049469915, 'weight_xgb_class_0': 0.4557810978265486, 'weight_xgb_class_1': 0.6932212786090693, 'weight_xgb_class_2': 0.5307656126966345}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:33,590] Trial 1893 finished with value: 0.9490414494340332 and parameters: {'weight_lgbm_class_0': 0.03834946713546944, 'weight_lgbm_class_1': 0.9707918494234227, 'weight_lgbm_class_2': 0.40302721596820174, 'weight_xgb_class_0': 0.08851317170471931, 'weight_xgb_class_1': 0.1815663378315347, 'weight_xgb_class_2': 0.5154168242942989}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:33,648] Trial 1895 finished with value: 0.8934195116447113 and parameters: {'weight_lgbm_class_0': 0.11478831365632956, 'weight_lgbm_class_1': 0.9660241329441145, 'weight_lgbm_class_2': 0.5889257284244126, 'weight_xgb_class_0': 0.9600849207414047, 'weight_xgb_class_1': 0.7173684384977818, 'weight_xgb_class_2': 0.5157800263181503}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌      | 1900/2000 [01:02<00:04, 20.95it/s]

[I 2026-07-05 15:32:33,752] Trial 1896 finished with value: 0.9487890792045569 and parameters: {'weight_lgbm_class_0': 0.037121933493738754, 'weight_lgbm_class_1': 0.9663791237521264, 'weight_lgbm_class_2': 0.42395034668833015, 'weight_xgb_class_0': 0.015562558134574639, 'weight_xgb_class_1': 0.7143360190976158, 'weight_xgb_class_2': 0.5130541823827879}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:33,827] Trial 1898 finished with value: 0.9491960502059578 and parameters: {'weight_lgbm_class_0': 0.039732915125956475, 'weight_lgbm_class_1': 0.38544215617860567, 'weight_lgbm_class_2': 0.424279894924428, 'weight_xgb_class_0': 0.08690714975152122, 'weight_xgb_class_1': 0.7098515183695877, 'weight_xgb_class_2': 0.5174004800639264}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:33,833] Trial 1897 finished with value: 0.9491238624764139 and parameters: {'weight_lgbm_class_0': 0.1205888340596363, 'weight_lgbm_class_1': 0.9655068906590072, 'weight_lgbm_class_2': 0.42611100272926294, 'weight_xgb_class_0': 0.016640155193438005, 'weight_xgb_class_1': 0.7143642543634403, 'weight_xgb_class_2': 0.520602279716446}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:33,880] Trial 1899 finished with value: 0.9477122079575754 and parameters: {'weight_lgbm_class_0': 0.11545970181527207, 'weight_lgbm_class_1': 0.966710244797099, 'weight_lgbm_class_2': 0.42268461449676287, 'weight_xgb_class_0': 0.08483617358279805, 'weight_xgb_class_1': 0.7198883973257324, 'weight_xgb_class_2': 0.5260270374482946}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:33,905] Trial 1900 finished with value: 0.9005797080317514 and parameters: {'weight_lgbm_class_0': 0.03478928581214138, 'weight_lgbm_class_1': 0.9693861697338672, 'weight_lgbm_class_2': 0.4258469408669353, 'weight_xgb_class_0': 0.861517815428385, 'weight_xgb_class_1': 0.7185660973541498, 'weight_xgb_class_2': 0.56598794554531}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉      | 1907/2000 [01:02<00:03, 25.28it/s]

[I 2026-07-05 15:32:33,909] Trial 1901 finished with value: 0.9497031665134313 and parameters: {'weight_lgbm_class_0': 0.1095514425597444, 'weight_lgbm_class_1': 0.9686903232692444, 'weight_lgbm_class_2': 0.4217545109464174, 'weight_xgb_class_0': 0.00011953564023293008, 'weight_xgb_class_1': 0.7165183856060701, 'weight_xgb_class_2': 0.5115935559679471}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:33,975] Trial 1902 finished with value: 0.9490494542729621 and parameters: {'weight_lgbm_class_0': 0.04105880154413494, 'weight_lgbm_class_1': 0.9071624795369247, 'weight_lgbm_class_2': 0.42664136820800874, 'weight_xgb_class_0': 0.017493523622834583, 'weight_xgb_class_1': 0.7192607025770678, 'weight_xgb_class_2': 0.5646039594858546}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:34,008] Trial 1903 finished with value: 0.949387396329247 and parameters: {'weight_lgbm_class_0': 0.039719618602555594, 'weight_lgbm_class_1': 0.16342437353510603, 'weight_lgbm_class_2': 0.43009926799638515, 'weight_xgb_class_0': 0.017800194985256403, 'weight_xgb_class_1': 0.7233792784461691, 'weight_xgb_class_2': 0.5651624177176978}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:34,057] Trial 1904 finished with value: 0.9484463098187778 and parameters: {'weight_lgbm_class_0': 0.03318992541663812, 'weight_lgbm_class_1': 0.9732876830841105, 'weight_lgbm_class_2': 0.42897656444728255, 'weight_xgb_class_0': 0.016361673016864836, 'weight_xgb_class_1': 0.71860908911386, 'weight_xgb_class_2': 0.5585387180149873}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:34,093] Trial 1905 finished with value: 0.9484685956219031 and parameters: {'weight_lgbm_class_0': 0.03411410208437995, 'weight_lgbm_class_1': 0.9056182304027293, 'weight_lgbm_class_2': 0.43904054962474137, 'weight_xgb_class_0': 0.014968435400808533, 'weight_xgb_class_1': 0.7174248167532324, 'weight_xgb_class_2': 0.5688317840663377}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:34,131] Trial 1906 finished with value: 0.949739340115892 and parameters: {'weight_lgbm_class_0': 0.07366436926985415, 'weight_lgbm_class_1': 0.9064633992883878, 'weight_lgbm_class_2': 0.44494243451039583, 'weight_xgb_class_0': 0.015845994675281805, 'weight_xgb_class_1': 0.7244334113346399, 'weight_xgb_class_2': 0.5652902416825247}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:34,155] Trial 1907 finished with value: 0.9495244699615317 and parameters: {'weight_lgbm_class_0': 0.07146478475763315, 'weight_lgbm_class_1': 0.9004067775364909, 'weight_lgbm_class_2': 0.4444158791689836, 'weight_xgb_class_0': 0.0018472268184085497, 'weight_xgb_class_1': 0.7179958992838447, 'weight_xgb_class_2': 0.5637094079962622}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏     | 1911/2000 [01:03<00:04, 21.55it/s]

[I 2026-07-05 15:32:34,263] Trial 1908 finished with value: 0.9494928536691956 and parameters: {'weight_lgbm_class_0': 0.07243783253021314, 'weight_lgbm_class_1': 0.910876510809733, 'weight_lgbm_class_2': 0.440308767860606, 'weight_xgb_class_0': 0.0002670593649289982, 'weight_xgb_class_1': 0.7154624750254677, 'weight_xgb_class_2': 0.5641173943080312}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:34,328] Trial 1909 finished with value: 0.9497237612469283 and parameters: {'weight_lgbm_class_0': 0.07447830914750368, 'weight_lgbm_class_1': 0.9056345989227904, 'weight_lgbm_class_2': 0.4472925414335706, 'weight_xgb_class_0': 0.016366132683939195, 'weight_xgb_class_1': 0.7286490765705498, 'weight_xgb_class_2': 0.5646257569961755}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:34,363] Trial 1910 finished with value: 0.9285265915655314 and parameters: {'weight_lgbm_class_0': 0.4984575699235683, 'weight_lgbm_class_1': 0.982135439524719, 'weight_lgbm_class_2': 0.44622122214105514, 'weight_xgb_class_0': 0.015555752321133213, 'weight_xgb_class_1': 0.7324997484047505, 'weight_xgb_class_2': 0.5626963540525538}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:34,443] Trial 1911 finished with value: 0.9497252887910839 and parameters: {'weight_lgbm_class_0': 0.07185784019419642, 'weight_lgbm_class_1': 0.9026058140867254, 'weight_lgbm_class_2': 0.4409735183399023, 'weight_xgb_class_0': 0.013905087068736204, 'weight_xgb_class_1': 0.729928195715849, 'weight_xgb_class_2': 0.5639678132514863}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋     | 1918/2000 [01:03<00:03, 22.14it/s]

[I 2026-07-05 15:32:34,452] Trial 1912 finished with value: 0.9497294742824055 and parameters: {'weight_lgbm_class_0': 0.07606283980387846, 'weight_lgbm_class_1': 0.903623478148399, 'weight_lgbm_class_2': 0.447801863833901, 'weight_xgb_class_0': 0.015832152833584343, 'weight_xgb_class_1': 0.6745112560188159, 'weight_xgb_class_2': 0.5683735622581012}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:34,478] Trial 1913 finished with value: 0.9497480220050267 and parameters: {'weight_lgbm_class_0': 0.06653395001344926, 'weight_lgbm_class_1': 0.9028240769420359, 'weight_lgbm_class_2': 0.44469922257776423, 'weight_xgb_class_0': 0.015820275646634366, 'weight_xgb_class_1': 0.3715669083429712, 'weight_xgb_class_2': 0.47600078509235977}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:34,569] Trial 1915 finished with value: 0.949499261519008 and parameters: {'weight_lgbm_class_0': 0.06878164453163588, 'weight_lgbm_class_1': 0.9029829452318827, 'weight_lgbm_class_2': 0.4397361072049667, 'weight_xgb_class_0': 0.0012251900796334946, 'weight_xgb_class_1': 0.6738335800220303, 'weight_xgb_class_2': 0.46762696199216897}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:34,570] Trial 1914 finished with value: 0.9497077237694985 and parameters: {'weight_lgbm_class_0': 0.06961827377792802, 'weight_lgbm_class_1': 0.9087495216491043, 'weight_lgbm_class_2': 0.4497422923523928, 'weight_xgb_class_0': 0.05029010604166713, 'weight_xgb_class_1': 0.6722239759098615, 'weight_xgb_class_2': 0.5838831381668357}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:34,597] Trial 1916 finished with value: 0.94933180512168 and parameters: {'weight_lgbm_class_0': 0.07251441476198102, 'weight_lgbm_class_1': 0.9820578379176182, 'weight_lgbm_class_2': 0.44880088320361966, 'weight_xgb_class_0': 0.05151827786160861, 'weight_xgb_class_1': 0.6778755261089664, 'weight_xgb_class_2': 0.4748313231023973}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:34,629] Trial 1917 finished with value: 0.94917338305433 and parameters: {'weight_lgbm_class_0': 0.0770516074582635, 'weight_lgbm_class_1': 0.9826330186479392, 'weight_lgbm_class_2': 0.4443644982158423, 'weight_xgb_class_0': 0.05266903221749009, 'weight_xgb_class_1': 0.6759066167832385, 'weight_xgb_class_2': 0.4789509288781946}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:34,672] Trial 1918 finished with value: 0.9495650822410425 and parameters: {'weight_lgbm_class_0': 0.07573033764712622, 'weight_lgbm_class_1': 0.9822015115690005, 'weight_lgbm_class_2': 0.45061144425908417, 'weight_xgb_class_0': 0.05236183703992304, 'weight_xgb_class_1': 0.6758595483231842, 'weight_xgb_class_2': 0.5899893157695314}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉     | 1922/2000 [01:03<00:03, 23.41it/s]

[I 2026-07-05 15:32:34,678] Trial 1919 finished with value: 0.9495811359174495 and parameters: {'weight_lgbm_class_0': 0.07353085407453708, 'weight_lgbm_class_1': 0.9786634669910761, 'weight_lgbm_class_2': 0.44761430520778117, 'weight_xgb_class_0': 0.0013651365334229712, 'weight_xgb_class_1': 0.6754935037095504, 'weight_xgb_class_2': 0.47577858572382115}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:34,731] Trial 1920 finished with value: 0.9491535567537662 and parameters: {'weight_lgbm_class_0': 0.07191090496746075, 'weight_lgbm_class_1': 0.9786303145732498, 'weight_lgbm_class_2': 0.3819322469836095, 'weight_xgb_class_0': 0.05147190742874712, 'weight_xgb_class_1': 0.6784649901872204, 'weight_xgb_class_2': 0.4736187445722758}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:34,829] Trial 1921 finished with value: 0.9495811703428778 and parameters: {'weight_lgbm_class_0': 0.07530947779565396, 'weight_lgbm_class_1': 0.9999511599493168, 'weight_lgbm_class_2': 0.3836833312783261, 'weight_xgb_class_0': 0.0006827342711489725, 'weight_xgb_class_1': 0.6807510135303857, 'weight_xgb_class_2': 0.47170535867588614}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:34,882] Trial 1922 finished with value: 0.9495156485145607 and parameters: {'weight_lgbm_class_0': 0.07380484812467986, 'weight_lgbm_class_1': 0.9998516247201712, 'weight_lgbm_class_2': 0.38559379101479807, 'weight_xgb_class_0': 0.05060306497543414, 'weight_xgb_class_1': 0.675924751623843, 'weight_xgb_class_2': 0.5905172477698605}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍    | 1929/2000 [01:03<00:03, 22.53it/s]

[I 2026-07-05 15:32:35,011] Trial 1923 finished with value: 0.9477405460114331 and parameters: {'weight_lgbm_class_0': 0.14895028545128453, 'weight_lgbm_class_1': 0.9849819515491575, 'weight_lgbm_class_2': 0.38105383279547195, 'weight_xgb_class_0': 0.051798178419249864, 'weight_xgb_class_1': 0.6760385095683838, 'weight_xgb_class_2': 0.5897955924279608}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:35,046] Trial 1925 finished with value: 0.9480218391713148 and parameters: {'weight_lgbm_class_0': 0.142113156087572, 'weight_lgbm_class_1': 0.999767380602232, 'weight_lgbm_class_2': 0.3808707003389372, 'weight_xgb_class_0': 0.05124257697810319, 'weight_xgb_class_1': 0.681231860334322, 'weight_xgb_class_2': 0.5879171652554426}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:35,061] Trial 1924 finished with value: 0.9491792635399028 and parameters: {'weight_lgbm_class_0': 0.13620046436494188, 'weight_lgbm_class_1': 0.9810375031148119, 'weight_lgbm_class_2': 0.3811105777639297, 'weight_xgb_class_0': 0.000684711493523088, 'weight_xgb_class_1': 0.6856962211023934, 'weight_xgb_class_2': 0.592985563153849}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:35,079] Trial 1926 finished with value: 0.9488808518363694 and parameters: {'weight_lgbm_class_0': 0.09795428943218948, 'weight_lgbm_class_1': 0.9838678917929543, 'weight_lgbm_class_2': 0.38188323064263757, 'weight_xgb_class_0': 0.05321125740770972, 'weight_xgb_class_1': 0.653042808868033, 'weight_xgb_class_2': 0.5967360267903167}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:35,133] Trial 1927 finished with value: 0.9480430356275057 and parameters: {'weight_lgbm_class_0': 0.14260442981240928, 'weight_lgbm_class_1': 0.9848720312996331, 'weight_lgbm_class_2': 0.38671914732880563, 'weight_xgb_class_0': 0.05237851659213852, 'weight_xgb_class_1': 0.7363001697956629, 'weight_xgb_class_2': 0.5904361286306341}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:35,158] Trial 1929 finished with value: 0.9339264635072061 and parameters: {'weight_lgbm_class_0': 0.14561338525356984, 'weight_lgbm_class_1': 0.9995233705425144, 'weight_lgbm_class_2': 0.38919639266125233, 'weight_xgb_class_0': 0.2930622706554331, 'weight_xgb_class_1': 0.7426864105662982, 'weight_xgb_class_2': 0.5912028343801488}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:35,202] Trial 1928 finished with value: 0.9490823378423302 and parameters: {'weight_lgbm_class_0': 0.14332781182152252, 'weight_lgbm_class_1': 0.9997842668060818, 'weight_lgbm_class_2': 0.38736729578296775, 'weight_xgb_class_0': 0.000719690973478571, 'weight_xgb_class_1': 0.7392922974695723, 'weight_xgb_class_2': 0.590961532721297}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  97%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋    | 1934/2000 [01:04<00:02, 24.18it/s]

[I 2026-07-05 15:32:35,251] Trial 1930 finished with value: 0.9498064408603405 and parameters: {'weight_lgbm_class_0': 0.09916874086427244, 'weight_lgbm_class_1': 0.9988765140287564, 'weight_lgbm_class_2': 0.38831339321953295, 'weight_xgb_class_0': 0.0007908215767771421, 'weight_xgb_class_1': 0.7347867059860903, 'weight_xgb_class_2': 0.6047317237349326}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:35,264] Trial 1931 finished with value: 0.9485736065273391 and parameters: {'weight_lgbm_class_0': 0.13346449288414466, 'weight_lgbm_class_1': 0.9433351096027803, 'weight_lgbm_class_2': 0.3973102901726782, 'weight_xgb_class_0': 0.03493137325114521, 'weight_xgb_class_1': 0.7355496046099724, 'weight_xgb_class_2': 0.5873395750874171}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:35,317] Trial 1932 finished with value: 0.9491734438097875 and parameters: {'weight_lgbm_class_0': 0.13794474283203806, 'weight_lgbm_class_1': 0.9991482821477956, 'weight_lgbm_class_2': 0.38906386040959434, 'weight_xgb_class_0': 9.11421694162922e-06, 'weight_xgb_class_1': 0.6493311624505737, 'weight_xgb_class_2': 0.5879601204856307}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:35,337] Trial 1933 finished with value: 0.9492165518526662 and parameters: {'weight_lgbm_class_0': 0.1352908918855378, 'weight_lgbm_class_1': 0.9462384429186768, 'weight_lgbm_class_2': 0.3941087156772218, 'weight_xgb_class_0': 0.0006266401179395608, 'weight_xgb_class_1': 0.7358515420272781, 'weight_xgb_class_2': 0.5858399708120376}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:35,400] Trial 1934 finished with value: 0.9484719512612448 and parameters: {'weight_lgbm_class_0': 0.13030098305235144, 'weight_lgbm_class_1': 0.9465447602395921, 'weight_lgbm_class_2': 0.39226768206759144, 'weight_xgb_class_0': 0.033377062302091004, 'weight_xgb_class_1': 0.7413059971587768, 'weight_xgb_class_2': 0.5373949244015211}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  97%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉    | 1938/2000 [01:04<00:02, 22.02it/s]

[I 2026-07-05 15:32:35,496] Trial 1935 finished with value: 0.9491780447304768 and parameters: {'weight_lgbm_class_0': 0.10191751839085862, 'weight_lgbm_class_1': 0.9444598881185531, 'weight_lgbm_class_2': 0.40739701306294696, 'weight_xgb_class_0': 0.030636439224630323, 'weight_xgb_class_1': 0.7369297501885884, 'weight_xgb_class_2': 0.5369649726190565}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:35,605] Trial 1938 finished with value: 0.9269405753147627 and parameters: {'weight_lgbm_class_0': 0.10105735610926445, 'weight_lgbm_class_1': 0.24869675043982736, 'weight_lgbm_class_2': 0.4726403505986473, 'weight_xgb_class_0': 0.34526117354901653, 'weight_xgb_class_1': 0.7419954357549672, 'weight_xgb_class_2': 0.536748380067799}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:35,623] Trial 1936 finished with value: 0.9490846964585282 and parameters: {'weight_lgbm_class_0': 0.10509447066593491, 'weight_lgbm_class_1': 0.9439296413256428, 'weight_lgbm_class_2': 0.3983915795465121, 'weight_xgb_class_0': 0.032313936521454034, 'weight_xgb_class_1': 0.745251493113279, 'weight_xgb_class_2': 0.5377149582108655}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:35,676] Trial 1937 finished with value: 0.9491630509537633 and parameters: {'weight_lgbm_class_0': 0.09972545866898497, 'weight_lgbm_class_1': 0.9478306105172779, 'weight_lgbm_class_2': 0.40155896405367014, 'weight_xgb_class_0': 0.033217328973082105, 'weight_xgb_class_1': 0.7329282806406776, 'weight_xgb_class_2': 0.537812221749827}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍   | 1945/2000 [01:04<00:02, 22.31it/s]

[I 2026-07-05 15:32:35,685] Trial 1939 finished with value: 0.9491620500209587 and parameters: {'weight_lgbm_class_0': 0.10283909240260461, 'weight_lgbm_class_1': 0.9433992882689157, 'weight_lgbm_class_2': 0.4136764086559365, 'weight_xgb_class_0': 0.03233334779074276, 'weight_xgb_class_1': 0.6372174780885905, 'weight_xgb_class_2': 0.5399775977884219}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:35,727] Trial 1940 finished with value: 0.9494310383998589 and parameters: {'weight_lgbm_class_0': 0.09987398767434937, 'weight_lgbm_class_1': 0.945201392015126, 'weight_lgbm_class_2': 0.4730170739441344, 'weight_xgb_class_0': 0.032706558785136175, 'weight_xgb_class_1': 0.7802151034935765, 'weight_xgb_class_2': 0.5388181419718473}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:35,754] Trial 1941 finished with value: 0.9493905942769884 and parameters: {'weight_lgbm_class_0': 0.10058106415046143, 'weight_lgbm_class_1': 0.9479968381223536, 'weight_lgbm_class_2': 0.4745005819158924, 'weight_xgb_class_0': 0.03080765997502402, 'weight_xgb_class_1': 0.635925053675413, 'weight_xgb_class_2': 0.5407715252430403}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:35,764] Trial 1942 finished with value: 0.9490357780970097 and parameters: {'weight_lgbm_class_0': 0.10910873148688122, 'weight_lgbm_class_1': 0.9463583568148676, 'weight_lgbm_class_2': 0.41730947370584576, 'weight_xgb_class_0': 0.03247493426180017, 'weight_xgb_class_1': 0.64286617120345, 'weight_xgb_class_2': 0.5382951023089612}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:35,809] Trial 1943 finished with value: 0.9489112967183589 and parameters: {'weight_lgbm_class_0': 0.11261516829318875, 'weight_lgbm_class_1': 0.9467486340777632, 'weight_lgbm_class_2': 0.4699430430922811, 'weight_xgb_class_0': 0.03735321292368683, 'weight_xgb_class_1': 0.6378709087969947, 'weight_xgb_class_2': 0.5381935104785376}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:35,848] Trial 1944 finished with value: 0.9492828338201723 and parameters: {'weight_lgbm_class_0': 0.10098739252890643, 'weight_lgbm_class_1': 0.9492747599738435, 'weight_lgbm_class_2': 0.4677246467740054, 'weight_xgb_class_0': 0.03616794624259804, 'weight_xgb_class_1': 0.7797680768994694, 'weight_xgb_class_2': 0.5426604105152869}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:35,896] Trial 1946 finished with value: 0.9490756387236369 and parameters: {'weight_lgbm_class_0': 0.10974224900011427, 'weight_lgbm_class_1': 0.9581281682744017, 'weight_lgbm_class_2': 0.4159667735512207, 'weight_xgb_class_0': 0.03327355037267375, 'weight_xgb_class_1': 0.776422521691202, 'weight_xgb_class_2': 0.552371765175849}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌   | 1947/2000 [01:04<00:02, 25.30it/s]

[I 2026-07-05 15:32:35,906] Trial 1945 finished with value: 0.9491562754153643 and parameters: {'weight_lgbm_class_0': 0.10622697316295704, 'weight_lgbm_class_1': 0.9507843902858238, 'weight_lgbm_class_2': 0.41654353824690715, 'weight_xgb_class_0': 0.02905234224475836, 'weight_xgb_class_1': 0.6341058696733222, 'weight_xgb_class_2': 0.538009741985367}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:36,011] Trial 1947 finished with value: 0.949173551627475 and parameters: {'weight_lgbm_class_0': 0.10066888156058959, 'weight_lgbm_class_1': 0.9631357389386064, 'weight_lgbm_class_2': 0.4203407490025363, 'weight_xgb_class_0': 0.03152104501484085, 'weight_xgb_class_1': 0.7823608233725503, 'weight_xgb_class_2': 0.5069179372056474}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  98%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉   | 1953/2000 [01:04<00:02, 19.89it/s]

[I 2026-07-05 15:32:36,165] Trial 1948 finished with value: 0.9491001381523286 and parameters: {'weight_lgbm_class_0': 0.10085817058955479, 'weight_lgbm_class_1': 0.9669992608668555, 'weight_lgbm_class_2': 0.4186353274010847, 'weight_xgb_class_0': 0.033895695213174704, 'weight_xgb_class_1': 0.7018099629018215, 'weight_xgb_class_2': 0.5090695156207574}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:36,182] Trial 1949 finished with value: 0.9479840004590937 and parameters: {'weight_lgbm_class_0': 0.12128363844949298, 'weight_lgbm_class_1': 0.963234507431938, 'weight_lgbm_class_2': 0.4690990667603134, 'weight_xgb_class_0': 0.07463099057238619, 'weight_xgb_class_1': 0.7020043579187126, 'weight_xgb_class_2': 0.5057864355066661}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:36,249] Trial 1951 finished with value: 0.9454905277906344 and parameters: {'weight_lgbm_class_0': 0.04696827894478261, 'weight_lgbm_class_1': 0.9653044425592879, 'weight_lgbm_class_2': 0.4196153944991249, 'weight_xgb_class_0': 0.06594712725506585, 'weight_xgb_class_1': 0.6986581082510692, 'weight_xgb_class_2': 0.0005224369233186033}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:36,257] Trial 1950 finished with value: 0.9494722897038684 and parameters: {'weight_lgbm_class_0': 0.045887470202035846, 'weight_lgbm_class_1': 0.9614882517101805, 'weight_lgbm_class_2': 0.4254873761295327, 'weight_xgb_class_0': 0.07576169735754357, 'weight_xgb_class_1': 0.7045910426742933, 'weight_xgb_class_2': 0.5049772932421128}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:36,304] Trial 1952 finished with value: 0.9497126375754134 and parameters: {'weight_lgbm_class_0': 0.04382466231196469, 'weight_lgbm_class_1': 0.9679854796383828, 'weight_lgbm_class_2': 0.4259572226972378, 'weight_xgb_class_0': 0.06833202799481108, 'weight_xgb_class_1': 0.7032770866224182, 'weight_xgb_class_2': 0.5149979075159085}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:36,317] Trial 1953 finished with value: 0.9494157668752107 and parameters: {'weight_lgbm_class_0': 0.04977386164285384, 'weight_lgbm_class_1': 0.9666755659396424, 'weight_lgbm_class_2': 0.4260445917674417, 'weight_xgb_class_0': 0.07460348222873833, 'weight_xgb_class_1': 0.69909087198112, 'weight_xgb_class_2': 0.5099082649530539}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎  | 1959/2000 [01:05<00:01, 22.90it/s]

[I 2026-07-05 15:32:36,366] Trial 1956 finished with value: 0.9497395051220092 and parameters: {'weight_lgbm_class_0': 0.051618570890665086, 'weight_lgbm_class_1': 0.9702360498699112, 'weight_lgbm_class_2': 0.8872331888810223, 'weight_xgb_class_0': 0.07574775869269287, 'weight_xgb_class_1': 0.7007814917063131, 'weight_xgb_class_2': 0.5053323232716858}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:36,394] Trial 1955 finished with value: 0.9494759408301418 and parameters: {'weight_lgbm_class_0': 0.04892938095057593, 'weight_lgbm_class_1': 0.9679640095579045, 'weight_lgbm_class_2': 0.4247588685314186, 'weight_xgb_class_0': 0.07008098703901966, 'weight_xgb_class_1': 0.7005504126802076, 'weight_xgb_class_2': 0.5006521633032335}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:36,406] Trial 1954 finished with value: 0.9496102557268414 and parameters: {'weight_lgbm_class_0': 0.04826179116257878, 'weight_lgbm_class_1': 0.9641182216113411, 'weight_lgbm_class_2': 0.4307539970117106, 'weight_xgb_class_0': 0.06766740434047208, 'weight_xgb_class_1': 0.7017749415673893, 'weight_xgb_class_2': 0.5090743803209247}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:36,413] Trial 1957 finished with value: 0.9494048027562721 and parameters: {'weight_lgbm_class_0': 0.04985638407967937, 'weight_lgbm_class_1': 0.9736811823099081, 'weight_lgbm_class_2': 0.42890370347991635, 'weight_xgb_class_0': 0.07423918389939102, 'weight_xgb_class_1': 0.7043832327064226, 'weight_xgb_class_2': 0.5074899271287786}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:36,482] Trial 1958 finished with value: 0.9495186825748477 and parameters: {'weight_lgbm_class_0': 0.04929583061926128, 'weight_lgbm_class_1': 0.9649091196100583, 'weight_lgbm_class_2': 0.4246274858037421, 'weight_xgb_class_0': 0.06965727555102823, 'weight_xgb_class_1': 0.7027139373879105, 'weight_xgb_class_2': 0.508987480821791}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:36,506] Trial 1959 finished with value: 0.949806196928768 and parameters: {'weight_lgbm_class_0': 0.04867297503003675, 'weight_lgbm_class_1': 0.9697636008127776, 'weight_lgbm_class_2': 0.42589693288802494, 'weight_xgb_class_0': 0.05976269951575884, 'weight_xgb_class_1': 0.7023912032997376, 'weight_xgb_class_2': 0.5149195622081952}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 1963/2000 [01:05<00:01, 22.15it/s]

[I 2026-07-05 15:32:36,636] Trial 1960 finished with value: 0.8933938158473028 and parameters: {'weight_lgbm_class_0': 0.9103916643759624, 'weight_lgbm_class_1': 0.97930075034739, 'weight_lgbm_class_2': 0.42757641819918946, 'weight_xgb_class_0': 0.07530099344849542, 'weight_xgb_class_1': 0.7014747891316794, 'weight_xgb_class_2': 0.5114514864436388}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:36,674] Trial 1961 finished with value: 0.9488235625568401 and parameters: {'weight_lgbm_class_0': 0.05041060649080366, 'weight_lgbm_class_1': 0.1964145642881106, 'weight_lgbm_class_2': 0.42627846241440714, 'weight_xgb_class_0': 0.07648406491749116, 'weight_xgb_class_1': 0.7029261668412586, 'weight_xgb_class_2': 0.5094093115052173}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:36,745] Trial 1962 finished with value: 0.9494713237032273 and parameters: {'weight_lgbm_class_0': 0.05581853292673216, 'weight_lgbm_class_1': 0.9779096308460898, 'weight_lgbm_class_2': 0.45603460515881517, 'weight_xgb_class_0': 0.015503175010493322, 'weight_xgb_class_1': 0.6576690570353135, 'weight_xgb_class_2': 0.5612457556435312}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:36,844] Trial 1963 finished with value: 0.9495090482137319 and parameters: {'weight_lgbm_class_0': 0.05829150807554417, 'weight_lgbm_class_1': 0.9220187877021689, 'weight_lgbm_class_2': 0.4549086794108971, 'weight_xgb_class_0': 0.01689065018049321, 'weight_xgb_class_1': 0.6603859858411953, 'weight_xgb_class_2': 0.5604711389701567}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████  | 1970/2000 [01:05<00:01, 22.05it/s]

[I 2026-07-05 15:32:36,853] Trial 1965 finished with value: 0.9490387369272638 and parameters: {'weight_lgbm_class_0': 0.085946951821612, 'weight_lgbm_class_1': 0.9276661887265296, 'weight_lgbm_class_2': 3.125324807012886e-05, 'weight_xgb_class_0': 0.0005106203456317306, 'weight_xgb_class_1': 0.6649488635176605, 'weight_xgb_class_2': 0.5605642330420091}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:36,905] Trial 1964 finished with value: 0.9497618585834565 and parameters: {'weight_lgbm_class_0': 0.08452668382996426, 'weight_lgbm_class_1': 0.9263268228964731, 'weight_lgbm_class_2': 0.4533708756599769, 'weight_xgb_class_0': 0.017441687495484526, 'weight_xgb_class_1': 0.6626269481014703, 'weight_xgb_class_2': 0.5597262479140523}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:36,943] Trial 1966 finished with value: 0.9497355803905835 and parameters: {'weight_lgbm_class_0': 0.08982690624241292, 'weight_lgbm_class_1': 0.9998779110950808, 'weight_lgbm_class_2': 0.45612623654730045, 'weight_xgb_class_0': 0.0003397087426503221, 'weight_xgb_class_1': 0.6535753493923854, 'weight_xgb_class_2': 0.5569326484811193}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:36,983] Trial 1967 finished with value: 0.9479376659946764 and parameters: {'weight_lgbm_class_0': 0.18041363402060104, 'weight_lgbm_class_1': 0.9235604062672049, 'weight_lgbm_class_2': 0.4553079920600666, 'weight_xgb_class_0': 0.017176183164137448, 'weight_xgb_class_1': 0.6632089387667354, 'weight_xgb_class_2': 0.5618959834832173}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:37,001] Trial 1968 finished with value: 0.9496315196439408 and parameters: {'weight_lgbm_class_0': 0.08219842574731791, 'weight_lgbm_class_1': 0.9260445323075861, 'weight_lgbm_class_2': 0.4553157181666395, 'weight_xgb_class_0': 0.00025590982295372114, 'weight_xgb_class_1': 0.7587698248581864, 'weight_xgb_class_2': 0.5630155958994251}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:37,014] Trial 1970 finished with value: 0.9497638911969557 and parameters: {'weight_lgbm_class_0': 0.07930923563579417, 'weight_lgbm_class_1': 0.9195695495105676, 'weight_lgbm_class_2': 0.45507564052764604, 'weight_xgb_class_0': 0.01526042172144757, 'weight_xgb_class_1': 0.6633781710669249, 'weight_xgb_class_2': 0.558531182599933}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:37,020] Trial 1969 finished with value: 0.9498338666344285 and parameters: {'weight_lgbm_class_0': 0.08382581569588819, 'weight_lgbm_class_1': 0.9226341738218418, 'weight_lgbm_class_2': 0.4516754688720144, 'weight_xgb_class_0': 0.016131758523348177, 'weight_xgb_class_1': 0.6819262638990531, 'weight_xgb_class_2': 0.560068933991594}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  99%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎ | 1974/2000 [01:05<00:01, 23.35it/s]

[I 2026-07-05 15:32:37,072] Trial 1971 finished with value: 0.949744864632224 and parameters: {'weight_lgbm_class_0': 0.08937493559828402, 'weight_lgbm_class_1': 0.925843448034288, 'weight_lgbm_class_2': 0.4554819792838391, 'weight_xgb_class_0': 0.00010385922252793215, 'weight_xgb_class_1': 0.6657285770241939, 'weight_xgb_class_2': 0.5635524561876599}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:37,183] Trial 1973 finished with value: 0.9497555561406649 and parameters: {'weight_lgbm_class_0': 0.08451883851377613, 'weight_lgbm_class_1': 0.9304899374971854, 'weight_lgbm_class_2': 0.45270718783524866, 'weight_xgb_class_0': 0.01698481401293172, 'weight_xgb_class_1': 0.6557320202240075, 'weight_xgb_class_2': 0.5601553494867465}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:37,189] Trial 1972 finished with value: 0.9497595014604691 and parameters: {'weight_lgbm_class_0': 0.0843564427019969, 'weight_lgbm_class_1': 0.9262384718141626, 'weight_lgbm_class_2': 0.46342025555276906, 'weight_xgb_class_0': 0.016118214816359534, 'weight_xgb_class_1': 0.6607260429436058, 'weight_xgb_class_2': 0.5679662171408358}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:37,233] Trial 1974 finished with value: 0.9497351453236053 and parameters: {'weight_lgbm_class_0': 0.08614512903662438, 'weight_lgbm_class_1': 0.9268085156809817, 'weight_lgbm_class_2': 0.4598490853009109, 'weight_xgb_class_0': 0.016247068201018768, 'weight_xgb_class_1': 0.6610906294895786, 'weight_xgb_class_2': 0.5610676089440484}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  99%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊ | 1981/2000 [01:06<00:00, 22.23it/s]

[I 2026-07-05 15:32:37,406] Trial 1975 finished with value: 0.9497914019591063 and parameters: {'weight_lgbm_class_0': 0.08493490213263036, 'weight_lgbm_class_1': 0.9836718717139631, 'weight_lgbm_class_2': 0.40140147087423667, 'weight_xgb_class_0': 0.018203593356902723, 'weight_xgb_class_1': 0.7623106432453775, 'weight_xgb_class_2': 0.6094447081610616}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:37,429] Trial 1977 finished with value: 0.9469249841020551 and parameters: {'weight_lgbm_class_0': 0.12792002646055842, 'weight_lgbm_class_1': 0.9821225448353712, 'weight_lgbm_class_2': 0.39983738617938736, 'weight_xgb_class_0': 0.020100459835213386, 'weight_xgb_class_1': 0.7642126463593535, 'weight_xgb_class_2': 0.2267644896179687}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:37,459] Trial 1976 finished with value: 0.9492540407123103 and parameters: {'weight_lgbm_class_0': 0.12312034179957437, 'weight_lgbm_class_1': 0.9997941488550909, 'weight_lgbm_class_2': 0.4027610643702373, 'weight_xgb_class_0': 0.016497270329737527, 'weight_xgb_class_1': 0.7601254805161318, 'weight_xgb_class_2': 0.6141767021491382}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:37,464] Trial 1978 finished with value: 0.9492189512783212 and parameters: {'weight_lgbm_class_0': 0.1195102202785451, 'weight_lgbm_class_1': 0.9837134797224317, 'weight_lgbm_class_2': 0.40046676054596314, 'weight_xgb_class_0': 0.02037440839886447, 'weight_xgb_class_1': 0.7509119387883197, 'weight_xgb_class_2': 0.6071344977492495}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:37,538] Trial 1979 finished with value: 0.9244973264110223 and parameters: {'weight_lgbm_class_0': 0.5169405475230253, 'weight_lgbm_class_1': 0.9830720594966423, 'weight_lgbm_class_2': 0.4019530084604734, 'weight_xgb_class_0': 0.0003319120674827314, 'weight_xgb_class_1': 0.4049184859309314, 'weight_xgb_class_2': 0.5766503784703358}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:37,540] Trial 1980 finished with value: 0.9486642628789057 and parameters: {'weight_lgbm_class_0': 0.11669771576303536, 'weight_lgbm_class_1': 0.9844987990279885, 'weight_lgbm_class_2': 0.40444457145778306, 'weight_xgb_class_0': 0.05050860693283782, 'weight_xgb_class_1': 0.726206518586536, 'weight_xgb_class_2': 0.6070149052968826}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:37,593] Trial 1981 finished with value: 0.9484386415706645 and parameters: {'weight_lgbm_class_0': 0.12670930618376275, 'weight_lgbm_class_1': 0.9822879726660112, 'weight_lgbm_class_2': 0.40353448257556485, 'weight_xgb_class_0': 0.051205428813355165, 'weight_xgb_class_1': 0.7530779779491923, 'weight_xgb_class_2': 0.5772765658381379}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864:  99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏| 1987/2000 [01:06<00:00, 23.86it/s]

[I 2026-07-05 15:32:37,607] Trial 1982 finished with value: 0.9494680210622578 and parameters: {'weight_lgbm_class_0': 0.12174072904206529, 'weight_lgbm_class_1': 0.9835980213252691, 'weight_lgbm_class_2': 0.4018989203118749, 'weight_xgb_class_0': 8.49734006977763e-05, 'weight_xgb_class_1': 0.11665158551530458, 'weight_xgb_class_2': 0.6155371635944799}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:37,625] Trial 1983 finished with value: 0.9450772998589471 and parameters: {'weight_lgbm_class_0': 0.12995004939376986, 'weight_lgbm_class_1': 0.9831061731800851, 'weight_lgbm_class_2': 0.4027729838303132, 'weight_xgb_class_0': 0.046652860768569324, 'weight_xgb_class_1': 0.7587514267427448, 'weight_xgb_class_2': 0.2185692243411408}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:37,717] Trial 1984 finished with value: 0.948715968711853 and parameters: {'weight_lgbm_class_0': 0.12085540228840388, 'weight_lgbm_class_1': 0.982899471266262, 'weight_lgbm_class_2': 0.4037710712873948, 'weight_xgb_class_0': 0.046253747585403314, 'weight_xgb_class_1': 0.759006796739318, 'weight_xgb_class_2': 0.609323670132534}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:37,763] Trial 1986 finished with value: 0.9455332719821801 and parameters: {'weight_lgbm_class_0': 0.12199918389481394, 'weight_lgbm_class_1': 0.9850894367029933, 'weight_lgbm_class_2': 0.4051490517263208, 'weight_xgb_class_0': 0.048321183233086505, 'weight_xgb_class_1': 0.7228742832676861, 'weight_xgb_class_2': 0.22528839900961517}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:37,781] Trial 1985 finished with value: 0.9485450607896831 and parameters: {'weight_lgbm_class_0': 0.12487964235819815, 'weight_lgbm_class_1': 0.9999506616658893, 'weight_lgbm_class_2': 0.4036226994778881, 'weight_xgb_class_0': 0.04921098210654443, 'weight_xgb_class_1': 0.7317265405708522, 'weight_xgb_class_2': 0.609778967048968}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1561. Best value: 0.949864: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍| 1992/2000 [01:06<00:00, 18.55it/s]

[I 2026-07-05 15:32:37,947] Trial 1987 finished with value: 0.9482735125691528 and parameters: {'weight_lgbm_class_0': 0.12440262196916119, 'weight_lgbm_class_1': 0.9842854000296758, 'weight_lgbm_class_2': 0.40470010615295204, 'weight_xgb_class_0': 0.05195320343877389, 'weight_xgb_class_1': 0.7256989717584661, 'weight_xgb_class_2': 0.5289170864654839}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:38,027] Trial 1988 finished with value: 0.9484663607569352 and parameters: {'weight_lgbm_class_0': 0.12429217916818959, 'weight_lgbm_class_1': 0.9998140063225593, 'weight_lgbm_class_2': 0.3717930183532809, 'weight_xgb_class_0': 0.04531859757486013, 'weight_xgb_class_1': 0.724505861812348, 'weight_xgb_class_2': 0.5793638252343297}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:38,055] Trial 1990 finished with value: 0.9498286275169319 and parameters: {'weight_lgbm_class_0': 0.06365744559875179, 'weight_lgbm_class_1': 0.9995857322283699, 'weight_lgbm_class_2': 0.4812356946591128, 'weight_xgb_class_0': 0.048810146563443624, 'weight_xgb_class_1': 0.7163918909158302, 'weight_xgb_class_2': 0.5288435056216878}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:38,073] Trial 1989 finished with value: 0.9477900224802287 and parameters: {'weight_lgbm_class_0': 0.1236619781463256, 'weight_lgbm_class_1': 0.48823103884253694, 'weight_lgbm_class_2': 0.3733513306808915, 'weight_xgb_class_0': 0.05074497105621334, 'weight_xgb_class_1': 0.7202469932034187, 'weight_xgb_class_2': 0.5330309372162841}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:38,080] Trial 1991 finished with value: 0.8877603432323976 and parameters: {'weight_lgbm_class_0': 0.9734210171698722, 'weight_lgbm_class_1': 0.9837641151793115, 'weight_lgbm_class_2': 0.37270558572194346, 'weight_xgb_class_0': 0.048425814273478446, 'weight_xgb_class_1': 0.7183369529187519, 'weight_xgb_class_2': 0.4329889026236781}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:38,154] Trial 1993 finished with value: 0.9495738147261233 and parameters: {'weight_lgbm_class_0': 0.0661271113437518, 'weight_lgbm_class_1': 0.9562948630654005, 'weight_lgbm_class_2': 0.3760455595119454, 'weight_xgb_class_0': 0.0472428374118851, 'weight_xgb_class_1': 0.7211230579247966, 'weight_xgb_class_2': 0.5251701216373754}. Best is trial 1561 with value: 0.9498642565074636.

Best trial: 1999. Best value: 0.949868: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2000/2000 [01:06<00:00, 29.91it/s]

[I 2026-07-05 15:32:38,157] Trial 1992 finished with value: 0.949617227394261 and parameters: {'weight_lgbm_class_0': 0.06427147119725747, 'weight_lgbm_class_1': 0.9998942768526572, 'weight_lgbm_class_2': 0.37345987900618954, 'weight_xgb_class_0': 0.045678950671587434, 'weight_xgb_class_1': 0.720311071216761, 'weight_xgb_class_2': 0.5254212928468864}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:38,164] Trial 1994 finished with value: 0.9498297873725008 and parameters: {'weight_lgbm_class_0': 0.06698794726248766, 'weight_lgbm_class_1': 0.9504744399978441, 'weight_lgbm_class_2': 0.48251586013750225, 'weight_xgb_class_0': 0.0463661646126676, 'weight_xgb_class_1': 0.7188006593590205, 'weight_xgb_class_2': 0.5266348837133208}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:38,203] Trial 1995 finished with value: 0.947580354056648 and parameters: {'weight_lgbm_class_0': 0.15442576812301986, 'weight_lgbm_class_1': 0.95511182336681, 'weight_lgbm_class_2': 0.37225956899095575, 'weight_xgb_class_0': 0.04242816561868608, 'weight_xgb_class_1': 0.7214685350082835, 'weight_xgb_class_2': 0.5385896724967328}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:38,217] Trial 1996 finished with value: 0.9495812769216873 and parameters: {'weight_lgbm_class_0': 0.06709222639345595, 'weight_lgbm_class_1': 0.9543359363820344, 'weight_lgbm_class_2': 0.37528469776858875, 'weight_xgb_class_0': 0.046456637789995134, 'weight_xgb_class_1': 0.7205859291771766, 'weight_xgb_class_2': 0.5278440873358253}. Best is trial 1561 with value: 0.9498642565074636.
[I 2026-07-05 15:32:38,222] Trial 1997 finished with value: 0.9498649863229813 and parameters: {'weight_lgbm_class_0': 0.06727443379171509, 'weight_lgbm_class_1': 0.9537086380192191, 'weight_lgbm_class_2': 0.3725360271250441, 'weight_xgb_class_0': 0.033927250299197034, 'weight_xgb_class_1': 0.6859434361077456, 'weight_xgb_class_2': 0.5263970838608527}. Best is trial 1997 with value: 0.9498649863229813.
[I 2026-07-05 15:32:38,236] Trial 1998 finished with value: 0.9498236864968431 and parameters: {'weight_lgbm_class_0': 0.06682533884513019, 'weight_lgbm_class_1': 0.9536975897439005, 'weight_lgbm_class_2': 0.38061411993285155, 'weight_xgb_class_0': 0.03667530671579866, 'weight_xgb_class_1': 0.6847672666698874, 'weight_xgb_class_2': 0.5266769434768946}. Best is trial 1997 with value: 0.9498649863229813.
[I 2026-07-05 15:32:38,259] Trial 1999 finished with value: 0.9498675923093853 and parameters: {'weight_lgbm_class_0': 0.06561079381700607, 'weight_lgbm_class_1': 0.9500944524977034, 'weight_lgbm_class_2': 0.37126475829750977, 'weight_xgb_class_0': 0.03475822835888954, 'weight_xgb_class_1': 0.688406618264081, 'weight_xgb_class_2': 0.5278760091827734}. Best is trial 1999 with value: 0.9498675923093853.

Best trial score:
0.9498675923093853

Best params:
{'weight_lgbm_class_0': 0.06561079381700607, 'weight_lgbm_class_1': 0.9500944524977034, 'weight_lgbm_class_2': 0.37126475829750977, 'weight_xgb_class_0': 0.03475822835888954, 'weight_xgb_class_1': 0.688406618264081, 'weight_xgb_class_2': 0.5278760091827734}

In [10]:
best_params = study.best_params

w_lgbm = np.array([best_params['weight_lgbm_class_0'], best_params['weight_lgbm_class_1'], best_params['weight_lgbm_class_2']])
w_xgb  = np.array([best_params['weight_xgb_class_0'],  best_params['weight_xgb_class_1'],  best_params['weight_xgb_class_2']])
# w_cat  = np.array([best_params['weight_cat_class_0'],  best_params['weight_cat_class_1'],  best_params['weight_cat_class_2']])

proba_lgbm_test = X_test[['lgbm_0', 'lgbm_1', 'lgbm_2']].to_numpy()
proba_xgb_test  = X_test[['xgb_0', 'xgb_1', 'xgb_2']].to_numpy()
# proba_cat_test  = X_test[['cat_0', 'cat_1', 'cat_2']].to_numpy()

blend_proba_test = (proba_lgbm_test * w_lgbm) + (proba_xgb_test * w_xgb) # + (proba_cat_test * w_cat)

pred = np.argmax(blend_proba_test, axis=1)

In [11]:
sub_labels = label_encoder.inverse_transform(pred)

In [12]:
np.unique(pred)

array([0, 1, 2])

# Submission

In [13]:
submission = pd.read_csv('../data/submission/sample_submission.csv')
submission['health_condition'] = sub_labels

submission.to_csv('../data/submission/submission_from_5.3.0_xgboost_lightgbm_submission.csv', index=False)

In [14]:
submission.head()

       id health_condition
0  690088        unhealthy
1  690089        unhealthy
2  690090          at-risk
3  690091          at-risk
4  690092        unhealthy