# Imports

In [1]:
import optuna
import pickle

import numpy as np
import pandas as pd

from tqdm import tqdm

from sklearn.metrics import balanced_accuracy_score
from sklearn.model_selection import StratifiedKFold, cross_val_predict

/home/junior/Documentos/GitHub/kaggle-competition-predicting-student-health/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Utils

In [2]:
def load_pickle(file_path):
    with open(file_path, 'rb') as file:
        return pickle.load(file)

# Loading Datasets

In [4]:
X_train = pd.read_parquet('../data/processed/X_train_stacking_layer_one_model_60_trials_data_type_feat_eng_target_encoding.parquet')
y_train = pd.read_parquet('../data/interim/y_train.parquet')

X_test = pd.read_parquet('../data/processed/X_test_stacking_layer_one_model_60_trials_data_type_feat_eng_target_encoding.parquet')

In [5]:
X_train.head()

     lgbm_0    lgbm_1    lgbm_2     xgb_0     xgb_1     xgb_2
0  0.001638  0.000283  0.998079  0.001796  0.000363  0.997841
1  0.996015  0.000339  0.003646  0.997132  0.000288  0.002580
2  0.009099  0.001175  0.989726  0.005254  0.000682  0.994064
3  0.003855  0.002145  0.994000  0.004080  0.001686  0.994234
4  0.995730  0.000018  0.004252  0.993613  0.000010  0.006377

In [6]:
X_test.head()

     lgbm_0    lgbm_1    lgbm_2     xgb_0     xgb_1     xgb_2
0  0.013297  0.004871  0.981832  0.011730  0.004806  0.983465
1  0.407736  0.001829  0.590435  0.492656  0.003306  0.504038
2  0.998801  0.001053  0.000147  0.998502  0.001166  0.000333
3  0.976600  0.000013  0.023387  0.988312  0.000014  0.011675
4  0.004873  0.002234  0.992892  0.007801  0.002434  0.989766

# Machine Learning

In [7]:
label_encoder = load_pickle('../artifacts/label_encoder.pkl')

In [8]:
def objective(trial, X, y):

    w0 = trial.suggest_float('weight_class_0', 0.001, 10.0, log=True)
    w1 = trial.suggest_float('weight_class_1', 0.001, 10.0, log=True)
    w2 = trial.suggest_float('weight_class_2', 0.001, 10.0, log=True)
    weights = np.array([w0, w1, w2])

    proba = X.loc[:, ['xgb_0', 'xgb_1', 'xgb_2']].to_numpy()
    
    weighted_probas = proba * weights
    pred = np.argmax(weighted_probas, axis=1)
    
    score = balanced_accuracy_score(y, pred)

    return score


study = optuna.create_study(
    direction="maximize", 
    sampler=optuna.samplers.TPESampler(seed=42), 
    pruner=optuna.pruners.MedianPruner(n_warmup_steps=2)
)

study.optimize(
    lambda trial: objective(trial, X_train, y_train.health_condition), 
    n_trials=500, 
    n_jobs=-1, 
    show_progress_bar=True
)

print("\nBest trial score:")
print(study.best_trial.value)

print("\nBest params:")
print(study.best_trial.params)

[I 2026-07-13 11:37:23,153] A new study created in memory with name: no-name-bfa5ee06-0a4a-4dd6-ae0b-ef9cf94d8480

[I 2026-07-13 11:37:23,303] Trial 0 finished with value: 0.8144581878444114 and parameters: {'weight_class_0': 7.043056947794508, 'weight_class_1': 0.6272229742606508, 'weight_class_2': 0.35468969785009963}. Best is trial 0 with value: 0.8144581878444114.
[I 2026-07-13 11:37:23,314] Trial 10 finished with value: 0.7180299036603275 and parameters: {'weight_class_0': 0.011671034164083272, 'weight_class_1': 3.602517705285598, 'weight_class_2': 0.004695408267093219}. Best is trial 0 with value: 0.8144581878444114.
[I 2026-07-13 11:37:23,315] Trial 11 finished with value: 0.9208543774446841 and parameters: {'weight_class_0': 0.27949725923119, 'weight_class_1': 8.271373223848721, 'weight_class_2': 0.3835593955355141}. Best is trial 11 with value: 0.9208543774446841.
[I 2026-07-13 11:37:23,319] Trial 8 finished with value: 0.8788120901142978 and parameters: {'weight_class_0': 0.09554163721988959, 'weight_class_1': 0.013022457965217879, 'weight_class_2': 1.514545433209645}. Best is trial 11 with value: 0.9208543774446841.
[I 2026-07-13 11:37:23,327] Trial 3 finished with value: 0.41237632788591044 and parameters: {'weight_class_0': 3.075079695145122, 'weight_class_1': 0.00308818658854155, 'weight_class_2': 0.006756488582136371}. Best is trial 11 with value: 0.9208543774446841.
[I 2026-07-13 11:37:23,333] Trial 4 finished with value: 0.8653644695422141 and parameters: {'weight_class_0': 0.0023702157091828355, 'weight_class_1': 0.04154750950882375, 'weight_class_2': 0.8562283881749835}. Best is trial 11 with value: 0.9208543774446841.
[I 2026-07-13 11:37:23,337] Trial 2 finished with value: 0.9439309120027916 and parameters: {'weight_class_0': 0.022521114618990538, 'weight_class_1': 0.1262932213755625, 'weight_class_2': 1.3412268728939627}. Best is trial 2 with value: 0.9439309120027916.
[I 2026-07-13 11:37:23,343] Trial 1 finished with value: 0.7187287778423858 and parameters: {'weight_class_0': 0.1571654369835205, 'weight_class_1': 5.880839481612272, 'weight_class_2': 0.0023965456244731714}. Best is trial 2 with value: 0.9439309120027916.
[I 2026-07-13 11:37:23,348] Trial 6 finished with value: 0.9262516791622252 and parameters: {'weight_class_0': 0.016422072099134963, 'weight_class_1': 0.1897572302400542, 'weight_class_2': 2.862867396527648}. Best is trial 2 with value: 0.9439309120027916.
[I 2026-07-13 11:37:23,349] Trial 7 finished with value: 0.6667521876146703 and parameters: {'weight_class_0': 7.12527221912577, 'weight_class_1': 0.3859179922558972, 'weight_class_2': 0.019805811363119753}. Best is trial 2 with value: 0.9439309120027916.
[I 2026-07-13 11:37:23,350] Trial 9 finished with value: 0.898748978763151 and parameters: {'weight_class_0': 0.985364369666559, 'weight_class_1': 1.5507121791016252, 'weight_class_2': 1.2638418455268605}. Best is trial 2 with value: 0.9439309120027916.
[I 2026-07-13 11:37:23,351] Trial 5 finished with value: 0.5294653110550244 and parameters: {'weight_class_0': 0.005826853048922974, 'weight_class_1': 4.333086566726474, 'weight_class_2': 0.0017960777490560497}. Best is trial 2 with value: 0.9439309120027916.
[I 2026-07-13 11:37:23,464] Trial 13 finished with value: 0.8912071048535438 and parameters: {'weight_class_0': 1.3945926716416985, 'weight_class_1': 3.1110198688895534, 'weight_class_2': 1.0349833886671085}. Best is trial 2 with value: 0.9439309120027916.

Best trial: 25. Best value: 0.946901:   5%|██████▊                                                                                                                                | 25/500 [00:00<00:09, 50.92it/s]

[I 2026-07-13 11:37:23,466] Trial 12 finished with value: 0.8746926235779663 and parameters: {'weight_class_0': 0.19783412168013723, 'weight_class_1': 0.6749289198542965, 'weight_class_2': 0.005805075958735924}. Best is trial 2 with value: 0.9439309120027916.
[I 2026-07-13 11:37:23,476] Trial 14 finished with value: 0.8193317456280051 and parameters: {'weight_class_0': 0.021770723563765665, 'weight_class_1': 0.08947855502256837, 'weight_class_2': 8.860942476409798}. Best is trial 2 with value: 0.9439309120027916.
[I 2026-07-13 11:37:23,497] Trial 15 finished with value: 0.8714293397769889 and parameters: {'weight_class_0': 0.02373506277918494, 'weight_class_1': 0.10408606896787156, 'weight_class_2': 6.8291460926901895}. Best is trial 2 with value: 0.9439309120027916.
[I 2026-07-13 11:37:23,518] Trial 16 finished with value: 0.8638562271960214 and parameters: {'weight_class_0': 0.026815640375531833, 'weight_class_1': 0.13793876046235437, 'weight_class_2': 8.488176605661659}. Best is trial 2 with value: 0.9439309120027916.
[I 2026-07-13 11:37:23,528] Trial 17 finished with value: 0.8687468095208146 and parameters: {'weight_class_0': 0.024706734260046534, 'weight_class_1': 0.11079079160947611, 'weight_class_2': 7.297991189176215}. Best is trial 2 with value: 0.9439309120027916.
[I 2026-07-13 11:37:23,531] Trial 18 finished with value: 0.8306348408064154 and parameters: {'weight_class_0': 0.024986706871710503, 'weight_class_1': 0.09793498513249936, 'weight_class_2': 9.376515455442448}. Best is trial 2 with value: 0.9439309120027916.
[I 2026-07-13 11:37:23,544] Trial 19 finished with value: 0.8448636956884039 and parameters: {'weight_class_0': 0.02743549203623447, 'weight_class_1': 0.14303504537109157, 'weight_class_2': 9.95826501580739}. Best is trial 2 with value: 0.9439309120027916.
[I 2026-07-13 11:37:23,578] Trial 21 finished with value: 0.8749196621032603 and parameters: {'weight_class_0': 0.03300903396730172, 'weight_class_1': 0.10144653623855845, 'weight_class_2': 8.403311146674403}. Best is trial 2 with value: 0.9439309120027916.
[I 2026-07-13 11:37:23,587] Trial 20 finished with value: 0.8875944012031672 and parameters: {'weight_class_0': 0.02605068843747733, 'weight_class_1': 0.17870443547366135, 'weight_class_2': 7.101281551988582}. Best is trial 2 with value: 0.9439309120027916.
[I 2026-07-13 11:37:23,610] Trial 22 finished with value: 0.8585285579015937 and parameters: {'weight_class_0': 0.028775970502970104, 'weight_class_1': 0.07924893714257229, 'weight_class_2': 8.1328422704944}. Best is trial 2 with value: 0.9439309120027916.
[I 2026-07-13 11:37:23,625] Trial 23 finished with value: 0.9275500450044682 and parameters: {'weight_class_0': 0.03947250014308978, 'weight_class_1': 0.11948097374218024, 'weight_class_2': 4.647951134401741}. Best is trial 2 with value: 0.9439309120027916.
[I 2026-07-13 11:37:23,638] Trial 24 finished with value: 0.9453559159251707 and parameters: {'weight_class_0': 0.0018378971005977996, 'weight_class_1': 0.01609332284347973, 'weight_class_2': 0.1048970180586496}. Best is trial 24 with value: 0.9453559159251707.
[I 2026-07-13 11:37:23,664] Trial 25 finished with value: 0.9469005485280201 and parameters: {'weight_class_0': 0.0021368941040420483, 'weight_class_1': 0.016695330815383696, 'weight_class_2': 0.06493435092946263}. Best is trial 25 with value: 0.9469005485280201.

[I 2026-07-13 11:37:23,683] Trial 26 finished with value: 0.944674757455887 and parameters: {'weight_class_0': 0.002009560950718271, 'weight_class_1': 0.01107019874110776, 'weight_class_2': 0.0932621750654652}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:23,696] Trial 27 finished with value: 0.9456594329812112 and parameters: {'weight_class_0': 0.0014044991871407242, 'weight_class_1': 0.0147642734003822, 'weight_class_2': 0.07989904924331862}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:23,706] Trial 28 finished with value: 0.9400099105066227 and parameters: {'weight_class_0': 0.006284387376577522, 'weight_class_1': 0.016764447844980608, 'weight_class_2': 0.07151843293735832}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:23,727] Trial 29 finished with value: 0.8181180391048923 and parameters: {'weight_class_0': 0.4362267970132112, 'weight_class_1': 0.017856856769830173, 'weight_class_2': 0.1327790521838177}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:23,744] Trial 30 finished with value: 0.9397884965973308 and parameters: {'weight_class_0': 0.001056852368089553, 'weight_class_1': 0.02184505402946847, 'weight_class_2': 0.1221092891257786}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:23,767] Trial 31 finished with value: 0.8188653525622033 and parameters: {'weight_class_0': 0.41303459313952073, 'weight_class_1': 0.01784116118197839, 'weight_class_2': 0.137811254785089}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:23,781] Trial 32 finished with value: 0.9442700191052696 and parameters: {'weight_class_0': 0.0012628176703053105, 'weight_class_1': 0.017243151002289663, 'weight_class_2': 0.09829491418672676}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:23,799] Trial 33 finished with value: 0.9447345126732029 and parameters: {'weight_class_0': 0.0013194794858470942, 'weight_class_1': 0.019664271651105417, 'weight_class_2': 0.09783325502013364}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:23,816] Trial 34 finished with value: 0.9468244580409904 and parameters: {'weight_class_0': 0.001025029925492463, 'weight_class_1': 0.013889384683526445, 'weight_class_2': 0.04626398411937871}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:23,842] Trial 35 finished with value: 0.9453830988497098 and parameters: {'weight_class_0': 0.0011251289674389265, 'weight_class_1': 0.009417086114025293, 'weight_class_2': 0.06168995456441282}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:23,855] Trial 36 finished with value: 0.9227113575849403 and parameters: {'weight_class_0': 0.0011318679307353275, 'weight_class_1': 0.001848935884797589, 'weight_class_2': 0.08410833852798964}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:23,868] Trial 37 finished with value: 0.9407212322808869 and parameters: {'weight_class_0': 0.0010313489802687048, 'weight_class_1': 0.003184088344556581, 'weight_class_2': 0.03139274247183117}. Best is trial 25 with value: 0.9469005485280201.

Best trial: 25. Best value: 0.946901:  10%|█████████████▌                                                                                                                         | 50/500 [00:00<00:08, 55.63it/s]

[I 2026-07-13 11:37:23,887] Trial 38 finished with value: 0.9437588569086025 and parameters: {'weight_class_0': 0.001261578505602896, 'weight_class_1': 0.005069076359329183, 'weight_class_2': 0.03569330178183595}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:23,922] Trial 39 finished with value: 0.9446041118507322 and parameters: {'weight_class_0': 0.0012077043980526587, 'weight_class_1': 0.005552605615773216, 'weight_class_2': 0.037236811319155565}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:23,923] Trial 40 finished with value: 0.9394664361358784 and parameters: {'weight_class_0': 0.0011932246612635577, 'weight_class_1': 0.003431232277286238, 'weight_class_2': 0.040395808696750496}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:23,938] Trial 41 finished with value: 0.9347851089604508 and parameters: {'weight_class_0': 0.002663555255634126, 'weight_class_1': 0.005405892096680334, 'weight_class_2': 0.03938417627026935}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:23,957] Trial 42 finished with value: 0.9321687942242839 and parameters: {'weight_class_0': 0.0022687080584787482, 'weight_class_1': 0.004065544698008504, 'weight_class_2': 0.029227381939595825}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:23,985] Trial 44 finished with value: 0.9249604480456372 and parameters: {'weight_class_0': 0.0034861638691373507, 'weight_class_1': 0.004720574707925935, 'weight_class_2': 0.03589031337404564}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:23,997] Trial 43 finished with value: 0.9199855222402201 and parameters: {'weight_class_0': 0.003924134504767728, 'weight_class_1': 0.00447719748450185, 'weight_class_2': 0.033625893620323394}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:24,009] Trial 46 finished with value: 0.9386380803825304 and parameters: {'weight_class_0': 0.003718500798762774, 'weight_class_1': 0.009332561349961343, 'weight_class_2': 0.03110339987114526}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:24,013] Trial 45 finished with value: 0.9301320342278498 and parameters: {'weight_class_0': 0.003818658360165513, 'weight_class_1': 0.006409850226840939, 'weight_class_2': 0.02995854546347398}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:24,058] Trial 47 finished with value: 0.922565339342309 and parameters: {'weight_class_0': 0.0038493754681342605, 'weight_class_1': 0.006354241058246516, 'weight_class_2': 0.29393952720781535}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:24,059] Trial 48 finished with value: 0.9250590052881402 and parameters: {'weight_class_0': 0.0036221007156294932, 'weight_class_1': 0.00636825625985292, 'weight_class_2': 0.26164199597857274}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:24,060] Trial 49 finished with value: 0.9449657604121061 and parameters: {'weight_class_0': 0.0035899169123729917, 'weight_class_1': 0.04442308651474406, 'weight_class_2': 0.24515699923842074}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:24,087] Trial 50 finished with value: 0.9448845417535194 and parameters: {'weight_class_0': 0.0040393825849266325, 'weight_class_1': 0.03553126046858397, 'weight_class_2': 0.2549467802583932}. Best is trial 25 with value: 0.9469005485280201.

Best trial: 25. Best value: 0.946901:  12%|████████████████▍                                                                                                                      | 61/500 [00:01<00:07, 56.78it/s]

[I 2026-07-13 11:37:24,104] Trial 51 finished with value: 0.9430384724379971 and parameters: {'weight_class_0': 0.004244664742609922, 'weight_class_1': 0.03462209527975944, 'weight_class_2': 0.01422239686953718}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:24,135] Trial 52 finished with value: 0.9365611032318659 and parameters: {'weight_class_0': 0.005002684616216369, 'weight_class_1': 0.03395664188208593, 'weight_class_2': 0.011957864796310518}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:24,140] Trial 53 finished with value: 0.9166965396150178 and parameters: {'weight_class_0': 0.008535154368419742, 'weight_class_1': 0.03552974407378462, 'weight_class_2': 0.011470831282590754}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:24,177] Trial 54 finished with value: 0.9454830754749275 and parameters: {'weight_class_0': 0.0083733209020381, 'weight_class_1': 0.043006834523412966, 'weight_class_2': 0.24529080448434823}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:24,193] Trial 55 finished with value: 0.9435213891271695 and parameters: {'weight_class_0': 0.00802748199589297, 'weight_class_1': 0.03278035226895597, 'weight_class_2': 0.2717362306766891}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:24,204] Trial 56 finished with value: 0.9223560208430723 and parameters: {'weight_class_0': 0.008680623944158779, 'weight_class_1': 0.03422653604433797, 'weight_class_2': 0.014146957530332476}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:24,231] Trial 58 finished with value: 0.9324666463318797 and parameters: {'weight_class_0': 0.006066406810659818, 'weight_class_1': 0.03637605289963867, 'weight_class_2': 0.012584800927466602}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:24,233] Trial 57 finished with value: 0.9223181480138131 and parameters: {'weight_class_0': 0.00938791904987117, 'weight_class_1': 0.03646952189498549, 'weight_class_2': 0.015342787120681557}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:24,242] Trial 59 finished with value: 0.9425315001451268 and parameters: {'weight_class_0': 0.00806378310626553, 'weight_class_1': 0.053018387443958925, 'weight_class_2': 0.6608049628530356}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:24,262] Trial 60 finished with value: 0.9433441078289498 and parameters: {'weight_class_0': 0.007700880890883245, 'weight_class_1': 0.05218540830205836, 'weight_class_2': 0.5754446764474808}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:24,267] Trial 61 finished with value: 0.946765414488138 and parameters: {'weight_class_0': 0.009399999580307324, 'weight_class_1': 0.05713315185278278, 'weight_class_2': 0.05771518008424584}. Best is trial 25 with value: 0.9469005485280201.

[I 2026-07-13 11:37:24,291] Trial 62 finished with value: 0.916962537651114 and parameters: {'weight_class_0': 0.0018162799485187402, 'weight_class_1': 0.0019619511384889213, 'weight_class_2': 0.05816657524721198}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:24,307] Trial 63 finished with value: 0.9093829722246146 and parameters: {'weight_class_0': 0.0018863629365519353, 'weight_class_1': 0.0690798828990876, 'weight_class_2': 0.4398779614174905}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:24,350] Trial 64 finished with value: 0.8925109649364864 and parameters: {'weight_class_0': 0.00177673528023793, 'weight_class_1': 0.062418384318911925, 'weight_class_2': 0.505027892446818}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:24,354] Trial 65 finished with value: 0.866025261640408 and parameters: {'weight_class_0': 0.0018866309935825015, 'weight_class_1': 0.062323079417989875, 'weight_class_2': 0.6853080508206941}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:24,373] Trial 66 finished with value: 0.805993907613941 and parameters: {'weight_class_0': 0.0019383151497392062, 'weight_class_1': 0.00190533130084141, 'weight_class_2': 0.578941701346828}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:24,387] Trial 67 finished with value: 0.9450930136446858 and parameters: {'weight_class_0': 0.0017904438095962627, 'weight_class_1': 0.009174561413255072, 'weight_class_2': 0.06123126097408475}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:24,410] Trial 68 finished with value: 0.9453823677571501 and parameters: {'weight_class_0': 0.0018392991645833873, 'weight_class_1': 0.009405323164702153, 'weight_class_2': 0.05635311190361354}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:24,419] Trial 69 finished with value: 0.9454728066432819 and parameters: {'weight_class_0': 0.0019478555154559556, 'weight_class_1': 0.010051801083512803, 'weight_class_2': 0.05811859271032544}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:24,434] Trial 70 finished with value: 0.9451851104549212 and parameters: {'weight_class_0': 0.0017326415847381494, 'weight_class_1': 0.009478885468449588, 'weight_class_2': 0.06468431135798701}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:24,465] Trial 71 finished with value: 0.9071658766646408 and parameters: {'weight_class_0': 0.012867749188612622, 'weight_class_1': 0.008911501954630596, 'weight_class_2': 0.17909547280961632}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:24,468] Trial 72 finished with value: 0.9036042540881043 and parameters: {'weight_class_0': 0.015358989329118663, 'weight_class_1': 0.008697467520861814, 'weight_class_2': 0.1703268554155869}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:24,493] Trial 73 finished with value: 0.8552134501925313 and parameters: {'weight_class_0': 0.04650160760714187, 'weight_class_1': 0.0094382136678674, 'weight_class_2': 0.05874240939753946}. Best is trial 25 with value: 0.9469005485280201.

Best trial: 75. Best value: 0.949471:  17%|███████████████████████▏                                                                                                               | 86/500 [00:01<00:07, 57.51it/s]

[I 2026-07-13 11:37:24,514] Trial 74 finished with value: 0.9061003450415841 and parameters: {'weight_class_0': 0.014882373140422745, 'weight_class_1': 0.009789440103397438, 'weight_class_2': 0.1779964336449121}. Best is trial 25 with value: 0.9469005485280201.
[I 2026-07-13 11:37:24,523] Trial 75 finished with value: 0.9494713256896755 and parameters: {'weight_class_0': 0.015055085791281383, 'weight_class_1': 0.3212668958008887, 'weight_class_2': 0.1789838759887953}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:24,544] Trial 76 finished with value: 0.6772141911670442 and parameters: {'weight_class_0': 4.077095617586192, 'weight_class_1': 0.024575356500738037, 'weight_class_2': 0.058546058401246805}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:24,561] Trial 77 finished with value: 0.9286175988264032 and parameters: {'weight_class_0': 0.01576448381792152, 'weight_class_1': 0.024519080948400766, 'weight_class_2': 0.15893951259964065}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:24,576] Trial 78 finished with value: 0.9098938113665266 and parameters: {'weight_class_0': 0.016189572313177525, 'weight_class_1': 0.012548472268007364, 'weight_class_2': 0.18054924393495053}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:24,601] Trial 79 finished with value: 0.9464558097471905 and parameters: {'weight_class_0': 0.0026790554697753094, 'weight_class_1': 0.014214799314175486, 'weight_class_2': 0.051395257200641836}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:24,612] Trial 80 finished with value: 0.7577382106347739 and parameters: {'weight_class_0': 3.6506830233793908, 'weight_class_1': 0.2530750313145445, 'weight_class_2': 0.023212533695422442}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:24,630] Trial 81 finished with value: 0.8498979197012736 and parameters: {'weight_class_0': 0.07195305528241425, 'weight_class_1': 0.023823159147428677, 'weight_class_2': 0.057899320122480696}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:24,646] Trial 82 finished with value: 0.9488480613069806 and parameters: {'weight_class_0': 0.002629915270248864, 'weight_class_1': 0.023238872106518274, 'weight_class_2': 0.02165153752696215}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:24,665] Trial 83 finished with value: 0.8359839206480041 and parameters: {'weight_class_0': 0.0028072276540055284, 'weight_class_1': 0.4077729633306474, 'weight_class_2': 0.001146475528886602}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:24,685] Trial 85 finished with value: 0.9272901109209903 and parameters: {'weight_class_0': 0.0026773401444679626, 'weight_class_1': 0.3740521996586775, 'weight_class_2': 0.021337910080929216}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:24,703] Trial 84 finished with value: 0.8290191720474662 and parameters: {'weight_class_0': 0.08236611596939204, 'weight_class_1': 0.01562504875022202, 'weight_class_2': 0.019749341970066128}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:24,732] Trial 86 finished with value: 0.9361240084443958 and parameters: {'weight_class_0': 0.0028521687392797667, 'weight_class_1': 0.33423440707333835, 'weight_class_2': 0.045196430297371144}. Best is trial 75 with value: 0.9494713256896755.

Best trial: 75. Best value: 0.949471:  19%|██████████████████████████▏                                                                                                            | 97/500 [00:01<00:07, 54.60it/s]

[I 2026-07-13 11:37:24,749] Trial 87 finished with value: 0.9223648618495784 and parameters: {'weight_class_0': 0.0025716482156014644, 'weight_class_1': 0.390976077604366, 'weight_class_2': 0.019429609273731597}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:24,759] Trial 88 finished with value: 0.8504437501874648 and parameters: {'weight_class_0': 0.002658401358324452, 'weight_class_1': 0.9092339941920311, 'weight_class_2': 0.04448257642294297}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:24,793] Trial 89 finished with value: 0.8883494957571617 and parameters: {'weight_class_0': 0.0030358219618440148, 'weight_class_1': 0.7415607209459818, 'weight_class_2': 0.046869270986792326}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:24,796] Trial 90 finished with value: 0.7971988859031666 and parameters: {'weight_class_0': 0.0026771804801472817, 'weight_class_1': 1.2535232979676485, 'weight_class_2': 0.020273477815305786}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:24,838] Trial 91 finished with value: 0.794478790483005 and parameters: {'weight_class_0': 0.0027565334754573803, 'weight_class_1': 1.3056116331059628, 'weight_class_2': 0.019826712730168134}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:24,840] Trial 93 finished with value: 0.7132031905060048 and parameters: {'weight_class_0': 0.0014106640941406279, 'weight_class_1': 1.8659109496131532, 'weight_class_2': 0.07786604999916012}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:24,848] Trial 92 finished with value: 0.8108840098592228 and parameters: {'weight_class_0': 0.0027526769285274905, 'weight_class_1': 1.1799252339094612, 'weight_class_2': 0.0218968608587703}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:24,854] Trial 94 finished with value: 0.9453870486206863 and parameters: {'weight_class_0': 0.0014106810834236332, 'weight_class_1': 0.013653190360880061, 'weight_class_2': 0.08382534381463659}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:24,883] Trial 95 finished with value: 0.7632950624526756 and parameters: {'weight_class_0': 0.0014595964306750695, 'weight_class_1': 1.0611581592453658, 'weight_class_2': 0.12424059295913936}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:24,919] Trial 98 finished with value: 0.9384691035455838 and parameters: {'weight_class_0': 0.0049826090564809074, 'weight_class_1': 0.012357688186853427, 'weight_class_2': 0.07870844555326446}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:24,932] Trial 97 finished with value: 0.701431668518323 and parameters: {'weight_class_0': 0.0014646019564367374, 'weight_class_1': 2.3824242588725237, 'weight_class_2': 0.08234281746638195}. Best is trial 75 with value: 0.9494713256896755.

[I 2026-07-13 11:37:24,939] Trial 96 finished with value: 0.9455962838170535 and parameters: {'weight_class_0': 0.0014511130413690492, 'weight_class_1': 0.01445541779912674, 'weight_class_2': 0.08169061369307903}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:24,947] Trial 99 finished with value: 0.943377501821328 and parameters: {'weight_class_0': 0.0014530972581789953, 'weight_class_1': 0.013461677589921702, 'weight_class_2': 0.11799984907263592}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:24,976] Trial 100 finished with value: 0.9448755490891497 and parameters: {'weight_class_0': 0.001451596760821838, 'weight_class_1': 0.012407486617999302, 'weight_class_2': 0.09081569877614173}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:24,989] Trial 101 finished with value: 0.9394732707053333 and parameters: {'weight_class_0': 0.005613528477480234, 'weight_class_1': 0.015267121564211943, 'weight_class_2': 0.1207016857416149}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:25,011] Trial 103 finished with value: 0.9438456866131287 and parameters: {'weight_class_0': 0.0014958323175361605, 'weight_class_1': 0.013610651647336224, 'weight_class_2': 0.11360864766330224}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:25,026] Trial 102 finished with value: 0.9429477419237361 and parameters: {'weight_class_0': 0.0014203384276710452, 'weight_class_1': 0.012154434074437523, 'weight_class_2': 0.1186607360475747}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:25,057] Trial 104 finished with value: 0.93853886579166 and parameters: {'weight_class_0': 0.005269839326920217, 'weight_class_1': 0.013177507298362822, 'weight_class_2': 0.0865655273105423}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:25,063] Trial 105 finished with value: 0.9381252245251681 and parameters: {'weight_class_0': 0.005469959901924887, 'weight_class_1': 0.013575844762587577, 'weight_class_2': 0.10194068652433204}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:25,090] Trial 106 finished with value: 0.9139113724267914 and parameters: {'weight_class_0': 0.006765163236906292, 'weight_class_1': 0.00722646329602535, 'weight_class_2': 0.02627982525000109}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:25,095] Trial 107 finished with value: 0.9429009487765155 and parameters: {'weight_class_0': 0.004722543432198187, 'weight_class_1': 0.029388887808776333, 'weight_class_2': 0.3608016649984107}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:25,141] Trial 108 finished with value: 0.9201221321974251 and parameters: {'weight_class_0': 0.0010502285102998831, 'weight_class_1': 0.028281362033291464, 'weight_class_2': 0.20948227728513888}. Best is trial 75 with value: 0.9494713256896755.

Best trial: 75. Best value: 0.949471:  24%|████████████████████████████████▏                                                                                                     | 120/500 [00:02<00:06, 55.05it/s]

[I 2026-07-13 11:37:25,144] Trial 109 finished with value: 0.9417030277148241 and parameters: {'weight_class_0': 0.0010159901748065616, 'weight_class_1': 0.018571688668459603, 'weight_class_2': 0.10368103899507962}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:25,162] Trial 110 finished with value: 0.9264035926655243 and parameters: {'weight_class_0': 0.019673990105561187, 'weight_class_1': 0.028119372913524534, 'weight_class_2': 0.3150888688838892}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:25,178] Trial 111 finished with value: 0.9472339862263311 and parameters: {'weight_class_0': 0.0010023606754400187, 'weight_class_1': 0.02787849430238821, 'weight_class_2': 0.0454083339503688}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:25,205] Trial 112 finished with value: 0.8859794227075001 and parameters: {'weight_class_0': 0.02145551476979119, 'weight_class_1': 0.02094566332211395, 'weight_class_2': 0.02801228199793382}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:25,207] Trial 113 finished with value: 0.9177923530736006 and parameters: {'weight_class_0': 0.01979703364217437, 'weight_class_1': 0.0207671363598626, 'weight_class_2': 0.2150968039050944}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:25,249] Trial 115 finished with value: 0.9116059771548319 and parameters: {'weight_class_0': 0.00100403548817326, 'weight_class_1': 0.01917251192759666, 'weight_class_2': 0.22680666636950758}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:25,251] Trial 114 finished with value: 0.9020989247339477 and parameters: {'weight_class_0': 0.01943876820998193, 'weight_class_1': 0.02059843202646846, 'weight_class_2': 1.8396978233243548}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:25,277] Trial 116 finished with value: 0.942518325311498 and parameters: {'weight_class_0': 0.0022592139374314627, 'weight_class_1': 0.02021967191957028, 'weight_class_2': 0.007235701403735921}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:25,297] Trial 117 finished with value: 0.883436584786824 and parameters: {'weight_class_0': 0.020636553876101325, 'weight_class_1': 0.04963905030958567, 'weight_class_2': 0.006531874222048422}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:25,305] Trial 118 finished with value: 0.9424945513800203 and parameters: {'weight_class_0': 0.002172804901603971, 'weight_class_1': 0.00744991067422676, 'weight_class_2': 0.04818627115745857}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:25,316] Trial 119 finished with value: 0.927444226821757 and parameters: {'weight_class_0': 0.011562073577116687, 'weight_class_1': 0.019963864165349912, 'weight_class_2': 0.04747272630317739}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:25,351] Trial 121 finished with value: 0.9285892130360986 and parameters: {'weight_class_0': 0.0022077979198908545, 'weight_class_1': 0.04613735762548793, 'weight_class_2': 0.003810816221115958}. Best is trial 75 with value: 0.9494713256896755.

Best trial: 75. Best value: 0.949471:  26%|███████████████████████████████████                                                                                                   | 131/500 [00:02<00:06, 54.32it/s]

[I 2026-07-13 11:37:25,369] Trial 120 finished with value: 0.9426017699547286 and parameters: {'weight_class_0': 0.01074525283108716, 'weight_class_1': 0.04371899765412133, 'weight_class_2': 0.05077040405263692}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:25,385] Trial 122 finished with value: 0.9331518003516047 and parameters: {'weight_class_0': 0.0022234773367713332, 'weight_class_1': 0.0449146529797975, 'weight_class_2': 0.004494130662368479}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:25,396] Trial 123 finished with value: 0.945153947328679 and parameters: {'weight_class_0': 0.009855110388025326, 'weight_class_1': 0.04925463355425518, 'weight_class_2': 0.05375176970587937}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:25,415] Trial 124 finished with value: 0.9490206489679446 and parameters: {'weight_class_0': 0.0023605987780190778, 'weight_class_1': 0.04887753297688665, 'weight_class_2': 0.04886269242231364}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:25,442] Trial 125 finished with value: 0.9488494538120271 and parameters: {'weight_class_0': 0.0021654346651138533, 'weight_class_1': 0.041712444310345, 'weight_class_2': 0.04824372549525138}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:25,453] Trial 127 finished with value: 0.9252696279128956 and parameters: {'weight_class_0': 0.011062834797904392, 'weight_class_1': 0.015720612631109344, 'weight_class_2': 0.07213642274159045}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:25,462] Trial 126 finished with value: 0.9437582360881294 and parameters: {'weight_class_0': 0.0021710676188739036, 'weight_class_1': 0.17124239650844567, 'weight_class_2': 0.0714539167932041}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:25,505] Trial 128 finished with value: 0.9440653158924869 and parameters: {'weight_class_0': 0.002208500415871665, 'weight_class_1': 0.17019997462621106, 'weight_class_2': 0.06986366730240635}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:25,515] Trial 129 finished with value: 0.9443384302348381 and parameters: {'weight_class_0': 0.0011686518960556996, 'weight_class_1': 0.007496998217000192, 'weight_class_2': 0.07027332673433594}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:25,527] Trial 130 finished with value: 0.9460522656650042 and parameters: {'weight_class_0': 0.0012339373115558634, 'weight_class_1': 0.015943458781158236, 'weight_class_2': 0.06662390325251147}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:25,552] Trial 131 finished with value: 0.9432146930334921 and parameters: {'weight_class_0': 0.0011561008791496016, 'weight_class_1': 0.08247789358116173, 'weight_class_2': 0.07133207300255659}. Best is trial 75 with value: 0.9494713256896755.

[I 2026-07-13 11:37:25,584] Trial 132 finished with value: 0.9460766445697218 and parameters: {'weight_class_0': 0.0012844781901349626, 'weight_class_1': 0.016252563405865197, 'weight_class_2': 0.06880314595351687}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:25,588] Trial 133 finished with value: 0.94566118476154 and parameters: {'weight_class_0': 0.0011843230475381088, 'weight_class_1': 0.07631086086095008, 'weight_class_2': 0.037402074246676964}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:25,603] Trial 134 finished with value: 0.9461751446749304 and parameters: {'weight_class_0': 0.0016191935158857153, 'weight_class_1': 0.0867764400730383, 'weight_class_2': 0.06844141396650048}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:25,611] Trial 135 finished with value: 0.6385182306275303 and parameters: {'weight_class_0': 0.0032640670704653972, 'weight_class_1': 7.601025727367741, 'weight_class_2': 0.035129254190419984}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:25,644] Trial 136 finished with value: 0.949409668225372 and parameters: {'weight_class_0': 0.0034125235991421298, 'weight_class_1': 0.08754191801351405, 'weight_class_2': 0.03845949526365474}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:25,649] Trial 137 finished with value: 0.9470790729205874 and parameters: {'weight_class_0': 0.0017388867279598324, 'weight_class_1': 0.09574318433817937, 'weight_class_2': 0.035627566270257024}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:25,697] Trial 138 finished with value: 0.9493472757130306 and parameters: {'weight_class_0': 0.00319673973534244, 'weight_class_1': 0.08238350821780013, 'weight_class_2': 0.03829413151943367}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:25,698] Trial 139 finished with value: 0.6490741508735186 and parameters: {'weight_class_0': 0.001703135637395141, 'weight_class_1': 5.591992620263336, 'weight_class_2': 0.03847524634879081}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:25,713] Trial 140 finished with value: 0.6661116493470085 and parameters: {'weight_class_0': 0.0032896272302846345, 'weight_class_1': 5.404738214357015, 'weight_class_2': 0.037535657040753824}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:25,743] Trial 141 finished with value: 0.9478104750555832 and parameters: {'weight_class_0': 0.0015847546782600161, 'weight_class_1': 0.06732828287391203, 'weight_class_2': 0.03882846030182152}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:25,752] Trial 142 finished with value: 0.94486354938676 and parameters: {'weight_class_0': 0.0016344128731834904, 'weight_class_1': 0.11992030040780552, 'weight_class_2': 0.03542382990403441}. Best is trial 75 with value: 0.9494713256896755.

[I 2026-07-13 11:37:25,778] Trial 143 finished with value: 0.9458582959216284 and parameters: {'weight_class_0': 0.001740671572232884, 'weight_class_1': 0.11483800041293694, 'weight_class_2': 0.03807527637909962}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:25,813] Trial 144 finished with value: 0.9471301838053106 and parameters: {'weight_class_0': 0.0017705572623190093, 'weight_class_1': 0.0921441982120404, 'weight_class_2': 0.041470712591765}. Best is trial 75 with value: 0.9494713256896755.
[I 2026-07-13 11:37:25,829] Trial 145 finished with value: 0.9495831298391959 and parameters: {'weight_class_0': 0.003388808853162133, 'weight_class_1': 0.06070519022146454, 'weight_class_2': 0.04231476323724335}. Best is trial 145 with value: 0.9495831298391959.
[I 2026-07-13 11:37:25,856] Trial 146 finished with value: 0.945237295703993 and parameters: {'weight_class_0': 0.0016872940517454766, 'weight_class_1': 0.11862023169812509, 'weight_class_2': 0.03867549134579251}. Best is trial 145 with value: 0.9495831298391959.
[I 2026-07-13 11:37:25,866] Trial 147 finished with value: 0.9486354236031286 and parameters: {'weight_class_0': 0.003436274599506103, 'weight_class_1': 0.12191238446042194, 'weight_class_2': 0.032262414499966835}. Best is trial 145 with value: 0.9495831298391959.
[I 2026-07-13 11:37:25,884] Trial 148 finished with value: 0.9440859895176619 and parameters: {'weight_class_0': 0.001624061815017027, 'weight_class_1': 0.13162074906297044, 'weight_class_2': 0.028079359888244976}. Best is trial 145 with value: 0.9495831298391959.
[I 2026-07-13 11:37:25,888] Trial 149 finished with value: 0.9484001250625975 and parameters: {'weight_class_0': 0.004013499871580597, 'weight_class_1': 0.09401595581654425, 'weight_class_2': 0.02714182024278627}. Best is trial 145 with value: 0.9495831298391959.
[I 2026-07-13 11:37:25,927] Trial 151 finished with value: 0.9486735008290887 and parameters: {'weight_class_0': 0.0031697052126968585, 'weight_class_1': 0.09385814831087416, 'weight_class_2': 0.025104669433756055}. Best is trial 145 with value: 0.9495831298391959.
[I 2026-07-13 11:37:25,935] Trial 150 finished with value: 0.9489124549417477 and parameters: {'weight_class_0': 0.003432242891611181, 'weight_class_1': 0.06757887702306976, 'weight_class_2': 0.02593877898145398}. Best is trial 145 with value: 0.9495831298391959.
[I 2026-07-13 11:37:25,947] Trial 152 finished with value: 0.948955075340106 and parameters: {'weight_class_0': 0.0034501153267606503, 'weight_class_1': 0.09171459306132164, 'weight_class_2': 0.02819526700471253}. Best is trial 145 with value: 0.9495831298391959.
[I 2026-07-13 11:37:25,969] Trial 153 finished with value: 0.9479506544358266 and parameters: {'weight_class_0': 0.004315912636201831, 'weight_class_1': 0.0958810527417488, 'weight_class_2': 0.026183900955201646}. Best is trial 145 with value: 0.9495831298391959.
[I 2026-07-13 11:37:25,985] Trial 154 finished with value: 0.9480657290778423 and parameters: {'weight_class_0': 0.004477685561959826, 'weight_class_1': 0.06463912146311727, 'weight_class_2': 0.027090772813021358}. Best is trial 145 with value: 0.9495831298391959.

Best trial: 145. Best value: 0.949583:  33%|████████████████████████████████████████████▏                                                                                        | 166/500 [00:03<00:06, 55.19it/s]

[I 2026-07-13 11:37:26,014] Trial 155 finished with value: 0.9454579815470859 and parameters: {'weight_class_0': 0.004134036526576516, 'weight_class_1': 0.06386710683160976, 'weight_class_2': 0.016469979059241826}. Best is trial 145 with value: 0.9495831298391959.
[I 2026-07-13 11:37:26,027] Trial 157 finished with value: 0.9428275086723783 and parameters: {'weight_class_0': 0.003861891726998571, 'weight_class_1': 0.22662796468589086, 'weight_class_2': 0.015740672744784526}. Best is trial 145 with value: 0.9495831298391959.
[I 2026-07-13 11:37:26,058] Trial 156 finished with value: 0.9444327351622993 and parameters: {'weight_class_0': 0.004661781001697367, 'weight_class_1': 0.10006226286191704, 'weight_class_2': 0.016892377467025748}. Best is trial 145 with value: 0.9495831298391959.
[I 2026-07-13 11:37:26,080] Trial 158 finished with value: 0.9476610719532413 and parameters: {'weight_class_0': 0.004408092373563653, 'weight_class_1': 0.1001396089205614, 'weight_class_2': 0.025416395192116206}. Best is trial 145 with value: 0.9495831298391959.
[I 2026-07-13 11:37:26,090] Trial 159 finished with value: 0.9478127107695209 and parameters: {'weight_class_0': 0.00427446379806759, 'weight_class_1': 0.09751164038811644, 'weight_class_2': 0.02523468386790127}. Best is trial 145 with value: 0.9495831298391959.
[I 2026-07-13 11:37:26,105] Trial 160 finished with value: 0.946967308703162 and parameters: {'weight_class_0': 0.003345482265951846, 'weight_class_1': 0.09644104860620255, 'weight_class_2': 0.01759819851643707}. Best is trial 145 with value: 0.9495831298391959.
[I 2026-07-13 11:37:26,113] Trial 161 finished with value: 0.9475354014643423 and parameters: {'weight_class_0': 0.004120785200268184, 'weight_class_1': 0.09426387433944804, 'weight_class_2': 0.023274659085216746}. Best is trial 145 with value: 0.9495831298391959.
[I 2026-07-13 11:37:26,137] Trial 162 finished with value: 0.9435758488862538 and parameters: {'weight_class_0': 0.0038497322812662757, 'weight_class_1': 0.21450518922423542, 'weight_class_2': 0.01652162464548452}. Best is trial 145 with value: 0.9495831298391959.
[I 2026-07-13 11:37:26,178] Trial 164 finished with value: 0.9476946408438837 and parameters: {'weight_class_0': 0.004435972843374179, 'weight_class_1': 0.07239563226895168, 'weight_class_2': 0.024957378379022233}. Best is trial 145 with value: 0.9495831298391959.
[I 2026-07-13 11:37:26,179] Trial 163 finished with value: 0.9458498836295752 and parameters: {'weight_class_0': 0.003920869984925259, 'weight_class_1': 0.06759612128230219, 'weight_class_2': 0.01620354479951142}. Best is trial 145 with value: 0.9495831298391959.
[I 2026-07-13 11:37:26,186] Trial 165 finished with value: 0.9372296412589671 and parameters: {'weight_class_0': 0.004437316175024663, 'weight_class_1': 0.07011679942502864, 'weight_class_2': 0.010411419006612525}. Best is trial 145 with value: 0.9495831298391959.
[I 2026-07-13 11:37:26,204] Trial 166 finished with value: 0.947903730502324 and parameters: {'weight_class_0': 0.004397882836374272, 'weight_class_1': 0.06767462883628711, 'weight_class_2': 0.025509988036256804}. Best is trial 145 with value: 0.9495831298391959.

[I 2026-07-13 11:37:26,222] Trial 167 finished with value: 0.9448050222958568 and parameters: {'weight_class_0': 0.006615584231358443, 'weight_class_1': 0.06983940860690477, 'weight_class_2': 0.024996972692649135}. Best is trial 145 with value: 0.9495831298391959.
[I 2026-07-13 11:37:26,245] Trial 168 finished with value: 0.9440752695653473 and parameters: {'weight_class_0': 0.006717615531184914, 'weight_class_1': 0.07306436208522098, 'weight_class_2': 0.02375930532157677}. Best is trial 145 with value: 0.9495831298391959.
[I 2026-07-13 11:37:26,266] Trial 169 finished with value: 0.9451195888213458 and parameters: {'weight_class_0': 0.006388890816617781, 'weight_class_1': 0.1509362200909356, 'weight_class_2': 0.025055600450781347}. Best is trial 145 with value: 0.9495831298391959.
[I 2026-07-13 11:37:26,281] Trial 171 finished with value: 0.9449126813933515 and parameters: {'weight_class_0': 0.006598432603645368, 'weight_class_1': 0.06838269294816043, 'weight_class_2': 0.025386366396538455}. Best is trial 145 with value: 0.9495831298391959.
[I 2026-07-13 11:37:26,289] Trial 170 finished with value: 0.9446435487356825 and parameters: {'weight_class_0': 0.0065264063908118276, 'weight_class_1': 0.0718755188682043, 'weight_class_2': 0.02424470032703936}. Best is trial 145 with value: 0.9495831298391959.
[I 2026-07-13 11:37:26,324] Trial 172 finished with value: 0.9448246980002462 and parameters: {'weight_class_0': 0.006785445919922855, 'weight_class_1': 0.14732596767956654, 'weight_class_2': 0.02544700291397421}. Best is trial 145 with value: 0.9495831298391959.
[I 2026-07-13 11:37:26,343] Trial 174 finished with value: 0.9481320519629203 and parameters: {'weight_class_0': 0.003414651346852192, 'weight_class_1': 0.1438468502990654, 'weight_class_2': 0.02946780704554865}. Best is trial 145 with value: 0.9495831298391959.
[I 2026-07-13 11:37:26,346] Trial 173 finished with value: 0.9459124489890999 and parameters: {'weight_class_0': 0.006831092849271064, 'weight_class_1': 0.1492958574110866, 'weight_class_2': 0.029174633374727633}. Best is trial 145 with value: 0.9495831298391959.
[I 2026-07-13 11:37:26,392] Trial 175 finished with value: 0.9468155436574306 and parameters: {'weight_class_0': 0.006025778506990237, 'weight_class_1': 0.14067036080371328, 'weight_class_2': 0.029527938831539577}. Best is trial 145 with value: 0.9495831298391959.
[I 2026-07-13 11:37:26,393] Trial 176 finished with value: 0.9494449578437947 and parameters: {'weight_class_0': 0.003296590407984536, 'weight_class_1': 0.0572670604843207, 'weight_class_2': 0.030948721503870413}. Best is trial 145 with value: 0.9495831298391959.
[I 2026-07-13 11:37:26,407] Trial 177 finished with value: 0.9495175948856919 and parameters: {'weight_class_0': 0.0030352860536047768, 'weight_class_1': 0.05702178484018774, 'weight_class_2': 0.03045538201979044}. Best is trial 145 with value: 0.9495831298391959.
[I 2026-07-13 11:37:26,426] Trial 178 finished with value: 0.9493678634737125 and parameters: {'weight_class_0': 0.003181576167265694, 'weight_class_1': 0.06319320991594429, 'weight_class_2': 0.030213514495284702}. Best is trial 145 with value: 0.9495831298391959.

[I 2026-07-13 11:37:26,432] Trial 179 finished with value: 0.9494791618753382 and parameters: {'weight_class_0': 0.003301008613063658, 'weight_class_1': 0.05854623318301979, 'weight_class_2': 0.03124170896959417}. Best is trial 145 with value: 0.9495831298391959.
[I 2026-07-13 11:37:26,461] Trial 180 finished with value: 0.9494621984456567 and parameters: {'weight_class_0': 0.0032179302197604025, 'weight_class_1': 0.05678135751067239, 'weight_class_2': 0.02997898887328954}. Best is trial 145 with value: 0.9495831298391959.
[I 2026-07-13 11:37:26,492] Trial 182 finished with value: 0.9495489970691754 and parameters: {'weight_class_0': 0.002979354238802684, 'weight_class_1': 0.05940470024046983, 'weight_class_2': 0.031986599376758754}. Best is trial 145 with value: 0.9495831298391959.
[I 2026-07-13 11:37:26,493] Trial 181 finished with value: 0.9494687229773371 and parameters: {'weight_class_0': 0.003230671672528968, 'weight_class_1': 0.05397837501007155, 'weight_class_2': 0.030343433833167933}. Best is trial 145 with value: 0.9495831298391959.
[I 2026-07-13 11:37:26,514] Trial 183 finished with value: 0.9495198198271307 and parameters: {'weight_class_0': 0.003150530294487052, 'weight_class_1': 0.05419228614744501, 'weight_class_2': 0.03147995111561311}. Best is trial 145 with value: 0.9495831298391959.
[I 2026-07-13 11:37:26,529] Trial 184 finished with value: 0.9495881322030627 and parameters: {'weight_class_0': 0.003166520437741583, 'weight_class_1': 0.05207193501217082, 'weight_class_2': 0.032456276341004675}. Best is trial 184 with value: 0.9495881322030627.
[I 2026-07-13 11:37:26,557] Trial 185 finished with value: 0.9425648751029003 and parameters: {'weight_class_0': 0.0030947712259693063, 'weight_class_1': 0.03916515278309941, 'weight_class_2': 0.009775701363283026}. Best is trial 184 with value: 0.9495881322030627.
[I 2026-07-13 11:37:26,561] Trial 186 finished with value: 0.9494960719205322 and parameters: {'weight_class_0': 0.0030858011009113275, 'weight_class_1': 0.050122742480620236, 'weight_class_2': 0.031159285138681}. Best is trial 184 with value: 0.9495881322030627.
[I 2026-07-13 11:37:26,599] Trial 188 finished with value: 0.9495202764771422 and parameters: {'weight_class_0': 0.0031341945969448194, 'weight_class_1': 0.05692492538257042, 'weight_class_2': 0.03135059308502592}. Best is trial 184 with value: 0.9495881322030627.
[I 2026-07-13 11:37:26,611] Trial 189 finished with value: 0.9496199228768184 and parameters: {'weight_class_0': 0.003062681185842763, 'weight_class_1': 0.05539254646344579, 'weight_class_2': 0.03200740544454597}. Best is trial 189 with value: 0.9496199228768184.
[I 2026-07-13 11:37:26,619] Trial 187 finished with value: 0.9494750164816109 and parameters: {'weight_class_0': 0.0031871945949578577, 'weight_class_1': 0.05378954863852257, 'weight_class_2': 0.030940941168184688}. Best is trial 189 with value: 0.9496199228768184.

[I 2026-07-13 11:37:26,648] Trial 190 finished with value: 0.9495061152656815 and parameters: {'weight_class_0': 0.003192769451609966, 'weight_class_1': 0.05588990987971231, 'weight_class_2': 0.03142847684172366}. Best is trial 189 with value: 0.9496199228768184.
[I 2026-07-13 11:37:26,658] Trial 191 finished with value: 0.9496737194624627 and parameters: {'weight_class_0': 0.0030038769958161036, 'weight_class_1': 0.05388232726756982, 'weight_class_2': 0.03369896329291614}. Best is trial 191 with value: 0.9496737194624627.
[I 2026-07-13 11:37:26,673] Trial 192 finished with value: 0.9496355380345821 and parameters: {'weight_class_0': 0.0029472931456368703, 'weight_class_1': 0.053937086112952747, 'weight_class_2': 0.03194059513304171}. Best is trial 191 with value: 0.9496737194624627.
[I 2026-07-13 11:37:26,698] Trial 193 finished with value: 0.9484833589460332 and parameters: {'weight_class_0': 0.0029632134505769105, 'weight_class_1': 0.05505452655087931, 'weight_class_2': 0.019481801913060568}. Best is trial 191 with value: 0.9496737194624627.
[I 2026-07-13 11:37:26,708] Trial 194 finished with value: 0.9496918515834345 and parameters: {'weight_class_0': 0.002965271702555062, 'weight_class_1': 0.053111739585572276, 'weight_class_2': 0.0327648342142428}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:26,725] Trial 195 finished with value: 0.9490894029841179 and parameters: {'weight_class_0': 0.002509557570889425, 'weight_class_1': 0.05307750628273126, 'weight_class_2': 0.020049494487127117}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:26,730] Trial 196 finished with value: 0.9490505354748269 and parameters: {'weight_class_0': 0.0024954090033159643, 'weight_class_1': 0.05541029233579395, 'weight_class_2': 0.019952190690146813}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:26,763] Trial 197 finished with value: 0.9493714472013144 and parameters: {'weight_class_0': 0.0024578147290744926, 'weight_class_1': 0.0575046404763713, 'weight_class_2': 0.03366285677286821}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:26,775] Trial 198 finished with value: 0.9494312112677878 and parameters: {'weight_class_0': 0.002560153139244828, 'weight_class_1': 0.055036127933400375, 'weight_class_2': 0.032097941039555246}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:26,811] Trial 199 finished with value: 0.9493962180967085 and parameters: {'weight_class_0': 0.002594051068035754, 'weight_class_1': 0.05814875019535842, 'weight_class_2': 0.03261649642054266}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:26,817] Trial 200 finished with value: 0.9494105772387901 and parameters: {'weight_class_0': 0.00260215014759943, 'weight_class_1': 0.05567932140713849, 'weight_class_2': 0.033384529674612994}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:26,836] Trial 201 finished with value: 0.9495842858241995 and parameters: {'weight_class_0': 0.0028039844810182277, 'weight_class_1': 0.05554163604831597, 'weight_class_2': 0.03213960534912872}. Best is trial 194 with value: 0.9496918515834345.

Best trial: 194. Best value: 0.949692:  42%|████████████████████████████████████████████████████████▍                                                                            | 212/500 [00:03<00:05, 53.98it/s]

[I 2026-07-13 11:37:26,861] Trial 202 finished with value: 0.9494018102998218 and parameters: {'weight_class_0': 0.0024999341475852722, 'weight_class_1': 0.0557252531745102, 'weight_class_2': 0.03201138646699945}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:26,871] Trial 203 finished with value: 0.9494064086042511 and parameters: {'weight_class_0': 0.0025147832642158706, 'weight_class_1': 0.055384691543732746, 'weight_class_2': 0.03241721448168096}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:26,896] Trial 204 finished with value: 0.8072962834358773 and parameters: {'weight_class_0': 0.9682320294560324, 'weight_class_1': 0.039436629691572495, 'weight_class_2': 0.03280939542412778}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:26,916] Trial 205 finished with value: 0.9494918265863569 and parameters: {'weight_class_0': 0.002757151981944373, 'weight_class_1': 0.03855170451465817, 'weight_class_2': 0.032496084422544445}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:26,950] Trial 206 finished with value: 0.9495150640882953 and parameters: {'weight_class_0': 0.002909162669919179, 'weight_class_1': 0.03843820656065795, 'weight_class_2': 0.03290998763044045}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:26,970] Trial 207 finished with value: 0.8086564662302131 and parameters: {'weight_class_0': 0.8357254731851791, 'weight_class_1': 0.03887571343375683, 'weight_class_2': 0.031844406580557864}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:26,979] Trial 208 finished with value: 0.8690913405319618 and parameters: {'weight_class_0': 0.04944119025561972, 'weight_class_1': 0.03839172249956274, 'weight_class_2': 0.04469831715049718}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,000] Trial 209 finished with value: 0.8308577163499735 and parameters: {'weight_class_0': 0.18005435144985596, 'weight_class_1': 0.03987478447817933, 'weight_class_2': 0.04178621598174685}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,016] Trial 210 finished with value: 0.8069806102211473 and parameters: {'weight_class_0': 1.1057735768801908, 'weight_class_1': 0.039103004073621675, 'weight_class_2': 0.0438722980313998}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,024] Trial 211 finished with value: 0.9494245149250701 and parameters: {'weight_class_0': 0.00282928589196185, 'weight_class_1': 0.043241051747438204, 'weight_class_2': 0.044840671435485535}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,057] Trial 212 finished with value: 0.8384604276815694 and parameters: {'weight_class_0': 0.12482470946248234, 'weight_class_1': 0.03931841849001307, 'weight_class_2': 0.042098885567801066}. Best is trial 194 with value: 0.9496918515834345.

Best trial: 194. Best value: 0.949692:  45%|███████████████████████████████████████████████████████████▌                                                                         | 224/500 [00:04<00:05, 54.00it/s]

[I 2026-07-13 11:37:27,075] Trial 213 finished with value: 0.9492401714154356 and parameters: {'weight_class_0': 0.002900801924535845, 'weight_class_1': 0.044569802146732826, 'weight_class_2': 0.0506901423510637}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,089] Trial 214 finished with value: 0.949376606743264 and parameters: {'weight_class_0': 0.0030820723646480517, 'weight_class_1': 0.04256445915665961, 'weight_class_2': 0.043347468757927575}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,107] Trial 215 finished with value: 0.835720735755561 and parameters: {'weight_class_0': 0.125778271710105, 'weight_class_1': 0.03376240633785136, 'weight_class_2': 0.04222276434595923}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,111] Trial 216 finished with value: 0.9490426096679428 and parameters: {'weight_class_0': 0.0030362838524344493, 'weight_class_1': 0.03272548855512193, 'weight_class_2': 0.04255521181821289}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,160] Trial 218 finished with value: 0.9478958749270056 and parameters: {'weight_class_0': 0.005219968351888156, 'weight_class_1': 0.032448831371290676, 'weight_class_2': 0.048608607260697864}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,163] Trial 217 finished with value: 0.9495018059714679 and parameters: {'weight_class_0': 0.003080939675889708, 'weight_class_1': 0.04554484924399328, 'weight_class_2': 0.04443809407095873}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,198] Trial 219 finished with value: 0.9490861763680267 and parameters: {'weight_class_0': 0.0029614224783659445, 'weight_class_1': 0.031033051307859036, 'weight_class_2': 0.04020308862169299}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,204] Trial 220 finished with value: 0.8413329319045895 and parameters: {'weight_class_0': 0.12580953155271, 'weight_class_1': 0.04767750860660241, 'weight_class_2': 0.040157960508963676}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,220] Trial 221 finished with value: 0.9492395473640679 and parameters: {'weight_class_0': 0.0029439014774033326, 'weight_class_1': 0.03014429141337389, 'weight_class_2': 0.03452101980919996}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,250] Trial 222 finished with value: 0.943619029769649 and parameters: {'weight_class_0': 0.005333911336489508, 'weight_class_1': 0.030546370648907462, 'weight_class_2': 0.02068944000369363}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,258] Trial 223 finished with value: 0.9470371170823162 and parameters: {'weight_class_0': 0.00528506926411481, 'weight_class_1': 0.03351216783153099, 'weight_class_2': 0.03328299985876197}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,292] Trial 225 finished with value: 0.9493947134439488 and parameters: {'weight_class_0': 0.002094769193208356, 'weight_class_1': 0.04847932639243268, 'weight_class_2': 0.03157711191792451}. Best is trial 194 with value: 0.9496918515834345.

Best trial: 194. Best value: 0.949692:  47%|██████████████████████████████████████████████████████████████▊                                                                      | 236/500 [00:04<00:04, 54.59it/s]

[I 2026-07-13 11:37:27,294] Trial 224 finished with value: 0.9479243911648886 and parameters: {'weight_class_0': 0.005220763979913918, 'weight_class_1': 0.0493639106174531, 'weight_class_2': 0.03264888823529454}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,327] Trial 227 finished with value: 0.9492941233173161 and parameters: {'weight_class_0': 0.0021559913710278147, 'weight_class_1': 0.04999701451454863, 'weight_class_2': 0.020850487833480782}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,335] Trial 226 finished with value: 0.948036759782108 and parameters: {'weight_class_0': 0.0051073139822051875, 'weight_class_1': 0.04895651282598957, 'weight_class_2': 0.032596766309205764}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,365] Trial 228 finished with value: 0.9479738804524721 and parameters: {'weight_class_0': 0.0036359868535399942, 'weight_class_1': 0.048710853238124935, 'weight_class_2': 0.02194983491433322}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,372] Trial 229 finished with value: 0.9494561246610959 and parameters: {'weight_class_0': 0.0022322351911126834, 'weight_class_1': 0.046901501386833216, 'weight_class_2': 0.03354352586150004}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,396] Trial 230 finished with value: 0.9494287626824783 and parameters: {'weight_class_0': 0.0021059842289557324, 'weight_class_1': 0.04949371278155171, 'weight_class_2': 0.021866151971665217}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,410] Trial 231 finished with value: 0.9493715633074279 and parameters: {'weight_class_0': 0.0021522549320283626, 'weight_class_1': 0.05135488416693865, 'weight_class_2': 0.030625818616813655}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,430] Trial 232 finished with value: 0.9493587837320353 and parameters: {'weight_class_0': 0.002059750763930991, 'weight_class_1': 0.048753666728721466, 'weight_class_2': 0.030406026632251296}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,452] Trial 233 finished with value: 0.9492403808308838 and parameters: {'weight_class_0': 0.0036161104931337665, 'weight_class_1': 0.049140346227444044, 'weight_class_2': 0.03044238611009615}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,455] Trial 234 finished with value: 0.9477938044975719 and parameters: {'weight_class_0': 0.003784367860076785, 'weight_class_1': 0.0492698069054583, 'weight_class_2': 0.02193037951572088}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,504] Trial 235 finished with value: 0.948160361332535 and parameters: {'weight_class_0': 0.003585961510344841, 'weight_class_1': 0.04900125380640425, 'weight_class_2': 0.022434491475763093}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,513] Trial 236 finished with value: 0.5674413136396427 and parameters: {'weight_class_0': 9.394996635282672, 'weight_class_1': 0.06106237003325965, 'weight_class_2': 0.02938418775470159}. Best is trial 194 with value: 0.9496918515834345.

[I 2026-07-13 11:37:27,517] Trial 237 finished with value: 0.9492570531277931 and parameters: {'weight_class_0': 0.0035594755348198953, 'weight_class_1': 0.058312805267697235, 'weight_class_2': 0.029012545642397265}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,542] Trial 238 finished with value: 0.9495110548417648 and parameters: {'weight_class_0': 0.0038260193110532968, 'weight_class_1': 0.060519452563747786, 'weight_class_2': 0.054470032249172594}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,547] Trial 239 finished with value: 0.9495286181104889 and parameters: {'weight_class_0': 0.0036676956776905585, 'weight_class_1': 0.06232946601939031, 'weight_class_2': 0.05406935897017658}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,563] Trial 240 finished with value: 0.9491962801484789 and parameters: {'weight_class_0': 0.0036358065673811183, 'weight_class_1': 0.059794570630688576, 'weight_class_2': 0.029065714364417825}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,591] Trial 241 finished with value: 0.9490939130466991 and parameters: {'weight_class_0': 0.003599647077570741, 'weight_class_1': 0.06060358176213515, 'weight_class_2': 0.027933096362271106}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,621] Trial 242 finished with value: 0.9494096316566414 and parameters: {'weight_class_0': 0.002795917692370609, 'weight_class_1': 0.060935769114051755, 'weight_class_2': 0.03711733086755171}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,623] Trial 243 finished with value: 0.9490155976500168 and parameters: {'weight_class_0': 0.0027582102885037527, 'weight_class_1': 0.06332346458751609, 'weight_class_2': 0.05530321414922666}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,642] Trial 244 finished with value: 0.9493837264953854 and parameters: {'weight_class_0': 0.0026874246755690797, 'weight_class_1': 0.06122139432489536, 'weight_class_2': 0.036709482143785645}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,672] Trial 245 finished with value: 0.9123687781701055 and parameters: {'weight_class_0': 0.0028415549171121107, 'weight_class_1': 0.5231094228621707, 'weight_class_2': 0.0366358798786478}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,691] Trial 246 finished with value: 0.8953420527467721 and parameters: {'weight_class_0': 0.0025653809165661393, 'weight_class_1': 0.581569157762784, 'weight_class_2': 0.037105371433461744}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,709] Trial 247 finished with value: 0.8690415502346868 and parameters: {'weight_class_0': 0.002779585302597929, 'weight_class_1': 0.07599407178745539, 'weight_class_2': 0.9833012739919611}. Best is trial 194 with value: 0.9496918515834345.

Best trial: 194. Best value: 0.949692:  52%|████████████████████████████████████████████████████████████████████▉                                                                | 259/500 [00:04<00:04, 55.18it/s]

[I 2026-07-13 11:37:27,718] Trial 248 finished with value: 0.949033420049318 and parameters: {'weight_class_0': 0.0029239190591832955, 'weight_class_1': 0.07222785888880294, 'weight_class_2': 0.05524099007938101}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,741] Trial 249 finished with value: 0.9490332117897653 and parameters: {'weight_class_0': 0.0029202389527479325, 'weight_class_1': 0.07545754772513928, 'weight_class_2': 0.05359004852483204}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,755] Trial 250 finished with value: 0.948973915216218 and parameters: {'weight_class_0': 0.002898939378091078, 'weight_class_1': 0.07839893226494427, 'weight_class_2': 0.053983523458232416}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,770] Trial 251 finished with value: 0.9490523900708593 and parameters: {'weight_class_0': 0.002892553552419106, 'weight_class_1': 0.08111479446631488, 'weight_class_2': 0.05075509960913496}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,785] Trial 252 finished with value: 0.7004277570548952 and parameters: {'weight_class_0': 0.003154256642402561, 'weight_class_1': 0.078836297185115, 'weight_class_2': 3.9290626907424446}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,818] Trial 253 finished with value: 0.9489648998867911 and parameters: {'weight_class_0': 0.0029648236573228243, 'weight_class_1': 0.07736990735848819, 'weight_class_2': 0.056570634310288415}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,833] Trial 254 finished with value: 0.9493447296881703 and parameters: {'weight_class_0': 0.0032525232588649948, 'weight_class_1': 0.07723151509954247, 'weight_class_2': 0.05147351033838682}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,851] Trial 255 finished with value: 0.9493547561432251 and parameters: {'weight_class_0': 0.0033578489077690263, 'weight_class_1': 0.07381918734562846, 'weight_class_2': 0.05418160468794595}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,860] Trial 256 finished with value: 0.9492044789142163 and parameters: {'weight_class_0': 0.0032056666408169206, 'weight_class_1': 0.07735905665000144, 'weight_class_2': 0.05471399276291434}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,889] Trial 257 finished with value: 0.9492653329366902 and parameters: {'weight_class_0': 0.003225937891039216, 'weight_class_1': 0.07960164228656576, 'weight_class_2': 0.05367775300863572}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,913] Trial 258 finished with value: 0.9493357951784255 and parameters: {'weight_class_0': 0.004043099407505012, 'weight_class_1': 0.042378606623490286, 'weight_class_2': 0.04387188179003133}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,914] Trial 259 finished with value: 0.9490000320862352 and parameters: {'weight_class_0': 0.004309444731379291, 'weight_class_1': 0.03790469794158521, 'weight_class_2': 0.04890990085147889}. Best is trial 194 with value: 0.9496918515834345.

Best trial: 194. Best value: 0.949692:  54%|███████████████████████████████████████████████████████████████████████▊                                                             | 270/500 [00:05<00:04, 55.33it/s]

[I 2026-07-13 11:37:27,946] Trial 260 finished with value: 0.9491252444777905 and parameters: {'weight_class_0': 0.004234906228590149, 'weight_class_1': 0.041130619017612544, 'weight_class_2': 0.03903563432196788}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,961] Trial 261 finished with value: 0.9492415593322701 and parameters: {'weight_class_0': 0.00408998528945405, 'weight_class_1': 0.04390456974780847, 'weight_class_2': 0.039727862410983826}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:27,992] Trial 262 finished with value: 0.949162383484858 and parameters: {'weight_class_0': 0.004141382807096667, 'weight_class_1': 0.040624473192543406, 'weight_class_2': 0.03875204434775882}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,013] Trial 263 finished with value: 0.8913276386046861 and parameters: {'weight_class_0': 0.004166730181592895, 'weight_class_1': 0.001214441440857415, 'weight_class_2': 0.04017868866985214}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,014] Trial 264 finished with value: 0.9491382774372568 and parameters: {'weight_class_0': 0.0041368894621449685, 'weight_class_1': 0.04089578885028441, 'weight_class_2': 0.03743363716967795}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,043] Trial 265 finished with value: 0.9490257048012115 and parameters: {'weight_class_0': 0.004106992743703347, 'weight_class_1': 0.03848384350020759, 'weight_class_2': 0.040376673574316665}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,044] Trial 267 finished with value: 0.9491176963482483 and parameters: {'weight_class_0': 0.0042360597116479, 'weight_class_1': 0.041050551119757264, 'weight_class_2': 0.038975269960134104}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,073] Trial 268 finished with value: 0.9495704759459599 and parameters: {'weight_class_0': 0.0023746212122581303, 'weight_class_1': 0.04158921516682057, 'weight_class_2': 0.03700299680079999}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,079] Trial 266 finished with value: 0.9490521703206958 and parameters: {'weight_class_0': 0.004291478279400751, 'weight_class_1': 0.04027832237869275, 'weight_class_2': 0.03919623029089117}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,103] Trial 269 finished with value: 0.9493406325776665 and parameters: {'weight_class_0': 0.0022823477358042796, 'weight_class_1': 0.039060423080178104, 'weight_class_2': 0.03980239545538075}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,118] Trial 270 finished with value: 0.9493420877956936 and parameters: {'weight_class_0': 0.0022514566743781035, 'weight_class_1': 0.058185854409841496, 'weight_class_2': 0.027610610133014774}. Best is trial 194 with value: 0.9496918515834345.

Best trial: 194. Best value: 0.949692:  56%|██████████████████████████████████████████████████████████████████████████▋                                                          | 281/500 [00:05<00:04, 51.18it/s]

[I 2026-07-13 11:37:28,145] Trial 271 finished with value: 0.9496143636961533 and parameters: {'weight_class_0': 0.0022854680923021665, 'weight_class_1': 0.035701190901549815, 'weight_class_2': 0.026057124696543615}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,182] Trial 272 finished with value: 0.9495110928752464 and parameters: {'weight_class_0': 0.002270816500461402, 'weight_class_1': 0.052684816442468155, 'weight_class_2': 0.02547652757290818}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,198] Trial 274 finished with value: 0.9493694335907615 and parameters: {'weight_class_0': 0.0024660391737113298, 'weight_class_1': 0.025621064925915735, 'weight_class_2': 0.025476712109916828}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,205] Trial 273 finished with value: 0.9494358690733692 and parameters: {'weight_class_0': 0.0022782798805735965, 'weight_class_1': 0.05472874393785142, 'weight_class_2': 0.026698433594089372}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,227] Trial 275 finished with value: 0.9494287159209248 and parameters: {'weight_class_0': 0.002266964201787482, 'weight_class_1': 0.055406608909767834, 'weight_class_2': 0.026610378097880263}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,237] Trial 276 finished with value: 0.9492876187523818 and parameters: {'weight_class_0': 0.0021457315851029567, 'weight_class_1': 0.05825990781927482, 'weight_class_2': 0.02637603881503875}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,258] Trial 277 finished with value: 0.9494704606777288 and parameters: {'weight_class_0': 0.002247626431981665, 'weight_class_1': 0.05539663243043371, 'weight_class_2': 0.02464268286453499}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,271] Trial 278 finished with value: 0.9492974276392051 and parameters: {'weight_class_0': 0.0022536435492150897, 'weight_class_1': 0.059813911136334504, 'weight_class_2': 0.026832728480430758}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,305] Trial 279 finished with value: 0.9492156405651554 and parameters: {'weight_class_0': 0.0019440372266430572, 'weight_class_1': 0.0550834121689936, 'weight_class_2': 0.025766428260921424}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,311] Trial 280 finished with value: 0.9494857501363313 and parameters: {'weight_class_0': 0.001896337951799054, 'weight_class_1': 0.02849948641227772, 'weight_class_2': 0.024986758883909447}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,335] Trial 281 finished with value: 0.9494951753952413 and parameters: {'weight_class_0': 0.001967329771482118, 'weight_class_1': 0.031600665944692574, 'weight_class_2': 0.024874912454269992}. Best is trial 194 with value: 0.9496918515834345.

[I 2026-07-13 11:37:28,361] Trial 282 finished with value: 0.9493441487618437 and parameters: {'weight_class_0': 0.0023385069055692066, 'weight_class_1': 0.027730950055037937, 'weight_class_2': 0.023523649473475464}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,381] Trial 283 finished with value: 0.9494418768573861 and parameters: {'weight_class_0': 0.0018908745309196846, 'weight_class_1': 0.03229040282171906, 'weight_class_2': 0.018029822254913164}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,401] Trial 284 finished with value: 0.9495828932091083 and parameters: {'weight_class_0': 0.001896188807036644, 'weight_class_1': 0.03244105992173528, 'weight_class_2': 0.022208078281101447}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,426] Trial 285 finished with value: 0.9494412839496675 and parameters: {'weight_class_0': 0.0018543320272889166, 'weight_class_1': 0.03262351080737455, 'weight_class_2': 0.017783311702326582}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,438] Trial 287 finished with value: 0.9488439560538641 and parameters: {'weight_class_0': 0.0018756251104952906, 'weight_class_1': 0.034716857265229946, 'weight_class_2': 0.01358802915543544}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,443] Trial 286 finished with value: 0.9496309609019996 and parameters: {'weight_class_0': 0.0018339547565848445, 'weight_class_1': 0.03219549292620358, 'weight_class_2': 0.018787205140054525}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,490] Trial 288 finished with value: 0.9493303542930541 and parameters: {'weight_class_0': 0.0019623563185560537, 'weight_class_1': 0.027098437938333875, 'weight_class_2': 0.01866983280300887}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,499] Trial 289 finished with value: 0.9025480015508097 and parameters: {'weight_class_0': 0.001720001350448977, 'weight_class_1': 0.027038108296706415, 'weight_class_2': 0.4337402736434372}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,505] Trial 290 finished with value: 0.9495360307144667 and parameters: {'weight_class_0': 0.0017943181486354087, 'weight_class_1': 0.030507106499709304, 'weight_class_2': 0.018003443218273782}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,529] Trial 291 finished with value: 0.9494355295241261 and parameters: {'weight_class_0': 0.0019698810798386046, 'weight_class_1': 0.0269279866011725, 'weight_class_2': 0.01987372733616614}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,566] Trial 292 finished with value: 0.9495984958328668 and parameters: {'weight_class_0': 0.0017667216962055465, 'weight_class_1': 0.024766613233180086, 'weight_class_2': 0.019415038259645495}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,577] Trial 293 finished with value: 0.9494684641836093 and parameters: {'weight_class_0': 0.0018317780677570116, 'weight_class_1': 0.024465337545376973, 'weight_class_2': 0.018992902572517782}. Best is trial 194 with value: 0.9496918515834345.

Best trial: 194. Best value: 0.949692:  61%|█████████████████████████████████████████████████████████████████████████████████▍                                                   | 306/500 [00:05<00:03, 57.31it/s]

[I 2026-07-13 11:37:28,593] Trial 294 finished with value: 0.9494585526705932 and parameters: {'weight_class_0': 0.0018372073293950518, 'weight_class_1': 0.027213233403914714, 'weight_class_2': 0.023635602096393996}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,602] Trial 295 finished with value: 0.9496146458619484 and parameters: {'weight_class_0': 0.0016917445730891903, 'weight_class_1': 0.025674586144410424, 'weight_class_2': 0.019155107969218647}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,622] Trial 296 finished with value: 0.9492817043423321 and parameters: {'weight_class_0': 0.001728522847044799, 'weight_class_1': 0.024925580903694393, 'weight_class_2': 0.014385857285598028}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,653] Trial 297 finished with value: 0.9495616322581503 and parameters: {'weight_class_0': 0.001634286801150815, 'weight_class_1': 0.02574445921691727, 'weight_class_2': 0.019856802797524137}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,663] Trial 298 finished with value: 0.9495838626821603 and parameters: {'weight_class_0': 0.001469857153098289, 'weight_class_1': 0.024610354828807485, 'weight_class_2': 0.015579195358381611}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,697] Trial 300 finished with value: 0.949549840094616 and parameters: {'weight_class_0': 0.0014910033623043695, 'weight_class_1': 0.024200257703596274, 'weight_class_2': 0.01777354980083174}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,706] Trial 299 finished with value: 0.9492868179755515 and parameters: {'weight_class_0': 0.0014937268703019196, 'weight_class_1': 0.0325409852209682, 'weight_class_2': 0.013257818768476818}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,737] Trial 301 finished with value: 0.948189856864607 and parameters: {'weight_class_0': 0.002560270344252855, 'weight_class_1': 0.03658835145586141, 'weight_class_2': 0.015973739362802983}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,759] Trial 302 finished with value: 0.9494395170076282 and parameters: {'weight_class_0': 0.0014359121804185164, 'weight_class_1': 0.035845532275574465, 'weight_class_2': 0.016267794249095757}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,772] Trial 303 finished with value: 0.9493951115715697 and parameters: {'weight_class_0': 0.001364586199723028, 'weight_class_1': 0.022458182231983866, 'weight_class_2': 0.012652340930801179}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,783] Trial 304 finished with value: 0.9494407836606319 and parameters: {'weight_class_0': 0.0014066829002294617, 'weight_class_1': 0.03693547313425534, 'weight_class_2': 0.015607880151439883}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,793] Trial 305 finished with value: 0.9496453541895787 and parameters: {'weight_class_0': 0.0014303484938838341, 'weight_class_1': 0.022010165802263622, 'weight_class_2': 0.015877061333633737}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,821] Trial 306 finished with value: 0.9491572062763187 and parameters: {'weight_class_0': 0.0013649268150702292, 'weight_class_1': 0.034548712465724454, 'weight_class_2': 0.01175435381529703}. Best is trial 194 with value: 0.9496918515834345.

Best trial: 194. Best value: 0.949692:  64%|████████████████████████████████████████████████████████████████████████████████████▌                                                | 318/500 [00:05<00:03, 54.29it/s]

[I 2026-07-13 11:37:28,858] Trial 307 finished with value: 0.9494339828486296 and parameters: {'weight_class_0': 0.001458448300417552, 'weight_class_1': 0.021999389530785736, 'weight_class_2': 0.014404875630513623}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,866] Trial 308 finished with value: 0.9494772978967553 and parameters: {'weight_class_0': 0.0013179872487880002, 'weight_class_1': 0.023741473193653297, 'weight_class_2': 0.012780668254871095}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,891] Trial 309 finished with value: 0.9484382793124775 and parameters: {'weight_class_0': 0.0013785079066435152, 'weight_class_1': 0.020415982115885974, 'weight_class_2': 0.008977231233123424}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,908] Trial 310 finished with value: 0.9493851791743512 and parameters: {'weight_class_0': 0.0014249818617510276, 'weight_class_1': 0.02233857000087786, 'weight_class_2': 0.012373461333766994}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,923] Trial 311 finished with value: 0.9495299947939674 and parameters: {'weight_class_0': 0.0012714868108809451, 'weight_class_1': 0.020919329443774025, 'weight_class_2': 0.016547535846913163}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,940] Trial 312 finished with value: 0.9475826728426163 and parameters: {'weight_class_0': 0.0018254036005274003, 'weight_class_1': 0.01992788544852426, 'weight_class_2': 0.010358702209422805}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,950] Trial 313 finished with value: 0.9495715251745543 and parameters: {'weight_class_0': 0.0012731562089325647, 'weight_class_1': 0.021433200033089014, 'weight_class_2': 0.015475874629136091}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,961] Trial 315 finished with value: 0.9496365793323456 and parameters: {'weight_class_0': 0.0012310825300649545, 'weight_class_1': 0.020937505213147932, 'weight_class_2': 0.014034727249247252}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:28,969] Trial 314 finished with value: 0.9487437539194133 and parameters: {'weight_class_0': 0.001300175961959974, 'weight_class_1': 0.02110385942092962, 'weight_class_2': 0.009170259769069114}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,017] Trial 317 finished with value: 0.9494119600181873 and parameters: {'weight_class_0': 0.001193805947038059, 'weight_class_1': 0.02016227444649969, 'weight_class_2': 0.010547328900833442}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,019] Trial 316 finished with value: 0.9495219353756208 and parameters: {'weight_class_0': 0.0011276628671833865, 'weight_class_1': 0.018541515166786728, 'weight_class_2': 0.014613871544420284}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,029] Trial 318 finished with value: 0.9486311585565398 and parameters: {'weight_class_0': 0.0015429372057012075, 'weight_class_1': 0.02093854005224368, 'weight_class_2': 0.010786546372463528}. Best is trial 194 with value: 0.9496918515834345.

Best trial: 194. Best value: 0.949692:  66%|███████████████████████████████████████████████████████████████████████████████████████▊                                             | 330/500 [00:06<00:03, 54.20it/s]

[I 2026-07-13 11:37:29,051] Trial 319 finished with value: 0.9495819514564996 and parameters: {'weight_class_0': 0.0012265728862066209, 'weight_class_1': 0.020685274846185073, 'weight_class_2': 0.018681816212339733}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,098] Trial 320 finished with value: 0.9495784901857283 and parameters: {'weight_class_0': 0.0016307764321779172, 'weight_class_1': 0.019603281580854014, 'weight_class_2': 0.01815695410514207}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,105] Trial 321 finished with value: 0.949443110969079 and parameters: {'weight_class_0': 0.0011874550208210986, 'weight_class_1': 0.025564538113386045, 'weight_class_2': 0.01775927800413586}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,121] Trial 322 finished with value: 0.9495328123965062 and parameters: {'weight_class_0': 0.0010092400968849228, 'weight_class_1': 0.01687744918832296, 'weight_class_2': 0.0160196491396288}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,139] Trial 323 finished with value: 0.9494002604067125 and parameters: {'weight_class_0': 0.0015669982473900757, 'weight_class_1': 0.021832636329988105, 'weight_class_2': 0.015629171150446285}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,159] Trial 324 finished with value: 0.9494960218516013 and parameters: {'weight_class_0': 0.0010987014233861075, 'weight_class_1': 0.017587678362561955, 'weight_class_2': 0.015878937675734242}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,174] Trial 325 finished with value: 0.9495375514793002 and parameters: {'weight_class_0': 0.0010960398038562895, 'weight_class_1': 0.01678482772971483, 'weight_class_2': 0.01664702997374483}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,185] Trial 326 finished with value: 0.9495112192644136 and parameters: {'weight_class_0': 0.0011001196627446685, 'weight_class_1': 0.018103830611328236, 'weight_class_2': 0.017297266301438442}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,197] Trial 327 finished with value: 0.9495080732485092 and parameters: {'weight_class_0': 0.0011068067449668687, 'weight_class_1': 0.017126178535407963, 'weight_class_2': 0.01489665715998964}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,229] Trial 328 finished with value: 0.9494883133060843 and parameters: {'weight_class_0': 0.0010628288109246163, 'weight_class_1': 0.01842011468269003, 'weight_class_2': 0.015040465715472552}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,254] Trial 329 finished with value: 0.949576997285626 and parameters: {'weight_class_0': 0.0010333472524711375, 'weight_class_1': 0.017190508537916618, 'weight_class_2': 0.015470106842146758}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,259] Trial 330 finished with value: 0.9495374319755787 and parameters: {'weight_class_0': 0.0010700235866169642, 'weight_class_1': 0.016784758890753485, 'weight_class_2': 0.01553556166769014}. Best is trial 194 with value: 0.9496918515834345.

Best trial: 194. Best value: 0.949692:  68%|██████████████████████████████████████████████████████████████████████████████████████████▋                                          | 341/500 [00:06<00:02, 53.87it/s]

[I 2026-07-13 11:37:29,272] Trial 331 finished with value: 0.9493856118465559 and parameters: {'weight_class_0': 0.0012417738989528514, 'weight_class_1': 0.016458340680568236, 'weight_class_2': 0.01648960884074203}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,318] Trial 333 finished with value: 0.949396251147616 and parameters: {'weight_class_0': 0.001068846727038213, 'weight_class_1': 0.016718580012491716, 'weight_class_2': 0.0174683146607715}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,330] Trial 332 finished with value: 0.9495774182225917 and parameters: {'weight_class_0': 0.0010521467793836138, 'weight_class_1': 0.01727897199732359, 'weight_class_2': 0.015964512580661644}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,332] Trial 334 finished with value: 0.9492296274521154 and parameters: {'weight_class_0': 0.001049018130581143, 'weight_class_1': 0.017520758655098445, 'weight_class_2': 0.018919392138840405}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,370] Trial 335 finished with value: 0.948956609950169 and parameters: {'weight_class_0': 0.001006001276389083, 'weight_class_1': 0.01611300896341766, 'weight_class_2': 0.019932046773444817}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,376] Trial 336 finished with value: 0.9490992913421664 and parameters: {'weight_class_0': 0.0010104095799132692, 'weight_class_1': 0.01670344557314484, 'weight_class_2': 0.019096185590301122}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,406] Trial 337 finished with value: 0.9489128420941378 and parameters: {'weight_class_0': 0.0010398565928186195, 'weight_class_1': 0.014615111369724928, 'weight_class_2': 0.01960376994849837}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,414] Trial 339 finished with value: 0.9495617060615961 and parameters: {'weight_class_0': 0.0010144172330093701, 'weight_class_1': 0.016436253870462127, 'weight_class_2': 0.012300195971777833}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,428] Trial 338 finished with value: 0.9490093367801457 and parameters: {'weight_class_0': 0.00157799044826145, 'weight_class_1': 0.014854611909077518, 'weight_class_2': 0.019642687153780918}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,459] Trial 340 finished with value: 0.9485968605196918 and parameters: {'weight_class_0': 0.0010186141210508015, 'weight_class_1': 0.011939897436148888, 'weight_class_2': 0.020651012043223456}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,475] Trial 341 finished with value: 0.9493844813894882 and parameters: {'weight_class_0': 0.0010100270856360347, 'weight_class_1': 0.01146443886989449, 'weight_class_2': 0.011761793688623826}. Best is trial 194 with value: 0.9496918515834345.

[I 2026-07-13 11:37:29,492] Trial 343 finished with value: 0.9482902722425205 and parameters: {'weight_class_0': 0.0015280980970577731, 'weight_class_1': 0.012289576476446552, 'weight_class_2': 0.011418220145709135}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,516] Trial 342 finished with value: 0.94861739618789 and parameters: {'weight_class_0': 0.0015931999353644628, 'weight_class_1': 0.014660749643515283, 'weight_class_2': 0.012233144456890563}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,519] Trial 344 finished with value: 0.948217220704605 and parameters: {'weight_class_0': 0.0015011103404285846, 'weight_class_1': 0.010359461003150392, 'weight_class_2': 0.013029830961391294}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,537] Trial 345 finished with value: 0.9489789340252153 and parameters: {'weight_class_0': 0.0015888400045757877, 'weight_class_1': 0.02524640815450499, 'weight_class_2': 0.0121309509536205}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,575] Trial 346 finished with value: 0.9484580376081647 and parameters: {'weight_class_0': 0.0016318061656309885, 'weight_class_1': 0.013083720554488046, 'weight_class_2': 0.01273039285996673}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,584] Trial 347 finished with value: 0.9486642526068927 and parameters: {'weight_class_0': 0.0015296252744146483, 'weight_class_1': 0.01335796860690148, 'weight_class_2': 0.011959915854400802}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,604] Trial 348 finished with value: 0.9474554855135064 and parameters: {'weight_class_0': 0.0015313497907439363, 'weight_class_1': 0.024982937412531502, 'weight_class_2': 0.008160480171351035}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,614] Trial 349 finished with value: 0.9489576091267852 and parameters: {'weight_class_0': 0.0015132723068010023, 'weight_class_1': 0.024361395335280832, 'weight_class_2': 0.011544492776421722}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,635] Trial 350 finished with value: 0.9476489206979366 and parameters: {'weight_class_0': 0.0015229322572801228, 'weight_class_1': 0.02394071915845021, 'weight_class_2': 0.008414927683116094}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,655] Trial 351 finished with value: 0.9457582909712272 and parameters: {'weight_class_0': 0.001778815569527211, 'weight_class_1': 0.02313918587345807, 'weight_class_2': 0.007393476129890861}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,669] Trial 352 finished with value: 0.9476092076782011 and parameters: {'weight_class_0': 0.001590996365344294, 'weight_class_1': 0.023334055196822755, 'weight_class_2': 0.00874902759028902}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,705] Trial 353 finished with value: 0.9481379126332831 and parameters: {'weight_class_0': 0.0013677987285452928, 'weight_class_1': 0.02482169545232955, 'weight_class_2': 0.008283416146163985}. Best is trial 194 with value: 0.9496918515834345.

[I 2026-07-13 11:37:29,717] Trial 354 finished with value: 0.9477847175413131 and parameters: {'weight_class_0': 0.0013476578294379683, 'weight_class_1': 0.024335919086738395, 'weight_class_2': 0.007693422417253464}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,726] Trial 355 finished with value: 0.9484469378913155 and parameters: {'weight_class_0': 0.0013653273543881997, 'weight_class_1': 0.02419596853131731, 'weight_class_2': 0.008841672176361198}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,764] Trial 357 finished with value: 0.9475409246930568 and parameters: {'weight_class_0': 0.0013164426812675015, 'weight_class_1': 0.024787576474747965, 'weight_class_2': 0.007189928350824341}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,774] Trial 356 finished with value: 0.9483747770342436 and parameters: {'weight_class_0': 0.001321983404584863, 'weight_class_1': 0.0245530990240666, 'weight_class_2': 0.008504160660610095}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,803] Trial 359 finished with value: 0.9484574191947811 and parameters: {'weight_class_0': 0.001215071862269166, 'weight_class_1': 0.023106702557177308, 'weight_class_2': 0.007991186069172665}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,804] Trial 358 finished with value: 0.9493574261798977 and parameters: {'weight_class_0': 0.0012684593763126382, 'weight_class_1': 0.024560995074745913, 'weight_class_2': 0.021603426995707067}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,842] Trial 360 finished with value: 0.9491997666754352 and parameters: {'weight_class_0': 0.0012241394071232667, 'weight_class_1': 0.026440493906155344, 'weight_class_2': 0.021761791140654674}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,849] Trial 361 finished with value: 0.9493254769250793 and parameters: {'weight_class_0': 0.001266888753719999, 'weight_class_1': 0.030437215837404916, 'weight_class_2': 0.020159086291205865}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,869] Trial 362 finished with value: 0.9492511844315162 and parameters: {'weight_class_0': 0.0012884799608749572, 'weight_class_1': 0.028265102076694793, 'weight_class_2': 0.022272068068592596}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,885] Trial 365 finished with value: 0.9492157659056105 and parameters: {'weight_class_0': 0.0012558893509382416, 'weight_class_1': 0.02899639299252525, 'weight_class_2': 0.021769886926772855}. Best is trial 194 with value: 0.9496918515834345.

[I 2026-07-13 11:37:29,895] Trial 363 finished with value: 0.9492644256505353 and parameters: {'weight_class_0': 0.0013147713771391727, 'weight_class_1': 0.02894294534856612, 'weight_class_2': 0.022449131409009046}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,907] Trial 364 finished with value: 0.9491544682811135 and parameters: {'weight_class_0': 0.001247736417980737, 'weight_class_1': 0.028920187221680015, 'weight_class_2': 0.02238592584996769}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,954] Trial 367 finished with value: 0.9492153024603835 and parameters: {'weight_class_0': 0.0012352634415224927, 'weight_class_1': 0.03063004038961364, 'weight_class_2': 0.020897774777153644}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,957] Trial 366 finished with value: 0.9493708204439218 and parameters: {'weight_class_0': 0.0013408851251869899, 'weight_class_1': 0.03065995460936956, 'weight_class_2': 0.021248386785888633}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,974] Trial 368 finished with value: 0.7697878283120536 and parameters: {'weight_class_0': 2.0568872247244223, 'weight_class_1': 0.029780866630396224, 'weight_class_2': 0.02120177812367027}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:29,986] Trial 369 finished with value: 0.9495922422539058 and parameters: {'weight_class_0': 0.0019202889505829952, 'weight_class_1': 0.030876335758239035, 'weight_class_2': 0.02074390695480964}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,003] Trial 370 finished with value: 0.9496089223947428 and parameters: {'weight_class_0': 0.001954300925554569, 'weight_class_1': 0.030513476666300596, 'weight_class_2': 0.02248483729954242}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,033] Trial 371 finished with value: 0.7688491713120058 and parameters: {'weight_class_0': 2.072852015072431, 'weight_class_1': 0.030170336918552015, 'weight_class_2': 0.02083956380672157}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,054] Trial 373 finished with value: 0.8122372071165952 and parameters: {'weight_class_0': 0.2724024223787257, 'weight_class_1': 0.01881387144889254, 'weight_class_2': 0.012925748881293863}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,066] Trial 372 finished with value: 0.9490369274465132 and parameters: {'weight_class_0': 0.0017740382658589418, 'weight_class_1': 0.01937696436648827, 'weight_class_2': 0.014547424189327826}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,091] Trial 374 finished with value: 0.9485229214988595 and parameters: {'weight_class_0': 0.0019061648383019258, 'weight_class_1': 0.01919912696905175, 'weight_class_2': 0.013602417395365883}. Best is trial 194 with value: 0.9496918515834345.

Best trial: 194. Best value: 0.949692:  77%|██████████████████████████████████████████████████████████████████████████████████████████████████████▋                              | 386/500 [00:07<00:02, 54.36it/s]

[I 2026-07-13 11:37:30,127] Trial 375 finished with value: 0.9489306072094609 and parameters: {'weight_class_0': 0.0018966124860655918, 'weight_class_1': 0.021437457999437238, 'weight_class_2': 0.014803973067249222}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,136] Trial 376 finished with value: 0.9485707579872104 and parameters: {'weight_class_0': 0.0019117059792134257, 'weight_class_1': 0.018601299031630786, 'weight_class_2': 0.014015965279144558}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,161] Trial 377 finished with value: 0.9486742884782755 and parameters: {'weight_class_0': 0.0018451038370982794, 'weight_class_1': 0.019748401603417846, 'weight_class_2': 0.013846629443358863}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,183] Trial 379 finished with value: 0.948949316265513 and parameters: {'weight_class_0': 0.0018029741436091497, 'weight_class_1': 0.018719359434571044, 'weight_class_2': 0.014381015533760137}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,190] Trial 380 finished with value: 0.948319410078088 and parameters: {'weight_class_0': 0.0020063986581052395, 'weight_class_1': 0.018697267011727695, 'weight_class_2': 0.013912308892710511}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,199] Trial 378 finished with value: 0.9485682372562333 and parameters: {'weight_class_0': 0.001911473356782657, 'weight_class_1': 0.019998967545627782, 'weight_class_2': 0.013702220914116334}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,218] Trial 381 finished with value: 0.9485732770193834 and parameters: {'weight_class_0': 0.0019567148142508473, 'weight_class_1': 0.018430680543049756, 'weight_class_2': 0.014580164713700976}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,235] Trial 382 finished with value: 0.948609621996097 and parameters: {'weight_class_0': 0.0019465619187046999, 'weight_class_1': 0.019766264348107503, 'weight_class_2': 0.014350341698621597}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,262] Trial 383 finished with value: 0.9487103206725598 and parameters: {'weight_class_0': 0.00184006360884553, 'weight_class_1': 0.01958582204690297, 'weight_class_2': 0.013893326022596433}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,272] Trial 384 finished with value: 0.9487520799754153 and parameters: {'weight_class_0': 0.002060195651369044, 'weight_class_1': 0.03434678514673934, 'weight_class_2': 0.01442923179838985}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,297] Trial 385 finished with value: 0.9487891303294481 and parameters: {'weight_class_0': 0.0020693475601691763, 'weight_class_1': 0.03394012312792446, 'weight_class_2': 0.01478631345609308}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,312] Trial 386 finished with value: 0.9486741861035536 and parameters: {'weight_class_0': 0.0022525535689328345, 'weight_class_1': 0.033843470015390426, 'weight_class_2': 0.015695849844672982}. Best is trial 194 with value: 0.9496918515834345.

Best trial: 194. Best value: 0.949692:  80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▊                           | 398/500 [00:07<00:01, 54.03it/s]

[I 2026-07-13 11:37:30,350] Trial 388 finished with value: 0.8984814255364756 and parameters: {'weight_class_0': 0.002267335693686992, 'weight_class_1': 0.03513500339305501, 'weight_class_2': 0.001173554440059091}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,357] Trial 387 finished with value: 0.9491956151361182 and parameters: {'weight_class_0': 0.0021201806267302213, 'weight_class_1': 0.03475891538530751, 'weight_class_2': 0.017027113941955798}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,388] Trial 391 finished with value: 0.9494212150051484 and parameters: {'weight_class_0': 0.0020321598271849524, 'weight_class_1': 0.03601590577019402, 'weight_class_2': 0.017630621398681372}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,392] Trial 389 finished with value: 0.9487849243858565 and parameters: {'weight_class_0': 0.0023627885859024917, 'weight_class_1': 0.037084880802980134, 'weight_class_2': 0.016837918748655232}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,415] Trial 390 finished with value: 0.9490324167797182 and parameters: {'weight_class_0': 0.00233965236095842, 'weight_class_1': 0.03604664019593507, 'weight_class_2': 0.018037027941014628}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,431] Trial 392 finished with value: 0.9489991234319373 and parameters: {'weight_class_0': 0.0023096260356659437, 'weight_class_1': 0.03551454834117727, 'weight_class_2': 0.017638346481301814}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,441] Trial 394 finished with value: 0.948956057794523 and parameters: {'weight_class_0': 0.0023996714740006104, 'weight_class_1': 0.03504149198102956, 'weight_class_2': 0.01826879939225773}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,442] Trial 393 finished with value: 0.937296123876151 and parameters: {'weight_class_0': 0.002378988119049473, 'weight_class_1': 0.037331644292843184, 'weight_class_2': 0.005593859927635817}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,462] Trial 395 finished with value: 0.9488584505695087 and parameters: {'weight_class_0': 0.002348275922031944, 'weight_class_1': 0.044994514382769815, 'weight_class_2': 0.017371628759691927}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,491] Trial 396 finished with value: 0.9488906163438463 and parameters: {'weight_class_0': 0.002471919962218073, 'weight_class_1': 0.041936503656186806, 'weight_class_2': 0.018232545291252022}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,501] Trial 397 finished with value: 0.9470630894115182 and parameters: {'weight_class_0': 0.0024083449450424434, 'weight_class_1': 0.013943163952584705, 'weight_class_2': 0.016865383831340095}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,539] Trial 398 finished with value: 0.9494090569136026 and parameters: {'weight_class_0': 0.002552843543868004, 'weight_class_1': 0.04361580568911544, 'weight_class_2': 0.023119274971924425}. Best is trial 194 with value: 0.9496918515834345.

[I 2026-07-13 11:37:30,572] Trial 400 finished with value: 0.9442437000315919 and parameters: {'weight_class_0': 0.0025374852690632286, 'weight_class_1': 0.015151408600234315, 'weight_class_2': 0.010358722463116376}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,577] Trial 399 finished with value: 0.9489538997585177 and parameters: {'weight_class_0': 0.0024013902564036754, 'weight_class_1': 0.04636767008906795, 'weight_class_2': 0.018317912387661547}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,599] Trial 401 finished with value: 0.9489407720278268 and parameters: {'weight_class_0': 0.001566295645823171, 'weight_class_1': 0.01520847566756231, 'weight_class_2': 0.02400627311338086}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,635] Trial 402 finished with value: 0.9479409680086954 and parameters: {'weight_class_0': 0.0016400455208891499, 'weight_class_1': 0.014545603886991866, 'weight_class_2': 0.010607234378743462}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,644] Trial 403 finished with value: 0.9481380443321691 and parameters: {'weight_class_0': 0.0016344738159169657, 'weight_class_1': 0.015312838592229375, 'weight_class_2': 0.010677457984452382}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,648] Trial 404 finished with value: 0.7044320142247105 and parameters: {'weight_class_0': 0.0016741988334170166, 'weight_class_1': 0.014630161980442574, 'weight_class_2': 1.5776732755126466}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,667] Trial 405 finished with value: 0.9489022846460445 and parameters: {'weight_class_0': 0.0016050780037609477, 'weight_class_1': 0.015891141773524704, 'weight_class_2': 0.02534595367493864}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,688] Trial 406 finished with value: 0.9487403074764256 and parameters: {'weight_class_0': 0.001598542146299249, 'weight_class_1': 0.013989954488869128, 'weight_class_2': 0.023745171787683064}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,706] Trial 407 finished with value: 0.948946088284606 and parameters: {'weight_class_0': 0.0016345808968544942, 'weight_class_1': 0.015601103276646213, 'weight_class_2': 0.02494374743570585}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,735] Trial 409 finished with value: 0.9483158624544382 and parameters: {'weight_class_0': 0.001582634957879226, 'weight_class_1': 0.015082509683237915, 'weight_class_2': 0.010692357022600265}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,741] Trial 408 finished with value: 0.7158883229561716 and parameters: {'weight_class_0': 0.0015949954789618275, 'weight_class_1': 0.014761215999259884, 'weight_class_2': 1.4112769383388148}. Best is trial 194 with value: 0.9496918515834345.

Best trial: 194. Best value: 0.949692:  84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                     | 421/500 [00:07<00:01, 51.19it/s]

[I 2026-07-13 11:37:30,781] Trial 411 finished with value: 0.9479354626429247 and parameters: {'weight_class_0': 0.0016032797127735307, 'weight_class_1': 0.010522672211930744, 'weight_class_2': 0.023053609517945713}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,783] Trial 410 finished with value: 0.9495640936858546 and parameters: {'weight_class_0': 0.001640891973953926, 'weight_class_1': 0.028322703673690944, 'weight_class_2': 0.025361233224703794}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,795] Trial 412 finished with value: 0.7101235646093986 and parameters: {'weight_class_0': 0.0016318717728042412, 'weight_class_1': 0.011228904821225974, 'weight_class_2': 1.3981582986584156}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,821] Trial 413 finished with value: 0.9494263926635043 and parameters: {'weight_class_0': 0.001562383278764577, 'weight_class_1': 0.02984669204384067, 'weight_class_2': 0.025444279151599684}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,872] Trial 415 finished with value: 0.9484832690757973 and parameters: {'weight_class_0': 0.0010031263935316886, 'weight_class_1': 0.02874290037955238, 'weight_class_2': 0.027089505603935145}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,876] Trial 414 finished with value: 0.9488381112976955 and parameters: {'weight_class_0': 0.001204212905845021, 'weight_class_1': 0.028559813257875283, 'weight_class_2': 0.027098819908174997}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,885] Trial 416 finished with value: 0.9488568449565138 and parameters: {'weight_class_0': 0.001204811955885188, 'weight_class_1': 0.029379788344571514, 'weight_class_2': 0.027079754285284335}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,901] Trial 417 finished with value: 0.9485327265903859 and parameters: {'weight_class_0': 0.001012936986531936, 'weight_class_1': 0.028148949600932966, 'weight_class_2': 0.02689280612454301}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,923] Trial 418 finished with value: 0.9489076784016923 and parameters: {'weight_class_0': 0.001263441498169901, 'weight_class_1': 0.027713828168434766, 'weight_class_2': 0.02759832676619249}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,943] Trial 419 finished with value: 0.9487015543638692 and parameters: {'weight_class_0': 0.0011772419768941607, 'weight_class_1': 0.02672420611976848, 'weight_class_2': 0.02823088745523249}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,947] Trial 420 finished with value: 0.948480295770968 and parameters: {'weight_class_0': 0.0010129079251712046, 'weight_class_1': 0.02615746531510096, 'weight_class_2': 0.02760503250366642}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:30,975] Trial 421 finished with value: 0.9478199958664105 and parameters: {'weight_class_0': 0.0012581000213098149, 'weight_class_1': 0.010612862647047463, 'weight_class_2': 0.027491693705317833}. Best is trial 194 with value: 0.9496918515834345.

[I 2026-07-13 11:37:30,989] Trial 422 finished with value: 0.9487866197381684 and parameters: {'weight_class_0': 0.0011624180509549637, 'weight_class_1': 0.02706373315296705, 'weight_class_2': 0.02696956547294021}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,006] Trial 424 finished with value: 0.948701427620434 and parameters: {'weight_class_0': 0.0012130512620342395, 'weight_class_1': 0.02786909250430119, 'weight_class_2': 0.02905975558553264}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,025] Trial 423 finished with value: 0.9486584295670043 and parameters: {'weight_class_0': 0.001192664083411103, 'weight_class_1': 0.027724936940194515, 'weight_class_2': 0.02952719335538163}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,042] Trial 425 finished with value: 0.9488064879379268 and parameters: {'weight_class_0': 0.0012587105023094689, 'weight_class_1': 0.022495517475252604, 'weight_class_2': 0.028296714050648535}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,061] Trial 426 finished with value: 0.9493514421917011 and parameters: {'weight_class_0': 0.001204229671459267, 'weight_class_1': 0.02259649579021486, 'weight_class_2': 0.021265936367806562}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,102] Trial 428 finished with value: 0.9495494731053261 and parameters: {'weight_class_0': 0.0013669107041609176, 'weight_class_1': 0.021266471781499825, 'weight_class_2': 0.020835129128487773}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,115] Trial 427 finished with value: 0.9495047249048687 and parameters: {'weight_class_0': 0.001290776860499469, 'weight_class_1': 0.022699612982110533, 'weight_class_2': 0.020945990053974642}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,130] Trial 429 finished with value: 0.9495458964943614 and parameters: {'weight_class_0': 0.001268834428376574, 'weight_class_1': 0.02248305893644052, 'weight_class_2': 0.020039188323220103}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,145] Trial 430 finished with value: 0.948938121527959 and parameters: {'weight_class_0': 0.0013288108663942963, 'weight_class_1': 0.04513422877551922, 'weight_class_2': 0.02033160512142708}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,156] Trial 431 finished with value: 0.9493932491971734 and parameters: {'weight_class_0': 0.0012573114622291296, 'weight_class_1': 0.021909875055040454, 'weight_class_2': 0.02138949294665182}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,172] Trial 432 finished with value: 0.9493993875874772 and parameters: {'weight_class_0': 0.0012836550243240721, 'weight_class_1': 0.021197275499017967, 'weight_class_2': 0.021430720042689987}. Best is trial 194 with value: 0.9496918515834345.

[I 2026-07-13 11:37:31,189] Trial 433 finished with value: 0.9481903245408555 and parameters: {'weight_class_0': 0.00276003154400406, 'weight_class_1': 0.020451226724111465, 'weight_class_2': 0.021544887973292754}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,204] Trial 434 finished with value: 0.9494557145796111 and parameters: {'weight_class_0': 0.00201730681882045, 'weight_class_1': 0.04508626955417878, 'weight_class_2': 0.021070067425805472}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,239] Trial 435 finished with value: 0.9494582391526943 and parameters: {'weight_class_0': 0.0020396901971693935, 'weight_class_1': 0.04538888613650353, 'weight_class_2': 0.020861928165808473}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,249] Trial 436 finished with value: 0.9495185069598685 and parameters: {'weight_class_0': 0.002000087533056651, 'weight_class_1': 0.04231896121913312, 'weight_class_2': 0.020883954644081472}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,266] Trial 437 finished with value: 0.9491566948185598 and parameters: {'weight_class_0': 0.0019850395874312365, 'weight_class_1': 0.04207226198329713, 'weight_class_2': 0.036520156831191725}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,288] Trial 438 finished with value: 0.9493295765360146 and parameters: {'weight_class_0': 0.0019899346431849247, 'weight_class_1': 0.04325829104112026, 'weight_class_2': 0.01940536747818712}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,305] Trial 439 finished with value: 0.9492334865010918 and parameters: {'weight_class_0': 0.002023050070587477, 'weight_class_1': 0.04488389858469738, 'weight_class_2': 0.03471716156507298}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,340] Trial 440 finished with value: 0.9494988782356578 and parameters: {'weight_class_0': 0.002661830556542579, 'weight_class_1': 0.04132481715470451, 'weight_class_2': 0.03637609198469038}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,351] Trial 441 finished with value: 0.9494932932722584 and parameters: {'weight_class_0': 0.002688161483175898, 'weight_class_1': 0.04331956495922286, 'weight_class_2': 0.034545361883258324}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,370] Trial 442 finished with value: 0.9494900735146792 and parameters: {'weight_class_0': 0.0026972919491192538, 'weight_class_1': 0.042768382987866047, 'weight_class_2': 0.03441109902894063}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,403] Trial 444 finished with value: 0.8175329435130608 and parameters: {'weight_class_0': 0.44906233351597163, 'weight_class_1': 0.04544862045805163, 'weight_class_2': 0.03595319665562217}. Best is trial 194 with value: 0.9496918515834345.

Best trial: 194. Best value: 0.949692:  91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████            | 455/500 [00:08<00:00, 55.14it/s]

[I 2026-07-13 11:37:31,409] Trial 443 finished with value: 0.6732954532187568 and parameters: {'weight_class_0': 0.002668802598170923, 'weight_class_1': 4.241094340835282, 'weight_class_2': 0.03494454071678251}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,420] Trial 445 finished with value: 0.9491811475267231 and parameters: {'weight_class_0': 0.0019892763192000938, 'weight_class_1': 0.04180143778584707, 'weight_class_2': 0.03633668888452816}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,443] Trial 446 finished with value: 0.9493854829979825 and parameters: {'weight_class_0': 0.0027627710862420892, 'weight_class_1': 0.06582498451161788, 'weight_class_2': 0.03583008360624719}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,449] Trial 447 finished with value: 0.9494858465020375 and parameters: {'weight_class_0': 0.0026405932569095385, 'weight_class_1': 0.040566271314744815, 'weight_class_2': 0.034898096758718716}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,489] Trial 449 finished with value: 0.9469188693227241 and parameters: {'weight_class_0': 0.0025025532407291075, 'weight_class_1': 0.03288416987371036, 'weight_class_2': 0.012361790431124542}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,491] Trial 448 finished with value: 0.9492949593626934 and parameters: {'weight_class_0': 0.0025011576847981188, 'weight_class_1': 0.0654345509209286, 'weight_class_2': 0.03606589681892865}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,501] Trial 450 finished with value: 0.7355690057170065 and parameters: {'weight_class_0': 0.002714100774939299, 'weight_class_1': 0.03403369427923796, 'weight_class_2': 2.248569636747653}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,523] Trial 451 finished with value: 0.9452335773779263 and parameters: {'weight_class_0': 0.0026562356212455314, 'weight_class_1': 0.03179809343990287, 'weight_class_2': 0.010487924830215135}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,557] Trial 452 finished with value: 0.9490258855150592 and parameters: {'weight_class_0': 0.0010100404610120092, 'weight_class_1': 0.03212073877344913, 'weight_class_2': 0.016308356621535104}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,572] Trial 453 finished with value: 0.9444886925391787 and parameters: {'weight_class_0': 0.00344099089732993, 'weight_class_1': 0.0335093204172132, 'weight_class_2': 0.012694449813621677}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,578] Trial 454 finished with value: 0.9445566109582657 and parameters: {'weight_class_0': 0.0035220963719323167, 'weight_class_1': 0.033946929316475374, 'weight_class_2': 0.013071089331196368}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,628] Trial 455 finished with value: 0.9425014953891462 and parameters: {'weight_class_0': 0.0036475513636212474, 'weight_class_1': 0.06877493387630608, 'weight_class_2': 0.011367254168335842}. Best is trial 194 with value: 0.9496918515834345.

Best trial: 194. Best value: 0.949692:  93%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏        | 467/500 [00:08<00:00, 53.18it/s]

[I 2026-07-13 11:37:31,642] Trial 456 finished with value: 0.9430613662373352 and parameters: {'weight_class_0': 0.0035106214021035334, 'weight_class_1': 0.030762775080524246, 'weight_class_2': 0.011704031937957406}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,656] Trial 457 finished with value: 0.9474913389548544 and parameters: {'weight_class_0': 0.001706969059764445, 'weight_class_1': 0.06829087187916968, 'weight_class_2': 0.011438103644149633}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,678] Trial 458 finished with value: 0.9298390436741331 and parameters: {'weight_class_0': 0.001495065830435892, 'weight_class_1': 0.0024987461002522636, 'weight_class_2': 0.010979617172467461}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,692] Trial 459 finished with value: 0.9465669453995625 and parameters: {'weight_class_0': 0.003414845470791934, 'weight_class_1': 0.03149959173921799, 'weight_class_2': 0.016499538576286908}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,725] Trial 460 finished with value: 0.9484980384422547 and parameters: {'weight_class_0': 0.0016557506193327306, 'weight_class_1': 0.017570938311690584, 'weight_class_2': 0.011647215747443151}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,731] Trial 461 finished with value: 0.729855465482057 and parameters: {'weight_class_0': 4.783163807764945, 'weight_class_1': 9.924617704426723, 'weight_class_2': 0.016835492252778424}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,749] Trial 463 finished with value: 0.9236930153006314 and parameters: {'weight_class_0': 0.0015285676651840372, 'weight_class_1': 0.017588256710809297, 'weight_class_2': 0.0022523317059361912}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,753] Trial 462 finished with value: 0.9492294364808118 and parameters: {'weight_class_0': 0.0017086000795654703, 'weight_class_1': 0.01937654538533293, 'weight_class_2': 0.01638254249198364}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,771] Trial 464 finished with value: 0.4745238485647112 and parameters: {'weight_class_0': 5.353019631518957, 'weight_class_1': 0.018174014257427432, 'weight_class_2': 0.016721260380225172}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,789] Trial 465 finished with value: 0.9478618068090717 and parameters: {'weight_class_0': 0.001740090503284969, 'weight_class_1': 0.01820567192128687, 'weight_class_2': 0.04447386661650079}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,796] Trial 466 finished with value: 0.9495274442687297 and parameters: {'weight_class_0': 0.001537645929373947, 'weight_class_1': 0.020082060342469888, 'weight_class_2': 0.016879329834859475}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,822] Trial 467 finished with value: 0.9494748034909554 and parameters: {'weight_class_0': 0.001491756128198998, 'weight_class_1': 0.018778003214137837, 'weight_class_2': 0.016277862751081458}. Best is trial 194 with value: 0.9496918515834345.

Best trial: 194. Best value: 0.949692:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏     | 478/500 [00:08<00:00, 52.56it/s]

[I 2026-07-13 11:37:31,839] Trial 468 finished with value: 0.9478449834714898 and parameters: {'weight_class_0': 0.0014734343152116751, 'weight_class_1': 0.020462109490735313, 'weight_class_2': 0.04664967953740525}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,876] Trial 469 finished with value: 0.9492575713715284 and parameters: {'weight_class_0': 0.0017849893741630034, 'weight_class_1': 0.018361279717232445, 'weight_class_2': 0.017466629101408577}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,884] Trial 470 finished with value: 0.9491690038064903 and parameters: {'weight_class_0': 0.001747846351479465, 'weight_class_1': 0.017568026917662953, 'weight_class_2': 0.016034321066200292}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,904] Trial 471 finished with value: 0.9488399364228192 and parameters: {'weight_class_0': 0.0014321671513650588, 'weight_class_1': 0.012276350120382458, 'weight_class_2': 0.0172294917245884}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,931] Trial 472 finished with value: 0.9463619655085184 and parameters: {'weight_class_0': 0.005011787394813831, 'weight_class_1': 0.023563828029942783, 'weight_class_2': 0.04391790160435227}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,946] Trial 473 finished with value: 0.9492714535271572 and parameters: {'weight_class_0': 0.0018074353619570425, 'weight_class_1': 0.023315760605627598, 'weight_class_2': 0.02553301731965127}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,961] Trial 474 finished with value: 0.9487656150959339 and parameters: {'weight_class_0': 0.0010048066098223086, 'weight_class_1': 0.02167978199697024, 'weight_class_2': 0.023518515045212185}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,980] Trial 475 finished with value: 0.948293904089244 and parameters: {'weight_class_0': 0.0021268111973906374, 'weight_class_1': 0.022717475380064522, 'weight_class_2': 0.04552250962238698}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:31,996] Trial 476 finished with value: 0.9443544060505232 and parameters: {'weight_class_0': 0.004928714735873893, 'weight_class_1': 0.023765172349562793, 'weight_class_2': 0.02448255552313087}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:32,025] Trial 477 finished with value: 0.7072499735553816 and parameters: {'weight_class_0': 0.002184352036296207, 'weight_class_1': 2.242846601157845, 'weight_class_2': 0.02457479935506064}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:32,039] Trial 479 finished with value: 0.7023564020867722 and parameters: {'weight_class_0': 0.002181540811230535, 'weight_class_1': 2.329382599892935, 'weight_class_2': 0.023788998176477092}. Best is trial 194 with value: 0.9496918515834345.

Best trial: 194. Best value: 0.949692:  98%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████   | 489/500 [00:09<00:00, 53.84it/s]

[I 2026-07-13 11:37:32,068] Trial 478 finished with value: 0.9487256068957266 and parameters: {'weight_class_0': 0.0010047334834619606, 'weight_class_1': 0.02439220090835415, 'weight_class_2': 0.02403541204477487}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:32,073] Trial 480 finished with value: 0.9363581465227808 and parameters: {'weight_class_0': 0.004790037643721256, 'weight_class_1': 0.012195050348501208, 'weight_class_2': 0.022671605314837855}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:32,115] Trial 481 finished with value: 0.945547065267485 and parameters: {'weight_class_0': 0.004742417289742555, 'weight_class_1': 0.02496388881490001, 'weight_class_2': 0.026416320928776556}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:32,119] Trial 482 finished with value: 0.9470529904532617 and parameters: {'weight_class_0': 0.001006589970040571, 'weight_class_1': 0.05310376353990562, 'weight_class_2': 0.023826887677296498}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:32,153] Trial 484 finished with value: 0.9494363531146881 and parameters: {'weight_class_0': 0.002177204996685333, 'weight_class_1': 0.051625624847218575, 'weight_class_2': 0.02344249694089988}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:32,163] Trial 485 finished with value: 0.9494919406929903 and parameters: {'weight_class_0': 0.002221844578382766, 'weight_class_1': 0.02560026729992512, 'weight_class_2': 0.02398031505441014}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:32,164] Trial 483 finished with value: 0.9495269627457267 and parameters: {'weight_class_0': 0.002140885733057695, 'weight_class_1': 0.05011425552108509, 'weight_class_2': 0.023599249662971424}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:32,179] Trial 486 finished with value: 0.9494621434574481 and parameters: {'weight_class_0': 0.0021710163770951997, 'weight_class_1': 0.05217833610114991, 'weight_class_2': 0.023679912695570855}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:32,215] Trial 487 finished with value: 0.949443649456164 and parameters: {'weight_class_0': 0.002213563228262187, 'weight_class_1': 0.052314166243866554, 'weight_class_2': 0.024012334775294512}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:32,245] Trial 488 finished with value: 0.9465563829940885 and parameters: {'weight_class_0': 0.001417338645471447, 'weight_class_1': 0.08630606662861813, 'weight_class_2': 0.013908262575037508}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:32,253] Trial 489 finished with value: 0.9486261350053988 and parameters: {'weight_class_0': 0.0013529179789099073, 'weight_class_1': 0.05218441157604261, 'weight_class_2': 0.01396531384179697}. Best is trial 194 with value: 0.9496918515834345.

Best trial: 194. Best value: 0.949692: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 500/500 [00:09<00:00, 54.14it/s]

[I 2026-07-13 11:37:32,261] Trial 490 finished with value: 0.9482507947530253 and parameters: {'weight_class_0': 0.0013707394067113063, 'weight_class_1': 0.05087916516556358, 'weight_class_2': 0.030276947519034828}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:32,294] Trial 491 finished with value: 0.9483020005102443 and parameters: {'weight_class_0': 0.0014219184938814254, 'weight_class_1': 0.049679780304126696, 'weight_class_2': 0.03205379014571665}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:32,302] Trial 492 finished with value: 0.9478741829775142 and parameters: {'weight_class_0': 0.0014076961342448927, 'weight_class_1': 0.008537952698106425, 'weight_class_2': 0.014209198350879852}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:32,321] Trial 493 finished with value: 0.9482164170519249 and parameters: {'weight_class_0': 0.0013739592002654023, 'weight_class_1': 0.05173398533262669, 'weight_class_2': 0.030355919274516814}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:32,336] Trial 494 finished with value: 0.9492859911775474 and parameters: {'weight_class_0': 0.001326618317781115, 'weight_class_1': 0.03634024352309388, 'weight_class_2': 0.013884268147490783}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:32,359] Trial 495 finished with value: 0.9466361160361735 and parameters: {'weight_class_0': 0.0013642719851962599, 'weight_class_1': 0.08360968825742965, 'weight_class_2': 0.013916746894838336}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:32,364] Trial 497 finished with value: 0.9486963486438341 and parameters: {'weight_class_0': 0.001385889937042689, 'weight_class_1': 0.03751573760763765, 'weight_class_2': 0.031248043196992325}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:32,371] Trial 496 finished with value: 0.9491767727677543 and parameters: {'weight_class_0': 0.001445997268292281, 'weight_class_1': 0.03715735101315971, 'weight_class_2': 0.01345677832696708}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:32,386] Trial 498 finished with value: 0.9493387197936971 and parameters: {'weight_class_0': 0.0014225441266579443, 'weight_class_1': 0.03718420999987137, 'weight_class_2': 0.014586634383873828}. Best is trial 194 with value: 0.9496918515834345.
[I 2026-07-13 11:37:32,387] Trial 499 finished with value: 0.9371545347383453 and parameters: {'weight_class_0': 0.003351568287588561, 'weight_class_1': 0.008485817064404292, 'weight_class_2': 0.018799121180561873}. Best is trial 194 with value: 0.9496918515834345.

Best trial score:
0.9496918515834345

Best params:
{'weight_class_0': 0.002965271702555062, 'weight_class_1': 0.053111739585572276, 'weight_class_2': 0.0327648342142428}

In [9]:
weights = np.array([study.best_params['weight_class_0'], study.best_params['weight_class_1'], study.best_params['weight_class_2']])
weighted_probas = X_test.loc[:, ['xgb_0', 'xgb_1', 'xgb_2']].to_numpy() * weights

pred = np.argmax(weighted_probas, axis=1)

In [10]:
sub_labels = label_encoder.inverse_transform(pred)

# Submission

In [11]:
submission = pd.read_csv('../data/submission/sample_submission.csv')
submission['health_condition'] = sub_labels

submission.to_csv('../data/submission/submission_from_5.3_xgboost_submission.csv', index=False)

In [12]:
submission.head()

       id health_condition
0  690088        unhealthy
1  690089        unhealthy
2  690090          at-risk
3  690091          at-risk
4  690092        unhealthy