# Imports

In [13]:
import pickle
import optuna

import numpy as np
import pandas as pd

from sklearn.metrics import balanced_accuracy_score, log_loss
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold, cross_val_predict

## Utils

In [11]:
def load_pickle(file_path):
    with open(file_path, 'rb') as file:
        return pickle.load(file)

# Loading Datasets

In [3]:
X_train = pd.read_parquet('../data/processed/X_train_stacking_layer_one_model_60_trials.parquet')
y_train = pd.read_parquet('../data/interim/y_train.parquet')

X_test = pd.read_parquet('../data/processed/X_test_stacking_layer_one_model_60_trials.parquet')

In [4]:
X_train.head()

,lgbm_0,lgbm_1,lgbm_2,xgb_0,xgb_1,xgb_2,cat_0,cat_1,cat_2
0,0.004922,0.001773,0.993304,0.004134,0.002593,0.993273,0.004337,0.000774,0.994889
1,0.997228,0.000463,0.002309,0.995591,0.000405,0.004004,0.994889,0.001056,0.004055
2,0.002369,0.000604,0.997026,0.001958,0.000503,0.997538,0.003438,0.001069,0.995493
3,0.004656,0.003362,0.991982,0.002466,0.002391,0.995142,0.004847,0.002650,0.992503
4,0.995353,0.000016,0.004632,0.994178,0.000003,0.005819,0.996479,0.000171,0.003351

In [5]:
X_test.head()

,lgbm_0,lgbm_1,lgbm_2,xgb_0,xgb_1,xgb_2,cat_0,cat_1,cat_2
0,0.012452,0.003199,0.984349,0.011048,0.004491,0.984461,0.007391,0.003335,0.989274
1,0.472116,0.002331,0.525553,0.499186,0.001896,0.498918,0.531268,0.002217,0.466515
2,0.998690,0.001012,0.000298,0.997826,0.001594,0.000579,0.995687,0.003676,0.000637
3,0.980854,0.000018,0.019128,0.987434,0.000009,0.012557,0.995089,0.000291,0.004620
4,0.006765,0.001847,0.991388,0.006876,0.001972,0.991152,0.004747,0.003551,0.991701

# Machine Learning

In [14]:
label_encoder = load_pickle('../artifacts/label_encoder.pkl')

In [42]:
def objective(trial, X, y):
    
    C = trial.suggest_float("C", 1e-5, 100.0, log=True)
    class_weight = trial.suggest_categorical("class_weight", [None, "balanced"])
    fit_intercept = trial.suggest_categorical("fit_intercept", [True, False])
    tol = trial.suggest_float("tol", 1e-4, 1e-2, log=True)
    max_iter = trial.suggest_int("max_iter", 1000, 5000)

    w0 = trial.suggest_float('weight_class_0', 0.05, 10.0, log=True)
    w1 = trial.suggest_float('weight_class_1', 0.05, 10.0, log=True)
    w2 = trial.suggest_float('weight_class_2', 0.05, 10.0, log=True)
    weights = np.array([w0, w1, w2])

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    scores = []

    for fold, (train_idx, valid_idx) in enumerate(cv.split(X, y)):
        
        X_train_fold, X_valid_fold = X.iloc[train_idx, :], X.iloc[valid_idx, :]
        y_train_fold, y_valid_fold = y.iloc[train_idx], y.iloc[valid_idx]

        model = LogisticRegression(
            solver="lbfgs",
            l1_ratio=0.0,
            C=C,
            class_weight=class_weight,
            fit_intercept=fit_intercept,
            tol=tol,
            max_iter=max_iter,
            random_state=42,
        ).fit(X_train_fold, y_train_fold)

        proba = model.predict_proba(X_valid_fold)
        
        weighted_probas = proba * weights
        pred = np.argmax(weighted_probas, axis=1)
        
        score = balanced_accuracy_score(y_valid_fold, pred)
        scores.append(score)

        trial.report(np.mean(scores), step=fold)
        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()

    return np.mean(scores)


study = optuna.create_study(
    direction="maximize", 
    sampler=optuna.samplers.TPESampler(seed=42), 
    pruner=optuna.pruners.MedianPruner(n_warmup_steps=2)
)

study.optimize(
    lambda trial: objective(trial, X_train, y_train.health_condition), 
    n_trials=500, 
    n_jobs=-1, 
    show_progress_bar=True
)

print("\nBest trial score:")
print(study.best_trial.value)

print("\nBest params:")
print(study.best_trial.params)

[I 2026-07-08 16:16:58,578] A new study created in memory with name: no-name-ded1b4db-1515-400a-9d5b-6c450f832994
Best trial: 0. Best value: 0.333333:   0%|▎                                                                                                                                      | 1/500 [00:11<1:39:06, 11.92s/it]

[I 2026-07-08 16:17:10,482] Trial 0 finished with value: 0.3333333333333333 and parameters: {'C': 1.933111004532516e-05, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0038215785301761456, 'max_iter': 1619, 'weight_class_0': 0.25840460120773046, 'weight_class_1': 0.13117619260016686, 'weight_class_2': 1.5767405064909965}. Best is trial 0 with value: 0.3333333333333333.

Best trial: 8. Best value: 0.937338:   0%|▌                                                                                                                                      | 2/500 [00:17<1:07:22,  8.12s/it]

[I 2026-07-08 16:17:15,891] Trial 8 finished with value: 0.9373375156264157 and parameters: {'C': 0.00027347651254961894, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.004470907046487394, 'max_iter': 3774, 'weight_class_0': 0.11645254607351578, 'weight_class_1': 0.43189630013191777, 'weight_class_2': 0.11426748531792445}. Best is trial 8 with value: 0.9373375156264157.

Best trial: 8. Best value: 0.937338:   1%|█                                                                                                                                        | 4/500 [00:18<25:54,  3.13s/it]

[I 2026-07-08 16:17:17,300] Trial 10 finished with value: 0.9341722406217157 and parameters: {'C': 0.0006707376757648931, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.004664846727786118, 'max_iter': 2028, 'weight_class_0': 0.16277076679033872, 'weight_class_1': 0.09382009716021812, 'weight_class_2': 0.3340402980737314}. Best is trial 8 with value: 0.9373375156264157.
[I 2026-07-08 16:17:17,420] Trial 11 finished with value: 0.8463609165915909 and parameters: {'C': 0.2566910771118291, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0018987167703514783, 'max_iter': 4631, 'weight_class_0': 6.945138258401626, 'weight_class_1': 0.20106267651797766, 'weight_class_2': 8.05746882358032}. Best is trial 8 with value: 0.9373375156264157.

Best trial: 6. Best value: 0.949734:   1%|█▎                                                                                                                                       | 5/500 [00:19<17:29,  2.12s/it]

[I 2026-07-08 16:17:17,780] Trial 6 finished with value: 0.9497340972525816 and parameters: {'C': 0.0004808339529203831, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.004360572264940558, 'max_iter': 2736, 'weight_class_0': 0.30024320580384356, 'weight_class_1': 2.3171738615368223, 'weight_class_2': 1.7132515538429283}. Best is trial 6 with value: 0.9497340972525816.

Best trial: 6. Best value: 0.949734:   1%|█▋                                                                                                                                       | 6/500 [00:20<15:53,  1.93s/it]

[I 2026-07-08 16:17:19,402] Trial 2 pruned.

Best trial: 6. Best value: 0.949734:   1%|█▉                                                                                                                                       | 7/500 [00:21<12:01,  1.46s/it]

[I 2026-07-08 16:17:19,907] Trial 4 pruned.

Best trial: 6. Best value: 0.949734:   2%|██▏                                                                                                                                      | 8/500 [00:23<13:17,  1.62s/it]

[I 2026-07-08 16:17:21,778] Trial 12 pruned.
[I 2026-07-08 16:17:21,831] Trial 3 pruned.

[I 2026-07-08 16:17:22,451] Trial 7 pruned.

Best trial: 6. Best value: 0.949734:   2%|██▉                                                                                                                                     | 11/500 [00:24<06:32,  1.24it/s]

[I 2026-07-08 16:17:22,648] Trial 5 pruned.
[I 2026-07-08 16:17:22,813] Trial 9 pruned.

Best trial: 6. Best value: 0.949734:   3%|███▌                                                                                                                                    | 13/500 [00:26<08:44,  1.08s/it]

[I 2026-07-08 16:17:25,021] Trial 13 pruned.

Best trial: 6. Best value: 0.949734:   3%|███▊                                                                                                                                    | 14/500 [00:33<21:49,  2.69s/it]

[I 2026-07-08 16:17:31,929] Trial 18 pruned.
[I 2026-07-08 16:17:31,990] Trial 15 pruned.

Best trial: 6. Best value: 0.949734:   3%|████▎                                                                                                                                   | 16/500 [00:35<15:24,  1.91s/it]

[I 2026-07-08 16:17:33,855] Trial 19 pruned.

Best trial: 6. Best value: 0.949734:   3%|████▌                                                                                                                                   | 17/500 [00:35<12:39,  1.57s/it]

[I 2026-07-08 16:17:34,186] Trial 23 pruned.

Best trial: 6. Best value: 0.949734:   4%|████▉                                                                                                                                   | 18/500 [00:36<09:50,  1.23s/it]

[I 2026-07-08 16:17:34,545] Trial 22 pruned.

[I 2026-07-08 16:17:36,180] Trial 24 pruned.

Best trial: 6. Best value: 0.949734:   4%|█████▍                                                                                                                                  | 20/500 [00:37<08:17,  1.04s/it]

[I 2026-07-08 16:17:36,406] Trial 17 pruned.

Best trial: 6. Best value: 0.949734:   4%|█████▋                                                                                                                                  | 21/500 [00:44<20:25,  2.56s/it]

[I 2026-07-08 16:17:42,848] Trial 20 pruned.

Best trial: 6. Best value: 0.949734:   4%|█████▉                                                                                                                                  | 22/500 [00:45<15:52,  1.99s/it]

[I 2026-07-08 16:17:43,496] Trial 26 pruned.
[I 2026-07-08 16:17:43,676] Trial 14 finished with value: 0.9436546417890808 and parameters: {'C': 20.42762555772729, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.002622755667958776, 'max_iter': 1206, 'weight_class_0': 1.664178272969175, 'weight_class_1': 1.278033563076989, 'weight_class_2': 5.4806136704233746}. Best is trial 6 with value: 0.9497340972525816.

Best trial: 6. Best value: 0.949734:   5%|██████▊                                                                                                                                 | 25/500 [00:45<06:22,  1.24it/s]

[I 2026-07-08 16:17:43,842] Trial 25 pruned.
[I 2026-07-08 16:17:43,930] Trial 1 finished with value: 0.9480245185374109 and parameters: {'C': 31.04218380981422, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00012313020837152573, 'max_iter': 2922, 'weight_class_0': 0.5869737503221768, 'weight_class_1': 1.6854724874893259, 'weight_class_2': 5.723753153452136}. Best is trial 6 with value: 0.9497340972525816.

Best trial: 6. Best value: 0.949734:   5%|███████▎                                                                                                                                | 27/500 [00:46<04:13,  1.87it/s]

[I 2026-07-08 16:17:44,521] Trial 28 pruned.
[I 2026-07-08 16:17:44,618] Trial 27 pruned.

Best trial: 6. Best value: 0.949734:   6%|███████▌                                                                                                                                | 28/500 [00:47<06:23,  1.23it/s]

[I 2026-07-08 16:17:46,060] Trial 29 pruned.

Best trial: 6. Best value: 0.949734:   6%|███████▉                                                                                                                                | 29/500 [00:50<09:53,  1.26s/it]

[I 2026-07-08 16:17:48,305] Trial 16 finished with value: 0.9446911419675865 and parameters: {'C': 0.00440562581238849, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00027301640163473134, 'max_iter': 4704, 'weight_class_0': 0.16194771359861748, 'weight_class_1': 0.14406039184046712, 'weight_class_2': 0.7810172868770966}. Best is trial 6 with value: 0.9497340972525816.
[I 2026-07-08 16:17:48,575] Trial 30 pruned.

[I 2026-07-08 16:17:54,907] Trial 21 pruned.

Best trial: 6. Best value: 0.949734:   6%|████████▋                                                                                                                               | 32/500 [00:56<14:33,  1.87s/it]

[I 2026-07-08 16:17:54,927] Trial 32 pruned.

Best trial: 6. Best value: 0.949734:   7%|████████▉                                                                                                                               | 33/500 [00:57<11:27,  1.47s/it]

[I 2026-07-08 16:17:55,502] Trial 33 pruned.

Best trial: 6. Best value: 0.949734:   7%|█████████▏                                                                                                                              | 34/500 [00:58<10:56,  1.41s/it]

[I 2026-07-08 16:17:56,951] Trial 31 finished with value: 0.942959341503099 and parameters: {'C': 87.48513141550079, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.005548473662378738, 'max_iter': 3135, 'weight_class_0': 0.4413394194643758, 'weight_class_1': 0.5579013768480335, 'weight_class_2': 2.8232504353614942}. Best is trial 6 with value: 0.9497340972525816.

Best trial: 6. Best value: 0.949734:   7%|█████████▌                                                                                                                              | 35/500 [00:59<09:45,  1.26s/it]

[I 2026-07-08 16:17:57,770] Trial 35 pruned.

Best trial: 6. Best value: 0.949734:   7%|█████████▊                                                                                                                              | 36/500 [01:04<18:34,  2.40s/it]

[I 2026-07-08 16:18:02,728] Trial 39 pruned.

Best trial: 6. Best value: 0.949734:   7%|██████████                                                                                                                              | 37/500 [01:05<14:18,  1.85s/it]

[I 2026-07-08 16:18:03,565] Trial 34 finished with value: 0.9431389521085587 and parameters: {'C': 33.16406347135863, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00517967694070678, 'max_iter': 4138, 'weight_class_0': 0.33795626735188367, 'weight_class_1': 0.6805839011490711, 'weight_class_2': 3.047426565312238}. Best is trial 6 with value: 0.9497340972525816.

Best trial: 6. Best value: 0.949734:   8%|██████████▎                                                                                                                             | 38/500 [01:11<25:46,  3.35s/it]

[I 2026-07-08 16:18:10,317] Trial 37 finished with value: 0.9425984081063215 and parameters: {'C': 67.76866377265256, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0007607750262386112, 'max_iter': 1146, 'weight_class_0': 1.3245559331883003, 'weight_class_1': 0.8046790171492048, 'weight_class_2': 3.574701083899953}. Best is trial 6 with value: 0.9497340972525816.

Best trial: 6. Best value: 0.949734:   8%|██████████▌                                                                                                                             | 39/500 [01:12<18:24,  2.40s/it]

[I 2026-07-08 16:18:10,406] Trial 42 pruned.

Best trial: 6. Best value: 0.949734:   8%|██████████▉                                                                                                                             | 40/500 [01:16<23:17,  3.04s/it]

[I 2026-07-08 16:18:15,154] Trial 41 pruned.

Best trial: 6. Best value: 0.949734:   8%|███████████▏                                                                                                                            | 41/500 [01:17<17:52,  2.34s/it]

[I 2026-07-08 16:18:15,841] Trial 40 pruned.

Best trial: 6. Best value: 0.949734:   8%|███████████▍                                                                                                                            | 42/500 [01:23<27:02,  3.54s/it]

[I 2026-07-08 16:18:22,156] Trial 43 finished with value: 0.9427697657580429 and parameters: {'C': 68.41914195385066, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0006135186130822455, 'max_iter': 1139, 'weight_class_0': 1.154675535197508, 'weight_class_1': 0.8474774314404951, 'weight_class_2': 2.1453916410580542}. Best is trial 6 with value: 0.9497340972525816.
[I 2026-07-08 16:18:22,252] Trial 44 finished with value: 0.9438918153613731 and parameters: {'C': 24.208943375393183, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0005728640537171428, 'max_iter': 4203, 'weight_class_0': 1.1339988909505057, 'weight_class_1': 0.7689844383242452, 'weight_class_2': 5.1308790966731594}. Best is trial 6 with value: 0.9497340972525816.

Best trial: 6. Best value: 0.949734:   9%|███████████▉                                                                                                                            | 44/500 [01:26<20:08,  2.65s/it]

[I 2026-07-08 16:18:25,208] Trial 45 finished with value: 0.9440643828469917 and parameters: {'C': 25.040391579572525, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0003697348767022447, 'max_iter': 1103, 'weight_class_0': 1.1942729828515803, 'weight_class_1': 0.8213420043433981, 'weight_class_2': 5.296052387543054}. Best is trial 6 with value: 0.9497340972525816.

Best trial: 6. Best value: 0.949734:   9%|████████████▏                                                                                                                           | 45/500 [01:27<16:27,  2.17s/it]

[I 2026-07-08 16:18:26,307] Trial 46 finished with value: 0.9443395648850249 and parameters: {'C': 21.698670704897665, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00047566553173172826, 'max_iter': 1034, 'weight_class_0': 1.2295493530929966, 'weight_class_1': 0.9094200000883143, 'weight_class_2': 5.580694983438346}. Best is trial 6 with value: 0.9497340972525816.

Best trial: 6. Best value: 0.949734:   9%|████████████▌                                                                                                                           | 46/500 [01:30<17:22,  2.30s/it]

[I 2026-07-08 16:18:28,931] Trial 49 pruned.

Best trial: 6. Best value: 0.949734:   9%|████████████▊                                                                                                                           | 47/500 [01:31<15:15,  2.02s/it]

[I 2026-07-08 16:18:30,330] Trial 50 pruned.

Best trial: 6. Best value: 0.949734:  10%|█████████████                                                                                                                           | 48/500 [01:34<16:23,  2.18s/it]

[I 2026-07-08 16:18:32,880] Trial 47 finished with value: 0.9489775223235041 and parameters: {'C': 17.904179823698662, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00041163785751986595, 'max_iter': 1071, 'weight_class_0': 1.2744051530389442, 'weight_class_1': 4.8095670781139175, 'weight_class_2': 5.253121434250716}. Best is trial 6 with value: 0.9497340972525816.
[I 2026-07-08 16:18:33,061] Trial 48 finished with value: 0.9491437512993313 and parameters: {'C': 10.555725667845527, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00039534225066147543, 'max_iter': 1085, 'weight_class_0': 1.1555253693433407, 'weight_class_1': 4.201002154919011, 'weight_class_2': 5.670954248049117}. Best is trial 6 with value: 0.9497340972525816.

Best trial: 6. Best value: 0.949734:  10%|█████████████▌                                                                                                                          | 50/500 [01:36<12:26,  1.66s/it]

[I 2026-07-08 16:18:34,920] Trial 51 pruned.

Best trial: 6. Best value: 0.949734:  10%|█████████████▊                                                                                                                          | 51/500 [01:42<23:20,  3.12s/it]

[I 2026-07-08 16:18:41,416] Trial 55 pruned.

Best trial: 6. Best value: 0.949734:  10%|██████████████▏                                                                                                                         | 52/500 [01:43<18:32,  2.48s/it]

[I 2026-07-08 16:18:42,446] Trial 54 pruned.

Best trial: 6. Best value: 0.949734:  11%|██████████████▍                                                                                                                         | 53/500 [01:45<16:42,  2.24s/it]

[I 2026-07-08 16:18:44,087] Trial 56 pruned.
[I 2026-07-08 16:18:44,122] Trial 36 finished with value: 0.9479072525729965 and parameters: {'C': 49.811698757102036, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00010236054882080399, 'max_iter': 3082, 'weight_class_0': 1.3371680804283914, 'weight_class_1': 4.247505526219274, 'weight_class_2': 3.34139195641542}. Best is trial 6 with value: 0.9497340972525816.

Best trial: 6. Best value: 0.949734:  11%|██████████████▉                                                                                                                         | 55/500 [01:46<10:20,  1.40s/it]

[I 2026-07-08 16:18:44,689] Trial 52 pruned.

[I 2026-07-08 16:18:45,384] Trial 38 pruned.

Best trial: 6. Best value: 0.949734:  12%|███████████████▊                                                                                                                        | 58/500 [01:47<05:15,  1.40it/s]

[I 2026-07-08 16:18:45,585] Trial 57 pruned.
[I 2026-07-08 16:18:45,616] Trial 53 pruned.

Best trial: 6. Best value: 0.949734:  12%|████████████████                                                                                                                        | 59/500 [01:52<15:17,  2.08s/it]

[I 2026-07-08 16:18:51,149] Trial 60 pruned.

Best trial: 6. Best value: 0.949734:  12%|████████████████                                                                                                                        | 59/500 [02:01<15:17,  2.08s/it]

[I 2026-07-08 16:18:59,966] Trial 58 finished with value: 0.9482912894879378 and parameters: {'C': 3.4053536042058643, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00033699944854792975, 'max_iter': 1398, 'weight_class_0': 0.9027877760516504, 'weight_class_1': 3.3652759927832907, 'weight_class_2': 9.35890105842869}. Best is trial 6 with value: 0.9497340972525816.

Best trial: 6. Best value: 0.949734:  12%|████████████████▌                                                                                                                       | 61/500 [02:03<25:39,  3.51s/it]

[I 2026-07-08 16:19:02,531] Trial 59 finished with value: 0.9479282977128035 and parameters: {'C': 2.4654966733345987, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.000312979218764705, 'max_iter': 1473, 'weight_class_0': 2.0172406964354845, 'weight_class_1': 4.128238171793467, 'weight_class_2': 9.062890987557436}. Best is trial 6 with value: 0.9497340972525816.

Best trial: 6. Best value: 0.949734:  12%|████████████████▊                                                                                                                       | 62/500 [02:05<22:10,  3.04s/it]

[I 2026-07-08 16:19:04,459] Trial 61 finished with value: 0.948355429326881 and parameters: {'C': 1.2370584313303725, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00034944772743915786, 'max_iter': 1469, 'weight_class_0': 1.9156106424295303, 'weight_class_1': 4.676967731157082, 'weight_class_2': 9.11018701947042}. Best is trial 6 with value: 0.9497340972525816.

Best trial: 6. Best value: 0.949734:  13%|█████████████████▏                                                                                                                      | 63/500 [02:06<17:24,  2.39s/it]

[I 2026-07-08 16:19:05,287] Trial 70 pruned.

Best trial: 6. Best value: 0.949734:  13%|█████████████████▍                                                                                                                      | 64/500 [02:11<23:32,  3.24s/it]

[I 2026-07-08 16:19:10,549] Trial 63 finished with value: 0.9488013507158918 and parameters: {'C': 6.370349005500454, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00033810235492877404, 'max_iter': 1400, 'weight_class_0': 0.8548675465116714, 'weight_class_1': 3.7823675153808423, 'weight_class_2': 8.393729423211985}. Best is trial 6 with value: 0.9497340972525816.

Best trial: 6. Best value: 0.949734:  13%|█████████████████▋                                                                                                                      | 65/500 [02:12<18:06,  2.50s/it]

[I 2026-07-08 16:19:11,198] Trial 62 finished with value: 0.9487978326457152 and parameters: {'C': 4.756966752798847, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.000284332296067184, 'max_iter': 1373, 'weight_class_0': 0.9497013548899282, 'weight_class_1': 4.015534595919821, 'weight_class_2': 8.876189546441193}. Best is trial 6 with value: 0.9497340972525816.

Best trial: 6. Best value: 0.949734:  13%|█████████████████▉                                                                                                                      | 66/500 [02:15<18:11,  2.51s/it]

[I 2026-07-08 16:19:13,860] Trial 68 finished with value: 0.9487940808174375 and parameters: {'C': 0.1253356876540983, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00026952207837417603, 'max_iter': 1300, 'weight_class_0': 0.846288101885232, 'weight_class_1': 5.312235779314817, 'weight_class_2': 9.213767704930511}. Best is trial 6 with value: 0.9497340972525816.

Best trial: 6. Best value: 0.949734:  13%|██████████████████▏                                                                                                                     | 67/500 [02:16<14:51,  2.06s/it]

[I 2026-07-08 16:19:14,841] Trial 69 finished with value: 0.9490844022080578 and parameters: {'C': 6.540716087491673, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00027796134426254, 'max_iter': 2816, 'weight_class_0': 0.904103113721576, 'weight_class_1': 5.249464472169995, 'weight_class_2': 8.678103895335637}. Best is trial 6 with value: 0.9497340972525816.

Best trial: 6. Best value: 0.949734:  14%|██████████████████▍                                                                                                                     | 68/500 [02:32<44:55,  6.24s/it]

[I 2026-07-08 16:19:30,333] Trial 72 finished with value: 0.9481036144680551 and parameters: {'C': 5.10209380036841, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0002775704320051098, 'max_iter': 1338, 'weight_class_0': 0.9452002648278286, 'weight_class_1': 2.613795117466303, 'weight_class_2': 8.620544804017637}. Best is trial 6 with value: 0.9497340972525816.

Best trial: 6. Best value: 0.949734:  14%|██████████████████▊                                                                                                                     | 69/500 [02:33<34:21,  4.78s/it]

[I 2026-07-08 16:19:32,100] Trial 73 finished with value: 0.9490112152593613 and parameters: {'C': 0.6254864550453606, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0011039875140165837, 'max_iter': 1375, 'weight_class_0': 0.8398351258157347, 'weight_class_1': 5.765794999968572, 'weight_class_2': 8.854425778070631}. Best is trial 6 with value: 0.9497340972525816.

Best trial: 6. Best value: 0.949734:  14%|███████████████████                                                                                                                     | 70/500 [02:35<27:15,  3.80s/it]

[I 2026-07-08 16:19:33,420] Trial 74 finished with value: 0.9468400292428276 and parameters: {'C': 0.5361199413086846, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0002744275457309014, 'max_iter': 1335, 'weight_class_0': 1.8114640530733324, 'weight_class_1': 2.479590698297466, 'weight_class_2': 9.945102903357816}. Best is trial 6 with value: 0.9497340972525816.

Best trial: 6. Best value: 0.949734:  14%|███████████████████▎                                                                                                                    | 71/500 [02:35<19:40,  2.75s/it]

[I 2026-07-08 16:19:33,860] Trial 65 pruned.

Best trial: 6. Best value: 0.949734:  14%|███████████████████▌                                                                                                                    | 72/500 [02:36<15:31,  2.18s/it]

[I 2026-07-08 16:19:34,876] Trial 64 finished with value: 0.9489566146676971 and parameters: {'C': 0.6839879929380291, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00013832454434855538, 'max_iter': 1439, 'weight_class_0': 0.8710433866362757, 'weight_class_1': 4.266692556974758, 'weight_class_2': 8.319274480798278}. Best is trial 6 with value: 0.9497340972525816.

Best trial: 6. Best value: 0.949734:  15%|████████████████████▏                                                                                                                   | 74/500 [02:36<08:38,  1.22s/it]

[I 2026-07-08 16:19:35,258] Trial 67 finished with value: 0.948952908394012 and parameters: {'C': 5.9638973510053725, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0001431331545278177, 'max_iter': 1418, 'weight_class_0': 0.9177288181897315, 'weight_class_1': 4.5793433948990705, 'weight_class_2': 8.880294588661046}. Best is trial 6 with value: 0.9497340972525816.
[I 2026-07-08 16:19:35,467] Trial 66 finished with value: 0.9486915798174346 and parameters: {'C': 6.5168922900952415, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00013636378384319412, 'max_iter': 1401, 'weight_class_0': 0.9311187145914692, 'weight_class_1': 4.27145722866569, 'weight_class_2': 9.387030651053127}. Best is trial 6 with value: 0.9497340972525816.

Best trial: 6. Best value: 0.949734:  15%|████████████████████▍                                                                                                                   | 75/500 [02:38<10:14,  1.45s/it]

[I 2026-07-08 16:19:37,519] Trial 75 finished with value: 0.9482139875795788 and parameters: {'C': 0.6058481633270015, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0011514713609142094, 'max_iter': 1326, 'weight_class_0': 0.906313216543405, 'weight_class_1': 2.480831572408882, 'weight_class_2': 7.752604613995498}. Best is trial 6 with value: 0.9497340972525816.

Best trial: 6. Best value: 0.949734:  15%|████████████████████▋                                                                                                                   | 76/500 [02:41<12:21,  1.75s/it]

[I 2026-07-08 16:19:39,856] Trial 76 finished with value: 0.9483622635820215 and parameters: {'C': 0.6039049778567133, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00026663881260426765, 'max_iter': 1302, 'weight_class_0': 0.9243951193076874, 'weight_class_1': 2.6106146897499105, 'weight_class_2': 7.7440056262284935}. Best is trial 6 with value: 0.9497340972525816.

Best trial: 6. Best value: 0.949734:  15%|████████████████████▉                                                                                                                   | 77/500 [02:43<13:29,  1.91s/it]

[I 2026-07-08 16:19:42,035] Trial 77 finished with value: 0.9480472983212931 and parameters: {'C': 6.473834350369235, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0002771366584763382, 'max_iter': 1306, 'weight_class_0': 1.6989920023096674, 'weight_class_1': 5.418791701921953, 'weight_class_2': 4.378128729416105}. Best is trial 6 with value: 0.9497340972525816.

Best trial: 6. Best value: 0.949734:  16%|█████████████████████▏                                                                                                                  | 78/500 [02:44<10:02,  1.43s/it]

[I 2026-07-08 16:19:42,544] Trial 78 finished with value: 0.9491245208018733 and parameters: {'C': 0.5744706373955152, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00026181029851672123, 'max_iter': 1281, 'weight_class_0': 0.7321353214834314, 'weight_class_1': 2.5772815475466757, 'weight_class_2': 4.2788735597487575}. Best is trial 6 with value: 0.9497340972525816.

Best trial: 6. Best value: 0.949734:  16%|█████████████████████▍                                                                                                                  | 79/500 [02:45<10:49,  1.54s/it]

[I 2026-07-08 16:19:44,396] Trial 85 pruned.

Best trial: 6. Best value: 0.949734:  16%|█████████████████████▊                                                                                                                  | 80/500 [02:47<10:52,  1.55s/it]

[I 2026-07-08 16:19:45,895] Trial 86 pruned.

Best trial: 6. Best value: 0.949734:  16%|██████████████████████                                                                                                                  | 81/500 [02:49<12:08,  1.74s/it]

[I 2026-07-08 16:19:48,144] Trial 71 finished with value: 0.9490033710794264 and parameters: {'C': 4.757493750985622, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00013707330096995627, 'max_iter': 2743, 'weight_class_0': 1.0008472290026, 'weight_class_1': 5.1503486707051715, 'weight_class_2': 9.562430856135983}. Best is trial 6 with value: 0.9497340972525816.

Best trial: 6. Best value: 0.949734:  16%|██████████████████████▎                                                                                                                 | 82/500 [02:51<12:02,  1.73s/it]

[I 2026-07-08 16:19:49,642] Trial 89 pruned.

Best trial: 6. Best value: 0.949734:  17%|██████████████████████▌                                                                                                                 | 83/500 [02:56<19:35,  2.82s/it]

[I 2026-07-08 16:19:54,973] Trial 88 pruned.

Best trial: 79. Best value: 0.949744:  17%|██████████████████████▋                                                                                                                | 84/500 [02:58<17:05,  2.47s/it]

[I 2026-07-08 16:19:56,740] Trial 79 finished with value: 0.949743679892439 and parameters: {'C': 0.5106816551912102, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0011588721043578087, 'max_iter': 2733, 'weight_class_0': 0.7261320502846351, 'weight_class_1': 5.533416947672339, 'weight_class_2': 4.556779581345758}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  17%|██████████████████████▉                                                                                                                | 85/500 [02:59<14:49,  2.14s/it]

[I 2026-07-08 16:19:58,231] Trial 83 finished with value: 0.9488393657679917 and parameters: {'C': 0.902973632442869, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0017280873800383817, 'max_iter': 1792, 'weight_class_0': 0.669177992624119, 'weight_class_1': 6.746774009793154, 'weight_class_2': 7.568805964808054}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  17%|███████████████████████▏                                                                                                               | 86/500 [03:00<11:11,  1.62s/it]

[I 2026-07-08 16:19:58,586] Trial 80 finished with value: 0.9489935304913777 and parameters: {'C': 0.6539597831270809, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.001057491295950258, 'max_iter': 1781, 'weight_class_0': 0.6810137209115648, 'weight_class_1': 2.243581267405174, 'weight_class_2': 4.229826097382691}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  17%|███████████████████████▍                                                                                                               | 87/500 [03:02<11:49,  1.72s/it]

[I 2026-07-08 16:20:00,380] Trial 81 finished with value: 0.9497246438447169 and parameters: {'C': 0.7606419683433738, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0009822456877320923, 'max_iter': 2634, 'weight_class_0': 0.7005959697503108, 'weight_class_1': 6.417167416228063, 'weight_class_2': 4.3728519092840195}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  18%|███████████████████████▊                                                                                                               | 88/500 [03:02<08:50,  1.29s/it]

[I 2026-07-08 16:20:00,840] Trial 82 finished with value: 0.9490765672061908 and parameters: {'C': 0.18237040991959272, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0009884779645345984, 'max_iter': 2744, 'weight_class_0': 0.7188437130331182, 'weight_class_1': 5.402218183496344, 'weight_class_2': 7.523049799016214}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  18%|████████████████████████                                                                                                               | 89/500 [03:05<13:38,  1.99s/it]

[I 2026-07-08 16:20:04,399] Trial 87 finished with value: 0.9492653376062679 and parameters: {'C': 8.849360294299311, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0022131711516437157, 'max_iter': 2661, 'weight_class_0': 0.6634357300509318, 'weight_class_1': 6.879722997817996, 'weight_class_2': 4.4126326295142455}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  18%|████████████████████████▎                                                                                                              | 90/500 [03:08<15:01,  2.20s/it]

[I 2026-07-08 16:20:07,152] Trial 91 finished with value: 0.9482863938216868 and parameters: {'C': 0.1748343774914688, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0037670412134134094, 'max_iter': 1791, 'weight_class_0': 0.748265997271833, 'weight_class_1': 3.0056459834254476, 'weight_class_2': 6.7719753631873045}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  18%|████████████████████████▌                                                                                                              | 91/500 [03:13<20:20,  2.99s/it]

[I 2026-07-08 16:20:11,961] Trial 97 pruned.

Best trial: 79. Best value: 0.949744:  18%|████████████████████████▊                                                                                                              | 92/500 [03:14<16:03,  2.36s/it]

[I 2026-07-08 16:20:12,816] Trial 96 pruned.

Best trial: 79. Best value: 0.949744:  19%|█████████████████████████                                                                                                              | 93/500 [03:15<12:24,  1.83s/it]

[I 2026-07-08 16:20:13,392] Trial 99 pruned.
[I 2026-07-08 16:20:13,500] Trial 90 pruned.

Best trial: 79. Best value: 0.949744:  19%|█████████████████████████▋                                                                                                             | 95/500 [03:15<06:30,  1.04it/s]

[I 2026-07-08 16:20:13,505] Trial 98 pruned.

Best trial: 79. Best value: 0.949744:  19%|█████████████████████████▉                                                                                                             | 96/500 [03:19<13:53,  2.06s/it]

[I 2026-07-08 16:20:18,192] Trial 100 pruned.

Best trial: 79. Best value: 0.949744:  19%|██████████████████████████▏                                                                                                            | 97/500 [03:20<11:19,  1.69s/it]

[I 2026-07-08 16:20:19,139] Trial 95 finished with value: 0.947877949507253 and parameters: {'C': 0.17988226666195806, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0016615607375374884, 'max_iter': 2313, 'weight_class_0': 1.5787212830297088, 'weight_class_1': 3.195788169754407, 'weight_class_2': 6.644536484187308}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  20%|██████████████████████████▍                                                                                                            | 98/500 [03:21<09:32,  1.42s/it]

[I 2026-07-08 16:20:19,983] Trial 84 finished with value: 0.9495885462570284 and parameters: {'C': 0.7437830233540458, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00016161449418356676, 'max_iter': 2756, 'weight_class_0': 0.6657800753919548, 'weight_class_1': 6.424252707483125, 'weight_class_2': 4.26442809238046}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  20%|██████████████████████████▋                                                                                                            | 99/500 [03:22<08:45,  1.31s/it]

[I 2026-07-08 16:20:21,059] Trial 101 pruned.

Best trial: 79. Best value: 0.949744:  20%|██████████████████████████▊                                                                                                           | 100/500 [03:29<19:38,  2.95s/it]

[I 2026-07-08 16:20:27,769] Trial 106 pruned.

Best trial: 79. Best value: 0.949744:  20%|███████████████████████████▎                                                                                                          | 102/500 [03:29<08:41,  1.31s/it]

[I 2026-07-08 16:20:28,235] Trial 103 pruned.
[I 2026-07-08 16:20:28,289] Trial 102 pruned.

Best trial: 79. Best value: 0.949744:  21%|███████████████████████████▌                                                                                                          | 103/500 [03:30<08:03,  1.22s/it]

[I 2026-07-08 16:20:29,268] Trial 92 finished with value: 0.9487717037185025 and parameters: {'C': 0.20729055504055577, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0001632595199820403, 'max_iter': 1801, 'weight_class_0': 0.7510249554810411, 'weight_class_1': 3.057795172713214, 'weight_class_2': 6.94391946741896}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  21%|███████████████████████████▊                                                                                                          | 104/500 [03:34<11:47,  1.79s/it]

[I 2026-07-08 16:20:32,672] Trial 93 finished with value: 0.9487362564637746 and parameters: {'C': 0.16736723240207915, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00015935180972091796, 'max_iter': 1766, 'weight_class_0': 0.6992569310401427, 'weight_class_1': 3.105606899693011, 'weight_class_2': 6.868982162949722}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  21%|████████████████████████████▏                                                                                                         | 105/500 [03:38<15:44,  2.39s/it]

[I 2026-07-08 16:20:36,631] Trial 105 finished with value: 0.9490159778186765 and parameters: {'C': 0.06701669333627587, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0014415720649859102, 'max_iter': 3271, 'weight_class_0': 1.056694001867448, 'weight_class_1': 6.116273203010271, 'weight_class_2': 3.764589912926745}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  21%|████████████████████████████▍                                                                                                         | 106/500 [03:38<12:01,  1.83s/it]

[I 2026-07-08 16:20:37,035] Trial 94 finished with value: 0.9488458951096119 and parameters: {'C': 0.19637995195868174, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00015669324148700057, 'max_iter': 1759, 'weight_class_0': 1.0488655050263724, 'weight_class_1': 3.0722565891244913, 'weight_class_2': 6.730635867063242}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  21%|████████████████████████████▋                                                                                                         | 107/500 [03:38<09:22,  1.43s/it]

[I 2026-07-08 16:20:37,459] Trial 104 finished with value: 0.949004858563611 and parameters: {'C': 0.05682693997809847, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0014710963077307529, 'max_iter': 3262, 'weight_class_0': 1.0837601661716634, 'weight_class_1': 5.935827453279874, 'weight_class_2': 3.8821616593256416}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  22%|████████████████████████████▉                                                                                                         | 108/500 [03:39<07:34,  1.16s/it]

[I 2026-07-08 16:20:37,993] Trial 109 pruned.

Best trial: 79. Best value: 0.949744:  22%|█████████████████████████████▏                                                                                                        | 109/500 [03:44<15:03,  2.31s/it]

[I 2026-07-08 16:20:43,055] Trial 107 finished with value: 0.9487764914882524 and parameters: {'C': 0.35636245240538, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0013571607231432049, 'max_iter': 2605, 'weight_class_0': 0.7972456300051769, 'weight_class_1': 5.993136906809635, 'weight_class_2': 2.380498509448365}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  22%|█████████████████████████████▍                                                                                                        | 110/500 [03:45<11:58,  1.84s/it]

[I 2026-07-08 16:20:43,636] Trial 111 pruned.

Best trial: 79. Best value: 0.949744:  22%|█████████████████████████████▋                                                                                                        | 111/500 [03:46<10:21,  1.60s/it]

[I 2026-07-08 16:20:44,835] Trial 113 pruned.

Best trial: 79. Best value: 0.949744:  22%|██████████████████████████████                                                                                                        | 112/500 [03:47<09:02,  1.40s/it]

[I 2026-07-08 16:20:45,707] Trial 108 finished with value: 0.9485212862669942 and parameters: {'C': 9.626845114797256, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0007836527994515372, 'max_iter': 2618, 'weight_class_0': 1.0880774120166676, 'weight_class_1': 5.917429930503819, 'weight_class_2': 2.6378889229997173}. Best is trial 79 with value: 0.949743679892439.
[I 2026-07-08 16:20:45,854] Trial 110 finished with value: 0.9495893557665646 and parameters: {'C': 0.45998454778470343, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.002271656578907869, 'max_iter': 2617, 'weight_class_0': 0.7756821023404237, 'weight_class_1': 6.05801477999733, 'weight_class_2': 3.910547619801116}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  23%|██████████████████████████████▌                                                                                                       | 114/500 [03:50<10:36,  1.65s/it]

[I 2026-07-08 16:20:49,021] Trial 115 pruned.

Best trial: 79. Best value: 0.949744:  23%|██████████████████████████████▊                                                                                                       | 115/500 [03:55<16:17,  2.54s/it]

[I 2026-07-08 16:20:53,656] Trial 119 pruned.

Best trial: 79. Best value: 0.949744:  23%|███████████████████████████████                                                                                                       | 116/500 [03:57<16:44,  2.61s/it]

[I 2026-07-08 16:20:56,343] Trial 112 finished with value: 0.9494654928704094 and parameters: {'C': 1.8025920557860635, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0007901421984695909, 'max_iter': 3260, 'weight_class_0': 1.0152462318161373, 'weight_class_1': 6.439540440914547, 'weight_class_2': 4.7133369603415325}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  23%|███████████████████████████████▎                                                                                                      | 117/500 [04:00<16:48,  2.63s/it]

[I 2026-07-08 16:20:59,073] Trial 114 finished with value: 0.9490298539119347 and parameters: {'C': 8.996254490830433, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00023365426663533967, 'max_iter': 2895, 'weight_class_0': 1.0799603273776721, 'weight_class_1': 6.164765853874954, 'weight_class_2': 3.73026712825015}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  24%|███████████████████████████████▌                                                                                                      | 118/500 [04:04<20:02,  3.15s/it]

[I 2026-07-08 16:21:03,362] Trial 117 finished with value: 0.9494712689043835 and parameters: {'C': 0.4475585940900059, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0008502317765922366, 'max_iter': 3230, 'weight_class_0': 0.791341280585964, 'weight_class_1': 6.072227036915453, 'weight_class_2': 3.666485909469007}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  24%|███████████████████████████████▉                                                                                                      | 119/500 [04:05<14:46,  2.33s/it]

[I 2026-07-08 16:21:03,737] Trial 118 finished with value: 0.9493511755510025 and parameters: {'C': 0.43808167832777584, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.000893134388042185, 'max_iter': 2887, 'weight_class_0': 0.5770805423909312, 'weight_class_1': 6.141214092866002, 'weight_class_2': 4.836151316573351}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  24%|████████████████████████████████▏                                                                                                     | 120/500 [04:05<11:02,  1.74s/it]

[I 2026-07-08 16:21:04,151] Trial 116 finished with value: 0.9495007176904489 and parameters: {'C': 0.3419764913863816, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0007582439783157536, 'max_iter': 2914, 'weight_class_0': 0.7870530373928678, 'weight_class_1': 6.49792634767522, 'weight_class_2': 3.8772464974946375}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  24%|████████████████████████████████▍                                                                                                     | 121/500 [04:08<12:38,  2.00s/it]

[I 2026-07-08 16:21:06,876] Trial 123 finished with value: 0.9497420596010298 and parameters: {'C': 0.008668274391346834, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0011901055116358963, 'max_iter': 2901, 'weight_class_0': 0.5876143558574827, 'weight_class_1': 4.989882667657065, 'weight_class_2': 3.689224169826673}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  24%|████████████████████████████████▋                                                                                                     | 122/500 [04:08<09:50,  1.56s/it]

[I 2026-07-08 16:21:07,324] Trial 125 finished with value: 0.9495558048129255 and parameters: {'C': 0.8648581587197868, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.004478188228536552, 'max_iter': 2142, 'weight_class_0': 0.632056179328915, 'weight_class_1': 5.186804536754963, 'weight_class_2': 4.747307726000221}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  25%|████████████████████████████████▉                                                                                                     | 123/500 [04:09<07:24,  1.18s/it]

[I 2026-07-08 16:21:07,596] Trial 121 finished with value: 0.9496935693435103 and parameters: {'C': 1.0602122216372871, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0012789889765120106, 'max_iter': 2859, 'weight_class_0': 0.5870739514562652, 'weight_class_1': 5.042031069299721, 'weight_class_2': 3.0977974315166614}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  25%|█████████████████████████████████▏                                                                                                    | 124/500 [04:10<07:00,  1.12s/it]

[I 2026-07-08 16:21:08,582] Trial 120 finished with value: 0.9482795368603076 and parameters: {'C': 0.9953310723288665, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0021641730756578686, 'max_iter': 2184, 'weight_class_0': 0.5730813969363079, 'weight_class_1': 5.092181615745958, 'weight_class_2': 1.8411742708902283}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  25%|█████████████████████████████████▌                                                                                                    | 125/500 [04:12<08:35,  1.37s/it]

[I 2026-07-08 16:21:10,633] Trial 122 finished with value: 0.9497356835915403 and parameters: {'C': 0.04623506434553715, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00023850016382732928, 'max_iter': 2896, 'weight_class_0': 0.5804818793516745, 'weight_class_1': 4.947095102223409, 'weight_class_2': 3.6541751790823365}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  25%|█████████████████████████████████▊                                                                                                    | 126/500 [04:13<09:35,  1.54s/it]

[I 2026-07-08 16:21:12,469] Trial 124 finished with value: 0.9494821951598077 and parameters: {'C': 0.918617545161484, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0012147094082617953, 'max_iter': 2902, 'weight_class_0': 0.5701432006248397, 'weight_class_1': 4.949945775751389, 'weight_class_2': 4.842601080141314}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  25%|██████████████████████████████████                                                                                                    | 127/500 [04:16<11:47,  1.90s/it]

[I 2026-07-08 16:21:15,224] Trial 127 finished with value: 0.9497186179204509 and parameters: {'C': 2.061956761238067, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.004319601925595018, 'max_iter': 2983, 'weight_class_0': 0.6313091882803332, 'weight_class_1': 4.914362740150858, 'weight_class_2': 3.741687494061098}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  26%|██████████████████████████████████▎                                                                                                   | 128/500 [04:20<15:11,  2.45s/it]

[I 2026-07-08 16:21:19,029] Trial 126 finished with value: 0.9496848187656223 and parameters: {'C': 0.013764843714684982, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0012031151426585346, 'max_iter': 2178, 'weight_class_0': 0.5792411791816577, 'weight_class_1': 4.899316160053719, 'weight_class_2': 3.776158524068331}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  26%|██████████████████████████████████▌                                                                                                   | 129/500 [04:20<11:07,  1.80s/it]

[I 2026-07-08 16:21:19,301] Trial 134 pruned.

Best trial: 79. Best value: 0.949744:  26%|██████████████████████████████████▊                                                                                                   | 130/500 [04:21<09:16,  1.50s/it]

[I 2026-07-08 16:21:20,116] Trial 135 pruned.

Best trial: 79. Best value: 0.949744:  26%|███████████████████████████████████                                                                                                   | 131/500 [04:22<07:17,  1.19s/it]

[I 2026-07-08 16:21:20,477] Trial 131 pruned.

Best trial: 79. Best value: 0.949744:  26%|███████████████████████████████████▍                                                                                                  | 132/500 [04:22<06:14,  1.02s/it]

[I 2026-07-08 16:21:21,197] Trial 136 pruned.

Best trial: 79. Best value: 0.949744:  27%|███████████████████████████████████▋                                                                                                  | 133/500 [04:24<07:54,  1.29s/it]

[I 2026-07-08 16:21:23,081] Trial 133 pruned.
[I 2026-07-08 16:21:23,166] Trial 132 pruned.

Best trial: 79. Best value: 0.949744:  27%|████████████████████████████████████▏                                                                                                 | 135/500 [04:29<12:46,  2.10s/it]

[I 2026-07-08 16:21:28,082] Trial 128 finished with value: 0.9487746140483972 and parameters: {'C': 0.9776139615318523, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00022012181566564846, 'max_iter': 3020, 'weight_class_0': 0.4042075735720608, 'weight_class_1': 5.014510373001562, 'weight_class_2': 3.3853804443354893}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  27%|████████████████████████████████████▍                                                                                                 | 136/500 [04:30<10:10,  1.68s/it]

[I 2026-07-08 16:21:28,624] Trial 129 finished with value: 0.9495750853321384 and parameters: {'C': 1.0224072888431794, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.000544019154748716, 'max_iter': 2136, 'weight_class_0': 0.5699592507558132, 'weight_class_1': 5.023554451823426, 'weight_class_2': 4.833252000349379}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  27%|████████████████████████████████████▋                                                                                                 | 137/500 [04:30<08:16,  1.37s/it]

[I 2026-07-08 16:21:29,143] Trial 130 finished with value: 0.949652286380379 and parameters: {'C': 1.9037761726590419, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0006578917222644368, 'max_iter': 2978, 'weight_class_0': 0.5785768538189093, 'weight_class_1': 4.896386594174592, 'weight_class_2': 3.0591716742299284}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  28%|████████████████████████████████████▉                                                                                                 | 138/500 [04:31<06:29,  1.08s/it]

[I 2026-07-08 16:21:29,824] Trial 139 pruned.

Best trial: 79. Best value: 0.949744:  28%|█████████████████████████████████████▎                                                                                                | 139/500 [04:32<06:14,  1.04s/it]

[I 2026-07-08 16:21:30,606] Trial 141 pruned.

Best trial: 79. Best value: 0.949744:  28%|█████████████████████████████████████▌                                                                                                | 140/500 [04:32<04:59,  1.20it/s]

[I 2026-07-08 16:21:31,116] Trial 140 pruned.

Best trial: 79. Best value: 0.949744:  28%|█████████████████████████████████████▊                                                                                                | 141/500 [04:36<10:01,  1.68s/it]

[I 2026-07-08 16:21:34,692] Trial 145 pruned.

Best trial: 79. Best value: 0.949744:  28%|██████████████████████████████████████                                                                                                | 142/500 [04:37<08:33,  1.43s/it]

[I 2026-07-08 16:21:35,507] Trial 144 pruned.

Best trial: 79. Best value: 0.949744:  29%|██████████████████████████████████████▎                                                                                               | 143/500 [04:38<08:12,  1.38s/it]

[I 2026-07-08 16:21:36,812] Trial 137 finished with value: 0.9494703294193858 and parameters: {'C': 1.891110732469981, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0012462818178764368, 'max_iter': 3039, 'weight_class_0': 0.42812549480493167, 'weight_class_1': 4.6236219754161985, 'weight_class_2': 3.025139600638439}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  29%|██████████████████████████████████████▌                                                                                               | 144/500 [04:39<08:40,  1.46s/it]

[I 2026-07-08 16:21:38,356] Trial 142 finished with value: 0.9493460631750932 and parameters: {'C': 0.01901240770805243, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.006202458372710829, 'max_iter': 3176, 'weight_class_0': 0.41414892922768926, 'weight_class_1': 3.5981543356691885, 'weight_class_2': 3.2633244672060995}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  29%|██████████████████████████████████████▊                                                                                               | 145/500 [04:41<09:05,  1.54s/it]

[I 2026-07-08 16:21:40,218] Trial 146 pruned.

Best trial: 79. Best value: 0.949744:  29%|███████████████████████████████████████▏                                                                                              | 146/500 [04:42<07:12,  1.22s/it]

[I 2026-07-08 16:21:40,658] Trial 148 pruned.

Best trial: 79. Best value: 0.949744:  29%|███████████████████████████████████████▍                                                                                              | 147/500 [04:42<05:45,  1.02it/s]

[I 2026-07-08 16:21:41,093] Trial 147 pruned.

Best trial: 79. Best value: 0.949744:  30%|███████████████████████████████████████▋                                                                                              | 148/500 [04:43<05:10,  1.13it/s]

[I 2026-07-08 16:21:41,698] Trial 138 finished with value: 0.9496631954153495 and parameters: {'C': 0.006290068986751227, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.001263980572668774, 'max_iter': 3020, 'weight_class_0': 0.5992964755815913, 'weight_class_1': 4.773906559769689, 'weight_class_2': 3.101432185270365}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  30%|███████████████████████████████████████▉                                                                                              | 149/500 [04:47<10:30,  1.79s/it]

[I 2026-07-08 16:21:45,647] Trial 149 pruned.

Best trial: 79. Best value: 0.949744:  30%|████████████████████████████████████████▍                                                                                             | 151/500 [04:48<07:04,  1.22s/it]

[I 2026-07-08 16:21:47,100] Trial 151 pruned.
[I 2026-07-08 16:21:47,264] Trial 150 pruned.

Best trial: 79. Best value: 0.949744:  30%|████████████████████████████████████████▋                                                                                             | 152/500 [04:48<05:13,  1.11it/s]

[I 2026-07-08 16:21:47,378] Trial 143 finished with value: 0.949630847570847 and parameters: {'C': 0.03776470367621505, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0012338328775300291, 'max_iter': 3145, 'weight_class_0': 0.6427238117369034, 'weight_class_1': 4.5126817512104065, 'weight_class_2': 3.291241104850059}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  31%|█████████████████████████████████████████                                                                                             | 153/500 [04:50<05:41,  1.02it/s]

[I 2026-07-08 16:21:48,599] Trial 152 pruned.

Best trial: 79. Best value: 0.949744:  31%|█████████████████████████████████████████▎                                                                                            | 154/500 [04:54<11:04,  1.92s/it]

[I 2026-07-08 16:21:52,688] Trial 154 pruned.
[I 2026-07-08 16:21:52,698] Trial 153 pruned.

Best trial: 79. Best value: 0.949744:  31%|█████████████████████████████████████████▊                                                                                            | 156/500 [04:58<11:18,  1.97s/it]

[I 2026-07-08 16:21:56,605] Trial 155 pruned.

Best trial: 79. Best value: 0.949744:  31%|██████████████████████████████████████████                                                                                            | 157/500 [04:59<10:57,  1.92s/it]

[I 2026-07-08 16:21:58,516] Trial 157 pruned.

Best trial: 79. Best value: 0.949744:  32%|██████████████████████████████████████████▎                                                                                           | 158/500 [05:05<16:08,  2.83s/it]

[I 2026-07-08 16:22:03,830] Trial 163 pruned.

Best trial: 79. Best value: 0.949744:  32%|██████████████████████████████████████████▌                                                                                           | 159/500 [05:07<14:54,  2.62s/it]

[I 2026-07-08 16:22:05,995] Trial 164 pruned.

Best trial: 79. Best value: 0.949744:  32%|██████████████████████████████████████████▉                                                                                           | 160/500 [05:08<13:03,  2.31s/it]

[I 2026-07-08 16:22:07,457] Trial 156 finished with value: 0.9493154726677453 and parameters: {'C': 2.666941071206156, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0009639087904611966, 'max_iter': 2833, 'weight_class_0': 0.5279296093001783, 'weight_class_1': 4.130992375794765, 'weight_class_2': 5.041737107648202}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  32%|███████████████████████████████████████████▏                                                                                          | 161/500 [05:10<11:03,  1.96s/it]

[I 2026-07-08 16:22:08,577] Trial 158 finished with value: 0.9495547041400798 and parameters: {'C': 0.0019080348383879512, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0009523140532491629, 'max_iter': 2843, 'weight_class_0': 0.6457665304375545, 'weight_class_1': 4.408853039834698, 'weight_class_2': 4.905924634889029}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  32%|███████████████████████████████████████████▍                                                                                          | 162/500 [05:10<08:38,  1.53s/it]

[I 2026-07-08 16:22:09,084] Trial 159 finished with value: 0.9495606389740928 and parameters: {'C': 0.005659157336809046, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.000985491410788563, 'max_iter': 2818, 'weight_class_0': 0.6563698392642773, 'weight_class_1': 4.311325813941684, 'weight_class_2': 5.1699452018416405}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  33%|███████████████████████████████████████████▋                                                                                          | 163/500 [05:12<08:54,  1.59s/it]

[I 2026-07-08 16:22:10,752] Trial 165 pruned.

Best trial: 79. Best value: 0.949744:  33%|███████████████████████████████████████████▉                                                                                          | 164/500 [05:13<07:56,  1.42s/it]

[I 2026-07-08 16:22:11,783] Trial 160 finished with value: 0.9487814741110434 and parameters: {'C': 0.005433641244074612, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0010012307167158473, 'max_iter': 2817, 'weight_class_0': 0.5214271953655644, 'weight_class_1': 4.317723634505261, 'weight_class_2': 5.7211380186991345}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  33%|███████████████████████████████████████████▉                                                                                          | 164/500 [05:14<07:56,  1.42s/it]

[I 2026-07-08 16:22:12,692] Trial 161 finished with value: 0.9491793803773924 and parameters: {'C': 0.004548181071402922, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0009648340516412923, 'max_iter': 2667, 'weight_class_0': 0.5251293600876629, 'weight_class_1': 4.458854831823618, 'weight_class_2': 5.171046562812981}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  33%|████████████████████████████████████████████▍                                                                                         | 166/500 [05:16<08:48,  1.58s/it]

[I 2026-07-08 16:22:15,059] Trial 162 finished with value: 0.9495852045699866 and parameters: {'C': 3.4532714450475512, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0009478756493203444, 'max_iter': 2677, 'weight_class_0': 0.6422369453324545, 'weight_class_1': 5.363954392895423, 'weight_class_2': 5.04956226751068}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  33%|████████████████████████████████████████████▊                                                                                         | 167/500 [05:16<06:51,  1.24s/it]

[I 2026-07-08 16:22:15,428] Trial 168 pruned.

Best trial: 79. Best value: 0.949744:  34%|█████████████████████████████████████████████▎                                                                                        | 169/500 [05:22<10:00,  1.81s/it]

[I 2026-07-08 16:22:21,053] Trial 166 finished with value: 0.9493677473750705 and parameters: {'C': 0.005503198319352388, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0005983433628719625, 'max_iter': 3390, 'weight_class_0': 0.6605105452687237, 'weight_class_1': 5.254406543703696, 'weight_class_2': 5.8685339018930245}. Best is trial 79 with value: 0.949743679892439.
[I 2026-07-08 16:22:21,068] Trial 169 pruned.

Best trial: 79. Best value: 0.949744:  34%|█████████████████████████████████████████████▌                                                                                        | 170/500 [05:23<08:13,  1.50s/it]

[I 2026-07-08 16:22:21,882] Trial 170 pruned.

Best trial: 79. Best value: 0.949744:  34%|█████████████████████████████████████████████▊                                                                                        | 171/500 [05:25<08:26,  1.54s/it]

[I 2026-07-08 16:22:23,515] Trial 167 finished with value: 0.9493724832370919 and parameters: {'C': 0.003933843773838364, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.001653599290831828, 'max_iter': 2730, 'weight_class_0': 0.6537103586649119, 'weight_class_1': 5.263610152417917, 'weight_class_2': 5.70964625376626}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  34%|██████████████████████████████████████████████                                                                                        | 172/500 [05:27<09:25,  1.73s/it]

[I 2026-07-08 16:22:25,646] Trial 172 pruned.

[I 2026-07-08 16:22:26,734] Trial 174 pruned.

Best trial: 79. Best value: 0.949744:  35%|██████████████████████████████████████████████▋                                                                                       | 174/500 [05:28<06:15,  1.15s/it]

[I 2026-07-08 16:22:26,919] Trial 173 pruned.

Best trial: 79. Best value: 0.949744:  35%|██████████████████████████████████████████████▉                                                                                       | 175/500 [05:29<05:32,  1.02s/it]

[I 2026-07-08 16:22:27,741] Trial 176 pruned.

Best trial: 79. Best value: 0.949744:  35%|███████████████████████████████████████████████▏                                                                                      | 176/500 [05:35<13:28,  2.49s/it]

[I 2026-07-08 16:22:33,730] Trial 171 finished with value: 0.9485600878597898 and parameters: {'C': 0.7182063148374782, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0005890327858678821, 'max_iter': 3334, 'weight_class_0': 0.6504530944112047, 'weight_class_1': 7.123663879602731, 'weight_class_2': 3.5686127529239537}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  35%|███████████████████████████████████████████████▍                                                                                      | 177/500 [05:36<11:45,  2.18s/it]

[I 2026-07-08 16:22:35,170] Trial 182 pruned.

Best trial: 79. Best value: 0.949744:  36%|███████████████████████████████████████████████▋                                                                                      | 178/500 [05:39<12:53,  2.40s/it]

[I 2026-07-08 16:22:37,918] Trial 183 pruned.

Best trial: 79. Best value: 0.949744:  36%|███████████████████████████████████████████████▉                                                                                      | 179/500 [05:40<10:44,  2.01s/it]

[I 2026-07-08 16:22:39,058] Trial 180 pruned.

Best trial: 79. Best value: 0.949744:  36%|████████████████████████████████████████████████▏                                                                                     | 180/500 [05:42<10:55,  2.05s/it]

[I 2026-07-08 16:22:41,210] Trial 177 finished with value: 0.9495023149015763 and parameters: {'C': 0.0034284010351860717, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0010955735858245168, 'max_iter': 2688, 'weight_class_0': 0.7277344681725038, 'weight_class_1': 6.909009356186315, 'weight_class_2': 5.902668918391728}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  36%|████████████████████████████████████████████████▌                                                                                     | 181/500 [05:46<13:06,  2.46s/it]

[I 2026-07-08 16:22:44,737] Trial 178 finished with value: 0.9495445210032573 and parameters: {'C': 0.002680791482248302, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00044388089865447095, 'max_iter': 2716, 'weight_class_0': 0.7606616702553993, 'weight_class_1': 6.673930222654002, 'weight_class_2': 6.035355885131142}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  36%|████████████████████████████████████████████████▊                                                                                     | 182/500 [05:47<10:42,  2.02s/it]

[I 2026-07-08 16:22:45,653] Trial 175 pruned.

Best trial: 79. Best value: 0.949744:  37%|█████████████████████████████████████████████████                                                                                     | 183/500 [05:48<10:20,  1.96s/it]

[I 2026-07-08 16:22:47,540] Trial 179 finished with value: 0.9493907135914673 and parameters: {'C': 0.0074390242640613126, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0011250476469514266, 'max_iter': 2447, 'weight_class_0': 0.7341834869290509, 'weight_class_1': 6.7020355233410545, 'weight_class_2': 3.4910082387376016}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  37%|█████████████████████████████████████████████████▎                                                                                    | 184/500 [05:50<08:59,  1.71s/it]

[I 2026-07-08 16:22:48,668] Trial 181 finished with value: 0.9494835349406543 and parameters: {'C': 0.6463159096897108, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00045457688130343636, 'max_iter': 2461, 'weight_class_0': 0.7393883460407288, 'weight_class_1': 4.930459319740459, 'weight_class_2': 3.47746943684063}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  37%|█████████████████████████████████████████████████▌                                                                                    | 185/500 [05:55<13:58,  2.66s/it]

[I 2026-07-08 16:22:53,512] Trial 189 pruned.

Best trial: 79. Best value: 0.949744:  37%|█████████████████████████████████████████████████▊                                                                                    | 186/500 [05:56<11:48,  2.26s/it]

[I 2026-07-08 16:22:54,804] Trial 185 finished with value: 0.9496433634301351 and parameters: {'C': 0.00019870683190022882, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0008770579066089308, 'max_iter': 2965, 'weight_class_0': 0.7298715321060812, 'weight_class_1': 4.805091812496598, 'weight_class_2': 4.438475306130194}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  37%|██████████████████████████████████████████████████                                                                                    | 187/500 [05:57<09:33,  1.83s/it]

[I 2026-07-08 16:22:55,618] Trial 190 pruned.

Best trial: 79. Best value: 0.949744:  38%|██████████████████████████████████████████████████▍                                                                                   | 188/500 [05:57<07:48,  1.50s/it]

[I 2026-07-08 16:22:56,282] Trial 186 finished with value: 0.9496502724594886 and parameters: {'C': 0.0003204461476813214, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0008622937640862015, 'max_iter': 2555, 'weight_class_0': 0.7397138698724801, 'weight_class_1': 4.866099709114398, 'weight_class_2': 4.469034719601563}. Best is trial 79 with value: 0.949743679892439.

Best trial: 79. Best value: 0.949744:  38%|██████████████████████████████████████████████████▋                                                                                   | 189/500 [06:02<12:55,  2.49s/it]

[I 2026-07-08 16:23:01,244] Trial 188 finished with value: 0.948623341720532 and parameters: {'C': 0.00019264945645800893, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0013473347901116009, 'max_iter': 2972, 'weight_class_0': 0.7376629936252321, 'weight_class_1': 4.95280609852353, 'weight_class_2': 2.83847028676956}. Best is trial 79 with value: 0.949743679892439.

[I 2026-07-08 16:23:01,550] Trial 193 pruned.
[I 2026-07-08 16:23:01,572] Trial 187 finished with value: 0.9496799358924456 and parameters: {'C': 0.0006511466487591821, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0009091325501114606, 'max_iter': 2530, 'weight_class_0': 0.7590885998570469, 'weight_class_1': 4.756357034370788, 'weight_class_2': 4.33515606643005}. Best is trial 79 with value: 0.949743679892439.

Best trial: 184. Best value: 0.949749:  38%|███████████████████████████████████████████████████                                                                                  | 192/500 [06:03<05:37,  1.09s/it]

[I 2026-07-08 16:23:01,621] Trial 184 finished with value: 0.9497490579269744 and parameters: {'C': 0.0003436212048875849, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00012059333600073268, 'max_iter': 2536, 'weight_class_0': 0.7480250833107795, 'weight_class_1': 4.952168573201663, 'weight_class_2': 4.431053072748499}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  39%|███████████████████████████████████████████████████▎                                                                                 | 193/500 [06:06<07:25,  1.45s/it]

[I 2026-07-08 16:23:04,518] Trial 195 pruned.
[I 2026-07-08 16:23:04,530] Trial 191 pruned.

Best trial: 184. Best value: 0.949749:  39%|███████████████████████████████████████████████████▊                                                                                 | 195/500 [06:13<11:47,  2.32s/it]

[I 2026-07-08 16:23:11,529] Trial 196 pruned.

Best trial: 184. Best value: 0.949749:  39%|████████████████████████████████████████████████████▏                                                                                | 196/500 [06:13<09:41,  1.91s/it]

[I 2026-07-08 16:23:12,201] Trial 197 pruned.

Best trial: 184. Best value: 0.949749:  39%|████████████████████████████████████████████████████▍                                                                                | 197/500 [06:14<08:56,  1.77s/it]

[I 2026-07-08 16:23:13,476] Trial 194 finished with value: 0.9496391991356485 and parameters: {'C': 1.4509416223779972, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0008428179435105069, 'max_iter': 2976, 'weight_class_0': 0.8204782373441075, 'weight_class_1': 4.8417425848478715, 'weight_class_2': 4.47183732918236}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  40%|████████████████████████████████████████████████████▋                                                                                | 198/500 [06:16<08:14,  1.64s/it]

[I 2026-07-08 16:23:14,683] Trial 198 finished with value: 0.9487611179806137 and parameters: {'C': 1.3631640553499438, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.004838503786401864, 'max_iter': 2838, 'weight_class_0': 0.46392576816340075, 'weight_class_1': 3.8399372138387564, 'weight_class_2': 4.527289263642919}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  40%|████████████████████████████████████████████████████▉                                                                                | 199/500 [06:16<06:28,  1.29s/it]

[I 2026-07-08 16:23:14,923] Trial 199 finished with value: 0.9496679534440586 and parameters: {'C': 0.00031653589068739797, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.005016743339402116, 'max_iter': 2545, 'weight_class_0': 0.8456540094333513, 'weight_class_1': 5.707175134540836, 'weight_class_2': 4.364700284415245}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  40%|█████████████████████████████████████████████████████▏                                                                               | 200/500 [06:17<05:37,  1.12s/it]

[I 2026-07-08 16:23:15,694] Trial 192 finished with value: 0.9497130386475423 and parameters: {'C': 0.0003457458680507999, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0005238454464018617, 'max_iter': 2976, 'weight_class_0': 0.8225647033624833, 'weight_class_1': 4.919627912940972, 'weight_class_2': 4.533680357079867}. Best is trial 184 with value: 0.9497490579269744.

[I 2026-07-08 16:23:28,499] Trial 201 finished with value: 0.9497173606382455 and parameters: {'C': 0.00027623030091544385, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0008644867012883611, 'max_iter': 2550, 'weight_class_0': 0.8511697845167641, 'weight_class_1': 5.623847370999475, 'weight_class_2': 4.422242523844465}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  40%|█████████████████████████████████████████████████████▋                                                                               | 202/500 [06:30<15:56,  3.21s/it]

[I 2026-07-08 16:23:28,527] Trial 206 finished with value: 0.9493912131843253 and parameters: {'C': 0.0001468331906027102, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0008876465876228299, 'max_iter': 2541, 'weight_class_0': 0.5598495776418659, 'weight_class_1': 3.9297966223648992, 'weight_class_2': 3.819122590916389}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  41%|██████████████████████████████████████████████████████▎                                                                              | 204/500 [06:31<09:42,  1.97s/it]

[I 2026-07-08 16:23:30,333] Trial 207 finished with value: 0.9492579372990949 and parameters: {'C': 0.0001260612238627447, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0008392317127008182, 'max_iter': 2561, 'weight_class_0': 0.8243923656227622, 'weight_class_1': 3.9570320458673205, 'weight_class_2': 3.7604299519878777}. Best is trial 184 with value: 0.9497490579269744.
[I 2026-07-08 16:23:30,392] Trial 200 finished with value: 0.9496805531275976 and parameters: {'C': 0.000302114969754302, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0008478761698321996, 'max_iter': 3101, 'weight_class_0': 0.8388584205821514, 'weight_class_1': 5.685120576255283, 'weight_class_2': 4.586732352672938}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  41%|██████████████████████████████████████████████████████▌                                                                              | 205/500 [06:32<07:17,  1.48s/it]

[I 2026-07-08 16:23:30,760] Trial 208 finished with value: 0.9492866369027244 and parameters: {'C': 0.00011594472046004778, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0006515114607447454, 'max_iter': 2582, 'weight_class_0': 0.8282203032593064, 'weight_class_1': 4.024716463502384, 'weight_class_2': 3.7526033868482194}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  41%|██████████████████████████████████████████████████████▊                                                                              | 206/500 [06:33<07:34,  1.55s/it]

[I 2026-07-08 16:23:32,394] Trial 205 finished with value: 0.9495801720431215 and parameters: {'C': 0.00023325286839916064, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0008482471598317177, 'max_iter': 2572, 'weight_class_0': 0.8131749788701128, 'weight_class_1': 3.9448433518863766, 'weight_class_2': 4.178762461526272}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  41%|███████████████████████████████████████████████████████                                                                              | 207/500 [06:34<05:42,  1.17s/it]

[I 2026-07-08 16:23:32,791] Trial 210 finished with value: 0.9490534611579374 and parameters: {'C': 0.00019596915137987271, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.005734288608615355, 'max_iter': 2565, 'weight_class_0': 0.8599122009655581, 'weight_class_1': 5.779279663840868, 'weight_class_2': 3.654861587854579}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  42%|███████████████████████████████████████████████████████▎                                                                             | 208/500 [06:35<05:12,  1.07s/it]

[I 2026-07-08 16:23:33,393] Trial 204 finished with value: 0.9492440686861926 and parameters: {'C': 0.00018142991794886215, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0008867886252207856, 'max_iter': 2561, 'weight_class_0': 0.5758985318308603, 'weight_class_1': 4.032158540032263, 'weight_class_2': 4.144576028563649}. Best is trial 184 with value: 0.9497490579269744.
[I 2026-07-08 16:23:33,678] Trial 209 finished with value: 0.9491604404461427 and parameters: {'C': 0.0001849497343011113, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0008484663003891434, 'max_iter': 2586, 'weight_class_0': 0.8197556521633526, 'weight_class_1': 3.946098245079067, 'weight_class_2': 3.7611511364475168}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  42%|███████████████████████████████████████████████████████▊                                                                             | 210/500 [06:35<03:31,  1.37it/s]

[I 2026-07-08 16:23:34,288] Trial 211 finished with value: 0.9491636748399748 and parameters: {'C': 0.0005251321950840966, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0008281732071094921, 'max_iter': 2539, 'weight_class_0': 0.8286689707802808, 'weight_class_1': 3.959918974083211, 'weight_class_2': 3.859423577333794}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  42%|████████████████████████████████████████████████████████▏                                                                            | 211/500 [06:37<05:10,  1.08s/it]

[I 2026-07-08 16:23:36,398] Trial 203 finished with value: 0.9497224682258659 and parameters: {'C': 0.0002727589864110881, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00011335590533181056, 'max_iter': 2562, 'weight_class_0': 0.8246605761685941, 'weight_class_1': 5.641218978672588, 'weight_class_2': 4.267043527941205}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  42%|████████████████████████████████████████████████████████▍                                                                            | 212/500 [06:40<07:27,  1.55s/it]

[I 2026-07-08 16:23:39,336] Trial 202 finished with value: 0.9494895071868589 and parameters: {'C': 0.00040832675751379717, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00011709246695755416, 'max_iter': 2570, 'weight_class_0': 0.8122090707874013, 'weight_class_1': 3.771185903490162, 'weight_class_2': 4.0757647973617726}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  43%|████████████████████████████████████████████████████████▋                                                                            | 213/500 [06:42<08:09,  1.70s/it]

[I 2026-07-08 16:23:41,348] Trial 215 pruned.

Best trial: 184. Best value: 0.949749:  43%|████████████████████████████████████████████████████████▉                                                                            | 214/500 [06:44<07:58,  1.67s/it]

[I 2026-07-08 16:23:42,896] Trial 217 pruned.

Best trial: 184. Best value: 0.949749:  43%|█████████████████████████████████████████████████████████▏                                                                           | 215/500 [06:48<10:51,  2.29s/it]

[I 2026-07-08 16:23:46,756] Trial 212 finished with value: 0.9492384669247238 and parameters: {'C': 0.00019772085599496976, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0006709557584843114, 'max_iter': 2426, 'weight_class_0': 0.8501800507521908, 'weight_class_1': 5.817774736521547, 'weight_class_2': 3.7184790604112465}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  43%|█████████████████████████████████████████████████████████▍                                                                           | 216/500 [06:48<08:24,  1.78s/it]

[I 2026-07-08 16:23:47,314] Trial 216 finished with value: 0.9487242010547658 and parameters: {'C': 0.00018921977344277474, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0058778548317866795, 'max_iter': 3051, 'weight_class_0': 0.9189321082854915, 'weight_class_1': 5.7871602471251675, 'weight_class_2': 3.251710699283209}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  43%|█████████████████████████████████████████████████████████▋                                                                           | 217/500 [06:49<06:31,  1.38s/it]

[I 2026-07-08 16:23:47,794] Trial 213 finished with value: 0.9492100446855443 and parameters: {'C': 0.0004772862822267656, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0008584369130004311, 'max_iter': 2558, 'weight_class_0': 0.8516122123619234, 'weight_class_1': 5.852502244445303, 'weight_class_2': 3.699092056960148}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  44%|█████████████████████████████████████████████████████████▉                                                                           | 218/500 [06:50<06:52,  1.46s/it]

[I 2026-07-08 16:23:49,469] Trial 223 pruned.

Best trial: 184. Best value: 0.949749:  44%|██████████████████████████████████████████████████████████▎                                                                          | 219/500 [06:53<08:01,  1.71s/it]

[I 2026-07-08 16:23:51,635] Trial 219 pruned.

Best trial: 184. Best value: 0.949749:  44%|██████████████████████████████████████████████████████████▌                                                                          | 220/500 [06:59<14:11,  3.04s/it]

[I 2026-07-08 16:23:57,886] Trial 227 pruned.

Best trial: 184. Best value: 0.949749:  44%|██████████████████████████████████████████████████████████▊                                                                          | 221/500 [07:00<11:09,  2.40s/it]

[I 2026-07-08 16:23:58,664] Trial 214 finished with value: 0.9486675636786417 and parameters: {'C': 0.00021412094459415747, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0007667099698540794, 'max_iter': 3096, 'weight_class_0': 0.9521721085505068, 'weight_class_1': 5.754766305086071, 'weight_class_2': 3.221002850333022}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  44%|███████████████████████████████████████████████████████████                                                                          | 222/500 [07:01<08:48,  1.90s/it]

[I 2026-07-08 16:23:59,482] Trial 225 finished with value: 0.9493235256007371 and parameters: {'C': 0.000805662313197894, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.007963407066554939, 'max_iter': 3178, 'weight_class_0': 0.9414914202516881, 'weight_class_1': 4.688390602964023, 'weight_class_2': 4.553240244676427}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  45%|███████████████████████████████████████████████████████████▎                                                                         | 223/500 [07:02<08:31,  1.85s/it]

[I 2026-07-08 16:24:01,288] Trial 218 finished with value: 0.9487848846954341 and parameters: {'C': 0.0008037915911359753, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0007754497328893906, 'max_iter': 2397, 'weight_class_0': 0.9512646909204612, 'weight_class_1': 5.887135338256576, 'weight_class_2': 3.1281566104997256}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  45%|███████████████████████████████████████████████████████████▌                                                                         | 224/500 [07:04<08:58,  1.95s/it]

[I 2026-07-08 16:24:03,275] Trial 221 finished with value: 0.9490320649904052 and parameters: {'C': 0.0010801556668374643, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0007824804796568015, 'max_iter': 3082, 'weight_class_0': 0.9169846199708218, 'weight_class_1': 5.649843928691595, 'weight_class_2': 3.3299671605684407}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  45%|███████████████████████████████████████████████████████████▊                                                                         | 225/500 [07:05<07:35,  1.65s/it]

[I 2026-07-08 16:24:04,401] Trial 220 finished with value: 0.9489710108813613 and parameters: {'C': 0.0005019821966626675, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0007546883242581189, 'max_iter': 2425, 'weight_class_0': 0.9311700908852689, 'weight_class_1': 5.848801125501134, 'weight_class_2': 3.2458375094311624}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  45%|████████████████████████████████████████████████████████████                                                                         | 226/500 [07:13<15:43,  3.45s/it]

[I 2026-07-08 16:24:12,052] Trial 224 finished with value: 0.9489188622506436 and parameters: {'C': 0.0007147739122377444, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0007656774242076518, 'max_iter': 3178, 'weight_class_0': 0.9326318344281416, 'weight_class_1': 4.772573682828508, 'weight_class_2': 3.277994797756323}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  45%|████████████████████████████████████████████████████████████▍                                                                        | 227/500 [07:14<12:13,  2.69s/it]

[I 2026-07-08 16:24:12,977] Trial 222 finished with value: 0.9488104041869485 and parameters: {'C': 0.0007743514175786476, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00011576745649951482, 'max_iter': 2392, 'weight_class_0': 0.9363325541262092, 'weight_class_1': 5.821942842606159, 'weight_class_2': 3.079208411799213}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  46%|████████████████████████████████████████████████████████████▋                                                                        | 228/500 [07:16<11:54,  2.63s/it]

[I 2026-07-08 16:24:15,315] Trial 226 finished with value: 0.9494234140163899 and parameters: {'C': 0.0002732600210315452, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0007674069568120961, 'max_iter': 3089, 'weight_class_0': 0.956895507951837, 'weight_class_1': 4.658303771869178, 'weight_class_2': 4.451263335802966}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  46%|████████████████████████████████████████████████████████████▉                                                                        | 229/500 [07:17<08:49,  1.95s/it]

[I 2026-07-08 16:24:15,714] Trial 230 finished with value: 0.9493794618067902 and parameters: {'C': 0.00031021095688832693, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0018680306190727357, 'max_iter': 3193, 'weight_class_0': 0.9778977417923579, 'weight_class_1': 4.684172824721415, 'weight_class_2': 4.634407140439238}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  46%|█████████████████████████████████████████████████████████████▍                                                                       | 231/500 [07:17<04:50,  1.08s/it]

[I 2026-07-08 16:24:16,032] Trial 232 finished with value: 0.949605447223177 and parameters: {'C': 0.00029366518604465757, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.004973590278338228, 'max_iter': 2886, 'weight_class_0': 0.7417740068825216, 'weight_class_1': 5.175095293667688, 'weight_class_2': 4.569066198762684}. Best is trial 184 with value: 0.9497490579269744.
[I 2026-07-08 16:24:16,329] Trial 229 finished with value: 0.9494043812801343 and parameters: {'C': 0.00025628317979236275, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0007804720051992166, 'max_iter': 3170, 'weight_class_0': 0.976698002655351, 'weight_class_1': 4.631283839501829, 'weight_class_2': 4.528318194904048}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  46%|█████████████████████████████████████████████████████████████▋                                                                       | 232/500 [07:18<03:49,  1.17it/s]

[I 2026-07-08 16:24:16,610] Trial 233 pruned.

Best trial: 184. Best value: 0.949749:  47%|█████████████████████████████████████████████████████████████▉                                                                       | 233/500 [07:19<04:17,  1.04it/s]

[I 2026-07-08 16:24:17,885] Trial 228 finished with value: 0.949200779118143 and parameters: {'C': 0.0009106165163913622, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0007513565897871006, 'max_iter': 3178, 'weight_class_0': 1.006566188663427, 'weight_class_1': 4.6810930197221206, 'weight_class_2': 4.453404409073013}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  47%|██████████████████████████████████████████████████████████████▏                                                                      | 234/500 [07:20<03:55,  1.13it/s]

[I 2026-07-08 16:24:18,600] Trial 234 finished with value: 0.9488401502291204 and parameters: {'C': 9.522018899452907e-05, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.004912885545753375, 'max_iter': 2897, 'weight_class_0': 0.7167178308895044, 'weight_class_1': 5.056911776050817, 'weight_class_2': 4.475124792856779}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  47%|██████████████████████████████████████████████████████████████▌                                                                      | 235/500 [07:30<16:52,  3.82s/it]

[I 2026-07-08 16:24:29,252] Trial 231 finished with value: 0.949185882798431 and parameters: {'C': 9.220415026113585e-05, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0001003449679010218, 'max_iter': 3190, 'weight_class_0': 0.7195202668069489, 'weight_class_1': 4.8456178598640385, 'weight_class_2': 4.408667366338193}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  47%|██████████████████████████████████████████████████████████████▊                                                                      | 236/500 [07:32<14:12,  3.23s/it]

[I 2026-07-08 16:24:31,137] Trial 237 pruned.

Best trial: 184. Best value: 0.949749:  47%|███████████████████████████████████████████████████████████████                                                                      | 237/500 [07:34<11:47,  2.69s/it]

[I 2026-07-08 16:24:32,507] Trial 239 pruned.

[I 2026-07-08 16:24:34,289] Trial 241 finished with value: 0.9491141358094307 and parameters: {'C': 0.00034647238604465687, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.005077285995775448, 'max_iter': 2883, 'weight_class_0': 0.708782923802092, 'weight_class_1': 5.172398701302255, 'weight_class_2': 5.4364410707735225}. Best is trial 184 with value: 0.9497490579269744.
[I 2026-07-08 16:24:34,405] Trial 240 pruned.

Best trial: 184. Best value: 0.949749:  48%|███████████████████████████████████████████████████████████████▊                                                                     | 240/500 [07:36<06:08,  1.42s/it]

[I 2026-07-08 16:24:34,505] Trial 242 finished with value: 0.9488411003236192 and parameters: {'C': 8.579396480229158e-05, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0049228927439875884, 'max_iter': 2886, 'weight_class_0': 0.7315209953687151, 'weight_class_1': 5.148692537453212, 'weight_class_2': 4.089415131090627}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  48%|████████████████████████████████████████████████████████████████                                                                     | 241/500 [07:38<06:52,  1.59s/it]

[I 2026-07-08 16:24:36,949] Trial 235 finished with value: 0.9496499054072538 and parameters: {'C': 0.00029423794784436537, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00017981390382631768, 'max_iter': 2875, 'weight_class_0': 0.6965914980997074, 'weight_class_1': 5.188971786996452, 'weight_class_2': 4.554529074824224}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  48%|████████████████████████████████████████████████████████████████▎                                                                    | 242/500 [07:39<06:35,  1.53s/it]

[I 2026-07-08 16:24:38,326] Trial 236 finished with value: 0.949316750354704 and parameters: {'C': 0.0002793544993020579, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00013220252946329858, 'max_iter': 2891, 'weight_class_0': 0.7446035703958409, 'weight_class_1': 6.301790077241266, 'weight_class_2': 4.6680629316490565}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  49%|████████████████████████████████████████████████████████████████▋                                                                    | 243/500 [07:43<09:23,  2.19s/it]

[I 2026-07-08 16:24:42,255] Trial 248 pruned.

Best trial: 184. Best value: 0.949749:  49%|████████████████████████████████████████████████████████████████▉                                                                    | 244/500 [07:45<09:06,  2.14s/it]

[I 2026-07-08 16:24:44,170] Trial 244 finished with value: 0.9496636040094039 and parameters: {'C': 1.9684047136037346, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0010157465490815928, 'max_iter': 2777, 'weight_class_0': 0.7128542389297559, 'weight_class_1': 5.1544841871964735, 'weight_class_2': 4.066000234038605}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  49%|█████████████████████████████████████████████████████████████████▏                                                                   | 245/500 [07:46<07:56,  1.87s/it]

[I 2026-07-08 16:24:45,392] Trial 246 pruned.

Best trial: 184. Best value: 0.949749:  49%|█████████████████████████████████████████████████████████████████▍                                                                   | 246/500 [07:49<09:01,  2.13s/it]

[I 2026-07-08 16:24:48,212] Trial 238 finished with value: 0.9491990661949418 and parameters: {'C': 0.000276154379343396, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00012656710199058954, 'max_iter': 2884, 'weight_class_0': 0.7328891000506788, 'weight_class_1': 6.31215438754185, 'weight_class_2': 4.661251809313634}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  49%|█████████████████████████████████████████████████████████████████▋                                                                   | 247/500 [07:50<07:39,  1.82s/it]

[I 2026-07-08 16:24:49,313] Trial 247 finished with value: 0.9486665483180381 and parameters: {'C': 0.00029509751964299093, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.004900315112888526, 'max_iter': 2781, 'weight_class_0': 0.5895469367772992, 'weight_class_1': 5.163223526852362, 'weight_class_2': 3.947458755042657}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  50%|█████████████████████████████████████████████████████████████████▉                                                                   | 248/500 [07:55<11:08,  2.65s/it]

[I 2026-07-08 16:24:53,991] Trial 253 pruned.

Best trial: 184. Best value: 0.949749:  50%|██████████████████████████████████████████████████████████████████▏                                                                  | 249/500 [07:56<09:06,  2.18s/it]

[I 2026-07-08 16:24:55,030] Trial 245 finished with value: 0.9496864473074963 and parameters: {'C': 0.0002968765194746379, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00010793702315773062, 'max_iter': 2766, 'weight_class_0': 0.7575387804150111, 'weight_class_1': 5.305214979418916, 'weight_class_2': 4.122232384005411}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  50%|██████████████████████████████████████████████████████████████████▌                                                                  | 250/500 [08:00<10:46,  2.58s/it]

[I 2026-07-08 16:24:58,314] Trial 250 finished with value: 0.9495098858810624 and parameters: {'C': 2.1419697830478173, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0010026198694877977, 'max_iter': 2805, 'weight_class_0': 0.5964441038277098, 'weight_class_1': 6.306840080652741, 'weight_class_2': 4.012333979897998}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  50%|██████████████████████████████████████████████████████████████████▊                                                                  | 251/500 [08:03<12:12,  2.94s/it]

[I 2026-07-08 16:25:02,388] Trial 249 finished with value: 0.9495980611857382 and parameters: {'C': 2.030880712952828, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0009923539977215769, 'max_iter': 2774, 'weight_class_0': 0.8028747763783152, 'weight_class_1': 6.266705630310871, 'weight_class_2': 3.950432708232818}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  50%|███████████████████████████████████████████████████████████████████                                                                  | 252/500 [08:05<10:27,  2.53s/it]

[I 2026-07-08 16:25:03,732] Trial 243 finished with value: 0.9496690589836995 and parameters: {'C': 2.0364963351591774, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00010698877591723988, 'max_iter': 2774, 'weight_class_0': 0.709638330625692, 'weight_class_1': 5.257114858671094, 'weight_class_2': 4.153524254846595}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  51%|███████████████████████████████████████████████████████████████████▎                                                                 | 253/500 [08:13<17:37,  4.28s/it]

[I 2026-07-08 16:25:12,222] Trial 255 finished with value: 0.9496949042861429 and parameters: {'C': 2.086469304205534, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0009638790657295072, 'max_iter': 2778, 'weight_class_0': 0.5932967305540836, 'weight_class_1': 4.30148882459802, 'weight_class_2': 4.0076886281142645}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  51%|███████████████████████████████████████████████████████████████████▌                                                                 | 254/500 [08:14<13:02,  3.18s/it]

[I 2026-07-08 16:25:12,813] Trial 251 finished with value: 0.9494825855938924 and parameters: {'C': 1.989531494612285, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0001748579782144479, 'max_iter': 2743, 'weight_class_0': 0.5954768579422464, 'weight_class_1': 6.2544616951688035, 'weight_class_2': 4.017992261144338}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  51%|███████████████████████████████████████████████████████████████████▊                                                                 | 255/500 [08:15<10:10,  2.49s/it]

[I 2026-07-08 16:25:13,770] Trial 256 finished with value: 0.94955409221854 and parameters: {'C': 1.4986769724138653, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0009374802142924051, 'max_iter': 3024, 'weight_class_0': 0.7927223619378351, 'weight_class_1': 4.297565774307201, 'weight_class_2': 3.95574872037003}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  51%|████████████████████████████████████████████████████████████████████▎                                                                | 257/500 [08:16<06:22,  1.58s/it]

[I 2026-07-08 16:25:15,274] Trial 252 finished with value: 0.9494987022320617 and parameters: {'C': 1.974929622659886, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00017377071245675604, 'max_iter': 2766, 'weight_class_0': 0.5978072439744453, 'weight_class_1': 6.32835235225907, 'weight_class_2': 3.9578343804311142}. Best is trial 184 with value: 0.9497490579269744.
[I 2026-07-08 16:25:15,347] Trial 260 pruned.

Best trial: 184. Best value: 0.949749:  52%|████████████████████████████████████████████████████████████████████▋                                                                | 258/500 [08:18<06:35,  1.64s/it]

[I 2026-07-08 16:25:17,106] Trial 258 finished with value: 0.9495834328217931 and parameters: {'C': 2.3118401053187525, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0010247886401313622, 'max_iter': 3040, 'weight_class_0': 0.7896091833665357, 'weight_class_1': 4.271132538958548, 'weight_class_2': 4.022935868489579}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  52%|████████████████████████████████████████████████████████████████████▉                                                                | 259/500 [08:25<12:26,  3.10s/it]

[I 2026-07-08 16:25:23,730] Trial 254 finished with value: 0.9496981292090672 and parameters: {'C': 1.7653210883000017, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0001583020352118547, 'max_iter': 2789, 'weight_class_0': 0.6079400034809754, 'weight_class_1': 4.2347860241744995, 'weight_class_2': 4.01280712084468}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  52%|█████████████████████████████████████████████████████████████████████▏                                                               | 260/500 [08:26<10:09,  2.54s/it]

[I 2026-07-08 16:25:24,869] Trial 257 finished with value: 0.9495712996345554 and parameters: {'C': 2.1995135195923816, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00018241604302639096, 'max_iter': 2998, 'weight_class_0': 0.7909933542354192, 'weight_class_1': 4.3196601398893835, 'weight_class_2': 4.040446520966018}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  52%|█████████████████████████████████████████████████████████████████████▍                                                               | 261/500 [08:31<13:12,  3.32s/it]

[I 2026-07-08 16:25:29,961] Trial 259 finished with value: 0.9494227659265853 and parameters: {'C': 2.0097119181989433, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0001760311161397521, 'max_iter': 3004, 'weight_class_0': 0.7884874555660916, 'weight_class_1': 4.323813369654539, 'weight_class_2': 3.5950137077493074}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  52%|█████████████████████████████████████████████████████████████████████▋                                                               | 262/500 [08:36<14:46,  3.73s/it]

[I 2026-07-08 16:25:34,732] Trial 261 finished with value: 0.9494731210458289 and parameters: {'C': 0.0003629361129754538, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0001998993955013786, 'max_iter': 2980, 'weight_class_0': 0.7945756714602187, 'weight_class_1': 4.3953589177558525, 'weight_class_2': 5.125906700602282}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  53%|█████████████████████████████████████████████████████████████████████▉                                                               | 263/500 [08:37<12:12,  3.09s/it]

[I 2026-07-08 16:25:36,399] Trial 262 finished with value: 0.9493745940892213 and parameters: {'C': 0.00040545632840440464, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00031392597982337315, 'max_iter': 2999, 'weight_class_0': 0.7625262747333825, 'weight_class_1': 4.3287307450994845, 'weight_class_2': 5.337348626793348}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  53%|██████████████████████████████████████████████████████████████████████▏                                                              | 264/500 [08:39<10:02,  2.55s/it]

[I 2026-07-08 16:25:37,643] Trial 264 pruned.

Best trial: 184. Best value: 0.949749:  53%|██████████████████████████████████████████████████████████████████████▍                                                              | 265/500 [08:41<10:12,  2.61s/it]

[I 2026-07-08 16:25:40,435] Trial 269 pruned.

Best trial: 184. Best value: 0.949749:  53%|██████████████████████████████████████████████████████████████████████▊                                                              | 266/500 [08:50<16:38,  4.27s/it]

[I 2026-07-08 16:25:48,502] Trial 263 finished with value: 0.9495775363533443 and parameters: {'C': 1.2665673059121083, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00010593722301161545, 'max_iter': 2635, 'weight_class_0': 0.7831376129049687, 'weight_class_1': 4.228049382558488, 'weight_class_2': 5.43562234755798}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  53%|███████████████████████████████████████████████████████████████████████                                                              | 267/500 [08:51<13:49,  3.56s/it]

[I 2026-07-08 16:25:50,484] Trial 272 pruned.

Best trial: 184. Best value: 0.949749:  54%|███████████████████████████████████████████████████████████████████████▎                                                             | 268/500 [08:56<14:27,  3.74s/it]

[I 2026-07-08 16:25:54,621] Trial 265 finished with value: 0.9491116200402594 and parameters: {'C': 1.1947162569235925, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0001115769409424043, 'max_iter': 2998, 'weight_class_0': 0.5212892188854321, 'weight_class_1': 4.39574604770432, 'weight_class_2': 5.308065711568225}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  54%|███████████████████████████████████████████████████████████████████████▌                                                             | 269/500 [08:58<12:36,  3.28s/it]

[I 2026-07-08 16:25:56,837] Trial 273 pruned.

Best trial: 184. Best value: 0.949749:  54%|███████████████████████████████████████████████████████████████████████▊                                                             | 270/500 [08:59<10:16,  2.68s/it]

[I 2026-07-08 16:25:58,085] Trial 266 finished with value: 0.9491905747141354 and parameters: {'C': 1.3050533078274793, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00010978879165650408, 'max_iter': 2636, 'weight_class_0': 0.5251899386364309, 'weight_class_1': 4.159462319388783, 'weight_class_2': 5.206551198441783}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  54%|████████████████████████████████████████████████████████████████████████                                                             | 271/500 [09:00<08:02,  2.11s/it]

[I 2026-07-08 16:25:58,770] Trial 267 finished with value: 0.9495875320980505 and parameters: {'C': 1.211343049804701, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00011322777715637009, 'max_iter': 2654, 'weight_class_0': 0.5193809994197102, 'weight_class_1': 4.239461061687926, 'weight_class_2': 3.55247177749416}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  54%|████████████████████████████████████████████████████████████████████████▎                                                            | 272/500 [09:02<08:01,  2.11s/it]

[I 2026-07-08 16:26:00,836] Trial 268 finished with value: 0.949226797961906 and parameters: {'C': 1.2720506506785416, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0001098235693059956, 'max_iter': 2635, 'weight_class_0': 0.5229851337190718, 'weight_class_1': 4.3277401681890675, 'weight_class_2': 5.004199206285725}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  55%|████████████████████████████████████████████████████████████████████████▌                                                            | 273/500 [09:03<06:14,  1.65s/it]

[I 2026-07-08 16:26:01,595] Trial 271 finished with value: 0.949587096759692 and parameters: {'C': 0.0004644993087502552, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00011428222409805652, 'max_iter': 2655, 'weight_class_0': 0.5309337731582645, 'weight_class_1': 3.439242353974978, 'weight_class_2': 3.5840740746746027}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  55%|████████████████████████████████████████████████████████████████████████▉                                                            | 274/500 [09:05<06:45,  1.79s/it]

[I 2026-07-08 16:26:03,662] Trial 274 pruned.

Best trial: 184. Best value: 0.949749:  55%|█████████████████████████████████████████████████████████████████████████▏                                                           | 275/500 [09:07<07:39,  2.04s/it]

[I 2026-07-08 16:26:06,339] Trial 270 finished with value: 0.9492701931110809 and parameters: {'C': 1.1499256118888845, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0001128738768574822, 'max_iter': 2641, 'weight_class_0': 0.5322385666911553, 'weight_class_1': 3.456754522369848, 'weight_class_2': 5.164126832687384}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  55%|█████████████████████████████████████████████████████████████████████████▍                                                           | 276/500 [09:16<15:08,  4.05s/it]

[I 2026-07-08 16:26:15,092] Trial 279 pruned.

Best trial: 184. Best value: 0.949749:  55%|█████████████████████████████████████████████████████████████████████████▋                                                           | 277/500 [09:16<10:56,  2.94s/it]

[I 2026-07-08 16:26:15,380] Trial 280 pruned.

Best trial: 184. Best value: 0.949749:  56%|█████████████████████████████████████████████████████████████████████████▉                                                           | 278/500 [09:18<09:02,  2.44s/it]

[I 2026-07-08 16:26:16,608] Trial 275 finished with value: 0.9496387757398423 and parameters: {'C': 3.9609981709885678, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00015437167361643202, 'max_iter': 2636, 'weight_class_0': 0.5258996742326175, 'weight_class_1': 3.329437343535322, 'weight_class_2': 3.5642468886715557}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  56%|██████████████████████████████████████████████████████████████████████████▏                                                          | 279/500 [09:20<08:36,  2.34s/it]

[I 2026-07-08 16:26:18,782] Trial 283 finished with value: 0.9490652676335072 and parameters: {'C': 0.000164518618350981, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.001058323944561219, 'max_iter': 2806, 'weight_class_0': 0.6570388138060049, 'weight_class_1': 3.3596462454405915, 'weight_class_2': 2.710934131558412}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  56%|██████████████████████████████████████████████████████████████████████████▍                                                          | 280/500 [09:21<07:28,  2.04s/it]

[I 2026-07-08 16:26:20,102] Trial 276 finished with value: 0.9492713756063234 and parameters: {'C': 2.814583152094845, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0001548708615073641, 'max_iter': 2489, 'weight_class_0': 0.5314212006241762, 'weight_class_1': 3.3465949174116902, 'weight_class_2': 5.0030389727585245}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  56%|██████████████████████████████████████████████████████████████████████████▋                                                          | 281/500 [09:26<10:09,  2.78s/it]

[I 2026-07-08 16:26:24,627] Trial 284 finished with value: 0.9492705750030875 and parameters: {'C': 0.013670404937121546, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.000507928223122756, 'max_iter': 2478, 'weight_class_0': 0.7039690075045011, 'weight_class_1': 4.968829654131139, 'weight_class_2': 2.8688952955602547}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  56%|███████████████████████████████████████████████████████████████████████████                                                          | 282/500 [09:30<11:26,  3.15s/it]

[I 2026-07-08 16:26:28,453] Trial 277 finished with value: 0.9492534692335113 and parameters: {'C': 0.013986617899311434, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00015073120976469745, 'max_iter': 2632, 'weight_class_0': 0.6731821295039226, 'weight_class_1': 3.3845143576347545, 'weight_class_2': 2.7546737831204275}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  57%|███████████████████████████████████████████████████████████████████████████▎                                                         | 283/500 [09:31<09:01,  2.50s/it]

[I 2026-07-08 16:26:29,503] Trial 281 finished with value: 0.9492983165765032 and parameters: {'C': 4.044160155113848, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00023055640458708994, 'max_iter': 2797, 'weight_class_0': 0.6730254985739419, 'weight_class_1': 4.899347891576411, 'weight_class_2': 2.784776302257315}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  57%|███████████████████████████████████████████████████████████████████████████▌                                                         | 284/500 [09:32<07:20,  2.04s/it]

[I 2026-07-08 16:26:30,625] Trial 290 pruned.
[I 2026-07-08 16:26:30,656] Trial 278 finished with value: 0.9492808812370859 and parameters: {'C': 3.895324559262986, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00015147425049485063, 'max_iter': 2485, 'weight_class_0': 0.6736978501514208, 'weight_class_1': 5.5119298894458755, 'weight_class_2': 2.8504122599505384}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  57%|████████████████████████████████████████████████████████████████████████████                                                         | 286/500 [09:32<04:13,  1.19s/it]

[I 2026-07-08 16:26:31,238] Trial 285 finished with value: 0.9493144416664236 and parameters: {'C': 2.7439196098254506, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00022103739183022754, 'max_iter': 2825, 'weight_class_0': 0.6259973485079907, 'weight_class_1': 4.953785969469828, 'weight_class_2': 2.7584614067116893}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  58%|████████████████████████████████████████████████████████████████████████████▌                                                        | 288/500 [09:33<02:33,  1.38it/s]

[I 2026-07-08 16:26:31,754] Trial 286 finished with value: 0.949726522492328 and parameters: {'C': 0.0012641389336704779, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00014272346821516763, 'max_iter': 2504, 'weight_class_0': 0.6838226687792978, 'weight_class_1': 4.8778324834070546, 'weight_class_2': 4.249117828427614}. Best is trial 184 with value: 0.9497490579269744.
[I 2026-07-08 16:26:31,926] Trial 291 pruned.

Best trial: 184. Best value: 0.949749:  58%|████████████████████████████████████████████████████████████████████████████▊                                                        | 289/500 [09:34<02:32,  1.38it/s]

[I 2026-07-08 16:26:32,524] Trial 282 finished with value: 0.9491269616485314 and parameters: {'C': 0.00024144466760254473, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00014018729354350098, 'max_iter': 2791, 'weight_class_0': 0.6774362792204338, 'weight_class_1': 3.350261252047178, 'weight_class_2': 2.7062594275089022}. Best is trial 184 with value: 0.9497490579269744.

[I 2026-07-08 16:26:35,681] Trial 292 pruned.

Best trial: 184. Best value: 0.949749:  58%|█████████████████████████████████████████████████████████████████████████████▍                                                       | 291/500 [09:37<03:57,  1.14s/it]

[I 2026-07-08 16:26:35,905] Trial 288 finished with value: 0.9496243453206221 and parameters: {'C': 0.0002237784647905107, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0005104633274876721, 'max_iter': 2811, 'weight_class_0': 0.6673838209537195, 'weight_class_1': 5.026239024809622, 'weight_class_2': 4.306494462213207}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  58%|█████████████████████████████████████████████████████████████████████████████▋                                                       | 292/500 [09:40<05:32,  1.60s/it]

[I 2026-07-08 16:26:38,746] Trial 289 finished with value: 0.9492770200606169 and parameters: {'C': 0.012354514999774753, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0011334316421382847, 'max_iter': 2809, 'weight_class_0': 0.671097485230419, 'weight_class_1': 4.936755858602391, 'weight_class_2': 2.8027957437973425}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  59%|█████████████████████████████████████████████████████████████████████████████▉                                                       | 293/500 [09:41<05:29,  1.59s/it]

[I 2026-07-08 16:26:40,476] Trial 287 finished with value: 0.9497370962172376 and parameters: {'C': 0.015540750198230507, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00022193089071118028, 'max_iter': 2821, 'weight_class_0': 0.6565582694167723, 'weight_class_1': 4.945862162565254, 'weight_class_2': 4.18040777747139}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  59%|██████████████████████████████████████████████████████████████████████████████▏                                                      | 294/500 [09:44<06:47,  1.98s/it]

[I 2026-07-08 16:26:43,178] Trial 299 pruned.

Best trial: 184. Best value: 0.949749:  59%|██████████████████████████████████████████████████████████████████████████████▋                                                      | 296/500 [09:49<06:39,  1.96s/it]

[I 2026-07-08 16:26:47,823] Trial 302 pruned.
[I 2026-07-08 16:26:47,825] Trial 294 finished with value: 0.9487781461877033 and parameters: {'C': 0.00022776898277748097, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.001160741062696398, 'max_iter': 2720, 'weight_class_0': 1.1298582133450403, 'weight_class_1': 5.5040111516684895, 'weight_class_2': 4.276140696639867}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  59%|███████████████████████████████████████████████████████████████████████████████                                                      | 297/500 [09:49<04:53,  1.44s/it]

[I 2026-07-08 16:26:48,016] Trial 301 pruned.

Best trial: 184. Best value: 0.949749:  60%|███████████████████████████████████████████████████████████████████████████████▎                                                     | 298/500 [09:50<03:57,  1.18s/it]

[I 2026-07-08 16:26:48,689] Trial 296 pruned.

[I 2026-07-08 16:26:49,096] Trial 297 pruned.

Best trial: 184. Best value: 0.949749:  60%|███████████████████████████████████████████████████████████████████████████████▊                                                     | 300/500 [09:50<02:21,  1.41it/s]

[I 2026-07-08 16:26:49,198] Trial 295 pruned.
[I 2026-07-08 16:26:49,353] Trial 300 pruned.

Best trial: 184. Best value: 0.949749:  61%|████████████████████████████████████████████████████████████████████████████████▌                                                    | 303/500 [09:51<01:35,  2.06it/s]

[I 2026-07-08 16:26:50,299] Trial 298 pruned.
[I 2026-07-08 16:26:50,369] Trial 293 finished with value: 0.9494333725070238 and parameters: {'C': 0.0002325281926957816, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0001263822797185942, 'max_iter': 2744, 'weight_class_0': 0.6168913008225766, 'weight_class_1': 4.791962205842407, 'weight_class_2': 4.276958253789373}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  61%|████████████████████████████████████████████████████████████████████████████████▊                                                    | 304/500 [09:55<04:21,  1.33s/it]

[I 2026-07-08 16:26:53,722] Trial 304 pruned.

Best trial: 184. Best value: 0.949749:  61%|█████████████████████████████████████████████████████████████████████████████████▏                                                   | 305/500 [10:02<09:49,  3.02s/it]

[I 2026-07-08 16:27:00,797] Trial 310 pruned.

Best trial: 184. Best value: 0.949749:  61%|█████████████████████████████████████████████████████████████████████████████████▍                                                   | 306/500 [10:05<10:20,  3.20s/it]

[I 2026-07-08 16:27:04,133] Trial 307 finished with value: 0.9492386788406207 and parameters: {'C': 0.0013532326796196457, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.003933555640872613, 'max_iter': 2570, 'weight_class_0': 0.8592714662581292, 'weight_class_1': 6.058118214052594, 'weight_class_2': 3.5480939151708744}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  61%|█████████████████████████████████████████████████████████████████████████████████▋                                                   | 307/500 [10:06<07:22,  2.29s/it]

[I 2026-07-08 16:27:04,543] Trial 306 finished with value: 0.9492571913631602 and parameters: {'C': 0.719272287040669, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.003909168889490844, 'max_iter': 2542, 'weight_class_0': 0.8293413117510724, 'weight_class_1': 3.902652497068944, 'weight_class_2': 3.4906742006150067}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  62%|█████████████████████████████████████████████████████████████████████████████████▉                                                   | 308/500 [10:06<05:39,  1.77s/it]

[I 2026-07-08 16:27:05,114] Trial 309 finished with value: 0.9490916077287341 and parameters: {'C': 0.0012675531549061648, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0037617655580706086, 'max_iter': 2537, 'weight_class_0': 0.8413566889065028, 'weight_class_1': 3.85681053499654, 'weight_class_2': 3.4631632083116575}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  62%|██████████████████████████████████████████████████████████████████████████████████▏                                                  | 309/500 [10:07<04:31,  1.42s/it]

[I 2026-07-08 16:27:05,577] Trial 315 pruned.

Best trial: 184. Best value: 0.949749:  62%|██████████████████████████████████████████████████████████████████████████████████▏                                                  | 309/500 [10:07<04:31,  1.42s/it]

[I 2026-07-08 16:27:06,137] Trial 303 finished with value: 0.949543930233447 and parameters: {'C': 0.00056061657245867, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00012863579234077775, 'max_iter': 2926, 'weight_class_0': 0.8606592001677018, 'weight_class_1': 5.664118702470955, 'weight_class_2': 6.265114700659325}. Best is trial 184 with value: 0.9497490579269744.

[I 2026-07-08 16:27:08,028] Trial 308 finished with value: 0.949122164373015 and parameters: {'C': 0.0012458916199323752, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0009396810392242282, 'max_iter': 2554, 'weight_class_0': 0.8570552108438716, 'weight_class_1': 6.091193624882507, 'weight_class_2': 3.5095556821373792}. Best is trial 184 with value: 0.9497490579269744.
[I 2026-07-08 16:27:08,028] Trial 312 finished with value: 0.9493004958540199 and parameters: {'C': 0.772981599352519, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00384589360692532, 'max_iter': 2548, 'weight_class_0': 0.8189408630196385, 'weight_class_1': 6.544800411443318, 'weight_class_2': 3.4443189576439512}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  63%|███████████████████████████████████████████████████████████████████████████████████▎                                                 | 313/500 [10:09<02:27,  1.27it/s]

[I 2026-07-08 16:27:08,116] Trial 311 finished with value: 0.9491883708451372 and parameters: {'C': 0.053393580446818766, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0038082960655308196, 'max_iter': 2549, 'weight_class_0': 0.8466976265256185, 'weight_class_1': 3.7962656390081184, 'weight_class_2': 3.4715101614862167}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  63%|███████████████████████████████████████████████████████████████████████████████████▌                                                 | 314/500 [10:12<03:30,  1.13s/it]

[I 2026-07-08 16:27:10,544] Trial 313 finished with value: 0.9491650602948729 and parameters: {'C': 0.025507998261918026, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.001563987025362911, 'max_iter': 2932, 'weight_class_0': 0.8621115256925946, 'weight_class_1': 3.8919791079787363, 'weight_class_2': 3.5265689145223083}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  63%|███████████████████████████████████████████████████████████████████████████████████▊                                                 | 315/500 [10:14<04:32,  1.47s/it]

[I 2026-07-08 16:27:12,953] Trial 314 pruned.

Best trial: 184. Best value: 0.949749:  63%|████████████████████████████████████████████████████████████████████████████████████                                                 | 316/500 [10:16<05:11,  1.69s/it]

[I 2026-07-08 16:27:15,130] Trial 305 finished with value: 0.9492656650295206 and parameters: {'C': 0.020361870432537135, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00013391101334379212, 'max_iter': 2711, 'weight_class_0': 0.863226189790859, 'weight_class_1': 5.832517028775671, 'weight_class_2': 3.5021782469908076}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  63%|████████████████████████████████████████████████████████████████████████████████████▎                                                | 317/500 [10:20<06:50,  2.24s/it]

[I 2026-07-08 16:27:18,910] Trial 323 pruned.

Best trial: 184. Best value: 0.949749:  64%|████████████████████████████████████████████████████████████████████████████████████▌                                                | 318/500 [10:22<06:16,  2.07s/it]

[I 2026-07-08 16:27:20,481] Trial 316 finished with value: 0.9495684835571261 and parameters: {'C': 0.009953324037000336, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0014824704054320064, 'max_iter': 2910, 'weight_class_0': 0.8641220490987809, 'weight_class_1': 7.7616879514904555, 'weight_class_2': 4.820696263727664}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 184. Best value: 0.949749:  64%|████████████████████████████████████████████████████████████████████████████████████▊                                                | 319/500 [10:22<05:03,  1.68s/it]

[I 2026-07-08 16:27:21,136] Trial 321 pruned.

Best trial: 184. Best value: 0.949749:  64%|█████████████████████████████████████████████████████████████████████████████████████                                                | 320/500 [10:27<08:02,  2.68s/it]

[I 2026-07-08 16:27:26,352] Trial 317 pruned.

Best trial: 184. Best value: 0.949749:  64%|█████████████████████████████████████████████████████████████████████████████████████▍                                               | 321/500 [10:31<08:31,  2.86s/it]

[I 2026-07-08 16:27:29,564] Trial 326 pruned.

Best trial: 184. Best value: 0.949749:  64%|█████████████████████████████████████████████████████████████████████████████████████▋                                               | 322/500 [10:31<06:33,  2.21s/it]

[I 2026-07-08 16:27:30,144] Trial 318 finished with value: 0.949556536402115 and parameters: {'C': 0.022939377580481753, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.001452249243578126, 'max_iter': 2924, 'weight_class_0': 0.7684407455113598, 'weight_class_1': 7.783078477073262, 'weight_class_2': 4.763341858347092}. Best is trial 184 with value: 0.9497490579269744.

Best trial: 320. Best value: 0.949752:  65%|█████████████████████████████████████████████████████████████████████████████████████▉                                               | 323/500 [10:32<05:27,  1.85s/it]

[I 2026-07-08 16:27:31,340] Trial 320 finished with value: 0.9497521962450051 and parameters: {'C': 0.016583182054671262, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0010484096989234488, 'max_iter': 2941, 'weight_class_0': 0.7574214432061076, 'weight_class_1': 6.716577353226011, 'weight_class_2': 4.729921076750412}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  65%|██████████████████████████████████████████████████████████████████████████████████████▏                                              | 324/500 [10:33<04:46,  1.63s/it]

[I 2026-07-08 16:27:32,312] Trial 324 finished with value: 0.949568493590467 and parameters: {'C': 0.03217394905198752, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0010562282017070048, 'max_iter': 2396, 'weight_class_0': 0.740658658155398, 'weight_class_1': 7.534912493148358, 'weight_class_2': 4.733132464909812}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  65%|██████████████████████████████████████████████████████████████████████████████████████▍                                              | 325/500 [10:34<03:59,  1.37s/it]

[I 2026-07-08 16:27:33,006] Trial 322 finished with value: 0.9496495175901236 and parameters: {'C': 0.017847960706324384, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0010591008780957234, 'max_iter': 2422, 'weight_class_0': 0.7671153386989894, 'weight_class_1': 4.5574215867358845, 'weight_class_2': 4.814429298278487}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  65%|██████████████████████████████████████████████████████████████████████████████████████▋                                              | 326/500 [10:36<04:41,  1.62s/it]

[I 2026-07-08 16:27:35,308] Trial 325 finished with value: 0.9496388400937235 and parameters: {'C': 0.02055692876988623, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0010368334705516578, 'max_iter': 3851, 'weight_class_0': 0.7429845951348298, 'weight_class_1': 4.533262132623366, 'weight_class_2': 4.662680979326482}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  65%|██████████████████████████████████████████████████████████████████████████████████████▉                                              | 327/500 [10:37<04:10,  1.45s/it]

[I 2026-07-08 16:27:36,403] Trial 330 pruned.

Best trial: 320. Best value: 0.949752:  66%|███████████████████████████████████████████████████████████████████████████████████████▏                                             | 328/500 [10:41<05:56,  2.07s/it]

[I 2026-07-08 16:27:40,003] Trial 327 finished with value: 0.94964429191587 and parameters: {'C': 2.417975560764608, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0013679707571465317, 'max_iter': 2317, 'weight_class_0': 0.7440743334570689, 'weight_class_1': 4.548048539399015, 'weight_class_2': 4.886997350464032}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  66%|███████████████████████████████████████████████████████████████████████████████████████▌                                             | 329/500 [10:44<06:47,  2.39s/it]

[I 2026-07-08 16:27:43,029] Trial 328 finished with value: 0.9496589245124015 and parameters: {'C': 1.7395884825455297, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0010030454569175955, 'max_iter': 2900, 'weight_class_0': 0.6902309630609827, 'weight_class_1': 4.679411437878854, 'weight_class_2': 4.6948864669843715}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  66%|███████████████████████████████████████████████████████████████████████████████████████▊                                             | 330/500 [10:46<06:13,  2.20s/it]

[I 2026-07-08 16:27:44,809] Trial 329 finished with value: 0.9496205117258721 and parameters: {'C': 5.324755312177115, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0012630711113875053, 'max_iter': 2415, 'weight_class_0': 0.7452836072213381, 'weight_class_1': 4.549665252458499, 'weight_class_2': 3.9473722315413884}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  66%|████████████████████████████████████████████████████████████████████████████████████████                                             | 331/500 [10:50<07:48,  2.77s/it]

[I 2026-07-08 16:27:48,982] Trial 337 pruned.

Best trial: 320. Best value: 0.949752:  66%|████████████████████████████████████████████████████████████████████████████████████████▎                                            | 332/500 [10:50<05:42,  2.04s/it]

[I 2026-07-08 16:27:49,156] Trial 332 pruned.

Best trial: 320. Best value: 0.949752:  67%|████████████████████████████████████████████████████████████████████████████████████████▌                                            | 333/500 [10:51<04:19,  1.56s/it]

[I 2026-07-08 16:27:49,520] Trial 335 pruned.

Best trial: 320. Best value: 0.949752:  67%|████████████████████████████████████████████████████████████████████████████████████████▊                                            | 334/500 [10:52<04:04,  1.47s/it]

[I 2026-07-08 16:27:50,946] Trial 338 pruned.

Best trial: 320. Best value: 0.949752:  67%|█████████████████████████████████████████████████████████████████████████████████████████▍                                           | 336/500 [10:52<02:16,  1.20it/s]

[I 2026-07-08 16:27:51,113] Trial 331 finished with value: 0.9488713846620314 and parameters: {'C': 0.00040501675169845724, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.001285742010575112, 'max_iter': 3281, 'weight_class_0': 1.0391414970858075, 'weight_class_1': 4.590521724639774, 'weight_class_2': 3.9268172676449367}. Best is trial 320 with value: 0.9497521962450051.
[I 2026-07-08 16:27:51,243] Trial 319 finished with value: 0.9495240688160098 and parameters: {'C': 0.007621161908547422, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00010175274744913664, 'max_iter': 4789, 'weight_class_0': 0.7433774761264675, 'weight_class_1': 7.591366344499295, 'weight_class_2': 4.767892667342006}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  67%|█████████████████████████████████████████████████████████████████████████████████████████▋                                           | 337/500 [10:55<04:03,  1.50s/it]

[I 2026-07-08 16:27:54,477] Trial 339 pruned.

Best trial: 320. Best value: 0.949752:  68%|█████████████████████████████████████████████████████████████████████████████████████████▉                                           | 338/500 [10:57<03:58,  1.47s/it]

[I 2026-07-08 16:27:55,960] Trial 334 finished with value: 0.94933523696746 and parameters: {'C': 0.014966557344386424, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.001280934044772917, 'max_iter': 2897, 'weight_class_0': 0.4687966612491712, 'weight_class_1': 2.6998399322072335, 'weight_class_2': 3.9650910870035023}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  68%|██████████████████████████████████████████████████████████████████████████████████████████▏                                          | 339/500 [10:58<03:42,  1.38s/it]

[I 2026-07-08 16:27:57,128] Trial 336 finished with value: 0.9491694702881794 and parameters: {'C': 0.047059929314841535, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.001273088372596623, 'max_iter': 3073, 'weight_class_0': 1.0357506825561917, 'weight_class_1': 6.620876649812712, 'weight_class_2': 3.9722401484065943}. Best is trial 320 with value: 0.9497521962450051.
[I 2026-07-08 16:27:57,201] Trial 340 pruned.

Best trial: 320. Best value: 0.949752:  68%|██████████████████████████████████████████████████████████████████████████████████████████▋                                          | 341/500 [10:59<02:29,  1.06it/s]

[I 2026-07-08 16:27:58,047] Trial 341 pruned.

Best trial: 320. Best value: 0.949752:  68%|██████████████████████████████████████████████████████████████████████████████████████████▉                                          | 342/500 [11:04<06:03,  2.30s/it]

[I 2026-07-08 16:28:03,327] Trial 333 finished with value: 0.9496217573243312 and parameters: {'C': 0.0005754861250919751, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00025519737976148656, 'max_iter': 3075, 'weight_class_0': 0.5679487110048029, 'weight_class_1': 4.471005069556326, 'weight_class_2': 3.977994279280848}. Best is trial 320 with value: 0.9497521962450051.
[I 2026-07-08 16:28:03,490] Trial 344 pruned.

Best trial: 320. Best value: 0.949752:  69%|███████████████████████████████████████████████████████████████████████████████████████████▌                                         | 344/500 [11:06<04:12,  1.62s/it]

[I 2026-07-08 16:28:05,176] Trial 346 pruned.

Best trial: 320. Best value: 0.949752:  69%|███████████████████████████████████████████████████████████████████████████████████████████▊                                         | 345/500 [11:07<03:31,  1.36s/it]

[I 2026-07-08 16:28:05,596] Trial 347 pruned.
[I 2026-07-08 16:28:05,792] Trial 343 finished with value: 0.948970804246661 and parameters: {'C': 0.5246131633130401, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.004442013976759175, 'max_iter': 3068, 'weight_class_0': 0.6630156542039826, 'weight_class_1': 6.666631426531599, 'weight_class_2': 5.568306047052128}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  69%|████████████████████████████████████████████████████████████████████████████████████████████▎                                        | 347/500 [11:11<04:35,  1.80s/it]

[I 2026-07-08 16:28:09,840] Trial 349 pruned.

Best trial: 320. Best value: 0.949752:  70%|████████████████████████████████████████████████████████████████████████████████████████████▌                                        | 348/500 [11:12<04:13,  1.67s/it]

[I 2026-07-08 16:28:11,097] Trial 350 pruned.

Best trial: 320. Best value: 0.949752:  70%|████████████████████████████████████████████████████████████████████████████████████████████▊                                        | 349/500 [11:13<03:25,  1.36s/it]

[I 2026-07-08 16:28:11,658] Trial 352 pruned.
[I 2026-07-08 16:28:11,763] Trial 342 finished with value: 0.9491365064433932 and parameters: {'C': 0.49986551838457255, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0011251084011785638, 'max_iter': 3083, 'weight_class_0': 1.0742125433162826, 'weight_class_1': 6.806677575820814, 'weight_class_2': 3.938717194522941}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  70%|█████████████████████████████████████████████████████████████████████████████████████████████▎                                       | 351/500 [11:15<02:53,  1.17s/it]

[I 2026-07-08 16:28:13,508] Trial 345 finished with value: 0.9496420111886665 and parameters: {'C': 42.92485143501889, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.001132026205395861, 'max_iter': 2841, 'weight_class_0': 1.007803577609754, 'weight_class_1': 6.7945163984092165, 'weight_class_2': 5.211339675305436}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  70%|█████████████████████████████████████████████████████████████████████████████████████████████▋                                       | 352/500 [11:18<04:17,  1.74s/it]

[I 2026-07-08 16:28:16,960] Trial 348 finished with value: 0.9494234994357091 and parameters: {'C': 0.047868232210702986, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0009644829377203626, 'max_iter': 2849, 'weight_class_0': 0.6515386209705847, 'weight_class_1': 6.592987570357432, 'weight_class_2': 5.551089363021557}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  71%|█████████████████████████████████████████████████████████████████████████████████████████████▉                                       | 353/500 [11:21<04:57,  2.03s/it]

[I 2026-07-08 16:28:19,974] Trial 351 finished with value: 0.9495197450594247 and parameters: {'C': 1.6610948630623132, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0011116053217286683, 'max_iter': 2806, 'weight_class_0': 0.6650201013802708, 'weight_class_1': 5.248353132584107, 'weight_class_2': 5.545251914075525}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  71%|██████████████████████████████████████████████████████████████████████████████████████████████▏                                      | 354/500 [11:22<04:24,  1.81s/it]

[I 2026-07-08 16:28:21,175] Trial 353 finished with value: 0.949329399788445 and parameters: {'C': 1.7239917266584086, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.004477284927775541, 'max_iter': 2812, 'weight_class_0': 0.6596732167156538, 'weight_class_1': 5.125858822215093, 'weight_class_2': 5.370868358581301}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  71%|██████████████████████████████████████████████████████████████████████████████████████████████▍                                      | 355/500 [11:27<06:14,  2.58s/it]

[I 2026-07-08 16:28:25,777] Trial 360 pruned.

Best trial: 320. Best value: 0.949752:  71%|██████████████████████████████████████████████████████████████████████████████████████████████▋                                      | 356/500 [11:28<05:29,  2.29s/it]

[I 2026-07-08 16:28:27,345] Trial 354 finished with value: 0.9493727295573707 and parameters: {'C': 1.585767323646876, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0009595764745677016, 'max_iter': 2824, 'weight_class_0': 0.651749343015139, 'weight_class_1': 5.18423192821255, 'weight_class_2': 5.7813544897392}. Best is trial 320 with value: 0.9497521962450051.

[I 2026-07-08 16:28:29,343] Trial 355 finished with value: 0.9495311607037074 and parameters: {'C': 1.7882801360887053, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0009577650961454973, 'max_iter': 2675, 'weight_class_0': 0.6569630798424764, 'weight_class_1': 5.1953606764220925, 'weight_class_2': 5.4238590915696}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  72%|███████████████████████████████████████████████████████████████████████████████████████████████▏                                     | 358/500 [11:31<03:54,  1.65s/it]

[I 2026-07-08 16:28:29,452] Trial 356 finished with value: 0.9494871815578056 and parameters: {'C': 1.9790163253109685, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.001100043192106376, 'max_iter': 2761, 'weight_class_0': 0.675541884868641, 'weight_class_1': 5.187607312094574, 'weight_class_2': 3.1366086187951447}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  72%|███████████████████████████████████████████████████████████████████████████████████████████████▍                                     | 359/500 [11:33<04:20,  1.84s/it]

[I 2026-07-08 16:28:31,761] Trial 357 finished with value: 0.9496957857169098 and parameters: {'C': 0.9058030579994409, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0010962420733069583, 'max_iter': 2682, 'weight_class_0': 0.6565631179687216, 'weight_class_1': 5.195026346917828, 'weight_class_2': 4.465713753319698}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  72%|███████████████████████████████████████████████████████████████████████████████████████████████▊                                     | 360/500 [11:34<03:38,  1.56s/it]

[I 2026-07-08 16:28:32,795] Trial 362 finished with value: 0.9494762408633438 and parameters: {'C': 1.8156696367851148, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.003176497071864819, 'max_iter': 2639, 'weight_class_0': 0.5791266431945203, 'weight_class_1': 5.123362837797815, 'weight_class_2': 4.513660159811949}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  72%|████████████████████████████████████████████████████████████████████████████████████████████████                                     | 361/500 [11:37<04:33,  1.97s/it]

[I 2026-07-08 16:28:35,646] Trial 358 finished with value: 0.9495954834392725 and parameters: {'C': 0.0019545144387383257, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0009486314297726449, 'max_iter': 2643, 'weight_class_0': 0.5767784378058223, 'weight_class_1': 5.155226718210227, 'weight_class_2': 3.0774155677123995}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  72%|████████████████████████████████████████████████████████████████████████████████████████████████▎                                    | 362/500 [11:40<05:16,  2.29s/it]

[I 2026-07-08 16:28:38,815] Trial 363 finished with value: 0.9495236775650095 and parameters: {'C': 1.508863660300425, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.002984959424059608, 'max_iter': 2652, 'weight_class_0': 0.5798191583255808, 'weight_class_1': 3.894202720838906, 'weight_class_2': 4.445462014621835}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  73%|████████████████████████████████████████████████████████████████████████████████████████████████▌                                    | 363/500 [11:42<04:59,  2.19s/it]

[I 2026-07-08 16:28:40,763] Trial 361 finished with value: 0.9497087487345505 and parameters: {'C': 0.9648008875226928, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00020327654092564294, 'max_iter': 2699, 'weight_class_0': 0.5571895354687866, 'weight_class_1': 3.858734505776629, 'weight_class_2': 3.179212365661726}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  73%|████████████████████████████████████████████████████████████████████████████████████████████████▊                                    | 364/500 [11:43<04:31,  2.00s/it]

[I 2026-07-08 16:28:42,200] Trial 367 pruned.

Best trial: 320. Best value: 0.949752:  73%|█████████████████████████████████████████████████████████████████████████████████████████████████                                    | 365/500 [11:47<05:25,  2.41s/it]

[I 2026-07-08 16:28:45,611] Trial 364 pruned.

Best trial: 320. Best value: 0.949752:  73%|█████████████████████████████████████████████████████████████████████████████████████████████████▎                                   | 366/500 [11:49<05:39,  2.53s/it]

[I 2026-07-08 16:28:48,422] Trial 365 finished with value: 0.9495678942608343 and parameters: {'C': 1.0524618763202636, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0003910461495737362, 'max_iter': 2645, 'weight_class_0': 0.5765555692543295, 'weight_class_1': 4.145150493607565, 'weight_class_2': 4.500532958207025}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  73%|█████████████████████████████████████████████████████████████████████████████████████████████████▌                                   | 367/500 [11:55<07:32,  3.40s/it]

[I 2026-07-08 16:28:53,748] Trial 366 finished with value: 0.9496784501504985 and parameters: {'C': 0.0004250502018654294, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00014363195840673293, 'max_iter': 2948, 'weight_class_0': 0.5848882767118501, 'weight_class_1': 3.940949133150235, 'weight_class_2': 3.1763797968133782}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  73%|█████████████████████████████████████████████████████████████████████████████████████████████████▌                                   | 367/500 [11:56<07:32,  3.40s/it]

[I 2026-07-08 16:28:54,876] Trial 359 finished with value: 0.9495800437105351 and parameters: {'C': 0.9087911243561927, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00014024025752519214, 'max_iter': 2669, 'weight_class_0': 0.6012867202634063, 'weight_class_1': 5.20637161951379, 'weight_class_2': 3.1535012614507174}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  74%|█████████████████████████████████████████████████████████████████████████████████████████████████▉                                   | 368/500 [12:03<06:02,  2.75s/it]

[I 2026-07-08 16:29:01,982] Trial 368 finished with value: 0.9496898572376574 and parameters: {'C': 0.006708493597457284, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00014038050807769464, 'max_iter': 2632, 'weight_class_0': 0.560093240421453, 'weight_class_1': 4.099289955230698, 'weight_class_2': 3.116748141568649}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  74%|██████████████████████████████████████████████████████████████████████████████████████████████████▍                                  | 370/500 [12:08<09:34,  4.42s/it]

[I 2026-07-08 16:29:07,373] Trial 376 pruned.

Best trial: 320. Best value: 0.949752:  74%|██████████████████████████████████████████████████████████████████████████████████████████████████▋                                  | 371/500 [12:12<08:50,  4.11s/it]

[I 2026-07-08 16:29:10,891] Trial 378 pruned.

Best trial: 320. Best value: 0.949752:  74%|██████████████████████████████████████████████████████████████████████████████████████████████████▉                                  | 372/500 [12:13<06:50,  3.21s/it]

[I 2026-07-08 16:29:11,950] Trial 375 pruned.

Best trial: 320. Best value: 0.949752:  75%|███████████████████████████████████████████████████████████████████████████████████████████████████▏                                 | 373/500 [12:14<05:09,  2.43s/it]

[I 2026-07-08 16:29:12,579] Trial 379 pruned.

Best trial: 320. Best value: 0.949752:  75%|███████████████████████████████████████████████████████████████████████████████████████████████████▍                                 | 374/500 [12:16<05:09,  2.46s/it]

[I 2026-07-08 16:29:15,135] Trial 371 finished with value: 0.9492420097157608 and parameters: {'C': 0.8911616498469077, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00015778449327808207, 'max_iter': 2628, 'weight_class_0': 0.5720627197669816, 'weight_class_1': 5.926397704114813, 'weight_class_2': 3.127141876947382}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  75%|███████████████████████████████████████████████████████████████████████████████████████████████████▊                                 | 375/500 [12:17<03:54,  1.88s/it]

[I 2026-07-08 16:29:15,612] Trial 369 finished with value: 0.9494283299801873 and parameters: {'C': 0.9359076622458091, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00014635884434910227, 'max_iter': 2950, 'weight_class_0': 0.5597514667692297, 'weight_class_1': 3.991764587315464, 'weight_class_2': 4.499168417514878}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  75%|████████████████████████████████████████████████████████████████████████████████████████████████████                                 | 376/500 [12:20<04:29,  2.17s/it]

[I 2026-07-08 16:29:18,501] Trial 370 finished with value: 0.9494907929405858 and parameters: {'C': 0.8754823167799116, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00014563268439301904, 'max_iter': 2616, 'weight_class_0': 0.5865433031111547, 'weight_class_1': 3.853950067871665, 'weight_class_2': 4.361304766660076}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  75%|████████████████████████████████████████████████████████████████████████████████████████████████████▎                                | 377/500 [12:25<06:21,  3.10s/it]

[I 2026-07-08 16:29:23,700] Trial 372 finished with value: 0.949367238103002 and parameters: {'C': 0.9685940391696269, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00014285517084197216, 'max_iter': 2716, 'weight_class_0': 0.4969163709770537, 'weight_class_1': 4.008566407525533, 'weight_class_2': 4.348820608025286}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  76%|████████████████████████████████████████████████████████████████████████████████████████████████████▊                                | 379/500 [12:28<04:36,  2.29s/it]

[I 2026-07-08 16:29:27,285] Trial 373 finished with value: 0.9493398963169373 and parameters: {'C': 0.9189055669805886, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00014279040360462317, 'max_iter': 2731, 'weight_class_0': 0.9369079726815605, 'weight_class_1': 5.944547865291479, 'weight_class_2': 4.33149166794525}. Best is trial 320 with value: 0.9497521962450051.
[I 2026-07-08 16:29:27,446] Trial 374 finished with value: 0.9492931769828372 and parameters: {'C': 0.28276274373664273, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0001401897967346745, 'max_iter': 2720, 'weight_class_0': 0.47429312438041954, 'weight_class_1': 4.086341615198844, 'weight_class_2': 4.299846093768327}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  76%|█████████████████████████████████████████████████████████████████████████████████████████████████████                                | 380/500 [12:35<07:00,  3.50s/it]

[I 2026-07-08 16:29:33,775] Trial 377 finished with value: 0.9493471670235796 and parameters: {'C': 0.75080195494283, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00014506028436633142, 'max_iter': 2730, 'weight_class_0': 0.9198226818881514, 'weight_class_1': 5.959539411576134, 'weight_class_2': 4.253291069360929}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  76%|█████████████████████████████████████████████████████████████████████████████████████████████████████▎                               | 381/500 [12:37<06:20,  3.20s/it]

[I 2026-07-08 16:29:36,272] Trial 381 finished with value: 0.9497382860894044 and parameters: {'C': 0.0009051006318242244, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00014409058696689359, 'max_iter': 2738, 'weight_class_0': 0.5131478254209745, 'weight_class_1': 3.7174997581213276, 'weight_class_2': 3.128053899753903}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  76%|█████████████████████████████████████████████████████████████████████████████████████████████████████▌                               | 382/500 [12:40<06:06,  3.10s/it]

[I 2026-07-08 16:29:39,100] Trial 389 pruned.

Best trial: 320. Best value: 0.949752:  77%|█████████████████████████████████████████████████████████████████████████████████████████████████████▉                               | 383/500 [12:41<04:32,  2.33s/it]

[I 2026-07-08 16:29:39,494] Trial 390 pruned.

Best trial: 320. Best value: 0.949752:  77%|██████████████████████████████████████████████████████████████████████████████████████████████████████▏                              | 384/500 [12:42<04:03,  2.10s/it]

[I 2026-07-08 16:29:41,234] Trial 383 finished with value: 0.9495507832420517 and parameters: {'C': 0.0008722628439096578, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00015254002281746192, 'max_iter': 2965, 'weight_class_0': 0.4982249029654118, 'weight_class_1': 3.7703965379911053, 'weight_class_2': 3.603967522977012}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  77%|██████████████████████████████████████████████████████████████████████████████████████████████████████▍                              | 385/500 [12:44<03:41,  1.93s/it]

[I 2026-07-08 16:29:42,597] Trial 384 finished with value: 0.9494143600053262 and parameters: {'C': 0.0007297426048473981, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.000140666688128365, 'max_iter': 2083, 'weight_class_0': 0.5243660169690058, 'weight_class_1': 3.6797489120114357, 'weight_class_2': 2.47891717562962}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  77%|██████████████████████████████████████████████████████████████████████████████████████████████████████▋                              | 386/500 [12:44<02:58,  1.56s/it]

[I 2026-07-08 16:29:43,354] Trial 386 finished with value: 0.9497075814409968 and parameters: {'C': 0.0009112833847927225, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00021186707037293726, 'max_iter': 2041, 'weight_class_0': 0.5219538348581513, 'weight_class_1': 4.113859688211652, 'weight_class_2': 3.3323262520754673}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  77%|██████████████████████████████████████████████████████████████████████████████████████████████████████▉                              | 387/500 [12:46<03:07,  1.66s/it]

[I 2026-07-08 16:29:45,091] Trial 385 finished with value: 0.9497171534737703 and parameters: {'C': 0.25604206661144313, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00021414563014485319, 'max_iter': 2752, 'weight_class_0': 0.507514984145563, 'weight_class_1': 3.643722653323465, 'weight_class_2': 3.3283309552940366}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  78%|███████████████████████████████████████████████████████████████████████████████████████████████████████▏                             | 388/500 [12:48<03:02,  1.63s/it]

[I 2026-07-08 16:29:46,858] Trial 391 pruned.

Best trial: 320. Best value: 0.949752:  78%|███████████████████████████████████████████████████████████████████████████████████████████████████████▍                             | 389/500 [12:48<02:23,  1.30s/it]

[I 2026-07-08 16:29:47,430] Trial 387 finished with value: 0.9496171717844364 and parameters: {'C': 0.0008243494567740949, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.000184618971299827, 'max_iter': 2750, 'weight_class_0': 0.4843875199879243, 'weight_class_1': 3.6391222957159757, 'weight_class_2': 3.3467165417796108}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  78%|███████████████████████████████████████████████████████████████████████████████████████████████████████▋                             | 390/500 [12:50<02:30,  1.37s/it]

[I 2026-07-08 16:29:48,994] Trial 380 finished with value: 0.9495952515535769 and parameters: {'C': 0.8342019740567268, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0001455178647354062, 'max_iter': 2080, 'weight_class_0': 0.49347821071299486, 'weight_class_1': 3.7331397113078224, 'weight_class_2': 3.085902430268919}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  78%|████████████████████████████████████████████████████████████████████████████████████████████████████████                             | 391/500 [12:51<02:05,  1.16s/it]

[I 2026-07-08 16:29:49,595] Trial 392 pruned.

Best trial: 320. Best value: 0.949752:  78%|████████████████████████████████████████████████████████████████████████████████████████████████████████▎                            | 392/500 [12:54<03:12,  1.79s/it]

[I 2026-07-08 16:29:52,909] Trial 388 finished with value: 0.9495586144108745 and parameters: {'C': 0.0008294651315633831, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00011871398799092826, 'max_iter': 1843, 'weight_class_0': 0.4938521443419942, 'weight_class_1': 3.647897257441321, 'weight_class_2': 3.6627644951810234}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  79%|████████████████████████████████████████████████████████████████████████████████████████████████████████▌                            | 393/500 [12:55<02:46,  1.55s/it]

[I 2026-07-08 16:29:53,896] Trial 382 finished with value: 0.9496204704748298 and parameters: {'C': 0.2794302125181114, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0001522114298761771, 'max_iter': 2958, 'weight_class_0': 0.5057274303153869, 'weight_class_1': 3.691024982925334, 'weight_class_2': 3.2828306951497126}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  79%|████████████████████████████████████████████████████████████████████████████████████████████████████████▊                            | 394/500 [12:58<03:37,  2.05s/it]

[I 2026-07-08 16:29:57,040] Trial 394 pruned.

Best trial: 320. Best value: 0.949752:  79%|█████████████████████████████████████████████████████████████████████████████████████████████████████████                            | 395/500 [13:00<03:31,  2.02s/it]

[I 2026-07-08 16:29:59,040] Trial 395 pruned.

Best trial: 320. Best value: 0.949752:  79%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▎                           | 396/500 [13:09<06:53,  3.98s/it]

[I 2026-07-08 16:30:07,482] Trial 393 finished with value: 0.9495106782730038 and parameters: {'C': 0.0009516665837778429, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00017332104426748702, 'max_iter': 2480, 'weight_class_0': 0.42832530453406864, 'weight_class_1': 2.944278182094846, 'weight_class_2': 3.280674480866212}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  79%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▌                           | 397/500 [13:12<06:41,  3.89s/it]

[I 2026-07-08 16:30:11,228] Trial 396 finished with value: 0.9497077724108376 and parameters: {'C': 0.006243682555173619, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00017556675846033622, 'max_iter': 2474, 'weight_class_0': 0.4653054844190923, 'weight_class_1': 3.572566140806819, 'weight_class_2': 3.0111117867267483}. Best is trial 320 with value: 0.9497521962450051.
[I 2026-07-08 16:30:11,332] Trial 397 finished with value: 0.9496750021426973 and parameters: {'C': 0.0009463600480590076, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0002222242024735223, 'max_iter': 2107, 'weight_class_0': 0.3959245252358518, 'weight_class_1': 3.12213197639543, 'weight_class_2': 2.557463754502323}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▏                          | 399/500 [13:14<04:00,  2.38s/it]

[I 2026-07-08 16:30:12,951] Trial 400 finished with value: 0.9496785881249157 and parameters: {'C': 0.4440104473062448, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00029472533725850744, 'max_iter': 2238, 'weight_class_0': 0.3868605599713367, 'weight_class_1': 3.5838136205894435, 'weight_class_2': 2.5439576171982834}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▍                          | 400/500 [13:17<04:19,  2.59s/it]

[I 2026-07-08 16:30:16,060] Trial 399 finished with value: 0.9497244799886607 and parameters: {'C': 0.351443084529941, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0002197881579997875, 'max_iter': 2086, 'weight_class_0': 0.4281979964799275, 'weight_class_1': 3.176294817391619, 'weight_class_2': 2.9699305113159866}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                          | 401/500 [13:18<03:43,  2.26s/it]

[I 2026-07-08 16:30:17,410] Trial 402 finished with value: 0.9497215656468668 and parameters: {'C': 0.08312702173575617, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0002463393257158032, 'max_iter': 2225, 'weight_class_0': 0.43399136365897983, 'weight_class_1': 3.365539845621084, 'weight_class_2': 2.644320902536661}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▉                          | 402/500 [13:20<03:11,  1.95s/it]

[I 2026-07-08 16:30:18,779] Trial 401 finished with value: 0.9497147684680627 and parameters: {'C': 0.348788823798468, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00022018940240036824, 'max_iter': 4242, 'weight_class_0': 0.47376815935344074, 'weight_class_1': 3.139267823260809, 'weight_class_2': 3.011880671584628}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  81%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▏                         | 403/500 [13:20<02:27,  1.52s/it]

[I 2026-07-08 16:30:19,178] Trial 398 finished with value: 0.949612142166577 and parameters: {'C': 0.4120742721944799, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00019282160447541927, 'max_iter': 2278, 'weight_class_0': 0.42327748986378655, 'weight_class_1': 3.554433373198605, 'weight_class_2': 3.2209409967400027}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  81%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▍                         | 404/500 [13:21<01:54,  1.20s/it]

[I 2026-07-08 16:30:19,639] Trial 403 finished with value: 0.9496713067809928 and parameters: {'C': 0.46129225275918323, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0002457583017109003, 'max_iter': 1985, 'weight_class_0': 0.37693082372940895, 'weight_class_1': 3.436906250110587, 'weight_class_2': 2.528750509682858}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  81%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▋                         | 405/500 [13:24<02:57,  1.87s/it]

[I 2026-07-08 16:30:23,140] Trial 404 finished with value: 0.9496880621144541 and parameters: {'C': 0.07476809466173004, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00021752068114287533, 'max_iter': 1895, 'weight_class_0': 0.41123885948602507, 'weight_class_1': 3.210876266208602, 'weight_class_2': 2.399587426012601}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  81%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▉                         | 406/500 [13:28<04:01,  2.57s/it]

[I 2026-07-08 16:30:27,294] Trial 406 finished with value: 0.9496835466956854 and parameters: {'C': 0.03174181440768149, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00021335592877954926, 'max_iter': 1658, 'weight_class_0': 0.45564789077766193, 'weight_class_1': 3.063246783476379, 'weight_class_2': 2.4572447995528637}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  81%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                        | 407/500 [13:29<03:15,  2.10s/it]

[I 2026-07-08 16:30:28,360] Trial 408 pruned.

Best trial: 320. Best value: 0.949752:  82%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                        | 408/500 [13:30<02:45,  1.80s/it]

[I 2026-07-08 16:30:29,400] Trial 405 finished with value: 0.9493215483994952 and parameters: {'C': 0.3313593862044807, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00019841522060869734, 'max_iter': 1879, 'weight_class_0': 0.38611902534328163, 'weight_class_1': 4.256699856404391, 'weight_class_2': 2.519782674984767}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  82%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                        | 409/500 [13:37<04:50,  3.20s/it]

[I 2026-07-08 16:30:35,939] Trial 407 finished with value: 0.9488683599638785 and parameters: {'C': 0.5136125435132298, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00023978530466361208, 'max_iter': 2241, 'weight_class_0': 0.4565539494000792, 'weight_class_1': 1.3959222397322286, 'weight_class_2': 2.850867035405404}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████                        | 410/500 [13:38<03:55,  2.62s/it]

[I 2026-07-08 16:30:37,121] Trial 412 pruned.

Best trial: 320. Best value: 0.949752:  82%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                       | 411/500 [13:42<04:16,  2.89s/it]

[I 2026-07-08 16:30:40,722] Trial 410 finished with value: 0.9496274038754157 and parameters: {'C': 0.007550029645076763, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00020441579603200914, 'max_iter': 1942, 'weight_class_0': 0.5453942053448206, 'weight_class_1': 3.303972193040164, 'weight_class_2': 2.9377762378887566}. Best is trial 320 with value: 0.9497521962450051.
[I 2026-07-08 16:30:40,734] Trial 409 finished with value: 0.9495670703600219 and parameters: {'C': 0.07021417542994975, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00020817559013639424, 'max_iter': 1882, 'weight_class_0': 0.4403050420957367, 'weight_class_1': 3.5512239740883627, 'weight_class_2': 2.1940917659840995}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                       | 413/500 [13:45<03:14,  2.24s/it]

[I 2026-07-08 16:30:43,630] Trial 411 finished with value: 0.9496546171236109 and parameters: {'C': 0.2913289158868886, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0002405483104581143, 'max_iter': 2022, 'weight_class_0': 0.3441996478876099, 'weight_class_1': 3.2381135125875344, 'weight_class_2': 2.2206303295685843}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  83%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████                       | 414/500 [13:47<03:19,  2.32s/it]

[I 2026-07-08 16:30:46,179] Trial 413 finished with value: 0.9497134819281332 and parameters: {'C': 0.3306884522479871, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00024071427284610235, 'max_iter': 1991, 'weight_class_0': 0.35151073245684183, 'weight_class_1': 2.8720237064053644, 'weight_class_2': 2.191556558798925}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  83%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                      | 415/500 [13:48<02:53,  2.04s/it]

[I 2026-07-08 16:30:47,448] Trial 414 finished with value: 0.9495181323547758 and parameters: {'C': 0.20609080657634207, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00024423167776133314, 'max_iter': 2042, 'weight_class_0': 0.3321552577932571, 'weight_class_1': 2.4741156267233393, 'weight_class_2': 2.802349602333709}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  83%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                      | 415/500 [13:49<02:53,  2.04s/it]

[I 2026-07-08 16:30:47,713] Trial 415 finished with value: 0.9496920846961106 and parameters: {'C': 0.13725810021537965, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00021478304839364024, 'max_iter': 4975, 'weight_class_0': 0.3566061433088038, 'weight_class_1': 2.733363594001924, 'weight_class_2': 2.0421554757912617}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  83%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                      | 417/500 [13:52<02:37,  1.90s/it]

[I 2026-07-08 16:30:50,607] Trial 416 finished with value: 0.9496337350458376 and parameters: {'C': 0.24898514979081124, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00024058902322367796, 'max_iter': 1691, 'weight_class_0': 0.3478436749216536, 'weight_class_1': 2.777398922191195, 'weight_class_2': 2.657737143216898}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                     | 418/500 [13:55<03:04,  2.25s/it]

[I 2026-07-08 16:30:53,718] Trial 417 finished with value: 0.9495433575443339 and parameters: {'C': 0.2883560726859774, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00023159935733620544, 'max_iter': 4601, 'weight_class_0': 0.36234225713508805, 'weight_class_1': 2.7083706625492576, 'weight_class_2': 2.9159635699493416}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                     | 419/500 [13:55<02:27,  1.83s/it]

[I 2026-07-08 16:30:54,382] Trial 418 finished with value: 0.9496751698019856 and parameters: {'C': 0.29428597527125333, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00022447690144343588, 'max_iter': 2186, 'weight_class_0': 0.36128424001988557, 'weight_class_1': 2.882548847037441, 'weight_class_2': 2.0494871602789067}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                     | 419/500 [13:57<02:27,  1.83s/it]

[I 2026-07-08 16:30:55,854] Trial 419 finished with value: 0.949705967699996 and parameters: {'C': 0.3210566118033324, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00023312367679923022, 'max_iter': 3536, 'weight_class_0': 0.3222681736360994, 'weight_class_1': 2.664105554151036, 'weight_class_2': 2.0586375993423136}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  84%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                     | 421/500 [14:03<03:59,  3.03s/it]

[I 2026-07-08 16:31:02,082] Trial 420 finished with value: 0.9492673900848434 and parameters: {'C': 0.21351511556717787, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00027405314523128394, 'max_iter': 2185, 'weight_class_0': 0.4475775125551297, 'weight_class_1': 2.6833505713188783, 'weight_class_2': 1.9376849642827187}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  84%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                    | 422/500 [14:05<03:36,  2.77s/it]

[I 2026-07-08 16:31:04,270] Trial 421 finished with value: 0.9496386838154699 and parameters: {'C': 0.11663247518183878, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00022679354390468438, 'max_iter': 2112, 'weight_class_0': 0.3056241841354875, 'weight_class_1': 2.5659032960051404, 'weight_class_2': 2.230419885857925}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  85%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                    | 423/500 [14:09<03:50,  2.99s/it]

[I 2026-07-08 16:31:07,881] Trial 422 finished with value: 0.9493898909488762 and parameters: {'C': 0.09943188305908121, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0002318129818738693, 'max_iter': 3586, 'weight_class_0': 0.29834274308059217, 'weight_class_1': 2.6228198574705694, 'weight_class_2': 2.769487972360939}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  85%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                    | 424/500 [14:10<03:07,  2.47s/it]

[I 2026-07-08 16:31:08,891] Trial 423 finished with value: 0.9494161997397036 and parameters: {'C': 0.17696307669089645, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0002410790453347673, 'max_iter': 3587, 'weight_class_0': 0.3355481144834268, 'weight_class_1': 2.896923763266888, 'weight_class_2': 2.9969879995139155}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████                    | 425/500 [14:11<02:21,  1.88s/it]

[I 2026-07-08 16:31:09,672] Trial 430 pruned.

Best trial: 320. Best value: 0.949752:  85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                   | 426/500 [14:12<02:12,  1.80s/it]

[I 2026-07-08 16:31:11,150] Trial 424 finished with value: 0.9496973046721002 and parameters: {'C': 0.2455936976021186, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0002428274694221022, 'max_iter': 4510, 'weight_class_0': 0.45565013519346836, 'weight_class_1': 2.837018380944297, 'weight_class_2': 2.736020801966527}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  85%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                   | 427/500 [14:14<02:01,  1.67s/it]

[I 2026-07-08 16:31:12,576] Trial 427 finished with value: 0.9494944678372729 and parameters: {'C': 0.2511259124172911, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0002730154154694286, 'max_iter': 4005, 'weight_class_0': 0.2782113976979145, 'weight_class_1': 2.741298054930243, 'weight_class_2': 2.1548416448780587}. Best is trial 320 with value: 0.9497521962450051.
[I 2026-07-08 16:31:12,701] Trial 426 finished with value: 0.9494718926420909 and parameters: {'C': 0.12248533704210629, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00028313307001573136, 'max_iter': 2171, 'weight_class_0': 0.320033835299391, 'weight_class_1': 2.0740883455936165, 'weight_class_2': 2.764812514847145}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  86%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                   | 428/500 [14:14<01:31,  1.27s/it]

[I 2026-07-08 16:31:12,950] Trial 425 finished with value: 0.9495016664525124 and parameters: {'C': 0.15603759076004162, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0002609075966407664, 'max_iter': 4666, 'weight_class_0': 0.3167117371500414, 'weight_class_1': 2.9965601119141465, 'weight_class_2': 2.6666620407794728}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                  | 430/500 [14:17<01:36,  1.38s/it]

[I 2026-07-08 16:31:15,911] Trial 428 finished with value: 0.9496267153072597 and parameters: {'C': 0.32629031783583007, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00026516468014611545, 'max_iter': 4506, 'weight_class_0': 0.3106251337485417, 'weight_class_1': 2.468177895037021, 'weight_class_2': 1.578295354705778}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                  | 431/500 [14:22<02:43,  2.36s/it]

[I 2026-07-08 16:31:21,258] Trial 429 finished with value: 0.9495636710971898 and parameters: {'C': 0.394156932544578, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00022144431400520625, 'max_iter': 3549, 'weight_class_0': 0.32519611930772996, 'weight_class_1': 3.2690198273648616, 'weight_class_2': 1.9763021145196678}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  86%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                  | 432/500 [14:23<02:19,  2.05s/it]

[I 2026-07-08 16:31:22,468] Trial 431 finished with value: 0.949743734178748 and parameters: {'C': 0.15610200623630247, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0002691583683670351, 'max_iter': 4561, 'weight_class_0': 0.31970895345325523, 'weight_class_1': 2.374757335828291, 'weight_class_2': 2.0024027018500874}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  87%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                 | 433/500 [14:29<03:22,  3.02s/it]

[I 2026-07-08 16:31:27,824] Trial 432 finished with value: 0.9496917344824973 and parameters: {'C': 0.1547532656212728, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00028536164190838434, 'max_iter': 2078, 'weight_class_0': 0.28413180581005576, 'weight_class_1': 2.619240926493927, 'weight_class_2': 1.7550329002599239}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  87%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                 | 434/500 [14:36<04:26,  4.04s/it]

[I 2026-07-08 16:31:34,723] Trial 435 finished with value: 0.9497000065715675 and parameters: {'C': 0.5715631755965657, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0002715656225402955, 'max_iter': 2332, 'weight_class_0': 0.2970466568437698, 'weight_class_1': 1.8885357914085739, 'weight_class_2': 1.7770996909667867}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  87%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                 | 435/500 [14:37<03:31,  3.26s/it]

[I 2026-07-08 16:31:36,033] Trial 436 finished with value: 0.9496541809346487 and parameters: {'C': 0.37905413849137964, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0002916042670222465, 'max_iter': 3484, 'weight_class_0': 0.27090209864060827, 'weight_class_1': 2.5128574018865164, 'weight_class_2': 1.8939398338885687}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  87%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                 | 436/500 [14:40<03:14,  3.04s/it]

[I 2026-07-08 16:31:38,432] Trial 437 finished with value: 0.9496806016323613 and parameters: {'C': 0.414701487316025, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0002742566752955446, 'max_iter': 4499, 'weight_class_0': 0.3142139219544539, 'weight_class_1': 2.541602561013819, 'weight_class_2': 1.8113403891517026}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  87%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                | 437/500 [14:41<02:49,  2.68s/it]

[I 2026-07-08 16:31:40,379] Trial 438 finished with value: 0.9496612742495767 and parameters: {'C': 0.3179448268995893, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00027436382933567995, 'max_iter': 4309, 'weight_class_0': 0.32488012707318425, 'weight_class_1': 2.3045485644112187, 'weight_class_2': 1.8750198470599797}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                | 438/500 [14:42<02:14,  2.18s/it]

[I 2026-07-08 16:31:41,302] Trial 433 finished with value: 0.9496779571821481 and parameters: {'C': 0.46288883515048745, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00018727560016040275, 'max_iter': 4026, 'weight_class_0': 0.28794580261194647, 'weight_class_1': 2.053728580149229, 'weight_class_2': 1.7473460015830808}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  88%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                | 439/500 [14:43<01:50,  1.81s/it]

[I 2026-07-08 16:31:42,057] Trial 442 finished with value: 0.9496415176670453 and parameters: {'C': 0.4216554128909054, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.002507863957694058, 'max_iter': 4493, 'weight_class_0': 0.3967814878838372, 'weight_class_1': 2.235789124709073, 'weight_class_2': 2.329920398393409}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                | 440/500 [14:47<02:22,  2.37s/it]

[I 2026-07-08 16:31:45,827] Trial 434 finished with value: 0.9494559150765355 and parameters: {'C': 0.38491111103669823, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00019059865868250645, 'max_iter': 3826, 'weight_class_0': 0.31995603175038256, 'weight_class_1': 2.411241117231036, 'weight_class_2': 1.477622026089122}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎               | 441/500 [14:48<01:51,  1.89s/it]

[I 2026-07-08 16:31:46,770] Trial 440 finished with value: 0.9496205101396619 and parameters: {'C': 0.4335551260851323, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00019552529720513143, 'max_iter': 4557, 'weight_class_0': 0.40474840544560636, 'weight_class_1': 2.2419630587153905, 'weight_class_2': 2.129811954794228}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌               | 442/500 [14:52<02:28,  2.56s/it]

[I 2026-07-08 16:31:50,815] Trial 439 finished with value: 0.9494623406824377 and parameters: {'C': 0.37993039194872946, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00018963296741194584, 'max_iter': 4804, 'weight_class_0': 0.3904387206728617, 'weight_class_1': 2.8678315156934975, 'weight_class_2': 1.8602081009982825}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  89%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊               | 443/500 [14:56<02:50,  3.00s/it]

[I 2026-07-08 16:31:54,813] Trial 441 finished with value: 0.9494589570819334 and parameters: {'C': 0.42479734542744596, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0001916402932166634, 'max_iter': 4294, 'weight_class_0': 0.4009568073420973, 'weight_class_1': 2.9359790445660026, 'weight_class_2': 1.8446612631510568}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████               | 444/500 [14:57<02:13,  2.38s/it]

[I 2026-07-08 16:31:55,762] Trial 443 finished with value: 0.9495104925907173 and parameters: {'C': 0.37320504122814024, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0001973066727738293, 'max_iter': 4342, 'weight_class_0': 0.3684633062124971, 'weight_class_1': 1.948888101005353, 'weight_class_2': 1.8524048101055115}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎              | 445/500 [15:02<02:52,  3.13s/it]

[I 2026-07-08 16:32:00,657] Trial 444 finished with value: 0.9497166998550283 and parameters: {'C': 0.38014619436450503, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00019405545103178072, 'max_iter': 4363, 'weight_class_0': 0.24805550366886792, 'weight_class_1': 2.1049848584560467, 'weight_class_2': 1.644406486232507}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋              | 446/500 [15:05<02:46,  3.08s/it]

[I 2026-07-08 16:32:03,329] Trial 446 finished with value: 0.9493237374727352 and parameters: {'C': 0.42296791732513217, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0003486541284599345, 'max_iter': 4851, 'weight_class_0': 0.4209802299299157, 'weight_class_1': 1.9041489956177509, 'weight_class_2': 1.9144854469754713}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  89%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉              | 447/500 [15:05<02:02,  2.31s/it]

[I 2026-07-08 16:32:04,034] Trial 447 finished with value: 0.9494208824410961 and parameters: {'C': 0.4955067158484113, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0003300737492080596, 'max_iter': 4250, 'weight_class_0': 0.25716434514960607, 'weight_class_1': 2.4255047932571125, 'weight_class_2': 2.237720722837988}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏             | 448/500 [15:08<02:00,  2.32s/it]

[I 2026-07-08 16:32:06,566] Trial 449 finished with value: 0.9488511757120502 and parameters: {'C': 0.5527342200826467, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0003328548848006917, 'max_iter': 2338, 'weight_class_0': 0.38459577759059366, 'weight_class_1': 1.6344960139577285, 'weight_class_2': 1.2662865876403075}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍             | 449/500 [15:08<01:29,  1.75s/it]

[I 2026-07-08 16:32:06,890] Trial 451 pruned.

Best trial: 320. Best value: 0.949752:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋             | 450/500 [15:10<01:25,  1.71s/it]

[I 2026-07-08 16:32:08,605] Trial 445 finished with value: 0.9494897437885983 and parameters: {'C': 0.39770629820208286, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0001924362231251565, 'max_iter': 4374, 'weight_class_0': 0.23598162565415834, 'weight_class_1': 1.6428508673411044, 'weight_class_2': 1.8609063372805188}. Best is trial 320 with value: 0.9497521962450051.
[I 2026-07-08 16:32:08,608] Trial 450 finished with value: 0.9492302400258372 and parameters: {'C': 0.5870869098049484, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0003453972184663449, 'max_iter': 4182, 'weight_class_0': 0.36682322283481694, 'weight_class_1': 1.6117503653464054, 'weight_class_2': 1.5278741044756086}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏            | 452/500 [15:16<01:54,  2.38s/it]

[I 2026-07-08 16:32:14,757] Trial 448 finished with value: 0.9495021979722077 and parameters: {'C': 0.5595398832116004, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00019605322866342182, 'max_iter': 4328, 'weight_class_0': 0.25016231874308575, 'weight_class_1': 2.0691635877058068, 'weight_class_2': 2.0527570097927987}. Best is trial 320 with value: 0.9497521962450051.
[I 2026-07-08 16:32:14,831] Trial 452 finished with value: 0.949331401014555 and parameters: {'C': 0.5607209188459737, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00021521858266739988, 'max_iter': 2351, 'weight_class_0': 0.37205270124287504, 'weight_class_1': 1.846647995641729, 'weight_class_2': 1.5785482448791075}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  91%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊            | 454/500 [15:18<01:27,  1.91s/it]

[I 2026-07-08 16:32:17,324] Trial 453 finished with value: 0.9494520006581914 and parameters: {'C': 0.21322759562135887, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00034382199212721693, 'max_iter': 3670, 'weight_class_0': 0.361798842183119, 'weight_class_1': 1.9830888780641838, 'weight_class_2': 1.662367384945379}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████            | 455/500 [15:23<01:52,  2.50s/it]

[I 2026-07-08 16:32:21,841] Trial 454 finished with value: 0.9490722311731782 and parameters: {'C': 0.6270741727458555, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0002209667550695816, 'max_iter': 2373, 'weight_class_0': 0.44457663617009147, 'weight_class_1': 1.8985473980731757, 'weight_class_2': 1.670277087995742}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎           | 456/500 [15:25<01:45,  2.39s/it]

[I 2026-07-08 16:32:23,811] Trial 455 finished with value: 0.9497364439370954 and parameters: {'C': 0.5905541551547445, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00021839478209438305, 'max_iter': 2315, 'weight_class_0': 0.2510370025832637, 'weight_class_1': 1.782286198844608, 'weight_class_2': 1.5175153901439715}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  91%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌           | 457/500 [15:28<01:53,  2.63s/it]

[I 2026-07-08 16:32:27,242] Trial 460 pruned.

Best trial: 320. Best value: 0.949752:  92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊           | 458/500 [15:29<01:29,  2.14s/it]

[I 2026-07-08 16:32:28,005] Trial 456 finished with value: 0.949523143984519 and parameters: {'C': 0.21197079506851374, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00021293612564813572, 'max_iter': 4791, 'weight_class_0': 0.26514813444022106, 'weight_class_1': 2.220562426713288, 'weight_class_2': 1.3137100387305964}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████           | 459/500 [15:33<01:52,  2.75s/it]

[I 2026-07-08 16:32:32,323] Trial 457 finished with value: 0.9496121241730826 and parameters: {'C': 0.21114739684658967, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00021253490379029286, 'max_iter': 4176, 'weight_class_0': 0.24089889761855532, 'weight_class_1': 2.1869913720966028, 'weight_class_2': 1.277101671220742}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎          | 460/500 [15:34<01:29,  2.23s/it]

[I 2026-07-08 16:32:33,309] Trial 458 finished with value: 0.9497415170781558 and parameters: {'C': 0.17892191055753107, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00021250691799867114, 'max_iter': 4694, 'weight_class_0': 0.23617419342487195, 'weight_class_1': 2.1367956466406746, 'weight_class_2': 1.4347833086342638}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋          | 461/500 [15:36<01:17,  1.99s/it]

[I 2026-07-08 16:32:34,613] Trial 465 pruned.
[I 2026-07-08 16:32:34,685] Trial 459 finished with value: 0.949412446994408 and parameters: {'C': 0.18876035846558822, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00021439405703908764, 'max_iter': 3734, 'weight_class_0': 0.22632968201874207, 'weight_class_1': 2.0383492599698996, 'weight_class_2': 2.054232697794328}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  93%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏         | 463/500 [15:39<01:06,  1.79s/it]

[I 2026-07-08 16:32:37,790] Trial 466 pruned.
[I 2026-07-08 16:32:37,830] Trial 468 pruned.

Best trial: 320. Best value: 0.949752:  93%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋         | 465/500 [15:40<00:43,  1.25s/it]

[I 2026-07-08 16:32:38,600] Trial 461 finished with value: 0.9495879026223099 and parameters: {'C': 0.1717438899026287, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00021979464475809171, 'max_iter': 4748, 'weight_class_0': 0.22513741123180894, 'weight_class_1': 2.153489084552024, 'weight_class_2': 1.3107705195511545}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  93%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉         | 466/500 [15:40<00:35,  1.06s/it]

[I 2026-07-08 16:32:38,660] Trial 462 finished with value: 0.949643097609477 and parameters: {'C': 0.0857639207136576, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00021123191226049364, 'max_iter': 4169, 'weight_class_0': 0.2403359927417434, 'weight_class_1': 2.1531656412032985, 'weight_class_2': 1.280689598095432}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  93%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏        | 467/500 [15:41<00:36,  1.11s/it]

[I 2026-07-08 16:32:40,225] Trial 467 pruned.

Best trial: 320. Best value: 0.949752:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍        | 468/500 [15:44<00:48,  1.51s/it]

[I 2026-07-08 16:32:42,950] Trial 464 finished with value: 0.9492884573197952 and parameters: {'C': 0.07621211498901169, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00021958185451512787, 'max_iter': 4708, 'weight_class_0': 0.2066830331225099, 'weight_class_1': 2.266848524301796, 'weight_class_2': 1.6603409567460201}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊        | 469/500 [15:45<00:43,  1.39s/it]

[I 2026-07-08 16:32:43,977] Trial 469 pruned.

Best trial: 320. Best value: 0.949752:  94%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████        | 470/500 [15:45<00:34,  1.14s/it]

[I 2026-07-08 16:32:44,346] Trial 463 finished with value: 0.9495594448610906 and parameters: {'C': 0.18639321283777774, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00023173721472345365, 'max_iter': 4456, 'weight_class_0': 0.4578268034447805, 'weight_class_1': 2.169149738076555, 'weight_class_2': 2.4466761677238567}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  94%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎       | 471/500 [15:50<00:59,  2.06s/it]

[I 2026-07-08 16:32:48,866] Trial 470 pruned.

Best trial: 320. Best value: 0.949752:  94%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 472/500 [15:51<00:52,  1.88s/it]

[I 2026-07-08 16:32:50,359] Trial 471 pruned.

Best trial: 320. Best value: 0.949752:  95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊       | 473/500 [15:52<00:43,  1.60s/it]

[I 2026-07-08 16:32:51,191] Trial 472 pruned.

Best trial: 320. Best value: 0.949752:  95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████       | 474/500 [15:59<01:21,  3.15s/it]

[I 2026-07-08 16:32:58,038] Trial 478 pruned.

Best trial: 320. Best value: 0.949752:  95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎      | 475/500 [15:59<00:58,  2.33s/it]

[I 2026-07-08 16:32:58,323] Trial 475 pruned.

Best trial: 320. Best value: 0.949752:  95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌      | 476/500 [16:01<00:53,  2.22s/it]

[I 2026-07-08 16:33:00,287] Trial 473 finished with value: 0.9494781722624446 and parameters: {'C': 0.08855921816494246, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00042953839797532406, 'max_iter': 4607, 'weight_class_0': 0.2281732882648248, 'weight_class_1': 2.3949658462309102, 'weight_class_2': 1.39948544519831}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉      | 477/500 [16:08<01:20,  3.49s/it]

[I 2026-07-08 16:33:06,971] Trial 480 pruned.

Best trial: 320. Best value: 0.949752:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍     | 479/500 [16:09<00:40,  1.92s/it]

[I 2026-07-08 16:33:07,754] Trial 474 finished with value: 0.9495538380483172 and parameters: {'C': 0.14845468851311597, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0002551475991641805, 'max_iter': 4653, 'weight_class_0': 0.23357110992900854, 'weight_class_1': 1.3828769504079095, 'weight_class_2': 1.1717479621110563}. Best is trial 320 with value: 0.9497521962450051.
[I 2026-07-08 16:33:07,845] Trial 482 pruned.

Best trial: 320. Best value: 0.949752:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋     | 480/500 [16:09<00:29,  1.46s/it]

[I 2026-07-08 16:33:08,208] Trial 477 finished with value: 0.9497203245572994 and parameters: {'C': 0.09915060869844439, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00025272248253080284, 'max_iter': 4607, 'weight_class_0': 0.21535032698823484, 'weight_class_1': 1.68609434040697, 'weight_class_2': 1.4590108087378613}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉     | 481/500 [16:15<00:54,  2.86s/it]

[I 2026-07-08 16:33:14,294] Trial 484 pruned.

Best trial: 320. Best value: 0.949752:  96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏    | 482/500 [16:16<00:39,  2.20s/it]

[I 2026-07-08 16:33:14,941] Trial 476 finished with value: 0.9495778669031439 and parameters: {'C': 0.022638765803787826, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0001730322183461577, 'max_iter': 4583, 'weight_class_0': 0.21833582940420845, 'weight_class_1': 1.4391831629936835, 'weight_class_2': 1.558179503777077}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏    | 482/500 [16:21<00:39,  2.20s/it]

[I 2026-07-08 16:33:19,319] Trial 483 finished with value: 0.9494218089522237 and parameters: {'C': 0.11524477141366145, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0004192435142127294, 'max_iter': 2451, 'weight_class_0': 0.24858094134895448, 'weight_class_1': 1.673985003953927, 'weight_class_2': 1.1135164089992164}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  97%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋    | 484/500 [16:22<00:38,  2.43s/it]

[I 2026-07-08 16:33:20,932] Trial 481 finished with value: 0.9496480850602464 and parameters: {'C': 0.032152015516516724, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00017679761844238738, 'max_iter': 2462, 'weight_class_0': 0.24125871964619444, 'weight_class_1': 1.6422082821171107, 'weight_class_2': 1.647571515209356}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  97%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████    | 485/500 [16:23<00:32,  2.15s/it]

[I 2026-07-08 16:33:22,379] Trial 485 pruned.

Best trial: 320. Best value: 0.949752:  97%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎   | 486/500 [16:26<00:30,  2.16s/it]

[I 2026-07-08 16:33:24,614] Trial 479 finished with value: 0.9496120679101308 and parameters: {'C': 0.13584010409027053, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0001677234752811906, 'max_iter': 4862, 'weight_class_0': 0.24839755225285085, 'weight_class_1': 1.7412219441711008, 'weight_class_2': 1.4236213576421048}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  97%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌   | 487/500 [16:28<00:28,  2.19s/it]

[I 2026-07-08 16:33:26,778] Trial 488 pruned.
[I 2026-07-08 16:33:26,867] Trial 486 pruned.

Best trial: 320. Best value: 0.949752:  98%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████   | 489/500 [16:35<00:36,  3.29s/it]

[I 2026-07-08 16:33:34,309] Trial 490 pruned.

Best trial: 320. Best value: 0.949752:  98%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎  | 490/500 [16:39<00:34,  3.42s/it]

[I 2026-07-08 16:33:38,050] Trial 491 finished with value: 0.9496071732759178 and parameters: {'C': 0.04019596049868701, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0002975600729386503, 'max_iter': 4616, 'weight_class_0': 0.20761758369995703, 'weight_class_1': 1.7358776759972063, 'weight_class_2': 1.5597982570464244}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  98%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 491/500 [16:40<00:25,  2.83s/it]

[I 2026-07-08 16:33:39,523] Trial 487 finished with value: 0.9497330603911542 and parameters: {'C': 0.14186150743375606, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00018777285266411166, 'max_iter': 4622, 'weight_class_0': 0.27067157617512755, 'weight_class_1': 1.8076642630397504, 'weight_class_2': 1.6576631058111353}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏ | 493/500 [16:44<00:15,  2.21s/it]

[I 2026-07-08 16:33:43,146] Trial 493 finished with value: 0.9495280830901317 and parameters: {'C': 0.2823227705462136, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0002972396999012125, 'max_iter': 2161, 'weight_class_0': 0.17631055944085114, 'weight_class_1': 1.7635194445938664, 'weight_class_2': 1.3391581712740248}. Best is trial 320 with value: 0.9497521962450051.
[I 2026-07-08 16:33:43,336] Trial 492 finished with value: 0.9493220312038464 and parameters: {'C': 0.039107045931197924, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00024301549808203633, 'max_iter': 4560, 'weight_class_0': 0.1793252455404535, 'weight_class_1': 1.188945736940833, 'weight_class_2': 1.6763203201333052}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍ | 494/500 [16:48<00:15,  2.50s/it]

[I 2026-07-08 16:33:46,585] Trial 494 finished with value: 0.9496659873440902 and parameters: {'C': 0.044793236216944234, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00024317330739183254, 'max_iter': 4622, 'weight_class_0': 0.20155214637440577, 'weight_class_1': 1.818075569412315, 'weight_class_2': 1.5414400315826966}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉ | 496/500 [16:48<00:05,  1.35s/it]

[I 2026-07-08 16:33:46,933] Trial 496 finished with value: 0.9496046490482508 and parameters: {'C': 0.05300383216302934, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00029370459287521154, 'max_iter': 4548, 'weight_class_0': 0.18189184057816946, 'weight_class_1': 1.255589383617017, 'weight_class_2': 1.3869952992416859}. Best is trial 320 with value: 0.9497521962450051.
[I 2026-07-08 16:33:47,110] Trial 489 finished with value: 0.949612624614742 and parameters: {'C': 0.26344199386752115, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00018639585193523723, 'max_iter': 2440, 'weight_class_0': 0.2506325971775389, 'weight_class_1': 1.7058826121059572, 'weight_class_2': 1.659768606188662}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752:  99%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏| 497/500 [16:49<00:03,  1.16s/it]

[I 2026-07-08 16:33:47,815] Trial 495 finished with value: 0.9495954952542407 and parameters: {'C': 0.04852262895753875, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00024292223310440933, 'max_iter': 2576, 'weight_class_0': 0.2824370874480394, 'weight_class_1': 1.7878342954700925, 'weight_class_2': 1.4438778838087711}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍| 498/500 [16:49<00:02,  1.00s/it]

[I 2026-07-08 16:33:48,457] Trial 497 finished with value: 0.94925565438709 and parameters: {'C': 0.25319371502331134, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00030262112912856335, 'max_iter': 4705, 'weight_class_0': 0.19432444497875603, 'weight_class_1': 1.1337130736343826, 'weight_class_2': 1.741145708636521}. Best is trial 320 with value: 0.9497521962450051.

Best trial: 320. Best value: 0.949752: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 500/500 [16:50<00:00,  2.02s/it]

[I 2026-07-08 16:33:48,707] Trial 499 finished with value: 0.9493121221330758 and parameters: {'C': 0.053437951140203825, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0003022478366219594, 'max_iter': 4648, 'weight_class_0': 0.18764628089020385, 'weight_class_1': 1.8668121836642209, 'weight_class_2': 1.6699953451770189}. Best is trial 320 with value: 0.9497521962450051.
[I 2026-07-08 16:33:48,857] Trial 498 finished with value: 0.9490095834950196 and parameters: {'C': 0.05934892750671261, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0003002000598966914, 'max_iter': 4629, 'weight_class_0': 0.16015575303819574, 'weight_class_1': 1.8338006593817024, 'weight_class_2': 1.5502079022726156}. Best is trial 320 with value: 0.9497521962450051.

Best trial score:
0.9497521962450051

Best params:
{'C': 0.016583182054671262, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0010484096989234488, 'max_iter': 2941, 'weight_class_0': 0.7574214432061076, 'weight_class_1': 6.716577353226011, 'weight_class_2': 4.729921076750412}

In [43]:
lg_params = {k: v for k, v in study.best_params.items() if k not in ['weight_class_0', 'weight_class_1', 'weight_class_2']}

lg = LogisticRegression(
    solver="lbfgs",
    l1_ratio=0.0,
    random_state=42,
    **lg_params
).fit(X_train, y_train.health_condition)

test_proba = lg.predict_proba(X_test)

weights = np.array([study.best_params['weight_class_0'], study.best_params['weight_class_1'], study.best_params['weight_class_2']])
weighted_probas = test_proba * weights

pred = np.argmax(weighted_probas, axis=1)

In [44]:
sub_labels = label_encoder.inverse_transform(pred)

# Submission

In [45]:
submission = pd.read_csv('../data/submission/sample_submission.csv')
submission['health_condition'] = sub_labels

submission.to_csv('../data/submission/submission_from_5.4.1_xgboost_lightgbm_catboost_stacking_submission.csv', index=False)

In [46]:
submission.head()

       id health_condition
0  690088        unhealthy
1  690089        unhealthy
2  690090          at-risk
3  690091          at-risk
4  690092        unhealthy

In [47]:
X_train.columns

Index(['lgbm_0', 'lgbm_1', 'lgbm_2', 'xgb_0', 'xgb_1', 'xgb_2', 'cat_0',
       'cat_1', 'cat_2'],
      dtype='str')

In [48]:
len(study.trials)

500