# Imports

In [1]:
import optuna

import numpy as np
import pandas as pd

from sklearn.metrics import balanced_accuracy_score, log_loss
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold, cross_val_predict

/home/junior/Documentos/GitHub/kaggle-competition-predicting-student-health/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Utils

In [2]:
def load_pickle(file_path):
    with open(file_path, 'rb') as file:
        return pickle.load(file)

# Loading Datasets

In [3]:
X_train = pd.read_parquet('../data/processed/X_train_stacking_layer_one.parquet') #.drop(to_drop, axis=1)
y_train = pd.read_parquet('../data/interim/y_train.parquet')

X_test = pd.read_parquet('../data/processed/X_test_stacking_layer_one.parquet') #.drop(to_drop, axis=1)

In [4]:
X_train.head()

,lgbm_0,lgbm_1,lgbm_2,xgb_0,xgb_1,xgb_2,cat_0,cat_1,cat_2
0,0.004831,0.002142,0.993027,0.005220,0.002128,0.992652,0.005655,0.000463,0.993882
1,0.998229,0.000143,0.001628,0.997774,0.000322,0.001904,0.994638,0.000368,0.004994
2,0.003982,0.000584,0.995434,0.002362,0.000710,0.996928,0.002327,0.000919,0.996754
3,0.007424,0.001954,0.990622,0.002922,0.003628,0.993450,0.003433,0.002374,0.994194
4,0.993583,0.000012,0.006405,0.997151,0.000013,0.002836,0.994112,0.000005,0.005883

In [5]:
X_test.head()

,lgbm_0,lgbm_1,lgbm_2,xgb_0,xgb_1,xgb_2,cat_0,cat_1,cat_2
0,0.011986,0.002516,0.985498,0.009749,0.003956,0.986295,0.008185,0.005526,0.986288
1,0.469590,0.002922,0.527488,0.344531,0.002104,0.653365,0.530403,0.002094,0.467503
2,0.998492,0.000991,0.000517,0.998555,0.001132,0.000313,0.996306,0.003216,0.000478
3,0.986619,0.000009,0.013372,0.978274,0.000024,0.021702,0.990683,0.000093,0.009224
4,0.008520,0.001975,0.989505,0.005601,0.002080,0.992319,0.003507,0.001947,0.994546

# Machine Learning

In [ ]:
def objective(trial, X, y):
    
    l1_ratio = trial.suggest_float("l1_ratio", 0.0, 1.0)
    C = trial.suggest_float("C", 1e-5, 100.0, log=True)
    class_weight = trial.suggest_categorical("class_weight", [None, "balanced"])
    fit_intercept = trial.suggest_categorical("fit_intercept", [True, False])
    tol = trial.suggest_float("tol", 1e-6, 1e-2, log=True)
    max_iter = trial.suggest_int("max_iter", 1000, 5000)

    w0 = trial.suggest_float('weight_class_0', 0.05, 10.0, log=True)
    w1 = trial.suggest_float('weight_class_1', 0.05, 10.0, log=True)
    w2 = trial.suggest_float('weight_class_2', 0.05, 10.0, log=True)
    weights = np.array([w0, w1, w2])

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    scores = []

    for fold, (train_idx, valid_idx) in enumerate(cv.split(X, y)):
        
        X_train_fold, X_valid_fold = X.iloc[train_idx, :], X.iloc[valid_idx, :]
        y_train_fold, y_valid_fold = y.iloc[train_idx], y.iloc[valid_idx]

        model = LogisticRegression(
            solver="saga",
            C=C,
            l1_ratio=l1_ratio,
            class_weight=class_weight,
            fit_intercept=fit_intercept,
            tol=tol,
            max_iter=max_iter,
            random_state=42,
        ).fit(X_train_fold, y_train_fold)

        proba = model.predict_proba(X_valid_fold)
        
        weighted_probas = proba * weights
        pred = np.argmax(weighted_probas, axis=1)
        
        score = balanced_accuracy_score(y_valid_fold, pred)
        scores.append(score)

        trial.report(np.mean(scores), step=fold)
        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()

    return np.mean(scores)


study = optuna.create_study(
    direction="maximize", 
    sampler=optuna.samplers.TPESampler(seed=42), 
    pruner=optuna.pruners.MedianPruner(n_warmup_steps=2)
)

study.optimize(
    lambda trial: objective(trial, X_train, y_train.health_condition), 
    n_trials=30, 
    n_jobs=-1, 
    show_progress_bar=True
)

print("\nBest trial score:")
print(study.best_trial.value)

print("\nBest params:")
print(study.best_trial.params)

[I 2026-07-05 15:50:45,094] A new study created in memory with name: no-name-77c8b126-b7a4-4ee9-8970-9b9c3f06edc0
Best trial: 6. Best value: 0.88965:   3%|████▋                                                                                                                                      | 1/30 [00:37<18:16, 37.80s/it]

[I 2026-07-05 15:51:22,878] Trial 6 finished with value: 0.8896502827517431 and parameters: {'l1_ratio': 0.8599735073948968, 'C': 0.061724338790983, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0007242402287206063, 'max_iter': 2995, 'weight_class_0': 0.6354361120667588, 'weight_class_1': 7.150304299616766, 'weight_class_2': 0.06786627877696891}. Best is trial 6 with value: 0.8896502827517431.

Best trial: 6. Best value: 0.88965:   7%|█████████▎                                                                                                                                 | 2/30 [00:43<08:44, 18.75s/it]

[I 2026-07-05 15:51:28,300] Trial 8 finished with value: 0.8360329086730831 and parameters: {'l1_ratio': 0.1071608892526591, 'C': 26.16360974044426, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0008706098904997742, 'max_iter': 1895, 'weight_class_0': 2.2576772773047344, 'weight_class_1': 0.1285033632156152, 'weight_class_2': 0.08240698902933564}. Best is trial 6 with value: 0.8896502827517431.

Best trial: 7. Best value: 0.893531:  10%|█████████████▊                                                                                                                            | 3/30 [00:45<05:03, 11.25s/it]

[I 2026-07-05 15:51:30,638] Trial 7 finished with value: 0.8935313100836761 and parameters: {'l1_ratio': 0.0683416055763858, 'C': 6.126555994285845, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0009859065802969818, 'max_iter': 2942, 'weight_class_0': 0.34805951131481633, 'weight_class_1': 0.6916144100572366, 'weight_class_2': 0.4405751364560168}. Best is trial 7 with value: 0.8935313100836761.

Best trial: 5. Best value: 0.912938:  13%|██████████████████▍                                                                                                                       | 4/30 [00:50<03:45,  8.68s/it]

[I 2026-07-05 15:51:35,380] Trial 5 finished with value: 0.912938463873019 and parameters: {'l1_ratio': 0.051072491658785246, 'C': 0.00045171512854482387, 'class_weight': None, 'fit_intercept': False, 'tol': 2.7602270107354277e-05, 'max_iter': 1743, 'weight_class_0': 0.2985401092017817, 'weight_class_1': 1.6887401741381824, 'weight_class_2': 1.2700943152518458}. Best is trial 5 with value: 0.912938463873019.

Best trial: 5. Best value: 0.912938:  17%|███████████████████████                                                                                                                   | 5/30 [00:57<03:27,  8.28s/it]

[I 2026-07-05 15:51:42,949] Trial 10 finished with value: 0.8574203381159438 and parameters: {'l1_ratio': 0.6336904556255466, 'C': 0.018099027791339487, 'class_weight': None, 'fit_intercept': False, 'tol': 3.593345350765351e-05, 'max_iter': 2957, 'weight_class_0': 3.9358365060317677, 'weight_class_1': 0.7519815046573018, 'weight_class_2': 1.6516468076855002}. Best is trial 5 with value: 0.912938463873019.

Best trial: 5. Best value: 0.912938:  20%|███████████████████████████▌                                                                                                              | 6/30 [01:01<02:43,  6.81s/it]

[I 2026-07-05 15:51:46,899] Trial 14 pruned.

Best trial: 5. Best value: 0.912938:  23%|████████████████████████████████▏                                                                                                         | 7/30 [01:03<01:57,  5.11s/it]

[I 2026-07-05 15:51:48,477] Trial 3 pruned.

Best trial: 4. Best value: 0.940922:  27%|████████████████████████████████████▊                                                                                                     | 8/30 [01:10<02:08,  5.83s/it]

[I 2026-07-05 15:51:55,882] Trial 4 finished with value: 0.9409219385469904 and parameters: {'l1_ratio': 0.4710384455918346, 'C': 0.0007667611842077291, 'class_weight': None, 'fit_intercept': True, 'tol': 2.396874746170733e-06, 'max_iter': 1159, 'weight_class_0': 0.09436356825455673, 'weight_class_1': 7.756663592191695, 'weight_class_2': 2.553065151731302}. Best is trial 4 with value: 0.9409219385469904.

Best trial: 4. Best value: 0.940922:  30%|█████████████████████████████████████████▍                                                                                                | 9/30 [01:19<02:21,  6.72s/it]

[I 2026-07-05 15:52:04,566] Trial 12 pruned.

Best trial: 4. Best value: 0.940922:  33%|█████████████████████████████████████████████▋                                                                                           | 10/30 [01:23<01:56,  5.82s/it]

[I 2026-07-05 15:52:08,354] Trial 18 pruned.

Best trial: 4. Best value: 0.940922:  37%|██████████████████████████████████████████████████▏                                                                                      | 11/30 [01:32<02:09,  6.81s/it]

[I 2026-07-05 15:52:17,412] Trial 1 finished with value: 0.9269520821919393 and parameters: {'l1_ratio': 0.5748525527305194, 'C': 1.419898634878129, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0010009904376366578, 'max_iter': 1189, 'weight_class_0': 5.136156598188829, 'weight_class_1': 8.120953934731611, 'weight_class_2': 0.6880444980497409}. Best is trial 4 with value: 0.9409219385469904.

Best trial: 4. Best value: 0.940922:  40%|██████████████████████████████████████████████████████▊                                                                                  | 12/30 [01:34<01:36,  5.38s/it]

[I 2026-07-05 15:52:19,515] Trial 15 finished with value: 0.8997493343919688 and parameters: {'l1_ratio': 0.07379640991326253, 'C': 0.0011078561980656845, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0002284227424896894, 'max_iter': 4217, 'weight_class_0': 0.2709458521768243, 'weight_class_1': 2.3919030080625436, 'weight_class_2': 0.25742926492345375}. Best is trial 4 with value: 0.9409219385469904.

Best trial: 4. Best value: 0.940922:  43%|███████████████████████████████████████████████████████████▎                                                                             | 13/30 [01:47<02:13,  7.84s/it]

[I 2026-07-05 15:52:33,015] Trial 13 finished with value: 0.926805014834404 and parameters: {'l1_ratio': 0.3780827092442458, 'C': 1.7103912836176056, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.004687568396127344, 'max_iter': 3867, 'weight_class_0': 2.501398133056396, 'weight_class_1': 1.2233794999547807, 'weight_class_2': 0.543167168954624}. Best is trial 4 with value: 0.9409219385469904.

Best trial: 4. Best value: 0.940922:  47%|███████████████████████████████████████████████████████████████▉                                                                         | 14/30 [05:23<18:47, 70.45s/it]

[I 2026-07-05 15:56:08,160] Trial 9 pruned.

Best trial: 4. Best value: 0.940922:  50%|████████████████████████████████████████████████████████████████████▌                                                                    | 15/30 [06:29<17:18, 69.25s/it]

[I 2026-07-05 15:57:14,610] Trial 22 pruned.

/home/junior/Documentos/GitHub/kaggle-competition-predicting-student-health/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
Best trial: 4. Best value: 0.940922:  50%|████████████████████████████████████████████████████████████████████▌                                                                    | 15/30 [11:05<17:18, 69.25s/it]

[W 2026-07-05 16:01:51,066] Trial 4 failed with parameters: {'l1_ratio': 0.08080250773400499, 'C': 11.807907496404642, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 2.49019809811721e-06, 'max_iter': 3773} because of the following error: NameError("name 'pred' is not defined").
Traceback (most recent call last):
  File "/home/junior/Documentos/GitHub/kaggle-competition-predicting-student-health/.venv/lib/python3.13/site-packages/optuna/study/_optimize.py", line 206, in _run_trial
    value_or_values = func(trial)
  File "/tmp/ipykernel_81633/350936297.py", line 48, in <lambda>
    lambda trial: objective(trial, X_train, y_train.health_condition),
                  ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ipykernel_81633/350936297.py", line 31, in objective
    score = log_loss(y_valid_fold, pred)
                                   ^^^^
NameError: name 'pred' is not defined
[W 2026-07-05 16:01:51,073] Trial 4 failed with value None.

Best trial: 23. Best value: 0.942317:  53%|████████████████████████████████████████████████████████████████████████                                                               | 16/30 [11:34<32:42, 140.17s/it]

[I 2026-07-05 16:02:19,475] Trial 23 finished with value: 0.9423170317762566 and parameters: {'l1_ratio': 0.5553690006663523, 'C': 2.802165191305813, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 2.528569649012793e-06, 'max_iter': 1009, 'weight_class_0': 8.636094349122967, 'weight_class_1': 9.648346735539304, 'weight_class_2': 8.881410940043384}. Best is trial 23 with value: 0.9423170317762566.

/home/junior/Documentos/GitHub/kaggle-competition-predicting-student-health/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
Best trial: 23. Best value: 0.942317:  57%|████████████████████████████████████████████████████████████████████████████▌                                                          | 17/30 [12:42<25:40, 118.53s/it]

[I 2026-07-05 16:03:27,671] Trial 20 finished with value: 0.9188627680871294 and parameters: {'l1_ratio': 0.6153220664430329, 'C': 12.057013914550447, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.008734853727935976, 'max_iter': 4742, 'weight_class_0': 4.575941137803842, 'weight_class_1': 0.17805981938287996, 'weight_class_2': 5.0699507806402435}. Best is trial 23 with value: 0.9423170317762566.

/home/junior/Documentos/GitHub/kaggle-competition-predicting-student-health/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/junior/Documentos/GitHub/kaggle-competition-predicting-student-health/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/home/junior/Documentos/GitHub/kaggle-competition-predicting-student-health/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

In [28]:
lg_params = {k: v for k, v in study.best_params.items() if k not in ['weight_class_0', 'weight_class_1', 'weight_class_2']}

lg = LogisticRegression(
    solver="saga",
    random_state=42,
    **lg_params
).fit(X_train, y_train.class_encoded)

test_proba = lg.predict_proba(X_test)

weights = np.array([study.best_params['weight_class_0'], study.best_params['weight_class_1'], study.best_params['weight_class_2']])
weighted_probas = test_proba * weights

pred = np.argmax(weighted_probas, axis=1)

In [29]:
sub_labels = label_encoder.inverse_transform(pred)

# Submission

In [30]:
submission = pd.read_csv('../data/sample_submission.csv')
submission['class'] = sub_labels

submission.to_csv('../data/submission_stacking_lg.csv', index=False)

In [31]:
submission.head()

       id   class
0  577347  GALAXY
1  577348  GALAXY
2  577349  GALAXY
3  577350    STAR
4  577351  GALAXY

In [32]:
X_train.columns

Index(['lgbm_0', 'lgbm_1', 'lgbm_2', 'cat_0', 'cat_1', 'cat_2', 'xgb_0',
       'xgb_1', 'xgb_2', 'lg_0', 'lg_1', 'lg_2', 'sgd_0', 'sgd_1', 'sgd_2'],
      dtype='str')

In [33]:
len(study.trials)

200