# Imports

In [1]:
import pickle
import optuna

import numpy as np
import pandas as pd

from sklearn.metrics import balanced_accuracy_score, log_loss
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold, cross_val_predict

/home/junior/Documentos/GitHub/kaggle-competition-predicting-student-health/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Utils

In [2]:
def load_pickle(file_path):
    with open(file_path, 'rb') as file:
        return pickle.load(file)

# Loading Datasets

In [3]:
X_train = pd.read_parquet('../data/processed/X_train_stacking_layer_one_model_90_trials.parquet')
y_train = pd.read_parquet('../data/interim/y_train.parquet')

X_test = pd.read_parquet('../data/processed/X_test_stacking_layer_one_model_90_trials.parquet')

In [4]:
X_train.head()

,lgbm_0,lgbm_1,lgbm_2,xgb_0,xgb_1,xgb_2,cat_0,cat_1,cat_2
0,0.004927,0.001350,0.993723,0.003345,0.002030,0.994625,0.008438,1.091890e-03,0.990470
1,0.996682,0.000414,0.002905,0.996100,0.000521,0.003379,0.993015,2.545769e-04,0.006731
2,0.003205,0.000699,0.996095,0.002819,0.000623,0.996558,0.003345,8.700245e-04,0.995785
3,0.004065,0.003263,0.992672,0.003906,0.002117,0.993978,0.004627,1.166784e-03,0.994206
4,0.996028,0.000021,0.003951,0.995773,0.000024,0.004204,0.990619,7.828402e-07,0.009381

In [5]:
X_test.head()

,lgbm_0,lgbm_1,lgbm_2,xgb_0,xgb_1,xgb_2,cat_0,cat_1,cat_2
0,0.010078,0.003001,0.986921,0.009916,0.003474,0.986609,0.009972,0.003525,0.986503
1,0.457102,0.002879,0.540019,0.505986,0.002978,0.491037,0.516644,0.001511,0.481845
2,0.998144,0.001284,0.000572,0.996786,0.002227,0.000987,0.998283,0.001372,0.000345
3,0.988863,0.000017,0.011120,0.989342,0.000024,0.010634,0.991011,0.000050,0.008939
4,0.006397,0.002261,0.991343,0.006481,0.001816,0.991703,0.004760,0.001775,0.993465

# Machine Learning

In [6]:
label_encoder = load_pickle('../artifacts/label_encoder.pkl')

In [14]:
def objective(trial, X, y):
    
    C = trial.suggest_float("C", 1e-5, 100.0, log=True)
    class_weight = trial.suggest_categorical("class_weight", [None, "balanced"])
    fit_intercept = trial.suggest_categorical("fit_intercept", [True, False])
    tol = trial.suggest_float("tol", 1e-4, 1e-2, log=True)
    max_iter = trial.suggest_int("max_iter", 1000, 5000)

    w0 = trial.suggest_float('weight_class_0', 0.05, 10.0, log=True)
    w1 = trial.suggest_float('weight_class_1', 0.05, 10.0, log=True)
    w2 = trial.suggest_float('weight_class_2', 0.05, 10.0, log=True)
    weights = np.array([w0, w1, w2])

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    scores = []

    for fold, (train_idx, valid_idx) in enumerate(cv.split(X, y)):
        
        X_train_fold, X_valid_fold = X.iloc[train_idx, :], X.iloc[valid_idx, :]
        y_train_fold, y_valid_fold = y.iloc[train_idx], y.iloc[valid_idx]

        model = LogisticRegression(
            solver="lbfgs",
            l1_ratio=0.0,
            C=C,
            class_weight=class_weight,
            fit_intercept=fit_intercept,
            tol=tol,
            max_iter=max_iter,
            random_state=42,
        ).fit(X_train_fold, y_train_fold)

        proba = model.predict_proba(X_valid_fold)
        
        weighted_probas = proba * weights
        pred = np.argmax(weighted_probas, axis=1)
        
        score = balanced_accuracy_score(y_valid_fold, pred)
        scores.append(score)

        trial.report(np.mean(scores), step=fold)
        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()

    return np.mean(scores)


study = optuna.create_study(
    direction="maximize", 
    sampler=optuna.samplers.TPESampler(seed=42), 
    pruner=optuna.pruners.MedianPruner(n_warmup_steps=2)
)

study.optimize(
    lambda trial: objective(trial, X_train, y_train.health_condition), 
    n_trials=60, 
    n_jobs=-1, 
    show_progress_bar=True
)

print("\nBest trial score:")
print(study.best_trial.value)

print("\nBest params:")
print(study.best_trial.params)

[I 2026-07-08 16:41:12,511] A new study created in memory with name: no-name-e4442cd1-cb66-4694-8f96-b94d9a0ca176
Best trial: 5. Best value: 0.587084:   2%|██▎                                                                                                                                       | 1/60 [00:11<10:58, 11.16s/it]

[I 2026-07-08 16:41:23,649] Trial 5 finished with value: 0.5870837854071609 and parameters: {'C': 1.8799000875026933e-05, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0034687427676954835, 'max_iter': 3188, 'weight_class_0': 0.7920368357377003, 'weight_class_1': 0.8455808762707437, 'weight_class_2': 0.2419388857433938}. Best is trial 5 with value: 0.5870837854071609.

Best trial: 5. Best value: 0.587084:   3%|████▌                                                                                                                                     | 2/60 [00:12<05:26,  5.62s/it]

[I 2026-07-08 16:41:25,415] Trial 0 finished with value: 0.580607738450374 and parameters: {'C': 6.525088353636968e-05, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0026270826372161407, 'max_iter': 3421, 'weight_class_0': 7.804049660204241, 'weight_class_1': 0.3066338906504279, 'weight_class_2': 1.4796396787848003}. Best is trial 5 with value: 0.5870837854071609.

Best trial: 9. Best value: 0.601187:   5%|██████▉                                                                                                                                   | 3/60 [00:14<03:43,  3.91s/it]

[I 2026-07-08 16:41:27,288] Trial 9 finished with value: 0.6011871384972433 and parameters: {'C': 0.00011768578227799708, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0015468751370834293, 'max_iter': 2780, 'weight_class_0': 3.81649824068052, 'weight_class_1': 5.158312100999416, 'weight_class_2': 0.19127284113146029}. Best is trial 9 with value: 0.6011871384972433.

Best trial: 1. Best value: 0.899455:   8%|███████████▌                                                                                                                              | 5/60 [00:15<02:17,  2.49s/it]

[I 2026-07-08 16:41:27,541] Trial 3 finished with value: 0.8300258654999665 and parameters: {'C': 0.00044158452939449885, 'class_weight': None, 'fit_intercept': True, 'tol': 0.003945794901289753, 'max_iter': 4295, 'weight_class_0': 0.7068372159904658, 'weight_class_1': 0.08967283368045793, 'weight_class_2': 0.1955955919627971}. Best is trial 3 with value: 0.8300258654999665.
[I 2026-07-08 16:41:27,590] Trial 4 finished with value: 0.8853971742686138 and parameters: {'C': 0.0007613669135031097, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.008951927549067646, 'max_iter': 4933, 'weight_class_0': 0.5489897913268338, 'weight_class_1': 0.6620875046226474, 'weight_class_2': 6.677978461912238}. Best is trial 4 with value: 0.8853971742686138.
[I 2026-07-08 16:41:27,594] Trial 1 finished with value: 0.8994546181343249 and parameters: {'C': 5.492331595550336, 'class_weight': None, 'fit_intercept': True, 'tol': 0.004164981638702719, 'max_iter': 4963, 'weight_class_0': 0.050605222783586874, 'weight_class_1': 0.40332783733142247, 'weight_class_2': 0.07430708143129539}. Best is trial 1 with value: 0.8994546181343249.

Best trial: 11. Best value: 0.924002:  12%|███████████████▉                                                                                                                         | 7/60 [00:16<01:09,  1.31s/it]

[I 2026-07-08 16:41:29,332] Trial 11 finished with value: 0.9240015961307794 and parameters: {'C': 0.0035339671497281685, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.002048536527331038, 'max_iter': 3849, 'weight_class_0': 0.35599913859091864, 'weight_class_1': 0.6875820140412157, 'weight_class_2': 0.058359110500117266}. Best is trial 11 with value: 0.9240015961307794.

Best trial: 11. Best value: 0.924002:  15%|████████████████████▌                                                                                                                    | 9/60 [00:17<00:44,  1.15it/s]

[I 2026-07-08 16:41:29,886] Trial 7 pruned.
[I 2026-07-08 16:41:29,993] Trial 2 finished with value: 0.8500739622864147 and parameters: {'C': 0.00213413803680717, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0009465520137293026, 'max_iter': 3224, 'weight_class_0': 0.7161724411478463, 'weight_class_1': 0.053442312621883564, 'weight_class_2': 0.503582125552418}. Best is trial 11 with value: 0.9240015961307794.

Best trial: 11. Best value: 0.924002:  17%|██████████████████████▋                                                                                                                 | 10/60 [00:21<01:24,  1.68s/it]

[I 2026-07-08 16:41:33,941] Trial 8 finished with value: 0.9152521621317412 and parameters: {'C': 0.013800336524832667, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.001299300475323952, 'max_iter': 2386, 'weight_class_0': 2.7278562744331984, 'weight_class_1': 0.8271799272450949, 'weight_class_2': 0.30715882252742904}. Best is trial 11 with value: 0.9240015961307794.

Best trial: 6. Best value: 0.946709:  18%|█████████████████████████                                                                                                                | 11/60 [00:24<01:35,  1.94s/it]

[I 2026-07-08 16:41:36,642] Trial 6 finished with value: 0.9467092834904669 and parameters: {'C': 0.021500088417485595, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00025975492794354135, 'max_iter': 3553, 'weight_class_0': 0.15582534629775507, 'weight_class_1': 0.5494145770016595, 'weight_class_2': 1.9795626816885645}. Best is trial 6 with value: 0.9467092834904669.

Best trial: 6. Best value: 0.946709:  20%|███████████████████████████▍                                                                                                             | 12/60 [00:25<01:20,  1.67s/it]

[I 2026-07-08 16:41:37,545] Trial 10 pruned.

[I 2026-07-08 16:41:38,648] Trial 12 finished with value: 0.8887369713063051 and parameters: {'C': 0.36345297347737154, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0021575472585602146, 'max_iter': 1497, 'weight_class_0': 0.18516219774115525, 'weight_class_1': 0.08333171179256287, 'weight_class_2': 0.7139543856381745}. Best is trial 6 with value: 0.9467092834904669.
[I 2026-07-08 16:41:38,850] Trial 20 pruned.

Best trial: 6. Best value: 0.946709:  25%|██████████████████████████████████▎                                                                                                      | 15/60 [00:26<00:37,  1.20it/s]

[I 2026-07-08 16:41:38,892] Trial 19 pruned.

Best trial: 6. Best value: 0.946709:  27%|████████████████████████████████████▌                                                                                                    | 16/60 [00:29<00:59,  1.36s/it]

[I 2026-07-08 16:41:41,635] Trial 17 pruned.
[I 2026-07-08 16:41:41,737] Trial 15 pruned.

Best trial: 6. Best value: 0.946709:  30%|█████████████████████████████████████████                                                                                                | 18/60 [00:29<00:35,  1.18it/s]

[I 2026-07-08 16:41:42,255] Trial 16 finished with value: 0.9209994193999795 and parameters: {'C': 0.0018119024181234248, 'class_weight': None, 'fit_intercept': True, 'tol': 0.004779402430381996, 'max_iter': 2793, 'weight_class_0': 0.5740130119895989, 'weight_class_1': 4.815801565359303, 'weight_class_2': 3.3191806684671747}. Best is trial 6 with value: 0.9467092834904669.

Best trial: 6. Best value: 0.946709:  32%|███████████████████████████████████████████▍                                                                                             | 19/60 [00:30<00:31,  1.30it/s]

[I 2026-07-08 16:41:42,821] Trial 14 pruned.

Best trial: 6. Best value: 0.946709:  33%|█████████████████████████████████████████████▋                                                                                           | 20/60 [00:31<00:29,  1.36it/s]

[I 2026-07-08 16:41:43,395] Trial 18 pruned.

Best trial: 6. Best value: 0.946709:  35%|███████████████████████████████████████████████▉                                                                                         | 21/60 [00:34<00:55,  1.42s/it]

[I 2026-07-08 16:41:46,205] Trial 13 finished with value: 0.8945073295962187 and parameters: {'C': 10.437495434091142, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0016731507373753793, 'max_iter': 3349, 'weight_class_0': 4.06966784108189, 'weight_class_1': 0.3193475521841103, 'weight_class_2': 0.1711994784265425}. Best is trial 6 with value: 0.9467092834904669.

Best trial: 6. Best value: 0.946709:  37%|██████████████████████████████████████████████████▏                                                                                      | 22/60 [00:35<00:56,  1.48s/it]

[I 2026-07-08 16:41:48,163] Trial 21 pruned.

Best trial: 6. Best value: 0.946709:  38%|████████████████████████████████████████████████████▌                                                                                    | 23/60 [00:38<01:07,  1.81s/it]

[I 2026-07-08 16:41:50,635] Trial 22 pruned.

Best trial: 6. Best value: 0.946709:  40%|██████████████████████████████████████████████████████▊                                                                                  | 24/60 [00:39<00:54,  1.50s/it]

[I 2026-07-08 16:41:51,406] Trial 24 pruned.
[I 2026-07-08 16:41:51,566] Trial 26 pruned.

Best trial: 6. Best value: 0.946709:  43%|███████████████████████████████████████████████████████████▎                                                                             | 26/60 [00:45<01:21,  2.40s/it]

[I 2026-07-08 16:41:58,393] Trial 23 finished with value: 0.9254321751170105 and parameters: {'C': 0.10578897133158272, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0003774410469179998, 'max_iter': 4000, 'weight_class_0': 0.1796233975708165, 'weight_class_1': 0.16482845350656686, 'weight_class_2': 3.3434894978437257}. Best is trial 6 with value: 0.9467092834904669.

Best trial: 6. Best value: 0.946709:  45%|█████████████████████████████████████████████████████████████▋                                                                           | 27/60 [00:48<01:17,  2.33s/it]

[I 2026-07-08 16:42:00,480] Trial 25 finished with value: 0.9461227763437272 and parameters: {'C': 0.0603935946009874, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0003841847009552646, 'max_iter': 3908, 'weight_class_0': 0.20903614667838588, 'weight_class_1': 2.1613355798111122, 'weight_class_2': 3.6367245708328513}. Best is trial 6 with value: 0.9467092834904669.

Best trial: 28. Best value: 0.948408:  47%|███████████████████████████████████████████████████████████████▍                                                                        | 28/60 [00:58<02:20,  4.39s/it]

[I 2026-07-08 16:42:10,496] Trial 28 finished with value: 0.9484078566314981 and parameters: {'C': 0.016699740227808214, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00014739017267065567, 'max_iter': 3532, 'weight_class_0': 0.21947355522581277, 'weight_class_1': 1.9697834771938725, 'weight_class_2': 2.898617072130844}. Best is trial 28 with value: 0.9484078566314981.

Best trial: 30. Best value: 0.949246:  48%|█████████████████████████████████████████████████████████████████▋                                                                      | 29/60 [00:59<01:46,  3.43s/it]

[I 2026-07-08 16:42:11,574] Trial 30 finished with value: 0.9492455490153432 and parameters: {'C': 0.02142821160947103, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00013696788193514944, 'max_iter': 3647, 'weight_class_0': 0.31100401165240815, 'weight_class_1': 1.6508997508613723, 'weight_class_2': 2.8207492872868656}. Best is trial 30 with value: 0.9492455490153432.

Best trial: 30. Best value: 0.949246:  50%|████████████████████████████████████████████████████████████████████                                                                    | 30/60 [01:00<01:21,  2.73s/it]

[I 2026-07-08 16:42:12,547] Trial 36 pruned.

Best trial: 33. Best value: 0.949513:  52%|██████████████████████████████████████████████████████████████████████▎                                                                 | 31/60 [01:01<01:06,  2.29s/it]

[I 2026-07-08 16:42:13,608] Trial 33 finished with value: 0.949512609276549 and parameters: {'C': 0.009388286323891267, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0006645768330429948, 'max_iter': 3771, 'weight_class_0': 0.36256687457667425, 'weight_class_1': 2.222384662719122, 'weight_class_2': 3.054397486583219}. Best is trial 33 with value: 0.949512609276549.

Best trial: 34. Best value: 0.949607:  53%|████████████████████████████████████████████████████████████████████████▌                                                               | 32/60 [01:02<00:58,  2.08s/it]

[I 2026-07-08 16:42:15,294] Trial 29 finished with value: 0.9479868635930675 and parameters: {'C': 0.017406455168673503, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00011277183431434535, 'max_iter': 3749, 'weight_class_0': 0.18800552789467673, 'weight_class_1': 2.544522654321287, 'weight_class_2': 2.023576784029294}. Best is trial 33 with value: 0.949512609276549.
[I 2026-07-08 16:42:15,324] Trial 34 finished with value: 0.9496066040882603 and parameters: {'C': 0.017118025661080442, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0006376448281857147, 'max_iter': 3653, 'weight_class_0': 0.3775785180286646, 'weight_class_1': 3.9126673894461947, 'weight_class_2': 2.788644688568666}. Best is trial 34 with value: 0.9496066040882603.

Best trial: 34. Best value: 0.949607:  57%|█████████████████████████████████████████████████████████████████████████████                                                           | 34/60 [01:04<00:37,  1.46s/it]

[I 2026-07-08 16:42:16,564] Trial 27 finished with value: 0.9486350871088387 and parameters: {'C': 0.01686287763440259, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00010616108279081132, 'max_iter': 3754, 'weight_class_0': 0.22881384743508207, 'weight_class_1': 2.0586066756551915, 'weight_class_2': 2.878299061840485}. Best is trial 34 with value: 0.9496066040882603.

Best trial: 34. Best value: 0.949607:  58%|███████████████████████████████████████████████████████████████████████████████▎                                                        | 35/60 [01:06<00:39,  1.57s/it]

[I 2026-07-08 16:42:18,538] Trial 35 finished with value: 0.9492237877716004 and parameters: {'C': 0.004250780143167305, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0007037355290537165, 'max_iter': 3649, 'weight_class_0': 0.34368908944221127, 'weight_class_1': 3.8722713839263756, 'weight_class_2': 2.744278496222732}. Best is trial 34 with value: 0.9496066040882603.

Best trial: 31. Best value: 0.949713:  60%|█████████████████████████████████████████████████████████████████████████████████▌                                                      | 36/60 [01:07<00:38,  1.59s/it]

[I 2026-07-08 16:42:20,283] Trial 31 finished with value: 0.9497128324966972 and parameters: {'C': 0.01798806694620488, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00010184796505166689, 'max_iter': 3649, 'weight_class_0': 0.29255523927819943, 'weight_class_1': 1.8148882329644411, 'weight_class_2': 2.119330647860387}. Best is trial 31 with value: 0.9497128324966972.

Best trial: 31. Best value: 0.949713:  62%|███████████████████████████████████████████████████████████████████████████████████▊                                                    | 37/60 [01:13<01:05,  2.84s/it]

[I 2026-07-08 16:42:26,473] Trial 32 finished with value: 0.9490258974466943 and parameters: {'C': 0.04871027448793649, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00012136037781329495, 'max_iter': 3690, 'weight_class_0': 0.29994439397173245, 'weight_class_1': 1.8806586486461108, 'weight_class_2': 3.224642739840749}. Best is trial 31 with value: 0.9497128324966972.

Best trial: 31. Best value: 0.949713:  63%|██████████████████████████████████████████████████████████████████████████████████████▏                                                 | 38/60 [01:17<01:03,  2.90s/it]

[I 2026-07-08 16:42:29,564] Trial 37 finished with value: 0.9464962449283773 and parameters: {'C': 0.0061931976157385046, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00012784277080031214, 'max_iter': 3622, 'weight_class_0': 0.32066286644625197, 'weight_class_1': 0.4681641271687529, 'weight_class_2': 2.333243126102887}. Best is trial 31 with value: 0.9497128324966972.

Best trial: 31. Best value: 0.949713:  65%|████████████████████████████████████████████████████████████████████████████████████████▍                                               | 39/60 [01:18<00:50,  2.41s/it]

[I 2026-07-08 16:42:30,507] Trial 38 pruned.

Best trial: 31. Best value: 0.949713:  67%|██████████████████████████████████████████████████████████████████████████████████████████▋                                             | 40/60 [01:26<01:24,  4.21s/it]

[I 2026-07-08 16:42:39,347] Trial 43 finished with value: 0.9487547957818606 and parameters: {'C': 0.006931482841478864, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0007496549589423675, 'max_iter': 4251, 'weight_class_0': 0.40304843113678523, 'weight_class_1': 1.3027806460827307, 'weight_class_2': 1.6736641352932338}. Best is trial 31 with value: 0.9497128324966972.

Best trial: 31. Best value: 0.949713:  68%|████████████████████████████████████████████████████████████████████████████████████████████▉                                           | 41/60 [01:27<00:59,  3.11s/it]

[I 2026-07-08 16:42:39,619] Trial 45 finished with value: 0.9486688772478704 and parameters: {'C': 0.005893094712941863, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0007725622082342516, 'max_iter': 4293, 'weight_class_0': 0.39222174949725913, 'weight_class_1': 1.3726896731490414, 'weight_class_2': 1.332586658640646}. Best is trial 31 with value: 0.9497128324966972.
[I 2026-07-08 16:42:39,806] Trial 44 finished with value: 0.9486145660962734 and parameters: {'C': 0.0059070450669170245, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0007524000382440919, 'max_iter': 4492, 'weight_class_0': 0.4038450249600987, 'weight_class_1': 1.2726449216061175, 'weight_class_2': 1.6361751989359896}. Best is trial 31 with value: 0.9497128324966972.

Best trial: 31. Best value: 0.949713:  72%|█████████████████████████████████████████████████████████████████████████████████████████████████▍                                      | 43/60 [01:27<00:30,  1.80s/it]

[I 2026-07-08 16:42:40,142] Trial 41 pruned.
[I 2026-07-08 16:42:40,143] Trial 42 pruned.

Best trial: 31. Best value: 0.949713:  75%|██████████████████████████████████████████████████████████████████████████████████████████████████████                                  | 45/60 [01:28<00:18,  1.24s/it]

[I 2026-07-08 16:42:41,045] Trial 46 finished with value: 0.9486275843326407 and parameters: {'C': 0.005556685826962227, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0007158899699333249, 'max_iter': 4410, 'weight_class_0': 0.3908737063316553, 'weight_class_1': 1.2602818502111532, 'weight_class_2': 1.4655817274756697}. Best is trial 31 with value: 0.9497128324966972.

Best trial: 31. Best value: 0.949713:  77%|████████████████████████████████████████████████████████████████████████████████████████████████████████▎                               | 46/60 [01:29<00:15,  1.11s/it]

[I 2026-07-08 16:42:41,648] Trial 50 pruned.

Best trial: 31. Best value: 0.949713:  78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▌                             | 47/60 [01:30<00:14,  1.14s/it]

[I 2026-07-08 16:42:42,920] Trial 47 finished with value: 0.9482967229846837 and parameters: {'C': 0.007067038114005299, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0007093145423827619, 'max_iter': 4355, 'weight_class_0': 0.42306546068573364, 'weight_class_1': 1.15449077356515, 'weight_class_2': 1.4930935842703168}. Best is trial 31 with value: 0.9497128324966972.

Best trial: 31. Best value: 0.949713:  80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                           | 48/60 [01:31<00:13,  1.14s/it]

[I 2026-07-08 16:42:44,106] Trial 40 pruned.

Best trial: 31. Best value: 0.949713:  82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████                         | 49/60 [01:32<00:11,  1.07s/it]

[I 2026-07-08 16:42:44,857] Trial 48 finished with value: 0.946634151975065 and parameters: {'C': 0.000525626783605854, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0006974244738426048, 'max_iter': 4513, 'weight_class_0': 0.484072133235336, 'weight_class_1': 1.3332678665945588, 'weight_class_2': 1.3083887042778632}. Best is trial 31 with value: 0.9497128324966972.

Best trial: 31. Best value: 0.949713:  83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                      | 50/60 [01:32<00:08,  1.17it/s]

[I 2026-07-08 16:42:45,158] Trial 49 finished with value: 0.9458577632713954 and parameters: {'C': 0.00032807417066256137, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0007582690640500576, 'max_iter': 4459, 'weight_class_0': 0.5059578636498387, 'weight_class_1': 1.2705712032913674, 'weight_class_2': 1.44838693939894}. Best is trial 31 with value: 0.9497128324966972.
[I 2026-07-08 16:42:45,236] Trial 39 pruned.

Best trial: 31. Best value: 0.949713:  87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                  | 52/60 [01:37<00:12,  1.53s/it]

[I 2026-07-08 16:42:49,975] Trial 56 pruned.
[I 2026-07-08 16:42:50,006] Trial 54 pruned.

Best trial: 31. Best value: 0.949713:  92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋           | 55/60 [01:41<00:08,  1.65s/it]

[I 2026-07-08 16:42:53,685] Trial 52 finished with value: 0.9493817401402772 and parameters: {'C': 0.00044764731782204, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0005879018453498046, 'max_iter': 3167, 'weight_class_0': 0.5756172154932527, 'weight_class_1': 3.602688354312446, 'weight_class_2': 4.439201472463529}. Best is trial 31 with value: 0.9497128324966972.
[I 2026-07-08 16:42:53,686] Trial 53 finished with value: 0.949119418102447 and parameters: {'C': 0.0005251186176306112, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0005914161728021718, 'max_iter': 3155, 'weight_class_0': 0.5209005746364117, 'weight_class_1': 3.483190154362102, 'weight_class_2': 4.541348608082075}. Best is trial 31 with value: 0.9497128324966972.
[I 2026-07-08 16:42:53,726] Trial 51 finished with value: 0.9477450379773552 and parameters: {'C': 0.0009137997932610713, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0006545100170819292, 'max_iter': 4502, 'weight_class_0': 0.5353838650421634, 'weight_class_1': 3.280224171306581, 'weight_class_2': 1.2654727842714464}. Best is trial 31 with value: 0.9497128324966972.

Best trial: 31. Best value: 0.949713:  95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏      | 57/60 [01:41<00:02,  1.02it/s]

[I 2026-07-08 16:42:54,217] Trial 55 finished with value: 0.9495858531876816 and parameters: {'C': 0.000610968553063849, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.000563711721965139, 'max_iter': 3135, 'weight_class_0': 0.6077065303206446, 'weight_class_1': 3.4801829635159844, 'weight_class_2': 4.238743777132113}. Best is trial 31 with value: 0.9497128324966972.

Best trial: 31. Best value: 0.949713:  97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍    | 58/60 [01:42<00:02,  1.02s/it]

[I 2026-07-08 16:42:55,416] Trial 59 finished with value: 0.9485251581227863 and parameters: {'C': 0.002137650570521202, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0005384889473122052, 'max_iter': 3253, 'weight_class_0': 1.0393965014516309, 'weight_class_1': 3.2971362724093587, 'weight_class_2': 4.40528821415475}. Best is trial 31 with value: 0.9497128324966972.

Best trial: 31. Best value: 0.949713:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋  | 59/60 [01:43<00:00,  1.15it/s]

[I 2026-07-08 16:42:55,702] Trial 57 finished with value: 0.9486380996700869 and parameters: {'C': 0.001958063839373326, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0002556299431989669, 'max_iter': 3159, 'weight_class_0': 1.0295950551508368, 'weight_class_1': 3.3827403652227197, 'weight_class_2': 4.57378436184786}. Best is trial 31 with value: 0.9497128324966972.

Best trial: 31. Best value: 0.949713: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 60/60 [01:43<00:00,  1.72s/it]

[I 2026-07-08 16:42:56,004] Trial 58 finished with value: 0.9496377640824301 and parameters: {'C': 0.0024640642231709823, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00024811751530652104, 'max_iter': 3205, 'weight_class_0': 0.6116402827401176, 'weight_class_1': 3.410585055192493, 'weight_class_2': 4.332224849661684}. Best is trial 31 with value: 0.9497128324966972.

Best trial score:
0.9497128324966972

Best params:
{'C': 0.01798806694620488, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00010184796505166689, 'max_iter': 3649, 'weight_class_0': 0.29255523927819943, 'weight_class_1': 1.8148882329644411, 'weight_class_2': 2.119330647860387}

In [15]:
lg_params = {k: v for k, v in study.best_params.items() if k not in ['weight_class_0', 'weight_class_1', 'weight_class_2']}

lg = LogisticRegression(
    solver="lbfgs",
    l1_ratio=0.0,
    random_state=42,
    **lg_params
).fit(X_train, y_train.health_condition)

test_proba = lg.predict_proba(X_test)

weights = np.array([study.best_params['weight_class_0'], study.best_params['weight_class_1'], study.best_params['weight_class_2']])
weighted_probas = test_proba * weights

pred = np.argmax(weighted_probas, axis=1)

In [16]:
sub_labels = label_encoder.inverse_transform(pred)

# Submission

In [17]:
submission = pd.read_csv('../data/submission/sample_submission.csv')
submission['health_condition'] = sub_labels

submission.to_csv('../data/submission/submission_from_5.4.2_xgboost_lightgbm_catboost_stacking_submission.csv', index=False)

In [18]:
submission.head()

       id health_condition
0  690088        unhealthy
1  690089        unhealthy
2  690090          at-risk
3  690091          at-risk
4  690092        unhealthy

In [19]:
X_train.columns

Index(['lgbm_0', 'lgbm_1', 'lgbm_2', 'xgb_0', 'xgb_1', 'xgb_2', 'cat_0',
       'cat_1', 'cat_2'],
      dtype='str')

In [20]:
len(study.trials)

60