# Imports

In [1]:
import optuna
import pickle

import numpy as np
import pandas as pd

from tqdm import tqdm

from sklearn.metrics import balanced_accuracy_score
from sklearn.model_selection import StratifiedKFold, cross_val_predict

/home/junior/Documentos/GitHub/kaggle-competition-predicting-student-health/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Utils

In [2]:
def load_pickle(file_path):
    with open(file_path, 'rb') as file:
        return pickle.load(file)

# Loading Datasets

In [3]:
X_train = pd.read_parquet('../data/processed/X_train_stacking_fe_layer_one_model_30_trials.parquet')
y_train = pd.read_parquet('../data/interim/y_train.parquet')

X_test = pd.read_parquet('../data/processed/X_test_stacking_fe_layer_one_model_30_trials.parquet')

In [4]:
X_train.head()

,lgbm_0,lgbm_1,lgbm_2,xgb_0,xgb_1,xgb_2,cat_0,cat_1,cat_2
0,0.005332,0.000921,0.993747,0.001583,0.000348,0.998069,0.007467,0.000788,0.991745
1,0.995298,0.000565,0.004136,0.996461,0.000307,0.003233,0.992663,0.000880,0.006457
2,0.003239,0.001006,0.995755,0.004254,0.000524,0.995222,0.004121,0.001199,0.994680
3,0.004635,0.001771,0.993594,0.003324,0.001662,0.995014,0.007385,0.002109,0.990506
4,0.994943,0.000108,0.004949,0.992094,0.000021,0.007886,0.994977,0.000148,0.004875

In [5]:
X_test.head()

,lgbm_0,lgbm_1,lgbm_2,xgb_0,xgb_1,xgb_2,cat_0,cat_1,cat_2
0,0.009638,0.004344,0.986018,0.010005,0.004287,0.985708,0.007769,0.003721,0.988511
1,0.522299,0.003439,0.474262,0.480004,0.003110,0.516887,0.509202,0.001904,0.488894
2,0.997536,0.001794,0.000670,0.999363,0.000490,0.000148,0.994896,0.004031,0.001073
3,0.989331,0.000063,0.010606,0.987457,0.000013,0.012530,0.994476,0.000479,0.005046
4,0.008243,0.002363,0.989394,0.011684,0.003013,0.985303,0.007928,0.002671,0.989401

# Machine Learning

In [6]:
label_encoder = load_pickle('../artifacts/label_encoder.pkl')

In [7]:
cols_use = ['lgbm_0', 'lgbm_1', 'lgbm_2']

In [8]:
def objective(trial, X, y):

    w0 = trial.suggest_float('weight_class_0', 0.0, 10.0, log=False)
    w1 = trial.suggest_float('weight_class_1', 0.0, 10.0, log=False)
    w2 = trial.suggest_float('weight_class_2', 0.0, 10.0, log=False)
    weights = np.array([w0, w1, w2])

    proba = X.loc[:, cols_use].to_numpy()
    
    weighted_probas = proba * weights
    pred = np.argmax(weighted_probas, axis=1)
    
    score = balanced_accuracy_score(y, pred)

    return score


study = optuna.create_study(
    direction="maximize", 
    sampler=optuna.samplers.TPESampler(seed=42), 
    pruner=optuna.pruners.MedianPruner(n_warmup_steps=2)
)

study.optimize(
    lambda trial: objective(trial, X_train, y_train.health_condition), 
    n_trials=3000, 
    n_jobs=-1, 
    show_progress_bar=True
)

print("\nBest trial score:")
print(study.best_trial.value)

print("\nBest params:")
print(study.best_trial.params)

[I 2026-07-10 16:12:06,763] A new study created in memory with name: no-name-b0cf5a24-946d-4aee-947f-82037a085b5e

[I 2026-07-10 16:12:06,933] Trial 5 finished with value: 0.8687846647110424 and parameters: {'weight_class_0': 2.2605978459710165, 'weight_class_1': 0.20858621258991628, 'weight_class_2': 5.788328507412893}. Best is trial 5 with value: 0.8687846647110424.
[I 2026-07-10 16:12:06,940] Trial 3 finished with value: 0.9084220434519971 and parameters: {'weight_class_0': 3.5741421468466816, 'weight_class_1': 7.8698227110758046, 'weight_class_2': 4.551571179132798}. Best is trial 3 with value: 0.9084220434519971.
[I 2026-07-10 16:12:06,947] Trial 0 finished with value: 0.8265867697917612 and parameters: {'weight_class_0': 8.37742777532354, 'weight_class_1': 0.6455653071284184, 'weight_class_2': 5.499711537559147}. Best is trial 3 with value: 0.9084220434519971.
[I 2026-07-10 16:12:06,948] Trial 10 finished with value: 0.8469858221956109 and parameters: {'weight_class_0': 6.626153401003126, 'weight_class_1': 2.730356241245999, 'weight_class_2': 3.8468499962747282}. Best is trial 3 with value: 0.9084220434519971.
[I 2026-07-10 16:12:06,950] Trial 9 finished with value: 0.8584317725695382 and parameters: {'weight_class_0': 9.056617466917107, 'weight_class_1': 6.610197870071023, 'weight_class_2': 5.434440166387522}. Best is trial 3 with value: 0.9084220434519971.
[I 2026-07-10 16:12:06,956] Trial 4 finished with value: 0.9454835183787136 and parameters: {'weight_class_0': 1.5963390199710437, 'weight_class_1': 7.660127740929477, 'weight_class_2': 7.285277325830789}. Best is trial 4 with value: 0.9454835183787136.
[I 2026-07-10 16:12:06,958] Trial 7 finished with value: 0.9483947788068958 and parameters: {'weight_class_0': 0.26264437825056275, 'weight_class_1': 7.95683737187699, 'weight_class_2': 6.643724000985353}. Best is trial 7 with value: 0.9483947788068958.
[I 2026-07-10 16:12:06,968] Trial 6 finished with value: 0.8641201506178428 and parameters: {'weight_class_0': 7.176788577468278, 'weight_class_1': 7.24215157200385, 'weight_class_2': 3.423685969200989}. Best is trial 7 with value: 0.9483947788068958.
[I 2026-07-10 16:12:06,970] Trial 2 finished with value: 0.8585618379330161 and parameters: {'weight_class_0': 2.2313479806684056, 'weight_class_1': 1.9967268194266363, 'weight_class_2': 0.6922954829094585}. Best is trial 7 with value: 0.9483947788068958.
[I 2026-07-10 16:12:06,975] Trial 1 finished with value: 0.8661413218575525 and parameters: {'weight_class_0': 8.438573854589631, 'weight_class_1': 9.397101661420725, 'weight_class_2': 3.581837434980646}. Best is trial 7 with value: 0.9483947788068958.
[I 2026-07-10 16:12:06,985] Trial 11 finished with value: 0.8652196764488588 and parameters: {'weight_class_0': 7.269036703407213, 'weight_class_1': 8.550848825505403, 'weight_class_2': 1.832164569095237}. Best is trial 7 with value: 0.9483947788068958.
[I 2026-07-10 16:12:06,991] Trial 8 finished with value: 0.8541935390638753 and parameters: {'weight_class_0': 4.590778235054627, 'weight_class_1': 5.11581967992586, 'weight_class_2': 0.1945819683074279}. Best is trial 7 with value: 0.9483947788068958.
[I 2026-07-10 16:12:07,083] Trial 12 finished with value: 0.7379274238276124 and parameters: {'weight_class_0': 9.976579480061435, 'weight_class_1': 0.11109832805517694, 'weight_class_2': 2.0236351795727314}. Best is trial 7 with value: 0.9483947788068958.

[I 2026-07-10 16:12:07,083] Trial 13 finished with value: 0.9161250322862021 and parameters: {'weight_class_0': 3.6340560672697517, 'weight_class_1': 6.514001713560442, 'weight_class_2': 6.627998551828179}. Best is trial 7 with value: 0.9483947788068958.
[I 2026-07-10 16:12:07,103] Trial 14 finished with value: 0.9293253549481371 and parameters: {'weight_class_0': 0.0634752805038643, 'weight_class_1': 4.761119355278575, 'weight_class_2': 9.45941446037954}. Best is trial 7 with value: 0.9483947788068958.
[I 2026-07-10 16:12:07,142] Trial 16 finished with value: 0.9486569845543666 and parameters: {'weight_class_0': 0.3858344094271557, 'weight_class_1': 5.493736673484943, 'weight_class_2': 8.462015703635382}. Best is trial 16 with value: 0.9486569845543666.
[I 2026-07-10 16:12:07,157] Trial 15 finished with value: 0.9022691068563607 and parameters: {'weight_class_0': 0.04368780665012406, 'weight_class_1': 5.462076053625172, 'weight_class_2': 8.532665274886348}. Best is trial 16 with value: 0.9486569845543666.
[I 2026-07-10 16:12:07,173] Trial 17 finished with value: 0.9459078889646428 and parameters: {'weight_class_0': 0.13922021580566124, 'weight_class_1': 5.128699332389116, 'weight_class_2': 8.73628328446315}. Best is trial 16 with value: 0.9486569845543666.
[I 2026-07-10 16:12:07,186] Trial 18 finished with value: 0.9261306544730381 and parameters: {'weight_class_0': 0.060108317831881586, 'weight_class_1': 5.852050528520854, 'weight_class_2': 8.639359683622416}. Best is trial 16 with value: 0.9486569845543666.
[I 2026-07-10 16:12:07,191] Trial 20 finished with value: 0.9448770812481749 and parameters: {'weight_class_0': 0.12016817344516184, 'weight_class_1': 5.4521112678903325, 'weight_class_2': 8.709140477642308}. Best is trial 16 with value: 0.9486569845543666.
[I 2026-07-10 16:12:07,201] Trial 19 finished with value: 0.9484570126666984 and parameters: {'weight_class_0': 0.3269085574729089, 'weight_class_1': 5.642512605489335, 'weight_class_2': 8.612829575334858}. Best is trial 16 with value: 0.9486569845543666.
[I 2026-07-10 16:12:07,229] Trial 21 finished with value: 0.9467329425779729 and parameters: {'weight_class_0': 0.1602413603153554, 'weight_class_1': 5.141462811938433, 'weight_class_2': 8.542836320577091}. Best is trial 16 with value: 0.9486569845543666.
[I 2026-07-10 16:12:07,251] Trial 22 finished with value: 0.944976696763853 and parameters: {'weight_class_0': 0.1247409540567943, 'weight_class_1': 5.164926462486807, 'weight_class_2': 9.162548682890552}. Best is trial 16 with value: 0.9486569845543666.
[I 2026-07-10 16:12:07,259] Trial 23 finished with value: 0.6987551304541354 and parameters: {'weight_class_0': 0.017249872750048356, 'weight_class_1': 9.914895484251714, 'weight_class_2': 8.232074388436374}. Best is trial 16 with value: 0.9486569845543666.

Best trial: 25. Best value: 0.948812:   1%|█▌                                                                                                                                    | 36/3000 [00:00<00:56, 52.65it/s]

[I 2026-07-10 16:12:07,272] Trial 24 finished with value: 0.9452222496532752 and parameters: {'weight_class_0': 0.17383542029910348, 'weight_class_1': 9.853384384423055, 'weight_class_2': 8.221301861613984}. Best is trial 16 with value: 0.9486569845543666.
[I 2026-07-10 16:12:07,296] Trial 25 finished with value: 0.9488119903437447 and parameters: {'weight_class_0': 1.1271046771091644, 'weight_class_1': 9.75591048739037, 'weight_class_2': 8.039971225180476}. Best is trial 25 with value: 0.9488119903437447.
[I 2026-07-10 16:12:07,327] Trial 26 finished with value: 0.9360593128904883 and parameters: {'weight_class_0': 1.7478283841818345, 'weight_class_1': 3.8786327228960378, 'weight_class_2': 7.20217112400275}. Best is trial 25 with value: 0.9488119903437447.
[I 2026-07-10 16:12:07,347] Trial 27 finished with value: 0.9412275305426294 and parameters: {'weight_class_0': 1.3439973192421268, 'weight_class_1': 3.738975489489343, 'weight_class_2': 7.4463919890373536}. Best is trial 25 with value: 0.9488119903437447.
[I 2026-07-10 16:12:07,352] Trial 28 finished with value: 0.9413873179775853 and parameters: {'weight_class_0': 1.3224792775235812, 'weight_class_1': 3.7511818658311284, 'weight_class_2': 7.138222386435716}. Best is trial 25 with value: 0.9488119903437447.
[I 2026-07-10 16:12:07,370] Trial 29 finished with value: 0.9403597409388104 and parameters: {'weight_class_0': 1.4370439931249395, 'weight_class_1': 3.91141601287264, 'weight_class_2': 7.112031217497255}. Best is trial 25 with value: 0.9488119903437447.
[I 2026-07-10 16:12:07,390] Trial 30 finished with value: 0.9400998151112825 and parameters: {'weight_class_0': 1.4401269262369116, 'weight_class_1': 3.7952765205337196, 'weight_class_2': 7.43705906956354}. Best is trial 25 with value: 0.9488119903437447.
[I 2026-07-10 16:12:07,423] Trial 31 finished with value: 0.9440978570210236 and parameters: {'weight_class_0': 1.1414746262464741, 'weight_class_1': 3.723772099656303, 'weight_class_2': 9.885937900159568}. Best is trial 25 with value: 0.9488119903437447.
[I 2026-07-10 16:12:07,440] Trial 32 finished with value: 0.9413030069472326 and parameters: {'weight_class_0': 1.3257201976982178, 'weight_class_1': 3.7319257905682583, 'weight_class_2': 7.2257831551844065}. Best is trial 25 with value: 0.9488119903437447.
[I 2026-07-10 16:12:07,444] Trial 33 finished with value: 0.9393716910848452 and parameters: {'weight_class_0': 1.3472081561415645, 'weight_class_1': 3.1907859912193834, 'weight_class_2': 9.813728980177677}. Best is trial 25 with value: 0.9488119903437447.
[I 2026-07-10 16:12:07,460] Trial 34 finished with value: 0.9442315524869477 and parameters: {'weight_class_0': 1.047104065794077, 'weight_class_1': 3.5490552573279053, 'weight_class_2': 7.560989611843762}. Best is trial 25 with value: 0.9488119903437447.
[I 2026-07-10 16:12:07,490] Trial 35 finished with value: 0.8861807506907602 and parameters: {'weight_class_0': 3.1784860007043245, 'weight_class_1': 1.7232026929083624, 'weight_class_2': 5.950843663684045}. Best is trial 25 with value: 0.9488119903437447.
[I 2026-07-10 16:12:07,494] Trial 36 finished with value: 0.9375547767222551 and parameters: {'weight_class_0': 3.062938342307051, 'weight_class_1': 8.729772072319514, 'weight_class_2': 9.801450849595067}. Best is trial 25 with value: 0.9488119903437447.

Best trial: 39. Best value: 0.949571:   2%|██▏                                                                                                                                   | 48/3000 [00:01<00:54, 54.41it/s]

[I 2026-07-10 16:12:07,529] Trial 37 finished with value: 0.8979530615857877 and parameters: {'weight_class_0': 3.2331311950793937, 'weight_class_1': 1.8451016413923762, 'weight_class_2': 9.776296954791363}. Best is trial 25 with value: 0.9488119903437447.
[I 2026-07-10 16:12:07,547] Trial 38 finished with value: 0.9486039004332883 and parameters: {'weight_class_0': 0.9862311585653558, 'weight_class_1': 8.779185989001608, 'weight_class_2': 6.31662731965007}. Best is trial 25 with value: 0.9488119903437447.
[I 2026-07-10 16:12:07,560] Trial 39 finished with value: 0.9495709219330517 and parameters: {'weight_class_0': 0.8666923281818497, 'weight_class_1': 8.885718225773603, 'weight_class_2': 9.695613336313297}. Best is trial 39 with value: 0.9495709219330517.
[I 2026-07-10 16:12:07,576] Trial 40 finished with value: 0.9366393961611813 and parameters: {'weight_class_0': 2.4490361038198496, 'weight_class_1': 8.94205621861801, 'weight_class_2': 6.248791131954766}. Best is trial 39 with value: 0.9495709219330517.
[I 2026-07-10 16:12:07,589] Trial 41 finished with value: 0.9338568802104205 and parameters: {'weight_class_0': 2.6440766778119924, 'weight_class_1': 8.716042341260627, 'weight_class_2': 6.204106686575763}. Best is trial 39 with value: 0.9495709219330517.
[I 2026-07-10 16:12:07,617] Trial 42 finished with value: 0.9333208668402492 and parameters: {'weight_class_0': 2.768629576509733, 'weight_class_1': 8.507895777429392, 'weight_class_2': 6.582680622037175}. Best is trial 39 with value: 0.9495709219330517.
[I 2026-07-10 16:12:07,626] Trial 43 finished with value: 0.9344537967009487 and parameters: {'weight_class_0': 2.571117979087158, 'weight_class_1': 9.03823399187603, 'weight_class_2': 6.0110793473207575}. Best is trial 39 with value: 0.9495709219330517.
[I 2026-07-10 16:12:07,656] Trial 45 finished with value: 0.9389748400502892 and parameters: {'weight_class_0': 2.253464973941857, 'weight_class_1': 8.535198012212355, 'weight_class_2': 6.393732629678029}. Best is trial 39 with value: 0.9495709219330517.
[I 2026-07-10 16:12:07,664] Trial 44 finished with value: 0.9375506601755368 and parameters: {'weight_class_0': 2.3855920338492904, 'weight_class_1': 8.764628120712857, 'weight_class_2': 6.375248544203181}. Best is trial 39 with value: 0.9495709219330517.
[I 2026-07-10 16:12:07,678] Trial 46 finished with value: 0.9347571252093845 and parameters: {'weight_class_0': 2.2173431908473136, 'weight_class_1': 8.278980609802215, 'weight_class_2': 5.095096254039851}. Best is trial 39 with value: 0.9495709219330517.
[I 2026-07-10 16:12:07,712] Trial 48 finished with value: 0.9397625679361455 and parameters: {'weight_class_0': 2.18954277843946, 'weight_class_1': 9.213304798736507, 'weight_class_2': 6.168896574372887}. Best is trial 39 with value: 0.9495709219330517.
[I 2026-07-10 16:12:07,715] Trial 47 finished with value: 0.9399056798078403 and parameters: {'weight_class_0': 2.2099423951338393, 'weight_class_1': 8.872342240452227, 'weight_class_2': 6.412627510888392}. Best is trial 39 with value: 0.9495709219330517.

Best trial: 39. Best value: 0.949571:   2%|██▋                                                                                                                                   | 59/3000 [00:01<00:56, 52.42it/s]

[I 2026-07-10 16:12:07,731] Trial 49 finished with value: 0.9487718192884363 and parameters: {'weight_class_0': 0.7945010110436808, 'weight_class_1': 8.156645697591596, 'weight_class_2': 5.025912727526025}. Best is trial 39 with value: 0.9495709219330517.
[I 2026-07-10 16:12:07,749] Trial 50 finished with value: 0.9487659200827089 and parameters: {'weight_class_0': 0.8202792792489275, 'weight_class_1': 9.2861179931297, 'weight_class_2': 4.972962348011863}. Best is trial 39 with value: 0.9495709219330517.
[I 2026-07-10 16:12:07,753] Trial 51 finished with value: 0.9490918823993683 and parameters: {'weight_class_0': 0.7100612430856867, 'weight_class_1': 9.308085755358642, 'weight_class_2': 4.933468541758554}. Best is trial 39 with value: 0.9495709219330517.
[I 2026-07-10 16:12:07,779] Trial 52 finished with value: 0.9491483101499368 and parameters: {'weight_class_0': 0.6626691608453834, 'weight_class_1': 9.430831609435442, 'weight_class_2': 4.971654515847411}. Best is trial 39 with value: 0.9495709219330517.
[I 2026-07-10 16:12:07,795] Trial 53 finished with value: 0.9490833134194804 and parameters: {'weight_class_0': 0.684337068597862, 'weight_class_1': 7.405314683267839, 'weight_class_2': 5.198647865793889}. Best is trial 39 with value: 0.9495709219330517.
[I 2026-07-10 16:12:07,806] Trial 54 finished with value: 0.9491599490295609 and parameters: {'weight_class_0': 0.6794436698340449, 'weight_class_1': 7.212179831681095, 'weight_class_2': 5.383232382976822}. Best is trial 39 with value: 0.9495709219330517.
[I 2026-07-10 16:12:07,836] Trial 55 finished with value: 0.9495632938833993 and parameters: {'weight_class_0': 0.6998791780774083, 'weight_class_1': 7.171832596274495, 'weight_class_2': 7.8718015873024845}. Best is trial 39 with value: 0.9495709219330517.
[I 2026-07-10 16:12:07,846] Trial 56 finished with value: 0.9494543715922795 and parameters: {'weight_class_0': 0.708689325324296, 'weight_class_1': 7.335860319512837, 'weight_class_2': 9.015906050003716}. Best is trial 39 with value: 0.9495709219330517.
[I 2026-07-10 16:12:07,871] Trial 57 finished with value: 0.9494010797342772 and parameters: {'weight_class_0': 0.734188218788072, 'weight_class_1': 7.071533491695039, 'weight_class_2': 9.16183480363512}. Best is trial 39 with value: 0.9495709219330517.
[I 2026-07-10 16:12:07,896] Trial 58 finished with value: 0.9489146101225878 and parameters: {'weight_class_0': 0.7089223401752235, 'weight_class_1': 7.256368400025368, 'weight_class_2': 4.7868299596608175}. Best is trial 39 with value: 0.9495709219330517.
[I 2026-07-10 16:12:07,916] Trial 59 finished with value: 0.947929428625021 and parameters: {'weight_class_0': 0.8173041088159112, 'weight_class_1': 7.670779385438994, 'weight_class_2': 4.157319355243221}. Best is trial 39 with value: 0.9495709219330517.

Best trial: 39. Best value: 0.949571:   2%|███▏                                                                                                                                  | 70/3000 [00:01<00:53, 54.28it/s]

[I 2026-07-10 16:12:07,926] Trial 60 finished with value: 0.9478176050719428 and parameters: {'weight_class_0': 0.8687053002675255, 'weight_class_1': 7.42139088417762, 'weight_class_2': 4.366032272208189}. Best is trial 39 with value: 0.9495709219330517.
[I 2026-07-10 16:12:07,944] Trial 61 finished with value: 0.9488995736035607 and parameters: {'weight_class_0': 0.571474004130528, 'weight_class_1': 7.424776405697525, 'weight_class_2': 3.618175406950704}. Best is trial 39 with value: 0.9495709219330517.
[I 2026-07-10 16:12:07,957] Trial 62 finished with value: 0.9487552838298411 and parameters: {'weight_class_0': 0.6819933209852768, 'weight_class_1': 7.363832192155647, 'weight_class_2': 4.264925504672048}. Best is trial 39 with value: 0.9495709219330517.
[I 2026-07-10 16:12:07,987] Trial 63 finished with value: 0.949103388863391 and parameters: {'weight_class_0': 0.5991201833142671, 'weight_class_1': 6.732343482044547, 'weight_class_2': 4.22710885408283}. Best is trial 39 with value: 0.9495709219330517.
[I 2026-07-10 16:12:08,014] Trial 64 finished with value: 0.9350433597025972 and parameters: {'weight_class_0': 1.7946648714841313, 'weight_class_1': 7.066185717431635, 'weight_class_2': 4.082183177068266}. Best is trial 39 with value: 0.9495709219330517.
[I 2026-07-10 16:12:08,038] Trial 65 finished with value: 0.9328503417065702 and parameters: {'weight_class_0': 1.8164914334266442, 'weight_class_1': 6.712683904765299, 'weight_class_2': 3.879965060539365}. Best is trial 39 with value: 0.9495709219330517.
[I 2026-07-10 16:12:08,061] Trial 66 finished with value: 0.9440252379194582 and parameters: {'weight_class_0': 1.8115484649708393, 'weight_class_1': 6.686144488266995, 'weight_class_2': 9.213244353126965}. Best is trial 39 with value: 0.9495709219330517.
[I 2026-07-10 16:12:08,071] Trial 67 finished with value: 0.9222381071877663 and parameters: {'weight_class_0': 1.8424380981490136, 'weight_class_1': 6.655795639774344, 'weight_class_2': 2.8640753513392827}. Best is trial 39 with value: 0.9495709219330517.
[I 2026-07-10 16:12:08,095] Trial 68 finished with value: 0.9227800255386276 and parameters: {'weight_class_0': 1.8080695953793662, 'weight_class_1': 6.748019014223719, 'weight_class_2': 2.8259658674127697}. Best is trial 39 with value: 0.9495709219330517.
[I 2026-07-10 16:12:08,110] Trial 69 finished with value: 0.9417533311264444 and parameters: {'weight_class_0': 1.6811354965046625, 'weight_class_1': 6.658279254278183, 'weight_class_2': 5.5721811203292315}. Best is trial 39 with value: 0.9495709219330517.
[I 2026-07-10 16:12:08,124] Trial 71 finished with value: 0.944331782104462 and parameters: {'weight_class_0': 1.7772860113988032, 'weight_class_1': 6.726997981996417, 'weight_class_2': 8.969749735309575}. Best is trial 39 with value: 0.9495709219330517.

[I 2026-07-10 16:12:08,131] Trial 70 finished with value: 0.944016746009368 and parameters: {'weight_class_0': 1.7751737118222997, 'weight_class_1': 6.484063369860107, 'weight_class_2': 9.14368600906168}. Best is trial 39 with value: 0.9495709219330517.
[I 2026-07-10 16:12:08,143] Trial 72 finished with value: 0.9491947877005887 and parameters: {'weight_class_0': 0.39798446997150216, 'weight_class_1': 6.771685308903923, 'weight_class_2': 2.9172965959864734}. Best is trial 39 with value: 0.9495709219330517.
[I 2026-07-10 16:12:08,159] Trial 73 finished with value: 0.8652312424563954 and parameters: {'weight_class_0': 5.982241301244398, 'weight_class_1': 6.35994845701555, 'weight_class_2': 2.70862075383625}. Best is trial 39 with value: 0.9495709219330517.
[I 2026-07-10 16:12:08,195] Trial 74 finished with value: 0.9220635006707587 and parameters: {'weight_class_0': 1.730753320008646, 'weight_class_1': 6.487696037069709, 'weight_class_2': 2.6522726815235185}. Best is trial 39 with value: 0.9495709219330517.
[I 2026-07-10 16:12:08,216] Trial 75 finished with value: 0.9485586381680512 and parameters: {'weight_class_0': 0.49393082359660234, 'weight_class_1': 6.085389097927914, 'weight_class_2': 2.786196337971056}. Best is trial 39 with value: 0.9495709219330517.
[I 2026-07-10 16:12:08,223] Trial 76 finished with value: 0.9417973693545879 and parameters: {'weight_class_0': 1.60609374230236, 'weight_class_1': 6.233045749567905, 'weight_class_2': 5.521954576728044}. Best is trial 39 with value: 0.9495709219330517.
[I 2026-07-10 16:12:08,249] Trial 77 finished with value: 0.9496636543571463 and parameters: {'weight_class_0': 0.41996533778403095, 'weight_class_1': 6.1445214900237906, 'weight_class_2': 5.536242173349179}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:08,263] Trial 78 finished with value: 0.9488058302965361 and parameters: {'weight_class_0': 0.4602253908920937, 'weight_class_1': 6.187993222260521, 'weight_class_2': 9.40533564828939}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:08,278] Trial 79 finished with value: 0.9419030628112957 and parameters: {'weight_class_0': 0.3846225482898136, 'weight_class_1': 6.053954699862464, 'weight_class_2': 1.0337531832479059}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:08,292] Trial 80 finished with value: 0.947788839455324 and parameters: {'weight_class_0': 0.4091574620355098, 'weight_class_1': 6.152380688257115, 'weight_class_2': 1.9835847893594578}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:08,320] Trial 81 finished with value: 0.9410543358887269 and parameters: {'weight_class_0': 0.3776056159700419, 'weight_class_1': 6.102039634511475, 'weight_class_2': 0.9730350445066869}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:08,335] Trial 82 finished with value: 0.9444336869639091 and parameters: {'weight_class_0': 0.3758761035704852, 'weight_class_1': 6.074496735945095, 'weight_class_2': 1.185589230246859}. Best is trial 77 with value: 0.9496636543571463.

Best trial: 77. Best value: 0.949664:   3%|████▏                                                                                                                                 | 93/3000 [00:01<00:53, 53.96it/s]

[I 2026-07-10 16:12:08,361] Trial 83 finished with value: 0.933834139571235 and parameters: {'weight_class_0': 0.3966445888602657, 'weight_class_1': 7.904560384185024, 'weight_class_2': 0.7608579378118403}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:08,377] Trial 84 finished with value: 0.9478318630907467 and parameters: {'weight_class_0': 0.36245981840770203, 'weight_class_1': 7.8135632504381185, 'weight_class_2': 1.8191329171016943}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:08,392] Trial 85 finished with value: 0.9489437571109116 and parameters: {'weight_class_0': 0.3810336445478493, 'weight_class_1': 7.896999572503373, 'weight_class_2': 7.786444960056219}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:08,419] Trial 86 finished with value: 0.9434202325370634 and parameters: {'weight_class_0': 0.3462257556378584, 'weight_class_1': 7.742800236985705, 'weight_class_2': 1.0343093021990708}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:08,459] Trial 87 finished with value: 0.9488805917709179 and parameters: {'weight_class_0': 1.0736519275925411, 'weight_class_1': 7.834382749283988, 'weight_class_2': 9.5466131891272}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:08,468] Trial 89 finished with value: 0.9414656516212488 and parameters: {'weight_class_0': 1.1532406945442286, 'weight_class_1': 7.793922359656429, 'weight_class_2': 3.1662711992144734}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:08,469] Trial 88 finished with value: 0.9479687519063674 and parameters: {'weight_class_0': 1.2139267114855101, 'weight_class_1': 7.01475896464807, 'weight_class_2': 9.443075704176964}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:08,493] Trial 90 finished with value: 0.9484302599409947 and parameters: {'weight_class_0': 1.1250336400126186, 'weight_class_1': 7.861394631071227, 'weight_class_2': 7.906225247814004}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:08,508] Trial 91 finished with value: 0.9482215550619765 and parameters: {'weight_class_0': 1.0928113465631424, 'weight_class_1': 6.989928470536615, 'weight_class_2': 7.873654226488628}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:08,519] Trial 92 finished with value: 0.9479838578568578 and parameters: {'weight_class_0': 1.177967057014998, 'weight_class_1': 6.964526069447348, 'weight_class_2': 8.130100267068398}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:08,544] Trial 93 finished with value: 0.9449864744008427 and parameters: {'weight_class_0': 1.1356068478551942, 'weight_class_1': 5.640503060701781, 'weight_class_2': 4.611874503131864}. Best is trial 77 with value: 0.9496636543571463.

[I 2026-07-10 16:12:08,550] Trial 94 finished with value: 0.9429732239194744 and parameters: {'weight_class_0': 1.0745307122266166, 'weight_class_1': 6.958713211223851, 'weight_class_2': 3.245719634991959}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:08,571] Trial 95 finished with value: 0.9458404852744579 and parameters: {'weight_class_0': 1.1381130194974232, 'weight_class_1': 6.978080610501646, 'weight_class_2': 4.583799380131358}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:08,606] Trial 96 finished with value: 0.9483589364656567 and parameters: {'weight_class_0': 1.1095192104188312, 'weight_class_1': 6.97973710720609, 'weight_class_2': 8.898420139565046}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:08,628] Trial 97 finished with value: 0.9466724649041373 and parameters: {'weight_class_0': 0.9574267333901796, 'weight_class_1': 5.77440107403985, 'weight_class_2': 4.548167234134229}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:08,638] Trial 98 finished with value: 0.9457660170944396 and parameters: {'weight_class_0': 0.9726158240829443, 'weight_class_1': 4.6782859817065034, 'weight_class_2': 4.698909366093604}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:08,665] Trial 99 finished with value: 0.6797650516265251 and parameters: {'weight_class_0': 0.010600204110313372, 'weight_class_1': 9.716139033977292, 'weight_class_2': 4.486401056539218}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:08,673] Trial 100 finished with value: 0.8262059793965859 and parameters: {'weight_class_0': 0.02904212783370952, 'weight_class_1': 9.589359039994534, 'weight_class_2': 4.6145521762978525}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:08,687] Trial 101 finished with value: 0.9107404263504977 and parameters: {'weight_class_0': 0.057645041106035855, 'weight_class_1': 9.415160412690522, 'weight_class_2': 5.709515955838516}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:08,699] Trial 102 finished with value: 0.9496008245650396 and parameters: {'weight_class_0': 0.662267931499101, 'weight_class_1': 9.656136377156768, 'weight_class_2': 8.886958976130094}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:08,732] Trial 103 finished with value: 0.9469191048610829 and parameters: {'weight_class_0': 1.4544629443340096, 'weight_class_1': 9.614702374293005, 'weight_class_2': 6.847583522652648}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:08,738] Trial 104 finished with value: 0.9468253569885828 and parameters: {'weight_class_0': 1.4726637660218822, 'weight_class_1': 9.589768743355359, 'weight_class_2': 6.843544436990486}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:08,759] Trial 105 finished with value: 0.9450037587465164 and parameters: {'weight_class_0': 1.4675284965171793, 'weight_class_1': 9.581004663783533, 'weight_class_2': 5.3148940161578695}. Best is trial 77 with value: 0.9496636543571463.

Best trial: 77. Best value: 0.949664:   4%|█████▏                                                                                                                               | 117/3000 [00:02<00:53, 53.87it/s]

[I 2026-07-10 16:12:08,777] Trial 106 finished with value: 0.9469893653479753 and parameters: {'weight_class_0': 1.4417724128764358, 'weight_class_1': 9.533016913451037, 'weight_class_2': 6.904912857015874}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:08,798] Trial 107 finished with value: 0.8609424729483709 and parameters: {'weight_class_0': 0.03728361241054645, 'weight_class_1': 9.553531644637832, 'weight_class_2': 5.472185094281658}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:08,829] Trial 108 finished with value: 0.949212822669654 and parameters: {'weight_class_0': 0.6694624594949448, 'weight_class_1': 8.219704425601703, 'weight_class_2': 5.2703317740012325}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:08,845] Trial 109 finished with value: 0.9493814413612114 and parameters: {'weight_class_0': 0.640179135141266, 'weight_class_1': 8.112597422155028, 'weight_class_2': 5.311486599569977}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:08,867] Trial 110 finished with value: 0.9448334660887324 and parameters: {'weight_class_0': 1.4777530670974925, 'weight_class_1': 9.569530349669956, 'weight_class_2': 5.273015597628219}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:08,881] Trial 111 finished with value: 0.9493118067760266 and parameters: {'weight_class_0': 0.655297637439367, 'weight_class_1': 8.279759701981527, 'weight_class_2': 5.326353170397426}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:08,892] Trial 112 finished with value: 0.9492615464981594 and parameters: {'weight_class_0': 0.6611296223134642, 'weight_class_1': 9.06361124160863, 'weight_class_2': 5.297652116987752}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:08,911] Trial 113 finished with value: 0.9492946039513225 and parameters: {'weight_class_0': 0.9032709368451938, 'weight_class_1': 8.162101655508565, 'weight_class_2': 8.42804186437887}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:08,916] Trial 114 finished with value: 0.9495499934431587 and parameters: {'weight_class_0': 0.818635706303524, 'weight_class_1': 8.289326590403117, 'weight_class_2': 8.468685690966383}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:08,951] Trial 115 finished with value: 0.9495145046682687 and parameters: {'weight_class_0': 0.6090460411800116, 'weight_class_1': 8.270147710794033, 'weight_class_2': 8.509484619632593}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:08,956] Trial 116 finished with value: 0.9495850364162703 and parameters: {'weight_class_0': 0.6605484685218169, 'weight_class_1': 9.14913417279321, 'weight_class_2': 8.748457984274808}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:08,979] Trial 117 finished with value: 0.9493709323329158 and parameters: {'weight_class_0': 0.6475022383776015, 'weight_class_1': 8.086423557637183, 'weight_class_2': 9.956954693277842}. Best is trial 77 with value: 0.9496636543571463.

[I 2026-07-10 16:12:09,004] Trial 118 finished with value: 0.9496159367634505 and parameters: {'weight_class_0': 0.6581292597308742, 'weight_class_1': 8.275853804489604, 'weight_class_2': 8.276262312531609}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,019] Trial 119 finished with value: 0.9496302126906105 and parameters: {'weight_class_0': 0.6646621218481412, 'weight_class_1': 8.23803188448285, 'weight_class_2': 8.351312053569991}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,050] Trial 121 finished with value: 0.9490652915963476 and parameters: {'weight_class_0': 0.7794384503592245, 'weight_class_1': 8.199999052202038, 'weight_class_2': 5.92868905869152}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,053] Trial 120 finished with value: 0.9494927345177512 and parameters: {'weight_class_0': 0.8279575833937675, 'weight_class_1': 8.312716983993248, 'weight_class_2': 8.369682324421323}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,066] Trial 122 finished with value: 0.9494573921726461 and parameters: {'weight_class_0': 0.853345197797091, 'weight_class_1': 8.247749780404927, 'weight_class_2': 8.80562640558225}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,089] Trial 123 finished with value: 0.9495792101042465 and parameters: {'weight_class_0': 0.7917801954080375, 'weight_class_1': 8.398829478163433, 'weight_class_2': 8.400716887936154}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,114] Trial 124 finished with value: 0.9493740289705409 and parameters: {'weight_class_0': 0.8755856382372407, 'weight_class_1': 8.360383179539737, 'weight_class_2': 8.389484389480343}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,129] Trial 125 finished with value: 0.878771127130307 and parameters: {'weight_class_0': 9.033775843785959, 'weight_class_1': 8.379313317423989, 'weight_class_2': 9.972084423036284}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,148] Trial 126 finished with value: 0.9494815803864566 and parameters: {'weight_class_0': 0.8383930293932337, 'weight_class_1': 8.410639295551048, 'weight_class_2': 8.366213390644877}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,177] Trial 127 finished with value: 0.9470308304635493 and parameters: {'weight_class_0': 0.2149411948847903, 'weight_class_1': 8.544487373461047, 'weight_class_2': 8.748413167317052}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,200] Trial 128 finished with value: 0.9471569171013927 and parameters: {'weight_class_0': 0.2168273599986117, 'weight_class_1': 8.460915586713414, 'weight_class_2': 8.410510794012232}. Best is trial 77 with value: 0.9496636543571463.

Best trial: 77. Best value: 0.949664:   5%|██████▏                                                                                                                              | 140/3000 [00:02<00:53, 53.51it/s]

[I 2026-07-10 16:12:09,219] Trial 130 finished with value: 0.9466487336236566 and parameters: {'weight_class_0': 0.19491898409578579, 'weight_class_1': 8.509342248702746, 'weight_class_2': 8.42318296606908}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,219] Trial 129 finished with value: 0.9463055434037084 and parameters: {'weight_class_0': 0.18391619460408537, 'weight_class_1': 8.495963498943054, 'weight_class_2': 8.48047075160407}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,240] Trial 131 finished with value: 0.8810443179318521 and parameters: {'weight_class_0': 7.944739150796719, 'weight_class_1': 8.523456394225924, 'weight_class_2': 8.348996340942994}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,259] Trial 132 finished with value: 0.9474999988251026 and parameters: {'weight_class_0': 0.24130772474907658, 'weight_class_1': 8.55093666998552, 'weight_class_2': 8.785154400780863}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,269] Trial 133 finished with value: 0.9494186995587578 and parameters: {'weight_class_0': 0.8946427013858618, 'weight_class_1': 8.606897579492207, 'weight_class_2': 8.746593330058007}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,303] Trial 134 finished with value: 0.9464981467757739 and parameters: {'weight_class_0': 0.21190326310652163, 'weight_class_1': 9.97688965152251, 'weight_class_2': 8.616431062243887}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,309] Trial 135 finished with value: 0.9442665179029363 and parameters: {'weight_class_0': 2.0436959946085587, 'weight_class_1': 8.624867412594115, 'weight_class_2': 8.690965151088937}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,345] Trial 136 finished with value: 0.9470571453486952 and parameters: {'weight_class_0': 0.22020640921825296, 'weight_class_1': 9.062636431699179, 'weight_class_2': 8.293820984222346}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,351] Trial 137 finished with value: 0.9481311830195073 and parameters: {'weight_class_0': 1.315403277007964, 'weight_class_1': 8.71965304104237, 'weight_class_2': 8.715346327323807}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,376] Trial 138 finished with value: 0.9493558005581999 and parameters: {'weight_class_0': 0.8789036990350371, 'weight_class_1': 9.098730017158715, 'weight_class_2': 7.636068295311335}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,388] Trial 139 finished with value: 0.9492991543837149 and parameters: {'weight_class_0': 0.887892925950355, 'weight_class_1': 8.719441680748549, 'weight_class_2': 7.610699280700081}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,398] Trial 140 finished with value: 0.9493984859937682 and parameters: {'weight_class_0': 0.9326921517608806, 'weight_class_1': 9.156269318289748, 'weight_class_2': 8.946107920642008}. Best is trial 77 with value: 0.9496636543571463.

[I 2026-07-10 16:12:09,429] Trial 142 finished with value: 0.949625783465596 and parameters: {'weight_class_0': 0.577682773921688, 'weight_class_1': 9.02485063006099, 'weight_class_2': 7.661325904726569}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,433] Trial 141 finished with value: 0.9480314149443481 and parameters: {'weight_class_0': 1.291319719440047, 'weight_class_1': 9.156846886218203, 'weight_class_2': 7.567726413483964}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,469] Trial 143 finished with value: 0.9495594907579715 and parameters: {'weight_class_0': 0.5497901176994334, 'weight_class_1': 9.084253492950483, 'weight_class_2': 7.5381719114399495}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,482] Trial 144 finished with value: 0.9484660082706801 and parameters: {'weight_class_0': 1.2655440546701477, 'weight_class_1': 9.110326115443442, 'weight_class_2': 9.022872069715962}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,496] Trial 145 finished with value: 0.9493210779368325 and parameters: {'weight_class_0': 0.5552475540643149, 'weight_class_1': 7.574027181278629, 'weight_class_2': 9.036746995150148}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,504] Trial 146 finished with value: 0.9041241092822703 and parameters: {'weight_class_0': 5.56596854988426, 'weight_class_1': 9.132093942031545, 'weight_class_2': 7.72218733245953}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,530] Trial 147 finished with value: 0.94921791605181 and parameters: {'weight_class_0': 0.5201156911870142, 'weight_class_1': 7.565877430709312, 'weight_class_2': 9.023788423099994}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,553] Trial 148 finished with value: 0.9493596339228523 and parameters: {'weight_class_0': 0.5036454959283587, 'weight_class_1': 7.53580012955572, 'weight_class_2': 8.072072722780824}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,567] Trial 149 finished with value: 0.9494326910585964 and parameters: {'weight_class_0': 0.5351317712800079, 'weight_class_1': 8.882623852386816, 'weight_class_2': 8.113109215244322}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,593] Trial 150 finished with value: 0.9493897162459785 and parameters: {'weight_class_0': 0.4940635495549791, 'weight_class_1': 7.4894024938518715, 'weight_class_2': 7.969872866944546}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,614] Trial 152 finished with value: 0.9136757652959816 and parameters: {'weight_class_0': 4.84503400808921, 'weight_class_1': 8.902038632605272, 'weight_class_2': 8.081846723849505}. Best is trial 77 with value: 0.9496636543571463.

Best trial: 77. Best value: 0.949664:   5%|███████▏                                                                                                                             | 163/3000 [00:03<00:51, 54.72it/s]

[I 2026-07-10 16:12:09,623] Trial 151 finished with value: 0.9494614086642086 and parameters: {'weight_class_0': 0.5279537485861325, 'weight_class_1': 8.842559480882034, 'weight_class_2': 8.111645869662432}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,647] Trial 154 finished with value: 0.9494654547675797 and parameters: {'weight_class_0': 0.503594935708745, 'weight_class_1': 8.78336538892583, 'weight_class_2': 7.952774106476299}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,662] Trial 153 finished with value: 0.9494303730462622 and parameters: {'weight_class_0': 0.5203056854304224, 'weight_class_1': 8.852727257366357, 'weight_class_2': 8.191235422881116}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,681] Trial 155 finished with value: 0.9494364097688547 and parameters: {'weight_class_0': 0.502308613645059, 'weight_class_1': 8.91760033626258, 'weight_class_2': 8.057046541617847}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,698] Trial 157 finished with value: 0.9494573030181943 and parameters: {'weight_class_0': 0.8183725716149342, 'weight_class_1': 8.884426042004687, 'weight_class_2': 7.429190502034295}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,716] Trial 156 finished with value: 0.9495882761531617 and parameters: {'weight_class_0': 0.5347176757430139, 'weight_class_1': 8.936900031760143, 'weight_class_2': 7.328561677427924}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,727] Trial 158 finished with value: 0.9495845310462507 and parameters: {'weight_class_0': 0.8396015193204579, 'weight_class_1': 8.870361448180985, 'weight_class_2': 9.606099966602978}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,765] Trial 159 finished with value: 0.9494925043334635 and parameters: {'weight_class_0': 0.7887800774973635, 'weight_class_1': 8.021883853330738, 'weight_class_2': 9.21383355498767}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,778] Trial 160 finished with value: 0.9495479053969526 and parameters: {'weight_class_0': 0.792275118764872, 'weight_class_1': 8.05551748811682, 'weight_class_2': 9.625172773843234}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,799] Trial 161 finished with value: 0.949291651954448 and parameters: {'weight_class_0': 0.8373751717955464, 'weight_class_1': 8.001462084061366, 'weight_class_2': 7.42939440995765}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,820] Trial 162 finished with value: 0.9298545059673528 and parameters: {'weight_class_0': 0.7588588360159554, 'weight_class_1': 1.190258872926936, 'weight_class_2': 7.470053630044219}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,829] Trial 163 finished with value: 0.9496243859674003 and parameters: {'weight_class_0': 0.7610751349459367, 'weight_class_1': 8.036867580119207, 'weight_class_2': 8.241553370630896}. Best is trial 77 with value: 0.9496636543571463.

Best trial: 77. Best value: 0.949664:   6%|███████▊                                                                                                                             | 175/3000 [00:03<00:51, 54.76it/s]

[I 2026-07-10 16:12:09,834] Trial 164 finished with value: 0.9274488888601619 and parameters: {'weight_class_0': 0.7737527894568104, 'weight_class_1': 1.1135670128354684, 'weight_class_2': 7.833081332870319}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,864] Trial 166 finished with value: 0.9492727628732697 and parameters: {'weight_class_0': 1.0474410121172146, 'weight_class_1': 9.831272157973986, 'weight_class_2': 9.360101992175219}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,887] Trial 165 finished with value: 0.9490380556526294 and parameters: {'weight_class_0': 1.0171799473087826, 'weight_class_1': 7.9932286393432195, 'weight_class_2': 9.346290888760294}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,892] Trial 167 finished with value: 0.949001339178535 and parameters: {'weight_class_0': 1.0383988400353188, 'weight_class_1': 8.006680453978339, 'weight_class_2': 9.667920512837583}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,918] Trial 168 finished with value: 0.9492160792869351 and parameters: {'weight_class_0': 1.0898678667697363, 'weight_class_1': 9.306563087120647, 'weight_class_2': 9.69649114594905}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,939] Trial 169 finished with value: 0.948996829629937 and parameters: {'weight_class_0': 1.0290151670867436, 'weight_class_1': 8.04369104158436, 'weight_class_2': 9.303820880401814}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,954] Trial 170 finished with value: 0.9491831810190486 and parameters: {'weight_class_0': 1.100171274492697, 'weight_class_1': 9.391266292403955, 'weight_class_2': 9.583233708541782}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:09,979] Trial 171 finished with value: 0.9488230248969808 and parameters: {'weight_class_0': 1.2243914800855613, 'weight_class_1': 9.82444812925138, 'weight_class_2': 9.509469111971043}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:10,002] Trial 172 finished with value: 0.9492918893658834 and parameters: {'weight_class_0': 1.0223806038350163, 'weight_class_1': 9.271339322219065, 'weight_class_2': 9.577918355769702}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:10,018] Trial 173 finished with value: 0.9492032495934065 and parameters: {'weight_class_0': 1.0829557748549576, 'weight_class_1': 9.367656982618096, 'weight_class_2': 9.691614359605131}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:10,026] Trial 174 finished with value: 0.9492983576627635 and parameters: {'weight_class_0': 1.0218851250297591, 'weight_class_1': 9.261213069929951, 'weight_class_2': 9.470041569435802}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:10,041] Trial 175 finished with value: 0.9484743440287242 and parameters: {'weight_class_0': 0.30473483542757784, 'weight_class_1': 9.384359198846779, 'weight_class_2': 7.029041699047533}. Best is trial 77 with value: 0.9496636543571463.

Best trial: 77. Best value: 0.949664:   6%|████████▏                                                                                                                            | 186/3000 [00:03<00:51, 54.69it/s]

[I 2026-07-10 16:12:10,051] Trial 176 finished with value: 0.9488116051048626 and parameters: {'weight_class_0': 0.3323223539708465, 'weight_class_1': 8.24528782197166, 'weight_class_2': 7.1558833653696485}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:10,085] Trial 177 finished with value: 0.9481872647702415 and parameters: {'weight_class_0': 0.31889292632069627, 'weight_class_1': 9.34646040285494, 'weight_class_2': 9.527392341240597}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:10,112] Trial 178 finished with value: 0.9486652100295335 and parameters: {'weight_class_0': 0.3181153410867543, 'weight_class_1': 8.261826513877262, 'weight_class_2': 7.269967869367589}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:10,135] Trial 179 finished with value: 0.9480410225010125 and parameters: {'weight_class_0': 0.2902061895339022, 'weight_class_1': 8.321236863416898, 'weight_class_2': 9.224513184896047}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:10,144] Trial 180 finished with value: 0.9496255119038106 and parameters: {'weight_class_0': 0.679344418548617, 'weight_class_1': 8.354761738954789, 'weight_class_2': 8.568966547908463}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:10,167] Trial 181 finished with value: 0.9489318902597871 and parameters: {'weight_class_0': 0.35564433596188466, 'weight_class_1': 8.340076011861717, 'weight_class_2': 7.2049770195904905}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:10,174] Trial 182 finished with value: 0.9483842310709542 and parameters: {'weight_class_0': 0.32980772367496497, 'weight_class_1': 8.211795197790213, 'weight_class_2': 9.159531278220278}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:10,207] Trial 183 finished with value: 0.949564172655197 and parameters: {'weight_class_0': 0.6826776964853944, 'weight_class_1': 7.737168324586792, 'weight_class_2': 8.632655837301483}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:10,209] Trial 184 finished with value: 0.9487714536595755 and parameters: {'weight_class_0': 0.6246469118909661, 'weight_class_1': 4.773383731059438, 'weight_class_2': 8.519220767407706}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:10,223] Trial 185 finished with value: 0.9486909928091666 and parameters: {'weight_class_0': 0.629800285160751, 'weight_class_1': 4.610841659224416, 'weight_class_2': 8.510377856342922}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:10,261] Trial 187 finished with value: 0.9495933505140215 and parameters: {'weight_class_0': 0.7011656234968269, 'weight_class_1': 7.730441056469758, 'weight_class_2': 8.61174768319634}. Best is trial 77 with value: 0.9496636543571463.

Best trial: 191. Best value: 0.949718:   7%|████████▋                                                                                                                           | 198/3000 [00:03<00:50, 55.81it/s]

[I 2026-07-10 16:12:10,276] Trial 188 finished with value: 0.9495661467260259 and parameters: {'weight_class_0': 0.678350340693302, 'weight_class_1': 7.762479516995402, 'weight_class_2': 8.568969898735428}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:10,278] Trial 186 finished with value: 0.9495475890446342 and parameters: {'weight_class_0': 0.6911470215369373, 'weight_class_1': 8.382026966761476, 'weight_class_2': 9.206898810775373}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:10,292] Trial 189 finished with value: 0.9495379399980314 and parameters: {'weight_class_0': 0.6238041555021987, 'weight_class_1': 7.73315285222332, 'weight_class_2': 8.477304087642851}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:10,326] Trial 190 finished with value: 0.9496114363179381 and parameters: {'weight_class_0': 0.6511931335621378, 'weight_class_1': 8.67177939187684, 'weight_class_2': 8.513059717060425}. Best is trial 77 with value: 0.9496636543571463.
[I 2026-07-10 16:12:10,337] Trial 191 finished with value: 0.9497178512629185 and parameters: {'weight_class_0': 0.721077871849306, 'weight_class_1': 8.645064905320755, 'weight_class_2': 8.572897260563938}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:10,353] Trial 192 finished with value: 0.9495358799932246 and parameters: {'weight_class_0': 0.6322491224359169, 'weight_class_1': 7.768283693737572, 'weight_class_2': 8.568048078950993}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:10,391] Trial 193 finished with value: 0.9496290445133037 and parameters: {'weight_class_0': 0.6979502768441768, 'weight_class_1': 7.707166578045616, 'weight_class_2': 8.223095544518292}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:10,399] Trial 194 finished with value: 0.9496483752303368 and parameters: {'weight_class_0': 0.7805492984201452, 'weight_class_1': 8.647387644707386, 'weight_class_2': 8.293467988684176}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:10,412] Trial 195 finished with value: 0.9495538916930192 and parameters: {'weight_class_0': 0.6765154591128677, 'weight_class_1': 7.817321987803547, 'weight_class_2': 8.62102989743274}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:10,438] Trial 196 finished with value: 0.7235506421601459 and parameters: {'weight_class_0': 0.0196581583676404, 'weight_class_1': 7.7060384161161535, 'weight_class_2': 0.02300210034084582}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:10,454] Trial 197 finished with value: 0.947399526956004 and parameters: {'weight_class_0': 1.3599240534645227, 'weight_class_1': 7.293376539770771, 'weight_class_2': 8.856260996379172}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:10,502] Trial 200 finished with value: 0.9292175324786965 and parameters: {'weight_class_0': 0.07919296314533164, 'weight_class_1': 8.725771490971004, 'weight_class_2': 8.795929550808866}. Best is trial 191 with value: 0.9497178512629185.

Best trial: 191. Best value: 0.949718:   7%|█████████▏                                                                                                                          | 209/3000 [00:03<00:53, 52.14it/s]

[I 2026-07-10 16:12:10,504] Trial 198 finished with value: 0.9480342276227569 and parameters: {'weight_class_0': 1.3533314710060917, 'weight_class_1': 8.667350676817923, 'weight_class_2': 8.64270030531513}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:10,508] Trial 199 finished with value: 0.6601839149810711 and parameters: {'weight_class_0': 0.008359894220299702, 'weight_class_1': 8.633153015212589, 'weight_class_2': 8.265599284537767}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:10,544] Trial 202 finished with value: 0.9427039075760262 and parameters: {'weight_class_0': 0.12422210839112313, 'weight_class_1': 8.631165796776608, 'weight_class_2': 8.243573539702236}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:10,553] Trial 201 finished with value: 0.8098744963413123 and parameters: {'weight_class_0': 0.030063652496028714, 'weight_class_1': 8.720089826008751, 'weight_class_2': 8.204474962964008}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:10,581] Trial 203 finished with value: 0.9470991108039132 and parameters: {'weight_class_0': 1.3990637128762216, 'weight_class_1': 7.236346850754128, 'weight_class_2': 8.251059142627124}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:10,598] Trial 204 finished with value: 0.9475896200003616 and parameters: {'weight_class_0': 1.4440528691654166, 'weight_class_1': 8.660850599742833, 'weight_class_2': 8.218399572947037}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:10,607] Trial 205 finished with value: 0.9492196140040233 and parameters: {'weight_class_0': 0.45117975037735575, 'weight_class_1': 8.644630238173145, 'weight_class_2': 8.261786434218685}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:10,631] Trial 206 finished with value: 0.9492804046494615 and parameters: {'weight_class_0': 0.9135079798204473, 'weight_class_1': 8.586172223618156, 'weight_class_2': 8.27827879761399}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:10,665] Trial 207 finished with value: 0.9493679998013702 and parameters: {'weight_class_0': 0.5010563615624783, 'weight_class_1': 9.037952050062703, 'weight_class_2': 8.254716952368115}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:10,670] Trial 208 finished with value: 0.9494033151663542 and parameters: {'weight_class_0': 0.48010632637873196, 'weight_class_1': 9.015613278975344, 'weight_class_2': 7.731136595492172}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:10,689] Trial 209 finished with value: 0.9494447766343136 and parameters: {'weight_class_0': 0.4948737474465643, 'weight_class_1': 8.918151038794289, 'weight_class_2': 7.7893031685434675}. Best is trial 191 with value: 0.9497178512629185.

[I 2026-07-10 16:12:10,709] Trial 210 finished with value: 0.9494482317343632 and parameters: {'weight_class_0': 0.4980424326757731, 'weight_class_1': 8.928353724016196, 'weight_class_2': 7.75204898335573}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:10,737] Trial 211 finished with value: 0.9493972887726935 and parameters: {'weight_class_0': 0.4823630057761213, 'weight_class_1': 8.975048699078096, 'weight_class_2': 7.81140469441562}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:10,752] Trial 212 finished with value: 0.949374867390412 and parameters: {'weight_class_0': 0.47349077123017935, 'weight_class_1': 8.970903916509071, 'weight_class_2': 7.817786654895648}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:10,759] Trial 214 finished with value: 0.9493992722829914 and parameters: {'weight_class_0': 0.8718847559183345, 'weight_class_1': 8.946907974225068, 'weight_class_2': 7.765409156650545}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:10,772] Trial 213 finished with value: 0.9493989042860148 and parameters: {'weight_class_0': 0.8820306762558278, 'weight_class_1': 9.0295736301609, 'weight_class_2': 7.7658128791025085}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:10,813] Trial 215 finished with value: 0.9493510075899669 and parameters: {'weight_class_0': 0.4812244478088287, 'weight_class_1': 8.969958589354718, 'weight_class_2': 7.9582374662263895}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:10,818] Trial 216 finished with value: 0.9494228802210324 and parameters: {'weight_class_0': 0.7960210452435525, 'weight_class_1': 7.5685740290945285, 'weight_class_2': 7.887174880838476}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:10,827] Trial 217 finished with value: 0.9494763550572703 and parameters: {'weight_class_0': 0.769250764843085, 'weight_class_1': 7.59819619859187, 'weight_class_2': 7.883353626514792}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:10,842] Trial 218 finished with value: 0.9493338133949253 and parameters: {'weight_class_0': 0.8357650137567896, 'weight_class_1': 7.916733357957582, 'weight_class_2': 7.925138593843681}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:10,898] Trial 220 finished with value: 0.949531247818376 and parameters: {'weight_class_0': 0.7602857772426463, 'weight_class_1': 7.854056052393787, 'weight_class_2': 8.70782847034069}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:10,911] Trial 219 finished with value: 0.9495187679774238 and parameters: {'weight_class_0': 0.753253967380811, 'weight_class_1': 7.882291641263152, 'weight_class_2': 8.687229497634148}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:10,921] Trial 222 finished with value: 0.9496307109724523 and parameters: {'weight_class_0': 0.7391911279198904, 'weight_class_1': 7.871539199973612, 'weight_class_2': 7.981538093677365}. Best is trial 191 with value: 0.9497178512629185.

Best trial: 191. Best value: 0.949718:   8%|██████████▏                                                                                                                         | 232/3000 [00:04<00:52, 52.55it/s]

[I 2026-07-10 16:12:10,925] Trial 221 finished with value: 0.9495012678748239 and parameters: {'weight_class_0': 0.7500593074031933, 'weight_class_1': 7.765454954447102, 'weight_class_2': 8.693492182742844}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:10,952] Trial 223 finished with value: 0.949537121776098 and parameters: {'weight_class_0': 0.6936337611220341, 'weight_class_1': 7.596105299858961, 'weight_class_2': 8.651257874706618}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:10,959] Trial 224 finished with value: 0.9495111859287232 and parameters: {'weight_class_0': 0.6303520809761746, 'weight_class_1': 7.854687172128327, 'weight_class_2': 8.660268617409928}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,015] Trial 226 finished with value: 0.9496031079540662 and parameters: {'weight_class_0': 0.7003899324684926, 'weight_class_1': 7.81909762874824, 'weight_class_2': 8.66381962133134}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,023] Trial 225 finished with value: 0.9495290787005507 and parameters: {'weight_class_0': 0.6924324026656593, 'weight_class_1': 7.856533115467892, 'weight_class_2': 8.904006667056327}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,030] Trial 227 finished with value: 0.9496068965638931 and parameters: {'weight_class_0': 0.7359426191970173, 'weight_class_1': 7.907483521476825, 'weight_class_2': 8.708282352155285}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,044] Trial 228 finished with value: 0.949549483400946 and parameters: {'weight_class_0': 0.6711895114915212, 'weight_class_1': 7.860417583831488, 'weight_class_2': 8.670971962428501}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,078] Trial 229 finished with value: 0.9451545539029677 and parameters: {'weight_class_0': 0.716616902422443, 'weight_class_1': 2.5172545085464537, 'weight_class_2': 8.630566857271553}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,091] Trial 230 finished with value: 0.9495194972379329 and parameters: {'weight_class_0': 0.6612265467847683, 'weight_class_1': 8.09055489527142, 'weight_class_2': 8.898258425859028}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,104] Trial 231 finished with value: 0.9495071622848159 and parameters: {'weight_class_0': 0.6491222061527502, 'weight_class_1': 8.067150667613223, 'weight_class_2': 8.899950952684655}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,122] Trial 233 finished with value: 0.9492064711525864 and parameters: {'weight_class_0': 1.0084991501570149, 'weight_class_1': 8.441286386831178, 'weight_class_2': 8.94575203860073}. Best is trial 191 with value: 0.9497178512629185.

[I 2026-07-10 16:12:11,143] Trial 232 finished with value: 0.9486665008509144 and parameters: {'weight_class_0': 1.14468829754022, 'weight_class_1': 8.465058421720785, 'weight_class_2': 8.970715706450221}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,160] Trial 234 finished with value: 0.949033581269782 and parameters: {'weight_class_0': 0.9496243640401122, 'weight_class_1': 7.389893241022521, 'weight_class_2': 8.925746105877844}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,169] Trial 235 finished with value: 0.9483667082516355 and parameters: {'weight_class_0': 1.181026100381415, 'weight_class_1': 8.062689393486583, 'weight_class_2': 8.963998275054431}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,187] Trial 236 finished with value: 0.9491288575421227 and parameters: {'weight_class_0': 0.9966153642207869, 'weight_class_1': 8.142127302708607, 'weight_class_2': 8.967529614425539}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,225] Trial 237 finished with value: 0.941331499982279 and parameters: {'weight_class_0': 0.9760040662212175, 'weight_class_1': 2.539297599427569, 'weight_class_2': 8.982560007637858}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,255] Trial 238 finished with value: 0.9489198222551112 and parameters: {'weight_class_0': 1.045669422536613, 'weight_class_1': 8.437970365061584, 'weight_class_2': 8.413869094824937}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,263] Trial 240 finished with value: 0.948916995804285 and parameters: {'weight_class_0': 0.9674281908761109, 'weight_class_1': 7.357780062112611, 'weight_class_2': 8.425065017284108}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,272] Trial 239 finished with value: 0.9485868954981801 and parameters: {'weight_class_0': 1.0263603843282822, 'weight_class_1': 7.338412108477407, 'weight_class_2': 8.39092900971814}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,285] Trial 241 finished with value: 0.9488433150129323 and parameters: {'weight_class_0': 0.9900904452146994, 'weight_class_1': 7.442227682956763, 'weight_class_2': 8.418430145707754}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,311] Trial 243 finished with value: 0.9484640931025733 and parameters: {'weight_class_0': 0.3197968751307595, 'weight_class_1': 8.414396653524564, 'weight_class_2': 8.434259076949024}. Best is trial 191 with value: 0.9497178512629185.

Best trial: 191. Best value: 0.949718:   8%|███████████▏                                                                                                                        | 254/3000 [00:04<00:52, 52.41it/s]

[I 2026-07-10 16:12:11,318] Trial 242 finished with value: 0.948089218697914 and parameters: {'weight_class_0': 0.27157906112446145, 'weight_class_1': 8.069970263020313, 'weight_class_2': 8.4175766715109}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,361] Trial 244 finished with value: 0.948469591659037 and parameters: {'weight_class_0': 0.3165843528851126, 'weight_class_1': 8.38646278112482, 'weight_class_2': 8.350735344031841}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,371] Trial 245 finished with value: 0.9481514233696609 and parameters: {'weight_class_0': 0.27320848650509594, 'weight_class_1': 7.418015666448519, 'weight_class_2': 8.418802840337474}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,388] Trial 246 finished with value: 0.9484225378518558 and parameters: {'weight_class_0': 0.31172737564280306, 'weight_class_1': 7.2135148386052075, 'weight_class_2': 8.427987253073608}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,405] Trial 247 finished with value: 0.9483655189208319 and parameters: {'weight_class_0': 0.2826348739198148, 'weight_class_1': 5.36479652273005, 'weight_class_2': 8.082773903291507}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,418] Trial 248 finished with value: 0.948597647135189 and parameters: {'weight_class_0': 0.3218938242118309, 'weight_class_1': 7.560287144332871, 'weight_class_2': 8.061842285946609}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,449] Trial 249 finished with value: 0.9486610290255574 and parameters: {'weight_class_0': 0.3330468454346723, 'weight_class_1': 7.6855915853504895, 'weight_class_2': 8.080669210107857}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,468] Trial 250 finished with value: 0.9486317800823435 and parameters: {'weight_class_0': 0.3305269035682464, 'weight_class_1': 8.12017377693641, 'weight_class_2': 8.056485357832456}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,493] Trial 252 finished with value: 0.8656393901607196 and parameters: {'weight_class_0': 9.852649994928585, 'weight_class_1': 7.779139607089871, 'weight_class_2': 8.049088314375432}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,507] Trial 251 finished with value: 0.94932942125309 and parameters: {'weight_class_0': 0.4766158823660051, 'weight_class_1': 7.652815929970441, 'weight_class_2': 8.05227842813454}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,521] Trial 253 finished with value: 0.9494212078020734 and parameters: {'weight_class_0': 0.5527428922205622, 'weight_class_1': 7.653178565281781, 'weight_class_2': 8.196933792195805}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,537] Trial 254 finished with value: 0.9494027057797277 and parameters: {'weight_class_0': 0.514298814228176, 'weight_class_1': 7.659191578469003, 'weight_class_2': 8.006149508996845}. Best is trial 191 with value: 0.9497178512629185.

Best trial: 191. Best value: 0.949718:   9%|███████████▋                                                                                                                        | 265/3000 [00:05<00:51, 53.53it/s]

[I 2026-07-10 16:12:11,568] Trial 255 finished with value: 0.9494971825502893 and parameters: {'weight_class_0': 0.579866001399095, 'weight_class_1': 7.691126999437313, 'weight_class_2': 8.137041246432075}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,596] Trial 257 finished with value: 0.8671415771249703 and parameters: {'weight_class_0': 9.80393393023433, 'weight_class_1': 7.6791289192473595, 'weight_class_2': 8.593667042151495}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,598] Trial 256 finished with value: 0.9495394444041724 and parameters: {'weight_class_0': 0.5463184052997149, 'weight_class_1': 7.648051309712515, 'weight_class_2': 7.534661459859258}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,611] Trial 258 finished with value: 0.9494015235674915 and parameters: {'weight_class_0': 0.5693913033351805, 'weight_class_1': 8.154728789632077, 'weight_class_2': 8.59056509867882}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,642] Trial 259 finished with value: 0.9493687856127832 and parameters: {'weight_class_0': 0.5620264922091919, 'weight_class_1': 7.774606928094899, 'weight_class_2': 8.592030744264381}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,671] Trial 260 finished with value: 0.9496415085510378 and parameters: {'weight_class_0': 0.5869294005327839, 'weight_class_1': 9.203059967832177, 'weight_class_2': 7.415069527404212}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,686] Trial 261 finished with value: 0.9494524916048852 and parameters: {'weight_class_0': 0.5745867181436933, 'weight_class_1': 8.778957771098534, 'weight_class_2': 8.616424177274496}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,705] Trial 263 finished with value: 0.9494650368450285 and parameters: {'weight_class_0': 0.8155521883541401, 'weight_class_1': 8.737191180620197, 'weight_class_2': 7.474433370854859}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,714] Trial 262 finished with value: 0.9496026462486687 and parameters: {'weight_class_0': 0.8162164347037575, 'weight_class_1': 8.719640414557535, 'weight_class_2': 8.649786423918867}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,744] Trial 264 finished with value: 0.9496256983950166 and parameters: {'weight_class_0': 0.7615835108348084, 'weight_class_1': 8.746271215689616, 'weight_class_2': 7.548021513688081}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,761] Trial 266 finished with value: 0.9495911709437225 and parameters: {'weight_class_0': 0.8268292534716091, 'weight_class_1': 8.769883438835064, 'weight_class_2': 8.582726365685646}. Best is trial 191 with value: 0.9497178512629185.

Best trial: 191. Best value: 0.949718:   9%|████████████                                                                                                                        | 275/3000 [00:05<00:55, 49.32it/s]

[I 2026-07-10 16:12:11,766] Trial 265 finished with value: 0.9495764009262421 and parameters: {'weight_class_0': 0.7892558541637534, 'weight_class_1': 8.777682278266687, 'weight_class_2': 7.563777065658674}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,792] Trial 267 finished with value: 0.949550107953265 and parameters: {'weight_class_0': 0.8363744284309593, 'weight_class_1': 8.666720828091709, 'weight_class_2': 8.761747950016236}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,844] Trial 268 finished with value: 0.9493797644370227 and parameters: {'weight_class_0': 0.8594340206461288, 'weight_class_1': 9.234422509696303, 'weight_class_2': 7.556239760876522}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,860] Trial 270 finished with value: 0.9496961146744303 and parameters: {'weight_class_0': 0.818796741336721, 'weight_class_1': 9.284074526919744, 'weight_class_2': 8.816743139637659}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,865] Trial 269 finished with value: 0.9493992887285874 and parameters: {'weight_class_0': 0.8189979929396698, 'weight_class_1': 8.689408268933285, 'weight_class_2': 7.364435284667886}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,879] Trial 271 finished with value: 0.9492021656561263 and parameters: {'weight_class_0': 0.8336015672452143, 'weight_class_1': 9.196847688314318, 'weight_class_2': 6.625778582772497}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,890] Trial 272 finished with value: 0.9265955991729701 and parameters: {'weight_class_0': 4.08451676324778, 'weight_class_1': 9.221759067765275, 'weight_class_2': 8.82196002150294}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,906] Trial 273 finished with value: 0.9479947661285757 and parameters: {'weight_class_0': 1.212985116122334, 'weight_class_1': 9.261240904875992, 'weight_class_2': 6.717481904123165}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,929] Trial 275 finished with value: 0.948209618735036 and parameters: {'weight_class_0': 1.172047301325607, 'weight_class_1': 8.572212828360938, 'weight_class_2': 6.96658947019489}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,939] Trial 274 finished with value: 0.9482608341426356 and parameters: {'weight_class_0': 1.202116027386343, 'weight_class_1': 9.141899302542882, 'weight_class_2': 7.14433281475881}. Best is trial 191 with value: 0.9497178512629185.

Best trial: 191. Best value: 0.949718:  10%|████████████▌                                                                                                                       | 286/3000 [00:05<00:52, 51.72it/s]

[I 2026-07-10 16:12:11,977] Trial 276 finished with value: 0.9487475716303925 and parameters: {'weight_class_0': 1.2265115651382128, 'weight_class_1': 9.17231880263301, 'weight_class_2': 9.976696457074459}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:11,987] Trial 277 finished with value: 0.9482403451042695 and parameters: {'weight_class_0': 1.2390970500048808, 'weight_class_1': 9.240866176718939, 'weight_class_2': 7.457301542672341}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,002] Trial 278 finished with value: 0.9482007454715909 and parameters: {'weight_class_0': 1.2236477558776695, 'weight_class_1': 8.79951094048844, 'weight_class_2': 7.609001453009431}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,032] Trial 279 finished with value: 0.9482090936168955 and parameters: {'weight_class_0': 1.225865258131738, 'weight_class_1': 9.216882716305054, 'weight_class_2': 7.226348299246592}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,054] Trial 280 finished with value: 0.948223311165953 and parameters: {'weight_class_0': 1.173850385622854, 'weight_class_1': 8.512227575573718, 'weight_class_2': 7.080003309055257}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,073] Trial 281 finished with value: 0.9493017223081778 and parameters: {'weight_class_0': 0.9667240281749154, 'weight_class_1': 8.85311868427439, 'weight_class_2': 9.103279305479713}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,093] Trial 282 finished with value: 0.948466903130479 and parameters: {'weight_class_0': 1.1958146252098902, 'weight_class_1': 9.705849441928756, 'weight_class_2': 7.260118570638036}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,132] Trial 283 finished with value: 0.9493947086713547 and parameters: {'weight_class_0': 0.9189470432132223, 'weight_class_1': 9.48381167044507, 'weight_class_2': 8.19929292861716}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,134] Trial 284 finished with value: 0.9493883164524789 and parameters: {'weight_class_0': 0.8896593654057802, 'weight_class_1': 8.81292742769938, 'weight_class_2': 8.264007381271256}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,144] Trial 285 finished with value: 0.9493340437437806 and parameters: {'weight_class_0': 0.9056320759312815, 'weight_class_1': 8.824470871035803, 'weight_class_2': 8.255762369870698}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,170] Trial 286 finished with value: 0.9495006744323765 and parameters: {'weight_class_0': 0.9346382598679936, 'weight_class_1': 9.629028097084415, 'weight_class_2': 9.137271168214067}. Best is trial 191 with value: 0.9497178512629185.

Best trial: 191. Best value: 0.949718:  10%|█████████████                                                                                                                       | 298/3000 [00:05<00:49, 54.64it/s]

[I 2026-07-10 16:12:12,205] Trial 287 finished with value: 0.9496770972538097 and parameters: {'weight_class_0': 0.8571403828624341, 'weight_class_1': 9.653875116344516, 'weight_class_2': 9.1172145526489}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,208] Trial 288 finished with value: 0.9495158175147856 and parameters: {'weight_class_0': 0.929555392110799, 'weight_class_1': 9.63476628015181, 'weight_class_2': 9.169388908010891}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,236] Trial 289 finished with value: 0.949545987367897 and parameters: {'weight_class_0': 0.9042918593011371, 'weight_class_1': 9.649074147934867, 'weight_class_2': 9.13687515078031}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,248] Trial 290 finished with value: 0.9495336366192757 and parameters: {'weight_class_0': 0.8771863879753531, 'weight_class_1': 9.736715695973139, 'weight_class_2': 8.291527740342419}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,262] Trial 292 finished with value: 0.9495660131666295 and parameters: {'weight_class_0': 0.8613523462346658, 'weight_class_1': 9.457346452234837, 'weight_class_2': 8.28002539717425}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,268] Trial 291 finished with value: 0.9495440672573103 and parameters: {'weight_class_0': 0.8771378940310246, 'weight_class_1': 9.548710652364935, 'weight_class_2': 8.751518300833895}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,305] Trial 294 finished with value: 0.9497173033769242 and parameters: {'weight_class_0': 0.717603031026905, 'weight_class_1': 9.48371301603667, 'weight_class_2': 8.776870685743956}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,318] Trial 293 finished with value: 0.8883405570483139 and parameters: {'weight_class_0': 7.247948584614344, 'weight_class_1': 8.322785313147316, 'weight_class_2': 8.788290172396767}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,346] Trial 295 finished with value: 0.9483938841786929 and parameters: {'weight_class_0': 0.6743789176104067, 'weight_class_1': 4.117239067013496, 'weight_class_2': 8.784384139947706}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,353] Trial 296 finished with value: 0.9483079414230097 and parameters: {'weight_class_0': 0.7037767450395696, 'weight_class_1': 4.081083172000344, 'weight_class_2': 8.819754099620056}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,377] Trial 297 finished with value: 0.9496106638295917 and parameters: {'weight_class_0': 0.6824795096404604, 'weight_class_1': 9.442133762909066, 'weight_class_2': 8.791384944774123}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,392] Trial 298 finished with value: 0.9484582850434689 and parameters: {'weight_class_0': 0.661244859299004, 'weight_class_1': 4.185056282433693, 'weight_class_2': 8.884469912386244}. Best is trial 191 with value: 0.9497178512629185.

Best trial: 191. Best value: 0.949718:  10%|█████████████▋                                                                                                                      | 311/3000 [00:05<00:49, 54.23it/s]

[I 2026-07-10 16:12:12,423] Trial 300 finished with value: 0.8887563896454762 and parameters: {'weight_class_0': 7.217541938319013, 'weight_class_1': 8.354605103353096, 'weight_class_2': 8.80048286318966}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,427] Trial 299 finished with value: 0.9496402736661765 and parameters: {'weight_class_0': 0.6493604704912634, 'weight_class_1': 9.963429940584373, 'weight_class_2': 8.818813230344624}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,455] Trial 302 finished with value: 0.9495506412493212 and parameters: {'weight_class_0': 0.6572466776550345, 'weight_class_1': 8.301522380018218, 'weight_class_2': 8.87307690343762}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,467] Trial 301 finished with value: 0.9495644449983301 and parameters: {'weight_class_0': 0.6572425911756445, 'weight_class_1': 8.278696823697103, 'weight_class_2': 8.785036993925866}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,494] Trial 303 finished with value: 0.94901580709439 and parameters: {'weight_class_0': 0.45276024136422305, 'weight_class_1': 9.869518352296652, 'weight_class_2': 8.897773668764028}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,510] Trial 304 finished with value: 0.9495701162374094 and parameters: {'weight_class_0': 0.6448513775577238, 'weight_class_1': 9.462529481204324, 'weight_class_2': 8.823708524236004}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,512] Trial 305 finished with value: 0.9489246684003083 and parameters: {'weight_class_0': 0.45028196925144565, 'weight_class_1': 9.87347653374032, 'weight_class_2': 9.330538620114087}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,547] Trial 306 finished with value: 0.9487902914195084 and parameters: {'weight_class_0': 0.4179995856136839, 'weight_class_1': 9.761184015173756, 'weight_class_2': 9.017265513708415}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,559] Trial 307 finished with value: 0.9491565586226235 and parameters: {'weight_class_0': 0.4647337358883893, 'weight_class_1': 9.989426783955249, 'weight_class_2': 8.57641557986345}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,573] Trial 308 finished with value: 0.9490312714532476 and parameters: {'weight_class_0': 0.43834013860866144, 'weight_class_1': 9.447994765274464, 'weight_class_2': 8.580975326803614}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,594] Trial 310 finished with value: 0.9489517359305969 and parameters: {'weight_class_0': 0.4261440965044284, 'weight_class_1': 9.537166781438916, 'weight_class_2': 8.558063825412376}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,616] Trial 309 finished with value: 0.9488817209095131 and parameters: {'weight_class_0': 0.4141638668311326, 'weight_class_1': 9.94756442721533, 'weight_class_2': 8.535390358283173}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,631] Trial 311 finished with value: 0.9487835045652367 and parameters: {'weight_class_0': 0.38863982355195437, 'weight_class_1': 9.448194977513953, 'weight_class_2': 8.519783106657853}. Best is trial 191 with value: 0.9497178512629185.

Best trial: 191. Best value: 0.949718:  11%|██████████████▎                                                                                                                     | 324/3000 [00:06<00:46, 57.31it/s]

[I 2026-07-10 16:12:12,641] Trial 312 finished with value: 0.8981505168514315 and parameters: {'weight_class_0': 6.642838028885508, 'weight_class_1': 9.813368404578132, 'weight_class_2': 8.493349849497765}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,672] Trial 313 finished with value: 0.9465374456537591 and parameters: {'weight_class_0': 0.20598655949868233, 'weight_class_1': 9.523940018363211, 'weight_class_2': 8.581610488389488}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,686] Trial 314 finished with value: 0.9488867445687689 and parameters: {'weight_class_0': 0.4092823805672, 'weight_class_1': 9.73583400247308, 'weight_class_2': 8.495149377836281}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,703] Trial 315 finished with value: 0.9460182556516203 and parameters: {'weight_class_0': 0.19546962016083835, 'weight_class_1': 9.967348309757526, 'weight_class_2': 8.566841423492308}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,711] Trial 316 finished with value: 0.8998999219384068 and parameters: {'weight_class_0': 6.5072162790156955, 'weight_class_1': 9.905303387997511, 'weight_class_2': 8.554140435475789}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,730] Trial 317 finished with value: 0.9484478214597801 and parameters: {'weight_class_0': 0.3307405378025377, 'weight_class_1': 9.414865539450242, 'weight_class_2': 8.523608947605483}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,749] Trial 318 finished with value: 0.9470320347650882 and parameters: {'weight_class_0': 0.23469628263324027, 'weight_class_1': 9.977066904696837, 'weight_class_2': 8.419469167725149}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,762] Trial 319 finished with value: 0.9465367486676625 and parameters: {'weight_class_0': 0.21201415207918994, 'weight_class_1': 9.95317739423371, 'weight_class_2': 8.51413276055966}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,793] Trial 320 finished with value: 0.9455521463927662 and parameters: {'weight_class_0': 0.17888984930580237, 'weight_class_1': 9.38980200805244, 'weight_class_2': 9.11985791530355}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,809] Trial 321 finished with value: 0.9448776904836094 and parameters: {'weight_class_0': 1.5621467015735, 'weight_class_1': 5.855936534869335, 'weight_class_2': 9.118815069960073}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,822] Trial 322 finished with value: 0.946041626486616 and parameters: {'weight_class_0': 0.1803906297897383, 'weight_class_1': 8.514391167584009, 'weight_class_2': 9.081891174856617}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,852] Trial 323 finished with value: 0.9461350334450572 and parameters: {'weight_class_0': 0.1903740209467657, 'weight_class_1': 9.019195722005698, 'weight_class_2': 9.044453504596797}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,867] Trial 324 finished with value: 0.9474645028640295 and parameters: {'weight_class_0': 1.5902306935780914, 'weight_class_1': 9.025899646335263, 'weight_class_2': 9.167155831982216}. Best is trial 191 with value: 0.9497178512629185.

Best trial: 332. Best value: 0.949749:  11%|██████████████▋                                                                                                                     | 335/3000 [00:06<00:47, 55.94it/s]

[I 2026-07-10 16:12:12,885] Trial 325 finished with value: 0.944183705254808 and parameters: {'weight_class_0': 0.14518950724648327, 'weight_class_1': 8.57058490850656, 'weight_class_2': 9.149866936885674}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,916] Trial 326 finished with value: 0.9485782737777079 and parameters: {'weight_class_0': 0.6842636788174568, 'weight_class_1': 8.5496164286312, 'weight_class_2': 3.8578711332657094}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,931] Trial 327 finished with value: 0.9496117350321259 and parameters: {'weight_class_0': 0.706414832361302, 'weight_class_1': 9.060296805576815, 'weight_class_2': 9.113435167520343}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,938] Trial 328 finished with value: 0.9495756305276063 and parameters: {'weight_class_0': 0.6811145098025516, 'weight_class_1': 9.02572828457734, 'weight_class_2': 9.025212748033615}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,970] Trial 329 finished with value: 0.9496147316805638 and parameters: {'weight_class_0': 0.7015043294001639, 'weight_class_1': 9.036118186271437, 'weight_class_2': 9.085583891341809}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,979] Trial 330 finished with value: 0.9495802165987067 and parameters: {'weight_class_0': 0.6668779202649943, 'weight_class_1': 9.000761464534591, 'weight_class_2': 9.051455003894429}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:12,987] Trial 331 finished with value: 0.9496890740248983 and parameters: {'weight_class_0': 0.685820766277679, 'weight_class_1': 9.003694559673288, 'weight_class_2': 7.9056480596255705}. Best is trial 191 with value: 0.9497178512629185.
[I 2026-07-10 16:12:13,019] Trial 332 finished with value: 0.9497485090612261 and parameters: {'weight_class_0': 0.6542929313741969, 'weight_class_1': 9.045954971964015, 'weight_class_2': 7.989226653005288}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,036] Trial 333 finished with value: 0.9496887346040498 and parameters: {'weight_class_0': 0.6795538677972334, 'weight_class_1': 9.038438370464535, 'weight_class_2': 7.847397550738558}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,044] Trial 334 finished with value: 0.9376290161028661 and parameters: {'weight_class_0': 1.066409168984601, 'weight_class_1': 7.961437955063814, 'weight_class_2': 2.394925345389674}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,061] Trial 335 finished with value: 0.9486365508121336 and parameters: {'weight_class_0': 1.06369630517089, 'weight_class_1': 7.9558719090358, 'weight_class_2': 7.9881247334671475}. Best is trial 332 with value: 0.9497485090612261.

Best trial: 332. Best value: 0.949749:  12%|███████████████▎                                                                                                                    | 348/3000 [00:06<00:46, 56.79it/s]

[I 2026-07-10 16:12:13,074] Trial 336 finished with value: 0.949698432645739 and parameters: {'weight_class_0': 0.6607587602890876, 'weight_class_1': 8.043201998767772, 'weight_class_2': 7.956574409340472}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,115] Trial 337 finished with value: 0.949202019804957 and parameters: {'weight_class_0': 0.9763510567899185, 'weight_class_1': 8.020158038822403, 'weight_class_2': 9.31751542308803}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,121] Trial 338 finished with value: 0.9486295244031241 and parameters: {'weight_class_0': 1.06173871225839, 'weight_class_1': 8.022718430317399, 'weight_class_2': 7.965655553052132}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,127] Trial 339 finished with value: 0.9488061027497139 and parameters: {'weight_class_0': 1.0290211122670276, 'weight_class_1': 7.994652016683455, 'weight_class_2': 8.180449913660809}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,138] Trial 340 finished with value: 0.9488270832621399 and parameters: {'weight_class_0': 1.0912714380909794, 'weight_class_1': 8.024941219640093, 'weight_class_2': 9.254545725404123}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,162] Trial 341 finished with value: 0.9494958607314773 and parameters: {'weight_class_0': 0.951026140387656, 'weight_class_1': 9.641389612100177, 'weight_class_2': 9.362324655609527}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,203] Trial 342 finished with value: 0.9492031454122319 and parameters: {'weight_class_0': 1.0486294668066485, 'weight_class_1': 9.3224079630933, 'weight_class_2': 9.400655577195874}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,206] Trial 343 finished with value: 0.9488823278260975 and parameters: {'weight_class_0': 1.0529510764944017, 'weight_class_1': 9.113298943161848, 'weight_class_2': 7.961123757634952}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,222] Trial 344 finished with value: 0.9489003270869697 and parameters: {'weight_class_0': 1.0517647787403377, 'weight_class_1': 9.321836212912746, 'weight_class_2': 7.907627890073575}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,244] Trial 345 finished with value: 0.949509562661239 and parameters: {'weight_class_0': 0.543547978066411, 'weight_class_1': 9.251074996511964, 'weight_class_2': 7.681486954611968}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,259] Trial 347 finished with value: 0.9495993444532749 and parameters: {'weight_class_0': 0.5693740217480695, 'weight_class_1': 9.254048431890377, 'weight_class_2': 7.7453481754996485}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,278] Trial 346 finished with value: 0.9495409558444338 and parameters: {'weight_class_0': 0.5618753093062883, 'weight_class_1': 9.339608416821726, 'weight_class_2': 7.862111209556044}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,303] Trial 348 finished with value: 0.9495004822612906 and parameters: {'weight_class_0': 0.5396281040132351, 'weight_class_1': 9.213098848967029, 'weight_class_2': 7.733325980342673}. Best is trial 332 with value: 0.9497485090612261.

Best trial: 332. Best value: 0.949749:  12%|███████████████▊                                                                                                                    | 359/3000 [00:06<00:48, 54.72it/s]

[I 2026-07-10 16:12:13,317] Trial 350 finished with value: 0.9495200215052408 and parameters: {'weight_class_0': 0.5437426028899833, 'weight_class_1': 9.254302307313521, 'weight_class_2': 7.7361559175345285}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,330] Trial 349 finished with value: 0.9496289068574688 and parameters: {'weight_class_0': 0.6033162418351676, 'weight_class_1': 9.268320959869168, 'weight_class_2': 8.059810487392319}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,359] Trial 351 finished with value: 0.9496054568837105 and parameters: {'weight_class_0': 0.5796116214583983, 'weight_class_1': 9.280700211014533, 'weight_class_2': 7.6957240037095165}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,365] Trial 352 finished with value: 0.9494570632708953 and parameters: {'weight_class_0': 0.5271334022441831, 'weight_class_1': 9.31044020705525, 'weight_class_2': 7.629086579458471}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,374] Trial 353 finished with value: 0.9494721776743794 and parameters: {'weight_class_0': 0.52211121357757, 'weight_class_1': 9.264165286142836, 'weight_class_2': 7.727304055195982}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,401] Trial 354 finished with value: 0.949472241046097 and parameters: {'weight_class_0': 0.5202002389402036, 'weight_class_1': 9.18694834894574, 'weight_class_2': 7.699877970773883}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,452] Trial 356 finished with value: 0.94954437183383 and parameters: {'weight_class_0': 0.5511230258482623, 'weight_class_1': 9.07883559223769, 'weight_class_2': 7.66416598294214}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,453] Trial 357 finished with value: 0.9496692984592504 and parameters: {'weight_class_0': 0.7883212785720769, 'weight_class_1': 9.050033975205606, 'weight_class_2': 8.15059942752152}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,460] Trial 355 finished with value: 0.9496193784376369 and parameters: {'weight_class_0': 0.5731355012487614, 'weight_class_1': 9.099734473877438, 'weight_class_2': 7.880687183272136}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,477] Trial 358 finished with value: 0.9497024450147991 and parameters: {'weight_class_0': 0.7175631638624628, 'weight_class_1': 9.021071523503213, 'weight_class_2': 7.672923029198233}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,495] Trial 359 finished with value: 0.949727682341841 and parameters: {'weight_class_0': 0.7495952822238254, 'weight_class_1': 8.976947627461676, 'weight_class_2': 8.078084703753268}. Best is trial 332 with value: 0.9497485090612261.

Best trial: 332. Best value: 0.949749:  12%|████████████████▎                                                                                                                   | 371/3000 [00:06<00:48, 54.25it/s]

[I 2026-07-10 16:12:13,535] Trial 360 finished with value: 0.9497392419847582 and parameters: {'weight_class_0': 0.7437223782739275, 'weight_class_1': 9.01565508011453, 'weight_class_2': 8.035079643163845}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,547] Trial 361 finished with value: 0.949697839470656 and parameters: {'weight_class_0': 0.7308346437835501, 'weight_class_1': 9.029609935020606, 'weight_class_2': 8.097263092979679}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,549] Trial 362 finished with value: 0.9470050269399589 and parameters: {'weight_class_0': 0.7915086481409175, 'weight_class_1': 3.448292346736028, 'weight_class_2': 8.15284748024789}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,590] Trial 363 finished with value: 0.9496988546439832 and parameters: {'weight_class_0': 0.7775386670344665, 'weight_class_1': 8.982753135952628, 'weight_class_2': 8.091039914941147}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,591] Trial 364 finished with value: 0.9496380199917552 and parameters: {'weight_class_0': 0.7939428927413298, 'weight_class_1': 9.016704809603931, 'weight_class_2': 8.111166261036525}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,612] Trial 365 finished with value: 0.9494631475851284 and parameters: {'weight_class_0': 0.8608025269094277, 'weight_class_1': 8.943917248337774, 'weight_class_2': 8.131221870197834}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,634] Trial 368 finished with value: 0.8791576069816104 and parameters: {'weight_class_0': 8.187610803394339, 'weight_class_1': 8.913121536393675, 'weight_class_2': 8.04723961982565}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,641] Trial 366 finished with value: 0.9479716806465373 and parameters: {'weight_class_0': 1.3598783320216385, 'weight_class_1': 9.028692435000936, 'weight_class_2': 8.099084224082821}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,655] Trial 367 finished with value: 0.9478351129108215 and parameters: {'weight_class_0': 1.3960134880859405, 'weight_class_1': 8.939119698962081, 'weight_class_2': 8.04217931168098}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,688] Trial 369 finished with value: 0.9477827977245593 and parameters: {'weight_class_0': 1.4015455421544676, 'weight_class_1': 8.849961653727355, 'weight_class_2': 8.02171538108745}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,699] Trial 370 finished with value: 0.9495560628923756 and parameters: {'weight_class_0': 0.8302702491717009, 'weight_class_1': 8.90691992272921, 'weight_class_2': 8.011396310438226}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,725] Trial 371 finished with value: 0.9477548744910029 and parameters: {'weight_class_0': 1.3988903348098591, 'weight_class_1': 9.005697312550291, 'weight_class_2': 7.963918296106119}. Best is trial 332 with value: 0.9497485090612261.

Best trial: 332. Best value: 0.949749:  13%|████████████████▊                                                                                                                   | 383/3000 [00:07<00:49, 53.27it/s]

[I 2026-07-10 16:12:13,739] Trial 372 finished with value: 0.9496632252422647 and parameters: {'weight_class_0': 0.7769819339717339, 'weight_class_1': 8.89405276378214, 'weight_class_2': 8.017322119751423}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,769] Trial 373 finished with value: 0.947633502674889 and parameters: {'weight_class_0': 1.4131040226827531, 'weight_class_1': 8.871998914001795, 'weight_class_2': 7.981874142313743}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,787] Trial 375 finished with value: 0.9481155898482495 and parameters: {'weight_class_0': 1.2772590202850507, 'weight_class_1': 8.852271608895368, 'weight_class_2': 7.963838301558153}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,789] Trial 374 finished with value: 0.9493306245623699 and parameters: {'weight_class_0': 0.9092327570911918, 'weight_class_1': 8.928677420163236, 'weight_class_2': 8.0227261071094}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,828] Trial 376 finished with value: 0.9478901244353262 and parameters: {'weight_class_0': 1.3569998225666908, 'weight_class_1': 8.831258787572677, 'weight_class_2': 7.931515792151145}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,841] Trial 377 finished with value: 0.9492933990455698 and parameters: {'weight_class_0': 0.8818531373866199, 'weight_class_1': 8.866332989409802, 'weight_class_2': 7.447495444248979}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,843] Trial 378 finished with value: 0.9493546754982202 and parameters: {'weight_class_0': 0.850356018903246, 'weight_class_1': 8.809569293590103, 'weight_class_2': 7.385318684729293}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,867] Trial 379 finished with value: 0.9488819848281117 and parameters: {'weight_class_0': 0.3628160976046855, 'weight_class_1': 8.777123600162064, 'weight_class_2': 7.4158665425220835}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,886] Trial 380 finished with value: 0.949294386930386 and parameters: {'weight_class_0': 0.873119685888195, 'weight_class_1': 8.707001729439362, 'weight_class_2': 7.376410931762958}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,919] Trial 381 finished with value: 0.9482835652909404 and parameters: {'weight_class_0': 0.8538997883325795, 'weight_class_1': 4.983096289912645, 'weight_class_2': 7.4287082804512385}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,929] Trial 383 finished with value: 0.9488292546159548 and parameters: {'weight_class_0': 0.3836801708111123, 'weight_class_1': 9.542413201104782, 'weight_class_2': 7.911054496566236}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,938] Trial 382 finished with value: 0.9485031978920436 and parameters: {'weight_class_0': 0.32984741661661643, 'weight_class_1': 9.553528810611697, 'weight_class_2': 7.887354014090637}. Best is trial 332 with value: 0.9497485090612261.

Best trial: 332. Best value: 0.949749:  13%|█████████████████▎                                                                                                                  | 393/3000 [00:07<00:50, 51.36it/s]

[I 2026-07-10 16:12:13,951] Trial 384 finished with value: 0.9488818563858726 and parameters: {'weight_class_0': 0.38567904347052523, 'weight_class_1': 9.637821741204169, 'weight_class_2': 7.822205622320571}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,994] Trial 386 finished with value: 0.948807168236661 and parameters: {'weight_class_0': 0.3853578349372873, 'weight_class_1': 9.54712895504001, 'weight_class_2': 8.293683473088988}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:13,998] Trial 385 finished with value: 0.948669088682809 and parameters: {'weight_class_0': 0.35721218635187757, 'weight_class_1': 9.537466870341504, 'weight_class_2': 8.251107874434386}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,017] Trial 387 finished with value: 0.9469658628112322 and parameters: {'weight_class_0': 0.347018241200862, 'weight_class_1': 9.539880069118723, 'weight_class_2': 1.524901247718713}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,030] Trial 388 finished with value: 0.9486440553002556 and parameters: {'weight_class_0': 0.3587840357226447, 'weight_class_1': 9.667432705919952, 'weight_class_2': 8.171249538001714}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,046] Trial 389 finished with value: 0.948675885968809 and parameters: {'weight_class_0': 0.36273600422286, 'weight_class_1': 9.43712527665343, 'weight_class_2': 8.241569515054818}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,092] Trial 390 finished with value: 0.9489458885418093 and parameters: {'weight_class_0': 0.40204850637211065, 'weight_class_1': 9.56116410268352, 'weight_class_2': 7.816096778047814}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,119] Trial 391 finished with value: 0.948722184154536 and parameters: {'weight_class_0': 1.1444613491506233, 'weight_class_1': 9.103415231860831, 'weight_class_2': 8.287938895485803}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,138] Trial 393 finished with value: 0.906953851998333 and parameters: {'weight_class_0': 0.05841382962980024, 'weight_class_1': 9.091042891464332, 'weight_class_2': 8.227556196616755}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,139] Trial 392 finished with value: 0.8863148169464918 and parameters: {'weight_class_0': 0.04890317717119719, 'weight_class_1': 9.183640381254058, 'weight_class_2': 8.25179365827694}. Best is trial 332 with value: 0.9497485090612261.

Best trial: 332. Best value: 0.949749:  13%|█████████████████▋                                                                                                                  | 403/3000 [00:07<00:51, 50.53it/s]

[I 2026-07-10 16:12:14,148] Trial 394 finished with value: 0.9488313070543078 and parameters: {'weight_class_0': 1.122175206608657, 'weight_class_1': 9.127215076356793, 'weight_class_2': 8.2127406368168}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,168] Trial 395 finished with value: 0.6913947748418362 and parameters: {'weight_class_0': 0.015566012822583408, 'weight_class_1': 9.140509819987136, 'weight_class_2': 8.280430231740596}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,197] Trial 396 finished with value: 0.9185391366543317 and parameters: {'weight_class_0': 0.06703798493528845, 'weight_class_1': 9.148783198559956, 'weight_class_2': 8.216389352856739}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,241] Trial 399 finished with value: 0.9488880435806314 and parameters: {'weight_class_0': 1.0553265616118375, 'weight_class_1': 9.075908910990101, 'weight_class_2': 7.7758329227986405}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,251] Trial 397 finished with value: 0.9497194222738168 and parameters: {'weight_class_0': 0.754180343775562, 'weight_class_1': 9.121487502715985, 'weight_class_2': 8.26487740418508}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,262] Trial 398 finished with value: 0.6901563656379185 and parameters: {'weight_class_0': 0.013139894379786687, 'weight_class_1': 9.075203270968023, 'weight_class_2': 5.961729056835015}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,277] Trial 400 finished with value: 0.9488340684630717 and parameters: {'weight_class_0': 1.1219747589127442, 'weight_class_1': 9.104534145487943, 'weight_class_2': 8.222019454101368}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,291] Trial 401 finished with value: 0.9488030373657826 and parameters: {'weight_class_0': 1.1274630721727688, 'weight_class_1': 9.10870371613764, 'weight_class_2': 8.212857570277619}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,296] Trial 402 finished with value: 0.9246544437723166 and parameters: {'weight_class_0': 0.07345605242040243, 'weight_class_1': 9.158872057527352, 'weight_class_2': 8.156917148270141}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,336] Trial 403 finished with value: 0.9495548909062744 and parameters: {'weight_class_0': 0.7836049020583208, 'weight_class_1': 8.58956721835099, 'weight_class_2': 7.643478290303288}. Best is trial 332 with value: 0.9497485090612261.

[I 2026-07-10 16:12:14,342] Trial 404 finished with value: 0.898539875204312 and parameters: {'weight_class_0': 0.7630656025885136, 'weight_class_1': 6.392049787146366, 'weight_class_2': 0.44049781243395714}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,386] Trial 406 finished with value: 0.9493131573225027 and parameters: {'weight_class_0': 0.7442393643815293, 'weight_class_1': 8.558983494730365, 'weight_class_2': 6.145295064831468}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,396] Trial 405 finished with value: 0.8981922775719635 and parameters: {'weight_class_0': 0.787952681369903, 'weight_class_1': 0.32997230680900547, 'weight_class_2': 7.627403057826293}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,429] Trial 407 finished with value: 0.9495536165405989 and parameters: {'weight_class_0': 0.7855121724336973, 'weight_class_1': 8.602214914435965, 'weight_class_2': 7.65517487989941}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,432] Trial 408 finished with value: 0.9496667649476497 and parameters: {'weight_class_0': 0.7336680533396249, 'weight_class_1': 8.620065478312203, 'weight_class_2': 8.043411044284161}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,464] Trial 410 finished with value: 0.9295612306513689 and parameters: {'weight_class_0': 3.437337938478967, 'weight_class_1': 8.58972516870394, 'weight_class_2': 7.848167543983206}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,485] Trial 409 finished with value: 0.9496776762293955 and parameters: {'weight_class_0': 0.7393343969445599, 'weight_class_1': 8.574222567351397, 'weight_class_2': 7.953743755917986}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,502] Trial 411 finished with value: 0.9497123855358757 and parameters: {'weight_class_0': 0.7313223471611068, 'weight_class_1': 8.595695480551713, 'weight_class_2': 7.871273823599305}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,518] Trial 412 finished with value: 0.9497034605582876 and parameters: {'weight_class_0': 0.7337431676972459, 'weight_class_1': 8.578205670669163, 'weight_class_2': 7.907778429651112}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,534] Trial 413 finished with value: 0.9497237531592431 and parameters: {'weight_class_0': 0.7078558318960538, 'weight_class_1': 9.369282558311916, 'weight_class_2': 7.89841442536887}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,536] Trial 414 finished with value: 0.9491119479414271 and parameters: {'weight_class_0': 0.970581259879326, 'weight_class_1': 9.42810682734275, 'weight_class_2': 7.859083928652449}. Best is trial 332 with value: 0.9497485090612261.

Best trial: 332. Best value: 0.949749:  14%|██████████████████▋                                                                                                                 | 424/3000 [00:08<00:54, 47.35it/s]

[I 2026-07-10 16:12:14,600] Trial 415 finished with value: 0.8818804606774314 and parameters: {'weight_class_0': 7.636928842565995, 'weight_class_1': 8.647036647359426, 'weight_class_2': 7.869503711621317}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,623] Trial 416 finished with value: 0.9477424624160221 and parameters: {'weight_class_0': 0.9871497696854679, 'weight_class_1': 8.742433748429399, 'weight_class_2': 4.884640346838956}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,638] Trial 417 finished with value: 0.9485120794381311 and parameters: {'weight_class_0': 0.9778447349781658, 'weight_class_1': 8.679764953974246, 'weight_class_2': 5.764268075374021}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,680] Trial 418 finished with value: 0.9484733040822793 and parameters: {'weight_class_0': 0.9873394378647355, 'weight_class_1': 8.683907266580544, 'weight_class_2': 5.736139262363573}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,690] Trial 419 finished with value: 0.9490737930491694 and parameters: {'weight_class_0': 0.9627441963426924, 'weight_class_1': 8.699886065735969, 'weight_class_2': 7.832367456856829}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,694] Trial 420 finished with value: 0.875759103656678 and parameters: {'weight_class_0': 7.671048475194983, 'weight_class_1': 8.716308758816322, 'weight_class_2': 6.447158804208317}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,707] Trial 421 finished with value: 0.9492173089725879 and parameters: {'weight_class_0': 0.9270666571943708, 'weight_class_1': 8.642118432950927, 'weight_class_2': 7.848836671793975}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,737] Trial 422 finished with value: 0.8931101588768673 and parameters: {'weight_class_0': 4.953888972453243, 'weight_class_1': 8.685702057017444, 'weight_class_2': 4.836882449088225}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,750] Trial 423 finished with value: 0.910547375596113 and parameters: {'weight_class_0': 4.95222344577305, 'weight_class_1': 8.644041065397007, 'weight_class_2': 7.8546722525463}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,785] Trial 425 finished with value: 0.9490292821983762 and parameters: {'weight_class_0': 0.9771571736727048, 'weight_class_1': 8.839397133813234, 'weight_class_2': 7.8041408943042825}. Best is trial 332 with value: 0.9497485090612261.

Best trial: 332. Best value: 0.949749:  14%|███████████████████                                                                                                                 | 434/3000 [00:08<00:50, 50.97it/s]

[I 2026-07-10 16:12:14,795] Trial 424 finished with value: 0.948964758905229 and parameters: {'weight_class_0': 0.9928274924089181, 'weight_class_1': 8.685695239434791, 'weight_class_2': 7.838633780183325}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,796] Trial 426 finished with value: 0.948084937282462 and parameters: {'weight_class_0': 1.2268994011648529, 'weight_class_1': 8.471164011355382, 'weight_class_2': 7.541868131067446}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,856] Trial 427 finished with value: 0.949595223629002 and parameters: {'weight_class_0': 0.5950175038725662, 'weight_class_1': 8.461445612293026, 'weight_class_2': 7.835122229432281}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,869] Trial 428 finished with value: 0.9496451309983861 and parameters: {'weight_class_0': 0.5867604224535004, 'weight_class_1': 9.359428088273992, 'weight_class_2': 7.596708617678466}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,875] Trial 429 finished with value: 0.9483372492598346 and parameters: {'weight_class_0': 1.220448136416086, 'weight_class_1': 9.385141659915977, 'weight_class_2': 7.638973964839192}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,888] Trial 430 finished with value: 0.9482885506098498 and parameters: {'weight_class_0': 1.2366231294837715, 'weight_class_1': 9.384081333589911, 'weight_class_2': 7.620934933068976}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,922] Trial 431 finished with value: 0.9482938139266398 and parameters: {'weight_class_0': 1.2345390509413667, 'weight_class_1': 9.376605429701938, 'weight_class_2': 7.583020747773518}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,925] Trial 432 finished with value: 0.94956682179224 and parameters: {'weight_class_0': 0.576638635256843, 'weight_class_1': 9.358534398153965, 'weight_class_2': 8.032093618654416}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,965] Trial 433 finished with value: 0.8742553918117456 and parameters: {'weight_class_0': 8.827786188168282, 'weight_class_1': 9.380671556968815, 'weight_class_2': 7.562158387585493}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:14,981] Trial 434 finished with value: 0.9496907125787559 and parameters: {'weight_class_0': 0.6072950416131049, 'weight_class_1': 9.359292178754044, 'weight_class_2': 7.596134991472751}. Best is trial 332 with value: 0.9497485090612261.

Best trial: 332. Best value: 0.949749:  15%|███████████████████▌                                                                                                                | 444/3000 [00:08<00:54, 46.72it/s]

[I 2026-07-10 16:12:15,021] Trial 435 finished with value: 0.9496118303080947 and parameters: {'weight_class_0': 0.5873642861353022, 'weight_class_1': 9.29974666068783, 'weight_class_2': 8.045418373429456}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,051] Trial 436 finished with value: 0.9494952917276938 and parameters: {'weight_class_0': 0.5468635077079094, 'weight_class_1': 8.91166091445241, 'weight_class_2': 7.99666233825331}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,061] Trial 438 finished with value: 0.9496158629933165 and parameters: {'weight_class_0': 0.569811420604279, 'weight_class_1': 8.922379690424949, 'weight_class_2': 7.334395889734768}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,071] Trial 437 finished with value: 0.9495531804997116 and parameters: {'weight_class_0': 0.5416929763326701, 'weight_class_1': 9.354173990760085, 'weight_class_2': 7.5210436037320125}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,089] Trial 439 finished with value: 0.9488008534490987 and parameters: {'weight_class_0': 0.5561302064762692, 'weight_class_1': 9.342049686855793, 'weight_class_2': 3.405000304028264}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,119] Trial 440 finished with value: 0.9496961113719053 and parameters: {'weight_class_0': 0.5792888093656461, 'weight_class_1': 9.382142559583732, 'weight_class_2': 7.199569166084874}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,159] Trial 441 finished with value: 0.9494458521519119 and parameters: {'weight_class_0': 0.5090158389277076, 'weight_class_1': 8.958252647986937, 'weight_class_2': 8.0866089666534}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,169] Trial 442 finished with value: 0.9496250926989603 and parameters: {'weight_class_0': 0.5731321061998743, 'weight_class_1': 8.907121311066515, 'weight_class_2': 7.318826927184089}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,174] Trial 443 finished with value: 0.9470303340229367 and parameters: {'weight_class_0': 0.7590853757184868, 'weight_class_1': 8.94766264559848, 'weight_class_2': 3.1331423871108965}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,183] Trial 444 finished with value: 0.9495865019994022 and parameters: {'weight_class_0': 0.7430645904036566, 'weight_class_1': 8.934145075698652, 'weight_class_2': 7.301217814150668}. Best is trial 332 with value: 0.9497485090612261.

[I 2026-07-10 16:12:15,216] Trial 445 finished with value: 0.9496057485430324 and parameters: {'weight_class_0': 0.7198323486852621, 'weight_class_1': 8.910515779651059, 'weight_class_2': 7.218216081638754}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,258] Trial 447 finished with value: 0.9496861230149648 and parameters: {'weight_class_0': 0.7657717508944349, 'weight_class_1': 8.964722503328378, 'weight_class_2': 8.063250828472365}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,268] Trial 448 finished with value: 0.9495504517635146 and parameters: {'weight_class_0': 0.7531883758253926, 'weight_class_1': 8.917845939140907, 'weight_class_2': 7.156027300123066}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,271] Trial 446 finished with value: 0.9496750956271054 and parameters: {'weight_class_0': 0.777577272825564, 'weight_class_1': 8.997179047290306, 'weight_class_2': 8.06098045776237}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,294] Trial 449 finished with value: 0.9496192273790799 and parameters: {'weight_class_0': 0.7984337056282136, 'weight_class_1': 8.878518414484809, 'weight_class_2': 8.089683384879642}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,330] Trial 450 finished with value: 0.9495426738608715 and parameters: {'weight_class_0': 0.8255978701798565, 'weight_class_1': 8.93975687101362, 'weight_class_2': 8.32650020355614}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,367] Trial 451 finished with value: 0.9496745011233795 and parameters: {'weight_class_0': 0.8152061977398453, 'weight_class_1': 9.676868016094335, 'weight_class_2': 8.343337459292854}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,375] Trial 452 finished with value: 0.9494624891623898 and parameters: {'weight_class_0': 0.8487229677991692, 'weight_class_1': 8.453977392173506, 'weight_class_2': 8.361493456511177}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,408] Trial 453 finished with value: 0.948209722030541 and parameters: {'weight_class_0': 0.7907395469343892, 'weight_class_1': 4.407863024131814, 'weight_class_2': 8.361695970137328}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,424] Trial 454 finished with value: 0.9480668242957534 and parameters: {'weight_class_0': 0.2727723535677826, 'weight_class_1': 8.4640510057473, 'weight_class_2': 8.408743323179037}. Best is trial 332 with value: 0.9497485090612261.

Best trial: 332. Best value: 0.949749:  15%|████████████████████▍                                                                                                               | 464/3000 [00:08<00:54, 46.92it/s]

[I 2026-07-10 16:12:15,437] Trial 455 finished with value: 0.9495702764680711 and parameters: {'weight_class_0': 0.8759708112354943, 'weight_class_1': 9.737127963776139, 'weight_class_2': 8.387602239414855}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,460] Trial 456 finished with value: 0.9476432984061359 and parameters: {'weight_class_0': 0.25378459762876854, 'weight_class_1': 9.669972944648622, 'weight_class_2': 7.771243535930567}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,473] Trial 457 finished with value: 0.9475248067211594 and parameters: {'weight_class_0': 0.25410363721058915, 'weight_class_1': 9.77337214506295, 'weight_class_2': 8.362555795783043}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,494] Trial 459 finished with value: 0.9494350443158709 and parameters: {'weight_class_0': 0.3501802026121834, 'weight_class_1': 9.679038432775137, 'weight_class_2': 4.096424060238658}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,497] Trial 458 finished with value: 0.9481843863712195 and parameters: {'weight_class_0': 0.30220596370105957, 'weight_class_1': 9.761356106265715, 'weight_class_2': 8.358796835013427}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,528] Trial 460 finished with value: 0.9464126978763581 and parameters: {'weight_class_0': 0.2009375313828251, 'weight_class_1': 9.683981223549956, 'weight_class_2': 7.833893015554793}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,568] Trial 461 finished with value: 0.9488410562059263 and parameters: {'weight_class_0': 1.1004587605937064, 'weight_class_1': 9.758243867102845, 'weight_class_2': 7.75301981779741}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,568] Trial 462 finished with value: 0.9467520123517268 and parameters: {'weight_class_0': 1.6041450007610687, 'weight_class_1': 9.718338780891163, 'weight_class_2': 7.741724058487324}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,616] Trial 463 finished with value: 0.9361187310722136 and parameters: {'weight_class_0': 2.940286679369319, 'weight_class_1': 9.70375442402682, 'weight_class_2': 7.747048098679276}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,627] Trial 464 finished with value: 0.9487255740528081 and parameters: {'weight_class_0': 1.035365357931963, 'weight_class_1': 9.637848568904326, 'weight_class_2': 6.933825978527209}. Best is trial 332 with value: 0.9497485090612261.

Best trial: 332. Best value: 0.949749:  16%|████████████████████▊                                                                                                               | 474/3000 [00:09<00:52, 48.29it/s]

[I 2026-07-10 16:12:15,652] Trial 465 finished with value: 0.9488425282966294 and parameters: {'weight_class_0': 1.1093268375599437, 'weight_class_1': 9.658073262253385, 'weight_class_2': 8.03925239094789}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,666] Trial 466 finished with value: 0.94541136167699 and parameters: {'weight_class_0': 1.68074548512144, 'weight_class_1': 9.245730744346009, 'weight_class_2': 6.787049774834144}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,692] Trial 467 finished with value: 0.9468565520307108 and parameters: {'weight_class_0': 1.5969070805332257, 'weight_class_1': 9.2262666220855, 'weight_class_2': 8.052820833889278}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,712] Trial 468 finished with value: 0.9489001101972893 and parameters: {'weight_class_0': 1.086217741274103, 'weight_class_1': 9.187007126226206, 'weight_class_2': 7.9609106973870425}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,720] Trial 470 finished with value: 0.9486423684448245 and parameters: {'weight_class_0': 1.0769556242862368, 'weight_class_1': 9.179025626690224, 'weight_class_2': 7.029947655551824}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,724] Trial 469 finished with value: 0.9488801577290449 and parameters: {'weight_class_0': 1.0909991135138895, 'weight_class_1': 9.26984610536108, 'weight_class_2': 8.05037373710394}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,754] Trial 471 finished with value: 0.9489703131207384 and parameters: {'weight_class_0': 1.0311695868215942, 'weight_class_1': 9.195327655127208, 'weight_class_2': 8.05023794836344}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,789] Trial 472 finished with value: 0.9485598591443866 and parameters: {'weight_class_0': 1.1048480059226624, 'weight_class_1': 9.202449693159723, 'weight_class_2': 6.971331760015971}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,818] Trial 473 finished with value: 0.9483639917743653 and parameters: {'weight_class_0': 1.245200223416392, 'weight_class_1': 9.202307483801373, 'weight_class_2': 7.943441361337482}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,835] Trial 474 finished with value: 0.949132128512428 and parameters: {'weight_class_0': 0.9812752469895643, 'weight_class_1': 9.17770274776772, 'weight_class_2': 8.090682070300856}. Best is trial 332 with value: 0.9497485090612261.

[I 2026-07-10 16:12:15,865] Trial 475 finished with value: 0.9481372160771276 and parameters: {'weight_class_0': 1.3052360366699056, 'weight_class_1': 9.177530152861001, 'weight_class_2': 8.0821427002163}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,879] Trial 476 finished with value: 0.9490781378667285 and parameters: {'weight_class_0': 0.9933230805764572, 'weight_class_1': 9.154443872823734, 'weight_class_2': 8.121051685336015}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,895] Trial 477 finished with value: 0.9482252041936222 and parameters: {'weight_class_0': 1.2760928474558513, 'weight_class_1': 9.19250348225289, 'weight_class_2': 7.967973002760794}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,920] Trial 479 finished with value: 0.9492318794349807 and parameters: {'weight_class_0': 0.9111722727590947, 'weight_class_1': 9.451160590192854, 'weight_class_2': 7.601033758995014}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,947] Trial 478 finished with value: 0.9491367002812346 and parameters: {'weight_class_0': 0.936092727334105, 'weight_class_1': 9.460960759721639, 'weight_class_2': 7.497914540147043}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,969] Trial 480 finished with value: 0.9477862740297671 and parameters: {'weight_class_0': 1.3437678315919241, 'weight_class_1': 9.392795610359446, 'weight_class_2': 7.4805382293339}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,985] Trial 481 finished with value: 0.9491987293790277 and parameters: {'weight_class_0': 0.9134756866710282, 'weight_class_1': 9.388813324813327, 'weight_class_2': 7.488516307096892}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:15,998] Trial 482 finished with value: 0.9479930285517261 and parameters: {'weight_class_0': 1.3210015849202725, 'weight_class_1': 9.478492266065743, 'weight_class_2': 7.580778101854473}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:16,002] Trial 483 finished with value: 0.9493915577236063 and parameters: {'weight_class_0': 0.8646699303148792, 'weight_class_1': 9.449394577821858, 'weight_class_2': 7.4645024995437135}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:16,048] Trial 484 finished with value: 0.9497072464823694 and parameters: {'weight_class_0': 0.7013230457249446, 'weight_class_1': 9.471003707252647, 'weight_class_2': 7.537531203537178}. Best is trial 332 with value: 0.9497485090612261.

Best trial: 332. Best value: 0.949749:  16%|█████████████████████▋                                                                                                              | 494/3000 [00:09<00:53, 46.43it/s]

[I 2026-07-10 16:12:16,058] Trial 485 finished with value: 0.9496063561975432 and parameters: {'weight_class_0': 0.7464789162523927, 'weight_class_1': 9.486309235761437, 'weight_class_2': 7.5154970309262445}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:16,071] Trial 486 finished with value: 0.9496639150219593 and parameters: {'weight_class_0': 0.6727641096719801, 'weight_class_1': 9.4954138103009, 'weight_class_2': 7.434979382245396}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:16,109] Trial 487 finished with value: 0.9497060415022793 and parameters: {'weight_class_0': 0.6971249554873833, 'weight_class_1': 9.497730557793888, 'weight_class_2': 7.556428272375661}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:16,141] Trial 488 finished with value: 0.9497072939842454 and parameters: {'weight_class_0': 0.6968143352546293, 'weight_class_1': 8.44416080305668, 'weight_class_2': 7.685939960182151}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:16,145] Trial 489 finished with value: 0.9497152675714106 and parameters: {'weight_class_0': 0.712360539206294, 'weight_class_1': 8.418041989263834, 'weight_class_2': 7.73870176056463}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:16,181] Trial 490 finished with value: 0.9492486061655555 and parameters: {'weight_class_0': 0.4480640483077002, 'weight_class_1': 8.442735740953712, 'weight_class_2': 7.819166959002976}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:16,199] Trial 491 finished with value: 0.9493196117905122 and parameters: {'weight_class_0': 0.4677549728241961, 'weight_class_1': 8.40924758223106, 'weight_class_2': 7.786614074155498}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:16,206] Trial 492 finished with value: 0.9493221431921226 and parameters: {'weight_class_0': 0.45593523885953846, 'weight_class_1': 9.050064994351109, 'weight_class_2': 7.699708645299604}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:16,232] Trial 493 finished with value: 0.9491213423424026 and parameters: {'weight_class_0': 0.41413072609787177, 'weight_class_1': 9.069445213258504, 'weight_class_2': 7.714005039822658}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:16,284] Trial 495 finished with value: 0.9493891505572858 and parameters: {'weight_class_0': 0.4625956672571653, 'weight_class_1': 9.035921381149793, 'weight_class_2': 7.170844847126474}. Best is trial 332 with value: 0.9497485090612261.

Best trial: 503. Best value: 0.949749:  17%|██████████████████████▏                                                                                                             | 505/3000 [00:09<00:51, 48.91it/s]

[I 2026-07-10 16:12:16,287] Trial 494 finished with value: 0.9494315214831618 and parameters: {'weight_class_0': 0.47851118350812705, 'weight_class_1': 9.046262648684648, 'weight_class_2': 7.79103735004854}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:16,297] Trial 496 finished with value: 0.9493884630854614 and parameters: {'weight_class_0': 0.5063370047816397, 'weight_class_1': 9.485506187678318, 'weight_class_2': 7.70884947382992}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:16,323] Trial 498 finished with value: 0.9494180329967336 and parameters: {'weight_class_0': 0.45102293369372726, 'weight_class_1': 8.326781478527831, 'weight_class_2': 7.17186860510567}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:16,327] Trial 497 finished with value: 0.9493115299460135 and parameters: {'weight_class_0': 0.4406819561249817, 'weight_class_1': 9.555335741416375, 'weight_class_2': 7.190496690515805}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:16,355] Trial 499 finished with value: 0.9494445518263683 and parameters: {'weight_class_0': 0.455308413674073, 'weight_class_1': 8.279759065857423, 'weight_class_2': 7.139573672198584}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:16,378] Trial 501 finished with value: 0.949409343258819 and parameters: {'weight_class_0': 0.4455509873349635, 'weight_class_1': 8.191644814171285, 'weight_class_2': 7.144568562596678}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:16,383] Trial 500 finished with value: 0.949334728913053 and parameters: {'weight_class_0': 0.43753163223809244, 'weight_class_1': 8.201904204951681, 'weight_class_2': 7.315266289791408}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:16,402] Trial 502 finished with value: 0.9497216204330144 and parameters: {'weight_class_0': 0.5717224916550959, 'weight_class_1': 8.271576320759639, 'weight_class_2': 7.117591001777344}. Best is trial 332 with value: 0.9497485090612261.
[I 2026-07-10 16:12:16,435] Trial 503 finished with value: 0.9497489719306985 and parameters: {'weight_class_0': 0.6101785849748873, 'weight_class_1': 8.402066558439486, 'weight_class_2': 7.248451039516123}. Best is trial 503 with value: 0.9497489719306985.
[I 2026-07-10 16:12:16,477] Trial 504 finished with value: 0.9497346390568752 and parameters: {'weight_class_0': 0.6541769448082086, 'weight_class_1': 8.332915568173743, 'weight_class_2': 7.350963861230686}. Best is trial 503 with value: 0.9497489719306985.
[I 2026-07-10 16:12:16,483] Trial 505 finished with value: 0.9497242826952442 and parameters: {'weight_class_0': 0.6462883522644538, 'weight_class_1': 8.2353618631703, 'weight_class_2': 7.199075846446658}. Best is trial 503 with value: 0.9497489719306985.

Best trial: 503. Best value: 0.949749:  17%|██████████████████████▋                                                                                                             | 516/3000 [00:09<00:49, 49.76it/s]

[I 2026-07-10 16:12:16,503] Trial 506 finished with value: 0.9497188400034199 and parameters: {'weight_class_0': 0.6877362640697171, 'weight_class_1': 8.304153557571663, 'weight_class_2': 7.289308832710388}. Best is trial 503 with value: 0.9497489719306985.
[I 2026-07-10 16:12:16,529] Trial 507 finished with value: 0.9497379404333687 and parameters: {'weight_class_0': 0.6602582197391613, 'weight_class_1': 8.296311896837214, 'weight_class_2': 7.4107529205571385}. Best is trial 503 with value: 0.9497489719306985.
[I 2026-07-10 16:12:16,541] Trial 508 finished with value: 0.949736889382428 and parameters: {'weight_class_0': 0.6861106272213222, 'weight_class_1': 8.24204735655904, 'weight_class_2': 7.456808197984585}. Best is trial 503 with value: 0.9497489719306985.
[I 2026-07-10 16:12:16,568] Trial 509 finished with value: 0.9497466918441969 and parameters: {'weight_class_0': 0.6586872571550396, 'weight_class_1': 8.47229849636038, 'weight_class_2': 7.358428194330144}. Best is trial 503 with value: 0.9497489719306985.
[I 2026-07-10 16:12:16,578] Trial 511 finished with value: 0.9497240457567666 and parameters: {'weight_class_0': 0.6551706157922632, 'weight_class_1': 8.50168601737337, 'weight_class_2': 7.26406882565935}. Best is trial 503 with value: 0.9497489719306985.
[I 2026-07-10 16:12:16,595] Trial 510 finished with value: 0.9496203759187765 and parameters: {'weight_class_0': 0.6796188555339459, 'weight_class_1': 8.399643743486015, 'weight_class_2': 6.9271113336216175}. Best is trial 503 with value: 0.9497489719306985.
[I 2026-07-10 16:12:16,620] Trial 512 finished with value: 0.9496547023786913 and parameters: {'weight_class_0': 0.6828129279377968, 'weight_class_1': 8.260244245485856, 'weight_class_2': 6.948870093547772}. Best is trial 503 with value: 0.9497489719306985.
[I 2026-07-10 16:12:16,657] Trial 513 finished with value: 0.9465365646691741 and parameters: {'weight_class_0': 0.17444022914465662, 'weight_class_1': 8.203399343201722, 'weight_class_2': 6.891654988978088}. Best is trial 503 with value: 0.9497489719306985.
[I 2026-07-10 16:12:16,669] Trial 514 finished with value: 0.9472584418562832 and parameters: {'weight_class_0': 0.2019173913425537, 'weight_class_1': 8.228442006625775, 'weight_class_2': 6.833145225194937}. Best is trial 503 with value: 0.9497489719306985.
[I 2026-07-10 16:12:16,698] Trial 515 finished with value: 0.944972118237995 and parameters: {'weight_class_0': 0.14132045807844118, 'weight_class_1': 8.246342274650226, 'weight_class_2': 6.918810007683714}. Best is trial 503 with value: 0.9497489719306985.
[I 2026-07-10 16:12:16,705] Trial 516 finished with value: 0.9483630748817776 and parameters: {'weight_class_0': 0.26731601598509136, 'weight_class_1': 8.326523923834824, 'weight_class_2': 6.753767713632836}. Best is trial 503 with value: 0.9497489719306985.

[I 2026-07-10 16:12:16,726] Trial 517 finished with value: 0.9475231070006576 and parameters: {'weight_class_0': 0.21169774765678273, 'weight_class_1': 8.211563467798815, 'weight_class_2': 6.890107563891229}. Best is trial 503 with value: 0.9497489719306985.
[I 2026-07-10 16:12:16,739] Trial 518 finished with value: 0.9474772919822146 and parameters: {'weight_class_0': 0.215630943961738, 'weight_class_1': 8.224275541934075, 'weight_class_2': 7.329033163495244}. Best is trial 503 with value: 0.9497489719306985.
[I 2026-07-10 16:12:16,801] Trial 519 finished with value: 0.947557638425314 and parameters: {'weight_class_0': 0.21531688985159958, 'weight_class_1': 8.391025519032135, 'weight_class_2': 6.725785003599064}. Best is trial 503 with value: 0.9497489719306985.
[I 2026-07-10 16:12:16,817] Trial 521 finished with value: 0.9472187859888042 and parameters: {'weight_class_0': 0.20280382274729658, 'weight_class_1': 8.1253579465234, 'weight_class_2': 7.280574781288253}. Best is trial 503 with value: 0.9497489719306985.
[I 2026-07-10 16:12:16,818] Trial 520 finished with value: 0.9481152734037708 and parameters: {'weight_class_0': 0.2453525432132579, 'weight_class_1': 8.16106527883901, 'weight_class_2': 6.69709609690053}. Best is trial 503 with value: 0.9497489719306985.
[I 2026-07-10 16:12:16,849] Trial 523 finished with value: 0.9466875266509508 and parameters: {'weight_class_0': 0.18271382759377214, 'weight_class_1': 8.18763287868676, 'weight_class_2': 7.2746311611071555}. Best is trial 503 with value: 0.9497489719306985.
[I 2026-07-10 16:12:16,852] Trial 522 finished with value: 0.9477544441044584 and parameters: {'weight_class_0': 0.21994989618811767, 'weight_class_1': 8.179025183545239, 'weight_class_2': 6.579055873333855}. Best is trial 503 with value: 0.9497489719306985.
[I 2026-07-10 16:12:16,874] Trial 524 finished with value: 0.947627146472657 and parameters: {'weight_class_0': 0.21793290135121463, 'weight_class_1': 8.275362708675276, 'weight_class_2': 6.7522906598252765}. Best is trial 503 with value: 0.9497489719306985.
[I 2026-07-10 16:12:16,897] Trial 525 finished with value: 0.9497497037123845 and parameters: {'weight_class_0': 0.6199292630996877, 'weight_class_1': 8.199056765296987, 'weight_class_2': 7.349737191408916}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:16,937] Trial 526 finished with value: 0.9174785818046641 and parameters: {'weight_class_0': 4.120402068385309, 'weight_class_1': 8.455733646362, 'weight_class_2': 7.051547439838256}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:16,937] Trial 527 finished with value: 0.9496828799137774 and parameters: {'weight_class_0': 0.6290213307930409, 'weight_class_1': 8.101272528760319, 'weight_class_2': 6.579935083983049}. Best is trial 525 with value: 0.9497497037123845.

Best trial: 525. Best value: 0.94975:  18%|███████████████████████▊                                                                                                             | 537/3000 [00:10<00:51, 47.83it/s]

[I 2026-07-10 16:12:16,940] Trial 528 finished with value: 0.9497016741224599 and parameters: {'weight_class_0': 0.6067486089454932, 'weight_class_1': 8.067065249738926, 'weight_class_2': 6.530486794192114}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:16,979] Trial 529 finished with value: 0.9496934084107288 and parameters: {'weight_class_0': 0.6147911361611557, 'weight_class_1': 8.069723118739216, 'weight_class_2': 7.13204627116645}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:16,989] Trial 530 finished with value: 0.9497088801738681 and parameters: {'weight_class_0': 0.5866849711010871, 'weight_class_1': 8.084193141891552, 'weight_class_2': 7.247257093680989}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:17,023] Trial 532 finished with value: 0.9496623889299887 and parameters: {'weight_class_0': 0.5815840481245877, 'weight_class_1': 8.460626908865844, 'weight_class_2': 7.371777370770045}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:17,034] Trial 531 finished with value: 0.9497044837449625 and parameters: {'weight_class_0': 0.6225671417555407, 'weight_class_1': 8.443897089786356, 'weight_class_2': 7.143173375068949}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:17,074] Trial 533 finished with value: 0.9497237681733997 and parameters: {'weight_class_0': 0.5995525063741499, 'weight_class_1': 8.466700002750578, 'weight_class_2': 7.344018423513238}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:17,091] Trial 534 finished with value: 0.9497372897566135 and parameters: {'weight_class_0': 0.5841225509117863, 'weight_class_1': 8.50377782302861, 'weight_class_2': 7.153140379312201}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:17,124] Trial 535 finished with value: 0.9497110802784884 and parameters: {'weight_class_0': 0.6089571159559862, 'weight_class_1': 8.45360146442612, 'weight_class_2': 7.15586141172411}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:17,150] Trial 536 finished with value: 0.9496696115708151 and parameters: {'weight_class_0': 0.5649196912296814, 'weight_class_1': 7.985872908098707, 'weight_class_2': 7.0530464063175815}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:17,155] Trial 537 finished with value: 0.9497492193009044 and parameters: {'weight_class_0': 0.6119869062038868, 'weight_class_1': 8.39917271699992, 'weight_class_2': 7.333615001989893}. Best is trial 525 with value: 0.9497497037123845.

[I 2026-07-10 16:12:17,175] Trial 538 finished with value: 0.9494053977334215 and parameters: {'weight_class_0': 0.4395343687052314, 'weight_class_1': 8.41893872641067, 'weight_class_2': 7.116812563924167}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:17,176] Trial 539 finished with value: 0.9496465701978972 and parameters: {'weight_class_0': 0.5639871093124066, 'weight_class_1': 8.4338924085724, 'weight_class_2': 7.376524579927079}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:17,200] Trial 540 finished with value: 0.9495576207655207 and parameters: {'weight_class_0': 0.524474670292197, 'weight_class_1': 8.48672985193342, 'weight_class_2': 7.332903211966499}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:17,234] Trial 541 finished with value: 0.9494952128278363 and parameters: {'weight_class_0': 0.48461861219086294, 'weight_class_1': 8.421329009717121, 'weight_class_2': 7.029939477592806}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:17,254] Trial 542 finished with value: 0.9495380511438419 and parameters: {'weight_class_0': 0.5030156967430714, 'weight_class_1': 8.405952823271399, 'weight_class_2': 7.104548230703367}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:17,276] Trial 543 finished with value: 0.9493280445411522 and parameters: {'weight_class_0': 0.4241101450012352, 'weight_class_1': 8.347151914254272, 'weight_class_2': 7.159053845132615}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:17,295] Trial 544 finished with value: 0.9489506769613912 and parameters: {'weight_class_0': 0.3625219583887356, 'weight_class_1': 8.437875850034668, 'weight_class_2': 7.1002722681467985}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:17,335] Trial 545 finished with value: 0.9492155836676971 and parameters: {'weight_class_0': 0.40603080514742024, 'weight_class_1': 8.44804590897669, 'weight_class_2': 7.0398877035060226}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:17,350] Trial 546 finished with value: 0.899592008149923 and parameters: {'weight_class_0': 5.491886534472556, 'weight_class_1': 8.460569200611125, 'weight_class_2': 7.076866777023392}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:17,391] Trial 547 finished with value: 0.9494078259407983 and parameters: {'weight_class_0': 0.4484463791514359, 'weight_class_1': 8.379974724314229, 'weight_class_2': 7.0298917148091675}. Best is trial 525 with value: 0.9497497037123845.

[I 2026-07-10 16:12:17,415] Trial 548 finished with value: 0.8963453638063522 and parameters: {'weight_class_0': 5.741570802174272, 'weight_class_1': 8.355858001344139, 'weight_class_2': 7.044679155819891}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:17,430] Trial 549 finished with value: 0.949072476036729 and parameters: {'weight_class_0': 0.37348756289598706, 'weight_class_1': 8.393680918607998, 'weight_class_2': 7.015292806900809}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:17,436] Trial 550 finished with value: 0.9489903813509991 and parameters: {'weight_class_0': 0.3646387429781839, 'weight_class_1': 8.411511441554543, 'weight_class_2': 7.0390952285607575}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:17,448] Trial 551 finished with value: 0.9494167117049367 and parameters: {'weight_class_0': 0.4370393149486471, 'weight_class_1': 8.288674596006729, 'weight_class_2': 7.06289808466837}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:17,486] Trial 553 finished with value: 0.9487764634094352 and parameters: {'weight_class_0': 0.33607293898233853, 'weight_class_1': 7.905036371309343, 'weight_class_2': 7.316628241040916}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:17,494] Trial 552 finished with value: 0.9492853998407037 and parameters: {'weight_class_0': 0.42709946535679233, 'weight_class_1': 7.952995127737395, 'weight_class_2': 7.298524731235948}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:17,540] Trial 554 finished with value: 0.6577742025974183 and parameters: {'weight_class_0': 0.005075900512045983, 'weight_class_1': 8.258794614753194, 'weight_class_2': 7.375454668231073}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:17,582] Trial 556 finished with value: 0.9489206767040734 and parameters: {'weight_class_0': 0.92286957680897, 'weight_class_1': 7.915981511141246, 'weight_class_2': 7.280744368731685}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:17,587] Trial 555 finished with value: 0.9490434859180978 and parameters: {'weight_class_0': 0.9030870654628822, 'weight_class_1': 8.069974943902583, 'weight_class_2': 7.311176054583444}. Best is trial 525 with value: 0.9497497037123845.

Best trial: 525. Best value: 0.94975:  19%|█████████████████████████                                                                                                            | 566/3000 [00:11<00:53, 45.40it/s]

[I 2026-07-10 16:12:17,604] Trial 557 finished with value: 0.9490238216295165 and parameters: {'weight_class_0': 0.8991634029681899, 'weight_class_1': 7.9566053722427075, 'weight_class_2': 7.342160837046826}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:17,623] Trial 558 finished with value: 0.9489974687567667 and parameters: {'weight_class_0': 0.9083141044460266, 'weight_class_1': 7.927365111134514, 'weight_class_2': 7.3304543117758225}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:17,658] Trial 559 finished with value: 0.8654686585340712 and parameters: {'weight_class_0': 9.463107814915274, 'weight_class_1': 7.929794011957431, 'weight_class_2': 7.240187931829653}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:17,678] Trial 561 finished with value: 0.9488237317390512 and parameters: {'weight_class_0': 0.9633079896985117, 'weight_class_1': 7.968710198614199, 'weight_class_2': 7.350701265099614}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:17,686] Trial 560 finished with value: 0.9489165671261882 and parameters: {'weight_class_0': 0.9312409908708856, 'weight_class_1': 7.914106814419226, 'weight_class_2': 7.340384458900089}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:17,716] Trial 562 finished with value: 0.949037715730364 and parameters: {'weight_class_0': 0.9096424783186782, 'weight_class_1': 8.180183962447344, 'weight_class_2': 7.311764425003461}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:17,719] Trial 563 finished with value: 0.9489643456809347 and parameters: {'weight_class_0': 0.9265571677154939, 'weight_class_1': 8.10231120093781, 'weight_class_2': 7.320786289117064}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:17,744] Trial 564 finished with value: 0.9489282457998689 and parameters: {'weight_class_0': 0.9392294574069726, 'weight_class_1': 8.125766375641215, 'weight_class_2': 7.303277477455758}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:17,760] Trial 565 finished with value: 0.9490019265912215 and parameters: {'weight_class_0': 0.9185689475313885, 'weight_class_1': 8.08748459438706, 'weight_class_2': 7.307624897786761}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:17,796] Trial 566 finished with value: 0.9488859867678392 and parameters: {'weight_class_0': 0.9514236619318378, 'weight_class_1': 8.075537008758163, 'weight_class_2': 7.2882798356740945}. Best is trial 525 with value: 0.9497497037123845.

[I 2026-07-10 16:12:17,818] Trial 567 finished with value: 0.9490984775993988 and parameters: {'weight_class_0': 0.9121393095889492, 'weight_class_1': 8.60935702443532, 'weight_class_2': 7.383028895060765}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:17,850] Trial 568 finished with value: 0.9488778424357672 and parameters: {'weight_class_0': 0.9082211425174808, 'weight_class_1': 8.136546730570506, 'weight_class_2': 6.794949669503946}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:17,862] Trial 570 finished with value: 0.9488320844050131 and parameters: {'weight_class_0': 0.9761336129190115, 'weight_class_1': 8.626516657591177, 'weight_class_2': 6.857414563260437}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:17,870] Trial 569 finished with value: 0.9488849800600718 and parameters: {'weight_class_0': 0.9226674717770352, 'weight_class_1': 8.598795570577058, 'weight_class_2': 6.846282442591475}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:17,907] Trial 571 finished with value: 0.9496049386428366 and parameters: {'weight_class_0': 0.6859347940822774, 'weight_class_1': 8.575570750026893, 'weight_class_2': 6.832123694308387}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:17,921] Trial 572 finished with value: 0.9496776044664551 and parameters: {'weight_class_0': 0.6623378089970985, 'weight_class_1': 8.591706208934212, 'weight_class_2': 6.931183664873756}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:17,936] Trial 573 finished with value: 0.9496725824032067 and parameters: {'weight_class_0': 0.6486282475963153, 'weight_class_1': 8.620855142741679, 'weight_class_2': 6.883444755218923}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:17,995] Trial 574 finished with value: 0.9496864329755406 and parameters: {'weight_class_0': 0.6447841613518228, 'weight_class_1': 8.58376839526351, 'weight_class_2': 6.821180730782915}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:17,998] Trial 575 finished with value: 0.9496726276305244 and parameters: {'weight_class_0': 0.6488840464602722, 'weight_class_1': 8.524436432141199, 'weight_class_2': 6.797894924706884}. Best is trial 525 with value: 0.9497497037123845.

[I 2026-07-10 16:12:18,042] Trial 576 finished with value: 0.9496554289611691 and parameters: {'weight_class_0': 0.6624728526983413, 'weight_class_1': 8.642233695684869, 'weight_class_2': 6.790397859308861}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:18,052] Trial 577 finished with value: 0.949676501968736 and parameters: {'weight_class_0': 0.653993717520191, 'weight_class_1': 8.633161184873103, 'weight_class_2': 6.851165780139556}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:18,074] Trial 578 finished with value: 0.949727526611091 and parameters: {'weight_class_0': 0.6597351643247353, 'weight_class_1': 8.642391126180215, 'weight_class_2': 7.550643634888196}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:18,090] Trial 580 finished with value: 0.9496950191080349 and parameters: {'weight_class_0': 0.6874880894514646, 'weight_class_1': 8.656240975804797, 'weight_class_2': 7.537597598747453}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:18,119] Trial 579 finished with value: 0.9495907196005683 and parameters: {'weight_class_0': 0.6691719444866202, 'weight_class_1': 8.612836208291279, 'weight_class_2': 6.318123493248247}. Best is trial 525 with value: 0.9497497037123845.
[I 2026-07-10 16:12:18,139] Trial 581 finished with value: 0.9497504258770016 and parameters: {'weight_class_0': 0.6222948632091037, 'weight_class_1': 8.554884395865669, 'weight_class_2': 7.543110253551251}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:18,156] Trial 582 finished with value: 0.9497415583600599 and parameters: {'weight_class_0': 0.6367979208563619, 'weight_class_1': 8.295568312876858, 'weight_class_2': 7.521228246602963}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:18,183] Trial 583 finished with value: 0.9497413351481216 and parameters: {'weight_class_0': 0.6244504930084455, 'weight_class_1': 8.273071798110154, 'weight_class_2': 7.505456780520842}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:18,203] Trial 584 finished with value: 0.9497463225185775 and parameters: {'weight_class_0': 0.6373018208141212, 'weight_class_1': 8.27432013103859, 'weight_class_2': 7.506453664506053}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:18,209] Trial 585 finished with value: 0.9483599047587403 and parameters: {'weight_class_0': 1.176225935023151, 'weight_class_1': 8.722209934092772, 'weight_class_2': 7.495292520238027}. Best is trial 581 with value: 0.9497504258770016.

[I 2026-07-10 16:12:18,238] Trial 586 finished with value: 0.9487872642905453 and parameters: {'weight_class_0': 0.34103941865779375, 'weight_class_1': 8.324637438566896, 'weight_class_2': 7.50789918867459}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:18,267] Trial 588 finished with value: 0.9485140055683693 and parameters: {'weight_class_0': 0.2989740137716327, 'weight_class_1': 8.268709224919023, 'weight_class_2': 7.530327134391187}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:18,276] Trial 587 finished with value: 0.9486825355451206 and parameters: {'weight_class_0': 0.32362280058200704, 'weight_class_1': 8.251752263381082, 'weight_class_2': 7.44994739935795}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:18,329] Trial 590 finished with value: 0.9485166055409056 and parameters: {'weight_class_0': 0.29842432938540675, 'weight_class_1': 8.281177802975678, 'weight_class_2': 7.491217947258874}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:18,344] Trial 589 finished with value: 0.9488329681964895 and parameters: {'weight_class_0': 0.35388396685498946, 'weight_class_1': 8.271841407977787, 'weight_class_2': 7.5311696080560795}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:18,360] Trial 591 finished with value: 0.9485589099030495 and parameters: {'weight_class_0': 0.3032949093846076, 'weight_class_1': 8.297993553796946, 'weight_class_2': 7.49830521466789}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:18,370] Trial 592 finished with value: 0.9453855242124968 and parameters: {'weight_class_0': 0.3186863384118678, 'weight_class_1': 1.3216560142807348, 'weight_class_2': 7.518613093971495}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:18,397] Trial 593 finished with value: 0.9480123231759089 and parameters: {'weight_class_0': 0.24725265140142572, 'weight_class_1': 8.230687148705927, 'weight_class_2': 7.5189356992162715}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:18,429] Trial 595 finished with value: 0.9485402951721981 and parameters: {'weight_class_0': 0.3005146437620802, 'weight_class_1': 8.255710624296453, 'weight_class_2': 7.510438283926083}. Best is trial 581 with value: 0.9497504258770016.

Best trial: 581. Best value: 0.94975:  20%|██████████████████████████▊                                                                                                          | 604/3000 [00:11<00:55, 43.48it/s]

[I 2026-07-10 16:12:18,452] Trial 596 finished with value: 0.79475038947922 and parameters: {'weight_class_0': 0.02590197600785671, 'weight_class_1': 8.243050755543976, 'weight_class_2': 7.477342621694264}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:18,457] Trial 594 finished with value: 0.9480161341424028 and parameters: {'weight_class_0': 0.24661334460804007, 'weight_class_1': 8.24462377548901, 'weight_class_2': 7.4961791820436785}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:18,500] Trial 597 finished with value: 0.9482745665379609 and parameters: {'weight_class_0': 0.2759107960129051, 'weight_class_1': 8.320027869740118, 'weight_class_2': 7.486800387198512}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:18,504] Trial 598 finished with value: 0.7973148604060531 and parameters: {'weight_class_0': 0.026411153178022007, 'weight_class_1': 8.233963081966126, 'weight_class_2': 7.594174956660654}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:18,550] Trial 599 finished with value: 0.9448449108589675 and parameters: {'weight_class_0': 0.10780075257658961, 'weight_class_1': 0.9763453862051419, 'weight_class_2': 7.487476610325354}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:18,566] Trial 601 finished with value: 0.9457336231894127 and parameters: {'weight_class_0': 0.1583551834409243, 'weight_class_1': 8.234079357035956, 'weight_class_2': 7.523062025346626}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:18,574] Trial 600 finished with value: 0.9403919187624062 and parameters: {'weight_class_0': 0.10207751108637009, 'weight_class_1': 8.243419425330544, 'weight_class_2': 7.4770413880631805}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:18,604] Trial 602 finished with value: 0.9441119082157571 and parameters: {'weight_class_0': 0.13764065984803464, 'weight_class_1': 8.77363012215901, 'weight_class_2': 7.533347072121057}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:18,611] Trial 603 finished with value: 0.9454839815209294 and parameters: {'weight_class_0': 0.15876255600079547, 'weight_class_1': 8.752876112490833, 'weight_class_2': 7.168636830012787}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:18,622] Trial 604 finished with value: 0.6591221730803155 and parameters: {'weight_class_0': 0.007151829086306849, 'weight_class_1': 8.716546534056851, 'weight_class_2': 7.443348221047037}. Best is trial 581 with value: 0.9497504258770016.

Best trial: 581. Best value: 0.94975:  20%|███████████████████████████▎                                                                                                         | 615/3000 [00:12<00:50, 47.26it/s]

[I 2026-07-10 16:12:18,650] Trial 605 finished with value: 0.6576092757721065 and parameters: {'weight_class_0': 0.0017892683287977773, 'weight_class_1': 8.76163914943482, 'weight_class_2': 7.091894335894061}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:18,661] Trial 606 finished with value: 0.9484102513122871 and parameters: {'weight_class_0': 1.1294875994484685, 'weight_class_1': 8.751971289805143, 'weight_class_2': 7.134577196907685}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:18,683] Trial 607 finished with value: 0.8568216068002542 and parameters: {'weight_class_0': 6.744046611007737, 'weight_class_1': 2.1842894655558016, 'weight_class_2': 7.143697063562374}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:18,706] Trial 608 finished with value: 0.9482171233360644 and parameters: {'weight_class_0': 1.1986401932972905, 'weight_class_1': 8.701644203075874, 'weight_class_2': 7.241749710489843}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:18,748] Trial 609 finished with value: 0.9494774515256944 and parameters: {'weight_class_0': 0.4967783820375583, 'weight_class_1': 8.786597028412823, 'weight_class_2': 7.150436207556226}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:18,778] Trial 612 finished with value: 0.9495812618746845 and parameters: {'weight_class_0': 0.5191744512525664, 'weight_class_1': 8.70060177187833, 'weight_class_2': 7.151620345369864}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:18,794] Trial 610 finished with value: 0.9482737425304285 and parameters: {'weight_class_0': 1.1756657089004425, 'weight_class_1': 8.753322077993191, 'weight_class_2': 7.244310346115621}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:18,803] Trial 611 finished with value: 0.9483460491927916 and parameters: {'weight_class_0': 1.1472871408236642, 'weight_class_1': 8.736329766463124, 'weight_class_2': 7.192811362835485}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:18,837] Trial 613 finished with value: 0.9484244731764088 and parameters: {'weight_class_0': 1.1101992271973866, 'weight_class_1': 8.516706812704786, 'weight_class_2': 7.188455714382144}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:18,852] Trial 614 finished with value: 0.9481201859809172 and parameters: {'weight_class_0': 1.1840858549649107, 'weight_class_1': 8.514068383848675, 'weight_class_2': 7.072912544109762}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:18,873] Trial 615 finished with value: 0.9496655843237068 and parameters: {'weight_class_0': 0.5539543415656689, 'weight_class_1': 8.495407432545084, 'weight_class_2': 7.170267259455589}. Best is trial 581 with value: 0.9497504258770016.

Best trial: 581. Best value: 0.94975:  21%|███████████████████████████▋                                                                                                         | 625/3000 [00:12<00:53, 44.44it/s]

[I 2026-07-10 16:12:18,915] Trial 616 finished with value: 0.9496068865689494 and parameters: {'weight_class_0': 0.5319906954293361, 'weight_class_1': 8.561751151576845, 'weight_class_2': 7.182209321456855}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:18,922] Trial 617 finished with value: 0.9497135202052106 and parameters: {'weight_class_0': 0.5803427077658799, 'weight_class_1': 8.498612228908602, 'weight_class_2': 7.221476426815862}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:18,942] Trial 618 finished with value: 0.949516708779563 and parameters: {'weight_class_0': 0.5069918364984292, 'weight_class_1': 7.809015478264173, 'weight_class_2': 7.1871718304414465}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:18,954] Trial 619 finished with value: 0.9494650661127397 and parameters: {'weight_class_0': 0.49012138344938116, 'weight_class_1': 7.8056111809695, 'weight_class_2': 7.252443297488852}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:18,983] Trial 620 finished with value: 0.9496188237231152 and parameters: {'weight_class_0': 0.5125177267304704, 'weight_class_1': 7.789377240202993, 'weight_class_2': 6.994697610967743}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:19,011] Trial 621 finished with value: 0.9494886803445791 and parameters: {'weight_class_0': 0.506409499797933, 'weight_class_1': 7.8634453005642095, 'weight_class_2': 7.252105646550872}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:19,048] Trial 623 finished with value: 0.9494988287009901 and parameters: {'weight_class_0': 0.7683926586749967, 'weight_class_1': 7.799699976349317, 'weight_class_2': 7.654001647940176}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:19,049] Trial 622 finished with value: 0.9458995695169566 and parameters: {'weight_class_0': 0.8133852396568819, 'weight_class_1': 3.097933177893937, 'weight_class_2': 7.671187849872599}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:19,073] Trial 624 finished with value: 0.9494252339464121 and parameters: {'weight_class_0': 0.8036530458025725, 'weight_class_1': 7.964684409442337, 'weight_class_2': 7.7054108344109675}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:19,099] Trial 625 finished with value: 0.949511082035193 and parameters: {'weight_class_0': 0.7792121921271947, 'weight_class_1': 8.040038802195928, 'weight_class_2': 7.67314457733461}. Best is trial 581 with value: 0.9497504258770016.

[I 2026-07-10 16:12:19,103] Trial 626 finished with value: 0.9491578356402663 and parameters: {'weight_class_0': 0.7965644233071616, 'weight_class_1': 7.744975036939771, 'weight_class_2': 6.56701812303752}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:19,133] Trial 627 finished with value: 0.9493659965323152 and parameters: {'weight_class_0': 0.805685788369614, 'weight_class_1': 7.812597498627602, 'weight_class_2': 7.637225560200279}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:19,138] Trial 628 finished with value: 0.9490738574411397 and parameters: {'weight_class_0': 0.8266100799027984, 'weight_class_1': 7.821462951137224, 'weight_class_2': 6.654713998299698}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:19,171] Trial 629 finished with value: 0.949273865370989 and parameters: {'weight_class_0': 0.8564400746246433, 'weight_class_1': 7.972090889832448, 'weight_class_2': 7.620716967400767}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:19,191] Trial 630 finished with value: 0.9493437681898365 and parameters: {'weight_class_0': 0.8391711138554725, 'weight_class_1': 8.077779440143459, 'weight_class_2': 7.678403864301412}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:19,193] Trial 631 finished with value: 0.9494943329817284 and parameters: {'weight_class_0': 0.7938853082270949, 'weight_class_1': 7.988926991191395, 'weight_class_2': 7.688179274278647}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:19,264] Trial 632 finished with value: 0.9493482050580379 and parameters: {'weight_class_0': 0.8374498394600273, 'weight_class_1': 8.098864400033513, 'weight_class_2': 7.660975548375442}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:19,280] Trial 633 finished with value: 0.9491692365660125 and parameters: {'weight_class_0': 0.7965551041356139, 'weight_class_1': 8.125751197140572, 'weight_class_2': 6.485395171455044}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:19,281] Trial 634 finished with value: 0.9492046263101966 and parameters: {'weight_class_0': 0.7978372777725664, 'weight_class_1': 8.045713307534225, 'weight_class_2': 6.614687399065572}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:19,314] Trial 636 finished with value: 0.9494654610768056 and parameters: {'weight_class_0': 0.7826294091918498, 'weight_class_1': 8.08698227546296, 'weight_class_2': 7.387667404994609}. Best is trial 581 with value: 0.9497504258770016.

Best trial: 581. Best value: 0.94975:  21%|████████████████████████████▌                                                                                                        | 644/3000 [00:12<00:51, 45.92it/s]

[I 2026-07-10 16:12:19,328] Trial 635 finished with value: 0.9491488241529455 and parameters: {'weight_class_0': 0.8087423427933824, 'weight_class_1': 8.10579369689319, 'weight_class_2': 6.492523179775918}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:19,341] Trial 637 finished with value: 0.9495103680277457 and parameters: {'weight_class_0': 0.7838333636678416, 'weight_class_1': 8.432196604089214, 'weight_class_2': 7.390071568875918}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:19,383] Trial 638 finished with value: 0.9494455656710526 and parameters: {'weight_class_0': 0.463057733093918, 'weight_class_1': 8.078492901839493, 'weight_class_2': 7.366610029112733}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:19,400] Trial 640 finished with value: 0.9492477536543023 and parameters: {'weight_class_0': 0.4182842542845809, 'weight_class_1': 8.40894956050496, 'weight_class_2': 7.395511225055914}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:19,412] Trial 641 finished with value: 0.9493743456698791 and parameters: {'weight_class_0': 0.4487440725588777, 'weight_class_1': 8.448213420652367, 'weight_class_2': 7.3823668215938945}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:19,426] Trial 639 finished with value: 0.9494209827190497 and parameters: {'weight_class_0': 0.42769894922601825, 'weight_class_1': 8.122519889627712, 'weight_class_2': 6.984431237781847}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:19,455] Trial 642 finished with value: 0.9493948063377101 and parameters: {'weight_class_0': 0.4598752503622752, 'weight_class_1': 8.418196959586215, 'weight_class_2': 6.945252202402286}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:19,467] Trial 643 finished with value: 0.9494298809221103 and parameters: {'weight_class_0': 0.47343994398489686, 'weight_class_1': 8.509731322642681, 'weight_class_2': 7.39048302337898}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:19,537] Trial 646 finished with value: 0.9495066866395719 and parameters: {'weight_class_0': 0.4934166119046187, 'weight_class_1': 8.4568938027072, 'weight_class_2': 6.982577760801407}. Best is trial 581 with value: 0.9497504258770016.

[I 2026-07-10 16:12:19,540] Trial 645 finished with value: 0.9493850426782044 and parameters: {'weight_class_0': 0.4480793459327516, 'weight_class_1': 8.438759759466048, 'weight_class_2': 6.95399456294335}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:19,543] Trial 644 finished with value: 0.9496029912644844 and parameters: {'weight_class_0': 0.5352777539293159, 'weight_class_1': 8.42621048527781, 'weight_class_2': 7.378971097959274}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:19,557] Trial 647 finished with value: 0.9493726382367056 and parameters: {'weight_class_0': 0.4326045701357051, 'weight_class_1': 8.43640745573885, 'weight_class_2': 6.952736963970017}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:19,593] Trial 648 finished with value: 0.9493980666991532 and parameters: {'weight_class_0': 0.43808342216946927, 'weight_class_1': 8.43971050366263, 'weight_class_2': 6.971397464975204}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:19,620] Trial 650 finished with value: 0.9484634336537984 and parameters: {'weight_class_0': 1.064276145241573, 'weight_class_1': 8.374416089513383, 'weight_class_2': 6.860659512692908}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:19,624] Trial 649 finished with value: 0.9494103564249524 and parameters: {'weight_class_0': 0.4407961583452168, 'weight_class_1': 8.419759571115023, 'weight_class_2': 6.986566392332076}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:19,661] Trial 651 finished with value: 0.9487313466178969 and parameters: {'weight_class_0': 1.006720340427008, 'weight_class_1': 8.486063735308651, 'weight_class_2': 6.92267892109945}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:19,664] Trial 652 finished with value: 0.9485920791463309 and parameters: {'weight_class_0': 1.0456498946072306, 'weight_class_1': 8.525249437011999, 'weight_class_2': 6.950814562853672}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:19,683] Trial 654 finished with value: 0.9486378418005389 and parameters: {'weight_class_0': 1.0341473288302307, 'weight_class_1': 8.339698772978126, 'weight_class_2': 6.995761353176699}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:19,705] Trial 653 finished with value: 0.9484933457049755 and parameters: {'weight_class_0': 1.0517863489780117, 'weight_class_1': 8.3454770316913, 'weight_class_2': 6.894671208943006}. Best is trial 581 with value: 0.9497504258770016.

Best trial: 581. Best value: 0.94975:  22%|█████████████████████████████▍                                                                                                       | 664/3000 [00:13<00:50, 46.49it/s]

[I 2026-07-10 16:12:19,724] Trial 655 finished with value: 0.9485738816131359 and parameters: {'weight_class_0': 1.087256158584795, 'weight_class_1': 8.342627776675476, 'weight_class_2': 7.433690304057245}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:19,741] Trial 656 finished with value: 0.9489592586499614 and parameters: {'weight_class_0': 0.9774695759920274, 'weight_class_1': 8.709164486390018, 'weight_class_2': 7.699660874588769}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:19,753] Trial 657 finished with value: 0.9488725132337964 and parameters: {'weight_class_0': 1.0537325213370172, 'weight_class_1': 8.749391455732015, 'weight_class_2': 7.728054351338228}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:19,799] Trial 659 finished with value: 0.9371506774750498 and parameters: {'weight_class_0': 1.1079934515290524, 'weight_class_1': 8.812423546098552, 'weight_class_2': 2.414371725954462}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:19,826] Trial 658 finished with value: 0.9488547309654011 and parameters: {'weight_class_0': 1.0362981617513054, 'weight_class_1': 8.650591666538443, 'weight_class_2': 7.704476331462275}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:19,831] Trial 660 finished with value: 0.9488907944548705 and parameters: {'weight_class_0': 1.0220679657041676, 'weight_class_1': 8.81791647197613, 'weight_class_2': 7.66431096450174}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:19,860] Trial 661 finished with value: 0.9267496356701966 and parameters: {'weight_class_0': 1.3898751330788015, 'weight_class_1': 8.735782992244513, 'weight_class_2': 2.2308305848856596}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:19,902] Trial 662 finished with value: 0.9477851347987496 and parameters: {'weight_class_0': 1.3560914857147266, 'weight_class_1': 8.82347369095804, 'weight_class_2': 7.7081908681353415}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:19,934] Trial 663 finished with value: 0.949744316679606 and parameters: {'weight_class_0': 0.6934369163134134, 'weight_class_1': 8.780396087940845, 'weight_class_2': 7.760570074001794}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:19,935] Trial 664 finished with value: 0.9496755459138334 and parameters: {'weight_class_0': 0.6126319479828607, 'weight_class_1': 8.783878699482935, 'weight_class_2': 7.664330095478234}. Best is trial 581 with value: 0.9497504258770016.

Best trial: 671. Best value: 0.949751:  22%|█████████████████████████████▋                                                                                                      | 674/3000 [00:13<00:50, 45.76it/s]

[I 2026-07-10 16:12:19,958] Trial 665 finished with value: 0.9497034372146792 and parameters: {'weight_class_0': 0.6761322810316227, 'weight_class_1': 8.81029163730575, 'weight_class_2': 7.298591962918342}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:19,975] Trial 666 finished with value: 0.9471086200354853 and parameters: {'weight_class_0': 1.4313892886185555, 'weight_class_1': 8.82113608503384, 'weight_class_2': 7.315555613964133}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:19,995] Trial 667 finished with value: 0.9496805995806569 and parameters: {'weight_class_0': 0.6293617219584382, 'weight_class_1': 8.759209825972382, 'weight_class_2': 7.325325629692588}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:20,017] Trial 669 finished with value: 0.9497371365470406 and parameters: {'weight_class_0': 0.6426116207843725, 'weight_class_1': 8.17910042068712, 'weight_class_2': 7.2534016030467106}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:20,033] Trial 668 finished with value: 0.9496935829977416 and parameters: {'weight_class_0': 0.6393208662222144, 'weight_class_1': 8.754998625401115, 'weight_class_2': 7.344814488122115}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:20,068] Trial 670 finished with value: 0.9497133444333773 and parameters: {'weight_class_0': 0.6407492007015153, 'weight_class_1': 8.168629649067398, 'weight_class_2': 7.314022775059553}. Best is trial 581 with value: 0.9497504258770016.
[I 2026-07-10 16:12:20,086] Trial 671 finished with value: 0.9497507654006467 and parameters: {'weight_class_0': 0.6199280342336284, 'weight_class_1': 8.229875623719176, 'weight_class_2': 7.35535035378634}. Best is trial 671 with value: 0.9497507654006467.
[I 2026-07-10 16:12:20,107] Trial 672 finished with value: 0.949738766881957 and parameters: {'weight_class_0': 0.6538436013092764, 'weight_class_1': 8.205502652103945, 'weight_class_2': 7.322009941031219}. Best is trial 671 with value: 0.9497507654006467.
[I 2026-07-10 16:12:20,141] Trial 674 finished with value: 0.9497055882498758 and parameters: {'weight_class_0': 0.6719426649983059, 'weight_class_1': 8.180124430611881, 'weight_class_2': 7.320714646743253}. Best is trial 671 with value: 0.9497507654006467.
[I 2026-07-10 16:12:20,159] Trial 673 finished with value: 0.9497136022353114 and parameters: {'weight_class_0': 0.6403927955533077, 'weight_class_1': 8.236140670979456, 'weight_class_2': 7.354961292579319}. Best is trial 671 with value: 0.9497507654006467.

[I 2026-07-10 16:12:20,183] Trial 676 finished with value: 0.9497452822695264 and parameters: {'weight_class_0': 0.6431377336687535, 'weight_class_1': 8.216623996258987, 'weight_class_2': 7.841851975049113}. Best is trial 671 with value: 0.9497507654006467.
[I 2026-07-10 16:12:20,188] Trial 675 finished with value: 0.9497186197779026 and parameters: {'weight_class_0': 0.6348188010352519, 'weight_class_1': 8.222517148364387, 'weight_class_2': 7.384087125060805}. Best is trial 671 with value: 0.9497507654006467.
[I 2026-07-10 16:12:20,215] Trial 677 finished with value: 0.9482879499257583 and parameters: {'weight_class_0': 0.2802349001188985, 'weight_class_1': 8.232108915241598, 'weight_class_2': 7.863109594276848}. Best is trial 671 with value: 0.9497507654006467.
[I 2026-07-10 16:12:20,256] Trial 678 finished with value: 0.9497603692199318 and parameters: {'weight_class_0': 0.6303339826536634, 'weight_class_1': 8.181650609674648, 'weight_class_2': 7.4585517118525235}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:20,275] Trial 679 finished with value: 0.948276777547267 and parameters: {'weight_class_0': 0.27261497407813573, 'weight_class_1': 8.142971032148363, 'weight_class_2': 7.49813115589539}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:20,283] Trial 680 finished with value: 0.9497006717582158 and parameters: {'weight_class_0': 0.6467752465111041, 'weight_class_1': 8.232490607259054, 'weight_class_2': 7.528495118144951}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:20,319] Trial 681 finished with value: 0.9482532719144631 and parameters: {'weight_class_0': 0.2698611500322648, 'weight_class_1': 8.169025321707194, 'weight_class_2': 7.511894829132799}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:20,326] Trial 682 finished with value: 0.9485916633858976 and parameters: {'weight_class_0': 0.30610157046135605, 'weight_class_1': 8.226267684275093, 'weight_class_2': 7.510639788201623}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:20,377] Trial 684 finished with value: 0.9485687706068126 and parameters: {'weight_class_0': 0.30231107263507123, 'weight_class_1': 7.6716265053705435, 'weight_class_2': 7.612591966595913}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:20,393] Trial 683 finished with value: 0.9482361927488289 and parameters: {'weight_class_0': 0.2595734881013861, 'weight_class_1': 7.671989619971003, 'weight_class_2': 7.558743741552864}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:20,397] Trial 685 finished with value: 0.9483299496626433 and parameters: {'weight_class_0': 0.2772598333559372, 'weight_class_1': 7.96363117008262, 'weight_class_2': 7.530640872657124}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:20,417] Trial 686 finished with value: 0.9481323720709068 and parameters: {'weight_class_0': 0.2570373104582421, 'weight_class_1': 7.609515421148009, 'weight_class_2': 7.825476154138957}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:20,445] Trial 687 finished with value: 0.9428514701089634 and parameters: {'weight_class_0': 1.9669014380637084, 'weight_class_1': 7.553530473933449, 'weight_class_2': 7.554914706218926}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:20,463] Trial 689 finished with value: 0.9481610594015869 and parameters: {'weight_class_0': 0.2567351558266483, 'weight_class_1': 7.883896910852734, 'weight_class_2': 7.545999993695316}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:20,476] Trial 688 finished with value: 0.9482931064451137 and parameters: {'weight_class_0': 0.2699857022639216, 'weight_class_1': 7.662282863163435, 'weight_class_2': 7.593247710309365}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:20,485] Trial 690 finished with value: 0.9482556460588009 and parameters: {'weight_class_0': 0.26198863528374194, 'weight_class_1': 7.651507082840972, 'weight_class_2': 7.5694154617399905}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:20,530] Trial 692 finished with value: 0.9486834695724916 and parameters: {'weight_class_0': 0.3294908833166624, 'weight_class_1': 7.920948493794385, 'weight_class_2': 7.640718484678751}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:20,562] Trial 691 finished with value: 0.9486318417552573 and parameters: {'weight_class_0': 0.3156411210622235, 'weight_class_1': 7.934765039605662, 'weight_class_2': 7.596434136099144}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  23%|███████████████████████████████                                                                                                      | 702/3000 [00:14<00:51, 44.94it/s]

[I 2026-07-10 16:12:20,588] Trial 694 finished with value: 0.9494060281224744 and parameters: {'weight_class_0': 0.5130577267621268, 'weight_class_1': 7.5856400253026735, 'weight_class_2': 7.805631588098316}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:20,613] Trial 695 finished with value: 0.9495177409742407 and parameters: {'weight_class_0': 0.5608558031957185, 'weight_class_1': 7.922256980203166, 'weight_class_2': 7.782560749689357}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:20,618] Trial 693 finished with value: 0.9489347566310734 and parameters: {'weight_class_0': 0.36854633391619135, 'weight_class_1': 7.628730635067437, 'weight_class_2': 7.556537601605577}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:20,656] Trial 696 finished with value: 0.9496373649589108 and parameters: {'weight_class_0': 0.561674807027669, 'weight_class_1': 7.926953977506198, 'weight_class_2': 7.16388735667848}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:20,670] Trial 697 finished with value: 0.9496424623188157 and parameters: {'weight_class_0': 0.549952936031522, 'weight_class_1': 7.933303414450182, 'weight_class_2': 7.1784397450476956}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:20,684] Trial 698 finished with value: 0.9192183446638592 and parameters: {'weight_class_0': 3.935785649039511, 'weight_class_1': 7.954595299782686, 'weight_class_2': 7.177115445510396}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:20,693] Trial 699 finished with value: 0.9492772824834348 and parameters: {'weight_class_0': 0.8378165952599892, 'weight_class_1': 7.910924749809785, 'weight_class_2': 7.208228617771147}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:20,728] Trial 700 finished with value: 0.9496377434904124 and parameters: {'weight_class_0': 0.5653846860909396, 'weight_class_1': 7.970377717755506, 'weight_class_2': 7.158505441027943}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:20,748] Trial 701 finished with value: 0.9491221765393701 and parameters: {'weight_class_0': 0.8646389092274838, 'weight_class_1': 8.004960672573443, 'weight_class_2': 7.165218736305984}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:20,765] Trial 702 finished with value: 0.9491856799739652 and parameters: {'weight_class_0': 0.8633783538556863, 'weight_class_1': 8.53915929301927, 'weight_class_2': 7.1489398779676465}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  24%|███████████████████████████████▌                                                                                                     | 712/3000 [00:14<00:49, 45.88it/s]

[I 2026-07-10 16:12:20,814] Trial 703 finished with value: 0.9489742811055999 and parameters: {'weight_class_0': 0.906216528418306, 'weight_class_1': 8.031481033534801, 'weight_class_2': 7.158984870572665}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:20,828] Trial 704 finished with value: 0.9493135933431102 and parameters: {'weight_class_0': 0.8196549815341536, 'weight_class_1': 7.983342921336418, 'weight_class_2': 7.175217097527562}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:20,854] Trial 705 finished with value: 0.9491434390863355 and parameters: {'weight_class_0': 0.8820555514807422, 'weight_class_1': 8.558692748492758, 'weight_class_2': 7.235573388248079}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:20,884] Trial 706 finished with value: 0.9492897252542392 and parameters: {'weight_class_0': 0.8527490991764304, 'weight_class_1': 8.55470054751061, 'weight_class_2': 7.186561300289335}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:20,905] Trial 707 finished with value: 0.9490733852629885 and parameters: {'weight_class_0': 0.8936170642316087, 'weight_class_1': 8.565994158216524, 'weight_class_2': 7.149038975035849}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:20,929] Trial 708 finished with value: 0.9493597486998574 and parameters: {'weight_class_0': 0.8163528914720767, 'weight_class_1': 8.569699629781736, 'weight_class_2': 7.089357307774105}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:20,953] Trial 709 finished with value: 0.9493732632489505 and parameters: {'weight_class_0': 0.8444817710378375, 'weight_class_1': 8.556650837362278, 'weight_class_2': 7.371548480800846}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:20,963] Trial 710 finished with value: 0.9492186477302339 and parameters: {'weight_class_0': 0.8794943576749803, 'weight_class_1': 8.553161735316053, 'weight_class_2': 7.37388679591748}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:20,997] Trial 712 finished with value: 0.9495201998469905 and parameters: {'weight_class_0': 0.8082552383280264, 'weight_class_1': 8.573081994275666, 'weight_class_2': 7.836550785320874}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:21,011] Trial 711 finished with value: 0.9496609420255199 and parameters: {'weight_class_0': 0.748843488194621, 'weight_class_1': 8.577047736235318, 'weight_class_2': 7.835872098440391}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  24%|███████████████████████████████▉                                                                                                     | 721/3000 [00:14<00:52, 43.58it/s]

[I 2026-07-10 16:12:21,070] Trial 714 finished with value: 0.9497081744958726 and parameters: {'weight_class_0': 0.69825812308206, 'weight_class_1': 8.566245603860526, 'weight_class_2': 7.431190167827}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:21,072] Trial 713 finished with value: 0.9496280978206718 and parameters: {'weight_class_0': 0.7461925922271436, 'weight_class_1': 8.586549179506708, 'weight_class_2': 7.39954180408576}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:21,097] Trial 715 finished with value: 0.9496991466247269 and parameters: {'weight_class_0': 0.6405207909033855, 'weight_class_1': 8.563641920955837, 'weight_class_2': 7.375997921156855}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:21,103] Trial 716 finished with value: 0.9497326331768782 and parameters: {'weight_class_0': 0.6335352152796944, 'weight_class_1': 8.551142714565609, 'weight_class_2': 7.79772143714049}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:21,159] Trial 719 finished with value: 0.9497105817987671 and parameters: {'weight_class_0': 0.6526597029040597, 'weight_class_1': 8.322398142036334, 'weight_class_2': 7.791544748578575}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:21,165] Trial 718 finished with value: 0.949726545315897 and parameters: {'weight_class_0': 0.6584026425906705, 'weight_class_1': 8.313469797630326, 'weight_class_2': 7.82826806564315}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:21,180] Trial 717 finished with value: 0.9497208340820201 and parameters: {'weight_class_0': 0.6576922596377844, 'weight_class_1': 8.274273501393385, 'weight_class_2': 7.807013732627283}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:21,202] Trial 720 finished with value: 0.9481386342075887 and parameters: {'weight_class_0': 1.2116310811657978, 'weight_class_1': 8.282432279040275, 'weight_class_2': 7.780022511312245}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:21,233] Trial 721 finished with value: 0.9496582558723867 and parameters: {'weight_class_0': 0.6228923508743578, 'weight_class_1': 8.268215524692618, 'weight_class_2': 7.806417866661345}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  24%|████████████████████████████████▍                                                                                                    | 731/3000 [00:14<00:51, 43.66it/s]

[I 2026-07-10 16:12:21,240] Trial 722 finished with value: 0.9476275626597045 and parameters: {'weight_class_0': 1.2292693393064944, 'weight_class_1': 8.30194446856583, 'weight_class_2': 6.699686479933371}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:21,270] Trial 723 finished with value: 0.9480984715719623 and parameters: {'weight_class_0': 1.2291158518574246, 'weight_class_1': 8.307350549061628, 'weight_class_2': 7.795343640666998}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:21,278] Trial 724 finished with value: 0.9479948528723607 and parameters: {'weight_class_0': 1.2405370624629275, 'weight_class_1': 8.265898249924275, 'weight_class_2': 7.400920585526863}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:21,302] Trial 725 finished with value: 0.9477582247313268 and parameters: {'weight_class_0': 1.205853076049589, 'weight_class_1': 8.281153380028789, 'weight_class_2': 6.748414805490087}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:21,335] Trial 726 finished with value: 0.9479899305724264 and parameters: {'weight_class_0': 1.260465771094025, 'weight_class_1': 8.278311896912983, 'weight_class_2': 7.678318722309559}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:21,353] Trial 727 finished with value: 0.9480160542193702 and parameters: {'weight_class_0': 1.2427927415021403, 'weight_class_1': 8.273094716165554, 'weight_class_2': 7.713204801000467}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:21,380] Trial 728 finished with value: 0.9491831476191912 and parameters: {'weight_class_0': 0.42559197069306787, 'weight_class_1': 8.196421304269974, 'weight_class_2': 7.913294310339629}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:21,409] Trial 729 finished with value: 0.9482826961126044 and parameters: {'weight_class_0': 1.1750419300088493, 'weight_class_1': 8.17834611217736, 'weight_class_2': 7.89010098439557}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:21,426] Trial 730 finished with value: 0.9492914070697118 and parameters: {'weight_class_0': 0.461453561909085, 'weight_class_1': 8.137097281166879, 'weight_class_2': 7.9010895239996195}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:21,461] Trial 731 finished with value: 0.949050946954905 and parameters: {'weight_class_0': 0.4058265168269928, 'weight_class_1': 8.175406941776272, 'weight_class_2': 7.893326263246388}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  25%|████████████████████████████████▊                                                                                                    | 739/3000 [00:14<00:51, 43.92it/s]

[I 2026-07-10 16:12:21,469] Trial 732 finished with value: 0.9493506264422055 and parameters: {'weight_class_0': 0.4658852107850614, 'weight_class_1': 8.16620328593183, 'weight_class_2': 7.770353947608332}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:21,497] Trial 734 finished with value: 0.9493335395638997 and parameters: {'weight_class_0': 0.4678599490222364, 'weight_class_1': 8.11651432056346, 'weight_class_2': 7.851851756906495}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:21,516] Trial 733 finished with value: 0.9493381031755362 and parameters: {'weight_class_0': 0.47107899402141773, 'weight_class_1': 8.100377893174045, 'weight_class_2': 7.890032957804332}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:21,551] Trial 736 finished with value: 0.9493023816203787 and parameters: {'weight_class_0': 0.4577311245044195, 'weight_class_1': 8.117595611975167, 'weight_class_2': 7.806481301998253}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:21,569] Trial 735 finished with value: 0.9492332371521516 and parameters: {'weight_class_0': 0.4418901965030479, 'weight_class_1': 8.111850114627291, 'weight_class_2': 7.918736502410978}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:21,602] Trial 737 finished with value: 0.9492960566153266 and parameters: {'weight_class_0': 0.4608823339328597, 'weight_class_1': 8.091193971451334, 'weight_class_2': 7.929245459013682}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:21,610] Trial 739 finished with value: 0.8218953193290296 and parameters: {'weight_class_0': 0.44467280061796466, 'weight_class_1': 0.01534688710136578, 'weight_class_2': 7.917042257536314}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:21,637] Trial 738 finished with value: 0.9494035919968328 and parameters: {'weight_class_0': 0.48503589507988404, 'weight_class_1': 8.072708555247745, 'weight_class_2': 7.837775908229859}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  25%|█████████████████████████████████▏                                                                                                   | 749/3000 [00:15<00:52, 42.91it/s]

[I 2026-07-10 16:12:21,690] Trial 741 finished with value: 0.9439973924339068 and parameters: {'weight_class_0': 0.12904751438627504, 'weight_class_1': 8.073529163932625, 'weight_class_2': 7.6808779610242155}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:21,697] Trial 740 finished with value: 0.744189102351878 and parameters: {'weight_class_0': 0.020060414989181097, 'weight_class_1': 8.136709951260174, 'weight_class_2': 7.658399656198695}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:21,702] Trial 742 finished with value: 0.9455022922022761 and parameters: {'weight_class_0': 0.15143413016804086, 'weight_class_1': 8.050392769434715, 'weight_class_2': 7.6408962537097285}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:21,739] Trial 744 finished with value: 0.939567605283233 and parameters: {'weight_class_0': 2.3987036539228432, 'weight_class_1': 8.084256631280208, 'weight_class_2': 7.678781660644523}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:21,740] Trial 743 finished with value: 0.9416743265872495 and parameters: {'weight_class_0': 0.10834633375055758, 'weight_class_1': 8.061438075132802, 'weight_class_2': 7.57695994634427}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:21,786] Trial 745 finished with value: 0.9401978961368301 and parameters: {'weight_class_0': 0.097990471454792, 'weight_class_1': 7.8269746871454915, 'weight_class_2': 7.672423647390583}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:21,792] Trial 747 finished with value: 0.928641423786658 and parameters: {'weight_class_0': 0.07306231814424691, 'weight_class_1': 8.431568274286343, 'weight_class_2': 7.594095292695818}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:21,797] Trial 746 finished with value: 0.9428730693655561 and parameters: {'weight_class_0': 0.1141405289690749, 'weight_class_1': 7.8091866744883704, 'weight_class_2': 7.580796839535434}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:21,832] Trial 748 finished with value: 0.9485757267972272 and parameters: {'weight_class_0': 1.0673032042320743, 'weight_class_1': 7.816301896973921, 'weight_class_2': 7.5907082977193046}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:21,837] Trial 749 finished with value: 0.8552034809180621 and parameters: {'weight_class_0': 0.03492701139833376, 'weight_class_1': 7.794350270559964, 'weight_class_2': 7.638694706131364}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  25%|█████████████████████████████████▋                                                                                                   | 759/3000 [00:15<00:50, 44.22it/s]

[I 2026-07-10 16:12:21,874] Trial 750 finished with value: 0.941074015954861 and parameters: {'weight_class_0': 0.10747505695492587, 'weight_class_1': 8.38418990188981, 'weight_class_2': 7.575112897615726}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:21,894] Trial 751 finished with value: 0.8723926018014696 and parameters: {'weight_class_0': 8.623121985844868, 'weight_class_1': 8.453310420470034, 'weight_class_2': 7.535244259842028}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:21,926] Trial 752 finished with value: 0.9488674400321591 and parameters: {'weight_class_0': 1.0208933395116184, 'weight_class_1': 8.402438197034632, 'weight_class_2': 7.489782300171175}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:21,957] Trial 753 finished with value: 0.948795522703187 and parameters: {'weight_class_0': 0.9726406295708975, 'weight_class_1': 7.806028597665612, 'weight_class_2': 7.456990441415376}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:21,978] Trial 754 finished with value: 0.948715765975792 and parameters: {'weight_class_0': 0.9960956525079785, 'weight_class_1': 7.766192345367599, 'weight_class_2': 7.471067571220774}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:22,022] Trial 757 finished with value: 0.9127733236740472 and parameters: {'weight_class_0': 4.5855208866067265, 'weight_class_1': 8.423484832948317, 'weight_class_2': 7.4452976679650185}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:22,029] Trial 756 finished with value: 0.9488549507797316 and parameters: {'weight_class_0': 1.0194317025068231, 'weight_class_1': 8.826102137323995, 'weight_class_2': 7.417928533009093}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:22,030] Trial 755 finished with value: 0.9488678983809744 and parameters: {'weight_class_0': 1.0100280585022925, 'weight_class_1': 8.409499457483296, 'weight_class_2': 7.444990897358702}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:22,082] Trial 758 finished with value: 0.8932343020278851 and parameters: {'weight_class_0': 6.15007168078942, 'weight_class_1': 8.379893074297483, 'weight_class_2': 7.3534391730641415}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:22,097] Trial 759 finished with value: 0.9488249753568369 and parameters: {'weight_class_0': 1.0309846803021818, 'weight_class_1': 8.848383006291035, 'weight_class_2': 7.396317904437108}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:22,106] Trial 760 finished with value: 0.9377037029463869 and parameters: {'weight_class_0': 2.614618266910301, 'weight_class_1': 8.836581928992087, 'weight_class_2': 7.3998733626823565}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:22,123] Trial 761 finished with value: 0.9488658515269526 and parameters: {'weight_class_0': 1.018441768336056, 'weight_class_1': 8.745437822411818, 'weight_class_2': 7.413962403870267}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:22,161] Trial 762 finished with value: 0.9488789901608042 and parameters: {'weight_class_0': 1.001228701971462, 'weight_class_1': 8.821946383795764, 'weight_class_2': 7.389419613402269}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:22,207] Trial 763 finished with value: 0.9140404851832131 and parameters: {'weight_class_0': 4.532320278607186, 'weight_class_1': 8.75163342609967, 'weight_class_2': 7.322772200201146}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:22,230] Trial 764 finished with value: 0.9496993788779794 and parameters: {'weight_class_0': 0.6836124725405232, 'weight_class_1': 8.81814891593227, 'weight_class_2': 7.335356397787626}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:22,245] Trial 765 finished with value: 0.9497007331637651 and parameters: {'weight_class_0': 0.6913250406716915, 'weight_class_1': 8.867119299135984, 'weight_class_2': 7.361802123418049}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:22,273] Trial 767 finished with value: 0.9495427647600051 and parameters: {'weight_class_0': 0.734022200140377, 'weight_class_1': 8.802067534974805, 'weight_class_2': 6.95953890357244}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:22,278] Trial 766 finished with value: 0.9496072295722531 and parameters: {'weight_class_0': 0.707777313871653, 'weight_class_1': 8.691787140123562, 'weight_class_2': 7.027888247248603}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:22,296] Trial 768 finished with value: 0.9495041404086527 and parameters: {'weight_class_0': 0.7512161426962215, 'weight_class_1': 8.707138621995531, 'weight_class_2': 7.017329925623034}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  26%|██████████████████████████████████▍                                                                                                  | 777/3000 [00:15<00:52, 42.56it/s]

[I 2026-07-10 16:12:22,316] Trial 769 finished with value: 0.9497180257471346 and parameters: {'weight_class_0': 0.6717800916592456, 'weight_class_1': 8.744447130855463, 'weight_class_2': 8.075153255301705}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:22,324] Trial 770 finished with value: 0.949689716207634 and parameters: {'weight_class_0': 0.6707921421052236, 'weight_class_1': 8.667928981828517, 'weight_class_2': 7.027851041191286}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:22,381] Trial 771 finished with value: 0.9496844542812579 and parameters: {'weight_class_0': 0.6361359426052947, 'weight_class_1': 8.648732173878374, 'weight_class_2': 7.050796150173056}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:22,410] Trial 772 finished with value: 0.9496114944697019 and parameters: {'weight_class_0': 0.6947937925208673, 'weight_class_1': 8.666877275745366, 'weight_class_2': 6.9995903053629345}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:22,450] Trial 773 finished with value: 0.9497047629243367 and parameters: {'weight_class_0': 0.6676981427737988, 'weight_class_1': 8.462592376751513, 'weight_class_2': 7.052980074314505}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:22,472] Trial 775 finished with value: 0.9495958417972922 and parameters: {'weight_class_0': 0.704666103326258, 'weight_class_1': 8.569345269452194, 'weight_class_2': 7.031992973902818}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:22,472] Trial 774 finished with value: 0.949583396854726 and parameters: {'weight_class_0': 0.7228356807456937, 'weight_class_1': 8.528520957568634, 'weight_class_2': 7.024805146923369}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:22,475] Trial 776 finished with value: 0.9496390357741488 and parameters: {'weight_class_0': 0.6849387691570673, 'weight_class_1': 8.672669939580747, 'weight_class_2': 6.977193487288196}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:22,515] Trial 777 finished with value: 0.949646115452283 and parameters: {'weight_class_0': 0.639917289912991, 'weight_class_1': 8.551734399417244, 'weight_class_2': 8.060004898814814}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:22,549] Trial 778 finished with value: 0.9467893405849503 and parameters: {'weight_class_0': 1.551095253368055, 'weight_class_1': 8.585004241276373, 'weight_class_2': 8.114363140127056}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:22,551] Trial 779 finished with value: 0.9495713906030848 and parameters: {'weight_class_0': 0.5842400153874954, 'weight_class_1': 8.565750343216694, 'weight_class_2': 8.004722892257842}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:22,581] Trial 780 finished with value: 0.9495037436096746 and parameters: {'weight_class_0': 0.5570055805621088, 'weight_class_1': 8.425887205495636, 'weight_class_2': 8.004885002003956}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:22,633] Trial 781 finished with value: 0.9493756384550326 and parameters: {'weight_class_0': 0.5321345059095599, 'weight_class_1': 7.367700654206658, 'weight_class_2': 8.078169248868798}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:22,638] Trial 782 finished with value: 0.9494309598373164 and parameters: {'weight_class_0': 0.5029262901111166, 'weight_class_1': 8.373295640018169, 'weight_class_2': 7.987205694012361}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:22,661] Trial 783 finished with value: 0.9488149176944319 and parameters: {'weight_class_0': 0.36974545016972005, 'weight_class_1': 8.387541483764618, 'weight_class_2': 8.020024318679843}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:22,671] Trial 784 finished with value: 0.9486749048792081 and parameters: {'weight_class_0': 0.34653884752087666, 'weight_class_1': 8.398556803414516, 'weight_class_2': 8.080841640510172}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:22,700] Trial 785 finished with value: 0.9488837129886334 and parameters: {'weight_class_0': 0.376985629565843, 'weight_class_1': 7.502969654430137, 'weight_class_2': 8.10921843850636}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:22,704] Trial 786 finished with value: 0.9488384449720404 and parameters: {'weight_class_0': 0.3550602844199915, 'weight_class_1': 7.365831870093602, 'weight_class_2': 7.698777882312104}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  27%|███████████████████████████████████▎                                                                                                 | 796/3000 [00:16<00:50, 44.06it/s]

[I 2026-07-10 16:12:22,742] Trial 787 finished with value: 0.9488338318180224 and parameters: {'weight_class_0': 0.3692579472719623, 'weight_class_1': 7.48447920766082, 'weight_class_2': 8.094719834205517}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:22,765] Trial 788 finished with value: 0.9487165651952448 and parameters: {'weight_class_0': 0.34484756502116704, 'weight_class_1': 8.34751064192552, 'weight_class_2': 7.721174293837208}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:22,798] Trial 789 finished with value: 0.9490864055089202 and parameters: {'weight_class_0': 0.35050318535002967, 'weight_class_1': 7.42120788375512, 'weight_class_2': 6.681918391967336}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:22,818] Trial 790 finished with value: 0.9487210654351639 and parameters: {'weight_class_0': 0.3458255623091284, 'weight_class_1': 8.330838511027869, 'weight_class_2': 7.752486911460598}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:22,831] Trial 791 finished with value: 0.9487198770034665 and parameters: {'weight_class_0': 0.3436112941298857, 'weight_class_1': 8.324277563808558, 'weight_class_2': 7.7076006051377535}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:22,849] Trial 792 finished with value: 0.9488839572001365 and parameters: {'weight_class_0': 0.33228045216040586, 'weight_class_1': 8.294976598499806, 'weight_class_2': 6.716085552120672}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:22,918] Trial 793 finished with value: 0.9492074159533872 and parameters: {'weight_class_0': 0.8954407941572338, 'weight_class_1': 8.248074963252051, 'weight_class_2': 7.676893722166327}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:22,919] Trial 794 finished with value: 0.9492606616666159 and parameters: {'weight_class_0': 0.8791116760362874, 'weight_class_1': 8.244959877559232, 'weight_class_2': 7.7122407002071185}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:22,927] Trial 795 finished with value: 0.9489062310522592 and parameters: {'weight_class_0': 0.8907868651892619, 'weight_class_1': 8.267176946643199, 'weight_class_2': 6.731982293156643}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:22,967] Trial 796 finished with value: 0.9466621384569819 and parameters: {'weight_class_0': 0.8960915443774039, 'weight_class_1': 8.238049981892233, 'weight_class_2': 3.6170527953434037}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  27%|███████████████████████████████████▋                                                                                                 | 805/3000 [00:16<00:50, 43.11it/s]

[I 2026-07-10 16:12:22,985] Trial 797 finished with value: 0.9490073264046238 and parameters: {'weight_class_0': 0.8621406697052678, 'weight_class_1': 8.257241891190828, 'weight_class_2': 6.75094378792048}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:23,012] Trial 799 finished with value: 0.9490485685312106 and parameters: {'weight_class_0': 0.9388514475044158, 'weight_class_1': 8.236506231034639, 'weight_class_2': 7.694274443732834}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:23,019] Trial 798 finished with value: 0.8651402679454026 and parameters: {'weight_class_0': 9.402450058924332, 'weight_class_1': 8.232566151545665, 'weight_class_2': 6.702583943751082}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:23,071] Trial 800 finished with value: 0.9490134471234856 and parameters: {'weight_class_0': 0.9087518701256516, 'weight_class_1': 8.020310065407832, 'weight_class_2': 7.270915476848129}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:23,079] Trial 801 finished with value: 0.949030009459405 and parameters: {'weight_class_0': 0.8906176569352654, 'weight_class_1': 7.889289387539526, 'weight_class_2': 7.2544655112364875}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:23,085] Trial 802 finished with value: 0.9489947916859736 and parameters: {'weight_class_0': 0.9114376715953424, 'weight_class_1': 7.973282527263503, 'weight_class_2': 7.2317532784643035}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:23,131] Trial 803 finished with value: 0.948923579808658 and parameters: {'weight_class_0': 0.9381318631946216, 'weight_class_1': 7.9633975919415345, 'weight_class_2': 7.245328426249196}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:23,139] Trial 805 finished with value: 0.9489656200466102 and parameters: {'weight_class_0': 0.9101157410221412, 'weight_class_1': 7.934398632098151, 'weight_class_2': 7.199878382513001}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:23,140] Trial 804 finished with value: 0.9490787412061753 and parameters: {'weight_class_0': 0.8820946579636998, 'weight_class_1': 7.9424892848894535, 'weight_class_2': 7.20652185417715}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:23,178] Trial 806 finished with value: 0.9489356507403798 and parameters: {'weight_class_0': 0.9356620299774963, 'weight_class_1': 8.017909333195126, 'weight_class_2': 7.2419155610401065}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:23,217] Trial 807 finished with value: 0.9462309480782465 and parameters: {'weight_class_0': 1.4989739235544177, 'weight_class_1': 7.946896846394235, 'weight_class_2': 7.250382826380814}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:23,235] Trial 808 finished with value: 0.9468890630341714 and parameters: {'weight_class_0': 1.397203862331553, 'weight_class_1': 7.942042368977043, 'weight_class_2': 7.236753028866295}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:23,279] Trial 809 finished with value: 0.9496258912499718 and parameters: {'weight_class_0': 0.5718170943273342, 'weight_class_1': 7.9727716019208, 'weight_class_2': 7.309020706718977}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:23,281] Trial 810 finished with value: 0.9496024713455521 and parameters: {'weight_class_0': 0.5401661826177794, 'weight_class_1': 7.985403010854497, 'weight_class_2': 7.267667068538368}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:23,306] Trial 811 finished with value: 0.9466654227565422 and parameters: {'weight_class_0': 1.461958161788965, 'weight_class_1': 7.974936006612976, 'weight_class_2': 7.504294457475786}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:23,344] Trial 812 finished with value: 0.9495544347832782 and parameters: {'weight_class_0': 0.5412487376600617, 'weight_class_1': 7.9428278160887595, 'weight_class_2': 7.5110514888750135}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:23,360] Trial 813 finished with value: 0.9495527915364818 and parameters: {'weight_class_0': 0.5350258031058116, 'weight_class_1': 8.931542325614146, 'weight_class_2': 7.50142878650344}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:23,384] Trial 814 finished with value: 0.9467820359550486 and parameters: {'weight_class_0': 1.5000908456276059, 'weight_class_1': 8.55727128616572, 'weight_class_2': 7.528978030557487}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  27%|████████████████████████████████████▍                                                                                                | 823/3000 [00:16<00:50, 42.83it/s]

[I 2026-07-10 16:12:23,406] Trial 816 finished with value: 0.9496184297662703 and parameters: {'weight_class_0': 0.5617937450922259, 'weight_class_1': 8.96179138468639, 'weight_class_2': 7.486884863492458}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:23,415] Trial 815 finished with value: 0.9472233192685288 and parameters: {'weight_class_0': 1.4177163004565556, 'weight_class_1': 8.551614911491027, 'weight_class_2': 7.517281999717453}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:23,445] Trial 817 finished with value: 0.9445747159612935 and parameters: {'weight_class_0': 0.5522740268467801, 'weight_class_1': 1.8608113115184484, 'weight_class_2': 7.514000783176886}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:23,471] Trial 818 finished with value: 0.9496102617488886 and parameters: {'weight_class_0': 0.5552104221867898, 'weight_class_1': 8.91504006712417, 'weight_class_2': 7.491882834348825}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:23,488] Trial 819 finished with value: 0.9496225514746879 and parameters: {'weight_class_0': 0.5608659949907193, 'weight_class_1': 8.919676125370433, 'weight_class_2': 7.528567947644962}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:23,500] Trial 820 finished with value: 0.9494219058417346 and parameters: {'weight_class_0': 0.49393825234726996, 'weight_class_1': 8.924237658930315, 'weight_class_2': 7.472634791658794}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:23,514] Trial 821 finished with value: 0.9496702685621141 and parameters: {'weight_class_0': 0.5793761602674425, 'weight_class_1': 8.890996599170537, 'weight_class_2': 7.536642078101968}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:23,555] Trial 822 finished with value: 0.9496663960255031 and parameters: {'weight_class_0': 0.586853046972234, 'weight_class_1': 8.559451598673283, 'weight_class_2': 7.517700475326358}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:23,594] Trial 823 finished with value: 0.9497154979202659 and parameters: {'weight_class_0': 0.7425345281794447, 'weight_class_1': 8.965275890557672, 'weight_class_2': 7.758380949302219}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  28%|████████████████████████████████████▉                                                                                                | 832/3000 [00:17<00:49, 43.88it/s]

[I 2026-07-10 16:12:23,615] Trial 824 finished with value: 0.8924133030830951 and parameters: {'weight_class_0': 1.182899435861707, 'weight_class_1': 0.3664974877187115, 'weight_class_2': 7.861159823427869}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:23,635] Trial 826 finished with value: 0.9483919242138037 and parameters: {'weight_class_0': 1.1666907553246197, 'weight_class_1': 8.478155968809993, 'weight_class_2': 7.8240319469983515}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:23,654] Trial 825 finished with value: 0.9496631364864333 and parameters: {'weight_class_0': 0.7466214908179105, 'weight_class_1': 8.503184841692715, 'weight_class_2': 7.907470654912741}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:23,681] Trial 827 finished with value: 0.9482077088790438 and parameters: {'weight_class_0': 1.1911483338261324, 'weight_class_1': 8.452120806129999, 'weight_class_2': 7.862806630922127}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:23,686] Trial 828 finished with value: 0.9483990122957268 and parameters: {'weight_class_0': 1.1616275332673174, 'weight_class_1': 8.458485271871846, 'weight_class_2': 7.7745720241392835}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:23,712] Trial 829 finished with value: 0.9484218859101591 and parameters: {'weight_class_0': 1.1750170604798233, 'weight_class_1': 8.590430584044293, 'weight_class_2': 7.860168853341748}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:23,734] Trial 830 finished with value: 0.9484779564038694 and parameters: {'weight_class_0': 1.144584292181212, 'weight_class_1': 8.480439425013353, 'weight_class_2': 7.806842177928823}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:23,755] Trial 831 finished with value: 0.948409133417684 and parameters: {'weight_class_0': 1.1648134842623463, 'weight_class_1': 8.444695352667072, 'weight_class_2': 7.84534731944673}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:23,772] Trial 832 finished with value: 0.9485598911465819 and parameters: {'weight_class_0': 1.1371013580180767, 'weight_class_1': 8.502071801441419, 'weight_class_2': 7.8910099765593475}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  28%|█████████████████████████████████████▎                                                                                               | 842/3000 [00:17<00:49, 43.88it/s]

[I 2026-07-10 16:12:23,823] Trial 833 finished with value: 0.8964150729133632 and parameters: {'weight_class_0': 1.1015596450228087, 'weight_class_1': 0.43087924807778766, 'weight_class_2': 7.79837011880968}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:23,838] Trial 834 finished with value: 0.9482001850105659 and parameters: {'weight_class_0': 1.1937558950739011, 'weight_class_1': 8.385520943439587, 'weight_class_2': 7.886250869109785}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:23,862] Trial 835 finished with value: 0.9475813391668858 and parameters: {'weight_class_0': 0.23038939576230594, 'weight_class_1': 8.390637434556346, 'weight_class_2': 7.82864880819412}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:23,890] Trial 836 finished with value: 0.9473598229776439 and parameters: {'weight_class_0': 0.2197893693116013, 'weight_class_1': 8.352350815919513, 'weight_class_2': 7.906699876632223}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:23,902] Trial 837 finished with value: 0.9472457857295145 and parameters: {'weight_class_0': 0.20109209947294165, 'weight_class_1': 8.148439596908391, 'weight_class_2': 7.064855483730351}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:23,935] Trial 838 finished with value: 0.9452162540442712 and parameters: {'weight_class_0': 0.17656171709165408, 'weight_class_1': 8.13710619001863, 'weight_class_2': 0.7250154838542757}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:23,943] Trial 839 finished with value: 0.9476602851794258 and parameters: {'weight_class_0': 0.23723274434253133, 'weight_class_1': 8.188059551359368, 'weight_class_2': 8.245127038152658}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:23,979] Trial 840 finished with value: 0.9475613607387733 and parameters: {'weight_class_0': 0.21586955838824085, 'weight_class_1': 8.151093962159807, 'weight_class_2': 7.1253959027730716}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:24,007] Trial 841 finished with value: 0.9472370370377429 and parameters: {'weight_class_0': 0.1992618445788622, 'weight_class_1': 8.149578186808785, 'weight_class_2': 6.85686590613385}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:24,016] Trial 842 finished with value: 0.9474720660772741 and parameters: {'weight_class_0': 0.20916071717980467, 'weight_class_1': 8.152664082546812, 'weight_class_2': 6.910474781972936}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  28%|█████████████████████████████████████▊                                                                                               | 852/3000 [00:17<00:49, 43.56it/s]

[I 2026-07-10 16:12:24,040] Trial 843 finished with value: 0.9464041328413729 and parameters: {'weight_class_0': 0.17530293894379861, 'weight_class_1': 7.7148958209075795, 'weight_class_2': 8.242638641349005}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:24,071] Trial 844 finished with value: 0.8803838873803956 and parameters: {'weight_class_0': 3.286422175944154, 'weight_class_1': 7.706352436924461, 'weight_class_2': 0.439638446578976}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:24,090] Trial 845 finished with value: 0.947482797333894 and parameters: {'weight_class_0': 0.22023039908257758, 'weight_class_1': 7.710026932583774, 'weight_class_2': 8.21567295264069}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:24,103] Trial 846 finished with value: 0.9495992198275441 and parameters: {'weight_class_0': 0.767531630590504, 'weight_class_1': 8.173940302277114, 'weight_class_2': 8.16450852908071}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:24,149] Trial 847 finished with value: 0.9494636896218228 and parameters: {'weight_class_0': 0.8198889057325809, 'weight_class_1': 8.197026032211653, 'weight_class_2': 8.243356264921768}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:24,177] Trial 848 finished with value: 0.9493122120772033 and parameters: {'weight_class_0': 0.8002365885180793, 'weight_class_1': 7.714724723398893, 'weight_class_2': 7.100745620461682}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:24,184] Trial 849 finished with value: 0.9492109496164449 and parameters: {'weight_class_0': 0.8340704047975478, 'weight_class_1': 8.68743817083378, 'weight_class_2': 6.868534329229553}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:24,221] Trial 850 finished with value: 0.9495761242270196 and parameters: {'weight_class_0': 0.7103124690425197, 'weight_class_1': 7.651523788482389, 'weight_class_2': 7.322766352211331}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:24,252] Trial 852 finished with value: 0.9487390344186474 and parameters: {'weight_class_0': 0.7871818419986757, 'weight_class_1': 5.365105926664623, 'weight_class_2': 7.289915130738359}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:24,255] Trial 851 finished with value: 0.9495882847576915 and parameters: {'weight_class_0': 0.7247450992975488, 'weight_class_1': 7.650477472775609, 'weight_class_2': 8.24107877930376}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  29%|██████████████████████████████████████▏                                                                                              | 862/3000 [00:17<00:51, 41.77it/s]

[I 2026-07-10 16:12:24,290] Trial 853 finished with value: 0.9293804355341395 and parameters: {'weight_class_0': 0.763471357851202, 'weight_class_1': 8.724050309477613, 'weight_class_2': 1.2870054982407475}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:24,321] Trial 854 finished with value: 0.9496051532246469 and parameters: {'weight_class_0': 0.7606088872523984, 'weight_class_1': 8.681538512117879, 'weight_class_2': 7.343999310242457}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:24,341] Trial 855 finished with value: 0.9493928540757879 and parameters: {'weight_class_0': 0.7479725839060359, 'weight_class_1': 8.688245659093608, 'weight_class_2': 6.290892595529266}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:24,355] Trial 856 finished with value: 0.9495068175822426 and parameters: {'weight_class_0': 0.7753176989857873, 'weight_class_1': 8.689339619225839, 'weight_class_2': 7.261264753076325}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:24,367] Trial 857 finished with value: 0.9495362051938304 and parameters: {'weight_class_0': 0.7966035046778623, 'weight_class_1': 8.639517540228985, 'weight_class_2': 7.641225350783014}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:24,431] Trial 858 finished with value: 0.9496537960099923 and parameters: {'weight_class_0': 0.717078997170693, 'weight_class_1': 8.781970087600765, 'weight_class_2': 7.374363646701344}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:24,439] Trial 859 finished with value: 0.9496297037917273 and parameters: {'weight_class_0': 0.7302854616919165, 'weight_class_1': 8.653634827072834, 'weight_class_2': 7.300514496850131}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:24,455] Trial 860 finished with value: 0.9496878584485121 and parameters: {'weight_class_0': 0.7028143140234628, 'weight_class_1': 8.691697544947713, 'weight_class_2': 7.349285687361907}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:24,496] Trial 861 finished with value: 0.9485039140562296 and parameters: {'weight_class_0': 0.4505085604338058, 'weight_class_1': 3.088336275234897, 'weight_class_2': 6.322341607421238}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:24,512] Trial 862 finished with value: 0.949595203831676 and parameters: {'weight_class_0': 0.42901424715137443, 'weight_class_1': 8.69759873182659, 'weight_class_2': 4.366422944302127}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:24,524] Trial 863 finished with value: 0.9492919297077007 and parameters: {'weight_class_0': 0.44647769772021983, 'weight_class_1': 8.670829757730058, 'weight_class_2': 7.694577397561485}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:24,527] Trial 864 finished with value: 0.9494680939535657 and parameters: {'weight_class_0': 0.5012401630016092, 'weight_class_1': 8.655131803793658, 'weight_class_2': 7.666777888303339}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:24,562] Trial 865 finished with value: 0.946015367921777 and parameters: {'weight_class_0': 0.5011983226833576, 'weight_class_1': 8.32590698426539, 'weight_class_2': 1.8502303820014738}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:24,580] Trial 866 finished with value: 0.9492642180285081 and parameters: {'weight_class_0': 0.4258369236231909, 'weight_class_1': 8.322840756309017, 'weight_class_2': 7.589348246356394}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:24,594] Trial 867 finished with value: 0.9492849232446918 and parameters: {'weight_class_0': 0.4446912875492428, 'weight_class_1': 8.333440149955441, 'weight_class_2': 7.6303320766206495}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:24,642] Trial 868 finished with value: 0.9494100533957006 and parameters: {'weight_class_0': 0.44164355775252595, 'weight_class_1': 8.334190996763654, 'weight_class_2': 7.08751775035518}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:24,662] Trial 869 finished with value: 0.9493069521633392 and parameters: {'weight_class_0': 0.43379393156861, 'weight_class_1': 8.324751040274743, 'weight_class_2': 7.540972700783514}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:24,686] Trial 871 finished with value: 0.9493208453467306 and parameters: {'weight_class_0': 0.4562016095331469, 'weight_class_1': 8.280794198797587, 'weight_class_2': 7.643319867080665}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  29%|███████████████████████████████████████                                                                                              | 880/3000 [00:18<00:47, 44.24it/s]

[I 2026-07-10 16:12:24,691] Trial 870 finished with value: 0.949178392193598 and parameters: {'weight_class_0': 0.41108616583881635, 'weight_class_1': 8.321080481468977, 'weight_class_2': 7.610942269775114}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:24,734] Trial 872 finished with value: 0.9492996739662635 and parameters: {'weight_class_0': 0.43343983738374603, 'weight_class_1': 8.374737582902164, 'weight_class_2': 7.590831640349745}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:24,765] Trial 873 finished with value: 0.9488546526412981 and parameters: {'weight_class_0': 0.996310658434945, 'weight_class_1': 8.346291806073253, 'weight_class_2': 7.616518636386776}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:24,767] Trial 874 finished with value: 0.9488128596707552 and parameters: {'weight_class_0': 1.0067025262781986, 'weight_class_1': 8.324289063612776, 'weight_class_2': 7.652671942087481}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:24,792] Trial 875 finished with value: 0.9486596614393807 and parameters: {'weight_class_0': 1.038009398810801, 'weight_class_1': 8.33036751888502, 'weight_class_2': 7.078445730967185}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:24,814] Trial 876 finished with value: 0.9487892408564874 and parameters: {'weight_class_0': 1.0020983413442919, 'weight_class_1': 8.113727042443607, 'weight_class_2': 7.11385692083246}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:24,860] Trial 878 finished with value: 0.9487061501003119 and parameters: {'weight_class_0': 1.0350200752109249, 'weight_class_1': 8.991506006393328, 'weight_class_2': 7.032056126685535}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:24,864] Trial 877 finished with value: 0.9488144565387252 and parameters: {'weight_class_0': 0.98441312019997, 'weight_class_1': 8.097522219598813, 'weight_class_2': 7.065318643613215}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:24,897] Trial 880 finished with value: 0.9487919901347194 and parameters: {'weight_class_0': 0.998686803275459, 'weight_class_1': 8.12147830842546, 'weight_class_2': 7.089841963486044}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:24,898] Trial 879 finished with value: 0.9487753164807078 and parameters: {'weight_class_0': 0.9990586850169048, 'weight_class_1': 8.051263357922847, 'weight_class_2': 7.099937809231242}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:24,929] Trial 881 finished with value: 0.9489570703057124 and parameters: {'weight_class_0': 0.913014996942886, 'weight_class_1': 8.087560923760249, 'weight_class_2': 7.066466396457308}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:24,976] Trial 882 finished with value: 0.9488293913615816 and parameters: {'weight_class_0': 0.9709277761675381, 'weight_class_1': 8.070187078766162, 'weight_class_2': 6.9681080939023525}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:25,003] Trial 883 finished with value: 0.9488889818202697 and parameters: {'weight_class_0': 0.9455406226791121, 'weight_class_1': 8.056982478312394, 'weight_class_2': 7.12621766476353}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:25,020] Trial 884 finished with value: 0.9488204272733402 and parameters: {'weight_class_0': 0.9872612914170031, 'weight_class_1': 8.111555771891503, 'weight_class_2': 7.122774550687804}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:25,036] Trial 885 finished with value: 0.8791547441996229 and parameters: {'weight_class_0': 7.5279246109883005, 'weight_class_1': 8.95355264122836, 'weight_class_2': 6.86301814098226}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:25,049] Trial 886 finished with value: 0.9497330699836857 and parameters: {'weight_class_0': 0.6111691022428349, 'weight_class_1': 8.955372858863505, 'weight_class_2': 7.4038572945255785}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:25,072] Trial 887 finished with value: 0.9497132480676709 and parameters: {'weight_class_0': 0.6480954672479091, 'weight_class_1': 8.069220812682829, 'weight_class_2': 7.372298960397267}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:25,087] Trial 888 finished with value: 0.9496994742852042 and parameters: {'weight_class_0': 0.6032010742342309, 'weight_class_1': 8.052034195098365, 'weight_class_2': 7.435655090403564}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:25,105] Trial 889 finished with value: 0.9409608649422799 and parameters: {'weight_class_0': 0.6263854090018997, 'weight_class_1': 1.5818201680415465, 'weight_class_2': 8.014151445988425}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:25,146] Trial 890 finished with value: 0.9497045016837693 and parameters: {'weight_class_0': 0.6178039202681855, 'weight_class_1': 8.959454575309469, 'weight_class_2': 7.421953824702072}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:25,154] Trial 891 finished with value: 0.9497108388193536 and parameters: {'weight_class_0': 0.6153976543315594, 'weight_class_1': 8.911071270858042, 'weight_class_2': 7.393981679550479}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:25,171] Trial 892 finished with value: 0.9061316341517948 and parameters: {'weight_class_0': 5.214951175192032, 'weight_class_1': 8.898285562505718, 'weight_class_2': 7.421972124530566}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:25,203] Trial 893 finished with value: 0.9496575751262927 and parameters: {'weight_class_0': 0.615959657491759, 'weight_class_1': 8.958900327558446, 'weight_class_2': 8.010005436470808}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:25,228] Trial 894 finished with value: 0.9496871267285973 and parameters: {'weight_class_0': 0.6267742493017862, 'weight_class_1': 8.866773970930643, 'weight_class_2': 7.391983788098741}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:25,257] Trial 895 finished with value: 0.9497122801288551 and parameters: {'weight_class_0': 0.6572563942586891, 'weight_class_1': 7.825903675700239, 'weight_class_2': 7.446191818961351}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:25,290] Trial 896 finished with value: 0.9497053568112827 and parameters: {'weight_class_0': 0.6248586241960952, 'weight_class_1': 9.010293658988433, 'weight_class_2': 7.424134585696013}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:25,305] Trial 897 finished with value: 0.9496571846698524 and parameters: {'weight_class_0': 0.6433906819737055, 'weight_class_1': 9.03941702577424, 'weight_class_2': 8.079683449592826}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:25,344] Trial 898 finished with value: 0.9495961854511533 and parameters: {'weight_class_0': 0.5932031114746312, 'weight_class_1': 8.840708211746625, 'weight_class_2': 7.940048781956306}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  30%|████████████████████████████████████████▏                                                                                            | 907/3000 [00:18<00:47, 43.91it/s]

[I 2026-07-10 16:12:25,347] Trial 899 finished with value: 0.9496152071868379 and parameters: {'weight_class_0': 0.5856624817019822, 'weight_class_1': 9.005721846267882, 'weight_class_2': 8.044301200309459}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:25,370] Trial 900 finished with value: 0.949641353704432 and parameters: {'weight_class_0': 0.6046517616253808, 'weight_class_1': 8.956119610411557, 'weight_class_2': 7.9657766998625155}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:25,377] Trial 901 finished with value: 0.9485077196739704 and parameters: {'weight_class_0': 0.3216331607964751, 'weight_class_1': 8.944107578741002, 'weight_class_2': 8.029385150837495}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:25,430] Trial 902 finished with value: 0.9485879427712423 and parameters: {'weight_class_0': 0.32965383157679645, 'weight_class_1': 8.879633227906087, 'weight_class_2': 7.947728468538745}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:25,435] Trial 903 finished with value: 0.9481556130037648 and parameters: {'weight_class_0': 0.2771222914375646, 'weight_class_1': 8.993396723979107, 'weight_class_2': 7.9994647556968275}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:25,472] Trial 905 finished with value: 0.9483357946740759 and parameters: {'weight_class_0': 0.29921662898487783, 'weight_class_1': 9.068241899828731, 'weight_class_2': 7.921543283137194}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:25,478] Trial 904 finished with value: 0.9485458241063904 and parameters: {'weight_class_0': 0.31983691535153835, 'weight_class_1': 8.558664641773797, 'weight_class_2': 8.019265901812764}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:25,507] Trial 906 finished with value: 0.9486100853853364 and parameters: {'weight_class_0': 0.3288866422840878, 'weight_class_1': 8.524944772913669, 'weight_class_2': 7.966914791603393}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:25,545] Trial 907 finished with value: 0.6588640722568258 and parameters: {'weight_class_0': 0.007052134651952424, 'weight_class_1': 8.571666036665148, 'weight_class_2': 7.7694758839154865}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:25,575] Trial 908 finished with value: 0.9485371734791291 and parameters: {'weight_class_0': 0.3167906756642869, 'weight_class_1': 8.538138357940614, 'weight_class_2': 7.938784101319708}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:25,590] Trial 909 finished with value: 0.9487598600584651 and parameters: {'weight_class_0': 0.34621216426778856, 'weight_class_1': 8.578605351131495, 'weight_class_2': 7.698132380753307}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:25,604] Trial 910 finished with value: 0.7742348369499038 and parameters: {'weight_class_0': 0.024191893658276342, 'weight_class_1': 8.55977121922225, 'weight_class_2': 7.712397988423862}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:25,629] Trial 911 finished with value: 0.9486907894964807 and parameters: {'weight_class_0': 0.3377242660709165, 'weight_class_1': 8.555793533907625, 'weight_class_2': 7.704583792448788}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:25,665] Trial 912 finished with value: 0.9482868275848353 and parameters: {'weight_class_0': 0.2839960627274169, 'weight_class_1': 8.538703293912983, 'weight_class_2': 7.748226609314656}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:25,678] Trial 913 finished with value: 0.8871452736171612 and parameters: {'weight_class_0': 6.975318781630293, 'weight_class_1': 8.582351276312554, 'weight_class_2': 7.732826611278296}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:25,701] Trial 915 finished with value: 0.9475036579062187 and parameters: {'weight_class_0': 0.7603163641920221, 'weight_class_1': 3.662873139882644, 'weight_class_2': 7.657810960141062}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:25,708] Trial 914 finished with value: 0.949435995346708 and parameters: {'weight_class_0': 0.8439519835136545, 'weight_class_1': 8.564939128581948, 'weight_class_2': 7.720581623426891}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:25,748] Trial 916 finished with value: 0.9494294742126353 and parameters: {'weight_class_0': 0.8421961516124049, 'weight_class_1': 8.549951468777959, 'weight_class_2': 7.6522628898984975}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  31%|█████████████████████████████████████████                                                                                            | 925/3000 [00:19<00:49, 42.21it/s]

[I 2026-07-10 16:12:25,780] Trial 917 finished with value: 0.9495515565357922 and parameters: {'weight_class_0': 0.7918253530829515, 'weight_class_1': 8.560256685169852, 'weight_class_2': 7.6995615699471385}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:25,802] Trial 918 finished with value: 0.9493148374338533 and parameters: {'weight_class_0': 0.8750570699867035, 'weight_class_1': 8.55228886049382, 'weight_class_2': 7.543903356536897}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:25,835] Trial 919 finished with value: 0.9493825864984476 and parameters: {'weight_class_0': 0.8548318102453771, 'weight_class_1': 8.717170752111219, 'weight_class_2': 7.618651041262931}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:25,847] Trial 920 finished with value: 0.9494864084639868 and parameters: {'weight_class_0': 0.8111581723808311, 'weight_class_1': 8.736797284329585, 'weight_class_2': 7.619194880214789}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:25,865] Trial 921 finished with value: 0.9493975768775534 and parameters: {'weight_class_0': 0.811751996282942, 'weight_class_1': 8.739719984010781, 'weight_class_2': 7.276255325703295}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:25,889] Trial 922 finished with value: 0.9494384712948657 and parameters: {'weight_class_0': 0.8311772322384594, 'weight_class_1': 8.75267021034648, 'weight_class_2': 7.523864913659699}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:25,904] Trial 923 finished with value: 0.9407028373383022 and parameters: {'weight_class_0': 0.89563492107469, 'weight_class_1': 2.275566286169392, 'weight_class_2': 7.334042117884388}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:25,951] Trial 925 finished with value: 0.9493629580257082 and parameters: {'weight_class_0': 0.8363227338766015, 'weight_class_1': 8.75734652193699, 'weight_class_2': 7.313428403996747}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:25,968] Trial 924 finished with value: 0.9493747424765709 and parameters: {'weight_class_0': 0.8274797739104925, 'weight_class_1': 8.762701339548691, 'weight_class_2': 7.255043098695742}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  31%|█████████████████████████████████████████▍                                                                                           | 934/3000 [00:19<00:49, 41.71it/s]

[I 2026-07-10 16:12:25,994] Trial 926 finished with value: 0.9493961470895179 and parameters: {'weight_class_0': 0.8049447500613183, 'weight_class_1': 8.760662323138714, 'weight_class_2': 7.254331843526151}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:26,019] Trial 927 finished with value: 0.945671582485585 and parameters: {'weight_class_0': 1.3238194119340765, 'weight_class_1': 5.636589745056151, 'weight_class_2': 7.2694670664342596}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:26,050] Trial 928 finished with value: 0.9492744388800022 and parameters: {'weight_class_0': 0.8664007817101282, 'weight_class_1': 8.784655186777883, 'weight_class_2': 7.2861236448671605}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:26,074] Trial 930 finished with value: 0.9494440781550063 and parameters: {'weight_class_0': 0.4970596696804434, 'weight_class_1': 9.135624421542644, 'weight_class_2': 7.265197872128661}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:26,116] Trial 929 finished with value: 0.947439720015237 and parameters: {'weight_class_0': 1.3106418193129605, 'weight_class_1': 7.872792516122008, 'weight_class_2': 7.258055220571275}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:26,117] Trial 931 finished with value: 0.9491153468433152 and parameters: {'weight_class_0': 0.5057361108699767, 'weight_class_1': 4.9268265294584825, 'weight_class_2': 7.290812032056473}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:26,144] Trial 932 finished with value: 0.9477531646804745 and parameters: {'weight_class_0': 1.304905961209067, 'weight_class_1': 9.157692331515339, 'weight_class_2': 7.246904355499961}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:26,166] Trial 933 finished with value: 0.9495482122605967 and parameters: {'weight_class_0': 0.5297647219347698, 'weight_class_1': 7.840715815313293, 'weight_class_2': 7.315471869027018}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:26,190] Trial 935 finished with value: 0.9473417939654665 and parameters: {'weight_class_0': 1.3467761980136501, 'weight_class_1': 9.15878144398108, 'weight_class_2': 6.852942345086319}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  31%|█████████████████████████████████████████▊                                                                                           | 943/3000 [00:19<00:47, 43.55it/s]

[I 2026-07-10 16:12:26,201] Trial 934 finished with value: 0.9477158456482808 and parameters: {'weight_class_0': 1.2896624035827964, 'weight_class_1': 8.338700960721498, 'weight_class_2': 7.25743445749526}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:26,202] Trial 936 finished with value: 0.9477764710207032 and parameters: {'weight_class_0': 1.3059612024965785, 'weight_class_1': 8.360232755086308, 'weight_class_2': 7.469320460288032}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:26,250] Trial 937 finished with value: 0.9493401085415499 and parameters: {'weight_class_0': 0.501528404316406, 'weight_class_1': 9.128985314836726, 'weight_class_2': 8.348813677508005}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:26,257] Trial 938 finished with value: 0.9494043932669007 and parameters: {'weight_class_0': 0.5164396521042938, 'weight_class_1': 7.806951561976378, 'weight_class_2': 8.279785844488757}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:26,304] Trial 939 finished with value: 0.9494085603054324 and parameters: {'weight_class_0': 0.5332941291134266, 'weight_class_1': 7.851546880535754, 'weight_class_2': 8.228889946580349}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:26,325] Trial 940 finished with value: 0.9472156421209932 and parameters: {'weight_class_0': 1.325471580116012, 'weight_class_1': 8.334556204548354, 'weight_class_2': 6.852921545628011}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:26,336] Trial 941 finished with value: 0.9494695411741382 and parameters: {'weight_class_0': 0.5678834185261417, 'weight_class_1': 8.363206412867752, 'weight_class_2': 8.299669958234169}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:26,389] Trial 943 finished with value: 0.949628181295244 and parameters: {'weight_class_0': 0.5246085110814592, 'weight_class_1': 8.286702591130176, 'weight_class_2': 6.803065555119621}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:26,413] Trial 942 finished with value: 0.9494139137684678 and parameters: {'weight_class_0': 0.5193801083695265, 'weight_class_1': 8.382740195714495, 'weight_class_2': 8.263397469166689}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  32%|██████████████████████████████████████████▏                                                                                          | 953/3000 [00:19<00:47, 43.44it/s]

[I 2026-07-10 16:12:26,426] Trial 944 finished with value: 0.9494425275012951 and parameters: {'weight_class_0': 0.547054594249849, 'weight_class_1': 8.310844634363354, 'weight_class_2': 8.253421779199906}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:26,452] Trial 945 finished with value: 0.9493867977160505 and parameters: {'weight_class_0': 0.5142058525320942, 'weight_class_1': 8.382675830534149, 'weight_class_2': 8.263208077618211}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:26,475] Trial 946 finished with value: 0.9495138666360292 and parameters: {'weight_class_0': 0.5995079965129212, 'weight_class_1': 8.362737700560029, 'weight_class_2': 8.335360908795922}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:26,494] Trial 947 finished with value: 0.9497073881371646 and parameters: {'weight_class_0': 0.569541001539098, 'weight_class_1': 8.365463660128066, 'weight_class_2': 6.830301217068091}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:26,513] Trial 948 finished with value: 0.9435031134887467 and parameters: {'weight_class_0': 0.12543878280298765, 'weight_class_1': 8.325784251620464, 'weight_class_2': 7.519750276634253}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:26,550] Trial 949 finished with value: 0.9332526126319743 and parameters: {'weight_class_0': 2.8243818231269557, 'weight_class_1': 8.39387081572669, 'weight_class_2': 6.830108628530418}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:26,572] Trial 950 finished with value: 0.9442263812504413 and parameters: {'weight_class_0': 0.1326295149258453, 'weight_class_1': 8.241100962257057, 'weight_class_2': 7.4702886077665305}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:26,581] Trial 951 finished with value: 0.8749466565750138 and parameters: {'weight_class_0': 8.125355191619619, 'weight_class_1': 8.246595155535418, 'weight_class_2': 7.496149034942888}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:26,608] Trial 952 finished with value: 0.9486080829256228 and parameters: {'weight_class_0': 1.0760308230625024, 'weight_class_1': 8.215350510534881, 'weight_class_2': 7.485263765142294}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:26,631] Trial 953 finished with value: 0.9479457666524823 and parameters: {'weight_class_0': 0.24207173385613773, 'weight_class_1': 8.182000711076594, 'weight_class_2': 7.504469600819916}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  32%|██████████████████████████████████████████▌                                                                                          | 961/3000 [00:20<00:47, 43.22it/s]

[I 2026-07-10 16:12:26,643] Trial 954 finished with value: 0.9452649479722638 and parameters: {'weight_class_0': 0.14754039812952158, 'weight_class_1': 8.177974114751372, 'weight_class_2': 7.454592789758241}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:26,678] Trial 955 finished with value: 0.9235355528817063 and parameters: {'weight_class_0': 3.7584883869002677, 'weight_class_1': 8.169345230992343, 'weight_class_2': 7.479243049195728}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:26,707] Trial 956 finished with value: 0.9485508966806115 and parameters: {'weight_class_0': 1.0803463023801565, 'weight_class_1': 8.140626288962608, 'weight_class_2': 7.568895196570206}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:26,715] Trial 957 finished with value: 0.7053987429343648 and parameters: {'weight_class_0': 0.0156746725276542, 'weight_class_1': 8.149114235724527, 'weight_class_2': 7.519804334164067}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:26,764] Trial 958 finished with value: 0.9484218814922986 and parameters: {'weight_class_0': 1.1116047746653939, 'weight_class_1': 8.105022745825735, 'weight_class_2': 7.493334892443308}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:26,796] Trial 960 finished with value: 0.9234567429351825 and parameters: {'weight_class_0': 3.6472360770904526, 'weight_class_1': 7.10992034379, 'weight_class_2': 7.839299526986162}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:26,811] Trial 959 finished with value: 0.9484782836941855 and parameters: {'weight_class_0': 1.1019034710517832, 'weight_class_1': 8.100421288002712, 'weight_class_2': 7.5045002520021}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:26,817] Trial 961 finished with value: 0.948760825527239 and parameters: {'weight_class_0': 1.0204282074067037, 'weight_class_1': 8.104112288161991, 'weight_class_2': 7.829583754247162}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:26,884] Trial 963 finished with value: 0.9250513252738459 and parameters: {'weight_class_0': 3.6914243064789343, 'weight_class_1': 7.906160567226527, 'weight_class_2': 7.809014339297015}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:26,893] Trial 962 finished with value: 0.9486135548721265 and parameters: {'weight_class_0': 1.0503348631607667, 'weight_class_1': 7.9580018573744775, 'weight_class_2': 7.82521426075012}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:26,919] Trial 964 finished with value: 0.9487589104102673 and parameters: {'weight_class_0': 1.0135857406559479, 'weight_class_1': 7.937706887616688, 'weight_class_2': 7.825411365442857}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:26,922] Trial 965 finished with value: 0.9496034440183324 and parameters: {'weight_class_0': 0.7393907745743619, 'weight_class_1': 7.9451232266201, 'weight_class_2': 7.859151040403717}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:26,957] Trial 967 finished with value: 0.949580580938425 and parameters: {'weight_class_0': 0.749595920201116, 'weight_class_1': 7.873159498889931, 'weight_class_2': 7.837188008152301}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:26,969] Trial 966 finished with value: 0.9486336279671416 and parameters: {'weight_class_0': 1.0514333929407362, 'weight_class_1': 7.972940638045718, 'weight_class_2': 7.839085162872412}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:27,001] Trial 968 finished with value: 0.9494029833833745 and parameters: {'weight_class_0': 0.7263853228188492, 'weight_class_1': 7.973648218809056, 'weight_class_2': 6.551166543146764}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:27,011] Trial 969 finished with value: 0.9496091508343486 and parameters: {'weight_class_0': 0.7319206643356762, 'weight_class_1': 7.843851787216364, 'weight_class_2': 7.878446792220409}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:27,022] Trial 970 finished with value: 0.9496388486121056 and parameters: {'weight_class_0': 0.7261217336179904, 'weight_class_1': 7.866562157682814, 'weight_class_2': 7.799775312734183}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:27,047] Trial 971 finished with value: 0.949634646880781 and parameters: {'weight_class_0': 0.7136286434892765, 'weight_class_1': 7.908728536402827, 'weight_class_2': 7.834932699793616}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:27,084] Trial 972 finished with value: 0.9496032660337118 and parameters: {'weight_class_0': 0.7322202321017535, 'weight_class_1': 7.8917251730219675, 'weight_class_2': 7.827722689048144}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:27,095] Trial 973 finished with value: 0.9497050256170891 and parameters: {'weight_class_0': 0.705560767115421, 'weight_class_1': 8.793847017653487, 'weight_class_2': 7.81675247259836}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:27,152] Trial 974 finished with value: 0.9496149225896304 and parameters: {'weight_class_0': 0.7038502555762395, 'weight_class_1': 8.527853195533465, 'weight_class_2': 7.091423929770157}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:27,170] Trial 975 finished with value: 0.949612084185406 and parameters: {'weight_class_0': 0.7322556461142745, 'weight_class_1': 8.851699810965092, 'weight_class_2': 7.075492075719474}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:27,196] Trial 976 finished with value: 0.9495002247880263 and parameters: {'weight_class_0': 0.7290271258313608, 'weight_class_1': 8.836728957088795, 'weight_class_2': 6.496236511145607}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:27,207] Trial 977 finished with value: 0.9491172823068988 and parameters: {'weight_class_0': 0.3925860580420866, 'weight_class_1': 8.875791295828542, 'weight_class_2': 7.137291218166664}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:27,218] Trial 978 finished with value: 0.9486186946273861 and parameters: {'weight_class_0': 0.3184715452043353, 'weight_class_1': 8.792560268607817, 'weight_class_2': 7.129540057435379}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:27,243] Trial 979 finished with value: 0.9493074871374536 and parameters: {'weight_class_0': 0.43068592659461263, 'weight_class_1': 8.823043145859737, 'weight_class_2': 7.083676664564817}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:27,250] Trial 980 finished with value: 0.949015545894848 and parameters: {'weight_class_0': 0.3733210764470881, 'weight_class_1': 8.511816029031408, 'weight_class_2': 7.1575950770256735}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:27,304] Trial 981 finished with value: 0.94915857792077 and parameters: {'weight_class_0': 0.3919748301073392, 'weight_class_1': 8.519108776777044, 'weight_class_2': 7.042557151226791}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:27,324] Trial 982 finished with value: 0.9490590899298748 and parameters: {'weight_class_0': 0.3773408048121099, 'weight_class_1': 8.577573247733202, 'weight_class_2': 7.029191590367212}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:27,363] Trial 983 finished with value: 0.9491013430508334 and parameters: {'weight_class_0': 0.3817846173148579, 'weight_class_1': 8.535135799883266, 'weight_class_2': 7.0418291379094935}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:27,380] Trial 985 finished with value: 0.9489465778152343 and parameters: {'weight_class_0': 0.36105806301997423, 'weight_class_1': 8.530869659842931, 'weight_class_2': 7.012961661266405}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:27,406] Trial 984 finished with value: 0.9490200114419745 and parameters: {'weight_class_0': 0.37153728360370925, 'weight_class_1': 8.508680354414295, 'weight_class_2': 7.0248691487865}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:27,432] Trial 986 finished with value: 0.9486877139481854 and parameters: {'weight_class_0': 0.317281936636505, 'weight_class_1': 8.533960140259188, 'weight_class_2': 6.974054096498386}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:27,456] Trial 987 finished with value: 0.9488277891148739 and parameters: {'weight_class_0': 0.3580832424317168, 'weight_class_1': 8.538823323777825, 'weight_class_2': 7.640546876742789}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:27,468] Trial 988 finished with value: 0.9491695116619795 and parameters: {'weight_class_0': 0.38412852317613605, 'weight_class_1': 8.517110819950192, 'weight_class_2': 6.904626798350647}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  33%|████████████████████████████████████████████▏                                                                                        | 998/3000 [00:20<00:46, 42.63it/s]

[I 2026-07-10 16:12:27,524] Trial 989 finished with value: 0.9486647159676728 and parameters: {'weight_class_0': 0.3477855214454854, 'weight_class_1': 8.473630185300346, 'weight_class_2': 8.122580659848298}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:27,531] Trial 991 finished with value: 0.9483319695394054 and parameters: {'weight_class_0': 0.2996996830948762, 'weight_class_1': 4.400742245163227, 'weight_class_2': 7.643110575636511}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:27,532] Trial 990 finished with value: 0.9487203370510856 and parameters: {'weight_class_0': 0.356408729978161, 'weight_class_1': 8.51519082748458, 'weight_class_2': 8.112862809974889}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:27,554] Trial 992 finished with value: 0.9487681703474221 and parameters: {'weight_class_0': 0.3645100121420674, 'weight_class_1': 8.501479182131536, 'weight_class_2': 8.103152774402293}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:27,572] Trial 993 finished with value: 0.9450236357573903 and parameters: {'weight_class_0': 0.15738572780285087, 'weight_class_1': 9.115700851816559, 'weight_class_2': 7.653216997244462}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:27,615] Trial 995 finished with value: 0.9493475284624401 and parameters: {'weight_class_0': 0.8845967844099062, 'weight_class_1': 9.20413381844783, 'weight_class_2': 7.630892669373368}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:27,618] Trial 994 finished with value: 0.9492217225999781 and parameters: {'weight_class_0': 0.913756248328527, 'weight_class_1': 9.057368510283544, 'weight_class_2': 7.631700312921215}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:27,666] Trial 996 finished with value: 0.9458283408018024 and parameters: {'weight_class_0': 1.703344888398076, 'weight_class_1': 9.031464972983866, 'weight_class_2': 7.6441764921736315}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:27,694] Trial 997 finished with value: 0.9461847088280266 and parameters: {'weight_class_0': 1.7074681493492334, 'weight_class_1': 9.107515873679603, 'weight_class_2': 8.129324248337044}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:27,702] Trial 998 finished with value: 0.949342039317452 and parameters: {'weight_class_0': 0.9245203414291989, 'weight_class_1': 9.210806192319096, 'weight_class_2': 8.096213804868771}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  34%|████████████████████████████████████████████▎                                                                                       | 1007/3000 [00:21<00:47, 42.32it/s]

[I 2026-07-10 16:12:27,730] Trial 999 finished with value: 0.9493018705651611 and parameters: {'weight_class_0': 0.9300580567929259, 'weight_class_1': 9.164184464513951, 'weight_class_2': 8.104734518692009}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:27,739] Trial 1000 finished with value: 0.9495399530767168 and parameters: {'weight_class_0': 0.5876600135044172, 'weight_class_1': 7.611849870270951, 'weight_class_2': 8.125224541616248}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:27,775] Trial 1001 finished with value: 0.9489531369108469 and parameters: {'weight_class_0': 0.9483218856452743, 'weight_class_1': 8.717600736970713, 'weight_class_2': 7.381311123821313}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:27,801] Trial 1002 finished with value: 0.9490271807055614 and parameters: {'weight_class_0': 0.9334262506980916, 'weight_class_1': 9.110076952719332, 'weight_class_2': 7.367376174855477}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:27,830] Trial 1003 finished with value: 0.9488550488442419 and parameters: {'weight_class_0': 1.0104686529000986, 'weight_class_1': 8.713824250202897, 'weight_class_2': 7.382741778508527}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:27,863] Trial 1004 finished with value: 0.9406571846452731 and parameters: {'weight_class_0': 2.147964264046491, 'weight_class_1': 7.60077082909832, 'weight_class_2': 7.315557285057839}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:27,880] Trial 1005 finished with value: 0.9497286477261682 and parameters: {'weight_class_0': 0.6049765962851849, 'weight_class_1': 7.642928982091312, 'weight_class_2': 7.357481449955906}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:27,903] Trial 1006 finished with value: 0.9497064799335534 and parameters: {'weight_class_0': 0.6116385265804162, 'weight_class_1': 7.54507585674652, 'weight_class_2': 7.3709906799586555}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:27,923] Trial 1007 finished with value: 0.9497550650936848 and parameters: {'weight_class_0': 0.6220494666827825, 'weight_class_1': 8.201213431986455, 'weight_class_2': 7.385796212232936}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  34%|████████████████████████████████████████████▋                                                                                       | 1016/3000 [00:21<00:46, 42.57it/s]

[I 2026-07-10 16:12:27,949] Trial 1008 finished with value: 0.9497177567321243 and parameters: {'weight_class_0': 0.6190747089529589, 'weight_class_1': 8.73937898093752, 'weight_class_2': 7.382399584199336}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:27,984] Trial 1010 finished with value: 0.9497368480589876 and parameters: {'weight_class_0': 0.6215339187640215, 'weight_class_1': 8.690084856407752, 'weight_class_2': 7.360115657964874}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:27,986] Trial 1009 finished with value: 0.9496884702742646 and parameters: {'weight_class_0': 0.5894978728776886, 'weight_class_1': 8.710064112786693, 'weight_class_2': 7.3342853719137455}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:28,006] Trial 1011 finished with value: 0.9493836775490383 and parameters: {'weight_class_0': 0.6055450905470694, 'weight_class_1': 8.232685627758716, 'weight_class_2': 5.063160157892074}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:28,048] Trial 1012 finished with value: 0.9497009854247892 and parameters: {'weight_class_0': 0.6615242945025372, 'weight_class_1': 8.233010898347034, 'weight_class_2': 7.368475033368443}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:28,060] Trial 1013 finished with value: 0.9496303504748402 and parameters: {'weight_class_0': 0.5547386415349925, 'weight_class_1': 8.182354195878501, 'weight_class_2': 7.369932649784224}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:28,096] Trial 1014 finished with value: 0.949758704089426 and parameters: {'weight_class_0': 0.6110499363301273, 'weight_class_1': 8.22014559272077, 'weight_class_2': 7.386699592032509}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:28,124] Trial 1015 finished with value: 0.9496919252382057 and parameters: {'weight_class_0': 0.5911284031598462, 'weight_class_1': 7.044272276714713, 'weight_class_2': 7.261574681412711}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:28,147] Trial 1016 finished with value: 0.9496722184413633 and parameters: {'weight_class_0': 0.5859997019223191, 'weight_class_1': 7.239391975769547, 'weight_class_2': 7.25513815551961}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  34%|█████████████████████████████████████████████                                                                                       | 1025/3000 [00:21<00:46, 42.10it/s]

[I 2026-07-10 16:12:28,164] Trial 1017 finished with value: 0.8796643251168499 and parameters: {'weight_class_0': 0.041021405843752246, 'weight_class_1': 8.135032691598035, 'weight_class_2': 7.21575063089024}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:28,198] Trial 1018 finished with value: 0.8954574518354455 and parameters: {'weight_class_0': 0.041994650362307095, 'weight_class_1': 6.890601233534183, 'weight_class_2': 7.209055080505198}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:28,232] Trial 1019 finished with value: 0.8876538098595578 and parameters: {'weight_class_0': 6.0237972617076085, 'weight_class_1': 7.3358557268565745, 'weight_class_2': 6.821694142966722}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:28,256] Trial 1021 finished with value: 0.8831800558765028 and parameters: {'weight_class_0': 6.233954919186278, 'weight_class_1': 7.069703094232817, 'weight_class_2': 6.653772893537678}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:28,260] Trial 1020 finished with value: 0.9383560089307869 and parameters: {'weight_class_0': 0.08324579608058214, 'weight_class_1': 7.36138171604543, 'weight_class_2': 6.60085727394408}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:28,291] Trial 1022 finished with value: 0.8487787726552624 and parameters: {'weight_class_0': 0.031528693930023444, 'weight_class_1': 7.259265811486228, 'weight_class_2': 7.204424869040981}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:28,318] Trial 1023 finished with value: 0.8251323328765975 and parameters: {'weight_class_0': 0.02771474856038314, 'weight_class_1': 7.5572801718737015, 'weight_class_2': 6.8519647306321465}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:28,332] Trial 1025 finished with value: 0.871568953482849 and parameters: {'weight_class_0': 0.0375535074627118, 'weight_class_1': 8.098804600916234, 'weight_class_2': 6.660898275455947}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:28,373] Trial 1024 finished with value: 0.9439139593322331 and parameters: {'weight_class_0': 0.1251038721409553, 'weight_class_1': 8.147771560040473, 'weight_class_2': 6.774001290229453}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  34%|█████████████████████████████████████████████▌                                                                                      | 1035/3000 [00:21<00:47, 41.40it/s]

[I 2026-07-10 16:12:28,397] Trial 1026 finished with value: 0.8907472898929036 and parameters: {'weight_class_0': 6.071093701455087, 'weight_class_1': 8.150059221507572, 'weight_class_2': 6.862298993386712}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:28,417] Trial 1027 finished with value: 0.9434795176069005 and parameters: {'weight_class_0': 0.11821242885719374, 'weight_class_1': 7.7968825046147145, 'weight_class_2': 7.18949610634108}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:28,427] Trial 1028 finished with value: 0.9446913628330557 and parameters: {'weight_class_0': 0.1342691663882477, 'weight_class_1': 8.085835151515925, 'weight_class_2': 6.693088639217232}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:28,464] Trial 1029 finished with value: 0.9467341621041143 and parameters: {'weight_class_0': 0.1785580727829103, 'weight_class_1': 8.08854112640899, 'weight_class_2': 6.608201911181496}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:28,469] Trial 1030 finished with value: 0.8903655582691599 and parameters: {'weight_class_0': 6.024010513359227, 'weight_class_1': 8.07623563811452, 'weight_class_2': 6.756710418773011}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:28,501] Trial 1031 finished with value: 0.9478926249148351 and parameters: {'weight_class_0': 0.227424767082205, 'weight_class_1': 7.760661747663464, 'weight_class_2': 7.172114864467129}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:28,531] Trial 1032 finished with value: 0.9491730933355784 and parameters: {'weight_class_0': 0.8341292063538691, 'weight_class_1': 8.103607190151488, 'weight_class_2': 6.921775771024532}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:28,555] Trial 1033 finished with value: 0.9493892961516658 and parameters: {'weight_class_0': 0.7990417271501635, 'weight_class_1': 8.069593710996358, 'weight_class_2': 7.025331013029215}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:28,572] Trial 1035 finished with value: 0.9491391730658373 and parameters: {'weight_class_0': 0.830940219226522, 'weight_class_1': 7.7239685086617405, 'weight_class_2': 6.912179930297351}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:28,586] Trial 1034 finished with value: 0.949275724355957 and parameters: {'weight_class_0': 0.8086257415014879, 'weight_class_1': 7.77283749868558, 'weight_class_2': 6.884832111191091}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  35%|█████████████████████████████████████████████▉                                                                                      | 1044/3000 [00:22<00:48, 40.67it/s]

[I 2026-07-10 16:12:28,623] Trial 1036 finished with value: 0.9493096121046672 and parameters: {'weight_class_0': 0.8070458814650555, 'weight_class_1': 7.766252640252757, 'weight_class_2': 7.166087257793384}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:28,648] Trial 1037 finished with value: 0.949177549026731 and parameters: {'weight_class_0': 0.8388874591239568, 'weight_class_1': 7.72542517703371, 'weight_class_2': 7.115314158061688}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:28,667] Trial 1038 finished with value: 0.9494276312003057 and parameters: {'weight_class_0': 0.8170041942433366, 'weight_class_1': 8.39592206348328, 'weight_class_2': 7.466268018882028}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:28,708] Trial 1039 finished with value: 0.9493419275264022 and parameters: {'weight_class_0': 0.8373448013301876, 'weight_class_1': 8.3768390511568, 'weight_class_2': 7.149949500031257}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:28,736] Trial 1040 finished with value: 0.9493058325361546 and parameters: {'weight_class_0': 0.8569354957087894, 'weight_class_1': 8.33897147467728, 'weight_class_2': 7.48736472996055}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:28,759] Trial 1042 finished with value: 0.9494661605893975 and parameters: {'weight_class_0': 0.4807726078070565, 'weight_class_1': 8.318199755817334, 'weight_class_2': 7.495544049456318}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:28,760] Trial 1041 finished with value: 0.9493780245856148 and parameters: {'weight_class_0': 0.8363678519625325, 'weight_class_1': 8.3938589567521, 'weight_class_2': 7.483026361605051}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:28,812] Trial 1043 finished with value: 0.9494106705644837 and parameters: {'weight_class_0': 0.46746790585340636, 'weight_class_1': 8.409666591506413, 'weight_class_2': 7.515417281356223}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:28,842] Trial 1044 finished with value: 0.9494596681342496 and parameters: {'weight_class_0': 0.4849748668974972, 'weight_class_1': 8.325520872914847, 'weight_class_2': 7.454883825928746}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  35%|██████████████████████████████████████████████▎                                                                                     | 1052/3000 [00:22<00:50, 38.75it/s]

[I 2026-07-10 16:12:28,846] Trial 1045 finished with value: 0.9495674902022083 and parameters: {'weight_class_0': 0.5399568866146771, 'weight_class_1': 8.375943712266773, 'weight_class_2': 7.497773005139991}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:28,852] Trial 1046 finished with value: 0.9494596681342496 and parameters: {'weight_class_0': 0.48612081727794415, 'weight_class_1': 8.343717329474298, 'weight_class_2': 7.4723066188526674}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:28,879] Trial 1048 finished with value: 0.9494257095685148 and parameters: {'weight_class_0': 0.4681942838821421, 'weight_class_1': 8.422108275392926, 'weight_class_2': 7.469800087480912}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:28,908] Trial 1047 finished with value: 0.9493416103314307 and parameters: {'weight_class_0': 0.4397862645013684, 'weight_class_1': 8.364471209651645, 'weight_class_2': 7.4405729715001065}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:28,958] Trial 1050 finished with value: 0.9316969096523593 and parameters: {'weight_class_0': 0.47362138194178405, 'weight_class_1': 0.811934827184075, 'weight_class_2': 2.9211924530111966}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:28,988] Trial 1049 finished with value: 0.9492052321968845 and parameters: {'weight_class_0': 0.4126098020216118, 'weight_class_1': 8.355181909690359, 'weight_class_2': 7.528689657488341}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:29,000] Trial 1051 finished with value: 0.9493392699624293 and parameters: {'weight_class_0': 0.45018830325076264, 'weight_class_1': 8.309607801184717, 'weight_class_2': 7.4801008285249315}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:29,040] Trial 1052 finished with value: 0.9483351777002501 and parameters: {'weight_class_0': 1.1458844862985296, 'weight_class_1': 8.382690085744468, 'weight_class_2': 7.363868890591805}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  35%|██████████████████████████████████████████████▋                                                                                     | 1061/3000 [00:22<00:46, 41.69it/s]

[I 2026-07-10 16:12:29,054] Trial 1053 finished with value: 0.9493521222182185 and parameters: {'weight_class_0': 0.4570485564830919, 'weight_class_1': 8.323576032252822, 'weight_class_2': 7.562841261906727}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:29,058] Trial 1054 finished with value: 0.9482348474937213 and parameters: {'weight_class_0': 1.1580288998876842, 'weight_class_1': 8.273964920169849, 'weight_class_2': 7.593459263321728}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:29,073] Trial 1055 finished with value: 0.949435659130906 and parameters: {'weight_class_0': 0.507207940256599, 'weight_class_1': 8.284384134906135, 'weight_class_2': 7.621544968931389}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:29,090] Trial 1056 finished with value: 0.9483418679832222 and parameters: {'weight_class_0': 1.1004086599080756, 'weight_class_1': 7.997330184349719, 'weight_class_2': 7.183714233765165}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:29,133] Trial 1057 finished with value: 0.9480045712017522 and parameters: {'weight_class_0': 1.1935588455664183, 'weight_class_1': 8.01480198316739, 'weight_class_2': 7.189399072853442}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:29,153] Trial 1058 finished with value: 0.9480408837602313 and parameters: {'weight_class_0': 1.1819360811118207, 'weight_class_1': 7.99481840037607, 'weight_class_2': 7.231098201365988}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:29,197] Trial 1059 finished with value: 0.9478405089849143 and parameters: {'weight_class_0': 1.2463957206780214, 'weight_class_1': 7.981966217849719, 'weight_class_2': 7.226137588922575}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:29,210] Trial 1060 finished with value: 0.9480971184092261 and parameters: {'weight_class_0': 1.1604691117535113, 'weight_class_1': 7.975114613219702, 'weight_class_2': 7.21686265429139}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:29,263] Trial 1062 finished with value: 0.9129670075857853 and parameters: {'weight_class_0': 4.38583054199024, 'weight_class_1': 7.949498927122186, 'weight_class_2': 7.240223933761835}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  36%|███████████████████████████████████████████████                                                                                     | 1070/3000 [00:22<00:47, 40.32it/s]

[I 2026-07-10 16:12:29,271] Trial 1061 finished with value: 0.9483821325254649 and parameters: {'weight_class_0': 1.1210024885630627, 'weight_class_1': 8.638615807934556, 'weight_class_2': 7.172273011947373}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:29,314] Trial 1064 finished with value: 0.9484939182221953 and parameters: {'weight_class_0': 1.0673825356965483, 'weight_class_1': 7.986836039762086, 'weight_class_2': 7.2635486930253075}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:29,328] Trial 1065 finished with value: 0.9476169360841512 and parameters: {'weight_class_0': 0.6817465983020767, 'weight_class_1': 3.3095218367039854, 'weight_class_2': 7.195665077935262}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:29,345] Trial 1063 finished with value: 0.9482311902507835 and parameters: {'weight_class_0': 1.1179172396466228, 'weight_class_1': 8.002124069477771, 'weight_class_2': 7.273637073124337}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:29,362] Trial 1066 finished with value: 0.9486387707314982 and parameters: {'weight_class_0': 1.0724279515128794, 'weight_class_1': 8.679208978748518, 'weight_class_2': 7.20849985740919}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:29,408] Trial 1067 finished with value: 0.9496982312557392 and parameters: {'weight_class_0': 0.6784079897833516, 'weight_class_1': 8.664550241765737, 'weight_class_2': 7.259596609497197}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:29,410] Trial 1068 finished with value: 0.9496525788993702 and parameters: {'weight_class_0': 0.6947881661548161, 'weight_class_1': 8.649912922938594, 'weight_class_2': 7.184274177642399}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:29,428] Trial 1070 finished with value: 0.9141019206662769 and parameters: {'weight_class_0': 4.387485658956845, 'weight_class_1': 8.66314177498317, 'weight_class_2': 6.988325411629047}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:29,464] Trial 1069 finished with value: 0.9497392720540971 and parameters: {'weight_class_0': 0.681158477342693, 'weight_class_1': 8.666971139770986, 'weight_class_2': 7.718389861020454}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  36%|███████████████████████████████████████████████▍                                                                                    | 1079/3000 [00:22<00:47, 40.55it/s]

[I 2026-07-10 16:12:29,491] Trial 1071 finished with value: 0.9496983386289282 and parameters: {'weight_class_0': 0.6937647550161784, 'weight_class_1': 8.639607751720972, 'weight_class_2': 7.684390196748462}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:29,501] Trial 1072 finished with value: 0.9497297090442691 and parameters: {'weight_class_0': 0.6775845756240213, 'weight_class_1': 8.652646338224521, 'weight_class_2': 7.687833497030858}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:29,517] Trial 1073 finished with value: 0.9497394032153927 and parameters: {'weight_class_0': 0.6818916381551658, 'weight_class_1': 8.649966470111517, 'weight_class_2': 7.64355508915986}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:29,567] Trial 1074 finished with value: 0.9496789542315837 and parameters: {'weight_class_0': 0.6508170615447907, 'weight_class_1': 8.623746565372896, 'weight_class_2': 6.952527335005468}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:29,576] Trial 1075 finished with value: 0.9497112872504238 and parameters: {'weight_class_0': 0.6905794811752657, 'weight_class_1': 8.703348044665184, 'weight_class_2': 7.648102122571061}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:29,615] Trial 1076 finished with value: 0.9497242903051192 and parameters: {'weight_class_0': 0.668020023824315, 'weight_class_1': 8.62208759126318, 'weight_class_2': 7.651240274982837}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:29,646] Trial 1077 finished with value: 0.9477796510537716 and parameters: {'weight_class_0': 0.2451745295558463, 'weight_class_1': 8.840836408538067, 'weight_class_2': 7.730723153362787}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:29,662] Trial 1078 finished with value: 0.9497557842718808 and parameters: {'weight_class_0': 0.6820499601850187, 'weight_class_1': 8.876173570125209, 'weight_class_2': 7.679195455747788}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:29,703] Trial 1080 finished with value: 0.9483724103646035 and parameters: {'weight_class_0': 0.2948189162575143, 'weight_class_1': 8.884399688698608, 'weight_class_2': 7.660235636214931}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  36%|███████████████████████████████████████████████▊                                                                                    | 1087/3000 [00:23<00:46, 41.40it/s]

[I 2026-07-10 16:12:29,709] Trial 1079 finished with value: 0.9477792977047117 and parameters: {'weight_class_0': 0.27675184988541596, 'weight_class_1': 8.856517734150056, 'weight_class_2': 1.5133296481090754}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:29,731] Trial 1081 finished with value: 0.948413929087616 and parameters: {'weight_class_0': 0.2992704628712839, 'weight_class_1': 8.868396263715024, 'weight_class_2': 7.682528327726473}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:29,761] Trial 1082 finished with value: 0.9478552461474367 and parameters: {'weight_class_0': 0.23926252235182083, 'weight_class_1': 8.204444522700863, 'weight_class_2': 7.689582407701269}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:29,787] Trial 1083 finished with value: 0.9247037965272494 and parameters: {'weight_class_0': 0.9836673037531574, 'weight_class_1': 8.231491063194207, 'weight_class_2': 1.4633028817461096}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:29,823] Trial 1085 finished with value: 0.9475576456297251 and parameters: {'weight_class_0': 0.22406557813108052, 'weight_class_1': 2.9314471681125034, 'weight_class_2': 7.665873524526309}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:29,825] Trial 1084 finished with value: 0.9483805756629287 and parameters: {'weight_class_0': 0.2902933358723037, 'weight_class_1': 8.462340786717139, 'weight_class_2': 7.717170647712001}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:29,896] Trial 1086 finished with value: 0.9482542659159435 and parameters: {'weight_class_0': 0.27420572220410266, 'weight_class_1': 8.16573001006093, 'weight_class_2': 7.5765178717067405}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:29,903] Trial 1088 finished with value: 0.9488888192609922 and parameters: {'weight_class_0': 0.9803356854735168, 'weight_class_1': 8.201682564403544, 'weight_class_2': 7.577511041359144}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  37%|████████████████████████████████████████████████▎                                                                                   | 1097/3000 [00:23<00:49, 38.41it/s]

[I 2026-07-10 16:12:29,912] Trial 1087 finished with value: 0.947707863290088 and parameters: {'weight_class_0': 0.23226121416164847, 'weight_class_1': 8.194502496182889, 'weight_class_2': 7.656842366987148}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:29,932] Trial 1089 finished with value: 0.9490666928367141 and parameters: {'weight_class_0': 0.9444717833834662, 'weight_class_1': 8.49623403967641, 'weight_class_2': 7.70231996047832}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:29,962] Trial 1090 finished with value: 0.9426378248646112 and parameters: {'weight_class_0': 0.9333965682242169, 'weight_class_1': 2.7045251557701464, 'weight_class_2': 7.732357101958193}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:30,006] Trial 1092 finished with value: 0.8878051515066584 and parameters: {'weight_class_0': 0.90682260045467, 'weight_class_1': 8.959243089097534, 'weight_class_2': 0.08471559855219013}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:30,023] Trial 1091 finished with value: 0.9492200609698765 and parameters: {'weight_class_0': 0.9383853723381512, 'weight_class_1': 8.990792785189914, 'weight_class_2': 7.8894090750443}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:30,030] Trial 1093 finished with value: 0.9430909873986533 and parameters: {'weight_class_0': 0.9104407410082578, 'weight_class_1': 2.718178563031603, 'weight_class_2': 7.903439855119382}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:30,063] Trial 1094 finished with value: 0.9492652264013021 and parameters: {'weight_class_0': 0.93677587618918, 'weight_class_1': 8.926285313456617, 'weight_class_2': 7.975918888443582}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:30,084] Trial 1095 finished with value: 0.9491423746790165 and parameters: {'weight_class_0': 0.9484244984422598, 'weight_class_1': 8.90655811508947, 'weight_class_2': 7.859572095475213}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:30,104] Trial 1096 finished with value: 0.9493326966977089 and parameters: {'weight_class_0': 0.9027160947629997, 'weight_class_1': 8.895009152668523, 'weight_class_2': 7.995773255522337}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:30,112] Trial 1097 finished with value: 0.949296148899556 and parameters: {'weight_class_0': 0.9156904914827267, 'weight_class_1': 8.877079415787627, 'weight_class_2': 7.950423263270198}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:30,167] Trial 1098 finished with value: 0.9494069999931612 and parameters: {'weight_class_0': 0.8771708084778571, 'weight_class_1': 9.03675398708218, 'weight_class_2': 7.950130009838486}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:30,190] Trial 1099 finished with value: 0.9493767050954185 and parameters: {'weight_class_0': 0.8918556489072904, 'weight_class_1': 8.864612108171691, 'weight_class_2': 7.917290623896143}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:30,204] Trial 1100 finished with value: 0.9496022005776807 and parameters: {'weight_class_0': 0.7995882625513118, 'weight_class_1': 8.914551462807403, 'weight_class_2': 7.960540280931081}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:30,271] Trial 1102 finished with value: 0.9471486269070498 and parameters: {'weight_class_0': 1.4971587360862793, 'weight_class_1': 8.801701693247852, 'weight_class_2': 7.943243383284271}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:30,272] Trial 1101 finished with value: 0.9472726472178289 and parameters: {'weight_class_0': 1.4828636813039908, 'weight_class_1': 8.845808224667637, 'weight_class_2': 7.967178934950938}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:30,346] Trial 1104 finished with value: 0.9495261025376948 and parameters: {'weight_class_0': 0.5220103927371589, 'weight_class_1': 8.49240767453643, 'weight_class_2': 7.411376485759929}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:30,350] Trial 1105 finished with value: 0.9486448876115808 and parameters: {'weight_class_0': 0.6195504843552913, 'weight_class_1': 3.951265167625878, 'weight_class_2': 7.377741506831879}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:30,360] Trial 1106 finished with value: 0.9496652936305804 and parameters: {'weight_class_0': 0.5899569774432538, 'weight_class_1': 8.493885040478053, 'weight_class_2': 7.416492234509142}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:30,365] Trial 1103 finished with value: 0.9496090567687986 and parameters: {'weight_class_0': 0.5442844397649867, 'weight_class_1': 8.784038372796966, 'weight_class_2': 7.414701210325978}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:30,371] Trial 1107 finished with value: 0.9496380566430025 and parameters: {'weight_class_0': 0.5551157999964401, 'weight_class_1': 8.500099212579, 'weight_class_2': 7.4164334083709615}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:30,397] Trial 1108 finished with value: 0.9496423687749628 and parameters: {'weight_class_0': 0.595321897161236, 'weight_class_1': 8.539853848458925, 'weight_class_2': 7.506710380161222}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:30,455] Trial 1109 finished with value: 0.9495294672859057 and parameters: {'weight_class_0': 0.5322280014659857, 'weight_class_1': 8.503499218837511, 'weight_class_2': 7.540899344328016}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:30,457] Trial 1110 finished with value: 0.9496418572805649 and parameters: {'weight_class_0': 0.5646615306801485, 'weight_class_1': 8.501481629971801, 'weight_class_2': 7.386851654928905}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:30,488] Trial 1111 finished with value: 0.9469715988417727 and parameters: {'weight_class_0': 1.4494127317876664, 'weight_class_1': 8.493759524940016, 'weight_class_2': 7.398372779289764}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:30,529] Trial 1112 finished with value: 0.9495722239829972 and parameters: {'weight_class_0': 0.5319357226283781, 'weight_class_1': 8.49172890621846, 'weight_class_2': 7.399892346397475}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:30,536] Trial 1113 finished with value: 0.9496556505978454 and parameters: {'weight_class_0': 0.5718612578193327, 'weight_class_1': 8.455114222770687, 'weight_class_2': 7.403837968508547}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:30,592] Trial 1114 finished with value: 0.9495144039180136 and parameters: {'weight_class_0': 0.5111402484555846, 'weight_class_1': 8.489235931615783, 'weight_class_2': 7.416277991059627}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:30,600] Trial 1115 finished with value: 0.9496109441730408 and parameters: {'weight_class_0': 0.7024967047885853, 'weight_class_1': 8.421828864927695, 'weight_class_2': 6.980260223735153}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:30,609] Trial 1116 finished with value: 0.9494845891369671 and parameters: {'weight_class_0': 0.7556867146025384, 'weight_class_1': 8.649270719027522, 'weight_class_2': 6.9489428787967835}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:30,672] Trial 1117 finished with value: 0.9492717336317013 and parameters: {'weight_class_0': 0.7341317123972736, 'weight_class_1': 6.504635571146469, 'weight_class_2': 6.986202129140395}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:30,696] Trial 1118 finished with value: 0.9496119790867752 and parameters: {'weight_class_0': 0.729148431965525, 'weight_class_1': 8.178545838651969, 'weight_class_2': 7.042770931624317}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:30,708] Trial 1119 finished with value: 0.9489492556673751 and parameters: {'weight_class_0': 0.3747489080123846, 'weight_class_1': 7.812620717167013, 'weight_class_2': 7.6589550943621925}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:30,721] Trial 1120 finished with value: 0.9494685266378707 and parameters: {'weight_class_0': 0.7707239270522768, 'weight_class_1': 8.208389621770447, 'weight_class_2': 7.029490853053746}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:30,756] Trial 1121 finished with value: 0.8648270922020834 and parameters: {'weight_class_0': 9.057547515148705, 'weight_class_1': 8.240054101727631, 'weight_class_2': 6.096423721780335}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:30,769] Trial 1122 finished with value: 0.9496289611338146 and parameters: {'weight_class_0': 0.7408422503173692, 'weight_class_1': 8.19071180950604, 'weight_class_2': 7.730190491677117}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:30,812] Trial 1123 finished with value: 0.9495627162079966 and parameters: {'weight_class_0': 0.7330223692361048, 'weight_class_1': 8.168115568214974, 'weight_class_2': 6.993927936870996}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:30,823] Trial 1124 finished with value: 0.9494928585136702 and parameters: {'weight_class_0': 0.7495061195176265, 'weight_class_1': 8.258780265355696, 'weight_class_2': 7.014271577939783}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:30,849] Trial 1125 finished with value: 0.9493087834843171 and parameters: {'weight_class_0': 0.8186968763934592, 'weight_class_1': 8.166319983119553, 'weight_class_2': 6.945523472243136}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:30,884] Trial 1126 finished with value: 0.9496405841484493 and parameters: {'weight_class_0': 0.7360455064522903, 'weight_class_1': 8.18160155029634, 'weight_class_2': 7.695943752471043}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:30,906] Trial 1127 finished with value: 0.9491485546475591 and parameters: {'weight_class_0': 0.7609977123948541, 'weight_class_1': 6.018474848937408, 'weight_class_2': 7.6824204722984675}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:30,930] Trial 1129 finished with value: 0.8696791892580075 and parameters: {'weight_class_0': 8.99441856970601, 'weight_class_1': 8.173435756020702, 'weight_class_2': 7.615117558062735}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:30,936] Trial 1128 finished with value: 0.9489989285784336 and parameters: {'weight_class_0': 0.3904750279987147, 'weight_class_1': 8.19019913297704, 'weight_class_2': 7.646838686257303}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:30,969] Trial 1130 finished with value: 0.9486320170024714 and parameters: {'weight_class_0': 1.069780677401293, 'weight_class_1': 8.198057037389157, 'weight_class_2': 7.7568804870257075}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:31,013] Trial 1131 finished with value: 0.948797733669072 and parameters: {'weight_class_0': 0.3587221896043438, 'weight_class_1': 8.716941774263034, 'weight_class_2': 7.747843867124139}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:31,035] Trial 1132 finished with value: 0.9490296688797999 and parameters: {'weight_class_0': 0.39102394313345407, 'weight_class_1': 7.809075855885429, 'weight_class_2': 7.728562867861159}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:31,069] Trial 1133 finished with value: 0.9402359003634961 and parameters: {'weight_class_0': 0.3923491494886089, 'weight_class_1': 7.838550699960652, 'weight_class_2': 0.9742138884653082}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:31,093] Trial 1134 finished with value: 0.9488454393045171 and parameters: {'weight_class_0': 0.3601605462242604, 'weight_class_1': 7.797566539319314, 'weight_class_2': 7.7146164126196775}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:31,100] Trial 1135 finished with value: 0.9490165701712608 and parameters: {'weight_class_0': 0.3962106784329168, 'weight_class_1': 8.695352316149302, 'weight_class_2': 7.7511018878313385}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:31,110] Trial 1136 finished with value: 0.9491658776598534 and parameters: {'weight_class_0': 0.41909371495336206, 'weight_class_1': 8.69386578229613, 'weight_class_2': 7.73067923130024}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:31,145] Trial 1137 finished with value: 0.9489578361277036 and parameters: {'weight_class_0': 0.3825831018740839, 'weight_class_1': 8.705017343918565, 'weight_class_2': 7.624816346893355}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:31,202] Trial 1138 finished with value: 0.9481180603582939 and parameters: {'weight_class_0': 1.154020639311709, 'weight_class_1': 7.848694219394935, 'weight_class_2': 7.279546529646016}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  38%|██████████████████████████████████████████████████▍                                                                                 | 1147/3000 [00:24<00:46, 39.73it/s]

[I 2026-07-10 16:12:31,208] Trial 1139 finished with value: 0.9486111103962876 and parameters: {'weight_class_0': 1.081360428027365, 'weight_class_1': 8.684533433282208, 'weight_class_2': 7.271088339800842}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:31,232] Trial 1140 finished with value: 0.9487651902473769 and parameters: {'weight_class_0': 0.33315906027510156, 'weight_class_1': 7.794553198198934, 'weight_class_2': 7.245796832904274}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:31,233] Trial 1141 finished with value: 0.9491797481781877 and parameters: {'weight_class_0': 0.39905557960773147, 'weight_class_1': 7.8541612192213455, 'weight_class_2': 7.3399462130318245}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:31,293] Trial 1142 finished with value: 0.9477588657166759 and parameters: {'weight_class_0': 1.250855695140493, 'weight_class_1': 7.772601535411306, 'weight_class_2': 7.282174121240435}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:31,306] Trial 1143 finished with value: 0.948687971258812 and parameters: {'weight_class_0': 1.0855902682680152, 'weight_class_1': 9.286436824789474, 'weight_class_2': 7.3129189495936275}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:31,337] Trial 1145 finished with value: 0.947738170903761 and parameters: {'weight_class_0': 1.3220039944660096, 'weight_class_1': 9.274100429589774, 'weight_class_2': 7.272610981023754}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:31,346] Trial 1144 finished with value: 0.9479540064014227 and parameters: {'weight_class_0': 1.2655216365250703, 'weight_class_1': 8.674334534203878, 'weight_class_2': 7.325939717107625}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:31,377] Trial 1147 finished with value: 0.9436912508161289 and parameters: {'weight_class_0': 1.281126964310937, 'weight_class_1': 9.209444230245534, 'weight_class_2': 4.016597318262662}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:31,382] Trial 1146 finished with value: 0.9478449263516137 and parameters: {'weight_class_0': 1.2980540029759338, 'weight_class_1': 9.18959849346184, 'weight_class_2': 7.284614300664125}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:31,438] Trial 1148 finished with value: 0.94814908711206 and parameters: {'weight_class_0': 1.2573545461796996, 'weight_class_1': 9.213738540563432, 'weight_class_2': 7.281872934483158}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:31,443] Trial 1149 finished with value: 0.9486336307605355 and parameters: {'weight_class_0': 1.093206195161755, 'weight_class_1': 9.117302071425948, 'weight_class_2': 7.319366115428142}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:31,468] Trial 1150 finished with value: 0.9478287393836405 and parameters: {'weight_class_0': 1.3037084950023796, 'weight_class_1': 8.405404070013562, 'weight_class_2': 7.486183088194471}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:31,496] Trial 1151 finished with value: 0.948894614154289 and parameters: {'weight_class_0': 1.0082673286053976, 'weight_class_1': 9.150143362629686, 'weight_class_2': 7.555101150778087}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:31,528] Trial 1152 finished with value: 0.9488806066663846 and parameters: {'weight_class_0': 1.023480994633448, 'weight_class_1': 9.23777836803272, 'weight_class_2': 7.456003167962523}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:31,562] Trial 1154 finished with value: 0.9496966538197863 and parameters: {'weight_class_0': 0.6073485978022123, 'weight_class_1': 8.400740872101933, 'weight_class_2': 7.533431680031806}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:31,595] Trial 1153 finished with value: 0.9488974145709096 and parameters: {'weight_class_0': 0.9800089121261524, 'weight_class_1': 9.123356763485905, 'weight_class_2': 7.459471454856223}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:31,605] Trial 1155 finished with value: 0.9496239788520566 and parameters: {'weight_class_0': 0.5928067019688055, 'weight_class_1': 8.405019911004645, 'weight_class_2': 7.540889895458718}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:31,607] Trial 1156 finished with value: 0.9466053911557638 and parameters: {'weight_class_0': 0.1840728345613123, 'weight_class_1': 8.40148093903597, 'weight_class_2': 7.518126727331002}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  39%|███████████████████████████████████████████████████▏                                                                                | 1163/3000 [00:25<00:46, 39.34it/s]

[I 2026-07-10 16:12:31,643] Trial 1157 finished with value: 0.9496394310803821 and parameters: {'weight_class_0': 0.5946423875376523, 'weight_class_1': 8.37266096157447, 'weight_class_2': 7.5260944486265435}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:31,685] Trial 1159 finished with value: 0.949619777223529 and parameters: {'weight_class_0': 0.5903201534906214, 'weight_class_1': 8.385047122990114, 'weight_class_2': 7.539548713763832}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:31,703] Trial 1158 finished with value: 0.9497473075815405 and parameters: {'weight_class_0': 0.6250586723910586, 'weight_class_1': 8.030232921896005, 'weight_class_2': 7.606557801195585}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:31,739] Trial 1160 finished with value: 0.9497179293814283 and parameters: {'weight_class_0': 0.6310321347754236, 'weight_class_1': 7.981792452545731, 'weight_class_2': 7.573686218427037}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:31,773] Trial 1161 finished with value: 0.949728957892337 and parameters: {'weight_class_0': 0.6030662798811472, 'weight_class_1': 8.021532535494977, 'weight_class_2': 7.106241126436291}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:31,796] Trial 1162 finished with value: 0.946502419488691 and parameters: {'weight_class_0': 0.1808027015831224, 'weight_class_1': 8.400344892208528, 'weight_class_2': 7.551071413006927}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:31,842] Trial 1163 finished with value: 0.9466556855506693 and parameters: {'weight_class_0': 0.17752623116188887, 'weight_class_1': 8.026177374256736, 'weight_class_2': 7.093180549339176}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  39%|███████████████████████████████████████████████████▌                                                                                | 1173/3000 [00:25<00:45, 40.09it/s]

[I 2026-07-10 16:12:31,863] Trial 1165 finished with value: 0.9497124545102746 and parameters: {'weight_class_0': 0.608901667919202, 'weight_class_1': 8.00352507185221, 'weight_class_2': 7.096650527213399}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:31,864] Trial 1164 finished with value: 0.9476435707159571 and parameters: {'weight_class_0': 0.22112445424505062, 'weight_class_1': 7.511600577946078, 'weight_class_2': 7.9239062757966225}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:31,870] Trial 1166 finished with value: 0.9494350300241522 and parameters: {'weight_class_0': 0.7752961886954297, 'weight_class_1': 8.003489621665693, 'weight_class_2': 7.094730087423737}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:31,892] Trial 1167 finished with value: 0.9494014893061653 and parameters: {'weight_class_0': 0.7835696535656249, 'weight_class_1': 8.05972075220798, 'weight_class_2': 7.079751039481774}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:31,923] Trial 1169 finished with value: 0.9491949659144095 and parameters: {'weight_class_0': 0.8469199290968226, 'weight_class_1': 8.00969070145826, 'weight_class_2': 7.079101180740839}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:31,958] Trial 1168 finished with value: 0.9496396297305796 and parameters: {'weight_class_0': 0.7194310482089443, 'weight_class_1': 7.990557385231756, 'weight_class_2': 7.951176202660856}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:31,979] Trial 1170 finished with value: 0.949403826408815 and parameters: {'weight_class_0': 0.8192547296535678, 'weight_class_1': 7.915458691489188, 'weight_class_2': 7.978416013329184}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:31,979] Trial 1171 finished with value: 0.9494126594385576 and parameters: {'weight_class_0': 0.8219690718479702, 'weight_class_1': 7.954927409870165, 'weight_class_2': 7.91067922818319}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:32,011] Trial 1172 finished with value: 0.9494521723843699 and parameters: {'weight_class_0': 0.782929907427331, 'weight_class_1': 7.650040941256423, 'weight_class_2': 7.968613004922829}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:32,050] Trial 1173 finished with value: 0.9493475587658317 and parameters: {'weight_class_0': 0.8353390860061847, 'weight_class_1': 7.57203122521079, 'weight_class_2': 8.02599980660924}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  39%|████████████████████████████████████████████████████                                                                                | 1182/3000 [00:25<00:45, 39.72it/s]

[I 2026-07-10 16:12:32,063] Trial 1174 finished with value: 0.9493815865115586 and parameters: {'weight_class_0': 0.823235920879389, 'weight_class_1': 7.586712298920518, 'weight_class_2': 7.9633679278020475}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:32,092] Trial 1175 finished with value: 0.9492727243383708 and parameters: {'weight_class_0': 0.872571230854798, 'weight_class_1': 7.629084040154752, 'weight_class_2': 8.099247267613926}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:32,137] Trial 1177 finished with value: 0.9492105035294179 and parameters: {'weight_class_0': 0.9008420581789838, 'weight_class_1': 7.958608391530548, 'weight_class_2': 7.971444208414754}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:32,141] Trial 1176 finished with value: 0.9492432452518952 and parameters: {'weight_class_0': 0.8664573769183695, 'weight_class_1': 7.497187426842213, 'weight_class_2': 8.139963047061265}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:32,202] Trial 1179 finished with value: 0.9491808301155222 and parameters: {'weight_class_0': 0.8996887885248496, 'weight_class_1': 7.456468160377745, 'weight_class_2': 7.893218562037763}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:32,219] Trial 1180 finished with value: 0.9492237739056377 and parameters: {'weight_class_0': 0.43603529664666496, 'weight_class_1': 7.64850836297744, 'weight_class_2': 8.06502726060141}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:32,221] Trial 1178 finished with value: 0.9492584997551927 and parameters: {'weight_class_0': 0.8876027582896792, 'weight_class_1': 7.6500147729686745, 'weight_class_2': 8.087236178272601}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:32,260] Trial 1181 finished with value: 0.9492038804940471 and parameters: {'weight_class_0': 0.44358501847562276, 'weight_class_1': 7.577425913857981, 'weight_class_2': 8.12988148442485}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:32,271] Trial 1182 finished with value: 0.9492694553521183 and parameters: {'weight_class_0': 0.47762598709400117, 'weight_class_1': 7.711259308973889, 'weight_class_2': 8.22633908099733}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  40%|████████████████████████████████████████████████████▎                                                                               | 1190/3000 [00:25<00:43, 41.56it/s]

[I 2026-07-10 16:12:32,306] Trial 1183 finished with value: 0.6574301388666515 and parameters: {'weight_class_0': 0.0023676805001155987, 'weight_class_1': 8.229717506218774, 'weight_class_2': 7.805043595560704}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:32,308] Trial 1184 finished with value: 0.9490457878192897 and parameters: {'weight_class_0': 0.41965353388619664, 'weight_class_1': 8.220750703468601, 'weight_class_2': 8.204101508053778}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:32,351] Trial 1186 finished with value: 0.9493611305135249 and parameters: {'weight_class_0': 0.4720307022876826, 'weight_class_1': 8.299780198608795, 'weight_class_2': 7.7721192871916465}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:32,358] Trial 1185 finished with value: 0.9493635646319727 and parameters: {'weight_class_0': 0.468783843393063, 'weight_class_1': 8.202235736677007, 'weight_class_2': 7.795854803744515}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:32,386] Trial 1187 finished with value: 0.94925925512471 and parameters: {'weight_class_0': 0.4419275063571932, 'weight_class_1': 8.232658589194125, 'weight_class_2': 7.7422764242487565}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:32,451] Trial 1189 finished with value: 0.9490724802156844 and parameters: {'weight_class_0': 0.43372242527174826, 'weight_class_1': 8.188765690932907, 'weight_class_2': 8.4513651043572}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:32,456] Trial 1188 finished with value: 0.9492630018020304 and parameters: {'weight_class_0': 0.47446303692053016, 'weight_class_1': 8.110551383302948, 'weight_class_2': 8.378865070126576}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:32,480] Trial 1190 finished with value: 0.9494287550474713 and parameters: {'weight_class_0': 0.5117669192953958, 'weight_class_1': 8.22995804921411, 'weight_class_2': 7.795112818193159}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:32,517] Trial 1191 finished with value: 0.9493283257894912 and parameters: {'weight_class_0': 0.45982614561905055, 'weight_class_1': 8.187729064617038, 'weight_class_2': 7.6464157846823175}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:32,563] Trial 1192 finished with value: 0.9472485852286789 and parameters: {'weight_class_0': 0.21064491677876368, 'weight_class_1': 8.219288938257748, 'weight_class_2': 7.83528646246419}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:32,583] Trial 1195 finished with value: 0.9481170370717446 and parameters: {'weight_class_0': 0.260597784618526, 'weight_class_1': 8.212253652238413, 'weight_class_2': 7.814721585129362}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:32,593] Trial 1194 finished with value: 0.9495532750305057 and parameters: {'weight_class_0': 0.5590352441968064, 'weight_class_1': 8.243931138929781, 'weight_class_2': 7.716301985162526}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:32,595] Trial 1193 finished with value: 0.9473092812125327 and parameters: {'weight_class_0': 0.21414258072799353, 'weight_class_1': 8.2346132934374, 'weight_class_2': 7.772653857265875}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:32,621] Trial 1196 finished with value: 0.9474140385340856 and parameters: {'weight_class_0': 0.21690065848364581, 'weight_class_1': 8.141870854436338, 'weight_class_2': 7.749911210842579}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:32,623] Trial 1197 finished with value: 0.9471827058481453 and parameters: {'weight_class_0': 0.2033504769790893, 'weight_class_1': 8.077783474495554, 'weight_class_2': 7.595869011593322}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:32,681] Trial 1199 finished with value: 0.9027227103399705 and parameters: {'weight_class_0': 5.321766776356647, 'weight_class_1': 8.10282650780852, 'weight_class_2': 7.575607212481847}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:32,694] Trial 1198 finished with value: 0.9479481180651398 and parameters: {'weight_class_0': 0.22547879755317973, 'weight_class_1': 5.150530475062496, 'weight_class_2': 7.578736554899206}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:32,700] Trial 1200 finished with value: 0.9480391736109235 and parameters: {'weight_class_0': 0.25417928908447196, 'weight_class_1': 8.564542455824007, 'weight_class_2': 7.5796807528008525}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:32,733] Trial 1201 finished with value: 0.8753461977702209 and parameters: {'weight_class_0': 7.856314044947654, 'weight_class_1': 8.586660102873271, 'weight_class_2': 6.821672558261424}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:32,765] Trial 1202 finished with value: 0.9474888803040568 and parameters: {'weight_class_0': 0.22379990564167274, 'weight_class_1': 8.570463540799642, 'weight_class_2': 7.505227736601572}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:32,820] Trial 1203 finished with value: 0.9487048103224134 and parameters: {'weight_class_0': 1.076476325560566, 'weight_class_1': 8.58412746783183, 'weight_class_2': 7.497736664381404}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:32,834] Trial 1204 finished with value: 0.8969259165749853 and parameters: {'weight_class_0': 5.621238083870528, 'weight_class_1': 8.583840668083232, 'weight_class_2': 6.785619352052426}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:32,866] Trial 1205 finished with value: 0.9485353767370454 and parameters: {'weight_class_0': 1.0565515337213771, 'weight_class_1': 8.558318023156781, 'weight_class_2': 6.8073984587308765}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:32,884] Trial 1206 finished with value: 0.9485912102922781 and parameters: {'weight_class_0': 1.0438510404919437, 'weight_class_1': 8.615273405058003, 'weight_class_2': 6.8374858890800585}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:32,906] Trial 1207 finished with value: 0.8885186763086589 and parameters: {'weight_class_0': 6.372049665161806, 'weight_class_1': 8.575990668010698, 'weight_class_2': 6.79328641151771}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:32,943] Trial 1208 finished with value: 0.9484411600840019 and parameters: {'weight_class_0': 1.0705643591093683, 'weight_class_1': 8.47586749068156, 'weight_class_2': 6.757371621110453}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  41%|█████████████████████████████████████████████████████▌                                                                              | 1217/3000 [00:26<00:43, 40.99it/s]

[I 2026-07-10 16:12:32,963] Trial 1210 finished with value: 0.9485660970924111 and parameters: {'weight_class_0': 1.0453511605323418, 'weight_class_1': 8.551919776079814, 'weight_class_2': 6.752094298792873}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:32,966] Trial 1209 finished with value: 0.9486556779263795 and parameters: {'weight_class_0': 1.0112395831454106, 'weight_class_1': 8.543215941523583, 'weight_class_2': 6.7781512739619085}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:33,020] Trial 1211 finished with value: 0.8736843315443057 and parameters: {'weight_class_0': 8.405834500399969, 'weight_class_1': 8.51218759561432, 'weight_class_2': 7.432683007432315}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:33,029] Trial 1212 finished with value: 0.9497233235921495 and parameters: {'weight_class_0': 0.6777256401141529, 'weight_class_1': 8.42648610517132, 'weight_class_2': 7.368942353926749}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:33,061] Trial 1214 finished with value: 0.9496723390063629 and parameters: {'weight_class_0': 0.6709094936831869, 'weight_class_1': 7.830334609482531, 'weight_class_2': 7.373801688247851}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:33,103] Trial 1213 finished with value: 0.9486657319373096 and parameters: {'weight_class_0': 1.0691685062737004, 'weight_class_1': 8.448566448607643, 'weight_class_2': 7.37159262002346}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:33,107] Trial 1215 finished with value: 0.9485658739089323 and parameters: {'weight_class_0': 1.0355997336392464, 'weight_class_1': 7.848322533410041, 'weight_class_2': 7.336758309357782}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:33,145] Trial 1216 finished with value: 0.9302881981565485 and parameters: {'weight_class_0': 3.096553182929087, 'weight_class_1': 7.8353593685035285, 'weight_class_2': 7.224067442005272}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:33,159] Trial 1217 finished with value: 0.9496578197566964 and parameters: {'weight_class_0': 0.70825599970766, 'weight_class_1': 8.414099809366725, 'weight_class_2': 7.168975141763925}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:33,200] Trial 1218 finished with value: 0.9496647651225459 and parameters: {'weight_class_0': 0.6847553617924257, 'weight_class_1': 7.849597613074283, 'weight_class_2': 7.189946812217994}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:33,208] Trial 1220 finished with value: 0.9497073771991668 and parameters: {'weight_class_0': 0.6585639298401832, 'weight_class_1': 7.825034164822373, 'weight_class_2': 7.350188607256358}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:33,232] Trial 1221 finished with value: 0.9496969017039755 and parameters: {'weight_class_0': 0.6451114880717967, 'weight_class_1': 7.852019700629148, 'weight_class_2': 7.336971821672001}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:33,235] Trial 1219 finished with value: 0.9496813047934084 and parameters: {'weight_class_0': 0.673530095250925, 'weight_class_1': 7.85433000123899, 'weight_class_2': 7.34758584183511}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:33,290] Trial 1222 finished with value: 0.949621252691094 and parameters: {'weight_class_0': 0.7067121232043264, 'weight_class_1': 7.957533493153808, 'weight_class_2': 7.140861889216003}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:33,326] Trial 1224 finished with value: 0.94969465589908 and parameters: {'weight_class_0': 0.6272236201894181, 'weight_class_1': 7.8652393582820945, 'weight_class_2': 7.191829483229202}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:33,331] Trial 1223 finished with value: 0.9496887577830903 and parameters: {'weight_class_0': 0.6899581651924878, 'weight_class_1': 7.906680992992503, 'weight_class_2': 7.158709615350983}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:33,372] Trial 1225 finished with value: 0.9374444633201064 and parameters: {'weight_class_0': 0.65984128148505, 'weight_class_1': 1.3599537762541845, 'weight_class_2': 7.157154602033767}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  41%|██████████████████████████████████████████████████████▎                                                                             | 1234/3000 [00:26<00:44, 39.97it/s]

[I 2026-07-10 16:12:33,382] Trial 1226 finished with value: 0.9496296975722661 and parameters: {'weight_class_0': 0.6986412195608673, 'weight_class_1': 8.78737119122525, 'weight_class_2': 7.147116920108996}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:33,401] Trial 1227 finished with value: 0.9497067248646333 and parameters: {'weight_class_0': 0.6823148891861541, 'weight_class_1': 8.823402013311608, 'weight_class_2': 7.19293847010298}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:33,427] Trial 1228 finished with value: 0.9496754025602344 and parameters: {'weight_class_0': 0.6484799485563559, 'weight_class_1': 8.83593936639667, 'weight_class_2': 7.215379023684992}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:33,451] Trial 1229 finished with value: 0.9480109082157853 and parameters: {'weight_class_0': 0.6738141792062683, 'weight_class_1': 8.77408452621018, 'weight_class_2': 3.3489338480510376}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:33,483] Trial 1230 finished with value: 0.9497013874360074 and parameters: {'weight_class_0': 0.6435650859956168, 'weight_class_1': 8.825957640300489, 'weight_class_2': 7.165913983668836}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:33,504] Trial 1231 finished with value: 0.949033007749728 and parameters: {'weight_class_0': 0.7888811755634546, 'weight_class_1': 8.811920700989782, 'weight_class_2': 5.433426950267964}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:33,531] Trial 1232 finished with value: 0.9494398039358471 and parameters: {'weight_class_0': 0.784840353698434, 'weight_class_1': 8.874987642031513, 'weight_class_2': 7.067109717180074}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:33,571] Trial 1233 finished with value: 0.9305626835345612 and parameters: {'weight_class_0': 0.8820346755362986, 'weight_class_1': 1.438777571713012, 'weight_class_2': 6.4570357701864545}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:33,590] Trial 1234 finished with value: 0.9493692214606434 and parameters: {'weight_class_0': 0.8834609579901858, 'weight_class_1': 8.894435579109171, 'weight_class_2': 7.597335505406214}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  41%|██████████████████████████████████████████████████████▋                                                                             | 1243/3000 [00:27<00:44, 39.20it/s]

[I 2026-07-10 16:12:33,635] Trial 1236 finished with value: 0.9494179982011444 and parameters: {'weight_class_0': 0.4682348445222403, 'weight_class_1': 8.831601589320389, 'weight_class_2': 7.608067746480004}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:33,637] Trial 1235 finished with value: 0.9493795656917422 and parameters: {'weight_class_0': 0.8809563188146251, 'weight_class_1': 8.87866024313241, 'weight_class_2': 7.645063426958901}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:33,643] Trial 1237 finished with value: 0.9492253347183949 and parameters: {'weight_class_0': 0.9051708905103457, 'weight_class_1': 8.815353101291192, 'weight_class_2': 7.587174303680783}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:33,704] Trial 1238 finished with value: 0.8580432480401456 and parameters: {'weight_class_0': 9.78556858916006, 'weight_class_1': 8.383405424961548, 'weight_class_2': 3.372924900981534}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:33,744] Trial 1239 finished with value: 0.9496061592051238 and parameters: {'weight_class_0': 0.48233304329291316, 'weight_class_1': 8.337073394779281, 'weight_class_2': 6.430745945218355}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:33,755] Trial 1240 finished with value: 0.94910230569004 and parameters: {'weight_class_0': 0.9175507643607973, 'weight_class_1': 8.345295243750197, 'weight_class_2': 7.598787513586299}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:33,759] Trial 1241 finished with value: 0.86654343828225 and parameters: {'weight_class_0': 9.737202743112473, 'weight_class_1': 8.398754032065698, 'weight_class_2': 7.597943510429827}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:33,769] Trial 1242 finished with value: 0.9494014937988289 and parameters: {'weight_class_0': 0.4672530307211066, 'weight_class_1': 8.288258554464015, 'weight_class_2': 7.613601731841601}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:33,796] Trial 1244 finished with value: 0.949655598546853 and parameters: {'weight_class_0': 0.41010137967559845, 'weight_class_1': 8.356617576428095, 'weight_class_2': 4.699570245898381}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  42%|███████████████████████████████████████████████████████                                                                             | 1251/3000 [00:27<00:43, 40.34it/s]

[I 2026-07-10 16:12:33,826] Trial 1243 finished with value: 0.949286322552202 and parameters: {'weight_class_0': 0.4314885779438972, 'weight_class_1': 8.40372295341655, 'weight_class_2': 7.572509817871833}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:33,849] Trial 1245 finished with value: 0.6793798536007613 and parameters: {'weight_class_0': 0.012743205586949191, 'weight_class_1': 8.344897618274743, 'weight_class_2': 7.81999607702504}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:33,869] Trial 1246 finished with value: 0.9492555240783264 and parameters: {'weight_class_0': 0.4529322629688274, 'weight_class_1': 8.321168985006553, 'weight_class_2': 7.831541314042176}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:33,922] Trial 1247 finished with value: 0.8668404061989917 and parameters: {'weight_class_0': 9.793560634635728, 'weight_class_1': 8.301773679074724, 'weight_class_2': 7.881194423604113}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:33,943] Trial 1249 finished with value: 0.9490776602147563 and parameters: {'weight_class_0': 0.4064239489493396, 'weight_class_1': 8.288971481976512, 'weight_class_2': 7.812362390407733}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:33,980] Trial 1248 finished with value: 0.9491391556670776 and parameters: {'weight_class_0': 0.4138924897930826, 'weight_class_1': 8.062187914927762, 'weight_class_2': 7.86126708910031}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:33,984] Trial 1250 finished with value: 0.9485233879773167 and parameters: {'weight_class_0': 0.30979937236408756, 'weight_class_1': 8.0898428368292, 'weight_class_2': 7.888500024336637}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:34,049] Trial 1251 finished with value: 0.9485886597033394 and parameters: {'weight_class_0': 0.316343017603467, 'weight_class_1': 8.048846715871461, 'weight_class_2': 7.8510153435524845}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  42%|███████████████████████████████████████████████████████▍                                                                            | 1260/3000 [00:27<00:45, 38.51it/s]

[I 2026-07-10 16:12:34,051] Trial 1253 finished with value: 0.6575774617498902 and parameters: {'weight_class_0': 0.004821933729149963, 'weight_class_1': 8.059783077927097, 'weight_class_2': 7.85074928693126}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:34,066] Trial 1252 finished with value: 0.9483146137460249 and parameters: {'weight_class_0': 0.2854538263678698, 'weight_class_1': 8.068421633005586, 'weight_class_2': 7.809521586843805}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:34,104] Trial 1254 finished with value: 0.9487044386044773 and parameters: {'weight_class_0': 0.3445338890499009, 'weight_class_1': 8.089529104284315, 'weight_class_2': 7.894653797886707}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:34,131] Trial 1255 finished with value: 0.9482942479506895 and parameters: {'weight_class_0': 0.2772111470069019, 'weight_class_1': 8.061971530639672, 'weight_class_2': 7.915936930797252}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:34,142] Trial 1256 finished with value: 0.9478578478187766 and parameters: {'weight_class_0': 0.24064734400054738, 'weight_class_1': 8.050756835014926, 'weight_class_2': 7.877999061668567}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:34,196] Trial 1259 finished with value: 0.9484456980832557 and parameters: {'weight_class_0': 0.28754421097759625, 'weight_class_1': 8.123159406214263, 'weight_class_2': 7.417873779676276}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:34,206] Trial 1257 finished with value: 0.9483412619353547 and parameters: {'weight_class_0': 0.2772114859740567, 'weight_class_1': 8.11810886473721, 'weight_class_2': 7.411886293160647}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:34,214] Trial 1258 finished with value: 0.9479090354315957 and parameters: {'weight_class_0': 0.25512298877338574, 'weight_class_1': 8.05292521089777, 'weight_class_2': 8.397216268663952}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:34,224] Trial 1260 finished with value: 0.9482332805305225 and parameters: {'weight_class_0': 1.1250496823265093, 'weight_class_1': 8.07100845372712, 'weight_class_2': 7.441119334081229}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:34,278] Trial 1261 finished with value: 0.9481145584349195 and parameters: {'weight_class_0': 1.176886784355824, 'weight_class_1': 8.092925310920469, 'weight_class_2': 7.423094692408854}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:34,283] Trial 1262 finished with value: 0.65769787888077 and parameters: {'weight_class_0': 0.0054816403975113115, 'weight_class_1': 8.679097725853367, 'weight_class_2': 8.153805370817754}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:34,312] Trial 1263 finished with value: 0.9484094512965248 and parameters: {'weight_class_0': 1.231532212993689, 'weight_class_1': 9.083413061461513, 'weight_class_2': 8.193435543805034}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:34,355] Trial 1264 finished with value: 0.9487163269097746 and parameters: {'weight_class_0': 1.1087590031363028, 'weight_class_1': 8.652917088648456, 'weight_class_2': 8.174406924615955}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:34,382] Trial 1265 finished with value: 0.948585035168676 and parameters: {'weight_class_0': 1.098033142465119, 'weight_class_1': 8.702065130704884, 'weight_class_2': 7.4172912833123}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:34,403] Trial 1266 finished with value: 0.9484231905507666 and parameters: {'weight_class_0': 1.2406753679951021, 'weight_class_1': 9.036891585218086, 'weight_class_2': 8.40995054893072}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:34,430] Trial 1267 finished with value: 0.9487114057328897 and parameters: {'weight_class_0': 1.1483824427716964, 'weight_class_1': 9.042640353462852, 'weight_class_2': 8.391624915810779}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:34,441] Trial 1268 finished with value: 0.9485569638837296 and parameters: {'weight_class_0': 1.2036658017481887, 'weight_class_1': 9.010611944807323, 'weight_class_2': 8.38571953281991}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:34,461] Trial 1269 finished with value: 0.9488394908387346 and parameters: {'weight_class_0': 0.9735729151257926, 'weight_class_1': 8.659905880515348, 'weight_class_2': 7.025348486299991}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  43%|████████████████████████████████████████████████████████▏                                                                           | 1277/3000 [00:27<00:45, 38.00it/s]

[I 2026-07-10 16:12:34,485] Trial 1270 finished with value: 0.9447679592730465 and parameters: {'weight_class_0': 1.8809771811785576, 'weight_class_1': 8.610916683146122, 'weight_class_2': 8.144479583416993}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:34,537] Trial 1271 finished with value: 0.9492104306149689 and parameters: {'weight_class_0': 0.856530920148431, 'weight_class_1': 9.034568812626238, 'weight_class_2': 6.969968066045695}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:34,580] Trial 1272 finished with value: 0.949063686776801 and parameters: {'weight_class_0': 0.9273854538842248, 'weight_class_1': 8.648719103870762, 'weight_class_2': 7.434711471945426}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:34,595] Trial 1274 finished with value: 0.9487485541229734 and parameters: {'weight_class_0': 1.0058634897206056, 'weight_class_1': 8.686799645103711, 'weight_class_2': 6.921304874647562}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:34,610] Trial 1273 finished with value: 0.9488823983347322 and parameters: {'weight_class_0': 0.9412282550998676, 'weight_class_1': 8.5445357048684, 'weight_class_2': 6.955975376360817}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:34,652] Trial 1275 finished with value: 0.9492490556448723 and parameters: {'weight_class_0': 0.8924180349614927, 'weight_class_1': 9.01000445595315, 'weight_class_2': 7.46835802311832}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:34,665] Trial 1276 finished with value: 0.949702789627142 and parameters: {'weight_class_0': 0.5584295495592613, 'weight_class_1': 8.602317586395708, 'weight_class_2': 6.9519528618819395}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:34,676] Trial 1277 finished with value: 0.9490761284245558 and parameters: {'weight_class_0': 0.8646640955341949, 'weight_class_1': 8.505372868312275, 'weight_class_2': 6.954515717085218}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  43%|████████████████████████████████████████████████████████▌                                                                           | 1286/3000 [00:28<00:43, 39.34it/s]

[I 2026-07-10 16:12:34,725] Trial 1278 finished with value: 0.9490655202748585 and parameters: {'weight_class_0': 0.8691968738046144, 'weight_class_1': 8.497618513563522, 'weight_class_2': 6.957265516816641}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:34,749] Trial 1279 finished with value: 0.9496832235058674 and parameters: {'weight_class_0': 0.5621050212952192, 'weight_class_1': 8.429674518050312, 'weight_class_2': 6.9338700515837015}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:34,755] Trial 1280 finished with value: 0.8844633737370079 and parameters: {'weight_class_0': 7.034146881716607, 'weight_class_1': 8.402579209149053, 'weight_class_2': 7.452883158329849}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:34,760] Trial 1281 finished with value: 0.949697550674213 and parameters: {'weight_class_0': 0.5659932420417406, 'weight_class_1': 8.430196959921883, 'weight_class_2': 6.940171109933046}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:34,792] Trial 1282 finished with value: 0.9496600451633793 and parameters: {'weight_class_0': 0.5606102172917741, 'weight_class_1': 8.423930242202946, 'weight_class_2': 6.976897472144885}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:34,829] Trial 1283 finished with value: 0.9496136690053606 and parameters: {'weight_class_0': 0.560002315894004, 'weight_class_1': 8.454383435680837, 'weight_class_2': 7.531877317663692}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:34,857] Trial 1284 finished with value: 0.905262002018067 and parameters: {'weight_class_0': 0.570829033095789, 'weight_class_1': 8.423707062819961, 'weight_class_2': 0.47497796240053525}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:34,888] Trial 1285 finished with value: 0.9497398826950291 and parameters: {'weight_class_0': 0.6146217633562272, 'weight_class_1': 8.373275915621395, 'weight_class_2': 7.544378411490942}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:34,929] Trial 1286 finished with value: 0.9495931209103409 and parameters: {'weight_class_0': 0.5541669806289145, 'weight_class_1': 8.368965374617012, 'weight_class_2': 7.645488125321315}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:34,956] Trial 1288 finished with value: 0.949648231013339 and parameters: {'weight_class_0': 0.598167653639352, 'weight_class_1': 8.339242701721593, 'weight_class_2': 7.587811859496093}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:34,968] Trial 1287 finished with value: 0.9496555847126645 and parameters: {'weight_class_0': 0.6080923596131486, 'weight_class_1': 8.36300173928059, 'weight_class_2': 7.685844359184661}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:34,990] Trial 1289 finished with value: 0.9496115005043152 and parameters: {'weight_class_0': 0.5713508162878461, 'weight_class_1': 8.355073830522112, 'weight_class_2': 7.634726830096239}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:35,027] Trial 1290 finished with value: 0.9495332226961505 and parameters: {'weight_class_0': 0.5370109161136271, 'weight_class_1': 8.296168494143672, 'weight_class_2': 7.574317956083278}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:35,043] Trial 1291 finished with value: 0.8983352122545615 and parameters: {'weight_class_0': 0.7242985926899392, 'weight_class_1': 8.274366935997563, 'weight_class_2': 0.39983436336991307}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:35,068] Trial 1292 finished with value: 0.9467151914860118 and parameters: {'weight_class_0': 1.4520507803645843, 'weight_class_1': 7.739139817004545, 'weight_class_2': 7.695912037866309}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:35,094] Trial 1293 finished with value: 0.949531307627918 and parameters: {'weight_class_0': 0.7455239210744379, 'weight_class_1': 7.73265427305801, 'weight_class_2': 7.657598096553998}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:35,117] Trial 1294 finished with value: 0.9495239313663321 and parameters: {'weight_class_0': 0.7391651948605497, 'weight_class_1': 7.700688023595003, 'weight_class_2': 7.60051359420892}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  43%|█████████████████████████████████████████████████████████▎                                                                          | 1303/3000 [00:28<00:42, 39.76it/s]

[I 2026-07-10 16:12:35,154] Trial 1296 finished with value: 0.9468696478145997 and parameters: {'weight_class_0': 1.475564985391188, 'weight_class_1': 8.259190403905828, 'weight_class_2': 7.717701362675211}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:35,171] Trial 1295 finished with value: 0.9496310889281996 and parameters: {'weight_class_0': 0.7390317986551984, 'weight_class_1': 8.261577781755214, 'weight_class_2': 7.660014939499375}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:35,179] Trial 1297 finished with value: 0.9470944263029937 and parameters: {'weight_class_0': 1.473966962705253, 'weight_class_1': 8.730374021820255, 'weight_class_2': 7.702275953438047}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:35,216] Trial 1298 finished with value: 0.9468327197861415 and parameters: {'weight_class_0': 1.558863753822509, 'weight_class_1': 8.748823539813452, 'weight_class_2': 8.05362398224452}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:35,268] Trial 1299 finished with value: 0.9467657941142296 and parameters: {'weight_class_0': 1.4841473714385471, 'weight_class_1': 8.72893197472941, 'weight_class_2': 7.286664462309404}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:35,282] Trial 1300 finished with value: 0.9495931786586317 and parameters: {'weight_class_0': 0.7527518916425462, 'weight_class_1': 8.699086627403354, 'weight_class_2': 7.260115728279699}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:35,306] Trial 1301 finished with value: 0.9495870602143283 and parameters: {'weight_class_0': 0.751480351180742, 'weight_class_1': 8.677683610655997, 'weight_class_2': 7.311381263789117}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:35,329] Trial 1302 finished with value: 0.9495087404118859 and parameters: {'weight_class_0': 0.773689430606826, 'weight_class_1': 8.68189615501961, 'weight_class_2': 7.268174801356059}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:35,379] Trial 1303 finished with value: 0.9495374354552375 and parameters: {'weight_class_0': 0.7712601922950755, 'weight_class_1': 8.719053052313715, 'weight_class_2': 7.283782944014112}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:35,387] Trial 1304 finished with value: 0.9492960828140998 and parameters: {'weight_class_0': 0.43576315743173033, 'weight_class_1': 8.746297364981062, 'weight_class_2': 7.312875398926854}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:35,403] Trial 1305 finished with value: 0.9495449036646694 and parameters: {'weight_class_0': 0.76705078038153, 'weight_class_1': 8.726381650563578, 'weight_class_2': 7.307754563145975}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:35,458] Trial 1306 finished with value: 0.9465580841006175 and parameters: {'weight_class_0': 0.18689010733556788, 'weight_class_1': 8.738314583733024, 'weight_class_2': 7.227764312161157}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:35,459] Trial 1307 finished with value: 0.9489035891732803 and parameters: {'weight_class_0': 0.3878732145089468, 'weight_class_1': 8.765870969585619, 'weight_class_2': 8.052566440829384}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:35,490] Trial 1308 finished with value: 0.9464642153957534 and parameters: {'weight_class_0': 0.1875650296873112, 'weight_class_1': 8.965559778581655, 'weight_class_2': 7.236231077826037}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:35,508] Trial 1309 finished with value: 0.9491689899414468 and parameters: {'weight_class_0': 0.40990492127220657, 'weight_class_1': 9.006333361232569, 'weight_class_2': 7.328602141173197}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:35,557] Trial 1310 finished with value: 0.9479071779230136 and parameters: {'weight_class_0': 0.4343777714474773, 'weight_class_1': 7.928992408112789, 'weight_class_2': 2.1650758478035765}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:35,564] Trial 1311 finished with value: 0.9466687615941508 and parameters: {'weight_class_0': 0.18476597733069888, 'weight_class_1': 7.941266451441555, 'weight_class_2': 8.04768218282151}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:35,584] Trial 1312 finished with value: 0.9446796780427106 and parameters: {'weight_class_0': 0.15140759315207142, 'weight_class_1': 9.053612430301213, 'weight_class_2': 8.010181428500363}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  44%|██████████████████████████████████████████████████████████                                                                          | 1321/3000 [00:29<00:44, 37.83it/s]

[I 2026-07-10 16:12:35,640] Trial 1314 finished with value: 0.9492487962807084 and parameters: {'weight_class_0': 0.4268484638898753, 'weight_class_1': 7.949051120294439, 'weight_class_2': 7.422232452652345}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:35,644] Trial 1313 finished with value: 0.9449978921351588 and parameters: {'weight_class_0': 0.16108823754249024, 'weight_class_1': 9.323896015721353, 'weight_class_2': 8.07853612397485}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:35,675] Trial 1315 finished with value: 0.9453988477243788 and parameters: {'weight_class_0': 0.136162817073183, 'weight_class_1': 9.005313460580282, 'weight_class_2': 2.4616968869662577}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:35,688] Trial 1316 finished with value: 0.9456076137526228 and parameters: {'weight_class_0': 0.154114919071764, 'weight_class_1': 7.944261631864597, 'weight_class_2': 7.994968919871601}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:35,738] Trial 1317 finished with value: 0.9453903453366822 and parameters: {'weight_class_0': 0.16425610364590343, 'weight_class_1': 9.015952160284584, 'weight_class_2': 8.022565312756104}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:35,748] Trial 1318 finished with value: 0.9492419798300555 and parameters: {'weight_class_0': 0.4474479688487417, 'weight_class_1': 8.033038363267718, 'weight_class_2': 7.9788727856066615}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:35,776] Trial 1319 finished with value: 0.9492778747126024 and parameters: {'weight_class_0': 0.9502400124050674, 'weight_class_1': 9.28521732582071, 'weight_class_2': 8.056279311847723}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:35,777] Trial 1320 finished with value: 0.9488377680086773 and parameters: {'weight_class_0': 0.9811089783440807, 'weight_class_1': 8.008259132712736, 'weight_class_2': 7.528345210003592}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:35,843] Trial 1321 finished with value: 0.949398490560769 and parameters: {'weight_class_0': 0.4952909898142668, 'weight_class_1': 9.2800453376154, 'weight_class_2': 7.491825202748413}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  44%|██████████████████████████████████████████████████████████▍                                                                         | 1329/3000 [00:29<00:41, 39.82it/s]

[I 2026-07-10 16:12:35,844] Trial 1322 finished with value: 0.9488087033723418 and parameters: {'weight_class_0': 1.0117935178423676, 'weight_class_1': 8.209009391188163, 'weight_class_2': 7.481167689586587}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:35,910] Trial 1324 finished with value: 0.9488973943860041 and parameters: {'weight_class_0': 0.9683618757604397, 'weight_class_1': 8.16152999888536, 'weight_class_2': 7.47534343297653}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:35,939] Trial 1323 finished with value: 0.9489301129704663 and parameters: {'weight_class_0': 0.948664273106766, 'weight_class_1': 8.173435220039336, 'weight_class_2': 7.484403092689235}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:35,955] Trial 1326 finished with value: 0.9488458648388732 and parameters: {'weight_class_0': 0.9783714002078425, 'weight_class_1': 8.191380885249172, 'weight_class_2': 7.494390853362873}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:35,961] Trial 1325 finished with value: 0.9488422709676531 and parameters: {'weight_class_0': 0.9831140438756416, 'weight_class_1': 8.179188063798664, 'weight_class_2': 7.455073375647521}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:35,994] Trial 1327 finished with value: 0.9489326104606316 and parameters: {'weight_class_0': 0.9433679135255761, 'weight_class_1': 8.128997722252592, 'weight_class_2': 7.4666641989640485}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:36,016] Trial 1328 finished with value: 0.9488331619915763 and parameters: {'weight_class_0': 0.9908170922923004, 'weight_class_1': 8.193121843736842, 'weight_class_2': 7.482592253951657}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:36,056] Trial 1329 finished with value: 0.9496383407131951 and parameters: {'weight_class_0': 0.5869993448411558, 'weight_class_1': 8.254082981794763, 'weight_class_2': 7.477168820288833}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  45%|██████████████████████████████████████████████████████████▊                                                                         | 1337/3000 [00:29<00:44, 37.52it/s]

[I 2026-07-10 16:12:36,067] Trial 1332 finished with value: 0.9496361884521524 and parameters: {'weight_class_0': 0.581146320398433, 'weight_class_1': 8.505709517581469, 'weight_class_2': 7.732037679165233}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:36,093] Trial 1331 finished with value: 0.9494847504501184 and parameters: {'weight_class_0': 0.5475353492977674, 'weight_class_1': 8.208192449765797, 'weight_class_2': 7.7749065229693715}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:36,097] Trial 1330 finished with value: 0.9496471118644304 and parameters: {'weight_class_0': 0.5707089154560943, 'weight_class_1': 8.224932074577389, 'weight_class_2': 7.4542000902066565}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:36,150] Trial 1333 finished with value: 0.9497415312771422 and parameters: {'weight_class_0': 0.6409122772696764, 'weight_class_1': 8.49678029992097, 'weight_class_2': 7.76640165616416}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:36,165] Trial 1334 finished with value: 0.9486604316295618 and parameters: {'weight_class_0': 0.6506977634638438, 'weight_class_1': 8.508280724979443, 'weight_class_2': 3.716437652092536}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:36,250] Trial 1336 finished with value: 0.9495856380569134 and parameters: {'weight_class_0': 0.593922040409454, 'weight_class_1': 8.385706868420655, 'weight_class_2': 7.812311439016594}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:36,251] Trial 1337 finished with value: 0.9494982659166675 and parameters: {'weight_class_0': 0.5430097261589701, 'weight_class_1': 8.504229537957773, 'weight_class_2': 7.786699017813493}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:36,259] Trial 1335 finished with value: 0.9496856576243152 and parameters: {'weight_class_0': 0.5715131512292916, 'weight_class_1': 8.471253737580081, 'weight_class_2': 7.109573991942401}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  45%|███████████████████████████████████████████████████████████▏                                                                        | 1346/3000 [00:29<00:42, 38.75it/s]

[I 2026-07-10 16:12:36,298] Trial 1338 finished with value: 0.9496470833910987 and parameters: {'weight_class_0': 0.6153109832744649, 'weight_class_1': 8.499728219769732, 'weight_class_2': 7.786450577073761}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:36,305] Trial 1339 finished with value: 0.9496019209460944 and parameters: {'weight_class_0': 0.5794152757934555, 'weight_class_1': 8.499220753723774, 'weight_class_2': 7.8250496637535}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:36,334] Trial 1340 finished with value: 0.9495809357561571 and parameters: {'weight_class_0': 0.7332650175231837, 'weight_class_1': 8.456689276638997, 'weight_class_2': 7.132898821239647}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:36,335] Trial 1341 finished with value: 0.9494446176367463 and parameters: {'weight_class_0': 0.7356276190622701, 'weight_class_1': 8.512912740052593, 'weight_class_2': 6.579930927106269}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:36,357] Trial 1342 finished with value: 0.9494821461827981 and parameters: {'weight_class_0': 0.7592176700945166, 'weight_class_1': 8.50974521553896, 'weight_class_2': 7.073521272314156}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:36,389] Trial 1343 finished with value: 0.9496884761930495 and parameters: {'weight_class_0': 0.7595231570979859, 'weight_class_1': 8.52254165276996, 'weight_class_2': 8.21792502947622}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:36,434] Trial 1344 finished with value: 0.9496002104314171 and parameters: {'weight_class_0': 0.785804591144603, 'weight_class_1': 8.539579143572873, 'weight_class_2': 8.258711153562793}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:36,478] Trial 1345 finished with value: 0.9497095216447411 and parameters: {'weight_class_0': 0.7270523845614324, 'weight_class_1': 8.555134990312608, 'weight_class_2': 7.849093852645361}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:36,485] Trial 1346 finished with value: 0.9487944053124576 and parameters: {'weight_class_0': 0.3570516943872538, 'weight_class_1': 8.616652927929673, 'weight_class_2': 7.824916904252083}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  45%|███████████████████████████████████████████████████████████▌                                                                        | 1354/3000 [00:29<00:44, 36.64it/s]

[I 2026-07-10 16:12:36,524] Trial 1347 finished with value: 0.9496290894732571 and parameters: {'weight_class_0': 0.7817600758506625, 'weight_class_1': 8.5866583234329, 'weight_class_2': 8.316188852356909}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:36,534] Trial 1348 finished with value: 0.9087472090257628 and parameters: {'weight_class_0': 0.816011630003079, 'weight_class_1': 0.5924166106521103, 'weight_class_2': 7.790304749071237}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:36,594] Trial 1349 finished with value: 0.9470095812482348 and parameters: {'weight_class_0': 0.3541068663866587, 'weight_class_1': 2.080548312781194, 'weight_class_2': 8.248064603197657}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:36,598] Trial 1350 finished with value: 0.94883825407554 and parameters: {'weight_class_0': 0.38214061667920407, 'weight_class_1': 9.011359975390622, 'weight_class_2': 8.134672901259478}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:36,639] Trial 1351 finished with value: 0.9487523136277268 and parameters: {'weight_class_0': 0.36675890006126044, 'weight_class_1': 8.925903606235199, 'weight_class_2': 8.161000791195674}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:36,657] Trial 1353 finished with value: 0.9487369456345757 and parameters: {'weight_class_0': 0.3533178103885633, 'weight_class_1': 8.800152631296218, 'weight_class_2': 7.915309931796714}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:36,659] Trial 1352 finished with value: 0.9488177252479696 and parameters: {'weight_class_0': 0.36475891253437703, 'weight_class_1': 8.874754209953933, 'weight_class_2': 7.747144747814462}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:36,703] Trial 1354 finished with value: 0.9487578964193646 and parameters: {'weight_class_0': 0.3584811831134751, 'weight_class_1': 8.988294218984255, 'weight_class_2': 7.9551740931119665}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  45%|███████████████████████████████████████████████████████████▉                                                                        | 1363/3000 [00:30<00:39, 40.99it/s]

[I 2026-07-10 16:12:36,731] Trial 1355 finished with value: 0.9492319862661929 and parameters: {'weight_class_0': 0.4406615612641712, 'weight_class_1': 8.887921143193902, 'weight_class_2': 7.929833342751087}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:36,749] Trial 1356 finished with value: 0.9487395456071118 and parameters: {'weight_class_0': 0.3561836467402757, 'weight_class_1': 8.910056103566756, 'weight_class_2': 7.9574108103577865}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:36,777] Trial 1359 finished with value: 0.9469251046721835 and parameters: {'weight_class_0': 0.38036362726456224, 'weight_class_1': 2.0713550046355813, 'weight_class_2': 8.195871896770718}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:36,778] Trial 1357 finished with value: 0.9486067554327148 and parameters: {'weight_class_0': 0.3471418197130964, 'weight_class_1': 8.916921240407662, 'weight_class_2': 8.229985402551678}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:36,804] Trial 1358 finished with value: 0.9487190653016703 and parameters: {'weight_class_0': 0.34996429317172467, 'weight_class_1': 8.79442804014799, 'weight_class_2': 7.967498152932994}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:36,820] Trial 1360 finished with value: 0.9487710247242847 and parameters: {'weight_class_0': 0.3628647494233495, 'weight_class_1': 8.945468681676047, 'weight_class_2': 8.028083313376888}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:36,883] Trial 1361 finished with value: 0.9481030434435657 and parameters: {'weight_class_0': 1.2688782970326062, 'weight_class_1': 8.891603298477431, 'weight_class_2': 7.68493693923}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:36,910] Trial 1362 finished with value: 0.948092962008016 and parameters: {'weight_class_0': 1.2924026294104478, 'weight_class_1': 8.904723375715946, 'weight_class_2': 7.956895373519273}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:36,960] Trial 1363 finished with value: 0.9481657541021119 and parameters: {'weight_class_0': 1.247426997721707, 'weight_class_1': 8.889602445150595, 'weight_class_2': 7.671921245091689}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:36,963] Trial 1364 finished with value: 0.9479797984429864 and parameters: {'weight_class_0': 1.308000482313398, 'weight_class_1': 8.884813884302517, 'weight_class_2': 7.670508343991317}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:36,969] Trial 1365 finished with value: 0.9483572822239438 and parameters: {'weight_class_0': 1.2045601282913077, 'weight_class_1': 8.82469985146989, 'weight_class_2': 7.667009223864283}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:37,017] Trial 1366 finished with value: 0.6574821504479074 and parameters: {'weight_class_0': 0.0017332647228646136, 'weight_class_1': 8.313817038738671, 'weight_class_2': 7.608344279918487}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:37,040] Trial 1367 finished with value: 0.948717142453677 and parameters: {'weight_class_0': 1.095114374290795, 'weight_class_1': 8.657836850327032, 'weight_class_2': 7.693037966969097}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:37,060] Trial 1368 finished with value: 0.9484054876267273 and parameters: {'weight_class_0': 1.144866483218279, 'weight_class_1': 8.68496406181972, 'weight_class_2': 7.575130992009817}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:37,091] Trial 1369 finished with value: 0.9480235902183801 and parameters: {'weight_class_0': 1.2366508132837044, 'weight_class_1': 8.331421291617954, 'weight_class_2': 7.670101685741901}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:37,144] Trial 1370 finished with value: 0.9492795974683225 and parameters: {'weight_class_0': 0.8684392839073205, 'weight_class_1': 8.360114700226747, 'weight_class_2': 7.760440756479679}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:37,146] Trial 1371 finished with value: 0.9479392137473447 and parameters: {'weight_class_0': 1.3082693440112907, 'weight_class_1': 8.682828856472744, 'weight_class_2': 7.707727012527347}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  46%|████████████████████████████████████████████████████████████▋                                                                       | 1380/3000 [00:30<00:40, 39.64it/s]

[I 2026-07-10 16:12:37,174] Trial 1372 finished with value: 0.948224543969283 and parameters: {'weight_class_0': 1.1631792317757823, 'weight_class_1': 8.340394753948669, 'weight_class_2': 7.688933506565748}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:37,183] Trial 1373 finished with value: 0.6579837162202712 and parameters: {'weight_class_0': 0.005810465335015169, 'weight_class_1': 8.311958641201018, 'weight_class_2': 7.669927206222636}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:37,200] Trial 1374 finished with value: 0.7184220476877724 and parameters: {'weight_class_0': 0.01745674163129185, 'weight_class_1': 8.329809792014863, 'weight_class_2': 7.642395859924761}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:37,257] Trial 1376 finished with value: 0.9493000942193602 and parameters: {'weight_class_0': 0.8600831909819804, 'weight_class_1': 8.403840792289612, 'weight_class_2': 7.683153179934192}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:37,271] Trial 1375 finished with value: 0.9492947570991244 and parameters: {'weight_class_0': 0.861972859668752, 'weight_class_1': 8.319430604770435, 'weight_class_2': 7.724387035668045}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:37,318] Trial 1377 finished with value: 0.9494355638752171 and parameters: {'weight_class_0': 0.8031869212519078, 'weight_class_1': 8.343996248614522, 'weight_class_2': 7.392482594919457}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:37,328] Trial 1379 finished with value: 0.9491223302629264 and parameters: {'weight_class_0': 0.8952694994968908, 'weight_class_1': 8.348018334935329, 'weight_class_2': 7.364870983006868}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:37,340] Trial 1378 finished with value: 0.949189352745043 and parameters: {'weight_class_0': 0.881108275081095, 'weight_class_1': 8.316595277343934, 'weight_class_2': 7.3845513469934305}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:37,363] Trial 1380 finished with value: 0.9495576275066789 and parameters: {'weight_class_0': 0.8165130648679111, 'weight_class_1': 8.343579162682145, 'weight_class_2': 8.464668961821939}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  46%|█████████████████████████████████████████████████████████████                                                                       | 1387/3000 [00:30<00:41, 38.93it/s]

[I 2026-07-10 16:12:37,377] Trial 1381 finished with value: 0.9494353714855062 and parameters: {'weight_class_0': 0.8220309289660026, 'weight_class_1': 9.363839448121668, 'weight_class_2': 7.329388093242452}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:37,445] Trial 1382 finished with value: 0.9493237887130116 and parameters: {'weight_class_0': 0.8574924581771881, 'weight_class_1': 9.271439658266665, 'weight_class_2': 7.236067336043599}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:37,461] Trial 1383 finished with value: 0.9493932166346511 and parameters: {'weight_class_0': 0.8404175886358511, 'weight_class_1': 9.224386330183675, 'weight_class_2': 7.3067805336355915}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:37,501] Trial 1384 finished with value: 0.9492137622663943 and parameters: {'weight_class_0': 0.8892203460322756, 'weight_class_1': 9.250784938293167, 'weight_class_2': 7.32375064617897}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:37,517] Trial 1385 finished with value: 0.9492895059128665 and parameters: {'weight_class_0': 0.8220958859849701, 'weight_class_1': 7.890186827565306, 'weight_class_2': 7.385848179726088}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:37,560] Trial 1386 finished with value: 0.9496776562423696 and parameters: {'weight_class_0': 0.5882503259096801, 'weight_class_1': 7.886260590891613, 'weight_class_2': 7.330126133330617}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:37,580] Trial 1387 finished with value: 0.9496870387874253 and parameters: {'weight_class_0': 0.5896378722598221, 'weight_class_1': 9.191835413139845, 'weight_class_2': 7.345054785199752}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  47%|█████████████████████████████████████████████████████████████▍                                                                      | 1396/3000 [00:31<00:43, 37.16it/s]

[I 2026-07-10 16:12:37,602] Trial 1388 finished with value: 0.9497256975308942 and parameters: {'weight_class_0': 0.6369901128534237, 'weight_class_1': 8.021238952458319, 'weight_class_2': 7.226516475980214}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:37,609] Trial 1389 finished with value: 0.949655721887828 and parameters: {'weight_class_0': 0.5687268200353099, 'weight_class_1': 7.875577711094956, 'weight_class_2': 7.173287356570558}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:37,642] Trial 1390 finished with value: 0.9496285174212812 and parameters: {'weight_class_0': 0.5697716954774361, 'weight_class_1': 9.252070644617422, 'weight_class_2': 7.209136282104493}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:37,652] Trial 1392 finished with value: 0.9496379680927644 and parameters: {'weight_class_0': 0.5403577371025255, 'weight_class_1': 7.847002201571352, 'weight_class_2': 7.125955997912415}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:37,666] Trial 1391 finished with value: 0.9496188014692448 and parameters: {'weight_class_0': 0.5589839420279732, 'weight_class_1': 7.94248517154979, 'weight_class_2': 7.149603988379714}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:37,684] Trial 1393 finished with value: 0.9497403716271665 and parameters: {'weight_class_0': 0.6076143844115954, 'weight_class_1': 7.779998160573615, 'weight_class_2': 7.190838641494577}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:37,731] Trial 1394 finished with value: 0.9496251898460145 and parameters: {'weight_class_0': 0.5595861664571631, 'weight_class_1': 7.96410541964647, 'weight_class_2': 7.135596219471753}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:37,754] Trial 1395 finished with value: 0.949634775418103 and parameters: {'weight_class_0': 0.5578265400459058, 'weight_class_1': 7.980667713002891, 'weight_class_2': 7.128936640647943}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:37,763] Trial 1396 finished with value: 0.9490819090883708 and parameters: {'weight_class_0': 0.585963297454678, 'weight_class_1': 4.508854499715457, 'weight_class_2': 7.123238199445565}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:37,807] Trial 1397 finished with value: 0.8821211138146224 and parameters: {'weight_class_0': 7.3741028543748275, 'weight_class_1': 8.02900517707537, 'weight_class_2': 7.90458240960187}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:37,822] Trial 1398 finished with value: 0.9496418192929612 and parameters: {'weight_class_0': 0.557475699113389, 'weight_class_1': 8.608143920278408, 'weight_class_2': 7.092969101485838}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:37,862] Trial 1399 finished with value: 0.9494622760250508 and parameters: {'weight_class_0': 0.5313786265623504, 'weight_class_1': 8.57195042131246, 'weight_class_2': 7.902250690082881}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:37,902] Trial 1401 finished with value: 0.9488091120759788 and parameters: {'weight_class_0': 1.0457149103800605, 'weight_class_1': 8.576690672155927, 'weight_class_2': 7.9379613155750315}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:37,913] Trial 1400 finished with value: 0.947885376178032 and parameters: {'weight_class_0': 0.24003197696652162, 'weight_class_1': 7.4651538070168035, 'weight_class_2': 7.97219420936907}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:37,937] Trial 1402 finished with value: 0.948447760310959 and parameters: {'weight_class_0': 1.0483896324511492, 'weight_class_1': 7.476850246456302, 'weight_class_2': 7.962956358903417}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:37,955] Trial 1403 finished with value: 0.9484256393416693 and parameters: {'weight_class_0': 1.0459367149016119, 'weight_class_1': 7.313157247434974, 'weight_class_2': 7.939296687626507}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:38,013] Trial 1404 finished with value: 0.9485004584465835 and parameters: {'weight_class_0': 1.043358925959487, 'weight_class_1': 7.504029589494167, 'weight_class_2': 7.9089731374415555}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:38,028] Trial 1405 finished with value: 0.9485883804723038 and parameters: {'weight_class_0': 1.033485236356344, 'weight_class_1': 7.47616123831938, 'weight_class_2': 7.983000791076734}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:38,058] Trial 1406 finished with value: 0.9486624590626073 and parameters: {'weight_class_0': 1.021778576655179, 'weight_class_1': 7.550206989704945, 'weight_class_2': 7.910567018017468}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:38,083] Trial 1407 finished with value: 0.9484962266459203 and parameters: {'weight_class_0': 1.0274431576056773, 'weight_class_1': 7.358118450607923, 'weight_class_2': 7.547429051961113}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:38,105] Trial 1408 finished with value: 0.9484498866121335 and parameters: {'weight_class_0': 1.0456120321478204, 'weight_class_1': 7.422515446210342, 'weight_class_2': 7.5837238830650895}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:38,161] Trial 1409 finished with value: 0.9483254681322425 and parameters: {'weight_class_0': 1.0926438361831257, 'weight_class_1': 7.57005349316168, 'weight_class_2': 7.508291817523331}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:38,171] Trial 1410 finished with value: 0.9485827139927867 and parameters: {'weight_class_0': 1.0392469881908837, 'weight_class_1': 7.591288588574979, 'weight_class_2': 7.54045760249867}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:38,183] Trial 1411 finished with value: 0.9485655681606238 and parameters: {'weight_class_0': 1.040652743818458, 'weight_class_1': 7.592605696767947, 'weight_class_2': 7.512905354177529}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:38,205] Trial 1412 finished with value: 0.9495910216380268 and parameters: {'weight_class_0': 0.7207539976495403, 'weight_class_1': 7.610402205771712, 'weight_class_2': 7.47929037435222}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:38,254] Trial 1413 finished with value: 0.9495778482085858 and parameters: {'weight_class_0': 0.7216903834101629, 'weight_class_1': 7.570596779506589, 'weight_class_2': 7.482937302062335}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:38,260] Trial 1414 finished with value: 0.9495540544989153 and parameters: {'weight_class_0': 0.733763626140213, 'weight_class_1': 7.769805352754545, 'weight_class_2': 7.532599772260329}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:38,306] Trial 1415 finished with value: 0.9496184345002346 and parameters: {'weight_class_0': 0.7166455068211317, 'weight_class_1': 7.875935251448436, 'weight_class_2': 7.522317924331555}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:38,313] Trial 1416 finished with value: 0.9470722841160405 and parameters: {'weight_class_0': 0.19434631110941047, 'weight_class_1': 7.839448171061128, 'weight_class_2': 7.524610969619757}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:38,351] Trial 1417 finished with value: 0.9480038026896903 and parameters: {'weight_class_0': 0.23849751918360346, 'weight_class_1': 7.598110555694854, 'weight_class_2': 7.479097452914042}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:38,356] Trial 1418 finished with value: 0.9479820871292265 and parameters: {'weight_class_0': 0.24206927311073978, 'weight_class_1': 7.877480425038891, 'weight_class_2': 7.540729248288477}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:38,401] Trial 1419 finished with value: 0.9470920994091214 and parameters: {'weight_class_0': 0.1942454252079916, 'weight_class_1': 7.7677749413623545, 'weight_class_2': 7.502795816360202}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:38,406] Trial 1420 finished with value: 0.9474318959630287 and parameters: {'weight_class_0': 0.23842307014872172, 'weight_class_1': 7.785288841336209, 'weight_class_2': 9.778916338293481}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:38,453] Trial 1421 finished with value: 0.9495571310674632 and parameters: {'weight_class_0': 0.7333982501010593, 'weight_class_1': 7.70224004186127, 'weight_class_2': 7.513268228819685}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  48%|██████████████████████████████████████████████████████████████▉                                                                     | 1430/3000 [00:31<00:40, 39.22it/s]

[I 2026-07-10 16:12:38,490] Trial 1422 finished with value: 0.94759196556378 and parameters: {'weight_class_0': 0.2171836927381337, 'weight_class_1': 7.751334717594635, 'weight_class_2': 7.539563148136849}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:38,494] Trial 1423 finished with value: 0.9468549051633558 and parameters: {'weight_class_0': 0.19243063462905075, 'weight_class_1': 7.690964705675403, 'weight_class_2': 8.43186849785702}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:38,536] Trial 1425 finished with value: 0.9472838153382358 and parameters: {'weight_class_0': 0.20968230442431723, 'weight_class_1': 7.762031363992234, 'weight_class_2': 8.201477893577566}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:38,545] Trial 1424 finished with value: 0.947393513104123 and parameters: {'weight_class_0': 0.2121729863861977, 'weight_class_1': 7.824516325556152, 'weight_class_2': 7.78930937878399}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:38,590] Trial 1426 finished with value: 0.9483045471600638 and parameters: {'weight_class_0': 0.29068874787052856, 'weight_class_1': 8.088770887032114, 'weight_class_2': 8.177707624531582}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:38,604] Trial 1427 finished with value: 0.9476546703112553 and parameters: {'weight_class_0': 0.22812306637332852, 'weight_class_1': 8.090020861005028, 'weight_class_2': 7.724957691193756}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:38,632] Trial 1428 finished with value: 0.9491646448849828 and parameters: {'weight_class_0': 0.4368989233258675, 'weight_class_1': 7.763948977626813, 'weight_class_2': 8.209355518626019}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:38,670] Trial 1429 finished with value: 0.9490773198764518 and parameters: {'weight_class_0': 0.43799305740477285, 'weight_class_1': 8.138522833779772, 'weight_class_2': 8.515711714302691}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:38,683] Trial 1430 finished with value: 0.9492564607219572 and parameters: {'weight_class_0': 0.446549827918301, 'weight_class_1': 8.089752243196356, 'weight_class_2': 7.778531604746081}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  48%|███████████████████████████████████████████████████████████████▎                                                                    | 1438/3000 [00:32<00:43, 36.08it/s]

[I 2026-07-10 16:12:38,716] Trial 1431 finished with value: 0.9492896786702851 and parameters: {'weight_class_0': 0.4514452143658838, 'weight_class_1': 8.08162231437221, 'weight_class_2': 7.747048832890417}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:38,735] Trial 1432 finished with value: 0.9491439910127811 and parameters: {'weight_class_0': 0.4448134914625085, 'weight_class_1': 8.113871592251352, 'weight_class_2': 8.35637042308965}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:38,758] Trial 1433 finished with value: 0.9109043194246634 and parameters: {'weight_class_0': 4.877295208924866, 'weight_class_1': 8.054386230107534, 'weight_class_2': 8.209852450322947}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:38,781] Trial 1434 finished with value: 0.9492734529333605 and parameters: {'weight_class_0': 0.46696137966184226, 'weight_class_1': 8.160715317534597, 'weight_class_2': 8.157616272630541}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:38,851] Trial 1435 finished with value: 0.9492702887320306 and parameters: {'weight_class_0': 0.4484077085322464, 'weight_class_1': 8.066465048639667, 'weight_class_2': 7.761027697788211}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:38,857] Trial 1437 finished with value: 0.9494264371379334 and parameters: {'weight_class_0': 0.5014326922077431, 'weight_class_1': 8.06995783425634, 'weight_class_2': 7.740930418415308}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:38,886] Trial 1436 finished with value: 0.9494112139298206 and parameters: {'weight_class_0': 0.475019137274063, 'weight_class_1': 8.055048416742808, 'weight_class_2': 7.681841508513147}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:38,887] Trial 1439 finished with value: 0.9494158531465038 and parameters: {'weight_class_0': 0.4939782241844248, 'weight_class_1': 8.092602004868915, 'weight_class_2': 7.772544004857764}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  48%|███████████████████████████████████████████████████████████████▋                                                                    | 1447/3000 [00:32<00:40, 37.99it/s]

[I 2026-07-10 16:12:38,911] Trial 1438 finished with value: 0.9496550697178624 and parameters: {'weight_class_0': 0.5240134086487029, 'weight_class_1': 8.076340893085598, 'weight_class_2': 6.965964159578501}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:38,975] Trial 1440 finished with value: 0.9496050153993917 and parameters: {'weight_class_0': 0.7494003149935828, 'weight_class_1': 8.084442620882418, 'weight_class_2': 7.819564634988198}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:38,985] Trial 1441 finished with value: 0.94962047418888 and parameters: {'weight_class_0': 0.703410561703662, 'weight_class_1': 8.14740841693218, 'weight_class_2': 6.951129918033878}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:38,992] Trial 1442 finished with value: 0.949615164048765 and parameters: {'weight_class_0': 0.7048835487250424, 'weight_class_1': 8.196582698705761, 'weight_class_2': 6.945571427643089}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:39,017] Trial 1443 finished with value: 0.9495932827370096 and parameters: {'weight_class_0': 0.7119055590817869, 'weight_class_1': 8.228343210903041, 'weight_class_2': 6.957571505047886}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:39,029] Trial 1444 finished with value: 0.9496001232431336 and parameters: {'weight_class_0': 0.6961846045689174, 'weight_class_1': 8.618045580648205, 'weight_class_2': 6.986562527658524}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:39,068] Trial 1445 finished with value: 0.9492457089098053 and parameters: {'weight_class_0': 0.7189128787988085, 'weight_class_1': 8.603798275408957, 'weight_class_2': 5.676965554126443}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:39,101] Trial 1446 finished with value: 0.9495546176789968 and parameters: {'weight_class_0': 0.770619611832393, 'weight_class_1': 8.533472117438745, 'weight_class_2': 7.346707059138281}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:39,132] Trial 1447 finished with value: 0.9495561100574021 and parameters: {'weight_class_0': 0.7057251451376528, 'weight_class_1': 8.661783715239945, 'weight_class_2': 6.706410985185162}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  48%|████████████████████████████████████████████████████████████████                                                                    | 1455/3000 [00:32<00:42, 35.95it/s]

[I 2026-07-10 16:12:39,155] Trial 1448 finished with value: 0.9495814982861471 and parameters: {'weight_class_0': 0.7456206499163446, 'weight_class_1': 8.56733681625193, 'weight_class_2': 7.259491363074594}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:39,200] Trial 1449 finished with value: 0.9496372579351373 and parameters: {'weight_class_0': 0.7187414918795623, 'weight_class_1': 8.632799667274307, 'weight_class_2': 7.2638222492933995}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:39,253] Trial 1450 finished with value: 0.9496184124852692 and parameters: {'weight_class_0': 0.7407822872553615, 'weight_class_1': 8.732659324721906, 'weight_class_2': 7.3028150797891636}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:39,261] Trial 1451 finished with value: 0.9493698185806293 and parameters: {'weight_class_0': 0.8340629255623822, 'weight_class_1': 8.64281847434244, 'weight_class_2': 7.33248463141131}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:39,280] Trial 1452 finished with value: 0.949356604444528 and parameters: {'weight_class_0': 0.8497324297667553, 'weight_class_1': 8.685632231595024, 'weight_class_2': 7.347650820652183}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:39,296] Trial 1453 finished with value: 0.9493361407902757 and parameters: {'weight_class_0': 0.8597563549411663, 'weight_class_1': 8.651341068493329, 'weight_class_2': 7.328186733677847}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:39,336] Trial 1455 finished with value: 0.9489629187147527 and parameters: {'weight_class_0': 0.9423046627822076, 'weight_class_1': 8.452896817782438, 'weight_class_2': 7.287599400665277}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:39,340] Trial 1454 finished with value: 0.942052905399562 and parameters: {'weight_class_0': 0.8651840793683058, 'weight_class_1': 2.3851317047271845, 'weight_class_2': 7.352186835913205}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  49%|████████████████████████████████████████████████████████████████▎                                                                   | 1463/3000 [00:32<00:41, 37.31it/s]

[I 2026-07-10 16:12:39,357] Trial 1456 finished with value: 0.9490347642064473 and parameters: {'weight_class_0': 0.9151940331578479, 'weight_class_1': 8.393416700658577, 'weight_class_2': 7.35554168567347}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:39,388] Trial 1457 finished with value: 0.949122058631656 and parameters: {'weight_class_0': 0.8937420195445711, 'weight_class_1': 8.426113298202242, 'weight_class_2': 7.304683765966197}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:39,418] Trial 1458 finished with value: 0.8637547979024323 and parameters: {'weight_class_0': 8.634203285024054, 'weight_class_1': 8.446448808136553, 'weight_class_2': 4.47047800290301}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:39,467] Trial 1459 finished with value: 0.9492523030611236 and parameters: {'weight_class_0': 0.8631892505776837, 'weight_class_1': 8.397062939614415, 'weight_class_2': 7.301778522974525}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:39,476] Trial 1460 finished with value: 0.8714838028597264 and parameters: {'weight_class_0': 6.75210927187371, 'weight_class_1': 4.735536641090218, 'weight_class_2': 7.2867212894380655}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:39,503] Trial 1461 finished with value: 0.9488381244224168 and parameters: {'weight_class_0': 1.0137558816280552, 'weight_class_1': 9.099668144644994, 'weight_class_2': 7.347689080356197}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:39,555] Trial 1462 finished with value: 0.9495530362904275 and parameters: {'weight_class_0': 0.57700259251956, 'weight_class_1': 9.084024022901, 'weight_class_2': 8.058806966986728}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:39,559] Trial 1463 finished with value: 0.949198705352016 and parameters: {'weight_class_0': 0.9410396429446259, 'weight_class_1': 8.389394275413741, 'weight_class_2': 8.095298459312549}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  49%|████████████████████████████████████████████████████████████████▋                                                                   | 1471/3000 [00:33<00:40, 38.02it/s]

[I 2026-07-10 16:12:39,603] Trial 1464 finished with value: 0.9495255295759767 and parameters: {'weight_class_0': 0.5680037009678034, 'weight_class_1': 9.073209258023736, 'weight_class_2': 8.05222510227752}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:39,643] Trial 1465 finished with value: 0.9494514594102075 and parameters: {'weight_class_0': 0.5316790700722736, 'weight_class_1': 9.070466662917301, 'weight_class_2': 8.103973633286888}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:39,644] Trial 1466 finished with value: 0.6574041512718217 and parameters: {'weight_class_0': 0.001760313118375989, 'weight_class_1': 8.280982930775227, 'weight_class_2': 8.077337729233443}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:39,665] Trial 1467 finished with value: 0.9494767247043115 and parameters: {'weight_class_0': 0.5225185613292409, 'weight_class_1': 7.190056689308998, 'weight_class_2': 7.623646336494927}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:39,716] Trial 1468 finished with value: 0.9495484710494719 and parameters: {'weight_class_0': 0.5721904994182467, 'weight_class_1': 7.168617930858269, 'weight_class_2': 7.649607020353583}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:39,726] Trial 1469 finished with value: 0.9495995848921569 and parameters: {'weight_class_0': 0.5669943283307352, 'weight_class_1': 8.283766715048584, 'weight_class_2': 7.6428203526722625}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:39,736] Trial 1470 finished with value: 0.9496139355402192 and parameters: {'weight_class_0': 0.5670322296484299, 'weight_class_1': 9.105297109136481, 'weight_class_2': 7.66767735238822}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:39,795] Trial 1471 finished with value: 0.9495341689568502 and parameters: {'weight_class_0': 0.5858713359708001, 'weight_class_1': 8.297284627379142, 'weight_class_2': 8.068313737330078}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:39,806] Trial 1472 finished with value: 0.9495502236404781 and parameters: {'weight_class_0': 0.579262228587179, 'weight_class_1': 9.094185924422288, 'weight_class_2': 8.102845762889324}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:39,819] Trial 1473 finished with value: 0.9492394788394857 and parameters: {'weight_class_0': 0.42402924672975306, 'weight_class_1': 8.28597722201756, 'weight_class_2': 7.634832737567597}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:39,853] Trial 1474 finished with value: 0.9489389713075896 and parameters: {'weight_class_0': 0.37433165494343473, 'weight_class_1': 8.288860305279545, 'weight_class_2': 7.627468289496583}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:39,899] Trial 1475 finished with value: 0.9482177300817641 and parameters: {'weight_class_0': 0.3376207115231348, 'weight_class_1': 3.5304075233034027, 'weight_class_2': 7.635320105320989}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:39,924] Trial 1476 finished with value: 0.9489972739824527 and parameters: {'weight_class_0': 0.3867167176672124, 'weight_class_1': 8.26919768475821, 'weight_class_2': 7.594028691983236}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:39,953] Trial 1478 finished with value: 0.9487751846258993 and parameters: {'weight_class_0': 0.3536324301146275, 'weight_class_1': 8.262304160487515, 'weight_class_2': 7.802139233354475}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:39,964] Trial 1477 finished with value: 0.9486696624258749 and parameters: {'weight_class_0': 0.3335971114806704, 'weight_class_1': 8.25586742952258, 'weight_class_2': 7.805912935273415}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:40,005] Trial 1481 finished with value: 0.9490477135040981 and parameters: {'weight_class_0': 0.3577054184672705, 'weight_class_1': 8.857900206422842, 'weight_class_2': 6.666942767750993}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  50%|█████████████████████████████████████████████████████████████████▍                                                                  | 1487/3000 [00:33<00:41, 36.84it/s]

[I 2026-07-10 16:12:40,012] Trial 1480 finished with value: 0.9485320794140352 and parameters: {'weight_class_0': 0.308913947339245, 'weight_class_1': 7.913190321585523, 'weight_class_2': 7.862854985669632}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:40,020] Trial 1479 finished with value: 0.9486803019735538 and parameters: {'weight_class_0': 0.3445708179329284, 'weight_class_1': 8.783027420655069, 'weight_class_2': 7.847763900321408}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:40,072] Trial 1482 finished with value: 0.9489870678439735 and parameters: {'weight_class_0': 0.37221894020961177, 'weight_class_1': 8.794067977616983, 'weight_class_2': 7.112627212640104}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:40,112] Trial 1483 finished with value: 0.9470198832472105 and parameters: {'weight_class_0': 1.3585449174221553, 'weight_class_1': 7.876027920710338, 'weight_class_2': 7.109373196559407}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:40,122] Trial 1484 finished with value: 0.9479798038810997 and parameters: {'weight_class_0': 1.2345693419351118, 'weight_class_1': 8.81347663666113, 'weight_class_2': 7.091404082340104}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:40,158] Trial 1485 finished with value: 0.948772213155982 and parameters: {'weight_class_0': 0.32159404942750375, 'weight_class_1': 7.912999414652867, 'weight_class_2': 7.086812942645887}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:40,181] Trial 1486 finished with value: 0.9482794212432744 and parameters: {'weight_class_0': 1.1006419010800605, 'weight_class_1': 7.940537034895472, 'weight_class_2': 7.057957115948421}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:40,211] Trial 1487 finished with value: 0.9479413986655268 and parameters: {'weight_class_0': 1.1940808951608726, 'weight_class_1': 8.780609823533096, 'weight_class_2': 6.634205446425703}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  50%|█████████████████████████████████████████████████████████████████▊                                                                  | 1495/3000 [00:33<00:39, 38.28it/s]

[I 2026-07-10 16:12:40,252] Trial 1489 finished with value: 0.9474140139076516 and parameters: {'weight_class_0': 1.3063440818550252, 'weight_class_1': 7.927921570421921, 'weight_class_2': 7.14256764266751}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:40,261] Trial 1488 finished with value: 0.9484588865905544 and parameters: {'weight_class_0': 1.1087718746596087, 'weight_class_1': 8.790625404145386, 'weight_class_2': 7.107050281099073}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:40,271] Trial 1490 finished with value: 0.946724899514931 and parameters: {'weight_class_0': 1.251829661270698, 'weight_class_1': 6.224998586539204, 'weight_class_2': 7.092750255979872}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:40,303] Trial 1491 finished with value: 0.947013849140878 and parameters: {'weight_class_0': 1.3609560044146427, 'weight_class_1': 7.914900579269285, 'weight_class_2': 7.090597533238653}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:40,342] Trial 1493 finished with value: 0.9478344156906721 and parameters: {'weight_class_0': 1.3003519349964305, 'weight_class_1': 9.407369126611083, 'weight_class_2': 7.1122383257878266}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:40,388] Trial 1492 finished with value: 0.9273864390276692 and parameters: {'weight_class_0': 1.201403176268326, 'weight_class_1': 1.7791956517254692, 'weight_class_2': 7.138990197725615}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:40,405] Trial 1494 finished with value: 0.949354732131641 and parameters: {'weight_class_0': 0.7214229883670062, 'weight_class_1': 6.3172317036273675, 'weight_class_2': 7.45590566869718}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:40,438] Trial 1495 finished with value: 0.949678033321686 and parameters: {'weight_class_0': 0.7209250967855005, 'weight_class_1': 8.456874619889769, 'weight_class_2': 7.458249567727376}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  50%|██████████████████████████████████████████████████████████████████▏                                                                 | 1503/3000 [00:33<00:40, 36.97it/s]

[I 2026-07-10 16:12:40,490] Trial 1496 finished with value: 0.9496207352856253 and parameters: {'weight_class_0': 0.7364214521529089, 'weight_class_1': 8.484297510910658, 'weight_class_2': 7.473234911799202}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:40,506] Trial 1498 finished with value: 0.8983327389507099 and parameters: {'weight_class_0': 5.781733561875321, 'weight_class_1': 8.536660144295851, 'weight_class_2': 7.42747783050233}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:40,511] Trial 1497 finished with value: 0.9496035200678771 and parameters: {'weight_class_0': 0.7464554336967232, 'weight_class_1': 8.504143958968076, 'weight_class_2': 7.479900367501977}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:40,534] Trial 1500 finished with value: 0.9410094624795623 and parameters: {'weight_class_0': 0.7079531541479455, 'weight_class_1': 1.7861041978807886, 'weight_class_2': 7.475519366382319}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:40,557] Trial 1499 finished with value: 0.9496139954602717 and parameters: {'weight_class_0': 0.7435891801065032, 'weight_class_1': 8.480764358199014, 'weight_class_2': 7.437796079084244}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:40,611] Trial 1501 finished with value: 0.949514737106369 and parameters: {'weight_class_0': 0.7847359053093561, 'weight_class_1': 8.478434107992424, 'weight_class_2': 7.462314142952198}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:40,617] Trial 1502 finished with value: 0.9391310668656733 and parameters: {'weight_class_0': 2.4593621015232707, 'weight_class_1': 8.526519130539171, 'weight_class_2': 7.461016147534939}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:40,655] Trial 1503 finished with value: 0.9496947207022369 and parameters: {'weight_class_0': 0.7106972651596081, 'weight_class_1': 8.489326328461393, 'weight_class_2': 7.4890389220627185}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  50%|██████████████████████████████████████████████████████████████████▍                                                                 | 1511/3000 [00:34<00:41, 36.11it/s]

[I 2026-07-10 16:12:40,683] Trial 1504 finished with value: 0.9496964430877958 and parameters: {'weight_class_0': 0.7277417056962495, 'weight_class_1': 8.452849712154315, 'weight_class_2': 7.5580347847846605}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:40,711] Trial 1505 finished with value: 0.9497043409671181 and parameters: {'weight_class_0': 0.7042255154396122, 'weight_class_1': 8.476320595785838, 'weight_class_2': 7.462674670546094}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:40,724] Trial 1506 finished with value: 0.9323581134297335 and parameters: {'weight_class_0': 0.9377200215329642, 'weight_class_1': 8.466352818043083, 'weight_class_2': 1.7319208174676564}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:40,750] Trial 1507 finished with value: 0.9491433504333008 and parameters: {'weight_class_0': 0.9068162716600745, 'weight_class_1': 8.49708174780511, 'weight_class_2': 7.502990477264049}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:40,799] Trial 1508 finished with value: 0.9491160665890863 and parameters: {'weight_class_0': 0.9257249009501614, 'weight_class_1': 7.728713746133459, 'weight_class_2': 7.817203701219109}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:40,811] Trial 1510 finished with value: 0.9490152030787877 and parameters: {'weight_class_0': 0.9605735177808072, 'weight_class_1': 8.163780071232392, 'weight_class_2': 7.832175114996869}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:40,834] Trial 1509 finished with value: 0.949370386577192 and parameters: {'weight_class_0': 0.8337672236191938, 'weight_class_1': 8.187405844969001, 'weight_class_2': 7.838671868147396}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:40,880] Trial 1511 finished with value: 0.9492074616536627 and parameters: {'weight_class_0': 0.8758380117513012, 'weight_class_1': 7.736154249133387, 'weight_class_2': 7.805739241320348}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:40,883] Trial 1512 finished with value: 0.9490016032742674 and parameters: {'weight_class_0': 0.9543868032061145, 'weight_class_1': 7.725190604162914, 'weight_class_2': 7.871771454344274}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:40,922] Trial 1514 finished with value: 0.9490151501387984 and parameters: {'weight_class_0': 0.9483662082644492, 'weight_class_1': 8.182705969724363, 'weight_class_2': 7.740924906364443}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:40,941] Trial 1513 finished with value: 0.9488199246431228 and parameters: {'weight_class_0': 0.9866129331260187, 'weight_class_1': 7.723846254798731, 'weight_class_2': 7.862516642062589}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:40,961] Trial 1515 finished with value: 0.9491473703378984 and parameters: {'weight_class_0': 0.9301062827579397, 'weight_class_1': 8.182598930563314, 'weight_class_2': 7.8631263893225585}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:40,987] Trial 1516 finished with value: 0.9432142221429581 and parameters: {'weight_class_0': 0.12172393627169409, 'weight_class_1': 8.130527091224053, 'weight_class_2': 7.771967928766481}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:41,041] Trial 1517 finished with value: 0.9457353474045048 and parameters: {'weight_class_0': 1.681050505786205, 'weight_class_1': 8.210811631877556, 'weight_class_2': 7.857961483036703}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:41,071] Trial 1518 finished with value: 0.9484032809150663 and parameters: {'weight_class_0': 0.9074626682303305, 'weight_class_1': 5.523097519460017, 'weight_class_2': 7.841163280066215}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:41,076] Trial 1519 finished with value: 0.9172460517999202 and parameters: {'weight_class_0': 3.347654530571954, 'weight_class_1': 5.54350752425411, 'weight_class_2': 6.829051803542202}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:41,082] Trial 1520 finished with value: 0.9465271509650418 and parameters: {'weight_class_0': 0.17123451534915546, 'weight_class_1': 8.041942048192235, 'weight_class_2': 6.829940902404195}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:41,171] Trial 1522 finished with value: 0.9456251776945191 and parameters: {'weight_class_0': 1.7225496864599266, 'weight_class_1': 8.073371769501513, 'weight_class_2': 8.502626053974824}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:41,172] Trial 1521 finished with value: 0.9454583235599324 and parameters: {'weight_class_0': 1.6955379764905845, 'weight_class_1': 8.166612797479717, 'weight_class_2': 7.67991992770972}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:41,220] Trial 1523 finished with value: 0.9444607254344081 and parameters: {'weight_class_0': 0.13055078251175234, 'weight_class_1': 8.033846820128494, 'weight_class_2': 6.881339663343597}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:41,224] Trial 1524 finished with value: 0.9097782336642001 and parameters: {'weight_class_0': 0.052188072795371965, 'weight_class_1': 8.007245798081833, 'weight_class_2': 6.9116020138242185}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:41,262] Trial 1526 finished with value: 0.9494197215736443 and parameters: {'weight_class_0': 0.5565975433887195, 'weight_class_1': 8.757736589786449, 'weight_class_2': 8.454214624520706}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:41,270] Trial 1525 finished with value: 0.9496404917817031 and parameters: {'weight_class_0': 0.5209703106870843, 'weight_class_1': 8.705518962303596, 'weight_class_2': 6.866475905737199}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:41,302] Trial 1527 finished with value: 0.9452253993539051 and parameters: {'weight_class_0': 1.679909153677659, 'weight_class_1': 8.696611422688349, 'weight_class_2': 6.87502098681349}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:41,316] Trial 1528 finished with value: 0.949348257394279 and parameters: {'weight_class_0': 0.5088837226283245, 'weight_class_1': 8.689763702675616, 'weight_class_2': 8.42103711920399}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  51%|███████████████████████████████████████████████████████████████████▋                                                                | 1537/3000 [00:34<00:39, 37.09it/s]

[I 2026-07-10 16:12:41,380] Trial 1530 finished with value: 0.9494901787368523 and parameters: {'weight_class_0': 0.5034427348597933, 'weight_class_1': 8.705374512652048, 'weight_class_2': 7.265132715322229}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:41,395] Trial 1529 finished with value: 0.9495075510757642 and parameters: {'weight_class_0': 0.5205016928651771, 'weight_class_1': 8.651421871827596, 'weight_class_2': 7.613113145042805}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:41,425] Trial 1531 finished with value: 0.9494034773839298 and parameters: {'weight_class_0': 0.5253522569774252, 'weight_class_1': 8.74036275640538, 'weight_class_2': 8.545289111873108}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:41,445] Trial 1532 finished with value: 0.9493949556434057 and parameters: {'weight_class_0': 0.47812818918209055, 'weight_class_1': 8.767114701670017, 'weight_class_2': 7.229353435668329}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:41,500] Trial 1534 finished with value: 0.9496270457007392 and parameters: {'weight_class_0': 0.5456554345304159, 'weight_class_1': 8.64085742423547, 'weight_class_2': 7.213164104371815}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:41,509] Trial 1533 finished with value: 0.9495191603638596 and parameters: {'weight_class_0': 0.5144436277441587, 'weight_class_1': 8.736733881312198, 'weight_class_2': 7.303470418473817}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:41,521] Trial 1535 finished with value: 0.949493605157977 and parameters: {'weight_class_0': 0.50439130339078, 'weight_class_1': 8.723633609976542, 'weight_class_2': 7.248140748770908}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:41,542] Trial 1536 finished with value: 0.9496146136005681 and parameters: {'weight_class_0': 0.5368010899187156, 'weight_class_1': 9.44893642202529, 'weight_class_2': 7.235528028481217}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:41,572] Trial 1538 finished with value: 0.9343159993833344 and parameters: {'weight_class_0': 0.597684198281115, 'weight_class_1': 1.0959120375496845, 'weight_class_2': 8.04047360748726}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:41,602] Trial 1537 finished with value: 0.9496921015573343 and parameters: {'weight_class_0': 0.5791839192603769, 'weight_class_1': 8.982177794752968, 'weight_class_2': 7.219932903195279}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:41,641] Trial 1539 finished with value: 0.94973260983327 and parameters: {'weight_class_0': 0.5948391297960823, 'weight_class_1': 8.98971928625591, 'weight_class_2': 7.29963459302137}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:41,663] Trial 1540 finished with value: 0.949692782241657 and parameters: {'weight_class_0': 0.684374839445387, 'weight_class_1': 8.970373296843018, 'weight_class_2': 7.270594301613314}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:41,708] Trial 1542 finished with value: 0.9497067502077217 and parameters: {'weight_class_0': 0.6207236112962677, 'weight_class_1': 8.99139343164935, 'weight_class_2': 7.299093893944267}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:41,718] Trial 1541 finished with value: 0.949702134170079 and parameters: {'weight_class_0': 0.6707615844760659, 'weight_class_1': 8.896585053804596, 'weight_class_2': 7.262216441628854}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:41,746] Trial 1544 finished with value: 0.9497126277686445 and parameters: {'weight_class_0': 0.6457241191960682, 'weight_class_1': 9.032049847375418, 'weight_class_2': 7.991311600657405}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:41,757] Trial 1543 finished with value: 0.9496567937404542 and parameters: {'weight_class_0': 0.6344195240465523, 'weight_class_1': 9.00205279245402, 'weight_class_2': 7.276578305852168}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:41,796] Trial 1545 finished with value: 0.9496245343479259 and parameters: {'weight_class_0': 0.6297842662172745, 'weight_class_1': 8.294185315307814, 'weight_class_2': 8.082494050727501}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:41,834] Trial 1546 finished with value: 0.9497356009818233 and parameters: {'weight_class_0': 0.679519318881946, 'weight_class_1': 8.956278463764049, 'weight_class_2': 7.600701346615869}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:41,860] Trial 1547 finished with value: 0.9484749918141411 and parameters: {'weight_class_0': 0.27072931571403347, 'weight_class_1': 8.97122152561775, 'weight_class_2': 5.90246736072564}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:41,884] Trial 1548 finished with value: 0.9482392086647161 and parameters: {'weight_class_0': 0.2735340279902123, 'weight_class_1': 8.307597961468195, 'weight_class_2': 7.639235802992607}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:41,918] Trial 1549 finished with value: 0.9472369483847082 and parameters: {'weight_class_0': 0.20960478979143388, 'weight_class_1': 8.31843415404259, 'weight_class_2': 7.609349274968623}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:41,960] Trial 1551 finished with value: 0.9489711008723171 and parameters: {'weight_class_0': 0.23282041458566832, 'weight_class_1': 8.302729553895224, 'weight_class_2': 2.93322497873925}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:41,968] Trial 1550 finished with value: 0.9482710002226161 and parameters: {'weight_class_0': 0.2842430242235452, 'weight_class_1': 8.308562302376764, 'weight_class_2': 8.038297748394422}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:41,986] Trial 1552 finished with value: 0.9480473675881735 and parameters: {'weight_class_0': 0.2539194716969607, 'weight_class_1': 8.308204741893539, 'weight_class_2': 7.619033818692013}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:42,030] Trial 1553 finished with value: 0.9486012263957256 and parameters: {'weight_class_0': 0.3086910122468986, 'weight_class_1': 8.272289505677637, 'weight_class_2': 7.55229757251675}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:42,077] Trial 1554 finished with value: 0.948462111917503 and parameters: {'weight_class_0': 1.1236126759355876, 'weight_class_1': 8.363288992128844, 'weight_class_2': 7.596952616678608}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:42,091] Trial 1555 finished with value: 0.9478919130791494 and parameters: {'weight_class_0': 0.24245847863188086, 'weight_class_1': 8.26513598264412, 'weight_class_2': 7.634159941596129}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:42,106] Trial 1557 finished with value: 0.863521884231611 and parameters: {'weight_class_0': 9.381788987524907, 'weight_class_1': 6.787228052976315, 'weight_class_2': 7.639164232446688}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:42,107] Trial 1556 finished with value: 0.9483845767445754 and parameters: {'weight_class_0': 0.28710871487406947, 'weight_class_1': 8.333144448367715, 'weight_class_2': 7.620406674700621}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:42,158] Trial 1558 finished with value: 0.9486797326584581 and parameters: {'weight_class_0': 1.081409441509349, 'weight_class_1': 8.313859275077034, 'weight_class_2': 8.30450618426633}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:42,184] Trial 1559 finished with value: 0.948439806949725 and parameters: {'weight_class_0': 1.136518150926712, 'weight_class_1': 8.331506821615674, 'weight_class_2': 7.638616892814362}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:42,202] Trial 1560 finished with value: 0.9485440709212799 and parameters: {'weight_class_0': 1.1084220221563748, 'weight_class_1': 8.296083106910569, 'weight_class_2': 7.641082613055361}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  52%|████████████████████████████████████████████████████████████████████▉                                                               | 1568/3000 [00:35<00:39, 35.85it/s]

[I 2026-07-10 16:12:42,230] Trial 1561 finished with value: 0.9488099694495911 and parameters: {'weight_class_0': 1.0766140335446583, 'weight_class_1': 9.336691794814078, 'weight_class_2': 7.622190629681727}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:42,300] Trial 1563 finished with value: 0.9482905081607452 and parameters: {'weight_class_0': 1.1338505662917748, 'weight_class_1': 7.902346621386309, 'weight_class_2': 7.610650055032909}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:42,314] Trial 1562 finished with value: 0.9484117052870498 and parameters: {'weight_class_0': 1.108061478286045, 'weight_class_1': 7.947377811608801, 'weight_class_2': 7.671904525334847}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:42,338] Trial 1564 finished with value: 0.9484648638404543 and parameters: {'weight_class_0': 1.1227468396562128, 'weight_class_1': 7.939454391875603, 'weight_class_2': 8.29990458285901}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:42,365] Trial 1565 finished with value: 0.9485458691792497 and parameters: {'weight_class_0': 1.1025411058910974, 'weight_class_1': 7.989601065490388, 'weight_class_2': 7.970368341012311}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:42,388] Trial 1567 finished with value: 0.9484192771019018 and parameters: {'weight_class_0': 1.0925575195037216, 'weight_class_1': 7.943738931249593, 'weight_class_2': 7.422401804030541}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:42,396] Trial 1566 finished with value: 0.9486214594438674 and parameters: {'weight_class_0': 1.0715089951065369, 'weight_class_1': 7.8230278041448225, 'weight_class_2': 8.329771646417036}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:42,432] Trial 1568 finished with value: 0.9492894144379784 and parameters: {'weight_class_0': 0.8566014768943664, 'weight_class_1': 7.897394791191537, 'weight_class_2': 7.987352268249387}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:42,453] Trial 1569 finished with value: 0.6933056613198816 and parameters: {'weight_class_0': 0.013932045350491085, 'weight_class_1': 7.896867911509221, 'weight_class_2': 7.421767327381869}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:42,469] Trial 1570 finished with value: 0.9493093172610448 and parameters: {'weight_class_0': 0.8710166132107178, 'weight_class_1': 7.96906849454166, 'weight_class_2': 8.273928452857444}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:42,515] Trial 1571 finished with value: 0.949344816624517 and parameters: {'weight_class_0': 0.8399308888640223, 'weight_class_1': 7.94606079097846, 'weight_class_2': 7.908473698446626}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:42,538] Trial 1572 finished with value: 0.9472979808646994 and parameters: {'weight_class_0': 0.8056804264182665, 'weight_class_1': 4.222625843622886, 'weight_class_2': 5.192392184548471}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:42,570] Trial 1573 finished with value: 0.6873740200908282 and parameters: {'weight_class_0': 0.013750540867792371, 'weight_class_1': 7.966888565786929, 'weight_class_2': 7.986542764166302}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:42,594] Trial 1574 finished with value: 0.9494555701265696 and parameters: {'weight_class_0': 0.8096097387862461, 'weight_class_1': 7.977386946411553, 'weight_class_2': 8.273345602861028}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:42,630] Trial 1576 finished with value: 0.949223771728558 and parameters: {'weight_class_0': 0.8512567155117416, 'weight_class_1': 7.7097279601867745, 'weight_class_2': 7.409894916308626}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:42,667] Trial 1575 finished with value: 0.9487093014751401 and parameters: {'weight_class_0': 0.8422003380405542, 'weight_class_1': 5.791042462274836, 'weight_class_2': 7.40700058880371}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  53%|█████████████████████████████████████████████████████████████████████▋                                                              | 1583/3000 [00:36<00:39, 36.10it/s]

[I 2026-07-10 16:12:42,690] Trial 1577 finished with value: 0.9490681606123533 and parameters: {'weight_class_0': 0.8492377854147107, 'weight_class_1': 7.434277055331779, 'weight_class_2': 7.047091625553459}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:42,691] Trial 1578 finished with value: 0.9493988650725648 and parameters: {'weight_class_0': 0.8236363546620397, 'weight_class_1': 8.552653445225438, 'weight_class_2': 7.419428823915726}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:42,700] Trial 1579 finished with value: 0.9493886574693344 and parameters: {'weight_class_0': 0.7476023158315163, 'weight_class_1': 7.370204984558195, 'weight_class_2': 7.063216457896217}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:42,765] Trial 1580 finished with value: 0.9491039905609528 and parameters: {'weight_class_0': 0.8368782822613494, 'weight_class_1': 7.408808677631797, 'weight_class_2': 6.991702218888418}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:42,778] Trial 1581 finished with value: 0.9493723656131762 and parameters: {'weight_class_0': 0.7961860205062863, 'weight_class_1': 8.534748755508538, 'weight_class_2': 6.992252182335673}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:42,853] Trial 1582 finished with value: 0.949128309797555 and parameters: {'weight_class_0': 0.3854895620436307, 'weight_class_1': 8.549294316309991, 'weight_class_2': 7.007007744695203}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:42,884] Trial 1583 finished with value: 0.9487299302577158 and parameters: {'weight_class_0': 0.4295372125783067, 'weight_class_1': 8.548400435162254, 'weight_class_2': 2.691601319308783}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  53%|██████████████████████████████████████████████████████████████████████                                                              | 1591/3000 [00:36<00:39, 35.89it/s]

[I 2026-07-10 16:12:42,900] Trial 1584 finished with value: 0.9492453917432929 and parameters: {'weight_class_0': 0.4140953498381473, 'weight_class_1': 8.54749827651587, 'weight_class_2': 6.998593932462566}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:42,921] Trial 1585 finished with value: 0.9492288794227127 and parameters: {'weight_class_0': 0.42219007400060066, 'weight_class_1': 8.569395189355385, 'weight_class_2': 7.4491728736037475}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:42,950] Trial 1586 finished with value: 0.9493823160650298 and parameters: {'weight_class_0': 0.4614991384839099, 'weight_class_1': 8.5398996280494, 'weight_class_2': 7.0088717775647575}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:42,972] Trial 1587 finished with value: 0.9494719529692307 and parameters: {'weight_class_0': 0.485018313170248, 'weight_class_1': 8.530677611554083, 'weight_class_2': 6.980808661870155}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:42,999] Trial 1588 finished with value: 0.9493707528189116 and parameters: {'weight_class_0': 0.42281494161506217, 'weight_class_1': 8.57104718088769, 'weight_class_2': 6.638035940319561}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:43,023] Trial 1590 finished with value: 0.9493905786465174 and parameters: {'weight_class_0': 0.42979384536265897, 'weight_class_1': 8.497253192281097, 'weight_class_2': 6.571461689801637}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:43,037] Trial 1591 finished with value: 0.9493235184441615 and parameters: {'weight_class_0': 0.4156801738740241, 'weight_class_1': 8.570045980474006, 'weight_class_2': 6.691684747805751}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:43,039] Trial 1589 finished with value: 0.9447924758883114 and parameters: {'weight_class_0': 0.3786696488373279, 'weight_class_1': 8.548004154644893, 'weight_class_2': 1.247313314107747}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:43,095] Trial 1592 finished with value: 0.9491716742519539 and parameters: {'weight_class_0': 0.3830566777878909, 'weight_class_1': 8.505118300511523, 'weight_class_2': 6.643665729417078}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:43,109] Trial 1593 finished with value: 0.9492185796375838 and parameters: {'weight_class_0': 0.399499564142188, 'weight_class_1': 9.18338548151829, 'weight_class_2': 6.653545671647294}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:43,148] Trial 1594 finished with value: 0.9493498211987753 and parameters: {'weight_class_0': 0.4291145227858186, 'weight_class_1': 9.216596541448109, 'weight_class_2': 6.688599661033355}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:43,173] Trial 1595 finished with value: 0.9493624019260909 and parameters: {'weight_class_0': 0.43398512031319575, 'weight_class_1': 9.21223764472382, 'weight_class_2': 6.5038120233807755}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:43,174] Trial 1596 finished with value: 0.9491551228207203 and parameters: {'weight_class_0': 0.4254405060870248, 'weight_class_1': 9.201244666692187, 'weight_class_2': 7.785609212246277}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:43,252] Trial 1597 finished with value: 0.9497107077608545 and parameters: {'weight_class_0': 0.6533577120754478, 'weight_class_1': 9.247434457768236, 'weight_class_2': 7.772914398552863}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:43,260] Trial 1598 finished with value: 0.9496912876504645 and parameters: {'weight_class_0': 0.6699025459039435, 'weight_class_1': 9.302252660515544, 'weight_class_2': 7.784368620532368}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:43,279] Trial 1599 finished with value: 0.9497229026551836 and parameters: {'weight_class_0': 0.720819476867152, 'weight_class_1': 9.169128345427126, 'weight_class_2': 7.756740281098583}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  54%|██████████████████████████████████████████████████████████████████████▋                                                             | 1607/3000 [00:36<00:38, 36.46it/s]

[I 2026-07-10 16:12:43,310] Trial 1600 finished with value: 0.9497087466019057 and parameters: {'weight_class_0': 0.6589750028876064, 'weight_class_1': 8.151805879061975, 'weight_class_2': 7.864558879882951}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:43,359] Trial 1601 finished with value: 0.9496829471560604 and parameters: {'weight_class_0': 0.6978550413735145, 'weight_class_1': 8.131633798308778, 'weight_class_2': 7.716404128723916}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:43,409] Trial 1602 finished with value: 0.9496939414471344 and parameters: {'weight_class_0': 0.6857709510860583, 'weight_class_1': 8.104618319519007, 'weight_class_2': 7.810514287865209}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:43,414] Trial 1604 finished with value: 0.9496820935217576 and parameters: {'weight_class_0': 0.6737642673990901, 'weight_class_1': 8.145697774315874, 'weight_class_2': 7.792232011950314}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:43,418] Trial 1603 finished with value: 0.9496811811391911 and parameters: {'weight_class_0': 0.6771889971190517, 'weight_class_1': 8.153759391439314, 'weight_class_2': 7.83362343448664}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:43,453] Trial 1605 finished with value: 0.9496611366203043 and parameters: {'weight_class_0': 0.6649008966858619, 'weight_class_1': 8.154929660950733, 'weight_class_2': 7.781308111159669}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:43,495] Trial 1606 finished with value: 0.949683701191617 and parameters: {'weight_class_0': 0.671737496667588, 'weight_class_1': 8.149454915837184, 'weight_class_2': 7.835691866884227}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:43,510] Trial 1607 finished with value: 0.9497062537351942 and parameters: {'weight_class_0': 0.6869985197838577, 'weight_class_1': 8.13819642227036, 'weight_class_2': 7.815216603850503}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  54%|███████████████████████████████████████████████████████████████████████                                                             | 1615/3000 [00:37<00:38, 36.44it/s]

[I 2026-07-10 16:12:43,546] Trial 1608 finished with value: 0.9484096306415745 and parameters: {'weight_class_0': 0.6551177573830758, 'weight_class_1': 3.823966764303191, 'weight_class_2': 7.386800795685917}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:43,553] Trial 1609 finished with value: 0.9497428660281141 and parameters: {'weight_class_0': 0.6599838234389963, 'weight_class_1': 8.186185464113823, 'weight_class_2': 7.410418053271548}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:43,632] Trial 1610 finished with value: 0.9464650241931185 and parameters: {'weight_class_0': 1.4660450645445642, 'weight_class_1': 7.673056763427231, 'weight_class_2': 7.414804584914321}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:43,636] Trial 1611 finished with value: 0.948859341297566 and parameters: {'weight_class_0': 0.9665922886239184, 'weight_class_1': 8.154844049765911, 'weight_class_2': 7.359236872036598}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:43,675] Trial 1612 finished with value: 0.9487140271446369 and parameters: {'weight_class_0': 0.9821683399814339, 'weight_class_1': 7.634621537244707, 'weight_class_2': 7.396463584737373}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:43,688] Trial 1613 finished with value: 0.9490007270492448 and parameters: {'weight_class_0': 0.9412018379349565, 'weight_class_1': 8.808386404799723, 'weight_class_2': 7.390632698576325}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:43,731] Trial 1614 finished with value: 0.9459975226406562 and parameters: {'weight_class_0': 0.157953036222439, 'weight_class_1': 7.730892432909882, 'weight_class_2': 7.461704754060724}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:43,752] Trial 1615 finished with value: 0.9192372453234223 and parameters: {'weight_class_0': 3.9495538333582036, 'weight_class_1': 7.673573264236762, 'weight_class_2': 7.391652820203773}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:43,761] Trial 1616 finished with value: 0.9464679861487637 and parameters: {'weight_class_0': 1.4627286762367242, 'weight_class_1': 7.6578460636255095, 'weight_class_2': 7.4029369296240075}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:43,791] Trial 1617 finished with value: 0.9488824915368835 and parameters: {'weight_class_0': 0.9459297187899699, 'weight_class_1': 7.689438054591188, 'weight_class_2': 7.386288631827678}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:43,843] Trial 1618 finished with value: 0.9490178078108861 and parameters: {'weight_class_0': 0.9118812381972886, 'weight_class_1': 8.80248057164252, 'weight_class_2': 7.1976672932574095}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:43,848] Trial 1619 finished with value: 0.9487174745320148 and parameters: {'weight_class_0': 0.9734221076077626, 'weight_class_1': 7.645250283588899, 'weight_class_2': 7.197568561594591}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:43,880] Trial 1620 finished with value: 0.9472369595692638 and parameters: {'weight_class_0': 1.4115536244471532, 'weight_class_1': 7.744438794335526, 'weight_class_2': 8.105109472194073}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:43,885] Trial 1621 finished with value: 0.942498254120347 and parameters: {'weight_class_0': 0.11162718201152577, 'weight_class_1': 7.668242997019009, 'weight_class_2': 8.125774077949314}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:43,946] Trial 1622 finished with value: 0.9441807425178151 and parameters: {'weight_class_0': 0.14234660367130825, 'weight_class_1': 8.838804113988848, 'weight_class_2': 8.140827318256886}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  54%|███████████████████████████████████████████████████████████████████████▊                                                            | 1631/3000 [00:37<00:37, 36.10it/s]

[I 2026-07-10 16:12:43,960] Trial 1623 finished with value: 0.9471950990765682 and parameters: {'weight_class_0': 0.21325832991180138, 'weight_class_1': 8.857527556887824, 'weight_class_2': 7.20338571898274}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:43,989] Trial 1624 finished with value: 0.9399156624217267 and parameters: {'weight_class_0': 0.10739786148475294, 'weight_class_1': 8.854166814595567, 'weight_class_2': 8.097161006579404}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:44,009] Trial 1625 finished with value: 0.9492384409340121 and parameters: {'weight_class_0': 0.9379139999809347, 'weight_class_1': 8.816742332674593, 'weight_class_2': 8.184919552491625}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:44,032] Trial 1626 finished with value: 0.9457543518853129 and parameters: {'weight_class_0': 0.16601849347938324, 'weight_class_1': 8.89572028713842, 'weight_class_2': 7.167116371796052}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:44,062] Trial 1627 finished with value: 0.9466709240813286 and parameters: {'weight_class_0': 0.1904080358964737, 'weight_class_1': 8.343473509745404, 'weight_class_2': 8.032421660670597}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:44,093] Trial 1629 finished with value: 0.9466016816513879 and parameters: {'weight_class_0': 0.18925581858376012, 'weight_class_1': 8.35886512830194, 'weight_class_2': 8.12193895307294}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:44,094] Trial 1628 finished with value: 0.9489732794942443 and parameters: {'weight_class_0': 0.9260282179564933, 'weight_class_1': 8.320796194994312, 'weight_class_2': 7.175216891428468}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:44,179] Trial 1630 finished with value: 0.9495413117108781 and parameters: {'weight_class_0': 0.5023639389683756, 'weight_class_1': 8.402849804781226, 'weight_class_2': 7.1292715787987015}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:44,189] Trial 1632 finished with value: 0.9496575143708351 and parameters: {'weight_class_0': 0.5453238835258635, 'weight_class_1': 8.428942444665005, 'weight_class_2': 7.154219650606479}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:44,193] Trial 1631 finished with value: 0.6589938771319696 and parameters: {'weight_class_0': 0.006750560684577689, 'weight_class_1': 8.345202438599383, 'weight_class_2': 7.179564406176526}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:44,224] Trial 1633 finished with value: 0.9496337194353185 and parameters: {'weight_class_0': 0.549479393801394, 'weight_class_1': 8.378050858332001, 'weight_class_2': 7.5565116640188625}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:44,306] Trial 1634 finished with value: 0.9496027065852259 and parameters: {'weight_class_0': 0.5606114987276868, 'weight_class_1': 8.371144671673843, 'weight_class_2': 7.560271455893581}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:44,331] Trial 1636 finished with value: 0.9497095920095536 and parameters: {'weight_class_0': 0.6117156345492435, 'weight_class_1': 8.434746041487676, 'weight_class_2': 7.567936093912432}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:44,333] Trial 1635 finished with value: 0.9496136871497605 and parameters: {'weight_class_0': 0.5553192160555398, 'weight_class_1': 8.383874981610822, 'weight_class_2': 7.575925224185988}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:44,354] Trial 1637 finished with value: 0.9495083420169005 and parameters: {'weight_class_0': 0.5396134942338776, 'weight_class_1': 8.01409004435701, 'weight_class_2': 7.586681708011854}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:44,419] Trial 1639 finished with value: 0.9495672992723961 and parameters: {'weight_class_0': 0.5620491152463563, 'weight_class_1': 8.026234580711204, 'weight_class_2': 7.606494902486732}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  55%|████████████████████████████████████████████████████████████████████████▍                                                           | 1646/3000 [00:37<00:36, 36.69it/s]

[I 2026-07-10 16:12:44,420] Trial 1640 finished with value: 0.9496234098970123 and parameters: {'weight_class_0': 0.550903515284046, 'weight_class_1': 8.397050343623933, 'weight_class_2': 7.535471301274044}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:44,441] Trial 1638 finished with value: 0.9496382196752376 and parameters: {'weight_class_0': 0.5516914152094323, 'weight_class_1': 8.392227919135259, 'weight_class_2': 7.582885424005732}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:44,471] Trial 1641 finished with value: 0.949584582382519 and parameters: {'weight_class_0': 0.567826836035445, 'weight_class_1': 7.979891711023677, 'weight_class_2': 7.556353925434899}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:44,490] Trial 1642 finished with value: 0.9494934762582076 and parameters: {'weight_class_0': 0.7886157951223436, 'weight_class_1': 7.974403745669679, 'weight_class_2': 7.583782944277193}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:44,506] Trial 1643 finished with value: 0.9495036590530787 and parameters: {'weight_class_0': 0.7879714317020088, 'weight_class_1': 8.049662414950104, 'weight_class_2': 7.597446964398146}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:44,528] Trial 1644 finished with value: 0.9494986595520906 and parameters: {'weight_class_0': 0.7735557296777602, 'weight_class_1': 8.047742060788543, 'weight_class_2': 7.582251660823643}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:44,575] Trial 1645 finished with value: 0.9494858574887747 and parameters: {'weight_class_0': 0.8398883480542845, 'weight_class_1': 9.55605603506806, 'weight_class_2': 7.644499828535129}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:44,592] Trial 1646 finished with value: 0.9490878506267504 and parameters: {'weight_class_0': 0.7947031469040303, 'weight_class_1': 8.019554450042635, 'weight_class_2': 6.263879093724177}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  55%|████████████████████████████████████████████████████████████████████████▊                                                           | 1655/3000 [00:38<00:37, 36.17it/s]

[I 2026-07-10 16:12:44,655] Trial 1647 finished with value: 0.9494491224257819 and parameters: {'weight_class_0': 0.7995869952504221, 'weight_class_1': 8.000562471247838, 'weight_class_2': 7.622658521750231}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:44,667] Trial 1648 finished with value: 0.9493029068693096 and parameters: {'weight_class_0': 0.8894660274562957, 'weight_class_1': 8.67944003163401, 'weight_class_2': 7.946218846541384}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:44,693] Trial 1649 finished with value: 0.9494037201586755 and parameters: {'weight_class_0': 0.8663192706775671, 'weight_class_1': 8.697264876628704, 'weight_class_2': 7.97439556260276}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:44,714] Trial 1650 finished with value: 0.949493238093884 and parameters: {'weight_class_0': 0.7981817835528386, 'weight_class_1': 8.131558014797339, 'weight_class_2': 7.988805458334803}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:44,766] Trial 1651 finished with value: 0.9494666952087782 and parameters: {'weight_class_0': 0.8175799932784327, 'weight_class_1': 8.164058724177865, 'weight_class_2': 7.950282000738187}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:44,773] Trial 1653 finished with value: 0.8770404057805575 and parameters: {'weight_class_0': 8.06031170802871, 'weight_class_1': 8.18656297140416, 'weight_class_2': 7.902073147724236}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:44,789] Trial 1652 finished with value: 0.9495359792628354 and parameters: {'weight_class_0': 0.8109101165812418, 'weight_class_1': 8.706224293270658, 'weight_class_2': 7.960850659804997}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:44,825] Trial 1654 finished with value: 0.94847375521984 and parameters: {'weight_class_0': 1.2056504350277275, 'weight_class_1': 9.563697215637955, 'weight_class_2': 7.966061760745114}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:44,841] Trial 1655 finished with value: 0.9489221290543693 and parameters: {'weight_class_0': 1.0116569015300374, 'weight_class_1': 8.625779634723877, 'weight_class_2': 7.972418361637748}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  55%|█████████████████████████████████████████████████████████████████████████▏                                                          | 1663/3000 [00:38<00:37, 35.64it/s]

[I 2026-07-10 16:12:44,902] Trial 1656 finished with value: 0.9487050611085769 and parameters: {'weight_class_0': 0.3532483446199578, 'weight_class_1': 8.659239533171815, 'weight_class_2': 7.941906954164827}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:44,923] Trial 1657 finished with value: 0.9483807683837053 and parameters: {'weight_class_0': 1.1906025141425196, 'weight_class_1': 8.70053906892631, 'weight_class_2': 7.9011992957778245}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:44,961] Trial 1658 finished with value: 0.9482267940892427 and parameters: {'weight_class_0': 1.2030567217488848, 'weight_class_1': 8.62317511789589, 'weight_class_2': 7.949984468890128}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:44,996] Trial 1659 finished with value: 0.9479548101849541 and parameters: {'weight_class_0': 1.2463068343717636, 'weight_class_1': 8.610980810128234, 'weight_class_2': 7.297610696809465}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:45,025] Trial 1661 finished with value: 0.9481365687362091 and parameters: {'weight_class_0': 1.2082307435983473, 'weight_class_1': 8.67937170736539, 'weight_class_2': 7.269772190714052}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:45,029] Trial 1660 finished with value: 0.9483000684230571 and parameters: {'weight_class_0': 1.1705730919219337, 'weight_class_1': 8.67522608893911, 'weight_class_2': 7.340961170574629}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:45,042] Trial 1662 finished with value: 0.9488869869453597 and parameters: {'weight_class_0': 0.34536709729591, 'weight_class_1': 8.679063746154167, 'weight_class_2': 6.857707682891395}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:45,059] Trial 1663 finished with value: 0.9478491339940093 and parameters: {'weight_class_0': 1.216807921755168, 'weight_class_1': 8.689779131915548, 'weight_class_2': 6.87314028973902}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  56%|█████████████████████████████████████████████████████████████████████████▍                                                          | 1670/3000 [00:38<00:36, 36.59it/s]

[I 2026-07-10 16:12:45,084] Trial 1664 finished with value: 0.9481111238281654 and parameters: {'weight_class_0': 1.2192621605168545, 'weight_class_1': 8.624123079068998, 'weight_class_2': 7.30272881338617}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:45,140] Trial 1665 finished with value: 0.9481858310088439 and parameters: {'weight_class_0': 0.2743658399168577, 'weight_class_1': 9.000751308753136, 'weight_class_2': 7.298595397320104}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:45,204] Trial 1666 finished with value: 0.9488464682376957 and parameters: {'weight_class_0': 0.34021167496027394, 'weight_class_1': 8.649689560280445, 'weight_class_2': 6.880127440688263}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:45,212] Trial 1668 finished with value: 0.9488073991612708 and parameters: {'weight_class_0': 0.32107797154426976, 'weight_class_1': 7.812955328752773, 'weight_class_2': 6.855682155270463}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:45,230] Trial 1667 finished with value: 0.9486712131823829 and parameters: {'weight_class_0': 0.32033700320524916, 'weight_class_1': 9.060031415311867, 'weight_class_2': 6.864997134412633}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:45,264] Trial 1669 finished with value: 0.9487792796958975 and parameters: {'weight_class_0': 0.347054672583918, 'weight_class_1': 9.082062343682734, 'weight_class_2': 7.271385224791848}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:45,305] Trial 1670 finished with value: 0.9490272565422647 and parameters: {'weight_class_0': 0.35044091043664416, 'weight_class_1': 7.838772106515804, 'weight_class_2': 6.807245190605126}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:45,313] Trial 1671 finished with value: 0.9485121185545681 and parameters: {'weight_class_0': 0.29043707804587976, 'weight_class_1': 8.226796728331545, 'weight_class_2': 6.830085321658072}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:45,335] Trial 1672 finished with value: 0.9484745253081558 and parameters: {'weight_class_0': 0.3032825779593362, 'weight_class_1': 9.074636419786088, 'weight_class_2': 7.351757169290325}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:45,392] Trial 1674 finished with value: 0.94900811567302 and parameters: {'weight_class_0': 0.35928576802630124, 'weight_class_1': 7.874750483603212, 'weight_class_2': 7.129825468672497}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:45,414] Trial 1675 finished with value: 0.948774039619919 and parameters: {'weight_class_0': 0.3222660664929756, 'weight_class_1': 7.83175613299075, 'weight_class_2': 7.136726191390702}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:45,422] Trial 1673 finished with value: 0.9491724494593571 and parameters: {'weight_class_0': 0.40828111261069183, 'weight_class_1': 9.037778815011904, 'weight_class_2': 7.083773419331108}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:45,451] Trial 1676 finished with value: 0.948918965899356 and parameters: {'weight_class_0': 0.3435261659784949, 'weight_class_1': 7.816557763266987, 'weight_class_2': 7.050719904180995}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:45,500] Trial 1677 finished with value: 0.9492513249632619 and parameters: {'weight_class_0': 0.3911116907963228, 'weight_class_1': 7.8035684456411065, 'weight_class_2': 7.023062168991381}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  56%|██████████████████████████████████████████████████████████████████████████▏                                                         | 1686/3000 [00:39<00:35, 36.54it/s]

[I 2026-07-10 16:12:45,545] Trial 1678 finished with value: 0.9497275417690698 and parameters: {'weight_class_0': 0.659452435553435, 'weight_class_1': 8.187439686814953, 'weight_class_2': 7.097486349495981}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:45,549] Trial 1680 finished with value: 0.94974203016805 and parameters: {'weight_class_0': 0.6350392809926276, 'weight_class_1': 8.206265375001731, 'weight_class_2': 7.079474605622525}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:45,550] Trial 1679 finished with value: 0.9497357382597832 and parameters: {'weight_class_0': 0.6420286678536682, 'weight_class_1': 8.231953441995966, 'weight_class_2': 7.074571491637513}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:45,599] Trial 1681 finished with value: 0.9476680244637219 and parameters: {'weight_class_0': 0.6789960382596018, 'weight_class_1': 8.284210816090663, 'weight_class_2': 3.1439817318817385}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:45,628] Trial 1682 finished with value: 0.9497072639766776 and parameters: {'weight_class_0': 0.6555179623357534, 'weight_class_1': 8.207149373100755, 'weight_class_2': 7.73958062098304}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:45,646] Trial 1683 finished with value: 0.9497224488270254 and parameters: {'weight_class_0': 0.6768416482445224, 'weight_class_1': 8.215016225712322, 'weight_class_2': 7.04960807491059}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:45,675] Trial 1684 finished with value: 0.9496797739134161 and parameters: {'weight_class_0': 0.6659241333917432, 'weight_class_1': 8.219867140329562, 'weight_class_2': 7.771919386979395}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:45,703] Trial 1685 finished with value: 0.9496183326887012 and parameters: {'weight_class_0': 0.6051819674532137, 'weight_class_1': 8.254660104688606, 'weight_class_2': 7.71659176560763}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:45,721] Trial 1686 finished with value: 0.9497464764477269 and parameters: {'weight_class_0': 0.6603885831745959, 'weight_class_1': 8.237176597610963, 'weight_class_2': 7.43046456098189}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:45,751] Trial 1687 finished with value: 0.9497002783771253 and parameters: {'weight_class_0': 0.6570548928840471, 'weight_class_1': 8.17916973259724, 'weight_class_2': 7.740408735222176}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:45,814] Trial 1688 finished with value: 0.949729398507939 and parameters: {'weight_class_0': 0.6779517514566327, 'weight_class_1': 8.225188007778451, 'weight_class_2': 7.409295901198711}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:45,817] Trial 1689 finished with value: 0.9489292292668247 and parameters: {'weight_class_0': 0.9829722284091995, 'weight_class_1': 8.410218855010807, 'weight_class_2': 7.71624527191079}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:45,882] Trial 1690 finished with value: 0.9488255852859059 and parameters: {'weight_class_0': 1.0356209339479907, 'weight_class_1': 8.438849007179073, 'weight_class_2': 7.717665856877249}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:45,905] Trial 1691 finished with value: 0.949150583061357 and parameters: {'weight_class_0': 1.009880954668487, 'weight_class_1': 8.408447103615623, 'weight_class_2': 8.62639474631608}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:45,921] Trial 1693 finished with value: 0.9488824892623252 and parameters: {'weight_class_0': 0.9783665745223697, 'weight_class_1': 8.410036683522504, 'weight_class_2': 7.427533991482233}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:45,937] Trial 1692 finished with value: 0.9492276846016684 and parameters: {'weight_class_0': 0.9859483942041698, 'weight_class_1': 9.423613437122478, 'weight_class_2': 8.296683264255307}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  57%|██████████████████████████████████████████████████████████████████████████▊                                                         | 1701/3000 [00:39<00:36, 35.99it/s]

[I 2026-07-10 16:12:45,939] Trial 1694 finished with value: 0.9491900261486262 and parameters: {'weight_class_0': 0.9691025505866878, 'weight_class_1': 8.439249438744241, 'weight_class_2': 8.26334614666344}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:46,016] Trial 1696 finished with value: 0.9487075991842562 and parameters: {'weight_class_0': 1.0230431194827962, 'weight_class_1': 8.08140278943636, 'weight_class_2': 7.396574230589982}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:46,036] Trial 1697 finished with value: 0.9489882792848254 and parameters: {'weight_class_0': 0.9346777643330894, 'weight_class_1': 8.420423912280304, 'weight_class_2': 7.378607999555383}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:46,041] Trial 1695 finished with value: 0.9484938889675161 and parameters: {'weight_class_0': 0.962767124186368, 'weight_class_1': 7.452510446516522, 'weight_class_2': 6.411761863543023}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:46,060] Trial 1698 finished with value: 0.9488776104909046 and parameters: {'weight_class_0': 0.9736859438276289, 'weight_class_1': 8.4147965302532, 'weight_class_2': 7.431703296902854}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:46,094] Trial 1699 finished with value: 0.6576469652814285 and parameters: {'weight_class_0': 0.0035081623408581564, 'weight_class_1': 8.011570088038537, 'weight_class_2': 6.4874489430245585}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:46,147] Trial 1700 finished with value: 0.7181517760713026 and parameters: {'weight_class_0': 0.01573687944430735, 'weight_class_1': 7.981567866231741, 'weight_class_2': 6.420171417610237}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:46,172] Trial 1701 finished with value: 0.7697399976589249 and parameters: {'weight_class_0': 0.02022453290120063, 'weight_class_1': 7.497031937734885, 'weight_class_2': 6.402564773164924}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  57%|███████████████████████████████████████████████████████████████████████████▏                                                        | 1708/3000 [00:39<00:38, 33.23it/s]

[I 2026-07-10 16:12:46,204] Trial 1702 finished with value: 0.9494438618410804 and parameters: {'weight_class_0': 0.493773496064599, 'weight_class_1': 8.015041394393208, 'weight_class_2': 7.388514579456318}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:46,247] Trial 1704 finished with value: 0.9344594329194358 and parameters: {'weight_class_0': 2.7673810303429334, 'weight_class_1': 8.026229213640384, 'weight_class_2': 7.223232066547002}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:46,250] Trial 1703 finished with value: 0.9495879722064539 and parameters: {'weight_class_0': 0.5244472333776979, 'weight_class_1': 7.912736771278638, 'weight_class_2': 7.222389081324957}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:46,290] Trial 1705 finished with value: 0.9494461629966321 and parameters: {'weight_class_0': 0.46440828894767633, 'weight_class_1': 7.926263572823825, 'weight_class_2': 7.240585655887094}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:46,302] Trial 1706 finished with value: 0.7099480174933192 and parameters: {'weight_class_0': 0.015222965122268284, 'weight_class_1': 7.509519089686935, 'weight_class_2': 7.223050664719029}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:46,359] Trial 1707 finished with value: 0.9495086552722873 and parameters: {'weight_class_0': 0.4917928899376161, 'weight_class_1': 7.885835135142495, 'weight_class_2': 7.191719643933425}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:46,372] Trial 1708 finished with value: 0.9495194459272627 and parameters: {'weight_class_0': 0.5089024388770528, 'weight_class_1': 7.981119914906998, 'weight_class_2': 7.181787427133607}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  57%|███████████████████████████████████████████████████████████████████████████▌                                                        | 1716/3000 [00:39<00:36, 34.93it/s]

[I 2026-07-10 16:12:46,394] Trial 1710 finished with value: 0.9495311157652222 and parameters: {'weight_class_0': 0.5058753797484393, 'weight_class_1': 7.967626187677464, 'weight_class_2': 7.207130072718606}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:46,404] Trial 1709 finished with value: 0.9494656659517823 and parameters: {'weight_class_0': 0.4766156754139531, 'weight_class_1': 8.040664073342368, 'weight_class_2': 7.169305215825989}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:46,444] Trial 1711 finished with value: 0.9494883225737376 and parameters: {'weight_class_0': 0.48401160898956097, 'weight_class_1': 8.035797479191613, 'weight_class_2': 7.162317121532506}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:46,494] Trial 1712 finished with value: 0.94966878763569 and parameters: {'weight_class_0': 0.5294934659785664, 'weight_class_1': 8.020054125792425, 'weight_class_2': 6.830553724470775}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:46,498] Trial 1713 finished with value: 0.9323906927972169 and parameters: {'weight_class_0': 2.9218948251491432, 'weight_class_1': 7.8994881783955675, 'weight_class_2': 7.2027750445558745}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:46,505] Trial 1714 finished with value: 0.9495132624124377 and parameters: {'weight_class_0': 0.48255576444105075, 'weight_class_1': 7.861976860691498, 'weight_class_2': 6.903043067267075}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:46,572] Trial 1715 finished with value: 0.8631316191674072 and parameters: {'weight_class_0': 9.98236764252595, 'weight_class_1': 8.194508217148488, 'weight_class_2': 6.9070131593222435}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:46,597] Trial 1716 finished with value: 0.9493719870816747 and parameters: {'weight_class_0': 0.7683126108668957, 'weight_class_1': 8.241440757190905, 'weight_class_2': 6.7897243615186955}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  57%|███████████████████████████████████████████████████████████████████████████▊                                                        | 1724/3000 [00:40<00:35, 36.19it/s]

[I 2026-07-10 16:12:46,621] Trial 1717 finished with value: 0.9495862673895403 and parameters: {'weight_class_0': 0.494394033903097, 'weight_class_1': 8.214521791610922, 'weight_class_2': 6.728142810344866}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:46,654] Trial 1718 finished with value: 0.9495780414872935 and parameters: {'weight_class_0': 0.6863759888115867, 'weight_class_1': 8.21638809738769, 'weight_class_2': 6.732707869237522}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:46,697] Trial 1719 finished with value: 0.9493813782235465 and parameters: {'weight_class_0': 0.7854115222459183, 'weight_class_1': 8.248286734235506, 'weight_class_2': 6.911505700798774}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:46,725] Trial 1721 finished with value: 0.9493734906731559 and parameters: {'weight_class_0': 0.7692498254479203, 'weight_class_1': 8.230429263667357, 'weight_class_2': 6.760785794302149}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:46,727] Trial 1720 finished with value: 0.9494955609685772 and parameters: {'weight_class_0': 0.7417840773443078, 'weight_class_1': 8.247920960662485, 'weight_class_2': 6.885259475472735}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:46,764] Trial 1722 finished with value: 0.8863697779791787 and parameters: {'weight_class_0': 0.7792268916070082, 'weight_class_1': 0.16000894447758363, 'weight_class_2': 7.511898053909633}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:46,796] Trial 1724 finished with value: 0.9494671078573181 and parameters: {'weight_class_0': 0.7907870228700253, 'weight_class_1': 8.245167996700799, 'weight_class_2': 7.491360033013188}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:46,828] Trial 1723 finished with value: 0.9494512016980381 and parameters: {'weight_class_0': 0.7950542138793845, 'weight_class_1': 8.242899077608604, 'weight_class_2': 7.467021515191229}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  58%|████████████████████████████████████████████████████████████████████████████▏                                                       | 1731/3000 [00:40<00:36, 34.52it/s]

[I 2026-07-10 16:12:46,849] Trial 1725 finished with value: 0.9495473384616683 and parameters: {'weight_class_0': 0.7738277975050445, 'weight_class_1': 8.22299237089567, 'weight_class_2': 7.473287985497477}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:46,916] Trial 1726 finished with value: 0.9495283810151575 and parameters: {'weight_class_0': 0.7727807307776585, 'weight_class_1': 8.424544590393044, 'weight_class_2': 7.392202793971607}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:46,930] Trial 1727 finished with value: 0.949617887942883 and parameters: {'weight_class_0': 0.7376782192878824, 'weight_class_1': 8.475701915649113, 'weight_class_2': 7.4536969510338125}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:46,955] Trial 1728 finished with value: 0.9496049785348375 and parameters: {'weight_class_0': 0.7588861328258477, 'weight_class_1': 8.464031353731972, 'weight_class_2': 7.507512366797381}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:46,961] Trial 1729 finished with value: 0.9495229579609434 and parameters: {'weight_class_0': 0.7843055589229094, 'weight_class_1': 8.455543580897208, 'weight_class_2': 7.499910925665939}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:47,007] Trial 1730 finished with value: 0.9495048650534216 and parameters: {'weight_class_0': 0.7875218848825432, 'weight_class_1': 8.408954619640484, 'weight_class_2': 7.480114304621932}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:47,017] Trial 1731 finished with value: 0.9474750418622552 and parameters: {'weight_class_0': 0.22109899453371318, 'weight_class_1': 8.442318948952446, 'weight_class_2': 7.510098140151389}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  58%|████████████████████████████████████████████████████████████████████████████▌                                                       | 1739/3000 [00:40<00:35, 35.41it/s]

[I 2026-07-10 16:12:47,039] Trial 1732 finished with value: 0.9495655442832893 and parameters: {'weight_class_0': 0.7716334903667447, 'weight_class_1': 8.420296219675121, 'weight_class_2': 7.474849444842254}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:47,052] Trial 1733 finished with value: 0.947407950467511 and parameters: {'weight_class_0': 0.1988763238474015, 'weight_class_1': 7.206842321354294, 'weight_class_2': 7.463411427896067}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:47,089] Trial 1734 finished with value: 0.9482053223064199 and parameters: {'weight_class_0': 0.26762835393482015, 'weight_class_1': 8.498093554091945, 'weight_class_2': 7.525830177307399}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:47,146] Trial 1736 finished with value: 0.9470340799203063 and parameters: {'weight_class_0': 0.20109102359358744, 'weight_class_1': 8.429282149835625, 'weight_class_2': 7.4636599467114255}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:47,178] Trial 1735 finished with value: 0.9480050823906824 and parameters: {'weight_class_0': 0.24756560852338266, 'weight_class_1': 8.469231926311645, 'weight_class_2': 7.422597537610221}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:47,179] Trial 1737 finished with value: 0.9473536317501475 and parameters: {'weight_class_0': 0.21502350425023825, 'weight_class_1': 8.462745817004375, 'weight_class_2': 7.457160241473458}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:47,230] Trial 1738 finished with value: 0.8791780336685117 and parameters: {'weight_class_0': 7.75928052620174, 'weight_class_1': 8.51846233976342, 'weight_class_2': 7.594604792945951}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:47,251] Trial 1740 finished with value: 0.9455438830299308 and parameters: {'weight_class_0': 0.15773455186953694, 'weight_class_1': 8.437660037209591, 'weight_class_2': 7.688173567788531}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  58%|████████████████████████████████████████████████████████████████████████████▊                                                       | 1746/3000 [00:40<00:36, 34.60it/s]

[I 2026-07-10 16:12:47,258] Trial 1741 finished with value: 0.9470554324774083 and parameters: {'weight_class_0': 0.19109012396721958, 'weight_class_1': 7.595036128180437, 'weight_class_2': 7.668158134464421}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:47,287] Trial 1739 finished with value: 0.9072944767561247 and parameters: {'weight_class_0': 5.082279524821589, 'weight_class_1': 8.425034843169657, 'weight_class_2': 7.682936219187889}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:47,328] Trial 1742 finished with value: 0.9466673736358254 and parameters: {'weight_class_0': 0.17377962305321193, 'weight_class_1': 7.792482416433161, 'weight_class_2': 7.027194662410937}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:47,387] Trial 1743 finished with value: 0.9469525598950984 and parameters: {'weight_class_0': 0.1830566892300537, 'weight_class_1': 7.755946467578033, 'weight_class_2': 7.025397995329443}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:47,415] Trial 1744 finished with value: 0.9169741092717935 and parameters: {'weight_class_0': 4.217159612799939, 'weight_class_1': 7.722216946726788, 'weight_class_2': 7.743360252037981}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:47,435] Trial 1745 finished with value: 0.9474658304038078 and parameters: {'weight_class_0': 0.2037825329935542, 'weight_class_1': 7.6793442773714435, 'weight_class_2': 7.038794014969943}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:47,459] Trial 1746 finished with value: 0.946566482075887 and parameters: {'weight_class_0': 1.416452450431812, 'weight_class_1': 7.826322841336773, 'weight_class_2': 7.045011046392093}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  58%|█████████████████████████████████████████████████████████████████████████████▏                                                      | 1753/3000 [00:40<00:38, 32.55it/s]

[I 2026-07-10 16:12:47,487] Trial 1748 finished with value: 0.94944972166879 and parameters: {'weight_class_0': 0.5445428109195432, 'weight_class_1': 7.680319616815161, 'weight_class_2': 7.7241004890567275}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:47,515] Trial 1747 finished with value: 0.9466439182774845 and parameters: {'weight_class_0': 1.388305236034661, 'weight_class_1': 7.661753599369644, 'weight_class_2': 7.01972942433485}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:47,554] Trial 1749 finished with value: 0.949456253234591 and parameters: {'weight_class_0': 0.5403006188799905, 'weight_class_1': 7.7604420546556545, 'weight_class_2': 7.73807540495258}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:47,570] Trial 1750 finished with value: 0.949654746133544 and parameters: {'weight_class_0': 0.5569697643027061, 'weight_class_1': 7.732621309000345, 'weight_class_2': 7.031069296471225}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:47,604] Trial 1751 finished with value: 0.9495960950993146 and parameters: {'weight_class_0': 0.5280986351905105, 'weight_class_1': 7.742611063195104, 'weight_class_2': 7.147481547675019}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:47,626] Trial 1752 finished with value: 0.9496016571302924 and parameters: {'weight_class_0': 0.5327123165391143, 'weight_class_1': 7.67262633853361, 'weight_class_2': 7.0402916258179875}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:47,654] Trial 1753 finished with value: 0.947034986643212 and parameters: {'weight_class_0': 1.3700946339170825, 'weight_class_1': 8.101671251499194, 'weight_class_2': 7.084532911522745}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  59%|█████████████████████████████████████████████████████████████████████████████▍                                                      | 1761/3000 [00:41<00:36, 33.75it/s]

[I 2026-07-10 16:12:47,672] Trial 1754 finished with value: 0.9467136817494067 and parameters: {'weight_class_0': 1.4155698634904643, 'weight_class_1': 8.08119108948193, 'weight_class_2': 7.047856177509893}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:47,721] Trial 1756 finished with value: 0.9495620212421256 and parameters: {'weight_class_0': 0.524318751336713, 'weight_class_1': 8.817379031663148, 'weight_class_2': 7.266985601270709}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:47,738] Trial 1755 finished with value: 0.9413068522114151 and parameters: {'weight_class_0': 2.144075535321048, 'weight_class_1': 8.098468303855993, 'weight_class_2': 7.241667405781733}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:47,762] Trial 1757 finished with value: 0.9496587064057337 and parameters: {'weight_class_0': 0.5781132689845082, 'weight_class_1': 8.082266850656183, 'weight_class_2': 7.3168868778630785}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:47,826] Trial 1758 finished with value: 0.9494823831343076 and parameters: {'weight_class_0': 0.4987385196098681, 'weight_class_1': 8.838426656452535, 'weight_class_2': 7.273559429003463}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:47,829] Trial 1759 finished with value: 0.9496329791263015 and parameters: {'weight_class_0': 0.5519402665396428, 'weight_class_1': 8.123504092688659, 'weight_class_2': 7.280872348333916}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:47,845] Trial 1760 finished with value: 0.94885439868147 and parameters: {'weight_class_0': 1.0012714228169515, 'weight_class_1': 8.831539066082158, 'weight_class_2': 7.288615720570138}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:47,887] Trial 1761 finished with value: 0.9485752540433214 and parameters: {'weight_class_0': 1.0581964228861924, 'weight_class_1': 8.106362514490566, 'weight_class_2': 7.273186158604308}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  59%|█████████████████████████████████████████████████████████████████████████████▊                                                      | 1769/3000 [00:41<00:35, 34.98it/s]

[I 2026-07-10 16:12:47,904] Trial 1762 finished with value: 0.9469711532832862 and parameters: {'weight_class_0': 0.9848559488830675, 'weight_class_1': 8.808584694160327, 'weight_class_2': 4.213656002531064}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:47,954] Trial 1764 finished with value: 0.9469708506255315 and parameters: {'weight_class_0': 1.0466702443654021, 'weight_class_1': 4.993730607128399, 'weight_class_2': 7.3264531284942285}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:47,957] Trial 1763 finished with value: 0.9488928119514165 and parameters: {'weight_class_0': 0.9737006347482255, 'weight_class_1': 8.852152667355123, 'weight_class_2': 7.324667516537577}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:47,989] Trial 1765 finished with value: 0.9488582504574211 and parameters: {'weight_class_0': 1.0083119916776493, 'weight_class_1': 8.804564401229728, 'weight_class_2': 7.325868655535229}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:48,040] Trial 1766 finished with value: 0.9489350605517178 and parameters: {'weight_class_0': 0.948818310970887, 'weight_class_1': 8.639646900778377, 'weight_class_2': 7.295491187482326}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:48,075] Trial 1767 finished with value: 0.9492478045200085 and parameters: {'weight_class_0': 0.9183848705874715, 'weight_class_1': 8.77556089824814, 'weight_class_2': 7.783824221807192}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:48,095] Trial 1768 finished with value: 0.9489733957031543 and parameters: {'weight_class_0': 0.9859565433555565, 'weight_class_1': 8.838758491506526, 'weight_class_2': 7.742364508225646}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:48,117] Trial 1769 finished with value: 0.9489787934760511 and parameters: {'weight_class_0': 0.9830449291108159, 'weight_class_1': 8.619240424268108, 'weight_class_2': 7.778895447142883}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  59%|██████████████████████████████████████████████████████████████████████████████▏                                                     | 1776/3000 [00:41<00:35, 34.22it/s]

[I 2026-07-10 16:12:48,151] Trial 1770 finished with value: 0.9043276207202187 and parameters: {'weight_class_0': 0.9910317755005831, 'weight_class_1': 8.650023016845505, 'weight_class_2': 0.8049794619747361}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:48,196] Trial 1772 finished with value: 0.9492043873312136 and parameters: {'weight_class_0': 0.9219241640686531, 'weight_class_1': 8.611535794274609, 'weight_class_2': 7.7650841318301485}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:48,199] Trial 1771 finished with value: 0.9490020472179923 and parameters: {'weight_class_0': 0.9702651530083617, 'weight_class_1': 8.632484108650484, 'weight_class_2': 7.759497403531593}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:48,219] Trial 1773 finished with value: 0.94919166623672 and parameters: {'weight_class_0': 0.9250468153913612, 'weight_class_1': 8.683630907113587, 'weight_class_2': 7.736845538899868}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:48,262] Trial 1774 finished with value: 0.9489376786947176 and parameters: {'weight_class_0': 0.3790159927230249, 'weight_class_1': 8.56096678229556, 'weight_class_2': 7.775794666693382}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:48,274] Trial 1775 finished with value: 0.9489082778295481 and parameters: {'weight_class_0': 0.3767890964847055, 'weight_class_1': 8.595659339910501, 'weight_class_2': 7.753186611541711}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:48,359] Trial 1776 finished with value: 0.9497113068880342 and parameters: {'weight_class_0': 0.664910057845292, 'weight_class_1': 8.624047152398406, 'weight_class_2': 7.740830413946895}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:48,360] Trial 1777 finished with value: 0.9488207522741362 and parameters: {'weight_class_0': 0.36285884329460716, 'weight_class_1': 8.620042682685167, 'weight_class_2': 7.7479525480302005}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:48,376] Trial 1778 finished with value: 0.9492554632200721 and parameters: {'weight_class_0': 0.4305899663710462, 'weight_class_1': 8.606964372898165, 'weight_class_2': 7.7017631557109345}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:48,398] Trial 1779 finished with value: 0.9492706984559204 and parameters: {'weight_class_0': 0.43267387807355195, 'weight_class_1': 8.326697630116122, 'weight_class_2': 7.61876018311578}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:48,448] Trial 1780 finished with value: 0.9490540443869097 and parameters: {'weight_class_0': 0.39536542376023986, 'weight_class_1': 8.2548250575932, 'weight_class_2': 7.629342094177603}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:48,473] Trial 1781 finished with value: 0.9496999766765164 and parameters: {'weight_class_0': 0.6869460056349258, 'weight_class_1': 8.28891665377437, 'weight_class_2': 7.648931191550753}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:48,490] Trial 1782 finished with value: 0.9489366578159123 and parameters: {'weight_class_0': 0.3725172755106342, 'weight_class_1': 8.282403654960584, 'weight_class_2': 7.60040938367212}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:48,501] Trial 1783 finished with value: 0.9489573446821028 and parameters: {'weight_class_0': 0.37177246246335116, 'weight_class_1': 8.311889117799387, 'weight_class_2': 7.553385535207642}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:48,541] Trial 1784 finished with value: 0.949685171521745 and parameters: {'weight_class_0': 0.7154510292180515, 'weight_class_1': 8.268930145530065, 'weight_class_2': 7.5703322388860155}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  60%|██████████████████████████████████████████████████████████████████████████████▊                                                     | 1791/3000 [00:42<00:34, 35.50it/s]

[I 2026-07-10 16:12:48,555] Trial 1785 finished with value: 0.9497376959467871 and parameters: {'weight_class_0': 0.614541230256167, 'weight_class_1': 8.283363633519457, 'weight_class_2': 7.555321169178046}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:48,592] Trial 1786 finished with value: 0.9497196364444406 and parameters: {'weight_class_0': 0.6665725738089452, 'weight_class_1': 8.289891644595695, 'weight_class_2': 7.5647405537246755}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:48,612] Trial 1787 finished with value: 0.9496768676168169 and parameters: {'weight_class_0': 0.6590021714768368, 'weight_class_1': 8.254512421993619, 'weight_class_2': 7.578738512553162}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:48,674] Trial 1789 finished with value: 0.9497232694263141 and parameters: {'weight_class_0': 0.652473216338875, 'weight_class_1': 8.242878475833928, 'weight_class_2': 7.44823704487937}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:48,685] Trial 1788 finished with value: 0.9496786910943329 and parameters: {'weight_class_0': 0.7082780001112915, 'weight_class_1': 8.257794133831322, 'weight_class_2': 7.565845201450941}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:48,732] Trial 1790 finished with value: 0.9497250762526405 and parameters: {'weight_class_0': 0.6904305228967693, 'weight_class_1': 8.285276062727942, 'weight_class_2': 7.5215873262135515}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:48,740] Trial 1791 finished with value: 0.9495451123971798 and parameters: {'weight_class_0': 0.7481935178768934, 'weight_class_1': 8.179477259132648, 'weight_class_2': 7.522585060881202}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  60%|███████████████████████████████████████████████████████████████████████████████▏                                                    | 1799/3000 [00:42<00:35, 33.93it/s]

[I 2026-07-10 16:12:48,803] Trial 1792 finished with value: 0.9496713843211287 and parameters: {'weight_class_0': 0.6985941179972208, 'weight_class_1': 8.036898027998618, 'weight_class_2': 7.403233329227149}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:48,820] Trial 1793 finished with value: 0.9497538948063874 and parameters: {'weight_class_0': 0.6124773234496014, 'weight_class_1': 8.139497022628676, 'weight_class_2': 7.39374165209102}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:48,847] Trial 1794 finished with value: 0.9496872330197624 and parameters: {'weight_class_0': 0.66873448383772, 'weight_class_1': 8.028626256891515, 'weight_class_2': 7.382113340220843}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:48,884] Trial 1795 finished with value: 0.949689925042941 and parameters: {'weight_class_0': 0.6740750304289033, 'weight_class_1': 8.073955381271483, 'weight_class_2': 7.382729239695614}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:48,890] Trial 1796 finished with value: 0.9497277471039727 and parameters: {'weight_class_0': 0.6517846814671197, 'weight_class_1': 8.140590907423697, 'weight_class_2': 7.413471283938732}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:48,931] Trial 1798 finished with value: 0.9480327339900461 and parameters: {'weight_class_0': 1.1992344887765336, 'weight_class_1': 8.004767906936632, 'weight_class_2': 7.3626888105354675}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:48,932] Trial 1797 finished with value: 0.9496939609201771 and parameters: {'weight_class_0': 0.6832365145710615, 'weight_class_1': 7.951536009419044, 'weight_class_2': 7.37252051303786}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:48,993] Trial 1799 finished with value: 0.9493560385453897 and parameters: {'weight_class_0': 0.836922705289285, 'weight_class_1': 7.96608325140062, 'weight_class_2': 7.9090518561788485}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  60%|███████████████████████████████████████████████████████████████████████████████▌                                                    | 1807/3000 [00:42<00:34, 34.19it/s]

[I 2026-07-10 16:12:48,994] Trial 1800 finished with value: 0.949503795002396 and parameters: {'weight_class_0': 0.7887786805784351, 'weight_class_1': 8.013711847879444, 'weight_class_2': 7.9695828704003295}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:49,058] Trial 1802 finished with value: 0.9483034722075839 and parameters: {'weight_class_0': 1.1629677609539624, 'weight_class_1': 8.031152350204504, 'weight_class_2': 7.95228975315008}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:49,067] Trial 1801 finished with value: 0.9493336806376224 and parameters: {'weight_class_0': 0.8459244953818494, 'weight_class_1': 8.015676578196206, 'weight_class_2': 7.9486598649072535}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:49,091] Trial 1803 finished with value: 0.9493305759094507 and parameters: {'weight_class_0': 0.41700151925373447, 'weight_class_1': 7.429354901705042, 'weight_class_2': 6.928168320758993}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:49,115] Trial 1804 finished with value: 0.9491353951604213 and parameters: {'weight_class_0': 0.37023386827070803, 'weight_class_1': 7.941291606957178, 'weight_class_2': 6.8891401532020655}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:49,181] Trial 1805 finished with value: 0.9491949017951217 and parameters: {'weight_class_0': 0.38433094737656337, 'weight_class_1': 7.542270918290811, 'weight_class_2': 6.97773658011679}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:49,217] Trial 1806 finished with value: 0.9490465413818884 and parameters: {'weight_class_0': 0.34535608620856345, 'weight_class_1': 7.279989586253171, 'weight_class_2': 6.688467664691355}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:49,218] Trial 1807 finished with value: 0.9491643376767754 and parameters: {'weight_class_0': 0.3747468548931196, 'weight_class_1': 7.892306269923418, 'weight_class_2': 6.904220689320885}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:49,262] Trial 1808 finished with value: 0.9493018893934302 and parameters: {'weight_class_0': 0.4100585857600179, 'weight_class_1': 7.882398825432985, 'weight_class_2': 7.131408479015145}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:49,311] Trial 1810 finished with value: 0.9492630731253247 and parameters: {'weight_class_0': 0.39691179598689397, 'weight_class_1': 7.885049834173035, 'weight_class_2': 6.916277131074088}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:49,327] Trial 1809 finished with value: 0.9493812444179971 and parameters: {'weight_class_0': 0.4237521900124718, 'weight_class_1': 7.336895710451618, 'weight_class_2': 6.972512945887561}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:49,339] Trial 1811 finished with value: 0.9491599675778993 and parameters: {'weight_class_0': 0.3711691501272404, 'weight_class_1': 7.384011881489742, 'weight_class_2': 6.928521109801885}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:49,346] Trial 1812 finished with value: 0.9491315103904814 and parameters: {'weight_class_0': 0.37254900153731896, 'weight_class_1': 7.874632873955058, 'weight_class_2': 6.9335409156042855}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:49,437] Trial 1814 finished with value: 0.9488615270849307 and parameters: {'weight_class_0': 0.3179690017608501, 'weight_class_1': 7.767996169278816, 'weight_class_2': 6.6341416723368045}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:49,449] Trial 1813 finished with value: 0.9459269743109502 and parameters: {'weight_class_0': 0.17212842401101125, 'weight_class_1': 7.304625302094622, 'weight_class_2': 9.994092358713033}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  61%|████████████████████████████████████████████████████████████████████████████████                                                    | 1821/3000 [00:42<00:35, 33.05it/s]

[I 2026-07-10 16:12:49,452] Trial 1815 finished with value: 0.9481559436916887 and parameters: {'weight_class_0': 0.24165959514672292, 'weight_class_1': 7.533260484457755, 'weight_class_2': 7.118508096551493}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:49,483] Trial 1816 finished with value: 0.9482795876886057 and parameters: {'weight_class_0': 0.20341795723271372, 'weight_class_1': 7.94188831891786, 'weight_class_2': 3.9169533108691352}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:49,532] Trial 1817 finished with value: 0.9467934211630156 and parameters: {'weight_class_0': 0.17949168570302582, 'weight_class_1': 7.8534042098835, 'weight_class_2': 7.135023178239414}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:49,563] Trial 1818 finished with value: 0.9459341460856047 and parameters: {'weight_class_0': 0.15755820016529037, 'weight_class_1': 8.118981894945348, 'weight_class_2': 7.109281114227473}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:49,594] Trial 1819 finished with value: 0.9452878623961533 and parameters: {'weight_class_0': 0.14162480972875557, 'weight_class_1': 7.82830928248443, 'weight_class_2': 7.1230910341101445}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:49,612] Trial 1820 finished with value: 0.9452548224324461 and parameters: {'weight_class_0': 0.14034271272774207, 'weight_class_1': 7.7886942086165565, 'weight_class_2': 7.089294372531529}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:49,653] Trial 1822 finished with value: 0.941227202096729 and parameters: {'weight_class_0': 0.10491227498511524, 'weight_class_1': 8.141174165093233, 'weight_class_2': 7.223012359893788}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:49,670] Trial 1821 finished with value: 0.9440579417283251 and parameters: {'weight_class_0': 0.12740056982273706, 'weight_class_1': 8.083087629243218, 'weight_class_2': 7.211804091755006}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:49,698] Trial 1824 finished with value: 0.9399778272014725 and parameters: {'weight_class_0': 0.09849308113572541, 'weight_class_1': 8.120129077942206, 'weight_class_2': 7.345543860548514}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:49,701] Trial 1823 finished with value: 0.940739834030219 and parameters: {'weight_class_0': 0.0989725160060908, 'weight_class_1': 7.822488587397221, 'weight_class_2': 7.172392737934248}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:49,743] Trial 1825 finished with value: 0.949643534541603 and parameters: {'weight_class_0': 0.5619197108275059, 'weight_class_1': 8.11388052796373, 'weight_class_2': 7.211182236178731}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:49,770] Trial 1826 finished with value: 0.949569652964464 and parameters: {'weight_class_0': 0.5723085892930843, 'weight_class_1': 6.665841187683652, 'weight_class_2': 7.288005541292975}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:49,810] Trial 1827 finished with value: 0.9496468690148818 and parameters: {'weight_class_0': 0.567868994405506, 'weight_class_1': 8.135051536605484, 'weight_class_2': 7.155319028289603}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:49,850] Trial 1828 finished with value: 0.9492912338393354 and parameters: {'weight_class_0': 0.8450479742689476, 'weight_class_1': 8.169921973521538, 'weight_class_2': 7.216028582104221}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:49,909] Trial 1830 finished with value: 0.9492608781861352 and parameters: {'weight_class_0': 0.8557698277029296, 'weight_class_1': 8.358394740566283, 'weight_class_2': 7.224429206089218}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  61%|████████████████████████████████████████████████████████████████████████████████▊                                                   | 1836/3000 [00:43<00:33, 35.01it/s]

[I 2026-07-10 16:12:49,922] Trial 1829 finished with value: 0.9496947274897387 and parameters: {'weight_class_0': 0.5739002017144891, 'weight_class_1': 8.398420240859837, 'weight_class_2': 7.226479981352775}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:49,957] Trial 1832 finished with value: 0.9497187279657514 and parameters: {'weight_class_0': 0.5897484612091989, 'weight_class_1': 8.416328402098904, 'weight_class_2': 7.253773484209814}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:49,972] Trial 1831 finished with value: 0.9496665210701343 and parameters: {'weight_class_0': 0.5673872618805008, 'weight_class_1': 8.39957536187847, 'weight_class_2': 7.233847489839814}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:49,996] Trial 1833 finished with value: 0.9481660240345784 and parameters: {'weight_class_0': 1.173374436383336, 'weight_class_1': 8.395542942411245, 'weight_class_2': 7.279815749146951}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:50,003] Trial 1834 finished with value: 0.949672733263884 and parameters: {'weight_class_0': 0.5825839139890671, 'weight_class_1': 8.330882314526345, 'weight_class_2': 7.2987503561159555}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:50,050] Trial 1835 finished with value: 0.9491366166218148 and parameters: {'weight_class_0': 0.8942260803069322, 'weight_class_1': 8.404283319514173, 'weight_class_2': 7.353172746009898}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:50,083] Trial 1836 finished with value: 0.9493822036518823 and parameters: {'weight_class_0': 0.8303948357287806, 'weight_class_1': 8.314180043523272, 'weight_class_2': 7.373923571806639}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  61%|█████████████████████████████████████████████████████████████████████████████████▏                                                  | 1844/3000 [00:43<00:34, 33.29it/s]

[I 2026-07-10 16:12:50,133] Trial 1837 finished with value: 0.9481652730882396 and parameters: {'weight_class_0': 1.187117484103788, 'weight_class_1': 8.410959400831102, 'weight_class_2': 7.3846978199469495}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:50,149] Trial 1838 finished with value: 0.9483769949318573 and parameters: {'weight_class_0': 1.1408690152010497, 'weight_class_1': 8.380540551691483, 'weight_class_2': 7.386034420771322}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:50,160] Trial 1839 finished with value: 0.9485259443412181 and parameters: {'weight_class_0': 1.1013802855860948, 'weight_class_1': 8.398518710636118, 'weight_class_2': 7.418540411335502}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:50,195] Trial 1840 finished with value: 0.9492882718836905 and parameters: {'weight_class_0': 0.8680662675441978, 'weight_class_1': 8.393199383823566, 'weight_class_2': 7.405008460435702}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:50,240] Trial 1842 finished with value: 0.9483835325115261 and parameters: {'weight_class_0': 1.1286538881837034, 'weight_class_1': 8.433324720287224, 'weight_class_2': 7.431388623565022}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:50,279] Trial 1841 finished with value: 0.9482905616480295 and parameters: {'weight_class_0': 1.1607608421328393, 'weight_class_1': 8.38616740972369, 'weight_class_2': 7.402748363515062}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:50,293] Trial 1843 finished with value: 0.9483709459759359 and parameters: {'weight_class_0': 1.157464137544243, 'weight_class_1': 8.424473465973103, 'weight_class_2': 7.499274361842548}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:50,295] Trial 1844 finished with value: 0.9493465742501637 and parameters: {'weight_class_0': 0.8519158229333608, 'weight_class_1': 8.476082258501346, 'weight_class_2': 7.49587336864451}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  62%|█████████████████████████████████████████████████████████████████████████████████▌                                                  | 1853/3000 [00:43<00:33, 34.62it/s]

[I 2026-07-10 16:12:50,327] Trial 1845 finished with value: 0.9483864085331929 and parameters: {'weight_class_0': 1.1320017158107443, 'weight_class_1': 8.438129647583667, 'weight_class_2': 7.438787580957032}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:50,363] Trial 1846 finished with value: 0.9483959676724555 and parameters: {'weight_class_0': 1.0757844520576643, 'weight_class_1': 8.510855233630632, 'weight_class_2': 6.735256795529694}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:50,391] Trial 1847 finished with value: 0.9487165799236871 and parameters: {'weight_class_0': 1.0731127555762954, 'weight_class_1': 8.489548696638291, 'weight_class_2': 7.538511818844279}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:50,392] Trial 1848 finished with value: 0.9481625639693733 and parameters: {'weight_class_0': 1.1305617242875952, 'weight_class_1': 7.560387964107242, 'weight_class_2': 7.534076354760585}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:50,471] Trial 1849 finished with value: 0.9488838578504047 and parameters: {'weight_class_0': 0.8540140445410864, 'weight_class_1': 6.9918288243528925, 'weight_class_2': 6.752339101660211}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:50,485] Trial 1851 finished with value: 0.9492398932843079 and parameters: {'weight_class_0': 0.8710060740966252, 'weight_class_1': 8.124230530154009, 'weight_class_2': 7.565526541548207}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:50,489] Trial 1850 finished with value: 0.9491989603320968 and parameters: {'weight_class_0': 0.8487415453713034, 'weight_class_1': 7.5727644200584825, 'weight_class_2': 7.573636038998591}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:50,555] Trial 1852 finished with value: 0.9489695847366604 and parameters: {'weight_class_0': 0.8468487565716354, 'weight_class_1': 7.558649213545308, 'weight_class_2': 6.642472121728645}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:50,566] Trial 1853 finished with value: 0.9496564103799053 and parameters: {'weight_class_0': 0.5299609363085545, 'weight_class_1': 8.13707907835812, 'weight_class_2': 6.692727557766221}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  62%|█████████████████████████████████████████████████████████████████████████████████▊                                                  | 1860/3000 [00:44<00:33, 34.14it/s]

[I 2026-07-10 16:12:50,584] Trial 1854 finished with value: 0.9496441840258236 and parameters: {'weight_class_0': 0.5283040755744124, 'weight_class_1': 8.09196855878411, 'weight_class_2': 6.70001303620068}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:50,585] Trial 1855 finished with value: 0.929893002781356 and parameters: {'weight_class_0': 0.5279486718028709, 'weight_class_1': 0.827102928361036, 'weight_class_2': 6.68414395559914}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:50,641] Trial 1856 finished with value: 0.9495060162918946 and parameters: {'weight_class_0': 0.5324827987458421, 'weight_class_1': 8.121688325822301, 'weight_class_2': 7.682041323695873}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:50,733] Trial 1858 finished with value: 0.9494480017966945 and parameters: {'weight_class_0': 0.5150534827351118, 'weight_class_1': 8.110131786478938, 'weight_class_2': 7.709902457961317}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:50,742] Trial 1859 finished with value: 0.9494982449504143 and parameters: {'weight_class_0': 0.5251706140681569, 'weight_class_1': 8.10274383289892, 'weight_class_2': 7.7207016471689505}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:50,748] Trial 1857 finished with value: 0.9494963342513031 and parameters: {'weight_class_0': 0.530810429520912, 'weight_class_1': 8.08485854552402, 'weight_class_2': 7.803391592780814}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:50,801] Trial 1860 finished with value: 0.9494732480622542 and parameters: {'weight_class_0': 0.5450580587711423, 'weight_class_1': 8.151132406067088, 'weight_class_2': 7.7972557220476}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  62%|██████████████████████████████████████████████████████████████████████████████████▏                                                 | 1867/3000 [00:44<00:32, 34.42it/s]

[I 2026-07-10 16:12:50,808] Trial 1861 finished with value: 0.9494105205469251 and parameters: {'weight_class_0': 0.5150735289945758, 'weight_class_1': 8.073219476763946, 'weight_class_2': 7.854294024370286}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:50,837] Trial 1862 finished with value: 0.9494661026224813 and parameters: {'weight_class_0': 0.5417290606771661, 'weight_class_1': 8.115963675983574, 'weight_class_2': 7.905972194511772}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:50,875] Trial 1863 finished with value: 0.9493050806110545 and parameters: {'weight_class_0': 0.49975485703900807, 'weight_class_1': 5.990170027306539, 'weight_class_2': 7.864398904511293}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:50,906] Trial 1864 finished with value: 0.9496317960994057 and parameters: {'weight_class_0': 0.6233122659088786, 'weight_class_1': 7.9335513286979, 'weight_class_2': 7.861715478506373}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:50,935] Trial 1865 finished with value: 0.9496750956271054 and parameters: {'weight_class_0': 0.679511009089136, 'weight_class_1': 7.863655630884122, 'weight_class_2': 7.040826720467578}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:50,974] Trial 1866 finished with value: 0.9496817107779888 and parameters: {'weight_class_0': 0.6927672945217029, 'weight_class_1': 7.891254346157929, 'weight_class_2': 7.853729967671624}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:50,993] Trial 1867 finished with value: 0.9496700181721754 and parameters: {'weight_class_0': 0.6720152865877178, 'weight_class_1': 7.8920235453437755, 'weight_class_2': 7.831328678323348}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  62%|██████████████████████████████████████████████████████████████████████████████████▍                                                 | 1874/3000 [00:44<00:33, 33.60it/s]

[I 2026-07-10 16:12:51,038] Trial 1868 finished with value: 0.9496406355542026 and parameters: {'weight_class_0': 0.6804427667308103, 'weight_class_1': 7.848007581404315, 'weight_class_2': 7.902746411484884}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:51,083] Trial 1869 finished with value: 0.9496303895932073 and parameters: {'weight_class_0': 0.7110708321976649, 'weight_class_1': 7.821689848928673, 'weight_class_2': 7.9170535797169626}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:51,105] Trial 1870 finished with value: 0.9494254465953659 and parameters: {'weight_class_0': 0.7023836923456084, 'weight_class_1': 7.85757621158847, 'weight_class_2': 6.1522002994071485}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:51,106] Trial 1871 finished with value: 0.949464516720503 and parameters: {'weight_class_0': 0.7487276035802812, 'weight_class_1': 7.879085070128175, 'weight_class_2': 6.968074046718092}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:51,130] Trial 1872 finished with value: 0.9495621752200144 and parameters: {'weight_class_0': 0.729463905973874, 'weight_class_1': 7.868803151434966, 'weight_class_2': 7.033933007103275}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:51,189] Trial 1874 finished with value: 0.9497084522438072 and parameters: {'weight_class_0': 0.6606002983436579, 'weight_class_1': 7.833478796725227, 'weight_class_2': 7.043039213701225}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:51,205] Trial 1873 finished with value: 0.9494780190362673 and parameters: {'weight_class_0': 0.7392976497030659, 'weight_class_1': 7.800074269477338, 'weight_class_2': 7.003476437677784}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  63%|██████████████████████████████████████████████████████████████████████████████████▊                                                 | 1882/3000 [00:44<00:32, 34.62it/s]

[I 2026-07-10 16:12:51,226] Trial 1875 finished with value: 0.9493511229094148 and parameters: {'weight_class_0': 0.786405999251025, 'weight_class_1': 7.783560265103231, 'weight_class_2': 7.09270048448064}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:51,232] Trial 1876 finished with value: 0.9494091199720778 and parameters: {'weight_class_0': 0.7819873348006727, 'weight_class_1': 8.55024059748352, 'weight_class_2': 7.064468424100228}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:51,291] Trial 1878 finished with value: 0.9493227077573 and parameters: {'weight_class_0': 0.8211525338645197, 'weight_class_1': 8.551246742299424, 'weight_class_2': 7.048015861176416}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:51,293] Trial 1877 finished with value: 0.9485862265023477 and parameters: {'weight_class_0': 0.3146993069703719, 'weight_class_1': 8.588568695032555, 'weight_class_2': 7.615901810043645}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:51,332] Trial 1879 finished with value: 0.9485859185822777 and parameters: {'weight_class_0': 0.31080196596273135, 'weight_class_1': 8.640360097939134, 'weight_class_2': 6.9894990927693375}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:51,359] Trial 1880 finished with value: 0.9489800874769413 and parameters: {'weight_class_0': 0.32540281574350954, 'weight_class_1': 8.557137536479342, 'weight_class_2': 6.166912421697048}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:51,389] Trial 1881 finished with value: 0.9487531835020323 and parameters: {'weight_class_0': 0.3422517316049213, 'weight_class_1': 8.61006591749392, 'weight_class_2': 7.6001701322927575}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:51,442] Trial 1882 finished with value: 0.9482462438066497 and parameters: {'weight_class_0': 0.27551891510083804, 'weight_class_1': 8.58746417413042, 'weight_class_2': 7.60388633126625}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  63%|███████████████████████████████████████████████████████████████████████████████████▏                                                | 1890/3000 [00:44<00:33, 33.27it/s]

[I 2026-07-10 16:12:51,448] Trial 1884 finished with value: 0.9487926587686308 and parameters: {'weight_class_0': 0.35208980688283076, 'weight_class_1': 8.591853476313325, 'weight_class_2': 7.591390439400739}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:51,457] Trial 1883 finished with value: 0.9485516994955518 and parameters: {'weight_class_0': 0.3116269193196613, 'weight_class_1': 8.607456668700577, 'weight_class_2': 7.594706783740368}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:51,536] Trial 1885 finished with value: 0.9485360345898132 and parameters: {'weight_class_0': 0.31037026107486804, 'weight_class_1': 8.637787287710646, 'weight_class_2': 7.611647798639843}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:51,536] Trial 1886 finished with value: 0.948661955476365 and parameters: {'weight_class_0': 0.32955517225238196, 'weight_class_1': 8.632552392678319, 'weight_class_2': 7.609844717397429}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:51,589] Trial 1887 finished with value: 0.9484086162284445 and parameters: {'weight_class_0': 0.2880571441268786, 'weight_class_1': 8.29278416864484, 'weight_class_2': 7.571345548481089}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:51,617] Trial 1888 finished with value: 0.9486622106620392 and parameters: {'weight_class_0': 0.32664574669206137, 'weight_class_1': 8.250890467575354, 'weight_class_2': 7.603922102452646}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:51,671] Trial 1889 finished with value: 0.6574209533680723 and parameters: {'weight_class_0': 0.0037470345433116004, 'weight_class_1': 8.306586158650008, 'weight_class_2': 8.138257309418377}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:51,677] Trial 1890 finished with value: 0.9475673958701499 and parameters: {'weight_class_0': 1.34071573521989, 'weight_class_1': 8.307128962607672, 'weight_class_2': 7.569485018880695}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  63%|███████████████████████████████████████████████████████████████████████████████████▌                                                | 1898/3000 [00:45<00:33, 33.37it/s]

[I 2026-07-10 16:12:51,703] Trial 1891 finished with value: 0.9489753390545527 and parameters: {'weight_class_0': 1.003673459999999, 'weight_class_1': 8.275395738604189, 'weight_class_2': 8.108731280109758}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:51,715] Trial 1892 finished with value: 0.8766607536631227 and parameters: {'weight_class_0': 8.280670384337364, 'weight_class_1': 8.291756246088049, 'weight_class_2': 8.111803810006347}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:51,757] Trial 1893 finished with value: 0.9488911685685116 and parameters: {'weight_class_0': 0.9661939078403775, 'weight_class_1': 8.24450868297492, 'weight_class_2': 7.28702722989428}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:51,801] Trial 1895 finished with value: 0.949152956527144 and parameters: {'weight_class_0': 0.9530965404978367, 'weight_class_1': 8.26047665408877, 'weight_class_2': 8.088946277416724}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:51,802] Trial 1894 finished with value: 0.9355172608127753 and parameters: {'weight_class_0': 0.9560725911429391, 'weight_class_1': 8.265174120499752, 'weight_class_2': 1.9712182299368388}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:51,865] Trial 1896 finished with value: 0.949121630557773 and parameters: {'weight_class_0': 0.886657413226435, 'weight_class_1': 8.209392845878083, 'weight_class_2': 7.298415766871803}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:51,935] Trial 1899 finished with value: 0.9491430089719467 and parameters: {'weight_class_0': 0.9597978514065396, 'weight_class_1': 8.26731491868729, 'weight_class_2': 8.13497010715465}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  63%|███████████████████████████████████████████████████████████████████████████████████▊                                                | 1904/3000 [00:45<00:34, 32.18it/s]

[I 2026-07-10 16:12:51,952] Trial 1898 finished with value: 0.9493279512593457 and parameters: {'weight_class_0': 0.8771921626608661, 'weight_class_1': 8.275403296074462, 'weight_class_2': 8.133368511541953}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:51,953] Trial 1897 finished with value: 0.6574681155353836 and parameters: {'weight_class_0': 0.004059930201126161, 'weight_class_1': 8.243507027957198, 'weight_class_2': 8.140189280040902}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:51,997] Trial 1900 finished with value: 0.9272869868000578 and parameters: {'weight_class_0': 3.490857967803765, 'weight_class_1': 8.806995858070804, 'weight_class_2': 7.2696469564878035}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:52,027] Trial 1902 finished with value: 0.9488799873542993 and parameters: {'weight_class_0': 0.9541896617377668, 'weight_class_1': 8.190007110031482, 'weight_class_2': 7.270804617113393}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:52,034] Trial 1901 finished with value: 0.9489724330996552 and parameters: {'weight_class_0': 0.9376770953904319, 'weight_class_1': 8.860218973603406, 'weight_class_2': 7.298018351298573}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:52,086] Trial 1903 finished with value: 0.9490660662564556 and parameters: {'weight_class_0': 0.9091940152395018, 'weight_class_1': 8.877788705937679, 'weight_class_2': 7.321714389488213}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:52,093] Trial 1904 finished with value: 0.9489651253061983 and parameters: {'weight_class_0': 0.9280791573452808, 'weight_class_1': 8.16877261612451, 'weight_class_2': 7.266130433207488}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:52,137] Trial 1906 finished with value: 0.9492160609084827 and parameters: {'weight_class_0': 0.8792163613559152, 'weight_class_1': 8.857459742584929, 'weight_class_2': 7.319152211391413}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:52,167] Trial 1905 finished with value: 0.9493904706512305 and parameters: {'weight_class_0': 0.8218125963969161, 'weight_class_1': 8.810917796095689, 'weight_class_2': 7.299483874715414}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:52,176] Trial 1907 finished with value: 0.9474657908249883 and parameters: {'weight_class_0': 1.3217813488463654, 'weight_class_1': 8.016894680833623, 'weight_class_2': 7.3326852777282845}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:52,201] Trial 1908 finished with value: 0.9476071188486562 and parameters: {'weight_class_0': 1.3485988464142649, 'weight_class_1': 8.788836841311209, 'weight_class_2': 7.354897526467684}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:52,252] Trial 1909 finished with value: 0.9494296631149739 and parameters: {'weight_class_0': 0.488373128166257, 'weight_class_1': 7.642420364997661, 'weight_class_2': 7.348490284286836}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:52,264] Trial 1910 finished with value: 0.9495140282083653 and parameters: {'weight_class_0': 0.5208270700138298, 'weight_class_1': 8.874815247743637, 'weight_class_2': 7.3083586979470025}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:52,293] Trial 1911 finished with value: 0.9476814238429124 and parameters: {'weight_class_0': 1.31600350124992, 'weight_class_1': 8.874857507852978, 'weight_class_2': 7.318796895320026}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:52,312] Trial 1912 finished with value: 0.9494895528351449 and parameters: {'weight_class_0': 0.5113224890346817, 'weight_class_1': 8.869743895484806, 'weight_class_2': 7.389353048892556}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  64%|████████████████████████████████████████████████████████████████████████████████████▍                                               | 1919/3000 [00:45<00:33, 32.53it/s]

[I 2026-07-10 16:12:52,377] Trial 1913 finished with value: 0.9468512507547765 and parameters: {'weight_class_0': 1.3904863708764674, 'weight_class_1': 7.640129425814154, 'weight_class_2': 7.41030550354717}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:52,390] Trial 1914 finished with value: 0.9494198050274707 and parameters: {'weight_class_0': 0.4892453254030147, 'weight_class_1': 8.841470642587394, 'weight_class_2': 7.422563957233624}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:52,432] Trial 1916 finished with value: 0.949449139801866 and parameters: {'weight_class_0': 0.48430175117282126, 'weight_class_1': 8.457940924061711, 'weight_class_2': 7.4729631948870905}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:52,444] Trial 1915 finished with value: 0.8662967970946059 and parameters: {'weight_class_0': 9.209235993154044, 'weight_class_1': 7.5236313562512445, 'weight_class_2': 7.45290974129489}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:52,524] Trial 1917 finished with value: 0.9495119836289018 and parameters: {'weight_class_0': 0.472671556342041, 'weight_class_1': 7.591052885661177, 'weight_class_2': 6.845070427849437}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:52,550] Trial 1918 finished with value: 0.9493326271813332 and parameters: {'weight_class_0': 0.44541946488149986, 'weight_class_1': 7.668466389125416, 'weight_class_2': 7.5002817213347175}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:52,568] Trial 1919 finished with value: 0.9495217498018708 and parameters: {'weight_class_0': 0.46942955720610224, 'weight_class_1': 8.060209565774032, 'weight_class_2': 6.819164870850994}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  64%|████████████████████████████████████████████████████████████████████████████████████▊                                               | 1927/3000 [00:46<00:32, 33.41it/s]

[I 2026-07-10 16:12:52,589] Trial 1920 finished with value: 0.9495234783040942 and parameters: {'weight_class_0': 0.48584367878820567, 'weight_class_1': 8.01685371217609, 'weight_class_2': 6.854461478357824}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:52,606] Trial 1921 finished with value: 0.9494143011356905 and parameters: {'weight_class_0': 0.4870301452779219, 'weight_class_1': 8.01365006491083, 'weight_class_2': 7.455646824751666}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:52,673] Trial 1924 finished with value: 0.9497221492571525 and parameters: {'weight_class_0': 0.646219089247401, 'weight_class_1': 7.9893613037712266, 'weight_class_2': 7.654952863129047}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:52,693] Trial 1923 finished with value: 0.9028362754384082 and parameters: {'weight_class_0': 5.360419106419145, 'weight_class_1': 8.006781105888752, 'weight_class_2': 7.752056854377784}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:52,695] Trial 1922 finished with value: 0.9496886683487077 and parameters: {'weight_class_0': 0.6496670127144286, 'weight_class_1': 8.010701448545955, 'weight_class_2': 6.8311749768769054}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:52,711] Trial 1925 finished with value: 0.9496341139061467 and parameters: {'weight_class_0': 0.606676719264367, 'weight_class_1': 7.993665590621162, 'weight_class_2': 7.69880789589123}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:52,761] Trial 1926 finished with value: 0.9496639661270363 and parameters: {'weight_class_0': 0.7030270048627264, 'weight_class_1': 7.978758092915799, 'weight_class_2': 7.746759050422843}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:52,773] Trial 1927 finished with value: 0.9497192628037574 and parameters: {'weight_class_0': 0.654866537449509, 'weight_class_1': 8.0247901026669, 'weight_class_2': 7.76144572103654}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  64%|█████████████████████████████████████████████████████████████████████████████████████▏                                              | 1935/3000 [00:46<00:31, 33.50it/s]

[I 2026-07-10 16:12:52,803] Trial 1928 finished with value: 0.9497138500784751 and parameters: {'weight_class_0': 0.639320934051444, 'weight_class_1': 8.020250354237858, 'weight_class_2': 7.750906692779457}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:52,844] Trial 1929 finished with value: 0.9496878169889632 and parameters: {'weight_class_0': 0.6807444468596404, 'weight_class_1': 8.002648558460269, 'weight_class_2': 7.759411533241542}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:52,917] Trial 1931 finished with value: 0.9497055204602977 and parameters: {'weight_class_0': 0.703380172120492, 'weight_class_1': 8.477174884858355, 'weight_class_2': 7.751612074437982}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:52,917] Trial 1930 finished with value: 0.9490459997969406 and parameters: {'weight_class_0': 0.7102396899257069, 'weight_class_1': 8.483250484346474, 'weight_class_2': 4.8938952315063675}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:52,921] Trial 1932 finished with value: 0.9497140519539989 and parameters: {'weight_class_0': 0.6848309979575645, 'weight_class_1': 8.446587231454107, 'weight_class_2': 7.741031742631607}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:52,959] Trial 1933 finished with value: 0.9497185461800502 and parameters: {'weight_class_0': 0.6947304117937727, 'weight_class_1': 8.485404625870705, 'weight_class_2': 7.777116068253839}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:53,003] Trial 1934 finished with value: 0.9496227981122853 and parameters: {'weight_class_0': 0.7244533770282697, 'weight_class_1': 8.496914991182619, 'weight_class_2': 7.155973080575143}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:53,034] Trial 1935 finished with value: 0.9496224708219692 and parameters: {'weight_class_0': 0.7165967743479426, 'weight_class_1': 8.48960485240659, 'weight_class_2': 7.104001909366602}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  65%|█████████████████████████████████████████████████████████████████████████████████████▍                                              | 1943/3000 [00:46<00:32, 32.79it/s]

[I 2026-07-10 16:12:53,059] Trial 1936 finished with value: 0.9494951928688039 and parameters: {'weight_class_0': 0.7530497325770515, 'weight_class_1': 8.563035642670446, 'weight_class_2': 7.042001574655901}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:53,108] Trial 1937 finished with value: 0.9494876343075335 and parameters: {'weight_class_0': 0.7691387598246067, 'weight_class_1': 8.530232168801044, 'weight_class_2': 7.167233940296182}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:53,134] Trial 1939 finished with value: 0.9475236125486814 and parameters: {'weight_class_0': 0.21254674032186754, 'weight_class_1': 2.5118313519686826, 'weight_class_2': 7.098046083082396}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:53,141] Trial 1938 finished with value: 0.8708566879774414 and parameters: {'weight_class_0': 8.67029784411667, 'weight_class_1': 8.49359925978278, 'weight_class_2': 7.099377811908802}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:53,143] Trial 1940 finished with value: 0.9493906773147759 and parameters: {'weight_class_0': 0.8097157860211749, 'weight_class_1': 8.5033707412551, 'weight_class_2': 7.129576301858427}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:53,221] Trial 1941 finished with value: 0.6597987847642949 and parameters: {'weight_class_0': 0.007371391949187567, 'weight_class_1': 8.50487224198462, 'weight_class_2': 7.094062318524493}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:53,283] Trial 1942 finished with value: 0.9478174595938572 and parameters: {'weight_class_0': 0.23579304822220615, 'weight_class_1': 8.560956440345716, 'weight_class_2': 7.10117565322895}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:53,285] Trial 1943 finished with value: 0.947020749472498 and parameters: {'weight_class_0': 0.2006149206980668, 'weight_class_1': 8.566930314642251, 'weight_class_2': 7.091624140222093}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:53,299] Trial 1944 finished with value: 0.65754745109176 and parameters: {'weight_class_0': 0.0007154357778101916, 'weight_class_1': 8.319577547866981, 'weight_class_2': 7.133296635828271}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:53,317] Trial 1945 finished with value: 0.9473111936104478 and parameters: {'weight_class_0': 0.21689198170663854, 'weight_class_1': 8.273697798416624, 'weight_class_2': 7.963379197114595}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:53,376] Trial 1947 finished with value: 0.8887335292471162 and parameters: {'weight_class_0': 6.446679452052276, 'weight_class_1': 8.301720911851248, 'weight_class_2': 7.14418145359602}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:53,398] Trial 1946 finished with value: 0.9475284579502294 and parameters: {'weight_class_0': 0.21516228885138539, 'weight_class_1': 8.2161232252791, 'weight_class_2': 7.111232748969153}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:53,415] Trial 1948 finished with value: 0.9481644979532438 and parameters: {'weight_class_0': 0.271105604383515, 'weight_class_1': 8.285334548487198, 'weight_class_2': 7.9849814360601234}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:53,435] Trial 1949 finished with value: 0.9486185422425822 and parameters: {'weight_class_0': 1.0969191747657638, 'weight_class_1': 8.212430474819277, 'weight_class_2': 8.01238351192345}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:53,516] Trial 1951 finished with value: 0.9487313674070164 and parameters: {'weight_class_0': 1.0464120373974914, 'weight_class_1': 8.257620337496563, 'weight_class_2': 7.990936971095918}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:53,518] Trial 1950 finished with value: 0.9488033326823627 and parameters: {'weight_class_0': 1.1043866510672655, 'weight_class_1': 9.057373539903118, 'weight_class_2': 7.9209826143089215}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:53,533] Trial 1952 finished with value: 0.9468069320706826 and parameters: {'weight_class_0': 1.1308545080814072, 'weight_class_1': 5.26491353364799, 'weight_class_2': 7.977497646607951}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:53,548] Trial 1953 finished with value: 0.9486601797907651 and parameters: {'weight_class_0': 1.0826276962915609, 'weight_class_1': 8.248714187115475, 'weight_class_2': 8.022927994417534}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:53,630] Trial 1954 finished with value: 0.9486146161902275 and parameters: {'weight_class_0': 1.0786592217939543, 'weight_class_1': 8.211550990660186, 'weight_class_2': 7.562996969647996}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:53,636] Trial 1955 finished with value: 0.948631750364816 and parameters: {'weight_class_0': 1.0904966463717867, 'weight_class_1': 8.21724496468034, 'weight_class_2': 7.98941453912787}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:53,657] Trial 1956 finished with value: 0.9487269817800001 and parameters: {'weight_class_0': 1.0430708540470497, 'weight_class_1': 8.228643079714372, 'weight_class_2': 7.936443538399148}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:53,684] Trial 1957 finished with value: 0.9412473681464997 and parameters: {'weight_class_0': 1.1173357449277161, 'weight_class_1': 2.999338759443647, 'weight_class_2': 7.53691928240441}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:53,727] Trial 1958 finished with value: 0.9488090918626139 and parameters: {'weight_class_0': 1.0689442088568053, 'weight_class_1': 9.064243155269805, 'weight_class_2': 7.508871337109554}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:53,736] Trial 1959 finished with value: 0.9484747916267849 and parameters: {'weight_class_0': 1.130114214357911, 'weight_class_1': 8.74122761434019, 'weight_class_2': 7.505892346386413}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:53,774] Trial 1960 finished with value: 0.9485842522486013 and parameters: {'weight_class_0': 1.1254318990232717, 'weight_class_1': 9.025225740478808, 'weight_class_2': 7.529339226912246}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:53,806] Trial 1961 finished with value: 0.9484285496575086 and parameters: {'weight_class_0': 1.146273093689182, 'weight_class_1': 8.771568064579228, 'weight_class_2': 7.564899301073495}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:53,860] Trial 1962 finished with value: 0.9493553732709827 and parameters: {'weight_class_0': 0.45000739428618364, 'weight_class_1': 8.747162776102055, 'weight_class_2': 7.532428495678969}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:53,870] Trial 1963 finished with value: 0.9463061709959794 and parameters: {'weight_class_0': 1.5788589083392686, 'weight_class_1': 8.678601049948808, 'weight_class_2': 7.534759628774656}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:53,901] Trial 1964 finished with value: 0.9492379883987893 and parameters: {'weight_class_0': 0.4251564085101792, 'weight_class_1': 8.758780804848422, 'weight_class_2': 7.5219337889223254}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:53,955] Trial 1965 finished with value: 0.9490567086486196 and parameters: {'weight_class_0': 0.3911784492745825, 'weight_class_1': 8.73163601182212, 'weight_class_2': 7.510285538044355}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:53,979] Trial 1966 finished with value: 0.9494182048646898 and parameters: {'weight_class_0': 0.4692950705146134, 'weight_class_1': 8.76127364406281, 'weight_class_2': 7.511203857718637}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:53,995] Trial 1967 finished with value: 0.9134533172970082 and parameters: {'weight_class_0': 4.647634560489157, 'weight_class_1': 8.71906151793413, 'weight_class_2': 7.554837478072153}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:54,016] Trial 1968 finished with value: 0.9492557827977167 and parameters: {'weight_class_0': 0.43150236123851665, 'weight_class_1': 8.723967097189867, 'weight_class_2': 7.531045642853342}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:54,061] Trial 1969 finished with value: 0.9492450155891463 and parameters: {'weight_class_0': 0.4252881717277634, 'weight_class_1': 7.764725740897786, 'weight_class_2': 7.541975234162319}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:54,083] Trial 1971 finished with value: 0.9492728027705887 and parameters: {'weight_class_0': 0.43379517151004604, 'weight_class_1': 7.80295160407321, 'weight_class_2': 7.468524810514132}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:54,087] Trial 1970 finished with value: 0.9492073833348775 and parameters: {'weight_class_0': 0.416445221444229, 'weight_class_1': 7.7598282979099915, 'weight_class_2': 7.550402185923293}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  66%|███████████████████████████████████████████████████████████████████████████████████████                                             | 1978/3000 [00:47<00:30, 33.37it/s]

[I 2026-07-10 16:12:54,130] Trial 1972 finished with value: 0.9493009067078222 and parameters: {'weight_class_0': 0.43795482750500436, 'weight_class_1': 7.741690642415662, 'weight_class_2': 7.484362992727131}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:54,150] Trial 1973 finished with value: 0.949148769918091 and parameters: {'weight_class_0': 0.39489874577344675, 'weight_class_1': 7.715140260876197, 'weight_class_2': 7.424863655178719}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:54,232] Trial 1975 finished with value: 0.9493545833167873 and parameters: {'weight_class_0': 0.4171617643317199, 'weight_class_1': 7.820969973724945, 'weight_class_2': 6.874061106249001}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:54,247] Trial 1976 finished with value: 0.9494123898762523 and parameters: {'weight_class_0': 0.813391012612775, 'weight_class_1': 7.754838123769865, 'weight_class_2': 8.29033861646206}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:54,252] Trial 1974 finished with value: 0.9488998544903837 and parameters: {'weight_class_0': 0.39031119963312777, 'weight_class_1': 7.694349379612545, 'weight_class_2': 8.31442791022559}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:54,300] Trial 1977 finished with value: 0.949079451343057 and parameters: {'weight_class_0': 0.8395608553362947, 'weight_class_1': 7.7647236718558865, 'weight_class_2': 6.843693996890139}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:54,317] Trial 1978 finished with value: 0.9492895400583641 and parameters: {'weight_class_0': 0.8717222209601236, 'weight_class_1': 7.721629492723896, 'weight_class_2': 8.367810869949771}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  66%|███████████████████████████████████████████████████████████████████████████████████████▍                                            | 1986/3000 [00:47<00:30, 33.27it/s]

[I 2026-07-10 16:12:54,321] Trial 1979 finished with value: 0.9489758480687988 and parameters: {'weight_class_0': 0.8792789662833311, 'weight_class_1': 7.724015585937657, 'weight_class_2': 6.90760944045315}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:54,387] Trial 1980 finished with value: 0.9493857005073044 and parameters: {'weight_class_0': 0.8639099745716334, 'weight_class_1': 8.084680217851929, 'weight_class_2': 8.32658816437798}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:54,417] Trial 1981 finished with value: 0.9491542202270384 and parameters: {'weight_class_0': 0.8045329795425713, 'weight_class_1': 8.077127611218694, 'weight_class_2': 6.491391875588053}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:54,442] Trial 1982 finished with value: 0.8764962733457294 and parameters: {'weight_class_0': 7.525575648175151, 'weight_class_1': 8.106265523052054, 'weight_class_2': 6.900469275489164}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:54,483] Trial 1983 finished with value: 0.9491222982891904 and parameters: {'weight_class_0': 0.8461016767388747, 'weight_class_1': 8.090605221230678, 'weight_class_2': 6.866082111372349}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:54,494] Trial 1984 finished with value: 0.949029011587359 and parameters: {'weight_class_0': 0.8345247114486088, 'weight_class_1': 8.09464166223888, 'weight_class_2': 6.528863549859599}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:54,497] Trial 1985 finished with value: 0.94944337697207 and parameters: {'weight_class_0': 0.8405090546798777, 'weight_class_1': 8.113383715213148, 'weight_class_2': 8.333895775846566}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:54,556] Trial 1986 finished with value: 0.9492714207180161 and parameters: {'weight_class_0': 0.8641969895624829, 'weight_class_1': 8.11402926956385, 'weight_class_2': 7.779010273693446}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  66%|███████████████████████████████████████████████████████████████████████████████████████▋                                            | 1993/3000 [00:48<00:29, 34.36it/s]

[I 2026-07-10 16:12:54,579] Trial 1987 finished with value: 0.9492943411557734 and parameters: {'weight_class_0': 0.8573214859730643, 'weight_class_1': 8.095372349003267, 'weight_class_2': 7.762215024817156}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:54,603] Trial 1988 finished with value: 0.9497271182776151 and parameters: {'weight_class_0': 0.6519851754959718, 'weight_class_1': 8.36295443822047, 'weight_class_2': 7.773367553751923}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:54,627] Trial 1989 finished with value: 0.9497157034197364 and parameters: {'weight_class_0': 0.6328473389845644, 'weight_class_1': 8.100660020730334, 'weight_class_2': 7.78938796384994}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:54,668] Trial 1990 finished with value: 0.9496167310327097 and parameters: {'weight_class_0': 0.6114428226898225, 'weight_class_1': 8.377778142002077, 'weight_class_2': 7.821301646253575}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:54,693] Trial 1991 finished with value: 0.9496117949034392 and parameters: {'weight_class_0': 0.5990986369395626, 'weight_class_1': 8.382166195881924, 'weight_class_2': 7.7758166982146015}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:54,753] Trial 1992 finished with value: 0.9496276135327341 and parameters: {'weight_class_0': 0.6061224158434336, 'weight_class_1': 8.463832425328928, 'weight_class_2': 7.789178394255378}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:54,777] Trial 1993 finished with value: 0.9496724667290254 and parameters: {'weight_class_0': 0.6206920591596773, 'weight_class_1': 8.369042032503446, 'weight_class_2': 7.75136626618265}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  67%|████████████████████████████████████████████████████████████████████████████████████████                                            | 2000/3000 [00:48<00:30, 32.65it/s]

[I 2026-07-10 16:12:54,836] Trial 1995 finished with value: 0.9495715277782483 and parameters: {'weight_class_0': 0.5672785821520772, 'weight_class_1': 8.398151289378259, 'weight_class_2': 7.753095554041045}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:54,868] Trial 1997 finished with value: 0.9495724767087997 and parameters: {'weight_class_0': 0.6046720986381332, 'weight_class_1': 8.38389962886315, 'weight_class_2': 5.544706225404435}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:54,869] Trial 1996 finished with value: 0.9496790808311967 and parameters: {'weight_class_0': 0.5782082839493077, 'weight_class_1': 8.3930809258836, 'weight_class_2': 7.253024629593291}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:54,871] Trial 1994 finished with value: 0.9496141189296413 and parameters: {'weight_class_0': 0.6095654611477181, 'weight_class_1': 8.40748757546482, 'weight_class_2': 7.778978648727635}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:54,928] Trial 1999 finished with value: 0.9497186645940338 and parameters: {'weight_class_0': 0.5882177541897659, 'weight_class_1': 8.424087167272571, 'weight_class_2': 7.243262678653143}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:54,934] Trial 1998 finished with value: 0.9497443676124014 and parameters: {'weight_class_0': 0.6164502854499273, 'weight_class_1': 8.407151304629801, 'weight_class_2': 7.247169400873584}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:54,961] Trial 2000 finished with value: 0.9495640040661589 and parameters: {'weight_class_0': 0.6073513368983453, 'weight_class_1': 8.419835451583706, 'weight_class_2': 5.542299845294871}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:55,018] Trial 2002 finished with value: 0.9497281930138657 and parameters: {'weight_class_0': 0.6045728037456025, 'weight_class_1': 8.379480301105696, 'weight_class_2': 7.254062247146219}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:55,019] Trial 2001 finished with value: 0.9497434854019704 and parameters: {'weight_class_0': 0.6001432355653398, 'weight_class_1': 8.399279030059057, 'weight_class_2': 7.294273976287767}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:55,077] Trial 2003 finished with value: 0.9462083666299321 and parameters: {'weight_class_0': 0.179833138131909, 'weight_class_1': 8.9922797271871, 'weight_class_2': 7.262703971897339}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:55,084] Trial 2004 finished with value: 0.9459444721723035 and parameters: {'weight_class_0': 0.1628056619107608, 'weight_class_1': 8.401884217257134, 'weight_class_2': 7.259132641202125}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:55,113] Trial 2005 finished with value: 0.9473416841642531 and parameters: {'weight_class_0': 0.22130051744900237, 'weight_class_1': 8.991770284661376, 'weight_class_2': 7.245307986728459}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:55,165] Trial 2006 finished with value: 0.7388222501176234 and parameters: {'weight_class_0': 0.19141077188564598, 'weight_class_1': 8.991521542091476, 'weight_class_2': 0.008139849390543574}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:55,199] Trial 2007 finished with value: 0.9470783280783469 and parameters: {'weight_class_0': 0.21190783949576614, 'weight_class_1': 9.010064837817922, 'weight_class_2': 7.347945084464164}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:55,235] Trial 2008 finished with value: 0.9463388708685275 and parameters: {'weight_class_0': 0.16605145687271888, 'weight_class_1': 7.991906429871682, 'weight_class_2': 6.971367552555544}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:55,242] Trial 2009 finished with value: 0.9453909469773253 and parameters: {'weight_class_0': 0.14452645669462233, 'weight_class_1': 7.953608927036642, 'weight_class_2': 6.933834701875929}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:55,296] Trial 2011 finished with value: 0.9477276222455719 and parameters: {'weight_class_0': 0.2162224917731594, 'weight_class_1': 7.914570497645589, 'weight_class_2': 6.863087425146506}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:55,346] Trial 2010 finished with value: 0.9483949887652523 and parameters: {'weight_class_0': 0.25560026590057694, 'weight_class_1': 7.466445101928283, 'weight_class_2': 6.724522241913338}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:55,350] Trial 2012 finished with value: 0.9469232615122999 and parameters: {'weight_class_0': 0.1847811125811658, 'weight_class_1': 7.913971241096177, 'weight_class_2': 6.956406142073467}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:55,374] Trial 2013 finished with value: 0.9485412208083462 and parameters: {'weight_class_0': 0.2896807214388443, 'weight_class_1': 8.170661857187286, 'weight_class_2': 6.726834717516162}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:55,386] Trial 2014 finished with value: 0.9489058811229497 and parameters: {'weight_class_0': 0.33534566432387236, 'weight_class_1': 7.922492894974939, 'weight_class_2': 6.722283711058608}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  67%|████████████████████████████████████████████████████████████████████████████████████████▉                                           | 2022/3000 [00:48<00:30, 31.94it/s]

[I 2026-07-10 16:12:55,407] Trial 2015 finished with value: 0.9486253927258267 and parameters: {'weight_class_0': 0.28788274063345426, 'weight_class_1': 7.422392850151036, 'weight_class_2': 6.785352840737094}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:55,458] Trial 2016 finished with value: 0.9486656458160883 and parameters: {'weight_class_0': 0.3044429927665306, 'weight_class_1': 7.9501621124127, 'weight_class_2': 6.9719546896294196}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:55,515] Trial 2017 finished with value: 0.9491470347234486 and parameters: {'weight_class_0': 0.36203713747906313, 'weight_class_1': 7.917832186893803, 'weight_class_2': 6.624253017655928}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:55,559] Trial 2019 finished with value: 0.9490644391806428 and parameters: {'weight_class_0': 0.3540289342847869, 'weight_class_1': 8.200148407591266, 'weight_class_2': 6.550949484457659}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:55,563] Trial 2018 finished with value: 0.9491913061223008 and parameters: {'weight_class_0': 0.36489673730607186, 'weight_class_1': 7.470846782377605, 'weight_class_2': 6.678020745538278}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:55,598] Trial 2020 finished with value: 0.9491123105673797 and parameters: {'weight_class_0': 0.3566970043570903, 'weight_class_1': 7.4987898391292465, 'weight_class_2': 6.678620097333195}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:55,608] Trial 2021 finished with value: 0.9492017155267178 and parameters: {'weight_class_0': 0.3845827945279175, 'weight_class_1': 7.494435799127728, 'weight_class_2': 6.981117343879991}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:55,659] Trial 2022 finished with value: 0.9490370021958746 and parameters: {'weight_class_0': 0.8930372106544942, 'weight_class_1': 8.213710720390251, 'weight_class_2': 7.162827894377779}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  68%|█████████████████████████████████████████████████████████████████████████████████████████▎                                          | 2030/3000 [00:49<00:28, 33.76it/s]

[I 2026-07-10 16:12:55,693] Trial 2023 finished with value: 0.948899535331174 and parameters: {'weight_class_0': 0.9274280613472101, 'weight_class_1': 8.208517884914547, 'weight_class_2': 7.031790669685287}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:55,725] Trial 2024 finished with value: 0.9489897029561964 and parameters: {'weight_class_0': 0.9075772822838966, 'weight_class_1': 8.18821316052772, 'weight_class_2': 7.174951838325086}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:55,729] Trial 2025 finished with value: 0.9492552181934437 and parameters: {'weight_class_0': 0.8455705234799327, 'weight_class_1': 8.228354266933941, 'weight_class_2': 7.116235219066009}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:55,795] Trial 2027 finished with value: 0.9489632988422613 and parameters: {'weight_class_0': 0.9127332779839987, 'weight_class_1': 8.160671836490868, 'weight_class_2': 7.1424649926751815}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:55,813] Trial 2026 finished with value: 0.6575538003578766 and parameters: {'weight_class_0': 0.00016476723274450045, 'weight_class_1': 8.267785139291036, 'weight_class_2': 7.142529235054781}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:55,861] Trial 2028 finished with value: 0.9491140625850271 and parameters: {'weight_class_0': 0.8755627005995552, 'weight_class_1': 8.213659036559799, 'weight_class_2': 7.111736670865577}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:55,875] Trial 2029 finished with value: 0.9489949056203256 and parameters: {'weight_class_0': 0.9079265190173644, 'weight_class_1': 8.603189492665228, 'weight_class_2': 7.083035897289953}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:55,912] Trial 2031 finished with value: 0.9490249659569456 and parameters: {'weight_class_0': 0.8967940526134265, 'weight_class_1': 8.198654281541053, 'weight_class_2': 7.197108563714289}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  68%|█████████████████████████████████████████████████████████████████████████████████████████▋                                          | 2037/3000 [00:49<00:29, 32.47it/s]

[I 2026-07-10 16:12:55,934] Trial 2030 finished with value: 0.9489978735898382 and parameters: {'weight_class_0': 0.9044428361259871, 'weight_class_1': 8.608587855487626, 'weight_class_2': 7.137842096087529}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:55,969] Trial 2033 finished with value: 0.9473597135402813 and parameters: {'weight_class_0': 1.3266037257851824, 'weight_class_1': 8.226674319925657, 'weight_class_2': 7.10245562840738}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:55,977] Trial 2032 finished with value: 0.8863095277391745 and parameters: {'weight_class_0': 6.7843393151297, 'weight_class_1': 8.570591365947674, 'weight_class_2': 7.177064851771347}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:56,048] Trial 2034 finished with value: 0.9474969595419394 and parameters: {'weight_class_0': 1.3355336336347359, 'weight_class_1': 8.650674297497927, 'weight_class_2': 7.173332166611493}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:56,091] Trial 2035 finished with value: 0.8857595414759474 and parameters: {'weight_class_0': 6.8623860751260946, 'weight_class_1': 8.628723153805016, 'weight_class_2': 7.192887738131094}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:56,100] Trial 2036 finished with value: 0.9496188317234312 and parameters: {'weight_class_0': 0.7217246343188196, 'weight_class_1': 8.593030045885266, 'weight_class_2': 7.1733647560679605}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:56,110] Trial 2037 finished with value: 0.9474409270358327 and parameters: {'weight_class_0': 1.3408895474984623, 'weight_class_1': 8.558263395926195, 'weight_class_2': 7.204605489432734}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:56,168] Trial 2038 finished with value: 0.9477199579452228 and parameters: {'weight_class_0': 1.2910195810603986, 'weight_class_1': 8.642555466785408, 'weight_class_2': 7.209533819612905}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:56,174] Trial 2040 finished with value: 0.9496837408085397 and parameters: {'weight_class_0': 0.5832048756460083, 'weight_class_1': 8.58012510122116, 'weight_class_2': 7.325953085159252}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:56,216] Trial 2039 finished with value: 0.947642095368546 and parameters: {'weight_class_0': 1.3184778516845013, 'weight_class_1': 8.544669036670248, 'weight_class_2': 7.320883862959677}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:56,278] Trial 2041 finished with value: 0.9497201169443296 and parameters: {'weight_class_0': 0.600031408700471, 'weight_class_1': 8.574569096535852, 'weight_class_2': 7.355213707523876}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:56,283] Trial 2042 finished with value: 0.9496608098362573 and parameters: {'weight_class_0': 0.5779485108314228, 'weight_class_1': 8.523007511702875, 'weight_class_2': 7.355910794855404}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:56,320] Trial 2043 finished with value: 0.9496102512143637 and parameters: {'weight_class_0': 0.5324066211618076, 'weight_class_1': 8.592552584769587, 'weight_class_2': 7.340972676665083}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:56,329] Trial 2044 finished with value: 0.9497035770345622 and parameters: {'weight_class_0': 0.6156304361865509, 'weight_class_1': 7.182166334149366, 'weight_class_2': 7.3662223683022905}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  68%|██████████████████████████████████████████████████████████████████████████████████████████▏                                         | 2051/3000 [00:49<00:29, 32.14it/s]

[I 2026-07-10 16:12:56,361] Trial 2046 finished with value: 0.949680968762454 and parameters: {'weight_class_0': 0.5608300687345065, 'weight_class_1': 8.500908768679057, 'weight_class_2': 7.309931521757929}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:56,363] Trial 2045 finished with value: 0.9496696608048066 and parameters: {'weight_class_0': 0.5585041071819715, 'weight_class_1': 8.623887750324565, 'weight_class_2': 7.359848110888849}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:56,461] Trial 2048 finished with value: 0.9496140389067343 and parameters: {'weight_class_0': 0.563052916592551, 'weight_class_1': 8.033213662403096, 'weight_class_2': 7.368258627515138}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:56,467] Trial 2049 finished with value: 0.9494586143642524 and parameters: {'weight_class_0': 0.49479071681291537, 'weight_class_1': 7.908722387385665, 'weight_class_2': 7.361958075959357}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:56,474] Trial 2047 finished with value: 0.9495319214531507 and parameters: {'weight_class_0': 0.528219232148361, 'weight_class_1': 7.9283805813481445, 'weight_class_2': 7.32967445901889}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:56,516] Trial 2050 finished with value: 0.9494843926792766 and parameters: {'weight_class_0': 0.5007443562243955, 'weight_class_1': 7.977654221289317, 'weight_class_2': 7.354423268365511}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:56,559] Trial 2052 finished with value: 0.9495276156434483 and parameters: {'weight_class_0': 0.5256693655615967, 'weight_class_1': 7.9501878198431415, 'weight_class_2': 7.369959017597749}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  69%|██████████████████████████████████████████████████████████████████████████████████████████▌                                         | 2058/3000 [00:50<00:28, 32.66it/s]

[I 2026-07-10 16:12:56,600] Trial 2053 finished with value: 0.94947949746226 and parameters: {'weight_class_0': 0.5080534838890698, 'weight_class_1': 7.944055279048754, 'weight_class_2': 7.406993430680429}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:56,602] Trial 2051 finished with value: 0.9495709183221369 and parameters: {'weight_class_0': 0.5303404489654081, 'weight_class_1': 8.029659442582547, 'weight_class_2': 7.359837143172783}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:56,616] Trial 2054 finished with value: 0.9494573399985771 and parameters: {'weight_class_0': 0.49733332402824426, 'weight_class_1': 7.945702153818463, 'weight_class_2': 7.388439927236354}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:56,694] Trial 2055 finished with value: 0.9494238306655399 and parameters: {'weight_class_0': 0.7657349838434999, 'weight_class_1': 7.948471533900844, 'weight_class_2': 6.999179511597082}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:56,698] Trial 2056 finished with value: 0.9496218256528124 and parameters: {'weight_class_0': 0.7298115127328737, 'weight_class_1': 8.36573694404695, 'weight_class_2': 7.373229747288073}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:56,706] Trial 2057 finished with value: 0.9494434194518716 and parameters: {'weight_class_0': 0.753725726845477, 'weight_class_1': 7.964179024269759, 'weight_class_2': 6.841698812607039}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:56,722] Trial 2058 finished with value: 0.9494471113876021 and parameters: {'weight_class_0': 0.7534386039762008, 'weight_class_1': 7.966598508761379, 'weight_class_2': 6.937972617451455}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:56,831] Trial 2060 finished with value: 0.94945147105475 and parameters: {'weight_class_0': 0.7525815076084439, 'weight_class_1': 8.328002709085874, 'weight_class_2': 6.897698734374946}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:56,837] Trial 2061 finished with value: 0.9496298459605056 and parameters: {'weight_class_0': 0.7290407305286307, 'weight_class_1': 8.286106523975057, 'weight_class_2': 7.435199754194396}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:56,845] Trial 2059 finished with value: 0.9494445141341226 and parameters: {'weight_class_0': 0.7608226606123563, 'weight_class_1': 8.341700929900243, 'weight_class_2': 6.917603033212407}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:56,877] Trial 2062 finished with value: 0.9470993991924965 and parameters: {'weight_class_0': 0.7453440765583587, 'weight_class_1': 3.4156723933654165, 'weight_class_2': 6.936031808121687}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:56,931] Trial 2064 finished with value: 0.9493716312152302 and parameters: {'weight_class_0': 0.7933229302555217, 'weight_class_1': 8.351428373095217, 'weight_class_2': 6.947863660751162}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:56,959] Trial 2063 finished with value: 0.9495019719076074 and parameters: {'weight_class_0': 0.7379339797133464, 'weight_class_1': 8.313374104255667, 'weight_class_2': 6.854518391280097}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:56,990] Trial 2065 finished with value: 0.9373710468300797 and parameters: {'weight_class_0': 0.7628523880761944, 'weight_class_1': 1.5839995160511577, 'weight_class_2': 6.984897354300134}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:56,994] Trial 2066 finished with value: 0.949395453501029 and parameters: {'weight_class_0': 0.7753286772052738, 'weight_class_1': 8.302455724469269, 'weight_class_2': 6.940392804252445}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  69%|███████████████████████████████████████████████████████████████████████████████████████████▏                                        | 2073/3000 [00:50<00:27, 33.41it/s]

[I 2026-07-10 16:12:57,046] Trial 2067 finished with value: 0.9486395910634222 and parameters: {'weight_class_0': 1.0260823319783592, 'weight_class_1': 8.398426807831392, 'weight_class_2': 6.928166576689597}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:57,067] Trial 2068 finished with value: 0.9488217721476504 and parameters: {'weight_class_0': 0.9786672305120547, 'weight_class_1': 8.305242019462396, 'weight_class_2': 6.930396604790194}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:57,080] Trial 2069 finished with value: 0.6590135667018683 and parameters: {'weight_class_0': 0.006656797239526502, 'weight_class_1': 8.363538581721997, 'weight_class_2': 6.956375923819756}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:57,098] Trial 2070 finished with value: 0.948678883824743 and parameters: {'weight_class_0': 1.0284753690599413, 'weight_class_1': 8.338445329247746, 'weight_class_2': 7.018043521782602}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:57,179] Trial 2072 finished with value: 0.8936609276105766 and parameters: {'weight_class_0': 0.9997567563020933, 'weight_class_1': 8.339954582043324, 'weight_class_2': 0.2584064533365602}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:57,209] Trial 2071 finished with value: 0.9488878947478936 and parameters: {'weight_class_0': 0.9841171933251298, 'weight_class_1': 8.289511467476226, 'weight_class_2': 7.5978914918224945}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:57,226] Trial 2073 finished with value: 0.9486950351081299 and parameters: {'weight_class_0': 1.0434338545766435, 'weight_class_1': 8.205521791044655, 'weight_class_2': 7.578525970509678}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:57,269] Trial 2074 finished with value: 0.9275663382112289 and parameters: {'weight_class_0': 1.0449473517859125, 'weight_class_1': 1.537609948177125, 'weight_class_2': 7.60214197103612}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:57,303] Trial 2075 finished with value: 0.9488921939679739 and parameters: {'weight_class_0': 1.029928824958316, 'weight_class_1': 8.820741614919795, 'weight_class_2': 7.589438622075564}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:57,339] Trial 2076 finished with value: 0.9489868556134544 and parameters: {'weight_class_0': 0.9691702690706365, 'weight_class_1': 8.774700758430292, 'weight_class_2': 7.634361737021802}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:57,359] Trial 2077 finished with value: 0.9488419223409225 and parameters: {'weight_class_0': 1.049151696536924, 'weight_class_1': 8.787372880108197, 'weight_class_2': 7.579505627088516}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:57,380] Trial 2079 finished with value: 0.8841529860408722 and parameters: {'weight_class_0': 7.274846131696009, 'weight_class_1': 8.82138543273676, 'weight_class_2': 7.5222126034921315}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:57,389] Trial 2078 finished with value: 0.9488269285642089 and parameters: {'weight_class_0': 1.0651605492269849, 'weight_class_1': 8.907972616124717, 'weight_class_2': 7.636844494420126}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:57,477] Trial 2080 finished with value: 0.9489072882459281 and parameters: {'weight_class_0': 0.3736675339677862, 'weight_class_1': 8.822676082581893, 'weight_class_2': 7.615818393133158}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  70%|███████████████████████████████████████████████████████████████████████████████████████████▊                                        | 2087/3000 [00:50<00:28, 32.00it/s]

[I 2026-07-10 16:12:57,488] Trial 2081 finished with value: 0.9488364259127993 and parameters: {'weight_class_0': 0.3616944820687022, 'weight_class_1': 8.813318669763328, 'weight_class_2': 7.615370961897958}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:57,489] Trial 2082 finished with value: 0.9488928117718868 and parameters: {'weight_class_0': 0.3727364109836596, 'weight_class_1': 8.832575956380222, 'weight_class_2': 7.626330652913124}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:57,516] Trial 2083 finished with value: 0.9487450357723528 and parameters: {'weight_class_0': 0.31095855602872635, 'weight_class_1': 8.830854163143895, 'weight_class_2': 6.341459017906896}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:57,556] Trial 2084 finished with value: 0.9490005537141418 and parameters: {'weight_class_0': 0.39031775899623344, 'weight_class_1': 8.766684777035216, 'weight_class_2': 7.6599167074023935}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:57,593] Trial 2085 finished with value: 0.9490798357499223 and parameters: {'weight_class_0': 0.39939412869051916, 'weight_class_1': 8.847540027968424, 'weight_class_2': 7.617403933584349}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:57,635] Trial 2086 finished with value: 0.9010180461998365 and parameters: {'weight_class_0': 5.856806717313787, 'weight_class_1': 9.333958769056592, 'weight_class_2': 7.633300344415925}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:57,651] Trial 2087 finished with value: 0.9488157616088694 and parameters: {'weight_class_0': 0.3576489322195483, 'weight_class_1': 8.758505587789093, 'weight_class_2': 7.582374938504495}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:57,709] Trial 2089 finished with value: 0.9489275097291827 and parameters: {'weight_class_0': 0.3501663375602754, 'weight_class_1': 7.628867931902498, 'weight_class_2': 7.181092594750181}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:57,719] Trial 2088 finished with value: 0.9474387021012372 and parameters: {'weight_class_0': 0.3590835393871568, 'weight_class_1': 9.303434721570866, 'weight_class_2': 1.7166607753364223}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:57,748] Trial 2090 finished with value: 0.9490505225175347 and parameters: {'weight_class_0': 0.37125682673545846, 'weight_class_1': 8.120228892067278, 'weight_class_2': 7.191574339085263}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:57,750] Trial 2091 finished with value: 0.9490333480064471 and parameters: {'weight_class_0': 0.3702063382249616, 'weight_class_1': 8.125608734670259, 'weight_class_2': 7.164362617210339}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:57,857] Trial 2092 finished with value: 0.9493607711466762 and parameters: {'weight_class_0': 0.43442153630807767, 'weight_class_1': 8.096972689007972, 'weight_class_2': 7.158575989298116}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:57,864] Trial 2093 finished with value: 0.9492106017353548 and parameters: {'weight_class_0': 0.4180981267520196, 'weight_class_1': 9.36445428282199, 'weight_class_2': 7.120316995524974}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:57,874] Trial 2095 finished with value: 0.9459672921961283 and parameters: {'weight_class_0': 1.5586341005611541, 'weight_class_1': 8.117648495855297, 'weight_class_2': 7.221252649421389}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:57,894] Trial 2094 finished with value: 0.9497111870141519 and parameters: {'weight_class_0': 0.6875100096229835, 'weight_class_1': 9.303510454555324, 'weight_class_2': 7.158737483446423}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  70%|████████████████████████████████████████████████████████████████████████████████████████████▍                                       | 2102/3000 [00:51<00:26, 33.71it/s]

[I 2026-07-10 16:12:57,924] Trial 2096 finished with value: 0.9496928444903251 and parameters: {'weight_class_0': 0.6539956472247039, 'weight_class_1': 8.130882556882565, 'weight_class_2': 7.188085650432327}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:57,943] Trial 2097 finished with value: 0.9496802943463316 and parameters: {'weight_class_0': 0.660177569761985, 'weight_class_1': 7.686194948265037, 'weight_class_2': 7.186463743229444}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:57,965] Trial 2098 finished with value: 0.9496704961996265 and parameters: {'weight_class_0': 0.6728835280305817, 'weight_class_1': 7.616975609343314, 'weight_class_2': 7.173217486795026}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:58,017] Trial 2099 finished with value: 0.949626870751279 and parameters: {'weight_class_0': 0.6848625006438811, 'weight_class_1': 7.662614726618549, 'weight_class_2': 7.176538994144461}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:58,072] Trial 2100 finished with value: 0.8660244595337988 and parameters: {'weight_class_0': 9.576989794697308, 'weight_class_1': 8.14272659668127, 'weight_class_2': 7.402984798992356}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:58,104] Trial 2101 finished with value: 0.9497464764477269 and parameters: {'weight_class_0': 0.6529855296375984, 'weight_class_1': 8.148949893053816, 'weight_class_2': 7.346926280273028}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:58,148] Trial 2102 finished with value: 0.9484897957024455 and parameters: {'weight_class_0': 0.6697702831780322, 'weight_class_1': 4.073069575202572, 'weight_class_2': 7.402693560273615}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  70%|████████████████████████████████████████████████████████████████████████████████████████████▊                                       | 2109/3000 [00:51<00:27, 31.96it/s]

[I 2026-07-10 16:12:58,184] Trial 2103 finished with value: 0.6679384102618141 and parameters: {'weight_class_0': 0.010176006847403718, 'weight_class_1': 8.118539328695041, 'weight_class_2': 7.411749066807173}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:58,213] Trial 2104 finished with value: 0.9496669338909557 and parameters: {'weight_class_0': 0.6450594495173414, 'weight_class_1': 7.749677919804112, 'weight_class_2': 7.43641452890577}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:58,229] Trial 2105 finished with value: 0.939178314756517 and parameters: {'weight_class_0': 2.3317798461291876, 'weight_class_1': 7.67816113542785, 'weight_class_2': 7.407174824715452}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:58,264] Trial 2106 finished with value: 0.7254319655976257 and parameters: {'weight_class_0': 0.017189211609468735, 'weight_class_1': 7.676169101370143, 'weight_class_2': 7.397355755342653}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:58,303] Trial 2107 finished with value: 0.9428302294535432 and parameters: {'weight_class_0': 0.12278316045440851, 'weight_class_1': 8.506704266381652, 'weight_class_2': 7.9294836160638384}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:58,311] Trial 2108 finished with value: 0.9441662400839057 and parameters: {'weight_class_0': 0.13401490260100635, 'weight_class_1': 8.433051708673409, 'weight_class_2': 7.405816239667682}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:58,369] Trial 2110 finished with value: 0.9436141715542874 and parameters: {'weight_class_0': 0.12814216590132999, 'weight_class_1': 8.497818714446545, 'weight_class_2': 7.418224081676835}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:12:58,375] Trial 2109 finished with value: 0.944995129706142 and parameters: {'weight_class_0': 0.14869053736252702, 'weight_class_1': 8.418998428043059, 'weight_class_2': 7.921827528629141}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:58,407] Trial 2112 finished with value: 0.9440031323467086 and parameters: {'weight_class_0': 0.13538798622635623, 'weight_class_1': 8.494879320031947, 'weight_class_2': 7.915734952917359}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:58,409] Trial 2111 finished with value: 0.9402950925197576 and parameters: {'weight_class_0': 0.1041505994863241, 'weight_class_1': 8.501281048933839, 'weight_class_2': 7.418790116542442}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:58,480] Trial 2113 finished with value: 0.948169939182247 and parameters: {'weight_class_0': 1.2018370602733959, 'weight_class_1': 8.50088227249803, 'weight_class_2': 7.432075513463495}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:58,524] Trial 2114 finished with value: 0.6953044348968019 and parameters: {'weight_class_0': 0.014717854788220741, 'weight_class_1': 8.46421371166945, 'weight_class_2': 7.455203065987826}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:58,535] Trial 2115 finished with value: 0.948160648276647 and parameters: {'weight_class_0': 1.2260805114333095, 'weight_class_1': 8.448763750943531, 'weight_class_2': 7.977836589961997}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:58,542] Trial 2116 finished with value: 0.948139689881983 and parameters: {'weight_class_0': 1.2439079496629948, 'weight_class_1': 8.487629557871365, 'weight_class_2': 7.920209588070231}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  71%|█████████████████████████████████████████████████████████████████████████████████████████████▍                                      | 2123/3000 [00:52<00:28, 31.07it/s]

[I 2026-07-10 16:12:58,615] Trial 2118 finished with value: 0.9480965834351117 and parameters: {'weight_class_0': 1.2507597557991734, 'weight_class_1': 8.439285715606667, 'weight_class_2': 7.940652566917736}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:58,637] Trial 2117 finished with value: 0.9481219468270378 and parameters: {'weight_class_0': 1.2520284934520398, 'weight_class_1': 8.504587744996067, 'weight_class_2': 7.910780787513268}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:58,667] Trial 2119 finished with value: 0.9481955007721586 and parameters: {'weight_class_0': 1.2086769568627784, 'weight_class_1': 8.480121965124804, 'weight_class_2': 7.943759202194929}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:58,694] Trial 2120 finished with value: 0.9494944189157063 and parameters: {'weight_class_0': 0.8419226096725624, 'weight_class_1': 8.513280698778, 'weight_class_2': 8.170784180166242}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:58,764] Trial 2121 finished with value: 0.9493599128836013 and parameters: {'weight_class_0': 0.8562927884854803, 'weight_class_1': 8.195931768085938, 'weight_class_2': 8.085932002488875}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:58,783] Trial 2122 finished with value: 0.949256938230107 and parameters: {'weight_class_0': 0.8791951508347682, 'weight_class_1': 8.20846882271761, 'weight_class_2': 7.86611558339424}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:58,797] Trial 2123 finished with value: 0.9495101547002408 and parameters: {'weight_class_0': 0.8028037178451345, 'weight_class_1': 8.215772920749338, 'weight_class_2': 8.129119012491037}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  71%|█████████████████████████████████████████████████████████████████████████████████████████████▊                                      | 2131/3000 [00:52<00:26, 32.75it/s]

[I 2026-07-10 16:12:58,849] Trial 2124 finished with value: 0.9493607106532648 and parameters: {'weight_class_0': 0.8610304867138463, 'weight_class_1': 8.249933875931346, 'weight_class_2': 8.169681581919704}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:58,882] Trial 2125 finished with value: 0.9493388927132269 and parameters: {'weight_class_0': 0.8675304774227275, 'weight_class_1': 8.209645376990837, 'weight_class_2': 8.156086779780134}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:58,896] Trial 2126 finished with value: 0.944449236783132 and parameters: {'weight_class_0': 1.9030240249342252, 'weight_class_1': 8.250981097470216, 'weight_class_2': 8.117938037798545}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:58,934] Trial 2127 finished with value: 0.9494138252051978 and parameters: {'weight_class_0': 0.8383812012810203, 'weight_class_1': 8.184533416974151, 'weight_class_2': 8.149920343946341}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:58,936] Trial 2128 finished with value: 0.9433321429613124 and parameters: {'weight_class_0': 0.8447561270489197, 'weight_class_1': 8.200229586648458, 'weight_class_2': 2.506277209920901}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:58,982] Trial 2129 finished with value: 0.9493411335245076 and parameters: {'weight_class_0': 0.8500499344345567, 'weight_class_1': 8.164702960712196, 'weight_class_2': 7.739810251066382}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:59,047] Trial 2130 finished with value: 0.9494147602528215 and parameters: {'weight_class_0': 0.8471897255196794, 'weight_class_1': 8.188992675401291, 'weight_class_2': 8.14360597591767}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:59,049] Trial 2131 finished with value: 0.9492983058458236 and parameters: {'weight_class_0': 0.8586355206480245, 'weight_class_1': 8.21802457544174, 'weight_class_2': 7.713059990357191}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  71%|██████████████████████████████████████████████████████████████████████████████████████████████                                      | 2138/3000 [00:52<00:28, 30.10it/s]

[I 2026-07-10 16:12:59,087] Trial 2132 finished with value: 0.9495259308212747 and parameters: {'weight_class_0': 0.7690238771794651, 'weight_class_1': 8.198923802389695, 'weight_class_2': 7.710494436005788}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:59,132] Trial 2133 finished with value: 0.9493472518660142 and parameters: {'weight_class_0': 0.8407225949465089, 'weight_class_1': 8.224396946460844, 'weight_class_2': 7.7126806339652}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:59,138] Trial 2134 finished with value: 0.94948060437784 and parameters: {'weight_class_0': 0.534733035578133, 'weight_class_1': 8.26412017960112, 'weight_class_2': 7.694759746002926}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:59,198] Trial 2135 finished with value: 0.9494236688311574 and parameters: {'weight_class_0': 0.49797969028629363, 'weight_class_1': 9.072987418361679, 'weight_class_2': 7.725307261113227}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:59,226] Trial 2136 finished with value: 0.9494252990632771 and parameters: {'weight_class_0': 0.489609347739928, 'weight_class_1': 9.090298636952827, 'weight_class_2': 7.7003587073438675}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:59,285] Trial 2138 finished with value: 0.9496184539245381 and parameters: {'weight_class_0': 0.5668860515125196, 'weight_class_1': 9.037251236395845, 'weight_class_2': 7.775068131268904}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  72%|██████████████████████████████████████████████████████████████████████████████████████████████▍                                     | 2146/3000 [00:52<00:26, 32.17it/s]

[I 2026-07-10 16:12:59,312] Trial 2140 finished with value: 0.949543396079546 and parameters: {'weight_class_0': 0.5501908847684266, 'weight_class_1': 9.052630025563289, 'weight_class_2': 7.664773374063856}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:59,320] Trial 2137 finished with value: 0.9494980254777857 and parameters: {'weight_class_0': 0.5265861904935364, 'weight_class_1': 9.12779102182427, 'weight_class_2': 7.637673956556514}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:59,332] Trial 2139 finished with value: 0.9495338529129218 and parameters: {'weight_class_0': 0.5435546122507778, 'weight_class_1': 8.648442856000328, 'weight_class_2': 7.732873939713928}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:59,379] Trial 2141 finished with value: 0.949600463499387 and parameters: {'weight_class_0': 0.5679132303394252, 'weight_class_1': 9.099232724370184, 'weight_class_2': 7.6461858753261485}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:59,405] Trial 2142 finished with value: 0.9494845116072436 and parameters: {'weight_class_0': 0.5218157436384651, 'weight_class_1': 8.616113480209345, 'weight_class_2': 7.704989395212628}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:59,421] Trial 2143 finished with value: 0.9494762646900042 and parameters: {'weight_class_0': 0.516575980079624, 'weight_class_1': 9.151946626916732, 'weight_class_2': 7.65496775008689}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:59,442] Trial 2144 finished with value: 0.9495056536302348 and parameters: {'weight_class_0': 0.5307571959582063, 'weight_class_1': 9.000453978224355, 'weight_class_2': 7.456443522471548}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:59,507] Trial 2146 finished with value: 0.9495846370546239 and parameters: {'weight_class_0': 0.5443044682392372, 'weight_class_1': 9.096109162817347, 'weight_class_2': 7.4923507996364265}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  72%|██████████████████████████████████████████████████████████████████████████████████████████████▋                                     | 2152/3000 [00:52<00:26, 31.96it/s]

[I 2026-07-10 16:12:59,540] Trial 2145 finished with value: 0.9143241106196721 and parameters: {'weight_class_0': 0.5698680571350535, 'weight_class_1': 0.5280869060519979, 'weight_class_2': 7.477404196893259}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:59,560] Trial 2147 finished with value: 0.9497101754030002 and parameters: {'weight_class_0': 0.6034632570111602, 'weight_class_1': 8.643397562223095, 'weight_class_2': 7.467034664785628}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:59,574] Trial 2148 finished with value: 0.9496316561357006 and parameters: {'weight_class_0': 0.5620987753518246, 'weight_class_1': 8.671331988452485, 'weight_class_2': 7.513174385584789}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:59,635] Trial 2149 finished with value: 0.9497474456741601 and parameters: {'weight_class_0': 0.6161369705837803, 'weight_class_1': 8.70899681738697, 'weight_class_2': 7.497973975844495}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:59,652] Trial 2150 finished with value: 0.9497318893674568 and parameters: {'weight_class_0': 0.6162198679017212, 'weight_class_1': 8.647334272031806, 'weight_class_2': 7.421725572557416}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:59,712] Trial 2151 finished with value: 0.9497036243023853 and parameters: {'weight_class_0': 0.6497158073861682, 'weight_class_1': 8.643540936147922, 'weight_class_2': 7.456401591582241}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:59,716] Trial 2152 finished with value: 0.9497487971791179 and parameters: {'weight_class_0': 0.6861166403867553, 'weight_class_1': 8.667627469692562, 'weight_class_2': 7.448426205158204}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  72%|███████████████████████████████████████████████████████████████████████████████████████████████                                     | 2160/3000 [00:53<00:26, 31.68it/s]

[I 2026-07-10 16:12:59,769] Trial 2153 finished with value: 0.9483618298735782 and parameters: {'weight_class_0': 0.2792330466940399, 'weight_class_1': 8.005410883815436, 'weight_class_2': 7.420109947462171}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:59,813] Trial 2154 finished with value: 0.9487638128669976 and parameters: {'weight_class_0': 0.9975197221986366, 'weight_class_1': 7.994463661587213, 'weight_class_2': 7.462053553248003}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:59,821] Trial 2156 finished with value: 0.9486536312036137 and parameters: {'weight_class_0': 1.0321847290086668, 'weight_class_1': 7.973831272183622, 'weight_class_2': 7.294226078640218}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:59,834] Trial 2155 finished with value: 0.9486867962119523 and parameters: {'weight_class_0': 1.0381135083019533, 'weight_class_1': 8.03595832381731, 'weight_class_2': 7.293326551698038}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:59,882] Trial 2158 finished with value: 0.9485431568399095 and parameters: {'weight_class_0': 1.0580376366751376, 'weight_class_1': 8.02332074012687, 'weight_class_2': 7.276533952121695}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:59,897] Trial 2157 finished with value: 0.9487325367483982 and parameters: {'weight_class_0': 1.0575500465778584, 'weight_class_1': 8.669246869970637, 'weight_class_2': 7.286641946968739}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:59,942] Trial 2159 finished with value: 0.948459092706805 and parameters: {'weight_class_0': 1.0795224059279924, 'weight_class_1': 7.987942944137905, 'weight_class_2': 7.244091769286683}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:12:59,953] Trial 2160 finished with value: 0.9484069060762145 and parameters: {'weight_class_0': 0.2785334740698995, 'weight_class_1': 7.96881686198689, 'weight_class_2': 7.2895940476303664}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  72%|███████████████████████████████████████████████████████████████████████████████████████████████▎                                    | 2167/3000 [00:53<00:26, 31.55it/s]

[I 2026-07-10 16:13:00,006] Trial 2162 finished with value: 0.948276979114401 and parameters: {'weight_class_0': 0.2799156193634665, 'weight_class_1': 8.887181008309257, 'weight_class_2': 7.250394255031178}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:00,031] Trial 2161 finished with value: 0.9481477057129671 and parameters: {'weight_class_0': 0.27117802473181984, 'weight_class_1': 8.890945762436507, 'weight_class_2': 7.288925631938926}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:00,080] Trial 2164 finished with value: 0.9487658041363108 and parameters: {'weight_class_0': 1.0555011691937526, 'weight_class_1': 8.990118694897712, 'weight_class_2': 7.284357154541196}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:00,092] Trial 2163 finished with value: 0.9487019259095236 and parameters: {'weight_class_0': 1.0364144603542857, 'weight_class_1': 8.953066470134145, 'weight_class_2': 7.046322555549231}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:00,122] Trial 2165 finished with value: 0.948694228474286 and parameters: {'weight_class_0': 1.0378273854274456, 'weight_class_1': 8.892761546520966, 'weight_class_2': 7.04601677641122}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:00,167] Trial 2167 finished with value: 0.9484041456877033 and parameters: {'weight_class_0': 0.29033737800568166, 'weight_class_1': 8.921289261606278, 'weight_class_2': 7.1118964184697875}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:00,180] Trial 2166 finished with value: 0.948459261598976 and parameters: {'weight_class_0': 0.29915231150664917, 'weight_class_1': 8.870598245563954, 'weight_class_2': 7.022213375529643}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  72%|███████████████████████████████████████████████████████████████████████████████████████████████▋                                    | 2175/3000 [00:53<00:26, 31.10it/s]

[I 2026-07-10 16:13:00,256] Trial 2168 finished with value: 0.9488226602590429 and parameters: {'weight_class_0': 0.26741158855938313, 'weight_class_1': 8.971125958425867, 'weight_class_2': 4.560481340986289}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:00,261] Trial 2169 finished with value: 0.9484395218081447 and parameters: {'weight_class_0': 0.29999865994932834, 'weight_class_1': 8.928811206921328, 'weight_class_2': 7.108580042562243}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:00,272] Trial 2170 finished with value: 0.9479513809448985 and parameters: {'weight_class_0': 0.2524331134632344, 'weight_class_1': 8.943149910311112, 'weight_class_2': 7.046808230522335}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:00,353] Trial 2172 finished with value: 0.9311884820321131 and parameters: {'weight_class_0': 3.124207587363342, 'weight_class_1': 8.949489980405023, 'weight_class_2': 7.020167714709321}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:00,365] Trial 2171 finished with value: 0.9495605425077431 and parameters: {'weight_class_0': 0.7323589465675676, 'weight_class_1': 8.955279584603757, 'weight_class_2': 7.015206532041625}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:00,372] Trial 2173 finished with value: 0.949601631355272 and parameters: {'weight_class_0': 0.7318453970232577, 'weight_class_1': 8.934645944639408, 'weight_class_2': 7.092963127807229}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:00,391] Trial 2174 finished with value: 0.9494875400851294 and parameters: {'weight_class_0': 0.7544396695900702, 'weight_class_1': 8.951866285946258, 'weight_class_2': 6.7240545233023665}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:00,426] Trial 2175 finished with value: 0.9495176422514593 and parameters: {'weight_class_0': 0.7429484513020802, 'weight_class_1': 8.846834728402417, 'weight_class_2': 6.725110721001506}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  73%|████████████████████████████████████████████████████████████████████████████████████████████████                                    | 2182/3000 [00:53<00:25, 32.55it/s]

[I 2026-07-10 16:13:00,489] Trial 2176 finished with value: 0.9494775638510072 and parameters: {'weight_class_0': 0.7662588069785217, 'weight_class_1': 9.162259099390313, 'weight_class_2': 6.840719603494302}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:00,504] Trial 2177 finished with value: 0.949491310344963 and parameters: {'weight_class_0': 0.7691572487238202, 'weight_class_1': 9.198199930760367, 'weight_class_2': 6.750013438020037}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:00,528] Trial 2178 finished with value: 0.9496177919188785 and parameters: {'weight_class_0': 0.6964207606903857, 'weight_class_1': 9.287111205622477, 'weight_class_2': 6.8070373639307045}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:00,548] Trial 2179 finished with value: 0.949507943662475 and parameters: {'weight_class_0': 0.7402364829223161, 'weight_class_1': 8.847751793005902, 'weight_class_2': 6.83665875450893}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:00,581] Trial 2180 finished with value: 0.9460291217388338 and parameters: {'weight_class_0': 1.5426325245475854, 'weight_class_1': 8.73211309153922, 'weight_class_2': 6.769705140628613}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:00,628] Trial 2182 finished with value: 0.9496274816721416 and parameters: {'weight_class_0': 0.7223640675279259, 'weight_class_1': 9.428208182282077, 'weight_class_2': 7.05723241485077}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:00,681] Trial 2181 finished with value: 0.9494819605883027 and parameters: {'weight_class_0': 0.767881803699436, 'weight_class_1': 8.605330490403615, 'weight_class_2': 6.973477149437093}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  73%|████████████████████████████████████████████████████████████████████████████████████████████████▎                                   | 2189/3000 [00:54<00:25, 31.63it/s]

[I 2026-07-10 16:13:00,692] Trial 2183 finished with value: 0.9496004403073147 and parameters: {'weight_class_0': 0.7541562461619533, 'weight_class_1': 8.652510383430638, 'weight_class_2': 7.281579848802306}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:00,727] Trial 2184 finished with value: 0.9494535404425729 and parameters: {'weight_class_0': 0.7679527582018384, 'weight_class_1': 9.56563624555544, 'weight_class_2': 6.491572997626742}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:00,769] Trial 2185 finished with value: 0.946942291491997 and parameters: {'weight_class_0': 1.4959458930273646, 'weight_class_1': 9.444432524967063, 'weight_class_2': 7.272942457057523}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:00,784] Trial 2186 finished with value: 0.9494579206314756 and parameters: {'weight_class_0': 0.7549865096122741, 'weight_class_1': 8.766056233783928, 'weight_class_2': 6.547509422776265}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:00,809] Trial 2187 finished with value: 0.9493786051287487 and parameters: {'weight_class_0': 0.7856533171983366, 'weight_class_1': 9.372324440803084, 'weight_class_2': 6.569134027634734}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:00,841] Trial 2188 finished with value: 0.9492172669088256 and parameters: {'weight_class_0': 0.8924227826323808, 'weight_class_1': 9.449305615113124, 'weight_class_2': 7.267640603973942}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:00,904] Trial 2190 finished with value: 0.9491545255979377 and parameters: {'weight_class_0': 0.4016577520408957, 'weight_class_1': 8.685187618923019, 'weight_class_2': 7.27352929540787}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  73%|████████████████████████████████████████████████████████████████████████████████████████████████▌                                   | 2196/3000 [00:54<00:25, 32.01it/s]

[I 2026-07-10 16:13:00,914] Trial 2189 finished with value: 0.9493483539988904 and parameters: {'weight_class_0': 0.454309145559667, 'weight_class_1': 9.496273495220574, 'weight_class_2': 7.27943052099876}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:00,930] Trial 2192 finished with value: 0.9490769762766479 and parameters: {'weight_class_0': 0.3882967598648161, 'weight_class_1': 8.711126825348584, 'weight_class_2': 7.291515059958577}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:00,933] Trial 2191 finished with value: 0.9495042593496515 and parameters: {'weight_class_0': 0.449128141087872, 'weight_class_1': 8.627934157207369, 'weight_class_2': 6.53023549108367}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:00,999] Trial 2193 finished with value: 0.9492415234189492 and parameters: {'weight_class_0': 0.420810956408785, 'weight_class_1': 8.608981276414815, 'weight_class_2': 7.279901316951647}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:01,060] Trial 2194 finished with value: 0.9492600416812976 and parameters: {'weight_class_0': 0.4258210890639766, 'weight_class_1': 8.694295314413868, 'weight_class_2': 7.472716341897412}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:01,064] Trial 2196 finished with value: 0.9491919407569328 and parameters: {'weight_class_0': 0.41383574913518173, 'weight_class_1': 8.722641954343358, 'weight_class_2': 7.508304082713057}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:01,076] Trial 2195 finished with value: 0.9494187325990904 and parameters: {'weight_class_0': 0.4568167251060445, 'weight_class_1': 8.679859871955355, 'weight_class_2': 7.463604110327701}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:13:01,159] Trial 2197 finished with value: 0.9493750349433041 and parameters: {'weight_class_0': 0.45067473346069636, 'weight_class_1': 8.424558990903494, 'weight_class_2': 7.391244419864604}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:01,180] Trial 2198 finished with value: 0.9491280188988352 and parameters: {'weight_class_0': 0.4002926982793455, 'weight_class_1': 8.62801391068911, 'weight_class_2': 7.4592181375212805}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:01,211] Trial 2199 finished with value: 0.9493350709501615 and parameters: {'weight_class_0': 0.4450809368716656, 'weight_class_1': 8.698283963874976, 'weight_class_2': 7.512980121469383}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:01,220] Trial 2200 finished with value: 0.9493685528170879 and parameters: {'weight_class_0': 0.44914448902390924, 'weight_class_1': 8.600551784108038, 'weight_class_2': 7.451817820394633}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:01,296] Trial 2201 finished with value: 0.9493199885204132 and parameters: {'weight_class_0': 0.44592512072431023, 'weight_class_1': 8.395860478266409, 'weight_class_2': 7.538103282678153}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:01,311] Trial 2203 finished with value: 0.9489510560425837 and parameters: {'weight_class_0': 0.96629570329233, 'weight_class_1': 8.432793765799572, 'weight_class_2': 7.514503622128685}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:01,313] Trial 2202 finished with value: 0.9480598240825949 and parameters: {'weight_class_0': 1.2390168987049175, 'weight_class_1': 8.423764987274728, 'weight_class_2': 7.518248645838448}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:13:01,339] Trial 2205 finished with value: 0.9479044394731396 and parameters: {'weight_class_0': 1.2930448955054374, 'weight_class_1': 8.445104978386878, 'weight_class_2': 7.507186639598011}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:01,347] Trial 2204 finished with value: 0.9481830872275742 and parameters: {'weight_class_0': 1.1939266267376707, 'weight_class_1': 8.417720870315355, 'weight_class_2': 7.552828238666091}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:01,410] Trial 2206 finished with value: 0.9496220273434884 and parameters: {'weight_class_0': 0.5918655840792625, 'weight_class_1': 8.409798086345923, 'weight_class_2': 7.555595611176975}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:01,413] Trial 2207 finished with value: 0.9480678956314739 and parameters: {'weight_class_0': 1.2370197439602566, 'weight_class_1': 8.390706165070004, 'weight_class_2': 7.548369957180634}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:01,471] Trial 2208 finished with value: 0.9489577099339591 and parameters: {'weight_class_0': 0.9594706718070176, 'weight_class_1': 8.385604209004946, 'weight_class_2': 7.566715176053051}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:01,526] Trial 2209 finished with value: 0.9490548571446662 and parameters: {'weight_class_0': 0.9306674597490596, 'weight_class_1': 8.355181377862808, 'weight_class_2': 7.566674494546673}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:01,546] Trial 2211 finished with value: 0.9478744144050667 and parameters: {'weight_class_0': 1.2973960001612266, 'weight_class_1': 8.40091647961112, 'weight_class_2': 7.570964217091781}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:01,551] Trial 2210 finished with value: 0.9481335846912614 and parameters: {'weight_class_0': 1.2079199114013783, 'weight_class_1': 8.404085849503154, 'weight_class_2': 7.5765666952581405}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  74%|█████████████████████████████████████████████████████████████████████████████████████████████████▌                                  | 2218/3000 [00:55<00:24, 32.17it/s]

[I 2026-07-10 16:13:01,557] Trial 2212 finished with value: 0.9477002589638487 and parameters: {'weight_class_0': 1.2655214263904013, 'weight_class_1': 8.399925638398987, 'weight_class_2': 7.081229339776008}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:01,604] Trial 2213 finished with value: 0.948917139512152 and parameters: {'weight_class_0': 0.9326822258871893, 'weight_class_1': 8.44440897860909, 'weight_class_2': 7.14092239548815}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:01,688] Trial 2214 finished with value: 0.9488948163999739 and parameters: {'weight_class_0': 0.9449319925353692, 'weight_class_1': 8.380441940435144, 'weight_class_2': 7.083891825637722}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:01,691] Trial 2215 finished with value: 0.9488888292197629 and parameters: {'weight_class_0': 0.9601391425746972, 'weight_class_1': 8.36202128219685, 'weight_class_2': 7.077573121921644}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:01,724] Trial 2216 finished with value: 0.9491022621330668 and parameters: {'weight_class_0': 0.9184048196330572, 'weight_class_1': 9.220628240609315, 'weight_class_2': 7.0974779508479}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:01,761] Trial 2217 finished with value: 0.9488843123286544 and parameters: {'weight_class_0': 0.9378488223705329, 'weight_class_1': 8.349776732711662, 'weight_class_2': 7.088108093944158}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:01,790] Trial 2218 finished with value: 0.9489402373587753 and parameters: {'weight_class_0': 0.9563274618843369, 'weight_class_1': 9.142702418247708, 'weight_class_2': 7.097092868813398}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  74%|█████████████████████████████████████████████████████████████████████████████████████████████████▉                                  | 2225/3000 [00:55<00:24, 31.29it/s]

[I 2026-07-10 16:13:01,817] Trial 2219 finished with value: 0.948893163502797 and parameters: {'weight_class_0': 0.941572671344152, 'weight_class_1': 8.386687204196987, 'weight_class_2': 7.091847406391467}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:01,882] Trial 2222 finished with value: 0.9497119608929122 and parameters: {'weight_class_0': 0.6341426632653001, 'weight_class_1': 8.723919037354857, 'weight_class_2': 7.077259191294042}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:01,887] Trial 2220 finished with value: 0.9491247422636121 and parameters: {'weight_class_0': 0.8944793386268117, 'weight_class_1': 9.13491646657983, 'weight_class_2': 7.093181481542315}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:01,902] Trial 2221 finished with value: 0.9490359261025217 and parameters: {'weight_class_0': 0.9251903767833745, 'weight_class_1': 9.170993370155406, 'weight_class_2': 7.184717168013885}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:01,952] Trial 2224 finished with value: 0.9497212952526887 and parameters: {'weight_class_0': 0.6766669343137136, 'weight_class_1': 8.665320568389589, 'weight_class_2': 7.878592869023143}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:01,984] Trial 2225 finished with value: 0.9497514259951468 and parameters: {'weight_class_0': 0.6604863626838997, 'weight_class_1': 8.72241332027986, 'weight_class_2': 7.8787222776282135}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:01,996] Trial 2223 finished with value: 0.9497095359803467 and parameters: {'weight_class_0': 0.6723205269150216, 'weight_class_1': 9.126926569854371, 'weight_class_2': 7.861068709124837}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  74%|██████████████████████████████████████████████████████████████████████████████████████████████████▏                                 | 2232/3000 [00:55<00:23, 32.16it/s]

[I 2026-07-10 16:13:02,060] Trial 2226 finished with value: 0.9497238358601812 and parameters: {'weight_class_0': 0.6324241887199167, 'weight_class_1': 9.187321659590886, 'weight_class_2': 7.822393874299847}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:02,074] Trial 2228 finished with value: 0.9496769572901046 and parameters: {'weight_class_0': 0.6453600980218844, 'weight_class_1': 9.164949243474009, 'weight_class_2': 7.21355362665219}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:02,095] Trial 2227 finished with value: 0.9496459583311191 and parameters: {'weight_class_0': 0.6257301606355656, 'weight_class_1': 8.652779345220367, 'weight_class_2': 7.919510748597789}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:02,129] Trial 2229 finished with value: 0.9494681166881077 and parameters: {'weight_class_0': 0.6697721758188114, 'weight_class_1': 8.74807049242866, 'weight_class_2': 9.530746423209688}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:02,183] Trial 2230 finished with value: 0.9497342107773988 and parameters: {'weight_class_0': 0.6677971769432175, 'weight_class_1': 8.706235118276485, 'weight_class_2': 7.859689452861385}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:02,200] Trial 2231 finished with value: 0.9496334151184493 and parameters: {'weight_class_0': 0.6086744700959812, 'weight_class_1': 8.69017884780385, 'weight_class_2': 7.742682901956748}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:02,236] Trial 2232 finished with value: 0.9497291815772332 and parameters: {'weight_class_0': 0.6389544855411222, 'weight_class_1': 8.130756023873916, 'weight_class_2': 7.8133112529540405}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  75%|██████████████████████████████████████████████████████████████████████████████████████████████████▌                                 | 2239/3000 [00:55<00:25, 29.38it/s]

[I 2026-07-10 16:13:02,280] Trial 2233 finished with value: 0.9487574269183132 and parameters: {'weight_class_0': 0.6417398543235656, 'weight_class_1': 8.101915000543, 'weight_class_2': 3.7616740272360962}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:02,341] Trial 2234 finished with value: 0.9497007052251624 and parameters: {'weight_class_0': 0.6363828484981819, 'weight_class_1': 8.10363641049151, 'weight_class_2': 7.820175797213381}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:02,355] Trial 2236 finished with value: 0.9496096861709103 and parameters: {'weight_class_0': 0.5977750093183344, 'weight_class_1': 8.862903277922378, 'weight_class_2': 7.985446620298265}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:02,362] Trial 2235 finished with value: 0.9465044569312372 and parameters: {'weight_class_0': 0.19233717671372663, 'weight_class_1': 8.971977148990385, 'weight_class_2': 7.973029666159899}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:02,365] Trial 2237 finished with value: 0.9496414502757317 and parameters: {'weight_class_0': 0.6284084695122258, 'weight_class_1': 9.062256215026595, 'weight_class_2': 8.015811601483886}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:02,413] Trial 2238 finished with value: 0.9468179060669955 and parameters: {'weight_class_0': 0.23722263715248137, 'weight_class_1': 8.712241867404275, 'weight_class_2': 1.1289435111160202}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:02,453] Trial 2240 finished with value: 0.948246370550085 and parameters: {'weight_class_0': 0.2887512590439772, 'weight_class_1': 8.919812480427995, 'weight_class_2': 7.980049345462586}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  75%|██████████████████████████████████████████████████████████████████████████████████████████████████▊                                 | 2247/3000 [00:55<00:23, 32.33it/s]

[I 2026-07-10 16:13:02,455] Trial 2239 finished with value: 0.946096039192331 and parameters: {'weight_class_0': 0.18339251617925645, 'weight_class_1': 8.930610863962945, 'weight_class_2': 8.461010133817474}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:02,497] Trial 2241 finished with value: 0.9465263443596571 and parameters: {'weight_class_0': 0.19100017814494963, 'weight_class_1': 8.83814262254922, 'weight_class_2': 7.997265382884848}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:02,517] Trial 2242 finished with value: 0.9459715899235247 and parameters: {'weight_class_0': 0.17496117683955698, 'weight_class_1': 8.913977062920292, 'weight_class_2': 7.833471605468235}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:02,575] Trial 2243 finished with value: 0.9467904470768383 and parameters: {'weight_class_0': 0.2026780031746026, 'weight_class_1': 8.916712635274335, 'weight_class_2': 7.965736405528398}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:02,598] Trial 2244 finished with value: 0.9488262195354148 and parameters: {'weight_class_0': 0.39098219858214084, 'weight_class_1': 8.906512094753593, 'weight_class_2': 8.385288232445621}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:02,601] Trial 2245 finished with value: 0.9471440901269208 and parameters: {'weight_class_0': 0.21994738811013104, 'weight_class_1': 8.950889696720171, 'weight_class_2': 8.076804004835118}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:02,677] Trial 2246 finished with value: 0.9470283929474937 and parameters: {'weight_class_0': 0.214344178900102, 'weight_class_1': 8.878708495854685, 'weight_class_2': 8.10054722792639}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:02,704] Trial 2248 finished with value: 0.9479055873656667 and parameters: {'weight_class_0': 0.2645018286465884, 'weight_class_1': 8.886101037797717, 'weight_class_2': 8.474204346286916}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:13:02,742] Trial 2247 finished with value: 0.946489706106869 and parameters: {'weight_class_0': 0.19111173700282247, 'weight_class_1': 8.834582819010675, 'weight_class_2': 8.09865875677743}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:02,778] Trial 2249 finished with value: 0.9492589695613072 and parameters: {'weight_class_0': 0.4398495893871662, 'weight_class_1': 8.762641937411411, 'weight_class_2': 7.724961143939879}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:02,841] Trial 2250 finished with value: 0.9492508622993828 and parameters: {'weight_class_0': 0.46222773143679213, 'weight_class_1': 8.773843007589, 'weight_class_2': 8.17138059381293}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:02,855] Trial 2252 finished with value: 0.9495798735205999 and parameters: {'weight_class_0': 0.8220925334877921, 'weight_class_1': 8.801842630501241, 'weight_class_2': 8.49412969601273}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:02,872] Trial 2251 finished with value: 0.9493638928397449 and parameters: {'weight_class_0': 0.4641946633005911, 'weight_class_1': 8.768188102946365, 'weight_class_2': 7.6917592261509435}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  75%|███████████████████████████████████████████████████████████████████████████████████████████████████▍                                | 2260/3000 [00:56<00:24, 30.15it/s]

[I 2026-07-10 16:13:02,945] Trial 2253 finished with value: 0.9492493708384337 and parameters: {'weight_class_0': 0.46421079918405556, 'weight_class_1': 8.764844760661013, 'weight_class_2': 8.337559553668187}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:02,956] Trial 2254 finished with value: 0.9492594687195793 and parameters: {'weight_class_0': 0.43779818978597057, 'weight_class_1': 8.763183911043855, 'weight_class_2': 7.6972611425730975}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:02,966] Trial 2255 finished with value: 0.9494626919553699 and parameters: {'weight_class_0': 0.8232761504815311, 'weight_class_1': 8.6025836954738, 'weight_class_2': 7.664846297065161}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:03,017] Trial 2256 finished with value: 0.9495147331614663 and parameters: {'weight_class_0': 0.8291438436183102, 'weight_class_1': 8.654863914459158, 'weight_class_2': 8.303595344271637}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:03,027] Trial 2257 finished with value: 0.94947803558466 and parameters: {'weight_class_0': 0.8235626661056846, 'weight_class_1': 8.683989477500875, 'weight_class_2': 7.7392227209592335}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:03,028] Trial 2258 finished with value: 0.949437912059687 and parameters: {'weight_class_0': 0.8303674278057298, 'weight_class_1': 8.59238524060024, 'weight_class_2': 7.670590800893542}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:03,080] Trial 2259 finished with value: 0.9494371549966839 and parameters: {'weight_class_0': 0.8258682042592749, 'weight_class_1': 8.601825292310547, 'weight_class_2': 7.7065032943989955}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:03,095] Trial 2260 finished with value: 0.9494253012630326 and parameters: {'weight_class_0': 0.8483239002715544, 'weight_class_1': 8.569515056913541, 'weight_class_2': 7.6981158738328554}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  76%|███████████████████████████████████████████████████████████████████████████████████████████████████▋                                | 2266/3000 [00:56<00:22, 32.40it/s]

[I 2026-07-10 16:13:03,140] Trial 2261 finished with value: 0.9495711535077532 and parameters: {'weight_class_0': 0.8054633901712324, 'weight_class_1': 8.603796171277004, 'weight_class_2': 8.257720940535021}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:03,169] Trial 2262 finished with value: 0.9484281017404217 and parameters: {'weight_class_0': 1.117436875376586, 'weight_class_1': 8.573512761355747, 'weight_class_2': 7.337782692072837}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:03,228] Trial 2264 finished with value: 0.933803190329774 and parameters: {'weight_class_0': 1.096987555890538, 'weight_class_1': 8.599918461935605, 'weight_class_2': 2.1325899038990177}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:03,253] Trial 2263 finished with value: 0.9485807597367023 and parameters: {'weight_class_0': 1.0902144549116262, 'weight_class_1': 8.565138213905756, 'weight_class_2': 7.383196630834733}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:03,285] Trial 2266 finished with value: 0.9483242406642294 and parameters: {'weight_class_0': 1.1650084437260797, 'weight_class_1': 8.57812628666688, 'weight_class_2': 7.327351515368906}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:03,294] Trial 2265 finished with value: 0.9475978509213556 and parameters: {'weight_class_0': 1.1510563137015501, 'weight_class_1': 8.474966743442456, 'weight_class_2': 5.91209229779681}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  76%|████████████████████████████████████████████████████████████████████████████████████████████████████                                | 2273/3000 [00:56<00:23, 31.33it/s]

[I 2026-07-10 16:13:03,385] Trial 2267 finished with value: 0.9185552137898095 and parameters: {'weight_class_0': 4.737515317389174, 'weight_class_1': 9.250641021797646, 'weight_class_2': 8.648353009420363}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:03,395] Trial 2268 finished with value: 0.9485735713157109 and parameters: {'weight_class_0': 1.1176795697934916, 'weight_class_1': 9.21061551949389, 'weight_class_2': 7.362376157290993}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:03,419] Trial 2269 finished with value: 0.948540300632987 and parameters: {'weight_class_0': 1.1394432802494479, 'weight_class_1': 9.329614372317238, 'weight_class_2': 7.332948091690878}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:03,453] Trial 2270 finished with value: 0.94842123676764 and parameters: {'weight_class_0': 1.1069805164325495, 'weight_class_1': 8.493403681481562, 'weight_class_2': 7.308279306903999}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:03,484] Trial 2271 finished with value: 0.6577323336849796 and parameters: {'weight_class_0': 0.004744815944991987, 'weight_class_1': 9.312293654025739, 'weight_class_2': 7.369206041472181}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:03,535] Trial 2272 finished with value: 0.9483613664177152 and parameters: {'weight_class_0': 1.1233632022479894, 'weight_class_1': 8.181645588899995, 'weight_class_2': 7.336876962442932}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:03,569] Trial 2273 finished with value: 0.9486711014757799 and parameters: {'weight_class_0': 1.093308738417125, 'weight_class_1': 9.250131413922626, 'weight_class_2': 7.334435128731246}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  76%|████████████████████████████████████████████████████████████████████████████████████████████████████▎                               | 2280/3000 [00:57<00:22, 31.55it/s]

[I 2026-07-10 16:13:03,577] Trial 2274 finished with value: 0.9486097858096797 and parameters: {'weight_class_0': 1.1052800879640814, 'weight_class_1': 9.225320455466036, 'weight_class_2': 7.355360690623954}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:03,592] Trial 2275 finished with value: 0.9001566838875519 and parameters: {'weight_class_0': 5.564025601849567, 'weight_class_1': 9.223763163055445, 'weight_class_2': 6.845918247653568}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:03,608] Trial 2276 finished with value: 0.9496448384008627 and parameters: {'weight_class_0': 0.5636142849383441, 'weight_class_1': 9.087026535168729, 'weight_class_2': 7.357592353834282}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:03,663] Trial 2277 finished with value: 0.9497456397035187 and parameters: {'weight_class_0': 0.610882140417899, 'weight_class_1': 9.230949948920706, 'weight_class_2': 6.918149148819397}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:03,688] Trial 2278 finished with value: 0.883838209979909 and parameters: {'weight_class_0': 7.086754994182223, 'weight_class_1': 9.180568699835144, 'weight_class_2': 6.799643738874964}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:03,756] Trial 2280 finished with value: 0.9496042795622927 and parameters: {'weight_class_0': 0.5456915735948906, 'weight_class_1': 8.180523559756754, 'weight_class_2': 7.385590961714173}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:03,776] Trial 2279 finished with value: 0.9491838343202431 and parameters: {'weight_class_0': 0.5568399325980042, 'weight_class_1': 4.872180294793927, 'weight_class_2': 7.337954605578538}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  76%|████████████████████████████████████████████████████████████████████████████████████████████████████▋                               | 2287/3000 [00:57<00:23, 29.97it/s]

[I 2026-07-10 16:13:03,816] Trial 2281 finished with value: 0.949694524059233 and parameters: {'weight_class_0': 0.5967289707888154, 'weight_class_1': 8.202584556809441, 'weight_class_2': 6.8118147369472055}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:03,824] Trial 2282 finished with value: 0.9457284320795347 and parameters: {'weight_class_0': 1.5439297307514717, 'weight_class_1': 8.214061337196098, 'weight_class_2': 6.790498030827305}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:03,881] Trial 2283 finished with value: 0.9384936859913172 and parameters: {'weight_class_0': 0.5686490603116594, 'weight_class_1': 1.2318731272602337, 'weight_class_2': 6.89881965601766}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:03,927] Trial 2285 finished with value: 0.9494487622573052 and parameters: {'weight_class_0': 0.528294816264933, 'weight_class_1': 7.854050131971877, 'weight_class_2': 7.8055845985762184}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:03,947] Trial 2284 finished with value: 0.9375513346684793 and parameters: {'weight_class_0': 0.578929642733758, 'weight_class_1': 1.1981703158071948, 'weight_class_2': 6.904129085306878}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:03,957] Trial 2286 finished with value: 0.9468261975290195 and parameters: {'weight_class_0': 1.490965848425525, 'weight_class_1': 8.282945533763153, 'weight_class_2': 7.841474220467343}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:03,995] Trial 2287 finished with value: 0.9496891336573063 and parameters: {'weight_class_0': 0.6649937489769056, 'weight_class_1': 7.868722691855378, 'weight_class_2': 7.849874282446168}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  76%|████████████████████████████████████████████████████████████████████████████████████████████████████▉                               | 2294/3000 [00:57<00:22, 31.47it/s]

[I 2026-07-10 16:13:04,016] Trial 2289 finished with value: 0.8689443110553725 and parameters: {'weight_class_0': 8.899529192680662, 'weight_class_1': 9.122004096132873, 'weight_class_2': 6.300333363497554}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:04,020] Trial 2288 finished with value: 0.9495819833607507 and parameters: {'weight_class_0': 0.4802143366339688, 'weight_class_1': 9.316074049808229, 'weight_class_2': 6.551471061111498}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:04,067] Trial 2290 finished with value: 0.9470457918109266 and parameters: {'weight_class_0': 1.426124048690822, 'weight_class_1': 9.446394589454252, 'weight_class_2': 6.920708807754576}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:04,108] Trial 2291 finished with value: 0.9495400827086288 and parameters: {'weight_class_0': 0.4588010128792236, 'weight_class_1': 9.604591995651976, 'weight_class_2': 6.305224274448145}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:04,165] Trial 2292 finished with value: 0.9491647789014435 and parameters: {'weight_class_0': 0.39809361353219663, 'weight_class_1': 9.140216336434156, 'weight_class_2': 6.960864074022228}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:04,184] Trial 2293 finished with value: 0.949195526339727 and parameters: {'weight_class_0': 0.3933399025841906, 'weight_class_1': 9.298629205986455, 'weight_class_2': 6.551911735946562}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:04,200] Trial 2294 finished with value: 0.9493349054377749 and parameters: {'weight_class_0': 0.42174964389760666, 'weight_class_1': 9.772233655703783, 'weight_class_2': 6.65873993014044}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  77%|█████████████████████████████████████████████████████████████████████████████████████████████████████▏                              | 2301/3000 [00:57<00:22, 30.99it/s]

[I 2026-07-10 16:13:04,217] Trial 2295 finished with value: 0.9492406955104619 and parameters: {'weight_class_0': 0.3864479122615332, 'weight_class_1': 9.739076019992421, 'weight_class_2': 6.317759951904999}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:04,285] Trial 2297 finished with value: 0.9496917371017876 and parameters: {'weight_class_0': 0.7506517464934691, 'weight_class_1': 9.78550966190245, 'weight_class_2': 7.910812478141485}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:04,321] Trial 2296 finished with value: 0.9493283352594108 and parameters: {'weight_class_0': 0.36718317888488944, 'weight_class_1': 9.634008008384704, 'weight_class_2': 3.504459675777116}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:04,331] Trial 2298 finished with value: 0.9493613292583397 and parameters: {'weight_class_0': 0.7920639844018282, 'weight_class_1': 9.572325293300938, 'weight_class_2': 6.487702667792184}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:04,406] Trial 2299 finished with value: 0.9199324128183628 and parameters: {'weight_class_0': 3.843771532202946, 'weight_class_1': 9.541116574697375, 'weight_class_2': 6.418310373955077}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:04,407] Trial 2300 finished with value: 0.9485477342297471 and parameters: {'weight_class_0': 0.3341435414126578, 'weight_class_1': 9.58845111752589, 'weight_class_2': 7.634383230704342}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:04,408] Trial 2301 finished with value: 0.9490716392925206 and parameters: {'weight_class_0': 0.3553197212877333, 'weight_class_1': 9.541460251283684, 'weight_class_2': 6.488890501364161}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:13:04,460] Trial 2302 finished with value: 0.9495815054230644 and parameters: {'weight_class_0': 0.8002135435367723, 'weight_class_1': 9.659636445676602, 'weight_class_2': 7.6654855502837815}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:04,467] Trial 2303 finished with value: 0.9492127225646382 and parameters: {'weight_class_0': 0.8257797440925527, 'weight_class_1': 9.080592456967802, 'weight_class_2': 6.623365600097625}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:04,552] Trial 2305 finished with value: 0.9495453664313452 and parameters: {'weight_class_0': 0.802304692182281, 'weight_class_1': 9.378027828431849, 'weight_class_2': 7.614085627079031}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:04,575] Trial 2304 finished with value: 0.949489610077166 and parameters: {'weight_class_0': 0.820246653061461, 'weight_class_1': 8.940162240229414, 'weight_class_2': 7.654039091477132}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:04,580] Trial 2306 finished with value: 0.949613507856777 and parameters: {'weight_class_0': 0.7853317754893009, 'weight_class_1': 9.467936056485827, 'weight_class_2': 7.60478587888242}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:04,630] Trial 2307 finished with value: 0.9494984292775724 and parameters: {'weight_class_0': 0.8329471771430427, 'weight_class_1': 9.36772855500342, 'weight_class_2': 7.6389118109262215}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:13:04,652] Trial 2308 finished with value: 0.9494370590754758 and parameters: {'weight_class_0': 0.8524765934399776, 'weight_class_1': 9.67617077667154, 'weight_class_2': 7.60717050291856}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:04,704] Trial 2309 finished with value: 0.9494678505152309 and parameters: {'weight_class_0': 0.8444545512697345, 'weight_class_1': 9.539101781322096, 'weight_class_2': 7.6378797484181895}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:04,727] Trial 2310 finished with value: 0.9494113596603091 and parameters: {'weight_class_0': 0.846329954067813, 'weight_class_1': 9.09759042421136, 'weight_class_2': 7.646176515583301}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:04,736] Trial 2311 finished with value: 0.9493701485900021 and parameters: {'weight_class_0': 0.8784380831491096, 'weight_class_1': 9.405099695977814, 'weight_class_2': 7.601836968700205}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:04,784] Trial 2312 finished with value: 0.6624118723853493 and parameters: {'weight_class_0': 0.009545166756913304, 'weight_class_1': 9.956625538048819, 'weight_class_2': 7.586701940197817}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:04,797] Trial 2313 finished with value: 0.9492016869168122 and parameters: {'weight_class_0': 0.9183170441078423, 'weight_class_1': 9.367235343019548, 'weight_class_2': 7.613268797360317}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:04,831] Trial 2314 finished with value: 0.9489951772515957 and parameters: {'weight_class_0': 0.9764101704071317, 'weight_class_1': 9.040896641833047, 'weight_class_2': 7.68977360790233}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  77%|██████████████████████████████████████████████████████████████████████████████████████████████████████                              | 2321/3000 [00:58<00:21, 30.98it/s]

[I 2026-07-10 16:13:04,870] Trial 2315 finished with value: 0.6646245342909043 and parameters: {'weight_class_0': 0.007095338529965356, 'weight_class_1': 4.321419937228444, 'weight_class_2': 7.5587190001107745}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:04,950] Trial 2316 finished with value: 0.9491388667417744 and parameters: {'weight_class_0': 0.9648351562332922, 'weight_class_1': 9.054621185302576, 'weight_class_2': 7.934736693417515}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:04,991] Trial 2317 finished with value: 0.7701616801565363 and parameters: {'weight_class_0': 0.017491748516740624, 'weight_class_1': 9.035799831202274, 'weight_class_2': 0.6419306858833824}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:05,004] Trial 2318 finished with value: 0.9496681062805298 and parameters: {'weight_class_0': 0.6315832732827856, 'weight_class_1': 9.074804190445686, 'weight_class_2': 7.939815760919176}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:05,018] Trial 2319 finished with value: 0.9497293180738454 and parameters: {'weight_class_0': 0.6577621169077641, 'weight_class_1': 9.128314108386864, 'weight_class_2': 7.890686437269403}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:05,070] Trial 2320 finished with value: 0.6728235815544061 and parameters: {'weight_class_0': 0.012161282132439388, 'weight_class_1': 9.072066420903063, 'weight_class_2': 7.898283070652327}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:05,084] Trial 2321 finished with value: 0.9497036722487596 and parameters: {'weight_class_0': 0.6455885957056403, 'weight_class_1': 8.951258426484939, 'weight_class_2': 7.208533878525152}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:13:05,102] Trial 2323 finished with value: 0.9492965455803098 and parameters: {'weight_class_0': 0.6502214792862937, 'weight_class_1': 8.9185886133662, 'weight_class_2': 5.312323364397352}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:05,117] Trial 2322 finished with value: 0.9497006926216724 and parameters: {'weight_class_0': 0.67980611579534, 'weight_class_1': 9.006059601448447, 'weight_class_2': 7.915171599023016}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:05,179] Trial 2324 finished with value: 0.9497181671345652 and parameters: {'weight_class_0': 0.644689288023934, 'weight_class_1': 8.973880735306885, 'weight_class_2': 7.950061038361672}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:05,202] Trial 2325 finished with value: 0.9496860723828456 and parameters: {'weight_class_0': 0.6445473522659063, 'weight_class_1': 9.047803644563146, 'weight_class_2': 7.183456707515801}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:05,236] Trial 2326 finished with value: 0.9392575907832822 and parameters: {'weight_class_0': 2.59804880845474, 'weight_class_1': 9.030051603813886, 'weight_class_2': 7.929341997594713}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:05,240] Trial 2327 finished with value: 0.9496829508543443 and parameters: {'weight_class_0': 0.6352497730803669, 'weight_class_1': 9.010391318560707, 'weight_class_2': 7.88907829969066}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:05,307] Trial 2328 finished with value: 0.9496947637167673 and parameters: {'weight_class_0': 0.6377203138731725, 'weight_class_1': 9.045760542055834, 'weight_class_2': 7.184636905022784}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  78%|██████████████████████████████████████████████████████████████████████████████████████████████████████▋                             | 2334/3000 [00:58<00:21, 30.41it/s]

[I 2026-07-10 16:13:05,321] Trial 2329 finished with value: 0.9497106365736686 and parameters: {'weight_class_0': 0.6002813696770575, 'weight_class_1': 8.885655749105723, 'weight_class_2': 7.203762183423609}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:05,406] Trial 2331 finished with value: 0.9496947623263535 and parameters: {'weight_class_0': 0.6688762386616258, 'weight_class_1': 8.945729202662656, 'weight_class_2': 7.17643189194123}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:05,420] Trial 2330 finished with value: 0.9479934395328438 and parameters: {'weight_class_0': 0.2543073774150929, 'weight_class_1': 8.927933980716054, 'weight_class_2': 7.227470190878179}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:05,460] Trial 2332 finished with value: 0.9484024425695936 and parameters: {'weight_class_0': 0.29209227538787685, 'weight_class_1': 9.307509605775127, 'weight_class_2': 6.9754744629639305}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:05,477] Trial 2334 finished with value: 0.9482556262155972 and parameters: {'weight_class_0': 0.2957682816278251, 'weight_class_1': 8.820805003620567, 'weight_class_2': 8.214527229847773}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:05,487] Trial 2333 finished with value: 0.9486749250641138 and parameters: {'weight_class_0': 0.3266975736048977, 'weight_class_1': 8.837497150154746, 'weight_class_2': 7.208245176839447}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:13:05,530] Trial 2335 finished with value: 0.9478764541584054 and parameters: {'weight_class_0': 0.2533600519413222, 'weight_class_1': 9.334996005597258, 'weight_class_2': 7.205599711045521}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:05,558] Trial 2336 finished with value: 0.9486105966741408 and parameters: {'weight_class_0': 0.33809437471980064, 'weight_class_1': 8.75361786639572, 'weight_class_2': 8.230592057410263}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:05,605] Trial 2337 finished with value: 0.9487834405149681 and parameters: {'weight_class_0': 0.33328174218965684, 'weight_class_1': 8.787551975203533, 'weight_class_2': 6.982546887784233}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:05,612] Trial 2338 finished with value: 0.9487551438463218 and parameters: {'weight_class_0': 0.3407446126885605, 'weight_class_1': 8.762961781486975, 'weight_class_2': 7.208145816348506}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:05,614] Trial 2339 finished with value: 0.9486682802786852 and parameters: {'weight_class_0': 0.3150615811970034, 'weight_class_1': 4.54627630731856, 'weight_class_2': 6.9627896819427795}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:05,685] Trial 2340 finished with value: 0.9482571742530483 and parameters: {'weight_class_0': 0.2687276432079949, 'weight_class_1': 8.756171870844689, 'weight_class_2': 6.950599788179012}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:05,717] Trial 2341 finished with value: 0.9481993226235245 and parameters: {'weight_class_0': 0.27142522362412164, 'weight_class_1': 3.2801972934975105, 'weight_class_2': 6.9293300483646165}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  78%|███████████████████████████████████████████████████████████████████████████████████████████████████████▎                            | 2347/3000 [00:59<00:21, 29.71it/s]

[I 2026-07-10 16:13:05,760] Trial 2342 finished with value: 0.9486895697695984 and parameters: {'weight_class_0': 0.35883833757527434, 'weight_class_1': 8.759741776905384, 'weight_class_2': 8.218102823383136}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:05,780] Trial 2343 finished with value: 0.9491024627754965 and parameters: {'weight_class_0': 0.42983053818185113, 'weight_class_1': 8.792233810161877, 'weight_class_2': 8.149730469139307}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:05,846] Trial 2344 finished with value: 0.9494284632646072 and parameters: {'weight_class_0': 0.47117053300509426, 'weight_class_1': 8.539274690545996, 'weight_class_2': 7.430339838059406}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:05,853] Trial 2345 finished with value: 0.9494046875965397 and parameters: {'weight_class_0': 0.4580101075712416, 'weight_class_1': 8.571693589004402, 'weight_class_2': 7.424526199008738}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:05,891] Trial 2346 finished with value: 0.9493971934272398 and parameters: {'weight_class_0': 0.43848058240229365, 'weight_class_1': 8.585185846796252, 'weight_class_2': 6.907398453708243}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:05,923] Trial 2347 finished with value: 0.9487738514241254 and parameters: {'weight_class_0': 0.9992687691750095, 'weight_class_1': 8.568314764198377, 'weight_class_2': 6.910163802747382}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  78%|███████████████████████████████████████████████████████████████████████████████████████████████████████▌                            | 2354/3000 [00:59<00:21, 30.26it/s]

[I 2026-07-10 16:13:05,986] Trial 2348 finished with value: 0.9489945183558994 and parameters: {'weight_class_0': 0.9445689258860029, 'weight_class_1': 8.577957480317036, 'weight_class_2': 7.421550533623173}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:06,005] Trial 2349 finished with value: 0.9488937729589083 and parameters: {'weight_class_0': 0.9906679988031402, 'weight_class_1': 8.537717022321145, 'weight_class_2': 7.399994627385231}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:06,028] Trial 2351 finished with value: 0.948845195038491 and parameters: {'weight_class_0': 1.0288744690513387, 'weight_class_1': 8.551561452794706, 'weight_class_2': 7.47323495799773}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:06,034] Trial 2350 finished with value: 0.8807577666751607 and parameters: {'weight_class_0': 5.0752139134279926, 'weight_class_1': 3.188881505292424, 'weight_class_2': 7.477063169358813}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:06,116] Trial 2352 finished with value: 0.9489211422926025 and parameters: {'weight_class_0': 0.965668251041593, 'weight_class_1': 8.469875182766662, 'weight_class_2': 7.407357710554837}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:06,117] Trial 2354 finished with value: 0.948952586614186 and parameters: {'weight_class_0': 0.9644091889558704, 'weight_class_1': 8.555083395898729, 'weight_class_2': 7.426066649251666}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:06,122] Trial 2353 finished with value: 0.9489138172722019 and parameters: {'weight_class_0': 0.9713555704382156, 'weight_class_1': 8.615971848012965, 'weight_class_2': 7.428062430684055}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:13:06,174] Trial 2356 finished with value: 0.9488496787300171 and parameters: {'weight_class_0': 1.0179801071259902, 'weight_class_1': 8.454800978388995, 'weight_class_2': 7.44173828974666}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:06,185] Trial 2355 finished with value: 0.9171834862813352 and parameters: {'weight_class_0': 4.274215960947488, 'weight_class_1': 8.477509524701503, 'weight_class_2': 7.434843052519668}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:06,250] Trial 2358 finished with value: 0.948819062555826 and parameters: {'weight_class_0': 1.0291022455636563, 'weight_class_1': 8.36088832069113, 'weight_class_2': 7.467152472264664}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:06,270] Trial 2357 finished with value: 0.9488775367902554 and parameters: {'weight_class_0': 0.9921322706917204, 'weight_class_1': 8.348956536776075, 'weight_class_2': 7.432820771045609}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:06,323] Trial 2359 finished with value: 0.9489986026524676 and parameters: {'weight_class_0': 0.9391639298352442, 'weight_class_1': 8.302725564896413, 'weight_class_2': 7.447399540583349}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:06,359] Trial 2360 finished with value: 0.9471337190643144 and parameters: {'weight_class_0': 1.4175340686770954, 'weight_class_1': 8.35719797973542, 'weight_class_2': 7.475252367720921}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:06,371] Trial 2362 finished with value: 0.9476298008831846 and parameters: {'weight_class_0': 1.3645231802515454, 'weight_class_1': 8.263764668415233, 'weight_class_2': 7.799166235119766}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  79%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏                           | 2368/3000 [00:59<00:20, 30.63it/s]

[I 2026-07-10 16:13:06,406] Trial 2361 finished with value: 0.9473093939668554 and parameters: {'weight_class_0': 1.386876177920778, 'weight_class_1': 8.334797065657767, 'weight_class_2': 7.450730408861933}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:06,425] Trial 2363 finished with value: 0.9496148053604675 and parameters: {'weight_class_0': 0.7418391237844183, 'weight_class_1': 8.425325511854474, 'weight_class_2': 7.45481683312056}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:06,462] Trial 2364 finished with value: 0.9467984912594809 and parameters: {'weight_class_0': 1.3784361382776074, 'weight_class_1': 8.34072730339479, 'weight_class_2': 6.735169518059712}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:06,526] Trial 2365 finished with value: 0.9496802400776995 and parameters: {'weight_class_0': 0.6677674224430273, 'weight_class_1': 8.054412628004751, 'weight_class_2': 7.778699303658757}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:06,543] Trial 2366 finished with value: 0.9473036814786732 and parameters: {'weight_class_0': 1.2956651210467862, 'weight_class_1': 8.328279134047245, 'weight_class_2': 6.724953528116512}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:06,559] Trial 2368 finished with value: 0.9478712613140162 and parameters: {'weight_class_0': 1.319480616667561, 'weight_class_1': 8.316056718348865, 'weight_class_2': 7.792413984405681}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:06,580] Trial 2367 finished with value: 0.9495079349295507 and parameters: {'weight_class_0': 0.7289236275709802, 'weight_class_1': 8.306407299981787, 'weight_class_2': 6.746569892338969}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  79%|████████████████████████████████████████████████████████████████████████████████████████████████████████▌                           | 2375/3000 [01:00<00:19, 32.37it/s]

[I 2026-07-10 16:13:06,650] Trial 2369 finished with value: 0.9496839386773894 and parameters: {'weight_class_0': 0.7036035637320787, 'weight_class_1': 9.29290217783305, 'weight_class_2': 7.74186997550006}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:06,654] Trial 2370 finished with value: 0.9478636337088618 and parameters: {'weight_class_0': 1.363416804624252, 'weight_class_1': 9.25108224194484, 'weight_class_2': 7.789194659922936}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:06,670] Trial 2371 finished with value: 0.9474683192686367 and parameters: {'weight_class_0': 1.3749636565336845, 'weight_class_1': 8.025475792905308, 'weight_class_2': 7.8143044561607935}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:06,734] Trial 2372 finished with value: 0.9497076749264136 and parameters: {'weight_class_0': 0.6824838690067546, 'weight_class_1': 9.291365187457341, 'weight_class_2': 7.785079116471606}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:06,760] Trial 2373 finished with value: 0.9494224482896155 and parameters: {'weight_class_0': 0.5160359101097833, 'weight_class_1': 8.037479938463715, 'weight_class_2': 7.821130169443891}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:06,814] Trial 2374 finished with value: 0.9495029415249472 and parameters: {'weight_class_0': 0.551454199607755, 'weight_class_1': 8.066648855061953, 'weight_class_2': 7.795555197424235}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:06,831] Trial 2375 finished with value: 0.9495126599571352 and parameters: {'weight_class_0': 0.558172005043332, 'weight_class_1': 8.065784877655688, 'weight_class_2': 7.799303033381609}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  79%|████████████████████████████████████████████████████████████████████████████████████████████████████████▊                           | 2382/3000 [01:00<00:19, 31.28it/s]

[I 2026-07-10 16:13:06,852] Trial 2376 finished with value: 0.9495120114931673 and parameters: {'weight_class_0': 0.5552733416221458, 'weight_class_1': 7.988823612948559, 'weight_class_2': 7.737920029998044}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:06,906] Trial 2377 finished with value: 0.949360005453545 and parameters: {'weight_class_0': 0.5224815097276783, 'weight_class_1': 9.21374300304471, 'weight_class_2': 8.587172907955065}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:06,912] Trial 2378 finished with value: 0.949539976692542 and parameters: {'weight_class_0': 0.5204752461037754, 'weight_class_1': 9.27038766683818, 'weight_class_2': 7.215637525513745}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:06,929] Trial 2379 finished with value: 0.949620607781588 and parameters: {'weight_class_0': 0.530476967973599, 'weight_class_1': 8.032431539544545, 'weight_class_2': 7.1041890904952645}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:06,985] Trial 2380 finished with value: 0.9494363338964438 and parameters: {'weight_class_0': 0.49930557489521593, 'weight_class_1': 9.217578658547417, 'weight_class_2': 7.192912899741209}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:07,030] Trial 2382 finished with value: 0.9496136116475107 and parameters: {'weight_class_0': 0.5251827154642901, 'weight_class_1': 7.985223239490817, 'weight_class_2': 7.164424170342211}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:07,056] Trial 2381 finished with value: 0.9495997280811882 and parameters: {'weight_class_0': 0.5297981387755746, 'weight_class_1': 7.911393697182772, 'weight_class_2': 7.2011321501975445}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████                           | 2389/3000 [01:00<00:19, 31.04it/s]

[I 2026-07-10 16:13:07,102] Trial 2383 finished with value: 0.9495497774221949 and parameters: {'weight_class_0': 0.5137128073916802, 'weight_class_1': 7.8105254859375775, 'weight_class_2': 7.188821155689015}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:07,122] Trial 2384 finished with value: 0.9495248418985587 and parameters: {'weight_class_0': 0.49325657083117924, 'weight_class_1': 7.964365358827382, 'weight_class_2': 7.200646677389922}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:07,157] Trial 2385 finished with value: 0.9497466104926472 and parameters: {'weight_class_0': 0.5862669005703888, 'weight_class_1': 7.881049162940525, 'weight_class_2': 7.180081759333045}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:07,170] Trial 2386 finished with value: 0.949409472687999 and parameters: {'weight_class_0': 0.5248459680314203, 'weight_class_1': 7.876365903029497, 'weight_class_2': 8.071586667705864}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:07,199] Trial 2387 finished with value: 0.949489891338537 and parameters: {'weight_class_0': 0.501641732508673, 'weight_class_1': 7.832319879498415, 'weight_class_2': 7.199227989284068}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:07,226] Trial 2388 finished with value: 0.9494854483536711 and parameters: {'weight_class_0': 0.49511001611185257, 'weight_class_1': 7.823316047143641, 'weight_class_2': 7.176422169374905}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:07,304] Trial 2389 finished with value: 0.9494906723411827 and parameters: {'weight_class_0': 0.7502865098657949, 'weight_class_1': 7.834575689259438, 'weight_class_2': 7.208468828481417}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▍                          | 2396/3000 [01:00<00:19, 31.52it/s]

[I 2026-07-10 16:13:07,309] Trial 2390 finished with value: 0.9445843290899734 and parameters: {'weight_class_0': 0.13650325805853225, 'weight_class_1': 7.843601579420657, 'weight_class_2': 8.084106404638765}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:07,327] Trial 2391 finished with value: 0.9494088176213772 and parameters: {'weight_class_0': 0.7806866725181998, 'weight_class_1': 7.847929206479326, 'weight_class_2': 7.210381878627344}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:07,395] Trial 2392 finished with value: 0.9495789644328445 and parameters: {'weight_class_0': 0.7677643467777399, 'weight_class_1': 7.8834304401728685, 'weight_class_2': 8.123997298199724}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:07,400] Trial 2393 finished with value: 0.9495362960186267 and parameters: {'weight_class_0': 0.8115744730038013, 'weight_class_1': 8.7479027900635, 'weight_class_2': 8.067569378520627}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:07,475] Trial 2394 finished with value: 0.9495421504415348 and parameters: {'weight_class_0': 0.8022807717212712, 'weight_class_1': 8.780721408533266, 'weight_class_2': 8.057623546241432}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:07,479] Trial 2396 finished with value: 0.9473462554885614 and parameters: {'weight_class_0': 0.19803545819803697, 'weight_class_1': 7.832961340108956, 'weight_class_2': 6.8744981292314895}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:07,512] Trial 2395 finished with value: 0.94676757876242 and parameters: {'weight_class_0': 0.15812923854343974, 'weight_class_1': 2.734198510873562, 'weight_class_2': 8.084672233741136}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  80%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▋                          | 2403/3000 [01:01<00:19, 30.29it/s]

[I 2026-07-10 16:13:07,529] Trial 2397 finished with value: 0.9464738797649027 and parameters: {'weight_class_0': 0.1656665809111531, 'weight_class_1': 7.732200556343381, 'weight_class_2': 6.975024643641189}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:07,548] Trial 2398 finished with value: 0.9464856928946901 and parameters: {'weight_class_0': 0.1650420924571584, 'weight_class_1': 7.685545822314643, 'weight_class_2': 6.939407284942702}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:07,584] Trial 2399 finished with value: 0.945421195833091 and parameters: {'weight_class_0': 0.1387989979833011, 'weight_class_1': 7.467212481990574, 'weight_class_2': 7.111599968183827}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:07,623] Trial 2400 finished with value: 0.9466419330428456 and parameters: {'weight_class_0': 0.16783803333828917, 'weight_class_1': 7.559974972355504, 'weight_class_2': 6.831387588331096}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:07,689] Trial 2402 finished with value: 0.9458182841751387 and parameters: {'weight_class_0': 0.16375050198709246, 'weight_class_1': 8.759748211045899, 'weight_class_2': 6.795174068202053}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:07,705] Trial 2403 finished with value: 0.9468285515092586 and parameters: {'weight_class_0': 0.17129282436365306, 'weight_class_1': 7.390283020209374, 'weight_class_2': 6.78683785760648}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:07,726] Trial 2401 finished with value: 0.9478879362585672 and parameters: {'weight_class_0': 0.21503172601216586, 'weight_class_1': 7.28844370347422, 'weight_class_2': 6.880606885947818}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████                          | 2410/3000 [01:01<00:19, 29.79it/s]

[I 2026-07-10 16:13:07,741] Trial 2404 finished with value: 0.9485224947594029 and parameters: {'weight_class_0': 0.2732240516856486, 'weight_class_1': 7.575858552823489, 'weight_class_2': 6.810752222478808}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:07,799] Trial 2405 finished with value: 0.9483394354714177 and parameters: {'weight_class_0': 0.25812820068825126, 'weight_class_1': 7.684996011487114, 'weight_class_2': 6.858089832297123}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:07,831] Trial 2406 finished with value: 0.9474656402886551 and parameters: {'weight_class_0': 0.19662831500614103, 'weight_class_1': 7.4631429084012355, 'weight_class_2': 6.796608693126728}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:07,867] Trial 2407 finished with value: 0.9461144345533504 and parameters: {'weight_class_0': 0.1714238148939125, 'weight_class_1': 8.75616933293275, 'weight_class_2': 6.886803001061852}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:07,925] Trial 2408 finished with value: 0.9494013494119452 and parameters: {'weight_class_0': 0.7386613276504922, 'weight_class_1': 7.378314519690626, 'weight_class_2': 6.7432163284614255}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:07,955] Trial 2409 finished with value: 0.9493363632493255 and parameters: {'weight_class_0': 0.7403802612594037, 'weight_class_1': 7.229605561506601, 'weight_class_2': 6.817002416097053}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:07,957] Trial 2410 finished with value: 0.9491217677329365 and parameters: {'weight_class_0': 0.8174069299660084, 'weight_class_1': 7.619341175473859, 'weight_class_2': 6.7293786025784685}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  81%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▍                         | 2418/3000 [01:01<00:18, 30.88it/s]

[I 2026-07-10 16:13:07,975] Trial 2411 finished with value: 0.9494899742035772 and parameters: {'weight_class_0': 0.7354669143318018, 'weight_class_1': 8.74469845139062, 'weight_class_2': 6.5910265910863775}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:08,016] Trial 2412 finished with value: 0.9492362194929774 and parameters: {'weight_class_0': 0.7756499707641714, 'weight_class_1': 7.250603884171879, 'weight_class_2': 6.719053380160345}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:08,072] Trial 2413 finished with value: 0.9495527295421461 and parameters: {'weight_class_0': 0.7421190509800819, 'weight_class_1': 8.17875991253804, 'weight_class_2': 7.091756520817619}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:08,101] Trial 2414 finished with value: 0.9493544551081353 and parameters: {'weight_class_0': 0.7709116670255224, 'weight_class_1': 8.147323989528775, 'weight_class_2': 6.61474050799512}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:08,123] Trial 2415 finished with value: 0.894086615534886 and parameters: {'weight_class_0': 0.7418815785223685, 'weight_class_1': 0.24362091198697744, 'weight_class_2': 7.010959450964009}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:08,134] Trial 2416 finished with value: 0.9495164169836671 and parameters: {'weight_class_0': 0.7419506953769254, 'weight_class_1': 8.079014183871816, 'weight_class_2': 6.978407730094897}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:08,207] Trial 2417 finished with value: 0.9493139756139212 and parameters: {'weight_class_0': 0.7780931828867922, 'weight_class_1': 8.144767679325296, 'weight_class_2': 6.6163306052257616}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:08,210] Trial 2418 finished with value: 0.9494855291782057 and parameters: {'weight_class_0': 0.7599738676208916, 'weight_class_1': 8.1952983003591, 'weight_class_2': 7.04057466014185}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  81%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                         | 2424/3000 [01:01<00:20, 28.71it/s]

[I 2026-07-10 16:13:08,235] Trial 2419 finished with value: 0.9494765860562174 and parameters: {'weight_class_0': 0.7629714510151064, 'weight_class_1': 8.121884740741711, 'weight_class_2': 6.998053107081391}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:08,291] Trial 2420 finished with value: 0.9494664032613463 and parameters: {'weight_class_0': 0.7688232304365501, 'weight_class_1': 8.110495435375697, 'weight_class_2': 7.0068919048653395}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:08,352] Trial 2423 finished with value: 0.9481153904244181 and parameters: {'weight_class_0': 1.1526434288573006, 'weight_class_1': 8.11786135789848, 'weight_class_2': 6.999717131478824}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:08,381] Trial 2422 finished with value: 0.9489809956496363 and parameters: {'weight_class_0': 0.9393507025669346, 'weight_class_1': 8.120201922474088, 'weight_class_2': 7.579133806812318}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:08,401] Trial 2421 finished with value: 0.9489086911305754 and parameters: {'weight_class_0': 0.9164197855181816, 'weight_class_1': 8.192899547428523, 'weight_class_2': 7.016482362240178}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:08,415] Trial 2425 finished with value: 0.9430873186593817 and parameters: {'weight_class_0': 1.1535624988485926, 'weight_class_1': 3.6495503121962884, 'weight_class_2': 7.0279145940951375}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  81%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▉                         | 2431/3000 [01:01<00:18, 30.67it/s]

[I 2026-07-10 16:13:08,475] Trial 2424 finished with value: 0.9494477649943253 and parameters: {'weight_class_0': 0.41039982918524387, 'weight_class_1': 8.121388147911903, 'weight_class_2': 6.055861059433605}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:08,504] Trial 2428 finished with value: 0.949286965002302 and parameters: {'weight_class_0': 0.43836660082041645, 'weight_class_1': 8.490928638792138, 'weight_class_2': 7.621376140950642}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:08,530] Trial 2427 finished with value: 0.9494032656239728 and parameters: {'weight_class_0': 0.4701138979295221, 'weight_class_1': 8.57448041934081, 'weight_class_2': 7.60664635784045}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:08,533] Trial 2426 finished with value: 0.94934797614594 and parameters: {'weight_class_0': 0.4515197373338149, 'weight_class_1': 8.549528575630806, 'weight_class_2': 7.57987455620565}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:08,599] Trial 2429 finished with value: 0.9492383867734947 and parameters: {'weight_class_0': 0.4226842343053485, 'weight_class_1': 8.464105306356757, 'weight_class_2': 7.6093671525814806}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:08,633] Trial 2430 finished with value: 0.9383798588583984 and parameters: {'weight_class_0': 0.4099900571180438, 'weight_class_1': 0.9181154455138731, 'weight_class_2': 7.628723743679347}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:08,637] Trial 2431 finished with value: 0.9195949590913114 and parameters: {'weight_class_0': 1.1027936247349488, 'weight_class_1': 8.487285147590839, 'weight_class_2': 1.4217306474840399}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  81%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▎                        | 2438/3000 [01:02<00:19, 29.06it/s]

[I 2026-07-10 16:13:08,661] Trial 2432 finished with value: 0.9494224203225535 and parameters: {'weight_class_0': 0.47316954254340515, 'weight_class_1': 8.527051388861505, 'weight_class_2': 7.593267983351586}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:08,718] Trial 2433 finished with value: 0.9489860893706328 and parameters: {'weight_class_0': 0.3811675810125425, 'weight_class_1': 8.56688414119975, 'weight_class_2': 7.529707312145722}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:08,790] Trial 2435 finished with value: 0.9493366604756209 and parameters: {'weight_class_0': 0.4362503726643341, 'weight_class_1': 8.53777334906755, 'weight_class_2': 7.313905877539457}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:08,812] Trial 2436 finished with value: 0.9491193048998564 and parameters: {'weight_class_0': 0.3919442175626883, 'weight_class_1': 8.537275653506637, 'weight_class_2': 7.318109323292043}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:08,819] Trial 2434 finished with value: 0.8925989950734284 and parameters: {'weight_class_0': 6.215166057276667, 'weight_class_1': 8.543060868289396, 'weight_class_2': 7.282717338362379}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:08,857] Trial 2437 finished with value: 0.9492479586190438 and parameters: {'weight_class_0': 0.4193095348557924, 'weight_class_1': 8.522702822750833, 'weight_class_2': 7.300263322712544}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:08,876] Trial 2439 finished with value: 0.9489569073449532 and parameters: {'weight_class_0': 0.41520666810796336, 'weight_class_1': 8.906442027601274, 'weight_class_2': 2.94455881553315}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▌                        | 2445/3000 [01:02<00:17, 30.95it/s]

[I 2026-07-10 16:13:08,919] Trial 2438 finished with value: 0.9488388136958418 and parameters: {'weight_class_0': 1.0087810320356645, 'weight_class_1': 8.940776418031923, 'weight_class_2': 7.311492992424999}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:08,927] Trial 2440 finished with value: 0.9492945836404791 and parameters: {'weight_class_0': 0.44141748491353683, 'weight_class_1': 9.045727149067138, 'weight_class_2': 7.332947461104967}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:08,959] Trial 2441 finished with value: 0.9488676683738207 and parameters: {'weight_class_0': 0.9878463344212961, 'weight_class_1': 9.137875157596394, 'weight_class_2': 7.337343991681106}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:08,977] Trial 2442 finished with value: 0.948872536713513 and parameters: {'weight_class_0': 0.9913925396166414, 'weight_class_1': 9.087185817146766, 'weight_class_2': 7.304931534287497}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:09,028] Trial 2443 finished with value: 0.8936093324736755 and parameters: {'weight_class_0': 6.328073236944277, 'weight_class_1': 9.0567992461048, 'weight_class_2': 7.33120442649362}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:09,069] Trial 2445 finished with value: 0.9488718248778275 and parameters: {'weight_class_0': 0.9908635389715825, 'weight_class_1': 9.08061644185452, 'weight_class_2': 7.288592350741841}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:09,085] Trial 2444 finished with value: 0.9497421035603093 and parameters: {'weight_class_0': 0.6127785483593652, 'weight_class_1': 8.978528194962571, 'weight_class_2': 7.273005993517992}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▊                        | 2451/3000 [01:02<00:18, 29.75it/s]

[I 2026-07-10 16:13:09,137] Trial 2446 finished with value: 0.9489009964143943 and parameters: {'weight_class_0': 0.9721306478447039, 'weight_class_1': 8.989836302247536, 'weight_class_2': 7.310010274418996}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:09,170] Trial 2447 finished with value: 0.9489555798650159 and parameters: {'weight_class_0': 0.9605898915551563, 'weight_class_1': 8.988132933890412, 'weight_class_2': 7.4010006938676565}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:09,198] Trial 2448 finished with value: 0.948871456880851 and parameters: {'weight_class_0': 1.0035302774683754, 'weight_class_1': 9.108514167214897, 'weight_class_2': 7.302211959183627}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:09,283] Trial 2449 finished with value: 0.9489768363981135 and parameters: {'weight_class_0': 0.9701124261890798, 'weight_class_1': 9.435780616018722, 'weight_class_2': 7.306084706532688}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:09,296] Trial 2450 finished with value: 0.9497416363757729 and parameters: {'weight_class_0': 0.6197615952171156, 'weight_class_1': 8.722779665169442, 'weight_class_2': 7.500734872232599}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:09,301] Trial 2452 finished with value: 0.9496036355161852 and parameters: {'weight_class_0': 0.6267756376347448, 'weight_class_1': 9.435463390602484, 'weight_class_2': 8.365243850014044}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  82%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                       | 2458/3000 [01:02<00:18, 29.20it/s]

[I 2026-07-10 16:13:09,314] Trial 2451 finished with value: 0.9495790134535289 and parameters: {'weight_class_0': 0.6024121921446393, 'weight_class_1': 9.835208334063626, 'weight_class_2': 8.316911915728964}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:09,367] Trial 2453 finished with value: 0.8800838078121139 and parameters: {'weight_class_0': 7.984072833699166, 'weight_class_1': 9.452619908503843, 'weight_class_2': 7.51499108643523}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:09,429] Trial 2454 finished with value: 0.9496017891757327 and parameters: {'weight_class_0': 0.640968886432338, 'weight_class_1': 7.8961741698409735, 'weight_class_2': 8.266854178167357}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:09,452] Trial 2456 finished with value: 0.9497305306638105 and parameters: {'weight_class_0': 0.6236587793259232, 'weight_class_1': 8.718340226547035, 'weight_class_2': 7.653295879529251}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:09,459] Trial 2455 finished with value: 0.9496369662758154 and parameters: {'weight_class_0': 0.5700050470663572, 'weight_class_1': 8.769390338536605, 'weight_class_2': 7.656815211600208}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:09,476] Trial 2457 finished with value: 0.9496274397603807 and parameters: {'weight_class_0': 0.6358753777864733, 'weight_class_1': 9.434650201334014, 'weight_class_2': 8.408863375189384}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:09,542] Trial 2458 finished with value: 0.9497345969187753 and parameters: {'weight_class_0': 0.6295724714577359, 'weight_class_1': 8.314678784156223, 'weight_class_2': 7.592871760963871}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  82%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                       | 2465/3000 [01:03<00:16, 31.59it/s]

[I 2026-07-10 16:13:09,570] Trial 2459 finished with value: 0.9495907571644193 and parameters: {'weight_class_0': 0.6196557980667696, 'weight_class_1': 7.839228222211105, 'weight_class_2': 8.261037773105308}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:09,581] Trial 2460 finished with value: 0.9495593491316358 and parameters: {'weight_class_0': 0.6176795492175479, 'weight_class_1': 7.838607872598578, 'weight_class_2': 8.403711668446043}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:09,642] Trial 2461 finished with value: 0.9496467206266422 and parameters: {'weight_class_0': 0.6264382043576988, 'weight_class_1': 9.827445365266112, 'weight_class_2': 7.917308356115319}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:09,683] Trial 2463 finished with value: 0.9496840854285963 and parameters: {'weight_class_0': 0.6192990070545756, 'weight_class_1': 8.268266813507875, 'weight_class_2': 7.666795552627864}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:09,695] Trial 2462 finished with value: 0.9496966485872664 and parameters: {'weight_class_0': 0.644966802708435, 'weight_class_1': 7.8463645683558045, 'weight_class_2': 7.909551088143097}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:09,706] Trial 2464 finished with value: 0.9497166869894889 and parameters: {'weight_class_0': 0.6429120352155273, 'weight_class_1': 7.870377386597873, 'weight_class_2': 7.848568447653788}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:09,733] Trial 2465 finished with value: 0.8839667707601385 and parameters: {'weight_class_0': 6.588414956513549, 'weight_class_1': 6.55222636187484, 'weight_class_2': 7.909837962838367}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:13:09,809] Trial 2466 finished with value: 0.948275930903137 and parameters: {'weight_class_0': 1.1621249339690398, 'weight_class_1': 7.895979446033261, 'weight_class_2': 7.892553876207831}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:09,834] Trial 2467 finished with value: 0.9483104649440536 and parameters: {'weight_class_0': 1.1721487138193316, 'weight_class_1': 8.326540313468513, 'weight_class_2': 7.897834718291499}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:09,867] Trial 2469 finished with value: 0.8731923460969533 and parameters: {'weight_class_0': 8.489377140651138, 'weight_class_1': 7.903445630351486, 'weight_class_2': 7.979056916608146}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:09,891] Trial 2468 finished with value: 0.948168087807154 and parameters: {'weight_class_0': 1.1928261496666064, 'weight_class_1': 8.278899316056622, 'weight_class_2': 7.883087882468379}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:09,963] Trial 2470 finished with value: 0.9484756406149583 and parameters: {'weight_class_0': 0.30676838219558356, 'weight_class_1': 8.330508712355547, 'weight_class_2': 7.9501798372051935}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:09,973] Trial 2472 finished with value: 0.9480232381940419 and parameters: {'weight_class_0': 1.198520861262051, 'weight_class_1': 8.32742987749633, 'weight_class_2': 7.076256834019581}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:13:09,984] Trial 2471 finished with value: 0.9475315493272798 and parameters: {'weight_class_0': 1.1872672100344472, 'weight_class_1': 6.447579398141489, 'weight_class_2': 7.971336603988501}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:10,038] Trial 2473 finished with value: 0.9485588189754565 and parameters: {'weight_class_0': 0.3060166902941771, 'weight_class_1': 8.73898493159695, 'weight_class_2': 7.054024940410582}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:10,081] Trial 2474 finished with value: 0.7872410795305685 and parameters: {'weight_class_0': 0.024372323101630733, 'weight_class_1': 8.274782410621123, 'weight_class_2': 7.058722290851737}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:10,097] Trial 2476 finished with value: 0.724715375857115 and parameters: {'weight_class_0': 0.01749778464213647, 'weight_class_1': 8.320458023163225, 'weight_class_2': 7.0597146606138645}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:10,102] Trial 2475 finished with value: 0.9475161486200704 and parameters: {'weight_class_0': 1.208571317625009, 'weight_class_1': 6.858433363114413, 'weight_class_2': 7.130513736923926}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:10,109] Trial 2477 finished with value: 0.9481264900197162 and parameters: {'weight_class_0': 1.1639792546097334, 'weight_class_1': 8.345957423032116, 'weight_class_2': 7.047417935767146}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:10,187] Trial 2479 finished with value: 0.9484932111233965 and parameters: {'weight_class_0': 0.28469481971042593, 'weight_class_1': 8.287551576271518, 'weight_class_2': 7.120798489530016}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:13:10,225] Trial 2478 finished with value: 0.9487112377253896 and parameters: {'weight_class_0': 0.31677533012426484, 'weight_class_1': 8.32734881152056, 'weight_class_2': 7.066254332957073}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:10,248] Trial 2480 finished with value: 0.9487881653239274 and parameters: {'weight_class_0': 0.3165814703264323, 'weight_class_1': 6.911191519923193, 'weight_class_2': 7.097402802719551}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:10,311] Trial 2481 finished with value: 0.94844891284722 and parameters: {'weight_class_0': 0.2915758272877621, 'weight_class_1': 8.780145016569955, 'weight_class_2': 7.0588205232019074}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:10,347] Trial 2482 finished with value: 0.9491059061224231 and parameters: {'weight_class_0': 0.8803610932384854, 'weight_class_1': 8.725213281361423, 'weight_class_2': 7.026511065787503}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:10,367] Trial 2483 finished with value: 0.9491828006574871 and parameters: {'weight_class_0': 0.8712757075475355, 'weight_class_1': 8.799330582995339, 'weight_class_2': 7.085025511399021}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:10,386] Trial 2484 finished with value: 0.9493578849268677 and parameters: {'weight_class_0': 0.8696834721053037, 'weight_class_1': 8.736542322337488, 'weight_class_2': 7.474871415807425}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                      | 2491/3000 [01:03<00:15, 31.94it/s]

[I 2026-07-10 16:13:10,401] Trial 2485 finished with value: 0.9493936635314851 and parameters: {'weight_class_0': 0.8450980680669291, 'weight_class_1': 8.753816790920135, 'weight_class_2': 7.4755622436716385}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:10,476] Trial 2486 finished with value: 0.9473236462927478 and parameters: {'weight_class_0': 0.9129356324231225, 'weight_class_1': 8.76733746863154, 'weight_class_2': 4.0739276493619965}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:10,503] Trial 2488 finished with value: 0.9493272549233405 and parameters: {'weight_class_0': 0.8805123665184046, 'weight_class_1': 8.830734984937944, 'weight_class_2': 7.496608494882111}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:10,503] Trial 2487 finished with value: 0.9493961036638008 and parameters: {'weight_class_0': 0.8374372274140294, 'weight_class_1': 8.721977160276325, 'weight_class_2': 7.516809139662719}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:10,561] Trial 2489 finished with value: 0.9493957704624135 and parameters: {'weight_class_0': 0.8572031953473611, 'weight_class_1': 8.739756448421891, 'weight_class_2': 7.514666359112555}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:10,575] Trial 2490 finished with value: 0.9493617305861544 and parameters: {'weight_class_0': 0.8638795953281471, 'weight_class_1': 8.789694561494787, 'weight_class_2': 7.455205922909833}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:10,598] Trial 2491 finished with value: 0.9492684263156774 and parameters: {'weight_class_0': 0.8904926930354385, 'weight_class_1': 8.752148535429075, 'weight_class_2': 7.530866556309669}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  83%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                      | 2498/3000 [01:04<00:17, 28.40it/s]

[I 2026-07-10 16:13:10,658] Trial 2492 finished with value: 0.9492962359565835 and parameters: {'weight_class_0': 0.8853561129261467, 'weight_class_1': 8.788791214426693, 'weight_class_2': 7.492888753869476}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:10,666] Trial 2493 finished with value: 0.9489687511511545 and parameters: {'weight_class_0': 0.9333474519713577, 'weight_class_1': 8.04831674602079, 'weight_class_2': 7.480131648537034}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:10,774] Trial 2495 finished with value: 0.9494332900699477 and parameters: {'weight_class_0': 0.807619669725425, 'weight_class_1': 8.11848114625332, 'weight_class_2': 7.644042025331123}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:10,780] Trial 2494 finished with value: 0.9492371561366083 and parameters: {'weight_class_0': 0.8693954337561398, 'weight_class_1': 8.03951306127013, 'weight_class_2': 7.5538614882987325}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:10,803] Trial 2496 finished with value: 0.9491582528379228 and parameters: {'weight_class_0': 0.8992946561530912, 'weight_class_1': 8.051742919231872, 'weight_class_2': 7.628549631187739}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:10,813] Trial 2497 finished with value: 0.9492884172444832 and parameters: {'weight_class_0': 0.8488181321923487, 'weight_class_1': 8.00719380738172, 'weight_class_2': 7.674304009790351}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:10,857] Trial 2498 finished with value: 0.9494583807075542 and parameters: {'weight_class_0': 0.7981664671791631, 'weight_class_1': 8.090707370718171, 'weight_class_2': 7.638631143381323}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 678. Best value: 0.94976:  84%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                     | 2505/3000 [01:04<00:15, 32.43it/s]

[I 2026-07-10 16:13:10,876] Trial 2500 finished with value: 0.9462255975339492 and parameters: {'weight_class_0': 0.478215751781486, 'weight_class_1': 1.9742100983651105, 'weight_class_2': 7.679423429412237}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:10,895] Trial 2499 finished with value: 0.9494500739320334 and parameters: {'weight_class_0': 0.5110350830168479, 'weight_class_1': 8.064465568579912, 'weight_class_2': 7.688223562557352}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:10,905] Trial 2501 finished with value: 0.949410027299724 and parameters: {'weight_class_0': 0.49030828331492693, 'weight_class_1': 8.019541060633344, 'weight_class_2': 7.748820587384379}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:10,953] Trial 2502 finished with value: 0.9490619492670405 and parameters: {'weight_class_0': 0.44777279059574493, 'weight_class_1': 8.134216579188442, 'weight_class_2': 8.690552669498638}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:10,968] Trial 2503 finished with value: 0.9493198330980532 and parameters: {'weight_class_0': 0.4249106226935425, 'weight_class_1': 8.051362709717386, 'weight_class_2': 7.277524466492799}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:10,993] Trial 2504 finished with value: 0.949229567675885 and parameters: {'weight_class_0': 0.4259698046808984, 'weight_class_1': 8.06100759739835, 'weight_class_2': 7.726615089148418}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:11,025] Trial 2505 finished with value: 0.9493096858801193 and parameters: {'weight_class_0': 0.46179201586442686, 'weight_class_1': 7.616336710621787, 'weight_class_2': 7.697169001962423}. Best is trial 678 with value: 0.9497603692199318.

[I 2026-07-10 16:13:11,143] Trial 2507 finished with value: 0.9494515262823294 and parameters: {'weight_class_0': 0.4844833847327187, 'weight_class_1': 7.622653314098072, 'weight_class_2': 7.2581636193912225}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:11,180] Trial 2508 finished with value: 0.949181302874746 and parameters: {'weight_class_0': 0.4790358749842831, 'weight_class_1': 7.678381587101586, 'weight_class_2': 8.73448231051714}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:11,190] Trial 2506 finished with value: 0.9493340526543047 and parameters: {'weight_class_0': 0.46792383614919425, 'weight_class_1': 7.679127080989055, 'weight_class_2': 7.70103472512638}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:11,239] Trial 2511 finished with value: 0.9495405834295966 and parameters: {'weight_class_0': 0.5174557014579017, 'weight_class_1': 8.540651889077372, 'weight_class_2': 7.207576821843017}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:11,243] Trial 2509 finished with value: 0.9494653655387905 and parameters: {'weight_class_0': 0.4777490233374627, 'weight_class_1': 8.44996081472702, 'weight_class_2': 7.303743241457126}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:11,256] Trial 2510 finished with value: 0.9494568008455072 and parameters: {'weight_class_0': 0.4765824079130354, 'weight_class_1': 8.50531336022467, 'weight_class_2': 7.30096584533706}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:11,293] Trial 2512 finished with value: 0.9497206486931179 and parameters: {'weight_class_0': 0.6477894663289567, 'weight_class_1': 7.655069483901277, 'weight_class_2': 7.260884821076533}. Best is trial 678 with value: 0.9497603692199318.
[I 2026-07-10 16:13:11,300] Trial 2513 finished with value: 0.9497552729830763 and parameters: {'weight_class_0': 0.6495877963115245, 'weight_class_1': 8.487482611771322, 'weight_class_2': 7.295134960791442}. Best is trial 678 with value: 0.9497603692199318.

Best trial: 2514. Best value: 0.949762:  84%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████                     | 2518/3000 [01:04<00:14, 33.59it/s]

[I 2026-07-10 16:13:11,350] Trial 2514 finished with value: 0.9497621740390644 and parameters: {'weight_class_0': 0.6108617569185698, 'weight_class_1': 8.372179852709031, 'weight_class_2': 7.232396670761757}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:11,374] Trial 2515 finished with value: 0.9497087370258624 and parameters: {'weight_class_0': 0.6836295486486419, 'weight_class_1': 8.391845006467792, 'weight_class_2': 7.27295629217387}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:11,392] Trial 2516 finished with value: 0.6790493875360649 and parameters: {'weight_class_0': 0.012325039288309303, 'weight_class_1': 8.45239555410532, 'weight_class_2': 7.288469298545768}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:11,401] Trial 2517 finished with value: 0.949734429304112 and parameters: {'weight_class_0': 0.6797036404560998, 'weight_class_1': 8.469813122819708, 'weight_class_2': 7.3007681918206035}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:11,546] Trial 2519 finished with value: 0.9497537060198774 and parameters: {'weight_class_0': 0.6452169935184173, 'weight_class_1': 8.487055085690951, 'weight_class_2': 7.296875476054747}. Best is trial 2514 with value: 0.9497621740390644.

Best trial: 2514. Best value: 0.949762:  84%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                    | 2526/3000 [01:05<00:15, 30.96it/s]

[I 2026-07-10 16:13:11,547] Trial 2518 finished with value: 0.9460676089850342 and parameters: {'weight_class_0': 0.16766952946475355, 'weight_class_1': 8.50552812422733, 'weight_class_2': 7.265752829312404}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:11,591] Trial 2520 finished with value: 0.9497212797245487 and parameters: {'weight_class_0': 0.6291770835783475, 'weight_class_1': 8.470892470239628, 'weight_class_2': 7.2765467491573546}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:11,598] Trial 2521 finished with value: 0.945469826899091 and parameters: {'weight_class_0': 0.1579962812101916, 'weight_class_1': 8.403618156169955, 'weight_class_2': 8.084637900624832}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:11,621] Trial 2522 finished with value: 0.9479441300314813 and parameters: {'weight_class_0': 0.23904809963923584, 'weight_class_1': 5.859612112819242, 'weight_class_2': 8.075839375506336}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:11,689] Trial 2524 finished with value: 0.9497044147705639 and parameters: {'weight_class_0': 0.6997511075759222, 'weight_class_1': 8.53258964186005, 'weight_class_2': 7.414738641726713}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:11,702] Trial 2523 finished with value: 0.6574352016365604 and parameters: {'weight_class_0': 0.0030472076500455136, 'weight_class_1': 8.54921768273217, 'weight_class_2': 8.10584954631797}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:11,732] Trial 2525 finished with value: 0.9468330346250303 and parameters: {'weight_class_0': 0.18535172861793076, 'weight_class_1': 8.320265593512012, 'weight_class_2': 6.5843628055407395}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:11,742] Trial 2526 finished with value: 0.9480548473523832 and parameters: {'weight_class_0': 0.24246508840674474, 'weight_class_1': 8.266227813106124, 'weight_class_2': 6.835311750429999}. Best is trial 2514 with value: 0.9497621740390644.

Best trial: 2514. Best value: 0.949762:  84%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                    | 2532/3000 [01:05<00:16, 27.90it/s]

[I 2026-07-10 16:13:11,772] Trial 2527 finished with value: 0.9467211605426296 and parameters: {'weight_class_0': 0.18225751535473794, 'weight_class_1': 8.294892565089821, 'weight_class_2': 6.776702119460728}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:11,785] Trial 2528 finished with value: 0.9473814006843931 and parameters: {'weight_class_0': 0.20720919597497744, 'weight_class_1': 8.255383145390486, 'weight_class_2': 6.816688764297426}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:11,807] Trial 2529 finished with value: 0.9467560886431875 and parameters: {'weight_class_0': 0.18298548775585521, 'weight_class_1': 8.284227599932436, 'weight_class_2': 6.7040985115135445}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:11,900] Trial 2530 finished with value: 0.9479575869191871 and parameters: {'weight_class_0': 0.23359261587375701, 'weight_class_1': 8.287240734200637, 'weight_class_2': 6.663485494552349}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:11,983] Trial 2532 finished with value: 0.9483930443936012 and parameters: {'weight_class_0': 0.2672194993840831, 'weight_class_1': 8.20235012612974, 'weight_class_2': 6.617826427058382}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:11,999] Trial 2533 finished with value: 0.9487025237264105 and parameters: {'weight_class_0': 0.3083961701334892, 'weight_class_1': 8.232364862457494, 'weight_class_2': 6.859001241339546}. Best is trial 2514 with value: 0.9497621740390644.

Best trial: 2514. Best value: 0.949762:  85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████                    | 2540/3000 [01:05<00:14, 30.98it/s]

[I 2026-07-10 16:13:12,005] Trial 2531 finished with value: 0.9485108093933033 and parameters: {'weight_class_0': 0.28575447941789994, 'weight_class_1': 8.250324175548666, 'weight_class_2': 6.8587395745579345}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:12,026] Trial 2534 finished with value: 0.944257452665819 and parameters: {'weight_class_0': 1.7713603852714432, 'weight_class_1': 8.23408143125462, 'weight_class_2': 6.909417984553282}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:12,055] Trial 2535 finished with value: 0.9482860140090312 and parameters: {'weight_class_0': 1.0827838162237724, 'weight_class_1': 8.16954407157511, 'weight_class_2': 6.674066922150898}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:12,068] Trial 2536 finished with value: 0.948309979586658 and parameters: {'weight_class_0': 1.0864660636509038, 'weight_class_1': 8.234474824532134, 'weight_class_2': 6.782677081845341}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:12,103] Trial 2537 finished with value: 0.9496047807070132 and parameters: {'weight_class_0': 0.7157213544264175, 'weight_class_1': 8.216181002829495, 'weight_class_2': 7.027744590954542}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:12,182] Trial 2538 finished with value: 0.9483868565530765 and parameters: {'weight_class_0': 1.068933314872924, 'weight_class_1': 7.833210269380915, 'weight_class_2': 6.931152602835451}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:12,189] Trial 2539 finished with value: 0.9481931130040779 and parameters: {'weight_class_0': 1.0967114808687675, 'weight_class_1': 7.8429478788812865, 'weight_class_2': 6.903580196582832}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:12,200] Trial 2540 finished with value: 0.9496053405179463 and parameters: {'weight_class_0': 0.7056746389959255, 'weight_class_1': 7.843805077188804, 'weight_class_2': 6.989521989960389}. Best is trial 2514 with value: 0.9497621740390644.

Best trial: 2514. Best value: 0.949762:  85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                   | 2546/3000 [01:05<00:15, 29.56it/s]

[I 2026-07-10 16:13:12,202] Trial 2541 finished with value: 0.9485175063913699 and parameters: {'weight_class_0': 1.0342607227257445, 'weight_class_1': 7.888279390238478, 'weight_class_2': 6.977190123880946}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:12,255] Trial 2542 finished with value: 0.949680049797979 and parameters: {'weight_class_0': 0.6757322152060586, 'weight_class_1': 7.890629156390739, 'weight_class_2': 7.093467629023024}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:12,359] Trial 2543 finished with value: 0.9496069073783486 and parameters: {'weight_class_0': 0.701100586473412, 'weight_class_1': 7.887316729061968, 'weight_class_2': 7.039718293227699}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:12,379] Trial 2544 finished with value: 0.9483640236453045 and parameters: {'weight_class_0': 1.0692711126666965, 'weight_class_1': 7.8468117797083305, 'weight_class_2': 7.037335770974235}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:12,417] Trial 2545 finished with value: 0.9495738570857096 and parameters: {'weight_class_0': 0.7136709224688609, 'weight_class_1': 7.844071712887734, 'weight_class_2': 7.052695038064233}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:12,443] Trial 2546 finished with value: 0.949599222073643 and parameters: {'weight_class_0': 0.6998064498366545, 'weight_class_1': 7.789920232152566, 'weight_class_2': 7.015866994573074}. Best is trial 2514 with value: 0.9497621740390644.

Best trial: 2514. Best value: 0.949762:  85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                   | 2553/3000 [01:05<00:13, 32.50it/s]

[I 2026-07-10 16:13:12,490] Trial 2547 finished with value: 0.8995058243330444 and parameters: {'weight_class_0': 4.049521827179029, 'weight_class_1': 7.8697160222514295, 'weight_class_2': 4.375183175401697}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:12,494] Trial 2549 finished with value: 0.9496938336009876 and parameters: {'weight_class_0': 0.688446442056438, 'weight_class_1': 8.607135085411757, 'weight_class_2': 7.179756176375104}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:12,506] Trial 2548 finished with value: 0.9495721348029473 and parameters: {'weight_class_0': 0.7178065680832096, 'weight_class_1': 7.884326222457215, 'weight_class_2': 7.071483633756652}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:12,585] Trial 2550 finished with value: 0.9496936856857058 and parameters: {'weight_class_0': 0.6514362049813381, 'weight_class_1': 8.57591149218925, 'weight_class_2': 7.195365207698266}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:12,596] Trial 2552 finished with value: 0.9487786361835875 and parameters: {'weight_class_0': 0.7235272503995609, 'weight_class_1': 8.535122926645979, 'weight_class_2': 4.31928147246539}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:12,650] Trial 2551 finished with value: 0.9495996936760398 and parameters: {'weight_class_0': 0.7328859998093586, 'weight_class_1': 8.588755498630102, 'weight_class_2': 7.162656282787253}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:12,655] Trial 2553 finished with value: 0.9496770150591409 and parameters: {'weight_class_0': 0.6882946402501223, 'weight_class_1': 8.468501720909307, 'weight_class_2': 7.129101171793571}. Best is trial 2514 with value: 0.9497621740390644.

Best trial: 2514. Best value: 0.949762:  85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                   | 2558/3000 [01:06<00:15, 27.85it/s]

[I 2026-07-10 16:13:12,657] Trial 2554 finished with value: 0.9495909796770609 and parameters: {'weight_class_0': 0.7263710513828232, 'weight_class_1': 8.607423487742288, 'weight_class_2': 7.119946825189581}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:12,772] Trial 2555 finished with value: 0.8681712037687995 and parameters: {'weight_class_0': 9.18340962819494, 'weight_class_1': 8.5385372695077, 'weight_class_2': 7.191705321532428}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:12,804] Trial 2556 finished with value: 0.9496857351747843 and parameters: {'weight_class_0': 0.7227083259499135, 'weight_class_1': 8.564102518832259, 'weight_class_2': 7.432596891612829}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:12,832] Trial 2558 finished with value: 0.9495141956584611 and parameters: {'weight_class_0': 0.5031867465295156, 'weight_class_1': 8.511794319947441, 'weight_class_2': 7.196104422615089}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:12,843] Trial 2557 finished with value: 0.9495069356057851 and parameters: {'weight_class_0': 0.505993936147357, 'weight_class_1': 8.581806612629258, 'weight_class_2': 7.415832810731073}. Best is trial 2514 with value: 0.9497621740390644.

Best trial: 2514. Best value: 0.949762:  86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                  | 2566/3000 [01:06<00:13, 31.02it/s]

[I 2026-07-10 16:13:12,922] Trial 2560 finished with value: 0.9492549789113887 and parameters: {'weight_class_0': 0.4199530421606389, 'weight_class_1': 8.587376849299426, 'weight_class_2': 7.380873663830133}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:12,933] Trial 2561 finished with value: 0.9494257468775675 and parameters: {'weight_class_0': 0.4532269941813192, 'weight_class_1': 8.569695753996957, 'weight_class_2': 7.3769775834930815}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:12,935] Trial 2559 finished with value: 0.9491896576429845 and parameters: {'weight_class_0': 0.40771956761244715, 'weight_class_1': 8.430275954923417, 'weight_class_2': 7.381458245304037}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:12,939] Trial 2562 finished with value: 0.9491060289880445 and parameters: {'weight_class_0': 0.39144430795420515, 'weight_class_1': 8.43658077776134, 'weight_class_2': 7.386477460033068}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:12,947] Trial 2563 finished with value: 0.9493130055371211 and parameters: {'weight_class_0': 0.4366960834578433, 'weight_class_1': 8.606046174798788, 'weight_class_2': 7.420224033169917}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:13,002] Trial 2564 finished with value: 0.9492737585788724 and parameters: {'weight_class_0': 0.42935120118897957, 'weight_class_1': 8.091572760324254, 'weight_class_2': 7.421581708955097}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:13,044] Trial 2566 finished with value: 0.9492887750206429 and parameters: {'weight_class_0': 0.43419649574788105, 'weight_class_1': 8.074388268235507, 'weight_class_2': 7.413920038413567}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:13,071] Trial 2565 finished with value: 0.9492803882091835 and parameters: {'weight_class_0': 0.42282639099959907, 'weight_class_1': 8.070870444609449, 'weight_class_2': 7.416534253194413}. Best is trial 2514 with value: 0.9497621740390644.

Best trial: 2514. Best value: 0.949762:  86%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                  | 2573/3000 [01:06<00:14, 29.57it/s]

[I 2026-07-10 16:13:13,140] Trial 2568 finished with value: 0.9489773892009898 and parameters: {'weight_class_0': 0.36770989026359474, 'weight_class_1': 8.064019059856825, 'weight_class_2': 7.358648783924285}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:13,171] Trial 2567 finished with value: 0.9492697921900183 and parameters: {'weight_class_0': 0.4247872484823877, 'weight_class_1': 8.030010758633999, 'weight_class_2': 7.409823467924996}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:13,216] Trial 2569 finished with value: 0.9489097136314513 and parameters: {'weight_class_0': 0.3584629555234387, 'weight_class_1': 8.11434664650606, 'weight_class_2': 7.432539635346648}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:13,273] Trial 2570 finished with value: 0.9493873422377489 and parameters: {'weight_class_0': 0.40698232529381617, 'weight_class_1': 8.073679599431397, 'weight_class_2': 6.39761563923489}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:13,287] Trial 2572 finished with value: 0.9489271918242782 and parameters: {'weight_class_0': 0.9544810970240204, 'weight_class_1': 8.146124888818802, 'weight_class_2': 7.504653729780703}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:13,308] Trial 2573 finished with value: 0.949044090853552 and parameters: {'weight_class_0': 0.9119177019592712, 'weight_class_1': 8.095128042514444, 'weight_class_2': 7.488610785973148}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:13,315] Trial 2571 finished with value: 0.9489461354414531 and parameters: {'weight_class_0': 0.9465597027629407, 'weight_class_1': 8.059952012393106, 'weight_class_2': 7.5153308068143945}. Best is trial 2514 with value: 0.9497621740390644.

[I 2026-07-10 16:13:13,361] Trial 2574 finished with value: 0.9489205048361172 and parameters: {'weight_class_0': 0.9472471147647078, 'weight_class_1': 8.052965611996095, 'weight_class_2': 7.45911455423541}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:13,371] Trial 2575 finished with value: 0.9487877410043156 and parameters: {'weight_class_0': 0.9115076391358342, 'weight_class_1': 8.09021223784957, 'weight_class_2': 6.355245060824296}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:13,475] Trial 2577 finished with value: 0.9489433089621677 and parameters: {'weight_class_0': 0.9569482758830816, 'weight_class_1': 8.315338987384724, 'weight_class_2': 7.569256357456662}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:13,482] Trial 2576 finished with value: 0.9486576277361438 and parameters: {'weight_class_0': 0.9653861951532843, 'weight_class_1': 8.288548221214922, 'weight_class_2': 6.4469156880487315}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:13,511] Trial 2578 finished with value: 0.9490682311209881 and parameters: {'weight_class_0': 0.9256538389824949, 'weight_class_1': 8.328074756200765, 'weight_class_2': 7.532236019790555}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:13,549] Trial 2580 finished with value: 0.9489261224233445 and parameters: {'weight_class_0': 0.973239306156876, 'weight_class_1': 8.340740386163432, 'weight_class_2': 7.5710918255072945}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:13,561] Trial 2579 finished with value: 0.9490015254974594 and parameters: {'weight_class_0': 0.946193463675232, 'weight_class_1': 8.291694722278244, 'weight_class_2': 7.547087008168173}. Best is trial 2514 with value: 0.9497621740390644.

Best trial: 2514. Best value: 0.949762:  86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████                  | 2586/3000 [01:07<00:13, 30.53it/s]

[I 2026-07-10 16:13:13,604] Trial 2581 finished with value: 0.9492674208622156 and parameters: {'weight_class_0': 0.8797938156617245, 'weight_class_1': 8.315788668765968, 'weight_class_2': 7.566177900939541}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:13,631] Trial 2583 finished with value: 0.9490367548256687 and parameters: {'weight_class_0': 0.9014808569554063, 'weight_class_1': 8.298250993486318, 'weight_class_2': 7.197051067986252}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:13,657] Trial 2582 finished with value: 0.9489058212255729 and parameters: {'weight_class_0': 0.9477895710529971, 'weight_class_1': 8.317567935717909, 'weight_class_2': 7.219262581815676}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:13,710] Trial 2584 finished with value: 0.9481541701981304 and parameters: {'weight_class_0': 1.1687269552076045, 'weight_class_1': 8.337564086277169, 'weight_class_2': 7.152375060862341}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:13,738] Trial 2585 finished with value: 0.9481820387928935 and parameters: {'weight_class_0': 1.1684934835463396, 'weight_class_1': 8.36595352472916, 'weight_class_2': 7.206728217589759}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:13,761] Trial 2586 finished with value: 0.9479844705508617 and parameters: {'weight_class_0': 1.2225228797906187, 'weight_class_1': 8.347075481876894, 'weight_class_2': 7.188271093195978}. Best is trial 2514 with value: 0.9497621740390644.

[I 2026-07-10 16:13:13,808] Trial 2587 finished with value: 0.9496973444218542 and parameters: {'weight_class_0': 0.6231677435229207, 'weight_class_1': 8.35257334846171, 'weight_class_2': 7.205756948894572}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:13,888] Trial 2588 finished with value: 0.948228026802342 and parameters: {'weight_class_0': 1.2034892469295444, 'weight_class_1': 8.910104387408378, 'weight_class_2': 7.169324061757949}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:13,904] Trial 2589 finished with value: 0.9496767507293558 and parameters: {'weight_class_0': 0.6460760341847991, 'weight_class_1': 8.923930930687234, 'weight_class_2': 7.190791910363323}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:13,911] Trial 2590 finished with value: 0.946268878709854 and parameters: {'weight_class_0': 1.5632930557706133, 'weight_class_1': 8.89886761958511, 'weight_class_2': 7.194490690012838}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:13,926] Trial 2591 finished with value: 0.9496860831229639 and parameters: {'weight_class_0': 0.6764801459177721, 'weight_class_1': 8.938364200400951, 'weight_class_2': 7.166956073940878}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:13,984] Trial 2592 finished with value: 0.9475658112070495 and parameters: {'weight_class_0': 1.333792902616218, 'weight_class_1': 8.85735104338749, 'weight_class_2': 7.20795133428804}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:14,004] Trial 2593 finished with value: 0.9482499957468794 and parameters: {'weight_class_0': 1.2013925729141484, 'weight_class_1': 8.789529390948914, 'weight_class_2': 7.247365270872007}. Best is trial 2514 with value: 0.9497621740390644.

Best trial: 2514. Best value: 0.949762:  87%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                 | 2599/3000 [01:07<00:12, 31.96it/s]

[I 2026-07-10 16:13:14,010] Trial 2594 finished with value: 0.9353169724616496 and parameters: {'weight_class_0': 1.1873389601584352, 'weight_class_1': 2.3251012990855173, 'weight_class_2': 7.220813255553183}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:14,041] Trial 2595 finished with value: 0.9478149180659861 and parameters: {'weight_class_0': 1.2145337217536132, 'weight_class_1': 7.563561130182942, 'weight_class_2': 7.151026317237769}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:14,099] Trial 2597 finished with value: 0.9495692620273521 and parameters: {'weight_class_0': 0.5567036294311745, 'weight_class_1': 8.897115055455677, 'weight_class_2': 7.737244156180627}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:14,104] Trial 2596 finished with value: 0.6578008939735601 and parameters: {'weight_class_0': 0.004859642654575058, 'weight_class_1': 7.511912708787872, 'weight_class_2': 6.931191127410406}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:14,162] Trial 2598 finished with value: 0.9465395555628682 and parameters: {'weight_class_0': 1.5922281012190673, 'weight_class_1': 8.929563686698206, 'weight_class_2': 7.785449393716206}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:14,181] Trial 2599 finished with value: 0.9460125973905177 and parameters: {'weight_class_0': 1.5808974684110821, 'weight_class_1': 8.906561798815009, 'weight_class_2': 6.944796728193766}. Best is trial 2514 with value: 0.9497621740390644.

Best trial: 2514. Best value: 0.949762:  87%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                 | 2606/3000 [01:07<00:13, 29.51it/s]

[I 2026-07-10 16:13:14,275] Trial 2600 finished with value: 0.6598399963818968 and parameters: {'weight_class_0': 0.007319680184574184, 'weight_class_1': 8.689931553904245, 'weight_class_2': 6.8877592859181505}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:14,297] Trial 2601 finished with value: 0.9496123026918393 and parameters: {'weight_class_0': 0.5817062840164554, 'weight_class_1': 8.696071066787498, 'weight_class_2': 7.687393323110563}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:14,313] Trial 2602 finished with value: 0.949701901472328 and parameters: {'weight_class_0': 0.6346749904805918, 'weight_class_1': 7.537043251651972, 'weight_class_2': 7.779777990957165}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:14,334] Trial 2603 finished with value: 0.6890804061735482 and parameters: {'weight_class_0': 0.013508726828576179, 'weight_class_1': 7.630993257375942, 'weight_class_2': 7.785253127651285}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:14,387] Trial 2604 finished with value: 0.6573585010872145 and parameters: {'weight_class_0': 0.00017512070047709383, 'weight_class_1': 7.647026068979807, 'weight_class_2': 7.7583705585444696}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:14,440] Trial 2606 finished with value: 0.6598732018579908 and parameters: {'weight_class_0': 0.008086875383288561, 'weight_class_1': 9.188990000065491, 'weight_class_2': 7.770675272908537}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:14,460] Trial 2605 finished with value: 0.9495946921886036 and parameters: {'weight_class_0': 0.5594819258153593, 'weight_class_1': 8.678597463759386, 'weight_class_2': 7.724419706312714}. Best is trial 2514 with value: 0.9497621740390644.

Best trial: 2514. Best value: 0.949762:  87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                | 2612/3000 [01:07<00:12, 30.36it/s]

[I 2026-07-10 16:13:14,472] Trial 2608 finished with value: 0.949675789783635 and parameters: {'weight_class_0': 0.6026151880553393, 'weight_class_1': 9.181700373376051, 'weight_class_2': 7.741235657899656}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:14,493] Trial 2607 finished with value: 0.9495419090364573 and parameters: {'weight_class_0': 0.5561497535210971, 'weight_class_1': 9.223206666016853, 'weight_class_2': 7.732300514902829}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:14,545] Trial 2610 finished with value: 0.9496191511162282 and parameters: {'weight_class_0': 0.5830386319616373, 'weight_class_1': 8.679267770485291, 'weight_class_2': 7.729542683806057}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:14,547] Trial 2611 finished with value: 0.9495167096970191 and parameters: {'weight_class_0': 0.5438680470746816, 'weight_class_1': 9.216545528925986, 'weight_class_2': 7.738861546373554}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:14,551] Trial 2609 finished with value: 0.9496248302735723 and parameters: {'weight_class_0': 0.579793189325628, 'weight_class_1': 9.1639768653004, 'weight_class_2': 7.723911103975666}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:14,660] Trial 2612 finished with value: 0.9496422219827304 and parameters: {'weight_class_0': 0.5958913739960786, 'weight_class_1': 9.248015186148123, 'weight_class_2': 7.70988723865519}. Best is trial 2514 with value: 0.9497621740390644.

Best trial: 2514. Best value: 0.949762:  87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                | 2619/3000 [01:08<00:12, 30.81it/s]

[I 2026-07-10 16:13:14,716] Trial 2614 finished with value: 0.9177905165629797 and parameters: {'weight_class_0': 0.7984610872330672, 'weight_class_1': 9.1676038504441, 'weight_class_2': 0.9668829464896369}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:14,722] Trial 2615 finished with value: 0.949653032275316 and parameters: {'weight_class_0': 0.5646007489183947, 'weight_class_1': 8.657897079740147, 'weight_class_2': 7.51640182789068}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:14,723] Trial 2613 finished with value: 0.9483022555520964 and parameters: {'weight_class_0': 0.2849030355892294, 'weight_class_1': 8.673637597178125, 'weight_class_2': 7.616530414940103}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:14,755] Trial 2616 finished with value: 0.9480868543067532 and parameters: {'weight_class_0': 0.27343796178513186, 'weight_class_1': 9.193037747700403, 'weight_class_2': 7.568574231193081}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:14,834] Trial 2618 finished with value: 0.9485730831784186 and parameters: {'weight_class_0': 0.29335308061447046, 'weight_class_1': 5.367723075433961, 'weight_class_2': 7.412292831777412}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:14,837] Trial 2617 finished with value: 0.948304389360349 and parameters: {'weight_class_0': 0.2784457488211454, 'weight_class_1': 8.625676289662067, 'weight_class_2': 7.435462737605873}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:14,866] Trial 2619 finished with value: 0.948399347514944 and parameters: {'weight_class_0': 0.2830147434132034, 'weight_class_1': 7.966960778085664, 'weight_class_2': 7.407237282237576}. Best is trial 2514 with value: 0.9497621740390644.

Best trial: 2514. Best value: 0.949762:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                | 2625/3000 [01:08<00:11, 31.39it/s]

[I 2026-07-10 16:13:14,910] Trial 2620 finished with value: 0.9493684047936916 and parameters: {'weight_class_0': 0.8076038568163356, 'weight_class_1': 7.970362194613296, 'weight_class_2': 7.5089614475571365}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:14,918] Trial 2622 finished with value: 0.9485419463705712 and parameters: {'weight_class_0': 0.3041776079716284, 'weight_class_1': 8.523667678759992, 'weight_class_2': 7.426443920257007}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:14,925] Trial 2621 finished with value: 0.9494351148350808 and parameters: {'weight_class_0': 0.7834419346984298, 'weight_class_1': 7.946734074085457, 'weight_class_2': 7.403799723034174}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:15,020] Trial 2623 finished with value: 0.9484332381883042 and parameters: {'weight_class_0': 0.28721595416987533, 'weight_class_1': 7.944316712555971, 'weight_class_2': 7.46219652306246}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:15,029] Trial 2624 finished with value: 0.9486008314186279 and parameters: {'weight_class_0': 0.3035253661245619, 'weight_class_1': 7.974170879564013, 'weight_class_2': 7.403872749050493}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:15,118] Trial 2625 finished with value: 0.9495254994525805 and parameters: {'weight_class_0': 0.7432940999104839, 'weight_class_1': 7.917672850818642, 'weight_class_2': 7.364231953085152}. Best is trial 2514 with value: 0.9497621740390644.

Best trial: 2514. Best value: 0.949762:  88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████                | 2633/3000 [01:08<00:11, 31.47it/s]

[I 2026-07-10 16:13:15,137] Trial 2626 finished with value: 0.9494017125181036 and parameters: {'weight_class_0': 0.8294492723449959, 'weight_class_1': 8.450999793373578, 'weight_class_2': 7.370949227512482}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:15,140] Trial 2627 finished with value: 0.9493983196667221 and parameters: {'weight_class_0': 0.7979075882483463, 'weight_class_1': 7.969112086319077, 'weight_class_2': 7.35936868942846}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:15,154] Trial 2628 finished with value: 0.9493840498562264 and parameters: {'weight_class_0': 0.8044158332582653, 'weight_class_1': 7.978181780394966, 'weight_class_2': 7.368224522597867}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:15,226] Trial 2630 finished with value: 0.9493469025607326 and parameters: {'weight_class_0': 0.8076371199777869, 'weight_class_1': 8.422871856131277, 'weight_class_2': 6.976126295821184}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:15,237] Trial 2629 finished with value: 0.9493688185652808 and parameters: {'weight_class_0': 0.8013110535235236, 'weight_class_1': 8.461208710727732, 'weight_class_2': 7.0207067784531585}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:15,263] Trial 2631 finished with value: 0.9492847076088512 and parameters: {'weight_class_0': 0.7962910364068628, 'weight_class_1': 8.190985858438344, 'weight_class_2': 6.733543829441031}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:15,306] Trial 2633 finished with value: 0.9493688532580734 and parameters: {'weight_class_0': 0.7960942706873382, 'weight_class_1': 8.439342734114952, 'weight_class_2': 7.00439075171878}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:15,320] Trial 2632 finished with value: 0.9493705652119041 and parameters: {'weight_class_0': 0.8058628853575089, 'weight_class_1': 8.172169347650783, 'weight_class_2': 6.9979918208977505}. Best is trial 2514 with value: 0.9497621740390644.

Best trial: 2514. Best value: 0.949762:  88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎               | 2638/3000 [01:08<00:11, 31.73it/s]

[I 2026-07-10 16:13:15,348] Trial 2634 finished with value: 0.9494094820579834 and parameters: {'weight_class_0': 0.7687630964213561, 'weight_class_1': 8.174587388901198, 'weight_class_2': 6.834438894422206}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:15,387] Trial 2636 finished with value: 0.9493971819004557 and parameters: {'weight_class_0': 0.7871241759369614, 'weight_class_1': 8.215156374898756, 'weight_class_2': 7.024154626666943}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:15,388] Trial 2635 finished with value: 0.949498469984233 and parameters: {'weight_class_0': 0.7390382028780557, 'weight_class_1': 8.43802131571905, 'weight_class_2': 6.871565558703477}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:15,524] Trial 2638 finished with value: 0.9493981742031327 and parameters: {'weight_class_0': 0.7803225821201869, 'weight_class_1': 8.196031724113976, 'weight_class_2': 6.903088234105782}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:15,547] Trial 2637 finished with value: 0.9424787722722888 and parameters: {'weight_class_0': 2.010813867239351, 'weight_class_1': 8.23393110326537, 'weight_class_2': 7.119154765660729}. Best is trial 2514 with value: 0.9497621740390644.

Best trial: 2514. Best value: 0.949762:  88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋               | 2646/3000 [01:09<00:11, 30.87it/s]

[I 2026-07-10 16:13:15,568] Trial 2639 finished with value: 0.9493967278667044 and parameters: {'weight_class_0': 0.7745575110318526, 'weight_class_1': 8.258605940402873, 'weight_class_2': 6.945014520514983}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:15,604] Trial 2641 finished with value: 0.9469831814032093 and parameters: {'weight_class_0': 0.5545358823813626, 'weight_class_1': 8.195620687423592, 'weight_class_2': 2.2866622197138797}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:15,622] Trial 2640 finished with value: 0.9496650564865096 and parameters: {'weight_class_0': 0.5329305008732226, 'weight_class_1': 8.199799592745086, 'weight_class_2': 6.926560804666547}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:15,648] Trial 2642 finished with value: 0.9497064365411481 and parameters: {'weight_class_0': 0.5597206821122208, 'weight_class_1': 8.274556769880592, 'weight_class_2': 6.894594746629572}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:15,675] Trial 2643 finished with value: 0.9496590179623166 and parameters: {'weight_class_0': 0.530021041796256, 'weight_class_1': 8.184626588477492, 'weight_class_2': 6.907488655564483}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:15,692] Trial 2644 finished with value: 0.9496151345064413 and parameters: {'weight_class_0': 0.5125419954364869, 'weight_class_1': 8.199101306386307, 'weight_class_2': 6.760448396284346}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:15,710] Trial 2645 finished with value: 0.9493897841383533 and parameters: {'weight_class_0': 0.5153693082911248, 'weight_class_1': 7.745544685490309, 'weight_class_2': 7.95418380766292}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:15,725] Trial 2646 finished with value: 0.9496337848475417 and parameters: {'weight_class_0': 0.49657694544309183, 'weight_class_1': 8.668140065554843, 'weight_class_2': 6.56879425241144}. Best is trial 2514 with value: 0.9497621740390644.

Best trial: 2514. Best value: 0.949762:  88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉               | 2652/3000 [01:09<00:11, 31.04it/s]

[I 2026-07-10 16:13:15,764] Trial 2647 finished with value: 0.9493841075972691 and parameters: {'weight_class_0': 0.5150461442644008, 'weight_class_1': 7.69844663402789, 'weight_class_2': 7.9960889091592495}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:15,773] Trial 2648 finished with value: 0.9492786832561616 and parameters: {'weight_class_0': 0.4580664032231023, 'weight_class_1': 7.748338907363268, 'weight_class_2': 7.965717356801852}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:15,892] Trial 2649 finished with value: 0.9494170678464594 and parameters: {'weight_class_0': 0.5440965362237689, 'weight_class_1': 7.7290055710124035, 'weight_class_2': 8.060069380468823}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:15,926] Trial 2651 finished with value: 0.948605969330735 and parameters: {'weight_class_0': 1.0536756640758052, 'weight_class_1': 7.6974222592425905, 'weight_class_2': 7.897578490796266}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:15,955] Trial 2650 finished with value: 0.9493107127727921 and parameters: {'weight_class_0': 0.4629693847416715, 'weight_class_1': 7.755664330329236, 'weight_class_2': 7.940707157726172}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:15,978] Trial 2652 finished with value: 0.9486915509589945 and parameters: {'weight_class_0': 1.0960082190477543, 'weight_class_1': 8.718101218036564, 'weight_class_2': 7.605231253661993}. Best is trial 2514 with value: 0.9497621740390644.

Best trial: 2514. Best value: 0.949762:  89%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏              | 2659/3000 [01:09<00:11, 30.08it/s]

[I 2026-07-10 16:13:16,014] Trial 2653 finished with value: 0.9483873341978004 and parameters: {'weight_class_0': 1.0978740975906303, 'weight_class_1': 7.718214912026422, 'weight_class_2': 7.596328963649421}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:16,070] Trial 2654 finished with value: 0.9488109381697547 and parameters: {'weight_class_0': 1.0669842784692127, 'weight_class_1': 8.697544096232429, 'weight_class_2': 7.588065655243481}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:16,103] Trial 2655 finished with value: 0.9485823030145912 and parameters: {'weight_class_0': 1.1044766528121257, 'weight_class_1': 8.45625010615856, 'weight_class_2': 7.601479475581831}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:16,105] Trial 2656 finished with value: 0.9487679358012614 and parameters: {'weight_class_0': 1.052015893046286, 'weight_class_1': 8.465410896966224, 'weight_class_2': 7.555677623507262}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:16,156] Trial 2657 finished with value: 0.9487823036762674 and parameters: {'weight_class_0': 1.0468253041753783, 'weight_class_1': 8.451098641024508, 'weight_class_2': 7.58859143499054}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:16,181] Trial 2658 finished with value: 0.9486715362420819 and parameters: {'weight_class_0': 1.072035686545254, 'weight_class_1': 8.691418193147495, 'weight_class_2': 7.292437837826186}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:16,200] Trial 2659 finished with value: 0.9488314728055994 and parameters: {'weight_class_0': 1.0237933330184896, 'weight_class_1': 8.466855436280166, 'weight_class_2': 7.59178627891514}. Best is trial 2514 with value: 0.9497621740390644.

Best trial: 2514. Best value: 0.949762:  89%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍              | 2665/3000 [01:09<00:11, 28.57it/s]

[I 2026-07-10 16:13:16,219] Trial 2660 finished with value: 0.9487608593769125 and parameters: {'weight_class_0': 1.0567816020080487, 'weight_class_1': 8.583026491799188, 'weight_class_2': 7.305115273415007}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:16,306] Trial 2661 finished with value: 0.9485094789467593 and parameters: {'weight_class_0': 1.1216802724681962, 'weight_class_1': 8.44110505239545, 'weight_class_2': 7.630698004293279}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:16,327] Trial 2662 finished with value: 0.9486344666205996 and parameters: {'weight_class_0': 1.0730252745488165, 'weight_class_1': 8.662955063497611, 'weight_class_2': 7.263108768866106}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:16,384] Trial 2663 finished with value: 0.9487675436643669 and parameters: {'weight_class_0': 0.329626368536624, 'weight_class_1': 8.450084518505985, 'weight_class_2': 7.261504464700583}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:16,395] Trial 2664 finished with value: 0.9253283155299205 and parameters: {'weight_class_0': 3.574030475765168, 'weight_class_1': 8.51563347988318, 'weight_class_2': 7.183404421709265}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:16,407] Trial 2665 finished with value: 0.9486841216729723 and parameters: {'weight_class_0': 0.31881264542660764, 'weight_class_1': 8.411072537939802, 'weight_class_2': 7.221594272321765}. Best is trial 2514 with value: 0.9497621740390644.

Best trial: 2514. Best value: 0.949762:  89%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊              | 2673/3000 [01:09<00:10, 31.53it/s]

[I 2026-07-10 16:13:16,427] Trial 2666 finished with value: 0.9472478231720607 and parameters: {'weight_class_0': 0.20827244271583711, 'weight_class_1': 8.478468670887148, 'weight_class_2': 7.26879282069345}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:16,494] Trial 2667 finished with value: 0.9483904895455861 and parameters: {'weight_class_0': 0.2881908309520565, 'weight_class_1': 8.92012914831703, 'weight_class_2': 7.223042883296967}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:16,516] Trial 2668 finished with value: 0.9478708484628053 and parameters: {'weight_class_0': 0.28723245258416097, 'weight_class_1': 8.925438587777288, 'weight_class_2': 9.707250407762492}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:16,577] Trial 2669 finished with value: 0.947187510137569 and parameters: {'weight_class_0': 0.21227167597752877, 'weight_class_1': 8.868737671972601, 'weight_class_2': 7.1470487064451245}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:16,580] Trial 2670 finished with value: 0.9485691858716123 and parameters: {'weight_class_0': 0.31642154916077914, 'weight_class_1': 8.92190755180931, 'weight_class_2': 7.24491940567024}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:16,587] Trial 2671 finished with value: 0.948737859037395 and parameters: {'weight_class_0': 0.33594320915400316, 'weight_class_1': 8.897653306062212, 'weight_class_2': 7.230860179814868}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:16,648] Trial 2672 finished with value: 0.9483985429500649 and parameters: {'weight_class_0': 0.28902362299066725, 'weight_class_1': 8.91318553005916, 'weight_class_2': 7.15990416182616}. Best is trial 2514 with value: 0.9497621740390644.

Best trial: 2514. Best value: 0.949762:  89%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████              | 2677/3000 [01:10<00:12, 26.29it/s]

[I 2026-07-10 16:13:16,696] Trial 2673 finished with value: 0.9481822431514914 and parameters: {'weight_class_0': 0.2731861436215285, 'weight_class_1': 8.992602118255364, 'weight_class_2': 7.250477195635898}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:16,746] Trial 2675 finished with value: 0.948865773940776 and parameters: {'weight_class_0': 0.3653122104733011, 'weight_class_1': 8.939704403195345, 'weight_class_2': 7.391120310709944}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:16,766] Trial 2674 finished with value: 0.9451603592238561 and parameters: {'weight_class_0': 0.155213397099992, 'weight_class_1': 8.886434618237006, 'weight_class_2': 7.259128205707638}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:16,847] Trial 2678 finished with value: 0.9496911656332799 and parameters: {'weight_class_0': 0.6775549241731755, 'weight_class_1': 8.895733206838067, 'weight_class_2': 7.424060571791701}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:16,849] Trial 2676 finished with value: 0.9469789200075621 and parameters: {'weight_class_0': 0.20379548527004976, 'weight_class_1': 8.920024820451252, 'weight_class_2': 7.097238391505325}. Best is trial 2514 with value: 0.9497621740390644.

[I 2026-07-10 16:13:16,874] Trial 2677 finished with value: 0.946697270364456 and parameters: {'weight_class_0': 0.19545521716837277, 'weight_class_1': 8.901087764716095, 'weight_class_2': 7.365749717463751}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:16,896] Trial 2679 finished with value: 0.949706182650805 and parameters: {'weight_class_0': 0.659137927775888, 'weight_class_1': 8.002755867077127, 'weight_class_2': 7.407426704328602}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:16,941] Trial 2680 finished with value: 0.9496938105247438 and parameters: {'weight_class_0': 0.6601887388885553, 'weight_class_1': 9.451022072415675, 'weight_class_2': 7.478349110524073}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:16,942] Trial 2681 finished with value: 0.949649865395955 and parameters: {'weight_class_0': 0.6787580284335643, 'weight_class_1': 9.664141232412259, 'weight_class_2': 7.835441057991112}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:16,978] Trial 2682 finished with value: 0.9496738291386695 and parameters: {'weight_class_0': 0.6721951985011477, 'weight_class_1': 7.965813492509038, 'weight_class_2': 7.842176491512065}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:16,995] Trial 2683 finished with value: 0.949666888663638 and parameters: {'weight_class_0': 0.6692612901328623, 'weight_class_1': 8.100367783802252, 'weight_class_2': 7.8230215203056295}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:17,012] Trial 2684 finished with value: 0.9497051588473499 and parameters: {'weight_class_0': 0.6665050526803582, 'weight_class_1': 8.0053839832852, 'weight_class_2': 7.834807523133027}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:17,065] Trial 2685 finished with value: 0.9496936836452002 and parameters: {'weight_class_0': 0.6921952003600278, 'weight_class_1': 8.048403204171452, 'weight_class_2': 7.829031565713171}. Best is trial 2514 with value: 0.9497621740390644.

Best trial: 2514. Best value: 0.949762:  90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌             | 2691/3000 [01:10<00:11, 27.66it/s]

[I 2026-07-10 16:13:17,115] Trial 2686 finished with value: 0.9496109441730408 and parameters: {'weight_class_0': 0.6689682928900276, 'weight_class_1': 8.02005027702883, 'weight_class_2': 6.647122944039777}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:17,136] Trial 2687 finished with value: 0.9496797183571668 and parameters: {'weight_class_0': 0.6783061852293376, 'weight_class_1': 8.043853983567562, 'weight_class_2': 7.880645156936672}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:17,222] Trial 2688 finished with value: 0.9476940393942767 and parameters: {'weight_class_0': 1.3535030169294568, 'weight_class_1': 8.236776439571674, 'weight_class_2': 7.824158955696566}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:17,262] Trial 2690 finished with value: 0.9496790821598394 and parameters: {'weight_class_0': 0.6650762465940897, 'weight_class_1': 9.645354907255907, 'weight_class_2': 7.751646852743044}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:17,283] Trial 2689 finished with value: 0.9496607069504138 and parameters: {'weight_class_0': 0.6780186996466725, 'weight_class_1': 8.091599281568268, 'weight_class_2': 7.864979228940902}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:17,290] Trial 2691 finished with value: 0.8810814870825959 and parameters: {'weight_class_0': 7.55495091459963, 'weight_class_1': 8.232284079681943, 'weight_class_2': 7.856979679399316}. Best is trial 2514 with value: 0.9497621740390644.

Best trial: 2514. Best value: 0.949762:  90%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉             | 2698/3000 [01:10<00:10, 29.75it/s]

[I 2026-07-10 16:13:17,311] Trial 2692 finished with value: 0.9488916052725225 and parameters: {'weight_class_0': 0.8719043102615955, 'weight_class_1': 8.112258121615891, 'weight_class_2': 6.605235332263982}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:17,375] Trial 2693 finished with value: 0.9488634668480896 and parameters: {'weight_class_0': 0.9120482572809913, 'weight_class_1': 8.313557542682037, 'weight_class_2': 6.6641886444243905}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:17,419] Trial 2695 finished with value: 0.9492330497507376 and parameters: {'weight_class_0': 0.9095698792838287, 'weight_class_1': 8.356269357459897, 'weight_class_2': 8.194469243281612}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:17,430] Trial 2694 finished with value: 0.9488621230968288 and parameters: {'weight_class_0': 0.9193708153083793, 'weight_class_1': 8.323171511778744, 'weight_class_2': 6.655718493428837}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:17,481] Trial 2696 finished with value: 0.9472854212523116 and parameters: {'weight_class_0': 1.4074268408470694, 'weight_class_1': 8.285437265815672, 'weight_class_2': 7.596126532656216}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:17,502] Trial 2697 finished with value: 0.9477564999635605 and parameters: {'weight_class_0': 1.3859182875486349, 'weight_class_1': 8.324432610134089, 'weight_class_2': 8.182072529159466}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:17,515] Trial 2699 finished with value: 0.9475782282520383 and parameters: {'weight_class_0': 1.3669651372733465, 'weight_class_1': 8.642363559242456, 'weight_class_2': 7.583917715140512}. Best is trial 2514 with value: 0.9497621740390644.

Best trial: 2514. Best value: 0.949762:  90%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏            | 2704/3000 [01:11<00:10, 28.66it/s]

[I 2026-07-10 16:13:17,524] Trial 2698 finished with value: 0.9491621922466559 and parameters: {'weight_class_0': 0.9554488290065992, 'weight_class_1': 8.298053489749726, 'weight_class_2': 8.126321034373726}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:17,595] Trial 2700 finished with value: 0.9490605319869466 and parameters: {'weight_class_0': 0.9352210897144985, 'weight_class_1': 8.619062126705796, 'weight_class_2': 7.569154756333708}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:17,674] Trial 2702 finished with value: 0.9491417653257018 and parameters: {'weight_class_0': 0.9217993261813742, 'weight_class_1': 8.6850089366279, 'weight_class_2': 7.594253857532444}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:17,702] Trial 2703 finished with value: 0.9493447951853059 and parameters: {'weight_class_0': 0.8984581440862489, 'weight_class_1': 8.698081191657629, 'weight_class_2': 8.174433697226613}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:17,717] Trial 2701 finished with value: 0.9493300394701195 and parameters: {'weight_class_0': 0.8616539308337452, 'weight_class_1': 8.36319407175713, 'weight_class_2': 7.5893150021498625}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:17,721] Trial 2704 finished with value: 0.9493006540302934 and parameters: {'weight_class_0': 0.9094165206447113, 'weight_class_1': 8.65349557351396, 'weight_class_2': 8.215473283150757}. Best is trial 2514 with value: 0.9497621740390644.

[I 2026-07-10 16:13:17,782] Trial 2705 finished with value: 0.9492020886891254 and parameters: {'weight_class_0': 0.903851200790089, 'weight_class_1': 8.637329920853285, 'weight_class_2': 7.57940712207329}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:17,818] Trial 2707 finished with value: 0.949407804974545 and parameters: {'weight_class_0': 0.46956563709171883, 'weight_class_1': 8.622544879242787, 'weight_class_2': 7.551096182268648}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:17,858] Trial 2706 finished with value: 0.9495757694348853 and parameters: {'weight_class_0': 0.5197518658418394, 'weight_class_1': 8.580308815945896, 'weight_class_2': 7.056267933927242}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:17,877] Trial 2708 finished with value: 0.9485729330875826 and parameters: {'weight_class_0': 0.45689597397401016, 'weight_class_1': 8.646566001641574, 'weight_class_2': 2.6247030685953354}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:17,898] Trial 2709 finished with value: 0.9494278116086248 and parameters: {'weight_class_0': 0.47583562044813854, 'weight_class_1': 8.660988707080945, 'weight_class_2': 7.075038993791301}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:17,945] Trial 2711 finished with value: 0.9494257365486357 and parameters: {'weight_class_0': 0.473584128699594, 'weight_class_1': 8.617490286189398, 'weight_class_2': 7.490747121051764}. Best is trial 2514 with value: 0.9497621740390644.

[I 2026-07-10 16:13:17,974] Trial 2710 finished with value: 0.9496560847189081 and parameters: {'weight_class_0': 0.4403696024958053, 'weight_class_1': 8.6337747427529, 'weight_class_2': 5.773204746500701}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:18,022] Trial 2712 finished with value: 0.8791617506306064 and parameters: {'weight_class_0': 0.46983407832431356, 'weight_class_1': 0.05884863572501864, 'weight_class_2': 6.968792135276961}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:18,074] Trial 2713 finished with value: 0.9493959538571537 and parameters: {'weight_class_0': 0.45375869334725283, 'weight_class_1': 8.59730873908815, 'weight_class_2': 7.034429852501041}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:18,089] Trial 2714 finished with value: 0.9495099114935629 and parameters: {'weight_class_0': 0.4899567141084489, 'weight_class_1': 7.832225249940353, 'weight_class_2': 7.055040112977107}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:18,109] Trial 2715 finished with value: 0.9495202150180013 and parameters: {'weight_class_0': 0.4932060616869965, 'weight_class_1': 7.8250601802036215, 'weight_class_2': 7.035241377078222}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:18,162] Trial 2716 finished with value: 0.9495810613278035 and parameters: {'weight_class_0': 0.5109223573015382, 'weight_class_1': 8.499885494898983, 'weight_class_2': 7.051842881924554}. Best is trial 2514 with value: 0.9497621740390644.

[I 2026-07-10 16:13:18,173] Trial 2717 finished with value: 0.94902713273558 and parameters: {'weight_class_0': 0.48002019866897006, 'weight_class_1': 7.831698955478164, 'weight_class_2': 3.2688330796415794}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:18,219] Trial 2718 finished with value: 0.9492983684081997 and parameters: {'weight_class_0': 0.4144086139981855, 'weight_class_1': 7.431216655356461, 'weight_class_2': 7.056423968882382}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:18,255] Trial 2720 finished with value: 0.9494648822503597 and parameters: {'weight_class_0': 0.4811199738307068, 'weight_class_1': 9.419858020783279, 'weight_class_2': 7.0310127246133955}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:18,257] Trial 2719 finished with value: 0.9495101857410931 and parameters: {'weight_class_0': 0.47512943267894325, 'weight_class_1': 7.913212649313145, 'weight_class_2': 7.003183244846497}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:18,336] Trial 2721 finished with value: 0.9102526072366964 and parameters: {'weight_class_0': 4.465720607717334, 'weight_class_1': 7.853696741858243, 'weight_class_2': 6.988285364582916}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:18,402] Trial 2723 finished with value: 0.9496859034395394 and parameters: {'weight_class_0': 0.5786853929552198, 'weight_class_1': 7.89655118751047, 'weight_class_2': 6.1283281032174965}. Best is trial 2514 with value: 0.9497621740390644.

Best trial: 2514. Best value: 0.949762:  91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎           | 2729/3000 [01:11<00:08, 30.34it/s]

[I 2026-07-10 16:13:18,419] Trial 2722 finished with value: 0.9496571186818746 and parameters: {'weight_class_0': 0.5888882608853606, 'weight_class_1': 7.891127883013702, 'weight_class_2': 7.353760096734382}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:18,429] Trial 2724 finished with value: 0.9496964732189058 and parameters: {'weight_class_0': 0.5920589155675897, 'weight_class_1': 7.808860498160664, 'weight_class_2': 7.330276166872201}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:18,472] Trial 2725 finished with value: 0.9495865862345765 and parameters: {'weight_class_0': 0.7522462304274364, 'weight_class_1': 9.42693937300514, 'weight_class_2': 7.369060988884052}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:18,476] Trial 2726 finished with value: 0.9495851709544282 and parameters: {'weight_class_0': 0.7325001194108486, 'weight_class_1': 8.127691204293685, 'weight_class_2': 7.368163912025053}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:18,504] Trial 2727 finished with value: 0.9495492143651901 and parameters: {'weight_class_0': 0.7489164599605773, 'weight_class_1': 8.174177976047348, 'weight_class_2': 7.337585336043373}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:18,561] Trial 2728 finished with value: 0.949501898679916 and parameters: {'weight_class_0': 0.7710830034977798, 'weight_class_1': 8.18026525395123, 'weight_class_2': 7.367918186166858}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:18,597] Trial 2729 finished with value: 0.9496133176388276 and parameters: {'weight_class_0': 0.7460328562063101, 'weight_class_1': 9.45259730715603, 'weight_class_2': 7.357779698291998}. Best is trial 2514 with value: 0.9497621740390644.

Best trial: 2514. Best value: 0.949762:  91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌           | 2735/3000 [01:12<00:08, 29.73it/s]

[I 2026-07-10 16:13:18,648] Trial 2731 finished with value: 0.9486287706523506 and parameters: {'weight_class_0': 0.8003822074091317, 'weight_class_1': 8.153887603003357, 'weight_class_2': 4.699350142232348}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:18,690] Trial 2730 finished with value: 0.9495625657792516 and parameters: {'weight_class_0': 0.7518798877743192, 'weight_class_1': 8.164831227739134, 'weight_class_2': 7.344058521615457}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:18,698] Trial 2732 finished with value: 0.9497002510268432 and parameters: {'weight_class_0': 0.6609324518083491, 'weight_class_1': 8.108988501243385, 'weight_class_2': 7.341541861649967}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:18,702] Trial 2733 finished with value: 0.9490282965311995 and parameters: {'weight_class_0': 0.739629349333938, 'weight_class_1': 8.154772452909011, 'weight_class_2': 5.100457440065365}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:18,779] Trial 2734 finished with value: 0.9486674330941033 and parameters: {'weight_class_0': 0.8112855564734669, 'weight_class_1': 8.124116384603084, 'weight_class_2': 4.880033585939465}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:18,800] Trial 2735 finished with value: 0.9460359327185882 and parameters: {'weight_class_0': 0.16250306632903572, 'weight_class_1': 8.102587282702242, 'weight_class_2': 7.396686445819349}. Best is trial 2514 with value: 0.9497621740390644.

Best trial: 2514. Best value: 0.949762:  91%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊           | 2743/3000 [01:12<00:08, 29.88it/s]

[I 2026-07-10 16:13:18,863] Trial 2736 finished with value: 0.9407614376968366 and parameters: {'weight_class_0': 0.10549634748324288, 'weight_class_1': 8.384200633319402, 'weight_class_2': 7.410142581938772}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:18,872] Trial 2737 finished with value: 0.9458807637729669 and parameters: {'weight_class_0': 0.17053104724265822, 'weight_class_1': 8.394087009563167, 'weight_class_2': 8.519384947799212}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:18,909] Trial 2739 finished with value: 0.9441725502393689 and parameters: {'weight_class_0': 0.13455113755111114, 'weight_class_1': 8.407453658001977, 'weight_class_2': 7.665007643516995}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:18,924] Trial 2738 finished with value: 0.9453209023598607 and parameters: {'weight_class_0': 0.15292819302127936, 'weight_class_1': 8.418684927161111, 'weight_class_2': 7.661559019058785}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:18,939] Trial 2740 finished with value: 0.9448234427677745 and parameters: {'weight_class_0': 0.1533103681952036, 'weight_class_1': 9.117254826821608, 'weight_class_2': 7.6539980596727375}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:18,997] Trial 2741 finished with value: 0.9447821643808472 and parameters: {'weight_class_0': 0.14344016749135746, 'weight_class_1': 8.364414773904393, 'weight_class_2': 7.677769131418689}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:19,059] Trial 2742 finished with value: 0.9451414491764245 and parameters: {'weight_class_0': 0.14887725107739302, 'weight_class_1': 8.392976438068846, 'weight_class_2': 7.651820804004384}. Best is trial 2514 with value: 0.9497621740390644.

[I 2026-07-10 16:13:19,078] Trial 2743 finished with value: 0.9447526593345033 and parameters: {'weight_class_0': 0.14298708772429058, 'weight_class_1': 8.40938926408922, 'weight_class_2': 7.616056853071581}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:19,112] Trial 2744 finished with value: 0.945308113475789 and parameters: {'weight_class_0': 0.15218438324995048, 'weight_class_1': 8.394227910300454, 'weight_class_2': 7.64612157721341}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:19,138] Trial 2745 finished with value: 0.939483005672323 and parameters: {'weight_class_0': 0.09975306617496149, 'weight_class_1': 8.41715055561723, 'weight_class_2': 7.618162145170201}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:19,175] Trial 2746 finished with value: 0.9475547007307332 and parameters: {'weight_class_0': 0.2367605989854687, 'weight_class_1': 9.108990996287567, 'weight_class_2': 7.563967789290314}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:19,202] Trial 2747 finished with value: 0.9472117845194101 and parameters: {'weight_class_0': 0.1903361995343057, 'weight_class_1': 7.094028345561995, 'weight_class_2': 7.643389075398942}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:19,240] Trial 2748 finished with value: 0.9484257987832695 and parameters: {'weight_class_0': 1.1842190610530459, 'weight_class_1': 9.104190940994117, 'weight_class_2': 7.6600034996571225}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:19,296] Trial 2749 finished with value: 0.9481269330459847 and parameters: {'weight_class_0': 1.160996518612242, 'weight_class_1': 8.400725563207773, 'weight_class_2': 6.806715315438111}. Best is trial 2514 with value: 0.9497621740390644.

Best trial: 2514. Best value: 0.949762:  92%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍          | 2756/3000 [01:12<00:08, 29.60it/s]

[I 2026-07-10 16:13:19,343] Trial 2750 finished with value: 0.9478890878971251 and parameters: {'weight_class_0': 1.2377798418058923, 'weight_class_1': 9.068966580302131, 'weight_class_2': 6.743845295481446}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:19,361] Trial 2751 finished with value: 0.9480520632013024 and parameters: {'weight_class_0': 1.2042299221768769, 'weight_class_1': 7.542594111161179, 'weight_class_2': 8.072599262834503}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:19,375] Trial 2752 finished with value: 0.9474530575999625 and parameters: {'weight_class_0': 1.2320756314267618, 'weight_class_1': 7.563614364345152, 'weight_class_2': 6.772686757000542}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:19,424] Trial 2753 finished with value: 0.9486337551835345 and parameters: {'weight_class_0': 1.025407628346254, 'weight_class_1': 7.503888104119549, 'weight_class_2': 8.015039845521628}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:19,444] Trial 2754 finished with value: 0.9470024343857958 and parameters: {'weight_class_0': 1.2949063204112021, 'weight_class_1': 7.480586262383849, 'weight_class_2': 6.78388140113626}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:19,498] Trial 2755 finished with value: 0.9473658036473614 and parameters: {'weight_class_0': 1.3067420861269805, 'weight_class_1': 8.808829672692934, 'weight_class_2': 6.827041562355172}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:19,518] Trial 2756 finished with value: 0.9482175975831807 and parameters: {'weight_class_0': 1.2472684936026486, 'weight_class_1': 8.840617001499416, 'weight_class_2': 8.040785260675973}. Best is trial 2514 with value: 0.9497621740390644.

[I 2026-07-10 16:13:19,532] Trial 2757 finished with value: 0.9479668122325076 and parameters: {'weight_class_0': 1.209264272948912, 'weight_class_1': 7.488022152886143, 'weight_class_2': 8.041439394808217}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:19,613] Trial 2759 finished with value: 0.9481847748175438 and parameters: {'weight_class_0': 1.2540310928015657, 'weight_class_1': 8.831698359848481, 'weight_class_2': 7.936716479529671}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:19,631] Trial 2758 finished with value: 0.9476928561666401 and parameters: {'weight_class_0': 1.2507823895396424, 'weight_class_1': 8.830301726320402, 'weight_class_2': 6.773920411285365}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:19,634] Trial 2760 finished with value: 0.9478962669635599 and parameters: {'weight_class_0': 1.2273192360493583, 'weight_class_1': 7.489255381302229, 'weight_class_2': 8.005260941997232}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:19,708] Trial 2761 finished with value: 0.9490996770385788 and parameters: {'weight_class_0': 0.961368037694764, 'weight_class_1': 8.793954715270745, 'weight_class_2': 8.00583814817299}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:19,718] Trial 2762 finished with value: 0.9460366877390337 and parameters: {'weight_class_0': 0.9930904935865605, 'weight_class_1': 4.045095044243471, 'weight_class_2': 7.160141601862583}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:19,748] Trial 2763 finished with value: 0.9490895454848932 and parameters: {'weight_class_0': 0.9668331586114316, 'weight_class_1': 8.74152619587397, 'weight_class_2': 7.993030318203263}. Best is trial 2514 with value: 0.9497621740390644.

[I 2026-07-10 16:13:19,824] Trial 2764 finished with value: 0.9488770983440195 and parameters: {'weight_class_0': 0.3572635073194379, 'weight_class_1': 8.79820181727692, 'weight_class_2': 7.205664474675062}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:19,831] Trial 2765 finished with value: 0.9490292758404112 and parameters: {'weight_class_0': 0.3836129353186004, 'weight_class_1': 8.786104603005594, 'weight_class_2': 7.192116164049341}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:19,867] Trial 2766 finished with value: 0.9490602856369934 and parameters: {'weight_class_0': 0.9018586353051776, 'weight_class_1': 8.751664512896202, 'weight_class_2': 7.200100621528583}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:19,920] Trial 2767 finished with value: 0.9488506307555702 and parameters: {'weight_class_0': 0.35166452224377553, 'weight_class_1': 8.73325661610293, 'weight_class_2': 7.192989393710617}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:19,922] Trial 2768 finished with value: 0.9488823329818845 and parameters: {'weight_class_0': 0.3534714163864635, 'weight_class_1': 8.780112528341022, 'weight_class_2': 7.144337638332411}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:19,957] Trial 2769 finished with value: 0.9490136348612831 and parameters: {'weight_class_0': 0.9130877537948988, 'weight_class_1': 8.781090571553506, 'weight_class_2': 7.196069265384545}. Best is trial 2514 with value: 0.9497621740390644.

[I 2026-07-10 16:13:20,027] Trial 2771 finished with value: 0.9490177586029582 and parameters: {'weight_class_0': 0.3671894011899012, 'weight_class_1': 8.007453904733552, 'weight_class_2': 7.182280101240066}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:20,048] Trial 2773 finished with value: 0.9488582318251017 and parameters: {'weight_class_0': 0.34972065593779966, 'weight_class_1': 8.539482793278463, 'weight_class_2': 7.1997991266353685}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:20,059] Trial 2772 finished with value: 0.9490209332360164 and parameters: {'weight_class_0': 0.3661490491841255, 'weight_class_1': 7.956207571572528, 'weight_class_2': 7.170815032417003}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:20,070] Trial 2770 finished with value: 0.9489373156652922 and parameters: {'weight_class_0': 0.9209701634362024, 'weight_class_1': 7.979569623039433, 'weight_class_2': 7.215910863065652}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:20,115] Trial 2774 finished with value: 0.9489393662846872 and parameters: {'weight_class_0': 0.3534521079443237, 'weight_class_1': 7.989196137634862, 'weight_class_2': 7.24019300426353}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:20,161] Trial 2775 finished with value: 0.9497223569409509 and parameters: {'weight_class_0': 0.6160653586553526, 'weight_class_1': 7.956093692291538, 'weight_class_2': 7.167982867958594}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:20,207] Trial 2776 finished with value: 0.9497167001402738 and parameters: {'weight_class_0': 0.6188768392135585, 'weight_class_1': 8.034678298794418, 'weight_class_2': 7.455462418491107}. Best is trial 2514 with value: 0.9497621740390644.

[I 2026-07-10 16:13:20,224] Trial 2777 finished with value: 0.9497183877302434 and parameters: {'weight_class_0': 0.6191931010113091, 'weight_class_1': 8.028502082154603, 'weight_class_2': 7.458107243509542}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:20,268] Trial 2778 finished with value: 0.9497185144736786 and parameters: {'weight_class_0': 0.6214382723172641, 'weight_class_1': 7.986989463252266, 'weight_class_2': 7.47293271343316}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:20,321] Trial 2779 finished with value: 0.9497174747719225 and parameters: {'weight_class_0': 0.6305810788402271, 'weight_class_1': 8.505730934365527, 'weight_class_2': 7.363269592248643}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:20,344] Trial 2780 finished with value: 0.9497226301682282 and parameters: {'weight_class_0': 0.6225733176478546, 'weight_class_1': 7.958828918918417, 'weight_class_2': 7.446689724993712}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:20,350] Trial 2781 finished with value: 0.9496875998652302 and parameters: {'weight_class_0': 0.7199761421969509, 'weight_class_1': 9.9928896399936, 'weight_class_2': 7.470699546554306}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:20,443] Trial 2783 finished with value: 0.9302063635188517 and parameters: {'weight_class_0': 3.2320772699047025, 'weight_class_1': 8.254967555908776, 'weight_class_2': 7.4598993378893095}. Best is trial 2514 with value: 0.9497621740390644.

Best trial: 2787. Best value: 0.949774:  93%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊         | 2789/3000 [01:13<00:07, 28.54it/s]

[I 2026-07-10 16:13:20,453] Trial 2782 finished with value: 0.9497272613020785 and parameters: {'weight_class_0': 0.687055285500606, 'weight_class_1': 8.524586698936591, 'weight_class_2': 7.468410464770976}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:20,492] Trial 2784 finished with value: 0.9497027425031409 and parameters: {'weight_class_0': 0.67757067600375, 'weight_class_1': 8.20115542278683, 'weight_class_2': 7.497429398448295}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:20,529] Trial 2786 finished with value: 0.9497405872292296 and parameters: {'weight_class_0': 0.6627062944887394, 'weight_class_1': 8.27430642523833, 'weight_class_2': 7.486528794504238}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:20,530] Trial 2785 finished with value: 0.944102651712977 and parameters: {'weight_class_0': 0.6199584953477082, 'weight_class_1': 8.231574428808011, 'weight_class_2': 1.9053861686035027}. Best is trial 2514 with value: 0.9497621740390644.
[I 2026-07-10 16:13:20,543] Trial 2787 finished with value: 0.9497743750090324 and parameters: {'weight_class_0': 0.614844576364072, 'weight_class_1': 8.258589181322845, 'weight_class_2': 7.48963067756502}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:20,602] Trial 2788 finished with value: 0.9193919071343647 and parameters: {'weight_class_0': 0.6241375669606443, 'weight_class_1': 0.6903563568329742, 'weight_class_2': 7.483737890609302}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:20,640] Trial 2789 finished with value: 0.9495291913883109 and parameters: {'weight_class_0': 0.7751532963489883, 'weight_class_1': 8.248051411245774, 'weight_class_2': 7.794336702851994}. Best is trial 2787 with value: 0.9497743750090324.

Best trial: 2787. Best value: 0.949774:  93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████         | 2795/3000 [01:14<00:07, 27.23it/s]

[I 2026-07-10 16:13:20,679] Trial 2790 finished with value: 0.9495787798586018 and parameters: {'weight_class_0': 0.7686449391096538, 'weight_class_1': 8.32096273827679, 'weight_class_2': 7.817900169979182}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:20,719] Trial 2791 finished with value: 0.9494611933575036 and parameters: {'weight_class_0': 0.8161346743508961, 'weight_class_1': 8.26472755580179, 'weight_class_2': 7.806590872644311}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:20,739] Trial 2792 finished with value: 0.9493847285951263 and parameters: {'weight_class_0': 0.8335455872619226, 'weight_class_1': 8.277293146025638, 'weight_class_2': 7.750169900027788}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:20,776] Trial 2793 finished with value: 0.9494490756024568 and parameters: {'weight_class_0': 0.8227876485171776, 'weight_class_1': 8.252343525253325, 'weight_class_2': 7.8102447309783924}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:20,865] Trial 2795 finished with value: 0.9494784024585873 and parameters: {'weight_class_0': 0.8004996956923446, 'weight_class_1': 8.31494801538921, 'weight_class_2': 7.782037109614938}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:20,881] Trial 2794 finished with value: 0.9493764052581811 and parameters: {'weight_class_0': 0.8418523519119296, 'weight_class_1': 8.357638746627849, 'weight_class_2': 7.812825659582775}. Best is trial 2787 with value: 0.9497743750090324.

Best trial: 2787. Best value: 0.949774:  93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍        | 2803/3000 [01:14<00:06, 30.68it/s]

[I 2026-07-10 16:13:20,907] Trial 2796 finished with value: 0.9494099255572097 and parameters: {'weight_class_0': 0.869742826823807, 'weight_class_1': 9.10694040608884, 'weight_class_2': 7.836565824869775}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:20,956] Trial 2797 finished with value: 0.8660138815326297 and parameters: {'weight_class_0': 9.547356327746062, 'weight_class_1': 8.53172392785609, 'weight_class_2': 7.004256648507727}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:21,007] Trial 2798 finished with value: 0.947710557744618 and parameters: {'weight_class_0': 0.844626271986777, 'weight_class_1': 4.658620600541984, 'weight_class_2': 6.466678785967224}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:21,009] Trial 2800 finished with value: 0.9491173869682793 and parameters: {'weight_class_0': 0.886789811683095, 'weight_class_1': 9.076483206216711, 'weight_class_2': 6.943996737636633}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:21,025] Trial 2799 finished with value: 0.9492228558171277 and parameters: {'weight_class_0': 0.8633902112430396, 'weight_class_1': 9.320231308520144, 'weight_class_2': 6.987375117743511}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:21,073] Trial 2801 finished with value: 0.9492442666833133 and parameters: {'weight_class_0': 0.41152904815702307, 'weight_class_1': 8.501613681410392, 'weight_class_2': 6.953080328122894}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:21,078] Trial 2802 finished with value: 0.9493047394552289 and parameters: {'weight_class_0': 0.4304302952743805, 'weight_class_1': 8.552475516992065, 'weight_class_2': 7.366387005096154}. Best is trial 2787 with value: 0.9497743750090324.

[I 2026-07-10 16:13:21,136] Trial 2803 finished with value: 0.9493321525230303 and parameters: {'weight_class_0': 0.4219916562803898, 'weight_class_1': 8.537802495283918, 'weight_class_2': 6.899225871751014}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:21,138] Trial 2804 finished with value: 0.949591193901742 and parameters: {'weight_class_0': 0.509654381802342, 'weight_class_1': 9.097843885864119, 'weight_class_2': 6.947499365135707}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:21,172] Trial 2805 finished with value: 0.9491818493341532 and parameters: {'weight_class_0': 0.40582750292079217, 'weight_class_1': 9.266589453740073, 'weight_class_2': 6.924954025704235}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:21,248] Trial 2807 finished with value: 0.9494027042170323 and parameters: {'weight_class_0': 0.45085835991384493, 'weight_class_1': 8.539739837010384, 'weight_class_2': 6.975284032983861}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:21,266] Trial 2806 finished with value: 0.9491914217554567 and parameters: {'weight_class_0': 0.39376971689125484, 'weight_class_1': 8.528036490742107, 'weight_class_2': 6.9134381845876955}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:21,300] Trial 2808 finished with value: 0.9492256849464505 and parameters: {'weight_class_0': 0.40609048457310326, 'weight_class_1': 8.54491474020427, 'weight_class_2': 6.939143446737485}. Best is trial 2787 with value: 0.9497743750090324.

Best trial: 2787. Best value: 0.949774:  94%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉        | 2815/3000 [01:14<00:06, 28.82it/s]

[I 2026-07-10 16:13:21,361] Trial 2809 finished with value: 0.9491593662789578 and parameters: {'weight_class_0': 0.4037765707731573, 'weight_class_1': 9.265755573130185, 'weight_class_2': 7.065613800028961}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:21,402] Trial 2810 finished with value: 0.9492023588942741 and parameters: {'weight_class_0': 0.4088148719824762, 'weight_class_1': 8.60856210490494, 'weight_class_2': 7.282098751095815}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:21,427] Trial 2811 finished with value: 0.9486322725872315 and parameters: {'weight_class_0': 0.412774493927303, 'weight_class_1': 3.821081130914849, 'weight_class_2': 7.30531813832114}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:21,453] Trial 2812 finished with value: 0.9495843470400486 and parameters: {'weight_class_0': 0.5395997206096128, 'weight_class_1': 7.746620225468252, 'weight_class_2': 7.31635751683317}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:21,496] Trial 2813 finished with value: 0.9494874137943721 and parameters: {'weight_class_0': 0.5172082029120555, 'weight_class_1': 7.747799085606059, 'weight_class_2': 7.3230134175983075}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:21,523] Trial 2814 finished with value: 0.9496126159472261 and parameters: {'weight_class_0': 0.5323126458223888, 'weight_class_1': 8.557871925450687, 'weight_class_2': 7.300867527740359}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:21,557] Trial 2815 finished with value: 0.9496568719207349 and parameters: {'weight_class_0': 0.5543639433674117, 'weight_class_1': 8.556527560739458, 'weight_class_2': 7.329482312600816}. Best is trial 2787 with value: 0.9497743750090324.

Best trial: 2787. Best value: 0.949774:  94%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏       | 2821/3000 [01:15<00:06, 28.75it/s]

[I 2026-07-10 16:13:21,585] Trial 2816 finished with value: 0.9495149430710835 and parameters: {'weight_class_0': 0.5193838933060496, 'weight_class_1': 7.679809421579288, 'weight_class_2': 7.284345473465077}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:21,617] Trial 2817 finished with value: 0.9494585631230671 and parameters: {'weight_class_0': 0.4886676123329834, 'weight_class_1': 7.778305378927724, 'weight_class_2': 7.306349275462327}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:21,683] Trial 2818 finished with value: 0.9496663308521849 and parameters: {'weight_class_0': 0.5592964777485692, 'weight_class_1': 8.628655403068972, 'weight_class_2': 7.274156793890554}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:21,700] Trial 2819 finished with value: 0.949621519349495 and parameters: {'weight_class_0': 0.5585759114807155, 'weight_class_1': 7.718349837693198, 'weight_class_2': 7.27109139197743}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:21,758] Trial 2821 finished with value: 0.9496164037423934 and parameters: {'weight_class_0': 0.5677154176575668, 'weight_class_1': 7.8283048492852, 'weight_class_2': 7.285073994453792}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:21,761] Trial 2820 finished with value: 0.9487820878068396 and parameters: {'weight_class_0': 1.0444294860322778, 'weight_class_1': 8.442092020479048, 'weight_class_2': 7.323445099192341}. Best is trial 2787 with value: 0.9497743750090324.

Best trial: 2787. Best value: 0.949774:  94%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 2829/3000 [01:15<00:05, 30.42it/s]

[I 2026-07-10 16:13:21,781] Trial 2822 finished with value: 0.9486776617489653 and parameters: {'weight_class_0': 0.9995099501369001, 'weight_class_1': 7.707689553827984, 'weight_class_2': 7.2742832473033054}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:21,851] Trial 2823 finished with value: 0.9488448016574004 and parameters: {'weight_class_0': 0.9940773056717193, 'weight_class_1': 8.17343147891192, 'weight_class_2': 7.329732995303735}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:21,905] Trial 2824 finished with value: 0.9488808485984771 and parameters: {'weight_class_0': 0.9993139174964383, 'weight_class_1': 8.443236034041146, 'weight_class_2': 7.4900061918749525}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:21,908] Trial 2825 finished with value: 0.9486716155121004 and parameters: {'weight_class_0': 1.0408008614700022, 'weight_class_1': 8.135811456865042, 'weight_class_2': 7.5145043548171}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:21,912] Trial 2826 finished with value: 0.948756717072403 and parameters: {'weight_class_0': 1.011934872390905, 'weight_class_1': 8.135410535234861, 'weight_class_2': 7.520961585605701}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:21,971] Trial 2827 finished with value: 0.9488492521493447 and parameters: {'weight_class_0': 0.9781057829785182, 'weight_class_1': 8.125248042223655, 'weight_class_2': 7.508051585471272}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:21,992] Trial 2828 finished with value: 0.9487631462586298 and parameters: {'weight_class_0': 1.0179061987230182, 'weight_class_1': 8.135394546008428, 'weight_class_2': 7.514344734951381}. Best is trial 2787 with value: 0.9497743750090324.

Best trial: 2787. Best value: 0.949774:  94%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊       | 2834/3000 [01:15<00:05, 29.13it/s]

[I 2026-07-10 16:13:22,045] Trial 2829 finished with value: 0.9481219957477869 and parameters: {'weight_class_0': 1.0246849313005222, 'weight_class_1': 6.135873969426687, 'weight_class_2': 7.547204394146066}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:22,069] Trial 2830 finished with value: 0.9487634161910962 and parameters: {'weight_class_0': 1.015086678973137, 'weight_class_1': 8.130595832023133, 'weight_class_2': 7.552698203241637}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:22,072] Trial 2831 finished with value: 0.8931468981421808 and parameters: {'weight_class_0': 1.0450165414955288, 'weight_class_1': 8.127071004866533, 'weight_class_2': 0.2445625395617581}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:22,158] Trial 2832 finished with value: 0.9487335856560364 and parameters: {'weight_class_0': 1.022926911254801, 'weight_class_1': 8.131479152455084, 'weight_class_2': 7.558100011426301}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:22,224] Trial 2833 finished with value: 0.6574717505577626 and parameters: {'weight_class_0': 0.0011810660378019922, 'weight_class_1': 8.17897450414882, 'weight_class_2': 7.561791234084112}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:22,226] Trial 2834 finished with value: 0.9495998429817355 and parameters: {'weight_class_0': 0.7722673576052278, 'weight_class_1': 9.021927099624621, 'weight_class_2': 7.55758274203799}. Best is trial 2787 with value: 0.9497743750090324.

Best trial: 2787. Best value: 0.949774:  95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████       | 2841/3000 [01:15<00:05, 27.38it/s]

[I 2026-07-10 16:13:22,233] Trial 2835 finished with value: 0.9487691621177657 and parameters: {'weight_class_0': 1.0097713892524598, 'weight_class_1': 8.116066956920463, 'weight_class_2': 7.556655638402772}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:22,342] Trial 2837 finished with value: 0.9494589520448057 and parameters: {'weight_class_0': 0.7619236233601923, 'weight_class_1': 8.957109384524653, 'weight_class_2': 6.516685356817884}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:22,343] Trial 2838 finished with value: 0.949606131595191 and parameters: {'weight_class_0': 0.7313426147443508, 'weight_class_1': 8.915624697250315, 'weight_class_2': 7.083825101422774}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:22,350] Trial 2836 finished with value: 0.9497163301771288 and parameters: {'weight_class_0': 0.6908366650348677, 'weight_class_1': 8.97216430542647, 'weight_class_2': 7.551091891527772}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:22,381] Trial 2839 finished with value: 0.9495373064372442 and parameters: {'weight_class_0': 0.7136321513587969, 'weight_class_1': 9.015109435395683, 'weight_class_2': 6.494235481655914}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:22,418] Trial 2840 finished with value: 0.9494829115057679 and parameters: {'weight_class_0': 0.7411504316593761, 'weight_class_1': 8.987450001401218, 'weight_class_2': 6.481784830467136}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:22,435] Trial 2841 finished with value: 0.9496062068918475 and parameters: {'weight_class_0': 0.7060768554770349, 'weight_class_1': 8.96459935840704, 'weight_class_2': 7.101527660523999}. Best is trial 2787 with value: 0.9497743750090324.

Best trial: 2787. Best value: 0.949774:  95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍      | 2848/3000 [01:15<00:05, 29.23it/s]

[I 2026-07-10 16:13:22,477] Trial 2842 finished with value: 0.6605057211479913 and parameters: {'weight_class_0': 0.007940898965726917, 'weight_class_1': 8.98854152799273, 'weight_class_2': 7.0760897170096335}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:22,491] Trial 2843 finished with value: 0.9495841355677359 and parameters: {'weight_class_0': 0.7209676658417388, 'weight_class_1': 8.947501258501912, 'weight_class_2': 7.090101610056012}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:22,510] Trial 2844 finished with value: 0.9496069760853828 and parameters: {'weight_class_0': 0.7201911926305185, 'weight_class_1': 9.023108595035623, 'weight_class_2': 7.168637303507637}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:22,599] Trial 2846 finished with value: 0.949564417969004 and parameters: {'weight_class_0': 0.7086983963396309, 'weight_class_1': 8.960979631832592, 'weight_class_2': 6.594088978183884}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:22,647] Trial 2845 finished with value: 0.9482341226539955 and parameters: {'weight_class_0': 0.2707973449170277, 'weight_class_1': 8.765002777227668, 'weight_class_2': 7.116283153249137}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:22,648] Trial 2847 finished with value: 0.9483572500552505 and parameters: {'weight_class_0': 0.27481095991620513, 'weight_class_1': 8.979663751640347, 'weight_class_2': 6.577148977698496}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:22,688] Trial 2848 finished with value: 0.9482970643399483 and parameters: {'weight_class_0': 0.26835370015053883, 'weight_class_1': 8.395226049280716, 'weight_class_2': 7.128374725702881}. Best is trial 2787 with value: 0.9497743750090324.

Best trial: 2787. Best value: 0.949774:  95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋      | 2854/3000 [01:16<00:05, 28.80it/s]

[I 2026-07-10 16:13:22,760] Trial 2849 finished with value: 0.9483137683716887 and parameters: {'weight_class_0': 0.26993993254704013, 'weight_class_1': 8.363536701268709, 'weight_class_2': 7.074263151331498}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:22,776] Trial 2850 finished with value: 0.9482430371998555 and parameters: {'weight_class_0': 0.27032083397484574, 'weight_class_1': 8.70650781234276, 'weight_class_2': 7.054865637970509}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:22,810] Trial 2851 finished with value: 0.9486952108365422 and parameters: {'weight_class_0': 0.31646350987352084, 'weight_class_1': 8.41207524519402, 'weight_class_2': 7.081324592063098}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:22,833] Trial 2852 finished with value: 0.9481677344705318 and parameters: {'weight_class_0': 0.3451511957616766, 'weight_class_1': 2.899255306824089, 'weight_class_2': 7.107259789988351}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:22,881] Trial 2853 finished with value: 0.9482062705048285 and parameters: {'weight_class_0': 0.26322837434166413, 'weight_class_1': 8.712510375404696, 'weight_class_2': 6.831838814541684}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:22,954] Trial 2854 finished with value: 0.94848278537618 and parameters: {'weight_class_0': 0.2857033429688889, 'weight_class_1': 8.373717320090242, 'weight_class_2': 6.782938565806665}. Best is trial 2787 with value: 0.9497743750090324.

[I 2026-07-10 16:13:22,965] Trial 2855 finished with value: 0.9485384411523855 and parameters: {'weight_class_0': 0.28884637124367796, 'weight_class_1': 8.351905823279202, 'weight_class_2': 6.708109656853815}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:22,983] Trial 2856 finished with value: 0.9484529998628447 and parameters: {'weight_class_0': 0.2789390388700241, 'weight_class_1': 8.389686651357344, 'weight_class_2': 6.777317275893381}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:23,022] Trial 2857 finished with value: 0.9482372389089511 and parameters: {'weight_class_0': 0.27132620689451187, 'weight_class_1': 8.419446329381973, 'weight_class_2': 7.670956280970458}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:23,094] Trial 2858 finished with value: 0.9483531384368598 and parameters: {'weight_class_0': 0.28814184064333465, 'weight_class_1': 8.36793356694919, 'weight_class_2': 7.708079522075234}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:23,097] Trial 2859 finished with value: 0.9496280266542315 and parameters: {'weight_class_0': 0.5863805916256971, 'weight_class_1': 8.400036528980074, 'weight_class_2': 7.650712493598533}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:23,124] Trial 2861 finished with value: 0.9491861236536526 and parameters: {'weight_class_0': 0.5953572289520394, 'weight_class_1': 5.1312805748562, 'weight_class_2': 7.6739631158104045}. Best is trial 2787 with value: 0.9497743750090324.

Best trial: 2787. Best value: 0.949774:  96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏     | 2866/3000 [01:16<00:04, 29.31it/s]

[I 2026-07-10 16:13:23,125] Trial 2860 finished with value: 0.9485521716737031 and parameters: {'weight_class_0': 0.3086895346040799, 'weight_class_1': 8.411773931829623, 'weight_class_2': 7.692778841199245}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:23,195] Trial 2862 finished with value: 0.9496736165973646 and parameters: {'weight_class_0': 0.584077217773077, 'weight_class_1': 8.65814684205034, 'weight_class_2': 6.8153652928723405}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:23,241] Trial 2863 finished with value: 0.9496680937798366 and parameters: {'weight_class_0': 0.5806486402313047, 'weight_class_1': 8.712284621985301, 'weight_class_2': 6.735528228247013}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:23,244] Trial 2864 finished with value: 0.9495901297000163 and parameters: {'weight_class_0': 0.5802145330161731, 'weight_class_1': 9.576964726952475, 'weight_class_2': 7.686551351215025}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:23,262] Trial 2865 finished with value: 0.9495514650121647 and parameters: {'weight_class_0': 0.5494697631872633, 'weight_class_1': 8.351700706908794, 'weight_class_2': 7.68213598398589}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:23,349] Trial 2866 finished with value: 0.9495754394255126 and parameters: {'weight_class_0': 0.5529349462152171, 'weight_class_1': 8.706286365331312, 'weight_class_2': 7.664296638834314}. Best is trial 2787 with value: 0.9497743750090324.

[I 2026-07-10 16:13:23,399] Trial 2868 finished with value: 0.9496502708665521 and parameters: {'weight_class_0': 0.5597204265876787, 'weight_class_1': 8.654816130296895, 'weight_class_2': 7.424524068900972}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:23,404] Trial 2869 finished with value: 0.949610101908668 and parameters: {'weight_class_0': 0.5382569535074078, 'weight_class_1': 8.663227200512816, 'weight_class_2': 7.416400340587287}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:23,413] Trial 2867 finished with value: 0.8767102828191001 and parameters: {'weight_class_0': 8.212272342268506, 'weight_class_1': 8.693628906721864, 'weight_class_2': 7.692990942758076}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:23,516] Trial 2870 finished with value: 0.949715397910333 and parameters: {'weight_class_0': 0.5970037110629514, 'weight_class_1': 8.645450261526511, 'weight_class_2': 7.404195373761399}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:23,523] Trial 2871 finished with value: 0.9494447489008385 and parameters: {'weight_class_0': 0.8472538625593892, 'weight_class_1': 9.540366562931073, 'weight_class_2': 7.3680265081336564}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:23,552] Trial 2872 finished with value: 0.9496300148960981 and parameters: {'weight_class_0': 0.5822391596647566, 'weight_class_1': 9.564060279443348, 'weight_class_2': 7.382206053311641}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:23,567] Trial 2873 finished with value: 0.9493543256456435 and parameters: {'weight_class_0': 0.8450836013011664, 'weight_class_1': 8.691845975165501, 'weight_class_2': 7.350036718546237}. Best is trial 2787 with value: 0.9497743750090324.

Best trial: 2787. Best value: 0.949774:  96%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊     | 2880/3000 [01:17<00:03, 30.95it/s]

[I 2026-07-10 16:13:23,592] Trial 2874 finished with value: 0.9493916508229611 and parameters: {'weight_class_0': 0.7976550074707776, 'weight_class_1': 7.96520778164833, 'weight_class_2': 7.435774718669376}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:23,667] Trial 2876 finished with value: 0.9492412822628863 and parameters: {'weight_class_0': 0.8503986479356008, 'weight_class_1': 7.922080654305704, 'weight_class_2': 7.365508069144272}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:23,679] Trial 2875 finished with value: 0.9492631167513169 and parameters: {'weight_class_0': 0.8445691024984674, 'weight_class_1': 7.953852369192554, 'weight_class_2': 7.323695508708052}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:23,680] Trial 2877 finished with value: 0.9492548749304893 and parameters: {'weight_class_0': 0.8445466286840096, 'weight_class_1': 7.965789270079465, 'weight_class_2': 7.396740272860656}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:23,724] Trial 2878 finished with value: 0.9492641860494543 and parameters: {'weight_class_0': 0.8298630620972731, 'weight_class_1': 7.936094457670988, 'weight_class_2': 7.42289769665493}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:23,798] Trial 2879 finished with value: 0.9492788917493012 and parameters: {'weight_class_0': 0.8342999399054483, 'weight_class_1': 7.9365550239744485, 'weight_class_2': 7.38912543336254}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:23,802] Trial 2880 finished with value: 0.9492939142049397 and parameters: {'weight_class_0': 0.8314777073965467, 'weight_class_1': 7.886457802084142, 'weight_class_2': 7.386319184841664}. Best is trial 2787 with value: 0.9497743750090324.

Best trial: 2787. Best value: 0.949774:  96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████     | 2887/3000 [01:17<00:03, 28.65it/s]

[I 2026-07-10 16:13:23,881] Trial 2881 finished with value: 0.9492526413589225 and parameters: {'weight_class_0': 0.8470684899032714, 'weight_class_1': 7.977658543089253, 'weight_class_2': 7.364915590439384}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:23,932] Trial 2883 finished with value: 0.8997575782636013 and parameters: {'weight_class_0': 5.404521426315202, 'weight_class_1': 7.968422982560735, 'weight_class_2': 7.230921227941485}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:23,941] Trial 2882 finished with value: 0.9492054099088225 and parameters: {'weight_class_0': 0.8558488138653046, 'weight_class_1': 7.954477382236548, 'weight_class_2': 7.242847817585289}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:23,956] Trial 2884 finished with value: 0.9354333852321278 and parameters: {'weight_class_0': 0.8182193402457493, 'weight_class_1': 7.895304188577567, 'weight_class_2': 1.669355347483919}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:23,980] Trial 2885 finished with value: 0.9490986787220342 and parameters: {'weight_class_0': 0.8776170787008993, 'weight_class_1': 7.926989755954779, 'weight_class_2': 7.305074753182836}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:24,041] Trial 2887 finished with value: 0.9494987487524206 and parameters: {'weight_class_0': 0.7876919487969736, 'weight_class_1': 9.224829453256136, 'weight_class_2': 7.2376281163500735}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:24,044] Trial 2886 finished with value: 0.9494647646380039 and parameters: {'weight_class_0': 0.8158441435959591, 'weight_class_1': 9.347746713816203, 'weight_class_2': 7.176478973857191}. Best is trial 2787 with value: 0.9497743750090324.

Best trial: 2787. Best value: 0.949774:  96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎    | 2893/3000 [01:17<00:03, 29.80it/s]

[I 2026-07-10 16:13:24,127] Trial 2888 finished with value: 0.7156179244773634 and parameters: {'weight_class_0': 0.016575394469353855, 'weight_class_1': 8.282603593115565, 'weight_class_2': 7.156930963271863}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:24,131] Trial 2889 finished with value: 0.9495479238956204 and parameters: {'weight_class_0': 0.7601444444062846, 'weight_class_1': 9.346724970956787, 'weight_class_2': 7.210466246257654}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:24,158] Trial 2890 finished with value: 0.9496232417143083 and parameters: {'weight_class_0': 0.724946218178271, 'weight_class_1': 8.215686473566597, 'weight_class_2': 7.140655457232137}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:24,205] Trial 2892 finished with value: 0.9467110844959272 and parameters: {'weight_class_0': 1.4362029000484193, 'weight_class_1': 8.263741709603883, 'weight_class_2': 7.100418865346254}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:24,207] Trial 2891 finished with value: 0.9493510130280803 and parameters: {'weight_class_0': 0.457139212327372, 'weight_class_1': 9.298406555466453, 'weight_class_2': 7.232785415271473}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:24,237] Trial 2893 finished with value: 0.9492603110380097 and parameters: {'weight_class_0': 0.42429606532956704, 'weight_class_1': 9.334849293017786, 'weight_class_2': 7.0362887893485695}. Best is trial 2787 with value: 0.9497743750090324.

Best trial: 2787. Best value: 0.949774:  97%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋    | 2900/3000 [01:17<00:03, 28.19it/s]

[I 2026-07-10 16:13:24,356] Trial 2894 finished with value: 0.9469004108886723 and parameters: {'weight_class_0': 1.4753239906951845, 'weight_class_1': 9.292291524851425, 'weight_class_2': 7.116681845778342}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:24,360] Trial 2895 finished with value: 0.94941950790929 and parameters: {'weight_class_0': 0.4457972958780233, 'weight_class_1': 8.257645809057466, 'weight_class_2': 7.089104541700852}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:24,361] Trial 2896 finished with value: 0.6662560756955512 and parameters: {'weight_class_0': 0.008955805914116266, 'weight_class_1': 8.222292075476261, 'weight_class_2': 6.226865076151393}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:24,433] Trial 2897 finished with value: 0.9494016093291879 and parameters: {'weight_class_0': 0.429741194737282, 'weight_class_1': 8.228211346044743, 'weight_class_2': 6.990784570938475}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:24,470] Trial 2899 finished with value: 0.8943898874854347 and parameters: {'weight_class_0': 5.870245850334887, 'weight_class_1': 8.234208882240717, 'weight_class_2': 7.069941908811821}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:24,477] Trial 2898 finished with value: 0.9494198864407917 and parameters: {'weight_class_0': 0.4453470853327898, 'weight_class_1': 8.259986709063442, 'weight_class_2': 7.013397324563382}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:24,525] Trial 2900 finished with value: 0.9492786433641607 and parameters: {'weight_class_0': 0.4358357890291097, 'weight_class_1': 8.231388344648463, 'weight_class_2': 7.5794108446217585}. Best is trial 2787 with value: 0.9497743750090324.

Best trial: 2787. Best value: 0.949774:  97%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉    | 2906/3000 [01:18<00:03, 29.01it/s]

[I 2026-07-10 16:13:24,540] Trial 2901 finished with value: 0.9494139632080527 and parameters: {'weight_class_0': 0.484556740766932, 'weight_class_1': 8.244097358604465, 'weight_class_2': 7.840050829130607}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:24,574] Trial 2902 finished with value: 0.9485699951443921 and parameters: {'weight_class_0': 1.1063602929769598, 'weight_class_1': 8.508124729214558, 'weight_class_2': 7.555006654799675}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:24,631] Trial 2903 finished with value: 0.9496353255091706 and parameters: {'weight_class_0': 0.5582120336618461, 'weight_class_1': 8.54952981485182, 'weight_class_2': 7.560854687658386}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:24,668] Trial 2905 finished with value: 0.948371594337107 and parameters: {'weight_class_0': 1.1475764484598636, 'weight_class_1': 8.512041403660492, 'weight_class_2': 7.583893642775177}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:24,668] Trial 2904 finished with value: 0.9484073895929139 and parameters: {'weight_class_0': 1.1435695164373718, 'weight_class_1': 8.499203614553068, 'weight_class_2': 7.587322235278236}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:24,754] Trial 2906 finished with value: 0.9486022025428466 and parameters: {'weight_class_0': 1.0989584171623534, 'weight_class_1': 8.479441334377467, 'weight_class_2': 7.543266543118263}. Best is trial 2787 with value: 0.9497743750090324.

[I 2026-07-10 16:13:24,785] Trial 2907 finished with value: 0.94956292917352 and parameters: {'weight_class_0': 0.5530276903592267, 'weight_class_1': 7.279819317467419, 'weight_class_2': 7.578270673237669}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:24,790] Trial 2908 finished with value: 0.9483504249638338 and parameters: {'weight_class_0': 1.1719549095597777, 'weight_class_1': 8.527935197463014, 'weight_class_2': 7.560497734096229}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:24,844] Trial 2909 finished with value: 0.9485585093049208 and parameters: {'weight_class_0': 1.1086110460243794, 'weight_class_1': 8.476161103283458, 'weight_class_2': 7.565990022221047}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:24,944] Trial 2911 finished with value: 0.9486076785370496 and parameters: {'weight_class_0': 1.1031783958042731, 'weight_class_1': 8.513351120366812, 'weight_class_2': 7.550342402282197}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:24,954] Trial 2910 finished with value: 0.9485495182365581 and parameters: {'weight_class_0': 1.1334576659809448, 'weight_class_1': 8.526353354186627, 'weight_class_2': 7.829120885138123}. Best is trial 2787 with value: 0.9497743750090324.

Best trial: 2787. Best value: 0.949774:  97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍   | 2919/3000 [01:18<00:02, 29.59it/s]

[I 2026-07-10 16:13:24,962] Trial 2912 finished with value: 0.9483964768179577 and parameters: {'weight_class_0': 1.1527354620424102, 'weight_class_1': 8.498112382384544, 'weight_class_2': 7.516067572346237}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:25,010] Trial 2914 finished with value: 0.9484684143602946 and parameters: {'weight_class_0': 1.1500980958250622, 'weight_class_1': 8.548231883824073, 'weight_class_2': 7.744284618389338}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:25,020] Trial 2913 finished with value: 0.9496914660052461 and parameters: {'weight_class_0': 0.6275201449764215, 'weight_class_1': 8.527328364412758, 'weight_class_2': 7.816701742060463}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:25,025] Trial 2915 finished with value: 0.9485083902783761 and parameters: {'weight_class_0': 1.1384128127942135, 'weight_class_1': 8.461943524905196, 'weight_class_2': 7.784317003128401}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:25,069] Trial 2916 finished with value: 0.9496836383956538 and parameters: {'weight_class_0': 0.6448068668059178, 'weight_class_1': 7.322597288891904, 'weight_class_2': 7.803649849802107}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:25,073] Trial 2917 finished with value: 0.9496700455967947 and parameters: {'weight_class_0': 0.6226562812321671, 'weight_class_1': 8.572085969142075, 'weight_class_2': 6.856817494600026}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:25,118] Trial 2918 finished with value: 0.9497019059929852 and parameters: {'weight_class_0': 0.656026900499095, 'weight_class_1': 7.7373092032599375, 'weight_class_2': 7.769331345293844}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:25,168] Trial 2919 finished with value: 0.9456534149417296 and parameters: {'weight_class_0': 0.1660698439611395, 'weight_class_1': 8.820353991379699, 'weight_class_2': 7.811229101173786}. Best is trial 2787 with value: 0.9497743750090324.

[I 2026-07-10 16:13:25,175] Trial 2920 finished with value: 0.9451893859753845 and parameters: {'weight_class_0': 0.1533755082523876, 'weight_class_1': 8.84420221373995, 'weight_class_2': 6.9125136448435}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:25,216] Trial 2921 finished with value: 0.9497547663794969 and parameters: {'weight_class_0': 0.6504542765762933, 'weight_class_1': 8.754816070408447, 'weight_class_2': 7.8686261441701255}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:25,302] Trial 2922 finished with value: 0.9497432505734834 and parameters: {'weight_class_0': 0.69917762217519, 'weight_class_1': 8.739773363803792, 'weight_class_2': 7.877524078556898}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:25,384] Trial 2923 finished with value: 0.9496231817609441 and parameters: {'weight_class_0': 0.6054781181382278, 'weight_class_1': 7.675455041709099, 'weight_class_2': 7.851133972837806}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:25,404] Trial 2924 finished with value: 0.949684610929464 and parameters: {'weight_class_0': 0.6502960123644073, 'weight_class_1': 8.796710708653313, 'weight_class_2': 6.800346884651692}. Best is trial 2787 with value: 0.9497743750090324.

Best trial: 2787. Best value: 0.949774:  98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████   | 2931/3000 [01:18<00:02, 29.24it/s]

[I 2026-07-10 16:13:25,411] Trial 2925 finished with value: 0.9466104660562049 and parameters: {'weight_class_0': 0.19443770768555158, 'weight_class_1': 8.839435785033869, 'weight_class_2': 7.9721634926381295}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:25,464] Trial 2926 finished with value: 0.9462657177087789 and parameters: {'weight_class_0': 0.17958683453449198, 'weight_class_1': 8.819313259582371, 'weight_class_2': 7.413522181825858}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:25,480] Trial 2927 finished with value: 0.9459610357340692 and parameters: {'weight_class_0': 0.1682384341599315, 'weight_class_1': 8.799790957423635, 'weight_class_2': 6.863279322678691}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:25,497] Trial 2928 finished with value: 0.9438359880537246 and parameters: {'weight_class_0': 0.11854612011188992, 'weight_class_1': 7.684041779131375, 'weight_class_2': 6.799567370586219}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:25,540] Trial 2929 finished with value: 0.945275729112967 and parameters: {'weight_class_0': 0.1531941618168463, 'weight_class_1': 8.725293171184502, 'weight_class_2': 6.937306281708323}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:25,582] Trial 2930 finished with value: 0.9496458966582054 and parameters: {'weight_class_0': 0.649219346495298, 'weight_class_1': 8.755649411058629, 'weight_class_2': 8.24915892806114}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:25,614] Trial 2931 finished with value: 0.9492622980154003 and parameters: {'weight_class_0': 0.9437831082705124, 'weight_class_1': 8.75949906592271, 'weight_class_2': 8.303816264479915}. Best is trial 2787 with value: 0.9497743750090324.

[I 2026-07-10 16:13:25,640] Trial 2932 finished with value: 0.9492842834055336 and parameters: {'weight_class_0': 0.9253069060351695, 'weight_class_1': 8.71534279108002, 'weight_class_2': 8.308571374773969}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:25,665] Trial 2933 finished with value: 0.9492694962923656 and parameters: {'weight_class_0': 0.9441204367656377, 'weight_class_1': 8.800549154673211, 'weight_class_2': 8.324803609561359}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:25,699] Trial 2934 finished with value: 0.948872173427825 and parameters: {'weight_class_0': 0.38229320641241454, 'weight_class_1': 8.744514910427622, 'weight_class_2': 8.009634295231056}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:25,774] Trial 2935 finished with value: 0.9492380128601289 and parameters: {'weight_class_0': 0.9459372854872001, 'weight_class_1': 8.718741832984936, 'weight_class_2': 8.321426069742152}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:25,792] Trial 2936 finished with value: 0.9492623448387251 and parameters: {'weight_class_0': 0.9488625648138361, 'weight_class_1': 8.786103281027652, 'weight_class_2': 8.39807059784459}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:25,826] Trial 2937 finished with value: 0.9492725606275848 and parameters: {'weight_class_0': 0.913907343950984, 'weight_class_1': 8.765755121257401, 'weight_class_2': 8.168403420713917}. Best is trial 2787 with value: 0.9497743750090324.

Best trial: 2787. Best value: 0.949774:  98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 2944/3000 [01:19<00:02, 27.97it/s]

[I 2026-07-10 16:13:25,872] Trial 2939 finished with value: 0.9492581085174047 and parameters: {'weight_class_0': 0.9428746815599691, 'weight_class_1': 8.731214370713316, 'weight_class_2': 8.328670329311198}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:25,900] Trial 2938 finished with value: 0.9493361462568485 and parameters: {'weight_class_0': 0.9130969927376776, 'weight_class_1': 8.712367322604448, 'weight_class_2': 8.326816240782362}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:25,907] Trial 2940 finished with value: 0.9488699111773333 and parameters: {'weight_class_0': 0.3774906246347349, 'weight_class_1': 8.745793209076636, 'weight_class_2': 7.856664739589989}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:25,949] Trial 2941 finished with value: 0.9491911087003452 and parameters: {'weight_class_0': 0.95202516244643, 'weight_class_1': 8.668614284158384, 'weight_class_2': 8.121251640051277}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:26,012] Trial 2943 finished with value: 0.9490351327434708 and parameters: {'weight_class_0': 0.4098093822918216, 'weight_class_1': 8.33965515719505, 'weight_class_2': 7.992440108919258}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:26,042] Trial 2944 finished with value: 0.9484998267882632 and parameters: {'weight_class_0': 0.32756025779366765, 'weight_class_1': 8.347206183838288, 'weight_class_2': 8.506553787761218}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:26,063] Trial 2942 finished with value: 0.948955856721558 and parameters: {'weight_class_0': 0.40069316539655986, 'weight_class_1': 8.34965997681626, 'weight_class_2': 8.155654770863467}. Best is trial 2787 with value: 0.9497743750090324.

Best trial: 2787. Best value: 0.949774:  98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊  | 2950/3000 [01:19<00:01, 28.84it/s]

[I 2026-07-10 16:13:26,098] Trial 2945 finished with value: 0.9489803952970761 and parameters: {'weight_class_0': 0.42442594296369307, 'weight_class_1': 5.691471887988751, 'weight_class_2': 8.070230082458549}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:26,141] Trial 2946 finished with value: 0.9487757367241607 and parameters: {'weight_class_0': 0.36568166160520676, 'weight_class_1': 8.356299513343485, 'weight_class_2': 8.09622097841605}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:26,169] Trial 2947 finished with value: 0.9488129331918748 and parameters: {'weight_class_0': 0.3691126340949122, 'weight_class_1': 8.117808511632347, 'weight_class_2': 8.059228276962399}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:26,195] Trial 2948 finished with value: 0.9490118684670046 and parameters: {'weight_class_0': 0.40823307950701476, 'weight_class_1': 8.31971452134797, 'weight_class_2': 8.031984597559228}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:26,200] Trial 2949 finished with value: 0.9488538772543653 and parameters: {'weight_class_0': 0.37615658576555244, 'weight_class_1': 8.136825236816374, 'weight_class_2': 8.037229938261232}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:26,306] Trial 2951 finished with value: 0.948928251942597 and parameters: {'weight_class_0': 0.3942643747205039, 'weight_class_1': 8.357998288390757, 'weight_class_2': 8.081888875834343}. Best is trial 2787 with value: 0.9497743750090324.

Best trial: 2787. Best value: 0.949774:  99%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏ | 2957/3000 [01:19<00:01, 29.03it/s]

[I 2026-07-10 16:13:26,322] Trial 2952 finished with value: 0.9488089425419565 and parameters: {'weight_class_0': 0.36869464899553855, 'weight_class_1': 8.34392975018241, 'weight_class_2': 8.019271628304145}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:26,332] Trial 2950 finished with value: 0.948903058719823 and parameters: {'weight_class_0': 0.3811885679523266, 'weight_class_1': 8.104456822818054, 'weight_class_2': 7.981407251960672}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:26,342] Trial 2953 finished with value: 0.9488876802949435 and parameters: {'weight_class_0': 0.38466043731382593, 'weight_class_1': 8.323353193066042, 'weight_class_2': 8.07483101616686}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:26,437] Trial 2955 finished with value: 0.9496950741169892 and parameters: {'weight_class_0': 0.6862291017037543, 'weight_class_1': 8.11851264566711, 'weight_class_2': 8.053273212779246}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:26,451] Trial 2956 finished with value: 0.9455157307707829 and parameters: {'weight_class_0': 1.69537603107809, 'weight_class_1': 8.06629863731809, 'weight_class_2': 7.884319574234836}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:26,456] Trial 2954 finished with value: 0.9496961991769689 and parameters: {'weight_class_0': 0.6880905338365654, 'weight_class_1': 8.169936003604999, 'weight_class_2': 8.072412879928907}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:26,486] Trial 2957 finished with value: 0.9362359966240081 and parameters: {'weight_class_0': 2.7844812244857726, 'weight_class_1': 8.094316474799829, 'weight_class_2': 8.032586393256071}. Best is trial 2787 with value: 0.9497743750090324.

Best trial: 2787. Best value: 0.949774:  99%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍ | 2963/3000 [01:20<00:01, 27.92it/s]

[I 2026-07-10 16:13:26,555] Trial 2958 finished with value: 0.9497118607878964 and parameters: {'weight_class_0': 0.6754263451781184, 'weight_class_1': 8.150449203275947, 'weight_class_2': 7.726957229489823}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:26,597] Trial 2959 finished with value: 0.9497167231137209 and parameters: {'weight_class_0': 0.6920405238720462, 'weight_class_1': 8.132757161593476, 'weight_class_2': 7.7691679119328665}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:26,602] Trial 2960 finished with value: 0.9496843905678386 and parameters: {'weight_class_0': 0.6904509633450707, 'weight_class_1': 8.05650350593084, 'weight_class_2': 7.890221359551641}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:26,616] Trial 2961 finished with value: 0.9496667454746067 and parameters: {'weight_class_0': 0.681537856550687, 'weight_class_1': 8.085557521670088, 'weight_class_2': 7.896400811831013}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:26,737] Trial 2963 finished with value: 0.949702065360248 and parameters: {'weight_class_0': 0.7014817509863903, 'weight_class_1': 8.518730380294764, 'weight_class_2': 7.785057937973618}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:26,740] Trial 2962 finished with value: 0.9496605622681721 and parameters: {'weight_class_0': 0.7091985525328962, 'weight_class_1': 8.125587359945907, 'weight_class_2': 7.846027679651585}. Best is trial 2787 with value: 0.9497743750090324.

Best trial: 2787. Best value: 0.949774:  99%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋ | 2970/3000 [01:20<00:01, 29.81it/s]

[I 2026-07-10 16:13:26,788] Trial 2964 finished with value: 0.9472463902662871 and parameters: {'weight_class_0': 1.4074706668385595, 'weight_class_1': 8.051836718718336, 'weight_class_2': 7.782853277195332}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:26,805] Trial 2966 finished with value: 0.949710049276345 and parameters: {'weight_class_0': 0.6939981409353062, 'weight_class_1': 8.554166503502655, 'weight_class_2': 7.718830789190065}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:26,811] Trial 2965 finished with value: 0.945945942016381 and parameters: {'weight_class_0': 1.6672816326756998, 'weight_class_1': 8.54753495967775, 'weight_class_2': 7.77948580131272}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:26,855] Trial 2967 finished with value: 0.9497010593310318 and parameters: {'weight_class_0': 0.6991955683523674, 'weight_class_1': 8.572061743190364, 'weight_class_2': 7.660318505140939}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:26,910] Trial 2969 finished with value: 0.9472304410229917 and parameters: {'weight_class_0': 1.447601149891318, 'weight_class_1': 8.543938926294551, 'weight_class_2': 7.74900299234672}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:26,924] Trial 2968 finished with value: 0.947460141264025 and parameters: {'weight_class_0': 1.3989831937128168, 'weight_class_1': 8.569017405621004, 'weight_class_2': 7.741399840593092}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:26,974] Trial 2970 finished with value: 0.9496417158931342 and parameters: {'weight_class_0': 0.6070362731453883, 'weight_class_1': 8.551583746123955, 'weight_class_2': 7.721702447693043}. Best is trial 2787 with value: 0.9497743750090324.

Best trial: 2787. Best value: 0.949774:  99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ | 2977/3000 [01:20<00:00, 28.67it/s]

[I 2026-07-10 16:13:27,043] Trial 2971 finished with value: 0.9496167004493876 and parameters: {'weight_class_0': 0.5794451464926249, 'weight_class_1': 8.570521094481597, 'weight_class_2': 7.708590697850669}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:27,046] Trial 2972 finished with value: 0.949622814578627 and parameters: {'weight_class_0': 0.5948712096480646, 'weight_class_1': 8.528927497289423, 'weight_class_2': 7.75764405717527}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:27,055] Trial 2973 finished with value: 0.9496325329080184 and parameters: {'weight_class_0': 0.5872461632922716, 'weight_class_1': 8.45168099908025, 'weight_class_2': 7.729166489526456}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:27,154] Trial 2975 finished with value: 0.9494323727965628 and parameters: {'weight_class_0': 0.8421294901890064, 'weight_class_1': 8.563703880772112, 'weight_class_2': 7.662983143080262}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:27,163] Trial 2974 finished with value: 0.9496212865204879 and parameters: {'weight_class_0': 0.5641692648851371, 'weight_class_1': 8.538731365909337, 'weight_class_2': 7.692849009226052}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:27,191] Trial 2976 finished with value: 0.9493643366140496 and parameters: {'weight_class_0': 0.5622693585246463, 'weight_class_1': 7.789921420815573, 'weight_class_2': 8.574459297461202}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:27,237] Trial 2978 finished with value: 0.8802993213638258 and parameters: {'weight_class_0': 7.341555495157961, 'weight_class_1': 7.790221319432174, 'weight_class_2': 7.615056883739063}. Best is trial 2787 with value: 0.9497743750090324.

Best trial: 2787. Best value: 0.949774:  99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎| 2983/3000 [01:20<00:00, 27.77it/s]

[I 2026-07-10 16:13:27,247] Trial 2977 finished with value: 0.9495565495296746 and parameters: {'weight_class_0': 0.5614606258703947, 'weight_class_1': 7.790345083841193, 'weight_class_2': 7.65402645102576}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:27,269] Trial 2979 finished with value: 0.9496111829338645 and parameters: {'weight_class_0': 0.5850772387298694, 'weight_class_1': 7.794958139471504, 'weight_class_2': 7.522230257987794}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:27,326] Trial 2980 finished with value: 0.9496227832834422 and parameters: {'weight_class_0': 0.5781294267688949, 'weight_class_1': 7.824824635607526, 'weight_class_2': 7.542015055280807}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:27,355] Trial 2981 finished with value: 0.9493056485376664 and parameters: {'weight_class_0': 0.8671933554880158, 'weight_class_1': 8.417609305914013, 'weight_class_2': 7.519867647929745}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:27,423] Trial 2983 finished with value: 0.949183574400139 and parameters: {'weight_class_0': 0.8778968549889588, 'weight_class_1': 7.668078854600918, 'weight_class_2': 7.510632819099284}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:27,438] Trial 2982 finished with value: 0.9492411136897413 and parameters: {'weight_class_0': 0.8492374944365504, 'weight_class_1': 7.654789674558449, 'weight_class_2': 7.490110684104707}. Best is trial 2787 with value: 0.9497743750090324.

Best trial: 2787. Best value: 0.949774: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌| 2990/3000 [01:20<00:00, 27.70it/s]

[I 2026-07-10 16:13:27,503] Trial 2984 finished with value: 0.9491970237759141 and parameters: {'weight_class_0': 0.8641247779795299, 'weight_class_1': 7.75479331650493, 'weight_class_2': 7.523348725792318}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:27,509] Trial 2985 finished with value: 0.9491657905357366 and parameters: {'weight_class_0': 0.8837413543448804, 'weight_class_1': 7.812228595215487, 'weight_class_2': 7.510248662472582}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:27,575] Trial 2987 finished with value: 0.9488888572485962 and parameters: {'weight_class_0': 0.9472061929879934, 'weight_class_1': 7.7858652635010035, 'weight_class_2': 7.488315591699197}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:27,589] Trial 2986 finished with value: 0.9489918589850079 and parameters: {'weight_class_0': 0.9230727638332521, 'weight_class_1': 7.685425704303277, 'weight_class_2': 7.479948295080044}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:27,600] Trial 2988 finished with value: 0.9489440253185103 and parameters: {'weight_class_0': 0.9678529931493569, 'weight_class_1': 8.309673063396094, 'weight_class_2': 7.48931038085924}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:27,662] Trial 2989 finished with value: 0.9489914165060344 and parameters: {'weight_class_0': 0.945246798291766, 'weight_class_1': 8.278684076935368, 'weight_class_2': 7.505801367488294}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:27,705] Trial 2990 finished with value: 0.9490531905209498 and parameters: {'weight_class_0': 0.924827149934687, 'weight_class_1': 8.34489163731183, 'weight_class_2': 7.426499111138151}. Best is trial 2787 with value: 0.9497743750090324.

Best trial: 2787. Best value: 0.949774: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3000/3000 [01:21<00:00, 36.99it/s]

[I 2026-07-10 16:13:27,726] Trial 2992 finished with value: 0.9488574185707193 and parameters: {'weight_class_0': 1.0047401052167664, 'weight_class_1': 8.287895722793179, 'weight_class_2': 7.493497356744003}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:27,734] Trial 2991 finished with value: 0.948860908260765 and parameters: {'weight_class_0': 0.9858064453007207, 'weight_class_1': 8.287015037234713, 'weight_class_2': 7.451002957376147}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:27,769] Trial 2993 finished with value: 0.949207097424455 and parameters: {'weight_class_0': 0.9886949595153631, 'weight_class_1': 8.319839978569364, 'weight_class_2': 9.35219841892416}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:27,793] Trial 2994 finished with value: 0.9488336596566381 and parameters: {'weight_class_0': 1.0193689007547628, 'weight_class_1': 8.314459451398513, 'weight_class_2': 7.424040791576996}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:27,817] Trial 2995 finished with value: 0.9487404760129318 and parameters: {'weight_class_0': 1.037276538945021, 'weight_class_1': 8.301514465896814, 'weight_class_2': 7.444536619071148}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:27,829] Trial 2996 finished with value: 0.9487518065328397 and parameters: {'weight_class_0': 1.0408181118421138, 'weight_class_1': 8.307295942178643, 'weight_class_2': 7.398332574478979}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:27,837] Trial 2997 finished with value: 0.9436072614569849 and parameters: {'weight_class_0': 0.1270877396579651, 'weight_class_1': 8.39840099120526, 'weight_class_2': 7.409507309271271}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:27,850] Trial 2999 finished with value: 0.9452417106759189 and parameters: {'weight_class_0': 0.1474772147524004, 'weight_class_1': 8.240678754748348, 'weight_class_2': 7.336363730109616}. Best is trial 2787 with value: 0.9497743750090324.
[I 2026-07-10 16:13:27,865] Trial 2998 finished with value: 0.945705994149387 and parameters: {'weight_class_0': 0.1582603517915983, 'weight_class_1': 8.362152609959567, 'weight_class_2': 7.340796509794658}. Best is trial 2787 with value: 0.9497743750090324.

Best trial score:
0.9497743750090324

Best params:
{'weight_class_0': 0.614844576364072, 'weight_class_1': 8.258589181322845, 'weight_class_2': 7.48963067756502}

In [9]:
weights = np.array([study.best_params['weight_class_0'], study.best_params['weight_class_1'], study.best_params['weight_class_2']])
weighted_probas = X_test.loc[:, cols_use].to_numpy() * weights

pred = np.argmax(weighted_probas, axis=1)

In [10]:
sub_labels = label_encoder.inverse_transform(pred)

# Submission

In [11]:
submission = pd.read_csv('../data/submission/sample_submission.csv')
submission['health_condition'] = sub_labels

submission.to_csv('../data/submission/submission_from_5.1.5_lightgbm_submission.csv', index=False)

In [12]:
submission.head()

       id health_condition
0  690088        unhealthy
1  690089        unhealthy
2  690090          at-risk
3  690091          at-risk
4  690092        unhealthy